ps2sdk: ee/rpc/ahx/include/ahx_rpc.h File Reference
ahx_rpc.h File Reference
Macros
#define AHX_IRX 0xC001D0E
#define AHX_INIT 0x01
#define AHX_PLAY 0x02
#define AHX_PAUSE 0x03
#define AHX_QUIT 0x04
#define AHX_LOADSONG 0x05
#define AHX_SETVOLUME 0x06
#define AHX_SETBOOST 0x07
#define AHX_OVERSAMPLING 0x08
#define AHX_SUBSONG 0x09
Functions
int AHX_Init ()
int AHX_LoadSongBuffer (char *songdata, int songsize)
int AHX_LoadSong (char *filename)
int AHX_SubSong (int songNo)
int AHX_SetVolume (int volumePercentage)
int AHX_SetBoost (int boostValue)
int AHX_ToggleOversampling ()
int AHX_Quit ()
int AHX_Play ()
int AHX_Pause ()
Detailed Description
AHX EE-side RPC code.
Definition in file ahx_rpc.h.
Macro Definition Documentation
AHX_INIT
#define AHX_INIT 0x01
Definition at line 20 of file ahx_rpc.h.
AHX_IRX
#define AHX_IRX 0xC001D0E
Definition at line 19 of file ahx_rpc.h.
AHX_LOADSONG
#define AHX_LOADSONG 0x05
Definition at line 24 of file ahx_rpc.h.
AHX_OVERSAMPLING
#define AHX_OVERSAMPLING 0x08
Definition at line 27 of file ahx_rpc.h.
AHX_PAUSE
#define AHX_PAUSE 0x03
Definition at line 22 of file ahx_rpc.h.
AHX_PLAY
#define AHX_PLAY 0x02
Definition at line 21 of file ahx_rpc.h.
AHX_QUIT
#define AHX_QUIT 0x04
Definition at line 23 of file ahx_rpc.h.
AHX_SETBOOST
#define AHX_SETBOOST 0x07
Definition at line 26 of file ahx_rpc.h.
AHX_SETVOLUME
#define AHX_SETVOLUME 0x06
Definition at line 25 of file ahx_rpc.h.
AHX_SUBSONG
#define AHX_SUBSONG 0x09
Definition at line 28 of file ahx_rpc.h.
Function Documentation
AHX_Init()
int AHX_Init ()
AHX Init
Sends a call the the loaded AHX IRX, telling it to set things up ready for loading a song.
Definition at line 48 of file ahx_rpc.c.
 {
         int i;
         // struct t_SifDmaTransfer sdt;
         // if already init'd, exit
         if (ahx_init_done) return 0;
         // bind rpc
         while(1){
                 if (SifBindRpc( &cd0, AHX_IRX, 0) < 0) return -1; // bind error
                 if (cd0.server != 0) break;
         i = 0x10000;
         while(i--);
         }
         SifCallRpc(&cd0,AHX_INIT,0,(void*)(&sbuff[0]),64,(void*)(&sbuff[0]),64,NULL,NULL);
         songbuffer_addr = (char*)sbuff[1];
         // set flag, init done
         ahx_init_done = 1;
         return 0;
 }
References AHX_INIT, ahx_init_done, AHX_IRX, cd0, NULL, sbuff, SifBindRpc(), SifCallRpc(), and songbuffer_addr.
AHX_LoadSong()
int AHX_LoadSong (char * filename)
AHX LongSongBuffer
This loads a song from disk etc. It loads the songdata into memory and passes it to LongSongBuffer.
Returns
number of subsongs.
Definition at line 191 of file ahx_rpc.c.
 {
         int fd, fdSize;
         char* buffer;
         fd = open(filename, O_RDONLY);
         if(fd < 0)
         {
                  printf("ERROR LOADING SONG\n");
                  return -1;
         }
         fdSize = lseek(fd, 0, SEEK_END);
         lseek(fd, 0, SEEK_SET);
         buffer = malloc(fdSize);
         if(!buffer)
         {
                  printf("ERROR ALLOCATING SONG MEMORY SONG\n");
                  return -1;
         }
         read(fd, buffer, fdSize);
         close(fd);
         return AHX_LoadSongBuffer(buffer, fdSize);
 }
References AHX_LoadSongBuffer(), and buffer.
AHX_LoadSongBuffer()
int AHX_LoadSongBuffer (char * songdata, int songsize)
AHX LongSongBuffer
This loads a song from a buffer in memory. It copies [songsize] bytes from [songdata] to the IOP memory song buffer.
Returns
number of subsongs.
Definition at line 167 of file ahx_rpc.c.
 {
         int i;
         // write song data to IOP song buffer
         iop_readwrite(songbuffer_addr, songdata, songsize, 0);
         while(1){
                 if (SifBindRpc( &cd0, AHX_IRX, 0) < 0) return -1;
                 if (cd0.server != 0) break;
         i = 0x10000;
         while(i--);
         }
         // set oversample and boost
         sbuff[0] = (unsigned)songsize;
         // call rpc
         SifCallRpc(&cd0,AHX_LOADSONG,0,(void*)(&sbuff[0]),64,(void*)(&sbuff[0]),64,NULL,NULL);
         // return number of sub-songs
         return (int)sbuff[1];
 }
References AHX_IRX, AHX_LOADSONG, cd0, iop_readwrite(), NULL, sbuff, SifBindRpc(), SifCallRpc(), and songbuffer_addr.
Referenced by AHX_LoadSong().
AHX_Pause()
int AHX_Pause ()
AHX Pause
Sends a call the the loaded AHX IRX, telling it to pause the currently loaded song.
Definition at line 86 of file ahx_rpc.c.
 {
         int i;
         while(1){
                 if (SifBindRpc( &cd0, AHX_IRX, 0) < 0) return -1;
                 if (cd0.server != 0) break;
         i = 0x10000;
         while(i--);
         }
         SifCallRpc(&cd0,AHX_PAUSE,0,(void*)(&sbuff[0]),64,(void*)(&sbuff[0]),64,NULL,NULL);
         return 0;
 }
References AHX_IRX, AHX_PAUSE, cd0, NULL, sbuff, SifBindRpc(), and SifCallRpc().
AHX_Play()
int AHX_Play ()
AHX Play
Sends a call the the loaded AHX IRX, telling it to play the currently loaded song.
Definition at line 73 of file ahx_rpc.c.
 {
         int i;
         while(1){
                 if (SifBindRpc( &cd0, AHX_IRX, 0) < 0) return -1;
                 if (cd0.server != 0) break;
         i = 0x10000;
         while(i--);
         }
         SifCallRpc(&cd0,AHX_PLAY,0,(void*)(&sbuff[0]),64,(void*)(&sbuff[0]),64,NULL,NULL);
         return 0;
 }
References AHX_IRX, AHX_PLAY, cd0, NULL, sbuff, SifBindRpc(), and SifCallRpc().
AHX_Quit()
int AHX_Quit ()
AHX Quit
Sends a call the the loaded AHX IRX, telling it to quit. This frees up IOP mem, quites threads, deletes semaphores and all that jazz....
Definition at line 154 of file ahx_rpc.c.
 {
         int i;
         while(1){
                 if (SifBindRpc( &cd0, AHX_IRX, 0) < 0) return -1;
                 if (cd0.server != 0) break;
         i = 0x10000;
         while(i--);
         }
         SifCallRpc(&cd0,AHX_QUIT,0,(void*)(&sbuff[0]),64,(void*)(&sbuff[0]),64,NULL,NULL);
         return 0;
 }
References AHX_IRX, AHX_QUIT, cd0, NULL, sbuff, SifBindRpc(), and SifCallRpc().
AHX_SetBoost()
int AHX_SetBoost (int boostValue)
AHX Set Boost
Sends a call the the loaded AHX IRX, telling it to change the output boost value. Boost value multiplies the level of the output for the AHX Mixer. A boost value of 1 is twice as load as a boost value of 0. A boost value of 3 is twice as load as 2 etc etc (ala DB)
Definition at line 127 of file ahx_rpc.c.
 {
         int i;
         while(1){
                 if (SifBindRpc( &cd0, AHX_IRX, 0) < 0) return -1;
                 if (cd0.server != 0) break;
         i = 0x10000;
         while(i--);
         }
         sbuff[0] = (unsigned)boostValue;
         SifCallRpc(&cd0,AHX_SETBOOST,0,(void*)(&sbuff[0]),64,(void*)(&sbuff[0]),64,NULL,NULL);
         return 0;
 }
References AHX_IRX, AHX_SETBOOST, cd0, NULL, sbuff, SifBindRpc(), and SifCallRpc().
AHX_SetVolume()
int AHX_SetVolume (int volumePercentage)
AHX Set Volume
Sends a call the the loaded AHX IRX, telling it to change the output volume of the SPU2. volumePercentage argument can range from 0 (0% silence) to 100 (100% full volume)
Definition at line 113 of file ahx_rpc.c.
 {
         int i;
         while(1){
                 if (SifBindRpc( &cd0, AHX_IRX, 0) < 0) return -1;
                 if (cd0.server != 0) break;
         i = 0x10000;
         while(i--);
         }
         sbuff[0] = (unsigned)volumePercentage;
         SifCallRpc(&cd0,AHX_QUIT,0,(void*)(&sbuff[0]),64,(void*)(&sbuff[0]),64,NULL,NULL);
         return 0;
 }
References AHX_IRX, AHX_QUIT, cd0, NULL, sbuff, SifBindRpc(), and SifCallRpc().
AHX_SubSong()
int AHX_SubSong (int songNo)
AHX Play Subsong
Sends a call the the loaded AHX IRX, telling it to load subsong (songNo). You can determine the number of subsongs by checking the values returned by AHX_LoadSong() and AHX_LoadSongBuffer();
Definition at line 99 of file ahx_rpc.c.
 {
         int i;
         while(1){
                 if (SifBindRpc( &cd0, AHX_IRX, 0) < 0) return -1;
                 if (cd0.server != 0) break;
         i = 0x10000;
         while(i--);
         }
         sbuff[0] = (unsigned)songNo;
         SifCallRpc(&cd0,AHX_PAUSE,0,(void*)(&sbuff[0]),64,(void*)(&sbuff[0]),64,NULL,NULL);
         return 0;
 }
References AHX_IRX, AHX_PAUSE, cd0, NULL, sbuff, SifBindRpc(), and SifCallRpc().
AHX_ToggleOversampling()
int AHX_ToggleOversampling ()
AHX Toggle Oversampling
Switches oversampling on/off. Oversampling produces a smoother output sound but uses a lot more CPU power. It sounds nasty/slows down for a lot of songs - use with caution (or not at all)
Definition at line 141 of file ahx_rpc.c.
 {
         int i;
         while(1){
                 if (SifBindRpc( &cd0, AHX_IRX, 0) < 0) return -1;
                 if (cd0.server != 0) break;
         i = 0x10000;
         while(i--);
         }
         SifCallRpc(&cd0,AHX_OVERSAMPLING,0,(void*)(&sbuff[0]),64,(void*)(&sbuff[0]),64,NULL,NULL);
         return 0;
 }
References AHX_IRX, AHX_OVERSAMPLING, cd0, NULL, sbuff, SifBindRpc(), and SifCallRpc().