ps2sdk: ee/kernel/src/alarm.c File Reference
alarm.c File Reference
#include <kernel.h>
#include <stdio.h>
Data Structures
struct SyscallData
Functions
void InitAlarm (void)
Variables
static const struct SyscallData SysEntry []
unsigned char srcfile []
unsigned int size_srcfile
unsigned char eenull []
unsigned int size_eenull
Detailed Description
EE kernel update for alarm functions ReleaseAlarm is unable to correctly release alarm in all CEX/DEX EE kernels. This also includes code for dealing with the restriction on the COP0 EIE bit becoming set to 0 when an interrupt occurs before interrupts can be disabled.
Definition in file alarm.c.
Function Documentation
InitAlarm()
void InitAlarm (void)
Definition at line 43 of file alarm.c.
 {
         int i;
         setup(SysEntry[0].syscall, SysEntry[0].function);
         Copy((void*)0x80076000, srcfile, size_srcfile);
         Copy((void*)0x00082000, eenull, size_eenull);
         FlushCache(0);
         FlushCache(2);
         setup(SysEntry[1].syscall, SysEntry[1].function);
         for(i=2; i<8; i++)
                 setup(SysEntry[i].syscall, GetEntryAddress(SysEntry[i].syscall));
 }
References Copy(), eenull, FlushCache(), GetEntryAddress(), setup(), size_eenull, size_srcfile, srcfile, SyscallData::syscall, and SysEntry.
Variable Documentation
eenull
unsigned char eenull[] extern
Referenced by InitAlarm().
size_eenull
unsigned int size_eenull extern
Referenced by InitAlarm().
size_srcfile
unsigned int size_srcfile extern
Referenced by InitAlarm().
srcfile
unsigned char srcfile[] extern
Referenced by InitAlarm().
SysEntry
const struct SyscallData SysEntry[] static
Initial value:
={
        {0x5A, &kCopy},
        {0x5B, (void*)0x80076000},
        {0xFC, NULL},
        {0xFD, NULL},
        {0xFE, NULL},
        {0xFF, NULL},
        {0x12C, NULL},
        {0x08, NULL},
}
Definition at line 1 of file alarm.c.
Referenced by InitAlarm().