ps2sdk: ee/rpc/audsrv/src/audsrv_rpc.c File Reference
audsrv_rpc.c File Reference
#include <stdio.h>
#include <kernel.h>
#include <sifrpc.h>
#include <tamtypes.h>
#include <string.h>
#include <iopheap.h>
#include <audsrv.h>
#include "audsrv_rpc.h"
Macros
#define MIN(a, b) ((a) <= (b)) ? (a) : (b)
Functions
static void set_error (int err)
int audsrv_get_error ()
static int call_rpc_1 (int func, int arg)
static int call_rpc_2 (int func, int arg1, int arg2)
int audsrv_quit ()
int audsrv_set_format (struct audsrv_fmt_t *fmt)
int audsrv_wait_audio (int bytes)
int audsrv_set_volume (int volume)
int audsrv_play_cd (int track)
int audsrv_play_sectors (int start, int end)
int audsrv_stop_cd ()
int audsrv_get_cdpos ()
int audsrv_get_trackpos ()
int audsrv_get_numtracks ()
int audsrv_get_track_offset (int track)
int audsrv_pause_cd ()
int audsrv_resume_cd ()
int audsrv_get_cd_type ()
int audsrv_get_cd_status ()
int audsrv_play_audio (const char *chunk, int bytes)
int audsrv_stop_audio ()
static void * audsrv_ee_rpc_handler (int fnum, void *buffer, int len)
static void rpc_server_thread (void *arg)
int audsrv_init ()
int audsrv_adpcm_init ()
int audsrv_adpcm_set_volume (int ch, int volume)
int audsrv_load_adpcm (audsrv_adpcm_t *adpcm, void *buffer, int size)
int audsrv_ch_play_adpcm (int ch, audsrv_adpcm_t *adpcm)
const char * audsrv_get_error_string ()
int audsrv_on_cdda_stop (audsrv_callback_t cb, void *arg)
int audsrv_on_fillbuf (int amount, audsrv_callback_t cb, void *arg)
Variables
static struct t_SifRpcClientData cd0
static unsigned int sbuff [4096]
static struct t_SifRpcDataQueue cb_queue
static struct t_SifRpcServerData cb_srv
static unsigned char rpc_server_stack [0x1800]
void * _gp
static int initialized = 0
static int rpc_server_thread_id
static int audsrv_error = AUDSRV_ERR_NOERROR
static int completion_sema
static audsrv_callback_t on_cdda_stop = NULL
static void * on_cdda_stop_arg = NULL
static audsrv_callback_t on_fillbuf = NULL
static void * on_fillbuf_arg = NULL
static const unsigned short vol_values [26]
Detailed Description
audsrv EE-side RPC code.
Definition in file audsrv_rpc.c.
Macro Definition Documentation
MIN
#define MIN (a, b) ((a) <= (b)) ? (a) : (b)
Definition at line 26 of file audsrv_rpc.c.
Function Documentation
audsrv_adpcm_init()
int audsrv_adpcm_init ()
Initializes adpcm unit of audsrv
Returns
zero on success, negative value on error
Frees up all memory taken by samples, and stops all voices from being played. This can be called multiple times
Definition at line 362 of file audsrv_rpc.c.
 {
         return call_rpc_1(AUDSRV_INIT_ADPCM, 0);
 }
References AUDSRV_INIT_ADPCM, and call_rpc_1().
Referenced by main().
audsrv_adpcm_set_volume()
int audsrv_adpcm_set_volume (int ch, int vol)
Sets output volume for the specified voice channel.
Parameters
ch Voice channel ID
vol volume in percentage (0-100)
Returns
0 on success, negative otherwise
Definition at line 367 of file audsrv_rpc.c.
 {
         if (volume > MAX_VOLUME)
         {
                 volume = MAX_VOLUME;
         }
         else if (volume < MIN_VOLUME)
         {
                 volume = MIN_VOLUME;
         }
         return call_rpc_2(AUDSRV_ADPCM_SET_VOLUME, ch, vol_values[volume/4]);
 }
References AUDSRV_ADPCM_SET_VOLUME, call_rpc_2(), MAX_VOLUME, MIN_VOLUME, and vol_values.
Referenced by main().
audsrv_ch_play_adpcm()
int audsrv_ch_play_adpcm (int ch, audsrv_adpcm_t * adpcm)
Plays an adpcm sample already uploaded with audsrv_load_adpcm()
Parameters
ch channel identifier. Specifies one of the 24 voice channel to play the ADPCM channel on.
id sample identifier, as specified in load()
Returns
zero on success, negative value on error
When ch is set to an invalid channel ID, the sample will be played in an unoccupied channel. If all 24 channels are used, then -AUDSRV_ERR_NO_MORE_CHANNELS is returned. When ch is set to a valid channel ID, -AUDSRV_ERR_NO_MORE_CHANNELS is returned if the channel is currently in use. Trying to play a sample which is unavailable will result in -AUDSRV_ERR_ARGS
Definition at line 432 of file audsrv_rpc.c.
 {
         /* on iop side, the sample id is like the pointer on ee side */
         return call_rpc_2(AUDSRV_PLAY_ADPCM, ch, (u32)adpcm);
 }
References AUDSRV_PLAY_ADPCM, and call_rpc_2().
Referenced by main().
audsrv_ee_rpc_handler()
static void* audsrv_ee_rpc_handler (int fnum, void * buffer, int len) static
Definition at line 271 of file audsrv_rpc.c.
 {
         switch(fnum){
                 case AUDSRV_FILLBUF_CALLBACK:
                         if (on_fillbuf != NULL)
                                 on_fillbuf(on_fillbuf_arg);
                         break;
                 case AUDSRV_CDDA_CALLBACK:
                         if (on_cdda_stop != NULL)
                                 on_cdda_stop(on_cdda_stop_arg);
                         break;
         }
         return buffer;
 }
References AUDSRV_CDDA_CALLBACK, AUDSRV_FILLBUF_CALLBACK, buffer, NULL, on_cdda_stop, on_cdda_stop_arg, on_fillbuf, and on_fillbuf_arg.
Referenced by rpc_server_thread().
audsrv_get_cd_status()
int audsrv_get_cd_status ()
Returns the status of the CD tray (open, closed, seeking etc.)
Returns
value as defined in libcdvd, negative on error
Definition at line 223 of file audsrv_rpc.c.
 {
         return call_rpc_1(AUDSRV_GET_CD_STATUS, 0);
 }
References AUDSRV_GET_CD_STATUS, and call_rpc_1().
audsrv_get_cd_type()
int audsrv_get_cd_type ()
Returns the type of disc currently in tray
Returns
value as defined in libcdvd, negative on error
Definition at line 218 of file audsrv_rpc.c.
 {
         return call_rpc_1(AUDSRV_GET_CD_TYPE, 0);
 }
References AUDSRV_GET_CD_TYPE, and call_rpc_1().
audsrv_get_cdpos()
int audsrv_get_cdpos ()
Returns the current playing sector
Returns
sector number
CDDA type discs have sector size of 2352 bytes. There are 75 such sectors per second.
Definition at line 188 of file audsrv_rpc.c.
 {
         return call_rpc_1(AUDSRV_GET_CDPOS, 0);
 }
References AUDSRV_GET_CDPOS, and call_rpc_1().
Referenced by main().
audsrv_get_error()
int audsrv_get_error ()
Returns the last error audsrv raised
Returns
error code
Definition at line 66 of file audsrv_rpc.c.
 {
         return audsrv_error;
 }
References audsrv_error.
Referenced by audsrv_get_error_string().
audsrv_get_error_string()
const char* audsrv_get_error_string ()
Translates audsrv_get_error() response to readable string
Returns
string representation of error code
Definition at line 438 of file audsrv_rpc.c.
 {
         switch(audsrv_get_error())
         {
                 case AUDSRV_ERR_NOERROR:
                 return "No error";
                 case AUDSRV_ERR_NOT_INITIALIZED:
                 return "Not initialized";
                 case AUDSRV_ERR_OUT_OF_MEMORY:
                 return "Out of IOP memory";
                 case AUDSRV_ERR_RPC_FAILED:
                 return "RPC operation failed";
                 case AUDSRV_ERR_FORMAT_NOT_SUPPORTED:
                 return "Format not supported";
                 case AUDSRV_ERR_NO_DISC:
                 return "No disc in drive";
         }
         return "Unknown error";
 }
References AUDSRV_ERR_FORMAT_NOT_SUPPORTED, AUDSRV_ERR_NO_DISC, AUDSRV_ERR_NOERROR, AUDSRV_ERR_NOT_INITIALIZED, AUDSRV_ERR_OUT_OF_MEMORY, AUDSRV_ERR_RPC_FAILED, and audsrv_get_error().
Referenced by main().
audsrv_get_numtracks()
int audsrv_get_numtracks ()
Returns the number of tracks available on the CD in tray
Returns
positive track count, or negative error status code
Definition at line 198 of file audsrv_rpc.c.
 {
         return call_rpc_1(AUDSRV_GET_NUMTRACKS, 0);
 }
References AUDSRV_GET_NUMTRACKS, and call_rpc_1().
Referenced by main().
audsrv_get_track_offset()
int audsrv_get_track_offset (int track)
Returns the first sector for the given track
Parameters
track track index, must be between 1 and the trackcount
Returns
sector number, or negative status code
Definition at line 203 of file audsrv_rpc.c.
 {
         return call_rpc_1(AUDSRV_GET_TRACKOFFSET, track);
 }
References AUDSRV_GET_TRACKOFFSET, and call_rpc_1().
Referenced by main().
audsrv_get_trackpos()
int audsrv_get_trackpos ()
Returns the current playing sector, relative to track
Returns
sector number
There are 75 sectors a second. To translate this position to mm:ss:ff use the following: mm = sector / (75*60) ss = (sector / 75) % 60 ff = sector % 75
where ff is the frame number, 1/75th of a second.
Definition at line 193 of file audsrv_rpc.c.
 {
         return call_rpc_1(AUDSRV_GET_TRACKPOS, 0);
 }
References AUDSRV_GET_TRACKPOS, and call_rpc_1().
Referenced by main().
audsrv_init()
int audsrv_init ()
Initializes audsrv library
Returns
error code
Definition at line 296 of file audsrv_rpc.c.
 {
         ee_sema_t compSema;
         ee_thread_t rpcThread;
         int ret;
         if (initialized)
         {
                 /* already done */
                 return 0;
         }
         memset(&cd0, '\0', sizeof(cd0));
         while (1)
         {
                 if (SifBindRpc(&cd0, AUDSRV_IRX, 0) < 0)
                 {
                         set_error(AUDSRV_ERR_RPC_FAILED);
                         return -1;
                 }
                 if (cd0.server != 0)
                 {
                         break;
                 }
                 nopdelay();
         }
         compSema.init_count = 1;
         compSema.max_count = 1;
         compSema.option = 0;
         completion_sema = CreateSema(&compSema);
         if (completion_sema < 0)
         {
                 set_error(AUDSRV_ERR_FAILED_TO_CREATE_SEMA);
                 return -1;
         }
         /* Create RPC server */
         rpcThread.attr = 0;
         rpcThread.option = 0;
         rpcThread.func = &rpc_server_thread;
         rpcThread.stack = rpc_server_stack;
         rpcThread.stack_size = sizeof(rpc_server_stack);
         rpcThread.gp_reg = &_gp;
         rpcThread.initial_priority = 0x60;
         rpc_server_thread_id = CreateThread(&rpcThread);
         StartThread(rpc_server_thread_id, NULL);
         SifCallRpc(&cd0, AUDSRV_INIT, 0, sbuff, 64, sbuff, 64, NULL, NULL);
         ret = sbuff[0];
         if (ret != 0)
         {
                 set_error(ret);
                 return ret;
         }
         /* initialize IOP heap (for adpcm samples) */
         SifInitIopHeap();
         set_error(AUDSRV_ERR_NOERROR);
         return AUDSRV_ERR_NOERROR;
 }
References _gp, ee_thread_t::attr, AUDSRV_ERR_FAILED_TO_CREATE_SEMA, AUDSRV_ERR_NOERROR, AUDSRV_ERR_RPC_FAILED, AUDSRV_INIT, AUDSRV_IRX, cd0, completion_sema, compSema, CreateSema(), CreateThread(), ee_thread_t::func, ee_thread_t::gp_reg, ee_sema_t::init_count, ee_thread_t::initial_priority, initialized, ee_sema_t::max_count, nopdelay(), NULL, ee_sema_t::option, ee_thread_t::option, rpc_server_stack, rpc_server_thread(), rpc_server_thread_id, sbuff, set_error(), SifBindRpc(), SifCallRpc(), SifInitIopHeap(), ee_thread_t::stack, ee_thread_t::stack_size, and StartThread().
Referenced by main().
audsrv_load_adpcm()
int audsrv_load_adpcm (audsrv_adpcm_t * adpcm, void * buffer, int size)
Uploads a sample to SPU2 memory
Parameters
adpcm adpcm descriptor structure
buffer pointer to adpcm sample
size size of sample (including the header)
Returns
zero on success, negative error code otherwise
Definition at line 381 of file audsrv_rpc.c.
 {
         void* iop_addr;
         SifDmaTransfer_t sifdma;
         int id, ret;
         iop_addr = SifAllocIopHeap(size);
         if (iop_addr == 0)
         {
                 return -AUDSRV_ERR_OUT_OF_MEMORY;
         }
         sifdma.src = buffer;
         sifdma.dest = iop_addr;
         sifdma.size = size;
         sifdma.attr = 0;
         /* send by dma */
         while((id = SifSetDma(&sifdma, 1)) == 0);
         while(SifDmaStat(id) >= 0);
         WaitSema(completion_sema);
         sbuff[0] = (int)iop_addr;
         sbuff[1] = size;
         sbuff[2] = (int)adpcm; /* use as id */
         SifCallRpc(&cd0, AUDSRV_LOAD_ADPCM, 0, sbuff, 12, sbuff, 16, NULL, NULL);
         if(sbuff[0] != 0)
         {
                 adpcm->buffer = 0;
                 ret = sbuff[0];
         }
         else
         {
                 adpcm->buffer = buffer;
                 adpcm->size = size;
                 adpcm->pitch = sbuff[1];
                 adpcm->loop = sbuff[2];
                 adpcm->channels = sbuff[3];
                 ret = AUDSRV_ERR_NOERROR;
         }
         SignalSema(completion_sema);
         SifFreeIopHeap(iop_addr);
         return ret;
 }
References SifDmaTransfer_t::attr, AUDSRV_ERR_NOERROR, AUDSRV_ERR_OUT_OF_MEMORY, AUDSRV_LOAD_ADPCM, buffer, audsrv_adpcm_t::buffer, cd0, audsrv_adpcm_t::channels, completion_sema, SifDmaTransfer_t::dest, audsrv_adpcm_t::loop, NULL, audsrv_adpcm_t::pitch, sbuff, SifAllocIopHeap(), SifCallRpc(), SifDmaStat(), SifFreeIopHeap(), SifSetDma(), SignalSema(), SifDmaTransfer_t::size, audsrv_adpcm_t::size, SifDmaTransfer_t::src, and WaitSema().
Referenced by main().
audsrv_on_cdda_stop()
int audsrv_on_cdda_stop (audsrv_callback_t cb, void * arg)
Installs a callback function upon completion of a cdda track
Parameters
cb your callback
arg extra parameter to pass to callback function later
Returns
status code
Definition at line 464 of file audsrv_rpc.c.
 {
         on_cdda_stop = cb;
         on_cdda_stop_arg = arg;
         return AUDSRV_ERR_NOERROR;
 }
References AUDSRV_ERR_NOERROR, on_cdda_stop, and on_cdda_stop_arg.
Referenced by main().
audsrv_on_fillbuf()
int audsrv_on_fillbuf (int amount, audsrv_callback_t cb, void * arg)
Installs a callback function to be called when ringbuffer has enough space to transmit the request number of bytes.
Parameters
bytes request a callback when this amount of bytes is available
cb your callback
arg extra parameter to pass to callback function later
Returns
AUDSRV_ERR_NOERROR, AUDSRV_ERR_ARGS if amount is greater than sizeof(ringbuf)
Definition at line 471 of file audsrv_rpc.c.
 {
         int err;
         on_fillbuf = 0;
         on_fillbuf_arg = 0;
         err = call_rpc_1(AUDSRV_SET_THRESHOLD, amount);
         if (err != 0)
         {
                 return err;
         }
         on_fillbuf = cb;
         on_fillbuf_arg = arg;
         return AUDSRV_ERR_NOERROR;
 }
References AUDSRV_ERR_NOERROR, AUDSRV_SET_THRESHOLD, call_rpc_1(), on_fillbuf, and on_fillbuf_arg.
Referenced by main().
audsrv_pause_cd()
int audsrv_pause_cd ()
Pauses CDDA playing
Returns
error status code
If CDDA is paused, no operation is taken
Definition at line 208 of file audsrv_rpc.c.
 {
         return call_rpc_1(AUDSRV_PAUSE_CD, 0);
 }
References AUDSRV_PAUSE_CD, and call_rpc_1().
audsrv_play_audio()
int audsrv_play_audio (const char * chunk, int bytes)
Uploads audio buffer to SPU
Parameters
chunk audio buffer
bytes size of chunk in bytes
Returns
positive number of bytes sent to processor or negative error status
Plays an audio buffer; It will not interrupt a playing buffer, rather queue it up and play it as soon as possible without interfering with fluent streaming. The buffer and buflen are given in host format (i.e, 11025hz 8bit stereo.)
Definition at line 228 of file audsrv_rpc.c.
 {
         int copy, maxcopy, copied;
         int packet_size;
         int sent = 0;
         set_error(AUDSRV_ERR_NOERROR);
         maxcopy = sizeof(sbuff) - sizeof(int);
         while (bytes > 0)
         {
                 WaitSema(completion_sema);
                 copy = MIN(bytes, maxcopy);
                 sbuff[0] = copy;
                 memcpy(&sbuff[1], chunk, copy);
                 packet_size = copy + sizeof(int);
                 SifCallRpc(&cd0, AUDSRV_PLAY_AUDIO, 0, sbuff, packet_size, sbuff, 1*4, NULL, NULL);
                 copied = sbuff[0];
                 SignalSema(completion_sema);
                 if (copied < 0)
                 {
                         /* there was an error */
                         set_error(-copied);
                         break;
                 }
                 chunk = chunk + copy;
                 bytes = bytes - copy;
                 sent = sent + copied;
         }
         return sent;
 }
References AUDSRV_ERR_NOERROR, AUDSRV_PLAY_AUDIO, cd0, completion_sema, MIN, NULL, sbuff, set_error(), SifCallRpc(), SignalSema(), and WaitSema().
Referenced by main().
audsrv_play_cd()
int audsrv_play_cd (int track)
Starts playing the request track
Parameters
track segment to play
Returns
status code
Definition at line 171 of file audsrv_rpc.c.
 {
         return call_rpc_1(AUDSRV_PLAY_CD, track);
 }
References AUDSRV_PLAY_CD, and call_rpc_1().
Referenced by main().
audsrv_play_sectors()
int audsrv_play_sectors (int start, int end)
Starts playing at a specific sector
Parameters
start first sector to play
end last sector to play
Returns
status code
Definition at line 176 of file audsrv_rpc.c.
 {
         return call_rpc_2(AUDSRV_PLAY_SECTORS, start, end);
 }
References AUDSRV_PLAY_SECTORS, and call_rpc_2().
audsrv_quit()
int audsrv_quit ()
Shutdowns audsrv
Returns
AUDSRV_ERR_NOERROR
Definition at line 117 of file audsrv_rpc.c.
 {
         WaitSema(completion_sema);
         SifCallRpc(&cd0, AUDSRV_QUIT, 0, sbuff, 1*4, sbuff, 4, NULL, NULL);
         set_error(AUDSRV_ERR_NOERROR);
         SifRemoveRpc(&cb_srv, &cb_queue);
         SifRemoveRpcQueue(&cb_queue);
         TerminateThread(rpc_server_thread_id);
         DeleteThread(rpc_server_thread_id);
         DeleteSema(completion_sema);
         return 0;
 }
References AUDSRV_ERR_NOERROR, AUDSRV_QUIT, cb_queue, cb_srv, cd0, completion_sema, DeleteSema(), DeleteThread(), NULL, rpc_server_thread_id, sbuff, set_error(), SifCallRpc(), SifRemoveRpc(), SifRemoveRpcQueue(), TerminateThread(), and WaitSema().
Referenced by main().
audsrv_resume_cd()
int audsrv_resume_cd ()
Resumes CDDA playing
Returns
error status code
If CDDA was not paused, no operation is taken
Definition at line 213 of file audsrv_rpc.c.
 {
         return call_rpc_1(AUDSRV_RESUME_CD, 0);
 }
References AUDSRV_RESUME_CD, and call_rpc_1().
audsrv_set_format()
int audsrv_set_format (struct audsrv_fmt_t * fmt)
Configures audio stream
Parameters
fmt output specification structure
Returns
0 on success, or one of the error codes otherwise
This sets up audsrv to accept stream in this format and convert it to SPU2's native format if required. Note: it is possible to change the format at any point. You might want to stop audio prior to that, to prevent mismatched audio output.
Definition at line 133 of file audsrv_rpc.c.
 {
         int ret;
         WaitSema(completion_sema);
         sbuff[0] = fmt->freq;
         sbuff[1] = fmt->bits;
         sbuff[2] = fmt->channels;
         SifCallRpc(&cd0, AUDSRV_SET_FORMAT, 0, sbuff, 3*4, sbuff, 4, NULL, NULL);
         ret = sbuff[0];
         SignalSema(completion_sema);
         set_error(ret);
         return ret;
 }
References AUDSRV_SET_FORMAT, audsrv_fmt_t::bits, cd0, audsrv_fmt_t::channels, completion_sema, audsrv_fmt_t::freq, NULL, sbuff, set_error(), SifCallRpc(), SignalSema(), and WaitSema().
Referenced by main().
audsrv_set_volume()
int audsrv_set_volume (int volume)
Sets output volume
Parameters
vol volume in percentage
Returns
error code
Definition at line 157 of file audsrv_rpc.c.
 {
         if (volume > MAX_VOLUME)
         {
                 volume = MAX_VOLUME;
         }
         else if (volume < MIN_VOLUME)
         {
                 volume = MIN_VOLUME;
         }
         return call_rpc_1(AUDSRV_SET_VOLUME, vol_values[volume/4]);
 }
References AUDSRV_SET_VOLUME, call_rpc_1(), MAX_VOLUME, MIN_VOLUME, and vol_values.
Referenced by main().
audsrv_stop_audio()
int audsrv_stop_audio ()
Stops audio from playing.
Returns
status code
Definition at line 264 of file audsrv_rpc.c.
 {
         int ret;
         ret = call_rpc_1(AUDSRV_STOP_AUDIO, 0);
         return ret;
 }
References AUDSRV_STOP_AUDIO, and call_rpc_1().
audsrv_stop_cd()
int audsrv_stop_cd ()
Stops CD from playing.
Returns
status code
Definition at line 181 of file audsrv_rpc.c.
 {
         int ret;
         ret = call_rpc_1(AUDSRV_STOP_CD, 0);
         return ret;
 }
References AUDSRV_STOP_CD, and call_rpc_1().
audsrv_wait_audio()
int audsrv_wait_audio (int bytes)
Blocks until there is enough space to enqueue chunk
Parameters
bytes size of chunk requested to be enqueued (in bytes)
Returns
error code
Blocks until there are enough space to store the upcoming chunk in audsrv's internal ring buffer.
Definition at line 152 of file audsrv_rpc.c.
 {
         return call_rpc_1(AUDSRV_WAIT_AUDIO, bytes);
 }
References AUDSRV_WAIT_AUDIO, and call_rpc_1().
Referenced by main().
call_rpc_1()
static int call_rpc_1 (int func, int arg) static
Internal function to simplify RPC calling
Parameters
func procedure to invoke
arg optional argument
Returns
value returned by RPC server
Definition at line 76 of file audsrv_rpc.c.
 {
         int ret;
         WaitSema(completion_sema);
         sbuff[0] = arg;
         SifCallRpc(&cd0, func, 0, sbuff, 1*4, sbuff, 4, NULL, NULL);
         ret = sbuff[0];
         SignalSema(completion_sema);
         set_error(ret);
         return ret;
 }
References cd0, completion_sema, NULL, sbuff, set_error(), SifCallRpc(), SignalSema(), and WaitSema().
Referenced by audsrv_adpcm_init(), audsrv_get_cd_status(), audsrv_get_cd_type(), audsrv_get_cdpos(), audsrv_get_numtracks(), audsrv_get_track_offset(), audsrv_get_trackpos(), audsrv_on_fillbuf(), audsrv_pause_cd(), audsrv_play_cd(), audsrv_resume_cd(), audsrv_set_volume(), audsrv_stop_audio(), audsrv_stop_cd(), and audsrv_wait_audio().
call_rpc_2()
static int call_rpc_2 (int func, int arg1, int arg2) static
Internal function to simplify RPC calling
Parameters
func procedure to invoke
arg1 optional argument
arg2 optional argument
Returns
value returned by RPC server
Definition at line 99 of file audsrv_rpc.c.
 {
         int ret;
         WaitSema(completion_sema);
         sbuff[0] = arg1;
         sbuff[1] = arg2;
         SifCallRpc(&cd0, func, 0, sbuff, 2*4, sbuff, 4, NULL, NULL);
         ret = sbuff[0];
         SignalSema(completion_sema);
         set_error(ret);
         return ret;
 }
References cd0, completion_sema, NULL, sbuff, set_error(), SifCallRpc(), SignalSema(), and WaitSema().
Referenced by audsrv_adpcm_set_volume(), audsrv_ch_play_adpcm(), and audsrv_play_sectors().
rpc_server_thread()
static void rpc_server_thread (void * arg) static
Definition at line 287 of file audsrv_rpc.c.
 {
         static unsigned char cb_rpc_buffer[64] __attribute__((aligned(64)));
         SifSetRpcQueue(&cb_queue, GetThreadId());
         SifRegisterRpc(&cb_srv, AUDSRV_IRX, &audsrv_ee_rpc_handler, cb_rpc_buffer, NULL, NULL, &cb_queue);
         SifRpcLoop(&cb_queue);
 }
References audsrv_ee_rpc_handler(), AUDSRV_IRX, cb_queue, cb_srv, GetThreadId(), NULL, SifRegisterRpc(), SifRpcLoop(), and SifSetRpcQueue().
Referenced by audsrv_init().
set_error()
static void set_error (int err) static
Internal function to set last error
Parameters
err
Definition at line 61 of file audsrv_rpc.c.
 {
         audsrv_error = err;
 }
References audsrv_error.
Referenced by audsrv_init(), audsrv_play_audio(), audsrv_quit(), audsrv_set_format(), call_rpc_1(), and call_rpc_2().
Variable Documentation
_gp
void* _gp extern
Referenced by audsrv_init().
audsrv_error
int audsrv_error = AUDSRV_ERR_NOERROR static
Definition at line 39 of file audsrv_rpc.c.
Referenced by audsrv_get_error(), and set_error().
cb_queue
struct t_SifRpcDataQueue cb_queue static
Definition at line 30 of file audsrv_rpc.c.
Referenced by audsrv_quit(), and rpc_server_thread().
cb_srv
struct t_SifRpcServerData cb_srv static
Definition at line 30 of file audsrv_rpc.c.
Referenced by audsrv_quit(), and rpc_server_thread().
cd0
struct t_SifRpcClientData cd0 static
Definition at line 1 of file audsrv_rpc.c.
Referenced by audsrv_init(), audsrv_load_adpcm(), audsrv_play_audio(), audsrv_quit(), audsrv_set_format(), call_rpc_1(), and call_rpc_2().
completion_sema
int completion_sema static
Definition at line 40 of file audsrv_rpc.c.
Referenced by audsrv_init(), audsrv_load_adpcm(), audsrv_play_audio(), audsrv_quit(), audsrv_set_format(), call_rpc_1(), and call_rpc_2().
initialized
int initialized = 0 static
Definition at line 37 of file audsrv_rpc.c.
Referenced by audsrv_init().
on_cdda_stop
audsrv_callback_t on_cdda_stop = NULL static
Definition at line 42 of file audsrv_rpc.c.
Referenced by audsrv_ee_rpc_handler(), and audsrv_on_cdda_stop().
on_cdda_stop_arg
void* on_cdda_stop_arg = NULL static
Definition at line 43 of file audsrv_rpc.c.
Referenced by audsrv_ee_rpc_handler(), and audsrv_on_cdda_stop().
on_fillbuf
audsrv_callback_t on_fillbuf = NULL static
Definition at line 45 of file audsrv_rpc.c.
Referenced by audsrv_ee_rpc_handler(), and audsrv_on_fillbuf().
on_fillbuf_arg
void* on_fillbuf_arg = NULL static
Definition at line 46 of file audsrv_rpc.c.
Referenced by audsrv_ee_rpc_handler(), and audsrv_on_fillbuf().
rpc_server_stack
unsigned char rpc_server_stack[0x1800] static
Definition at line 33 of file audsrv_rpc.c.
Referenced by audsrv_init().
rpc_server_thread_id
int rpc_server_thread_id static
Definition at line 38 of file audsrv_rpc.c.
Referenced by audsrv_init(), and audsrv_quit().
sbuff
unsigned int sbuff[4096] static
Definition at line 30 of file audsrv_rpc.c.
Referenced by audsrv_init(), audsrv_load_adpcm(), audsrv_play_audio(), audsrv_quit(), audsrv_set_format(), call_rpc_1(), and call_rpc_2().
vol_values
const unsigned short vol_values[26] static
Initial value:
=
{
        0x0000,
        0x0000, 0x0096, 0x0190, 0x0230, 0x0320,
        0x042E, 0x0532, 0x05FA, 0x06C2, 0x088E,
        0x09F6, 0x0BC2, 0x0DC0, 0x0FF0, 0x118A,
        0x1482, 0x1752, 0x1B4E, 0x1F40, 0x2378,
        0x28D2, 0x2EFE, 0x34F8, 0x3A5C, 0x3FFF
}
Definition at line 48 of file audsrv_rpc.c.
Referenced by audsrv_adpcm_set_volume(), and audsrv_set_volume().