ps2sdk: ee/debug/src/callstack.c File Reference
callstack.c File Reference
Data Structures
struct ReturnCachePtr
Macros
#define RESTORE_RETURNVAL 0x8fbf0000
#define RESTORE_RETURNVAL_MASK 0xffff0000
#define RESTORE_RETURNVAL2 0xdfbf0000
#define RESTORE_RETURNVAL3 0x7bbf0000
#define ADJUST_STACKP_C 0x27bd0000
#define ADJUST_STACKP_C_MASK 0xffff0000
#define ADJUST_STACKP_V 0x03a1e821
#define ADJUST_STACKP_V_MASK 0xffffffff
#define SET_UPPER_C 0x3c010000
#define SET_UPPER_C_MASK 0xffff0000
#define OR_LOWER_C 0x34210000
#define OR_LOWER_C_MASK 0xffff0000
#define SET_LOWER_C 0x34010000
#define SET_LOWER_C_MASK 0xffff0000
#define RETURN 0x03e00008
#define CALL(f) (0x0c000000 | (((int) (f)) >> 2))
#define HASH_SIZE 256
#define HASH(ra) ((((int) (ra)) >> 2) & (HASH_SIZE - 1))
#define TRUE 1
#define FALSE 0
Typedefs
typedef int Bool
Functions
unsigned int * ps2GetReturnAddress ()
unsigned int * ps2GetStackPointer ()
int main ()
void ps2GetStackTrace (unsigned int *results, int max)
Variables
static ReturnCacheRec returnCache [HASH_SIZE]
Macro Definition Documentation
ADJUST_STACKP_C
#define ADJUST_STACKP_C 0x27bd0000
Definition at line 56 of file callstack.c.
ADJUST_STACKP_C_MASK
#define ADJUST_STACKP_C_MASK 0xffff0000
Definition at line 57 of file callstack.c.
ADJUST_STACKP_V
#define ADJUST_STACKP_V 0x03a1e821
Definition at line 62 of file callstack.c.
ADJUST_STACKP_V_MASK
#define ADJUST_STACKP_V_MASK 0xffffffff
Definition at line 63 of file callstack.c.
CALL
#define CALL (f) (0x0c000000 | (((int) (f)) >> 2))
Definition at line 86 of file callstack.c.
FALSE
#define FALSE 0
Definition at line 112 of file callstack.c.
HASH
#define HASH (ra) ((((int) (ra)) >> 2) & (HASH_SIZE - 1))
Definition at line 104 of file callstack.c.
HASH_SIZE
#define HASH_SIZE 256
Definition at line 93 of file callstack.c.
OR_LOWER_C
#define OR_LOWER_C 0x34210000
Definition at line 74 of file callstack.c.
OR_LOWER_C_MASK
#define OR_LOWER_C_MASK 0xffff0000
Definition at line 75 of file callstack.c.
RESTORE_RETURNVAL
#define RESTORE_RETURNVAL 0x8fbf0000
Definition at line 40 of file callstack.c.
RESTORE_RETURNVAL2
#define RESTORE_RETURNVAL2 0xdfbf0000
Definition at line 46 of file callstack.c.
RESTORE_RETURNVAL3
#define RESTORE_RETURNVAL3 0x7bbf0000
Definition at line 51 of file callstack.c.
RESTORE_RETURNVAL_MASK
#define RESTORE_RETURNVAL_MASK 0xffff0000
Definition at line 41 of file callstack.c.
RETURN
#define RETURN 0x03e00008
Definition at line 84 of file callstack.c.
SET_LOWER_C
#define SET_LOWER_C 0x34010000
Definition at line 80 of file callstack.c.
SET_LOWER_C_MASK
#define SET_LOWER_C_MASK 0xffff0000
Definition at line 81 of file callstack.c.
SET_UPPER_C
#define SET_UPPER_C 0x3c010000
Definition at line 68 of file callstack.c.
SET_UPPER_C_MASK
#define SET_UPPER_C_MASK 0xffff0000
Definition at line 69 of file callstack.c.
TRUE
#define TRUE 1
Definition at line 109 of file callstack.c.
Typedef Documentation
Bool
typedef int Bool
Definition at line 106 of file callstack.c.
Function Documentation
main()
int main ()
Definition at line 45 of file callstacktest.c.
 {
   testFunction1();
   while(1)
   {
   }
   return 0;
 }
References actAlign, framebuffer_t::address, zbuffer_t::address, ARRAY_ENTRIES, padButtonStatus::btns, CreateSave(), packet_t::data, data, dma_channel_fast_waits(), DMA_CHANNEL_GIF, dma_channel_initialize(), dma_channel_send_chain(), dma_channel_send_normal(), dma_channel_shutdown(), DMA_CHANNEL_toIPU, dma_wait_fast(), DOUBLE_BYTE, draw_clear(), draw_init_env(), draw_setup_environment(), zbuffer_t::enable, fontstudio_load_ini(), fontstudio_parse_ini(), fontstudio_unload_ini(), fontx_load(), fontx_unload(), GRAPH_ALIGN_BLOCK, GRAPH_ALIGN_PAGE, graph_initialize(), graph_shutdown(), graph_vram_allocate(), graph_vram_free(), graph_wait_vsync(), GS_PSM_32, framebuffer_t::height, impress, init_drawing_environment(), init_gs(), init_texture(), InitCB(), initializePad(), krom_k, krom_u, LoadModules(), loadModules(), InitCBParam::m_DrawPck, InitCBParam::m_pData, InitCBParam::m_pInfo, InitCBParam::m_TexAddr, InitCBParam::m_XFerPck, framebuffer_t::mask, zbuffer_t::mask, MAX_SIZE, MC_ATTR_SUBDIR, mc_Format, mc_Free, mc_Type, MC_TYPE_MC, MC_TYPE_XMC, mcDir, mcGetDir(), mcGetInfo(), mcInit(), mcSync(), zbuffer_t::method, MPEG_BITSTREAM_FILE, MPEG_Destroy(), MPEG_Initialize(), MPEG_Picture, new_pad, NULL, old_pad, packet, packet_free(), packet_init(), PACKET_NORMAL, PAD_CIRCLE, PAD_CROSS, PAD_DOWN, PAD_L1, PAD_L2, PAD_L3, PAD_LEFT, PAD_R1, PAD_R2, PAD_R3, PAD_RIGHT, PAD_SELECT, PAD_SQUARE, PAD_START, PAD_STATE_DISCONN, PAD_STATE_FINDCTP1, PAD_STATE_STABLE, PAD_TRIANGLE, PAD_UP, padBuf, paddata, padEnterPressMode(), padExitPressMode(), padGetPortMax(), padGetSlotMax(), padGetState(), padInit(), padPortOpen(), padRead(), padSetActDirect(), port, framebuffer_t::psm, render(), padButtonStatus::rjoy_h, run_demo(), s_MPEGDataSize, s_pMPEGData, s_pTransferPtr, sceSdInit(), sceSdSetParam(), SD_PARAM_MVOLL, SD_PARAM_MVOLR, SD_VOICE, SetDMA(), SifExitRpc(), SifInitRpc(), SifLoadModule(), SINGLE_BYTE, SleepThread(), slot, sndStreamOpen(), sndStreamPlay(), STREAM_END_CLOSE, STREAM_STEREO, testFunction1(), padButtonStatus::triangle_p, framebuffer_t::width, and zbuffer_t::zsm.
Referenced by ps2GetStackTrace().
ps2GetReturnAddress()
unsigned int* ps2GetReturnAddress ()
Referenced by ps2GetStackTrace().
ps2GetStackPointer()
unsigned int* ps2GetStackPointer ()
Referenced by ps2GetStackTrace().
ps2GetStackTrace()
void ps2GetStackTrace (unsigned int * results, int max)
Definition at line 119 of file callstack.c.
 {
   unsigned int*   ra;
   unsigned int*   ra_limit;
   unsigned int*   sp;
   unsigned int    inst;
   unsigned int    mainCall;
   unsigned short  const_upper;
   unsigned short  const_lower;
   int ra_offset;
   int sp_adjust;
   Bool found_ra_offset, found_sp_adjust;
   Bool found_const_upper, found_const_lower;
   ReturnCachePtr  rc;
   ra = ps2GetReturnAddress();
   sp = ps2GetStackPointer();
   mainCall = CALL(main);
   while (ra && max)
   {
     rc = &returnCache[HASH(ra)];
     if (rc->returnAddress != ra)
     {
       found_ra_offset = FALSE;
       found_sp_adjust = FALSE;
       found_const_upper = FALSE;
       found_const_lower = FALSE;
       const_upper = 0;
       const_lower = 0;
       rc->returnAddress = ra;
       ra_limit = (unsigned int *) 0x200000;
       ra_offset = 0;
       sp_adjust = -1;
       while ((!found_ra_offset || !found_sp_adjust) && ra < ra_limit)
       {
         inst = *ra;
         /* look for the offset of the PC in the stack frame */
         if ((inst & RESTORE_RETURNVAL_MASK) == RESTORE_RETURNVAL)
         {
           ra_offset = inst & ~RESTORE_RETURNVAL_MASK;
           found_ra_offset = TRUE;
         }
         else if ((inst & RESTORE_RETURNVAL_MASK) == RESTORE_RETURNVAL2)
         {
             ra_offset = inst & ~RESTORE_RETURNVAL_MASK;
             found_ra_offset = TRUE;
         }
         else if ((inst & RESTORE_RETURNVAL_MASK) == RESTORE_RETURNVAL3)
         {
             ra_offset = inst & ~RESTORE_RETURNVAL_MASK;
             found_ra_offset = TRUE;
         }
         else if ((inst & ADJUST_STACKP_C_MASK) == ADJUST_STACKP_C)
         {
           sp_adjust = inst & ~ADJUST_STACKP_C_MASK;
           found_sp_adjust = TRUE;
         }
         else if ((inst & ADJUST_STACKP_V_MASK) == ADJUST_STACKP_V)
         {
           sp_adjust = 0;
           found_sp_adjust = TRUE;
         }
         else if ((inst & SET_UPPER_C_MASK) == SET_UPPER_C)
         {
           const_upper = inst & ~SET_UPPER_C_MASK;
           const_lower = 0;
           found_const_upper = TRUE;
         }
         else if ((inst & OR_LOWER_C_MASK) == OR_LOWER_C)
         {
           const_lower = inst & ~OR_LOWER_C_MASK;
           found_const_lower = TRUE;
         }
         else if ((inst & SET_LOWER_C_MASK) == SET_LOWER_C)
         {
           const_lower = inst & ~SET_LOWER_C_MASK;
           const_upper = 0;
           found_const_lower = TRUE;
         }
         else if (inst == RETURN)
           ra_limit = ra + 2;
         ra++;
       }
       if (sp_adjust == 0 && (found_const_upper || found_const_lower))
         sp_adjust = (const_upper << 16) | const_lower;
       rc->raOffset = ra_offset;
       rc->spAdjust = sp_adjust;
     }
     /* if something went wrong, punt */
     if (rc->spAdjust <= 0)
     {
       *results++ = 0;
       break;
     }
     ra = (unsigned int *) sp[rc->raOffset>>2];
     sp += rc->spAdjust >> 2;
     if (ra == 0)
     {
       *results++ = 0;
       break;
     }
     *results++ = ((unsigned int) ra) - 8;
     if (ra[-2] == mainCall)
     {
       *results++ = 0;
       break;
     }
     max--;
   }
 }
References ADJUST_STACKP_C, ADJUST_STACKP_C_MASK, ADJUST_STACKP_V, ADJUST_STACKP_V_MASK, CALL, FALSE, HASH, main(), max, OR_LOWER_C, OR_LOWER_C_MASK, ps2GetReturnAddress(), ps2GetStackPointer(), ra, RESTORE_RETURNVAL, RESTORE_RETURNVAL2, RESTORE_RETURNVAL3, RESTORE_RETURNVAL_MASK, RETURN, returnCache, SET_LOWER_C, SET_LOWER_C_MASK, SET_UPPER_C, SET_UPPER_C_MASK, sp, and TRUE.
Referenced by TestFunction3().
Variable Documentation
returnCache
ReturnCacheRec returnCache[HASH_SIZE] static
Definition at line 102 of file callstack.c.
Referenced by ps2GetStackTrace().