ps2sdk: ee/debug/samples/callstacktest/callstacktest.c File Reference
callstacktest.c File Reference
#include <stdio.h>
#include <tamtypes.h>
#include <debug.h>
Functions
int TestFunction3 ()
int TestFunction2 ()
int testFunction1 ()
int main ()
Function Documentation
main()
int main (void)
Definition at line 45 of file callstacktest.c.
 {
   testFunction1();
   while(1)
   {
   }
   return 0;
 }
References testFunction1().
testFunction1()
int testFunction1 ()
Definition at line 40 of file callstacktest.c.
 {
   return TestFunction2();
 }
References TestFunction2().
Referenced by main().
TestFunction2()
int TestFunction2 ()
Definition at line 35 of file callstacktest.c.
 {
   return TestFunction3();
 }
References TestFunction3().
Referenced by testFunction1().
TestFunction3()
int TestFunction3 ()
A bunch of test function that we use to test the stacktrace.
Definition at line 17 of file callstacktest.c.
 {
   unsigned int* stackTrace[256];
   int i = 0;
   ps2GetStackTrace((unsigned int*)&stackTrace,256);
   for(i = 0; i < 256; ++i)
   {
     if (stackTrace[i] == 0)
       break;
     printf("adress %d 0x%08x\n",i,(int)stackTrace[i]);
   }
   return 0;
 }
References ps2GetStackTrace().
Referenced by TestFunction2().