ps2sdk: ee/rpc/camera/samples/camera-test.c File Reference
camera-test.c File Reference
#include "../include/ps2cam_rpc.h"
#include "libjpg.h"
#include "fileio.h"
#include "kernel.h"
#include "sifrpc.h"
#include "loadfile.h"
#include "stdio.h"
Functions
int main (int argc, char *argv[])
Variables
char jpg_buffer [500512]
jpgData * info
PS2CAM_DEVICE_INFO caminfo
PS2CAM_DEVICE_CONFIG cfg
int * iopval
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 24 of file camera-test.c.
 {
         static int ret;
         static int devid;
         static int fh;
         SifInitRpc(0);
         fioInit();
         SifLoadModule("rom0:SIO2MAN", 0, 0);
         SifLoadModule("host:usbd.irx", 0, 0);
         SifLoadModule("host:ps2cam.irx", 0, 0);
         printf("binding...\n");
         PS2CamInit(0);
         while(1)
         {
                 ret = PS2CamGetDeviceCount();
                 printf("there is %d camera connected\n",ret);
                 if(ret > 0)break;
         }
         devid = PS2CamOpenDevice(0);
         printf("device %d ID == %d\n",0,devid);
         while(1)
         {
                 ret = PS2CamGetDeviceStatus(devid);
                 if(ret==2)break;
         }
         printf("status =%d\n",ret);
         ret = PS2CamSetDeviceBandwidth(devid, 4);
         printf("set Bandwidth = %d\n",ret);
         cfg.ssize       = sizeof(cfg);
         cfg.mask        = CAM_CONFIG_MASK_DIMENSION|CAM_CONFIG_MASK_DIVIDER|CAM_CONFIG_MASK_OFFSET|CAM_CONFIG_MASK_FRAMERATE;
         cfg.width       = 640;
         cfg.height      = 480;
         cfg.x_offset =0x00;
         cfg.y_offset =0x00;
         cfg.h_divider =0;
         cfg.v_divider =0;
         cfg.framerate =30;
         PS2CamSetDeviceConfig(devid, &cfg);
         caminfo.ssize = sizeof(caminfo);
         PS2CamGetDeviceInfo(devid, &caminfo);
         printf("info = %s (%d)\n",(char *)&caminfo.product_name[0],caminfo.ssize);
         // capture and save jpg to host
         // loop and capture a valid frame
         while(1)
         {
                 ret = PS2CamExtractFrame(devid, jpg_buffer, 500512);
                 if(ret>0)break; // valid frame
                 if(ret<0)break; // error
                 printf("frame skiped\n");
         }
         if(ret>0)
         {
                 printf("frame captured\n");
                 fh = open("host:image.jpg", O_WRONLY|O_CREAT|O_TRUNC);
                 write(fh, jpg_buffer, ret);
                 close(fh);
         }
         else
         {
                 printf("error capturing image (%d)\n",ret);
         }
         while(1)
         {
                 //do nothing
         }
         return 0;
 }
References CAM_CONFIG_MASK_DIMENSION, CAM_CONFIG_MASK_DIVIDER, CAM_CONFIG_MASK_FRAMERATE, CAM_CONFIG_MASK_OFFSET, caminfo, cfg, fioInit(), PS2CAM_DEVICE_CONFIG::framerate, PS2CAM_DEVICE_CONFIG::h_divider, PS2CAM_DEVICE_CONFIG::height, jpg_buffer, PS2CAM_DEVICE_CONFIG::mask, PS2CAM_DEVICE_INFO::product_name, PS2CamExtractFrame(), PS2CamGetDeviceCount(), PS2CamGetDeviceInfo(), PS2CamGetDeviceStatus(), PS2CamInit(), PS2CamOpenDevice(), PS2CamSetDeviceBandwidth(), PS2CamSetDeviceConfig(), SifInitRpc(), SifLoadModule(), PS2CAM_DEVICE_INFO::ssize, PS2CAM_DEVICE_CONFIG::ssize, PS2CAM_DEVICE_CONFIG::v_divider, PS2CAM_DEVICE_CONFIG::width, PS2CAM_DEVICE_CONFIG::x_offset, and PS2CAM_DEVICE_CONFIG::y_offset.
Variable Documentation
caminfo
PS2CAM_DEVICE_INFO caminfo
Definition at line 16 of file camera-test.c.
Referenced by main().
cfg
PS2CAM_DEVICE_CONFIG cfg
Definition at line 18 of file camera-test.c.
Referenced by main(), and PS2CamSetDeviceConfig().
info
jpgData* info
Definition at line 14 of file camera-test.c.
Referenced by hddGetInfo(), mcGetInfoApdx(), mcSetFileInfo(), PS2CamGetDeviceInfo(), and smod_get_mod_by_name().
iopval
int* iopval
Definition at line 21 of file camera-test.c.
jpg_buffer
char jpg_buffer[500512]
Definition at line 10 of file camera-test.c.
Referenced by main().