ps2sdk: ee/sbv/src/common.h File Reference
common.h File Reference
Data Structures
struct smem_buf
Macros
#define SMEM_BUF_SIZE 0x300
Functions
int smem_write_word (void *address, u32 value)
int __memcmp (const void *s1, const void *s2, unsigned int length)
Macro Definition Documentation
SMEM_BUF_SIZE
#define SMEM_BUF_SIZE 0x300
Definition at line 1 of file common.h.
Function Documentation
__memcmp()
int __memcmp (const void * s1, const void * s2, unsigned int length)
Definition at line 27 of file common.c.
 {
         const char *a = s1;
         const char *b = s2;
         while (length--) {
                 if (*a++ != *b++)
                         return 1;
         }
         return 0;
 }
References s1, and s2.
Referenced by slib_exp_lib_list(), slib_get_exp_lib(), and smod_get_mod_by_name().
smem_write_word()
int smem_write_word (void * address, u32 value)
Definition at line 40 of file common.c.
 {
         SifRpcReceiveData_t RData;
         void *pDestRounded;
         int result;
         SifDmaTransfer_t dmat;
         pDestRounded=(void*)(((u32)address)&0xFFFFFFC0);
         SyncDCache(&smem_buf, smem_buf.bytes+64);
         if((result=SifRpcGetOtherData(&RData, pDestRounded, &smem_buf, 64, 0))>=0)
         {
                 *(u32*)UNCACHED_SEG((&smem_buf.bytes[((u32)address&0x3F)]))=value;
                 dmat.src=&smem_buf;
                 dmat.dest=pDestRounded;
                 dmat.size=64;
                 dmat.attr=0;
                 SifSetDma(&dmat, 1);
         }
         return result;
 }
References SifDmaTransfer_t::attr, smem_buf::bytes, SifDmaTransfer_t::dest, result, SifRpcGetOtherData(), SifSetDma(), SifDmaTransfer_t::size, smem_buf, SifDmaTransfer_t::src, SyncDCache(), and UNCACHED_SEG.
Referenced by sbv_patch_enable_lmb(), and sbv_patch_fileio().