ps2sdk: ee/draw/samples/cube/cube.c File Reference
cube.c File Reference
#include <kernel.h>
#include <stdlib.h>
#include <tamtypes.h>
#include <math3d.h>
#include <packet.h>
#include <dma_tags.h>
#include <gif_tags.h>
#include <gs_psm.h>
#include <dma.h>
#include <graph.h>
#include <draw.h>
#include <draw3d.h>
#include "mesh_data.c"
Functions
void init_gs (framebuffer_t *frame, zbuffer_t *z)
void init_drawing_environment (framebuffer_t *frame, zbuffer_t *z)
int render (framebuffer_t *frame, zbuffer_t *z)
int main (int argc, char **argv)
Variables
VECTOR object_position = { 0.00f, 0.00f, 0.00f, 1.00f }
VECTOR object_rotation = { 0.00f, 0.00f, 0.00f, 1.00f }
VECTOR camera_position = { 0.00f, 0.00f, 100.00f, 1.00f }
VECTOR camera_rotation = { 0.00f, 0.00f, 0.00f, 1.00f }
Function Documentation
init_drawing_environment()
void init_drawing_environment (framebuffer_t * frame, zbuffer_t * z)
Definition at line 60 of file cube.c.
 {
         packet_t *packet = packet_init(16,PACKET_NORMAL);
         // This is our generic qword pointer.
         qword_t *q = packet->data;
         // This will setup a default drawing environment.
         q = draw_setup_environment(q,0,frame,z);
         // Now reset the primitive origin to 2048-width/2,2048-height/2.
         q = draw_primitive_xyoffset(q,0,(2048-320),(2048-256));
         // Finish setting up the environment.
         q = draw_finish(q);
         // Now send the packet, no need to wait since it's the first.
         dma_channel_send_normal(DMA_CHANNEL_GIF,packet->data,q - packet->data, 0, 0);
         dma_wait_fast();
         packet_free(packet);
 }
References packet_t::data, DMA_CHANNEL_GIF, dma_channel_send_normal(), dma_wait_fast(), draw_finish(), draw_primitive_xyoffset(), draw_setup_environment(), packet, packet_free(), packet_init(), and PACKET_NORMAL.
Referenced by main().
init_gs()
void init_gs (framebuffer_t * frame, zbuffer_t * z)
Definition at line 38 of file cube.c.
 {
         // Define a 32-bit 640x512 framebuffer.
         frame->width = 640;
         frame->height = 512;
         frame->mask = 0;
         frame->psm = GS_PSM_32;
         frame->address = graph_vram_allocate(frame->width,frame->height, frame->psm, GRAPH_ALIGN_PAGE);
         // Enable the zbuffer.
         z->enable = DRAW_ENABLE;
         z->mask = 0;
         z->method = ZTEST_METHOD_GREATER_EQUAL;
         z->zsm = GS_ZBUF_32;
         z->address = graph_vram_allocate(frame->width,frame->height,z->zsm, GRAPH_ALIGN_PAGE);
         // Initialize the screen and tie the first framebuffer to the read circuits.
         graph_initialize(frame->address,frame->width,frame->height,frame->psm,0,0);
 }
References framebuffer_t::address, zbuffer_t::address, DRAW_ENABLE, zbuffer_t::enable, GRAPH_ALIGN_PAGE, graph_initialize(), graph_vram_allocate(), GS_PSM_32, GS_ZBUF_32, framebuffer_t::height, framebuffer_t::mask, zbuffer_t::mask, zbuffer_t::method, framebuffer_t::psm, framebuffer_t::width, zbuffer_t::zsm, and ZTEST_METHOD_GREATER_EQUAL.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 222 of file cube.c.
 {
         // The buffers to be used.
         framebuffer_t frame;
         zbuffer_t z;
         // Init GIF dma channel.
         dma_channel_initialize(DMA_CHANNEL_GIF,NULL,0);
         dma_channel_fast_waits(DMA_CHANNEL_GIF);
         // Init the GS, framebuffer, and zbuffer.
         init_gs(&frame, &z);
         // Init the drawing environment and framebuffer.
         init_drawing_environment(&frame,&z);
         // Render the cube
         render(&frame,&z);
         // Sleep
         SleepThread();
         // End program.
         return 0;
 }
References dma_channel_fast_waits(), DMA_CHANNEL_GIF, dma_channel_initialize(), init_drawing_environment(), init_gs(), NULL, render(), and SleepThread().
render()
int render (framebuffer_t * frame, zbuffer_t * z)
Definition at line 85 of file cube.c.
 {
         int i;
         int context = 0;
         // Matrices to setup the 3D environment and camera
         MATRIX local_world;
         MATRIX world_view;
         MATRIX view_screen;
         MATRIX local_screen;
         VECTOR *temp_vertices;
         prim_t prim;
         color_t color;
         xyz_t   *verts;
         color_t *colors;
         // The data packets for double buffering dma sends.
         packet_t *packets[2];
         packet_t *current;
         qword_t *q;
         qword_t *dmatag;
         packets[0] = packet_init(100,PACKET_NORMAL);
         packets[1] = packet_init(100,PACKET_NORMAL);
         // Allocate calculation space.
         temp_vertices = memalign(128, sizeof(VECTOR) * vertex_count);
         // Allocate register space.
         verts  = memalign(128, sizeof(vertex_t) * vertex_count);
         colors = memalign(128, sizeof(color_t)  * vertex_count);
         // Define the triangle primitive we want to use.
         prim.type = PRIM_TRIANGLE;
         prim.shading = PRIM_SHADE_GOURAUD;
         prim.mapping = DRAW_DISABLE;
         prim.fogging = DRAW_DISABLE;
         prim.blending = DRAW_DISABLE;
         prim.antialiasing = DRAW_ENABLE;
         prim.mapping_type = PRIM_MAP_ST;
         prim.colorfix = PRIM_UNFIXED;
         color.r = 0x80;
         color.g = 0x80;
         color.b = 0x80;
         color.a = 0x80;
         color.q = 1.0f;
         // Create the view_screen matrix.
         create_view_screen(view_screen, graph_aspect_ratio(), -3.00f, 3.00f, -3.00f, 3.00f, 1.00f, 2000.00f);
         // Wait for any previous dma transfers to finish before starting.
         dma_wait_fast();
         // The main loop...
         for (;;)
         {
                 current = packets[context];
                 // Spin the cube a bit.
                 object_rotation[0] += 0.008f; //while (object_rotation[0] > 3.14f) { object_rotation[0] -= 6.28f; }
                 object_rotation[1] += 0.012f; //while (object_rotation[1] > 3.14f) { object_rotation[1] -= 6.28f; }
                 // Create the local_world matrix.
                 create_local_world(local_world, object_position, object_rotation);
                 // Create the world_view matrix.
                 create_world_view(world_view, camera_position, camera_rotation);
                 // Create the local_screen matrix.
                 create_local_screen(local_screen, local_world, world_view, view_screen);
                 // Calculate the vertex values.
                 calculate_vertices(temp_vertices, vertex_count, vertices, local_screen);
                 // Convert floating point vertices to fixed point and translate to center of screen.
                 draw_convert_xyz(verts, 2048, 2048, 32, vertex_count, (vertex_f_t*)temp_vertices);
                 // Convert floating point colours to fixed point.
                 draw_convert_rgbq(colors, vertex_count, (vertex_f_t*)temp_vertices, (color_f_t*)colours, 0x80);
                 // Grab our dmatag pointer for the dma chain.
                 dmatag = current->data;
                 // Now grab our qword pointer and increment past the dmatag.
                 q = dmatag;
                 q++;
                 // Clear framebuffer but don't update zbuffer.
                 q = draw_disable_tests(q,0,z);
                 q = draw_clear(q,0,2048.0f-320.0f,2048.0f-256.0f,frame->width,frame->height,0x00,0x00,0x00);
                 q = draw_enable_tests(q,0,z);
                 // Draw the triangles using triangle primitive type.
                 q = draw_prim_start(q,0,&prim, &color);
                 for(i = 0; i < points_count; i++)
                 {
                         q->dw[0] = colors[points[i]].rgbaq;
                         q->dw[1] = verts[points[i]].xyz;
                         q++;
                 }
                 q = draw_prim_end(q,2,DRAW_RGBAQ_REGLIST);
                 // Setup a finish event.
                 q = draw_finish(q);
                 // Define our dmatag for the dma chain.
                 DMATAG_END(dmatag,(q-current->data)-1,0,0,0);
                 // Now send our current dma chain.
                 dma_wait_fast();
                 dma_channel_send_chain(DMA_CHANNEL_GIF,current->data, q - current->data, 0, 0);
                 // Now switch our packets so we can process data while the DMAC is working.
                 context ^= 1;
                 // Wait for scene to finish drawing
                 draw_wait_finish();
                 graph_wait_vsync();
         }
         packet_free(packets[0]);
         packet_free(packets[1]);
         return 0;
 }
References color_t::a, prim_t::antialiasing, color_t::b, prim_t::blending, calculate_vertices(), camera_position, camera_rotation, prim_t::colorfix, colours, context, create_local_screen(), create_local_world(), create_view_screen(), create_world_view(), packet_t::data, DMA_CHANNEL_GIF, dma_channel_send_chain(), dma_wait_fast(), DMATAG_END, draw_clear(), draw_convert_rgbq(), draw_convert_xyz(), DRAW_DISABLE, draw_disable_tests(), DRAW_ENABLE, draw_enable_tests(), draw_finish(), draw_prim_end(), draw_prim_start(), DRAW_RGBAQ_REGLIST, draw_wait_finish(), qword_t::dw, prim_t::fogging, color_t::g, graph_aspect_ratio(), graph_wait_vsync(), framebuffer_t::height, local_screen, local_world, prim_t::mapping, prim_t::mapping_type, object_position, object_rotation, packet_free(), packet_init(), PACKET_NORMAL, packets, points, points_count, prim, PRIM_MAP_ST, PRIM_SHADE_GOURAUD, PRIM_TRIANGLE, PRIM_UNFIXED, color_t::q, color_t::r, color_t::rgbaq, prim_t::shading, temp_vertices, prim_t::type, vertex_count, vertices, view_screen, framebuffer_t::width, world_view, and xyz_t::xyz.
Referenced by main().
Variable Documentation
camera_position
VECTOR camera_position = { 0.00f, 0.00f, 100.00f, 1.00f }
Definition at line 35 of file cube.c.
Referenced by render().
camera_rotation
VECTOR camera_rotation = { 0.00f, 0.00f, 0.00f, 1.00f }
Definition at line 36 of file cube.c.
Referenced by render().
object_position
VECTOR object_position = { 0.00f, 0.00f, 0.00f, 1.00f }
Definition at line 32 of file cube.c.
Referenced by render(), and render_teapot().
object_rotation
VECTOR object_rotation = { 0.00f, 0.00f, 0.00f, 1.00f }
Definition at line 33 of file cube.c.
Referenced by render(), and render_teapot().