ps2sdk: ee/debug/include/debug.h File Reference
debug.h File Reference
#include <tamtypes.h>
Macros
#define DEBUG_BGCOLOR(col) *((u64 *) 0x120000e0) = (u64) (col)
Functions
void init_scr (void)
void scr_printf (const char *,...)
void scr_putchar (int x, int y, u32 color, int ch)
void ps2GetStackTrace (unsigned int *results, int max)
void scr_setXY (int x, int y)
int scr_getX (void)
int scr_getY (void)
void scr_clear (void)
void scr_setbgcolor (u32 color)
Detailed Description
EE Debug prototypes
Definition in file debug.h.
Macro Definition Documentation
DEBUG_BGCOLOR
#define DEBUG_BGCOLOR (col) *((u64 *) 0x120000e0) = (u64) (col)
Definition at line 21 of file debug.h.
Function Documentation
init_scr()
void init_scr (void)
Definition at line 185 of file scr_printf.c.
 {
   static struct t_setupscr setupscr __attribute__ (( aligned (16) )) = {
         { 0x100000000000800E, 0xE, 0xA0000, 0x4C, 0x8C, 0x4E },          //GIFtag (REGS: A+D, NREG 1, FLG PACKED, EOP, NLOOP 14), FRAME_1 (PSM PSMCT32, FBW 10, FBP 0), ZBUF_1 (PSM PSMZ32, ZBP 140)
         { 27648, 30976 }, { 0x18 },                                      //XYOFFSET_1 (OFX 1728.0, OFY 1936.0)
         { 0, 639, 0, 223 },                                              //SCISSOR_1 (SCAX0 0, SCAX1 639, SCAY0 0, SCAY1 223)
         { 0x40, 1, 0x1a, 1, 0x46, 0, 0x45, 0x70000,                      //PRMODECONT (AC PRIM), COLCLAMP (CLAMP 1), DTHE (DTHE 0)
         0x47, 0x30000, 0x47, 6, 0, 0x3F80000000000000, 1, 0x79006C00, 5, //TEST_1 (ZTST GREATER, ZTE 1), TEST_1 (ZTST ALWAYS, ZTE 1), PMODE (CRTMD 1, EN2 1), RGBAQ (Q 1.0, A 0, B 0, G 0, R 0), XYZ2 (Z 0.0, Y 1728.0, X 1936.0)
         0x87009400, 5, 0x70000, 0x47 }                                   //XYZ2 (Z 0, Y 2160.0, X 2368.0), TEST_1 (ZTST GREATER, ZTE 1)
    };
    X = Y = 0;
    DmaReset();
    Init_GS( 1, debug_detect_signal() == 1 ? 3 : 2, 0); // Interlaced, NTSC/PAL and FIELD mode
    SetVideoMode();
    Dma02Wait();
    progdma( &setupscr, 15);
    Dma02Wait();
 }
References debug_detect_signal(), Dma02Wait(), DmaReset(), Init_GS(), progdma(), SetVideoMode(), X, and Y.
Referenced by main().
ps2GetStackTrace()
void ps2GetStackTrace (unsigned int * results, int max)
Definition at line 119 of file callstack.c.
 {
   unsigned int*   ra;
   unsigned int*   ra_limit;
   unsigned int*   sp;
   unsigned int    inst;
   unsigned int    mainCall;
   unsigned short  const_upper;
   unsigned short  const_lower;
   int ra_offset;
   int sp_adjust;
   Bool found_ra_offset, found_sp_adjust;
   Bool found_const_upper, found_const_lower;
   ReturnCachePtr  rc;
   ra = ps2GetReturnAddress();
   sp = ps2GetStackPointer();
   mainCall = CALL(main);
   while (ra && max)
   {
     rc = &returnCache[HASH(ra)];
     if (rc->returnAddress != ra)
     {
       found_ra_offset = FALSE;
       found_sp_adjust = FALSE;
       found_const_upper = FALSE;
       found_const_lower = FALSE;
       const_upper = 0;
       const_lower = 0;
       rc->returnAddress = ra;
       ra_limit = (unsigned int *) 0x200000;
       ra_offset = 0;
       sp_adjust = -1;
       while ((!found_ra_offset || !found_sp_adjust) && ra < ra_limit)
       {
         inst = *ra;
         /* look for the offset of the PC in the stack frame */
         if ((inst & RESTORE_RETURNVAL_MASK) == RESTORE_RETURNVAL)
         {
           ra_offset = inst & ~RESTORE_RETURNVAL_MASK;
           found_ra_offset = TRUE;
         }
         else if ((inst & RESTORE_RETURNVAL_MASK) == RESTORE_RETURNVAL2)
         {
             ra_offset = inst & ~RESTORE_RETURNVAL_MASK;
             found_ra_offset = TRUE;
         }
         else if ((inst & RESTORE_RETURNVAL_MASK) == RESTORE_RETURNVAL3)
         {
             ra_offset = inst & ~RESTORE_RETURNVAL_MASK;
             found_ra_offset = TRUE;
         }
         else if ((inst & ADJUST_STACKP_C_MASK) == ADJUST_STACKP_C)
         {
           sp_adjust = inst & ~ADJUST_STACKP_C_MASK;
           found_sp_adjust = TRUE;
         }
         else if ((inst & ADJUST_STACKP_V_MASK) == ADJUST_STACKP_V)
         {
           sp_adjust = 0;
           found_sp_adjust = TRUE;
         }
         else if ((inst & SET_UPPER_C_MASK) == SET_UPPER_C)
         {
           const_upper = inst & ~SET_UPPER_C_MASK;
           const_lower = 0;
           found_const_upper = TRUE;
         }
         else if ((inst & OR_LOWER_C_MASK) == OR_LOWER_C)
         {
           const_lower = inst & ~OR_LOWER_C_MASK;
           found_const_lower = TRUE;
         }
         else if ((inst & SET_LOWER_C_MASK) == SET_LOWER_C)
         {
           const_lower = inst & ~SET_LOWER_C_MASK;
           const_upper = 0;
           found_const_lower = TRUE;
         }
         else if (inst == RETURN)
           ra_limit = ra + 2;
         ra++;
       }
       if (sp_adjust == 0 && (found_const_upper || found_const_lower))
         sp_adjust = (const_upper << 16) | const_lower;
       rc->raOffset = ra_offset;
       rc->spAdjust = sp_adjust;
     }
     /* if something went wrong, punt */
     if (rc->spAdjust <= 0)
     {
       *results++ = 0;
       break;
     }
     ra = (unsigned int *) sp[rc->raOffset>>2];
     sp += rc->spAdjust >> 2;
     if (ra == 0)
     {
       *results++ = 0;
       break;
     }
     *results++ = ((unsigned int) ra) - 8;
     if (ra[-2] == mainCall)
     {
       *results++ = 0;
       break;
     }
     max--;
   }
 }
References ADJUST_STACKP_C, ADJUST_STACKP_C_MASK, ADJUST_STACKP_V, ADJUST_STACKP_V_MASK, CALL, FALSE, HASH, main(), max, OR_LOWER_C, OR_LOWER_C_MASK, ps2GetReturnAddress(), ps2GetStackPointer(), ra, RESTORE_RETURNVAL, RESTORE_RETURNVAL2, RESTORE_RETURNVAL3, RESTORE_RETURNVAL_MASK, RETURN, returnCache, SET_LOWER_C, SET_LOWER_C_MASK, SET_UPPER_C, SET_UPPER_C_MASK, sp, and TRUE.
Referenced by TestFunction3().
scr_clear()
void scr_clear (void)
Definition at line 313 of file scr_printf.c.
 {
         int y;
         for(y=0;y<MY;y++)
                 clear_line(y);
         scr_setXY(0,0);
 }
References clear_line(), MY, scr_setXY(), and y.
Referenced by main().
scr_getX()
int scr_getX (void)
Definition at line 303 of file scr_printf.c.
 {
         return X;
 }
References X.
scr_getY()
int scr_getY (void)
Definition at line 308 of file scr_printf.c.
 {
         return Y;
 }
References Y.
Referenced by main().
scr_printf()
void scr_printf (const char * format, ...)
Definition at line 252 of file scr_printf.c.
 {
    va_list      opt;
    char         buff[2048], c;
    int          i, bufsz, j;
    va_start(opt, format);
    bufsz = vsnprintf(buff, sizeof(buff), format, opt);
    for (i = 0; i < bufsz; i++)
        {
        c = buff[i];
        switch (c)
           {
           case          '\n':
                              X = 0;
                              Y ++;
                              if (Y == MY)
                                  Y = 0;
                              clear_line(Y);
                              break;
           case      '\t':
                              for (j = 0; j < 5; j++) {
                                 scr_putchar( X*7 , Y * 8, 0xffffff, ' ');
                                 X++;
                              }
                              break;
           default:
                              scr_putchar( X*7 , Y * 8, 0xffffff, c);
                              X++;
                              if (X == MX)
{
                                 X = 0;
                                 Y++;
                                 if (Y == MY)
                                    Y = 0;
                                 clear_line(Y);
                                 }
           }
        }
     scr_putchar( X*7 , Y * 8, 0xffffff, 219);
     va_end(opt);
 }
References clear_line(), MX, MY, scr_putchar(), X, and Y.
Referenced by ethPrintIPConfig(), ethPrintLinkStatus(), and main().
scr_putchar()
void scr_putchar (int x, int y, u32 color, int ch)
Definition at line 210 of file scr_printf.c.
 {
    static struct t_setupchar setupchar __attribute__((aligned(16))) = {
         { 0x1000000000000004, 0xE, 0xA000000000000, 0x50 }, //GIFtag (REGS: A+D, NREG 1, FLG PACKED, NLOOP 4), BITBLTBUF (DPSM PSMCT32, DBW 10, DBP 0)
         { 0 }, 100, 100, { 0x51 },                          //TRXPOS (DSAX 100, DSAY 100)
         { 8, 8 },                                           //TRXREG (RRW 8, RRH 8)
         { 0x52, 0, 0x53, 0x800000000008010, 0}              //TRXDIR (XDIR Host -> Local), GIFtag (FLG IMAGE, EOP, NLOOP 16)
    };
    /* charmap must be aligned to a 16-bye boundary.  */
    static u32   charmap[64] __attribute__((aligned(16)));
    int  i, j, l;
    u8   *font;
    u32  pixel;
    ((struct t_setupchar*)UNCACHED_SEG(&setupchar))->x = x;
    ((struct t_setupchar*)UNCACHED_SEG(&setupchar))->y = y;
    progdma(&setupchar, 6);
    font = &msx[ ch * 8];
    for (i=l=0; i < 8; i++, l+= 8, font++)
    {
       for (j=0; j < 8; j++)
       {
           pixel = ((*font & (128 >> j))) ? color : bgcolor;
           *(u32*)UNCACHED_SEG(&charmap[ l + j]) = pixel;
       }
    }
    Dma02Wait();
    progdma(charmap, (8*8*4) / 16);
    Dma02Wait();
 }
References bgcolor, Dma02Wait(), msx, progdma(), UNCACHED_SEG, x, and y.
Referenced by clear_line(), and scr_printf().
scr_setbgcolor()
void scr_setbgcolor (u32 color)
Definition at line 180 of file scr_printf.c.
 {
   bgcolor = color;
 }
References bgcolor.
scr_setXY()
void scr_setXY (int x, int y)
Definition at line 297 of file scr_printf.c.
 {
         if( x<MX && x>=0 ) X=x;
         if( y<MY && y>=0 ) Y=y;
 }
References X, x, Y, and y.
Referenced by main(), and scr_clear().