ps2sdk: ee/libgs/src/DoubleBuff.c File Reference
DoubleBuff.c File Reference
#include <errno.h>
#include <stdio.h>
#include <kernel.h>
#include <libgs.h>
#include "internal.h"
Functions
int GsDbGetDrawBuffer (void)
int GsDbGetDisplayBuffer (void)
void GsDbSwapBuffer (void)
Variables
static short int gs_db_draw_buffer =0
Function Documentation
GsDbGetDisplayBuffer()
int GsDbGetDisplayBuffer (void)
Definition at line 25 of file DoubleBuff.c.
 {
         return(gs_db_draw_buffer? 0: 1);
 }
References gs_db_draw_buffer.
Referenced by main().
GsDbGetDrawBuffer()
int GsDbGetDrawBuffer (void)
Definition at line 20 of file DoubleBuff.c.
 {
         return gs_db_draw_buffer;
 }
References gs_db_draw_buffer.
Referenced by main().
GsDbSwapBuffer()
void GsDbSwapBuffer (void)
Definition at line 30 of file DoubleBuff.c.
 {
         gs_db_draw_buffer = gs_db_draw_buffer? 0: 1;
 }
References gs_db_draw_buffer.
Referenced by main().
Variable Documentation
gs_db_draw_buffer
short int gs_db_draw_buffer =0 static
Definition at line 18 of file DoubleBuff.c.
Referenced by GsDbGetDisplayBuffer(), GsDbGetDrawBuffer(), and GsDbSwapBuffer().