ps2sdk: ee/draw/include/draw_buffers.h File Reference
draw_buffers.h File Reference
#include <tamtypes.h>
Data Structures
struct texinfo_t
struct framebuffer_t
struct zbuffer_t
struct texbuffer_t
struct clutbuffer_t
Macros
#define TEXTURE_COMPONENTS_RGB 0
#define TEXTURE_COMPONENTS_RGBA 1
#define TEXTURE_FUNCTION_MODULATE 0
#define TEXTURE_FUNCTION_DECAL 1
#define TEXTURE_FUNCTION_HIGHLIGHT 2
#define TEXTURE_FUNCTION_HIGHLIGHT2 3
#define CLUT_STORAGE_MODE1 0
#define CLUT_STORAGE_MODE2 1
#define CLUT_NO_LOAD 0
#define CLUT_LOAD 1
#define CLUT_LOAD_COPY_CBP0 2
#define CLUT_LOAD_COPY_CBP1 3
#define CLUT_COMPARE_CBP0 4
#define CLUT_COMPARE_CBP1 5
Functions
unsigned char draw_log2 (unsigned int x)
qword_t * draw_framebuffer (qword_t *q, int context, framebuffer_t *frame)
qword_t * draw_zbuffer (qword_t *q, int context, zbuffer_t *zbuffer)
qword_t * draw_texturebuffer (qword_t *q, int context, texbuffer_t *texbuffer, clutbuffer_t *clut)
qword_t * draw_clutbuffer (qword_t *q, int context, int psm, clutbuffer_t *clut)
qword_t * draw_clut_offset (qword_t *q, int cbw, int u, int v)
Detailed Description
Draw library buffer functions
Definition in file draw_buffers.h.
Macro Definition Documentation
CLUT_COMPARE_CBP0
#define CLUT_COMPARE_CBP0 4
Definition at line 30 of file draw_buffers.h.
CLUT_COMPARE_CBP1
#define CLUT_COMPARE_CBP1 5
Definition at line 31 of file draw_buffers.h.
CLUT_LOAD
#define CLUT_LOAD 1
Definition at line 27 of file draw_buffers.h.
CLUT_LOAD_COPY_CBP0
#define CLUT_LOAD_COPY_CBP0 2
Definition at line 28 of file draw_buffers.h.
CLUT_LOAD_COPY_CBP1
#define CLUT_LOAD_COPY_CBP1 3
Definition at line 29 of file draw_buffers.h.
CLUT_NO_LOAD
#define CLUT_NO_LOAD 0
CLUT Load Control
Definition at line 26 of file draw_buffers.h.
CLUT_STORAGE_MODE1
#define CLUT_STORAGE_MODE1 0
CLUT Storage Mode
Definition at line 22 of file draw_buffers.h.
CLUT_STORAGE_MODE2
#define CLUT_STORAGE_MODE2 1
Definition at line 23 of file draw_buffers.h.
TEXTURE_COMPONENTS_RGB
#define TEXTURE_COMPONENTS_RGB 0
Texture Color Components
Definition at line 12 of file draw_buffers.h.
TEXTURE_COMPONENTS_RGBA
#define TEXTURE_COMPONENTS_RGBA 1
Definition at line 13 of file draw_buffers.h.
TEXTURE_FUNCTION_DECAL
#define TEXTURE_FUNCTION_DECAL 1
Definition at line 17 of file draw_buffers.h.
TEXTURE_FUNCTION_HIGHLIGHT
#define TEXTURE_FUNCTION_HIGHLIGHT 2
Definition at line 18 of file draw_buffers.h.
TEXTURE_FUNCTION_HIGHLIGHT2
#define TEXTURE_FUNCTION_HIGHLIGHT2 3
Definition at line 19 of file draw_buffers.h.
TEXTURE_FUNCTION_MODULATE
#define TEXTURE_FUNCTION_MODULATE 0
Texture Function
Definition at line 16 of file draw_buffers.h.
Function Documentation
draw_clut_offset()
qword_t* draw_clut_offset (qword_t * q, int cbw, int u, int v)
CLUT Storage Mode 2 Information
Definition at line 95 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_TEXCLUT(cbw,u,v), GS_REG_TEXCLUT);
         q++;
         return q;
 }
References GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_TEXCLUT, GS_SET_TEXCLUT, and PACK_GIFTAG.
draw_clutbuffer()
qword_t* draw_clutbuffer (qword_t * q, int context, int psm, clutbuffer_t * clut)
CLUT Storage Mode 1 Information
Definition at line 77 of file draw_environment.c.
 {
         if (clut->storage_mode == CLUT_STORAGE_MODE2)
         {
                 clut->start = 0;
         }
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_TEX2(psm,clut->address>>6,clut->psm,clut->storage_mode,clut->start,clut->load_method), GS_REG_TEX2 + context);
         q++;
         return q;
 }
References clutbuffer_t::address, clut, CLUT_STORAGE_MODE2, context, GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_TEX2, GS_SET_TEX2, clutbuffer_t::load_method, PACK_GIFTAG, clutbuffer_t::psm, clutbuffer_t::start, and clutbuffer_t::storage_mode.
draw_framebuffer()
qword_t* draw_framebuffer (qword_t * q, int context, framebuffer_t * frame)
Framebuffer Attributes
Definition at line 33 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_FRAME(frame->address>>11,frame->width>>6,frame->psm,frame->mask), GS_REG_FRAME + context);
         q++;
         return q;
 }
References framebuffer_t::address, context, GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_FRAME, GS_SET_FRAME, framebuffer_t::mask, PACK_GIFTAG, framebuffer_t::psm, and framebuffer_t::width.
Referenced by flip_buffers().
draw_log2()
unsigned char draw_log2 (unsigned int x)
Returns the power of 2 needed for texture width and height
Definition at line 348 of file draw.c.
 {
         unsigned char res;
         __asm__ __volatile__ ("plzcw %0, %1\n\t" : "=r" (res) : "r" (x));
         res = 31 - (res + 1);
         res += (x > (1<<res) ? 1 : 0);
         return res;
 }
References x.
Referenced by InitCB(), run_demo(), set_lod_clut_prim_tex_buff(), and setup_texture().
draw_texturebuffer()
qword_t* draw_texturebuffer (qword_t * q, int context, texbuffer_t * texbuffer, clutbuffer_t * clut)
TextureBuffer Attributes
Definition at line 57 of file draw_environment.c.
 {
         if(clut->storage_mode == CLUT_STORAGE_MODE2)
         {
                 clut->start = 0;
         }
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_TEX0(texture->address>>6,texture->width>>6,texture->psm,
                                                            texture->info.width,texture->info.height,texture->info.components,texture->info.function,
                                                            clut->address>>6,clut->psm,clut->storage_mode,clut->start,clut->load_method), GS_REG_TEX0 + context);
         q++;
         return q;
 }
References texbuffer_t::address, clutbuffer_t::address, clut, CLUT_STORAGE_MODE2, texinfo_t::components, context, texinfo_t::function, GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_TEX0, GS_SET_TEX0, texinfo_t::height, texbuffer_t::info, clutbuffer_t::load_method, PACK_GIFTAG, texbuffer_t::psm, clutbuffer_t::psm, clutbuffer_t::start, clutbuffer_t::storage_mode, texinfo_t::width, and texbuffer_t::width.
Referenced by run_demo(), and setup_texture().
draw_zbuffer()
qword_t* draw_zbuffer (qword_t * q, int context, zbuffer_t * zbuffer)
ZBuffer Attributes
Definition at line 45 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_ZBUF(zbuffer->address>>11,zbuffer->zsm,zbuffer->mask), GS_REG_ZBUF + context);
         q++;
         return q;
 }
References zbuffer_t::address, context, GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_ZBUF, GS_SET_ZBUF, zbuffer_t::mask, PACK_GIFTAG, and zbuffer_t::zsm.