ps2sdk: ee/draw/src/draw_environment.c File Reference
draw_environment.c File Reference
#include <tamtypes.h>
#include <gif_tags.h>
#include <gs_gp.h>
#include <draw.h>
Functions
qword_t * draw_pixel_alpha_control (qword_t *q, int enable)
qword_t * draw_alpha_blending (qword_t *q, int context, blend_t *blend)
qword_t * draw_framebuffer (qword_t *q, int context, framebuffer_t *frame)
qword_t * draw_zbuffer (qword_t *q, int context, zbuffer_t *zbuffer)
qword_t * draw_texturebuffer (qword_t *q, int context, texbuffer_t *texture, clutbuffer_t *clut)
qword_t * draw_clutbuffer (qword_t *q, int context, int psm, clutbuffer_t *clut)
qword_t * draw_clut_offset (qword_t *q, int cbw, int u, int v)
qword_t * draw_dithering (qword_t *q, int enable)
qword_t * draw_dither_matrix (qword_t *q, char *dm)
qword_t * draw_fog_color (qword_t *q, unsigned char r, unsigned char g, unsigned char b)
qword_t * draw_scan_masking (qword_t *q, int mask)
qword_t * draw_color_clamping (qword_t *q, int enable)
qword_t * draw_alpha_correction (qword_t *q, int context, int alpha)
qword_t * draw_primitive_xyoffset (qword_t *q, int context, float x, float y)
qword_t * draw_primitive_override (qword_t *q, int mode)
qword_t * draw_primitive_override_setting (qword_t *q, int context, prim_t *prim)
qword_t * draw_texture_sampling (qword_t *q, int context, lod_t *lod)
qword_t * draw_mipmap1 (qword_t *q, int context, mipmap_t *mipmap)
qword_t * draw_mipmap2 (qword_t *q, int context, mipmap_t *mipmap)
qword_t * draw_scissor_area (qword_t *q, int context, int x0, int x1, int y0, int y1)
qword_t * draw_pixel_test (qword_t *q, int context, atest_t *atest, dtest_t *dtest, ztest_t *ztest)
qword_t * draw_texture_wrapping (qword_t *q, int context, texwrap_t *wrap)
qword_t * draw_texture_expand_alpha (qword_t *q, unsigned char zero_value, int expand, unsigned char one_value)
Function Documentation
draw_alpha_blending()
qword_t* draw_alpha_blending (qword_t * q, int context, blend_t * blend)
Alpha Blending
Definition at line 20 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_ALPHA(blend->color1,blend->color2,blend->alpha,
                                                                 blend->color3,blend->fixed_alpha), GS_REG_ALPHA + context);
         q++;
         return q;
 }
References blend_t::alpha, blend_t::color1, blend_t::color2, blend_t::color3, context, blend_t::fixed_alpha, GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_ALPHA, GS_SET_ALPHA, and PACK_GIFTAG.
draw_alpha_correction()
qword_t* draw_alpha_correction (qword_t * q, int context, int alpha)
Alpha Correction
Definition at line 176 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q,GS_SET_FBA(alpha),GS_REG_FBA + context);
         q++;
         return q;
 }
References context, GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_FBA, GS_SET_FBA, and PACK_GIFTAG.
draw_clut_offset()
qword_t* draw_clut_offset (qword_t * q, int cbw, int u, int v)
CLUT Storage Mode 2 Information
Definition at line 95 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_TEXCLUT(cbw,u,v), GS_REG_TEXCLUT);
         q++;
         return q;
 }
References GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_TEXCLUT, GS_SET_TEXCLUT, and PACK_GIFTAG.
draw_clutbuffer()
qword_t* draw_clutbuffer (qword_t * q, int context, int psm, clutbuffer_t * clut)
CLUT Storage Mode 1 Information
Definition at line 77 of file draw_environment.c.
 {
         if (clut->storage_mode == CLUT_STORAGE_MODE2)
         {
                 clut->start = 0;
         }
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_TEX2(psm,clut->address>>6,clut->psm,clut->storage_mode,clut->start,clut->load_method), GS_REG_TEX2 + context);
         q++;
         return q;
 }
References clutbuffer_t::address, clut, CLUT_STORAGE_MODE2, context, GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_TEX2, GS_SET_TEX2, clutbuffer_t::load_method, PACK_GIFTAG, clutbuffer_t::psm, clutbuffer_t::start, and clutbuffer_t::storage_mode.
draw_color_clamping()
qword_t* draw_color_clamping (qword_t * q, int enable)
Color Masking/Clamping
Definition at line 163 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q,GS_SET_COLCLAMP(enable),GS_REG_COLCLAMP);
         q++;
         return q;
 }
References GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_COLCLAMP, GS_SET_COLCLAMP, and PACK_GIFTAG.
draw_dither_matrix()
qword_t* draw_dither_matrix (qword_t * q, char * dm)
Dithering Matrix
Definition at line 121 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_DIMX(dm[0], dm[1], dm[2], dm[3],
                                                            dm[4], dm[5], dm[6], dm[7],
                                                            dm[8], dm[9], dm[10],dm[11],
                                                            dm[12],dm[13],dm[14],dm[15]), GS_REG_DIMX);
         q++;
         return q;
 }
References GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_DIMX, GS_SET_DIMX, and PACK_GIFTAG.
draw_dithering()
qword_t* draw_dithering (qword_t * q, int enable)
Dithering Switch
Definition at line 108 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_DTHE(enable), GS_REG_DTHE);
         q++;
         return q;
 }
References GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_DTHE, GS_SET_DTHE, and PACK_GIFTAG.
draw_fog_color()
qword_t* draw_fog_color (qword_t * q, unsigned char r, unsigned char g, unsigned char b)
Fog Color
Definition at line 137 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_FOGCOL(r,g,b), GS_REG_FOGCOL);
         q++;
         return q;
 }
References GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_FOGCOL, GS_SET_FOGCOL, and PACK_GIFTAG.
draw_framebuffer()
qword_t* draw_framebuffer (qword_t * q, int context, framebuffer_t * frame)
Framebuffer Attributes
Definition at line 33 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_FRAME(frame->address>>11,frame->width>>6,frame->psm,frame->mask), GS_REG_FRAME + context);
         q++;
         return q;
 }
References framebuffer_t::address, context, GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_FRAME, GS_SET_FRAME, framebuffer_t::mask, PACK_GIFTAG, framebuffer_t::psm, and framebuffer_t::width.
Referenced by flip_buffers().
draw_mipmap1()
qword_t* draw_mipmap1 (qword_t * q, int context, mipmap_t * mipmap)
Mipmap levels 1-3
Definition at line 243 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_MIPTBP1(mipmap->address1,mipmap->width1,
                                                                   mipmap->address2,mipmap->width2,
                                                                   mipmap->address3,mipmap->width3), GS_REG_MIPTBP1 + context);
         q++;
         return q;
 }
References mipmap_t::address1, mipmap_t::address2, mipmap_t::address3, context, GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_MIPTBP1, GS_SET_MIPTBP1, PACK_GIFTAG, mipmap_t::width1, mipmap_t::width2, and mipmap_t::width3.
draw_mipmap2()
qword_t* draw_mipmap2 (qword_t * q, int context, mipmap_t * mipmap)
Mipmap levels 4-6
Definition at line 258 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_MIPTBP2(mipmap->address1,mipmap->width1,
                                                                    mipmap->address2,mipmap->width2,
                                                                    mipmap->address3,mipmap->width3), GS_REG_MIPTBP2 + context);
         q++;
         return q;
 }
References mipmap_t::address1, mipmap_t::address2, mipmap_t::address3, context, GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_MIPTBP2, GS_SET_MIPTBP2, PACK_GIFTAG, mipmap_t::width1, mipmap_t::width2, and mipmap_t::width3.
draw_pixel_alpha_control()
qword_t* draw_pixel_alpha_control (qword_t * q, int enable)
Alpha Blending Per-Pixel MSB Control
Definition at line 8 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_PABE(enable), GS_REG_PABE);
         q++;
         return q;
 }
References GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_PABE, GS_SET_PABE, and PACK_GIFTAG.
draw_pixel_test()
qword_t* draw_pixel_test (qword_t * q, int context, atest_t * atest, dtest_t * dtest, ztest_t * ztest)
Pixel Testing
Definition at line 286 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_TEST(atest->enable,atest->method,atest->compval,atest->keep,
                                                            dtest->enable,dtest->pass,
                                                            ztest->enable,ztest->method), GS_REG_TEST + context);
         q++;
         return q;
 }
References atest_t::compval, context, atest_t::enable, dtest_t::enable, ztest_t::enable, GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_TEST, GS_SET_TEST, atest_t::keep, atest_t::method, ztest_t::method, PACK_GIFTAG, and dtest_t::pass.
draw_primitive_override()
qword_t* draw_primitive_override (qword_t * q, int mode)
Primitive Control
Definition at line 202 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_PRMODECONT(mode),GS_REG_PRMODECONT);
         q++;
         return q;
 }
References GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_PRMODECONT, GS_SET_PRMODECONT, mode, and PACK_GIFTAG.
draw_primitive_override_setting()
qword_t* draw_primitive_override_setting (qword_t * q, int context, prim_t * prim)
Overridden Primitive Attributes
Definition at line 215 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_PRMODE(prim->shading,prim->mapping,prim->fogging,
                                                                  prim->blending,prim->antialiasing,prim->mapping_type,
                                                                  context,prim->colorfix), GS_REG_PRMODE);
         q++;
         return q;
 }
References prim_t::antialiasing, prim_t::blending, prim_t::colorfix, context, prim_t::fogging, GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_PRMODE, GS_SET_PRMODE, prim_t::mapping, prim_t::mapping_type, PACK_GIFTAG, prim, and prim_t::shading.
draw_primitive_xyoffset()
qword_t* draw_primitive_xyoffset (qword_t * q, int context, float x, float y)
Primitive Coordinate System offset
Definition at line 189 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_XYOFFSET((int)(x*16.0f),(int)(y*16.0f)), GS_REG_XYOFFSET + context);
         q++;
         return q;
 }
References context, GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_XYOFFSET, GS_SET_XYOFFSET, PACK_GIFTAG, x, and y.
Referenced by init_drawing_environment().
draw_scan_masking()
qword_t* draw_scan_masking (qword_t * q, int mask)
Scanline Masking (framebuffer)
Definition at line 150 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q,GS_SET_SCANMSK(mask),GS_REG_SCANMSK);
         q++;
         return q;
 }
References GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_SCANMSK, GS_SET_SCANMSK, and PACK_GIFTAG.
draw_scissor_area()
qword_t* draw_scissor_area (qword_t * q, int context, int x0, int x1, int y0, int y1)
Scissoring pixel test area
Definition at line 273 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_SCISSOR(x0,x1,y0,y1), GS_REG_SCISSOR + context);
         q++;
         return q;
 }
References context, GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_SCISSOR, GS_SET_SCISSOR, and PACK_GIFTAG.
draw_texture_expand_alpha()
qword_t* draw_texture_expand_alpha (qword_t * q, unsigned char zero_value, int expand, unsigned char one_value)
Alpha Expansion Values
Definition at line 315 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_TEXA(zero_value,expand,one_value), GS_REG_TEXA);
         q++;
         return q;
 }
References GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_TEXA, GS_SET_TEXA, and PACK_GIFTAG.
draw_texture_sampling()
qword_t* draw_texture_sampling (qword_t * q, int context, lod_t * lod)
Texture Sampling, Level-of-Detail, and Filtering
Definition at line 230 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_TEX1(lod->calculation,lod->max_level,lod->mag_filter,lod->min_filter,lod->mipmap_select,lod->l,(int)(lod->k*16.0f)), GS_REG_TEX1 + context);
         q++;
         return q;
 }
References lod_t::calculation, context, GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_TEX1, GS_SET_TEX1, lod_t::k, lod_t::l, lod, lod_t::mag_filter, lod_t::max_level, lod_t::min_filter, lod_t::mipmap_select, and PACK_GIFTAG.
Referenced by run_demo(), and setup_texture().
draw_texture_wrapping()
qword_t* draw_texture_wrapping (qword_t * q, int context, texwrap_t * wrap)
Texture Clamping
Definition at line 301 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_CLAMP(wrap->horizontal,wrap->vertical,wrap->minu,
                                                                 wrap->maxu,wrap->minv,wrap->maxv), GS_REG_CLAMP + context);
         q++;
         return q;
 }
References context, GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_CLAMP, GS_SET_CLAMP, texwrap_t::horizontal, texwrap_t::maxu, texwrap_t::maxv, texwrap_t::minu, texwrap_t::minv, PACK_GIFTAG, and texwrap_t::vertical.
draw_texturebuffer()
qword_t* draw_texturebuffer (qword_t * q, int context, texbuffer_t * texbuffer, clutbuffer_t * clut)
TextureBuffer Attributes
Definition at line 57 of file draw_environment.c.
 {
         if(clut->storage_mode == CLUT_STORAGE_MODE2)
         {
                 clut->start = 0;
         }
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_TEX0(texture->address>>6,texture->width>>6,texture->psm,
                                                            texture->info.width,texture->info.height,texture->info.components,texture->info.function,
                                                            clut->address>>6,clut->psm,clut->storage_mode,clut->start,clut->load_method), GS_REG_TEX0 + context);
         q++;
         return q;
 }
References texbuffer_t::address, clutbuffer_t::address, clut, CLUT_STORAGE_MODE2, texinfo_t::components, context, texinfo_t::function, GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_TEX0, GS_SET_TEX0, texinfo_t::height, texbuffer_t::info, clutbuffer_t::load_method, PACK_GIFTAG, texbuffer_t::psm, clutbuffer_t::psm, clutbuffer_t::start, clutbuffer_t::storage_mode, texinfo_t::width, and texbuffer_t::width.
Referenced by run_demo(), and setup_texture().
draw_zbuffer()
qword_t* draw_zbuffer (qword_t * q, int context, zbuffer_t * zbuffer)
ZBuffer Attributes
Definition at line 45 of file draw_environment.c.
 {
         PACK_GIFTAG(q, GIF_SET_TAG(1,0,0,0,GIF_FLG_PACKED,1), GIF_REG_AD);
         q++;
         PACK_GIFTAG(q, GS_SET_ZBUF(zbuffer->address>>11,zbuffer->zsm,zbuffer->mask), GS_REG_ZBUF + context);
         q++;
         return q;
 }
References zbuffer_t::address, context, GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, GS_REG_ZBUF, GS_SET_ZBUF, zbuffer_t::mask, PACK_GIFTAG, and zbuffer_t::zsm.