ps2sdk: ee/draw/include/draw3d.h File Reference
draw3d.h File Reference
#include <tamtypes.h>
#include <draw_primitives.h>
#include <draw_types.h>
#include <gif_tags.h>
Macros
#define DRAW_XYZ_REGLIST
#define DRAW_RGBAQ_REGLIST
#define DRAW_UV_REGLIST
#define DRAW_RGBAQ_UV_REGLIST
#define DRAW_STQ_REGLIST
#define DRAW_STQ2_REGLIST
Functions
qword_t * draw_prim_start (qword_t *q, int context, prim_t *prim, color_t *color)
qword_t * draw_prim_end (qword_t *q, int nreg, u64 reglist)
int draw_convert_rgbq (color_t *output, int count, vertex_f_t *vertices, color_f_t *colours, unsigned char alpha)
int draw_convert_rgbaq (color_t *output, int count, vertex_f_t *vertices, color_f_t *colours)
int draw_convert_st (texel_t *output, int count, vertex_f_t *vertices, texel_f_t *coords)
int draw_convert_xyz (xyz_t *output, float x, float y, int z, int count, vertex_f_t *vertices)
Detailed Description
Draw library 3D functions
Definition in file draw3d.h.
Macro Definition Documentation
DRAW_RGBAQ_REGLIST
#define DRAW_RGBAQ_REGLIST
Value:
        ((u64)GIF_REG_RGBAQ) <<  0 | \
        ((u64)GIF_REG_XYZ2)  <<  4
Definition at line 20 of file draw3d.h.
DRAW_RGBAQ_UV_REGLIST
#define DRAW_RGBAQ_UV_REGLIST
Value:
        ((u64)GIF_REG_RGBAQ)  << 0 | \
        ((u64)GIF_REG_UV)     << 4 | \
        ((u64)GIF_REG_XYZ2)   << 8
Definition at line 28 of file draw3d.h.
DRAW_STQ2_REGLIST
#define DRAW_STQ2_REGLIST
Value:
        ((u64)GIF_REG_ST)     << 0 | \
        ((u64)GIF_REG_RGBAQ)  << 4 | \
        ((u64)GIF_REG_XYZ2)   << 8
Sandro: Similar to DRAW_STQ_REGLIST, but order of ST and RGBAQ is swapped. Needed for REGLIST mode which is used mostly in VU1, because of nature of 128bit registers. Without that, texture perspective correction will not work. Bad example:
RGBA -> RGBAQ (q was not set!)
STQ -> ST
XYZ2 Good example:
STQ -> ST
RGBA -> RGBAQ (q grabbed from STQ)
XYZ2 For more details, please check: EE_Overview_Manual.pdf - 3.3 Data transfer to GS GS_Users_Manual.pdf - 3.4.10 Perspective correction
Definition at line 55 of file draw3d.h.
DRAW_STQ_REGLIST
#define DRAW_STQ_REGLIST
Value:
        ((u64)GIF_REG_RGBAQ)  << 0 | \
        ((u64)GIF_REG_ST)     << 4 | \
        ((u64)GIF_REG_XYZ2)   << 8
Definition at line 33 of file draw3d.h.
DRAW_UV_REGLIST
#define DRAW_UV_REGLIST
Value:
        ((u64)GIF_REG_UV)   << 0 | \
        ((u64)GIF_REG_XYZ2) << 4
Definition at line 24 of file draw3d.h.
DRAW_XYZ_REGLIST
#define DRAW_XYZ_REGLIST
Value:
        ((u64)GIF_REG_XYZ2) << 0 | \
        ((u64)GIF_REG_XYZ2) << 4
Register lists
Definition at line 16 of file draw3d.h.
Function Documentation
draw_convert_rgbaq()
int draw_convert_rgbaq (color_t * output, int count, vertex_f_t * vertices, color_f_t * colours)
Converts floating point color and calculates q value
Definition at line 88 of file draw3d.c.
 {
         int i;
         float q = 1.00f;
         // For each colour...
         for (i=0;i<count;i++)
         {
                 // Calculate the Q value.
                 if (vertices[i].w != 0)
                 {
                         q = 1 / vertices[i].w;
                 }
                 // Calculate the RGBA values.
                 output[i].r = (int)(colours[i].r * 128.0f);
                 output[i].g = (int)(colours[i].g * 128.0f);
                 output[i].b = (int)(colours[i].b * 128.0f);
                 output[i].a = (int)(colours[i].a * 128.0f);
                 output[i].q = q;
         }
         // End function.
         return 0;
 }
References color_t::a, color_t::b, colours, color_t::g, color_t::q, color_t::r, and vertices.
draw_convert_rgbq()
int draw_convert_rgbq (color_t * output, int count, vertex_f_t * vertices, color_f_t * colours, unsigned char alpha)
Converts floating point color, replacing alpha with constant value, and calculates q
Definition at line 56 of file draw3d.c.
 {
         int i;
         float q = 1.00f;
         // For each colour...
         for (i=0;i<count;i++)
         {
                 // Calculate the Q value.
                 if (vertices[i].w != 0)
                 {
                         q = 1 / vertices[i].w;
                 }
                 // Calculate the RGBA values.
                 output[i].r = (int)(colours[i].r * 128.0f);
                 output[i].g = (int)(colours[i].g * 128.0f);
                 output[i].b = (int)(colours[i].b * 128.0f);
                 output[i].a = alpha;
                 output[i].q = q;
         }
         // End function.
         return 0;
 }
References color_t::a, color_t::b, colours, color_t::g, color_t::q, color_t::r, and vertices.
Referenced by render(), and render_teapot().
draw_convert_st()
int draw_convert_st (texel_t * output, int count, vertex_f_t * vertices, texel_f_t * coords)
Calculates the st coordinates from the perspective coordinate q = 1/w
Definition at line 120 of file draw3d.c.
 {
         int i = 0;
         float q = 1.00f;
         // For each coordinate...
         for (i=0;i<count;i++)
         {
                 // Calculate the Q value.
                 if (vertices[i].w != 0)
                 {
                         q = 1 / vertices[i].w;
                 }
                 // Calculate the S and T values.
                 output[i].s = coords[i].s * q;
                 output[i].t = coords[i].t * q;
         }
         // End function.
         return 0;
 }
References texel_t::s, texel_f_t::s, texel_t::t, texel_f_t::t, and vertices.
Referenced by render().
draw_convert_xyz()
int draw_convert_xyz (xyz_t * output, float x, float y, int z, int count, vertex_f_t * vertices)
Converts and translates floating point vertices to fixed point vertices
Definition at line 147 of file draw3d.c.
 {
         int i;
         int center_x;
         int center_y;
         unsigned int max_z;
         center_x = ftoi4(x);
         center_y = ftoi4(y);
         max_z = 1 << (z - 1);
         // For each colour...
         for (i=0;i<count;i++)
         {
                 // Calculate the XYZ values.
                 output[i].x = (short)((vertices[i].x + 1.0f) * center_x);
                 output[i].y = (short)((vertices[i].y + 1.0f) * -center_y);
                 output[i].z = (unsigned int)((vertices[i].z + 1.0f) * max_z);
         }
         // End function.
         return 0;
 }
References ftoi4, vertices, xyz_t::x, x, xyz_t::y, y, and xyz_t::z.
Referenced by render(), and render_teapot().
draw_prim_end()
qword_t* draw_prim_end (qword_t * q, int nreg, u64 reglist)
Ends a primitive by calculating the number of qwords used, the number of registers, the register list
Definition at line 33 of file draw3d.c.
 {
         u32 vertex_qwords;
         u32 vertex_loops;
         // Determine number qwords that were needed minus the reglist giftag
         vertex_qwords = q - __prim_start - 1;
         // Determine number of loops based on qwords used and number of regs per loop
         vertex_loops = (vertex_qwords * 2) / nreg;
         // Now set the giftag of the vertex reglist chain
         __prim_start->dw[0] = GIF_SET_TAG(vertex_loops,1,0,0,GIF_FLG_REGLIST,nreg);
         // Set the higher 64bits to the reglist
         __prim_start->dw[1] = reglist;
         // Return the current qword pointer
         return q;
 }
References __prim_start, qword_t::dw, GIF_FLG_REGLIST, and GIF_SET_TAG.
Referenced by fontstudio_print_string(), fontx_print_ascii(), fontx_print_sjis(), render(), and render_teapot().
draw_prim_start()
qword_t* draw_prim_start (qword_t * q, int context, prim_t * prim, color_t * color)
Begins a primitive, allowing for vertex data to be filled in the packet directly
Definition at line 11 of file draw3d.c.
 {
         // Set the primitive register in packed mode, but don't end the packet
         PACK_GIFTAG(q,GIF_SET_TAG(2,0,0,0,GIF_FLG_PACKED,1),GIF_REG_AD);
         q++;
         PACK_GIFTAG(q,GS_SET_PRIM(prim->type,prim->shading,prim->mapping,prim->fogging,
                                                           prim->blending,prim->antialiasing,prim->mapping_type,
                                                           context,prim->colorfix),GS_REG_PRIM);
         q++;
         PACK_GIFTAG(q,color->rgbaq,GIF_REG_RGBAQ);
         q++;
         // Save the position for the reglist giftag that draw_primitive_end will add
         __prim_start = q;
         q++;
         // Return the current qword pointer
         return q;
 }
References __prim_start, prim_t::antialiasing, prim_t::blending, prim_t::colorfix, context, prim_t::fogging, GIF_FLG_PACKED, GIF_REG_AD, GIF_REG_RGBAQ, GIF_SET_TAG, GS_REG_PRIM, GS_SET_PRIM, prim_t::mapping, prim_t::mapping_type, PACK_GIFTAG, prim, color_t::rgbaq, prim_t::shading, and prim_t::type.
Referenced by fontstudio_print_string(), fontx_print_ascii(), fontx_print_sjis(), render(), and render_teapot().