ps2sdk: ee/eedebug/include/ee_debug.h File Reference
ee_debug.h File Reference
#include <tamtypes.h>
#include <ee_cop0_defs.h>
#include <ps2_debug.h>
Typedefs
typedef int() EE_ExceptionHandler(struct st_EE_RegFrame *)
Functions
int ee_dbg_install (int levels)
int ee_dbg_remove (int levels)
EE_ExceptionHandler * ee_dbg_get_level1_handler (int cause)
EE_ExceptionHandler * ee_dbg_set_level1_handler (int cause, EE_ExceptionHandler *handler)
EE_ExceptionHandler * ee_dbg_get_level2_handler (int cause)
EE_ExceptionHandler * ee_dbg_set_level2_handler (int cause, EE_ExceptionHandler *handler)
u32 ee_dbg_get_bpc (void)
void ee_dbg_set_bpc (u32)
u32 ee_dbg_get_iab (void)
void ee_dbg_set_iab (u32)
u32 ee_dbg_get_iabm (void)
void ee_dbg_set_iabm (u32)
u32 ee_dbg_get_dab (void)
void ee_dbg_set_dab (u32)
u32 ee_dbg_get_dabm (void)
void ee_dbg_set_dabm (u32)
u32 ee_dbg_get_dvb (void)
void ee_dbg_set_dvb (u32)
u32 ee_dbg_get_dvbm (void)
void ee_dbg_set_dvbm (u32)
void ee_dbg_set_bpr (u32 addr, u32 mask, u32 opmode_mask)
void ee_dbg_set_bpw (u32 addr, u32 mask, u32 opmode_mask)
void ee_dbg_set_bpv (u32 value, u32 mask, u32 opmode_mask)
void ee_dbg_set_bpx (u32 addr, u32 mask, u32 opmode_mask)
void ee_dbg_clr_bps (void)
void ee_dbg_clr_bpda (void)
void ee_dbg_clr_bpdv (void)
void ee_dbg_clr_bpx (void)
Detailed Description
EEDEBUG - EE debugging library. Definitions for the EEDEBUG library.
Definition in file ee_debug.h.
Typedef Documentation
EE_ExceptionHandler
typedef int() EE_ExceptionHandler(struct st_EE_RegFrame *)
Definition at line 28 of file ee_debug.h.
Function Documentation
ee_dbg_clr_bpda()
void ee_dbg_clr_bpda (void)
Definition at line 120 of file ee_debug.c.
 {
     u32 bpc = ee_dbg_get_bpc();
     bpc &= ~(EE_BPC_DWE | EE_BPC_DRE);
     if(!(bpc & (EE_BPC_DVE)))
     {
         // if Data Value breakpoint not enabled, disable all Data bp bits.
         bpc &= ~(EE_BPC_DUE | EE_BPC_DSE | EE_BPC_DKE | EE_BPC_DXE | EE_BPC_DTE);
     }
     ee_dbg_set_bpc(bpc);
 }
References EE_BPC_DKE, EE_BPC_DRE, EE_BPC_DSE, EE_BPC_DTE, EE_BPC_DUE, EE_BPC_DVE, EE_BPC_DWE, EE_BPC_DXE, ee_dbg_get_bpc(), and ee_dbg_set_bpc().
ee_dbg_clr_bpdv()
void ee_dbg_clr_bpdv (void)
Definition at line 135 of file ee_debug.c.
 {
     u32 bpc = ee_dbg_get_bpc();
     bpc &= ~(EE_BPC_DVE);
     if(!(bpc & (EE_BPC_DWE | EE_BPC_DRE)))
     {
         // if Data Read or Data Write breakpoints not enabled, disable all Data bp bits.
         bpc &= ~(EE_BPC_DUE | EE_BPC_DSE | EE_BPC_DKE | EE_BPC_DXE | EE_BPC_DTE);
     }
     ee_dbg_set_bpc(bpc);
 }
References EE_BPC_DKE, EE_BPC_DRE, EE_BPC_DSE, EE_BPC_DTE, EE_BPC_DUE, EE_BPC_DVE, EE_BPC_DWE, EE_BPC_DXE, ee_dbg_get_bpc(), and ee_dbg_set_bpc().
ee_dbg_clr_bps()
void ee_dbg_clr_bps (void)
Definition at line 157 of file ee_debug.c.
 {
     ee_dbg_set_bpc(EE_BPC_BED);
     ee_dbg_set_iab(0);
     ee_dbg_set_iabm(0);
     ee_dbg_set_dab(0);
     ee_dbg_set_dabm(0);
     ee_dbg_set_dvb(0);
     ee_dbg_set_dvbm(0);
 }
References EE_BPC_BED, ee_dbg_set_bpc(), ee_dbg_set_dab(), ee_dbg_set_dabm(), ee_dbg_set_dvb(), ee_dbg_set_dvbm(), ee_dbg_set_iab(), and ee_dbg_set_iabm().
Referenced by ee_dbg_install(), and ee_dbg_remove().
ee_dbg_clr_bpx()
void ee_dbg_clr_bpx (void)
Definition at line 150 of file ee_debug.c.
 {
     u32 bpc = ee_dbg_get_bpc();
     bpc &= ~(EE_BPC_IXE | EE_BPC_IUE | EE_BPC_ISE | EE_BPC_IKE | EE_BPC_IXE | EE_BPC_ITE);
     ee_dbg_set_bpc(bpc);
 }
References EE_BPC_IKE, EE_BPC_ISE, EE_BPC_ITE, EE_BPC_IUE, EE_BPC_IXE, ee_dbg_get_bpc(), and ee_dbg_set_bpc().
ee_dbg_get_bpc()
u32 ee_dbg_get_bpc (void)
Referenced by ee_dbg_clr_bpda(), ee_dbg_clr_bpdv(), and ee_dbg_clr_bpx().
ee_dbg_get_dab()
u32 ee_dbg_get_dab (void)
ee_dbg_get_dabm()
u32 ee_dbg_get_dabm (void)
ee_dbg_get_dvb()
u32 ee_dbg_get_dvb (void)
ee_dbg_get_dvbm()
u32 ee_dbg_get_dvbm (void)
ee_dbg_get_iab()
u32 ee_dbg_get_iab (void)
ee_dbg_get_iabm()
u32 ee_dbg_get_iabm (void)
ee_dbg_get_level1_handler()
EE_ExceptionHandler* ee_dbg_get_level1_handler (int cause)
Definition at line 53 of file ee_debug.c.
 {
     if((cause < 0) || (cause > 13)) { return(NULL); }
     return(ee_level1_exception_handlers[cause]);
 }
References ee_level1_exception_handlers, and NULL.
ee_dbg_get_level2_handler()
EE_ExceptionHandler* ee_dbg_get_level2_handler (int cause)
Definition at line 77 of file ee_debug.c.
 {
     if((cause < 0) || (cause > 3)) { return(NULL); }
     return(ee_level2_exception_handlers[cause]);
 }
References ee_level2_exception_handlers, and NULL.
ee_dbg_install()
int ee_dbg_install (int levels)
Definition at line 171 of file ee_debug.c.
 {
     u32 oldintr, oldop;
     int i;
     if(_installed_levels & levels)
     {
         return(-1);
     }
     if(levels & 1)
     {
         for(i = 0; i < 16; i++) { ee_level1_exception_handlers[i] = NULL; }
     }
     if(levels & 2)
     {
         for(i = 0; i < 4; i++) { ee_level2_exception_handlers[i] = NULL; }
         oldintr = DIntr();
         oldop = ee_set_opmode(0);
         ee_dbg_clr_bps();
         // save the original level 2 debug exception vector.
         memcpy(&__saved_dbg_ex_vector, (void *) (0x80000100), 0x80);
         // replace the level 2 debug exception vector with our own
         memcpy((void *) (0x80000100), &__ee_level2_ex_vector, 32);
         ee_set_opmode(oldop);
         if(oldintr) { EIntr(); }
     }
     if(levels & 1)
     {
         // redirect desirable "Level 1" exceptions to our level 1 handler.
         for(i = 1; i <= 3; i++)
         {
             _old_l1_handlers[i] = GetExceptionHandler(i);
             SetVTLBRefillHandler(i, __ee_level1_ex_vector);
         }
         for(i = 4; i <= 7; i++)
         {
             _old_l1_handlers[i] = GetExceptionHandler(i);
             SetVCommonHandler(i, __ee_level1_ex_vector);
         }
         for(i = 10; i <= 13; i++)
         {
             _old_l1_handlers[i] = GetExceptionHandler(i);
             SetVCommonHandler(i, __ee_level1_ex_vector);
         }
     }
     FlushCache(0);
     FlushCache(2);
     _installed_levels |= levels;
     return(0);
 }
References __ee_level1_ex_vector(), __ee_level2_ex_vector(), __saved_dbg_ex_vector, _installed_levels, _old_l1_handlers, DIntr(), ee_dbg_clr_bps(), ee_level1_exception_handlers, ee_level2_exception_handlers, ee_set_opmode(), EIntr(), FlushCache(), GetExceptionHandler(), NULL, SetVCommonHandler(), and SetVTLBRefillHandler().
ee_dbg_remove()
int ee_dbg_remove (int levels)
Definition at line 235 of file ee_debug.c.
 {
     u32 oldintr, oldop;
     int i;
     if((levels < 1) || (levels > 3)) { return(-1); }
     if(!(_installed_levels & levels)) { return(-1); }
     if((levels & _installed_levels) & 2)
     {
         oldintr = DIntr();
         oldop = ee_set_opmode(0);
         ee_dbg_clr_bps();
         // restore the original debug exception vector.
         memcpy((void *) (0x80000100), &__saved_dbg_ex_vector, sizeof(__saved_dbg_ex_vector));
         ee_set_opmode(oldop);
         if(oldintr) { EIntr(); }
         FlushCache(0);
         FlushCache(2);
         _installed_levels &= 1;
     }
     if((levels & _installed_levels) & 1)
     {
         // restore the exception handlers that we previously hooked.
         for(i = 1; i <= 3; i++)
         {
             if(_old_l1_handlers[i] != NULL)
             {
                 SetVTLBRefillHandler(i, _old_l1_handlers[i]);
                 _old_l1_handlers[i] = NULL;
             }
         }
         for(i = 4; i <= 7; i++)
         {
             if(_old_l1_handlers[i] != NULL)
             {
                 SetVCommonHandler(i, _old_l1_handlers[i]);
                 _old_l1_handlers[i] = NULL;
             }
         }
         for(i = 10; i <= 13; i++)
         {
             if(_old_l1_handlers[i] != NULL)
             {
                 SetVCommonHandler(i, _old_l1_handlers[i]);
                 _old_l1_handlers[i] = NULL;
             }
         }
         FlushCache(0);
         FlushCache(2);
         _installed_levels &= 2;
     }
     return(0);
 }
References __saved_dbg_ex_vector, _installed_levels, _old_l1_handlers, DIntr(), ee_dbg_clr_bps(), ee_set_opmode(), EIntr(), FlushCache(), NULL, SetVCommonHandler(), and SetVTLBRefillHandler().
ee_dbg_set_bpc()
void ee_dbg_set_bpc (u32)
Referenced by ee_dbg_clr_bpda(), ee_dbg_clr_bpdv(), ee_dbg_clr_bps(), and ee_dbg_clr_bpx().
ee_dbg_set_bpr()
void ee_dbg_set_bpr (u32 addr, u32 mask, u32 opmode_mask)
Definition at line 106 of file ee_debug.c.
 { _ee_dbg_set_bpda(addr, mask, EE_BPC_DRE | opmode_mask); }
References _ee_dbg_set_bpda(), and EE_BPC_DRE.
ee_dbg_set_bpv()
void ee_dbg_set_bpv (u32 value, u32 mask, u32 opmode_mask)
Definition at line 115 of file ee_debug.c.
 { _ee_dbg_set_bpdv(value, mask, opmode_mask); }
References _ee_dbg_set_bpdv().
ee_dbg_set_bpw()
void ee_dbg_set_bpw (u32 addr, u32 mask, u32 opmode_mask)
Definition at line 109 of file ee_debug.c.
 { _ee_dbg_set_bpda(addr, mask, EE_BPC_DWE | opmode_mask); }
References _ee_dbg_set_bpda(), and EE_BPC_DWE.
ee_dbg_set_bpx()
void ee_dbg_set_bpx (u32 addr, u32 mask, u32 opmode_mask)
Definition at line 118 of file ee_debug.c.
 { _ee_dbg_set_bpx(addr, mask, opmode_mask); }
References _ee_dbg_set_bpx().
ee_dbg_set_dab()
void ee_dbg_set_dab (u32)
Referenced by ee_dbg_clr_bps().
ee_dbg_set_dabm()
void ee_dbg_set_dabm (u32)
Referenced by ee_dbg_clr_bps().
ee_dbg_set_dvb()
void ee_dbg_set_dvb (u32)
Referenced by ee_dbg_clr_bps().
ee_dbg_set_dvbm()
void ee_dbg_set_dvbm (u32)
Referenced by ee_dbg_clr_bps().
ee_dbg_set_iab()
void ee_dbg_set_iab (u32)
Referenced by ee_dbg_clr_bps().
ee_dbg_set_iabm()
void ee_dbg_set_iabm (u32)
Referenced by ee_dbg_clr_bps().
ee_dbg_set_level1_handler()
EE_ExceptionHandler* ee_dbg_set_level1_handler (int cause, EE_ExceptionHandler * handler)
Definition at line 60 of file ee_debug.c.
 {
     EE_ExceptionHandler *old_handler;
     u32 oldintr;
     if((cause < 0) || (cause > 13)) { return(NULL); }
     oldintr = DIntr();
     old_handler = ee_level1_exception_handlers[cause];
     ee_level1_exception_handlers[cause] = handler;
     if(oldintr) { EIntr(); }
     return(old_handler);
 }
References DIntr(), ee_level1_exception_handlers, EIntr(), and NULL.
ee_dbg_set_level2_handler()
EE_ExceptionHandler* ee_dbg_set_level2_handler (int cause, EE_ExceptionHandler * handler)
Definition at line 84 of file ee_debug.c.
 {
     EE_ExceptionHandler *old_handler;
     u32 oldintr;
     if((cause < 0) || (cause > 3)) { return(NULL); }
     oldintr = DIntr();
     old_handler = ee_level2_exception_handlers[cause];
     ee_level2_exception_handlers[cause] = handler;
     if(oldintr) { EIntr(); }
     return(old_handler);
 }
References DIntr(), ee_level2_exception_handlers, EIntr(), and NULL.