ps2sdk: ee/elf-loader/src/elf.c File Reference
elf.c File Reference
#include <string.h>
#include <sifrpc.h>
#include <kernel.h>
#include <sys/stat.h>
#include <stdbool.h>
#include <malloc.h>
#include "elf.h"
Macros
#define ELF_MAGIC 0x464c457f
#define ELF_PT_LOAD 1
Functions
static bool file_exists (const char *filename)
int LoadELFFromFile (const char *filename, int argc, char *argv[])
Variables
u8 loader_elf []
int size_loader_elf
Macro Definition Documentation
ELF_MAGIC
#define ELF_MAGIC 0x464c457f
Definition at line 25 of file elf.c.
ELF_PT_LOAD
#define ELF_PT_LOAD 1
Definition at line 26 of file elf.c.
Function Documentation
file_exists()
static bool file_exists (const char * filename) static
Definition at line 28 of file elf.c.
{
         struct stat   buffer;
         return (stat (filename, &buffer) == 0);
 }
References buffer.
Referenced by LoadELFFromFile().
LoadELFFromFile()
int LoadELFFromFile (const char * filename, int argc, char * argv[])
Definition at line 33 of file elf.c.
 {
         u8 *boot_elf;
         elf_header_t *eh;
         elf_pheader_t *eph;
         void *pdata;
         int i;
         int new_argc = argc + 1;
         // We need to check that the ELF file before continue
         if (!file_exists(filename)) {
                 return -1; // ELF file doesn't exists
         }
         // ELF Exists
         char *new_argv[new_argc];
         new_argv[0] = (char *)filename;
         for (i = 0; i < argc; i++) {
                 new_argv[i + 1] = argv[i];
         }
         /* NB: LOADER.ELF is embedded  */
         boot_elf = (u8 *)loader_elf;
         eh = (elf_header_t *)boot_elf;
         if (_lw((u32)&eh->ident) != ELF_MAGIC)
                 asm volatile("break\n");
         eph = (elf_pheader_t *)(boot_elf + eh->phoff);
         /* Scan through the ELF's program headers and copy them into RAM, then zero out any non-loaded regions.  */
         for (i = 0; i < eh->phnum; i++) {
                 if (eph[i].type != ELF_PT_LOAD)
                         continue;
                 pdata = (void *)(boot_elf + eph[i].offset);
                 memcpy(eph[i].vaddr, pdata, eph[i].filesz);
                 if (eph[i].memsz > eph[i].filesz)
                         memset(eph[i].vaddr + eph[i].filesz, 0, eph[i].memsz - eph[i].filesz);
         }
         /* Let's go.  */
         SifExitRpc();
         FlushCache(0);
         FlushCache(2);
         return ExecPS2((void *)eh->entry, NULL, new_argc, new_argv);
 }
References _lw(), ELF_MAGIC, ELF_PT_LOAD, elf_header_t::entry, ExecPS2(), file_exists(), FlushCache(), elf_header_t::ident, loader_elf, NULL, elf_header_t::phnum, elf_header_t::phoff, and SifExitRpc().
Variable Documentation
loader_elf
u8 loader_elf[] extern
Referenced by LoadELFFromFile().
size_loader_elf
int size_loader_elf extern