ps2sdk: ee/erl-loader/src/erl-loader.c File Reference
erl-loader.c File Reference
#include <string.h>
#include <erl.h>
Data Structures
struct export_list_t
Typedefs
typedef void(* func_t) (void)
Functions
static void parse_boot_path (int argc, char **argv)
static void export_symbols ()
int main (int argc, char **argv)
Variables
struct export_list_t export_list []
static char * prohibit_list []
Typedef Documentation
func_t
typedef void(* func_t) (void)
Definition at line 67 of file erl-loader.c.
Function Documentation
export_symbols()
static void export_symbols () static
Definition at line 50 of file erl-loader.c.
{
     struct export_list_t * p;
     int i, prohibit;
     for (p = export_list; p->name; p++) {
         prohibit = 0;
         for (i = 0; prohibit_list[i]; i++) {
             if (!(strcmp(prohibit_list[i], p->name))) {
                 prohibit = 1;
                 break;
             }
         }
         if (!prohibit)
             erl_add_global_symbol(p->name, (u32) p->pointer);
     }
 }
References erl_add_global_symbol(), export_list, export_list_t::name, export_list_t::pointer, and prohibit_list.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 69 of file erl-loader.c.
{
     struct symbol_t * s;
     int i;
     parse_boot_path(argc, argv);
     export_symbols();
     if (argc >= 2) {
         for (i = 1; i < argc; i++) {
             _init_load_erl_from_file(argv[i], 0);
         }
     } else {
         _init_load_erl_from_file("main.erl", 0);
     }
     if ((s = erl_find_symbol("main"))) {
         ((func_t) s->address)();
     }
     return 0;
 }
References _init_load_erl_from_file(), erl_find_symbol(), export_symbols(), parse_boot_path(), and s.
parse_boot_path()
static void parse_boot_path (int argc, char ** argv) static
Definition at line 21 of file erl-loader.c.
{
     char * p;
     if (argc == 0) // Are people still using naplink ? :P
         strcpy(_init_erl_prefix, "host:");
     strcpy(_init_erl_prefix, argv[0]);
     p = strrchr(_init_erl_prefix, '/');
     if (!p)
         p = strrchr(_init_erl_prefix, '\\');
     if (!p)
         p = strrchr(_init_erl_prefix, ':');
     if (!p)
         return;
     *(++p) = 0;
     _init_erl_prefix[p - _init_erl_prefix] = 0;
 }
References _init_erl_prefix.
Referenced by main().
Variable Documentation
export_list
struct export_list_t export_list[]
Referenced by export_symbols().
prohibit_list
char* prohibit_list[] static
Initial value:
= {
    "_edata", "_end", "_end_bss", "_fbss", "_fdata", "_fini",
    "_ftext", "_gp", "_init", "main",
    0
}
Definition at line 44 of file erl-loader.c.
Referenced by export_symbols().