ps2sdk: ee/erl/include/erl.h File Reference
erl.h File Reference
#include <tamtypes.h>
Data Structures
struct erl_loader_t
struct symbol_t
Macros
#define ERL_FLAG_STICKY 1
#define ERL_FLAG_STATIC 2
#define ERL_FLAG_CLEAR 4
#define ERL_DYN_ADDR 0
Functions
struct erl_record_t * load_erl_from_mem (u8 *mem, int argc, char **argv)
struct erl_record_t * load_erl_from_file (const char *fname, int argc, char **argv)
struct erl_record_t * _init_load_erl_from_file (const char *fname, char *erl_id)
struct erl_record_t * load_erl_from_mem_to_addr (u8 *mem, u32 addr, int argc, char **argv)
struct erl_record_t * load_erl_from_file_to_addr (const char *fname, u32 addr, int argc, char **argv)
struct erl_record_t * _init_load_erl_from_file_to_addr (const char *fname, u32 addr, char *erl_id)
int unload_erl (struct erl_record_t *erl)
int erl_add_global_symbol (const char *symbol, u32 address)
struct erl_record_t * find_erl (const char *name)
struct erl_record_t * erl_resolve (u32 address)
struct symbol_t * erl_find_local_symbol (const char *symbol, struct erl_record_t *erl)
struct symbol_t * erl_find_symbol (const char *symbol)
void erl_flush_symbols (struct erl_record_t *erl)
Variables
char _init_erl_prefix []
erl_loader_t _init_load_erl
Detailed Description
The relocatable elf loader/linker.
Definition in file erl.h.
Macro Definition Documentation
ERL_DYN_ADDR
#define ERL_DYN_ADDR 0
Definition at line 66 of file erl.h.
ERL_FLAG_CLEAR
#define ERL_FLAG_CLEAR 4
Clear ERL bytes on unload
Definition at line 28 of file erl.h.
ERL_FLAG_STATIC
#define ERL_FLAG_STATIC 2
ERL is relocated at a static memory address; set by *_to_addr functions
Definition at line 26 of file erl.h.
ERL_FLAG_STICKY
#define ERL_FLAG_STICKY 1
ERL is sticky and cannot be unloaded
Definition at line 24 of file erl.h.
Function Documentation
_init_load_erl_from_file()
struct erl_record_t* _init_load_erl_from_file (const char * fname, char * erl_id)
Definition at line 1012 of file erl.c.
{
     char tfname[1024];
     struct erl_record_t * r;
     char * argv[2];
     if (erl_id)
         if ((r = find_erl(erl_id)))
             return r;
     argv[0] = erl_id;
     argv[1] = 0;
     strcpy(tfname, _init_erl_prefix);
     strcat(tfname, fname);
     return load_erl_from_file(tfname, 1, argv);
 }
References _init_erl_prefix, erl_id, find_erl(), and load_erl_from_file().
Referenced by _init_load_erl_wrapper_from_file(), and main().
_init_load_erl_from_file_to_addr()
struct erl_record_t* _init_load_erl_from_file_to_addr (const char * fname, u32 addr, char * erl_id)
Definition at line 1055 of file erl.c.
{
     char tfname[1024];
     struct erl_record_t * r;
     char * argv[2];
     if (erl_id)
         if ((r = find_erl(erl_id)))
             return r;
     argv[0] = erl_id;
     argv[1] = 0;
     strcpy(tfname, _init_erl_prefix);
     strcat(tfname, fname);
     return load_erl_from_file_to_addr(tfname, addr, 1, argv);
 }
References _init_erl_prefix, erl_id, find_erl(), and load_erl_from_file_to_addr().
erl_add_global_symbol()
int erl_add_global_symbol (const char * symbol, u32 address)
Definition at line 574 of file erl.c.
{
     return add_symbol(0, symbol, address);
 }
References add_symbol().
Referenced by export_symbols().
erl_find_local_symbol()
struct symbol_t* erl_find_local_symbol (const char * symbol, struct erl_record_t * erl)
Definition at line 427 of file erl.c.
{
     if (!erl)
         return 0;
     if (hfind(erl->symbols, symbol, strlen(symbol)))
         return hstuff(erl->symbols);
     return 0;
 }
References hfind(), hstuff, and erl_loader_t::symbols.
Referenced by load_erl(), and unload_erl().
erl_find_symbol()
struct symbol_t* erl_find_symbol (const char * symbol)
Definition at line 443 of file erl.c.
{
     if (global_symbols)
         if (hfind(global_symbols, symbol, strlen(symbol)))
             return hstuff(global_symbols);
     return r_find_symbol(symbol, erl_record_root);
 }
References erl_record_root, global_symbols, hfind(), hstuff, and r_find_symbol().
Referenced by add_symbol(), main(), and read_erl().
erl_flush_symbols()
void erl_flush_symbols (struct erl_record_t * erl)
Definition at line 1145 of file erl.c.
{
     if (!erl->symbols)
         return;
     if (hfirst(erl->symbols)) do {
         destroy_symbol((struct symbol_t *) hstuff(erl->symbols));
         free(hkey(erl->symbols));
         hdel(erl->symbols);
     } while (hcount(erl->symbols));
     hdestroy(erl->symbols);
     erl->symbols = 0;
 }
References destroy_symbol(), hcount, hdel(), hdestroy(), hfirst(), hkey, hstuff, and erl_loader_t::symbols.
Referenced by destroy_erl_record(), and unload_erl().
erl_resolve()
struct erl_record_t* erl_resolve (u32 address)
Definition at line 1121 of file erl.c.
{
     struct erl_record_t * r;
     for (r = erl_record_root; r; r = r->next) {
         u32 r_ptr = (u32) r->bytes;
         if ((address >= r_ptr) && (address < (r_ptr + r->fullsize)))
             return r;
     }
     return 0;
 }
References erl_loader_t::bytes, erl_record_root, erl_loader_t::fullsize, and erl_loader_t::next.
find_erl()
struct erl_record_t* find_erl (const char * name)
Definition at line 1133 of file erl.c.
{
     struct erl_record_t * r;
     for (r = erl_record_root; r; r = r->next) {
         if (r->name)
             if (!strcmp(name, r->name))
                 return r;
     }
     return 0;
 }
References erl_record_root, erl_loader_t::name, and erl_loader_t::next.
Referenced by _init_load_erl_from_file(), _init_load_erl_from_file_to_addr(), and r_unload_dependancies().
load_erl_from_file()
struct erl_record_t* load_erl_from_file (const char * fname, int argc, char ** argv)
Definition at line 1030 of file erl.c.
{
     return load_erl(fname, 0, ERL_DYN_ADDR, argc, argv);
 }
References ERL_DYN_ADDR, and load_erl().
Referenced by _init_load_erl_from_file().
load_erl_from_file_to_addr()
struct erl_record_t* load_erl_from_file_to_addr (const char * fname, u32 addr, int argc, char ** argv)
Definition at line 1048 of file erl.c.
{
     return load_erl(fname, 0, addr, argc, argv);
 }
References load_erl().
Referenced by _init_load_erl_from_file_to_addr().
load_erl_from_mem()
struct erl_record_t* load_erl_from_mem (u8 * mem, int argc, char ** argv)
Definition at line 1034 of file erl.c.
{
     return load_erl(0, mem, ERL_DYN_ADDR, argc, argv);
 }
References ERL_DYN_ADDR, and load_erl().
load_erl_from_mem_to_addr()
struct erl_record_t* load_erl_from_mem_to_addr (u8 * mem, u32 addr, int argc, char ** argv)
Definition at line 1041 of file erl.c.
{
     return load_erl(0, mem, addr, argc, argv);
 }
References load_erl().
unload_erl()
int unload_erl (struct erl_record_t * erl)
Definition at line 1084 of file erl.c.
{
     struct symbol_t * s;
     struct dependancy_t * p;
     dprintf("Unloading module %s.\n", erl->name ? erl->name : "(noname)");
     if ((erl->flags) & ERL_FLAG_STICKY) {
         dprintf("Module is sticky, won't unload.\n");
         return 0;
     }
     for (p = dependancy_root; p; p = p->next) {
         if (p->provider == erl) {
             dprintf("Other modules depend on it, won't unload.\n");
             return 0;
         }
     }
     if ((s = erl_find_local_symbol("_fini", erl))) {
         dprintf("_fini = %08X\n", s->address);
 #ifdef _EE
         ((func_t)s->address)();
 #endif
     }
     if (erl->dependancies)
         r_unload_dependancies(erl->dependancies);
     erl_flush_symbols(erl);
     destroy_dependancy_r(erl);
     destroy_erl_record(erl);
     return 1;
 }
References erl_loader_t::dependancies, dependancy_root, destroy_dependancy_r(), destroy_erl_record(), dprintf, erl_find_local_symbol(), ERL_FLAG_STICKY, erl_flush_symbols(), erl_loader_t::flags, erl_loader_t::name, dependancy_t::next, dependancy_t::provider, r_unload_dependancies(), and s.
Referenced by load_erl(), and r_unload_dependancies().
Variable Documentation
_init_erl_prefix
char _init_erl_prefix[] extern
Definition at line 281 of file erl.c.
Referenced by _init_load_erl_from_file(), _init_load_erl_from_file_to_addr(), and parse_boot_path().
_init_load_erl
erl_loader_t _init_load_erl extern
Definition at line 938 of file erl.c.
Referenced by load_erl().