ps2sdk: ee/kernel/src/osdsrc/src/ExecPS2.c File Reference
ExecPS2.c File Reference
#include <kernel.h>
#include "ExecPS2.h"
Data Structures
struct TCB
Functions
static void SoftPeripheralEEReset (void)
void * ExecPS2Patch (void *EntryPoint, void *gp, int argc, char *argv[])
Variables
static int * p_ThreadID =(int*)0x800125EC
static int * p_ThreadStatus =(int*)0x800125F4
static int(* p_CancelWakeupThread)(int ThreadID) =(void*)0x80004970
static int(* p_ChangeThreadPriority)(int ThreadID, int priority) =(void*)0x80004288
static int(* p_InitPgifHandler2)(void) =(void*)0x800021b0
static int(* p_InitSemaphores)(void) =(void*)0x80004e68
static int(* p_DeleteThread)(int thread_id) =(void*)0x80003f00
static int(* p_TerminateThread)(int ThreadID) =(void*)0x80003e00
static struct TCB * p_TCBs =(struct TCB *)0x80017400
static void(* p_InitializeINTC)(int interrupts) =(void*)0x8000b8d0
static void(* p_InitializeTIMER)(void) =(void*)0x8000b900
static void(* p_InitializeFPU)(void) =(void*)0x8000b7a8
static void(* p_InitializeScratchPad)(void) =(void*)0x8000b840
static int(* p_ResetEE)(int flags) =(void*)0x8000ad68
static void(* p_InitializeGS)(void) =(void*)0x8000aa60
static void(* p_SetGSCrt)(unsigned short int interlace, unsigned short int mode, unsigned short int ffmd) =(void*)0x8000a060
static void(* p_FlushDCache)(void) =(void*)0x80002a80
static void(* p_FlushICache)(void) =(void*)0x80002ac0
static char *(* p_eestrcpy)(char *dst, const char *src) =(void*)0x80005560
static char * p_ArgsBuffer =(char*)0x80012608
Function Documentation
ExecPS2Patch()
void* ExecPS2Patch (void * EntryPoint, void * gp, int argc, char * argv[])
Definition at line 83 of file ExecPS2.c.
{
         int i, CurrentThreadID;
         struct TCB *tcb;
 #ifndef REUSE_EXECPS2
         char *ArgsPtr;
 #endif
         CurrentThreadID=*p_ThreadID;
         p_CancelWakeupThread(CurrentThreadID);
         p_ChangeThreadPriority(CurrentThreadID, 0);
         //Like IOP kernels, the first thread is the idle thread.
         for(i=1,tcb=&p_TCBs[1]; i<MAX_THREADS; i++,tcb++){
                 if(tcb->status!=0 && i!=CurrentThreadID){
                         if(tcb->status!=THS_DORMANT) p_TerminateThread(i);
                         p_DeleteThread(i);
                 }
         }
         p_InitSemaphores();
         p_InitPgifHandler2();
         *p_ThreadStatus=0;
         SoftPeripheralEEReset();
 #ifdef REUSE_EXECPS2
         //Unlike the Sony patch, why don't we just reuse the original function in the kernel?
         return p_ExecPS2(EntryPoint, gp, argc, argv);
 #else
         for(i=0,ArgsPtr=p_ArgsBuffer; i<argc; i++){
                 ArgsPtr=p_eestrcpy(ArgsPtr, argv[i]);
         }
         tcb=&p_TCBs[CurrentThreadID];
         tcb->argstring=p_ArgsBuffer;
         tcb->argc=argc;
         tcb->entry=EntryPoint;
         tcb->entry_=EntryPoint;
         tcb->gpReg=gp;
         tcb->initPriority=0;
         tcb->currentPriority=0;
         tcb->wakeupCount=0;
         tcb->waitSema=0;
         tcb->semaId=0;
         p_FlushICache();
         p_FlushDCache();
         return EntryPoint;
 #endif
 }
References TCB::argc, TCB::argstring, TCB::currentPriority, TCB::entry, TCB::entry_, gp, TCB::gpReg, TCB::initPriority, MAX_THREADS, p_ArgsBuffer, p_CancelWakeupThread, p_ChangeThreadPriority, p_DeleteThread, p_eestrcpy, p_FlushDCache, p_FlushICache, p_InitPgifHandler2, p_InitSemaphores, p_TCBs, p_TerminateThread, p_ThreadID, p_ThreadStatus, TCB::semaId, SoftPeripheralEEReset(), TCB::status, THS_DORMANT, TCB::waitSema, and TCB::wakeupCount.
SoftPeripheralEEReset()
static void SoftPeripheralEEReset (void) inline static
Definition at line 69 of file ExecPS2.c.
{
         *(volatile unsigned int *)0x1000f000=4;
         while((*(volatile unsigned int *)0x1000f000&4)==0){};
         *(volatile unsigned int *)0x1000f000=4;
         p_InitializeGS();
         p_SetGSCrt(1, 2, 1);    //Interlaced, NTSC, field mode.
         p_InitializeINTC(0xdffd);
         p_InitializeTIMER();
         p_ResetEE(0x7F);
         p_InitializeFPU();
         p_InitializeScratchPad();
 }
References p_InitializeFPU, p_InitializeGS, p_InitializeINTC, p_InitializeScratchPad, p_InitializeTIMER, p_ResetEE, and p_SetGSCrt.
Referenced by ExecPS2Patch().
Variable Documentation
p_ArgsBuffer
char* p_ArgsBuffer =(char*)0x80012608 static
Definition at line 37 of file ExecPS2.c.
Referenced by ExecPS2Patch().
p_CancelWakeupThread
int(* p_CancelWakeupThread) (int ThreadID) (int ThreadID) =(void*)0x80004970 static
Definition at line 16 of file ExecPS2.c.
Referenced by ExecPS2Patch().
p_ChangeThreadPriority
int(* p_ChangeThreadPriority) (int ThreadID, int priority) (int ThreadID, int priority) =(void*)0x80004288 static
Definition at line 17 of file ExecPS2.c.
Referenced by ExecPS2Patch().
p_DeleteThread
int(* p_DeleteThread) (int thread_id) (int thread_id) =(void*)0x80003f00 static
Definition at line 20 of file ExecPS2.c.
Referenced by ExecPS2Patch().
p_eestrcpy
char*(* p_eestrcpy) (char *dst, const char *src) (char * dst, const char * src) =(void*)0x80005560 static
Definition at line 35 of file ExecPS2.c.
Referenced by ExecPS2Patch().
p_FlushDCache
void(* p_FlushDCache) (void) (void) =(void*)0x80002a80 static
Definition at line 33 of file ExecPS2.c.
Referenced by ExecPS2Patch().
p_FlushICache
void(* p_FlushICache) (void) (void) =(void*)0x80002ac0 static
Definition at line 34 of file ExecPS2.c.
Referenced by ExecPS2Patch().
p_InitializeFPU
void(* p_InitializeFPU) (void) (void) =(void*)0x8000b7a8 static
Definition at line 25 of file ExecPS2.c.
Referenced by SoftPeripheralEEReset().
p_InitializeGS
void(* p_InitializeGS) (void) (void) =(void*)0x8000aa60 static
Definition at line 28 of file ExecPS2.c.
Referenced by SoftPeripheralEEReset().
p_InitializeINTC
void(* p_InitializeINTC) (int interrupts) (int interrupts) =(void*)0x8000b8d0 static
Definition at line 23 of file ExecPS2.c.
Referenced by SoftPeripheralEEReset().
p_InitializeScratchPad
void(* p_InitializeScratchPad) (void) (void) =(void*)0x8000b840 static
Definition at line 26 of file ExecPS2.c.
Referenced by SoftPeripheralEEReset().
p_InitializeTIMER
void(* p_InitializeTIMER) (void) (void) =(void*)0x8000b900 static
Definition at line 24 of file ExecPS2.c.
Referenced by SoftPeripheralEEReset().
p_InitPgifHandler2
int(* p_InitPgifHandler2) (void) (void) =(void*)0x800021b0 static
Definition at line 18 of file ExecPS2.c.
Referenced by ExecPS2Patch().
p_InitSemaphores
int(* p_InitSemaphores) (void) (void) =(void*)0x80004e68 static
Definition at line 19 of file ExecPS2.c.
Referenced by ExecPS2Patch().
p_ResetEE
int(* p_ResetEE) (int flags) (int flags) =(void*)0x8000ad68 static
Definition at line 27 of file ExecPS2.c.
Referenced by SoftPeripheralEEReset().
p_SetGSCrt
void(* p_SetGSCrt) (unsigned short int interlace, unsigned short int mode, unsigned short int ffmd) (unsigned short int interlace, unsigned short int mode, unsigned short int ffmd) =(void*)0x8000a060 static
Definition at line 29 of file ExecPS2.c.
Referenced by SoftPeripheralEEReset().
p_TCBs
struct TCB* p_TCBs =(struct TCB *)0x80017400 static
Definition at line 22 of file ExecPS2.c.
Referenced by ExecPS2Patch().
p_TerminateThread
int(* p_TerminateThread) (int ThreadID) (int ThreadID) =(void*)0x80003e00 static
Definition at line 21 of file ExecPS2.c.
Referenced by ExecPS2Patch().
p_ThreadID
int* p_ThreadID =(int*)0x800125EC static
Definition at line 14 of file ExecPS2.c.
Referenced by ExecPS2Patch().
p_ThreadStatus
int* p_ThreadStatus =(int*)0x800125F4 static
Definition at line 15 of file ExecPS2.c.
Referenced by ExecPS2Patch().