ps2sdk: ee/kernel/include/fileio.h File Reference
fileio.h File Reference
#include <io_common.h>
Macros
#define FIO_PATH_MAX 256
#define FIO_WAIT 0
#define FIO_NOWAIT 1
#define FIO_COMPLETE 1
#define FIO_INCOMPLETE 0
#define EOF (-1)
Functions
int fioInit (void)
void fioExit (void)
int fioOpen (const char *fname, int mode)
int fioClose (int fd)
int fioRead (int fd, void *buff, int buff_size)
int fioWrite (int fd, const void *buff, int buff_size)
int fioLseek (int fd, int offset, int whence)
int fioMkdir (const char *dirname)
int fioPutc (int fd, int c)
int fioGetc (int fd)
int fioGets (int fd, char *buff, int n)
void fioSetBlockMode (int blocking)
int fioSync (int mode, int *retVal)
int fioIoctl (int fd, int request, void *data)
int fioDopen (const char *name)
int fioDclose (int fd)
int fioDread (int fd, io_dirent_t *buf)
int fioGetstat (const char *name, io_stat_t *buf)
int fioChstat (const char *name, io_stat_t *buf, unsigned int cbit)
int fioRemove (const char *name)
int fioFormat (const char *name)
int fioRmdir (const char *dirname)
Detailed Description
EE FILE IO handling
Definition in file fileio.h.
Macro Definition Documentation
EOF
#define EOF (-1)
Definition at line 35 of file fileio.h.
FIO_COMPLETE
#define FIO_COMPLETE 1
Definition at line 32 of file fileio.h.
FIO_INCOMPLETE
#define FIO_INCOMPLETE 0
Definition at line 33 of file fileio.h.
FIO_NOWAIT
#define FIO_NOWAIT 1
Definition at line 30 of file fileio.h.
FIO_PATH_MAX
#define FIO_PATH_MAX 256
Definition at line 27 of file fileio.h.
FIO_WAIT
#define FIO_WAIT 0
Definition at line 29 of file fileio.h.
Function Documentation
fioChstat()
int fioChstat (const char * name, io_stat_t * buf, unsigned int cbit)
fioClose()
int fioClose (int fd)
fioDclose()
int fioDclose (int fd)
Referenced by fioClosedirHelper().
fioDopen()
int fioDopen (const char * name)
Referenced by fioOpendirHelper().
fioDread()
int fioDread (int fd, io_dirent_t * buf)
Referenced by fioReaddirHelper().
fioExit()
void fioExit (void)
fioFormat()
int fioFormat (const char * name)
fioGetc()
int fioGetc (int fd)
fioGets()
int fioGets (int fd, char * buff, int n)
fioGetstat()
int fioGetstat (const char * name, io_stat_t * buf)
Referenced by fioGetstatHelper().
fioInit()
int fioInit (void)
Referenced by main().
fioIoctl()
int fioIoctl (int fd, int request, void * data)
fioLseek()
int fioLseek (int fd, int offset, int whence)
fioMkdir()
int fioMkdir (const char * dirname)
Referenced by fioMkdirHelper().
fioOpen()
int fioOpen (const char * fname, int mode)
fioPutc()
int fioPutc (int fd, int c)
fioRead()
int fioRead (int fd, void * buff, int buff_size)
fioRemove()
int fioRemove (const char * name)
fioRmdir()
int fioRmdir (const char * dirname)
fioSetBlockMode()
void fioSetBlockMode (int blocking)
fioSync()
int fioSync (int mode, int * retVal)
fioWrite()
int fioWrite (int fd, const void * buff, int buff_size)