ps2sdk: ee/font/include/font.h File Reference
font.h File Reference
#include <draw.h>
#include <tamtypes.h>
Data Structures
struct fontx_t
struct inidata_t
struct fsfont_t
Macros
#define SINGLE_BYTE 0
#define DOUBLE_BYTE 1
#define LEFT_ALIGN 0
#define CENTER_ALIGN 1
#define RIGHT_ALIGN 2
Functions
int fontx_load (const char *path, fontx_t *fontx, int type, int wmargin, int hmargin, int bold)
void fontx_unload (fontx_t *fontx)
qword_t * fontx_print_ascii (qword_t *q, int context, const unsigned char *str, int alignment, vertex_t *v0, color_t *c0, fontx_t *fontx)
qword_t * fontx_print_sjis (qword_t *q, int context, const unsigned char *str, int alignment, vertex_t *v0, color_t *c0, fontx_t *ascii, fontx_t *kanji)
fsfont_t * fontstudio_init (int height)
void fontstudio_free (fsfont_t *font)
int fontstudio_parse_ini (fsfont_t *font, char *ini, float tex_width, float tex_height)
char * fontstudio_load_ini (const char *path)
void fontstudio_unload_ini (fsfont_t *font)
qword_t * fontstudio_print_string (qword_t *q, int context, const unsigned char *string, int alignment, vertex_t *v0, color_t *c0, fsfont_t *font)
Detailed Description
Font library.
Definition in file font.h.
Macro Definition Documentation
CENTER_ALIGN
#define CENTER_ALIGN 1
Definition at line 61 of file font.h.
DOUBLE_BYTE
#define DOUBLE_BYTE 1
Definition at line 14 of file font.h.
LEFT_ALIGN
#define LEFT_ALIGN 0
Alignments
Definition at line 60 of file font.h.
RIGHT_ALIGN
#define RIGHT_ALIGN 2
Definition at line 62 of file font.h.
SINGLE_BYTE
#define SINGLE_BYTE 0
FontX2 types
Definition at line 13 of file font.h.
Function Documentation
fontstudio_free()
void fontstudio_free (fsfont_t * font)
Definition at line 36 of file fsfont.c.
 {
         if (font->charmap != NULL)
         {
                 free(font->charmap);
         }
         if (font->chardata != NULL)
         {
                 free(font->chardata);
         }
         free(font);
 }
References fsfont_t::chardata, fsfont_t::charmap, and NULL.
fontstudio_init()
fsfont_t* fontstudio_init (int height)
Loads the FontStudio ini file that contains the font texture's characteristics
Definition at line 22 of file fsfont.c.
 {
         fsfont_t *font;
         font = (fsfont_t*)malloc(sizeof(fsfont_t));
         font->height = char_height;
         font->scale = 1.0f;
         return font;
 }
References fsfont_t::height, and fsfont_t::scale.
fontstudio_load_ini()
char* fontstudio_load_ini (const char * path)
Loads an ini file into memory and returns pointer to it
Definition at line 53 of file fsfont.c.
 {
         FILE *file;
         char *ini;
         int size;
         file = fopen(path, "r");
         if (file == NULL)
         {
                 printf("Error opening %s.\n", path);
                 return NULL;
         }
         fseek(file, 0, SEEK_END);
         size = ftell(file);
         fseek(file, 0, SEEK_SET);
         ini = (char *)malloc(size);
         if (ini == NULL)
         {
                 printf("Error allocated %d bytes of memory.\n", size);
                 fclose(file);
                 return NULL;
         }
         fread(ini, size, 1, file);
         fclose(file);
         return ini;
 }
References NULL.
Referenced by main().
fontstudio_parse_ini()
int fontstudio_parse_ini (fsfont_t * font, char * ini, float tex_width, float tex_height)
Parses a font's ini for the font. The content of ini is no longer required afterwards and can be discarded.
Definition at line 91 of file fsfont.c.
 {
         int i;
         char *temp0;
         char *temp1;
         temp0 = ini;
         temp1 = strtok(temp0,"=");
         if (temp1 == NULL)
         {
                 printf("Error parsing number of chars.\n");
                 return -1;
         }
         temp0 += strlen(temp1)+1;
         font->totalchars = (int)strtol(temp0,NULL,10);
         temp1 = strtok(temp0,"=");
         if (temp1 == NULL)
         {
                 printf("Error parsing space width.\n");
                 return -1;
         }
         temp0 += strlen(temp1)+1;
         font->spacewidth = (int)strtol(temp0,NULL,10);
         font->charmap = (unsigned short*)malloc(sizeof(short)*font->totalchars);
         if (font->charmap == NULL)
         {
                 //131 kilobytes of memory
                 printf("Error allocated %d bytes of memory.\n", sizeof(short)*font->totalchars);
                 return -1;
         }
         // Clear memory
         memset(font->charmap,0,sizeof(short)*font->totalchars);
         font->chardata = (inidata_t*)malloc(sizeof(inidata_t)*font->totalchars);
         if (font->chardata == NULL)
         {
                 printf("Error allocating %d bytes of memory.\n", sizeof(inidata_t)*font->totalchars);
                 free(font->charmap);
                 return -1;
         }
         // Clear memory
         memset(font->chardata,0,sizeof(inidata_t)*font->totalchars);
         for (i = 0; i < font->totalchars; i++)
         {
                 temp1 = strtok(temp0,"=");
                 if (temp1 == NULL)
                 {
                         printf("Error parsing Char for char %d.\n", i);
                         free(font->charmap);
                         free(font->chardata);
                         return -1;
                 }
                 temp0 += strlen(temp1)+1;
                 font->charmap[i] = (int)strtol(temp0,NULL,10);
                 temp1 = strtok(temp0,"=");
                 if (temp1 == NULL)
                 {
                         printf("Error parsing A for char %d.\n", i);
                         free(font->charmap);
                         free(font->chardata);
                         return -1;
                 }
                 temp0 += strlen(temp1)+1;
                 font->chardata[i].A = (int)strtol(temp0,NULL,10);
                 temp1 = strtok(temp0,"=");
                 if (temp1 == NULL)
                 {
                         printf("Error parsing B for char %d.\n", i);
                         free(font->charmap);
                         free(font->chardata);
                         return -1;
                 }
                 temp0 += strlen(temp1)+1;
                 font->chardata[i].B = (int)strtol(temp0,NULL,10);
                 temp1 = strtok(temp0,"=");
                 if (temp1 == NULL)
                 {
                         printf("Error parsing C for char %d.\n", i);
                         free(font->charmap);
                         free(font->chardata);
                         return -1;
                 }
                 temp0 += strlen(temp1)+1;
                 font->chardata[i].C = (int)strtol(temp0,NULL,10);
                 temp1 = strtok(temp0,"=");
                 if (temp1 == NULL)
                 {
                         printf("Error parsing ox for char %d.\n", i);
                         free(font->charmap);
                         free(font->chardata);
                         return -1;
                 }
                 temp0 += strlen(temp1)+1;
                 font->chardata[i].ox = (int)strtol(temp0,NULL,10);
                 temp1 = strtok(temp0,"=");
                 if (temp1 == NULL)
                 {
                         printf("Error parsing oy for char %d.\n", i);
                         free(font->charmap);
                         free(font->chardata);
                         return -1;
                 }
                 temp0 += strlen(temp1)+1;
                 font->chardata[i].oy = (int)strtol(temp0,NULL,10);
                 temp1 = strtok(temp0,"=");
                 if (temp1 == NULL)
                 {
                         printf("Error parsing Wid for char %d.\n", i);
                         free(font->charmap);
                         free(font->chardata);
                         return -1;
                 }
                 temp0 += strlen(temp1)+1;
                 font->chardata[i].width = (int)strtol(temp0,NULL,10);
                 temp1 = strtok(temp0,"=");
                 if (temp1 == NULL)
                 {
                         printf("Error parsing Hgt for char %d.\n", i);
                         free(font->charmap);
                         free(font->chardata);
                         return -1;
                 }
                 temp0 += strlen(temp1)+1;
                 font->chardata[i].height = (int)strtol(temp0,NULL,10);
                 temp1 = strtok(temp0,"=");
                 if (temp1 == NULL)
                 {
                         printf("Error parsing X1 for char %d.\n", i);
                         free(font->charmap);
                         free(font->chardata);
                         return -1;
                 }
                 temp0 += strlen(temp1)+1;
                 font->chardata[i].u1 = ftoi4(((float)(strtod(temp0,NULL) * tex_width)));
                 temp1 = strtok(temp0,"=");
                 if (temp1 == NULL)
                 {
                         printf("Error parsing Y1 for char %d.\n", i);
                         free(font->charmap);
                         free(font->chardata);
                         return -1;
                 }
                 temp0 += strlen(temp1)+1;
                 font->chardata[i].v1 = ftoi4(((float)(strtod(temp0,NULL) * tex_height)));
                 temp1 = strtok(temp0,"=");
                 if (temp1 == NULL)
                 {
                         printf("Error parsing X2 for char %d.\n", i);
                         free(font->charmap);
                         free(font->chardata);
                         return -1;
                 }
                 temp0 += strlen(temp1)+1;
                 font->chardata[i].u2 = ftoi4(((float)(strtod(temp0,NULL) * tex_width)));
                 temp1 = strtok(temp0,"=");
                 if (temp1 == NULL)
                 {
                         printf("Error parsing Y2 for char %d.\n", i);
                         free(font->charmap);
                         free(font->chardata);
                         return -1;
                 }
                 temp0 += strlen(temp1)+1;
                 font->chardata[i].v2 = ftoi4(((float)(strtod(temp0,NULL) * tex_height)));
         }
         return 0;
 }
References inidata_t::A, inidata_t::B, inidata_t::C, fsfont_t::chardata, fsfont_t::charmap, ftoi4, inidata_t::height, NULL, inidata_t::ox, inidata_t::oy, fsfont_t::spacewidth, fsfont_t::totalchars, inidata_t::u1, inidata_t::u2, inidata_t::v1, inidata_t::v2, and inidata_t::width.
Referenced by main().
fontstudio_print_string()
qword_t* fontstudio_print_string (qword_t * q, int context, const unsigned char * string, int alignment, vertex_t * v0, color_t * c0, fsfont_t * font)
Prints a unicode formatted string (UTF+8)
Definition at line 456 of file fsfont.c.
 {
         int i = 0,j;
         unsigned short curchar = 0;
         int length;
         vertex_t v_pos = *v0;
         unsigned short utf8[2048];
         memset(utf8,0,sizeof(short)*2048);
         // Decodes the encoded string into unicode numbers U+xxxx
         // length is the number of characters in the string
         length = decode_unicode(str, utf8);
         //for (i = 0; i < length; i++)
         //{
         //      printf("utf8[%d] = %d\n", i, utf8[i]);
         //}
         // Converts the unicode numbers into the index numbers
         // used by the FontStudio ini
         convert_to_index(utf8,length,font);
         //for (i = 0; i < length; i++)
         //{
         //      printf("utf8[%d] = %d\n", i, utf8[i]);
         //}
         float line_num[100];
         int line = 0;
         float x_orig[100];
         x_orig[0] = 0;
         // line_num is used to keep track of number of characters per line
         line_num[0] = 0;
         switch (alignment)
         {
                 default:
                 case LEFT_ALIGN:
                 {
                         for (i = 0; i < length; i++)
{
                                 while (utf8[i] == TAB || utf8[i] == NEWLINE)
{
                                         if (utf8[i] == NEWLINE)
{
                                                 x_orig[line] = v_pos.x;
                                                 line++;
                                                 line_num[line] = 0;
                                         }
                                         i++;
                                 }
                                 if (i == length-1)
{
                                         x_orig[line] = v_pos.x;
                                         line++;
                                 }
                         }
                         break;
                 }
                 case RIGHT_ALIGN:
                 {
                         for (i = 0; i < length; i++)
{
                                 while (utf8[i] == TAB || utf8[i] == NEWLINE || utf8[i] == SPACE)
{
                                         if (utf8[i] == NEWLINE)
{
                                                 x_orig[line] = v_pos.x - line_num[line]*font->scale;
                                                 line++;
                                                 line_num[line] = 0;
                                         }
                                         if (utf8[i] == TAB)
{
                                                 line_num[line] += font->spacewidth * 4;
                                         }
                                         if (utf8[i] == SPACE)
{
                                                 line_num[line] += font->spacewidth;
                                         }
                                         i++;
                                 }
                                 curchar = utf8[i];
                                 line_num[line] += font->chardata[curchar].A + font->chardata[curchar].B + font->chardata[curchar].C;
                                 if (i == length-1)
{
                                         x_orig[line] = v_pos.x - line_num[line]*font->scale;
                                         line++;
                                 }
                         }
                         break;
                 }
                 case CENTER_ALIGN:
                 {
                         for (i = 0; i < length; i++)
{
                                 while (utf8[i] == TAB || utf8[i] == NEWLINE || utf8[i] == SPACE)
{
                                         if (utf8[i] == NEWLINE)
{
                                                 x_orig[line] = v_pos.x - (line_num[line]*font->scale)/2.0f;
                                                 line++;
                                                 line_num[line] = 0;
                                         }
                                         if (utf8[i] == TAB)
{
                                                 line_num[line] += font->spacewidth * 4;
                                         }
                                         if (utf8[i] == SPACE)
{
                                                 line_num[line] += font->spacewidth;
                                         }
                                         i++;
                                 }
                                 curchar = utf8[i];
                                 line_num[line] += font->chardata[curchar].A + font->chardata[curchar].B + font->chardata[curchar].C;
                                 if (i == length-1)
{
                                         x_orig[line] = v_pos.x - (line_num[line]*font->scale)/2.0f;
                                         line++;
                                 }
                         }
                         break;
                 }
         };
         line = 0;
         v_pos.x = x_orig[0];
         q = draw_prim_start(q,context,&charprim,c0);
         for (j = 0; j < length; j++)
         {
                 while(utf8[j] == NEWLINE || utf8[j] == TAB || utf8[j] == SPACE)
                 {
                         if (utf8[j] == NEWLINE)
{
                                 line++;
                                 v_pos.y += font->height*font->scale;
                                 v_pos.x = x_orig[line];
                         }
                         if (utf8[j] == TAB)
{
                                 v_pos.x += font->spacewidth*font->scale * 4.0f;
                         }
                         if (utf8[j] == SPACE)
{
                                 v_pos.x += font->spacewidth*font->scale;
                         }
                         j++;
                 }
                 v_pos.x += (font->chardata[utf8[j]].A*font->scale);
                 q = draw_fontstudio_char(q,utf8[j],&v_pos,font);
                 v_pos.x += (font->chardata[utf8[j]].B*font->scale) + (font->chardata[utf8[j]].C*font->scale);
         }
         q = draw_prim_end(q,2,DRAW_UV_REGLIST);
         return q;
 }
References inidata_t::A, inidata_t::B, inidata_t::C, CENTER_ALIGN, fsfont_t::chardata, charprim, context, convert_to_index(), decode_unicode(), draw_fontstudio_char(), draw_prim_end(), draw_prim_start(), DRAW_UV_REGLIST, fsfont_t::height, LEFT_ALIGN, NEWLINE, RIGHT_ALIGN, fsfont_t::scale, SPACE, fsfont_t::spacewidth, TAB, v0, vertex_t::x, and vertex_t::y.
Referenced by run_demo().
fontstudio_unload_ini()
void fontstudio_unload_ini (fsfont_t * font)
Unloads a parsed font's ini file.
Definition at line 313 of file fsfont.c.
 {
         if(font->charmap != NULL)
         {
                 free(font->charmap);
                 font->charmap = NULL;
         }
         if(font->chardata != NULL)
         {
                 free(font->chardata);
                 font->chardata = NULL;
         }
 }
References fsfont_t::chardata, fsfont_t::charmap, and NULL.
Referenced by main().
fontx_load()
int fontx_load (const char * path, fontx_t * fontx, int type, int wmargin, int hmargin, int bold)
Loads a FontX2 type font with set characteristics Use "rom0:KROM" as the path to load the PS2's internal FontX2 font
Definition at line 262 of file fontx.c.
 {
         FILE *file = NULL;
         int ret = -1;
         long size = 0;
         fontx_hdr *fontx_header = NULL;
         if (!strcmp("rom0:KROM",path) || !strcmp("rom0:/KROM",path))
         {
                 if (type == SINGLE_BYTE)
                 {
                         ret = fontx_load_single_krom(fontx);
                 }
                 else
                 {
                         ret = fontx_load_double_krom(fontx);
                 }
                 if (ret < 0)
                 {
                         printf("Error opening %s\n", path);
                         return -1;
                 }
         }
         else
         {
                 file = fopen(path, "r");
                 if (file == NULL)
                 {
                         printf("Error opening %s\n", path);
                         return -1;
                 }
                 // get size of file
                 fseek(file, 0, SEEK_END);
                 size = ftell(file);
                 fseek(file, 0, SEEK_SET);
                 fontx->font = (char *)malloc(size);
                 if (fontx->font == NULL)
                 {
                         printf("Error allocating %ld bytes of memory.\n", size);
                         fclose(file);
                         return -1;
                 }
                 fread(fontx->font, size, 1, file);
                 fclose(file);
         }
         fontx_header = (fontx_hdr*)fontx->font;
         if (strncmp(fontx_header->id, "FONTX2", 6) != 0)
         {
                 printf("Not FONTX2 type font!\n");
                 free(fontx->font);
                 return -1;
         }
         if (fontx_header->type != type)
         {
                 printf("Type mismatch\n");
                 free(fontx->font);
                 return -1;
         }
         // Fill in some information about the font
         strcpy(fontx->name,fontx_header->name);
         fontx->rowsize = ((fontx_header->width+7)>>3);
         fontx->charsize = fontx->rowsize * fontx_header->height;
         fontx->w_margin = wmargin;
         fontx->h_margin = hmargin;
         fontx->bold = bold;
         // This is the offset that character data starts
         if (fontx_header->type == SINGLE_BYTE)
         {
                 fontx->offset = 17;
         }
         else
         {
                 // 17 + 1 + (number of tables * 4) bytes
                 fontx->offset = 18 + (fontx_header->table_num * 4);
         }
         return 0;
 }
References fontx_t::bold, fontx_t::charsize, fontx_t::font, fontx_load_double_krom(), fontx_load_single_krom(), fontx_t::h_margin, fontx_hdr::height, fontx_hdr::id, fontx_t::name, fontx_hdr::name, NULL, fontx_t::offset, fontx_t::rowsize, SINGLE_BYTE, fontx_hdr::table_num, fontx_hdr::type, fontx_t::w_margin, and fontx_hdr::width.
Referenced by main().
fontx_print_ascii()
qword_t* fontx_print_ascii (qword_t * q, int context, const unsigned char * str, int alignment, vertex_t * v0, color_t * c0, fontx_t * fontx)
Prints an ascii/JISX201 formatted string
Definition at line 559 of file fontx.c.
 {
         int i,j;
         fontx_hdr *fontx_header = (fontx_hdr*)fontx->font;
         vertex_t v_pos = *v0;
         int length = strlen((const char *)str);
         short line_num[100];
         int line = 0;
         float x_orig[100];
         x_orig[0] = 0;
         float w = fontx_header->width;
         float h = fontx_header->height;
         float wm = fontx->w_margin;
         float hm = fontx->h_margin;
         // line_num is used to keep track of number of characters per line
         line_num[0] = 0;
         switch (alignment)
         {
                 default:
                 case LEFT_ALIGN:
                 {
                         for (i = 0; i < length; i++)
{
                                 while (str[i] == '\t' || str[i] == '\n')
{
                                         if(str[i] == '\n')
{
                                                 x_orig[line] = v_pos.x;
                                                 line++;
                                                 line_num[line] = 0;
                                         }
                                         i++;
                                 }
                                 if (i == length-1)
{
                                         x_orig[line] = v_pos.x;
                                         line++;
                                 }
                         }
                         break;
                 }
                 case RIGHT_ALIGN:
                 {
                         for (i = 0; i < length; i++)
{
                                 while (str[i] == '\t' || str[i] == '\n')
{
                                         if (str[i] == '\t')
{
                                                 line_num[line] += 4;
                                         }
                                         if (str[i] == '\n')
{
                                                 x_orig[line] = v_pos.x - (line_num[line] * (w + wm));
                                                 line++;
                                                 line_num[line] = 0;
                                         }
                                         i++;
                                 }
                                 line_num[line]++;
                                 if (i == length-1)
{
                                         x_orig[line] = v_pos.x - (line_num[line] * (w + wm));
                                         line++;
                                 }
                         }
                         break;
                 }
                 case CENTER_ALIGN:
                 {
                         for (i = 0; i < length; i++)
{
                                 while (str[i] == '\t' || str[i] == '\n')
{
                                         if (str[i] == '\t')
{
                                                 line_num[line] += 4;
                                         }
                                         if (str[i] == '\n')
{
                                                 x_orig[line] = v_pos.x - (line_num[line] * (w + wm))/2.0f;
                                                 line++;
                                                 line_num[line] = 0;
                                         }
                                         i++;
                                 }
                                 line_num[line]++;
                                 if (i == length-1)
{
                                         x_orig[line] = v_pos.x - (line_num[line] * (w + wm))/2.0f;
                                         line++;
                                 }
                         }
                         break;
                 }
         };
         line = 0;
         v_pos.x = x_orig[0];
         q = draw_prim_start(q,context,&charprim,c0);
         for (j = 0; j < length; j++)
         {
                 while(str[j] == '\n' || str[j] == '\t')
                 {
                         if (str[j] == '\n')
{
                                 line++;
                                 v_pos.y += h + hm;
                                 v_pos.x = x_orig[line];
                         }
                         if (str[j] == '\t')
{
                                 v_pos.x += w * 5.0f;
                         }
                         j++;
                 }
                 if (str[j] < 0x80)
                 {
                         q = draw_fontx_char(q,str[j],&v_pos,fontx);
                 }
                 else if (str[j] >= 0xA1 && str[j] <= 0xDF)
                 {
                         q = draw_fontx_char(q,str[j],&v_pos,fontx);
                 }
                 v_pos.x += w + wm;
         }
         q = draw_prim_end(q,2,DRAW_XYZ_REGLIST);
         return q;
 }
References CENTER_ALIGN, charprim, context, draw_fontx_char(), draw_prim_end(), draw_prim_start(), DRAW_XYZ_REGLIST, fontx_t::font, fontx_t::h_margin, fontx_hdr::height, LEFT_ALIGN, RIGHT_ALIGN, v0, fontx_t::w_margin, and fontx_hdr::width.
fontx_print_sjis()
qword_t* fontx_print_sjis (qword_t * q, int context, const unsigned char * str, int alignment, vertex_t * v0, color_t * c0, fontx_t * ascii, fontx_t * kanji)
Prints a SJIS formatted string
Definition at line 735 of file fontx.c.
 {
         int i,j;
         fontx_hdr *ascii_header = (fontx_hdr*)ascii->font;
         fontx_hdr *kanji_header = (fontx_hdr*)kanji->font;
         vertex_t v_pos = *v0;
         int length = strlen((const char *)str);
         int line = 0;
         short halfwidth[100];
         short fullwidth[100];
         float x_orig[100];
         x_orig[0] = 0;
         unsigned short wide;
         float hw = ascii_header->width;
         float fw = kanji_header->width;
         float h = kanji_header->height;
         float wm = kanji->w_margin;
         float hm = kanji->h_margin;
         // line_num is used to keep track of number of characters per line
         halfwidth[0] = 0;
         fullwidth[0] = 0;
         switch (alignment)
         {
                 default:
                 case LEFT_ALIGN:
                 {
                         for (i = 0; i < length; i++)
{
                                 while (str[i] == '\t'|| str[i] == '\n')
{
                                         if (str[i] == '\t')
{
                                                 halfwidth[line] += 4;
                                         }
                                         if (str[i] == '\n')
{
                                                 x_orig[line] = v_pos.x;
                                                 line++;
                                                 halfwidth[line] = 0;
                                                 fullwidth[line] = 0;
                                         }
                                         i++;
                                 }
                                 if (i == length-1)
{
                                         x_orig[line] = v_pos.x;
                                         line++;
                                 }
                         }
                         break;
                 }
                 case RIGHT_ALIGN:
                 {
                         for (i = 0; i < length; i++)
{
                                 while (str[i] == '\t'|| str[i] == '\n')
{
                                         if (str[i] == '\t')
{
                                                 halfwidth[line] += 4;
                                         }
                                         if (str[i] == '\n')
{
                                                 x_orig[line] = v_pos.x - ((halfwidth[line] * (hw+wm)) + (fullwidth[line] * (fw + wm)));;
                                                 line++;
                                                 halfwidth[line] = 0;
                                                 fullwidth[line] = 0;
                                         }
                                         i++;
                                 }
                                 if (str[i] < 0x80)
{
                                         halfwidth[line]++;
                                 }
                                 else if (str[i] >= 0xA1 && str[i] <= 0xDF)
{
                                         halfwidth[line]++;
                                 }
                                 else if (str[i] >= 0x81 && str[i] <= 0x9F)
{
                                         fullwidth[line]++;
                                 }
                                 else if (str[i] >= 0xE0 && str[i] <= 0xEF)
{
                                         fullwidth[line]++;
                                 }
                                 if (i == length-1)
{
                                         x_orig[line] = v_pos.x - ((halfwidth[line] * (hw+wm)) + (fullwidth[line] * (fw + wm)));
                                         line++;
                                 }
                         }
                         break;
                 }
                 case CENTER_ALIGN:
                 {
                         for (i = 0; i < length; i++)
{
                                 while (str[i] == '\t'|| str[i] == '\n')
{
                                         if (str[i] == '\t')
{
                                                 halfwidth[line] += 4;
                                         }
                                         if (str[i] == '\n')
{
                                                 x_orig[line] = v_pos.x - ((halfwidth[line] * (hw+wm)) + (fullwidth[line] * (fw + wm)))/2.0f;
                                                 line++;
                                                 halfwidth[line] = 0;
                                                 fullwidth[line] = 0;
                                         }
                                         i++;
                                 }
                                 if (str[i] < 0x80)
{
                                         halfwidth[line]++;
                                 }
                                 else if (str[i] >= 0xA1 && str[i] <= 0xDF)
{
                                         halfwidth[line]++;
                                 }
                                 else if (str[i] >= 0x81 && str[i] <= 0x9F)
{
                                         fullwidth[line]++;
                                 }
                                 else if (str[i] >= 0xE0 && str[i] <= 0xEF)
{
                                         fullwidth[line]++;
                                 }
                                 if (i == length-1)
{
                                         x_orig[line] = v_pos.x - ((halfwidth[line] * (hw+wm)) + (fullwidth[line] * (fw + wm)))/2.0f;
                                         line++;
                                 }
                         }
                         break;
                 }
         };
         line = 0;
         v_pos.x = x_orig[0];
         q = draw_prim_start(q,context,&charprim,c0);
         for (j = 0; j < length; j++)
         {
                 wide = 0;
                 while(str[j] == '\n' || str[j] == '\t')
                 {
                         if (str[j] == '\n')
{
                                 line++;
                                 v_pos.y += h + hm;
                                 v_pos.x = x_orig[line];
                         }
                         if (str[j] == '\t')
{
                                 v_pos.x += hw * 5.0f;
                         }
                         j++;
                 }
                 if (str[j] < 0x80)
                 {
                         q = draw_fontx_char(q,str[j],&v_pos,ascii);
                         v_pos.x += hw + wm;
                 }
                 else if (str[j] >= 0xA1 && str[j] <= 0xDF)
                 {
                         q = draw_fontx_char(q,str[j],&v_pos,ascii);
                         v_pos.x += hw + wm;
                 }
                 else if (str[j] >= 0x81 && str[j] <= 0x9F)
                 {
                         wide = str[j++]<<8;
                         wide += str[j];
                         q = draw_fontx_char(q,wide,&v_pos,kanji);
                         v_pos.x += fw + wm;
                 }
                 else if (str[j] >= 0xE0 && str[j] <= 0xEF)
                 {
                         wide = str[j++]<<8;
                         wide += str[j];
                         q = draw_fontx_char(q,wide,&v_pos,kanji);
                         v_pos.x += fw + wm;
                 }
                 else
                 {
                         v_pos.x += fw + wm;
                 }
         }
         q = draw_prim_end(q,2,DRAW_XYZ_REGLIST);
         return q;
 }
References CENTER_ALIGN, charprim, context, draw_fontx_char(), draw_prim_end(), draw_prim_start(), DRAW_XYZ_REGLIST, fontx_t::font, fontx_t::h_margin, LEFT_ALIGN, RIGHT_ALIGN, v0, fontx_t::w_margin, fontx_hdr::width, vertex_t::x, and vertex_t::y.
Referenced by run_demo().
fontx_unload()
void fontx_unload (fontx_t * fontx)
Frees memory if a font is loaded
Definition at line 383 of file fontx.c.
 {
         if (fontx->font != NULL)
         {
                 free(fontx->font);
         }
 }
References fontx_t::font, and NULL.
Referenced by main().