ps2sdk: ee/graph/src/graph_vram.c File Reference
graph_vram.c File Reference
#include <gs_psm.h>
#include <graph_vram.h>
Functions
int graph_vram_allocate (int width, int height, int psm, int alignment)
void graph_vram_free (int address)
void graph_vram_clear (void)
int graph_vram_size (int width, int height, int psm, int alignment)
Variables
static int graph_vram_pointer = 0
Function Documentation
graph_vram_allocate()
int graph_vram_allocate (int width, int height, int psm, int alignment)
Allocates vram and returns vram base pointer
Definition at line 7 of file graph_vram.c.
 {
         int size;
         // Calculate the size and increment the pointer
         size = graph_vram_size(width,height,psm,alignment);
         graph_vram_pointer += size;
         // If the pointer overflows the vram size
         if (graph_vram_pointer > GRAPH_VRAM_MAX_WORDS)
         {
                 graph_vram_pointer -= size;
                 return -1;
         }
         return graph_vram_pointer - size;
 }
References GRAPH_VRAM_MAX_WORDS, graph_vram_pointer, and graph_vram_size().
Referenced by draw_init_env(), init_gs(), init_texture(), and main().
graph_vram_clear()
void graph_vram_clear (void)
Clears the vram status
Definition at line 37 of file graph_vram.c.
 {
         graph_vram_pointer = 0;
 }
References graph_vram_pointer.
graph_vram_free()
void graph_vram_free (int address)
Frees in FIFO order...
Definition at line 30 of file graph_vram.c.
 {
         graph_vram_pointer = address;
 }
References graph_vram_pointer.
Referenced by main().
graph_vram_size()
int graph_vram_size (int width, int height, int psm, int alignment)
Calculate the size in vram of a texture or buffer
Definition at line 44 of file graph_vram.c.
 {
         int size = 0;
         // First correct the buffer width to be a multiple of 64 or 128
         // If the width is less than or equal to 16, then it's a palette
         if (width > 16)
         {
                 switch (psm)
                 {
                         case GS_PSM_8:
                         case GS_PSM_4:
                         case GS_PSM_8H:
                         case GS_PSM_4HL:
                         case GS_PSM_4HH:        width = -128 & (width + 127); break;
                         default:                        width = -64  & (width + 63);  break;
                 }
         }
         // Texture storage size is in pixels/word
         switch (psm)
         {
                 case GS_PSM_4:          size = width*(height>>3); break;
                 case GS_PSM_8:          size = width*(height>>2); break;
                 case GS_PSM_24:
                 case GS_PSM_32:
                 case GS_PSM_8H:
                 case GS_PSM_4HL:
                 case GS_PSM_4HH:
                 case GS_PSMZ_24:
                 case GS_PSMZ_32:        size = width*height; break;
                 case GS_PSM_16:
                 case GS_PSM_16S:
                 case GS_PSMZ_16:
                 case GS_PSMZ_16S:       size = width*(height>>1); break;
                 default: return 0;
         }
         // The buffer size is dependent on alignment
         size = -alignment & (size + (alignment-1));
         return size;
 }
References GS_PSM_16, GS_PSM_16S, GS_PSM_24, GS_PSM_32, GS_PSM_4, GS_PSM_4HH, GS_PSM_4HL, GS_PSM_8, GS_PSM_8H, GS_PSMZ_16, GS_PSMZ_16S, GS_PSMZ_24, and GS_PSMZ_32.
Referenced by graph_vram_allocate().
Variable Documentation
graph_vram_pointer
int graph_vram_pointer = 0 static
Definition at line 5 of file graph_vram.c.
Referenced by graph_vram_allocate(), graph_vram_clear(), and graph_vram_free().