ps2sdk: VIF
VIF
Packet2 library
Macros
#define MAKE_VIF_CODE(_immediate, _num, _cmd, _irq) ((u32)(_immediate) | ((u32)(_num) << 16) | ((u32)(_cmd) << 24) | ((u32)(_irq) << 31))
Functions
static void packet2_vif_open_unpack (packet2_t *packet2, enum UnpackMode mode, u32 vuAddr, u8 dblBuffered, u8 masked, u8 usigned, u8 irq)
static void packet2_vif_close_unpack_manual (packet2_t *packet2, u32 unpack_num)
u32 packet2_vif_close_unpack_auto (packet2_t *packet2, u32 wl, u32 cl)
static void packet2_vif_open_direct (packet2_t *packet2, u8 irq)
static void packet2_vif_close_direct_manual (packet2_t *packet2, u32 qwords)
static void packet2_vif_close_direct_auto (packet2_t *packet2)
static void packet2_vif_nop (packet2_t *packet2, u8 irq)
static void packet2_vif_pad96 (packet2_t *packet2)
static void packet2_vif_pad128 (packet2_t *packet2)
static void packet2_vif_mpg (packet2_t *packet2, u32 num, u32 addr, u8 irq)
static void packet2_vif_stcycl (packet2_t *packet2, u32 wl, u32 cl, u8 irq)
static void packet2_vif_offset (packet2_t *packet2, u32 offset, u8 irq)
static void packet2_vif_base (packet2_t *packet2, u32 base, u8 irq)
static void packet2_vif_flush (packet2_t *packet2, u8 irq)
static void packet2_vif_mscal (packet2_t *packet2, u32 addr, u8 irq)
static void packet2_vif_mscnt (packet2_t *packet2, u8 irq)
static void packet2_vif_itop (packet2_t *packet2, u32 itops, u8 irq)
static void packet2_vif_stmod (packet2_t *packet2, u32 mode, u8 irq)
static void packet2_vif_mskpath3 (packet2_t *packet2, u32 mask, u8 irq)
static void packet2_vif_mark (packet2_t *packet2, u32 value, u8 irq)
static void packet2_vif_flushe (packet2_t *packet2, u8 irq)
static void packet2_vif_flusha (packet2_t *packet2, u8 irq)
static void packet2_vif_mscalf (packet2_t *packet2, u32 addr, u8 irq)
static void packet2_vif_stmask (packet2_t *packet2, Mask mask, u8 irq)
static void packet2_vif_strow (packet2_t *packet2, const u32 *row_arr, u8 irq)
static void packet2_vif_stcol (packet2_t *packet2, const u32 *col_arr, u8 irq)
void packet2_vif_add_micro_program (packet2_t *packet2, u32 dest, u32 *start, u32 *end)
Detailed Description
VIF related functions of libpacket2.
Macro Definition Documentation
MAKE_VIF_CODE
#define MAKE_VIF_CODE (_immediate, _num, _cmd, _irq) ((u32)(_immediate) | ((u32)(_num) << 16) | ((u32)(_cmd) << 24) | ((u32)(_irq) << 31))
Definition at line 26 of file packet2_vif.h.
Function Documentation
packet2_vif_add_micro_program()
void packet2_vif_add_micro_program (packet2_t * packet2, u32 dest, u32 * start, u32 * end)
Add VU micro program into packet2. Packet2 MODE for micro program upload: Chain
Parameters
dest VU destination address (divided by 16).
start Start address.
end End address.
Definition at line 14 of file packet2_vif.c.
 {
     // get the size of the code as we can only send 256 instructions in each MPGtag
     u32 count = (end - start) / 2;
     if (count & 1)
         count++;
     u32 *l_start = start;
     while (count > 0)
     {
         u16 curr_count = count > 256 ? 256 : count;
         packet2_chain_ref(packet2, l_start, curr_count / 2, 0, 0, 0);
         packet2_vif_nop(packet2, 0);
         packet2_vif_mpg(packet2, curr_count & 0xFF, dest, 0);
         l_start += curr_count * 2;
         count -= curr_count;
         dest += curr_count;
     }
 }
References packet2_chain_ref(), packet2_vif_mpg(), and packet2_vif_nop().
Referenced by vu1_upload_micro_program().
packet2_vif_base()
static void packet2_vif_base (packet2_t * packet2, u32 base, u8 irq) inline static
Add BASE VIF opcode.
Note
Alignment alert. Size of word (1/4). For more details, check description of VIFOpcode.
Parameters
packet2 Pointer to packet.
base Base address of double buffer.
irq Interrupt Request. False by default.
Definition at line 207 of file packet2_vif.h.
     {
         packet2_add_u32(packet2, MAKE_VIF_CODE(base, 0, P2_VIF_BASE, irq));
     }
References MAKE_VIF_CODE, P2_VIF_BASE, and packet2_add_u32().
Referenced by packet2_utils_vu_add_double_buffer().
packet2_vif_close_direct_auto()
static void packet2_vif_close_direct_auto (packet2_t * packet2) inline static
Close DIRECT automatically. In reality, get back to pointer "vif_code_opened_at" and fix immediate value with qwords counted from last packet2_vif_open_direct().
Parameters
packet2 Pointer to packet.
Definition at line 123 of file packet2_vif.h.
     {
         return packet2_vif_close_direct_manual(packet2, ((u32)packet2->next - ((u32)packet2->vif_code_opened_at + 4)) >> 4);
     }
References packet2_t::next, packet2_vif_close_direct_manual(), and packet2_t::vif_code_opened_at.
packet2_vif_close_direct_manual()
static void packet2_vif_close_direct_manual (packet2_t * packet2, u32 qwords) inline static
Close DIRECT manually. In reality, get back to pointer "vif_code_opened_at" and fix immediate value with given value.
Parameters
packet2 Pointer to packet.
qwords Qwords count.
Definition at line 109 of file packet2_vif.h.
     {
         assert(packet2->vif_code_opened_at != NULL); // There is open UNPACK/DIRECT.
         assert((((u32)packet2->next - ((u32)packet2->vif_code_opened_at + 4)) & 0xF) == 0);
         packet2->vif_code_opened_at->immediate = qwords;
         packet2->vif_code_opened_at = (vif_code_t *)NULL;
     }
References vif_code_t::immediate, packet2_t::next, NULL, and packet2_t::vif_code_opened_at.
Referenced by packet2_vif_close_direct_auto().
packet2_vif_close_unpack_auto()
u32 packet2_vif_close_unpack_auto (packet2_t * packet2, u32 wl, u32 cl)
Close UNPACK automatically. In reality, get back to pointer "vif_code_opened_at" and fix num value with qwords counted from last packet2_vif_open_unpack().
Parameters
packet2 Pointer to packet.
wl WL Value (look at STCYCL)
cl CL Value (look at STCYCL)
Returns
Unpacked qwords count
Definition at line 34 of file packet2_vif.c.
 {
     assert(packet2->vif_code_opened_at != NULL);               // There is open UNPACK/DIRECT.
     assert(((u32)packet2->next & 0x3) == 0);                   // Make sure we're u32 aligned
     assert((packet2->vif_code_opened_at->cmd & 0x60) == 0x60); // It was UNPACK
     u32 vn = (packet2->vif_code_opened_at->cmd & 0xC) >> 2;
     u32 vl = packet2->vif_code_opened_at->cmd & 0x3;
     // "the goal here is to find the num field of the open unpack, which is the number of
     // qwords ACTUALLY WRITTEN to vu memory (it does not count quads that are skipped in
     // "skipping write" mode.)  But first forget about skipping/filling writes and compute the number
     // of qwords that the data in this packet will expand to."
     u32 bytes_count = (u32)packet2->next - (u32)packet2->vif_code_opened_at - 4;
     u32 block_bytes_count = 4 >> vl;
     u32 quad_blocks_count = vn + 1;
     // "make sure that the data length is a multiple of 8, 16, or 32 bits, whichever is appropriate"
     assert((bytes_count & (block_bytes_count - 1)) == 0);
     u32 quads_count = (bytes_count / block_bytes_count) / quad_blocks_count;
     // "We have the number of quads our data will directly expand to, so now we need to account for
     // skipping/filling write modes.""
     // "skipping write is easy -- we are already done"
     // "filling write: now we get ambiguous -- what to do when quads_count == CL in the last
     // block? I will say that in this case the vif should still do the full wl length block, filling
     // with internal registers. If you want different behavior call packet2_vif_close_unpack_manual
     // with a num field you've computed yourself"
     if (cl < wl)
     {
         u32 wl_blocks_count = (quads_count / cl);
         u32 last_block_quads = quads_count - wl_blocks_count * cl;
         if (last_block_quads == cl)
             last_block_quads = wl;
         quads_count = wl_blocks_count * wl + last_block_quads;
     }
     packet2_vif_close_unpack_manual(packet2, quads_count);
     return quads_count;
 }
References vif_code_t::cmd, packet2_t::next, NULL, packet2_vif_close_unpack_manual(), and packet2_t::vif_code_opened_at.
Referenced by packet2_utils_vu_close_unpack().
packet2_vif_close_unpack_manual()
static void packet2_vif_close_unpack_manual (packet2_t * packet2, u32 unpack_num) inline static
Close UNPACK manually. In reality, get back to pointer "vif_code_opened_at" and fix num value with qwords counted from last packet2_vif_open_unpack().
Parameters
packet2 Pointer to packet.
unpack_num Amount of data written to the VU Mem (qwords) or MicroMem (dwords). 256 is max value!
Definition at line 68 of file packet2_vif.h.
     {
         assert(packet2->vif_code_opened_at != NULL);               // There is open UNPACK/DIRECT.
         assert(((u32)packet2->next & 0x3) == 0);                   // Make sure we're u32 aligned
         assert((packet2->vif_code_opened_at->cmd & 0x60) == 0x60); // It was UNPACK
         assert(unpack_num <= 256);
         packet2->vif_code_opened_at->num = (unpack_num == 256) ? 0 : unpack_num;
         packet2->vif_code_opened_at = (vif_code_t *)NULL;
     }
References vif_code_t::cmd, packet2_t::next, NULL, vif_code_t::num, and packet2_t::vif_code_opened_at.
Referenced by packet2_utils_vu_add_unpack_data(), and packet2_vif_close_unpack_auto().
packet2_vif_flush()
static void packet2_vif_flush (packet2_t * packet2, u8 irq) inline static
Add FLUSH VIF opcode.
Note
Alignment alert. Size of word (1/4). For more details, check description of VIFOpcode.
Parameters
packet2 Pointer to packet.
irq Interrupt Request. False by default.
Definition at line 219 of file packet2_vif.h.
     {
         packet2_add_u32(packet2, MAKE_VIF_CODE(0, 0, P2_VIF_FLUSH, irq));
     }
References MAKE_VIF_CODE, P2_VIF_FLUSH, and packet2_add_u32().
Referenced by packet2_utils_vu_add_continue_program(), and packet2_utils_vu_add_start_program().
packet2_vif_flusha()
static void packet2_vif_flusha (packet2_t * packet2, u8 irq) inline static
Add FLUSHA VIF opcode.
Note
Alignment alert. Size of word (1/4). For more details, check description of VIFOpcode.
Parameters
packet2 Pointer to packet.
irq Interrupt Request. False by default.
Definition at line 320 of file packet2_vif.h.
     {
         packet2_add_u32(packet2, MAKE_VIF_CODE(0, 0, P2_VIF_FLUSHA, irq));
     }
References MAKE_VIF_CODE, P2_VIF_FLUSHA, and packet2_add_u32().
packet2_vif_flushe()
static void packet2_vif_flushe (packet2_t * packet2, u8 irq) inline static
Add FLUSHE VIF opcode.
Note
Alignment alert. Size of word (1/4). For more details, check description of VIFOpcode.
Parameters
packet2 Pointer to packet.
irq Interrupt Request. False by default.
Definition at line 308 of file packet2_vif.h.
     {
         packet2_add_u32(packet2, MAKE_VIF_CODE(0, 0, P2_VIF_FLUSHE, irq));
     }
References MAKE_VIF_CODE, P2_VIF_FLUSHE, and packet2_add_u32().
packet2_vif_itop()
static void packet2_vif_itop (packet2_t * packet2, u32 itops, u8 irq) inline static
Add ITOP VIF opcode.
Note
Alignment alert. Size of word (1/4). For more details, check description of VIFOpcode.
Parameters
packet2 Pointer to packet.
itops Value for VU XITOP instruction.
irq Interrupt Request. False by default.
Definition at line 257 of file packet2_vif.h.
     {
         packet2_add_u32(packet2, MAKE_VIF_CODE(itops, 0, P2_VIF_ITOP, irq));
     }
References MAKE_VIF_CODE, P2_VIF_ITOP, and packet2_add_u32().
packet2_vif_mark()
static void packet2_vif_mark (packet2_t * packet2, u32 value, u8 irq) inline static
Add MARK VIF opcode.
Note
Alignment alert. Size of word (1/4). For more details, check description of VIFOpcode.
Parameters
packet2 Pointer to packet.
value Value.
irq Interrupt Request. False by default.
Definition at line 296 of file packet2_vif.h.
     {
         packet2_add_u32(packet2, MAKE_VIF_CODE(value, 0, P2_VIF_MARK, irq));
     }
References MAKE_VIF_CODE, P2_VIF_MARK, and packet2_add_u32().
packet2_vif_mpg()
static void packet2_vif_mpg (packet2_t * packet2, u32 num, u32 addr, u8 irq) inline static
Add MPG VIF opcode.
Note
Alignment alert. Size of word (1/4). For more details, check description of VIFOpcode.
Parameters
packet2 Pointer to packet.
num Number of 64-bit data.
addr Address.
irq Interrupt Request. False by default.
Definition at line 167 of file packet2_vif.h.
     {
         packet2_add_u32(packet2, MAKE_VIF_CODE(addr, num, P2_VIF_MPG, irq));
     }
References MAKE_VIF_CODE, P2_VIF_MPG, and packet2_add_u32().
Referenced by packet2_vif_add_micro_program().
packet2_vif_mscal()
static void packet2_vif_mscal (packet2_t * packet2, u32 addr, u8 irq) inline static
Add MSCAL VIF opcode.
Note
Alignment alert. Size of word (1/4). For more details, check description of VIFOpcode.
Parameters
packet2 Pointer to packet.
addr Starting address.
irq Interrupt Request. False by default.
Definition at line 232 of file packet2_vif.h.
     {
         packet2_add_u32(packet2, MAKE_VIF_CODE(addr, 0, P2_VIF_MSCAL, irq));
     }
References MAKE_VIF_CODE, P2_VIF_MSCAL, and packet2_add_u32().
Referenced by packet2_utils_vu_add_start_program().
packet2_vif_mscalf()
static void packet2_vif_mscalf (packet2_t * packet2, u32 addr, u8 irq) inline static
Add MSCALF VIF opcode.
Note
Alignment alert. Size of word (1/4). For more details, check description of VIFOpcode.
Parameters
packet2 Pointer to packet.
addr Address.
irq Interrupt Request. False by default.
Definition at line 333 of file packet2_vif.h.
     {
         packet2_add_u32(packet2, MAKE_VIF_CODE(addr, 0, P2_VIF_MSCALF, irq));
     }
References MAKE_VIF_CODE, P2_VIF_MSCALF, and packet2_add_u32().
packet2_vif_mscnt()
static void packet2_vif_mscnt (packet2_t * packet2, u8 irq) inline static
Add MSCNT VIF opcode.
Note
Alignment alert. Size of word (1/4). For more details, check description of VIFOpcode.
Parameters
packet2 Pointer to packet.
irq Interrupt Request. False by default.
Definition at line 244 of file packet2_vif.h.
     {
         packet2_add_u32(packet2, MAKE_VIF_CODE(0, 0, P2_VIF_MSCNT, irq));
     }
References MAKE_VIF_CODE, P2_VIF_MSCNT, and packet2_add_u32().
Referenced by packet2_utils_vu_add_continue_program().
packet2_vif_mskpath3()
static void packet2_vif_mskpath3 (packet2_t * packet2, u32 mask, u8 irq) inline static
Add MSKPATH3 VIF opcode.
Note
Alignment alert. Size of word (1/4). For more details, check description of VIFOpcode.
Parameters
packet2 Pointer to packet.
mask Mask.
irq Interrupt Request. False by default.
Definition at line 283 of file packet2_vif.h.
     {
         packet2_add_u32(packet2, MAKE_VIF_CODE(mask, 0, P2_VIF_MSKPATH3, irq));
     }
References MAKE_VIF_CODE, P2_VIF_MSKPATH3, and packet2_add_u32().
packet2_vif_nop()
static void packet2_vif_nop (packet2_t * packet2, u8 irq) inline static
Add NOP VIF opcode.
Note
Alignment alert. Size of word (1/4). For more details, check description of VIFOpcode.
Parameters
packet2 Pointer to packet.
irq Interrupt Request. False by default.
Definition at line 135 of file packet2_vif.h.
     {
         packet2_add_u32(packet2, MAKE_VIF_CODE(0, 0, P2_VIF_NOP, irq));
     }
References MAKE_VIF_CODE, P2_VIF_NOP, and packet2_add_u32().
Referenced by packet2_utils_vu_add_end_tag(), and packet2_vif_add_micro_program().
packet2_vif_offset()
static void packet2_vif_offset (packet2_t * packet2, u32 offset, u8 irq) inline static
Add OFFSET VIF opcode.
Note
Alignment alert. Size of word (1/4). For more details, check description of VIFOpcode.
Parameters
packet2 Pointer to packet.
offset Offset. BASE+OFFSET will be the address of second buffer.
irq Interrupt Request. False by default.
Definition at line 194 of file packet2_vif.h.
     {
         packet2_add_u32(packet2, MAKE_VIF_CODE(offset, 0, P2_VIF_OFFSET, irq));
     }
References MAKE_VIF_CODE, P2_VIF_OFFSET, and packet2_add_u32().
Referenced by packet2_utils_vu_add_double_buffer().
packet2_vif_open_direct()
static void packet2_vif_open_direct (packet2_t * packet2, u8 irq) inline static
Add DIRECT VIF opcode.
Note
Direct must be closed via packet2_vif_close_direct_manual() or packet2_vif_close : "memory"
Definition at line 95 of file packet2_vif.h.
     {
         assert(packet2->vif_code_opened_at == NULL); // All previous UNPACK/DIRECT are closed.
         packet2->vif_code_opened_at = (vif_code_t *)packet2->next;
         packet2_add_u32(packet2, MAKE_VIF_CODE(0, 0, P2_VIF_DIRECT, irq));
     }
References MAKE_VIF_CODE, packet2_t::next, NULL, P2_VIF_DIRECT, packet2_add_u32(), and packet2_t::vif_code_opened_at.
packet2_vif_open_unpack()
static void packet2_vif_open_unpack (packet2_t * packet2, enum UnpackMode mode, u32 vuAddr, u8 dblBuffered, u8 masked, u8 usigned, u8 irq) inline static
Add UNPACK VIF opcode.
Note
packet2_vif_close_unpack() required. Qwords are counted automatically. For more details, check description of vif_code_t.
Parameters
packet2 Pointer to packet.
mode Unpack mode
vuAddr Memory address (divided by 16).
dblBuffered (VIF1 only) 1 - Adds VIF1_TOPS register to ADDR 0 - Does not use VIF1_TOPS register.
masked Is masked
usigned 1 - Unsigned - Decompress by padding 0 to the upper field 0 - Signed - Decompress by sign extension
irq Interrupt Request. False by default.
Definition at line 50 of file packet2_vif.h.
     {
         assert(packet2->vif_code_opened_at == NULL); // All previous UNPACK/DIRECT are closed.
         packet2->vif_code_opened_at = (vif_code_t *)packet2->next;
         packet2_add_u32(packet2,
                         MAKE_VIF_CODE(vuAddr | ((u32)usigned << 14) | ((u32)dblBuffered << 15),
                                       0,
                                       mode | ((u32)masked << 4) | 0x60, irq));
     }
References MAKE_VIF_CODE, mode, packet2_t::next, NULL, packet2_add_u32(), and packet2_t::vif_code_opened_at.
Referenced by packet2_utils_vu_add_unpack_data(), and packet2_utils_vu_open_unpack().
packet2_vif_pad128()
static void packet2_vif_pad128 (packet2_t * packet2) inline static
Fill with NOP VIF opcode to align to 128bits
Parameters
packet2 Pointer to packet.
Definition at line 153 of file packet2_vif.h.
     {
         packet2_pad128(packet2, MAKE_VIF_CODE(0, 0, P2_VIF_NOP, 0));
     }
References MAKE_VIF_CODE, P2_VIF_NOP, and packet2_pad128().
Referenced by packet2_utils_vu_close_unpack().
packet2_vif_pad96()
static void packet2_vif_pad96 (packet2_t * packet2) inline static
Fill with NOP VIF opcode to align to 96bits
Parameters
packet2 Pointer to packet.
Definition at line 144 of file packet2_vif.h.
     {
         packet2_pad96(packet2, MAKE_VIF_CODE(0, 0, P2_VIF_NOP, 0));
     }
References MAKE_VIF_CODE, P2_VIF_NOP, and packet2_pad96().
packet2_vif_stcol()
static void packet2_vif_stcol (packet2_t * packet2, const u32 * col_arr, u8 irq) inline static
Add STCOL VIF opcode.
Note
Alignment alert. Size of 5 x word (1+1/4). For more details, check description of VIFOpcode.
Parameters
packet2 Pointer to packet.
col_arr Column array.
irq Interrupt Request. False by default.
Definition at line 377 of file packet2_vif.h.
     {
         packet2_add_u32(packet2, MAKE_VIF_CODE(0, 0, P2_VIF_STCOL, irq));
         packet2_add_u32(packet2, col_arr[0]);
         packet2_add_u32(packet2, col_arr[1]);
         packet2_add_u32(packet2, col_arr[2]);
         packet2_add_u32(packet2, col_arr[3]);
     }
References MAKE_VIF_CODE, P2_VIF_STCOL, and packet2_add_u32().
packet2_vif_stcycl()
static void packet2_vif_stcycl (packet2_t * packet2, u32 wl, u32 cl, u8 irq) inline static
Add STCYCL VIF opcode.
Note
Alignment alert. Size of word (1/4). For more details, check description of VIFOpcode.
Parameters
packet2 Pointer to packet.
wl WL field.
cl CL field.
irq Interrupt Request. False by default.
Definition at line 181 of file packet2_vif.h.
     {
         packet2_add_u32(packet2, MAKE_VIF_CODE(cl | (wl << 8), 0, P2_VIF_STCYCL, irq));
     }
References MAKE_VIF_CODE, P2_VIF_STCYCL, and packet2_add_u32().
Referenced by packet2_utils_vu_add_unpack_data(), and packet2_utils_vu_open_unpack().
packet2_vif_stmask()
static void packet2_vif_stmask (packet2_t * packet2, Mask mask, u8 irq) inline static
Add STMASK VIF opcode.
Note
Alignment alert. Size of dword (1/2). For more details, check description of VIFOpcode.
Parameters
packet2 Pointer to packet.
mask Mask.
irq Interrupt Request. False by default.
Definition at line 346 of file packet2_vif.h.
     {
         packet2_add_u32(packet2, MAKE_VIF_CODE(0, 0, P2_VIF_STMASK, irq));
         packet2_add_u32(packet2, mask.m);
     }
References Mask::m, MAKE_VIF_CODE, P2_VIF_STMASK, and packet2_add_u32().
packet2_vif_stmod()
static void packet2_vif_stmod (packet2_t * packet2, u32 mode, u8 irq) inline static
Add MSKPATH3 VIF opcode.
Note
Alignment alert. Size of word (1/4). For more details, check description of VIFOpcode.
Parameters
packet2 Pointer to packet.
mode Decompression mode.
irq Interrupt Request. False by default.
Definition at line 270 of file packet2_vif.h.
     {
         packet2_add_u32(packet2, MAKE_VIF_CODE(mode, 0, P2_VIF_STMOD, irq));
     }
References MAKE_VIF_CODE, mode, P2_VIF_STMOD, and packet2_add_u32().
packet2_vif_strow()
static void packet2_vif_strow (packet2_t * packet2, const u32 * row_arr, u8 irq) inline static
Add STROW VIF opcode.
Note
Alignment alert. Size of 5 x word (1+1/4). For more details, check description of VIFOpcode.
Parameters
packet2 Pointer to packet.
row_arr Row array.
irq Interrupt Request. False by default.
Definition at line 360 of file packet2_vif.h.
     {
         packet2_add_u32(packet2, MAKE_VIF_CODE(0, 0, P2_VIF_STROW, irq));
         packet2_add_u32(packet2, row_arr[0]);
         packet2_add_u32(packet2, row_arr[1]);
         packet2_add_u32(packet2, row_arr[2]);
         packet2_add_u32(packet2, row_arr[3]);
     }
References MAKE_VIF_CODE, P2_VIF_STROW, and packet2_add_u32().