ps2sdk: Utils
Utils
Packet2 library
Macros
#define VU_GS_PRIM(PRIM, IIP, TME, FGE, ABE, AA1, FST, CTXT, FIX) (u128)(((FIX << 10) | (CTXT << 9) | (FST << 8) | (AA1 << 7) | (ABE << 6) | (FGE << 5) | (TME << 4) | (IIP << 3) | (PRIM)))
#define VU_GS_GIFTAG(NLOOP, EOP, PRE, PRIM, FLG, NREG) (((u64)(NREG) << 60) | ((u64)(FLG) << 58) | ((u64)(PRIM) << 47) | ((u64)(PRE) << 46) | (EOP << 15) | (NLOOP << 0))
Functions
static void packet2_utils_vu_add_double_buffer (packet2_t *packet2, u16 base, u16 offset)
static void packet2_utils_vu_add_unpack_data (packet2_t *packet2, u32 t_dest_address, void *t_data, u32 t_size, u8 t_use_top)
static void packet2_utils_vu_open_unpack (packet2_t *packet2, u32 t_dest_address, u8 t_use_top)
static u32 packet2_utils_vu_close_unpack (packet2_t *packet2)
static void packet2_utils_vu_add_continue_program (packet2_t *packet2)
static void packet2_utils_vu_add_start_program (packet2_t *packet2, u32 addr)
static void packet2_utils_vu_add_end_tag (packet2_t *packet2)
static u32 packet2_utils_get_packet_size_for_program (u32 *start, u32 *end)
static void packet2_utils_gif_add_set (packet2_t *packet2, u32 loops_count)
static void packet2_utils_gs_add_lod (packet2_t *packet2, lod_t *lod)
static void packet2_utils_gs_add_texbuff_clut (packet2_t *packet2, texbuffer_t *texbuff, clutbuffer_t *clut)
static void packet2_utils_gs_add_draw_finish_giftag (packet2_t *packet2)
static void packet2_utils_gs_add_prim_giftag (packet2_t *packet2, prim_t *prim, u32 loops_count, u32 nreg, u8 nreg_count, u8 context)
Detailed Description
Useful functions and examples for libpacket2.
Macro Definition Documentation
VU_GS_GIFTAG
#define VU_GS_GIFTAG (NLOOP, EOP, PRE, PRIM, FLG, NREG) (((u64)(NREG) << 60) | ((u64)(FLG) << 58) | ((u64)(PRIM) << 47) | ((u64)(PRE) << 46) | (EOP << 15) | (NLOOP << 0))
Definition at line 33 of file packet2_utils.h.
VU_GS_PRIM
#define VU_GS_PRIM (PRIM, IIP, TME, FGE, ABE, AA1, FST, CTXT, FIX) (u128)(((FIX << 10) | (CTXT << 9) | (FST << 8) | (AA1 << 7) | (ABE << 6) | (FGE << 5) | (TME << 4) | (IIP << 3) | (PRIM)))
Definition at line 32 of file packet2_utils.h.
Function Documentation
packet2_utils_get_packet_size_for_program()
static u32 packet2_utils_get_packet_size_for_program (u32 * start, u32 * end) inline static
Get program size in qws
Parameters
start Start address.
end End address.
Returns
Packet size in qws for specified program (instructions/256 + 1qw for tolerance).
Definition at line 138 of file packet2_utils.h.
     {
         // Count instructions
         u32 count = (end - start) / 2;
         if (count & 1)
             count++;
         return (count >> 8) + 1;
     }
Referenced by vu1_upload_micro_program().
packet2_utils_gif_add_set()
static void packet2_utils_gif_add_set (packet2_t * packet2, u32 loops_count) inline static
Add set GIFTag which will be sent from VU1 via XGKICK instruction.
Parameters
packet2 Pointer to packet2.
loops_count How many GIF tags there will be?
Definition at line 157 of file packet2_utils.h.
     {
         packet2_add_2x_s64(packet2, GIF_SET_TAG(loops_count, 0, 0, 0, GIF_FLG_PACKED, 1), GIF_REG_AD);
     }
References GIF_FLG_PACKED, GIF_REG_AD, GIF_SET_TAG, and packet2_add_2x_s64().
Referenced by calculate_cube().
packet2_utils_gs_add_draw_finish_giftag()
static void packet2_utils_gs_add_draw_finish_giftag (packet2_t * packet2) inline static
Add draw finish event GIFTag which will be sent from VU1 via XGKICK instruction. Used for synchronization via draw_wait_finish()
Parameters
packet2 Pointer to packet2.
Definition at line 220 of file packet2_utils.h.
     {
         packet2_add_2x_s64(packet2, 1, GS_REG_FINISH);
     }
References GS_REG_FINISH, and packet2_add_2x_s64().
packet2_utils_gs_add_lod()
static void packet2_utils_gs_add_lod (packet2_t * packet2, lod_t * lod) inline static
Add lod GIFTag which will be sent from VU1 via XGKICK instruction.
Parameters
packet2 Pointer to packet2.
lod Pointer to lod settings.
Definition at line 172 of file packet2_utils.h.
     {
         packet2_add_2x_s64(
             packet2,
             GS_SET_TEX1(
                 lod->calculation,
                 lod->max_level,
                 lod->mag_filter,
                 lod->min_filter,
                 lod->mipmap_select,
                 lod->l,
                 (int)(lod->k * 16.0F)),
             GS_REG_TEX1);
     }
References lod_t::calculation, GS_REG_TEX1, GS_SET_TEX1, lod_t::k, lod_t::l, lod, lod_t::mag_filter, lod_t::max_level, lod_t::min_filter, lod_t::mipmap_select, and packet2_add_2x_s64().
Referenced by calculate_cube().
packet2_utils_gs_add_prim_giftag()
static void packet2_utils_gs_add_prim_giftag (packet2_t * packet2, prim_t * prim, u32 loops_count, u32 nreg, u8 nreg_count, u8 context) inline static
Add drawing (prim) GIFTag which will be sent from VU1 via XGKICK instruction.
Parameters
packet2 Pointer to packet2.
prim Pointer to prim settings.
loops_count GIF tag loops count.
nreg What types of data we will use?
nreg_count How many types there are in nreg?
context Drawing context
Definition at line 235 of file packet2_utils.h.
     {
         packet2_add_2x_s64(
             packet2,
             VU_GS_GIFTAG(
                 loops_count, // Information for GS. Amount of loops
                 1,
                 1,
                 VU_GS_PRIM(
                     prim->type,
                     prim->shading,
                     prim->mapping,
                     prim->fogging,
                     prim->blending,
                     prim->antialiasing,
                     prim->mapping_type,
                     context, // context
                     prim->colorfix),
                 0,
                 nreg_count),
             nreg);
     }
References prim_t::antialiasing, prim_t::blending, prim_t::colorfix, context, prim_t::fogging, prim_t::mapping, prim_t::mapping_type, packet2_add_2x_s64(), prim, prim_t::shading, prim_t::type, VU_GS_GIFTAG, and VU_GS_PRIM.
Referenced by calculate_cube().
packet2_utils_gs_add_texbuff_clut()
static void packet2_utils_gs_add_texbuff_clut (packet2_t * packet2, texbuffer_t * texbuff, clutbuffer_t * clut) inline static
Add texture buffer / clut GIFTag which will be sent from VU1 via XGKICK instruction.
Parameters
packet2 Pointer to packet2.
texbuff Pointer to texture buffer.
clut Pointer to clut buffer.
Definition at line 194 of file packet2_utils.h.
     {
         packet2_add_2x_s64(
             packet2,
             GS_SET_TEX0(
                 texbuff->address >> 6,
                 texbuff->width >> 6,
                 texbuff->psm,
                 texbuff->info.width,
                 texbuff->info.height,
                 texbuff->info.components,
                 texbuff->info.function,
                 clut->address >> 6,
                 clut->psm,
                 clut->storage_mode,
                 clut->start,
                 clut->load_method),
             GS_REG_TEX0);
     }
References texbuffer_t::address, clutbuffer_t::address, clut, texinfo_t::components, texinfo_t::function, GS_REG_TEX0, GS_SET_TEX0, texinfo_t::height, texbuffer_t::info, clutbuffer_t::load_method, packet2_add_2x_s64(), texbuffer_t::psm, clutbuffer_t::psm, clutbuffer_t::start, clutbuffer_t::storage_mode, texinfo_t::width, and texbuffer_t::width.
Referenced by calculate_cube().
packet2_utils_vu_add_continue_program()
static void packet2_utils_vu_add_continue_program (packet2_t * packet2) inline static
Continue VU micro program (from –cont line). Adds FLUSH and MSCNT VIF opcodes.
Definition at line 103 of file packet2_utils.h.
     {
         packet2_chain_open_cnt(packet2, 0, 0, 0);
         packet2_vif_flush(packet2, 0);
         packet2_vif_mscnt(packet2, 0);
         packet2_chain_close_tag(packet2);
     }
References packet2_chain_close_tag(), packet2_chain_open_cnt(), packet2_vif_flush(), and packet2_vif_mscnt().
packet2_utils_vu_add_double_buffer()
static void packet2_utils_vu_add_double_buffer (packet2_t * packet2, u16 base, u16 offset) inline static
Add VU buffers size settings.
Parameters
t_base Base address (qw)
t_offset Offset address (qw)
Definition at line 49 of file packet2_utils.h.
     {
         packet2_chain_open_cnt(packet2, 0, 0, 0);
         packet2_vif_base(packet2, base, 0);
         packet2_vif_offset(packet2, offset, 0);
         packet2_chain_close_tag(packet2);
     }
References packet2_chain_close_tag(), packet2_chain_open_cnt(), packet2_vif_base(), and packet2_vif_offset().
Referenced by vu1_set_double_buffer_settings().
packet2_utils_vu_add_end_tag()
static void packet2_utils_vu_add_end_tag (packet2_t * packet2) inline static
Add aligned END tag (with nops).
Definition at line 124 of file packet2_utils.h.
     {
         packet2_chain_open_end(packet2, 0, 0);
         packet2_vif_nop(packet2, 0);
         packet2_vif_nop(packet2, 0);
         packet2_chain_close_tag(packet2);
     }
References packet2_chain_close_tag(), packet2_chain_open_end(), and packet2_vif_nop().
Referenced by draw_cube(), vu1_set_double_buffer_settings(), and vu1_upload_micro_program().
packet2_utils_vu_add_start_program()
static void packet2_utils_vu_add_start_program (packet2_t * packet2, u32 addr) inline static
Start VU micro program. Adds FLUSH and MSCAL VIF opcodes.
Definition at line 115 of file packet2_utils.h.
     {
         packet2_chain_open_cnt(packet2, 0, 0, 0);
         packet2_vif_flush(packet2, 0);
         packet2_vif_mscal(packet2, addr, 0);
         packet2_chain_close_tag(packet2);
     }
References packet2_chain_close_tag(), packet2_chain_open_cnt(), packet2_vif_flush(), and packet2_vif_mscal().
Referenced by draw_cube().
packet2_utils_vu_add_unpack_data()
static void packet2_utils_vu_add_unpack_data (packet2_t * packet2, u32 t_dest_address, void * t_data, u32 t_size, u8 t_use_top) inline static
Add data via REF tag and UNPACK. Please be sure that data is aligned, and there is no any open UNPACK/DIRECT.
Parameters
packet2 Pointer to packet2.
t_dest_address Destination address.
t_data Data pointer.
t_size Size in quadwords.
t_use_top Unpack to current double buffer?
Definition at line 67 of file packet2_utils.h.
     {
         packet2_chain_ref(packet2, t_data, t_size, 0, 0, 0);
         packet2_vif_stcycl(packet2, 0, 0x0101, 0);
         packet2_vif_open_unpack(packet2, P2_UNPACK_V4_32, t_dest_address, t_use_top, 0, 1, 0);
         packet2_vif_close_unpack_manual(packet2, t_size);
     }
References P2_UNPACK_V4_32, packet2_chain_ref(), packet2_vif_close_unpack_manual(), packet2_vif_open_unpack(), and packet2_vif_stcycl().
Referenced by draw_cube().
packet2_utils_vu_close_unpack()
static u32 packet2_utils_vu_close_unpack (packet2_t * packet2) inline static
Close CNT tag + VU unpack.
Returns
Unpacked qwords count
Definition at line 92 of file packet2_utils.h.
     {
         packet2_vif_pad128(packet2);
         packet2_chain_close_tag(packet2);
         return packet2_vif_close_unpack_auto(packet2, 0, 0x0101);
     }
References packet2_chain_close_tag(), packet2_vif_close_unpack_auto(), and packet2_vif_pad128().
packet2_utils_vu_open_unpack()
static void packet2_utils_vu_open_unpack (packet2_t * packet2, u32 t_dest_address, u8 t_use_top) inline static
Open CNT tag + VU unpack.
Parameters
packet2 Pointer to packet2.
t_dest_address Destination address.
t_use_top Unpack to current double buffer?
Definition at line 81 of file packet2_utils.h.
     {
         packet2_chain_open_cnt(packet2, 0, 0, 0);
         packet2_vif_stcycl(packet2, 0, 0x0101, 0);
         packet2_vif_open_unpack(packet2, P2_UNPACK_V4_32, t_dest_address, t_use_top, 0, 1, 0);
     }
References P2_UNPACK_V4_32, packet2_chain_open_cnt(), packet2_vif_open_unpack(), and packet2_vif_stcycl().