ps2sdk: Packet2 library
Packet2 library
Modules
Chain
Types
Utils
VIF
Functions
packet2_t * packet2_create (u16 qwords, enum Packet2Type type, enum Packet2Mode mode, u8 tte)
packet2_t * packet2_create_from (qword_t *base, qword_t *next, u16 qwords, enum Packet2Type type, enum Packet2Mode mode, u8 tte)
void packet2_free (packet2_t *packet2)
void packet2_reset (packet2_t *packet2, u8 clear_mem)
static void packet2_update (packet2_t *packet2, qword_t *qw)
static void packet2_advance_next (packet2_t *packet2, u32 i)
static void packet2_add_u128 (packet2_t *packet2, const u128 val)
static void packet2_add_s64 (packet2_t *packet2, const s64 val)
static void packet2_add_2x_s64 (packet2_t *packet2, const s64 v1, const s64 v2)
static void packet2_add_s128 (packet2_t *packet2, const s128 val)
static void packet2_add_u64 (packet2_t *packet2, const u64 val)
static void packet2_add_u32 (packet2_t *packet2, const u32 val)
static void packet2_add_s32 (packet2_t *packet2, const s32 val)
static void packet2_add_float (packet2_t *packet2, const float val)
static void packet2_add_data (packet2_t *packet2, void *t_data, u32 t_size)
static void packet2_pad96 (packet2_t *packet2, const u32 val)
static void packet2_pad128 (packet2_t *packet2, const u32 val)
void packet2_print (packet2_t *packet2, u32 qw_count)
void packet2_print_qw_count (packet2_t *packet2)
void packet2_add (packet2_t *a, packet2_t *b)
static u32 packet2_get_qw_count (packet2_t *packet2)
static u8 packet2_doesnt_have_even_number_of_quads (packet2_t *packet2)
static u8 packet2_is_dma_tag_opened (packet2_t *packet2)
static u8 packet2_is_vif_code_opened (packet2_t *packet2)
Detailed Description
Successor of packet_t. Main goal of this library is to create simple API for packet management. Library is splitted into several parts:
This - core functionality of libpacket2
"_types" - Enums and structures used in libpacket2
"_chain" - DMA tags
"_vif" - VU related
"_utils" - useful functions, and examples
Function Documentation
packet2_add()
void packet2_add (packet2_t * a, packet2_t * b)
Copy data from b packet into a packet with memcpy()
Definition at line 101 of file packet2.c.
 {
     assert(packet2_get_qw_count(a) + packet2_get_qw_count(b) <= a->max_qwords_count);
     memcpy(a->next, b->base, (u32)b->next - (u32)b->base);
     a->next = a->base + packet2_get_qw_count(b) + 1;
 }
References packet2_t::base, packet2_t::max_qwords_count, packet2_t::next, and packet2_get_qw_count().
packet2_add_2x_s64()
static void packet2_add_2x_s64 (packet2_t * packet2, const s64 v1, const s64 v2) inline static
Definition at line 114 of file packet2.h.
     {
         packet2_add_s64(packet2, v1);
         packet2_add_s64(packet2, v2);
     }
References packet2_add_s64(), and v1.
Referenced by packet2_utils_gif_add_set(), packet2_utils_gs_add_draw_finish_giftag(), packet2_utils_gs_add_lod(), packet2_utils_gs_add_prim_giftag(), and packet2_utils_gs_add_texbuff_clut().
packet2_add_data()
static void packet2_add_data (packet2_t * packet2, void * t_data, u32 t_size) inline static
Definition at line 154 of file packet2.h.
     {
         int i;
         for (i = 0; i < t_size; i++)
             packet2_add_u128(packet2, ((u128 *)t_data)[i]);
     }
References packet2_add_u128().
packet2_add_float()
static void packet2_add_float (packet2_t * packet2, const float val) inline static
Note
Alignment alert. Size of word (1/4)
Definition at line 148 of file packet2.h.
     {
         *((float *)packet2->next) = val;
         packet2_advance_next(packet2, sizeof(float));
     }
References packet2_t::next, and packet2_advance_next().
Referenced by calculate_cube().
packet2_add_s128()
static void packet2_add_s128 (packet2_t * packet2, const s128 val) inline static
Definition at line 120 of file packet2.h.
     {
         *((s128 *)packet2->next) = val;
         packet2_advance_next(packet2, sizeof(s128));
     }
References packet2_t::next, and packet2_advance_next().
packet2_add_s32()
static void packet2_add_s32 (packet2_t * packet2, const s32 val) inline static
Note
Alignment alert. Size of word (1/4)
Definition at line 141 of file packet2.h.
     {
         *((s32 *)packet2->next) = val;
         packet2_advance_next(packet2, sizeof(s32));
     }
References packet2_t::next, and packet2_advance_next().
Referenced by calculate_cube().
packet2_add_s64()
static void packet2_add_s64 (packet2_t * packet2, const s64 val) inline static
Note
Alignment alert. Size of dword (1/2)
Definition at line 108 of file packet2.h.
     {
         *((s64 *)packet2->next) = val;
         packet2_advance_next(packet2, sizeof(s64));
     }
References packet2_t::next, and packet2_advance_next().
Referenced by packet2_add_2x_s64().
packet2_add_u128()
static void packet2_add_u128 (packet2_t * packet2, const u128 val) inline static
Definition at line 101 of file packet2.h.
     {
         *((u128 *)packet2->next) = val;
         packet2_advance_next(packet2, sizeof(u128));
     }
References packet2_t::next, and packet2_advance_next().
Referenced by packet2_add_data().
packet2_add_u32()
static void packet2_add_u32 (packet2_t * packet2, const u32 val) inline static
Note
Alignment alert. Size of word (1/4)
Definition at line 134 of file packet2.h.
     {
         *((u32 *)packet2->next) = val;
         packet2_advance_next(packet2, sizeof(u32));
     }
References packet2_t::next, and packet2_advance_next().
Referenced by calculate_cube(), packet2_pad128(), packet2_pad96(), packet2_vif_base(), packet2_vif_flush(), packet2_vif_flusha(), packet2_vif_flushe(), packet2_vif_itop(), packet2_vif_mark(), packet2_vif_mpg(), packet2_vif_mscal(), packet2_vif_mscalf(), packet2_vif_mscnt(), packet2_vif_mskpath3(), packet2_vif_nop(), packet2_vif_offset(), packet2_vif_open_direct(), packet2_vif_open_unpack(), packet2_vif_stcol(), packet2_vif_stcycl(), packet2_vif_stmask(), packet2_vif_stmod(), and packet2_vif_strow().
packet2_add_u64()
static void packet2_add_u64 (packet2_t * packet2, const u64 val) inline static
Note
Alignment alert. Size of dword (1/2)
Definition at line 127 of file packet2.h.
     {
         *((u64 *)packet2->next) = val;
         packet2_advance_next(packet2, sizeof(u64));
     }
References packet2_t::next, and packet2_advance_next().
packet2_advance_next()
static void packet2_advance_next (packet2_t * packet2, u32 i) inline static
Move "next" pointer forward.
Definition at line 96 of file packet2.h.
     {
         packet2->next = (qword_t *)((u8 *)packet2->next + i);
     }
References packet2_t::next.
Referenced by packet2_add_float(), packet2_add_s128(), packet2_add_s32(), packet2_add_s64(), packet2_add_u128(), packet2_add_u32(), packet2_add_u64(), and packet2_chain_add_dma_tag().
packet2_create()
packet2_t* packet2_create (u16 qwords, enum Packet2Type type, enum Packet2Mode mode, u8 tte)
Allocate new packet2.
Parameters
qwords Maximum data size in qwords (128bit).
type Memory mapping type.
mode Packet mode. Normal or chain.
tte Tag transfer enable. Used only for CHAIN mode! If >0 transfer tag is set during packet sending and add_dma_tag() (so also every open_tag()) will move buffer by DWORD, so remember to align memory!
Returns
Pointer to packet2 on success or NULL if memory allocation fail.
Definition at line 25 of file packet2.c.
 {
     packet2_t *packet2 = (packet2_t *)calloc(1, sizeof(packet2_t));
     if (packet2 == NULL)
         return NULL;
     packet2->max_qwords_count = qwords;
     packet2->type = type;
     packet2->mode = mode;
     packet2->tte = tte;
     packet2->tag_opened_at = NULL;
     packet2->vif_code_opened_at = NULL;
     // Dma buffer size should be a whole number of cache lines (64 bytes = 4 quads)
     assert(!((packet2->type == P2_TYPE_UNCACHED || packet2->type == P2_TYPE_UNCACHED_ACCL) && packet2->max_qwords_count & (4 - 1)));
     u32 byte_size = packet2->max_qwords_count << 4;
     if ((packet2->base = memalign(P2_ALIGNMENT, byte_size)) == NULL)
     {
         free(packet2);
         return NULL;
     }
     packet2->base = packet2->next = (qword_t *)((u32)packet2->base | packet2->type);
     memset(packet2->base, 0, byte_size);
     // "I hate to do this, but I've wasted FAR too much time hunting down cache incoherency"
     if (packet2->type == P2_TYPE_UNCACHED || packet2->type == P2_TYPE_UNCACHED_ACCL)
         FlushCache(0);
     return packet2;
 }
References packet2_t::base, FlushCache(), packet2_t::max_qwords_count, mode, packet2_t::mode, packet2_t::next, NULL, P2_ALIGNMENT, P2_TYPE_UNCACHED, P2_TYPE_UNCACHED_ACCL, packet2_t::tag_opened_at, packet2_t::tte, packet2_t::type, and packet2_t::vif_code_opened_at.
Referenced by clear_screen(), init_drawing_environment(), main(), send_texture(), vu1_set_double_buffer_settings(), and vu1_upload_micro_program().
packet2_create_from()
packet2_t* packet2_create_from (qword_t * base, qword_t * next, u16 qwords, enum Packet2Type type, enum Packet2Mode mode, u8 tte)
Create new packet2 with given data pointer.
Parameters
base Pointer to base (start of buffer).
next Pointer to next (current position of buffer).
qwords Maximum data size in qwords (128bit).
type Memory mapping type.
mode Packet mode. Normal or chain (so also vif/vu).
tte Tag transfer enable. Used only for CHAIN mode! If >0 transfer tag is set during packet sending and add_dma_tag() (so also every open_tag()) will move buffer by DWORD, so remember to align memory!
Returns
Pointer to packet2 on success or NULL if memory allocation fail.
Definition at line 60 of file packet2.c.
 {
     // Dma buffer size should be a whole number of cache lines (64 bytes = 4 quads)
     assert(!((type == P2_TYPE_UNCACHED || type == P2_TYPE_UNCACHED_ACCL) && qwords & (4 - 1)));
     // Dma buffer should be aligned on a cache line (64-byte boundary)
     assert(!((type == P2_TYPE_UNCACHED || type == P2_TYPE_UNCACHED_ACCL) && (u32)base & (64 - 1)));
     packet2_t *packet2 = (packet2_t *)calloc(1, sizeof(packet2_t));
     if (packet2 == NULL)
         return NULL;
     packet2->base = base;
     packet2->next = next;
     packet2->max_qwords_count = qwords;
     packet2->type = type;
     packet2->tte = tte;
     packet2->mode = mode;
     return packet2;
 }
References packet2_t::base, packet2_t::max_qwords_count, mode, packet2_t::mode, packet2_t::next, NULL, P2_TYPE_UNCACHED, P2_TYPE_UNCACHED_ACCL, packet2_t::tte, and packet2_t::type.
packet2_doesnt_have_even_number_of_quads()
static u8 packet2_doesnt_have_even_number_of_quads (packet2_t * packet2) inline static
True if packet doesnt have even number of quads.
Definition at line 203 of file packet2.h.
 { return ((u32)packet2->next & 0xF) != 0; }
References packet2_t::next.
packet2_free()
void packet2_free (packet2_t * packet2)
Free packet2 memory.
Parameters
packet2 Pointer to packet2.
Definition at line 81 of file packet2.c.
 {
     if (packet2->base != NULL)
         free((qword_t *)P2_MAKE_PTR_NORMAL(packet2->base));
     free(packet2);
 }
References packet2_t::base, NULL, and P2_MAKE_PTR_NORMAL.
Referenced by clear_screen(), init_drawing_environment(), main(), send_texture(), vu1_set_double_buffer_settings(), and vu1_upload_micro_program().
packet2_get_qw_count()
static u32 packet2_get_qw_count (packet2_t * packet2) inline static
Returns count of added qwords into packet.
Definition at line 200 of file packet2.h.
 { return ((u32)packet2->next - (u32)packet2->base) >> 4; }
References packet2_t::base, and packet2_t::next.
Referenced by draw_cube(), packet2_add(), and packet2_print_qw_count().
packet2_is_dma_tag_opened()
static u8 packet2_is_dma_tag_opened (packet2_t * packet2) inline static
True if dma tag is opened.
Definition at line 206 of file packet2.h.
 { return packet2->tag_opened_at != NULL; }
References NULL, and packet2_t::tag_opened_at.
packet2_is_vif_code_opened()
static u8 packet2_is_vif_code_opened (packet2_t * packet2) inline static
True if DIRECT/UNPACK is opened.
Definition at line 209 of file packet2.h.
 { return packet2->vif_code_opened_at != NULL; }
References NULL, and packet2_t::vif_code_opened_at.
packet2_pad128()
static void packet2_pad128 (packet2_t * packet2, const u32 val) inline static
Fill to align to 128bits
Definition at line 173 of file packet2.h.
     {
         while (((u32)packet2->next & 0xf) != 0)
             packet2_add_u32(packet2, val);
     }
References packet2_t::next, and packet2_add_u32().
Referenced by packet2_vif_pad128().
packet2_pad96()
static void packet2_pad96 (packet2_t * packet2, const u32 val) inline static
Fill to align to 96bits
Definition at line 164 of file packet2.h.
     {
         while ((((u32)packet2->next + 4) & 0xf) != 0)
             packet2_add_u32(packet2, val);
     }
References packet2_t::next, and packet2_add_u32().
Referenced by packet2_vif_pad96().
packet2_print()
void packet2_print (packet2_t * packet2, u32 qw_count)
Print data of packet.
Parameters
packet2 Pointer to packet.
clear_mem Count of qwords, type 0 for all.
Definition at line 108 of file packet2.c.
 {
     if (qw_count == 0)
         qw_count = ((u32)packet2->next - (u32)packet2->base) >> 4;
     printf("\n============================\n");
     printf("Packet2: Dumping %d words...\n", ((u32)packet2->next - (u32)packet2->base) >> 2);
     u32 i = 0;
     u32 *nextWord;
     for (nextWord = (u32 *)packet2->base; nextWord != (u32 *)packet2->next; nextWord++, i++)
     {
         if ((i % 4) == 0)
             printf("\n0x%08x:  ", (u32)nextWord);
         printf("0x%08x ", *nextWord);
         if (i / 4 == qw_count)
             break;
     }
     printf("\n============================\n");
 }
References packet2_t::base, and packet2_t::next.
packet2_print_qw_count()
void packet2_print_qw_count (packet2_t * packet2)
Print amount of qwords of packet.
Parameters
packet2 Pointer to packet.
Definition at line 127 of file packet2.c.
 {
     printf("Packet2: Qwords count:%d \n", packet2_get_qw_count(packet2));
 }
References packet2_get_qw_count().
packet2_reset()
void packet2_reset (packet2_t * packet2, u8 clear_mem)
Reset packet. Move next pointer back to base pointer, Make all "openedAt" vars to NULL Do memset on data if required.
Parameters
packet2 Pointer to packet.
clear_mem If >0, data is cleared via memset(). SLOW!
Definition at line 88 of file packet2.c.
 {
     packet2->next = packet2->base;
     packet2->vif_code_opened_at = NULL;
     packet2->tag_opened_at = NULL;
     if (clear_mem)
         memset(packet2->base, 0, packet2->max_qwords_count << 4);
 }
References packet2_t::base, packet2_t::max_qwords_count, packet2_t::next, NULL, packet2_t::tag_opened_at, and packet2_t::vif_code_opened_at.
Referenced by draw_cube().
packet2_update()
static void packet2_update (packet2_t * packet2, qword_t * qw) inline static
Update current position of packet buffer. Useful with drawlib functions.
Definition at line 89 of file packet2.h.
 { packet2->next = qw; }
References packet2_t::next.
Referenced by clear_screen(), init_drawing_environment(), and send_texture().