ps2sdk: Chain
Chain
Packet2 library
Macros
#define PACKET2_COUNT_QWC 1 << 16
Functions
static void packet2_chain_set_dma_tag (dma_tag_t *tag, u32 qwc, u32 pce, u32 id, u8 irq, const u128 *addr, u8 spr)
static void packet2_chain_add_dma_tag (packet2_t *packet2, u32 qwc, u32 pce, enum DmaTagType id, u8 irq, const u128 *addr, u8 spr)
static void packet2_chain_close_tag (packet2_t *packet2)
static void packet2_chain_open_cnt (packet2_t *packet2, u8 irq, u32 pce, u8 spr)
static void packet2_chain_open_end (packet2_t *packet2, u8 irq, u32 pce)
static void packet2_chain_ref (packet2_t *packet2, const void *ref_data, u32 qw_length, u8 irq, u8 spr, u32 pce)
static void packet2_chain_next (packet2_t *packet2, const dma_tag_t *next_tag, u8 irq, u8 spr, u32 pce)
static void packet2_chain_refs (packet2_t *packet2, const void *ref_data, u32 qw_length, u8 irq, u8 spr, u32 pce)
static void packet2_chain_refe (packet2_t *packet2, const void *ref_data, u32 qw_length, u8 irq, u8 spr, u32 pce)
static void packet2_chain_call (packet2_t *packet2, const void *next_tag, u8 irq, u8 spr, u32 pce)
static void packet2_chain_ret (packet2_t *packet2, u8 irq, u32 pce)
Detailed Description
Chain mode related functions of libpacket2.
Macro Definition Documentation
PACKET2_COUNT_QWC
#define PACKET2_COUNT_QWC 1 << 16
Definition at line 26 of file packet2_chain.h.
Function Documentation
packet2_chain_add_dma_tag()
static void packet2_chain_add_dma_tag (packet2_t * packet2, u32 qwc, u32 pce, enum DmaTagType id, u8 irq, const u128 * addr, u8 spr) inline static
Add dma tag. For more details, check description of dma_tag_t. Will move current buffer position by: DWORD if packet->tte == true, QWORD if packet->tte == false
Parameters
packet2 Pointer to packet.
qwc Qword count. If you want to use packet2_chain_close_tag(), and count qwords automatically, set value to PACKET2_COUNT_QWC.
pce Priority Control Enable. 0 by default.
id Tag ID.
irq Interrupt Request. False by default.
addr Address.
spr Memory/SPR Selection. False by default.
Definition at line 74 of file packet2_chain.h.
     {
         assert(((u32)packet2->next & 0xF) == 0); // Free space in packet is aligned properly.
         assert(packet2->tag_opened_at == NULL);  // All previous tags are closed.
         if (qwc == PACKET2_COUNT_QWC)
         {
             packet2_chain_set_dma_tag((dma_tag_t *)packet2->next, 0, pce, id, irq, addr, spr); // placeholder
             packet2->tag_opened_at = (dma_tag_t *)packet2->next;
         }
         else
         {
             packet2_chain_set_dma_tag((dma_tag_t *)packet2->next, qwc, pce, id, irq, addr, spr);
             packet2->tag_opened_at = (dma_tag_t *)NULL;
         }
         if (!packet2->tte)
             packet2_advance_next(packet2, sizeof(dma_tag_t));
         else
             packet2_advance_next(packet2, sizeof(u64));
     }
References packet2_t::next, NULL, packet2_advance_next(), packet2_chain_set_dma_tag(), PACKET2_COUNT_QWC, packet2_t::tag_opened_at, and packet2_t::tte.
Referenced by packet2_chain_call(), packet2_chain_next(), packet2_chain_open_cnt(), packet2_chain_open_end(), packet2_chain_ref(), packet2_chain_refe(), packet2_chain_refs(), and packet2_chain_ret().
packet2_chain_call()
static void packet2_chain_call (packet2_t * packet2, const void * next_tag, u8 irq, u8 spr, u32 pce) inline static
Add CALL tag.
Note
packet2_chain_close_tag() required. Qwords are counted automatically. For more details, check description of dma_tag_t.
Parameters
packet2 Pointer to packet.
next_tag Pointer to next tag.
irq Interrupt Request. False by default.
spr Memory/SPR Selection. False by default.
pce Priority Control Enable. 0 by default.
Definition at line 223 of file packet2_chain.h.
     {
         assert(((u32)packet2->next & 0xF) == 0); // Free space in packet is aligned properly.
         packet2_chain_add_dma_tag(packet2, PACKET2_COUNT_QWC, pce, P2_DMA_TAG_CALL, irq, (u128 *)next_tag, spr);
     }
References packet2_t::next, P2_DMA_TAG_CALL, packet2_chain_add_dma_tag(), and PACKET2_COUNT_QWC.
packet2_chain_close_tag()
static void packet2_chain_close_tag (packet2_t * packet2) inline static
Close dma tag. In reality, get back to pointer "tag_opened_at" and fix qwc value.
Parameters
packet2 Pointer to packet.
Definition at line 100 of file packet2_chain.h.
     {
         assert(packet2->tag_opened_at != NULL);  // There is opened tag.
         assert(((u32)packet2->next & 0xF) == 0); // Free space in packet is aligned properly.
         packet2->tag_opened_at->QWC = (((u32)packet2->next - (u32)packet2->tag_opened_at) / 16 - 1);
         packet2->tag_opened_at = (dma_tag_t *)NULL;
     }
References packet2_t::next, NULL, dma_tag_t::QWC, and packet2_t::tag_opened_at.
Referenced by packet2_utils_vu_add_continue_program(), packet2_utils_vu_add_double_buffer(), packet2_utils_vu_add_end_tag(), packet2_utils_vu_add_start_program(), and packet2_utils_vu_close_unpack().
packet2_chain_next()
static void packet2_chain_next (packet2_t * packet2, const dma_tag_t * next_tag, u8 irq, u8 spr, u32 pce) inline static
Add NEXT tag.
Note
packet2_chain_close_tag() required. Qwords are counted automatically. For more details, check description of dma_tag_t.
Parameters
next_tag Pointer to next tag.
irq Interrupt Request. False by default.
spr Memory/SPR Selection. False by default.
pce Priority Control Enable. 0 by default.
Definition at line 170 of file packet2_chain.h.
     {
         assert(((u32)packet2->next & 0xF) == 0); // Free space in packet is aligned properly.
         packet2_chain_add_dma_tag(packet2, PACKET2_COUNT_QWC, pce, P2_DMA_TAG_NEXT, irq, (u128 *)next_tag, spr);
     }
References packet2_t::next, P2_DMA_TAG_NEXT, packet2_chain_add_dma_tag(), and PACKET2_COUNT_QWC.
packet2_chain_open_cnt()
static void packet2_chain_open_cnt (packet2_t * packet2, u8 irq, u32 pce, u8 spr) inline static
Add CNT tag.
Note
packet2_chain_close_tag() required. Qwords are counted automatically. For more details, check description of dma_tag_t.
Parameters
packet2 Pointer to packet.
irq Interrupt Request. False by default.
pce Priority Control Enable. 0 by default.
spr Memory/SPR Selection. False by default.
Definition at line 122 of file packet2_chain.h.
     {
         packet2_chain_add_dma_tag(packet2, PACKET2_COUNT_QWC, pce, P2_DMA_TAG_CNT, irq, 0, spr);
     }
References P2_DMA_TAG_CNT, packet2_chain_add_dma_tag(), and PACKET2_COUNT_QWC.
Referenced by packet2_utils_vu_add_continue_program(), packet2_utils_vu_add_double_buffer(), packet2_utils_vu_add_start_program(), and packet2_utils_vu_open_unpack().
packet2_chain_open_end()
static void packet2_chain_open_end (packet2_t * packet2, u8 irq, u32 pce) inline static
Add END tag.
Note
packet2_chain_close_tag() required. Qwords are counted automatically. For more details, check description of dma_tag_t.
Don't forget about close_tag()!
Parameters
packet2 Pointer to packet.
irq Interrupt Request. False by default.
pce Priority Control Enable. 0 by default.
Definition at line 137 of file packet2_chain.h.
     {
         packet2_chain_add_dma_tag(packet2, PACKET2_COUNT_QWC, pce, P2_DMA_TAG_END, irq, 0, 0);
     }
References P2_DMA_TAG_END, packet2_chain_add_dma_tag(), and PACKET2_COUNT_QWC.
Referenced by packet2_utils_vu_add_end_tag().
packet2_chain_ref()
static void packet2_chain_ref (packet2_t * packet2, const void * ref_data, u32 qw_length, u8 irq, u8 spr, u32 pce) inline static
Add REF tag.
Note
Qwords are NOT counted automatically, so there is NO need to use packet2_chain_close_tag(); For more details, check description of dma_tag_t.
Parameters
packet2 Pointer to packet.
ref_data Pointer to data.
qw_length Size of data in qwords.
irq Interrupt Request. False by default.
spr Memory/SPR Selection. False by default.
pce Priority Control Enable. 0 by default.
Definition at line 154 of file packet2_chain.h.
     {
         assert(((u32)packet2->next & 0xF) == 0); // Free space in packet is aligned properly.
         packet2_chain_add_dma_tag(packet2, qw_length, pce, P2_DMA_TAG_REF, irq, (const u128 *)ref_data, spr);
     }
References packet2_t::next, P2_DMA_TAG_REF, and packet2_chain_add_dma_tag().
Referenced by packet2_utils_vu_add_unpack_data(), and packet2_vif_add_micro_program().
packet2_chain_refe()
static void packet2_chain_refe (packet2_t * packet2, const void * ref_data, u32 qw_length, u8 irq, u8 spr, u32 pce) inline static
Add REFE tag.
Note
Qwords are NOT counted automatically, so there is NO need to use packet2_chain_close_tag(); For more details, check description of dma_tag_t.
Parameters
packet2 Pointer to packet.
ref_data Pointer to data.
qw_length Size of data in qwords.
irq Interrupt Request. False by default.
spr Memory/SPR Selection. False by default.
pce Priority Control Enable. 0 by default.
Definition at line 206 of file packet2_chain.h.
     {
         assert(((u32)packet2->next & 0xF) == 0); // Free space in packet is aligned properly.
         packet2_chain_add_dma_tag(packet2, qw_length, pce, P2_DMA_TAG_REFE, irq, (const u128 *)ref_data, spr);
     }
References packet2_t::next, P2_DMA_TAG_REFE, and packet2_chain_add_dma_tag().
packet2_chain_refs()
static void packet2_chain_refs (packet2_t * packet2, const void * ref_data, u32 qw_length, u8 irq, u8 spr, u32 pce) inline static
Add REFS tag.
Note
Qwords are NOT counted automatically, so there is NO need to use packet2_chain_close_tag(); For more details, check description of dma_tag_t.
Parameters
packet2 Pointer to packet.
ref_data Pointer to data.
qw_length Size of data in qwords.
irq Interrupt Request. False by default.
spr Memory/SPR Selection. False by default.
pce Priority Control Enable. 0 by default.
Definition at line 188 of file packet2_chain.h.
     {
         assert(((u32)packet2->next & 0xF) == 0); // Free space in packet is aligned properly.
         packet2_chain_add_dma_tag(packet2, qw_length, pce, P2_DMA_TAG_REFS, irq, (const u128 *)ref_data, spr);
     }
References packet2_t::next, P2_DMA_TAG_REFS, and packet2_chain_add_dma_tag().
packet2_chain_ret()
static void packet2_chain_ret (packet2_t * packet2, u8 irq, u32 pce) inline static
Add RET tag.
Note
packet2_chain_close_tag() required. Qwords are counted automatically. For more details, check description of dma_tag_t.
Parameters
packet2 Pointer to packet.
irq Interrupt Request. False by default.
pce Priority Control Enable. 0 by default.
Definition at line 238 of file packet2_chain.h.
     {
         packet2_chain_add_dma_tag(packet2, PACKET2_COUNT_QWC, pce, P2_DMA_TAG_RET, irq, 0, 0);
     }
References P2_DMA_TAG_RET, packet2_chain_add_dma_tag(), and PACKET2_COUNT_QWC.
packet2_chain_set_dma_tag()
static void packet2_chain_set_dma_tag (dma_tag_t * tag, u32 qwc, u32 pce, u32 id, u8 irq, const u128 * addr, u8 spr) inline static
Set dma tag. For more details, check description of dma_tag_t.
Parameters
tag Pointer to DMA tag to set.
qwc Qword count.
pce Priority Control Enable. 0 by default.
id Tag ID.
irq Interrupt Request. False by default.
addr Address.
spr Memory/SPR Selection. False by default.
Definition at line 48 of file packet2_chain.h.
     {
         tag->QWC = qwc;
         tag->PCE = pce;
         tag->ID = id;
         tag->IRQ = irq;
         tag->ADDR = (u64)((u32)addr);
         tag->SPR = spr;
     }
References dma_tag_t::ADDR, dma_tag_t::ID, dma_tag_t::IRQ, dma_tag_t::PCE, dma_tag_t::QWC, and dma_tag_t::SPR.
Referenced by packet2_chain_add_dma_tag().