ps2sdk: ee/erl/include/hashtab.h File Reference
hashtab.h File Reference
#include "standard.h"
Data Structures
struct hitem
struct htab
Macros
#define hcount(t) ((t)->count)
#define hkey(t) ((t)->ipos->key)
#define hkeyl(t) ((t)->ipos->keyl)
#define hstuff(t) ((t)->ipos->stuff)
#define hnext(t)
Functions
htab * hcreate ()
void hdestroy ()
word hfind ()
word hadd ()
word hdel ()
word hfirst ()
word hnbucket ()
void hstat ()
Macro Definition Documentation
hcount
#define hcount (t) ((t)->count)
Definition at line 108 of file hashtab.h.
hkey
#define hkey (t) ((t)->ipos->key)
Definition at line 109 of file hashtab.h.
hkeyl
#define hkeyl (t) ((t)->ipos->keyl)
Definition at line 110 of file hashtab.h.
hnext
#define hnext (t)
Value:
  ((!(t)->ipos) ? FALSE :  \
   ((t)->ipos=(t)->ipos->next) ? TRUE : hnbucket(t))
Definition at line 184 of file hashtab.h.
hstuff
#define hstuff (t) ((t)->ipos->stuff)
Definition at line 111 of file hashtab.h.
Function Documentation
hadd()
word hadd ()
Referenced by add_loosy(), and add_symbol().
hcreate()
htab* hcreate ()
Referenced by add_loosy(), add_symbol(), and allocate_erl_record().
hdel()
word hdel ()
Referenced by erl_flush_symbols(), and fix_loosy().
hdestroy()
void hdestroy ()
Referenced by erl_flush_symbols().
hfind()
word hfind ()
Referenced by erl_find_local_symbol(), erl_find_symbol(), fix_loosy(), and r_find_symbol().
hfirst()
word hfirst ()
Referenced by erl_flush_symbols().
hnbucket()
word hnbucket ()
hstat()
void hstat ()