ps2sdk: ee/debug/samples/helloworld/helloworld.c File Reference
helloworld.c File Reference
#include <stdio.h>
#include <tamtypes.h>
#include <sifrpc.h>
#include <debug.h>
#include <unistd.h>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 17 of file helloworld.c.
 {
   SifInitRpc(0);
   init_scr();
   scr_printf("Hello, World!\n");
   // After 5 seconds, clear the screen.
   sleep(5);
   scr_clear();
   // Move cursor to 20, 20
   scr_setXY(20, 20);
   scr_printf("Hello Again, World!\n");
   sleep(10);
   return 0;
 }
References init_scr(), scr_clear(), scr_printf(), scr_setXY(), SifInitRpc(), and sleep().