ps2sdk: ee/kernel/include/iopheap.h File Reference
iopheap.h File Reference
Functions
int SifInitIopHeap (void)
void SifExitIopHeap (void)
void * SifAllocIopHeap (int size)
int SifFreeIopHeap (void *addr)
int SifLoadIopHeap (const char *path, void *addr)
Detailed Description
IOP heap handling prototypes
Definition in file iopheap.h.
Function Documentation
SifAllocIopHeap()
void* SifAllocIopHeap (int size)
Referenced by audsrv_load_adpcm(), sbv_patch_enable_lmb(), sbv_patch_fileio(), and sndLoadSample().
SifExitIopHeap()
void SifExitIopHeap (void)
SifFreeIopHeap()
int SifFreeIopHeap (void * addr)
Referenced by audsrv_load_adpcm(), and sndLoadSample().
SifInitIopHeap()
int SifInitIopHeap (void)
Referenced by audsrv_init(), main(), sbv_patch_enable_lmb(), and sbv_patch_fileio().
SifLoadIopHeap()
int SifLoadIopHeap (const char * path, void * addr)