ps2sdk: ee/kernel/src/srcfile/src/internal.h File Reference
internal.h File Reference
Functions
void Intc12Handler (void)
void InvokeUserModeCallback (void *dispatcher, void *callback, int id, u32 target, void *common)
void ResumeIntrDispatch (void)
Function Documentation
Intc12Handler()
void Intc12Handler (void)
Definition at line 167 of file alarm.c.
 {
         struct alarm alarm;
         void *gp;
         int i;
         for(i = 0; i < AlarmCount; i++)
         {       //Attempt to find another alarm request that has a different target. Update TIM3's comparator.
                 if(alarms[i].target != alarms[0].target)
                 {
                         SetupTIM3(alarms[i].target);
                         break;
                 }
         }
         do{
                 alarm = alarms[0];
                 AlarmCount--;
                 for(i = 0; i < AlarmCount; i++)
                         alarms[i] = alarms[i+1];
                 gp = ChangeGP(alarm.gp);
                 AlarmStatus &= ~(1 << alarm.id);
                 InvokeUserModeCallback((void*)USER_MODE_DISPATCHER, alarm.callback, alarm.id, alarm.target, alarm.common);
                 SetGP(gp);
                 if(AlarmCount <= 0)
                         break;
         }while(alarms[0].target == alarm.target);
         if(AlarmCount <= 0)     //If there are no further alarms, disable CMPE.
                 *T3_MODE_W = Tn_MODE(3,0,0,0,0,1,0,0,1,0);
         else
                 SetupTIM3(alarms[0].target);
         ExitHandler();
 }
References AlarmCount, alarms, AlarmStatus, alarm::callback, ChangeGP(), alarm::common, ExitHandler, gp, alarm::gp, alarm::id, InvokeUserModeCallback(), SetGP(), SetupTIM3(), T3_MODE_W, alarm::target, Tn_MODE, and USER_MODE_DISPATCHER.
InvokeUserModeCallback()
void InvokeUserModeCallback (void * dispatcher, void * callback, int id, u32 target, void * common)
Referenced by Intc12Handler().
ResumeIntrDispatch()
void ResumeIntrDispatch (void)