ps2sdk: ee/kernel/include/kernel.h File Reference
kernel.h File Reference
#include <stddef.h>
#include <stdarg.h>
#include <sifdma.h>
Data Structures
struct ee_sema_t
struct ee_thread_t
struct ee_thread_status_t
Macros
#define DI DIntr
#define EI EIntr
#define ExitHandler() asm volatile("sync\nei\n")
#define EE_SYNC() __asm__ volatile ("sync")
#define EE_SYNCL() __asm__ volatile ("sync.l")
#define EE_SYNCP() __asm__ volatile ("sync.p")
#define UNCACHED_SEG(x) ((void *)(((u32)(x)) | 0x20000000))
#define IS_UNCACHED_SEG(x) (((u32)(x)) & 0x20000000)
#define UCAB_SEG(x) ((void *)(((u32)(x)) | 0x30000000))
#define PUSHDATA(t, x, v, l) *(t *)(x) = (v); (l) = sizeof(t)
#define POPDATA(t, x, v, l) (v) = *(t *)(x); (l) = sizeof(t)
#define ALIGNED(x) __attribute__((aligned((x))))
#define SetModuleGP() ChangeGP(&_gp)
#define TH_SELF 0
#define MAX_THREADS 256
#define MAX_SEMAPHORES 256
#define MAX_PRIORITY 128
#define MAX_HANDLERS 128
#define MAX_ALARMS 64
#define WRITEBACK_DCACHE 0
#define INVALIDATE_DCACHE 1
#define INVALIDATE_ICACHE 2
#define INVALIDATE_CACHE 3
#define kINTC_GS INTC_GS
#define kINTC_SBUS INTC_SBUS
#define kINTC_VBLANK_START INTC_VBLANK_S
#define kINTC_VBLANK_END INTC_VBLANK_E
#define kINTC_VIF0 INTC_VIF0
#define kINTC_VIF1 INTC_VIF1
#define kINTC_VU0 INTC_VU0
#define kINTC_VU1 INTC_VU1
#define kINTC_IPU INTC_IPU
#define kINTC_TIMER0 INTC_TIM0
#define kINTC_TIMER1 INTC_TIM1
#define INIT_DMAC 0x01
#define INIT_VU1 0x02
#define INIT_VIF1 0x04
#define INIT_GIF 0x08
#define INIT_VU0 0x10
#define INIT_VIF0 0x20
#define INIT_IPU 0x40
#define THS_RUN 0x01
#define THS_READY 0x02
#define THS_WAIT 0x04
#define THS_SUSPEND 0x08
#define THS_WAITSUSPEND 0x0c
#define THS_DORMANT 0x10
#define TSW_NONE 0
#define TSW_SLEEP 1
#define TSW_SEMA 2
#define CPU_DATA_CACHE 1
#define CPU_INSTRUCTION_CACHE 2
Enumerations
enum {
INTC_GS ,
INTC_SBUS ,
INTC_VBLANK_S ,
INTC_VBLANK_E ,
INTC_VIF0 ,
INTC_VIF1 ,
INTC_VU0 ,
INTC_VU1 ,
INTC_IPU ,
INTC_TIM0 ,
INTC_TIM1 ,
INTC_TIM2 ,
INTC_SFIFO = 13 ,
INTC_VU0WD
}
enum {
DMAC_VIF0 ,
DMAC_VIF1 ,
DMAC_GIF ,
DMAC_FROM_IPU ,
DMAC_TO_IPU ,
DMAC_SIF0 ,
DMAC_SIF1 ,
DMAC_SIF2 ,
DMAC_FROM_SPR ,
DMAC_TO_SPR ,
DMAC_CIS = 13 ,
DMAC_MEIS ,
DMAC_BEIS
}
enum CPU_CONFIG {
CPU_CONFIG_ENABLE_DIE = 0 ,
CPU_CONFIG_ENABLE_ICE ,
CPU_CONFIG_ENABLE_DCE ,
CPU_CONFIG_DISBLE_DIE ,
CPU_CONFIG_DISBLE_ICE ,
CPU_CONFIG_DISBLE_DCE
}
Functions
void * ChangeGP (void *gp)
void SetGP (void *gp)
void * GetGP (void)
static void nopdelay (void)
static int ee_get_opmode (void)
static int ee_set_opmode (u32 opmode)
static int ee_kmode_enter ()
static int ee_kmode_exit ()
void _InitSys (void)
void TerminateLibrary (void)
int InitThread (void)
s32 iWakeupThread (s32 thread_id)
s32 iRotateThreadReadyQueue (s32 priority)
s32 iSuspendThread (s32 thread_id)
void InitTLBFunctions (void)
void InitTLB (void)
void Exit (s32 exit_code)
s32 ExecPS2 (void *entry, void *gp, int num_args, char *args[])
void LoadExecPS2 (const char *filename, s32 num_args, char *args[])
void ExecOSD (int num_args, char *args[])
void InitAlarm (void)
void InitExecPS2 (void)
void InitOsd (void)
int PatchIsNeeded (void)
int DIntr (void)
int EIntr (void)
int EnableIntc (int intc)
int DisableIntc (int intc)
int EnableDmac (int dmac)
int DisableDmac (int dmac)
int iEnableIntc (int intc)
int iDisableIntc (int intc)
int iEnableDmac (int dmac)
int iDisableDmac (int dmac)
void SyncDCache (void *start, void *end)
void iSyncDCache (void *start, void *end)
void InvalidDCache (void *start, void *end)
void iInvalidDCache (void *start, void *end)
void ResetEE (u32 init_bitfield)
void SetGsCrt (s16 interlace, s16 pal_ntsc, s16 field)
void _Exit (s32 exit_code)
void _LoadExecPS2 (const char *filename, s32 num_args, char *args[])
s32 _ExecPS2 (void *entry, void *gp, int num_args, char *args[])
void RFU009 (u32 arg0, u32 arg1)
s32 AddSbusIntcHandler (s32 cause, void(*handler)(int call))
s32 RemoveSbusIntcHandler (s32 cause)
s32 Interrupt2Iop (s32 cause)
void SetVTLBRefillHandler (s32 handler_num, void *handler_func)
void SetVCommonHandler (s32 handler_num, void *handler_func)
void SetVInterruptHandler (s32 handler_num, void *handler_func)
s32 AddIntcHandler (s32 cause, s32(*handler_func)(s32 cause), s32 next)
s32 AddIntcHandler2 (s32 cause, s32(*handler_func)(s32 cause, void *arg, void *addr), s32 next, void *arg)
s32 RemoveIntcHandler (s32 cause, s32 handler_id)
s32 AddDmacHandler (s32 channel, s32(*handler)(s32 channel), s32 next)
s32 AddDmacHandler2 (s32 channel, s32(*handler)(s32 channel, void *arg, void *addr), s32 next, void *arg)
s32 RemoveDmacHandler (s32 channel, s32 handler_id)
s32 _EnableIntc (s32 cause)
s32 _DisableIntc (s32 cause)
s32 _EnableDmac (s32 channel)
s32 _DisableDmac (s32 channel)
s32 SetAlarm (u16 time, void(*callback)(s32 alarm_id, u16 time, void *common), void *common)
s32 _SetAlarm (u16 time, void(*callback)(s32 alarm_id, u16 time, void *common), void *common)
s32 ReleaseAlarm (s32 alarm_id)
s32 _ReleaseAlarm (s32 alarm_id)
s32 _iEnableIntc (s32 cause)
s32 _iDisableIntc (s32 cause)
s32 _iEnableDmac (s32 channel)
s32 _iDisableDmac (s32 channel)
s32 iSetAlarm (u16 time, void(*callback)(s32 alarm_id, u16 time, void *common), void *common)
s32 _iSetAlarm (u16 time, void(*callback)(s32 alarm_id, u16 time, void *common), void *common)
s32 iReleaseAlarm (s32 alarm_id)
s32 _iReleaseAlarm (s32 alarm_id)
s32 CreateThread (ee_thread_t *thread)
s32 DeleteThread (s32 thread_id)
s32 StartThread (s32 thread_id, void *args)
void ExitThread (void)
void ExitDeleteThread (void)
s32 TerminateThread (s32 thread_id)
s32 iTerminateThread (s32 thread_id)
s32 ChangeThreadPriority (s32 thread_id, s32 priority)
s32 iChangeThreadPriority (s32 thread_id, s32 priority)
s32 RotateThreadReadyQueue (s32 priority)
s32 _iRotateThreadReadyQueue (s32 priority)
s32 ReleaseWaitThread (s32 thread_id)
s32 iReleaseWaitThread (s32 thread_id)
s32 GetThreadId (void)
s32 _iGetThreadId (void)
s32 ReferThreadStatus (s32 thread_id, ee_thread_status_t *info)
s32 iReferThreadStatus (s32 thread_id, ee_thread_status_t *info)
s32 SleepThread (void)
s32 WakeupThread (s32 thread_id)
s32 _iWakeupThread (s32 thread_id)
s32 CancelWakeupThread (s32 thread_id)
s32 iCancelWakeupThread (s32 thread_id)
s32 SuspendThread (s32 thread_id)
s32 _iSuspendThread (s32 thread_id)
s32 ResumeThread (s32 thread_id)
s32 iResumeThread (s32 thread_id)
u8 RFU059 (void)
void * SetupThread (void *gp, void *stack, s32 stack_size, void *args, void *root_func)
void SetupHeap (void *heap_start, s32 heap_size)
void * EndOfHeap (void)
s32 CreateSema (ee_sema_t *sema)
s32 DeleteSema (s32 sema_id)
s32 SignalSema (s32 sema_id)
s32 iSignalSema (s32 sema_id)
s32 WaitSema (s32 sema_id)
s32 PollSema (s32 sema_id)
s32 iPollSema (s32 sema_id)
s32 ReferSemaStatus (s32 sema_id, ee_sema_t *sema)
s32 iReferSemaStatus (s32 sema_id, ee_sema_t *sema)
s32 iDeleteSema (s32 sema_id)
void SetOsdConfigParam (void *addr)
void GetOsdConfigParam (void *addr)
void GetGsHParam (void *addr1, void *addr2, void *addr3)
s32 GetGsVParam (void)
void SetGsHParam (void *addr1, void *addr2, void *addr3, void *addr4)
void SetGsVParam (s32 arg1)
int PutTLBEntry (unsigned int PageMask, unsigned int EntryHi, unsigned int EntryLo0, unsigned int EntryLo1)
int iPutTLBEntry (unsigned int PageMask, unsigned int EntryHi, unsigned int EntryLo0, unsigned int EntryLo1)
int _SetTLBEntry (unsigned int index, unsigned int PageMask, unsigned int EntryHi, unsigned int EntryLo0, unsigned int EntryLo1)
int iSetTLBEntry (unsigned int index, unsigned int PageMask, unsigned int EntryHi, unsigned int EntryLo0, unsigned int EntryLo1)
int GetTLBEntry (unsigned int index, unsigned int *PageMask, unsigned int *EntryHi, unsigned int *EntryLo0, unsigned int *EntryLo1)
int iGetTLBEntry (unsigned int index, unsigned int *PageMask, unsigned int *EntryHi, unsigned int *EntryLo0, unsigned int *EntryLo1)
int ProbeTLBEntry (unsigned int EntryHi, unsigned int *PageMask, unsigned int *EntryLo0, unsigned int *EntryLo1)
int iProbeTLBEntry (unsigned int EntryHi, unsigned int *PageMask, unsigned int *EntryLo0, unsigned int *EntryLo1)
int ExpandScratchPad (unsigned int page)
void EnableIntcHandler (u32 cause)
void iEnableIntcHandler (u32 cause)
void DisableIntcHandler (u32 cause)
void iDisableIntcHandler (u32 cause)
void EnableDmacHandler (u32 channel)
void iEnableDmacHandler (u32 channel)
void DisableDmacHandler (u32 channel)
void iDisableDmacHandler (u32 channel)
void KSeg0 (s32 arg1)
s32 EnableCache (s32 cache)
s32 DisableCache (s32 cache)
u32 GetCop0 (s32 reg_id)
void FlushCache (s32 operation)
u32 CpuConfig (u32 config)
u32 iGetCop0 (s32 reg_id)
void iFlushCache (s32 operation)
u32 iCpuConfig (u32 config)
void SetCPUTimerHandler (void(*handler)(void))
void SetCPUTimer (s32 compval)
void SetOsdConfigParam2 (void *config, s32 size, s32 offset)
void GetOsdConfigParam2 (void *config, s32 size, s32 offset)
u64 GsGetIMR (void)
u64 iGsGetIMR (void)
u64 GsPutIMR (u64 imr)
u64 iGsPutIMR (u64 imr)
void SetPgifHandler (void *handler)
void SetVSyncFlag (u32 *, u64 *)
void SetSyscall (s32 syscall_num, void *handler)
void SifStopDma (void)
s32 SifDmaStat (u32 id)
s32 iSifDmaStat (u32 id)
u32 SifSetDma (SifDmaTransfer_t *sdd, s32 len)
u32 iSifSetDma (SifDmaTransfer_t *sdd, s32 len)
void SifSetDChain (void)
void iSifSetDChain (void)
int SifSetReg (u32 register_num, int register_value)
int SifGetReg (u32 register_num)
void _ExecOSD (int num_args, char *args[])
s32 Deci2Call (s32, u32 *)
void PSMode (void)
s32 MachineType (void)
s32 GetMemorySize (void)
void _GetGsDxDyOffset (int mode, int *dx, int *dy, int *dw, int *dh)
int _InitTLB (void)
int SetMemoryMode (int mode)
void _SyncDCache (void *start, void *end)
void _InvalidDCache (void *start, void *end)
void abort (void)
void exit (int retval)
void _exit (int retval)
int * __errno (void)
void * GetSyscallHandler (int syscall_no)
void * GetExceptionHandler (int except_no)
void * GetInterruptHandler (int intr_no)
int kCopy (void *dest, const void *src, int size)
int kCopyBytes (void *dest, const void *src, int size)
int Copy (void *dest, const void *src, int size)
void setup (int syscall_num, void *handler)
void * GetEntryAddress (int syscall)
Variables
void * _gp
int errno
Detailed Description
EE Kernel prototypes
Definition in file kernel.h.
Macro Definition Documentation
ALIGNED
#define ALIGNED (x) __attribute__((aligned((x))))
Definition at line 50 of file kernel.h.
CPU_DATA_CACHE
#define CPU_DATA_CACHE 1
EnableCache & DisableCache options (multiple options may be specified)
Definition at line 279 of file kernel.h.
CPU_INSTRUCTION_CACHE
#define CPU_INSTRUCTION_CACHE 2
Definition at line 280 of file kernel.h.
DI
#define DI DIntr
Definition at line 24 of file kernel.h.
EE_SYNC
#define EE_SYNC () __asm__ volatile ("sync")
Definition at line 31 of file kernel.h.
EE_SYNCL
#define EE_SYNCL () __asm__ volatile ("sync.l")
Definition at line 32 of file kernel.h.
EE_SYNCP
#define EE_SYNCP () __asm__ volatile ("sync.p")
Definition at line 33 of file kernel.h.
EI
#define EI EIntr
Definition at line 25 of file kernel.h.
ExitHandler
#define ExitHandler () asm volatile("sync\nei\n")
Definition at line 28 of file kernel.h.
INIT_DMAC
#define INIT_DMAC 0x01
ResetEE argument bits
Definition at line 133 of file kernel.h.
INIT_GIF
#define INIT_GIF 0x08
Definition at line 136 of file kernel.h.
INIT_IPU
#define INIT_IPU 0x40
Definition at line 139 of file kernel.h.
INIT_VIF0
#define INIT_VIF0 0x20
Definition at line 138 of file kernel.h.
INIT_VIF1
#define INIT_VIF1 0x04
Definition at line 135 of file kernel.h.
INIT_VU0
#define INIT_VU0 0x10
Definition at line 137 of file kernel.h.
INIT_VU1
#define INIT_VU1 0x02
Definition at line 134 of file kernel.h.
INVALIDATE_CACHE
#define INVALIDATE_CACHE 3
Definition at line 78 of file kernel.h.
INVALIDATE_DCACHE
#define INVALIDATE_DCACHE 1
Definition at line 76 of file kernel.h.
INVALIDATE_ICACHE
#define INVALIDATE_ICACHE 2
Definition at line 77 of file kernel.h.
IS_UNCACHED_SEG
#define IS_UNCACHED_SEG (x) (((u32)(x)) & 0x20000000)
Definition at line 38 of file kernel.h.
kINTC_GS
#define kINTC_GS INTC_GS
Definition at line 101 of file kernel.h.
kINTC_IPU
#define kINTC_IPU INTC_IPU
Definition at line 109 of file kernel.h.
kINTC_SBUS
#define kINTC_SBUS INTC_SBUS
Definition at line 102 of file kernel.h.
kINTC_TIMER0
#define kINTC_TIMER0 INTC_TIM0
Definition at line 110 of file kernel.h.
kINTC_TIMER1
#define kINTC_TIMER1 INTC_TIM1
Definition at line 111 of file kernel.h.
kINTC_VBLANK_END
#define kINTC_VBLANK_END INTC_VBLANK_E
Definition at line 104 of file kernel.h.
kINTC_VBLANK_START
#define kINTC_VBLANK_START INTC_VBLANK_S
Definition at line 103 of file kernel.h.
kINTC_VIF0
#define kINTC_VIF0 INTC_VIF0
Definition at line 105 of file kernel.h.
kINTC_VIF1
#define kINTC_VIF1 INTC_VIF1
Definition at line 106 of file kernel.h.
kINTC_VU0
#define kINTC_VU0 INTC_VU0
Definition at line 107 of file kernel.h.
kINTC_VU1
#define kINTC_VU1 INTC_VU1
Definition at line 108 of file kernel.h.
MAX_ALARMS
#define MAX_ALARMS 64
Definition at line 72 of file kernel.h.
MAX_HANDLERS
#define MAX_HANDLERS 128
Definition at line 71 of file kernel.h.
MAX_PRIORITY
#define MAX_PRIORITY 128
Definition at line 70 of file kernel.h.
MAX_SEMAPHORES
#define MAX_SEMAPHORES 256
Definition at line 69 of file kernel.h.
MAX_THREADS
#define MAX_THREADS 256
Limits
Definition at line 68 of file kernel.h.
POPDATA
#define POPDATA (t, x, v, l) (v) = *(t *)(x); (l) = sizeof(t)
Definition at line 47 of file kernel.h.
PUSHDATA
#define PUSHDATA (t, x, v, l) *(t *)(x) = (v); (l) = sizeof(t)
Definition at line 44 of file kernel.h.
SetModuleGP
#define SetModuleGP () ChangeGP(&_gp)
Definition at line 58 of file kernel.h.
TH_SELF
#define TH_SELF 0
Special thread ID for referring to the running thread. Unlike the IOP kernel, this is only supported by ReferThreadStatus() and ChangeThreadPriority(). It can also be used by the iWakeupThread() syscall. But because the libkernel patch may call WakeupThread() to avoid the defect within iWakeupThread() that prevents the running thread from being woken up, THS_SELF should not be used with iWakeupThread().
Definition at line 65 of file kernel.h.
THS_DORMANT
#define THS_DORMANT 0x10
Definition at line 244 of file kernel.h.
THS_READY
#define THS_READY 0x02
Definition at line 240 of file kernel.h.
THS_RUN
#define THS_RUN 0x01
Thread status
Definition at line 239 of file kernel.h.
THS_SUSPEND
#define THS_SUSPEND 0x08
Definition at line 242 of file kernel.h.
THS_WAIT
#define THS_WAIT 0x04
Definition at line 241 of file kernel.h.
THS_WAITSUSPEND
#define THS_WAITSUSPEND 0x0c
Definition at line 243 of file kernel.h.
TSW_NONE
#define TSW_NONE 0
Thread WAIT Status
Definition at line 247 of file kernel.h.
TSW_SEMA
#define TSW_SEMA 2
Definition at line 249 of file kernel.h.
TSW_SLEEP
#define TSW_SLEEP 1
Definition at line 248 of file kernel.h.
UCAB_SEG
#define UCAB_SEG (x) ((void *)(((u32)(x)) | 0x30000000))
Definition at line 41 of file kernel.h.
UNCACHED_SEG
#define UNCACHED_SEG (x) ((void *)(((u32)(x)) | 0x20000000))
Definition at line 35 of file kernel.h.
WRITEBACK_DCACHE
#define WRITEBACK_DCACHE 0
Modes for FlushCache
Definition at line 75 of file kernel.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
EE Interrupt Controller (INTC) interrupt numbers
Enumerator
INTC_GS
INTC_SBUS
INTC_VBLANK_S
INTC_VBLANK_E
INTC_VIF0
INTC_VIF1
INTC_VU0
INTC_VU1
INTC_IPU
INTC_TIM0
INTC_TIM1
INTC_TIM2
INTC_SFIFO
INTC_VU0WD
Definition at line 81 of file kernel.h.
 {
         INTC_GS,
         INTC_SBUS,
         INTC_VBLANK_S,
         INTC_VBLANK_E,
         INTC_VIF0,
         INTC_VIF1,
         INTC_VU0,
         INTC_VU1,
         INTC_IPU,
         INTC_TIM0,
         INTC_TIM1,
         INTC_TIM2,
 //      INTC_TIM3,              //Reserved by the EE kernel for alarms (do not use)
         INTC_SFIFO = 13,        //Error encountered during SFIFO transfer
         INTC_VU0WD              //VU0 WatchDog; ForceBreak is sent to VU0 if left in RUN state for extended periods of time.
 };
anonymous enum
anonymous enum
EE Direct Memory Access Controller (DMAC) interrupt numbers
Enumerator
DMAC_VIF0
DMAC_VIF1
DMAC_GIF
DMAC_FROM_IPU
DMAC_TO_IPU
DMAC_SIF0
DMAC_SIF1
DMAC_SIF2
DMAC_FROM_SPR
DMAC_TO_SPR
DMAC_CIS
DMAC_MEIS
DMAC_BEIS
Definition at line 114 of file kernel.h.
 {
         DMAC_VIF0,
         DMAC_VIF1,
         DMAC_GIF,
         DMAC_FROM_IPU,
         DMAC_TO_IPU,
         DMAC_SIF0,
         DMAC_SIF1,
         DMAC_SIF2,
         DMAC_FROM_SPR,
         DMAC_TO_SPR,
         DMAC_CIS        = 13,   //Channel interrupt
         DMAC_MEIS,              //MemFIFO empty interrupt
         DMAC_BEIS,              //Bus error interrupt
 };
CPU_CONFIG
enum CPU_CONFIG
CpuConfig options
Enumerator
CPU_CONFIG_ENABLE_DIE
CPU_CONFIG_ENABLE_ICE
CPU_CONFIG_ENABLE_DCE
CPU_CONFIG_DISBLE_DIE
CPU_CONFIG_DISBLE_ICE
CPU_CONFIG_DISBLE_DCE
Definition at line 269 of file kernel.h.
                 {
         CPU_CONFIG_ENABLE_DIE   = 0,    //Enable Dual Issue
         CPU_CONFIG_ENABLE_ICE,          //Enable Instruction Cache
         CPU_CONFIG_ENABLE_DCE,          //Enable Data Cache
         CPU_CONFIG_DISBLE_DIE,          //Disable Dual Issue
         CPU_CONFIG_DISBLE_ICE,          //Disable Instruction Cache
         CPU_CONFIG_DISBLE_DCE           //Disable Data Cache
 };
Function Documentation
__errno()
int* __errno (void)
_DisableDmac()
s32 _DisableDmac (s32 channel)
_DisableIntc()
s32 _DisableIntc (s32 cause)
Referenced by main().
_EnableDmac()
s32 _EnableDmac (s32 channel)
_EnableIntc()
s32 _EnableIntc (s32 cause)
Referenced by main().
_ExecOSD()
void _ExecOSD (int num_args, char * args[])
_ExecPS2()
s32 _ExecPS2 (void * entry, void * gp, int num_args, char * args[])
_exit()
void _exit (int retval)
Referenced by abort(), and exit().
_Exit()
void _Exit (s32 exit_code)
_GetGsDxDyOffset()
void _GetGsDxDyOffset (int mode, int * dx, int * dy, int * dw, int * dh)
Referenced by GsSetDefaultDisplayEnv().
_iDisableDmac()
s32 _iDisableDmac (s32 channel)
_iDisableIntc()
s32 _iDisableIntc (s32 cause)
_iEnableDmac()
s32 _iEnableDmac (s32 channel)
_iEnableIntc()
s32 _iEnableIntc (s32 cause)
_iGetThreadId()
s32 _iGetThreadId (void)
_InitSys()
void _InitSys (void)
_InitTLB()
int _InitTLB (void)
_InvalidDCache()
void _InvalidDCache (void * start, void * end)
_iReleaseAlarm()
s32 _iReleaseAlarm (s32 alarm_id)
_iRotateThreadReadyQueue()
s32 _iRotateThreadReadyQueue (s32 priority)
_iSetAlarm()
s32 _iSetAlarm (u16 time, void(*)(s32 alarm_id, u16 time, void *common) callback, void * common)
_iSuspendThread()
s32 _iSuspendThread (s32 thread_id)
_iWakeupThread()
s32 _iWakeupThread (s32 thread_id)
_LoadExecPS2()
void _LoadExecPS2 (const char * filename, s32 num_args, char * args[])
_ReleaseAlarm()
s32 _ReleaseAlarm (s32 alarm_id)
_SetAlarm()
s32 _SetAlarm (u16 time, void(*)(s32 alarm_id, u16 time, void *common) callback, void * common)
_SetTLBEntry()
int _SetTLBEntry (unsigned int index, unsigned int PageMask, unsigned int EntryHi, unsigned int EntryLo0, unsigned int EntryLo1)
Referenced by InitTLB32MB().
_SyncDCache()
void _SyncDCache (void * start, void * end)
abort()
void abort (void)
Definition at line 16 of file terminate.c.
 {
         printf("Program aborted.\n");
         while (1)
                 _exit(1);
 }
References _exit().
AddDmacHandler()
s32 AddDmacHandler (s32 channel, s32(*)(s32 channel) handler, s32 next)
Referenced by dma_channel_initialize().
AddDmacHandler2()
s32 AddDmacHandler2 (s32 channel, s32(*)(s32 channel, void *arg, void *addr) handler, s32 next, void * arg)
AddIntcHandler()
s32 AddIntcHandler (s32 cause, s32(*)(s32 cause) handler_func, s32 next)
Referenced by graph_add_vsync_handler(), and main().
AddIntcHandler2()
s32 AddIntcHandler2 (s32 cause, s32(*)(s32 cause, void *arg, void *addr) handler_func, s32 next, void * arg)
AddSbusIntcHandler()
s32 AddSbusIntcHandler (s32 cause, void(*)(int call) handler)
CancelWakeupThread()
s32 CancelWakeupThread (s32 thread_id)
ChangeGP()
void* ChangeGP (void * gp)
Referenced by Intc12Handler().
ChangeThreadPriority()
s32 ChangeThreadPriority (s32 thread_id, s32 priority)
Referenced by poweroffChangeThreadPriority().
Copy()
int Copy (void * dest, const void * src, int size)
Referenced by InitAlarm(), InitExecPS2(), InitOsd(), and InitTLBFunctions().
CpuConfig()
u32 CpuConfig (u32 config)
CreateSema()
s32 CreateSema (ee_sema_t * sema)
Referenced by audsrv_init(), fileXioInit(), main(), nanosleep(), NetManInitRPCClient(), PS2CamInit(), ps2ip_init(), sys_init(), sys_mbox_new(), and sys_sem_new().
CreateThread()
s32 CreateThread (ee_thread_t * thread)
Referenced by audsrv_init(), NetManInitRPCClient(), NetManInitRPCServer(), poweroffInit(), SIOR_Init(), and sys_thread_new().
Deci2Call()
s32 Deci2Call (s32 , u32 *)
DeleteSema()
s32 DeleteSema (s32 sema_id)
Referenced by audsrv_quit(), deinitCleanup(), fileXioExit(), main(), nanosleep(), ps2ip_deinit(), sys_mbox_free(), and sys_sem_free().
DeleteThread()
s32 DeleteThread (s32 thread_id)
Referenced by audsrv_quit(), deinitCleanup(), NetManDeinitRPCServer(), poweroffInit(), and sys_thread_new().
DIntr()
int DIntr (void)
Referenced by ee_dbg_install(), ee_dbg_remove(), ee_dbg_set_level1_handler(), ee_dbg_set_level2_handler(), graph_add_vsync_handler(), graph_remove_vsync_handler(), and sys_arch_protect().
DisableCache()
s32 DisableCache (s32 cache)
DisableDmac()
int DisableDmac (int dmac)
Referenced by dma_channel_shutdown().
DisableDmacHandler()
void DisableDmacHandler (u32 channel)
DisableIntc()
int DisableIntc (int intc)
Referenced by graph_remove_vsync_handler().
DisableIntcHandler()
void DisableIntcHandler (u32 cause)
ee_get_opmode()
static int ee_get_opmode (void) inline static
Definition at line 150 of file kernel.h.
 {
         u32 status;
         __asm__ volatile (
                 ".set\tpush\n\t"                \
                 ".set\tnoreorder\n\t"           \
                 "mfc0\t%0, $12\n\t"             \
                 ".set\tpop\n\t" : "=r" (status));
         return((status >> 3) & 3);
 }
ee_kmode_enter()
static int ee_kmode_enter () inline static
Definition at line 181 of file kernel.h.
 {
         u32 status, mask;
         __asm__ volatile (
                 ".set\tpush\n\t"                \
                 ".set\tnoreorder\n\t"           \
                 "mfc0\t%0, $12\n\t"             \
                 "li\t%1, 0xffffffe7\n\t"        \
                 "and\t%0, %1\n\t"               \
                 "mtc0\t%0, $12\n\t"             \
                 "sync.p\n\t"
                 ".set\tpop\n\t" : "=r" (status), "=r" (mask));
         return status;
 }
Referenced by iop_readwrite(), PS2CamReadPacket(), sbv_patch_user_mem_clear(), sior_rpc_server(), smem_read(), and smem_write().
ee_kmode_exit()
static int ee_kmode_exit () inline static
Definition at line 198 of file kernel.h.
 {
         int status;
         __asm__ volatile (
                 ".set\tpush\n\t"                \
                 ".set\tnoreorder\n\t"           \
                 "mfc0\t%0, $12\n\t"             \
                 "ori\t%0, 0x10\n\t"             \
                 "mtc0\t%0, $12\n\t"             \
                 "sync.p\n\t" \
                 ".set\tpop\n\t" : "=r" (status));
         return status;
 }
Referenced by iop_readwrite(), PS2CamReadPacket(), sbv_patch_user_mem_clear(), sior_rpc_server(), smem_read(), and smem_write().
ee_set_opmode()
static int ee_set_opmode (u32 opmode) inline static
Definition at line 163 of file kernel.h.
 {
         u32 status, mask;
         __asm__ volatile (
                 ".set\tpush\n\t"                \
                 ".set\tnoreorder\n\t"           \
                 "mfc0\t%0, $12\n\t"             \
                 "li\t%1, 0xffffffe7\n\t"        \
                 "and\t%0, %1\n\t"               \
                 "or\t%0, %2\n\t"                \
                 "mtc0\t%0, $12\n\t"             \
                 "sync.p\n\t"
                 ".set\tpop\n\t" : "=r" (status), "=r" (mask) : "r" (opmode));
         return((status >> 3) & 3);
 }
Referenced by ee_dbg_install(), and ee_dbg_remove().
EIntr()
int EIntr (void)
Referenced by ee_dbg_install(), ee_dbg_remove(), ee_dbg_set_level1_handler(), ee_dbg_set_level2_handler(), graph_add_vsync_handler(), graph_remove_vsync_handler(), and sys_arch_unprotect().
EnableCache()
s32 EnableCache (s32 cache)
EnableDmac()
int EnableDmac (int dmac)
Referenced by dma_channel_initialize().
EnableDmacHandler()
void EnableDmacHandler (u32 channel)
EnableIntc()
int EnableIntc (int intc)
Referenced by graph_add_vsync_handler().
EnableIntcHandler()
void EnableIntcHandler (u32 cause)
EndOfHeap()
void* EndOfHeap (void)
Referenced by ps2_sbrk().
ExecOSD()
void ExecOSD (int num_args, char * args[])
ExecPS2()
s32 ExecPS2 (void * entry, void * gp, int num_args, char * args[])
Referenced by LoadELFFromFile(), and main().
exit()
void exit (int retval)
Definition at line 25 of file terminate.c.
 {
         while (1)
                 _exit(retval);
 }
References _exit().
Exit()
void Exit (s32 exit_code)
Referenced by InitTLB32MB().
ExitDeleteThread()
void ExitDeleteThread (void)
Referenced by _kill().
ExitThread()
void ExitThread (void)
ExpandScratchPad()
int ExpandScratchPad (unsigned int page)
Definition at line 163 of file tlbsrc.c.
{
         int result, index;
         unsigned int PageMask, EntryHi, EntryLo0, EntryLo1;
         if(!(page&0xFFF)){
                 if(0xFFFFE<page-1){
                         if((index=ProbeTLBEntry(0x70004000, &PageMask, &EntryLo0, &EntryLo1))>=0){
                                 if(page==0){
                                         EntryHi=0xE0010000+((index-1)<<13);
                                         __asm volatile( "mfc0 $v0, $6\n"
                                                         "addiu $v0, $v0, 0xFFFF\n"
                                                         "mtc0 $v0, $6\n"
                                                         "mtc0 %0, $0\n"
                                                         "mtc0 $zero, $5\n"
                                                         "mtc0 %1, $10\n"
                                                         "mtc0 $zero, $2\n"
                                                         "mtc0 $zero, $3\n"
                                                         "sync.p\n"
                                                         "tlbwi\n"
                                                         "sync.p\n" ::"r"(index),"r"(EntryHi));
                                 }
                                 else{
                                         __asm volatile( "mfc0 %0, $6\n"
                                                         "addiu $v0, %0, 1\n"
                                                         "mtc0 $v0, $6\n" ::"r"(index));
                                 }
                         }
                         if(page!=0){
                         /*      Not sure why this code saves the EntryLo0 and EntryLo1 values on the stack, and sets a word on the stack to zero, but does not use them:
                                 0($sp)=0
                                 4($sp)=$v0=(page+0x1000&0xFFFFF000)>>6|0x1F
                                 8($sp)=$a0=(page&0xFFFFF000)>>6|0x1F */
                                 EntryHi=0x70004000;
                                 EntryLo0=((page+0x1000)&0xFFFFF000)>>6|0x1F;
                                 EntryLo1=(page&0xFFFFF000)>>6|0x1F;
                                 __asm volatile( "mtc0 %0, $0\n"
                                                 "daddu $v1, $zero, $zero\n"
                                                 "mtc0 $v1, $5\n"
                                                 "mtc0 %1, $10\n"
                                                 "mtc0 %2, $2\n"
                                                 "mtc0 %3, $3\n"
                                                 "sync.p\n"
                                                 "tlbwi\n"
                                                 "sync.p\n" ::"r"(index),"r"(EntryHi),"r"(EntryLo0),"r"(EntryLo1));
                                 result=index;
                         }
                         else result=0;
                 }
                 else result=-1;
         }
         else result=-1;
         return result;
 }
References index, ProbeTLBEntry(), and result.
FlushCache()
void FlushCache (s32 operation)
Referenced by add_symbol(), dma_channel_send_packet2(), ee_dbg_install(), ee_dbg_remove(), InitAlarm(), InitExecPS2(), InitOsd(), InitTLBFunctions(), LoadELFFromFile(), main(), mcRename(), mcSetFileInfo(), mcWrite(), packet2_create(), ps2_screenshot(), read_erl(), and sndLoadSample().
GetCop0()
u32 GetCop0 (s32 reg_id)
GetEntryAddress()
void* GetEntryAddress (int syscall)
Referenced by InitAlarm(), InitExecPS2(), and InitOsd().
GetExceptionHandler()
void* GetExceptionHandler (int except_no)
Referenced by ee_dbg_install().
GetGP()
void* GetGP (void)
Referenced by SetAlarmInternal().
GetGsHParam()
void GetGsHParam (void * addr1, void * addr2, void * addr3)
GetGsVParam()
s32 GetGsVParam (void)
GetInterruptHandler()
void* GetInterruptHandler (int intr_no)
GetMemorySize()
s32 GetMemorySize (void)
Referenced by wipeUserMem().
GetOsdConfigParam()
void GetOsdConfigParam (void * addr)
Referenced by PatchIsNeeded().
GetOsdConfigParam2()
void GetOsdConfigParam2 (void * config, s32 size, s32 offset)
GetSyscallHandler()
void* GetSyscallHandler (int syscall_no)
GetThreadId()
s32 GetThreadId (void)
Referenced by _getpid(), rpc_server_thread(), sior_thread(), WaitSemaTimeout(), and WaitValidNetState().
GetTLBEntry()
int GetTLBEntry (unsigned int index, unsigned int * PageMask, unsigned int * EntryHi, unsigned int * EntryLo0, unsigned int * EntryLo1)
Definition at line 111 of file tlbsrc.c.
{
         int result;
         if(index<0x30){
                 __asm volatile( "mtc0 %0, $0\n"
                                 "sync.p\n"
                                 "tlbr\n"
                                 "sync.p\n"
                                 "mfc0 $v0, $5\n"
                                 "sw $v0, (%1)\n"
                                 "mfc0 $v0, $10\n"
                                 "sw $v0, (%2)\n"
                                 "mfc0 $v0, $2\n"
                                 "sw $v0, (%3)\n"
                                 "mfc0 $v0, $3\n"
                                 "sw $v0, (%4)\n" ::"r"(index),"r"(PageMask),"r"(EntryHi),"r"(EntryLo0),"r"(EntryLo1));
                 result=index;
         }
         else result=-1;
         return result;
 }
References index, and result.
GsGetIMR()
u64 GsGetIMR (void)
Referenced by ps2_screenshot().
GsPutIMR()
u64 GsPutIMR (u64 imr)
Referenced by graph_set_mode(), GsResetGraph(), Init_GS(), and ps2_screenshot().
iCancelWakeupThread()
s32 iCancelWakeupThread (s32 thread_id)
iChangeThreadPriority()
s32 iChangeThreadPriority (s32 thread_id, s32 priority)
iCpuConfig()
u32 iCpuConfig (u32 config)
iDeleteSema()
s32 iDeleteSema (s32 sema_id)
iDisableDmac()
int iDisableDmac (int dmac)
Referenced by dma_channel_shutdown().
iDisableDmacHandler()
void iDisableDmacHandler (u32 channel)
iDisableIntc()
int iDisableIntc (int intc)
iDisableIntcHandler()
void iDisableIntcHandler (u32 cause)
iEnableDmac()
int iEnableDmac (int dmac)
Referenced by dma_channel_initialize().
iEnableDmacHandler()
void iEnableDmacHandler (u32 channel)
iEnableIntc()
int iEnableIntc (int intc)
iEnableIntcHandler()
void iEnableIntcHandler (u32 cause)
iFlushCache()
void iFlushCache (s32 operation)
iGetCop0()
u32 iGetCop0 (s32 reg_id)
iGetTLBEntry()
int iGetTLBEntry (unsigned int index, unsigned int * PageMask, unsigned int * EntryHi, unsigned int * EntryLo0, unsigned int * EntryLo1)
iGsGetIMR()
u64 iGsGetIMR (void)
iGsPutIMR()
u64 iGsPutIMR (u64 imr)
iInvalidDCache()
void iInvalidDCache (void * start, void * end)
InitAlarm()
void InitAlarm (void)
Definition at line 43 of file alarm.c.
 {
         int i;
         setup(SysEntry[0].syscall, SysEntry[0].function);
         Copy((void*)0x80076000, srcfile, size_srcfile);
         Copy((void*)0x00082000, eenull, size_eenull);
         FlushCache(0);
         FlushCache(2);
         setup(SysEntry[1].syscall, SysEntry[1].function);
         for(i=2; i<8; i++)
                 setup(SysEntry[i].syscall, GetEntryAddress(SysEntry[i].syscall));
 }
References Copy(), eenull, FlushCache(), GetEntryAddress(), setup(), size_eenull, size_srcfile, srcfile, SyscallData::syscall, and SysEntry.
InitExecPS2()
void InitExecPS2 (void)
Definition at line 47 of file libosd.c.
                       {
         unsigned int i;
         if(PatchIsNeeded()){
                 setup(SyscallPatchEntries[0].syscall_num, SyscallPatchEntries[0].function);
                 Copy((unsigned int*)0x80074000, (unsigned int*)osdsrc, size_osdsrc);
                 FlushCache(0);
                 FlushCache(2);
                 setup(SyscallPatchEntries[1].syscall_num, SyscallPatchEntries[1].function);
                 for(i=2; i<3; i++){
                         setup(SyscallPatchEntries[i].syscall_num, GetEntryAddress(SyscallPatchEntries[i].syscall_num));
                 }
         }
 }
References Copy(), FlushCache(), GetEntryAddress(), osdsrc, PatchIsNeeded(), setup(), size_osdsrc, SyscallData::syscall_num, and SyscallPatchEntries.
InitOsd()
void InitOsd (void)
Definition at line 69 of file libosd_full.c.
                   {
         unsigned int i;
         if(PatchIsNeeded()){
                 setup(SyscallPatchEntries[0].syscall_num, SyscallPatchEntries[0].function);
                 Copy((unsigned int*)0x80074000, (unsigned int*)osdsrc, size_osdsrc);
                 FlushCache(0);
                 FlushCache(2);
                 setup(SyscallPatchEntries[1].syscall_num, SyscallPatchEntries[1].function);
                 for(i=2; i<7; i++){
                         setup(SyscallPatchEntries[i].syscall_num, GetEntryAddress(SyscallPatchEntries[i].syscall_num));
                 }
         }
 }
References Copy(), FlushCache(), GetEntryAddress(), osdsrc, PatchIsNeeded(), setup(), size_osdsrc, SyscallData::syscall_num, and SyscallPatchEntries.
InitThread()
int InitThread (void)
InitTLB()
void InitTLB (void)
Definition at line 57 of file tlbfunc.c.
                   {
         if(GetMemorySize()==0x2000000){
                 InitTLB32MB();
         }
         else{
                 _InitTLB();
         }
 }
InitTLBFunctions()
void InitTLBFunctions (void)
Definition at line 41 of file tlbfunc.c.
{
         int i;
         setup(SysEntry[0].syscall, SysEntry[0].function);
         Copy((void*)0x80075000, tlbsrc, size_tlbsrc);
         FlushCache(0);
         FlushCache(2);
         setup(SysEntry[1].syscall, SysEntry[1].function);
         for(i=3; i<8; i++){
                 setup(SysEntry[i].syscall, GetEntryAddress(SysEntry[i].syscall));
         }
         _kExecArg = GetEntryAddress(3);
 }
References _kExecArg, Copy(), FlushCache(), GetEntryAddress(), setup(), size_tlbsrc, SyscallData::syscall, SysEntry, and tlbsrc.
Interrupt2Iop()
s32 Interrupt2Iop (s32 cause)
InvalidDCache()
void InvalidDCache (void * start, void * end)
iPollSema()
s32 iPollSema (s32 sema_id)
iProbeTLBEntry()
int iProbeTLBEntry (unsigned int EntryHi, unsigned int * PageMask, unsigned int * EntryLo0, unsigned int * EntryLo1)
iPutTLBEntry()
int iPutTLBEntry (unsigned int PageMask, unsigned int EntryHi, unsigned int EntryLo0, unsigned int EntryLo1)
iReferSemaStatus()
s32 iReferSemaStatus (s32 sema_id, ee_sema_t * sema)
iReferThreadStatus()
s32 iReferThreadStatus (s32 thread_id, ee_thread_status_t * info)
iReleaseAlarm()
s32 iReleaseAlarm (s32 alarm_id)
iReleaseWaitThread()
s32 iReleaseWaitThread (s32 thread_id)
Referenced by TimeoutHandler().
iResumeThread()
s32 iResumeThread (s32 thread_id)
iRotateThreadReadyQueue()
s32 iRotateThreadReadyQueue (s32 priority)
iSetAlarm()
s32 iSetAlarm (u16 time, void(*)(s32 alarm_id, u16 time, void *common) callback, void * common)
iSetTLBEntry()
int iSetTLBEntry (unsigned int index, unsigned int PageMask, unsigned int EntryHi, unsigned int EntryLo0, unsigned int EntryLo1)
iSifDmaStat()
s32 iSifDmaStat (u32 id)
iSifSetDChain()
void iSifSetDChain (void)
Referenced by HandleRxEvent().
iSifSetDma()
u32 iSifSetDma (SifDmaTransfer_t * sdd, s32 len)
iSignalSema()
s32 iSignalSema (s32 sema_id)
Referenced by _fxio_intr(), _sleep_waker(), fillbuffer(), fxio_ctl_intr(), recv_intr(), VblankEndHandler(), and VblankStartHandler().
iSuspendThread()
s32 iSuspendThread (s32 thread_id)
iSyncDCache()
void iSyncDCache (void * start, void * end)
Referenced by dma_channel_send_chain(), dma_channel_send_normal(), and dma_channel_send_normal_ucab().
iTerminateThread()
s32 iTerminateThread (s32 thread_id)
iWakeupThread()
s32 iWakeupThread (s32 thread_id)
Referenced by EthStatusCheckCb(), and HandleRxEvent().
kCopy()
int kCopy (void * dest, const void * src, int size)
kCopyBytes()
int kCopyBytes (void * dest, const void * src, int size)
KSeg0()
void KSeg0 (s32 arg1)
LoadExecPS2()
void LoadExecPS2 (const char * filename, s32 num_args, char * args[])
MachineType()
s32 MachineType (void)
nopdelay()
static void nopdelay (void) inline static
Definition at line 141 of file kernel.h.
 {
         int i = 0xfffff;
         do {
                 __asm__ ("nop\nnop\nnop\nnop\nnop\n");
         } while (i-- != -1);
 }
Referenced by audsrv_init(), fileXioInit(), main(), mcInit(), mtapInit(), NetManInitRPCClient(), padInit(), poweroffInit(), PS2CamGetDeviceCount(), PS2CamGetDeviceInfo(), PS2CamGetDeviceStatus(), PS2CamGetIRXVersion(), PS2CamInit(), PS2CamSetDeviceBandwidth(), ps2ip_init(), PS2MouseInit(), RMMan_Init(), and sceSdInit().
PatchIsNeeded()
int PatchIsNeeded (void)
Definition at line 20 of file libosd_common.c.
{
         ConfigParam original_config, config;
         GetOsdConfigParam(&original_config);
         config=original_config;
         config.version=1;       //Protokernels cannot retain values set in this field.
         SetOsdConfigParam(&config);
         GetOsdConfigParam(&config);
         SetOsdConfigParam(&original_config);
         return(config.version<1);
 }
References GetOsdConfigParam(), SetOsdConfigParam(), and ConfigParam::version.
Referenced by InitExecPS2(), and InitOsd().
PollSema()
s32 PollSema (s32 sema_id)
Referenced by fileXioWaitAsync(), PollMbx(), sys_arch_sem_wait(), and try_alloc_msg().
ProbeTLBEntry()
int ProbeTLBEntry (unsigned int EntryHi, unsigned int * PageMask, unsigned int * EntryLo0, unsigned int * EntryLo1)
Definition at line 136 of file tlbsrc.c.
{
         int result, index;
         __asm volatile( "mtc0 %1, $10\n"
                         "sync.p\n"
                         "tlbp\n"
                         "sync.p\n"
                         "mfc0 %0, $0\n" :"=r"(index):"r"(EntryHi));
         if(index>=0){
                 __asm volatile( "tlbr\n"
                                 "sync.p\n"
                                 "mfc0 $v0, $5\n"
                                 "sw $v0, (%0)\n"
                                 "mfc0 $v1, $2\n"
                                 "sw $v1, (%1)\n"
                                 "mfc0 $v0, $3\n"
                                 "sw $v0, (%2)\n" ::"r"(PageMask),"r"(EntryLo0),"r"(EntryLo1));
                 result=index;
         }
         else result=-1;
         return result;
 }
References index, and result.
Referenced by ExpandScratchPad().
PSMode()
void PSMode (void)
PutTLBEntry()
int PutTLBEntry (unsigned int PageMask, unsigned int EntryHi, unsigned int EntryLo0, unsigned int EntryLo1)
Definition at line 61 of file tlbsrc.c.
{
         int result;
         switch(EntryHi>>24){
                 case 0x40:
                 case 0x30:
                 case 0x20:
                 case 0x00:
                         __asm volatile( "mtc0 %1, $5\n"
                                         "mtc0 %2, $10\n"
                                         "mtc0 %3, $2\n"
                                         "mtc0 %4, $3\n"
                                         "sync.p\n"
                                         "tlbwr\n"
                                         "sync.p\n"
                                         "tlbp\n"
                                         "sync.p\n"
                                         "mfc0 %0, $0\n" :"=r"(result):"r"(PageMask),"r"(EntryHi),"r"(EntryLo0),"r"(EntryLo1));
                         break;
                 case 0x50:
                 case 0x10:
                 default:        //SP193: I don't remember seeing a default case. Anyway... Keeping Compilers Happy (TM).
                         result=-1;
         }
         return result;
 }
References result.
ReferSemaStatus()
s32 ReferSemaStatus (s32 sema_id, ee_sema_t * sema)
ReferThreadStatus()
s32 ReferThreadStatus (s32 thread_id, ee_thread_status_t * info)
ReleaseAlarm()
s32 ReleaseAlarm (s32 alarm_id)
Definition at line 110 of file alarm.c.
 {
         u16 time;
         s32 result;
         int i, j;
         result = -1;
         for(i = 0; i < AlarmCount; i++)
         {
                 if(alarms[i].id == id)
                 {
                         if(alarms[i].target == *T3_COMP_W)
{
                                 if(*R_EE_I_STAT & (1 << INTC_TIM3))     //Cannot release alarm that has already triggered.
                                         return -1;
                         }
                         time = alarms[i].time;
                         //Move forward list.
                         for(j = i; j < AlarmCount - 1; j++)
                                 alarms[j] = alarms[j+1];
                         --AlarmCount;
                         AlarmStatus &= ~(1 << id);
                         if(i == 0)      //If the first alarm was released, update timer comparator.
                                 SetupTIM3(alarms[0].target);
                         if(AlarmCount == 0)     //Stop timer if there are no alarms left.
                                 *T3_MODE_W = Tn_MODE(3,0,0,0,0,1,0,0,0,0);
                         result = (CalculateTimeDiff(time, *T3_COUNT_W) - time);
                 }
         }
         EE_SYNC();
         return result;
 }
References AlarmCount, alarms, AlarmStatus, CalculateTimeDiff(), EE_SYNC, alarm::id, INTC_TIM3, R_EE_I_STAT, result, SetupTIM3(), T3_COMP_W, T3_COUNT_W, T3_MODE_W, alarm::target, alarm::time, time, and Tn_MODE.
Referenced by WaitSemaTimeout().
ReleaseWaitThread()
s32 ReleaseWaitThread (s32 thread_id)
RemoveDmacHandler()
s32 RemoveDmacHandler (s32 channel, s32 handler_id)
Referenced by dma_channel_shutdown(), and NetManDeinitRPCServer().
RemoveIntcHandler()
s32 RemoveIntcHandler (s32 cause, s32 handler_id)
Referenced by graph_remove_vsync_handler().
RemoveSbusIntcHandler()
s32 RemoveSbusIntcHandler (s32 cause)
ResetEE()
void ResetEE (u32 init_bitfield)
Referenced by dma_reset().
ResumeThread()
s32 ResumeThread (s32 thread_id)
RFU009()
void RFU009 (u32 arg0, u32 arg1)
RFU059()
u8 RFU059 (void)
RotateThreadReadyQueue()
s32 RotateThreadReadyQueue (s32 priority)
SetAlarm()
s32 SetAlarm (u16 time, void(*)(s32 alarm_id, u16 time, void *common) callback, void * common)
Referenced by nanosleep(), WaitSemaTimeout(), and WaitValidNetState().
SetCPUTimer()
void SetCPUTimer (s32 compval)
SetCPUTimerHandler()
void SetCPUTimerHandler (void(*)(void) handler)
SetGP()
void SetGP (void * gp)
Referenced by Intc12Handler().
SetGsCrt()
void SetGsCrt (s16 interlace, s16 pal_ntsc, s16 field)
Referenced by graph_set_mode(), GsResetGraph(), and Init_GS().
SetGsHParam()
void SetGsHParam (void * addr1, void * addr2, void * addr3, void * addr4)
SetGsVParam()
void SetGsVParam (s32 arg1)
SetMemoryMode()
int SetMemoryMode (int mode)
SetOsdConfigParam()
void SetOsdConfigParam (void * addr)
Referenced by PatchIsNeeded().
SetOsdConfigParam2()
void SetOsdConfigParam2 (void * config, s32 size, s32 offset)
SetPgifHandler()
void SetPgifHandler (void * handler)
SetSyscall()
void SetSyscall (s32 syscall_num, void * handler)
setup()
void setup (int syscall_num, void * handler)
Referenced by InitAlarm(), InitExecPS2(), and InitOsd().
SetupHeap()
void SetupHeap (void * heap_start, s32 heap_size)
SetupThread()
void* SetupThread (void * gp, void * stack, s32 stack_size, void * args, void * root_func)
SetVCommonHandler()
void SetVCommonHandler (s32 handler_num, void * handler_func)
Referenced by ee_dbg_install(), and ee_dbg_remove().
SetVInterruptHandler()
void SetVInterruptHandler (s32 handler_num, void * handler_func)
SetVSyncFlag()
void SetVSyncFlag (u32 * , u64 *)
SetVTLBRefillHandler()
void SetVTLBRefillHandler (s32 handler_num, void * handler_func)
Referenced by ee_dbg_install(), and ee_dbg_remove().
SifDmaStat()
s32 SifDmaStat (u32 id)
Referenced by audsrv_load_adpcm(), NETMAN_TxThread(), and sndLoadSample().
SifGetReg()
int SifGetReg (u32 register_num)
SifSetDChain()
void SifSetDChain (void)
SifSetDma()
u32 SifSetDma (SifDmaTransfer_t * sdd, s32 len)
Referenced by audsrv_load_adpcm(), ClearBufferLen(), NETMAN_TxThread(), sbv_patch_disable_prefix_check(), sbv_patch_enable_lmb(), sbv_patch_fileio(), smem_write_word(), and sndLoadSample().
SifSetReg()
int SifSetReg (u32 register_num, int register_value)
SifStopDma()
void SifStopDma (void)
SignalSema()
s32 SignalSema (s32 sema_id)
Referenced by _unlock(), accept(), audsrv_load_adpcm(), audsrv_play_audio(), audsrv_set_format(), bind(), call_rpc_1(), call_rpc_2(), connect(), disconnect(), fileXioChdir(), fileXioChStat(), fileXioClose(), fileXioCopyfile(), fileXioDclose(), fileXioDevctl(), fileXioDopen(), fileXioDread(), fileXioFormat(), fileXioGetDeviceList(), fileXioGetdir(), fileXioGetStat(), fileXioIoctl(), fileXioIoctl2(), fileXioLseek(), fileXioLseek64(), fileXioMkdir(), fileXioMount(), fileXioOpen(), fileXioRead(), fileXioReadlink(), fileXioRemove(), fileXioRename(), fileXioRmdir(), fileXioSetRWBufferSize(), fileXioSymlink(), fileXioSync(), fileXioUmount(), fileXioWaitAsync(), fileXioWrite(), free_msg(), getpeername(), getsockname(), getsockopt(), ioctlsocket(), listen(), NetManQueryMainIF(), NetManRpcIoctl(), NetManRPCRegisterNetworkStack(), NetManRPCUnregisterNetworkStack(), NetManSetLinkMode(), NetManSetMainIF(), PS2CamReadPacket(), ps2ip_getconfig(), ps2ip_setconfig(), recv(), recvfrom(), select(), send(), SendMbx(), sendto(), setsockopt(), socket(), and sys_sem_signal().
SleepThread()
s32 SleepThread (void)
Referenced by loadmodules(), LoadModules(), loadModules(), main(), NETMAN_RxThread(), NETMAN_TxThread(), serverThread(), and WaitValidNetState().
StartThread()
s32 StartThread (s32 thread_id, void * args)
Referenced by audsrv_init(), NetManInitRPCClient(), NetManInitRPCServer(), poweroffInit(), SIOR_Init(), and sys_thread_new().
SuspendThread()
s32 SuspendThread (s32 thread_id)
SyncDCache()
void SyncDCache (void * start, void * end)
Referenced by dma_channel_send_chain(), dma_channel_send_normal(), dma_channel_send_normal_ucab(), InitCB(), padGetDmaStr(), rmGetDmaStr(), sbv_patch_enable_lmb(), slib_exp_lib_list(), slib_get_exp_lib(), smem_write_word(), smod_get_mod_by_name(), and smod_get_next_mod().
TerminateLibrary()
void TerminateLibrary (void)
TerminateThread()
s32 TerminateThread (s32 thread_id)
Referenced by audsrv_quit(), deinitCleanup(), NetManDeinitRPCServer(), and poweroffInit().
WaitSema()
s32 WaitSema (s32 sema_id)
Referenced by _lock(), accept(), alloc_msg(), audsrv_load_adpcm(), audsrv_play_audio(), audsrv_quit(), audsrv_set_format(), bind(), call_rpc_1(), call_rpc_2(), connect(), disconnect(), fileXioChdir(), fileXioChStat(), fileXioClose(), fileXioCopyfile(), fileXioDclose(), fileXioDevctl(), fileXioDopen(), fileXioDread(), fileXioFormat(), fileXioGetDeviceList(), fileXioGetdir(), fileXioGetStat(), fileXioIoctl(), fileXioIoctl2(), fileXioLseek(), fileXioLseek64(), fileXioMkdir(), fileXioMount(), fileXioOpen(), fileXioRead(), fileXioReadlink(), fileXioRemove(), fileXioRename(), fileXioRmdir(), fileXioSetRWBufferSize(), fileXioSymlink(), fileXioSync(), fileXioUmount(), fileXioWaitAsync(), fileXioWrite(), getpeername(), getsockname(), getsockopt(), ioctlsocket(), listen(), main(), nanosleep(), NetManDeinitRPCClient(), NetManQueryMainIF(), NetManRpcIoctl(), NetManRPCRegisterNetworkStack(), NetManRPCUnregisterNetworkStack(), NetManSetLinkMode(), NetManSetMainIF(), PS2CamReadPacket(), ps2ip_getconfig(), ps2ip_setconfig(), ReceiveMbx(), recv(), recvfrom(), select(), send(), sendto(), setsockopt(), socket(), sys_arch_sem_wait(), and WaitSemaTimeout().
WakeupThread()
s32 WakeupThread (s32 thread_id)
Referenced by NetManRpcNetIFXmit().
Variable Documentation
_gp
void* _gp extern
errno
int errno extern
Referenced by sleep().