ps2sdk: ee/libgs/src/internal.h File Reference
internal.h File Reference
Functions
int checkModelVersion (void)
void GsDmaInit (void)
void GsDmaSend (const void *addr, u32 qwords)
void GsDmaSend_tag (const void *addr, u32 qwords, const GS_GIF_DMACHAIN_TAG *tag)
void GsDmaWait (void)
Function Documentation
checkModelVersion()
int checkModelVersion (void)
Definition at line 52 of file draw.c.
 {
         int fd, result, i;
         char data[256], *pData;
         if((fd=open("rom0:ROMVER", O_RDONLY))>=0)
         {
                 for(pData=data,i=0; i<sizeof(data); i++)
                 {
                         read(fd, pData, 1);
                         if(*pData++=='\0') break;
                 }
                 close(fd);
                 //ROMVER string format: VVVVRTYYYYMMDD\n
                 result=(20010608<atoi(data+i-9));
         }
         else result=-1;
         return result;
 }
References data, and result.
Referenced by GsSetDefaultDisplayEnv().
GsDmaInit()
void GsDmaInit (void)
Definition at line 58 of file dma.c.
 {
         /* This appears to have been based on code from Sony that initializes DMA channels 0-9, in bulk.
            Reset/init DMA CH 2 (GIF) only. */
         __asm__(
         "li     $2,0x1000A000   \n"
         "sw     $0,0x80($2)             \n" // D2_SADR = 0. Documented to not exist, but is done.
         "sw     $0,0($2)                \n" // D2_CHCR = 0
         "sw     $0,0x30($2)             \n" // D2_TADR = 0
         "sw     $0,0x10($2)             \n" // D2_MADR = 0
         "sw     $0,0x50($2)             \n" // D2_ASR1 = 0
         "sw     $0,0x40($2)             \n" // D2_ASR0 = 0
         "li     $2,0xFF1F               \n" // Clear all interrupt status under D_STAT, other than SIF0, SIF1 & SIF2.
         "sw     $2,0x1000E010   \n"
         "lw     $2,0x1000E010   \n"
         "lui    $3,0xFF1F               \n" // Clear all interrupt masks under D_STAT, other SIF0, SIF1 & SIF2. Writing a 1 reverses the bit.
         "and    $2,$3           \n"
         "sw     $2,0x1000E010   \n"
         "sw     $0,0x1000E000   \n" // D_CTRL = 0
         "sw     $0,0x1000E020   \n" // D_PCR = 0
         "sw     $0,0x1000E030   \n" // D_SQWC = 0
         "sw     $0,0x1000E050   \n" // D_RBOR = 0
         "sw     $0,0x1000E040   \n" // D_RBSR = 0
         "li     $3,1                    \n"
         "lw     $2,0x1000E000   \n"
         "ori    $3,$2,1         \n" // D_CTRL (DMAE 1)
         "sw     $3,0x1000E000   \n"
         );
 }
Referenced by GsResetGraph().
GsDmaSend()
void GsDmaSend (const void * addr, u32 qwords)
Definition at line 88 of file dma.c.
 {
         DMA_CHCR                chcr;
         static char             spr;
         if((u32)addr >= 0x70000000 && (u32)addr <= 0x70003fff)
         {
                 spr = 1;
         }
         else
         {
                 spr = 0;
         }
         *((vu32 *)(gif_madr)) = ( u32 )((( u32 )addr) & 0x7FFFFFFF) << 0 | (u32)((spr) & 0x00000001) << 31;;
         *((vu32 *)(gif_qwc)) = qwords;
         chcr.direction  =1;
         chcr.mode               =0;
         chcr.asp                =0;
         chcr.tte                =0;
         chcr.tie                =0;
         chcr.start_flag =1;
         chcr.tag                =0;
         chcr.pad1               =0;
         chcr.pad2               =0;
         *((volatile DMA_CHCR *)(gif_chcr)) = chcr;
 }
References DMA_CHCR::asp, DMA_CHCR::direction, gif_chcr, gif_madr, gif_qwc, DMA_CHCR::mode, DMA_CHCR::pad1, DMA_CHCR::pad2, DMA_CHCR::start_flag, DMA_CHCR::tag, DMA_CHCR::tie, and DMA_CHCR::tte.
Referenced by GsClearDrawEnv1(), GsClearDrawEnv2(), GsEnableAlphaBlending1(), GsEnableAlphaBlending2(), GsEnableAlphaTransparency1(), GsEnableAlphaTransparency2(), GsEnableColorClamp(), GsEnableDithering(), GsLoadImage(), GsOverridePrimAttributes(), GsPutZBufferEnv1(), GsPutZBufferEnv2(), GsSelectTexure1(), GsSelectTexure2(), GsSetFogColor(), GsSetFrame1(), GsSetFrame2(), GsSetPixelTest1(), GsSetPixelTest2(), GsSetScissor1(), GsSetScissor2(), GsSetXYOffset1(), GsSetXYOffset2(), and GsTextureFlush().
GsDmaSend_tag()
void GsDmaSend_tag (const void * addr, u32 qwords, const GS_GIF_DMACHAIN_TAG * tag)
Definition at line 118 of file dma.c.
 {
         DMA_CHCR                chcr;
         static char             spr;
         if((u32)addr >= 0x70000000 && (u32)addr <= 0x70003fff)
         {
                 spr = 1;
         }
         else
         {
                 spr = 0;
         }
         *((vu32 *)(gif_madr)) = ( u32 )((( u32 )addr) & 0x7FFFFFFF) << 0 | (u32)((spr) & 0x00000001) << 31;
         *((vu32 *)(gif_qwc)) = qwords;
         *((vu32 *)(gif_tadr)) = ( u32 )((( u32 )tag) & 0x7FFFFFFF) << 0 | (u32)((0) & 0x00000001) << 31;
         chcr.direction  =1;
         chcr.mode               =1; //chain
         chcr.asp                =0;
         chcr.tte                =0;
         chcr.tie                =0;
         chcr.start_flag =1;
         chcr.tag                =0;
         chcr.pad1               =0;
         chcr.pad2               =0;
         *((volatile DMA_CHCR *)(gif_chcr)) = chcr;
 }
References DMA_CHCR::asp, DMA_CHCR::direction, gif_chcr, gif_madr, gif_qwc, gif_tadr, DMA_CHCR::mode, DMA_CHCR::pad1, DMA_CHCR::pad2, DMA_CHCR::start_flag, DMA_CHCR::tag, DMA_CHCR::tie, and DMA_CHCR::tte.
Referenced by GsGifPacketsExecute().
GsDmaWait()
void GsDmaWait (void)
Definition at line 148 of file dma.c.
 {
         while(*((vu32 *)(0x1000a000)) & ((u32)1<<8));
 }
Referenced by GsClearDrawEnv1(), GsClearDrawEnv2(), GsDrawSync(), GsEnableAlphaBlending1(), GsEnableAlphaBlending2(), GsEnableAlphaTransparency1(), GsEnableAlphaTransparency2(), GsEnableColorClamp(), GsEnableDithering(), GsGifPacketsExecute(), GsLoadImage(), GsOverridePrimAttributes(), GsPutZBufferEnv1(), GsPutZBufferEnv2(), GsSelectTexure1(), GsSelectTexure2(), GsSetFogColor(), GsSetFrame1(), GsSetFrame2(), GsSetPixelTest1(), GsSetPixelTest2(), GsSetScissor1(), GsSetScissor2(), GsSetXYOffset1(), GsSetXYOffset2(), and GsTextureFlush().