ps2sdk: ee/libgs/samples/libgs_draw/main.c File Reference
main.c File Reference
#include <kernel.h>
#include <libgs.h>
Data Structures
struct MAVING_SPRITE
Macros
#define MAX_SPRITES 1000
#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 448
#define GIF_PACKET_MAX 10
Functions
static int InitGraphics (void)
static int InitSprites (void)
static int MoveSprites (void)
static int DrawSprites (GS_PACKET_TABLE *table)
int main (int argc, char *argv[])
Variables
static const char x_randspeeds [10] = {1,4,6,5,2,3,8,6,6,7}
static const GS_RGBAQ randcolor [10]
static short int ScreenOffsetX
static short int ScreenOffsetY
static GS_DRAWENV draw_env
static GS_DISPENV disp_env
static GS_GIF_PACKET packets [GIF_PACKET_MAX]
static GS_PACKET_TABLE giftable
static MAVING_SPRITE sprites [MAX_SPRITES]
Macro Definition Documentation
GIF_PACKET_MAX
#define GIF_PACKET_MAX 10
Definition at line 50 of file main.c.
MAX_SPRITES
#define MAX_SPRITES 1000
Definition at line 43 of file main.c.
SCREEN_HEIGHT
#define SCREEN_HEIGHT 448
Definition at line 46 of file main.c.
SCREEN_WIDTH
#define SCREEN_WIDTH 640
Definition at line 45 of file main.c.
Function Documentation
DrawSprites()
static int DrawSprites (GS_PACKET_TABLE * table) static
Definition at line 213 of file main.c.
 {
         int i;
         QWORD *p;
         for(i=0;i<MAX_SPRITES;i++)
         {
                 //Use the uncached segment, to avoid needing to flush the data cache.
                 p = (QWORD*)UNCACHED_SEG(GsGifPacketsAlloc(table, 5)); //Allocate 5 qword for 1 untextured strite
                 /*      For this GIF packet, the EOP flag is set to 1.
                         Rightfully, it should only be set for only the final packet so that the GIF knows when it can safely switch paths,
                         but to keep things simple, it's set to 1 for every packet.
                         The packets are all in the PACKED format.       */
                 gs_setGIF_TAG(((GS_GIF_TAG      *)&p[0]), 4,1,0,0,GS_GIF_PACKED,1,gif_rd_ad);
                 gs_setR_PRIM(((GS_R_PRIM        *)&p[1]), GS_PRIM_SPRITE,0, 0, 0, 1, 0, 0, 0, 0);
                 gs_setR_RGBAQ(((GS_R_RGBAQ      *)&p[2]), sprites[i].color.r, sprites[i].color.g, sprites[i].color.b, sprites[i].color.a, sprites[i].color.q);
                 gs_setR_XYZ2(((GS_R_XYZ         *)&p[3]), (ScreenOffsetX+sprites[i].x_pos)<<4,  (ScreenOffsetY+sprites[i].y_pos)<<4, 0x00000000);
                 gs_setR_XYZ2(((GS_R_XYZ         *)&p[4]), (ScreenOffsetX+sprites[i].x_pos+10)<<4,       (ScreenOffsetY+sprites[i].y_pos+10)<<4, 0x00000000);
         }
         return 0;
 }
References GS_RGBAQ::a, GS_RGBAQ::b, MAVING_SPRITE::color, GS_RGBAQ::g, gif_rd_ad, GS_GIF_PACKED, GS_PRIM_SPRITE, gs_setGIF_TAG, gs_setR_PRIM, gs_setR_RGBAQ, gs_setR_XYZ2, GsGifPacketsAlloc(), MAX_SPRITES, GS_RGBAQ::q, ScreenOffsetX, ScreenOffsetY, sprites, and UNCACHED_SEG.
Referenced by main().
InitGraphics()
int InitGraphics (void) static
Definition at line 88 of file main.c.
 {
         unsigned int FrameBufferVRAMAddress;
         GsResetGraph(GS_INIT_RESET, GS_INTERLACED, GS_MODE_NTSC, GS_FFMD_FIELD);
         FrameBufferVRAMAddress=GsVramAllocFrameBuffer(SCREEN_WIDTH, SCREEN_HEIGHT, GS_PIXMODE_32);
         GsSetDefaultDrawEnv(&draw_env, GS_PIXMODE_32, SCREEN_WIDTH, SCREEN_HEIGHT);
         //Retrieve screen offset parameters.
         ScreenOffsetX=draw_env.offset_x;
         ScreenOffsetY=draw_env.offset_y;
         GsSetDefaultDrawEnvAddress(&draw_env, FrameBufferVRAMAddress);
         GsSetDefaultDisplayEnv(&disp_env, GS_PIXMODE_32, SCREEN_WIDTH, SCREEN_HEIGHT, 0, 0);
         GsSetDefaultDisplayEnvAddress(&disp_env, FrameBufferVRAMAddress);
         //execute draw/display environment(s)  (context 1)
         GsPutDrawEnv1(&draw_env);
         GsPutDisplayEnv1(&disp_env);
         //Set common primitive-drawing settings (Refer to documentation on PRMODE and PRMODECONT registers).
         GsOverridePrimAttributes(GS_DISABLE, 0, 0, 0, 0, 0, 0, 0, 0);
         //Set transparency settings for context 1 (Refer to documentation on TEST and TEXA registers).
         //Alpha test = enabled, pass if >= alpha reference, alpha reference = 1, fail method = no update
         GsEnableAlphaTransparency1(GS_ENABLE, GS_ALPHA_GEQUAL, 0x01, GS_ALPHA_NO_UPDATE);
         //Enable global alpha blending
         GsEnableAlphaBlending1(GS_ENABLE);
         //set transparency settings for context 2 (Refer to documentation on TEST and TEXA registers).
         //Alpha test = enabled, pass if >= alpha reference, alpha reference = 1, fail method = no update
         GsEnableAlphaTransparency2(GS_ENABLE, GS_ALPHA_GEQUAL, 0x01, GS_ALPHA_NO_UPDATE);
         //Enable global alpha blending
         GsEnableAlphaBlending2(GS_ENABLE);
         return 0;
 }
References disp_env, draw_env, GS_ALPHA_GEQUAL, GS_ALPHA_NO_UPDATE, GS_DISABLE, GS_ENABLE, GS_FFMD_FIELD, GS_INIT_RESET, GS_INTERLACED, GS_MODE_NTSC, GS_PIXMODE_32, GsEnableAlphaBlending1(), GsEnableAlphaBlending2(), GsEnableAlphaTransparency1(), GsEnableAlphaTransparency2(), GsOverridePrimAttributes(), GsPutDisplayEnv1(), GsPutDrawEnv1(), GsResetGraph(), GsSetDefaultDisplayEnv(), GsSetDefaultDisplayEnvAddress(), GsSetDefaultDrawEnv(), GsSetDefaultDrawEnvAddress(), GsVramAllocFrameBuffer(), GS_DRAWENV::offset_x, GS_DRAWENV::offset_y, SCREEN_HEIGHT, SCREEN_WIDTH, ScreenOffsetX, and ScreenOffsetY.
Referenced by main().
InitSprites()
static int InitSprites (void) static
Definition at line 128 of file main.c.
 {
         int i,j;
         for(i=0,j=0;i<MAX_SPRITES;i++,j++)
         {
                 if(j>9)j=0;
                 sprites[i].x_pos        =i;
                 sprites[i].y_pos        =i/2;
                 sprites[i].x_dir        =0;
                 sprites[i].y_dir        =0;
                 sprites[i].x_speed      =i/x_randspeeds[j];
                 sprites[i].y_speed      =x_randspeeds[j]+1;
                 if(sprites[i].x_speed<=0)sprites[i].x_speed=2;
                 if(sprites[i].y_speed<=0)sprites[i].y_speed=1;
                 //set color
                 sprites[i].color = randcolor[j];
         }
         return 0;
 }
References MAVING_SPRITE::color, MAX_SPRITES, randcolor, sprites, MAVING_SPRITE::x_dir, MAVING_SPRITE::x_pos, x_randspeeds, MAVING_SPRITE::x_speed, MAVING_SPRITE::y_dir, MAVING_SPRITE::y_pos, and MAVING_SPRITE::y_speed.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 63 of file main.c.
 {
         InitGraphics();
         giftable.packet_count   = GIF_PACKET_MAX;
         giftable.packets        = packets;
         InitSprites();
         while(1)
         {
                 GsGifPacketsClear(&giftable);           // clear the area that we are going to put the sprites/triangles/....
                 MoveSprites();
                 DrawSprites(&giftable);                 //add stuff to the packet area
                 GsDrawSync(0);
                 GsVSync(0);
                 GsClearDrawEnv1(&draw_env);             // clear the draw environment before we draw stuff on it
                 GsGifPacketsExecute(&giftable, 1);      // set to '1' becuse we want to wait for drawing to finish. if we dont wait we will write on packets that is currently writing to the gif
         }
         return 0;
 }
References draw_env, DrawSprites(), GIF_PACKET_MAX, giftable, GsClearDrawEnv1(), GsDrawSync(), GsGifPacketsClear(), GsGifPacketsExecute(), GsVSync(), InitGraphics(), InitSprites(), MoveSprites(), GS_PACKET_TABLE::packet_count, GS_PACKET_TABLE::packets, and packets.
MoveSprites()
static int MoveSprites (void) static
Definition at line 156 of file main.c.
 {
         int i;
         for(i=0;i<MAX_SPRITES;i++)
         {
                 // mod a little
         //      sprites[i].x_speed++;
         //      sprites[i].y_speed++;
                 if(sprites[i].x_speed>10)sprites[i].x_speed             =sprites[i].x_speed-10;
                 if(sprites[i].y_speed>10)sprites[i].y_speed             =sprites[i].y_speed-10;
                 //x
                 if(sprites[i].x_dir==0)
                 {
                         sprites[i].x_pos        -= sprites[i].x_speed;
                         if(sprites[i].x_pos<0)
{
                                 sprites[i].x_pos=0;
                                 sprites[i].x_dir=1;
                         }
                 }
                 else if(sprites[i].x_dir==1)
                 {
                         sprites[i].x_pos        += sprites[i].x_speed;
                         if(sprites[i].x_pos>SCREEN_WIDTH)
{
                                 sprites[i].x_pos = SCREEN_WIDTH;
                                 sprites[i].x_dir=0;
                         }
                 }
                 //y
                 if(sprites[i].y_dir==0)
                 {
                         sprites[i].y_pos        -= sprites[i].y_speed;
                         if(sprites[i].y_pos<0)
{
                                 sprites[i].y_pos=0;
                                 sprites[i].y_dir=1;
                         }
                 }
                 else if(sprites[i].y_dir==1)
                 {
                         sprites[i].y_pos        += sprites[i].y_speed;
                         if(sprites[i].y_pos>SCREEN_HEIGHT)
{
                                 sprites[i].y_pos=SCREEN_HEIGHT;
                                 sprites[i].y_dir=0;
                         }
                 }
         }
         return 0;
 }
References MAX_SPRITES, SCREEN_HEIGHT, SCREEN_WIDTH, sprites, MAVING_SPRITE::x_dir, MAVING_SPRITE::x_pos, MAVING_SPRITE::x_speed, MAVING_SPRITE::y_dir, MAVING_SPRITE::y_pos, and MAVING_SPRITE::y_speed.
Referenced by main().
Variable Documentation
disp_env
GS_DISPENV disp_env static
Definition at line 53 of file main.c.
Referenced by InitGraphics().
draw_env
GS_DRAWENV draw_env static
Definition at line 52 of file main.c.
Referenced by InitGraphics(), and main().
giftable
GS_PACKET_TABLE giftable static
Definition at line 56 of file main.c.
Referenced by main().
packets
GS_GIF_PACKET packets[GIF_PACKET_MAX] static
Definition at line 55 of file main.c.
Referenced by main().
randcolor
const GS_RGBAQ randcolor[10] static
Initial value:
={      {28 ,200,200,0x80,0.0f},
                                        {255,  0,128,0x80,0.0f},
                                        {255,128,0,0x80,0.0f},
                                        {255,255,255,0x80,0.0f},
                                        {0  ,128,255,0x80,0.0f},
                                        {255,255,128,0x80,0.0f},
                                        {128,128,255,0x80,0.0f},
                                        {226,137,245,0x80,0.0f},
                                        {172,177,210,0x80,0.0f},
                                        {221,180,162,0x80,0.0f}
                                }
Definition at line 30 of file main.c.
Referenced by InitSprites().
ScreenOffsetX
short int ScreenOffsetX static
Definition at line 48 of file main.c.
Referenced by DrawSprites(), and InitGraphics().
ScreenOffsetY
short int ScreenOffsetY static
Definition at line 48 of file main.c.
Referenced by DrawSprites(), and InitGraphics().
sprites
MAVING_SPRITE sprites[MAX_SPRITES] static
Definition at line 126 of file main.c.
Referenced by DrawSprites(), InitSprites(), and MoveSprites().
x_randspeeds
const char x_randspeeds[10] = {1,4,6,5,2,3,8,6,6,7} static
Definition at line 28 of file main.c.
Referenced by InitSprites().