ps2sdk: ee/libgs/src/libgs.c File Reference
libgs.c File Reference
#include <errno.h>
#include <stdio.h>
#include <kernel.h>
#include <libgs.h>
#include "internal.h"
Functions
GsGParam_t * GsGetGParam (void)
void GsResetGraph (s16 mode, s16 interlace, s16 omode, s16 ffmode)
void GsSetCRTCSettings (u64 settings, u8 alpha_value)
Variables
QWORD GsPrimWorkArea []
static GsGParam_t gp_15 ={GS_INTERLACED, GS_MODE_NTSC, GS_FFMD_FRAME, 3}
Function Documentation
GsGetGParam()
GsGParam_t* GsGetGParam (void)
Definition at line 24 of file libgs.c.
 {
         return &gp_15;
 }
References gp_15.
Referenced by GsResetGraph(), and GsSetDefaultDisplayEnv().
GsResetGraph()
void GsResetGraph (s16 mode, s16 interlace, s16 omode, s16 ffmode)
Definition at line 29 of file libgs.c.
 {
         GsGParam_t *pGParams;
         switch(mode){
                 case GS_INIT_RESET:
                         GsDmaInit();    //It seems like the Sony developers reset the GIF DMA channel with their libdma library, but a lot of homebrew GS libraries will do this on their own.
                         pGParams=GsGetGParam();
                         GS_SET_CSR_reset(1);
                         pGParams->ffmode=ffmode;
                         pGParams->interlace=interlace;
                         pGParams->omode=omode;
                         pGParams->version=GS_GET_CSR_gs_rev_number>>16;
                         GsPutIMR(0xFF00);
                         SetGsCrt(interlace&1, omode&0xFF, ffmode&1);
                         GsSetCRTCSettings(CRTC_SETTINGS_DEFAULT1, 0x80);
                         break;
                 case GS_INIT_DRAW_RESET:
                         GS_SET_CSR_flush(1);
                         break;
         /*      There is a mode 5 present in the Sony sceGsResetGraph, but is not documented. It seems to change the video mode without resetting anything. */
         }
 }
References CRTC_SETTINGS_DEFAULT1, GsGParam_t::ffmode, GS_GET_CSR_gs_rev_number, GS_INIT_DRAW_RESET, GS_INIT_RESET, GS_SET_CSR_flush, GS_SET_CSR_reset, GsDmaInit(), GsGetGParam(), GsPutIMR(), GsSetCRTCSettings(), GsGParam_t::interlace, mode, GsGParam_t::omode, SetGsCrt(), and GsGParam_t::version.
GsSetCRTCSettings()
void GsSetCRTCSettings (u64 settings, u8 alpha_value)
Definition at line 56 of file libgs.c.
 {
         *((vu64 *)(gs_p_pmode)) =  (settings|((u64)(0x001) << 2)|((u64)(alpha_value)    << 8));
 }
References gs_p_pmode.
Referenced by GsResetGraph(), and SelectDisplayContext().
Variable Documentation
gp_15
GsGParam_t gp_15 ={GS_INTERLACED, GS_MODE_NTSC, GS_FFMD_FRAME, 3} static
Definition at line 22 of file libgs.c.
Referenced by GsGetGParam().
GsPrimWorkArea
QWORD GsPrimWorkArea[] extern
Definition at line 18 of file packets.c.