ps2sdk: ee/mpeg/include/libmpeg.h File Reference
libmpeg.h File Reference
#include <tamtypes.h>
Data Structures
struct MPEGSequenceInfo
Macros
#define MPEG_CHROMA_FORMAT_420 1
#define MPEG_CHROMA_FORMAT_422 2
#define MPEG_CHROMA_FORMAT_444 3
#define MPEG_PROFILE_422 133
#define MPEG_PROFILE_SIMPLE 5
#define MPEG_PROFILE_MAIN_ 4
#define MPEG_PROFILE_SNR_SCALABLE 3
#define MPEG_PROFILE_SPT_SCALABLE 2
#define MPEG_PROFILE_HIGH 1
#define MPEG_LEVEL_MAIN 8
#define MPEG_LEVEL_LOW 12
#define MPEG_LEVEL_HIGH1440 6
#define MPEG_LEVEL_HIGH 4
#define MPEG_VIDEO_FORMAT_COMPONENT 0
#define MPEG_VIDEO_FORMAT_PAL 1
#define MPEG_VIDEO_FORMAT_NTSC 2
#define MPEG_VIDEO_FORMAT_SECAM 3
#define MPEG_VIDEO_FORMAT_MAC 4
#define MPEG_VIDEO_FORMAT_UNSPEC 5
Functions
void MPEG_Initialize (int(*)(void *), void *, void *(*)(void *, MPEGSequenceInfo *), void *, s64 *)
void MPEG_Destroy (void)
Variables
int(* MPEG_Picture)(void *, s64 *)
Detailed Description
MPEG decoding functions.
Definition in file libmpeg.h.
Macro Definition Documentation
MPEG_CHROMA_FORMAT_420
#define MPEG_CHROMA_FORMAT_420 1
Definition at line 21 of file libmpeg.h.
MPEG_CHROMA_FORMAT_422
#define MPEG_CHROMA_FORMAT_422 2
Definition at line 22 of file libmpeg.h.
MPEG_CHROMA_FORMAT_444
#define MPEG_CHROMA_FORMAT_444 3
Definition at line 23 of file libmpeg.h.
MPEG_LEVEL_HIGH
#define MPEG_LEVEL_HIGH 4
Definition at line 35 of file libmpeg.h.
MPEG_LEVEL_HIGH1440
#define MPEG_LEVEL_HIGH1440 6
Definition at line 34 of file libmpeg.h.
MPEG_LEVEL_LOW
#define MPEG_LEVEL_LOW 12
Definition at line 33 of file libmpeg.h.
MPEG_LEVEL_MAIN
#define MPEG_LEVEL_MAIN 8
Definition at line 32 of file libmpeg.h.
MPEG_PROFILE_422
#define MPEG_PROFILE_422 133
Definition at line 25 of file libmpeg.h.
MPEG_PROFILE_HIGH
#define MPEG_PROFILE_HIGH 1
Definition at line 30 of file libmpeg.h.
MPEG_PROFILE_MAIN_
#define MPEG_PROFILE_MAIN_ 4
Definition at line 27 of file libmpeg.h.
MPEG_PROFILE_SIMPLE
#define MPEG_PROFILE_SIMPLE 5
Definition at line 26 of file libmpeg.h.
MPEG_PROFILE_SNR_SCALABLE
#define MPEG_PROFILE_SNR_SCALABLE 3
Definition at line 28 of file libmpeg.h.
MPEG_PROFILE_SPT_SCALABLE
#define MPEG_PROFILE_SPT_SCALABLE 2
Definition at line 29 of file libmpeg.h.
MPEG_VIDEO_FORMAT_COMPONENT
#define MPEG_VIDEO_FORMAT_COMPONENT 0
Definition at line 37 of file libmpeg.h.
MPEG_VIDEO_FORMAT_MAC
#define MPEG_VIDEO_FORMAT_MAC 4
Definition at line 41 of file libmpeg.h.
MPEG_VIDEO_FORMAT_NTSC
#define MPEG_VIDEO_FORMAT_NTSC 2
Definition at line 39 of file libmpeg.h.
MPEG_VIDEO_FORMAT_PAL
#define MPEG_VIDEO_FORMAT_PAL 1
Definition at line 38 of file libmpeg.h.
MPEG_VIDEO_FORMAT_SECAM
#define MPEG_VIDEO_FORMAT_SECAM 3
Definition at line 40 of file libmpeg.h.
MPEG_VIDEO_FORMAT_UNSPEC
#define MPEG_VIDEO_FORMAT_UNSPEC 5
Definition at line 42 of file libmpeg.h.
Function Documentation
MPEG_Destroy()
void MPEG_Destroy (void)
Definition at line 117 of file libmpeg.c.
{
  _destroy_seq  ();
  _MPEG_Destroy ();
 }  /* end MPEG_Destroy */
References _destroy_seq(), and _MPEG_Destroy().
Referenced by main().
MPEG_Initialize()
void MPEG_Initialize (int(*)(void *) , void * , void * *)(void *, MPEGSequenceInfo *, void * , s64 *)
Referenced by main().
Variable Documentation
MPEG_Picture
int(* MPEG_Picture) (void *, s64 *) (void * , s64 *)
Definition at line 62 of file libmpeg.h.
Referenced by main().