ps2sdk: ee/rpc/mouse/include/libmouse.h File Reference
libmouse.h File Reference
#include <ps2mouse.h>
Typedefs
typedef mouse_data PS2MouseData
Functions
int PS2MouseInit (void)
int PS2MouseRead (PS2MouseData *)
int PS2MouseSetReadMode (u32 readMode)
u32 PS2MouseGetReadMode ()
int PS2MouseSetThres (u32 thres)
u32 PS2MouseGetThres ()
int PS2MouseSetAccel (float accel)
float PS2MouseGetAccel ()
int PS2MouseSetBoundary (int minx, int maxx, int miny, int maxy)
int PS2MouseGetBoundary (int *minx, int *maxx, int *miny, int *maxy)
int PS2MouseSetPosition (int x, int y)
int PS2MouseReset ()
u32 PS2MouseEnum ()
int PS2MouseSetDblClickTime (u32 msec)
u32 PS2MouseGetDblClickTIme ()
u32 PS2MouseGetVersion ()
Detailed Description
USB Mouse Driver for PS2
Definition in file libmouse.h.
Typedef Documentation
PS2MouseData
typedef mouse_data PS2MouseData
Definition at line 21 of file libmouse.h.
Function Documentation
PS2MouseEnum()
u32 PS2MouseEnum ()
Definition at line 205 of file libmouse.c.
 {
   u32* uncached = (u32 *) UNCACHED_SEG(&buffer.data);
   if (SifCallRpc(&mouseif, PS2MOUSE_ENUM, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
     return -1;
   return uncached[0];
 }
References buffer, mouseif, NULL, PS2MOUSE_ENUM, SifCallRpc(), and UNCACHED_SEG.
PS2MouseGetAccel()
float PS2MouseGetAccel ()
Definition at line 140 of file libmouse.c.
 {
   u32* uncached = (u32 *) UNCACHED_SEG(&buffer.accel);
   u32 accel_fixed;
   if (SifCallRpc(&mouseif, PS2MOUSE_GETACCEL, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
     return -1;
   accel_fixed = uncached[0];
   return ((float) accel_fixed) / 65536.0 ;
 }
References buffer, mouseif, NULL, PS2MOUSE_GETACCEL, SifCallRpc(), and UNCACHED_SEG.
PS2MouseGetBoundary()
int PS2MouseGetBoundary (int * minx, int * maxx, int * miny, int * maxy)
Definition at line 168 of file libmouse.c.
 {
   struct mbounds* uncached = (struct mbounds *) UNCACHED_SEG(&buffer.bounds);
   if (SifCallRpc(&mouseif, PS2MOUSE_GETBOUNDARY, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
     return -1;
   *minx = uncached->minx;
   *maxx = uncached->maxx;
   *miny = uncached->miny;
   *maxy = uncached->maxy;
   return 1;
 }
References buffer, maxx, maxy, minx, miny, mouseif, NULL, PS2MOUSE_GETBOUNDARY, SifCallRpc(), and UNCACHED_SEG.
PS2MouseGetDblClickTIme()
u32 PS2MouseGetDblClickTIme ()
Definition at line 238 of file libmouse.c.
 {
   u32* uncached = (u32 *) UNCACHED_SEG(&buffer.time);
   if (SifCallRpc(&mouseif, PS2MOUSE_GETDBLCLICKTIME, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
     return -1;
   return uncached[0];
 }
References buffer, mouseif, NULL, PS2MOUSE_GETDBLCLICKTIME, SifCallRpc(), and UNCACHED_SEG.
PS2MouseGetReadMode()
u32 PS2MouseGetReadMode ()
Gets the current read mode
Definition at line 94 of file libmouse.c.
 {
   u32 *uncached = (u32 *) UNCACHED_SEG(&buffer.mode);
   if (SifCallRpc(&mouseif, PS2MOUSE_GETREADMODE, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
     return 0xFF;
   return uncached[0];
 }
References buffer, mouseif, NULL, PS2MOUSE_GETREADMODE, SifCallRpc(), and UNCACHED_SEG.
PS2MouseGetThres()
u32 PS2MouseGetThres ()
Definition at line 115 of file libmouse.c.
 {
   u32* uncached = (u32 *) UNCACHED_SEG(&buffer.thres);
   if (SifCallRpc(&mouseif, PS2MOUSE_GETTHRES, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
     return 0;
   return uncached[0];
 }
References buffer, mouseif, NULL, PS2MOUSE_GETTHRES, SifCallRpc(), and UNCACHED_SEG.
PS2MouseGetVersion()
u32 PS2MouseGetVersion ()
Definition at line 216 of file libmouse.c.
 {
   u32* uncached = (u32 *) UNCACHED_SEG(&buffer.data);
   if (SifCallRpc(&mouseif, PS2MOUSE_GETVERSION, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
     return -1;
   return uncached[0];
 }
References buffer, mouseif, NULL, PS2MOUSE_GETVERSION, SifCallRpc(), and UNCACHED_SEG.
PS2MouseInit()
int PS2MouseInit (void)
Initialise the RPC library
Definition at line 41 of file libmouse.c.
 {
   if(mouse_init)
     {
       printf("PS2Mouse Library already initialised\n");
       return 0;
     }
   mouseif.server = NULL;
   do {
     if (SifBindRpc(&mouseif, PS2MOUSE_BIND_RPC_ID, 0) < 0) {
       return -1;
     }
     nopdelay();
   } while(!mouseif.server);
   mouse_init = 1;
   return 1;
 }
References mouse_init, mouseif, nopdelay(), NULL, PS2MOUSE_BIND_RPC_ID, SifRpcClientData_t::server, and SifBindRpc().
PS2MouseRead()
int PS2MouseRead (PS2MouseData * data)
Reads the current mouse data (depending on read mode)
Definition at line 64 of file libmouse.c.
 {
   u8* uncached = UNCACHED_SEG(buffer.buffer);
   if(!data)
     {
       return -1;
     }
   if (SifCallRpc(&mouseif, PS2MOUSE_READ, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
     return -1;
   memcpy(data, uncached, sizeof(PS2MouseData));
   //  printf("MouseRead %d %d %d %d\n", data->x, data->y, data->wheel, data->buttons);
   return 1;
 }
References buffer, data, mouseif, NULL, PS2MOUSE_READ, SifCallRpc(), and UNCACHED_SEG.
PS2MouseReset()
int PS2MouseReset ()
Definition at line 196 of file libmouse.c.
 {
   if (SifCallRpc(&mouseif, PS2MOUSE_RESET, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
     return -1;
   return 1;
 }
References buffer, mouseif, NULL, PS2MOUSE_RESET, and SifCallRpc().
PS2MouseSetAccel()
int PS2MouseSetAccel (float accel)
Definition at line 125 of file libmouse.c.
 {
   u32 accel_fixed;
   if(accel < 0) return -1;
   accel_fixed = (u32) (accel * 65536.0);
   buffer.accel = accel_fixed;
   if (SifCallRpc(&mouseif, PS2MOUSE_SETACCEL, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
     return -1;
   return 1;
 }
References accel, buffer, mouseif, NULL, PS2MOUSE_SETACCEL, and SifCallRpc().
PS2MouseSetBoundary()
int PS2MouseSetBoundary (int minx, int maxx, int miny, int maxy)
Definition at line 154 of file libmouse.c.
 {
   buffer.bounds.minx = minx;
   buffer.bounds.maxx = maxx;
   buffer.bounds.miny = miny;
   buffer.bounds.maxy = maxy;
   if (SifCallRpc(&mouseif, PS2MOUSE_SETBOUNDARY, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
     return -1;
   return 1;
 }
References buffer, maxx, maxy, minx, miny, mouseif, NULL, PS2MOUSE_SETBOUNDARY, and SifCallRpc().
PS2MouseSetDblClickTime()
int PS2MouseSetDblClickTime (u32 msec)
Definition at line 227 of file libmouse.c.
 {
   buffer.time = msec;
   if (SifCallRpc(&mouseif, PS2MOUSE_SETDBLCLICKTIME, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
     return -1;
   return 1;
 }
References buffer, mouseif, NULL, PS2MOUSE_SETDBLCLICKTIME, and SifCallRpc().
PS2MouseSetPosition()
int PS2MouseSetPosition (int x, int y)
Definition at line 184 of file libmouse.c.
 {
   buffer.pos.x = x;
   buffer.pos.y = y;
   if (SifCallRpc(&mouseif, PS2MOUSE_SETPOSITION, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
     return -1;
   return 1;
 }
References buffer, mouseif, NULL, PS2MOUSE_SETPOSITION, SifCallRpc(), x, and y.
PS2MouseSetReadMode()
int PS2MouseSetReadMode (u32 readMode)
Sets the read mode
Definition at line 84 of file libmouse.c.
 {
   buffer.mode = readMode;
   if (SifCallRpc(&mouseif, PS2MOUSE_SETREADMODE, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
     return -1;
   return 1;
 }
References buffer, mouseif, NULL, PS2MOUSE_SETREADMODE, and SifCallRpc().
PS2MouseSetThres()
int PS2MouseSetThres (u32 thres)
Definition at line 105 of file libmouse.c.
 {
   buffer.thres = thres;
   if (SifCallRpc(&mouseif, PS2MOUSE_SETTHRES, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
     return -1;
   return 1;
 }
References buffer, mouseif, NULL, PS2MOUSE_SETTHRES, SifCallRpc(), and thres.