ps2sdk: ee/rpc/multitap/src/libmtap.c File Reference
libmtap.c File Reference
#include <tamtypes.h>
#include <string.h>
#include <kernel.h>
#include <sifrpc.h>
#include <stdarg.h>
#include "libmtap.h"
Macros
#define MTAPSERV_PORT_OPEN 0x80000901
#define MTAPSERV_PORT_CLOSE 0x80000902
#define MTAPSERV_GET_CONNECTION 0x80000903
Functions
int mtapInit (void)
int mtapPortOpen (int port)
int mtapPortClose (int port)
int mtapGetConnection (int port)
Variables
static unsigned int mtapRpcBuffer [32]
static struct t_SifRpcClientData clientPortOpen
static struct t_SifRpcClientData clientPortClose
static struct t_SifRpcClientData clientGetConnection
static int mtapInited = 0
Detailed Description
Functions to provide access to multi-taps.
Definition in file libmtap.c.
Macro Definition Documentation
MTAPSERV_GET_CONNECTION
#define MTAPSERV_GET_CONNECTION 0x80000903
Definition at line 26 of file libmtap.c.
MTAPSERV_PORT_CLOSE
#define MTAPSERV_PORT_CLOSE 0x80000902
Definition at line 25 of file libmtap.c.
MTAPSERV_PORT_OPEN
#define MTAPSERV_PORT_OPEN 0x80000901
Definition at line 24 of file libmtap.c.
Function Documentation
mtapGetConnection()
int mtapGetConnection (int port)
Checks if a multitap is connected to an opened port.
Parameters
port is the port to be checked.
Returns
1 if a multitap exists on the specified port; !1 if there isno multitap on the specified port.
Definition at line 87 of file libmtap.c.
 {
         if(!mtapInited) return -1;
         mtapRpcBuffer[0] = port;
         SifCallRpc(&clientGetConnection, 1, 0, mtapRpcBuffer, 4, mtapRpcBuffer, 8, NULL, NULL);
         return mtapRpcBuffer[1];
 }
References clientGetConnection, mtapInited, mtapRpcBuffer, NULL, port, and SifCallRpc().
Referenced by find_controllers(), and pad_open().
mtapInit()
int mtapInit (void)
Initialise the multitap library.
Returns
1 on success; 1 on failure
Definition at line 34 of file libmtap.c.
 {
         if(mtapInited) return -1;
         while(1)
         {
                 if (SifBindRpc(&clientPortOpen, MTAPSERV_PORT_OPEN, 0) < 0) return -1;
                 if (clientPortOpen.server != 0) break;
         nopdelay();
         }
         while(1)
         {
                 if (SifBindRpc(&clientPortClose, MTAPSERV_PORT_CLOSE, 0) < 0) return -1;
                 if (clientPortClose.server != 0) break;
         nopdelay();
         }
         while(1)
         {
                 if (SifBindRpc(&clientGetConnection, MTAPSERV_GET_CONNECTION, 0) < 0) return -1;
                 if (clientGetConnection.server != 0) break;
         nopdelay();
         }
         mtapInited = 1;
         return 1;
 }
References clientGetConnection, clientPortClose, clientPortOpen, mtapInited, MTAPSERV_GET_CONNECTION, MTAPSERV_PORT_CLOSE, MTAPSERV_PORT_OPEN, nopdelay(), and SifBindRpc().
Referenced by main().
mtapPortClose()
int mtapPortClose (int port)
Closes a port for the multitap.
Parameters
port is a port that is to be closed (must have been previously opened by mtapPortOpen).
Returns
1 on success; !1 on failure.
Definition at line 77 of file libmtap.c.
 {
         if(!mtapInited) return -1;
         mtapRpcBuffer[0] = port;
         SifCallRpc(&clientPortClose, 1, 0, mtapRpcBuffer, 4, mtapRpcBuffer, 8, NULL, NULL);
         return mtapRpcBuffer[1];
 }
References clientPortClose, mtapInited, mtapRpcBuffer, NULL, port, and SifCallRpc().
mtapPortOpen()
int mtapPortOpen (int port)
Open a port for the multitap.
Parameters
port specifies the port that is to be monitored as a multitap connection destination.
Returns
1 on success; !1 on failure.
Definition at line 67 of file libmtap.c.
 {
         if(!mtapInited) return -1;
         mtapRpcBuffer[0] = port;
         SifCallRpc(&clientPortOpen, 1, 0, mtapRpcBuffer, 4, mtapRpcBuffer, 8, NULL, NULL);
         return mtapRpcBuffer[1];
 }
References clientPortOpen, mtapInited, mtapRpcBuffer, NULL, port, and SifCallRpc().
Referenced by main().
Variable Documentation
clientGetConnection
struct t_SifRpcClientData clientGetConnection static
Definition at line 28 of file libmtap.c.
Referenced by mtapGetConnection(), and mtapInit().
clientPortClose
struct t_SifRpcClientData clientPortClose static
Definition at line 28 of file libmtap.c.
Referenced by mtapInit(), and mtapPortClose().
clientPortOpen
struct t_SifRpcClientData clientPortOpen static
Definition at line 28 of file libmtap.c.
Referenced by mtapInit(), and mtapPortOpen().
mtapInited
int mtapInited = 0 static
Definition at line 32 of file libmtap.c.
Referenced by mtapGetConnection(), mtapInit(), mtapPortClose(), and mtapPortOpen().
mtapRpcBuffer
unsigned int mtapRpcBuffer[32] static
Definition at line 28 of file libmtap.c.
Referenced by mtapGetConnection(), mtapPortClose(), and mtapPortOpen().