ps2sdk: ee/mpeg/src/libmpeg_internal.h File Reference
libmpeg_internal.h File Reference
#include <libmpeg.h>
Data Structures
struct _MPEGMBXY
struct _MPEGMacroBlock8
struct _MPEGMotion
struct _MPEGMotions
struct _MPEGContext
Macros
#define _MPEG_PT_I 1
#define _MPEG_PT_P 2
#define _MPEG_PT_B 3
#define _MPEG_PT_D 4
#define _MPEG_PS_TOP_FIELD 1
#define _MPEG_PS_BOTTOM_FIELD 2
#define _MPEG_PS_FRAME 3
#define _MPEG_MBT_INTRA 1
#define _MPEG_MBT_PATTERN 2
#define _MPEG_MBT_MOTION_BACKWARD 4
#define _MPEG_MBT_MOTION_FORWARD 8
#define _MPEG_MBT_QUANT 16
#define _MPEG_MC_FIELD 1
#define _MPEG_MC_FRAME 2
#define _MPEG_MC_16X8 2
#define _MPEG_MC_DMV 3
#define _MPEG_MV_FIELD 0
#define _MPEG_MV_FRAME 1
#define _MPEG_CODE_PIC_START 0x00000100
#define _MPEG_CODE_SLICE_MIN 0x00000101
#define _MPEG_CODE_SLICE_MAX 0x000001AF
#define _MPEG_CODE_USER_DATA 0x000001B2
#define _MPEG_CODE_SEQ_HDR 0x000001B3
#define _MPEG_CODE_EXTENSION 0x000001B5
#define _MPEG_CODE_SEQ_END 0x000001B7
#define _MPEG_CODE_GRP_START 0x000001B8
#define _MPEG_XID_0 0
#define _MPEG_XID_SEQUENCE 1
#define _MPEG_XID_DISPLAY 2
#define _MPEG_XID_QMATRIX 3
#define _MPEG_XID_COPYRIGHT 4
#define _MPEG_XID_SCALABLE 5
#define _MPEG_XID_6 6
#define _MPEG_XID_PIC_DSP 7
#define _MPEG_XID_PIC_COD 8
#define _MPEG_XID_PIC_SSC 9
#define _MPEG_XID_PIC_TSC 10
Functions
void _MPEG_Initialize (_MPEGContext *, int(*)(void *), void *, int *)
void _MPEG_Destroy (void)
int _MPEG_CSCImage (void *, void *, int)
void _MPEG_SetDefQM (int)
void _MPEG_SetQM (int)
int _MPEG_GetMBAI (void)
int _MPEG_GetMBType (void)
int _MPEG_GetMotionCode (void)
int _MPEG_GetDMVector (void)
unsigned int _MPEG_NextStartCode (void)
void _MPEG_AlignBits (void)
unsigned int _MPEG_GetBits (unsigned int)
unsigned int _MPEG_ShowBits (unsigned int)
void _MPEG_SetIDCP (void)
void _MPEG_SetQSTIVFAS (void)
void _MPEG_SetPCT (unsigned int)
void _MPEG_BDEC (int, int, int, int, void *)
int _MPEG_WaitBDEC (void)
void _MPEG_dma_ref_image (_MPEGMacroBlock8 *, _MPEGMotion *, int, int)
void _MPEG_do_mc (_MPEGMotion *)
void _MPEG_put_luma (_MPEGMotion *)
void _MPEG_put_luma_X (_MPEGMotion *)
void _MPEG_put_luma_Y (_MPEGMotion *)
void _MPEG_put_luma_XY (_MPEGMotion *)
void _MPEG_put_chroma (void)
void _MPEG_put_chroma_X (void)
void _MPEG_put_chroma_Y (void)
void _MPEG_put_chroma_XY (void)
void _MPEG_avg_luma (_MPEGMotion *)
void _MPEG_avg_luma_X (_MPEGMotion *)
void _MPEG_avg_luma_Y (_MPEGMotion *)
void _MPEG_avg_luma_XY (_MPEGMotion *)
void _MPEG_avg_chroma (void)
void _MPEG_avg_chroma_X (void)
void _MPEG_avg_chroma_Y (void)
void _MPEG_avg_chroma_XY (void)
void _MPEG_put_block_fr (_MPEGMotions *)
void _MPEG_put_block_fl (_MPEGMotions *)
void _MPEG_put_block_il (_MPEGMotions *)
void _MPEG_add_block_ilfl (_MPEGMotions *)
void _MPEG_add_block_frfr (_MPEGMotions *)
void _MPEG_add_block_frfl (_MPEGMotions *)
void _MPEG_Suspend (void)
void _MPEG_Resume (void)
Detailed Description
MPEG decoding internal functions.
Definition in file libmpeg_internal.h.
Macro Definition Documentation
_MPEG_CODE_EXTENSION
#define _MPEG_CODE_EXTENSION 0x000001B5
Definition at line 49 of file libmpeg_internal.h.
_MPEG_CODE_GRP_START
#define _MPEG_CODE_GRP_START 0x000001B8
Definition at line 51 of file libmpeg_internal.h.
_MPEG_CODE_PIC_START
#define _MPEG_CODE_PIC_START 0x00000100
Definition at line 44 of file libmpeg_internal.h.
_MPEG_CODE_SEQ_END
#define _MPEG_CODE_SEQ_END 0x000001B7
Definition at line 50 of file libmpeg_internal.h.
_MPEG_CODE_SEQ_HDR
#define _MPEG_CODE_SEQ_HDR 0x000001B3
Definition at line 48 of file libmpeg_internal.h.
_MPEG_CODE_SLICE_MAX
#define _MPEG_CODE_SLICE_MAX 0x000001AF
Definition at line 46 of file libmpeg_internal.h.
_MPEG_CODE_SLICE_MIN
#define _MPEG_CODE_SLICE_MIN 0x00000101
Definition at line 45 of file libmpeg_internal.h.
_MPEG_CODE_USER_DATA
#define _MPEG_CODE_USER_DATA 0x000001B2
Definition at line 47 of file libmpeg_internal.h.
_MPEG_MBT_INTRA
#define _MPEG_MBT_INTRA 1
Definition at line 30 of file libmpeg_internal.h.
_MPEG_MBT_MOTION_BACKWARD
#define _MPEG_MBT_MOTION_BACKWARD 4
Definition at line 32 of file libmpeg_internal.h.
_MPEG_MBT_MOTION_FORWARD
#define _MPEG_MBT_MOTION_FORWARD 8
Definition at line 33 of file libmpeg_internal.h.
_MPEG_MBT_PATTERN
#define _MPEG_MBT_PATTERN 2
Definition at line 31 of file libmpeg_internal.h.
_MPEG_MBT_QUANT
#define _MPEG_MBT_QUANT 16
Definition at line 34 of file libmpeg_internal.h.
_MPEG_MC_16X8
#define _MPEG_MC_16X8 2
Definition at line 38 of file libmpeg_internal.h.
_MPEG_MC_DMV
#define _MPEG_MC_DMV 3
Definition at line 39 of file libmpeg_internal.h.
_MPEG_MC_FIELD
#define _MPEG_MC_FIELD 1
Definition at line 36 of file libmpeg_internal.h.
_MPEG_MC_FRAME
#define _MPEG_MC_FRAME 2
Definition at line 37 of file libmpeg_internal.h.
_MPEG_MV_FIELD
#define _MPEG_MV_FIELD 0
Definition at line 41 of file libmpeg_internal.h.
_MPEG_MV_FRAME
#define _MPEG_MV_FRAME 1
Definition at line 42 of file libmpeg_internal.h.
_MPEG_PS_BOTTOM_FIELD
#define _MPEG_PS_BOTTOM_FIELD 2
Definition at line 27 of file libmpeg_internal.h.
_MPEG_PS_FRAME
#define _MPEG_PS_FRAME 3
Definition at line 28 of file libmpeg_internal.h.
_MPEG_PS_TOP_FIELD
#define _MPEG_PS_TOP_FIELD 1
Definition at line 26 of file libmpeg_internal.h.
_MPEG_PT_B
#define _MPEG_PT_B 3
Definition at line 23 of file libmpeg_internal.h.
_MPEG_PT_D
#define _MPEG_PT_D 4
Definition at line 24 of file libmpeg_internal.h.
_MPEG_PT_I
#define _MPEG_PT_I 1
Definition at line 21 of file libmpeg_internal.h.
_MPEG_PT_P
#define _MPEG_PT_P 2
Definition at line 22 of file libmpeg_internal.h.
_MPEG_XID_0
#define _MPEG_XID_0 0
Definition at line 53 of file libmpeg_internal.h.
_MPEG_XID_6
#define _MPEG_XID_6 6
Definition at line 59 of file libmpeg_internal.h.
_MPEG_XID_COPYRIGHT
#define _MPEG_XID_COPYRIGHT 4
Definition at line 57 of file libmpeg_internal.h.
_MPEG_XID_DISPLAY
#define _MPEG_XID_DISPLAY 2
Definition at line 55 of file libmpeg_internal.h.
_MPEG_XID_PIC_COD
#define _MPEG_XID_PIC_COD 8
Definition at line 61 of file libmpeg_internal.h.
_MPEG_XID_PIC_DSP
#define _MPEG_XID_PIC_DSP 7
Definition at line 60 of file libmpeg_internal.h.
_MPEG_XID_PIC_SSC
#define _MPEG_XID_PIC_SSC 9
Definition at line 62 of file libmpeg_internal.h.
_MPEG_XID_PIC_TSC
#define _MPEG_XID_PIC_TSC 10
Definition at line 63 of file libmpeg_internal.h.
_MPEG_XID_QMATRIX
#define _MPEG_XID_QMATRIX 3
Definition at line 56 of file libmpeg_internal.h.
_MPEG_XID_SCALABLE
#define _MPEG_XID_SCALABLE 5
Definition at line 58 of file libmpeg_internal.h.
_MPEG_XID_SEQUENCE
#define _MPEG_XID_SEQUENCE 1
Definition at line 54 of file libmpeg_internal.h.
Function Documentation
_MPEG_add_block_frfl()
void _MPEG_add_block_frfl (_MPEGMotions *)
_MPEG_add_block_frfr()
void _MPEG_add_block_frfr (_MPEGMotions *)
_MPEG_add_block_ilfl()
void _MPEG_add_block_ilfl (_MPEGMotions *)
_MPEG_AlignBits()
void _MPEG_AlignBits (void)
_MPEG_avg_chroma()
void _MPEG_avg_chroma (void)
_MPEG_avg_chroma_X()
void _MPEG_avg_chroma_X (void)
_MPEG_avg_chroma_XY()
void _MPEG_avg_chroma_XY (void)
_MPEG_avg_chroma_Y()
void _MPEG_avg_chroma_Y (void)
_MPEG_avg_luma()
void _MPEG_avg_luma (_MPEGMotion *)
_MPEG_avg_luma_X()
void _MPEG_avg_luma_X (_MPEGMotion *)
_MPEG_avg_luma_XY()
void _MPEG_avg_luma_XY (_MPEGMotion *)
_MPEG_avg_luma_Y()
void _MPEG_avg_luma_Y (_MPEGMotion *)
_MPEG_BDEC()
void _MPEG_BDEC (int , int , int , int , void *)
Referenced by _mpeg12_dec_mb().
_MPEG_CSCImage()
int _MPEG_CSCImage (void * , void * , int)
Referenced by _get_next_picture().
_MPEG_Destroy()
void _MPEG_Destroy (void)
Referenced by MPEG_Destroy().
_MPEG_dma_ref_image()
void _MPEG_dma_ref_image (_MPEGMacroBlock8 * , _MPEGMotion * , int , int)
Referenced by _mpeg12_get_refs().
_MPEG_do_mc()
void _MPEG_do_mc (_MPEGMotion *)
Referenced by _mpeg12_do_next_mc().
_MPEG_GetBits()
unsigned int _MPEG_GetBits (unsigned int)
Referenced by _ext_and_ud(), _ext_cpy_rgt(), _ext_pic_cod(), _ext_pic_dsp(), _ext_qnt_mtx(), _ext_seq(), _ext_seq_dsp(), _get_hdr(), _gop_header(), _mpeg12_dec_mb(), _mpeg12_motion_vector(), _mpeg12_motion_vectors(), _mpeg12_slice(), _pic_header(), _seq_header(), and _xtra_bitinf().
_MPEG_GetDMVector()
int _MPEG_GetDMVector (void)
Referenced by _mpeg12_motion_vector().
_MPEG_GetMBAI()
int _MPEG_GetMBAI (void)
Referenced by _mpeg12_slice().
_MPEG_GetMBType()
int _MPEG_GetMBType (void)
Referenced by _mpeg12_dec_mb().
_MPEG_GetMotionCode()
int _MPEG_GetMotionCode (void)
Referenced by _mpeg12_motion_vector().
_MPEG_Initialize()
void _MPEG_Initialize (_MPEGContext * , int(*)(void *) , void * , int *)
Referenced by MPEG_Initialize().
_MPEG_NextStartCode()
unsigned int _MPEG_NextStartCode (void)
Referenced by _ext_and_ud(), _get_hdr(), and _mpeg12_slice().
_MPEG_put_block_fl()
void _MPEG_put_block_fl (_MPEGMotions *)
_MPEG_put_block_fr()
void _MPEG_put_block_fr (_MPEGMotions *)
_MPEG_put_block_il()
void _MPEG_put_block_il (_MPEGMotions *)
_MPEG_put_chroma()
void _MPEG_put_chroma (void)
_MPEG_put_chroma_X()
void _MPEG_put_chroma_X (void)
_MPEG_put_chroma_XY()
void _MPEG_put_chroma_XY (void)
_MPEG_put_chroma_Y()
void _MPEG_put_chroma_Y (void)
_MPEG_put_luma()
void _MPEG_put_luma (_MPEGMotion *)
_MPEG_put_luma_X()
void _MPEG_put_luma_X (_MPEGMotion *)
_MPEG_put_luma_XY()
void _MPEG_put_luma_XY (_MPEGMotion *)
_MPEG_put_luma_Y()
void _MPEG_put_luma_Y (_MPEGMotion *)
_MPEG_Resume()
void _MPEG_Resume (void)
_MPEG_SetDefQM()
void _MPEG_SetDefQM (int)
Referenced by _seq_header().
_MPEG_SetIDCP()
void _MPEG_SetIDCP (void)
Referenced by _ext_pic_cod().
_MPEG_SetPCT()
void _MPEG_SetPCT (unsigned int)
Referenced by _pic_header().
_MPEG_SetQM()
void _MPEG_SetQM (int)
Referenced by _ext_qnt_mtx(), and _seq_header().
_MPEG_SetQSTIVFAS()
void _MPEG_SetQSTIVFAS (void)
Referenced by _ext_pic_cod().
_MPEG_ShowBits()
unsigned int _MPEG_ShowBits (unsigned int)
Referenced by _mpeg12_slice().
_MPEG_Suspend()
void _MPEG_Suspend (void)
_MPEG_WaitBDEC()
int _MPEG_WaitBDEC (void)
Referenced by _mpeg12_picture_data(), and _mpeg12_slice().