ps2sdk: ee/kernel/src/libosd.c File Reference
libosd.c File Reference
#include <kernel.h>
#include <syscallnr.h>
#include <osd_config.h>
Data Structures
struct SyscallData
Functions
void InitExecPS2 (void)
Variables
unsigned char osdsrc []
unsigned int size_osdsrc
static struct SyscallData SyscallPatchEntries []
Detailed Description
libosd - ExecPS2 update.
Applicable to only the SCPH-10000 and SCPH-15000. Both contain either boot ROM v1.00 or v1.01. This is the "lite" libosd update will replace only ExecPS2, as done by games.
Definition in file libosd.c.
Function Documentation
InitExecPS2()
void InitExecPS2 (void)
Definition at line 47 of file libosd.c.
                       {
         unsigned int i;
         if(PatchIsNeeded()){
                 setup(SyscallPatchEntries[0].syscall_num, SyscallPatchEntries[0].function);
                 Copy((unsigned int*)0x80074000, (unsigned int*)osdsrc, size_osdsrc);
                 FlushCache(0);
                 FlushCache(2);
                 setup(SyscallPatchEntries[1].syscall_num, SyscallPatchEntries[1].function);
                 for(i=2; i<3; i++){
                         setup(SyscallPatchEntries[i].syscall_num, GetEntryAddress(SyscallPatchEntries[i].syscall_num));
                 }
         }
 }
References Copy(), FlushCache(), GetEntryAddress(), osdsrc, PatchIsNeeded(), setup(), size_osdsrc, SyscallData::syscall_num, and SyscallPatchEntries.
Variable Documentation
osdsrc
unsigned char osdsrc[] extern
Referenced by InitExecPS2().
size_osdsrc
unsigned int size_osdsrc extern
Referenced by InitExecPS2().
SyscallPatchEntries
struct SyscallData SyscallPatchEntries[] static
Initial value:
={
        {
                0x5A,
                &kCopy
        },
        {
                0x5B,
                (void*)0x80074000
        },
        {
                0xFFFFC402,
                NULL
        },
}
Definition at line 24 of file libosd.c.
Referenced by InitExecPS2().