ps2sdk: ee/kernel/src/libosd_common.c File Reference
libosd_common.c File Reference
#include <kernel.h>
#include <syscallnr.h>
#include <osd_config.h>
Functions
int PatchIsNeeded (void)
Detailed Description
libosd support functions
Definition in file libosd_common.c.
Function Documentation
PatchIsNeeded()
int PatchIsNeeded (void)
Definition at line 20 of file libosd_common.c.
{
         ConfigParam original_config, config;
         GetOsdConfigParam(&original_config);
         config=original_config;
         config.version=1;       //Protokernels cannot retain values set in this field.
         SetOsdConfigParam(&config);
         GetOsdConfigParam(&config);
         SetOsdConfigParam(&original_config);
         return(config.version<1);
 }
References GetOsdConfigParam(), SetOsdConfigParam(), and ConfigParam::version.
Referenced by InitExecPS2(), and InitOsd().