ps2sdk: ee/rpc/pad/include/libpad.h File Reference
libpad.h File Reference
Data Structures
struct padButtonStatus
Macros
#define PAD_LEFT 0x0080
#define PAD_DOWN 0x0040
#define PAD_RIGHT 0x0020
#define PAD_UP 0x0010
#define PAD_START 0x0008
#define PAD_R3 0x0004
#define PAD_L3 0x0002
#define PAD_SELECT 0x0001
#define PAD_SQUARE 0x8000
#define PAD_CROSS 0x4000
#define PAD_CIRCLE 0x2000
#define PAD_TRIANGLE 0x1000
#define PAD_R1 0x0800
#define PAD_L1 0x0400
#define PAD_R2 0x0200
#define PAD_L2 0x0100
#define PAD_STATE_DISCONN 0x00
#define PAD_STATE_FINDPAD 0x01
#define PAD_STATE_FINDCTP1 0x02
#define PAD_STATE_EXECCMD 0x05
#define PAD_STATE_STABLE 0x06
#define PAD_STATE_ERROR 0x07
#define PAD_RSTAT_COMPLETE 0x00
#define PAD_RSTAT_FAILED 0x01
#define PAD_RSTAT_BUSY 0x02
#define PAD_TYPE_NEJICON 0x2
#define PAD_TYPE_KONAMIGUN 0x3
#define PAD_TYPE_DIGITAL 0x4
#define PAD_TYPE_ANALOG 0x5
#define PAD_TYPE_NAMCOGUN 0x6
#define PAD_TYPE_DUALSHOCK 0x7
#define PAD_TYPE_JOGCON 0xE
#define PAD_TYPE_EX_TSURICON 0x100
#define PAD_TYPE_EX_JOGCON 0x300
#define PAD_MODECURID 1
#define PAD_MODECUREXID 2
#define PAD_MODECUROFFS 3
#define PAD_MODETABLE 4
#define PAD_MMODE_DIGITAL 0
#define PAD_MMODE_DUALSHOCK 1
#define PAD_MMODE_UNLOCK 2
#define PAD_MMODE_LOCK 3
#define PAD_ACTFUNC 1
#define PAD_ACTSUB 2
#define PAD_ACTSIZE 3
#define PAD_ACTCURR 4
Functions
int padInit (int mode)
int padPortInit (int mode)
int padEnd (void)
int padPortOpen (int port, int slot, void *padArea)
int padPortClose (int port, int slot)
unsigned char padRead (int port, int slot, struct padButtonStatus *data)
int padGetState (int port, int slot)
unsigned char padGetReqState (int port, int slot)
int padSetReqState (int port, int slot, int state)
void padStateInt2String (int state, char buf[16])
void padReqStateInt2String (int state, char buf[16])
int padGetPortMax (void)
int padGetSlotMax (int port)
int padGetModVersion ()
int padInfoMode (int port, int slot, int infoMode, int index)
int padSetMainMode (int port, int slot, int mode, int lock)
int padInfoPressMode (int port, int slot)
int padEnterPressMode (int port, int slot)
int padExitPressMode (int port, int slot)
int padGetButtonMask (int port, int slot)
int padSetButtonInfo (int port, int slot, int buttonInfo)
unsigned char padInfoAct (int port, int slot, int word, int byte)
int padSetActAlign (int port, int slot, char act_align[6])
int padSetActDirect (int port, int slot, char act_align[6])
int padGetConnection (int port, int slot)
Detailed Description
Pad externals
Definition in file libpad.h.
Macro Definition Documentation
PAD_ACTCURR
#define PAD_ACTCURR 4
Definition at line 92 of file libpad.h.
PAD_ACTFUNC
#define PAD_ACTFUNC 1
Definition at line 89 of file libpad.h.
PAD_ACTSIZE
#define PAD_ACTSIZE 3
Definition at line 91 of file libpad.h.
PAD_ACTSUB
#define PAD_ACTSUB 2
Definition at line 90 of file libpad.h.
PAD_CIRCLE
#define PAD_CIRCLE 0x2000
Definition at line 33 of file libpad.h.
PAD_CROSS
#define PAD_CROSS 0x4000
Definition at line 32 of file libpad.h.
PAD_DOWN
#define PAD_DOWN 0x0040
Definition at line 24 of file libpad.h.
PAD_L1
#define PAD_L1 0x0400
Definition at line 36 of file libpad.h.
PAD_L2
#define PAD_L2 0x0100
Definition at line 38 of file libpad.h.
PAD_L3
#define PAD_L3 0x0002
Definition at line 29 of file libpad.h.
PAD_LEFT
#define PAD_LEFT 0x0080
Definition at line 23 of file libpad.h.
PAD_MMODE_DIGITAL
#define PAD_MMODE_DIGITAL 0
Definition at line 80 of file libpad.h.
PAD_MMODE_DUALSHOCK
#define PAD_MMODE_DUALSHOCK 1
Definition at line 81 of file libpad.h.
PAD_MMODE_LOCK
#define PAD_MMODE_LOCK 3
Definition at line 84 of file libpad.h.
PAD_MMODE_UNLOCK
#define PAD_MMODE_UNLOCK 2
Definition at line 83 of file libpad.h.
PAD_MODECUREXID
#define PAD_MODECUREXID 2
Definition at line 73 of file libpad.h.
PAD_MODECURID
#define PAD_MODECURID 1
Definition at line 72 of file libpad.h.
PAD_MODECUROFFS
#define PAD_MODECUROFFS 3
Definition at line 74 of file libpad.h.
PAD_MODETABLE
#define PAD_MODETABLE 4
Definition at line 75 of file libpad.h.
PAD_R1
#define PAD_R1 0x0800
Definition at line 35 of file libpad.h.
PAD_R2
#define PAD_R2 0x0200
Definition at line 37 of file libpad.h.
PAD_R3
#define PAD_R3 0x0004
Definition at line 28 of file libpad.h.
PAD_RIGHT
#define PAD_RIGHT 0x0020
Definition at line 25 of file libpad.h.
PAD_RSTAT_BUSY
#define PAD_RSTAT_BUSY 0x02
Definition at line 55 of file libpad.h.
PAD_RSTAT_COMPLETE
#define PAD_RSTAT_COMPLETE 0x00
Definition at line 53 of file libpad.h.
PAD_RSTAT_FAILED
#define PAD_RSTAT_FAILED 0x01
Definition at line 54 of file libpad.h.
PAD_SELECT
#define PAD_SELECT 0x0001
Definition at line 30 of file libpad.h.
PAD_SQUARE
#define PAD_SQUARE 0x8000
Definition at line 31 of file libpad.h.
PAD_START
#define PAD_START 0x0008
Definition at line 27 of file libpad.h.
PAD_STATE_DISCONN
#define PAD_STATE_DISCONN 0x00
Definition at line 43 of file libpad.h.
PAD_STATE_ERROR
#define PAD_STATE_ERROR 0x07
Definition at line 48 of file libpad.h.
PAD_STATE_EXECCMD
#define PAD_STATE_EXECCMD 0x05
Definition at line 46 of file libpad.h.
PAD_STATE_FINDCTP1
#define PAD_STATE_FINDCTP1 0x02
Definition at line 45 of file libpad.h.
PAD_STATE_FINDPAD
#define PAD_STATE_FINDPAD 0x01
Definition at line 44 of file libpad.h.
PAD_STATE_STABLE
#define PAD_STATE_STABLE 0x06
Definition at line 47 of file libpad.h.
PAD_TRIANGLE
#define PAD_TRIANGLE 0x1000
Definition at line 34 of file libpad.h.
PAD_TYPE_ANALOG
#define PAD_TYPE_ANALOG 0x5
Definition at line 63 of file libpad.h.
PAD_TYPE_DIGITAL
#define PAD_TYPE_DIGITAL 0x4
Definition at line 62 of file libpad.h.
PAD_TYPE_DUALSHOCK
#define PAD_TYPE_DUALSHOCK 0x7
Definition at line 65 of file libpad.h.
PAD_TYPE_EX_JOGCON
#define PAD_TYPE_EX_JOGCON 0x300
Definition at line 68 of file libpad.h.
PAD_TYPE_EX_TSURICON
#define PAD_TYPE_EX_TSURICON 0x100
Definition at line 67 of file libpad.h.
PAD_TYPE_JOGCON
#define PAD_TYPE_JOGCON 0xE
Definition at line 66 of file libpad.h.
PAD_TYPE_KONAMIGUN
#define PAD_TYPE_KONAMIGUN 0x3
Definition at line 61 of file libpad.h.
PAD_TYPE_NAMCOGUN
#define PAD_TYPE_NAMCOGUN 0x6
Definition at line 64 of file libpad.h.
PAD_TYPE_NEJICON
#define PAD_TYPE_NEJICON 0x2
Definition at line 60 of file libpad.h.
PAD_UP
#define PAD_UP 0x0010
Definition at line 26 of file libpad.h.
Function Documentation
padEnd()
int padEnd (void)
Ends all pad communication Note: PADMAN from release 1.3.4 does not have padPortInit implemented. As a result, it is impossible to reinitialize libpad after calling padEnd(). This was known as padClose in the really early official SDK releases.
Returns
== 1 => OK
Definition at line 372 of file libpad.c.
 {
     int ret;
     buffer.command=PAD_RPCCMD_END;
     if (SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
         return -1;
     ret = buffer.padResult.result;
     if (ret == 1) {
         padInitialised = 0;
     }
     return ret;
 }
References buffer, NULL, PAD_RPCCMD_END, padInitialised, padsif, and SifCallRpc().
padEnterPressMode()
int padEnterPressMode (int port, int slot)
Pressure sensitive mode ON
Definition at line 690 of file libpad.c.
 {
     return padSetButtonInfo(port, slot, 0xFFF);
 }
References padSetButtonInfo(), port, and slot.
Referenced by initializePad(), main(), and pad_set_sensitivity().
padExitPressMode()
int padExitPressMode (int port, int slot)
Check for newer version Pressure sensitive mode OFF
Definition at line 696 of file libpad.c.
 {
     return padSetButtonInfo(port, slot, 0);
 }
References padSetButtonInfo(), port, and slot.
Referenced by main(), and pad_set_sensitivity().
padGetButtonMask()
int padGetButtonMask (int port, int slot)
Definition at line 703 of file libpad.c.
 {
         buffer.padGetButtonMaskArgs.command = PAD_RPCCMD_GET_BTNMASK;
         buffer.padGetButtonMaskArgs.port = port;
         buffer.padGetButtonMaskArgs.slot = slot;
     if (SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
         return 0;
     return buffer.padResult.result;
 }
References buffer, NULL, PAD_RPCCMD_GET_BTNMASK, padsif, port, SifCallRpc(), and slot.
Referenced by padInfoPressMode().
padGetConnection()
int padGetConnection (int port, int slot)
Returns whether the device at port,slot is connected (1 = connected) Appears to have been removed very early during the PS2's lifetime. If possible, use the documented padGetState instead.
NOT SUPPORTED with module rom0:padman
Definition at line 823 of file libpad.c.
 {
 #ifdef _XPAD
     struct open_slot *oslot;
     oslot = padGetConnDmaStr();
     return ((oslot->openSlots[port] >> slot) & 0x1);
 #else
     return 1;
 #endif
 }
References port, and slot.
padGetModVersion()
int padGetModVersion ()
Returns the padman.irx version NOT SUPPORTED on module rom0:padman
Definition at line 573 of file libpad.c.
 {
 #ifdef _XPAD
     buffer.command = PAD_RPCCMD_GET_MODVER;
     if (SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
         return -1;
     return buffer.padResult.result;
 #else
     return 1; // Well.. return a low version #
 #endif
 }
References buffer, NULL, padsif, and SifCallRpc().
padGetPortMax()
int padGetPortMax (void)
Returns # slots on the PS2 (usally 2)
Definition at line 548 of file libpad.c.
 {
         buffer.command = PAD_RPCCMD_GET_PORTMAX;
     if (SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
         return -1;
     return buffer.padResult.result;
 }
References buffer, NULL, PAD_RPCCMD_GET_PORTMAX, padsif, and SifCallRpc().
Referenced by main().
padGetReqState()
unsigned char padGetReqState (int port, int slot)
Get pad request state
Definition at line 511 of file libpad.c.
 {
     struct pad_data *pdata;
     pdata = padGetDmaStr(port, slot);
     return pdata->reqState;
 }
References padGetDmaStr(), port, pad_data::reqState, and slot.
Referenced by padGetState(), and padWait().
padGetSlotMax()
int padGetSlotMax (int port)
Returns # slots the port has (usually 1) probably 4 if using a multi tap (not tested)
Definition at line 560 of file libpad.c.
 {
     buffer.padSlotMaxArgs.command = PAD_RPCCMD_GET_SLOTMAX;
     buffer.padSlotMaxArgs.port = port;
     if (SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
         return -1;
     return buffer.padResult.result;
 }
References buffer, NULL, PAD_RPCCMD_GET_SLOTMAX, padsif, port, and SifCallRpc().
Referenced by main().
padGetState()
int padGetState (int port, int slot)
Get current pad state Wait until state == 6 (Ready) before trying to access the pad
Definition at line 482 of file libpad.c.
 {
     struct pad_data *pdata;
     unsigned char state;
     pdata = padGetDmaStr(port, slot);
     state = pdata->state;
 #ifdef _XPAD
     if (state == PAD_STATE_ERROR)
     {
         if (pdata->findPadRetries)
         {
             return PAD_STATE_FINDPAD;
         }
     }
 #endif
     if (state == PAD_STATE_STABLE) { // Ok
         if (padGetReqState(port, slot) == PAD_RSTAT_BUSY) {
             return PAD_STATE_EXECCMD;
         }
     }
     return state;
 }
References PAD_RSTAT_BUSY, PAD_STATE_ERROR, PAD_STATE_EXECCMD, PAD_STATE_FINDPAD, PAD_STATE_STABLE, padGetDmaStr(), padGetReqState(), port, slot, and pad_data::state.
Referenced by find_controllers(), main(), pad_get_state(), padWait(), and waitPadReady().
padInfoAct()
unsigned char padInfoAct (int port, int slot, int word, int byte)
Get actuator status for this controller If padInfoAct(port, slot, -1, 0) != 0, the controller has actuators (i think ;))
Definition at line 738 of file libpad.c.
 {
 #ifdef _XPAD
     struct pad_data *pdata;
     pdata = padGetDmaStr(port, slot);
     if (pdata->currentTask != 1)
         return 0;
     if (pdata->modeConfig < 2)
         return 0;
     if (actuator >= pdata->nrOfActuators)
         return 0;
     if (actuator == -1)
         return pdata->nrOfActuators;   // # of acutators?
     if (cmd >= 4)
         return 0;
     return pdata->actData[actuator*4+cmd];
 #else
         buffer.padInfoActArgs.command = PAD_RPCCMD_INFO_ACT;
         buffer.padInfoActArgs.port = port;
         buffer.padInfoActArgs.slot = slot;
         buffer.padInfoActArgs.actuator = actuator;
         buffer.padInfoActArgs.act_cmd = cmd;
     if (SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
         return 0;
     if (buffer.padModeResult.result == 1) {
         padSetReqState(port, slot, PAD_RSTAT_BUSY);
     }
     return buffer.padModeResult.result;
 #endif
 }
References actuator, buffer, NULL, PAD_RPCCMD_INFO_ACT, PAD_RSTAT_BUSY, padGetDmaStr(), padSetReqState(), padsif, port, SifCallRpc(), and slot.
Referenced by initializePad(), main(), and pad_init_actuators().
padInfoMode()
int padInfoMode (int port, int slot, int infoMode, int index)
Get pad info (digital (4), dualshock (7), etc..)
Returns
3 - KONAMI GUN; 4 - DIGITAL PAD; 5 - JOYSTICK; 6 - NAMCO GUN; 7 - DUAL SHOCK
Definition at line 588 of file libpad.c.
 {
 #ifdef _XPAD
     struct pad_data *pdata;
     pdata = padGetDmaStr(port, slot);
     if (pdata->currentTask != 1)
         return 0;
     if (pdata->reqState == PAD_RSTAT_BUSY)
         return 0;
     switch(infoMode) {
     case PAD_MODECURID:
         if (pdata->modeCurId == 0xF3)
             return 0;
         else
             return (pdata->modeCurId >> 4);
         break;
     case PAD_MODECUREXID:
         if (pdata->modeConfig == pdata->currentTask)
             return 0;
         return pdata->modeTable[pdata->modeCurOffs];
         break;
     case PAD_MODECUROFFS:
         if (pdata->modeConfig != 0)
             return pdata->modeCurOffs;
         else
             return 0;
         break;
     case PAD_MODETABLE:
         if (pdata->modeConfig != 0) {
             if(index == -1) {
                 return pdata->nrOfModes;
             }
             else if (index < pdata->nrOfModes) {
                 return pdata->modeTable[index];
             }
             else {
                 return 0;
             }
         }
         else
             return 0;
         break;
     }
     return 0;
 #else
         buffer.padInfoModeArgs.command = PAD_RPCCMD_INFO_MODE;
         buffer.padInfoModeArgs.port = port;
         buffer.padInfoModeArgs.slot = slot;
         buffer.padInfoModeArgs.infoMode = infoMode;
         buffer.padInfoModeArgs.index = index;
     if (SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
         return 0;
     if (buffer.padModeResult.result == 1) {
         padSetReqState(port, slot, PAD_RSTAT_BUSY);
     }
     return buffer.padModeResult.result;
 #endif
 }
References buffer, index, infoMode, NULL, PAD_MODECUREXID, PAD_MODECURID, PAD_MODECUROFFS, PAD_MODETABLE, PAD_RPCCMD_INFO_MODE, PAD_RSTAT_BUSY, padGetDmaStr(), padSetReqState(), padsif, port, pad_data::reqState, SifCallRpc(), and slot.
Referenced by initializePad(), main(), pad_get_num_modes(), pad_get_type(), pad_has_type(), and pad_init_actuators().
padInfoPressMode()
int padInfoPressMode (int port, int slot)
Check if the pad has pressure sensitive buttons
Definition at line 675 of file libpad.c.
 {
     int mask;
     mask = padGetButtonMask(port, slot);
     if (mask^0x3ffff) {
         return 0;
     }
     else {
         return 1;
     }
 }
References padGetButtonMask(), port, and slot.
Referenced by initializePad(), main(), and pad_set_sensitivity().
padInit()
int padInit (int mode)
Initialise libpad
Parameters
mode Must be set to 0.
Returns
== 1 => OK
Definition at line 297 of file libpad.c.
 {
     // Version check isn't used by default
     // int ver;
     static int _rb_count = 0;
     if (_rb_count != _iop_reboot_count)
     {
         _rb_count = _iop_reboot_count;
         padInitialised = 0;
     }
     if(padInitialised)
         return 0;
     padInitialised = 1;
     padsif[0].server = NULL;
     padsif[1].server = NULL;
     do {
         if (SifBindRpc(&padsif[0], PAD_BIND_RPC_ID1, 0) < 0) {
             return -1;
         }
         nopdelay();
     } while(!padsif[0].server);
     do {
         if (SifBindRpc(&padsif[1], PAD_BIND_RPC_ID2, 0) < 0) {
             return -3;
         }
         nopdelay();
     } while(!padsif[1].server);
     // If you require a special version of the padman, check for that here (uncomment)
     // ver = padGetModVersion();
     //At v1.3.4, this used to return 1 (and padPortInit is not used). But we are interested in the better design from release 1.4.
     return padPortInit(mode);
 }
References _iop_reboot_count, mode, nopdelay(), NULL, PAD_BIND_RPC_ID1, PAD_BIND_RPC_ID2, padInitialised, padPortInit(), padsif, SifRpcClientData_t::server, and SifBindRpc().
Referenced by main().
padPortClose()
int padPortClose (int port, int slot)
Closes an opened port.
Parameters
port Port to close
slot Slot to close
Returns
!= 0 => OK
Definition at line 449 of file libpad.c.
 {
     int ret;
         buffer.padCloseArgs.command = PAD_RPCCMD_CLOSE;
         buffer.padCloseArgs.port = port;
         buffer.padCloseArgs.slot = slot;
         buffer.padCloseArgs.mode = 1;
     ret = SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL);
     if(ret < 0)
         return ret;
     else {
         PadState[port][slot].open = 0;
         return buffer.padResult.result;
     }
 }
References buffer, NULL, pad_state::open, PAD_RPCCMD_CLOSE, padsif, PadState, port, SifCallRpc(), and slot.
Referenced by find_controllers(), and pad_close().
padPortInit()
int padPortInit (int mode)
Initialise pad ports. Automatically called by padInit(), there is no need to call this function directly.
Parameters
mode Must be set to 0.
Returns
== 1 => OK
Note: PADMAN from release 1.3.4 does not have this function implemented. As a result, it is impossible to reinitialize libpad after calling padEnd().
Returns
== 1 => OK
Definition at line 338 of file libpad.c.
 {
 #ifdef _XPAD    //Unofficial: libpad EE client from v1.3.4 has this RPC function implemented, but is not implemented within its PADMAN module.
     int ret;
 #endif
     int i;
     for(i = 0; i<8; i++)
     {
         PadState[0][i].open = 0;
         PadState[0][i].port = 0;
         PadState[0][i].slot = 0;
         PadState[1][i].open = 0;
         PadState[1][i].port = 0;
         PadState[1][i].slot = 0;
     }
 #ifdef _XPAD    //Unofficial: libpad EE client from v1.3.4 has this RPC function implemented, but is not implemented within its PADMAN module.
 #ifdef _XPAD
     buffer.padInitArgs.command = PAD_RPCCMD_INIT;
     buffer.padInitArgs.statBuf = openSlot;
 #else
     buffer.command = PAD_RPCCMD_INIT;
 #endif
     ret = SifCallRpc( &padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL);
     return(ret >= 0 ? buffer.padResult.result : 0);
 #else
     return 1;
 #endif
 }
References buffer, NULL, pad_state::open, PAD_RPCCMD_INIT, padsif, PadState, pad_state::port, SifCallRpc(), and pad_state::slot.
Referenced by padInit().
padPortOpen()
int padPortOpen (int port, int slot, void * padArea)
Parameters
port Port to open
slot Slot to open
padArea The address of the buffer for storing the pad status. Must be a 256-byte region (2xsizeof(struct pad_data). Must be a 64-byte aligned address. For the old libpad, at least 16-bytes alignment.
Returns
!= 0 => OK
Definition at line 392 of file libpad.c.
 {
     int i;
     struct pad_data *dma_buf = (struct pad_data *)padArea;
 #ifndef _XPAD
     // Check 16 byte alignment
     if((u32)padArea & 0xf) {
         printf("Address is not 16-byte aligned.\n");
         return 0;
     }
 #else
     // Check 64 byte alignment
     if((u32)padArea & 0x3f) {
         printf("Address is not 16-byte aligned.\n");
         return 0;
     }
 #endif
     for (i=0; i<2; i++) {                // Pad data is double buffered
         memset(dma_buf[i].data, 0xff, 32); // 'Clear' data area
         dma_buf[i].frame = 0;
         dma_buf[i].length = 0;
         dma_buf[i].state = PAD_STATE_EXECCMD;
         dma_buf[i].reqState = PAD_RSTAT_BUSY;
 #ifndef _XPAD
         dma_buf[i].ok = 0;
 #endif
 #ifdef _XPAD
         dma_buf[i].currentTask = 0;
 #endif
         dma_buf[i].length = 0;
 #ifdef _XPAD
         dma_buf[i].buttonDataReady = 0; // Should be cleared in newer padman
 #endif
     }
         buffer.padOpenArgs.command = PAD_RPCCMD_OPEN;
         buffer.padOpenArgs.port = port;
     buffer.padOpenArgs.slot = slot;
     buffer.padOpenArgs.padArea = padArea;
     if(SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
     {
         return 0;
     }
     PadState[port][slot].open = 1;
     PadState[port][slot].padData = padArea;
     PadState[port][slot].padBuf = buffer.padOpenResult.padBuf;
     return buffer.padOpenResult.result;
 }
References buffer, data, pad_data::frame, pad_data::length, NULL, pad_data::ok, pad_state::open, PAD_RPCCMD_OPEN, PAD_RSTAT_BUSY, PAD_STATE_EXECCMD, padArea, pad_state::padBuf, pad_state::padData, padsif, PadState, port, pad_data::reqState, SifCallRpc(), slot, and pad_data::state.
Referenced by find_controllers(), main(), and pad_open().
padRead()
unsigned char padRead (int port, int slot, struct padButtonStatus * data)
Read pad data
Parameters
port Port number of the pad to get the status for.
slot Slot number of the pad to get the status for.
data A pointer to a 32 byte array where the result is stored
Returns
!= 0 => OK
Definition at line 470 of file libpad.c.
 {
     struct pad_data *pdata;
     pdata = padGetDmaStr(port, slot);
     memcpy(data, pdata->data, pdata->length);
     return pdata->length;
 }
References data, pad_data::data, pad_data::length, padGetDmaStr(), port, and slot.
Referenced by main(), and pad_get_buttons().
padReqStateInt2String()
void padReqStateInt2String (int state, char buf[16])
Definition at line 541 of file libpad.c.
 {
     if(state < 4)
         strcpy(buf, padReqStateString[state]);
 }
References padReqStateString, and pad_data::state.
padSetActAlign()
int padSetActAlign (int port, int slot, char act_align[6])
Initalise actuators. On dual shock controller: act_align[0] = 0 enables 'small' engine act_align[1] = 1 enables 'big' engine set act_align[2-5] to 0xff (disable)
Definition at line 777 of file libpad.c.
 {
     int i;
     s8 *ptr;
         buffer.padActDirAlignArgs.command = PAD_RPCCMD_SET_ACTALIGN;
         buffer.padActDirAlignArgs.port = port;
         buffer.padActDirAlignArgs.slot = slot;
         ptr = buffer.padActDirAlignArgs.align;
     for (i=0; i<6; i++)
         ptr[i]=actAlign[i];
     if (SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
         return 0;
     if (buffer.padModeResult.result == 1) {
         padSetReqState(port, slot, PAD_RSTAT_BUSY);
     }
     return buffer.padModeResult.result;
 }
References actAlign, buffer, NULL, PAD_RPCCMD_SET_ACTALIGN, PAD_RSTAT_BUSY, padSetReqState(), padsif, port, SifCallRpc(), and slot.
Referenced by initializePad(), main(), and pad_init_actuators().
padSetActDirect()
int padSetActDirect (int port, int slot, char act_align[6])
Set actuator status on dual shock controller, act_align[0] = 0/1 turns off/on 'small' engine act_align[1] = 0-255 sets 'big' engine speed
Definition at line 800 of file libpad.c.
 {
     int i;
     s8 *ptr;
         buffer.padActDirAlignArgs.command = PAD_RPCCMD_SET_ACTDIR;
         buffer.padActDirAlignArgs.port = port;
         buffer.padActDirAlignArgs.slot = slot;
     ptr = buffer.padActDirAlignArgs.align;
     for (i=0; i<6; i++)
         ptr[i]=actAlign[i];
     if (SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
         return 0;
     return buffer.padModeResult.result;
 }
References actAlign, buffer, NULL, PAD_RPCCMD_SET_ACTDIR, padsif, port, SifCallRpc(), and slot.
Referenced by main(), pad_set_actuators(), and padStartAct().
padSetButtonInfo()
int padSetButtonInfo (int port, int slot, int buttonInfo)
Definition at line 717 of file libpad.c.
 {
     int val;
         buffer.padSetButtonInfoArgs.command = PAD_RPCCMD_SET_BTNINFO;
         buffer.padSetButtonInfoArgs.port = port;
         buffer.padSetButtonInfoArgs.slot = slot;
         buffer.padSetButtonInfoArgs.buttonInfo = buttonInfo;
     if (SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
         return 0;
     val = buffer.padSetButtonInfoResult.result;
     if (val == 1) {
         padSetReqState(port, slot, PAD_RSTAT_BUSY);
     }
     return buffer.padSetButtonInfoResult.result;
 }
References buffer, buttonInfo, NULL, PAD_RPCCMD_SET_BTNINFO, PAD_RSTAT_BUSY, padSetReqState(), padsif, port, SifCallRpc(), and slot.
Referenced by padEnterPressMode(), and padExitPressMode().
padSetMainMode()
int padSetMainMode (int port, int slot, int mode, int lock)
mode = 1, -> Analog/dual shock enabled; mode = 0 -> Digital lock = 3 -> Mode not changeable by user
Definition at line 656 of file libpad.c.
 {
         buffer.padSetMainModeArgs.command = PAD_RPCCMD_SET_MMODE;
         buffer.padSetMainModeArgs.port = port;
         buffer.padSetMainModeArgs.slot = slot;
         buffer.padSetMainModeArgs.mode = mode;
         buffer.padSetMainModeArgs.lock = lock;
     if (SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
         return 0;
     if (buffer.padModeResult.result == 1) {
         padSetReqState(port, slot, PAD_RSTAT_BUSY);
     }
     return buffer.padModeResult.result;
 }
References buffer, lock, mode, NULL, PAD_RPCCMD_SET_MMODE, PAD_RSTAT_BUSY, padSetReqState(), padsif, port, SifCallRpc(), and slot.
Referenced by initializePad(), main(), and pad_set_mode().
padSetReqState()
int padSetReqState (int port, int slot, int state)
Set pad request state (after a param setting) No need to export this one perhaps..
Definition at line 521 of file libpad.c.
 {
     struct pad_data *pdata;
     pdata = padGetDmaStr(port, slot);
     pdata->reqState = state;
     return 1;
 }
References padGetDmaStr(), port, pad_data::reqState, slot, and pad_data::state.
Referenced by padInfoAct(), padInfoMode(), padSetActAlign(), padSetButtonInfo(), and padSetMainMode().
padStateInt2String()
void padStateInt2String (int state, char buf[16])
Definition at line 532 of file libpad.c.
 {
     if(state < 8) {
         strcpy(buf, padStateString[state]);
     }
 }
References padStateString, and pad_data::state.
Referenced by waitPadReady().