ps2sdk: ee/rpc/pad/src/libpad.c File Reference
libpad.c File Reference
#include <tamtypes.h>
#include <kernel.h>
#include <stdio.h>
#include <string.h>
#include <sifrpc.h>
#include <sifcmd.h>
#include "libpad.h"
Data Structures
struct pad_state
struct pad_data
Macros
#define PAD_BIND_RPC_ID1 0x8000010f
#define PAD_BIND_RPC_ID2 0x8000011f
#define PAD_RPCCMD_OPEN 0x80000100
#define PAD_RPCCMD_INFO_ACT 0x80000102
#define PAD_RPCCMD_INFO_COMB 0x80000103
#define PAD_RPCCMD_INFO_MODE 0x80000104
#define PAD_RPCCMD_SET_MMODE 0x80000105
#define PAD_RPCCMD_SET_ACTDIR 0x80000106
#define PAD_RPCCMD_SET_ACTALIGN 0x80000107
#define PAD_RPCCMD_GET_BTNMASK 0x80000108
#define PAD_RPCCMD_SET_BTNINFO 0x80000109
#define PAD_RPCCMD_SET_VREF 0x8000010a
#define PAD_RPCCMD_GET_PORTMAX 0x8000010b
#define PAD_RPCCMD_GET_SLOTMAX 0x8000010c
#define PAD_RPCCMD_CLOSE 0x8000010d
#define PAD_RPCCMD_END 0x8000010e
#define PAD_RPCCMD_INIT 0x00000100
Functions
static struct pad_data * padGetDmaStr (int port, int slot)
int padInit (int mode)
int padPortInit (int mode)
int padEnd (void)
int padPortOpen (int port, int slot, void *padArea)
int padPortClose (int port, int slot)
unsigned char padRead (int port, int slot, struct padButtonStatus *data)
int padGetState (int port, int slot)
unsigned char padGetReqState (int port, int slot)
int padSetReqState (int port, int slot, int state)
void padStateInt2String (int state, char buf[16])
void padReqStateInt2String (int state, char buf[16])
int padGetPortMax (void)
int padGetSlotMax (int port)
int padGetModVersion ()
int padInfoMode (int port, int slot, int infoMode, int index)
int padSetMainMode (int port, int slot, int mode, int lock)
int padInfoPressMode (int port, int slot)
int padEnterPressMode (int port, int slot)
int padExitPressMode (int port, int slot)
int padGetButtonMask (int port, int slot)
int padSetButtonInfo (int port, int slot, int buttonInfo)
unsigned char padInfoAct (int port, int slot, int actuator, int cmd)
int padSetActAlign (int port, int slot, char actAlign[6])
int padSetActDirect (int port, int slot, char actAlign[6])
int padGetConnection (int port, int slot)
Variables
int _iop_reboot_count
static const char padStateString [8][16]
static const char padReqStateString [3][16] = {"COMPLETE", "FAILED", "BUSY"}
static int padInitialised = 0
static SifRpcClientData_t padsif [2]
static struct pad_state PadState [2][8]
Detailed Description
Pad library functions Quite easy rev engineered from util demos.. Find any bugs? Mail me: pukko.nosp@m.@hom.nosp@m.e.se
Definition in file libpad.c.
Macro Definition Documentation
PAD_BIND_RPC_ID1
#define PAD_BIND_RPC_ID1 0x8000010f
Definition at line 48 of file libpad.c.
PAD_BIND_RPC_ID2
#define PAD_BIND_RPC_ID2 0x8000011f
Definition at line 49 of file libpad.c.
PAD_RPCCMD_CLOSE
#define PAD_RPCCMD_CLOSE 0x8000010d
Definition at line 63 of file libpad.c.
PAD_RPCCMD_END
#define PAD_RPCCMD_END 0x8000010e
Definition at line 64 of file libpad.c.
PAD_RPCCMD_GET_BTNMASK
#define PAD_RPCCMD_GET_BTNMASK 0x80000108
Definition at line 58 of file libpad.c.
PAD_RPCCMD_GET_PORTMAX
#define PAD_RPCCMD_GET_PORTMAX 0x8000010b
Definition at line 61 of file libpad.c.
PAD_RPCCMD_GET_SLOTMAX
#define PAD_RPCCMD_GET_SLOTMAX 0x8000010c
Definition at line 62 of file libpad.c.
PAD_RPCCMD_INFO_ACT
#define PAD_RPCCMD_INFO_ACT 0x80000102
Definition at line 52 of file libpad.c.
PAD_RPCCMD_INFO_COMB
#define PAD_RPCCMD_INFO_COMB 0x80000103
Definition at line 53 of file libpad.c.
PAD_RPCCMD_INFO_MODE
#define PAD_RPCCMD_INFO_MODE 0x80000104
Definition at line 54 of file libpad.c.
PAD_RPCCMD_INIT
#define PAD_RPCCMD_INIT 0x00000100
Definition at line 65 of file libpad.c.
PAD_RPCCMD_OPEN
#define PAD_RPCCMD_OPEN 0x80000100
Definition at line 51 of file libpad.c.
PAD_RPCCMD_SET_ACTALIGN
#define PAD_RPCCMD_SET_ACTALIGN 0x80000107
Definition at line 57 of file libpad.c.
PAD_RPCCMD_SET_ACTDIR
#define PAD_RPCCMD_SET_ACTDIR 0x80000106
Definition at line 56 of file libpad.c.
PAD_RPCCMD_SET_BTNINFO
#define PAD_RPCCMD_SET_BTNINFO 0x80000109
Definition at line 59 of file libpad.c.
PAD_RPCCMD_SET_MMODE
#define PAD_RPCCMD_SET_MMODE 0x80000105
Definition at line 55 of file libpad.c.
PAD_RPCCMD_SET_VREF
#define PAD_RPCCMD_SET_VREF 0x8000010a
Definition at line 60 of file libpad.c.
Function Documentation
padEnd()
int padEnd (void)
Ends all pad communication Note: PADMAN from release 1.3.4 does not have padPortInit implemented. As a result, it is impossible to reinitialize libpad after calling padEnd(). This was known as padClose in the really early official SDK releases.
Returns
== 1 => OK
Definition at line 372 of file libpad.c.
 {
     int ret;
     buffer.command=PAD_RPCCMD_END;
     if (SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
         return -1;
     ret = buffer.padResult.result;
     if (ret == 1) {
         padInitialised = 0;
     }
     return ret;
 }
References buffer, NULL, PAD_RPCCMD_END, padInitialised, padsif, and SifCallRpc().
padEnterPressMode()
int padEnterPressMode (int port, int slot)
Pressure sensitive mode ON
Definition at line 690 of file libpad.c.
 {
     return padSetButtonInfo(port, slot, 0xFFF);
 }
References padSetButtonInfo(), port, and slot.
Referenced by initializePad(), main(), and pad_set_sensitivity().
padExitPressMode()
int padExitPressMode (int port, int slot)
Check for newer version Pressure sensitive mode OFF
Definition at line 696 of file libpad.c.
 {
     return padSetButtonInfo(port, slot, 0);
 }
References padSetButtonInfo(), port, and slot.
Referenced by main(), and pad_set_sensitivity().
padGetButtonMask()
int padGetButtonMask (int port, int slot)
Definition at line 703 of file libpad.c.
 {
         buffer.padGetButtonMaskArgs.command = PAD_RPCCMD_GET_BTNMASK;
         buffer.padGetButtonMaskArgs.port = port;
         buffer.padGetButtonMaskArgs.slot = slot;
     if (SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
         return 0;
     return buffer.padResult.result;
 }
References buffer, NULL, PAD_RPCCMD_GET_BTNMASK, padsif, port, SifCallRpc(), and slot.
Referenced by padInfoPressMode().
padGetConnection()
int padGetConnection (int port, int slot)
Returns whether the device at port,slot is connected (1 = connected) Appears to have been removed very early during the PS2's lifetime. If possible, use the documented padGetState instead.
NOT SUPPORTED with module rom0:padman
Definition at line 823 of file libpad.c.
 {
 #ifdef _XPAD
     struct open_slot *oslot;
     oslot = padGetConnDmaStr();
     return ((oslot->openSlots[port] >> slot) & 0x1);
 #else
     return 1;
 #endif
 }
References port, and slot.
padGetDmaStr()
static struct pad_data* padGetDmaStr (int port, int slot) static
Common helper
Definition at line 253 of file libpad.c.
 {
     struct pad_data *pdata;
     pdata = PadState[port][slot].padData;
     SyncDCache(pdata, (u8 *)pdata + 256);
     if(pdata[0].frame < pdata[1].frame) {
         return &pdata[1];
     }
     else {
         return &pdata[0];
     }
 }
References pad_data::frame, pad_state::padData, PadState, port, slot, and SyncDCache().
Referenced by padGetReqState(), padGetState(), padInfoAct(), padInfoMode(), padRead(), and padSetReqState().
padGetModVersion()
int padGetModVersion ()
Returns the padman.irx version NOT SUPPORTED on module rom0:padman
Definition at line 573 of file libpad.c.
 {
 #ifdef _XPAD
     buffer.command = PAD_RPCCMD_GET_MODVER;
     if (SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
         return -1;
     return buffer.padResult.result;
 #else
     return 1; // Well.. return a low version #
 #endif
 }
References buffer, NULL, padsif, and SifCallRpc().
padGetPortMax()
int padGetPortMax (void)
Returns # slots on the PS2 (usally 2)
Definition at line 548 of file libpad.c.
 {
         buffer.command = PAD_RPCCMD_GET_PORTMAX;
     if (SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
         return -1;
     return buffer.padResult.result;
 }
References buffer, NULL, PAD_RPCCMD_GET_PORTMAX, padsif, and SifCallRpc().
Referenced by main().
padGetReqState()
unsigned char padGetReqState (int port, int slot)
Get pad request state
Definition at line 511 of file libpad.c.
 {
     struct pad_data *pdata;
     pdata = padGetDmaStr(port, slot);
     return pdata->reqState;
 }
References padGetDmaStr(), port, pad_data::reqState, and slot.
Referenced by padGetState(), and padWait().
padGetSlotMax()
int padGetSlotMax (int port)
Returns # slots the port has (usually 1) probably 4 if using a multi tap (not tested)
Definition at line 560 of file libpad.c.
 {
     buffer.padSlotMaxArgs.command = PAD_RPCCMD_GET_SLOTMAX;
     buffer.padSlotMaxArgs.port = port;
     if (SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
         return -1;
     return buffer.padResult.result;
 }
References buffer, NULL, PAD_RPCCMD_GET_SLOTMAX, padsif, port, and SifCallRpc().
Referenced by main().
padGetState()
int padGetState (int port, int slot)
Get current pad state Wait until state == 6 (Ready) before trying to access the pad
Definition at line 482 of file libpad.c.
 {
     struct pad_data *pdata;
     unsigned char state;
     pdata = padGetDmaStr(port, slot);
     state = pdata->state;
 #ifdef _XPAD
     if (state == PAD_STATE_ERROR)
     {
         if (pdata->findPadRetries)
         {
             return PAD_STATE_FINDPAD;
         }
     }
 #endif
     if (state == PAD_STATE_STABLE) { // Ok
         if (padGetReqState(port, slot) == PAD_RSTAT_BUSY) {
             return PAD_STATE_EXECCMD;
         }
     }
     return state;
 }
References PAD_RSTAT_BUSY, PAD_STATE_ERROR, PAD_STATE_EXECCMD, PAD_STATE_FINDPAD, PAD_STATE_STABLE, padGetDmaStr(), padGetReqState(), port, slot, and pad_data::state.
Referenced by find_controllers(), main(), pad_get_state(), padWait(), and waitPadReady().
padInfoAct()
unsigned char padInfoAct (int port, int slot, int word, int byte)
Get actuator status for this controller If padInfoAct(port, slot, -1, 0) != 0, the controller has actuators (i think ;))
Definition at line 738 of file libpad.c.
 {
 #ifdef _XPAD
     struct pad_data *pdata;
     pdata = padGetDmaStr(port, slot);
     if (pdata->currentTask != 1)
         return 0;
     if (pdata->modeConfig < 2)
         return 0;
     if (actuator >= pdata->nrOfActuators)
         return 0;
     if (actuator == -1)
         return pdata->nrOfActuators;   // # of acutators?
     if (cmd >= 4)
         return 0;
     return pdata->actData[actuator*4+cmd];
 #else
         buffer.padInfoActArgs.command = PAD_RPCCMD_INFO_ACT;
         buffer.padInfoActArgs.port = port;
         buffer.padInfoActArgs.slot = slot;
         buffer.padInfoActArgs.actuator = actuator;
         buffer.padInfoActArgs.act_cmd = cmd;
     if (SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
         return 0;
     if (buffer.padModeResult.result == 1) {
         padSetReqState(port, slot, PAD_RSTAT_BUSY);
     }
     return buffer.padModeResult.result;
 #endif
 }
References actuator, buffer, NULL, PAD_RPCCMD_INFO_ACT, PAD_RSTAT_BUSY, padGetDmaStr(), padSetReqState(), padsif, port, SifCallRpc(), and slot.
Referenced by initializePad(), main(), and pad_init_actuators().
padInfoMode()
int padInfoMode (int port, int slot, int infoMode, int index)
Get pad info (digital (4), dualshock (7), etc..)
Returns
3 - KONAMI GUN; 4 - DIGITAL PAD; 5 - JOYSTICK; 6 - NAMCO GUN; 7 - DUAL SHOCK
Definition at line 588 of file libpad.c.
 {
 #ifdef _XPAD
     struct pad_data *pdata;
     pdata = padGetDmaStr(port, slot);
     if (pdata->currentTask != 1)
         return 0;
     if (pdata->reqState == PAD_RSTAT_BUSY)
         return 0;
     switch(infoMode) {
     case PAD_MODECURID:
         if (pdata->modeCurId == 0xF3)
             return 0;
         else
             return (pdata->modeCurId >> 4);
         break;
     case PAD_MODECUREXID:
         if (pdata->modeConfig == pdata->currentTask)
             return 0;
         return pdata->modeTable[pdata->modeCurOffs];
         break;
     case PAD_MODECUROFFS:
         if (pdata->modeConfig != 0)
             return pdata->modeCurOffs;
         else
             return 0;
         break;
     case PAD_MODETABLE:
         if (pdata->modeConfig != 0) {
             if(index == -1) {
                 return pdata->nrOfModes;
             }
             else if (index < pdata->nrOfModes) {
                 return pdata->modeTable[index];
             }
             else {
                 return 0;
             }
         }
         else
             return 0;
         break;
     }
     return 0;
 #else
         buffer.padInfoModeArgs.command = PAD_RPCCMD_INFO_MODE;
         buffer.padInfoModeArgs.port = port;
         buffer.padInfoModeArgs.slot = slot;
         buffer.padInfoModeArgs.infoMode = infoMode;
         buffer.padInfoModeArgs.index = index;
     if (SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
         return 0;
     if (buffer.padModeResult.result == 1) {
         padSetReqState(port, slot, PAD_RSTAT_BUSY);
     }
     return buffer.padModeResult.result;
 #endif
 }
References buffer, index, infoMode, NULL, PAD_MODECUREXID, PAD_MODECURID, PAD_MODECUROFFS, PAD_MODETABLE, PAD_RPCCMD_INFO_MODE, PAD_RSTAT_BUSY, padGetDmaStr(), padSetReqState(), padsif, port, pad_data::reqState, SifCallRpc(), and slot.
Referenced by initializePad(), main(), pad_get_num_modes(), pad_get_type(), pad_has_type(), and pad_init_actuators().
padInfoPressMode()
int padInfoPressMode (int port, int slot)
Check if the pad has pressure sensitive buttons
Definition at line 675 of file libpad.c.
 {
     int mask;
     mask = padGetButtonMask(port, slot);
     if (mask^0x3ffff) {
         return 0;
     }
     else {
         return 1;
     }
 }
References padGetButtonMask(), port, and slot.
Referenced by initializePad(), main(), and pad_set_sensitivity().
padInit()
int padInit (int mode)
Initialise libpad
Parameters
mode Must be set to 0.
Returns
== 1 => OK
Definition at line 297 of file libpad.c.
 {
     // Version check isn't used by default
     // int ver;
     static int _rb_count = 0;
     if (_rb_count != _iop_reboot_count)
     {
         _rb_count = _iop_reboot_count;
         padInitialised = 0;
     }
     if(padInitialised)
         return 0;
     padInitialised = 1;
     padsif[0].server = NULL;
     padsif[1].server = NULL;
     do {
         if (SifBindRpc(&padsif[0], PAD_BIND_RPC_ID1, 0) < 0) {
             return -1;
         }
         nopdelay();
     } while(!padsif[0].server);
     do {
         if (SifBindRpc(&padsif[1], PAD_BIND_RPC_ID2, 0) < 0) {
             return -3;
         }
         nopdelay();
     } while(!padsif[1].server);
     // If you require a special version of the padman, check for that here (uncomment)
     // ver = padGetModVersion();
     //At v1.3.4, this used to return 1 (and padPortInit is not used). But we are interested in the better design from release 1.4.
     return padPortInit(mode);
 }
References _iop_reboot_count, mode, nopdelay(), NULL, PAD_BIND_RPC_ID1, PAD_BIND_RPC_ID2, padInitialised, padPortInit(), padsif, SifRpcClientData_t::server, and SifBindRpc().
Referenced by main().
padPortClose()
int padPortClose (int port, int slot)
Closes an opened port.
Parameters
port Port to close
slot Slot to close
Returns
!= 0 => OK
Definition at line 449 of file libpad.c.
 {
     int ret;
         buffer.padCloseArgs.command = PAD_RPCCMD_CLOSE;
         buffer.padCloseArgs.port = port;
         buffer.padCloseArgs.slot = slot;
         buffer.padCloseArgs.mode = 1;
     ret = SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL);
     if(ret < 0)
         return ret;
     else {
         PadState[port][slot].open = 0;
         return buffer.padResult.result;
     }
 }
References buffer, NULL, pad_state::open, PAD_RPCCMD_CLOSE, padsif, PadState, port, SifCallRpc(), and slot.
Referenced by find_controllers(), and pad_close().
padPortInit()
int padPortInit (int mode)
Initialise pad ports. Automatically called by padInit(), there is no need to call this function directly.
Parameters
mode Must be set to 0.
Returns
== 1 => OK
Note: PADMAN from release 1.3.4 does not have this function implemented. As a result, it is impossible to reinitialize libpad after calling padEnd().
Returns
== 1 => OK
Definition at line 338 of file libpad.c.
 {
 #ifdef _XPAD    //Unofficial: libpad EE client from v1.3.4 has this RPC function implemented, but is not implemented within its PADMAN module.
     int ret;
 #endif
     int i;
     for(i = 0; i<8; i++)
     {
         PadState[0][i].open = 0;
         PadState[0][i].port = 0;
         PadState[0][i].slot = 0;
         PadState[1][i].open = 0;
         PadState[1][i].port = 0;
         PadState[1][i].slot = 0;
     }
 #ifdef _XPAD    //Unofficial: libpad EE client from v1.3.4 has this RPC function implemented, but is not implemented within its PADMAN module.
 #ifdef _XPAD
     buffer.padInitArgs.command = PAD_RPCCMD_INIT;
     buffer.padInitArgs.statBuf = openSlot;
 #else
     buffer.command = PAD_RPCCMD_INIT;
 #endif
     ret = SifCallRpc( &padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL);
     return(ret >= 0 ? buffer.padResult.result : 0);
 #else
     return 1;
 #endif
 }
References buffer, NULL, pad_state::open, PAD_RPCCMD_INIT, padsif, PadState, pad_state::port, SifCallRpc(), and pad_state::slot.
Referenced by padInit().
padPortOpen()
int padPortOpen (int port, int slot, void * padArea)
Parameters
port Port to open
slot Slot to open
padArea The address of the buffer for storing the pad status. Must be a 256-byte region (2xsizeof(struct pad_data). Must be a 64-byte aligned address. For the old libpad, at least 16-bytes alignment.
Returns
!= 0 => OK
Definition at line 392 of file libpad.c.
 {
     int i;
     struct pad_data *dma_buf = (struct pad_data *)padArea;
 #ifndef _XPAD
     // Check 16 byte alignment
     if((u32)padArea & 0xf) {
         printf("Address is not 16-byte aligned.\n");
         return 0;
     }
 #else
     // Check 64 byte alignment
     if((u32)padArea & 0x3f) {
         printf("Address is not 16-byte aligned.\n");
         return 0;
     }
 #endif
     for (i=0; i<2; i++) {                // Pad data is double buffered
         memset(dma_buf[i].data, 0xff, 32); // 'Clear' data area
         dma_buf[i].frame = 0;
         dma_buf[i].length = 0;
         dma_buf[i].state = PAD_STATE_EXECCMD;
         dma_buf[i].reqState = PAD_RSTAT_BUSY;
 #ifndef _XPAD
         dma_buf[i].ok = 0;
 #endif
 #ifdef _XPAD
         dma_buf[i].currentTask = 0;
 #endif
         dma_buf[i].length = 0;
 #ifdef _XPAD
         dma_buf[i].buttonDataReady = 0; // Should be cleared in newer padman
 #endif
     }
         buffer.padOpenArgs.command = PAD_RPCCMD_OPEN;
         buffer.padOpenArgs.port = port;
     buffer.padOpenArgs.slot = slot;
     buffer.padOpenArgs.padArea = padArea;
     if(SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
     {
         return 0;
     }
     PadState[port][slot].open = 1;
     PadState[port][slot].padData = padArea;
     PadState[port][slot].padBuf = buffer.padOpenResult.padBuf;
     return buffer.padOpenResult.result;
 }
References buffer, data, pad_data::frame, pad_data::length, NULL, pad_data::ok, pad_state::open, PAD_RPCCMD_OPEN, PAD_RSTAT_BUSY, PAD_STATE_EXECCMD, padArea, pad_state::padBuf, pad_state::padData, padsif, PadState, port, pad_data::reqState, SifCallRpc(), slot, and pad_data::state.
Referenced by find_controllers(), main(), and pad_open().
padRead()
unsigned char padRead (int port, int slot, struct padButtonStatus * data)
Read pad data
Parameters
port Port number of the pad to get the status for.
slot Slot number of the pad to get the status for.
data A pointer to a 32 byte array where the result is stored
Returns
!= 0 => OK
Definition at line 470 of file libpad.c.
 {
     struct pad_data *pdata;
     pdata = padGetDmaStr(port, slot);
     memcpy(data, pdata->data, pdata->length);
     return pdata->length;
 }
References data, pad_data::data, pad_data::length, padGetDmaStr(), port, and slot.
Referenced by main(), and pad_get_buttons().
padReqStateInt2String()
void padReqStateInt2String (int state, char buf[16])
Definition at line 541 of file libpad.c.
 {
     if(state < 4)
         strcpy(buf, padReqStateString[state]);
 }
References padReqStateString, and pad_data::state.
padSetActAlign()
int padSetActAlign (int port, int slot, char act_align[6])
Initalise actuators. On dual shock controller: act_align[0] = 0 enables 'small' engine act_align[1] = 1 enables 'big' engine set act_align[2-5] to 0xff (disable)
Definition at line 777 of file libpad.c.
 {
     int i;
     s8 *ptr;
         buffer.padActDirAlignArgs.command = PAD_RPCCMD_SET_ACTALIGN;
         buffer.padActDirAlignArgs.port = port;
         buffer.padActDirAlignArgs.slot = slot;
         ptr = buffer.padActDirAlignArgs.align;
     for (i=0; i<6; i++)
         ptr[i]=actAlign[i];
     if (SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
         return 0;
     if (buffer.padModeResult.result == 1) {
         padSetReqState(port, slot, PAD_RSTAT_BUSY);
     }
     return buffer.padModeResult.result;
 }
References actAlign, buffer, NULL, PAD_RPCCMD_SET_ACTALIGN, PAD_RSTAT_BUSY, padSetReqState(), padsif, port, SifCallRpc(), and slot.
Referenced by initializePad(), main(), and pad_init_actuators().
padSetActDirect()
int padSetActDirect (int port, int slot, char act_align[6])
Set actuator status on dual shock controller, act_align[0] = 0/1 turns off/on 'small' engine act_align[1] = 0-255 sets 'big' engine speed
Definition at line 800 of file libpad.c.
 {
     int i;
     s8 *ptr;
         buffer.padActDirAlignArgs.command = PAD_RPCCMD_SET_ACTDIR;
         buffer.padActDirAlignArgs.port = port;
         buffer.padActDirAlignArgs.slot = slot;
     ptr = buffer.padActDirAlignArgs.align;
     for (i=0; i<6; i++)
         ptr[i]=actAlign[i];
     if (SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
         return 0;
     return buffer.padModeResult.result;
 }
References actAlign, buffer, NULL, PAD_RPCCMD_SET_ACTDIR, padsif, port, SifCallRpc(), and slot.
Referenced by main(), pad_set_actuators(), and padStartAct().
padSetButtonInfo()
int padSetButtonInfo (int port, int slot, int buttonInfo)
Definition at line 717 of file libpad.c.
 {
     int val;
         buffer.padSetButtonInfoArgs.command = PAD_RPCCMD_SET_BTNINFO;
         buffer.padSetButtonInfoArgs.port = port;
         buffer.padSetButtonInfoArgs.slot = slot;
         buffer.padSetButtonInfoArgs.buttonInfo = buttonInfo;
     if (SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
         return 0;
     val = buffer.padSetButtonInfoResult.result;
     if (val == 1) {
         padSetReqState(port, slot, PAD_RSTAT_BUSY);
     }
     return buffer.padSetButtonInfoResult.result;
 }
References buffer, buttonInfo, NULL, PAD_RPCCMD_SET_BTNINFO, PAD_RSTAT_BUSY, padSetReqState(), padsif, port, SifCallRpc(), and slot.
Referenced by padEnterPressMode(), and padExitPressMode().
padSetMainMode()
int padSetMainMode (int port, int slot, int mode, int lock)
mode = 1, -> Analog/dual shock enabled; mode = 0 -> Digital lock = 3 -> Mode not changeable by user
Definition at line 656 of file libpad.c.
 {
         buffer.padSetMainModeArgs.command = PAD_RPCCMD_SET_MMODE;
         buffer.padSetMainModeArgs.port = port;
         buffer.padSetMainModeArgs.slot = slot;
         buffer.padSetMainModeArgs.mode = mode;
         buffer.padSetMainModeArgs.lock = lock;
     if (SifCallRpc(&padsif[0], 1, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
         return 0;
     if (buffer.padModeResult.result == 1) {
         padSetReqState(port, slot, PAD_RSTAT_BUSY);
     }
     return buffer.padModeResult.result;
 }
References buffer, lock, mode, NULL, PAD_RPCCMD_SET_MMODE, PAD_RSTAT_BUSY, padSetReqState(), padsif, port, SifCallRpc(), and slot.
Referenced by initializePad(), main(), and pad_set_mode().
padSetReqState()
int padSetReqState (int port, int slot, int state)
Set pad request state (after a param setting) No need to export this one perhaps..
Definition at line 521 of file libpad.c.
 {
     struct pad_data *pdata;
     pdata = padGetDmaStr(port, slot);
     pdata->reqState = state;
     return 1;
 }
References padGetDmaStr(), port, pad_data::reqState, slot, and pad_data::state.
Referenced by padInfoAct(), padInfoMode(), padSetActAlign(), padSetButtonInfo(), and padSetMainMode().
padStateInt2String()
void padStateInt2String (int state, char buf[16])
Definition at line 532 of file libpad.c.
 {
     if(state < 8) {
         strcpy(buf, padStateString[state]);
     }
 }
References padStateString, and pad_data::state.
Referenced by waitPadReady().
Variable Documentation
_iop_reboot_count
int _iop_reboot_count extern
Referenced by padInit().
act_cmd
s32 act_cmd
Definition at line 224 of file libpad.c.
actuator
s32 actuator
Definition at line 223 of file libpad.c.
Referenced by padInfoAct().
align
s8 align[6]
Definition at line 230 of file libpad.c.
Referenced by remkroot().
union { ... } buffer
Definition at line 232 of file libpad.c.
Referenced by padEnd(), padGetButtonMask(), padGetModVersion(), padGetPortMax(), padGetSlotMax(), padInfoAct(), padInfoMode(), padPortClose(), padPortInit(), padPortOpen(), padSetActAlign(), padSetActDirect(), padSetButtonInfo(), and padSetMainMode().
buttonInfo
s32 buttonInfo
Definition at line 213 of file libpad.c.
Referenced by padSetButtonInfo().
command
s32 command
Definition at line 156 of file libpad.c.
Referenced by fileXioIoctl2(), NetManIoctl(), and NetManRpcIoctl().
index
s32 index
Definition at line 194 of file libpad.c.
Referenced by ClearBufferLen(), ExpandScratchPad(), GetTLBEntry(), padInfoMode(), ProbeTLBEntry(), and SetTLBEntry().
infoMode
s32 infoMode
Definition at line 193 of file libpad.c.
Referenced by padInfoMode().
lock
s32 lock
Definition at line 200 of file libpad.c.
Referenced by pad_open(), pad_set_mode(), and padSetMainMode().
mode
s32 mode
Definition at line 184 of file libpad.c.
Referenced by padInit(), and padSetMainMode().
struct { ... } padActDirAlignArgs
padArea
void* padArea
Definition at line 178 of file libpad.c.
Referenced by padPortOpen().
padBuf
void* padBuf
Definition at line 168 of file libpad.c.
struct { ... } padCloseArgs
struct { ... } padGetButtonMaskArgs
struct { ... } padInfoActArgs
struct { ... } padInfoModeArgs
padInitialised
int padInitialised = 0 static
Definition at line 151 of file libpad.c.
Referenced by padEnd(), and padInit().
struct { ... } padModeResult
struct { ... } padOpenArgs
struct { ... } padOpenResult
padReqStateString
const char padReqStateString[3][16] = {"COMPLETE", "FAILED", "BUSY"} static
Definition at line 149 of file libpad.c.
Referenced by padReqStateInt2String().
struct { ... } padResult
struct { ... } padSetButtonInfoArgs
struct { ... } padSetButtonInfoResult
struct { ... } padSetMainModeArgs
padsif
SifRpcClientData_t padsif[2] static
Definition at line 154 of file libpad.c.
Referenced by padEnd(), padGetButtonMask(), padGetModVersion(), padGetPortMax(), padGetSlotMax(), padInfoAct(), padInfoMode(), padInit(), padPortClose(), padPortInit(), padPortOpen(), padSetActAlign(), padSetActDirect(), padSetButtonInfo(), and padSetMainMode().
struct { ... } padSlotMaxArgs
PadState
struct pad_state PadState[2][8] static
Port state data
Definition at line 154 of file libpad.c.
Referenced by padGetDmaStr(), padPortClose(), padPortInit(), and padPortOpen().
padStateString
const char padStateString[8][16] static
Initial value:
= {"DISCONNECT", "FINDPAD",
                                           "FINDCTP1", "", "", "EXECCMD",
                                           "STABLE", "ERROR"}
Definition at line 146 of file libpad.c.
Referenced by padStateInt2String().
port
s32 port
Definition at line 176 of file libpad.c.
Referenced by find_controllers(), initializePad(), main(), mcChdir(), mcDelete(), mcFormat(), mcGetDir(), mcGetEntSpace(), mcGetInfo(), mcMkDir(), mcOpen(), mcReadPage(), mcRename(), mcSetFileInfo(), mcUnformat(), mcWritePage(), mtapGetConnection(), mtapPortClose(), mtapPortOpen(), pad_open(), padEnterPressMode(), padExitPressMode(), padGetButtonMask(), padGetConnection(), padGetDmaStr(), padGetReqState(), padGetSlotMax(), padGetState(), padInfoAct(), padInfoMode(), padInfoPressMode(), padPortClose(), padPortOpen(), padRead(), padSetActAlign(), padSetActDirect(), padSetButtonInfo(), padSetMainMode(), padSetReqState(), padStartAct(), padStopAct(), padWait(), rmGetDmaStr(), RMMan_Close(), RMMan_Open(), RMMan_Read(), and waitPadReady().
result
s32 result
Definition at line 166 of file libpad.c.
slot
s32 slot
Definition at line 176 of file libpad.c.
Referenced by find_controllers(), initializePad(), main(), mcChdir(), mcDelete(), mcFormat(), mcGetDir(), mcGetEntSpace(), mcGetInfo(), mcMkDir(), mcOpen(), mcReadPage(), mcRename(), mcSetFileInfo(), mcUnformat(), mcWritePage(), pad_open(), padEnterPressMode(), padExitPressMode(), padGetButtonMask(), padGetConnection(), padGetDmaStr(), padGetReqState(), padGetState(), padInfoAct(), padInfoMode(), padInfoPressMode(), padPortClose(), padPortOpen(), padRead(), padSetActAlign(), padSetActDirect(), padSetButtonInfo(), padSetMainMode(), padSetReqState(), RMMan_Close(), RMMan_Open(), RMMan_Read(), and waitPadReady().
unknown
s32 unknown[4]
Definition at line 165 of file libpad.c.
unknown2
s32 unknown2
Definition at line 167 of file libpad.c.