ps2sdk: ee/rpc/remote/src/librm.c File Reference
librm.c File Reference
#include <stdio.h>
#include <tamtypes.h>
#include <sifrpc.h>
#include <kernel.h>
#include <string.h>
#include "librm.h"
Data Structures
struct port_state
Functions
static struct rmEEData * rmGetDmaStr (int port, int slot)
int RMMan_Init (void)
u32 RMMan_GetModuleVersion (void)
int RMMan_Open (int port, int slot, void *pData)
int RMMan_End (void)
int RMMan_Close (int port, int slot)
void RMMan_Read (int port, int slot, struct remote_data *data)
Variables
static SifRpcClientData_t rmmanif
static struct rmRpcPacket buffer
static int rmman_init = 0
static struct port_state ports [2]
Detailed Description
RPC Interface for PS2 Remote Control Driver (RMMAN)
Definition in file librm.c.
Function Documentation
rmGetDmaStr()
static struct rmEEData* rmGetDmaStr (int port, int slot) static
Definition at line 36 of file librm.c.
 {
    struct rmEEData *pdata;
    pdata = ports[port].rmData;
    SyncDCache(pdata, (u8 *)pdata + 256);
    return pdata;
    if(pdata[0].frame < pdata[1].frame) {
       return &pdata[1];
    }
    else {
       return &pdata[0];
    }
 }
References rmEEData::frame, port, ports, port_state::rmData, and SyncDCache().
Referenced by RMMan_Read().
RMMan_Close()
int RMMan_Close (int port, int slot)
Definition at line 138 of file librm.c.
 {
    if((port < 0) || (port > 1) || (slot != 0))
    {
       printf("Error, port must be 0 or 1 and slot set to 0\n");
       return 0;
    }
    if(!ports[port].opened)
    {
       return 0;
    }
    buffer.cmd.command = RMMAN_RPCFUNC_CLOSE;
    buffer.cmd.port = port;
    buffer.cmd.slot = slot;
    if (SifCallRpc(&rmmanif, 0, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
        return 0;
    return buffer.cmd.result;
 }
References buffer, rmRpcPacket::cmd, NULL, port, ports, RMMAN_RPCFUNC_CLOSE, rmmanif, SifCallRpc(), and slot.
Referenced by main().
RMMan_End()
int RMMan_End (void)
Definition at line 127 of file librm.c.
 {
    buffer.cmd.command = RMMAN_RPCFUNC_END;
    if (SifCallRpc(&rmmanif, 0, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
        return 0;
    return buffer.cmd.result;
 }
References buffer, rmRpcPacket::cmd, NULL, RMMAN_RPCFUNC_END, rmmanif, and SifCallRpc().
Referenced by main().
RMMan_GetModuleVersion()
u32 RMMan_GetModuleVersion (void)
Definition at line 87 of file librm.c.
 {
    buffer.cmd.command = RMMAN_RPCFUNC_VERSION;
    if (SifCallRpc(&rmmanif, 0, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
        return 0;
    return buffer.cmd.result;
 }
References buffer, rmRpcPacket::cmd, NULL, RMMAN_RPCFUNC_VERSION, rmmanif, and SifCallRpc().
Referenced by main().
RMMan_Init()
int RMMan_Init (void)
Definition at line 54 of file librm.c.
 {
    if(rmman_init)
     {
       printf("RMMan Library already initialised\n");
       return 0;
     }
    rmmanif.server = NULL;
    do {
       if (SifBindRpc(&rmmanif, RMMAN_RPC_ID, 0) < 0) {
          return -1;
       }
       nopdelay();
    } while(!rmmanif.server);
    buffer.cmd.command = RMMAN_RPCFUNC_INIT;
    if (SifCallRpc(&rmmanif, 0, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
        return -1;
    ports[0].opened = 0;
    ports[0].rmData = NULL;
    ports[1].opened = 1;
    ports[1].rmData = NULL;
    rmman_init = 1;
    return buffer.cmd.result;
 }
References buffer, rmRpcPacket::cmd, nopdelay(), NULL, port_state::opened, ports, port_state::rmData, rmman_init, RMMAN_RPC_ID, RMMAN_RPCFUNC_INIT, rmmanif, SifRpcClientData_t::server, SifBindRpc(), and SifCallRpc().
Referenced by main().
RMMan_Open()
int RMMan_Open (int port, int slot, void * pData)
Definition at line 98 of file librm.c.
 {
    if((port < 0) || (port > 1) || (slot != 0))
    {
       printf("Error, port must be 0 or 1 and slot set to 0\n");
       return 0;
    }
    if((u32) pData & 0x3F)
    {
       printf("Error, pData not aligned to 64byte boundary");
       return 0;
    }
    buffer.cmd.command = RMMAN_RPCFUNC_OPEN;
    buffer.cmd.port = port;
    buffer.cmd.slot = slot;
    buffer.cmd.data = pData;
    if (SifCallRpc(&rmmanif, 0, 0, &buffer, 128, &buffer, 128, NULL, NULL) < 0)
        return 0;
    ports[port].opened = 1;
    ports[port].rmData = pData;
    return buffer.cmd.result;
 }
References buffer, rmRpcPacket::cmd, NULL, port_state::opened, port, ports, port_state::rmData, RMMAN_RPCFUNC_OPEN, rmmanif, SifCallRpc(), and slot.
Referenced by main().
RMMan_Read()
void RMMan_Read (int port, int slot, struct remote_data * data)
Definition at line 162 of file librm.c.
 {
    struct rmEEData *pdata;
    if((port < 0) || (port > 1) || (slot != 0))
    {
       printf("Error, port must be 0 or 1 and slot set to 0\n");
       return;
    }
    pdata = rmGetDmaStr(port, slot);
    memcpy(data, pdata->data, 8);
 }
References rmEEData::data, data, port, rmGetDmaStr(), and slot.
Referenced by main().
Variable Documentation
buffer
struct rmRpcPacket buffer static
Definition at line 23 of file librm.c.
Referenced by RMMan_Close(), RMMan_End(), RMMan_GetModuleVersion(), RMMan_Init(), and RMMan_Open().
ports
struct port_state ports[2] static
Definition at line 25 of file librm.c.
Referenced by rmGetDmaStr(), RMMan_Close(), RMMan_Init(), and RMMan_Open().
rmman_init
int rmman_init = 0 static
Definition at line 25 of file librm.c.
Referenced by RMMan_Init().
rmmanif
SifRpcClientData_t rmmanif static
Definition at line 23 of file librm.c.
Referenced by RMMan_Close(), RMMan_End(), RMMan_GetModuleVersion(), RMMan_Init(), and RMMan_Open().