ps2sdk: ee/libvux/include/libvux.h File Reference
libvux.h File Reference
Data Structures
struct VU_MATRIX
struct VU_VECTOR
struct VU_SXYZ
struct VU_SXYZF
struct VU_CVECTOR
struct VU_FCVECTOR
struct VU_FLAT_LIGHT
Macros
#define VU_LIGHT_TYPE_FLAT 0x10
#define ftoi4(f) ((int)((f)*16.0f))
#define deg2radian(angle) ((angle*3.1415926535f)/180)
#define radian2deg(radian) ((180.0f / 3.1415926535f) * (radian))
Functions
void VuInit (void)
void VuSetGeometryXYOffset (unsigned short x, unsigned short y)
void VuSetProjection (float z)
void VuSetProjectionMatrix (VU_MATRIX *projection)
void VuSetProjectionType (unsigned int type)
void VuSetWorldMatrix (VU_MATRIX *world)
void VuSetViewMatrix (VU_MATRIX *view)
void VuSetLocalScreenMatrix (VU_MATRIX *m)
void VuSetProjectionNearPlaneWH (unsigned int w, unsigned int h)
void VuSetAmbientLight (float r, float g, float b)
void Vu0IdMatrix (VU_MATRIX *m)
void Vu0ResetMatrix (VU_MATRIX *m)
void Vu0TransMatrix (VU_MATRIX *m, VU_VECTOR *t)
void Vu0TransMatrixXYZ (VU_MATRIX *m, float x, float y, float z)
void Vu0ScaleMatrix (VU_MATRIX *m, VU_VECTOR *s)
void Vu0ScaleMatrixXYZ (VU_MATRIX *m, float x, float y, float z)
void Vu0MulMatrix (VU_MATRIX *m0, VU_MATRIX *m1, VU_MATRIX *out)
void Vu0ApplyMatrix (VU_MATRIX *m, VU_VECTOR *v0, VU_VECTOR *out)
void Vu0ApplyRotMatrix (VU_MATRIX *m, VU_VECTOR *v0, VU_VECTOR *out)
void Vu0CopyMatrix (VU_MATRIX *dest, VU_MATRIX *src)
float Vu0DotProduct (VU_VECTOR *v0, VU_VECTOR *v1)
void VuxIdMatrix (VU_MATRIX *m)
void VuxResetMatrix (VU_MATRIX *m)
void VuxRotMatrix (VU_MATRIX *m, VU_VECTOR *v)
void VuxRotMatrixX (VU_MATRIX *m, float x)
void VuxRotMatrixY (VU_MATRIX *m, float y)
void VuxRotMatrixZ (VU_MATRIX *m, float z)
void VuxRotMatrixXYZ (VU_MATRIX *m, float x, float y, float z)
void VuxTransMatrix (VU_MATRIX *m, VU_VECTOR *v0)
void VuxTransMatrixXYZ (VU_MATRIX *m, float x, float y, float z)
void VuxScaleMatrix (VU_MATRIX *m, VU_VECTOR *s)
void VuxScaleMatrixXYZ (VU_MATRIX *m, float x, float y, float z)
void VuxMulMatrix (VU_MATRIX *m0, VU_MATRIX *m1, VU_MATRIX *out)
void VuxInverseMatrix (VU_MATRIX *in, VU_MATRIX *mat)
void VuxCopyMatrix (VU_MATRIX *dest, VU_MATRIX *src)
void VuxApplyMatrix (VU_MATRIX *m, VU_VECTOR *v0, VU_VECTOR *out)
void VuxApplyRotMatrix (VU_MATRIX *m, VU_VECTOR *v0, VU_VECTOR *out)
float VuxDotProduct (VU_VECTOR *v0, VU_VECTOR *v1)
VU_VECTOR VuxCrossProduct (VU_VECTOR *v0, VU_VECTOR *v1)
void VuxCrossProduct0 (VU_VECTOR *v0, VU_VECTOR *v1, VU_VECTOR *out)
void VuxVectorNormal (VU_VECTOR *v)
void VuxVectorNormal0 (VU_VECTOR *in, VU_VECTOR *out)
void VuxApplyMatrixLS (VU_VECTOR *v0, VU_VECTOR *out)
void VuxApplyRotMatrixLS (VU_VECTOR *v0, VU_VECTOR *out)
void VuxMakeLocalScreenMatrix (VU_MATRIX *out, VU_MATRIX *world, VU_MATRIX *view)
void VuxMakeLocalScreenMatrix2 (VU_MATRIX *out, VU_MATRIX *world, VU_MATRIX *view, VU_MATRIX *projection)
void VuxMakeViewMatrix (VU_MATRIX *out, VU_VECTOR *rot, VU_VECTOR *pos, VU_VECTOR *scale)
void VuxMakeLookAtViewMatrix (VU_MATRIX *out, VU_VECTOR *eye, VU_VECTOR *target, VU_VECTOR *up)
void VuxMakeProjectionMatrix (VU_MATRIX *proj, float near_plane_w, float near_plane_h, float near_plane_z, float far_plane_z)
void VuxUpdateLocalScreenMatrix (void)
void VuxRotTrans (VU_VECTOR *v0, VU_VECTOR *out)
void VuxRotTrans3 (VU_VECTOR *v0, VU_VECTOR *v1, VU_VECTOR *v2, VU_VECTOR *tv0, VU_VECTOR *tv1, VU_VECTOR *tv2)
void VuxRotTransN (VU_VECTOR *verts, VU_VECTOR *tverts, unsigned int num_verts)
void VuxPers (VU_VECTOR *v0, VU_SXYZ *sxyz0)
void VuxPers3 (VU_VECTOR *v0, VU_VECTOR *v1, VU_VECTOR *v2, VU_SXYZ *sxyz0, VU_SXYZ *sxyz1, VU_SXYZ *sxyz2)
void VuxPersN (VU_VECTOR *verts, VU_SXYZ *sxyz, unsigned int num_verts)
int VuxPersClip3 (VU_VECTOR *v0, VU_VECTOR *v1, VU_VECTOR *v2, VU_SXYZ *sxyz0, VU_SXYZ *sxyz1, VU_SXYZ *sxyz2)
float VuxRotTransPers (VU_VECTOR *v0, VU_SXYZ *sxyz0)
float VuxRotTransPers3 (VU_VECTOR *v0, VU_VECTOR *v1, VU_VECTOR *v2, VU_SXYZ *sxyz0, VU_SXYZ *sxyz1, VU_SXYZ *sxyz2)
void VuxRotTransPersN (VU_VECTOR *verts, VU_SXYZ *sxyz, unsigned int num_verts)
int VuxRotTransPersClip3 (VU_VECTOR *v0, VU_VECTOR *v1, VU_VECTOR *v2, VU_SXYZ *sxyz0, VU_SXYZ *sxyz1, VU_SXYZ *sxyz2)
int VuxClipSxyz (VU_SXYZ *sxyz0, VU_SXYZ *sxyz1, VU_SXYZ *sxyz2)
int VuxLightNormal (VU_VECTOR *normal, VU_CVECTOR *col0, void *light, unsigned int light_type, VU_CVECTOR *out0)
Variables
VU_MATRIX VuWorldMatrix
VU_MATRIX VuViewMatrix
VU_MATRIX VuPrjectionMatrix
VU_MATRIX VuLocalScreenMatrix
Detailed Description
VU library functions.
Definition in file libvux.h.
Macro Definition Documentation
deg2radian
#define deg2radian (angle) ((angle*3.1415926535f)/180)
Definition at line 108 of file libvux.h.
ftoi4
#define ftoi4 (f) ((int)((f)*16.0f))
Definition at line 104 of file libvux.h.
radian2deg
#define radian2deg (radian) ((180.0f / 3.1415926535f) * (radian))
Definition at line 112 of file libvux.h.
VU_LIGHT_TYPE_FLAT
#define VU_LIGHT_TYPE_FLAT 0x10
Definition at line 32 of file libvux.h.
Function Documentation
Vu0ApplyMatrix()
void Vu0ApplyMatrix (VU_MATRIX * m, VU_VECTOR * v0, VU_VECTOR * out)
Definition at line 218 of file vuhw.c.
 {
         /*
         out->x = m->m[0][0]*v0->x + m->m[1][0]*v0->y + m->m[2][0]*v0->z + m->m[3][0]*v0->w;
         out->y = m->m[0][1]*v0->x + m->m[1][1]*v0->y + m->m[2][1]*v0->z + m->m[3][1]*v0->w;
         out->z = m->m[0][2]*v0->x + m->m[1][2]*v0->y + m->m[2][2]*v0->z + m->m[3][2]*v0->w;
         out->w = m->m[0][3]*v0->x + m->m[1][3]*v0->y + m->m[2][3]*v0->z + m->m[3][3]*v0->w;
         */
         asm __volatile__(
 #if __GNUC__ > 3
         "lqc2            $vf20,  0x00(%1)  \n"
         "lqc2            $vf16,  0x00(%0)  \n"
         "lqc2            $vf17,  0x10(%0)  \n"
         "lqc2            $vf18,  0x20(%0)  \n"
         "lqc2            $vf19,  0x30(%0)  \n"
         "vmulax.xyzw     $ACC,   $vf16,$vf20 \n"
         "vmadday.xyzw    $ACC,   $vf17,$vf20 \n"
         "vmaddaz.xyzw    $ACC,   $vf18,$vf20 \n"
         "vmaddw.xyzw     $vf20,  $vf19,$vf20 \n"
         "sqc2            $vf20,0x00(%2)  \n"
 #else
         "lqc2            vf20,  0x00(%1)        \n"
         "lqc2            vf16,  0x00(%0)        \n"
         "lqc2            vf17,  0x10(%0)        \n"
         "lqc2            vf18,  0x20(%0)        \n"
         "lqc2            vf19,  0x30(%0)        \n"
         "vmulax.xyzw     ACC,   vf16,vf20       \n"
         "vmadday.xyzw    ACC,   vf17,vf20       \n"
         "vmaddaz.xyzw    ACC,   vf18,vf20       \n"
         "vmaddw.xyzw     vf20,  vf19,vf20       \n"
         "sqc2            vf20,0x00(%2)  \n"
 #endif
         : : "r"(m), "r"(v0), "r"(out)
     );
 }
References v0.
Vu0ApplyRotMatrix()
void Vu0ApplyRotMatrix (VU_MATRIX * m, VU_VECTOR * v0, VU_VECTOR * out)
Definition at line 256 of file vuhw.c.
 {
         /*
         out->x = m->m[0][0]*v0->x + m->m[1][0]*v0->y + m->m[2][0]*v0->z;
         out->y = m->m[0][1]*v0->x + m->m[1][1]*v0->y + m->m[2][1]*v0->z;
         out->z = m->m[0][2]*v0->x + m->m[1][2]*v0->y + m->m[2][2]*v0->z;
         */
         asm __volatile__(
 #if __GNUC__ > 3
         "lqc2            $vf20,  0x00(%1)  \n"
         "lqc2            $vf16,  0x00(%0)  \n"
         "lqc2            $vf17,  0x10(%0)  \n"
         "lqc2            $vf18,  0x20(%0)  \n"
         "vmulax.xyz     $ACC,   $vf16,$vf20  \n"
         "vmadday.xyz  $ACC,   $vf17,$vf20  \n"
         "vmaddz.xyz     $vf20,  $vf18,$vf20  \n"
         "vmulw.w     $vf20, $vf0, $vf0  \n" // out->w = 1.0f
         "sqc2            $vf20,  0x00(%2)  \n" // copy result to out
 #else
         "lqc2            vf20,  0x00(%1)        \n"
         "lqc2            vf16,  0x00(%0)        \n"
         "lqc2            vf17,  0x10(%0)        \n"
         "lqc2            vf18,  0x20(%0)        \n"
         "vmulax.xyz              ACC,   vf16,vf20       \n"
         "vmadday.xyz     ACC,   vf17,vf20       \n"
         "vmaddz.xyz              vf20,  vf18,vf20       \n"
                 "vmulw.w                 vf20,  vf0, vf0        \n"     // out->w = 1.0f
         "sqc2            vf20,  0x00(%2)        \n" // copy result to out
 #endif
         : : "r"(m), "r"(v0), "r"(out)
     );
 }
References v0.
Vu0CopyMatrix()
void Vu0CopyMatrix (VU_MATRIX * dest, VU_MATRIX * src)
Definition at line 291 of file vuhw.c.
 {
         asm __volatile__ (
 #if __GNUC__ > 3
    "lqc2   $vf1,   0(%1) \n"   // load 1 qword from ee
    "lqc2   $vf2,  16(%1) \n"   // load 1 qword from ee
    "lqc2   $vf3,  32(%1) \n"   // load 1 qword from ee
    "lqc2   $vf4,  48(%1) \n"   // load 1 qword from ee
    "sqc2   $vf1,   0(%0) \n"   // store 1 qword in ee
    "sqc2   $vf2,  16(%0) \n"   // store 1 qword in ee
    "sqc2   $vf3,  32(%0) \n"   // store 1 qword in ee
    "sqc2   $vf4,  48(%0) \n"   // store 1 qword in ee
 #else
    "lqc2                vf1,   0(%1)    \n"             // load 1 qword from ee
    "lqc2                vf2,  16(%1)    \n"             // load 1 qword from ee
    "lqc2                vf3,  32(%1)    \n"             // load 1 qword from ee
    "lqc2                vf4,  48(%1)    \n"             // load 1 qword from ee
    "sqc2                vf1,   0(%0)    \n"             // store 1 qword in ee
    "sqc2                vf2,  16(%0)    \n"             // store 1 qword in ee
    "sqc2                vf3,  32(%0)    \n"             // store 1 qword in ee
    "sqc2                vf4,  48(%0)    \n"             // store 1 qword in ee
 #endif
    : : "r" (dest), "r" (src)
    );
 }
Vu0DotProduct()
float Vu0DotProduct (VU_VECTOR * v0, VU_VECTOR * v1)
Definition at line 321 of file vuhw.c.
 {
         float ret=0;
         /*      ret = (v0.x*v1.x + v0.y*v1.y + v0.z*v1.z);*/
         asm __volatile__ (
 #if __GNUC__ > 3
    "lqc2 $vf1, 0(%1) \n"   // load 1 qword from ee
    "lqc2 $vf2, 0(%2) \n"   // load 1 qword from ee
    "vmul.xyz  $vf3, $vf1, $vf2  \n"        // mul v0 by v1
    "vaddy.x  $vf3, $vf3, $vf3y \n"   // add x+y and store in x
    "vaddz.x  $vf3, $vf3, $vf3z \n"   // add z+x and store in x
    "qmfc2 %0, $vf3    \n"      // copy vector to ee reg
 #else
    "lqc2        vf1, 0(%1)      \n"             // load 1 qword from ee
    "lqc2        vf2, 0(%2)      \n"             // load 1 qword from ee
    "vmul.xyz    vf3, vf1, vf2   \n"             // mul v0 by v1
    "vaddy.x     vf3, vf3, vf3y  \n"             // add x+y and store in x
    "vaddz.x     vf3, vf3, vf3z  \n"             // add z+x and store in x
    "qmfc2       %0, vf3         \n"             // copy vector to ee reg
 #endif
    : "=r" (ret) : "r" (v0), "r" (v1)
    );
         return ret;
 }
References v0, and v1.
Vu0IdMatrix()
void Vu0IdMatrix (VU_MATRIX * m)
Definition at line 13 of file vuhw.c.
 {
         Vu0ResetMatrix(m);
 }
References Vu0ResetMatrix().
Vu0MulMatrix()
void Vu0MulMatrix (VU_MATRIX * m0, VU_MATRIX * m1, VU_MATRIX * out)
Definition at line 148 of file vuhw.c.
 {
         asm __volatile__ (
 #if __GNUC__ > 3
    "lqc2   $vf1, 0x00(%0)  \n"
    "lqc2   $vf2, 0x10(%0)  \n"
    "lqc2   $vf3, 0x20(%0)  \n"
    "lqc2   $vf4, 0x30(%0)  \n"
    "lqc2   $vf5, 0x00(%1)  \n"
    "lqc2   $vf6, 0x10(%1)  \n"
    "lqc2   $vf7, 0x20(%1)  \n"
    "lqc2   $vf8, 0x30(%1)  \n"
    "vmulax.xyzw    $ACC, $vf5, $vf1  \n"
    "vmadday.xyzw $ACC, $vf6, $vf1  \n"
    "vmaddaz.xyzw $ACC, $vf7, $vf1  \n"
    "vmaddw.xyzw    $vf1, $vf8, $vf1  \n"
    "vmulax.xyzw    $ACC, $vf5, $vf2  \n"
    "vmadday.xyzw $ACC, $vf6, $vf2  \n"
    "vmaddaz.xyzw $ACC, $vf7, $vf2  \n"
    "vmaddw.xyzw    $vf2, $vf8, $vf2  \n"
    "vmulax.xyzw    $ACC, $vf5, $vf3  \n"
    "vmadday.xyzw $ACC, $vf6, $vf3  \n"
    "vmaddaz.xyzw $ACC, $vf7, $vf3  \n"
    "vmaddw.xyzw    $vf3, $vf8, $vf3  \n"
    "vmulax.xyzw    $ACC, $vf5, $vf4  \n"
    "vmadday.xyzw $ACC, $vf6, $vf4  \n"
    "vmaddaz.xyzw $ACC, $vf7, $vf4  \n"
    "vmaddw.xyzw    $vf4, $vf8, $vf4  \n"
    "sqc2   $vf1, 0x00(%2)  \n"
    "sqc2   $vf2, 0x10(%2)  \n"
    "sqc2   $vf3, 0x20(%2)  \n"
    "sqc2   $vf4, 0x30(%2)  \n"
 #else
    "lqc2                vf1, 0x00(%0)   \n"
    "lqc2                vf2, 0x10(%0)   \n"
    "lqc2                vf3, 0x20(%0)   \n"
    "lqc2                vf4, 0x30(%0)   \n"
    "lqc2                vf5, 0x00(%1)   \n"
    "lqc2                vf6, 0x10(%1)   \n"
    "lqc2                vf7, 0x20(%1)   \n"
    "lqc2                vf8, 0x30(%1)   \n"
    "vmulax.xyzw         ACC, vf5, vf1   \n"
    "vmadday.xyzw        ACC, vf6, vf1   \n"
    "vmaddaz.xyzw        ACC, vf7, vf1   \n"
    "vmaddw.xyzw         vf1, vf8, vf1   \n"
    "vmulax.xyzw         ACC, vf5, vf2   \n"
    "vmadday.xyzw        ACC, vf6, vf2   \n"
    "vmaddaz.xyzw        ACC, vf7, vf2   \n"
    "vmaddw.xyzw         vf2, vf8, vf2   \n"
    "vmulax.xyzw         ACC, vf5, vf3   \n"
    "vmadday.xyzw        ACC, vf6, vf3   \n"
    "vmaddaz.xyzw        ACC, vf7, vf3   \n"
    "vmaddw.xyzw         vf3, vf8, vf3   \n"
    "vmulax.xyzw         ACC, vf5, vf4   \n"
    "vmadday.xyzw        ACC, vf6, vf4   \n"
    "vmaddaz.xyzw        ACC, vf7, vf4   \n"
    "vmaddw.xyzw         vf4, vf8, vf4   \n"
    "sqc2                vf1, 0x00(%2)   \n"
    "sqc2                vf2, 0x10(%2)   \n"
    "sqc2                vf3, 0x20(%2)   \n"
    "sqc2                vf4, 0x30(%2)   \n"
 #endif
    : :  "r" (m0), "r" (m1), "r" (out)
   );
 }
Vu0ResetMatrix()
void Vu0ResetMatrix (VU_MATRIX * m)
Definition at line 18 of file vuhw.c.
 {
         asm __volatile__(
 #if __GNUC__ > 3
         "vmr32.xyzw  $vf18, $vf0    \n"
         "sqc2        $vf0, 0x30(%0)   \n"
         "vmr32.xyzw  $vf17, $vf18   \n"
         "sqc2        $vf18, 0x20(%0)    \n"
         "vmr32.xyzw  $vf16, $vf17   \n"
         "sqc2        $vf17, 0x10(%0)    \n"
         "sqc2        $vf16, 0x00(%0)    \n"
 #else
         "vmr32.xyzw  vf18, vf00                 \n"
         "sqc2        vf00, 0x30(%0)             \n"
         "vmr32.xyzw  vf17, vf18                 \n"
         "sqc2        vf18, 0x20(%0)             \n"
         "vmr32.xyzw  vf16, vf17                 \n"
         "sqc2        vf17, 0x10(%0)             \n"
         "sqc2        vf16, 0x00(%0)             \n"
 #endif
         : : "r"(m)
     );
 }
Referenced by Vu0IdMatrix().
Vu0ScaleMatrix()
void Vu0ScaleMatrix (VU_MATRIX * m, VU_VECTOR * s)
Definition at line 93 of file vuhw.c.
 {
         asm __volatile__ (
 #if __GNUC__ > 3
         "lqc2    $vf1,   0(%1) \n"      // load 1 qword from 't' to vu's vf1
         "lqc2    $vf10,  0(%0) \n"      // load m[0][0]
         "lqc2    $vf11, 16(%0) \n"      // load m[1][0]
         "lqc2    $vf12, 32(%0) \n"      // load m[2][0]
  //  "lqc2    $vf123,48(%0) \n"        // load m[3][0]
         "vmulx.x $vf10, $vf10, $vf1x \n"    // multiply [0][0] by s->x and store in [0][0]
         "vmuly.y $vf11, $vf11, $vf1y \n"
         "vmulz.z $vf12, $vf12, $vf1z \n"
         "sqc2    $vf10,  0(%0) \n"      // store v m[0][0]
         "sqc2    $vf11, 16(%0) \n"      // store v m[1][0]
         "sqc2    $vf12, 32(%0) \n"      // store v m[2][0]
 //   "sqc2    $vf1, 48(%0)  \n"        // store v m[3][0]
 #else
         "lqc2           vf1,   0(%1)    \n"             // load 1 qword from 't' to vu's vf1
         "lqc2           vf10,  0(%0)    \n"             // load m[0][0]
         "lqc2           vf11, 16(%0)    \n"             // load m[1][0]
         "lqc2           vf12, 32(%0)    \n"             // load m[2][0]
  //  "lqc2              vf123,48(%0)    \n"             // load m[3][0]
         "vmulx.x        vf10, vf10, vf1x        \n"     // multiply [0][0] by s->x and store in [0][0]
         "vmuly.y        vf11, vf11, vf1y        \n"
         "vmulz.z        vf12, vf12, vf1z        \n"
         "sqc2           vf10,  0(%0)    \n"             // store v m[0][0]
         "sqc2           vf11, 16(%0)    \n"             // store v m[1][0]
         "sqc2           vf12, 32(%0)    \n"             // store v m[2][0]
 //   "sqc2              vf1, 48(%0)     \n"             // store v m[3][0]
 #endif
    : : "r" (m), "r" (s)
    );
 }
References s.
Referenced by Vu0ScaleMatrixXYZ().
Vu0ScaleMatrixXYZ()
void Vu0ScaleMatrixXYZ (VU_MATRIX * m, float x, float y, float z)
Definition at line 136 of file vuhw.c.
 {
         VU_VECTOR       s;
         s.x = x;
         s.y = y;
         s.z = z;
         s.w = 1.0f;
         Vu0ScaleMatrix(m, &s);
 }
References s, Vu0ScaleMatrix(), x, and y.
Vu0TransMatrix()
void Vu0TransMatrix (VU_MATRIX * m, VU_VECTOR * t)
Definition at line 61 of file vuhw.c.
 {
         asm __volatile__ (
 #if __GNUC__ > 3
    "lqc2    $vf1,  0(%1)  \n"      // load 1 qword from 't' to vu's vf1
    "sqc2    $vf1, 48(%0)  \n"      // store vf1 data in 'm' with 48 bytes offset which is m[3][0]
 #else
    "lqc2                vf1,  0(%1)     \n"             // load 1 qword from 't' to vu's vf1
    "sqc2                vf1, 48(%0)     \n"             // store vf1 data in 'm' with 48 bytes offset which is m[3][0]
 #endif
    : : "r" (m), "r" (t)
    );
 }
Referenced by Vu0TransMatrixXYZ().
Vu0TransMatrixXYZ()
void Vu0TransMatrixXYZ (VU_MATRIX * m, float x, float y, float z)
Definition at line 77 of file vuhw.c.
 {
         VU_VECTOR t;
         t.x     = x;
         t.y     = y;
         t.z     = z;
         t.w     = 1.0f;
         Vu0TransMatrix(m, &t);
 }
References Vu0TransMatrix(), VU_VECTOR::w, VU_VECTOR::x, x, VU_VECTOR::y, y, and VU_VECTOR::z.
VuInit()
void VuInit (void)
Definition at line 70 of file vux.c.
 {
 }
VuSetAmbientLight()
void VuSetAmbientLight (float r, float g, float b)
Definition at line 154 of file vux.c.
 {
         vu_light_ambient.r = r;
         vu_light_ambient.g = g;
         vu_light_ambient.b = b;
         vu_light_ambient.a = 1.0f;
 }
References VU_FCVECTOR::a, VU_FCVECTOR::b, VU_FCVECTOR::g, VU_FCVECTOR::r, and vu_light_ambient.
VuSetGeometryXYOffset()
void VuSetGeometryXYOffset (unsigned short x, unsigned short y)
Definition at line 78 of file vux.c.
 {
         vu_offset_x = x;
         vu_offset_y = y;
 }
References vu_offset_x, vu_offset_y, x, and y.
VuSetLocalScreenMatrix()
void VuSetLocalScreenMatrix (VU_MATRIX * m)
Definition at line 135 of file vux.c.
 {
         VuLocalScreenMatrix = *m;
 }
References VuLocalScreenMatrix.
Referenced by VuxUpdateLocalScreenMatrix().
VuSetProjection()
void VuSetProjection (float z)
Definition at line 88 of file vux.c.
 {
         vu_projection = z;
         vu_projection_type = 0;
 }
References vu_projection, and vu_projection_type.
VuSetProjectionMatrix()
void VuSetProjectionMatrix (VU_MATRIX * projection)
Definition at line 98 of file vux.c.
 {
         VuPrjectionMatrix       = *projection;
         vu_projection_type      = 1; // use projection matrix
 }
References vu_projection_type, and VuPrjectionMatrix.
VuSetProjectionNearPlaneWH()
void VuSetProjectionNearPlaneWH (unsigned int w, unsigned int h)
Definition at line 144 of file vux.c.
 {
         vu_near_plane_w = w;
         vu_near_plane_h = h;
 }
References vu_near_plane_h, and vu_near_plane_w.
VuSetProjectionType()
void VuSetProjectionType (unsigned int type)
Definition at line 108 of file vux.c.
 {
         vu_projection_type = type;
 }
References vu_projection_type.
VuSetViewMatrix()
void VuSetViewMatrix (VU_MATRIX * view)
Definition at line 125 of file vux.c.
 {
         VuViewMatrix =          *view;
 }
References VuViewMatrix.
VuSetWorldMatrix()
void VuSetWorldMatrix (VU_MATRIX * world)
Definition at line 116 of file vux.c.
 {
         VuWorldMatrix =         *world;
 }
References VuWorldMatrix.
VuxApplyMatrix()
void VuxApplyMatrix (VU_MATRIX * m, VU_VECTOR * v0, VU_VECTOR * out)
Definition at line 383 of file vusw.c.
 {
         out->x = m->m[0][0]*v0->x + m->m[1][0]*v0->y + m->m[2][0]*v0->z + m->m[3][0]*v0->w;
         out->y = m->m[0][1]*v0->x + m->m[1][1]*v0->y + m->m[2][1]*v0->z + m->m[3][1]*v0->w;
         out->z = m->m[0][2]*v0->x + m->m[1][2]*v0->y + m->m[2][2]*v0->z + m->m[3][2]*v0->w;
         out->w = m->m[0][3]*v0->x + m->m[1][3]*v0->y + m->m[2][3]*v0->z + m->m[3][3]*v0->w;
 }
References VU_MATRIX::m, v0, VU_VECTOR::w, VU_VECTOR::x, VU_VECTOR::y, and VU_VECTOR::z.
Referenced by VuxApplyMatrixLS().
VuxApplyMatrixLS()
void VuxApplyMatrixLS (VU_VECTOR * v0, VU_VECTOR * out)
Definition at line 484 of file vusw.c.
 {
 //      Vu0ApplyMatrix(&VuLocalScreenMatrix, v0, out);
         VuxApplyMatrix(&VuLocalScreenMatrix, v0, out);
 }
References v0, VuLocalScreenMatrix, and VuxApplyMatrix().
Referenced by VuxRotTrans(), VuxRotTrans3(), and VuxRotTransN().
VuxApplyRotMatrix()
void VuxApplyRotMatrix (VU_MATRIX * m, VU_VECTOR * v0, VU_VECTOR * out)
Definition at line 396 of file vusw.c.
 {
         out->x = m->m[0][0]*v0->x + m->m[1][0]*v0->y + m->m[2][0]*v0->z;
         out->y = m->m[0][1]*v0->x + m->m[1][1]*v0->y + m->m[2][1]*v0->z;
         out->z = m->m[0][2]*v0->x + m->m[1][2]*v0->y + m->m[2][2]*v0->z;
         out->w = 1.0f;
 }
References VU_MATRIX::m, v0, VU_VECTOR::w, VU_VECTOR::x, VU_VECTOR::y, and VU_VECTOR::z.
Referenced by VuxApplyRotMatrixLS().
VuxApplyRotMatrixLS()
void VuxApplyRotMatrixLS (VU_VECTOR * v0, VU_VECTOR * out)
Definition at line 496 of file vusw.c.
 {
         VuxApplyRotMatrix(&VuLocalScreenMatrix, v0, out);
 }
References v0, VuLocalScreenMatrix, and VuxApplyRotMatrix().
VuxClipSxyz()
int VuxClipSxyz (VU_SXYZ * sxyz0, VU_SXYZ * sxyz1, VU_SXYZ * sxyz2)
Definition at line 894 of file vusw.c.
 {
         return (sxyz1->x - sxyz0->x) * (sxyz2->y - sxyz0->y) - (sxyz2->x - sxyz0->x) * (sxyz1->y - sxyz0->y);
 }
References VU_SXYZ::x, and VU_SXYZ::y.
Referenced by VuxPersClip3(), and VuxRotTransPersClip3().
VuxCopyMatrix()
void VuxCopyMatrix (VU_MATRIX * dest, VU_MATRIX * src)
Definition at line 366 of file vusw.c.
 {
         int i,j;
         for(i=0;i<4;i++)
         {
                 for(j=0;j<4;j++)
                 {
                         dest->m[i][j] = src->m[i][j];
                 }
         }
 }
References VU_MATRIX::m.
VuxCrossProduct()
VU_VECTOR VuxCrossProduct (VU_VECTOR * v0, VU_VECTOR * v1)
Definition at line 419 of file vusw.c.
 {
         VU_VECTOR       ret;
         ret.x = v0->y*v1->z - v0->z*v1->y;
         ret.y = v0->z*v1->x - v0->x*v1->z;
         ret.z = v0->x*v1->y - v0->y*v1->x;
         return ret;
 }
References v0, v1, VU_VECTOR::x, VU_VECTOR::y, and VU_VECTOR::z.
Referenced by VuxMakeLookAtViewMatrix().
VuxCrossProduct0()
void VuxCrossProduct0 (VU_VECTOR * v0, VU_VECTOR * v1, VU_VECTOR * out)
Definition at line 434 of file vusw.c.
 {
         out->x = v0->y*v1->z - v0->z*v1->y;
         out->y = v0->z*v1->x - v0->x*v1->z;
         out->z = v0->x*v1->y - v0->y*v1->x;
 }
References v0, v1, VU_VECTOR::x, VU_VECTOR::y, and VU_VECTOR::z.
VuxDotProduct()
float VuxDotProduct (VU_VECTOR * v0, VU_VECTOR * v1)
Definition at line 409 of file vusw.c.
 {
     return (v0->x*v1->x + v0->y*v1->y + v0->z*v1->z);
 }
References v0, and v1.
Referenced by VuxLightNormal(), and VuxMakeLookAtViewMatrix().
VuxIdMatrix()
void VuxIdMatrix (VU_MATRIX * m)
Definition at line 30 of file vusw.c.
 {
         VuxResetMatrix(m);
 }
References VuxResetMatrix().
Referenced by VuxMakeProjectionMatrix().
VuxInverseMatrix()
void VuxInverseMatrix (VU_MATRIX * in, VU_MATRIX * mat)
Definition at line 273 of file vusw.c.
 {
         int i,j;
         static float    *m,*out;
         float tmp[12]; /* temp array for pairs */
         float src[16]; /* array of transpose source matrix */
         float det; /* determinant */
         m       = (float *)in;
         out     = (float *)mat;
         /* transpose matrix */
         for ( i = 0; i < 4; i++)
         {
                 src[i] = m[i*4];
                 src[i + 4] = m[i*4 + 1];
                 src[i + 8] = m[i*4 + 2];
                 src[i + 12] = m[i*4 + 3];
         }
         /* calculate pairs for first 8 elements (cofactors) */
         tmp[0] = src[10] * src[15];
         tmp[1] = src[11] * src[14];
         tmp[2] = src[9] * src[15];
         tmp[3] = src[11] * src[13];
         tmp[4] = src[9] * src[14];
         tmp[5] = src[10] * src[13];
         tmp[6] = src[8] * src[15];
         tmp[7] = src[11] * src[12];
         tmp[8] = src[8] * src[14];
         tmp[9] = src[10] * src[12];
         tmp[10] = src[8] * src[13];
         tmp[11] = src[9] * src[12];
         /* calculate first 8 elements (cofactors) */
         out[0] = tmp[0]*src[5] + tmp[3]*src[6] + tmp[4]*src[7];
         out[0] -= tmp[1]*src[5] + tmp[2]*src[6] + tmp[5]*src[7];
         out[1] = tmp[1]*src[4] + tmp[6]*src[6] + tmp[9]*src[7];
         out[1] -= tmp[0]*src[4] + tmp[7]*src[6] + tmp[8]*src[7];
         out[2] = tmp[2]*src[4] + tmp[7]*src[5] + tmp[10]*src[7];
         out[2] -= tmp[3]*src[4] + tmp[6]*src[5] + tmp[11]*src[7];
         out[3] = tmp[5]*src[4] + tmp[8]*src[5] + tmp[11]*src[6];
         out[3] -= tmp[4]*src[4] + tmp[9]*src[5] + tmp[10]*src[6];
         out[4] = tmp[1]*src[1] + tmp[2]*src[2] + tmp[5]*src[3];
         out[4] -= tmp[0]*src[1] + tmp[3]*src[2] + tmp[4]*src[3];
         out[5] = tmp[0]*src[0] + tmp[7]*src[2] + tmp[8]*src[3];
         out[5] -= tmp[1]*src[0] + tmp[6]*src[2] + tmp[9]*src[3];
         out[6] = tmp[3]*src[0] + tmp[6]*src[1] + tmp[11]*src[3];
         out[6] -= tmp[2]*src[0] + tmp[7]*src[1] + tmp[10]*src[3];
         out[7] = tmp[4]*src[0] + tmp[9]*src[1] + tmp[10]*src[2];
         out[7] -= tmp[5]*src[0] + tmp[8]*src[1] + tmp[11]*src[2];
         /* calculate pairs for second 8 elements (cofactors) */
         tmp[0] = src[2]*src[7];
         tmp[1] = src[3]*src[6];
         tmp[2] = src[1]*src[7];
         tmp[3] = src[3]*src[5];
         tmp[4] = src[1]*src[6];
         tmp[5] = src[2]*src[5];
         tmp[6] = src[0]*src[7];
         tmp[7] = src[3]*src[4];
         tmp[8] = src[0]*src[6];
         tmp[9] = src[2]*src[4];
         tmp[10] = src[0]*src[5];
         tmp[11] = src[1]*src[4];
         /* calculate second 8 elements (cofactors) */
         out[8] = tmp[0]*src[13] + tmp[3]*src[14] + tmp[4]*src[15];
         out[8] -= tmp[1]*src[13] + tmp[2]*src[14] + tmp[5]*src[15];
         out[9] = tmp[1]*src[12] + tmp[6]*src[14] + tmp[9]*src[15];
         out[9] -= tmp[0]*src[12] + tmp[7]*src[14] + tmp[8]*src[15];
         out[10] = tmp[2]*src[12] + tmp[7]*src[13] + tmp[10]*src[15];
         out[10]-= tmp[3]*src[12] + tmp[6]*src[13] + tmp[11]*src[15];
         out[11] = tmp[5]*src[12] + tmp[8]*src[13] + tmp[11]*src[14];
         out[11]-= tmp[4]*src[12] + tmp[9]*src[13] + tmp[10]*src[14];
         out[12] = tmp[2]*src[10] + tmp[5]*src[11] + tmp[1]*src[9];
         out[12]-= tmp[4]*src[11] + tmp[0]*src[9] + tmp[3]*src[10];
         out[13] = tmp[8]*src[11] + tmp[0]*src[8] + tmp[7]*src[10];
         out[13]-= tmp[6]*src[10] + tmp[9]*src[11] + tmp[1]*src[8];
         out[14] = tmp[6]*src[9] + tmp[11]*src[11] + tmp[3]*src[8];
         out[14]-= tmp[10]*src[11] + tmp[2]*src[8] + tmp[7]*src[9];
         out[15] = tmp[10]*src[10] + tmp[4]*src[8] + tmp[9]*src[9];
         out[15]-= tmp[8]*src[9] + tmp[11]*src[10] + tmp[5]*src[8];
         /* calculate determinant */
         det=src[0]*out[0]+src[1]*out[1]+src[2]*out[2]+src[3]*out[3];
         /* calculate matrix inverse */
         det = 1/det;
         for (j = 0; j < 16; j++)
                 out[j] *= det;
 }
Referenced by VuxMakeViewMatrix().
VuxLightNormal()
int VuxLightNormal (VU_VECTOR * normal, VU_CVECTOR * col0, void * light, unsigned int light_type, VU_CVECTOR * out0)
Definition at line 920 of file vusw.c.
 {
         float                   dot;
         VU_FCVECTOR             final;
         VU_FCVECTOR             c0;
         VU_FLAT_LIGHT   *f_light;
         c0.r = col0->r * 0.0078125f;
         c0.g = col0->g * 0.0078125f;
         c0.b = col0->b * 0.0078125f;
         if(light_type == VU_LIGHT_TYPE_FLAT)
         {
                 f_light = (VU_FLAT_LIGHT *)light;
                 dot = -VuxDotProduct(normal, &f_light->direction);
                 if(dot <0.0f)dot = 0.0f;
                 final.r = vu_light_ambient.r + (c0.r * dot * f_light->color.r);
                 final.g = vu_light_ambient.g + (c0.g * dot * f_light->color.g);
                 final.b = vu_light_ambient.b + (c0.b * dot * f_light->color.b);
         }
         else
         {
                 final.r = vu_light_ambient.r + c0.r;
                 final.g = vu_light_ambient.g + c0.g;
                 final.b = vu_light_ambient.b + c0.b;
         }
         out0->r =final.r*128.0f;
         out0->g =final.g*128.0f;
         out0->b =final.b*128.0f;
         out0->a =0x80;
         out0->q =1.0f;
         return 0;
 }
References VU_CVECTOR::a, VU_CVECTOR::b, VU_FCVECTOR::b, VU_FLAT_LIGHT::color, VU_FLAT_LIGHT::direction, VU_CVECTOR::g, VU_FCVECTOR::g, light_type, VU_CVECTOR::q, VU_CVECTOR::r, VU_FCVECTOR::r, vu_light_ambient, VU_LIGHT_TYPE_FLAT, and VuxDotProduct().
VuxMakeLocalScreenMatrix()
void VuxMakeLocalScreenMatrix (VU_MATRIX * out, VU_MATRIX * world, VU_MATRIX * view)
Definition at line 511 of file vusw.c.
 {
         VuxMulMatrix(world, view,  out);                // then multiply it by world
 }
References VuxMulMatrix().
Referenced by VuxUpdateLocalScreenMatrix().
VuxMakeLocalScreenMatrix2()
void VuxMakeLocalScreenMatrix2 (VU_MATRIX * out, VU_MATRIX * world, VU_MATRIX * view, VU_MATRIX * projection)
Definition at line 524 of file vusw.c.
 {
         VU_MATRIX       work;
         VuxMulMatrix(world,     view,           &work);         // then multiply it by world
         VuxMulMatrix(&work,     projection,     out);           // mul projection
 }
References VuxMulMatrix().
Referenced by VuxUpdateLocalScreenMatrix().
VuxMakeLookAtViewMatrix()
void VuxMakeLookAtViewMatrix (VU_MATRIX * out, VU_VECTOR * eye, VU_VECTOR * target, VU_VECTOR * up)
Definition at line 563 of file vusw.c.
 {
         static VU_VECTOR        xaxis, yaxis, zaxis;
         zaxis.x = target->x - eye->x;
         zaxis.y = target->y - eye->y;
         zaxis.z = target->z - eye->z;
         VuxVectorNormal(&zaxis);
         xaxis = VuxCrossProduct(up, &zaxis);
         VuxVectorNormal(&xaxis);
         yaxis = VuxCrossProduct(&zaxis, &xaxis);
         out->m[0][0] = xaxis.x;
         out->m[0][1] = yaxis.x;
         out->m[0][2] = zaxis.x;
         out->m[0][3] = 0.0f;
         out->m[1][0] = xaxis.y;
         out->m[1][1] = yaxis.y;
         out->m[1][2] = zaxis.y;
         out->m[1][3] = 0.0f;
         out->m[2][0] = xaxis.z;
         out->m[2][1] = yaxis.z;
         out->m[2][2] = zaxis.z;
         out->m[2][3] = 0.0f;
         out->m[3][0] = -VuxDotProduct(&xaxis, eye);
         out->m[3][1] = -VuxDotProduct(&yaxis, eye);
         out->m[3][2] = -VuxDotProduct(&zaxis, eye);
         out->m[3][3] = 1.0f;
         /*******************************************
         ** the created matrix is already inverted **
         *******************************************/
 }
References VU_MATRIX::m, VuxCrossProduct(), VuxDotProduct(), VuxVectorNormal(), VU_VECTOR::x, VU_VECTOR::y, and VU_VECTOR::z.
VuxMakeProjectionMatrix()
void VuxMakeProjectionMatrix (VU_MATRIX * proj, float near_plane_w, float near_plane_h, float near_plane_z, float far_plane_z)
Definition at line 612 of file vusw.c.
 {
         VuxIdMatrix(proj);
         proj->m[0][0] = (1.0f*near_plane_z)/near_plane_w;
     proj->m[1][1] = (1.0f*near_plane_z)/near_plane_h;
         proj->m[2][2] = far_plane_z/(far_plane_z-near_plane_z);
         proj->m[2][3] = 1.0f;
         proj->m[3][2] = near_plane_z*far_plane_z/(near_plane_z-far_plane_z);
 }
References VU_MATRIX::m, and VuxIdMatrix().
VuxMakeViewMatrix()
void VuxMakeViewMatrix (VU_MATRIX * out, VU_VECTOR * rot, VU_VECTOR * pos, VU_VECTOR * scale)
Definition at line 544 of file vusw.c.
 {
         VU_MATRIX       work;
         VuxResetMatrix(&work);
         VuxRotMatrix(&work, rot);
         VuxTransMatrix(&work, pos);
         VuxScaleMatrix(&work, scale);
         VuxInverseMatrix(&work, out);
 }
References pos, VuxInverseMatrix(), VuxResetMatrix(), VuxRotMatrix(), VuxScaleMatrix(), and VuxTransMatrix().
VuxMulMatrix()
void VuxMulMatrix (VU_MATRIX * m0, VU_MATRIX * m1, VU_MATRIX * out)
Definition at line 251 of file vusw.c.
 {
         int i,j,k;
     float* pA = (float*)m1;
     float* pB = (float*)m0;
         float* pQ = (float*)out;
     float  pM[16];
     for(i=0;i<16;i++)pM[i]=0;
     for(  i=0; i<4; i++ )
         for(  j=0; j<4; j++ )
             for(  k=0; k<4; k++ )
                 pM[4*i+j] += pA[4*k+j] * pB[4*i+k];
     for(i=0;i<16;i++)pQ[i] = pM[i];
 }
Referenced by VuxMakeLocalScreenMatrix(), VuxMakeLocalScreenMatrix2(), VuxRotMatrix(), VuxRotMatrixXYZ(), VuxScaleMatrix(), and VuxScaleMatrixXYZ().
VuxPers()
void VuxPers (VU_VECTOR * v0, VU_SXYZ * sxyz0)
Definition at line 698 of file vusw.c.
 {
         if(vu_projection_type==0)
         {
                 sxyz0->x = ftoi4( (vu_projection * v0->x / (v0->z))             +vu_offset_x);
                 sxyz0->y = ftoi4(-(vu_projection * v0->y / (v0->z))             +vu_offset_y);
                 sxyz0->z = 0xffffff-(short)(float)v0->z;
         }
         else    // use projection matrix
         {
                 sxyz0->x = ftoi4( (((v0->x)/(v0->w))*vu_near_plane_w)   +vu_offset_x);
                 sxyz0->y = ftoi4(-(((v0->y)/(v0->w))*vu_near_plane_h)   +vu_offset_y);
                 sxyz0->z =  (int)(-(v0->z/v0->w) * 0xffff);
         }
 }
References ftoi4, v0, vu_near_plane_h, vu_near_plane_w, vu_offset_x, vu_offset_y, vu_projection, vu_projection_type, VU_SXYZ::x, VU_SXYZ::y, and VU_SXYZ::z.
Referenced by VuxPersN(), and VuxRotTransPers().
VuxPers3()
void VuxPers3 (VU_VECTOR * v0, VU_VECTOR * v1, VU_VECTOR * v2, VU_SXYZ * sxyz0, VU_SXYZ * sxyz1, VU_SXYZ * sxyz2)
Definition at line 724 of file vusw.c.
 {
         if(vu_projection_type==0)
         {
                 //v0
                 sxyz0->x = ftoi4( (vu_projection * v0->x / (v0->z))             +vu_offset_x);
                 sxyz0->y = ftoi4(-(vu_projection * v0->y / (v0->z))             +vu_offset_y);
                 sxyz0->z = 0xffffff      - (short)(float)v0->z;
                 //v1
                 sxyz1->x = ftoi4( (vu_projection * v1->x / (v1->z))             +vu_offset_x);
                 sxyz1->y = ftoi4(-(vu_projection * v1->y / (v1->z))             +vu_offset_y);
                 sxyz1->z = 0xffffff - (short)(float)v1->z;
                 //v2
                 sxyz2->x = ftoi4( (vu_projection * v2->x / (v2->z))             +vu_offset_x);
                 sxyz2->y = ftoi4(-(vu_projection * v2->y / (v2->z))             +vu_offset_y);
                 sxyz2->z = 0xffffff - (short)(float)v2->z;
         }
         else    // use projection matrix
         {
                 sxyz0->x = ftoi4( (((v0->x)/(v0->w))*vu_near_plane_w)   +vu_offset_x);
                 sxyz0->y = ftoi4(-(((v0->y)/(v0->w))*vu_near_plane_h)   +vu_offset_y);
                 sxyz0->z =  (int)(-(v0->z/v0->w) * 0xffff);
                 sxyz1->x = ftoi4( (((v1->x)/(v1->w))*vu_near_plane_w)   +vu_offset_x);
                 sxyz1->y = ftoi4(-(((v1->y)/(v1->w))*vu_near_plane_h)   +vu_offset_y);
                 sxyz1->z =  (int)(-(v1->z/v1->w) * 0xffff);
                 sxyz2->x = ftoi4( (((v2->x)/(v2->w))*vu_near_plane_w)   +vu_offset_x);
                 sxyz2->y = ftoi4(-(((v2->y)/(v2->w))*vu_near_plane_h)   +vu_offset_y);
                 sxyz2->z =  (int)(-(v2->z/v2->w) * 0xffff);
         }
 }
References ftoi4, v0, v1, vu_near_plane_h, vu_near_plane_w, vu_offset_x, vu_offset_y, vu_projection, vu_projection_type, VU_VECTOR::w, VU_VECTOR::x, VU_SXYZ::x, VU_VECTOR::y, VU_SXYZ::y, VU_VECTOR::z, and VU_SXYZ::z.
Referenced by VuxRotTransPers3(), and VuxRotTransPersClip3().
VuxPersClip3()
int VuxPersClip3 (VU_VECTOR * v0, VU_VECTOR * v1, VU_VECTOR * v2, VU_SXYZ * sxyz0, VU_SXYZ * sxyz1, VU_SXYZ * sxyz2)
Definition at line 783 of file vusw.c.
 {
         if(vu_projection_type==0)
         {
                 //v0
                 sxyz0->x = ftoi4( (vu_projection * v0->x / (v0->z))             +vu_offset_x);
                 sxyz0->y = ftoi4(-(vu_projection * v0->y / (v0->z))             +vu_offset_y);
                 sxyz0->z = 0xffffff - (short)(float)v0->z;
                 //v1
                 sxyz1->x = ftoi4( (vu_projection * v1->x / (v1->z))             +vu_offset_x);
                 sxyz1->y = ftoi4(-(vu_projection * v1->y / (v1->z))             +vu_offset_y);
                 sxyz1->z = 0xffffff - (short)(float)v1->z;
                 //v2
                 sxyz2->x = ftoi4( (vu_projection * v2->x / (v2->z))             +vu_offset_x);
                 sxyz2->y = ftoi4(-(vu_projection * v2->y / (v2->z))             +vu_offset_y);
                 sxyz2->z = 0xffffff - (short)(float)v2->z;
         }
         else    // use projection matrix
         {
                 sxyz0->x = ftoi4( (((v0->x)/(v0->w))*vu_near_plane_w)   +vu_offset_x);
                 sxyz0->y = ftoi4(-(((v0->y)/(v0->w))*vu_near_plane_h)   +vu_offset_y);
                 sxyz0->z =  (int)(-(v0->z/v0->w) * 0xffff);
                 sxyz1->x = ftoi4( (((v1->x)/(v1->w))*vu_near_plane_w)   +vu_offset_x);
                 sxyz1->y = ftoi4(-(((v1->y)/(v1->w))*vu_near_plane_h)   +vu_offset_y);
                 sxyz1->z =  (int)(-(v1->z/v1->w) * 0xffff);
                 sxyz2->x = ftoi4( (((v2->x)/(v2->w))*vu_near_plane_w)   +vu_offset_x);
                 sxyz2->y = ftoi4(-(((v2->y)/(v2->w))*vu_near_plane_h)   +vu_offset_y);
                 sxyz2->z =  (int)(-(v2->z/v2->w) * 0xffff);
         }
         return VuxClipSxyz(sxyz0, sxyz1, sxyz2);
 }
References ftoi4, v0, v1, vu_near_plane_h, vu_near_plane_w, vu_offset_x, vu_offset_y, vu_projection, vu_projection_type, VuxClipSxyz(), VU_VECTOR::w, VU_VECTOR::x, VU_SXYZ::x, VU_VECTOR::y, VU_SXYZ::y, VU_VECTOR::z, and VU_SXYZ::z.
VuxPersN()
void VuxPersN (VU_VECTOR * verts, VU_SXYZ * sxyz, unsigned int num_verts)
Definition at line 767 of file vusw.c.
 {
         unsigned int    i;
         for(i=0;i<num_verts;i++)
         {
                 VuxPers(&verts[i], &sxyz[i]);
         }
 }
References VuxPers().
VuxResetMatrix()
void VuxResetMatrix (VU_MATRIX * m)
Definition at line 39 of file vusw.c.
 {
         m->m[0][0]=1.0f; m->m[0][1]=0.0f; m->m[0][2]=0.0f; m->m[0][3]=0.0f;
         m->m[1][0]=0.0f; m->m[1][1]=1.0f; m->m[1][2]=0.0f; m->m[1][3]=0.0f;
         m->m[2][0]=0.0f; m->m[2][1]=0.0f; m->m[2][2]=1.0f; m->m[2][3]=0.0f;
         m->m[3][0]=0.0f; m->m[3][1]=0.0f; m->m[3][2]=0.0f; m->m[3][3]=1.0f;
 }
References VU_MATRIX::m.
Referenced by VuxIdMatrix(), VuxMakeViewMatrix(), VuxRotMatrix(), VuxRotMatrixXYZ(), VuxScaleMatrix(), and VuxScaleMatrixXYZ().
VuxRotMatrix()
void VuxRotMatrix (VU_MATRIX * m, VU_VECTOR * v)
Definition at line 51 of file vusw.c.
 {
         VU_MATRIX       mx,my,mz, m0;
         VuxResetMatrix(m);
         mx = my = mz = m0 = *m;
         VuxRotMatrixX(&mx, r->x);
         VuxRotMatrixY(&my, r->y);
         VuxRotMatrixZ(&mz, r->z);
 //      VuxMulMatrix(&my, &mx, &m0);
 //      VuxMulMatrix(&mz, &m0, m);
         VuxMulMatrix(&mz, &mx, &m0);
         VuxMulMatrix(&my, &m0, m);
 }
References VuxMulMatrix(), VuxResetMatrix(), VuxRotMatrixX(), VuxRotMatrixY(), VuxRotMatrixZ(), VU_VECTOR::x, VU_VECTOR::y, and VU_VECTOR::z.
Referenced by VuxMakeViewMatrix().
VuxRotMatrixX()
void VuxRotMatrixX (VU_MATRIX * m, float x)
Definition at line 74 of file vusw.c.
 {
         float cs,sn;
         cs = cosf(x);
         sn = sinf(x);
         m->m[1][1] = cs;
         m->m[1][2] = sn;
         m->m[2][1] = -sn;
         m->m[2][2] = cs;
 /*  colum major(left hand)
         m->m[1][1] = cs;
         m->m[1][2] = -sn;
         m->m[2][1] = sn;
         m->m[2][2] = cs;
 */
 }
References VU_MATRIX::m, and x.
Referenced by VuxRotMatrix(), and VuxRotMatrixXYZ().
VuxRotMatrixXYZ()
void VuxRotMatrixXYZ (VU_MATRIX * m, float x, float y, float z)
Definition at line 157 of file vusw.c.
 {
         VU_MATRIX       mx,my,mz, m0;
         VuxResetMatrix(m);
         mx = my = mz = m0 = *m;
         VuxRotMatrixX(&mx, x);
         VuxRotMatrixY(&my, y);
         VuxRotMatrixZ(&mz, z);
 //      VuxMulMatrix(&mx, &my, &m0);
 //      VuxMulMatrix(&m0, &mz, m);
 //      VuxMulMatrix(&mz, &my, &m0);
 //      VuxMulMatrix(&mx, &m0, m);
         VuxMulMatrix(&mz, &mx, &m0);
         VuxMulMatrix(&my, &m0, m);
 }
References VuxMulMatrix(), VuxResetMatrix(), VuxRotMatrixX(), VuxRotMatrixY(), VuxRotMatrixZ(), x, and y.
VuxRotMatrixY()
void VuxRotMatrixY (VU_MATRIX * m, float y)
Definition at line 101 of file vusw.c.
 {
         float cs,sn;
         cs = cosf(y);
         sn = sinf(y);
         m->m[0][0] = cs;
         m->m[0][2] = -sn;
         m->m[2][0] = sn;
         m->m[2][2] = cs;
 /*      colum major(left hand)
         m->m[0][0] = cs;
         m->m[0][2] = sn;
         m->m[2][0] = -sn;
         m->m[2][2] = cs;
         */
 }
References VU_MATRIX::m, and y.
Referenced by VuxRotMatrix(), and VuxRotMatrixXYZ().
VuxRotMatrixZ()
void VuxRotMatrixZ (VU_MATRIX * m, float z)
Definition at line 129 of file vusw.c.
 {
         float cs,sn;
         cs = cosf(z);
         sn = sinf(z);
         m->m[0][0] = cs;
         m->m[0][1] = sn;
         m->m[1][0] = -sn;
         m->m[1][1] = cs;
         /* colum major(left hand)
         m->m[0][0] = cs;
         m->m[0][1] = -sn;
         m->m[1][0] = sn;
         m->m[1][1] = cs;
 */
 }
References VU_MATRIX::m.
Referenced by VuxRotMatrix(), and VuxRotMatrixXYZ().
VuxRotTrans()
void VuxRotTrans (VU_VECTOR * v0, VU_VECTOR * out)
Definition at line 662 of file vusw.c.
 {
         VuxApplyMatrixLS(v0, out);
 }
References v0, and VuxApplyMatrixLS().
Referenced by VuxRotTransPers().
VuxRotTrans3()
void VuxRotTrans3 (VU_VECTOR * v0, VU_VECTOR * v1, VU_VECTOR * v2, VU_VECTOR * tv0, VU_VECTOR * tv1, VU_VECTOR * tv2)
Definition at line 671 of file vusw.c.
 {
         // v0
         VuxApplyMatrixLS(v0, tv0);
         // v1
         VuxApplyMatrixLS(v1, tv1);
         // v2
         VuxApplyMatrixLS(v2, tv2);
 }
References v0, v1, and VuxApplyMatrixLS().
Referenced by VuxRotTransPers3(), and VuxRotTransPersClip3().
VuxRotTransN()
void VuxRotTransN (VU_VECTOR * verts, VU_VECTOR * tverts, unsigned int num_verts)
Definition at line 684 of file vusw.c.
 {
         unsigned int i;
         for(i=0;i<num_verts;i++)
         {
                 VuxApplyMatrixLS(&verts[i], &tverts[i]);
         }
 }
References VuxApplyMatrixLS().
VuxRotTransPers()
float VuxRotTransPers (VU_VECTOR * v0, VU_SXYZ * sxyz0)
Definition at line 829 of file vusw.c.
 {
         VU_VECTOR       tv0;
         VuxRotTrans(v0, &tv0);
         VuxPers(&tv0    , sxyz0);
         return tv0.z;
 }
References v0, VuxPers(), VuxRotTrans(), and VU_VECTOR::z.
Referenced by VuxRotTransPersN().
VuxRotTransPers3()
float VuxRotTransPers3 (VU_VECTOR * v0, VU_VECTOR * v1, VU_VECTOR * v2, VU_SXYZ * sxyz0, VU_SXYZ * sxyz1, VU_SXYZ * sxyz2)
Definition at line 843 of file vusw.c.
 {
         VU_VECTOR       tv0,tv1,tv2;
         VuxRotTrans3(v0, v1, v2,  &tv0, &tv1, &tv2);
         VuxPers3(&tv0, &tv1, &tv2, sxyz0, sxyz1, sxyz2);
         return tv0.z;
 }
References v0, v1, VuxPers3(), VuxRotTrans3(), and VU_VECTOR::z.
VuxRotTransPersClip3()
int VuxRotTransPersClip3 (VU_VECTOR * v0, VU_VECTOR * v1, VU_VECTOR * v2, VU_SXYZ * sxyz0, VU_SXYZ * sxyz1, VU_SXYZ * sxyz2)
Definition at line 875 of file vusw.c.
 {
         VU_VECTOR       tv0,tv1,tv2;
         VuxRotTrans3(v0, v1, v2,  &tv0, &tv1, &tv2);
         VuxPers3(&tv0, &tv1, &tv2, sxyz0, sxyz1, sxyz2);
         return VuxClipSxyz(sxyz0, sxyz1, sxyz2);
 }
References v0, v1, VuxClipSxyz(), VuxPers3(), and VuxRotTrans3().
VuxRotTransPersN()
void VuxRotTransPersN (VU_VECTOR * verts, VU_SXYZ * sxyz, unsigned int num_verts)
Definition at line 858 of file vusw.c.
 {
         unsigned int i;
         for(i=0;i<num_verts;i++)
         {
                 VuxRotTransPers(&verts[i], &sxyz[i]);
         }
 }
References VuxRotTransPers().
VuxScaleMatrix()
void VuxScaleMatrix (VU_MATRIX * m, VU_VECTOR * s)
Definition at line 216 of file vusw.c.
 {
         VU_MATRIX       w;
         VuxResetMatrix(&w);
         w.m[0][0] = s->x;
         w.m[1][1] = s->y;
         w.m[2][2] = s->z;
         VuxMulMatrix(m, &w, m);
 }
References VU_MATRIX::m, s, VuxMulMatrix(), and VuxResetMatrix().
Referenced by VuxMakeViewMatrix().
VuxScaleMatrixXYZ()
void VuxScaleMatrixXYZ (VU_MATRIX * m, float x, float y, float z)
Definition at line 232 of file vusw.c.
 {
         VU_MATRIX       w;
         VuxResetMatrix(&w);
         w.m[0][0] = x;
         w.m[1][1] = y;
         w.m[2][2] = z;
         VuxMulMatrix(m, &w, m);
 }
References VU_MATRIX::m, VuxMulMatrix(), VuxResetMatrix(), x, and y.
VuxTransMatrix()
void VuxTransMatrix (VU_MATRIX * m, VU_VECTOR * v0)
Definition at line 188 of file vusw.c.
 {
         m->m[3][0] =  t->x;
         m->m[3][1] =  t->y;
         m->m[3][2] =  t->z;
         m->m[3][3] =  1.0f;
 }
References VU_MATRIX::m, VU_VECTOR::x, VU_VECTOR::y, and VU_VECTOR::z.
Referenced by VuxMakeViewMatrix().
VuxTransMatrixXYZ()
void VuxTransMatrixXYZ (VU_MATRIX * m, float x, float y, float z)
Definition at line 202 of file vusw.c.
 {
         m->m[3][0] =  x;
         m->m[3][1] =  y;
         m->m[3][2] =  z;
         m->m[3][3] =  1.0f;
 }
References VU_MATRIX::m, x, and y.
VuxUpdateLocalScreenMatrix()
void VuxUpdateLocalScreenMatrix (void)
update lsm using view, world, proj
Definition at line 634 of file vusw.c.
 {
         VU_MATRIX lsm;
         if(vu_projection_type==0)               // use vu_projection
         {
                 VuxMakeLocalScreenMatrix(&lsm, &VuWorldMatrix, &VuViewMatrix);
         }
         else /*if(vu_projection_type==1)*/      // use projection matrix
         {
                 VuxMakeLocalScreenMatrix2(&lsm, &VuWorldMatrix, &VuViewMatrix, &VuPrjectionMatrix);
         }
         VuSetLocalScreenMatrix(&lsm);
 }
References vu_projection_type, VuPrjectionMatrix, VuSetLocalScreenMatrix(), VuViewMatrix, VuWorldMatrix, VuxMakeLocalScreenMatrix(), and VuxMakeLocalScreenMatrix2().
VuxVectorNormal()
void VuxVectorNormal (VU_VECTOR * v)
Definition at line 447 of file vusw.c.
 {
    float m = sqrtf(v->x*v->x + v->y*v->y + v->z*v->z + v->w*v->w);
    v->x /= m;
    v->y /= m;
    v->z /= m;
    v->w /= m;
 }
References VU_VECTOR::w, VU_VECTOR::x, VU_VECTOR::y, and VU_VECTOR::z.
Referenced by VuxMakeLookAtViewMatrix().
VuxVectorNormal0()
void VuxVectorNormal0 (VU_VECTOR * in, VU_VECTOR * out)
Definition at line 460 of file vusw.c.
 {
    float m = sqrtf(in->x*in->x + in->y*in->y + in->z*in->z + in->w*in->w);
    out->x /= m;
    out->y /= m;
    out->z /= m;
    out->w /= m;
 }
References VU_VECTOR::w, VU_VECTOR::x, VU_VECTOR::y, and VU_VECTOR::z.
Variable Documentation
VuLocalScreenMatrix
VU_MATRIX VuLocalScreenMatrix extern
Definition at line 42 of file vux.c.
Referenced by VuSetLocalScreenMatrix(), VuxApplyMatrixLS(), and VuxApplyRotMatrixLS().
VuPrjectionMatrix
VU_MATRIX VuPrjectionMatrix extern
Definition at line 35 of file vux.c.
Referenced by VuSetProjectionMatrix(), and VuxUpdateLocalScreenMatrix().
VuViewMatrix
VU_MATRIX VuViewMatrix extern
Definition at line 28 of file vux.c.
Referenced by VuSetViewMatrix(), and VuxUpdateLocalScreenMatrix().
VuWorldMatrix
VU_MATRIX VuWorldMatrix extern
Definition at line 21 of file vux.c.
Referenced by VuSetWorldMatrix(), and VuxUpdateLocalScreenMatrix().