ps2sdk: ee/elf-loader/src/loader/loader.c File Reference
loader.c File Reference
#include <kernel.h>
#include <loadfile.h>
#include <sifrpc.h>
#include <errno.h>
Functions
static void wipeUserMem (void)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 40 of file loader.c.
 {
         static t_ExecData elfdata;
         int ret;
         if (argc < 1) {  // arg1=path to ELF
                 return -EINVAL;
         }
         // Initialize
         SifInitRpc(0);
         wipeUserMem();
         //Writeback data cache before loading ELF.
         FlushCache(0);
         ret = SifLoadElf(argv[0], &elfdata);
         if (ret == 0) {
                 SifExitRpc();
                 FlushCache(0);
                 FlushCache(2);
                 // Following the standard the first parameter of a argv is the executable itself
                 return ExecPS2((void *)elfdata.epc, (void *)elfdata.gp, argc, argv);
         } else {
                 SifExitRpc();
                 return -ENOENT;
         }
 }
References EINVAL, ENOENT, t_ExecData::epc, ExecPS2(), FlushCache(), t_ExecData::gp, SifExitRpc(), SifInitRpc(), SifLoadElf(), and wipeUserMem().
wipeUserMem()
static void wipeUserMem (void) static
Definition at line 23 of file loader.c.
 {
         int i;
         for (i = 0x100000; i < GetMemorySize(); i += 64) {
                 asm volatile(
                         "\tsq $0, 0(%0) \n"
                         "\tsq $0, 16(%0) \n"
                         "\tsq $0, 32(%0) \n"
                         "\tsq $0, 48(%0) \n" ::"r"(i));
         }
 }
References GetMemorySize().
Referenced by main().