ps2sdk: ee/libgs/src/lowlevel.c File Reference
lowlevel.c File Reference
#include <errno.h>
#include <stdio.h>
#include <kernel.h>
#include <libgs.h>
#include "internal.h"
Functions
static s8 twh (s16 val)
int GsSetXYOffset1 (u16 x, u16 y)
int GsSetXYOffset2 (u16 x, u16 y)
int GsSetScissor1 (u16 upper_x, u16 upper_y, u16 lower_x, u16 lower_y)
int GsSetScissor2 (u16 upper_x, u16 upper_y, u16 lower_x, u16 lower_y)
int GsSetFrame1 (u16 framebuffer_addr, u8 framebuffer_width, u8 psm, u32 draw_mask)
int GsSetFrame2 (u16 framebuffer_addr, u8 framebuffer_width, u8 psm, u32 draw_mask)
int GsTextureFlush (void)
int GsSetPixelTest1 (u8 enable_alpha_test, u8 alpha_test_method, u8 alpha_reference, u8 alpha_fail_method, u8 enable_dest_alpha_test, u8 dest_alpha_test_mode, u8 enable_zbuff_test, u8 alpha_zbuff_method)
int GsSetPixelTest2 (u8 enable_alpha_test, u8 alpha_test_method, u8 alpha_reference, u8 alpha_fail_method, u8 enable_dest_alpha_test, u8 dest_alpha_test_mode, u8 enable_zbuff_test, u8 alpha_zbuff_method)
int GsSelectTexure1 (u16 tex_addr, u8 addr_width, u8 tex_pixmode, u16 tex_width, u16 tex_height, u16 clut_addr, u8 clut_pixmode, u8 clut_storagemode, u8 clut_offset)
int GsSelectTexure2 (u16 tex_addr, u8 addr_width, u8 tex_pixmode, u16 tex_width, u16 tex_height, u16 clut_addr, u8 clut_pixmode, u8 clut_storagemode, u8 clut_offset)
void GsSetFogColor (u8 r, u8 g, u8 b)
void GsEnableColorClamp (u16 enable)
Variables
QWORD GsPrimWorkArea []
Function Documentation
GsEnableColorClamp()
void GsEnableColorClamp (u16 enable)
Definition at line 190 of file lowlevel.c.
 {
         QWORD *p;
         p=UNCACHED_SEG(GsPrimWorkArea);
         gs_setGIF_TAG(((GS_GIF_TAG *)&p[0]), 1,1,0,0,GS_GIF_PACKED,1,gif_rd_ad);
         gs_setR_COLCLAMP(((GS_R_COLCLAMP *)&p[1]), enable);
         GsDmaSend(GsPrimWorkArea, 2);
         GsDmaWait();
 }
References gif_rd_ad, GS_GIF_PACKED, gs_setGIF_TAG, gs_setR_COLCLAMP, GsDmaSend(), GsDmaWait(), GsPrimWorkArea, and UNCACHED_SEG.
GsSelectTexure1()
int GsSelectTexure1 (u16 tex_addr, u8 addr_width, u8 tex_pixmode, u16 tex_width, u16 tex_height, u16 clut_addr, u8 clut_pixmode, u8 clut_storagemode, u8 clut_offset)
Definition at line 153 of file lowlevel.c.
 {
         QWORD *p;
         p=UNCACHED_SEG(GsPrimWorkArea);
         gs_setGIF_TAG(((GS_GIF_TAG *)&p[0]), 1,1,0,0,GS_GIF_PACKED,1,gif_rd_ad);
         gs_setR_TEX0_1(((GS_R_TEX0 *)&p[1]), tex_addr,addr_width,tex_pixmode, twh(tex_width), twh(tex_height),1,0,clut_addr,clut_pixmode,clut_storagemode,clut_offset,4); /*4 load contex 0*/
         GsDmaSend(GsPrimWorkArea, 2);
         GsDmaWait();
         return 0;
 }
References gif_rd_ad, GS_GIF_PACKED, gs_setGIF_TAG, gs_setR_TEX0_1, GsDmaSend(), GsDmaWait(), GsPrimWorkArea, twh(), and UNCACHED_SEG.
GsSelectTexure2()
int GsSelectTexure2 (u16 tex_addr, u8 addr_width, u8 tex_pixmode, u16 tex_width, u16 tex_height, u16 clut_addr, u8 clut_pixmode, u8 clut_storagemode, u8 clut_offset)
Definition at line 166 of file lowlevel.c.
 {
         QWORD *p;
         p=UNCACHED_SEG(GsPrimWorkArea);
         gs_setGIF_TAG(((GS_GIF_TAG *)&p[0]), 1,1,0,0,GS_GIF_PACKED,1,gif_rd_ad);
         gs_setR_TEX0_2(((GS_R_TEX0 *)&p[1]), tex_addr, addr_width, tex_pixmode, twh(tex_width), twh(tex_height), 1, 0, clut_addr, clut_pixmode, clut_storagemode,clut_offset,5);/*5 load contex 2*/
         GsDmaSend(GsPrimWorkArea, 2);
         GsDmaWait();
         return 0;
 }
References gif_rd_ad, GS_GIF_PACKED, gs_setGIF_TAG, gs_setR_TEX0_2, GsDmaSend(), GsDmaWait(), GsPrimWorkArea, twh(), and UNCACHED_SEG.
GsSetFogColor()
void GsSetFogColor (u8 r, u8 g, u8 b)
Definition at line 179 of file lowlevel.c.
 {
         QWORD *p;
         p=UNCACHED_SEG(GsPrimWorkArea);
         gs_setGIF_TAG(((GS_GIF_TAG*)&p[0]), 1,1,0,0,GS_GIF_PACKED,1,gif_rd_ad);
         gs_setR_FOGCOLOR(((GS_R_FOGCOLOR*)&p[1]), r,g,b);
         GsDmaSend(GsPrimWorkArea, 2);
         GsDmaWait();
 }
References gif_rd_ad, GS_GIF_PACKED, gs_setGIF_TAG, gs_setR_FOGCOLOR, GsDmaSend(), GsDmaWait(), GsPrimWorkArea, and UNCACHED_SEG.
GsSetFrame1()
int GsSetFrame1 (u16 framebuffer_addr, u8 framebuffer_width, u8 psm, u32 draw_mask)
Definition at line 88 of file lowlevel.c.
 {
         QWORD *p;
         p=UNCACHED_SEG(GsPrimWorkArea);
         gs_setGIF_TAG(((GS_GIF_TAG *)&p[0]), 1,1,0,0,GS_GIF_PACKED,1,gif_rd_ad);
         gs_setR_FRAME_1(((GS_R_FRAME *)&p[1]), framebuffer_addr,framebuffer_width,psm,draw_mask);
         GsDmaSend(GsPrimWorkArea, 2);
         GsDmaWait();
         return 0;
 }
References gif_rd_ad, GS_GIF_PACKED, gs_setGIF_TAG, gs_setR_FRAME_1, GsDmaSend(), GsDmaWait(), GsPrimWorkArea, and UNCACHED_SEG.
Referenced by GsPutDrawEnv1().
GsSetFrame2()
int GsSetFrame2 (u16 framebuffer_addr, u8 framebuffer_width, u8 psm, u32 draw_mask)
Definition at line 101 of file lowlevel.c.
 {
         QWORD *p;
         p=UNCACHED_SEG(GsPrimWorkArea);
         gs_setGIF_TAG(((GS_GIF_TAG *)&p[0]), 1,1,0,0,GS_GIF_PACKED,1,gif_rd_ad);
         gs_setR_FRAME_2(((GS_R_FRAME *)&p[1]), framebuffer_addr,framebuffer_width,psm,draw_mask);
         GsDmaSend(GsPrimWorkArea, 2);
         GsDmaWait();
         return 0;
 }
References gif_rd_ad, GS_GIF_PACKED, gs_setGIF_TAG, gs_setR_FRAME_2, GsDmaSend(), GsDmaWait(), GsPrimWorkArea, and UNCACHED_SEG.
Referenced by GsPutDrawEnv2().
GsSetPixelTest1()
int GsSetPixelTest1 (u8 enable_alpha_test, u8 alpha_test_method, u8 alpha_reference, u8 alpha_fail_method, u8 enable_dest_alpha_test, u8 dest_alpha_test_mode, u8 enable_zbuff_test, u8 alpha_zbuff_method)
Definition at line 127 of file lowlevel.c.
 {
         QWORD *p;
         p=UNCACHED_SEG(GsPrimWorkArea);
         gs_setGIF_TAG(((GS_GIF_TAG *)&p[0]), 1,1,0,0,GS_GIF_PACKED,1,gif_rd_ad);
         gs_setR_TEST_1(((GS_R_TEST *)&p[1]), enable_alpha_test, alpha_test_method, alpha_reference, alpha_fail_method, enable_dest_alpha_test, dest_alpha_test_mode, enable_zbuff_test, alpha_zbuff_method);
         GsDmaSend(GsPrimWorkArea, 2);
         GsDmaWait();
         return 0;
 }
References gif_rd_ad, GS_GIF_PACKED, gs_setGIF_TAG, gs_setR_TEST_1, GsDmaSend(), GsDmaWait(), GsPrimWorkArea, and UNCACHED_SEG.
Referenced by GsEnableAlphaTransparency1(), and GsEnableZbuffer1().
GsSetPixelTest2()
int GsSetPixelTest2 (u8 enable_alpha_test, u8 alpha_test_method, u8 alpha_reference, u8 alpha_fail_method, u8 enable_dest_alpha_test, u8 dest_alpha_test_mode, u8 enable_zbuff_test, u8 alpha_zbuff_method)
Definition at line 140 of file lowlevel.c.
 {
         QWORD *p;
         p=UNCACHED_SEG(GsPrimWorkArea);
         gs_setGIF_TAG(((GS_GIF_TAG *)&p[0]), 1,1,0,0,GS_GIF_PACKED,1,gif_rd_ad);
         gs_setR_TEST_2(((GS_R_TEST *)&p[1]), enable_alpha_test, alpha_test_method, alpha_reference, alpha_fail_method, enable_dest_alpha_test, dest_alpha_test_mode, enable_zbuff_test, alpha_zbuff_method);
         GsDmaSend(GsPrimWorkArea, 2);
         GsDmaWait();
         return 0;
 }
References gif_rd_ad, GS_GIF_PACKED, gs_setGIF_TAG, gs_setR_TEST_2, GsDmaSend(), GsDmaWait(), GsPrimWorkArea, and UNCACHED_SEG.
Referenced by GsEnableAlphaTransparency2(), and GsEnableZbuffer2().
GsSetScissor1()
int GsSetScissor1 (u16 upper_x, u16 upper_y, u16 lower_x, u16 lower_y)
Definition at line 62 of file lowlevel.c.
 {
         QWORD *p;
         p=UNCACHED_SEG(GsPrimWorkArea);
         gs_setGIF_TAG(((GS_GIF_TAG *)&p[0]), 1,1,0,0,GS_GIF_PACKED,1,gif_rd_ad);
         gs_setR_SCISSOR_1(((GS_R_SCISSOR *)&p[1]), upper_x,lower_x,upper_y,lower_y);
         GsDmaSend(GsPrimWorkArea, 2);
         GsDmaWait();
         return 0;
 }
References gif_rd_ad, GS_GIF_PACKED, gs_setGIF_TAG, gs_setR_SCISSOR_1, GsDmaSend(), GsDmaWait(), GsPrimWorkArea, and UNCACHED_SEG.
Referenced by GsPutDrawEnv1().
GsSetScissor2()
int GsSetScissor2 (u16 upper_x, u16 upper_y, u16 lower_x, u16 lower_y)
Definition at line 75 of file lowlevel.c.
 {
         QWORD *p;
         p=UNCACHED_SEG(GsPrimWorkArea);
         gs_setGIF_TAG(((GS_GIF_TAG *)&p[0]), 1,1,0,0,GS_GIF_PACKED,1,gif_rd_ad);
         gs_setR_SCISSOR_2(((GS_R_SCISSOR *)&p[1]), upper_x,lower_x,upper_y,lower_y);
         GsDmaSend(GsPrimWorkArea, 2);
         GsDmaWait();
         return 0;
 }
References gif_rd_ad, GS_GIF_PACKED, gs_setGIF_TAG, gs_setR_SCISSOR_2, GsDmaSend(), GsDmaWait(), GsPrimWorkArea, and UNCACHED_SEG.
Referenced by GsPutDrawEnv2().
GsSetXYOffset1()
int GsSetXYOffset1 (u16 x, u16 y)
Definition at line 36 of file lowlevel.c.
 {
         QWORD *p;
         p=UNCACHED_SEG(GsPrimWorkArea);
         gs_setGIF_TAG(((GS_GIF_TAG *)&p[0]), 1,1,0,0,GS_GIF_PACKED,1,gif_rd_ad);
         gs_setR_XYOFFSET_1(((GS_R_XYOFFSET *)&p[1]), x,y);
         GsDmaSend(GsPrimWorkArea, 2);
         GsDmaWait();
         return 0;
 }
References gif_rd_ad, GS_GIF_PACKED, gs_setGIF_TAG, gs_setR_XYOFFSET_1, GsDmaSend(), GsDmaWait(), GsPrimWorkArea, UNCACHED_SEG, x, and y.
Referenced by GsPutDrawEnv1().
GsSetXYOffset2()
int GsSetXYOffset2 (u16 x, u16 y)
Definition at line 49 of file lowlevel.c.
 {
         QWORD *p;
         p=UNCACHED_SEG(GsPrimWorkArea);
         gs_setGIF_TAG(((GS_GIF_TAG *)&p[0]), 1,1,0,0,GS_GIF_PACKED,1,gif_rd_ad);
         gs_setR_XYOFFSET_2(((GS_R_XYOFFSET *)&p[1]), x,y);
         GsDmaSend(GsPrimWorkArea, 2);
         GsDmaWait();
         return 0;
 }
References gif_rd_ad, GS_GIF_PACKED, gs_setGIF_TAG, gs_setR_XYOFFSET_2, GsDmaSend(), GsDmaWait(), GsPrimWorkArea, UNCACHED_SEG, x, and y.
Referenced by GsPutDrawEnv2().
GsTextureFlush()
int GsTextureFlush (void)
Definition at line 114 of file lowlevel.c.
 {
         QWORD *p;
         p=UNCACHED_SEG(GsPrimWorkArea);
         gs_setGIF_TAG(((GS_GIF_TAG *)&p[0]), 1,1,0,0,GS_GIF_PACKED,1,gif_rd_ad);
         gs_setR_TEXFLUSH(((GS_R_TEXFLUSH *)&p[1]));
         GsDmaSend(GsPrimWorkArea,2);
         GsDmaWait();
         return 0;
 }
References gif_rd_ad, GS_GIF_PACKED, gs_setGIF_TAG, gs_setR_TEXFLUSH, GsDmaSend(), GsDmaWait(), GsPrimWorkArea, and UNCACHED_SEG.
twh()
static s8 twh (s16 val) static
Definition at line 22 of file lowlevel.c.
 {
         s8 res;
         asm volatile ("plzcw   %0, %1\n": "=r" (res) : "r" (val));
         res = 31 - (res + 1);
         if(val > res)
                 res++;
         return res;
 }
Referenced by GsSelectTexure1(), and GsSelectTexure2().
Variable Documentation
GsPrimWorkArea
QWORD GsPrimWorkArea[] extern
Definition at line 18 of file packets.c.
Referenced by GsEnableColorClamp(), GsSelectTexure1(), GsSelectTexure2(), GsSetFogColor(), GsSetFrame1(), GsSetFrame2(), GsSetPixelTest1(), GsSetPixelTest2(), GsSetScissor1(), GsSetScissor2(), GsSetXYOffset1(), GsSetXYOffset2(), and GsTextureFlush().