ps2sdk: ee/rpc/multitap/samples/mtap_sample.c File Reference
mtap_sample.c File Reference
#include <tamtypes.h>
#include <kernel.h>
#include <sifrpc.h>
#include <loadfile.h>
#include <stdio.h>
#include <string.h>
#include "gs_privileged.h"
#include "libpad.h"
#include "libmtap.h"
Functions
int wait_vsync (void)
void loadmodules (int free)
void find_controllers ()
int main (int argc, char **argv)
Variables
static char * padBuf [2][4]
static u32 padConnected [2][4]
static u32 padOpen [2][4]
static u32 mtapConnected [2]
static u32 maxslot [2]
Function Documentation
find_controllers()
void find_controllers ()
Definition at line 105 of file mtap_sample.c.
 {
         u32 port, slot;
         u32 mtapcon;
         // Look for multitaps and controllers on both ports
         for(port = 0; port < 2; port++)
         {
                 //if(mtapConnected[port] == 0) mtapPortOpen(port);
                 mtapcon = mtapGetConnection(port);
                 // if(mtapcon == 0) mtapPortClose(port);
                 if((mtapcon == 1) && (mtapConnected[port] == 0))
                 {
                         printf("Multitap (%i) connected\n", (int)port);
                 }
                 if((mtapcon == 0) && (mtapConnected[port] == 1))
                 {
                         printf("Multitap (%i) disconnected(int argc, char **argv)\n", (int)port);
                 }
                 mtapConnected[port] = mtapcon;
                 // Check for multitap
                 if(mtapConnected[port] == 1)
                         maxslot[port] = 4;
                 else
                         maxslot[port] = 1;
                 // Find any connected controllers
                 for(slot=0; slot < maxslot[port]; slot++)
                 {
                         if(padOpen[port][slot] == 0)
{
                                 padOpen[port][slot] = padPortOpen(port, slot, padBuf[port][slot]);
                                 //if(padOpen[port][slot])
                                 //      printf("padOpen(%i, %i) = %i\n", port, slot, padOpen[port][slot] );
                         }
                         if(padOpen[port][slot] == 1)
{
                         if(padGetState(port, slot) == PAD_STATE_STABLE)
{
                                 if(padConnected[port][slot] == 0)
{
                                         printf("Controller (%i,%i) connected\n", (int)port, (int)slot);
                                 }
                                 padConnected[port][slot] = 1;
                         }
                         else
{
                                 if((padGetState(port, slot) == PAD_STATE_DISCONN) && (padConnected[port][slot] == 1))
{
                                         printf("Controller (%i,%i) disconnected\n", (int)port, (int)slot);
                                         padConnected[port][slot] = 0;
                                 }
                         }
                         }
                 }
                 // Close controllers when multitap is disconnected
                 if(mtapConnected[port] == 0)
                 {
                         for(slot=1; slot < 4; slot++)
{
                                 if(padOpen[port][slot] == 1)
{
                                         padPortClose(port, slot);
                                         padOpen[port][slot] = 0;
                                 }
                         }
                 }
         }
 }
References maxslot, mtapConnected, mtapGetConnection(), PAD_STATE_DISCONN, PAD_STATE_STABLE, padBuf, padConnected, padGetState(), padOpen, padPortClose(), padPortOpen(), port, and slot.
Referenced by main().
loadmodules()
void loadmodules (int free)
Definition at line 48 of file mtap_sample.c.
 {
     int ret;
         if(free == 1)
         {
                 ret = SifLoadModule("host0:sio2man.irx", 0, NULL);
             if (ret < 0) {
                 printf("SifLoadModule sio2man.irx failed: %d\n", ret);
                 SleepThread();
             }
                 ret = SifLoadModule("host0:mtapman.irx", 0, NULL);
             if (ret < 0) {
                 printf("SifLoadModule mtapman.irx failed: %d\n", ret);
                 SleepThread();
             }
             ret = SifLoadModule("host0:padman.irx", 0, NULL);
             if (ret < 0) {
                 printf("SifLoadModule padman.irx failed: %d\n", ret);
                 SleepThread();
             }
         }
         else
         {
             ret = SifLoadModule("rom0:XSIO2MAN", 0, NULL);
             if (ret < 0) {
                 printf("SifLoadModule XSIO2MAN failed: %d\n", ret);
                 SleepThread();
             }
                 ret = SifLoadModule("rom0:XMTAPMAN", 0, NULL);
             if (ret < 0) {
                 printf("SifLoadModule XMTAPMAN failed: %d\n", ret);
                 SleepThread();
             }
             ret = SifLoadModule("rom0:XPADMAN", 0, NULL);
             if (ret < 0) {
                 printf("SifLoadModule XPADMAN failed: %d\n", ret);
                 SleepThread();
             }
         }
 }
References NULL, SifLoadModule(), and SleepThread().
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 193 of file mtap_sample.c.
 {
         u32 i;
     struct padButtonStatus buttons;
     u32 paddata;
     u32 old_pad[2][4];
     u32 new_pad[2][4];
         s32 ret;
         SifInitRpc(0);
     printf("libmtap sample");
         if((argc == 2) && (strncmp(argv[1], "free", 4) == 0))
         {
                 printf(" - Using PS2SDK sio2man.irx, mtapman.irx and padman.irx modules.\n");
                 loadmodules(1);
         }
         else
         {
                 printf(" - Using ROM XSIO2MAN, XMTAP and XPADMAN modules.\n");
                 printf("Start this sample with 'free' as an argument to load sio2man.irx, mtapman.irx and padman.irx\n");
                 printf("Example: ps2client execee host:mtap_sample.elf free\n");
                 loadmodules(0);
         }
         mtapInit();
     padInit(0);
         mtapConnected[0] = 0;
         mtapConnected[1] = 0;
         mtapPortOpen(0);
         mtapPortOpen(1);
         for(i = 0; i < 4; i++)
         {
                 padConnected[0][i] = 0;
                 padConnected[1][i] = 0;
                 padOpen[0][i] = 0;
                 padOpen[1][i] = 0;
                 old_pad[0][i] = 0;
                 old_pad[1][i] = 0;
                 new_pad[0][i] = 0;
                 new_pad[1][i] = 0;
                 padBuf[0][i] = memalign(64, 256);
                 padBuf[1][i] = memalign(64, 256);
         }
         while(1)
         {
                 u32 port, slot;
                 find_controllers();
                 for(port = 0; port < 2 ; port++)
                 {
                         for(slot=0; slot < maxslot[port]; slot++)
{
                                 if(padOpen[port][slot] && padConnected[port][slot])
{
                                         ret = padRead(port, slot, &buttons);
                                 if (ret != 0)
{
                                 paddata = 0xffff ^ buttons.btns;
                                                 new_pad[port][slot] = paddata & ~old_pad[port][slot];
                                 old_pad[port][slot] = paddata;
                                                 if(new_pad[port][slot]) printf("Controller (%i,%i) button(s) pressed: ", (int)port, (int)slot);
                                 if(new_pad[port][slot] & PAD_LEFT)              printf("LEFT ");
                                                 if(new_pad[port][slot] & PAD_RIGHT)     printf("RIGHT ");
                                                 if(new_pad[port][slot] & PAD_UP)                printf("UP ");
                                                 if(new_pad[port][slot] & PAD_DOWN)              printf("DOWN ");
                                                 if(new_pad[port][slot] & PAD_START)     printf("START ");
                                                 if(new_pad[port][slot] & PAD_SELECT)    printf("SELECT ");
                                                 if(new_pad[port][slot] & PAD_SQUARE)    printf("SQUARE ");
                                                 if(new_pad[port][slot] & PAD_TRIANGLE)  printf("TRIANGLE ");
                                                 if(new_pad[port][slot] & PAD_CIRCLE)    printf("CIRCLE ");
                                                 if(new_pad[port][slot] & PAD_CROSS)             printf("CROSS ");
                                                 if(new_pad[port][slot] & PAD_L1)                printf("L1 ");
                                                 if(new_pad[port][slot] & PAD_L2)                printf("L2 ");
                                                 if(new_pad[port][slot] & PAD_L3)                printf("L3 ");
                                                 if(new_pad[port][slot] & PAD_R1)                printf("R1 ");
                                                 if(new_pad[port][slot] & PAD_R2)                printf("R2 ");
                                                 if(new_pad[port][slot] & PAD_R3)                printf("R3 ");
                                                 if(new_pad[port][slot]) printf("\n");
                                         }
                                 }
                         }
                 }
                 wait_vsync();
         }
     return 0;
 }
References padButtonStatus::btns, find_controllers(), loadmodules(), maxslot, mtapConnected, mtapInit(), mtapPortOpen(), new_pad, old_pad, PAD_CIRCLE, PAD_CROSS, PAD_DOWN, PAD_L1, PAD_L2, PAD_L3, PAD_LEFT, PAD_R1, PAD_R2, PAD_R3, PAD_RIGHT, PAD_SELECT, PAD_SQUARE, PAD_START, PAD_TRIANGLE, PAD_UP, padBuf, padConnected, paddata, padInit(), padOpen, padRead(), port, SifInitRpc(), slot, and wait_vsync().
wait_vsync()
int wait_vsync (void)
Definition at line 31 of file mtap_sample.c.
  {
   // Enable the vsync interrupt.
   *GS_REG_CSR |= GS_SET_CSR(0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
   // Wait for the vsync interrupt.
   while (!(*GS_REG_CSR & (GS_SET_CSR(0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0)))) { }
   // Disable the vsync interrupt.
   *GS_REG_CSR &= ~GS_SET_CSR(0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
   // End function.
   return 0;
  }
References GS_REG_CSR, and GS_SET_CSR.
Referenced by main().
Variable Documentation
maxslot
u32 maxslot[2] static
Definition at line 28 of file mtap_sample.c.
Referenced by find_controllers(), and main().
mtapConnected
u32 mtapConnected[2] static
Definition at line 27 of file mtap_sample.c.
Referenced by find_controllers(), and main().
padBuf
char* padBuf[2][4] static
Definition at line 24 of file mtap_sample.c.
Referenced by find_controllers(), and main().
padConnected
u32 padConnected[2][4] static
Definition at line 25 of file mtap_sample.c.
Referenced by find_controllers(), and main().
padOpen
u32 padOpen[2][4] static
Definition at line 26 of file mtap_sample.c.
Referenced by find_controllers(), and main().