ps2sdk: ee/packet/src/packet.c File Reference
packet.c File Reference
#include <string.h>
#include <stdlib.h>
#include <malloc.h>
#include <packet.h>
Macros
#define SPR_BEGIN 0x70000000
Functions
packet_t * packet_init (int qwords, int type)
void packet_free (packet_t *packet)
void packet_reset (packet_t *packet)
Macro Definition Documentation
SPR_BEGIN
#define SPR_BEGIN 0x70000000
Definition at line 6 of file packet.c.
Function Documentation
packet_free()
void packet_free (packet_t * packet)
Free the space allocated by packet.
Definition at line 63 of file packet.c.
 {
         // Free the allocated data buffer.
         if (packet->type == PACKET_SPR)
         {
                 packet->data = NULL;
         }
         else
         {
                 if (packet->type == PACKET_UCAB)
                 {
                         packet->data = (qword_t *)((u32)packet->data ^ 0x30000000);
                 }
                 free(packet->data);
         }
         free(packet);
 }
References packet_t::data, NULL, packet, PACKET_SPR, PACKET_UCAB, and packet_t::type.
Referenced by draw_init_env(), init_drawing_environment(), init_texture(), load_texture(), main(), render(), and setup_texture().
packet_init()
packet_t* packet_init (int qwords, int type)
Allocate a new packet for use, size in quadwords.
Definition at line 8 of file packet.c.
 {
         int byte_size = 0;
         packet_t *packet = (packet_t*)calloc(1,sizeof(packet_t));
         if (packet == NULL)
         {
                 return NULL;
         }
         if (type == PACKET_SPR)
         {
                 packet->data = (qword_t *)SPR_BEGIN;
                 packet->qwc = 0x1000;
         }
         else
         {
                 // Size of qwords in bytes.
                 byte_size = qwords << 4;
                 // Allocate the data area in bytes aligned to cache line.
                 if ((packet->data = memalign(64, byte_size)) == NULL)
                 {
                         free(packet);
                         return NULL;
                 }
         }
         // Set the pointer attribute to ucab space.
         if (type == PACKET_UCAB)
         {
                 packet->data = (qword_t *)((u32)packet->data | 0x30000000);
         }
         // Clear the packet area.
         memset(packet->data, 0, byte_size);
         // Set the packet counts
         packet->qwc = 0;
         packet->qwords = qwords;
         packet->type = type;
         // End function.
         return packet;
 }
References packet_t::data, NULL, packet, PACKET_SPR, PACKET_UCAB, packet_t::qwc, packet_t::qwords, SPR_BEGIN, and packet_t::type.
Referenced by draw_init_env(), init_drawing_environment(), init_texture(), InitCB(), load_texture(), main(), render(), run_demo(), and setup_texture().
packet_reset()
void packet_reset (packet_t * packet)
Reset the packet quadword counter and zero out data.
Definition at line 89 of file packet.c.
 {
         // Reset the quadword counter.
         packet->qwc = 0;
         if (packet->type == PACKET_SPR)
         {
                 packet->data = (qword_t *)SPR_BEGIN;
                 return;
         }
         // Zero out the data
         memset(packet->data, 0, packet->qwords << 4);
 }
References packet_t::data, packet, PACKET_SPR, packet_t::qwc, packet_t::qwords, SPR_BEGIN, and packet_t::type.