ps2sdk: ee/rpc/audsrv/samples/playcdda/playcdda.c File Reference
playcdda.c File Reference
#include <stdio.h>
#include <string.h>
#include <kernel.h>
#include <sifrpc.h>
#include <loadfile.h>
#include <tamtypes.h>
#include <audsrv.h>
Functions
static void cdda_stopped (void *arg)
int main (int argc, char **argv)
Variables
static volatile int track_ended = 0
Function Documentation
cdda_stopped()
static void cdda_stopped (void * arg) static
Definition at line 25 of file playcdda.c.
 {
         track_ended = 1;
 }
References track_ended.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 30 of file playcdda.c.
 {
         int ret;
         int track;
         int lastpos;
         SifInitRpc(0);
         printf("sample: kicking IRXs\n");
         ret = SifLoadModule("rom0:LIBSD", 0, NULL);
         printf("libsd loadmodule %d\n", ret);
         printf("sample: loading audsrv\n");
         ret = SifLoadModule("host:audsrv.irx", 0, NULL);
         printf("audsrv loadmodule %d\n", ret);
         ret = audsrv_init();
         if (ret != 0)
         {
                 printf("sample: failed to initialize audsrv\n");
                 printf("audsrv returned error string: %s\n", audsrv_get_error_string());
                 return 1;
         }
         printf("setting callback\n");
         audsrv_on_cdda_stop((void *)cdda_stopped, 0);
         track = 4;
         printf("playing track %d\n", track);
         audsrv_play_cd(track);
         //printf("starting loop\n");
         lastpos = 0;
         while (track_ended == 0)
         {
                 int pos;
                 if (audsrv_get_cdpos() == 0)
                 {
                         printf("-- track ended before semaphore --\n");
                         break;
                 }
                 pos = audsrv_get_trackpos();
                 nopdelay();
                 if (lastpos != pos)
                 {
                         printf("\rTrack %02d: %02d:%02d:%02d",
                         track, pos / (75*60), (pos / 75) % 60, pos % 75);
                         lastpos = pos;
                 }
         }
         printf("\n");
         printf("track ended\n");
         audsrv_quit();
         printf("sample: ended\n");
         return 0;
 }
References audsrv_get_cdpos(), audsrv_get_error_string(), audsrv_get_trackpos(), audsrv_init(), audsrv_on_cdda_stop(), audsrv_play_cd(), audsrv_quit(), cdda_stopped(), nopdelay(), NULL, pos, SifInitRpc(), SifLoadModule(), and track_ended.
Variable Documentation
track_ended
volatile int track_ended = 0 static
Definition at line 23 of file playcdda.c.
Referenced by cdda_stopped(), and main().