ps2sdk: ee/rpc/audsrv/samples/playadpcm/playadpcm.c File Reference
playadpcm.c File Reference
#include <stdio.h>
#include <string.h>
#include <kernel.h>
#include <sifrpc.h>
#include <loadfile.h>
#include <tamtypes.h>
#include <audsrv.h>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 22 of file playadpcm.c.
 {
         /* Uncomment to hear two samples played simultaenously
         int i;
         */
         int ret;
         FILE* adpcm;
         audsrv_adpcm_t sample;
         int size;
         u8* buffer;
         SifInitRpc(0);
         printf("sample: kicking IRXs\n");
         ret = SifLoadModule("rom0:LIBSD", 0, NULL);
         printf("libsd loadmodule %d\n", ret);
         printf("sample: loading audsrv\n");
         ret = SifLoadModule("host:audsrv.irx", 0, NULL);
         printf("audsrv loadmodule %d\n", ret);
         ret = audsrv_init();
         if (ret != 0)
         {
                 printf("sample: failed to initialize audsrv\n");
                 printf("audsrv returned error string: %s\n", audsrv_get_error_string());
                 return 1;
         }
         adpcm = fopen("host:evillaugh.adp", "rb");
         if (adpcm == NULL)
         {
                 printf("failed to open adpcm file\n");
                 audsrv_quit();
                 return 1;
         }
         fseek(adpcm, 0, SEEK_END);
         size = ftell(adpcm);
         fseek(adpcm, 0, SEEK_SET);
         buffer = malloc(size);
         fread(buffer, 1, size, adpcm);
         fclose(adpcm);
         printf("playing sample..\n");
         audsrv_adpcm_init();
         audsrv_set_volume(MAX_VOLUME);
         audsrv_adpcm_set_volume(0, MAX_VOLUME);
         audsrv_load_adpcm(&sample, buffer, size);
         audsrv_ch_play_adpcm(0, &sample);
         /* Uncomment to hear two samples played simultaenously
         for (i=0; i<100; i++)
         {
                 nopdelay();
         }
         audsrv_adpcm_set_volume(1, MAX_VOLUME);
         audsrv_ch_play_adpcm(1, &sample);
         */
         printf("sample played..\n");
         free(buffer);
         while (1);
         return 0;
 }
References audsrv_adpcm_init(), audsrv_adpcm_set_volume(), audsrv_ch_play_adpcm(), audsrv_get_error_string(), audsrv_init(), audsrv_load_adpcm(), audsrv_quit(), audsrv_set_volume(), buffer, MAX_VOLUME, NULL, SifInitRpc(), and SifLoadModule().