ps2sdk: ee/libgs/src/primitives.c File Reference
primitives.c File Reference
#include <errno.h>
#include <stdio.h>
#include <kernel.h>
#include <libgs.h>
#include "internal.h"
Functions
void GsOverridePrimAttributes (s8 override, s8 iip, s8 tme, s8 fge, s8 abe, s8 aa1, s8 fst, s8 ctxt, s8 fix)
void GsEnableDithering (u8 enable, int mode)
void GsEnableAlphaTransparency1 (u16 enable, u16 method, u8 alpha_ref, u16 fail_method)
void GsEnableAlphaTransparency2 (u16 enable, u16 method, u8 alpha_ref, u16 fail_method)
void GsEnableZbuffer1 (u16 enable, u16 test_method)
void GsEnableZbuffer2 (u16 enable, u16 test_method)
void GsEnableAlphaBlending1 (u16 enable)
void GsEnableAlphaBlending2 (u16 enable)
Variables
QWORD GsPrimWorkArea []
static GS_TEST GSGLOBAL_TEST1
static GS_TEST GSGLOBAL_TEST2
Function Documentation
GsEnableAlphaBlending1()
void GsEnableAlphaBlending1 (u16 enable)
Definition at line 137 of file primitives.c.
 {
         QWORD *p;
         p=UNCACHED_SEG(GsPrimWorkArea);
         gs_setGIF_TAG(((GS_GIF_TAG *)&p[0]), 4,1,0,0,GS_GIF_PACKED,1,gif_rd_ad);
         if(enable)
         {
                 gs_setR_ALPHA_1(((GS_R_ALPHA *)&p[1]), 0,1,0,1,0x00); //last arg(0x00) is not used bceause of other settings
         }
         else
         {
                 gs_setR_ALPHA_1(((GS_R_ALPHA *)&p[1]), 0,0,0,0,0x80);
         }
         gs_setR_PABE(((GS_R_PABE *)&p[2]), 0);
         gs_setR_FBA_1(((GS_R_FBA *)&p[3]), 0);
         gs_setR_TEXA(((GS_R_TEXA *)&p[4]), 0x80, 0, 0x00);
         GsDmaSend(GsPrimWorkArea, 5);
         GsDmaWait();
 }
References gif_rd_ad, GS_GIF_PACKED, gs_setGIF_TAG, gs_setR_ALPHA_1, gs_setR_FBA_1, gs_setR_PABE, gs_setR_TEXA, GsDmaSend(), GsDmaWait(), GsPrimWorkArea, and UNCACHED_SEG.
Referenced by InitGraphics().
GsEnableAlphaBlending2()
void GsEnableAlphaBlending2 (u16 enable)
Definition at line 160 of file primitives.c.
 {
         QWORD *p;
         p=UNCACHED_SEG(GsPrimWorkArea);
         gs_setGIF_TAG(((GS_GIF_TAG*)&p[0]), 4,1,0,0,GS_GIF_PACKED,1,gif_rd_ad);
         if(enable)
         {
                 gs_setR_ALPHA_2(((GS_R_ALPHA*)&p[1]), 0,1,0,1,0x00); //last arg(0x00) is not used bceause of other settings
         }
         else
         {
                 gs_setR_ALPHA_2(((GS_R_ALPHA *)&p[1]), 0,0,0,0,0x80);
         }
         gs_setR_PABE(((GS_R_PABE *)&p[2]), 0);
         gs_setR_FBA_2(((GS_R_FBA *)&p[3]), 0);
         gs_setR_TEXA(((GS_R_TEXA *)&p[4]), 0x80, 0, 0x00);
         GsDmaSend(GsPrimWorkArea, 5);
         GsDmaWait();
 }
References gif_rd_ad, GS_GIF_PACKED, gs_setGIF_TAG, gs_setR_ALPHA_2, gs_setR_FBA_2, gs_setR_PABE, gs_setR_TEXA, GsDmaSend(), GsDmaWait(), GsPrimWorkArea, and UNCACHED_SEG.
Referenced by InitGraphics().
GsEnableAlphaTransparency1()
void GsEnableAlphaTransparency1 (u16 enable, u16 method, u8 alpha_ref, u16 fail_method)
Definition at line 72 of file primitives.c.
 {
         QWORD *p;
         p=UNCACHED_SEG(GsPrimWorkArea);
         GSGLOBAL_TEST1.atest_enable = enable;
         GSGLOBAL_TEST1.atest_method = method;
         GSGLOBAL_TEST1.atest_reference = alpha_ref;
         GSGLOBAL_TEST1.atest_fail_method = fail_method;
         GsSetPixelTest1(GSGLOBAL_TEST1.atest_enable, GSGLOBAL_TEST1.atest_method, GSGLOBAL_TEST1.atest_reference, GSGLOBAL_TEST1.atest_fail_method,
                                         GSGLOBAL_TEST1.datest_enable, GSGLOBAL_TEST1.datest_mode,
                                         GSGLOBAL_TEST1.ztest_enable,  GSGLOBAL_TEST1.ztest_method);
         // tell GS in 16bit texture 1=transparent,0=solid
         gs_setGIF_TAG(((GS_GIF_TAG *)&p[0]), 1,1,0,0,GS_GIF_PACKED,1,gif_rd_ad);
         gs_setR_TEXA(((GS_R_TEXA *)&p[1]), 0x80, 0, 0x00);
         GsDmaSend(GsPrimWorkArea, 2);
         GsDmaWait();
 }
References GS_TEST::atest_enable, GS_TEST::atest_fail_method, GS_TEST::atest_method, GS_TEST::atest_reference, GS_TEST::datest_enable, GS_TEST::datest_mode, gif_rd_ad, GS_GIF_PACKED, gs_setGIF_TAG, gs_setR_TEXA, GsDmaSend(), GsDmaWait(), GSGLOBAL_TEST1, GsPrimWorkArea, GsSetPixelTest1(), UNCACHED_SEG, GS_TEST::ztest_enable, and GS_TEST::ztest_method.
Referenced by InitGraphics().
GsEnableAlphaTransparency2()
void GsEnableAlphaTransparency2 (u16 enable, u16 method, u8 alpha_ref, u16 fail_method)
Definition at line 94 of file primitives.c.
 {
         QWORD *p;
         p=UNCACHED_SEG(GsPrimWorkArea);
         GSGLOBAL_TEST2.atest_enable = enable;
         GSGLOBAL_TEST2.atest_method = method;
         GSGLOBAL_TEST2.atest_reference = alpha_ref;
         GSGLOBAL_TEST2.atest_fail_method = fail_method;
         GsSetPixelTest2(GSGLOBAL_TEST2.atest_enable, GSGLOBAL_TEST2.atest_method, GSGLOBAL_TEST2.atest_reference, GSGLOBAL_TEST2.atest_fail_method,
                                         GSGLOBAL_TEST2.datest_enable, GSGLOBAL_TEST2.datest_mode,
                                         GSGLOBAL_TEST2.ztest_enable,  GSGLOBAL_TEST2.ztest_method);
         // tell GS in 16bit texture 1=transparent,0=solid
         gs_setGIF_TAG(((GS_GIF_TAG *)&p[0]), 1,1,0,0,GS_GIF_PACKED,1,gif_rd_ad);
         gs_setR_TEXA(((GS_R_TEXA *)&p[1]), 0x80, 0, 0x00);
         GsDmaSend(GsPrimWorkArea, 2);
         GsDmaWait();
 }
References GS_TEST::atest_enable, GS_TEST::atest_fail_method, GS_TEST::atest_method, GS_TEST::atest_reference, GS_TEST::datest_enable, GS_TEST::datest_mode, gif_rd_ad, GS_GIF_PACKED, gs_setGIF_TAG, gs_setR_TEXA, GsDmaSend(), GsDmaWait(), GSGLOBAL_TEST2, GsPrimWorkArea, GsSetPixelTest2(), UNCACHED_SEG, GS_TEST::ztest_enable, and GS_TEST::ztest_method.
Referenced by InitGraphics().
GsEnableDithering()
void GsEnableDithering (u8 enable, int mode)
Definition at line 46 of file primitives.c.
 {
         QWORD *p;
         p=UNCACHED_SEG(GsPrimWorkArea);
         if(enable)
         {
                 gs_setGIF_TAG(((GS_GIF_TAG *)&p[0]), 3,1,0,0,GS_GIF_PACKED,1,gif_rd_ad);
                 gs_setR_DTHE(((GS_R_DTHE *)&p[1]), 1);
                 gs_setR_DIMX(((GS_R_DIMX *)&p[2]), 4,2,5,3,0,6,1,7,5,3,4,2,1,7,0,6); //thanks to:"Maximus32" on ps2dev.org
                 gs_setR_COLCLAMP(((GS_R_COLCLAMP *)&p[3]), 1);
                 GsDmaSend(GsPrimWorkArea, 4);
         }
         else
         {
                 gs_setGIF_TAG(((GS_GIF_TAG *)&p[0]), 2,1,0,0,GS_GIF_PACKED,1,gif_rd_ad);
                 gs_setR_DTHE(((GS_R_DTHE *)&p[1]), 0);
                 gs_setR_DIMX(((GS_R_DIMX *)&p[2]), 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
                 GsDmaSend(GsPrimWorkArea, 3);
         }
         GsDmaWait();
 }
References gif_rd_ad, GS_GIF_PACKED, gs_setGIF_TAG, gs_setR_COLCLAMP, gs_setR_DIMX, gs_setR_DTHE, GsDmaSend(), GsDmaWait(), GsPrimWorkArea, and UNCACHED_SEG.
GsEnableZbuffer1()
void GsEnableZbuffer1 (u16 enable, u16 test_method)
Definition at line 116 of file primitives.c.
 {
         GSGLOBAL_TEST1.ztest_enable = enable;
         GSGLOBAL_TEST1.ztest_method = test_method;
         GsSetPixelTest1(GSGLOBAL_TEST1.atest_enable, GSGLOBAL_TEST1.atest_method, GSGLOBAL_TEST1.atest_reference, GSGLOBAL_TEST1.atest_fail_method,
                                         GSGLOBAL_TEST1.datest_enable, GSGLOBAL_TEST1.datest_mode,
                                         GSGLOBAL_TEST1.ztest_enable,  GSGLOBAL_TEST1.ztest_method);
 }
References GS_TEST::atest_enable, GS_TEST::atest_fail_method, GS_TEST::atest_method, GS_TEST::atest_reference, GS_TEST::datest_enable, GS_TEST::datest_mode, GSGLOBAL_TEST1, GsSetPixelTest1(), GS_TEST::ztest_enable, and GS_TEST::ztest_method.
GsEnableZbuffer2()
void GsEnableZbuffer2 (u16 enable, u16 test_method)
Definition at line 126 of file primitives.c.
 {
         GSGLOBAL_TEST2.ztest_enable = enable;
         GSGLOBAL_TEST2.ztest_method = test_method;
         GsSetPixelTest2(GSGLOBAL_TEST2.atest_enable, GSGLOBAL_TEST2.atest_method, GSGLOBAL_TEST2.atest_reference, GSGLOBAL_TEST2.atest_fail_method,
                                         GSGLOBAL_TEST2.datest_enable, GSGLOBAL_TEST2.datest_mode,
                                         GSGLOBAL_TEST2.ztest_enable,  GSGLOBAL_TEST2.ztest_method);
 }
References GS_TEST::atest_enable, GS_TEST::atest_fail_method, GS_TEST::atest_method, GS_TEST::atest_reference, GS_TEST::datest_enable, GS_TEST::datest_mode, GSGLOBAL_TEST2, GsSetPixelTest2(), GS_TEST::ztest_enable, and GS_TEST::ztest_method.
GsOverridePrimAttributes()
void GsOverridePrimAttributes (s8 override, s8 iip, s8 tme, s8 fge, s8 abe, s8 aa1, s8 fst, s8 ctxt, s8 fix)
Definition at line 23 of file primitives.c.
 {
         QWORD *p;
         p=UNCACHED_SEG(GsPrimWorkArea);
         gs_setGIF_TAG(((GS_GIF_TAG *)&p[0]), 2,1,0,0,GS_GIF_PACKED,1,gif_rd_ad);
         //override. (0 = use PRIM)(1 = use PRMODE)
         if(override)
         {
                 gs_setR_PRMODECONT(((GS_R_PRMODECONT *)&p[1]), 0);
         }
         else
         {
                 gs_setR_PRMODECONT(((GS_R_PRMODECONT *)&p[1]), 1);
         }
         gs_setR_PRMODE(((GS_R_PRMODE *)&p[2]), iip,tme,fge,abe,aa1,fst,ctxt,fix);
         GsDmaSend(GsPrimWorkArea, 3);
         GsDmaWait();
 }
References gif_rd_ad, GS_GIF_PACKED, gs_setGIF_TAG, gs_setR_PRMODE, gs_setR_PRMODECONT, GsDmaSend(), GsDmaWait(), GsPrimWorkArea, and UNCACHED_SEG.
Referenced by InitGraphics().
Variable Documentation
GSGLOBAL_TEST1
GS_TEST GSGLOBAL_TEST1 static
Definition at line 20 of file primitives.c.
Referenced by GsEnableAlphaTransparency1(), and GsEnableZbuffer1().
GSGLOBAL_TEST2
GS_TEST GSGLOBAL_TEST2 static
Definition at line 21 of file primitives.c.
Referenced by GsEnableAlphaTransparency2(), and GsEnableZbuffer2().
GsPrimWorkArea
QWORD GsPrimWorkArea[] extern
Definition at line 18 of file packets.c.
Referenced by GsEnableAlphaBlending1(), GsEnableAlphaBlending2(), GsEnableAlphaTransparency1(), GsEnableAlphaTransparency2(), GsEnableDithering(), and GsOverridePrimAttributes().