ps2sdk: ee/rpc/camera/src/ps2cam_rpc.c File Reference
ps2cam_rpc.c File Reference
#include <tamtypes.h>
#include <kernel.h>
#include <sifrpc.h>
#include <stdio.h>
#include <string.h>
#include "../include/ps2cam_rpc.h"
Macros
#define PS2_CAM_RPC_ID 0x00FD000 +2
Functions
int PS2CamInit (int mode)
int PS2CamGetIRXVersion (void)
int PS2CamGetDeviceCount (void)
int PS2CamOpenDevice (int device_index)
int PS2CamCloseDevice (int handle)
int PS2CamGetDeviceStatus (int handle)
int PS2CamGetDeviceInfo (int handle, PS2CAM_DEVICE_INFO *info)
int PS2CamSetDeviceBandwidth (int handle, char bandwidth)
int PS2CamReadPacket (int handle)
int PS2CamSetLEDMode (int handle, int mode)
int PS2CamSetDeviceConfig (int handle, PS2CAM_DEVICE_CONFIG *cfg)
int PS2CamExtractFrame (int handle, char *buffer, int bufsize)
Variables
static int CamInited = 0
static SifRpcClientData_t cdata
static char data [1024]
static char campacket [896]
ee_sema_t compSema
int sem
Detailed Description
PS2CAM.irx rpc client
Definition in file ps2cam_rpc.c.
Macro Definition Documentation
PS2_CAM_RPC_ID
#define PS2_CAM_RPC_ID 0x00FD000 +2
Definition at line 21 of file ps2cam_rpc.c.
Function Documentation
PS2CamCloseDevice()
int PS2CamCloseDevice (int handle)
Definition at line 134 of file ps2cam_rpc.c.
 {
         int *ret;
         ret = (int *)&data[0];
         ret[0] = handle;
         SifCallRpc(&cdata, PS2CAM_RPC_CLOSEDEVICE, 0, (void*)(&data[0]),4,(void*)(&data[0]),4,0,0);
         return ret[0];
 }
References cdata, data, PS2CAM_RPC_CLOSEDEVICE, and SifCallRpc().
PS2CamExtractFrame()
int PS2CamExtractFrame (int handle, char * buffer, int bufsize)
Definition at line 284 of file ps2cam_rpc.c.
 {
         static EYETOY_FRAME_HEAD        *head;
         static int                      capturing;
         static int                      pos;
         static int                      ret;
         static int                      pic_size;
         pos                                     = 0;
         capturing                       = 0;
         while(1)
         {
                 ret  = PS2CamReadPacket(handle);
         //      printf("packet =%d\n",ret);
                 //if read has a error return it
                 if(ret < 0) return ret;
                 head = (EYETOY_FRAME_HEAD *)&campacket[0];
                 if(head->magic2==0xff && head->magic3==0xff && ret!=0)
                 {
                         if(head->type==0x50 && head->frame==0x00)
{
                                 // start of frame
                         //      printf("SOF(%d)\n",ret);
                                 if(capturing == 1)
{
                                         return 0;
                                 }
                                 memcpy(&buffer[pos], &campacket[16], ret-16 );
                                 pos += (ret-16);
                                 capturing = 1;
                         }
                         else if(head->type==0x50 && head->frame==0x01)
{
                                 // frame head with no data
                                 // so do nothing
                         }
                         else if(head->type==0x51 && capturing==1)
{
                                 //end of frame
                         //      printf("EOF(%d)\n",ret);
                                 pic_size = (int)(((head->Lo) + ((int)(head->Hi)<<8))<<3);
                                 if(pos != pic_size)
{
                                         return 0;
                                 }
                                 else
{
                                         return pic_size;
                                 }
                         }
                         else
{
                                 //if it doesnt fit in those pos then it must be data
                                 if(capturing==1)
{
                                         memcpy(&buffer[pos], &campacket[0], ret );
                                         pos += (ret);
                                 }
                         }
                 }
                 else
                 {
                         // it must be data
                         if(capturing==1 && ret !=0)
{
                                 memcpy(&buffer[pos], &campacket[0], ret );
                                 pos += (ret);
                         }
                 }
         }
 }
References buffer, campacket, EYETOY_FRAME_HEAD::frame, EYETOY_FRAME_HEAD::Hi, EYETOY_FRAME_HEAD::Lo, EYETOY_FRAME_HEAD::magic2, EYETOY_FRAME_HEAD::magic3, pos, PS2CamReadPacket(), and EYETOY_FRAME_HEAD::type.
Referenced by main().
PS2CamGetDeviceCount()
int PS2CamGetDeviceCount (void)
Definition at line 102 of file ps2cam_rpc.c.
 {
         int *ret;
         ret = (int *)&data[0];
         SifCallRpc(&cdata, PS2CAM_RPC_GETDEVCOUNT, 0, (void*)(&data[0]),4,(void*)(&data[0]),4,0,0);
         nopdelay();
         return ret[0];
 }
References cdata, data, nopdelay(), PS2CAM_RPC_GETDEVCOUNT, and SifCallRpc().
Referenced by main().
PS2CamGetDeviceInfo()
int PS2CamGetDeviceInfo (int handle, PS2CAM_DEVICE_INFO * info)
Definition at line 170 of file ps2cam_rpc.c.
 {
         int                                     *ret;
         PS2CAM_DEVICE_INFO      *iop_info;
         ret                     = (int *)&data[0];
         iop_info        = (PS2CAM_DEVICE_INFO *)&ret[1];
         ret[0] = handle;
         memcpy(iop_info, info, info->ssize);
         SifCallRpc(&cdata, PS2CAM_RPC_GETDEVINFO, 0, (void*)(&data[0]),info->ssize+4,(void*)(&data[0]),info->ssize+4,0,0);
         nopdelay();
         memcpy(info, iop_info, iop_info->ssize);
         return ret[0];
 }
References cdata, data, info, nopdelay(), PS2CAM_RPC_GETDEVINFO, SifCallRpc(), and PS2CAM_DEVICE_INFO::ssize.
Referenced by main().
PS2CamGetDeviceStatus()
int PS2CamGetDeviceStatus (int handle)
Definition at line 151 of file ps2cam_rpc.c.
 {
         int *ret;
         ret = (int *)&data[0];
         ret[0] = handle;
         SifCallRpc(&cdata, PS2CAM_RPC_GETDEVSTATUS, 0, (void*)(&data[0]),4,(void*)(&data[0]),4,0,0);
         nopdelay();
         return ret[0];
 }
References cdata, data, nopdelay(), PS2CAM_RPC_GETDEVSTATUS, and SifCallRpc().
Referenced by main().
PS2CamGetIRXVersion()
int PS2CamGetIRXVersion (void)
Definition at line 86 of file ps2cam_rpc.c.
 {
         int *ret;
         ret = (int *)&data[0];
         SifCallRpc(&cdata, PS2CAM_RPC_GETIRXVERSION, 0, (void*)(&data[0]),4,(void*)(&data[0]),4,0,0);
         nopdelay();
         return ret[0];
 }
References cdata, data, nopdelay(), PS2CAM_RPC_GETIRXVERSION, and SifCallRpc().
PS2CamInit()
int PS2CamInit (int mode)
Definition at line 37 of file ps2cam_rpc.c.
 {
         int                             ret=0;
         int                             *buf;
         // unsigned int i;
         // int timeout = 100000;
         if(CamInited)return 0;
         SifInitRpc(0);
         while (((ret = SifBindRpc(&cdata, PS2_CAM_RPC_ID, 0)) >= 0) && (cdata.server == NULL))
                 nopdelay();
         nopdelay();
         if (ret < 0)return ret;
         buf             = (int *)&data[0];
         buf[0]  = mode;
         printf("bind done\n");
         SifCallRpc(&cdata, PS2CAM_RPC_INITIALIZE, 0, (void*)(&data[0]),4,(void*)(&data[0]),4,0,0);
         nopdelay();
         CamInited = 1;
 printf("init done\n");
         compSema.init_count = 1;
         compSema.max_count = 1;
         compSema.option = 0;
         sem = CreateSema(&compSema);
 printf("sema done\n");
         return buf[0];
 }
References CamInited, cdata, compSema, CreateSema(), data, ee_sema_t::init_count, ee_sema_t::max_count, mode, nopdelay(), NULL, ee_sema_t::option, PS2_CAM_RPC_ID, PS2CAM_RPC_INITIALIZE, sem, SifRpcClientData_t::server, SifBindRpc(), SifCallRpc(), and SifInitRpc().
Referenced by main().
PS2CamOpenDevice()
int PS2CamOpenDevice (int device_index)
Definition at line 118 of file ps2cam_rpc.c.
 {
         int *ret;
         ret = (int *)&data[0];
         ret[0] = device_index;
         SifCallRpc(&cdata, PS2CAM_RPC_OPENDEVICE, 0, (void*)(&data[0]),4,(void*)(&data[0]),4,0,0);
         return ret[0];
 }
References cdata, data, PS2CAM_RPC_OPENDEVICE, and SifCallRpc().
Referenced by main().
PS2CamReadPacket()
int PS2CamReadPacket (int handle)
Definition at line 216 of file ps2cam_rpc.c.
 {
         int *ret;
         int *iop_addr;
         WaitSema(sem);
         ret = (int *)&data[0];
         ret[0] = handle;
         SifCallRpc(&cdata, PS2CAM_RPC_READPACKET, 0, (void*)(&data[0]),4,(void*)(&data[0]),4*2,0,0);
         if(ret[0] < 0) return ret[0];
         DI();
         ee_kmode_enter();
         iop_addr = (int *)(0xbc000000+ret[1]);
         memcpy(&campacket[0],iop_addr, ret[0]);
         ee_kmode_exit();
         EI();
         //if i add a printf here, the ps2 will exit to sony's explorer
         SignalSema(sem);
         return ret[0];
 }
References campacket, cdata, data, DI, ee_kmode_enter(), ee_kmode_exit(), EI, PS2CAM_RPC_READPACKET, sem, SifCallRpc(), SignalSema(), and WaitSema().
Referenced by PS2CamExtractFrame().
PS2CamSetDeviceBandwidth()
int PS2CamSetDeviceBandwidth (int handle, char bandwidth)
Definition at line 194 of file ps2cam_rpc.c.
 {
         int *ret;
         ret = (int *)&data[0];
         ret[0] = handle;
         ret[1] = bandwidth;
         SifCallRpc(&cdata, PS2CAM_RPC_SETDEVBANDWIDTH, 0, (void*)(&data[0]),4,(void*)(&data[0]),4,0,0);
         nopdelay();
         return ret[0];
 }
References cdata, data, nopdelay(), PS2CAM_RPC_SETDEVBANDWIDTH, and SifCallRpc().
Referenced by main().
PS2CamSetDeviceConfig()
int PS2CamSetDeviceConfig (int handle, PS2CAM_DEVICE_CONFIG * cfg)
Definition at line 267 of file ps2cam_rpc.c.
 {
         int *ret;
         ret = (int *)&data[0];
         ret[0] = handle;
         memcpy(&ret[1], cfg, cfg->ssize);
         SifCallRpc(&cdata, PS2CAM_RPC_SETDEVCONFIG, 0, (void*)(&data[0]), 4+cfg->ssize,(void*)(&data[0]),4+cfg->ssize,0,0);
         return ret[0];
 }
References cdata, cfg, data, PS2CAM_RPC_SETDEVCONFIG, SifCallRpc(), and PS2CAM_DEVICE_CONFIG::ssize.
Referenced by main().
PS2CamSetLEDMode()
int PS2CamSetLEDMode (int handle, int mode)
Definition at line 251 of file ps2cam_rpc.c.
 {
         int *ret;
         ret = (int *)&data[0];
         ret[0] = handle;
         ret[1] = mode;
         SifCallRpc(&cdata, PS2CAM_RPC_SETLEDMODE, 0, (void*)(&data[0]),4,(void*)(&data[0]),4,0,0);
         return ret[0];
 }
References cdata, data, mode, PS2CAM_RPC_SETLEDMODE, and SifCallRpc().
Variable Documentation
CamInited
int CamInited = 0 static
Definition at line 25 of file ps2cam_rpc.c.
Referenced by PS2CamInit().
campacket
char campacket[896] static
Definition at line 28 of file ps2cam_rpc.c.
Referenced by PS2CamExtractFrame(), and PS2CamReadPacket().
cdata
SifRpcClientData_t cdata static
Definition at line 26 of file ps2cam_rpc.c.
Referenced by PS2CamCloseDevice(), PS2CamGetDeviceCount(), PS2CamGetDeviceInfo(), PS2CamGetDeviceStatus(), PS2CamGetIRXVersion(), PS2CamInit(), PS2CamOpenDevice(), PS2CamReadPacket(), PS2CamSetDeviceBandwidth(), PS2CamSetDeviceConfig(), and PS2CamSetLEDMode().
compSema
ee_sema_t compSema
Definition at line 30 of file ps2cam_rpc.c.
Referenced by audsrv_init(), and PS2CamInit().
data
char data[1024] static
Definition at line 27 of file ps2cam_rpc.c.
Referenced by PS2CamCloseDevice(), PS2CamGetDeviceCount(), PS2CamGetDeviceInfo(), PS2CamGetDeviceStatus(), PS2CamGetIRXVersion(), PS2CamInit(), PS2CamOpenDevice(), PS2CamReadPacket(), PS2CamSetDeviceBandwidth(), PS2CamSetDeviceConfig(), and PS2CamSetLEDMode().
sem
int sem
Definition at line 32 of file ps2cam_rpc.c.
Referenced by PS2CamInit(), PS2CamReadPacket(), sys_sem_new(), sys_sem_set_invalid(), and sys_sem_valid().