ps2sdk: ee/libc/src/ps2sdkapi.c File Reference
ps2sdkapi.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <errno.h>
#include <string.h>
#include <kernel.h>
#include <malloc.h>
#include <sio.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <stdint.h>
#include <limits.h>
#include <inttypes.h>
#include <tamtypes.h>
#include "fileio.h"
#include "io_common.h"
#include "iox_stat.h"
#include "ps2sdkapi.h"
Macros
#define NEWLIB_PORT_AWARE
#define IOP_O_RDONLY 0x0001
#define IOP_O_WRONLY 0x0002
#define IOP_O_RDWR 0x0003
#define IOP_O_DIROPEN 0x0008
#define IOP_O_NBLOCK 0x0010
#define IOP_O_APPEND 0x0100
#define IOP_O_CREAT 0x0200
#define IOP_O_TRUNC 0x0400
#define IOP_O_EXCL 0x0800
#define IOP_O_NOWAIT 0x8000
#define ct_assert(e) {enum { ct_assert_value = 1/(!!(e)) };}
Functions
void * ps2_sbrk (size_t increment)
int fioRename (const char *old, const char *new)
int fioMkdirHelper (const char *path, int mode)
static time_t io_to_posix_time (const unsigned char *ps2time)
static mode_t io_to_posix_mode (unsigned int ps2mode)
static void fill_stat (struct stat *stat, const io_stat_t *fiostat)
static int fioGetstatHelper (const char *path, struct stat *buf)
static DIR * fioOpendirHelper (const char *path)
static struct dirent * fioReaddirHelper (DIR *dir)
static void fioRewinddirHelper (DIR *dir)
static int fioClosedirHelper (DIR *dir)
void compile_time_check ()
static char * normalize_path (const char *path_name)
static int isCdromPath (const char *path)
int _open (const char *buf, int flags,...)
int _close (int fd)
int _read (int fd, void *buf, size_t nbytes)
int _write (int fd, const void *buf, size_t nbytes)
int _fstat (int fd, struct stat *buf)
int _stat (const char *path, struct stat *buf)
int access (const char *fn, int flags)
DIR * opendir (const char *path)
struct dirent * readdir (DIR *dir)
void rewinddir (DIR *dir)
int closedir (DIR *dir)
int _isatty (int fd)
off_t _lseek (int fd, off_t offset, int whence)
off64_t lseek64 (int fd, off64_t offset, int whence)
int chdir (const char *path)
int mkdir (const char *path, mode_t mode)
int rmdir (const char *path)
int _link (const char *old, const char *new)
int _unlink (const char *path)
char * getcwd (char *buf, size_t len)
int _getpid (void)
int _kill (int pid, int sig)
void * _sbrk (size_t incr)
time_t time (time_t *t)
int _gettimeofday (struct timeval *tv, struct timezone *tz)
clock_t _times (struct tms *buffer)
long int random (void)
void srandom (unsigned int seed)
Variables
char __direct_pwd [256] = ""
int(* _ps2sdk_close)(int) = fioClose
int(* _ps2sdk_open)(const char *, int,...) = (void *)fioOpen
int(* _ps2sdk_read)(int, void *, int) = fioRead
int(* _ps2sdk_lseek)(int, int, int) = fioLseek
int64_t(* _ps2sdk_lseek64)(int, int64_t, int) = NULL
int(* _ps2sdk_write)(int, const void *, int) = fioWrite
int(* _ps2sdk_ioctl)(int, int, void *) = fioIoctl
int(* _ps2sdk_remove)(const char *) = fioRemove
int(* _ps2sdk_rename)(const char *, const char *) = fioRename
int(* _ps2sdk_mkdir)(const char *, int) = fioMkdirHelper
int(* _ps2sdk_rmdir)(const char *) = fioRmdir
int(* _ps2sdk_stat)(const char *path, struct stat *buf) = fioGetstatHelper
DIR *(* _ps2sdk_opendir)(const char *path) = fioOpendirHelper
struct dirent *(* _ps2sdk_readdir)(DIR *dir) = fioReaddirHelper
void(* _ps2sdk_rewinddir)(DIR *dir) = fioRewinddirHelper
int(* _ps2sdk_closedir)(DIR *dir) = fioClosedirHelper
Macro Definition Documentation
ct_assert
#define ct_assert (e) {enum { ct_assert_value = 1/(!!(e)) };}
Definition at line 211 of file ps2sdkapi.c.
IOP_O_APPEND
#define IOP_O_APPEND 0x0100
Definition at line 195 of file ps2sdkapi.c.
IOP_O_CREAT
#define IOP_O_CREAT 0x0200
Definition at line 196 of file ps2sdkapi.c.
IOP_O_DIROPEN
#define IOP_O_DIROPEN 0x0008
Definition at line 193 of file ps2sdkapi.c.
IOP_O_EXCL
#define IOP_O_EXCL 0x0800
Definition at line 198 of file ps2sdkapi.c.
IOP_O_NBLOCK
#define IOP_O_NBLOCK 0x0010
Definition at line 194 of file ps2sdkapi.c.
IOP_O_NOWAIT
#define IOP_O_NOWAIT 0x8000
Definition at line 199 of file ps2sdkapi.c.
IOP_O_RDONLY
#define IOP_O_RDONLY 0x0001
Definition at line 190 of file ps2sdkapi.c.
IOP_O_RDWR
#define IOP_O_RDWR 0x0003
Definition at line 192 of file ps2sdkapi.c.
IOP_O_TRUNC
#define IOP_O_TRUNC 0x0400
Definition at line 197 of file ps2sdkapi.c.
IOP_O_WRONLY
#define IOP_O_WRONLY 0x0002
Definition at line 191 of file ps2sdkapi.c.
NEWLIB_PORT_AWARE
#define NEWLIB_PORT_AWARE
Definition at line 34 of file ps2sdkapi.c.
Function Documentation
_close()
int _close (int fd)
Definition at line 366 of file ps2sdkapi.c.
                    {
         return _ps2sdk_close(fd);
 }
References _ps2sdk_close.
_fstat()
int _fstat (int fd, struct stat * buf)
Definition at line 382 of file ps2sdkapi.c.
{
         if (fd >=0 && fd <= 1) {
                 // Character device
                 buf->st_mode = S_IFCHR;
                 buf->st_blksize = 0;
         }
         else {
                 // Block device
                 buf->st_mode = S_IFBLK;
                 buf->st_blksize = 16*1024;
         }
         return 0;
 }
Referenced by _isatty().
_getpid()
int _getpid (void)
Definition at line 487 of file ps2sdkapi.c.
                   {
         return GetThreadId();
 }
References GetThreadId().
_gettimeofday()
int _gettimeofday (struct timeval * tv, struct timezone * tz)
Definition at line 531 of file ps2sdkapi.c.
{
         if (tz) {
                 /* Timezone not supported for gettimeofday */
                 tz->tz_minuteswest = 0;
                 tz->tz_dsttime = 0;
         }
         tv->tv_usec = 0;
         tv->tv_sec = time(0);
         return 0;
 }
References time().
_isatty()
int _isatty (int fd)
Definition at line 435 of file ps2sdkapi.c.
                     {
         struct stat buf;
         if (_fstat (fd, &buf) < 0) {
                 //errno = EBADF;
                 return 0;
         }
         if (S_ISCHR (buf.st_mode))
                 return 1;
         //errno = ENOTTY;
         return 0;
 }
References _fstat().
_kill()
int _kill (int pid, int sig)
Definition at line 491 of file ps2sdkapi.c.
{
 #if 0 // needs to be tested first
         // null signal: do error checking on pid only
         if (sig == 0)
                 return pid == getpid() ? 0 : -1;
         if (pid == getpid()) {
                 ExitDeleteThread();
                 // NOTE: ExitDeleteThread does not return
                 return 0;
         }
 #endif
         // FIXME: set errno
         return -1;
 }
References ExitDeleteThread().
_link()
int _link (const char * old, const char * new)
Definition at line 474 of file ps2sdkapi.c.
{
     return _ps2sdk_rename(old, new);
 }
References _ps2sdk_rename.
_lseek()
off_t _lseek (int fd, off_t offset, int whence)
Definition at line 448 of file ps2sdkapi.c.
 {
         return _ps2sdk_lseek(fd, offset, whence);
 }
References _ps2sdk_lseek.
_open()
int _open (const char * buf, int flags, ...)
Definition at line 301 of file ps2sdkapi.c.
{
         int iop_flags = 0;
         // newlib frags differ from iop flags
         if ((flags & 3) == O_RDONLY) iop_flags |= IOP_O_RDONLY;
         if ((flags & 3) == O_WRONLY) iop_flags |= IOP_O_WRONLY;
         if ((flags & 3) == O_RDWR  ) iop_flags |= IOP_O_RDWR;
         if (flags & O_NONBLOCK)      iop_flags |= IOP_O_NBLOCK;
         if (flags & O_APPEND)        iop_flags |= IOP_O_APPEND;
         if (flags & O_CREAT)         iop_flags |= IOP_O_CREAT;
         if (flags & O_TRUNC)         iop_flags |= IOP_O_TRUNC;
         if (flags & O_EXCL)          iop_flags |= IOP_O_EXCL;
         //if (flags & O_???)           iop_flags |= IOP_O_NOWAIT;
         char *t_fname = normalize_path(buf);
         char b_fname[FILENAME_MAX];
         if (!strchr(buf, ':')) { // filename doesn't contain device
                 t_fname = b_fname;
                 if (buf[0] == '/' || buf[0] == '\\') {   // does it contain root ?
                         char *device_end = strchr(__direct_pwd, ':');
                         if (device_end) {      // yes, let's strip pwd a bit to keep device only
                                 strncpy(b_fname, __direct_pwd, device_end - __direct_pwd);
                                 strcpy(b_fname + (device_end - __direct_pwd), buf);
                         } else {               // but pwd doesn't contain any device, let's default to host
                                 strcpy(b_fname, "host:");
                                 strcpy(b_fname + 5, buf);
                         }
                 } else {                 // otherwise, it's relative directory, let's copy pwd straight
                         int b_fname_len = strlen(__direct_pwd);
                         if (!strchr(__direct_pwd, ':')) { // check if pwd contains device name
                                 strcpy(b_fname, "host:");
                                 strcpy(b_fname + 5, __direct_pwd);
                                 if (!(__direct_pwd[b_fname_len - 1] == '/' || __direct_pwd[b_fname_len - 1] == '\\')) { // does it has trailing slash ?
                                         if(isCdromPath(b_fname)) {
                                                 b_fname[b_fname_len + 5] = '\\';
                                                 b_fname_len++;
                                         } else {
                                                 b_fname[b_fname_len + 5] = '/';
                                                 b_fname_len++;
                                         }
                                 }
                                 b_fname_len += 5;
                                 strcpy(b_fname + b_fname_len, buf);
                         } else {                          // device name is here
                                 if (b_fname_len) {
                                 strcpy(b_fname, __direct_pwd);
                                 if (!(b_fname[b_fname_len - 1] == '/' || b_fname[b_fname_len - 1] == '\\')) {
                                         if(isCdromPath(b_fname)) {
                                                 b_fname[b_fname_len] = '\\';
                                                 b_fname_len++;
                                         } else {
                                                 b_fname[b_fname_len] = '/';
                                                 b_fname_len++;
                                         }
                                 }
                                 strcpy(b_fname + b_fname_len, buf);
                                 }
                         }
                 }
         }
         return _ps2sdk_open(t_fname, iop_flags);
 }
References __direct_pwd, _ps2sdk_open, IOP_O_APPEND, IOP_O_CREAT, IOP_O_EXCL, IOP_O_NBLOCK, IOP_O_RDONLY, IOP_O_RDWR, IOP_O_TRUNC, IOP_O_WRONLY, isCdromPath(), normalize_path(), and O_NONBLOCK.
_read()
int _read (int fd, void * buf, size_t nbytes)
Definition at line 370 of file ps2sdkapi.c.
{
         return _ps2sdk_read(fd, buf, nbytes);
 }
References _ps2sdk_read.
_sbrk()
void* _sbrk (size_t incr)
Definition at line 507 of file ps2sdkapi.c.
{
         return ps2_sbrk(incr);
 }
References ps2_sbrk().
_stat()
int _stat (const char * path, struct stat * buf)
Definition at line 397 of file ps2sdkapi.c.
{
         return _ps2sdk_stat(path, buf);
 }
References _ps2sdk_stat.
_times()
clock_t _times (struct tms * buffer)
Definition at line 544 of file ps2sdkapi.c.
{
         clock_t clk = ps2_clock() / (PS2_CLOCKS_PER_SEC / CLOCKS_PER_SEC);
         if (buffer != NULL) {
                 buffer->tms_utime  = clk;
                 buffer->tms_stime  = 0;
                 buffer->tms_cutime = clk;
                 buffer->tms_cstime = 0;
         }
         return clk;
 }
References buffer, NULL, ps2_clock(), and PS2_CLOCKS_PER_SEC.
_unlink()
int _unlink (const char * path)
Definition at line 478 of file ps2sdkapi.c.
{
     return _ps2sdk_remove(path);
 }
References _ps2sdk_remove.
_write()
int _write (int fd, const void * buf, size_t nbytes)
Definition at line 374 of file ps2sdkapi.c.
{
         // HACK: stdout and strerr to serial
         //if ((fd==1) || (fd==2))
         //      return sio_write((void *)buf, nbytes);
         return _ps2sdk_write(fd, buf, nbytes);
 }
References _ps2sdk_write.
access()
int access (const char * fn, int flags)
Definition at line 401 of file ps2sdkapi.c.
{
         struct stat s;
         if (stat(fn, &s))
                 return -1;
         if (s.st_mode & S_IFDIR)
                 return 0;
         if (flags & W_OK) {
                 if (s.st_mode & S_IWRITE)
                         return 0;
                 return -1;
         }
         return 0;
 }
References s.
chdir()
int chdir (const char * path)
Definition at line 461 of file ps2sdkapi.c.
{
     strcpy(__direct_pwd, path);
     return 0;
 }
References __direct_pwd.
closedir()
int closedir (DIR * dir)
Definition at line 430 of file ps2sdkapi.c.
 {
     return _ps2sdk_closedir(dir);
 }
References _ps2sdk_closedir.
compile_time_check()
void compile_time_check ()
Definition at line 212 of file ps2sdkapi.c.
{
         // Compiler (ABI n32)
         ct_assert(sizeof(unsigned char)==1);
         ct_assert(sizeof(unsigned short)==2);
         ct_assert(sizeof(unsigned int)==4);
         ct_assert(sizeof(unsigned long)==4);
         ct_assert(sizeof(unsigned long long)==8);
         ct_assert(sizeof(unsigned int __attribute__(( mode(TI) )))==16);
         ct_assert(sizeof(void *)==4);
         // Defined in tamtypes.h (ps2sdk)
         ct_assert(sizeof(u8)==1);
         ct_assert(sizeof(u16)==2);
         ct_assert(sizeof(u32)==4);
         ct_assert(sizeof(u64)==8);
         ct_assert(sizeof(u128)==16);
         // Defined in inttypes.h/stdint.h (newlib)
         ct_assert(sizeof(uint8_t)==1);
         ct_assert(sizeof(uint16_t)==2);
         ct_assert(sizeof(uint32_t)==4);
         ct_assert(sizeof(uint64_t)==8);
 }
References ct_assert, and mode.
fill_stat()
static void fill_stat (struct stat * stat, const io_stat_t * fiostat) static
Definition at line 80 of file ps2sdkapi.c.
 {
         stat->st_dev = 0;
         stat->st_ino = 0;
         stat->st_mode = io_to_posix_mode(fiostat->mode);
         stat->st_nlink = 0;
         stat->st_uid = 0;
         stat->st_gid = 0;
         stat->st_rdev = 0;
         stat->st_size = ((off_t)fiostat->hisize << 32) | (off_t)fiostat->size;
         stat->st_atime = io_to_posix_time(fiostat->atime);
         stat->st_mtime = io_to_posix_time(fiostat->mtime);
         stat->st_ctime = io_to_posix_time(fiostat->ctime);
         stat->st_blksize = 16*1024;
         stat->st_blocks = stat->st_size / 512;
 }
References io_stat_t::atime, io_stat_t::ctime, io_stat_t::hisize, io_to_posix_mode(), io_to_posix_time(), io_stat_t::mode, io_stat_t::mtime, and io_stat_t::size.
Referenced by fioGetstatHelper(), and fioReaddirHelper().
fioClosedirHelper()
static int fioClosedirHelper (DIR * dir) static
Definition at line 157 of file ps2sdkapi.c.
 {
         if(dir == NULL) {
                 //errno = EBADF;
                 return -1;
         }
         fioDclose(dir->dd_fd); // Check return value?
         free(dir->dd_buf);
         free(dir);
         return 0;
 }
References fioDclose(), and NULL.
fioGetstatHelper()
static int fioGetstatHelper (const char * path, struct stat * buf) static
Definition at line 97 of file ps2sdkapi.c.
{
         io_stat_t fiostat;
         if (fioGetstat(path, &fiostat) < 0) {
                 //errno = ENOENT;
                 return -1;
         }
         fill_stat(buf, &fiostat);
         return 0;
 }
References fill_stat(), and fioGetstat().
fioMkdirHelper()
int fioMkdirHelper (const char * path, int mode)
Definition at line 52 of file ps2sdkapi.c.
{
   // Old fio mkdir has no mode argument
   return fioMkdir(path);
 }
References fioMkdir().
fioOpendirHelper()
static DIR* fioOpendirHelper (const char * path) static
Definition at line 110 of file ps2sdkapi.c.
 {
         int dd;
         DIR *dir;
         dd = fioDopen(path);
         if (dd < 0) {
                 //errno = ENOENT;
                 return NULL;
         }
         dir = malloc(sizeof(DIR));
         dir->dd_fd = dd;
         dir->dd_buf = malloc(sizeof(struct dirent));
         return dir;
 }
References fioDopen(), and NULL.
fioReaddirHelper()
static struct dirent* fioReaddirHelper (DIR * dir) static
Definition at line 128 of file ps2sdkapi.c.
 {
         int rv;
         struct dirent *de;
         io_dirent_t fiode;
         if(dir == NULL) {
                 //errno = EBADF;
                 return NULL;
         }
         de = (struct dirent *)dir->dd_buf;
         rv = fioDread(dir->dd_fd, &fiode);
         if (rv <= 0) {
                 return NULL;
         }
         fill_stat(&de->d_stat, &fiode.stat);
         strncpy(de->d_name, fiode.name, 255);
         de->d_name[255] = 0;
         return de;
 }
References fill_stat(), fioDread(), io_dirent_t::name, NULL, and io_dirent_t::stat.
fioRename()
int fioRename (const char * old, const char * new)
Definition at line 48 of file ps2sdkapi.c.
{
   return -ENOSYS;
 }
References ENOSYS.
fioRewinddirHelper()
static void fioRewinddirHelper (DIR * dir) static
Definition at line 152 of file ps2sdkapi.c.
 {
         printf("rewinddir not implemented\n");
 }
getcwd()
char* getcwd (char * buf, size_t len)
Definition at line 482 of file ps2sdkapi.c.
{
         strncpy(buf, __direct_pwd, len);
         return buf;
 }
References __direct_pwd.
io_to_posix_mode()
static mode_t io_to_posix_mode (unsigned int ps2mode) static
Definition at line 69 of file ps2sdkapi.c.
 {
         mode_t posixmode = 0;
         if (ps2mode & FIO_SO_IFREG) posixmode |= S_IFREG;
         if (ps2mode & FIO_SO_IFDIR) posixmode |= S_IFDIR;
         if (ps2mode & FIO_SO_IROTH) posixmode |= S_IRUSR|S_IRGRP|S_IROTH;
         if (ps2mode & FIO_SO_IWOTH) posixmode |= S_IWUSR|S_IWGRP|S_IWOTH;
         if (ps2mode & FIO_SO_IXOTH) posixmode |= S_IXUSR|S_IXGRP|S_IXOTH;
         return posixmode;
 }
References FIO_SO_IFDIR, FIO_SO_IFREG, FIO_SO_IROTH, FIO_SO_IWOTH, and FIO_SO_IXOTH.
Referenced by fill_stat().
io_to_posix_time()
static time_t io_to_posix_time (const unsigned char * ps2time) static
Definition at line 57 of file ps2sdkapi.c.
 {
         struct tm tim;
         tim.tm_sec  = ps2time[1];
         tim.tm_min  = ps2time[2];
         tim.tm_hour = ps2time[3];
         tim.tm_mday = ps2time[4];
         tim.tm_mon  = ps2time[5] - 1;
         tim.tm_year = ((u16)ps2time[6] | ((u16)ps2time[7] << 8)) - 1900;
         return mktime(&tim);
 }
Referenced by fill_stat().
isCdromPath()
static int isCdromPath (const char * path) static
Definition at line 296 of file ps2sdkapi.c.
 {
         return !strncmp(path, "cdrom0:", 7) || !strncmp(path, "cdrom:", 6);
 }
Referenced by _open().
lseek64()
off64_t lseek64 (int fd, off64_t offset, int whence)
Definition at line 453 of file ps2sdkapi.c.
 {
     if (_ps2sdk_lseek64 == NULL)
         return EOVERFLOW;
     return _ps2sdk_lseek64(fd, offset, whence);
 }
References _ps2sdk_lseek64, EOVERFLOW, and NULL.
mkdir()
int mkdir (const char * path, mode_t mode)
Definition at line 466 of file ps2sdkapi.c.
{
     return _ps2sdk_mkdir(path, mode);
 }
References _ps2sdk_mkdir, and mode.
Referenced by CreateSave().
normalize_path()
static char* normalize_path (const char * path_name) static
Definition at line 237 of file ps2sdkapi.c.
 {
         int i, j;
         int first, next;
         static char out[255];
         /* First copy the path into our temp buffer */
         strcpy(out, path_name);
         /* Then append "/" to make the rest easier */
         strcat(out,"/");
         /* Convert "//" to "/" */
         for(i=0; out[i+1]; i++) {
                 if(out[i]=='/' && out[i+1]=='/') {
                         for(j=i+1; out[j]; j++)
                                         out[j] = out[j+1];
                         i--;
                 ;}
         }
         /* Convert "/./" to "/" */
         for(i=0; out[i] && out[i+1] && out[i+2]; i++) {
                 if(out[i]=='/' && out[i+1]=='.' && out[i+2]=='/') {
                         for(j=i+1; out[j]; j++)
                                         out[j] = out[j+2];
                         i--;
                 }
         }
         /* Convert "/path/../" to "/" until we can't anymore.  Also convert leading
          * "/../" to "/" */
         first = next = 0;
         while(1) {
                 /* If a "../" follows, remove it and the parent */
                 if(out[next+1] && out[next+1]=='.' &&
                         out[next+2] && out[next+2]=='.' &&
                         out[next+3] && out[next+3]=='/') {
                         for(j=0; out[first+j+1]; j++)
                                 out[first+j+1] = out[next+j+4];
                         first = next = 0;
                         continue;
                 }
                 /* Find next slash */
                 first = next;
                 for(next=first+1; out[next] && out[next] != '/'; next++)
                         continue;
                 if(!out[next]) break;
         }
         /* Remove trailing "/" */
         for(i=1; out[i]; i++)
                 continue;
         if(i >= 1 && out[i-1] == '/')
                 out[i-1] = 0;
         return (char*)out;
 }
Referenced by _open().
opendir()
DIR* opendir (const char * path)
Definition at line 415 of file ps2sdkapi.c.
 {
     return _ps2sdk_opendir(path);
 }
References _ps2sdk_opendir.
ps2_sbrk()
void* ps2_sbrk (size_t increment)
Definition at line 22 of file sbrk.c.
 {
         static void * _heap_ptr = &_end;
         void *mp, *ret = (void *)-1;
         if (increment == 0)
                 return _heap_ptr;
         /* If the area we want to allocated is past the end of our heap, we have a problem. */
         mp = _heap_ptr + increment;
         if (mp <= EndOfHeap()) {
                 ret = _heap_ptr;
                 _heap_ptr = mp;
         }
         return ret;
 }
References _end, and EndOfHeap().
Referenced by _sbrk().
random()
long int random (void)
Definition at line 557 of file ps2sdkapi.c.
 {
         return rand();
 }
readdir()
struct dirent* readdir (DIR * dir)
Definition at line 420 of file ps2sdkapi.c.
 {
     return _ps2sdk_readdir(dir);
 }
References _ps2sdk_readdir.
rewinddir()
void rewinddir (DIR * dir)
Definition at line 425 of file ps2sdkapi.c.
 {
     return _ps2sdk_rewinddir(dir);
 }
References _ps2sdk_rewinddir.
rmdir()
int rmdir (const char * path)
Definition at line 470 of file ps2sdkapi.c.
{
     return _ps2sdk_rmdir(path);
 }
References _ps2sdk_rmdir.
srandom()
void srandom (unsigned int seed)
Definition at line 562 of file ps2sdkapi.c.
 {
         srand(seed);
 }
time()
time_t time (time_t * t)
Definition at line 518 of file ps2sdkapi.c.
 {
         printf("ERROR: include libcdvd when using the time function\n");
         if(t != NULL)
                 *t = -1;
         return -1;
 }
References NULL.
Referenced by _gettimeofday().
Variable Documentation
__direct_pwd
char __direct_pwd[256] = ""
Definition at line 45 of file ps2sdkapi.c.
Referenced by _open(), chdir(), and getcwd().
_ps2sdk_close
int(* _ps2sdk_close) (int) (int) = fioClose
Inter-library helpers
Definition at line 171 of file ps2sdkapi.c.
Referenced by _close(), and fileXioInit().
_ps2sdk_closedir
int(* _ps2sdk_closedir) (DIR *dir) (DIR * dir) = fioClosedirHelper
Definition at line 188 of file ps2sdkapi.c.
Referenced by closedir(), and fileXioInit().
_ps2sdk_ioctl
int(* _ps2sdk_ioctl) (int, int, void *) (int , int , void *) = fioIoctl
Definition at line 177 of file ps2sdkapi.c.
Referenced by fileXioInit(), PS2KbdFlushBuffer(), PS2KbdResetKeymap(), PS2KbdSetAltmap(), PS2KbdSetBlockingMode(), PS2KbdSetCtrlmap(), PS2KbdSetKeymap(), PS2KbdSetLeds(), PS2KbdSetReadmode(), PS2KbdSetRepeatRate(), and PS2KbdSetSpecialmap().
_ps2sdk_lseek
int(* _ps2sdk_lseek) (int, int, int) (int , int , int) = fioLseek
Definition at line 174 of file ps2sdkapi.c.
Referenced by _lseek(), and fileXioInit().
_ps2sdk_lseek64
int64_t(* _ps2sdk_lseek64) (int, int64_t, int) (int , int64_t , int) = NULL
Definition at line 175 of file ps2sdkapi.c.
Referenced by fileXioInit(), and lseek64().
_ps2sdk_mkdir
int(* _ps2sdk_mkdir) (const char *, int) (const char * , int) = fioMkdirHelper
Definition at line 180 of file ps2sdkapi.c.
Referenced by fileXioInit(), and mkdir().
_ps2sdk_open
int(* _ps2sdk_open) (const char *, int,...) (const char * , int , ...) = (void *)fioOpen
Definition at line 172 of file ps2sdkapi.c.
Referenced by _open(), and fileXioInit().
_ps2sdk_opendir
DIR*(* _ps2sdk_opendir) (const char *path) (const char * path) = fioOpendirHelper
Definition at line 185 of file ps2sdkapi.c.
Referenced by fileXioInit(), and opendir().
_ps2sdk_read
int(* _ps2sdk_read) (int, void *, int) (int , void * , int) = fioRead
Definition at line 173 of file ps2sdkapi.c.
Referenced by _read(), and fileXioInit().
_ps2sdk_readdir
struct dirent*(* _ps2sdk_readdir) (DIR *dir) (DIR * dir) = fioReaddirHelper
Definition at line 185 of file ps2sdkapi.c.
Referenced by fileXioInit(), and readdir().
_ps2sdk_remove
int(* _ps2sdk_remove) (const char *) (const char *) = fioRemove
Definition at line 178 of file ps2sdkapi.c.
Referenced by _unlink(), and fileXioInit().
_ps2sdk_rename
int(* _ps2sdk_rename) (const char *, const char *) (const char * , const char *) = fioRename
Definition at line 179 of file ps2sdkapi.c.
Referenced by _link(), and fileXioInit().
_ps2sdk_rewinddir
void(* _ps2sdk_rewinddir) (DIR *dir) (DIR * dir) = fioRewinddirHelper
Definition at line 187 of file ps2sdkapi.c.
Referenced by fileXioInit(), and rewinddir().
_ps2sdk_rmdir
int(* _ps2sdk_rmdir) (const char *) (const char *) = fioRmdir
Definition at line 181 of file ps2sdkapi.c.
Referenced by fileXioInit(), and rmdir().
_ps2sdk_stat
int(* _ps2sdk_stat) (const char *path, struct stat *buf) (const char * path, struct stat * buf) = fioGetstatHelper
Definition at line 183 of file ps2sdkapi.c.
Referenced by _stat(), and fileXioInit().
_ps2sdk_write
int(* _ps2sdk_write) (int, const void *, int) (int , const void * , int) = fioWrite
Definition at line 176 of file ps2sdkapi.c.
Referenced by _write(), and fileXioInit().