ps2sdk: ee/rpc/ps2snd/src/ps2snd.c File Reference
ps2snd.c File Reference
#include <string.h>
#include <kernel.h>
#include <sifrpc.h>
#include <iopheap.h>
#include <stdio.h>
#include <ps2snd.h>
Functions
int sceSdInit (int flag)
void sceSdSetParam (u16 entry, u16 value)
u16 sceSdGetParam (u16 entry)
void sceSdSetSwitch (u16 entry, u32 value)
u32 sceSdGetSwitch (u16 entry)
void sceSdSetAddr (u16 entry, u32 value)
u32 sceSdGetAddr (u16 entry)
void sceSdSetCoreAttr (u16 entry, u16 value)
u16 sceSdGetCoreAttr (u16 entry)
u16 sceSdNote2Pitch (u16 center_note, u16 center_fine, u16 note, s16 fine)
u16 sceSdPitch2Note (u16 center_note, u16 center_fine, u16 pitch)
int sceSdProcBatch (sceSdBatch *batch, u32 returns[], u32 num)
int sceSdProcBatchEx (sceSdBatch *batch, u32 returns[], u32 num, u32 voice)
int sceSdVoiceTrans (s16 channel, u16 mode, u8 *m_addr, u32 *s_addr, u32 size)
int sceSdBlockTrans (s16 channel, u16 mode, u8 *m_addr, u32 size,...)
u32 sceSdVoiceTransStatus (s16 channel, s16 flag)
u32 sceSdBlockTransStatus (s16 channel, s16 flag)
int sceSdSetEffectAttr (int core, sceSdEffectAttr *attr)
void sceSdGetEffectAttr (int core, sceSdEffectAttr *attr)
int sceSdClearEffectWorkArea (int core, int channel, int effect_mode)
u32 sndQueryMaxFreeMemSize (void)
int sndStreamOpen (char *file, u32 voices, u32 flags, u32 bufaddr, u32 bufsize)
int sndStreamClose (void)
int sndStreamPlay (void)
int sndStreamPause (void)
int sndStreamSetPosition (int block)
int sndStreamSetVolume (int left, int right)
int sndStreamGetPosition (void)
int sndLoadSample (void *buf, u32 spuaddr, int size)
Variables
static SifRpcClientData_t sd_client
static int sd_started = 0
Function Documentation
sceSdBlockTrans()
int sceSdBlockTrans (s16 channel, u16 mode, u8 * m_addr, u32 size, ...)
Definition at line 152 of file ps2snd.c.
 {
         return(-1);
 }
sceSdBlockTransStatus()
u32 sceSdBlockTransStatus (s16 channel, s16 flag)
Definition at line 167 of file ps2snd.c.
 {
         s32 buf[2] ALIGNED(64);
         buf[0] = channel;
         buf[1] = flag;
         SifCallRpc(&sd_client, PS2SND_BlockTransStatus, 0, buf, 8, buf, 4, NULL, NULL);
         return(((u32 *)buf)[0]);
 }
References ALIGNED, NULL, PS2SND_BlockTransStatus, sd_client, and SifCallRpc().
sceSdClearEffectWorkArea()
int sceSdClearEffectWorkArea (int core, int channel, int effect_mode)
Definition at line 197 of file ps2snd.c.
 {
         s32 buf[3] ALIGNED(64);
         buf[0] = core;
         buf[1] = channel;
         buf[2] = effect_mode;
         SifCallRpc(&sd_client, PS2SND_ClearEffectWorkArea, 0, buf, 12, buf, 4, NULL, NULL);
         return(buf[0]);
 }
References ALIGNED, NULL, PS2SND_ClearEffectWorkArea, sd_client, and SifCallRpc().
sceSdGetAddr()
u32 sceSdGetAddr (u16 entry)
Definition at line 90 of file ps2snd.c.
 {
         u32 buf[1] ALIGNED(64);
         buf[0] = entry;
         SifCallRpc(&sd_client, PS2SND_GetAddr, 0, buf, 4, buf, 4, NULL, NULL);
         return(buf[0]);
 }
References ALIGNED, NULL, PS2SND_GetAddr, sd_client, and SifCallRpc().
sceSdGetCoreAttr()
u16 sceSdGetCoreAttr (u16 entry)
Definition at line 106 of file ps2snd.c.
 {
         u32 buf[1] ALIGNED(64);
         buf[0] = entry;
         SifCallRpc(&sd_client, PS2SND_GetCoreAttr, 0, buf, 4, buf, 4, NULL, NULL);
         return(buf[0]);
 }
References ALIGNED, NULL, PS2SND_GetCoreAttr, sd_client, and SifCallRpc().
sceSdGetEffectAttr()
void sceSdGetEffectAttr (int core, sceSdEffectAttr * attr)
Definition at line 189 of file ps2snd.c.
 {
         s32 buf[((sizeof(sceSdEffectAttr)+3)/4)] ALIGNED(64);
         buf[0] = core;
         SifCallRpc(&sd_client, PS2SND_GetEffectAttr, 0, buf, 4, buf, sizeof(sceSdEffectAttr), NULL, NULL);
         memcpy(attr, buf, sizeof(sceSdEffectAttr));
 }
References ALIGNED, NULL, PS2SND_GetEffectAttr, sd_client, and SifCallRpc().
sceSdGetParam()
u16 sceSdGetParam (u16 entry)
Definition at line 58 of file ps2snd.c.
 {
         u32 buf[1] ALIGNED(64);
         buf[0] = entry;
         SifCallRpc(&sd_client, PS2SND_GetParam, 0, buf, 4, buf, 4, NULL, NULL);
         return(buf[0]);
 }
References ALIGNED, NULL, PS2SND_GetParam, sd_client, and SifCallRpc().
sceSdGetSwitch()
u32 sceSdGetSwitch (u16 entry)
Definition at line 74 of file ps2snd.c.
 {
         u32 buf[1] ALIGNED(64);
         buf[0] = entry;
         SifCallRpc(&sd_client, PS2SND_GetSwitch, 0, buf, 4, buf, 4, NULL, NULL);
         return(buf[0]);
 }
References ALIGNED, NULL, PS2SND_GetSwitch, sd_client, and SifCallRpc().
sceSdInit()
int sceSdInit (int flag)
Definition at line 21 of file ps2snd.c.
 {
         s32 buf[1] ALIGNED(64);
         if (!sd_started)
         {
                 while(1)
                 {
                         if (SifBindRpc(&sd_client, BINDID_PS2SND, 0) < 0)
{
                                 printf("%s: Failed to bind to rpc '0x%08x'\n", __FUNCTION__, BINDID_PS2SND);
                                 return(-1);
                         }
                         if (sd_client.server != NULL)
                                 break;
                         nopdelay();
                 }
         }
         buf[0] = flag;
         SifCallRpc(&sd_client, PS2SND_Init, 0, buf, 4, buf, 4, NULL, NULL);
         return(buf[0]);
 }
References ALIGNED, BINDID_PS2SND, nopdelay(), NULL, PS2SND_Init, sd_client, sd_started, SifRpcClientData_t::server, SifBindRpc(), and SifCallRpc().
Referenced by main().
sceSdNote2Pitch()
u16 sceSdNote2Pitch (u16 center_note, u16 center_fine, u16 note, s16 fine)
Definition at line 114 of file ps2snd.c.
 {
         /* TODO: These functions were documented for the ps1 once... */
         return(0);
 }
sceSdPitch2Note()
u16 sceSdPitch2Note (u16 center_note, u16 center_fine, u16 pitch)
Definition at line 120 of file ps2snd.c.
 {
         /* TODO: These functions were documented for the ps1 once... */
         return(0);
 }
sceSdProcBatch()
int sceSdProcBatch (sceSdBatch * batch, u32 returns[], u32 num)
Definition at line 126 of file ps2snd.c.
 {
         /* TODO */
         return(-1);
 }
sceSdProcBatchEx()
int sceSdProcBatchEx (sceSdBatch * batch, u32 returns[], u32 num, u32 voice)
Definition at line 132 of file ps2snd.c.
 {
         /* TODO */
         return(-1);
 }
sceSdSetAddr()
void sceSdSetAddr (u16 entry, u32 value)
Definition at line 82 of file ps2snd.c.
 {
         u32 buf[2] ALIGNED(64);
         buf[0] = entry;
         buf[1] = value;
         SifCallRpc(&sd_client, PS2SND_SetAddr, 0, buf, 8, NULL, 0, NULL, NULL);
 }
References ALIGNED, NULL, PS2SND_SetAddr, sd_client, and SifCallRpc().
sceSdSetCoreAttr()
void sceSdSetCoreAttr (u16 entry, u16 value)
Definition at line 98 of file ps2snd.c.
 {
         u32 buf[2] ALIGNED(64);
         buf[0] = entry;
         buf[1] = value;
         SifCallRpc(&sd_client, PS2SND_SetCoreAttr, 0, buf, 8, NULL, 0, NULL, NULL);
 }
References ALIGNED, NULL, PS2SND_SetCoreAttr, sd_client, and SifCallRpc().
sceSdSetEffectAttr()
int sceSdSetEffectAttr (int core, sceSdEffectAttr * attr)
Definition at line 180 of file ps2snd.c.
 {
         s32 buf[1+((sizeof(sceSdEffectAttr)+3)/4)] ALIGNED(64);
         buf[0] = core;
         memcpy(&buf[1], attr, sizeof(sceSdEffectAttr));
         SifCallRpc(&sd_client, PS2SND_SetEffectAttr, 0, buf, 4+sizeof(sceSdEffectAttr), buf, 4, NULL, NULL);
         return(buf[0]);
 }
References ALIGNED, NULL, PS2SND_SetEffectAttr, sd_client, and SifCallRpc().
sceSdSetParam()
void sceSdSetParam (u16 entry, u16 value)
Definition at line 50 of file ps2snd.c.
 {
         u32 buf[2] ALIGNED(64);
         buf[0] = entry;
         buf[1] = value;
         SifCallRpc(&sd_client, PS2SND_SetParam, 0, buf, 8, NULL, 0, NULL, NULL);
 }
References ALIGNED, NULL, PS2SND_SetParam, sd_client, and SifCallRpc().
Referenced by main().
sceSdSetSwitch()
void sceSdSetSwitch (u16 entry, u32 value)
Definition at line 66 of file ps2snd.c.
 {
         u32 buf[2] ALIGNED(64);
         buf[0] = entry;
         buf[1] = value;
         SifCallRpc(&sd_client, PS2SND_SetSwitch, 0, buf, 8, NULL, 0, NULL, NULL);
 }
References ALIGNED, NULL, PS2SND_SetSwitch, sd_client, and SifCallRpc().
sceSdVoiceTrans()
int sceSdVoiceTrans (s16 channel, u16 mode, u8 * m_addr, u32 * s_addr, u32 size)
Definition at line 139 of file ps2snd.c.
 {
         u32 buf[5] ALIGNED(64);
         ((s32 *)buf)[0] = channel;
         buf[1] = mode;
         buf[2] = (u32)m_addr;
         buf[3] = (u32)s_addr;
         buf[4] = size;
         SifCallRpc(&sd_client, PS2SND_VoiceTrans, 0, buf, 20, buf, 4, NULL, NULL);
         return(((s32 *)buf)[0]);
 }
References ALIGNED, mode, NULL, PS2SND_VoiceTrans, sd_client, and SifCallRpc().
Referenced by sndLoadSample().
sceSdVoiceTransStatus()
u32 sceSdVoiceTransStatus (s16 channel, s16 flag)
Definition at line 157 of file ps2snd.c.
 {
         s32 buf[2] ALIGNED(64);
         buf[0] = channel;
         buf[1] = flag;
         SifCallRpc(&sd_client, PS2SND_VoiceTransStatus, 0, buf, 8, buf, 4, NULL, NULL);
         return(((u32 *)buf)[0]);
 }
References ALIGNED, NULL, PS2SND_VoiceTransStatus, sd_client, and SifCallRpc().
Referenced by sndLoadSample().
sndLoadSample()
int sndLoadSample (void * buf, u32 spuaddr, int size)
Definition at line 276 of file ps2snd.c.
 {
         void *iopbuf;
         int id, iopfree;
         SifDmaTransfer_t sifdma;
         iopfree = sndQueryMaxFreeMemSize()/2;
         if (size>iopfree)
         {
                 return(-1);
         }
         iopbuf = SifAllocIopHeap(size);
         if (iopbuf==0)
                 return(-1);
         FlushCache(0);
         sifdma.src  = buf;
         sifdma.dest = iopbuf;
         sifdma.size = size;
         sifdma.attr = 0;
         id = SifSetDma(&sifdma, 1);
         while(SifDmaStat(id) >= 0);;
         FlushCache(0);
         sceSdVoiceTrans(0, SD_TRANS_WRITE, iopbuf, (void*)spuaddr, size);
         sceSdVoiceTransStatus(0, 1);
         SifFreeIopHeap(iopbuf);
         return(size);
 }
References SifDmaTransfer_t::attr, SifDmaTransfer_t::dest, FlushCache(), sceSdVoiceTrans(), sceSdVoiceTransStatus(), SD_TRANS_WRITE, SifAllocIopHeap(), SifDmaStat(), SifFreeIopHeap(), SifSetDma(), SifDmaTransfer_t::size, sndQueryMaxFreeMemSize(), and SifDmaTransfer_t::src.
sndQueryMaxFreeMemSize()
u32 sndQueryMaxFreeMemSize (void)
Definition at line 208 of file ps2snd.c.
 {
         u32 buf[1] ALIGNED(64);
         SifCallRpc(&sd_client, PS2SND_QueryMaxFreeMemSize, 0, NULL, 0, buf, 4, NULL, NULL);
         return(buf[0]);
 }
References ALIGNED, NULL, PS2SND_QueryMaxFreeMemSize, sd_client, and SifCallRpc().
Referenced by sndLoadSample().
sndStreamClose()
int sndStreamClose (void)
Definition at line 230 of file ps2snd.c.
 {
         s32 buf[1] ALIGNED(64);
         SifCallRpc(&sd_client, PS2SND_StreamClose, 0, NULL, 0, buf, 4, NULL, NULL);
         return(buf[0]);
 }
References ALIGNED, NULL, PS2SND_StreamClose, sd_client, and SifCallRpc().
sndStreamGetPosition()
int sndStreamGetPosition (void)
Definition at line 269 of file ps2snd.c.
 {
         s32 buf[1] ALIGNED(64);
         SifCallRpc(&sd_client, PS2SND_StreamGetPosition, 0, NULL, 0, buf, 4, NULL, NULL);
         return(buf[0]);
 }
References ALIGNED, NULL, PS2SND_StreamGetPosition, sd_client, and SifCallRpc().
sndStreamOpen()
int sndStreamOpen (char * file, u32 voices, u32 flags, u32 bufaddr, u32 bufsize)
Definition at line 215 of file ps2snd.c.
 {
         u32 buf[32] ALIGNED(64);
         buf[0] = voices;
         buf[1] = flags;
         buf[2] = bufaddr;
         buf[3] = bufsize;
         strncpy((char*)&buf[4], file, 27*4);
         buf[31] = 0;
         SifCallRpc(&sd_client, PS2SND_StreamOpen, 0, buf, 128, buf, 4, NULL, NULL);
         return(((s32 *)buf)[0]);
 }
References ALIGNED, NULL, PS2SND_StreamOpen, sd_client, and SifCallRpc().
Referenced by main().
sndStreamPause()
int sndStreamPause (void)
Definition at line 245 of file ps2snd.c.
 {
         s32 buf[1] ALIGNED(64);
         SifCallRpc(&sd_client, PS2SND_StreamPause, 0, NULL, 0, buf, 4, NULL, NULL);
         return(buf[0]);
 }
References ALIGNED, NULL, PS2SND_StreamPause, sd_client, and SifCallRpc().
sndStreamPlay()
int sndStreamPlay (void)
Definition at line 237 of file ps2snd.c.
 {
         s32 buf[1] ALIGNED(64);
         SifCallRpc(&sd_client, PS2SND_StreamPlay, 0, NULL, 0, buf, 4, NULL, NULL);
         return(buf[0]);
 }
References ALIGNED, NULL, PS2SND_StreamPlay, sd_client, and SifCallRpc().
Referenced by main().
sndStreamSetPosition()
int sndStreamSetPosition (int block)
Definition at line 252 of file ps2snd.c.
 {
         s32 buf[1] ALIGNED(64);
         buf[0] = block;
         SifCallRpc(&sd_client, PS2SND_StreamSetPosition, 0, buf, 4, buf, 4, NULL, NULL);
         return(buf[0]);
 }
References ALIGNED, NULL, PS2SND_StreamSetPosition, sd_client, and SifCallRpc().
sndStreamSetVolume()
int sndStreamSetVolume (int left, int right)
Definition at line 260 of file ps2snd.c.
 {
         s32 buf[2] ALIGNED(64);
         buf[0] = left;
         buf[1] = right;
         SifCallRpc(&sd_client, PS2SND_StreamSetVolume, 0, buf, 8, buf, 4, NULL, NULL);
         return(buf[0]);
 }
References ALIGNED, NULL, PS2SND_StreamSetVolume, sd_client, and SifCallRpc().
Variable Documentation
sd_client
SifRpcClientData_t sd_client static
Definition at line 18 of file ps2snd.c.
Referenced by sceSdBlockTransStatus(), sceSdClearEffectWorkArea(), sceSdGetAddr(), sceSdGetCoreAttr(), sceSdGetEffectAttr(), sceSdGetParam(), sceSdGetSwitch(), sceSdInit(), sceSdSetAddr(), sceSdSetCoreAttr(), sceSdSetEffectAttr(), sceSdSetParam(), sceSdSetSwitch(), sceSdVoiceTrans(), sceSdVoiceTransStatus(), sndQueryMaxFreeMemSize(), sndStreamClose(), sndStreamGetPosition(), sndStreamOpen(), sndStreamPause(), sndStreamPlay(), sndStreamSetPosition(), and sndStreamSetVolume().
sd_started
int sd_started = 0 static
Definition at line 19 of file ps2snd.c.
Referenced by sceSdInit().