ps2sdk: ee/erl/src/recycle.c File Reference
recycle.c File Reference
#include <string.h>
#include <malloc.h>
#include "standard.h"
#include "recycle.h"
Functions
reroot * remkroot (size_t size)
void refree (struct reroot *r)
char * renewx (struct reroot *r)
char * remalloc (size_t len)
Function Documentation
refree()
void refree (struct reroot * r)
Definition at line 38 of file recycle.c.
 {
    recycle *temp;
    if ((temp = r->list)) while (r->list)
    {
       temp = r->list->next;
       free((char *)r->list);
       r->list = temp;
    }
    free((char *)r);
    return;
 }
References reroot::list, and recycle::next.
remalloc()
char* remalloc (size_t len)
Definition at line 76 of file recycle.c.
 {
   char *x = (char *)malloc(len);
   if (!x)
   {
     //exit(SUCCESS);  // let's just bug silently...
   }
   return x;
 }
References x.
Referenced by remkroot(), and renewx().
remkroot()
reroot* remkroot (size_t size)
Definition at line 26 of file recycle.c.
 {
    reroot *r = (reroot *)remalloc(sizeof(reroot));
    r->list = (recycle *)0;
    r->trash = (recycle *)0;
    r->size = align(size);
    r->logsize = RESTART;
    r->numleft = 0;
    return r;
 }
References align, reroot::list, reroot::logsize, reroot::numleft, remalloc(), RESTART, reroot::size, and reroot::trash.
renewx()
char* renewx (struct reroot * r)
Definition at line 53 of file recycle.c.
 {
    recycle *temp;
    if (r->trash)
    {  /* pull a node off the trash heap */
       temp = r->trash;
       r->trash = temp->next;
       (void)memset((void *)temp, 0, r->size);
    }
    else
    {  /* allocate a new block of nodes */
       r->numleft = r->size*((ub4)1<<r->logsize);
       if (r->numleft < REMAX) ++r->logsize;
       temp = (recycle *)remalloc(sizeof(recycle) + r->numleft);
       temp->next = r->list;
       r->list = temp;
       r->numleft-=r->size;
       temp = (recycle *)((char *)(r->list+1)+r->numleft);
    }
    return (char *)temp;
 }
References reroot::list, reroot::logsize, recycle::next, reroot::numleft, remalloc(), REMAX, reroot::size, and reroot::trash.