ps2sdk: ee/network/netman/src/include/rpc_server.h File Reference
rpc_server.h File Reference
Functions
int NetManInitRPCServer (void)
void NetManDeinitRPCServer (void)
int NetManRPCAllocRxBuffers (void)
Function Documentation
NetManDeinitRPCServer()
void NetManDeinitRPCServer (void)
Definition at line 236 of file rpc_server.c.
 {
         if(IsInitialized)
         {
                 SifRemoveRpc(&cb_srv, &cb_queue);
                 SifRemoveRpcQueue(&cb_queue);
                 RemoveDmacHandler(DMAC_SIF0, SifHandlerID);
                 if(NETMAN_RpcSvr_threadID>=0)
                 {
                         TerminateThread(NETMAN_RpcSvr_threadID);
                         DeleteThread(NETMAN_RpcSvr_threadID);
                         NETMAN_RpcSvr_threadID = -1;
                 }
                 if(NETMAN_Rx_threadID>=0)
                 {
                         TerminateThread(NETMAN_Rx_threadID);
                         DeleteThread(NETMAN_Rx_threadID);
                         NETMAN_Rx_threadID = -1;
                 }
                 IsInitialized=0;
         }
 }
References cb_queue, cb_srv, DeleteThread(), DMAC_SIF0, IsInitialized, NETMAN_RpcSvr_threadID, NETMAN_Rx_threadID, RemoveDmacHandler(), SifHandlerID, SifRemoveRpc(), SifRemoveRpcQueue(), and TerminateThread().
Referenced by NetManDeinit().
NetManInitRPCServer()
int NetManInitRPCServer (void)
Definition at line 209 of file rpc_server.c.
 {
         int result;
         ee_thread_t ThreadData;
         if(!IsInitialized)
         {
                 ThreadData.func=&NETMAN_RPC_Thread;
                 ThreadData.stack=NETMAN_RpcSvr_ThreadStack;
                 ThreadData.stack_size=sizeof(NETMAN_RpcSvr_ThreadStack);
                 ThreadData.gp_reg=&_gp;
                 ThreadData.initial_priority=0x57;       /* The RPC server thread should be given a higher priority than the protocol stack, so that it can issue commants to the EE and return. */
                 ThreadData.attr=ThreadData.option=0;
                 if((NETMAN_RpcSvr_threadID=CreateThread(&ThreadData))>=0)
                 {
                         StartThread(NETMAN_RpcSvr_threadID, NULL);
                         IsInitialized=1;
                         result=0;
                 }
                 else result=NETMAN_RpcSvr_threadID;
         }
         else result=0;
         return result;
 }
References _gp, ee_thread_t::attr, CreateThread(), ee_thread_t::func, ee_thread_t::gp_reg, ee_thread_t::initial_priority, IsInitialized, NETMAN_RPC_Thread(), NETMAN_RpcSvr_threadID, NETMAN_RpcSvr_ThreadStack, NULL, ee_thread_t::option, result, ee_thread_t::stack, ee_thread_t::stack_size, and StartThread().
Referenced by NetManInit().
NetManRPCAllocRxBuffers()
int NetManRPCAllocRxBuffers (void)
Definition at line 65 of file rpc_server.c.
 {
         int i;
         void *packet, *payload;
         for(i = 0; i < NETMAN_RPC_BLOCK_SIZE; i++)
         {
                 if((packet = NetManNetProtStackAllocRxPacket(NETMAN_NETIF_FRAME_SIZE, &payload)) != NULL)
                 {
                         ClearBufferLen(i, packet, payload);
                 } else {
                         printf("NETMAN: error - unable to allocate Rx FIFO buffers.\n");
                         return -ENOMEM;
                 }
         }
         return 0;
 }
References ClearBufferLen(), ENOMEM, NETMAN_NETIF_FRAME_SIZE, NETMAN_RPC_BLOCK_SIZE, NetManNetProtStackAllocRxPacket(), NULL, packet, and NetManBD::payload.
Referenced by NetManRegisterNetworkStack().