ps2sdk: ee/network/netman/src/include/rpc_client.h File Reference
rpc_client.h File Reference
Functions
int NetManInitRPCClient (void)
void NetManDeinitRPCClient (void)
int NetManRPCRegisterNetworkStack (void)
int NetManRPCUnregisterNetworkStack (void)
int NetManRpcIoctl (unsigned int command, void *arg, unsigned int arg_len, void *output, unsigned int length)
void NetManRpcNetIFXmit (void)
Function Documentation
NetManDeinitRPCClient()
void NetManDeinitRPCClient (void)
Definition at line 160 of file rpc_client.c.
 {
         if(IsInitialized)
         {
                 WaitSema(NetManIOSemaID);
                 SifCallRpc(&NETMAN_rpc_cd, NETMAN_IOP_RPC_FUNC_DEINIT, 0, NULL, 0, NULL, 0, NULL, NULL);
                 deinitCleanup();
                 IsInitialized=0;
         }
 }
References deinitCleanup(), IsInitialized, NETMAN_IOP_RPC_FUNC_DEINIT, NETMAN_rpc_cd, NetManIOSemaID, NULL, SifCallRpc(), and WaitSema().
Referenced by NetManDeinit().
NetManInitRPCClient()
int NetManInitRPCClient (void)
Definition at line 57 of file rpc_client.c.
{
         static const char NetManID[]="NetMan";
         int result;
         ee_sema_t SemaData;
         ee_thread_t thread;
         if(!IsInitialized)
         {
                 SemaData.max_count=1;
                 SemaData.init_count=1;
                 SemaData.option=(u32)NetManID;
                 SemaData.attr=0;
                 if((NetManIOSemaID=CreateSema(&SemaData)) < 0)
                 {
                         deinitCleanup();
                         return NetManIOSemaID;
                 }
                 thread.func=&NETMAN_TxThread;
                 thread.stack=NETMAN_Tx_ThreadStack;
                 thread.stack_size=sizeof(NETMAN_Tx_ThreadStack);
                 thread.gp_reg=&_gp;
                 thread.initial_priority=0x56;   /* Should be given a higher priority than the protocol stack, so that it can dump frames in the EE and return. */
                 thread.attr=thread.option=0;
                 if((NETMAN_Tx_threadID=CreateThread(&thread)) >= 0)
                 {
                         IsProcessingTx = 0;
                         StartThread(NETMAN_Tx_threadID, NULL);
                 } else {
                         deinitCleanup();
                         return NETMAN_Tx_threadID;
                 }
                 while((SifBindRpc(&NETMAN_rpc_cd, NETMAN_RPC_NUMBER, 0)<0)||(NETMAN_rpc_cd.server==NULL))
                         nopdelay();
                 if((result=SifCallRpc(&NETMAN_rpc_cd, NETMAN_IOP_RPC_FUNC_INIT, 0, NULL, 0, &ReceiveBuffer, sizeof(s32), NULL, NULL))>=0)
                 {
                         if((result=ReceiveBuffer.result) == 0)
                                 IsInitialized=1;
                         else
                                 deinitCleanup();
                 }else{
                         deinitCleanup();
                 }
         }
         else result=0;
         return result;
 }
References _gp, ee_sema_t::attr, ee_thread_t::attr, CreateSema(), CreateThread(), deinitCleanup(), ee_thread_t::func, ee_thread_t::gp_reg, ee_sema_t::init_count, ee_thread_t::initial_priority, IsInitialized, IsProcessingTx, ee_sema_t::max_count, NETMAN_IOP_RPC_FUNC_INIT, NETMAN_rpc_cd, NETMAN_RPC_NUMBER, NETMAN_Tx_threadID, NETMAN_Tx_ThreadStack, NETMAN_TxThread(), NetManIOSemaID, nopdelay(), NULL, ee_sema_t::option, ee_thread_t::option, ReceiveBuffer, result, SifRpcClientData_t::server, SifBindRpc(), SifCallRpc(), ee_thread_t::stack, ee_thread_t::stack_size, and StartThread().
Referenced by NetManInit().
NetManRpcIoctl()
int NetManRpcIoctl (unsigned int command, void * arg, unsigned int arg_len, void * output, unsigned int length)
Definition at line 173 of file rpc_client.c.
 {
         int result;
         struct NetManIoctl *IoctlArgs=&TransmitBuffer.IoctlArgs;
         WaitSema(NetManIOSemaID);
         IoctlArgs->command=command;
         memcpy(IoctlArgs->args, args, args_len);
         IoctlArgs->args_len=args_len;
         IoctlArgs->output=output;
         IoctlArgs->length=length;
         if((result=SifCallRpc(&NETMAN_rpc_cd, NETMAN_IOP_RPC_FUNC_IOCTL, 0, &TransmitBuffer, sizeof(struct NetManIoctl), &ReceiveBuffer, sizeof(struct NetManIoctlResult), NULL, NULL))>=0)
         {
                 result=ReceiveBuffer.IoctlResult.result;
                 memcpy(output, ReceiveBuffer.IoctlResult.output, length);
         }
         SignalSema(NetManIOSemaID);
         return result;
 }
References NetManIoctl::args, NetManIoctl::args_len, NetManIoctl::command, command, IoctlArgs, NetManIoctl::length, NETMAN_IOP_RPC_FUNC_IOCTL, NETMAN_rpc_cd, NetManIOSemaID, NULL, NetManIoctl::output, ReceiveBuffer, result, SifCallRpc(), SignalSema(), TransmitBuffer, and WaitSema().
Referenced by NetManIoctl().
NetManRpcNetIFXmit()
void NetManRpcNetIFXmit (void)
Definition at line 284 of file rpc_client.c.
 {
         if(!IsProcessingTx)
                 WakeupThread(NETMAN_Tx_threadID);
 }
References IsProcessingTx, NETMAN_Tx_threadID, and WakeupThread().
Referenced by NetManNetIFXmit().
NetManRPCRegisterNetworkStack()
int NetManRPCRegisterNetworkStack (void)
Definition at line 109 of file rpc_client.c.
 {
         int result;
         WaitSema(NetManIOSemaID);
         if(FrameBufferStatus == NULL) FrameBufferStatus = memalign(64, NETMAN_RPC_BLOCK_SIZE * sizeof(struct NetManBD));
         if(FrameBufferStatus != NULL)
         {
                 memset(UNCACHED_SEG(FrameBufferStatus), 0, NETMAN_RPC_BLOCK_SIZE * sizeof(struct NetManBD));
                 TransmitBuffer.NetStack.FrameBufferStatus = FrameBufferStatus;
                 IOPFrameBufferWrPtr = 0;
                 if((result=SifCallRpc(&NETMAN_rpc_cd, NETMAN_IOP_RPC_FUNC_REG_NETWORK_STACK, 0, &TransmitBuffer, sizeof(struct NetManRegNetworkStack), &ReceiveBuffer, sizeof(struct NetManRegNetworkStackResult), NULL, NULL))>=0)
                 {
                         if((result=ReceiveBuffer.NetStackResult.result) == 0)
{
                                 IOPFrameBuffer = ReceiveBuffer.NetStackResult.FrameBuffer;
                                 IOPFrameBufferStatus = ReceiveBuffer.NetStackResult.FrameBufferStatus;
                         }
                 }
         }
         else
         {
                 result = -ENOMEM;
         }
         SignalSema(NetManIOSemaID);
         return result;
 }
References ENOMEM, FrameBufferStatus, IOPFrameBuffer, IOPFrameBufferStatus, IOPFrameBufferWrPtr, NETMAN_IOP_RPC_FUNC_REG_NETWORK_STACK, NETMAN_RPC_BLOCK_SIZE, NETMAN_rpc_cd, NetManIOSemaID, NULL, ReceiveBuffer, result, SifCallRpc(), SignalSema(), TransmitBuffer, UNCACHED_SEG, and WaitSema().
Referenced by NetManRegisterNetworkStack().
NetManRPCUnregisterNetworkStack()
int NetManRPCUnregisterNetworkStack (void)
Definition at line 142 of file rpc_client.c.
 {
         int result;
         WaitSema(NetManIOSemaID);
         result=SifCallRpc(&NETMAN_rpc_cd, NETMAN_IOP_RPC_FUNC_UNREG_NETWORK_STACK, 0, NULL, 0, NULL, 0, NULL, NULL);
         IOPFrameBuffer = NULL;
         IOPFrameBufferWrPtr = 0;
         free(FrameBufferStatus);
         FrameBufferStatus = NULL;
         SignalSema(NetManIOSemaID);
         return result;
 }
References FrameBufferStatus, IOPFrameBuffer, IOPFrameBufferWrPtr, NETMAN_IOP_RPC_FUNC_UNREG_NETWORK_STACK, NETMAN_rpc_cd, NetManIOSemaID, NULL, result, SifCallRpc(), SignalSema(), and WaitSema().
Referenced by NetManUnregisterNetworkStack().