ps2sdk: ee/debug/src/scr_printf.c File Reference
scr_printf.c File Reference
#include <stdio.h>
#include <tamtypes.h>
#include <sifcmd.h>
#include <kernel.h>
#include <osd_config.h>
#include <stdarg.h>
#include <debug.h>
Data Structures
struct t_setupscr
struct t_setupchar
Functions
static int debug_detect_signal ()
static void Init_GS (int interlace, int omode, int ffmd)
static void SetVideoMode (void)
static void Dma02Wait (void)
static void DmaReset (void)
static void progdma (void *addr, int size)
void scr_setbgcolor (u32 color)
void init_scr (void)
void scr_putchar (int x, int y, u32 color, int ch)
static void clear_line (int Y)
void scr_printf (const char *format,...)
void scr_setXY (int x, int y)
int scr_getX ()
int scr_getY ()
void scr_clear ()
Variables
static short int X = 0
static short int Y = 0
static short int MX =80
static short int MY =40
static u32 bgcolor = 0
u8 msx []
Detailed Description
EE UGLY DEBUG ON SCREEN
Definition in file scr_printf.c.
Function Documentation
clear_line()
static void clear_line (int Y) static
Definition at line 245 of file scr_printf.c.
 {
    int i;
    for (i=0; i < MX; i++)
     scr_putchar( i*8 , Y * 8, bgcolor, ' ');
 }
References bgcolor, MX, scr_putchar(), and Y.
Referenced by scr_clear(), and scr_printf().
debug_detect_signal()
static int debug_detect_signal () static
Definition at line 48 of file scr_printf.c.
 {
    char romname[14];
    GetRomName(romname);
    return((romname[4] == 'E') ? 1 : 0);
 }
References GetRomName().
Referenced by init_scr().
Dma02Wait()
static void Dma02Wait (void) inline static
Definition at line 103 of file scr_printf.c.
 {
   unsigned dma_addr;
   unsigned status;
   asm volatile ("        .set push               \n"
                 "        .set noreorder          \n"
                 "        lui   %0, 0x1001        \n"
                 "        lw    %1, -0x6000(%0)   \n"
                 "1:      andi  %1, %1, 0x100     \n" // Wait until STR bit of D2_CHCR = 0
                 "        nop                     \n"
                 "        nop                     \n"
                 "        nop                     \n"
                 "        nop                     \n"
                 "        bnel  %1, $0, 1b        \n"
                 "        lw    %1, -0x6000(%0)   \n"
                 "        .set pop                \n"
                 : "=&r" (dma_addr), "=&r" (status) );
 }
Referenced by init_scr(), and scr_putchar().
DmaReset()
static void DmaReset (void) static
Definition at line 123 of file scr_printf.c.
 {
   unsigned dma_addr;
   unsigned temp, temp2;
   // This appears to have been based on code from Sony that initializes DMA channels 0-9, in bulk.
   asm volatile ("        .set push               \n"
                 "        .set noreorder          \n"
                 "        lui   %0, 0x1001        \n"
                 "        sw    $0, -0x5f80(%0)   \n" // D2_SADR = 0. Documented to not exist, but is done.
                 "        sw    $0, -0x6000(%0)   \n" // D2_CHCR = 0
                 "        sw    $0, -0x5fd0(%0)   \n" // D2_TADR = 0
                 "        sw    $0, -0x5ff0(%0)   \n" // D2_MADR = 0
                 "        sw    $0, -0x5fb0(%0)   \n" // D2_ASR1 = 0
                 "        sw    $0, -0x5fc0(%0)   \n" // D2_ASR0 = 0
                 "        lui   %1, 0             \n"
                 "        ori   %1, %1, 0xff1f    \n"
                 "        sw    %1, -0x1ff0(%0)   \n" // Clear all interrupt status under D_STAT, other than SIF0, SIF1 & SIF2.
                 "        lw    %1, -0x1ff0(%0)   \n"
                 "        lui   %2, 0xff1f        \n"
                 "        and   %1, %1, %2        \n" // Clear all interrupt masks under D_STAT, other SIF0, SIF1 & SIF2. Writing a 1 reverses the bit.
                 "        sw    %1, -0x1ff0(%0)   \n"
                 "        sw    $0, -0x2000(%0)   \n" // D_CTRL = 0
                 "        sw    $0, -0x1fe0(%0)   \n" // D_PCR = 0
                 "        sw    $0, -0x1fd0(%0)   \n" // D_SQWC = 0
                 "        sw    $0, -0x1fb0(%0)   \n" // D_RBOR = 0
                 "        sw    $0, -0x1fc0(%0)   \n" // D_RBSR = 0
                 "        lw    %1, -0x2000(%0)   \n"
                 "        ori   %1, %1, 1         \n" // D_CTRL (DMAE 1)
                 "        sw    %1, -0x2000(%0)   \n"
                 "        .set pop                \n"
                 : "=&r" (dma_addr), "=&r" (temp), "=&r" (temp2) );
 }
Referenced by init_scr().
Init_GS()
static void Init_GS (int interlace, int omode, int ffmd) static
Definition at line 55 of file scr_printf.c.
 {
    // Reset GS
    *(vu64 *)0x12001000 = 0x200;
    // Mask interrupts
    GsPutIMR(0xff00);
    // Configure GS CRT
    SetGsCrt(interlace, omode, ffmd);
 }
References GsPutIMR(), and SetGsCrt().
Referenced by init_scr().
init_scr()
void init_scr (void)
Definition at line 185 of file scr_printf.c.
 {
   static struct t_setupscr setupscr __attribute__ (( aligned (16) )) = {
         { 0x100000000000800E, 0xE, 0xA0000, 0x4C, 0x8C, 0x4E },          //GIFtag (REGS: A+D, NREG 1, FLG PACKED, EOP, NLOOP 14), FRAME_1 (PSM PSMCT32, FBW 10, FBP 0), ZBUF_1 (PSM PSMZ32, ZBP 140)
         { 27648, 30976 }, { 0x18 },                                      //XYOFFSET_1 (OFX 1728.0, OFY 1936.0)
         { 0, 639, 0, 223 },                                              //SCISSOR_1 (SCAX0 0, SCAX1 639, SCAY0 0, SCAY1 223)
         { 0x40, 1, 0x1a, 1, 0x46, 0, 0x45, 0x70000,                      //PRMODECONT (AC PRIM), COLCLAMP (CLAMP 1), DTHE (DTHE 0)
         0x47, 0x30000, 0x47, 6, 0, 0x3F80000000000000, 1, 0x79006C00, 5, //TEST_1 (ZTST GREATER, ZTE 1), TEST_1 (ZTST ALWAYS, ZTE 1), PMODE (CRTMD 1, EN2 1), RGBAQ (Q 1.0, A 0, B 0, G 0, R 0), XYZ2 (Z 0.0, Y 1728.0, X 1936.0)
         0x87009400, 5, 0x70000, 0x47 }                                   //XYZ2 (Z 0, Y 2160.0, X 2368.0), TEST_1 (ZTST GREATER, ZTE 1)
    };
    X = Y = 0;
    DmaReset();
    Init_GS( 1, debug_detect_signal() == 1 ? 3 : 2, 0); // Interlaced, NTSC/PAL and FIELD mode
    SetVideoMode();
    Dma02Wait();
    progdma( &setupscr, 15);
    Dma02Wait();
 }
References debug_detect_signal(), Dma02Wait(), DmaReset(), Init_GS(), progdma(), SetVideoMode(), X, and Y.
Referenced by main().
progdma()
static void progdma (void * addr, int size) inline static
Initiates a normal-mode DMA transfer over the GIF.
Parameters
addr The address of the data to be transfered, which must be 16 byte aligned.
size The size (in 16 byte quads) of the data to be transfered.
Definition at line 163 of file scr_printf.c.
 {
   unsigned dma_addr;
   unsigned temp;
   asm volatile ("        .set push               \n"
                 "        .set noreorder          \n"
                 "        lui   %0, 0x1001        \n"
                 "        sw    %3, -0x5fe0(%0)   \n" //D2_QWC
                 "        sw    %2, -0x5ff0(%0)   \n" //D2_MADR
                 "        li    %1, 0x101         \n" //STR 1, DIR 1
                 "        sw    %1, -0x6000(%0)   \n" //D2_CHCR
                 "        .set pop                \n"
                 : "=&r" (dma_addr), "=&r" (temp)
                 : "r" (addr), "r" (size) );
 }
Referenced by init_scr(), and scr_putchar().
scr_clear()
void scr_clear (void)
Definition at line 313 of file scr_printf.c.
 {
         int y;
         for(y=0;y<MY;y++)
                 clear_line(y);
         scr_setXY(0,0);
 }
References clear_line(), MY, scr_setXY(), and y.
Referenced by main().
scr_getX()
int scr_getX (void)
Definition at line 303 of file scr_printf.c.
 {
         return X;
 }
References X.
scr_getY()
int scr_getY (void)
Definition at line 308 of file scr_printf.c.
 {
         return Y;
 }
References Y.
Referenced by main().
scr_printf()
void scr_printf (const char * format, ...)
Definition at line 252 of file scr_printf.c.
 {
    va_list      opt;
    char         buff[2048], c;
    int          i, bufsz, j;
    va_start(opt, format);
    bufsz = vsnprintf(buff, sizeof(buff), format, opt);
    for (i = 0; i < bufsz; i++)
        {
        c = buff[i];
        switch (c)
           {
           case          '\n':
                              X = 0;
                              Y ++;
                              if (Y == MY)
                                  Y = 0;
                              clear_line(Y);
                              break;
           case      '\t':
                              for (j = 0; j < 5; j++) {
                                 scr_putchar( X*7 , Y * 8, 0xffffff, ' ');
                                 X++;
                              }
                              break;
           default:
                              scr_putchar( X*7 , Y * 8, 0xffffff, c);
                              X++;
                              if (X == MX)
{
                                 X = 0;
                                 Y++;
                                 if (Y == MY)
                                    Y = 0;
                                 clear_line(Y);
                                 }
           }
        }
     scr_putchar( X*7 , Y * 8, 0xffffff, 219);
     va_end(opt);
 }
References clear_line(), MX, MY, scr_putchar(), X, and Y.
Referenced by ethPrintIPConfig(), ethPrintLinkStatus(), and main().
scr_putchar()
void scr_putchar (int x, int y, u32 color, int ch)
Definition at line 210 of file scr_printf.c.
 {
    static struct t_setupchar setupchar __attribute__((aligned(16))) = {
         { 0x1000000000000004, 0xE, 0xA000000000000, 0x50 }, //GIFtag (REGS: A+D, NREG 1, FLG PACKED, NLOOP 4), BITBLTBUF (DPSM PSMCT32, DBW 10, DBP 0)
         { 0 }, 100, 100, { 0x51 },                          //TRXPOS (DSAX 100, DSAY 100)
         { 8, 8 },                                           //TRXREG (RRW 8, RRH 8)
         { 0x52, 0, 0x53, 0x800000000008010, 0}              //TRXDIR (XDIR Host -> Local), GIFtag (FLG IMAGE, EOP, NLOOP 16)
    };
    /* charmap must be aligned to a 16-bye boundary.  */
    static u32   charmap[64] __attribute__((aligned(16)));
    int  i, j, l;
    u8   *font;
    u32  pixel;
    ((struct t_setupchar*)UNCACHED_SEG(&setupchar))->x = x;
    ((struct t_setupchar*)UNCACHED_SEG(&setupchar))->y = y;
    progdma(&setupchar, 6);
    font = &msx[ ch * 8];
    for (i=l=0; i < 8; i++, l+= 8, font++)
    {
       for (j=0; j < 8; j++)
       {
           pixel = ((*font & (128 >> j))) ? color : bgcolor;
           *(u32*)UNCACHED_SEG(&charmap[ l + j]) = pixel;
       }
    }
    Dma02Wait();
    progdma(charmap, (8*8*4) / 16);
    Dma02Wait();
 }
References bgcolor, Dma02Wait(), msx, progdma(), UNCACHED_SEG, x, and y.
Referenced by clear_line(), and scr_printf().
scr_setbgcolor()
void scr_setbgcolor (u32 color)
Definition at line 180 of file scr_printf.c.
 {
   bgcolor = color;
 }
References bgcolor.
scr_setXY()
void scr_setXY (int x, int y)
Definition at line 297 of file scr_printf.c.
 {
         if( x<MX && x>=0 ) X=x;
         if( y<MY && y>=0 ) Y=y;
 }
References X, x, Y, and y.
Referenced by main(), and scr_clear().
SetVideoMode()
static void SetVideoMode (void) static
Definition at line 65 of file scr_printf.c.
 {
   unsigned dma_addr;
   unsigned val1;
   unsigned val2;
   unsigned val3;
   unsigned val4;
   unsigned val4_lo;
 /*      DISPLAY1        0x0983227c001bf9ff
                 DX = 0x27C (636)
                 DY = 0x032 (50)
                 MAGH = 0x03 (4x)
                 MAGV = 0x01 (2x)
                 DW = 0x9FF (2560)
                 DH = 0x1BF (447)        */
   asm volatile ("        .set push               \n"
                 "        .set noreorder          \n"
                 "        lui     %4, 0x001b      \n"
                 "        lui     %5, 0x0983      \n"
                 "        lui     %0, 0x1200      \n"
                 "        ori     %4, %4, 0xf9ff  \n"
                 "        ori     %5, %5, 0x227c  \n"
                 "        li      %1, 0xff62      \n"
                 "        dsll32  %4, %4, 0       \n"
                 "        li      %3, 0x1400      \n"
                 "        sd      %1, 0(%0)       \n"
                 "        or      %4, %4, %5      \n"
                 "        sd      %3, 0x90(%0)    \n"
                 "        sd      %4, 0xa0(%0)    \n"
                 "        .set pop                \n"
                 : "=&r" (dma_addr), "=&r" (val1), "=&r" (val2),
                 "=&r" (val3), "=&r" (val4), "=&r" (val4_lo) );
 }
Referenced by init_scr().
Variable Documentation
bgcolor
u32 bgcolor = 0 static
Definition at line 26 of file scr_printf.c.
Referenced by clear_line(), CreateSave(), scr_putchar(), and scr_setbgcolor().
msx
u8 msx[] extern
Definition at line 18 of file font.c.
Referenced by scr_putchar().
MX
short int MX =80 static
Definition at line 25 of file scr_printf.c.
Referenced by clear_line(), and scr_printf().
MY
short int MY =40 static
Definition at line 25 of file scr_printf.c.
Referenced by scr_clear(), and scr_printf().
X
short int X = 0 static
Definition at line 24 of file scr_printf.c.
Referenced by init_scr(), scr_getX(), scr_printf(), and scr_setXY().
Y
short int Y = 0 static
Definition at line 24 of file scr_printf.c.
Referenced by clear_line(), init_scr(), scr_getY(), scr_printf(), and scr_setXY().