ps2sdk: ee/kernel/include/sifrpc.h File Reference
sifrpc.h File Reference
#include <sifcmd.h>
Data Structures
struct SifRpcPktHeader_t
struct SifRpcRendPkt_t
struct SifRpcOtherDataPkt_t
struct SifRpcBindPkt_t
struct SifRpcCallPkt_t
struct SifRpcServerData_t
struct SifRpcHeader_t
struct SifRpcClientData_t
struct SifRpcReceiveData_t
struct SifRpcDataQueue_t
Macros
#define SIF_RPC_M_NOWAIT 0x01
#define SIF_RPC_M_NOWBDC 0x02
Typedefs
typedef void *(* SifRpcFunc_t) (int fno, void *buffer, int length)
typedef void(* SifRpcEndFunc_t) (void *end_param)
Functions
void SifInitRpc (int mode)
void SifExitRpc (void)
int SifBindRpc (SifRpcClientData_t *client, int rpc_number, int mode)
int SifCallRpc (SifRpcClientData_t *client, int rpc_number, int mode, void *send, int ssize, void *receive, int rsize, SifRpcEndFunc_t end_function, void *end_param)
int SifRpcGetOtherData (SifRpcReceiveData_t *rd, void *src, void *dest, int size, int mode)
int SifCheckStatRpc (SifRpcClientData_t *cd)
SifRpcDataQueue_t * SifSetRpcQueue (SifRpcDataQueue_t *q, int thread_id)
SifRpcDataQueue_t * SifRemoveRpcQueue (SifRpcDataQueue_t *qd)
SifRpcServerData_t * SifRegisterRpc (SifRpcServerData_t *srv, int sid, SifRpcFunc_t func, void *buff, SifRpcFunc_t cfunc, void *cbuff, SifRpcDataQueue_t *qd)
SifRpcServerData_t * SifRemoveRpc (SifRpcServerData_t *sd, SifRpcDataQueue_t *queue)
SifRpcServerData_t * SifGetNextRequest (SifRpcDataQueue_t *qd)
void SifExecRequest (SifRpcServerData_t *srv)
void SifRpcLoop (SifRpcDataQueue_t *q)
Detailed Description
EE SIF RPC commands prototypes
Definition in file sifrpc.h.
Macro Definition Documentation
SIF_RPC_M_NOWAIT
#define SIF_RPC_M_NOWAIT 0x01
Don't wait for end function
Definition at line 24 of file sifrpc.h.
SIF_RPC_M_NOWBDC
#define SIF_RPC_M_NOWBDC 0x02
Don't write back the D cache
Definition at line 26 of file sifrpc.h.
Typedef Documentation
SifRpcEndFunc_t
typedef void(* SifRpcEndFunc_t) (void *end_param)
Definition at line 33 of file sifrpc.h.
SifRpcFunc_t
typedef void*(* SifRpcFunc_t) (int fno, void *buffer, int length)
Definition at line 32 of file sifrpc.h.
Function Documentation
SifBindRpc()
int SifBindRpc (SifRpcClientData_t * client, int rpc_number, int mode)
Referenced by AHX_Init(), AHX_LoadSongBuffer(), AHX_Pause(), AHX_Play(), AHX_Quit(), AHX_SetBoost(), AHX_SetVolume(), AHX_SubSong(), AHX_ToggleOversampling(), audsrv_init(), fileXioInit(), mcInit(), mtapInit(), NetManInitRPCClient(), padInit(), poweroffInit(), PS2CamInit(), ps2ip_init(), PS2MouseInit(), RMMan_Init(), and sceSdInit().
SifCallRpc()
int SifCallRpc (SifRpcClientData_t * client, int rpc_number, int mode, void * send, int ssize, void * receive, int rsize, SifRpcEndFunc_t end_function, void * end_param)
Referenced by accept(), AHX_Init(), AHX_LoadSongBuffer(), AHX_Pause(), AHX_Play(), AHX_Quit(), AHX_SetBoost(), AHX_SetVolume(), AHX_SubSong(), AHX_ToggleOversampling(), audsrv_init(), audsrv_load_adpcm(), audsrv_play_audio(), audsrv_quit(), audsrv_set_format(), bind(), call_rpc_1(), call_rpc_2(), connect(), disconnect(), fileXioChdir(), fileXioChStat(), fileXioClose(), fileXioCopyfile(), fileXioDclose(), fileXioDevctl(), fileXioDopen(), fileXioDread(), fileXioFormat(), fileXioGetDeviceList(), fileXioGetdir(), fileXioGetStat(), fileXioIoctl(), fileXioIoctl2(), fileXioLseek(), fileXioLseek64(), fileXioMkdir(), fileXioMount(), fileXioOpen(), fileXioRead(), fileXioReadlink(), fileXioRemove(), fileXioRename(), fileXioRmdir(), fileXioSetRWBufferSize(), fileXioStop(), fileXioSymlink(), fileXioSync(), fileXioUmount(), fileXioWrite(), getpeername(), getsockname(), getsockopt(), ioctlsocket(), listen(), mcChangeThreadPriority(), mcChdir(), mcClose(), mcDelete(), mcFlush(), mcFormat(), mcGetDir(), mcGetEntSpace(), mcGetInfo(), mcInit(), mcOpen(), mcRead(), mcReadPage(), mcRename(), mcSeek(), mcSetFileInfo(), mcUnformat(), mcWrite(), mcWritePage(), mtapGetConnection(), mtapPortClose(), mtapPortOpen(), NetManDeinitRPCClient(), NetManInitRPCClient(), NetManQueryMainIF(), NetManRpcIoctl(), NetManRPCRegisterNetworkStack(), NetManRPCUnregisterNetworkStack(), NetManSetLinkMode(), NetManSetMainIF(), padEnd(), padGetButtonMask(), padGetModVersion(), padGetPortMax(), padGetSlotMax(), padInfoAct(), padInfoMode(), padPortClose(), padPortInit(), padPortOpen(), padSetActAlign(), padSetActDirect(), padSetButtonInfo(), padSetMainMode(), poweroffInit(), poweroffShutdown(), PS2CamCloseDevice(), PS2CamGetDeviceCount(), PS2CamGetDeviceInfo(), PS2CamGetDeviceStatus(), PS2CamGetIRXVersion(), PS2CamInit(), PS2CamOpenDevice(), PS2CamReadPacket(), PS2CamSetDeviceBandwidth(), PS2CamSetDeviceConfig(), PS2CamSetLEDMode(), ps2ip_getconfig(), ps2ip_setconfig(), PS2MouseEnum(), PS2MouseGetAccel(), PS2MouseGetBoundary(), PS2MouseGetDblClickTIme(), PS2MouseGetReadMode(), PS2MouseGetThres(), PS2MouseGetVersion(), PS2MouseRead(), PS2MouseReset(), PS2MouseSetAccel(), PS2MouseSetBoundary(), PS2MouseSetDblClickTime(), PS2MouseSetPosition(), PS2MouseSetReadMode(), PS2MouseSetThres(), recv(), recvfrom(), RMMan_Close(), RMMan_End(), RMMan_GetModuleVersion(), RMMan_Init(), RMMan_Open(), sceSdBlockTransStatus(), sceSdClearEffectWorkArea(), sceSdGetAddr(), sceSdGetCoreAttr(), sceSdGetEffectAttr(), sceSdGetParam(), sceSdGetSwitch(), sceSdInit(), sceSdSetAddr(), sceSdSetCoreAttr(), sceSdSetEffectAttr(), sceSdSetParam(), sceSdSetSwitch(), sceSdVoiceTrans(), sceSdVoiceTransStatus(), select(), send(), sendto(), setsockopt(), sndQueryMaxFreeMemSize(), sndStreamClose(), sndStreamGetPosition(), sndStreamOpen(), sndStreamPause(), sndStreamPlay(), sndStreamSetPosition(), sndStreamSetVolume(), and socket().
SifCheckStatRpc()
int SifCheckStatRpc (SifRpcClientData_t * cd)
Referenced by mcSync().
SifExecRequest()
void SifExecRequest (SifRpcServerData_t * srv)
SifExitRpc()
void SifExitRpc (void)
Referenced by LoadELFFromFile(), and main().
SifGetNextRequest()
SifRpcServerData_t* SifGetNextRequest (SifRpcDataQueue_t * qd)
SifInitRpc()
void SifInitRpc (int mode)
Referenced by main(), mcInit(), PS2CamInit(), and sior_thread().
SifRegisterRpc()
SifRpcServerData_t* SifRegisterRpc (SifRpcServerData_t * srv, int sid, SifRpcFunc_t func, void * buff, SifRpcFunc_t cfunc, void * cbuff, SifRpcDataQueue_t * qd)
Referenced by NETMAN_RPC_Thread(), PowerOffThread(), rpc_server_thread(), and sior_thread().
SifRemoveRpc()
SifRpcServerData_t* SifRemoveRpc (SifRpcServerData_t * sd, SifRpcDataQueue_t * queue)
Referenced by audsrv_quit(), NetManDeinitRPCServer(), and poweroffInit().
SifRemoveRpcQueue()
SifRpcDataQueue_t* SifRemoveRpcQueue (SifRpcDataQueue_t * qd)
Referenced by audsrv_quit(), NetManDeinitRPCServer(), and poweroffInit().
SifRpcGetOtherData()
int SifRpcGetOtherData (SifRpcReceiveData_t * rd, void * src, void * dest, int size, int mode)
Referenced by sbv_patch_enable_lmb(), slib_exp_lib_list(), slib_get_exp_lib(), smem_write_word(), smod_get_mod_by_name(), and smod_get_next_mod().
SifRpcLoop()
void SifRpcLoop (SifRpcDataQueue_t * q)
Referenced by NETMAN_RPC_Thread(), PowerOffThread(), rpc_server_thread(), and sior_thread().
SifSetRpcQueue()
SifRpcDataQueue_t* SifSetRpcQueue (SifRpcDataQueue_t * q, int thread_id)
Referenced by NETMAN_RPC_Thread(), PowerOffThread(), rpc_server_thread(), and sior_thread().