ps2sdk: ee/rpc/sior/src/sior_rpc.c File Reference
sior_rpc.c File Reference
#include <tamtypes.h>
#include <kernel.h>
#include <sifrpc.h>
#include <stdarg.h>
#include <string.h>
#include <malloc.h>
#include <fcntl.h>
#include <stdio.h>
#include <sio.h>
#include "sior_rpc.h"
Data Structures
struct init_arguments_t
Macros
#define IOP_MEM 0xbc000000
Enumerations
enum {
SIOR_INIT = 1 ,
SIOR_PUTC ,
SIOR_GETC ,
SIOR_GETCBLOCK ,
SIOR_WRITE ,
SIOR_READ ,
SIOR_PUTS ,
SIOR_PUTSN ,
SIOR_GETS ,
SIOR_FLUSH
}
Functions
static void * sior_rpc_server (u32 funcno, void *data, int size)
static void sior_thread (void)
int SIOR_Init (int priority)
Variables
static SifRpcDataQueue_t qd
static SifRpcServerData_t Sd0
static u32 buffer [32]
Detailed Description
SIOR EE-side RPC code.
Definition in file sior_rpc.c.
Macro Definition Documentation
IOP_MEM
#define IOP_MEM 0xbc000000
EE mapped IOP mem
Definition at line 32 of file sior_rpc.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SIOR_INIT
SIOR_PUTC
SIOR_GETC
SIOR_GETCBLOCK
SIOR_WRITE
SIOR_READ
SIOR_PUTS
SIOR_PUTSN
SIOR_GETS
SIOR_FLUSH
Definition at line 34 of file sior_rpc.c.
      {
     SIOR_INIT = 1,
     SIOR_PUTC,
     SIOR_GETC,
     SIOR_GETCBLOCK,
     SIOR_WRITE,
     SIOR_READ,
     SIOR_PUTS,
     SIOR_PUTSN,
     SIOR_GETS,
     SIOR_FLUSH
 };
Function Documentation
SIOR_Init()
int SIOR_Init (int priority)
Definition at line 134 of file sior_rpc.c.
 {
     static int sior_init_done = 0;
     static u8 stack[4096];
     int thid;
     ee_thread_t t;
     if (sior_init_done)
         return 0;
     t.func = sior_thread;
     t.gp_reg = 0;
     t.initial_priority = priority;
     t.stack = stack;
     t.stack_size = 4096;
     if ((thid = CreateThread(&t)) < 0) {
         printf("Error creating SIO Remote EE-thread.\n");
         return thid;
     }
     StartThread(thid, NULL);
     sior_init_done = 1;
     return thid;
 }
References CreateThread(), ee_thread_t::func, ee_thread_t::gp_reg, ee_thread_t::initial_priority, NULL, sior_thread(), ee_thread_t::stack, ee_thread_t::stack_size, and StartThread().
sior_rpc_server()
static void* sior_rpc_server (u32 funcno, void * data, int size) static
Definition at line 55 of file sior_rpc.c.
{
     int res = 0, c;
     size_t s;
     char * p;
     struct init_arguments_t * i;
     switch(funcno) {
     case SIOR_INIT:
         i = (struct init_arguments_t *) data;
         sio_init(i->baudrate, i->lcr_ueps, i->lcr_upen, i->lcr_usbl, i->lcr_umode);
         break;
     case SIOR_PUTC:
         c = *((int *) data);
         res = sio_putc(c);
         break;
     case SIOR_GETC:
         res = sio_getc();
         break;
     case SIOR_GETCBLOCK:
         res = sio_getc_block();
         break;
     case SIOR_WRITE:
         p = *((char **) data) + IOP_MEM;
         s = *(((size_t *) data) + 1);
         DI();
         ee_kmode_enter();
         res = sio_write(p, s);
         ee_kmode_exit();
         EI();
         break;
     case SIOR_READ:
         p = *((char **) data) + IOP_MEM;
         s = *(((size_t *) data) + 1);
         DI();
         ee_kmode_enter();
         res = sio_read(p, s);
         ee_kmode_exit();
         EI();
         break;
     case SIOR_PUTS:
         p = *((char **) data) + IOP_MEM;
         DI();
         ee_kmode_enter();
         res = sio_puts(p);
         ee_kmode_exit();
         EI();
         break;
     case SIOR_PUTSN:
         p = *((char **) data) + IOP_MEM;
         DI();
         ee_kmode_enter();
         res = sio_putsn(p);
         ee_kmode_exit();
         EI();
         break;
     case SIOR_GETS:
         p = *((char **) data) + IOP_MEM;
         DI();
         ee_kmode_enter();
         res = (int)sio_gets(p);
         ee_kmode_exit();
         EI();
         break;
     case SIOR_FLUSH:
         sio_flush();
         break;
     }
     *((int *) data) = res;
     return data;
 }
References init_arguments_t::baudrate, data, DI, ee_kmode_enter(), ee_kmode_exit(), EI, IOP_MEM, init_arguments_t::lcr_ueps, init_arguments_t::lcr_umode, init_arguments_t::lcr_upen, init_arguments_t::lcr_usbl, s, sio_flush(), sio_getc(), sio_getc_block(), sio_gets(), sio_init(), sio_putc(), sio_puts(), sio_putsn(), sio_read(), sio_write(), SIOR_FLUSH, SIOR_GETC, SIOR_GETCBLOCK, SIOR_GETS, SIOR_INIT, SIOR_PUTC, SIOR_PUTS, SIOR_PUTSN, SIOR_READ, and SIOR_WRITE.
Referenced by sior_thread().
sior_thread()
static void sior_thread (void) static
Definition at line 127 of file sior_rpc.c.
{
     SifInitRpc(0);
     SifSetRpcQueue(&qd, GetThreadId());
     SifRegisterRpc(&Sd0, SIOR_IRX, (SifRpcFunc_t)sior_rpc_server, buffer, NULL, NULL, &qd);
     SifRpcLoop(&qd);
 }
References buffer, GetThreadId(), NULL, qd, Sd0, SifInitRpc(), SifRegisterRpc(), SifRpcLoop(), SifSetRpcQueue(), SIOR_IRX, and sior_rpc_server().
Referenced by SIOR_Init().
Variable Documentation
buffer
u32 buffer[32] static
Definition at line 29 of file sior_rpc.c.
Referenced by sior_thread().
qd
SifRpcDataQueue_t qd static
Definition at line 27 of file sior_rpc.c.
Referenced by sior_thread().
Sd0
SifRpcServerData_t Sd0 static
Definition at line 28 of file sior_rpc.c.
Referenced by sior_thread().