ps2sdk: ee/rpc/sior/include/sior_rpc.h File Reference
sior_rpc.h File Reference
Macros
#define SIOR_IRX 0xC001510
Functions
int SIOR_Init (int priority)
Detailed Description
EE-side SIO remote service.
Definition in file sior_rpc.h.
Macro Definition Documentation
SIOR_IRX
#define SIOR_IRX 0xC001510
Definition at line 19 of file sior_rpc.h.
Function Documentation
SIOR_Init()
int SIOR_Init (int priority)
Definition at line 134 of file sior_rpc.c.
 {
     static int sior_init_done = 0;
     static u8 stack[4096];
     int thid;
     ee_thread_t t;
     if (sior_init_done)
         return 0;
     t.func = sior_thread;
     t.gp_reg = 0;
     t.initial_priority = priority;
     t.stack = stack;
     t.stack_size = 4096;
     if ((thid = CreateThread(&t)) < 0) {
         printf("Error creating SIO Remote EE-thread.\n");
         return thid;
     }
     StartThread(thid, NULL);
     sior_init_done = 1;
     return thid;
 }
References CreateThread(), ee_thread_t::func, ee_thread_t::gp_reg, ee_thread_t::initial_priority, NULL, sior_thread(), ee_thread_t::stack, ee_thread_t::stack_size, and StartThread().