ps2sdk: ee/libc/src/sleep.c File Reference
sleep.c File Reference
#include <kernel.h>
#include <errno.h>
#include <time.h>
#include <unistd.h>
#include "ps2sdkapi.h"
Macros
#define MIN_HSYNC_PER_SEC (240*50)
#define MIN_HSYNC_DELAY 100
#define MAX_PS2CLOCK_PER_HSYNC (PS2_CLOCKS_PER_SEC/MIN_HSYNC_PER_SEC)
Functions
static void _sleep_waker (s32 alarm_id, u16 time, void *arg2)
static u64 timespec_to_us (const struct timespec *pts)
static ps2_clock_t us_to_ps2_clock (u64 us)
static ps2_clock_t timespec_to_ps2_clock (const struct timespec *pts)
int nanosleep (const struct timespec *req, struct timespec *rem)
unsigned int sleep (unsigned int seconds)
Variables
static unsigned int iPS2ClockPerHSync = MAX_PS2CLOCK_PER_HSYNC
Detailed Description
sleep implementation
Definition in file sleep.c.
Macro Definition Documentation
MAX_PS2CLOCK_PER_HSYNC
#define MAX_PS2CLOCK_PER_HSYNC (PS2_CLOCKS_PER_SEC/MIN_HSYNC_PER_SEC)
Definition at line 26 of file sleep.c.
MIN_HSYNC_DELAY
#define MIN_HSYNC_DELAY 100
Definition at line 25 of file sleep.c.
MIN_HSYNC_PER_SEC
#define MIN_HSYNC_PER_SEC (240*50)
Definition at line 24 of file sleep.c.
Function Documentation
_sleep_waker()
static void _sleep_waker (s32 alarm_id, u16 time, void * arg2) static
Definition at line 31 of file sleep.c.
 {
     s32 *pSema = (s32 *)arg2;
     iSignalSema(*pSema);
     ExitHandler();
 }
References ExitHandler, and iSignalSema().
Referenced by nanosleep().
nanosleep()
int nanosleep (const struct timespec * req, struct timespec * rem)
Definition at line 50 of file sleep.c.
 {
     ee_sema_t sema;
     s32 sema_id;
     ps2_clock_t clock_delay, clock_end, clock_real_end;
     u16 hsync_delay;
     clock_delay = timespec_to_ps2_clock(req);
     clock_end   = ps2_clock() + clock_delay;
     hsync_delay = clock_delay / iPS2ClockPerHSync;
     if (hsync_delay >= MIN_HSYNC_DELAY) {
         sema.init_count = 0;
         sema.max_count  = 1;
         sema.option     = 0;
         sema_id = CreateSema(&sema);
         SetAlarm(hsync_delay, _sleep_waker, &sema_id);
         WaitSema(sema_id);
         DeleteSema(sema_id);
         // Correct the HSync delay
         // NOTE: We're always trying to end btween 0 and 1 HSyncs too short
         clock_real_end = ps2_clock();
         if (clock_real_end < (clock_end - iPS2ClockPerHSync)) {
             // We sleeped too short, so HSyncs must be faster
             // Correct the HSyncs for next time
             iPS2ClockPerHSync -= (clock_end - iPS2ClockPerHSync - clock_real_end) / hsync_delay;
         }
         else if (clock_real_end > clock_end) {
             // We sleeped too long, so HSyncs must be slower
             // Correct the HSyncs for next time
             iPS2ClockPerHSync += (clock_real_end - clock_end) / (hsync_delay-1);
         }
     }
     // Delay whatever time is left
     while(clock_end > ps2_clock())
         ;
     if (rem != NULL) {
         rem->tv_sec = 0;
         rem->tv_nsec = 0;
     }
         return 0;
 }
References _sleep_waker(), CreateSema(), DeleteSema(), ee_sema_t::init_count, iPS2ClockPerHSync, ee_sema_t::max_count, MIN_HSYNC_DELAY, NULL, ee_sema_t::option, ps2_clock(), SetAlarm(), timespec_to_ps2_clock(), and WaitSema().
Referenced by sleep().
sleep()
unsigned int sleep (unsigned int seconds)
Definition at line 98 of file sleep.c.
 {
     struct timespec ts;
     ts.tv_sec = seconds;
     ts.tv_nsec = 0;
     if (!nanosleep(&ts, &ts))
         return 0;
     if (errno == EINTR)
         return ts.tv_sec;
     return -1;
 }
References EINTR, errno, and nanosleep().
Referenced by main().
timespec_to_ps2_clock()
static ps2_clock_t timespec_to_ps2_clock (const struct timespec * pts) inline static
Definition at line 46 of file sleep.c.
{
     return us_to_ps2_clock(timespec_to_us(pts));
 }
References timespec_to_us(), and us_to_ps2_clock().
Referenced by nanosleep().
timespec_to_us()
static u64 timespec_to_us (const struct timespec * pts) inline static
Definition at line 38 of file sleep.c.
{
     return (pts->tv_sec * 1000000ULL) + (pts->tv_nsec / 1000ULL);
 }
Referenced by timespec_to_ps2_clock().
us_to_ps2_clock()
static ps2_clock_t us_to_ps2_clock (u64 us) inline static
Definition at line 42 of file sleep.c.
{
     return (us * PS2_CLOCKS_PER_MSEC) / 1000;
 }
References PS2_CLOCKS_PER_MSEC.
Referenced by timespec_to_ps2_clock().
Variable Documentation
iPS2ClockPerHSync
unsigned int iPS2ClockPerHSync = MAX_PS2CLOCK_PER_HSYNC static
Definition at line 29 of file sleep.c.
Referenced by nanosleep().