ps2sdk: ee/sbv/include/smod.h File Reference
smod.h File Reference
#include <tamtypes.h>
Data Structures
struct smod_mod_info_t
Functions
int smod_get_next_mod (smod_mod_info_t *cur_mod, smod_mod_info_t *next_mod)
int smod_get_mod_by_name (const char *name, smod_mod_info_t *info)
Detailed Description
Sub-CPU module interface.
Definition in file smod.h.
Function Documentation
smod_get_mod_by_name()
int smod_get_mod_by_name (const char * name, smod_mod_info_t * info)
Find and retreive a module by it's module name.
Definition at line 54 of file smod.c.
 {
         SifRpcReceiveData_t RData;
         int len = strlen(name);
         if (!smod_get_next_mod(NULL, info))
                 return 0;
         smem_buf.bytes[64]='\0';
         do {
                 SyncDCache(&smem_buf, smem_buf.bytes+64);
                 if(SifRpcGetOtherData(&RData, info->name, &smem_buf, 64, 0)>=0){
                         if (!__memcmp(smem_buf.bytes, name, len))
                                 return info->id;
                 }
         } while (smod_get_next_mod(info, info) != 0);
         return 0;
 }
References __memcmp(), smem_buf::bytes, info, NULL, SifRpcGetOtherData(), smod_get_next_mod(), and SyncDCache().
Referenced by sbv_patch_enable_lmb(), and sbv_patch_fileio().
smod_get_next_mod()
int smod_get_next_mod (smod_mod_info_t * cur_mod, smod_mod_info_t * next_mod)
Return the next module referenced in the global module list.
Definition at line 30 of file smod.c.
 {
         SifRpcReceiveData_t RData;
         void *addr;
         /* If cur_mod is 0, return the head of the list (typically IOP address 0x800).  */
         if (!cur_mod) {
                 addr = (void *)0x800;
         } else {
                 if (!cur_mod->next)
                         return 0;
                 else
                         addr = cur_mod->next;
         }
         SyncDCache(&smem_buf, smem_buf.bytes+sizeof(smod_mod_info_t));
         if(SifRpcGetOtherData(&RData, addr, &smem_buf, sizeof(smod_mod_info_t), 0)>=0){
                 memcpy(next_mod, &smem_buf.mod_info, sizeof(smod_mod_info_t));
                 return next_mod->id;
         }
         return 0;
 }
References smem_buf::bytes, smod_mod_info_t::id, smem_buf::mod_info, smod_mod_info_t::next, SifRpcGetOtherData(), and SyncDCache().
Referenced by smod_get_mod_by_name().