ps2sdk: ee/graph/src/graph.c File Reference
graph.c File Reference
#include <kernel.h>
#include <gs_privileged.h>
#include <graph.h>
Functions
int graph_initialize (int fbp, int width, int height, int psm, int x, int y)
int graph_add_vsync_handler (int(*vsync_callback)())
void graph_remove_vsync_handler (int callback_id)
int graph_get_field (void)
void graph_wait_hsync (void)
int graph_check_vsync (void)
void graph_start_vsync (void)
void graph_wait_vsync (void)
Function Documentation
graph_add_vsync_handler()
int graph_add_vsync_handler (int(*)() vsync_callback)
Add a vsync interrupt handler
Definition at line 29 of file graph.c.
 {
         int callback_id;
         DIntr();
         callback_id = AddIntcHandler(INTC_VBLANK_S, vsync_callback, -1);
         EnableIntc(INTC_VBLANK_S);
         EIntr();
         return callback_id;
 }
References AddIntcHandler(), DIntr(), EIntr(), EnableIntc(), and INTC_VBLANK_S.
graph_check_vsync()
int graph_check_vsync (void)
Checks if a vertical sync event is currently generated.
Definition at line 85 of file graph.c.
 {
         return (*GS_REG_CSR & 8);
 }
References GS_REG_CSR.
graph_get_field()
int graph_get_field (void)
Definition at line 59 of file graph.c.
 {
         // Return the currently displayed field.
         if (*GS_REG_CSR & (1 << 13))
         {
                 return GRAPH_FIELD_ODD;
         }
         return GRAPH_FIELD_EVEN;
 }
References GRAPH_FIELD_EVEN, GRAPH_FIELD_ODD, and GS_REG_CSR.
graph_initialize()
int graph_initialize (int fbp, int width, int height, int psm, int x, int y)
Initializes a default NTSC/PAL mode with default settings.
Definition at line 6 of file graph.c.
 {
         int mode = graph_get_region();
         // Set a default interlaced video mode with flicker filter.
         graph_set_mode(GRAPH_MODE_INTERLACED, mode, GRAPH_MODE_FIELD, GRAPH_ENABLE);
         // Set the screen up
         graph_set_screen(0,0,width,height);
         // Set black background
         graph_set_bgcolor(0,0,0);
         graph_set_framebuffer_filtered(fbp,width,psm,x,y);
         graph_enable_output();
         // End function.
         return 0;
 }
References GRAPH_ENABLE, graph_enable_output(), graph_get_region(), GRAPH_MODE_FIELD, GRAPH_MODE_INTERLACED, graph_set_bgcolor(), graph_set_framebuffer_filtered(), graph_set_mode(), graph_set_screen(), mode, x, and y.
Referenced by draw_init_env(), init_gs(), and main().
graph_remove_vsync_handler()
void graph_remove_vsync_handler (int callback_id)
Remove a vsync interrupt handler
Definition at line 46 of file graph.c.
 {
         DIntr();
         DisableIntc(INTC_VBLANK_S);
         RemoveIntcHandler(INTC_VBLANK_S, callback_id);
         EIntr();
 }
References DIntr(), DisableIntc(), EIntr(), INTC_VBLANK_S, and RemoveIntcHandler().
graph_start_vsync()
void graph_start_vsync (void)
Starts a vertical sync event and returns immediately.
Definition at line 92 of file graph.c.
 {
         *GS_REG_CSR |= *GS_REG_CSR & 8;
 }
References GS_REG_CSR.
graph_wait_hsync()
void graph_wait_hsync (void)
Starts a horizontal sync event and waits
Definition at line 74 of file graph.c.
 {
         // Initiate hsync interrupt
         *GS_REG_CSR |= *GS_REG_CSR & 4;
         // Wait for hsync interrupt to be generated.
         while (!(*GS_REG_CSR & 4));
 }
References GS_REG_CSR.
graph_wait_vsync()
void graph_wait_vsync (void)
Starts a vertical sync event and waits.
Definition at line 99 of file graph.c.
 {
         // Initiate vsync interrupt.
         *GS_REG_CSR |= *GS_REG_CSR & 8;
         // Wait for vsync interrupt to be generated.
         while (!(*GS_REG_CSR & 8));
 }
References GS_REG_CSR.
Referenced by main(), render(), and run_demo().