ps2sdk: ee/rpc/poweroff/src/poweroff.c File Reference
poweroff.c File Reference
#include "libpwroff.h"
#include <errno.h>
#include <stdio.h>
#include <tamtypes.h>
#include <kernel.h>
#include <string.h>
#include <sifrpc.h>
#include <pwroff_rpc.h>
Functions
static void * PowerOff_ee_rpc_handler (int fnum, void *buffer, int len)
static void PowerOffThread (void *dat)
int poweroffInit (void)
void poweroffSetCallback (poweroff_callback cb, void *arg)
void poweroffShutdown (void)
void poweroffChangeThreadPriority (int priority)
Variables
void * _gp
static poweroff_callback poweroff_cb = NULL
static void * poweroff_data = NULL
static u8 poffThreadStack [512 *16]
int _iop_reboot_count
static SifRpcClientData_t cd0
static struct t_SifRpcDataQueue cb_queue
static struct t_SifRpcServerData cb_srv
static int powerOffThreadId = -1
Function Documentation
PowerOff_ee_rpc_handler()
static void* PowerOff_ee_rpc_handler (int fnum, void * buffer, int len) static
Definition at line 34 of file poweroff.c.
 {
         switch(fnum){
                 case POFF_RPC_BUTTON:
                         printf("EE: power button pressed\n");
                         if (poweroff_cb)
                                 poweroff_cb(poweroff_data);
                         break;
         }
         return buffer;
 }
References buffer, POFF_RPC_BUTTON, poweroff_cb, and poweroff_data.
Referenced by PowerOffThread().
poweroffChangeThreadPriority()
void poweroffChangeThreadPriority (int priority)
Definition at line 110 of file poweroff.c.
 {
         ChangeThreadPriority(powerOffThreadId, priority);
 }
References ChangeThreadPriority(), and powerOffThreadId.
poweroffInit()
int poweroffInit (void)
Initializes the poweroff library. A service thread with a default priority of 0x70 will be created.
Definition at line 57 of file poweroff.c.
 {
         ee_thread_t thread;
         int res;
         static int _init_count = -1;
         if(_init_count == _iop_reboot_count)
                 return 0;
         _init_count = _iop_reboot_count;
         while(((res = SifBindRpc(&cd0, PWROFF_IRX, 0)) < 0) || (cd0.server == NULL))
                 nopdelay();
         // Terminate and delete any previously created threads
         if (powerOffThreadId >= 0) {
                 TerminateThread(powerOffThreadId);
                 DeleteThread(powerOffThreadId);
                 SifRemoveRpc(&cb_srv, &cb_queue);
                 SifRemoveRpcQueue(&cb_queue);
                 powerOffThreadId = -1;
         }
         thread.initial_priority = POWEROFF_THREAD_PRIORITY;
         thread.stack_size = sizeof(poffThreadStack);
         thread.gp_reg = &_gp;
         thread.func = PowerOffThread;
         thread.stack = (void *)poffThreadStack;
         thread.option = 0;
         thread.attr = 0;
         powerOffThreadId = CreateThread(&thread);
         StartThread(powerOffThreadId, NULL);
         int autoShutdown[4] = {0};
         SifCallRpc(&cd0, PWROFF_ENABLE_AUTO_SHUTOFF, 0, NULL, 0, autoShutdown, sizeof(autoShutdown), NULL, NULL);
         return res;
 }
References _gp, _iop_reboot_count, ee_thread_t::attr, cb_queue, cb_srv, cd0, CreateThread(), DeleteThread(), ee_thread_t::func, ee_thread_t::gp_reg, ee_thread_t::initial_priority, nopdelay(), NULL, ee_thread_t::option, poffThreadStack, POWEROFF_THREAD_PRIORITY, PowerOffThread(), powerOffThreadId, PWROFF_ENABLE_AUTO_SHUTOFF, PWROFF_IRX, SifRpcClientData_t::server, SifBindRpc(), SifCallRpc(), SifRemoveRpc(), SifRemoveRpcQueue(), ee_thread_t::stack, ee_thread_t::stack_size, StartThread(), and TerminateThread().
Referenced by main(), poweroffSetCallback(), and poweroffShutdown().
poweroffSetCallback()
void poweroffSetCallback (poweroff_callback cb, void * arg)
Definition at line 95 of file poweroff.c.
 {
         poweroffInit();
         poweroff_cb = cb;
         poweroff_data = arg;
 }
References poweroff_cb, poweroff_data, and poweroffInit().
Referenced by main().
poweroffShutdown()
void poweroffShutdown (void)
Definition at line 103 of file poweroff.c.
 {
         poweroffInit();
         SifCallRpc(&cd0, PWROFF_SHUTDOWN, 0, NULL, 0, NULL, 0, NULL, NULL);
 }
References cd0, NULL, poweroffInit(), PWROFF_SHUTDOWN, and SifCallRpc().
Referenced by poweroffCallback().
PowerOffThread()
static void PowerOffThread (void * dat) static
Definition at line 48 of file poweroff.c.
 {
         static unsigned char cb_rpc_buffer[64] __attribute__((aligned(64)));
         SifSetRpcQueue(&cb_queue, powerOffThreadId);
         SifRegisterRpc(&cb_srv, PWROFF_IRX, &PowerOff_ee_rpc_handler, cb_rpc_buffer, NULL, NULL, &cb_queue);
         SifRpcLoop(&cb_queue);
 }
References cb_queue, cb_srv, NULL, PowerOff_ee_rpc_handler(), powerOffThreadId, PWROFF_IRX, SifRegisterRpc(), SifRpcLoop(), and SifSetRpcQueue().
Referenced by poweroffInit().
Variable Documentation
_gp
void* _gp extern
Referenced by poweroffInit().
_iop_reboot_count
int _iop_reboot_count extern
Referenced by poweroffInit().
cb_queue
struct t_SifRpcDataQueue cb_queue static
Definition at line 29 of file poweroff.c.
Referenced by poweroffInit(), and PowerOffThread().
cb_srv
struct t_SifRpcServerData cb_srv static
Definition at line 29 of file poweroff.c.
Referenced by poweroffInit(), and PowerOffThread().
cd0
SifRpcClientData_t cd0 static
Definition at line 29 of file poweroff.c.
Referenced by poweroffInit(), and poweroffShutdown().
poffThreadStack
u8 poffThreadStack[512 *16] static
Definition at line 26 of file poweroff.c.
Referenced by poweroffInit().
poweroff_cb
poweroff_callback poweroff_cb = NULL static
Definition at line 23 of file poweroff.c.
Referenced by PowerOff_ee_rpc_handler(), and poweroffSetCallback().
poweroff_data
void* poweroff_data = NULL static
Definition at line 24 of file poweroff.c.
Referenced by PowerOff_ee_rpc_handler(), and poweroffSetCallback().
powerOffThreadId
int powerOffThreadId = -1 static
Definition at line 32 of file poweroff.c.
Referenced by poweroffChangeThreadPriority(), poweroffInit(), and PowerOffThread().