ps2sdk: ee/network/tcpip/src/ps2ip.c File Reference
ps2ip.c File Reference
#include <stdio.h>
#include <string.h>
#include <netman.h>
#include <lwip/memp.h>
#include "lwip/sys.h"
#include "lwip/tcp.h"
#include "lwip/tcpip.h"
#include "lwip/netif.h"
#include "lwip/dhcp.h"
#include "lwip/prot/dhcp.h"
#include "lwip/inet.h"
#include "netif/etharp.h"
#include "ps2ip_internal.h"
Functions
int ps2ip_getconfig (char *pszName, t_ip_info *pInfo)
int ps2ip_setconfig (const t_ip_info *pInfo)
static void EnQTxPacket (struct pbuf *tx)
static err_t SMapLowLevelOutput (struct netif *pNetIF, struct pbuf *pOutput)
static void LinkStateUp (void)
static void LinkStateDown (void)
static void * AllocRxPacket (unsigned int size, void **payload)
static void ReallocRxPacket (void *packet, unsigned int size)
static void FreeRxPacket (void *packet)
static void EnQRxPacket (void *packet)
static int NextTxPacket (void **payload)
static void DeQTxPacket (void)
static int AfterTxPacket (void **payload)
static void InitDone (void *pvArg)
static err_t SMapIFInit (struct netif *pNetIF)
err_t ps2ip_input (PBuf *pInput, NetIF *pNetIF)
static void InitializeLWIP (void)
int ps2ipInit (struct ip4_addr *ip_address, struct ip4_addr *subnet_mask, struct ip4_addr *gateway)
void ps2ipDeinit (void)
void ps2ipSetHsyncTicksPerMSec (unsigned char ticks)
Variables
static struct netif NIF
static struct pbuf * TxHead
static struct pbuf * TxTail
unsigned short int hsyncTicksPerMSec = 16
Detailed Description
PS2 TCP/IP STACK FOR EE
Definition in file ps2ip.c.
Function Documentation
AfterTxPacket()
static int AfterTxPacket (void ** payload) static
Definition at line 248 of file ps2ip.c.
 {
         int len;
         if(TxTail != NULL && TxTail->next != NULL)
         {
                 *payload = TxTail->next->payload;
                 len = TxTail->next->len;
         } else
                 len = 0;
         return len;
 }
References PBuf::len, PBuf::next, NULL, PBuf::payload, and TxTail.
Referenced by ps2ipInit().
AllocRxPacket()
static void* AllocRxPacket (unsigned int size, void ** payload) static
Definition at line 181 of file ps2ip.c.
 {
         struct pbuf* pbuf;
         if((pbuf = pbuf_alloc(PBUF_RAW, size, PBUF_POOL)) != NULL)
                 *payload = pbuf->payload;
         return pbuf;
 }
References NULL, PBuf::payload, pbuf_alloc(), PBUF_POOL, and PBUF_RAW.
Referenced by ps2ipInit().
DeQTxPacket()
static void DeQTxPacket (void) static
Definition at line 220 of file ps2ip.c.
 {
         struct pbuf *toFree;
         toFree = NULL;
         DI();
         if(TxTail != NULL)
         {
                 toFree = TxTail;
                 if(TxTail == TxHead) {
                         //Last in queue.
                         TxTail = NULL;
                         TxHead = NULL;
                 } else {
                         TxTail = TxTail->next;
                 }
         }
         EI();
         if(toFree != NULL)
         {
                 toFree->next = NULL;
                 pbuf_free(toFree);
         }
 }
References DI, EI, PBuf::next, NULL, pbuf_free(), TxHead, and TxTail.
Referenced by ps2ipInit().
EnQRxPacket()
static void EnQRxPacket (void * packet) static
Definition at line 201 of file ps2ip.c.
 {
         ps2ip_input(packet, &NIF);
 }
References NIF, packet, and ps2ip_input().
Referenced by ps2ipInit().
EnQTxPacket()
static void EnQTxPacket (struct pbuf * tx) static
Definition at line 131 of file ps2ip.c.
 {
         DI();
         if(TxHead != NULL)
                 TxHead->next = tx;
         TxHead = tx;
         tx->next = NULL;
         if(TxTail == NULL)      //Queue empty
                 TxTail = tx;
         EI();
 }
References DI, EI, PBuf::next, NULL, TxHead, and TxTail.
Referenced by SMapLowLevelOutput().
FreeRxPacket()
static void FreeRxPacket (void * packet) static
Definition at line 196 of file ps2ip.c.
 {
         pbuf_free(packet);
 }
References packet, and pbuf_free().
Referenced by ps2ipInit().
InitDone()
static void InitDone (void * pvArg) static
Definition at line 262 of file ps2ip.c.
 {
         dbgprintf("InitDone: TCPIP initialized\n");
         sys_sem_signal((sys_sem_t*)pvArg);
 }
References dbgprintf, and sys_sem_signal().
Referenced by InitializeLWIP().
InitializeLWIP()
static void InitializeLWIP (void) inline static
Definition at line 300 of file ps2ip.c.
 {
         sys_sem_t Sema;
         dbgprintf("PS2IP: Module Loaded.\n");
         sys_sem_new(&Sema, 0);
         dbgprintf("PS2IP: Calling tcpip_init\n");
         tcpip_init(InitDone,&Sema);
         sys_arch_sem_wait(&Sema, 0);
         sys_sem_free(&Sema);
         dbgprintf("PS2IP: System Initialised\n");
 }
References dbgprintf, InitDone(), sys_arch_sem_wait(), sys_sem_free(), and sys_sem_new().
Referenced by ps2ipInit().
LinkStateDown()
static void LinkStateDown (void) static
Definition at line 176 of file ps2ip.c.
 {
         tcpip_callback((void*)&netif_set_link_down, &NIF);
 }
References NIF.
Referenced by ps2ipInit().
LinkStateUp()
static void LinkStateUp (void) static
Definition at line 171 of file ps2ip.c.
 {
         tcpip_callback((void*)&netif_set_link_up, &NIF);
 }
References NIF.
Referenced by ps2ipInit().
NextTxPacket()
static int NextTxPacket (void ** payload) static
Definition at line 206 of file ps2ip.c.
 {
         int len;
         if(TxTail != NULL)
         {
                 *payload = TxTail->payload;
                 len = TxTail->len;
         } else
                 len = 0;
         return len;
 }
References PBuf::len, NULL, PBuf::payload, and TxTail.
Referenced by ps2ipInit().
ps2ip_getconfig()
int ps2ip_getconfig (char * pszName, t_ip_info * pInfo)
Definition at line 41 of file ps2ip.c.
 {
         NetIF*  pNetIF=netif_find(pszName);
         if (pNetIF==NULL)
         {
                 //Net interface not found.
                 memset(pInfo,0,sizeof(*pInfo));
                 return  0;
         }
         strcpy(pInfo->netif_name,pszName);
         pInfo->ipaddr.s_addr=pNetIF->ip_addr.addr;
         pInfo->netmask.s_addr=pNetIF->netmask.addr;
         pInfo->gw.s_addr=pNetIF->gw.addr;
         memcpy(pInfo->hw_addr,pNetIF->hwaddr,sizeof(pInfo->hw_addr));
 #if LWIP_DHCP
         struct dhcp *dhcp = netif_dhcp_data(pNetIF);
         if ((dhcp != NULL) && (dhcp->state != DHCP_STATE_OFF))
         {
                 pInfo->dhcp_enabled=1;
                 pInfo->dhcp_status=dhcp->state;
         }
         else
         {
                 pInfo->dhcp_enabled=0;
                 pInfo->dhcp_status=DHCP_STATE_OFF;
         }
 #else
         pInfo->dhcp_enabled=0;
 #endif
         return  1;
 }
Referenced by ethApplyIPConfig(), ethGetDHCPStatus(), and ethPrintIPConfig().
ps2ip_input()
err_t ps2ip_input (PBuf * pInput, NetIF * pNetIF)
Definition at line 290 of file ps2ip.c.
 {
         err_t result;
         if((result = pNetIF->input(pInput, pNetIF)) != ERR_OK)
                 pbuf_free(pInput);
         return result;
 }
References pbuf_free(), and result.
Referenced by EnQRxPacket().
ps2ip_setconfig()
int ps2ip_setconfig (const t_ip_info * pInfo)
Definition at line 79 of file ps2ip.c.
 {
         NetIF*  pNetIF=netif_find(pInfo->netif_name);
         if      (pNetIF==NULL)
         {
                 return  0;
         }
 #if     LWIP_DHCP
         struct dhcp *dhcp = netif_dhcp_data(pNetIF);
         //Enable dhcp here
         if (pInfo->dhcp_enabled)
         {
                 if ((dhcp == NULL) || (dhcp->state == DHCP_STATE_OFF))
                 {
                         //Set initial IP address
                         netif_set_ipaddr(pNetIF,(IPAddr*)&pInfo->ipaddr);
                         netif_set_netmask(pNetIF,(IPAddr*)&pInfo->netmask);
                         netif_set_gw(pNetIF,(IPAddr*)&pInfo->gw);
                         //Start DHCP client
                         dhcp_start(pNetIF);
                 }
         }
         else
         {
                 if ((dhcp != NULL) && (dhcp->state != DHCP_STATE_OFF))
                 {
                         //Release DHCP lease
                         dhcp_release(pNetIF);
                         //Stop DHCP client
                         dhcp_stop(pNetIF);
                 }
                 netif_set_ipaddr(pNetIF,(IPAddr*)&pInfo->ipaddr);
                 netif_set_netmask(pNetIF,(IPAddr*)&pInfo->netmask);
                 netif_set_gw(pNetIF,(IPAddr*)&pInfo->gw);
         }
 #else
         netif_set_ipaddr(pNetIF,(IPAddr*)&pInfo->ipaddr);
         netif_set_netmask(pNetIF,(IPAddr*)&pInfo->netmask);
         netif_set_gw(pNetIF,(IPAddr*)&pInfo->gw);
 #endif
         return  1;
 }
References t_ip_info::dhcp_enabled, DHCP_STATE_OFF, t_ip_info::gw, t_ip_info::ipaddr, netif_dhcp_data, netif_find(), t_ip_info::netif_name, netif_set_gw(), netif_set_ipaddr(), netif_set_netmask(), t_ip_info::netmask, and NULL.
Referenced by ethApplyIPConfig().
ps2ipDeinit()
void ps2ipDeinit (void)
Definition at line 342 of file ps2ip.c.
                       {
         NetManUnregisterNetworkStack();
 }
References NetManUnregisterNetworkStack().
Referenced by main().
ps2ipInit()
int ps2ipInit (struct ip4_addr * ip_address, struct ip4_addr * subnet_mask, struct ip4_addr * gateway)
Initializes PS2IP. Specify a dummy address like "169.254.0.1" if DHCP is to be used, before enabling DHCP via ps2ip_setconfig().
Definition at line 316 of file ps2ip.c.
{
         static struct NetManNetProtStack stack={
                 &LinkStateUp,
                 &LinkStateDown,
                 &AllocRxPacket,
                 &FreeRxPacket,
                 &EnQRxPacket,
                 &NextTxPacket,
                 &DeQTxPacket,
                 &AfterTxPacket,
                 &ReallocRxPacket
         };
         NetManInit();
         InitializeLWIP();
         netif_add(&NIF, ip_address, subnet_mask, gateway, NULL, &SMapIFInit, tcpip_input);
         netif_set_default(&NIF);
         NetManRegisterNetworkStack(&stack);
         netif_set_up(&NIF);
         return 0;
 }
References AfterTxPacket(), AllocRxPacket(), DeQTxPacket(), EnQRxPacket(), FreeRxPacket(), InitializeLWIP(), LinkStateDown(), LinkStateUp(), netif_add(), netif_set_default(), netif_set_up(), NetManInit(), NetManRegisterNetworkStack(), NextTxPacket(), NIF, NULL, ReallocRxPacket(), SMapIFInit(), and tcpip_input().
Referenced by main().
ps2ipSetHsyncTicksPerMSec()
void ps2ipSetHsyncTicksPerMSec (unsigned char ticks)
Use to specify the number of H-sync ticks per milisecond (Default: 16). Use this function to keep timings accurate, if a mode like 480P (~31KHz H-sync) is used instead of NTSC/PAL (~16KHz H-sync).
Definition at line 346 of file ps2ip.c.
{
         hsyncTicksPerMSec = ticks;
 }
References hsyncTicksPerMSec.
ReallocRxPacket()
static void ReallocRxPacket (void * packet, unsigned int size) static
Definition at line 191 of file ps2ip.c.
 {
         pbuf_realloc((struct pbuf *)packet, size);
 }
References packet, and pbuf_realloc().
Referenced by ps2ipInit().
SMapIFInit()
static err_t SMapIFInit (struct netif * pNetIF) static
Should be called at the beginning of the program to set up the network interface.
Definition at line 269 of file ps2ip.c.
 {
         TxHead = NULL;
         TxTail = NULL;
         pNetIF->name[0]='s';
         pNetIF->name[1]='m';
         pNetIF->output=&etharp_output;  // For LWIP 1.3.0 and later.
         pNetIF->linkoutput=&SMapLowLevelOutput;
         pNetIF->hwaddr_len=NETIF_MAX_HWADDR_LEN;
         pNetIF->flags|=(NETIF_FLAG_ETHARP|NETIF_FLAG_BROADCAST);        // For LWIP v1.3.0 and later.
         pNetIF->mtu=1500;
         //Get MAC address.
         NetManIoctl(NETMAN_NETIF_IOCTL_ETH_GET_MAC, NULL, 0, pNetIF->hwaddr, sizeof(pNetIF->hwaddr));
         dbgprintf("MAC address : %02d:%02d:%02d:%02d:%02d:%02d\n",pNetIF->hwaddr[0],pNetIF->hwaddr[1],pNetIF->hwaddr[2],
                                  pNetIF->hwaddr[3],pNetIF->hwaddr[4],pNetIF->hwaddr[5]);
         return  ERR_OK;
 }
References dbgprintf, etharp_output(), NetIF::flags, NetIF::hwaddr, NetIF::hwaddr_len, NetIF::linkoutput, NetIF::mtu, NetIF::name, NETIF_FLAG_BROADCAST, NETIF_FLAG_ETHARP, NETIF_MAX_HWADDR_LEN, NETMAN_NETIF_IOCTL_ETH_GET_MAC, NetManIoctl(), NULL, NetIF::output, SMapLowLevelOutput(), TxHead, and TxTail.
Referenced by ps2ipInit().
SMapLowLevelOutput()
static err_t SMapLowLevelOutput (struct netif * pNetIF, struct pbuf * pOutput) static
Definition at line 147 of file ps2ip.c.
 {
         struct pbuf* pbuf;
         err_t result;
         result = ERR_OK;
         if(pOutput->tot_len > pOutput->len)
         {
                 pbuf_ref(pOutput);      //Increment reference count because LWIP must free the PBUF, not the driver!
                 if((pbuf = pbuf_coalesce(pOutput, PBUF_RAW)) != pOutput)
                 {       //No need to increase reference count because pbuf_coalesce() does it.
                         EnQTxPacket(pbuf);
                         NetManNetIFXmit();
                 } else
                         result = ERR_MEM;
         } else {
                 pbuf_ref(pOutput);      //This will be freed later.
                 EnQTxPacket(pOutput);
                 NetManNetIFXmit();
         }
         return result;
 }
References EnQTxPacket(), PBuf::len, NetManNetIFXmit(), pbuf_coalesce(), PBUF_RAW, pbuf_ref(), result, and PBuf::tot_len.
Referenced by SMapIFInit().
Variable Documentation
hsyncTicksPerMSec
unsigned short int hsyncTicksPerMSec = 16
Definition at line 39 of file ps2ip.c.
Referenced by mSec2HSyncTicks(), and ps2ipSetHsyncTicksPerMSec().
NIF
struct netif NIF static
Definition at line 1 of file ps2ip.c.
Referenced by EnQRxPacket(), LinkStateDown(), LinkStateUp(), and ps2ipInit().
TxHead
struct pbuf* TxHead static
Definition at line 37 of file ps2ip.c.
Referenced by DeQTxPacket(), EnQTxPacket(), and SMapIFInit().
TxTail
struct pbuf * TxTail static
Definition at line 37 of file ps2ip.c.
Referenced by AfterTxPacket(), DeQTxPacket(), EnQTxPacket(), NextTxPacket(), and SMapIFInit().