ps2sdk: ee/kernel/src/srcfile/src/alarm.c File Reference
alarm.c File Reference
#include "tamtypes.h"
#include "timer.h"
#include "ee_regs.h"
#include "kernel.h"
#include "internal.h"
Data Structures
struct alarm
Macros
#define USER_MODE_DISPATCHER 0x00082000
#define INTC_TIM3 12
#define T3_COUNT_W ((vu32*)0xB0001800)
#define T3_MODE_W ((vu32*)0xB0001810)
#define T3_COMP_W ((vu32*)0xB0001820)
Functions
static u32 CalculateTimeDiff (u32 t1, u32 t2)
static int InsertAlarm (u32 now, u32 target)
static s32 SetAlarmInternal (u16 time, void(*callback)(s32 dispatch_id, u16 time, void *common), void *common)
static void SetupTIM3 (u16 ticks)
s32 ReleaseAlarm (s32 id)
s32 SetAlarm (u16 time, void(*callback)(s32 dispatch_id, u16 time, void *common), void *common)
void Intc12Handler (void)
Variables
static int AlarmCount = 0
static u64 AlarmStatus = 0
static struct alarm alarms [MAX_ALARMS]
Macro Definition Documentation
INTC_TIM3
#define INTC_TIM3 12
Definition at line 19 of file alarm.c.
T3_COMP_W
#define T3_COMP_W ((vu32*)0xB0001820)
Definition at line 22 of file alarm.c.
T3_COUNT_W
#define T3_COUNT_W ((vu32*)0xB0001800)
Definition at line 20 of file alarm.c.
T3_MODE_W
#define T3_MODE_W ((vu32*)0xB0001810)
Definition at line 21 of file alarm.c.
USER_MODE_DISPATCHER
#define USER_MODE_DISPATCHER 0x00082000
Definition at line 17 of file alarm.c.
Function Documentation
CalculateTimeDiff()
static u32 CalculateTimeDiff (u32 t1, u32 t2) static
Definition at line 44 of file alarm.c.
 {
         return(t2 < t1 ? (0x10000 | t2) : t2);
 }
Referenced by InsertAlarm(), and ReleaseAlarm().
InsertAlarm()
static int InsertAlarm (u32 now, u32 target) static
Definition at line 49 of file alarm.c.
 {
         int pos, i;
         pos = 0;
         for(pos = 0; pos < AlarmCount; pos++)
         {
                 if(target < CalculateTimeDiff(now, alarms[pos].time))
                 {       //Spot found. If it is not at the end of the list, move back the list.
                         for(i = AlarmCount - 1; i >= pos; i--)
                                 alarms[i+1] = alarms[i];
                         break;
                 }
         }
         return pos;
 }
References AlarmCount, alarms, CalculateTimeDiff(), pos, alarm::target, and time.
Referenced by SetAlarmInternal().
Intc12Handler()
void Intc12Handler (void)
Definition at line 167 of file alarm.c.
 {
         struct alarm alarm;
         void *gp;
         int i;
         for(i = 0; i < AlarmCount; i++)
         {       //Attempt to find another alarm request that has a different target. Update TIM3's comparator.
                 if(alarms[i].target != alarms[0].target)
                 {
                         SetupTIM3(alarms[i].target);
                         break;
                 }
         }
         do{
                 alarm = alarms[0];
                 AlarmCount--;
                 for(i = 0; i < AlarmCount; i++)
                         alarms[i] = alarms[i+1];
                 gp = ChangeGP(alarm.gp);
                 AlarmStatus &= ~(1 << alarm.id);
                 InvokeUserModeCallback((void*)USER_MODE_DISPATCHER, alarm.callback, alarm.id, alarm.target, alarm.common);
                 SetGP(gp);
                 if(AlarmCount <= 0)
                         break;
         }while(alarms[0].target == alarm.target);
         if(AlarmCount <= 0)     //If there are no further alarms, disable CMPE.
                 *T3_MODE_W = Tn_MODE(3,0,0,0,0,1,0,0,1,0);
         else
                 SetupTIM3(alarms[0].target);
         ExitHandler();
 }
References AlarmCount, alarms, AlarmStatus, alarm::callback, ChangeGP(), alarm::common, ExitHandler, gp, alarm::gp, alarm::id, InvokeUserModeCallback(), SetGP(), SetupTIM3(), T3_MODE_W, alarm::target, Tn_MODE, and USER_MODE_DISPATCHER.
ReleaseAlarm()
s32 ReleaseAlarm (s32 id)
Definition at line 110 of file alarm.c.
 {
         u16 time;
         s32 result;
         int i, j;
         result = -1;
         for(i = 0; i < AlarmCount; i++)
         {
                 if(alarms[i].id == id)
                 {
                         if(alarms[i].target == *T3_COMP_W)
{
                                 if(*R_EE_I_STAT & (1 << INTC_TIM3))     //Cannot release alarm that has already triggered.
                                         return -1;
                         }
                         time = alarms[i].time;
                         //Move forward list.
                         for(j = i; j < AlarmCount - 1; j++)
                                 alarms[j] = alarms[j+1];
                         --AlarmCount;
                         AlarmStatus &= ~(1 << id);
                         if(i == 0)      //If the first alarm was released, update timer comparator.
                                 SetupTIM3(alarms[0].target);
                         if(AlarmCount == 0)     //Stop timer if there are no alarms left.
                                 *T3_MODE_W = Tn_MODE(3,0,0,0,0,1,0,0,0,0);
                         result = (CalculateTimeDiff(time, *T3_COUNT_W) - time);
                 }
         }
         EE_SYNC();
         return result;
 }
References AlarmCount, alarms, AlarmStatus, CalculateTimeDiff(), EE_SYNC, alarm::id, INTC_TIM3, R_EE_I_STAT, result, SetupTIM3(), T3_COMP_W, T3_COUNT_W, T3_MODE_W, alarm::target, alarm::time, time, and Tn_MODE.
Referenced by WaitSemaTimeout().
SetAlarm()
s32 SetAlarm (u16 time, void(*)(s32 dispatch_id, u16 time, void *common) callback, void * common)
Definition at line 149 of file alarm.c.
 {
         s32 result;
         result = SetAlarmInternal(time, callback, common);
         EE_SYNC();
         return result;
 }
References alarm::callback, alarm::common, EE_SYNC, result, SetAlarmInternal(), and time.
SetAlarmInternal()
static s32 SetAlarmInternal (u16 time, void(*)(s32 dispatch_id, u16 time, void *common) callback, void * common) static
Definition at line 68 of file alarm.c.
 {
         void *gp;
         u32 target, now;
         struct alarm *alarm;
         int i, alarmID, pos;
         now = *T3_COUNT_W;
         target = now + time;
         if(AlarmCount >= MAX_ALARMS)
                 return -1;
         alarmID = -1;
         for(i = 0; i < MAX_ALARMS; i++)
         {
                 if(((AlarmStatus >> i) & 1) == 0)
                 {
                         AlarmStatus |= (1 << i);
                         alarmID = i;
                         break;
                 }
         }
         if(alarmID < 0)
                 return alarmID;
         gp = GetGP();
         pos = InsertAlarm(now, target);
         alarm = &alarms[pos];
         alarm->time = time;
         alarm->target = (u16)target;
         alarm->id = alarmID;
         alarm->gp = gp;
         alarm->callback = callback;
         alarm->common = common;
         AlarmCount++;
         SetupTIM3(alarms[0].target);
         return alarm->id;
 }
References AlarmCount, alarms, AlarmStatus, alarm::callback, alarm::common, GetGP(), gp, alarm::gp, alarm::id, InsertAlarm(), MAX_ALARMS, pos, SetupTIM3(), T3_COUNT_W, alarm::target, alarm::time, and time.
Referenced by SetAlarm().
SetupTIM3()
static void SetupTIM3 (u16 ticks) static
Definition at line 159 of file alarm.c.
 {
         *T3_COMP_W = ticks;
         EE_SYNC();
         *T3_MODE_W = Tn_MODE(3,0,0,0,0,1,1,0,1,0);
 }
References EE_SYNC, T3_COMP_W, T3_MODE_W, and Tn_MODE.
Referenced by Intc12Handler(), ReleaseAlarm(), and SetAlarmInternal().
Variable Documentation
AlarmCount
int AlarmCount = 0 static
Definition at line 24 of file alarm.c.
Referenced by InsertAlarm(), Intc12Handler(), ReleaseAlarm(), and SetAlarmInternal().
alarms
struct alarm alarms[MAX_ALARMS] static
Definition at line 25 of file alarm.c.
Referenced by InsertAlarm(), Intc12Handler(), ReleaseAlarm(), and SetAlarmInternal().
AlarmStatus
u64 AlarmStatus = 0 static
Definition at line 25 of file alarm.c.
Referenced by Intc12Handler(), ReleaseAlarm(), and SetAlarmInternal().