ps2sdk: NetManNetProtStack Struct Reference
NetManNetProtStack Struct Reference
#include <netman.h>
Data Fields
void(* LinkStateUp)(void)
void(* LinkStateDown)(void)
void *(* AllocRxPacket)(unsigned int size, void **payload)
void(* FreeRxPacket)(void *packet)
void(* EnQRxPacket)(void *packet)
int(* NextTxPacket)(void **payload)
void(* DeQTxPacket)(void)
int(* AfterTxPacket)(void **payload)
void(* ReallocRxPacket)(void *packet, unsigned int size)
Detailed Description
Definition at line 16 of file netman.h.
Field Documentation
AfterTxPacket
int(* NetManNetProtStack::AfterTxPacket) (void **payload)
Definition at line 24 of file netman.h.
Referenced by NetManTxPacketAfter().
AllocRxPacket
void*(* NetManNetProtStack::AllocRxPacket) (unsigned int size, void **payload)
Definition at line 19 of file netman.h.
Referenced by NetManNetProtStackAllocRxPacket().
DeQTxPacket
void(* NetManNetProtStack::DeQTxPacket) (void)
Definition at line 23 of file netman.h.
Referenced by NetManTxPacketDeQ().
EnQRxPacket
void(* NetManNetProtStack::EnQRxPacket) (void *packet)
Definition at line 21 of file netman.h.
Referenced by NetManNetProtStackEnQRxPacket().
FreeRxPacket
void(* NetManNetProtStack::FreeRxPacket) (void *packet)
Definition at line 20 of file netman.h.
Referenced by NetManNetProtStackFreeRxPacket().
LinkStateDown
void(* NetManNetProtStack::LinkStateDown) (void)
Definition at line 18 of file netman.h.
Referenced by NetManUpdateStackNIFLinkState().
LinkStateUp
void(* NetManNetProtStack::LinkStateUp) (void)
Definition at line 17 of file netman.h.
Referenced by NetManUpdateStackNIFLinkState().
NextTxPacket
int(* NetManNetProtStack::NextTxPacket) (void **payload)
Definition at line 22 of file netman.h.
Referenced by NetManTxPacketNext().
ReallocRxPacket
void(* NetManNetProtStack::ReallocRxPacket) (void *packet, unsigned int size)
Definition at line 25 of file netman.h.
Referenced by NetManNetProtStackReallocRxPacket().
The documentation for this struct was generated from the following file:
common/include/netman.h