ps2sdk: smem_buf Struct Reference
smem_buf Struct Reference
#include <common.h>
Data Fields
union {
u8 bytes [SMEM_BUF_SIZE/sizeof(u8)]
u32 words [SMEM_BUF_SIZE/sizeof(u32)]
smod_mod_info_t mod_info
slib_exp_lib_t exp_lib
};
Detailed Description
Definition at line 3 of file common.h.
Field Documentation
union { ... }
bytes
u8 smem_buf::bytes[SMEM_BUF_SIZE/sizeof(u8)]
Definition at line 5 of file common.h.
Referenced by sbv_patch_enable_lmb(), slib_exp_lib_list(), slib_get_exp_lib(), smem_write_word(), smod_get_mod_by_name(), and smod_get_next_mod().
exp_lib
slib_exp_lib_t smem_buf::exp_lib
Definition at line 8 of file common.h.
Referenced by slib_get_exp_lib().
mod_info
smod_mod_info_t smem_buf::mod_info
Definition at line 7 of file common.h.
Referenced by slib_exp_lib_list(), and smod_get_next_mod().
words
u32 smem_buf::words[SMEM_BUF_SIZE/sizeof(u32)]
Definition at line 6 of file common.h.
Referenced by sbv_patch_enable_lmb(), and slib_exp_lib_list().
The documentation for this struct was generated from the following file:
ee/sbv/src/common.h