ps2sdk: ee/libgs/src/sync.c File Reference
sync.c File Reference
#include <errno.h>
#include <stdio.h>
#include <kernel.h>
#include <libgs.h>
#include "internal.h"
Functions
void GsDrawSync (int mode)
void GsHSync (int mode)
void GsVSync (int mode)
Function Documentation
GsDrawSync()
void GsDrawSync (int mode)
Definition at line 18 of file sync.c.
 {
         switch(mode)
         {
         case 0:
         default:
                 GsDmaWait();
         }
 }
References GsDmaWait(), and mode.
Referenced by main().
GsHSync()
void GsHSync (int mode)
Definition at line 28 of file sync.c.
 {
         unsigned short i;
         switch(mode)
         {
         case 0:
                 GS_SET_CSR_hsync_intrupt(1);
                 while(!GS_GET_CSR_hsync_intrupt);
         break;
         default:
                 if(mode>1)
                 {
                         for(i=0;i<mode;i++)
{
                                 GS_SET_CSR_hsync_intrupt(1);
                                 while(!GS_GET_CSR_hsync_intrupt);
                         }
                 }
         }
 }
References GS_GET_CSR_hsync_intrupt, GS_SET_CSR_hsync_intrupt, and mode.
GsVSync()
void GsVSync (int mode)
Definition at line 50 of file sync.c.
 {
         unsigned short i;
         switch(mode)
         {
         case 0: //just wait
                 GS_SET_CSR_vsync_intrupt(1);
                 while(!GS_GET_CSR_vsync_intrupt);
         break;
         default: // wait for num of vsync to pass
                 if(mode>1)
                 {
                         for(i=0;i<mode;i++)
{
                                 GS_SET_CSR_vsync_intrupt(1);
                                 while(!GS_GET_CSR_vsync_intrupt);
                         }
                 }
         }
 }
References GS_GET_CSR_vsync_intrupt, GS_SET_CSR_vsync_intrupt, and mode.
Referenced by main().