ps2sdk: ee/libgs/src/Zbuffer.c File Reference
Zbuffer.c File Reference
#include <errno.h>
#include <stdio.h>
#include <kernel.h>
#include <libgs.h>
#include "internal.h"
Functions
void GsSetDefaultZBufferEnv (GS_ZENV *zenv, u8 update_mask)
void GsSetDefaultZBufferEnvAddress (GS_ZENV *zenv, unsigned short vram_addr, unsigned char psm)
void GsPutZBufferEnv1 (GS_ZENV *zenv)
void GsPutZBufferEnv2 (GS_ZENV *zenv)
Variables
QWORD GsPrimWorkArea []
Function Documentation
GsPutZBufferEnv1()
void GsPutZBufferEnv1 (GS_ZENV * zenv)
Definition at line 31 of file Zbuffer.c.
 {
         QWORD *p;
         p=UNCACHED_SEG(GsPrimWorkArea);
         gs_setGIF_TAG(((GS_GIF_TAG *)&p[0]), 1,1,0,0,GS_GIF_PACKED,1,gif_rd_ad);
         gs_setR_ZBUF_1(((GS_R_ZBUF *)&p[1]), zenv->vram_addr, zenv->psm, zenv->update_mask);
         GsDmaSend(GsPrimWorkArea, 2);
         GsDmaWait();
 }
References gif_rd_ad, GS_GIF_PACKED, gs_setGIF_TAG, gs_setR_ZBUF_1, GsDmaSend(), GsDmaWait(), GsPrimWorkArea, GS_ZENV::psm, UNCACHED_SEG, GS_ZENV::update_mask, and GS_ZENV::vram_addr.
GsPutZBufferEnv2()
void GsPutZBufferEnv2 (GS_ZENV * zenv)
Definition at line 42 of file Zbuffer.c.
 {
         QWORD *p;
         p=UNCACHED_SEG(GsPrimWorkArea);
         gs_setGIF_TAG(((GS_GIF_TAG *)&p[0]), 4,1,0,0,GS_GIF_PACKED,1,gif_rd_ad);
         gs_setR_ZBUF_2(((GS_R_ZBUF *)&p[1]), zenv->vram_addr, zenv->psm, zenv->update_mask);
         GsDmaSend(GsPrimWorkArea, 2);
         GsDmaWait();
 }
References gif_rd_ad, GS_GIF_PACKED, gs_setGIF_TAG, gs_setR_ZBUF_2, GsDmaSend(), GsDmaWait(), GsPrimWorkArea, GS_ZENV::psm, UNCACHED_SEG, GS_ZENV::update_mask, and GS_ZENV::vram_addr.
GsSetDefaultZBufferEnv()
void GsSetDefaultZBufferEnv (GS_ZENV * zenv, u8 update_mask)
Definition at line 20 of file Zbuffer.c.
 {
         zenv->update_mask = update_mask;
 }
References GS_ZENV::update_mask.
GsSetDefaultZBufferEnvAddress()
void GsSetDefaultZBufferEnvAddress (GS_ZENV * zenv, unsigned short vram_addr, unsigned char psm)
Definition at line 25 of file Zbuffer.c.
 {
         zenv->vram_addr=vram_addr;
         zenv->psm=psm;
 }
References GS_ZENV::psm, and GS_ZENV::vram_addr.
Variable Documentation
GsPrimWorkArea
QWORD GsPrimWorkArea[] extern
Definition at line 18 of file packets.c.
Referenced by GsPutZBufferEnv1(), and GsPutZBufferEnv2().