ps2sdk: iop/sound/audsrv/src/adpcm.c File Reference
adpcm.c File Reference
#include <stdio.h>
#include <thbase.h>
#include <thsemap.h>
#include <loadcore.h>
#include <sysmem.h>
#include <intrman.h>
#include <libsd.h>
#include <sysclib.h>
#include <audsrv.h>
#include "audsrv_internal.h"
#include "common.h"
#include "rpc_server.h"
#include "spu.h"
Data Structures
struct adpcm_list_t
Functions
static adpcm_list_t * alloc_new_sample (void)
static void free_all_samples ()
static adpcm_list_t * adpcm_loaded (int id)
static void audsrv_read_adpcm_header (adpcm_list_t *adpcm, u32 *buffer)
void * audsrv_load_adpcm (u32 *buffer, int size, int id)
static int audsrv_adpcm_alloc_channel (void)
int audsrv_ch_play_adpcm (int ch, u32 id)
int audsrv_adpcm_init ()
int audsrv_adpcm_set_volume (int ch, int vol)
Variables
static adpcm_list_t * adpcm_list_head = 0
static adpcm_list_t * adpcm_list_tail = 0
static u32 sbuffer [16]
Detailed Description
audsrv adpcm module
Definition in file adpcm.c.
Function Documentation
adpcm_loaded()
static adpcm_list_t* adpcm_loaded (int id) static
Looks up the given identifier in list of loaded samples
Parameters
id sample identifier
Returns
node entry from container, NULL on failure
Definition at line 82 of file adpcm.c.
 {
         adpcm_list_t *cur = adpcm_list_head;
         while (cur != 0)
         {
                 if (cur->id == id)
                 {
                         return cur;
                 }
                 cur = cur->next;
         }
         return NULL;
 }
References adpcm_list_head, adpcm_list_t::id, adpcm_list_t::next, and NULL.
Referenced by audsrv_ch_play_adpcm(), and audsrv_load_adpcm().
alloc_new_sample()
static adpcm_list_t* alloc_new_sample (void) static
Allocates memory for a new sample.
Definition at line 48 of file adpcm.c.
 {
         void *buffer;
         int OldState;
         CpuSuspendIntr(&OldState);
         buffer = AllocSysMemory(ALLOC_FIRST, sizeof(adpcm_list_t), NULL);
         CpuResumeIntr(OldState);
         return buffer;
 }
References ALLOC_FIRST, AllocSysMemory(), buffer, CpuResumeIntr(), CpuSuspendIntr(), and NULL.
Referenced by audsrv_load_adpcm().
audsrv_adpcm_alloc_channel()
static int audsrv_adpcm_alloc_channel (void) static
Definition at line 164 of file adpcm.c.
 {
         int i, channel;
         u32 endx;
         endx = sceSdGetSwitch(SD_CORE_1 | SD_SWITCH_ENDX);
         if (endx == 0)
         {
                 /* all channels are occupied */
                 return -AUDSRV_ERR_NO_MORE_CHANNELS;
         }
         /* find first channel available */
         i = 1;
         channel = -1;
         while ((channel < 0) && (i < 24))
         {
                 if (endx & (1 << i))
                 {
                         channel = i;
                 }
                 i++;
         }
         if (channel == -1)
         {
                 /* cannot find a single channel free */
                 return -AUDSRV_ERR_NO_MORE_CHANNELS;
         }
         return channel;
 }
References AUDSRV_ERR_NO_MORE_CHANNELS, sceSdGetSwitch(), SD_CORE_1, and SD_SWITCH_ENDX.
Referenced by audsrv_ch_play_adpcm().
audsrv_adpcm_init()
int audsrv_adpcm_init ()
Initializes adpcm unit of audsrv
Returns
zero on success, negative value on error
Definition at line 250 of file adpcm.c.
 {
         int voice;
         printf("audsrv_adpcm_init()\n");
         for (voice = 0; voice < 24; voice++)
         {
                 sceSdSetSwitch(SD_CORE_1 | SD_SWITCH_KOFF, (1 << voice));
                 sceSdSetParam(SD_CORE_1 | (voice << 1) | SD_VPARAM_VOLL, 0x3fff);
                 sceSdSetParam(SD_CORE_1 | (voice << 1) | SD_VPARAM_VOLR, 0x3fff);
         }
         if (adpcm_list_head != NULL)
         {
                 /* called second time, after samples were already uploaded */
                 free_all_samples();
         }
         return AUDSRV_ERR_NOERROR;
 }
References adpcm_list_head, AUDSRV_ERR_NOERROR, free_all_samples(), NULL, printf(), sceSdSetParam(), sceSdSetSwitch(), SD_CORE_1, SD_SWITCH_KOFF, SD_VPARAM_VOLL, and SD_VPARAM_VOLR.
Referenced by _start(), audsrv_quit(), and rpc_command().
audsrv_adpcm_set_volume()
int audsrv_adpcm_set_volume (int ch, int vol)
Sets output volume for the specified voice channel.
Parameters
ch Voice channel ID
vol volume in SPU2 units [0 .. 0x3fff]
Returns
0 on success, negative otherwise
Definition at line 277 of file adpcm.c.
 {
         if (vol < 0 || vol > MAX_VOLUME)
         {
                 /* bad joke */
                 return AUDSRV_ERR_ARGS;
         }
         sceSdSetParam(SD_CORE_1 | (ch << 1) | SD_VPARAM_VOLL, vol);
         sceSdSetParam(SD_CORE_1 | (ch << 1) | SD_VPARAM_VOLR, vol);
         return AUDSRV_ERR_NOERROR;
 }
References AUDSRV_ERR_ARGS, AUDSRV_ERR_NOERROR, MAX_VOLUME, sceSdSetParam(), SD_CORE_1, SD_VPARAM_VOLL, and SD_VPARAM_VOLR.
Referenced by rpc_command().
audsrv_ch_play_adpcm()
int audsrv_ch_play_adpcm (int ch, u32 id)
Plays an adpcm sample already uploaded with audsrv_load_adpcm()
Parameters
ch channel identifier. Specifies one of the 24 voice channel to play the ADPCM channel on. If set to an invalid channel ID, an unoccupied channel will be selected.
id sample identifier, as specified in load()
Returns
zero on success, negative value on error
When ch is set to an invalid channel ID, the sample will be played in an unoccupied channel. If all 24 channels are used, then -AUDSRV_ERR_NO_MORE_CHANNELS is returned. When ch is set to a valid channel ID, -AUDSRV_ERR_NO_MORE_CHANNELS is returned if the channel is currently in use. Trying to play a sample which is unavailable will result in -AUDSRV_ERR_ARGS
Definition at line 208 of file adpcm.c.
 {
         int channel;
         u32 endx;
         adpcm_list_t *a;
         a = adpcm_loaded(id);
         if (a == NULL)
         {
                 /* bad joke */
                 return AUDSRV_ERR_ARGS;
         }
         /* sample was loaded */
         if (ch >= 0 && ch < 24)
         {
                 endx = sceSdGetSwitch(SD_CORE_1 | SD_SWITCH_ENDX);
                 if (!(endx & (1 << ch)))
                 {
                         /* Channel in use. */
                         return -AUDSRV_ERR_NO_MORE_CHANNELS;
                 }
                 channel = ch;
         }
         else
         {
                 channel = audsrv_adpcm_alloc_channel();
                 if (channel < 0)
                         return channel;
         }
         sceSdSetParam(SD_CORE_1 | (channel << 1) | SD_VPARAM_PITCH, a->pitch);
         sceSdSetAddr(SD_CORE_1 | (channel << 1) | SD_VOICE_START, a->spu2_addr);
         sceSdSetSwitch(SD_CORE_1 | SD_SWITCH_KON, (1 << channel));
         return AUDSRV_ERR_NOERROR;
 }
References adpcm_loaded(), audsrv_adpcm_alloc_channel(), AUDSRV_ERR_ARGS, AUDSRV_ERR_NO_MORE_CHANNELS, AUDSRV_ERR_NOERROR, NULL, adpcm_list_t::pitch, sceSdGetSwitch(), sceSdSetAddr(), sceSdSetParam(), sceSdSetSwitch(), SD_CORE_1, SD_SWITCH_ENDX, SD_SWITCH_KON, SD_VOICE_START, SD_VPARAM_PITCH, and adpcm_list_t::spu2_addr.
Referenced by rpc_command().
audsrv_load_adpcm()
void* audsrv_load_adpcm (u32 * buffer, int size, int id)
Uploads a sample to SPU2 memory
Parameters
buffer pointer to adpcm sample header
size size of sample in bytes
id sample identifier (to be later used in play())
Returns
pointer to local adpcm buffer
Definition at line 116 of file adpcm.c.
 {
         adpcm_list_t *adpcm;
         adpcm = adpcm_loaded(id);
         if (adpcm == NULL)
         {
                 if (adpcm_list_head == NULL)
                 {
                         /* first entry ever! yay! */
                         adpcm = alloc_new_sample();
                         adpcm->id = id;
                         adpcm->spu2_addr = 0x5010; /* Need to change this so it considers to PCM streaming space usage :) */
                         adpcm->size = size - 16; /* header is 16 bytes */
                         adpcm->next = NULL;
                         audsrv_read_adpcm_header(adpcm, buffer);
                         adpcm_list_head = adpcm;
                         adpcm_list_tail = adpcm_list_head;
                 }
                 else
                 {
                         /* add at the end of the list */
                         adpcm = alloc_new_sample();
                         adpcm->id = id;
                         adpcm->spu2_addr = adpcm_list_tail->spu2_addr + adpcm_list_tail->size;
                         adpcm->size = size - 16; /* header is 16 bytes */
                         adpcm->next = NULL;
                         audsrv_read_adpcm_header(adpcm, buffer);
                         adpcm_list_tail->next = adpcm;
                         adpcm_list_tail = adpcm;
                 }
                 /* DMA from IOP to SPU2 */
                 sceSdVoiceTrans(AUDSRV_VOICE_DMA_CH, SD_TRANS_WRITE | SD_TRANS_MODE_DMA, ((u8*)buffer)+16, (u32*)adpcm->spu2_addr, adpcm->size);
                 sceSdVoiceTransStatus(AUDSRV_VOICE_DMA_CH, 1);
         }
         sbuffer[0] = 0;
         sbuffer[1] = adpcm->pitch;
         sbuffer[2] = adpcm->loop;
         sbuffer[3] = adpcm->channels;
         return sbuffer;
 }
References adpcm_list_head, adpcm_list_tail, adpcm_loaded(), alloc_new_sample(), audsrv_read_adpcm_header(), AUDSRV_VOICE_DMA_CH, buffer, adpcm_list_t::channels, adpcm_list_t::id, adpcm_list_t::loop, adpcm_list_t::next, NULL, adpcm_list_t::pitch, sbuffer, sceSdVoiceTrans(), sceSdVoiceTransStatus(), SD_TRANS_MODE_DMA, SD_TRANS_WRITE, adpcm_list_t::size, and adpcm_list_t::spu2_addr.
Referenced by rpc_command().
audsrv_read_adpcm_header()
static void audsrv_read_adpcm_header (adpcm_list_t * adpcm, u32 * buffer) static
Extracts adpcm parameters from header
Parameters
adpcm node entry
buffer pointer to adpcm header
Definition at line 103 of file adpcm.c.
 {
         adpcm->pitch = buffer[2];
         adpcm->loop = (buffer[1] >> 16) & 0xFF;
         adpcm->channels = (buffer[1] >> 8) & 0xFF;
 }
References buffer, adpcm_list_t::channels, adpcm_list_t::loop, and adpcm_list_t::pitch.
Referenced by audsrv_load_adpcm().
free_all_samples()
static void free_all_samples () static
Frees up all memory taken by the linked list of samples
Definition at line 61 of file adpcm.c.
 {
         adpcm_list_t *p, *q;
         int OldState;
         CpuSuspendIntr(&OldState);
         for (p = adpcm_list_head; p != NULL; p = q)
         {
                 q = p->next;
                 FreeSysMemory(p);
         }
         adpcm_list_head = NULL;
         adpcm_list_tail = NULL;
         CpuResumeIntr(OldState);
 }
References adpcm_list_head, adpcm_list_tail, CpuResumeIntr(), CpuSuspendIntr(), FreeSysMemory(), adpcm_list_t::next, and NULL.
Referenced by audsrv_adpcm_init().
Variable Documentation
adpcm_list_head
adpcm_list_t* adpcm_list_head = 0 static
Definition at line 42 of file adpcm.c.
Referenced by adpcm_loaded(), audsrv_adpcm_init(), audsrv_load_adpcm(), and free_all_samples().
adpcm_list_tail
adpcm_list_t* adpcm_list_tail = 0 static
Definition at line 43 of file adpcm.c.
Referenced by audsrv_load_adpcm(), and free_all_samples().
sbuffer
u32 sbuffer[16] static
Definition at line 45 of file adpcm.c.
Referenced by audsrv_load_adpcm().