ps2sdk: iop/sound/ps2snd/src/adpcm-stream.c File Reference
adpcm-stream.c File Reference
#include <types.h>
#include <irx.h>
#include <sifrpc.h>
#include <loadcore.h>
#include <stdio.h>
#include <libsd.h>
#include <thbase.h>
#include <intrman.h>
#include <sysmem.h>
#include <ioman.h>
#include <thsemap.h>
#include <ps2snd.h>
#include "mod.h"
Macros
#define FLAG_STEREO 0x1
#define FLAG_BUFID 0x10000
#define STATUS_CLOSED 0
#define STATUS_OPEN 1
#define STATUS_PLAYING 2
#define STATUS_ERROR 3
#define stream_endflag (stream_flags&0xF000)
#define stream_bufsafe (1-stream_bufid)
Functions
static void setloopflags (int id, u8 *buf, int len)
int fillbuf (int id, int chan)
void stream_thread (void *a)
int stream_handler (int core, void *data)
int sndStreamOpen (char *file, u32 voices, u32 flags, u32 bufaddr, u32 bufsize)
int sndStreamClose (void)
int sndStreamPlay (void)
int sndStreamPause (void)
int sndStreamSetPosition (int block)
int sndStreamGetPosition (void)
int sndStreamSetVolume (int left, int right)
Variables
static u32 stream_flags =0
static int stream_sema =-1
static int stream_thid =-1
static int stream_fd
static u32 stream_bufid
static int stream_cur
static int stream_status
static u8 * stream_buf
static u32 stream_chans
static u32 stream_buflen
static u32 stream_bufspu [2]
static u32 stream_voice [2]
Macro Definition Documentation
FLAG_BUFID
#define FLAG_BUFID 0x10000
Definition at line 26 of file adpcm-stream.c.
FLAG_STEREO
#define FLAG_STEREO 0x1
Definition at line 25 of file adpcm-stream.c.
STATUS_CLOSED
#define STATUS_CLOSED 0
Definition at line 27 of file adpcm-stream.c.
STATUS_ERROR
#define STATUS_ERROR 3
Definition at line 30 of file adpcm-stream.c.
STATUS_OPEN
#define STATUS_OPEN 1
Definition at line 28 of file adpcm-stream.c.
STATUS_PLAYING
#define STATUS_PLAYING 2
Definition at line 29 of file adpcm-stream.c.
stream_bufsafe
#define stream_bufsafe (1-stream_bufid)
Definition at line 44 of file adpcm-stream.c.
stream_endflag
#define stream_endflag (stream_flags&0xF000)
Definition at line 32 of file adpcm-stream.c.
Function Documentation
fillbuf()
int fillbuf (int id, int chan)
Definition at line 80 of file adpcm-stream.c.
 {
         u8 *buf = stream_buf;
         int size;
         id &= 1;
         size = read(stream_fd, buf, stream_buflen);
         if (size<0)  /* Error */
         {
                 dprintf(OUT_ERROR, "Channel%d: error: %d\n", chan,  size);
                 return(-1);
         }
         if (size==0)
                 return(0);   /* EOF */
         /* If we're stereo and we've read less than a chunk, we're screwed  */
         if ((stream_chans>1) && (size<stream_buflen))
         {
                 dprintf(OUT_ERROR, "Channel%d: failed to read entire chunk (read %d bytes)\n", chan, size);
                 return(-1);
         }
         setloopflags(id, buf, size);
         sceSdVoiceTrans(0, SD_TRANS_WRITE | SD_TRANS_MODE_DMA, buf, (u32*)(stream_bufspu[chan]+(id*stream_buflen)), size);
         sceSdVoiceTransStatus(0, 1);
         return(size);
 }
References dprintf, OUT_ERROR, read(), sceSdVoiceTrans(), sceSdVoiceTransStatus(), SD_TRANS_MODE_DMA, SD_TRANS_WRITE, setloopflags(), stream_buf, stream_buflen, stream_bufspu, stream_chans, and stream_fd.
Referenced by sndStreamSetPosition(), and stream_thread().
setloopflags()
static void setloopflags (int id, u8 * buf, int len) inline static
Definition at line 53 of file adpcm-stream.c.
 {
         /* XXX: double check these numbers */
         /* Set loop flags */
         for (int i=0;i<len;i+=16)
         {
 //              if (buf[i+1] == 0)
 //              {
                         if (id == 0 && i==0)
                                 buf[i+1] = 6; /* Set 'repeat start' when at the begining of buf0 */
                         else if (id == 1 && ((i+16)>=len))
                                 buf[i+1] = 3; /* Set 'repeat from begining' when at the end of buf1 */
                         else
                                 buf[i+1] = 2; /* Set 'in repeat section' when elsewhere */
 //              }
         }
 }
Referenced by fillbuf().
sndStreamClose()
int sndStreamClose (void)
Definition at line 269 of file adpcm-stream.c.
 {
         if (stream_status==STATUS_PLAYING)
                 sndStreamPause();
         if (stream_status==STATUS_CLOSED)
                 return(-1);
         if (stream_thid>=0)
                 DeleteThread(stream_thid);
         close(stream_fd);
         FreeSysMemory(stream_buf);
         sceSdSetSpu2IntrHandler(NULL, NULL);
         stream_status = STATUS_CLOSED;
         dprintf(OUT_INFO, "Closed!\n");
         return(0);
 }
References close(), DeleteThread(), dprintf, FreeSysMemory(), NULL, OUT_INFO, sceSdSetSpu2IntrHandler(), sndStreamPause(), STATUS_CLOSED, STATUS_PLAYING, stream_buf, stream_fd, stream_status, and stream_thid.
Referenced by rpc_server(), sndStreamOpen(), sndStreamSetPosition(), and stream_thread().
sndStreamGetPosition()
int sndStreamGetPosition (void)
Definition at line 378 of file adpcm-stream.c.
 {
         int i;
         if (stream_status==STATUS_CLOSED)
                 return(-1);
         if (stream_status==STATUS_OPEN)
                 return(stream_cur);
         /* During playback we can get the current position in the buffer from the SPU2! */
         i = sceSdGetAddr(stream_voice[0] | SD_VADDR_NAX);
         i -= stream_bufspu[0]+(stream_buflen*stream_bufid);
         i /= 16;
         return(stream_cur+i);
 }
References sceSdGetAddr(), SD_VADDR_NAX, STATUS_CLOSED, STATUS_OPEN, stream_bufid, stream_buflen, stream_bufspu, stream_cur, stream_status, and stream_voice.
Referenced by rpc_server().
sndStreamOpen()
int sndStreamOpen (char * file, u32 voices, u32 flags, u32 bufaddr, u32 bufsize)
Definition at line 149 of file adpcm-stream.c.
 {
         iop_thread_t thread;
         dprintf(OUT_DEBUG, "%s\n", file);
         if (stream_status)
         {
                 dprintf(OUT_WARNING, "There's a stream already open\n");
                 return(-1);
         }
         stream_voice[0] = voices&0xffff;
         stream_voice[1] = (voices>>16)&0xffff;
         dprintf(OUT_INFO, "%s  Voices %d:%d and %d:%d\n", file, (int)stream_voice[0]&1, (int)stream_voice[0]>>1, (int)stream_voice[1]&1, (int)stream_voice[1]>>1);
         if ((stream_voice[0]&1) != (stream_voice[1]&1))
         {
                 dprintf(OUT_ERROR, "Stream voices arn't on the same core!!!!\n");
                 return(-1);
         }
         /* Setup Semaphore */
         if (stream_sema<0)
         {
                 iop_sema_t sema;
                 sema.attr = 0;
                 sema.option = 0;
                 sema.initial = 0;
                 sema.max = 1;
                 stream_sema = CreateSema(&sema);
                 if (stream_sema<0)
                         dprintf(OUT_ERROR, "Failed to get a semaphore\n");
         }
         stream_buflen = bufsize*16;
         stream_flags = flags&0xffff; /* only the bottom 16bits are for user use! */
         stream_buf = AllocSysMemory(ALLOC_FIRST, stream_buflen, NULL);
         if (stream_buf==NULL)
         {
                 dprintf(OUT_ERROR, "malloc failed (%u bytes)\n", (unsigned int)stream_buflen);
                 return(-2);
         }
         /* Try to open file... */
         stream_fd = open(file, O_RDONLY);
         if (stream_fd<0)
         {
                 dprintf(OUT_ERROR, "open failed (%d)\n", stream_fd);
                 FreeSysMemory(stream_buf);
                 return(-3);
         }
         stream_bufspu[0] = bufaddr;
         stream_bufspu[1] = bufaddr + (stream_buflen*2);
         /* Setup SPU2 voice volumes.... */
         if (stream_flags&FLAG_STEREO)
         {
                 dprintf(OUT_INFO, "stereo...\n");
                 stream_chans = 2;
                 sceSdSetParam(stream_voice[0] | SD_VPARAM_VOLL,  0x1fff);
                 sceSdSetParam(stream_voice[0] | SD_VPARAM_VOLR,  0);
                 sceSdSetParam(stream_voice[1] | SD_VPARAM_VOLL,  0);
                 sceSdSetParam(stream_voice[1] | SD_VPARAM_VOLR,  0x1fff);
         }
         else
         {
                 dprintf(OUT_INFO, "mono...\n");
                 stream_chans = 1;
                 sceSdSetParam(stream_voice[0] | SD_VPARAM_VOLL,  0x1fff);
                 sceSdSetParam(stream_voice[0] | SD_VPARAM_VOLR,  0x1fff);
         }
         /* Setup other SPU2 voice stuff... */
         for (int i=0;i<stream_chans;i++) /* XXX */
         {
                 sceSdSetParam(stream_voice[i] | SD_VPARAM_PITCH, 0x1000); /* 0x1000 = normal pitch */
                 sceSdSetParam(stream_voice[i] | SD_VPARAM_ADSR1, SD_SET_ADSR1(SD_ADSR_AR_EXPi, 0, 0xf, 0xf));
                 sceSdSetParam(stream_voice[i] | SD_VPARAM_ADSR2, SD_SET_ADSR2(SD_ADSR_SR_EXPd, 127, SD_ADSR_RR_EXPd, 0));
         }
         /* Get a thread */
         thread.attr      = TH_C;
         thread.thread    = stream_thread;
         thread.priority  = 40;
         thread.stacksize = 0x800;
         thread.option    = 0;
         stream_thid = CreateThread(&thread);
         if (stream_thid<0)
         {
                 dprintf(OUT_ERROR, "Failed to make play thread\n");
                 sndStreamClose();
                 return(-1);
         }
         /* Start the thread (it'll wait patiently until it gets an interrupt) */
         StartThread(stream_thid, NULL);
         /* Get some interrupts going! */
         sceSdSetCoreAttr(SD_CORE_IRQ_ENABLE, 0); /* disable pesky interrupts for a minute */
         sceSdSetSpu2IntrHandler(stream_handler, (void*)1);
         stream_status = STATUS_OPEN;
         stream_cur = 0;
         if (sndStreamSetPosition(0)<0)
         {
                 sndStreamClose();
                 return(-1);
         }
         dprintf(OUT_INFO, "Opened %s\n", file);
         return(0);
 }
References ALLOC_FIRST, AllocSysMemory(), iop_thread_t::attr, iop_sema_t::attr, CreateSema(), CreateThread(), dprintf, FLAG_STEREO, FreeSysMemory(), iop_sema_t::initial, iop_sema_t::max, NULL, O_RDONLY, open(), iop_thread_t::option, iop_sema_t::option, OUT_DEBUG, OUT_ERROR, OUT_INFO, OUT_WARNING, iop_thread_t::priority, sceSdSetCoreAttr(), sceSdSetParam(), sceSdSetSpu2IntrHandler(), SD_ADSR_AR_EXPi, SD_ADSR_RR_EXPd, SD_ADSR_SR_EXPd, SD_CORE_IRQ_ENABLE, SD_SET_ADSR1, SD_SET_ADSR2, SD_VPARAM_ADSR1, SD_VPARAM_ADSR2, SD_VPARAM_PITCH, SD_VPARAM_VOLL, SD_VPARAM_VOLR, sndStreamClose(), sndStreamSetPosition(), iop_thread_t::stacksize, StartThread(), STATUS_OPEN, stream_buf, stream_buflen, stream_bufspu, stream_chans, stream_cur, stream_fd, stream_flags, stream_handler(), stream_sema, stream_status, stream_thid, stream_thread(), stream_voice, TH_C, and iop_thread_t::thread.
Referenced by rpc_server().
sndStreamPause()
int sndStreamPause (void)
Definition at line 313 of file adpcm-stream.c.
 {
         if (stream_status==STATUS_CLOSED)
                 return(-1);
         if (stream_status==STATUS_OPEN)
                 return(0);
         /* Release keys */
         if (stream_chans>1)
                 sceSdSetSwitch((stream_voice[0]&1) | SD_SWITCH_KEYUP, 1<<(stream_voice[0]>>1) | 1<<(stream_voice[1]>>1));
         else
                 sceSdSetSwitch((stream_voice[0]&1) | SD_SWITCH_KEYUP, 1<<(stream_voice[0]>>1));
         sceSdSetCoreAttr(SD_CORE_IRQ_ENABLE, 0); /* disable pesky interrupts for a minute */
         stream_status=STATUS_OPEN;
         dprintf(OUT_INFO, "Paused!\n");
         return(1);
 }
References dprintf, OUT_INFO, sceSdSetCoreAttr(), sceSdSetSwitch(), SD_CORE_IRQ_ENABLE, SD_SWITCH_KEYUP, STATUS_CLOSED, STATUS_OPEN, stream_chans, stream_status, and stream_voice.
Referenced by rpc_server(), sndStreamClose(), and sndStreamSetPosition().
sndStreamPlay()
int sndStreamPlay (void)
Definition at line 291 of file adpcm-stream.c.
 {
         if (stream_status==STATUS_CLOSED)
                 return(-1);
         if (stream_status==STATUS_PLAYING)
                 return(0);
         /* Press down the keys :) */
         if (stream_chans>1)
                 sceSdSetSwitch((stream_voice[0]&1) | SD_SWITCH_KEYDOWN, 1<<(stream_voice[0]>>1) | 1<<(stream_voice[1]>>1));
         else
                 sceSdSetSwitch((stream_voice[0]&1) | SD_SWITCH_KEYDOWN, 1<<(stream_voice[0]>>1));
         sceSdSetCoreAttr(SD_CORE_IRQ_ENABLE, 1);
         stream_status=STATUS_PLAYING;
         dprintf(OUT_INFO, "Playing!\n");
         return(1);
 }
References dprintf, OUT_INFO, sceSdSetCoreAttr(), sceSdSetSwitch(), SD_CORE_IRQ_ENABLE, SD_SWITCH_KEYDOWN, STATUS_CLOSED, STATUS_PLAYING, stream_chans, stream_status, and stream_voice.
Referenced by rpc_server(), and sndStreamSetPosition().
sndStreamSetPosition()
int sndStreamSetPosition (int block)
Definition at line 334 of file adpcm-stream.c.
 {
         int chunk;
         int r=0;
         if (stream_status==STATUS_CLOSED)
                 return(-1);
         if (stream_status==STATUS_PLAYING)
                 r = sndStreamPause();
         if (block<0)
                 return(-2);
         /* lock block number to a chunk */
         chunk = (stream_buflen/16)*stream_chans;
         dprintf(OUT_DEBUG, "chunk = %d\n", chunk);
         block = (block/chunk)*chunk;
         stream_cur = block;
         lseek(stream_fd, block*16*stream_chans, SEEK_SET);
         stream_bufid = 0;
         sceSdSetAddr(SD_ADDR_IRQA, stream_bufspu[0]+stream_buflen);
         for (int i=0;i<2;i++)
         for (int c=0;c<stream_chans;c++)
         if (fillbuf(i, c)<=0)
                 {
                         dprintf(OUT_ERROR, "Hit EOF or error on buffer fill %d\n", i);
                         sndStreamClose();
                         return(-1);
                 }
         for (int c=0;c<stream_chans;c++)
                 sceSdSetAddr(stream_voice[c] | SD_VADDR_SSA, stream_bufspu[c]);
         /* Restart playing if we were playing before */
         if (r)
                 sndStreamPlay();
         dprintf(OUT_INFO, "Position %d!\n", stream_cur);
         return(block);
 }
References dprintf, fillbuf(), lseek(), OUT_DEBUG, OUT_ERROR, OUT_INFO, sceSdSetAddr(), SD_ADDR_IRQA, SD_VADDR_SSA, SEEK_SET, sndStreamClose(), sndStreamPause(), sndStreamPlay(), STATUS_CLOSED, STATUS_PLAYING, stream_bufid, stream_buflen, stream_bufspu, stream_chans, stream_cur, stream_fd, stream_status, and stream_voice.
Referenced by rpc_server(), and sndStreamOpen().
sndStreamSetVolume()
int sndStreamSetVolume (int left, int right)
Definition at line 395 of file adpcm-stream.c.
 {
         if (stream_status==STATUS_CLOSED)
                 return(-1);
         if (stream_chans>1)
         {
                 sceSdSetParam(stream_voice[0] | SD_VPARAM_VOLL,  left);
                 sceSdSetParam(stream_voice[0] | SD_VPARAM_VOLR,  0);
                 sceSdSetParam(stream_voice[1] | SD_VPARAM_VOLL,  0);
                 sceSdSetParam(stream_voice[1] | SD_VPARAM_VOLR,  right);
         }
         else
         {
                 sceSdSetParam(stream_voice[0] | SD_VPARAM_VOLL,  left);
                 sceSdSetParam(stream_voice[0] | SD_VPARAM_VOLR,  right);
         }
         return(0);
 }
References sceSdSetParam(), SD_VPARAM_VOLL, SD_VPARAM_VOLR, STATUS_CLOSED, stream_chans, stream_status, and stream_voice.
Referenced by rpc_server().
stream_handler()
int stream_handler (int core, void * data)
Definition at line 143 of file adpcm-stream.c.
 {
         iSignalSema(stream_sema);
         return(0); /* What should i return here? */
 }
References iSignalSema(), and stream_sema.
Referenced by sndStreamOpen().
stream_thread()
void stream_thread (void * a)
Definition at line 112 of file adpcm-stream.c.
 {
         while(1)
         {
                 /* Wait for an interrupt */
                 WaitSema(stream_sema);
                 /* Update stuff */
                 stream_bufid = stream_bufsafe;
                 stream_cur+=(stream_buflen/16);
                 dprintf(OUT_DEBUG, "SPU2 now playing buffer %d (block %d)\n", (int)stream_bufid, stream_cur);
                 /* Fill the buffer the SPU2 isn't playing */
                 for (int i=0;i<stream_chans;i++)
                 {
                         int r;
                         r = fillbuf(stream_bufsafe, i);
                         if (r<stream_buflen) /* treat EOF and errors as the same thing atm */
{
                                 sndStreamClose();
                                 return;
                         }
                 }
                 sceSdSetAddr(SD_ADDR_IRQA, stream_bufspu[0]+(stream_bufsafe*stream_buflen));
                 sceSdSetCoreAttr(SD_CORE_IRQ_ENABLE, 1);
         }
 }
References dprintf, fillbuf(), OUT_DEBUG, sceSdSetAddr(), sceSdSetCoreAttr(), SD_ADDR_IRQA, SD_CORE_IRQ_ENABLE, sndStreamClose(), stream_bufid, stream_buflen, stream_bufsafe, stream_bufspu, stream_chans, stream_cur, stream_sema, and WaitSema().
Referenced by sndStreamOpen().
Variable Documentation
stream_buf
u8* stream_buf static
Definition at line 47 of file adpcm-stream.c.
Referenced by fillbuf(), sndStreamClose(), and sndStreamOpen().
stream_bufid
u32 stream_bufid static
Definition at line 43 of file adpcm-stream.c.
Referenced by sndStreamGetPosition(), sndStreamSetPosition(), and stream_thread().
stream_buflen
u32 stream_buflen static
Definition at line 49 of file adpcm-stream.c.
Referenced by fillbuf(), sndStreamGetPosition(), sndStreamOpen(), sndStreamSetPosition(), and stream_thread().
stream_bufspu
u32 stream_bufspu[2] static
Definition at line 50 of file adpcm-stream.c.
Referenced by fillbuf(), sndStreamGetPosition(), sndStreamOpen(), sndStreamSetPosition(), and stream_thread().
stream_chans
u32 stream_chans static
Definition at line 48 of file adpcm-stream.c.
Referenced by fillbuf(), sndStreamOpen(), sndStreamPause(), sndStreamPlay(), sndStreamSetPosition(), sndStreamSetVolume(), and stream_thread().
stream_cur
int stream_cur static
Definition at line 45 of file adpcm-stream.c.
Referenced by sndStreamGetPosition(), sndStreamOpen(), sndStreamSetPosition(), and stream_thread().
stream_fd
int stream_fd static
Definition at line 42 of file adpcm-stream.c.
Referenced by fillbuf(), sndStreamClose(), sndStreamOpen(), and sndStreamSetPosition().
stream_flags
u32 stream_flags =0 static
Definition at line 40 of file adpcm-stream.c.
Referenced by sndStreamOpen().
stream_sema
int stream_sema =-1 static
Definition at line 41 of file adpcm-stream.c.
Referenced by sndStreamOpen(), stream_handler(), and stream_thread().
stream_status
int stream_status static
Definition at line 46 of file adpcm-stream.c.
Referenced by sndStreamClose(), sndStreamGetPosition(), sndStreamOpen(), sndStreamPause(), sndStreamPlay(), sndStreamSetPosition(), and sndStreamSetVolume().
stream_thid
int stream_thid =-1 static
Definition at line 41 of file adpcm-stream.c.
Referenced by sndStreamClose(), and sndStreamOpen().
stream_voice
u32 stream_voice[2] static
Definition at line 51 of file adpcm-stream.c.
Referenced by sndStreamGetPosition(), sndStreamOpen(), sndStreamPause(), sndStreamPlay(), sndStreamSetPosition(), and sndStreamSetVolume().