ps2sdk: iop/sound/ahx/src/ahx_irx.c File Reference
ahx_irx.c File Reference
#include "irx_imports.h"
#include "libsd.h"
#include "ahx.h"
Macros
#define COMPACT_CODE
#define MODNAME "AHXplayer"
#define MODVERSION "1.0b"
#define MODAUTHOR "Raizor"
#define M_PRINTF(format, args...) printf(MODNAME ": " format, ## args)
#define SD_CORE_1 1
#define SD_INIT_COLD 0
#define AHX_IRX 0xC001D0E
#define AHX_INIT 0x01
#define AHX_PLAY 0x02
#define AHX_PAUSE 0x03
#define AHX_QUIT 0x04
#define AHX_LOADSONG 0x05
#define AHX_SETVOLUME 0x06
#define AHX_SETBOOST 0x07
#define AHX_OVERSAMPLE 0x08
#define AHX_SUBSONG 0x09
#define TH_C 0x02000000
Functions
void wmemcpy (void *dest, void *src, int numwords)
void AHX_Thread (void *param)
void AHX_PlayThread (void *param)
static int AHX_TransCallback (void *param)
void AHX_SetVol (u16 vol)
void AHX_ResetPlayThread ()
void AHX_ClearSoundBuffers ()
void * AHX_rpc_server (unsigned int funcno, void *data, int size)
void * AHX_Init (unsigned int *sbuff)
void * AHX_LoadSong (unsigned int *sbuff)
void * AHX_SubSong (unsigned int *sbuff)
void * AHX_Play (unsigned int *sbuff)
void * AHX_Pause (unsigned int *sbuff)
void * AHX_SetVolume (unsigned int *sbuff)
void * AHX_SetBoost (unsigned int *sbuff)
void * AHX_ToggleOversampling (unsigned int *sbuff)
void * AHX_Quit (unsigned int *sbuff)
int _start ()
Variables
u8 * spubuf = NULL
char * pcmbuf = NULL
int transfer_sema = 0
int play_tid = 0
int intr_state
int readpos = 0
int seg_done [8]
int playing = 0
int songloaded = 0
int boost_val = 0
int oversample_enabled = 0
u16 SPU2_Volume = 0x3fff
char mod_buffer [50 *1024]
SifRpcDataQueue_t qd
SifRpcServerData_t Sd0
static unsigned int buffer [0x80]
Macro Definition Documentation
AHX_INIT
#define AHX_INIT 0x01
Definition at line 35 of file ahx_irx.c.
AHX_IRX
#define AHX_IRX 0xC001D0E
Definition at line 34 of file ahx_irx.c.
AHX_LOADSONG
#define AHX_LOADSONG 0x05
Definition at line 39 of file ahx_irx.c.
AHX_OVERSAMPLE
#define AHX_OVERSAMPLE 0x08
Definition at line 42 of file ahx_irx.c.
AHX_PAUSE
#define AHX_PAUSE 0x03
Definition at line 37 of file ahx_irx.c.
AHX_PLAY
#define AHX_PLAY 0x02
Definition at line 36 of file ahx_irx.c.
AHX_QUIT
#define AHX_QUIT 0x04
Definition at line 38 of file ahx_irx.c.
AHX_SETBOOST
#define AHX_SETBOOST 0x07
Definition at line 41 of file ahx_irx.c.
AHX_SETVOLUME
#define AHX_SETVOLUME 0x06
Definition at line 40 of file ahx_irx.c.
AHX_SUBSONG
#define AHX_SUBSONG 0x09
Definition at line 43 of file ahx_irx.c.
COMPACT_CODE
#define COMPACT_CODE
Definition at line 16 of file ahx_irx.c.
M_PRINTF
#define M_PRINTF (format, args...) printf(MODNAME ": " format, ## args)
Definition at line 21 of file ahx_irx.c.
MODAUTHOR
#define MODAUTHOR "Raizor"
Definition at line 20 of file ahx_irx.c.
MODNAME
#define MODNAME "AHXplayer"
Definition at line 18 of file ahx_irx.c.
MODVERSION
#define MODVERSION "1.0b"
Definition at line 19 of file ahx_irx.c.
SD_CORE_1
#define SD_CORE_1 1
Definition at line 24 of file ahx_irx.c.
SD_INIT_COLD
#define SD_INIT_COLD 0
Definition at line 25 of file ahx_irx.c.
TH_C
#define TH_C 0x02000000
Definition at line 44 of file ahx_irx.c.
Function Documentation
_start()
int _start ()
AHX Entry Point
This function is called automatically when the IRX module
is loaded. We simply set up the AHX Setup thread and exit...
Definition at line 85 of file ahx_irx.c.
 {
   iop_thread_t param;
   int th;
   FlushDcache();
   CpuEnableIntr(0);
   EnableIntr(40);       // Enables SPU DMA (channel 1) interrupt.
   param.attr         = TH_C;
   param.thread       = AHX_Thread;
   param.priority         = 40;
   param.stacksize    = 0x800;
   param.option       = 0;
   th = CreateThread(&param);
   if (th > 0) {
         StartThread(th,0);
         return 0;
   }else{
     return 1;
   }
 }
References AHX_Thread(), iop_thread_t::attr, CpuEnableIntr(), CreateThread(), EnableIntr(), FlushDcache(), iop_thread_t::option, iop_thread_t::priority, iop_thread_t::stacksize, StartThread(), TH_C, and iop_thread_t::thread.
AHX_ClearSoundBuffers()
void AHX_ClearSoundBuffers ()
AHX Clear Sound Buffers
Clears the pcm and spu buffers
Definition at line 281 of file ahx_irx.c.
 {
         // clear sound buffer
         memset(spubuf, 0, 0x800);
         memset(pcmbuf, 0, 0xF00*8);
 }
References memset(), pcmbuf, and spubuf.
Referenced by AHX_LoadSong(), and AHX_Thread().
AHX_Init()
void * AHX_Init (unsigned int * sbuff)
AHX Main Init
Called via RPC interface. This inits the player, SPU and
sets up the playing thread.
Definition at line 324 of file ahx_irx.c.
 {
         iop_thread_t play_thread; // play thread
         // init AXH Player
         AHXPlayer_Init();
         #ifndef COMPACT_CODE
                 printf("AHX INIT DONE!\n");
         #endif
         // Initialise SPU
         sceSdInit(SD_INIT_COLD);
         // set left and right channel volumes
         sceSdSetParam(SD_CORE_1|SD_PARAM_MVOLL,0x3fff);
         sceSdSetParam(SD_CORE_1|SD_PARAM_MVOLR,0x3fff);
         // Start audio streaming
         sceSdBlockTrans(1,SD_TRANS_LOOP,spubuf, 0x800, 0);
         // set SPU2 callback function pointer
         sceSdSetTransCallback(1, (void *)AHX_TransCallback);
         // Start playing thread
         play_thread.attr         = TH_C;
         play_thread.thread       = AHX_PlayThread;
         play_thread.priority     = 39;
         play_thread.stacksize    = 0x800;
         play_thread.option       = 0;
         play_tid = CreateThread(&play_thread);
         if (play_tid > 0) StartThread(play_tid,0);
         else {
                 #ifndef COMPACT_CODE
                 M_PRINTF("FATAL - Failed to start playing thread!\n");
                 #endif
                 ExitDeleteThread();
         }
         // volume up
         AHX_SetVol(0x3fff);
         // send out addresses for EE RPC to write data to
         sbuff[1] = (unsigned)mod_buffer;
         return sbuff;
 }
References AHX_PlayThread(), AHX_SetVol(), AHX_TransCallback(), AHXPlayer_Init(), CreateThread(), ExitDeleteThread(), M_PRINTF, mod_buffer, play_thread(), play_tid, printf(), sceSdBlockTrans(), sceSdInit(), sceSdSetParam(), sceSdSetTransCallback(), SD_CORE_1, SD_INIT_COLD, SD_PARAM_MVOLL, SD_PARAM_MVOLR, SD_TRANS_LOOP, spubuf, StartThread(), and TH_C.
Referenced by AHX_rpc_server().
AHX_LoadSong()
void * AHX_LoadSong (unsigned int * sbuff)
AHX Load Song
Loads a song via RPC
Definition at line 376 of file ahx_irx.c.
 {
         // if we're playing, stop
         if (playing)
         {
                 AHX_Pause(sbuff);
         }
         // reset playing params
         AHX_ResetPlayThread();
         #ifndef COMPACT_CODE
                 printf("Loading song - oversampling = %d, boost = %d\n", oversample_enabled, boost_val);
         #endif
         // load song
         sbuff[1] = (unsigned)AHXPlayer_LoadSongBuffer(mod_buffer, (int)sbuff[0]);
         // wait for SPU
         WaitSema(transfer_sema);
         AHX_ClearSoundBuffers();
         // init first sub-song
         AHXPlayer_InitSubsong(0);
         AHX_Play(sbuff);
         #ifndef COMPACT_CODE
                 M_PRINTF("Memory Allocated. %d bytes left.\n",QueryTotalFreeMemSize());
         #endif
         return sbuff; // return number of subsongs
 }
References AHX_ClearSoundBuffers(), AHX_Pause(), AHX_Play(), AHX_ResetPlayThread(), AHXPlayer_InitSubsong(), AHXPlayer_LoadSongBuffer(), boost_val, M_PRINTF, mod_buffer, oversample_enabled, playing, printf(), QueryTotalFreeMemSize(), transfer_sema, and WaitSema().
Referenced by AHX_rpc_server().
AHX_Pause()
void * AHX_Pause (unsigned int * sbuff)
AHX Pause
Pauses the currently playing song
Definition at line 426 of file ahx_irx.c.
 {
         AHX_SetVol(0);
         playing = 0;
         return sbuff;
 }
References AHX_SetVol(), and playing.
Referenced by AHX_LoadSong(), and AHX_rpc_server().
AHX_Play()
void * AHX_Play (unsigned int * sbuff)
AHX Play
Plays the currently loaded/paused song
Definition at line 415 of file ahx_irx.c.
 {
         AHX_SetVol(SPU2_Volume);
         playing = 1;
         return sbuff;
 }
References AHX_SetVol(), playing, and SPU2_Volume.
Referenced by AHX_LoadSong(), and AHX_rpc_server().
AHX_PlayThread()
void AHX_PlayThread (void * param)
Playing Thread
This code is called repeatedly, in here we mix our AHX
data into PCM format and store it in a buffer. We then
move it to another buffer so the SPU can grab it and
play it.
Definition at line 168 of file ahx_irx.c.
 {
         int i;
         int chunk; // we transfer to 2 blocks of SPU mem, are we working chunk 1 or 2?
         // reset position and flags etc
         AHX_ResetPlayThread();
         // main thread loop
         while(1)
         {
                 // backfill chunks that have already been passed to SPU. We do this before the WaitSema
                 // because we could be stuck there waiting for a while. If any spare time exists, we use
                 // it to mix the buffers...
                 if (playing)
                 {
                         for (i=0; i<7; i++)
{
                                 // check if we've just passed a section of data and refill it
                                 if (readpos>=0xF00*(i+1) && readpos<=0xF00*(i+2) && !seg_done[i])
{
                                         if (playing)
{
                                                 AHXOutput_MixBuffer( (short*)(pcmbuf+(0xF00*i)) ); // remix
                                         }
                                         seg_done[i] = 1; // mark segment as mixed and ready
                                         if (i>0) seg_done[i-1] = 0; else seg_done[7] = 0; // catch end segment
                                 }
                         }
                 }
                 // wait for SPU2 to set sema to indicate it's ready for more data
                 WaitSema(transfer_sema);
                 // suspend interrupts so our sema trigger doesn't get fired more than once
                 // while we work in here...
                 CpuSuspendIntr(&intr_state);
                 if (playing)
                 {
                         // get SPU transfer status to determine which area of SPU buffer to write PCM data to
                         chunk = 1 - (sceSdBlockTransStatus(1, 0 )>>24);
                         wmemcpy(spubuf+(1024*chunk),pcmbuf+readpos,512);                // left channel
                         wmemcpy(spubuf+(1024*chunk)+512,pcmbuf+readpos,512);    // right channel (same cos we're mono)
                         // SPU2 reads 512 bytes for each channel per frame, we're using the same PCM buffer for each
                         // channel (left/right), so update read position by 512 bytes. SPU reads data like so:
                         // 512 bytes for left channel | 512 bytes for right channel | 512 for left... etc etc
                         readpos += 512;
                         // check to see whether we've reached the end of our PCM buffer, if so, reset read position
                         // remix end chunk of AHX data in PCM buffer and mark segment as complete
                         if(readpos >= 0xF00 * 8)
{
                                 readpos = 0;
                                 AHXOutput_MixBuffer( (short*)(pcmbuf+(0xF00*7)) );
                                 seg_done[7] = 1;
                                 seg_done[6] = 0;
                         }
                 }
                 // re-enable interrupts
                 CpuResumeIntr(intr_state);
         }
 }
References AHX_ResetPlayThread(), AHXOutput_MixBuffer(), CpuResumeIntr(), CpuSuspendIntr(), intr_state, pcmbuf, playing, readpos, sceSdBlockTransStatus(), seg_done, spubuf, transfer_sema, WaitSema(), and wmemcpy().
Referenced by AHX_Init().
AHX_Quit()
void * AHX_Quit (unsigned int * sbuff)
AHX Quit
 Cleans up and quits
Definition at line 486 of file ahx_irx.c.
 {
         sceSdSetTransCallback(1,NULL);
         sceSdBlockTrans(1,SD_TRANS_STOP,0,0,0);
         TerminateThread(play_tid);
         DeleteThread(play_tid);
         DeleteSema(transfer_sema);
         return sbuff;
 }
References DeleteSema(), DeleteThread(), NULL, play_tid, sceSdBlockTrans(), sceSdSetTransCallback(), SD_TRANS_STOP, TerminateThread(), and transfer_sema.
Referenced by AHX_rpc_server().
AHX_ResetPlayThread()
void AHX_ResetPlayThread ()
AHX Reset Play Thread
Resets the play thread properties
Definition at line 263 of file ahx_irx.c.
 {
         int i;
         // loop through and mark all segments as not done
         for (i=0; i<8; i++)
         {
                 seg_done[i] = 0;
         }
         // set play marker back to beginning
         readpos = 0;
 }
References readpos, and seg_done.
Referenced by AHX_LoadSong(), and AHX_PlayThread().
AHX_rpc_server()
void * AHX_rpc_server (unsigned int funcno, void * data, int size)
AHX RPC Server
This catches messages sent across from the EE interface
and calls the appropriate function (according to the
function code 'funcno'.
Definition at line 294 of file ahx_irx.c.
 {
         switch(funcno) {
                 case AHX_INIT:
                         return AHX_Init((unsigned*)data);
                 case AHX_PLAY:
                         return AHX_Play((unsigned*)data);
                 case AHX_PAUSE:
                         return AHX_Pause((unsigned*)data);
                 case AHX_QUIT:
                         return AHX_Quit((unsigned*)data);
                 case AHX_LOADSONG:
                         return AHX_LoadSong((unsigned*)data);
                 case AHX_SETVOLUME:
                         return AHX_SetVolume((unsigned*)data);
                 case AHX_SETBOOST:
                         return AHX_SetBoost((unsigned*)data);
                 case AHX_OVERSAMPLE:
                         return AHX_ToggleOversampling((unsigned*)data);
                 case AHX_SUBSONG:
                         return AHX_SubSong((unsigned*)data);
         }
         return NULL;
 }
References AHX_INIT, AHX_Init(), AHX_LOADSONG, AHX_LoadSong(), AHX_OVERSAMPLE, AHX_PAUSE, AHX_Pause(), AHX_PLAY, AHX_Play(), AHX_QUIT, AHX_Quit(), AHX_SETBOOST, AHX_SetBoost(), AHX_SETVOLUME, AHX_SetVolume(), AHX_SUBSONG, AHX_SubSong(), AHX_ToggleOversampling(), and NULL.
Referenced by AHX_Thread().
AHX_SetBoost()
void * AHX_SetBoost (unsigned int * sbuff)
AHX Set Boost
Sets the AHX Output Boost value. Each increment increases
output volume by 100%. Large numbers can cause
distortion. It's advisable not to boost above 1 or 2.
Definition at line 450 of file ahx_irx.c.
 {
         boost_val = (int)sbuff[0];
         AHXPlayer_SetBoost(boost_val);
         return sbuff;
 }
References AHXPlayer_SetBoost(), and boost_val.
Referenced by AHX_rpc_server().
AHX_SetVol()
void AHX_SetVol (u16 vol)
AHX Set Volume
Sets the output SPU volume for both channels (left/right)
Definition at line 253 of file ahx_irx.c.
 {
         sceSdSetParam(SD_CORE_1|SD_PARAM_BVOLL,vol);
         sceSdSetParam(SD_CORE_1|SD_PARAM_BVOLR,vol);
 }
References sceSdSetParam(), SD_CORE_1, SD_PARAM_BVOLL, and SD_PARAM_BVOLR.
Referenced by AHX_Init(), AHX_Pause(), AHX_Play(), and AHX_SetVolume().
AHX_SetVolume()
void * AHX_SetVolume (unsigned int * sbuff)
AHX Set Volume
Sets SPU2 Volume to %
Definition at line 437 of file ahx_irx.c.
 {
         SPU2_Volume = (u16)(0x3fff*(u16)sbuff[1])/100;
         AHX_SetVol(SPU2_Volume);
         return sbuff;
 }
References AHX_SetVol(), and SPU2_Volume.
Referenced by AHX_rpc_server().
AHX_SubSong()
void * AHX_SubSong (unsigned int * sbuff)
AHX Play Subsong
Plays the requested subsong. Number of subsongs is
returned by LoadSong(). A lot of AHX files report the
wrong number of subsongs - please check your AHX files...
Definition at line 476 of file ahx_irx.c.
 {
         AHXPlayer_InitSubsong((int)sbuff[0]);
         return sbuff;
 }
References AHXPlayer_InitSubsong().
Referenced by AHX_rpc_server().
AHX_Thread()
void AHX_Thread (void * param)
AHX Setup Thread
This inits the AHX output system (AHX->PCM decoder), sets
up our semaphore so the SPU can flag when it wants more
data. We also init the RPC server in here, as well as
creating buffers for the SPU to transfer PCM data from
and also a buffer to decode AHX to PCM.
Definition at line 114 of file ahx_irx.c.
 {
         // int i;
         iop_sema_t sema; // semaphore
         // set sema properties and create...
         sema.attr = 0; // SA_THFIFO;
         sema.initial = 0;
         sema.max = 1;
         transfer_sema= CreateSema(&sema);
         // check sema created successfully, or exit
         if(transfer_sema <= 0) {
                 #ifndef COMPACT_CODE
                         M_PRINTF("FATAL - Failed to create semaphore!\n");
                 #endif
                 ExitDeleteThread();
         }
         // allocate memory for SPU2 xfer buffer
         spubuf = AllocSysMemory(0, 0x800, NULL); // 2048 bytes (enough for 2 SPU cycles at 512 bytes per channel)
         pcmbuf = AllocSysMemory(0, 0xF00*8, NULL); // enough to hold 8 full AHX-PCM decoded chunks (0xF00 per chunk)
         if(spubuf == NULL) {
                 #ifndef COMPACT_CODE
                 M_PRINTF("FATAL - Failed to allocate memory for sound buffer!\n");
                 #endif
                 ExitDeleteThread();
         }
         // print version #
         #ifndef COMPACT_CODE
                 M_PRINTF("AHXplayer %s Started\n", MODVERSION);
         #endif
         AHX_ClearSoundBuffers();
         #ifndef COMPACT_CODE
                 M_PRINTF("Memory Allocated. %d bytes left.\n",QueryTotalFreeMemSize());
         #endif
         // Init the RPC server
         SifInitRpc(0);
         SifSetRpcQueue(&qd, GetThreadId());
         SifRegisterRpc(&Sd0, AHX_IRX, (void*)AHX_rpc_server, (void*)&buffer[0], 0, 0, &qd);
         SifRpcLoop(&qd);
 }
References AHX_ClearSoundBuffers(), AHX_IRX, AHX_rpc_server(), AllocSysMemory(), iop_sema_t::attr, buffer, CreateSema(), ExitDeleteThread(), GetThreadId(), iop_sema_t::initial, M_PRINTF, iop_sema_t::max, MODVERSION, NULL, pcmbuf, qd, QueryTotalFreeMemSize(), Sd0, SifInitRpc, SifRegisterRpc, SifRpcLoop, SifSetRpcQueue, spubuf, and transfer_sema.
Referenced by _start().
AHX_ToggleOversampling()
void * AHX_ToggleOversampling (unsigned int * sbuff)
AHX Set Oversample
Enables oversampling. This gives a smoother sound but
requires more CPU power. It can result in slowdown of
playback with certain songs or produce an awful din...
Definition at line 463 of file ahx_irx.c.
 {
         oversample_enabled = oversample_enabled ? 0 : 1;
         AHXPlayer_SetOversampling(oversample_enabled);
         return sbuff;
 }
References AHXPlayer_SetOversampling(), and oversample_enabled.
Referenced by AHX_rpc_server().
AHX_TransCallback()
static int AHX_TransCallback (void * param) static
AHX Callback
Called by SPU2 when it wants more sound data
Definition at line 239 of file ahx_irx.c.
 {
         // signal our semaphore to indicate that SPU2 has finished
         // processing current sound data and that it's time to
         // xfer some more data across...
         iSignalSema(transfer_sema);
         return 1;
 }
References iSignalSema(), and transfer_sema.
Referenced by AHX_Init().
wmemcpy()
void wmemcpy (void * dest, void * src, int numwords)
Referenced by AHX_PlayThread(), cdda_procedure(), and play_thread().
Variable Documentation
boost_val
int boost_val = 0
Definition at line 50 of file ahx_irx.c.
Referenced by AHX_LoadSong(), and AHX_SetBoost().
buffer
unsigned int buffer[0x80] static
Definition at line 59 of file ahx_irx.c.
Referenced by AHX_Thread().
intr_state
int intr_state
Definition at line 31 of file ahx_irx.c.
Referenced by AHX_PlayThread(), cdda_procedure(), DmaSendEE(), padInit(), and play_thread().
mod_buffer
char mod_buffer[50 *1024]
Definition at line 53 of file ahx_irx.c.
Referenced by AHX_Init(), and AHX_LoadSong().
oversample_enabled
int oversample_enabled = 0
Definition at line 51 of file ahx_irx.c.
Referenced by AHX_LoadSong(), and AHX_ToggleOversampling().
pcmbuf
char* pcmbuf = NULL
Definition at line 28 of file ahx_irx.c.
Referenced by AHX_ClearSoundBuffers(), AHX_PlayThread(), and AHX_Thread().
play_tid
int play_tid = 0
Definition at line 30 of file ahx_irx.c.
Referenced by AHX_Init(), and AHX_Quit().
playing
int playing = 0
Definition at line 48 of file ahx_irx.c.
Referenced by AHX_LoadSong(), AHX_Pause(), AHX_Play(), and AHX_PlayThread().
qd
SifRpcDataQueue_t qd
Definition at line 55 of file ahx_irx.c.
Referenced by AHX_Thread().
readpos
int readpos = 0
Definition at line 46 of file ahx_irx.c.
Referenced by AHX_PlayThread(), and AHX_ResetPlayThread().
Sd0
SifRpcServerData_t Sd0
Definition at line 56 of file ahx_irx.c.
Referenced by AHX_Thread().
seg_done
int seg_done[8]
Definition at line 47 of file ahx_irx.c.
Referenced by AHX_PlayThread(), and AHX_ResetPlayThread().
songloaded
int songloaded = 0
Definition at line 49 of file ahx_irx.c.
SPU2_Volume
u16 SPU2_Volume = 0x3fff
Definition at line 52 of file ahx_irx.c.
Referenced by AHX_Play(), and AHX_SetVolume().
spubuf
u8* spubuf = NULL
Definition at line 27 of file ahx_irx.c.
Referenced by AHX_ClearSoundBuffers(), AHX_Init(), AHX_PlayThread(), and AHX_Thread().
transfer_sema
int transfer_sema = 0
Definition at line 29 of file ahx_irx.c.
Referenced by AHX_LoadSong(), AHX_PlayThread(), AHX_Quit(), AHX_Thread(), and AHX_TransCallback().