ps2sdk: iop/sound/ahx/include/ahx.h File Reference
ahx.h File Reference
Data Structures
struct AHXPListEntry
struct AHXPList
struct AHXEnvelope
struct AHXInstrument
struct AHXPosition
struct AHXStep
struct AHXSong
struct AHXVoice
struct AHXWaves
Functions
void AHXPlayer_Init ()
int AHXPlayer_LoadSongBuffer (void *Buffer, int Len)
int AHXPlayer_InitSubsong (int Nr)
void AHXPlayer_NextPosition ()
void AHXPlayer_PrevPosition ()
void AHXPlayer_VoiceOnOff (int Voice, int OnOff)
void AHXPlayer_SetAudio (int v)
void AHXPlayer_PListCommandParse (int v, int FX, int FXParam)
void AHXPlayer_PlayIRQ ()
void AHXPlayer_ProcessStep (int v)
void AHXPlayer_ProcessFrame (int v)
void AHXPlayer_SetBoost (int boostval)
void AHXPlayer_SetOversampling (int enable)
void AHXOutput_MixBuffer (short *target)
Detailed Description
AHX player functions
Definition in file ahx.h.
Function Documentation
AHXOutput_MixBuffer()
void AHXOutput_MixBuffer (short * target)
Definition at line 1105 of file AHX.c.
 {
         #define LOW_CLIP16     -0x8000
         #define HI_CLIP16       0x7FFF
         #define LOW_CLIP8      -0x80
         #define HI_CLIP8        0x7F
     int f;
         int NrSamples = Frequency / Hz / Song.SpeedMultiplier;
         int* mb = MixingBuffer;
         int thissample;
     int s;
         memset(MixingBuffer, 0, MixLen*Frequency/Hz*sizeof(int));
         for(f = 0; f < MixLen*Song.SpeedMultiplier /* MixLen = # frames */; f++) {
                 AHXPlayer_PlayIRQ();
                 AHXOutput_MixChunk(NrSamples, &mb);
         } // frames
         for(s = 0; s < BlockLen /(16/8); s++)
         {
                 thissample = *(MixingBuffer+s) << 6; // 16 bit
         target[s] = thissample < LOW_CLIP16 ? LOW_CLIP16 : thissample > HI_CLIP16 ? HI_CLIP16 : thissample;
     }
 }
References AHXOutput_MixChunk(), AHXPlayer_PlayIRQ(), BlockLen, Frequency, HI_CLIP16, Hz, memset(), MixingBuffer, MixLen, Song, and AHXSong::SpeedMultiplier.
Referenced by AHX_PlayThread().
AHXPlayer_Init()
void AHXPlayer_Init ()
Definition at line 278 of file AHX.c.
 {
         Waves = (struct AHXWaves*)malloc(sizeof(struct AHXWaves));
         WaveformTab[0] = Waves->Triangle04;
         WaveformTab[1] = Waves->Sawtooth04;
         WaveformTab[3] = Waves->WhiteNoiseBig;
         GenerateSawtooth(Waves->Sawtooth04, 0x04);
         GenerateSawtooth(Waves->Sawtooth08, 0x08);
         GenerateSawtooth(Waves->Sawtooth10, 0x10);
         GenerateSawtooth(Waves->Sawtooth20, 0x20);
         GenerateSawtooth(Waves->Sawtooth40, 0x40);
         GenerateSawtooth(Waves->Sawtooth80, 0x80);
         GenerateTriangle(Waves->Triangle04, 0x04);
         GenerateTriangle(Waves->Triangle08, 0x08);
         GenerateTriangle(Waves->Triangle10, 0x10);
         GenerateTriangle(Waves->Triangle20, 0x20);
         GenerateTriangle(Waves->Triangle40, 0x40);
         GenerateTriangle(Waves->Triangle80, 0x80);
         GenerateSquare(Waves->Squares);
         GenerateWhiteNoise(Waves->WhiteNoiseBig, 0x280*3);
         GenerateFilterWaveforms(Waves->Triangle04, Waves->LowPasses, Waves->HighPasses);
         MixingBuffer = (int*) malloc(sizeof(int)*(MixLen*Frequency/Hz));
         AHXOutput_SetOption(AHXOF_BOOST, Boost+1);
 }
References AHXOF_BOOST, AHXOutput_SetOption(), Boost, Frequency, GenerateFilterWaveforms(), GenerateSawtooth(), GenerateSquare(), GenerateTriangle(), GenerateWhiteNoise(), AHXWaves::HighPasses, Hz, AHXWaves::LowPasses, malloc, MixingBuffer, MixLen, AHXWaves::Sawtooth04, AHXWaves::Sawtooth08, AHXWaves::Sawtooth10, AHXWaves::Sawtooth20, AHXWaves::Sawtooth40, AHXWaves::Sawtooth80, AHXWaves::Squares, AHXWaves::Triangle04, AHXWaves::Triangle08, AHXWaves::Triangle10, AHXWaves::Triangle20, AHXWaves::Triangle40, AHXWaves::Triangle80, WaveformTab, Waves, and AHXWaves::WhiteNoiseBig.
Referenced by AHX_Init().
AHXPlayer_InitSubsong()
int AHXPlayer_InitSubsong (int Nr)
Definition at line 459 of file AHX.c.
 {
     int v;
         if(Nr > Song.SubsongNr) return 0;
         if(Nr == 0) PosNr = 0;
                else PosNr = Song.Subsongs[Nr-1];
         PosJump = 0;
         PatternBreak = 0;
         MainVolume = 0x40;
         Playing = 1;
         NoteNr = PosJumpNote = 0;
         Tempo = 6;
         StepWaitFrames = 0;
         GetNewPosition = 1;
         SongEndReached = 0;
         TimingValue = PlayingTime = 0;
         for(v = 0; v < 4; v++)
     {
         AHXVoice_Init(&Voices[v]);
     }
         return 1;
 }
References AHXVoice_Init(), GetNewPosition, MainVolume, NoteNr, PatternBreak, Playing, PlayingTime, PosJump, PosJumpNote, PosNr, Song, SongEndReached, StepWaitFrames, AHXSong::SubsongNr, AHXSong::Subsongs, Tempo, TimingValue, and Voices.
Referenced by AHX_LoadSong(), and AHX_SubSong().
AHXPlayer_LoadSongBuffer()
int AHXPlayer_LoadSongBuffer (void * Buffer, int Len)
Definition at line 327 of file AHX.c.
 {
         int SongLength = Len;
     int i, j, MaxTrack;
         unsigned char* SongBuffer = (unsigned char*)Buffer;
         unsigned char* SBPtr = &SongBuffer[14];
     char* NamePtr;
         AHXPlayer_FreeMem();
         if(SongLength < 14 || SongLength == 65536) return 0;
         if(SongBuffer[0] != 'T' && SongBuffer[1] != 'H' && SongBuffer[2] != 'X') return 0;
         Song.Revision = SongBuffer[3];
         if(Song.Revision > 1) return 0;
         // Header ////////////////////////////////////////////
         // Songname
         NamePtr = (char*)&SongBuffer[(SongBuffer[4]<<8) | SongBuffer[5]];
         Song.Name =  (char*) malloc(strlen(NamePtr)+1);
         strcpy(Song.Name, NamePtr); NamePtr += strlen(NamePtr)+1;
         Song.SpeedMultiplier = ((SongBuffer[6]>>5)&3)+1;
         Song.PositionNr = ((SongBuffer[6]&0xf)<<8) | SongBuffer[7];
         Song.Restart = (SongBuffer[8]<<8) | SongBuffer[9];
         Song.TrackLength = SongBuffer[10];
         Song.TrackNr = SongBuffer[11];
         Song.InstrumentNr = SongBuffer[12];
         Song.SubsongNr = SongBuffer[13];
         // Subsongs //////////////////////////////////////////
         Song.Subsongs = (int*) malloc(sizeof(int)*Song.SubsongNr);
         #ifndef COMPACT_CODE
                 printf("name length = %d\n",strlen(NamePtr)+1);
                 printf("playing: %s\n", NamePtr);
                 printf("subsongs = %d\n",Song.SubsongNr);
                 printf("Positions = %d\n",Song.PositionNr);
                 printf("Tracks = %d\n",(MaxTrack+1));
         #endif
         for(i = 0; i < Song.SubsongNr; i++) {
                 if(SBPtr - SongBuffer > SongLength) return 0;
                 Song.Subsongs[i] = (SBPtr[0]<<8)|SBPtr[1];
                 SBPtr += 2;
         }
         // Position List /////////////////////////////////////
         Positions = (struct AHXPosition*) malloc(sizeof(struct AHXPosition)*Song.PositionNr);
         for(i = 0; i < Song.PositionNr; i++) {
                 for(j = 0; j < 4; j++) {
                         if(SBPtr - SongBuffer > SongLength) return 0;
                         Positions[i].Track[j] = *SBPtr++;
                         Positions[i].Transpose[j] = *(signed char*)SBPtr++;
                 }
         }
         // Tracks ////////////////////////////////////////////
         MaxTrack = Song.TrackNr;
         Tracks = (struct AHXStep**) malloc(sizeof(struct AHXStep)*(MaxTrack+1));
         for(i = 0; i < MaxTrack+1; i++) {
                 Tracks[i] = (struct AHXStep*) malloc(sizeof(struct AHXStep)*Song.TrackLength);
                 if((SongBuffer[6]&0x80)==0x80 && i==0) {
                         memset(Tracks[i], 0, Song.TrackLength*sizeof(struct AHXStep));
                         continue;
                 }
                 for(j = 0; j < Song.TrackLength; j++) {
                         if(SBPtr - SongBuffer > SongLength) return 0;
                         Tracks[i][j].Note = (SBPtr[0]>>2)&0x3f;
                         Tracks[i][j].Instrument = ((SBPtr[0]&0x3)<<4) | (SBPtr[1]>>4);
                         Tracks[i][j].FX = SBPtr[1]&0xf;
                         Tracks[i][j].FXParam = SBPtr[2];
                         SBPtr += 3;
                 }
         }
         // Instruments ///////////////////////////////////////
         Instruments = (struct AHXInstrument*) malloc(sizeof(struct AHXInstrument)*(Song.InstrumentNr+1));
         for(i = 1; i < Song.InstrumentNr+1; i++) {
                 Instruments[i].Name = (char*) malloc(strlen(NamePtr)+1);
                 strcpy(Instruments[i].Name, NamePtr); NamePtr += strlen(NamePtr)+1;
                 if(SBPtr - SongBuffer > SongLength) return 0;
                 Instruments[i].Volume = SBPtr[0];
                 Instruments[i].FilterSpeed = ((SBPtr[1]>>3)&0x1f) | ((SBPtr[12]>>2)&0x20);
                 Instruments[i].WaveLength = SBPtr[1]&0x7;
                 Instruments[i].Envelope.aFrames = SBPtr[2];
                 Instruments[i].Envelope.aVolume = SBPtr[3];
                 Instruments[i].Envelope.dFrames = SBPtr[4]; //4
                 Instruments[i].Envelope.dVolume = SBPtr[5];
                 Instruments[i].Envelope.sFrames = SBPtr[6];
                 Instruments[i].Envelope.rFrames = SBPtr[7]; //7
                 Instruments[i].Envelope.rVolume = SBPtr[8];
                 Instruments[i].FilterLowerLimit = SBPtr[12]&0x7f;
                 Instruments[i].VibratoDelay = SBPtr[13]; //13
                 Instruments[i].HardCutReleaseFrames = (SBPtr[14]>>4)&7;
                 Instruments[i].HardCutRelease = SBPtr[14]&0x80?1:0;
                 Instruments[i].VibratoDepth = SBPtr[14]&0xf; //14
                 Instruments[i].VibratoSpeed = SBPtr[15];
                 Instruments[i].SquareLowerLimit = SBPtr[16];
                 Instruments[i].SquareUpperLimit = SBPtr[17]; //17
                 Instruments[i].SquareSpeed = SBPtr[18];
                 Instruments[i].FilterUpperLimit = SBPtr[19]&0x3f; //19
                 Instruments[i].PList.Speed = SBPtr[20];
                 Instruments[i].PList.Length= SBPtr[21];
                 SBPtr += 22;
                 Instruments[i].PList.Entries = (struct AHXPListEntry*) malloc(sizeof(struct AHXPListEntry)*Instruments[i].PList.Length);
                 for(j = 0; j < Instruments[i].PList.Length; j++) {
                         if(SBPtr - SongBuffer > SongLength) return 0;
                         Instruments[i].PList.Entries[j].FX[1] = (SBPtr[0]>>5)&7;
                         Instruments[i].PList.Entries[j].FX[0] = (SBPtr[0]>>2)&7;
                         Instruments[i].PList.Entries[j].Waveform = ((SBPtr[0]<<1)&6) | (SBPtr[1]>>7);
                         Instruments[i].PList.Entries[j].Fixed = (SBPtr[1]>>6)&1;
                         Instruments[i].PList.Entries[j].Note = SBPtr[1]&0x3f;
                         Instruments[i].PList.Entries[j].FXParam[0] = SBPtr[2];
                         Instruments[i].PList.Entries[j].FXParam[1] = SBPtr[3];
                         SBPtr += 4;
                 }
         }
         return Song.SubsongNr;
 }
References AHXEnvelope::aFrames, AHXPlayer_FreeMem(), AHXEnvelope::aVolume, AHXEnvelope::dFrames, AHXEnvelope::dVolume, AHXPList::Entries, AHXInstrument::Envelope, AHXInstrument::FilterLowerLimit, AHXInstrument::FilterSpeed, AHXInstrument::FilterUpperLimit, AHXPListEntry::Fixed, AHXPListEntry::FX, AHXStep::FX, AHXPListEntry::FXParam, AHXStep::FXParam, AHXInstrument::HardCutRelease, AHXInstrument::HardCutReleaseFrames, AHXStep::Instrument, AHXSong::InstrumentNr, Instruments, AHXPList::Length, malloc, memset(), AHXInstrument::Name, AHXSong::Name, AHXPListEntry::Note, AHXStep::Note, AHXInstrument::PList, AHXSong::PositionNr, Positions, printf(), AHXSong::Restart, AHXSong::Revision, AHXEnvelope::rFrames, AHXEnvelope::rVolume, AHXEnvelope::sFrames, Song, AHXPList::Speed, AHXSong::SpeedMultiplier, AHXInstrument::SquareLowerLimit, AHXInstrument::SquareSpeed, AHXInstrument::SquareUpperLimit, strcpy(), strlen(), AHXSong::SubsongNr, AHXSong::Subsongs, AHXPosition::Track, AHXSong::TrackLength, AHXSong::TrackNr, Tracks, AHXPosition::Transpose, AHXInstrument::VibratoDelay, AHXInstrument::VibratoDepth, AHXInstrument::VibratoSpeed, AHXInstrument::Volume, AHXPListEntry::Waveform, and AHXInstrument::WaveLength.
Referenced by AHX_LoadSong().
AHXPlayer_NextPosition()
void AHXPlayer_NextPosition ()
Definition at line 487 of file AHX.c.
 {
         PosNr++;
         if(PosNr == Song.PositionNr) PosNr = 0;
         StepWaitFrames = 0;
         GetNewPosition = 1;
 }
References GetNewPosition, AHXSong::PositionNr, PosNr, Song, and StepWaitFrames.
AHXPlayer_PlayIRQ()
void AHXPlayer_PlayIRQ ()
Definition at line 1010 of file AHX.c.
 {
     int NextPos, i, a;
         if(StepWaitFrames <= 0) {
                 if(GetNewPosition) {
                         NextPos = (PosNr+1==Song.PositionNr)?0:(PosNr+1);
                         for(i = 0; i < 4; i++) {
                                 Voices[i].Track = Positions[PosNr].Track[i];
                                 Voices[i].Transpose = Positions[PosNr].Transpose[i];
                                 Voices[i].NextTrack = Positions[NextPos].Track[i];
                                 Voices[i].NextTranspose = Positions[NextPos].Transpose[i];
                         }
                         GetNewPosition = 0;
                 }
                 for(i = 0; i < 4; i++) AHXPlayer_ProcessStep(i);
                 StepWaitFrames = Tempo;
         }
         //DoFrameStuff
         for(i = 0; i < 4; i++) AHXPlayer_ProcessFrame(i);
         PlayingTime++;
         if(Tempo > 0 && --StepWaitFrames <= 0) {
                 if(!PatternBreak) {
                         NoteNr++;
                         if(NoteNr >= Song.TrackLength) {
                                 PosJump = PosNr+1;
                                 PosJumpNote = 0;
                                 PatternBreak = 1;
                         }
                 }
                 if(PatternBreak) {
                         PatternBreak = 0;
                         NoteNr = PosJumpNote;
                         PosJumpNote = 0;
                         PosNr = PosJump;
                         PosJump = 0;
                         if(PosNr == Song.PositionNr) {
                                 SongEndReached = 1;
                                 PosNr = Song.Restart;
                         }
                         GetNewPosition = 1;
                 }
         }
         //RemainPosition
         for(a = 0; a < 4; a++) AHXPlayer_SetAudio(a);
 }
References AHXPlayer_ProcessFrame(), AHXPlayer_ProcessStep(), AHXPlayer_SetAudio(), GetNewPosition, AHXVoice::NextTrack, AHXVoice::NextTranspose, NoteNr, PatternBreak, PlayingTime, AHXSong::PositionNr, Positions, PosJump, PosJumpNote, PosNr, AHXSong::Restart, Song, SongEndReached, StepWaitFrames, Tempo, AHXPosition::Track, AHXVoice::Track, AHXSong::TrackLength, AHXPosition::Transpose, AHXVoice::Transpose, and Voices.
Referenced by AHXOutput_MixBuffer().
AHXPlayer_PListCommandParse()
void AHXPlayer_PListCommandParse (int v, int FX, int FXParam)
Definition at line 694 of file AHX.c.
 {
         switch(FX) {
                 case 0:
                         if(Song.Revision > 0 && FXParam != 0) {
                                 if(Voices[v].IgnoreFilter) {
                                         Voices[v].FilterPos = Voices[v].IgnoreFilter;
                                         Voices[v].IgnoreFilter = 0;
                                 } else Voices[v].FilterPos = FXParam;
                                 Voices[v].NewWaveform = 1;
                         }
                         break;
                 case 1:
                         Voices[v].PeriodPerfSlideSpeed = FXParam;
                         Voices[v].PeriodPerfSlideOn = 1;
                         break;
                 case 2:
                         Voices[v].PeriodPerfSlideSpeed = -FXParam;
                         Voices[v].PeriodPerfSlideOn = 1;
                         break;
                 case 3: // Init Square Modulation
                         if(!Voices[v].IgnoreSquare) {
                                 Voices[v].SquarePos = FXParam >> (5-Voices[v].WaveLength);
                         } else Voices[v].IgnoreSquare = 0;
                         break;
                 case 4: // Start/Stop Modulation
                         if(Song.Revision == 0 || FXParam == 0) {
                                 Voices[v].SquareInit = (Voices[v].SquareOn ^= 1);
                                 Voices[v].SquareSign = 1;
                         } else {
                                 if(FXParam & 0x0f) {
                                         Voices[v].SquareInit = (Voices[v].SquareOn ^= 1);
                                         Voices[v].SquareSign = 1;
                                         if((FXParam & 0x0f) == 0x0f) Voices[v].SquareSign = -1;
                                 }
                                 if(FXParam & 0xf0) {
                                         Voices[v].FilterInit = (Voices[v].FilterOn ^= 1);
                                         Voices[v].FilterSign = 1;
                                         if((FXParam & 0xf0) == 0xf0) Voices[v].FilterSign = -1;
                                 }
                         }
                         break;
                 case 5: // Jump to Step [xx]
                         Voices[v].PerfCurrent = FXParam;
                         break;
                 case 6: // Set Volume
                         if(FXParam > 0x40) {
                                 if((FXParam -= 0x50) >= 0) {
                                         if(FXParam <= 0x40) Voices[v].PerfSubVolume = FXParam;
                                         else
                                                 if((FXParam -= 0xa0-0x50) >= 0)
                                                         if(FXParam <= 0x40) Voices[v].TrackMasterVolume = FXParam;
                                 }
                         } else Voices[v].NoteMaxVolume = FXParam;
                         break;
                 case 7: // set speed
                         Voices[v].PerfSpeed = Voices[v].PerfWait = FXParam;
                         break;
         }
 }
References AHXVoice::FilterInit, AHXVoice::FilterOn, AHXVoice::FilterPos, AHXVoice::FilterSign, AHXPListEntry::FX, AHXPListEntry::FXParam, AHXVoice::IgnoreFilter, AHXVoice::IgnoreSquare, AHXVoice::NewWaveform, AHXVoice::NoteMaxVolume, AHXVoice::PerfCurrent, AHXVoice::PerfSpeed, AHXVoice::PerfSubVolume, AHXVoice::PerfWait, AHXVoice::PeriodPerfSlideOn, AHXVoice::PeriodPerfSlideSpeed, AHXSong::Revision, Song, AHXVoice::SquareInit, AHXVoice::SquareOn, AHXVoice::SquarePos, AHXVoice::SquareSign, AHXVoice::TrackMasterVolume, Voices, and AHXVoice::WaveLength.
Referenced by AHXPlayer_ProcessFrame().
AHXPlayer_PrevPosition()
void AHXPlayer_PrevPosition ()
Definition at line 495 of file AHX.c.
 {
         PosNr--;
         if(PosNr < 0) PosNr = 0;
         StepWaitFrames = 0;
         GetNewPosition = 1;
 }
References GetNewPosition, PosNr, and StepWaitFrames.
AHXPlayer_ProcessFrame()
void AHXPlayer_ProcessFrame (int v)
Definition at line 755 of file AHX.c.
 {
     int d0, d1, d2, d3, Cur, FMax, i, X, Delta;
     char* SquarePtr, *AudioSource;
         if(!Voices[v].TrackOn) return;
         if(Voices[v].NoteDelayOn) {
                 if(Voices[v].NoteDelayWait <= 0) AHXPlayer_ProcessStep(v);
                                             else Voices[v].NoteDelayWait--;
         }
         if(Voices[v].HardCut) {
                 int NextInstrument;
                 if(NoteNr+1 < Song.TrackLength) NextInstrument = Tracks[Voices[v].Track][NoteNr+1].Instrument;
                                                            else NextInstrument = Tracks[Voices[v].NextTrack][0].Instrument;
                 if(NextInstrument) {
                         d1 = Tempo - Voices[v].HardCut;
                         if(d1 < 0) d1 = 0;
                         if(!Voices[v].NoteCutOn) {
                                 Voices[v].NoteCutOn = 1;
                                 Voices[v].NoteCutWait = d1;
                                 Voices[v].HardCutReleaseF = -(d1 - Tempo);
                         } else Voices[v].HardCut = 0;
                 }
         }
         if(Voices[v].NoteCutOn) {
                 if(Voices[v].NoteCutWait <= 0) {
                         Voices[v].NoteCutOn = 0;
                         if(Voices[v].HardCutRelease) {
                                 Voices[v].ADSR.rVolume = -(Voices[v].ADSRVolume - (Voices[v].Instrument->Envelope.rVolume << 8))/Voices[v].HardCutReleaseF;
                                 Voices[v].ADSR.rFrames = Voices[v].HardCutReleaseF;
                                 Voices[v].ADSR.aFrames = Voices[v].ADSR.dFrames = Voices[v].ADSR.sFrames = 0;
                         } else Voices[v].NoteMaxVolume = 0;
                 } else Voices[v].NoteCutWait--;
         }
         //adsrEnvelope
         if(Voices[v].ADSR.aFrames) {
                 Voices[v].ADSRVolume += Voices[v].ADSR.aVolume; // Delta
                 if(--Voices[v].ADSR.aFrames <= 0) Voices[v].ADSRVolume = Voices[v].Instrument->Envelope.aVolume << 8;
         } else if(Voices[v].ADSR.dFrames) {
                 Voices[v].ADSRVolume += Voices[v].ADSR.dVolume; // Delta
                 if(--Voices[v].ADSR.dFrames <= 0) Voices[v].ADSRVolume = Voices[v].Instrument->Envelope.dVolume << 8;
         } else if(Voices[v].ADSR.sFrames) {
                 Voices[v].ADSR.sFrames--;
         } else if(Voices[v].ADSR.rFrames) {
                 Voices[v].ADSRVolume += Voices[v].ADSR.rVolume; // Delta
                 if(--Voices[v].ADSR.rFrames <= 0) Voices[v].ADSRVolume = Voices[v].Instrument->Envelope.rVolume << 8;
         }
         //VolumeSlide
         Voices[v].NoteMaxVolume = Voices[v].NoteMaxVolume + Voices[v].VolumeSlideUp - Voices[v].VolumeSlideDown;
         if(Voices[v].NoteMaxVolume < 0) Voices[v].NoteMaxVolume = 0;
         if(Voices[v].NoteMaxVolume > 0x40) Voices[v].NoteMaxVolume = 0x40;
         //Portamento
         if(Voices[v].PeriodSlideOn) {
                 if(Voices[v].PeriodSlideWithLimit) {
                         d0 = Voices[v].PeriodSlidePeriod - Voices[v].PeriodSlideLimit;
                         d2 = Voices[v].PeriodSlideSpeed;
                         if(d0 > 0) d2 = -d2;
                         if(d0) {
                                 d3 = (d0 + d2) ^ d0;
                                 if(d3 >= 0) d0 = Voices[v].PeriodSlidePeriod + d2;
                                        else d0 = Voices[v].PeriodSlideLimit;
                                 Voices[v].PeriodSlidePeriod = d0;
                                 Voices[v].PlantPeriod = 1;
                         }
                 } else {
                         Voices[v].PeriodSlidePeriod += Voices[v].PeriodSlideSpeed;
                         Voices[v].PlantPeriod = 1;
                 }
         }
         //Vibrato
         if(Voices[v].VibratoDepth) {
                 if(Voices[v].VibratoDelay <= 0) {
                         Voices[v].VibratoPeriod = (VibratoTable[Voices[v].VibratoCurrent] * Voices[v].VibratoDepth) >> 7;
                         Voices[v].PlantPeriod = 1;
                         Voices[v].VibratoCurrent = (Voices[v].VibratoCurrent + Voices[v].VibratoSpeed) & 0x3f;
                 } else Voices[v].VibratoDelay--;
         }
         //PList
         if(Voices[v].Instrument && Voices[v].PerfCurrent < Voices[v].Instrument->PList.Length) {
                 if(--Voices[v].PerfWait <= 0) {
                         Cur = Voices[v].PerfCurrent++;
                         Voices[v].PerfWait = Voices[v].PerfSpeed;
                         if(Voices[v].PerfList->Entries[Cur].Waveform) {
                                 Voices[v].Waveform = Voices[v].PerfList->Entries[Cur].Waveform-1;
                                 Voices[v].NewWaveform = 1;
                                 Voices[v].PeriodPerfSlideSpeed = Voices[v].PeriodPerfSlidePeriod = 0;
                         }
                         //Holdwave
                         Voices[v].PeriodPerfSlideOn = 0;
                         for(i = 0; i < 2; i++) AHXPlayer_PListCommandParse(v, Voices[v].PerfList->Entries[Cur].FX[i], Voices[v].PerfList->Entries[Cur].FXParam[i]);
                         //GetNote
                         if(Voices[v].PerfList->Entries[Cur].Note) {
                                 Voices[v].InstrPeriod = Voices[v].PerfList->Entries[Cur].Note;
                                 Voices[v].PlantPeriod = 1;
                                 Voices[v].FixedNote = Voices[v].PerfList->Entries[Cur].Fixed;
                         }
                 }
         } else {
                 if(Voices[v].PerfWait) Voices[v].PerfWait--;
                                   else Voices[v].PeriodPerfSlideSpeed = 0;
         }
         //PerfPortamento
         if(Voices[v].PeriodPerfSlideOn) {
                 Voices[v].PeriodPerfSlidePeriod -= Voices[v].PeriodPerfSlideSpeed;
                 if(Voices[v].PeriodPerfSlidePeriod) Voices[v].PlantPeriod = 1;
         }
         if(Voices[v].Waveform == 3-1 && Voices[v].SquareOn) {
                 if(--Voices[v].SquareWait <= 0) {
                         int d1 = Voices[v].SquareLowerLimit;
                         int     d2 = Voices[v].SquareUpperLimit;
                         int d3 = Voices[v].SquarePos;
                         if(Voices[v].SquareInit) {
                                 Voices[v].SquareInit = 0;
                                 if(d3 <= d1) {
                                         Voices[v].SquareSlidingIn = 1;
                                         Voices[v].SquareSign = 1;
                                 } else if(d3 >= d2) {
                                         Voices[v].SquareSlidingIn = 1;
                                         Voices[v].SquareSign = -1;
                                 }
                         }
                         //NoSquareInit
                         if(d1 == d3 || d2 == d3) {
                                 if(Voices[v].SquareSlidingIn) {
                                         Voices[v].SquareSlidingIn = 0;
                                 } else {
                                         Voices[v].SquareSign = -Voices[v].SquareSign;
                                 }
                         }
                         d3 += Voices[v].SquareSign;
                         Voices[v].SquarePos = d3;
                         Voices[v].PlantSquare = 1;
                         Voices[v].SquareWait = Voices[v].Instrument->SquareSpeed;
                 }
         }
         if(Voices[v].FilterOn && --Voices[v].FilterWait <= 0) {
                 d1 = Voices[v].FilterLowerLimit;
                 d2 = Voices[v].FilterUpperLimit;
                 d3 = Voices[v].FilterPos;
                 if(Voices[v].FilterInit) {
                         Voices[v].FilterInit = 0;
                         if(d3 <= d1) {
                                 Voices[v].FilterSlidingIn = 1;
                                 Voices[v].FilterSign = 1;
                         } else if(d3 >= d2) {
                                 Voices[v].FilterSlidingIn = 1;
                                 Voices[v].FilterSign = -1;
                         }
                 }
                 //NoFilterInit
                 FMax = (Voices[v].FilterSpeed < 3)?(5-Voices[v].FilterSpeed):1;
                 for(i = 0; i < FMax; i++) {
                         if(d1 == d3 || d2 == d3) {
                                 if(Voices[v].FilterSlidingIn) {
                                         Voices[v].FilterSlidingIn = 0;
                                 } else {
                                         Voices[v].FilterSign = -Voices[v].FilterSign;
                                 }
                         }
                         d3 += Voices[v].FilterSign;
                 }
                 Voices[v].FilterPos = d3;
                 Voices[v].NewWaveform = 1;
                 Voices[v].FilterWait = Voices[v].FilterSpeed - 3;
                 if(Voices[v].FilterWait < 1) Voices[v].FilterWait = 1;
         }
         if(Voices[v].Waveform == 3-1 || Voices[v].PlantSquare) {
                 //CalcSquare
                 SquarePtr = &Waves->Squares[(Voices[v].FilterPos-0x20)*(0xfc+0xfc+0x80*0x1f+0x80+0x280*3)];
                 X = Voices[v].SquarePos << (5 - Voices[v].WaveLength);
                 if(X > 0x20) {
                         X = 0x40 - X;
                         Voices[v].SquareReverse = 1;
                 }
                 //OkDownSquare
                 if(--X) SquarePtr += X << 7;
                 Delta = 32 >> Voices[v].WaveLength;
                 WaveformTab[2] = Voices[v].SquareTempBuffer;
                 for(i = 0; i < (1 << Voices[v].WaveLength)*4; i++) {
                         Voices[v].SquareTempBuffer[i] = *SquarePtr;
                         SquarePtr += Delta;
                 }
                 Voices[v].NewWaveform = 1;
                 Voices[v].Waveform = 3-1;
                 Voices[v].PlantSquare = 0;
         }
         if(Voices[v].Waveform == 4-1) Voices[v].NewWaveform = 1;
         if(Voices[v].NewWaveform) {
                 AudioSource = WaveformTab[Voices[v].Waveform];
                 if(Voices[v].Waveform != 3-1) {
                         AudioSource += (Voices[v].FilterPos-0x20)*(0xfc+0xfc+0x80*0x1f+0x80+0x280*3);
                 }
                 if(Voices[v].Waveform < 3-1) {
                         AudioSource += Offsets[Voices[v].WaveLength];
                 }
                 if(Voices[v].Waveform == 4-1) {
                         //AddRandomMoving
                         AudioSource += (WNRandom & (2*0x280-1)) & ~1;
                         //GoOnRandom
                         WNRandom += 2239384;
                         WNRandom = ((((WNRandom >> 8) | (WNRandom << 24)) + 782323) ^ 75) - 6735;
                 }
                 Voices[v].AudioSource = AudioSource;
         }
         //StillHoldWaveform
         //AudioInitPeriod
         Voices[v].AudioPeriod = Voices[v].InstrPeriod;
         if(!Voices[v].FixedNote) Voices[v].AudioPeriod += Voices[v].Transpose + Voices[v].TrackPeriod-1;
         if(Voices[v].AudioPeriod > 5*12) Voices[v].AudioPeriod = 5*12;
         if(Voices[v].AudioPeriod < 0)    Voices[v].AudioPeriod = 0;
         Voices[v].AudioPeriod = PeriodTable[Voices[v].AudioPeriod];
         if(!Voices[v].FixedNote) Voices[v].AudioPeriod += Voices[v].PeriodSlidePeriod;
         Voices[v].AudioPeriod += Voices[v].PeriodPerfSlidePeriod + Voices[v].VibratoPeriod;
         if(Voices[v].AudioPeriod > 0x0d60) Voices[v].AudioPeriod = 0x0d60;
         if(Voices[v].AudioPeriod < 0x0071) Voices[v].AudioPeriod = 0x0071;
         //AudioInitVolume
         Voices[v].AudioVolume = ((((((((Voices[v].ADSRVolume >> 8) * Voices[v].NoteMaxVolume) >> 6) * Voices[v].PerfSubVolume) >> 6) * Voices[v].TrackMasterVolume) >> 6) * MainVolume) >> 6;
 }
References AHXVoice::ADSR, AHXVoice::ADSRVolume, AHXEnvelope::aFrames, AHXPlayer_PListCommandParse(), AHXPlayer_ProcessStep(), AHXVoice::AudioPeriod, AHXVoice::AudioSource, AHXVoice::AudioVolume, AHXEnvelope::aVolume, AHXEnvelope::dFrames, AHXEnvelope::dVolume, AHXPList::Entries, AHXInstrument::Envelope, AHXVoice::FilterInit, AHXVoice::FilterLowerLimit, AHXVoice::FilterPos, AHXVoice::FilterSign, AHXVoice::FilterSlidingIn, AHXVoice::FilterSpeed, AHXVoice::FilterUpperLimit, AHXVoice::FilterWait, AHXPListEntry::Fixed, AHXVoice::FixedNote, AHXPListEntry::FXParam, AHXVoice::HardCut, AHXVoice::HardCutReleaseF, AHXVoice::InstrPeriod, AHXStep::Instrument, AHXVoice::Instrument, MainVolume, AHXVoice::NewWaveform, AHXVoice::NextTrack, AHXPListEntry::Note, AHXVoice::NoteCutOn, AHXVoice::NoteCutWait, AHXVoice::NoteDelayWait, AHXVoice::NoteMaxVolume, NoteNr, Offsets, AHXVoice::PerfCurrent, AHXVoice::PerfList, AHXVoice::PerfSpeed, AHXVoice::PerfWait, AHXVoice::PeriodPerfSlideOn, AHXVoice::PeriodPerfSlidePeriod, AHXVoice::PeriodPerfSlideSpeed, AHXVoice::PeriodSlideLimit, AHXVoice::PeriodSlidePeriod, AHXVoice::PeriodSlideSpeed, PeriodTable, AHXVoice::PlantPeriod, AHXVoice::PlantSquare, AHXEnvelope::rFrames, AHXEnvelope::rVolume, AHXEnvelope::sFrames, Song, AHXVoice::SquareInit, AHXVoice::SquareLowerLimit, AHXVoice::SquarePos, AHXVoice::SquareReverse, AHXWaves::Squares, AHXVoice::SquareSign, AHXVoice::SquareSlidingIn, AHXInstrument::SquareSpeed, AHXVoice::SquareTempBuffer, AHXVoice::SquareUpperLimit, AHXVoice::SquareWait, Tempo, AHXVoice::Track, AHXSong::TrackLength, AHXVoice::TrackPeriod, Tracks, AHXVoice::Transpose, AHXVoice::VibratoCurrent, AHXVoice::VibratoDelay, AHXVoice::VibratoDepth, AHXVoice::VibratoPeriod, AHXVoice::VibratoSpeed, VibratoTable, Voices, AHXVoice::VolumeSlideDown, AHXVoice::VolumeSlideUp, AHXPListEntry::Waveform, AHXVoice::Waveform, WaveformTab, AHXVoice::WaveLength, Waves, and WNRandom.
Referenced by AHXPlayer_PlayIRQ().
AHXPlayer_ProcessStep()
void AHXPlayer_ProcessStep (int v)
Definition at line 503 of file AHX.c.
 {
         int Note, Instrument, FX, FXParam, SquareLower, SquareUpper, d3, d4, d6, Neue, Alte, i;
         if(!Voices[v].TrackOn) return;
         Voices[v].VolumeSlideUp = Voices[v].VolumeSlideDown = 0;
         Note = Tracks[Positions[PosNr].Track[v]][NoteNr].Note;
         Instrument = Tracks[Positions[PosNr].Track[v]][NoteNr].Instrument;
         FX = Tracks[Positions[PosNr].Track[v]][NoteNr].FX;
         FXParam = Tracks[Positions[PosNr].Track[v]][NoteNr].FXParam;
         switch(FX) {
                 case 0x0: // Position Jump HI
                         if((FXParam & 0xf) > 0 && (FXParam & 0xf) <= 9)
                                 PosJump = FXParam & 0xf;
                         break;
                 case 0x5: // Volume Slide + Tone Portamento
                 case 0xa: // Volume Slide
                         Voices[v].VolumeSlideDown = FXParam & 0x0f;
                         Voices[v].VolumeSlideUp   = FXParam >> 4;
                         break;
                 case 0xb: // Position Jump
                         PosJump = PosJump*100 + (FXParam & 0x0f) + (FXParam >> 4)*10;
                         PatternBreak = 1;
                         break;
                 case 0xd: // Patternbreak
                         PosJump = PosNr + 1;
                         PosJumpNote = (FXParam & 0x0f) + (FXParam >> 4)*10;
                         if(PosJumpNote > Song.TrackLength) PosJumpNote = 0;
                         PatternBreak = 1;
                         break;
                 case 0xe: // Enhanced commands
                         switch(FXParam >> 4) {
                                 case 0xc: // Note Cut
                                         if((FXParam & 0x0f) < Tempo) {
                                                 Voices[v].NoteCutWait = FXParam & 0x0f;
                                                 if(Voices[v].NoteCutWait) {
                                                         Voices[v].NoteCutOn = 1;
                                                         Voices[v].HardCutRelease = 0;
                                                 }
                                         }
                                         break;
                                 case 0xd: // Note Delay
                                         if(Voices[v].NoteDelayOn) {
                                                 Voices[v].NoteDelayOn = 0;
                                         } else {
                                                 if((FXParam & 0x0f) < Tempo) {
                                                         Voices[v].NoteDelayWait = FXParam & 0x0f;
                                                         if(Voices[v].NoteDelayWait) {
                                                                 Voices[v].NoteDelayOn = 1;
                                                                 return;
                                                         }
                                                 }
                                         }
                                         break;
                         }
                         break;
                 case 0xf: // Speed
                         Tempo = FXParam;
                         break;
         }
         if(Instrument) {
                 Voices[v].PerfSubVolume = 0x40;
                 Voices[v].PeriodSlideSpeed = Voices[v].PeriodSlidePeriod = Voices[v].PeriodSlideLimit = 0;
                 Voices[v].ADSRVolume = 0;
                 Voices[v].Instrument = &Instruments[Instrument];
                 AHXVoice_CalcADSR(&Voices[v]);
                 //InitOnInstrument
                 Voices[v].WaveLength = Voices[v].Instrument->WaveLength;
                 Voices[v].NoteMaxVolume = Voices[v].Instrument->Volume;
                 //InitVibrato
                 Voices[v].VibratoCurrent = 0;
                 Voices[v].VibratoDelay = Voices[v].Instrument->VibratoDelay;
                 Voices[v].VibratoDepth = Voices[v].Instrument->VibratoDepth;
                 Voices[v].VibratoSpeed = Voices[v].Instrument->VibratoSpeed;
                 Voices[v].VibratoPeriod = 0;
                 //InitHardCut
                 Voices[v].HardCutRelease = Voices[v].Instrument->HardCutRelease;
                 Voices[v].HardCut = Voices[v].Instrument->HardCutReleaseFrames;
                 //InitSquare
                 Voices[v].IgnoreSquare = Voices[v].SquareSlidingIn = 0;
                 Voices[v].SquareWait = Voices[v].SquareOn = 0;
                 SquareLower = Voices[v].Instrument->SquareLowerLimit >> (5-Voices[v].WaveLength);
                 SquareUpper = Voices[v].Instrument->SquareUpperLimit >> (5-Voices[v].WaveLength);
                 if(SquareUpper < SquareLower) { int t = SquareUpper; SquareUpper = SquareLower; SquareLower = t; }
                 Voices[v].SquareUpperLimit = SquareUpper;
                 Voices[v].SquareLowerLimit = SquareLower;
                 //InitFilter
                 Voices[v].IgnoreFilter = Voices[v].FilterWait = Voices[v].FilterOn = 0;
                 Voices[v].FilterSlidingIn = 0;
                 d6 = Voices[v].Instrument->FilterSpeed;
                 d3 = Voices[v].Instrument->FilterLowerLimit;
                 d4 = Voices[v].Instrument->FilterUpperLimit;
                 if(d3 & 0x80) d6 |= 0x20;
                 if(d4 & 0x80) d6 |= 0x40;
                 Voices[v].FilterSpeed = d6;
                 d3 &= ~0x80;
                 d4 &= ~0x80;
                 if(d3 > d4) { int t = d3; d3 = d4; d4 = t; }
                 Voices[v].FilterUpperLimit = d4;
                 Voices[v].FilterLowerLimit = d3;
                 Voices[v].FilterPos = 32;
                 //Init PerfList
                 Voices[v].PerfWait  =  Voices[v].PerfCurrent = 0;
                 Voices[v].PerfSpeed =  Voices[v].Instrument->PList.Speed;
                 Voices[v].PerfList  = &Voices[v].Instrument->PList;
         }
         //NoInstrument
         Voices[v].PeriodSlideOn = 0;
         switch(FX) {
                 case 0x4: // Override filter
                         break;
                 case 0x9: // Set Squarewave-Offset
                         Voices[v].SquarePos = FXParam >> (5 - Voices[v].WaveLength);
                         Voices[v].PlantSquare = 1;
                         Voices[v].IgnoreSquare = 1;
                         break;
                 case 0x5: // Tone Portamento + Volume Slide
                 case 0x3: // Tone Portamento (Period Slide Up/Down w/ Limit)
                         if(FXParam != 0) Voices[v].PeriodSlideSpeed = FXParam;
                         if(Note) {
                                 Neue = PeriodTable[Note];
                                 Alte = PeriodTable[Voices[v].TrackPeriod];
                                 Alte -= Neue;
                                 Neue = Alte + Voices[v].PeriodSlidePeriod;
                                 if(Neue) Voices[v].PeriodSlideLimit = -Alte;
                         }
                         Voices[v].PeriodSlideOn = 1;
                         Voices[v].PeriodSlideWithLimit = 1;
                         goto NoNote;
         }
         // Note anschlagen
         if(Note) {
                 Voices[v].TrackPeriod = Note;
                 Voices[v].PlantPeriod = 1;
         }
 NoNote:
         switch(FX) {
                 case 0x1: // Portamento up (Period slide down)
                         Voices[v].PeriodSlideSpeed = -FXParam;
                         Voices[v].PeriodSlideOn = 1;
                         Voices[v].PeriodSlideWithLimit = 0;
                         break;
                 case 0x2: // Portamento down (Period slide up)
                         Voices[v].PeriodSlideSpeed = FXParam;
                         Voices[v].PeriodSlideOn = 1;
                         Voices[v].PeriodSlideWithLimit = 0;
                         break;
                 case 0xc: // Volume
                         if(FXParam <= 0x40)
                                 Voices[v].NoteMaxVolume = FXParam;
                         else {
                                 FXParam -= 0x50;
                                 if(FXParam <= 0x40)
                                         for(i = 0; i < 4; i++) Voices[i].TrackMasterVolume = FXParam;
                                 else {
                                         FXParam -= 0xa0 - 0x50;
                                         if(FXParam <= 0x40)
                                                 Voices[v].TrackMasterVolume = FXParam;
                                 }
                         }
                         break;
                 case 0xe: // Enhanced commands
                         switch(FXParam >> 4) {
                                 case 0x1: // Fineslide up (Period fineslide down)
                                         Voices[v].PeriodSlidePeriod = -(FXParam & 0x0f);
                                         Voices[v].PlantPeriod = 1;
                                         break;
                                 case 0x2: // Fineslide down (Period fineslide up)
                                         Voices[v].PeriodSlidePeriod = FXParam & 0x0f;
                                         Voices[v].PlantPeriod = 1;
                                         break;
                                 case 0x4: // Vibrato control
                                         Voices[v].VibratoDepth = FXParam & 0x0f;
                                         break;
                                 case 0xa: // Finevolume up
                                         Voices[v].NoteMaxVolume += FXParam & 0x0f;
                                         if(Voices[v].NoteMaxVolume > 0x40) Voices[v].NoteMaxVolume = 0x40;
                                         break;
                                 case 0xb: // Finevolume down
                                         Voices[v].NoteMaxVolume -= FXParam & 0x0f;
                                         if(Voices[v].NoteMaxVolume < 0) Voices[v].NoteMaxVolume = 0;
                                         break;
                         }
                         break;
         }
 }
References AHXVoice::ADSRVolume, AHXVoice_CalcADSR(), AHXInstrument::FilterLowerLimit, AHXVoice::FilterLowerLimit, AHXVoice::FilterOn, AHXVoice::FilterPos, AHXVoice::FilterSlidingIn, AHXInstrument::FilterSpeed, AHXVoice::FilterSpeed, AHXInstrument::FilterUpperLimit, AHXVoice::FilterUpperLimit, AHXVoice::FilterWait, AHXPListEntry::FX, AHXStep::FX, AHXPListEntry::FXParam, AHXStep::FXParam, AHXVoice::HardCut, AHXInstrument::HardCutRelease, AHXVoice::HardCutRelease, AHXInstrument::HardCutReleaseFrames, AHXVoice::IgnoreFilter, AHXVoice::IgnoreSquare, AHXStep::Instrument, AHXVoice::Instrument, Instruments, AHXPListEntry::Note, AHXStep::Note, AHXVoice::NoteCutOn, AHXVoice::NoteCutWait, AHXVoice::NoteDelayOn, AHXVoice::NoteDelayWait, AHXVoice::NoteMaxVolume, NoteNr, PatternBreak, AHXVoice::PerfCurrent, AHXVoice::PerfList, AHXVoice::PerfSpeed, AHXVoice::PerfSubVolume, AHXVoice::PerfWait, AHXVoice::PeriodSlideLimit, AHXVoice::PeriodSlideOn, AHXVoice::PeriodSlidePeriod, AHXVoice::PeriodSlideSpeed, AHXVoice::PeriodSlideWithLimit, PeriodTable, AHXVoice::PlantPeriod, AHXVoice::PlantSquare, AHXInstrument::PList, Positions, PosJump, PosJumpNote, PosNr, Song, AHXPList::Speed, AHXInstrument::SquareLowerLimit, AHXVoice::SquareLowerLimit, AHXVoice::SquareOn, AHXVoice::SquarePos, AHXVoice::SquareSlidingIn, AHXInstrument::SquareUpperLimit, AHXVoice::SquareUpperLimit, AHXVoice::SquareWait, Tempo, AHXPosition::Track, AHXSong::TrackLength, AHXVoice::TrackMasterVolume, AHXVoice::TrackPeriod, Tracks, AHXVoice::VibratoCurrent, AHXInstrument::VibratoDelay, AHXVoice::VibratoDelay, AHXInstrument::VibratoDepth, AHXVoice::VibratoDepth, AHXVoice::VibratoPeriod, AHXInstrument::VibratoSpeed, AHXVoice::VibratoSpeed, Voices, AHXInstrument::Volume, AHXVoice::VolumeSlideDown, AHXVoice::VolumeSlideUp, AHXInstrument::WaveLength, and AHXVoice::WaveLength.
Referenced by AHXPlayer_PlayIRQ(), and AHXPlayer_ProcessFrame().
AHXPlayer_SetAudio()
void AHXPlayer_SetAudio (int v)
Definition at line 976 of file AHX.c.
 {
     int i, WaveLoops;
         if(!Voices[v].TrackOn) {
                 Voices[v].VoiceVolume = 0;
                 return;
         }
         Voices[v].VoiceVolume = Voices[v].AudioVolume;
         if(Voices[v].PlantPeriod) {
                 Voices[v].PlantPeriod = 0;
                 Voices[v].VoicePeriod = Voices[v].AudioPeriod;
         }
         if(Voices[v].NewWaveform) {
                 if(Voices[v].Waveform == 4-1) {
                         memcpy(Voices[v].VoiceBuffer, Voices[v].AudioSource, 0x280);
                 } else {
                         WaveLoops = (1 << (5-Voices[v].WaveLength))*5;
                         for(i = 0; i < WaveLoops; i++) memcpy(&Voices[v].VoiceBuffer[i*4*(1 << Voices[v].WaveLength)], Voices[v].AudioSource, 4*(1 << Voices[v].WaveLength));
                 }
                 Voices[v].VoiceBuffer[0x280] = Voices[v].VoiceBuffer[0];
         }
 }
References AHXVoice::AudioPeriod, AHXVoice::AudioSource, AHXVoice::AudioVolume, memcpy(), AHXVoice::PlantPeriod, AHXVoice::VoiceBuffer, VoiceBuffer, AHXVoice::VoicePeriod, Voices, AHXVoice::VoiceVolume, AHXPListEntry::Waveform, and AHXVoice::WaveLength.
Referenced by AHXPlayer_PlayIRQ().
AHXPlayer_SetBoost()
void AHXPlayer_SetBoost (int boostval)
Definition at line 1056 of file AHX.c.
 {
         Boost = boostval;
         AHXOutput_SetOption(AHXOF_BOOST, Boost+1);
 }
References AHXOF_BOOST, AHXOutput_SetOption(), and Boost.
Referenced by AHX_SetBoost().
AHXPlayer_SetOversampling()
void AHXPlayer_SetOversampling (int enable)
Definition at line 1062 of file AHX.c.
 {
         Oversampling = enable;
 }
References Oversampling.
Referenced by AHX_ToggleOversampling().
AHXPlayer_VoiceOnOff()
void AHXPlayer_VoiceOnOff (int Voice, int OnOff)
Definition at line 1001 of file AHX.c.
 {
         if(Voice < 0 || Voice > 3) return;
         Voices[Voice].TrackOn = OnOff;
 }
References AHXVoice::TrackOn, and Voices.