ps2sdk: iop/system/alloc/src/alloc.c File Reference
alloc.c File Reference
#include <stdarg.h>
#include "types.h"
#include "defs.h"
#include "alloc.h"
#include "irx_imports.h"
Data Structures
struct heap_mem_header_t
Macros
#define MODNAME "alloc"
#define DEFAULT_HEAP_SIZE 128 * 1024
#define DEFAULT_ALIGNMENT 16
#define ALIGN(x, align) (((x)+((align)-1))&~((align)-1))
Functions
IRX_ID ("Basic alloc library", 1, 1)
static void alloc_lock ()
static void alloc_unlock ()
int _start (int argc, char **argv)
int shutdown ()
static void * alloc_sbrk (size_t increment)
static heap_mem_header_t * _heap_mem_fit (heap_mem_header_t *head, size_t size)
void * malloc (size_t size)
void * realloc (void *ptr, size_t size)
void * calloc (size_t n, size_t size)
void * memalign (size_t align, size_t size)
void free (void *ptr)
void * __mem_walk_begin ()
void __mem_walk_read (void *token, u32 *size, void **ptr, int *valid)
void * __mem_walk_inc (void *token)
int __mem_walk_end (void *token)
Variables
struct irx_export_table _exp_alloc
static vs32 alloc_sema = -1
u32 heap_size = DEFAULT_HEAP_SIZE
static u8 * heap_start
static u8 * heap_end
static u8 * _heap_ptr
static void * __alloc_heap_base = NULL
static heap_mem_header_t * __alloc_heap_head = NULL
static heap_mem_header_t * __alloc_heap_tail = NULL
Detailed Description
Basic alloc library
Definition in file alloc.c.
Macro Definition Documentation
ALIGN
#define ALIGN (x, align) (((x)+((align)-1))&~((align)-1))
Definition at line 92 of file alloc.c.
DEFAULT_ALIGNMENT
#define DEFAULT_ALIGNMENT 16
Use this to set the default malloc() alignment.
Definition at line 89 of file alloc.c.
DEFAULT_HEAP_SIZE
#define DEFAULT_HEAP_SIZE 128 * 1024
Definition at line 32 of file alloc.c.
MODNAME
#define MODNAME "alloc"
Definition at line 25 of file alloc.c.
Function Documentation
__mem_walk_begin()
void* __mem_walk_begin ()
Definition at line 436 of file alloc.c.
{
         return __alloc_heap_head;
 }
References __alloc_heap_head.
__mem_walk_end()
int __mem_walk_end (void * token)
Definition at line 455 of file alloc.c.
{
         return token == NULL;
 }
References NULL.
__mem_walk_inc()
void* __mem_walk_inc (void * token)
Definition at line 449 of file alloc.c.
{
         heap_mem_header_t * cur = (heap_mem_header_t *) token;
         return cur->next;
 }
References heap_mem_header_t::next.
__mem_walk_read()
void __mem_walk_read (void * token, u32 * size, void ** ptr, int * valid)
Definition at line 440 of file alloc.c.
{
         heap_mem_header_t * cur = (heap_mem_header_t *) token;
         *valid = 1;
         *size = cur->size;
         *ptr = cur->ptr;
 }
References heap_mem_header_t::ptr, and heap_mem_header_t::size.
_heap_mem_fit()
static heap_mem_header_t* _heap_mem_fit (heap_mem_header_t * head, size_t size) static
Find the lowest block that we can allocate AFTER, returning NULL if there are none.
Definition at line 125 of file alloc.c.
 {
         heap_mem_header_t *prev_mem = head;
         u32 prev_top, next_bot;
         while (prev_mem != NULL) {
                 if (prev_mem->next != NULL) {
                         prev_top = (u32)prev_mem->ptr + prev_mem->size;
                         next_bot = (u32)prev_mem->next - prev_top;
                         if (next_bot >= size)
                                 return prev_mem;
                 }
                 prev_mem = prev_mem->next;
         }
         return prev_mem;
 }
References heap_mem_header_t::next, NULL, heap_mem_header_t::ptr, and heap_mem_header_t::size.
Referenced by malloc().
alloc_lock()
static void alloc_lock () static
Definition at line 37 of file alloc.c.
{
     if (alloc_sema >= 0) {
         WaitSema(alloc_sema);
     }
 }
References alloc_sema, and WaitSema().
Referenced by free(), malloc(), memalign(), and realloc().
alloc_sbrk()
static void* alloc_sbrk (size_t increment) static
Definition at line 107 of file alloc.c.
 {
         u8 *mp, *ret = (void *)-1;
         if (increment == 0)
                 return _heap_ptr;
         /* If the area we want to allocated is past the end of our heap, we have a problem. */
         mp = _heap_ptr + increment;
         if (mp <= heap_end) {
                 ret = _heap_ptr;
                 _heap_ptr = mp;
         }
         return ret;
 }
References _heap_ptr, and heap_end.
Referenced by free(), malloc(), and realloc().
alloc_unlock()
static void alloc_unlock () static
Definition at line 43 of file alloc.c.
{
     if (alloc_sema >= 0) {
         SignalSema(alloc_sema);
     }
 }
References alloc_sema, and SignalSema().
Referenced by free(), malloc(), memalign(), and realloc().
calloc()
void* calloc (size_t n, size_t size)
Definition at line 307 of file alloc.c.
 {
         void *ptr = NULL;
         size_t sz = n * size;
         if ((ptr = malloc(sz)) == NULL)
                 return ptr;
         memset(ptr, 0, sz);
         return ptr;
 }
free()
void free (void * ptr)
Definition at line 370 of file alloc.c.
 {
         heap_mem_header_t *cur;
         void *heap_top;
         size_t size;
         if (!ptr)
                 return;
         alloc_lock();
         if (!__alloc_heap_head) {
                 alloc_unlock();
                 return;
         }
         /* Freeing the head pointer is a special case.  */
         if (ptr == __alloc_heap_head->ptr) {
                 size = __alloc_heap_head->size +
                         (size_t)(__alloc_heap_head->ptr - (void *)__alloc_heap_head);
                 __alloc_heap_head = __alloc_heap_head->next;
                 if (__alloc_heap_head != NULL) {
                         __alloc_heap_head->prev = NULL;
                 } else {
                         __alloc_heap_tail = NULL;
                         alloc_sbrk(-size);
                 }
                 alloc_unlock();
                 return;
         }
         cur = __alloc_heap_head;
         while (ptr != cur->ptr)  {
                 /* ptr isn't in our list */
                 if (cur->next == NULL) {
                         alloc_unlock();
                         return;
                 }
                 cur = cur->next;
         }
         /* Deallocate the block.  */
         if (cur->next != NULL) {
                 cur->next->prev = cur->prev;
         } else {
                 /* If this block was the last one in the list, shrink the heap.  */
                 __alloc_heap_tail = cur->prev;
                 /* We need to free (heap top) - (prev->ptr + prev->size), or else
                    we'll end up with an unallocatable block of heap.  */
                 heap_top = alloc_sbrk(0);
                 size = (u32)heap_top - (u32)(cur->prev->ptr + cur->prev->size);
                 alloc_sbrk(-size);
         }
         cur->prev->next = cur->next;
         alloc_unlock();
 }
References __alloc_heap_head, __alloc_heap_tail, alloc_lock(), alloc_sbrk(), alloc_unlock(), heap_mem_header_t::next, NULL, heap_mem_header_t::prev, heap_mem_header_t::ptr, and heap_mem_header_t::size.
Referenced by realloc().
IRX_ID()
IRX_ID ("Basic alloc library" , 1 , 1)
malloc()
void* malloc (size_t size)
Definition at line 144 of file alloc.c.
 {
         void *ptr = NULL, *mem_ptr;
         heap_mem_header_t *new_mem, *prev_mem;
         size_t mem_sz, heap_align_bytes;
         mem_sz = size + sizeof(heap_mem_header_t);
         if ((mem_sz & (DEFAULT_ALIGNMENT - 1)) != 0)
                 mem_sz = ALIGN(mem_sz, DEFAULT_ALIGNMENT);
         alloc_lock();
         /* If we don't have any allocated blocks, reserve the first block from
            the OS and initialize __alloc_heap_tail.  */
         if (__alloc_heap_head == NULL) {
                 /* Align the bottom of the heap to our default alignment.  */
                 if (__alloc_heap_base == NULL) {
                         heap_align_bytes = (u32)alloc_sbrk(0) & (DEFAULT_ALIGNMENT - 1);
                         alloc_sbrk(heap_align_bytes);
                         __alloc_heap_base = alloc_sbrk(0);
                 }
                 /* Allocate the physical heap and setup the head block.  */
                 if ((mem_ptr = alloc_sbrk(mem_sz)) == (void *)-1)
                         return ptr;     /* NULL */
                 ptr = (void *)((u32)mem_ptr + sizeof(heap_mem_header_t));
                 __alloc_heap_head       = (heap_mem_header_t *)mem_ptr;
                 __alloc_heap_head->ptr  = ptr;
                 __alloc_heap_head->size = mem_sz - sizeof(heap_mem_header_t);
                 __alloc_heap_head->prev = NULL;
                 __alloc_heap_head->next = NULL;
                 __alloc_heap_tail = __alloc_heap_head;
                 alloc_unlock();
                 return ptr;
         }
         /* Check to see if there's free space at the bottom of the heap.  */
         if ((__alloc_heap_base + mem_sz) < (void *)__alloc_heap_head) {
                 new_mem = (heap_mem_header_t *)__alloc_heap_base;
                 ptr     = (void *)((u32)new_mem + sizeof(heap_mem_header_t));
                 new_mem->ptr  = ptr;
                 new_mem->size = mem_sz - sizeof(heap_mem_header_t);
                 new_mem->prev = NULL;
                 new_mem->next = __alloc_heap_head;
                 new_mem->next->prev = new_mem;
                 __alloc_heap_head = new_mem;
                 alloc_unlock();
                 return ptr;
         }
         /* See if we can allocate the block without extending the heap. */
         prev_mem = _heap_mem_fit(__alloc_heap_head, mem_sz);
         if (prev_mem != NULL) {
                 new_mem = (heap_mem_header_t *)((u32)prev_mem->ptr + prev_mem->size);
                 ptr     = (void *)((u32)new_mem + sizeof(heap_mem_header_t));
                 new_mem->ptr  = ptr;
                 new_mem->size = mem_sz - sizeof(heap_mem_header_t);
                 new_mem->prev = prev_mem;
                 new_mem->next = prev_mem->next;
                 new_mem->next->prev = new_mem;
                 prev_mem->next = new_mem;
                 alloc_unlock();
                 return ptr;
         }
         /* Extend the heap, but make certain the block is inserted in
            order. */
         if ((mem_ptr = alloc_sbrk(mem_sz)) == (void *)-1) {
                 alloc_unlock();
                 return ptr;     /* NULL */
         }
         ptr = (void *)((u32)mem_ptr + sizeof(heap_mem_header_t));
         new_mem       = (heap_mem_header_t *)mem_ptr;
         new_mem->ptr  = ptr;
         new_mem->size = mem_sz - sizeof(heap_mem_header_t);
         new_mem->prev = __alloc_heap_tail;
         new_mem->next = NULL;
         __alloc_heap_tail->next = new_mem;
         __alloc_heap_tail       = new_mem;
         alloc_unlock();
         return ptr;
 }
Referenced by calloc(), memalign(), and realloc().
memalign()
void* memalign (size_t align, size_t size)
Definition at line 319 of file alloc.c.
 {
         heap_mem_header_t new_mem;
         heap_mem_header_t *cur_mem;
         heap_mem_header_t *old_mem;
         void *ptr = NULL;
         if (align <= DEFAULT_ALIGNMENT)
                 return malloc(size);
         /* Allocate with extra alignment bytes just in case it isn't aligned
            properly by malloc.  */
         if ((ptr = malloc(size + align)) == NULL)
                 return ptr;     /* NULL */
         /* If malloc returned it aligned for us we're fine.  */
         if (((u32)ptr & (align - 1)) == 0)
                 return ptr;
         alloc_lock();
         cur_mem = (heap_mem_header_t *)((u32)ptr - sizeof(heap_mem_header_t));
         cur_mem->size -= align;
         /* Otherwise, align the pointer and fixup our hearder accordingly.  */
         ptr = (void *)ALIGN((u32)ptr, align);
         old_mem = cur_mem;
         /* Copy the heap_mem_header_t locally, before repositioning (to make
            sure we don't overwrite ourselves.  */
         memcpy(&new_mem, cur_mem, sizeof(heap_mem_header_t));
         cur_mem = (heap_mem_header_t *)((u32)ptr - sizeof(heap_mem_header_t));
         memcpy(cur_mem, &new_mem, sizeof(heap_mem_header_t));
         if (cur_mem->prev)
                 cur_mem->prev->next = cur_mem;
         if (cur_mem->next)
                 cur_mem->next->prev = cur_mem;
         if (__alloc_heap_head == old_mem)
                 __alloc_heap_head = cur_mem;
         if (__alloc_heap_tail == old_mem)
                 __alloc_heap_tail = cur_mem;
         cur_mem->ptr = ptr;
         alloc_unlock();
         return ptr;
 }
References __alloc_heap_head, __alloc_heap_tail, ALIGN, alloc_lock(), alloc_unlock(), DEFAULT_ALIGNMENT, malloc(), memcpy(), heap_mem_header_t::next, NULL, heap_mem_header_t::prev, heap_mem_header_t::ptr, and heap_mem_header_t::size.
realloc()
void* realloc (void * ptr, size_t size)
Definition at line 240 of file alloc.c.
 {
         heap_mem_header_t *prev_mem;
         void *new_ptr = NULL;
         if (!size && ptr != NULL) {
                 free(ptr);
                 return new_ptr;
         }
         if (ptr == NULL)
                 return malloc(size);
         if ((size & (DEFAULT_ALIGNMENT - 1)) != 0)
                 size = ALIGN(size, DEFAULT_ALIGNMENT);
         alloc_lock();
         prev_mem = (heap_mem_header_t *)((u32)ptr - sizeof(heap_mem_header_t));
         /* Don't do anything if asked for same sized block. */
         /* If the new size is shorter, let's just shorten the block. */
         if (prev_mem->size >= size) {
                 /* However, if this is the last block, we have to shrink the heap. */
                 if (!prev_mem->next)
                         alloc_sbrk(ptr + size - alloc_sbrk(0));
                 prev_mem->size = size;
                 alloc_unlock();
                 return ptr;
         }
         /* We are asked for a larger block of memory. */
         /* Are we the last memory block ? */
         if (!prev_mem->next) {
                 /* Yes, let's just extend the heap then. */
                 if (alloc_sbrk(size - prev_mem->size) == (void*) -1)
                         return NULL;
                 prev_mem->size = size;
                 alloc_unlock();
                 return ptr;
         }
         /* Is the next block far enough so we can extend the current block ? */
         if ((prev_mem->next->ptr - ptr) > size) {
                 prev_mem->size = size;
                 alloc_unlock();
                 return ptr;
         }
         alloc_unlock();
         /* We got out of luck, let's allocate a new block of memory. */
         if ((new_ptr = malloc(size)) == NULL)
                 return new_ptr;
         /* New block is larger, we only copy the old data. */
         memcpy(new_ptr, ptr, prev_mem->size);
         free(ptr);
         return new_ptr;
 }
References ALIGN, alloc_lock(), alloc_sbrk(), alloc_unlock(), DEFAULT_ALIGNMENT, free(), malloc(), memcpy(), heap_mem_header_t::next, NULL, and heap_mem_header_t::size.
shutdown()
int shutdown (void)
Definition at line 77 of file alloc.c.
 {
     if (alloc_sema >= 0) {
         DeleteSema(alloc_sema);
     }
     FreeSysMemory(heap_start);
     return 0;
 }
References alloc_sema, DeleteSema(), FreeSysMemory(), and heap_start.
Variable Documentation
__alloc_heap_base
void* __alloc_heap_base = NULL static
Definition at line 103 of file alloc.c.
Referenced by malloc().
__alloc_heap_head
heap_mem_header_t* __alloc_heap_head = NULL static
Definition at line 104 of file alloc.c.
Referenced by __mem_walk_begin(), free(), malloc(), and memalign().
__alloc_heap_tail
heap_mem_header_t* __alloc_heap_tail = NULL static
Definition at line 105 of file alloc.c.
Referenced by free(), malloc(), and memalign().
_exp_alloc
struct irx_export_table _exp_alloc extern
Referenced by _start().
_heap_ptr
u8 * _heap_ptr static
Definition at line 35 of file alloc.c.
Referenced by _start(), and alloc_sbrk().
alloc_sema
vs32 alloc_sema = -1 static
Definition at line 30 of file alloc.c.
Referenced by _start(), alloc_lock(), alloc_unlock(), and shutdown().
heap_end
u8 * heap_end static
Definition at line 35 of file alloc.c.
Referenced by _start(), and alloc_sbrk().
heap_size
u32 heap_size = DEFAULT_HEAP_SIZE
Definition at line 34 of file alloc.c.
Referenced by _start().
heap_start
u8* heap_start static
Definition at line 35 of file alloc.c.
Referenced by _start(), and shutdown().