ps2sdk: iop/system/alloc/include/alloc.h File Reference
alloc.h File Reference
#include <types.h>
#include <irx.h>
Macros
#define alloc_IMPORTS_start DECLARE_IMPORT_TABLE(alloc, 1, 1)
#define alloc_IMPORTS_end END_IMPORT_TABLE
#define I_malloc DECLARE_IMPORT(4, malloc)
#define I_realloc DECLARE_IMPORT(5, realloc)
#define I_free DECLARE_IMPORT(6, free)
#define I_calloc DECLARE_IMPORT(7, calloc)
#define I_memalign DECLARE_IMPORT(8, memalign)
#define I___mem_walk_begin DECLARE_IMPORT(9, __mem_walk_begin)
#define I___mem_walk_read DECLARE_IMPORT(10, __mem_walk_read)
#define I___mem_walk_inc DECLARE_IMPORT(11, __mem_walk_inc)
#define I___mem_walk_end DECLARE_IMPORT(12, __mem_walk_end)
Functions
void * malloc (size_t size)
void * realloc (void *ptr, size_t size)
void free (void *ptr)
void * calloc (size_t n, size_t size)
void * memalign (size_t align, size_t size)
void * __mem_walk_begin ()
void __mem_walk_read (void *token, u32 *size, void **ptr, int *valid)
void * __mem_walk_inc (void *token)
int __mem_walk_end (void *token)
Detailed Description
Basic alloc library
Definition in file alloc.h.
Macro Definition Documentation
alloc_IMPORTS_end
#define alloc_IMPORTS_end END_IMPORT_TABLE
Definition at line 33 of file alloc.h.
alloc_IMPORTS_start
#define alloc_IMPORTS_start DECLARE_IMPORT_TABLE(alloc, 1, 1)
Definition at line 32 of file alloc.h.
I___mem_walk_begin
#define I___mem_walk_begin DECLARE_IMPORT(9, __mem_walk_begin)
Definition at line 40 of file alloc.h.
I___mem_walk_end
#define I___mem_walk_end DECLARE_IMPORT(12, __mem_walk_end)
Definition at line 43 of file alloc.h.
I___mem_walk_inc
#define I___mem_walk_inc DECLARE_IMPORT(11, __mem_walk_inc)
Definition at line 42 of file alloc.h.
I___mem_walk_read
#define I___mem_walk_read DECLARE_IMPORT(10, __mem_walk_read)
Definition at line 41 of file alloc.h.
I_calloc
#define I_calloc DECLARE_IMPORT(7, calloc)
Definition at line 38 of file alloc.h.
I_free
#define I_free DECLARE_IMPORT(6, free)
Definition at line 37 of file alloc.h.
I_malloc
#define I_malloc DECLARE_IMPORT(4, malloc)
Definition at line 35 of file alloc.h.
I_memalign
#define I_memalign DECLARE_IMPORT(8, memalign)
Definition at line 39 of file alloc.h.
I_realloc
#define I_realloc DECLARE_IMPORT(5, realloc)
Definition at line 36 of file alloc.h.
Function Documentation
__mem_walk_begin()
void* __mem_walk_begin ()
Definition at line 436 of file alloc.c.
{
         return __alloc_heap_head;
 }
References __alloc_heap_head.
__mem_walk_end()
int __mem_walk_end (void * token)
Definition at line 455 of file alloc.c.
{
         return token == NULL;
 }
References NULL.
__mem_walk_inc()
void* __mem_walk_inc (void * token)
Definition at line 449 of file alloc.c.
{
         heap_mem_header_t * cur = (heap_mem_header_t *) token;
         return cur->next;
 }
References heap_mem_header_t::next.
__mem_walk_read()
void __mem_walk_read (void * token, u32 * size, void ** ptr, int * valid)
Definition at line 440 of file alloc.c.
{
         heap_mem_header_t * cur = (heap_mem_header_t *) token;
         *valid = 1;
         *size = cur->size;
         *ptr = cur->ptr;
 }
References heap_mem_header_t::ptr, and heap_mem_header_t::size.
calloc()
void* calloc (size_t n, size_t size)
Definition at line 307 of file alloc.c.
 {
         void *ptr = NULL;
         size_t sz = n * size;
         if ((ptr = malloc(sz)) == NULL)
                 return ptr;
         memset(ptr, 0, sz);
         return ptr;
 }
References malloc(), memset(), and NULL.
free()
void free (void * ptr)
Definition at line 63 of file main.c.
 {
     int OldState;
     CpuSuspendIntr(&OldState);
     FreeSysMemory(ptr);
     CpuResumeIntr(OldState);
 }
malloc()
void* malloc (size_t size)
Definition at line 144 of file alloc.c.
 {
         void *ptr = NULL, *mem_ptr;
         heap_mem_header_t *new_mem, *prev_mem;
         size_t mem_sz, heap_align_bytes;
         mem_sz = size + sizeof(heap_mem_header_t);
         if ((mem_sz & (DEFAULT_ALIGNMENT - 1)) != 0)
                 mem_sz = ALIGN(mem_sz, DEFAULT_ALIGNMENT);
         alloc_lock();
         /* If we don't have any allocated blocks, reserve the first block from
            the OS and initialize __alloc_heap_tail.  */
         if (__alloc_heap_head == NULL) {
                 /* Align the bottom of the heap to our default alignment.  */
                 if (__alloc_heap_base == NULL) {
                         heap_align_bytes = (u32)alloc_sbrk(0) & (DEFAULT_ALIGNMENT - 1);
                         alloc_sbrk(heap_align_bytes);
                         __alloc_heap_base = alloc_sbrk(0);
                 }
                 /* Allocate the physical heap and setup the head block.  */
                 if ((mem_ptr = alloc_sbrk(mem_sz)) == (void *)-1)
                         return ptr;     /* NULL */
                 ptr = (void *)((u32)mem_ptr + sizeof(heap_mem_header_t));
                 __alloc_heap_head       = (heap_mem_header_t *)mem_ptr;
                 __alloc_heap_head->ptr  = ptr;
                 __alloc_heap_head->size = mem_sz - sizeof(heap_mem_header_t);
                 __alloc_heap_head->prev = NULL;
                 __alloc_heap_head->next = NULL;
                 __alloc_heap_tail = __alloc_heap_head;
                 alloc_unlock();
                 return ptr;
         }
         /* Check to see if there's free space at the bottom of the heap.  */
         if ((__alloc_heap_base + mem_sz) < (void *)__alloc_heap_head) {
                 new_mem = (heap_mem_header_t *)__alloc_heap_base;
                 ptr     = (void *)((u32)new_mem + sizeof(heap_mem_header_t));
                 new_mem->ptr  = ptr;
                 new_mem->size = mem_sz - sizeof(heap_mem_header_t);
                 new_mem->prev = NULL;
                 new_mem->next = __alloc_heap_head;
                 new_mem->next->prev = new_mem;
                 __alloc_heap_head = new_mem;
                 alloc_unlock();
                 return ptr;
         }
         /* See if we can allocate the block without extending the heap. */
         prev_mem = _heap_mem_fit(__alloc_heap_head, mem_sz);
         if (prev_mem != NULL) {
                 new_mem = (heap_mem_header_t *)((u32)prev_mem->ptr + prev_mem->size);
                 ptr     = (void *)((u32)new_mem + sizeof(heap_mem_header_t));
                 new_mem->ptr  = ptr;
                 new_mem->size = mem_sz - sizeof(heap_mem_header_t);
                 new_mem->prev = prev_mem;
                 new_mem->next = prev_mem->next;
                 new_mem->next->prev = new_mem;
                 prev_mem->next = new_mem;
                 alloc_unlock();
                 return ptr;
         }
         /* Extend the heap, but make certain the block is inserted in
            order. */
         if ((mem_ptr = alloc_sbrk(mem_sz)) == (void *)-1) {
                 alloc_unlock();
                 return ptr;     /* NULL */
         }
         ptr = (void *)((u32)mem_ptr + sizeof(heap_mem_header_t));
         new_mem       = (heap_mem_header_t *)mem_ptr;
         new_mem->ptr  = ptr;
         new_mem->size = mem_sz - sizeof(heap_mem_header_t);
         new_mem->prev = __alloc_heap_tail;
         new_mem->next = NULL;
         __alloc_heap_tail->next = new_mem;
         __alloc_heap_tail       = new_mem;
         alloc_unlock();
         return ptr;
 }
References __alloc_heap_base, __alloc_heap_head, __alloc_heap_tail, _heap_mem_fit(), ALIGN, alloc_lock(), alloc_sbrk(), alloc_unlock(), DEFAULT_ALIGNMENT, heap_mem_header_t::next, NULL, heap_mem_header_t::prev, heap_mem_header_t::ptr, and heap_mem_header_t::size.
memalign()
void* memalign (size_t align, size_t size)
Definition at line 319 of file alloc.c.
 {
         heap_mem_header_t new_mem;
         heap_mem_header_t *cur_mem;
         heap_mem_header_t *old_mem;
         void *ptr = NULL;
         if (align <= DEFAULT_ALIGNMENT)
                 return malloc(size);
         /* Allocate with extra alignment bytes just in case it isn't aligned
            properly by malloc.  */
         if ((ptr = malloc(size + align)) == NULL)
                 return ptr;     /* NULL */
         /* If malloc returned it aligned for us we're fine.  */
         if (((u32)ptr & (align - 1)) == 0)
                 return ptr;
         alloc_lock();
         cur_mem = (heap_mem_header_t *)((u32)ptr - sizeof(heap_mem_header_t));
         cur_mem->size -= align;
         /* Otherwise, align the pointer and fixup our hearder accordingly.  */
         ptr = (void *)ALIGN((u32)ptr, align);
         old_mem = cur_mem;
         /* Copy the heap_mem_header_t locally, before repositioning (to make
            sure we don't overwrite ourselves.  */
         memcpy(&new_mem, cur_mem, sizeof(heap_mem_header_t));
         cur_mem = (heap_mem_header_t *)((u32)ptr - sizeof(heap_mem_header_t));
         memcpy(cur_mem, &new_mem, sizeof(heap_mem_header_t));
         if (cur_mem->prev)
                 cur_mem->prev->next = cur_mem;
         if (cur_mem->next)
                 cur_mem->next->prev = cur_mem;
         if (__alloc_heap_head == old_mem)
                 __alloc_heap_head = cur_mem;
         if (__alloc_heap_tail == old_mem)
                 __alloc_heap_tail = cur_mem;
         cur_mem->ptr = ptr;
         alloc_unlock();
         return ptr;
 }
References __alloc_heap_head, __alloc_heap_tail, ALIGN, alloc_lock(), alloc_unlock(), DEFAULT_ALIGNMENT, malloc(), memcpy(), heap_mem_header_t::next, NULL, heap_mem_header_t::prev, heap_mem_header_t::ptr, and heap_mem_header_t::size.
realloc()
void* realloc (void * ptr, size_t size)
Definition at line 240 of file alloc.c.
 {
         heap_mem_header_t *prev_mem;
         void *new_ptr = NULL;
         if (!size && ptr != NULL) {
                 free(ptr);
                 return new_ptr;
         }
         if (ptr == NULL)
                 return malloc(size);
         if ((size & (DEFAULT_ALIGNMENT - 1)) != 0)
                 size = ALIGN(size, DEFAULT_ALIGNMENT);
         alloc_lock();
         prev_mem = (heap_mem_header_t *)((u32)ptr - sizeof(heap_mem_header_t));
         /* Don't do anything if asked for same sized block. */
         /* If the new size is shorter, let's just shorten the block. */
         if (prev_mem->size >= size) {
                 /* However, if this is the last block, we have to shrink the heap. */
                 if (!prev_mem->next)
                         alloc_sbrk(ptr + size - alloc_sbrk(0));
                 prev_mem->size = size;
                 alloc_unlock();
                 return ptr;
         }
         /* We are asked for a larger block of memory. */
         /* Are we the last memory block ? */
         if (!prev_mem->next) {
                 /* Yes, let's just extend the heap then. */
                 if (alloc_sbrk(size - prev_mem->size) == (void*) -1)
                         return NULL;
                 prev_mem->size = size;
                 alloc_unlock();
                 return ptr;
         }
         /* Is the next block far enough so we can extend the current block ? */
         if ((prev_mem->next->ptr - ptr) > size) {
                 prev_mem->size = size;
                 alloc_unlock();
                 return ptr;
         }
         alloc_unlock();
         /* We got out of luck, let's allocate a new block of memory. */
         if ((new_ptr = malloc(size)) == NULL)
                 return new_ptr;
         /* New block is larger, we only copy the old data. */
         memcpy(new_ptr, ptr, prev_mem->size);
         free(ptr);
         return new_ptr;
 }
References ALIGN, alloc_lock(), alloc_sbrk(), alloc_unlock(), DEFAULT_ALIGNMENT, free(), malloc(), memcpy(), heap_mem_header_t::next, NULL, and heap_mem_header_t::size.