ps2sdk: iop/dev9/atad/include/atad.h File Reference
atad.h File Reference
#include <types.h>
#include <irx.h>
Data Structures
struct ata_devinfo_t
Macros
#define ATA_DIR_READ 0
#define ATA_DIR_WRITE 1
#define ATA_RES_ERR_NOTREADY -501
#define ATA_RES_ERR_TIMEOUT -502
#define ATA_RES_ERR_IO -503
#define ATA_RES_ERR_NODATA -504
#define ATA_RES_ERR_NODEV -505
#define ATA_RES_ERR_CMD -506
#define ATA_RES_ERR_LOCKED -509
#define ATA_RES_ERR_ICRC -510
#define ata_device_dma_transfer ata_device_sector_io
#define atad_IMPORTS_start DECLARE_IMPORT_TABLE(atad, 1, 3)
#define atad_IMPORTS_end END_IMPORT_TABLE
#define I_ata_get_devinfo DECLARE_IMPORT(4, ata_get_devinfo)
#define I_ata_reset_devices DECLARE_IMPORT(5, ata_reset_devices)
#define I_ata_io_start DECLARE_IMPORT(6, ata_io_start)
#define I_ata_io_finish DECLARE_IMPORT(7, ata_io_finish)
#define I_ata_get_error DECLARE_IMPORT(8, ata_get_error)
#define I_ata_device_dma_transfer I_ata_device_sector_io
#define I_ata_device_sector_io DECLARE_IMPORT(9, ata_device_sector_io)
#define I_ata_device_sce_sec_set_password DECLARE_IMPORT(10, ata_device_sce_sec_set_password)
#define I_ata_device_sce_sec_unlock DECLARE_IMPORT(11, ata_device_sce_sec_unlock)
#define I_ata_device_sce_sec_erase DECLARE_IMPORT(12, ata_device_sce_sec_erase)
#define I_ata_device_idle DECLARE_IMPORT(13, ata_device_idle)
#define I_ata_device_sce_identify_drive DECLARE_IMPORT(14, ata_device_sce_identify_drive)
#define I_ata_device_smart_get_status DECLARE_IMPORT(15, ata_device_smart_get_status)
#define I_ata_device_smart_save_attr DECLARE_IMPORT(16, ata_device_smart_save_attr)
#define I_ata_device_flush_cache DECLARE_IMPORT(17, ata_device_flush_cache)
#define I_ata_device_idle_immediate DECLARE_IMPORT(18, ata_device_idle_immediate)
Functions
ata_devinfo_t * ata_get_devinfo (int device)
int ata_reset_devices (void)
int ata_io_start (void *buf, u32 blkcount, u16 feature, u16 nsector, u16 sector, u16 lcyl, u16 hcyl, u16 select, u16 command)
int ata_io_finish (void)
int ata_get_error (void)
int ata_device_sector_io (int device, void *buf, u32 lba, u32 nsectors, int dir)
int ata_device_sce_sec_set_password (int device, void *password)
int ata_device_sce_sec_unlock (int device, void *password)
int ata_device_sce_sec_erase (int device)
int ata_device_idle (int device, int period)
int ata_device_sce_identify_drive (int device, void *data)
int ata_device_smart_get_status (int device)
int ata_device_smart_save_attr (int device)
int ata_device_flush_cache (int device)
int ata_device_idle_immediate (int device)
Detailed Description
ATA Device Driver definitions and imports.
Definition in file atad.h.
Macro Definition Documentation
ata_device_dma_transfer
#define ata_device_dma_transfer ata_device_sector_io
Definition at line 58 of file atad.h.
ATA_DIR_READ
#define ATA_DIR_READ 0
Definition at line 23 of file atad.h.
ATA_DIR_WRITE
#define ATA_DIR_WRITE 1
Definition at line 24 of file atad.h.
ATA_RES_ERR_CMD
#define ATA_RES_ERR_CMD -506
Definition at line 45 of file atad.h.
ATA_RES_ERR_ICRC
#define ATA_RES_ERR_ICRC -510
Definition at line 47 of file atad.h.
ATA_RES_ERR_IO
#define ATA_RES_ERR_IO -503
Definition at line 42 of file atad.h.
ATA_RES_ERR_LOCKED
#define ATA_RES_ERR_LOCKED -509
Definition at line 46 of file atad.h.
ATA_RES_ERR_NODATA
#define ATA_RES_ERR_NODATA -504
Definition at line 43 of file atad.h.
ATA_RES_ERR_NODEV
#define ATA_RES_ERR_NODEV -505
Definition at line 44 of file atad.h.
ATA_RES_ERR_NOTREADY
#define ATA_RES_ERR_NOTREADY -501
Definition at line 40 of file atad.h.
ATA_RES_ERR_TIMEOUT
#define ATA_RES_ERR_TIMEOUT -502
Definition at line 41 of file atad.h.
atad_IMPORTS_end
#define atad_IMPORTS_end END_IMPORT_TABLE
Definition at line 74 of file atad.h.
atad_IMPORTS_start
#define atad_IMPORTS_start DECLARE_IMPORT_TABLE(atad, 1, 3)
Definition at line 73 of file atad.h.
I_ata_device_dma_transfer
#define I_ata_device_dma_transfer I_ata_device_sector_io
Definition at line 81 of file atad.h.
I_ata_device_flush_cache
#define I_ata_device_flush_cache DECLARE_IMPORT(17, ata_device_flush_cache)
Definition at line 90 of file atad.h.
I_ata_device_idle
#define I_ata_device_idle DECLARE_IMPORT(13, ata_device_idle)
Definition at line 86 of file atad.h.
I_ata_device_idle_immediate
#define I_ata_device_idle_immediate DECLARE_IMPORT(18, ata_device_idle_immediate)
Definition at line 91 of file atad.h.
I_ata_device_sce_identify_drive
#define I_ata_device_sce_identify_drive DECLARE_IMPORT(14, ata_device_sce_identify_drive)
Definition at line 87 of file atad.h.
I_ata_device_sce_sec_erase
#define I_ata_device_sce_sec_erase DECLARE_IMPORT(12, ata_device_sce_sec_erase)
Definition at line 85 of file atad.h.
I_ata_device_sce_sec_set_password
#define I_ata_device_sce_sec_set_password DECLARE_IMPORT(10, ata_device_sce_sec_set_password)
Definition at line 83 of file atad.h.
I_ata_device_sce_sec_unlock
#define I_ata_device_sce_sec_unlock DECLARE_IMPORT(11, ata_device_sce_sec_unlock)
Definition at line 84 of file atad.h.
I_ata_device_sector_io
#define I_ata_device_sector_io DECLARE_IMPORT(9, ata_device_sector_io)
Definition at line 82 of file atad.h.
I_ata_device_smart_get_status
#define I_ata_device_smart_get_status DECLARE_IMPORT(15, ata_device_smart_get_status)
Definition at line 88 of file atad.h.
I_ata_device_smart_save_attr
#define I_ata_device_smart_save_attr DECLARE_IMPORT(16, ata_device_smart_save_attr)
Definition at line 89 of file atad.h.
I_ata_get_devinfo
#define I_ata_get_devinfo DECLARE_IMPORT(4, ata_get_devinfo)
Definition at line 76 of file atad.h.
I_ata_get_error
#define I_ata_get_error DECLARE_IMPORT(8, ata_get_error)
Definition at line 80 of file atad.h.
I_ata_io_finish
#define I_ata_io_finish DECLARE_IMPORT(7, ata_io_finish)
Definition at line 79 of file atad.h.
I_ata_io_start
#define I_ata_io_start DECLARE_IMPORT(6, ata_io_start)
Definition at line 78 of file atad.h.
I_ata_reset_devices
#define I_ata_reset_devices DECLARE_IMPORT(5, ata_reset_devices)
Definition at line 77 of file atad.h.
Function Documentation
ata_device_flush_cache()
int ata_device_flush_cache (int device)
Definition at line 699 of file ps2atad.c.
 {
         int res;
         if(!(res = ata_io_start(NULL, 1, 0, 0, 0, 0, 0, (device << 4) & 0xffff, atad_devinfo[device].lba48?ATA_C_FLUSH_CACHE_EXT:ATA_C_FLUSH_CACHE))) res=ata_io_finish();
         return res;
 }
References ATA_C_FLUSH_CACHE, ATA_C_FLUSH_CACHE_EXT, ata_io_finish(), ata_io_start(), atad_devinfo, hdpro_io_finish(), hdpro_io_start(), and NULL.
Referenced by apaJournalFlush(), apaSaveError(), hddDevctl(), hddFormat(), and hddIoctl2().
ata_device_idle()
int ata_device_idle (int device, int period)
Definition at line 709 of file ps2atad.c.
 {
         int res;
         if(!(res = ata_io_start(NULL, 1, 0, period & 0xff, 0, 0, 0, (device << 4) & 0xffff, ATA_C_IDLE))) res=ata_io_finish();
         return res;
 }
References ATA_C_IDLE, ata_io_finish(), ata_io_start(), and NULL.
Referenced by ata_init_devices(), and hddDevctl().
ata_device_idle_immediate()
int ata_device_idle_immediate (int device)
Definition at line 1186 of file ps2atad.c.
 {
         int res;
         if (!(res = ata_io_start(NULL, 1, 0, 0, 0, 0, 0, (device << 4)&0xFFFF, ATA_C_IDLE_IMMEDIATE))) res = ata_io_finish();
         return res;
 }
References ATA_C_IDLE_IMMEDIATE, ata_io_finish(), ata_io_start(), and NULL.
Referenced by hddDevctl().
ata_device_sce_identify_drive()
int ata_device_sce_identify_drive (int device, void * data)
Definition at line 738 of file ps2atad.c.
 {
         int res;
         if(!(res = ata_io_start(data, 1, ATA_SCE_IDENTIFY_DRIVE, 0, 0, 0, 0, (device << 4) & 0xffff, ATA_C_SCE_SECURITY_CONTROL))) res=ata_io_finish();
         return res;
 }
References ATA_C_SCE_SECURITY_CONTROL, ata_io_finish(), ata_io_start(), and ATA_SCE_IDENTIFY_DRIVE.
Referenced by ata_init_devices(), and hddDevctl().
ata_device_sce_sec_erase()
int ata_device_sce_sec_erase (int device)
Definition at line 937 of file ps2atad.c.
 {
         ata_devinfo_t *devinfo = atad_devinfo;
         int res;
         if (!(devinfo[device].security_status & ATA_F_SEC_ENABLED) || !(devinfo[device].security_status & ATA_F_SEC_LOCKED)) return 0;
         /* First send the mandatory ERASE PREPARE command.  */
         if ((res = ata_io_start(NULL, 1, ATA_SCE_SECURITY_ERASE_PREPARE, 0, 0, 0, 0, (device << 4) & 0xffff, ATA_C_SCE_SECURITY_CONTROL)) != 0)
                 goto finish;
         if ((res = ata_io_finish()) != 0)
                 goto finish;
         if ((res = ata_io_start(NULL, 1, ATA_SCE_SECURITY_ERASE_UNIT, 0, 0, 0, 0, (device << 4) & 0xffff, ATA_C_SCE_SECURITY_CONTROL)) == 0)
                 res = ata_io_finish();
 finish:
         ata_get_security_status(device, devinfo, NULL);
         return res;
 }
References ATA_C_SCE_SECURITY_CONTROL, ATA_F_SEC_ENABLED, ATA_F_SEC_LOCKED, ata_get_security_status(), ata_io_finish(), ata_io_start(), ATA_SCE_SECURITY_ERASE_PREPARE, ATA_SCE_SECURITY_ERASE_UNIT, atad_devinfo, and NULL.
ata_device_sce_sec_set_password()
int ata_device_sce_sec_set_password (int device, void * password)
Definition at line 892 of file ps2atad.c.
 {
         ata_devinfo_t *devinfo = atad_devinfo;
         u16 *param = ata_param;
         int res;
         if (devinfo[device].security_status & ATA_F_SEC_ENABLED) return 0;
         memset(param, 0, 512);
         memcpy(param + 1, password, 32);
         res = ata_io_start(param, 1, ATA_SCE_SECURITY_SET_PASSWORD, 0, 0, 0, 0, (device << 4) & 0xffff, ATA_C_SCE_SECURITY_CONTROL);
         if (res == 0)
                 res = ata_io_finish();
         ata_get_security_status(device, devinfo, param);
         return res;
 }
References ATA_C_SCE_SECURITY_CONTROL, ATA_F_SEC_ENABLED, ata_get_security_status(), ata_io_finish(), ata_io_start(), ata_param, ATA_SCE_SECURITY_SET_PASSWORD, atad_devinfo, memcpy(), and memset().
ata_device_sce_sec_unlock()
int ata_device_sce_sec_unlock (int device, void * password)
Definition at line 912 of file ps2atad.c.
 {
         ata_devinfo_t *devinfo = atad_devinfo;
         u16 *param = ata_param;
         int res;
         if (!(devinfo[device].security_status & ATA_F_SEC_LOCKED)) return 0;
         memset(param, 0, 512);
         memcpy(param + 1, password, 32);
         if ((res = ata_io_start(param, 1, ATA_SCE_SECURITY_UNLOCK, 0, 0, 0, 0, (device << 4) & 0xffff, ATA_C_SCE_SECURITY_CONTROL)) != 0)
                 return res;
         if ((res = ata_io_finish()) != 0)
                 return res;
         /* Check to see if the drive was actually unlocked.  */
         ata_get_security_status(device, devinfo, param);
         if (devinfo[device].security_status & ATA_F_SEC_LOCKED)
                 return ATA_RES_ERR_LOCKED;
         return 0;
 }
References ATA_C_SCE_SECURITY_CONTROL, ATA_F_SEC_LOCKED, ata_get_security_status(), ata_io_finish(), ata_io_start(), ata_param, ATA_RES_ERR_LOCKED, ATA_SCE_SECURITY_UNLOCK, atad_devinfo, memcpy(), and memset().
Referenced by unlockDrive().
ata_device_sector_io()
int ata_device_sector_io (int device, void * buf, u32 lba, u32 nsectors, int dir)
Definition at line 821 of file ps2atad.c.
 {
         USE_SPD_REGS;
         int res = 0, retries;
         u16 sector, lcyl, hcyl, select, command, len;
         while (res == 0 && nsectors > 0) {
                 /* Variable lba is only 32 bits so no change for lcyl and hcyl.  */
                 lcyl = (lba >> 8) & 0xff;
                 hcyl = (lba >> 16) & 0xff;
                 if (atad_devinfo[device].lba48) {
                         /* Setup for 48-bit LBA.  */
                         len = (nsectors > 65536) ? 65536 : nsectors;
                         /* Combine bits 24-31 and bits 0-7 of lba into sector.  */
                         sector = ((lba >> 16) & 0xff00) | (lba & 0xff);
                         /* In v1.04, LBA was enabled here.  */
                         select = (device << 4) & 0xffff;
                         command = (dir == 1) ? ATA_C_WRITE_DMA_EXT : ATA_C_READ_DMA_EXT;
                 } else {
                         /* Setup for 28-bit LBA.  */
                         len = (nsectors > 256) ? 256 : nsectors;
                         sector = lba & 0xff;
                         /* In v1.04, LBA was enabled here.  */
                         select = ((device << 4) | ((lba >> 24) & 0xf)) & 0xffff;
                         command = (dir == 1) ? ATA_C_WRITE_DMA : ATA_C_READ_DMA;
                 }
                 for(retries = 3; retries > 0; retries--) {
 #ifdef ATA_GAMESTAR_WORKAROUND
                         /* Due to the retry loop, put this call (for the GameStar workaround) here instead of the old location. */
                         if (ata_gamestar_workaround)
                                 ata_set_dir(dir);
 #endif
                         if ((res = ata_io_start(buf, len, 0, len, sector, lcyl, hcyl, select, command)) != 0)
                                 break;
 #ifdef ATA_GAMESTAR_WORKAROUND
                         if (!ata_gamestar_workaround)
                                 ata_set_dir(dir);
 #else
                         /* Set up (part of) the transfer here. In v1.04, this was called at the top of the outer loop. */
                         ata_set_dir(dir);
 #endif
                         res = ata_io_finish();
                         /* In v1.04, this was not done. Neither was there a mechanism to retry if a non-permanent error occurs. */
                         SPD_REG16(SPD_R_IF_CTRL) &= ~SPD_IF_DMA_ENABLE;
                         if(res != ATA_RES_ERR_ICRC)
                                 break;
                 }
                 buf = (void*)((u8 *)buf + len * 512);
                 lba += len;
                 nsectors -= len;
         }
         return res;
 }
References ATA_C_READ_DMA, ATA_C_READ_DMA_EXT, ATA_C_READ_SECTOR, ATA_C_READ_SECTOR_EXT, ATA_C_WRITE_DMA, ATA_C_WRITE_DMA_EXT, ATA_C_WRITE_SECTOR, ATA_C_WRITE_SECTOR_EXT, ata_io_finish(), ata_io_start(), ATA_RES_ERR_ICRC, ata_set_dir(), atad_devinfo, hdpro_io_finish(), hdpro_io_start(), select, SPD_IF_DMA_ENABLE, SPD_R_IF_CTRL, SPD_REG16, and USE_SPD_REGS.
Referenced by apaGetFormat(), apaGetPartErrorSector(), apaJournalFlush(), apaJournalRestore(), apaJournalWrite(), apaOpen(), apaReadHeader(), apaSaveError(), apaWriteHeader(), fioDataTransfer(), hddDevctl(), hddFormat(), and ioctl2Transfer().
ata_device_smart_get_status()
int ata_device_smart_get_status (int device)
Definition at line 767 of file ps2atad.c.
 {
         USE_ATA_REGS;
         int res;
         res = ata_io_start(NULL, 1, ATA_S_SMART_RETURN_STATUS, 0, 0, 0x4f, 0xc2, (device << 4) & 0xffff, ATA_C_SMART);
         if (res)
                 return res;
         res = ata_io_finish();
         if (res)
                 return res;
         /* Check to see if the report exceeded the threshold.  */
         if (((ata_hwport->r_lcyl&0xFF) != 0x4f) || ((ata_hwport->r_hcyl&0xFF) != 0xc2)) {
                 M_PRINTF("Error: SMART report exceeded threshold.\n");
                 return 1;
         }
         return res;
 }
References ATA_C_SMART, ata_io_finish(), ata_io_start(), ATA_S_SMART_RETURN_STATUS, M_PRINTF, NULL, and USE_ATA_REGS.
Referenced by hddDevctl().
ata_device_smart_save_attr()
int ata_device_smart_save_attr (int device)
Definition at line 757 of file ps2atad.c.
 {
         int res;
         if(!(res = ata_io_start(NULL, 1, ATA_S_SMART_SAVE_ATTRIBUTE_VALUES, 0, 0, 0x4f, 0xc2, (device << 4) & 0xffff, ATA_C_SMART))) res=ata_io_finish();
         return res;
 }
References ATA_C_SMART, ata_io_finish(), ata_io_start(), ATA_S_SMART_SAVE_ATTRIBUTE_VALUES, and NULL.
Referenced by hddShutdownCb().
ata_get_devinfo()
ata_devinfo_t* ata_get_devinfo (int device)
Definition at line 1080 of file ps2atad.c.
 {
         if(!ata_devinfo_init){
                 ata_devinfo_init = 1;
                 if(ata_bus_reset() || ata_init_devices(atad_devinfo)) return NULL;
         }
         return &atad_devinfo[device];
 }
References ata_bus_reset(), ata_devinfo_init, ata_init_devices(), atad_devinfo, CDVDreg_STATUS, hdpro_io_finish(), hdpro_io_start(), HDPROreg_IO8, and NULL.
Referenced by _start().
ata_get_error()
int ata_get_error (void)
Definition at line 297 of file ps2atad.c.
 {
         USE_ATA_REGS;
         return ata_hwport->r_error & 0xff;
 }
References ATAreg_ERROR_RD, hdpro_io_read(), and USE_ATA_REGS.
Referenced by ata_dma_complete(), ata_io_finish(), and ata_pio_transfer().
ata_io_finish()
int ata_io_finish (void)
Definition at line 597 of file ps2atad.c.
 {
         USE_SPD_REGS;
         USE_ATA_REGS;
         ata_cmd_state_t *cmd_state = &atad_cmd_state;
         u32 bits;
         int i, res = 0, type = cmd_state->type;
         u16 stat;
         if (type == 1 || type == 6) {   /* Non-data commands.  */
                 WaitEventFlag(ata_evflg, ATA_EV_TIMEOUT|ATA_EV_COMPLETE, WEF_CLEAR|WEF_OR, &bits);
                 if (bits & ATA_EV_TIMEOUT) {    /* Timeout.  */
                         M_PRINTF("Error: ATA timeout on a non-data command.\n");
                         return ATA_RES_ERR_TIMEOUT;
                 }
         } else if (type == 4) {         /* DMA.  */
                 if ((res = ata_dma_complete(cmd_state->buf, cmd_state->blkcount,
                                                 cmd_state->dir)) < 0)
                         goto finish;
                 for (i = 0; i < 100; i++)
                         if ((stat = SPD_REG16(SPD_R_INTR_STAT) & 0x01))
                                 break;
                 if (!stat) {
                         dev9IntrEnable(SPD_INTR_ATA0);
                         WaitEventFlag(ata_evflg, ATA_EV_TIMEOUT|ATA_EV_COMPLETE, WEF_CLEAR|WEF_OR, &bits);
                         if (bits & ATA_EV_TIMEOUT) {
                                 M_PRINTF("Error: ATA timeout on DMA completion, buffer stat %04x\n", SPD_REG16(0x38));
                                 M_PRINTF("Error: istat %x, ienable %x\n", SPD_REG16(SPD_R_INTR_STAT), SPD_REG16(SPD_R_INTR_MASK));
                                 res = ATA_RES_ERR_TIMEOUT;
                         }
                 }
         } else {                        /* PIO transfers.  */
                 stat = ata_hwport->r_control;
                 if ((res = ata_wait_busy()) < 0)
                         goto finish;
                 /* Transfer each PIO data block.  */
                 while (--cmd_state->blkcount != -1) {
                         if ((res = ata_pio_transfer(cmd_state)) < 0)
                                 goto finish;
                         if ((res = ata_wait_busy()) < 0)
                                 goto finish;
                 }
         }
         if (res)
                 goto finish;
         /* Wait until the device isn't busy.  */
         if (ata_hwport->r_status & ATA_STAT_BUSY)
                 res = ata_wait_busy();
         if ((stat = ata_hwport->r_status) & ATA_STAT_ERR) {
                 M_PRINTF("Error: Command error: status 0x%02x, error 0x%02x.\n", stat, ata_get_error());
                 /* In v1.04, there was no check for ICRC. */
                 res = (ata_get_error() & ATA_ERR_ICRC) ? ATA_RES_ERR_ICRC : ATA_RES_ERR_IO;
         }
 finish:
         /* The command has completed (with an error or not), so clean things up.  */
         CancelAlarm(&ata_alarm_cb, NULL);
         /* Turn off the LED.  */
         dev9LEDCtl(0);
         if(res)
                 M_PRINTF("error: ATA failed, %d\n", res);
         return res;
 }
References ata_alarm_cb(), ata_dma_complete(), ATA_ERR_ICRC, ATA_EV_COMPLETE, ATA_EV_TIMEOUT, ata_evflg, ata_get_error(), ata_pio_transfer(), ATA_RES_ERR_ICRC, ATA_RES_ERR_IO, ATA_RES_ERR_TIMEOUT, ATA_STAT_BUSY, ATA_STAT_ERR, ata_wait_busy, atad_cmd_state, ATAreg_CONTROL_RD, ATAreg_STATUS_RD, ata_cmd_state_t::blkcount, ata_cmd_state_t::buf, CancelAlarm(), CDVDreg_STATUS, DelayThread(), dev9IntrEnable(), dev9LEDCtl(), ata_cmd_state_t::dir, hdpro_io_read(), HDPROreg_IO8, M_PRINTF, NULL, PollEventFlag(), resume_intr(), SPD_INTR_ATA0, SPD_R_INTR_MASK, SPD_R_INTR_STAT, SPD_REG16, suspend_intr(), ata_cmd_state_t::type, USE_ATA_REGS, USE_SPD_REGS, WaitEventFlag(), WEF_CLEAR, and WEF_OR.
Referenced by ata_device_flush_cache(), ata_device_identify(), ata_device_idle(), ata_device_idle_immediate(), ata_device_pkt_identify(), ata_device_sce_identify_drive(), ata_device_sce_sec_erase(), ata_device_sce_sec_set_password(), ata_device_sce_sec_unlock(), ata_device_sector_io(), ata_device_set_transfer_mode(), ata_device_smart_enable(), ata_device_smart_get_status(), ata_device_smart_save_attr(), and ata_device_standby_immediate().
ata_io_start()
int ata_io_start (void * buf, u32 blkcount, u16 feature, u16 nsector, u16 sector, u16 lcyl, u16 hcyl, u16 select, u16 command)
Definition at line 377 of file ps2atad.c.
 {
         USE_ATA_REGS;
         iop_sys_clock_t cmd_timeout;
         const ata_cmd_info_t *cmd_table;
         int i, res, type, cmd_table_size;
         int using_timeout, device = (select >> 4) & 1;
         u8 searchcmd;
         ClearEventFlag(ata_evflg, 0);
         if (!atad_devinfo[device].exists)
                 return ATA_RES_ERR_NODEV;
         if ((res = ata_device_select(device)) != 0)
                 return res;
         /* For the SCE and SMART commands, we need to search on the subcommand
         specified in the feature register.  */
         if (command == ATA_C_SCE_SECURITY_CONTROL) {
                 cmd_table = sec_ctrl_cmd_table;
                 cmd_table_size = SEC_CTRL_CMD_TABLE_SIZE;
                 searchcmd = (u8)feature;
         } else if (command == ATA_C_SMART) {
                 cmd_table = smart_cmd_table;
                 cmd_table_size = SMART_CMD_TABLE_SIZE;
                 searchcmd = (u8)feature;
         } else {
                 cmd_table = ata_cmd_table;
                 cmd_table_size = ATA_CMD_TABLE_SIZE;
                 searchcmd = (u8)command;
         }
         type = 0;
         for (i = 0; i < cmd_table_size; i++) {
                 if (searchcmd == cmd_table[i].command) {
                         type = cmd_table[i].type;
                         break;
                 }
         }
         if (!(atad_cmd_state.type = type & 0x7F))       //Non-SONY: ignore the 48-bit LBA flag.
                 return ATA_RES_ERR_CMD;
         atad_cmd_state.buf = buf;
         atad_cmd_state.blkcount = blkcount;
         /* Check that the device is ready if this the appropiate command.  */
         if (!(ata_hwport->r_control & 0x40)) {
                 switch (command) {
                         case ATA_C_DEVICE_RESET:
                         case ATA_C_EXECUTE_DEVICE_DIAGNOSTIC:
                         case ATA_C_INITIALIZE_DEVICE_PARAMETERS:
                         case ATA_C_PACKET:
                         case ATA_C_IDENTIFY_PACKET_DEVICE:
                                 break;
                         default:
                                 M_PRINTF("Error: Device %d is not ready.\n", device);
                                 return ATA_RES_ERR_NOTREADY;
                 }
         }
         /* Does this command need a timeout?  */
         using_timeout = 0;
         switch (type & 0x7F) {  //Non-SONY: ignore the 48-bit LBA flag.
                 case 1:
                 case 6:
                         using_timeout = 1;
                         break;
                 case 4:
                         atad_cmd_state.dir = (command != ATA_C_READ_DMA && command != ATA_C_READ_DMA_EXT);
                         using_timeout = 1;
                         break;
         }
         if (using_timeout) {
                 cmd_timeout.lo = 0x41eb0000;
                 cmd_timeout.hi = 0;
                 /* SECURITY ERASE UNIT needs a bit more time.  */
                 if (command == ATA_C_SCE_SECURITY_CONTROL && feature == ATA_SCE_SECURITY_ERASE_UNIT)
                         USec2SysClock(180000000, &cmd_timeout);
                 if ((res = SetAlarm(&cmd_timeout, &ata_alarm_cb, NULL)) < 0)
                         return res;
         }
         /* Enable the command completion interrupt.  */
         if ((type & 0x7F) == 1)
                 dev9IntrEnable(SPD_INTR_ATA0);
         /* Finally!  We send off the ATA command with arguments.  */
         ata_hwport->r_control = (using_timeout == 0) << 1;
         if(type&0x80) { //For the sake of achieving improved performance, write the registers twice only if required! This is also required for compatibility with the buggy firmware of certain PSX units.
                 /* 48-bit LBA requires writing to the address registers twice,
                    24 bits of the LBA address is written each time.
                    Writing to registers twice does not affect 28-bit LBA since
                    only the latest data stored in address registers is used.  */
                 ata_hwport->r_feature = (feature >> 8) & 0xff;
                 ata_hwport->r_nsector = (nsector >> 8) & 0xff;
                 ata_hwport->r_sector  = (sector >> 8) & 0xff;
                 ata_hwport->r_lcyl    = (lcyl >> 8) & 0xff;
                 ata_hwport->r_hcyl    = (hcyl >> 8) & 0xff;
         }
         ata_hwport->r_feature = feature & 0xff;
         ata_hwport->r_nsector = nsector & 0xff;
         ata_hwport->r_sector  = sector & 0xff;
         ata_hwport->r_lcyl    = lcyl & 0xff;
         ata_hwport->r_hcyl    = hcyl & 0xff;
         ata_hwport->r_select  = (select | ATA_SEL_LBA) & 0xff;  //In v1.04, LBA was enabled in the ata_device_sector_io function.
         ata_hwport->r_command = command & 0xff;
         /* Turn on the LED.  */
         dev9LEDCtl(1);
         return 0;
 }
References ata_alarm_cb(), ATA_C_DEVICE_RESET, ATA_C_EXECUTE_DEVICE_DIAGNOSTIC, ATA_C_IDENTIFY_PACKET_DEVICE, ATA_C_INITIALIZE_DEVICE_PARAMETERS, ATA_C_PACKET, ATA_C_READ_DMA, ATA_C_READ_DMA_EXT, ATA_C_SCE_SECURITY_CONTROL, ATA_C_SMART, ata_cmd_table, ATA_CMD_TABLE_SIZE, ata_device_select(), ata_evflg, ATA_RES_ERR_CMD, ATA_RES_ERR_NODEV, ATA_RES_ERR_NOTREADY, ATA_SCE_SECURITY_ERASE_UNIT, ATA_SEL_LBA, atad_cmd_state, atad_devinfo, ATAreg_COMMAND_WR, ATAreg_CONTROL_RD, ATAreg_CONTROL_WR, ATAreg_FEATURE_WR, ATAreg_HCYL_WR, ATAreg_LCYL_WR, ATAreg_NSECTOR_WR, ATAreg_SECTOR_WR, ATAreg_SELECT_WR, ata_cmd_state_t::blkcount, ata_cmd_state_t::buf, CDVDreg_STATUS, ClearEventFlag(), dev9IntrEnable(), dev9LEDCtl(), ata_cmd_state_t::dir, dummy(), hdpro_io_read(), hdpro_io_write(), HDPROreg_IO8, iop_sys_clock_t::hi, iop_sys_clock_t::lo, M_PRINTF, NULL, resume_intr(), sec_ctrl_cmd_table, SEC_CTRL_CMD_TABLE_SIZE, select, SetAlarm(), smart_cmd_table, SMART_CMD_TABLE_SIZE, SPD_INTR_ATA0, suspend_intr(), ata_cmd_info_t::type, ata_cmd_state_t::type, USE_ATA_REGS, and USec2SysClock().
Referenced by ata_device_flush_cache(), ata_device_identify(), ata_device_idle(), ata_device_idle_immediate(), ata_device_pkt_identify(), ata_device_sce_identify_drive(), ata_device_sce_sec_erase(), ata_device_sce_sec_set_password(), ata_device_sce_sec_unlock(), ata_device_sector_io(), ata_device_set_transfer_mode(), ata_device_smart_enable(), ata_device_smart_get_status(), ata_device_smart_save_attr(), and ata_device_standby_immediate().
ata_reset_devices()
int ata_reset_devices (void)
Definition at line 680 of file ps2atad.c.
 {
         USE_ATA_REGS;
         if (ata_hwport->r_control & 0x80)
                 return ATA_RES_ERR_NOTREADY;
         /* Disables device interrupt assertion and asserts SRST. */
         ata_hwport->r_control = 6;
         DelayThread(100);
         /* Disable ATA interrupts.  */
         ata_hwport->r_control = 2;
         DelayThread(3000);
         return ata_wait_busy();
 }
References ATA_RES_ERR_NOTREADY, ata_wait_busy, ATAreg_CONTROL_RD, ATAreg_CONTROL_WR, DelayThread(), hdpro_io_read(), hdpro_io_write(), and USE_ATA_REGS.
Referenced by ata_init_devices().