ps2sdk: iop/sound/audsrv/include/audsrv.h File Reference
audsrv.h File Reference
#include <types.h>
#include <irx.h>
Macros
#define AUDSRV_INIT 0x0000
#define AUDSRV_QUIT 0x0001
#define AUDSRV_FORMAT_OK 0x0002
#define AUDSRV_SET_FORMAT 0x0003
#define AUDSRV_PLAY_AUDIO 0x0004
#define AUDSRV_WAIT_AUDIO 0x0005
#define AUDSRV_STOP_AUDIO 0x0006
#define AUDSRV_SET_VOLUME 0x0007
#define AUDSRV_SET_THRESHOLD 0x0008
#define AUDSRV_PLAY_CD 0x0009
#define AUDSRV_STOP_CD 0x000a
#define AUDSRV_GET_CDPOS 0x000b
#define AUDSRV_GET_TRACKPOS 0x000c
#define AUDSRV_GET_NUMTRACKS 0x000d
#define AUDSRV_GET_TRACKOFFSET 0x000e
#define AUDSRV_PAUSE_CD 0x0011
#define AUDSRV_RESUME_CD 0x0012
#define AUDSRV_PLAY_SECTORS 0x0013
#define AUDSRV_GET_CD_STATUS 0x0014
#define AUDSRV_GET_CD_TYPE 0x0015
#define AUDSRV_INIT_ADPCM 0x0016
#define AUDSRV_LOAD_ADPCM 0x0017
#define AUDSRV_PLAY_ADPCM 0x0018
#define AUDSRV_SET_ADPCM_VOL 0x0019
#define AUDSRV_FILLBUF_CALLBACK 0x0001
#define AUDSRV_CDDA_CALLBACK 0x0002
#define AUDSRV_ERR_NOERROR 0x0000
#define AUDSRV_ERR_NOT_INITIALIZED 0x0001
#define AUDSRV_ERR_RPC_FAILED 0x0002
#define AUDSRV_ERR_FORMAT_NOT_SUPPORTED 0x0003
#define AUDSRV_ERR_OUT_OF_MEMORY 0x0004
#define AUDSRV_ERR_ARGS 0x0005
#define AUDSRV_ERR_NO_DISC 0x0006
#define AUDSRV_ERR_NO_MORE_CHANNELS 0x0007
#define audsrv_play_adpcm(id) audsrv_ch_play_adpcm(-1, id)
#define audsrv_IMPORTS_start DECLARE_IMPORT_TABLE(audsrv, 1, 1)
#define audsrv_IMPORTS_end END_IMPORT_TABLE
#define I_audsrv_init DECLARE_IMPORT(4, audsrv_init)
#define I_audsrv_quit DECLARE_IMPORT(5, audsrv_quit)
#define I_audsrv_format_ok DECLARE_IMPORT(6, audsrv_format_ok)
#define I_audsrv_set_format DECLARE_IMPORT(7, audsrv_set_format)
#define I_audsrv_wait_audio DECLARE_IMPORT(8, audsrv_wait_audio)
#define I_audsrv_play_audio DECLARE_IMPORT(9, audsrv_play_audio)
#define I_audsrv_stop_audio DECLARE_IMPORT(10, audsrv_stop_audio)
#define I_audsrv_set_volume DECLARE_IMPORT(11, audsrv_set_volume)
#define I_audsrv_play_cd DECLARE_IMPORT(12, audsrv_play_cd)
#define I_audsrv_stop_cd DECLARE_IMPORT(13, audsrv_stop_cd)
#define I_audsrv_set_threshold DECLARE_IMPORT(14, audsrv_set_threshold)
#define I_audsrv_get_cdpos DECLARE_IMPORT(15, audsrv_get_cdpos)
#define I_audsrv_get_trackpos DECLARE_IMPORT(16, audsrv_get_trackpos)
#define I_audsrv_get_numtracks DECLARE_IMPORT(17, audsrv_get_numtracks)
#define I_audsrv_get_track_offset DECLARE_IMPORT(18, audsrv_get_track_offset)
#define I_audsrv_cd_pause DECLARE_IMPORT(19, audsrv_cd_pause)
#define I_audsrv_cd_resume DECLARE_IMPORT(20, audsrv_cd_resume)
#define I_audsrv_cd_play_sectors DECLARE_IMPORT(21, audsrv_cd_play_sectors)
#define I_audsrv_get_cd_status DECLARE_IMPORT(22, audsrv_get_cd_status)
#define I_audsrv_get_cd_type DECLARE_IMPORT(23, audsrv_get_cd_type)
#define I_audsrv_adpcm_init DECLARE_IMPORT(24, audsrv_adpcm_init)
#define I_audsrv_load_adpcm DECLARE_IMPORT(25, audsrv_load_adpcm)
#define I_audsrv_play_adpcm I_audsrv_ch_play_adpcm
#define I_audsrv_ch_play_adpcm DECLARE_IMPORT(26, audsrv_ch_play_adpcm)
#define I_audsrv_adpcm_set_volume DECLARE_IMPORT(27, audsrv_adpcm_set_volume)
Functions
int audsrv_init ()
int audsrv_quit ()
int audsrv_format_ok (int freq, int bits, int channels)
int audsrv_set_format (int freq, int bits, int channels)
int audsrv_wait_audio (int buflen)
int audsrv_play_audio (const char *buf, int buflen)
int audsrv_stop_audio ()
int audsrv_set_volume (int vol)
int audsrv_play_cd (int track)
int audsrv_stop_cd ()
int audsrv_set_threshold (int amount)
int audsrv_get_cdpos ()
int audsrv_get_trackpos ()
int audsrv_get_numtracks ()
int audsrv_get_track_offset (int track)
int audsrv_cd_pause ()
int audsrv_cd_resume ()
int audsrv_cd_play_sectors (int start, int end)
int audsrv_get_cd_status ()
int audsrv_get_cd_type ()
int audsrv_adpcm_init ()
int audsrv_adpcm_set_volume (int ch, int vol)
void * audsrv_load_adpcm (u32 *buffer, int size, int id)
int audsrv_ch_play_adpcm (int ch, u32 id)
Detailed Description
audsrv IOP server
Definition in file audsrv.h.
Macro Definition Documentation
AUDSRV_CDDA_CALLBACK
#define AUDSRV_CDDA_CALLBACK 0x0002
Definition at line 53 of file audsrv.h.
AUDSRV_ERR_ARGS
#define AUDSRV_ERR_ARGS 0x0005
Definition at line 61 of file audsrv.h.
AUDSRV_ERR_FORMAT_NOT_SUPPORTED
#define AUDSRV_ERR_FORMAT_NOT_SUPPORTED 0x0003
Definition at line 59 of file audsrv.h.
AUDSRV_ERR_NO_DISC
#define AUDSRV_ERR_NO_DISC 0x0006
Definition at line 62 of file audsrv.h.
AUDSRV_ERR_NO_MORE_CHANNELS
#define AUDSRV_ERR_NO_MORE_CHANNELS 0x0007
Definition at line 63 of file audsrv.h.
AUDSRV_ERR_NOERROR
#define AUDSRV_ERR_NOERROR 0x0000
Definition at line 56 of file audsrv.h.
AUDSRV_ERR_NOT_INITIALIZED
#define AUDSRV_ERR_NOT_INITIALIZED 0x0001
Definition at line 57 of file audsrv.h.
AUDSRV_ERR_OUT_OF_MEMORY
#define AUDSRV_ERR_OUT_OF_MEMORY 0x0004
Definition at line 60 of file audsrv.h.
AUDSRV_ERR_RPC_FAILED
#define AUDSRV_ERR_RPC_FAILED 0x0002
Definition at line 58 of file audsrv.h.
AUDSRV_FILLBUF_CALLBACK
#define AUDSRV_FILLBUF_CALLBACK 0x0001
Definition at line 52 of file audsrv.h.
AUDSRV_FORMAT_OK
#define AUDSRV_FORMAT_OK 0x0002
audio control functions
Definition at line 26 of file audsrv.h.
AUDSRV_GET_CD_STATUS
#define AUDSRV_GET_CD_STATUS 0x0014
Definition at line 44 of file audsrv.h.
AUDSRV_GET_CD_TYPE
#define AUDSRV_GET_CD_TYPE 0x0015
Definition at line 45 of file audsrv.h.
AUDSRV_GET_CDPOS
#define AUDSRV_GET_CDPOS 0x000b
Definition at line 37 of file audsrv.h.
AUDSRV_GET_NUMTRACKS
#define AUDSRV_GET_NUMTRACKS 0x000d
Definition at line 39 of file audsrv.h.
AUDSRV_GET_TRACKOFFSET
#define AUDSRV_GET_TRACKOFFSET 0x000e
Definition at line 40 of file audsrv.h.
AUDSRV_GET_TRACKPOS
#define AUDSRV_GET_TRACKPOS 0x000c
Definition at line 38 of file audsrv.h.
audsrv_IMPORTS_end
#define audsrv_IMPORTS_end END_IMPORT_TABLE
Definition at line 98 of file audsrv.h.
audsrv_IMPORTS_start
#define audsrv_IMPORTS_start DECLARE_IMPORT_TABLE(audsrv, 1, 1)
Definition at line 97 of file audsrv.h.
AUDSRV_INIT
#define AUDSRV_INIT 0x0000
intialization and destruction functions
Definition at line 22 of file audsrv.h.
AUDSRV_INIT_ADPCM
#define AUDSRV_INIT_ADPCM 0x0016
Definition at line 47 of file audsrv.h.
AUDSRV_LOAD_ADPCM
#define AUDSRV_LOAD_ADPCM 0x0017
Definition at line 48 of file audsrv.h.
AUDSRV_PAUSE_CD
#define AUDSRV_PAUSE_CD 0x0011
Definition at line 41 of file audsrv.h.
AUDSRV_PLAY_ADPCM
#define AUDSRV_PLAY_ADPCM 0x0018
Definition at line 49 of file audsrv.h.
audsrv_play_adpcm
#define audsrv_play_adpcm (id) audsrv_ch_play_adpcm(-1, id)
Definition at line 94 of file audsrv.h.
AUDSRV_PLAY_AUDIO
#define AUDSRV_PLAY_AUDIO 0x0004
Definition at line 28 of file audsrv.h.
AUDSRV_PLAY_CD
#define AUDSRV_PLAY_CD 0x0009
cdrom functions
Definition at line 35 of file audsrv.h.
AUDSRV_PLAY_SECTORS
#define AUDSRV_PLAY_SECTORS 0x0013
Definition at line 43 of file audsrv.h.
AUDSRV_QUIT
#define AUDSRV_QUIT 0x0001
Definition at line 23 of file audsrv.h.
AUDSRV_RESUME_CD
#define AUDSRV_RESUME_CD 0x0012
Definition at line 42 of file audsrv.h.
AUDSRV_SET_ADPCM_VOL
#define AUDSRV_SET_ADPCM_VOL 0x0019
Definition at line 50 of file audsrv.h.
AUDSRV_SET_FORMAT
#define AUDSRV_SET_FORMAT 0x0003
Definition at line 27 of file audsrv.h.
AUDSRV_SET_THRESHOLD
#define AUDSRV_SET_THRESHOLD 0x0008
Definition at line 32 of file audsrv.h.
AUDSRV_SET_VOLUME
#define AUDSRV_SET_VOLUME 0x0007
Definition at line 31 of file audsrv.h.
AUDSRV_STOP_AUDIO
#define AUDSRV_STOP_AUDIO 0x0006
Definition at line 30 of file audsrv.h.
AUDSRV_STOP_CD
#define AUDSRV_STOP_CD 0x000a
Definition at line 36 of file audsrv.h.
AUDSRV_WAIT_AUDIO
#define AUDSRV_WAIT_AUDIO 0x0005
Definition at line 29 of file audsrv.h.
I_audsrv_adpcm_init
#define I_audsrv_adpcm_init DECLARE_IMPORT(24, audsrv_adpcm_init)
Definition at line 125 of file audsrv.h.
I_audsrv_adpcm_set_volume
#define I_audsrv_adpcm_set_volume DECLARE_IMPORT(27, audsrv_adpcm_set_volume)
Definition at line 129 of file audsrv.h.
I_audsrv_cd_pause
#define I_audsrv_cd_pause DECLARE_IMPORT(19, audsrv_cd_pause)
Definition at line 119 of file audsrv.h.
I_audsrv_cd_play_sectors
#define I_audsrv_cd_play_sectors DECLARE_IMPORT(21, audsrv_cd_play_sectors)
Definition at line 121 of file audsrv.h.
I_audsrv_cd_resume
#define I_audsrv_cd_resume DECLARE_IMPORT(20, audsrv_cd_resume)
Definition at line 120 of file audsrv.h.
I_audsrv_ch_play_adpcm
#define I_audsrv_ch_play_adpcm DECLARE_IMPORT(26, audsrv_ch_play_adpcm)
Definition at line 128 of file audsrv.h.
I_audsrv_format_ok
#define I_audsrv_format_ok DECLARE_IMPORT(6, audsrv_format_ok)
Definition at line 104 of file audsrv.h.
I_audsrv_get_cd_status
#define I_audsrv_get_cd_status DECLARE_IMPORT(22, audsrv_get_cd_status)
Definition at line 122 of file audsrv.h.
I_audsrv_get_cd_type
#define I_audsrv_get_cd_type DECLARE_IMPORT(23, audsrv_get_cd_type)
Definition at line 123 of file audsrv.h.
I_audsrv_get_cdpos
#define I_audsrv_get_cdpos DECLARE_IMPORT(15, audsrv_get_cdpos)
Definition at line 115 of file audsrv.h.
I_audsrv_get_numtracks
#define I_audsrv_get_numtracks DECLARE_IMPORT(17, audsrv_get_numtracks)
Definition at line 117 of file audsrv.h.
I_audsrv_get_track_offset
#define I_audsrv_get_track_offset DECLARE_IMPORT(18, audsrv_get_track_offset)
Definition at line 118 of file audsrv.h.
I_audsrv_get_trackpos
#define I_audsrv_get_trackpos DECLARE_IMPORT(16, audsrv_get_trackpos)
Definition at line 116 of file audsrv.h.
I_audsrv_init
#define I_audsrv_init DECLARE_IMPORT(4, audsrv_init)
Definition at line 100 of file audsrv.h.
I_audsrv_load_adpcm
#define I_audsrv_load_adpcm DECLARE_IMPORT(25, audsrv_load_adpcm)
Definition at line 126 of file audsrv.h.
I_audsrv_play_adpcm
#define I_audsrv_play_adpcm I_audsrv_ch_play_adpcm
Definition at line 127 of file audsrv.h.
I_audsrv_play_audio
#define I_audsrv_play_audio DECLARE_IMPORT(9, audsrv_play_audio)
Definition at line 107 of file audsrv.h.
I_audsrv_play_cd
#define I_audsrv_play_cd DECLARE_IMPORT(12, audsrv_play_cd)
Definition at line 112 of file audsrv.h.
I_audsrv_quit
#define I_audsrv_quit DECLARE_IMPORT(5, audsrv_quit)
Definition at line 101 of file audsrv.h.
I_audsrv_set_format
#define I_audsrv_set_format DECLARE_IMPORT(7, audsrv_set_format)
Definition at line 105 of file audsrv.h.
I_audsrv_set_threshold
#define I_audsrv_set_threshold DECLARE_IMPORT(14, audsrv_set_threshold)
Definition at line 114 of file audsrv.h.
I_audsrv_set_volume
#define I_audsrv_set_volume DECLARE_IMPORT(11, audsrv_set_volume)
Definition at line 109 of file audsrv.h.
I_audsrv_stop_audio
#define I_audsrv_stop_audio DECLARE_IMPORT(10, audsrv_stop_audio)
Definition at line 108 of file audsrv.h.
I_audsrv_stop_cd
#define I_audsrv_stop_cd DECLARE_IMPORT(13, audsrv_stop_cd)
Definition at line 113 of file audsrv.h.
I_audsrv_wait_audio
#define I_audsrv_wait_audio DECLARE_IMPORT(8, audsrv_wait_audio)
Definition at line 106 of file audsrv.h.
Function Documentation
audsrv_adpcm_init()
int audsrv_adpcm_init ()
Initializes adpcm unit of audsrv
Returns
zero on success, negative value on error
Definition at line 250 of file adpcm.c.
 {
         int voice;
         printf("audsrv_adpcm_init()\n");
         for (voice = 0; voice < 24; voice++)
         {
                 sceSdSetSwitch(SD_CORE_1 | SD_SWITCH_KOFF, (1 << voice));
                 sceSdSetParam(SD_CORE_1 | (voice << 1) | SD_VPARAM_VOLL, 0x3fff);
                 sceSdSetParam(SD_CORE_1 | (voice << 1) | SD_VPARAM_VOLR, 0x3fff);
         }
         if (adpcm_list_head != NULL)
         {
                 /* called second time, after samples were already uploaded */
                 free_all_samples();
         }
         return AUDSRV_ERR_NOERROR;
 }
References adpcm_list_head, AUDSRV_ERR_NOERROR, free_all_samples(), NULL, printf(), sceSdSetParam(), sceSdSetSwitch(), SD_CORE_1, SD_SWITCH_KOFF, SD_VPARAM_VOLL, and SD_VPARAM_VOLR.
Referenced by _start(), audsrv_quit(), and rpc_command().
audsrv_adpcm_set_volume()
int audsrv_adpcm_set_volume (int ch, int vol)
Sets output volume for the specified voice channel.
Parameters
ch Voice channel ID
vol volume in SPU2 units [0 .. 0x3fff]
Returns
0 on success, negative otherwise
Definition at line 277 of file adpcm.c.
 {
         if (vol < 0 || vol > MAX_VOLUME)
         {
                 /* bad joke */
                 return AUDSRV_ERR_ARGS;
         }
         sceSdSetParam(SD_CORE_1 | (ch << 1) | SD_VPARAM_VOLL, vol);
         sceSdSetParam(SD_CORE_1 | (ch << 1) | SD_VPARAM_VOLR, vol);
         return AUDSRV_ERR_NOERROR;
 }
References AUDSRV_ERR_ARGS, AUDSRV_ERR_NOERROR, MAX_VOLUME, sceSdSetParam(), SD_CORE_1, SD_VPARAM_VOLL, and SD_VPARAM_VOLR.
Referenced by rpc_command().
audsrv_cd_pause()
int audsrv_cd_pause ()
Pauses CD playing
Returns
status code
Definition at line 295 of file cdrom.c.
 {
         cd_paused = 1;
         return AUDSRV_ERR_NOERROR;
 }
References AUDSRV_ERR_NOERROR, and cd_paused.
Referenced by rpc_command().
audsrv_cd_play_sectors()
int audsrv_cd_play_sectors (int start, int end)
Starts playing cdda sectors from disc
Parameters
start first sector to play
end stop playing at this sector
Returns
status code
Starts the cdda feeding thread at the given sector. Any previously set up playback is stopped. If a callback was set, it will NOT be called, as the thread is stopped abnormally.
Definition at line 465 of file cdrom.c.
 {
         printf("audsrv: cd_play_sectors: %d %d\n", start, end);
         if (initialize_cdda() < 0)
         {
                 printf("audsrv: initialized cdda failed\n");
                 return AUDSRV_ERR_NOT_INITIALIZED; //FIXME
         }
         /* stop previous track (and delete running thread) */
         audsrv_stop_cd();
         cdda_play_start = start;
         cdda_play_end = end;
         cdda_pos = start;
         printf("audsrv: creating cdda feed thread\n");
         /* .. and start a new one! */
         cdda_play_tid = create_thread(cdda_procedure, 48, 0);
         if (cdda_play_tid < 0)
         {
                 return AUDSRV_ERR_OUT_OF_MEMORY;
         }
         printf("cdda thread 0x%x started\n", cdda_play_tid);
         cd_playing = 1;
         return AUDSRV_ERR_NOERROR;
 }
References AUDSRV_ERR_NOERROR, AUDSRV_ERR_NOT_INITIALIZED, AUDSRV_ERR_OUT_OF_MEMORY, audsrv_stop_cd(), cd_playing, cdda_play_end, cdda_play_start, cdda_play_tid, cdda_pos, cdda_procedure(), create_thread(), initialize_cdda(), and printf().
Referenced by audsrv_play_cd(), and rpc_command().
audsrv_cd_resume()
int audsrv_cd_resume ()
Resumes CD playing
Returns
status code
Definition at line 304 of file cdrom.c.
 {
         cd_paused = 0;
         return AUDSRV_ERR_NOERROR;
 }
References AUDSRV_ERR_NOERROR, and cd_paused.
Referenced by rpc_command().
audsrv_ch_play_adpcm()
int audsrv_ch_play_adpcm (int ch, u32 id)
Plays an adpcm sample already uploaded with audsrv_load_adpcm()
Parameters
ch channel identifier. Specifies one of the 24 voice channel to play the ADPCM channel on. If set to an invalid channel ID, an unoccupied channel will be selected.
id sample identifier, as specified in load()
Returns
zero on success, negative value on error
When ch is set to an invalid channel ID, the sample will be played in an unoccupied channel. If all 24 channels are used, then -AUDSRV_ERR_NO_MORE_CHANNELS is returned. When ch is set to a valid channel ID, -AUDSRV_ERR_NO_MORE_CHANNELS is returned if the channel is currently in use. Trying to play a sample which is unavailable will result in -AUDSRV_ERR_ARGS
Definition at line 208 of file adpcm.c.
 {
         int channel;
         u32 endx;
         adpcm_list_t *a;
         a = adpcm_loaded(id);
         if (a == NULL)
         {
                 /* bad joke */
                 return AUDSRV_ERR_ARGS;
         }
         /* sample was loaded */
         if (ch >= 0 && ch < 24)
         {
                 endx = sceSdGetSwitch(SD_CORE_1 | SD_SWITCH_ENDX);
                 if (!(endx & (1 << ch)))
                 {
                         /* Channel in use. */
                         return -AUDSRV_ERR_NO_MORE_CHANNELS;
                 }
                 channel = ch;
         }
         else
         {
                 channel = audsrv_adpcm_alloc_channel();
                 if (channel < 0)
                         return channel;
         }
         sceSdSetParam(SD_CORE_1 | (channel << 1) | SD_VPARAM_PITCH, a->pitch);
         sceSdSetAddr(SD_CORE_1 | (channel << 1) | SD_VOICE_START, a->spu2_addr);
         sceSdSetSwitch(SD_CORE_1 | SD_SWITCH_KON, (1 << channel));
         return AUDSRV_ERR_NOERROR;
 }
References adpcm_loaded(), audsrv_adpcm_alloc_channel(), AUDSRV_ERR_ARGS, AUDSRV_ERR_NO_MORE_CHANNELS, AUDSRV_ERR_NOERROR, NULL, adpcm_list_t::pitch, sceSdGetSwitch(), sceSdSetAddr(), sceSdSetParam(), sceSdSetSwitch(), SD_CORE_1, SD_SWITCH_ENDX, SD_SWITCH_KON, SD_VOICE_START, SD_VPARAM_PITCH, and adpcm_list_t::spu2_addr.
Referenced by rpc_command().
audsrv_format_ok()
int audsrv_format_ok (int freq, int bits, int channels)
Checks if the format noted by frequency and depth is supported
Parameters
freq frequency in hz
bits bits per sample (8, 16)
channels channels
Returns
positive on success, zero value on failure
Definition at line 152 of file audsrv.c.
 {
         if (find_upsampler(freq, bits, channels) != NULL)
         {
                 return 1;
         }
         /* unsupported format */
         return 0;
 }
References find_upsampler(), and NULL.
Referenced by audsrv_set_format(), and rpc_command().
audsrv_get_cd_status()
int audsrv_get_cd_status ()
Returns CD drive status
Returns
status according to PS2 native values
Definition at line 115 of file cdrom.c.
 {
         return sceCdStatus();
 }
References sceCdStatus().
Referenced by rpc_command().
audsrv_get_cd_type()
int audsrv_get_cd_type ()
Returns the type of disc in drive
Returns
disc type (according to native PS2 values) or -AUDSRV_ERR_NO_DISC
Definition at line 99 of file cdrom.c.
 {
         int type = sceCdGetDiskType();
         if (type == 0)
         {
                 /* no disc inserted */
                 return -AUDSRV_ERR_NO_DISC;
         }
         return type;
 }
References AUDSRV_ERR_NO_DISC, and sceCdGetDiskType().
Referenced by initialize_cdda(), and rpc_command().
audsrv_get_cdpos()
int audsrv_get_cdpos ()
Returns the current sector being played
Returns
sector number, or negative value on error
Definition at line 431 of file cdrom.c.
 {
         if (cd_playing == 0)
         {
                 /* cdrom not playing */
                 return 0;
         }
         return cdda_pos;
 }
References cd_playing, and cdda_pos.
Referenced by rpc_command().
audsrv_get_numtracks()
int audsrv_get_numtracks ()
Returns the number of tracks available on the CD in tray
Returns
positive track count, or negative error status code
Definition at line 202 of file cdrom.c.
 {
         int err = initialize_cdda();
         if (err < 0)
         {
                 return err;
         }
         return toc.num_tracks;
 }
References initialize_cdda(), cdda_toc::num_tracks, and toc.
Referenced by rpc_command().
audsrv_get_track_offset()
int audsrv_get_track_offset (int track)
Returns the first sector for the given track
Parameters
track track index, must be between 1 and the trackcount
Returns
sector number, or negative status code
Definition at line 217 of file cdrom.c.
 {
         int err;
         int offset;
         err = initialize_cdda();
         if (err < 0)
         {
                 return err;
         }
         if (track < 1 || track > toc.num_tracks)
         {
                 return -AUDSRV_ERR_ARGS;
         }
         offset = (toc.tracks[track].minute) * 60 + toc.tracks[track].second;
         offset = (offset * 75) + toc.tracks[track].sector - 150;
         return offset;
 }
References AUDSRV_ERR_ARGS, initialize_cdda(), sceCdlLOCCD::minute, cdda_toc::num_tracks, sceCdlLOCCD::second, sceCdlLOCCD::sector, toc, and cdda_toc::tracks.
Referenced by audsrv_play_cd(), and rpc_command().
audsrv_get_trackpos()
int audsrv_get_trackpos ()
Returns the current sector being played, relative to first sector in track
Returns
sector number, or negative value on error
Definition at line 445 of file cdrom.c.
 {
         if (cd_playing == 0)
         {
                 /* cdrom not playing */
                 return 0;
         }
         return cdda_pos - cdda_play_start;
 }
References cd_playing, cdda_play_start, and cdda_pos.
Referenced by rpc_command().
audsrv_init()
int audsrv_init ()
Initializes audsrv library
Returns
0 on success
Definition at line 215 of file audsrv.c.
 {
         if (initialized)
         {
                 return 0;
         }
         /* initialize libsd */
         if (sceSdInit(SD_INIT_COLD) < 0)
         {
                 printf("audsrv: failed to initialize libsd\n");
                 return -1;
         }
         readpos = 0;
         writepos = 0;
         /* initialize transfer_complete's semaphore */
         transfer_sema = CreateMutex(0);
         if (transfer_sema < 0)
         {
                 return AUDSRV_ERR_OUT_OF_MEMORY;
         }
         queue_sema = CreateMutex(0);
         if (queue_sema < 0)
         {
                 DeleteSema(transfer_sema);
                 return AUDSRV_ERR_OUT_OF_MEMORY;
         }
         /* audio is always playing in the background. trick is to
          * set the data input volume to zero
          */
         audsrv_stop_audio();
         /* initialize transfer-complete callback */
         sceSdSetTransCallback(AUDSRV_BLOCK_DMA_CH, (void *)transfer_complete);
         sceSdBlockTrans(AUDSRV_BLOCK_DMA_CH, SD_TRANS_LOOP, core1_buf, sizeof(core1_buf), 0);
         /* default to SPU's native */
         audsrv_set_format(48000, 16, 2);
         play_tid = create_thread(play_thread, 39, 0);
         printf("audsrv: playing thread 0x%x started\n", play_tid);
         printf("audsrv: kickstarted\n");
         initialized = 1;
         return AUDSRV_ERR_NOERROR;
 }
References AUDSRV_BLOCK_DMA_CH, AUDSRV_ERR_NOERROR, AUDSRV_ERR_OUT_OF_MEMORY, audsrv_set_format(), audsrv_stop_audio(), core1_buf, create_thread(), CreateMutex(), DeleteSema(), initialized, play_thread(), play_tid, printf(), queue_sema, readpos, sceSdBlockTrans(), sceSdInit(), sceSdSetTransCallback(), SD_INIT_COLD, SD_TRANS_LOOP, transfer_complete(), transfer_sema, and writepos.
Referenced by rpc_command().
audsrv_load_adpcm()
void* audsrv_load_adpcm (u32 * buffer, int size, int id)
Uploads a sample to SPU2 memory
Parameters
buffer pointer to adpcm sample header
size size of sample in bytes
id sample identifier (to be later used in play())
Returns
pointer to local adpcm buffer
Definition at line 116 of file adpcm.c.
 {
         adpcm_list_t *adpcm;
         adpcm = adpcm_loaded(id);
         if (adpcm == NULL)
         {
                 if (adpcm_list_head == NULL)
                 {
                         /* first entry ever! yay! */
                         adpcm = alloc_new_sample();
                         adpcm->id = id;
                         adpcm->spu2_addr = 0x5010; /* Need to change this so it considers to PCM streaming space usage :) */
                         adpcm->size = size - 16; /* header is 16 bytes */
                         adpcm->next = NULL;
                         audsrv_read_adpcm_header(adpcm, buffer);
                         adpcm_list_head = adpcm;
                         adpcm_list_tail = adpcm_list_head;
                 }
                 else
                 {
                         /* add at the end of the list */
                         adpcm = alloc_new_sample();
                         adpcm->id = id;
                         adpcm->spu2_addr = adpcm_list_tail->spu2_addr + adpcm_list_tail->size;
                         adpcm->size = size - 16; /* header is 16 bytes */
                         adpcm->next = NULL;
                         audsrv_read_adpcm_header(adpcm, buffer);
                         adpcm_list_tail->next = adpcm;
                         adpcm_list_tail = adpcm;
                 }
                 /* DMA from IOP to SPU2 */
                 sceSdVoiceTrans(AUDSRV_VOICE_DMA_CH, SD_TRANS_WRITE | SD_TRANS_MODE_DMA, ((u8*)buffer)+16, (u32*)adpcm->spu2_addr, adpcm->size);
                 sceSdVoiceTransStatus(AUDSRV_VOICE_DMA_CH, 1);
         }
         sbuffer[0] = 0;
         sbuffer[1] = adpcm->pitch;
         sbuffer[2] = adpcm->loop;
         sbuffer[3] = adpcm->channels;
         return sbuffer;
 }
References adpcm_list_head, adpcm_list_tail, adpcm_loaded(), alloc_new_sample(), audsrv_read_adpcm_header(), AUDSRV_VOICE_DMA_CH, buffer, adpcm_list_t::channels, adpcm_list_t::id, adpcm_list_t::loop, adpcm_list_t::next, NULL, adpcm_list_t::pitch, sbuffer, sceSdVoiceTrans(), sceSdVoiceTransStatus(), SD_TRANS_MODE_DMA, SD_TRANS_WRITE, adpcm_list_t::size, and adpcm_list_t::spu2_addr.
Referenced by rpc_command().
audsrv_play_audio()
int audsrv_play_audio (const char * buf, int buflen)
Uploads audio buffer to SPU
Parameters
buf audio chunk
buflen size of chunk in bytes
Returns
positive number of bytes sent to processor or negative error status
Plays an audio buffer; It will not interrupt a playing buffer, rather queue it up and play it as soon as possible without interfering with fluent streaming. The buffer and buflen are given in host format (i.e, 11025hz 8bit stereo.)
Definition at line 323 of file audsrv.c.
 {
         int sent = 0;
         if (initialized == 0)
         {
                 return -AUDSRV_ERR_NOT_INITIALIZED;
         }
         if (playing == 0)
         {
                 /* audio is always playing, just change the volume */
                 playing = 1;
                 update_volume();
         }
         //printf("play audio %d bytes, readpos %d, writepos %d avail %d\n", buflen, readpos, writepos, audsrv_available());
         /* limit to what's available, no crossing possible */
         buflen = MIN(buflen, audsrv_available());
         while (buflen > 0)
         {
                 int copy = buflen;
                 if (writepos >= readpos)
                 {
                         copy = MIN(ringbuf_size - writepos, buflen);
                 }
                 memcpy(ringbuf + writepos, buf, copy);
                 buf = buf + copy;
                 buflen = buflen - copy;
                 sent = sent + copy;
                 writepos = writepos + copy;
                 if (writepos >= ringbuf_size)
                 {
                         /* rewind */
                         writepos = 0;
                 }
         }
         return sent;
 }
References audsrv_available(), AUDSRV_ERR_NOT_INITIALIZED, initialized, memcpy(), MIN, playing, readpos, ringbuf, ringbuf_size, update_volume(), and writepos.
Referenced by rpc_command().
audsrv_play_cd()
int audsrv_play_cd (int track)
Plays CD audio track
Parameters
track segment to play [1 .. 99]
Returns
error status
Definition at line 501 of file cdrom.c.
 {
         int type;
         int ret;
         int start, end;
         printf("request to play track %d\n", track);
         if (initialize_cdda() < 0)
         {
                 printf("audsrv: initialized cdda failed\n");
                 return AUDSRV_ERR_NOT_INITIALIZED; //FIXME
         }
         if (track < 1 || track > toc.num_tracks)
         {
                 /* invalid track selected */
                 return AUDSRV_ERR_ARGS;
         }
         type = sceCdGetDiskType();
         if (track == 1 && (type == 11 || type == 0x13))
         {
                 /* first track is data */
                 printf("audsrv: request to play data track\n");
                 return AUDSRV_ERR_ARGS;
         }
         start = audsrv_get_track_offset(track - 1);
         end = audsrv_get_track_offset(track);
         if (start < 0 || end < 0 || end < start)
         {
                 printf("audsrv: invalid track offsets %d, %d\n", start, end);
                 return AUDSRV_ERR_ARGS; //FIXME:
         }
         ret = audsrv_cd_play_sectors(start, end);
         /* core0 input (known as Evilo's patch #1) */
         sceSdSetParam(SD_CORE_0 | SD_PARAM_BVOLL, 0x7fff);
         sceSdSetParam(SD_CORE_0 | SD_PARAM_BVOLR, 0x7fff);
         /* set master volume for core 0 */
         sceSdSetParam(SD_CORE_0 | SD_PARAM_MVOLL, MAX_VOLUME);
         sceSdSetParam(SD_CORE_0 | SD_PARAM_MVOLR, MAX_VOLUME);
         return ret;
 }
References audsrv_cd_play_sectors(), AUDSRV_ERR_ARGS, AUDSRV_ERR_NOT_INITIALIZED, audsrv_get_track_offset(), initialize_cdda(), MAX_VOLUME, cdda_toc::num_tracks, printf(), sceCdGetDiskType(), sceSdSetParam(), SD_CORE_0, SD_PARAM_BVOLL, SD_PARAM_BVOLR, SD_PARAM_MVOLL, SD_PARAM_MVOLR, and toc.
Referenced by rpc_command().
audsrv_quit()
int audsrv_quit ()
Shutdowns audsrv
Returns
AUDSRV_ERR_NOERROR
Definition at line 488 of file audsrv.c.
 {
         /* silence! */
         audsrv_stop_audio();
         audsrv_stop_cd();
         audsrv_adpcm_init();
         /* stop transmission */
         sceSdSetTransCallback(AUDSRV_BLOCK_DMA_CH, NULL);
         sceSdBlockTrans(AUDSRV_BLOCK_DMA_CH, SD_TRANS_STOP, 0, 0, 0);
         /* stop playing thread */
         if (play_tid > 0)
         {
                 TerminateThread(play_tid);
                 DeleteThread(play_tid);
                 play_tid = 0;
         }
 #ifndef NO_RPC_THREAD
         /* Deinitialize RPC client, only once the playback thread is stopped. */
         deinitialize_rpc_client();
 #endif
         if (transfer_sema > 0)
         {
                 DeleteSema(transfer_sema);
                 transfer_sema = 0;
         }
         if (queue_sema > 0)
         {
                 DeleteSema(queue_sema);
                 queue_sema = 0;
         }
         return 0;
 }
References audsrv_adpcm_init(), AUDSRV_BLOCK_DMA_CH, audsrv_stop_audio(), audsrv_stop_cd(), deinitialize_rpc_client(), DeleteSema(), DeleteThread(), NULL, play_tid, queue_sema, sceSdBlockTrans(), sceSdSetTransCallback(), SD_TRANS_STOP, TerminateThread(), and transfer_sema.
Referenced by rpc_command().
audsrv_set_format()
int audsrv_set_format (int freq, int bits, int channels)
Configures audio stream
Parameters
freq frequency in hz
bits bits per sample (8, 16)
channels number of channels
Returns
0 on success, negative if configuration is not supported
This sets up audsrv to accept stream in this format and convert it to SPU2's native format if required. Note: it is possible to change the format at any point. You might want to stop audio prior to that, to prevent mismatched audio output.
Definition at line 174 of file audsrv.c.
 {
         int feed_size;
         if (audsrv_format_ok(freq, bits, channels) == 0)
         {
                 return -AUDSRV_ERR_FORMAT_NOT_SUPPORTED;
         }
         /* update shift-right count */
         core1_sample_shift = 0;
         if (bits == 16)
         {
                 core1_sample_shift++;
         }
         if (channels == 2)
         {
                 core1_sample_shift++;
         }
         core1_freq = freq;
         core1_bits = bits;
         core1_channels = channels;
         /* set ring buffer size to 10 iterations worth of data (~50 ms) */
         feed_size = ((512 * core1_freq) / 48000) << core1_sample_shift;
         ringbuf_size = feed_size * 10;
         writepos = 0;
         readpos = (feed_size * 5) & ~3;
         printf("audsrv: freq %d bits %d channels %d ringbuf_sz %d feed_size %d shift %d\n", freq, bits, channels, ringbuf_size, feed_size, core1_sample_shift);
         format_changed = 1;
         return AUDSRV_ERR_NOERROR;
 }
References AUDSRV_ERR_FORMAT_NOT_SUPPORTED, AUDSRV_ERR_NOERROR, audsrv_format_ok(), core1_bits, core1_channels, core1_freq, core1_sample_shift, format_changed, printf(), readpos, ringbuf_size, and writepos.
Referenced by audsrv_init(), and rpc_command().
audsrv_set_threshold()
int audsrv_set_threshold (int amount)
Definition at line 385 of file audsrv.c.
 {
         if (amount > (ringbuf_size / 2))
         {
                 /* amount is greater than what we'd recommend */
                 return AUDSRV_ERR_ARGS;
         }
         printf("audsrv: callback threshold: %d\n", amount);
         fillbuf_threshold = amount;
         return 0;
 }
References AUDSRV_ERR_ARGS, fillbuf_threshold, printf(), and ringbuf_size.
Referenced by rpc_command().
audsrv_set_volume()
int audsrv_set_volume (int vol)
Sets output volume
Parameters
vol volume in SPU2 units [0 .. 0x3fff]
Returns
0 on success, negative otherwise
Definition at line 372 of file audsrv.c.
 {
         if (vol < 0 || vol > MAX_VOLUME)
         {
                 /* bad joke */
                 return AUDSRV_ERR_ARGS;
         }
         core1_volume = vol;
         update_volume();
         return AUDSRV_ERR_NOERROR;
 }
References AUDSRV_ERR_ARGS, AUDSRV_ERR_NOERROR, core1_volume, MAX_VOLUME, and update_volume().
Referenced by rpc_command().
audsrv_stop_audio()
int audsrv_stop_audio ()
Stops all audio playing
Returns
0, always
Mutes output and stops accepting audio blocks; also, clears callbacks.
Definition at line 135 of file audsrv.c.
 {
         /* audio is still playing, just mute */
         playing = 0;
         update_volume();
         fillbuf_threshold = 0;
         return AUDSRV_ERR_NOERROR;
 }
References AUDSRV_ERR_NOERROR, fillbuf_threshold, playing, and update_volume().
Referenced by audsrv_init(), audsrv_quit(), and rpc_command().
audsrv_stop_cd()
int audsrv_stop_cd ()
Stops CD play
Returns
0, always
Stops CD from being played; this has no effect on other music audsrv is currently playing
Definition at line 557 of file cdrom.c.
 {
         audsrv_stop_cd_stream();
         /* stop playing thread */
         if (cdda_play_tid >= 0)
         {
                 TerminateThread(cdda_play_tid);
                 DeleteThread(cdda_play_tid);
                 cdda_play_tid = -1;
         }
         return 0;
 }
References audsrv_stop_cd_stream(), cdda_play_tid, DeleteThread(), and TerminateThread().
Referenced by audsrv_cd_play_sectors(), audsrv_quit(), cdda_procedure(), and rpc_command().
audsrv_wait_audio()
int audsrv_wait_audio (int buflen)
Blocks until there is enough space to enqueue chunk
Parameters
buflen size of chunk requested to be enqueued (in bytes)
Returns
error status code
Blocks until there are enough space to store the upcoming chunk in audsrv's internal ring buffer.
Definition at line 293 of file audsrv.c.
 {
         if (ringbuf_size < buflen)
         {
                 /* this will never happen */
                 return AUDSRV_ERR_ARGS;
         }
         while (1)
         {
                 if (audsrv_available() >= buflen)
                 {
                         /* enough space! */
                         return AUDSRV_ERR_NOERROR;
                 }
                 WaitSema(queue_sema);
         }
 }
References audsrv_available(), AUDSRV_ERR_ARGS, AUDSRV_ERR_NOERROR, queue_sema, ringbuf_size, and WaitSema().
Referenced by rpc_command().