ps2sdk: iop/sound/audsrv/src/audsrv.c File Reference
audsrv.c File Reference
#include <stdio.h>
#include <thbase.h>
#include <thsemap.h>
#include <loadcore.h>
#include <sysmem.h>
#include <intrman.h>
#include <sifcmd.h>
#include <libsd.h>
#include <sysclib.h>
#include <audsrv.h>
#include "audsrv_internal.h"
#include "common.h"
#include "rpc_server.h"
#include "rpc_client.h"
#include "upsamplers.h"
#include "hw.h"
#include "spu.h"
Macros
#define VERSION "0.92"
Functions
IRX_ID ("audsrv", 1, 3)
static void play_thread (void *arg)
static int transfer_complete (void *arg)
static void update_volume ()
int audsrv_stop_audio ()
int audsrv_format_ok (int freq, int bits, int channels)
int audsrv_set_format (int freq, int bits, int channels)
int audsrv_init ()
int audsrv_available ()
int audsrv_wait_audio (int buflen)
int audsrv_play_audio (const char *buf, int buflen)
int audsrv_set_volume (int vol)
int audsrv_set_threshold (int amount)
int audsrv_quit ()
void unittest_start ()
int _start (int argc, char *argv[])
Variables
static int core1_volume = MAX_VOLUME
static int core1_freq = 0
static int core1_bits = 0
static int core1_channels = 0
static int core1_sample_shift = 0
static int initialized = 0
static int playing = 0
static char ringbuf [20480]
static int ringbuf_size = sizeof(ringbuf)
static int readpos
static int writepos
static int play_tid = 0
static int queue_sema = 0
static int transfer_sema = 0
static int fillbuf_threshold = 0
static int format_changed = 0
static u8 core1_buf [0x1000]
static short rendered_left [512]
static short rendered_right [512]
struct irx_export_table _exp_audsrv
Detailed Description
audsrv IOP server
Definition in file audsrv.c.
Macro Definition Documentation
VERSION
#define VERSION "0.92"
Definition at line 34 of file audsrv.c.
Function Documentation
_start()
int _start (int argc, char * argv[])
IRX _start function
Returns
zero on success
Initializes interrupts and the RPC thread. Oh, and greets the user.
Definition at line 538 of file audsrv.c.
 {
         int err;
         printf("audsrv: greetings from version " VERSION " !\n");
         err = RegisterLibraryEntries(&_exp_audsrv);
         if (err != 0)
         {
                 printf("audsrv: couldn't register library entries. Error %d\n", err);
                 return MODULE_NO_RESIDENT_END;
         }
         audsrv_adpcm_init();
 #ifndef NO_RPC_THREAD
         /* create RPC listener thread */
         initialize_rpc_thread();
 #endif
         /* call unittest, if available */
         unittest_start();
         return MODULE_RESIDENT_END;
 }
References _exp_audsrv, audsrv_adpcm_init(), initialize_rpc_thread(), MODULE_NO_RESIDENT_END, MODULE_RESIDENT_END, printf(), RegisterLibraryEntries(), unittest_start(), and VERSION.
audsrv_available()
int audsrv_available ()
Returns the number of bytes that can be queued
Returns
sample count
Returns the number of bytes that are available in the ring buffer. This is the total bytes that can be queued, without collision of the reading head with the writing head.
Definition at line 274 of file audsrv.c.
 {
         if (writepos <= readpos)
         {
                 return readpos - writepos;
         }
         else
         {
                 return (ringbuf_size - (writepos - readpos));
         }
 }
References readpos, ringbuf_size, and writepos.
Referenced by audsrv_play_audio(), audsrv_wait_audio(), and play_thread().
audsrv_format_ok()
int audsrv_format_ok (int freq, int bits, int channels)
Checks if the format noted by frequency and depth is supported
Parameters
freq frequency in hz
bits bits per sample (8, 16)
channels channels
Returns
positive on success, zero value on failure
Definition at line 152 of file audsrv.c.
 {
         if (find_upsampler(freq, bits, channels) != NULL)
         {
                 return 1;
         }
         /* unsupported format */
         return 0;
 }
References find_upsampler(), and NULL.
Referenced by audsrv_set_format(), and rpc_command().
audsrv_init()
int audsrv_init ()
Initializes audsrv library
Returns
0 on success
Definition at line 215 of file audsrv.c.
 {
         if (initialized)
         {
                 return 0;
         }
         /* initialize libsd */
         if (sceSdInit(SD_INIT_COLD) < 0)
         {
                 printf("audsrv: failed to initialize libsd\n");
                 return -1;
         }
         readpos = 0;
         writepos = 0;
         /* initialize transfer_complete's semaphore */
         transfer_sema = CreateMutex(0);
         if (transfer_sema < 0)
         {
                 return AUDSRV_ERR_OUT_OF_MEMORY;
         }
         queue_sema = CreateMutex(0);
         if (queue_sema < 0)
         {
                 DeleteSema(transfer_sema);
                 return AUDSRV_ERR_OUT_OF_MEMORY;
         }
         /* audio is always playing in the background. trick is to
          * set the data input volume to zero
          */
         audsrv_stop_audio();
         /* initialize transfer-complete callback */
         sceSdSetTransCallback(AUDSRV_BLOCK_DMA_CH, (void *)transfer_complete);
         sceSdBlockTrans(AUDSRV_BLOCK_DMA_CH, SD_TRANS_LOOP, core1_buf, sizeof(core1_buf), 0);
         /* default to SPU's native */
         audsrv_set_format(48000, 16, 2);
         play_tid = create_thread(play_thread, 39, 0);
         printf("audsrv: playing thread 0x%x started\n", play_tid);
         printf("audsrv: kickstarted\n");
         initialized = 1;
         return AUDSRV_ERR_NOERROR;
 }
References AUDSRV_BLOCK_DMA_CH, AUDSRV_ERR_NOERROR, AUDSRV_ERR_OUT_OF_MEMORY, audsrv_set_format(), audsrv_stop_audio(), core1_buf, create_thread(), CreateMutex(), DeleteSema(), initialized, play_thread(), play_tid, printf(), queue_sema, readpos, sceSdBlockTrans(), sceSdInit(), sceSdSetTransCallback(), SD_INIT_COLD, SD_TRANS_LOOP, transfer_complete(), transfer_sema, and writepos.
Referenced by rpc_command().
audsrv_play_audio()
int audsrv_play_audio (const char * buf, int buflen)
Uploads audio buffer to SPU
Parameters
buf audio chunk
buflen size of chunk in bytes
Returns
positive number of bytes sent to processor or negative error status
Plays an audio buffer; It will not interrupt a playing buffer, rather queue it up and play it as soon as possible without interfering with fluent streaming. The buffer and buflen are given in host format (i.e, 11025hz 8bit stereo.)
Definition at line 323 of file audsrv.c.
 {
         int sent = 0;
         if (initialized == 0)
         {
                 return -AUDSRV_ERR_NOT_INITIALIZED;
         }
         if (playing == 0)
         {
                 /* audio is always playing, just change the volume */
                 playing = 1;
                 update_volume();
         }
         //printf("play audio %d bytes, readpos %d, writepos %d avail %d\n", buflen, readpos, writepos, audsrv_available());
         /* limit to what's available, no crossing possible */
         buflen = MIN(buflen, audsrv_available());
         while (buflen > 0)
         {
                 int copy = buflen;
                 if (writepos >= readpos)
                 {
                         copy = MIN(ringbuf_size - writepos, buflen);
                 }
                 memcpy(ringbuf + writepos, buf, copy);
                 buf = buf + copy;
                 buflen = buflen - copy;
                 sent = sent + copy;
                 writepos = writepos + copy;
                 if (writepos >= ringbuf_size)
                 {
                         /* rewind */
                         writepos = 0;
                 }
         }
         return sent;
 }
References audsrv_available(), AUDSRV_ERR_NOT_INITIALIZED, initialized, memcpy(), MIN, playing, readpos, ringbuf, ringbuf_size, update_volume(), and writepos.
Referenced by rpc_command().
audsrv_quit()
int audsrv_quit ()
Shutdowns audsrv
Returns
AUDSRV_ERR_NOERROR
Definition at line 488 of file audsrv.c.
 {
         /* silence! */
         audsrv_stop_audio();
         audsrv_stop_cd();
         audsrv_adpcm_init();
         /* stop transmission */
         sceSdSetTransCallback(AUDSRV_BLOCK_DMA_CH, NULL);
         sceSdBlockTrans(AUDSRV_BLOCK_DMA_CH, SD_TRANS_STOP, 0, 0, 0);
         /* stop playing thread */
         if (play_tid > 0)
         {
                 TerminateThread(play_tid);
                 DeleteThread(play_tid);
                 play_tid = 0;
         }
 #ifndef NO_RPC_THREAD
         /* Deinitialize RPC client, only once the playback thread is stopped. */
         deinitialize_rpc_client();
 #endif
         if (transfer_sema > 0)
         {
                 DeleteSema(transfer_sema);
                 transfer_sema = 0;
         }
         if (queue_sema > 0)
         {
                 DeleteSema(queue_sema);
                 queue_sema = 0;
         }
         return 0;
 }
References audsrv_adpcm_init(), AUDSRV_BLOCK_DMA_CH, audsrv_stop_audio(), audsrv_stop_cd(), deinitialize_rpc_client(), DeleteSema(), DeleteThread(), NULL, play_tid, queue_sema, sceSdBlockTrans(), sceSdSetTransCallback(), SD_TRANS_STOP, TerminateThread(), and transfer_sema.
Referenced by rpc_command().
audsrv_set_format()
int audsrv_set_format (int freq, int bits, int channels)
Configures audio stream
Parameters
freq frequency in hz
bits bits per sample (8, 16)
channels number of channels
Returns
0 on success, negative if configuration is not supported
This sets up audsrv to accept stream in this format and convert it to SPU2's native format if required. Note: it is possible to change the format at any point. You might want to stop audio prior to that, to prevent mismatched audio output.
Definition at line 174 of file audsrv.c.
 {
         int feed_size;
         if (audsrv_format_ok(freq, bits, channels) == 0)
         {
                 return -AUDSRV_ERR_FORMAT_NOT_SUPPORTED;
         }
         /* update shift-right count */
         core1_sample_shift = 0;
         if (bits == 16)
         {
                 core1_sample_shift++;
         }
         if (channels == 2)
         {
                 core1_sample_shift++;
         }
         core1_freq = freq;
         core1_bits = bits;
         core1_channels = channels;
         /* set ring buffer size to 10 iterations worth of data (~50 ms) */
         feed_size = ((512 * core1_freq) / 48000) << core1_sample_shift;
         ringbuf_size = feed_size * 10;
         writepos = 0;
         readpos = (feed_size * 5) & ~3;
         printf("audsrv: freq %d bits %d channels %d ringbuf_sz %d feed_size %d shift %d\n", freq, bits, channels, ringbuf_size, feed_size, core1_sample_shift);
         format_changed = 1;
         return AUDSRV_ERR_NOERROR;
 }
References AUDSRV_ERR_FORMAT_NOT_SUPPORTED, AUDSRV_ERR_NOERROR, audsrv_format_ok(), core1_bits, core1_channels, core1_freq, core1_sample_shift, format_changed, printf(), readpos, ringbuf_size, and writepos.
Referenced by audsrv_init(), and rpc_command().
audsrv_set_threshold()
int audsrv_set_threshold (int amount)
Definition at line 385 of file audsrv.c.
 {
         if (amount > (ringbuf_size / 2))
         {
                 /* amount is greater than what we'd recommend */
                 return AUDSRV_ERR_ARGS;
         }
         printf("audsrv: callback threshold: %d\n", amount);
         fillbuf_threshold = amount;
         return 0;
 }
References AUDSRV_ERR_ARGS, fillbuf_threshold, printf(), and ringbuf_size.
Referenced by rpc_command().
audsrv_set_volume()
int audsrv_set_volume (int vol)
Sets output volume
Parameters
vol volume in SPU2 units [0 .. 0x3fff]
Returns
0 on success, negative otherwise
Definition at line 372 of file audsrv.c.
 {
         if (vol < 0 || vol > MAX_VOLUME)
         {
                 /* bad joke */
                 return AUDSRV_ERR_ARGS;
         }
         core1_volume = vol;
         update_volume();
         return AUDSRV_ERR_NOERROR;
 }
References AUDSRV_ERR_ARGS, AUDSRV_ERR_NOERROR, core1_volume, MAX_VOLUME, and update_volume().
Referenced by rpc_command().
audsrv_stop_audio()
int audsrv_stop_audio ()
Stops all audio playing
Returns
0, always
Mutes output and stops accepting audio blocks; also, clears callbacks.
Definition at line 135 of file audsrv.c.
 {
         /* audio is still playing, just mute */
         playing = 0;
         update_volume();
         fillbuf_threshold = 0;
         return AUDSRV_ERR_NOERROR;
 }
References AUDSRV_ERR_NOERROR, fillbuf_threshold, playing, and update_volume().
Referenced by audsrv_init(), audsrv_quit(), and rpc_command().
audsrv_wait_audio()
int audsrv_wait_audio (int buflen)
Blocks until there is enough space to enqueue chunk
Parameters
buflen size of chunk requested to be enqueued (in bytes)
Returns
error status code
Blocks until there are enough space to store the upcoming chunk in audsrv's internal ring buffer.
Definition at line 293 of file audsrv.c.
 {
         if (ringbuf_size < buflen)
         {
                 /* this will never happen */
                 return AUDSRV_ERR_ARGS;
         }
         while (1)
         {
                 if (audsrv_available() >= buflen)
                 {
                         /* enough space! */
                         return AUDSRV_ERR_NOERROR;
                 }
                 WaitSema(queue_sema);
         }
 }
References audsrv_available(), AUDSRV_ERR_ARGS, AUDSRV_ERR_NOERROR, queue_sema, ringbuf_size, and WaitSema().
Referenced by rpc_command().
IRX_ID()
IRX_ID ("audsrv" , 1 , 3)
play_thread()
static void play_thread (void * arg) static
Main playing thread
Parameters
arg not used
This is the main playing thread. It feeds the SPU with upsampled, demux'd audio data, from what has been queued beforehand. The stream is constructed as a ring buffer. This thread only ends with TerminateThread, and is usually asleep, waiting for SPU to complete playing the current wave. SPU plays 2048 bytes blocks, which yields that this thread wakes and sleeps 93.75 times a second
Definition at line 408 of file audsrv.c.
 {
         int block;
         u8 *bufptr;
         int intr_state;
         int step;
         int available;
         struct upsample_t up;
         upsampler_t upsampler = NULL;
         printf("starting play thread\n");
         while (1)
         {
                 if (format_changed)
                 {
                         upsampler = find_upsampler(core1_freq, core1_bits, core1_channels);
                         format_changed = 0;
                 }
                 if (playing && upsampler != NULL)
                 {
                         up.src = (const unsigned char *)ringbuf + readpos;
                         up.left = rendered_left;
                         up.right = rendered_right;
                         step = upsampler(&up);
                         readpos = readpos + step;
                         if (readpos >= ringbuf_size)
{
                                 /* wrap around */
                                 readpos = 0;
                         }
                 }
                 else
                 {
                         /* not playing */
                         memset(rendered_left, '\0', sizeof(rendered_left));
                         memset(rendered_right, '\0', sizeof(rendered_right));
                 }
                 /* wait until it's safe to transmit another block */
                 WaitSema(transfer_sema);
                 /* suspend all interrupts */
                 CpuSuspendIntr(&intr_state);
                 /* one block is playing currently, other is idle */
                 block = 1 - (sceSdBlockTransStatus(AUDSRV_BLOCK_DMA_CH, 0) >> 24);
                 /* copy 1024 bytes from left and right buffers, into core1_buf */
                 bufptr = core1_buf + (block << 11);
                 wmemcpy(bufptr +    0, rendered_left + 0, 512);
                 wmemcpy(bufptr +  512, rendered_right + 0, 512);
                 wmemcpy(bufptr + 1024, rendered_left + 256, 512);
                 wmemcpy(bufptr + 1536, rendered_right + 256, 512);
                 CpuResumeIntr(intr_state);
                 available = audsrv_available();
                 if (available >= (ringbuf_size / 10))
                 {
                         /* arbitrarily selected ringbuf_size / 10, to reduce
                          * number of semaphores signalled.
                          */
                         SignalSema(queue_sema);
                 }
                 if (fillbuf_threshold > 0 && available >= fillbuf_threshold)
                 {
                         /* EE client requested a callback */
                         call_client_callback(AUDSRV_FILLBUF_CALLBACK);
                 }
                 //printf("avaiable: %d, queued: %d\n", available, ringbuf_size - available);
         }
 }
References audsrv_available(), AUDSRV_BLOCK_DMA_CH, AUDSRV_FILLBUF_CALLBACK, call_client_callback(), core1_bits, core1_buf, core1_channels, core1_freq, CpuResumeIntr(), CpuSuspendIntr(), fillbuf_threshold, find_upsampler(), format_changed, intr_state, upsample_t::left, memset(), NULL, playing, printf(), queue_sema, readpos, rendered_left, rendered_right, upsample_t::right, ringbuf, ringbuf_size, sceSdBlockTransStatus(), SignalSema(), upsample_t::src, transfer_sema, WaitSema(), and wmemcpy().
Referenced by AHX_Init(), and audsrv_init().
transfer_complete()
static int transfer_complete (void * arg) static
Transfer complete callback.
Parameters
arg not used
Returns
true, always
Definition at line 97 of file audsrv.c.
 {
         iSignalSema(transfer_sema);
         return 1;
 }
References iSignalSema(), and transfer_sema.
Referenced by audsrv_init().
unittest_start()
void unittest_start ()
Definition at line 528 of file audsrv.c.
 {
         /* override this from a unittest */
 }
Referenced by _start().
update_volume()
static void update_volume () static
Apply volume changes, or keep mute if not playing
Definition at line 104 of file audsrv.c.
 {
         int vol;
         /* external input */
         sceSdSetParam(SD_CORE_1 | SD_PARAM_AVOLL, 0x7fff);
         sceSdSetParam(SD_CORE_1 | SD_PARAM_AVOLR, 0x7fff);
         /* core0 input */
         sceSdSetParam(SD_CORE_0 | SD_PARAM_BVOLL, 0);
         sceSdSetParam(SD_CORE_0 | SD_PARAM_BVOLR, 0);
         /* core1 input */
         vol = playing ? core1_volume : 0;
         sceSdSetParam(SD_CORE_1 | SD_PARAM_BVOLL, vol);
         sceSdSetParam(SD_CORE_1 | SD_PARAM_BVOLR, vol);
         /* set master volume for core 0 */
         sceSdSetParam(SD_CORE_0 | SD_PARAM_MVOLL, 0);
         sceSdSetParam(SD_CORE_0 | SD_PARAM_MVOLR, 0);
         /* set master volume for core 1 */
         sceSdSetParam(SD_CORE_1 | SD_PARAM_MVOLL, MAX_VOLUME);
         sceSdSetParam(SD_CORE_1 | SD_PARAM_MVOLR, MAX_VOLUME);
 }
References core1_volume, MAX_VOLUME, playing, sceSdSetParam(), SD_CORE_0, SD_CORE_1, SD_PARAM_AVOLL, SD_PARAM_AVOLR, SD_PARAM_BVOLL, SD_PARAM_BVOLR, SD_PARAM_MVOLL, and SD_PARAM_MVOLR.
Referenced by audsrv_play_audio(), audsrv_set_volume(), and audsrv_stop_audio().
Variable Documentation
_exp_audsrv
struct irx_export_table _exp_audsrv extern
exports table
Referenced by _start().
core1_bits
int core1_bits = 0 static
bits per sample, set by user
Definition at line 43 of file audsrv.c.
Referenced by audsrv_set_format(), and play_thread().
core1_buf
u8 core1_buf[0x1000] static
double buffer for streaming
Definition at line 79 of file audsrv.c.
Referenced by audsrv_init(), and play_thread().
core1_channels
int core1_channels = 0 static
number of audio channels
Definition at line 45 of file audsrv.c.
Referenced by audsrv_set_format(), and play_thread().
core1_freq
int core1_freq = 0 static
frequency set by user
Definition at line 41 of file audsrv.c.
Referenced by audsrv_set_format(), and play_thread().
core1_sample_shift
int core1_sample_shift = 0 static
shift count from bytes to samples
Definition at line 47 of file audsrv.c.
Referenced by audsrv_set_format().
core1_volume
int core1_volume = MAX_VOLUME static
core1 (sfx) volume
Definition at line 39 of file audsrv.c.
Referenced by audsrv_set_volume(), and update_volume().
fillbuf_threshold
int fillbuf_threshold = 0 static
threshold to initiate a callback
Definition at line 73 of file audsrv.c.
Referenced by audsrv_set_threshold(), audsrv_stop_audio(), and play_thread().
format_changed
int format_changed = 0 static
boolean to notify when format has changed
Definition at line 76 of file audsrv.c.
Referenced by audsrv_set_format(), and play_thread().
initialized
int initialized = 0 static
initialization status
Definition at line 51 of file audsrv.c.
Referenced by audsrv_init(), and audsrv_play_audio().
play_tid
int play_tid = 0 static
playing thread id
Definition at line 67 of file audsrv.c.
Referenced by audsrv_init(), and audsrv_quit().
playing
int playing = 0 static
playing (not mute) status
Definition at line 53 of file audsrv.c.
Referenced by audsrv_play_audio(), audsrv_stop_audio(), play_thread(), and update_volume().
queue_sema
int queue_sema = 0 static
semaphore for wait_audio()
Definition at line 69 of file audsrv.c.
Referenced by audsrv_init(), audsrv_quit(), audsrv_wait_audio(), and play_thread().
readpos
int readpos static
reading head pointer
Definition at line 62 of file audsrv.c.
Referenced by audsrv_available(), audsrv_init(), audsrv_play_audio(), audsrv_set_format(), and play_thread().
rendered_left
short rendered_left[512] static
Definition at line 81 of file audsrv.c.
Referenced by play_thread().
rendered_right
short rendered_right[512] static
Definition at line 82 of file audsrv.c.
Referenced by play_thread().
ringbuf
char ringbuf[20480] static
ring buffer itself
Definition at line 58 of file audsrv.c.
Referenced by audsrv_play_audio(), and play_thread().
ringbuf_size
int ringbuf_size = sizeof(ringbuf) static
size of ring buffer in bytes
Definition at line 60 of file audsrv.c.
Referenced by audsrv_available(), audsrv_play_audio(), audsrv_set_format(), audsrv_set_threshold(), audsrv_wait_audio(), and play_thread().
transfer_sema
int transfer_sema = 0 static
SPU2 transfer complete semaphore
Definition at line 71 of file audsrv.c.
Referenced by audsrv_init(), audsrv_quit(), play_thread(), and transfer_complete().
writepos
int writepos static
writing head pointer
Definition at line 64 of file audsrv.c.
Referenced by audsrv_available(), audsrv_init(), audsrv_play_audio(), and audsrv_set_format().