ps2sdk: iop/fs/bdm/include/bdm.h File Reference
bdm.h File Reference
#include <irx.h>
#include <types.h>
Data Structures
struct block_device
struct file_system
Macros
#define bdm_IMPORTS_start DECLARE_IMPORT_TABLE(bdm, 1, 0)
#define bdm_IMPORTS_end END_IMPORT_TABLE
#define I_bdm_connect_bd DECLARE_IMPORT(4, bdm_connect_bd)
#define I_bdm_disconnect_bd DECLARE_IMPORT(5, bdm_disconnect_bd)
#define I_bdm_connect_fs DECLARE_IMPORT(6, bdm_connect_fs)
#define I_bdm_disconnect_fs DECLARE_IMPORT(7, bdm_disconnect_fs)
#define I_bdm_get_bd DECLARE_IMPORT(8, bdm_get_bd)
#define I_bdm_RegisterCallback DECLARE_IMPORT(9, bdm_RegisterCallback)
Typedefs
typedef void(* bdm_cb) (int event)
Functions
void bdm_connect_bd (struct block_device *bd)
void bdm_disconnect_bd (struct block_device *bd)
void bdm_connect_fs (struct file_system *fs)
void bdm_disconnect_fs (struct file_system *fs)
void bdm_get_bd (struct block_device **pbd, unsigned int count)
void bdm_RegisterCallback (bdm_cb cb)
Detailed Description
IOP BDM (Block Device Manager) definitions.
Definition in file bdm.h.
Macro Definition Documentation
bdm_IMPORTS_end
#define bdm_IMPORTS_end END_IMPORT_TABLE
Definition at line 65 of file bdm.h.
bdm_IMPORTS_start
#define bdm_IMPORTS_start DECLARE_IMPORT_TABLE(bdm, 1, 0)
Definition at line 64 of file bdm.h.
I_bdm_connect_bd
#define I_bdm_connect_bd DECLARE_IMPORT(4, bdm_connect_bd)
Definition at line 67 of file bdm.h.
I_bdm_connect_fs
#define I_bdm_connect_fs DECLARE_IMPORT(6, bdm_connect_fs)
Definition at line 69 of file bdm.h.
I_bdm_disconnect_bd
#define I_bdm_disconnect_bd DECLARE_IMPORT(5, bdm_disconnect_bd)
Definition at line 68 of file bdm.h.
I_bdm_disconnect_fs
#define I_bdm_disconnect_fs DECLARE_IMPORT(7, bdm_disconnect_fs)
Definition at line 70 of file bdm.h.
I_bdm_get_bd
#define I_bdm_get_bd DECLARE_IMPORT(8, bdm_get_bd)
Definition at line 71 of file bdm.h.
I_bdm_RegisterCallback
#define I_bdm_RegisterCallback DECLARE_IMPORT(9, bdm_RegisterCallback)
Definition at line 72 of file bdm.h.
Typedef Documentation
bdm_cb
typedef void(* bdm_cb) (int event)
Definition at line 54 of file bdm.h.
Function Documentation
bdm_connect_bd()
void bdm_connect_bd (struct block_device * bd)
Definition at line 46 of file bdm.c.
 {
     int i;
     M_PRINTF("connecting device %s%dp%d\n", bd->name, bd->devNr, bd->parNr);
     for (i = 0; i < MAX_CONNECTIONS; ++i) {
         if (g_mount[i].bd == NULL) {
             g_mount[i].bd = bd;
             // New block device, try to mount it to a filesystem
             SetEventFlag(bdm_event, BDM_EVENT_MOUNT);
             break;
         }
     }
 }
References bdm_mounts::bd, bdm_event, BDM_EVENT_MOUNT, block_device::devNr, g_mount, M_PRINTF, MAX_CONNECTIONS, block_device::name, NULL, block_device::parNr, and SetEventFlag().
Referenced by part_create(), and scsi_connect().
bdm_connect_fs()
void bdm_connect_fs (struct file_system * fs)
Definition at line 80 of file bdm.c.
 {
     int i;
     M_PRINTF("connecting fs %s\n", fs->name);
     for (i = 0; i < MAX_CONNECTIONS; ++i) {
         if (g_fs[i] == NULL) {
             g_fs[i] = fs;
             break;
         }
     }
     // New filesystem, try to mount it to the block devices
     SetEventFlag(bdm_event, BDM_EVENT_MOUNT);
 }
References bdm_event, BDM_EVENT_MOUNT, g_fs, M_PRINTF, MAX_CONNECTIONS, file_system::name, NULL, and SetEventFlag().
Referenced by _start(), and part_init().
bdm_disconnect_bd()
void bdm_disconnect_bd (struct block_device * bd)
Definition at line 62 of file bdm.c.
 {
     int i;
     M_PRINTF("disconnecting device %s%dp%d\n", bd->name, bd->devNr, bd->parNr);
     for (i = 0; i < MAX_CONNECTIONS; ++i) {
         if (g_mount[i].bd == bd) {
             g_mount[i].fs->disconnect_bd(bd);
             M_PRINTF("%s%dp%d unmounted from %s\n", bd->name, bd->devNr, bd->parNr, g_mount[i].fs->name);
             g_mount[i].bd = NULL;
             g_mount[i].fs = NULL;
             if (g_cb != NULL)
                 SetEventFlag(bdm_event, BDM_EVENT_CB_UMOUNT);
         }
     }
 }
References bdm_mounts::bd, bdm_event, BDM_EVENT_CB_UMOUNT, block_device::devNr, file_system::disconnect_bd, bdm_mounts::fs, g_cb, g_mount, M_PRINTF, MAX_CONNECTIONS, block_device::name, file_system::name, NULL, block_device::parNr, and SetEventFlag().
Referenced by part_disconnect(), and scsi_disconnect().
bdm_disconnect_fs()
void bdm_disconnect_fs (struct file_system * fs)
Definition at line 97 of file bdm.c.
 {
     int i;
     M_PRINTF("disconnecting fs %s\n", fs->name);
     // Unmount fs from block devices
     for (i = 0; i < MAX_CONNECTIONS; ++i) {
         if (g_mount[i].fs == fs) {
             g_mount[i].fs = NULL;
             if (g_cb != NULL)
                 SetEventFlag(bdm_event, BDM_EVENT_CB_UMOUNT);
         }
     }
     // Remove fs from list
     for (i = 0; i < MAX_CONNECTIONS; ++i) {
         if (g_fs[i] == fs) {
             g_fs[i] = NULL;
             break;
         }
     }
 }
References bdm_event, BDM_EVENT_CB_UMOUNT, bdm_mounts::fs, g_cb, g_fs, g_mount, M_PRINTF, MAX_CONNECTIONS, file_system::name, NULL, and SetEventFlag().
bdm_get_bd()
void bdm_get_bd (struct block_device ** pbd, unsigned int count)
Definition at line 121 of file bdm.c.
 {
     int i;
     M_DEBUG("%s\n", __func__);
     // Fill pointer array with block device pointers
     for (i = 0; i < count && i < MAX_CONNECTIONS; i++)
         pbd[i] = g_mount[i].bd;
 }
References g_mount, M_DEBUG, and MAX_CONNECTIONS.
bdm_RegisterCallback()
void bdm_RegisterCallback (bdm_cb cb)
Definition at line 26 of file bdm.c.
 {
     int i;
     M_DEBUG("%s\n", __func__);
     g_cb = cb;
     if (g_cb == NULL)
         return;
     // Trigger a mount callback if we already have mounts
     for (i = 0; i < MAX_CONNECTIONS; ++i) {
         if ((g_mount[i].bd != NULL) && (g_mount[i].fs != NULL)) {
             SetEventFlag(bdm_event, BDM_EVENT_CB_MOUNT);
             break;
         }
     }
 }
References bdm_event, BDM_EVENT_CB_MOUNT, g_cb, g_mount, M_DEBUG, MAX_CONNECTIONS, NULL, and SetEventFlag().