ps2sdk: iop/fs/bdm/src/bdm.c File Reference
bdm.c File Reference
#include <bdm.h>
#include <stdio.h>
#include <thbase.h>
#include <thevent.h>
#include "module_debug.h"
Data Structures
struct bdm_mounts
Macros
#define MAX_CONNECTIONS 20
#define BDM_EVENT_CB_MOUNT 0x01
#define BDM_EVENT_CB_UMOUNT 0x02
#define BDM_EVENT_MOUNT 0x04
Functions
void bdm_RegisterCallback (bdm_cb cb)
void bdm_connect_bd (struct block_device *bd)
void bdm_disconnect_bd (struct block_device *bd)
void bdm_connect_fs (struct file_system *fs)
void bdm_disconnect_fs (struct file_system *fs)
void bdm_get_bd (struct block_device **pbd, unsigned int count)
static void bdm_try_mount (struct bdm_mounts *mount)
static void bdm_thread (void *arg)
int bdm_init ()
Variables
static struct bdm_mounts g_mount [MAX_CONNECTIONS]
static struct file_system * g_fs [MAX_CONNECTIONS]
static bdm_cb g_cb = NULL
static int bdm_event = -1
static int bdm_thread_id = -1
Macro Definition Documentation
BDM_EVENT_CB_MOUNT
#define BDM_EVENT_CB_MOUNT 0x01
Definition at line 22 of file bdm.c.
BDM_EVENT_CB_UMOUNT
#define BDM_EVENT_CB_UMOUNT 0x02
Definition at line 23 of file bdm.c.
BDM_EVENT_MOUNT
#define BDM_EVENT_MOUNT 0x04
Definition at line 24 of file bdm.c.
MAX_CONNECTIONS
#define MAX_CONNECTIONS 20
Definition at line 14 of file bdm.c.
Function Documentation
bdm_connect_bd()
void bdm_connect_bd (struct block_device * bd)
Definition at line 46 of file bdm.c.
 {
     int i;
     M_PRINTF("connecting device %s%dp%d\n", bd->name, bd->devNr, bd->parNr);
     for (i = 0; i < MAX_CONNECTIONS; ++i) {
         if (g_mount[i].bd == NULL) {
             g_mount[i].bd = bd;
             // New block device, try to mount it to a filesystem
             SetEventFlag(bdm_event, BDM_EVENT_MOUNT);
             break;
         }
     }
 }
References bdm_mounts::bd, bdm_event, BDM_EVENT_MOUNT, block_device::devNr, g_mount, M_PRINTF, MAX_CONNECTIONS, block_device::name, NULL, block_device::parNr, and SetEventFlag().
Referenced by part_create(), and scsi_connect().
bdm_connect_fs()
void bdm_connect_fs (struct file_system * fs)
Definition at line 80 of file bdm.c.
 {
     int i;
     M_PRINTF("connecting fs %s\n", fs->name);
     for (i = 0; i < MAX_CONNECTIONS; ++i) {
         if (g_fs[i] == NULL) {
             g_fs[i] = fs;
             break;
         }
     }
     // New filesystem, try to mount it to the block devices
     SetEventFlag(bdm_event, BDM_EVENT_MOUNT);
 }
References bdm_event, BDM_EVENT_MOUNT, g_fs, M_PRINTF, MAX_CONNECTIONS, file_system::name, NULL, and SetEventFlag().
Referenced by _start(), and part_init().
bdm_disconnect_bd()
void bdm_disconnect_bd (struct block_device * bd)
Definition at line 62 of file bdm.c.
 {
     int i;
     M_PRINTF("disconnecting device %s%dp%d\n", bd->name, bd->devNr, bd->parNr);
     for (i = 0; i < MAX_CONNECTIONS; ++i) {
         if (g_mount[i].bd == bd) {
             g_mount[i].fs->disconnect_bd(bd);
             M_PRINTF("%s%dp%d unmounted from %s\n", bd->name, bd->devNr, bd->parNr, g_mount[i].fs->name);
             g_mount[i].bd = NULL;
             g_mount[i].fs = NULL;
             if (g_cb != NULL)
                 SetEventFlag(bdm_event, BDM_EVENT_CB_UMOUNT);
         }
     }
 }
References bdm_mounts::bd, bdm_event, BDM_EVENT_CB_UMOUNT, block_device::devNr, file_system::disconnect_bd, bdm_mounts::fs, g_cb, g_mount, M_PRINTF, MAX_CONNECTIONS, block_device::name, file_system::name, NULL, block_device::parNr, and SetEventFlag().
Referenced by part_disconnect(), and scsi_disconnect().
bdm_disconnect_fs()
void bdm_disconnect_fs (struct file_system * fs)
Definition at line 97 of file bdm.c.
 {
     int i;
     M_PRINTF("disconnecting fs %s\n", fs->name);
     // Unmount fs from block devices
     for (i = 0; i < MAX_CONNECTIONS; ++i) {
         if (g_mount[i].fs == fs) {
             g_mount[i].fs = NULL;
             if (g_cb != NULL)
                 SetEventFlag(bdm_event, BDM_EVENT_CB_UMOUNT);
         }
     }
     // Remove fs from list
     for (i = 0; i < MAX_CONNECTIONS; ++i) {
         if (g_fs[i] == fs) {
             g_fs[i] = NULL;
             break;
         }
     }
 }
References bdm_event, BDM_EVENT_CB_UMOUNT, bdm_mounts::fs, g_cb, g_fs, g_mount, M_PRINTF, MAX_CONNECTIONS, file_system::name, NULL, and SetEventFlag().
bdm_get_bd()
void bdm_get_bd (struct block_device ** pbd, unsigned int count)
Definition at line 121 of file bdm.c.
 {
     int i;
     M_DEBUG("%s\n", __func__);
     // Fill pointer array with block device pointers
     for (i = 0; i < count && i < MAX_CONNECTIONS; i++)
         pbd[i] = g_mount[i].bd;
 }
References g_mount, M_DEBUG, and MAX_CONNECTIONS.
bdm_init()
int bdm_init ()
Definition at line 183 of file bdm.c.
 {
     int i, result;
     iop_event_t EventFlagData;
     iop_thread_t ThreadData;
     M_DEBUG("%s\n", __func__);
     for (i = 0; i < MAX_CONNECTIONS; ++i) {
         g_mount[i].bd = NULL;
         g_mount[i].fs = NULL;
         g_fs[i]       = NULL;
     }
     EventFlagData.attr   = 0;
     EventFlagData.option = 0;
     EventFlagData.bits   = 0;
     result = bdm_event = CreateEventFlag(&EventFlagData);
     if (result < 0) {
         M_DEBUG("ERROR: CreateEventFlag %d\n", result);
         return result;
     }
     ThreadData.attr      = TH_C;
     ThreadData.thread    = bdm_thread;
     ThreadData.option    = 0;
     ThreadData.priority  = 0x30;   // Low priority
     ThreadData.stacksize = 0x1000; // 4KiB
     result = bdm_thread_id = CreateThread(&ThreadData);
     if (result < 0) {
         M_DEBUG("ERROR: CreateThread %d\n", result);
         DeleteEventFlag(bdm_event);
         return result;
     }
     result = StartThread(bdm_thread_id, NULL);
     if (result < 0) {
         M_DEBUG("ERROR: StartThread %d\n", result);
         DeleteThread(bdm_thread_id);
         DeleteEventFlag(bdm_event);
         return result;
     }
     return 0;
 }
References iop_thread_t::attr, iop_event_t::attr, bdm_mounts::bd, bdm_event, bdm_thread(), bdm_thread_id, iop_event_t::bits, CreateEventFlag(), CreateThread(), DeleteEventFlag(), DeleteThread(), EventFlagData, bdm_mounts::fs, g_fs, g_mount, M_DEBUG, MAX_CONNECTIONS, NULL, iop_thread_t::option, iop_event_t::option, iop_thread_t::priority, result, iop_thread_t::stacksize, StartThread(), TH_C, and iop_thread_t::thread.
Referenced by _start().
bdm_RegisterCallback()
void bdm_RegisterCallback (bdm_cb cb)
Definition at line 26 of file bdm.c.
 {
     int i;
     M_DEBUG("%s\n", __func__);
     g_cb = cb;
     if (g_cb == NULL)
         return;
     // Trigger a mount callback if we already have mounts
     for (i = 0; i < MAX_CONNECTIONS; ++i) {
         if ((g_mount[i].bd != NULL) && (g_mount[i].fs != NULL)) {
             SetEventFlag(bdm_event, BDM_EVENT_CB_MOUNT);
             break;
         }
     }
 }
References bdm_event, BDM_EVENT_CB_MOUNT, g_cb, g_mount, M_DEBUG, MAX_CONNECTIONS, NULL, and SetEventFlag().
bdm_thread()
static void bdm_thread (void * arg) static
Definition at line 151 of file bdm.c.
 {
     u32 EFBits;
     int i;
     M_PRINTF("BDM event thread running\n");
     while (1) {
         WaitEventFlag(bdm_event, BDM_EVENT_CB_MOUNT | BDM_EVENT_CB_UMOUNT | BDM_EVENT_MOUNT, WEF_OR | WEF_CLEAR, &EFBits);
         if (EFBits & BDM_EVENT_MOUNT) {
             // Try to mount any unmounted block devices
             for (i = 0; i < MAX_CONNECTIONS; ++i) {
                 if ((g_mount[i].bd != NULL) && (g_mount[i].fs == NULL))
                     bdm_try_mount(&g_mount[i]);
             }
         }
         if (EFBits & BDM_EVENT_CB_MOUNT) {
             // Notify callback about changes
             if (g_cb != NULL)
                 g_cb(1);
         }
         if (EFBits & BDM_EVENT_CB_UMOUNT) {
             // Notify callback about changes
             if (g_cb != NULL)
                 g_cb(0);
         }
     }
 }
References bdm_event, BDM_EVENT_CB_MOUNT, BDM_EVENT_CB_UMOUNT, BDM_EVENT_MOUNT, bdm_try_mount(), g_cb, g_mount, M_PRINTF, MAX_CONNECTIONS, NULL, WaitEventFlag(), WEF_CLEAR, and WEF_OR.
Referenced by bdm_init().
bdm_try_mount()
static void bdm_try_mount (struct bdm_mounts * mount) static
Definition at line 132 of file bdm.c.
 {
     int i;
     M_DEBUG("%s(%s%dp%d)\n", __func__, mount->bd->name, mount->bd->devNr, mount->bd->parNr);
     for (i = 0; i < MAX_CONNECTIONS; ++i) {
         if (g_fs[i] != NULL) {
             if (g_fs[i]->connect_bd(mount->bd) == 0) {
                 M_PRINTF("%s%dp%d mounted to %s\n", mount->bd->name, mount->bd->devNr, mount->bd->parNr, g_fs[i]->name);
                 mount->fs = g_fs[i];
                 if (g_cb != NULL)
                     SetEventFlag(bdm_event, BDM_EVENT_CB_MOUNT);
                 break;
             }
         }
     }
 }
References bdm_event, BDM_EVENT_CB_MOUNT, file_system::connect_bd, g_cb, g_fs, M_DEBUG, M_PRINTF, MAX_CONNECTIONS, mount(), file_system::name, NULL, and SetEventFlag().
Referenced by bdm_thread().
Variable Documentation
bdm_event
int bdm_event = -1 static
Definition at line 18 of file bdm.c.
Referenced by bdm_connect_bd(), bdm_connect_fs(), bdm_disconnect_bd(), bdm_disconnect_fs(), bdm_init(), bdm_RegisterCallback(), bdm_thread(), and bdm_try_mount().
bdm_thread_id
int bdm_thread_id = -1 static
Definition at line 19 of file bdm.c.
Referenced by bdm_init().
g_cb
bdm_cb g_cb = NULL static
Definition at line 17 of file bdm.c.
Referenced by bdm_disconnect_bd(), bdm_disconnect_fs(), bdm_RegisterCallback(), bdm_thread(), and bdm_try_mount().
g_fs
struct file_system* g_fs[MAX_CONNECTIONS] static
Definition at line 16 of file bdm.c.
Referenced by bdm_connect_fs(), bdm_disconnect_fs(), bdm_init(), and bdm_try_mount().
g_mount
struct bdm_mounts g_mount[MAX_CONNECTIONS] static
Definition at line 1 of file bdm.c.
Referenced by bdm_connect_bd(), bdm_disconnect_bd(), bdm_disconnect_fs(), bdm_get_bd(), bdm_init(), bdm_RegisterCallback(), and bdm_thread().