ps2sdk: iop/hdd/libpfs/src/bitmap.c File Reference
bitmap.c File Reference
#include <errno.h>
#include <stdio.h>
#include <limits.h>
#include "pfs-opt.h"
#include "libpfs.h"
Functions
void pfsBitmapSetupInfo (pfs_mount_t *pfsMount, pfs_bitmapInfo_t *info, u32 subpart, u32 number)
void pfsBitmapAllocFree (pfs_cache_t *clink, u32 operation, u32 subpart, u32 chunk, u32 index, u32 _bit, u32 count)
int pfsBitmapAllocateAdditionalZones (pfs_mount_t *pfsMount, pfs_blockinfo_t *bi, u32 count)
int pfsBitmapAllocZones (pfs_mount_t *pfsMount, pfs_blockinfo_t *bi, u32 amount)
int pfsBitmapSearchFreeZone (pfs_mount_t *pfsMount, pfs_blockinfo_t *bi, u32 max_count)
void pfsBitmapFreeBlockSegment (pfs_mount_t *pfsMount, pfs_blockinfo_t *bi)
int pfsBitmapCalcFreeZones (pfs_mount_t *pfsMount, int sub)
void pfsBitmapShow (pfs_mount_t *pfsMount)
void pfsBitmapFreeInodeBlocks (pfs_cache_t *clink)
Variables
u32 pfsMetaSize
u32 pfsBlockSize
u32 pfsBitsPerBitmapChunk = 8192
Function Documentation
pfsBitmapAllocateAdditionalZones()
int pfsBitmapAllocateAdditionalZones (pfs_mount_t * pfsMount, pfs_blockinfo_t * bi, u32 count)
Definition at line 87 of file bitmap.c.
 {
         int result;
         pfs_bitmapInfo_t info;
         pfs_cache_t *c;
         int res=0;
         u32 bitmapMax;
         u32 *bitmapWord, *bitmapEnd;
         pfsBitmapSetupInfo(pfsMount, &info, bi->subpart, bi->number+bi->count);
         // Make sure we're not trying to allocate more than is possible
         if ((u32)USHRT_MAX - bi->count < count)
                 count = USHRT_MAX - bi->count;
         // Loop over each bitmap chunk (each is 1024 bytes in size) until either we have allocated
         // the requested amount of blocks, or until we have run out of space on the current partition
         while ((((info.partitionRemainder==0) && (info.chunk < info.partitionChunks  )) ||
                 ((info.partitionRemainder!=0) && (info.chunk < info.partitionChunks+1))) && count)
         {
                 u32 sector=(1<<pfsMount->inode_scale) + info.chunk;
                 // if main partition, add offset (in units of blocks)
                 if (bi->subpart==0)
                         sector += 0x2000 >> pfsBlockSize;
                 // Read the bitmap chunk from the hdd
                 c=pfsCacheGetData(pfsMount, bi->subpart, sector, PFS_CACHE_FLAG_BITMAP, &result);
                 if (c==NULL)break;
                 // Loop over each 32-bit word in the current bitmap chunk until
                 // we find a used zone or we've allocated all the zones we need
                 bitmapMax = info.chunk==info.partitionChunks ? info.partitionRemainder / 8 : pfsMetaSize;
                 bitmapEnd = (u32*)&((u8*)c->u.bitmap)[bitmapMax];
                 for (bitmapWord=&c->u.bitmap[info.index]; (bitmapWord < bitmapEnd) && count;  bitmapWord++, info.bit=0)
                 {
                         // Loop over each of the 32 bits in the current word from the current bitmap chunk,
                         // trying to allocate the requested number of zones
                         for ( ; (info.bit < 32) && count; count--)
{
                                 // We only want to allocate a continuous area, so if we come
                                 // accross a used zone bail
                                 if (*bitmapWord & (1<<info.bit))
{
                                         pfsCacheFree(c);
                                         goto exit;
                                 }
                                 // If the current bit in the bitmap is marked as free, mark it was used
                                 res++;
                                 *bitmapWord |= 1<<info.bit;
                                 info.bit++;
                                 c->flags |= PFS_CACHE_FLAG_DIRTY;
                         }
                 }
                 pfsCacheFree(c);
                 info.index=0;
                 info.chunk++;
         }
 exit:
         // Adjust global free zone counts
         pfsMount->free_zone[bi->subpart]-=res;
         pfsMount->zfree-=res;
         return res;
 }
References pfs_cache_t::bitmap, pfs_blockinfo_t::count, pfs_cache_t::flags, pfs_mount_t::free_zone, pfs_mount_t::inode_scale, NULL, pfs_blockinfo_t::number, PFS_CACHE_FLAG_BITMAP, PFS_CACHE_FLAG_DIRTY, pfsBitmapSetupInfo(), pfsBlockSize, pfsCacheFree(), pfsCacheGetData(), pfsMetaSize, result, pfs_blockinfo_t::subpart, pfs_cache_t::u, USHRT_MAX, and pfs_mount_t::zfree.
Referenced by pfsBlockExpandSegment().
pfsBitmapAllocFree()
void pfsBitmapAllocFree (pfs_cache_t * clink, u32 operation, u32 subpart, u32 chunk, u32 index, u32 _bit, u32 count)
Definition at line 39 of file bitmap.c.
 {
         int result;
         u32 sector, bit;
         u32 *bitmapWord, *bitmapEnd;
         while (clink)
         {
                 bitmapEnd = (u32*)&((u8*)clink->u.bitmap)[pfsMetaSize];
                 for (bitmapWord = &clink->u.bitmap[index]; (bitmapWord < bitmapEnd) && count; bitmapWord++, _bit = 0)
                 {
                         for (bit = _bit; bit < 32 && count; bit++, count--)
{
                                 if(operation == PFS_BITMAP_ALLOC)
{
                                         if (*bitmapWord & (1 << bit))
                                                 PFS_PRINTF(PFS_DRV_NAME": Error: Tried to allocate used block!\n");
                                         *bitmapWord |= (1 << bit);
                                 }
                                 else
{
                                         if ((*bitmapWord & (1 << bit))==0)
                                                 PFS_PRINTF(PFS_DRV_NAME": Error: Tried to free unused block!\n");
                                         *bitmapWord &= ~(1 << bit);
                                 }
                         }
                 }
                 index = 0;
                 clink->flags |= PFS_CACHE_FLAG_DIRTY;
                 pfsCacheFree(clink);
                 if (count==0)
                         break;
                 chunk++;
                 sector = (1 << clink->pfsMount->inode_scale) + chunk;
                 if(subpart==0)
                         sector += 0x2000 >> pfsBlockSize;
                 clink = pfsCacheGetData(clink->pfsMount, subpart, sector, PFS_CACHE_FLAG_BITMAP, &result);
         }
 }
References pfs_cache_t::bitmap, pfs_cache_t::flags, index(), pfs_mount_t::inode_scale, PFS_BITMAP_ALLOC, PFS_CACHE_FLAG_BITMAP, PFS_CACHE_FLAG_DIRTY, PFS_DRV_NAME, PFS_PRINTF, pfsBlockSize, pfsCacheFree(), pfsCacheGetData(), pfsMetaSize, pfs_cache_t::pfsMount, result, and pfs_cache_t::u.
Referenced by pfsBitmapAllocZones(), and pfsBitmapFreeBlockSegment().
pfsBitmapAllocZones()
int pfsBitmapAllocZones (pfs_mount_t * pfsMount, pfs_blockinfo_t * bi, u32 amount)
Definition at line 156 of file bitmap.c.
 {
         pfs_bitmapInfo_t info;
         int result;
         u32 startBit = 0, startPos = 0, startChunk = 0, count = 0;
         u32 sector;
         pfs_cache_t *bitmap;
         u32 *bitmapWord, *bitmapEnd;
         u32 i, bitmapMax;
         pfsBitmapSetupInfo(pfsMount, &info, bi->subpart, bi->number);
         for ( ; ((info.partitionRemainder==0) && (info.chunk < info.partitionChunks))||
                 ((info.partitionRemainder!=0) && (info.chunk < info.partitionChunks+1)); info.chunk++){
                 sector = info.chunk + (1 << pfsMount->inode_scale);
                 if(bi->subpart==0)
                         sector += 0x2000 >> pfsBlockSize;
                 // read in the bitmap chunk
                 bitmap = pfsCacheGetData(pfsMount, bi->subpart, sector, PFS_CACHE_FLAG_BITMAP, &result);
                 if(bitmap==0)
                         return 0;
                 bitmapMax = info.chunk == info.partitionChunks ? info.partitionRemainder / 8 : pfsMetaSize;
                 bitmapEnd = (u32*)&((u8*)bitmap->u.bitmap)[bitmapMax];
                 for (bitmapWord=&bitmap->u.bitmap[info.index]; bitmapWord < bitmapEnd; info.bit=0, bitmapWord++)
                 {
                         for (i=info.bit; i < 32; i++)
{
                                 // if this bit is marked as free..
                                 if (((*bitmapWord >> i) & 1)==0)
{
                                         if (count==0)
{
                                                 startBit = i;
                                                 startChunk = info.chunk;
                                                 startPos = bitmapWord - bitmap->u.bitmap;
                                         }
                                         if (++count == amount)
{
                                                 bi->number = (startPos * 32) + (startChunk * pfsBitsPerBitmapChunk) + startBit;
                                                 if (count < bi->count)
                                                         bi->count=count;
                                                 if (bitmap->block != (startChunk + (1 << pfsMount->inode_scale)))
{
                                                         pfsCacheFree(bitmap);
                                                         sector = (1 << pfsMount->inode_scale) + startChunk;
                                                         if(bi->subpart==0)
                                                                 sector += 0x2000 >> pfsBlockSize;
                                                         bitmap = pfsCacheGetData(pfsMount, bi->subpart, sector, PFS_CACHE_FLAG_BITMAP, &result);
                                                 }
                                                 pfsBitmapAllocFree(bitmap, PFS_BITMAP_ALLOC, bi->subpart, startChunk, startPos, startBit, bi->count);
                                                 return 1;
                                         }
                                 }
                                 else
                                         count=0;
                         }
                 }
                 pfsCacheFree(bitmap);
                 info.index=0;
         }
         return 0;
 }
References pfs_cache_t::bitmap, pfs_cache_t::block, pfs_blockinfo_t::count, pfs_mount_t::inode_scale, pfs_blockinfo_t::number, PFS_BITMAP_ALLOC, PFS_CACHE_FLAG_BITMAP, pfsBitmapAllocFree(), pfsBitmapSetupInfo(), pfsBitsPerBitmapChunk, pfsBlockSize, pfsCacheFree(), pfsCacheGetData(), pfsMetaSize, result, pfs_blockinfo_t::subpart, and pfs_cache_t::u.
Referenced by pfsBitmapSearchFreeZone().
pfsBitmapCalcFreeZones()
int pfsBitmapCalcFreeZones (pfs_mount_t * pfsMount, int sub)
Definition at line 288 of file bitmap.c.
 {
         // "Free zone" map. Used to get number of free zone in bitmap, 4-bits at a time
         u32 pfsFreeZoneBitmap[16]={4, 3, 3, 2, 3, 2, 2, 1, 3, 2, 2, 1, 2, 1, 1, 0};
         int result;
         pfs_bitmapInfo_t info;
         pfs_cache_t *clink;
         u32 i, bitmapSize, zoneFree=0, sector;
         pfsBitmapSetupInfo(pfsMount, &info, sub, 0);
         while (((info.partitionRemainder!=0) && (info.chunk<info.partitionChunks+1)) ||
                ((info.partitionRemainder==0) && (info.chunk<info.partitionChunks)))
         {
                 bitmapSize = info.chunk==info.partitionChunks ? info.partitionRemainder / 8 : pfsMetaSize;
                 sector = (1<<pfsMount->inode_scale) + info.chunk;
                 if (sub==0)
                         sector +=0x2000>>pfsBlockSize;
                 if ((clink=pfsCacheGetData(pfsMount, sub, sector, PFS_CACHE_FLAG_BITMAP, &result)))
                 {
                         for (i=0; i<bitmapSize; i++)
{
                                 zoneFree+=pfsFreeZoneBitmap[((u8*)clink->u.bitmap)[i] & 0xF]
                                    +pfsFreeZoneBitmap[((u8*)clink->u.bitmap)[i] >> 4];
                         }
                         pfsCacheFree(clink);
                 }
                 info.chunk++;
         }
         return zoneFree;
 }
References pfs_cache_t::bitmap, pfs_mount_t::inode_scale, PFS_CACHE_FLAG_BITMAP, pfsBitmapSetupInfo(), pfsBlockSize, pfsCacheFree(), pfsCacheGetData(), pfsMetaSize, result, and pfs_cache_t::u.
Referenced by pfsMountSuperBlock().
pfsBitmapFreeBlockSegment()
void pfsBitmapFreeBlockSegment (pfs_mount_t * pfsMount, pfs_blockinfo_t * bi)
Definition at line 266 of file bitmap.c.
 {
         pfs_bitmapInfo_t info;
         pfs_cache_t *clink;
         u32 sector;
         int rv;
         pfsBitmapSetupInfo(pfsMount, &info, bi->subpart, bi->number);
         sector = (1 << pfsMount->inode_scale) + info.chunk;
         if(bi->subpart==0)
                 sector += 0x2000 >> pfsBlockSize;
         if((clink=pfsCacheGetData(pfsMount, (u16)bi->subpart, sector, PFS_CACHE_FLAG_BITMAP, &rv)) != NULL)
         {
                 pfsBitmapAllocFree(clink, PFS_BITMAP_FREE, bi->subpart, info.chunk, info.index, info.bit, bi->count);
                 pfsMount->free_zone[(u16)bi->subpart]+=bi->count;
                 pfsMount->zfree+=bi->count;
         }
 }
References pfs_blockinfo_t::count, pfs_mount_t::free_zone, pfs_mount_t::inode_scale, NULL, pfs_blockinfo_t::number, PFS_BITMAP_FREE, PFS_CACHE_FLAG_BITMAP, pfsBitmapAllocFree(), pfsBitmapSetupInfo(), pfsBlockSize, pfsCacheGetData(), pfs_blockinfo_t::subpart, and pfs_mount_t::zfree.
Referenced by pfsBitmapFreeInodeBlocks(), pfsFreeZones(), and pfsInodeCreate().
pfsBitmapFreeInodeBlocks()
void pfsBitmapFreeInodeBlocks (pfs_cache_t * clink)
Definition at line 362 of file bitmap.c.
 {
         pfs_mount_t *pfsMount=clink->pfsMount;
         u32 i;
         pfsCacheUsedAdd(clink);
         for(i=0;i < clink->u.inode->number_data; i++)
         {
                 u32 index = pfsFixIndex(i);
                 pfs_blockinfo_t *bi=&clink->u.inode->data[index];
                 int err;
                 if(i!=0) {
                         if(index==0)
                                 if((clink = pfsBlockGetNextSegment(clink, &err))==NULL)
                                         return;
                 }
                 pfsBitmapFreeBlockSegment(pfsMount, bi);
                 pfsCacheMarkClean(pfsMount, (u16)bi->subpart,  bi->number << pfsMount->inode_scale,
                         (bi->number + bi->count) << pfsMount->inode_scale);
         }
         pfsCacheFree(clink);
 }
References pfs_blockinfo_t::count, pfs_inode_t::data, index(), pfs_cache_t::inode, pfs_mount_t::inode_scale, NULL, pfs_blockinfo_t::number, pfs_inode_t::number_data, pfsBitmapFreeBlockSegment(), pfsBlockGetNextSegment(), pfsCacheFree(), pfsCacheMarkClean(), pfsCacheUsedAdd(), pfsFixIndex(), pfs_cache_t::pfsMount, pfs_blockinfo_t::subpart, and pfs_cache_t::u.
Referenced by pfsFioRename(), and pfsInodeRemove().
pfsBitmapSearchFreeZone()
int pfsBitmapSearchFreeZone (pfs_mount_t * pfsMount, pfs_blockinfo_t * bi, u32 max_count)
Definition at line 228 of file bitmap.c.
 {
         u32 num, count, n;
         num = pfsMount->num_subs + 1;
         if (bi->subpart >= num)
                 bi->subpart = 0;
         if (bi->number)
                 num = pfsMount->num_subs + 2;
         count = max_count < 33 ? max_count : 32;                //min(max_count, 32)
         if(count < bi->count)
                 count = bi->count;                              //max(count, bi->count)
                                                                 // => count = bound(bi->count, 32);
         for(--num; num >= 0; num--)
         {
                 for (n = count; n; n /= 2)
                 {
                         if ((pfsMount->free_zone[bi->subpart] >= n) &&
                             pfsBitmapAllocZones(pfsMount, bi, n))
{
                                 pfsMount->free_zone[bi->subpart] -= bi->count;
                                 pfsMount->zfree -= bi->count;
                                 return 0;       // the good exit ;)
                         }
                 }
                 bi->number=0;
                 bi->subpart++;
                 if(bi->subpart == pfsMount->num_subs + 1)
                         bi->subpart=0;
         }
         return -ENOSPC;
 }
References pfs_blockinfo_t::count, ENOSPC, pfs_mount_t::free_zone, pfs_mount_t::num_subs, pfs_blockinfo_t::number, pfsBitmapAllocZones(), pfs_blockinfo_t::subpart, and pfs_mount_t::zfree.
Referenced by pfsBlockAllocNewSegment(), and pfsInodeCreate().
pfsBitmapSetupInfo()
void pfsBitmapSetupInfo (pfs_mount_t * pfsMount, pfs_bitmapInfo_t * info, u32 subpart, u32 number)
Definition at line 25 of file bitmap.c.
 {
         u32 size;
         size = pfsMount->blockDev->getSize(pfsMount->fd, subpart) >> pfsMount->sector_scale;
         info->chunk = number / pfsBitsPerBitmapChunk;
         info->bit = number & 31;
         info->index = (number % pfsBitsPerBitmapChunk) / 32;
         info->partitionChunks = size / pfsBitsPerBitmapChunk;
         info->partitionRemainder = size % pfsBitsPerBitmapChunk;
 }
References pfs_mount_t::blockDev, pfs_mount_t::fd, pfs_block_device_t::getSize, pfsBitsPerBitmapChunk, and pfs_mount_t::sector_scale.
Referenced by pfsBitmapAllocateAdditionalZones(), pfsBitmapAllocZones(), pfsBitmapCalcFreeZones(), pfsBitmapFreeBlockSegment(), and pfsBitmapShow().
pfsBitmapShow()
void pfsBitmapShow (pfs_mount_t * pfsMount)
Definition at line 325 of file bitmap.c.
 {
         int result;
         pfs_bitmapInfo_t info;
         u32 pn, bitcnt;
         for (pn=0; pn < pfsMount->num_subs+1; pn++)
         {
                 bitcnt=pfsBitsPerBitmapChunk;
                 pfsBitmapSetupInfo(pfsMount, &info, pn, 0);
                 while (((info.partitionRemainder!=0) && (info.chunk<info.partitionChunks+1)) ||
                        ((info.partitionRemainder==0) && (info.chunk<info.partitionChunks)))
                 {
                         pfs_cache_t *clink;
                         u32 sector = (1<<pfsMount->inode_scale) + info.chunk;
                         u32 i;
                         if(pn==0)
                                 sector += 0x2000 >> pfsBlockSize;
                         clink=pfsCacheGetData(pfsMount, pn, sector, PFS_CACHE_FLAG_BITMAP, &result);
                         if (info.chunk == info.partitionChunks)
                                 bitcnt=info.partitionRemainder;
                         PFS_PRINTF(PFS_DRV_NAME": Zone show: pn %ld, bn %ld, bitcnt %ld\n", pn, info.chunk, bitcnt);
                         for(i=0; (i < (u32)(1<<pfsBlockSize)) && ((i * 512) < (bitcnt / 8)); i++)
                                 pfsPrintBitmap(clink->u.bitmap+128*i);
                         pfsCacheFree(clink);
                         info.chunk++;
                 }
         }
 }
References pfs_cache_t::bitmap, pfs_mount_t::inode_scale, pfs_mount_t::num_subs, PFS_CACHE_FLAG_BITMAP, PFS_DRV_NAME, PFS_PRINTF, pfsBitmapSetupInfo(), pfsBitsPerBitmapChunk, pfsBlockSize, pfsCacheFree(), pfsCacheGetData(), pfsPrintBitmap(), result, and pfs_cache_t::u.
Referenced by pfsFioDevctl().
Variable Documentation
pfsBitsPerBitmapChunk
u32 pfsBitsPerBitmapChunk = 8192
Definition at line 23 of file bitmap.c.
Referenced by pfsBitmapAllocZones(), pfsBitmapSetupInfo(), and pfsBitmapShow().
pfsBlockSize
u32 pfsBlockSize extern
Definition at line 25 of file super.c.
Referenced by fioStatFiller(), pfsBitmapAllocateAdditionalZones(), pfsBitmapAllocFree(), pfsBitmapAllocZones(), pfsBitmapCalcFreeZones(), pfsBitmapFreeBlockSegment(), and pfsBitmapShow().
pfsMetaSize
u32 pfsMetaSize extern
Definition at line 26 of file super.c.
Referenced by pfsBitmapAllocateAdditionalZones(), pfsBitmapAllocFree(), pfsBitmapAllocZones(), and pfsBitmapCalcFreeZones().