ps2sdk: iop/fs/netfs/src/byteorder.h File Reference
byteorder.h File Reference
Functions
unsigned int htonl (unsigned int x)
unsigned short htons (unsigned short x)
Detailed Description
Lame header.
Definition in file byteorder.h.
Function Documentation
htonl()
unsigned int htonl (unsigned int x) inline
Definition at line 26 of file byteorder.h.
 {
     return ((x & 0xff) << 24 ) |
         ((x & 0xff00) << 8 ) |
         ((x & 0xff0000) >> 8 ) |
         ((x & 0xff000000) >> 24 );
 }
Referenced by ps2netfs_op_chdir(), ps2netfs_op_close(), ps2netfs_op_dclose(), ps2netfs_op_devlist(), ps2netfs_op_dopen(), ps2netfs_op_dread(), ps2netfs_op_format(), ps2netfs_op_fstype(), ps2netfs_op_info(), ps2netfs_op_ioctl(), ps2netfs_op_lseek(), ps2netfs_op_mkdir(), ps2netfs_op_mount(), ps2netfs_op_open(), ps2netfs_op_read(), ps2netfs_op_readlink(), ps2netfs_op_remove(), ps2netfs_op_rename(), ps2netfs_op_rmdir(), ps2netfs_op_symlink(), ps2netfs_op_sync(), ps2netfs_op_umount(), ps2netfs_op_write(), and ps2netfs_serv().
htons()
unsigned short htons (unsigned short x) inline
Definition at line 37 of file byteorder.h.
 {
     return ((x & 0xff) << 8 ) | ((x & 0xff00) >> 8 );
 }
Referenced by OpenTCPSession(), ps2netfs_op_chdir(), ps2netfs_op_close(), ps2netfs_op_dclose(), ps2netfs_op_devlist(), ps2netfs_op_dopen(), ps2netfs_op_dread(), ps2netfs_op_format(), ps2netfs_op_fstype(), ps2netfs_op_info(), ps2netfs_op_ioctl(), ps2netfs_op_lseek(), ps2netfs_op_mkdir(), ps2netfs_op_mount(), ps2netfs_op_open(), ps2netfs_op_read(), ps2netfs_op_readlink(), ps2netfs_op_remove(), ps2netfs_op_rename(), ps2netfs_op_rmdir(), ps2netfs_op_symlink(), ps2netfs_op_sync(), ps2netfs_op_umount(), ps2netfs_op_write(), ps2netfs_serv(), resolveAddress(), and udp_send().