ps2sdk: iop/cdvd/cdfs/src/cdfs_iop.h File Reference
cdfs_iop.h File Reference
Data Structures
struct TocEntry
Macros
#define DPRINTF(args...) do { } while(0)
#define CDFS_FILEPROPERTY_DIR 0x02
Enumerations
enum CDFS_getMode {
CDFS_GET_FILES_ONLY = 1 ,
CDFS_GET_DIRS_ONLY = 2 ,
CDFS_GET_FILES_AND_DIRS = 3
}
Functions
int cdfs_prepare (void)
int cdfs_start (void)
int cdfs_finish (void)
int cdfs_findfile (const char *fname, struct TocEntry *tocEntry)
int cdfs_readSect (u32 lsn, u32 sectors, u8 *buf)
int cdfs_getDir (const char *pathname, const char *extensions, enum CDFS_getMode getMode, struct TocEntry tocEntry[], unsigned int req_entries)
Macro Definition Documentation
CDFS_FILEPROPERTY_DIR
#define CDFS_FILEPROPERTY_DIR 0x02
Definition at line 10 of file cdfs_iop.h.
DPRINTF
#define DPRINTF (args...) do { } while(0)
Definition at line 7 of file cdfs_iop.h.
Enumeration Type Documentation
CDFS_getMode
enum CDFS_getMode
Enumerator
CDFS_GET_FILES_ONLY
CDFS_GET_DIRS_ONLY
CDFS_GET_FILES_AND_DIRS
Definition at line 20 of file cdfs_iop.h.
                   {
     CDFS_GET_FILES_ONLY = 1,
     CDFS_GET_DIRS_ONLY = 2,
     CDFS_GET_FILES_AND_DIRS = 3
 };
Function Documentation
cdfs_findfile()
int cdfs_findfile (const char * fname, struct TocEntry * tocEntry)
Definition at line 710 of file cdfs_iop.c.
{
     static char filename[128 + 1];
     static char pathname[1024 + 1];
     struct DirTocEntry *tocEntryPointer;
     DPRINTF("cdfs_findfile called\n\n");
     splitPath(fname, pathname, filename);
     DPRINTF("Trying to find file: %s in directory: %s\n", filename, pathname);
     if ((cacheInfoDir.valid) && (comparePath(pathname) == MATCH)) {
         // the directory is already cached, so check through the currently
         // cached chunk of the directory first
         tocEntryPointer = (struct DirTocEntry *)cacheInfoDir.cache;
         for (; tocEntryPointer < (struct DirTocEntry *)(cacheInfoDir.cache + (cacheInfoDir.cache_size * 2048)); tocEntryPointer = (struct DirTocEntry *)((u8 *)tocEntryPointer + tocEntryPointer->length)) {
             if (tocEntryPointer->length == 0) {
                 DPRINTF("Got a null pointer entry, so either reached end of dir, or end of sector\n");
                 tocEntryPointer = (struct DirTocEntry *)(cacheInfoDir.cache + (((((char *)tocEntryPointer - cacheInfoDir.cache) / 2048) + 1) * 2048));
             }
             if (tocEntryPointer >= (struct DirTocEntry *)(cacheInfoDir.cache + (cacheInfoDir.cache_size * 2048))) {
                 // reached the end of the cache block
                 break;
             }
             copyToTocEntry(tocEntry, tocEntryPointer);
             if (strcasecmp(tocEntry->filename, filename) == 0) {
                // and it matches !!
                return TRUE;
             }
         }  // end of for loop
         // If that was the only dir block, and we havent found it, then fail
         if (cacheInfoDir.cache_size == cacheInfoDir.sector_num)
             return FALSE;
         // Otherwise there is more dir to check
         if (cacheInfoDir.cache_offset == 0) {
             // If that was the first block then continue with the next block
             if (!cdfs_cacheDir(pathname, CACHE_NEXT))
                 return FALSE;
         } else {
             // otherwise (if that wasnt the first block) then start checking from the start
             if (!cdfs_cacheDir(pathname, CACHE_START))
                 return FALSE;
         }
     } else {
         DPRINTF("Trying to cache directory\n\n");
         // The wanted directory wasnt already cached, so cache it now
         if (!cdfs_cacheDir(pathname, CACHE_START)) {
             DPRINTF("Failed to cache directory\n\n");
             return FALSE;
         }
     }
     // If we've got here, then we have a block of the directory cached, and want to check
     // from this point, to the end of the dir
     DPRINTF("cache_size = %d\n", cacheInfoDir.cache_size);
     while (cacheInfoDir.cache_size > 0) {
         tocEntryPointer = (struct DirTocEntry *)cacheInfoDir.cache;
         if (cacheInfoDir.cache_offset == 0)
             tocEntryPointer = (struct DirTocEntry *)((u8 *)tocEntryPointer + tocEntryPointer->length);
         for (; tocEntryPointer < (struct DirTocEntry *)(cacheInfoDir.cache + (cacheInfoDir.cache_size * 2048)); tocEntryPointer = (struct DirTocEntry *)((u8 *)tocEntryPointer + tocEntryPointer->length)) {
             if (tocEntryPointer->length == 0) {
                 DPRINTF("Got a null pointer entry, so either reached end of dir, or end of sector\n");
                 DPRINTF("Offset into cache = %d bytes\n", (char *)tocEntryPointer - cacheInfoDir.cache);
                 tocEntryPointer = (struct DirTocEntry *)(cacheInfoDir.cache + (((((char *)tocEntryPointer - cacheInfoDir.cache) / 2048) + 1) * 2048));
             }
             if (tocEntryPointer >= (struct DirTocEntry *)(cacheInfoDir.cache + (cacheInfoDir.cache_size * 2048))) {
                 // reached the end of the cache block
                 break;
             }
             copyToTocEntry(tocEntry, tocEntryPointer);
             if (strcasecmp(tocEntry->filename, filename) == 0) {
                 DPRINTF("Found a matching file\n\n");
                 // and it matches !!
                 return TRUE;
             }
             DPRINTF("Non-matching file - looking for %s , found %s\n", filename, tocEntry->filename);
         }  // end of for loop
         DPRINTF("Reached end of cache block\n");
         // cache the next block
         cdfs_cacheDir(pathname, CACHE_NEXT);
     }
     // we've run out of dir blocks to cache, and still not found it, so fail
     DPRINTF("cdfs_findfile: could not find file\n");
     return FALSE;
 }
References CacheInfoDir::cache, CACHE_NEXT, CacheInfoDir::cache_offset, CacheInfoDir::cache_size, CACHE_START, cacheInfoDir, cdfs_cacheDir(), comparePath(), copyToTocEntry(), DPRINTF, FALSE, TocEntry::filename, DirTocEntry::filename, DirTocEntry::length, MATCH, CacheInfoDir::sector_num, splitPath(), strcasecmp(), TRUE, and CacheInfoDir::valid.
Referenced by fio_getstat(), and fio_open().
cdfs_finish()
int cdfs_finish (void)
Definition at line 703 of file cdfs_iop.c.
                       {
     if (cacheInfoDir.cache)
         FreeSysMemory(cacheInfoDir.cache);
     return 0;
 }
References CacheInfoDir::cache, cacheInfoDir, and FreeSysMemory().
Referenced by fio_deinit().
cdfs_getDir()
int cdfs_getDir (const char * pathname, const char * extensions, enum CDFS_getMode getMode, struct TocEntry tocEntry[], unsigned int req_entries)
Definition at line 892 of file cdfs_iop.c.
{
     int matched_entries;
     int dir_entry;
     struct TocEntry localTocEntry;
     struct DirTocEntry *tocEntryPointer;
     DPRINTF("cdfs_getDir Request\n\n");
     matched_entries = 0;
     // pre-cache the dir (and get the new pathname - in-case selected "..")
     if (!cdfs_cacheDir(pathname, CACHE_START)) {
         DPRINTF("cdfs_getDir - Call of cdfs_cacheDir failed\n\n");
         return -1;
     }
     DPRINTF("requested directory is %d sectors\n", cacheInfoDir.sector_num);
     if ((getMode == CDFS_GET_DIRS_ONLY) || (getMode == CDFS_GET_FILES_AND_DIRS)) {
         // Cache the start of the requested directory
         if (!cdfs_cacheDir(cacheInfoDir.pathname, CACHE_START)) {
             DPRINTF("cdfs_getDir - Call of cdfs_cacheDir failed\n\n");
             return -1;
         }
         tocEntryPointer = (struct DirTocEntry *)cacheInfoDir.cache;
         // skip the first self-referencing entry
         tocEntryPointer = (struct DirTocEntry *)((u8 *)tocEntryPointer + tocEntryPointer->length);
         // skip the parent entry if this is the root
         if (cacheInfoDir.path_depth == 0)
             tocEntryPointer = (struct DirTocEntry *)((u8 *)tocEntryPointer + tocEntryPointer->length);
         dir_entry = 0;
         while (1) {
             DPRINTF("cdfs_getDir - inside while-loop\n\n");
             // parse the current cache block
             for (; tocEntryPointer < (struct DirTocEntry *)(cacheInfoDir.cache + (cacheInfoDir.cache_size * 2048)); tocEntryPointer = (struct DirTocEntry *)((u8 *)tocEntryPointer + tocEntryPointer->length)) {
                 if (tocEntryPointer->length == 0) {
                     // if we have a toc entry length of zero,
                     // then we've either reached the end of the sector, or the end of the dir
                     // so point to next sector (if there is one - will be checked by next condition)
                     tocEntryPointer = (struct DirTocEntry *)(cacheInfoDir.cache + (((((char *)tocEntryPointer - cacheInfoDir.cache) / 2048) + 1) * 2048));
                 }
                 if (tocEntryPointer >= (struct DirTocEntry *)(cacheInfoDir.cache + (cacheInfoDir.cache_size * 2048))) {
                     // we've reached the end of the current cache block (which may be end of entire dir
                     // so just break the loop
                     break;
                 }
                 // Check if the current entry is a dir or a file
                 if (tocEntryPointer->fileProperties & 0x02) {
                     DPRINTF("We found a dir, and we want all dirs\n\n");
                     copyToTocEntry(&localTocEntry, tocEntryPointer);
                     if (dir_entry == 0) {
                         if (cacheInfoDir.path_depth != 0) {
                             DPRINTF("It's the first directory entry, so name it '..'\n\n");
                             strcpy(localTocEntry.filename, "..");
                         }
                     }
                     // Copy from localTocEntry
                     tocEntry[matched_entries] = localTocEntry;
                     matched_entries++;
                 } else { // it must be a file
                     DPRINTF("We found a file, but we dont want files (at least not yet)\n\n");
                 }
                 dir_entry++;
                 if (matched_entries >= req_entries)  // if we've filled the requested buffer
                     return (matched_entries);        // then just return
             }  // end of the current cache block
             // if there is more dir to load, then load next chunk, else finish
             if ((cacheInfoDir.cache_offset + cacheInfoDir.cache_size) < cacheInfoDir.sector_num) {
                 if (!cdfs_cacheDir(cacheInfoDir.pathname, CACHE_NEXT)) {
                     // failed to cache next block (should return TRUE even if
                     // there is no more directory, as long as a CD read didnt fail
                     return -1;
                 }
             } else
                 break;
             tocEntryPointer = (struct DirTocEntry *)cacheInfoDir.cache;
         }
     }
     // Next do files
     if ((getMode == CDFS_GET_FILES_ONLY) || (getMode == CDFS_GET_FILES_AND_DIRS)) {
         // Cache the start of the requested directory
         if (!cdfs_cacheDir(cacheInfoDir.pathname, CACHE_START)) {
             DPRINTF("cdfs_getDir - Call of cdfs_cacheDir failed\n\n");
             return -1;
         }
         tocEntryPointer = (struct DirTocEntry *)cacheInfoDir.cache;
         // skip the first self-referencing entry
         tocEntryPointer = (struct DirTocEntry *)((u8 *)tocEntryPointer + tocEntryPointer->length);
         // skip the parent entry if this is the root
         if (cacheInfoDir.path_depth == 0)
             tocEntryPointer = (struct DirTocEntry *)((u8 *)tocEntryPointer + tocEntryPointer->length);
         dir_entry = 0;
         while (1) {
             DPRINTF("cdfs_getDir - inside while-loop\n\n");
             // parse the current cache block
             for (; tocEntryPointer < (struct DirTocEntry *)(cacheInfoDir.cache + (cacheInfoDir.cache_size * 2048)); tocEntryPointer = (struct DirTocEntry *)((u8 *)tocEntryPointer + tocEntryPointer->length)) {
                 if (tocEntryPointer->length == 0) {
                     // if we have a toc entry length of zero,
                     // then we've either reached the end of the sector, or the end of the dir
                     // so point to next sector (if there is one - will be checked by next condition)
                     tocEntryPointer = (struct DirTocEntry *)(cacheInfoDir.cache + (((((char *)tocEntryPointer - cacheInfoDir.cache) / 2048) + 1) * 2048));
                 }
                 if (tocEntryPointer >= (struct DirTocEntry *)(cacheInfoDir.cache + (cacheInfoDir.cache_size * 2048))) {
                     // we've reached the end of the current cache block (which may be end of entire dir
                     // so just break the loop
                     break;
                 }
                 // Check if the current entry is a dir or a file
                 if (tocEntryPointer->fileProperties & 0x02) {
                     DPRINTF("We don't want files now\n\n");
                 } else { // it must be a file
                     copyToTocEntry(&localTocEntry, tocEntryPointer);
                     if (strlen(extensions) > 0) {
                         // check if the file matches the extension list
                         if (compareTocEntry(localTocEntry.filename, extensions)) {
                             DPRINTF("We found a file that matches the requested extension list\n\n");
                             // Copy from localTocEntry
                             tocEntry[matched_entries] = localTocEntry;
                             matched_entries++;
                         } else {
                             DPRINTF("We found a file, but it didnt match the requested extension list\n\n");
                         }
                     } else { // no extension list to match against
                         DPRINTF("We found a file, and there is not extension list to match against\n\n");
                         // Copy from localTocEntry
                         tocEntry[matched_entries] = localTocEntry;
                         matched_entries++;
                     }
                 }
                 dir_entry++;
                 if (matched_entries >= req_entries)  // if we've filled the requested buffer
                     return (matched_entries);        // then just return
             }  // end of the current cache block
             // if there is more dir to load, then load next chunk, else finish
             if ((cacheInfoDir.cache_offset + cacheInfoDir.cache_size) < cacheInfoDir.sector_num) {
                 if (!cdfs_cacheDir(cacheInfoDir.pathname, CACHE_NEXT)) {
                     // failed to cache next block (should return TRUE even if
                     // there is no more directory, as long as a CD read didnt fail
                     return -1;
                 }
             } else
                 break;
             tocEntryPointer = (struct DirTocEntry *)cacheInfoDir.cache;
         }
     }
     // reached the end of the dir, before filling up the requested entries
     return (matched_entries);
 }
References CacheInfoDir::cache, CACHE_NEXT, CacheInfoDir::cache_offset, CacheInfoDir::cache_size, CACHE_START, cacheInfoDir, cdfs_cacheDir(), CDFS_GET_DIRS_ONLY, CDFS_GET_FILES_AND_DIRS, CDFS_GET_FILES_ONLY, compareTocEntry(), copyToTocEntry(), DPRINTF, TocEntry::filename, DirTocEntry::fileProperties, DirTocEntry::length, CacheInfoDir::path_depth, CacheInfoDir::pathname, CacheInfoDir::sector_num, strcpy(), and strlen().
Referenced by fio_openDir().
cdfs_prepare()
int cdfs_prepare (void)
Definition at line 677 of file cdfs_iop.c.
{
     // Initialise the directory cache
     strcpy(cacheInfoDir.pathname, "");  // The pathname of the cached directory
     cacheInfoDir.valid = FALSE;         // Cache is not valid
     cacheInfoDir.path_depth = 0;        // 0 = root)
     cacheInfoDir.sector_start = 0;      // The start sector (LBA) of the cached directory
     cacheInfoDir.sector_num = 0;        // The total size of the directory (in sectors)
     cacheInfoDir.cache_offset = 0;      // The offset from sector_start of the cached area
     cacheInfoDir.cache_size = 0;        // The size of the cached directory area (in sectors)
     if (cacheInfoDir.cache == NULL)
         cacheInfoDir.cache = (char *)AllocSysMemory(0, MAX_DIR_CACHE_SECTORS * 2048, NULL);
      // setup the cdReadMode structure
     cdReadMode.trycount = 0;
     cdReadMode.spindlctrl = SCECdSpinStm;
     cdReadMode.datapattern = SCECdSecS2048;
     return 0;
 }
References AllocSysMemory(), CacheInfoDir::cache, CacheInfoDir::cache_offset, CacheInfoDir::cache_size, cacheInfoDir, cdReadMode, sceCdRMode::datapattern, FALSE, MAX_DIR_CACHE_SECTORS, NULL, CacheInfoDir::path_depth, CacheInfoDir::pathname, SCECdSecS2048, SCECdSpinStm, CacheInfoDir::sector_num, CacheInfoDir::sector_start, sceCdRMode::spindlctrl, strcpy(), sceCdRMode::trycount, and CacheInfoDir::valid.
Referenced by _start().
cdfs_readSect()
int cdfs_readSect (u32 lsn, u32 sectors, u8 * buf)
Definition at line 815 of file cdfs_iop.c.
{
     u32 i;
     u32 consecutive_sectors = (sectors > 2) ? (sectors * 2048) / 2064 : 0;
     int retry;
     int result = 0;
     cdReadMode.trycount = 32;
     for (retry = 0; retry < 32; retry++) { // 32 retries
         if (retry <= 8)
             cdReadMode.spindlctrl = 1;  // Try fast reads for first 8 tries
         else
             cdReadMode.spindlctrl = 0;  // Then try slow reads
         if (!isValidDisc())
             return FALSE;
         sceCdDiskReady(0);
         if (sceCdGetDiskType() == SCECdDVDV)
         {
             if (consecutive_sectors > 0)
             {
                 result = !sceCdReadDVDV(lsn, consecutive_sectors, buf, &cdReadMode);
                 if (result == 0)
                 {
                     sceCdSync(0);
                     result = sceCdGetError();
                 }
                 if (result != 0)
                 {
                     continue;
                 }
             }
             for (i = 0; i < consecutive_sectors; i += 1)
             {
                 memmove(buf + (2048 * i), buf + (2064 * i) + 12, 2048);
             }
             for (i = consecutive_sectors; i < sectors; i += 1)
             {
                 result = !sceCdReadDVDV(lsn + i, 1, dvdvBuffer, &cdReadMode);
                 if (result == 0)
                 {
                     sceCdSync(0);
                     result = sceCdGetError();
                 }
                 if (result != 0)
                 {
                     break;
                 }
                 memcpy(buf + (2048 * i), dvdvBuffer + 12, 2048);
             }
         }
         else
         {
             result = !sceCdRead(lsn, sectors, buf, &cdReadMode);
             if (result == 0)
             {
                 sceCdSync(0);
                 result = sceCdGetError();
             }
         }
         if (result == 0)
             break;
     }
     cdReadMode.trycount = 32;
     cdReadMode.spindlctrl = 1;
     if (result == 0)
         return TRUE;
     memset(buf, 0, (sectors << 11));
     return FALSE;  // error
 }
References cdReadMode, dvdvBuffer, FALSE, isValidDisc(), memcpy(), memmove(), memset(), result, sceCdDiskReady(), SCECdDVDV, sceCdGetDiskType(), sceCdGetError(), sceCdRead(), sceCdReadDVDV(), sceCdSync(), sceCdRMode::spindlctrl, TRUE, and sceCdRMode::trycount.
Referenced by cdfs_cacheDir(), cdfs_getVolumeDescriptor(), findPath(), and fio_read().
cdfs_start()
int cdfs_start (void)
Definition at line 699 of file cdfs_iop.c.
                      {
     return sceCdInit(SCECdINoD);
 }
References sceCdInit(), and SCECdINoD.
Referenced by fio_init().