ps2sdk: iop/cdvd/cdfs/src/main.c File Reference
main.c File Reference
#include <stdio.h>
#include <ioman.h>
#include <iox_stat.h>
#include <sysclib.h>
#include "cdfs_iop.h"
Data Structures
struct fdtable
struct fodtable
Macros
#define MAX_FILES_PER_FOLDER 256
#define MAX_FILES_OPENED 16
#define MAX_FOLDERS_OPENED 16
#define MAX_BYTES_READ 16384
#define DRIVER_UNIT_NAME "cdfs"
#define DRIVER_UNIT_VERSION 2
Functions
static int fio_init (iop_device_t *driver)
static int fio_deinit (iop_device_t *f)
static int fio_open (iop_file_t *f, const char *name, int mode)
static int fio_close (iop_file_t *f)
static int fio_read (iop_file_t *f, void *buffer, int size)
static int fio_write (iop_file_t *f, void *buffer, int size)
static int fio_lseek (iop_file_t *f, int offset, int whence)
static int fio_openDir (iop_file_t *f, const char *path)
static int fio_closeDir (iop_file_t *fd)
static int fio_dread (iop_file_t *fd, io_dirent_t *dirent)
static int fio_getstat (iop_file_t *fd, const char *name, io_stat_t *stat)
static int cdfs_dummy ()
int _start (int argc, char **argv)
Variables
static struct fdtable fd_table [MAX_FILES_OPENED]
static int fd_used [MAX_FILES_OPENED]
static struct fodtable fod_table [MAX_FOLDERS_OPENED]
static int fod_used [MAX_FOLDERS_OPENED]
static int lastsector
static int last_bk = 0
static iop_device_ops_t fio_ops
Macro Definition Documentation
DRIVER_UNIT_NAME
#define DRIVER_UNIT_NAME "cdfs"
Definition at line 14 of file main.c.
DRIVER_UNIT_VERSION
#define DRIVER_UNIT_VERSION 2
Definition at line 15 of file main.c.
MAX_BYTES_READ
#define MAX_BYTES_READ 16384
Definition at line 12 of file main.c.
MAX_FILES_OPENED
#define MAX_FILES_OPENED 16
Definition at line 10 of file main.c.
MAX_FILES_PER_FOLDER
#define MAX_FILES_PER_FOLDER 256
Definition at line 9 of file main.c.
MAX_FOLDERS_OPENED
#define MAX_FOLDERS_OPENED 16
Definition at line 11 of file main.c.
Function Documentation
_start()
int _start (int argc, char ** argv)
Definition at line 428 of file main.c.
 {
     static iop_device_t fio_driver;
     // Prepare cache and read mode
     cdfs_prepare();
     char driverDesc[50];
     sprintf(driverDesc, "%s Filedriver v%i", DRIVER_UNIT_NAME, DRIVER_UNIT_VERSION);
     // setup the fio_driver structure
     fio_driver.name = DRIVER_UNIT_NAME;
     fio_driver.type = IOP_DT_FS;
     fio_driver.version = DRIVER_UNIT_VERSION;
     fio_driver.desc = driverDesc;
     fio_driver.ops = &fio_ops;
     DelDrv(DRIVER_UNIT_NAME);
     if(AddDrv(&fio_driver) != 0) { return(-1); }
     return(0);
 }
References AddDrv(), cdfs_prepare(), DelDrv(), iop_device_t::desc, DRIVER_UNIT_NAME, DRIVER_UNIT_VERSION, fio_ops, IOP_DT_FS, iop_device_t::name, iop_device_t::ops, sprintf(), iop_device_t::type, and iop_device_t::version.
cdfs_dummy()
static int cdfs_dummy () static
Definition at line 403 of file main.c.
{
     DPRINTF("CDFS: dummy function called\n\n");
     return -5;
 }
References DPRINTF.
fio_close()
static int fio_close (iop_file_t * f) static
Definition at line 121 of file main.c.
 {
     int i;
     DPRINTF("CDFS: fio_close called.\n");
     DPRINTF("      kernel fd.. %p\n\n", f);
     i = (int)f->privdata;
     if (i >= MAX_FILES_OPENED) {
         printf("fio_close: ERROR: File does not appear to be open!\n");
         return -1;
     }
     fd_used[i] = 0;
     return 0;
 }
References DPRINTF, fd_used, MAX_FILES_OPENED, printf(), and iop_file_t::privdata.
fio_closeDir()
static int fio_closeDir (iop_file_t * fd) static
Definition at line 313 of file main.c.
 {
     int i;
     DPRINTF("CDFS: fio_closeDir called.\n");
     DPRINTF("      kernel_fd.. %p\n", fd);
     i = (int)fd->privdata;
     if (i >= MAX_FOLDERS_OPENED) {
         printf("fio_close: ERROR: File does not appear to be open!\n");
         return -1;
     }
     fod_used[i] = 0;
     return 0;
 }
References DPRINTF, fod_used, MAX_FOLDERS_OPENED, printf(), and iop_file_t::privdata.
fio_deinit()
static int fio_deinit (iop_device_t * f) static
Definition at line 63 of file main.c.
 {
     DPRINTF("CDFS: fio_deinit called.\n");
     DPRINTF("      kernel_fd.. %p\n", f);
     return cdfs_finish();
 }
References cdfs_finish(), and DPRINTF.
fio_dread()
static int fio_dread (iop_file_t * fd, io_dirent_t * dirent) static
Definition at line 331 of file main.c.
 {
     int i;
     int filesIndex;
     struct TocEntry entry;
     DPRINTF("CDFS: fio_dread called.\n");
     DPRINTF("      kernel_fd.. %p\n", fd);
     DPRINTF("      mode....... %p\n\n", dirent);
     i = (int)fd->privdata;
     if (i >= MAX_FOLDERS_OPENED) {
         printf("fio_dread: ERROR: Folder does not appear to be open!\n\n");
         return -1;
     }
     filesIndex = fod_table[i].filesIndex;
     if (filesIndex >= fod_table[i].files) {
         printf("fio_dread: No more items pending to read!\n\n");
         return -1;
     }
     entry = fod_table[i].entries[filesIndex];
     DPRINTF("fio_dread: fod_table index=%i, fileIndex=%i\n\n", i, filesIndex);
     DPRINTF("fio_dread: entries=%i\n\n", fod_table[i].files);
     DPRINTF("fio_dread: reading entry\n\n");
     DPRINTF("      entry.. %p\n", entry);
     DPRINTF("      filesize....... %i\n\n", entry.fileSize);
     DPRINTF("      filename....... %s\n\n", entry.filename);
     DPRINTF("      fileproperties.. %i\n\n", entry.fileProperties);
     dirent->stat.mode = (entry.fileProperties == CDFS_FILEPROPERTY_DIR) ? FIO_SO_IFDIR : FIO_SO_IFREG;
     dirent->stat.attr = entry.fileProperties;
     dirent->stat.size = entry.fileSize;
     memcpy(dirent->stat.ctime, entry.dateStamp, 8);
     memcpy(dirent->stat.atime, entry.dateStamp, 8);
     memcpy(dirent->stat.mtime, entry.dateStamp, 8);
     strncpy(dirent->name, entry.filename, 128);
     dirent->unknown = 0;
     fod_table[i].filesIndex++;
     return fod_table[i].filesIndex;
 }
References io_stat_t::atime, io_stat_t::attr, CDFS_FILEPROPERTY_DIR, io_stat_t::ctime, TocEntry::dateStamp, DPRINTF, fodtable::entries, TocEntry::filename, TocEntry::fileProperties, fodtable::filesIndex, TocEntry::fileSize, FIO_SO_IFDIR, FIO_SO_IFREG, fod_table, MAX_FOLDERS_OPENED, memcpy(), io_stat_t::mode, io_stat_t::mtime, io_dirent_t::name, printf(), iop_file_t::privdata, io_stat_t::size, io_dirent_t::stat, strncpy(), and io_dirent_t::unknown.
fio_getstat()
static int fio_getstat (iop_file_t * fd, const char * name, io_stat_t * stat) static
Definition at line 377 of file main.c.
 {
     struct TocEntry entry;
     int ret = -1;
     DPRINTF("CDFS: fio_getstat called.\n");
     DPRINTF("      kernel_fd.. %p\n", fd);
     DPRINTF("      name....... %s\n\n", name);
     ret = cdfs_findfile(name, &entry);
     DPRINTF("      entry.. %p\n", entry);
     DPRINTF("      filesize....... %i\n\n", entry.fileSize);
     DPRINTF("      filename....... %s\n\n", entry.filename);
     DPRINTF("      fileproperties.. %i\n\n", entry.fileProperties);
     stat->mode = (entry.fileProperties == CDFS_FILEPROPERTY_DIR) ? FIO_SO_IFDIR : FIO_SO_IFREG;
     stat->attr = entry.fileProperties;
     stat->size = entry.fileSize;
     memcpy(stat->ctime, entry.dateStamp, 8);
     memcpy(stat->atime, entry.dateStamp, 8);
     memcpy(stat->mtime, entry.dateStamp, 8);
     return ret;
 }
References io_stat_t::atime, io_stat_t::attr, CDFS_FILEPROPERTY_DIR, cdfs_findfile(), io_stat_t::ctime, TocEntry::dateStamp, DPRINTF, TocEntry::filename, TocEntry::fileProperties, TocEntry::fileSize, FIO_SO_IFDIR, FIO_SO_IFREG, memcpy(), io_stat_t::mode, io_stat_t::mtime, and io_stat_t::size.
fio_init()
static int fio_init (iop_device_t * driver) static
Definition at line 51 of file main.c.
 {
     printf("%s\n", driver->desc);
     printf("Re-edited by fjtrujy\n");
     printf("Original implementation\n");
     printf("by A.Lee (aka Hiryu) & Nicholas Van Veen (aka Sjeep)\n");
     printf("CDFS: Initializing '%s' file driver.\n", driver->name);
     cdfs_start();
     return 0;
 }
References cdfs_start(), iop_io_device_t::desc, driver, iop_io_device_t::name, and printf().
fio_lseek()
static int fio_lseek (iop_file_t * f, int offset, int whence) static
Definition at line 222 of file main.c.
 {
     int i;
     DPRINTF("CDFS: fio_lseek called.\n");
     DPRINTF("      kernel_fd... %p\n", f);
     DPRINTF("      offset...... %d\n", offset);
     DPRINTF("      whence...... %d\n\n", whence);
     i = (int) f->privdata;
     if (i >= 16) {
         DPRINTF("fio_lseek: ERROR: File does not appear to be open!\n");
         return -1;
     }
     switch (whence) {
         case SEEK_SET:
             fd_table[i].filePos = offset;
             break;
         case SEEK_CUR:
             fd_table[i].filePos += offset;
             break;
         case SEEK_END:
             fd_table[i].filePos = fd_table[i].fileSize + offset;
             break;
         default:
             return -1;
     }
     if (fd_table[i].filePos < 0)
         fd_table[i].filePos = 0;
     if (fd_table[i].filePos > fd_table[i].fileSize)
         fd_table[i].filePos = fd_table[i].fileSize;
     return fd_table[i].filePos;
 }
References DPRINTF, fd_table, fdtable::filePos, TocEntry::fileSize, fdtable::fileSize, iop_file_t::privdata, SEEK_CUR, SEEK_END, and SEEK_SET.
fio_open()
static int fio_open (iop_file_t * f, const char * name, int mode) static
Definition at line 70 of file main.c.
 {
     int j;
     static struct TocEntry tocEntry;
     DPRINTF("CDFS: fio_open called.\n");
     DPRINTF("      kernel_fd.. %p\n", f);
     DPRINTF("      name....... %s %x\n", name, (int)name);
     DPRINTF("      mode....... %d\n\n", mode);
     // check if the file exists
     if (!cdfs_findfile(name, &tocEntry)) {
         printf("***** FILE %s CAN NOT FOUND ******\n\n", name);
         return -1;
     }
     if (mode != O_RDONLY) {
         printf("mode is different than O_RDONLY, expected %i, received %i\n\n", O_RDONLY, mode);
         return -2;
     }
     DPRINTF("CDFS: fio_open TocEntry info\n");
     DPRINTF("      TocEntry....... %p\n", &tocEntry);
     DPRINTF("      fileLBA........ %i\n", tocEntry.fileLBA);
     DPRINTF("      fileSize....... %i\n", tocEntry.fileSize);
     DPRINTF("      fileProperties. %i\n", tocEntry.fileProperties);
     DPRINTF("      dateStamp...... %s\n", tocEntry.dateStamp);
     DPRINTF("      filename....... %s\n", tocEntry.filename);
     // set up a new file descriptor
     for (j = 0; j < MAX_FILES_OPENED; j++) {
         if (fd_used[j] == 0)
             break;
     }
     if (j >= MAX_FILES_OPENED) {
         printf("File descriptor overflow!!\n\n");
         return -3;
     }
     fd_used[j] = 1;
     fd_table[j].fd = f;
     fd_table[j].fileSize = tocEntry.fileSize;
     fd_table[j].LBA = tocEntry.fileLBA;
     fd_table[j].filePos = 0;
     f->privdata = (void *)j;
     return j;
 }
References cdfs_findfile(), TocEntry::dateStamp, DPRINTF, fdtable::fd, fd_table, fd_used, TocEntry::fileLBA, TocEntry::filename, fdtable::filePos, TocEntry::fileProperties, TocEntry::fileSize, fdtable::fileSize, fdtable::LBA, MAX_FILES_OPENED, O_RDONLY, printf(), and iop_file_t::privdata.
fio_openDir()
static int fio_openDir (iop_file_t * f, const char * path) static
Definition at line 264 of file main.c.
{
    int j;
     DPRINTF("CDFS: fio_openDir called.\n");
     DPRINTF("      kernel_fd.. %p\n", f);
     DPRINTF("      name....... %s\n", f->device->name);
     DPRINTF("      mode....... %d\n\n", f->mode);
     DPRINTF("      path....... %s\n\n", path);
     // set up a new file descriptor
     for (j = 0; j < MAX_FOLDERS_OPENED; j++) {
         if (fod_used[j] == 0)
             break;
     }
     if (j >= MAX_FOLDERS_OPENED)
         return -3;
     fod_table[j].files = cdfs_getDir(path, NULL, CDFS_GET_FILES_AND_DIRS, fod_table[j].entries, MAX_FILES_PER_FOLDER);
     if (fod_table[j].files < 0) {
         printf("The path doesn't exist\n\n");
         return -2;
     }
     fod_table[j].filesIndex = 0;
     fod_table[j].fd = f;
     fod_used[j] = 1;
     DPRINTF("ITEMS %i\n\n", fod_table[j].files);
 #ifdef DEBUG
     int index = 0;
     for (index=0; index < fod_table[j].files; index++) {
         struct TocEntry tocEntry = fod_table[j].entries[index];
         DPRINTF("CDFS: fio_openDir index=%d TocEntry info\n", index);
         DPRINTF("      TocEntry....... %p\n", &tocEntry);
         DPRINTF("      fileLBA........ %i\n", tocEntry.fileLBA);
         DPRINTF("      fileSize....... %i\n", tocEntry.fileSize);
         DPRINTF("      fileProperties. %i\n", tocEntry.fileProperties);
         DPRINTF("      dateStamp....... %s\n", tocEntry.dateStamp);
         DPRINTF("      filename....... %s\n", tocEntry.filename);
     }
 #endif
     f->privdata = (void *)j;
     return j;
 }
References CDFS_GET_FILES_AND_DIRS, cdfs_getDir(), TocEntry::dateStamp, iop_file_t::device, DPRINTF, fodtable::entries, fodtable::fd, TocEntry::fileLBA, TocEntry::filename, TocEntry::fileProperties, fodtable::files, fodtable::filesIndex, TocEntry::fileSize, fod_table, fod_used, index(), MAX_FILES_PER_FOLDER, MAX_FOLDERS_OPENED, iop_file_t::mode, NULL, printf(), and iop_file_t::privdata.
fio_read()
static int fio_read (iop_file_t * f, void * buffer, int size) static
Definition at line 140 of file main.c.
 {
     int i;
     int start_sector;
     int off_sector;
     int num_sectors;
     int read = 0;
     static char local_buffer[9 * 2048];
     DPRINTF("CDFS: fio_read called\n\n");
     DPRINTF("      kernel_fd... %p\n", f);
     DPRINTF("      buffer...... 0x%X\n", (int)buffer);
     DPRINTF("      size........ %d\n\n", size);
     i = (int)f->privdata;
     if (i >= MAX_FILES_OPENED) {
         printf("fio_read: ERROR: File does not appear to be open!\n");
         return -1;
     }
     // A few sanity checks
     if (fd_table[i].filePos > fd_table[i].fileSize) {
         // We cant start reading from past the beginning of the file
         return 0;  // File exists but we couldnt read anything from it
     }
     if ((fd_table[i].filePos + size) > fd_table[i].fileSize)
         size = fd_table[i].fileSize - fd_table[i].filePos;
     if (size <= 0)
         return 0;
     if (size > MAX_BYTES_READ)
         size = MAX_BYTES_READ;
     // Now work out where we want to start reading from
     start_sector = fd_table[i].LBA + (fd_table[i].filePos >> 11);
     off_sector = (fd_table[i].filePos & 0x7FF);
     num_sectors = (off_sector + size);
     num_sectors = (num_sectors >> 11) + ((num_sectors & 2047) != 0);
     DPRINTF("fio_read: read sectors %d to %d\n", start_sector, start_sector + num_sectors);
     // Skip a Sector for equal (use the last sector in buffer)
     if (start_sector == lastsector) {
         read = 1;
         if (last_bk > 0)
             memcpy(local_buffer, local_buffer + 2048 * (last_bk), 2048);
         last_bk = 0;
     }
     lastsector = start_sector + num_sectors - 1;
     // Read the data (we only ever get 16KB max request at once)
     if (read == 0 || (read == 1 && num_sectors > 1)) {
         if (!cdfs_readSect(start_sector + read, num_sectors - read, local_buffer + ((read) << 11))) {
             DPRINTF("Couldn't Read from file for some reason\n");
         }
         last_bk = num_sectors - 1;
     }
     memcpy(buffer, local_buffer + off_sector, size);
     fd_table[i].filePos += size;
     return (size);
 }
References buffer, cdfs_readSect(), DPRINTF, fd_table, fdtable::filePos, TocEntry::fileSize, fdtable::fileSize, last_bk, lastsector, fdtable::LBA, MAX_BYTES_READ, MAX_FILES_OPENED, memcpy(), printf(), iop_file_t::privdata, and read().
fio_write()
static int fio_write (iop_file_t * f, void * buffer, int size) static
Definition at line 212 of file main.c.
 {
     if (size == 0)
         return 0;
     else {
         printf("CDFS: dummy fio_write function called, this is not a re-writer xD");
         return -1;
     }
 }
References printf().
Variable Documentation
fd_table
struct fdtable fd_table[MAX_FILES_OPENED] static
Definition at line 1 of file main.c.
Referenced by fio_lseek(), fio_open(), and fio_read().
fd_used
int fd_used[MAX_FILES_OPENED] static
Definition at line 35 of file main.c.
Referenced by fio_close(), and fio_open().
fio_ops
iop_device_ops_t fio_ops static
Initial value:
= {
    fio_init,
    fio_deinit,
    cdfs_dummy,
    fio_open,
    fio_close,
    fio_read,
    fio_write,
    fio_lseek,
    cdfs_dummy,
    cdfs_dummy,
    cdfs_dummy,
    cdfs_dummy,
    fio_openDir,
    fio_closeDir,
    fio_dread,
    fio_getstat,
    cdfs_dummy
}
Definition at line 408 of file main.c.
Referenced by _start().
fod_table
struct fodtable fod_table[MAX_FOLDERS_OPENED] static
Definition at line 35 of file main.c.
Referenced by fio_dread(), and fio_openDir().
fod_used
int fod_used[MAX_FOLDERS_OPENED] static
Definition at line 39 of file main.c.
Referenced by fio_closeDir(), and fio_openDir().
last_bk
int last_bk = 0 static
Definition at line 43 of file main.c.
Referenced by fio_read().
lastsector
int lastsector static
Definition at line 42 of file main.c.
Referenced by fio_read().