ps2sdk: iop/debug/iopdebug/src/main.c File Reference
main.c File Reference
#include <tamtypes.h>
#include <stdio.h>
#include <loadcore.h>
#include <thbase.h>
#include "iopdebug.h"
#include "iopdebug_priv.h"
Functions
IRX_ID ("iopdebug", 1, 0)
int _start (int argc, char *argv[])
int _stop (int argc, char *argv[])
Variables
struct irx_export_table _exp_iopdebug
Detailed Description
IOPDEBUG - IOP debugging library. startup code
Definition in file main.c.
Function Documentation
_start()
int _start (int argc, char * argv[])
Definition at line 18 of file main.c.
 {
     // install IOP debug system.
     if(iop_dbg_install() != 0)
     {
         //printf("Failed installing IOP debug system!\n");
         return(1); // return "non-resident"
     }
     // register our IRX exports.
     if(RegisterLibraryEntries(&_exp_iopdebug) != 0)
     {
         iop_dbg_remove();
         //printf("Error registering library!\n");
         return(1);
     }
     FlushIcache();
     FlushDcache();
     //printf("IOPDEBUG installed!\n");
     return(0); // return "resident"
 }
References _exp_iopdebug, FlushDcache(), FlushIcache(), iop_dbg_install(), iop_dbg_remove(), and RegisterLibraryEntries().
_stop()
int _stop (int argc, char * argv[])
Definition at line 44 of file main.c.
 {
     // remove IOP debug system.
     if(iop_dbg_remove() != 0)
     {
         //printf("Failed removing IOP debug handlers!\n");
     }
     return(1); // return "non-resident"
 }
References iop_dbg_remove().
IRX_ID()
IRX_ID ("iopdebug" , 1 , 0)
Variable Documentation
_exp_iopdebug
struct irx_export_table _exp_iopdebug extern
Referenced by _start().