ps2sdk: iop/debug/iop_sbusdbg/src/main.c File Reference
main.c File Reference
#include <tamtypes.h>
#include <stdio.h>
#include <loadcore.h>
#include <thbase.h>
#include <iop_cop0_defs.h>
#include <ps2_sbus.h>
#include <iopdebug.h>
#include <excepman.h>
#include "sbus_tty.h"
Functions
IRX_ID ("sbusdebug", 1, 0)
void signal_iop_exception (IOP_RegFrame *frame)
void _iop_ex_handler (IOP_RegFrame *frame)
void soft_break (void)
void _controller_thread (void)
void create_th (void)
void SBUS_dbg_init (void)
int _start (int argc, char *argv[])
Variables
volatile int _iop_controlled = 0
volatile int _iop_exception_state = 0
int tid
Function Documentation
_controller_thread()
void _controller_thread (void)
Definition at line 50 of file main.c.
 {
     while(1)
     {
 //        printf("IOP: Controller thread going to sleep(%d)...\n", _iop_exception_state);
         SleepThread();
 //        printf("IOP: Controller thread woke up!\n");
         soft_break();
     }
 }
References SleepThread(), and soft_break().
Referenced by create_th().
_iop_ex_handler()
void _iop_ex_handler (IOP_RegFrame * frame)
Definition at line 19 of file main.c.
 {
     int excode = M_IOP_GET_CAUSE_EXCODE(frame->cause);
     if(excode == IOP_EXCEPTION_HDB)
     {
         _iop_exception_state = 2;
     }
     else
     {
         _iop_exception_state = 1;
     }
     _iop_controlled = 1;
     // signal to the EE that an IOP exception occured.
     signal_iop_exception(frame);
     // wait for EE to send a "IOP control" command and release the IOP.
     while(_iop_controlled)
     {
         // since we're spinning in an interrupt-disabled state, we have to manually
         //  poll for SBUS interrupts from EE, otherwise we'll never get released!
         SBUS_check_intr();
     }
 }
References _iop_controlled, _iop_exception_state, IOP_RegFrame::cause, IOP_EXCEPTION_HDB, M_IOP_GET_CAUSE_EXCODE, and signal_iop_exception().
Referenced by _start().
_start()
int _start (int argc, char * argv[])
Definition at line 77 of file main.c.
 {
     int i;
     for(i = 2; i <= 7; i++)
     {
         iop_dbg_set_handler(i, (IOP_ExceptionHandler *) _iop_ex_handler);
     }
     for(i = 9; i <= 15; i++)
     {
         iop_dbg_set_handler(i, (IOP_ExceptionHandler *) _iop_ex_handler);
     }
     create_th();
     if(sbus_tty_init() != 0)
     {
         printf("Failed initializing SBUS TTY system!\n");
         return(1);
     }
     SBUS_dbg_init();
     FlushIcache();
     FlushDcache();
     printf("IOP SBUS Debug installed!\n");
     return(0); // return resident!
 }
References _iop_ex_handler(), create_th(), FlushDcache(), FlushIcache(), iop_dbg_set_handler(), printf(), SBUS_dbg_init(), and sbus_tty_init().
create_th()
void create_th (void)
Definition at line 61 of file main.c.
 {
         iop_thread_t param;
         param.attr = TH_C;
         param.thread = (void *) _controller_thread;
         param.priority = 9; // highest possible priority
         param.stacksize = 512; // tiny stack, not much is needed!
         param.option = 0;
         tid = CreateThread(&param);
         StartThread(tid, 0);
 }
References _controller_thread(), iop_thread_t::attr, CreateThread(), iop_thread_t::option, iop_thread_t::priority, iop_thread_t::stacksize, StartThread(), TH_C, iop_thread_t::thread, and tid.
Referenced by _start().
IRX_ID()
IRX_ID ("sbusdebug" , 1 , 0)
SBUS_dbg_init()
void SBUS_dbg_init (void)
Definition at line 76 of file sbus_dbg.c.
 {
     iop_dbg_get_reg_frames(&_iop_ex_def_frame, &_iop_ex_dbg_frame);
     SIF2_set_cmd_handler(SIF2_CMD_DBG_CTRL, &_sif2_cmd_dbg_control, NULL);
 }
References _iop_ex_dbg_frame, _iop_ex_def_frame, _sif2_cmd_dbg_control(), iop_dbg_get_reg_frames(), NULL, and SIF2_CMD_DBG_CTRL.
Referenced by _start().
signal_iop_exception()
void signal_iop_exception (IOP_RegFrame * frame)
Definition at line 39 of file sbus_dbg.c.
 {
     SIF2_send_cmd(SIF2_CMD_DBG_EXC, (void *) frame, sizeof(IOP_RegFrame));
 }
Referenced by _iop_ex_handler().
soft_break()
void soft_break (void)
Referenced by _controller_thread().
Variable Documentation
_iop_controlled
volatile int _iop_controlled = 0
Definition at line 13 of file main.c.
Referenced by _iop_ex_handler(), and _sif2_cmd_dbg_control().
_iop_exception_state
volatile int _iop_exception_state = 0
Definition at line 14 of file main.c.
Referenced by _iop_ex_handler(), and _sif2_cmd_dbg_control().
tid
int tid
Definition at line 46 of file main.c.
Referenced by _sif2_cmd_dbg_control(), create_th(), create_thread(), rpcMainThread(), and sys_thread_new().