ps2sdk: iop/kernel/include/defs.h File Reference
defs.h File Reference
#include <types.h>
Macros
#define NULL ((void *)0)
#define ALIGN(x, align) (((x)+((align)-1))&~((align)-1))
#define PHYSADDR(a) (((u32)(a)) & 0x1fffffff)
#define KSEG1 0xa0000000
#define KSEG1ADDR(a) ((__typeof__(a))(((u32)(a) & 0x1fffffff) | KSEG1))
#define SetModuleGP() ChangeGP(&_gp)
Functions
static __inline__ void * ChangeGP (void *gp)
static __inline__ void SetGP (void *gp)
static __inline__ void * GetGP (void)
static void * iop_memcpy (void *dest, const void *src, int size)
Variables
void * _gp
Detailed Description
IOPkit standard definitions.
Definition in file defs.h.
Macro Definition Documentation
ALIGN
#define ALIGN (x, align) (((x)+((align)-1))&~((align)-1))
Definition at line 25 of file defs.h.
KSEG1
#define KSEG1 0xa0000000
Definition at line 29 of file defs.h.
KSEG1ADDR
#define KSEG1ADDR (a) ((__typeof__(a))(((u32)(a) & 0x1fffffff) | KSEG1))
Definition at line 30 of file defs.h.
NULL
#define NULL ((void *)0)
Definition at line 22 of file defs.h.
PHYSADDR
#define PHYSADDR (a) (((u32)(a)) & 0x1fffffff)
Definition at line 27 of file defs.h.
SetModuleGP
#define SetModuleGP () ChangeGP(&_gp)
Definition at line 54 of file defs.h.
Function Documentation
ChangeGP()
static __inline__ void* ChangeGP (void * gp) static
Definition at line 32 of file defs.h.
 {
         void *OldGP;
         __asm__ volatile(       "move %0, $gp\n"
                                 "move $gp, %1"
                                 : "=&r"(OldGP)
                                 : "r"(gp)
                                 : "gp", "memory");
         return OldGP;
 }
References gp.
Referenced by callUsbDriverFunc().
GetGP()
static __inline__ void* GetGP (void) static
Definition at line 56 of file defs.h.
 {
         void *gp;
         __asm__ volatile(       "move %0, $gp"
                                 : "=r"(gp)
                                 :
                                 : "memory");
         return gp;
 }
References gp.
Referenced by sceUsbdTransferPipe().
iop_memcpy()
static void* iop_memcpy (void * dest, const void * src, int size) inline static
Definition at line 68 of file defs.h.
 {
         u8 *d = (u8 *)dest, *s = (u8 *)src;
         while (size--)
                 *d++ = *s++;
         return dest;
 }
SetGP()
static __inline__ void SetGP (void * gp) static
Definition at line 45 of file defs.h.
 {
         __asm__ volatile(       "move $gp, %0"
                                 :
                                 : "r"(gp)
                                 : "gp", "memory");
 }
References gp.
Referenced by callbackThreadFunc(), callUsbDriverFunc(), Dev9IntrCb(), sceUsbdChangeThreadPriority(), sceUsbdClosePipe(), sceUsbdGetDeviceLocation(), sceUsbdGetPrivateData(), sceUsbdOpenPipe(), sceUsbdOpenPipeAligned(), sceUsbdRegisterAutoloader(), sceUsbdRegisterLdd(), sceUsbdScanStaticDescriptor(), sceUsbdSetPrivateData(), sceUsbdTransferPipe(), sceUsbdUnregisterAutoloader(), sceUsbdUnregisterLdd(), SMAPIoctl(), SMAPStart(), SMAPStop(), and SMAPXmit().
Variable Documentation
_gp
void* _gp extern
Referenced by callbackThreadFunc(), callUsbDriverFunc(), and initHubDriver().