ps2sdk: iop/network/smbman/src/des.h File Reference
des.h File Reference
Functions
unsigned char * DES (const unsigned char *key, const unsigned char *message, unsigned char *cipher)
Function Documentation
DES()
unsigned char* DES (const unsigned char * key, const unsigned char * message, unsigned char * cipher)
Definition at line 525 of file des.c.
 {
         unsigned int l, r, t, u;
         int i;
         unsigned int *s;
         unsigned char *keys;
         keys = DES_createkeys(key);
         c2l(message, l); /* get endian free int from input block */
         c2l(message, r); /* get endian free int from input block */
         /* do IP */
         PERM_OP(r,l,t, 4,0x0f0f0f0f);
         PERM_OP(l,r,t,16,0x0000ffff);
         PERM_OP(r,l,t, 2,0x33333333);
         PERM_OP(l,r,t, 8,0x00ff00ff);
         PERM_OP(r,l,t, 1,0x55555555);
         /* r and l are reversed - remember that :-) - fix
          * it in the next step */
         /* Things have been modified so that the initial rotate is
          * done outside the loop.  This required the
          * des_SPtrans values in sp.h to be rotated 1 bit to the right.
          * One perl script later and things have a 5% speed up on a sparc2.
          * Thanks to Richard Outerbridge <71755.204@CompuServe.COM>
          * for pointing this out. */
         t = (r << 1) | (r >> 31);
         r = (l << 1) | (l >> 31);
         l = t;
         s = (unsigned int *)keys;
         /* I don't know if it is worth the effort of loop unrolling the
          * inner loop */
         for (i=0; i<32; i+=4) {
                 D_ENCRYPT(l,r,i+0); /*  1 */
                 D_ENCRYPT(r,l,i+2); /*  2 */
         }
         l = (l >> 1) | (l << 31);
         r = (r >> 1) | (r << 31);
         /* swap l and r
          * we will not do the swap so just remember they are
          * reversed for the rest of the subroutine
          * luckily FP fixes this problem :-) */
         PERM_OP(r,l,t, 1,0x55555555);
         PERM_OP(l,r,t, 8,0x00ff00ff);
         PERM_OP(r,l,t, 2,0x33333333);
         PERM_OP(l,r,t,16,0x0000ffff);
         PERM_OP(r,l,t, 4,0x0f0f0f0f);
         l2c(l, cipher); /* get endian free int from input block */
         l2c(r, cipher); /* get endian free int from input block */
         return (unsigned char *)cipher;
 }
References c2l, D_ENCRYPT, DES_createkeys(), l2c, and PERM_OP.
Referenced by LM_Password_Hash(), and LM_Response().