ps2sdk: iop/network/smbman/src/des.c File Reference
des.c File Reference
Macros
#define c2l(c, l)
#define l2c(l, c)
#define ITERATIONS 16
#define HPERM_OP(a, t, n, m)
#define D_ENCRYPT(L, R, S)
#define PERM_OP(a, b, t, n, m)
Functions
static unsigned char * key7TOkey8 (const unsigned char *key7, unsigned char *key8)
static unsigned char * DES_createkeys (const unsigned char *key)
unsigned char * DES (const unsigned char *key, const unsigned char *message, unsigned char *cipher)
Variables
static const unsigned int des_SPtrans [8][64]
static const unsigned int des_skb [8][64]
static unsigned char DES_Keys [128]
Macro Definition Documentation
c2l
#define c2l (c, l)
Value:
                         (l =((unsigned int)(*((c)++))), \
                         l|=((unsigned int)(*((c)++)))<< 8, \
                         l|=((unsigned int)(*((c)++)))<<16, \
                         l|=((unsigned int)(*((c)++)))<<24)
Definition at line 52 of file des.c.
D_ENCRYPT
#define D_ENCRYPT (L, R, S)
Value:
        u=(R^s[S  ]); \
        t=R^s[S+1]; \
        t=((t>>4)+(t<<28)); \
        L^=     des_SPtrans[1][(t    )&0x3f]| \
                des_SPtrans[3][(t>> 8)&0x3f]| \
                des_SPtrans[5][(t>>16)&0x3f]| \
                des_SPtrans[7][(t>>24)&0x3f]| \
                des_SPtrans[0][(u    )&0x3f]| \
                des_SPtrans[2][(u>> 8)&0x3f]| \
                des_SPtrans[4][(u>>16)&0x3f]| \
                des_SPtrans[6][(u>>24)&0x3f];
Definition at line 380 of file des.c.
HPERM_OP
#define HPERM_OP (a, t, n, m)
Value:
        ((t)=((((a)<<(16-(n)))^(a))&(m)),\
        (a)=(a)^(t)^(t>>(16-(n))))
Definition at line 63 of file des.c.
ITERATIONS
#define ITERATIONS 16
Definition at line 62 of file des.c.
l2c
#define l2c (l, c)
Value:
                         (*((c)++)=(unsigned char)(((l)    )&0xff), \
                         *((c)++)=(unsigned char)(((l)>> 8)&0xff), \
                         *((c)++)=(unsigned char)(((l)>>16)&0xff), \
                         *((c)++)=(unsigned char)(((l)>>24)&0xff))
Definition at line 57 of file des.c.
PERM_OP
#define PERM_OP (a, b, t, n, m)
Value:
        ((t)=((((a)>>(n))^(b))&(m)),\
        (b)^=(t),\
        (a)^=((t)<<(n)))
Definition at line 430 of file des.c.
Function Documentation
DES()
unsigned char* DES (const unsigned char * key, const unsigned char * message, unsigned char * cipher)
Definition at line 525 of file des.c.
 {
         unsigned int l, r, t, u;
         int i;
         unsigned int *s;
         unsigned char *keys;
         keys = DES_createkeys(key);
         c2l(message, l); /* get endian free int from input block */
         c2l(message, r); /* get endian free int from input block */
         /* do IP */
         PERM_OP(r,l,t, 4,0x0f0f0f0f);
         PERM_OP(l,r,t,16,0x0000ffff);
         PERM_OP(r,l,t, 2,0x33333333);
         PERM_OP(l,r,t, 8,0x00ff00ff);
         PERM_OP(r,l,t, 1,0x55555555);
         /* r and l are reversed - remember that :-) - fix
          * it in the next step */
         /* Things have been modified so that the initial rotate is
          * done outside the loop.  This required the
          * des_SPtrans values in sp.h to be rotated 1 bit to the right.
          * One perl script later and things have a 5% speed up on a sparc2.
          * Thanks to Richard Outerbridge <71755.204@CompuServe.COM>
          * for pointing this out. */
         t = (r << 1) | (r >> 31);
         r = (l << 1) | (l >> 31);
         l = t;
         s = (unsigned int *)keys;
         /* I don't know if it is worth the effort of loop unrolling the
          * inner loop */
         for (i=0; i<32; i+=4) {
                 D_ENCRYPT(l,r,i+0); /*  1 */
                 D_ENCRYPT(r,l,i+2); /*  2 */
         }
         l = (l >> 1) | (l << 31);
         r = (r >> 1) | (r << 31);
         /* swap l and r
          * we will not do the swap so just remember they are
          * reversed for the rest of the subroutine
          * luckily FP fixes this problem :-) */
         PERM_OP(r,l,t, 1,0x55555555);
         PERM_OP(l,r,t, 8,0x00ff00ff);
         PERM_OP(r,l,t, 2,0x33333333);
         PERM_OP(l,r,t,16,0x0000ffff);
         PERM_OP(r,l,t, 4,0x0f0f0f0f);
         l2c(l, cipher); /* get endian free int from input block */
         l2c(r, cipher); /* get endian free int from input block */
         return (unsigned char *)cipher;
 }
References c2l, D_ENCRYPT, DES_createkeys(), l2c, and PERM_OP.
Referenced by LM_Password_Hash(), and LM_Response().
DES_createkeys()
static unsigned char* DES_createkeys (const unsigned char * key) static
Definition at line 461 of file des.c.
 {
         unsigned int c, d, t, s;
         unsigned char *in;
         unsigned int *k;
         unsigned char k8[8];
         int i;
         static unsigned char shifts[16] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0 };
         key7TOkey8(key, k8);
         k = (unsigned int *)DES_Keys;
         in = (unsigned char *)k8;
         c2l(in, c);
         c2l(in, d);
         /* I now do it in 47 simple operations :-)
          * Thanks to John Fletcher (john_fletcher@lccmail.ocf.llnl.gov)
          * for the inspiration. :-) */
         PERM_OP (d,c,t,4,0x0f0f0f0f);
         HPERM_OP(c,t,-2,0xcccc0000);
         HPERM_OP(d,t,-2,0xcccc0000);
         PERM_OP (d,c,t,1,0x55555555);
         PERM_OP (c,d,t,8,0x00ff00ff);
         PERM_OP (d,c,t,1,0x55555555);
         d =     (((d & 0x000000ff) << 16) |  (d & 0x0000ff00) |
                  ((d & 0x00ff0000) >> 16) | ((c & 0xf0000000) >> 4));
         c&=0x0fffffff;
         for (i=0; i<ITERATIONS; i++) {
                 if (shifts[i]) {
                         c = ((c >> 2)|(c << 26));
                         d = ((d >> 2)|(d << 26));
                 }
                 else {
                         c = ((c >> 1)|(c << 27));
                         d = ((d >> 1)|(d << 27));
                 }
                 c &= 0x0fffffff;
                 d &= 0x0fffffff;
                 /* could be a few less shifts but I am to lazy at this
                  * point in time to investigate */
                 s =     des_skb[0][ (c      ) & 0x3f                      ] |
                         des_skb[1][((c >>  6) & 0x03) | ((c >>  7) & 0x3c)] |
                         des_skb[2][((c >> 13) & 0x0f) | ((c >> 14) & 0x30)] |
                         des_skb[3][((c >> 20) & 0x01) | ((c >> 21) & 0x06)  | ((c >> 22) & 0x38)];
                 t =     des_skb[4][ (d      ) & 0x3f                      ] |
                         des_skb[5][((d >>  7) & 0x03) | ((d >>  8) & 0x3c)] |
                         des_skb[6][ (d >> 15) & 0x3f                      ] |
                         des_skb[7][((d >> 21) & 0x0f) | ((d >> 22) & 0x30)];
                 /* table contained 0213 4657 */
                 *(k++) = ((t << 16) | (s & 0x0000ffff)) & 0xffffffff;
                 s =      ((s >> 16) | (t & 0xffff0000));
                 s = (s << 4) | (s >> 28);
                 *(k++) = s & 0xffffffff;
         }
         return (unsigned char *)DES_Keys;
 }
References c2l, DES_Keys, des_skb, HPERM_OP, ITERATIONS, key7TOkey8(), and PERM_OP.
Referenced by DES().
key7TOkey8()
static unsigned char* key7TOkey8 (const unsigned char * key7, unsigned char * key8) static
Definition at line 435 of file des.c.
 {
         int i;
         key8[0] = ((key7[0] >> 1) & 0xff);
         key8[1] = ((((key7[0] & 0x01) << 6) | (((key7[1] & 0xff) >> 2) & 0xff)) & 0xff);
         key8[2] = ((((key7[1] & 0x03) << 5) | (((key7[2] & 0xff) >> 3) & 0xff)) & 0xff);
         key8[3] = ((((key7[2] & 0x07) << 4) | (((key7[3] & 0xff) >> 4) & 0xff)) & 0xff);
         key8[4] = ((((key7[3] & 0x0F) << 3) | (((key7[4] & 0xff) >> 5) & 0xff)) & 0xff);
         key8[5] = ((((key7[4] & 0x1F) << 2) | (((key7[5] & 0xff) >> 6) & 0xff)) & 0xff);
         key8[6] = ((((key7[5] & 0x3F) << 1) | (((key7[6] & 0xff) >> 7) & 0xff)) & 0xff);
         key8[7] = (key7[6] & 0x7F);
         for (i = 0; i < 8; i++) {
                 key8[i] = (key8[i] << 1);
         }
         return (unsigned char *)key8;
 }
Referenced by DES_createkeys().
Variable Documentation
DES_Keys
unsigned char DES_Keys[128] static
Definition at line 455 of file des.c.
Referenced by DES_createkeys().
des_skb
const unsigned int des_skb[8][64] static
Definition at line 219 of file des.c.
Referenced by DES_createkeys().
des_SPtrans
const unsigned int des_SPtrans[8][64] static
Definition at line 66 of file des.c.