ps2sdk: iop/dev9/dev9/include/dev9.h File Reference
dev9.h File Reference
#include <types.h>
#include <irx.h>
#include <hdd-ioctl.h>
Macros
#define dev9_IMPORTS_start DECLARE_IMPORT_TABLE(dev9, 1, 9)
#define dev9_IMPORTS_end END_IMPORT_TABLE
#define I_dev9RegisterIntrCb DECLARE_IMPORT(4, dev9RegisterIntrCb)
#define I_dev9DmaTransfer DECLARE_IMPORT(5, dev9DmaTransfer)
#define I_dev9Shutdown DECLARE_IMPORT(6, dev9Shutdown)
#define I_dev9IntrEnable DECLARE_IMPORT(7, dev9IntrEnable)
#define I_dev9IntrDisable DECLARE_IMPORT(8, dev9IntrDisable)
#define I_dev9GetEEPROM DECLARE_IMPORT(9, dev9GetEEPROM)
#define I_dev9LEDCtl DECLARE_IMPORT(10, dev9LEDCtl)
#define I_dev9RegisterShutdownCb DECLARE_IMPORT(11, dev9RegisterShutdownCb)
#define I_dev9RegisterPreDmaCb DECLARE_IMPORT(12, dev9RegisterPreDmaCb)
#define I_dev9RegisterPostDmaCb DECLARE_IMPORT(13, dev9RegisterPostDmaCb)
Typedefs
typedef int(* dev9_intr_cb_t) (int flag)
typedef void(* dev9_shutdown_cb_t) (void)
typedef void(* dev9_dma_cb_t) (int bcr, int dir)
Functions
void dev9RegisterIntrCb (int intr, dev9_intr_cb_t cb)
int dev9DmaTransfer (int ctrl, void *buf, int bcr, int dir)
void dev9Shutdown (void)
void dev9IntrEnable (int mask)
void dev9IntrDisable (int mask)
int dev9GetEEPROM (u16 *buf)
void dev9LEDCtl (int ctl)
int dev9RegisterShutdownCb (int idx, dev9_shutdown_cb_t cb)
void dev9RegisterPreDmaCb (int ctrl, dev9_dma_cb_t cb)
void dev9RegisterPostDmaCb (int ctrl, dev9_dma_cb_t cb)
Detailed Description
DEV9 Device Driver definitions and imports.
Definition in file dev9.h.
Macro Definition Documentation
dev9_IMPORTS_end
#define dev9_IMPORTS_end END_IMPORT_TABLE
Definition at line 47 of file dev9.h.
dev9_IMPORTS_start
#define dev9_IMPORTS_start DECLARE_IMPORT_TABLE(dev9, 1, 9)
Definition at line 46 of file dev9.h.
I_dev9DmaTransfer
#define I_dev9DmaTransfer DECLARE_IMPORT(5, dev9DmaTransfer)
Definition at line 50 of file dev9.h.
I_dev9GetEEPROM
#define I_dev9GetEEPROM DECLARE_IMPORT(9, dev9GetEEPROM)
Definition at line 54 of file dev9.h.
I_dev9IntrDisable
#define I_dev9IntrDisable DECLARE_IMPORT(8, dev9IntrDisable)
Definition at line 53 of file dev9.h.
I_dev9IntrEnable
#define I_dev9IntrEnable DECLARE_IMPORT(7, dev9IntrEnable)
Definition at line 52 of file dev9.h.
I_dev9LEDCtl
#define I_dev9LEDCtl DECLARE_IMPORT(10, dev9LEDCtl)
Definition at line 55 of file dev9.h.
I_dev9RegisterIntrCb
#define I_dev9RegisterIntrCb DECLARE_IMPORT(4, dev9RegisterIntrCb)
Definition at line 49 of file dev9.h.
I_dev9RegisterPostDmaCb
#define I_dev9RegisterPostDmaCb DECLARE_IMPORT(13, dev9RegisterPostDmaCb)
Definition at line 58 of file dev9.h.
I_dev9RegisterPreDmaCb
#define I_dev9RegisterPreDmaCb DECLARE_IMPORT(12, dev9RegisterPreDmaCb)
Definition at line 57 of file dev9.h.
I_dev9RegisterShutdownCb
#define I_dev9RegisterShutdownCb DECLARE_IMPORT(11, dev9RegisterShutdownCb)
Definition at line 56 of file dev9.h.
I_dev9Shutdown
#define I_dev9Shutdown DECLARE_IMPORT(6, dev9Shutdown)
Definition at line 51 of file dev9.h.
Typedef Documentation
dev9_dma_cb_t
typedef void(* dev9_dma_cb_t) (int bcr, int dir)
Definition at line 26 of file dev9.h.
dev9_intr_cb_t
typedef int(* dev9_intr_cb_t) (int flag)
Definition at line 24 of file dev9.h.
dev9_shutdown_cb_t
typedef void(* dev9_shutdown_cb_t) (void)
Definition at line 25 of file dev9.h.
Function Documentation
dev9DmaTransfer()
int dev9DmaTransfer (int ctrl, void * buf, int bcr, int dir)
Definition at line 394 of file ps2dev9.c.
 {
         USE_SPD_REGS;
         volatile iop_dmac_chan_t *dev9_chan = (iop_dmac_chan_t *)DEV9_DMAC_BASE;
         int res, dmactrl, OldState;
         if(device >= 2)
         {
                 if (dev9_predma_cbs[device] == NULL)    return -1;
                 if (dev9_postdma_cbs[device] == NULL)   return -1;
         }
         if ((res = WaitSema(dma_lock_sem)) < 0)
                 return res;
         switch (device)
         {
                 case 0:
                         dmactrl = 0;
                         break;
                 case 1:
                         dmactrl = 1;
                         break;
 #ifdef DEV9_PSX_SUPPORT
                 //Used for the PSX
                 case 2:
                         dmactrl = 0x10;
                         break;
                 case 3:
                         dmactrl = 0x20;
                         break;
 #endif
                 default:
                         dmactrl = 0;
         }
         SPD_REG16(SPD_R_DMA_CTRL) = (SPD_REG16(SPD_R_REV_1) < 17) ? (dmactrl & 0x03) | 0x04 : dmactrl | 0x06;
         if (dev9_predma_cbs[device])
                 dev9_predma_cbs[device](bcr, dir);
         dev9_chan->madr = (u32)buf;
         /* Older versions of DEV9 do not suspend interrupts. Not sure why this must be done though. */
         CpuSuspendIntr(&OldState);
         dev9_chan->bcr  = bcr;
         dev9_chan->chcr = DMAC_CHCR_30|DMAC_CHCR_TR|DMAC_CHCR_CO|(dir & DMAC_CHCR_DR);
         CpuResumeIntr(OldState);
         /* Wait for DMA to complete. Do not use a semaphore as thread switching hurts throughput greatly.  */
         while(dev9_chan->chcr & DMAC_CHCR_TR) {}
         if (dev9_postdma_cbs[device])
                 dev9_postdma_cbs[device](bcr, dir);
         SignalSema(dma_lock_sem);
         return 0;
 }
References iop_dmac_chan_t::bcr, iop_dmac_chan_t::chcr, CpuResumeIntr(), CpuSuspendIntr(), DEV9_DMAC_BASE, dev9_postdma_cbs, dev9_predma_cbs, dma_lock_sem, DMAC_CHCR_30, DMAC_CHCR_CO, DMAC_CHCR_DR, DMAC_CHCR_TR, iop_dmac_chan_t::madr, NULL, SignalSema(), SPD_R_DMA_CTRL, SPD_R_REV_1, SPD_REG16, USE_SPD_REGS, and WaitSema().
Referenced by ata_dma_complete(), and SmapDmaTransfer().
dev9GetEEPROM()
int dev9GetEEPROM (u16 * buf)
Definition at line 521 of file ps2dev9.c.
 {
         int i;
         if (!eeprom_data[0])
                 return -1;
         if (eeprom_data[0] < 0)
                 return -2;
         /* We only return the MAC address and checksum.  */
         for (i = 0; i < 4; i++)
                 buf[i] = eeprom_data[i+1];
         return 0;
 }
References eeprom_data.
Referenced by smap_init().
dev9IntrDisable()
void dev9IntrDisable (int mask)
Definition at line 383 of file ps2dev9.c.
 {
         USE_SPD_REGS;
         int flags;
         CpuSuspendIntr(&flags);
         SPD_REG16(SPD_R_INTR_MASK) = SPD_REG16(SPD_R_INTR_MASK) & ~mask;
         CpuResumeIntr(flags);
 }
References CpuResumeIntr(), CpuSuspendIntr(), SPD_R_INTR_MASK, SPD_REG16, and USE_SPD_REGS.
Referenced by ata_intr_cb(), dev9_init(), Dev9IntrCb(), IntrHandlerThread(), and smap_init().
dev9IntrEnable()
void dev9IntrEnable (int mask)
Definition at line 372 of file ps2dev9.c.
 {
         USE_SPD_REGS;
         int flags;
         CpuSuspendIntr(&flags);
         SPD_REG16(SPD_R_INTR_MASK) = SPD_REG16(SPD_R_INTR_MASK) | mask;
         CpuResumeIntr(flags);
 }
References CpuResumeIntr(), CpuSuspendIntr(), SPD_R_INTR_MASK, SPD_REG16, and USE_SPD_REGS.
Referenced by ata_dma_complete(), ata_io_finish(), ata_io_start(), and IntrHandlerThread().
dev9LEDCtl()
void dev9LEDCtl (int ctl)
Definition at line 538 of file ps2dev9.c.
 {
         USE_SPD_REGS;
         SPD_REG8(SPD_R_PIO_DATA) = (ctl == 0);
 }
References SPD_R_PIO_DATA, SPD_REG8, and USE_SPD_REGS.
Referenced by ata_io_finish(), ata_io_start(), and dev9_init().
dev9RegisterIntrCb()
void dev9RegisterIntrCb (int intr, dev9_intr_cb_t cb)
Definition at line 247 of file ps2dev9.c.
 {
         dev9_intr_cbs[intr] = cb;
 }
References dev9_intr_cbs.
Referenced by _start(), and smap_init().
dev9RegisterPostDmaCb()
void dev9RegisterPostDmaCb (int ctrl, dev9_dma_cb_t cb)
Definition at line 258 of file ps2dev9.c.
{
         dev9_postdma_cbs[ctrl] = cb;
 }
References dev9_postdma_cbs.
Referenced by _start(), and smap_init().
dev9RegisterPreDmaCb()
void dev9RegisterPreDmaCb (int ctrl, dev9_dma_cb_t cb)
Definition at line 253 of file ps2dev9.c.
{
         dev9_predma_cbs[ctrl] = cb;
 }
References dev9_predma_cbs.
Referenced by _start(), and smap_init().
dev9RegisterShutdownCb()
int dev9RegisterShutdownCb (int idx, dev9_shutdown_cb_t cb)
Definition at line 550 of file ps2dev9.c.
 {
         if (idx < 16)
         {
                 dev9_shutdown_cbs[idx] = cb;
                 return 0;
         }
         return -1;
 }
References dev9_shutdown_cbs.
Referenced by _start(), and hddInitError().
dev9Shutdown()
void dev9Shutdown (void)
Definition at line 337 of file ps2dev9.c.
 {
         int idx;
         USE_DEV9_REGS;
         for (idx = 0; idx < 16; idx++)
                 if (dev9_shutdown_cbs[idx])
                         dev9_shutdown_cbs[idx]();
         if (dev9type == DEV9_TYPE_PCMCIA) {     /* PCMCIA */
                 DEV9_REG(DEV9_R_POWER) = 0;
                 DEV9_REG(DEV9_R_1474) = 0;
         } else if (dev9type == DEV9_TYPE_EXPBAY) {
                 DEV9_REG(DEV9_R_1466) = 1;
                 DEV9_REG(DEV9_R_1464) = 0;
                 DEV9_REG(DEV9_R_1460) = DEV9_REG(DEV9_R_1464);
                 DEV9_REG(DEV9_R_POWER) = DEV9_REG(DEV9_R_POWER) & ~4;
                 DEV9_REG(DEV9_R_POWER) = DEV9_REG(DEV9_R_POWER) & ~1;
         }
         DelayThread(1000000);
 }
References DelayThread(), DEV9_R_1460, DEV9_R_1464, DEV9_R_1466, DEV9_R_1474, DEV9_R_POWER, DEV9_REG, dev9_shutdown_cbs, DEV9_TYPE_EXPBAY, DEV9_TYPE_PCMCIA, dev9type, and USE_DEV9_REGS.
Referenced by dev9x_devctl(), hddDevctl(), and speed_device_init().