ps2sdk: iop/fs/devfs/src/devfs.c File Reference
devfs.c File Reference
#include "types.h"
#include "defs.h"
#include "irx.h"
#include "loadcore.h"
#include "thbase.h"
#include "thevent.h"
#include "thsemap.h"
#include "intrman.h"
#include "stdio.h"
#include "sysclib.h"
#include "devfs.h"
#include "sysmem.h"
#include "iomanX.h"
Data Structures
struct subdev_t
struct devfs_device_t
struct ioman_data_t
struct directory_file_t
Macros
#define MODNAME "devfs"
#define M_PRINTF(format, args...) printf(MODNAME ": " format, ## args)
#define BANNER "DEVFS %s\n"
#define VERSION "v0.1"
#define MAX_OPENFILES 32
#define MAX_OPEN_DIRFILES 16
Typedefs
typedef int(* dummy_func) (void)
Functions
IRX_ID (MODNAME, 1, 1)
const char * devfs_subdev_to_str (int subdev)
int devfs_fill_dirent (iox_dirent_t *dirent, int devno)
devfs_device_t * devfs_create_device (const devfs_node_t *node)
int devfs_delete_device (devfs_device_t *dev)
devfs_device_t * devfs_find_devicename (const char *name)
devfs_device_t * devfs_find_deviceid (HDEV hDev)
int devfs_dummy (void)
int devfs_init (iop_device_t *dev)
int devfs_deinit (iop_device_t *dev)
int devfs_open (iop_file_t *file, const char *name, int mode, int unused)
int devfs_close (iop_file_t *file)
int devfs_ioctl (iop_file_t *file, int cmd, void *args)
int devfs_ioctl2 (iop_file_t *file, int cmd, void *args, unsigned int arglen, void *buf, unsigned int buflen)
int devfs_read (iop_file_t *file, void *buf, int len)
int devfs_write (iop_file_t *file, void *buf, int len)
int devfs_lseek (iop_file_t *file, long loc, int whence)
int devfs_lseek64 (iop_file_t *file, long long loc, int whence)
int devfs_dopen (iop_file_t *file, const char *name)
int devfs_dclose (iop_file_t *file)
int devfs_dread (iop_file_t *file, iox_dirent_t *buf)
int devfs_getstat (iop_file_t *file, const char *name, iox_stat_t *stat)
int init_devfs (void)
int _start (int argc, char **argv)
int devfs_check_devname (const char *name)
HDEV DevFSAddDevice (const devfs_node_t *node)
int DevFSDelDevice (HDEV hDev)
int DevFSAddSubDevice (HDEV hDev, u32 subdev_no, s32 mode, devfs_loc_t extent, void *data)
int DevFSDelSubDevice (HDEV hDev, u32 subdev_no)
Variables
struct irx_export_table _exp_devfs
iop_device_t devfs_device
iop_device_ops_t devfs_ops
devfs_device_t * root_device
HDEV dev_count
directory_file_t open_dirfiles [MAX_OPEN_DIRFILES]
Detailed Description
DevFS source file
Definition in file devfs.c.
Macro Definition Documentation
BANNER
#define BANNER "DEVFS %s\n"
Definition at line 41 of file devfs.c.
M_PRINTF
#define M_PRINTF (format, args...) printf(MODNAME ": " format, ## args)
Definition at line 39 of file devfs.c.
MAX_OPEN_DIRFILES
#define MAX_OPEN_DIRFILES 16
Definition at line 44 of file devfs.c.
MAX_OPENFILES
#define MAX_OPENFILES 32
Definition at line 43 of file devfs.c.
MODNAME
#define MODNAME "devfs"
Definition at line 36 of file devfs.c.
VERSION
#define VERSION "v0.1"
Definition at line 42 of file devfs.c.
Typedef Documentation
dummy_func
typedef int(* dummy_func) (void)
Definition at line 50 of file devfs.c.
Function Documentation
_start()
int _start (int argc, char ** argv)
Main start function of the module
Parameters
argc Unused
argv Unused
Returns
0 on success, -1 on error
Definition at line 1056 of file devfs.c.
 {
    int res = 1;
    printf(BANNER, VERSION);
    if ((res = RegisterLibraryEntries(&_exp_devfs)) != 0) {
       M_PRINTF("Library is already registered, exiting.\n");
       printf("res=%d\n", res);
    }
    else
    {
       res = init_devfs();
    }
    M_PRINTF("devfs_device_t size=%d\n", sizeof(devfs_device_t));
    M_PRINTF("Driver loaded.\n");
    return res;
 }
References _exp_devfs, BANNER, init_devfs(), M_PRINTF, printf(), RegisterLibraryEntries(), and VERSION.
devfs_check_devname()
int devfs_check_devname (const char * name)
Function to check a device name only contains alphabetic characters
Parameters
name The name to check.
Returns
0 if the name is invalid, else 1
Definition at line 1081 of file devfs.c.
 {
    int str_loop;
    if((name == NULL) || (name[0] == 0))
    {
       return 0;
    }
    if(strlen(name) > DEVFS_MAX_DEVNAME_LENGTH)
    {
       return 0;
    }
    str_loop = 0;
    while(name[str_loop])
    {
       char ch;
       ch = name[str_loop];
       if(((ch >= 'a') && (ch <= 'z')) || ((ch >= 'A') && (ch <= 'Z')))
       {
          str_loop++;
       }
       else
       {
          return 0;
       }
    }
    return 1;
 }
References DEVFS_MAX_DEVNAME_LENGTH, NULL, and strlen().
Referenced by DevFSAddDevice().
devfs_close()
int devfs_close (iop_file_t * file)
ioman close handler
Parameters
file Pointer to an ioman file structure
Returns
0 on success, else -1
Definition at line 500 of file devfs.c.
 {
    devfs_device_t *dev;
    ioman_data_t *data = (ioman_data_t *) file->privdata;
    int loop;
    if((data) && (data->hDev != INVALID_HDEV)) /* Invalid HDEV is a dir listing */
    {
       dev = data->dev;
       if(dev != NULL)
       {
          if(dev->subdevs[data->subdev].open_refcount > 0)
          {
              dev->subdevs[data->subdev].open_refcount--;
          }
          if(dev->open_refcount > 0)
          {
             dev->open_refcount--;
          }
          loop = 0;
          while((loop < MAX_OPENFILES)
                && (dev->subdevs[data->subdev].open_files[loop] != data))
          {
             loop++;
          }
          if(loop != MAX_OPENFILES)
          {
             dev->subdevs[data->subdev].open_files[loop] = NULL;
          }
          else
          {
             M_PRINTF("close: Could not find opened file\n");
          }
          M_PRINTF("close: Closing device %s subdev %d\n", dev->node.name, data->subdev);
          FreeSysMemory(data);
       }
       else
       {
          FreeSysMemory(data);
          file->privdata = NULL;
          return -1;
       }
    }
    else
    {
       return -1;
    }
    return 0;
 }
References ioman_data_t::dev, FreeSysMemory(), ioman_data_t::hDev, INVALID_HDEV, M_PRINTF, MAX_OPENFILES, devfs_node_t::name, devfs_device_t::node, NULL, subdev_t::open_files, subdev_t::open_refcount, devfs_device_t::open_refcount, iop_file_t::privdata, ioman_data_t::subdev, and devfs_device_t::subdevs.
Referenced by init_devfs().
devfs_create_device()
devfs_device_t* devfs_create_device (const devfs_node_t * node)
Creates a new device based on the node data supplied
Parameters
node Pointer to a devfs_node_t structure
Returns
A new device structure or NULL on error.
Definition at line 201 of file devfs.c.
 {
    devfs_device_t *dev;
    if((node == NULL) || (node->name == NULL))
    {
       return NULL;
    }
    dev = AllocSysMemory(ALLOC_FIRST, sizeof(devfs_device_t), NULL);
    if(dev == NULL)
    {
       printf("create_device: Alloc Failed\n");
       return NULL;
    }
    memset(dev, 0, sizeof(devfs_device_t));
    memcpy(&dev->node, node, sizeof(devfs_node_t));
    if(dev->node.name != NULL)
    {
       dev->node.name = AllocSysMemory(ALLOC_FIRST, strlen(node->name) + 1, NULL);
       if(dev->node.name == NULL)
       {
          FreeSysMemory(dev);
          return NULL;
       }
       memcpy(dev->node.name, node->name, strlen(node->name) + 1);
    }
    if(dev->node.desc != NULL)
    {
       dev->node.desc = AllocSysMemory(ALLOC_FIRST, strlen(node->desc) + 1, NULL);
       if(dev->node.name == NULL)
       {
          FreeSysMemory(dev->node.name);
          FreeSysMemory(dev);
          return NULL;
       }
       memcpy(dev->node.desc, node->desc, strlen(node->desc) + 1);
    }
    return dev;
 }
References ALLOC_FIRST, AllocSysMemory(), devfs_node_t::desc, FreeSysMemory(), memcpy(), memset(), devfs_node_t::name, devfs_device_t::node, NULL, printf(), and strlen().
Referenced by DevFSAddDevice().
devfs_dclose()
int devfs_dclose (iop_file_t * file)
ioman dclose handler
Parameters
file Pointer to an ioman file structure
Returns
Always returns 0
Definition at line 882 of file devfs.c.
 {
    directory_file_t *dir;
    //M_PRINTF("dclose: file=%p\n", file);
    dir = (directory_file_t *) file->privdata;
    if((dir) && (dir->hDev == INVALID_HDEV))
    {
       dir->opened = 0;
       file->privdata = NULL;
    }
    return 0;
 }
References directory_file_t::hDev, INVALID_HDEV, NULL, directory_file_t::opened, and iop_file_t::privdata.
Referenced by init_devfs().
devfs_deinit()
int devfs_deinit (iop_device_t * dev)
ioman deinit handler
Returns
Always returns 0
Definition at line 354 of file devfs.c.
 {
    printf("devfs_deinit dev=%p\n", dev);
    return 0;
 }
References printf().
Referenced by init_devfs().
devfs_delete_device()
int devfs_delete_device (devfs_device_t * dev)
Deletes a device
Parameters
dev Pointer to a previously allocated device structure
Returns
Always 0
Definition at line 251 of file devfs.c.
 {
   if(dev != NULL)
   {
      if(dev->node.name)
      {
         FreeSysMemory(dev->node.name);
      }
      if(dev->node.desc)
      {
         FreeSysMemory(dev->node.desc);
      }
      FreeSysMemory(dev);
   }
   return 0;
 }
References devfs_node_t::desc, FreeSysMemory(), devfs_node_t::name, devfs_device_t::node, and NULL.
Referenced by DevFSDelDevice().
devfs_dopen()
int devfs_dopen (iop_file_t * file, const char * name)
ioman dopen handler
Parameters
file Pointer to an ioman file structure
name Name of directory to open
Returns
0 if success, -1 on error
Definition at line 853 of file devfs.c.
 {
    int dir_loop;
    if((name == NULL) && (name[0] != '\\') && (name[0] != '/'))
    {
       M_PRINTF("dopen: Not a valid directory name\n");
       return -1;
    }
    //M_PRINTF("dopen: file=%p name=%s\n", file, name);
    for(dir_loop = 0; dir_loop < MAX_OPEN_DIRFILES; dir_loop++)
    {
       if(!open_dirfiles[dir_loop].opened)
       {
          open_dirfiles[dir_loop].devno = 0;
          open_dirfiles[dir_loop].hDev = INVALID_HDEV;
          file->privdata = &open_dirfiles[dir_loop];
          return 0;
       }
    }
    return -1;
 }
References directory_file_t::devno, directory_file_t::hDev, INVALID_HDEV, M_PRINTF, MAX_OPEN_DIRFILES, NULL, open_dirfiles, and iop_file_t::privdata.
Referenced by init_devfs().
devfs_dread()
int devfs_dread (iop_file_t * file, iox_dirent_t * buf)
Definition at line 901 of file devfs.c.
 {
    directory_file_t *dir;
    int ret = 0;
    //M_PRINTF("dread: file=%p buf=%p\n", file, buf);
    dir = (directory_file_t *) file->privdata;
    if((dir) && (dir->hDev == INVALID_HDEV) && (buf))
    {
       ret = devfs_fill_dirent(buf, dir->devno);
       if(ret)
       {
          dir->devno++;
       }
    }
    return ret;
 }
References devfs_fill_dirent(), directory_file_t::devno, directory_file_t::hDev, INVALID_HDEV, and iop_file_t::privdata.
Referenced by init_devfs().
devfs_dummy()
int devfs_dummy (void)
Dummy ioman handler
Returns
Always returns -1
Definition at line 334 of file devfs.c.
 {
    printf("devfs_dummy\n");
    return -1;
 }
References printf().
Referenced by init_devfs().
devfs_fill_dirent()
int devfs_fill_dirent (iox_dirent_t * dirent, int devno)
Scans the device list and fills in the corresponding directory entry
Parameters
dirent Pointer to a iox_dirent_t structure.
devno The sequential device number to read
Returns
Always 0
Definition at line 140 of file devfs.c.
 {
    devfs_device_t *dev_scan;
    int curr_no = 0;
    u32 subdev_loop;
    dev_scan = root_device;
    while(dev_scan != NULL)
    {
      if((curr_no + dev_scan->subdev_count) > devno)
      {
         for(subdev_loop = 0; subdev_loop < DEVFS_MAX_SUBDEVS; subdev_loop++)
         {
            if(dev_scan->subdevs[subdev_loop].valid)
            {
               if(curr_no == devno)
               {
                  break;
               }
               curr_no++;
            }
         }
         if(subdev_loop < DEVFS_MAX_SUBDEVS)
         {
            memset(dirent, 0, sizeof(iox_dirent_t));
            dirent->stat.size = dev_scan->subdevs[subdev_loop].extent.loc32[0];
            dirent->stat.hisize = dev_scan->subdevs[subdev_loop].extent.loc32[1];
            dirent->stat.mode = FIO_S_IFREG;
            if(dev_scan->subdevs[subdev_loop].mode & DEVFS_MODE_R)
            {
               dirent->stat.mode |= FIO_S_IRUSR;
            }
            if(dev_scan->subdevs[subdev_loop].mode & DEVFS_MODE_W)
            {
               dirent->stat.mode |= FIO_S_IWUSR;
            }
            dirent->name[0] = 0;
            strcpy(dirent->name, dev_scan->node.name);
            strcat(dirent->name, devfs_subdev_to_str(subdev_loop));
            return strlen(dirent->name);
         }
      }
      curr_no += dev_scan->subdev_count;
      dev_scan = dev_scan->forw;
    }
    return 0;
 }
References DEVFS_MAX_SUBDEVS, DEVFS_MODE_R, DEVFS_MODE_W, devfs_subdev_to_str(), subdev_t::extent, FIO_S_IFREG, FIO_S_IRUSR, FIO_S_IWUSR, devfs_device_t::forw, iox_stat_t::hisize, devfs_loc_t::loc32, memset(), iox_stat_t::mode, subdev_t::mode, iox_dirent_t::name, devfs_node_t::name, devfs_device_t::node, NULL, root_device, iox_stat_t::size, iox_dirent_t::stat, strcat(), strcpy(), strlen(), devfs_device_t::subdev_count, devfs_device_t::subdevs, and subdev_t::valid.
Referenced by devfs_dread().
devfs_find_deviceid()
devfs_device_t* devfs_find_deviceid (HDEV hDev)
Finds a device from its device handle.
Parameters
hDev Handle to the device.
Returns
A pointer to the device, if not found returns NULL
Definition at line 312 of file devfs.c.
 {
    devfs_device_t *dev_scan;
    dev_scan = root_device;
    while(dev_scan != NULL)
    {
      if(dev_scan->hDev == hDev)
      {
         return dev_scan;
      }
      dev_scan = dev_scan->forw;
    }
    return NULL;
 }
References devfs_device_t::forw, devfs_device_t::hDev, NULL, and root_device.
Referenced by DevFSAddSubDevice(), DevFSDelDevice(), and DevFSDelSubDevice().
devfs_find_devicename()
devfs_device_t* devfs_find_devicename (const char * name)
Trys to find a device with a matching name.
The name can be a full device name with subdev on the end, the function should still find the device.
Parameters
name The name of the device to find
Returns
A pointer to the device, if not found returns NULL
Definition at line 279 of file devfs.c.
 {
    devfs_device_t *dev_scan;
    if(name == NULL)
    {
       return NULL;
    }
    dev_scan = root_device;
    while(dev_scan != NULL)
    {
      /* Ensure name is at least less than or equal to the one we want to find */
      if(strlen(dev_scan->node.name) <= strlen(name))
      {
         if(strncmp(dev_scan->node.name, name, strlen(dev_scan->node.name)) == 0)
         {
            return dev_scan;
         }
      }
      dev_scan = dev_scan->forw;
    }
    return NULL;
 }
References devfs_device_t::forw, devfs_node_t::name, devfs_device_t::node, NULL, root_device, strlen(), and strncmp().
Referenced by devfs_getstat(), devfs_open(), and DevFSAddDevice().
devfs_getstat()
int devfs_getstat (iop_file_t * file, const char * name, iox_stat_t * stat)
ioman getstat handler
Parameters
file Pointer to an ioman file structure
name Name of the file to stat
stat Buffer to receive the stat
Returns
0 on success, -1 on error
Definition at line 930 of file devfs.c.
 {
    devfs_device_t *dev;
    int fn_offset = 0;
    if(name == NULL)
    {
       return -1;
    }
    if((name[0] == '\\') || (name[0] == '/'))
    {
       fn_offset = 1;
    }
    if(stat == NULL)
    {
       return -1;
    }
    dev = devfs_find_devicename(name + fn_offset);
    if(dev != NULL)
    {
       char *endp;
       int subdev;
       int name_len;
       name_len = strlen(dev->node.name);
       if(name_len == strlen(name)) /* If this is has not got a subnumber */
       {
         M_PRINTF("getstat: No subdevice number in filename %s\n", name);
         return -1;
       }
       subdev = strtoul(&name[name_len + fn_offset], &endp, 10);
       if(((subdev == 0) && (name[name_len + fn_offset] != '0'))
         || (subdev >= DEVFS_MAX_SUBDEVS))
          /* Invalid number */
       {
          M_PRINTF("getstat: Invalid subdev number %d\n", subdev);
          return -1;
       }
       if(*endp)
       /* Extra charactes after filename */
       {
          M_PRINTF("getstat: Invalid filename\n");
          return -1;
       }
       if(!dev->subdevs[subdev].valid)
       {
         M_PRINTF("getstat: No subdev registered\n");
         return -1;
       }
 #ifdef USE_IOMAN
       memset(stat, 0, sizeof(fio_stat_t));
 #else
       memset(stat, 0, sizeof(iox_stat_t));
 #endif
       stat->size = dev->subdevs[subdev].extent.loc32[0];
       stat->hisize = dev->subdevs[subdev].extent.loc32[1];
       stat->mode = FIO_S_IFREG;
       if(dev->subdevs[subdev].mode & DEVFS_MODE_R)
       {
          stat->mode |= FIO_S_IRUSR;
       }
       if(dev->subdevs[subdev].mode & DEVFS_MODE_W)
       {
          stat->mode |= FIO_S_IWUSR;
       }
    }
    return 0;
 }
References devfs_find_devicename(), DEVFS_MAX_SUBDEVS, DEVFS_MODE_R, DEVFS_MODE_W, subdev_t::extent, FIO_S_IFREG, FIO_S_IRUSR, FIO_S_IWUSR, iox_stat_t::hisize, devfs_loc_t::loc32, M_PRINTF, memset(), iox_stat_t::mode, subdev_t::mode, devfs_node_t::name, devfs_device_t::node, NULL, iox_stat_t::size, strlen(), strtoul(), devfs_device_t::subdevs, and subdev_t::valid.
Referenced by init_devfs().
devfs_init()
int devfs_init (iop_device_t * dev)
ioman init handler
Returns
Always returns 0
Definition at line 344 of file devfs.c.
 {
    printf("devfs_init dev=%p\n", dev);
    return 0;
 }
References printf().
Referenced by init_devfs().
devfs_ioctl()
int devfs_ioctl (iop_file_t * file, int cmd, void * args)
ioman ioctl handler
Parameters
file Pointer to an ioman file structure
cmd ioctl command number
args Pointer to a buffer containing any arguments
Returns
>= 0 Defined by the type of command, -1 on error
Definition at line 562 of file devfs.c.
 {
    devfs_device_t *dev;
    ioman_data_t *data = (ioman_data_t *) file->privdata;
    if(cmd == DEVFS_IOCTL_GETDESC)
    {
       return -1; /* ioctl cannot support this call */
    }
    data = file->privdata;
    if((data) && (data->hDev != INVALID_HDEV))
    {
       dev = data->dev;
       if(dev == NULL) /* Device has been closed from under us */
       {
          /* Delete data to try and prevent a memory leak */
          FreeSysMemory(data);
          file->privdata = NULL;
          return -1;
       }
       if(dev->node.ioctl != NULL)
       {
          devfs_info_t dev_info;
          dev_info.data = dev->subdevs[data->subdev].data;
          dev_info.subdev = data->subdev;
          dev_info.mode = data->mode;
          dev_info.loc = data->loc;
          return dev->node.ioctl(&dev_info, DEVFS_IOCTL_TYPE_1, cmd, args, 0, NULL, 0);
       }
    }
    return -1;
 }
References devfs_info_t::data, subdev_t::data, ioman_data_t::dev, DEVFS_IOCTL_GETDESC, DEVFS_IOCTL_TYPE_1, FreeSysMemory(), ioman_data_t::hDev, INVALID_HDEV, devfs_node_t::ioctl, devfs_info_t::loc, ioman_data_t::loc, devfs_info_t::mode, ioman_data_t::mode, devfs_device_t::node, NULL, iop_file_t::privdata, devfs_info_t::subdev, ioman_data_t::subdev, and devfs_device_t::subdevs.
Referenced by init_devfs().
devfs_ioctl2()
int devfs_ioctl2 (iop_file_t * file, int cmd, void * args, unsigned int arglen, void * buf, unsigned int buflen)
ioman ioctl2 handler
Parameters
file Pointer to an ioman file structure
cmd ioctl command number
args Pointer a buffer containing command arguments
arglen Length of args buffer
buf Pointer to a return buffer
buflen Length of buf
Returns
>= 0 Depends on command, -1 on error
Definition at line 610 of file devfs.c.
 {
    devfs_device_t *dev;
    ioman_data_t *data = (ioman_data_t *) file->privdata;
    data = file->privdata;
    if((data) && (data->hDev != INVALID_HDEV))
    {
       dev = data->dev;
       if(dev == NULL) /* Device has been closed from under us */
       {
          /* Delete data to try and prevent a memory leak */
          FreeSysMemory(data);
          file->privdata = NULL;
          return -1;
       }
       if((cmd == DEVFS_IOCTL_GETDESC) && (buf) && (buflen >= DEVFS_MAX_DESC_LENGTH))
       {
          if(dev->node.desc)
          {
             strncpy(buf, dev->node.desc, buflen-1);
             *((u8 *) (buf + buflen)) = 0;
             return strlen(buf);
          }
          return 0;
       }
       if(dev->node.ioctl != NULL)
       {
          devfs_info_t dev_info;
          dev_info.data = dev->subdevs[data->subdev].data;
          dev_info.subdev = data->subdev;
          dev_info.mode = data->mode;
          dev_info.loc = data->loc;
          return dev->node.ioctl(&dev_info, DEVFS_IOCTL_TYPE_2, cmd, args, arglen, buf, buflen);
       }
    }
    return -1;
 }
References devfs_info_t::data, subdev_t::data, devfs_node_t::desc, ioman_data_t::dev, DEVFS_IOCTL_GETDESC, DEVFS_IOCTL_TYPE_2, DEVFS_MAX_DESC_LENGTH, FreeSysMemory(), ioman_data_t::hDev, INVALID_HDEV, devfs_node_t::ioctl, devfs_info_t::loc, ioman_data_t::loc, devfs_info_t::mode, ioman_data_t::mode, devfs_device_t::node, NULL, iop_file_t::privdata, strlen(), strncpy(), devfs_info_t::subdev, ioman_data_t::subdev, and devfs_device_t::subdevs.
Referenced by init_devfs().
devfs_lseek()
int devfs_lseek (iop_file_t * file, long loc, int whence)
ioman lseek handler
Parameters
file Pointer to a ioman file structure
loc Location to seek to
whence Seek base.
Returns
location seeked to, -1 on error.
Definition at line 757 of file devfs.c.
 {
    devfs_device_t *dev;
    ioman_data_t *data = (ioman_data_t *) file->privdata;
    //printf("devfs_lseek file=%p loc=%ld whence=%d\n", file, loc, whence);
    data = file->privdata;
    if((data) && (data->hDev != INVALID_HDEV))
    {
       dev = data->dev;
       if(dev == NULL) /* Device has been closed from under us */
       {
          /* Delete data to try and prevent a memory leak */
          FreeSysMemory(data);
          file->privdata = NULL;
          return -1;
       }
       switch(whence)
       {
         case SEEK_SET: if(loc > 0)
                          data->loc.loc64 = (u64) loc;
                        break;
         case SEEK_CUR: if(loc > 0)
                          data->loc.loc64 += (u64) loc;
                        else if(((s64) -loc) < data->loc.loc64)
                          data->loc.loc64 += (s64) loc;
                        break;
         case SEEK_END: if((loc > 0)
                        && (dev->subdevs[data->subdev].extent.loc64 >= (u64) loc))
                          data->loc.loc64 = dev->subdevs[data->subdev].extent.loc64 - (u64) loc;
                        break;
         default:       return -1;
       }
    }
    else
    {
       return -1;
    }
    return data->loc.loc32[0];
 }
References ioman_data_t::dev, subdev_t::extent, FreeSysMemory(), ioman_data_t::hDev, INVALID_HDEV, ioman_data_t::loc, devfs_loc_t::loc32, devfs_loc_t::loc64, NULL, iop_file_t::privdata, SEEK_CUR, SEEK_END, SEEK_SET, ioman_data_t::subdev, and devfs_device_t::subdevs.
devfs_lseek64()
int devfs_lseek64 (iop_file_t * file, long long loc, int whence)
ioman lseek64 handler
Parameters
file Pointer to an ioman file structure
loc 64bit seek location
whence Seek base
Definition at line 805 of file devfs.c.
 {
    devfs_device_t *dev;
    ioman_data_t *data = (ioman_data_t *) file->privdata;
    //printf("devfs_lseek64 file=%p loc= whence=%d\n", file, whence);
    data = file->privdata;
    if((data) && (data->hDev != INVALID_HDEV))
    {
       dev = data->dev;
       if(dev == NULL) /* Device has been closed from under us */
       {
          /* Delete data to try and prevent a memory leak */
          FreeSysMemory(data);
          file->privdata = NULL;
          return -1;
       }
       switch(whence)
       {
         case SEEK_SET: if(loc > 0)
                          data->loc.loc64 = (u64) loc;
                        break;
         case SEEK_CUR: if(loc > 0)
                          data->loc.loc64 += (u64) loc;
                        else if(((s64) -loc) < data->loc.loc64)
                          data->loc.loc64 += (s64) loc;
                        break;
         case SEEK_END: if((loc > 0)                                                                                  && (dev->subdevs[data->subdev].extent.loc64 >= (u64) loc))
                          data->loc.loc64 = dev->subdevs[data->subdev].extent.loc64 - (u64) loc;
                        break;
         default:       return -1;
       }
    }
    else
    {
       return -1;
    }
    return data->loc.loc32[0];
 }
References ioman_data_t::dev, subdev_t::extent, FreeSysMemory(), ioman_data_t::hDev, INVALID_HDEV, ioman_data_t::loc, devfs_loc_t::loc32, devfs_loc_t::loc64, NULL, iop_file_t::privdata, SEEK_CUR, SEEK_END, SEEK_SET, ioman_data_t::subdev, and devfs_device_t::subdevs.
devfs_open()
int devfs_open (iop_file_t * file, const char * name, int mode, int unused)
ioman open handler @oaram file: Pointer to the ioman file structure
Parameters
name Name of file to open
mode Open file mode settings
Returns
0 if success, -1 on error
Definition at line 370 of file devfs.c.
 {
    devfs_device_t *dev;
    int loop;
    int fn_offset = 0;
    //printf("devfs_open file=%p name=%s mode=%d\n", file, name, mode);
    if(name == NULL)
    {
       M_PRINTF("open: Name is NULL\n");
       return -1;
    }
    if((name[0] == '\\') || (name[0] == '/'))
    {
       fn_offset = 1;
    }
    dev = devfs_find_devicename(name + fn_offset);
    if(dev != NULL)
    {
       char *endp;
       int subdev;
       int name_len;
       name_len = strlen(dev->node.name);
       if(name_len == strlen(name)) /* If this is has not got a subnumber */
       {
         M_PRINTF("open: No subdevice number in filename %s\n", name);
         return -1;
       }
       subdev = strtoul(&name[name_len + fn_offset], &endp, 10);
       if(((subdev == 0) && (name[name_len + fn_offset] != '0'))
         || (subdev >= DEVFS_MAX_SUBDEVS))
          /* Invalid number */
       {
          M_PRINTF("open: Invalid subdev number %d\n", subdev);
          return -1;
       }
       if(*endp)
       /* Extra charactes after filename */
       {
          M_PRINTF("open: Invalid filename\n");
          return -1;
       }
       if(!dev->subdevs[subdev].valid)
       /* No subdev */
       {
         M_PRINTF("open: No subdev registered\n");
         return -1;
       }
       if((dev->subdevs[subdev].mode & DEVFS_MODE_EX)
         && (dev->subdevs[subdev].open_refcount > 0))
       /* Already opened in exclusive mode */
       {
          M_PRINTF("open: Exclusive subdevice already opened\n");
          return -1;
       }
       if(dev->subdevs[subdev].open_refcount == MAX_OPENFILES)
       {
          M_PRINTF("open: Reached open file limit for sub device\n");
       }
       /* Tried to open read but not allowed */
       if(((mode & O_RDONLY) || ((mode & O_RDWR) == O_RDWR))
         && !(dev->subdevs[subdev].mode & DEVFS_MODE_R))
       {
          M_PRINTF("open: Read mode requested but not permitted\n");
          return -1;
       }
       if(((mode & O_WRONLY) || ((mode & O_RDWR) == O_RDWR))
         && !(dev->subdevs[subdev].mode & DEVFS_MODE_W))
       {
          M_PRINTF("open: Write mode requested but not permitted\n");
          return -1;
       }
       file->privdata = AllocSysMemory(ALLOC_FIRST, sizeof(ioman_data_t), NULL);
       if(file->privdata == NULL)
       {
          M_PRINTF("open: Allocation failure\n");
          return -1;
       }
       ((ioman_data_t *) file->privdata)->hDev = dev->hDev;
       ((ioman_data_t *) file->privdata)->subdev = subdev;
       ((ioman_data_t *) file->privdata)->loc.loc64 = 0;
       ((ioman_data_t *) file->privdata)->dev = dev;
       ((ioman_data_t *) file->privdata)->mode = mode;
       dev->subdevs[subdev].open_refcount++;
       loop = 0;
       while((loop < MAX_OPENFILES) && (dev->subdevs[subdev].open_files[loop]))
       {
           loop++;
       }
       if(loop == MAX_OPENFILES)
       {
          FreeSysMemory(file->privdata);
          M_PRINTF("open: Inconsistency between number of open files and available slot\n");
          return -1;
       }
       dev->subdevs[subdev].open_files[loop] = file->privdata;
       dev->open_refcount++;
       M_PRINTF("open: Opened device %s subdev %d\n", dev->node.name, subdev);
    }
    else
    {
       M_PRINTF("open: Couldn't find the device\n");
       return -1;
    }
    return 0;
 }
References ALLOC_FIRST, AllocSysMemory(), devfs_find_devicename(), DEVFS_MAX_SUBDEVS, DEVFS_MODE_EX, DEVFS_MODE_R, DEVFS_MODE_W, FreeSysMemory(), devfs_device_t::hDev, M_PRINTF, MAX_OPENFILES, subdev_t::mode, devfs_node_t::name, devfs_device_t::node, NULL, O_RDONLY, O_RDWR, O_WRONLY, subdev_t::open_files, subdev_t::open_refcount, devfs_device_t::open_refcount, iop_file_t::privdata, strlen(), strtoul(), devfs_device_t::subdevs, and subdev_t::valid.
Referenced by init_devfs().
devfs_read()
int devfs_read (iop_file_t * file, void * buf, int len)
ioman read handler
Parameters
file Pointer to an ioman file structure
buf Buffer to read data to
len Length of data to read
Returns
Length of data read. 0 on eof or file pointer out of range. -1 on error.
Definition at line 662 of file devfs.c.
 {
    devfs_device_t *dev;
    ioman_data_t *data = (ioman_data_t *) file->privdata;
    //printf("devfs_read file=%p buf=%p len=%d\n", file, buf, len);
    data = file->privdata;
    if((data) && (data->hDev != INVALID_HDEV))
    {
       dev = data->dev;
       if(dev == NULL) /* Device has been closed from under us */
       {
          /* Delete data to try and prevent a memory leak */
          FreeSysMemory(data);
          file->privdata = NULL;
          return -1;
       }
       if((dev->node.read != NULL)
         && (dev->subdevs[data->subdev].mode & DEVFS_MODE_R))
       {
          devfs_info_t dev_info;
          int bytes_read;
          dev_info.data = dev->subdevs[data->subdev].data;
          dev_info.subdev = data->subdev;
          dev_info.mode = data->mode;
          dev_info.loc = data->loc;
          bytes_read = dev->node.read(&dev_info, buf, len);
          if(bytes_read > 0)
          {
             data->loc.loc64 += (u64) bytes_read;
          }
          return bytes_read;
       }
    }
    return -1;
 }
References devfs_info_t::data, subdev_t::data, ioman_data_t::dev, DEVFS_MODE_R, FreeSysMemory(), ioman_data_t::hDev, INVALID_HDEV, devfs_info_t::loc, ioman_data_t::loc, devfs_loc_t::loc64, devfs_info_t::mode, subdev_t::mode, ioman_data_t::mode, devfs_device_t::node, NULL, iop_file_t::privdata, devfs_node_t::read, devfs_info_t::subdev, ioman_data_t::subdev, and devfs_device_t::subdevs.
Referenced by init_devfs().
devfs_subdev_to_str()
const char* devfs_subdev_to_str (int subdev)
Simple function to convert a number to a string
Parameters
subdev The number to convert.
Returns
A constant string containing the number. Returns an empty string if not possible to convert.
Definition at line 106 of file devfs.c.
 {
    static char name[4]; /* Supports up to 999 subdevices */
    int loop;
    if((subdev > 999) || (subdev < 0))
    {
       name[0] = 0;
    }
    else
    {
       loop = 0;
       name[loop++] = ((subdev / 100) % 10) + '0';
       name[loop++] = ((subdev / 10) % 10) + '0';
       name[loop++] = (subdev % 10) + '0';
       name[loop++] = 0;
    }
    loop = 0;
    if(name[0] == '0') loop = 1;
    if((name[0] == '0') && (name[1] == '0')) loop = 2;
    return &name[loop];
 }
Referenced by devfs_fill_dirent().
devfs_write()
int devfs_write (iop_file_t * file, void * buf, int len)
ioman write handler
Parameters
file Pointer to an ioman file structure
buf Pointer to the buffer to write
len Length of data to write
Returns
Number of bytes written, 0 on eof or -1 on error
Definition at line 710 of file devfs.c.
 {
    devfs_device_t *dev;
    ioman_data_t *data = (ioman_data_t *) file->privdata;
    //printf("devfs_write file=%p buf=%p len=%d\n", file, buf, len);
    data = file->privdata;
    if((data) && (data->hDev != INVALID_HDEV))
    {
       dev = data->dev;
       if(dev == NULL) /* Device has been closed from under us */
       {
          /* Delete data to try and prevent a memory leak */
          FreeSysMemory(data);
          file->privdata = NULL;
          return -1;
       }
       if((dev->node.write != NULL)
         && (dev->subdevs[data->subdev].mode & DEVFS_MODE_W))
       {
          devfs_info_t dev_info;
          int bytes_written;
          dev_info.data = dev->subdevs[data->subdev].data;
          dev_info.subdev = data->subdev;
          dev_info.mode = data->mode;
          dev_info.loc = data->loc;
          bytes_written = dev->node.write(&dev_info, buf, len);
          if(bytes_written > 0)
          {
             data->loc.loc64 += (u64) bytes_written;
          }
          return bytes_written;
       }
    }
    return -1;
 }
References devfs_info_t::data, subdev_t::data, ioman_data_t::dev, DEVFS_MODE_W, FreeSysMemory(), ioman_data_t::hDev, INVALID_HDEV, devfs_info_t::loc, ioman_data_t::loc, devfs_loc_t::loc64, devfs_info_t::mode, subdev_t::mode, ioman_data_t::mode, devfs_device_t::node, NULL, iop_file_t::privdata, devfs_info_t::subdev, ioman_data_t::subdev, devfs_device_t::subdevs, and devfs_node_t::write.
init_devfs()
int init_devfs (void)
DevFS initialise function
Returns
>= 0 on success, -1 on error
Definition at line 1013 of file devfs.c.
 {
    int dummy_loop;
    dummy_func *dummy;
    root_device = NULL;
    dev_count = 0;
    /* Set all io handlers to dummy values */
    dummy = (dummy_func *) &devfs_ops;
    for(dummy_loop = 0; dummy_loop < (sizeof(iop_device_ops_t) / sizeof(dummy)); dummy_loop++)
    {
       dummy[dummy_loop] = devfs_dummy;
    }
    memset(open_dirfiles, 0, sizeof(directory_file_t) * MAX_OPEN_DIRFILES);
    devfs_device.name = "devfs";
    devfs_device.type = IOP_DT_FS | IOP_DT_FSEXT;
    devfs_device.version = 0x100;
    devfs_device.desc = "PS2 Device FS Driver";
    devfs_device.ops = &devfs_ops;
    devfs_ops.init = devfs_init;
    devfs_ops.deinit = devfs_deinit;
    devfs_ops.open = devfs_open;
    devfs_ops.read = devfs_read;
    devfs_ops.close = devfs_close;
    devfs_ops.dopen = devfs_dopen;
    devfs_ops.dclose = devfs_dclose;
    devfs_ops.dread = devfs_dread;
    devfs_ops.ioctl = devfs_ioctl;
    devfs_ops.ioctl2 = devfs_ioctl2;
    devfs_ops.getstat = devfs_getstat;
    DelDrv("devfs");
    return AddDrv(&devfs_device);
 }
References AddDrv(), iop_device_ops_t::close, iop_device_ops_t::dclose, iop_device_ops_t::deinit, DelDrv(), iop_device_t::desc, dev_count, devfs_close(), devfs_dclose(), devfs_deinit(), devfs_device, devfs_dopen(), devfs_dread(), devfs_dummy(), devfs_getstat(), devfs_init(), devfs_ioctl(), devfs_ioctl2(), devfs_open(), devfs_ops, devfs_read(), iop_device_ops_t::dopen, iop_device_ops_t::dread, dummy(), iop_device_ops_t::getstat, iop_device_ops_t::init, iop_device_ops_t::ioctl, iop_device_ops_t::ioctl2, IOP_DT_FS, IOP_DT_FSEXT, MAX_OPEN_DIRFILES, memset(), iop_device_t::name, NULL, iop_device_ops_t::open, open_dirfiles, iop_device_t::ops, iop_device_ops_t::read, root_device, iop_device_t::type, and iop_device_t::version.
Referenced by _start().
IRX_ID()
IRX_ID (MODNAME , 1 , 1)
Variable Documentation
_exp_devfs
struct irx_export_table _exp_devfs extern
Referenced by _start().
dev_count
HDEV dev_count
Definition at line 86 of file devfs.c.
Referenced by DevFSAddDevice(), and init_devfs().
devfs_device
iop_device_t devfs_device
Definition at line 48 of file devfs.c.
Referenced by init_devfs().
devfs_ops
iop_device_ops_t devfs_ops
Definition at line 49 of file devfs.c.
Referenced by init_devfs().
open_dirfiles
directory_file_t open_dirfiles[MAX_OPEN_DIRFILES]
Definition at line 99 of file devfs.c.
Referenced by devfs_dopen(), and init_devfs().
root_device
devfs_device_t* root_device
Pointer to the root device
Definition at line 85 of file devfs.c.
Referenced by devfs_fill_dirent(), devfs_find_deviceid(), devfs_find_devicename(), DevFSAddDevice(), DevFSDelDevice(), and init_devfs().