ps2sdk: iop/kernel/include/dmacman.h File Reference
dmacman.h File Reference
#include <types.h>
#include <irx.h>
Data Structures
struct iop_dmac_chan_t
Macros
#define DMAC_CHCR_30 (1<<30)
#define DMAC_CHCR_TR (1<<24)
#define DMAC_CHCR_LI (1<<10)
#define DMAC_CHCR_CO (1<<9)
#define DMAC_CHCR_08 (1<<8)
#define DMAC_CHCR_DR (1<<0)
#define DMAC_TO_MEM 0
#define DMAC_FROM_MEM 1
#define IOP_DMAC_SIF2_MADR (*(volatile int*)0xBF8010A0)
#define IOP_DMAC_SIF2_BCR (*(volatile int*)0xBF8010A4)
#define IOP_DMAC_SIF2_BCR_size (*(volatile short*)0xBF8010A4)
#define IOP_DMAC_SIF2_BCR_count (*(volatile short*)0xBF8010A6)
#define IOP_DMAC_SIF2_CHCR (*(volatile int*)0xBF8010A8)
#define IOP_DMAC_SIF9_MADR (*(volatile int*)0xBF801520)
#define IOP_DMAC_SIF9_BCR (*(volatile int*)0xBF801524)
#define IOP_DMAC_SIF9_BCR_size (*(volatile short*)0xBF801524)
#define IOP_DMAC_SIF9_BCR_count (*(volatile short*)0xBF801526)
#define IOP_DMAC_SIF9_CHCR (*(volatile int*)0xBF801528)
#define IOP_DMAC_SIF9_TADR (*(volatile int*)0xBF80152C)
#define IOP_DMAC_SIFA_MADR (*(volatile int*)0xBF801530)
#define IOP_DMAC_SIFA_BCR (*(volatile int*)0xBF801534)
#define IOP_DMAC_SIFA_BCR_size (*(volatile short*)0xBF801534)
#define IOP_DMAC_SIFA_BCR_count (*(volatile short*)0xBF801536)
#define IOP_DMAC_SIFA_CHCR (*(volatile int*)0xBF801538)
#define IOP_DMAC_DPCR (*(volatile int*)0xBF8010F0)
#define IOP_DMAC_DPCR2 (*(volatile int*)0xBF801570)
#define dmacman_IMPORTS_start DECLARE_IMPORT_TABLE(dmacman, 1, 1)
#define dmacman_IMPORTS_end END_IMPORT_TABLE
#define I_dmac_ch_set_madr DECLARE_IMPORT(4, dmac_ch_set_madr)
#define I_dmac_ch_get_madr DECLARE_IMPORT(5, dmac_ch_get_madr)
#define I_dmac_ch_set_bcr DECLARE_IMPORT(6, dmac_ch_set_bcr)
#define I_dmac_ch_get_bcr DECLARE_IMPORT(7, dmac_ch_get_bcr)
#define I_dmac_ch_set_chcr DECLARE_IMPORT(8, dmac_ch_set_chcr)
#define I_dmac_ch_get_chcr DECLARE_IMPORT(9, dmac_ch_get_chcr)
#define I_dmac_ch_set_tadr DECLARE_IMPORT(10, dmac_ch_set_tadr)
#define I_dmac_ch_get_tadr DECLARE_IMPORT(11, dmac_ch_get_tadr)
#define I_dmac_set_dpcr DECLARE_IMPORT(14, dmac_set_dpcr)
#define I_dmac_get_dpcr DECLARE_IMPORT(15, dmac_get_dpcr)
#define I_dmac_set_dpcr2 DECLARE_IMPORT(16, dmac_set_dpcr2)
#define I_dmac_get_dpcr2 DECLARE_IMPORT(17, dmac_get_dpcr2)
#define I_dmac_set_dpcr3 DECLARE_IMPORT(18, dmac_set_dpcr3)
#define I_dmac_get_dpcr3 DECLARE_IMPORT(19, dmac_get_dpcr3)
#define I_dmac_set_dicr DECLARE_IMPORT(20, dmac_set_dicr)
#define I_dmac_get_dicr DECLARE_IMPORT(21, dmac_get_dicr)
#define I_dmac_set_dicr2 DECLARE_IMPORT(22, dmac_set_dicr2)
#define I_dmac_get_dicr2 DECLARE_IMPORT(23, dmac_get_dicr2)
#define I_dmac_request DECLARE_IMPORT(28, dmac_request)
#define I_dmac_transfer DECLARE_IMPORT(32, dmac_transfer)
#define I_dmac_ch_set_dpcr DECLARE_IMPORT(33, dmac_ch_set_dpcr)
#define I_dmac_enable DECLARE_IMPORT(34, dmac_enable)
#define I_dmac_disable DECLARE_IMPORT(35, dmac_disable)
Enumerations
enum _iop_dmac_ch {
IOP_DMAC_MDECin ,
IOP_DMAC_MDECout ,
IOP_DMAC_SIF2 ,
IOP_DMAC_CDVD ,
IOP_DMAC_SPU ,
IOP_DMAC_PIO ,
IOP_DMAC_OTC ,
IOP_DMAC_SPU2 ,
IOP_DMAC_DEV9 ,
IOP_DMAC_SIF0 ,
IOP_DMAC_SIF1 ,
IOP_DMAC_SIO2in ,
IOP_DMAC_SIO2out ,
IOP_DMAC_FDMA0 ,
IOP_DMAC_FDMA1 ,
IOP_DMAC_FDMA2 ,
IOP_DMAC_CPU = 67 ,
IOP_DMAC_USB = 85
}
Functions
void dmac_ch_set_madr (u32 channel, u32 val)
u32 dmac_ch_get_madr (u32 channel)
void dmac_ch_set_bcr (u32 channel, u32 val)
u32 dmac_ch_get_bcr (u32 channel)
void dmac_ch_set_chcr (u32 channel, u32 val)
u32 dmac_ch_get_chcr (u32 channel)
void dmac_ch_set_tadr (u32 channel, u32 val)
u32 dmac_ch_get_tadr (u32 channel)
void dmac_set_dpcr (u32 val)
u32 dmac_get_dpcr (void)
void dmac_set_dpcr2 (u32 val)
u32 dmac_get_dpcr2 (void)
void dmac_set_dpcr3 (u32 val)
u32 dmac_get_dpcr3 (void)
void dmac_set_dicr (u32 val)
u32 dmac_get_dicr (void)
void dmac_set_dicr2 (u32 val)
u32 dmac_get_dicr2 (void)
int dmac_request (u32 channel, void *addr, u32 size, u32 count, int dir)
void dmac_transfer (u32 channel)
void dmac_ch_set_dpcr (u32 channel, u32 val)
void dmac_enable (u32 channel)
void dmac_disable (u32 channel)
Detailed Description
DMACMAN definitions and imports.
Definition in file dmacman.h.
Macro Definition Documentation
DMAC_CHCR_08
#define DMAC_CHCR_08 (1<<8)
Definition at line 36 of file dmacman.h.
DMAC_CHCR_30
#define DMAC_CHCR_30 (1<<30)
Definition at line 29 of file dmacman.h.
DMAC_CHCR_CO
#define DMAC_CHCR_CO (1<<9)
COntinuous (?)
Definition at line 35 of file dmacman.h.
DMAC_CHCR_DR
#define DMAC_CHCR_DR (1<<0)
DiRection; 0 = to RAM, 1 = from RAM
Definition at line 38 of file dmacman.h.
DMAC_CHCR_LI
#define DMAC_CHCR_LI (1<<10)
LInked list (GPU, SPU and SIF0)
Definition at line 33 of file dmacman.h.
DMAC_CHCR_TR
#define DMAC_CHCR_TR (1<<24)
TRansfer
Definition at line 31 of file dmacman.h.
DMAC_FROM_MEM
#define DMAC_FROM_MEM 1
Definition at line 41 of file dmacman.h.
DMAC_TO_MEM
#define DMAC_TO_MEM 0
Definition at line 40 of file dmacman.h.
dmacman_IMPORTS_end
#define dmacman_IMPORTS_end END_IMPORT_TABLE
Definition at line 121 of file dmacman.h.
dmacman_IMPORTS_start
#define dmacman_IMPORTS_start DECLARE_IMPORT_TABLE(dmacman, 1, 1)
Definition at line 120 of file dmacman.h.
I_dmac_ch_get_bcr
#define I_dmac_ch_get_bcr DECLARE_IMPORT(7, dmac_ch_get_bcr)
Definition at line 126 of file dmacman.h.
I_dmac_ch_get_chcr
#define I_dmac_ch_get_chcr DECLARE_IMPORT(9, dmac_ch_get_chcr)
Definition at line 128 of file dmacman.h.
I_dmac_ch_get_madr
#define I_dmac_ch_get_madr DECLARE_IMPORT(5, dmac_ch_get_madr)
Definition at line 124 of file dmacman.h.
I_dmac_ch_get_tadr
#define I_dmac_ch_get_tadr DECLARE_IMPORT(11, dmac_ch_get_tadr)
Definition at line 130 of file dmacman.h.
I_dmac_ch_set_bcr
#define I_dmac_ch_set_bcr DECLARE_IMPORT(6, dmac_ch_set_bcr)
Definition at line 125 of file dmacman.h.
I_dmac_ch_set_chcr
#define I_dmac_ch_set_chcr DECLARE_IMPORT(8, dmac_ch_set_chcr)
Definition at line 127 of file dmacman.h.
I_dmac_ch_set_dpcr
#define I_dmac_ch_set_dpcr DECLARE_IMPORT(33, dmac_ch_set_dpcr)
Definition at line 143 of file dmacman.h.
I_dmac_ch_set_madr
#define I_dmac_ch_set_madr DECLARE_IMPORT(4, dmac_ch_set_madr)
Definition at line 123 of file dmacman.h.
I_dmac_ch_set_tadr
#define I_dmac_ch_set_tadr DECLARE_IMPORT(10, dmac_ch_set_tadr)
Definition at line 129 of file dmacman.h.
I_dmac_disable
#define I_dmac_disable DECLARE_IMPORT(35, dmac_disable)
Definition at line 145 of file dmacman.h.
I_dmac_enable
#define I_dmac_enable DECLARE_IMPORT(34, dmac_enable)
Definition at line 144 of file dmacman.h.
I_dmac_get_dicr
#define I_dmac_get_dicr DECLARE_IMPORT(21, dmac_get_dicr)
Definition at line 138 of file dmacman.h.
I_dmac_get_dicr2
#define I_dmac_get_dicr2 DECLARE_IMPORT(23, dmac_get_dicr2)
Definition at line 140 of file dmacman.h.
I_dmac_get_dpcr
#define I_dmac_get_dpcr DECLARE_IMPORT(15, dmac_get_dpcr)
Definition at line 132 of file dmacman.h.
I_dmac_get_dpcr2
#define I_dmac_get_dpcr2 DECLARE_IMPORT(17, dmac_get_dpcr2)
Definition at line 134 of file dmacman.h.
I_dmac_get_dpcr3
#define I_dmac_get_dpcr3 DECLARE_IMPORT(19, dmac_get_dpcr3)
Definition at line 136 of file dmacman.h.
I_dmac_request
#define I_dmac_request DECLARE_IMPORT(28, dmac_request)
Definition at line 141 of file dmacman.h.
I_dmac_set_dicr
#define I_dmac_set_dicr DECLARE_IMPORT(20, dmac_set_dicr)
Definition at line 137 of file dmacman.h.
I_dmac_set_dicr2
#define I_dmac_set_dicr2 DECLARE_IMPORT(22, dmac_set_dicr2)
Definition at line 139 of file dmacman.h.
I_dmac_set_dpcr
#define I_dmac_set_dpcr DECLARE_IMPORT(14, dmac_set_dpcr)
Definition at line 131 of file dmacman.h.
I_dmac_set_dpcr2
#define I_dmac_set_dpcr2 DECLARE_IMPORT(16, dmac_set_dpcr2)
Definition at line 133 of file dmacman.h.
I_dmac_set_dpcr3
#define I_dmac_set_dpcr3 DECLARE_IMPORT(18, dmac_set_dpcr3)
Definition at line 135 of file dmacman.h.
I_dmac_transfer
#define I_dmac_transfer DECLARE_IMPORT(32, dmac_transfer)
Definition at line 142 of file dmacman.h.
IOP_DMAC_DPCR
#define IOP_DMAC_DPCR (*(volatile int*)0xBF8010F0)
Definition at line 63 of file dmacman.h.
IOP_DMAC_DPCR2
#define IOP_DMAC_DPCR2 (*(volatile int*)0xBF801570)
Definition at line 64 of file dmacman.h.
IOP_DMAC_SIF2_BCR
#define IOP_DMAC_SIF2_BCR (*(volatile int*)0xBF8010A4)
Definition at line 45 of file dmacman.h.
IOP_DMAC_SIF2_BCR_count
#define IOP_DMAC_SIF2_BCR_count (*(volatile short*)0xBF8010A6)
Definition at line 47 of file dmacman.h.
IOP_DMAC_SIF2_BCR_size
#define IOP_DMAC_SIF2_BCR_size (*(volatile short*)0xBF8010A4)
Definition at line 46 of file dmacman.h.
IOP_DMAC_SIF2_CHCR
#define IOP_DMAC_SIF2_CHCR (*(volatile int*)0xBF8010A8)
Definition at line 48 of file dmacman.h.
IOP_DMAC_SIF2_MADR
#define IOP_DMAC_SIF2_MADR (*(volatile int*)0xBF8010A0)
Definition at line 44 of file dmacman.h.
IOP_DMAC_SIF9_BCR
#define IOP_DMAC_SIF9_BCR (*(volatile int*)0xBF801524)
Definition at line 51 of file dmacman.h.
IOP_DMAC_SIF9_BCR_count
#define IOP_DMAC_SIF9_BCR_count (*(volatile short*)0xBF801526)
Definition at line 53 of file dmacman.h.
IOP_DMAC_SIF9_BCR_size
#define IOP_DMAC_SIF9_BCR_size (*(volatile short*)0xBF801524)
Definition at line 52 of file dmacman.h.
IOP_DMAC_SIF9_CHCR
#define IOP_DMAC_SIF9_CHCR (*(volatile int*)0xBF801528)
Definition at line 54 of file dmacman.h.
IOP_DMAC_SIF9_MADR
#define IOP_DMAC_SIF9_MADR (*(volatile int*)0xBF801520)
Definition at line 50 of file dmacman.h.
IOP_DMAC_SIF9_TADR
#define IOP_DMAC_SIF9_TADR (*(volatile int*)0xBF80152C)
Definition at line 55 of file dmacman.h.
IOP_DMAC_SIFA_BCR
#define IOP_DMAC_SIFA_BCR (*(volatile int*)0xBF801534)
Definition at line 58 of file dmacman.h.
IOP_DMAC_SIFA_BCR_count
#define IOP_DMAC_SIFA_BCR_count (*(volatile short*)0xBF801536)
Definition at line 60 of file dmacman.h.
IOP_DMAC_SIFA_BCR_size
#define IOP_DMAC_SIFA_BCR_size (*(volatile short*)0xBF801534)
Definition at line 59 of file dmacman.h.
IOP_DMAC_SIFA_CHCR
#define IOP_DMAC_SIFA_CHCR (*(volatile int*)0xBF801538)
Definition at line 61 of file dmacman.h.
IOP_DMAC_SIFA_MADR
#define IOP_DMAC_SIFA_MADR (*(volatile int*)0xBF801530)
Definition at line 57 of file dmacman.h.
Enumeration Type Documentation
_iop_dmac_ch
enum _iop_dmac_ch
Enumerator
IOP_DMAC_MDECin
IOP_DMAC_MDECout
IOP_DMAC_SIF2
IOP_DMAC_CDVD
IOP_DMAC_SPU
IOP_DMAC_PIO
IOP_DMAC_OTC
IOP_DMAC_SPU2
IOP_DMAC_DEV9
IOP_DMAC_SIF0
IOP_DMAC_SIF1
IOP_DMAC_SIO2in
IOP_DMAC_SIO2out
IOP_DMAC_FDMA0
IOP_DMAC_FDMA1
IOP_DMAC_FDMA2
IOP_DMAC_CPU
IOP_DMAC_USB
Definition at line 66 of file dmacman.h.
                   {
         IOP_DMAC_MDECin,        IOP_DMAC_MDECout,       IOP_DMAC_SIF2,  IOP_DMAC_CDVD,
         IOP_DMAC_SPU,           IOP_DMAC_PIO,           IOP_DMAC_OTC,   IOP_DMAC_SPU2,
         IOP_DMAC_DEV9,          IOP_DMAC_SIF0,          IOP_DMAC_SIF1,  IOP_DMAC_SIO2in,
         IOP_DMAC_SIO2out,       IOP_DMAC_FDMA0,         IOP_DMAC_FDMA1, IOP_DMAC_FDMA2,
         IOP_DMAC_CPU = 67,      //'C'
         IOP_DMAC_USB = 85,      //'U'
 };
Function Documentation
dmac_ch_get_bcr()
u32 dmac_ch_get_bcr (u32 channel)
dmac_ch_get_chcr()
u32 dmac_ch_get_chcr (u32 channel)
dmac_ch_get_madr()
u32 dmac_ch_get_madr (u32 channel)
dmac_ch_get_tadr()
u32 dmac_ch_get_tadr (u32 channel)
dmac_ch_set_bcr()
void dmac_ch_set_bcr (u32 channel, u32 val)
dmac_ch_set_chcr()
void dmac_ch_set_chcr (u32 channel, u32 val)
dmac_ch_set_dpcr()
void dmac_ch_set_dpcr (u32 channel, u32 val)
Referenced by _start().
dmac_ch_set_madr()
void dmac_ch_set_madr (u32 channel, u32 val)
dmac_ch_set_tadr()
void dmac_ch_set_tadr (u32 channel, u32 val)
dmac_disable()
void dmac_disable (u32 channel)
Referenced by shutdown(), and ShutDownDMAChannels().
dmac_enable()
void dmac_enable (u32 channel)
Referenced by _start(), and iLinkHWInitialize().
dmac_get_dicr()
u32 dmac_get_dicr (void)
dmac_get_dicr2()
u32 dmac_get_dicr2 (void)
dmac_get_dpcr()
u32 dmac_get_dpcr (void)
dmac_get_dpcr2()
u32 dmac_get_dpcr2 (void)
Referenced by dev9_init().
dmac_get_dpcr3()
u32 dmac_get_dpcr3 (void)
dmac_request()
int dmac_request (u32 channel, void * addr, u32 size, u32 count, int dir)
Referenced by send_td().
dmac_set_dicr()
void dmac_set_dicr (u32 val)
dmac_set_dicr2()
void dmac_set_dicr2 (u32 val)
dmac_set_dpcr()
void dmac_set_dpcr (u32 val)
dmac_set_dpcr2()
void dmac_set_dpcr2 (u32 val)
Referenced by dev9_init().
dmac_set_dpcr3()
void dmac_set_dpcr3 (u32 val)
dmac_transfer()
void dmac_transfer (u32 channel)
Referenced by send_td().