ps2sdk: iop/sound/libsd/src/effect.c File Reference
effect.c File Reference
#include "types.h"
#include "libsd.h"
#include "spu2regs.h"
#include "sysclib.h"
Functions
u32 GetEEA (s32 core)
void SetESA (s32 core, u32 value)
void SetEffectRegister (volatile u16 *reg, u32 val)
void SetEffectData (u16 *mode_data, u32 core)
int sceSdSetEffectAttr (int core, sceSdEffectAttr *attr)
void sceSdGetEffectAttr (int core, sceSdEffectAttr *attr)
int sceSdClearEffectWorkArea (int core, int chan, int effect_type)
Variables
u32 VoiceTransIoMode [2]
sceSdTransIntrHandler TransIntrHandlers [2]
SdIntrCallback TransIntrCallbacks [2]
sceSdEffectAttr EffectAttr [2]
u32 EffectAddr [2]
u16 EffectSizes [10] = { 0x1, 0x26C, 0x1F4, 0x484, 0x6FE, 0xADE, 0xF6C, 0x1804, 0x1804, 0x3C0 }
u32 EffectParams [160]
const u32 ClearEffectData [256]
Detailed Description
Part of the IOP Sound Driver
Definition in file effect.c.
Function Documentation
GetEEA()
u32 GetEEA (s32 core)
Definition at line 72 of file effect.c.
 {
         return (*SD_A_EEA_HI(core) << 17) | 0x1FFFF;
 }
References SD_A_EEA_HI.
Referenced by sceSdClearEffectWorkArea(), and sceSdSetEffectAttr().
sceSdClearEffectWorkArea()
int sceSdClearEffectWorkArea (int core, int chan, int effect_type)
Definition at line 203 of file effect.c.
 {
         if(effect_type > 9) return -1;
         if(effect_type != SD_EFFECT_MODE_OFF)
         {
                 u32 aligned_addr = 0;
                 u32 effect_addr;
                 s32 effect_size;
                 s32 old_iomode;
                 sceSdTransIntrHandler old_handler = NULL;
                 SdIntrCallback old_callback = NULL;
                 effect_size = EffectSizes[effect_type] << 4;
                 effect_addr = (GetEEA(core) - (effect_size - 2));
                 if(effect_size & 127)
                 {
                         effect_size &= ~127;
                         aligned_addr = (GetEEA(core) - (effect_size - 2));
                 }
                 old_iomode = VoiceTransIoMode[chan];
                 if(VoiceTransIoMode[chan] == 1) VoiceTransIoMode[chan] = 0;
                 // Disable intr_handlers by removing them
                 if(TransIntrHandlers[chan])
                 {
                         old_handler = TransIntrHandlers[chan];
                         TransIntrHandlers[chan] = 0;
                 }
                 if(TransIntrCallbacks[chan])
                 {
                         old_callback = TransIntrCallbacks[chan];
                         TransIntrCallbacks[chan] = NULL;
                 }
                 if(aligned_addr)
                 {
                         sceSdVoiceTrans(chan, 0, (u8*)ClearEffectData, (u32*)effect_addr, 64);
                         sceSdVoiceTransStatus(chan, 1);
                         effect_addr = aligned_addr;
                 }
                 while(effect_size > 0)
                 {
                         u32 size;
                         if(effect_size < 1024)
                                 size = effect_size;
                         else
                                 size = 1024;
                         sceSdVoiceTrans(chan, 0, (u8*)ClearEffectData, (u32*)effect_addr, size);
                         sceSdVoiceTransStatus(chan, 1); // Wait for completion
                         effect_size -= 1024;
                         effect_addr += 1024;
                 }
                 VoiceTransIoMode[chan] = old_iomode;
                 // Enable intr_handlers by adding them again
                 if(old_handler) TransIntrHandlers[chan] = old_handler;
                 if(old_callback) TransIntrCallbacks[chan] = old_callback;
         }
         return 0;
 }
References ClearEffectData, EffectSizes, GetEEA(), NULL, sceSdVoiceTrans(), sceSdVoiceTransStatus(), SD_EFFECT_MODE_OFF, TransIntrCallbacks, TransIntrHandlers, and VoiceTransIoMode.
Referenced by rpc_server(), and sceSdSetEffectAttr().
sceSdGetEffectAttr()
void sceSdGetEffectAttr (int core, sceSdEffectAttr * attr)
Definition at line 198 of file effect.c.
 {
         *attr = EffectAttr[core & 1];
 }
References EffectAttr.
Referenced by rpc_server().
sceSdSetEffectAttr()
int sceSdSetEffectAttr (int core, sceSdEffectAttr * attr)
Definition at line 109 of file effect.c.
 {
         u32 mode = attr->mode;
         u32 clearram = 0;
         u32 effects_disabled = 0;
         u32 last_mode = 0;
         u16     mode_data[32];
         core &= 1;
         if(mode & SD_EFFECT_MODE_CLEAR)
         {
                 mode &= ~SD_EFFECT_MODE_CLEAR;
                 clearram = 1;
                 last_mode = EffectAttr[core].mode;
         }
         // Check if valid mode
         if(mode > 9) return -1;
         EffectAddr[core] = GetEEA(core) - ((EffectSizes[mode] << 4) - 2);
         memcpy(mode_data, &EffectParams[mode * 16], 64);
         memcpy(&EffectAttr[core], attr, sizeof(sceSdEffectAttr));
         EffectAttr[core].core = core;
         switch(mode)
         {
                 case SD_EFFECT_MODE_ECHO:
                         EffectAttr[core].feedback = 0x80;
                         EffectAttr[core].delay = 0x80;
                         break;
                 case SD_EFFECT_MODE_DELAY:
                         EffectAttr[core].feedback = 0;
                         EffectAttr[core].delay = 0x80;
                         break;
                 default:
                         EffectAttr[core].feedback = 0;
                         EffectAttr[core].delay = 0;
                         break;
         }
         if((mode == SD_EFFECT_MODE_DELAY) || (mode == SD_EFFECT_MODE_ECHO))
         {
                 u16 delay               = ((attr->delay+1) << 5);
                 u16 feedback    = ((attr->feedback << 7) + attr->feedback) << 1;
                 mode_data[7]  = feedback;
                 mode_data[10] = (delay << 1) - mode_data[0];
                 mode_data[11] = delay - mode_data[1];
                 mode_data[16] = mode_data[17] + delay;
                 mode_data[12] = mode_data[13] + delay;
                 mode_data[27] = mode_data[29] + delay;
                 mode_data[26] = mode_data[28] + delay;
         }
         // Disable effects
         if(*SD_CORE_ATTR(core) & SD_ENABLE_EFFECTS)
         {
                 effects_disabled = 1;
                 *SD_CORE_ATTR(core) &= ~SD_ENABLE_EFFECTS;
         }
         // Clean up after last mode
         if((effects_disabled) && (clearram))
                 sceSdClearEffectWorkArea(core, 0, last_mode);
         // Depth / Volume
         *SD_P_EVOLL(core) = attr->depth_L;
         *SD_P_EVOLR(core) = attr->depth_R;
         SetEffectData(mode_data, core);
         // Set effect start addr (ESA)
         SetESA(core, EffectAddr[core]);
         if(clearram)
                 sceSdClearEffectWorkArea(core, 0, mode);
         // Enable effects
         if(effects_disabled)
                 *SD_CORE_ATTR(core) |= SD_ENABLE_EFFECTS;
         return 0;
 }
References sceSdEffectAttr::core, sceSdEffectAttr::delay, sceSdEffectAttr::depth_L, sceSdEffectAttr::depth_R, EffectAddr, EffectAttr, EffectParams, EffectSizes, sceSdEffectAttr::feedback, GetEEA(), memcpy(), sceSdEffectAttr::mode, sceSdClearEffectWorkArea(), SD_CORE_ATTR, SD_EFFECT_MODE_CLEAR, SD_EFFECT_MODE_DELAY, SD_EFFECT_MODE_ECHO, SD_ENABLE_EFFECTS, SD_P_EVOLL, SD_P_EVOLR, SetEffectData(), and SetESA().
Referenced by rpc_server().
SetEffectData()
void SetEffectData (u16 * mode_data, u32 core)
Definition at line 92 of file effect.c.
 {
         s32 i;
         SetEffectRegister(SD_R_FB_SRC_A(core), mode_data[0]);
         SetEffectRegister(SD_R_FB_SRC_B(core), mode_data[1]);
         for(i=0; i < 8; i++)
                 *(SD_R_IIR_ALPHA(core)+i) = mode_data[2+i];
         for(i=0; i < 20; i++)
                 SetEffectRegister(SD_R_IIR_DEST_A0(core)+(i*2), mode_data[10+i]);
         *SD_R_IN_COEF_L(core) = mode_data[30];
         *SD_R_IN_COEF_R(core) = mode_data[31];
 }
References SD_R_FB_SRC_A, SD_R_FB_SRC_B, SD_R_IIR_ALPHA, SD_R_IIR_DEST_A0, SD_R_IN_COEF_L, SD_R_IN_COEF_R, and SetEffectRegister().
Referenced by sceSdSetEffectAttr().
SetEffectRegister()
void SetEffectRegister (volatile u16 * reg, u32 val)
Definition at line 86 of file effect.c.
 {
         reg[0] = (u16)(val >> 14);
         reg[1] = (u16)(val << 2);
 }
Referenced by SetEffectData().
SetESA()
void SetESA (s32 core, u32 value)
Definition at line 77 of file effect.c.
 {
         volatile u16 *reg = SD_A_ESA_HI(core);
         reg[0] = value >> 17;
         reg[1] = value >> 1;
 }
References SD_A_ESA_HI.
Referenced by Reset(), and sceSdSetEffectAttr().
Variable Documentation
ClearEffectData
const u32 ClearEffectData[256]
Initial value:
=
{
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
}
Definition at line 63 of file effect.c.
Referenced by sceSdClearEffectWorkArea().
EffectAddr
u32 EffectAddr[2]
Definition at line 24 of file effect.c.
Referenced by Reset(), and sceSdSetEffectAttr().
EffectAttr
sceSdEffectAttr EffectAttr[2]
Definition at line 23 of file effect.c.
Referenced by Reset(), sceSdGetEffectAttr(), and sceSdSetEffectAttr().
EffectParams
u32 EffectParams[160]
Definition at line 29 of file effect.c.
Referenced by sceSdSetEffectAttr().
EffectSizes
u16 EffectSizes[10] = { 0x1, 0x26C, 0x1F4, 0x484, 0x6FE, 0xADE, 0xF6C, 0x1804, 0x1804, 0x3C0 }
Definition at line 27 of file effect.c.
Referenced by Reset(), sceSdClearEffectWorkArea(), and sceSdSetEffectAttr().
TransIntrCallbacks
SdIntrCallback TransIntrCallbacks[2] extern
Definition at line 37 of file spu2.c.
Referenced by Reset(), sceSdClearEffectWorkArea(), sceSdSetTransCallback(), and TransInterrupt().
TransIntrHandlers
sceSdTransIntrHandler TransIntrHandlers[2] extern
Definition at line 36 of file spu2.c.
Referenced by Reset(), sceSdClearEffectWorkArea(), sceSdSetTransIntrHandler(), and TransInterrupt().
VoiceTransIoMode
u32 VoiceTransIoMode[2] extern
Definition at line 32 of file spu2.c.
Referenced by sceSdClearEffectWorkArea().