ps2sdk: iop/dev9/extflash/src/extflash.c File Reference
extflash.c File Reference
#include "types.h"
#include "defs.h"
#include "irx.h"
#include "loadcore.h"
#include "thbase.h"
#include "stdio.h"
#include "sysclib.h"
#include "dev9regs.h"
#include "speedregs.h"
Data Structures
struct flash_info_t
Macros
#define MODNAME "flash"
#define M_PRINTF(format, args...) printf(MODNAME ": " format, ## args)
#define FLASH_ID_64MBIT 0xe6
#define FLASH_ID_128MBIT 0x73
#define FLASH_ID_256MBIT 0x75
#define FLASH_ID_512MBIT 0x76
#define FLASH_ID_1024MBIT 0x79
#define SM_CMD_READ1 0x00
#define SM_CMD_READ2 0x01
#define SM_CMD_READ3 0x50
#define SM_CMD_RESET 0xff
#define SM_CMD_WRITEDATA 0x80
#define SM_CMD_PROGRAMPAGE 0x10
#define SM_CMD_ERASEBLOCK 0x60
#define SM_CMD_ERASECONFIRM 0xd0
#define SM_CMD_GETSTATUS 0x70
#define SM_CMD_READID 0x90
#define NUM_DEVICES (sizeof(devices)/sizeof(flash_info_t))
Functions
IRX_ID (MODNAME, 1, 1)
static u32 timeout_cb (void *)
int flash_detect (void)
int flash_call5 (void)
int flash_get_info (flash_info_t *info)
int _start (int argc, char *argv[])
int flash_device_reset ()
static void flash_set_page (u32 id, u32 pageofs)
int flash_page_erase (flash_info_t *info, u32 page)
int flash_page_read (flash_info_t *info, u32 page, u32 count, void *buf)
int flash_page_write (flash_info_t *info, u32 page, void *buf)
Variables
static flash_info_t devices []
static iop_sys_clock_t timeout
struct irx_export_table _exp_fls
Macro Definition Documentation
FLASH_ID_1024MBIT
#define FLASH_ID_1024MBIT 0x79
Definition at line 35 of file extflash.c.
FLASH_ID_128MBIT
#define FLASH_ID_128MBIT 0x73
Definition at line 32 of file extflash.c.
FLASH_ID_256MBIT
#define FLASH_ID_256MBIT 0x75
Definition at line 33 of file extflash.c.
FLASH_ID_512MBIT
#define FLASH_ID_512MBIT 0x76
Definition at line 34 of file extflash.c.
FLASH_ID_64MBIT
#define FLASH_ID_64MBIT 0xe6
Definition at line 31 of file extflash.c.
M_PRINTF
#define M_PRINTF (format, args...) printf(MODNAME ": " format, ## args)
Definition at line 26 of file extflash.c.
MODNAME
#define MODNAME "flash"
Definition at line 25 of file extflash.c.
NUM_DEVICES
#define NUM_DEVICES (sizeof(devices)/sizeof(flash_info_t))
Definition at line 64 of file extflash.c.
SM_CMD_ERASEBLOCK
#define SM_CMD_ERASEBLOCK 0x60
Definition at line 44 of file extflash.c.
SM_CMD_ERASECONFIRM
#define SM_CMD_ERASECONFIRM 0xd0
Definition at line 45 of file extflash.c.
SM_CMD_GETSTATUS
#define SM_CMD_GETSTATUS 0x70
Definition at line 46 of file extflash.c.
SM_CMD_PROGRAMPAGE
#define SM_CMD_PROGRAMPAGE 0x10
Definition at line 43 of file extflash.c.
SM_CMD_READ1
#define SM_CMD_READ1 0x00
Definition at line 38 of file extflash.c.
SM_CMD_READ2
#define SM_CMD_READ2 0x01
Definition at line 39 of file extflash.c.
SM_CMD_READ3
#define SM_CMD_READ3 0x50
Definition at line 40 of file extflash.c.
SM_CMD_READID
#define SM_CMD_READID 0x90
Definition at line 47 of file extflash.c.
SM_CMD_RESET
#define SM_CMD_RESET 0xff
Definition at line 41 of file extflash.c.
SM_CMD_WRITEDATA
#define SM_CMD_WRITEDATA 0x80
Definition at line 42 of file extflash.c.
Function Documentation
_start()
int _start (int argc, char * argv[])
Definition at line 75 of file extflash.c.
 {
         if (flash_detect() < 0)
                 return MODULE_NO_RESIDENT_END;
         return RegisterLibraryEntries(&_exp_fls) != 0;
 }
References _exp_fls, flash_detect(), MODULE_NO_RESIDENT_END, and RegisterLibraryEntries().
flash_call5()
int flash_call5 (void)
flash_detect()
int flash_detect (void)
Definition at line 84 of file extflash.c.
 {
         USE_DEV9_REGS;
         USE_SPD_REGS;
         u16 rev;
         if ((DEV9_REG(DEV9_R_REV) & 0xf0) != DEV9_DEV9C_9611) {
                 M_PRINTF("CXD9611 required for flash interface.\n");
                 return -1;
         }
         /* Check bit 5 of the revision register.  */
         if ((rev = SPD_REG16(SPD_R_REV_3)) & SPD_CAPS_FLASH) {
                 M_PRINTF("Detected flash (rev3 0x%02x).\n", rev);
                 return 0;
         }
         M_PRINTF("No flash detected (rev3 0x%02x).\n", rev);
         return -1;
 }
References DEV9_DEV9C_9611, DEV9_R_REV, DEV9_REG, M_PRINTF, SPD_CAPS_FLASH, SPD_R_REV_3, SPD_REG16, USE_DEV9_REGS, and USE_SPD_REGS.
Referenced by _start().
flash_device_reset()
int flash_device_reset ()
Definition at line 106 of file extflash.c.
 {
         USE_SPD_REGS;
         u32 has_timedout = 0;
         u16 tmp __attribute__((unused));
         SPD_REG16(0x480c) = 0x100;
         SPD_REG16(0x4804) = SM_CMD_RESET;
         tmp = SPD_REG16(0x480c);
         tmp = SPD_REG16(0x480c);
         SetAlarm(&timeout, (void *)timeout_cb, &has_timedout);
         while ((SPD_REG16(0x480c) & 0x01) == 0) {
                 if (has_timedout) {
                         if (SPD_REG16(0x480c) & 0x01)
                                 break;
                         M_PRINTF("Device erase: timed out.\n");
                         return -3;
                 }
         }
         CancelAlarm((void *)timeout_cb, &has_timedout);
         SPD_REG16(0x4804) = SM_CMD_GETSTATUS;
         if (SPD_REG16(0x4814) & 0x01) {
                 M_PRINTF("Device erase: status error.\n");
                 return -6;
         }
         SPD_REG16(0x480c) = 0;
         return 0;
 }
References CancelAlarm(), M_PRINTF, SetAlarm(), SM_CMD_GETSTATUS, SM_CMD_RESET, SPD_REG16, timeout, timeout_cb(), and USE_SPD_REGS.
flash_get_info()
int flash_get_info (flash_info_t * info)
Definition at line 142 of file extflash.c.
 {
         USE_SPD_REGS;
         int i;
         u16 tmp __attribute__((unused)), id;
         SPD_REG16(0x480c) = 0x100;
         SPD_REG16(0x4804) = SM_CMD_READID;
         SPD_REG16(0x4808) = 0;
         tmp = SPD_REG16(0x480c);
         tmp = SPD_REG16(0x4814);
         id = SPD_REG16(0x4814);
         SPD_REG16(0x480c) = 0;
         memset(info, 0, sizeof(flash_info_t));
         for (i = 0; i < NUM_DEVICES; i++) {
                 if (id != devices[i].id)
                         continue;
                 memcpy(info, &devices[i], sizeof(flash_info_t));
                 M_PRINTF("Device: ID 0x%02x, %ld Mbit, %ld bytes/page, %ld pages/block, %ld blocks total.\n",
                                 id, info->mbits, info->page_bytes, info->block_pages, info->blocks);
                 return 0;
         }
         return -5;
 }
References devices, M_PRINTF, memcpy(), memset(), NUM_DEVICES, SM_CMD_READID, SPD_REG16, and USE_SPD_REGS.
flash_page_erase()
int flash_page_erase (flash_info_t * info, u32 page)
Definition at line 203 of file extflash.c.
 {
         USE_SPD_REGS;
         u32 pageofs = page * 512;
         u32 has_timedout = 0;
         u16 tmp __attribute__((unused));
         SPD_REG16(0x480c) = 0x180;
         SPD_REG16(0x4804) = SM_CMD_ERASEBLOCK;
         flash_set_page(info->id, pageofs);
         SPD_REG16(0x4804) = SM_CMD_ERASECONFIRM;
         tmp = SPD_REG16(0x480c);
         tmp = SPD_REG16(0x480c);
         SetAlarm(&timeout, (void *)timeout_cb, &has_timedout);
         while ((SPD_REG16(0x480c) & 0x01) == 0) {
                 if (has_timedout) {
                         if (SPD_REG16(0x480c) & 0x01)
                                 break;
                         M_PRINTF("Page erase: timed out.\n");
                         return -3;
                 }
         }
         CancelAlarm((void *)timeout_cb, &has_timedout);
         SPD_REG16(0x4804) = SM_CMD_GETSTATUS;
         if (SPD_REG16(0x4814) & 0x01) {
                 M_PRINTF("Page erase: status error.\n");
                 return -6;
         }
         SPD_REG16(0x480c) = 0;
         return 0;
 }
References CancelAlarm(), flash_set_page(), M_PRINTF, SetAlarm(), SM_CMD_ERASEBLOCK, SM_CMD_ERASECONFIRM, SM_CMD_GETSTATUS, SPD_REG16, timeout, timeout_cb(), and USE_SPD_REGS.
flash_page_read()
int flash_page_read (flash_info_t * info, u32 page, u32 count, void * buf)
Definition at line 250 of file extflash.c.
 {
         USE_SPD_REGS;
         u32 *buf_w;
         u16 *buf_h;
         int i, j;
         u32 byteofs, pageofs = page * 512;
         u32 has_timedout;
         u16 tmp __attribute__((unused)), func = 0x100;
         if (info->page_bytes == 512)
                 func = 0x1100;
         SPD_REG16(0x480c) = func;
         if (info->page_bytes == 16) {
                 SPD_REG16(0x4804) = SM_CMD_READ3;
                 byteofs = pageofs & 0x0f;
         } else {
                 SPD_REG16(0x4804) = SM_CMD_READ1;
                 byteofs = pageofs & 0x1ff;
         }
         SPD_REG16(0x4808) = (byteofs & 0xff) | 0x100;
         /* Set the rest of the page info.  */
         flash_set_page(info->id, pageofs);
         buf_w = (u32 *)buf;
         buf_h = (u16 *)buf;
         for (i = 0; i < count; i++) {
                 tmp = SPD_REG16(0x480c);
                 tmp = SPD_REG16(0x480c);
                 has_timedout = 0;
                 SetAlarm(&timeout, (void *)timeout_cb, &has_timedout);
                 while ((SPD_REG16(0x480c) & 0x01) == 0) {
                         if (has_timedout) {
                                 if (SPD_REG16(0x480c) & 0x01)
                                         break;
                                 M_PRINTF("Page read: timed out.\n");
                                 return -3;
                         }
                 }
                 CancelAlarm((void *)timeout_cb, &has_timedout);
                 SPD_REG16(0x480c) = func | 0x800;
                 if (byteofs == 0) {
                         /* 32-bit copy.  */
                         for (j = 0; j < (info->page_bytes / 4); j++)
                                 *buf_w++ = SPD_REG32(0x4800);
                 } else {
                         /* 16-bit copy.  */
                         for (j = (byteofs + (byteofs >> 31)) / 2; j < (info->page_bytes / 2); j++)
                                 *buf_h++ = SPD_REG16(0x4800);
                 }
                 byteofs = 0;
                 SPD_REG16(0x480c) = func;
         }
         SPD_REG16(0x480c) = 0;
         return 0;
 }
References CancelAlarm(), flash_set_page(), M_PRINTF, SetAlarm(), SM_CMD_READ1, SM_CMD_READ3, SPD_REG16, SPD_REG32, timeout, timeout_cb(), and USE_SPD_REGS.
flash_page_write()
int flash_page_write (flash_info_t * info, u32 page, void * buf)
Definition at line 322 of file extflash.c.
 {
         USE_SPD_REGS;
         u16 *buf_h = buf;
         int i;
         u32 pageofs = page * 512;
         u32 has_timedout = 0;
         u16 tmp __attribute__((unused));
         SPD_REG16(0x480c) = 0x180;
         SPD_REG16(0x4804) = SM_CMD_WRITEDATA;
         SPD_REG16(0x4808) = 0x100;
         flash_set_page(info->id, pageofs);
         for (i = 0; i < (info->page_bytes / 2); i++)
                 SPD_REG16(0x4800) = *buf_h++;
         SPD_REG16(0x4804) = SM_CMD_PROGRAMPAGE;
         tmp = SPD_REG16(0x480c);
         tmp = SPD_REG16(0x480c);
         SetAlarm(&timeout, (void *)timeout_cb, &has_timedout);
         while ((SPD_REG16(0x480c) & 0x01) == 0) {
                 if (has_timedout) {
                         if (SPD_REG16(0x480c) & 0x01)
                                 break;
                         M_PRINTF("Page write: timed out.\n");
                         return -3;
                 }
         }
         CancelAlarm((void *)timeout_cb, &has_timedout);
         SPD_REG16(0x4804) = SM_CMD_GETSTATUS;
         if (SPD_REG16(0x4814) & 0x01) {
                 M_PRINTF("Page write: status error.\n");
                 return -6;
         }
         SPD_REG16(0x480c) = 0;
         return 0;
 }
References CancelAlarm(), flash_set_page(), M_PRINTF, SetAlarm(), SM_CMD_GETSTATUS, SM_CMD_PROGRAMPAGE, SM_CMD_WRITEDATA, SPD_REG16, timeout, timeout_cb(), and USE_SPD_REGS.
flash_set_page()
static void flash_set_page (u32 id, u32 pageofs) static
Definition at line 172 of file extflash.c.
 {
         USE_SPD_REGS;
         switch (id) {
                 case FLASH_ID_128MBIT:
                         SPD_REG16(0x4808) = ((pageofs >> 9) & 0xf0) | 0x100;
                         SPD_REG16(0x4808) = (pageofs >> 17) & 0x7f;
                         break;
                 case FLASH_ID_256MBIT:
                         SPD_REG16(0x4808) = ((pageofs >> 9) & 0xf0) | 0x100;
                         SPD_REG16(0x4808) = (pageofs >> 17) & 0xff;
                         break;
                 case FLASH_ID_512MBIT:
                         SPD_REG16(0x4808) = ((pageofs >> 9) & 0xe0) | 0x100;
                         SPD_REG16(0x4808) = ((pageofs >> 17) & 0xff) | 0x100;
                         SPD_REG16(0x4808) = (pageofs >> 25) & 0x01;
                         break;
                 case FLASH_ID_1024MBIT:
                         SPD_REG16(0x4808) = ((pageofs >> 9) & 0xe0) | 0x100;
                         SPD_REG16(0x4808) = ((pageofs >> 17) & 0xff) | 0x100;
                         SPD_REG16(0x4808) = (pageofs >> 25) & 0x02;
                         break;
                 case FLASH_ID_64MBIT:
                         SPD_REG16(0x4808) = ((pageofs >> 9) & 0xf0) | 0x100;
                         SPD_REG16(0x4808) = (pageofs >> 17) & 0x3f;
                         break;
         }
 }
References FLASH_ID_1024MBIT, FLASH_ID_128MBIT, FLASH_ID_256MBIT, FLASH_ID_512MBIT, FLASH_ID_64MBIT, SPD_REG16, and USE_SPD_REGS.
Referenced by flash_page_erase(), flash_page_read(), and flash_page_write().
IRX_ID()
IRX_ID (MODNAME , 1 , 1)
timeout_cb()
static u32 timeout_cb (void * arg) static
Definition at line 368 of file extflash.c.
 {
         u32 *has_timedout = (u32 *)arg;
         *has_timedout = 1;
         return 0;
 }
References arg.
Referenced by flash_device_reset(), flash_page_erase(), flash_page_read(), and flash_page_write().
Variable Documentation
_exp_fls
struct irx_export_table _exp_fls extern
Referenced by _start().
devices
flash_info_t devices[] static
Initial value:
= {
        { FLASH_ID_64MBIT, 64, 528, 16, 1024 },
        { FLASH_ID_128MBIT, 128, 528, 32, 1024 },
        { FLASH_ID_256MBIT, 256, 528, 32, 2048 },
        { FLASH_ID_512MBIT, 512, 528, 32, 4096 },
        { FLASH_ID_1024MBIT, 1024, 528, 32, 8192 }
}
Definition at line 57 of file extflash.c.
Referenced by fileXio_GetDeviceList_RPC(), and flash_get_info().
timeout
iop_sys_clock_t timeout static
Definition at line 66 of file extflash.c.
Referenced by flash_device_reset(), flash_page_erase(), flash_page_read(), flash_page_write(), poll(), sys_arch_mbox_fetch(), and sys_arch_sem_wait().