ps2sdk: iop/fs/filexio/src/fileXio_iop.c File Reference
fileXio_iop.c File Reference
#include <types.h>
#include <stdio.h>
#include <sysclib.h>
#include <thbase.h>
#include <intrman.h>
#include <iomanX.h>
#include <loadcore.h>
#include <sysmem.h>
#include <sifman.h>
#include <sifcmd.h>
#include <errno.h>
#include <fileXio.h>
Macros
#define MODNAME "IOX/File_Manager_Rpc"
#define TRUE 1
#define FALSE 0
#define MIN(a, b) (((a)<(b))?(a):(b))
#define RDOWN_64(a) ((unsigned int)(a)&~0x3F)
#define DEFAULT_RWSIZE 16384
Functions
IRX_ID (MODNAME, 1, 2)
static int fileXio_GetDeviceList_RPC (struct fileXioDevice *ee_devices, int eecount)
static int fileXio_CopyFile_RPC (const char *src, const char *dest, int mode)
static int fileXio_Read_RPC (int infd, char *read_buf, int read_size, void *intr_data)
static int fileXio_Write_RPC (int outfd, const char *write_buf, int write_size, int mis, u8 *misbuf)
static int fileXio_GetDir_RPC (const char *pathname, struct fileXioDirEntry dirEntry[], unsigned int req_entries)
static int fileXio_Mount_RPC (const char *mountstring, const char *mountpoint, int flag)
static int fileXio_chstat_RPC (char *filename, void *eeptr, int mask)
static int fileXio_getstat_RPC (char *filename, void *eeptr)
static int fileXio_dread_RPC (int fd, void *eeptr)
static void * fileXioRpc_Stop ()
static void * fileXioRpc_GetDeviceList (unsigned int *sbuff)
static void * fileXioRpc_Getdir (unsigned int *sbuff)
static void * fileXioRpc_Mount (unsigned int *sbuff)
static void * fileXioRpc_uMount (unsigned int *sbuff)
static void * fileXioRpc_CopyFile (unsigned int *sbuff)
static void * fileXioRpc_MkDir (unsigned int *sbuff)
static void * fileXioRpc_RmDir (unsigned int *sbuff)
static void * fileXioRpc_Remove (unsigned int *sbuff)
static void * fileXioRpc_Rename (unsigned int *sbuff)
static void * fileXioRpc_SymLink (unsigned int *sbuff)
static void * fileXioRpc_ReadLink (unsigned int *sbuff)
static void * fileXioRpc_ChDir (unsigned int *sbuff)
static void * fileXioRpc_Open (unsigned int *sbuff)
static void * fileXioRpc_Close (unsigned int *sbuff)
static void * fileXioRpc_Read (unsigned int *sbuff)
static void * fileXioRpc_Write (unsigned int *sbuff)
static void * fileXioRpc_Lseek (unsigned int *sbuff)
static void * fileXioRpc_Lseek64 (unsigned int *sbuff)
static void * fileXioRpc_ChStat (unsigned int *sbuff)
static void * fileXioRpc_GetStat (unsigned int *sbuff)
static void * fileXioRpc_Format (unsigned int *sbuff)
static void * fileXioRpc_AddDrv (unsigned int *sbuff)
static void * fileXioRpc_DelDrv (unsigned int *sbuff)
static void * fileXioRpc_Sync (unsigned int *sbuff)
static void * fileXioRpc_Devctl (unsigned int *sbuff)
static void * fileXioRpc_Ioctl (unsigned int *sbuff)
static void * fileXioRpc_Ioctl2 (unsigned int *sbuff)
static void * fileXioRpc_Dopen (unsigned int *sbuff)
static void * fileXioRpc_Dread (unsigned int *sbuff)
static void * fileXioRpc_Dclose (unsigned int *sbuff)
static void * filexioRpc_SetRWBufferSize (void *sbuff)
static void DirEntryCopy (struct fileXioDirEntry *dirEntry, iox_dirent_t *internalDirEntry)
static void * fileXio_rpc_server (int fno, void *data, int size)
static void fileXio_Thread (void *param)
int _start (int argc, char **argv)
Variables
static void * rwbuf = NULL
static unsigned int RWBufferSize =DEFAULT_RWSIZE
static unsigned char fileXio_rpc_buffer [0x4C00]
struct t_SifRpcDataQueue qd
struct t_SifRpcServerData sd0
static rests_pkt rests
Detailed Description
fileXio RPC Server This module provides an RPC interface to the EE for all the functions of ioman/fileio.
Definition in file fileXio_iop.c.
Macro Definition Documentation
DEFAULT_RWSIZE
#define DEFAULT_RWSIZE 16384
Definition at line 42 of file fileXio_iop.c.
FALSE
#define FALSE 0
Definition at line 37 of file fileXio_iop.c.
MIN
#define MIN (a, b) (((a)<(b))?(a):(b))
Definition at line 39 of file fileXio_iop.c.
MODNAME
#define MODNAME "IOX/File_Manager_Rpc"
Definition at line 33 of file fileXio_iop.c.
RDOWN_64
#define RDOWN_64 (a) ((unsigned int)(a)&~0x3F)
Definition at line 40 of file fileXio_iop.c.
TRUE
#define TRUE 1
Definition at line 36 of file fileXio_iop.c.
Function Documentation
DirEntryCopy()
static void DirEntryCopy (struct fileXioDirEntry * dirEntry, iox_dirent_t * internalDirEntry) static
Definition at line 1145 of file fileXio_iop.c.
 {
         dirEntry->fileSize = internalDirEntry->stat.size;
         dirEntry->fileProperties = internalDirEntry->stat.attr;
         strncpy(dirEntry->filename,internalDirEntry->name,127);
         dirEntry->filename[127] = '\0';
 }
References iox_stat_t::attr, fileXioDirEntry::filename, fileXioDirEntry::fileProperties, fileXioDirEntry::fileSize, iox_dirent_t::name, iox_stat_t::size, iox_dirent_t::stat, and strncpy().
Referenced by fileXio_GetDir_RPC().
fileXio_chstat_RPC()
static int fileXio_chstat_RPC (char * filename, void * eeptr, int mask) static
Definition at line 413 of file fileXio_iop.c.
 {
       int res=0;
         iox_stat_t localStat;
       SifRpcReceiveData_t rdata;
         SifRpcGetOtherData(&rdata, (void *)eeptr, &localStat, 64, 0);
         res = chstat(filename, &localStat, mask);
       return(res);
 }
References chstat(), fileXioDirEntry::filename, and SifRpcGetOtherData.
Referenced by fileXioRpc_ChStat().
fileXio_CopyFile_RPC()
static int fileXio_CopyFile_RPC (const char * src, const char * dest, int mode) static
Definition at line 162 of file fileXio_iop.c.
 {
   iox_stat_t stat;
   int infd, outfd, size, remain, i, retval = 0;
   if ((infd = open(src, O_RDONLY, 0666)) < 0) {
     return infd;
   }
   if ((outfd = open(dest, O_RDWR|O_CREAT|O_TRUNC, 0666)) < 0) {
     close(infd);
     return outfd;
   }
   size = lseek(infd, 0, SEEK_END);
   lseek(infd, 0, SEEK_SET);
   if (!size)
     return retval;
   remain = size % RWBufferSize;
   for (i = 0; i < (size / RWBufferSize); i++) {
     read(infd, rwbuf, RWBufferSize);
     write(outfd, rwbuf, RWBufferSize);
   }
   read(infd, rwbuf, remain);
   write(outfd, rwbuf, remain);
   close(infd);
   close(outfd);
   stat.mode = mode;
   chstat(dest, &stat, 1);
   return size;
 }
References chstat(), close(), lseek(), iox_stat_t::mode, O_CREAT, O_RDONLY, O_RDWR, O_TRUNC, open(), read(), rwbuf, RWBufferSize, SEEK_END, SEEK_SET, and write().
Referenced by fileXioRpc_CopyFile().
fileXio_dread_RPC()
static int fileXio_dread_RPC (int fd, void * eeptr) static
Definition at line 451 of file fileXio_iop.c.
 {
       int res=0;
         iox_dirent_t localDir;
       struct t_SifDmaTransfer dmaStruct;
       int intStatus;    // interrupt status - for dis/en-abling interrupts
         res = dread(fd, &localDir);
       if (res > 0)
       {
           // DMA localStat to the address specified by eeptr
           // setup the dma struct
           dmaStruct.src = &localDir;
           dmaStruct.dest = eeptr;
           dmaStruct.size = 64+256;
           dmaStruct.attr = 0;
           // Do the DMA transfer
           CpuSuspendIntr(&intStatus);
           SifSetDma(&dmaStruct, 1);
           CpuResumeIntr(intStatus);
       }
       return(res);
 }
References CpuResumeIntr(), CpuSuspendIntr(), dread(), and SifSetDma.
Referenced by fileXioRpc_Dread().
fileXio_GetDeviceList_RPC()
static int fileXio_GetDeviceList_RPC (struct fileXioDevice * ee_devices, int eecount) static
Definition at line 128 of file fileXio_iop.c.
 {
     int device_count = 0;
     iop_device_t **devices = GetDeviceList();
     struct fileXioDevice local_devices[FILEXIO_MAX_DEVICES];
     while (devices[device_count] && device_count < eecount)
     {
         iop_device_t *device = devices[device_count];
         strncpy(local_devices[device_count].name, device->name, 128);
         local_devices[device_count].name[15] = '\0';
         local_devices[device_count].type = device->type;
         local_devices[device_count].version = device->version;
         strncpy(local_devices[device_count].desc, device->desc, 128);
         local_devices[device_count].desc[127] = '\0';
         ++device_count;
     }
     if (device_count)
     {
         struct t_SifDmaTransfer dmaStruct;
         int intStatus;  // interrupt status - for dis/en-abling interrupts
         dmaStruct.src = local_devices;
         dmaStruct.dest = ee_devices;
         dmaStruct.size = sizeof(struct fileXioDevice) * device_count;
         dmaStruct.attr = 0;
         // Do the DMA transfer
         CpuSuspendIntr(&intStatus);
         SifSetDma(&dmaStruct, 1);
         CpuResumeIntr(intStatus);
     }
     return device_count;
 }
References CpuResumeIntr(), CpuSuspendIntr(), fileXioDevice::desc, iop_device_t::desc, devices, FILEXIO_MAX_DEVICES, GetDeviceList(), fileXioDevice::name, iop_device_t::name, SifSetDma, strncpy(), fileXioDevice::type, iop_device_t::type, fileXioDevice::version, and iop_device_t::version.
Referenced by fileXioRpc_GetDeviceList().
fileXio_GetDir_RPC()
static int fileXio_GetDir_RPC (const char * pathname, struct fileXioDirEntry dirEntry[], unsigned int req_entries) static
Definition at line 337 of file fileXio_iop.c.
 {
         int matched_entries;
       int fd, res;
         iox_dirent_t dirbuf;
         struct fileXioDirEntry localDirEntry;
         int intStatus;  // interrupt status - for dis/en-abling interrupts
         struct t_SifDmaTransfer dmaStruct;
         int dmaID;
         dmaID = 0;
         #ifdef DEBUG
                 printf("RPC GetDir Request\n");
                 printf("dirname: %s\n",pathname);
         #endif
         matched_entries = 0;
       fd = dopen(pathname);
       if (fd <= 0)
       {
         return fd;
       }
         {
         res = 1;
         while (res > 0)
         {
           memset(&dirbuf, 0, sizeof(dirbuf));
           res = dread(fd, &dirbuf);
           if (res > 0)
           {
                 // check for too many entries
                 if (matched_entries == req_entries)
                 {
                         close(fd);
                         return (matched_entries);
                 }
                 // wait for any previous DMA to complete
               // before over-writing localDirEntry
               while(SifDmaStat(dmaID)>=0);
             DirEntryCopy(&localDirEntry, &dirbuf);
               // DMA localDirEntry to the address specified by dirEntry[matched_entries]
               // setup the dma struct
               dmaStruct.src = &localDirEntry;
               dmaStruct.dest = &dirEntry[matched_entries];
               dmaStruct.size = sizeof(struct fileXioDirEntry);
               dmaStruct.attr = 0;
               // Do the DMA transfer
               CpuSuspendIntr(&intStatus);
               dmaID = SifSetDma(&dmaStruct, 1);
               CpuResumeIntr(intStatus);
               matched_entries++;
           } // if res
         } // while
       } // if dirs and files
       // cleanup and return # of entries
       close(fd);
         return (matched_entries);
 }
References close(), CpuResumeIntr(), CpuSuspendIntr(), DirEntryCopy(), dopen(), dread(), memset(), printf(), SifDmaStat, and SifSetDma.
Referenced by fileXioRpc_Getdir().
fileXio_getstat_RPC()
static int fileXio_getstat_RPC (char * filename, void * eeptr) static
Definition at line 425 of file fileXio_iop.c.
 {
         iox_stat_t localStat;
         int res = 0;
         struct t_SifDmaTransfer dmaStruct;
         int intStatus;  // interrupt status - for dis/en-abling interrupts
         res = getstat(filename, &localStat);
         if(res >= 0)
         {
                 // DMA localStat to the address specified by eeptr
                 // setup the dma struct
                 dmaStruct.src = &localStat;
                 dmaStruct.dest = eeptr;
                 dmaStruct.size = sizeof(iox_stat_t);
                 dmaStruct.attr = 0;
                 // Do the DMA transfer
                 CpuSuspendIntr(&intStatus);
                 SifSetDma(&dmaStruct, 1);
                 CpuResumeIntr(intStatus);
         }
         return(res);
 }
References CpuResumeIntr(), CpuSuspendIntr(), getstat(), SifSetDma, and iox_stat_t::size.
Referenced by fileXioRpc_GetStat().
fileXio_Mount_RPC()
static int fileXio_Mount_RPC (const char * mountstring, const char * mountpoint, int flag) static
Definition at line 402 of file fileXio_iop.c.
 {
         int res=0;
         #ifdef DEBUG
                 printf("RPC Mount Request\n");
                 printf("mountpoint: %s - %s - %d\n",mountpoint,mountstring,flag);
         #endif
         res = mount(mountpoint, mountstring, flag, NULL, 0);
         return(res);
 }
References mount(), NULL, and printf().
Referenced by fileXioRpc_Mount().
fileXio_Read_RPC()
static int fileXio_Read_RPC (int infd, char * read_buf, int read_size, void * intr_data) static
Definition at line 195 of file fileXio_iop.c.
 {
      int srest;
      int erest;
      int asize;
      int abuffer;
      int rlen;
      int total;
      int readlen;
      int status;
      struct t_SifDmaTransfer dmaStruct;
      void *buffer;
      void *aebuffer;
      int intStatus;     // interrupt status - for dis/en-abling interrupts
      int read_buf2 = (int)read_buf;
         total = 0;
         if(read_size < 64)
         {
                 srest = read_size;
                 erest = asize = abuffer = 0;
                 buffer = read_buf;
                 aebuffer = 0;
         }else{
                 if ((read_buf2 & 0x3F) == 0)
                         srest=0;
                 else
                         srest=(int)RDOWN_64(read_buf2) - read_buf2 + 64;
                 buffer = read_buf;
                 abuffer = read_buf2 + srest;
                 aebuffer=(void *)RDOWN_64(read_buf2 + read_size);
                 asize = (int)aebuffer - (int)abuffer;
                 erest = (read_buf2 + read_size) - (int)aebuffer;
         }
         if (srest>0)
         {
                 if (srest!=(rlen=read(infd, rests.sbuffer, srest)))
                 {
                         total += srest = (rlen>0 ? rlen:0);
                         goto EXIT;
                 }
                 else
                         total += srest;
         }
         status=0;
         while (asize>0)
         {
                 readlen=MIN(RWBufferSize, asize);
                 while(SifDmaStat(status)>=0);
                 rlen=read(infd, rwbuf, readlen);
                 if (readlen!=rlen){
                         if (rlen<=0)goto EXIT;
                         dmaStruct.dest=(void *)abuffer;
                         dmaStruct.size=rlen;
                         dmaStruct.attr=0;
                         dmaStruct.src =rwbuf;
                         CpuSuspendIntr(&intStatus);
                         SifSetDma(&dmaStruct, 1);
                         CpuResumeIntr(intStatus);
                         total   +=rlen;
                         goto EXIT;
                 }else{                  //read ok
                         total   += rlen;
                         asize   -=rlen;
                         dmaStruct.dest=(void *)abuffer;
                         abuffer +=rlen;
                         dmaStruct.size=rlen;
                         dmaStruct.attr=0;
                         dmaStruct.src =rwbuf;
                         CpuSuspendIntr(&intStatus);
                         status=SifSetDma(&dmaStruct, 1);
                         CpuResumeIntr(intStatus);
                 }
         }
         if (erest>0)
         {
                 rlen = read(infd, rests.ebuffer, erest);
                 total += (rlen>0 ? rlen : 0);
         }
 EXIT:
         rests.ssize=srest;
         rests.esize=erest;
         rests.sbuf =buffer;
         rests.ebuf =aebuffer;
       dmaStruct.src =&rests;
         dmaStruct.size=sizeof(rests_pkt);
         dmaStruct.attr=0;
         dmaStruct.dest=intr_data;
         CpuSuspendIntr(&intStatus);
         SifSetDma(&dmaStruct, 1);
         CpuResumeIntr(intStatus);
         return (total);
 }
References buffer, CpuResumeIntr(), CpuSuspendIntr(), rests_pkt::ebuf, rests_pkt::ebuffer, rests_pkt::esize, MIN, RDOWN_64, read(), rests, rwbuf, RWBufferSize, rests_pkt::sbuf, rests_pkt::sbuffer, SifDmaStat, SifSetDma, rests_pkt::ssize, and status.
Referenced by fileXioRpc_Read().
fileXio_rpc_server()
static void * fileXio_rpc_server (int fno, void * data, int size) static
Definition at line 1071 of file fileXio_iop.c.
 {
         switch(fno) {
                 case FILEXIO_DOPEN:
                         return fileXioRpc_Dopen((unsigned*)data);
                 case FILEXIO_DREAD:
                         return fileXioRpc_Dread((unsigned*)data);
                 case FILEXIO_DCLOSE:
                         return fileXioRpc_Dclose((unsigned*)data);
                 case FILEXIO_MOUNT:
                         return fileXioRpc_Mount((unsigned*)data);
                 case FILEXIO_UMOUNT:
                         return fileXioRpc_uMount((unsigned*)data);
                 case FILEXIO_GETDIR:
                         return fileXioRpc_Getdir((unsigned*)data);
                 case FILEXIO_COPYFILE:
                         return fileXioRpc_CopyFile((unsigned*)data);
                 case FILEXIO_STOP:
                         return fileXioRpc_Stop();
                 case FILEXIO_CHDIR:
                         return fileXioRpc_ChDir((unsigned*)data);
                 case FILEXIO_RENAME:
                         return fileXioRpc_Rename((unsigned*)data);
                 case FILEXIO_MKDIR:
                         return fileXioRpc_MkDir((unsigned*)data);
                 case FILEXIO_RMDIR:
                         return fileXioRpc_RmDir((unsigned*)data);
                 case FILEXIO_REMOVE:
                         return fileXioRpc_Remove((unsigned*)data);
                 case FILEXIO_OPEN:
                         return fileXioRpc_Open((unsigned*)data);
                 case FILEXIO_CLOSE:
                         return fileXioRpc_Close((unsigned*)data);
                 case FILEXIO_READ:
                         return fileXioRpc_Read((unsigned*)data);
                 case FILEXIO_WRITE:
                         return fileXioRpc_Write((unsigned*)data);
                 case FILEXIO_LSEEK:
                         return fileXioRpc_Lseek((unsigned*)data);
                 case FILEXIO_IOCTL:
                         return fileXioRpc_Ioctl((unsigned*)data);
                 case FILEXIO_GETSTAT:
                         return fileXioRpc_GetStat((unsigned*)data);
                 case FILEXIO_CHSTAT:
                         return fileXioRpc_ChStat((unsigned*)data);
                 case FILEXIO_FORMAT:
                         return fileXioRpc_Format((unsigned*)data);
                 case FILEXIO_ADDDRV:
                         return fileXioRpc_AddDrv((unsigned*)data);
                 case FILEXIO_DELDRV:
                         return fileXioRpc_DelDrv((unsigned*)data);
                 case FILEXIO_SYNC:
                         return fileXioRpc_Sync((unsigned*)data);
                 case FILEXIO_DEVCTL:
                         return fileXioRpc_Devctl((unsigned*)data);
                 case FILEXIO_SYMLINK:
                         return fileXioRpc_SymLink((unsigned*)data);
                 case FILEXIO_READLINK:
                         return fileXioRpc_ReadLink((unsigned*)data);
                 case FILEXIO_IOCTL2:
                         return fileXioRpc_Ioctl2((unsigned*)data);
                 case FILEXIO_LSEEK64:
                         return fileXioRpc_Lseek64((unsigned*)data);
                 case FILEXIO_GETDEVICELIST:
                         return fileXioRpc_GetDeviceList((unsigned*)data);
                 case FILEXIO_SETRWBUFFSIZE:
                         return filexioRpc_SetRWBufferSize(data);
         }
         return NULL;
 }
References FILEXIO_ADDDRV, FILEXIO_CHDIR, FILEXIO_CHSTAT, FILEXIO_CLOSE, FILEXIO_COPYFILE, FILEXIO_DCLOSE, FILEXIO_DELDRV, FILEXIO_DEVCTL, FILEXIO_DOPEN, FILEXIO_DREAD, FILEXIO_FORMAT, FILEXIO_GETDEVICELIST, FILEXIO_GETDIR, FILEXIO_GETSTAT, FILEXIO_IOCTL, FILEXIO_IOCTL2, FILEXIO_LSEEK, FILEXIO_LSEEK64, FILEXIO_MKDIR, FILEXIO_MOUNT, FILEXIO_OPEN, FILEXIO_READ, FILEXIO_READLINK, FILEXIO_REMOVE, FILEXIO_RENAME, FILEXIO_RMDIR, FILEXIO_SETRWBUFFSIZE, FILEXIO_STOP, FILEXIO_SYMLINK, FILEXIO_SYNC, FILEXIO_UMOUNT, FILEXIO_WRITE, fileXioRpc_AddDrv(), fileXioRpc_ChDir(), fileXioRpc_ChStat(), fileXioRpc_Close(), fileXioRpc_CopyFile(), fileXioRpc_Dclose(), fileXioRpc_DelDrv(), fileXioRpc_Devctl(), fileXioRpc_Dopen(), fileXioRpc_Dread(), fileXioRpc_Format(), fileXioRpc_GetDeviceList(), fileXioRpc_Getdir(), fileXioRpc_GetStat(), fileXioRpc_Ioctl(), fileXioRpc_Ioctl2(), fileXioRpc_Lseek(), fileXioRpc_Lseek64(), fileXioRpc_MkDir(), fileXioRpc_Mount(), fileXioRpc_Open(), fileXioRpc_Read(), fileXioRpc_ReadLink(), fileXioRpc_Remove(), fileXioRpc_Rename(), fileXioRpc_RmDir(), filexioRpc_SetRWBufferSize(), fileXioRpc_Stop(), fileXioRpc_SymLink(), fileXioRpc_Sync(), fileXioRpc_uMount(), fileXioRpc_Write(), and NULL.
Referenced by fileXio_Thread().
fileXio_Thread()
static void fileXio_Thread (void * param) static
Definition at line 1023 of file fileXio_iop.c.
 {
         int OldState;
         printf("fileXio: fileXio RPC Server v1.00\nCopyright (c) 2003 adresd\n");
         #ifdef DEBUG
                 printf("fileXio: RPC Initialize\n");
         #endif
         SifInitRpc(0);
         RWBufferSize=DEFAULT_RWSIZE;
         CpuSuspendIntr(&OldState);
         rwbuf = AllocSysMemory(ALLOC_FIRST, RWBufferSize, NULL);
         CpuResumeIntr(OldState);
         if (rwbuf == NULL)
         {
                 #ifdef DEBUG
                         printf("Failed to allocate memory for RW buffer!\n");
                 #endif
                 SleepThread();
         }
         SifSetRpcQueue(&qd, GetThreadId());
         SifRegisterRpc(&sd0, FILEXIO_IRX, &fileXio_rpc_server, fileXio_rpc_buffer, NULL, NULL, &qd);
         SifRpcLoop(&qd);
 }
References ALLOC_FIRST, AllocSysMemory(), CpuResumeIntr(), CpuSuspendIntr(), DEFAULT_RWSIZE, FILEXIO_IRX, fileXio_rpc_buffer, fileXio_rpc_server(), GetThreadId(), NULL, printf(), qd, rwbuf, RWBufferSize, sd0, SifInitRpc, SifRegisterRpc, SifRpcLoop, SifSetRpcQueue, and SleepThread().
Referenced by _start().
fileXio_Write_RPC()
static int fileXio_Write_RPC (int outfd, const char * write_buf, int write_size, int mis, u8 * misbuf) static
Definition at line 293 of file fileXio_iop.c.
 {
      SifRpcReceiveData_t rdata;
      int left;
      int wlen;
      int writelen;
      int pos;
      int total;
         left  = write_size;
         total = 0;
         if (mis > 0)
       {
                 wlen=write(outfd, misbuf, mis);
                 if (wlen != mis)
             {
                         if (wlen > 0)
                                 total += wlen;
                         return (total);
                 }
                 total += wlen;
         }
         left-=mis;
         pos=(int)write_buf+mis;
         while(left){
                 writelen = MIN(RWBufferSize, left);
                 SifRpcGetOtherData(&rdata, (void *)pos, rwbuf, writelen, 0);
                 wlen=write(outfd, rwbuf, writelen);
                 if (wlen != writelen){
                         if (wlen>0)
                                 total+=wlen;
                         return (total);
                 }
                 left -=writelen;
                 pos  +=writelen;
                 total+=writelen;
         }
         return (total);
 }
References MIN, pos, rwbuf, RWBufferSize, SifRpcGetOtherData, and write().
Referenced by fileXioRpc_Write().
fileXioRpc_AddDrv()
static void * fileXioRpc_AddDrv (unsigned int * sbuff) static
Definition at line 843 of file fileXio_iop.c.
 {
         int ret=-1;
         #ifdef DEBUG
                 printf("RPC AddDrv Request\n");
         #endif
         //      BODY
         sbuff[0] = ret;
         return sbuff;
 }
References printf().
Referenced by fileXio_rpc_server().
fileXioRpc_ChDir()
void * fileXioRpc_ChDir (unsigned int * sbuff) static
Definition at line 670 of file fileXio_iop.c.
 {
         int ret;
         #ifdef DEBUG
                 printf("RPC ChDir Request\n");
         #endif
         ret=chdir((char*)sbuff);
         sbuff[0] = ret;
         return sbuff;
 }
References chdir(), and printf().
Referenced by fileXio_rpc_server().
fileXioRpc_ChStat()
static void * fileXioRpc_ChStat (unsigned int * sbuff) static
Definition at line 795 of file fileXio_iop.c.
 {
         int ret=-1;
         struct fxio_chstat_packet *packet=(struct fxio_chstat_packet*)sbuff;
         #ifdef DEBUG
                 printf("RPC ChStat Request\n");
         #endif
       ret=fileXio_chstat_RPC(packet->pathname, packet->stat, packet->mask);
         sbuff[0] = ret;
         return sbuff;
 }
References fileXio_chstat_RPC(), fxio_chstat_packet::mask, fxio_chstat_packet::pathname, printf(), and fxio_chstat_packet::stat.
Referenced by fileXio_rpc_server().
fileXioRpc_Close()
static void * fileXioRpc_Close (unsigned int * sbuff) static
Definition at line 700 of file fileXio_iop.c.
 {
         int ret;
         struct fxio_close_packet *packet=(struct fxio_close_packet*)sbuff;
         #ifdef DEBUG
                 printf("RPC Close Request\n");
         #endif
         ret=close(packet->fd);
         sbuff[0] = ret;
         return sbuff;
 }
References close(), fxio_close_packet::fd, and printf().
Referenced by fileXio_rpc_server().
fileXioRpc_CopyFile()
static void * fileXioRpc_CopyFile (unsigned int * sbuff) static
Definition at line 558 of file fileXio_iop.c.
 {
         int ret;
         struct fxio_copyfile_packet *packet=(struct fxio_copyfile_packet*)sbuff;
         ret=fileXio_CopyFile_RPC(
                 packet->source,         // source filename
                 packet->dest,           // dest filename
                 packet->mode            // mode
                 );
         sbuff[0] = ret;
         return sbuff;
 }
References fxio_copyfile_packet::dest, fileXio_CopyFile_RPC(), fxio_copyfile_packet::mode, and fxio_copyfile_packet::source.
Referenced by fileXio_rpc_server().
fileXioRpc_Dclose()
static void * fileXioRpc_Dclose (unsigned int * sbuff) static
Definition at line 1005 of file fileXio_iop.c.
 {
         int ret;
         struct fxio_close_packet *packet=(struct fxio_close_packet*)sbuff;
         #ifdef DEBUG
                 printf("RPC Dclose Request\n");
         #endif
         ret=dclose(packet->fd);
         sbuff[0] = ret;
         return sbuff;
 }
References dclose(), fxio_close_packet::fd, and printf().
Referenced by fileXio_rpc_server().
fileXioRpc_DelDrv()
static void * fileXioRpc_DelDrv (unsigned int * sbuff) static
Definition at line 856 of file fileXio_iop.c.
 {
         int ret=-1;
         #ifdef DEBUG
                 printf("RPC DelDrv Request\n");
         #endif
 //      ret=deldrv((char *)&sbuff[0/4]);
         sbuff[0] = ret;
         return sbuff;
 }
References printf().
Referenced by fileXio_rpc_server().
fileXioRpc_Devctl()
static void * fileXioRpc_Devctl (unsigned int * sbuff) static
Definition at line 885 of file fileXio_iop.c.
 {
         struct fxio_devctl_packet *packet = (struct fxio_devctl_packet *)sbuff;
         struct fxio_ctl_return_pkt *ret_buf = (struct fxio_ctl_return_pkt *)rwbuf;
         SifDmaTransfer_t dmatrans;
         int intStatus;
         int ret;
         #ifdef DEBUG
                 printf("RPC Devctl Request\n");
         #endif
         ret = devctl(packet->name, packet->cmd, packet->arg, packet->arglen, ret_buf->buf, packet->buflen);
         // Transfer buffer back to EE
         if(packet->buflen != 0)
         {
                 dmatrans.src = ret_buf;
                 dmatrans.dest = packet->intr_data;
                 dmatrans.attr = 0;
                 dmatrans.size = sizeof(struct fxio_ctl_return_pkt);
                 ret_buf->dest = packet->buf;
                 // EE is expecting data.. on error, simply use size of 0 so no data is copied.
                 if(ret >= 0)
                         ret_buf->len = packet->buflen;
                 else
                         ret_buf->len = 0;
                 CpuSuspendIntr(&intStatus);
                 SifSetDma(&dmatrans, 1);
                 CpuResumeIntr(intStatus);
         }
         sbuff[0] = ret;
         return sbuff;
 }
References fxio_devctl_packet::arg, fxio_devctl_packet::arglen, SifDmaTransfer_t::attr, fxio_devctl_packet::buf, fxio_ctl_return_pkt::buf, fxio_devctl_packet::buflen, fxio_devctl_packet::cmd, CpuResumeIntr(), CpuSuspendIntr(), fxio_ctl_return_pkt::dest, SifDmaTransfer_t::dest, devctl(), fxio_devctl_packet::intr_data, fxio_ctl_return_pkt::len, fxio_devctl_packet::name, printf(), rwbuf, SifSetDma, SifDmaTransfer_t::size, and SifDmaTransfer_t::src.
Referenced by fileXio_rpc_server().
fileXioRpc_Dopen()
static void * fileXioRpc_Dopen (unsigned int * sbuff) static
Definition at line 979 of file fileXio_iop.c.
 {
         int ret;
         struct fxio_pathsel_packet *packet=(struct fxio_pathsel_packet*)sbuff;
         #ifdef DEBUG
                 printf("RPC Dopen Request\n");
         #endif
         ret=dopen(packet->pathname);
         sbuff[0] = ret;
         return sbuff;
 }
References dopen(), fxio_pathsel_packet::pathname, and printf().
Referenced by fileXio_rpc_server().
fileXioRpc_Dread()
static void * fileXioRpc_Dread (unsigned int * sbuff) static
Definition at line 992 of file fileXio_iop.c.
 {
         int ret=-1;
         struct fxio_dread_packet *packet=(struct fxio_dread_packet*)sbuff;
         #ifdef DEBUG
                 printf("RPC Dread Request\n");
         #endif
         ret=fileXio_dread_RPC(packet->fd, packet->dirent);
         sbuff[0] = ret;
         return sbuff;
 }
References fxio_dread_packet::dirent, fxio_dread_packet::fd, fileXio_dread_RPC(), and printf().
Referenced by fileXio_rpc_server().
fileXioRpc_Format()
static void * fileXioRpc_Format (unsigned int * sbuff) static
Definition at line 829 of file fileXio_iop.c.
 {
         int ret;
         struct fxio_format_packet *packet=(struct fxio_format_packet*)sbuff;
         #ifdef DEBUG
                 printf("RPC Format Request\n");
         #endif
         ret=format(packet->device, packet->blockDevice, packet->args, packet->arglen);
         sbuff[0] = ret;
         return sbuff;
 }
References fxio_format_packet::arglen, fxio_format_packet::args, fxio_format_packet::blockDevice, fxio_format_packet::device, format(), and printf().
Referenced by fileXio_rpc_server().
fileXioRpc_GetDeviceList()
static void * fileXioRpc_GetDeviceList (unsigned int * sbuff) static
Definition at line 487 of file fileXio_iop.c.
 {
         int ret;
         struct fxio_devlist_packet *packet=(struct fxio_devlist_packet*)sbuff;
         ret=fileXio_GetDeviceList_RPC(
                 packet->deviceEntry,
                 packet->reqEntries
                 );
         sbuff[0] = ret;
         return sbuff;
 }
References fxio_devlist_packet::deviceEntry, fileXio_GetDeviceList_RPC(), and fxio_devlist_packet::reqEntries.
Referenced by fileXio_rpc_server().
fileXioRpc_Getdir()
static void * fileXioRpc_Getdir (unsigned int * sbuff) static
Definition at line 504 of file fileXio_iop.c.
 {
         int ret;
         struct fxio_getdir_packet *packet=(struct fxio_getdir_packet*)sbuff;
         ret=fileXio_GetDir_RPC(
                 packet->pathname,
                 packet->dirEntry,
                 packet->reqEntries
                 );
         sbuff[0] = ret;
         return sbuff;
 }
References fxio_getdir_packet::dirEntry, fileXio_GetDir_RPC(), fxio_getdir_packet::pathname, and fxio_getdir_packet::reqEntries.
Referenced by fileXio_rpc_server().
fileXioRpc_GetStat()
static void * fileXioRpc_GetStat (unsigned int * sbuff) static
Definition at line 811 of file fileXio_iop.c.
 {
         int ret=-1;
         struct fxio_getstat_packet *packet=(struct fxio_getstat_packet*)sbuff;
         #ifdef DEBUG
                 printf("RPC GetStat Request\n");
         #endif
         ret=fileXio_getstat_RPC(packet->pathname, packet->stat);
         sbuff[0] = ret;
         return sbuff;
 }
References fileXio_getstat_RPC(), fxio_getstat_packet::pathname, printf(), and fxio_getstat_packet::stat.
Referenced by fileXio_rpc_server().
fileXioRpc_Ioctl()
static void * fileXioRpc_Ioctl (unsigned int * sbuff) static
Definition at line 925 of file fileXio_iop.c.
 {
         struct fxio_ioctl_packet *packet = (struct fxio_ioctl_packet *)sbuff;
         int ret;
         #ifdef DEBUG
                 printf("RPC Ioctl Request\n");
         #endif
         //      BODY
         ret=ioctl(packet->fd, packet->cmd, packet->arg);
         sbuff[0] = ret;
         return sbuff;
 }
References fxio_ioctl_packet::arg, fxio_ioctl_packet::cmd, fxio_ioctl_packet::fd, ioctl(), and printf().
Referenced by fileXio_rpc_server().
fileXioRpc_Ioctl2()
static void * fileXioRpc_Ioctl2 (unsigned int * sbuff) static
Definition at line 940 of file fileXio_iop.c.
 {
         struct fxio_ioctl2_packet *packet = (struct fxio_ioctl2_packet *)sbuff;
         struct fxio_ctl_return_pkt *ret_buf = (struct fxio_ctl_return_pkt *)rwbuf;
         SifDmaTransfer_t dmatrans;
         int intStatus;
         int ret;
         #ifdef DEBUG
                 printf("RPC ioctl2 Request\n");
         #endif
         ret = ioctl2(packet->fd, packet->cmd, packet->arg, packet->arglen, ret_buf->buf, packet->buflen);
         // Transfer buffer back to EE
         if(packet->buflen != 0)
         {
                 dmatrans.src = ret_buf;
                 dmatrans.dest = packet->intr_data;
                 dmatrans.attr = 0;
                 dmatrans.size = sizeof(struct fxio_ctl_return_pkt);
                 ret_buf->dest = packet->buf;
                 // EE is expecting data.. on error, simply use size of 0 so no data is copied.
                 if(ret >= 0)
                         ret_buf->len = packet->buflen;
                 else
                         ret_buf->len = 0;
                 CpuSuspendIntr(&intStatus);
                 SifSetDma(&dmatrans, 1);
                 CpuResumeIntr(intStatus);
         }
         sbuff[0] = ret;
         return sbuff;
 }
References fxio_ioctl2_packet::arg, fxio_ioctl2_packet::arglen, SifDmaTransfer_t::attr, fxio_ioctl2_packet::buf, fxio_ctl_return_pkt::buf, fxio_ioctl2_packet::buflen, fxio_ioctl2_packet::cmd, CpuResumeIntr(), CpuSuspendIntr(), fxio_ctl_return_pkt::dest, SifDmaTransfer_t::dest, fxio_ioctl2_packet::fd, fxio_ioctl2_packet::intr_data, ioctl2(), fxio_ctl_return_pkt::len, printf(), rwbuf, SifSetDma, SifDmaTransfer_t::size, and SifDmaTransfer_t::src.
Referenced by fileXio_rpc_server().
fileXioRpc_Lseek()
static void * fileXioRpc_Lseek (unsigned int * sbuff) static
Definition at line 753 of file fileXio_iop.c.
 {
         int ret;
         struct fxio_lseek_packet *packet=(struct fxio_lseek_packet*)sbuff;
         #ifdef DEBUG
                 printf("RPC Lseek Request\n");
         #endif
         ret=lseek(packet->fd, (long int)packet->offset, packet->whence);
         sbuff[0] = ret;
         return sbuff;
 }
References fxio_lseek_packet::fd, lseek(), fxio_lseek_packet::offset, printf(), and fxio_lseek_packet::whence.
Referenced by fileXio_rpc_server().
fileXioRpc_Lseek64()
static void * fileXioRpc_Lseek64 (unsigned int * sbuff) static
Definition at line 770 of file fileXio_iop.c.
 {
         long long ret;
         struct fxio_lseek64_packet *packet=(struct fxio_lseek64_packet*)sbuff;
         struct fxio_lseek64_return_pkt *ret_packet=(struct fxio_lseek64_return_pkt*)sbuff;
         #ifdef DEBUG
                 printf("RPC Lseek64 Request\n");
         #endif
         long long offsetHI = packet->offset_hi;
         offsetHI = offsetHI << 32;
         long long offset = offsetHI | packet->offset_lo;
         ret=lseek64(packet->fd, offset, packet->whence);
         ret_packet->pos_lo = (u32)(ret & 0xffffffff);
         ret_packet->pos_hi = (u32)((ret >> 32) & 0xffffffff);
         return sbuff;
 }
References fxio_lseek64_packet::fd, lseek64(), fxio_lseek64_packet::offset_hi, fxio_lseek64_packet::offset_lo, fxio_lseek64_return_pkt::pos_hi, fxio_lseek64_return_pkt::pos_lo, printf(), and fxio_lseek64_packet::whence.
Referenced by fileXio_rpc_server().
fileXioRpc_MkDir()
static void * fileXioRpc_MkDir (unsigned int * sbuff) static
Definition at line 576 of file fileXio_iop.c.
 {
         int ret;
         struct fxio_mkdir_packet *packet=(struct fxio_mkdir_packet*)sbuff;
         #ifdef DEBUG
                 printf("RPC MkDir Request\n");
         #endif
         ret=mkdir(packet->pathname, packet->mode);
         sbuff[0] = ret;
         return sbuff;
 }
References mkdir(), fxio_mkdir_packet::mode, fxio_mkdir_packet::pathname, and printf().
Referenced by fileXio_rpc_server().
fileXioRpc_Mount()
static void * fileXioRpc_Mount (unsigned int * sbuff) static
Definition at line 521 of file fileXio_iop.c.
 {
         struct fxio_mount_packet *packet=(struct fxio_mount_packet*)sbuff;
         int ret;
         #ifdef DEBUG
                 printf("RPC Mount Request\n");
         #endif
         ret=fileXio_Mount_RPC(
                 packet->blockdevice,            // mount format string
                 packet->mountpoint,             // mount point
                 packet->flags                   // flag (normal,readonly,robust)
                 );
         sbuff[0] = ret;
         return sbuff;
 }
References fxio_mount_packet::blockdevice, fileXio_Mount_RPC(), fxio_mount_packet::flags, fxio_mount_packet::mountpoint, and printf().
Referenced by fileXio_rpc_server().
fileXioRpc_Open()
static void * fileXioRpc_Open (unsigned int * sbuff) static
Definition at line 685 of file fileXio_iop.c.
 {
         int ret;
         struct fxio_open_packet *packet=(struct fxio_open_packet*)sbuff;
         #ifdef DEBUG
                 printf("RPC Open Request\n");
         #endif
         ret=open(packet->pathname, packet->flags, packet->mode);
         sbuff[0] = ret;
         return sbuff;
 }
References fxio_open_packet::flags, fxio_open_packet::mode, open(), fxio_open_packet::pathname, and printf().
Referenced by fileXio_rpc_server().
fileXioRpc_Read()
static void * fileXioRpc_Read (unsigned int * sbuff) static
Definition at line 717 of file fileXio_iop.c.
 {
         int ret;
         struct fxio_read_packet *packet=(struct fxio_read_packet*)sbuff;
         #ifdef DEBUG
                 printf("RPC Read Request\n");
         #endif
         ret=fileXio_Read_RPC(packet->fd, packet->buffer, packet->size, packet->intrData);
         sbuff[0] = ret;
         return sbuff;
 }
References fxio_read_packet::buffer, fxio_read_packet::fd, fileXio_Read_RPC(), fxio_read_packet::intrData, printf(), and fxio_read_packet::size.
Referenced by fileXio_rpc_server().
fileXioRpc_ReadLink()
static void * fileXioRpc_ReadLink (unsigned int * sbuff) static
Definition at line 655 of file fileXio_iop.c.
 {
         int ret;
         struct fxio_readlink_packet *packet=(struct fxio_readlink_packet*)sbuff;
         #ifdef DEBUG
                 printf("RPC ReadLink Request\n");
         #endif
         ret=readlink(packet->source, packet->buffer, packet->buflen);
         sbuff[0] = ret;
         return sbuff;
 }
References fxio_readlink_packet::buffer, fxio_readlink_packet::buflen, printf(), readlink(), and fxio_readlink_packet::source.
Referenced by fileXio_rpc_server().
fileXioRpc_Remove()
static void * fileXioRpc_Remove (unsigned int * sbuff) static
Definition at line 606 of file fileXio_iop.c.
 {
         int ret;
         struct fxio_pathsel_packet *packet=(struct fxio_pathsel_packet*)sbuff;
         #ifdef DEBUG
                 printf("RPC Remove Request\n");
         #endif
         ret=remove(packet->pathname);
         sbuff[0] = ret;
         return sbuff;
 }
References fxio_pathsel_packet::pathname, printf(), and remove().
Referenced by fileXio_rpc_server().
fileXioRpc_Rename()
static void * fileXioRpc_Rename (unsigned int * sbuff) static
Definition at line 622 of file fileXio_iop.c.
 {
         int ret;
         struct fxio_rename_packet *packet=(struct fxio_rename_packet*)sbuff;
         #ifdef DEBUG
                 printf("RPC Rename Request\n");
         #endif
         ret=rename(packet->source, packet->dest);
         sbuff[0] = ret;
         return sbuff;
 }
References fxio_rename_packet::dest, printf(), rename(), and fxio_rename_packet::source.
Referenced by fileXio_rpc_server().
fileXioRpc_RmDir()
static void * fileXioRpc_RmDir (unsigned int * sbuff) static
Definition at line 591 of file fileXio_iop.c.
 {
         int ret;
         struct fxio_pathsel_packet *packet=(struct fxio_pathsel_packet*)sbuff;
         #ifdef DEBUG
                 printf("RPC RmDir Request\n");
         #endif
         ret=rmdir(packet->pathname);
         sbuff[0] = ret;
         return sbuff;
 }
References fxio_pathsel_packet::pathname, printf(), and rmdir().
Referenced by fileXio_rpc_server().
filexioRpc_SetRWBufferSize()
static void * filexioRpc_SetRWBufferSize (void * sbuff) static
Definition at line 1052 of file fileXio_iop.c.
 {
         int OldState;
         if(rwbuf!=NULL){
                 CpuSuspendIntr(&OldState);
                 FreeSysMemory(rwbuf);
                 CpuResumeIntr(OldState);
         }
         RWBufferSize=((struct fxio_rwbuff*)sbuff)->size;
         CpuSuspendIntr(&OldState);
         rwbuf=AllocSysMemory(ALLOC_FIRST, RWBufferSize, NULL);
         CpuResumeIntr(OldState);
         ((int*)sbuff)[0] = rwbuf!=NULL?0:-ENOMEM;
         return sbuff;
 }
References ALLOC_FIRST, AllocSysMemory(), CpuResumeIntr(), CpuSuspendIntr(), ENOMEM, FreeSysMemory(), NULL, rwbuf, and RWBufferSize.
Referenced by fileXio_rpc_server().
fileXioRpc_Stop()
static void * fileXioRpc_Stop (void) static
Definition at line 476 of file fileXio_iop.c.
 {
         #ifdef DEBUG
                 printf("RPC Stop Request\n");
         #endif
         return NULL;
 }
References NULL, and printf().
Referenced by fileXio_rpc_server().
fileXioRpc_SymLink()
static void * fileXioRpc_SymLink (unsigned int * sbuff) static
Definition at line 638 of file fileXio_iop.c.
 {
         int ret;
         struct fxio_rename_packet *packet=(struct fxio_rename_packet*)sbuff;
         #ifdef DEBUG
                 printf("RPC SymLink Request\n");
         #endif
         ret=symlink(packet->source, packet->dest);
         sbuff[0] = ret;
         return sbuff;
 }
References fxio_rename_packet::dest, printf(), fxio_rename_packet::source, and symlink().
Referenced by fileXio_rpc_server().
fileXioRpc_Sync()
static void * fileXioRpc_Sync (unsigned int * sbuff) static
Definition at line 870 of file fileXio_iop.c.
 {
         int ret;
         struct fxio_sync_packet *packet=(struct fxio_sync_packet*)sbuff;
         #ifdef DEBUG
                 printf("RPC Sync Request\n");
         #endif
         ret=sync(packet->device, packet->flags);
         sbuff[0] = ret;
         return sbuff;
 }
References fxio_sync_packet::device, fxio_sync_packet::flags, printf(), and sync().
Referenced by fileXio_rpc_server().
fileXioRpc_uMount()
static void * fileXioRpc_uMount (unsigned int * sbuff) static
Definition at line 542 of file fileXio_iop.c.
 {
         int ret;
         struct fxio_unmount_packet *packet=(struct fxio_unmount_packet*)sbuff;
         #ifdef DEBUG
                 printf("RPC uMount Request\n");
         #endif
         ret=umount(packet->mountpoint);
         sbuff[0] = ret;
         return sbuff;
 }
References fxio_unmount_packet::mountpoint, printf(), and umount().
Referenced by fileXio_rpc_server().
fileXioRpc_Write()
static void * fileXioRpc_Write (unsigned int * sbuff) static
Definition at line 735 of file fileXio_iop.c.
 {
         int ret;
         struct fxio_write_packet *packet=(struct fxio_write_packet*)sbuff;
         #ifdef DEBUG
                 printf("RPC Write Request\n");
         #endif
         ret=fileXio_Write_RPC(packet->fd, packet->buffer, packet->size,
                             packet->unalignedDataLen, packet->unalignedData);
         sbuff[0] = ret;
         return sbuff;
 }
References fxio_write_packet::buffer, fxio_write_packet::fd, fileXio_Write_RPC(), printf(), fxio_write_packet::size, fxio_write_packet::unalignedData, and fxio_write_packet::unalignedDataLen.
Referenced by fileXio_rpc_server().
IRX_ID()
IRX_ID (MODNAME , 1 , 2)
Variable Documentation
fileXio_rpc_buffer
unsigned char fileXio_rpc_buffer[0x4C00] static
Definition at line 48 of file fileXio_iop.c.
Referenced by fileXio_Thread().
qd
struct t_SifRpcDataQueue qd
Definition at line 48 of file fileXio_iop.c.
Referenced by fileXio_Thread().
rests
rests_pkt rests static
Definition at line 52 of file fileXio_iop.c.
Referenced by fileXio_Read_RPC().
rwbuf
void* rwbuf = NULL static
Definition at line 43 of file fileXio_iop.c.
Referenced by fileXio_CopyFile_RPC(), fileXio_Read_RPC(), fileXio_Thread(), fileXio_Write_RPC(), fileXioRpc_Devctl(), fileXioRpc_Ioctl2(), and filexioRpc_SetRWBufferSize().
RWBufferSize
unsigned int RWBufferSize =DEFAULT_RWSIZE static
Definition at line 44 of file fileXio_iop.c.
Referenced by fileXio_CopyFile_RPC(), fileXio_Read_RPC(), fileXio_Thread(), fileXio_Write_RPC(), and filexioRpc_SetRWBufferSize().
sd0
struct t_SifRpcServerData sd0
Definition at line 48 of file fileXio_iop.c.
Referenced by fileXio_Thread().