ps2sdk: iop/system/padman/src/freepad.h File Reference
freepad.h File Reference
#include "irx.h"
#include "types.h"
Data Structures
struct vblankData_t
struct ee_paddata_t
struct padState_t
Macros
#define MODNAME "freepad"
#define M_PRINTF(format, args...) printf(MODNAME ": " format, ## args)
#define M_KPRINTF(format, args...) Kprintf(MODNAME ": " format, ## args)
#define D_PRINTF(a...) (void)0
#define PADMAN_THPRI_LO 46
#define PADMAN_THPRI_HI 20
#define SB_STAT *((volatile unsigned int*)0xBD000040)
#define PAD_STATE_DISCONN 0x00
#define PAD_STATE_FINDPAD 0x01
#define PAD_STATE_FINDCTP1 0x02
#define PAD_STATE_EXECCMD 0x05
#define PAD_STATE_STABLE 0x06
#define PAD_STATE_ERROR 0x07
#define PAD_RSTAT_COMPLETE 0x00
#define PAD_RSTAT_FAILED 0x01
#define PAD_RSTAT_BUSY 0x02
#define PAD_TYPE_NEJICON 0x2
#define PAD_TYPE_KONAMIGUN 0x3
#define PAD_TYPE_DIGITAL 0x4
#define PAD_TYPE_ANALOG 0x5
#define PAD_TYPE_NAMCOGUN 0x6
#define PAD_TYPE_DUALSHOCK 0x7
#define PAD_MODEL_DUALSHOCK 0x1
#define PAD_MODEL_DUALSHOCK2 0x3
#define MODE_CONFIG_NO_PAD 0x0
#define MODE_CONFIG_QUERY_PAD 0x1
#define MODE_CONFIG_READY 0x2
#define TASK_NONE 0
#define TASK_UPDATE_PAD 1
#define TASK_QUERY_PAD 2
#define TASK_PORT_CLOSE 3
#define TASK_SET_MAIN_MODE 4
#define TASK_SET_ACT_ALIGN 5
#define TASK_SET_BUTTON_INFO 6
#define TASK_SET_VREF_PARAM 7
#define EF_UPDATE_PAD 0x0001
#define EF_QUERY_PAD 0x0002
#define EF_SET_MAIN_MODE 0x0008
#define EF_SET_ACT_ALIGN 0x0010
#define EF_SET_SET_BUTTON_INFO 0x0020
#define EF_SET_VREF_PARAM 0x0040
#define EF_PAD_TRANSFER_START 0x0080
#define EF_PAD_TRANSFER_DONE 0x0100
#define EF_TASK_DONE 0x0200
#define EF_PORT_CLOSE 0x0400
#define EF_EXIT_THREAD 0x1000
#define EF_VB_TRANSFER 0x0001
#define EF_VB_TRANSFER_DONE 0x0004
#define EF_VB_WAIT_THREAD_EXIT 0x0008
Functions
void WaitClearEvent (int eventflag, u32 bits, int mode, u32 *resbits_out)
int VblankStart (void *arg)
int VblankEnd (void *arg)
s32 padInit (void *ee_addr)
s32 padEnd (void)
s32 padPortClose (s32 port, s32 slot, s32 wait)
s32 padPortOpen (s32 port, s32 slot, s32 pad_area_ee_addr, u32 *buf)
u32 padSetMainMode (u32 port, u32 slot, u32 mode, u32 lock)
u32 padSetActDirect (u32 port, u32 slot, u8 *actData)
u32 padSetActAlign (u32 port, u32 slot, u8 *actData)
u32 padGetButtonMask (u32 port, u32 slot)
u32 padSetButtonInfo (u32 port, u32 slot, u32 info)
u32 padSetVrefParam (u32 port, u32 slot, u8 *vparam)
s32 padInfoAct (u32 port, u32 slot, s32 act, u32 val)
s32 padInfoComb (u32 port, u32 slot, s32 listno, u32 offs)
s32 padInfoMode (u32 port, u32 slot, s32 term, u32 offs)
u32 padGetPortMax (void)
u32 padGetSlotMax (u32 port)
u32 padGetModVersion (void)
Detailed Description
IOP pad driver
Definition in file freepad.h.
Macro Definition Documentation
D_PRINTF
#define D_PRINTF (a...) (void)0
Definition at line 25 of file freepad.h.
EF_EXIT_THREAD
#define EF_EXIT_THREAD 0x1000
Definition at line 89 of file freepad.h.
EF_PAD_TRANSFER_DONE
#define EF_PAD_TRANSFER_DONE 0x0100
Definition at line 86 of file freepad.h.
EF_PAD_TRANSFER_START
#define EF_PAD_TRANSFER_START 0x0080
Definition at line 85 of file freepad.h.
EF_PORT_CLOSE
#define EF_PORT_CLOSE 0x0400
Definition at line 88 of file freepad.h.
EF_QUERY_PAD
#define EF_QUERY_PAD 0x0002
Definition at line 79 of file freepad.h.
EF_SET_ACT_ALIGN
#define EF_SET_ACT_ALIGN 0x0010
Definition at line 82 of file freepad.h.
EF_SET_MAIN_MODE
#define EF_SET_MAIN_MODE 0x0008
Definition at line 81 of file freepad.h.
EF_SET_SET_BUTTON_INFO
#define EF_SET_SET_BUTTON_INFO 0x0020
Definition at line 83 of file freepad.h.
EF_SET_VREF_PARAM
#define EF_SET_VREF_PARAM 0x0040
Definition at line 84 of file freepad.h.
EF_TASK_DONE
#define EF_TASK_DONE 0x0200
Definition at line 87 of file freepad.h.
EF_UPDATE_PAD
#define EF_UPDATE_PAD 0x0001
Definition at line 78 of file freepad.h.
EF_VB_TRANSFER
#define EF_VB_TRANSFER 0x0001
Definition at line 92 of file freepad.h.
EF_VB_TRANSFER_DONE
#define EF_VB_TRANSFER_DONE 0x0004
Definition at line 93 of file freepad.h.
EF_VB_WAIT_THREAD_EXIT
#define EF_VB_WAIT_THREAD_EXIT 0x0008
Definition at line 94 of file freepad.h.
M_KPRINTF
#define M_KPRINTF (format, args...) Kprintf(MODNAME ": " format, ## args)
Definition at line 20 of file freepad.h.
M_PRINTF
#define M_PRINTF (format, args...) printf(MODNAME ": " format, ## args)
Definition at line 19 of file freepad.h.
MODE_CONFIG_NO_PAD
#define MODE_CONFIG_NO_PAD 0x0
Definition at line 63 of file freepad.h.
MODE_CONFIG_QUERY_PAD
#define MODE_CONFIG_QUERY_PAD 0x1
Definition at line 64 of file freepad.h.
MODE_CONFIG_READY
#define MODE_CONFIG_READY 0x2
Definition at line 65 of file freepad.h.
MODNAME
#define MODNAME "freepad"
Definition at line 18 of file freepad.h.
PAD_MODEL_DUALSHOCK
#define PAD_MODEL_DUALSHOCK 0x1
Definition at line 60 of file freepad.h.
PAD_MODEL_DUALSHOCK2
#define PAD_MODEL_DUALSHOCK2 0x3
Definition at line 61 of file freepad.h.
PAD_RSTAT_BUSY
#define PAD_RSTAT_BUSY 0x02
Definition at line 48 of file freepad.h.
PAD_RSTAT_COMPLETE
#define PAD_RSTAT_COMPLETE 0x00
Definition at line 46 of file freepad.h.
PAD_RSTAT_FAILED
#define PAD_RSTAT_FAILED 0x01
Definition at line 47 of file freepad.h.
PAD_STATE_DISCONN
#define PAD_STATE_DISCONN 0x00
Definition at line 36 of file freepad.h.
PAD_STATE_ERROR
#define PAD_STATE_ERROR 0x07
Definition at line 41 of file freepad.h.
PAD_STATE_EXECCMD
#define PAD_STATE_EXECCMD 0x05
Definition at line 39 of file freepad.h.
PAD_STATE_FINDCTP1
#define PAD_STATE_FINDCTP1 0x02
Definition at line 38 of file freepad.h.
PAD_STATE_FINDPAD
#define PAD_STATE_FINDPAD 0x01
Definition at line 37 of file freepad.h.
PAD_STATE_STABLE
#define PAD_STATE_STABLE 0x06
Definition at line 40 of file freepad.h.
PAD_TYPE_ANALOG
#define PAD_TYPE_ANALOG 0x5
Definition at line 56 of file freepad.h.
PAD_TYPE_DIGITAL
#define PAD_TYPE_DIGITAL 0x4
Definition at line 55 of file freepad.h.
PAD_TYPE_DUALSHOCK
#define PAD_TYPE_DUALSHOCK 0x7
Definition at line 58 of file freepad.h.
PAD_TYPE_KONAMIGUN
#define PAD_TYPE_KONAMIGUN 0x3
Definition at line 54 of file freepad.h.
PAD_TYPE_NAMCOGUN
#define PAD_TYPE_NAMCOGUN 0x6
Definition at line 57 of file freepad.h.
PAD_TYPE_NEJICON
#define PAD_TYPE_NEJICON 0x2
Definition at line 53 of file freepad.h.
PADMAN_THPRI_HI
#define PADMAN_THPRI_HI 20
Definition at line 29 of file freepad.h.
PADMAN_THPRI_LO
#define PADMAN_THPRI_LO 46
Definition at line 28 of file freepad.h.
SB_STAT
#define SB_STAT *((volatile unsigned int*)0xBD000040)
Definition at line 31 of file freepad.h.
TASK_NONE
#define TASK_NONE 0
Definition at line 68 of file freepad.h.
TASK_PORT_CLOSE
#define TASK_PORT_CLOSE 3
Definition at line 71 of file freepad.h.
TASK_QUERY_PAD
#define TASK_QUERY_PAD 2
Definition at line 70 of file freepad.h.
TASK_SET_ACT_ALIGN
#define TASK_SET_ACT_ALIGN 5
Definition at line 73 of file freepad.h.
TASK_SET_BUTTON_INFO
#define TASK_SET_BUTTON_INFO 6
Definition at line 74 of file freepad.h.
TASK_SET_MAIN_MODE
#define TASK_SET_MAIN_MODE 4
Definition at line 72 of file freepad.h.
TASK_SET_VREF_PARAM
#define TASK_SET_VREF_PARAM 7
Definition at line 75 of file freepad.h.
TASK_UPDATE_PAD
#define TASK_UPDATE_PAD 1
Definition at line 69 of file freepad.h.
Function Documentation
padEnd()
s32 padEnd (void)
Definition at line 38 of file padMiscFuncs.c.
 {
         if(padman_init != 0)
         {
                 int port,slot;
                 for(port = 0; port < 2; port++)
                         for(slot=0; slot < 4; slot++)
{
                                 if((openSlots[port] >> slot) & 0x1)
                                         padPortClose(port, slot, 1);
                         }
                 SetEventFlag(vblankData.eventflag, EF_EXIT_THREAD);
                 vblankData.padEnd = 1;
                 WaitEventFlag(vblankData.eventflag, EF_VB_WAIT_THREAD_EXIT, 0x11, 0);
                 DeleteThreadsEventFlag( &vblankData );
                 while(ReleaseVblankHandler(0, (void*)VblankStart) != 0)
                         M_PRINTF("Release VB_START failed.\n");
                 while(ReleaseVblankHandler(1, VblankEnd) != 0)
                         M_PRINTF("Release VB_END failed.\n");
                 padman_init = 0;
         }
         return 1;
 }
padGetButtonMask()
u32 padGetButtonMask (u32 port, u32 slot)
Definition at line 336 of file padMiscFuncs.c.
 {
         u32 ret = 0;
         if( (padState[port][slot].currentTask != TASK_UPDATE_PAD) || ( padState[port][slot].modeConfig < MODE_CONFIG_READY) )
                 return ret;
         if( padState[port][slot].model < 2)
                 return ret;
         ret  = (u32)padState[port][slot].buttonMask[0];
         ret |= (u32)padState[port][slot].buttonMask[1] << 8;
         ret |= (u32)padState[port][slot].buttonMask[2] << 16;
         ret |= (u32)padState[port][slot].buttonMask[3] << 24;
         return ret;
 }
padGetModVersion()
u32 padGetModVersion (void)
Definition at line 422 of file padMiscFuncs.c.
 {
         return _irx_id.v;
 }
References _irx_id, and irx_id::v.
Referenced by RpcGetModVersion().
padGetPortMax()
u32 padGetPortMax (void)
Definition at line 412 of file padMiscFuncs.c.
 {
         return 2;
 }
Referenced by ActDirectTotal(), and RpcPadGetPortMax().
padGetSlotMax()
u32 padGetSlotMax (u32 port)
Definition at line 417 of file padMiscFuncs.c.
 {
         return sio2_mtap_get_slot_max(port);
 }
References sio2_mtap_get_slot_max().
Referenced by ActDirectTotal(), and RpcPadGetSlotMax().
padInfoAct()
s32 padInfoAct (u32 port, u32 slot, s32 act, u32 val)
Definition at line 123 of file padMiscFuncs.c.
 {
         if(padState[port][slot].currentTask != TASK_UPDATE_PAD)
                 return 0;
         if(padState[port][slot].modeConfig < MODE_CONFIG_READY)
                 return -1;
         if(act == -1) return padState[port][slot].numActuators;
         if( act < padState[port][slot].numActuators )
         {
                 u8 *actData = padState[port][slot].actData.data[act];
                 switch(val)
                 {
                         case 1:
                                 return actData[0];
                         case 2:
                                 return actData[1];
                         case 3:
                                 return actData[2];
                         case 4:
                                 return actData[3];
                 }
         }
         return -1;
 }
padInfoComb()
s32 padInfoComb (u32 port, u32 slot, s32 listno, u32 offs)
Definition at line 153 of file padMiscFuncs.c.
 {
         if(padState[port][slot].currentTask != TASK_UPDATE_PAD)
                 return 0;
         if(padState[port][slot].modeConfig < MODE_CONFIG_READY)
                 return -1;
         if(listno == -1) return padState[port][slot].numActComb;
         if( listno < padState[port][slot].numActComb)
         {
                 u8 *combData = padState[port][slot].combData.data[listno];
                 switch(offs)
                 {
                         case -1:
                                 return combData[0];
                         case 0:
                                 return combData[1];
                         case 1:
                                 return combData[2];
                         case 2:
                                 return combData[3];
                 }
         }
         return -1;
 }
padInfoMode()
s32 padInfoMode (u32 port, u32 slot, s32 term, u32 offs)
Definition at line 183 of file padMiscFuncs.c.
 {
         if((padState[port][slot].currentTask != TASK_UPDATE_PAD) || (padState[port][slot].reqState == PAD_RSTAT_BUSY))
                 return 0;
         switch(term)
         {
                 case 2:
                         if(padState[port][slot].modeConfig == MODE_CONFIG_QUERY_PAD)
                                 return 0;
                         else
                                 return padState[port][slot].modeTable.data[padState[port][slot].modeCurOffs];
                 case 1:
                         if( padState[port][slot].modeCurId != PAD_ID_CONFIG)
                                 return (PAD_ID_HI(PAD_ID_CONFIG));
                         else
                                 return 0;
                 case 3:
                         if(padState[port][slot].modeConfig == MODE_CONFIG_QUERY_PAD)
                                 return 0;
                         else
                                 return padState[port][slot].modeCurOffs;
                 case 4:
                         if(padState[port][slot].modeConfig == MODE_CONFIG_QUERY_PAD)
                                 return 0;
                         else
{
                                 if(offs == -1)
{
                                         return padState[port][slot].numModes;
                                 }
                                 else
{
                                         u16* mode = padState[port][slot].modeTable.data;
                                         if(offs < padState[port][slot].numModes)
                                                 return mode[offs];
                                         else
                                                 return 0;
                                 }
                         }
         }
         return -1;
 }
padInit()
s32 padInit (void * ee_addr)
Definition at line 649 of file padInit.c.
 {
         iop_thread_t thread;
         int intr_state;
         iop_event_t event;
         if(padman_init == 1)
         {
                 M_PRINTF("Refresh request from EE\n.");
                 padEnd();
         }
         vblankData.padEnd = 0;
         vblankData.init = 0;
         vblankData.stopTransfer = 1;
         pad_ee_addr = ee_addr;
         pad_port = 0;
         pad_slot = 0;
         mainThreadCount2 = 0;
         pad_portdata[0] = 0;
         pad_portdata[1] = 0;
         sif_buffer[0] = 0;
         sio2cmdReset();
         sio2cmdInitFindPads();
         sio2cmdInitMouse();
         sio2cmdInitNegicon();
         sio2cmdInitKonamiGun();
         sio2cmdInitDigital();
         sio2cmdInitJoystick();
         sio2cmdInitNamcoGun();
         sio2cmdInitAnalog();
         sio2cmdInitJogcon();
         sio2cmdInitConfig();
         pdReset();
         openSlots[0] = 0;
         openSlots[1] = 0;
         event.attr = EA_MULTI;
         event.bits = 0;
         vblankData.eventflag = CreateEventFlag(&event);
         if( vblankData.eventflag == 0)
         {
                 M_PRINTF("padInit: CreateEventFlag failed (%d).\n", vblankData.eventflag);
                 return 0;
         }
         thread.attr = TH_C;
         thread.thread = &TransferThread;
         thread.stacksize = 0x800;
         thread.priority = thpri_hi;
         vblankData.tid_2 = CreateThread(&thread);
         if(vblankData.tid_2 == 0)
         {
                 M_PRINTF("padInit: CreateThread TransferThread failed (%d)\n.", vblankData.tid_2);
                 return 0;
         }
         StartThread(vblankData.tid_2, NULL);
         thread.attr = TH_C;
         thread.thread = MainThread;
         thread.stacksize = 0x1000;
         thread.priority = thpri_lo;
         vblankData.tid_1 = CreateThread(&thread);
         if(vblankData.tid_1 == 0)
         {
                 M_PRINTF("padInit: CreateThread MainThread failed (%d)\n.", vblankData.tid_1);
                 return 0;
         }
         StartThread(vblankData.tid_1, NULL);
         CpuSuspendIntr(&intr_state);
         RegisterVblankHandler(0, 16, &VblankStart, (void*)&vblankData);
         RegisterVblankHandler(1, 16, &VblankEnd, (void*)&vblankData);
         CpuResumeIntr(intr_state);      //Original BUG: was originally a call to CpuEnableIntr with intr_state as an argument
         vblankData.init = 1;
         padman_init = 1;
         return 1;
 }
padPortClose()
s32 padPortClose (s32 port, s32 slot, s32 wait)
Definition at line 71 of file padMiscFuncs.c.
 {
         if(((openSlots[port] >> slot) & 1) == 0)
         {
                 M_PRINTF("padPortClose: Port %i Slot %i is not open.\n", (int)port, (int)slot);
                 return 0;
         }
         if(padState[port][slot].reqState == PAD_RSTAT_BUSY)
         {
                 M_PRINTF("padPortClose: Port %i Slot %i request failed.\n", (int)port, (int)slot);
                 return 0;
         }
         padState[port][slot].runTask = TASK_PORT_CLOSE;
         padState[port][slot].taskTid = 0;
         padState[port][slot].reqState = PAD_RSTAT_BUSY;
         if(wait)
         {
                 u32 resbits;
                 WaitEventFlag(padState[port][slot].eventflag, EF_PORT_CLOSE, 0x10, &resbits);
                 DeleteEventFlag(padState[port][slot].eventflag);
                 padState[port][slot].eventflag = 0;
         }
         return 1;
 }
Referenced by padEnd().
padPortOpen()
s32 padPortOpen (s32 port, s32 slot, s32 pad_area_ee_addr, u32 * buf)
Definition at line 648 of file padPortOpen.c.
 {
         iop_event_t event;
         iop_thread_t thread;
         if(port > 2)
         {
                 M_PRINTF("Invalid port number: %d\n", (int)port);
                 return 0;
         }
         if(slot > 4)
         {
                 M_PRINTF("Invalid slot number: %d\n", (int)port);
                 return 0;
         }
         if( (openSlots[port] >> slot) & 0x1)
         {
                 M_PRINTF("This slot is already open: (%d, %d)\n", (int)port, (int)slot);
                 return 0;
         }
         padState[port][slot].port = port;
         padState[port][slot].slot = slot;
         openSlots[port] |= 1 << slot;
         padState[port][slot].state = PAD_STATE_EXECCMD;
         padState[port][slot].modeCurId = 0;
         padState[port][slot].reqState = PAD_RSTAT_COMPLETE;
         padState[port][slot].frame = 0;
         padState[port][slot].padarea_ee_addr = pad_area_ee_addr;
         padState[port][slot].buttonDataReady = 0;
         padState[port][slot].ee_actDirectSize = 0;
         padState[port][slot].val_c6 = 0;
         padState[port][slot].currentTask = TASK_NONE;
         padState[port][slot].runTask = TASK_NONE;
         padState[port][slot].val_184 = 0;
         padState[port][slot].disconnected = 1;
         padState[port][slot].stat70bit = 0;
         event.attr = EA_MULTI;
         event.bits = 0;
         if((padState[port][slot].eventflag = CreateEventFlag(&event)) == 0)
         {
                 M_PRINTF("Port open failed (CreateEventFlag).\n");
                 return 0;
         }
         // Create UpdatePadThread
         thread.attr = TH_C;
         thread.option = (u32)&padState[port][slot];
         thread.thread = &UpdatePadThread;
         thread.stacksize = 0x600;
         thread.priority = thpri_lo;
         padState[port][slot].updatepadTid = CreateThread(&thread);
         if(padState[port][slot].updatepadTid == 0)
         {
                 M_PRINTF("Port open failed (CreateThread UpdatePadThread).\n");
                 return 0;
         }
         // Create QueryPadThread
         thread.attr = TH_C;
         thread.option = (u32)&padState[port][slot];
         thread.thread = &QueryPadThread;
         thread.stacksize = 0x600;
         thread.priority = thpri_lo;
         padState[port][slot].querypadTid = CreateThread(&thread);
         if(padState[port][slot].querypadTid == 0)
         {
                 M_PRINTF("Port open failed (CreateThread QueryPadThread).\n");
                 return 0;
         }
         // Create SetMainModeThread
         thread.attr = TH_C;
         thread.option = (u32)&padState[port][slot];
         thread.thread = &SetMainModeThread;
         thread.stacksize = 0x400;
         thread.priority = thpri_lo;
         padState[port][slot].setmainmodeTid = CreateThread(&thread);
         if(padState[port][slot].setmainmodeTid == 0)
         {
                 M_PRINTF("Port open failed (CreateThread SetMainModeThread)\n.");
                 return 0;
         }
         // Create SetActAlignThread
         thread.attr = TH_C;
         thread.option = (u32)&padState[port][slot];
         thread.thread = &SetActAlignThread;
         thread.stacksize = 0x400;
         thread.priority = thpri_lo;
         padState[port][slot].setactalignTid = CreateThread(&thread);
         if(padState[port][slot].setactalignTid == 0)
         {
                 M_PRINTF("Port open failed (CreateThread SetActAlignThread).\n");
                 return 0;
         }
         // Create SetButtonInfoThread
         thread.attr = TH_C;
         thread.option = (u32)&padState[port][slot];
         thread.thread = &SetButtonInfoThread;
         thread.stacksize = 0x400;
         thread.priority = thpri_lo;
         padState[port][slot].setbuttoninfoTid = CreateThread(&thread);
         if(padState[port][slot].setbuttoninfoTid == 0)
         {
                 M_PRINTF("Port open failed (CreateThread SetButtonInfoThread).\n");
                 return 0;
         }
         // Create SetVrefParamThread
         thread.attr = TH_C;
         thread.option = (u32)&padState[port][slot];
         thread.thread = &SetVrefParamThread;
         thread.stacksize = 0x400;
         thread.priority = thpri_lo;
         padState[port][slot].setvrefparamTid = CreateThread(&thread);
         if(padState[port][slot].setvrefparamTid == 0)
         {
                 M_PRINTF("Port open failed (CreateThread SetVrefParamThread).\n");
                 return 0;
         }
         if(padState[port][slot].currentTask < TASK_QUERY_PAD)
         {
                 StartThread(padState[port][slot].updatepadTid, NULL);
                 padState[port][slot].currentTask = TASK_UPDATE_PAD;
         }
         else
         {
                 M_PRINTF("Port open failed, busy.\n");
                 return 0;
         }
         return 1;
 }
padSetActAlign()
u32 padSetActAlign (u32 port, u32 slot, u8 * actData)
Definition at line 314 of file padMiscFuncs.c.
 {
         if( (padState[port][slot].currentTask != TASK_UPDATE_PAD) || ( padState[port][slot].modeConfig < MODE_CONFIG_READY) )
                 return 0;
         if( padState[port][slot].reqState != PAD_RSTAT_BUSY)
         {
                 int i;
                 for(i=0; i < 6; i++)
                         padState[port][slot].ee_actAlignData.data[i] = actData[i];
                 padState[port][slot].reqState = PAD_RSTAT_BUSY;
                 padState[port][slot].runTask = TASK_SET_ACT_ALIGN;
                 padState[port][slot].taskTid = padState[port][slot].setactalignTid;
                 return 1;
         }
         return 0;
 }
padSetActDirect()
u32 padSetActDirect (u32 port, u32 slot, u8 * actData)
Definition at line 290 of file padMiscFuncs.c.
 {
         if(padState[port][slot].currentTask == TASK_UPDATE_PAD)
         {
                 if( CheckAirDirectTotal(port, slot, actData) == 0)
                 {       //This doesn't seem to be ever used.
                         M_KPRINTF("Over consumpt Max [%d][%d]\n", (int)port, (int)slot);
                 }
                 else
                 {
                         int i;
                         for(i=0; i < 6; i++)
                                 padState[port][slot].ee_actDirectData.data[i] = actData[i];
                         padState[port][slot].ee_actDirectSize = 6;
                         return 1;
                 }
         }
         return 0;
 }
padSetButtonInfo()
u32 padSetButtonInfo (u32 port, u32 slot, u32 info)
Definition at line 354 of file padMiscFuncs.c.
 {
         if( (padState[port][slot].currentTask != TASK_UPDATE_PAD) || ( padState[port][slot].modeConfig < MODE_CONFIG_READY) )
                 return 0;
         if( padState[port][slot].model < 2)
                 return 0;
         if( padState[port][slot].reqState != PAD_RSTAT_BUSY)
         {
                 int i;
                 info = (info << 6) | 0x3F;
                 padState[port][slot].buttonInfo[0] = (u8)(info);
                 padState[port][slot].buttonInfo[1] = (u8)(info >> 8);
                 padState[port][slot].buttonInfo[2] = (u8)(info >> 16);
                 padState[port][slot].buttonInfo[3] = (u8)(info >> 24);
                 for(i=0; i < 11; i++)
                         padState[port][slot].modeParam[i] = 0x2;
                 padState[port][slot].reqState = PAD_RSTAT_BUSY;
                 padState[port][slot].runTask = TASK_SET_BUTTON_INFO;
                 padState[port][slot].taskTid = padState[port][slot].setbuttoninfoTid;
                 return 1;
         }
         return 0;
 }
padSetMainMode()
u32 padSetMainMode (u32 port, u32 slot, u32 mode, u32 lock)
Definition at line 101 of file padMiscFuncs.c.
 {
         if( (padState[port][slot].currentTask != TASK_UPDATE_PAD) || ( padState[port][slot].modeConfig < MODE_CONFIG_READY) )
                 return 0;
         if( mode >= padState[port][slot].numModes )
                 return 0;
         if( padState[port][slot].reqState != PAD_RSTAT_BUSY)
         {
                 padState[port][slot].mode = mode;
                 padState[port][slot].lock = lock;
                 padState[port][slot].runTask = TASK_SET_MAIN_MODE;
                 padState[port][slot].reqState = PAD_RSTAT_BUSY;
                 padState[port][slot].taskTid = padState[port][slot].setmainmodeTid;
                 return 1;
         }
         return 0;
 }
padSetVrefParam()
u32 padSetVrefParam (u32 port, u32 slot, u8 * vparam)
Definition at line 387 of file padMiscFuncs.c.
 {
         if( (padState[port][slot].currentTask != TASK_UPDATE_PAD) || ( padState[port][slot].modeConfig < MODE_CONFIG_READY) )
                 return 0;
         if( padState[port][slot].model < 2)
                 return 0;
         if( padState[port][slot].reqState != PAD_RSTAT_BUSY)
         {
                 int i;
                 for(i=0; i < 12; i++)
                         padState[port][slot].modeParam[i] = vparam[i];
                 padState[port][slot].runTask = TASK_SET_VREF_PARAM;
                 padState[port][slot].reqState = PAD_RSTAT_BUSY;
                 padState[port][slot].taskTid = padState[port][slot].setvrefparamTid;
                 return 1;
         }
         return 0;
 }
References MODE_CONFIG_READY, PAD_RSTAT_BUSY, padState, padState_t::reqState, padState_t::runTask, padState_t::setvrefparamTid, TASK_SET_VREF_PARAM, TASK_UPDATE_PAD, and padState_t::taskTid.
Referenced by RpcPadSetVrefParam().
VblankEnd()
int VblankEnd (void * arg)
Definition at line 643 of file padInit.c.
 {
         vblank_end = 1;
         return 1;
 }
References vblank_end.
Referenced by padEnd(), and padInit().
VblankStart()
int VblankStart (void * arg)
Definition at line 618 of file padInit.c.
 {
         vblankData_t *vData = arg;
         vblank_end = 0;
         vblankStartCount++;
         frame_count++;
         if((vData->init == 1) && (vData->stopTransfer == 0))
         {
                 vData->stopTransfer = 1;
                 iSetEventFlag(vData->eventflag, EF_VB_TRANSFER);
         }
         /* Wait for threads to exit and signal event to padEnd */
         if(vData->padEnd == 1)
         {
                 if( VbReferThreadStatus(vData) == 0 )
                         iSetEventFlag(vData->eventflag, EF_VB_WAIT_THREAD_EXIT);
         }
         return 1;
 }
References arg, EF_VB_TRANSFER, EF_VB_WAIT_THREAD_EXIT, vblankData_t::eventflag, frame_count, vblankData_t::init, iSetEventFlag(), vblankData_t::padEnd, vblankData_t::stopTransfer, vblank_end, vblankStartCount, and VbReferThreadStatus().
Referenced by padEnd(), and padInit().
WaitClearEvent()
void WaitClearEvent (int eventflag, u32 bits, int mode, u32 * resbits_out)
Definition at line 127 of file freepad.c.
 {
         u32 resbits;
         WaitEventFlag(eventflag, bits | EF_EXIT_THREAD, WEF_OR, &resbits);
         if( resbits & EF_EXIT_THREAD )
         {       //Yes, it's unused. Probably leftover code.
                 iop_thread_info_t tinfo;
                 ReferThreadStatus(TH_SELF, &tinfo);
                 SetEventFlag(eventflag, EF_EXIT_THREAD);
                 ExitThread();
         }
         ClearEventFlag(eventflag, ~bits);
 }
References ClearEventFlag(), EF_EXIT_THREAD, ExitThread(), ReferThreadStatus(), SetEventFlag(), TH_SELF, WaitEventFlag(), and WEF_OR.
Referenced by EnterConfigMode(), ExitConfigMode(), MainThread(), PadIsSupported(), QueryAct(), QueryButtonMask(), QueryComb(), QueryMode(), QueryModel(), QueryPadThread(), ReadData(), SetActAlign(), SetActAlignThread(), SetButtonInfo(), SetButtonInfoThread(), SetMainMode(), SetMainModeThread(), SetVrefParamThread(), TransferThread(), UpdatePadThread(), and VrefParam().