ps2sdk: iop/system/mtapman/src/freemtap.h File Reference
freemtap.h File Reference
Macros
#define MODNAME "freemtap"
#define M_PRINTF(format, args...) printf(MODNAME ": " format, ## args)
Functions
s32 InitRpcServers ()
s32 mtapPortOpen (u32 port)
s32 mtapPortClose (u32 port)
s32 mtapGetConnection (u32 port)
s32 mtapGetSlotNumber (u32 port)
s32 mtapChangeSlot (u32 port, u32 slot)
Detailed Description
IOP multitap driver
Definition in file freemtap.h.
Macro Definition Documentation
M_PRINTF
#define M_PRINTF (format, args...) printf(MODNAME ": " format, ## args)
Definition at line 16 of file freemtap.h.
MODNAME
#define MODNAME "freemtap"
Definition at line 15 of file freemtap.h.
Function Documentation
InitRpcServers()
s32 InitRpcServers ()
Definition at line 166 of file rpcservers.c.
 {
         iop_thread_t rpc_thread;
         // mtapPortOpen RPC Server
         rpc_thread.attr = TH_C;
         rpc_thread.thread = RpcThreadPortOpen;
         rpc_thread.stacksize = 0x2000;
         rpc_thread.priority = 32;
         threadid_rpc1 = CreateThread(&rpc_thread);
         if(threadid_rpc1 == 0) return 0;
         StartThread(threadid_rpc1, 0);
         // mtapPortClose RPC Server
         rpc_thread.thread = RpcThreadPortClose;
         threadid_rpc2 = CreateThread(&rpc_thread);
         if(threadid_rpc2 == 0) return 0;
         StartThread(threadid_rpc2, 0);
         // mtapGetConnection RPC Server
         rpc_thread.thread = RpcThreadGetConnection;
         threadid_rpc3 = CreateThread(&rpc_thread);
         if(threadid_rpc3 == 0) return 0;
         StartThread(threadid_rpc3, 0);
         // mtapGetSlotNumber RPC Server
         rpc_thread.thread = rpc_thread_get_slot_number;
         threadid_rpc4 = CreateThread(&rpc_thread);
         if(threadid_rpc4 == 0) return 0;
         StartThread(threadid_rpc4, 0);
         // mtapChangeSlot RPC Server
         rpc_thread.thread = rpc_thread_change_slot;
         threadid_rpc5 = CreateThread(&rpc_thread);
         if(threadid_rpc5 == 0) return 0;
         StartThread(threadid_rpc5, 0);
         return 1;
 }
References CreateThread(), rpc_thread(), rpc_thread_change_slot(), rpc_thread_get_slot_number(), RpcThreadGetConnection(), RpcThreadPortClose(), RpcThreadPortOpen(), StartThread(), TH_C, threadid_rpc1, threadid_rpc2, threadid_rpc3, threadid_rpc4, and threadid_rpc5.
Referenced by _start().
mtapChangeSlot()
s32 mtapChangeSlot (u32 port, u32 slot)
Definition at line 516 of file freemtap.c.
 {
         s32 data[4];
         u32 i;
         if(port > 4) return 0;
         if(state_open[port] == 0)
         {
                 M_PRINTF("mtap manager doesn't work\n");
                 return -1;
         }
         for(i=0; i < 4; i++)
                 data[i] = -1;
         data[port] = slot;
         sio2_mtap_transfer_init();
         change_slot(data);
         sio2_transfer_reset2();
         if(data[port] < 0)
         {
                 M_PRINTF("Failed to change slot.\n");
                 return data[port];
         }
         else
         {
                 M_PRINTF("Change slot complete.\n");
                 return 1;
         }
 }
mtapGetConnection()
s32 mtapGetConnection (u32 port)
Definition at line 495 of file freemtap.c.
 {
         return state_getcon[port];
 }
References state_getcon.
Referenced by RpcServerGetConnection().
mtapGetSlotNumber()
s32 mtapGetSlotNumber (u32 port)
Definition at line 500 of file freemtap.c.
 {
         s32 res;
         if(port > 4) return -1;
         if(state_open[port] == 0) return 1;
         res = get_slot_number(port, 10);
         if(res >= 0)
                 return res;
         else
                 return 1;
 }
mtapPortClose()
s32 mtapPortClose (u32 port)
Definition at line 487 of file freemtap.c.
 {
         state_open[port] = 0;
         state_getcon[port] = 0;
         return 1;
 }
mtapPortOpen()
s32 mtapPortOpen (u32 port)
Definition at line 462 of file freemtap.c.
 {
         if(port < 4)
         {
                 state_open[port] = 1;
                 s32 res = get_slot_number(port, 10);
                 if(res < 0)
                 {
                         state_getcon[port] = 0;
                         state_slots[port] = 1;
                         return res;
                 }
                 else
                 {
                         state_getcon[port] = 1;
                         state_slots[port] = res;
                         return 1;
                 }
         }
         return 0;
 }