ps2sdk: iop/system/padman/src/freepad.c File Reference
freepad.c File Reference
#include "irx.h"
#include "types.h"
#include "ctype.h"
#include "stdio.h"
#include "loadcore.h"
#include "sysclib.h"
#include "sysmem.h"
#include "thevent.h"
#include "thbase.h"
#include "rpcserver.h"
#include "freepad.h"
Functions
IRX_ID ("padman", 3, 6)
static int ParseParams (int argc, char *argv[])
int _start (int argc, char *argv[])
void WaitClearEvent (int eventflag, u32 bits, int mode, u32 *resbits_out)
Variables
struct irx_export_table _exp_padman
int padman_init
int thpri_hi
int thpri_lo
int vblank_end
Detailed Description
IOP pad driver
Definition in file freepad.c.
Function Documentation
_start()
int _start (int argc, char * argv[])
Definition at line 94 of file freepad.c.
 {
         padman_init = 0;
         vblank_end = 0;
         thpri_hi = PADMAN_THPRI_HI;
         thpri_lo = PADMAN_THPRI_LO;
         D_PRINTF("Debug Version\n");
         if(argc >= 2)
                 ParseParams(argc, argv);
         if(thpri_hi != PADMAN_THPRI_HI || thpri_lo != PADMAN_THPRI_LO)
                 M_PRINTF("thread priority: high=%d, low=%d\n", thpri_hi, thpri_lo);
         if(RegisterLibraryEntries(&_exp_padman) != 0)
         {
                 M_PRINTF("RegisterLibraryEntries failed.\n");
                 return MODULE_NO_RESIDENT_END;
         }
         if(InitRpcServers(thpri_lo) == 0)
         {
                 M_PRINTF("Failed to init RPC servers.\n");
                 return MODULE_NO_RESIDENT_END;
         }
         printf("Pad Driver for OSD\n");
         return MODULE_RESIDENT_END;
 }
References _exp_padman, D_PRINTF, InitRpcServers(), M_PRINTF, MODULE_NO_RESIDENT_END, MODULE_RESIDENT_END, padman_init, PADMAN_THPRI_HI, PADMAN_THPRI_LO, ParseParams(), printf(), RegisterLibraryEntries(), thpri_hi, thpri_lo, and vblank_end.
IRX_ID()
IRX_ID ("padman" , 3 , 6)
ParseParams()
static int ParseParams (int argc, char * argv[]) static
Definition at line 34 of file freepad.c.
 {
         int i, new_thpri_hi, new_thpri_lo;
         const char *param;
         new_thpri_hi = PADMAN_THPRI_HI;
         new_thpri_lo = PADMAN_THPRI_LO;
         if(argc > 1)
         {
                 argv++;
                 for(i = 1; i < argc; i++,argv++)
                 {
                         if(strncmp("thpri=", *argv, 6) == 0)
{
                                 //Parse high priority
                                 param = &(*argv)[6];
                                 if(isdigit(*param))
                                         new_thpri_hi = strtol(param, NULL, 10);
                                 //Skip value for high priority
                                 while(isdigit(*param))
                                         param++;
                                 //Valid high priority parameter
                                 if(new_thpri_hi - 9 < 115)
{
                                         if(*param == ',')
{
                                                 ++param;
                                                 //Parse low priority
                                                 if(isdigit(*param))
                                                         new_thpri_lo = strtol(param, NULL, 10);
                                                 if(new_thpri_lo - 9 >= 115)
{
                                                         M_KPRINTF("invalid priority %d\n", new_thpri_lo);
                                                         return 0;
                                                 }
                                         }
                                         if(new_thpri_lo < new_thpri_hi)
                                                 M_PRINTF("high prio thread must be higher than low prio thread\n");
                                 }
                                 else
{
                                         M_KPRINTF("invalid priority %d\n", new_thpri_hi);
                                         return 0;
                                 }
                         }
                 }
         }
         thpri_hi = new_thpri_hi;
         thpri_lo = new_thpri_lo;
         return 1;
 }
References isdigit, M_KPRINTF, M_PRINTF, NULL, PADMAN_THPRI_HI, PADMAN_THPRI_LO, strncmp(), strtol(), thpri_hi, and thpri_lo.
Referenced by _start().
WaitClearEvent()
void WaitClearEvent (int eventflag, u32 bits, int mode, u32 * resbits_out)
Definition at line 127 of file freepad.c.
 {
         u32 resbits;
         WaitEventFlag(eventflag, bits | EF_EXIT_THREAD, WEF_OR, &resbits);
         if( resbits & EF_EXIT_THREAD )
         {       //Yes, it's unused. Probably leftover code.
                 iop_thread_info_t tinfo;
                 ReferThreadStatus(TH_SELF, &tinfo);
                 SetEventFlag(eventflag, EF_EXIT_THREAD);
                 ExitThread();
         }
         ClearEventFlag(eventflag, ~bits);
 }
References ClearEventFlag(), EF_EXIT_THREAD, ExitThread(), ReferThreadStatus(), SetEventFlag(), TH_SELF, WaitEventFlag(), and WEF_OR.
Referenced by EnterConfigMode(), ExitConfigMode(), MainThread(), PadIsSupported(), QueryAct(), QueryButtonMask(), QueryComb(), QueryMode(), QueryModel(), QueryPadThread(), ReadData(), SetActAlign(), SetActAlignThread(), SetButtonInfo(), SetButtonInfoThread(), SetMainMode(), SetMainModeThread(), SetVrefParamThread(), TransferThread(), UpdatePadThread(), and VrefParam().
Variable Documentation
_exp_padman
struct irx_export_table _exp_padman extern
Referenced by _start().
padman_init
int padman_init extern
Definition at line 34 of file padInit.c.
Referenced by _start().
thpri_hi
int thpri_hi extern
Definition at line 36 of file padInit.c.
Referenced by _start(), and ParseParams().
thpri_lo
int thpri_lo extern
Definition at line 37 of file padInit.c.
Referenced by _start(), and ParseParams().
vblank_end
int vblank_end extern
Definition at line 40 of file padInit.c.
Referenced by _start(), VblankEnd(), and VblankStart().