ps2sdk: iop/system/mtapman/src/freemtap.c File Reference
freemtap.c File Reference
#include "types.h"
#include "irx.h"
#include "stdio.h"
#include "loadcore.h"
#include "thevent.h"
#include "thbase.h"
#include "xsio2man.h"
#include "freemtap.h"
Macros
#define BANNER "FREEMTAP %s\n"
#define VERSION "v1.0"
#define EF_UPDATE_SLOTS 0x1
#define EF_EXIT_THREAD 0x2
Functions
IRX_ID ("multitap_manager", 2, 2)
s32 read_stat6c_bit (u32 bit, sio2_transfer_data_t *tdata)
void get_slot_number_setup_td (u32 port, u32 reg)
s32 get_slot_number_check_td (u32 bit)
s32 get_slot_number (u32 port, u32 retries)
void update_slot_numbers_thread ()
s32 change_slot_setup_td (u32 port, s32 slot, u32 reg)
s32 change_slot_check_td (u32 a)
int change_slot (s32 *arg)
int get_slots1 (int port)
int get_slots2 (int port)
void update_slot_numbers ()
s32 _start (char **argv, int argc)
void shutdown ()
s32 mtapPortOpen (u32 port)
s32 mtapPortClose (u32 port)
s32 mtapGetConnection (u32 port)
s32 mtapGetSlotNumber (u32 port)
s32 mtapChangeSlot (u32 port, u32 slot)
Variables
struct irx_export_table _exp_mtapman
static s32 event_flag
static s32 threadid_main
static u32 state_open [4]
static u32 state_getcon [4]
static u32 state_slots [4]
static u8 in_buffer [256]
static u8 out_buffer [256]
static sio2_transfer_data_t td
Detailed Description
IOP multitap driver
Definition in file freemtap.c.
Macro Definition Documentation
BANNER
#define BANNER "FREEMTAP %s\n"
Definition at line 23 of file freemtap.c.
EF_EXIT_THREAD
#define EF_EXIT_THREAD 0x2
Definition at line 27 of file freemtap.c.
EF_UPDATE_SLOTS
#define EF_UPDATE_SLOTS 0x1
Definition at line 26 of file freemtap.c.
VERSION
#define VERSION "v1.0"
Definition at line 24 of file freemtap.c.
Function Documentation
_start()
s32 _start (char ** argv, int argc)
Definition at line 380 of file freemtap.c.
 {
         iop_event_t event;
         iop_thread_t thread;
         u32 i;
         printf(BANNER,VERSION);
         if(RegisterLibraryEntries(&_exp_mtapman) != 0)
         {
                 M_PRINTF("RegisterLibraryEntries failed.\n");
                 return 1;
         }
         if(InitRpcServers() == 0)
         {
                 M_PRINTF("Failed to setup RPC Servers.\n");
                 return 1;
         }
         event.attr = 2;
         event.bits = 0;
         event_flag = CreateEventFlag(&event);
         if(event_flag < 0)
         {
                 M_PRINTF("Could not create event flag (%i)\n.", (int)event_flag);
                 return 1;
         }
         thread.attr = TH_C;
         thread.thread = update_slot_numbers_thread;
         thread.stacksize = 0x800;
         thread.priority = 32;
         threadid_main = CreateThread(&thread);
         if(threadid_main < 0)
         {
                 M_PRINTF("Could not create thread (%i)\n.", (int)threadid_main);
                 return 1;
         }
         StartThread(threadid_main, 0);
         for(i=0; i < 4; i++)
         {
                 state_open[i] = 0;
                 state_getcon[i] = 0;
                 state_slots[i] = 0;
         }
         sio2_mtap_change_slot_set(change_slot);
         sio2_mtap_get_slot_max_set(get_slots1);
         sio2_mtap_get_slot_max2_set(get_slots2);
         sio2_mtap_update_slots_set(update_slot_numbers);
         td.in = in_buffer;
         td.out = out_buffer;
         return 0;
 }
References _exp_mtapman, iop_thread_t::attr, BANNER, change_slot(), CreateEventFlag(), CreateThread(), event_flag, get_slots1(), get_slots2(), sio2_transfer_data_t::in, in_buffer, InitRpcServers(), M_PRINTF, sio2_transfer_data_t::out, out_buffer, printf(), iop_thread_t::priority, RegisterLibraryEntries(), sio2_mtap_change_slot_set(), sio2_mtap_get_slot_max2_set(), sio2_mtap_get_slot_max_set(), sio2_mtap_update_slots_set(), iop_thread_t::stacksize, StartThread(), state_getcon, state_open, state_slots, td, TH_C, iop_thread_t::thread, threadid_main, update_slot_numbers(), update_slot_numbers_thread(), and VERSION.
change_slot()
int change_slot (s32 * arg)
Definition at line 261 of file freemtap.c.
 {
         u32 loop = 0;
         u32 count = 4;
         u32 reg = 0;
         s32 data[4];
         u32 i, port;
         while((loop < 10) && (count != 0))
         {
                 count = 4;
                 reg = 0;
                 td.in_size = 0;
                 td.out_size = 0;
                 for(i=0; i < 16; i++) td.regdata[i] = 0;
                 // Setup transfer data
                 for(port=0; port < 4; port++)
                 {
                         data[port] = -1;
                         if(arg[port] >= 0)
{
                                 if((state_open[port] == 1) && (state_getcon[port] == 1))
{
                                         if(state_slots[port] > arg[port])
{
                                                 change_slot_setup_td(port, arg[port], reg);
                                                 data[port] = port;
                                                 reg++;
                                         }
                                         else
{
                                                 arg[port+4] = -1;
                                         }
                                 }
                                 else
{
                                         if(arg[port] == 0)
                                                 arg[port+4] = 1;
                                         else
                                                 arg[port+4] = -1;
                                 }
                         }
                         else
{
                                 arg[port+4] = 0;
                         }
                 }
                 // Send transfer data and check result
                 if(reg > 0)
                 {
                         sio2_transfer2(&td);
                         for(port=0; port < 4; port++)
{
                                 if(data[port] >= 0)
{
                                         s32 res = change_slot_check_td(data[port]);
                                         if(res == -2)
{
                                                 arg[port+4] = -1;
                                                 count--;
                                         }
                                         else
{
                                                 if(res >= 0)
{
                                                         if(res == arg[port])
                                                                 arg[port+4] = 1;
                                                         else
                                                                 arg[port+4] = -1;
                                                         count--;
                                                 }
                                         }
                                 }
                                 else
{
                                         count--;
                                 }
                         }
                 }
                 if(count != 0) loop++;
         }
         for(i=0; i < 4; i++)
         {
                 if(arg[i+4] < 0)
                         return 0;
         }
         return 1;
 }
References arg, change_slot_check_td(), change_slot_setup_td(), sio2_transfer_data_t::in_size, sio2_transfer_data_t::out_size, sio2_transfer_data_t::regdata, sio2_transfer2(), state_getcon, state_open, state_slots, and td.
Referenced by _start(), and mtapChangeSlot().
change_slot_check_td()
s32 change_slot_check_td (u32 a)
Definition at line 224 of file freemtap.c.
 {
         u32 i;
         s32 res;
         if(td.out_size >= 7)
         {
                 if(read_stat6c_bit(a, &td) != 1)
                 {
                         if(td.out[5] == 0x66)
                                 res = -2;
                         else
                                 res = td.out[5];
                 }
                 else
                 {
                         res = -1;
                 }
         }
         else
         {
                 return -99;
         }
         for(i=0; i < 249; i++)
         {
                 td.out[i] = td.out[i+7];
         }
         td.out_size -= 7;
         return res;
 }
References sio2_transfer_data_t::out, sio2_transfer_data_t::out_size, read_stat6c_bit(), and td.
Referenced by change_slot().
change_slot_setup_td()
s32 change_slot_setup_td (u32 port, s32 slot, u32 reg)
Definition at line 190 of file freemtap.c.
 {
         u32 p = port | 0x2;
         u32 i;
         td.port_ctrl1[p] = 0xFF020505;
         td.port_ctrl2[p] = 0x00030064;
         td.regdata[reg] = (p & 0x3) | 0x1c0740;
         for(i=0; i < 7; i++) td.in[td.in_size + i] = 0;
         td.in[td.in_size] = 0x21;
         if(port < 2)
         {
                 td.in[td.in_size + 1] = 0x21;
         }
         else
         {
                 td.in[td.in_size + 1] = 0x22;
         }
         td.in[td.in_size + 2] = (u8)slot;
         td.in_size += 7;
         td.out_size += 7;
         td.in_dma.addr = 0;
         td.out_dma.addr = 0;
         return 0;
 }
References _sio2_dma_arg::addr, sio2_transfer_data_t::in, sio2_transfer_data_t::in_dma, sio2_transfer_data_t::in_size, sio2_transfer_data_t::out_dma, sio2_transfer_data_t::out_size, sio2_transfer_data_t::port_ctrl1, sio2_transfer_data_t::port_ctrl2, sio2_transfer_data_t::regdata, and td.
Referenced by change_slot().
get_slot_number()
s32 get_slot_number (u32 port, u32 retries)
Definition at line 113 of file freemtap.c.
 {
         u32 i,j;
         s32 slots = -1;
         if(port >= 4) return -3;
         if(state_open[port] == 0) return -4;
         i = 0;
         while((slots < 0) && (i <= retries))
         {
                 sio2_mtap_transfer_init();
                 td.in_size = 0;
                 td.out_size = 0;
                 for(j=0; j < 16; j++) td.regdata[j] = 0;
                 get_slot_number_setup_td(port, 0);
                 sio2_transfer2(&td);
                 slots = get_slot_number_check_td(0);
                 sio2_transfer_reset2();
                 if((slots == -2) || (slots >= 0)) return slots;
                 i++;
                 //M_PRINTF("get_slot_number retry %i.\n", (int)i);
         }
         return -4;
 }
References get_slot_number_check_td(), get_slot_number_setup_td(), sio2_transfer_data_t::in_size, sio2_transfer_data_t::out_size, sio2_transfer_data_t::regdata, sio2_mtap_transfer_init(), sio2_transfer2(), sio2_transfer_reset2(), state_open, and td.
Referenced by mtapGetSlotNumber(), mtapPortOpen(), and update_slot_numbers_thread().
get_slot_number_check_td()
s32 get_slot_number_check_td (u32 bit)
Definition at line 90 of file freemtap.c.
 {
         s32 res;
         u32 i;
         if(read_stat6c_bit(bit, &td) != 1)
         {
                 if(td.out[5] == 0x66)
                         res = -2;
                 else
                         res = td.out[3];
         }
         else
         {
                 res = -1;
         }
         for(i=0; i < 250; i++) td.out[i] = td.out[i+6];
         td.out_size -= 6;
         return res;
 }
References sio2_transfer_data_t::out, sio2_transfer_data_t::out_size, read_stat6c_bit(), and td.
Referenced by get_slot_number().
get_slot_number_setup_td()
void get_slot_number_setup_td (u32 port, u32 reg)
Definition at line 65 of file freemtap.c.
 {
         u32 p = port | 0x2;
         u32 i;
         td.port_ctrl1[p] = 0xFF020505;
         td.port_ctrl2[p] = 0x00030064;
         td.regdata[reg] = (p & 0x3) | 0x180640;
         for(i=0; i < 6 ; i++) td.in[td.in_size + i] = 0;
         td.in[td.in_size] = 0x21;
         if(port < 2)
                 td.in[td.in_size + 1] = 0x12;
         else
                 td.in[td.in_size + 1] = 0x13;
         td.in_size += 6;
         td.out_size += 6;
         td.in_dma.addr = 0;
         td.out_dma.addr = 0;
 }
References _sio2_dma_arg::addr, sio2_transfer_data_t::in, sio2_transfer_data_t::in_dma, sio2_transfer_data_t::in_size, sio2_transfer_data_t::out_dma, sio2_transfer_data_t::out_size, sio2_transfer_data_t::port_ctrl1, sio2_transfer_data_t::port_ctrl2, sio2_transfer_data_t::regdata, and td.
Referenced by get_slot_number().
get_slots1()
int get_slots1 (int port)
Definition at line 365 of file freemtap.c.
 {
         return state_slots[port];
 }
References state_slots.
Referenced by _start().
get_slots2()
int get_slots2 (int port)
Definition at line 370 of file freemtap.c.
 {
         return state_slots[port];
 }
References state_slots.
Referenced by _start().
IRX_ID()
IRX_ID ("multitap_manager" , 2 , 2)
mtapChangeSlot()
s32 mtapChangeSlot (u32 port, u32 slot)
Definition at line 516 of file freemtap.c.
 {
         s32 data[4];
         u32 i;
         if(port > 4) return 0;
         if(state_open[port] == 0)
         {
                 M_PRINTF("mtap manager doesn't work\n");
                 return -1;
         }
         for(i=0; i < 4; i++)
                 data[i] = -1;
         data[port] = slot;
         sio2_mtap_transfer_init();
         change_slot(data);
         sio2_transfer_reset2();
         if(data[port] < 0)
         {
                 M_PRINTF("Failed to change slot.\n");
                 return data[port];
         }
         else
         {
                 M_PRINTF("Change slot complete.\n");
                 return 1;
         }
 }
References change_slot(), M_PRINTF, sio2_mtap_transfer_init(), sio2_transfer_reset2(), and state_open.
Referenced by rpc_server_change_slot().
mtapGetConnection()
s32 mtapGetConnection (u32 port)
Definition at line 495 of file freemtap.c.
 {
         return state_getcon[port];
 }
References state_getcon.
Referenced by RpcServerGetConnection().
mtapGetSlotNumber()
s32 mtapGetSlotNumber (u32 port)
Definition at line 500 of file freemtap.c.
 {
         s32 res;
         if(port > 4) return -1;
         if(state_open[port] == 0) return 1;
         res = get_slot_number(port, 10);
         if(res >= 0)
                 return res;
         else
                 return 1;
 }
References get_slot_number(), and state_open.
Referenced by rpc_server_get_slot_number().
mtapPortClose()
s32 mtapPortClose (u32 port)
Definition at line 487 of file freemtap.c.
 {
         state_open[port] = 0;
         state_getcon[port] = 0;
         return 1;
 }
References state_getcon, and state_open.
Referenced by RpcServerPortClose().
mtapPortOpen()
s32 mtapPortOpen (u32 port)
Definition at line 462 of file freemtap.c.
 {
         if(port < 4)
         {
                 state_open[port] = 1;
                 s32 res = get_slot_number(port, 10);
                 if(res < 0)
                 {
                         state_getcon[port] = 0;
                         state_slots[port] = 1;
                         return res;
                 }
                 else
                 {
                         state_getcon[port] = 1;
                         state_slots[port] = res;
                         return 1;
                 }
         }
         return 0;
 }
References get_slot_number(), state_getcon, state_open, and state_slots.
Referenced by RpcServerPortOpen().
read_stat6c_bit()
s32 read_stat6c_bit (u32 bit, sio2_transfer_data_t * tdata)
Definition at line 41 of file freemtap.c.
 {
         switch(bit)
         {
                 case 0:         return (tdata->stat6c >> 16) & 1;
                 case 1:         return (tdata->stat6c >> 17) & 1;
                 case 2:         return (tdata->stat6c >> 18) & 1;
                 case 3:         return (tdata->stat6c >> 19) & 1;
                 case 4:         return (tdata->stat6c >> 20) & 1;
                 case 5:         return (tdata->stat6c >> 21) & 1;
                 case 6:         return (tdata->stat6c >> 22) & 1;
                 case 7:         return (tdata->stat6c >> 23) & 1;
                 case 8:         return (tdata->stat6c >> 24) & 1;
                 case 9:         return (tdata->stat6c >> 25) & 1;
                 case 10:        return (tdata->stat6c >> 26) & 1;
                 case 11:        return (tdata->stat6c >> 27) & 1;
                 case 12:        return (tdata->stat6c >> 28) & 1;
                 case 13:        return (tdata->stat6c >> 29) & 1;
                 case 14:        return (tdata->stat6c >> 30) & 1;
                 case 15:        return (tdata->stat6c >> 31) & 1;
                 default:        return 0;
         }
 }
References sio2_transfer_data_t::stat6c.
Referenced by change_slot_check_td(), and get_slot_number_check_td().
update_slot_numbers()
void update_slot_numbers ()
Definition at line 375 of file freemtap.c.
 {
         SetEventFlag(event_flag, EF_UPDATE_SLOTS);
 }
References EF_UPDATE_SLOTS, event_flag, and SetEventFlag().
Referenced by _start().
update_slot_numbers_thread()
void update_slot_numbers_thread ()
Definition at line 149 of file freemtap.c.
 {
         while(1)
         {
                 u32 resbits, port;
                 s32 slots;
                 WaitEventFlag(event_flag, EF_UPDATE_SLOTS | EF_EXIT_THREAD, 0x11, &resbits);
                 if(resbits & EF_EXIT_THREAD)
                 {
                         SetEventFlag(event_flag, 0x4);
                         ExitThread();
                 }
                 for(port=0; port < 4; port++)
                 {
                         if(state_open[port] == 1)
{
                                 if(state_getcon[port] == 0)
                                         slots = get_slot_number(port, 10);
                                 else
                                         slots = get_slot_number(port, 0);
                                 if(slots < 0)
{
                                         state_slots[port] = 1;
                                         state_getcon[port] = 0;
                                 }
                                 else
{
                                         state_slots[port] = slots;
                                         state_getcon[port] = 1;
                                 }
                         }
                 }
         }
 }
References EF_EXIT_THREAD, EF_UPDATE_SLOTS, event_flag, ExitThread(), get_slot_number(), SetEventFlag(), state_getcon, state_open, state_slots, and WaitEventFlag().
Referenced by _start().
Variable Documentation
_exp_mtapman
struct irx_export_table _exp_mtapman extern
Referenced by _start().
event_flag
s32 event_flag static
Definition at line 31 of file freemtap.c.
Referenced by _start(), update_slot_numbers(), and update_slot_numbers_thread().
in_buffer
u8 in_buffer[256] static
Definition at line 37 of file freemtap.c.
Referenced by _start(), and pdSetInBuffer().
out_buffer
u8 out_buffer[256] static
Definition at line 38 of file freemtap.c.
Referenced by _start(), and pdGetOutBuffer().
state_getcon
u32 state_getcon[4] static
Definition at line 35 of file freemtap.c.
Referenced by _start(), change_slot(), mtapGetConnection(), mtapPortClose(), mtapPortOpen(), shutdown(), and update_slot_numbers_thread().
state_open
u32 state_open[4] static
Definition at line 34 of file freemtap.c.
Referenced by _start(), change_slot(), get_slot_number(), mtapChangeSlot(), mtapGetSlotNumber(), mtapPortClose(), mtapPortOpen(), shutdown(), and update_slot_numbers_thread().
state_slots
u32 state_slots[4] static
Definition at line 36 of file freemtap.c.
Referenced by _start(), change_slot(), get_slots1(), get_slots2(), mtapPortOpen(), shutdown(), and update_slot_numbers_thread().
td
sio2_transfer_data_t td static
Definition at line 39 of file freemtap.c.
Referenced by _start(), change_slot(), change_slot_check_td(), change_slot_setup_td(), get_slot_number(), get_slot_number_check_td(), get_slot_number_setup_td(), openDeviceEndpoint(), readStat6cBit(), recv_td(), send_td(), and sio2_transfer().
threadid_main
s32 threadid_main static
Definition at line 32 of file freemtap.c.
Referenced by _start().