ps2sdk: iop/hdd/libapa/src/free.c File Reference
free.c File Reference
#include <errno.h>
#include <iomanX.h>
#include <sysclib.h>
#include <stdio.h>
#include <atad.h>
#include <hdd-ioctl.h>
#include "apa-opt.h"
#include "libapa.h"
Functions
static void apaCalculateFreeSpace (u32 *free, u32 sectors)
int apaGetFreeSectors (s32 device, u32 *free, apa_device_t *deviceinfo)
Function Documentation
apaCalculateFreeSpace()
static void apaCalculateFreeSpace (u32 * free, u32 sectors) static
Definition at line 27 of file free.c.
 {
         if(0x1FFFFF < sectors)
         {
                 *free += sectors;
                 return;
         }
         if((*free & sectors) == 0)
         {
                 *free |= sectors;
                 return;
         }
         for(sectors /= 2; 0x3FFFF < sectors; sectors /= 2)
                 *free |= sectors;
 }
References free.
Referenced by apaGetFreeSectors().
apaGetFreeSectors()
int apaGetFreeSectors (s32 device, u32 * free, apa_device_t * deviceinfo)
Definition at line 45 of file free.c.
 {
         u32 sectors, partMax;
         int rv;
         apa_cache_t *clink;
         sectors = 0;
         *free = 0;
         if((clink = apaCacheGetHeader(device, 0, APA_IO_MODE_READ, &rv)) != NULL)
         {
                 do{
                         if(clink->header->type == 0)
                                 apaCalculateFreeSpace(free, clink->header->length);
                         sectors += clink->header->length;
                 }while((clink = apaGetNextHeader(clink, &rv)) != NULL);
         }
         if(rv == 0)
         {
                 for(partMax = deviceinfo[device].partitionMaxSize; 0x0003FFFF < partMax; partMax = deviceinfo[device].partitionMaxSize)
                 {       //As weird as it looks, this was how it was done in the original HDD.IRX.
                         for( ; 0x0003FFFF < partMax; partMax /= 2)
{
                                 //Non-SONY: Perform 64-bit arithmetic here to avoid overflows when dealing with large disks.
                                 if((sectors % partMax == 0) && ((u64)sectors + partMax < deviceinfo[device].totalLBA))
{
                                         apaCalculateFreeSpace(free, partMax);
                                         sectors += partMax;
                                         break;
                                 }
                         }
                         if(0x0003FFFF >= partMax)
                                 break;
                 }
                 APA_PRINTF(APA_DRV_NAME": total = %08lx sectors, installable = %08lx sectors.\n", sectors, *free);
         }
         return rv;
 }
References APA_DRV_NAME, APA_IO_MODE_READ, APA_PRINTF, apaCacheGetHeader(), apaCalculateFreeSpace(), apaGetNextHeader(), free, apa_cache_t::header, apa_header_t::length, NULL, apa_device_t::partitionMaxSize, and apa_header_t::type.
Referenced by hddDevctl().