ps2sdk: iop/sound/libsd/src/freesd.c File Reference
freesd.c File Reference
#include "types.h"
#include "irx.h"
#include "loadcore.h"
#include "stdio.h"
#include "intrman.h"
#include "freesd.h"
#include "spu2regs.h"
Macros
#define BANNER "FREESD %s\n"
#define VERSION "v1.01"
#define MODNAME "freesd"
#define M_PRINTF(format, args...) printf(MODNAME ": " format, ## args)
Functions
IRX_ID (MODNAME, 1, 1)
void SetESA (s32 core, u32 value)
u32 GetEEA (int chan)
void nopdelay ()
void InitSpu2 ()
s32 _start (char **argv, int argc)
int TransInterrupt (void *data)
int Spu2Interrupt (void *data)
void RegisterInterrupts ()
void ResetAll ()
void Reset (s32 flag)
sceSdSpu2IntrHandler sceSdSetSpu2IntrHandler (sceSdSpu2IntrHandler handler, void *data)
void InitVoices ()
void InitCoreVolume (s32 flag)
void InitSpdif ()
int sceSdInit (int flag)
void sceSdSetParam (u16 reg, u16 val)
u16 sceSdGetParam (u16 reg)
void sceSdSetSwitch (u16 reg, u32 val)
u32 sceSdGetSwitch (u16 reg)
u32 DmaStop (u32 core)
void SetDmaWrite (s32 chan)
void SetDmaRead (s32 chan)
u16 sceSdNote2Pitch (u16 center_note, u16 center_fine, u16 note, short fine)
u16 sceSdPitch2Note (u16 center_note, u16 center_fine, u16 pitch)
void SetSpdifMode (u16 val)
void sceSdSetCoreAttr (u16 entry, u16 val)
u16 sceSdGetCoreAttr (u16 entry)
sceSdTransIntrHandler sceSdSetTransIntrHandler (int chan, sceSdTransIntrHandler func, void *data)
int sceSdQuit ()
void sceSdSetAddr (u16 reg, u32 val)
u32 sceSdGetAddr (u16 reg)
SdIntrCallback sceSdSetTransCallback (s32 core, SdIntrCallback cb)
SdIntrCallback sceSdSetIRQCallback (SdIntrCallback cb)
Variables
struct irx_export_table _exp_libsd
u32 BlockTransBuff [2]
u32 BlockTransAddr [2]
u32 BlockTransSize [2]
u32 EffectSizes [10]
sceSdEffectAttr EffectAttr [2]
u32 EffectAddr [2]
u32 VoiceTransStatus [2]
volatile u16 VoiceTransComplete [2]
u32 VoiceTransIoMode [2]
u16 SpdifSettings
void * Spu2IntrData
sceSdTransIntrHandler TransIntrHandlers [2]
SdIntrCallback TransIntrCallbacks [2]
sceSdSpu2IntrHandler Spu2IntrHandler
SdIntrCallback Spu2IrqCallback
IntrData TransIntrData [2]
volatile u16 * ParamRegList []
u16 NotePitchTable []
u16 VoiceDataInit [16]
u8 CoreAttrShifts [4] = {7, 6, 14, 8}
Detailed Description
Part of the IOP Sound Driver
Definition in file freesd.c.
Macro Definition Documentation
BANNER
#define BANNER "FREESD %s\n"
Definition at line 23 of file freesd.c.
M_PRINTF
#define M_PRINTF (format, args...) printf(MODNAME ": " format, ## args)
Definition at line 30 of file freesd.c.
MODNAME
#define MODNAME "freesd"
Definition at line 26 of file freesd.c.
VERSION
#define VERSION "v1.01"
Definition at line 24 of file freesd.c.
Function Documentation
_start()
s32 _start (char ** argv, int argc)
Definition at line 121 of file freesd.c.
 {
         printf(BANNER, VERSION);
         if(RegisterLibraryEntries(&_exp_libsd) != 0) return 1;
         InitSpu2();
         return 0;
 }
References _exp_libsd, BANNER, InitSpu2(), printf(), RegisterLibraryEntries(), and VERSION.
DmaStop()
u32 DmaStop (u32 core)
Definition at line 580 of file freesd.c.
 {
         u32 retval;
         core &= 1;
         if(*U16_REGISTER(0x1B0 + (core * 1024)) == 0)
                 retval = 0;
         else
                 retval = *SD_DMA_ADDR(core);
         *SD_DMA_CHCR(core) &= ~SD_DMA_START;
         *U16_REGISTER(0x1B0 + (core * 1024)) = 0;
         retval = (BlockTransBuff[core] << 24) | (retval & 0xFFFFFF);
         return retval;
 }
References BlockTransBuff, SD_DMA_ADDR, SD_DMA_CHCR, SD_DMA_START, and U16_REGISTER.
Referenced by sceSdBlockTrans(), and sceSdQuit().
GetEEA()
u32 GetEEA (int chan)
Referenced by Reset().
InitCoreVolume()
void InitCoreVolume (s32 flag)
Definition at line 412 of file freesd.c.
 {
         *SD_C_SPDIF_OUT = 0xC032;
         if(flag)
         {
                 *SD_CORE_ATTR(0) = SD_SPU2_ON | SD_ENABLE_EFFECTS | SD_MUTE;
                 *SD_CORE_ATTR(1) = SD_SPU2_ON | SD_ENABLE_EFFECTS | SD_MUTE | SD_ENABLE_EX_INPUT;
         }
         else
         {
                 *SD_CORE_ATTR(0) = SD_SPU2_ON | SD_MUTE;
                 *SD_CORE_ATTR(1) = SD_SPU2_ON | SD_MUTE | SD_ENABLE_EX_INPUT;
         }
         // HIgh is voices 0-15, LOw is 16-23, representing voices 0..23 (24)
         *SD_S_VMIXL_HI(0)       = 0xFFFF;
         *SD_S_VMIXL_LO(0)       = 0xFF;
         *SD_S_VMIXR_HI(0)       = 0xFFFF;
         *SD_S_VMIXR_LO(0)       = 0xFF;
         *SD_S_VMIXEL_HI(0)      = 0xFFFF;
         *SD_S_VMIXEL_LO(0)      = 0xFF;
         *SD_S_VMIXER_HI(0)      = 0xFFFF;
         *SD_S_VMIXER_LO(0)      = 0xFF;
         *SD_S_VMIXL_HI(1)       = 0xFFFF;
         *SD_S_VMIXL_LO(1)       = 0xFF;
         *SD_S_VMIXR_HI(1)       = 0xFFFF;
         *SD_S_VMIXR_LO(1)       = 0xFF;
         *SD_S_VMIXEL_HI(1)      = 0xFFFF;
         *SD_S_VMIXEL_LO(1)      = 0xFF;
         *SD_S_VMIXER_HI(1)      = 0xFFFF;
         *SD_S_VMIXER_LO(1)      = 0xFF;
         *SD_P_MMIX(0) = 0xFF0;
         *SD_P_MMIX(1) = 0xFFC;
         if(flag == 0)
         {
                 *SD_P_MVOLL(0) = 0;
                 *SD_P_MVOLR(0) = 0;
                 *SD_P_MVOLL(1) = 0;
                 *SD_P_MVOLR(1) = 0;
                 *SD_P_EVOLL(0) = 0;
                 *SD_P_EVOLL(1) = 0;
                 *SD_P_EVOLR(0) = 0;
                 *SD_P_EVOLR(1) = 0;
                 // Effect End Address, Upper part
                 *SD_A_EEA_HI(0) = 0xE;
                 *SD_A_EEA_HI(1) = 0xF;
         }
         *SD_P_AVOLL(0) = 0;
         *SD_P_AVOLR(0) = 0;
         // Core 1 External Input Volume.
         // The external Input is Core 0's output.
         *SD_P_AVOLL(1) = 0x7FFF;
         *SD_P_AVOLR(1) = 0x7FFF;
         *SD_P_BVOLL(0) = 0;
         *SD_P_BVOLR(0) = 0;
         *SD_P_BVOLL(1) = 0;
         *SD_P_BVOLR(1) = 0;
 }
References SD_A_EEA_HI, SD_C_SPDIF_OUT, SD_CORE_ATTR, SD_ENABLE_EFFECTS, SD_ENABLE_EX_INPUT, SD_MUTE, SD_P_AVOLL, SD_P_AVOLR, SD_P_BVOLL, SD_P_BVOLR, SD_P_EVOLL, SD_P_EVOLR, SD_P_MMIX, SD_P_MVOLL, SD_P_MVOLR, SD_S_VMIXEL_HI, SD_S_VMIXEL_LO, SD_S_VMIXER_HI, SD_S_VMIXER_LO, SD_S_VMIXL_HI, SD_S_VMIXL_LO, SD_S_VMIXR_HI, SD_S_VMIXR_LO, and SD_SPU2_ON.
Referenced by sceSdInit().
InitSpdif()
void InitSpdif ()
Definition at line 480 of file freesd.c.
 {
         *SD_C_SPDIF_MODE        = 0x900;
         *SD_C_SPDIF_MEDIA       = 0x200;
         *U16_REGISTER(0x7CA) = 8;
 }
References SD_C_SPDIF_MEDIA, SD_C_SPDIF_MODE, and U16_REGISTER.
Referenced by sceSdInit().
InitSpu2()
void InitSpu2 ()
Definition at line 109 of file freesd.c.
 {
         *U32_REGISTER(0x1404)  = 0xBF900000;
         *U32_REGISTER(0x140C)  = 0xBF900800;
         *U32_REGISTER(0x10F0) |= 0x80000;
         *U32_REGISTER(0x1570) |= 8;
         *U32_REGISTER(0x1014)  = 0x200B31E1;
         *U32_REGISTER(0x1414)  = 0x200B31E1;
 }
References U32_REGISTER.
Referenced by _start(), and sceSdInit().
InitVoices()
void InitVoices ()
Definition at line 341 of file freesd.c.
 {
         s32 voice, i;
         volatile u16 *statx;
         // Set Start Address of data to transfer.
         *SD_A_TSA_HI(0) = 0;
         *SD_A_TSA_LO(0) = 0x5000 >> 1;
         // Fill with data.
         // First 16 bytes are reserved.
         for(i = 0; i < 16; i++) *SD_A_STD(0) = VoiceDataInit[i];
         // Set Transfer mode to IO
         *SD_CORE_ATTR(0) = (*SD_CORE_ATTR(0) & ~SD_CORE_DMA) | SD_DMA_IO;
         statx = U16_REGISTER(0x344);
         // Wait for transfer to complete;
         while(*statx & SD_IO_IN_PROCESS);
         // Reset DMA settings
         *SD_CORE_ATTR(0) &= ~SD_CORE_DMA;
         // Init voices
         for(voice = 0; voice < 24; voice++)
         {
                 *SD_VP_VOLL(0, voice)   = 0;
                 *SD_VP_VOLR(0, voice)   = 0;
                 *SD_VP_PITCH(0, voice)  = 0x3FFF;
                 *SD_VP_ADSR1(0, voice)  = 0;
                 *SD_VP_ADSR2(0, voice)  = 0;
                 *SD_VP_VOLL(1, voice)   = 0;
                 *SD_VP_VOLR(1, voice)   = 0;
                 *SD_VP_PITCH(1, voice)  = 0x3FFF;
                 *SD_VP_ADSR1(1, voice)  = 0;
                 *SD_VP_ADSR2(1, voice)  = 0;
                 // Top address of waveform data
                 *SD_VA_SSA_HI(0, voice) = 0;
                 *SD_VA_SSA_LO(0, voice) = 0x5000 >> 1;
                 *SD_VA_SSA_HI(1, voice) = 0;
                 *SD_VA_SSA_LO(1, voice) = 0x5000 >> 1;
         }
         // Set all voices to ON
         *SD_A_KON_HI(0) = 0xFFFF;
         *SD_A_KON_LO(0) = 0xFF;
         *SD_A_KON_HI(1) = 0xFFFF;
         *SD_A_KON_LO(1) = 0xFF;
         // There is no guarantee that voices will be turn on at once.
         // So we wait to make sure.
         nopdelay();
         // Set all voices to OFF
         *SD_A_KOFF_HI(0) = 0xFFFF;
         *SD_A_KOFF_LO(0) = 0xFF;
         *SD_A_KOFF_HI(1) = 0xFFFF;
         *SD_A_KOFF_LO(1) = 0xFF;
         // There is no guarantee that voices will be turn off at once.
         // So we wait to make sure.
         nopdelay();
         *SD_S_ENDX_HI(0) = 0;
         *SD_S_ENDX_LO(0) = 0;
 }
References nopdelay(), SD_A_KOFF_HI, SD_A_KOFF_LO, SD_A_KON_HI, SD_A_KON_LO, SD_A_STD, SD_A_TSA_HI, SD_A_TSA_LO, SD_CORE_ATTR, SD_CORE_DMA, SD_DMA_IO, SD_IO_IN_PROCESS, SD_S_ENDX_HI, SD_S_ENDX_LO, SD_VA_SSA_HI, SD_VA_SSA_LO, SD_VP_ADSR1, SD_VP_ADSR2, SD_VP_PITCH, SD_VP_VOLL, SD_VP_VOLR, U16_REGISTER, and VoiceDataInit.
Referenced by sceSdInit().
IRX_ID()
IRX_ID (MODNAME , 1 , 1)
nopdelay()
void nopdelay ()
Definition at line 101 of file freesd.c.
 {
         s32 i;
         for(i=0; i < 0x10000; i++)
                 asm volatile("nop\nnop\nnop\nnop\nnop");
 }
Referenced by InitVoices(), and ResetAll().
RegisterInterrupts()
void RegisterInterrupts ()
Definition at line 223 of file freesd.c.
 {
         s32 ret;
         DisableIntr(0x24, (int *)&ret);
         DisableIntr(0x28, (int *)&ret);
         DisableIntr(0x9, (int *)&ret);
         ReleaseIntrHandler(0x24);
         ReleaseIntrHandler(0x28);
         RegisterIntrHandler(0x24, 1, TransInterrupt, &TransIntrData[0]);
         RegisterIntrHandler(0x28, 1, TransInterrupt, &TransIntrData[1]);
         VoiceTransComplete[0] = 0;
         VoiceTransComplete[1] = 0;
         ReleaseIntrHandler(0x9);
         RegisterIntrHandler(0x9, 1, Spu2Interrupt, &Spu2IntrData);
 }
References DisableIntr(), RegisterIntrHandler(), ReleaseIntrHandler(), Spu2Interrupt(), Spu2IntrData, TransInterrupt(), TransIntrData, and VoiceTransComplete.
Referenced by Reset().
Reset()
void Reset (s32 flag)
Definition at line 283 of file freesd.c.
 {
         s32 core;
         if(flag == 0) ResetAll();
         VoiceTransStatus[0]     = 1;
         VoiceTransStatus[1]     = 1;
         TransIntrCallbacks[0]   = NULL;
         TransIntrCallbacks[1]   = NULL;
         TransIntrHandlers[0]    = NULL;
         TransIntrHandlers[1]    = NULL;
         TransIntrData[0].mode   = 0;
         TransIntrData[1].mode   = 1;
         TransIntrData[0].data   = NULL;
         TransIntrData[1].data   = NULL;
         VoiceTransIoMode[0]             = 0;
         VoiceTransIoMode[1]             = 0;
         Spu2IntrHandler                 = NULL;
         Spu2IrqCallback                 = NULL;
         Spu2IntrData                    = NULL;
         RegisterInterrupts();
         for(core = 0; core < 2; core++)
         {
                 EffectAttr[core].core = core;
                 EffectAttr[core].mode = 0;
                 EffectAttr[core].depth_L = 0;
                 EffectAttr[core].depth_R = 0;
                 EffectAttr[core].delay = 0;
                 EffectAttr[core].feedback = 0;
         }
         if(flag == 0)
         {
                 for(core = 0; core < 2; core++)
                 {
                         EffectAddr[core] = GetEEA(core) - ((EffectSizes[0] << 4) - 2);
                         SetESA(core, EffectAddr[core]);
                 }
         }
 }
References sceSdEffectAttr::core, IntrData::data, sceSdEffectAttr::delay, sceSdEffectAttr::depth_L, sceSdEffectAttr::depth_R, EffectAddr, EffectAttr, EffectSizes, sceSdEffectAttr::feedback, GetEEA(), sceSdEffectAttr::mode, IntrData::mode, NULL, RegisterInterrupts(), ResetAll(), SetESA(), Spu2IntrData, Spu2IntrHandler, Spu2IrqCallback, TransIntrCallbacks, TransIntrData, TransIntrHandlers, VoiceTransIoMode, and VoiceTransStatus.
Referenced by sceSdInit().
ResetAll()
void ResetAll ()
Definition at line 244 of file freesd.c.
 {
         u32 core;
         volatile u16 *statx;
         *SD_C_SPDIF_OUT = 0;
         nopdelay();
         *SD_C_SPDIF_OUT = 0x8000;
         nopdelay();
         *U32_REGISTER(0x10F0) |= 0xB0000;
         for(core=0; core < 2; core++)
         {
                 VoiceTransIoMode[core]  = 0;
                 *U16_REGISTER(0x1B0)    = 0;
                 *SD_CORE_ATTR(core)             = 0;
                 nopdelay();
                 *SD_CORE_ATTR(core)             = SD_SPU2_ON;
                 *SD_P_MVOLL(core)               = 0;
                 *SD_P_MVOLR(core)               = 0;
                 statx = U16_REGISTER(0x344 + (core * 1024));
                 while(*statx & 0x7FF);
                 *SD_A_KOFF_HI(core)             = 0xFFFF;
                 *SD_A_KOFF_LO(core)             = 0xFFFF; // Should probably only be 0xFF
         }
         *SD_S_PMON_HI(1)        = 0;
         *SD_S_PMON_LO(1)        = 0;
         *SD_S_NON_HI(1)         = 0;
         *SD_S_NON_LO(1)         = 0;
 }
References nopdelay(), SD_A_KOFF_HI, SD_A_KOFF_LO, SD_C_SPDIF_OUT, SD_CORE_ATTR, SD_P_MVOLL, SD_P_MVOLR, SD_S_NON_HI, SD_S_NON_LO, SD_S_PMON_HI, SD_S_PMON_LO, SD_SPU2_ON, U16_REGISTER, U32_REGISTER, and VoiceTransIoMode.
Referenced by Reset().
sceSdGetAddr()
u32 sceSdGetAddr (u16 reg)
Definition at line 866 of file freesd.c.
 {
         volatile u16 *reg1;
         u16 voice;
         u32 retlo, rethi;
         reg1 = ParamRegList[(reg >> 8) & 0xFF] + ((reg & 1) << 9);
         voice = reg & 0x3E;
         reg1 += ((voice << 1) + voice);
         rethi = *reg1 << 17;
         retlo = 0x1FFFF;
         reg &= 0xFF00;
         if(reg != 0x1D00)
         {
                 retlo = *(reg1 + 1) << 1;
                 if((reg == 0x2100) || (reg == 0x2200))
                 {
                         u32 lo, hi;
                         hi = *reg1 << 17;
                         lo = *(reg1 + 1) << 1;
                         if((rethi == hi) || (retlo != lo))
{
                                 retlo = lo;
                                 rethi = hi;
                         }
                 }
         }
         return rethi | retlo;
 }
References ParamRegList.
Referenced by rpc_server(), sceSdProcBatch(), sceSdProcBatchEx(), and sndStreamGetPosition().
sceSdGetCoreAttr()
u16 sceSdGetCoreAttr (u16 entry)
Definition at line 800 of file freesd.c.
 {
         switch(entry & ~1)
         {
                 case SD_CORE_NOISE_CLK:
                         return (*SD_CORE_ATTR(entry & 1) >> 8) & 0x3F;
                 case SD_CORE_SPDIF_MODE:
                         return SpdifSettings;
                 default:
                 {
                         u32 core = entry & 1;
                         entry = (entry >> 1)-1;
                         return (*SD_CORE_ATTR(core) >> CoreAttrShifts[entry]) & 1;
                 }
         }
 }
References CoreAttrShifts, SD_CORE_ATTR, SD_CORE_NOISE_CLK, SD_CORE_SPDIF_MODE, and SpdifSettings.
Referenced by rpc_server(), sceSdProcBatch(), and sceSdProcBatchEx().
sceSdGetParam()
u16 sceSdGetParam (u16 reg)
Definition at line 529 of file freesd.c.
 {
         u32 offs;
         u32 voice;
         u32 reg_index;
         u32 core;
         volatile u16 *reg_p;
         core = reg & 1;
         // Determine the channel offset
         if(reg & 0x80)
                 offs = (40 * core) >> 1;
         else
                 offs = (1024 * core) >> 1;
         reg_index = (reg >> 8) & 0xFF;
         voice = (reg & 0x3E) << 2;
         reg_p = ParamRegList[reg_index] + offs + voice;
         return *reg_p;
 }
References ParamRegList.
Referenced by rpc_server(), sceSdProcBatch(), and sceSdProcBatchEx().
sceSdGetSwitch()
u32 sceSdGetSwitch (u16 reg)
Definition at line 564 of file freesd.c.
 {
         u32 reg_index;
         volatile u16 *reg_p;
         u32 ret;
         reg_index = (reg >> 8) & 0xFF;
         reg_p = ParamRegList[reg_index] + ((reg & 1) << 9);
         ret =  reg_p[0];
         ret |= reg_p[1] << 16;
         return ret;
 }
References ParamRegList.
Referenced by audsrv_adpcm_alloc_channel(), audsrv_ch_play_adpcm(), rpc_server(), sceSdProcBatch(), and sceSdProcBatchEx().
sceSdInit()
int sceSdInit (int flag)
Definition at line 487 of file freesd.c.
 {
         flag &= 1;
         InitSpu2();
         InitSpdif();
         Reset(flag);
         InitVoices();
         InitCoreVolume(flag);
         EnableIntr(IOP_IRQ_DMA_SPU);
         EnableIntr(IOP_IRQ_DMA_SPU2);
         EnableIntr(IOP_IRQ_SPU);
         return 0;
 }
References EnableIntr(), InitCoreVolume(), InitSpdif(), InitSpu2(), InitVoices(), IOP_IRQ_DMA_SPU, IOP_IRQ_DMA_SPU2, IOP_IRQ_SPU, and Reset().
sceSdNote2Pitch()
u16 sceSdNote2Pitch (u16 center_note, u16 center_fine, u16 note, short fine)
Definition at line 611 of file freesd.c.
 {
         s32 _fine;
         s32 _fine2;
         s32 _note;
         s32 offset1, offset2;
         s32 val;
         s32 val2;
         s32 val3;
         s32 ret;
         _fine = fine + (u16)center_fine;
         _fine2 = _fine;
         if(_fine < 0) _fine2 = _fine + 127;
         _fine2 = _fine2 / 128;
         _note = note + _fine2 - center_note;
         val3 = _note / 6;
         if(_note < 0) val3--;
         offset2 = _fine - _fine2 * 128;
         if(_note < 0) val2 = -1; else val2 = 0;
         if(val3 < 0) val3--;
         val2 = (val3 / 2) - val2;
         val = val2 - 2;
         offset1 = _note - (val2 * 12);
         if((offset1 < 0) || ((offset1 == 0) && (offset2 < 0)))
         {
                 offset1 = offset1 + 12;
                 val = val2 - 3;
         }
         if(offset2 < 0)
         {
                 offset1 = (offset1-1) + _fine2;
                 offset2 += (_fine2+1) * 128;
         }
         ret = (NotePitchTable[offset1] * NotePitchTable[offset2 + 12]) / 0x10000;
         if(val < 0)     ret = (ret + (1 << (-val -1))) >> -val;
         return (u16)ret;
 }
References NotePitchTable.
Referenced by rpc_server().
sceSdPitch2Note()
u16 sceSdPitch2Note (u16 center_note, u16 center_fine, u16 pitch)
Definition at line 661 of file freesd.c.
 {
         s32 _pitch;
         s32 i = 0;
         s32 bit = 0;
         s32 offset1 = 0;
         s32 offset2 = 0;
         s32 val;
         s32 ret;
         if(((u16)pitch) >= 0x4000) pitch = 0x3FFF;
         _pitch = (u16)pitch;
         do
         {
                 if((_pitch & 1) == 1) bit = i;
                 _pitch >>= 1;
                 i++;
         } while(i < 14);
         val = (u16)pitch << (15 - bit);
         i = 11;
         do
         {
                 if((u16)val >= NotePitchTable[i])
                 {
                         offset1 = i;
                         break;
                 }
                 i--;
         } while(i >= 0);
         val = ((u16)val * 0x8000) / NotePitchTable[(u16)offset1];
         i = 127;
         do
         {
                 if((u16)val >= NotePitchTable[12 + i])
                 {
                         offset2 = i;
                         break;
                 }
                 i--;
         } while(i >= 0);
         val = (u16)(center_fine + offset2 +1);
         ret = (center_note + offset1 + ((bit - 12) * 12) + (val/128)) * 256;
         ret = (ret + (val & 0x7E)) & 0xFFFE;
         return (u16)ret;
 }
References NotePitchTable.
Referenced by rpc_server().
sceSdQuit()
int sceSdQuit ()
Definition at line 831 of file freesd.c.
 {
         s32 ret;
         DmaStop(0);
         DmaStop(1);
         DisableIntr(0x28, (int *)&ret);
         DisableIntr(0x24, (int *)&ret);
         DisableIntr(0x9, (int *)&ret);
         ReleaseIntrHandler(0x28);
         ReleaseIntrHandler(0x24);
         ReleaseIntrHandler(0x9);
         return 0;
 }
References DisableIntr(), DmaStop(), and ReleaseIntrHandler().
sceSdSetAddr()
void sceSdSetAddr (u16 reg, u32 val)
Definition at line 848 of file freesd.c.
 {
         volatile u16 *reg1;
         u16 voice;
         reg1 = ParamRegList[(reg >> 8) & 0xFF] + ((reg & 1) << 9);
         voice = reg & 0x3E;
         reg1 += ((voice << 1) + voice);
         *reg1++ = (val >> 17) & 0xFFFF;
         if((reg & 0xFF00) != 0x1D00)
         {
                 *reg1 = (val >> 1) & 0xFFF8;
         }
 }
References ParamRegList.
Referenced by audsrv_ch_play_adpcm(), rpc_server(), sceSdProcBatch(), sceSdProcBatchEx(), sndStreamSetPosition(), and stream_thread().
sceSdSetCoreAttr()
void sceSdSetCoreAttr (u16 entry, u16 val)
Definition at line 776 of file freesd.c.
 {
         u16 core_attr = *SD_CORE_ATTR(entry & 1);
         switch(entry & ~1)
         {
                 case SD_CORE_NOISE_CLK: // 0x8
                         *SD_CORE_ATTR(entry & 1) = (core_attr-0x3F01) | ((val & 0x3F) << 8);
                         break;
                 case SD_CORE_SPDIF_MODE: // 0xA
                         SetSpdifMode(val); // sub1
                         break;
                 default:
                 {
                         u32 core = entry & 1;
                         entry = (entry >> 1)-1;
                         core_attr &= ~(1 << CoreAttrShifts[entry]);
                         core_attr |= (val & 1) << CoreAttrShifts[entry];
                         *SD_CORE_ATTR(core) = core_attr;
                 }
                 break;
         }
 }
References CoreAttrShifts, SD_CORE_ATTR, SD_CORE_NOISE_CLK, SD_CORE_SPDIF_MODE, and SetSpdifMode().
sceSdSetIRQCallback()
SdIntrCallback sceSdSetIRQCallback (SdIntrCallback cb)
Definition at line 913 of file freesd.c.
 {
         SdIntrCallback old_cb;
         old_cb = Spu2IrqCallback;
         Spu2IrqCallback = cb;
         return old_cb;
 }
References Spu2IrqCallback.
sceSdSetParam()
void sceSdSetParam (u16 reg, u16 val)
Definition at line 506 of file freesd.c.
 {
         u32 offs;
         u32 voice;
         u32 reg_index;
         u32 core;
         volatile u16 *reg_p;
         core = reg & 1;
         // Determine the channel offset
         if(reg & 0x80)
                 offs = (40 * core) >> 1;
         else
                 offs = (1024 * core) >> 1;
         reg_index = (reg >> 8) & 0xFF;
         voice = (reg & 0x3E) << 2;
         reg_p = ParamRegList[reg_index] + offs + voice;
         *reg_p = val;
 }
References ParamRegList.
sceSdSetSpu2IntrHandler()
sceSdSpu2IntrHandler sceSdSetSpu2IntrHandler (sceSdSpu2IntrHandler handler, void * data)
Definition at line 327 of file freesd.c.
 {
         sceSdSpu2IntrHandler old_handler;
         old_handler = Spu2IntrHandler;
         Spu2IntrHandler = handler;
         Spu2IntrData = data;
         return old_handler;
 }
References handler, Spu2IntrData, and Spu2IntrHandler.
Referenced by sndStreamClose(), and sndStreamOpen().
sceSdSetSwitch()
void sceSdSetSwitch (u16 reg, u32 val)
Definition at line 552 of file freesd.c.
 {
         u32 reg_index;
         volatile u16 *reg_p;
         reg_index = (reg >> 8) & 0xFF;
         reg_p = ParamRegList[reg_index] + ((reg & 1) << 9);
         reg_p[0] = (u16)val;
         reg_p[1] = (u16)((val >> 16) & 0xFF);
 }
References ParamRegList.
Referenced by audsrv_adpcm_init(), audsrv_ch_play_adpcm(), rpc_server(), sceSdProcBatch(), sceSdProcBatchEx(), sndStreamPause(), and sndStreamPlay().
sceSdSetTransCallback()
SdIntrCallback sceSdSetTransCallback (s32 core, SdIntrCallback cb)
Definition at line 903 of file freesd.c.
 {
         SdIntrCallback old_cb;
         old_cb = TransIntrCallbacks[core & 1];
         TransIntrCallbacks[core & 1] = cb;
         return old_cb;
 }
References TransIntrCallbacks.
sceSdSetTransIntrHandler()
sceSdTransIntrHandler sceSdSetTransIntrHandler (int chan, sceSdTransIntrHandler func, void * data)
Definition at line 818 of file freesd.c.
 {
         sceSdTransIntrHandler old_handler;
         old_handler = TransIntrHandlers[chan & 1];
         TransIntrHandlers[chan & 1] = func;
         TransIntrData[chan & 1].data = data;
         return old_handler;
 }
References IntrData::data, TransIntrData, and TransIntrHandlers.
SetDmaRead()
void SetDmaRead (s32 chan)
Definition at line 605 of file freesd.c.
 {
         volatile u32 *reg = U32_REGISTER(0x1014 + (chan << 10));
         *reg = (*reg & 0xF0FFFFFF) | 0x22000000;
 }
References U32_REGISTER.
Referenced by BlockTransRead(), and VoiceTransDma().
SetDmaWrite()
void SetDmaWrite (s32 chan)
Definition at line 599 of file freesd.c.
 {
         volatile u32 *reg = U32_REGISTER(0x1014 + (chan << 10));
         *reg = (*reg & 0xF0FFFFFF) | 0x20000000;
 }
References U32_REGISTER.
Referenced by BlockTransWrite(), BlockTransWriteFrom(), and VoiceTransDma().
SetESA()
void SetESA (s32 core, u32 value)
Definition at line 77 of file effect.c.
 {
         volatile u16 *reg = SD_A_ESA_HI(core);
         reg[0] = value >> 17;
         reg[1] = value >> 1;
 }
References SD_A_ESA_HI.
Referenced by Reset(), and sceSdSetEffectAttr().
SetSpdifMode()
void SetSpdifMode (u16 val)
Definition at line 720 of file freesd.c.
 {
         u16 out, mode;
         out  = *SD_C_SPDIF_OUT;
         mode = *SD_C_SPDIF_MODE;
         switch(val & 0xF)
         {
                 case 0:
                         mode &= 0xFFFD;
                         out = (val & 0xFEF7) | 0x20;
                         break;
                 case 1:
                         mode |= 2;
                         out = (out & 0xFFD7) | 0x100;
                         break;
                 case 2:
                         out &= 0xFED7;
                         break;
                 case 0xF:
                         out = (out & 0xFEDF) | 8;
                         break;
                 default: return;
         }
         if(val & 0x80)
                 mode |= 0x8000;
         else
                 mode &= 0x7FFF;
         switch(val & 0xF00)
         {
                 case 0x800:
                         *SD_C_SPDIF_MEDIA = 0x200;
                         mode |= 0x1800;
                         break;
                 case 0x400 :
                         *SD_C_SPDIF_MEDIA = 0;
                         mode &= 0xE7FF;
                         break;
                 default:
                         *SD_C_SPDIF_MEDIA = 0x200;
                         mode = (mode & 0xE7FF) | 0x800;
                         break;
         }
         *SD_C_SPDIF_OUT = out;
         *SD_C_SPDIF_MODE = mode;
         SpdifSettings = val;
 }
References irx_export_table::mode, SD_C_SPDIF_MEDIA, SD_C_SPDIF_MODE, SD_C_SPDIF_OUT, and SpdifSettings.
Referenced by sceSdSetCoreAttr().
Spu2Interrupt()
int Spu2Interrupt (void * data)
Definition at line 197 of file freesd.c.
 {
         u16 val;
         val = ((*SD_C_IRQINFO)&0xc)>>2;
         if (!val)
                 return 1;
         if (val&1)
                 *SD_CORE_ATTR(0) = *SD_CORE_ATTR(0) & 0xffbf;
         if (val&2)
                 *SD_CORE_ATTR(1) = *SD_CORE_ATTR(1) & 0xffbf;
         if(Spu2IntrHandler != NULL)
         {
                 Spu2IntrHandler(val, Spu2IntrData);
         }
         else
         {
                 if(Spu2IrqCallback) Spu2IrqCallback(0);
         }
         return 1;
 }
References NULL, SD_CORE_ATTR, Spu2IntrData, Spu2IntrHandler, and Spu2IrqCallback.
Referenced by RegisterInterrupts().
TransInterrupt()
int TransInterrupt (void * data)
Definition at line 132 of file freesd.c.
 {
         IntrData *intr = (IntrData*) data;
         s32 dir;
         s32 core;
         dir = ((intr->mode & 0x200) < 1);
         core = intr->mode & 0xFF;
         // Voice Transfer
         if((intr->mode & 0x100) == 0)
         {
                 // SD_C_STATX(core)
                 // If done elsewise, it doesn't work, havn't figured out why yet.
                 volatile u16 *statx = U16_REGISTER(0x344 + (core * 1024));
                 if(!(*statx & 0x80))    while(!(*statx & 0x80));
                 *SD_CORE_ATTR(core) &= ~SD_CORE_DMA;
                 if(*SD_CORE_ATTR(core) & 0x30)  while((*SD_CORE_ATTR(core) & 0x30));
                 if(TransIntrHandlers[core])             goto intr_handler;
                 if(TransIntrCallbacks[core])    goto SdIntrCallback;
                 VoiceTransComplete[core] = 1;
         }
         else
         {       // Block Transfer
                 if(intr->mode & (SD_TRANS_LOOP << 8))
                 {
                         // Switch buffers
                         BlockTransBuff[core] = 1 - BlockTransBuff[core];
                         // Setup DMA & send
                         *SD_DMA_ADDR(core) = (BlockTransSize[core] * BlockTransBuff[core])+BlockTransAddr[core];
                         *SD_DMA_SIZE(core) = (BlockTransSize[core]/64)+((BlockTransSize[core]&63)>0);
                         *SD_DMA_CHCR(core) = SD_DMA_START | SD_DMA_CS | dir;
                 }
                 else
                 {
                         *SD_CORE_ATTR(core) &= ~SD_CORE_DMA;
                         *SD_P_MMIX(core)        &= 0xFF3F;
                         *U16_REGISTER(0x1B0 + (core * 1024)) = 0;
                 }
                 if(TransIntrHandlers[core])
                 {
                         intr_handler:
                         TransIntrHandlers[core](core, intr->data);
                 }
                 else
                 {
                         if(TransIntrCallbacks[core])
{
                                 SdIntrCallback:
                                 TransIntrCallbacks[core](0);
                         }
                 }
         }
         if(dir == SD_DMA_DIR_SPU2IOP)   FlushDcache();
         return 1;
 }
References BlockTransAddr, BlockTransBuff, BlockTransSize, IntrData::data, FlushDcache(), IntrData::mode, SD_CORE_ATTR, SD_CORE_DMA, SD_DMA_ADDR, SD_DMA_CHCR, SD_DMA_CS, SD_DMA_DIR_SPU2IOP, SD_DMA_SIZE, SD_DMA_START, SD_P_MMIX, SD_TRANS_LOOP, TransIntrCallbacks, TransIntrHandlers, U16_REGISTER, and VoiceTransComplete.
Referenced by RegisterInterrupts().
Variable Documentation
_exp_libsd
struct irx_export_table _exp_libsd extern
Referenced by _start().
BlockTransAddr
u32 BlockTransAddr[2] extern
Definition at line 25 of file spu2.c.
Referenced by BlockTransRead(), BlockTransWrite(), BlockTransWriteFrom(), and TransInterrupt().
BlockTransBuff
u32 BlockTransBuff[2] extern
Definition at line 24 of file spu2.c.
Referenced by BlockTransRead(), BlockTransWrite(), BlockTransWriteFrom(), DmaStop(), sceSdBlockTransStatus(), and TransInterrupt().
BlockTransSize
u32 BlockTransSize[2] extern
Definition at line 26 of file spu2.c.
Referenced by BlockTransRead(), BlockTransWrite(), BlockTransWriteFrom(), and TransInterrupt().
CoreAttrShifts
u8 CoreAttrShifts[4] = {7, 6, 14, 8}
Definition at line 774 of file freesd.c.
Referenced by sceSdGetCoreAttr(), and sceSdSetCoreAttr().
EffectAddr
u32 EffectAddr[2] extern
Definition at line 24 of file effect.c.
Referenced by Reset(), and sceSdSetEffectAttr().
EffectAttr
sceSdEffectAttr EffectAttr[2] extern
Definition at line 23 of file effect.c.
Referenced by Reset(), sceSdGetEffectAttr(), and sceSdSetEffectAttr().
EffectSizes
u32 EffectSizes[10] extern
Definition at line 27 of file effect.c.
Referenced by Reset(), sceSdClearEffectWorkArea(), and sceSdSetEffectAttr().
NotePitchTable
u16 NotePitchTable[]
Initial value:
=
{
        0x8000, 0x879C, 0x8FAC, 0x9837, 0xA145, 0xAADC, 0xB504,
        0xBFC8, 0xCB2F, 0xD744, 0xE411, 0xF1A1, 0x8000, 0x800E,
        0x801D, 0x802C, 0x803B, 0x804A, 0x8058, 0x8067, 0x8076,
        0x8085, 0x8094, 0x80A3, 0x80B1, 0x80C0, 0x80CF, 0x80DE,
        0x80ED, 0x80FC, 0x810B, 0x811A, 0x8129, 0x8138, 0x8146,
        0x8155, 0x8164, 0x8173, 0x8182, 0x8191, 0x81A0, 0x81AF,
        0x81BE, 0x81CD, 0x81DC, 0x81EB, 0x81FA, 0x8209, 0x8218,
        0x8227, 0x8236, 0x8245, 0x8254, 0x8263, 0x8272, 0x8282,
        0x8291, 0x82A0, 0x82AF, 0x82BE, 0x82CD, 0x82DC, 0x82EB,
        0x82FA, 0x830A, 0x8319, 0x8328, 0x8337, 0x8346, 0x8355,
        0x8364, 0x8374, 0x8383, 0x8392, 0x83A1, 0x83B0, 0x83C0,
        0x83CF, 0x83DE, 0x83ED, 0x83FD, 0x840C, 0x841B, 0x842A,
        0x843A, 0x8449, 0x8458, 0x8468, 0x8477, 0x8486, 0x8495,
        0x84A5, 0x84B4, 0x84C3, 0x84D3, 0x84E2, 0x84F1, 0x8501,
        0x8510, 0x8520, 0x852F, 0x853E, 0x854E, 0x855D, 0x856D,
        0x857C, 0x858B, 0x859B, 0x85AA, 0x85BA, 0x85C9, 0x85D9,
        0x85E8, 0x85F8, 0x8607, 0x8617, 0x8626, 0x8636, 0x8645,
        0x8655, 0x8664, 0x8674, 0x8683, 0x8693, 0x86A2, 0x86B2,
        0x86C1, 0x86D1, 0x86E0, 0x86F0, 0x8700, 0x870F, 0x871F,
        0x872E, 0x873E, 0x874E, 0x875D, 0x876D, 0x877D, 0x878C
}
Definition at line 77 of file freesd.c.
Referenced by sceSdNote2Pitch(), and sceSdPitch2Note().
ParamRegList
volatile u16* ParamRegList[]
Initial value:
=
{
        SD_VP_VOLL(0, 0),       SD_VP_VOLR(0, 0),       SD_VP_PITCH(0, 0),      SD_VP_ADSR1(0, 0),
        SD_VP_ADSR2(0, 0),      SD_VP_ENVX(0, 0),       SD_VP_VOLXL(0, 0),      SD_VP_VOLXR(0, 0),
        SD_P_MMIX(0),           SD_P_MVOLL(0),          SD_P_MVOLR(0),          SD_P_EVOLL(0),
        SD_P_EVOLR(0),          SD_P_AVOLL(0),          SD_P_AVOLR(0),          SD_P_BVOLL(0),
        SD_P_BVOLR(0),          SD_P_MVOLXL(0),         SD_P_MVOLXR(0),         SD_S_PMON_HI(0),
        SD_S_NON_HI(0),         SD_A_KON_HI(0),         SD_A_KOFF_HI(0),        SD_S_ENDX_HI(0),
        SD_S_VMIXL_HI(0),       SD_S_VMIXEL_HI(0),      SD_S_VMIXR_HI(0),       SD_S_VMIXER_HI(0),
        SD_A_ESA_HI(0),         SD_A_EEA_HI(0),         SD_A_TSA_HI(0),         SD_CORE_IRQA(0),
        SD_VA_SSA_HI(0, 0),     SD_VA_LSAX(0,0),        SD_VA_NAX(0, 0),        SD_CORE_ATTR(0),
        SD_A_TSA_HI(0),         SD_A_STD(0),
        U16_REGISTER(0x1AE),    U16_REGISTER(0x1B0),
        (u16*)0xBF900334
}
Definition at line 59 of file freesd.c.
Referenced by sceSdGetAddr(), sceSdGetParam(), sceSdGetSwitch(), sceSdSetAddr(), sceSdSetParam(), and sceSdSetSwitch().
SpdifSettings
u16 SpdifSettings
Definition at line 50 of file freesd.c.
Referenced by sceSdGetCoreAttr(), and SetSpdifMode().
Spu2IntrData
void* Spu2IntrData
Definition at line 51 of file freesd.c.
Referenced by RegisterInterrupts(), Reset(), sceSdSetSpu2IntrHandler(), and Spu2Interrupt().
Spu2IntrHandler
sceSdSpu2IntrHandler Spu2IntrHandler
Definition at line 54 of file freesd.c.
Referenced by Reset(), sceSdSetSpu2IntrHandler(), and Spu2Interrupt().
Spu2IrqCallback
SdIntrCallback Spu2IrqCallback
Definition at line 55 of file freesd.c.
Referenced by Reset(), sceSdSetIRQCallback(), and Spu2Interrupt().
TransIntrCallbacks
SdIntrCallback TransIntrCallbacks[2]
Definition at line 53 of file freesd.c.
Referenced by Reset(), sceSdClearEffectWorkArea(), sceSdSetTransCallback(), and TransInterrupt().
TransIntrData
IntrData TransIntrData[2]
Definition at line 56 of file freesd.c.
Referenced by RegisterInterrupts(), Reset(), sceSdBlockTrans(), sceSdSetTransIntrHandler(), VoiceTrans_Write_IOMode(), and VoiceTransDma().
TransIntrHandlers
sceSdTransIntrHandler TransIntrHandlers[2]
Definition at line 52 of file freesd.c.
Referenced by Reset(), sceSdClearEffectWorkArea(), sceSdSetTransIntrHandler(), and TransInterrupt().
VoiceDataInit
u16 VoiceDataInit[16]
Initial value:
= { 0x707, 0x707, 0x707, 0x707, 0x707, 0x707, 0x707, 0x707,
                                                0,     0,     0,     0,     0,     0,     0,     0 }
Definition at line 338 of file freesd.c.
Referenced by InitVoices().
VoiceTransComplete
volatile u16 VoiceTransComplete[2] extern
Definition at line 31 of file spu2.c.
Referenced by RegisterInterrupts(), sceSdVoiceTransStatus(), and TransInterrupt().
VoiceTransIoMode
u32 VoiceTransIoMode[2] extern
Definition at line 32 of file spu2.c.
Referenced by Reset(), ResetAll(), sceSdVoiceTrans(), and sceSdVoiceTransStatus().
VoiceTransStatus
u32 VoiceTransStatus[2] extern
Definition at line 30 of file spu2.c.
Referenced by Reset(), sceSdVoiceTrans(), and sceSdVoiceTransStatus().