ps2sdk: iop/fs/bdmfs_vfat/src/include/common.h File Reference
common.h File Reference
Macros
#define USBHD_INLINE inline
#define getI32(buf) ((int)(((u8*)(buf))[0] + (((u8*)(buf))[1] << 8) + (((u8*)(buf))[2] << 16) + (((u8*)(buf))[3] << 24)))
#define getI32_2(buf1, buf2) ((int)(((u8*)(buf1))[0] + (((u8*)(buf1))[1] << 8) + (((u8*)(buf2))[0] << 16) + (((u8*)(buf2))[1] << 24)))
#define getI16(buf) ((int)(((u8*)(buf))[0] + (((u8*)(buf))[1] << 8)))
Functions
void * malloc (int size)
void free (void *ptr)
Macro Definition Documentation
getI16
#define getI16 (buf) ((int)(((u8*)(buf))[0] + (((u8*)(buf))[1] << 8)))
Definition at line 16 of file common.h.
getI32
#define getI32 (buf) ((int)(((u8*)(buf))[0] + (((u8*)(buf))[1] << 8) + (((u8*)(buf))[2] << 16) + (((u8*)(buf))[3] << 24)))
Definition at line 14 of file common.h.
getI32_2
#define getI32_2 (buf1, buf2) ((int)(((u8*)(buf1))[0] + (((u8*)(buf1))[1] << 8) + (((u8*)(buf2))[0] << 16) + (((u8*)(buf2))[1] << 24)))
Definition at line 15 of file common.h.
USBHD_INLINE
#define USBHD_INLINE inline
Definition at line 8 of file common.h.
Function Documentation
free()
void free (void * ptr)
Definition at line 662 of file sbp2_driver.c.
 {
     int OldState;
     CpuSuspendIntr(&OldState);
     FreeSysMemory(buffer);
     CpuResumeIntr(OldState);
 }
References buffer, CpuResumeIntr(), CpuSuspendIntr(), and FreeSysMemory().
malloc()
void * malloc (int size)
Definition at line 650 of file sbp2_driver.c.
 {
     int OldState;
     void* buffer;
     CpuSuspendIntr(&OldState);
     buffer = AllocSysMemory(ALLOC_FIRST, NumBytes, NULL);
     CpuResumeIntr(OldState);
     return buffer;
 }
References ALLOC_FIRST, AllocSysMemory(), buffer, CpuResumeIntr(), CpuSuspendIntr(), and NULL.