ps2sdk: iop/fs/bdm/src/part_driver.c File Reference
part_driver.c File Reference
#include <errno.h>
#include <stdio.h>
#include <bdm.h>
#include "module_debug.h"
Data Structures
struct part_record
struct part_table
struct part_raw_record
struct partition
Macros
#define getI32(buf) ((int)(((u8*)(buf))[0] + (((u8*)(buf))[1] << 8) + (((u8*)(buf))[2] << 16) + (((u8*)(buf))[3] << 24)))
#define MAX_PARTITIONS 10
Functions
static int part_getPartitionRecord (struct block_device *bd, part_raw_record *raw, part_record *rec)
static int part_getPartitionTable (struct block_device *bd, part_table *part)
void part_create (struct block_device *bd, part_record *rec, unsigned int parNr)
int part_connect (struct block_device *bd)
void part_disconnect (struct block_device *bd)
static int part_read (struct block_device *bd, u32 sector, void *buffer, u16 count)
static int part_write (struct block_device *bd, u32 sector, const void *buffer, u16 count)
static void part_flush (struct block_device *bd)
void part_init ()
Variables
static struct partition g_part [MAX_PARTITIONS]
static struct block_device g_part_bd [MAX_PARTITIONS]
static struct file_system g_part_fs
static unsigned char sbuf [512]
Macro Definition Documentation
getI32
#define getI32 (buf) ((int)(((u8*)(buf))[0] + (((u8*)(buf))[1] << 8) + (((u8*)(buf))[2] << 16) + (((u8*)(buf))[3] << 24)))
Definition at line 9 of file part_driver.c.
MAX_PARTITIONS
#define MAX_PARTITIONS 10
Definition at line 38 of file part_driver.c.
Function Documentation
part_connect()
int part_connect (struct block_device * bd)
Definition at line 118 of file part_driver.c.
 {
     part_table partTable;
     unsigned int i;
     int parts;
     int rval = -1;
     M_DEBUG("%s\n", __func__);
     if ((parts = part_getPartitionTable(bd, &partTable)) <= 0)
         return rval;
     for (i = 0; i < parts; i++) {
         if (partTable.record[i].sid != 0x00) {
             M_DEBUG("mount partition %d id %02x\n", i, partTable.record[i].sid);
             part_create(bd, &partTable.record[i], i);
             rval = 0;
         }
     }
     return rval;
 }
References M_DEBUG, part_create(), part_getPartitionTable(), part_table::record, and part_record::sid.
Referenced by ConfigureSBP2Device(), mass_stor_configureNextDevice(), and part_init().
part_create()
void part_create (struct block_device * bd, part_record * rec, unsigned int parNr)
Definition at line 96 of file part_driver.c.
 {
     int i;
     M_DEBUG("%s\n", __func__);
     for (i = 0; i < MAX_PARTITIONS; ++i) {
         if (g_part[i].bd == NULL) {
             g_part[i].bd              = bd;
             g_part_bd[i].name         = bd->name;
             g_part_bd[i].devNr        = bd->devNr;
             g_part_bd[i].parNr        = parNr + 1;
             g_part_bd[i].sectorSize   = bd->sectorSize;
             g_part_bd[i].sectorOffset = bd->sectorOffset + rec->start;
             g_part_bd[i].sectorCount  = rec->count;
             bdm_connect_bd(&g_part_bd[i]);
             break;
         }
     }
 }
References partition::bd, bdm_connect_bd(), part_record::count, block_device::devNr, g_part, g_part_bd, M_DEBUG, MAX_PARTITIONS, block_device::name, NULL, block_device::parNr, block_device::sectorCount, block_device::sectorOffset, block_device::sectorSize, and part_record::start.
Referenced by part_connect().
part_disconnect()
void part_disconnect (struct block_device * bd)
Definition at line 142 of file part_driver.c.
 {
     int i;
     M_DEBUG("%s\n", __func__);
     for (i = 0; i < MAX_PARTITIONS; ++i) {
         if (g_part[i].bd == bd) {
             bdm_disconnect_bd(&g_part_bd[i]);
             g_part[i].bd = NULL;
         }
     }
 }
References partition::bd, bdm_disconnect_bd(), g_part, g_part_bd, M_DEBUG, MAX_PARTITIONS, and NULL.
Referenced by mass_stor_disconnect(), part_init(), and releaseSBP2Device().
part_flush()
static void part_flush (struct block_device * bd) static
Definition at line 183 of file part_driver.c.
 {
     struct partition* part = (struct partition*)bd->priv;
     M_DEBUG("%s\n", __func__);
     if ((part == NULL) || (part->bd == NULL))
         return;
     return part->bd->flush(part->bd);
 }
References partition::bd, block_device::flush, M_DEBUG, NULL, and block_device::priv.
Referenced by part_init().
part_getPartitionRecord()
static int part_getPartitionRecord (struct block_device * bd, part_raw_record * raw, part_record * rec) static
Definition at line 44 of file part_driver.c.
 {
     M_DEBUG("%s\n", __func__);
     rec->sid   = raw->sid;
     rec->start = getI32(raw->startLBA);
     rec->count = getI32(raw->size);
     if (rec->sid != 0x00) { /*  Windows appears to check if the start LBA is not 0 and whether the start LBA is within the disk.
                         There may be checks against the size, but I didn't manage to identify a pattern.
                         If the disk has no partition table (i.e. disks with "removable" media), then this check is also one safeguard. */
         if ((rec->start == 0) || (rec->start >= bd->sectorCount))
             return 1;
     }
     return 0;
 }
References part_record::count, getI32, M_DEBUG, block_device::sectorCount, part_record::sid, part_raw_record::sid, part_raw_record::size, part_record::start, and part_raw_record::startLBA.
Referenced by part_getPartitionTable().
part_getPartitionTable()
static int part_getPartitionTable (struct block_device * bd, part_table * part) static
Definition at line 65 of file part_driver.c.
 {
     part_raw_record* part_raw;
     int ret;
     unsigned int i;
     M_DEBUG("%s\n", __func__);
     ret = bd->read(bd, bd->sectorOffset, sbuf, 1); // read sector 0 - Disk MBR or boot sector
     if (ret < 0) {
         M_DEBUG("ERROR: part_getPartitionTable read failed %d!\n", ret);
         return -EIO;
     }
     M_DEBUG("boot signature %X %X\n", sbuf[0x1FE], sbuf[0x1FF]);
     if (sbuf[0x1FE] == 0x55 && sbuf[0x1FF] == 0xAA) {
         for (i = 0; i < 4; i++) {
             part_raw = (part_raw_record*)(sbuf + 0x01BE + (i * 16));
             if (part_getPartitionRecord(bd, part_raw, &part->record[i]) != 0)
                 return 0; //Invalid record encountered, so the table is probably invalid.
         }
         return 4;
     } else {
         for (i = 0; i < 4; i++) {
             part->record[i].sid = 0;
         }
         return 0;
     }
 }
References EIO, M_DEBUG, part_getPartitionRecord(), block_device::read, part_table::record, sbuf, block_device::sectorOffset, and part_record::sid.
Referenced by part_connect().
part_init()
void part_init ()
Definition at line 195 of file part_driver.c.
 {
     int i;
     M_DEBUG("%s\n", __func__);
     for (i = 0; i < MAX_PARTITIONS; ++i) {
         g_part[i].bd = NULL;
         g_part_bd[i].priv  = &g_part[i];
         g_part_bd[i].read  = part_read;
         g_part_bd[i].write = part_write;
         g_part_bd[i].flush = part_flush;
     }
     g_part_fs.priv          = NULL;
     g_part_fs.name          = "MBR";
     g_part_fs.connect_bd    = part_connect;
     g_part_fs.disconnect_bd = part_disconnect;
     bdm_connect_fs(&g_part_fs);
 }
References partition::bd, bdm_connect_fs(), file_system::connect_bd, file_system::disconnect_bd, block_device::flush, g_part, g_part_bd, g_part_fs, M_DEBUG, MAX_PARTITIONS, file_system::name, NULL, part_connect(), part_disconnect(), part_flush(), part_read(), part_write(), block_device::priv, file_system::priv, block_device::read, and block_device::write.
Referenced by _start().
part_read()
static int part_read (struct block_device * bd, u32 sector, void * buffer, u16 count) static
Definition at line 159 of file part_driver.c.
 {
     struct partition* part = (struct partition*)bd->priv;
     M_DEBUG("%s\n", __func__);
     if ((part == NULL) || (part->bd == NULL))
         return -1;
     return part->bd->read(part->bd, sector, buffer, count);
 }
References partition::bd, buffer, M_DEBUG, NULL, block_device::priv, and block_device::read.
Referenced by part_init().
part_write()
static int part_write (struct block_device * bd, u32 sector, const void * buffer, u16 count) static
Definition at line 171 of file part_driver.c.
 {
     struct partition* part = (struct partition*)bd->priv;
     M_DEBUG("%s\n", __func__);
     if ((part == NULL) || (part->bd == NULL))
         return -1;
     return part->bd->write(part->bd, sector, buffer, count);
 }
References partition::bd, buffer, M_DEBUG, NULL, block_device::priv, and block_device::write.
Referenced by part_init().
Variable Documentation
g_part
struct partition g_part[MAX_PARTITIONS] static
Definition at line 1 of file part_driver.c.
Referenced by part_create(), part_disconnect(), and part_init().
g_part_bd
struct block_device g_part_bd[MAX_PARTITIONS] static
Definition at line 1 of file part_driver.c.
Referenced by part_create(), part_disconnect(), and part_init().
g_part_fs
struct file_system g_part_fs static
Definition at line 1 of file part_driver.c.
Referenced by part_init().
sbuf
unsigned char sbuf[512] static
Definition at line 64 of file part_driver.c.
Referenced by createDirectorySpace(), enlargeDirentryClusterSpace(), fat_fillDirentryInfo(), fat_getClusterChain12(), fat_getClusterChain16(), fat_getClusterChain32(), fat_getDirentryStartCluster(), fat_getNextDirentry(), fat_getPartitionBootSector(), fat_readEmptyClusters12(), fat_readEmptyClusters16(), fat_readEmptyClusters32(), fat_readFile(), fat_readSingleSector(), fat_renameFile(), fat_saveClusterRecord12(), fat_saveClusterRecord16(), fat_saveClusterRecord32(), fat_truncateFile(), fat_updateSfn(), fat_wipeDirEntries(), fat_writeFile(), fat_writeSingleSector(), part_getPartitionTable(), saveDirentry(), and updateDirectoryParent().