ps2sdk: iop/fs/bdm/src/main.c File Reference
main.c File Reference
#include <bdm.h>
#include <irx.h>
#include <loadcore.h>
#include <stdio.h>
#include "module_debug.h"
Macros
#define MAJOR_VER 1
#define MINOR_VER 1
Functions
IRX_ID ("bdm", MAJOR_VER, MINOR_VER)
int bdm_init ()
void part_init ()
int _start (int argc, char *argv[])
Variables
struct irx_export_table _exp_bdm
Macro Definition Documentation
MAJOR_VER
#define MAJOR_VER 1
Definition at line 9 of file main.c.
MINOR_VER
#define MINOR_VER 1
Definition at line 10 of file main.c.
Function Documentation
_start()
int _start (int argc, char * argv[])
Definition at line 18 of file main.c.
 {
     printf("Block Device Manager (BDM) v%d.%d\n", MAJOR_VER, MINOR_VER);
     if (RegisterLibraryEntries(&_exp_bdm) != 0) {
         M_PRINTF("ERROR: Already registered!\n");
         return MODULE_NO_RESIDENT_END;
     }
     // initialize the block device manager
     if (bdm_init() < 0) {
         M_PRINTF("ERROR: BDM init failed!\n");
         return MODULE_NO_RESIDENT_END;
     }
     // initialize the partition driver
     part_init();
     // return resident
     return MODULE_RESIDENT_END;
 }
References _exp_bdm, bdm_init(), M_PRINTF, MAJOR_VER, MINOR_VER, MODULE_NO_RESIDENT_END, MODULE_RESIDENT_END, part_init(), printf(), and RegisterLibraryEntries().
bdm_init()
int bdm_init ()
Definition at line 183 of file bdm.c.
 {
     int i, result;
     iop_event_t EventFlagData;
     iop_thread_t ThreadData;
     M_DEBUG("%s\n", __func__);
     for (i = 0; i < MAX_CONNECTIONS; ++i) {
         g_mount[i].bd = NULL;
         g_mount[i].fs = NULL;
         g_fs[i]       = NULL;
     }
     EventFlagData.attr   = 0;
     EventFlagData.option = 0;
     EventFlagData.bits   = 0;
     result = bdm_event = CreateEventFlag(&EventFlagData);
     if (result < 0) {
         M_DEBUG("ERROR: CreateEventFlag %d\n", result);
         return result;
     }
     ThreadData.attr      = TH_C;
     ThreadData.thread    = bdm_thread;
     ThreadData.option    = 0;
     ThreadData.priority  = 0x30;   // Low priority
     ThreadData.stacksize = 0x1000; // 4KiB
     result = bdm_thread_id = CreateThread(&ThreadData);
     if (result < 0) {
         M_DEBUG("ERROR: CreateThread %d\n", result);
         DeleteEventFlag(bdm_event);
         return result;
     }
     result = StartThread(bdm_thread_id, NULL);
     if (result < 0) {
         M_DEBUG("ERROR: StartThread %d\n", result);
         DeleteThread(bdm_thread_id);
         DeleteEventFlag(bdm_event);
         return result;
     }
     return 0;
 }
References iop_thread_t::attr, iop_event_t::attr, bdm_mounts::bd, bdm_event, bdm_thread(), bdm_thread_id, iop_event_t::bits, CreateEventFlag(), CreateThread(), DeleteEventFlag(), DeleteThread(), EventFlagData, bdm_mounts::fs, g_fs, g_mount, M_DEBUG, MAX_CONNECTIONS, NULL, iop_thread_t::option, iop_event_t::option, iop_thread_t::priority, result, iop_thread_t::stacksize, StartThread(), TH_C, and iop_thread_t::thread.
Referenced by _start().
IRX_ID()
IRX_ID ("bdm" , MAJOR_VER , MINOR_VER)
part_init()
void part_init ()
Definition at line 195 of file part_driver.c.
 {
     int i;
     M_DEBUG("%s\n", __func__);
     for (i = 0; i < MAX_PARTITIONS; ++i) {
         g_part[i].bd = NULL;
         g_part_bd[i].priv  = &g_part[i];
         g_part_bd[i].read  = part_read;
         g_part_bd[i].write = part_write;
         g_part_bd[i].flush = part_flush;
     }
     g_part_fs.priv          = NULL;
     g_part_fs.name          = "MBR";
     g_part_fs.connect_bd    = part_connect;
     g_part_fs.disconnect_bd = part_disconnect;
     bdm_connect_fs(&g_part_fs);
 }
References partition::bd, bdm_connect_fs(), file_system::connect_bd, file_system::disconnect_bd, block_device::flush, g_part, g_part_bd, g_part_fs, M_DEBUG, MAX_PARTITIONS, file_system::name, NULL, part_connect(), part_disconnect(), part_flush(), part_read(), part_write(), block_device::priv, file_system::priv, block_device::read, and block_device::write.
Referenced by _start().
Variable Documentation
_exp_bdm
struct irx_export_table _exp_bdm extern
Referenced by _start().