ps2sdk: iop/fs/bdmfs_vfat/src/main.c File Reference
main.c File Reference
#include <bdm.h>
#include <intrman.h>
#include <irx.h>
#include <loadcore.h>
#include <stdio.h>
#include <sysmem.h>
#include "fat_driver.h"
#include "module_debug.h"
Macros
#define MAJOR_VER 1
#define MINOR_VER 1
Functions
IRX_ID ("bdmvfat", MAJOR_VER, MINOR_VER)
int InitFAT (void)
int InitFS (void)
int _start (int argc, char *argv[])
void * malloc (int size)
void free (void *ptr)
Variables
static struct file_system g_fs
Macro Definition Documentation
MAJOR_VER
#define MAJOR_VER 1
Definition at line 13 of file main.c.
MINOR_VER
#define MINOR_VER 1
Definition at line 14 of file main.c.
Function Documentation
_start()
int _start (int argc, char * argv[])
Definition at line 28 of file main.c.
 {
     printf("BDM VFAT driver (FAT12/16/32) v%d.%d\n", MAJOR_VER, MINOR_VER);
     // initialize the FAT driver
     if (InitFAT() != 0) {
         M_DEBUG("Error initializing FAT driver!\n");
         return MODULE_NO_RESIDENT_END;
     }
     // initialize the file system driver
     if (InitFS() != 0) {
         M_DEBUG("Error initializing FS driver!\n");
         return MODULE_NO_RESIDENT_END;
     }
     // Connect to block device manager
     bdm_connect_fs(&g_fs);
     // return resident
     return MODULE_RESIDENT_END;
 }
References bdm_connect_fs(), g_fs, InitFAT(), InitFS(), M_DEBUG, MAJOR_VER, MINOR_VER, MODULE_NO_RESIDENT_END, MODULE_RESIDENT_END, and printf().
free()
void free (void * ptr)
Definition at line 63 of file main.c.
 {
     int OldState;
     CpuSuspendIntr(&OldState);
     FreeSysMemory(ptr);
     CpuResumeIntr(OldState);
 }
References CpuResumeIntr(), CpuSuspendIntr(), and FreeSysMemory().
Referenced by mcman_findfree1().
InitFAT()
int InitFAT (void)
Definition at line 23 of file fat_driver.c.
 {
     int i;
     M_DEBUG("%s\n", __func__);
     for (i = 0; i < NUM_DRIVES; ++i)
         g_fatd[i] = NULL;
     return 0;
 }
Referenced by _start().
InitFS()
int InitFS (void)
Definition at line 905 of file fs_driver.c.
 {
     M_DEBUG("%s\n", __func__);
     DelDrv("mass");
     return (AddDrv(&fs_driver) == 0 ? 0 : -1);
 }
Referenced by _start().
IRX_ID()
IRX_ID ("bdmvfat" , MAJOR_VER , MINOR_VER)
malloc()
void* malloc (int size)
Definition at line 51 of file main.c.
 {
     void* result;
     int OldState;
     CpuSuspendIntr(&OldState);
     result = AllocSysMemory(ALLOC_FIRST, size, NULL);
     CpuResumeIntr(OldState);
     return result;
 }
References ALLOC_FIRST, AllocSysMemory(), CpuResumeIntr(), CpuSuspendIntr(), NULL, and result.
Variable Documentation
g_fs
struct file_system g_fs static
Initial value:
= {
    .priv          = NULL,
    .name          = "vfat",
    .connect_bd    = fat_mount,
    .disconnect_bd = fat_forceUnmount,
}
Definition at line 19 of file main.c.
Referenced by _start().