ps2sdk: fakehost - host: to hdd driver
fakehost - host: to hdd driver
Functions
char * fd_name (char *buffer, const char *name)
int fd_save (int fd, iop_io_file_t *f)
int realfd (iop_io_file_t *f)
int dummy ()
int fd_initialize (iop_io_device_t *driver)
int fd_open (iop_io_file_t *f, const char *name, int mode)
int fd_close (iop_io_file_t *f)
int fd_read (iop_io_file_t *f, void *buffer, int size)
int fd_write (iop_io_file_t *fd, void *buffer, int size)
int fd_lseek (iop_io_file_t *fd, int offset, int whence)
int _start (int argc, char **argv)
static void * naplinkRpcHandler (int cmd, void *buffer, int size)
static void napThread (void *arg)
int naplinkRpcInit (void)
Detailed Description
Function Documentation
_start()
int _start (int argc, char ** argv)
Entry point for IRX.
if argc != 2 , quit, as it needs parameter if argc == 2 , use arv[1] as basename.
Parameters
argc Number of arguments.
argv Pointer to array of arguments.
Returns
Module Status on Exit.
This initialises the fakehost driver, setting up the 'host:' fs driver basename redirection, and naplink compatible rpc hander.
return values: MODULE_RESIDENT_END if loaded and registered as library. MODULE_NO_RESIDENT_END if just exiting normally.
Definition at line 214 of file fakehost.c.
 {
         printf( "fakehost: Copyright (c) 2004 adresd\n" );
         if ( argc != 2 )
         {
                 printf( "HOST requires based argument\n" );
                 return -1;
         }
       else
       {
                 // Copy the base location.
                 strncpy( base, argv[1] ,sizeof(base) - 1);
                 base[sizeof(base) - 1] = '\0';
         printf("redirecting '%s:' to '%s'\n",FS_REPNAME,base);
                 fd_global = 1;
                 driver.name = FS_REPNAME;
                 driver.type = 16;
                 driver.version = 1;
                 driver.desc = "host redirection driver";
                 driver.ops = &functions;
                 functions.io_init = fd_initialize;
                 functions.io_deinit = dummy;
                 functions.io_format = dummy;
                 functions.io_open = fd_open;
                 functions.io_close = fd_close;
                 functions.io_read = fd_read;
                 functions.io_write = dummy;
                 functions.io_lseek = fd_lseek;
                 functions.io_ioctl = dummy;
                 functions.io_remove = dummy;
                 functions.io_mkdir = dummy;
                 functions.io_rmdir = dummy;
                 functions.io_dopen =  dummy;
                 functions.io_dclose = dummy;
                 functions.io_dread = dummy;
                 functions.io_getstat = dummy;
                 functions.io_chstat = dummy;
                 printf( "HOST final step, bye\n" );
                 // Install naplink RPC handler
                 naplinkRpcInit();
         // now install the fileio driver
                 io_DelDrv( FS_REPNAME );
                 io_AddDrv( &driver );
         }
         return 0;
 }
References base, iop_io_device_t::desc, driver, dummy(), fd_close(), fd_global, fd_initialize(), fd_lseek(), fd_open(), fd_read(), FS_REPNAME, functions, io_AddDrv(), iop_io_device_ops_t::io_chstat, iop_io_device_ops_t::io_close, iop_io_device_ops_t::io_dclose, iop_io_device_ops_t::io_deinit, io_DelDrv(), iop_io_device_ops_t::io_dopen, iop_io_device_ops_t::io_dread, iop_io_device_ops_t::io_format, iop_io_device_ops_t::io_getstat, iop_io_device_ops_t::io_init, iop_io_device_ops_t::io_ioctl, iop_io_device_ops_t::io_lseek, iop_io_device_ops_t::io_mkdir, iop_io_device_ops_t::io_open, iop_io_device_ops_t::io_read, iop_io_device_ops_t::io_remove, iop_io_device_ops_t::io_rmdir, iop_io_device_ops_t::io_write, iop_io_device_t::name, naplinkRpcInit(), iop_io_device_t::ops, printf(), strncpy(), iop_io_device_t::type, and iop_io_device_t::version.
dummy()
int dummy ()
Dummy function, for where needed.
Definition at line 105 of file fakehost.c.
 {
 #ifdef DEBUG_T
         printf("fakehost: dummy function called\n");
 #endif
         return -5;
 }
References printf().
Referenced by _start(), ata_io_start(), ieee1394_ResetFetchAgent(), init_devfs(), initialize_cdda(), and smb_Disconnect().
fd_close()
int fd_close (iop_io_file_t * f)
Handle close request.
Parameters
f Pointer to io_device structure.
Returns
Status (as for fileio close).
Definition at line 153 of file fakehost.c.
 {
         return close( realfd(f) );
 }
References close(), and realfd().
Referenced by _start().
fd_initialize()
int fd_initialize (iop_io_device_t * driver)
Initialise fs driver.
Parameters
driver io_device pointer to device
Returns
Status (0=successful).
Definition at line 119 of file fakehost.c.
 {
         printf("fakehost: initializing '%s' file driver.\n", driver->name );
         return 0;
 }
References driver, iop_io_device_t::name, and printf().
Referenced by _start().
fd_lseek()
int fd_lseek (iop_io_file_t * fd, int offset, int whence)
Handle lseek request.
Parameters
f Pointer to io_device structure.
offset Offset for seek.
whence Base for seek.
Returns
Status (as for fileio lseek).
Definition at line 192 of file fakehost.c.
 {
         return lseek( realfd(fd), offset, whence );
 }
References lseek(), and realfd().
Referenced by _start().
fd_name()
char* fd_name (char * buffer, const char * name)
Make a full pathname string, adding base on.
Parameters
buffer buffer to hold result.
name name to add base to.
Returns
Pointer to buffer.
This function takes the name param and adds it to the basename for replacement, returning the destination full pathname.
Definition at line 70 of file fakehost.c.
 {
         strcpy( buffer, base );
         strcat( buffer, name );
         return buffer;
 }
References base, buffer, strcat(), and strcpy().
Referenced by fd_open().
fd_open()
int fd_open (iop_io_file_t * f, const char * name, int mode)
Handle open request.
Parameters
f Pointer to io_device structure.
name pathname.
mode open mode.
Returns
Status (as for fileio open).
Definition at line 133 of file fakehost.c.
 {
         char nameBuffer[ 250 ];
         int fd;
 #ifdef DEBUG_T
         printf( "fakehost: open %i %s %s\n", f->unit, name ,base);
 #endif
         fd = open( fd_name( nameBuffer, name), mode, 0 );
         if ( fd < 0 ) return fd;
         return fd_save( fd, f );
 }
References base, fd_name(), fd_save(), open(), printf(), and iop_io_file_t::unit.
Referenced by _start().
fd_read()
int fd_read (iop_io_file_t * f, void * buffer, int size)
Handle read request.
Parameters
f Pointer to io_device structure.
buffer Pointer to read buffer.
size Size of buffer.
Returns
Status (as for fileio read).
Definition at line 166 of file fakehost.c.
 {
         return read( realfd(f), buffer, size );
 }
References buffer, read(), and realfd().
Referenced by _start().
fd_save()
int fd_save (int fd, iop_io_file_t * f)
Store filedescriptor and get client filedescriptor.
Parameters
fd filedescriptor to store.
f io_file pointer to store fd in .
Returns
client filedescriptor.
Definition at line 84 of file fakehost.c.
 {
         f->unit = ++fd_global;
         f->privdata = (void *) fd;
         return f->unit;
 }
References fd_global, iop_io_file_t::privdata, and iop_io_file_t::unit.
Referenced by fd_open().
fd_write()
int fd_write (iop_io_file_t * fd, void * buffer, int size)
Handle write request.
Parameters
f Pointer to io_device structure.
buffer Pointer to read buffer.
size Size of buffer.
Returns
Status (as for fileio write).
Definition at line 179 of file fakehost.c.
 {
         return write( realfd(fd), buffer, size );
 }
References buffer, realfd(), and write().
naplinkRpcHandler()
static void* naplinkRpcHandler (int cmd, void * buffer, int size) static
RPC handler function.
Parameters
cmd Command.
buffer Pointer to buffer.
size Size of buffer.
Definition at line 38 of file nprintf.c.
 {
     return buffer;
 }
References buffer.
Referenced by napThread().
naplinkRpcInit()
int naplinkRpcInit (void)
Setup naplink compatible RPC handler.
Returns
Status.
return values: 0 on success. -1 on error.
Definition at line 75 of file nprintf.c.
 {
     iop_thread_t th_attr;
     int ret;
     int pid;
     th_attr.attr = 0x02000000;
     th_attr.option = 0;
     th_attr.thread = napThread;
     th_attr.stacksize = 0x800;
     th_attr.priority = 0x4f;
     pid = CreateThread(&th_attr);
     if (pid < 0) {
         printf("IOP: napRpc createThread failed %d\n", pid);
         return -1;
     }
     ret = StartThread(pid, 0);
     if (ret < 0) {
         printf("IOP: napRpc startThread failed %d\n", ret);
         DeleteThread(pid);
         return -1;
     }
     return 0;
 }
References iop_thread_t::attr, CreateThread(), DeleteThread(), napThread(), iop_thread_t::option, printf(), iop_thread_t::priority, iop_thread_t::stacksize, StartThread(), and iop_thread_t::thread.
Referenced by _start().
napThread()
static void napThread (void * arg) static
naplink compatbile RPC handler thread.
Parameters
arg Startup parameters.
Definition at line 53 of file nprintf.c.
 {
     int pid;
     SifInitRpc(0);
     pid = GetThreadId();
     SifSetRpcQueue(&queue, pid);
     SifRegisterRpc(&server, RPC_NPM_USER, naplinkRpcHandler,
                    rpc_buffer, 0, 0, &queue);
     SifRpcLoop(&queue);  // Never exits
     ExitDeleteThread();
 }
References ExitDeleteThread(), GetThreadId(), naplinkRpcHandler(), queue, rpc_buffer, RPC_NPM_USER, server, SifInitRpc, SifRegisterRpc, SifRpcLoop, and SifSetRpcQueue.
Referenced by naplinkRpcInit().
realfd()
int realfd (iop_io_file_t * f)
Get real filedescriptor.
Parameters
f io_file pointer to get fd from.
Returns
real filedescriptor.
Definition at line 97 of file fakehost.c.
 {
         return (int) f->privdata;
 }
References iop_io_file_t::privdata.
Referenced by fd_close(), fd_lseek(), fd_read(), and fd_write().