ps2sdk: ps2netfs - TCP fs driver
ps2netfs - TCP fs driver
Data Structures
struct dev_table_t
struct fd_table_t
Macros
#define DEVSCAN_MAX (DEVSCAN_IOMAX+DEVSCAN_IOXMAX+1)
#define DEVSCAN_MASK (IOP_DT_FS | IOP_DT_BLOCK)
#define PFS_ZONE_SIZE 8192
Functions
ModuleInfo_t * devscan_getmodule (const char *name)
int devscan_setup (int devtype)
int devscan_gettype (char *name)
int devscan_getdevlist (char *buffer)
static void fdh_setup ()
static int fdh_getfd (int devtype, int fd)
static void fdh_freefd (int fd)
static int convmode_to_iomanx (int stat)
static int convmode_from_iomanx (int stat)
int ps2netfs_close_socket (void)
void ps2netfs_close_fsys (void)
static int ps2netfs_op_info (char *buf, int len)
static int ps2netfs_op_fstype (char *buf, int len)
static int ps2netfs_op_devlist (char *buf, int len)
static int ps2netfs_op_open (char *buf, int len)
static int ps2netfs_op_close (char *buf, int len)
static int ps2netfs_op_read (char *buf, int len)
static int ps2netfs_op_write (char *buf, int len)
static int ps2netfs_op_lseek (char *buf, int len)
static int ps2netfs_op_ioctl (char *buf, int len)
static int ps2netfs_op_remove (char *buf, int len)
static int ps2netfs_op_mkdir (char *buf, int len)
static int ps2netfs_op_rmdir (char *buf, int len)
static int ps2netfs_op_dopen (char *buf, int len)
static int ps2netfs_op_dclose (char *buf, int len)
static int ps2netfs_op_dread (char *buf, int len)
static int ps2netfs_op_getstat (char *buf, int len)
static int ps2netfs_op_chstat (char *buf, int len)
static int ps2netfs_op_rename (char *buf, int len)
static int ps2netfs_op_chdir (char *buf, int len)
static int ps2netfs_op_sync (char *buf, int len)
static int ps2netfs_op_mount (char *buf, int len)
static int ps2netfs_op_umount (char *buf, int len)
static int ps2netfs_op_lseek64 (char *buf, int len)
static int ps2netfs_op_devctl (char *buf, int len)
static int ps2netfs_op_symlink (char *buf, int len)
static int ps2netfs_op_readlink (char *buf, int len)
static int ps2netfs_op_ioctl2 (char *buf, int len)
static void ps2netfs_Listener (int sock)
int ps2netfs_serv (void *argv)
int ps2netfs_Init (void)
int ps2fs_Destroy (void)
int _start (int argc, char *argv[])
Variables
static dev_table_t dev_info_list [DEVSCAN_MAX+1]
Detailed Description
Macro Definition Documentation
DEVSCAN_MASK
#define DEVSCAN_MASK (IOP_DT_FS | IOP_DT_BLOCK)
Device scan mask.
Definition at line 26 of file devscan.h.
DEVSCAN_MAX
#define DEVSCAN_MAX (DEVSCAN_IOMAX+DEVSCAN_IOXMAX+1)
Maximum number of devices handled.
Definition at line 21 of file devscan.h.
PFS_ZONE_SIZE
#define PFS_ZONE_SIZE 8192
Handles a PS2NETFS_FORMAT_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found +X if handled ok, valid FD returned. -X if error.
Definition at line 1299 of file ps2_fio.c.
Function Documentation
_start()
int _start (int argc, char * argv[])
Entry point for IRX.
argc and argv make no difference to runstate.
Parameters
argc Number of arguments.
argv Pointer to array of arguments.
Returns
Module Status on Exit.
return values: MODULE_RESIDENT_END if loaded and registered as library. MODULE_NO_RESIDENT_END if just exiting normally.
Definition at line 47 of file ps2netfs.c.
 {
   printf("%s - v%d.%d - Copyright (c) 2004 adresd\n",
     PS2NETFS_MODNAME,PS2NETFS_VERSION_HIGH,PS2NETFS_VERSION_LOW);
   if (!devscan_getmodule(IOPMGR_IOMAN_IDENT))
   {
     printf("ioman not found\n");
     return MODULE_NO_RESIDENT_END;
   }
   if (!devscan_getmodule(IOPMGR_IOMANX_IDENT))
   {
     printf("iomanx not found\n");
     return MODULE_NO_RESIDENT_END;
   }
   if (ps2netfs_Init() == 0)
   {
     printf("\nServer Started\n");
     return MODULE_RESIDENT_END;
   }
   printf("\nExiting.\n");
   return MODULE_NO_RESIDENT_END;
 }
References devscan_getmodule(), IOPMGR_IOMAN_IDENT, IOPMGR_IOMANX_IDENT, MODULE_NO_RESIDENT_END, MODULE_RESIDENT_END, printf(), ps2netfs_Init(), PS2NETFS_MODNAME, PS2NETFS_VERSION_HIGH, and PS2NETFS_VERSION_LOW.
convmode_from_iomanx()
static int convmode_from_iomanx (int stat) inline static
changes mode from iomanx to ioman format
Definition at line 168 of file ps2_fio.c.
 {
   return stat;
 }
convmode_to_iomanx()
static int convmode_to_iomanx (int stat) inline static
changes mode from ioman to iomanx format
Definition at line 147 of file ps2_fio.c.
 {
   int mode = 0;
   if FIO_SO_ISLNK(stat) mode |= FIO_S_IFLNK; // Symbolic link
   if FIO_SO_ISREG(stat) mode |= FIO_S_IFREG; // regular file
   if FIO_SO_ISDIR(stat) mode |= FIO_S_IFDIR; // directory
   if (((stat) & FIO_SO_IROTH) == FIO_SO_IROTH) // read
     mode |= FIO_S_IRUSR | FIO_S_IRGRP | FIO_S_IROTH;
   if (((stat) & FIO_SO_IWOTH) == FIO_SO_IWOTH) // write
     mode |= FIO_S_IWUSR | FIO_S_IWGRP | FIO_S_IWOTH;
   if (((stat) & FIO_SO_IXOTH) == FIO_SO_IXOTH) // execute
     mode |= FIO_S_IXUSR | FIO_S_IXGRP | FIO_S_IXOTH;
   return mode;
 }
References FIO_S_IFDIR, FIO_S_IFLNK, FIO_S_IFREG, FIO_S_IRGRP, FIO_S_IROTH, FIO_S_IRUSR, FIO_S_IWGRP, FIO_S_IWOTH, FIO_S_IWUSR, FIO_S_IXGRP, FIO_S_IXOTH, FIO_S_IXUSR, FIO_SO_IROTH, FIO_SO_ISDIR, FIO_SO_ISLNK, FIO_SO_ISREG, FIO_SO_IWOTH, and FIO_SO_IXOTH.
Referenced by ps2netfs_op_dread().
devscan_getdevlist()
int devscan_getdevlist (char * buffer)
Get device list.
Parameters
buffer Pointer to dest buffer
Returns
number of devices returned.
Definition at line 169 of file devscan.c.
 {
   int count;
   int i;
   char *bufptr = buffer;
   dbgprintf("devscan: getdevlist\n");
   /* rescan for devices, before returning list */
   count = devscan_setup(DEVSCAN_MASK);
   /* now convert this list into the right format */
   for (i=0;i<count;i++)
   {
     strcpy(bufptr,dev_info_list[i].name);
     dbgprintf("devscan: '%s'\n",bufptr);
     bufptr += strlen(bufptr)+1;
   }
   return count;
 }
References buffer, dbgprintf, dev_info_list, DEVSCAN_MASK, devscan_setup(), strcpy(), and strlen().
Referenced by ps2netfs_op_devlist().
devscan_getmodule()
ModuleInfo_t* devscan_getmodule (const char * name)
Get pointer to module structure for named module.
Parameters
name Stringname of module (eg "atad_driver").
Returns
Pointer to module structure.
return values: 0 if not found. pointer to module structure for loaded module if found.
Definition at line 53 of file devscan.c.
 {
   ModuleInfo_t *modptr;
   int len = strlen(name)+1;
   modptr = GetLoadcoreInternalData()->image_info;
   while (modptr != 0)
   {
     if (!memcmp(modptr->name, name, len))
       return modptr;
     modptr = modptr->next;
   }
   return 0;
 }
References GetLoadcoreInternalData(), lc_internals_t::image_info, memcmp(), ModuleInfo_t::name, ModuleInfo_t::next, and strlen().
Referenced by _start(), and devscan_setup().
devscan_gettype()
int devscan_gettype (char * name)
Get device handler type for path.
Parameters
name Full pathname to check.
Returns
Device handler type.
return values: MODULE_RESIDENT_END if loaded and registered as library. MODULE_NO_RESIDENT_END if just exiting normally.
Definition at line 147 of file devscan.c.
 {
   int count = 0;
   int ret = 0;
   dbgprintf("devscan: gettype '%s'\n",name);
   while (dev_info_list[count].name[0] != 0)
   {
     ret = strncmp(dev_info_list[count].name,name,dev_info_list[count].len );
     dbgprintf("'%s'",dev_info_list[count].name);
     if (!ret)
       return dev_info_list[count].devtype;
     count++;
   }
   return IOPMGR_DEVTYPE_INVALID;
 }
References dbgprintf, dev_info_list, dev_table_t::devtype, IOPMGR_DEVTYPE_INVALID, and strncmp().
Referenced by ps2netfs_op_chdir(), ps2netfs_op_dopen(), ps2netfs_op_format(), ps2netfs_op_fstype(), ps2netfs_op_mkdir(), ps2netfs_op_mount(), ps2netfs_op_open(), ps2netfs_op_readlink(), ps2netfs_op_remove(), ps2netfs_op_rename(), ps2netfs_op_rmdir(), ps2netfs_op_symlink(), ps2netfs_op_sync(), and ps2netfs_op_umount().
devscan_setup()
int devscan_setup (int devtype)
Initialise the devices table
Parameters
devtype Mask for device types to return (0x10 = FS drivers).
Returns
Number of devices found.
This scans ioman and iomanx for devices, then adds them to the internal list, with basename and the handler type.
Also used to re-init the devices table
Definition at line 79 of file devscan.c.
 {
   ModuleInfo_t *info;
   iop_device_t **devinfo_table;
   int i;
   int  count = 0;
   dbgprintf("devscan: setup\n");
   // clear device list
   memset(&dev_info_list,0,sizeof(dev_info_list));
   /* do the ioman devices */
   if ((info = devscan_getmodule(IOPMGR_IOMAN_IDENT)))
   {
     /* Find the start of the device info array, in .bss.  */
     devinfo_table = (iop_device_t **)(info->text_start + info->text_size + info->data_size + 0x0c);
     /* The device info table had 16 entries, but some may be empty.  Just look at all of them.  */
     for (i = 0; i < DEVSCAN_IOMAX; i++)
     {
       if (devinfo_table[i])
         if ((devinfo_table[i]->type & devtype))
         {
           dev_info_list[count].devtype = IOPMGR_DEVTYPE_IOMAN;
           strncpy(dev_info_list[count].name,devinfo_table[i]->name,255);
           dev_info_list[count].name[255] = '\0';
           dev_info_list[count].len = strlen(dev_info_list[count].name);
           dbgprintf("devscan: ioman '%s'\n",dev_info_list[count].name);
           count++;
         }
     }
   }
   /* do the iomanx devices */
   if ((info = devscan_getmodule(IOPMGR_IOMANX_IDENT)))
   {
     /* Find the start of the device info array, in .bss.  */
     devinfo_table = (iop_device_t **)(info->text_start + info->text_size + info->data_size);
     /* The device info table had 32 entries, but some may be empty.  Just look at all of them.  */
     for (i = 0; i < DEVSCAN_IOXMAX; i++)
     {
       if (devinfo_table[i])
         /* only add iomanx ones here, so must have extended flag set  else we get duplication with new iomanx */
         if ((devinfo_table[i]->type & IOP_DT_FSEXT) && (devinfo_table[i]->type & devtype))
         {
           dev_info_list[count].devtype = IOPMGR_DEVTYPE_IOMANX;
           strncpy(dev_info_list[count].name,devinfo_table[i]->name,255);
           dev_info_list[count].name[255] = '\0';
           dev_info_list[count].len = strlen(dev_info_list[count].name);
           dbgprintf("devscan: iomanx '%s'\n",dev_info_list[count].name);
           count++;
         }
     }
   }
   return count;
 }
References dbgprintf, dev_info_list, devscan_getmodule(), DEVSCAN_IOMAX, DEVSCAN_IOXMAX, dev_table_t::devtype, IOP_DT_FSEXT, IOPMGR_DEVTYPE_IOMAN, IOPMGR_DEVTYPE_IOMANX, IOPMGR_IOMAN_IDENT, IOPMGR_IOMANX_IDENT, dev_table_t::len, memset(), dev_table_t::name, strlen(), strncpy(), and iop_device_t::type.
Referenced by devscan_getdevlist(), and ps2netfs_serv().
fdh_freefd()
static void fdh_freefd (int fd) inline static
Free file descriptor from client table.
Parameters
fd client file descriptor.
Definition at line 124 of file ps2_fio.c.
 {
   if (fd < FDH_MAX)
   {
     fd_info_list[fd].used = 0;
     fd_info_list[fd].realfd = 0;
     fd_info_list[fd].devtype = 0;
   }
 }
References fd_table_t::devtype, fd_info_list, FDH_MAX, fd_table_t::realfd, and fd_table_t::used.
Referenced by ps2netfs_op_close(), and ps2netfs_op_dclose().
fdh_getfd()
static int fdh_getfd (int devtype, int fd) inline static
Get file descriptor for client.
Parameters
devtype Device Manager type.
fd PS2 file descriptor.
Returns
FD to send to client.
return values: -1 if no space in list. FD if returning valid entry.
Definition at line 102 of file ps2_fio.c.
 {
   int count = 1;
   while ((count < FDH_MAX))
   {
     if (fd_info_list[count].used == 0)
     {
       fd_info_list[count].used = 1;
       fd_info_list[count].realfd = fd;
       fd_info_list[count].devtype = devtype;
       return count;
     }
     count++;
   }
   return -1;
 }
References fd_table_t::devtype, fd_info_list, FDH_MAX, fd_table_t::realfd, and fd_table_t::used.
Referenced by ps2netfs_op_dopen(), and ps2netfs_op_open().
fdh_setup()
static void fdh_setup () inline static
Initialise the file descriptor table.
This initialises the file descriptor table that we use to translate to numbers passed to client, and to enable quick lookups on handler type.
Definition at line 86 of file ps2_fio.c.
 {
   memset(&fd_info_list,0,sizeof(fd_info_list));
 }
References fd_info_list, and memset().
Referenced by ps2netfs_serv().
ps2fs_Destroy()
int ps2fs_Destroy (void)
Shutdown ps2netfs.
This handles Stopping the thread and disconnecting. All shutdown for ps2netfs.
Definition at line 2097 of file ps2_fio.c.
 {
   WaitSema(ps2netfs_sema);
   //    ExitDeleteThread(ps2netfs_pid);
   SignalSema(ps2netfs_sema);
   DeleteSema(ps2netfs_sema);
   return 0;
 }
References DeleteSema(), ps2netfs_sema, SignalSema(), and WaitSema().
ps2netfs_close_fsys()
void ps2netfs_close_fsys (void)
Shortcut to close the socket forcibly and set to exit (active=0).
This will close down the socket, and cause the server thread to exit.
Returns
disconnect return value.
Definition at line 196 of file ps2_fio.c.
 {
   if (ps2netfs_sock > 0)
     disconnect(ps2netfs_sock);
   ps2netfs_active = 0;
   return;
 }
References disconnect, ps2netfs_active, and ps2netfs_sock.
ps2netfs_close_socket()
int ps2netfs_close_socket (void)
Shortcut to close the socket and cleanup.
Returns
disconnect return value.
Definition at line 178 of file ps2_fio.c.
 {
   int ret;
   ret = disconnect(ps2netfs_sock);
   if (ret < 0)
     printf("ps2netfs: disconnect returned error %d\n", ret);
   ps2netfs_sock = -1;
   return ret;
 }
References disconnect, printf(), and ps2netfs_sock.
Referenced by ps2netfs_lwip_send(), and ps2netfs_serv().
ps2netfs_Init()
int ps2netfs_Init (void)
Init ps2netfs.
Returns
Status (0=success, -1 = failure).
This handles setting up the Thread, and starting it running.
Definition at line 2054 of file ps2_fio.c.
 {
   iop_thread_t mythread;
   int pid;
   int i;
   dbgprintf("initializing ps2netfs\n");
   // Start socket server thread
   mythread.attr = 0x02000000; // attr
   mythread.option = 0; // option
   mythread.thread = (void *)ps2netfs_serv; // entry
   mythread.stacksize = 0x800;
   mythread.priority = 0x43; // just above ps2link
   pid = CreateThread(&mythread);
   if (pid > 0)
   {
     if ((i=StartThread(pid, NULL)) < 0)
     {
       printf("StartThread failed (%d)\n", i);
       return -1;
     }
   }
   else
   {
     printf("ps2netfs: CreateThread failed (%d)\n", pid);
     return -1;
   }
   ps2netfs_pid = pid;
   dbgprintf("ps2netfs: Thread id: %x\n", pid);
   return 0;
 }
References iop_thread_t::attr, CreateThread(), dbgprintf, NULL, iop_thread_t::option, printf(), iop_thread_t::priority, ps2netfs_pid, ps2netfs_serv(), iop_thread_t::stacksize, StartThread(), and iop_thread_t::thread.
Referenced by _start().
ps2netfs_Listener()
static void ps2netfs_Listener (int sock) static
Listen for packets and handle them.
Parameters
sock Socket to receive on.
This function listens on the given socket for command packets. It loops until a socket error, or protocol error is found, then exits to the calling function, which should clean the socket up.
Definition at line 1810 of file ps2_fio.c.
 {
  int done;
  int len;
  unsigned int cmd;
  ps2netfs_pkt_hdr *header;
  int retval;
  done = 0;
  while(!done) {
    len = ps2netfs_accept_pktunknown(sock, &ps2netfs_recv_packet[0]);
    if (len > 0)
      dbgprintf("ps2netfs: received packet (%d)\n", len);
    if (len < 0) {
      dbgprintf("ps2netfs_Listener: recvfrom error (%d)\n", len);
      return;
    }
    if (len >= sizeof(ps2netfs_pkt_hdr))
    {
      header = (ps2netfs_pkt_hdr *)ps2netfs_recv_packet;
      cmd = ntohl(header->cmd);
      switch (cmd)
      {
        case PS2NETFS_OPEN_CMD:
          retval = ps2netfs_op_open(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_CLOSE_CMD:
          retval = ps2netfs_op_close(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_READ_CMD:
          retval = ps2netfs_op_read(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_WRITE_CMD:
          retval = ps2netfs_op_write(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_LSEEK_CMD:
          retval = ps2netfs_op_lseek(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_IOCTL_CMD:
          retval = ps2netfs_op_ioctl(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_REMOVE_CMD:
          retval = ps2netfs_op_remove(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_MKDIR_CMD:
          retval = ps2netfs_op_mkdir(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_RMDIR_CMD:
          retval = ps2netfs_op_rmdir(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_DOPEN_CMD:
          retval = ps2netfs_op_dopen(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_DCLOSE_CMD:
          retval = ps2netfs_op_dclose(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_DREAD_CMD:
          retval = ps2netfs_op_dread(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_GETSTAT_CMD:
          retval = ps2netfs_op_getstat(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_CHSTAT_CMD:
          retval = ps2netfs_op_chstat(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_FORMAT_CMD:
          retval = ps2netfs_op_format(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_RENAME_CMD:
          retval = ps2netfs_op_rename(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_CHDIR_CMD:
          retval = ps2netfs_op_chdir(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_SYNC_CMD:
          retval = ps2netfs_op_sync(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_MOUNT_CMD:
          retval = ps2netfs_op_mount(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_UMOUNT_CMD:
          retval = ps2netfs_op_umount(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_LSEEK64_CMD:
          retval = ps2netfs_op_lseek64(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_DEVCTL_CMD:
          retval = ps2netfs_op_devctl(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_SYMLINK_CMD:
          retval = ps2netfs_op_symlink(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_READLINK_CMD:
          retval = ps2netfs_op_readlink(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_IOCTL2_CMD:
          retval = ps2netfs_op_ioctl2(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_INFO_CMD:
          retval = ps2netfs_op_info(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_FSTYPE_CMD:
          retval = ps2netfs_op_fstype(ps2netfs_recv_packet, len);
          break;
        case PS2NETFS_DEVLIST_CMD:
          retval = ps2netfs_op_devlist(ps2netfs_recv_packet, len);
          break;
        default:
          dbgprintf("ps2netfs: Unknown cmd received\n");
          retval = 0;
          break;
       }
       if (retval == -1)
         return;
     }
     else
     {
       dbgprintf("ps2netfs: packet too small (%d)\n", len);
       return;
     }
     dbgprintf("ps2netfs: waiting for next pkt\n");
   }
 }
References ps2netfs_pkt_hdr::cmd, dbgprintf, ntohl, ps2netfs_accept_pktunknown(), PS2NETFS_CHDIR_CMD, PS2NETFS_CHSTAT_CMD, PS2NETFS_CLOSE_CMD, PS2NETFS_DCLOSE_CMD, PS2NETFS_DEVCTL_CMD, PS2NETFS_DEVLIST_CMD, PS2NETFS_DOPEN_CMD, PS2NETFS_DREAD_CMD, PS2NETFS_FORMAT_CMD, PS2NETFS_FSTYPE_CMD, PS2NETFS_GETSTAT_CMD, PS2NETFS_INFO_CMD, PS2NETFS_IOCTL2_CMD, PS2NETFS_IOCTL_CMD, PS2NETFS_LSEEK64_CMD, PS2NETFS_LSEEK_CMD, PS2NETFS_MKDIR_CMD, PS2NETFS_MOUNT_CMD, ps2netfs_op_chdir(), ps2netfs_op_chstat(), ps2netfs_op_close(), ps2netfs_op_dclose(), ps2netfs_op_devctl(), ps2netfs_op_devlist(), ps2netfs_op_dopen(), ps2netfs_op_dread(), ps2netfs_op_format(), ps2netfs_op_fstype(), ps2netfs_op_getstat(), ps2netfs_op_info(), ps2netfs_op_ioctl(), ps2netfs_op_ioctl2(), ps2netfs_op_lseek(), ps2netfs_op_lseek64(), ps2netfs_op_mkdir(), ps2netfs_op_mount(), ps2netfs_op_open(), ps2netfs_op_read(), ps2netfs_op_readlink(), ps2netfs_op_remove(), ps2netfs_op_rename(), ps2netfs_op_rmdir(), ps2netfs_op_symlink(), ps2netfs_op_sync(), ps2netfs_op_umount(), ps2netfs_op_write(), PS2NETFS_OPEN_CMD, PS2NETFS_READ_CMD, PS2NETFS_READLINK_CMD, ps2netfs_recv_packet, PS2NETFS_REMOVE_CMD, PS2NETFS_RENAME_CMD, PS2NETFS_RMDIR_CMD, PS2NETFS_SYMLINK_CMD, PS2NETFS_SYNC_CMD, PS2NETFS_UMOUNT_CMD, and PS2NETFS_WRITE_CMD.
Referenced by ps2netfs_serv().
ps2netfs_op_chdir()
static int ps2netfs_op_chdir (char * buf, int len) static
Handles a PS2NETFS_CHDIR_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found +X if handled ok, valid FD returned. -X if error.
Definition at line 1422 of file ps2_fio.c.
 {
   ps2netfs_pkt_open_req *cmd;
   ps2netfs_pkt_file_rly *chdirrly;
   int retval = -ENODEV;
   int devtype;
   cmd = (ps2netfs_pkt_open_req *)buf;
   dbgprintf("ps2netfs: chdir\n");
   if (len != sizeof(ps2netfs_pkt_open_req))
   {
     dbgprintf("ps2netfs: got a broken packet (%d)!\n", len);
     return -1;
   }
   // do the stuff here
   devtype = devscan_gettype(cmd->path);
   if (devtype == IOPMGR_DEVTYPE_IOMANX)
     retval = chdir(cmd->path);
   // now build the response
   chdirrly = (ps2netfs_pkt_file_rly *)&ps2netfs_send_packet[0];
   // Build packet
   chdirrly->cmd = htonl(PS2NETFS_CHDIR_RLY);
   chdirrly->len = htons((unsigned short)sizeof(ps2netfs_pkt_file_rly));
   chdirrly->retval = htonl(retval);
   if (ps2netfs_lwip_send(ps2netfs_sock, chdirrly, sizeof(ps2netfs_pkt_file_rly), 0) < 0)
   {
     dbgprintf("ps2netfs: error sending reply!\n");
     return -1;
   }
   return 0;
 }
References chdir(), ps2netfs_pkt_file_rly::cmd, dbgprintf, devscan_gettype(), ENODEV, htonl(), htons(), IOPMGR_DEVTYPE_IOMANX, ps2netfs_pkt_file_rly::len, ps2netfs_pkt_open_req::path, PS2NETFS_CHDIR_RLY, ps2netfs_lwip_send(), ps2netfs_send_packet, ps2netfs_sock, and ps2netfs_pkt_file_rly::retval.
Referenced by ps2netfs_Listener().
ps2netfs_op_chstat()
static int ps2netfs_op_chstat (char * buf, int len) static
Handles a PS2NETFS_CHSTAT_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found +X if handled ok, valid FD returned. -X if error.
Definition at line 1272 of file ps2_fio.c.
 {
   return -1;
 }
Referenced by ps2netfs_Listener().
ps2netfs_op_close()
static int ps2netfs_op_close (char * buf, int len) static
Handles a PS2NETFS_CLOSE_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found >=0 if handled ok. -X if error.
Definition at line 548 of file ps2_fio.c.
 {
   ps2netfs_pkt_close_req *cmd;
   ps2netfs_pkt_file_rly *closerly;
   int retval = -1;
   fd_table_t *fdptr;
   cmd = (ps2netfs_pkt_close_req *)buf;
   dbgprintf("ps2netfs: close\n");
   if (len != sizeof(ps2netfs_pkt_close_req))
   {
     dbgprintf("ps2netfs: got a broken packet (%d)!\n", len);
     return -1;
   }
   // do the stuff here
   fdptr = fdh_get(ntohl(cmd->fd));
   if (fdptr != 0)
   {
     if (fdptr->devtype == IOPMGR_DEVTYPE_IOMAN)
       retval = io_close(fdptr->realfd);
     else if (fdptr->devtype == IOPMGR_DEVTYPE_IOMANX)
       retval = close(fdptr->realfd);
     fdh_freefd(ntohl(cmd->fd));
   }
   // now build the response
   closerly = (ps2netfs_pkt_file_rly *)&ps2netfs_send_packet[0];
   // Build packet
   closerly->cmd = htonl(PS2NETFS_CLOSE_RLY);
   closerly->len = htons((unsigned short)sizeof(ps2netfs_pkt_file_rly));
   closerly->retval = htonl(retval);
   if (ps2netfs_lwip_send(ps2netfs_sock, closerly, sizeof(ps2netfs_pkt_file_rly), 0) < 0)
   {
     dbgprintf("ps2netfs: error sending reply!\n");
     return -1;
   }
   return 0;
 }
References close(), ps2netfs_pkt_file_rly::cmd, dbgprintf, fd_table_t::devtype, ps2netfs_pkt_close_req::fd, fdh_freefd(), fdh_get, htonl(), htons(), io_close(), IOPMGR_DEVTYPE_IOMAN, IOPMGR_DEVTYPE_IOMANX, ps2netfs_pkt_file_rly::len, ntohl, PS2NETFS_CLOSE_RLY, ps2netfs_lwip_send(), ps2netfs_send_packet, ps2netfs_sock, fd_table_t::realfd, and ps2netfs_pkt_file_rly::retval.
Referenced by ps2netfs_Listener().
ps2netfs_op_dclose()
static int ps2netfs_op_dclose (char * buf, int len) static
Handles a PS2NETFS_DCLOSE_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found >=0 if handled ok. -X if error.
Definition at line 1104 of file ps2_fio.c.
 {
   ps2netfs_pkt_close_req *cmd;
   ps2netfs_pkt_file_rly *closerly;
   fd_table_t *fdptr;
   int retval = -ENODEV;
   cmd = (ps2netfs_pkt_close_req *)buf;
   dbgprintf("ps2netfs: dclose\n");
   if (len != sizeof(ps2netfs_pkt_close_req))
   {
     dbgprintf("ps2netfs: got a broken packet (%d)!\n", len);
     return -1;
   }
   // do the stuff here
   fdptr = fdh_get(ntohl(cmd->fd));
   if (fdptr != 0)
   {
     if (fdptr->devtype == IOPMGR_DEVTYPE_IOMAN)
       retval = io_dclose(fdptr->realfd);
     else if (fdptr->devtype == IOPMGR_DEVTYPE_IOMANX)
       retval = dclose(fdptr->realfd);
     if (retval == 0) fdh_freefd(ntohl(cmd->fd));
   }
   // now build the response
   closerly = (ps2netfs_pkt_file_rly *)&ps2netfs_send_packet[0];
   // Build packet
   closerly->cmd = htonl(PS2NETFS_DCLOSE_RLY);
   closerly->len = htons((unsigned short)sizeof(ps2netfs_pkt_file_rly));
   closerly->retval = htonl(retval);
   if (ps2netfs_lwip_send(ps2netfs_sock, closerly, sizeof(ps2netfs_pkt_file_rly), 0) < 0)
   {
     dbgprintf("ps2netfs: error sending reply!\n");
     return -1;
   }
   return 0;
 }
References ps2netfs_pkt_file_rly::cmd, dbgprintf, dclose(), fd_table_t::devtype, ENODEV, ps2netfs_pkt_close_req::fd, fdh_freefd(), fdh_get, htonl(), htons(), io_dclose(), IOPMGR_DEVTYPE_IOMAN, IOPMGR_DEVTYPE_IOMANX, ps2netfs_pkt_file_rly::len, ntohl, PS2NETFS_DCLOSE_RLY, ps2netfs_lwip_send(), ps2netfs_send_packet, ps2netfs_sock, fd_table_t::realfd, and ps2netfs_pkt_file_rly::retval.
Referenced by ps2netfs_Listener().
ps2netfs_op_devctl()
static int ps2netfs_op_devctl (char * buf, int len) static
Handles a PS2NETFS_DEVCTL_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found +X if handled ok, valid FD returned. -X if error.
Definition at line 1660 of file ps2_fio.c.
 {
   return -1;
 }
Referenced by ps2netfs_Listener().
ps2netfs_op_devlist()
static int ps2netfs_op_devlist (char * buf, int len) static
Handles a PS2NETFS_DEVLIST_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -1 if error. 0 if handled ok.
Definition at line 420 of file ps2_fio.c.
 {
   ps2netfs_pkt_open_req *cmd;
   ps2netfs_pkt_devlist_rly *devlistrly;
   int count;
   cmd = (ps2netfs_pkt_open_req *)buf;
   dbgprintf("ps2netfs: devlist\n");
   if (len != sizeof(ps2netfs_pkt_open_req))
   {
     dbgprintf("ps2netfs: got a broken packet (%d)!\n", len);
     return -1;
   }
   devlistrly = (ps2netfs_pkt_devlist_rly *)&ps2netfs_send_packet[0];
   // do the stuff here
   count = devscan_getdevlist(devlistrly->list);
   // first char of the path passed in is the delimiter
   { // so fudge in the delimiters
     int cnt; char *ptr = &devlistrly->list[0]; int len;
     for(cnt=0;cnt<(count-1);cnt++)
     {
       len = strlen(ptr);
       // ok, got a string, so replace the final 0, with delimiter
       // move onto next string
       *(ptr+len) = cmd->path[0];
       ptr += len + 1;
     }
   }
   // now build the response
   // Build packet
   devlistrly->cmd = htonl(PS2NETFS_DEVLIST_RLY);
   devlistrly->len = htons((unsigned short)sizeof(ps2netfs_pkt_devlist_rly));
   devlistrly->retval = htonl(count);
   devlistrly->count = htonl(count);
   if (ps2netfs_lwip_send(ps2netfs_sock, devlistrly, sizeof(ps2netfs_pkt_devlist_rly), 0) < 0)
   {
     dbgprintf("ps2netfs: error sending reply!\n");
     return -1;
   }
   return 0;
 }
References ps2netfs_pkt_devlist_rly::cmd, ps2netfs_pkt_devlist_rly::count, dbgprintf, devscan_getdevlist(), htonl(), htons(), ps2netfs_pkt_devlist_rly::len, ps2netfs_pkt_devlist_rly::list, ps2netfs_pkt_open_req::path, PS2NETFS_DEVLIST_RLY, ps2netfs_lwip_send(), ps2netfs_send_packet, ps2netfs_sock, ps2netfs_pkt_devlist_rly::retval, and strlen().
Referenced by ps2netfs_Listener().
ps2netfs_op_dopen()
static int ps2netfs_op_dopen (char * buf, int len) static
Handles a PS2NETFS_DOPEN_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found +X if handled ok, valid FD returned. -X if error.
Definition at line 1043 of file ps2_fio.c.
 {
   ps2netfs_pkt_open_req *cmd;
   ps2netfs_pkt_file_rly *dopenrly;
   int retval = -ENODEV;
   int devtype;
   cmd = (ps2netfs_pkt_open_req *)buf;
   dbgprintf("ps2netfs: dopen\n");
   if (len != sizeof(ps2netfs_pkt_open_req))
   {
     dbgprintf("ps2netfs: got a broken packet (%d)!\n", len);
     return -1;
   }
   // do the stuff here
   devtype = devscan_gettype(cmd->path);
   if (devtype != IOPMGR_DEVTYPE_INVALID)
   {
     if (devtype == IOPMGR_DEVTYPE_IOMAN)
       retval = io_dopen(cmd->path,0);
     else if (devtype == IOPMGR_DEVTYPE_IOMANX)
       retval = dopen(cmd->path);
     if (retval > 0)
       retval = fdh_getfd(devtype,retval);
   }
   // now build the response
   dopenrly = (ps2netfs_pkt_file_rly *)&ps2netfs_send_packet[0];
   // Build packet
   dopenrly->cmd = htonl(PS2NETFS_DOPEN_RLY);
   dopenrly->len = htons((unsigned short)sizeof(ps2netfs_pkt_file_rly));
   dopenrly->retval = htonl(retval);
   if (ps2netfs_lwip_send(ps2netfs_sock, dopenrly, sizeof(ps2netfs_pkt_file_rly), 0) < 0)
   {
     dbgprintf("ps2netfs: error sending reply!\n");
     return -1;
   }
   return 0;
 }
References ps2netfs_pkt_file_rly::cmd, dbgprintf, devscan_gettype(), dopen(), ENODEV, fdh_getfd(), htonl(), htons(), io_dopen(), IOPMGR_DEVTYPE_INVALID, IOPMGR_DEVTYPE_IOMAN, IOPMGR_DEVTYPE_IOMANX, ps2netfs_pkt_file_rly::len, ps2netfs_pkt_open_req::path, PS2NETFS_DOPEN_RLY, ps2netfs_lwip_send(), ps2netfs_send_packet, ps2netfs_sock, and ps2netfs_pkt_file_rly::retval.
Referenced by ps2netfs_Listener().
ps2netfs_op_dread()
static int ps2netfs_op_dread (char * buf, int len) static
Handles a PS2NETFS_DREAD_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found >=0 if handled ok. -X if error.
Definition at line 1164 of file ps2_fio.c.
 {
   ps2netfs_pkt_dread_req *cmd;
   ps2netfs_pkt_dread_rly *dreadrly;
   fd_table_t *fdptr;
   int retval = -ENODEV;
   cmd = (ps2netfs_pkt_dread_req *)buf;
   dbgprintf("ps2netfs: dread\n");
   if (len != sizeof(ps2netfs_pkt_dread_req))
   {
     dbgprintf("ps2netfs: got a broken packet (%d)!\n", len);
     return -1;
   }
   // get response structure ready for filling
   dreadrly = (ps2netfs_pkt_dread_rly *)&ps2netfs_send_packet[0];
   memset(dreadrly,0,sizeof(ps2netfs_pkt_dread_rly));
   // do the stuff here
   fdptr = fdh_get(ntohl(cmd->fd));
   if (fdptr != 0)
   {
     if (fdptr->devtype == IOPMGR_DEVTYPE_IOMAN)
     {
       io_dirent_t dirent;
       retval = io_dread(fdptr->realfd,&dirent);
       if (retval > 0)
       {
         dreadrly->mode   = htonl(convmode_to_iomanx(dirent.stat.mode));
         dreadrly->attr   = htonl(dirent.stat.attr);
         dreadrly->size   = htonl(dirent.stat.size);
         dreadrly->hisize = htonl(0);
         memcpy(dreadrly->ctime,dirent.stat.ctime,8*3);
         strncpy(dreadrly->name,dirent.name,255);
         dreadrly->name[255] = '\0';
       }
     }
     else if (fdptr->devtype == IOPMGR_DEVTYPE_IOMANX)
     {
       iox_dirent_t dirent;
       retval = dread(fdptr->realfd,&dirent);
       if (retval > 0)
       {
         dreadrly->mode   = htonl(dirent.stat.mode);
         dreadrly->attr   = htonl(dirent.stat.attr);
         dreadrly->size   = htonl(dirent.stat.size);
         dreadrly->hisize = htonl(0);
         memcpy(dreadrly->ctime,dirent.stat.ctime,8*3);
         strncpy(dreadrly->name,dirent.name,255);
         dreadrly->name[255] = '\0';
       }
     }
   }
   dbgprintf("ps2netfs: dread '%s' %d\n",dreadrly->name,dreadrly->size);
   // Build packet
   dreadrly->cmd = htonl(PS2NETFS_DREAD_RLY);
   dreadrly->len = htons((unsigned short)sizeof(ps2netfs_pkt_dread_rly));
   dreadrly->retval = htonl(retval);
   if (ps2netfs_lwip_send(ps2netfs_sock, dreadrly, sizeof(ps2netfs_pkt_dread_rly), 0) < 0)
   {
     dbgprintf("ps2netfs: error sending reply!\n");
     return -1;
   }
   return 0;
 }
References io_stat_t::attr, iox_stat_t::attr, ps2netfs_pkt_dread_rly::attr, ps2netfs_pkt_dread_rly::cmd, convmode_to_iomanx(), io_stat_t::ctime, iox_stat_t::ctime, ps2netfs_pkt_dread_rly::ctime, dbgprintf, fd_table_t::devtype, dread(), ENODEV, ps2netfs_pkt_dread_req::fd, fdh_get, ps2netfs_pkt_dread_rly::hisize, htonl(), htons(), io_dread(), IOPMGR_DEVTYPE_IOMAN, IOPMGR_DEVTYPE_IOMANX, ps2netfs_pkt_dread_rly::len, memcpy(), memset(), io_stat_t::mode, iox_stat_t::mode, ps2netfs_pkt_dread_rly::mode, io_dirent_t::name, iox_dirent_t::name, ps2netfs_pkt_dread_rly::name, ntohl, PS2NETFS_DREAD_RLY, ps2netfs_lwip_send(), ps2netfs_send_packet, ps2netfs_sock, fd_table_t::realfd, ps2netfs_pkt_dread_rly::retval, io_stat_t::size, iox_stat_t::size, ps2netfs_pkt_dread_rly::size, io_dirent_t::stat, iox_dirent_t::stat, and strncpy().
Referenced by ps2netfs_Listener().
ps2netfs_op_fstype()
static int ps2netfs_op_fstype (char * buf, int len) static
Handles a PS2NETFS_FSTYPE_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -1 if error. 0 if handled ok.
Definition at line 371 of file ps2_fio.c.
 {
   ps2netfs_pkt_open_req *cmd;
   ps2netfs_pkt_file_rly *openrly;
   int devtype = -1;
   cmd = (ps2netfs_pkt_open_req *)buf;
   dbgprintf("ps2netfs: fstype\n");
   if (len != sizeof(ps2netfs_pkt_open_req))
   {
     dbgprintf("ps2netfs: got a broken packet (%d)!\n", len);
     return -1;
   }
   // do the stuff here
   devtype = devscan_gettype(cmd->path);
   // now build the response
   openrly = (ps2netfs_pkt_file_rly *)&ps2netfs_send_packet[0];
   // Build packet
   openrly->cmd = htonl(PS2NETFS_OPEN_RLY);
   openrly->len = htons((unsigned short)sizeof(ps2netfs_pkt_file_rly));
   openrly->retval = htonl(devtype);
   if (ps2netfs_lwip_send(ps2netfs_sock, openrly, sizeof(ps2netfs_pkt_file_rly), 0) < 0)
   {
     dbgprintf("ps2netfs: error sending reply!\n");
     return -1;
   }
   return 0;
 }
References ps2netfs_pkt_file_rly::cmd, dbgprintf, devscan_gettype(), htonl(), htons(), ps2netfs_pkt_file_rly::len, ps2netfs_pkt_open_req::path, ps2netfs_lwip_send(), PS2NETFS_OPEN_RLY, ps2netfs_send_packet, ps2netfs_sock, and ps2netfs_pkt_file_rly::retval.
Referenced by ps2netfs_Listener().
ps2netfs_op_getstat()
static int ps2netfs_op_getstat (char * buf, int len) static
Handles a PS2NETFS_GETSTAT_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found +X if handled ok, valid FD returned. -X if error.
Definition at line 1250 of file ps2_fio.c.
 {
   return -1;
 }
Referenced by ps2netfs_Listener().
ps2netfs_op_info()
static int ps2netfs_op_info (char * buf, int len) static
Handles a PS2NETFS_INFO_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -1 if error. 0 if handled ok.
Definition at line 320 of file ps2_fio.c.
 {
 //  ps2netfs_pkt_open_req *cmd;
   ps2netfs_pkt_info_rly *inforly;
   int count;
 //  cmd = (ps2netfs_pkt_open_req *)buf;
   dbgprintf("ps2netfs: info\n");
   if (len != sizeof(ps2netfs_pkt_open_req))
   {
     dbgprintf("ps2netfs: got a broken packet (%d)!\n", len);
     return -1;
   }
   inforly = (ps2netfs_pkt_info_rly *)&ps2netfs_send_packet[0];
   // do the stuff here
   count = 0;
   // now build the response
   // Build packet
   inforly->cmd = htonl(PS2NETFS_INFO_RLY);
   inforly->len = htons((unsigned short)sizeof(ps2netfs_pkt_info_rly));
   inforly->retval = htonl(count);
   inforly->count = htonl(count);
   if (ps2netfs_lwip_send(ps2netfs_sock, inforly, sizeof(ps2netfs_pkt_info_rly), 0) < 0)
   {
     dbgprintf("ps2netfs: error sending reply!\n");
     return -1;
   }
   return 0;
 }
References ps2netfs_pkt_info_rly::cmd, ps2netfs_pkt_info_rly::count, dbgprintf, htonl(), htons(), ps2netfs_pkt_info_rly::len, PS2NETFS_INFO_RLY, ps2netfs_lwip_send(), ps2netfs_send_packet, ps2netfs_sock, and ps2netfs_pkt_info_rly::retval.
Referenced by ps2netfs_Listener().
ps2netfs_op_ioctl()
static int ps2netfs_op_ioctl (char * buf, int len) static
Handles a PS2NETFS_IOCTL_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found >=0 if handled ok. -X if error.
Definition at line 808 of file ps2_fio.c.
 {
   ps2netfs_pkt_ioctl_req *cmd;
   ps2netfs_pkt_ioctl_rly *ioctlrly;
   fd_table_t *fdptr;
   int retval = -ENODEV;
   cmd = (ps2netfs_pkt_ioctl_req *)buf;
   dbgprintf("ps2netfs: ioctl\n");
   if (len != sizeof(ps2netfs_pkt_ioctl_req))
   {
     dbgprintf("ps2netfs: got a broken packet (%d)!\n", len);
     return -1;
   }
   // now build the response
   ioctlrly = (ps2netfs_pkt_ioctl_rly *)&ps2netfs_send_packet[0];
   // do the stuff here
   fdptr = fdh_get(ntohl(cmd->fd));
   if (fdptr != 0)
   {
     if (fdptr->devtype == IOPMGR_DEVTYPE_IOMAN)
       retval = io_ioctl(fdptr->realfd,ntohl(cmd->command),(void *)ioctlrly->buf);
     else if (fdptr->devtype == IOPMGR_DEVTYPE_IOMANX)
       retval = ioctl(fdptr->realfd,ntohl(cmd->command),(void *)ioctlrly->buf);
   }
   // Build packet
   ioctlrly->cmd = htonl(PS2NETFS_IOCTL_RLY);
   ioctlrly->len = htons((unsigned short)sizeof(ps2netfs_pkt_ioctl_rly));
   ioctlrly->retval = htonl(retval);
   if (ps2netfs_lwip_send(ps2netfs_sock, ioctlrly, sizeof(ps2netfs_pkt_ioctl_rly), 0) < 0)
   {
     dbgprintf("ps2netfs: error sending reply!\n");
     return -1;
   }
   return 0;
 }
References ps2netfs_pkt_ioctl_rly::buf, ps2netfs_pkt_ioctl_rly::cmd, ps2netfs_pkt_ioctl_req::command, dbgprintf, fd_table_t::devtype, ENODEV, ps2netfs_pkt_ioctl_req::fd, fdh_get, htonl(), htons(), io_ioctl(), ioctl(), IOPMGR_DEVTYPE_IOMAN, IOPMGR_DEVTYPE_IOMANX, ps2netfs_pkt_ioctl_rly::len, ntohl, PS2NETFS_IOCTL_RLY, ps2netfs_lwip_send(), ps2netfs_send_packet, ps2netfs_sock, fd_table_t::realfd, and ps2netfs_pkt_ioctl_rly::retval.
Referenced by ps2netfs_Listener().
ps2netfs_op_ioctl2()
static int ps2netfs_op_ioctl2 (char * buf, int len) static
Handles a PS2NETFS_IOCTL2_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found +X if handled ok, valid FD returned. -X if error.
Definition at line 1795 of file ps2_fio.c.
 {
   return -1;
 }
Referenced by ps2netfs_Listener().
ps2netfs_op_lseek()
static int ps2netfs_op_lseek (char * buf, int len) static
Handles a PS2NETFS_LSEEK_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found >=0 if handled ok , position. -X if error.
Definition at line 750 of file ps2_fio.c.
 {
   ps2netfs_pkt_lseek_req *cmd;
   ps2netfs_pkt_file_rly *lseekrly;
   fd_table_t *fdptr;
   int retval = -ENODEV;
   cmd = (ps2netfs_pkt_lseek_req *)buf;
   dbgprintf("ps2netfs: lseek\n");
   if (len != sizeof(ps2netfs_pkt_lseek_req))
   {
     dbgprintf("ps2netfs: got a broken packet (%d)!\n", len);
     return -1;
   }
   // do the stuff here
   fdptr = fdh_get(ntohl(cmd->fd));
   if (fdptr != 0)
   {
     if (fdptr->devtype == IOPMGR_DEVTYPE_IOMAN)
       retval = io_lseek(fdptr->realfd,ntohl(cmd->offset),ntohl(cmd->whence));
     else if (fdptr->devtype == IOPMGR_DEVTYPE_IOMANX)
       retval = lseek(fdptr->realfd,ntohl(cmd->offset),ntohl(cmd->whence));
   }
   // now build the response
   lseekrly = (ps2netfs_pkt_file_rly *)&ps2netfs_send_packet[0];
   // Build packet
   lseekrly->cmd = htonl(PS2NETFS_LSEEK_RLY);
   lseekrly->len = htons((unsigned short)sizeof(ps2netfs_pkt_file_rly));
   lseekrly->retval = htonl(retval);
   if (ps2netfs_lwip_send(ps2netfs_sock, lseekrly, sizeof(ps2netfs_pkt_file_rly), 0) < 0)
   {
     dbgprintf("ps2netfs: error sending reply!\n");
     return -1;
   }
   return 0;
 }
References ps2netfs_pkt_file_rly::cmd, dbgprintf, fd_table_t::devtype, ENODEV, ps2netfs_pkt_lseek_req::fd, fdh_get, htonl(), htons(), io_lseek(), IOPMGR_DEVTYPE_IOMAN, IOPMGR_DEVTYPE_IOMANX, ps2netfs_pkt_file_rly::len, lseek(), ntohl, ps2netfs_pkt_lseek_req::offset, PS2NETFS_LSEEK_RLY, ps2netfs_lwip_send(), ps2netfs_send_packet, ps2netfs_sock, fd_table_t::realfd, ps2netfs_pkt_file_rly::retval, and ps2netfs_pkt_lseek_req::whence.
Referenced by ps2netfs_Listener().
ps2netfs_op_lseek64()
static int ps2netfs_op_lseek64 (char * buf, int len) static
Handles a PS2NETFS_LSEEK64_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found +X if handled ok, valid FD returned. -X if error.
Definition at line 1638 of file ps2_fio.c.
 {
   return -1;
 }
Referenced by ps2netfs_Listener().
ps2netfs_op_mkdir()
static int ps2netfs_op_mkdir (char * buf, int len) static
Handles a PS2NETFS_MKDIR_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found >=0 if handled ok. -X if error.
Definition at line 925 of file ps2_fio.c.
 {
   ps2netfs_pkt_open_req *cmd;
   ps2netfs_pkt_file_rly *mkdirrly;
   int retval = -19;
   int devtype;
   cmd = (ps2netfs_pkt_open_req *)buf;
   dbgprintf("ps2netfs: mkdir\n");
   if (len != sizeof(ps2netfs_pkt_open_req))
   {
     dbgprintf("ps2netfs: got a broken packet (%d)!\n", len);
     return -1;
   }
   // do the stuff here
   devtype = devscan_gettype(cmd->path);
   if (devtype != IOPMGR_DEVTYPE_INVALID)
   {
     if (devtype == IOPMGR_DEVTYPE_IOMAN)
       retval = io_mkdir(cmd->path);
     else if (devtype == IOPMGR_DEVTYPE_IOMANX)
       retval = mkdir(cmd->path,0644);
   }
   // now build the response
   mkdirrly = (ps2netfs_pkt_file_rly *)&ps2netfs_send_packet[0];
   // Build packet
   mkdirrly->cmd = htonl(PS2NETFS_MKDIR_RLY);
   mkdirrly->len = htons((unsigned short)sizeof(ps2netfs_pkt_file_rly));
   mkdirrly->retval = htonl(retval);
   if (ps2netfs_lwip_send(ps2netfs_sock, mkdirrly, sizeof(ps2netfs_pkt_file_rly), 0) < 0)
   {
     dbgprintf("ps2netfs: error sending reply!\n");
     return -1;
   }
   return 0;
 }
References ps2netfs_pkt_file_rly::cmd, dbgprintf, devscan_gettype(), htonl(), htons(), io_mkdir(), IOPMGR_DEVTYPE_INVALID, IOPMGR_DEVTYPE_IOMAN, IOPMGR_DEVTYPE_IOMANX, ps2netfs_pkt_file_rly::len, mkdir(), ps2netfs_pkt_open_req::path, ps2netfs_lwip_send(), PS2NETFS_MKDIR_RLY, ps2netfs_send_packet, ps2netfs_sock, and ps2netfs_pkt_file_rly::retval.
Referenced by ps2netfs_Listener().
ps2netfs_op_mount()
static int ps2netfs_op_mount (char * buf, int len) static
Handles a PS2NETFS_MOUNT_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found +X if handled ok, valid FD returned. -X if error.
Definition at line 1530 of file ps2_fio.c.
 {
   ps2netfs_pkt_mount_req *cmd;
   ps2netfs_pkt_file_rly *mountrly;
   int retval = -ENODEV;
   int devtype;
   cmd = (ps2netfs_pkt_mount_req *)buf;
   dbgprintf("ps2netfs: mount\n");
   if (len != sizeof(ps2netfs_pkt_mount_req))
   {
     dbgprintf("ps2netfs: got a broken packet (%d)!\n", len);
     return -1;
   }
   // do the stuff here
   devtype = devscan_gettype(cmd->fsname);
   if (devtype == IOPMGR_DEVTYPE_IOMANX)
     retval = mount(cmd->fsname,cmd->devname,ntohl(cmd->flag),cmd->arg,ntohl(cmd->arglen));
   // now build the response
   mountrly = (ps2netfs_pkt_file_rly *)&ps2netfs_send_packet[0];
   // Build packet
   mountrly->cmd = htonl(PS2NETFS_MOUNT_RLY);
   mountrly->len = htons((unsigned short)sizeof(ps2netfs_pkt_file_rly));
   mountrly->retval = htonl(retval);
   if (ps2netfs_lwip_send(ps2netfs_sock, mountrly, sizeof(ps2netfs_pkt_file_rly), 0) < 0)
   {
     dbgprintf("ps2netfs: error sending reply!\n");
     return -1 ;
   }
   return 0;
 }
References ps2netfs_pkt_mount_req::arg, ps2netfs_pkt_mount_req::arglen, ps2netfs_pkt_file_rly::cmd, dbgprintf, ps2netfs_pkt_mount_req::devname, devscan_gettype(), ENODEV, ps2netfs_pkt_mount_req::flag, ps2netfs_pkt_mount_req::fsname, htonl(), htons(), IOPMGR_DEVTYPE_IOMANX, ps2netfs_pkt_file_rly::len, mount(), ntohl, ps2netfs_lwip_send(), PS2NETFS_MOUNT_RLY, ps2netfs_send_packet, ps2netfs_sock, and ps2netfs_pkt_file_rly::retval.
Referenced by ps2netfs_Listener().
ps2netfs_op_open()
static int ps2netfs_op_open (char * buf, int len) static
Handles a PS2NETFS_OPEN_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found +X if handled ok, valid FD returned. -X if error.
Definition at line 487 of file ps2_fio.c.
 {
   ps2netfs_pkt_open_req *cmd;
   ps2netfs_pkt_file_rly *openrly;
   int retval = -ENODEV;
   int devtype = 0;
   cmd = (ps2netfs_pkt_open_req *)buf;
   dbgprintf("ps2netfs: open\n");
   if (len != sizeof(ps2netfs_pkt_open_req))
   {
     dbgprintf("ps2netfs: got a broken packet (%d)!\n", len);
     return -1;
   }
   // do the stuff here
   devtype = devscan_gettype(cmd->path);
   if (devtype != IOPMGR_DEVTYPE_INVALID)
   {
     if (devtype == IOPMGR_DEVTYPE_IOMAN)
       retval = io_open(cmd->path,ntohl(cmd->flags));
     else if (devtype == IOPMGR_DEVTYPE_IOMANX)
       retval = open(cmd->path,ntohl(cmd->flags),0644);
     if (retval > 0)
       retval = fdh_getfd(devtype,retval);
   }
   // now build the response
   openrly = (ps2netfs_pkt_file_rly *)&ps2netfs_send_packet[0];
   // Build packet
   openrly->cmd = htonl(PS2NETFS_OPEN_RLY);
   openrly->len = htons((unsigned short)sizeof(ps2netfs_pkt_file_rly));
   openrly->retval = htonl(retval);
   if (ps2netfs_lwip_send(ps2netfs_sock, openrly, sizeof(ps2netfs_pkt_file_rly), 0) < 0)
   {
     dbgprintf("ps2netfs: error sending reply!\n");
     return -1;
   }
   return 0;
 }
References ps2netfs_pkt_file_rly::cmd, dbgprintf, devscan_gettype(), ENODEV, fdh_getfd(), ps2netfs_pkt_open_req::flags, htonl(), htons(), io_open(), IOPMGR_DEVTYPE_INVALID, IOPMGR_DEVTYPE_IOMAN, IOPMGR_DEVTYPE_IOMANX, ps2netfs_pkt_file_rly::len, ntohl, open(), ps2netfs_pkt_open_req::path, ps2netfs_lwip_send(), PS2NETFS_OPEN_RLY, ps2netfs_send_packet, ps2netfs_sock, and ps2netfs_pkt_file_rly::retval.
Referenced by ps2netfs_Listener().
ps2netfs_op_read()
static int ps2netfs_op_read (char * buf, int len) static
Handles a PS2NETFS_READ_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found >=0 if handled ok , bytes read. -X if error.
Definition at line 608 of file ps2_fio.c.
 {
   ps2netfs_pkt_read_req *cmd;
   ps2netfs_pkt_read_rly *readrly;
   int retval = -1;
   int nbytes;
   fd_table_t *fdptr;
   cmd = (ps2netfs_pkt_read_req *)buf;
   dbgprintf("ps2netfs: read\n");
   if (len != sizeof(ps2netfs_pkt_read_req))
   {
     dbgprintf("ps2netfs: got a broken packet (%d)!\n", len);
     return -1;
   }
   // limit read request to 64k
   nbytes = ntohl(cmd->nbytes);
   if (nbytes > FIOTRAN_MAXSIZE) nbytes = FIOTRAN_MAXSIZE;
   // do the stuff here
   fdptr = fdh_get(ntohl(cmd->fd));
   if (fdptr != 0)
   {
     if (fdptr->devtype == IOPMGR_DEVTYPE_IOMAN)
       retval = io_read(fdptr->realfd,ps2netfs_fiobuffer,nbytes);
     else if (fdptr->devtype == IOPMGR_DEVTYPE_IOMANX)
       retval = read(fdptr->realfd,ps2netfs_fiobuffer,nbytes);
   }
   // now build the response
   readrly = (ps2netfs_pkt_read_rly *)&ps2netfs_send_packet[0];
   // Build packet
   readrly->cmd = htonl(PS2NETFS_READ_RLY);
   readrly->len = htons((unsigned short)sizeof(ps2netfs_pkt_read_rly));
   readrly->retval = htonl(retval);
   readrly->nbytes = readrly->retval;
   // send the response
   if (ps2netfs_lwip_send(ps2netfs_sock, readrly, sizeof(ps2netfs_pkt_read_rly), 0) < 0)
   {
     dbgprintf("ps2netfs: error sending reply!\n");
     return -1;
   }
   // now send the data
   if (retval > 0)
     if (ps2netfs_lwip_send(ps2netfs_sock, ps2netfs_fiobuffer, ntohl(readrly->retval), 0) < 0)
     {
       dbgprintf("ps2netfs: error sending data!\n");
       return -1;
     }
   return 0;
 }
References ps2netfs_pkt_read_rly::cmd, dbgprintf, fd_table_t::devtype, ps2netfs_pkt_read_req::fd, fdh_get, FIOTRAN_MAXSIZE, htonl(), htons(), io_read(), IOPMGR_DEVTYPE_IOMAN, IOPMGR_DEVTYPE_IOMANX, ps2netfs_pkt_read_rly::len, ps2netfs_pkt_read_req::nbytes, ps2netfs_pkt_read_rly::nbytes, ntohl, ps2netfs_fiobuffer, ps2netfs_lwip_send(), PS2NETFS_READ_RLY, ps2netfs_send_packet, ps2netfs_sock, read(), fd_table_t::realfd, and ps2netfs_pkt_read_rly::retval.
Referenced by ps2netfs_Listener().
ps2netfs_op_readlink()
static int ps2netfs_op_readlink (char * buf, int len) static
Handles a PS2NETFS_READLINK_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found +X if handled ok, valid FD returned. -X if error.
Definition at line 1740 of file ps2_fio.c.
 {
   ps2netfs_pkt_open_req *cmd;
   ps2netfs_pkt_readlink_rly *readlinkrly;
   int retval = -ENODEV;
   int devtype;
   cmd = (ps2netfs_pkt_open_req *)buf;
   dbgprintf("ps2netfs: readlink\n");
   if (len != sizeof(ps2netfs_pkt_open_req))
   {
     dbgprintf("ps2netfs: got a broken packet (%d)!\n", len);
     return -1;
   }
   // now build the response
   readlinkrly = (ps2netfs_pkt_readlink_rly *)&ps2netfs_send_packet[0];
   // do the stuff here
   devtype = devscan_gettype(cmd->path);
   if (devtype == IOPMGR_DEVTYPE_IOMANX)
     retval = readlink(cmd->path,readlinkrly->path,cmd->flags);
   // Build packet
   readlinkrly->cmd = htonl(PS2NETFS_READLINK_RLY);
   readlinkrly->len = htons((unsigned short)sizeof(ps2netfs_pkt_readlink_rly));
   readlinkrly->retval = htonl(retval);
   if (ps2netfs_lwip_send(ps2netfs_sock, readlinkrly, sizeof(ps2netfs_pkt_readlink_rly), 0) < 0)
   {
     dbgprintf("ps2netfs: error sending reply!\n");
     return -1 ;
   }
   return 0;
 }
References ps2netfs_pkt_readlink_rly::cmd, dbgprintf, devscan_gettype(), ENODEV, ps2netfs_pkt_open_req::flags, htonl(), htons(), IOPMGR_DEVTYPE_IOMANX, ps2netfs_pkt_readlink_rly::len, ps2netfs_pkt_open_req::path, ps2netfs_pkt_readlink_rly::path, ps2netfs_lwip_send(), PS2NETFS_READLINK_RLY, ps2netfs_send_packet, ps2netfs_sock, readlink(), and ps2netfs_pkt_readlink_rly::retval.
Referenced by ps2netfs_Listener().
ps2netfs_op_remove()
static int ps2netfs_op_remove (char * buf, int len) static
Handles a PS2NETFS_REMOVE_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found >=0 if handled ok. -X if error.
Definition at line 866 of file ps2_fio.c.
 {
   ps2netfs_pkt_open_req *cmd;
   ps2netfs_pkt_file_rly *removerly;
   int retval = -ENODEV;
   int devtype;
   cmd = (ps2netfs_pkt_open_req *)buf;
   dbgprintf("ps2netfs: remove\n");
   if (len != sizeof(ps2netfs_pkt_open_req))
   {
     dbgprintf("ps2netfs: got a broken packet (%d)!\n", len);
     return -1;
   }
   // do the stuff here
   devtype = devscan_gettype(cmd->path);
   if (devtype != IOPMGR_DEVTYPE_INVALID)
   {
     if (devtype == IOPMGR_DEVTYPE_IOMAN)
       retval = io_remove(cmd->path);
     else if (devtype == IOPMGR_DEVTYPE_IOMANX)
       retval = remove(cmd->path);
   }
   // now build the response
   removerly = (ps2netfs_pkt_file_rly *)&ps2netfs_send_packet[0];
   // Build packet
   removerly->cmd = htonl(PS2NETFS_REMOVE_RLY);
   removerly->len = htons((unsigned short)sizeof(ps2netfs_pkt_file_rly));
   removerly->retval = htonl(retval);
   if (ps2netfs_lwip_send(ps2netfs_sock, removerly, sizeof(ps2netfs_pkt_file_rly), 0) < 0)
   {
     dbgprintf("ps2netfs: error sending reply!\n");
     return -1;
   }
   return 0;
 }
References ps2netfs_pkt_file_rly::cmd, dbgprintf, devscan_gettype(), ENODEV, htonl(), htons(), io_remove(), IOPMGR_DEVTYPE_INVALID, IOPMGR_DEVTYPE_IOMAN, IOPMGR_DEVTYPE_IOMANX, ps2netfs_pkt_file_rly::len, ps2netfs_pkt_open_req::path, ps2netfs_lwip_send(), PS2NETFS_REMOVE_RLY, ps2netfs_send_packet, ps2netfs_sock, remove(), and ps2netfs_pkt_file_rly::retval.
Referenced by ps2netfs_Listener().
ps2netfs_op_rename()
static int ps2netfs_op_rename (char * buf, int len) static
Handles a PS2NETFS_RENAME_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found +X if handled ok, valid FD returned. -X if error.
Definition at line 1364 of file ps2_fio.c.
 {
   ps2netfs_pkt_symlink_req *cmd;
   ps2netfs_pkt_file_rly *renamerly;
   int retval = -ENODEV;
   int devtype;
   cmd = (ps2netfs_pkt_symlink_req *)buf;
   dbgprintf("ps2netfs: rename\n");
   if (len != sizeof(ps2netfs_pkt_symlink_req))
   {
     dbgprintf("ps2netfs: got a broken packet (%d)!\n", len);
     return -1;
   }
   // check that both are iomanx devices
   devtype = devscan_gettype(cmd->oldpath);
   if (devtype == IOPMGR_DEVTYPE_IOMANX)
   {
     devtype = devscan_gettype(cmd->newpath);
     if (devtype == IOPMGR_DEVTYPE_IOMANX)
       retval = rename(cmd->oldpath,cmd->newpath);
     else retval = -1;
   }
   // now build the response
   renamerly = (ps2netfs_pkt_file_rly *)&ps2netfs_send_packet[0];
   // Build packet
   renamerly->cmd = htonl(PS2NETFS_SYMLINK_RLY);
   renamerly->len = htons((unsigned short)sizeof(ps2netfs_pkt_file_rly));
   renamerly->retval = htonl(retval);
   if (ps2netfs_lwip_send(ps2netfs_sock, renamerly, sizeof(ps2netfs_pkt_file_rly), 0) < 0)
   {
     dbgprintf("ps2netfs: error sending reply!\n");
     return -1 ;
   }
   return 0;
 }
References ps2netfs_pkt_file_rly::cmd, dbgprintf, devscan_gettype(), ENODEV, htonl(), htons(), IOPMGR_DEVTYPE_IOMANX, ps2netfs_pkt_file_rly::len, ps2netfs_pkt_symlink_req::newpath, ps2netfs_pkt_symlink_req::oldpath, ps2netfs_lwip_send(), ps2netfs_send_packet, ps2netfs_sock, PS2NETFS_SYMLINK_RLY, rename(), and ps2netfs_pkt_file_rly::retval.
Referenced by ps2netfs_Listener().
ps2netfs_op_rmdir()
static int ps2netfs_op_rmdir (char * buf, int len) static
Handles a PS2NETFS_RMDIR_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found >=0 if handled ok. -X if error.
Definition at line 984 of file ps2_fio.c.
 {
   ps2netfs_pkt_open_req *cmd;
   ps2netfs_pkt_file_rly *rmdirrly;
   int retval = -ENODEV;
   int devtype;
   cmd = (ps2netfs_pkt_open_req *)buf;
   dbgprintf("ps2netfs: remove\n");
   if (len != sizeof(ps2netfs_pkt_open_req))
   {
     dbgprintf("ps2netfs: got a broken packet (%d)!\n", len);
     return -1;
   }
   // do the stuff here
   devtype = devscan_gettype(cmd->path);
   if (devtype != IOPMGR_DEVTYPE_INVALID)
   {
     if (devtype == IOPMGR_DEVTYPE_IOMAN)
       retval = io_rmdir(cmd->path);
     else if (devtype == IOPMGR_DEVTYPE_IOMANX)
       retval = rmdir(cmd->path);
   }
   // now build the response
   rmdirrly = (ps2netfs_pkt_file_rly *)&ps2netfs_send_packet[0];
   // Build packet
   rmdirrly->cmd = htonl(PS2NETFS_RMDIR_RLY);
   rmdirrly->len = htons((unsigned short)sizeof(ps2netfs_pkt_file_rly));
   rmdirrly->retval = htonl(retval);
   if (ps2netfs_lwip_send(ps2netfs_sock, rmdirrly, sizeof(ps2netfs_pkt_file_rly), 0) < 0)
   {
     dbgprintf("ps2netfs: error sending reply!\n");
     return -1;
   }
   return 0;
 }
References ps2netfs_pkt_file_rly::cmd, dbgprintf, devscan_gettype(), ENODEV, htonl(), htons(), io_rmdir(), IOPMGR_DEVTYPE_INVALID, IOPMGR_DEVTYPE_IOMAN, IOPMGR_DEVTYPE_IOMANX, ps2netfs_pkt_file_rly::len, ps2netfs_pkt_open_req::path, ps2netfs_lwip_send(), PS2NETFS_RMDIR_RLY, ps2netfs_send_packet, ps2netfs_sock, ps2netfs_pkt_file_rly::retval, and rmdir().
Referenced by ps2netfs_Listener().
ps2netfs_op_symlink()
static int ps2netfs_op_symlink (char * buf, int len) static
Handles a PS2NETFS_SYMLINK_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found +X if handled ok, valid FD returned. -X if error.
Definition at line 1682 of file ps2_fio.c.
 {
   ps2netfs_pkt_symlink_req *cmd;
   ps2netfs_pkt_file_rly *symlinkrly;
   int retval = -ENODEV;
   int devtype;
   cmd = (ps2netfs_pkt_symlink_req *)buf;
   dbgprintf("ps2netfs: symlink\n");
   if (len != sizeof(ps2netfs_pkt_symlink_req))
   {
     dbgprintf("ps2netfs: got a broken packet (%d)!\n", len);
     return -1;
   }
   // check that both are iomanx devices
   devtype = devscan_gettype(cmd->oldpath);
   if (devtype == IOPMGR_DEVTYPE_IOMANX)
   {
     devtype = devscan_gettype(cmd->newpath);
     if (devtype == IOPMGR_DEVTYPE_IOMANX)
       retval = symlink(cmd->oldpath,cmd->newpath);
     else retval = -1;
   }
   // now build the response
   symlinkrly = (ps2netfs_pkt_file_rly *)&ps2netfs_send_packet[0];
   // Build packet
   symlinkrly->cmd = htonl(PS2NETFS_SYMLINK_RLY);
   symlinkrly->len = htons((unsigned short)sizeof(ps2netfs_pkt_file_rly));
   symlinkrly->retval = htonl(retval);
   if (ps2netfs_lwip_send(ps2netfs_sock, symlinkrly, sizeof(ps2netfs_pkt_file_rly), 0) < 0)
   {
     dbgprintf("ps2netfs: error sending reply!\n");
     return -1 ;
   }
   return 0;
 }
References ps2netfs_pkt_file_rly::cmd, dbgprintf, devscan_gettype(), ENODEV, htonl(), htons(), IOPMGR_DEVTYPE_IOMANX, ps2netfs_pkt_file_rly::len, ps2netfs_pkt_symlink_req::newpath, ps2netfs_pkt_symlink_req::oldpath, ps2netfs_lwip_send(), ps2netfs_send_packet, ps2netfs_sock, PS2NETFS_SYMLINK_RLY, ps2netfs_pkt_file_rly::retval, and symlink().
Referenced by ps2netfs_Listener().
ps2netfs_op_sync()
static int ps2netfs_op_sync (char * buf, int len) static
Handles a PS2NETFS_SYNC_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found +X if handled ok, valid FD returned. -X if error.
Definition at line 1476 of file ps2_fio.c.
 {
   ps2netfs_pkt_open_req *cmd;
   ps2netfs_pkt_file_rly *syncrly;
   int retval = -ENODEV;
   int devtype;
   cmd = (ps2netfs_pkt_open_req *)buf;
   dbgprintf("ps2netfs: sync\n");
   if (len != sizeof(ps2netfs_pkt_open_req))
   {
     dbgprintf("ps2netfs: got a broken packet (%d)!\n", len);
     return -1;
   }
   // do the stuff here
   devtype = devscan_gettype(cmd->path);
   if (devtype == IOPMGR_DEVTYPE_IOMANX)
     retval = sync(cmd->path,ntohl(cmd->flags));
   // now build the response
   syncrly = (ps2netfs_pkt_file_rly *)&ps2netfs_send_packet[0];
   // Build packet
   syncrly->cmd = htonl(PS2NETFS_SYNC_RLY);
   syncrly->len = htons((unsigned short)sizeof(ps2netfs_pkt_file_rly));
   syncrly->retval = htonl(retval);
   if (ps2netfs_lwip_send(ps2netfs_sock, syncrly, sizeof(ps2netfs_pkt_file_rly), 0) < 0)
   {
     dbgprintf("ps2netfs: error sending reply!\n");
     return -1;
   }
   return 0;
 }
References ps2netfs_pkt_file_rly::cmd, dbgprintf, devscan_gettype(), ENODEV, ps2netfs_pkt_open_req::flags, htonl(), htons(), IOPMGR_DEVTYPE_IOMANX, ps2netfs_pkt_file_rly::len, ntohl, ps2netfs_pkt_open_req::path, ps2netfs_lwip_send(), ps2netfs_send_packet, ps2netfs_sock, PS2NETFS_SYNC_RLY, ps2netfs_pkt_file_rly::retval, and sync().
Referenced by ps2netfs_Listener().
ps2netfs_op_umount()
static int ps2netfs_op_umount (char * buf, int len) static
Handles a PS2NETFS_UMOUNT_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found +X if handled ok, valid FD returned. -X if error.
Definition at line 1584 of file ps2_fio.c.
 {
   ps2netfs_pkt_open_req *cmd;
   ps2netfs_pkt_file_rly *umountrly;
   int retval = -ENODEV;
   int devtype;
   cmd = (ps2netfs_pkt_open_req *)buf;
   dbgprintf("ps2netfs: umount\n");
   if (len != sizeof(ps2netfs_pkt_open_req))
   {
     dbgprintf("ps2netfs: got a broken packet (%d)!\n", len);
     return -1;
   }
   // do the stuff here
   devtype = devscan_gettype(cmd->path);
   if (devtype == IOPMGR_DEVTYPE_IOMANX)
     retval = umount(cmd->path);
   // now build the response
   umountrly = (ps2netfs_pkt_file_rly *)&ps2netfs_send_packet[0];
   // Build packet
   umountrly->cmd = htonl(PS2NETFS_UMOUNT_RLY);
   umountrly->len = htons((unsigned short)sizeof(ps2netfs_pkt_file_rly));
   umountrly->retval = htonl(retval);
   if (ps2netfs_lwip_send(ps2netfs_sock, umountrly, sizeof(ps2netfs_pkt_file_rly), 0) < 0)
   {
     dbgprintf("ps2netfs: error sending reply!\n");
     return -1 ;
   }
   return 0;
 }
References ps2netfs_pkt_file_rly::cmd, dbgprintf, devscan_gettype(), ENODEV, htonl(), htons(), IOPMGR_DEVTYPE_IOMANX, ps2netfs_pkt_file_rly::len, ps2netfs_pkt_open_req::path, ps2netfs_lwip_send(), ps2netfs_send_packet, ps2netfs_sock, PS2NETFS_UMOUNT_RLY, ps2netfs_pkt_file_rly::retval, and umount().
Referenced by ps2netfs_Listener().
ps2netfs_op_write()
static int ps2netfs_op_write (char * buf, int len) static
Handles a PS2NETFS_WRITE_CMD request.
Parameters
buf Pointer to packet data.
len Length of packet.
Returns
Status.
status returns: 0 if all request and response handled ok. -X if error.
return values for client: -19 (ENODEV) if device not found >=0 if handled ok , bytes written. -X if error.
Definition at line 680 of file ps2_fio.c.
 {
   ps2netfs_pkt_write_req *cmd;
   ps2netfs_pkt_file_rly *writerly;
   int retval = -1;
   fd_table_t *fdptr;
   cmd = (ps2netfs_pkt_write_req *)buf;
   dbgprintf("ps2netfs: write\n");
   // do the stuff here
   fdptr = fdh_get(ntohl(cmd->fd));
   if (fdptr != 0)
   {
     int left = ntohl(cmd->nbytes);
     int towrite, written;
     written = retval = 0;
     while ((retval >= 0) && (left > 0))
     {
       towrite = left; if (towrite > FIOTRAN_MAXSIZE) towrite = FIOTRAN_MAXSIZE;
       if (ps2netfs_recv_bytes(ps2netfs_sock, ps2netfs_fiobuffer, towrite) <=0 )
       {
         dbgprintf("ps2netfs: error reading data!\n");
         return -1;
       }
       if (fdptr->devtype == IOPMGR_DEVTYPE_IOMAN)
         retval = io_write(fdptr->realfd,ps2netfs_fiobuffer,towrite);
       else if (fdptr->devtype == IOPMGR_DEVTYPE_IOMANX)
         retval = write(fdptr->realfd,ps2netfs_fiobuffer,towrite);
       if (retval > 0) { written += retval; left -= retval; }
     }
     if (retval > 0)
         retval = written;
   }
   // now build the response
   writerly = (ps2netfs_pkt_file_rly *)&ps2netfs_send_packet[0];
   // Build packet
   writerly->cmd = htonl(PS2NETFS_WRITE_RLY);
   writerly->len = htons((unsigned short)sizeof(ps2netfs_pkt_file_rly));
   writerly->retval = htonl(retval);
   if (ps2netfs_lwip_send(ps2netfs_sock, writerly, sizeof(ps2netfs_pkt_file_rly), 0) < 0)
   {
     dbgprintf("ps2netfs: error sending reply!\n");
     return -1;
   }
   return 0;
 }
References ps2netfs_pkt_file_rly::cmd, dbgprintf, fd_table_t::devtype, ps2netfs_pkt_write_req::fd, fdh_get, FIOTRAN_MAXSIZE, htonl(), htons(), io_write(), IOPMGR_DEVTYPE_IOMAN, IOPMGR_DEVTYPE_IOMANX, ps2netfs_pkt_file_rly::len, ps2netfs_pkt_write_req::nbytes, ntohl, ps2netfs_fiobuffer, ps2netfs_lwip_send(), ps2netfs_recv_bytes(), ps2netfs_send_packet, ps2netfs_sock, PS2NETFS_WRITE_RLY, fd_table_t::realfd, ps2netfs_pkt_file_rly::retval, and write().
Referenced by ps2netfs_Listener().
ps2netfs_serv()
int ps2netfs_serv (void * argv)
Main ps2netfs Thread.
Parameters
argv Parameters to thread.
Returns
Status.
This is the main thread function for ps2netfs. It runs until 'ps2netfs_active' is set to 0. Handles accepting connections and passing them onto the listener function to handle them.
status returns: 0 if exiting and finished. -1 if error starting thread.
Definition at line 1955 of file ps2_fio.c.
 {
  struct sockaddr_in server_addr;
  struct sockaddr_in client_addr;
  int sock;
  int client_sock;
  int client_len;
  int ret;
  dbgprintf(" - ps2netfs TCP Server -\n");
  devscan_setup(DEVSCAN_MASK);
  fdh_setup();
  memset((void *)&server_addr, 0, sizeof(server_addr));
  // Should perhaps specify PC side ip..
  server_addr.sin_family = AF_INET;
  server_addr.sin_addr.s_addr = htonl(INADDR_ANY);
  server_addr.sin_port = htons(PS2NETFS_LISTEN_PORT);
  while ((sock = socket(AF_INET, SOCK_STREAM, 0)) < 0)
  {
    dbgprintf("ps2netfs: socket creation error (%d)\n", sock);
    return -1;
  }
  ret = bind(sock, (struct sockaddr *)&server_addr,
          sizeof(server_addr));
  if (ret < 0)
  {
    dbgprintf("ps2netfs: bind error (%d)\n", ret);
    ps2netfs_close_socket();
    return -1;
  }
  ret = listen(sock, 5);
  if (ret < 0)
  {
    dbgprintf("ps2netfs: listen error (%d)\n", ret);
    disconnect(sock);
    return -1;
  }
  // Active flag kinda sux, cause it wont be checked until a new client has
  // connected.. But it's better than nothing and good for now at least
  ps2netfs_active = 1;
  // Connection loop
  while(ps2netfs_active)
  {
    dbgprintf("ps2netfs: Waiting for connection\n");
    client_len = sizeof(client_addr);
    client_sock = accept(sock, (struct sockaddr *)&client_addr,
                         &client_len);
    if (client_sock < 0)
    {
      dbgprintf("ps2netfs: accept error (%d)", client_sock);
      continue;
    }
    dbgprintf("Client connected from %x\n",
              client_addr.sin_addr.s_addr);
    if (ps2netfs_sock > 0)
    {
      dbgprintf("ps2netfs: Client reconnected\n");
      ret = ps2netfs_close_socket();
      dbgprintf("ps2netfs: close ret %d\n", ret);
      continue;
    }
    ps2netfs_sock = client_sock;
    if (ps2netfs_sock > 0)
    {
      ps2netfs_Listener(ps2netfs_sock);
      ret = ps2netfs_close_socket();
      dbgprintf("ps2netfs: close2 ret %d\n", ret);
      continue;
    }
  }
  if (ps2netfs_sock > 0)
    disconnect(ps2netfs_sock);
  disconnect(sock);
  ExitDeleteThread();
  return 0;
 }
References accept, AF_INET, bind, dbgprintf, DEVSCAN_MASK, devscan_setup(), disconnect, ExitDeleteThread(), fdh_setup(), htonl(), htons(), INADDR_ANY, listen, memset(), ps2netfs_active, ps2netfs_close_socket(), PS2NETFS_LISTEN_PORT, ps2netfs_Listener(), ps2netfs_sock, in_addr::s_addr, sockaddr_in::sin_addr, sockaddr_in::sin_family, sockaddr_in::sin_port, SOCK_STREAM, and socket.
Referenced by ps2netfs_Init().
Variable Documentation
dev_info_list
dev_table_t dev_info_list[DEVSCAN_MAX+1] static
Device type structure.
Definition at line 41 of file devscan.c.
Referenced by devscan_getdevlist(), devscan_gettype(), and devscan_setup().