ps2sdk: iopmgr - IOP Manager
iopmgr - IOP Manager
Functions
void list_all_libraries ()
void list_all_modules ()
void list_devices_ioman ()
void list_devices_iomanx ()
void list_fs_devices (int mgrtype)
void cmdline_handle (char *command, char *arg1)
iop_device_t * iopmgr_get_iomandev (char *device)
iop_device_t * iopmgr_get_iomanxdev (char *device)
int iopmgr_get_devicelist (int man, int devtype, char *buffer)
iop_device_t * iopmgr_get_device (char *device)
int iopmgr_get_devicetype (char *device)
int _start (int argc, char *argv[])
int shutdown ()
iop_library_t * slib_get_lib_by_name (const char *name)
void * slib_get_exportlist_by_name (const char *name)
int slib_get_version_by_name (const char *name)
int slib_release_library (const char *name)
ModuleInfo_t * smod_get_next_mod (ModuleInfo_t *cur_mod)
ModuleInfo_t * smod_get_mod_by_name (const char *name)
int smod_get_modcount_by_name (const char *name)
int smod_get_modversion_by_name (const char *name)
int smod_unload_module (const char *name)
Detailed Description
Function Documentation
_start()
int _start (int argc, char * argv[])
Entry point for IRX.
if argc <= 1 , install as library. if argc > 1 , run given command in argv[1].
Parameters
argc Number of arguments.
argv Pointer to array of arguments.
Returns
Module Status on Exit.
return values: MODULE_RESIDENT_END if loaded and registered as library. MODULE_NO_RESIDENT_END if just exiting normally.
Definition at line 46 of file main.c.
 {
   printf("%s - Version %d.%d\nCopyright (c) 2003,2004 adresd\n\n",
     IOPMGR_MODNAME, IOPMGR_VERSION_HIGH, IOPMGR_VERSION_LOW);
   if (argc > 1)
   { /* Execute in command line mode, so parse command */
     if(argc>2)
     {
       cmdline_handle(argv[1],argv[2]);
     }
     else
     {
       cmdline_handle(argv[1],NULL);
     }
   }
   else
   { /* no params, so set into resident mode */
     if (RegisterLibraryEntries(&_exp_iopmgr) == 0)
     {
       printf("Registered.\n");
       return MODULE_RESIDENT_END;
     }
     else
     {
       /* luckily the previously installed one will be higher up the list, so will
        *  be the first one found , so get the version
        */
       int version = smod_get_modversion_by_name(IOPMGR_MODNAME);
       printf ("Error Registering - ");
       if (version >= 0)
         printf("Already Registered , version : %d.%d\n",
                 (version&0xff00)>>8,version&0xff);
       else
         printf("Error : %d\n",version);
     }
   }
   printf("\nExiting.\n");
   return MODULE_NO_RESIDENT_END;
 }
References _exp_iopmgr, cmdline_handle(), IOPMGR_MODNAME, IOPMGR_VERSION_HIGH, IOPMGR_VERSION_LOW, MODULE_NO_RESIDENT_END, MODULE_RESIDENT_END, NULL, printf(), RegisterLibraryEntries(), smod_get_modversion_by_name(), and irx_export_table::version.
cmdline_handle()
void cmdline_handle (char * command, char * arg1)
Handles basic parsing of commands, for command execution mode.
Parameters
command Pointer to command string.
Definition at line 161 of file commandline.c.
 {
   if (!strncmp("modlist",command,7))
     list_all_modules();
   else if (!strncmp("iomanx",command,6))
   {
     list_devices_iomanx();
     list_fs_devices(IOPMGR_DEVTYPE_IOMANX);
   }
   else if (!strncmp("ioman",command,5))
   {
     list_devices_ioman();
     list_fs_devices(IOPMGR_DEVTYPE_IOMAN);
   }
   else if (!strncmp("devices",command,7))
   {
     list_devices_ioman();
     list_devices_iomanx();
     list_fs_devices(IOPMGR_DEVTYPE_ALL);
   }
   else if (!strncmp("libs",command,4))
     list_all_libraries();
   else if (!strncmp("release",command,7))
     shutdown();
   else if (!strncmp("help",command,4))
   {
     printf("\nCommands are:\n modlist - List of Loaded Modules\n iomanx  - List iomanx Devices\n ioman   - List ioman Devices\n devices - List all Devices\n libs    - List Registered Libraries\n release - release iopmgr lib if loaded\n help    - This page\n");
   }
   else if (!strncmp("unreg",command,7))
   {
     if (arg1 != 0)
     {
       printf("unregistering : '%s' - ",arg1);
       switch(slib_release_library(arg1))
       {
         case 0: printf("UnRegistered\n"); break;
         case -1: printf("Failed to UnRegister\n"); break;
         case -2: printf("Library Not Present\n"); break;
       }
     }
     else printf("\nNo Library Specified\n");
   }
   else printf("\nUnknown Command , try 'help'\n");
 }
References IOPMGR_DEVTYPE_ALL, IOPMGR_DEVTYPE_IOMAN, IOPMGR_DEVTYPE_IOMANX, list_all_libraries(), list_all_modules(), list_devices_ioman(), list_devices_iomanx(), list_fs_devices(), printf(), shutdown(), slib_release_library(), and strncmp().
Referenced by _start().
iopmgr_get_device()
iop_device_t* iopmgr_get_device (char * device)
Get a pointer to a device of either type
Parameters
device Stringname of device (eg "host).
Returns
Pointer to device structure.
return values: 0 if not found. pointer to device structure for named driver if found.
Definition at line 163 of file devices.c.
 {
   iop_device_t *devptr;
   devptr = iopmgr_get_iomandev(device);
   if (devptr > 0) return(devptr);
   devptr = iopmgr_get_iomanxdev(device);
   if (devptr > 0) return(devptr);
   return 0;
 }
References iopmgr_get_iomandev(), and iopmgr_get_iomanxdev().
iopmgr_get_devicelist()
int iopmgr_get_devicelist (int man, int devtype, char * buffer)
Get a list of devices of a certain type
Parameters
man Device manager mask (IOPMGR_DEVTYPE_IOMAN or IOPMGR_DEVTYPE_IOMANX).
devtype Device type mask (0x10 for filesystems).
Returns
Number of devices found
return values: 0 if no matching devices found device count, if found, and buffer buffer filled with ascii serial string of device names.
Definition at line 102 of file devices.c.
 {
   ModuleInfo_t *info;
   iop_device_t **devinfo_table;
   int i;
   char *bufptr = buffer;
   int  count = 0;
   /* do the ioman devices */
   if ((man & IOPMGR_DEVTYPE_IOMAN))
   if ((info = smod_get_mod_by_name(IOPMGR_IOMAN_IDENT)))
   {
     /* Find the start of the device info array, in .bss.  */
     devinfo_table = (iop_device_t **)(info->text_start + info->text_size + info->data_size + 0x0c);
     /* The device info table had 16 entries, but some may be empty.  Just look at all of them.  */
     for (i = 0; i < 16; i++)
     {
       if (devinfo_table[i])
         if ((devinfo_table[i]->type & devtype))
         {
           strcpy(bufptr,devinfo_table[i]->name);
           bufptr += strlen(bufptr)+1;
           count++;
         }
     }
   }
   /* do the iomanx devices */
   if ((man & IOPMGR_DEVTYPE_IOMANX))
   if ((info = smod_get_mod_by_name(IOPMGR_IOMANX_IDENT)))
   {
     /* Find the start of the device info array, in .bss.  */
     devinfo_table = (iop_device_t **)(info->text_start + info->text_size + info->data_size);
     /* The device info table had 32 entries, but some may be empty.  Just look at all of them.  */
     for (i = 0; i < 32; i++)
     {
       if (devinfo_table[i])
         /* only add iomanx ones here, so must have extended flag set  else we get duplication with new iomanx */
         if ((devinfo_table[i]->type & IOP_DT_FSEXT) && (devinfo_table[i]->type & devtype))
         {
           strcpy(bufptr,devinfo_table[i]->name);
           bufptr += strlen(bufptr)+1;
           count++;
         }
     }
   }
   return count;
 }
References buffer, IOP_DT_FSEXT, IOPMGR_DEVTYPE_IOMAN, IOPMGR_DEVTYPE_IOMANX, IOPMGR_IOMAN_IDENT, IOPMGR_IOMANX_IDENT, smod_get_mod_by_name(), strcpy(), strlen(), and iop_device_t::type.
Referenced by list_fs_devices().
iopmgr_get_devicetype()
int iopmgr_get_devicetype (char * device)
Returns which i/o manager handles the given device.
Parameters
device Stringname of device (eg "host).
Returns
numeric value for i/o manager.
return values: IOPMGR_DEVTYPE_INVALID if not found, IOPMGR_DEVTYPE_IOMAN if found and ioman device, IOPMGR_DEVTYPE_IOMANX if found and iomanx device.
Definition at line 184 of file devices.c.
 {
   if (iopmgr_get_iomandev(device) > 0)
     return(IOPMGR_DEVTYPE_IOMAN);
   if (iopmgr_get_iomanxdev(device) > 0)
     return(IOPMGR_DEVTYPE_IOMANX);
   return IOPMGR_DEVTYPE_INVALID;
 }
References IOPMGR_DEVTYPE_INVALID, IOPMGR_DEVTYPE_IOMAN, IOPMGR_DEVTYPE_IOMANX, iopmgr_get_iomandev(), and iopmgr_get_iomanxdev().
Referenced by list_fs_devices().
iopmgr_get_iomandev()
iop_device_t* iopmgr_get_iomandev (char * device)
Get a pointer to an ioman device handler.
Parameters
device Stringname of device (eg "host").
Returns
Pointer to device structure.
return values: 0 if not found. pointer to device structure for named driver if found.
Definition at line 34 of file devices.c.
 {
   ModuleInfo_t *info = 0;
   iop_device_t **devinfo_table;
   int i;
   int len = strlen(device) + 1;
   if (!(info = smod_get_mod_by_name(IOPMGR_IOMAN_IDENT))) {
     return 0;
   }
   /* Find the start of the device info array, in .bss.  */
   devinfo_table = (iop_device_t **)(info->text_start + info->text_size + info->data_size + 0x0c);
   /* The device info table had 16 entries, but some may be empty.  Just look at all of them.  */
   for (i = 0; i < 16; i++) {
     if (devinfo_table[i])
       if (!memcmp(devinfo_table[i]->name, device, len))
         return(devinfo_table[i]);
   }
   return 0;
 }
References IOPMGR_IOMAN_IDENT, memcmp(), smod_get_mod_by_name(), and strlen().
Referenced by iopmgr_get_device(), and iopmgr_get_devicetype().
iopmgr_get_iomanxdev()
iop_device_t* iopmgr_get_iomanxdev (char * device)
Get a pointer to an iomanx device handler.
Parameters
device Stringname of device (eg "hdd").
Returns
Pointer to device structure.
return values: 0 if not found. pointer to device structure for named driver if found.
Definition at line 67 of file devices.c.
 {
   ModuleInfo_t *info;
   iop_device_t **devinfo_table;
   int i;
   int len = strlen(device) + 1;
   if (!(info = smod_get_mod_by_name(IOPMGR_IOMANX_IDENT))) {
     return 0;
   }
   /* Find the start of the device info array, in .bss.  */
   devinfo_table = (iop_device_t **)(info->text_start + info->text_size + info->data_size);
   /* The device info table had 32 entries, but some may be empty.  Just look at all of them.  */
   for (i = 0; i < 32; i++) {
     if (devinfo_table[i])
       if (!memcmp(devinfo_table[i]->name, device, len))
         return(devinfo_table[i]);
   }
   return 0;
 }
References IOPMGR_IOMANX_IDENT, memcmp(), smod_get_mod_by_name(), and strlen().
Referenced by iopmgr_get_device(), and iopmgr_get_devicetype().
list_all_libraries()
void list_all_libraries ()
Prints out a list of all currently registered libraries with their name and version.
Definition at line 28 of file commandline.c.
 {
   char name[9];
   iop_library_t *libptr;
   printf("Registered Libraries:\n");
   libptr = GetLoadcoreInternalData()->let_next;
   while (libptr)
   {
     /* We only have a 8-char buffer for the name, so we need to convert it into a C
        string just in case the name is 8 chars.  */
     memset(name, 0, sizeof(name));
     memcpy(name, libptr->name, 8);
     printf("    %-20s v%d.%d\n",name,
      (libptr->version&0xff00)>>8,libptr->version&0xff);
     libptr = libptr->prev;
   }
   printf("\n");
 }
References GetLoadcoreInternalData(), lc_internals_t::let_next, memcpy(), memset(), iop_library_t::name, iop_library_t::prev, printf(), and iop_library_t::version.
Referenced by cmdline_handle().
list_all_modules()
void list_all_modules ()
Prints out a list of all currently loaded IRX modules with description and version number.
Definition at line 52 of file commandline.c.
 {
   ModuleInfo_t *info;
   printf("Loaded Modules:\n");
   info = smod_get_next_mod(0);
   while (info != 0)
   {
     printf("    %-40s v%d.%d (%d)\n",info->name,
       (info->version&0xff00)>>8,(info->version&0xff),info->flags);
     info = info->next;
   }
   printf("\n");
 }
References printf(), and smod_get_next_mod().
Referenced by cmdline_handle().
list_devices_ioman()
void list_devices_ioman ()
Print out all devices for ONLY ioman and shows which one they belong to.
Definition at line 69 of file commandline.c.
 {
         ModuleInfo_t *info;
         iop_device_t **devinfo_table;
         int i;
         if (!(info = smod_get_mod_by_name(IOPMGR_IOMAN_IDENT))) {
                 printf("Unable to find '%s's module info!\n",IOPMGR_IOMAN_IDENT);
                 return;
         }
         /* Find the start of the device info array, in .bss.  */
         devinfo_table = (iop_device_t **)(info->text_start + info->text_size + info->data_size + 0x0c);
         printf("Known '%s' devices:\n",IOPMGR_IOMAN_IDENT);
         /* The device info table had 16 entries, but some may be empty.  Just look at all of them.  */
         for (i = 0; i < 16; i++) {
                 if (devinfo_table[i])
                         printf("    %-10s: %-27s  v%d.%d type:%08X\n",
                           devinfo_table[i]->name, devinfo_table[i]->desc,
                           (devinfo_table[i]->version&0xff00)>>8,
                           (devinfo_table[i]->version&0xff),
                           devinfo_table[i]->type);
         }
         printf("\n");
 }
References IOPMGR_IOMAN_IDENT, printf(), and smod_get_mod_by_name().
Referenced by cmdline_handle().
list_devices_iomanx()
void list_devices_iomanx ()
Print out all devices for ONLY iomanx and shows which one they belong to.
Definition at line 99 of file commandline.c.
 {
         ModuleInfo_t *info;
         iop_device_t **devinfo_table;
         int i;
         if (!(info = smod_get_mod_by_name(IOPMGR_IOMANX_IDENT))) {
                 printf("Unable to find '%s's module info!\n",IOPMGR_IOMANX_IDENT);
                 return;
         }
         /* Find the start of the device info array, in .bss.  */
         devinfo_table = (iop_device_t **)(info->text_start + info->text_size + info->data_size + 0x00);
         printf("Known '%s' devices:\n",IOPMGR_IOMANX_IDENT);
         /* The device info table had 32 entries, but some may be empty.  Just look at all of them.  */
         for (i = 0; i < 32; i++) {
                 if (devinfo_table[i])
                         printf("    %-10s: %-28s v%d.%d type:%08X\n",
                         devinfo_table[i]->name, devinfo_table[i]->desc,
                         (devinfo_table[i]->version&0xff00)>>8,
                         (devinfo_table[i]->version&0xff),
                         devinfo_table[i]->type);
         }
         printf("\n");
 }
References IOPMGR_IOMANX_IDENT, printf(), and smod_get_mod_by_name().
Referenced by cmdline_handle().
list_fs_devices()
void list_fs_devices (int mgrtype)
Print out all devices for both ioman and iomanx and shows which one they belong to.
Parameters
mgrtype Device manager type search mask (IOPMGR_DEVTYPE_XXXX).
Definition at line 131 of file commandline.c.
 {
   int count;
   int i;
   char *bufptr;
   char buffer[256];
   bufptr = &buffer[0];
   count = iopmgr_get_devicelist(mgrtype,IOP_DT_FS,bufptr);
   printf("filesystems found : %d\n",count);
   for (i=0;i<count;i++)
   {
     printf(" %02d : %-10s - ",i,bufptr);
     switch(iopmgr_get_devicetype(bufptr))
     {
       case IOPMGR_DEVTYPE_IOMAN:     printf("%s\n",IOPMGR_IOMAN_IDENT);break;
       case IOPMGR_DEVTYPE_IOMANX:    printf("%s\n",IOPMGR_IOMANX_IDENT);break;
       default: printf("Invalid\n");break;
     }
     bufptr += strlen(bufptr)+1;
   }
 }
References buffer, IOP_DT_FS, IOPMGR_DEVTYPE_IOMAN, IOPMGR_DEVTYPE_IOMANX, iopmgr_get_devicelist(), iopmgr_get_devicetype(), IOPMGR_IOMAN_IDENT, IOPMGR_IOMANX_IDENT, printf(), and strlen().
Referenced by cmdline_handle().
shutdown()
int shutdown (void)
shutdown the IRX.
This checks if the library is registered, if it is then it unregisters it.
Returns
Module Status on Exit.
return values: MODULE_RESIDENT_END if loaded and registered as library. MODULE_NO_RESIDENT_END if just exiting normally.
Definition at line 99 of file main.c.
 {
   switch(slib_release_library(IOPMGR_LIBNAME))
   {
     case 0: printf("UnRegistered\n"); break;
     case -1: printf("Failed to UnRegister\n"); return MODULE_RESIDENT_END; break;
     case -2: printf("Library Not Present\n"); break;
   }
   return MODULE_NO_RESIDENT_END;
 }
References IOPMGR_LIBNAME, MODULE_NO_RESIDENT_END, MODULE_RESIDENT_END, printf(), and slib_release_library().
slib_get_exportlist_by_name()
void* slib_get_exportlist_by_name (const char * name)
Get pointer to export list for named library.
Parameters
name Stringname of library (eg "ioman").
Returns
Pointer to export list.
return values: 0 if not found. pointer to export list for registered library if found.
Definition at line 62 of file slib.c.
 {
   iop_library_t *libptr;
   libptr = slib_get_lib_by_name(name);
   if (libptr != 0)
     return libptr->exports;
   return 0;
 }
References iop_library_t::exports, and slib_get_lib_by_name().
slib_get_lib_by_name()
iop_library_t* slib_get_lib_by_name (const char * name)
Get pointer to system library structure for named library.
Parameters
name Stringname of library (eg "ioman").
Returns
Pointer to IOP library structure.
return values: 0 if not found. pointer to library structure for registered library if found.
Definition at line 37 of file slib.c.
 {
   iop_library_t *libptr;
   int len = strlen(name) + 1;
   libptr = GetLoadcoreInternalData()->let_next;
   while ((libptr != 0))
   {
     if (!memcmp(libptr->name, name, len))
         return libptr;
     libptr = libptr->prev;
   }
   return 0;
 }
References GetLoadcoreInternalData(), lc_internals_t::let_next, memcmp(), iop_library_t::name, iop_library_t::prev, and strlen().
Referenced by slib_get_exportlist_by_name(), slib_get_version_by_name(), and slib_release_library().
slib_get_version_by_name()
int slib_get_version_by_name (const char * name)
Get version number for named library.
Parameters
name Stringname of library (eg "ioman").
Returns
version number.
return values: 0 if not found. Version number for registered library if found. (0xXXYY, XX=HIGH, YY=LOW)
Definition at line 82 of file slib.c.
 {
   iop_library_t *libptr;
   libptr = slib_get_lib_by_name(name);
   if (libptr != 0)
     return (int)libptr->version;
   return 0;
 }
References slib_get_lib_by_name(), and iop_library_t::version.
slib_release_library()
int slib_release_library (const char * name)
Release (Unregister) a given named registered library.
Parameters
name Stringname of library (eg "ioman").
Returns
Status of operation.
return values: 0 if found and sucessfully unregistered. -1 if found, but failed to unregister. -2 if library was not found.
Definition at line 103 of file slib.c.
 {
   struct irx_export_table *libptr;
   libptr = (struct irx_export_table *)slib_get_lib_by_name(name);
   if (libptr != 0)
     return ReleaseLibraryEntries(libptr);
   return -2;
 }
References irx_export_table::name, ReleaseLibraryEntries(), and slib_get_lib_by_name().
Referenced by cmdline_handle(), and shutdown().
smod_get_mod_by_name()
ModuleInfo_t* smod_get_mod_by_name (const char * name)
Get pointer to module structure for named module.
Parameters
name Stringname of module (eg "atad_driver").
Returns
Pointer to module structure.
return values: 0 if not found. pointer to module structure for loaded module if found.
Definition at line 63 of file smod.c.
 {
   ModuleInfo_t *modptr;
   int len = strlen(name)+1;
   modptr = smod_get_next_mod(0);
   while (modptr != 0)
   {
     if (!memcmp(modptr->name, name, len))
       return modptr;
     modptr = modptr->next;
   }
   return 0;
 }
References memcmp(), ModuleInfo_t::name, ModuleInfo_t::next, smod_get_next_mod(), and strlen().
Referenced by smod_get_modversion_by_name().
smod_get_modcount_by_name()
int smod_get_modcount_by_name (const char * name)
Get instance count for given module name.
Parameters
name Stringname of module (eg "atad_driver").
Returns
Number of instances loaded.
NOTE: if doing this to check for own module, the run being used to check automatically adds one to the count.. so ret=2 means another, instance loaded as well as current one.
Definition at line 88 of file smod.c.
 {
   ModuleInfo_t *modptr = 0;
   int len = strlen(name)+1;
   int count = 0;
   modptr = smod_get_next_mod(0);
   while (modptr != 0)
   {
     if (!memcmp(modptr->name, name, len))
       count++;
     modptr = modptr->next;
   }
   return count;
 }
References memcmp(), ModuleInfo_t::name, ModuleInfo_t::next, smod_get_next_mod(), and strlen().
smod_get_modversion_by_name()
int smod_get_modversion_by_name (const char * name)
Get version number for given module name.
Parameters
name Stringname of module (eg "atad_driver").
Returns
Version number.
return values: 0 if not found. Version number for module if found. (0xXXYY, XX=HIGH, YY=LOW)
Definition at line 115 of file smod.c.
 {
   ModuleInfo_t *modptr = 0;
   modptr = smod_get_mod_by_name(name);
   if (modptr != 0)
     return (int)modptr->version;
   else
     return -1;
 }
References smod_get_mod_by_name(), and ModuleInfo_t::version.
Referenced by _start().
smod_get_next_mod()
ModuleInfo_t* smod_get_next_mod (ModuleInfo_t * cur_mod)
Get pointer to head of module list, or next module in list.
Parameters
cur_mod Pointer to module structure, or 0 to return the head.
Returns
Pointer to module structure.
return values: 0 if end of list. pointer to head of module list if cur_mod=0. pointer to next module, if cur_mod!=0.
Definition at line 39 of file smod.c.
 {
   /* If cur_mod is 0, return the head of the list.  */
   if (!cur_mod) {
     return GetLoadcoreInternalData()->image_info;
   } else {
     if (!cur_mod->next)
       return 0;
     else
       return cur_mod->next;
   }
   return 0;
 }
References GetLoadcoreInternalData(), lc_internals_t::image_info, and ModuleInfo_t::next.
Referenced by smod_get_mod_by_name(), and smod_get_modcount_by_name().
smod_unload_module()
int smod_unload_module (const char * name)
Unload the named module.
Parameters
name Stringname of module (eg "atad_driver").
Returns
Status of operation.
return values: 0 if found and sucessfully unloaded. -1 if found, but failed to unload. -2 if module was not found.
Definition at line 136 of file smod.c.
 {
   return -2;
 }