ps2sdk: devfs: PS2 Device Filing System
devfs: PS2 Device Filing System
Data Structures
union devfs_loc_t
struct devfs_info_t
struct devfs_node_t
Macros
#define DEVFS_MAX_SUBDEVS 16
#define DEVFS_MAX_DEVNAME_LENGTH 32
#define DEVFS_MAX_DESC_LENGTH 256
#define DEVFS_IOCTL_TYPE_1 1
#define DEVFS_IOCTL_TYPE_2 2
#define DEVFS_IOCTL_GETDESC 0
#define INVALID_HDEV -1
#define devfs_IMPORTS_start DECLARE_IMPORT_TABLE(devfs, 1, 1)
#define devfs_IMPORTS_end END_IMPORT_TABLE
#define I_DevFSAddDevice DECLARE_IMPORT(4, DevFSAddDevice)
#define I_DevFSDelDevice DECLARE_IMPORT(5, DevFSDelDevice)
#define I_DevFSAddSubDevice DECLARE_IMPORT(6, DevFSAddSubDevice)
#define I_DevFSDelSubDevice DECLARE_IMPORT(7, DevFSDelSubDevice)
Typedefs
typedef s32 HDEV
typedef s32(* read_handler) (const devfs_info_t *dev, u8 *buf, s32 len)
typedef s32(* write_handler) (const devfs_info_t *dev, u8 *buf, s32 len)
typedef s32(* ioctl_handler) (const devfs_info_t *dev, int ioctl_type, int cmd, void *arg, size_t arglen, void *buf, size_t buflen)
Enumerations
enum devfs_subdev_modes {
DEVFS_MODE_EX = (1 << 0) ,
DEVFS_MODE_W = (1 << 1) ,
DEVFS_MODE_R = (1 << 2) ,
DEVFS_MODE_RW = (DEVFS_MODE_R | DEVFS_MODE_W)
}
enum devfs_devtypes {
DEVFS_DEVTYPE_CHAR = 1 ,
DEVFS_DEVTYPE_BLOCK = 2 ,
DEVFS_DEVTYPE_STREAM = 3
}
Functions
HDEV DevFSAddDevice (const devfs_node_t *node)
int DevFSDelDevice (HDEV hDev)
int DevFSAddSubDevice (HDEV hDev, u32 subdev_no, s32 mode, devfs_loc_t extent, void *data)
int DevFSDelSubDevice (HDEV hDev, u32 subdev_no)
Detailed Description
Macro Definition Documentation
devfs_IMPORTS_end
#define devfs_IMPORTS_end END_IMPORT_TABLE
Definition at line 155 of file devfs.h.
devfs_IMPORTS_start
#define devfs_IMPORTS_start DECLARE_IMPORT_TABLE(devfs, 1, 1)
Definition at line 154 of file devfs.h.
DEVFS_IOCTL_GETDESC
#define DEVFS_IOCTL_GETDESC 0
ioctl command to return the description associated with a device
Definition at line 66 of file devfs.h.
DEVFS_IOCTL_TYPE_1
#define DEVFS_IOCTL_TYPE_1 1
Specifies ioctl was called. No return value and the lengths are invalid
Definition at line 61 of file devfs.h.
DEVFS_IOCTL_TYPE_2
#define DEVFS_IOCTL_TYPE_2 2
ioctl2 was called. Parameters should all be valid
Definition at line 63 of file devfs.h.
DEVFS_MAX_DESC_LENGTH
#define DEVFS_MAX_DESC_LENGTH 256
Maximum length of a description string
Definition at line 32 of file devfs.h.
DEVFS_MAX_DEVNAME_LENGTH
#define DEVFS_MAX_DEVNAME_LENGTH 32
Maximum size of a device name
Definition at line 30 of file devfs.h.
DEVFS_MAX_SUBDEVS
#define DEVFS_MAX_SUBDEVS 16
Maximum number of sub devices per device
Definition at line 28 of file devfs.h.
I_DevFSAddDevice
#define I_DevFSAddDevice DECLARE_IMPORT(4, DevFSAddDevice)
Definition at line 157 of file devfs.h.
I_DevFSAddSubDevice
#define I_DevFSAddSubDevice DECLARE_IMPORT(6, DevFSAddSubDevice)
Definition at line 159 of file devfs.h.
I_DevFSDelDevice
#define I_DevFSDelDevice DECLARE_IMPORT(5, DevFSDelDevice)
Definition at line 158 of file devfs.h.
I_DevFSDelSubDevice
#define I_DevFSDelSubDevice DECLARE_IMPORT(7, DevFSDelSubDevice)
Definition at line 160 of file devfs.h.
INVALID_HDEV
#define INVALID_HDEV -1
Defines an invalid HDEV value
Definition at line 152 of file devfs.h.
Typedef Documentation
HDEV
typedef s32 HDEV
Type to hold a handle to a device
Definition at line 26 of file devfs.h.
ioctl_handler
typedef s32(* ioctl_handler) (const devfs_info_t *dev, int ioctl_type, int cmd, void *arg, size_t arglen, void *buf, size_t buflen)
Typedef of the ioctl handler
Definition at line 99 of file devfs.h.
read_handler
typedef s32(* read_handler) (const devfs_info_t *dev, u8 *buf, s32 len)
Typedef of the read event handler
Definition at line 95 of file devfs.h.
write_handler
typedef s32(* write_handler) (const devfs_info_t *dev, u8 *buf, s32 len)
Typedef of the write event handler
Definition at line 97 of file devfs.h.
Enumeration Type Documentation
devfs_devtypes
enum devfs_devtypes
Enumeration of device type.
Note
These are currently not used
Enumerator
DEVFS_DEVTYPE_CHAR
Indicates a device is character device
DEVFS_DEVTYPE_BLOCK
Indicates a device is a block device
DEVFS_DEVTYPE_STREAM
Indicates a device is a stream device (no seek)
Definition at line 50 of file devfs.h.
 {
     DEVFS_DEVTYPE_CHAR = 1,
     DEVFS_DEVTYPE_BLOCK = 2,
     DEVFS_DEVTYPE_STREAM = 3
 };
devfs_subdev_modes
enum devfs_subdev_modes
Enumeration of sub device access modes
Enumerator
DEVFS_MODE_EX
Indicates a sub device can only be opened by one application at a time
DEVFS_MODE_W
Indicates a sub device can be opened for reading
DEVFS_MODE_R
Indicates a sub device can be opened for writing
DEVFS_MODE_RW
Indicates a sub device can be opened for reading and writing
Definition at line 35 of file devfs.h.
 {
     DEVFS_MODE_EX = (1 << 0),
     DEVFS_MODE_W  = (1 << 1),
     DEVFS_MODE_R  = (1 << 2),
     DEVFS_MODE_RW = (DEVFS_MODE_R | DEVFS_MODE_W)
 };
Function Documentation
DevFSAddDevice()
HDEV DevFSAddDevice (const devfs_node_t * node)
Adds a new device to the filing system
Parameters
node Pointer to a devfs_node_t structure
Returns
A device handle is returned if the device was added. On error INVALID_HDEV is returned
Definition at line 1117 of file devfs.c.
 {
    devfs_device_t *dev = NULL;
    devfs_device_t *dev_scan;
    //printf("AddDevice node=%p\n", node);
    if(node == NULL)
    {
       M_PRINTF("AddDevice: node == NULL\n");
       return INVALID_HDEV;
    }
    if(!devfs_check_devname(node->name))
    {
       M_PRINTF("AddDevice: node name invalid\n");
       return INVALID_HDEV;
    }
    if(devfs_find_devicename(node->name))
    {
      M_PRINTF("AddDevice: cannot add new device. Already exists\n");
      return INVALID_HDEV;
    }
    dev = devfs_create_device(node);
    if(dev == NULL)
    {
       M_PRINTF("AddDevice: failed to allocate device structure\n");
       return INVALID_HDEV;
    }
    if(root_device == NULL)
    {
       root_device = dev;
    }
    else
    {
       dev_scan = root_device;
       while(dev_scan->forw) /* Scan the device linked list */
       {
          dev_scan = dev_scan->forw;
       }
       dev_scan->forw = dev;
       dev->back = dev_scan;
    }
    dev->hDev = dev_count++;
    if(dev_count == INVALID_HDEV) dev_count++;
    M_PRINTF("AddDevice: Registered device (%s)\n", node->name);
    return dev->hDev;
 }
References devfs_device_t::back, dev_count, devfs_check_devname(), devfs_create_device(), devfs_find_devicename(), devfs_device_t::forw, devfs_device_t::hDev, INVALID_HDEV, M_PRINTF, devfs_node_t::name, NULL, and root_device.
DevFSAddSubDevice()
int DevFSAddSubDevice (HDEV hDev, u32 subdev_no, s32 mode, devfs_loc_t extent, void * data)
Adds a sub device to a previously opened device
Parameters
hDev Handle to an opened device
subdev_no The number of the subdevice. Can be 0 to DEVFS_MAX_SUBDEVS
extent A 64bit extent which reflects the size of the underlying device
data Pointer to some private data to associate with this sub device
Returns
0 if sub device added, else -1
Definition at line 1221 of file devfs.c.
 {
    devfs_device_t *dev;
    //M_PRINTF("AddSubDevice hDev=%d subdev_no=%d data=%p\n", hDev, subdev_no, data);
    dev = devfs_find_deviceid(hDev);
    if(dev != NULL)
    {
       if(subdev_no >= DEVFS_MAX_SUBDEVS)
       {
          M_PRINTF("AddSubDevice: Sub device number too big\n");
          return -1;
       }
       if(dev->subdevs[subdev_no].valid)
       {
          M_PRINTF("AddSubDevice: Sub device already created\n");
          return -1;
       }
       dev->subdevs[subdev_no].data = data;
       dev->subdevs[subdev_no].valid = 1;
       dev->subdevs[subdev_no].mode = mode;
       dev->subdevs[subdev_no].open_refcount = 0;
       dev->subdevs[subdev_no].extent = extent;
       memset(dev->subdevs[subdev_no].open_files, 0, sizeof(ioman_data_t *) * MAX_OPENFILES);
       dev->subdev_count++;
    }
    else
    {
       M_PRINTF("AddSubDevice: Couldn't find device ID\n");
       return -1;
    }
    return 0;
 }
References subdev_t::data, devfs_find_deviceid(), DEVFS_MAX_SUBDEVS, subdev_t::extent, M_PRINTF, MAX_OPENFILES, memset(), subdev_t::mode, NULL, subdev_t::open_files, subdev_t::open_refcount, devfs_device_t::subdev_count, devfs_device_t::subdevs, and subdev_t::valid.
DevFSDelDevice()
int DevFSDelDevice (HDEV hDev)
Define to add DevFSAddDevice to the imports list Deletes an previously opened device.
Parameters
hDev Handle to the device to delete
Returns
0 if device deleted, -1 on error
Definition at line 1170 of file devfs.c.
 {
    devfs_device_t *dev;
    int ret = -1;
    devfs_device_t *forw, *back;
    //printf("DelDevice hDev=%d\n", hDev);
    dev = devfs_find_deviceid(hDev);
    if(dev)
    {
       int subdev_loop;
       int openfile_loop;
       forw = dev->forw;
       back = dev->back;
       /* Delete the device even if open files */
       for(subdev_loop = 0; subdev_loop < DEVFS_MAX_SUBDEVS; subdev_loop++)
       {
          for(openfile_loop = 0; openfile_loop < MAX_OPENFILES; openfile_loop++)
          {
             if(dev->subdevs[subdev_loop].open_files[openfile_loop])
             {
                dev->subdevs[subdev_loop].open_files[openfile_loop]->dev = NULL;
                /* Set the device reference to NULL */
             }
          }
       }
       devfs_delete_device(dev);
       if(back)
       {
          back->forw = forw;
       }
       else
       {
          root_device = NULL;
       }
       if(forw)
       {
          forw->back = back;
       }
       ret = 0;
    }
    return ret;
 }
References devfs_device_t::back, devfs_delete_device(), devfs_find_deviceid(), DEVFS_MAX_SUBDEVS, devfs_device_t::forw, MAX_OPENFILES, NULL, subdev_t::open_files, root_device, and devfs_device_t::subdevs.
DevFSDelSubDevice()
int DevFSDelSubDevice (HDEV hDev, u32 subdev_no)
Deletes a sub device.
Parameters
hDev Handle to an opened device.
subdev_no The number of the subdevice to delete.
Returns
0 if device deleted. -1 on error.
Definition at line 1259 of file devfs.c.
 {
    devfs_device_t *dev;
    int openfile_loop;
    //printf("DelSubDevice hDev=%d subdev_no=%d\n", hDev, subdev_no);
    dev = devfs_find_deviceid(hDev);
    if(dev != NULL)
    {
       if(subdev_no >= DEVFS_MAX_SUBDEVS)
       {
          M_PRINTF("DelSubDevice: Sub device number too big\n");
          return -1;
       }
       if(!dev->subdevs[subdev_no].valid)
       {
          M_PRINTF("DelSubDevice: Sub device not created\n");
          return -1;
       }
       dev->subdevs[subdev_no].data = NULL;
       dev->subdevs[subdev_no].valid = 0;
       dev->subdevs[subdev_no].mode = 0;
       dev->subdevs[subdev_no].open_refcount = 0;
       dev->subdevs[subdev_no].extent.loc64= 0;
       for(openfile_loop = 0; openfile_loop < MAX_OPENFILES; openfile_loop++)
       {
          if(dev->subdevs[subdev_no].open_files[openfile_loop])
          {
            dev->subdevs[subdev_no].open_files[openfile_loop]->dev = NULL;
            dev->subdevs[subdev_no].open_files[openfile_loop] = NULL;
          }
       }
       dev->subdev_count--;
    }
    return 0;
 }
References subdev_t::data, devfs_find_deviceid(), DEVFS_MAX_SUBDEVS, subdev_t::extent, devfs_loc_t::loc64, M_PRINTF, MAX_OPENFILES, subdev_t::mode, NULL, subdev_t::open_files, subdev_t::open_refcount, devfs_device_t::subdev_count, devfs_device_t::subdevs, and subdev_t::valid.