ps2sdk: iop/usb/usbd/src/hcd.h File Reference
hcd.h File Reference
#include "usbdpriv.h"
Functions
int callUsbDriverFunc (int(*func)(int), int devId, void *gp)
Endpoint * openDeviceEndpoint (Device *dev, UsbEndpointDescriptor *endpDesc, u32 alignFlag)
Endpoint * doOpenEndpoint (Device *dev, UsbEndpointDescriptor *endpDesc, u32 alignFlag)
void * doGetDeviceStaticDescriptor (int devId, void *data, u8 type)
int doCloseEndpoint (Endpoint *ep)
int hcdInit (void)
Detailed Description
USB Driver function prototypes and constants.
Definition in file hcd.h.
Function Documentation
callUsbDriverFunc()
int callUsbDriverFunc (int(*)(int) func, int devId, void * gp)
doCloseEndpoint()
int doCloseEndpoint (Endpoint * ep)
Definition at line 172 of file hcd.c.
{
         Device *dev = ep->correspDevice;
         if (dev->endpointListStart != ep)
                 return removeEndpointFromDevice(dev, ep);
         else
                 return 0;
 }
References Endpoint::correspDevice, Device::endpointListStart, and removeEndpointFromDevice().
Referenced by sceUsbdClosePipe().
doGetDeviceStaticDescriptor()
void* doGetDeviceStaticDescriptor (int devId, void * data, u8 type)
Definition at line 181 of file hcd.c.
{
         UsbDeviceDescriptor *descBuf;
         Device *dev = fetchDeviceById(devId);
         if (!dev)
                 return NULL;
         if (data)
                 descBuf = (UsbDeviceDescriptor *) ((u8 *)data + ((UsbDeviceDescriptor*)data)->bLength);
         else
                 descBuf = (UsbDeviceDescriptor *) dev->staticDeviceDescPtr;
         if (type == 0)
                 return descBuf;
         while (((u8*)descBuf < (u8*)dev->staticDeviceDescEndPtr) && (descBuf->bLength >= 2)) {
                 if (descBuf->bDescriptorType == type)
                         return descBuf;
                 descBuf = (UsbDeviceDescriptor *) ((u8 *)descBuf + descBuf->bLength);
         }
         return NULL;
 }
References UsbDeviceDescriptor::bDescriptorType, UsbDeviceDescriptor::bLength, fetchDeviceById(), NULL, Device::staticDeviceDescEndPtr, and Device::staticDeviceDescPtr.
Referenced by hubDrvConnect(), hubDrvProbe(), and sceUsbdScanStaticDescriptor().
doOpenEndpoint()
Endpoint* doOpenEndpoint (Device * dev, UsbEndpointDescriptor * endpDesc, u32 alignFlag)
Definition at line 162 of file hcd.c.
{
         if (!dev->parent)
                 return NULL;
         if (endpDesc == NULL)
                 return dev->endpointListStart; // default control EP was already opened
         else
                 return openDeviceEndpoint(dev, endpDesc, alignFlag);
 }
References Device::endpointListStart, NULL, openDeviceEndpoint(), and Device::parent.
Referenced by hubDrvConnect(), sceUsbdOpenPipe(), and sceUsbdOpenPipeAligned().
hcdInit()
int hcdInit (void)
Definition at line 485 of file hcd.c.
                   {
         int irqRes;
         iop_event_t event;
         iop_thread_t thread;
         dbg_printf("Threads and events...\n");
         event.attr = event.option = event.bits = 0;
         hcdIrqEvent = CreateEventFlag(&event);
         dbg_printf("Intr handler...\n");
         DisableIntr(IOP_IRQ_USB, &irqRes);
         if (RegisterIntrHandler(IOP_IRQ_USB, 1, usbdIntrHandler, (void *)hcdIrqEvent) != 0) {
                 if (irqRes == IOP_IRQ_USB)
                         EnableIntr(IOP_IRQ_USB);
                 return 1;
         }
         dbg_printf("HCD thread...\n");
         thread.attr = TH_C;
         thread.option = 0;
         thread.thread = hcdIrqThread;
         thread.stacksize = 0x4000;
         thread.priority = usbConfig.hcdThreadPrio;
         hcdTid = CreateThread(&thread);
         StartThread(hcdTid, (void *)hcdIrqEvent);
         dbg_printf("Callback thread...\n");
         initCallbackThread();
         dbg_printf("HCD init...\n");
         initHcdStructs();
         dbg_printf("Hub driver...\n");
         initHubDriver();
         dbg_printf("Enabling interrupts...\n");
         EnableIntr(IOP_IRQ_USB);
         return 0;
 }
References iop_thread_t::attr, CreateEventFlag(), CreateThread(), dbg_printf, DisableIntr(), EnableIntr(), hcdIrqEvent, hcdIrqThread(), UsbdConfig::hcdThreadPrio, hcdTid, initCallbackThread(), initHcdStructs(), initHubDriver(), IOP_IRQ_USB, iop_thread_t::option, iop_thread_t::priority, RegisterIntrHandler(), iop_thread_t::stacksize, StartThread(), TH_C, iop_thread_t::thread, usbConfig, and usbdIntrHandler().
Referenced by _start().
openDeviceEndpoint()
Endpoint* openDeviceEndpoint (Device * dev, UsbEndpointDescriptor * endpDesc, u32 alignFlag)
Definition at line 64 of file hcd.c.
{
         u16 flags = 0;
         u16 hcMaxPktSize;
         u8  endpType = 0;
         u8  type;
         HcTD   *td = NULL;
         Endpoint *newEp = allocEndpointForDevice(dev, alignFlag);
         if (!newEp) {
                 dbg_printf("ran out of endpoints\n");
                 return NULL;
         }
         if (endpDesc) {
                 type = endpDesc->bmAttributes & USB_ENDPOINT_XFERTYPE_MASK;
                 hcMaxPktSize = (endpDesc->wMaxPacketSizeHB << 8) | endpDesc->wMaxPacketSizeLB;
                 if (type == USB_ENDPOINT_XFER_ISOC) {
                         endpType = TYPE_ISOCHRON;
                         td = (HcTD *)allocIsoTd();
                         if (!td) {
                                 cleanUpFunc(dev, newEp);
                                 dbg_printf("Open ISOC EP: no TDs left\n");
                                 return NULL;
                         }
                 } else if (type == USB_ENDPOINT_XFER_CONTROL) {
                         endpType = TYPE_CONTROL;
                         if (!alignFlag)
                                 if (hcMaxPktSize >= 0x3F)
                                         hcMaxPktSize = 0x3E;
                 } else { // BULK or INT
                         if (type == USB_ENDPOINT_XFER_INT) {
                                 if (endpDesc->bInterval >= 0x20)
                                         endpType = 0x1F;
                                 else if (endpDesc->bInterval >= 0x10)
                                         endpType = 0xF;
                                 else if (endpDesc->bInterval >= 8)
                                         endpType = 7;
                                 else if (endpDesc->bInterval >= 4)
                                         endpType = 3;
                                 else if (endpDesc->bInterval >= 2)
                                         endpType = 1;
                                 else
                                         endpType = 0;
                                 // todo: add bandwidth scheduling
                                 dbg_printf("opening INT endpoint (%d - %p), interval %d, list %d\n", newEp->id, newEp, endpDesc->bInterval, endpType);
                         } else
                                 endpType = TYPE_BULK;
                         if (((endpDesc->bEndpointAddress & USB_DIR_IN) == 0) && !alignFlag)
                                 if (hcMaxPktSize >= 0x3F)
                                         hcMaxPktSize = 0x3E;
                 }
                 hcMaxPktSize &= 0x7FF;
                 if (type == USB_ENDPOINT_XFER_ISOC)
                         flags |= HCED_ISOC;
                 if (dev->isLowSpeedDevice)
                         flags |= HCED_SPEED;
                 flags |= (endpDesc->bEndpointAddress & 0xF) << 7;
                 if (endpDesc->bEndpointAddress & USB_DIR_IN)
                         flags |= HCED_DIR_IN;
                 else
                         flags |= HCED_DIR_OUT;
                 flags |= dev->functionAddress & 0x7F;
                 newEp->hcEd.hcArea = flags;
                 newEp->hcEd.maxPacketSize = hcMaxPktSize;
         } else {
                 newEp->hcEd.maxPacketSize = 8;
                 if (dev->isLowSpeedDevice)
                         newEp->hcEd.hcArea = HCED_SPEED;
                 else
                         newEp->hcEd.hcArea = 0;
                 endpType = TYPE_CONTROL;
         }
         newEp->endpointType = endpType;
         if (!td) {
                 td = allocTd();
                 if (!td) {
                         dbg_printf("Ran out of TDs\n");
                         cleanUpFunc(dev, newEp);
                         return NULL;
                 }
         }
         newEp->hcEd.tdHead = newEp->hcEd.tdTail = td;
         addToHcEndpointList(newEp->endpointType, &newEp->hcEd);
         return newEp;
 }
References addToHcEndpointList(), allocEndpointForDevice(), allocIsoTd(), allocTd(), UsbEndpointDescriptor::bEndpointAddress, UsbEndpointDescriptor::bInterval, UsbEndpointDescriptor::bmAttributes, cleanUpFunc(), dbg_printf, Endpoint::endpointType, Device::functionAddress, HcED::hcArea, Endpoint::hcEd, HCED_DIR_IN, HCED_DIR_OUT, HCED_ISOC, HCED_SPEED, Endpoint::id, Device::isLowSpeedDevice, HcED::maxPacketSize, NULL, td, HcED::tdHead, HcED::tdTail, TYPE_BULK, TYPE_CONTROL, TYPE_ISOCHRON, USB_DIR_IN, USB_ENDPOINT_XFER_CONTROL, USB_ENDPOINT_XFER_INT, USB_ENDPOINT_XFER_ISOC, USB_ENDPOINT_XFERTYPE_MASK, UsbEndpointDescriptor::wMaxPacketSizeHB, and UsbEndpointDescriptor::wMaxPacketSizeLB.
Referenced by doOpenEndpoint(), handleRhsc(), and hubGetPortStatusCallback().