ps2sdk: iop/usb/usbd/src/hcd.c File Reference
hcd.c File Reference
#include "usbdpriv.h"
#include "mem.h"
#include "usbio.h"
#include "hub.h"
#include "driver.h"
#include "stdio.h"
#include "sysclib.h"
#include "sysmem.h"
#include "thbase.h"
#include "thevent.h"
#include "thsemap.h"
#include "intrman.h"
Functions
int cleanUpFunc (Device *dev, Endpoint *ep)
Endpoint * openDeviceEndpoint (Device *dev, UsbEndpointDescriptor *endpDesc, u32 alignFlag)
Endpoint * doOpenEndpoint (Device *dev, UsbEndpointDescriptor *endpDesc, u32 alignFlag)
int doCloseEndpoint (Endpoint *ep)
void * doGetDeviceStaticDescriptor (int devId, void *data, u8 type)
void handleRhsc (void)
void hcdProcessIntr (void)
static void PostIntrEnableFunction (void)
void hcdIrqThread (void *arg)
int usbdIntrHandler (void *arg)
int initHardware (void)
int initHcdStructs (void)
int hcdInit (void)
Variables
int hcdIrqEvent
int hcdTid
Detailed Description
USB Driver function prototypes and constants.
Definition in file hcd.c.
Function Documentation
cleanUpFunc()
int cleanUpFunc (Device * dev, Endpoint * ep)
Definition at line 33 of file hcd.c.
{
         if (!ep)
                 return 0;
         if ((ep < memPool.endpointBuf) || (ep >= memPool.endpointBuf + usbConfig.maxEndpoints))
                 return 0;
         if (ep->inTdQueue)
                 removeEndpointFromQueue(ep);
         if (ep->next)
                 ep->next->prev = ep->prev;
         else
                 dev->endpointListEnd = ep->prev;
         if (ep->prev)
                 ep->prev->next = ep->next;
         else
                 dev->endpointListStart = ep->next;
         ep->correspDevice = NULL;
         ep->next = NULL;
         ep->prev = memPool.freeEpListEnd;
         if (memPool.freeEpListEnd)
                 memPool.freeEpListEnd->next = ep;
         else
                 memPool.freeEpListStart = ep;
         memPool.freeEpListEnd = ep;
         return 0;
 }
References Endpoint::correspDevice, MemoryPool::endpointBuf, Device::endpointListEnd, Device::endpointListStart, MemoryPool::freeEpListEnd, MemoryPool::freeEpListStart, Endpoint::inTdQueue, UsbdConfig::maxEndpoints, memPool, Endpoint::next, NULL, Endpoint::prev, removeEndpointFromQueue(), and usbConfig.
Referenced by openDeviceEndpoint().
doCloseEndpoint()
int doCloseEndpoint (Endpoint * ep)
Definition at line 172 of file hcd.c.
{
         Device *dev = ep->correspDevice;
         if (dev->endpointListStart != ep)
                 return removeEndpointFromDevice(dev, ep);
         else
                 return 0;
 }
References Endpoint::correspDevice, Device::endpointListStart, and removeEndpointFromDevice().
Referenced by sceUsbdClosePipe().
doGetDeviceStaticDescriptor()
void* doGetDeviceStaticDescriptor (int devId, void * data, u8 type)
Definition at line 181 of file hcd.c.
{
         UsbDeviceDescriptor *descBuf;
         Device *dev = fetchDeviceById(devId);
         if (!dev)
                 return NULL;
         if (data)
                 descBuf = (UsbDeviceDescriptor *) ((u8 *)data + ((UsbDeviceDescriptor*)data)->bLength);
         else
                 descBuf = (UsbDeviceDescriptor *) dev->staticDeviceDescPtr;
         if (type == 0)
                 return descBuf;
         while (((u8*)descBuf < (u8*)dev->staticDeviceDescEndPtr) && (descBuf->bLength >= 2)) {
                 if (descBuf->bDescriptorType == type)
                         return descBuf;
                 descBuf = (UsbDeviceDescriptor *) ((u8 *)descBuf + descBuf->bLength);
         }
         return NULL;
 }
References UsbDeviceDescriptor::bDescriptorType, UsbDeviceDescriptor::bLength, fetchDeviceById(), NULL, Device::staticDeviceDescEndPtr, and Device::staticDeviceDescPtr.
Referenced by hubDrvConnect(), hubDrvProbe(), and sceUsbdScanStaticDescriptor().
doOpenEndpoint()
Endpoint* doOpenEndpoint (Device * dev, UsbEndpointDescriptor * endpDesc, u32 alignFlag)
Definition at line 162 of file hcd.c.
{
         if (!dev->parent)
                 return NULL;
         if (endpDesc == NULL)
                 return dev->endpointListStart; // default control EP was already opened
         else
                 return openDeviceEndpoint(dev, endpDesc, alignFlag);
 }
References Device::endpointListStart, NULL, openDeviceEndpoint(), and Device::parent.
Referenced by hubDrvConnect(), sceUsbdOpenPipe(), and sceUsbdOpenPipeAligned().
handleRhsc()
void handleRhsc (void)
Definition at line 203 of file hcd.c.
                       {
         u32 portNum = 0;
         Device *port = memPool.deviceTreeRoot->childListStart;
         while (port) {
                 u32 status = memPool.ohciRegs->HcRhPortStatus[portNum];
                 memPool.ohciRegs->HcRhPortStatus[portNum] = C_PORT_FLAGS; // reset all flags
                 if (status & BIT(PORT_CONNECTION)) {
                         if ((port->deviceStatus != DEVICE_NOTCONNECTED) && (status & BIT(C_PORT_CONNECTION)))
                                 flushPort(port);
                         if (port->deviceStatus == DEVICE_NOTCONNECTED) {
                                 port->deviceStatus = DEVICE_CONNECTED;
                                 addTimerCallback(&port->timer, (TimerCallback)hubResetDevice, port, 500);
                         } else if (port->deviceStatus == DEVICE_RESETPENDING) {
                                 if (!(status & BIT(PORT_RESET))) {
                                         port->deviceStatus = DEVICE_RESETCOMPLETE;
                                         port->isLowSpeedDevice = (status >> PORT_LOW_SPEED) & 1;
                                         Endpoint *ep = openDeviceEndpoint(port, NULL, 0);
                                         if (ep)
                                                 hubTimedSetFuncAddress(port);
                                 }
                         }
                 } else
                         flushPort(port);
                 port = port->next;
                 portNum++;
         }
 }
References addTimerCallback(), BIT, C_PORT_CONNECTION, C_PORT_FLAGS, DEVICE_CONNECTED, DEVICE_NOTCONNECTED, DEVICE_RESETCOMPLETE, DEVICE_RESETPENDING, Device::deviceStatus, MemoryPool::deviceTreeRoot, flushPort(), OhciRegs::HcRhPortStatus, hubResetDevice(), hubTimedSetFuncAddress(), Device::isLowSpeedDevice, memPool, Device::next, NULL, MemoryPool::ohciRegs, openDeviceEndpoint(), PORT_CONNECTION, PORT_LOW_SPEED, PORT_RESET, status, and Device::timer.
Referenced by hcdProcessIntr().
hcdInit()
int hcdInit (void)
Definition at line 485 of file hcd.c.
                   {
         int irqRes;
         iop_event_t event;
         iop_thread_t thread;
         dbg_printf("Threads and events...\n");
         event.attr = event.option = event.bits = 0;
         hcdIrqEvent = CreateEventFlag(&event);
         dbg_printf("Intr handler...\n");
         DisableIntr(IOP_IRQ_USB, &irqRes);
         if (RegisterIntrHandler(IOP_IRQ_USB, 1, usbdIntrHandler, (void *)hcdIrqEvent) != 0) {
                 if (irqRes == IOP_IRQ_USB)
                         EnableIntr(IOP_IRQ_USB);
                 return 1;
         }
         dbg_printf("HCD thread...\n");
         thread.attr = TH_C;
         thread.option = 0;
         thread.thread = hcdIrqThread;
         thread.stacksize = 0x4000;
         thread.priority = usbConfig.hcdThreadPrio;
         hcdTid = CreateThread(&thread);
         StartThread(hcdTid, (void *)hcdIrqEvent);
         dbg_printf("Callback thread...\n");
         initCallbackThread();
         dbg_printf("HCD init...\n");
         initHcdStructs();
         dbg_printf("Hub driver...\n");
         initHubDriver();
         dbg_printf("Enabling interrupts...\n");
         EnableIntr(IOP_IRQ_USB);
         return 0;
 }
References iop_thread_t::attr, CreateEventFlag(), CreateThread(), dbg_printf, DisableIntr(), EnableIntr(), hcdIrqEvent, hcdIrqThread(), UsbdConfig::hcdThreadPrio, hcdTid, initCallbackThread(), initHcdStructs(), initHubDriver(), IOP_IRQ_USB, iop_thread_t::option, iop_thread_t::priority, RegisterIntrHandler(), iop_thread_t::stacksize, StartThread(), TH_C, iop_thread_t::thread, usbConfig, and usbdIntrHandler().
Referenced by _start().
hcdIrqThread()
void hcdIrqThread (void * arg)
Definition at line 303 of file hcd.c.
{
         u32 eventRes;
         while (1) {
                 WaitEventFlag(hcdIrqEvent, 1, WEF_CLEAR | WEF_OR, &eventRes);
                 usbdLock();
                 hcdProcessIntr();
                 EnableIntr(IOP_IRQ_USB);
                 PostIntrEnableFunction();
                 usbdUnlock();
         }
 }
References EnableIntr(), hcdIrqEvent, hcdProcessIntr(), IOP_IRQ_USB, PostIntrEnableFunction(), usbdLock(), usbdUnlock(), WaitEventFlag(), WEF_CLEAR, and WEF_OR.
Referenced by hcdInit().
hcdProcessIntr()
void hcdProcessIntr (void)
Definition at line 233 of file hcd.c.
{
         u32 intrFlags;
         intrFlags = memPool.ohciRegs->HcInterruptStatus & memPool.ohciRegs->HcInterruptEnable;
         if (intrFlags & OHCI_INT_SO) {
                 dbg_printf("HC: Scheduling overrun\n");
                 memPool.ohciRegs->HcInterruptStatus = OHCI_INT_SO;
                 intrFlags &= ~OHCI_INT_SO;
         }
         HcTD *doneQueue = (HcTD*)((u32)memPool.hcHCCA->DoneHead & ~0xF);
         if (doneQueue) {
                 memPool.hcHCCA->DoneHead = NULL;
                 memPool.ohciRegs->HcInterruptStatus = OHCI_INT_WDH;
                 // reverse queue
                 HcTD *prev = NULL;
                 do {
                         HcTD *tmp = doneQueue;
                         doneQueue = tmp->next;
                         tmp->next = prev;
                         prev = tmp;
                 } while (doneQueue);
                 do {
                         HcTD *tmp = prev->next;
                         if ((prev >= memPool.hcTdBuf) && (prev < memPool.hcTdBufEnd))
                                 processDoneQueue_GenTd(prev);
                         else if ((prev >= (HcTD *)memPool.hcIsoTdBuf) && (prev < (HcTD *)memPool.hcIsoTdBufEnd))
                                 processDoneQueue_IsoTd((HcIsoTD *)prev);
                         prev = tmp;
                 } while (prev);
                 intrFlags &= ~OHCI_INT_WDH;
         }
         if (intrFlags & OHCI_INT_SF) {
                 memPool.ohciRegs->HcInterruptStatus = OHCI_INT_SF;
                 handleTimerList();
                 intrFlags &= ~OHCI_INT_SF;
         }
         if (intrFlags & OHCI_INT_UE) {
                 printf("HC: Unrecoverable error\n");
                 memPool.ohciRegs->HcInterruptStatus = OHCI_INT_UE;
                 intrFlags &= ~OHCI_INT_UE;
         }
         if (intrFlags & OHCI_INT_RHSC) {
                 dbg_printf("RHSC\n");
                 memPool.ohciRegs->HcInterruptStatus = OHCI_INT_RHSC;
                 handleRhsc();
                 intrFlags &= ~OHCI_INT_RHSC;
         }
         intrFlags &= ~OHCI_INT_MIE;
         if (intrFlags) {
                 dbg_printf("Disable intr: %d\n", intrFlags);
                 memPool.ohciRegs->HcInterruptDisable = intrFlags;
         }
 }
References dbg_printf, HcCA::DoneHead, handleRhsc(), handleTimerList(), MemoryPool::hcHCCA, OhciRegs::HcInterruptDisable, OhciRegs::HcInterruptEnable, OhciRegs::HcInterruptStatus, MemoryPool::hcIsoTdBuf, MemoryPool::hcIsoTdBufEnd, MemoryPool::hcTdBuf, MemoryPool::hcTdBufEnd, memPool, HcTD::next, NULL, OHCI_INT_MIE, OHCI_INT_RHSC, OHCI_INT_SF, OHCI_INT_SO, OHCI_INT_UE, OHCI_INT_WDH, MemoryPool::ohciRegs, printf(), processDoneQueue_GenTd(), and processDoneQueue_IsoTd().
Referenced by hcdIrqThread().
initHardware()
int initHardware (void)
Definition at line 321 of file hcd.c.
{
         unsigned int i;
         dbg_printf("Host Controller...\n");
         memPool.ohciRegs->HcInterruptDisable = ~0;
         memPool.ohciRegs->HcCommandStatus = OHCI_COM_HCR;
         memPool.ohciRegs->HcControl = 0;
         for (i=0; memPool.ohciRegs->HcCommandStatus & OHCI_COM_HCR; i++) {
                 if(i==1000) return -1;
                 asm volatile("lw $zero, 0xffffffffbfc00000\n");
         }
         dbg_printf("HC reset done\n");
         *(volatile u32*)0xBF801570 |= 0x800 << 16;
         *(volatile u32*)0xBF801680 = 1;
         return 0;
 }
References dbg_printf, OhciRegs::HcCommandStatus, OhciRegs::HcControl, OhciRegs::HcInterruptDisable, memPool, OHCI_COM_HCR, and MemoryPool::ohciRegs.
Referenced by initHcdStructs().
initHcdStructs()
int initHcdStructs (void)
Definition at line 341 of file hcd.c.
{
         int             i;
         HcCA    *hcCommArea;
         memPool.ohciRegs = (volatile OhciRegs*)OHCI_REG_BASE;
         initHardware();
         dbg_printf("Structs...\n");
         memPool.hcHCCA = NULL;
         memPool.hcIsoTdBuf                      = (HcIsoTD *)   ((u8*)memPool.hcHCCA + sizeof(HcCA));
         memPool.hcIsoTdBufEnd           =                                memPool.hcIsoTdBuf + usbConfig.maxIsoTransfDesc;
         memPool.hcTdBuf                         = (HcTD *)               memPool.hcIsoTdBufEnd;
         memPool.hcTdBufEnd                      =                                memPool.hcTdBuf + usbConfig.maxTransfDesc;
         memPool.hcEdBuf                         = (HcED *)               memPool.hcTdBufEnd;
         memPool.endpointBuf                     = (Endpoint *)  (memPool.hcEdBuf + 0x42);
         memPool.deviceTreeBuf           = (Device *)    (memPool.endpointBuf + usbConfig.maxEndpoints);
         memPool.ioReqBufPtr                     = (IoRequest *) (memPool.deviceTreeBuf + usbConfig.maxDevices);
         memPool.hcIsoTdToIoReqLUT       = (IoRequest **)(memPool.ioReqBufPtr + usbConfig.maxIoReqs);
         memPool.hcTdToIoReqLUT          = (IoRequest **)(memPool.hcIsoTdToIoReqLUT + usbConfig.maxIsoTransfDesc);
         u8 *devDescBuf                  = (u8*)         (memPool.hcTdToIoReqLUT + usbConfig.maxTransfDesc);
         u32 memSize = ((u32)devDescBuf) + usbConfig.maxDevices * usbConfig.maxStaticDescSize;
         u8 *memBuf      = AllocSysMemory(ALLOC_FIRST, memSize, 0);
         memset(memBuf, 0, memSize);
         hcCommArea                                      = (HcCA *)              memBuf;
         memPool.hcHCCA                          = (HcCA *)              ((((u32)memBuf + (u32)memPool.hcHCCA) & 0x1FFFFFFF) | 0xA0000000);
         memPool.hcIsoTdBuf                      = (HcIsoTD *)   ((u32)memBuf + (u32)memPool.hcIsoTdBuf);
         memPool.hcIsoTdBufEnd           = (HcIsoTD *)   ((u32)memBuf + (u32)memPool.hcIsoTdBufEnd);
         memPool.hcTdBuf                         = (HcTD *)              ((u32)memBuf + (u32)memPool.hcTdBuf);
         memPool.hcTdBufEnd                      = (HcTD *)              ((u32)memBuf + (u32)memPool.hcTdBufEnd);
         memPool.hcEdBuf                         = (HcED *)              ((u32)memBuf + (u32)memPool.hcEdBuf);
         memPool.endpointBuf                     = (Endpoint *)  ((u32)memBuf + (u32)memPool.endpointBuf);
         memPool.deviceTreeBuf           = (Device *)    ((u32)memBuf + (u32)memPool.deviceTreeBuf);
         memPool.ioReqBufPtr                     = (IoRequest *) ((u32)memBuf + (u32)memPool.ioReqBufPtr);
         memPool.hcIsoTdToIoReqLUT       = (IoRequest **)((u32)memBuf + (u32)memPool.hcIsoTdToIoReqLUT);
         memPool.hcTdToIoReqLUT          = (IoRequest **)((u32)memBuf + (u32)memPool.hcTdToIoReqLUT);
         devDescBuf                                      = (u8 *)                ((u32)memBuf + (u32)devDescBuf);
         Endpoint *ep = memPool.endpointBuf;
         for (i = 0; i < usbConfig.maxEndpoints; i++) {
                 ep->id = i;
                 ep->next = NULL;
                 ep->prev = memPool.freeEpListEnd;
                 if (memPool.freeEpListEnd)
                         memPool.freeEpListEnd->next = ep;
                 else
                         memPool.freeEpListStart = ep;
                 memPool.freeEpListEnd = ep;
                 ep++;
         }
         memPool.tdQueueStart[0] = memPool.tdQueueStart[1] = NULL;
         memPool.tdQueueEnd[0] = memPool.tdQueueEnd[1] = NULL;
         Device *dev = memPool.deviceTreeBuf;
         for (i = 0; i < usbConfig.maxDevices; i++) {
                 dev->functionAddress = i;
                 dev->id = i & 0xFF;
                 dev->next = NULL;
                 dev->prev = memPool.freeDeviceListEnd;
                 if (memPool.freeDeviceListEnd)
                         memPool.freeDeviceListEnd->next = dev;
                 else
                         memPool.freeDeviceListStart = dev;
                 memPool.freeDeviceListEnd = dev;
                 dev->staticDeviceDescPtr = devDescBuf;
                 dev++;
                 devDescBuf += usbConfig.maxStaticDescSize;
         }
         memPool.deviceTreeRoot = attachChildDevice(NULL, 0); // virtual root
         attachChildDevice(memPool.deviceTreeRoot, 1); // root hub port 0
         attachChildDevice(memPool.deviceTreeRoot, 2); // root hub port 1
         IoRequest *req = memPool.ioReqBufPtr;
         for (i = 0; i < usbConfig.maxIoReqs; i++) {
                 req->next = NULL;
                 req->prev = memPool.freeIoReqListEnd;
                 if (memPool.freeIoReqListEnd)
                         memPool.freeIoReqListEnd->next = req;
                 else
                         memPool.freeIoReqList = req;
                 memPool.freeIoReqListEnd = req;
                 req++;
         }
         HcTD *hcTd = memPool.freeHcTdList = memPool.hcTdBuf;
         for (i = 0; i < usbConfig.maxTransfDesc - 1; i++) {
                 hcTd->next = hcTd + 1;
                 hcTd++;
         }
         hcTd->next = NULL;
         HcIsoTD *isoTd = memPool.freeHcIsoTdList = memPool.hcIsoTdBuf;
         for (i = 0; i < usbConfig.maxIsoTransfDesc - 1; i++) {
                 isoTd->next = isoTd + 1;
                 isoTd++;
         }
         isoTd->next = NULL;
         // build tree for interrupt table
         HcED *ed = memPool.hcEdBuf;
         for (i = 0; i < 0x3F; i++) {
                 ed->hcArea = HCED_SKIP;
                 if (i == 0)
                         ed->next = NULL;
                 else
                         ed->next = memPool.hcEdBuf + ((i - 1) >> 1);
                 int intrId = i - 31;
                 if (intrId >= 0) {
                         intrId = ((intrId & 1) << 4) | ((intrId & 2) << 2) | (intrId & 4) | ((intrId & 8) >> 2) | ((intrId & 0x10) >> 4);
                         hcCommArea->InterruptTable[intrId] = ed;
                 }
                 ed++;
         }
         ed->hcArea = HCED_SKIP;
         memPool.ohciRegs->HcControlHeadEd = ed;
         ed++;
         ed->hcArea = HCED_SKIP;
         memPool.ohciRegs->HcBulkHeadEd = ed;
         ed++;
         ed->hcArea = HCED_SKIP;
         memPool.hcEdBuf->next = ed; // the isochronous endpoint
         memPool.ohciRegs->HcHCCA = hcCommArea;
         memPool.ohciRegs->HcFmInterval = 0x27782EDF;
     memPool.ohciRegs->HcPeriodicStart = 0x2A2F;
     memPool.ohciRegs->HcInterruptEnable = OHCI_INT_MIE | OHCI_INT_RHSC | OHCI_INT_UE | OHCI_INT_WDH | OHCI_INT_SO;
     memPool.ohciRegs->HcControl = OHCI_CTR_USB_OPERATIONAL | OHCI_CTR_PLE | OHCI_CTR_IE | OHCI_CTR_CLE | OHCI_CTR_BLE | 3;
     return 0;
 }
References ALLOC_FIRST, AllocSysMemory(), attachChildDevice(), dbg_printf, MemoryPool::deviceTreeBuf, MemoryPool::deviceTreeRoot, MemoryPool::endpointBuf, MemoryPool::freeDeviceListEnd, MemoryPool::freeDeviceListStart, MemoryPool::freeEpListEnd, MemoryPool::freeEpListStart, MemoryPool::freeHcIsoTdList, MemoryPool::freeHcTdList, MemoryPool::freeIoReqList, MemoryPool::freeIoReqListEnd, Device::functionAddress, HcED::hcArea, OhciRegs::HcBulkHeadEd, OhciRegs::HcControl, OhciRegs::HcControlHeadEd, HCED_SKIP, MemoryPool::hcEdBuf, OhciRegs::HcFmInterval, OhciRegs::HcHCCA, MemoryPool::hcHCCA, OhciRegs::HcInterruptEnable, MemoryPool::hcIsoTdBuf, MemoryPool::hcIsoTdBufEnd, MemoryPool::hcIsoTdToIoReqLUT, OhciRegs::HcPeriodicStart, MemoryPool::hcTdBuf, MemoryPool::hcTdBufEnd, MemoryPool::hcTdToIoReqLUT, Device::id, Endpoint::id, initHardware(), HcCA::InterruptTable, MemoryPool::ioReqBufPtr, UsbdConfig::maxDevices, UsbdConfig::maxEndpoints, UsbdConfig::maxIoReqs, UsbdConfig::maxIsoTransfDesc, UsbdConfig::maxStaticDescSize, UsbdConfig::maxTransfDesc, memPool, memset(), IoRequest::next, Device::next, HcTD::next, HcIsoTD::next, HcED::next, Endpoint::next, NULL, OHCI_CTR_BLE, OHCI_CTR_CLE, OHCI_CTR_IE, OHCI_CTR_PLE, OHCI_CTR_USB_OPERATIONAL, OHCI_INT_MIE, OHCI_INT_RHSC, OHCI_INT_SO, OHCI_INT_UE, OHCI_INT_WDH, OHCI_REG_BASE, MemoryPool::ohciRegs, IoRequest::prev, Device::prev, Endpoint::prev, Device::staticDeviceDescPtr, MemoryPool::tdQueueEnd, MemoryPool::tdQueueStart, and usbConfig.
Referenced by hcdInit().
openDeviceEndpoint()
Endpoint* openDeviceEndpoint (Device * dev, UsbEndpointDescriptor * endpDesc, u32 alignFlag)
Definition at line 64 of file hcd.c.
{
         u16 flags = 0;
         u16 hcMaxPktSize;
         u8  endpType = 0;
         u8  type;
         HcTD   *td = NULL;
         Endpoint *newEp = allocEndpointForDevice(dev, alignFlag);
         if (!newEp) {
                 dbg_printf("ran out of endpoints\n");
                 return NULL;
         }
         if (endpDesc) {
                 type = endpDesc->bmAttributes & USB_ENDPOINT_XFERTYPE_MASK;
                 hcMaxPktSize = (endpDesc->wMaxPacketSizeHB << 8) | endpDesc->wMaxPacketSizeLB;
                 if (type == USB_ENDPOINT_XFER_ISOC) {
                         endpType = TYPE_ISOCHRON;
                         td = (HcTD *)allocIsoTd();
                         if (!td) {
                                 cleanUpFunc(dev, newEp);
                                 dbg_printf("Open ISOC EP: no TDs left\n");
                                 return NULL;
                         }
                 } else if (type == USB_ENDPOINT_XFER_CONTROL) {
                         endpType = TYPE_CONTROL;
                         if (!alignFlag)
                                 if (hcMaxPktSize >= 0x3F)
                                         hcMaxPktSize = 0x3E;
                 } else { // BULK or INT
                         if (type == USB_ENDPOINT_XFER_INT) {
                                 if (endpDesc->bInterval >= 0x20)
                                         endpType = 0x1F;
                                 else if (endpDesc->bInterval >= 0x10)
                                         endpType = 0xF;
                                 else if (endpDesc->bInterval >= 8)
                                         endpType = 7;
                                 else if (endpDesc->bInterval >= 4)
                                         endpType = 3;
                                 else if (endpDesc->bInterval >= 2)
                                         endpType = 1;
                                 else
                                         endpType = 0;
                                 // todo: add bandwidth scheduling
                                 dbg_printf("opening INT endpoint (%d - %p), interval %d, list %d\n", newEp->id, newEp, endpDesc->bInterval, endpType);
                         } else
                                 endpType = TYPE_BULK;
                         if (((endpDesc->bEndpointAddress & USB_DIR_IN) == 0) && !alignFlag)
                                 if (hcMaxPktSize >= 0x3F)
                                         hcMaxPktSize = 0x3E;
                 }
                 hcMaxPktSize &= 0x7FF;
                 if (type == USB_ENDPOINT_XFER_ISOC)
                         flags |= HCED_ISOC;
                 if (dev->isLowSpeedDevice)
                         flags |= HCED_SPEED;
                 flags |= (endpDesc->bEndpointAddress & 0xF) << 7;
                 if (endpDesc->bEndpointAddress & USB_DIR_IN)
                         flags |= HCED_DIR_IN;
                 else
                         flags |= HCED_DIR_OUT;
                 flags |= dev->functionAddress & 0x7F;
                 newEp->hcEd.hcArea = flags;
                 newEp->hcEd.maxPacketSize = hcMaxPktSize;
         } else {
                 newEp->hcEd.maxPacketSize = 8;
                 if (dev->isLowSpeedDevice)
                         newEp->hcEd.hcArea = HCED_SPEED;
                 else
                         newEp->hcEd.hcArea = 0;
                 endpType = TYPE_CONTROL;
         }
         newEp->endpointType = endpType;
         if (!td) {
                 td = allocTd();
                 if (!td) {
                         dbg_printf("Ran out of TDs\n");
                         cleanUpFunc(dev, newEp);
                         return NULL;
                 }
         }
         newEp->hcEd.tdHead = newEp->hcEd.tdTail = td;
         addToHcEndpointList(newEp->endpointType, &newEp->hcEd);
         return newEp;
 }
References addToHcEndpointList(), allocEndpointForDevice(), allocIsoTd(), allocTd(), UsbEndpointDescriptor::bEndpointAddress, UsbEndpointDescriptor::bInterval, UsbEndpointDescriptor::bmAttributes, cleanUpFunc(), dbg_printf, Endpoint::endpointType, Device::functionAddress, HcED::hcArea, Endpoint::hcEd, HCED_DIR_IN, HCED_DIR_OUT, HCED_ISOC, HCED_SPEED, Endpoint::id, Device::isLowSpeedDevice, HcED::maxPacketSize, NULL, td, HcED::tdHead, HcED::tdTail, TYPE_BULK, TYPE_CONTROL, TYPE_ISOCHRON, USB_DIR_IN, USB_ENDPOINT_XFER_CONTROL, USB_ENDPOINT_XFER_INT, USB_ENDPOINT_XFER_ISOC, USB_ENDPOINT_XFERTYPE_MASK, UsbEndpointDescriptor::wMaxPacketSizeHB, and UsbEndpointDescriptor::wMaxPacketSizeLB.
Referenced by doOpenEndpoint(), handleRhsc(), and hubGetPortStatusCallback().
PostIntrEnableFunction()
static void PostIntrEnableFunction (void) static
Definition at line 296 of file hcd.c.
 {
         memPool.ohciRegs->HcInterruptDisable = OHCI_INT_MIE;
         asm volatile("lw $zero, 0xffffffffbfc00000\n");
         memPool.ohciRegs->HcInterruptEnable = OHCI_INT_MIE;
 }
References OhciRegs::HcInterruptDisable, OhciRegs::HcInterruptEnable, memPool, OHCI_INT_MIE, and MemoryPool::ohciRegs.
Referenced by hcdIrqThread().
usbdIntrHandler()
int usbdIntrHandler (void * arg)
Definition at line 316 of file hcd.c.
{
         iSetEventFlag((int)arg, 1);
         return 0;
 }
References arg, and iSetEventFlag().
Referenced by hcdInit().
Variable Documentation
hcdIrqEvent
int hcdIrqEvent
Definition at line 30 of file hcd.c.
Referenced by hcdInit(), and hcdIrqThread().
hcdTid
int hcdTid
Definition at line 31 of file hcd.c.
Referenced by hcdInit(), and sceUsbdChangeThreadPriority().