ps2sdk: iop/hdd/apa/src/hdd.c File Reference
hdd.c File Reference
#include <stdio.h>
#include <sysclib.h>
#include <loadcore.h>
#include <atad.h>
#include <dev9.h>
#include <errno.h>
#include <irx.h>
#include <iomanX.h>
#include <hdd-ioctl.h>
#include "apa-opt.h"
#include <libapa.h>
#include "hdd.h"
#include "hdd_fio.h"
Functions
IRX_ID ("hdd_driver", APA_MODVER_MAJOR, APA_MODVER_MINOR)
static int inputError (char *input)
static int unlockDrive (s32 device)
static void hddShutdownCb (void)
static int hddInitError (void)
int hddCheckPartitionMax (s32 device, u32 size)
apa_cache_t * hddAddPartitionHere (s32 device, const apa_params_t *params, u32 *emptyBlocks, u32 sector, int *err)
static void printStartup (void)
int _start (int argc, char **argv)
Variables
static iop_device_ops_t hddOps
static iop_device_t hddFioDev
apa_device_t hddDevices [2]
int apaMaxOpen
hdd_file_slot_t * hddFileSlots
Function Documentation
hddAddPartitionHere()
apa_cache_t* hddAddPartitionHere (s32 device, const apa_params_t * params, u32 * emptyBlocks, u32 sector, int * err)
Definition at line 92 of file hdd.c.
 {
         apa_cache_t     *clink_this;
         apa_cache_t     *clink_next;
         apa_cache_t     *clink_new;
         apa_header_t    *header;
         u32                     i;
         u32                     tmp, some_size, part_end;
         u32                     tempSize;
         // walk empty blocks in case can use one :)
         for(i=0;i< 32;i++)
         {
                 if((u32)(1 << i) >= params->size && emptyBlocks[i]!=0)
                         return apaInsertPartition(device, params, emptyBlocks[i], err);
         }
         clink_this=apaCacheGetHeader(device, sector, APA_IO_MODE_READ, err);
         header=clink_this->header;
         part_end=header->start+header->length;
         some_size=(part_end%params->size);
         tmp = some_size ? params->size - some_size : 0;
         if(hddDevices[device].totalLBA < (part_end + params->size + tmp)
                 //Non-SONY: when dealing with large disks, this check may overflow (therefore, check for overflows!).
                 || (part_end < sector))
         {
                 *err=-ENOSPC;
                 apaCacheFree(clink_this);
                 return NULL;
         }
         if((clink_next=apaCacheGetHeader(device, 0, APA_IO_MODE_READ, err))==NULL)
         {
                 apaCacheFree(clink_this);
                 return NULL;
         }
         tempSize=params->size;
         while(part_end%params->size)
         {
                 tempSize=params->size>>1;
                 while(0x3FFFF<tempSize)
                 {
                         if(!(part_end%tempSize))
{
                                 clink_new=apaRemovePartition(device, part_end, 0,
                                         clink_this->header->start, tempSize);
                                 clink_this->header->next=part_end;
                                 clink_this->flags|=APA_CACHE_FLAG_DIRTY;
                                 clink_next->header->prev=clink_new->header->start;
                                 part_end+=tempSize;
                                 clink_next->flags|=APA_CACHE_FLAG_DIRTY;
                                 apaCacheFlushAllDirty(device);
                                 apaCacheFree(clink_this);
                                 clink_this=clink_new;
                                 break;
                         }
                         tempSize>>=1;
                 }
         }
         if((clink_new=apaFillHeader(device, params, part_end, 0, clink_this->header->start,
                 params->size, err))!=NULL)
         {
                 clink_this->header->next=part_end;
                 clink_this->flags|=APA_CACHE_FLAG_DIRTY;
                 clink_next->header->prev=clink_new->header->start;
                 clink_next->flags|=APA_CACHE_FLAG_DIRTY;
                 apaCacheFlushAllDirty(device);
         }
         apaCacheFree(clink_this);
         apaCacheFree(clink_next);
         return clink_new;
 }
References APA_CACHE_FLAG_DIRTY, APA_IO_MODE_READ, apaCacheFlushAllDirty(), apaCacheFree(), apaCacheGetHeader(), apaFillHeader(), apaInsertPartition(), apaRemovePartition(), ENOSPC, apa_cache_t::flags, hddDevices, apa_cache_t::header, apa_header_t::length, apa_header_t::next, NULL, apa_header_t::prev, apa_params_t::size, and apa_header_t::start.
Referenced by apaOpen(), hddFormat(), and ioctl2AddSub().
hddCheckPartitionMax()
int hddCheckPartitionMax (s32 device, u32 size)
Definition at line 87 of file hdd.c.
 {
         return (hddDevices[device].partitionMaxSize >= size) ? 0 : -EINVAL;
 }
References EINVAL, and hddDevices.
Referenced by apaOpen(), and ioctl2AddSub().
hddInitError()
static int hddInitError (void) static
Definition at line 321 of file hdd.c.
 {
         dev9RegisterShutdownCb(0, NULL);
         return MODULE_NO_RESIDENT_END;
 }
References dev9RegisterShutdownCb(), MODULE_NO_RESIDENT_END, and NULL.
Referenced by _start().
hddShutdownCb()
static void hddShutdownCb (void) static
Definition at line 310 of file hdd.c.
 {
         int i;
         for(i = 0; i < 2; i++)
         {
                 if(hddDevices[i].status == 0)
                         ata_device_smart_save_attr(i);
         }
 }
References ata_device_smart_save_attr(), hddDevices, and status.
Referenced by _start().
inputError()
static int inputError (char * input) static
Definition at line 167 of file hdd.c.
 {
         APA_PRINTF(APA_DRV_NAME": Error: Usage: %s [-o <apaMaxOpen>] [-n <maxcache>]\n", input);
         return MODULE_NO_RESIDENT_END;
 }
References APA_DRV_NAME, APA_PRINTF, and MODULE_NO_RESIDENT_END.
Referenced by _start().
IRX_ID()
IRX_ID ("hdd_driver" , APA_MODVER_MAJOR , APA_MODVER_MINOR)
printStartup()
static void printStartup (void) static
Definition at line 173 of file hdd.c.
 {
         APA_PRINTF(APA_DRV_NAME": PS2 APA Driver v%d.%d (c) 2003 Vector\n", APA_MODVER_MAJOR, APA_MODVER_MINOR);
         return;
 }
References APA_DRV_NAME, APA_MODVER_MAJOR, APA_MODVER_MINOR, and APA_PRINTF.
Referenced by _start().
unlockDrive()
static int unlockDrive (s32 device) static
Definition at line 179 of file hdd.c.
 {
         u8 id[32];
         int rv;
         if((rv=apaGetIlinkID(id))==0)
                 return ata_device_sce_sec_unlock(device, id);
         return rv;
 }
References apaGetIlinkID(), and ata_device_sce_sec_unlock().
Referenced by _start().
Variable Documentation
apaMaxOpen
int apaMaxOpen extern
Definition at line 35 of file hdd_fio.c.
Referenced by _start(), apaRemove(), apaRename(), and getFileSlot().
hddDevices
apa_device_t hddDevices[2]
Initial value:
={
        {0, 0, 0, 3},
        {0, 0, 0, 3}
}
Definition at line 74 of file hdd.c.
Referenced by _start(), hddAddPartitionHere(), hddCheckPartitionMax(), hddDevctl(), hddFormat(), hddOpen(), and hddShutdownCb().
hddFileSlots
hdd_file_slot_t* hddFileSlots extern
Definition at line 33 of file hdd_fio.c.
Referenced by _start(), apaRemove(), apaRename(), and getFileSlot().
hddFioDev
iop_device_t hddFioDev static
Initial value:
={
        "hdd",
        IOP_DT_BLOCK | IOP_DT_FSEXT,
        1,
        "HDD",
        (struct _iop_device_ops *)&hddOps,
}
Definition at line 66 of file hdd.c.
Referenced by _start().
hddOps
iop_device_ops_t hddOps static
Initial value:
={
        hddInit,
        hddDeinit,
        hddFormat,
        hddOpen,
        hddClose,
        hddRead,
        hddWrite,
        hddLseek,
        (void*)hddUnsupported,
        hddRemove,
        (void*)hddUnsupported,
        (void*)hddUnsupported,
        hddDopen,
        hddClose,
        hddDread,
        hddGetStat,
        (void*)hddUnsupported,
        hddReName,
        (void*)hddUnsupported,
        (void*)hddUnsupported,
        (void*)hddUnsupported,
        (void*)hddUnsupported,
        (void*)hddUnsupported,
        hddDevctl,
        (void*)hddUnsupported,
        (void*)hddUnsupported,
        hddIoctl2,
}
Definition at line 37 of file hdd.c.