ps2sdk: iop/hdd/apa/src/hdd.h File Reference
hdd.h File Reference
Data Structures
struct hdd_file_slot_t
Functions
int hddCheckPartitionMax (s32 device, u32 size)
apa_cache_t * hddAddPartitionHere (s32 device, const apa_params_t *params, u32 *EmptyBlocks, u32 sector, int *err)
Function Documentation
hddAddPartitionHere()
apa_cache_t* hddAddPartitionHere (s32 device, const apa_params_t * params, u32 * EmptyBlocks, u32 sector, int * err)
Definition at line 92 of file hdd.c.
 {
         apa_cache_t     *clink_this;
         apa_cache_t     *clink_next;
         apa_cache_t     *clink_new;
         apa_header_t    *header;
         u32                     i;
         u32                     tmp, some_size, part_end;
         u32                     tempSize;
         // walk empty blocks in case can use one :)
         for(i=0;i< 32;i++)
         {
                 if((u32)(1 << i) >= params->size && emptyBlocks[i]!=0)
                         return apaInsertPartition(device, params, emptyBlocks[i], err);
         }
         clink_this=apaCacheGetHeader(device, sector, APA_IO_MODE_READ, err);
         header=clink_this->header;
         part_end=header->start+header->length;
         some_size=(part_end%params->size);
         tmp = some_size ? params->size - some_size : 0;
         if(hddDevices[device].totalLBA < (part_end + params->size + tmp)
                 //Non-SONY: when dealing with large disks, this check may overflow (therefore, check for overflows!).
                 || (part_end < sector))
         {
                 *err=-ENOSPC;
                 apaCacheFree(clink_this);
                 return NULL;
         }
         if((clink_next=apaCacheGetHeader(device, 0, APA_IO_MODE_READ, err))==NULL)
         {
                 apaCacheFree(clink_this);
                 return NULL;
         }
         tempSize=params->size;
         while(part_end%params->size)
         {
                 tempSize=params->size>>1;
                 while(0x3FFFF<tempSize)
                 {
                         if(!(part_end%tempSize))
{
                                 clink_new=apaRemovePartition(device, part_end, 0,
                                         clink_this->header->start, tempSize);
                                 clink_this->header->next=part_end;
                                 clink_this->flags|=APA_CACHE_FLAG_DIRTY;
                                 clink_next->header->prev=clink_new->header->start;
                                 part_end+=tempSize;
                                 clink_next->flags|=APA_CACHE_FLAG_DIRTY;
                                 apaCacheFlushAllDirty(device);
                                 apaCacheFree(clink_this);
                                 clink_this=clink_new;
                                 break;
                         }
                         tempSize>>=1;
                 }
         }
         if((clink_new=apaFillHeader(device, params, part_end, 0, clink_this->header->start,
                 params->size, err))!=NULL)
         {
                 clink_this->header->next=part_end;
                 clink_this->flags|=APA_CACHE_FLAG_DIRTY;
                 clink_next->header->prev=clink_new->header->start;
                 clink_next->flags|=APA_CACHE_FLAG_DIRTY;
                 apaCacheFlushAllDirty(device);
         }
         apaCacheFree(clink_this);
         apaCacheFree(clink_next);
         return clink_new;
 }
References APA_CACHE_FLAG_DIRTY, APA_IO_MODE_READ, apaCacheFlushAllDirty(), apaCacheFree(), apaCacheGetHeader(), apaFillHeader(), apaInsertPartition(), apaRemovePartition(), ENOSPC, apa_cache_t::flags, hddDevices, apa_cache_t::header, apa_header_t::length, apa_header_t::next, NULL, apa_header_t::prev, apa_params_t::size, and apa_header_t::start.
Referenced by apaOpen(), hddFormat(), and ioctl2AddSub().
hddCheckPartitionMax()
int hddCheckPartitionMax (s32 device, u32 size)
Definition at line 87 of file hdd.c.
 {
         return (hddDevices[device].partitionMaxSize >= size) ? 0 : -EINVAL;
 }
References EINVAL, and hddDevices.
Referenced by apaOpen(), and ioctl2AddSub().