ps2sdk: iop/hdd/apa/src/hdd_fio.h File Reference
hdd_fio.h File Reference
Functions
int hddInit (iop_device_t *f)
int hddDeinit (iop_device_t *f)
int hddFormat (iop_file_t *f, const char *dev, const char *blockdev, void *arg, int arglen)
int hddOpen (iop_file_t *f, const char *name, int flags, int mode)
int hddClose (iop_file_t *f)
int hddRead (iop_file_t *f, void *buf, int size)
int hddWrite (iop_file_t *f, void *buf, int size)
int hddLseek (iop_file_t *f, int post, int whence)
int hddIoctl2 (iop_file_t *f, int request, void *argp, unsigned int arglen, void *bufp, unsigned intbuflen)
int hddRemove (iop_file_t *f, const char *name)
int hddDopen (iop_file_t *f, const char *name)
int hddDread (iop_file_t *f, iox_dirent_t *dirent)
int hddGetStat (iop_file_t *f, const char *name, iox_stat_t *stat)
int hddReName (iop_file_t *f, const char *oldname, const char *newname)
int hddDevctl (iop_file_t *f, const char *devname, int cmd, void *arg, unsigned int arglen, void *bufp, unsigned int buflen)
int hddUnsupported (iop_file_t *f)
Function Documentation
hddClose()
int hddClose (iop_file_t * f)
Definition at line 553 of file hdd_fio.c.
 {
         WaitSema(fioSema);
         memset(f->privdata, 0, sizeof(hdd_file_slot_t));
         SignalSema(fioSema);
         return 0;
 }
References fioSema, memset(), iop_file_t::privdata, SignalSema(), and WaitSema().
hddDeinit()
int hddDeinit (iop_device_t * f)
Definition at line 256 of file hdd_fio.c.
 {
         DeleteSema(fioSema);
         return 0;
 }
References DeleteSema(), and fioSema.
hddDevctl()
int hddDevctl (iop_file_t * f, const char * devname, int cmd, void * arg, unsigned int arglen, void * bufp, unsigned int buflen)
Definition at line 935 of file hdd_fio.c.
 {
         int     rv=0;
         WaitSema(fioSema);
         switch(cmd)
         {
         // Command set 1 ('H')
         case HDIOC_DEV9OFF:
                 //Early versions called ata_device_smart_save_attr() here, when their old dev9 versions did not support the pre-shutdown callback.
                 dev9Shutdown();
                 break;
         case HDIOC_IDLE:
                 rv=ata_device_idle(f->unit, *(char *)arg);
                 break;
         case HDIOC_MAXSECTOR:
                 rv=hddDevices[f->unit].partitionMaxSize;
                 break;
         case HDIOC_TOTALSECTOR:
                 rv=hddDevices[f->unit].totalLBA;
                 break;
         case HDIOC_FLUSH:
                 if(ata_device_flush_cache(f->unit))
                         rv=-EIO;
                 break;
         case HDIOC_SWAPTMP:
                 rv=devctlSwapTemp(f->unit, (char *)arg);
                 break;
         case HDIOC_SMARTSTAT:
                 rv=ata_device_smart_get_status(f->unit);
                 break;
         case HDIOC_STATUS:
                 rv=hddDevices[f->unit].status;
                 break;
         case HDIOC_FORMATVER:
                 rv=hddDevices[f->unit].format;
                 break;
         case HDIOC_FREESECTOR:
                 rv=apaGetFreeSectors(f->unit, bufp, hddDevices);
                 break;
         case HDIOC_IDLEIMM:
                 rv=ata_device_idle_immediate(f->unit);
                 break;
         // Command set 2 ('h')
         case HDIOC_GETTIME:
                 rv=apaGetTime((apa_ps2time_t *)bufp);
                 break;
         case HDIOC_SETOSDMBR:
                 rv=devctlSetOsdMBR(f->unit, (hddSetOsdMBR_t *)arg);
                 break;
         case HDIOC_GETSECTORERROR:
                 rv=apaGetPartErrorSector(f->unit, APA_SECTOR_SECTOR_ERROR, 0);
                 break;
         case HDIOC_GETERRORPARTNAME:
                 rv=apaGetPartErrorName(f->unit, (char *)bufp);
                 break;
         case HDIOC_READSECTOR:
                 rv=ata_device_sector_io(f->unit, (void *)bufp, ((hddAtaTransfer_t *)arg)->lba,
                         ((hddAtaTransfer_t *)arg)->size, ATA_DIR_READ);
                 break;
         case HDIOC_WRITESECTOR:
                 rv=ata_device_sector_io(f->unit, ((hddAtaTransfer_t *)arg)->data,
                         ((hddAtaTransfer_t *)arg)->lba, ((hddAtaTransfer_t *)arg)->size,
                                 ATA_DIR_WRITE);
                 break;
         case HDIOC_SCEIDENTIFY:
                 rv=ata_device_sce_identify_drive(f->unit, (u16 *)bufp);
                 break;
         default:
                 rv=-EINVAL;
                 break;
         }
         SignalSema(fioSema);
         return rv;
 }
References APA_SECTOR_SECTOR_ERROR, apaGetFreeSectors(), apaGetPartErrorName(), apaGetPartErrorSector(), apaGetTime(), arg, ata_device_flush_cache(), ata_device_idle(), ata_device_idle_immediate(), ata_device_sce_identify_drive(), ata_device_sector_io(), ata_device_smart_get_status(), ATA_DIR_READ, ATA_DIR_WRITE, dev9Shutdown(), devctlSetOsdMBR(), devctlSwapTemp(), EINVAL, EIO, fioSema, apa_device_t::format, hddDevices, HDIOC_DEV9OFF, HDIOC_FLUSH, HDIOC_FORMATVER, HDIOC_FREESECTOR, HDIOC_GETERRORPARTNAME, HDIOC_GETSECTORERROR, HDIOC_GETTIME, HDIOC_IDLE, HDIOC_IDLEIMM, HDIOC_MAXSECTOR, HDIOC_READSECTOR, HDIOC_SCEIDENTIFY, HDIOC_SETOSDMBR, HDIOC_SMARTSTAT, HDIOC_STATUS, HDIOC_SWAPTMP, HDIOC_TOTALSECTOR, HDIOC_WRITESECTOR, apa_device_t::partitionMaxSize, SignalSema(), apa_device_t::status, apa_device_t::totalLBA, iop_file_t::unit, and WaitSema().
hddDopen()
int hddDopen (iop_file_t * f, const char * name)
Definition at line 656 of file hdd_fio.c.
 {
     return hddOpen(f, name, 0, 0);
 }
References hddOpen().
hddDread()
int hddDread (iop_file_t * f, iox_dirent_t * dirent)
Definition at line 661 of file hdd_fio.c.
 {
         int                             rv;
         hdd_file_slot_t *fileSlot=f->privdata;
         apa_cache_t             *clink;
         if(!(f->mode & O_DIROPEN))
                 return -ENOTDIR;
         if(fileSlot->parts[0].start==-1)
                 return 0;// end :)
         WaitSema(fioSema);
         if((clink=apaCacheGetHeader(f->unit, fileSlot->parts[0].start, APA_IO_MODE_READ, &rv)) &&
                 clink->header->length)
         {
                 if(clink->header->flags & APA_FLAG_SUB) {
                         // if sub get id from main header...
                         apa_cache_t *cmain=apaCacheGetHeader(f->unit, clink->header->main, APA_IO_MODE_READ, &rv);
                         if(cmain!=NULL){
                         /*      This was the SONY original, which didn't do bounds-checking:
                                 rv=strlen(cmain->header->id);
                                 strcpy(dirent->name, cmain->header->id); */
                                 strncpy(dirent->name, cmain->header->id, APA_IDMAX);
                                 dirent->name[APA_IDMAX] = '\0';
                                 rv=strlen(dirent->name);
                                 apaCacheFree(cmain);
                         }
                 }
                 else {
                 /*      This was the SONY original, which didn't do bounds-checking:
                         rv=strlen(clink->header->id);
                         strcpy(dirent->name, clink->header->id); */
                         strncpy(dirent->name, clink->header->id, APA_IDMAX);
                         dirent->name[APA_IDMAX] = '\0';
                         rv=strlen(dirent->name);
                 }
                 fioGetStatFiller(clink, &dirent->stat);
                 if(clink->header->next==0)
                         fileSlot->parts[0].start=-1;            // mark end
                 else
                         fileSlot->parts[0].start=clink->header->next;// set next
                 apaCacheFree(clink);
         }
         SignalSema(fioSema);
         return rv;
 }
References APA_FLAG_SUB, APA_IDMAX, APA_IO_MODE_READ, apaCacheFree(), apaCacheGetHeader(), ENOTDIR, fioGetStatFiller(), fioSema, apa_header_t::flags, apa_cache_t::header, apa_header_t::id, apa_header_t::length, apa_header_t::main, iop_file_t::mode, iox_dirent_t::name, apa_header_t::next, NULL, O_DIROPEN, hdd_file_slot_t::parts, iop_file_t::privdata, SignalSema(), apa_sub_t::start, iox_dirent_t::stat, strlen(), strncpy(), iop_file_t::unit, and WaitSema().
hddFormat()
int hddFormat (iop_file_t * f, const char * dev, const char * blockdev, void * arg, int arglen)
Definition at line 262 of file hdd_fio.c.
 {
         int                             rv=0;
         apa_cache_t             *clink;
         u32                     i;
 #ifdef APA_FORMAT_MAKE_PARTITIONS
         apa_params_t            params;
         u32                             emptyBlocks[32];
 #endif
         if(f->unit >= 2)
                 return -ENXIO;
         // clear all errors on hdd
         clink=apaCacheAlloc();
         memset(clink->header, 0, sizeof(apa_header_t));
         if(ata_device_sector_io(f->unit, clink->header, APA_SECTOR_SECTOR_ERROR, 1, ATA_DIR_WRITE)){
                 apaCacheFree(clink);
                 return -EIO;
         }
         if(ata_device_sector_io(f->unit, clink->header, APA_SECTOR_PART_ERROR, 1, ATA_DIR_WRITE)){
                 apaCacheFree(clink);
                 return -EIO;
         }
         // clear apa headers
         for(i=1024*8;i<hddDevices[f->unit].totalLBA;i+=(1024*256))
         {
                 ata_device_sector_io(f->unit, clink->header, i, sizeof(apa_header_t)/512,
                         ATA_DIR_WRITE);
         }
         apaCacheFree(clink);
         if((rv=apaJournalReset(f->unit))!=0)
                 return rv;
         // set up mbr :)
         if((clink=apaCacheGetHeader(f->unit, 0, APA_IO_MODE_WRITE, &rv))){
                 apa_header_t *header=clink->header;
                 memset(header, 0, sizeof(apa_header_t));
                 header->magic=APA_MAGIC;
                 header->length=(1024*256);      // 128MB
                 header->type=APA_TYPE_MBR;
                 strcpy(header->id,"__mbr");
 #ifdef APA_FORMAT_LOCK_MBR
                 apaEncryptPassword(header->id, header->fpwd, "sce_mbr");
                 apaEncryptPassword(header->id, header->rpwd, "sce_mbr");
 #endif
                 memcpy(header->mbr.magic, apaMBRMagic, sizeof(header->mbr.magic));
                 header->mbr.version=APA_MBR_VERSION;
                 header->mbr.nsector=0;
                 apaGetTime(&header->created);
                 apaGetTime(&header->mbr.created);
                 header->checksum=apaCheckSum(header);
                 clink->flags|=APA_CACHE_FLAG_DIRTY;
                 apaCacheFlushDirty(clink);
                 ata_device_flush_cache(f->unit);
                 apaCacheFree(clink);
                 hddDevices[f->unit].status=0;
                 hddDevices[f->unit].format=APA_MBR_VERSION;
         }
 #ifdef APA_FORMAT_MAKE_PARTITIONS
         memset(&emptyBlocks, 0, sizeof(emptyBlocks));
         memset(&params, 0, sizeof(apa_params_t));
         params.size=(1024*256);
         params.type=APA_TYPE_PFS;
         // add __net, __system....
         for(i=0;formatPartList[i];i++)
         {
                 memset(params.id, 0, APA_IDMAX);
                 strcpy(params.id, formatPartList[i]);
                 if(!(clink=hddAddPartitionHere(f->unit, &params, emptyBlocks, i ? clink->sector : 0, &rv)))
                         return rv;
                 apaCacheFree(clink);
                 params.size<<=1;
                 if(hddDevices[f->unit].partitionMaxSize < params.size)
                         params.size=hddDevices[f->unit].partitionMaxSize;
         }
 #endif
         return rv;
 }
References APA_CACHE_FLAG_DIRTY, APA_IDMAX, APA_IO_MODE_WRITE, APA_MAGIC, APA_MBR_VERSION, APA_SECTOR_PART_ERROR, APA_SECTOR_SECTOR_ERROR, APA_TYPE_MBR, APA_TYPE_PFS, apaCacheAlloc(), apaCacheFlushDirty(), apaCacheFree(), apaCacheGetHeader(), apaCheckSum(), apaEncryptPassword(), apaGetTime(), apaJournalReset(), apaMBRMagic, ata_device_flush_cache(), ata_device_sector_io(), ATA_DIR_WRITE, apa_header_t::checksum, apa_header_t::created, EIO, ENXIO, apa_cache_t::flags, apa_device_t::format, formatPartList, apa_header_t::fpwd, hddAddPartitionHere(), hddDevices, apa_cache_t::header, apa_header_t::id, apa_params_t::id, apa_header_t::length, apa_header_t::magic, apa_header_t::mbr, memcpy(), memset(), apa_header_t::nsector, apa_device_t::partitionMaxSize, apa_header_t::rpwd, apa_cache_t::sector, apa_params_t::size, apa_device_t::status, strcpy(), apa_device_t::totalLBA, apa_header_t::type, apa_params_t::type, iop_file_t::unit, and apa_header_t::version.
hddGetStat()
int hddGetStat (iop_file_t * f, const char * name, iox_stat_t * stat)
Definition at line 637 of file hdd_fio.c.
 {
         apa_cache_t     *clink;
         apa_params_t    params;
         int                     rv;
         if((rv=fioGetInput(name, &params))<0)
                 return rv;
         WaitSema(fioSema);
         if((clink=apaFindPartition(f->unit, params.id, &rv))){
                 if((rv=apaPassCmp(clink->header->fpwd, params.fpwd))==0 || (rv=apaPassCmp(clink->header->rpwd, params.rpwd))==0)
                                 fioGetStatFiller(clink, stat);
                 apaCacheFree(clink);
         }
         SignalSema(fioSema);
         return rv;
 }
References apaCacheFree(), apaFindPartition(), apaPassCmp(), fioGetInput(), fioGetStatFiller(), fioSema, apa_header_t::fpwd, apa_params_t::fpwd, apa_cache_t::header, apa_params_t::id, apa_header_t::rpwd, apa_params_t::rpwd, SignalSema(), iop_file_t::unit, and WaitSema().
hddInit()
int hddInit (iop_device_t * f)
Definition at line 243 of file hdd_fio.c.
 {
         iop_sema_t sema;
         sema.attr=1;
         sema.initial=1;
         sema.max=1;
         sema.option=0;
         fioSema=CreateSema(&sema);
         return 0;
 }
References iop_sema_t::attr, CreateSema(), fioSema, iop_sema_t::initial, iop_sema_t::max, and iop_sema_t::option.
hddIoctl2()
int hddIoctl2 (iop_file_t * f, int request, void * argp, unsigned int arglen, void * bufp, unsigned intbuflen)
hddLseek()
int hddLseek (iop_file_t * f, int post, int whence)
Definition at line 573 of file hdd_fio.c.
 {
         int     rv=0;
         hdd_file_slot_t *fileSlot;
         // test input( no seeking to end point less :P )
         if(whence==SEEK_END)
                 return -EINVAL;
         if((post & 0x1FF))
                 return -EINVAL;
         post>>=9;// post/512
         WaitSema(fioSema);
         fileSlot=f->privdata;
         if(whence==SEEK_CUR)
         {
                 if((fileSlot->post+post) < 0 || (fileSlot->post+post)>=0x1FF9)
                         rv=-EINVAL;
                 else
                 {
                         fileSlot->post+=post;
                         rv=fileSlot->post<<9;
                 }
         }
         else if(whence==SEEK_SET)
         {
                 if(post < 0 || post>=0x1FF9)
                         rv=-EINVAL;
                 else
                 {
                         fileSlot->post=post;
                         rv=fileSlot->post<<9;
                 }
         }
         SignalSema(fioSema);
         return rv;
 }
References EINVAL, fioSema, hdd_file_slot_t::post, iop_file_t::privdata, SEEK_CUR, SEEK_END, SEEK_SET, SignalSema(), and WaitSema().
hddOpen()
int hddOpen (iop_file_t * f, const char * name, int flags, int mode)
Definition at line 522 of file hdd_fio.c.
 {
         int                     rv;
         apa_params_t    params;
         hdd_file_slot_t *fileSlot;
         if(f->unit >= 2 || hddDevices[f->unit].status!=0)
                 return -ENODEV;
         if(!(f->mode & O_DIROPEN))
                 if((rv=fioGetInput(name, &params)) < 0)
                         return rv;
         WaitSema(fioSema);
         if((rv=getFileSlot(&params, &fileSlot))==0) {
                 if(!(f->mode & O_DIROPEN)) {
                         if((rv=apaOpen(f->unit, fileSlot, &params, flags))==0){
                                 fileSlot->f=f;
                                 f->privdata=fileSlot;
                         }
                 }
                 else
                 {
                         fileSlot->f=f;
                         f->privdata=fileSlot;
                 }
         }
         SignalSema(fioSema);
         return rv;
 }
References apaOpen(), ENODEV, hdd_file_slot_t::f, fioGetInput(), fioSema, getFileSlot(), hddDevices, iop_file_t::mode, O_DIROPEN, iop_file_t::privdata, SignalSema(), apa_device_t::status, iop_file_t::unit, and WaitSema().
Referenced by hddDopen().
hddRead()
int hddRead (iop_file_t * f, void * buf, int size)
Definition at line 561 of file hdd_fio.c.
 {
         return fioDataTransfer(f, buf, size, ATA_DIR_READ);
 }
References ATA_DIR_READ, and fioDataTransfer().
hddRemove()
int hddRemove (iop_file_t * f, const char * name)
Definition at line 507 of file hdd_fio.c.
 {
         int                     rv;
         apa_params_t    params;
         if((rv=fioGetInput(name, &params)) < 0)
                 return rv;
         WaitSema(fioSema);
         rv = apaRemove(f->unit, params.id, params.fpwd);
         SignalSema(fioSema);
         return rv;
 }
References apaRemove(), fioGetInput(), fioSema, apa_params_t::fpwd, apa_params_t::id, SignalSema(), iop_file_t::unit, and WaitSema().
hddReName()
int hddReName (iop_file_t * f, const char * oldname, const char * newname)
Definition at line 715 of file hdd_fio.c.
 {
         apa_params_t oldParams;
         apa_params_t newParams;
         int rv;
         if((rv=fioGetInput(oldname, &oldParams))<0)
                 return rv;
         if((rv=fioGetInput(newname, &newParams))<0)
                 return rv;
         WaitSema(fioSema);
         rv = apaRename(f->unit, &oldParams, &newParams);
         SignalSema(fioSema);
         return rv;
 }
References apaRename(), fioGetInput(), fioSema, SignalSema(), iop_file_t::unit, and WaitSema().
hddUnsupported()
int hddUnsupported (iop_file_t * f)
Definition at line 1031 of file hdd_fio.c.
 {return -1;}
hddWrite()
int hddWrite (iop_file_t * f, void * buf, int size)
Definition at line 566 of file hdd_fio.c.
 {
         if(!(f->mode & O_WRONLY))
                 return -EACCES;
         return fioDataTransfer(f, buf, size, ATA_DIR_WRITE);
 }
References ATA_DIR_WRITE, EACCES, fioDataTransfer(), iop_file_t::mode, and O_WRONLY.