ps2sdk: iop/hdd/libpfs/src/block.c File Reference
block.c File Reference
#include <errno.h>
#include <stdio.h>
#include <sysclib.h>
#include "pfs-opt.h"
#include "libpfs.h"
Functions
pfs_cache_t * pfsBlockGetNextSegment (pfs_cache_t *clink, int *result)
int pfsBlockSeekNextSegment (pfs_cache_t *clink, pfs_blockpos_t *blockpos)
u32 pfsBlockSyncPos (pfs_blockpos_t *blockpos, u64 size)
int pfsBlockInitPos (pfs_cache_t *clink, pfs_blockpos_t *blockpos, u64 position)
Function Documentation
pfsBlockGetNextSegment()
pfs_cache_t* pfsBlockGetNextSegment (pfs_cache_t * clink, int * result)
Definition at line 25 of file block.c.
 {
         pfsCacheFree(clink);
         if (clink->u.inode->next_segment.number)
                 return pfsCacheGetData(clink->pfsMount,
                 clink->u.inode->next_segment.subpart,
                 clink->u.inode->next_segment.number << clink->pfsMount->inode_scale,
                 PFS_CACHE_FLAG_SEGI, result);
         PFS_PRINTF(PFS_DRV_NAME": Error: There is no next segment descriptor\n");
         *result=-EINVAL;
         return NULL;
 }
References EINVAL, pfs_cache_t::inode, pfs_mount_t::inode_scale, pfs_inode_t::next_segment, NULL, pfs_blockinfo_t::number, PFS_CACHE_FLAG_SEGI, PFS_DRV_NAME, PFS_PRINTF, pfsCacheFree(), pfsCacheGetData(), pfs_cache_t::pfsMount, result, pfs_blockinfo_t::subpart, and pfs_cache_t::u.
Referenced by pfsBitmapFreeInodeBlocks(), pfsBlockSeekNextSegment(), pfsFreeZones(), and pfsInodeSync().
pfsBlockInitPos()
int pfsBlockInitPos (pfs_cache_t * clink, pfs_blockpos_t * blockpos, u64 position)
Definition at line 85 of file block.c.
 {
         blockpos->inode=pfsCacheUsedAdd(clink);
         blockpos->byte_offset=0;
         if (clink->u.inode->size)
         {
                 blockpos->block_segment=1;
                 blockpos->block_offset=0;
         }else{
                 blockpos->block_segment=0;
                 blockpos->block_offset=1;
         }
         return pfsInodeSync(blockpos, position, clink->u.inode->number_data);
 }
References pfs_blockpos_t::block_offset, pfs_blockpos_t::block_segment, pfs_blockpos_t::byte_offset, pfs_cache_t::inode, pfs_blockpos_t::inode, pfs_inode_t::number_data, pfsCacheUsedAdd(), pfsInodeSync(), pfs_inode_t::size, and pfs_cache_t::u.
Referenced by _seek(), openFile(), and pfsGetDentriesAtPos().
pfsBlockSeekNextSegment()
int pfsBlockSeekNextSegment (pfs_cache_t * clink, pfs_blockpos_t * blockpos)
Definition at line 42 of file block.c.
 {
         pfs_cache_t *nextSegment;
         int result=0;
         if (blockpos->byte_offset)
         {
                 PFS_PRINTF(PFS_DRV_NAME": Panic: This is a bug!\n");
                 return -1;
         }
         // If we're at the end of the block descriptor array for the current
         // inode, then move onto the next inode
         if (pfsFixIndex(blockpos->block_segment+1)==0)
         {
                 if ((nextSegment=pfsBlockGetNextSegment(pfsCacheUsedAdd(blockpos->inode), &result)) == NULL)
                         return result;
                 pfsCacheFree(blockpos->inode);
                 blockpos->inode=nextSegment;
                 if (clink->u.inode->number_data-1 == ++blockpos->block_segment)
                         return -EINVAL;
         }
         blockpos->block_offset=0;
         blockpos->block_segment++;
         return result;
 }
References pfs_blockpos_t::block_offset, pfs_blockpos_t::block_segment, pfs_blockpos_t::byte_offset, EINVAL, pfs_cache_t::inode, pfs_blockpos_t::inode, NULL, pfs_inode_t::number_data, PFS_DRV_NAME, PFS_PRINTF, pfsBlockGetNextSegment(), pfsCacheFree(), pfsCacheUsedAdd(), pfsFixIndex(), result, and pfs_cache_t::u.
Referenced by fileTransfer().
pfsBlockSyncPos()
u32 pfsBlockSyncPos (pfs_blockpos_t * blockpos, u64 size)
Definition at line 70 of file block.c.
 {
         u32 i;
         i = (u32)(size / blockpos->inode->pfsMount->zsize);
         blockpos->byte_offset += size % blockpos->inode->pfsMount->zsize;
         if (blockpos->byte_offset >= blockpos->inode->pfsMount->zsize)
         {
                 blockpos->byte_offset -= blockpos->inode->pfsMount->zsize;
                 i++;
         }
         return i;
 }
References pfs_blockpos_t::byte_offset, pfs_blockpos_t::inode, pfs_cache_t::pfsMount, and pfs_mount_t::zsize.
Referenced by fileTransfer(), and pfsInodeSync().