ps2sdk: iop/dev9/hdpro_atad/src/hdproatad.c File Reference
hdproatad.c File Reference
#include <types.h>
#include <defs.h>
#include <irx.h>
#include <loadcore.h>
#include <intrman.h>
#include <thbase.h>
#include <thevent.h>
#include <stdio.h>
#include <sysclib.h>
#include <atad.h>
#include <atahw.h>
Data Structures
struct ata_cmd_info_t
struct ata_cmd_state_t
Macros
#define MODNAME "hdcombo_driver"
#define M_PRINTF(format, args...) printf(MODNAME ": " format, ## args)
#define BANNER "ATA device driver for HD Pro Kit %s\n"
#define VERSION "v1.0"
#define ATA_XFER_MODE_PIO 0x08
#define ATA_EV_TIMEOUT 1
#define ATA_EV_COMPLETE 2
#define HDPROreg_IO8 (*(vu8 *)0xBFC00000)
#define HDPROreg_IO32 (*(vu32 *)0xBFC00000)
#define CDVDreg_STATUS (*(vu8 *)0xBF40200A)
#define ATAreg_CONTROL_RD 0x68
#define ATAreg_SELECT_RD 0x70
#define ATAreg_STATUS_RD 0xf0
#define ATAreg_ERROR_RD 0x90
#define ATAreg_NSECTOR_RD 0x50
#define ATAreg_SECTOR_RD 0xd0
#define ATAreg_LCYL_RD 0x30
#define ATAreg_HCYL_RD 0xb0
#define ATAreg_DATA_RD 0x41
#define ATAreg_CONTROL_WR 0x6a
#define ATAreg_SELECT_WR 0x72
#define ATAreg_COMMAND_WR 0xf2
#define ATAreg_FEATURE_WR 0x92
#define ATAreg_NSECTOR_WR 0x52
#define ATAreg_SECTOR_WR 0xd2
#define ATAreg_LCYL_WR 0x32
#define ATAreg_HCYL_WR 0xb2
#define ATAreg_DATA_WR 0x12
#define ATA_CMD_TABLE_SIZE (sizeof ata_cmd_table/sizeof(ata_cmd_info_t))
#define SMART_CMD_TABLE_SIZE (sizeof smart_cmd_table/sizeof(ata_cmd_info_t))
#define ATA_WAIT_BUSY 0x80
#define ATA_WAIT_BUSBUSY 0x88
#define ata_wait_busy() gen_ata_wait_busy(ATA_WAIT_BUSY)
#define ata_wait_bus_busy() gen_ata_wait_busy(ATA_WAIT_BUSBUSY)
Functions
IRX_ID (MODNAME, 1, 1)
static int hdpro_io_start (void)
static int hdpro_io_finish (void)
static void hdpro_io_write (u8 cmd, u16 val)
static int hdpro_io_read (u8 cmd)
static int ata_bus_reset (void)
static int ata_init_devices (ata_devinfo_t *devinfo)
static int gen_ata_wait_busy (int bits)
static unsigned int ata_alarm_cb (void *unused)
static void suspend_intr (void)
static void resume_intr (void)
static int ata_create_event_flag (void)
int _start (int argc, char *argv[])
int shutdown (void)
int ata_get_error (void)
static int ata_device_select (int device)
int ata_io_start (void *buf, u32 blkcount, u16 feature, u16 nsector, u16 sector, u16 lcyl, u16 hcyl, u16 select, u16 command)
static int ata_pio_transfer (ata_cmd_state_t *cmd_state)
int ata_reset_devices (void)
int ata_device_sce_sec_unlock (int device, void *password)
static void ata_device_probe (ata_devinfo_t *devinfo)
int ata_device_flush_cache (int device)
int ata_device_idle (int device, int period)
static int ata_device_set_transfer_mode (int device, int type, int mode)
static int ata_device_identify (int device, void *info)
static int ata_device_smart_enable (int device)
int ata_io_finish (void)
int ata_device_sector_io (int device, void *buf, u32 lba, u32 nsectors, int dir)
ata_devinfo_t * ata_get_devinfo (int device)
Variables
static int ata_devinfo_init = 0
static int ata_evflg = -1
static ata_devinfo_t atad_devinfo [2]
static u16 ata_param [256]
static const ata_cmd_info_t ata_cmd_table []
static const ata_cmd_info_t smart_cmd_table []
static ata_cmd_state_t atad_cmd_state
static int hdpro_io_active = 0
static int intr_suspended = 0
static int intr_state
struct irx_export_table _exp_atad
Macro Definition Documentation
ATA_CMD_TABLE_SIZE
#define ATA_CMD_TABLE_SIZE (sizeof ata_cmd_table/sizeof(ata_cmd_info_t))
Definition at line 138 of file hdproatad.c.
ATA_EV_COMPLETE
#define ATA_EV_COMPLETE 2
Definition at line 39 of file hdproatad.c.
ATA_EV_TIMEOUT
#define ATA_EV_TIMEOUT 1
Definition at line 38 of file hdproatad.c.
ata_wait_bus_busy
#define ata_wait_bus_busy () gen_ata_wait_busy(ATA_WAIT_BUSBUSY)
Definition at line 257 of file hdproatad.c.
ATA_WAIT_BUSBUSY
#define ATA_WAIT_BUSBUSY 0x88
Definition at line 254 of file hdproatad.c.
ATA_WAIT_BUSY
#define ATA_WAIT_BUSY 0x80
Definition at line 253 of file hdproatad.c.
ata_wait_busy
#define ata_wait_busy () gen_ata_wait_busy(ATA_WAIT_BUSY)
Definition at line 256 of file hdproatad.c.
ATA_XFER_MODE_PIO
#define ATA_XFER_MODE_PIO 0x08
Definition at line 36 of file hdproatad.c.
ATAreg_COMMAND_WR
#define ATAreg_COMMAND_WR 0xf2
Definition at line 63 of file hdproatad.c.
ATAreg_CONTROL_RD
#define ATAreg_CONTROL_RD 0x68
Definition at line 50 of file hdproatad.c.
ATAreg_CONTROL_WR
#define ATAreg_CONTROL_WR 0x6a
Definition at line 61 of file hdproatad.c.
ATAreg_DATA_RD
#define ATAreg_DATA_RD 0x41
Definition at line 58 of file hdproatad.c.
ATAreg_DATA_WR
#define ATAreg_DATA_WR 0x12
Definition at line 69 of file hdproatad.c.
ATAreg_ERROR_RD
#define ATAreg_ERROR_RD 0x90
Definition at line 53 of file hdproatad.c.
ATAreg_FEATURE_WR
#define ATAreg_FEATURE_WR 0x92
Definition at line 64 of file hdproatad.c.
ATAreg_HCYL_RD
#define ATAreg_HCYL_RD 0xb0
Definition at line 57 of file hdproatad.c.
ATAreg_HCYL_WR
#define ATAreg_HCYL_WR 0xb2
Definition at line 68 of file hdproatad.c.
ATAreg_LCYL_RD
#define ATAreg_LCYL_RD 0x30
Definition at line 56 of file hdproatad.c.
ATAreg_LCYL_WR
#define ATAreg_LCYL_WR 0x32
Definition at line 67 of file hdproatad.c.
ATAreg_NSECTOR_RD
#define ATAreg_NSECTOR_RD 0x50
Definition at line 54 of file hdproatad.c.
ATAreg_NSECTOR_WR
#define ATAreg_NSECTOR_WR 0x52
Definition at line 65 of file hdproatad.c.
ATAreg_SECTOR_RD
#define ATAreg_SECTOR_RD 0xd0
Definition at line 55 of file hdproatad.c.
ATAreg_SECTOR_WR
#define ATAreg_SECTOR_WR 0xd2
Definition at line 66 of file hdproatad.c.
ATAreg_SELECT_RD
#define ATAreg_SELECT_RD 0x70
Definition at line 51 of file hdproatad.c.
ATAreg_SELECT_WR
#define ATAreg_SELECT_WR 0x72
Definition at line 62 of file hdproatad.c.
ATAreg_STATUS_RD
#define ATAreg_STATUS_RD 0xf0
Definition at line 52 of file hdproatad.c.
BANNER
#define BANNER "ATA device driver for HD Pro Kit %s\n"
Definition at line 33 of file hdproatad.c.
CDVDreg_STATUS
#define CDVDreg_STATUS (*(vu8 *)0xBF40200A)
Definition at line 47 of file hdproatad.c.
HDPROreg_IO32
#define HDPROreg_IO32 (*(vu32 *)0xBFC00000)
Definition at line 45 of file hdproatad.c.
HDPROreg_IO8
#define HDPROreg_IO8 (*(vu8 *)0xBFC00000)
Definition at line 44 of file hdproatad.c.
M_PRINTF
#define M_PRINTF (format, args...) printf(MODNAME ": " format, ## args)
Definition at line 30 of file hdproatad.c.
MODNAME
#define MODNAME "hdcombo_driver"
Definition at line 27 of file hdproatad.c.
SMART_CMD_TABLE_SIZE
#define SMART_CMD_TABLE_SIZE (sizeof smart_cmd_table/sizeof(ata_cmd_info_t))
Definition at line 151 of file hdproatad.c.
VERSION
#define VERSION "v1.0"
Definition at line 34 of file hdproatad.c.
Function Documentation
_start()
int _start (int argc, char * argv[])
Definition at line 212 of file hdproatad.c.
 {
         int res = MODULE_NO_RESIDENT_END;
         printf(BANNER, VERSION);
         if (!hdpro_io_start()) {
                 M_PRINTF("Failed to detect HD Pro, exiting.\n");
                 goto out;
         }
         hdpro_io_finish();
         if ((ata_evflg = ata_create_event_flag()) < 0) {
                 M_PRINTF("Couldn't create event flag, exiting.\n");
                 goto out;
         }
         if ((res = RegisterLibraryEntries(&_exp_atad)) != 0) {
                 M_PRINTF("Library is already registered, exiting.\n");
                 goto out;
         }
         res = MODULE_RESIDENT_END;
         M_PRINTF("Driver loaded.\n");
 out:
         return res;
 }
References _exp_atad, ata_create_event_flag(), ata_evflg, BANNER, hdpro_io_finish(), hdpro_io_start(), M_PRINTF, MODULE_NO_RESIDENT_END, MODULE_RESIDENT_END, printf(), RegisterLibraryEntries(), and VERSION.
ata_alarm_cb()
static unsigned int ata_alarm_cb (void * unused) static
Definition at line 180 of file hdproatad.c.
 {
         iSetEventFlag(ata_evflg, ATA_EV_TIMEOUT);
         return 0;
 }
References ATA_EV_TIMEOUT, ata_evflg, and iSetEventFlag().
Referenced by ata_io_finish(), and ata_io_start().
ata_bus_reset()
static int ata_bus_reset (void) static
Definition at line 398 of file hdproatad.c.
 {
         suspend_intr();
         // HD Pro IO initialization commands sequence
         HDPROreg_IO8 = 0x13;
         CDVDreg_STATUS = 0;
         HDPROreg_IO8 = 0x00;
         CDVDreg_STATUS = 0;
         resume_intr();
         DelayThread(100);
         suspend_intr();
         HDPROreg_IO8 = 0x13;
         CDVDreg_STATUS = 0;
         HDPROreg_IO8 = 0x01;
         CDVDreg_STATUS = 0;
         resume_intr();
         DelayThread(3000);
         return ata_wait_busy();
 }
References ata_wait_busy, CDVDreg_STATUS, DelayThread(), HDPROreg_IO8, resume_intr(), and suspend_intr().
Referenced by ata_get_devinfo().
ata_create_event_flag()
static int ata_create_event_flag (void) static
Definition at line 204 of file hdproatad.c.
{
         iop_event_t event;
         event.attr = EA_SINGLE; //In v1.04, EA_MULTI was specified.
         event.bits = 0;
         return CreateEventFlag(&event);
 }
References iop_event_t::attr, CreateEventFlag(), and EA_SINGLE.
Referenced by _start().
ata_device_flush_cache()
int ata_device_flush_cache (int device)
Definition at line 703 of file hdproatad.c.
 {
         int res;
         if (!hdpro_io_start())
                 return -1;
         if(!(res = ata_io_start(NULL, 1, 0, 0, 0, 0, 0, (device << 4) & 0xffff, atad_devinfo[device].lba48?ATA_C_FLUSH_CACHE_EXT:ATA_C_FLUSH_CACHE))) res=ata_io_finish();
         if (!hdpro_io_finish())
                 return -2;
         return res;
 }
References ATA_C_FLUSH_CACHE, ATA_C_FLUSH_CACHE_EXT, ata_io_finish(), ata_io_start(), atad_devinfo, hdpro_io_finish(), hdpro_io_start(), and NULL.
Referenced by apaJournalFlush(), apaSaveError(), hddDevctl(), hddFormat(), and hddIoctl2().
ata_device_identify()
static int ata_device_identify (int device, void * info) static
Definition at line 746 of file hdproatad.c.
 {
         int res;
         res = ata_io_start(info, 1, 0, 0, 0, 0, 0, (device << 4) & 0xffff, ATA_C_IDENTIFY_DEVICE);
         if (res)
                 return res;
         return ata_io_finish();
 }
References ATA_C_IDENTIFY_DEVICE, ata_io_finish(), and ata_io_start().
Referenced by ata_init_devices().
ata_device_idle()
int ata_device_idle (int device, int period)
Definition at line 719 of file hdproatad.c.
 {
         int res;
         res = ata_io_start(NULL, 1, 0, period & 0xff, 0, 0, 0, (device << 4) & 0xffff, ATA_C_IDLE);
         if (res)
                 return res;
         return ata_io_finish();
 }
References ATA_C_IDLE, ata_io_finish(), ata_io_start(), and NULL.
Referenced by ata_init_devices(), and hddDevctl().
ata_device_probe()
static void ata_device_probe (ata_devinfo_t * devinfo) static
Definition at line 663 of file hdproatad.c.
 {
         u16 nsector, lcyl, hcyl, sector, select;
         devinfo->exists = 0;
         devinfo->has_packet = 2;
         if (hdpro_io_read(ATAreg_CONTROL_RD) & 0x88)
                 return;
         nsector = hdpro_io_read(ATAreg_NSECTOR_RD) & 0xff;
         sector = hdpro_io_read(ATAreg_SECTOR_RD) & 0xff;
         lcyl = hdpro_io_read(ATAreg_LCYL_RD) & 0xff;
         hcyl = hdpro_io_read(ATAreg_HCYL_RD) & 0xff;
         select = hdpro_io_read(ATAreg_SELECT_RD) & 0xff;
         /*      The original HDPro driver did not check sector.
                 However, by the ATA-4 specification (9.1), sector should be 1.
                 So it should be perfectly fine to check. */
         if ((nsector != 1) || (sector != 1))
                 return;
         devinfo->exists = 1;
         if ((lcyl == 0x00) && (hcyl == 0x00))
                 devinfo->has_packet = 0;
         else if ((lcyl == 0x14) && (hcyl == 0xeb))
                 devinfo->has_packet = 1;
         /* Seems to be for ensuring that there is a device connected.
                 Not sure why this has to be done, but is present in v2.4.  */
         hdpro_io_write(ATAreg_LCYL_WR, 0x55);
         hdpro_io_write(ATAreg_HCYL_WR, 0xaa);
         lcyl = hdpro_io_read(ATAreg_LCYL_RD) & 0xff;
         hcyl = hdpro_io_read(ATAreg_HCYL_RD) & 0xff;
         if((lcyl != 0x55) || (hcyl != 0xaa))
                 devinfo->exists = 0;
 }
References ATAreg_CONTROL_RD, ATAreg_HCYL_RD, ATAreg_HCYL_WR, ATAreg_LCYL_RD, ATAreg_LCYL_WR, ATAreg_NSECTOR_RD, ATAreg_SECTOR_RD, ATAreg_SELECT_RD, ata_devinfo_t::exists, ata_devinfo_t::has_packet, hdpro_io_read(), hdpro_io_write(), and select.
Referenced by ata_init_devices().
ata_device_sce_sec_unlock()
int ata_device_sce_sec_unlock (int device, void * password)
Definition at line 658 of file hdproatad.c.
 {       //Device can always be unlocked.
         return 0;
 }
References ATA_C_SCE_SECURITY_CONTROL, ATA_F_SEC_LOCKED, ata_get_security_status(), ata_io_finish(), ata_io_start(), ata_param, ATA_RES_ERR_LOCKED, ATA_SCE_SECURITY_UNLOCK, atad_devinfo, memcpy(), and memset().
Referenced by unlockDrive().
ata_device_sector_io()
int ata_device_sector_io (int device, void * buf, u32 lba, u32 nsectors, int dir)
Definition at line 919 of file hdproatad.c.
 {
         int res = 0;
         u16 sector, lcyl, hcyl, select, command, len;
         if (!hdpro_io_start())
                 return -1;
         while (nsectors) {
                 len = (nsectors > 256) ? 256 : nsectors;
                 /* Variable lba is only 32 bits so no change for lcyl and hcyl.  */
                 lcyl = (lba >> 8) & 0xff;
                 hcyl = (lba >> 16) & 0xff;
                 if (atad_devinfo[device].lba48) {
                         /* Setup for 48-bit LBA.  */
                         /* Combine bits 24-31 and bits 0-7 of lba into sector.  */
                         sector = ((lba >> 16) & 0xff00) | (lba & 0xff);
                         /* In v1.04, LBA was enabled here.  */
                         select = (device << 4) & 0xffff;
                         command = (dir == 1) ? ATA_C_WRITE_SECTOR_EXT : ATA_C_READ_SECTOR_EXT;
                 } else {
                         /* Setup for 28-bit LBA.  */
                         sector = lba & 0xff;
                         /* In v1.04, LBA was enabled here.  */
                         select = ((device << 4) | ((lba >> 24) & 0xf)) & 0xffff;
                         command = (dir == 1) ? ATA_C_WRITE_SECTOR : ATA_C_READ_SECTOR;
                 }
                 //Unlike ATAD, retry indefinitely until the I/O operation succeeds.
                 if ((res = ata_io_start(buf, len, 0, len, sector, lcyl,
                                         hcyl, select, command)) != 0)
                         continue;
                 if ((res = ata_io_finish()) != 0)
                         continue;
                 buf = (void*)((u8 *)buf + len * 512);
                 lba += len;
                 nsectors -= len;
         }
         if (!hdpro_io_finish())
                 return -2;
         return res;
 }
References ATA_C_READ_DMA, ATA_C_READ_DMA_EXT, ATA_C_READ_SECTOR, ATA_C_READ_SECTOR_EXT, ATA_C_WRITE_DMA, ATA_C_WRITE_DMA_EXT, ATA_C_WRITE_SECTOR, ATA_C_WRITE_SECTOR_EXT, ata_io_finish(), ata_io_start(), ATA_RES_ERR_ICRC, ata_set_dir(), atad_devinfo, hdpro_io_finish(), hdpro_io_start(), select, SPD_IF_DMA_ENABLE, SPD_R_IF_CTRL, SPD_REG16, and USE_SPD_REGS.
Referenced by apaGetFormat(), apaGetPartErrorSector(), apaJournalFlush(), apaJournalRestore(), apaJournalWrite(), apaOpen(), apaReadHeader(), apaSaveError(), apaWriteHeader(), fioDataTransfer(), hddDevctl(), hddFormat(), and ioctl2Transfer().
ata_device_select()
static int ata_device_select (int device) static
Definition at line 426 of file hdproatad.c.
 {
         int res;
         if ((res = ata_wait_bus_busy()) < 0)
                 return res;
         /* If the device was already selected, nothing to do.  */
         if (((hdpro_io_read(ATAreg_SELECT_RD) >> 4) & 1) == device)
                 return 0;
         /* Select the device.  */
         hdpro_io_write(ATAreg_SELECT_WR, (device & 1) << 4);
         res = hdpro_io_read(ATAreg_CONTROL_RD);
         return ata_wait_bus_busy();
 }
References ata_wait_bus_busy, ATAreg_CONTROL_RD, ATAreg_SELECT_RD, ATAreg_SELECT_WR, hdpro_io_read(), and hdpro_io_write().
Referenced by ata_init_devices(), and ata_io_start().
ata_device_set_transfer_mode()
static int ata_device_set_transfer_mode (int device, int type, int mode) static
Definition at line 731 of file hdproatad.c.
 {
         int res;
         res = ata_io_start(NULL, 1, 3, (type|mode) & 0xff, 0, 0, 0, (device << 4) & 0xffff, ATA_C_SET_FEATURES);
         if (res)
                 return res;
         res = ata_io_finish();
         if (res)
                 return res;
         return 0;
 }
References ATA_C_SET_FEATURES, ata_io_finish(), ata_io_start(), irx_export_table::mode, and NULL.
Referenced by ata_init_devices().
ata_device_smart_enable()
static int ata_device_smart_enable (int device) static
Definition at line 757 of file hdproatad.c.
 {
         int res;
         if(!(res = ata_io_start(NULL, 1, ATA_S_SMART_ENABLE_OPERATIONS, 0, 0, 0x4f, 0xc2, (device << 4) & 0xffff, ATA_C_SMART))) res=ata_io_finish();
         return res;
 }
References ATA_C_SMART, ata_io_finish(), ata_io_start(), ATA_S_SMART_ENABLE_OPERATIONS, and NULL.
Referenced by ata_init_devices().
ata_get_devinfo()
ata_devinfo_t* ata_get_devinfo (int device)
Definition at line 968 of file hdproatad.c.
 {
         if(!ata_devinfo_init){
                 ata_devinfo_init = 1;
                 if (!hdpro_io_start())
                         return NULL;
                 HDPROreg_IO8 = 0xe3;
                 CDVDreg_STATUS = 0;
                 if ((ata_bus_reset() != 0) || (ata_init_devices(atad_devinfo) != 0) || (!hdpro_io_finish()))
                         return NULL;
         }
         return &atad_devinfo[device];
 }
References ata_bus_reset(), ata_devinfo_init, ata_init_devices(), atad_devinfo, CDVDreg_STATUS, hdpro_io_finish(), hdpro_io_start(), HDPROreg_IO8, and NULL.
Referenced by _start().
ata_get_error()
int ata_get_error (void)
Definition at line 248 of file hdproatad.c.
 {
         return hdpro_io_read(ATAreg_ERROR_RD) & 0xff;
 }
References ATAreg_ERROR_RD, hdpro_io_read(), and USE_ATA_REGS.
Referenced by ata_io_finish(), and ata_pio_transfer().
ata_init_devices()
static int ata_init_devices (ata_devinfo_t * devinfo) static
Definition at line 766 of file hdproatad.c.
 {
         int i, res;
         if((res = ata_reset_devices()) != 0)
                 return res;
         ata_device_probe(&devinfo[0]);
         if (!devinfo[0].exists) {
                 M_PRINTF("Error: Unable to detect HDD 0.\n");
                 devinfo[1].exists = 0;
                 return ATA_RES_ERR_NODEV;       //Returns 0 in v1.04.
         }
         /* If there is a device 1, grab it's info too.  */
         if ((res = ata_device_select(1)) != 0)
                 return res;
         if (hdpro_io_read(ATAreg_CONTROL_RD) & 0xff)
                 ata_device_probe(&devinfo[1]);
         else
                 devinfo[1].exists = 0;
         for (i = 0; i < 2; i++) {
                 if (!devinfo[i].exists)
                         continue;
                 /* Send the IDENTIFY DEVICE command. if it doesn't succeed
                    devinfo is disabled.  */
                 if (!devinfo[i].has_packet) {
                         res = ata_device_identify(i, ata_param);
                         devinfo[i].exists = (res == 0);
                 } else if (devinfo[i].has_packet == 1) {
                         /* If it's a packet device, send the IDENTIFY PACKET
                            DEVICE command.  */
                         /*      Packet devices are not supported:
                                 The original HDPro driver issues the IDENTIFY PACKET DEVICE command,
                                 but does not export ata_io_start and ata_io_finish.
                                 This makes packet device support impossible. */
                         res = -1;
                         devinfo[i].exists = (res == 0);
                 }
                 /* Otherwise, do nothing if has_packet = 2. */
                 /* This next section is HDD-specific: if no device or it's a
                    packet (ATAPI) device, we're done.  */
                 if (!devinfo[i].exists || devinfo[i].has_packet)
                         continue;
                 /* This section is to detect whether the HDD supports 48-bit LBA
                    (IDENITFY DEVICE bit 10 word 83) and get the total sectors from
                    either words(61:60) for 28-bit or words(103:100) for 48-bit.  */
                 if (ata_param[ATA_ID_COMMAND_SETS_SUPPORTED] & 0x0400) {
                         atad_devinfo[i].lba48 = 1;
                         /* I don't think anyone would use a >2TB HDD but just in case.  */
                         if (ata_param[ATA_ID_48BIT_SECTOTAL_HI]) {
                                 devinfo[i].total_sectors = 0xffffffff;
                         } else {
                                 devinfo[i].total_sectors =
                                         (ata_param[ATA_ID_48BIT_SECTOTAL_MI] << 16)|
                                         ata_param[ATA_ID_48BIT_SECTOTAL_LO];
                         }
                 } else {
                         atad_devinfo[i].lba48 = 0;
                         devinfo[i].total_sectors = (ata_param[ATA_ID_SECTOTAL_HI] << 16)|
                                 ata_param[ATA_ID_SECTOTAL_LO];
                 }
                 devinfo[i].security_status = ata_param[ATA_ID_SECURITY_STATUS];
                 /* PIO mode 0 (flow control).  */
                 ata_device_set_transfer_mode(i, ATA_XFER_MODE_PIO, 0);
                 ata_device_smart_enable(i);
                 /* Disable idle timeout.  */
                 ata_device_idle(i, 0);
         }
         return 0;
 }
References ata_device_identify(), ata_device_idle(), ata_device_probe(), ata_device_select(), ata_device_set_transfer_mode(), ata_device_smart_enable(), ATA_ID_48BIT_SECTOTAL_HI, ATA_ID_48BIT_SECTOTAL_LO, ATA_ID_48BIT_SECTOTAL_MI, ATA_ID_COMMAND_SETS_SUPPORTED, ATA_ID_SECTOTAL_HI, ATA_ID_SECTOTAL_LO, ATA_ID_SECURITY_STATUS, ata_param, ATA_RES_ERR_NODEV, ata_reset_devices(), ATA_XFER_MODE_PIO, atad_devinfo, ATAreg_CONTROL_RD, ata_devinfo_t::exists, hdpro_io_read(), ata_devinfo_t::lba48, M_PRINTF, ata_devinfo_t::security_status, and ata_devinfo_t::total_sectors.
Referenced by ata_get_devinfo().
ata_io_finish()
int ata_io_finish (void)
Definition at line 845 of file hdproatad.c.
 {
         ata_cmd_state_t *cmd_state = &atad_cmd_state;
         u32 bits;
         int res = 0, type = cmd_state->type;
         u16 stat;
         if (type == 1 || type == 6) {   /* Non-data commands.  */
                 //Unlike ATAD, poll until the device either completes its command or times out. There is no completion interrupt.
                 while(1)
                 {
                         suspend_intr();
                         HDPROreg_IO8 = 0x21;
                         CDVDreg_STATUS = 0;
                         unsigned int ret = HDPROreg_IO8;
                         CDVDreg_STATUS = 0;
                         resume_intr();
                         if (((ret & 0xff) & 1) != 0) {
                                 //Command completed.
                                 break;
                         }
                         /*      The original did not check on the return value of PollEventFlag,
                                 but PollEventFlag does not seem to return the event flag's bits if the wait condition is not satisfied. */
                         if(PollEventFlag(ata_evflg, ATA_EV_TIMEOUT | ATA_EV_COMPLETE, WEF_CLEAR|WEF_OR, &bits) == 0)
{
                                 if (bits & ATA_EV_TIMEOUT) {    /* Timeout.  */
                                         M_PRINTF("Error: ATA timeout on a non-data command.\n");
                                         return ATA_RES_ERR_TIMEOUT;
                                 }
                         }
                         DelayThread(500);
                 }
         /*      Support for DMA commands (type = 4) is removed because HDPro cannot support DMA.
                 The original would return ATA_RES_ERR_TIMEOUT for type = 4. */
         } else {                        /* PIO transfers.  */
                 stat = hdpro_io_read(ATAreg_CONTROL_RD);
                 if ((res = ata_wait_busy()) < 0)
                         goto finish;
                 /* Transfer each PIO data block.  */
                 while (--cmd_state->blkcount != -1) {
                         if ((res = ata_pio_transfer(cmd_state)) < 0)
                                 goto finish;
                         if ((res = ata_wait_busy()) < 0)
                                 goto finish;
                 }
         }
         if (res)
                 goto finish;
         /* Wait until the device isn't busy.  */
         if (hdpro_io_read(ATAreg_STATUS_RD) & ATA_STAT_BUSY)
                 res = ata_wait_busy();
         if ((stat = hdpro_io_read(ATAreg_STATUS_RD)) & ATA_STAT_ERR) {
                 M_PRINTF("Error: Command error: status 0x%02x, error 0x%02x.\n", stat, ata_get_error());
                 res = ATA_RES_ERR_IO;
         }
 finish:
         /* The command has completed (with an error or not), so clean things up.  */
         CancelAlarm(&ata_alarm_cb, NULL);
         return res;
 }
References ata_alarm_cb(), ata_dma_complete(), ATA_ERR_ICRC, ATA_EV_COMPLETE, ATA_EV_TIMEOUT, ata_evflg, ata_get_error(), ata_pio_transfer(), ATA_RES_ERR_ICRC, ATA_RES_ERR_IO, ATA_RES_ERR_TIMEOUT, ATA_STAT_BUSY, ATA_STAT_ERR, ata_wait_busy, atad_cmd_state, ATAreg_CONTROL_RD, ATAreg_STATUS_RD, ata_cmd_state_t::blkcount, ata_cmd_state_t::buf, CancelAlarm(), CDVDreg_STATUS, DelayThread(), dev9IntrEnable(), dev9LEDCtl(), ata_cmd_state_t::dir, hdpro_io_read(), HDPROreg_IO8, M_PRINTF, NULL, PollEventFlag(), resume_intr(), SPD_INTR_ATA0, SPD_R_INTR_MASK, SPD_R_INTR_STAT, SPD_REG16, suspend_intr(), ata_cmd_state_t::type, USE_ATA_REGS, USE_SPD_REGS, WaitEventFlag(), WEF_CLEAR, and WEF_OR.
Referenced by ata_device_flush_cache(), ata_device_identify(), ata_device_idle(), ata_device_sector_io(), ata_device_set_transfer_mode(), and ata_device_smart_enable().
ata_io_start()
int ata_io_start (void * buf, u32 blkcount, u16 feature, u16 nsector, u16 sector, u16 lcyl, u16 hcyl, u16 select, u16 command)
Definition at line 445 of file hdproatad.c.
 {
         iop_sys_clock_t cmd_timeout;
         const ata_cmd_info_t *cmd_table;
         int i, res, type, cmd_table_size;
         int using_timeout, device = (select >> 4) & 1;
         u8 searchcmd;
         ClearEventFlag(ata_evflg, 0);
         if (!atad_devinfo[device].exists)
                 return ATA_RES_ERR_NODEV;
         if ((res = ata_device_select(device)) != 0)
                 return res;
         /* For the SMART commands, we need to search on the subcommand
         specified in the feature register.  */
         if (command == ATA_C_SMART) {
                 cmd_table = smart_cmd_table;
                 cmd_table_size = SMART_CMD_TABLE_SIZE;
                 searchcmd = feature;
         } else {
                 cmd_table = ata_cmd_table;
                 cmd_table_size = ATA_CMD_TABLE_SIZE;
                 searchcmd = command & 0xff;
         }
         type = 0;
         for (i = 0; i < cmd_table_size; i++) {
                 if (searchcmd == cmd_table[i].command) {
                         type = cmd_table[i].type;
                         break;
                 }
         }
         if (!(atad_cmd_state.type = type & 0x7F))
                 return ATA_RES_ERR_CMD;
         atad_cmd_state.buf = buf;
         atad_cmd_state.blkcount = blkcount;
         /* Check that the device is ready if this the appropiate command.  */
         if (!(hdpro_io_read(ATAreg_CONTROL_RD) & 0x40)) {
                 switch (command) {
                         case ATA_C_DEVICE_RESET:
                         case ATA_C_EXECUTE_DEVICE_DIAGNOSTIC:
                         case ATA_C_INITIALIZE_DEVICE_PARAMETERS:
                         case ATA_C_PACKET:
                         case ATA_C_IDENTIFY_PACKET_DEVICE:
                                 break;
                         default:
                                 M_PRINTF("Error: Device %d is not ready.\n", device);
                                 return ATA_RES_ERR_NOTREADY;
                 }
         }
         /* Does this command need a timeout?  */
         using_timeout = 0;
         switch (type & 0x7F) {
                 case 1:
                 case 6:
                         using_timeout = 1;
                         break;
                 //Support for DMA commands (type = 4) is removed because HDPro cannot support DMA. The original HDPro driver still had code for it though.
         }
         if (using_timeout) {
                 cmd_timeout.lo = 0x41eb0000;
                 cmd_timeout.hi = 0;
                 if ((res = SetAlarm(&cmd_timeout, &ata_alarm_cb, NULL)) < 0)
                         return res;
         }
         /* Enable the command completion interrupt.  */
         suspend_intr();
         HDPROreg_IO8 = 0x21;
         CDVDreg_STATUS = 0;
         unsigned int dummy __attribute__((unused)) = HDPROreg_IO8;
         CDVDreg_STATUS = 0;
         resume_intr();
         dummy = 0;
         /* Finally!  We send off the ATA command with arguments.  */
         hdpro_io_write(ATAreg_CONTROL_WR, (using_timeout == 0) << 1);
         if(type&0x80) { //For the sake of achieving improved performance, write the registers twice only if required!
                 /* 48-bit LBA requires writing to the address registers twice,
                    24 bits of the LBA address is written each time.
                    Writing to registers twice does not affect 28-bit LBA since
                    only the latest data stored in address registers is used.  */
                 hdpro_io_write(ATAreg_FEATURE_WR, (feature & 0xffff) >> 8);
                 hdpro_io_write(ATAreg_NSECTOR_WR, (nsector & 0xffff) >> 8);
                 hdpro_io_write(ATAreg_SECTOR_WR, (sector & 0xffff) >> 8);
                 hdpro_io_write(ATAreg_LCYL_WR, (lcyl & 0xffff) >> 8);
                 hdpro_io_write(ATAreg_HCYL_WR, (hcyl & 0xffff) >> 8);
         }
         hdpro_io_write(ATAreg_FEATURE_WR, feature & 0xff);
         hdpro_io_write(ATAreg_NSECTOR_WR, nsector & 0xff);
         hdpro_io_write(ATAreg_SECTOR_WR, sector & 0xff);
         hdpro_io_write(ATAreg_LCYL_WR, lcyl & 0xff);
         hdpro_io_write(ATAreg_HCYL_WR, hcyl & 0xff);
         hdpro_io_write(ATAreg_SELECT_WR, (select | ATA_SEL_LBA) & 0xff);        //In v1.04, LBA was enabled in the ata_device_sector_io function.
         hdpro_io_write(ATAreg_COMMAND_WR, command & 0xff);
         return 0;
 }
References ata_alarm_cb(), ATA_C_DEVICE_RESET, ATA_C_EXECUTE_DEVICE_DIAGNOSTIC, ATA_C_IDENTIFY_PACKET_DEVICE, ATA_C_INITIALIZE_DEVICE_PARAMETERS, ATA_C_PACKET, ATA_C_READ_DMA, ATA_C_READ_DMA_EXT, ATA_C_SCE_SECURITY_CONTROL, ATA_C_SMART, ata_cmd_table, ATA_CMD_TABLE_SIZE, ata_device_select(), ata_evflg, ATA_RES_ERR_CMD, ATA_RES_ERR_NODEV, ATA_RES_ERR_NOTREADY, ATA_SCE_SECURITY_ERASE_UNIT, ATA_SEL_LBA, atad_cmd_state, atad_devinfo, ATAreg_COMMAND_WR, ATAreg_CONTROL_RD, ATAreg_CONTROL_WR, ATAreg_FEATURE_WR, ATAreg_HCYL_WR, ATAreg_LCYL_WR, ATAreg_NSECTOR_WR, ATAreg_SECTOR_WR, ATAreg_SELECT_WR, ata_cmd_state_t::blkcount, ata_cmd_state_t::buf, CDVDreg_STATUS, ClearEventFlag(), dev9IntrEnable(), dev9LEDCtl(), ata_cmd_state_t::dir, dummy(), hdpro_io_read(), hdpro_io_write(), HDPROreg_IO8, iop_sys_clock_t::hi, iop_sys_clock_t::lo, M_PRINTF, NULL, resume_intr(), sec_ctrl_cmd_table, SEC_CTRL_CMD_TABLE_SIZE, select, SetAlarm(), smart_cmd_table, SMART_CMD_TABLE_SIZE, SPD_INTR_ATA0, suspend_intr(), ata_cmd_info_t::type, ata_cmd_state_t::type, USE_ATA_REGS, and USec2SysClock().
Referenced by ata_device_flush_cache(), ata_device_identify(), ata_device_idle(), ata_device_sector_io(), ata_device_set_transfer_mode(), and ata_device_smart_enable().
ata_pio_transfer()
static int ata_pio_transfer (ata_cmd_state_t * cmd_state) static
Definition at line 557 of file hdproatad.c.
 {
         u8 *buf8;
         u16 *buf16;
         int i, type;
         int res = 0, chk = 0;
         u16 status = hdpro_io_read(ATAreg_STATUS_RD);
         if (status & ATA_STAT_ERR) {
                 M_PRINTF("Error: Command error: status 0x%02x, error 0x%02x.\n", status, ata_get_error());
                 return ATA_RES_ERR_IO;
         }
         /* DRQ must be set (data request).  */
         if (!(status & ATA_STAT_DRQ))
                 return ATA_RES_ERR_NODATA;
         type = cmd_state->type;
         if (type == 3 || type == 8) {
                 /* PIO data out */
                 buf16 = cmd_state->buf16;
                 HDPROreg_IO8 = 0x43;
                 CDVDreg_STATUS = 0;
                 for (i = 0; i < 256; i++) {
                         u16 r_data = *buf16;
                         hdpro_io_write(ATAreg_DATA_WR, r_data);
                         chk ^= r_data + i;
                         cmd_state->buf = ++buf16;
                 }
                 u16 out = hdpro_io_read(ATAreg_DATA_RD) & 0xffff;
                 if (out != (chk & 0xffff))
                         return ATA_RES_ERR_IO;
                 if (cmd_state->type == 8) {
                         buf8 = cmd_state->buf8;
                         for (i = 0; i < 4; i++) {
                                 hdpro_io_write(ATAreg_DATA_WR, *buf8);
                                 cmd_state->buf = ++buf8;
                         }
                 }
         } else if (type == 2) {
                 /* PIO data in  */
                 buf16 = cmd_state->buf16;
                 suspend_intr();
                 HDPROreg_IO8 = 0x53;
                 CDVDreg_STATUS = 0;
                 CDVDreg_STATUS = 0;
                 for (i = 0; i < 256; i++) {
                         unsigned int res0 = HDPROreg_IO8;
                         CDVDreg_STATUS = 0;
                         unsigned int res1 = HDPROreg_IO8;
                         CDVDreg_STATUS = 0;
                         res0 = (res0 & 0xff) | (res1 << 8);
                         chk ^= res0 + i;
                         *buf16 = res0 & 0xffff;
                         cmd_state->buf16 = ++buf16;
                 }
                 HDPROreg_IO8 = 0x51;
                 CDVDreg_STATUS = 0;
                 CDVDreg_STATUS = 0;
                 resume_intr();
                 u16 r_data = hdpro_io_read(ATAreg_DATA_RD) & 0xffff;
                 if (r_data != (chk & 0xffff))
                         return ATA_RES_ERR_IO;
         }
         return res;
 }
References ata_get_error(), ATA_RES_ERR_IO, ATA_RES_ERR_NODATA, ATA_STAT_DRQ, ATA_STAT_ERR, ATAreg_DATA_RD, ATAreg_DATA_WR, ATAreg_STATUS_RD, ata_cmd_state_t::buf, ata_cmd_state_t::buf16, ata_cmd_state_t::buf8, CDVDreg_STATUS, hdpro_io_read(), hdpro_io_write(), HDPROreg_IO8, M_PRINTF, resume_intr(), status, suspend_intr(), and ata_cmd_state_t::type.
Referenced by ata_io_finish().
ata_reset_devices()
int ata_reset_devices (void)
Definition at line 641 of file hdproatad.c.
 {
         if (hdpro_io_read(ATAreg_CONTROL_RD) & 0x80)
                 return ATA_RES_ERR_NOTREADY;
         /* Disables device interrupt assertion and asserts SRST. */
         hdpro_io_write(ATAreg_CONTROL_WR, 6);
         DelayThread(100);
         /* Disable ATA interrupts.  */
         hdpro_io_write(ATAreg_CONTROL_WR, 2);
         DelayThread(3000);
         return ata_wait_busy();
 }
References ATA_RES_ERR_NOTREADY, ata_wait_busy, ATAreg_CONTROL_RD, ATAreg_CONTROL_WR, DelayThread(), hdpro_io_read(), hdpro_io_write(), and USE_ATA_REGS.
Referenced by ata_init_devices().
gen_ata_wait_busy()
static int gen_ata_wait_busy (int bits) static
Definition at line 261 of file hdproatad.c.
 {
         int i, didx, delay;
         int res = 0;
         for (i = 0; i < 80; i++) {
                 hdpro_io_start();
                 u16 r_control = hdpro_io_read(ATAreg_CONTROL_RD);
                 hdpro_io_finish();
                 if (r_control == 0xffff)        //Differs from the normal ATAD here.
                         return ATA_RES_ERR_TIMEOUT;
                 if (!(r_control & bits))
                         goto out;
                 didx = i / 10;
                 switch (didx) {
                         case 0:
                                 continue;
                         case 1:
                                 delay = 100;
                                 break;
                         case 2:
                                 delay = 1000;
                                 break;
                         case 3:
                                 delay = 10000;
                                 break;
                         case 4:
                                 delay = 100000;
                                 break;
                         default:
                                 delay = 1000000;
                 }
                 DelayThread(delay);
         }
         res = ATA_RES_ERR_TIMEOUT;
         M_PRINTF("Timeout while waiting on busy (0x%02x).\n", bits);
 out:
         hdpro_io_start();
         return res;
 }
References ATA_RES_ERR_TIMEOUT, ATAreg_CONTROL_RD, DelayThread(), hdpro_io_finish(), hdpro_io_read(), hdpro_io_start(), and M_PRINTF.
hdpro_io_finish()
static int hdpro_io_finish (void) static
Definition at line 343 of file hdproatad.c.
 {
         if (!hdpro_io_active)
                 return 0;
         suspend_intr();
         // HD Pro IO finish commands sequence
         HDPROreg_IO8 = 0xf3;
         CDVDreg_STATUS = 0;
         resume_intr();
         DelayThread(200);
         if (HDPROreg_IO32 == 0x401a7800) // check the 1st in ROM0 seg get
                 hdpro_io_active = 0;     // back to it's original state
         return hdpro_io_active ^ 1;
 }
References CDVDreg_STATUS, DelayThread(), hdpro_io_active, HDPROreg_IO32, HDPROreg_IO8, resume_intr(), and suspend_intr().
Referenced by _start(), ata_device_flush_cache(), ata_device_sector_io(), ata_get_devinfo(), and gen_ata_wait_busy().
hdpro_io_read()
static int hdpro_io_read (u8 cmd) static
Definition at line 379 of file hdproatad.c.
 {
         suspend_intr();
         // IO read from HD Pro
         HDPROreg_IO8 = cmd;
         CDVDreg_STATUS = 0;
         unsigned int res0 = HDPROreg_IO8;
         CDVDreg_STATUS = 0;
         unsigned int res1 = HDPROreg_IO8;
         CDVDreg_STATUS = 0;
         res0 = (res0 & 0xff) | (res1 << 8);
         resume_intr();
         return res0 & 0xffff;
 }
References CDVDreg_STATUS, HDPROreg_IO8, resume_intr(), and suspend_intr().
Referenced by ata_device_probe(), ata_device_select(), ata_get_error(), ata_init_devices(), ata_io_finish(), ata_io_start(), ata_pio_transfer(), ata_reset_devices(), and gen_ata_wait_busy().
hdpro_io_start()
static int hdpro_io_start (void) static
Definition at line 314 of file hdproatad.c.
 {
         if (hdpro_io_active)
                 return 0;
         hdpro_io_active = 0;
         suspend_intr();
         // HD Pro IO start commands sequence
         HDPROreg_IO8 = 0x72;
         CDVDreg_STATUS = 0;
         HDPROreg_IO8 = 0x34;
         CDVDreg_STATUS = 0;
         HDPROreg_IO8 = 0x61;
         CDVDreg_STATUS = 0;
         unsigned int res = HDPROreg_IO8;
         CDVDreg_STATUS = 0;
         resume_intr();
         // check result
         if ((res & 0xff) == 0xe7)
                 hdpro_io_active = 1;
         return hdpro_io_active;
 }
References CDVDreg_STATUS, hdpro_io_active, HDPROreg_IO8, resume_intr(), and suspend_intr().
Referenced by _start(), ata_device_flush_cache(), ata_device_sector_io(), ata_get_devinfo(), and gen_ata_wait_busy().
hdpro_io_write()
static void hdpro_io_write (u8 cmd, u16 val) static
Definition at line 364 of file hdproatad.c.
 {
         suspend_intr();
         // IO write to HD Pro
         HDPROreg_IO8 = cmd;
         CDVDreg_STATUS = 0;
         HDPROreg_IO8 = val;
         CDVDreg_STATUS = 0;
         HDPROreg_IO8 = (val & 0xffff) >> 8;
         CDVDreg_STATUS = 0;
         resume_intr();
 }
References CDVDreg_STATUS, HDPROreg_IO8, resume_intr(), and suspend_intr().
Referenced by ata_device_probe(), ata_device_select(), ata_io_start(), ata_pio_transfer(), and ata_reset_devices().
IRX_ID()
IRX_ID (MODNAME , 1 , 1)
resume_intr()
static void resume_intr (void) static
Definition at line 195 of file hdproatad.c.
 {
         if (intr_suspended) {
                 CpuResumeIntr(intr_state);
                 intr_suspended = 0;
         }
 }
References CpuResumeIntr(), intr_state, and intr_suspended.
Referenced by ata_bus_reset(), ata_io_finish(), ata_io_start(), ata_pio_transfer(), hdpro_io_finish(), hdpro_io_read(), hdpro_io_start(), and hdpro_io_write().
shutdown()
int shutdown (void)
Definition at line 242 of file hdproatad.c.
 {
         return 0;
 }
suspend_intr()
static void suspend_intr (void) static
Definition at line 186 of file hdproatad.c.
 {
         if (!intr_suspended) {
                 CpuSuspendIntr(&intr_state);
                 intr_suspended = 1;
         }
 }
References CpuSuspendIntr(), intr_state, and intr_suspended.
Referenced by ata_bus_reset(), ata_io_finish(), ata_io_start(), ata_pio_transfer(), hdpro_io_finish(), hdpro_io_read(), hdpro_io_start(), and hdpro_io_write().
Variable Documentation
_exp_atad
struct irx_export_table _exp_atad extern
Referenced by _start().
ata_cmd_table
const ata_cmd_info_t ata_cmd_table[] static
Definition at line 88 of file hdproatad.c.
Referenced by ata_io_start().
ata_devinfo_init
int ata_devinfo_init = 0 static
Definition at line 71 of file hdproatad.c.
Referenced by ata_get_devinfo().
ata_evflg
int ata_evflg = -1 static
Definition at line 72 of file hdproatad.c.
Referenced by _start(), ata_alarm_cb(), ata_io_finish(), and ata_io_start().
ata_param
u16 ata_param[256] static
Definition at line 79 of file hdproatad.c.
Referenced by ata_init_devices().
atad_cmd_state
ata_cmd_state_t atad_cmd_state static
Definition at line 164 of file hdproatad.c.
Referenced by ata_io_finish(), and ata_io_start().
atad_devinfo
ata_devinfo_t atad_devinfo[2] static
Definition at line 75 of file hdproatad.c.
Referenced by ata_device_flush_cache(), ata_device_sector_io(), ata_get_devinfo(), ata_init_devices(), and ata_io_start().
hdpro_io_active
int hdpro_io_active = 0 static
Definition at line 166 of file hdproatad.c.
Referenced by hdpro_io_finish(), and hdpro_io_start().
intr_state
int intr_state static
Definition at line 168 of file hdproatad.c.
Referenced by resume_intr(), and suspend_intr().
intr_suspended
int intr_suspended = 0 static
Definition at line 167 of file hdproatad.c.
Referenced by resume_intr(), and suspend_intr().
smart_cmd_table
const ata_cmd_info_t smart_cmd_table[] static
Initial value:
= {
        {ATA_S_SMART_READ_DATA,2},
        {ATA_S_SMART_ENABLE_DISABLE_AUTOSAVE,1},
        {ATA_S_SMART_SAVE_ATTRIBUTE_VALUES,1},
        {ATA_S_SMART_EXECUTE_OFF_LINE,1},
        {ATA_S_SMART_READ_LOG,2},
        {ATA_S_SMART_WRITE_LOG,3},
        {ATA_S_SMART_ENABLE_OPERATIONS,1},
        {ATA_S_SMART_DISABLE_OPERATIONS,1},
        {ATA_S_SMART_RETURN_STATUS,1}
}
Definition at line 140 of file hdproatad.c.
Referenced by ata_io_start().