ps2sdk: iop/usb/usbd/src/hub.h File Reference
hub.h File Reference
#include "usbdpriv.h"
Functions
int removeEndpointFromDevice (Device *dev, Endpoint *ep)
int initHubDriver (void)
void flushPort (Device *dev)
int addTimerCallback (TimerCbStruct *arg, TimerCallback func, void *cbArg, u32 delay)
int hubResetDevice (Device *dev)
int hubTimedSetFuncAddress (Device *dev)
Detailed Description
USB Driver function prototypes and constants.
Definition in file hub.h.
Function Documentation
addTimerCallback()
int addTimerCallback (TimerCbStruct * arg, TimerCallback func, void * cbArg, u32 delay)
Definition at line 178 of file hub.c.
{
         if (arg->isActive)
                 return -1;
         arg->isActive = 1;
         arg->callbackProc = func;
         arg->callbackArg  = cbArg;
         TimerCbStruct *pos = memPool.timerListStart;
         while (pos && (delay > pos->delayCount)) {
                 delay -= pos->delayCount;
                 pos = pos->next;
         }
         if (pos) {
                 arg->prev = pos->prev;
                 if (pos->prev)
                         pos->prev->next = arg;
                 else
                         memPool.timerListStart = arg;
                 arg->next = pos;
                 pos->prev = arg;
                 pos->delayCount -= delay;
         } else {
                 arg->prev = memPool.timerListEnd;
                 if (memPool.timerListEnd)
                         memPool.timerListEnd->next = arg;
                 else
                         memPool.timerListStart = arg;
                 memPool.timerListEnd = arg;
                 arg->next = NULL;
         }
         arg->delayCount = delay;
         memPool.ohciRegs->HcInterruptEnable = OHCI_INT_SF;
         return 0;
 }
References arg, OhciRegs::HcInterruptEnable, memPool, NULL, OHCI_INT_SF, MemoryPool::ohciRegs, pos, MemoryPool::timerListEnd, and MemoryPool::timerListStart.
Referenced by handleRhsc(), hubGetPortStatusCallback(), hubSetFuncAddressCB(), hubTimedSetFuncAddress(), and removeEndpointFromDevice().
flushPort()
void flushPort (Device * dev)
Definition at line 345 of file hub.c.
{
         Device *child;
         if (dev->deviceStatus != DEVICE_NOTCONNECTED) {
                 dev->deviceStatus = DEVICE_NOTCONNECTED;
                 if (dev->devDriver) {
                         callUsbDriverFunc(dev->devDriver->disconnect, dev->id, dev->devDriver->gp);
                         dev->devDriver = NULL;
                 }
                 if (dev->timer.isActive)
                         cancelTimerCallback(&dev->timer);
                 while (dev->endpointListStart)
                         removeEndpointFromDevice(dev, dev->endpointListStart);
                 while ((child = dev->childListStart)) {
                         if (child->next)
                                 child->next->prev = child->prev;
                         else
                                 dev->childListEnd = child->prev;
                         if (child->prev)
                                 child->prev->next = child->next;
                         else
                                 dev->childListStart = child->next;
                         flushPort(child);
                         freeDevice(child);
                 }
                 dev->ioRequest.busyFlag = 0;
                 dev->privDataField = NULL;
         }
         if (dev->resetFlag)
                 checkDelayedResets(dev);
 }
References IoRequest::busyFlag, callUsbDriverFunc(), cancelTimerCallback(), checkDelayedResets(), Device::childListEnd, Device::childListStart, Device::devDriver, DEVICE_NOTCONNECTED, Device::deviceStatus, sceUsbdLddOps::disconnect, Device::endpointListStart, freeDevice(), sceUsbdLddOps::gp, Device::id, Device::ioRequest, TimerCbStruct::isActive, Device::next, NULL, Device::prev, Device::privDataField, removeEndpointFromDevice(), Device::resetFlag, and Device::timer.
Referenced by handleRhsc(), and hubGetPortStatusCallback().
hubResetDevice()
int hubResetDevice (Device * dev)
Definition at line 294 of file hub.c.
{
         UsbHub *hub;
         if (memPool.delayResets) {
                 dev->deviceStatus = DEVICE_RESETDELAYED;
                 return 0;
         } else {
                 memPool.delayResets = 1;
                 dev->deviceStatus = DEVICE_RESETPENDING;
                 dev->resetFlag = 1;
                 if (dev->parent == memPool.deviceTreeRoot) { // root hub port
                         memPool.ohciRegs->HcRhPortStatus[dev->attachedToPortNo - 1] = BIT(PORT_RESET);
                 } else { // normal hub port
                         hub = (UsbHub *)dev->parent->privDataField;
                         hub->hubStatusCounter = dev->attachedToPortNo;
                         HubControlTransfer(hub,
                                 USB_DIR_OUT | USB_RT_PORT, USB_REQ_SET_FEATURE, PORT_RESET, dev->attachedToPortNo, 0, NULL,
                                 hubDeviceResetCallback);
                 }
                 return 1;
         }
 }
References Device::attachedToPortNo, BIT, MemoryPool::delayResets, DEVICE_RESETDELAYED, DEVICE_RESETPENDING, Device::deviceStatus, MemoryPool::deviceTreeRoot, OhciRegs::HcRhPortStatus, HubControlTransfer(), hubDeviceResetCallback(), UsbHub::hubStatusCounter, memPool, NULL, MemoryPool::ohciRegs, Device::parent, PORT_RESET, Device::resetFlag, USB_DIR_OUT, USB_REQ_SET_FEATURE, and USB_RT_PORT.
Referenced by checkDelayedResetsTree(), handleRhsc(), hubGetPortStatusCallback(), and killDevice().
hubTimedSetFuncAddress()
int hubTimedSetFuncAddress (Device * dev)
Definition at line 489 of file hub.c.
{
         dev->functionDelay = 20;
         addTimerCallback(&dev->timer, (TimerCallback)hubSetFuncAddress, dev->endpointListStart, 20);
         return 0;
 }
References addTimerCallback(), Device::endpointListStart, Device::functionDelay, hubSetFuncAddress(), and Device::timer.
Referenced by handleRhsc(), and hubGetPortStatusCallback().
initHubDriver()
int initHubDriver (void)
Definition at line 43 of file hub.c.
{
         int i;
         UsbHub *hub;
         u32 needMem = usbConfig.maxHubDevices * sizeof(UsbHub);
         hubBufferList = (UsbHub *)AllocSysMemory(ALLOC_FIRST, needMem, 0);
         if (!hubBufferList) {
                 dbg_printf("ERROR: unable to alloc hub buffer\n");
                 return -1;
         }
         memset(hubBufferList, 0, needMem);
         hub = hubBufferList;
         for (i = 0; i < usbConfig.maxHubDevices - 1; i++) {
                 hub->next = hub + 1;
                 hub++;
         }
         hub->next = NULL;
         doRegisterDriver(&HubDriver, &_gp);
         return 0;
 }
References _gp, ALLOC_FIRST, AllocSysMemory(), dbg_printf, doRegisterDriver(), hubBufferList, HubDriver, UsbdConfig::maxHubDevices, memset(), UsbHub::next, NULL, and usbConfig.
Referenced by hcdInit().
removeEndpointFromDevice()
int removeEndpointFromDevice (Device * dev, Endpoint * ep)
Definition at line 268 of file hub.c.
{
         ep->hcEd.hcArea |= HCED_SKIP;
         removeHcEdFromList(ep->endpointType, &ep->hcEd);
         if (ep->next)
                 ep->next->prev = ep->prev;
         else
                 dev->endpointListEnd = ep->prev;
         if (ep->prev)
                 ep->prev->next = ep->next;
         else
                 dev->endpointListStart = ep->next;
         ep->correspDevice = NULL;
         addTimerCallback(&ep->timer, (TimerCallback)killEndpoint, ep, 200);
         return 0;
 }
References addTimerCallback(), Endpoint::correspDevice, Device::endpointListEnd, Device::endpointListStart, Endpoint::endpointType, HcED::hcArea, Endpoint::hcEd, HCED_SKIP, killEndpoint(), Endpoint::next, NULL, Endpoint::prev, removeHcEdFromList(), and Endpoint::timer.
Referenced by disconnectDriver(), doCloseEndpoint(), flushPort(), and killDevice().