ps2sdk: iop/iLink/IEEE1394_bd/src/include/sbp2_disk.h File Reference
sbp2_disk.h File Reference
#include <tamtypes.h>
#include "scsi.h"
Data Structures
struct sbp2_status
struct sbp2_pointer
struct sbp2_ORB_pointer
struct sbp2_login_response
struct management_ORB
struct CommandDescriptorBlock
struct SBP2Device
Macros
#define XFER_BLOCK_SIZE
#define READ_TRANSACTION 0
#define WRITE_TRANSACTION 1
#define CDB_PAGE_SIZE(v) ((v) << 16) /* Not in use. */
#define CDB_PAGE_TABLE_PRESENT(v) ((v) << 19) /* Not in use. */
#define CDB_MAX_PAYLOAD(v) ((v) << 20)
#define CDB_SPEED(v) ((v) << 24)
#define CDB_DIRECTION(v) ((v) << 27)
#define CDB_DATA_SIZE(v) ((v))
#define WRITE_REQ_INCOMING 1
#define READ_REQ_INCOMING 2
#define BUS_RESET_COMPLETE 4
#define ERROR_TIME_OUT 8
#define SBP2_LOGIN_REQUEST 0x0
#define SBP2_QUERY_LOGINS_REQUEST 0x1
#define SBP2_RECONNECT_REQUEST 0x3
#define SBP2_SET_PASSWORD_REQUEST 0x4
#define SBP2_LOGOUT_REQUEST 0x7
#define SBP2_ABORT_TASK_REQUEST 0xb
#define SBP2_ABORT_TASK_SET 0xc
#define SBP2_LOGICAL_UNIT_RESET 0xe
#define SBP2_TARGET_RESET_REQUEST 0xf
#define IEEE1394_CROM_LOGICAL_UNIT_NUM 0x14
#define IEEE1394_CROM_UNIT_CHARA 0x3A
#define IEEE1394_CROM_CSR_OFFSET 0x54
#define IEEE1394_CROM_UNIT_DIRECTORY 0xD1
#define MANAGEMENT_ORB_LOGINID(v) ((v))
#define MANAGEMENT_ORB_LUN(v) ((v))
#define MANAGEMENT_ORB_FUNCTION(v) ((v) << 16)
#define MANAGEMENT_ORB_RECONNECT(v) ((v) << 20)
#define MANAGEMENT_ORB_EXCLUSIVE(v) ((v) ? 1 << 28 : 0)
#define ORB_REQUEST_FORMAT(v) ((v) << 29)
#define ORB_NOTIFY ((1) << 31)
#define MANAGEMENT_ORB_RESPONSE_LENGTH(v) ((v)&0x0000FFFF)
#define MANAGEMENT_ORB_PASSWORD_LENGTH(v) ((v) << 16)
#define NULL_POINTER (1<<15)
#define RESP_SBP_STATUS(v) (((v)>>16)&0xFF)
#define RESP_LEN(v) (((v)>>24)&0x07)
#define RESP_DEAD(v) (((v)>>27)&0x01)
#define RESP_RESP(v) (((v)>>28)&0x03)
#define RESP_SRC(v) (((v)>>30)&0x03)
Functions
void init_ieee1394DiskDriver (void)
int ieee1394_SendCommandBlockORB (struct SBP2Device *dev, struct CommandDescriptorBlock *firstCDB)
int ieee1394_Sync (void)
void DeinitIEEE1394 (void)
Macro Definition Documentation
BUS_RESET_COMPLETE
#define BUS_RESET_COMPLETE 4
Definition at line 25 of file sbp2_disk.h.
CDB_DATA_SIZE
#define CDB_DATA_SIZE (v) ((v))
Definition at line 20 of file sbp2_disk.h.
CDB_DIRECTION
#define CDB_DIRECTION (v) ((v) << 27)
Definition at line 19 of file sbp2_disk.h.
CDB_MAX_PAYLOAD
#define CDB_MAX_PAYLOAD (v) ((v) << 20)
Definition at line 17 of file sbp2_disk.h.
CDB_PAGE_SIZE
#define CDB_PAGE_SIZE (v) ((v) << 16) /* Not in use. */
Definition at line 15 of file sbp2_disk.h.
CDB_PAGE_TABLE_PRESENT
#define CDB_PAGE_TABLE_PRESENT (v) ((v) << 19) /* Not in use. */
Definition at line 16 of file sbp2_disk.h.
CDB_SPEED
#define CDB_SPEED (v) ((v) << 24)
Definition at line 18 of file sbp2_disk.h.
ERROR_TIME_OUT
#define ERROR_TIME_OUT 8
Definition at line 26 of file sbp2_disk.h.
IEEE1394_CROM_CSR_OFFSET
#define IEEE1394_CROM_CSR_OFFSET 0x54
Definition at line 42 of file sbp2_disk.h.
IEEE1394_CROM_LOGICAL_UNIT_NUM
#define IEEE1394_CROM_LOGICAL_UNIT_NUM 0x14
Definition at line 40 of file sbp2_disk.h.
IEEE1394_CROM_UNIT_CHARA
#define IEEE1394_CROM_UNIT_CHARA 0x3A
Definition at line 41 of file sbp2_disk.h.
IEEE1394_CROM_UNIT_DIRECTORY
#define IEEE1394_CROM_UNIT_DIRECTORY 0xD1
Definition at line 43 of file sbp2_disk.h.
MANAGEMENT_ORB_EXCLUSIVE
#define MANAGEMENT_ORB_EXCLUSIVE (v) ((v) ? 1 << 28 : 0)
Definition at line 50 of file sbp2_disk.h.
MANAGEMENT_ORB_FUNCTION
#define MANAGEMENT_ORB_FUNCTION (v) ((v) << 16)
Definition at line 48 of file sbp2_disk.h.
MANAGEMENT_ORB_LOGINID
#define MANAGEMENT_ORB_LOGINID (v) ((v))
Definition at line 46 of file sbp2_disk.h.
MANAGEMENT_ORB_LUN
#define MANAGEMENT_ORB_LUN (v) ((v))
Definition at line 47 of file sbp2_disk.h.
MANAGEMENT_ORB_PASSWORD_LENGTH
#define MANAGEMENT_ORB_PASSWORD_LENGTH (v) ((v) << 16)
Definition at line 56 of file sbp2_disk.h.
MANAGEMENT_ORB_RECONNECT
#define MANAGEMENT_ORB_RECONNECT (v) ((v) << 20)
Definition at line 49 of file sbp2_disk.h.
MANAGEMENT_ORB_RESPONSE_LENGTH
#define MANAGEMENT_ORB_RESPONSE_LENGTH (v) ((v)&0x0000FFFF)
Definition at line 55 of file sbp2_disk.h.
NULL_POINTER
#define NULL_POINTER (1<<15)
Definition at line 58 of file sbp2_disk.h.
ORB_NOTIFY
#define ORB_NOTIFY ((1) << 31)
Definition at line 53 of file sbp2_disk.h.
ORB_REQUEST_FORMAT
#define ORB_REQUEST_FORMAT (v) ((v) << 29)
Definition at line 52 of file sbp2_disk.h.
READ_REQ_INCOMING
#define READ_REQ_INCOMING 2
Definition at line 24 of file sbp2_disk.h.
READ_TRANSACTION
#define READ_TRANSACTION 0
Definition at line 11 of file sbp2_disk.h.
RESP_DEAD
#define RESP_DEAD (v) (((v)>>27)&0x01)
Definition at line 62 of file sbp2_disk.h.
RESP_LEN
#define RESP_LEN (v) (((v)>>24)&0x07)
Definition at line 61 of file sbp2_disk.h.
RESP_RESP
#define RESP_RESP (v) (((v)>>28)&0x03)
Definition at line 63 of file sbp2_disk.h.
RESP_SBP_STATUS
#define RESP_SBP_STATUS (v) (((v)>>16)&0xFF)
Definition at line 60 of file sbp2_disk.h.
RESP_SRC
#define RESP_SRC (v) (((v)>>30)&0x03)
Definition at line 64 of file sbp2_disk.h.
SBP2_ABORT_TASK_REQUEST
#define SBP2_ABORT_TASK_REQUEST 0xb
Definition at line 34 of file sbp2_disk.h.
SBP2_ABORT_TASK_SET
#define SBP2_ABORT_TASK_SET 0xc
Definition at line 35 of file sbp2_disk.h.
SBP2_LOGICAL_UNIT_RESET
#define SBP2_LOGICAL_UNIT_RESET 0xe
Definition at line 36 of file sbp2_disk.h.
SBP2_LOGIN_REQUEST
#define SBP2_LOGIN_REQUEST 0x0
Definition at line 29 of file sbp2_disk.h.
SBP2_LOGOUT_REQUEST
#define SBP2_LOGOUT_REQUEST 0x7
Definition at line 33 of file sbp2_disk.h.
SBP2_QUERY_LOGINS_REQUEST
#define SBP2_QUERY_LOGINS_REQUEST 0x1
Definition at line 30 of file sbp2_disk.h.
SBP2_RECONNECT_REQUEST
#define SBP2_RECONNECT_REQUEST 0x3
Definition at line 31 of file sbp2_disk.h.
SBP2_SET_PASSWORD_REQUEST
#define SBP2_SET_PASSWORD_REQUEST 0x4
Definition at line 32 of file sbp2_disk.h.
SBP2_TARGET_RESET_REQUEST
#define SBP2_TARGET_RESET_REQUEST 0xf
Definition at line 37 of file sbp2_disk.h.
WRITE_REQ_INCOMING
#define WRITE_REQ_INCOMING 1
Definition at line 23 of file sbp2_disk.h.
WRITE_TRANSACTION
#define WRITE_TRANSACTION 1
Definition at line 12 of file sbp2_disk.h.
XFER_BLOCK_SIZE
#define XFER_BLOCK_SIZE
Value:
                                                65024   /* 65536-512. It seems like my Oxford 934 is capable of maximum transfers of less than 65536 bytes.
                                                NOTE: I reduced the maximum block size here by 512, since transfers are done in (smallest) groups of 512 bytes!
                                */
Definition at line 9 of file sbp2_disk.h.
Function Documentation
DeinitIEEE1394()
void DeinitIEEE1394 (void)
Definition at line 643 of file sbp2_driver.c.
 {
     TerminateThread(iLinkIntrCBThreadID);
     DeleteThread(iLinkIntrCBThreadID);
     DeleteEventFlag(sbp2_event_flag);
 }
References DeleteEventFlag(), DeleteThread(), iLinkIntrCBThreadID, sbp2_event_flag, and TerminateThread().
ieee1394_SendCommandBlockORB()
int ieee1394_SendCommandBlockORB (struct SBP2Device * dev, struct CommandDescriptorBlock * firstCDB)
Definition at line 481 of file sbp2_driver.c.
 {
     int result, retries;
     struct sbp2_pointer address;
     memset((void*)&statusFIFO, 0, sizeof(statusFIFO));
     address.low    = (u32)firstCDB;
     address.NodeID = dev->InitiatorNodeID;
     address.high   = 0;
     retries = 0;
     /* Write the pointer to the first ORB in the fetch agent's NEXT_ORB register. */
     while ((result = iLinkTrWrite(dev->trContext, dev->CommandBlockAgent_high, dev->CommandBlockAgent_low + 0x08, &address, 8)) < 0) {
         M_DEBUG("Error writing to the Fetch Agent's ORB_POINTER register @ 0x%08lx %08lx. Code: %d.\n", dev->CommandBlockAgent_high, dev->CommandBlockAgent_low + 0x08, result);
         DelayThread(200000);
         ieee1394_ResetFetchAgent(dev);
         retries++;
         if (retries > 3)
             return (-1);
     }
 #if 0
         /* Write a value to the fetch agent's DOORBELL register. */
         result=1;
         if((result=iLinkTrWrite(dev->trContext, dev->CommandBlockAgent_high, dev->CommandBlockAgent_low+0x10, &result, 4))<0){
                 M_DEBUG("Error writing to the Fetch Agent's DOORBELL register @ 0x%08lx %08lx. Code: %d.\n", dev->CommandBlockAgent_high, dev->CommandBlockAgent_low+0x10, result);
                 return -2;
         }
 #endif
     return 1;
 }
References SBP2Device::CommandBlockAgent_high, SBP2Device::CommandBlockAgent_low, DelayThread(), sbp2_pointer::high, ieee1394_ResetFetchAgent(), iLinkTrWrite(), SBP2Device::InitiatorNodeID, sbp2_pointer::low, M_DEBUG, memset(), sbp2_pointer::NodeID, result, statusFIFO, and SBP2Device::trContext.
Referenced by scsiInquiry(), scsiReadSector(), scsiRequestSense(), scsiStartStopUnit(), scsiTestUnitReady(), and scsiWriteSector().
ieee1394_Sync()
int ieee1394_Sync (void)
Definition at line 632 of file sbp2_driver.c.
 {
     //  WaitEventFlag(sbp2_event_flag, WRITE_REQ_INCOMING, WEF_AND|WEF_CLEAR, NULL);
     while (RESP_SRC(statusFIFO.status.status) == 0) {
         DelayThread(50);
     };
     return (ProcessStatus());
 }
References DelayThread(), ProcessStatus(), RESP_SRC, and statusFIFO.
Referenced by scsiInquiry(), scsiReadSector(), scsiRequestSense(), scsiStartStopUnit(), scsiTestUnitReady(), and scsiWriteSector().
init_ieee1394DiskDriver()
void init_ieee1394DiskDriver (void)
Definition at line 85 of file sbp2_driver.c.
 {
     int i;
     for (i = 0; i < MAX_DEVICES; i++) {
         SBP2Devices[i].IsConnected = 0;
         SBP2Devices[i].nodeID      = 0;
         SBP2Devices[i].trContext   = (-1);
         SBP2Devices[i].scsi.priv        = &SBP2Devices[i];
         SBP2Devices[i].scsi.name        = "sd";
         SBP2Devices[i].scsi.max_sectors = XFER_BLOCK_SIZE / 512;
         SBP2Devices[i].scsi.get_max_lun = sbp2_get_max_lun;
         SBP2Devices[i].scsi.queue_cmd   = sbp2_queue_cmd;
     }
     writeBuffer = malloc(XFER_BLOCK_SIZE);
     sbp2_event_flag = CreateEventFlag(&evfp);
     M_DEBUG("Starting threads..\n");
     threadData.thread   = &iLinkIntrCBHandlingThread;
     iLinkIntrCBThreadID = CreateThread(&threadData);
     StartThread(iLinkIntrCBThreadID, NULL);
     iLinkSetTrCallbackHandler(&ieee1394_callback);
     M_DEBUG("Threads created and started.\n");
     iLinkEnableSBus();
 }
References CreateEventFlag(), CreateThread(), evfp, scsi_interface::get_max_lun, ieee1394_callback(), iLinkEnableSBus(), iLinkIntrCBHandlingThread(), iLinkIntrCBThreadID, iLinkSetTrCallbackHandler(), SBP2Device::IsConnected, M_DEBUG, malloc(), MAX_DEVICES, scsi_interface::max_sectors, scsi_interface::name, SBP2Device::nodeID, NULL, scsi_interface::priv, scsi_interface::queue_cmd, sbp2_event_flag, sbp2_get_max_lun(), sbp2_queue_cmd(), SBP2Devices, SBP2Device::scsi, StartThread(), iop_thread_t::thread, threadData, SBP2Device::trContext, writeBuffer, and XFER_BLOCK_SIZE.
Referenced by _start().