ps2sdk: iop/iLink/iLinkman/src/iLink_PHY.c File Reference
iLink_PHY.c File Reference
#include <thbase.h>
#include "iLinkman.h"
#include "iLink_internal.h"
Macros
#define RdPhy 0x80000000
#define WrPhy 0x40000000
Functions
static void iLinkPhySync (void)
unsigned char iLinkReadPhy (unsigned char address)
void iLinkWritePhy (unsigned char address, unsigned char data)
void iLinkPHY_SetRootBit (int isRoot)
void iLinkPHY_SetGapCount (unsigned char GapCount)
void iLinkPHY_SetLCTRL (int LCTRL_status)
void iLinkPHYBusReset (void)
Variables
struct ILINKMemMap * ILINKRegisterBase
Macro Definition Documentation
RdPhy
#define RdPhy 0x80000000
Definition at line 15 of file iLink_PHY.c.
WrPhy
#define WrPhy 0x40000000
Definition at line 16 of file iLink_PHY.c.
Function Documentation
iLinkPHY_SetGapCount()
void iLinkPHY_SetGapCount (unsigned char GapCount)
Definition at line 47 of file iLink_PHY.c.
{
         iLinkWritePhy(1, (iLinkReadPhy(1)&0xC0)|GapCount);
 }
References iLinkReadPhy(), and iLinkWritePhy().
iLinkPHY_SetLCTRL()
void iLinkPHY_SetLCTRL (int LCTRL_status)
Definition at line 51 of file iLink_PHY.c.
{
         unsigned short int Register04value;
         Register04value=iLinkReadPhy(4);
         if(LCTRL_status) Register04value|=REG04_LCTRL;
         else Register04value&=(~REG04_LCTRL);
         iLinkWritePhy(4, Register04value);
 }
References iLinkReadPhy(), iLinkWritePhy(), and REG04_LCTRL.
Referenced by iLinkEnableSBus(), and iLinkHWInitialize().
iLinkPHY_SetRootBit()
void iLinkPHY_SetRootBit (int isRoot)
Definition at line 37 of file iLink_PHY.c.
{
         unsigned short int Register01value;
         Register01value=iLinkReadPhy(1);
         if(isRoot) Register01value|=REG01_RHB;
         else Register01value&=(~REG01_RHB);
         iLinkWritePhy(1, Register01value);
 }
References iLinkReadPhy(), iLinkWritePhy(), and REG01_RHB.
iLinkPHYBusReset()
void iLinkPHYBusReset (void)
Definition at line 61 of file iLink_PHY.c.
{
         iLinkWritePhy(5, iLinkReadPhy(5)|REG05_ISBR);
 }
References iLinkReadPhy(), iLinkWritePhy(), and REG05_ISBR.
Referenced by iLinkIntrHandler(), and iLinkResetSBus().
iLinkPhySync()
static void iLinkPhySync (void) static
Definition at line 18 of file iLink_PHY.c.
{
         while(ILINKRegisterBase->PHYAccess&(RdPhy|WrPhy)){};
 }
References ILINKRegisterBase, ILINKMemMap::PHYAccess, RdPhy, and WrPhy.
Referenced by iLinkReadPhy(), and iLinkWritePhy().
iLinkReadPhy()
unsigned char iLinkReadPhy (unsigned char address)
Definition at line 22 of file iLink_PHY.c.
{
         ILINKRegisterBase->PHYAccess=(((unsigned int)address)<<24)|RdPhy;
         iLinkPhySync();
         while(!(ILINKRegisterBase->intr0&iLink_INTR0_PhyRRx)){};
         ILINKRegisterBase->intr0=iLink_INTR0_PhyRRx;
         return(ILINKRegisterBase->PHYAccess&0xFF);
 }
References iLink_INTR0_PhyRRx, iLinkPhySync(), ILINKRegisterBase, ILINKMemMap::intr0, ILINKMemMap::PHYAccess, and RdPhy.
Referenced by iLinkHWInitialize(), iLinkPHY_SetGapCount(), iLinkPHY_SetLCTRL(), iLinkPHY_SetRootBit(), and iLinkPHYBusReset().
iLinkWritePhy()
void iLinkWritePhy (unsigned char address, unsigned char data)
Definition at line 32 of file iLink_PHY.c.
{
         ILINKRegisterBase->PHYAccess=(((unsigned int)address)<<24)|(((unsigned int)data)<<16)|WrPhy;
         iLinkPhySync();
 }
References iLinkPhySync(), ILINKRegisterBase, ILINKMemMap::PHYAccess, and WrPhy.
Referenced by iLinkHWInitialize(), iLinkPHY_SetGapCount(), iLinkPHY_SetLCTRL(), iLinkPHY_SetRootBit(), and iLinkPHYBusReset().
Variable Documentation
ILINKRegisterBase
struct ILINKMemMap* ILINKRegisterBase extern
Definition at line 31 of file iLink.c.
Referenced by iLinkPhySync(), iLinkReadPhy(), and iLinkWritePhy().