ps2sdk: iop/iLink/iLinkman/src/iLink.c File Reference
iLink.c File Reference
#include <dmacman.h>
#include <errno.h>
#include <ioman.h>
#include <intrman.h>
#include <irx.h>
#include <loadcore.h>
#include <stdio.h>
#include <thbase.h>
#include <thevent.h>
#include <thsemap.h>
#include <sysmem.h>
#include <sysclib.h>
#include "iLinkman.h"
#include "iLink_internal.h"
Macros
#define MODNAME "iLINK_HW_Manager"
Functions
IRX_ID (MODNAME, 0x00, 0x98)
int _start (int argc, char **argv)
int _exit (int argc, char **argv)
int iLinkTrAlloc (unsigned short int NodeID, unsigned char speed)
void iLinkTrFree (int trContext)
int iLinkTrWrite (int trContext, unsigned short int offset_high, unsigned int offset_low, void *buffer, unsigned int nBytes)
int iLinkTrRead (int trContext, unsigned short int offset_high, unsigned int offset_low, void *buffer, unsigned int nBytes)
unsigned int iLinkSetNodeCapabilities (unsigned int capabilities)
int iLinkGetGenerationNumber (void)
int iLinkGetLocalNodeID (void)
int iLinkGetNodeCount (void)
void iLinkEnableSBus (void)
void iLinkDisableSBus (void)
void iLinkResetSBus (void)
void * iLinkSetTrCallbackHandler (void *function)
int iLinkGetNodeTrSpeed (int trContext)
int iLinkSetNodeTrSpeed (int trContext, unsigned char speed)
u64 iLinkGetLocalNodeEUI64 (void)
Variables
struct irx_export_table _exp_iLinkman
struct ILINKMemMap * ILINKRegisterBase =(struct ILINKMemMap *)ILINK_REGISTER_BASE
struct TransactionContextData TransactionContexts [MAX_CONCURRENT_TRANSACTIONS]
unsigned int * ConfigurationROM
void(* CallBackFunction)(int reason, unsigned int offset, unsigned int size)
u64 ConsoleGUID
char ConsoleModelName [32]
unsigned short int LocalNodeID
int GenerationNumber
int nNodes
int NodeCapabilities
int IntrEventFlag
int UBUFTxSema
int UBUFThreadID
unsigned char IsBusRoot
static iop_event_t EventFlagData
static const unsigned char speeds [3]
Macro Definition Documentation
MODNAME
#define MODNAME "iLINK_HW_Manager"
Definition at line 25 of file iLink.c.
Function Documentation
_exit()
int _exit (int argc, char ** argv)
Definition at line 126 of file iLink.c.
{
         int result;
         /* Shutdown the hardware and unregister all registered library exports. */
         ReleaseLibraryEntries(&_exp_iLinkman);
         DisableIntr(IOP_IRQ_ILINK, &result);
         ReleaseIntrHandler(IOP_IRQ_ILINK);
         TerminateThread(UBUFThreadID);
         DeleteThread(UBUFThreadID);
         DeleteSema(UBUFTxSema);
         DeleteEventFlag(IntrEventFlag);
         iLinkShutdownHW();
         FreeSysMemory(ConfigurationROM);        /* Free the memory allocated for storing the configuration ROM. */
         return 0;
 }
References _exp_iLinkman, ConfigurationROM, DeleteEventFlag(), DeleteSema(), DeleteThread(), DisableIntr(), FreeSysMemory(), iLinkShutdownHW(), IntrEventFlag, IOP_IRQ_ILINK, ReleaseIntrHandler(), ReleaseLibraryEntries(), result, TerminateThread(), UBUFThreadID, and UBUFTxSema.
iLinkDisableSBus()
void iLinkDisableSBus (void)
Definition at line 206 of file iLink.c.
{
         ILINKRegisterBase->ctrl0&=~(iLink_CTRL0_RxEn|iLink_CTRL0_TxEn);         /* CTL0: ~(TxEn | RxEn) */
 }
References ILINKMemMap::ctrl0, iLink_CTRL0_RxEn, iLink_CTRL0_TxEn, and ILINKRegisterBase.
iLinkEnableSBus()
void iLinkEnableSBus (void)
Definition at line 200 of file iLink.c.
{
         iLinkPHY_SetLCTRL(1);
         iLinkBusEnable();
         iLinkResetSBus();
 }
References iLinkBusEnable(), iLinkPHY_SetLCTRL(), and iLinkResetSBus().
Referenced by init_ieee1394DiskDriver().
iLinkGetGenerationNumber()
int iLinkGetGenerationNumber (void)
Definition at line 188 of file iLink.c.
{
         return(GenerationNumber);
 }
References GenerationNumber.
Referenced by iLinkIntrCBHandlingThread().
iLinkGetLocalNodeEUI64()
u64 iLinkGetLocalNodeEUI64 (void)
Definition at line 266 of file iLink.c.
{
         return ConsoleGUID;
 }
References ConsoleGUID.
iLinkGetLocalNodeID()
int iLinkGetLocalNodeID (void)
Definition at line 192 of file iLink.c.
{
         return(LocalNodeID);
 }
References LocalNodeID.
Referenced by iLinkIntrCBHandlingThread().
iLinkGetNodeCount()
int iLinkGetNodeCount (void)
Definition at line 196 of file iLink.c.
{
         return(nNodes);
 }
References nNodes.
Referenced by iLinkIntrCBHandlingThread().
iLinkGetNodeTrSpeed()
int iLinkGetNodeTrSpeed (int trContext)
Definition at line 237 of file iLink.c.
{
         int CurrentSpeed, i;
         CurrentSpeed=-1;
         for(i=0; i<3; i++){
                 if(speeds[i]==TransactionContexts[trContext].speed){
                         CurrentSpeed=i;
                         break;
                 }
         }
         return CurrentSpeed;
 }
References TransactionContextData::speed, speeds, and TransactionContexts.
Referenced by iLinkIntrCBHandlingThread(), and iLinkSetNodeTrSpeed().
iLinkResetSBus()
void iLinkResetSBus (void)
Definition at line 210 of file iLink.c.
{
         ClearEventFlag(IntrEventFlag, ~(iLinkEventBusReady|iLinkEventGotSELFIDs));
         DEBUG_PRINTF("-=Reseting bus=-\n");
         iLinkPHYBusReset();
         DEBUG_PRINTF("-=Waiting for the serial bus to be ready=-\n");
         WaitEventFlag(IntrEventFlag, iLinkEventBusReady|iLinkEventGotSELFIDs, WEF_AND, NULL); /* Wait for the bus to be completely reset. */
         DEBUG_PRINTF("-=Bus reset and ready=-\n");
 }
References ClearEventFlag(), DEBUG_PRINTF, iLinkEventBusReady, iLinkEventGotSELFIDs, iLinkPHYBusReset(), IntrEventFlag, NULL, WaitEventFlag(), and WEF_AND.
Referenced by iLinkEnableSBus().
iLinkSetNodeCapabilities()
unsigned int iLinkSetNodeCapabilities (unsigned int capabilities)
Definition at line 178 of file iLink.c.
{
         NodeCapabilities=capabilities;
         /* Enable the enabled iLink features. */
         if(NodeCapabilities&iLink_NODE_CMC) iLinkEnableCMaster();
         InitializeConfigurationROM();
         return(NodeCapabilities);
 }
References iLink_NODE_CMC, iLinkEnableCMaster(), InitializeConfigurationROM(), and NodeCapabilities.
iLinkSetNodeTrSpeed()
int iLinkSetNodeTrSpeed (int trContext, unsigned char speed)
Definition at line 251 of file iLink.c.
{
         int result;
         result=iLinkGetNodeTrSpeed(trContext);
         /* !!HACK!! Due to a chip bug (?) in the iLink hardware of most consoles, limit the speed to S100 mode whenever the console is the root node
                 (Read the README file for more details on this bug). */
         if(IsBusRoot) speed=S100;
         /* Assign the specified speed to the specified transaction. Assign the maxium allowed speed if the specified speed is above the maximum value. */
         TransactionContexts[trContext].speed=(speed>(sizeof(speeds)-1))?speeds[sizeof(speeds)-1]:speeds[speed];
         return result;
 }
References iLinkGetNodeTrSpeed(), IsBusRoot, result, S100, TransactionContextData::speed, speeds, and TransactionContexts.
Referenced by iLinkTrAlloc().
iLinkSetTrCallbackHandler()
void* iLinkSetTrCallbackHandler (void * function)
Definition at line 222 of file iLink.c.
{
         void *cb_function;
         cb_function=CallBackFunction;
         CallBackFunction=function;
         return cb_function;
 }
References CallBackFunction.
Referenced by init_ieee1394DiskDriver().
iLinkTrAlloc()
int iLinkTrAlloc (unsigned short int NodeID, unsigned char speed)
Definition at line 144 of file iLink.c.
{
         int result;
         unsigned int i;
         if(NodeID!=LocalNodeID){
                 for(i=0; i<MAX_CONCURRENT_TRANSACTIONS; i++){
                         if(TransactionContexts[i].IsConnected==0){
                                 TransactionContexts[i].NodeID=NodeID;
                                 TransactionContexts[i].GenerationNumber=GenerationNumber;
                                 TransactionContexts[i].IsConnected=1;
                                 iLinkSetNodeTrSpeed(i, speed);
                                 break;
                         }
                 }
                 result=(i==MAX_CONCURRENT_TRANSACTIONS)?-1002:i;
         }
         else result = -1;
         return result;
 }
References GenerationNumber, TransactionContextData::GenerationNumber, iLinkSetNodeTrSpeed(), TransactionContextData::IsConnected, LocalNodeID, MAX_CONCURRENT_TRANSACTIONS, TransactionContextData::NodeID, result, TransactionContextData::speed, and TransactionContexts.
Referenced by iLinkIntrCBHandlingThread(), and iLinkReadCROM().
iLinkTrFree()
void iLinkTrFree (int trContext)
Definition at line 166 of file iLink.c.
{
         TransactionContexts[trContext].IsConnected=0;
 }
References TransactionContextData::IsConnected, and TransactionContexts.
Referenced by iLinkIntrCBHandlingThread(), and iLinkReadCROM().
iLinkTrRead()
int iLinkTrRead (int trContext, unsigned short int offset_high, unsigned int offset_low, void * buffer, unsigned int nBytes)
Definition at line 174 of file iLink.c.
{
         return((nBytes==4)?iLinkReadReq(&TransactionContexts[trContext], offset_high, offset_low, buffer, nBytes):iLinkReadPHTReq(&TransactionContexts[trContext], offset_high,offset_low, buffer, nBytes));
 }
References buffer, iLinkReadPHTReq(), iLinkReadReq(), and TransactionContexts.
Referenced by ieee1394_GetFetchAgentState(), and iLinkReadCROM().
iLinkTrWrite()
int iLinkTrWrite (int trContext, unsigned short int offset_high, unsigned int offset_low, void * buffer, unsigned int nBytes)
Definition at line 170 of file iLink.c.
{
         return((nBytes==4)?iLinkWriteReq(&TransactionContexts[trContext], offset_high, offset_low, buffer, nBytes):iLinkWritePHTReq(&TransactionContexts[trContext], offset_high,offset_low, buffer, nBytes));
 }
References buffer, iLinkWritePHTReq(), iLinkWriteReq(), and TransactionContexts.
Referenced by ieee1394_InitializeFetchAgent(), ieee1394_ResetFetchAgent(), ieee1394_SendCommandBlockORB(), and ieee1394_SendManagementORB().
IRX_ID()
IRX_ID (MODNAME , 0x00 , 0x98)
Variable Documentation
_exp_iLinkman
struct irx_export_table _exp_iLinkman extern
Referenced by _exit(), and _start().
CallBackFunction
void(* CallBackFunction) (int reason, unsigned int offset, unsigned int size) (int reason, unsigned int offset, unsigned int size)
Definition at line 34 of file iLink.c.
Referenced by _start(), iLinkSetTrCallbackHandler(), PHYPacketHandler(), ReadRequestHandler(), and WriteRequestHandler().
ConfigurationROM
unsigned int* ConfigurationROM extern
Definition at line 26 of file iLink_crom.c.
Referenced by _exit().
ConsoleGUID
u64 ConsoleGUID
Definition at line 36 of file iLink.c.
Referenced by _start(), BuildConfigurationROM(), and iLinkGetLocalNodeEUI64().
ConsoleModelName
char ConsoleModelName[32]
Definition at line 37 of file iLink.c.
Referenced by _start(), and BuildConfigurationROM().
EventFlagData
iop_event_t EventFlagData static
Initial value:
={
  2,
  0,
  0
}
Definition at line 49 of file iLink.c.
Referenced by _start(), bdm_init(), rmmanInit(), and SetupNetDev().
GenerationNumber
int GenerationNumber extern
Definition at line 26 of file iLink_internal.c.
Referenced by iLinkGetGenerationNumber(), and iLinkTrAlloc().
ILINKRegisterBase
struct ILINKMemMap* ILINKRegisterBase =(struct ILINKMemMap *)ILINK_REGISTER_BASE
Definition at line 31 of file iLink.c.
Referenced by iLinkBusEnable(), iLinkDisableIntr(), iLinkDisableSBus(), iLinkEnableCMaster(), iLinkEnableIntr(), iLinkHWInitialize(), iLinkInitPHT(), iLinkIntrHandler(), iLinkPHTSendData(), iLinkPhySync(), iLinkReadPhy(), iLinkResetHW(), iLinkSendData(), iLinkShutdownHW(), iLinkWritePhy(), PHYPacketHandler(), ShutDownDMAChannels(), and UBUFThread().
IntrEventFlag
int IntrEventFlag
Definition at line 45 of file iLink.c.
Referenced by _exit(), _start(), iLinkIntrHandler(), iLinkPHTSendData(), iLinkResetSBus(), iLinkSendData(), iLinkSync(), PHYPacketHandler(), ResponseHandler(), TimeoutCallbackFunction(), and UBUFThread().
IsBusRoot
unsigned char IsBusRoot extern
Definition at line 31 of file iLink_intr.c.
Referenced by iLinkSetNodeTrSpeed(), and PHYPacketHandler().
LocalNodeID
unsigned short int LocalNodeID
Definition at line 39 of file iLink.c.
Referenced by iLinkFindUnit(), iLinkGetLocalNodeID(), iLinkGetNodeCapabilities(), iLinkTrAlloc(), and PHYPacketHandler().
nNodes
int nNodes extern
Definition at line 27 of file iLink_internal.c.
Referenced by iLinkGetNodeCount(), and iLinkIntrCBHandlingThread().
NodeCapabilities
int NodeCapabilities extern
Definition at line 28 of file iLink_internal.c.
Referenced by iLinkSetNodeCapabilities().
speeds
const unsigned char speeds[3] static
Initial value:
={
        0,
        2,
        4
}
Definition at line 231 of file iLink.c.
Referenced by iLinkGetNodeTrSpeed(), and iLinkSetNodeTrSpeed().
TransactionContexts
struct TransactionContextData TransactionContexts[MAX_CONCURRENT_TRANSACTIONS] extern
Definition at line 28 of file iLink_internal.c.
Referenced by _start(), iLinkGetNodeTrSpeed(), iLinkSetNodeTrSpeed(), iLinkTrAlloc(), iLinkTrFree(), iLinkTrRead(), and iLinkTrWrite().
UBUFThreadID
int UBUFThreadID
Definition at line 45 of file iLink.c.
Referenced by _exit(), and _start().
UBUFTxSema
int UBUFTxSema
Definition at line 45 of file iLink.c.
Referenced by _exit(), _start(), and iLinkSendData().