ps2sdk: iop/iLink/IEEE1394_disk/src/include/part_driver.h File Reference
part_driver.h File Reference
Functions
int part_connect (struct SBP2Device *dev)
void part_disconnect (struct SBP2Device *dev)
Function Documentation
part_connect()
int part_connect (struct SBP2Device * dev)
Definition at line 85 of file part_driver.c.
 {
     part_table partTable;
     int count = 0;
     int i;
     XPRINTF("USBHDFSD: part_connect devId %i \n", dev->nodeID);
     if (part_getPartitionTable(dev, &partTable) < 0)
         return -1;
     for ( i = 0; i < 4; i++)
     {
         if(
             partTable.record[ i ].sid == 6    ||
             partTable.record[ i ].sid == 4    ||
             partTable.record[ i ].sid == 1    ||  // fat 16, fat 12
             partTable.record[ i ].sid == 0x0B ||
             partTable.record[ i ].sid == 0x0C ||  // fat 32
             partTable.record[ i ].sid == 0x0E)    // fat 16 LBA
         {
             XPRINTF("USBHDFSD: mount partition %d\n", i);
             if (fat_mount(dev, partTable.record[i].start, partTable.record[i].count) >= 0)
                 count++;
         }
     }
     if ( count == 0 )
     {  // no partition table detected
         // try to use "floppy" option
         printf("USBHDFSD: mount drive\n");
         if (fat_mount(dev, 0, dev->maxLBA) < 0)
             return -1;
     }
     return 0;
 }
References part_record::count, fat_mount(), SBP2Device::maxLBA, SBP2Device::nodeID, part_getPartitionTable(), printf(), part_table::record, part_record::sid, part_record::start, and XPRINTF.
part_disconnect()
void part_disconnect (struct SBP2Device * dev)
Definition at line 123 of file part_driver.c.
 {
     printf("USBHDFSD: part_disconnect devId %i \n", dev->nodeID);
     fat_forceUnmount(dev);
 }
References fat_forceUnmount(), SBP2Device::nodeID, and printf().