ps2sdk: iop/iLink/iLinkman/src/iLink_internal.c File Reference
iLink_internal.c File Reference
#include <dmacman.h>
#include <intrman.h>
#include <stdio.h>
#include <sysclib.h>
#include <sysmem.h>
#include <thbase.h>
#include <thevent.h>
#include <cdvdman.h>
#include "iLinkman.h"
#include "iLink_internal.h"
Functions
void UBUFThread (void *arg)
int GetConsoleIDs (u64 *guid, char *ModelName)
void iLinkDisableIntr (void)
void iLinkEnableIntr (void)
static void ShutDownDMAChannels (void)
int iLinkResetHW (void)
void iLinkShutdownHW (void)
void iLinkHWInitialize (void)
void iLinkEnableCMaster (void)
void iLinkBusEnable (void)
void * malloc (unsigned int nBytes)
void free (void *buffer)
Variables
struct ILINKMemMap * ILINKRegisterBase
struct DMAChannelRegBlock * iLinkDMACRegs
struct DMARRegBlock * iLinkDMARRegs
void(* CallBackFunction)(int reason, unsigned int offset, unsigned int size)
int GenerationNumber
int nNodes
int NodeCapabilities
struct TransactionContextData TransactionContexts [10]
int IntrEventFlag
const void * RequestHandlers []
Function Documentation
free()
void free (void * buffer)
Definition at line 180 of file iLink_internal.c.
{
         int OldState;
         CpuSuspendIntr(&OldState);
         FreeSysMemory(buffer);
         CpuResumeIntr(OldState);
 }
References buffer, CpuResumeIntr(), CpuSuspendIntr(), and FreeSysMemory().
GetConsoleIDs()
int GetConsoleIDs (u64 * guid, char * ModelName)
Definition at line 52 of file iLink_internal.c.
{
         u64 ilink_id;
         u32 stat;
         int result;
         if(sceCdRI((u8*)&ilink_id, &stat)<0 || stat!=0){
                 result=-1;
                 DEBUG_PRINTF("Error reading console/ILINK ID.\n");
         }
         else{
                 *guid=(ilink_id&0xFFFFFFFF00000000) | ((*(u8*)&ilink_id)|0x08004600);
                 if(sceCdRM(ModelName, &stat)<0 || stat!=0){
                         result=-1;
                         DEBUG_PRINTF("Error reading console model name.\n");
                 }
                 result=0;
         }
         return result;
 }
References DEBUG_PRINTF, result, sceCdRI(), and sceCdRM().
Referenced by _start().
iLinkBusEnable()
void iLinkBusEnable (void)
Definition at line 165 of file iLink_internal.c.
{
         ILINKRegisterBase->ctrl0|=(iLink_CTRL0_RxEn|iLink_CTRL0_TxEn);  /* Enable transmitter and receiver. */
 }
References ILINKMemMap::ctrl0, iLink_CTRL0_RxEn, iLink_CTRL0_TxEn, and ILINKRegisterBase.
Referenced by iLinkEnableSBus().
iLinkDisableIntr()
void iLinkDisableIntr (void)
Definition at line 74 of file iLink_internal.c.
{
         ILINKRegisterBase->intr0Mask=0;
         ILINKRegisterBase->intr1Mask=0;
         ILINKRegisterBase->intr2Mask=0;
         /* Set all interrupt bits, to acknowledge any pending interrupts that there may be. */
         ILINKRegisterBase->intr0=0xFFFFFFFF;
         ILINKRegisterBase->intr1=0xFFFFFFFF;
         ILINKRegisterBase->intr2=0xFFFFFFFF;
 }
References ILINKRegisterBase, ILINKMemMap::intr0, ILINKMemMap::intr0Mask, ILINKMemMap::intr1, ILINKMemMap::intr1Mask, ILINKMemMap::intr2, and ILINKMemMap::intr2Mask.
Referenced by _start().
iLinkEnableCMaster()
void iLinkEnableCMaster (void)
Definition at line 161 of file iLink_internal.c.
{
         ILINKRegisterBase->ctrl0|=iLink_CTRL0_CMstr;
 }
References ILINKMemMap::ctrl0, iLink_CTRL0_CMstr, and ILINKRegisterBase.
Referenced by iLinkSetNodeCapabilities().
iLinkEnableIntr()
void iLinkEnableIntr (void)
Definition at line 85 of file iLink_internal.c.
{
         /* Enable the interrupt events */
         ILINKRegisterBase->intr0Mask=iLink_INTR0_CmdRst|iLink_INTR0_PhyRst|iLink_INTR0_RetEx|iLink_INTR0_STO|iLink_INTR0_PBCntR|iLink_INTR0_UResp|iLink_INTR0_URx;
 #ifdef REQ_CHECK_DMAC_STAT
         ILINKRegisterBase->intr0Mask|=iLink_INTR0_DRFR;
 #endif
 #ifdef REQ_CHECK_ERRORS
         ILINKRegisterBase->intr0Mask|=(iLink_INTR0_HdrErr|iLink_INTR0_SntBsyAck); /* For debugging purposes */
 #endif
         ILINKRegisterBase->intr1Mask=iLink_INTR1_UTD;
 }
References iLink_INTR0_CmdRst, iLink_INTR0_DRFR, iLink_INTR0_HdrErr, iLink_INTR0_PBCntR, iLink_INTR0_PhyRst, iLink_INTR0_RetEx, iLink_INTR0_SntBsyAck, iLink_INTR0_STO, iLink_INTR0_UResp, iLink_INTR0_URx, iLink_INTR1_UTD, ILINKRegisterBase, ILINKMemMap::intr0Mask, and ILINKMemMap::intr1Mask.
Referenced by iLinkHWInitialize().
iLinkHWInitialize()
void iLinkHWInitialize (void)
Definition at line 134 of file iLink_internal.c.
{
         iLinkPHY_SetLCTRL(0);
         /* Configure the Control 0 register, resetting the transmitter and receiver at the same time. */
 //      ILINKRegisterBase->ctrl0=iLink_CTRL0_TxRst|iLink_CTRL0_RxRst|iLink_CTRL0_RcvSelfID|iLink_CTRL0_BusIDRst|iLink_CTRL0_CycTmrEn|iLink_CTRL0_RetLim(0x0F)|iLink_CTRL0_RSP0|iLink_CTRL0_DELim(3);
         ILINKRegisterBase->ctrl0=iLink_CTRL0_TxRst|iLink_CTRL0_RxRst|iLink_CTRL0_RcvSelfID|iLink_CTRL0_BusIDRst|iLink_CTRL0_CycTmrEn|iLink_CTRL0_RetLim(0x0F)|iLink_CTRL0_DELim(3);
         while(ILINKRegisterBase->ctrl0&(iLink_CTRL0_RxRst|iLink_CTRL0_TxRst)){};
         ILINKRegisterBase->ubufTransmitClear=0; /* Clear UBUF Tx FIFO. */
         ILINKRegisterBase->ubufReceiveClear=0;  /* Clear UBUF Rx FIFO. */
         ILINKRegisterBase->dbufFIFO_lvlR0=DBUF_FIFO_RESET_TX|DBUF_FIFO_RESET_RX;        /* Reset DBUF FIFO 0 */
         ILINKRegisterBase->dbufFIFO_lvlR1=DBUF_FIFO_RESET_TX|DBUF_FIFO_RESET_RX;        /* Reset DBUF FIFO 1 */
         iLinkInitPHT();
         iLinkEnableIntr();
         iLinkWritePhy(5, iLinkReadPhy(5)|REG05_EN_ACCL|REG05_EN_MULTI); /* Enable supported P1394A-2000 enhancements. */
         /* Enable DMA channels 13 and 15. */
         dmac_enable(IOP_DMAC_FDMA0);
         dmac_enable(IOP_DMAC_FDMA2);
         GenerationNumber=0;
         NodeCapabilities=0;
 }
References ILINKMemMap::ctrl0, DBUF_FIFO_RESET_RX, DBUF_FIFO_RESET_TX, ILINKMemMap::dbufFIFO_lvlR0, ILINKMemMap::dbufFIFO_lvlR1, dmac_enable(), GenerationNumber, iLink_CTRL0_BusIDRst, iLink_CTRL0_CycTmrEn, iLink_CTRL0_DELim, iLink_CTRL0_RcvSelfID, iLink_CTRL0_RetLim, iLink_CTRL0_RxRst, iLink_CTRL0_TxRst, iLinkEnableIntr(), iLinkInitPHT(), iLinkPHY_SetLCTRL(), iLinkReadPhy(), ILINKRegisterBase, iLinkWritePhy(), IOP_DMAC_FDMA0, IOP_DMAC_FDMA2, NodeCapabilities, REG05_EN_ACCL, REG05_EN_MULTI, ILINKMemMap::ubufReceiveClear, and ILINKMemMap::ubufTransmitClear.
Referenced by _start().
iLinkResetHW()
int iLinkResetHW (void)
Definition at line 112 of file iLink_internal.c.
                       {
         ShutDownDMAChannels();
         /* Turn off, and then turn back on the LINK and PHY. If this is not done, the iLink hardware might not function correctly on some consoles. :( */
         ILINKRegisterBase->UnknownRegister7C=0x40;      /* Shut down. */
         DelayThread(400000);
         ILINKRegisterBase->UnknownRegister7C=0;
         /* If the LINK is off, switch it on. */
         if(!(ILINKRegisterBase->ctrl2&iLink_CTRL2_LPSEn)) ILINKRegisterBase->ctrl2=iLink_CTRL2_LPSEn;
         /* Wait for the clock to stabilize. */
         while(!(ILINKRegisterBase->ctrl2&iLink_CTRL2_SOK)) DelayThread(50);
         return 0;
 }
References ILINKMemMap::ctrl2, DelayThread(), iLink_CTRL2_LPSEn, iLink_CTRL2_SOK, ILINKRegisterBase, ShutDownDMAChannels(), and ILINKMemMap::UnknownRegister7C.
Referenced by _start().
iLinkShutdownHW()
void iLinkShutdownHW (void)
Definition at line 129 of file iLink_internal.c.
{
         ShutDownDMAChannels();
         ILINKRegisterBase->ctrl2&=(~iLink_CTRL2_LPSEn); /* Set the LINK to enter standby mode. */
 }
References ILINKMemMap::ctrl2, iLink_CTRL2_LPSEn, ILINKRegisterBase, and ShutDownDMAChannels().
Referenced by _exit().
malloc()
void* malloc (unsigned int nBytes)
Definition at line 169 of file iLink_internal.c.
{
         int OldState;
         void *result;
         CpuSuspendIntr(&OldState);
         result=AllocSysMemory(ALLOC_FIRST, nBytes, NULL);
         CpuResumeIntr(OldState);
         return result;
 }
References ALLOC_FIRST, AllocSysMemory(), CpuResumeIntr(), CpuSuspendIntr(), NULL, and result.
ShutDownDMAChannels()
static void ShutDownDMAChannels (void) static
Definition at line 98 of file iLink_internal.c.
{
         /* Stop all DMA-related activities */
         ILINKRegisterBase->dmaCtrlSR0=ILINKRegisterBase->dmaCtrlSR1=0;
         /* Stop all DMA-related activities */
         iLinkDMACRegs[0].chcr=iLinkDMACRegs[1].chcr=iLinkDMACRegs[2].chcr=0;
         /* Disable all DMAC channels connected to the i.Link hardware.
                 (Disable DMA channels 13, 14 and 15) */
         dmac_disable(IOP_DMAC_FDMA0);
         dmac_disable(IOP_DMAC_FDMA1);
         dmac_disable(IOP_DMAC_FDMA2);
 }
References DMAChannelRegBlock::chcr, dmac_disable(), ILINKMemMap::dmaCtrlSR0, ILINKMemMap::dmaCtrlSR1, iLinkDMACRegs, ILINKRegisterBase, IOP_DMAC_FDMA0, IOP_DMAC_FDMA1, and IOP_DMAC_FDMA2.
Referenced by iLinkResetHW(), and iLinkShutdownHW().
UBUFThread()
void UBUFThread (void * arg)
Definition at line 34 of file iLink_internal.c.
{
         void (*RequestResponseHandler)(unsigned int header, volatile unsigned int *buffer, unsigned int nQuads);
         unsigned int data, DataBufferLevel;
         u32 ef_bits;
         while(1){
                 WaitEventFlag(IntrEventFlag, iLinkEventBusReset|iLinkEventURx, WEF_OR, &ef_bits);
                 ClearEventFlag(IntrEventFlag, ~(iLinkEventBusReset|iLinkEventURx));
                 while((DataBufferLevel=ILINKRegisterBase->ubufReceiveLevel)>0){
                         data=ILINKRegisterBase->ubufReceive;
                         iDEBUG_PRINTF("Handling UBUF data... handler: 0x%02lx.\n", (data>>4)&0xF);
                         RequestResponseHandler=RequestHandlers[(data>>4)&0xF];
                         RequestResponseHandler(data, (volatile unsigned int *)&ILINKRegisterBase->ubufReceive, DataBufferLevel-1);
                 }
         }
 }
References buffer, ClearEventFlag(), iDEBUG_PRINTF, iLinkEventBusReset, iLinkEventURx, ILINKRegisterBase, IntrEventFlag, RequestHandlers, ILINKMemMap::ubufReceive, ILINKMemMap::ubufReceiveLevel, WaitEventFlag(), and WEF_OR.
Referenced by _start().
Variable Documentation
CallBackFunction
void(* CallBackFunction) (int reason, unsigned int offset, unsigned int size) (int reason, unsigned int offset, unsigned int size) extern
Definition at line 34 of file iLink.c.
GenerationNumber
int GenerationNumber
Definition at line 26 of file iLink_internal.c.
Referenced by iLinkGetGenerationNumber(), iLinkHWInitialize(), iLinkIntrHandler(), iLinkPHTSendData(), iLinkSendData(), and iLinkTrAlloc().
iLinkDMACRegs
struct DMAChannelRegBlock* iLinkDMACRegs extern
Definition at line 27 of file iLink_DMA.c.
Referenced by ShutDownDMAChannels().
iLinkDMARRegs
struct DMARRegBlock* iLinkDMARRegs extern
Definition at line 28 of file iLink_DMA.c.
Referenced by iLinkInitPHT().
ILINKRegisterBase
struct ILINKMemMap* ILINKRegisterBase extern
Definition at line 31 of file iLink.c.
Referenced by iLinkBusEnable(), iLinkDisableIntr(), iLinkEnableCMaster(), iLinkEnableIntr(), iLinkHWInitialize(), iLinkResetHW(), iLinkShutdownHW(), ShutDownDMAChannels(), and UBUFThread().
IntrEventFlag
int IntrEventFlag extern
Definition at line 45 of file iLink.c.
Referenced by UBUFThread().
nNodes
int nNodes
Definition at line 27 of file iLink_internal.c.
Referenced by iLinkFindUnit(), iLinkGetNodeCount(), iLinkGetNodeMaxSpeed(), iLinkIntrCBHandlingThread(), and PHYPacketHandler().
NodeCapabilities
int NodeCapabilities
Definition at line 28 of file iLink_internal.c.
Referenced by BuildConfigurationROM(), iLinkGetNodeCapabilities(), iLinkHWInitialize(), and iLinkSetNodeCapabilities().
RequestHandlers
const void* RequestHandlers[] extern
Definition at line 294 of file iLink_intr.c.
Referenced by UBUFThread().
TransactionContexts
struct TransactionContextData TransactionContexts[10]
Definition at line 28 of file iLink_internal.c.
Referenced by _start(), iLinkGetNodeTrSpeed(), iLinkSetNodeTrSpeed(), iLinkTrAlloc(), iLinkTrFree(), iLinkTrRead(), and iLinkTrWrite().