ps2sdk: iop/iLink/iLinkman/src/include/iLink_internal.h File Reference
iLink_internal.h File Reference
Data Structures
struct ieee1394_TrPacketHdr
struct ieee1394_TrResponsePacketHdr
struct ILINKMemMap
struct DMAChannelRegBlock
struct DMARRegBlock
struct TransactionContextData
Macros
#define DEBUG_PRINTF(args...)
#define iDEBUG_PRINTF(args...)
#define REQ_CHECK_MEM_BOUNDARIES /* Define this to enable memory address boundary checking for incoming requests. */
#define REQ_CHECK_CONSOLE_VERSION /* Define this to enable version checks on the Playstation 2 console. */
#define iLink_INTR0_DRFR 0x00000001
#define iLink_INTR0_DRFO 0x00000002
#define iLink_INTR0_TxStk 0x00000040
#define iLink_INTR0_FmtE 0x00000080
#define iLink_INTR0_UResp 0x00000100
#define iLink_INTR0_PBCntR 0x00000200
#define iLink_INTR0_STO 0x00000400
#define iLink_INTR0_RetEx 0x00000800
#define iLink_INTR0_InvAck 0x00001000
#define iLink_INTR0_AckMiss 0x00002000
#define iLink_INTR0_AckRcvd 0x00004000
#define iLink_INTR0_CycArbFl 0x00008000
#define iLink_INTR0_CycLost 0x00010000
#define iLink_INTR0_CycSt 0x00080000
#define iLink_INTR0_CycTL 0x00200000
#define iLink_INTR0_URx 0x00400000
#define iLink_INTR0_SubActGap 0x00800000
#define iLink_INTR0_TCErr 0x01000000
#define iLink_INTR0_HdrErr 0x02000000
#define iLink_INTR0_SntBsyAck 0x04000000
#define iLink_INTR0_CmdRst 0x08000000
#define iLink_INTR0_ArbRstGap 0x10000000
#define iLink_INTR0_PhyRst 0x20000000
#define iLink_INTR0_PhyRRx 0x40000000
#define iLink_INTR0_PhyInt 0x80000000
#define iLink_INTR1_DTFO 0x00000001
#define iLink_INTR1_UTD 0x00000002
#define iLink_CTRL0_URcvM 0x00000010
#define iLink_CTRL0_RSP0 0x00000020
#define iLink_CTRL0_RetLim(x) (x<<12)
#define iLink_CTRL0_LooseTightIso 0x00010000
#define iLink_CTRL0_STardy 0x00020000
#define iLink_CTRL0_BRDE 0x00040000
#define iLink_CTRL0_Root 0x00080000
#define iLink_CTRL0_ExtCyc 0x00100000
#define iLink_CTRL0_CycTmrEn 0x00200000
#define iLink_CTRL0_CMstr 0x00400000
#define iLink_CTRL0_BusIDRst 0x00800000
#define iLink_CTRL0_RxRst 0x01000000
#define iLink_CTRL0_TxRst 0x02000000
#define iLink_CTRL0_RxEn 0x04000000
#define iLink_CTRL0_TxEn 0x08000000
#define iLink_CTRL0_DELim(x) (x<<28)
#define iLink_CTRL0_SIDF 0x40000000
#define iLink_CTRL0_RcvSelfID 0x80000000
#define iLink_CTRL2_LPSRst 0x00000001
#define iLink_CTRL2_LPSEn 0x00000002
#define iLink_CTRL2_SRst 0x00000004
#define iLink_CTRL2_SOK 0x00000008
#define iLinkDMA_CTRL_SR_DWidth(x) (x<<17)
#define iLinkDMA_CTRL_SR_DEn 0x080000
#define iLinkDMA_CTRL_SR_RActl 0x010000
#define iLinkDMA_CTRL_SR_LFirst 0x100000
#define PHT_CTRL_ST_PRBR 0x00000200
#define PHT_CTRL_ST_PStk 0x00000400
#define PHT_CTRL_ST_EnDMAS 0x00001000
#define PHT_CTRL_ST_EBCNT 0x00008000
#define PHT_CTRL_ST_EWREQ 0x00010000
#define PHT_CTRL_ST_ERREQ 0x00020000
#define PHT_CTRL_ST_EPCNT 0x00100000
#define PHT_CTRL_ST_PHTRst 0x00200000
#define PHT_CTRL_ST_IHdr 0x00400000
#define PHT_CTRL_ST_EHdr 0x02000000
#define DBUF_FIFO_RESET_TX 0x00008000
#define DBUF_FIFO_RESET_RX 0x80000000
#define PACKET_TCODE (((x)>>4)&0xF)
#define PHY_CONFIG_PACKET 0xE0
#define PHY_CONFIG_GAP_CNT(x) (((x)>>16)&0x3F)
#define PHY_CONFIG_T(x) (((x)>>22)&0x01)
#define PHY_CONFIG_R(x) (((x)>>23)&0x01)
#define PHY_CONFIG_ROOT_ID(x) (((x)>>24)&0x3F)
#define PHY_SELF_ID_PACKET 0xE1
#define PHY_SELF_ID_PKT_SIG 0x2 /* 10b */
#define SELF_ID_SIGNATURE(x) (((x)>>30)&0x03)
#define SELF_ID_NODEID(x) (((x)>>24)&0x3F)
#define SELF_ID_L(x) (((x)>>22)&0x01)
#define SELF_ID_GAP_CNT(x) (((x)>>16)&0x3F)
#define SELF_ID_SPEED(x) (((x)>>14)&0x03)
#define SELF_ID_POWER(x) (((x)>>8)&0x07)
#define SELF_ID_M(x) (((x)&0x01)
#define REG01_IBR 0x40
#define REG01_RHB 0x80
#define REG04_LCTRL 0x80
#define REG05_ISBR 0x40
#define REG05_EN_ACCL 0x02
#define REG05_EN_MULTI 0x01
#define iLinkEventInterrupt 0x00000001
#define iLinkEventBusReady 0x00000002
#define iLinkEventGotSELFIDs 0x00000004
#define iLinkEventDataSent 0x00000008
#define iLinkEventDataReceived 0x00000010
#define iLinkEventDMATransEnd 0x00000020
#define iLinkEventBusReset 0x00000040
#define iLinkEventURx 0x00000080
#define iLinkEventError 0x80000000
#define IEEE1394_TCODE_WRITEQ 0
#define IEEE1394_TCODE_WRITEB 1
#define IEEE1394_TCODE_WRITE_RESPONSE 2
#define IEEE1394_TCODE_READQ 4
#define IEEE1394_TCODE_READB 5
#define IEEE1394_TCODE_READQ_RESPONSE 6
#define IEEE1394_TCODE_READB_RESPONSE 7
#define ILINK_REGISTER_BASE 0xBF808400
#define ILINK_DMAC_REGISTER_BASE 0xBF801580
#define ILINK_DMAC_DMAR_CTRL_BASE 0xBF8015DC
#define MAX_CONCURRENT_TRANSACTIONS 10
#define DMAC_CHCR_AR (1<<31) /* Automatic Response. */
#define DMAC_CHCR_11 (1<<11) /* I don't know what this does, but it appears to be a bit that means something to the DMAC. */
Functions
void UBUFThread (void *arg)
int GetConsoleIDs (u64 *guid, char *ModelName)
void iLinkDisableIntr (void)
int iLinkResetHW (void)
void iLinkShutdownHW (void)
void iLinkHWInitialize (void)
void iLinkEnableCMaster (void)
void iLinkBusEnable (void)
void * malloc (unsigned int nBytes)
void free (void *buffer)
void InitializeConfigurationROM (void)
unsigned char iLinkReadPhy (unsigned char address)
void iLinkWritePhy (unsigned char address, unsigned char data)
void iLinkPHY_SetRootBit (int isRoot)
void iLinkPHY_SetGapCount (unsigned char GapCount)
void iLinkPHY_SetLCTRL (int LCTRL_status)
void iLinkPHYBusReset (void)
int iLinkIntrHandler (void *arg)
void iLinkIntrRegister0Handler (void *arg)
void SendResponse (unsigned short int NodeID, unsigned short RcvdBusID, unsigned char rcode, unsigned char tLabel, unsigned char tCode, unsigned char speed, unsigned int *buffer, unsigned int nQuads)
int iLinkReadReq (struct TransactionContextData *trContext, unsigned short int offset_high, unsigned int offset_low, void *buffer, unsigned int nBytes)
int iLinkWriteReq (struct TransactionContextData *trContext, unsigned short int offset_high, unsigned int offset_low, void *buffer, unsigned int nBytes)
void iLinkInitPHT (void)
void PHTSendResponse (unsigned short int NodeID, unsigned short RcvdBusID, unsigned char rcode, unsigned char tLabel, unsigned char tCode, unsigned char speed, unsigned int *buffer, unsigned int nQuads)
int iLinkReadPHTReq (struct TransactionContextData *trContext, unsigned short int offset_high, unsigned int offset_low, void *buffer, unsigned int nBytes)
int iLinkWritePHTReq (struct TransactionContextData *trContext, unsigned short int offset_high, unsigned int offset_low, void *buffer, unsigned int nBytes)
Macro Definition Documentation
DBUF_FIFO_RESET_RX
#define DBUF_FIFO_RESET_RX 0x80000000
Definition at line 86 of file iLink_internal.h.
DBUF_FIFO_RESET_TX
#define DBUF_FIFO_RESET_TX 0x00008000
Definition at line 85 of file iLink_internal.h.
DEBUG_PRINTF
#define DEBUG_PRINTF (args...)
Definition at line 7 of file iLink_internal.h.
DMAC_CHCR_11
#define DMAC_CHCR_11 (1<<11) /* I don't know what this does, but it appears to be a bit that means something to the DMAC. */
Definition at line 273 of file iLink_internal.h.
DMAC_CHCR_AR
#define DMAC_CHCR_AR (1<<31) /* Automatic Response. */
Definition at line 272 of file iLink_internal.h.
iDEBUG_PRINTF
#define iDEBUG_PRINTF (args...)
Definition at line 8 of file iLink_internal.h.
IEEE1394_TCODE_READB
#define IEEE1394_TCODE_READB 5
Definition at line 132 of file iLink_internal.h.
IEEE1394_TCODE_READB_RESPONSE
#define IEEE1394_TCODE_READB_RESPONSE 7
Definition at line 134 of file iLink_internal.h.
IEEE1394_TCODE_READQ
#define IEEE1394_TCODE_READQ 4
Definition at line 131 of file iLink_internal.h.
IEEE1394_TCODE_READQ_RESPONSE
#define IEEE1394_TCODE_READQ_RESPONSE 6
Definition at line 133 of file iLink_internal.h.
IEEE1394_TCODE_WRITE_RESPONSE
#define IEEE1394_TCODE_WRITE_RESPONSE 2
Definition at line 130 of file iLink_internal.h.
IEEE1394_TCODE_WRITEB
#define IEEE1394_TCODE_WRITEB 1
Definition at line 129 of file iLink_internal.h.
IEEE1394_TCODE_WRITEQ
#define IEEE1394_TCODE_WRITEQ 0
Definition at line 128 of file iLink_internal.h.
iLink_CTRL0_BRDE
#define iLink_CTRL0_BRDE 0x00040000
Definition at line 50 of file iLink_internal.h.
iLink_CTRL0_BusIDRst
#define iLink_CTRL0_BusIDRst 0x00800000
Definition at line 55 of file iLink_internal.h.
iLink_CTRL0_CMstr
#define iLink_CTRL0_CMstr 0x00400000
Definition at line 54 of file iLink_internal.h.
iLink_CTRL0_CycTmrEn
#define iLink_CTRL0_CycTmrEn 0x00200000
Definition at line 53 of file iLink_internal.h.
iLink_CTRL0_DELim
#define iLink_CTRL0_DELim (x) (x<<28)
Definition at line 60 of file iLink_internal.h.
iLink_CTRL0_ExtCyc
#define iLink_CTRL0_ExtCyc 0x00100000
Definition at line 52 of file iLink_internal.h.
iLink_CTRL0_LooseTightIso
#define iLink_CTRL0_LooseTightIso 0x00010000
Definition at line 48 of file iLink_internal.h.
iLink_CTRL0_RcvSelfID
#define iLink_CTRL0_RcvSelfID 0x80000000
Definition at line 62 of file iLink_internal.h.
iLink_CTRL0_RetLim
#define iLink_CTRL0_RetLim (x) (x<<12)
Definition at line 47 of file iLink_internal.h.
iLink_CTRL0_Root
#define iLink_CTRL0_Root 0x00080000
Definition at line 51 of file iLink_internal.h.
iLink_CTRL0_RSP0
#define iLink_CTRL0_RSP0 0x00000020
Definition at line 46 of file iLink_internal.h.
iLink_CTRL0_RxEn
#define iLink_CTRL0_RxEn 0x04000000
Definition at line 58 of file iLink_internal.h.
iLink_CTRL0_RxRst
#define iLink_CTRL0_RxRst 0x01000000
Definition at line 56 of file iLink_internal.h.
iLink_CTRL0_SIDF
#define iLink_CTRL0_SIDF 0x40000000
Definition at line 61 of file iLink_internal.h.
iLink_CTRL0_STardy
#define iLink_CTRL0_STardy 0x00020000
Definition at line 49 of file iLink_internal.h.
iLink_CTRL0_TxEn
#define iLink_CTRL0_TxEn 0x08000000
Definition at line 59 of file iLink_internal.h.
iLink_CTRL0_TxRst
#define iLink_CTRL0_TxRst 0x02000000
Definition at line 57 of file iLink_internal.h.
iLink_CTRL0_URcvM
#define iLink_CTRL0_URcvM 0x00000010
Definition at line 45 of file iLink_internal.h.
iLink_CTRL2_LPSEn
#define iLink_CTRL2_LPSEn 0x00000002
Definition at line 65 of file iLink_internal.h.
iLink_CTRL2_LPSRst
#define iLink_CTRL2_LPSRst 0x00000001
Definition at line 64 of file iLink_internal.h.
iLink_CTRL2_SOK
#define iLink_CTRL2_SOK 0x00000008
Definition at line 67 of file iLink_internal.h.
iLink_CTRL2_SRst
#define iLink_CTRL2_SRst 0x00000004
Definition at line 66 of file iLink_internal.h.
ILINK_DMAC_DMAR_CTRL_BASE
#define ILINK_DMAC_DMAR_CTRL_BASE 0xBF8015DC
Definition at line 263 of file iLink_internal.h.
ILINK_DMAC_REGISTER_BASE
#define ILINK_DMAC_REGISTER_BASE 0xBF801580
Definition at line 249 of file iLink_internal.h.
iLink_INTR0_AckMiss
#define iLink_INTR0_AckMiss 0x00002000
Definition at line 25 of file iLink_internal.h.
iLink_INTR0_AckRcvd
#define iLink_INTR0_AckRcvd 0x00004000
Definition at line 26 of file iLink_internal.h.
iLink_INTR0_ArbRstGap
#define iLink_INTR0_ArbRstGap 0x10000000
Definition at line 37 of file iLink_internal.h.
iLink_INTR0_CmdRst
#define iLink_INTR0_CmdRst 0x08000000
Definition at line 36 of file iLink_internal.h.
iLink_INTR0_CycArbFl
#define iLink_INTR0_CycArbFl 0x00008000
Definition at line 27 of file iLink_internal.h.
iLink_INTR0_CycLost
#define iLink_INTR0_CycLost 0x00010000
Definition at line 28 of file iLink_internal.h.
iLink_INTR0_CycSt
#define iLink_INTR0_CycSt 0x00080000
Definition at line 29 of file iLink_internal.h.
iLink_INTR0_CycTL
#define iLink_INTR0_CycTL 0x00200000
Definition at line 30 of file iLink_internal.h.
iLink_INTR0_DRFO
#define iLink_INTR0_DRFO 0x00000002
Definition at line 17 of file iLink_internal.h.
iLink_INTR0_DRFR
#define iLink_INTR0_DRFR 0x00000001
Definition at line 16 of file iLink_internal.h.
iLink_INTR0_FmtE
#define iLink_INTR0_FmtE 0x00000080
Definition at line 19 of file iLink_internal.h.
iLink_INTR0_HdrErr
#define iLink_INTR0_HdrErr 0x02000000
Definition at line 34 of file iLink_internal.h.
iLink_INTR0_InvAck
#define iLink_INTR0_InvAck 0x00001000
Definition at line 24 of file iLink_internal.h.
iLink_INTR0_PBCntR
#define iLink_INTR0_PBCntR 0x00000200
Definition at line 21 of file iLink_internal.h.
iLink_INTR0_PhyInt
#define iLink_INTR0_PhyInt 0x80000000
Definition at line 40 of file iLink_internal.h.
iLink_INTR0_PhyRRx
#define iLink_INTR0_PhyRRx 0x40000000
Definition at line 39 of file iLink_internal.h.
iLink_INTR0_PhyRst
#define iLink_INTR0_PhyRst 0x20000000
Definition at line 38 of file iLink_internal.h.
iLink_INTR0_RetEx
#define iLink_INTR0_RetEx 0x00000800
Definition at line 23 of file iLink_internal.h.
iLink_INTR0_SntBsyAck
#define iLink_INTR0_SntBsyAck 0x04000000
Definition at line 35 of file iLink_internal.h.
iLink_INTR0_STO
#define iLink_INTR0_STO 0x00000400
Definition at line 22 of file iLink_internal.h.
iLink_INTR0_SubActGap
#define iLink_INTR0_SubActGap 0x00800000
Definition at line 32 of file iLink_internal.h.
iLink_INTR0_TCErr
#define iLink_INTR0_TCErr 0x01000000
Definition at line 33 of file iLink_internal.h.
iLink_INTR0_TxStk
#define iLink_INTR0_TxStk 0x00000040
Definition at line 18 of file iLink_internal.h.
iLink_INTR0_UResp
#define iLink_INTR0_UResp 0x00000100
Definition at line 20 of file iLink_internal.h.
iLink_INTR0_URx
#define iLink_INTR0_URx 0x00400000
Definition at line 31 of file iLink_internal.h.
iLink_INTR1_DTFO
#define iLink_INTR1_DTFO 0x00000001
Definition at line 42 of file iLink_internal.h.
iLink_INTR1_UTD
#define iLink_INTR1_UTD 0x00000002
Definition at line 43 of file iLink_internal.h.
ILINK_REGISTER_BASE
#define ILINK_REGISTER_BASE 0xBF808400
Definition at line 150 of file iLink_internal.h.
iLinkDMA_CTRL_SR_DEn
#define iLinkDMA_CTRL_SR_DEn 0x080000
Definition at line 70 of file iLink_internal.h.
iLinkDMA_CTRL_SR_DWidth
#define iLinkDMA_CTRL_SR_DWidth (x) (x<<17)
Definition at line 69 of file iLink_internal.h.
iLinkDMA_CTRL_SR_LFirst
#define iLinkDMA_CTRL_SR_LFirst 0x100000
Definition at line 72 of file iLink_internal.h.
iLinkDMA_CTRL_SR_RActl
#define iLinkDMA_CTRL_SR_RActl 0x010000
Definition at line 71 of file iLink_internal.h.
iLinkEventBusReady
#define iLinkEventBusReady 0x00000002
Definition at line 118 of file iLink_internal.h.
iLinkEventBusReset
#define iLinkEventBusReset 0x00000040
Definition at line 123 of file iLink_internal.h.
iLinkEventDataReceived
#define iLinkEventDataReceived 0x00000010
Definition at line 121 of file iLink_internal.h.
iLinkEventDataSent
#define iLinkEventDataSent 0x00000008
Definition at line 120 of file iLink_internal.h.
iLinkEventDMATransEnd
#define iLinkEventDMATransEnd 0x00000020
Definition at line 122 of file iLink_internal.h.
iLinkEventError
#define iLinkEventError 0x80000000
Definition at line 125 of file iLink_internal.h.
iLinkEventGotSELFIDs
#define iLinkEventGotSELFIDs 0x00000004
Definition at line 119 of file iLink_internal.h.
iLinkEventInterrupt
#define iLinkEventInterrupt 0x00000001
Definition at line 117 of file iLink_internal.h.
iLinkEventURx
#define iLinkEventURx 0x00000080
Definition at line 124 of file iLink_internal.h.
MAX_CONCURRENT_TRANSACTIONS
#define MAX_CONCURRENT_TRANSACTIONS 10
Definition at line 270 of file iLink_internal.h.
PACKET_TCODE
#define PACKET_TCODE (((x)>>4)&0xF)
Definition at line 88 of file iLink_internal.h.
PHT_CTRL_ST_EBCNT
#define PHT_CTRL_ST_EBCNT 0x00008000
Definition at line 77 of file iLink_internal.h.
PHT_CTRL_ST_EHdr
#define PHT_CTRL_ST_EHdr 0x02000000
Definition at line 83 of file iLink_internal.h.
PHT_CTRL_ST_EnDMAS
#define PHT_CTRL_ST_EnDMAS 0x00001000
Definition at line 76 of file iLink_internal.h.
PHT_CTRL_ST_EPCNT
#define PHT_CTRL_ST_EPCNT 0x00100000
Definition at line 80 of file iLink_internal.h.
PHT_CTRL_ST_ERREQ
#define PHT_CTRL_ST_ERREQ 0x00020000
Definition at line 79 of file iLink_internal.h.
PHT_CTRL_ST_EWREQ
#define PHT_CTRL_ST_EWREQ 0x00010000
Definition at line 78 of file iLink_internal.h.
PHT_CTRL_ST_IHdr
#define PHT_CTRL_ST_IHdr 0x00400000
Definition at line 82 of file iLink_internal.h.
PHT_CTRL_ST_PHTRst
#define PHT_CTRL_ST_PHTRst 0x00200000
Definition at line 81 of file iLink_internal.h.
PHT_CTRL_ST_PRBR
#define PHT_CTRL_ST_PRBR 0x00000200
Definition at line 74 of file iLink_internal.h.
PHT_CTRL_ST_PStk
#define PHT_CTRL_ST_PStk 0x00000400
Definition at line 75 of file iLink_internal.h.
PHY_CONFIG_GAP_CNT
#define PHY_CONFIG_GAP_CNT (x) (((x)>>16)&0x3F)
Definition at line 92 of file iLink_internal.h.
PHY_CONFIG_PACKET
#define PHY_CONFIG_PACKET 0xE0
Definition at line 91 of file iLink_internal.h.
PHY_CONFIG_R
#define PHY_CONFIG_R (x) (((x)>>23)&0x01)
Definition at line 94 of file iLink_internal.h.
PHY_CONFIG_ROOT_ID
#define PHY_CONFIG_ROOT_ID (x) (((x)>>24)&0x3F)
Definition at line 95 of file iLink_internal.h.
PHY_CONFIG_T
#define PHY_CONFIG_T (x) (((x)>>22)&0x01)
Definition at line 93 of file iLink_internal.h.
PHY_SELF_ID_PACKET
#define PHY_SELF_ID_PACKET 0xE1
Definition at line 98 of file iLink_internal.h.
PHY_SELF_ID_PKT_SIG
#define PHY_SELF_ID_PKT_SIG 0x2 /* 10b */
Definition at line 99 of file iLink_internal.h.
REG01_IBR
#define REG01_IBR 0x40
Definition at line 109 of file iLink_internal.h.
REG01_RHB
#define REG01_RHB 0x80
Definition at line 110 of file iLink_internal.h.
REG04_LCTRL
#define REG04_LCTRL 0x80
Definition at line 111 of file iLink_internal.h.
REG05_EN_ACCL
#define REG05_EN_ACCL 0x02
Definition at line 113 of file iLink_internal.h.
REG05_EN_MULTI
#define REG05_EN_MULTI 0x01
Definition at line 114 of file iLink_internal.h.
REG05_ISBR
#define REG05_ISBR 0x40
Definition at line 112 of file iLink_internal.h.
REQ_CHECK_CONSOLE_VERSION
#define REQ_CHECK_CONSOLE_VERSION /* Define this to enable version checks on the Playstation 2 console. */
Definition at line 12 of file iLink_internal.h.
REQ_CHECK_MEM_BOUNDARIES
#define REQ_CHECK_MEM_BOUNDARIES /* Define this to enable memory address boundary checking for incoming requests. */
Definition at line 11 of file iLink_internal.h.
SELF_ID_GAP_CNT
#define SELF_ID_GAP_CNT (x) (((x)>>16)&0x3F)
Definition at line 103 of file iLink_internal.h.
SELF_ID_L
#define SELF_ID_L (x) (((x)>>22)&0x01)
Definition at line 102 of file iLink_internal.h.
SELF_ID_M
#define SELF_ID_M (x) (((x)&0x01)
Definition at line 106 of file iLink_internal.h.
SELF_ID_NODEID
#define SELF_ID_NODEID (x) (((x)>>24)&0x3F)
Definition at line 101 of file iLink_internal.h.
SELF_ID_POWER
#define SELF_ID_POWER (x) (((x)>>8)&0x07)
Definition at line 105 of file iLink_internal.h.
SELF_ID_SIGNATURE
#define SELF_ID_SIGNATURE (x) (((x)>>30)&0x03)
Definition at line 100 of file iLink_internal.h.
SELF_ID_SPEED
#define SELF_ID_SPEED (x) (((x)>>14)&0x03)
Definition at line 104 of file iLink_internal.h.
Function Documentation
free()
void free (void * buffer)
Definition at line 63 of file main.c.
 {
     int OldState;
     CpuSuspendIntr(&OldState);
     FreeSysMemory(ptr);
     CpuResumeIntr(OldState);
 }
GetConsoleIDs()
int GetConsoleIDs (u64 * guid, char * ModelName)
Definition at line 52 of file iLink_internal.c.
{
         u64 ilink_id;
         u32 stat;
         int result;
         if(sceCdRI((u8*)&ilink_id, &stat)<0 || stat!=0){
                 result=-1;
                 DEBUG_PRINTF("Error reading console/ILINK ID.\n");
         }
         else{
                 *guid=(ilink_id&0xFFFFFFFF00000000) | ((*(u8*)&ilink_id)|0x08004600);
                 if(sceCdRM(ModelName, &stat)<0 || stat!=0){
                         result=-1;
                         DEBUG_PRINTF("Error reading console model name.\n");
                 }
                 result=0;
         }
         return result;
 }
References DEBUG_PRINTF, result, sceCdRI(), and sceCdRM().
Referenced by _start().
iLinkBusEnable()
void iLinkBusEnable (void)
Definition at line 165 of file iLink_internal.c.
{
         ILINKRegisterBase->ctrl0|=(iLink_CTRL0_RxEn|iLink_CTRL0_TxEn);  /* Enable transmitter and receiver. */
 }
References ILINKMemMap::ctrl0, iLink_CTRL0_RxEn, iLink_CTRL0_TxEn, and ILINKRegisterBase.
Referenced by iLinkEnableSBus().
iLinkDisableIntr()
void iLinkDisableIntr (void)
Definition at line 74 of file iLink_internal.c.
{
         ILINKRegisterBase->intr0Mask=0;
         ILINKRegisterBase->intr1Mask=0;
         ILINKRegisterBase->intr2Mask=0;
         /* Set all interrupt bits, to acknowledge any pending interrupts that there may be. */
         ILINKRegisterBase->intr0=0xFFFFFFFF;
         ILINKRegisterBase->intr1=0xFFFFFFFF;
         ILINKRegisterBase->intr2=0xFFFFFFFF;
 }
References ILINKRegisterBase, ILINKMemMap::intr0, ILINKMemMap::intr0Mask, ILINKMemMap::intr1, ILINKMemMap::intr1Mask, ILINKMemMap::intr2, and ILINKMemMap::intr2Mask.
Referenced by _start().
iLinkEnableCMaster()
void iLinkEnableCMaster (void)
Definition at line 161 of file iLink_internal.c.
{
         ILINKRegisterBase->ctrl0|=iLink_CTRL0_CMstr;
 }
References ILINKMemMap::ctrl0, iLink_CTRL0_CMstr, and ILINKRegisterBase.
Referenced by iLinkSetNodeCapabilities().
iLinkHWInitialize()
void iLinkHWInitialize (void)
Definition at line 134 of file iLink_internal.c.
{
         iLinkPHY_SetLCTRL(0);
         /* Configure the Control 0 register, resetting the transmitter and receiver at the same time. */
 //      ILINKRegisterBase->ctrl0=iLink_CTRL0_TxRst|iLink_CTRL0_RxRst|iLink_CTRL0_RcvSelfID|iLink_CTRL0_BusIDRst|iLink_CTRL0_CycTmrEn|iLink_CTRL0_RetLim(0x0F)|iLink_CTRL0_RSP0|iLink_CTRL0_DELim(3);
         ILINKRegisterBase->ctrl0=iLink_CTRL0_TxRst|iLink_CTRL0_RxRst|iLink_CTRL0_RcvSelfID|iLink_CTRL0_BusIDRst|iLink_CTRL0_CycTmrEn|iLink_CTRL0_RetLim(0x0F)|iLink_CTRL0_DELim(3);
         while(ILINKRegisterBase->ctrl0&(iLink_CTRL0_RxRst|iLink_CTRL0_TxRst)){};
         ILINKRegisterBase->ubufTransmitClear=0; /* Clear UBUF Tx FIFO. */
         ILINKRegisterBase->ubufReceiveClear=0;  /* Clear UBUF Rx FIFO. */
         ILINKRegisterBase->dbufFIFO_lvlR0=DBUF_FIFO_RESET_TX|DBUF_FIFO_RESET_RX;        /* Reset DBUF FIFO 0 */
         ILINKRegisterBase->dbufFIFO_lvlR1=DBUF_FIFO_RESET_TX|DBUF_FIFO_RESET_RX;        /* Reset DBUF FIFO 1 */
         iLinkInitPHT();
         iLinkEnableIntr();
         iLinkWritePhy(5, iLinkReadPhy(5)|REG05_EN_ACCL|REG05_EN_MULTI); /* Enable supported P1394A-2000 enhancements. */
         /* Enable DMA channels 13 and 15. */
         dmac_enable(IOP_DMAC_FDMA0);
         dmac_enable(IOP_DMAC_FDMA2);
         GenerationNumber=0;
         NodeCapabilities=0;
 }
References ILINKMemMap::ctrl0, DBUF_FIFO_RESET_RX, DBUF_FIFO_RESET_TX, ILINKMemMap::dbufFIFO_lvlR0, ILINKMemMap::dbufFIFO_lvlR1, dmac_enable(), GenerationNumber, iLink_CTRL0_BusIDRst, iLink_CTRL0_CycTmrEn, iLink_CTRL0_DELim, iLink_CTRL0_RcvSelfID, iLink_CTRL0_RetLim, iLink_CTRL0_RxRst, iLink_CTRL0_TxRst, iLinkEnableIntr(), iLinkInitPHT(), iLinkPHY_SetLCTRL(), iLinkReadPhy(), ILINKRegisterBase, iLinkWritePhy(), IOP_DMAC_FDMA0, IOP_DMAC_FDMA2, NodeCapabilities, REG05_EN_ACCL, REG05_EN_MULTI, ILINKMemMap::ubufReceiveClear, and ILINKMemMap::ubufTransmitClear.
Referenced by _start().
iLinkInitPHT()
void iLinkInitPHT (void)
Definition at line 32 of file iLink_DMA.c.
{
         /* Stop all DMA-related activities */
         iLinkDMACRegs[0].chcr=iLinkDMACRegs[2].chcr=0;
         ILINKRegisterBase->PHT_ctrl_ST_R0=PHT_CTRL_ST_PHTRst;   /* Reset PHT 00 */
         ILINKRegisterBase->PHT_ctrl_ST_R1=PHT_CTRL_ST_PHTRst;   /* Reset PHT 01 */
         while((ILINKRegisterBase->PHT_ctrl_ST_R0&PHT_CTRL_ST_PHTRst) || (ILINKRegisterBase->PHT_ctrl_ST_R1&PHT_CTRL_ST_PHTRst)){};
         ILINKRegisterBase->dmar=0x00000020;             /* DMA space is within the 2MB of IOP memory. */
         ILINKRegisterBase->PHT_ctrl_ST_R1=PHT_CTRL_ST_EnDMAS|PHT_CTRL_ST_IHdr; /* EnDMAS | IHdr */
         ILINKRegisterBase->PHT_ctrl_ST_R0=0;
         ILINKRegisterBase->STRxNIDSel0_R1=ILINKRegisterBase->STRxNIDSel1_R1=0xFFFFFFFF; /* Accept DMA transfers from all nodes. */
         ILINKRegisterBase->STRxNIDSel0_R0=ILINKRegisterBase->STRxNIDSel1_R0=0;          /* Reject DMA transfers from all nodes. */
         iLinkDMACRegs[0].slice=iLinkDMACRegs[2].slice=0x400;
         iLinkDMACRegs[2].chcr=DMAC_CHCR_AR|DMAC_CHCR_CO;
         iLinkDMACRegs[0].DmarReadStart=iLinkDMACRegs[2].DmarReadStart=iLinkDMARRegs->DmarWriteStart=0x00000800;
         iLinkDMACRegs[0].DmarReadEnd=iLinkDMACRegs[2].DmarReadEnd=iLinkDMARRegs->DmarWriteEnd=0x00200000;
         ILINKRegisterBase->dmaTransTRSH0=0x03FF0000;
         ILINKRegisterBase->dmaTransTRSH1=0x000F03FF;
         ILINKRegisterBase->dmaCtrlSR0=ILINKRegisterBase->dmaCtrlSR1=iLinkDMA_CTRL_SR_LFirst|iLinkDMA_CTRL_SR_DWidth(2)|iLinkDMA_CTRL_SR_DEn|iLinkDMA_CTRL_SR_RActl;
         ILINKRegisterBase->PHT_split_TO_R1=ILINKRegisterBase->PHT_split_TO_R0=0x00000800;       /* STO: 0x800 */
 }
References DMAChannelRegBlock::chcr, DMAC_CHCR_AR, DMAC_CHCR_CO, ILINKMemMap::dmaCtrlSR0, ILINKMemMap::dmaCtrlSR1, ILINKMemMap::dmar, DMAChannelRegBlock::DmarReadEnd, DMAChannelRegBlock::DmarReadStart, DMARRegBlock::DmarWriteEnd, DMARRegBlock::DmarWriteStart, ILINKMemMap::dmaTransTRSH0, ILINKMemMap::dmaTransTRSH1, iLinkDMA_CTRL_SR_DEn, iLinkDMA_CTRL_SR_DWidth, iLinkDMA_CTRL_SR_LFirst, iLinkDMA_CTRL_SR_RActl, iLinkDMACRegs, iLinkDMARRegs, ILINKRegisterBase, PHT_CTRL_ST_EnDMAS, PHT_CTRL_ST_IHdr, PHT_CTRL_ST_PHTRst, ILINKMemMap::PHT_ctrl_ST_R0, ILINKMemMap::PHT_ctrl_ST_R1, ILINKMemMap::PHT_split_TO_R0, ILINKMemMap::PHT_split_TO_R1, DMAChannelRegBlock::slice, ILINKMemMap::STRxNIDSel0_R0, ILINKMemMap::STRxNIDSel0_R1, ILINKMemMap::STRxNIDSel1_R0, and ILINKMemMap::STRxNIDSel1_R1.
Referenced by iLinkHWInitialize(), and iLinkIntrHandler().
iLinkIntrHandler()
int iLinkIntrHandler (void * arg)
Definition at line 313 of file iLink_intr.c.
{
         unsigned int LocalCachedIntr1Register, EventFlagBitsToSet;
 #ifdef REQ_CHECK_DMAC_STAT
         unsigned int i;
 #endif
         while(1){
                 /* Acknowledge interrupts while determining which interrupt events have occurred. Some events need to be acknowledged as early as possible or they will prevent the hardware from working properly. */
                 ILINKRegisterBase->intr0=LocalCachedIntr0Register=ILINKRegisterBase->intr0&ILINKRegisterBase->intr0Mask;
                 ILINKRegisterBase->intr1=LocalCachedIntr1Register=ILINKRegisterBase->intr1&ILINKRegisterBase->intr1Mask;
                 if(!LocalCachedIntr0Register && !LocalCachedIntr1Register) break;
                 EventFlagBitsToSet=0;
                 DEBUG_PRINTF("iLink interrupt: 0x%08x 0x%08x\n", LocalCachedIntr0Register, LocalCachedIntr1Register);
                 if(LocalCachedIntr1Register&iLink_INTR1_UTD) EventFlagBitsToSet|=iLinkEventDataSent;
 #ifdef REQ_CHECK_DMAC_STAT
                 if(LocalCachedIntr0Register&iLink_INTR0_DRFR){
                         iDEBUG_PRINTF("Handling DBUF FIFO data...\n");
                         for(i=0; i<3; i++){
                                 iDEBUG_PRINTF("DMA Channel %d CHCR: 0x%08x MADR: 0x%08x DLEN: 0x%05x SLICE: 0x%03x\n", 13+i, iLinkDMACRegs[i].chcr, iLinkDMACRegs[i].madr, iLinkDMACRegs[i].dlen, iLinkDMACRegs[i].slice);
                                 if((i>0) && !(iLinkDMACRegs[i].chcr&DMAC_CHCR_AR)){
                                         iLinkDMACRegs[i].chcr=0;
                                         switch(i){
                                                 case 1:
                                                         ILINKRegisterBase->dmaCtrlSR0=0;
                                                         break;
                                                 case 2:
                                                         ILINKRegisterBase->dmaCtrlSR1=0;
                                                         break;
                                         }
                                         iDEBUG_PRINTF("DMAC Channel %d stalled. Flushing FIFOs and reseting PHTs.\n", 13+i);
                                         iLinkInitPHT();
                                 }
                         }
                 }
 #endif
                 if(LocalCachedIntr0Register&iLink_INTR0_PhyRst){
                         iDEBUG_PRINTF("-=Bus reset start detected=-\n");
                         GenerationNumber++;
                         iLinkInitPHT();
                         EventFlagBitsToSet|=(iLinkEventBusReady|iLinkEventBusReset);
                         iDEBUG_PRINTF("-=PHTs initialized=-\n");
                 }
                 if(LocalCachedIntr0Register&iLink_INTR0_URx){
                         EventFlagBitsToSet|=iLinkEventURx;
                 }
                 if(LocalCachedIntr0Register&(iLink_INTR0_InvAck|iLink_INTR0_RetEx|iLink_INTR0_UResp)){
                         EventFlagBitsToSet|=iLinkEventError;
                         iDEBUG_PRINTF("-=Missing/invalid response detected=-\n");
                 }
                 /* For debugging purposes */
 #ifdef REQ_CHECK_ERRORS
                 if(LocalCachedIntr0Register&iLink_INTR0_HdrErr){
                         iDEBUG_PRINTF("-=HdrErr=-\n");
                 }
                 if(LocalCachedIntr0Register&iLink_INTR0_SntBsyAck){
                         iDEBUG_PRINTF("-=iLink_INTR0_SntBsyAck=-\n");
                 }
 #endif
                 if(LocalCachedIntr0Register&iLink_INTR0_PBCntR){
                         EventFlagBitsToSet|=iLinkEventDMATransEnd;
                         iDEBUG_PRINTF("-=End of DMA transfer=-\n");
                 }
                 if(LocalCachedIntr0Register&iLink_INTR0_CmdRst){
                         iDEBUG_PRINTF("-=CmdRst=-\n");
                         iLinkPHYBusReset();
                 }
                 iSetEventFlag(IntrEventFlag, EventFlagBitsToSet);
         }
         return 1;
 }
References DMAChannelRegBlock::chcr, DEBUG_PRINTF, DMAC_CHCR_AR, ILINKMemMap::dmaCtrlSR0, ILINKMemMap::dmaCtrlSR1, GenerationNumber, iDEBUG_PRINTF, iLink_INTR0_CmdRst, iLink_INTR0_DRFR, iLink_INTR0_HdrErr, iLink_INTR0_InvAck, iLink_INTR0_PBCntR, iLink_INTR0_PhyRst, iLink_INTR0_RetEx, iLink_INTR0_SntBsyAck, iLink_INTR0_UResp, iLink_INTR0_URx, iLink_INTR1_UTD, iLinkDMACRegs, iLinkEventBusReady, iLinkEventBusReset, iLinkEventDataSent, iLinkEventDMATransEnd, iLinkEventError, iLinkEventURx, iLinkInitPHT(), iLinkPHYBusReset(), ILINKRegisterBase, ILINKMemMap::intr0, ILINKMemMap::intr0Mask, ILINKMemMap::intr1, ILINKMemMap::intr1Mask, IntrEventFlag, iSetEventFlag(), and LocalCachedIntr0Register.
Referenced by _start().
iLinkIntrRegister0Handler()
void iLinkIntrRegister0Handler (void * arg)
iLinkPHY_SetGapCount()
void iLinkPHY_SetGapCount (unsigned char GapCount)
Definition at line 47 of file iLink_PHY.c.
{
         iLinkWritePhy(1, (iLinkReadPhy(1)&0xC0)|GapCount);
 }
References iLinkReadPhy(), and iLinkWritePhy().
iLinkPHY_SetLCTRL()
void iLinkPHY_SetLCTRL (int LCTRL_status)
Definition at line 51 of file iLink_PHY.c.
{
         unsigned short int Register04value;
         Register04value=iLinkReadPhy(4);
         if(LCTRL_status) Register04value|=REG04_LCTRL;
         else Register04value&=(~REG04_LCTRL);
         iLinkWritePhy(4, Register04value);
 }
References iLinkReadPhy(), iLinkWritePhy(), and REG04_LCTRL.
Referenced by iLinkEnableSBus(), and iLinkHWInitialize().
iLinkPHY_SetRootBit()
void iLinkPHY_SetRootBit (int isRoot)
Definition at line 37 of file iLink_PHY.c.
{
         unsigned short int Register01value;
         Register01value=iLinkReadPhy(1);
         if(isRoot) Register01value|=REG01_RHB;
         else Register01value&=(~REG01_RHB);
         iLinkWritePhy(1, Register01value);
 }
References iLinkReadPhy(), iLinkWritePhy(), and REG01_RHB.
iLinkPHYBusReset()
void iLinkPHYBusReset (void)
Definition at line 61 of file iLink_PHY.c.
{
         iLinkWritePhy(5, iLinkReadPhy(5)|REG05_ISBR);
 }
References iLinkReadPhy(), iLinkWritePhy(), and REG05_ISBR.
Referenced by iLinkIntrHandler(), and iLinkResetSBus().
iLinkReadPHTReq()
int iLinkReadPHTReq (struct TransactionContextData * trContext, unsigned short int offset_high, unsigned int offset_low, void * buffer, unsigned int nBytes)
Definition at line 101 of file iLink_DMA.c.
{
         DEBUG_PRINTF("iLinkReadPHTReq() 0x%08x 0x%08x; nbytes: 0x%08x. Node: 0x%04x.\n", offset_high, offset_low, nBytes, trContext->NodeID);
         TargetBuffer=buffer;
         return(iLinkPHTSendData(trContext, IEEE1394_TCODE_READB, offset_high, offset_low, NULL, nBytes, 0));
 }
References buffer, DEBUG_PRINTF, IEEE1394_TCODE_READB, iLinkPHTSendData(), TransactionContextData::NodeID, NULL, and TargetBuffer.
Referenced by iLinkTrRead().
iLinkReadPhy()
unsigned char iLinkReadPhy (unsigned char address)
Definition at line 22 of file iLink_PHY.c.
{
         ILINKRegisterBase->PHYAccess=(((unsigned int)address)<<24)|RdPhy;
         iLinkPhySync();
         while(!(ILINKRegisterBase->intr0&iLink_INTR0_PhyRRx)){};
         ILINKRegisterBase->intr0=iLink_INTR0_PhyRRx;
         return(ILINKRegisterBase->PHYAccess&0xFF);
 }
References iLink_INTR0_PhyRRx, iLinkPhySync(), ILINKRegisterBase, ILINKMemMap::intr0, ILINKMemMap::PHYAccess, and RdPhy.
Referenced by iLinkHWInitialize(), iLinkPHY_SetGapCount(), iLinkPHY_SetLCTRL(), iLinkPHY_SetRootBit(), and iLinkPHYBusReset().
iLinkReadReq()
int iLinkReadReq (struct TransactionContextData * trContext, unsigned short int offset_high, unsigned int offset_low, void * buffer, unsigned int nBytes)
Definition at line 127 of file iLink_TxRx.c.
{
         unsigned int nBytesToTransfer;
         struct ieee1394_TrPacketHdr TxHeader;
         int result;
         unsigned char tlabel, tCode;
         DEBUG_PRINTF("iLinkTrRead() 0x%08x %08x; nbytes: 0x%08x. Node: 0x%04x.\n", offset_high, offset_low, nBytes, trContext->NodeID);
         TargetBuffer=buffer;
         tlabel=1; /* Note: As the tlabel is the same, multiple simultaneous transactions will probably not be possible. */
         tCode=IEEE1394_TCODE_READQ;
         TxHeader.header= (((unsigned int)trContext->speed)<<16) | (((unsigned int)tlabel) << 10) | (1<<8) | (((unsigned int)tCode) << 4 );
         TxHeader.offset_high=(((unsigned int)trContext->NodeID)<<16)|offset_high;
         TxHeader.offset_low=offset_low;
         TxHeader.misc=nBytes<<16;
         nBytesToTransfer=sizeof(struct ieee1394_TrPacketHdr)-4; /* Quadlet reads do not have the data length field. */
         if((result=iLinkSendData(trContext, (unsigned int *)&TxHeader, nBytesToTransfer>>2, NULL, 0))>=0){
                 result=iLinkSync(nBytesToTransfer);
         }
         return result;
 }
References buffer, DEBUG_PRINTF, ieee1394_TrPacketHdr::header, IEEE1394_TCODE_READQ, iLinkSendData(), iLinkSync(), ieee1394_TrPacketHdr::misc, TransactionContextData::NodeID, NULL, ieee1394_TrPacketHdr::offset_high, ieee1394_TrPacketHdr::offset_low, result, TransactionContextData::speed, and TargetBuffer.
Referenced by iLinkTrRead().
iLinkResetHW()
int iLinkResetHW (void)
Definition at line 112 of file iLink_internal.c.
                       {
         ShutDownDMAChannels();
         /* Turn off, and then turn back on the LINK and PHY. If this is not done, the iLink hardware might not function correctly on some consoles. :( */
         ILINKRegisterBase->UnknownRegister7C=0x40;      /* Shut down. */
         DelayThread(400000);
         ILINKRegisterBase->UnknownRegister7C=0;
         /* If the LINK is off, switch it on. */
         if(!(ILINKRegisterBase->ctrl2&iLink_CTRL2_LPSEn)) ILINKRegisterBase->ctrl2=iLink_CTRL2_LPSEn;
         /* Wait for the clock to stabilize. */
         while(!(ILINKRegisterBase->ctrl2&iLink_CTRL2_SOK)) DelayThread(50);
         return 0;
 }
References ILINKMemMap::ctrl2, DelayThread(), iLink_CTRL2_LPSEn, iLink_CTRL2_SOK, ILINKRegisterBase, ShutDownDMAChannels(), and ILINKMemMap::UnknownRegister7C.
Referenced by _start().
iLinkShutdownHW()
void iLinkShutdownHW (void)
Definition at line 129 of file iLink_internal.c.
{
         ShutDownDMAChannels();
         ILINKRegisterBase->ctrl2&=(~iLink_CTRL2_LPSEn); /* Set the LINK to enter standby mode. */
 }
References ILINKMemMap::ctrl2, iLink_CTRL2_LPSEn, ILINKRegisterBase, and ShutDownDMAChannels().
Referenced by _exit().
iLinkWritePHTReq()
int iLinkWritePHTReq (struct TransactionContextData * trContext, unsigned short int offset_high, unsigned int offset_low, void * buffer, unsigned int nBytes)
Definition at line 110 of file iLink_DMA.c.
{
         DEBUG_PRINTF("iLinkWritePHTReq() 0x%08x 0x%08x; nbytes: 0x%08x. Node: 0x%04x.\n", offset_high, offset_low, nBytes, trContext->NodeID);
         return(iLinkPHTSendData(trContext, IEEE1394_TCODE_WRITEB, offset_high, offset_low, buffer, nBytes, 1));
 }
References buffer, DEBUG_PRINTF, IEEE1394_TCODE_WRITEB, iLinkPHTSendData(), and TransactionContextData::NodeID.
Referenced by iLinkTrWrite().
iLinkWritePhy()
void iLinkWritePhy (unsigned char address, unsigned char data)
Definition at line 32 of file iLink_PHY.c.
{
         ILINKRegisterBase->PHYAccess=(((unsigned int)address)<<24)|(((unsigned int)data)<<16)|WrPhy;
         iLinkPhySync();
 }
References iLinkPhySync(), ILINKRegisterBase, ILINKMemMap::PHYAccess, and WrPhy.
Referenced by iLinkHWInitialize(), iLinkPHY_SetGapCount(), iLinkPHY_SetLCTRL(), iLinkPHY_SetRootBit(), and iLinkPHYBusReset().
iLinkWriteReq()
int iLinkWriteReq (struct TransactionContextData * trContext, unsigned short int offset_high, unsigned int offset_low, void * buffer, unsigned int nBytes)
Definition at line 153 of file iLink_TxRx.c.
{
         unsigned int nBytesToTransfer;
         struct ieee1394_TrPacketHdr TxHeader;
         int result;
         unsigned char tlabel, tCode;
         DEBUG_PRINTF("iLinkTrWrite() 0x%08x %08x; nbytes: 0x%08x. Node: 0x%04x.\n", offset_high, offset_low, nBytes, trContext->NodeID);
         tlabel=1; /* Note: As the tlabel is the same, multiple simultaneous transactions will probably not be possible. */
         tCode=IEEE1394_TCODE_WRITEQ;
         TxHeader.header=(((unsigned int)trContext->speed)<<16) | (((unsigned int)tlabel) << 10) | (1<<8) | (((unsigned int)tCode) << 4 );
         TxHeader.offset_high=(((unsigned int)trContext->NodeID)<<16)|offset_high;
         TxHeader.offset_low=offset_low;
         TxHeader.misc=nBytes<<16;
         nBytesToTransfer=sizeof(struct ieee1394_TrPacketHdr)-4; /* Quadlet writes do not have the data length field. */
         if((result=iLinkSendData(trContext, (unsigned int *)&TxHeader, nBytesToTransfer>>2, buffer, nBytes>>2))>=0){
                 result=iLinkSync(nBytesToTransfer);
         }
         return result;
 }
References buffer, DEBUG_PRINTF, ieee1394_TrPacketHdr::header, IEEE1394_TCODE_WRITEQ, iLinkSendData(), iLinkSync(), ieee1394_TrPacketHdr::misc, TransactionContextData::NodeID, ieee1394_TrPacketHdr::offset_high, ieee1394_TrPacketHdr::offset_low, result, and TransactionContextData::speed.
Referenced by iLinkTrWrite().
InitializeConfigurationROM()
void InitializeConfigurationROM (void)
Definition at line 224 of file iLink_crom.c.
{
         register unsigned int i;
         for(i=0; i<16; i++) ExtraCROMUnits[i]=NULL;
         nExtraCROMUnits=0;
         ConfigurationROM=NULL;
         LinkSpeed=4;
         CycleClkAcc=~0;
         Max_Rec=10;
         BuildConfigurationROM();
 }
References BuildConfigurationROM(), ConfigurationROM, CycleClkAcc, ExtraCROMUnits, LinkSpeed, Max_Rec, nExtraCROMUnits, and NULL.
Referenced by _start(), and iLinkSetNodeCapabilities().
malloc()
void* malloc (unsigned int nBytes)
Definition at line 169 of file iLink_internal.c.
{
         int OldState;
         void *result;
         CpuSuspendIntr(&OldState);
         result=AllocSysMemory(ALLOC_FIRST, nBytes, NULL);
         CpuResumeIntr(OldState);
         return result;
 }
References ALLOC_FIRST, AllocSysMemory(), CpuResumeIntr(), CpuSuspendIntr(), NULL, and result.
PHTSendResponse()
void PHTSendResponse (unsigned short int NodeID, unsigned short RcvdBusID, unsigned char rcode, unsigned char tLabel, unsigned char tCode, unsigned char speed, unsigned int * buffer, unsigned int nQuads)
SendResponse()
void SendResponse (unsigned short int NodeID, unsigned short RcvdBusID, unsigned char rcode, unsigned char tLabel, unsigned char tCode, unsigned char speed, unsigned int * buffer, unsigned int nQuads)
Definition at line 73 of file iLink_TxRx.c.
{
         struct ieee1394_TrResponsePacketHdr ResponseHeader;
         unsigned int ResponseHeaderLength;
         ResponseHeaderLength=(tCode==IEEE1394_TCODE_READB_RESPONSE)?4:3;
         DEBUG_PRINTF("Sending response to: 0x%04x, RcvdBusID: 0x%04x, rcode: %d, Header length: %u, speed: 0x%04x. Payload length: 0x%08x.\n", NodeID, RcvdBusID, rCode, ResponseHeaderLength, speed, nQuads);
         DEBUG_PRINTF("tCode: 0x%02x\n", tCode);
         ResponseHeader.header=(((unsigned int)RcvdBusID)<<22) | (((unsigned int)speed)<<16) | (((unsigned int)tLabel)<<10) | (1<<8) | (((unsigned int)tCode)<<4);
         ResponseHeader.header2=(((unsigned int)NodeID)<<16) | (((unsigned int)rCode)<<12);
         ResponseHeader.reserved=0;
         ResponseHeader.LastField=nQuads<<18;
         iLinkSendData(NULL, (unsigned int *)&ResponseHeader, ResponseHeaderLength, buffer, nQuads);
 }
References buffer, DEBUG_PRINTF, ieee1394_TrResponsePacketHdr::header, ieee1394_TrResponsePacketHdr::header2, IEEE1394_TCODE_READB_RESPONSE, iLinkSendData(), ieee1394_TrResponsePacketHdr::LastField, NULL, and ieee1394_TrResponsePacketHdr::reserved.
Referenced by ReadRequestHandler(), and WriteRequestHandler().
UBUFThread()
void UBUFThread (void * arg)
Definition at line 34 of file iLink_internal.c.
{
         void (*RequestResponseHandler)(unsigned int header, volatile unsigned int *buffer, unsigned int nQuads);
         unsigned int data, DataBufferLevel;
         u32 ef_bits;
         while(1){
                 WaitEventFlag(IntrEventFlag, iLinkEventBusReset|iLinkEventURx, WEF_OR, &ef_bits);
                 ClearEventFlag(IntrEventFlag, ~(iLinkEventBusReset|iLinkEventURx));
                 while((DataBufferLevel=ILINKRegisterBase->ubufReceiveLevel)>0){
                         data=ILINKRegisterBase->ubufReceive;
                         iDEBUG_PRINTF("Handling UBUF data... handler: 0x%02lx.\n", (data>>4)&0xF);
                         RequestResponseHandler=RequestHandlers[(data>>4)&0xF];
                         RequestResponseHandler(data, (volatile unsigned int *)&ILINKRegisterBase->ubufReceive, DataBufferLevel-1);
                 }
         }
 }
References buffer, ClearEventFlag(), iDEBUG_PRINTF, iLinkEventBusReset, iLinkEventURx, ILINKRegisterBase, IntrEventFlag, RequestHandlers, ILINKMemMap::ubufReceive, ILINKMemMap::ubufReceiveLevel, WaitEventFlag(), and WEF_OR.
Referenced by _start().