ps2sdk: iop/iLink/iLinkman/include/iLinkman.h File Reference
iLinkman.h File Reference
#include <types.h>
#include <irx.h>
Macros
#define BSWAP32(x) ((x<<24)|((x&0xff00)<<8)|((x&0xff0000)>>8)|(x>>24))
#define BSWAP16(x) ((((unsigned short int)x)<<8)|(x>>8))
#define S100 0
#define S200 1
#define S400 2
#define iLink_NODE_IRMC 0x10
#define iLink_NODE_CMC 0x08
#define iLink_NODE_ISC 0x04
#define iLink_NODE_BMC 0x02
#define iLink_NODE_PMC 0x01
#define iLink_CB_WRITE_REQUEST 0x01
#define iLink_CB_READ_REQUEST 0x02
#define iLink_CB_LOCK_REQUEST 0x04
#define iLink_CB_BUS_RESET 0x08
#define iLinkman_IMPORTS_start DECLARE_IMPORT_TABLE(iLinkman, 1, 1)
#define iLinkman_IMPORTS_end END_IMPORT_TABLE
#define I_iLinkEnableSBus DECLARE_IMPORT(4, iLinkEnableSBus)
#define I_iLinkDisableSBus DECLARE_IMPORT(5, iLinkDisableSBus)
#define I_iLinkResetSBus DECLARE_IMPORT(6, iLinkResetSBus)
#define I_iLinkSetNodeCapabilities DECLARE_IMPORT(7, iLinkSetNodeCapabilities)
#define I_iLinkSetTrCallbackHandler DECLARE_IMPORT(8, iLinkSetTrCallbackHandler)
#define I_iLinkGetGenerationNumber DECLARE_IMPORT(9, iLinkGetGenerationNumber)
#define I_iLinkGetLocalNodeID DECLARE_IMPORT(10, iLinkGetLocalNodeID)
#define I_iLinkGetNodeCount DECLARE_IMPORT(11, iLinkGetNodeCount)
#define I_iLinkTrAlloc DECLARE_IMPORT(12, iLinkTrAlloc)
#define I_iLinkTrFree DECLARE_IMPORT(13, iLinkTrFree)
#define I_iLinkTrWrite DECLARE_IMPORT(14, iLinkTrWrite)
#define I_iLinkTrRead DECLARE_IMPORT(15, iLinkTrRead)
#define I_iLinkCalculateCRC16 DECLARE_IMPORT(16, iLinkCalculateCRC16)
#define I_iLinkAddCROMUnit DECLARE_IMPORT(17, iLinkAddCROMUnit)
#define I_iLinkDeleteCROMUnit DECLARE_IMPORT(18, iLinkDeleteCROMUnit)
#define I_iLinkGetNodeCapabilities DECLARE_IMPORT(19, iLinkGetNodeCapabilities)
#define I_iLinkGetNodeMaxSpeed DECLARE_IMPORT(20, iLinkGetNodeMaxSpeed)
#define I_iLinkGetNodeTrSpeed DECLARE_IMPORT(21, iLinkGetNodeTrSpeed)
#define I_iLinkSetNodeTrSpeed DECLARE_IMPORT(22, iLinkSetNodeTrSpeed)
#define I_iLinkFindUnit DECLARE_IMPORT(23, iLinkFindUnit)
#define I_iLinkReadCROM DECLARE_IMPORT(24, iLinkReadCROM)
#define I_iLinkGetLocalNodeEUI64 DECLARE_IMPORT(12, iLinkGetLocalNodeEUI64)
Functions
void iLinkEnableSBus (void)
void iLinkDisableSBus (void)
void iLinkResetSBus (void)
unsigned int iLinkSetNodeCapabilities (unsigned int capabilities)
void * iLinkSetTrCallbackHandler (void *function)
int iLinkGetGenerationNumber (void)
int iLinkGetLocalNodeID (void)
int iLinkGetNodeCount (void)
int iLinkTrAlloc (unsigned short int NodeID, unsigned char speed)
void iLinkTrFree (int trContext)
int iLinkTrWrite (int trContext, unsigned short int offset_high, unsigned int offset_low, void *buffer, unsigned int nBytes)
int iLinkTrRead (int trContext, unsigned short int offset_high, unsigned int offset_low, void *buffer, unsigned int nBytes)
unsigned short int iLinkCalculateCRC16 (void *data, unsigned int nQuads)
int iLinkAddCROMUnit (unsigned int *data, unsigned int nQuads)
void iLinkDeleteCROMUnit (unsigned int id)
int iLinkGetNodeCapabilities (unsigned short NodeID)
int iLinkGetNodeMaxSpeed (unsigned short int NodeID)
int iLinkGetNodeTrSpeed (int trContext)
int iLinkSetNodeTrSpeed (int trContext, unsigned char speed)
int iLinkFindUnit (int UnitInList, unsigned int UnitSpec, unsigned int UnitSW_Version)
int iLinkReadCROM (unsigned short int NodeID, unsigned int Offset, unsigned int nQuads, unsigned int *buffer)
u64 iLinkGetLocalNodeEUI64 (void)
Macro Definition Documentation
BSWAP16
#define BSWAP16 (x) ((((unsigned short int)x)<<8)|(x>>8))
Definition at line 15 of file iLinkman.h.
BSWAP32
#define BSWAP32 (x) ((x<<24)|((x&0xff00)<<8)|((x&0xff0000)>>8)|(x>>24))
Definition at line 14 of file iLinkman.h.
I_iLinkAddCROMUnit
#define I_iLinkAddCROMUnit DECLARE_IMPORT(17, iLinkAddCROMUnit)
Definition at line 78 of file iLinkman.h.
I_iLinkCalculateCRC16
#define I_iLinkCalculateCRC16 DECLARE_IMPORT(16, iLinkCalculateCRC16)
Definition at line 77 of file iLinkman.h.
I_iLinkDeleteCROMUnit
#define I_iLinkDeleteCROMUnit DECLARE_IMPORT(18, iLinkDeleteCROMUnit)
Definition at line 79 of file iLinkman.h.
I_iLinkDisableSBus
#define I_iLinkDisableSBus DECLARE_IMPORT(5, iLinkDisableSBus)
Definition at line 66 of file iLinkman.h.
I_iLinkEnableSBus
#define I_iLinkEnableSBus DECLARE_IMPORT(4, iLinkEnableSBus)
Definition at line 65 of file iLinkman.h.
I_iLinkFindUnit
#define I_iLinkFindUnit DECLARE_IMPORT(23, iLinkFindUnit)
Definition at line 84 of file iLinkman.h.
I_iLinkGetGenerationNumber
#define I_iLinkGetGenerationNumber DECLARE_IMPORT(9, iLinkGetGenerationNumber)
Definition at line 70 of file iLinkman.h.
I_iLinkGetLocalNodeEUI64
#define I_iLinkGetLocalNodeEUI64 DECLARE_IMPORT(12, iLinkGetLocalNodeEUI64)
Definition at line 86 of file iLinkman.h.
I_iLinkGetLocalNodeID
#define I_iLinkGetLocalNodeID DECLARE_IMPORT(10, iLinkGetLocalNodeID)
Definition at line 71 of file iLinkman.h.
I_iLinkGetNodeCapabilities
#define I_iLinkGetNodeCapabilities DECLARE_IMPORT(19, iLinkGetNodeCapabilities)
Definition at line 80 of file iLinkman.h.
I_iLinkGetNodeCount
#define I_iLinkGetNodeCount DECLARE_IMPORT(11, iLinkGetNodeCount)
Definition at line 72 of file iLinkman.h.
I_iLinkGetNodeMaxSpeed
#define I_iLinkGetNodeMaxSpeed DECLARE_IMPORT(20, iLinkGetNodeMaxSpeed)
Definition at line 81 of file iLinkman.h.
I_iLinkGetNodeTrSpeed
#define I_iLinkGetNodeTrSpeed DECLARE_IMPORT(21, iLinkGetNodeTrSpeed)
Definition at line 82 of file iLinkman.h.
I_iLinkReadCROM
#define I_iLinkReadCROM DECLARE_IMPORT(24, iLinkReadCROM)
Definition at line 85 of file iLinkman.h.
I_iLinkResetSBus
#define I_iLinkResetSBus DECLARE_IMPORT(6, iLinkResetSBus)
Definition at line 67 of file iLinkman.h.
I_iLinkSetNodeCapabilities
#define I_iLinkSetNodeCapabilities DECLARE_IMPORT(7, iLinkSetNodeCapabilities)
Definition at line 68 of file iLinkman.h.
I_iLinkSetNodeTrSpeed
#define I_iLinkSetNodeTrSpeed DECLARE_IMPORT(22, iLinkSetNodeTrSpeed)
Definition at line 83 of file iLinkman.h.
I_iLinkSetTrCallbackHandler
#define I_iLinkSetTrCallbackHandler DECLARE_IMPORT(8, iLinkSetTrCallbackHandler)
Definition at line 69 of file iLinkman.h.
I_iLinkTrAlloc
#define I_iLinkTrAlloc DECLARE_IMPORT(12, iLinkTrAlloc)
Definition at line 73 of file iLinkman.h.
I_iLinkTrFree
#define I_iLinkTrFree DECLARE_IMPORT(13, iLinkTrFree)
Definition at line 74 of file iLinkman.h.
I_iLinkTrRead
#define I_iLinkTrRead DECLARE_IMPORT(15, iLinkTrRead)
Definition at line 76 of file iLinkman.h.
I_iLinkTrWrite
#define I_iLinkTrWrite DECLARE_IMPORT(14, iLinkTrWrite)
Definition at line 75 of file iLinkman.h.
iLink_CB_BUS_RESET
#define iLink_CB_BUS_RESET 0x08
Definition at line 31 of file iLinkman.h.
iLink_CB_LOCK_REQUEST
#define iLink_CB_LOCK_REQUEST 0x04
Definition at line 30 of file iLinkman.h.
iLink_CB_READ_REQUEST
#define iLink_CB_READ_REQUEST 0x02
Definition at line 29 of file iLinkman.h.
iLink_CB_WRITE_REQUEST
#define iLink_CB_WRITE_REQUEST 0x01
Definition at line 28 of file iLinkman.h.
iLink_NODE_BMC
#define iLink_NODE_BMC 0x02
Definition at line 25 of file iLinkman.h.
iLink_NODE_CMC
#define iLink_NODE_CMC 0x08
Definition at line 23 of file iLinkman.h.
iLink_NODE_IRMC
#define iLink_NODE_IRMC 0x10
Definition at line 22 of file iLinkman.h.
iLink_NODE_ISC
#define iLink_NODE_ISC 0x04
Definition at line 24 of file iLinkman.h.
iLink_NODE_PMC
#define iLink_NODE_PMC 0x01
Definition at line 26 of file iLinkman.h.
iLinkman_IMPORTS_end
#define iLinkman_IMPORTS_end END_IMPORT_TABLE
Definition at line 63 of file iLinkman.h.
iLinkman_IMPORTS_start
#define iLinkman_IMPORTS_start DECLARE_IMPORT_TABLE(iLinkman, 1, 1)
Definition at line 62 of file iLinkman.h.
S100
#define S100 0
Definition at line 18 of file iLinkman.h.
S200
#define S200 1
Definition at line 19 of file iLinkman.h.
S400
#define S400 2
Definition at line 20 of file iLinkman.h.
Function Documentation
iLinkAddCROMUnit()
int iLinkAddCROMUnit (unsigned int * data, unsigned int nQuads)
Definition at line 60 of file iLink_crom.c.
{
         unsigned int i, CROM_EntrySizeInBytes;
         int result;
         result = -1002;
         for(i=0; i<16; i++){
                 if(ExtraCROMUnits[i]==NULL){
                         CROM_EntrySizeInBytes=nQuads*4;
                         if((ExtraCROMUnits[i]=malloc(CROM_EntrySizeInBytes))!=NULL){
                                 ExtraCROMUnitsSize[i]=CROM_EntrySizeInBytes;
                                 ieee1394Swab32(ExtraCROMUnits[i], data, nQuads);
                                 nExtraCROMUnits++;
                                 BuildConfigurationROM();
                                 result = i;
                         }
                         break;
                 }
         }
         return result;
 }
References BuildConfigurationROM(), ExtraCROMUnits, ExtraCROMUnitsSize, ieee1394Swab32(), malloc, nExtraCROMUnits, NULL, and result.
iLinkCalculateCRC16()
unsigned short int iLinkCalculateCRC16 (void * data, unsigned int nQuads)
Definition at line 43 of file iLink_crom.c.
{
         int i, lShift;
         unsigned int lData, lSum;
         unsigned short int lCRC = 0;
         for ( i = 0; i < nQuads; ++i ) {
                 lData = ((unsigned int *)data)[i];
                 for ( lShift = 28; lShift >= 0; lShift -= 4 ) {
                         lSum = (  ( lCRC >> 12 ) ^ ( lData >> lShift )  ) & 15;
                         lCRC = ( lCRC << 4 ) ^ ( lSum << 12 ) ^ ( lSum << 5 ) ^ lSum;
                 }  /* end for */
                 lCRC &= 0xFFFF;
         }  /* end for */
         return lCRC;
 }
Referenced by BuildConfigurationROM().
iLinkDeleteCROMUnit()
void iLinkDeleteCROMUnit (unsigned int id)
Definition at line 86 of file iLink_crom.c.
{
         free(ExtraCROMUnits[id]);
         ExtraCROMUnits[id]=NULL;
         BuildConfigurationROM();
         nExtraCROMUnits--;
 }
References BuildConfigurationROM(), ExtraCROMUnits, free, nExtraCROMUnits, and NULL.
iLinkDisableSBus()
void iLinkDisableSBus (void)
Definition at line 206 of file iLink.c.
{
         ILINKRegisterBase->ctrl0&=~(iLink_CTRL0_RxEn|iLink_CTRL0_TxEn);         /* CTL0: ~(TxEn | RxEn) */
 }
References ILINKMemMap::ctrl0, iLink_CTRL0_RxEn, iLink_CTRL0_TxEn, and ILINKRegisterBase.
iLinkEnableSBus()
void iLinkEnableSBus (void)
Definition at line 200 of file iLink.c.
{
         iLinkPHY_SetLCTRL(1);
         iLinkBusEnable();
         iLinkResetSBus();
 }
References iLinkBusEnable(), iLinkPHY_SetLCTRL(), and iLinkResetSBus().
Referenced by init_ieee1394DiskDriver().
iLinkFindUnit()
int iLinkFindUnit (int UnitInList, unsigned int UnitSpec, unsigned int UnitSW_Version)
Definition at line 174 of file iLink_crom.c.
{
         int result;
         unsigned int CurrentUnitSW_Version, CurrentUnitSpec;
         unsigned short int NodeID;
         DEBUG_PRINTF("iLinkFindUnit() %d UnitSpec: 0x%08x; UnitSW Version: 0x%08x.\n", UnitInList, UnitSpec, UnitSW_Version);
         result=-1;
         if(UnitInList<nNodes){
                 NodeID=(unsigned short int)SELF_ID_NODEID(NodeData[UnitInList])|(LocalNodeID&0xFFC0);
                 CurrentUnitSW_Version=CurrentUnitSpec=0;
                 if((result=ParseUnitCROM(NodeID, &CurrentUnitSpec, &CurrentUnitSW_Version))>=0){
                         result=((CurrentUnitSW_Version==UnitSW_Version)&&(CurrentUnitSpec==UnitSpec))?NodeID:(-1);
                 }
         }
         return result;
 }
References DEBUG_PRINTF, LocalNodeID, nNodes, NodeData, ParseUnitCROM(), result, and SELF_ID_NODEID.
Referenced by iLinkIntrCBHandlingThread().
iLinkGetGenerationNumber()
int iLinkGetGenerationNumber (void)
Definition at line 188 of file iLink.c.
{
         return(GenerationNumber);
 }
References GenerationNumber.
Referenced by iLinkIntrCBHandlingThread().
iLinkGetLocalNodeEUI64()
u64 iLinkGetLocalNodeEUI64 (void)
Definition at line 266 of file iLink.c.
{
         return ConsoleGUID;
 }
References ConsoleGUID.
iLinkGetLocalNodeID()
int iLinkGetLocalNodeID (void)
Definition at line 192 of file iLink.c.
{
         return(LocalNodeID);
 }
References LocalNodeID.
Referenced by iLinkIntrCBHandlingThread().
iLinkGetNodeCapabilities()
int iLinkGetNodeCapabilities (unsigned short NodeID)
Definition at line 94 of file iLink_crom.c.
{
         int result;
         unsigned int data;
         if(NodeID==LocalNodeID) return NodeCapabilities;
         result=iLinkReadCROM(NodeID, 8, 1, &data);
         result=(result<0)?(-1):(int)(data>>27);
         return result;
 }
References iLinkReadCROM(), LocalNodeID, NodeCapabilities, and result.
iLinkGetNodeCount()
int iLinkGetNodeCount (void)
Definition at line 196 of file iLink.c.
{
         return(nNodes);
 }
References nNodes.
Referenced by iLinkIntrCBHandlingThread().
iLinkGetNodeMaxSpeed()
int iLinkGetNodeMaxSpeed (unsigned short int NodeID)
Definition at line 106 of file iLink_crom.c.
{
         unsigned int i;
         int result;
         result=-1;
         for(i=0; i<nNodes; i++){
                 if(SELF_ID_NODEID(NodeData[i])==(NodeID&0x3F)){
                         result=SELF_ID_SPEED(NodeData[i]);
                         break;
                 }
         }
         return result;
 }
References nNodes, NodeData, result, SELF_ID_NODEID, and SELF_ID_SPEED.
Referenced by iLinkIntrCBHandlingThread().
iLinkGetNodeTrSpeed()
int iLinkGetNodeTrSpeed (int trContext)
Definition at line 237 of file iLink.c.
{
         int CurrentSpeed, i;
         CurrentSpeed=-1;
         for(i=0; i<3; i++){
                 if(speeds[i]==TransactionContexts[trContext].speed){
                         CurrentSpeed=i;
                         break;
                 }
         }
         return CurrentSpeed;
 }
References TransactionContextData::speed, speeds, and TransactionContexts.
Referenced by iLinkIntrCBHandlingThread(), and iLinkSetNodeTrSpeed().
iLinkReadCROM()
int iLinkReadCROM (unsigned short int NodeID, unsigned int Offset, unsigned int nQuads, unsigned int * buffer)
Definition at line 194 of file iLink_crom.c.
{
         unsigned int i;
         int result, trContext, retries;
         DEBUG_PRINTF("Reading CROM of node 0x%04x, offset: %u, nquads: %u.\n", NodeID, Offset, nQuads);
         result=-1;
         if((trContext=iLinkTrAlloc(NodeID, S100))<0) return trContext;
         for(i=0; i<nQuads; i++){
                 retries=10;
                 do{
                         if((result=iLinkTrRead(trContext, 0x0000FFFF, 0xF0000400+(Offset<<2), buffer, 4))>=0){
                                 *buffer=BSWAP32(*buffer);
                                 buffer++;
                                 Offset++;
                         }
                         else{
                                 DelayThread(100000);
                                 retries--;
                         }
                 }while((result<0)&&(retries>0));
                 if(retries==0) break;
         }
         iLinkTrFree(trContext);
         return result;
 }
References BSWAP32, buffer, DEBUG_PRINTF, DelayThread(), iLinkTrAlloc(), iLinkTrFree(), iLinkTrRead(), result, and S100.
Referenced by iLinkGetNodeCapabilities(), initSBP2Disk(), and ParseUnitCROM().
iLinkResetSBus()
void iLinkResetSBus (void)
Definition at line 210 of file iLink.c.
{
         ClearEventFlag(IntrEventFlag, ~(iLinkEventBusReady|iLinkEventGotSELFIDs));
         DEBUG_PRINTF("-=Reseting bus=-\n");
         iLinkPHYBusReset();
         DEBUG_PRINTF("-=Waiting for the serial bus to be ready=-\n");
         WaitEventFlag(IntrEventFlag, iLinkEventBusReady|iLinkEventGotSELFIDs, WEF_AND, NULL); /* Wait for the bus to be completely reset. */
         DEBUG_PRINTF("-=Bus reset and ready=-\n");
 }
References ClearEventFlag(), DEBUG_PRINTF, iLinkEventBusReady, iLinkEventGotSELFIDs, iLinkPHYBusReset(), IntrEventFlag, NULL, WaitEventFlag(), and WEF_AND.
Referenced by iLinkEnableSBus().
iLinkSetNodeCapabilities()
unsigned int iLinkSetNodeCapabilities (unsigned int capabilities)
Definition at line 178 of file iLink.c.
{
         NodeCapabilities=capabilities;
         /* Enable the enabled iLink features. */
         if(NodeCapabilities&iLink_NODE_CMC) iLinkEnableCMaster();
         InitializeConfigurationROM();
         return(NodeCapabilities);
 }
References iLink_NODE_CMC, iLinkEnableCMaster(), InitializeConfigurationROM(), and NodeCapabilities.
iLinkSetNodeTrSpeed()
int iLinkSetNodeTrSpeed (int trContext, unsigned char speed)
Definition at line 251 of file iLink.c.
{
         int result;
         result=iLinkGetNodeTrSpeed(trContext);
         /* !!HACK!! Due to a chip bug (?) in the iLink hardware of most consoles, limit the speed to S100 mode whenever the console is the root node
                 (Read the README file for more details on this bug). */
         if(IsBusRoot) speed=S100;
         /* Assign the specified speed to the specified transaction. Assign the maxium allowed speed if the specified speed is above the maximum value. */
         TransactionContexts[trContext].speed=(speed>(sizeof(speeds)-1))?speeds[sizeof(speeds)-1]:speeds[speed];
         return result;
 }
References iLinkGetNodeTrSpeed(), IsBusRoot, result, S100, TransactionContextData::speed, speeds, and TransactionContexts.
Referenced by iLinkTrAlloc().
iLinkSetTrCallbackHandler()
void* iLinkSetTrCallbackHandler (void * function)
Definition at line 222 of file iLink.c.
{
         void *cb_function;
         cb_function=CallBackFunction;
         CallBackFunction=function;
         return cb_function;
 }
References CallBackFunction.
Referenced by init_ieee1394DiskDriver().
iLinkTrAlloc()
int iLinkTrAlloc (unsigned short int NodeID, unsigned char speed)
Definition at line 144 of file iLink.c.
{
         int result;
         unsigned int i;
         if(NodeID!=LocalNodeID){
                 for(i=0; i<MAX_CONCURRENT_TRANSACTIONS; i++){
                         if(TransactionContexts[i].IsConnected==0){
                                 TransactionContexts[i].NodeID=NodeID;
                                 TransactionContexts[i].GenerationNumber=GenerationNumber;
                                 TransactionContexts[i].IsConnected=1;
                                 iLinkSetNodeTrSpeed(i, speed);
                                 break;
                         }
                 }
                 result=(i==MAX_CONCURRENT_TRANSACTIONS)?-1002:i;
         }
         else result = -1;
         return result;
 }
References GenerationNumber, TransactionContextData::GenerationNumber, iLinkSetNodeTrSpeed(), TransactionContextData::IsConnected, LocalNodeID, MAX_CONCURRENT_TRANSACTIONS, TransactionContextData::NodeID, result, TransactionContextData::speed, and TransactionContexts.
Referenced by iLinkIntrCBHandlingThread(), and iLinkReadCROM().
iLinkTrFree()
void iLinkTrFree (int trContext)
Definition at line 166 of file iLink.c.
{
         TransactionContexts[trContext].IsConnected=0;
 }
References TransactionContextData::IsConnected, and TransactionContexts.
Referenced by iLinkIntrCBHandlingThread(), and iLinkReadCROM().
iLinkTrRead()
int iLinkTrRead (int trContext, unsigned short int offset_high, unsigned int offset_low, void * buffer, unsigned int nBytes)
Definition at line 174 of file iLink.c.
{
         return((nBytes==4)?iLinkReadReq(&TransactionContexts[trContext], offset_high, offset_low, buffer, nBytes):iLinkReadPHTReq(&TransactionContexts[trContext], offset_high,offset_low, buffer, nBytes));
 }
References buffer, iLinkReadPHTReq(), iLinkReadReq(), and TransactionContexts.
Referenced by ieee1394_GetFetchAgentState(), and iLinkReadCROM().
iLinkTrWrite()
int iLinkTrWrite (int trContext, unsigned short int offset_high, unsigned int offset_low, void * buffer, unsigned int nBytes)
Definition at line 170 of file iLink.c.
{
         return((nBytes==4)?iLinkWriteReq(&TransactionContexts[trContext], offset_high, offset_low, buffer, nBytes):iLinkWritePHTReq(&TransactionContexts[trContext], offset_high,offset_low, buffer, nBytes));
 }
References buffer, iLinkWritePHTReq(), iLinkWriteReq(), and TransactionContexts.
Referenced by ieee1394_InitializeFetchAgent(), ieee1394_ResetFetchAgent(), ieee1394_SendCommandBlockORB(), and ieee1394_SendManagementORB().