ps2sdk: iop/iLink/iLinkman/src/iLink_TxRx.c File Reference
iLink_TxRx.c File Reference
#include <intrman.h>
#include <stdio.h>
#include <sysmem.h>
#include <thbase.h>
#include <thevent.h>
#include <thsemap.h>
#include "iLinkman.h"
#include "iLink_internal.h"
Functions
static int iLinkSendData (struct TransactionContextData *trContext, unsigned int *header, unsigned int HeaderLength, unsigned int *payload, unsigned int PayloadLength)
void SendResponse (unsigned short int NodeID, unsigned short RcvdBusID, unsigned char rCode, unsigned char tLabel, unsigned char tCode, unsigned char speed, unsigned int *buffer, unsigned int nQuads)
static unsigned int TimeoutCallbackFunction (void *argv)
static int iLinkSync (unsigned int PayloadLength)
int iLinkReadReq (struct TransactionContextData *trContext, unsigned short int offset_high, unsigned int offset_low, void *buffer, unsigned int nBytes)
int iLinkWriteReq (struct TransactionContextData *trContext, unsigned short int offset_high, unsigned int offset_low, void *buffer, unsigned int nBytes)
Variables
unsigned short int LocalNodeID
int GenerationNumber
int IntrEventFlag
struct ILINKMemMap * ILINKRegisterBase
struct DMAChannelRegBlock * iLinkDMACRegs
unsigned * TargetBuffer
unsigned int LocalCachedIntr0Register
int UBUFTxSema
static iop_sys_clock_t Timeout
Function Documentation
iLinkReadReq()
int iLinkReadReq (struct TransactionContextData * trContext, unsigned short int offset_high, unsigned int offset_low, void * buffer, unsigned int nBytes)
Definition at line 127 of file iLink_TxRx.c.
{
         unsigned int nBytesToTransfer;
         struct ieee1394_TrPacketHdr TxHeader;
         int result;
         unsigned char tlabel, tCode;
         DEBUG_PRINTF("iLinkTrRead() 0x%08x %08x; nbytes: 0x%08x. Node: 0x%04x.\n", offset_high, offset_low, nBytes, trContext->NodeID);
         TargetBuffer=buffer;
         tlabel=1; /* Note: As the tlabel is the same, multiple simultaneous transactions will probably not be possible. */
         tCode=IEEE1394_TCODE_READQ;
         TxHeader.header= (((unsigned int)trContext->speed)<<16) | (((unsigned int)tlabel) << 10) | (1<<8) | (((unsigned int)tCode) << 4 );
         TxHeader.offset_high=(((unsigned int)trContext->NodeID)<<16)|offset_high;
         TxHeader.offset_low=offset_low;
         TxHeader.misc=nBytes<<16;
         nBytesToTransfer=sizeof(struct ieee1394_TrPacketHdr)-4; /* Quadlet reads do not have the data length field. */
         if((result=iLinkSendData(trContext, (unsigned int *)&TxHeader, nBytesToTransfer>>2, NULL, 0))>=0){
                 result=iLinkSync(nBytesToTransfer);
         }
         return result;
 }
References buffer, DEBUG_PRINTF, ieee1394_TrPacketHdr::header, IEEE1394_TCODE_READQ, iLinkSendData(), iLinkSync(), ieee1394_TrPacketHdr::misc, TransactionContextData::NodeID, NULL, ieee1394_TrPacketHdr::offset_high, ieee1394_TrPacketHdr::offset_low, result, TransactionContextData::speed, and TargetBuffer.
Referenced by iLinkTrRead().
iLinkSendData()
static int iLinkSendData (struct TransactionContextData * trContext, unsigned int * header, unsigned int HeaderLength, unsigned int * payload, unsigned int PayloadLength) static
Definition at line 31 of file iLink_TxRx.c.
{
         unsigned int i, *data;
         u32 FlagBits;
         WaitSema(UBUFTxSema);
         ClearEventFlag(IntrEventFlag, ~(iLinkEventDataSent|iLinkEventDataReceived|iLinkEventError));
         ILINKRegisterBase->ubufTransmitClear=0;
         data=header;
         /* Transmit the header... */
         for(i=0; i<HeaderLength; i++){
                 if((trContext!=NULL)&&(trContext->GenerationNumber!=GenerationNumber)) return(-1021);
                 ILINKRegisterBase->ubufTransmitNext=*data;
                 data++;
         }
         /* Now transmit the payload. */
         if(PayloadLength>0){
                 data=payload;
                 for(i=0; i<PayloadLength; i++){
                         if((trContext!=NULL)&&(trContext->GenerationNumber!=GenerationNumber)) return(-1021);
                         ILINKRegisterBase->ubufTransmitNext=*data;
                         data++;
                 }
         }
         ILINKRegisterBase->ubufTransmitLast=*(data-1);
         DEBUG_PRINTF("Transmitting payload...\n");
         WaitEventFlag(IntrEventFlag, iLinkEventDataSent|iLinkEventError, WEF_OR, &FlagBits);
         if(FlagBits&iLinkEventError){
                 DEBUG_PRINTF("iLinkman: TX Error.\n");
         }
         SignalSema(UBUFTxSema);
         return((FlagBits&iLinkEventError)?-1:PayloadLength);
 }
References ClearEventFlag(), DEBUG_PRINTF, GenerationNumber, TransactionContextData::GenerationNumber, iLinkEventDataReceived, iLinkEventDataSent, iLinkEventError, ILINKRegisterBase, IntrEventFlag, NULL, SignalSema(), ILINKMemMap::ubufTransmitClear, ILINKMemMap::ubufTransmitLast, ILINKMemMap::ubufTransmitNext, UBUFTxSema, WaitEventFlag(), WaitSema(), and WEF_OR.
Referenced by iLinkReadReq(), iLinkWriteReq(), and SendResponse().
iLinkSync()
static int iLinkSync (unsigned int PayloadLength) static
Definition at line 100 of file iLink_TxRx.c.
{
         u32 FlagBits;
         DEBUG_PRINTF("Payload transmitted. Now awaiting response...\n");
         SetAlarm(&Timeout, &TimeoutCallbackFunction, NULL);
         WaitEventFlag(IntrEventFlag, iLinkEventDataReceived|iLinkEventError, WEF_OR, &FlagBits);
         if(!(FlagBits&iLinkEventError)){
                 CancelAlarm(&TimeoutCallbackFunction, NULL);
         }
         else{
                 DEBUG_PRINTF("iLinkman: Split timeout.\n");
                 LocalCachedIntr0Register|=iLink_INTR0_STO;
         }
         DEBUG_PRINTF("Processing results...\n");
         if(LocalCachedIntr0Register&iLink_INTR0_InvAck) return(-1023);
         if(LocalCachedIntr0Register&iLink_INTR0_STO) return(-1024);
         if(LocalCachedIntr0Register&iLink_INTR0_AckMiss) return(-1025);
         if(LocalCachedIntr0Register&iLink_INTR0_RetEx) return(-1026);
         /* if(!(LocalCachedIntr0Register&iLink_INTR0_AckRcvd)) return(-1); *//* Don't test for an acknowledge, as this somehow doesn't work right. :/ */
         return PayloadLength;
 }
References CancelAlarm(), DEBUG_PRINTF, iLink_INTR0_AckMiss, iLink_INTR0_InvAck, iLink_INTR0_RetEx, iLink_INTR0_STO, iLinkEventDataReceived, iLinkEventError, IntrEventFlag, LocalCachedIntr0Register, NULL, SetAlarm(), Timeout, TimeoutCallbackFunction(), WaitEventFlag(), and WEF_OR.
Referenced by iLinkReadReq(), and iLinkWriteReq().
iLinkWriteReq()
int iLinkWriteReq (struct TransactionContextData * trContext, unsigned short int offset_high, unsigned int offset_low, void * buffer, unsigned int nBytes)
Definition at line 153 of file iLink_TxRx.c.
{
         unsigned int nBytesToTransfer;
         struct ieee1394_TrPacketHdr TxHeader;
         int result;
         unsigned char tlabel, tCode;
         DEBUG_PRINTF("iLinkTrWrite() 0x%08x %08x; nbytes: 0x%08x. Node: 0x%04x.\n", offset_high, offset_low, nBytes, trContext->NodeID);
         tlabel=1; /* Note: As the tlabel is the same, multiple simultaneous transactions will probably not be possible. */
         tCode=IEEE1394_TCODE_WRITEQ;
         TxHeader.header=(((unsigned int)trContext->speed)<<16) | (((unsigned int)tlabel) << 10) | (1<<8) | (((unsigned int)tCode) << 4 );
         TxHeader.offset_high=(((unsigned int)trContext->NodeID)<<16)|offset_high;
         TxHeader.offset_low=offset_low;
         TxHeader.misc=nBytes<<16;
         nBytesToTransfer=sizeof(struct ieee1394_TrPacketHdr)-4; /* Quadlet writes do not have the data length field. */
         if((result=iLinkSendData(trContext, (unsigned int *)&TxHeader, nBytesToTransfer>>2, buffer, nBytes>>2))>=0){
                 result=iLinkSync(nBytesToTransfer);
         }
         return result;
 }
References buffer, DEBUG_PRINTF, ieee1394_TrPacketHdr::header, IEEE1394_TCODE_WRITEQ, iLinkSendData(), iLinkSync(), ieee1394_TrPacketHdr::misc, TransactionContextData::NodeID, ieee1394_TrPacketHdr::offset_high, ieee1394_TrPacketHdr::offset_low, result, and TransactionContextData::speed.
Referenced by iLinkTrWrite().
SendResponse()
void SendResponse (unsigned short int NodeID, unsigned short RcvdBusID, unsigned char rCode, unsigned char tLabel, unsigned char tCode, unsigned char speed, unsigned int * buffer, unsigned int nQuads)
Definition at line 73 of file iLink_TxRx.c.
{
         struct ieee1394_TrResponsePacketHdr ResponseHeader;
         unsigned int ResponseHeaderLength;
         ResponseHeaderLength=(tCode==IEEE1394_TCODE_READB_RESPONSE)?4:3;
         DEBUG_PRINTF("Sending response to: 0x%04x, RcvdBusID: 0x%04x, rcode: %d, Header length: %u, speed: 0x%04x. Payload length: 0x%08x.\n", NodeID, RcvdBusID, rCode, ResponseHeaderLength, speed, nQuads);
         DEBUG_PRINTF("tCode: 0x%02x\n", tCode);
         ResponseHeader.header=(((unsigned int)RcvdBusID)<<22) | (((unsigned int)speed)<<16) | (((unsigned int)tLabel)<<10) | (1<<8) | (((unsigned int)tCode)<<4);
         ResponseHeader.header2=(((unsigned int)NodeID)<<16) | (((unsigned int)rCode)<<12);
         ResponseHeader.reserved=0;
         ResponseHeader.LastField=nQuads<<18;
         iLinkSendData(NULL, (unsigned int *)&ResponseHeader, ResponseHeaderLength, buffer, nQuads);
 }
References buffer, DEBUG_PRINTF, ieee1394_TrResponsePacketHdr::header, ieee1394_TrResponsePacketHdr::header2, IEEE1394_TCODE_READB_RESPONSE, iLinkSendData(), ieee1394_TrResponsePacketHdr::LastField, NULL, and ieee1394_TrResponsePacketHdr::reserved.
Referenced by ReadRequestHandler(), and WriteRequestHandler().
TimeoutCallbackFunction()
static unsigned int TimeoutCallbackFunction (void * argv) static
Definition at line 95 of file iLink_TxRx.c.
{
         iSetEventFlag(IntrEventFlag, iLinkEventError);
         return 0;
 }
References iLinkEventError, IntrEventFlag, and iSetEventFlag().
Referenced by iLinkSync().
Variable Documentation
GenerationNumber
int GenerationNumber extern
Definition at line 26 of file iLink_internal.c.
Referenced by iLinkHWInitialize(), and iLinkSendData().
iLinkDMACRegs
struct DMAChannelRegBlock* iLinkDMACRegs extern
Definition at line 27 of file iLink_DMA.c.
Referenced by iLinkInitPHT(), and iLinkPHTSendData().
ILINKRegisterBase
struct ILINKMemMap* ILINKRegisterBase extern
Definition at line 31 of file iLink.c.
Referenced by iLinkDisableSBus(), and iLinkSendData().
IntrEventFlag
int IntrEventFlag extern
Definition at line 45 of file iLink.c.
Referenced by _exit(), _start(), iLinkResetSBus(), iLinkSendData(), iLinkSync(), and TimeoutCallbackFunction().
LocalCachedIntr0Register
unsigned int LocalCachedIntr0Register extern
Definition at line 29 of file iLink_intr.c.
Referenced by iLinkIntrHandler(), and iLinkSync().
LocalNodeID
unsigned short int LocalNodeID extern
Definition at line 39 of file iLink.c.
Referenced by iLinkGetLocalNodeID(), and iLinkTrAlloc().
TargetBuffer
unsigned* TargetBuffer extern
Definition at line 28 of file iLink_intr.c.
Referenced by iLinkReadReq(), and ResponseHandler().
Timeout
iop_sys_clock_t Timeout static
Initial value:
={
        0x8E9400,
        0
}
Definition at line 90 of file iLink_TxRx.c.
Referenced by iLinkSync().
UBUFTxSema
int UBUFTxSema extern
Definition at line 45 of file iLink.c.
Referenced by _exit(), _start(), and iLinkSendData().