ps2sdk: iop/iLink/IEEE1394_bd/src/scsi.c File Reference
scsi.c File Reference
#include <errno.h>
#include <stdio.h>
#include <sysclib.h>
#include <thsemap.h>
#include "scsi.h"
#include <bdm.h>
#include "module_debug.h"
Data Structures
struct inquiry_data
struct sense_data
struct read_capacity_data
Macros
#define getBI32(__buf) ((((u8*)(__buf))[3] << 0) | (((u8*)(__buf))[2] << 8) | (((u8*)(__buf))[1] << 16) | (((u8*)(__buf))[0] << 24))
#define SCSI_MAX_RETRIES 16
#define NUM_DEVICES 2
Functions
static int scsi_cmd (struct block_device *bd, unsigned char cmd, void *buffer, int buf_size, int cmd_size)
static int scsi_cmd_test_unit_ready (struct block_device *bd)
static int scsi_cmd_request_sense (struct block_device *bd, void *buffer, int size)
static int scsi_cmd_inquiry (struct block_device *bd, void *buffer, int size)
static int scsi_cmd_start_stop_unit (struct block_device *bd)
static int scsi_cmd_read_capacity (struct block_device *bd, void *buffer, int size)
static int scsi_cmd_rw_sector (struct block_device *bd, unsigned int lba, const void *buffer, unsigned short int sectorCount, unsigned int write)
static int scsi_warmup (struct block_device *bd)
static int scsi_read (struct block_device *bd, u32 sector, void *buffer, u16 count)
static int scsi_write (struct block_device *bd, u32 sector, const void *buffer, u16 count)
static void scsi_flush (struct block_device *bd)
void scsi_connect (struct scsi_interface *scsi)
void scsi_disconnect (struct scsi_interface *scsi)
int scsi_init (void)
Variables
static struct block_device g_scsi_bd [NUM_DEVICES]
Macro Definition Documentation
getBI32
#define getBI32 (__buf) ((((u8*)(__buf))[3] << 0) | (((u8*)(__buf))[2] << 8) | (((u8*)(__buf))[1] << 16) | (((u8*)(__buf))[0] << 24))
Definition at line 12 of file scsi.c.
NUM_DEVICES
#define NUM_DEVICES 2
Definition at line 44 of file scsi.c.
SCSI_MAX_RETRIES
#define SCSI_MAX_RETRIES 16
Definition at line 13 of file scsi.c.
Function Documentation
scsi_cmd()
static int scsi_cmd (struct block_device * bd, unsigned char cmd, void * buffer, int buf_size, int cmd_size) static
Definition at line 50 of file scsi.c.
 {
     unsigned char comData[12]   = { 0x00, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
     struct scsi_interface* scsi = (struct scsi_interface*)bd->priv;
     //M_DEBUG("%s\n", __func__);
     comData[0] = cmd;
     comData[4] = cmd_size;
     return scsi->queue_cmd(scsi, comData, 12, buffer, buf_size, 0);
 }
References buffer, block_device::priv, and scsi_interface::queue_cmd.
Referenced by scsi_cmd_inquiry(), scsi_cmd_read_capacity(), scsi_cmd_request_sense(), scsi_cmd_start_stop_unit(), and scsi_cmd_test_unit_ready().
scsi_cmd_inquiry()
static int scsi_cmd_inquiry (struct block_device * bd, void * buffer, int size) inline static
Definition at line 77 of file scsi.c.
 {
     M_DEBUG("%s\n", __func__);
     return scsi_cmd(bd, 0x12, buffer, size, size);
 }
References buffer, M_DEBUG, and scsi_cmd().
Referenced by scsi_warmup().
scsi_cmd_read_capacity()
static int scsi_cmd_read_capacity (struct block_device * bd, void * buffer, int size) inline static
Definition at line 91 of file scsi.c.
 {
     M_DEBUG("%s\n", __func__);
     return scsi_cmd(bd, 0x25, buffer, size, 0);
 }
References buffer, M_DEBUG, and scsi_cmd().
Referenced by scsi_warmup().
scsi_cmd_request_sense()
static int scsi_cmd_request_sense (struct block_device * bd, void * buffer, int size) inline static
Definition at line 70 of file scsi.c.
 {
     M_DEBUG("%s\n", __func__);
     return scsi_cmd(bd, 0x03, buffer, size, size);
 }
References buffer, M_DEBUG, and scsi_cmd().
Referenced by scsi_warmup().
scsi_cmd_rw_sector()
static int scsi_cmd_rw_sector (struct block_device * bd, unsigned int lba, const void * buffer, unsigned short int sectorCount, unsigned int write) static
Definition at line 98 of file scsi.c.
 {
     unsigned char comData[12]   = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
     struct scsi_interface* scsi = (struct scsi_interface*)bd->priv;
     M_DEBUG("scsi_cmd_rw_sector - 0x%08x %p 0x%04x\n", lba, buffer, sectorCount);
     comData[0] = write ? 0x2a : 0x28;
     comData[2] = (lba & 0xFF000000) >> 24;    //lba 1 (MSB)
     comData[3] = (lba & 0xFF0000) >> 16;      //lba 2
     comData[4] = (lba & 0xFF00) >> 8;         //lba 3
     comData[5] = (lba & 0xFF);                //lba 4 (LSB)
     comData[7] = (sectorCount & 0xFF00) >> 8; //Transfer length MSB
     comData[8] = (sectorCount & 0xFF);        //Transfer length LSB
     return scsi->queue_cmd(scsi, comData, 12, (void*)buffer, bd->sectorSize * sectorCount, write);
 }
References buffer, M_DEBUG, block_device::priv, scsi_interface::queue_cmd, block_device::sectorSize, and write().
Referenced by scsi_read(), and scsi_write().
scsi_cmd_start_stop_unit()
static int scsi_cmd_start_stop_unit (struct block_device * bd) inline static
Definition at line 84 of file scsi.c.
 {
     M_DEBUG("%s\n", __func__);
     return scsi_cmd(bd, 0x1b, NULL, 0, 1);
 }
References M_DEBUG, NULL, and scsi_cmd().
Referenced by scsi_warmup().
scsi_cmd_test_unit_ready()
static int scsi_cmd_test_unit_ready (struct block_device * bd) inline static
Definition at line 63 of file scsi.c.
 {
     M_DEBUG("%s\n", __func__);
     return scsi_cmd(bd, 0x00, NULL, 0, 0);
 }
References M_DEBUG, NULL, and scsi_cmd().
Referenced by scsi_warmup().
scsi_connect()
void scsi_connect (struct scsi_interface * scsi)
Definition at line 239 of file scsi.c.
 {
     int i;
     M_DEBUG("%s\n", __func__);
     for (i = 0; i < NUM_DEVICES; ++i) {
         if (g_scsi_bd[i].priv == NULL) {
             struct block_device* bd = &g_scsi_bd[i];
             bd->priv = scsi;
             bd->name = scsi->name;
             scsi_warmup(bd);
             bdm_connect_bd(bd);
             break;
         }
     }
 }
scsi_disconnect()
void scsi_disconnect (struct scsi_interface * scsi)
Definition at line 258 of file scsi.c.
 {
     int i;
     M_DEBUG("%s\n", __func__);
     for (i = 0; i < NUM_DEVICES; ++i) {
         if (g_scsi_bd[i].priv == scsi) {
             struct block_device* bd = &g_scsi_bd[i];
             bdm_disconnect_bd(bd);
             bd->priv = NULL;
             break;
         }
     }
 }
scsi_flush()
static void scsi_flush (struct block_device * bd) static
Definition at line 231 of file scsi.c.
 {
     // Dummy function
 }
Referenced by scsi_init().
scsi_init()
int scsi_init (void)
Definition at line 274 of file scsi.c.
 {
     int i;
     M_DEBUG("%s\n", __func__);
     for (i = 0; i < NUM_DEVICES; ++i) {
         g_scsi_bd[i].devNr = i;
         g_scsi_bd[i].parNr = 0;
         g_scsi_bd[i].priv  = NULL;
         g_scsi_bd[i].read  = scsi_read;
         g_scsi_bd[i].write = scsi_write;
         g_scsi_bd[i].flush = scsi_flush;
     }
     return 0;
 }
scsi_read()
static int scsi_read (struct block_device * bd, u32 sector, void * buffer, u16 count) static
Definition at line 177 of file scsi.c.
 {
     struct scsi_interface* scsi = (struct scsi_interface*)bd->priv;
     u16 sc_remaining = count;
     int retries;
     M_DEBUG("%s: sector=%d, count=%d\n", __func__, sector, count);
     while (sc_remaining > 0) {
         u16 sc = sc_remaining > scsi->max_sectors ? scsi->max_sectors : sc_remaining;
         for (retries = SCSI_MAX_RETRIES; retries > 0; retries--) {
             if (scsi_cmd_rw_sector(bd, sector, buffer, sc, 0) == 0)
                 break;
         }
         if (retries == 0)
             return -EIO;
         sc_remaining -= sc;
         sector += sc;
         buffer = (u8*)buffer + (sc * bd->sectorSize);
     }
     return count;
 }
References buffer, EIO, M_DEBUG, scsi_interface::max_sectors, block_device::priv, scsi_cmd_rw_sector(), SCSI_MAX_RETRIES, and block_device::sectorSize.
Referenced by scsi_init().
scsi_warmup()
static int scsi_warmup (struct block_device * bd) static
Definition at line 118 of file scsi.c.
 {
     struct scsi_interface* scsi = (struct scsi_interface*)bd->priv;
     inquiry_data id;
     sense_data sd;
     read_capacity_data rcd;
     int stat;
     M_DEBUG("%s\n", __func__);
     stat = scsi->get_max_lun(scsi);
     M_DEBUG("scsi->get_max_lun %d\n", stat);
     memset(&id, 0, sizeof(inquiry_data));
     if ((stat = scsi_cmd_inquiry(bd, &id, sizeof(inquiry_data))) < 0) {
         M_PRINTF("ERROR: scsi_cmd_inquiry %d\n", stat);
         return -1;
     }
     M_PRINTF("Vendor: %.8s\n", id.vendor);
     M_PRINTF("Product: %.16s\n", id.product);
     M_PRINTF("Revision: %.4s\n", id.revision);
     while ((stat = scsi_cmd_test_unit_ready(bd)) != 0) {
         M_PRINTF("ERROR: scsi_cmd_test_unit_ready %d\n", stat);
         stat = scsi_cmd_request_sense(bd, &sd, sizeof(sense_data));
         if (stat != 0)
             M_PRINTF("ERROR: scsi_cmd_request_sense %d\n", stat);
         if ((sd.error_code == 0x70) && (sd.sense_key != 0x00)) {
             M_PRINTF("Sense Data key: %02X code: %02X qual: %02X\n", sd.sense_key, sd.add_sense_code, sd.add_sense_qual);
             if ((sd.sense_key == 0x02) && (sd.add_sense_code == 0x04) && (sd.add_sense_qual == 0x02)) {
                 M_PRINTF("ERROR: Additional initalization is required for this device!\n");
                 if ((stat = scsi_cmd_start_stop_unit(bd)) != 0) {
                     M_PRINTF("ERROR: scsi_cmd_start_stop_unit %d\n", stat);
                     return -1;
                 }
             }
         }
     }
     if ((stat = scsi_cmd_read_capacity(bd, &rcd, sizeof(read_capacity_data))) != 0) {
         M_PRINTF("ERROR: scsi_cmd_read_capacity %d\n", stat);
         return -1;
     }
     bd->sectorSize   = getBI32(&rcd.block_length);
     bd->sectorOffset = 0;
     bd->sectorCount  = getBI32(&rcd.last_lba);
     M_PRINTF("%u %u-byte logical blocks: (%uMB / %uMiB)\n", bd->sectorCount, bd->sectorSize, bd->sectorCount / ((1000 * 1000) / bd->sectorSize), bd->sectorCount / ((1024 * 1024) / bd->sectorSize));
     return 0;
 }
References scsi_interface::get_max_lun, getBI32, M_DEBUG, M_PRINTF, memset(), block_device::priv, scsi_cmd_inquiry(), scsi_cmd_read_capacity(), scsi_cmd_request_sense(), scsi_cmd_start_stop_unit(), scsi_cmd_test_unit_ready(), sd, block_device::sectorCount, block_device::sectorOffset, and block_device::sectorSize.
Referenced by scsi_connect().
scsi_write()
static int scsi_write (struct block_device * bd, u32 sector, const void * buffer, u16 count) static
Definition at line 204 of file scsi.c.
 {
     struct scsi_interface* scsi = (struct scsi_interface*)bd->priv;
     u16 sc_remaining = count;
     int retries;
     M_DEBUG("%s: sector=%d, count=%d\n", __func__, sector, count);
     while (sc_remaining > 0) {
         u16 sc = sc_remaining > scsi->max_sectors ? scsi->max_sectors : sc_remaining;
         for (retries = SCSI_MAX_RETRIES; retries > 0; retries--) {
             if (scsi_cmd_rw_sector(bd, sector, buffer, sc, 1) == 0)
                 break;
         }
         if (retries == 0)
             return -EIO;
         sc_remaining -= sc;
         sector += sc;
         buffer = (u8*)buffer + (sc * bd->sectorSize);
     }
     return count;
 }
References buffer, EIO, M_DEBUG, scsi_interface::max_sectors, block_device::priv, scsi_cmd_rw_sector(), SCSI_MAX_RETRIES, and block_device::sectorSize.
Referenced by scsi_init().
Variable Documentation
g_scsi_bd
struct block_device g_scsi_bd[NUM_DEVICES] static
Definition at line 1 of file scsi.c.
Referenced by scsi_connect(), scsi_disconnect(), and scsi_init().