ps2sdk: iop/iLink/IEEE1394_disk/src/include/scsi.h File Reference
scsi.h File Reference
Data Structures
struct inquiry_data
struct sense_data
struct read_capacity_data
Macros
#define XFER_BLOCK_SIZE
#define READ_TRANSACTION 0
#define WRITE_TRANSACTION 1
#define CDB_PAGE_SIZE(v) ((v) << 16) /* Not in use. */
#define CDB_PAGE_TABLE_PRESENT(v) ((v) << 19) /* Not in use. */
#define CDB_MAX_PAYLOAD(v) ((v) << 20)
#define CDB_SPEED(v) ((v) << 24)
#define CDB_DIRECTION(v) ((v) << 27)
#define CDB_DATA_SIZE(v) ((v))
Functions
int scsiReadSector (struct SBP2Device *dev, unsigned long int lba, void *buffer, int sectorCount)
int scsiWriteSector (struct SBP2Device *dev, unsigned long int lba, void *buffer, int sectorCount)
void releaseSBP2Device (struct SBP2Device *dev)
int ConfigureSBP2Device (struct SBP2Device *dev)
Macro Definition Documentation
CDB_DATA_SIZE
#define CDB_DATA_SIZE (v) ((v))
Definition at line 12 of file scsi.h.
CDB_DIRECTION
#define CDB_DIRECTION (v) ((v) << 27)
Definition at line 11 of file scsi.h.
CDB_MAX_PAYLOAD
#define CDB_MAX_PAYLOAD (v) ((v) << 20)
Definition at line 9 of file scsi.h.
CDB_PAGE_SIZE
#define CDB_PAGE_SIZE (v) ((v) << 16) /* Not in use. */
Definition at line 7 of file scsi.h.
CDB_PAGE_TABLE_PRESENT
#define CDB_PAGE_TABLE_PRESENT (v) ((v) << 19) /* Not in use. */
Definition at line 8 of file scsi.h.
CDB_SPEED
#define CDB_SPEED (v) ((v) << 24)
Definition at line 10 of file scsi.h.
READ_TRANSACTION
#define READ_TRANSACTION 0
Definition at line 3 of file scsi.h.
WRITE_TRANSACTION
#define WRITE_TRANSACTION 1
Definition at line 4 of file scsi.h.
XFER_BLOCK_SIZE
#define XFER_BLOCK_SIZE
Value:
                                                65024   /* 65536-512. It seems like my Oxford 934 is capable of maximum transfers of less than 65536 bytes.
                                                NOTE: I reduced the maximum block size here by 512, since transfers are done in (smallest) groups of 512 bytes!
                                */
Definition at line 1 of file scsi.h.
Function Documentation
ConfigureSBP2Device()
int ConfigureSBP2Device (struct SBP2Device * dev)
Definition at line 412 of file scsi.c.
 {
         int ret;
         if((ret = InitializeSCSIDevice(dev))<0)
         {
                 XPRINTF("IEEE1394_disk: Error - failed to warmup device 0x%08x\n", dev->nodeID);
                 return ret;
         }
         if((dev->cache = scache_init(dev, dev->sectorSize))==NULL){
                 XPRINTF("IEEE1394_disk: Error - scache_init failed \n" );
                 return ret;
         }
         return(part_connect(dev));
 }
References SBP2Device::cache, InitializeSCSIDevice(), SBP2Device::nodeID, NULL, part_connect(), scache_init(), SBP2Device::sectorSize, and XPRINTF.
Referenced by initConfigureSBP2Device().
releaseSBP2Device()
void releaseSBP2Device (struct SBP2Device * dev)
Definition at line 407 of file scsi.c.
{
         part_disconnect(dev);
         scache_kill(dev->cache);
 }
References SBP2Device::cache, part_disconnect(), and scache_kill().
Referenced by iLinkIntrCBHandlingThread().
scsiReadSector()
int scsiReadSector (struct SBP2Device * dev, unsigned long int lba, void * buffer, int sectorCount)
Definition at line 205 of file scsi.c.
 {
         unsigned int nOrbs, OrbsRemaining, i, sectorsToRead, sectorsRemaining, SectorsPerBlock, BlockNum;
         unsigned long int startingLBA;
         void *bufferPtr, *PreviousReqBufferPtr;
         int result;
         XPRINTF("IEEE1394_disk: scsiReadSector. buffer: %p, lba: 0x%08lx, numsectors: %d.\n", buffer, lba, sectorCount);
         SectorsPerBlock=XFER_BLOCK_SIZE/dev->sectorSize;
         OrbsRemaining=sectorCount/SectorsPerBlock;
         if((sectorCount%SectorsPerBlock)!=0) OrbsRemaining++;
         XPRINTF("NumOrbs=%d cdb: %p.\n", OrbsRemaining, cdb);
         startingLBA=lba;
         sectorsRemaining=sectorCount;
         bufferPtr=buffer;
         result=0;
         for(PreviousReqBufferPtr=NULL, BlockNum=0, sectorsToRead=0; (OrbsRemaining>0) && (result==0); OrbsRemaining-=nOrbs, BlockNum++){
                 nOrbs=(OrbsRemaining>MAX_ORBS)?MAX_ORBS:OrbsRemaining;
                 if(BlockNum>0){ /* While waiting for the read request that was just sent to be processed, byte-swap the previously read in data. */
                         for(i=0; i<sectorsToRead<<7; i++) ((unsigned int *)PreviousReqBufferPtr)[i]=BSWAP32(((unsigned int *)PreviousReqBufferPtr)[i]);
                         result=ieee1394_Sync(); /* Only sync if a read request is being processed. Otherwise, it'll wait eternally.. */
                 }
                 /* Save the current pointer to the buffer, so that the code above can byte-swap the payload of the request below that will be read in,
                         when this loop loops around.
                 */
                 PreviousReqBufferPtr=bufferPtr;
                 for(i=0; i<nOrbs; i++){
                         sectorsToRead=(sectorsRemaining>SectorsPerBlock)?SectorsPerBlock:sectorsRemaining;
                         cdb[i].misc=(ORB_NOTIFY | ORB_REQUEST_FORMAT(0) | CDB_MAX_PAYLOAD(dev->max_payload) | CDB_DIRECTION(WRITE_TRANSACTION) | CDB_SPEED(dev->speed) | CDB_DATA_SIZE((dev->sectorSize * sectorsToRead)));
                         cdb[i].DataDescriptor.low=(u32)bufferPtr;
                         cdb[i].DataDescriptor.high=0;
                         cdb[i].DataDescriptor.NodeID=dev->InitiatorNodeID;
                         if(i>0){
                                 cdb[i-1].NextOrb.high=0;
                                 cdb[i-1].NextOrb.low=(u32)&cdb[i];
                                 cdb[i-1].NextOrb.reserved=0;
                         }
                         //scsi command packet
                         cdb[i].CDBs[3] = 0x28;                          //read operation code
                         cdb[i].CDBs[2] = 0;                             //Reserved
                         cdb[i].CDBs[1] = (startingLBA & 0xFF000000) >> 24;      //lba 1 (MSB)
                         cdb[i].CDBs[0] = (startingLBA & 0xFF0000) >> 16;        //lba 2
                         cdb[i].CDBs[7] = (startingLBA & 0xFF00) >> 8;           //lba 3
                         cdb[i].CDBs[6] = (startingLBA & 0xFF);                  //lba 4 (LSB)
                         cdb[i].CDBs[5] = 0;                             //Reserved
                         cdb[i].CDBs[4] = (sectorsToRead & 0xFF00) >> 8; //Transfer length MSB
                         cdb[i].CDBs[11] = (sectorsToRead & 0xFF);       //Transfer length LSB
                         cdb[i].CDBs[10] = 0;                            //reserved
                         cdb[i].CDBs[9] = 0;                             //reserved
                         cdb[i].CDBs[8] = 0;                             //reserved
                         startingLBA+=sectorsToRead;
                         sectorsRemaining-=sectorsToRead;
                         bufferPtr+=dev->sectorSize * sectorsToRead;
                 }
                 /* NULL terminate the last ORB. */
                 cdb[i-1].NextOrb.high=cdb[i-1].NextOrb.low=0;
                 cdb[i-1].NextOrb.reserved=NULL_POINTER;
                 ieee1394_SendCommandBlockORB(dev, cdb);
         }
         /* Sync and byte-swap the last block. */
         result=ieee1394_Sync();
         for(i=0; i<sectorsToRead<<7; i++) ((unsigned int *)PreviousReqBufferPtr)[i]=BSWAP32(((unsigned int *)PreviousReqBufferPtr)[i]);
         XPRINTF("IEEE1394_disk: scsiReadSector done.\n");
         return result;
 }
References BSWAP32, buffer, cdb, CDB_DATA_SIZE, CDB_DIRECTION, CDB_MAX_PAYLOAD, CDB_SPEED, CommandDescriptorBlock::CDBs, CommandDescriptorBlock::DataDescriptor, sbp2_pointer::high, sbp2_ORB_pointer::high, ieee1394_SendCommandBlockORB(), ieee1394_Sync(), SBP2Device::InitiatorNodeID, sbp2_pointer::low, sbp2_ORB_pointer::low, MAX_ORBS, SBP2Device::max_payload, CommandDescriptorBlock::misc, CommandDescriptorBlock::NextOrb, sbp2_pointer::NodeID, NULL, NULL_POINTER, ORB_NOTIFY, ORB_REQUEST_FORMAT, sbp2_ORB_pointer::reserved, result, SBP2Device::sectorSize, SBP2Device::speed, WRITE_TRANSACTION, XFER_BLOCK_SIZE, and XPRINTF.
Referenced by initConfigureSBP2Device().
scsiWriteSector()
int scsiWriteSector (struct SBP2Device * dev, unsigned long int lba, void * buffer, int sectorCount)
Definition at line 287 of file scsi.c.
 {
         unsigned int nOrbs, OrbsRemaining, i, sectorsToRead, sectorsRemaining, SectorsPerBlock;
         unsigned long int startingLBA;
         void *bufferPtr;
         int result, max_payload;
         XPRINTF("IEEE1394_disk: scsiWriteSector.\n");
         SectorsPerBlock=XFER_BLOCK_SIZE/dev->sectorSize;
         OrbsRemaining=sectorCount/SectorsPerBlock;
         if((sectorCount%SectorsPerBlock)!=0) OrbsRemaining++;
         startingLBA=lba;
         sectorsRemaining=sectorCount;
         bufferPtr=buffer;
         max_payload=(dev->max_payload>7)?7:dev->max_payload;    /* Do not allow the maximum payload to exceed 512 bytes (Actually, is this necessary?). */
         result=0;
         for(; (OrbsRemaining>0) && (result==0); OrbsRemaining-=nOrbs){
                 nOrbs=(OrbsRemaining>MAX_ORBS)?MAX_ORBS:OrbsRemaining;
                 for(i=0; i<nOrbs; i++){
                         sectorsToRead=(sectorsRemaining>SectorsPerBlock)?SectorsPerBlock:sectorsRemaining;
                         cdb[i].misc=(ORB_NOTIFY | ORB_REQUEST_FORMAT(0) | CDB_MAX_PAYLOAD(max_payload) | CDB_DIRECTION(READ_TRANSACTION) | CDB_SPEED(dev->speed) | CDB_DATA_SIZE((dev->sectorSize * sectorsToRead)));
                         cdb[i].DataDescriptor.low=(u32)bufferPtr;
                         cdb[i].DataDescriptor.high=0;
                         cdb[i].DataDescriptor.NodeID=dev->InitiatorNodeID;
                         if(i>0){
                                 cdb[i-1].NextOrb.high=0;
                                 cdb[i-1].NextOrb.low=(u32)&cdb[i];
                                 cdb[i-1].NextOrb.reserved=0;
                         }
                         //scsi command packet
                         cdb[i].CDBs[3] = 0x2A;                          //write operation code
                         cdb[i].CDBs[2] = 0;                             //Reserved
                         cdb[i].CDBs[1] = (startingLBA & 0xFF000000) >> 24;      //lba 1 (MSB)
                         cdb[i].CDBs[0] = (startingLBA & 0xFF0000) >> 16;        //lba 2
                         cdb[i].CDBs[7] = (startingLBA & 0xFF00) >> 8;           //lba 3
                         cdb[i].CDBs[6] = (startingLBA & 0xFF);                  //lba 4 (LSB)
                         cdb[i].CDBs[5] = 0;                             //Reserved
                         cdb[i].CDBs[4] = (sectorsToRead & 0xFF00) >> 8; //Transfer length MSB
                         cdb[i].CDBs[11] = (sectorsToRead & 0xFF);       //Transfer length LSB
                         cdb[i].CDBs[10] = 0;                            //reserved
                         cdb[i].CDBs[9] = 0;                             //reserved
                         cdb[i].CDBs[8] = 0;                             //reserved
                         startingLBA+=sectorsToRead;
                         sectorsRemaining-=sectorsToRead;
                         bufferPtr+=dev->sectorSize * sectorsToRead;
                 }
                 /* NULL terminate the last ORB. */
                 cdb[i-1].NextOrb.high=cdb[i-1].NextOrb.low=0;
                 cdb[i-1].NextOrb.reserved=NULL_POINTER;
                 ieee1394_SendCommandBlockORB(dev, cdb);
                 result=ieee1394_Sync();
         }
         return result;
 }
References buffer, cdb, CDB_DATA_SIZE, CDB_DIRECTION, CDB_MAX_PAYLOAD, CDB_SPEED, CommandDescriptorBlock::CDBs, CommandDescriptorBlock::DataDescriptor, sbp2_pointer::high, sbp2_ORB_pointer::high, ieee1394_SendCommandBlockORB(), ieee1394_Sync(), SBP2Device::InitiatorNodeID, sbp2_pointer::low, sbp2_ORB_pointer::low, MAX_ORBS, SBP2Device::max_payload, CommandDescriptorBlock::misc, CommandDescriptorBlock::NextOrb, sbp2_pointer::NodeID, NULL_POINTER, ORB_NOTIFY, ORB_REQUEST_FORMAT, READ_TRANSACTION, sbp2_ORB_pointer::reserved, result, SBP2Device::sectorSize, SBP2Device::speed, XFER_BLOCK_SIZE, and XPRINTF.