ps2sdk: iop/hdd/libpfs/src/inode.c File Reference
inode.c File Reference
#include <errno.h>
#include <stdio.h>
#include <sysclib.h>
#include "pfs-opt.h"
#include "libpfs.h"
Functions
void pfsInodePrint (pfs_inode_t *inode)
int pfsInodeCheckSum (pfs_inode_t *inode)
pfs_cache_t * pfsInodeGetData (pfs_mount_t *pfsMount, u16 sub, u32 inode, int *result)
void pfsInodeSetTime (pfs_cache_t *clink)
void pfsInodeSetTimeParent (pfs_cache_t *parent, pfs_cache_t *self)
int pfsInodeSync (pfs_blockpos_t *blockpos, u64 size, u32 used_segments)
pfs_cache_t * pfsGetDentriesChunk (pfs_blockpos_t *position, int *result)
pfs_cache_t * pfsGetDentriesAtPos (pfs_cache_t *clink, u64 position, int *offset, int *result)
Variables
u32 pfsMetaSize
Function Documentation
pfsGetDentriesAtPos()
pfs_cache_t* pfsGetDentriesAtPos (pfs_cache_t * clink, u64 position, int * offset, int * result)
Definition at line 122 of file inode.c.
 {
         pfs_blockpos_t blockpos;
         pfs_cache_t *r;
         *result=pfsBlockInitPos(clink, &blockpos, position);
         if (*result)    return 0;
         *offset=blockpos.byte_offset % pfsMetaSize;
         r=pfsGetDentriesChunk(&blockpos, result);
         pfsCacheFree(blockpos.inode);
         return r;
 }
References pfs_blockpos_t::byte_offset, pfs_blockpos_t::inode, pfsBlockInitPos(), pfsCacheFree(), pfsGetDentriesChunk(), pfsMetaSize, and result.
Referenced by pfsDirAddEntry(), and pfsSetDentryParent().
pfsGetDentriesChunk()
pfs_cache_t* pfsGetDentriesChunk (pfs_blockpos_t * position, int * result)
Definition at line 110 of file inode.c.
 {
         pfs_blockinfo_t *bi;
         pfs_mount_t *pfsMount=position->inode->pfsMount;
         bi = &position->inode->u.inode->data[pfsFixIndex(position->block_segment)];
         return pfsCacheGetData(pfsMount, bi->subpart,
                  ((bi->number + position->block_offset) << pfsMount->inode_scale) +
                  position->byte_offset / pfsMetaSize, PFS_CACHE_FLAG_NOTHING, result);
 }
References pfs_blockpos_t::block_offset, pfs_blockpos_t::block_segment, pfs_blockpos_t::byte_offset, pfs_inode_t::data, pfs_cache_t::inode, pfs_blockpos_t::inode, pfs_mount_t::inode_scale, pfs_blockinfo_t::number, PFS_CACHE_FLAG_NOTHING, pfsCacheGetData(), pfsFixIndex(), pfsMetaSize, pfs_cache_t::pfsMount, result, pfs_blockinfo_t::subpart, and pfs_cache_t::u.
Referenced by pfsGetDentriesAtPos(), pfsGetDentry(), and pfsGetNextDentry().
pfsInodeCheckSum()
int pfsInodeCheckSum (pfs_inode_t * inode)
Definition at line 36 of file inode.c.
 {
         u32 *ptr=(u32 *)inode;
         u32 sum=0;
         int i;
         for(i=1; i < 256; i++)
                 sum+=ptr[i];
         return sum;
 }
Referenced by pfsCacheTransfer(), pfsFormat(), and pfsJournalWrite().
pfsInodeGetData()
pfs_cache_t* pfsInodeGetData (pfs_mount_t * pfsMount, u16 sub, u32 inode, int * result)
Definition at line 47 of file inode.c.
 {
         return pfsCacheGetData(pfsMount, sub, inode << pfsMount->inode_scale,
                                 PFS_CACHE_FLAG_SEGD, result);
 }
References pfs_mount_t::inode_scale, PFS_CACHE_FLAG_SEGD, pfsCacheGetData(), and result.
Referenced by pfsFioDread(), pfsInodeGetFileInDir(), and pfsInodeGetParent().
pfsInodePrint()
void pfsInodePrint (pfs_inode_t * inode)
Definition at line 29 of file inode.c.
 {
         PFS_PRINTF(PFS_DRV_NAME": pfsInodePrint: Checksum = 0x%lX, Magic = 0x%lX\n", inode->checksum, inode->magic);
         PFS_PRINTF(PFS_DRV_NAME":     Mode = 0x%X, attr = 0x%X\n", inode->mode, inode->attr);
         PFS_PRINTF(PFS_DRV_NAME":     size = 0x%08lX%08lX\n", (u32)(inode->size >> 32), (u32)(inode->size));
 }
References pfs_inode_t::attr, pfs_inode_t::checksum, pfs_inode_t::magic, pfs_inode_t::mode, PFS_DRV_NAME, PFS_PRINTF, and pfs_inode_t::size.
pfsInodeSetTime()
void pfsInodeSetTime (pfs_cache_t * clink)
Definition at line 53 of file inode.c.
 {       // set the inode time's in cache
         pfsGetTime(&clink->u.inode->mtime);
         memcpy(&clink->u.inode->ctime, &clink->u.inode->mtime, sizeof(pfs_datetime_t));
         memcpy(&clink->u.inode->atime, &clink->u.inode->mtime, sizeof(pfs_datetime_t));
         clink->flags|=PFS_CACHE_FLAG_DIRTY;
 }
References pfs_inode_t::atime, pfs_inode_t::ctime, pfs_cache_t::flags, pfs_cache_t::inode, memcpy(), pfs_inode_t::mtime, PFS_CACHE_FLAG_DIRTY, pfsGetTime(), and pfs_cache_t::u.
Referenced by pfsFioCloseFileSlot(), and pfsInodeSetTimeParent().
pfsInodeSetTimeParent()
void pfsInodeSetTimeParent (pfs_cache_t * parent, pfs_cache_t * self)
Definition at line 61 of file inode.c.
 {       // set the inode time's in cache
         pfsInodeSetTime(parent);
         self->flags|=PFS_CACHE_FLAG_DIRTY;
 }
References PFS_CACHE_FLAG_DIRTY, and pfsInodeSetTime().
Referenced by openFile(), pfsFioRename(), and pfsInodeRemove().
pfsInodeSync()
int pfsInodeSync (pfs_blockpos_t * blockpos, u64 size, u32 used_segments)
Definition at line 67 of file inode.c.
 {
         int result=0;
         u32 i;
         u16 count;
         for(i=pfsBlockSyncPos(blockpos, size); i; )
         {
                 count=blockpos->inode->u.inode->data[pfsFixIndex(blockpos->block_segment)].count;
                 i+=blockpos->block_offset;
                 if (i < count){
                         blockpos->block_offset=i;
                         break;
                 }
                 i-=count;
                 if (blockpos->block_segment + 1 == used_segments)
                 {
                         blockpos->block_offset=count;
                         if (i || blockpos->byte_offset){
                                 PFS_PRINTF(PFS_DRV_NAME": panic: fp exceeds file.\n");
                                 return -EINVAL;
                         }
                 }else{
                         blockpos->block_offset=0;
                         blockpos->block_segment++;
                 }
                 if (pfsFixIndex(blockpos->block_segment))
                         continue;
                 if ((blockpos->inode = pfsBlockGetNextSegment(blockpos->inode, &result)) == 0)
                         break;
                 i++;
         }
         return result;
 }
References pfs_blockpos_t::block_offset, pfs_blockpos_t::block_segment, pfs_blockpos_t::byte_offset, pfs_blockinfo_t::count, pfs_inode_t::data, EINVAL, pfs_cache_t::inode, pfs_blockpos_t::inode, PFS_DRV_NAME, PFS_PRINTF, pfsBlockGetNextSegment(), pfsBlockSyncPos(), pfsFixIndex(), result, and pfs_cache_t::u.
Referenced by pfsBlockInitPos(), pfsGetDentry(), and pfsGetNextDentry().
Variable Documentation
pfsMetaSize
u32 pfsMetaSize extern
Definition at line 26 of file super.c.
Referenced by pfsGetDentriesAtPos(), and pfsGetDentriesChunk().