ps2sdk: iop/usb/usbd/src/interface.c File Reference
interface.c File Reference
#include <defs.h>
#include <thbase.h>
#include "usbdpriv.h"
#include "driver.h"
#include "mem.h"
#include "hcd.h"
#include "usbio.h"
Functions
int sceUsbdRegisterLdd (sceUsbdLddOps *driver)
int sceUsbdRegisterAutoloader (sceUsbdLddOps *drv)
int sceUsbdUnregisterLdd (sceUsbdLddOps *driver)
int sceUsbdUnregisterAutoloader (void)
void * sceUsbdScanStaticDescriptor (int devId, void *data, u8 type)
int sceUsbdGetDeviceLocation (int devId, u8 *path)
int sceUsbdSetPrivateData (int devId, void *data)
void * sceUsbdGetPrivateData (int devId)
int sceUsbdOpenPipe (int devId, UsbEndpointDescriptor *desc)
int sceUsbdClosePipe (int id)
int sceUsbdTransferPipe (int id, void *data, u32 len, void *option, sceUsbdDoneCallback callback, void *cbArg)
int sceUsbdOpenPipeAligned (int devId, UsbEndpointDescriptor *desc)
int sceUsbdChangeThreadPriority (int prio1, int prio2)
Variables
UsbdConfig usbConfig
int hcdTid
int callbackTid
Detailed Description
USB Driver function prototypes and constants.
Definition in file interface.c.
Function Documentation
sceUsbdChangeThreadPriority()
int sceUsbdChangeThreadPriority (int prio1, int prio2)
Definition at line 322 of file interface.c.
{
         int res;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return USB_RC_BADCONTEXT;
         }
         res = 0;
         if(usbConfig.hcdThreadPrio != prio1) {
                 usbConfig.hcdThreadPrio = prio1;
                 res = ChangeThreadPriority(hcdTid, prio1);
         }
         if(usbConfig.cbThreadPrio != prio2) {
                 usbConfig.cbThreadPrio = prio2;
                 res = ChangeThreadPriority(callbackTid, prio2);
         }
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References callbackTid, UsbdConfig::cbThreadPrio, ChangeThreadPriority(), UsbdConfig::hcdThreadPrio, hcdTid, SetGP(), SetModuleGP, USB_RC_BADCONTEXT, usbConfig, usbdLock(), and usbdUnlock().
sceUsbdClosePipe()
int sceUsbdClosePipe (int id)
Definition at line 211 of file interface.c.
{
         Endpoint *ep;
         int res;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return -1;
         }
         ep = fetchEndpointById(id);
         if (ep)
                 res = doCloseEndpoint(ep);
         else
                 res = USB_RC_BADPIPE;
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References doCloseEndpoint(), fetchEndpointById(), SetGP(), SetModuleGP, USB_RC_BADPIPE, usbdLock(), and usbdUnlock().
Referenced by mass_stor_release(), PS2CamDisconnect(), PS2CamSetDeviceBandwidth(), and usb_mass_release().
sceUsbdGetDeviceLocation()
int sceUsbdGetDeviceLocation (int devId, u8 * path)
Definition at line 119 of file interface.c.
{
         Device *dev;
         int res;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return USB_RC_BADCONTEXT;
         }
         dev = fetchDeviceById(devId);
         if (dev)
                 res = doGetDeviceLocation(dev, path);
         else
                 res = USB_RC_BADDEV;
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References doGetDeviceLocation(), fetchDeviceById(), SetGP(), SetModuleGP, USB_RC_BADCONTEXT, USB_RC_BADDEV, usbdLock(), and usbdUnlock().
sceUsbdGetPrivateData()
void* sceUsbdGetPrivateData (int devId)
Definition at line 165 of file interface.c.
{
         Device *dev;
         void *res = NULL;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return NULL;
         }
         dev = fetchDeviceById(devId);
         if (dev)
                 res = dev->privDataField;
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References fetchDeviceById(), NULL, Device::privDataField, SetGP(), SetModuleGP, usbdLock(), and usbdUnlock().
sceUsbdOpenPipe()
int sceUsbdOpenPipe (int devId, UsbEndpointDescriptor * desc)
Definition at line 186 of file interface.c.
{
         Device *dev;
         Endpoint *ep;
         int res = -1;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return -1;
         }
         dev = fetchDeviceById(devId);
         if (dev) {
                 ep = doOpenEndpoint(dev, desc, 0);
                 if (ep)
                         res = ep->id;
         }
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References doOpenEndpoint(), fetchDeviceById(), Endpoint::id, SetGP(), SetModuleGP, usbdLock(), and usbdUnlock().
Referenced by mass_stor_connect(), PS2CamConnect(), PS2CamSetDeviceBandwidth(), ps2kbd_connect(), ps2mouse_connect(), usb_bulk_probeEndpoint(), and usb_mass_connect().
sceUsbdOpenPipeAligned()
int sceUsbdOpenPipeAligned (int devId, UsbEndpointDescriptor * desc)
Definition at line 297 of file interface.c.
{
         Device *dev;
         Endpoint *ep;
         int res = -1;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return -1;
         }
         dev = fetchDeviceById(devId);
         if (dev) {
                 ep = doOpenEndpoint(dev, desc, 1);
                 if (ep)
                         res = ep->id;
         }
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References doOpenEndpoint(), fetchDeviceById(), Endpoint::id, SetGP(), SetModuleGP, usbdLock(), and usbdUnlock().
Referenced by usb_bulk_probeEndpoint().
sceUsbdRegisterAutoloader()
int sceUsbdRegisterAutoloader (sceUsbdLddOps * drv)
Definition at line 47 of file interface.c.
{
         int res;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return USB_RC_BADCONTEXT;
         }
         res = doRegisterAutoLoader(drv, OldGP);
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References doRegisterAutoLoader(), SetGP(), SetModuleGP, USB_RC_BADCONTEXT, usbdLock(), and usbdUnlock().
sceUsbdRegisterLdd()
int sceUsbdRegisterLdd (sceUsbdLddOps * driver)
Definition at line 29 of file interface.c.
{
         int res;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return USB_RC_BADCONTEXT;
         }
         res = doRegisterDriver(driver, OldGP);
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References doRegisterDriver(), driver, SetGP(), SetModuleGP, USB_RC_BADCONTEXT, usbdLock(), and usbdUnlock().
Referenced by InitUSB(), PS2CamInitDriver(), ps2kbd_init(), ps2mouse_init(), and usb_mass_init().
sceUsbdScanStaticDescriptor()
void* sceUsbdScanStaticDescriptor (int devId, void * data, u8 type)
Definition at line 101 of file interface.c.
{
         void *res;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return NULL;
         }
         res = doGetDeviceStaticDescriptor(devId, data, type);
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References doGetDeviceStaticDescriptor(), NULL, SetGP(), SetModuleGP, usbdLock(), and usbdUnlock().
Referenced by mass_stor_connect(), mass_stor_probe(), PS2CamConnect(), PS2CamGetDeviceInfo(), PS2CamInitializeNewDevice(), PS2CamProbe(), PS2CamSetDeviceBandwidth(), ps2kbd_connect(), ps2kbd_probe(), ps2mouse_connect(), ps2mouse_probe(), usb_mass_connect(), and usb_mass_probe().
sceUsbdSetPrivateData()
int sceUsbdSetPrivateData (int devId, void * data)
Definition at line 142 of file interface.c.
{
         Device *dev;
         int res = USB_RC_OK;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return USB_RC_BADCONTEXT;
         }
         dev = fetchDeviceById(devId);
         if (dev)
                 dev->privDataField = data;
         else
                 res = USB_RC_BADDEV;
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References fetchDeviceById(), Device::privDataField, SetGP(), SetModuleGP, USB_RC_BADCONTEXT, USB_RC_BADDEV, USB_RC_OK, usbdLock(), and usbdUnlock().
Referenced by ps2kbd_connect(), and ps2mouse_connect().
sceUsbdTransferPipe()
int sceUsbdTransferPipe (int id, void * data, u32 len, void * option, sceUsbdDoneCallback callback, void * cbArg)
Definition at line 234 of file interface.c.
{
         UsbDeviceRequest *ctrlPkt = (UsbDeviceRequest *)option;
         IoRequest *req;
         Endpoint *ep;
         int res = 0;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return USB_RC_BADCONTEXT;
         }
         ep = fetchEndpointById(id);
         if (!ep) {
                 dbg_printf("sceUsbdTransferPipe: Endpoint %d not found\n", id);
                 res = USB_RC_BADPIPE;
         }
         if ((res == 0) && data && len) {
                 if ((((u32)(data + len - 1) >> 12) - ((u32)data >> 12)) > 1)
                         res = USB_RC_BADLENGTH;
                 else if (ep->alignFlag && ((u32)data & 3))
                         res = USB_RC_BADALIGN;
                 else if ((ep->endpointType == TYPE_ISOCHRON) && ((ep->hcEd.maxPacketSize & 0x7FF) < len))
                         res = USB_RC_BADLENGTH;
         }
         if (res == 0) {
                 req = allocIoRequest();
                 if (!req) {
                         dbg_printf("Ran out of IoReqs\n");
                         res = USB_RC_IOREQ;
                 }
         }
         if (res == 0) {
                 req->userCallbackProc = callback;
                 req->userCallbackArg = cbArg;
                 req->gpSeg = GetGP(); // gp of the calling module
                 if (ep->endpointType == TYPE_CONTROL) {
                         if (!ctrlPkt) {
                                 res = USB_RC_BADOPTION;
                                 freeIoRequest(req);
                         } else if (ctrlPkt->length != len) {
                                 res = USB_RC_BADLENGTH;
                                 freeIoRequest(req);
                         } else {
                                 res = doControlTransfer(ep, req,
                                         ctrlPkt->requesttype, ctrlPkt->request, ctrlPkt->value, ctrlPkt->index, ctrlPkt->length,
                                         data, signalCallbackThreadFunc);
                         }
                 } else {
                         if (ep->endpointType == TYPE_ISOCHRON)
                                 req->waitFrames = (u32)option;
                         res = attachIoReqToEndpoint(ep, req, data, len, signalCallbackThreadFunc);
                 }
         }
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References Endpoint::alignFlag, allocIoRequest(), attachIoReqToEndpoint(), dbg_printf, doControlTransfer(), Endpoint::endpointType, fetchEndpointById(), freeIoRequest(), GetGP(), IoRequest::gpSeg, Endpoint::hcEd, UsbDeviceRequest::index, UsbDeviceRequest::length, HcED::maxPacketSize, UsbDeviceRequest::request, UsbDeviceRequest::requesttype, SetGP(), SetModuleGP, signalCallbackThreadFunc(), TYPE_CONTROL, TYPE_ISOCHRON, USB_RC_BADALIGN, USB_RC_BADCONTEXT, USB_RC_BADLENGTH, USB_RC_BADOPTION, USB_RC_BADPIPE, USB_RC_IOREQ, usbdLock(), usbdUnlock(), IoRequest::userCallbackArg, IoRequest::userCallbackProc, UsbDeviceRequest::value, and IoRequest::waitFrames.
Referenced by sceUsbdControlTransfer().
sceUsbdUnregisterAutoloader()
int sceUsbdUnregisterAutoloader (void)
Definition at line 83 of file interface.c.
{
         int res;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return USB_RC_BADCONTEXT;
         }
         res = doUnregisterAutoLoader();
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References doUnregisterAutoLoader(), SetGP(), SetModuleGP, USB_RC_BADCONTEXT, usbdLock(), and usbdUnlock().
sceUsbdUnregisterLdd()
int sceUsbdUnregisterLdd (sceUsbdLddOps * driver)
Definition at line 65 of file interface.c.
{
         int res;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return USB_RC_BADCONTEXT;
         }
         res = doUnregisterDriver(driver);
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References doUnregisterDriver(), driver, SetGP(), SetModuleGP, USB_RC_BADCONTEXT, usbdLock(), and usbdUnlock().
Variable Documentation
callbackTid
int callbackTid extern
Definition at line 33 of file driver.c.
Referenced by initCallbackThread(), and sceUsbdChangeThreadPriority().
hcdTid
int hcdTid extern
Definition at line 31 of file hcd.c.
Referenced by hcdInit(), and sceUsbdChangeThreadPriority().
usbConfig
UsbdConfig usbConfig extern
Definition at line 34 of file usbd.c.
Referenced by cleanUpFunc(), fetchConfigDescriptors(), fetchDeviceById(), fetchEndpointById(), freeDevice(), freeIoRequest(), hcdInit(), hubCheckPorts(), initCallbackThread(), initHcdStructs(), initHubDriver(), killEndpoint(), and sceUsbdChangeThreadPriority().