ps2sdk: iop/network/netman/src/include/internal.h File Reference
internal.h File Reference
Functions
void NetManUpdateStackNIFLinkState (void)
void NetManToggleGlobalNetIFLinkState (unsigned char state)
void * malloc (int size)
void free (void *buffer)
Function Documentation
free()
void free (void * buffer)
Definition at line 63 of file main.c.
 {
     int OldState;
     CpuSuspendIntr(&OldState);
     FreeSysMemory(ptr);
     CpuResumeIntr(OldState);
 }
malloc()
void* malloc (int size)
Definition at line 51 of file main.c.
 {
     void* result;
     int OldState;
     CpuSuspendIntr(&OldState);
     result = AllocSysMemory(ALLOC_FIRST, size, NULL);
     CpuResumeIntr(OldState);
     return result;
 }
NetManToggleGlobalNetIFLinkState()
void NetManToggleGlobalNetIFLinkState (unsigned char state)
Definition at line 66 of file netman.c.
{
         NIFLinkState = state;
         NetManUpdateStackNIFLinkState();
 }
References NetManUpdateStackNIFLinkState(), NIFLinkState, and state.
Referenced by UpdateNetIFStatus().
NetManUpdateStackNIFLinkState()
void NetManUpdateStackNIFLinkState (void)
Definition at line 76 of file netman.c.
{
         if(IsInitialized){
                 if(NIFLinkState){
                         MainNetProtStack.LinkStateUp();
                 }
                 else{
                         MainNetProtStack.LinkStateDown();
                 }
         }
 }
References IsInitialized, NetManNetProtStack::LinkStateDown, NetManNetProtStack::LinkStateUp, MainNetProtStack, and NIFLinkState.
Referenced by NetManRegisterNetworkStack(), and NetManToggleGlobalNetIFLinkState().