ps2sdk: iop/kernel/include/ioman_mod.h File Reference
ioman_mod.h File Reference
#include <types.h>
#include <irx.h>
#include <io_common.h>
#include <iox_stat.h>
Data Structures
struct iop_io_file_t
struct iop_io_device_t
struct iop_io_device_ops_t
Macros
#define IOP_DT_CHAR 0x01
#define IOP_DT_CONS 0x02
#define IOP_DT_BLOCK 0x04
#define IOP_DT_RAW 0x08
#define IOP_DT_FS 0x10
#define ioman_mod_IMPORTS_start DECLARE_IMPORT_TABLE(ioman, 1, 1)
#define ioman_mod_IMPORTS_end END_IMPORT_TABLE
#define I_io_open DECLARE_IMPORT(4, io_open)
#define I_io_close DECLARE_IMPORT(5, io_close)
#define I_io_read DECLARE_IMPORT(6, io_read)
#define I_io_write DECLARE_IMPORT(7, io_write)
#define I_io_lseek DECLARE_IMPORT(8, io_lseek)
#define I_io_ioctl DECLARE_IMPORT(9, io_ioctl)
#define I_io_remove DECLARE_IMPORT(10, io_remove)
#define I_io_mkdir DECLARE_IMPORT(11, io_mkdir)
#define I_io_rmdir DECLARE_IMPORT(12, io_rmdir)
#define I_io_dopen DECLARE_IMPORT(13, io_dopen)
#define I_io_dclose DECLARE_IMPORT(14, io_dclose)
#define I_io_dread DECLARE_IMPORT(15, io_dread)
#define I_io_getstat DECLARE_IMPORT(16, io_getstat)
#define I_io_chstat DECLARE_IMPORT(17, io_chstat)
#define I_io_format DECLARE_IMPORT(18, io_format)
#define I_io_AddDrv DECLARE_IMPORT(20, io_AddDrv);
#define I_io_DelDrv DECLARE_IMPORT(21, io_DelDrv);
Functions
int io_open (const char *name, int mode)
int io_close (int fd)
int io_read (int fd, void *ptr, size_t size)
int io_write (int fd, void *ptr, size_t size)
int io_lseek (int fd, int pos, int mode)
int io_ioctl (int fd, unsigned long arg, void *param)
int io_remove (const char *name)
int io_mkdir (const char *path)
int io_rmdir (const char *path)
int io_dopen (const char *path, int mode)
int io_dclose (int fd)
int io_dread (int fd, io_dirent_t *buf)
int io_getstat (const char *name, io_stat_t *stat)
int io_chstat (const char *name, io_stat_t *stat, unsigned int statmask)
int io_format (const char *dev)
int io_AddDrv (iop_io_device_t *device)
int io_DelDrv (const char *name)
Detailed Description
IOMAN definitions and imports.
Definition in file ioman_mod.h.
Macro Definition Documentation
I_io_AddDrv
#define I_io_AddDrv DECLARE_IMPORT(20, io_AddDrv);
Definition at line 112 of file ioman_mod.h.
I_io_chstat
#define I_io_chstat DECLARE_IMPORT(17, io_chstat)
Definition at line 110 of file ioman_mod.h.
I_io_close
#define I_io_close DECLARE_IMPORT(5, io_close)
Definition at line 98 of file ioman_mod.h.
I_io_dclose
#define I_io_dclose DECLARE_IMPORT(14, io_dclose)
Definition at line 107 of file ioman_mod.h.
I_io_DelDrv
#define I_io_DelDrv DECLARE_IMPORT(21, io_DelDrv);
Definition at line 113 of file ioman_mod.h.
I_io_dopen
#define I_io_dopen DECLARE_IMPORT(13, io_dopen)
Definition at line 106 of file ioman_mod.h.
I_io_dread
#define I_io_dread DECLARE_IMPORT(15, io_dread)
Definition at line 108 of file ioman_mod.h.
I_io_format
#define I_io_format DECLARE_IMPORT(18, io_format)
Definition at line 111 of file ioman_mod.h.
I_io_getstat
#define I_io_getstat DECLARE_IMPORT(16, io_getstat)
Definition at line 109 of file ioman_mod.h.
I_io_ioctl
#define I_io_ioctl DECLARE_IMPORT(9, io_ioctl)
Definition at line 102 of file ioman_mod.h.
I_io_lseek
#define I_io_lseek DECLARE_IMPORT(8, io_lseek)
Definition at line 101 of file ioman_mod.h.
I_io_mkdir
#define I_io_mkdir DECLARE_IMPORT(11, io_mkdir)
Definition at line 104 of file ioman_mod.h.
I_io_open
#define I_io_open DECLARE_IMPORT(4, io_open)
Definition at line 97 of file ioman_mod.h.
I_io_read
#define I_io_read DECLARE_IMPORT(6, io_read)
Definition at line 99 of file ioman_mod.h.
I_io_remove
#define I_io_remove DECLARE_IMPORT(10, io_remove)
Definition at line 103 of file ioman_mod.h.
I_io_rmdir
#define I_io_rmdir DECLARE_IMPORT(12, io_rmdir)
Definition at line 105 of file ioman_mod.h.
I_io_write
#define I_io_write DECLARE_IMPORT(7, io_write)
Definition at line 100 of file ioman_mod.h.
ioman_mod_IMPORTS_end
#define ioman_mod_IMPORTS_end END_IMPORT_TABLE
Definition at line 95 of file ioman_mod.h.
ioman_mod_IMPORTS_start
#define ioman_mod_IMPORTS_start DECLARE_IMPORT_TABLE(ioman, 1, 1)
Definition at line 94 of file ioman_mod.h.
IOP_DT_BLOCK
#define IOP_DT_BLOCK 0x04
Definition at line 46 of file ioman_mod.h.
IOP_DT_CHAR
#define IOP_DT_CHAR 0x01
Definition at line 44 of file ioman_mod.h.
IOP_DT_CONS
#define IOP_DT_CONS 0x02
Definition at line 45 of file ioman_mod.h.
IOP_DT_FS
#define IOP_DT_FS 0x10
Definition at line 48 of file ioman_mod.h.
IOP_DT_RAW
#define IOP_DT_RAW 0x08
Definition at line 47 of file ioman_mod.h.
Function Documentation
io_AddDrv()
int io_AddDrv (iop_io_device_t * device)
Referenced by _start().
io_chstat()
int io_chstat (const char * name, io_stat_t * stat, unsigned int statmask)
io_close()
int io_close (int fd)
Referenced by ps2netfs_op_close().
io_dclose()
int io_dclose (int fd)
Referenced by ps2netfs_op_dclose().
io_DelDrv()
int io_DelDrv (const char * name)
Referenced by _start().
io_dopen()
int io_dopen (const char * path, int mode)
Referenced by ps2netfs_op_dopen().
io_dread()
int io_dread (int fd, io_dirent_t * buf)
Referenced by dread(), ioman_dread(), and ps2netfs_op_dread().
io_format()
int io_format (const char * dev)
io_getstat()
int io_getstat (const char * name, io_stat_t * stat)
io_ioctl()
int io_ioctl (int fd, unsigned long arg, void * param)
Referenced by ps2netfs_op_ioctl().
io_lseek()
int io_lseek (int fd, int pos, int mode)
Referenced by ps2netfs_op_lseek().
io_mkdir()
int io_mkdir (const char * path)
Referenced by ps2netfs_op_mkdir().
io_open()
int io_open (const char * name, int mode)
Referenced by ps2netfs_op_open().
io_read()
int io_read (int fd, void * ptr, size_t size)
Referenced by ps2netfs_op_read().
io_remove()
int io_remove (const char * name)
Referenced by ps2netfs_op_remove().
io_rmdir()
int io_rmdir (const char * path)
Referenced by ps2netfs_op_rmdir().
io_write()
int io_write (int fd, void * ptr, size_t size)
Referenced by ps2netfs_op_write().