ps2sdk: iop/kernel/include/iomanX.h File Reference
iomanX.h File Reference
#include <types.h>
#include <irx.h>
#include <io_common.h>
#include <iox_stat.h>
Data Structures
struct iop_file_t
struct iop_device_t
struct iop_device_ops_t
Macros
#define IOP_DT_CHAR 0x01
#define IOP_DT_CONS 0x02
#define IOP_DT_BLOCK 0x04
#define IOP_DT_RAW 0x08
#define IOP_DT_FS 0x10
#define IOP_DT_FSEXT 0x10000000
#define iomanX_IMPORTS_start DECLARE_IMPORT_TABLE(iomanx, 1, 1)
#define iomanX_IMPORTS_end END_IMPORT_TABLE
#define I_GetDeviceList DECLARE_IMPORT(3, GetDeviceList)
#define I_open DECLARE_IMPORT(4, open)
#define I_close DECLARE_IMPORT(5, close)
#define I_read DECLARE_IMPORT(6, read)
#define I_write DECLARE_IMPORT(7, write)
#define I_lseek DECLARE_IMPORT(8, lseek)
#define I_ioctl DECLARE_IMPORT(9, ioctl)
#define I_remove DECLARE_IMPORT(10, remove)
#define I_mkdir DECLARE_IMPORT(11, mkdir)
#define I_rmdir DECLARE_IMPORT(12, rmdir)
#define I_dopen DECLARE_IMPORT(13, dopen)
#define I_dclose DECLARE_IMPORT(14, dclose)
#define I_dread DECLARE_IMPORT(15, dread)
#define I_getstat DECLARE_IMPORT(16, getstat)
#define I_chstat DECLARE_IMPORT(17, chstat)
#define I_format DECLARE_IMPORT(18, format)
#define I_rename DECLARE_IMPORT(25, rename)
#define I_chdir DECLARE_IMPORT(26, chdir)
#define I_sync DECLARE_IMPORT(27, sync)
#define I_mount DECLARE_IMPORT(28, mount)
#define I_umount DECLARE_IMPORT(29, umount)
#define I_lseek64 DECLARE_IMPORT(30, lseek64)
#define I_devctl DECLARE_IMPORT(31, devctl)
#define I_symlink DECLARE_IMPORT(32, symlink)
#define I_readlink DECLARE_IMPORT(33, readlink)
#define I_ioctl2 DECLARE_IMPORT(34, ioctl2)
#define I_AddDrv DECLARE_IMPORT(20, AddDrv);
#define I_DelDrv DECLARE_IMPORT(21, DelDrv);
#define I_StdioInit DECLARE_IMPORT(23, StdioInit);
Functions
iop_device_t ** GetDeviceList (void)
int open (const char *name, int flags,...)
int close (int fd)
int read (int fd, void *ptr, int size)
int write (int fd, void *ptr, int size)
int lseek (int fd, int offset, int mode)
int ioctl (int fd, int cmd, void *param)
int remove (const char *name)
int mkdir (const char *path, int mode)
int rmdir (const char *path)
int dopen (const char *path)
int dclose (int fd)
int dread (int fd, iox_dirent_t *buf)
int getstat (const char *name, iox_stat_t *stat)
int chstat (const char *name, iox_stat_t *stat, unsigned int statmask)
int format (const char *dev, const char *blockdev, void *arg, int arglen)
int rename (const char *old, const char *new)
int chdir (const char *name)
int sync (const char *dev, int flag)
int mount (const char *fsname, const char *devname, int flag, void *arg, int arglen)
int umount (const char *fsname)
s64 lseek64 (int fd, s64 offset, int whence)
int devctl (const char *name, int cmd, void *arg, unsigned int arglen, void *buf, unsigned int buflen)
int symlink (const char *old, const char *new)
int readlink (const char *path, char *buf, unsigned int buflen)
int ioctl2 (int fd, int cmd, void *arg, unsigned int arglen, void *buf, unsigned int buflen)
int AddDrv (iop_device_t *device)
int DelDrv (const char *name)
void StdioInit (int mode)
Detailed Description
Definitions and imports for iomanX.
Definition in file iomanX.h.
Macro Definition Documentation
I_AddDrv
#define I_AddDrv DECLARE_IMPORT(20, AddDrv);
Definition at line 163 of file iomanX.h.
I_chdir
#define I_chdir DECLARE_IMPORT(26, chdir)
Definition at line 154 of file iomanX.h.
I_chstat
#define I_chstat DECLARE_IMPORT(17, chstat)
Definition at line 151 of file iomanX.h.
I_close
#define I_close DECLARE_IMPORT(5, close)
Definition at line 139 of file iomanX.h.
I_dclose
#define I_dclose DECLARE_IMPORT(14, dclose)
Definition at line 148 of file iomanX.h.
I_DelDrv
#define I_DelDrv DECLARE_IMPORT(21, DelDrv);
Definition at line 164 of file iomanX.h.
I_devctl
#define I_devctl DECLARE_IMPORT(31, devctl)
Definition at line 159 of file iomanX.h.
I_dopen
#define I_dopen DECLARE_IMPORT(13, dopen)
Definition at line 147 of file iomanX.h.
I_dread
#define I_dread DECLARE_IMPORT(15, dread)
Definition at line 149 of file iomanX.h.
I_format
#define I_format DECLARE_IMPORT(18, format)
Definition at line 152 of file iomanX.h.
I_GetDeviceList
#define I_GetDeviceList DECLARE_IMPORT(3, GetDeviceList)
Definition at line 137 of file iomanX.h.
I_getstat
#define I_getstat DECLARE_IMPORT(16, getstat)
Definition at line 150 of file iomanX.h.
I_ioctl
#define I_ioctl DECLARE_IMPORT(9, ioctl)
Definition at line 143 of file iomanX.h.
I_ioctl2
#define I_ioctl2 DECLARE_IMPORT(34, ioctl2)
Definition at line 162 of file iomanX.h.
I_lseek
#define I_lseek DECLARE_IMPORT(8, lseek)
Definition at line 142 of file iomanX.h.
I_lseek64
#define I_lseek64 DECLARE_IMPORT(30, lseek64)
Definition at line 158 of file iomanX.h.
I_mkdir
#define I_mkdir DECLARE_IMPORT(11, mkdir)
Definition at line 145 of file iomanX.h.
I_mount
#define I_mount DECLARE_IMPORT(28, mount)
Definition at line 156 of file iomanX.h.
I_open
#define I_open DECLARE_IMPORT(4, open)
Definition at line 138 of file iomanX.h.
I_read
#define I_read DECLARE_IMPORT(6, read)
Definition at line 140 of file iomanX.h.
I_readlink
#define I_readlink DECLARE_IMPORT(33, readlink)
Definition at line 161 of file iomanX.h.
I_remove
#define I_remove DECLARE_IMPORT(10, remove)
Definition at line 144 of file iomanX.h.
I_rename
#define I_rename DECLARE_IMPORT(25, rename)
Definition at line 153 of file iomanX.h.
I_rmdir
#define I_rmdir DECLARE_IMPORT(12, rmdir)
Definition at line 146 of file iomanX.h.
I_StdioInit
#define I_StdioInit DECLARE_IMPORT(23, StdioInit);
Definition at line 165 of file iomanX.h.
I_symlink
#define I_symlink DECLARE_IMPORT(32, symlink)
Definition at line 160 of file iomanX.h.
I_sync
#define I_sync DECLARE_IMPORT(27, sync)
Definition at line 155 of file iomanX.h.
I_umount
#define I_umount DECLARE_IMPORT(29, umount)
Definition at line 157 of file iomanX.h.
I_write
#define I_write DECLARE_IMPORT(7, write)
Definition at line 141 of file iomanX.h.
iomanX_IMPORTS_end
#define iomanX_IMPORTS_end END_IMPORT_TABLE
Definition at line 135 of file iomanX.h.
iomanX_IMPORTS_start
#define iomanX_IMPORTS_start DECLARE_IMPORT_TABLE(iomanx, 1, 1)
Definition at line 134 of file iomanX.h.
IOP_DT_BLOCK
#define IOP_DT_BLOCK 0x04
Definition at line 29 of file iomanX.h.
IOP_DT_CHAR
#define IOP_DT_CHAR 0x01
Definition at line 27 of file iomanX.h.
IOP_DT_CONS
#define IOP_DT_CONS 0x02
Definition at line 28 of file iomanX.h.
IOP_DT_FS
#define IOP_DT_FS 0x10
Definition at line 31 of file iomanX.h.
IOP_DT_FSEXT
#define IOP_DT_FSEXT 0x10000000
Supports calls after chstat().
Definition at line 34 of file iomanX.h.
IOP_DT_RAW
#define IOP_DT_RAW 0x08
Definition at line 30 of file iomanX.h.
Function Documentation
AddDrv()
int AddDrv (iop_device_t * device)
Definition at line 72 of file iomanX.c.
 {
         int i, res = -1;
     int oldIntr;
     CpuSuspendIntr(&oldIntr);
         for (i = 0; i < MAX_DEVICES; i++)
         {
                 if (dev_list[i] == NULL)
                         break;
         }
         if (i >= MAX_DEVICES)
         {
             CpuResumeIntr(oldIntr);
                 return res;
         }
         dev_list[i] = device;
     CpuResumeIntr(oldIntr);
     FlushIcache();
         if ((res = device->ops->init(device)) < 0)
         {
                 dev_list[i] = NULL;
                 return(-1);
         }
         return(0);
 }
chdir()
int chdir (const char * name)
Definition at line 545 of file iomanX.c.
 {
         return path_common(name, 0, 0x103);
 }
References irx_export_table::name, and path_common().
Referenced by fileXioRpc_ChDir(), and ps2netfs_op_chdir().
chstat()
int chstat (const char * name, iox_stat_t * stat, unsigned int statmask)
Definition at line 485 of file iomanX.c.
 {
         iop_file_t file;
         char *filename;
         if ((filename = find_iop_device(name, &file.unit, &file.device)) == (char *)-1)
                 return -ENODEV;
         /* If this is a legacy device (such as mc:) then we need to convert the mode
            variable to iomanX's extended format.  */
         if ((file.device->type & 0xf0000000) != IOP_DT_FSEXT)
                 stat->mode = modex2mode(stat->mode);
     return file.device->ops->chstat(&file, filename, stat, mask);
 }
References iop_file_t::device, ENODEV, find_iop_device(), IOP_DT_FSEXT, iox_stat_t::mode, modex2mode(), irx_export_table::name, and iop_file_t::unit.
close()
int close (int fd)
Definition at line 239 of file iomanX.c.
 {
         iop_file_t *f;
         int res;
         if ((f = get_file(fd)) == NULL)
         {
                 return -EBADF;
         }
         if (f->mode & 8)
         {       /* Directory.  */
                 res = f->device->ops->dclose(f);
         }
         else
         {
                 res = f->device->ops->close(f);
         }
         f->mode = 0;
         f->device = NULL;
         return res;
 }
dclose()
int dclose (int fd)
DelDrv()
int DelDrv (const char * name)
Definition at line 105 of file iomanX.c.
 {
         int i;
         for (i = 0; i < MAX_DEVICES; i++) {
                 if (dev_list[i] != NULL && !strcmp(name, dev_list[i]->name)) {
                         dev_list[i]->ops->deinit(dev_list[i]);
                         dev_list[i] = NULL;
                         return 0;
                 }
         }
         return -1;
 }
devctl()
int devctl (const char * name, int cmd, void * arg, unsigned int arglen, void * buf, unsigned int buflen)
Definition at line 601 of file iomanX.c.
 {
         iop_file_t file;
         char *filename;
         if ((filename = find_iop_device(name, &file.unit, &file.device)) == (char *)-1)
                 return -ENODEV;
         /* The filesystem must support these ops.  */
         if ((file.device->type & 0xf0000000) != IOP_DT_FSEXT)
                 return -48;
         return file.device->ops->devctl(&file, filename, cmd, arg, arglen, buf, buflen);
 }
References arg, iop_file_t::device, ENODEV, find_iop_device(), IOP_DT_FSEXT, irx_export_table::name, and iop_file_t::unit.
Referenced by fileXioRpc_Devctl().
dopen()
int dopen (const char * path)
Definition at line 358 of file iomanX.c.
 {
         iop_file_t *f = get_new_file();
         char *filename;
         int res;
         if (!f)
                 return -EMFILE;
         if ((filename = find_iop_device(name, &f->unit, &f->device)) == (char *)-1)
         {
         f->device = NULL;
                 return -ENODEV;
         }
         f->mode = 8;    /* Indicates a directory.  */
         if ((res = f->device->ops->dopen(f, filename)) >= 0)
                 res = (int)(f - file_table);
         else
         {
         f->mode = 0;
         f->device = NULL;
         }
         return res;
 }
References iop_file_t::device, EMFILE, ENODEV, file_table, find_iop_device(), get_new_file(), iop_file_t::mode, irx_export_table::name, NULL, and iop_file_t::unit.
dread()
int dread (int fd, iox_dirent_t * buf)
Definition at line 429 of file iomanX.c.
 {
     iop_file_t *f = get_file(fd);
     int res;
     if (f == NULL ||  !(f->mode & 8))
             return -EBADF;
     /* If this is a legacy device (such as mc:) then we need to convert the mode
        variable of the stat structure to iomanX's extended format.  */
     if ((f->device->type & 0xf0000000) != IOP_DT_FSEXT)
     {
         typedef int     io_dread_t(iop_file_t *, io_dirent_t *);
         io_dirent_t io_dirent;
         io_dread_t *io_dread = (io_dread_t*) f->device->ops->dread;
         res = io_dread(f, &io_dirent);
         iox_dirent->stat.mode = mode2modex(io_dirent.stat.mode);
         iox_dirent->stat.attr = io_dirent.stat.attr;
         iox_dirent->stat.size = io_dirent.stat.size;
         memcpy(iox_dirent->stat.ctime, io_dirent.stat.ctime, sizeof(io_dirent.stat.ctime));
         memcpy(iox_dirent->stat.atime, io_dirent.stat.atime, sizeof(io_dirent.stat.atime));
         memcpy(iox_dirent->stat.mtime, io_dirent.stat.mtime, sizeof(io_dirent.stat.mtime));
         iox_dirent->stat.hisize = io_dirent.stat.hisize;
         strncpy(iox_dirent->name, io_dirent.name, sizeof(iox_dirent->name));
     }
     else
         res = f->device->ops->dread(f, iox_dirent);
     return res;
 }
References io_stat_t::atime, iox_stat_t::atime, io_stat_t::attr, iox_stat_t::attr, io_stat_t::ctime, iox_stat_t::ctime, iop_file_t::device, EBADF, get_file(), io_stat_t::hisize, iox_stat_t::hisize, io_dread(), IOP_DT_FSEXT, memcpy(), io_stat_t::mode, iox_stat_t::mode, iop_file_t::mode, mode2modex(), io_stat_t::mtime, iox_stat_t::mtime, io_dirent_t::name, iox_dirent_t::name, NULL, io_stat_t::size, iox_stat_t::size, io_dirent_t::stat, iox_dirent_t::stat, and strncpy().
format()
int format (const char * dev, const char * blockdev, void * arg, int arglen)
This can take take more than one form.
Definition at line 501 of file iomanX.c.
 {
         iop_file_t file;
         char *filename;
         if ((filename = find_iop_device(dev, &file.unit, &file.device)) == (char *)-1)
                 return -ENODEV;
         return file.device->ops->format(&file, filename, blockdev, arg, arglen);
 }
References arg, iop_file_t::device, ENODEV, find_iop_device(), and iop_file_t::unit.
GetDeviceList()
iop_device_t** GetDeviceList (void)
Definition at line 43 of file iomanX.c.
 {
     return(dev_list);
 }
References dev_list.
Referenced by fileXio_GetDeviceList_RPC(), hook_ioman(), and unhook_ioman().
getstat()
int getstat (const char * name, iox_stat_t * stat)
Definition at line 463 of file iomanX.c.
 {
         iop_file_t file;
         char *filename;
         int res;
         if ((filename = find_iop_device(name, &file.unit, &file.device)) == (char *)-1)
                 return -ENODEV;
         res = file.device->ops->getstat(&file, filename, stat);
     if (res == 0)
     {
         /* If this is a legacy device (such as mc:) then we need to convert the mode
            variable to iomanX's extended format.  */
         if ((file.device->type & 0xf0000000) != IOP_DT_FSEXT)
                 stat->mode = mode2modex(stat->mode);
     }
         return res;
 }
References iop_file_t::device, ENODEV, find_iop_device(), IOP_DT_FSEXT, iox_stat_t::mode, mode2modex(), irx_export_table::name, and iop_file_t::unit.
ioctl()
int ioctl (int fd, int cmd, void * param)
Definition at line 296 of file iomanX.c.
 {
         iop_file_t *f = get_file(fd);
         if (f == NULL)
                 return -EBADF;
         return f->device->ops->ioctl(f, cmd, arg);
 }
ioctl2()
int ioctl2 (int fd, int cmd, void * arg, unsigned int arglen, void * buf, unsigned int buflen)
Definition at line 637 of file iomanX.c.
 {
         iop_file_t *f;
         if ((f = get_file(fd)) == NULL)
                 return -EBADF;
         return f->device->ops->ioctl2(f, command, arg, arglen, buf, buflen);
 }
References arg, iop_file_t::device, EBADF, get_file(), and NULL.
Referenced by fileXioRpc_Ioctl2(), pfsHddFlushCache(), pfsHddGetPartSize(), pfsHddGetSubCount(), pfsHddSetPartError(), and pfsHddTransfer().
lseek()
int lseek (int fd, int offset, int mode)
Definition at line 283 of file iomanX.c.
 {
         iop_file_t *f = get_file(fd);
         if (f == NULL)
                 return -EBADF;
         if (whence < SEEK_SET || whence > SEEK_END)
                 return -EINVAL;
         return f->device->ops->lseek(f, offset, whence);
 }
lseek64()
s64 lseek64 (int fd, s64 offset, int whence)
Referenced by fileXioRpc_Lseek64().
mkdir()
int mkdir (const char * path, int mode)
Definition at line 348 of file iomanX.c.
 {
         return path_common(name, mode, 4);
 }
References irx_export_table::mode, irx_export_table::name, and path_common().
mount()
int mount (const char * fsname, const char * devname, int flag, void * arg, int arglen)
Definition at line 555 of file iomanX.c.
 {
         iop_file_t file;
         char *filename;
         if ((filename = find_iop_device(fsname, &file.unit, &file.device)) == (char *)-1)
                 return -ENODEV;
         /* The filesystem must support these ops.  */
         if ((file.device->type & 0xf0000000) != IOP_DT_FSEXT)
                 return -48;
         return file.device->ops->mount(&file, filename, devname, flag, arg, arglen);
 }
References arg, iop_file_t::device, ENODEV, find_iop_device(), IOP_DT_FSEXT, and iop_file_t::unit.
Referenced by bdm_try_mount(), fileXio_Mount_RPC(), and ps2netfs_op_mount().
open()
int open (const char * name, int flags, ...)
Definition at line 203 of file iomanX.c.
 {
         iop_file_t *f = get_new_file();
         char *filename;
         va_list alist;
         int res = -ENOSYS, mode;
         va_start(alist, flags);
         mode = va_arg(alist, int);
         va_end(alist);
         if (!f)
         {
                 return -EMFILE;
         }
         if ((filename = find_iop_device(name, &f->unit, &f->device)) == (char *)-1)
         {
         f->device = NULL;
                 return -ENODEV;
         }
         f->mode = flags;
         if ((res = f->device->ops->open(f, filename, flags, mode)) >= 0)
         {
                 res = (int)(f - file_table);
         }
         else
         {
         f->mode = 0;
         f->device = NULL;
         }
         return res;
 }
References iop_file_t::device, EMFILE, ENODEV, ENOSYS, file_table, find_iop_device(), get_new_file(), iop_file_t::mode, irx_export_table::mode, irx_export_table::name, NULL, and iop_file_t::unit.
read()
int read (int fd, void * ptr, int size)
Definition at line 263 of file iomanX.c.
 {
         iop_file_t *f = get_file(fd);
         if (f == NULL || !(f->mode & O_RDONLY))
                 return -EBADF;
         return f->device->ops->read(f, ptr, size);
 }
References iop_file_t::device, EBADF, get_file(), iop_file_t::mode, NULL, and O_RDONLY.
readlink()
int readlink (const char * path, char * buf, unsigned int buflen)
Definition at line 621 of file iomanX.c.
 {
         iop_file_t file;
         char *filename;
         if ((filename = find_iop_device(name, &file.unit, &file.device)) == (char *)-1)
                 return -ENODEV;
         /* The filesystem must support these ops.  */
         if ((file.device->type & 0xf0000000) != IOP_DT_FSEXT)
                 return -48;
         return file.device->ops->readlink(&file, filename, buf, buflen);
 }
References iop_file_t::device, ENODEV, find_iop_device(), IOP_DT_FSEXT, irx_export_table::name, and iop_file_t::unit.
Referenced by fileXioRpc_ReadLink(), and ps2netfs_op_readlink().
remove()
int remove (const char * name)
Definition at line 306 of file iomanX.c.
 {
         iop_file_t file;
         char *filename;
         if ((filename = find_iop_device(name, &file.unit, &file.device)) == (char *)-1)
                 return -ENODEV;
         return file.device->ops->remove(&file, filename);
 }
rename()
int rename (const char * old, const char * new)
Definition at line 540 of file iomanX.c.
 {
         return link_common(old, new, 7);
 }
References link_common().
Referenced by fileXioRpc_Rename(), and ps2netfs_op_rename().
rmdir()
int rmdir (const char * path)
Definition at line 353 of file iomanX.c.
 {
         return path_common(name, 0, 5);
 }
StdioInit()
void StdioInit (int mode)
symlink()
int symlink (const char * old, const char * new)
Definition at line 616 of file iomanX.c.
 {
         return link_common(old, new, 8);
 }
References link_common().
Referenced by fileXioRpc_SymLink(), and ps2netfs_op_symlink().
sync()
int sync (const char * dev, int flag)
Definition at line 550 of file iomanX.c.
 {
         return path_common(dev, flag, 0x106);
 }
References path_common().
Referenced by fileXioRpc_Sync(), and ps2netfs_op_sync().
umount()
int umount (const char * fsname)
Definition at line 570 of file iomanX.c.
 {
         iop_file_t file;
         char *filename;
         if ((filename = find_iop_device(fsname, &file.unit, &file.device)) == (char *)-1)
                 return -ENODEV;
         /* The filesystem must support these ops.  */
         if ((file.device->type & 0xf0000000) != IOP_DT_FSEXT)
                 return -48;
         return file.device->ops->umount(&file, filename);
 }
References iop_file_t::device, ENODEV, find_iop_device(), IOP_DT_FSEXT, and iop_file_t::unit.
Referenced by fileXioRpc_uMount(), and ps2netfs_op_umount().
write()
int write (int fd, void * ptr, int size)
Definition at line 273 of file iomanX.c.
 {
         iop_file_t *f = get_file(fd);
         if (f == NULL || !(f->mode & O_WRONLY))
                 return -EBADF;
         return f->device->ops->write(f, ptr, size);
 }
References iop_file_t::device, EBADF, get_file(), iop_file_t::mode, NULL, and O_WRONLY.