ps2sdk: iop/system/iomanx/src/iomanX.c File Reference
iomanX.c File Reference
#include "types.h"
#include "defs.h"
#include "loadcore.h"
#include "iomanX.h"
#include "sysclib.h"
#include "stdarg.h"
#include "intrman.h"
#include "errno.h"
Macros
#define MODNAME "iomanx"
#define MAX_DEVICES 32
#define MAX_FILES 32
#define isnum(c) ((c) >= '0' && (c) <= '9')
Functions
IRX_ID ("IOX/File_Manager", 1, 1)
int hook_ioman ()
int unhook_ioman ()
iop_device_t ** GetDeviceList (void)
int _start (int argc, char **argv)
int shutdown ()
int AddDrv (iop_device_t *device)
int DelDrv (const char *name)
static char * find_iop_device (const char *dev, int *unit, iop_device_t **device)
iop_file_t * get_file (int fd)
iop_file_t * get_new_file (void)
int open (const char *name, int flags,...)
int close (int fd)
int read (int fd, void *ptr, int size)
int write (int fd, void *ptr, int size)
int lseek (int fd, int offset, int whence)
int ioctl (int fd, int cmd, void *arg)
int remove (const char *name)
static int path_common (const char *name, int arg, int code)
int mkdir (const char *name, int mode)
int rmdir (const char *name)
int dopen (const char *name)
int mode2modex (int mode)
int modex2mode (int modex)
int dread (int fd, iox_dirent_t *iox_dirent)
int getstat (const char *name, iox_stat_t *stat)
int chstat (const char *name, iox_stat_t *stat, unsigned int mask)
int format (const char *dev, const char *blockdev, void *arg, int arglen)
static int link_common (const char *old, const char *new, int code)
int rename (const char *old, const char *new)
int chdir (const char *name)
int sync (const char *dev, int flag)
int mount (const char *fsname, const char *devname, int flag, void *arg, int arglen)
int umount (const char *fsname)
long long lseek64 (int fd, long long offset, int whence)
int devctl (const char *name, int cmd, void *arg, unsigned int arglen, void *buf, unsigned int buflen)
int symlink (const char *old, const char *new)
int readlink (const char *name, char *buf, unsigned int buflen)
int ioctl2 (int fd, int command, void *arg, unsigned int arglen, void *buf, unsigned int buflen)
Variables
static iop_device_t * dev_list [MAX_DEVICES]
iop_file_t file_table [MAX_FILES]
struct irx_export_table _exp_iomanx
Detailed Description
Advanced I/O library.
Definition in file iomanX.c.
Macro Definition Documentation
isnum
#define isnum (c) ((c) >= '0' && (c) <= '9')
Definition at line 36 of file iomanX.c.
MAX_DEVICES
#define MAX_DEVICES 32
Definition at line 30 of file iomanX.c.
MAX_FILES
#define MAX_FILES 32
Definition at line 31 of file iomanX.c.
MODNAME
#define MODNAME "iomanx"
Definition at line 25 of file iomanX.c.
Function Documentation
AddDrv()
int AddDrv (iop_device_t * device)
Definition at line 72 of file iomanX.c.
 {
         int i, res = -1;
     int oldIntr;
     CpuSuspendIntr(&oldIntr);
         for (i = 0; i < MAX_DEVICES; i++)
         {
                 if (dev_list[i] == NULL)
                         break;
         }
         if (i >= MAX_DEVICES)
         {
             CpuResumeIntr(oldIntr);
                 return res;
         }
         dev_list[i] = device;
     CpuResumeIntr(oldIntr);
     FlushIcache();
         if ((res = device->ops->init(device)) < 0)
         {
                 dev_list[i] = NULL;
                 return(-1);
         }
         return(0);
 }
References CpuResumeIntr(), CpuSuspendIntr(), dev_list, FlushIcache(), MAX_DEVICES, NULL, and iop_device_t::ops.
Referenced by _start(), hook_ioman(), init_devfs(), init_fio(), InitFS(), mcman_initdev(), sbus_tty_init(), and smb_initdev().
chdir()
int chdir (const char * name)
Definition at line 545 of file iomanX.c.
 {
         return path_common(name, 0, 0x103);
 }
References irx_export_table::name, and path_common().
Referenced by fileXioRpc_ChDir(), and ps2netfs_op_chdir().
chstat()
int chstat (const char * name, iox_stat_t * stat, unsigned int mask)
Definition at line 485 of file iomanX.c.
 {
         iop_file_t file;
         char *filename;
         if ((filename = find_iop_device(name, &file.unit, &file.device)) == (char *)-1)
                 return -ENODEV;
         /* If this is a legacy device (such as mc:) then we need to convert the mode
            variable to iomanX's extended format.  */
         if ((file.device->type & 0xf0000000) != IOP_DT_FSEXT)
                 stat->mode = modex2mode(stat->mode);
     return file.device->ops->chstat(&file, filename, stat, mask);
 }
References iop_file_t::device, ENODEV, find_iop_device(), IOP_DT_FSEXT, iox_stat_t::mode, modex2mode(), irx_export_table::name, and iop_file_t::unit.
close()
int close (int fd)
Definition at line 239 of file iomanX.c.
 {
         iop_file_t *f;
         int res;
         if ((f = get_file(fd)) == NULL)
         {
                 return -EBADF;
         }
         if (f->mode & 8)
         {       /* Directory.  */
                 res = f->device->ops->dclose(f);
         }
         else
         {
                 res = f->device->ops->close(f);
         }
         f->mode = 0;
         f->device = NULL;
         return res;
 }
References iop_file_t::device, EBADF, get_file(), iop_file_t::mode, and NULL.
Referenced by _start(), fd_close(), fileXio_CopyFile_RPC(), fileXio_GetDir_RPC(), fileXioRpc_Close(), hook_ioman(), pfsFioFormat(), pfsFioMount(), pfsFioUmount(), ps2netfs_op_close(), sbus_tty_init(), and sndStreamClose().
DelDrv()
int DelDrv (const char * name)
Definition at line 105 of file iomanX.c.
 {
         int i;
         for (i = 0; i < MAX_DEVICES; i++) {
                 if (dev_list[i] != NULL && !strcmp(name, dev_list[i]->name)) {
                         dev_list[i]->ops->deinit(dev_list[i]);
                         dev_list[i] = NULL;
                         return 0;
                 }
         }
         return -1;
 }
References dev_list, MAX_DEVICES, irx_export_table::name, NULL, iop_device_t::ops, and strcmp().
Referenced by _start(), hook_ioman(), init_devfs(), InitFS(), mcman_initdev(), sbus_tty_init(), and smb_initdev().
devctl()
int devctl (const char * name, int cmd, void * arg, unsigned int arglen, void * buf, unsigned int buflen)
Definition at line 601 of file iomanX.c.
 {
         iop_file_t file;
         char *filename;
         if ((filename = find_iop_device(name, &file.unit, &file.device)) == (char *)-1)
                 return -ENODEV;
         /* The filesystem must support these ops.  */
         if ((file.device->type & 0xf0000000) != IOP_DT_FSEXT)
                 return -48;
         return file.device->ops->devctl(&file, filename, cmd, arg, arglen, buf, buflen);
 }
References arg, iop_file_t::device, ENODEV, find_iop_device(), IOP_DT_FSEXT, irx_export_table::name, and iop_file_t::unit.
Referenced by fileXioRpc_Devctl().
dopen()
int dopen (const char * name)
Definition at line 358 of file iomanX.c.
 {
         iop_file_t *f = get_new_file();
         char *filename;
         int res;
         if (!f)
                 return -EMFILE;
         if ((filename = find_iop_device(name, &f->unit, &f->device)) == (char *)-1)
         {
         f->device = NULL;
                 return -ENODEV;
         }
         f->mode = 8;    /* Indicates a directory.  */
         if ((res = f->device->ops->dopen(f, filename)) >= 0)
                 res = (int)(f - file_table);
         else
         {
         f->mode = 0;
         f->device = NULL;
         }
         return res;
 }
References iop_file_t::device, EMFILE, ENODEV, file_table, find_iop_device(), get_new_file(), iop_file_t::mode, irx_export_table::name, NULL, and iop_file_t::unit.
dread()
int dread (int fd, iox_dirent_t * iox_dirent)
Definition at line 429 of file iomanX.c.
 {
     iop_file_t *f = get_file(fd);
     int res;
     if (f == NULL ||  !(f->mode & 8))
             return -EBADF;
     /* If this is a legacy device (such as mc:) then we need to convert the mode
        variable of the stat structure to iomanX's extended format.  */
     if ((f->device->type & 0xf0000000) != IOP_DT_FSEXT)
     {
         typedef int     io_dread_t(iop_file_t *, io_dirent_t *);
         io_dirent_t io_dirent;
         io_dread_t *io_dread = (io_dread_t*) f->device->ops->dread;
         res = io_dread(f, &io_dirent);
         iox_dirent->stat.mode = mode2modex(io_dirent.stat.mode);
         iox_dirent->stat.attr = io_dirent.stat.attr;
         iox_dirent->stat.size = io_dirent.stat.size;
         memcpy(iox_dirent->stat.ctime, io_dirent.stat.ctime, sizeof(io_dirent.stat.ctime));
         memcpy(iox_dirent->stat.atime, io_dirent.stat.atime, sizeof(io_dirent.stat.atime));
         memcpy(iox_dirent->stat.mtime, io_dirent.stat.mtime, sizeof(io_dirent.stat.mtime));
         iox_dirent->stat.hisize = io_dirent.stat.hisize;
         strncpy(iox_dirent->name, io_dirent.name, sizeof(iox_dirent->name));
     }
     else
         res = f->device->ops->dread(f, iox_dirent);
     return res;
 }
References io_stat_t::atime, iox_stat_t::atime, io_stat_t::attr, iox_stat_t::attr, io_stat_t::ctime, iox_stat_t::ctime, iop_file_t::device, EBADF, get_file(), io_stat_t::hisize, iox_stat_t::hisize, io_dread(), IOP_DT_FSEXT, memcpy(), io_stat_t::mode, iox_stat_t::mode, iop_file_t::mode, mode2modex(), io_stat_t::mtime, iox_stat_t::mtime, io_dirent_t::name, iox_dirent_t::name, NULL, io_stat_t::size, iox_stat_t::size, io_dirent_t::stat, iox_dirent_t::stat, and strncpy().
find_iop_device()
static char* find_iop_device (const char * dev, int * unit, iop_device_t ** device) static
Definition at line 121 of file iomanX.c.
 {
         char canon[16];
         char *filename, *tail, *d = (char *)dev;
         int i, len, num = 0;
         if (*d == ' ') {
                 while (*d == ' ')
                         d++;
                 d--;
         }
         if ((tail = index(d, ':')) == NULL)
                 return (char *)-1;
         len = (int)(tail - d);
         strncpy(canon, d, len);
         canon[len] = '\0';
         /* This is the name passed to the device op.  */
         filename = d + len + 1;
         /* Search backward for the unit number.  */
         if (isnum(canon[len - 1])) {
                 while (isnum(canon[len - 1]))
                         len--;
                 num = strtol(canon + len, 0, 10);
         }
         if (unit)
                 *unit = num;
         /* Find the actual device.  */
         canon[len] = '\0';
         for (i = 0; i < MAX_DEVICES; i++) {
                 if (dev_list[i] != NULL && !strcmp(canon, dev_list[i]->name)) {
                         if (device)
                                 *device = dev_list[i];
                         return filename;
                 }
         }
         return (char *)-1;
 }
References dev_list, index(), isnum, MAX_DEVICES, irx_export_table::name, NULL, strcmp(), strncpy(), and strtol().
Referenced by chstat(), devctl(), dopen(), format(), getstat(), link_common(), mount(), open(), path_common(), readlink(), remove(), and umount().
format()
int format (const char * dev, const char * blockdev, void * arg, int arglen)
This can take take more than one form.
Definition at line 501 of file iomanX.c.
 {
         iop_file_t file;
         char *filename;
         if ((filename = find_iop_device(dev, &file.unit, &file.device)) == (char *)-1)
                 return -ENODEV;
         return file.device->ops->format(&file, filename, blockdev, arg, arglen);
 }
References arg, iop_file_t::device, ENODEV, find_iop_device(), and iop_file_t::unit.
get_file()
iop_file_t* get_file (int fd)
Definition at line 167 of file iomanX.c.
 {
         if (fd >= MAX_FILES)
                 return NULL;
         if (file_table[fd].device != NULL)
                 return &file_table[fd];
         return NULL;
 }
References file_table, MAX_FILES, and NULL.
Referenced by close(), dread(), ioctl(), ioctl2(), ioman_dread(), lseek(), lseek64(), read(), and write().
get_new_file()
iop_file_t* get_new_file (void)
Definition at line 178 of file iomanX.c.
 {
         int i;
         iop_file_t *fd = NULL;
         int oldIntr;
         CpuSuspendIntr(&oldIntr);
         for (i = 0; i < MAX_FILES; i++)
         {
                 if (!file_table[i].device)
                 {
                         fd = &file_table[i];
                         // fill in "device" temporarily to mark the fd as allocated.
                         fd->device = (iop_device_t *) 0xFFFFFFFF;
                         break;
                 }
         }
         CpuResumeIntr(oldIntr);
         return fd;
 }
References CpuResumeIntr(), CpuSuspendIntr(), iop_file_t::device, file_table, MAX_FILES, and NULL.
Referenced by dopen(), and open().
GetDeviceList()
iop_device_t** GetDeviceList (void)
Definition at line 43 of file iomanX.c.
 {
     return(dev_list);
 }
References dev_list.
Referenced by fileXio_GetDeviceList_RPC(), hook_ioman(), and unhook_ioman().
getstat()
int getstat (const char * name, iox_stat_t * stat)
Definition at line 463 of file iomanX.c.
 {
         iop_file_t file;
         char *filename;
         int res;
         if ((filename = find_iop_device(name, &file.unit, &file.device)) == (char *)-1)
                 return -ENODEV;
         res = file.device->ops->getstat(&file, filename, stat);
     if (res == 0)
     {
         /* If this is a legacy device (such as mc:) then we need to convert the mode
            variable to iomanX's extended format.  */
         if ((file.device->type & 0xf0000000) != IOP_DT_FSEXT)
                 stat->mode = mode2modex(stat->mode);
     }
         return res;
 }
References iop_file_t::device, ENODEV, find_iop_device(), IOP_DT_FSEXT, iox_stat_t::mode, mode2modex(), irx_export_table::name, and iop_file_t::unit.
hook_ioman()
int hook_ioman ()
Definition at line 238 of file ioman_sbv.c.
 {
         iop_library_t ioman_library = { NULL, NULL, 0x102, 0, "ioman\0\0" };
         ModuleInfo_t info;
     dev_list = GetDeviceList();
         if (smod_get_mod_by_name(ioman_modname, &info))
         {
         // steal the original IOMAN's 16 registered device entries
         memcpy(dev_list, (void *) (info.text_start + info.text_size + info.data_size + 0x10), sizeof(iop_device_t *) * 16);
         // steal the original IOMAN's 16 file descriptors
         memcpy(file_table, (void *) (info.text_start + info.text_size + info.data_size + 0x50), sizeof(iop_file_t) * 16);
         }
         else { return(-1); }
     // patch the IOMAN export library table to call iomanX functions
         if ((ioman_exports = (u32 *)QueryLibraryEntryTable(&ioman_library)) != NULL)
         {
         /* Preserve ioman's library exports.  */
         Addr_IOMAN_open = ioman_exports[4];
         Addr_IOMAN_close = ioman_exports[5];
         Addr_IOMAN_read = ioman_exports[6];
         Addr_IOMAN_write = ioman_exports[7];
         Addr_IOMAN_lseek = ioman_exports[8];
         Addr_IOMAN_ioctl = ioman_exports[9];
         Addr_IOMAN_remove = ioman_exports[10];
         Addr_IOMAN_mkdir = ioman_exports[11];
         Addr_IOMAN_rmdir = ioman_exports[12];
         Addr_IOMAN_dopen = ioman_exports[13];
         Addr_IOMAN_dclose = ioman_exports[14];
         Addr_IOMAN_dread = ioman_exports[15];
         Addr_IOMAN_getstat = ioman_exports[16];
         Addr_IOMAN_chstat = ioman_exports[17];
         Addr_IOMAN_format = ioman_exports[18];
         Addr_IOMAN_AddDrv = ioman_exports[20];
         Addr_IOMAN_DelDrv = ioman_exports[21];
 #ifdef FULL_IOMAN
                 ioman_exports[4] = (u32) ioman_open;
                 ioman_exports[5] = (u32) close;
                 ioman_exports[6] = (u32) read;
                 ioman_exports[7] = (u32) write;
                 ioman_exports[8] = (u32) lseek;
                 ioman_exports[9] = (u32) ioctl;
                 ioman_exports[10] = (u32) remove;
                 ioman_exports[11] = (u32) ioman_mkdir;
                 ioman_exports[12] = (u32) rmdir;
                 ioman_exports[13] = (u32) dopen;
                 ioman_exports[14] = (u32) close;
                 ioman_exports[15] = (u32) ioman_dread;
                 ioman_exports[16] = (u32) ioman_getstat;
                 ioman_exports[17] = (u32) ioman_chstat;
                 ioman_exports[18] = (u32) ioman_format;
                 ioman_exports[20] = (u32) AddDrv;
                 ioman_exports[21] = (u32) DelDrv;
 #else
                 ioman_exports[20] = (u32) sbv_AddDrv;
                 ioman_exports[21] = (u32) sbv_DelDrv;
 #endif
         // repair all the tables that import the ioman library
         fix_imports((iop_library_t *) (((u32) ioman_exports) - 0x14));
         }
         else { return(-2); }
         return(0);
 }
References AddDrv(), Addr_IOMAN_AddDrv, Addr_IOMAN_chstat, Addr_IOMAN_close, Addr_IOMAN_dclose, Addr_IOMAN_DelDrv, Addr_IOMAN_dopen, Addr_IOMAN_dread, Addr_IOMAN_format, Addr_IOMAN_getstat, Addr_IOMAN_ioctl, Addr_IOMAN_lseek, Addr_IOMAN_mkdir, Addr_IOMAN_open, Addr_IOMAN_read, Addr_IOMAN_remove, Addr_IOMAN_rmdir, Addr_IOMAN_write, close(), DelDrv(), dev_list, dopen(), file_table, fix_imports(), GetDeviceList(), ioctl(), ioman_chstat(), ioman_dread(), ioman_exports, ioman_format(), ioman_getstat(), ioman_mkdir(), ioman_modname, ioman_open(), lseek(), memcpy(), NULL, QueryLibraryEntryTable(), read(), remove(), rmdir(), smod_get_mod_by_name(), and write().
Referenced by _start().
ioctl()
int ioctl (int fd, int cmd, void * arg)
Definition at line 296 of file iomanX.c.
 {
         iop_file_t *f = get_file(fd);
         if (f == NULL)
                 return -EBADF;
         return f->device->ops->ioctl(f, cmd, arg);
 }
References arg, iop_file_t::device, EBADF, get_file(), and NULL.
Referenced by fileXioRpc_Ioctl(), hook_ioman(), and ps2netfs_op_ioctl().
ioctl2()
int ioctl2 (int fd, int command, void * arg, unsigned int arglen, void * buf, unsigned int buflen)
Definition at line 637 of file iomanX.c.
 {
         iop_file_t *f;
         if ((f = get_file(fd)) == NULL)
                 return -EBADF;
         return f->device->ops->ioctl2(f, command, arg, arglen, buf, buflen);
 }
References arg, iop_file_t::device, EBADF, get_file(), and NULL.
Referenced by fileXioRpc_Ioctl2(), pfsHddFlushCache(), pfsHddGetPartSize(), pfsHddGetSubCount(), pfsHddSetPartError(), and pfsHddTransfer().
IRX_ID()
IRX_ID ("IOX/File_Manager" , 1 , 1)
link_common()
static int link_common (const char * old, const char * new, int code) static
Definition at line 512 of file iomanX.c.
 {
         iop_file_t file;
         iop_device_t *new_device;
         char *filename, *new_filename = (char *)new;
         int new_unit;
         if ((filename = find_iop_device(old, &file.unit, &file.device)) == (char *)-1)
                 return -ENODEV;
         /* Make sure the user isn't attempting to link across devices.  */
         if (index(new, ':') != NULL) {
                 new_filename = find_iop_device(new, &new_unit, &new_device);
                 if ((new_filename == (char *)-1) || (new_unit != file.unit) ||
                                 (new_device != file.device))
                         return -ENXIO;
         }
         /* The filesystem must support these ops.  */
         if ((file.device->type & 0xf0000000) != IOP_DT_FSEXT)
                 return -48;
         if (code == 7)  /* rename() */
                 return file.device->ops->rename(&file, filename, new_filename);
         return file.device->ops->symlink(&file, filename, new_filename);
 }
References iop_file_t::device, ENODEV, ENXIO, find_iop_device(), index(), IOP_DT_FSEXT, NULL, and iop_file_t::unit.
Referenced by rename(), and symlink().
lseek()
int lseek (int fd, int offset, int whence)
Definition at line 283 of file iomanX.c.
 {
         iop_file_t *f = get_file(fd);
         if (f == NULL)
                 return -EBADF;
         if (whence < SEEK_SET || whence > SEEK_END)
                 return -EINVAL;
         return f->device->ops->lseek(f, offset, whence);
 }
References iop_file_t::device, EBADF, EINVAL, get_file(), NULL, and SEEK_END.
Referenced by fd_lseek(), fileXio_CopyFile_RPC(), fileXioRpc_Lseek(), hook_ioman(), ps2netfs_op_lseek(), and sndStreamSetPosition().
lseek64()
long long lseek64 (int fd, long long offset, int whence)
Definition at line 585 of file iomanX.c.
 {
         iop_file_t *f = get_file(fd);
         if (f == NULL)
                 return -EBADF;
         if (whence < SEEK_SET || whence > SEEK_END)
                 return -EINVAL;
         if ((f->device->type & 0xf0000000) != IOP_DT_FSEXT)
                 return -48;
         return f->device->ops->lseek64(f, offset, whence);
 }
References iop_file_t::device, EBADF, EINVAL, get_file(), IOP_DT_FSEXT, NULL, and SEEK_END.
mkdir()
int mkdir (const char * name, int mode)
Definition at line 348 of file iomanX.c.
 {
         return path_common(name, mode, 4);
 }
References irx_export_table::mode, irx_export_table::name, and path_common().
mode2modex()
int mode2modex (int mode)
Definition at line 385 of file iomanX.c.
 {
         int modex = 0;
         if (FIO_SO_ISLNK(mode))
                 modex |= FIO_S_IFLNK;
         if (FIO_SO_ISREG(mode))
                 modex |= FIO_S_IFREG;
         if (FIO_SO_ISDIR(mode))
                 modex |= FIO_S_IFDIR;
         /* Convert the file access modes.  */
         if (mode & FIO_SO_IROTH)
                 modex |= FIO_S_IRUSR | FIO_S_IRGRP | FIO_S_IROTH;
         if (mode & FIO_SO_IWOTH)
                 modex |= FIO_S_IWUSR | FIO_S_IWGRP | FIO_S_IWOTH;
         if (mode & FIO_SO_IXOTH)
                 modex |= FIO_S_IXUSR | FIO_S_IXGRP | FIO_S_IXOTH;
         return modex;
 }
References FIO_S_IFDIR, FIO_S_IFLNK, FIO_S_IFREG, FIO_S_IRGRP, FIO_S_IROTH, FIO_S_IRUSR, FIO_S_IWGRP, FIO_S_IWOTH, FIO_S_IWUSR, FIO_S_IXGRP, FIO_S_IXOTH, FIO_S_IXUSR, FIO_SO_IROTH, FIO_SO_ISDIR, FIO_SO_ISLNK, FIO_SO_ISREG, FIO_SO_IWOTH, FIO_SO_IXOTH, and irx_export_table::mode.
Referenced by dread(), getstat(), and stat2statx().
modex2mode()
int modex2mode (int modex)
Definition at line 407 of file iomanX.c.
 {
         int mode = 0;
         if (FIO_S_ISLNK(modex))
                 mode |= FIO_SO_IFLNK;
         if (FIO_S_ISREG(modex))
                 mode |= FIO_SO_IFREG;
         if (FIO_S_ISDIR(modex))
                 mode |= FIO_SO_IFDIR;
         /* Convert the file access modes.  */
         if (modex & (FIO_S_IRUSR | FIO_S_IRGRP | FIO_S_IROTH))
                 mode |= FIO_SO_IROTH;
         if (modex & (FIO_S_IWUSR | FIO_S_IWGRP | FIO_S_IWOTH))
                 mode |= FIO_SO_IWOTH;
         if (modex & (FIO_S_IXUSR | FIO_S_IXGRP | FIO_S_IXOTH))
                 mode |= FIO_SO_IXOTH;
         return mode;
 }
References FIO_S_IRGRP, FIO_S_IROTH, FIO_S_IRUSR, FIO_S_ISDIR, FIO_S_ISLNK, FIO_S_ISREG, FIO_S_IWGRP, FIO_S_IWOTH, FIO_S_IWUSR, FIO_S_IXGRP, FIO_S_IXOTH, FIO_S_IXUSR, FIO_SO_IFDIR, FIO_SO_IFLNK, FIO_SO_IFREG, FIO_SO_IROTH, FIO_SO_IWOTH, FIO_SO_IXOTH, and irx_export_table::mode.
Referenced by chstat(), and statx2stat().
mount()
int mount (const char * fsname, const char * devname, int flag, void * arg, int arglen)
Definition at line 555 of file iomanX.c.
 {
         iop_file_t file;
         char *filename;
         if ((filename = find_iop_device(fsname, &file.unit, &file.device)) == (char *)-1)
                 return -ENODEV;
         /* The filesystem must support these ops.  */
         if ((file.device->type & 0xf0000000) != IOP_DT_FSEXT)
                 return -48;
         return file.device->ops->mount(&file, filename, devname, flag, arg, arglen);
 }
References arg, iop_file_t::device, ENODEV, find_iop_device(), IOP_DT_FSEXT, and iop_file_t::unit.
Referenced by bdm_try_mount(), fileXio_Mount_RPC(), and ps2netfs_op_mount().
open()
int open (const char * name, int flags, ...)
Definition at line 203 of file iomanX.c.
 {
         iop_file_t *f = get_new_file();
         char *filename;
         va_list alist;
         int res = -ENOSYS, mode;
         va_start(alist, flags);
         mode = va_arg(alist, int);
         va_end(alist);
         if (!f)
         {
                 return -EMFILE;
         }
         if ((filename = find_iop_device(name, &f->unit, &f->device)) == (char *)-1)
         {
         f->device = NULL;
                 return -ENODEV;
         }
         f->mode = flags;
         if ((res = f->device->ops->open(f, filename, flags, mode)) >= 0)
         {
                 res = (int)(f - file_table);
         }
         else
         {
         f->mode = 0;
         f->device = NULL;
         }
         return res;
 }
References iop_file_t::device, EMFILE, ENODEV, ENOSYS, file_table, find_iop_device(), get_new_file(), iop_file_t::mode, irx_export_table::mode, irx_export_table::name, NULL, and iop_file_t::unit.
path_common()
static int path_common (const char * name, int arg, int code) static
Definition at line 320 of file iomanX.c.
 {
         iop_file_t file;
         iop_device_ops_t *dops;
         char *filename;
         if ((filename = find_iop_device(name, &file.unit, &file.device)) == (char *)-1)
                 return -ENODEV;
         if (code & 0x100)
                 if ((file.device->type & 0xf0000000) != IOP_DT_FSEXT)
                         return -48;
         dops = (iop_device_ops_t *)file.device->ops;
         switch (code) {
                 case 4:         /* mkdir() */
                         return dops->mkdir(&file, filename, arg);
                 case 5:         /* rmdir() */
                         return dops->rmdir(&file, filename);
                 case 0x103:     /* chdir() */
                         return dops->chdir(&file, filename);
                 case 0x106:
                         return dops->sync(&file, filename, arg);
         }
         return -EINVAL;
 }
References arg, iop_device_ops_t::chdir, iop_file_t::device, EINVAL, ENODEV, find_iop_device(), IOP_DT_FSEXT, iop_device_ops_t::mkdir, irx_export_table::name, iop_device_ops_t::rmdir, iop_device_ops_t::sync, and iop_file_t::unit.
Referenced by chdir(), mkdir(), rmdir(), and sync().
read()
int read (int fd, void * ptr, int size)
Definition at line 263 of file iomanX.c.
 {
         iop_file_t *f = get_file(fd);
         if (f == NULL || !(f->mode & O_RDONLY))
                 return -EBADF;
         return f->device->ops->read(f, ptr, size);
 }
References iop_file_t::device, EBADF, get_file(), iop_file_t::mode, NULL, and O_RDONLY.
readlink()
int readlink (const char * name, char * buf, unsigned int buflen)
Definition at line 621 of file iomanX.c.
 {
         iop_file_t file;
         char *filename;
         if ((filename = find_iop_device(name, &file.unit, &file.device)) == (char *)-1)
                 return -ENODEV;
         /* The filesystem must support these ops.  */
         if ((file.device->type & 0xf0000000) != IOP_DT_FSEXT)
                 return -48;
         return file.device->ops->readlink(&file, filename, buf, buflen);
 }
References iop_file_t::device, ENODEV, find_iop_device(), IOP_DT_FSEXT, irx_export_table::name, and iop_file_t::unit.
Referenced by fileXioRpc_ReadLink(), and ps2netfs_op_readlink().
remove()
int remove (const char * name)
Definition at line 306 of file iomanX.c.
 {
         iop_file_t file;
         char *filename;
         if ((filename = find_iop_device(name, &file.unit, &file.device)) == (char *)-1)
                 return -ENODEV;
         return file.device->ops->remove(&file, filename);
 }
References iop_file_t::device, ENODEV, find_iop_device(), irx_export_table::name, and iop_file_t::unit.
Referenced by fileXioRpc_Remove(), hook_ioman(), and ps2netfs_op_remove().
rename()
int rename (const char * old, const char * new)
Definition at line 540 of file iomanX.c.
 {
         return link_common(old, new, 7);
 }
References link_common().
Referenced by fileXioRpc_Rename(), and ps2netfs_op_rename().
rmdir()
int rmdir (const char * name)
Definition at line 353 of file iomanX.c.
 {
         return path_common(name, 0, 5);
 }
References irx_export_table::name, and path_common().
Referenced by fileXioRpc_RmDir(), hook_ioman(), and ps2netfs_op_rmdir().
shutdown()
int shutdown (void)
Definition at line 66 of file iomanX.c.
 {
     unhook_ioman();
         return MODULE_NO_RESIDENT_END;
 }
References MODULE_NO_RESIDENT_END, and unhook_ioman().
symlink()
int symlink (const char * old, const char * new)
Definition at line 616 of file iomanX.c.
 {
         return link_common(old, new, 8);
 }
References link_common().
Referenced by fileXioRpc_SymLink(), and ps2netfs_op_symlink().
sync()
int sync (const char * dev, int flag)
Definition at line 550 of file iomanX.c.
 {
         return path_common(dev, flag, 0x106);
 }
References path_common().
Referenced by fileXioRpc_Sync(), and ps2netfs_op_sync().
umount()
int umount (const char * fsname)
Definition at line 570 of file iomanX.c.
 {
         iop_file_t file;
         char *filename;
         if ((filename = find_iop_device(fsname, &file.unit, &file.device)) == (char *)-1)
                 return -ENODEV;
         /* The filesystem must support these ops.  */
         if ((file.device->type & 0xf0000000) != IOP_DT_FSEXT)
                 return -48;
         return file.device->ops->umount(&file, filename);
 }
References iop_file_t::device, ENODEV, find_iop_device(), IOP_DT_FSEXT, and iop_file_t::unit.
Referenced by fileXioRpc_uMount(), and ps2netfs_op_umount().
unhook_ioman()
int unhook_ioman ()
Definition at line 308 of file ioman_sbv.c.
 {
         int i;
     dev_list = GetDeviceList();
         /* Remove all registered devices.  */
         for (i = 0; i < MAX_DEVICES; i++) {
                 if (dev_list[i] != NULL) {
                         dev_list[i]->ops->deinit(dev_list[i]);
                         dev_list[i] = NULL;
                 }
         }
         /* Restore ioman's library exports.  */
     ioman_exports[4] = Addr_IOMAN_open;
     ioman_exports[5] = Addr_IOMAN_close;
     ioman_exports[6] = Addr_IOMAN_read;
     ioman_exports[7] = Addr_IOMAN_write;
     ioman_exports[8] = Addr_IOMAN_lseek;
     ioman_exports[9] = Addr_IOMAN_ioctl;
     ioman_exports[10] = Addr_IOMAN_remove;
     ioman_exports[11] = Addr_IOMAN_mkdir;
     ioman_exports[12] = Addr_IOMAN_rmdir;
     ioman_exports[13] = Addr_IOMAN_dopen;
     ioman_exports[14] = Addr_IOMAN_dclose;
     ioman_exports[15] = Addr_IOMAN_dread;
     ioman_exports[16] = Addr_IOMAN_getstat;
     ioman_exports[17] = Addr_IOMAN_chstat;
     ioman_exports[18] = Addr_IOMAN_format;
     ioman_exports[20] = Addr_IOMAN_AddDrv;
     ioman_exports[21] = Addr_IOMAN_DelDrv;
     // repair all the tables that import the ioman library
     fix_imports((iop_library_t *) (((u32) ioman_exports) - 0x14));
         return 0;
 }
References Addr_IOMAN_AddDrv, Addr_IOMAN_chstat, Addr_IOMAN_close, Addr_IOMAN_dclose, Addr_IOMAN_DelDrv, Addr_IOMAN_dopen, Addr_IOMAN_dread, Addr_IOMAN_format, Addr_IOMAN_getstat, Addr_IOMAN_ioctl, Addr_IOMAN_lseek, Addr_IOMAN_mkdir, Addr_IOMAN_open, Addr_IOMAN_read, Addr_IOMAN_remove, Addr_IOMAN_rmdir, Addr_IOMAN_write, dev_list, fix_imports(), GetDeviceList(), ioman_exports, MAX_DEVICES, NULL, and iop_device_t::ops.
Referenced by shutdown().
write()
int write (int fd, void * ptr, int size)
Definition at line 273 of file iomanX.c.
 {
         iop_file_t *f = get_file(fd);
         if (f == NULL || !(f->mode & O_WRONLY))
                 return -EBADF;
         return f->device->ops->write(f, ptr, size);
 }
References iop_file_t::device, EBADF, get_file(), iop_file_t::mode, NULL, and O_WRONLY.
Variable Documentation
_exp_iomanx
struct irx_export_table _exp_iomanx extern
Referenced by _start().
dev_list
iop_device_t* dev_list[MAX_DEVICES] static
Definition at line 33 of file iomanX.c.
Referenced by _start(), AddDrv(), DelDrv(), find_iop_device(), and GetDeviceList().
file_table
iop_file_t file_table[MAX_FILES]
Definition at line 34 of file iomanX.c.
Referenced by _start(), dopen(), get_file(), get_new_file(), hook_ioman(), and open().