ps2sdk: iop/system/iomanx/src/ioman_sbv.c File Reference
ioman_sbv.c File Reference
#include <stdarg.h>
#include "types.h"
#include "defs.h"
#include "loadcore.h"
#include "iomanX.h"
#include "sysclib.h"
#include "errno.h"
Macros
#define FULL_IOMAN
#define MAX_DEVICES 32
#define MAX_FILES 32
Functions
static int smod_get_next_mod (ModuleInfo_t *cur_mod, ModuleInfo_t *next_mod)
static int smod_get_mod_by_name (const char *name, ModuleInfo_t *info)
void fix_imports (iop_library_t *lib)
int ioman_open (const char *name, u32 flags)
int ioman_mkdir (const char *name)
int ioman_format (const char *dev)
iop_file_t * get_file (int fd)
int mode2modex (int mode)
int modex2mode (int mode)
static void statx2stat (iox_stat_t *iox_stat, io_stat_t *stat)
static void stat2statx (io_stat_t *stat, iox_stat_t *iox_stat)
int ioman_dread (int fd, io_dirent_t *io_dirent)
int ioman_getstat (const char *name, io_stat_t *stat)
int ioman_chstat (const char *name, io_stat_t *stat, unsigned int mask)
int hook_ioman (void)
int unhook_ioman ()
Variables
iop_device_t ** dev_list
iop_file_t file_table [MAX_FILES]
static const char * ioman_modname = "IO/File_Manager"
static u32 * ioman_exports
static u32 Addr_IOMAN_open = 0
static u32 Addr_IOMAN_close = 0
static u32 Addr_IOMAN_read = 0
static u32 Addr_IOMAN_write = 0
static u32 Addr_IOMAN_lseek = 0
static u32 Addr_IOMAN_ioctl = 0
static u32 Addr_IOMAN_remove = 0
static u32 Addr_IOMAN_mkdir = 0
static u32 Addr_IOMAN_rmdir = 0
static u32 Addr_IOMAN_dopen = 0
static u32 Addr_IOMAN_dclose = 0
static u32 Addr_IOMAN_dread = 0
static u32 Addr_IOMAN_getstat = 0
static u32 Addr_IOMAN_chstat = 0
static u32 Addr_IOMAN_format = 0
static u32 Addr_IOMAN_AddDrv = 0
static u32 Addr_IOMAN_DelDrv = 0
Detailed Description
Advanced I/O library.
Definition in file ioman_sbv.c.
Macro Definition Documentation
FULL_IOMAN
#define FULL_IOMAN
Definition at line 28 of file ioman_sbv.c.
MAX_DEVICES
#define MAX_DEVICES 32
Definition at line 30 of file ioman_sbv.c.
MAX_FILES
#define MAX_FILES 32
Definition at line 31 of file ioman_sbv.c.
Function Documentation
fix_imports()
void fix_imports (iop_library_t * lib)
Definition at line 71 of file ioman_sbv.c.
 {
     struct irx_import_table *table;
     struct irx_import_stub *stub;
     FlushDcache();
     // go through each table that imports the library
     for(table = lib->caller; table != NULL; table = table->next)
     {
         // go through each import in the table
         for(stub = (struct irx_import_stub *) table->stubs; stub->jump != 0; stub++)
         {
             // patch the stub to jump to the address specified in the library export table for "fno"
             stub->jump = 0x08000000 | (((u32) lib->exports[stub->fno] << 4) >> 6);
         }
     }
     FlushIcache();
 }
References iop_library_t::caller, iop_library_t::exports, FlushDcache(), FlushIcache(), irx_import_stub::fno, irx_import_stub::jump, irx_import_table::next, NULL, and irx_import_table::stubs.
Referenced by hook_ioman(), and unhook_ioman().
get_file()
iop_file_t* get_file (int fd)
Definition at line 167 of file iomanX.c.
 {
         if (fd >= MAX_FILES)
                 return NULL;
         if (file_table[fd].device != NULL)
                 return &file_table[fd];
         return NULL;
 }
References file_table, MAX_FILES, and NULL.
Referenced by close(), dread(), ioctl(), ioctl2(), ioman_dread(), lseek(), lseek64(), read(), and write().
hook_ioman()
int hook_ioman (void)
Definition at line 238 of file ioman_sbv.c.
 {
         iop_library_t ioman_library = { NULL, NULL, 0x102, 0, "ioman\0\0" };
         ModuleInfo_t info;
     dev_list = GetDeviceList();
         if (smod_get_mod_by_name(ioman_modname, &info))
         {
         // steal the original IOMAN's 16 registered device entries
         memcpy(dev_list, (void *) (info.text_start + info.text_size + info.data_size + 0x10), sizeof(iop_device_t *) * 16);
         // steal the original IOMAN's 16 file descriptors
         memcpy(file_table, (void *) (info.text_start + info.text_size + info.data_size + 0x50), sizeof(iop_file_t) * 16);
         }
         else { return(-1); }
     // patch the IOMAN export library table to call iomanX functions
         if ((ioman_exports = (u32 *)QueryLibraryEntryTable(&ioman_library)) != NULL)
         {
         /* Preserve ioman's library exports.  */
         Addr_IOMAN_open = ioman_exports[4];
         Addr_IOMAN_close = ioman_exports[5];
         Addr_IOMAN_read = ioman_exports[6];
         Addr_IOMAN_write = ioman_exports[7];
         Addr_IOMAN_lseek = ioman_exports[8];
         Addr_IOMAN_ioctl = ioman_exports[9];
         Addr_IOMAN_remove = ioman_exports[10];
         Addr_IOMAN_mkdir = ioman_exports[11];
         Addr_IOMAN_rmdir = ioman_exports[12];
         Addr_IOMAN_dopen = ioman_exports[13];
         Addr_IOMAN_dclose = ioman_exports[14];
         Addr_IOMAN_dread = ioman_exports[15];
         Addr_IOMAN_getstat = ioman_exports[16];
         Addr_IOMAN_chstat = ioman_exports[17];
         Addr_IOMAN_format = ioman_exports[18];
         Addr_IOMAN_AddDrv = ioman_exports[20];
         Addr_IOMAN_DelDrv = ioman_exports[21];
 #ifdef FULL_IOMAN
                 ioman_exports[4] = (u32) ioman_open;
                 ioman_exports[5] = (u32) close;
                 ioman_exports[6] = (u32) read;
                 ioman_exports[7] = (u32) write;
                 ioman_exports[8] = (u32) lseek;
                 ioman_exports[9] = (u32) ioctl;
                 ioman_exports[10] = (u32) remove;
                 ioman_exports[11] = (u32) ioman_mkdir;
                 ioman_exports[12] = (u32) rmdir;
                 ioman_exports[13] = (u32) dopen;
                 ioman_exports[14] = (u32) close;
                 ioman_exports[15] = (u32) ioman_dread;
                 ioman_exports[16] = (u32) ioman_getstat;
                 ioman_exports[17] = (u32) ioman_chstat;
                 ioman_exports[18] = (u32) ioman_format;
                 ioman_exports[20] = (u32) AddDrv;
                 ioman_exports[21] = (u32) DelDrv;
 #else
                 ioman_exports[20] = (u32) sbv_AddDrv;
                 ioman_exports[21] = (u32) sbv_DelDrv;
 #endif
         // repair all the tables that import the ioman library
         fix_imports((iop_library_t *) (((u32) ioman_exports) - 0x14));
         }
         else { return(-2); }
         return(0);
 }
References AddDrv(), Addr_IOMAN_AddDrv, Addr_IOMAN_chstat, Addr_IOMAN_close, Addr_IOMAN_dclose, Addr_IOMAN_DelDrv, Addr_IOMAN_dopen, Addr_IOMAN_dread, Addr_IOMAN_format, Addr_IOMAN_getstat, Addr_IOMAN_ioctl, Addr_IOMAN_lseek, Addr_IOMAN_mkdir, Addr_IOMAN_open, Addr_IOMAN_read, Addr_IOMAN_remove, Addr_IOMAN_rmdir, Addr_IOMAN_write, close(), DelDrv(), dev_list, dopen(), file_table, fix_imports(), GetDeviceList(), ioctl(), ioman_chstat(), ioman_dread(), ioman_exports, ioman_format(), ioman_getstat(), ioman_mkdir(), ioman_modname, ioman_open(), lseek(), memcpy(), NULL, QueryLibraryEntryTable(), read(), remove(), rmdir(), smod_get_mod_by_name(), and write().
Referenced by _start().
ioman_chstat()
int ioman_chstat (const char * name, io_stat_t * stat, unsigned int mask)
Definition at line 229 of file ioman_sbv.c.
 {
     iox_stat_t iox_stat;
     stat2statx(stat, &iox_stat);
     return chstat(name, &iox_stat, mask);
 }
References chstat(), and stat2statx().
Referenced by hook_ioman().
ioman_dread()
int ioman_dread (int fd, io_dirent_t * io_dirent)
Definition at line 191 of file ioman_sbv.c.
 {
     iop_file_t *f = get_file(fd);
     int res;
     if (f == NULL ||  !(f->mode & 8))
             return -EBADF;
     /* If this is a new device (such as pfs:) then we need to convert the mode
        variable of the stat structure to ioman's format.  */
     if ((f->device->type & 0xf0000000) == IOP_DT_FSEXT)
     {
         iox_dirent_t iox_dirent;
         res = f->device->ops->dread(f, &iox_dirent);
         statx2stat(&iox_dirent.stat, &io_dirent->stat);
         strncpy(io_dirent->name, iox_dirent.name, sizeof(iox_dirent.name));
     }
     else
     {
         typedef int     io_dread_t(iop_file_t *, io_dirent_t *);
         io_dread_t *io_dread = (io_dread_t*) f->device->ops->dread;
         res = io_dread(f, io_dirent);
     }
     return res;
 }
References iop_file_t::device, EBADF, get_file(), io_dread(), IOP_DT_FSEXT, iop_file_t::mode, io_dirent_t::name, iox_dirent_t::name, NULL, io_dirent_t::stat, iox_dirent_t::stat, statx2stat(), and strncpy().
Referenced by hook_ioman().
ioman_format()
int ioman_format (const char * dev)
Definition at line 159 of file ioman_sbv.c.
 {
     return(format(dev, NULL, NULL, 0));
 }
References format(), and NULL.
Referenced by hook_ioman().
ioman_getstat()
int ioman_getstat (const char * name, io_stat_t * stat)
Definition at line 220 of file ioman_sbv.c.
 {
     iox_stat_t iox_stat;
     int res = getstat(name, &iox_stat);
     if (res == 0)
         statx2stat(&iox_stat, stat);
     return res;
 }
References getstat(), and statx2stat().
Referenced by hook_ioman().
ioman_mkdir()
int ioman_mkdir (const char * name)
Definition at line 153 of file ioman_sbv.c.
 {
     return(mkdir(name, 0755));
 }
References mkdir().
Referenced by hook_ioman().
ioman_open()
int ioman_open (const char * name, u32 flags)
Definition at line 148 of file ioman_sbv.c.
 {
     return(open(name, flags, 0644));
 }
References open().
Referenced by hook_ioman().
mode2modex()
int mode2modex (int mode)
Definition at line 385 of file iomanX.c.
 {
         int modex = 0;
         if (FIO_SO_ISLNK(mode))
                 modex |= FIO_S_IFLNK;
         if (FIO_SO_ISREG(mode))
                 modex |= FIO_S_IFREG;
         if (FIO_SO_ISDIR(mode))
                 modex |= FIO_S_IFDIR;
         /* Convert the file access modes.  */
         if (mode & FIO_SO_IROTH)
                 modex |= FIO_S_IRUSR | FIO_S_IRGRP | FIO_S_IROTH;
         if (mode & FIO_SO_IWOTH)
                 modex |= FIO_S_IWUSR | FIO_S_IWGRP | FIO_S_IWOTH;
         if (mode & FIO_SO_IXOTH)
                 modex |= FIO_S_IXUSR | FIO_S_IXGRP | FIO_S_IXOTH;
         return modex;
 }
References FIO_S_IFDIR, FIO_S_IFLNK, FIO_S_IFREG, FIO_S_IRGRP, FIO_S_IROTH, FIO_S_IRUSR, FIO_S_IWGRP, FIO_S_IWOTH, FIO_S_IWUSR, FIO_S_IXGRP, FIO_S_IXOTH, FIO_S_IXUSR, FIO_SO_IROTH, FIO_SO_ISDIR, FIO_SO_ISLNK, FIO_SO_ISREG, FIO_SO_IWOTH, FIO_SO_IXOTH, and irx_export_table::mode.
Referenced by dread(), getstat(), and stat2statx().
modex2mode()
int modex2mode (int mode)
Definition at line 407 of file iomanX.c.
 {
         int mode = 0;
         if (FIO_S_ISLNK(modex))
                 mode |= FIO_SO_IFLNK;
         if (FIO_S_ISREG(modex))
                 mode |= FIO_SO_IFREG;
         if (FIO_S_ISDIR(modex))
                 mode |= FIO_SO_IFDIR;
         /* Convert the file access modes.  */
         if (modex & (FIO_S_IRUSR | FIO_S_IRGRP | FIO_S_IROTH))
                 mode |= FIO_SO_IROTH;
         if (modex & (FIO_S_IWUSR | FIO_S_IWGRP | FIO_S_IWOTH))
                 mode |= FIO_SO_IWOTH;
         if (modex & (FIO_S_IXUSR | FIO_S_IXGRP | FIO_S_IXOTH))
                 mode |= FIO_SO_IXOTH;
         return mode;
 }
References FIO_S_IRGRP, FIO_S_IROTH, FIO_S_IRUSR, FIO_S_ISDIR, FIO_S_ISLNK, FIO_S_ISREG, FIO_S_IWGRP, FIO_S_IWOTH, FIO_S_IWUSR, FIO_S_IXGRP, FIO_S_IXOTH, FIO_S_IXUSR, FIO_SO_IFDIR, FIO_SO_IFLNK, FIO_SO_IFREG, FIO_SO_IROTH, FIO_SO_IWOTH, FIO_SO_IXOTH, and irx_export_table::mode.
Referenced by chstat(), and statx2stat().
smod_get_mod_by_name()
static int smod_get_mod_by_name (const char * name, ModuleInfo_t * info) static
Definition at line 56 of file ioman_sbv.c.
 {
         int len = strlen(name) + 1; /* Thanks to adresd for this fix.  */
         if (!smod_get_next_mod(NULL, info))
                 return 0;
         do {
                 if (!memcmp(info->name, name, len))
                         return info->id;
         } while (smod_get_next_mod(info, info) != 0);
         return 0;
 }
References memcmp(), NULL, smod_get_next_mod(), and strlen().
Referenced by hook_ioman(), iopmgr_get_devicelist(), iopmgr_get_iomandev(), iopmgr_get_iomanxdev(), list_devices_ioman(), and list_devices_iomanx().
smod_get_next_mod()
static int smod_get_next_mod (ModuleInfo_t * cur_mod, ModuleInfo_t * next_mod) static
Definition at line 38 of file ioman_sbv.c.
 {
         void *addr;
         /* If cur_mod is 0, return the head of the list (IOP address 0x800).  */
         if (!cur_mod) {
                 addr = GetLoadcoreInternalData()->image_info;
         } else {
                 if (!cur_mod->next)
                         return 0;
                 else
                         addr = cur_mod->next;
         }
         memcpy(next_mod, addr, sizeof(ModuleInfo_t));
         return next_mod->id;
 }
References GetLoadcoreInternalData(), ModuleInfo_t::id, lc_internals_t::image_info, memcpy(), and ModuleInfo_t::next.
Referenced by list_all_modules(), and smod_get_mod_by_name().
stat2statx()
static void stat2statx (io_stat_t * stat, iox_stat_t * iox_stat) static
Definition at line 180 of file ioman_sbv.c.
 {
     iox_stat->mode = mode2modex(stat->mode);
     iox_stat->attr = stat->attr;
     iox_stat->size = stat->size;
     memcpy(iox_stat->ctime, stat->ctime, sizeof(stat->ctime));
     memcpy(iox_stat->atime, stat->atime, sizeof(stat->atime));
     memcpy(iox_stat->mtime, stat->mtime, sizeof(stat->mtime));
     iox_stat->hisize = stat->hisize;
 }
References io_stat_t::atime, iox_stat_t::atime, io_stat_t::attr, iox_stat_t::attr, io_stat_t::ctime, iox_stat_t::ctime, io_stat_t::hisize, iox_stat_t::hisize, memcpy(), io_stat_t::mode, iox_stat_t::mode, mode2modex(), io_stat_t::mtime, iox_stat_t::mtime, io_stat_t::size, and iox_stat_t::size.
Referenced by ioman_chstat().
statx2stat()
static void statx2stat (iox_stat_t * iox_stat, io_stat_t * stat) static
Definition at line 169 of file ioman_sbv.c.
 {
     stat->mode = modex2mode(iox_stat->mode);
     stat->attr = iox_stat->attr;
     stat->size = iox_stat->size;
     memcpy(stat->ctime, iox_stat->ctime, sizeof(iox_stat->ctime));
     memcpy(stat->atime, iox_stat->atime, sizeof(iox_stat->atime));
     memcpy(stat->mtime, iox_stat->mtime, sizeof(iox_stat->mtime));
     stat->hisize = iox_stat->hisize;
 }
References io_stat_t::atime, iox_stat_t::atime, io_stat_t::attr, iox_stat_t::attr, io_stat_t::ctime, iox_stat_t::ctime, io_stat_t::hisize, iox_stat_t::hisize, memcpy(), io_stat_t::mode, iox_stat_t::mode, modex2mode(), io_stat_t::mtime, iox_stat_t::mtime, io_stat_t::size, and iox_stat_t::size.
Referenced by ioman_dread(), and ioman_getstat().
unhook_ioman()
int unhook_ioman ()
Definition at line 308 of file ioman_sbv.c.
 {
         int i;
     dev_list = GetDeviceList();
         /* Remove all registered devices.  */
         for (i = 0; i < MAX_DEVICES; i++) {
                 if (dev_list[i] != NULL) {
                         dev_list[i]->ops->deinit(dev_list[i]);
                         dev_list[i] = NULL;
                 }
         }
         /* Restore ioman's library exports.  */
     ioman_exports[4] = Addr_IOMAN_open;
     ioman_exports[5] = Addr_IOMAN_close;
     ioman_exports[6] = Addr_IOMAN_read;
     ioman_exports[7] = Addr_IOMAN_write;
     ioman_exports[8] = Addr_IOMAN_lseek;
     ioman_exports[9] = Addr_IOMAN_ioctl;
     ioman_exports[10] = Addr_IOMAN_remove;
     ioman_exports[11] = Addr_IOMAN_mkdir;
     ioman_exports[12] = Addr_IOMAN_rmdir;
     ioman_exports[13] = Addr_IOMAN_dopen;
     ioman_exports[14] = Addr_IOMAN_dclose;
     ioman_exports[15] = Addr_IOMAN_dread;
     ioman_exports[16] = Addr_IOMAN_getstat;
     ioman_exports[17] = Addr_IOMAN_chstat;
     ioman_exports[18] = Addr_IOMAN_format;
     ioman_exports[20] = Addr_IOMAN_AddDrv;
     ioman_exports[21] = Addr_IOMAN_DelDrv;
     // repair all the tables that import the ioman library
     fix_imports((iop_library_t *) (((u32) ioman_exports) - 0x14));
         return 0;
 }
References Addr_IOMAN_AddDrv, Addr_IOMAN_chstat, Addr_IOMAN_close, Addr_IOMAN_dclose, Addr_IOMAN_DelDrv, Addr_IOMAN_dopen, Addr_IOMAN_dread, Addr_IOMAN_format, Addr_IOMAN_getstat, Addr_IOMAN_ioctl, Addr_IOMAN_lseek, Addr_IOMAN_mkdir, Addr_IOMAN_open, Addr_IOMAN_read, Addr_IOMAN_remove, Addr_IOMAN_rmdir, Addr_IOMAN_write, dev_list, fix_imports(), GetDeviceList(), ioman_exports, MAX_DEVICES, NULL, and iop_device_t::ops.
Referenced by shutdown().
Variable Documentation
Addr_IOMAN_AddDrv
u32 Addr_IOMAN_AddDrv = 0 static
Definition at line 110 of file ioman_sbv.c.
Referenced by hook_ioman(), and unhook_ioman().
Addr_IOMAN_chstat
u32 Addr_IOMAN_chstat = 0 static
Definition at line 107 of file ioman_sbv.c.
Referenced by hook_ioman(), and unhook_ioman().
Addr_IOMAN_close
u32 Addr_IOMAN_close = 0 static
Definition at line 95 of file ioman_sbv.c.
Referenced by hook_ioman(), and unhook_ioman().
Addr_IOMAN_dclose
u32 Addr_IOMAN_dclose = 0 static
Definition at line 104 of file ioman_sbv.c.
Referenced by hook_ioman(), and unhook_ioman().
Addr_IOMAN_DelDrv
u32 Addr_IOMAN_DelDrv = 0 static
Definition at line 111 of file ioman_sbv.c.
Referenced by hook_ioman(), and unhook_ioman().
Addr_IOMAN_dopen
u32 Addr_IOMAN_dopen = 0 static
Definition at line 103 of file ioman_sbv.c.
Referenced by hook_ioman(), and unhook_ioman().
Addr_IOMAN_dread
u32 Addr_IOMAN_dread = 0 static
Definition at line 105 of file ioman_sbv.c.
Referenced by hook_ioman(), and unhook_ioman().
Addr_IOMAN_format
u32 Addr_IOMAN_format = 0 static
Definition at line 108 of file ioman_sbv.c.
Referenced by hook_ioman(), and unhook_ioman().
Addr_IOMAN_getstat
u32 Addr_IOMAN_getstat = 0 static
Definition at line 106 of file ioman_sbv.c.
Referenced by hook_ioman(), and unhook_ioman().
Addr_IOMAN_ioctl
u32 Addr_IOMAN_ioctl = 0 static
Definition at line 99 of file ioman_sbv.c.
Referenced by hook_ioman(), and unhook_ioman().
Addr_IOMAN_lseek
u32 Addr_IOMAN_lseek = 0 static
Definition at line 98 of file ioman_sbv.c.
Referenced by hook_ioman(), and unhook_ioman().
Addr_IOMAN_mkdir
u32 Addr_IOMAN_mkdir = 0 static
Definition at line 101 of file ioman_sbv.c.
Referenced by hook_ioman(), and unhook_ioman().
Addr_IOMAN_open
u32 Addr_IOMAN_open = 0 static
Definition at line 94 of file ioman_sbv.c.
Referenced by hook_ioman(), and unhook_ioman().
Addr_IOMAN_read
u32 Addr_IOMAN_read = 0 static
Definition at line 96 of file ioman_sbv.c.
Referenced by hook_ioman(), and unhook_ioman().
Addr_IOMAN_remove
u32 Addr_IOMAN_remove = 0 static
Definition at line 100 of file ioman_sbv.c.
Referenced by hook_ioman(), and unhook_ioman().
Addr_IOMAN_rmdir
u32 Addr_IOMAN_rmdir = 0 static
Definition at line 102 of file ioman_sbv.c.
Referenced by hook_ioman(), and unhook_ioman().
Addr_IOMAN_write
u32 Addr_IOMAN_write = 0 static
Definition at line 97 of file ioman_sbv.c.
Referenced by hook_ioman(), and unhook_ioman().
dev_list
iop_device_t** dev_list
Definition at line 33 of file ioman_sbv.c.
Referenced by hook_ioman(), and unhook_ioman().
file_table
iop_file_t file_table[MAX_FILES] extern
Definition at line 34 of file iomanX.c.
Referenced by _start(), dopen(), get_file(), get_new_file(), hook_ioman(), and open().
ioman_exports
u32* ioman_exports static
Definition at line 92 of file ioman_sbv.c.
Referenced by hook_ioman(), and unhook_ioman().
ioman_modname
const char* ioman_modname = "IO/File_Manager" static
Definition at line 36 of file ioman_sbv.c.
Referenced by hook_ioman().