ps2sdk: iop/kernel/include/ioman.h File Reference
ioman.h File Reference
#include <types.h>
#include <irx.h>
#include <io_common.h>
Data Structures
struct iop_file_t
struct iop_device_t
struct iop_device_ops_t
Macros
#define IOP_DT_CHAR 0x01
#define IOP_DT_CONS 0x02
#define IOP_DT_BLOCK 0x04
#define IOP_DT_RAW 0x08
#define IOP_DT_FS 0x10
#define ioman_IMPORTS_start DECLARE_IMPORT_TABLE(ioman, 1, 1)
#define ioman_IMPORTS_end END_IMPORT_TABLE
#define I_open DECLARE_IMPORT(4, open)
#define I_close DECLARE_IMPORT(5, close)
#define I_read DECLARE_IMPORT(6, read)
#define I_write DECLARE_IMPORT(7, write)
#define I_lseek DECLARE_IMPORT(8, lseek)
#define I_ioctl DECLARE_IMPORT(9, ioctl)
#define I_remove DECLARE_IMPORT(10, remove)
#define I_mkdir DECLARE_IMPORT(11, mkdir)
#define I_rmdir DECLARE_IMPORT(12, rmdir)
#define I_dopen DECLARE_IMPORT(13, dopen)
#define I_dclose DECLARE_IMPORT(14, dclose)
#define I_dread DECLARE_IMPORT(15, dread)
#define I_getstat DECLARE_IMPORT(16, getstat)
#define I_chstat DECLARE_IMPORT(17, chstat)
#define I_format DECLARE_IMPORT(18, format)
#define I_AddDrv DECLARE_IMPORT(20, AddDrv);
#define I_DelDrv DECLARE_IMPORT(21, DelDrv);
Functions
int open (const char *name, int mode)
int close (int fd)
int read (int fd, void *ptr, size_t size)
int write (int fd, void *ptr, size_t size)
int lseek (int fd, int pos, int mode)
int ioctl (int fd, int command, void *arg)
int remove (const char *name)
int mkdir (const char *path)
int rmdir (const char *path)
int dopen (const char *path, int mode)
int dclose (int fd)
int dread (int fd, io_dirent_t *buf)
int getstat (const char *name, io_stat_t *stat)
int chstat (const char *name, io_stat_t *stat, unsigned int statmask)
int format (const char *dev)
int AddDrv (iop_device_t *device)
int DelDrv (const char *name)
Detailed Description
IOMAN definitions and imports.
Definition in file ioman.h.
Macro Definition Documentation
I_AddDrv
#define I_AddDrv DECLARE_IMPORT(20, AddDrv);
Definition at line 110 of file ioman.h.
I_chstat
#define I_chstat DECLARE_IMPORT(17, chstat)
Definition at line 108 of file ioman.h.
I_close
#define I_close DECLARE_IMPORT(5, close)
Definition at line 96 of file ioman.h.
I_dclose
#define I_dclose DECLARE_IMPORT(14, dclose)
Definition at line 105 of file ioman.h.
I_DelDrv
#define I_DelDrv DECLARE_IMPORT(21, DelDrv);
Definition at line 111 of file ioman.h.
I_dopen
#define I_dopen DECLARE_IMPORT(13, dopen)
Definition at line 104 of file ioman.h.
I_dread
#define I_dread DECLARE_IMPORT(15, dread)
Definition at line 106 of file ioman.h.
I_format
#define I_format DECLARE_IMPORT(18, format)
Definition at line 109 of file ioman.h.
I_getstat
#define I_getstat DECLARE_IMPORT(16, getstat)
Definition at line 107 of file ioman.h.
I_ioctl
#define I_ioctl DECLARE_IMPORT(9, ioctl)
Definition at line 100 of file ioman.h.
I_lseek
#define I_lseek DECLARE_IMPORT(8, lseek)
Definition at line 99 of file ioman.h.
I_mkdir
#define I_mkdir DECLARE_IMPORT(11, mkdir)
Definition at line 102 of file ioman.h.
I_open
#define I_open DECLARE_IMPORT(4, open)
Definition at line 95 of file ioman.h.
I_read
#define I_read DECLARE_IMPORT(6, read)
Definition at line 97 of file ioman.h.
I_remove
#define I_remove DECLARE_IMPORT(10, remove)
Definition at line 101 of file ioman.h.
I_rmdir
#define I_rmdir DECLARE_IMPORT(12, rmdir)
Definition at line 103 of file ioman.h.
I_write
#define I_write DECLARE_IMPORT(7, write)
Definition at line 98 of file ioman.h.
ioman_IMPORTS_end
#define ioman_IMPORTS_end END_IMPORT_TABLE
Definition at line 93 of file ioman.h.
ioman_IMPORTS_start
#define ioman_IMPORTS_start DECLARE_IMPORT_TABLE(ioman, 1, 1)
Definition at line 92 of file ioman.h.
IOP_DT_BLOCK
#define IOP_DT_BLOCK 0x04
Definition at line 44 of file ioman.h.
IOP_DT_CHAR
#define IOP_DT_CHAR 0x01
Definition at line 42 of file ioman.h.
IOP_DT_CONS
#define IOP_DT_CONS 0x02
Definition at line 43 of file ioman.h.
IOP_DT_FS
#define IOP_DT_FS 0x10
Definition at line 46 of file ioman.h.
IOP_DT_RAW
#define IOP_DT_RAW 0x08
Definition at line 45 of file ioman.h.
Function Documentation
AddDrv()
int AddDrv (iop_device_t * device)
Definition at line 72 of file iomanX.c.
 {
         int i, res = -1;
     int oldIntr;
     CpuSuspendIntr(&oldIntr);
         for (i = 0; i < MAX_DEVICES; i++)
         {
                 if (dev_list[i] == NULL)
                         break;
         }
         if (i >= MAX_DEVICES)
         {
             CpuResumeIntr(oldIntr);
                 return res;
         }
         dev_list[i] = device;
     CpuResumeIntr(oldIntr);
     FlushIcache();
         if ((res = device->ops->init(device)) < 0)
         {
                 dev_list[i] = NULL;
                 return(-1);
         }
         return(0);
 }
References CpuResumeIntr(), CpuSuspendIntr(), dev_list, FlushIcache(), MAX_DEVICES, NULL, and iop_device_t::ops.
Referenced by _start(), hook_ioman(), init_devfs(), init_fio(), InitFS(), mcman_initdev(), sbus_tty_init(), and smb_initdev().
chstat()
int chstat (const char * name, io_stat_t * stat, unsigned int statmask)
Referenced by fileXio_chstat_RPC(), fileXio_CopyFile_RPC(), and ioman_chstat().
close()
int close (int fd)
Definition at line 239 of file iomanX.c.
 {
         iop_file_t *f;
         int res;
         if ((f = get_file(fd)) == NULL)
         {
                 return -EBADF;
         }
         if (f->mode & 8)
         {       /* Directory.  */
                 res = f->device->ops->dclose(f);
         }
         else
         {
                 res = f->device->ops->close(f);
         }
         f->mode = 0;
         f->device = NULL;
         return res;
 }
References iop_file_t::device, EBADF, get_file(), iop_file_t::mode, and NULL.
Referenced by _start(), fd_close(), fileXio_CopyFile_RPC(), fileXio_GetDir_RPC(), fileXioRpc_Close(), hook_ioman(), pfsFioFormat(), pfsFioMount(), pfsFioUmount(), ps2netfs_op_close(), sbus_tty_init(), and sndStreamClose().
dclose()
int dclose (int fd)
Referenced by fileXioRpc_Dclose(), and ps2netfs_op_dclose().
DelDrv()
int DelDrv (const char * name)
Definition at line 105 of file iomanX.c.
 {
         int i;
         for (i = 0; i < MAX_DEVICES; i++) {
                 if (dev_list[i] != NULL && !strcmp(name, dev_list[i]->name)) {
                         dev_list[i]->ops->deinit(dev_list[i]);
                         dev_list[i] = NULL;
                         return 0;
                 }
         }
         return -1;
 }
References dev_list, MAX_DEVICES, irx_export_table::name, NULL, iop_device_t::ops, and strcmp().
Referenced by _start(), hook_ioman(), init_devfs(), InitFS(), mcman_initdev(), sbus_tty_init(), and smb_initdev().
dopen()
int dopen (const char * path, int mode)
Referenced by fileXio_GetDir_RPC(), fileXioRpc_Dopen(), hook_ioman(), and ps2netfs_op_dopen().
dread()
int dread (int fd, io_dirent_t * buf)
Referenced by fileXio_dread_RPC(), fileXio_GetDir_RPC(), and ps2netfs_op_dread().
format()
int format (const char * dev)
Referenced by _kPrintf(), _start(), apaGetFormat(), fileXioRpc_Format(), ioman_format(), ps2netfs_op_format(), and vxprintf().
getstat()
int getstat (const char * name, io_stat_t * stat)
Referenced by fileXio_getstat_RPC(), and ioman_getstat().
ioctl()
int ioctl (int fd, int command, void * arg)
Definition at line 296 of file iomanX.c.
 {
         iop_file_t *f = get_file(fd);
         if (f == NULL)
                 return -EBADF;
         return f->device->ops->ioctl(f, cmd, arg);
 }
References arg, iop_file_t::device, EBADF, get_file(), and NULL.
Referenced by fileXioRpc_Ioctl(), hook_ioman(), and ps2netfs_op_ioctl().
lseek()
int lseek (int fd, int pos, int mode)
Definition at line 283 of file iomanX.c.
 {
         iop_file_t *f = get_file(fd);
         if (f == NULL)
                 return -EBADF;
         if (whence < SEEK_SET || whence > SEEK_END)
                 return -EINVAL;
         return f->device->ops->lseek(f, offset, whence);
 }
References iop_file_t::device, EBADF, EINVAL, get_file(), NULL, and SEEK_END.
Referenced by fd_lseek(), fileXio_CopyFile_RPC(), fileXioRpc_Lseek(), hook_ioman(), ps2netfs_op_lseek(), and sndStreamSetPosition().
mkdir()
int mkdir (const char * path)
Referenced by fileXioRpc_MkDir(), ioman_mkdir(), and ps2netfs_op_mkdir().
open()
int open (const char * name, int mode)
Referenced by _start(), fd_open(), fileXio_CopyFile_RPC(), fileXioRpc_Open(), ioman_open(), pfsFioFormat(), pfsFioMount(), ps2netfs_op_open(), sbus_tty_init(), and sndStreamOpen().
read()
int read (int fd, void * ptr, size_t size)
Referenced by fd_read(), fileXio_CopyFile_RPC(), fileXio_Read_RPC(), fillbuf(), fio_read(), hook_ioman(), and ps2netfs_op_read().
remove()
int remove (const char * name)
Definition at line 306 of file iomanX.c.
 {
         iop_file_t file;
         char *filename;
         if ((filename = find_iop_device(name, &file.unit, &file.device)) == (char *)-1)
                 return -ENODEV;
         return file.device->ops->remove(&file, filename);
 }
References iop_file_t::device, ENODEV, find_iop_device(), irx_export_table::name, and iop_file_t::unit.
Referenced by fileXioRpc_Remove(), hook_ioman(), and ps2netfs_op_remove().
rmdir()
int rmdir (const char * path)
Definition at line 353 of file iomanX.c.
 {
         return path_common(name, 0, 5);
 }
References irx_export_table::name, and path_common().
Referenced by fileXioRpc_RmDir(), hook_ioman(), and ps2netfs_op_rmdir().
write()
int write (int fd, void * ptr, size_t size)
Referenced by fd_write(), fileXio_CopyFile_RPC(), fileXio_Write_RPC(), hook_ioman(), ps2netfs_op_write(), and scsi_cmd_rw_sector().