ps2sdk: iop/debug/iop_sbusdbg/include/iop_sbusdbg.h File Reference
iop_sbusdbg.h File Reference
#include <types.h>
#include <ps2_debug.h>
Functions
int iop_dbg_install (void)
int iop_dbg_remove (void)
u32 iop_dbg_get_dcic (void)
u32 iop_dbg_get_bpc (void)
u32 iop_dbg_get_bpcm (void)
u32 iop_dbg_get_bda (void)
u32 iop_dbg_get_bdam (void)
void iop_dbg_set_dcic (u32 v)
void iop_dbg_set_bpc (u32 v)
void iop_dbg_set_bpcm (u32 v)
void iop_dbg_set_bda (u32 v)
void iop_dbg_set_bdam (u32 v)
void iop_dbg_set_bpr (u32 addr, u32 mask, u32 user_mask)
void iop_dbg_set_bpw (u32 addr, u32 mask, u32 user_mask)
void iop_dbg_set_bpx (u32 addr, u32 mask, u32 user_mask)
void iop_dbg_clear (void)
void iop_dbg_clr_bpda (void)
void iop_dbg_clr_bpx (void)
void tty_puts (const char *str)
void signal_iop_exception (IOP_RegFrame *frame)
Detailed Description
IOP SBUS debug library.
Definition in file iop_sbusdbg.h.
Function Documentation
iop_dbg_clear()
void iop_dbg_clear (void)
iop_dbg_clr_bpda()
void iop_dbg_clr_bpda (void)
Definition at line 88 of file iop_debug.c.
 {
     u32 dcic = iop_dbg_get_dcic();
     dcic &= ~(IOP_DCIC_DW | IOP_DCIC_DR | IOP_DCIC_DAE);
     if(!(dcic & IOP_DCIC_PCE)) { dcic = 0; }
     iop_dbg_set_dcic(dcic);
 }
References iop_dbg_get_dcic(), iop_dbg_set_dcic(), IOP_DCIC_DAE, IOP_DCIC_DR, IOP_DCIC_DW, and IOP_DCIC_PCE.
iop_dbg_clr_bpx()
void iop_dbg_clr_bpx (void)
Definition at line 96 of file iop_debug.c.
 {
     u32 dcic = iop_dbg_get_dcic();
     dcic &= ~(IOP_DCIC_PCE);
     if(!(dcic & IOP_DCIC_DAE)) { dcic = 0; }
     iop_dbg_set_dcic(dcic);
 }
References iop_dbg_get_dcic(), iop_dbg_set_dcic(), IOP_DCIC_DAE, and IOP_DCIC_PCE.
iop_dbg_get_bda()
u32 iop_dbg_get_bda (void)
iop_dbg_get_bdam()
u32 iop_dbg_get_bdam (void)
iop_dbg_get_bpc()
u32 iop_dbg_get_bpc (void)
iop_dbg_get_bpcm()
u32 iop_dbg_get_bpcm (void)
iop_dbg_get_dcic()
u32 iop_dbg_get_dcic (void)
Referenced by iop_dbg_clr_bpda(), and iop_dbg_clr_bpx().
iop_dbg_install()
int iop_dbg_install (void)
Definition at line 117 of file iop_debug.c.
 {
     int i;
     // if already installed, return with an error.
     if(_is_iop_dbg_installed) { return(-1); }
     // initialize our exception handler pointers.
     for(i = 0; i < 16; i++)
     {
         iop_exception_handlers[i] = NULL;
     }
     // todo: preserve original exception handlers here!
     // This will require using "EXCEPMAN" export 3..
     // register our "default" exception handler.
     if(RegisterDefaultExceptionHandler((exception_handler_t) _iop_ex_def_handler) < 0)
     {
         orig_iop_def_ex_handler = NULL;
         return(-2);
     }
     // register our "BREAK" instruction exception handler.
     if(RegisterPriorityExceptionHandler(IOP_EXCEPTION_BP, 0, (exception_handler_t) _iop_ex_break_handler) < 0)
     {
         RegisterDefaultExceptionHandler((exception_handler_t) orig_iop_def_ex_handler);
         orig_iop_def_ex_handler = NULL;
         orig_iop_break_ex_handler = NULL;
         return(-3);
     }
     // register our "Hardware DeBug"(aka "Hardware BreakPoint") exception handler.
     if(RegisterPriorityExceptionHandler(IOP_EXCEPTION_HDB, 0, (exception_handler_t) _iop_ex_dbg_handler) < 0)
     {
         RegisterDefaultExceptionHandler((exception_handler_t) orig_iop_def_ex_handler);
         orig_iop_def_ex_handler = NULL;
         RegisterPriorityExceptionHandler(IOP_EXCEPTION_BP, 0, (exception_handler_t) orig_iop_break_ex_handler);
         orig_iop_break_ex_handler = NULL;
         orig_iop_dbg_ex_handler = NULL;
         return(-4);
     }
     _is_iop_dbg_installed = 1;
     return(0);
 }
References _iop_ex_break_handler(), _iop_ex_dbg_handler(), _iop_ex_def_handler(), _is_iop_dbg_installed, IOP_EXCEPTION_BP, iop_exception_handlers, IOP_EXCEPTION_HDB, NULL, orig_iop_break_ex_handler, orig_iop_dbg_ex_handler, orig_iop_def_ex_handler, RegisterDefaultExceptionHandler(), and RegisterPriorityExceptionHandler().
Referenced by _start().
iop_dbg_remove()
int iop_dbg_remove (void)
Definition at line 166 of file iop_debug.c.
 {
     // if not installed, return with an error.
     if(!_is_iop_dbg_installed) { return(-1); }
     if(orig_iop_def_ex_handler)
     {
         RegisterDefaultExceptionHandler((exception_handler_t) orig_iop_def_ex_handler);
         orig_iop_def_ex_handler = NULL;
     }
     if(orig_iop_break_ex_handler)
     {
         RegisterPriorityExceptionHandler(IOP_EXCEPTION_BP, 0, (exception_handler_t) orig_iop_break_ex_handler);
         orig_iop_break_ex_handler = NULL;
     }
     if(orig_iop_dbg_ex_handler)
     {
         RegisterPriorityExceptionHandler(IOP_EXCEPTION_HDB, 0, (exception_handler_t) orig_iop_dbg_ex_handler);
         orig_iop_dbg_ex_handler = NULL;
     }
     _is_iop_dbg_installed = 0;
     return(0);
 }
References _is_iop_dbg_installed, IOP_EXCEPTION_BP, IOP_EXCEPTION_HDB, NULL, orig_iop_break_ex_handler, orig_iop_dbg_ex_handler, orig_iop_def_ex_handler, RegisterDefaultExceptionHandler(), and RegisterPriorityExceptionHandler().
Referenced by _start(), and _stop().
iop_dbg_set_bda()
void iop_dbg_set_bda (u32 v)
Referenced by iop_dbg_clr_bps().
iop_dbg_set_bdam()
void iop_dbg_set_bdam (u32 v)
Referenced by iop_dbg_clr_bps().
iop_dbg_set_bpc()
void iop_dbg_set_bpc (u32 v)
Referenced by iop_dbg_clr_bps().
iop_dbg_set_bpcm()
void iop_dbg_set_bpcm (u32 v)
Referenced by iop_dbg_clr_bps().
iop_dbg_set_bpr()
void iop_dbg_set_bpr (u32 addr, u32 mask, u32 user_mask)
Definition at line 80 of file iop_debug.c.
 { _iop_dbg_set_bpda(addr, mask, IOP_DCIC_DR | user_mask); }
References _iop_dbg_set_bpda(), and IOP_DCIC_DR.
iop_dbg_set_bpw()
void iop_dbg_set_bpw (u32 addr, u32 mask, u32 user_mask)
Definition at line 83 of file iop_debug.c.
 { _iop_dbg_set_bpda(addr, mask, IOP_DCIC_DW | user_mask); }
References _iop_dbg_set_bpda(), and IOP_DCIC_DW.
iop_dbg_set_bpx()
void iop_dbg_set_bpx (u32 addr, u32 mask, u32 user_mask)
Definition at line 86 of file iop_debug.c.
 { _iop_dbg_set_bpx(addr, mask, user_mask); }
References _iop_dbg_set_bpx().
iop_dbg_set_dcic()
void iop_dbg_set_dcic (u32 v)
Referenced by iop_dbg_clr_bpda(), iop_dbg_clr_bps(), and iop_dbg_clr_bpx().
signal_iop_exception()
void signal_iop_exception (IOP_RegFrame * frame)
Definition at line 39 of file sbus_dbg.c.
 {
     SIF2_send_cmd(SIF2_CMD_DBG_EXC, (void *) frame, sizeof(IOP_RegFrame));
 }
References SIF2_CMD_DBG_EXC.
tty_puts()
void tty_puts (const char * str)