ps2sdk: iop/debug/iopdebug/src/iop_debug.c File Reference
iop_debug.c File Reference
#include <tamtypes.h>
#include <excepman.h>
#include <iop_cop0_defs.h>
#include <ps2_debug.h>
#include "iopdebug.h"
#include "iopdebug_priv.h"
#include "iopdebug_defs.h"
Functions
IOP_ExceptionHandler * iop_dbg_get_handler (int cause)
IOP_ExceptionHandler * iop_dbg_set_handler (int cause, IOP_ExceptionHandler *handler)
void iop_exception_dispatcher (IOP_RegFrame *frame)
void _iop_dbg_set_bpda (u32 addr, u32 mask, u32 user_mask)
void _iop_dbg_set_bpx (u32 addr, u32 mask, u32 user_mask)
void iop_dbg_set_bpr (u32 addr, u32 mask, u32 user_mask)
void iop_dbg_set_bpw (u32 addr, u32 mask, u32 user_mask)
void iop_dbg_set_bpx (u32 addr, u32 mask, u32 user_mask)
void iop_dbg_clr_bpda (void)
void iop_dbg_clr_bpx (void)
void iop_dbg_clr_bps (void)
void _iop_ex_def_handler (void)
void _iop_ex_dbg_handler (void)
void _iop_ex_break_handler (void)
int iop_dbg_install (void)
int iop_dbg_remove (void)
void iop_dbg_get_reg_frames (IOP_RegFrame **def_frame_ptr, IOP_RegFrame **dbg_frame_ptr)
Variables
u32 _iop_ex_def_stack [_EX_DEF_STACK_SIZE/4]
u32 _iop_ex_dbg_stack [_EX_DBG_STACK_SIZE/4]
IOP_RegFrame _iop_ex_def_frame
IOP_RegFrame _iop_ex_dbg_frame
static int _is_iop_dbg_installed = 0
static void * orig_iop_def_ex_handler = NULL
static void * orig_iop_break_ex_handler = NULL
static void * orig_iop_dbg_ex_handler = NULL
static IOP_ExceptionHandler * iop_exception_handlers [16]
Detailed Description
IOPDEBUG - IOP debugging library. high-level IOP debugging library code.
Definition in file iop_debug.c.
Function Documentation
_iop_dbg_set_bpda()
void _iop_dbg_set_bpda (u32 addr, u32 mask, u32 user_mask)
Referenced by iop_dbg_set_bpr(), and iop_dbg_set_bpw().
_iop_dbg_set_bpx()
void _iop_dbg_set_bpx (u32 addr, u32 mask, u32 user_mask)
Referenced by iop_dbg_set_bpx().
_iop_ex_break_handler()
void _iop_ex_break_handler (void)
Referenced by iop_dbg_install().
_iop_ex_dbg_handler()
void _iop_ex_dbg_handler (void)
Referenced by iop_dbg_install().
_iop_ex_def_handler()
void _iop_ex_def_handler (void)
Referenced by iop_dbg_install().
iop_dbg_clr_bpda()
void iop_dbg_clr_bpda (void)
Definition at line 88 of file iop_debug.c.
 {
     u32 dcic = iop_dbg_get_dcic();
     dcic &= ~(IOP_DCIC_DW | IOP_DCIC_DR | IOP_DCIC_DAE);
     if(!(dcic & IOP_DCIC_PCE)) { dcic = 0; }
     iop_dbg_set_dcic(dcic);
 }
References iop_dbg_get_dcic(), iop_dbg_set_dcic(), IOP_DCIC_DAE, IOP_DCIC_DR, IOP_DCIC_DW, and IOP_DCIC_PCE.
iop_dbg_clr_bps()
void iop_dbg_clr_bps (void)
Definition at line 104 of file iop_debug.c.
 {
     iop_dbg_set_dcic(0);
     iop_dbg_set_bda(0);
     iop_dbg_set_bdam(0);
     iop_dbg_set_bpc(0);
     iop_dbg_set_bpcm(0);
 }
References iop_dbg_set_bda(), iop_dbg_set_bdam(), iop_dbg_set_bpc(), iop_dbg_set_bpcm(), and iop_dbg_set_dcic().
iop_dbg_clr_bpx()
void iop_dbg_clr_bpx (void)
Definition at line 96 of file iop_debug.c.
 {
     u32 dcic = iop_dbg_get_dcic();
     dcic &= ~(IOP_DCIC_PCE);
     if(!(dcic & IOP_DCIC_DAE)) { dcic = 0; }
     iop_dbg_set_dcic(dcic);
 }
References iop_dbg_get_dcic(), iop_dbg_set_dcic(), IOP_DCIC_DAE, and IOP_DCIC_PCE.
iop_dbg_get_handler()
IOP_ExceptionHandler* iop_dbg_get_handler (int cause)
Definition at line 40 of file iop_debug.c.
 {
     if((cause < 0) || (cause > 15)) { return(NULL); }
     return(iop_exception_handlers[cause]);
 }
References iop_exception_handlers, and NULL.
iop_dbg_get_reg_frames()
void iop_dbg_get_reg_frames (IOP_RegFrame ** def_frame_ptr, IOP_RegFrame ** dbg_frame_ptr)
Definition at line 193 of file iop_debug.c.
 {
     if(def_frame_ptr) { *def_frame_ptr = &_iop_ex_def_frame; }
     if(dbg_frame_ptr) { *dbg_frame_ptr = &_iop_ex_dbg_frame; }
 }
References _iop_ex_dbg_frame, and _iop_ex_def_frame.
Referenced by SBUS_dbg_init().
iop_dbg_install()
int iop_dbg_install (void)
Definition at line 117 of file iop_debug.c.
 {
     int i;
     // if already installed, return with an error.
     if(_is_iop_dbg_installed) { return(-1); }
     // initialize our exception handler pointers.
     for(i = 0; i < 16; i++)
     {
         iop_exception_handlers[i] = NULL;
     }
     // todo: preserve original exception handlers here!
     // This will require using "EXCEPMAN" export 3..
     // register our "default" exception handler.
     if(RegisterDefaultExceptionHandler((exception_handler_t) _iop_ex_def_handler) < 0)
     {
         orig_iop_def_ex_handler = NULL;
         return(-2);
     }
     // register our "BREAK" instruction exception handler.
     if(RegisterPriorityExceptionHandler(IOP_EXCEPTION_BP, 0, (exception_handler_t) _iop_ex_break_handler) < 0)
     {
         RegisterDefaultExceptionHandler((exception_handler_t) orig_iop_def_ex_handler);
         orig_iop_def_ex_handler = NULL;
         orig_iop_break_ex_handler = NULL;
         return(-3);
     }
     // register our "Hardware DeBug"(aka "Hardware BreakPoint") exception handler.
     if(RegisterPriorityExceptionHandler(IOP_EXCEPTION_HDB, 0, (exception_handler_t) _iop_ex_dbg_handler) < 0)
     {
         RegisterDefaultExceptionHandler((exception_handler_t) orig_iop_def_ex_handler);
         orig_iop_def_ex_handler = NULL;
         RegisterPriorityExceptionHandler(IOP_EXCEPTION_BP, 0, (exception_handler_t) orig_iop_break_ex_handler);
         orig_iop_break_ex_handler = NULL;
         orig_iop_dbg_ex_handler = NULL;
         return(-4);
     }
     _is_iop_dbg_installed = 1;
     return(0);
 }
References _iop_ex_break_handler(), _iop_ex_dbg_handler(), _iop_ex_def_handler(), _is_iop_dbg_installed, IOP_EXCEPTION_BP, iop_exception_handlers, IOP_EXCEPTION_HDB, NULL, orig_iop_break_ex_handler, orig_iop_dbg_ex_handler, orig_iop_def_ex_handler, RegisterDefaultExceptionHandler(), and RegisterPriorityExceptionHandler().
Referenced by _start().
iop_dbg_remove()
int iop_dbg_remove (void)
Definition at line 166 of file iop_debug.c.
 {
     // if not installed, return with an error.
     if(!_is_iop_dbg_installed) { return(-1); }
     if(orig_iop_def_ex_handler)
     {
         RegisterDefaultExceptionHandler((exception_handler_t) orig_iop_def_ex_handler);
         orig_iop_def_ex_handler = NULL;
     }
     if(orig_iop_break_ex_handler)
     {
         RegisterPriorityExceptionHandler(IOP_EXCEPTION_BP, 0, (exception_handler_t) orig_iop_break_ex_handler);
         orig_iop_break_ex_handler = NULL;
     }
     if(orig_iop_dbg_ex_handler)
     {
         RegisterPriorityExceptionHandler(IOP_EXCEPTION_HDB, 0, (exception_handler_t) orig_iop_dbg_ex_handler);
         orig_iop_dbg_ex_handler = NULL;
     }
     _is_iop_dbg_installed = 0;
     return(0);
 }
References _is_iop_dbg_installed, IOP_EXCEPTION_BP, IOP_EXCEPTION_HDB, NULL, orig_iop_break_ex_handler, orig_iop_dbg_ex_handler, orig_iop_def_ex_handler, RegisterDefaultExceptionHandler(), and RegisterPriorityExceptionHandler().
Referenced by _start(), and _stop().
iop_dbg_set_bpr()
void iop_dbg_set_bpr (u32 addr, u32 mask, u32 user_mask)
Definition at line 80 of file iop_debug.c.
 { _iop_dbg_set_bpda(addr, mask, IOP_DCIC_DR | user_mask); }
References _iop_dbg_set_bpda(), and IOP_DCIC_DR.
iop_dbg_set_bpw()
void iop_dbg_set_bpw (u32 addr, u32 mask, u32 user_mask)
Definition at line 83 of file iop_debug.c.
 { _iop_dbg_set_bpda(addr, mask, IOP_DCIC_DW | user_mask); }
References _iop_dbg_set_bpda(), and IOP_DCIC_DW.
iop_dbg_set_bpx()
void iop_dbg_set_bpx (u32 addr, u32 mask, u32 user_mask)
Definition at line 86 of file iop_debug.c.
 { _iop_dbg_set_bpx(addr, mask, user_mask); }
References _iop_dbg_set_bpx().
iop_dbg_set_handler()
IOP_ExceptionHandler* iop_dbg_set_handler (int cause, IOP_ExceptionHandler * handler)
Definition at line 47 of file iop_debug.c.
 {
     IOP_ExceptionHandler *old_handler;
     u32 old_state;
     if((cause < 0) || (cause > 15)) { return(NULL); }
     EnterCritical(&old_state);
     old_handler = iop_exception_handlers[cause];
     iop_exception_handlers[cause] = handler;
     ExitCritical(old_state);
     return(old_handler);
 }
References EnterCritical(), ExitCritical(), handler, iop_exception_handlers, and NULL.
Referenced by _start().
iop_exception_dispatcher()
void iop_exception_dispatcher (IOP_RegFrame * frame)
Definition at line 65 of file iop_debug.c.
 {
     int excode = M_IOP_GET_CAUSE_EXCODE(frame->cause);
     IOP_ExceptionHandler *handler = iop_exception_handlers[excode];
     if(handler)
     {
         handler(frame);
     }
 }
References IOP_RegFrame::cause, handler, iop_exception_handlers, and M_IOP_GET_CAUSE_EXCODE.
Variable Documentation
_iop_ex_dbg_frame
IOP_RegFrame _iop_ex_dbg_frame
Definition at line 30 of file iop_debug.c.
Referenced by iop_dbg_get_reg_frames().
_iop_ex_dbg_stack
u32 _iop_ex_dbg_stack[_EX_DBG_STACK_SIZE/4]
Definition at line 27 of file iop_debug.c.
_iop_ex_def_frame
IOP_RegFrame _iop_ex_def_frame
Definition at line 29 of file iop_debug.c.
Referenced by iop_dbg_get_reg_frames().
_iop_ex_def_stack
u32 _iop_ex_def_stack[_EX_DEF_STACK_SIZE/4]
Definition at line 26 of file iop_debug.c.
_is_iop_dbg_installed
int _is_iop_dbg_installed = 0 static
Definition at line 32 of file iop_debug.c.
Referenced by iop_dbg_install(), and iop_dbg_remove().
iop_exception_handlers
IOP_ExceptionHandler* iop_exception_handlers[16] static
Definition at line 38 of file iop_debug.c.
Referenced by iop_dbg_get_handler(), iop_dbg_install(), iop_dbg_set_handler(), and iop_exception_dispatcher().
orig_iop_break_ex_handler
void* orig_iop_break_ex_handler = NULL static
Definition at line 35 of file iop_debug.c.
Referenced by iop_dbg_install(), and iop_dbg_remove().
orig_iop_dbg_ex_handler
void* orig_iop_dbg_ex_handler = NULL static
Definition at line 36 of file iop_debug.c.
Referenced by iop_dbg_install(), and iop_dbg_remove().
orig_iop_def_ex_handler
void* orig_iop_def_ex_handler = NULL static
Definition at line 34 of file iop_debug.c.
Referenced by iop_dbg_install(), and iop_dbg_remove().