ps2sdk: iop/debug/iopdebug/include/iopdebug.h File Reference
iopdebug.h File Reference
#include <types.h>
#include <irx.h>
#include <iop_cop0_defs.h>
#include <ps2_debug.h>
Macros
#define iopdebug_IMPORTS_start DECLARE_IMPORT_TABLE(iopdebug, 1, 1)
#define iopdebug_IMPORTS_end END_IMPORT_TABLE
#define I_iop_dbg_install DECLARE_IMPORT(5, iop_dbg_install)
#define I_iop_dbg_remove DECLARE_IMPORT(6, iop_dbg_remove)
#define I_iop_dbg_get_handler DECLARE_IMPORT(7, iop_dbg_get_handler)
#define I_iop_dbg_set_handler DECLARE_IMPORT(8, iop_dbg_set_handler)
#define I_iop_dbg_get_reg_frames DECLARE_IMPORT(9, iop_dbg_get_reg_frames)
#define I_iop_dbg_get_dcic DECLARE_IMPORT(10, iop_dbg_get_dcic)
#define I_iop_dbg_set_dcic DECLARE_IMPORT(11, iop_dbg_set_dcic)
#define I_iop_dbg_get_bpc DECLARE_IMPORT(12, iop_dbg_get_bpc)
#define I_iop_dbg_set_bpc DECLARE_IMPORT(13, iop_dbg_set_bpc)
#define I_iop_dbg_get_bpcm DECLARE_IMPORT(14, iop_dbg_get_bpcm)
#define I_iop_dbg_set_bpcm DECLARE_IMPORT(15, iop_dbg_set_bpcm)
#define I_iop_dbg_bda DECLARE_IMPORT(16, iop_dbg_bda)
#define I_iop_dbg_set_bda DECLARE_IMPORT(17, iop_dbg_set_bda)
#define I_iop_dbg_bdam DECLARE_IMPORT(18, iop_dbg_bdam)
#define I_iop_dbg_set_bdam DECLARE_IMPORT(19, iop_dbg_bdam)
#define I_iop_dbg_set_bpr DECLARE_IMPORT(20, iop_dbg_set_bpr)
#define I_iop_dbg_set_bpw DECLARE_IMPORT(21, iop_dbg_set_bpw)
#define I_iop_dbg_set_bpx DECLARE_IMPORT(22, iop_dbg_bpx)
#define I_iop_dbg_clr_bps DECLARE_IMPORT(23, iop_dbg_clr_bps)
#define I_iop_dbg_clr_bpda DECLARE_IMPORT(24, iop_dbg_clr_bpda)
#define I_iop_dbg_clr_bpx DECLARE_IMPORT(25, iop_dbg_clr_bpx)
Typedefs
typedef int() IOP_ExceptionHandler(struct st_IOP_RegFrame *)
Functions
int iop_dbg_install (void)
int iop_dbg_remove (void)
IOP_ExceptionHandler * iop_dbg_get_handler (int cause)
IOP_ExceptionHandler * iop_dbg_set_handler (int cause, IOP_ExceptionHandler *handler)
void iop_dbg_get_reg_frames (IOP_RegFrame **def_frame_ptr, IOP_RegFrame **dbg_frame_ptr)
u32 iop_dbg_get_dcic (void)
void iop_dbg_set_dcic (u32 v)
u32 iop_dbg_get_bpc (void)
void iop_dbg_set_bpc (u32 v)
u32 iop_dbg_get_bpcm (void)
void iop_dbg_set_bpcm (u32 v)
u32 iop_dbg_get_bda (void)
void iop_dbg_set_bda (u32 v)
u32 iop_dbg_get_bdam (void)
void iop_dbg_set_bdam (u32 v)
void iop_dbg_set_bpr (u32 addr, u32 mask, u32 user_mask)
void iop_dbg_set_bpw (u32 addr, u32 mask, u32 user_mask)
void iop_dbg_set_bpx (u32 addr, u32 mask, u32 user_mask)
void iop_dbg_clr_bps (void)
void iop_dbg_clr_bpda (void)
void iop_dbg_clr_bpx (void)
Detailed Description
IOPDEBUG - IOP debugging library. Definitions for the IOPDEBUG library.
Definition in file iopdebug.h.
Macro Definition Documentation
I_iop_dbg_bda
#define I_iop_dbg_bda DECLARE_IMPORT(16, iop_dbg_bda)
Definition at line 68 of file iopdebug.h.
I_iop_dbg_bdam
#define I_iop_dbg_bdam DECLARE_IMPORT(18, iop_dbg_bdam)
Definition at line 70 of file iopdebug.h.
I_iop_dbg_clr_bpda
#define I_iop_dbg_clr_bpda DECLARE_IMPORT(24, iop_dbg_clr_bpda)
Definition at line 76 of file iopdebug.h.
I_iop_dbg_clr_bps
#define I_iop_dbg_clr_bps DECLARE_IMPORT(23, iop_dbg_clr_bps)
Definition at line 75 of file iopdebug.h.
I_iop_dbg_clr_bpx
#define I_iop_dbg_clr_bpx DECLARE_IMPORT(25, iop_dbg_clr_bpx)
Definition at line 77 of file iopdebug.h.
I_iop_dbg_get_bpc
#define I_iop_dbg_get_bpc DECLARE_IMPORT(12, iop_dbg_get_bpc)
Definition at line 64 of file iopdebug.h.
I_iop_dbg_get_bpcm
#define I_iop_dbg_get_bpcm DECLARE_IMPORT(14, iop_dbg_get_bpcm)
Definition at line 66 of file iopdebug.h.
I_iop_dbg_get_dcic
#define I_iop_dbg_get_dcic DECLARE_IMPORT(10, iop_dbg_get_dcic)
Definition at line 62 of file iopdebug.h.
I_iop_dbg_get_handler
#define I_iop_dbg_get_handler DECLARE_IMPORT(7, iop_dbg_get_handler)
Definition at line 59 of file iopdebug.h.
I_iop_dbg_get_reg_frames
#define I_iop_dbg_get_reg_frames DECLARE_IMPORT(9, iop_dbg_get_reg_frames)
Definition at line 61 of file iopdebug.h.
I_iop_dbg_install
#define I_iop_dbg_install DECLARE_IMPORT(5, iop_dbg_install)
Definition at line 57 of file iopdebug.h.
I_iop_dbg_remove
#define I_iop_dbg_remove DECLARE_IMPORT(6, iop_dbg_remove)
Definition at line 58 of file iopdebug.h.
I_iop_dbg_set_bda
#define I_iop_dbg_set_bda DECLARE_IMPORT(17, iop_dbg_set_bda)
Definition at line 69 of file iopdebug.h.
I_iop_dbg_set_bdam
#define I_iop_dbg_set_bdam DECLARE_IMPORT(19, iop_dbg_bdam)
Definition at line 71 of file iopdebug.h.
I_iop_dbg_set_bpc
#define I_iop_dbg_set_bpc DECLARE_IMPORT(13, iop_dbg_set_bpc)
Definition at line 65 of file iopdebug.h.
I_iop_dbg_set_bpcm
#define I_iop_dbg_set_bpcm DECLARE_IMPORT(15, iop_dbg_set_bpcm)
Definition at line 67 of file iopdebug.h.
I_iop_dbg_set_bpr
#define I_iop_dbg_set_bpr DECLARE_IMPORT(20, iop_dbg_set_bpr)
Definition at line 72 of file iopdebug.h.
I_iop_dbg_set_bpw
#define I_iop_dbg_set_bpw DECLARE_IMPORT(21, iop_dbg_set_bpw)
Definition at line 73 of file iopdebug.h.
I_iop_dbg_set_bpx
#define I_iop_dbg_set_bpx DECLARE_IMPORT(22, iop_dbg_bpx)
Definition at line 74 of file iopdebug.h.
I_iop_dbg_set_dcic
#define I_iop_dbg_set_dcic DECLARE_IMPORT(11, iop_dbg_set_dcic)
Definition at line 63 of file iopdebug.h.
I_iop_dbg_set_handler
#define I_iop_dbg_set_handler DECLARE_IMPORT(8, iop_dbg_set_handler)
Definition at line 60 of file iopdebug.h.
iopdebug_IMPORTS_end
#define iopdebug_IMPORTS_end END_IMPORT_TABLE
Definition at line 55 of file iopdebug.h.
iopdebug_IMPORTS_start
#define iopdebug_IMPORTS_start DECLARE_IMPORT_TABLE(iopdebug, 1, 1)
Definition at line 54 of file iopdebug.h.
Typedef Documentation
IOP_ExceptionHandler
typedef int() IOP_ExceptionHandler(struct st_IOP_RegFrame *)
Definition at line 25 of file iopdebug.h.
Function Documentation
iop_dbg_clr_bpda()
void iop_dbg_clr_bpda (void)
Definition at line 88 of file iop_debug.c.
 {
     u32 dcic = iop_dbg_get_dcic();
     dcic &= ~(IOP_DCIC_DW | IOP_DCIC_DR | IOP_DCIC_DAE);
     if(!(dcic & IOP_DCIC_PCE)) { dcic = 0; }
     iop_dbg_set_dcic(dcic);
 }
iop_dbg_clr_bps()
void iop_dbg_clr_bps (void)
Definition at line 104 of file iop_debug.c.
 {
     iop_dbg_set_dcic(0);
     iop_dbg_set_bda(0);
     iop_dbg_set_bdam(0);
     iop_dbg_set_bpc(0);
     iop_dbg_set_bpcm(0);
 }
References iop_dbg_set_bda(), iop_dbg_set_bdam(), iop_dbg_set_bpc(), iop_dbg_set_bpcm(), and iop_dbg_set_dcic().
iop_dbg_clr_bpx()
void iop_dbg_clr_bpx (void)
Definition at line 96 of file iop_debug.c.
 {
     u32 dcic = iop_dbg_get_dcic();
     dcic &= ~(IOP_DCIC_PCE);
     if(!(dcic & IOP_DCIC_DAE)) { dcic = 0; }
     iop_dbg_set_dcic(dcic);
 }
iop_dbg_get_bda()
u32 iop_dbg_get_bda (void)
iop_dbg_get_bdam()
u32 iop_dbg_get_bdam (void)
iop_dbg_get_bpc()
u32 iop_dbg_get_bpc (void)
iop_dbg_get_bpcm()
u32 iop_dbg_get_bpcm (void)
iop_dbg_get_dcic()
u32 iop_dbg_get_dcic (void)
iop_dbg_get_handler()
IOP_ExceptionHandler* iop_dbg_get_handler (int cause)
Definition at line 40 of file iop_debug.c.
 {
     if((cause < 0) || (cause > 15)) { return(NULL); }
     return(iop_exception_handlers[cause]);
 }
References iop_exception_handlers, and NULL.
iop_dbg_get_reg_frames()
void iop_dbg_get_reg_frames (IOP_RegFrame ** def_frame_ptr, IOP_RegFrame ** dbg_frame_ptr)
Definition at line 193 of file iop_debug.c.
 {
     if(def_frame_ptr) { *def_frame_ptr = &_iop_ex_def_frame; }
     if(dbg_frame_ptr) { *dbg_frame_ptr = &_iop_ex_dbg_frame; }
 }
References _iop_ex_dbg_frame, and _iop_ex_def_frame.
Referenced by SBUS_dbg_init().
iop_dbg_install()
int iop_dbg_install (void)
Definition at line 117 of file iop_debug.c.
 {
     int i;
     // if already installed, return with an error.
     if(_is_iop_dbg_installed) { return(-1); }
     // initialize our exception handler pointers.
     for(i = 0; i < 16; i++)
     {
         iop_exception_handlers[i] = NULL;
     }
     // todo: preserve original exception handlers here!
     // This will require using "EXCEPMAN" export 3..
     // register our "default" exception handler.
     if(RegisterDefaultExceptionHandler((exception_handler_t) _iop_ex_def_handler) < 0)
     {
         orig_iop_def_ex_handler = NULL;
         return(-2);
     }
     // register our "BREAK" instruction exception handler.
     if(RegisterPriorityExceptionHandler(IOP_EXCEPTION_BP, 0, (exception_handler_t) _iop_ex_break_handler) < 0)
     {
         RegisterDefaultExceptionHandler((exception_handler_t) orig_iop_def_ex_handler);
         orig_iop_def_ex_handler = NULL;
         orig_iop_break_ex_handler = NULL;
         return(-3);
     }
     // register our "Hardware DeBug"(aka "Hardware BreakPoint") exception handler.
     if(RegisterPriorityExceptionHandler(IOP_EXCEPTION_HDB, 0, (exception_handler_t) _iop_ex_dbg_handler) < 0)
     {
         RegisterDefaultExceptionHandler((exception_handler_t) orig_iop_def_ex_handler);
         orig_iop_def_ex_handler = NULL;
         RegisterPriorityExceptionHandler(IOP_EXCEPTION_BP, 0, (exception_handler_t) orig_iop_break_ex_handler);
         orig_iop_break_ex_handler = NULL;
         orig_iop_dbg_ex_handler = NULL;
         return(-4);
     }
     _is_iop_dbg_installed = 1;
     return(0);
 }
iop_dbg_remove()
int iop_dbg_remove (void)
Definition at line 166 of file iop_debug.c.
 {
     // if not installed, return with an error.
     if(!_is_iop_dbg_installed) { return(-1); }
     if(orig_iop_def_ex_handler)
     {
         RegisterDefaultExceptionHandler((exception_handler_t) orig_iop_def_ex_handler);
         orig_iop_def_ex_handler = NULL;
     }
     if(orig_iop_break_ex_handler)
     {
         RegisterPriorityExceptionHandler(IOP_EXCEPTION_BP, 0, (exception_handler_t) orig_iop_break_ex_handler);
         orig_iop_break_ex_handler = NULL;
     }
     if(orig_iop_dbg_ex_handler)
     {
         RegisterPriorityExceptionHandler(IOP_EXCEPTION_HDB, 0, (exception_handler_t) orig_iop_dbg_ex_handler);
         orig_iop_dbg_ex_handler = NULL;
     }
     _is_iop_dbg_installed = 0;
     return(0);
 }
iop_dbg_set_bda()
void iop_dbg_set_bda (u32 v)
iop_dbg_set_bdam()
void iop_dbg_set_bdam (u32 v)
iop_dbg_set_bpc()
void iop_dbg_set_bpc (u32 v)
iop_dbg_set_bpcm()
void iop_dbg_set_bpcm (u32 v)
iop_dbg_set_bpr()
void iop_dbg_set_bpr (u32 addr, u32 mask, u32 user_mask)
Definition at line 80 of file iop_debug.c.
 { _iop_dbg_set_bpda(addr, mask, IOP_DCIC_DR | user_mask); }
iop_dbg_set_bpw()
void iop_dbg_set_bpw (u32 addr, u32 mask, u32 user_mask)
Definition at line 83 of file iop_debug.c.
 { _iop_dbg_set_bpda(addr, mask, IOP_DCIC_DW | user_mask); }
iop_dbg_set_bpx()
void iop_dbg_set_bpx (u32 addr, u32 mask, u32 user_mask)
Definition at line 86 of file iop_debug.c.
 { _iop_dbg_set_bpx(addr, mask, user_mask); }
iop_dbg_set_dcic()
void iop_dbg_set_dcic (u32 v)
iop_dbg_set_handler()
IOP_ExceptionHandler* iop_dbg_set_handler (int cause, IOP_ExceptionHandler * handler)
Definition at line 47 of file iop_debug.c.
 {
     IOP_ExceptionHandler *old_handler;
     u32 old_state;
     if((cause < 0) || (cause > 15)) { return(NULL); }
     EnterCritical(&old_state);
     old_handler = iop_exception_handlers[cause];
     iop_exception_handlers[cause] = handler;
     ExitCritical(old_state);
     return(old_handler);
 }
References EnterCritical(), ExitCritical(), handler, iop_exception_handlers, and NULL.
Referenced by _start().