ps2sdk: iop/debug/ioptrap/src/ioptrap.c File Reference
ioptrap.c File Reference
#include "types.h"
#include "defs.h"
#include "irx.h"
#include "ioptrap.h"
#include "excepman.h"
#include "loadcore.h"
#include "intrman.h"
#include "sifman.h"
#include "stdio.h"
#include "sysclib.h"
#include "thbase.h"
Macros
#define JUMP_BUF_PC 0
#define JUMP_BUF_SP 1
#define JUMP_BUF_FP 2
#define JUMP_BUF_S0 3
#define JUMP_BUF_S1 4
#define JUMP_BUF_S2 5
#define JUMP_BUF_S3 6
#define JUMP_BUF_S4 7
#define JUMP_BUF_S5 8
#define JUMP_BUF_S6 9
#define JUMP_BUF_S7 10
#define JUMP_BUF_GP 11
#define TRAP_PRINTF(args...)
#define do_tests()
Functions
IRX_ID ("ioptrap_driver", 1, 1)
const char * get_exception_name (exception_type_t type)
void def_exc_handler ()
void bp_exc_handler ()
exception_type_t dbg_setjmp ()
trap_exception_handler_t set_exception_handler (exception_type_t type, trap_exception_handler_t handler)
trap_exception_handler_t get_exception_handler (exception_type_t type)
void trap (exception_type_t type, struct exception_frame *ex)
int _start (int argc, char **argv)
int shutdown ()
Variables
struct irx_export_table _exp_ioptrap
static const char * exception_type_name []
exception_frame_t __trap_frame
int dbg_jmp_buf_setup = 0
jmp_buf dbg_jmp_buf
static trap_exception_handler_t handlers [16]
Detailed Description
IOP exception handling.
Definition in file ioptrap.c.
Macro Definition Documentation
do_tests
#define do_tests ()
Definition at line 193 of file ioptrap.c.
JUMP_BUF_FP
#define JUMP_BUF_FP 2
Definition at line 76 of file ioptrap.c.
JUMP_BUF_GP
#define JUMP_BUF_GP 11
Definition at line 85 of file ioptrap.c.
JUMP_BUF_PC
#define JUMP_BUF_PC 0
Definition at line 74 of file ioptrap.c.
JUMP_BUF_S0
#define JUMP_BUF_S0 3
Definition at line 77 of file ioptrap.c.
JUMP_BUF_S1
#define JUMP_BUF_S1 4
Definition at line 78 of file ioptrap.c.
JUMP_BUF_S2
#define JUMP_BUF_S2 5
Definition at line 79 of file ioptrap.c.
JUMP_BUF_S3
#define JUMP_BUF_S3 6
Definition at line 80 of file ioptrap.c.
JUMP_BUF_S4
#define JUMP_BUF_S4 7
Definition at line 81 of file ioptrap.c.
JUMP_BUF_S5
#define JUMP_BUF_S5 8
Definition at line 82 of file ioptrap.c.
JUMP_BUF_S6
#define JUMP_BUF_S6 9
Definition at line 83 of file ioptrap.c.
JUMP_BUF_S7
#define JUMP_BUF_S7 10
Definition at line 84 of file ioptrap.c.
JUMP_BUF_SP
#define JUMP_BUF_SP 1
Definition at line 75 of file ioptrap.c.
TRAP_PRINTF
#define TRAP_PRINTF (args...)
Definition at line 88 of file ioptrap.c.
Function Documentation
_start()
int _start (int argc, char ** argv)
Definition at line 196 of file ioptrap.c.
 {
     int rv;
         if(RegisterLibraryEntries(&_exp_ioptrap) != 0) return 1;
     memset(handlers, 0, sizeof(trap_exception_handler_t) * 16);
     printf("ioptrap starts.\n");
     if((rv = RegisterDefaultExceptionHandler(def_exc_handler)) < 0) {
         printf("RegisterDefaultExceptionHandler failed, rv=%d\n", rv);
         return 1;
     }
     if((rv = RegisterPriorityExceptionHandler(IOP_EXCEPTION_HDB, 0, bp_exc_handler)) < 0) {
         // shouldn't we release the default exception handler here... ?
         printf("RegisterDefaultExceptionHandler failed, rv=%d\n", rv);
         return 1;
     }
     do_tests();
     return 0;
 }
References _exp_ioptrap, bp_exc_handler(), def_exc_handler(), do_tests, handlers, IOP_EXCEPTION_HDB, memset(), printf(), RegisterDefaultExceptionHandler(), RegisterLibraryEntries(), and RegisterPriorityExceptionHandler().
bp_exc_handler()
void bp_exc_handler ()
Referenced by _start().
dbg_setjmp()
exception_type_t dbg_setjmp ()
Definition at line 64 of file ioptrap.c.
{
     int v;
     if(0 == (v = setjmp(dbg_jmp_buf))) {
         dbg_jmp_buf_setup = 1;
     } else {
         dbg_jmp_buf_setup = 0;
     }
     return v;
 }
References dbg_jmp_buf, dbg_jmp_buf_setup, and setjmp().
def_exc_handler()
void def_exc_handler ()
Referenced by _start().
get_exception_handler()
trap_exception_handler_t get_exception_handler (exception_type_t type)
Definition at line 98 of file ioptrap.c.
{
     return handlers[type];
 }
References handlers.
get_exception_name()
const char* get_exception_name (exception_type_t type)
Definition at line 53 of file ioptrap.c.
{
     return exception_type_name[type];
 }
References exception_type_name.
IRX_ID()
IRX_ID ("ioptrap_driver" , 1 , 1)
set_exception_handler()
trap_exception_handler_t set_exception_handler (exception_type_t type, trap_exception_handler_t handler)
Definition at line 92 of file ioptrap.c.
{
     trap_exception_handler_t old_handler = handlers[type];
     handlers[type] = handler;
     return old_handler;
 }
References handler, and handlers.
shutdown()
int shutdown (void)
Definition at line 217 of file ioptrap.c.
 {
     return 0;
 }
trap()
void trap (exception_type_t type, struct exception_frame * ex)
Definition at line 102 of file ioptrap.c.
{
     u32 i;
     if(dbg_jmp_buf_setup) {
         u32 *p = (u32*)dbg_jmp_buf;
         /* simulate longjmp */
         ex->epc = p[JUMP_BUF_PC];
         ex->regs[29] = p[JUMP_BUF_SP];
         ex->regs[30] = p[JUMP_BUF_FP];
         ex->regs[16] = p[JUMP_BUF_S0];
         ex->regs[17] = p[JUMP_BUF_S1];
         ex->regs[18] = p[JUMP_BUF_S2];
         ex->regs[19] = p[JUMP_BUF_S3];
         ex->regs[20] = p[JUMP_BUF_S4];
         ex->regs[21] = p[JUMP_BUF_S5];
         ex->regs[22] = p[JUMP_BUF_S6];
         ex->regs[23] = p[JUMP_BUF_S7];
         ex->regs[28] = p[JUMP_BUF_GP];
         ex->regs[2] = type; /* return value from setjmp */
         return;
     }
     TRAP_PRINTF("IOP Exception : %s\n", exception_type_name[type]);
     TRAP_PRINTF("EPC=%08x CAUSE=%08x SR=%08x BADVADDR=%08x DCIC=%08x\n", ex->epc, ex->cause, ex->sr, ex->badvaddr, ex->dcic);
     for(i = 0; i != 32; i += 4) {
         TRAP_PRINTF("r[%02d]=%08x r[%02d]=%08x r[%02d]=%08x r[%02d]=%08x",
                 i, ex->regs[i], i+1, ex->regs[i+1], i+2, ex->regs[i+2], i+3, ex->regs[i+3]);
     }
     if (handlers[type]) {
         handlers[type](type, ex);
     }
     if(type == EXCEPTION_Bp) {
         ex->dcic = 0;
     } else {
         if(ex->cause & (1<<31)) {
             ex->cause &= ~(1<<31); /* clear BD */
         } else {
             ex->epc += 4;
         }
     }
 }
References dbg_jmp_buf, dbg_jmp_buf_setup, EXCEPTION_Bp, exception_type_name, handlers, JUMP_BUF_FP, JUMP_BUF_GP, JUMP_BUF_PC, JUMP_BUF_S0, JUMP_BUF_S1, JUMP_BUF_S2, JUMP_BUF_S3, JUMP_BUF_S4, JUMP_BUF_S5, JUMP_BUF_S6, JUMP_BUF_S7, JUMP_BUF_SP, and TRAP_PRINTF.
Variable Documentation
__trap_frame
exception_frame_t __trap_frame
Definition at line 57 of file ioptrap.c.
_exp_ioptrap
struct irx_export_table _exp_ioptrap extern
Referenced by _start().
dbg_jmp_buf
jmp_buf dbg_jmp_buf
Definition at line 62 of file ioptrap.c.
Referenced by dbg_setjmp(), and trap().
dbg_jmp_buf_setup
int dbg_jmp_buf_setup = 0
Definition at line 61 of file ioptrap.c.
Referenced by dbg_setjmp(), and trap().
exception_type_name
const char* exception_type_name[] static
Initial value:
= {
    "Interrupt",
    "TLB Modification",
    "TLB Miss Load",
    "TLB Miss Store",
    "Address Error Load",
    "Address Error Store",
    "Instruction Bus Error",
    "Data Bus Error",
    "Syscall",
    "Breakpoint",
    "Reserved Instruction",
    "Coprocessor Unusable",
    "Overflow",
    "Reserved 13",
    "Reserved 14"
}
Definition at line 35 of file ioptrap.c.
Referenced by get_exception_name(), and trap().
handlers
trap_exception_handler_t handlers[16] static
Definition at line 90 of file ioptrap.c.
Referenced by _start(), get_exception_handler(), set_exception_handler(), and trap().