ps2sdk: iop/hdd/libapa/src/misc.c File Reference
misc.c File Reference
#include <errno.h>
#include <intrman.h>
#include <cdvdman.h>
#include <sysclib.h>
#include <sysmem.h>
#include <thbase.h>
#include <iomanX.h>
#include <stdio.h>
#include <hdd-ioctl.h>
#include "apa-opt.h"
#include "libapa.h"
Functions
void * apaAllocMem (int size)
void apaFreeMem (void *ptr)
int apaGetTime (apa_ps2time_t *tm)
int apaGetIlinkID (u8 *idbuf)
Function Documentation
apaAllocMem()
void* apaAllocMem (int size)
Definition at line 32 of file misc.c.
 {
 #ifdef _IOP
         int intrStat;
         void *mem;
         CpuSuspendIntr(&intrStat);
         mem = AllocSysMemory(ALLOC_FIRST, size, NULL);
         if(mem == NULL)
                 APA_PRINTF(APA_DRV_NAME": error: out of memory\n");
         CpuResumeIntr(intrStat);
         return mem;
 #else
         return malloc(size);
 #endif
 }
References ALLOC_FIRST, AllocSysMemory(), APA_DRV_NAME, APA_PRINTF, CpuResumeIntr(), CpuSuspendIntr(), malloc, and NULL.
Referenced by _start(), and apaCacheInit().
apaFreeMem()
void apaFreeMem (void * ptr)
Definition at line 50 of file misc.c.
 {
 #ifdef _IOP
         int intrStat;
         CpuSuspendIntr(&intrStat);
         FreeSysMemory(ptr);
         CpuResumeIntr(intrStat);
 #else
         free(ptr);
 #endif
 }
References CpuResumeIntr(), CpuSuspendIntr(), free, and FreeSysMemory().
apaGetIlinkID()
int apaGetIlinkID (u8 * idbuf)
Definition at line 111 of file misc.c.
 {
 #ifdef _IOP
         u32 stat;
         int i;
         for(i = 0; ; i++)
         {
                 stat=0;
                 memset(idbuf, 0, 32);
                 if((sceCdRI(idbuf, &stat) != 0) && (stat == 0))
                 {
                         return 0;
                 }
                 if(i >= 20)
                         break;
                 DelayThread(100000);
         }
         APA_PRINTF(APA_DRV_NAME": Error: cannot get id\n");
         return -EIO;
 #else
         memset(idbuf, 0, 32);
         return 0;
 #endif
 }
References APA_DRV_NAME, APA_PRINTF, DelayThread(), EIO, memset(), and sceCdRI().
Referenced by unlockDrive().
apaGetTime()
int apaGetTime (apa_ps2time_t * tm)
Definition at line 63 of file misc.c.
 {
 #ifdef _IOP
         int ret, i;
         sceCdCLOCK      cdtime;
         static apa_ps2time_t timeBuf={
                 0, 7, 6, 5, 4, 3, 2000  // used if can not get time...
         };
         for(i = 0; i < 20; i++)
         {
                 ret = sceCdReadClock(&cdtime);
                 if(ret!=0 && cdtime.stat==0)
                 {
                         timeBuf.sec=btoi(cdtime.second);
                         timeBuf.min=btoi(cdtime.minute);
                         timeBuf.hour=btoi(cdtime.hour);
                         timeBuf.day=btoi(cdtime.day);
                         timeBuf.month=btoi(cdtime.month & 0x7F);        //The old CDVDMAN sceCdReadClock() function does not automatically file off the highest bit.
                         timeBuf.year=btoi(cdtime.year) + 2000;
                         break;
                 } else {
                         if(!(cdtime.stat & 0x80))
                                 break;
                 }
                 DelayThread(100000);
         }
         memcpy(tm, &timeBuf, sizeof(apa_ps2time_t));
 #else
         time_t rawtime;
         struct tm * timeinfo;
         time (&rawtime);
         timeinfo=localtime (&rawtime);
         tm->sec=timeinfo->tm_sec;
         tm->min=timeinfo->tm_min;
         tm->hour=timeinfo->tm_hour;
         tm->day=timeinfo->tm_mday;
         tm->month=timeinfo->tm_mon;
         tm->year=timeinfo->tm_year+1900;
 #endif
         return 0;
 }
References btoi, sceCdCLOCK::day, apa_ps2time_t::day, DelayThread(), sceCdCLOCK::hour, apa_ps2time_t::hour, memcpy(), apa_ps2time_t::min, sceCdCLOCK::minute, sceCdCLOCK::month, apa_ps2time_t::month, sceCdReadClock(), apa_ps2time_t::sec, sceCdCLOCK::second, sceCdCLOCK::stat, sceCdCLOCK::year, and apa_ps2time_t::year.
Referenced by _start(), apaFillHeader(), apaMakeEmpty(), apaRemovePartition(), hddDevctl(), and hddFormat().