ps2sdk: iop/hdd/libapa/src/cache.c File Reference
cache.c File Reference
#include <errno.h>
#include <iomanX.h>
#include <sysclib.h>
#include <stdio.h>
#include <hdd-ioctl.h>
#include "apa-opt.h"
#include "libapa.h"
Functions
int apaCacheInit (u32 size)
void apaCacheLink (apa_cache_t *clink, apa_cache_t *cnew)
apa_cache_t * apaCacheUnLink (apa_cache_t *clink)
int apaCacheTransfer (apa_cache_t *clink, int type)
void apaCacheFlushDirty (apa_cache_t *clink)
int apaCacheFlushAllDirty (s32 device)
apa_cache_t * apaCacheGetHeader (s32 device, u32 sector, u32 mode, int *result)
void apaCacheFree (apa_cache_t *clink)
apa_cache_t * apaCacheAlloc (void)
Variables
static apa_cache_t * cacheBuf
static int cacheSize
Function Documentation
apaCacheAlloc()
apa_cache_t* apaCacheAlloc (void)
Definition at line 182 of file cache.c.
 {
         apa_cache_t *cnext;
         if((cacheBuf->tail==cacheBuf) &&
                 (cacheBuf->tail==cacheBuf->tail->next)){
                         APA_PRINTF(APA_DRV_NAME": error: free buffer empty\n");
                         return NULL;
                 }
         cnext=cacheBuf->next;
         if(cnext->flags & APA_CACHE_FLAG_DIRTY)
                 APA_PRINTF(APA_DRV_NAME": error: dirty buffer allocated\n");
         cnext->nused=1;
         cnext->flags=0;
         cnext->device=-1;
         cnext->sector=-1;
         return apaCacheUnLink(cnext);
 }
References APA_CACHE_FLAG_DIRTY, APA_DRV_NAME, APA_PRINTF, apaCacheUnLink(), cacheBuf, apa_cache_t::device, apa_cache_t::flags, apa_cache_t::next, NULL, apa_cache_t::nused, apa_cache_t::sector, and apa_cache_t::tail.
Referenced by apaGetFormat(), apaGetPartErrorSector(), apaJournalRestore(), apaOpen(), apaSetPartErrorSector(), and hddFormat().
apaCacheFlushAllDirty()
int apaCacheFlushAllDirty (s32 device)
Definition at line 95 of file cache.c.
 {
         int i;
         // flush apal
         for(i=1;i<cacheSize+1;i++){
                 if((cacheBuf[i].flags & APA_CACHE_FLAG_DIRTY) && cacheBuf[i].device==device)
                         apaJournalWrite(&cacheBuf[i]);
         }
         apaJournalFlush(device);
         // flush apa
         for(i=1;i<cacheSize+1;i++){
                 if((cacheBuf[i].flags & APA_CACHE_FLAG_DIRTY) && cacheBuf[i].device==device)
                         apaCacheTransfer(&cacheBuf[i], APA_IO_MODE_WRITE);
         }
         return apaJournalReset(device);
 }
References APA_CACHE_FLAG_DIRTY, APA_IO_MODE_WRITE, apaCacheTransfer(), apaJournalFlush(), apaJournalReset(), apaJournalWrite(), cacheBuf, and cacheSize.
Referenced by apaDelete(), apaDeleteFixNext(), apaDeleteFixPrev(), apaGetNextHeader(), apaInsertPartition(), apaRemove(), apaRename(), devctlSetOsdMBR(), devctlSwapTemp(), hddAddPartitionHere(), ioctl2AddSub(), and ioctl2DeleteLastSub().
apaCacheFlushDirty()
void apaCacheFlushDirty (apa_cache_t * clink)
Definition at line 89 of file cache.c.
 {
         if(clink->flags&APA_CACHE_FLAG_DIRTY)
                 apaCacheTransfer(clink, APA_IO_MODE_WRITE);
 }
References APA_CACHE_FLAG_DIRTY, APA_IO_MODE_WRITE, apaCacheTransfer(), and apa_cache_t::flags.
Referenced by hddFormat().
apaCacheFree()
void apaCacheFree (apa_cache_t * clink)
Definition at line 164 of file cache.c.
 {
         if(clink==NULL){
                 APA_PRINTF(APA_DRV_NAME": error: null buffer returned\n");
                 return;
         }
         if(clink->nused==0){
                 APA_PRINTF(APA_DRV_NAME": error: unused cache returned\n");
                 return;
         }
         if(clink->flags & APA_CACHE_FLAG_DIRTY)
                 APA_PRINTF(APA_DRV_NAME": error: dirty buffer returned\n");
         clink->nused--;
         if(clink->nused==0)
                 apaCacheLink(cacheBuf->tail, clink);
         return;
 }
References APA_CACHE_FLAG_DIRTY, APA_DRV_NAME, APA_PRINTF, apaCacheLink(), cacheBuf, apa_cache_t::flags, NULL, apa_cache_t::nused, and apa_cache_t::tail.
Referenced by apaDelete(), apaDeleteFixNext(), apaDeleteFixPrev(), apaGetFormat(), apaGetNextHeader(), apaGetPartErrorName(), apaGetPartErrorSector(), apaInsertPartition(), apaJournalRestore(), apaOpen(), apaRemove(), apaRename(), apaSetPartErrorSector(), devctlSetOsdMBR(), devctlSwapTemp(), hddAddPartitionHere(), hddDread(), hddFormat(), hddGetStat(), ioctl2AddSub(), and ioctl2DeleteLastSub().
apaCacheGetHeader()
apa_cache_t* apaCacheGetHeader (s32 device, u32 sector, u32 mode, int * result)
Definition at line 112 of file cache.c.
 {
         apa_cache_t *clink=NULL;
         int i;
         *result=0;
         for(i=1;i<cacheSize+1;i++){
                 if(cacheBuf[i].sector==sector &&
                         cacheBuf[i].device==device){
                                 clink=&cacheBuf[i];
                                 break;
                         }
         }
         if(clink!=NULL) {
                 // cached ver was found :)
                 if(clink->nused==0)
                         clink=apaCacheUnLink(clink);
                 clink->nused++;
                 return clink;
         }
         if((cacheBuf->tail==cacheBuf) &&
                 (cacheBuf->tail==cacheBuf->tail->next)){
                         APA_PRINTF(APA_DRV_NAME": error: free buffer empty\n");
                 }
         else
         {
                 clink=cacheBuf->next;
                 if(clink->flags & APA_CACHE_FLAG_DIRTY)
                         APA_PRINTF(APA_DRV_NAME": error: dirty buffer allocated\n");
                 clink->flags=0;
                 clink->nused=1;
                 clink->device=device;
                 clink->sector=sector;
                 clink=apaCacheUnLink(clink);
         }
         if(clink==NULL)
         {
                 *result=-ENOMEM;
                 return NULL;
         }
         if(!mode)
         {
                 if((*result=apaCacheTransfer(clink, APA_IO_MODE_READ))<0){
                         clink->nused=0;
                         clink->device=-1;
                         apaCacheLink(cacheBuf, clink);
                         clink=NULL;
                 }
         }
         return clink;
 }
References APA_CACHE_FLAG_DIRTY, APA_DRV_NAME, APA_IO_MODE_READ, APA_PRINTF, apaCacheLink(), apaCacheTransfer(), apaCacheUnLink(), cacheBuf, cacheSize, apa_cache_t::device, ENOMEM, apa_cache_t::flags, apa_cache_t::next, NULL, apa_cache_t::nused, result, apa_cache_t::sector, and apa_cache_t::tail.
Referenced by apaDelete(), apaDeleteFixNext(), apaDeleteFixPrev(), apaFillHeader(), apaFindPartition(), apaGetFreeSectors(), apaGetNextHeader(), apaGetPartErrorName(), apaInsertPartition(), apaOpen(), apaRemove(), apaRemovePartition(), devctlSetOsdMBR(), hddAddPartitionHere(), hddDread(), hddFormat(), ioctl2AddSub(), and ioctl2DeleteLastSub().
apaCacheInit()
int apaCacheInit (u32 size)
Definition at line 30 of file cache.c.
 {
         apa_header_t *header;
         unsigned int i;
         cacheSize=size; // save size ;)
         if((header=(apa_header_t *)apaAllocMem(size*sizeof(apa_header_t)))){
                 cacheBuf=apaAllocMem((size+1)*sizeof(apa_cache_t));
                 if(cacheBuf==NULL)
                         return -ENOMEM;
         }
         else
                 return -ENOMEM;
         // setup cache header...
         memset(cacheBuf, 0, (size+1)*sizeof(apa_cache_t));
         cacheBuf->next=cacheBuf;
         cacheBuf->tail=cacheBuf;
         for(i=1; i<size+1;i++, header++){
                 cacheBuf[i].header=header;
                 cacheBuf[i].device=-1;
                 apaCacheLink(cacheBuf->tail, &cacheBuf[i]);
         }
         return 0;
 }
References apaAllocMem(), apaCacheLink(), cacheBuf, cacheSize, apa_cache_t::device, ENOMEM, apa_cache_t::header, memset(), apa_cache_t::next, NULL, and apa_cache_t::tail.
Referenced by _start().
apaCacheLink()
void apaCacheLink (apa_cache_t * clink, apa_cache_t * cnew)
Definition at line 55 of file cache.c.
 {
         cnew->tail=clink;
         cnew->next=clink->next;
         clink->next->tail=cnew;
         clink->next=cnew;
 }
References apa_cache_t::next, and apa_cache_t::tail.
Referenced by apaCacheFree(), apaCacheGetHeader(), and apaCacheInit().
apaCacheTransfer()
int apaCacheTransfer (apa_cache_t * clink, int type)
Definition at line 70 of file cache.c.
 {
         int err;
         if(type)
                 err=apaWriteHeader(clink->device, clink->header, clink->sector);
         else// 0
                 err=apaReadHeader(clink->device, clink->header, clink->sector);
         if(err)
         {
                 APA_PRINTF(APA_DRV_NAME": error: disk err %d on device %ld, sector %ld, type %d\n",
                         err, clink->device, clink->sector, type);
                 if(type==0)// save any read error's..
                         apaSaveError(clink->device, clink->header, APA_SECTOR_SECTOR_ERROR, clink->sector);
         }
         clink->flags&=~APA_CACHE_FLAG_DIRTY;
         return err;
 }
References APA_CACHE_FLAG_DIRTY, APA_DRV_NAME, APA_PRINTF, APA_SECTOR_SECTOR_ERROR, apaReadHeader(), apaSaveError(), apaWriteHeader(), apa_cache_t::device, apa_cache_t::flags, apa_cache_t::header, and apa_cache_t::sector.
Referenced by apaCacheFlushAllDirty(), apaCacheFlushDirty(), and apaCacheGetHeader().
apaCacheUnLink()
apa_cache_t* apaCacheUnLink (apa_cache_t * clink)
Definition at line 63 of file cache.c.
 {
         clink->tail->next=clink->next;
         clink->next->tail=clink->tail;
         return clink;
 }
References apa_cache_t::next, and apa_cache_t::tail.
Referenced by apaCacheAlloc(), and apaCacheGetHeader().
Variable Documentation
cacheBuf
apa_cache_t* cacheBuf static
Definition at line 27 of file cache.c.
Referenced by apaCacheAlloc(), apaCacheFlushAllDirty(), apaCacheFree(), apaCacheGetHeader(), and apaCacheInit().
cacheSize
int cacheSize static
Definition at line 28 of file cache.c.
Referenced by _start(), apaCacheFlushAllDirty(), apaCacheGetHeader(), and apaCacheInit().