ps2sdk: iop/hdd/libapa/src/journal.c File Reference
journal.c File Reference
#include <errno.h>
#include <iomanX.h>
#include <atad.h>
#include <sysclib.h>
#include <stdio.h>
#include <hdd-ioctl.h>
#include "apa-opt.h"
#include "libapa.h"
Functions
int apaJournalFlush (s32 device)
int apaJournalReset (s32 device)
int apaJournalWrite (apa_cache_t *clink)
int apaJournalRestore (s32 device)
Variables
static apa_journal_t journalBuf
Function Documentation
apaJournalFlush()
int apaJournalFlush (s32 device)
Definition at line 30 of file journal.c.
 {// this write any thing that in are journal buffer :)
         if(ata_device_flush_cache(device))
                 return -EIO;
         if(ata_device_sector_io(device, &journalBuf, APA_SECTOR_APAL, 1, ATA_DIR_WRITE))
                 return -EIO;
         if(ata_device_flush_cache(device))
                 return -EIO;
         return 0;
 }
References APA_SECTOR_APAL, ata_device_flush_cache(), ata_device_sector_io(), ATA_DIR_WRITE, EIO, and journalBuf.
Referenced by apaCacheFlushAllDirty(), and apaJournalReset().
apaJournalReset()
int apaJournalReset (s32 device)
Definition at line 41 of file journal.c.
 {
         memset(&journalBuf, 0, sizeof(apa_journal_t));
         journalBuf.magic=APAL_MAGIC;
         return apaJournalFlush(device);
 }
References apaJournalFlush(), APAL_MAGIC, journalBuf, apa_journal_t::magic, and memset().
Referenced by apaCacheFlushAllDirty(), apaJournalRestore(), and hddFormat().
apaJournalRestore()
int apaJournalRestore (s32 device)
Definition at line 59 of file journal.c.
 {       // copies the journal from the HDD and erases the original.
         int i, ret;
         u32 sector;
         apa_cache_t *clink;
         APA_PRINTF(APA_DRV_NAME": checking log...\n");
         ret = ata_device_sector_io(device, &journalBuf, APA_SECTOR_APAL, sizeof(apa_journal_t)/512, ATA_DIR_READ) == 0 ? 0 : -EIO;
         if((ret == 0) && (journalBuf.magic == APAL_MAGIC))
         {
                 if(journalBuf.num == 0)
                         return 0;
                 clink=apaCacheAlloc();
                 for(i=0, sector=APA_SECTOR_APAL_HEADERS;i<journalBuf.num;i++, sector+=2)
                 {
                         ret = (ata_device_sector_io(device, clink->header, sector, 2, ATA_DIR_READ) == 0) ? 0 : -EIO;
                         if(ret != 0)
                                 break;
                         ret = (ata_device_sector_io(device, clink->header, journalBuf.sectors[i], 2, ATA_DIR_WRITE) == 0) ? 0 : -EIO;
                         if(ret != 0)
                                 break;
                 }
                 apaCacheFree(clink);
         }
         return apaJournalReset(device);
 }
References APA_DRV_NAME, APA_PRINTF, APA_SECTOR_APAL, APA_SECTOR_APAL_HEADERS, apaCacheAlloc(), apaCacheFree(), apaJournalReset(), APAL_MAGIC, ata_device_sector_io(), ATA_DIR_READ, ATA_DIR_WRITE, EIO, apa_cache_t::header, journalBuf, apa_journal_t::magic, apa_journal_t::num, and apa_journal_t::sectors.
Referenced by _start().
apaJournalWrite()
int apaJournalWrite (apa_cache_t * clink)
Definition at line 48 of file journal.c.
 {
         clink->header->checksum=journalCheckSum(clink->header);
         if(ata_device_sector_io(clink->device, clink->header,
                 (journalBuf.num << 1)+APA_SECTOR_APAL_HEADERS, 2, ATA_DIR_WRITE))
                         return -EIO;
         journalBuf.sectors[journalBuf.num]=clink->sector;
         journalBuf.num++;
         return 0;
 }
References APA_SECTOR_APAL_HEADERS, ata_device_sector_io(), ATA_DIR_WRITE, apa_header_t::checksum, apa_cache_t::device, EIO, apa_cache_t::header, journalBuf, journalCheckSum, apa_journal_t::num, apa_cache_t::sector, and apa_journal_t::sectors.
Referenced by apaCacheFlushAllDirty().
Variable Documentation
journalBuf
apa_journal_t journalBuf static
Definition at line 28 of file journal.c.
Referenced by apaJournalFlush(), apaJournalReset(), apaJournalRestore(), and apaJournalWrite().