ps2sdk: iop/hdd/libapa/include/libapa.h File Reference
libapa.h File Reference
#include <types.h>
#include <hdd-ioctl.h>
Data Structures
struct apa_ps2time_t
struct apa_sub_t
struct apa_header_t
struct apa_cache_t
struct apa_params_t
struct apa_journal_t
struct apa_device_t
Macros
#define APA_SECTOR_MBR 0
#define APA_SECTOR_SECTOR_ERROR 6
#define APA_SECTOR_PART_ERROR 7
#define APA_SECTOR_APAL 8
#define APA_SECTOR_APAL_HEADERS 10
#define APA_MAGIC 0x00415041
#define APA_MBR_VERSION 2
#define APA_MODVER ((APA_MODVER_MAJOR << 8) | APA_MODVER_MINOR)
#define APA_CACHE_FLAG_DIRTY 0x01
#define APAL_MAGIC 0x4150414C
#define journalCheckSum(header) apaCheckSum((apa_header_t *)header)
Functions
void apaSaveError (s32 device, void *buffer, u32 lba, u32 err_lba)
void apaSetPartErrorSector (s32 device, u32 lba)
int apaGetPartErrorSector (s32 device, u32 lba, u32 *lba_out)
int apaGetPartErrorName (s32 device, char *name)
apa_cache_t * apaFillHeader (s32 device, const apa_params_t *params, u32 start, u32 next, u32 prev, u32 length, int *err)
apa_cache_t * apaInsertPartition (s32 device, const apa_params_t *params, u32 sector, int *err)
apa_cache_t * apaFindPartition (s32 device, const char *id, int *err)
void apaAddEmptyBlock (apa_header_t *header, u32 *emptyBlocks)
apa_cache_t * apaRemovePartition (s32 device, u32 start, u32 next, u32 prev, u32 length)
void apaMakeEmpty (apa_cache_t *clink)
apa_cache_t * apaDeleteFixPrev (apa_cache_t *clink1, int *err)
apa_cache_t * apaDeleteFixNext (apa_cache_t *clink, int *err)
int apaDelete (apa_cache_t *clink)
int apaCheckSum (apa_header_t *header)
int apaReadHeader (s32 device, apa_header_t *header, u32 lba)
int apaWriteHeader (s32 device, apa_header_t *header, u32 lba)
int apaGetFormat (s32 device, int *format)
u32 apaGetPartitionMax (u32 totalLBA)
apa_cache_t * apaGetNextHeader (apa_cache_t *clink, int *err)
int apaCacheInit (u32 size)
void apaCacheLink (apa_cache_t *clink, apa_cache_t *cnew)
apa_cache_t * apaCacheUnLink (apa_cache_t *clink)
int apaCacheTransfer (apa_cache_t *clink, int type)
void apaCacheFlushDirty (apa_cache_t *clink)
int apaCacheFlushAllDirty (s32 device)
apa_cache_t * apaCacheGetHeader (s32 device, u32 sector, u32 mode, int *err)
void apaCacheFree (apa_cache_t *clink)
apa_cache_t * apaCacheAlloc (void)
int apaJournalReset (s32 device)
int apaJournalFlush (s32 device)
int apaJournalWrite (apa_cache_t *clink)
int apaJournalRestore (s32 device)
void * apaAllocMem (int size)
void apaFreeMem (void *ptr)
int apaGetTime (apa_ps2time_t *tm)
int apaGetIlinkID (u8 *idbuf)
int apaPassCmp (const char *password1, const char *password2)
void apaEncryptPassword (const char *id, char *password_out, const char *password_in)
int apaGetFreeSectors (s32 device, u32 *free, apa_device_t *deviceinfo)
Macro Definition Documentation
APA_CACHE_FLAG_DIRTY
#define APA_CACHE_FLAG_DIRTY 0x01
Definition at line 80 of file libapa.h.
APA_MAGIC
#define APA_MAGIC 0x00415041
Definition at line 25 of file libapa.h.
APA_MBR_VERSION
#define APA_MBR_VERSION 2
Definition at line 26 of file libapa.h.
APA_MODVER
#define APA_MODVER ((APA_MODVER_MAJOR << 8) | APA_MODVER_MINOR)
Definition at line 28 of file libapa.h.
APA_SECTOR_APAL
#define APA_SECTOR_APAL 8
Definition at line 21 of file libapa.h.
APA_SECTOR_APAL_HEADERS
#define APA_SECTOR_APAL_HEADERS 10
Definition at line 22 of file libapa.h.
APA_SECTOR_MBR
#define APA_SECTOR_MBR 0
Definition at line 18 of file libapa.h.
APA_SECTOR_PART_ERROR
#define APA_SECTOR_PART_ERROR 7
Definition at line 20 of file libapa.h.
APA_SECTOR_SECTOR_ERROR
#define APA_SECTOR_SECTOR_ERROR 6
Definition at line 19 of file libapa.h.
APAL_MAGIC
#define APAL_MAGIC 0x4150414C
Definition at line 143 of file libapa.h.
journalCheckSum
#define journalCheckSum (header) apaCheckSum((apa_header_t *)header)
Definition at line 151 of file libapa.h.
Function Documentation
apaAddEmptyBlock()
void apaAddEmptyBlock (apa_header_t * header, u32 * emptyBlocks)
Definition at line 190 of file apa.c.
 {       // small helper.... to track empty blocks..
         u32 i;
         if(header->type==APA_TYPE_FREE) {
                 for(i=0;i<32;i++)
                 {
                         if(header->length==(1 << i)) {
                                 if(emptyBlocks[i]==APA_TYPE_FREE) {
                                         emptyBlocks[i]=header->start;
                                         return;
                                 }
                         }
                 }
         }
 }
References APA_TYPE_FREE, apa_header_t::length, apa_header_t::start, and apa_header_t::type.
Referenced by apaOpen(), and ioctl2AddSub().
apaAllocMem()
void* apaAllocMem (int size)
Definition at line 32 of file misc.c.
 {
 #ifdef _IOP
         int intrStat;
         void *mem;
         CpuSuspendIntr(&intrStat);
         mem = AllocSysMemory(ALLOC_FIRST, size, NULL);
         if(mem == NULL)
                 APA_PRINTF(APA_DRV_NAME": error: out of memory\n");
         CpuResumeIntr(intrStat);
         return mem;
 #else
         return malloc(size);
 #endif
 }
References ALLOC_FIRST, AllocSysMemory(), APA_DRV_NAME, APA_PRINTF, CpuResumeIntr(), CpuSuspendIntr(), malloc, and NULL.
Referenced by _start(), and apaCacheInit().
apaCacheAlloc()
apa_cache_t* apaCacheAlloc (void)
Definition at line 182 of file cache.c.
 {
         apa_cache_t *cnext;
         if((cacheBuf->tail==cacheBuf) &&
                 (cacheBuf->tail==cacheBuf->tail->next)){
                         APA_PRINTF(APA_DRV_NAME": error: free buffer empty\n");
                         return NULL;
                 }
         cnext=cacheBuf->next;
         if(cnext->flags & APA_CACHE_FLAG_DIRTY)
                 APA_PRINTF(APA_DRV_NAME": error: dirty buffer allocated\n");
         cnext->nused=1;
         cnext->flags=0;
         cnext->device=-1;
         cnext->sector=-1;
         return apaCacheUnLink(cnext);
 }
References APA_CACHE_FLAG_DIRTY, APA_DRV_NAME, APA_PRINTF, apaCacheUnLink(), cacheBuf, apa_cache_t::device, apa_cache_t::flags, apa_cache_t::next, NULL, apa_cache_t::nused, apa_cache_t::sector, and apa_cache_t::tail.
Referenced by apaGetFormat(), apaGetPartErrorSector(), apaJournalRestore(), apaOpen(), apaSetPartErrorSector(), and hddFormat().
apaCacheFlushAllDirty()
int apaCacheFlushAllDirty (s32 device)
Definition at line 95 of file cache.c.
 {
         int i;
         // flush apal
         for(i=1;i<cacheSize+1;i++){
                 if((cacheBuf[i].flags & APA_CACHE_FLAG_DIRTY) && cacheBuf[i].device==device)
                         apaJournalWrite(&cacheBuf[i]);
         }
         apaJournalFlush(device);
         // flush apa
         for(i=1;i<cacheSize+1;i++){
                 if((cacheBuf[i].flags & APA_CACHE_FLAG_DIRTY) && cacheBuf[i].device==device)
                         apaCacheTransfer(&cacheBuf[i], APA_IO_MODE_WRITE);
         }
         return apaJournalReset(device);
 }
References APA_CACHE_FLAG_DIRTY, APA_IO_MODE_WRITE, apaCacheTransfer(), apaJournalFlush(), apaJournalReset(), apaJournalWrite(), cacheBuf, and cacheSize.
Referenced by apaDelete(), apaDeleteFixNext(), apaDeleteFixPrev(), apaGetNextHeader(), apaInsertPartition(), apaRemove(), apaRename(), devctlSetOsdMBR(), devctlSwapTemp(), hddAddPartitionHere(), ioctl2AddSub(), and ioctl2DeleteLastSub().
apaCacheFlushDirty()
void apaCacheFlushDirty (apa_cache_t * clink)
Definition at line 89 of file cache.c.
 {
         if(clink->flags&APA_CACHE_FLAG_DIRTY)
                 apaCacheTransfer(clink, APA_IO_MODE_WRITE);
 }
References APA_CACHE_FLAG_DIRTY, APA_IO_MODE_WRITE, apaCacheTransfer(), and apa_cache_t::flags.
Referenced by hddFormat().
apaCacheFree()
void apaCacheFree (apa_cache_t * clink)
Definition at line 164 of file cache.c.
 {
         if(clink==NULL){
                 APA_PRINTF(APA_DRV_NAME": error: null buffer returned\n");
                 return;
         }
         if(clink->nused==0){
                 APA_PRINTF(APA_DRV_NAME": error: unused cache returned\n");
                 return;
         }
         if(clink->flags & APA_CACHE_FLAG_DIRTY)
                 APA_PRINTF(APA_DRV_NAME": error: dirty buffer returned\n");
         clink->nused--;
         if(clink->nused==0)
                 apaCacheLink(cacheBuf->tail, clink);
         return;
 }
References APA_CACHE_FLAG_DIRTY, APA_DRV_NAME, APA_PRINTF, apaCacheLink(), cacheBuf, apa_cache_t::flags, NULL, apa_cache_t::nused, and apa_cache_t::tail.
Referenced by apaDelete(), apaDeleteFixNext(), apaDeleteFixPrev(), apaGetFormat(), apaGetNextHeader(), apaGetPartErrorName(), apaGetPartErrorSector(), apaInsertPartition(), apaJournalRestore(), apaOpen(), apaRemove(), apaRename(), apaSetPartErrorSector(), devctlSetOsdMBR(), devctlSwapTemp(), hddAddPartitionHere(), hddDread(), hddFormat(), hddGetStat(), ioctl2AddSub(), and ioctl2DeleteLastSub().
apaCacheGetHeader()
apa_cache_t* apaCacheGetHeader (s32 device, u32 sector, u32 mode, int * err)
Definition at line 112 of file cache.c.
 {
         apa_cache_t *clink=NULL;
         int i;
         *result=0;
         for(i=1;i<cacheSize+1;i++){
                 if(cacheBuf[i].sector==sector &&
                         cacheBuf[i].device==device){
                                 clink=&cacheBuf[i];
                                 break;
                         }
         }
         if(clink!=NULL) {
                 // cached ver was found :)
                 if(clink->nused==0)
                         clink=apaCacheUnLink(clink);
                 clink->nused++;
                 return clink;
         }
         if((cacheBuf->tail==cacheBuf) &&
                 (cacheBuf->tail==cacheBuf->tail->next)){
                         APA_PRINTF(APA_DRV_NAME": error: free buffer empty\n");
                 }
         else
         {
                 clink=cacheBuf->next;
                 if(clink->flags & APA_CACHE_FLAG_DIRTY)
                         APA_PRINTF(APA_DRV_NAME": error: dirty buffer allocated\n");
                 clink->flags=0;
                 clink->nused=1;
                 clink->device=device;
                 clink->sector=sector;
                 clink=apaCacheUnLink(clink);
         }
         if(clink==NULL)
         {
                 *result=-ENOMEM;
                 return NULL;
         }
         if(!mode)
         {
                 if((*result=apaCacheTransfer(clink, APA_IO_MODE_READ))<0){
                         clink->nused=0;
                         clink->device=-1;
                         apaCacheLink(cacheBuf, clink);
                         clink=NULL;
                 }
         }
         return clink;
 }
References APA_CACHE_FLAG_DIRTY, APA_DRV_NAME, APA_IO_MODE_READ, APA_PRINTF, apaCacheLink(), apaCacheTransfer(), apaCacheUnLink(), cacheBuf, cacheSize, apa_cache_t::device, ENOMEM, apa_cache_t::flags, apa_cache_t::next, NULL, apa_cache_t::nused, result, apa_cache_t::sector, and apa_cache_t::tail.
Referenced by apaDelete(), apaDeleteFixNext(), apaDeleteFixPrev(), apaFillHeader(), apaFindPartition(), apaGetFreeSectors(), apaGetNextHeader(), apaGetPartErrorName(), apaInsertPartition(), apaOpen(), apaRemove(), apaRemovePartition(), devctlSetOsdMBR(), hddAddPartitionHere(), hddDread(), hddFormat(), ioctl2AddSub(), and ioctl2DeleteLastSub().
apaCacheInit()
int apaCacheInit (u32 size)
Definition at line 30 of file cache.c.
 {
         apa_header_t *header;
         unsigned int i;
         cacheSize=size; // save size ;)
         if((header=(apa_header_t *)apaAllocMem(size*sizeof(apa_header_t)))){
                 cacheBuf=apaAllocMem((size+1)*sizeof(apa_cache_t));
                 if(cacheBuf==NULL)
                         return -ENOMEM;
         }
         else
                 return -ENOMEM;
         // setup cache header...
         memset(cacheBuf, 0, (size+1)*sizeof(apa_cache_t));
         cacheBuf->next=cacheBuf;
         cacheBuf->tail=cacheBuf;
         for(i=1; i<size+1;i++, header++){
                 cacheBuf[i].header=header;
                 cacheBuf[i].device=-1;
                 apaCacheLink(cacheBuf->tail, &cacheBuf[i]);
         }
         return 0;
 }
References apaAllocMem(), apaCacheLink(), cacheBuf, cacheSize, apa_cache_t::device, ENOMEM, apa_cache_t::header, memset(), apa_cache_t::next, NULL, and apa_cache_t::tail.
Referenced by _start().
apaCacheLink()
void apaCacheLink (apa_cache_t * clink, apa_cache_t * cnew)
Definition at line 55 of file cache.c.
 {
         cnew->tail=clink;
         cnew->next=clink->next;
         clink->next->tail=cnew;
         clink->next=cnew;
 }
References apa_cache_t::next, and apa_cache_t::tail.
Referenced by apaCacheFree(), apaCacheGetHeader(), and apaCacheInit().
apaCacheTransfer()
int apaCacheTransfer (apa_cache_t * clink, int type)
Definition at line 70 of file cache.c.
 {
         int err;
         if(type)
                 err=apaWriteHeader(clink->device, clink->header, clink->sector);
         else// 0
                 err=apaReadHeader(clink->device, clink->header, clink->sector);
         if(err)
         {
                 APA_PRINTF(APA_DRV_NAME": error: disk err %d on device %ld, sector %ld, type %d\n",
                         err, clink->device, clink->sector, type);
                 if(type==0)// save any read error's..
                         apaSaveError(clink->device, clink->header, APA_SECTOR_SECTOR_ERROR, clink->sector);
         }
         clink->flags&=~APA_CACHE_FLAG_DIRTY;
         return err;
 }
References APA_CACHE_FLAG_DIRTY, APA_DRV_NAME, APA_PRINTF, APA_SECTOR_SECTOR_ERROR, apaReadHeader(), apaSaveError(), apaWriteHeader(), apa_cache_t::device, apa_cache_t::flags, apa_cache_t::header, and apa_cache_t::sector.
Referenced by apaCacheFlushAllDirty(), apaCacheFlushDirty(), and apaCacheGetHeader().
apaCacheUnLink()
apa_cache_t* apaCacheUnLink (apa_cache_t * clink)
Definition at line 63 of file cache.c.
 {
         clink->tail->next=clink->next;
         clink->next->tail=clink->tail;
         return clink;
 }
References apa_cache_t::next, and apa_cache_t::tail.
Referenced by apaCacheAlloc(), and apaCacheGetHeader().
apaCheckSum()
int apaCheckSum (apa_header_t * header)
Definition at line 402 of file apa.c.
 {
         u32 *ptr=(u32 *)header;
         u32 sum, i;
         for(sum=0,i=1; i < 256; i++)    //sizeof(header)/4 = 256, start at offset +4 to omit the checksum field.
                 sum+=ptr[i];
         return sum;
 }
Referenced by apaReadHeader(), and hddFormat().
apaDelete()
int apaDelete (apa_cache_t * clink)
Definition at line 352 of file apa.c.
 {
         int                             rv=0;
         apa_cache_t             *clink_mbr;
         u32                             device=clink->device;
         u32                             start=clink->header->start;
         int                             i;
         if(!start) {
                 apaCacheFree(clink);
                 return -EACCES;
         }
         if(clink->header->next==0)
         {
                 if((clink_mbr=apaCacheGetHeader(device, 0, APA_IO_MODE_READ, &rv))==NULL)
                 {
                         apaCacheFree(clink);
                         return rv;
                 }
                 do {
                         apaCacheFree(clink);
                         if((clink=apaCacheGetHeader(clink->device, clink->header->prev, APA_IO_MODE_READ, &rv))==NULL)
                                 return 0;
                         clink->header->next=0;
                         clink->flags|=APA_CACHE_FLAG_DIRTY;
                         clink_mbr->header->prev=clink->header->start;
                         clink_mbr->flags|=APA_CACHE_FLAG_DIRTY;
                         apaCacheFlushAllDirty(device);
                 } while(clink->header->type==0);
                 apaCacheFree(clink_mbr);
         } else {
                 u32 length=clink->header->length;
                 for(i=0;i < 2;i++){
                         if((clink=apaDeleteFixPrev(clink, &rv))==NULL)
                                 return 0;
                         if((clink=apaDeleteFixNext(clink, &rv))==NULL)
                                 return 0;
                 }
                 if(clink->header->start==start && clink->header->length==length)
                 {
                         apaMakeEmpty(clink);
                         apaCacheFlushAllDirty(clink->device);
                 }
         }
         apaCacheFree(clink);
         return rv;
 }
References APA_CACHE_FLAG_DIRTY, APA_IO_MODE_READ, apaCacheFlushAllDirty(), apaCacheFree(), apaCacheGetHeader(), apaDeleteFixNext(), apaDeleteFixPrev(), apaMakeEmpty(), apa_cache_t::device, EACCES, apa_cache_t::flags, apa_cache_t::header, apa_header_t::length, apa_header_t::next, NULL, apa_header_t::prev, apa_header_t::start, and apa_header_t::type.
Referenced by apaRemove(), and ioctl2DeleteLastSub().
apaDeleteFixNext()
apa_cache_t* apaDeleteFixNext (apa_cache_t * clink, int * err)
Definition at line 299 of file apa.c.
 {
         apa_header_t            *header=clink->header;
         u32                             length=header->length;
         u32                             saved_length=header->length;
         u32                             lnext=header->next;
         apa_cache_t             *clink1;
         apa_cache_t             *clink2;
         u32                             device=clink->device;
         u32                             tmp;
         while(lnext!=0)
         {
                 if(!(clink1=apaCacheGetHeader(device, lnext, APA_IO_MODE_READ, err)))
                 {
                         apaCacheFree(clink);
                         return 0;
                 }
                 header=clink1->header;
                 tmp=header->length+length;
                 if(header->type!=0)
                 {
                         apaCacheFree(clink1);
                         break;
                 }
                 if((clink->header->start%tmp)!=0 || ((tmp-1) & tmp))
                 {
                         apaCacheFree(clink1);
                         break;
                 }
                 length=tmp;
                 apaCacheFree(clink1);
                 lnext=header->next;
         }
         if(length!=saved_length)
         {
                 if(!(clink2=apaCacheGetHeader(device, lnext, APA_IO_MODE_READ, err)))
                 {
                         apaCacheFree(clink);
                         return NULL;
                 }
                 clink->header->length=length;
                 clink->header->next=lnext;
                 apaMakeEmpty(clink);
                 clink2->header->prev=clink->header->start;
                 clink2->flags|=APA_CACHE_FLAG_DIRTY;
                 apaCacheFlushAllDirty(device);
                 apaCacheFree(clink2);
         }
         return clink;
 }
References APA_CACHE_FLAG_DIRTY, APA_IO_MODE_READ, apaCacheFlushAllDirty(), apaCacheFree(), apaCacheGetHeader(), apaMakeEmpty(), apa_cache_t::device, apa_cache_t::flags, apa_cache_t::header, apa_header_t::length, apa_header_t::next, NULL, apa_header_t::prev, apa_header_t::start, and apa_header_t::type.
Referenced by apaDelete().
apaDeleteFixPrev()
apa_cache_t* apaDeleteFixPrev (apa_cache_t * clink1, int * err)
Definition at line 249 of file apa.c.
 {
         apa_cache_t             *clink2=clink;
         apa_header_t            *header=clink2->header;
         u32                             device=clink->device;
         u32                             length=clink->header->length;
         u32                             saved_next=clink->header->next;
         u32                             saved_length=clink->header->length;
         u32                             tmp;
         while(header->start)
         {
                 if(!(clink2=apaCacheGetHeader(device, header->prev, APA_IO_MODE_READ, err)))
                 {
                         apaCacheFree(clink);
                         return NULL;
                 }
                 header=clink2->header;
                 tmp=header->length+length;
                 if(header->type!=0) {
                         apaCacheFree(clink2);
                         break;
                 }
                 if((header->start%tmp) || (tmp & (tmp-1))) {
                         apaCacheFree(clink2);
                         break;
                 }
                 length=tmp;
                 apaCacheFree(clink);
                 clink=clink2;
         }
         if(length!=saved_length)
         {
                 if(!(clink2=apaCacheGetHeader(device, saved_next, APA_IO_MODE_READ, err)))
                 {
                         apaCacheFree(clink);
                         return NULL;
                 }
                 clink->header->length=length;
                 clink->header->next=clink->header->start+length;
                 clink2->header->prev=clink->header->start;
                 clink2->flags|=APA_CACHE_FLAG_DIRTY;
                 clink->flags|=APA_CACHE_FLAG_DIRTY;
                 apaCacheFlushAllDirty(device);
                 apaCacheFree(clink2);
         }
         return clink;
 }
References APA_CACHE_FLAG_DIRTY, APA_IO_MODE_READ, apaCacheFlushAllDirty(), apaCacheFree(), apaCacheGetHeader(), apa_cache_t::device, apa_cache_t::flags, apa_cache_t::header, apa_header_t::length, apa_header_t::next, NULL, apa_header_t::prev, apa_header_t::start, and apa_header_t::type.
Referenced by apaDelete().
apaEncryptPassword()
void apaEncryptPassword (const char * id, char * password_out, const char * password_in)
Definition at line 39 of file password.c.
 {
         char password[APA_PASSMAX];
         memcpy(password, password_in, APA_PASSMAX);
         DESEncryptPassword(*(u32*)(id), *(u32*)(id + 4), password_out, password);
 }
References APA_PASSMAX, DESEncryptPassword(), and memcpy().
Referenced by fioGetInput(), and hddFormat().
apaFillHeader()
apa_cache_t* apaFillHeader (s32 device, const apa_params_t * params, u32 start, u32 next, u32 prev, u32 length, int * err)
Definition at line 98 of file apa.c.
 {       // used for making a new partition
         apa_cache_t *clink;
         if(!(clink=apaCacheGetHeader(device, start, APA_IO_MODE_WRITE, err)))
                 return NULL;
         memset(clink->header, 0, sizeof(apa_header_t));
         clink->header->magic=APA_MAGIC;
         clink->header->start=start;
         clink->header->next=next;
         clink->header->prev=prev;
         clink->header->length=length;
         clink->header->type=params->type;
         clink->header->flags=params->flags;
         clink->header->modver=APA_MODVER;
         memcpy(clink->header->id, params->id, APA_IDMAX);
         if(params->flags & APA_FLAG_SUB)
         {
                 clink->header->main=params->main;
                 clink->header->number=params->number;
         }
         else
         {
                 if(strncmp(clink->header->id, "_tmp", APA_IDMAX)!=0)
                 {
                         memcpy(clink->header->rpwd, params->rpwd, APA_PASSMAX);
                         memcpy(clink->header->fpwd, params->fpwd, APA_PASSMAX);
                 }
         }
         apaGetTime(&clink->header->created);
         clink->flags|=APA_CACHE_FLAG_DIRTY;
         return clink;
 }
References APA_CACHE_FLAG_DIRTY, APA_FLAG_SUB, APA_IDMAX, APA_IO_MODE_WRITE, APA_MAGIC, APA_MODVER, APA_PASSMAX, apaCacheGetHeader(), apaGetTime(), apa_header_t::created, apa_header_t::flags, apa_cache_t::flags, apa_params_t::flags, apa_header_t::fpwd, apa_params_t::fpwd, apa_cache_t::header, apa_header_t::id, apa_params_t::id, apa_header_t::length, apa_header_t::magic, apa_header_t::main, apa_params_t::main, memcpy(), memset(), apa_header_t::modver, apa_header_t::next, NULL, apa_header_t::number, apa_params_t::number, apa_header_t::prev, apa_header_t::rpwd, apa_params_t::rpwd, apa_header_t::start, strncmp(), apa_header_t::type, and apa_params_t::type.
Referenced by apaInsertPartition(), and hddAddPartitionHere().
apaFindPartition()
apa_cache_t* apaFindPartition (s32 device, const char * id, int * err)
Definition at line 168 of file apa.c.
 {
         apa_cache_t *clink;
         clink=apaCacheGetHeader(device, 0, APA_IO_MODE_READ, err);
         while(clink)
         {
                 if(!(clink->header->flags & APA_FLAG_SUB)) {
                         if(memcmp(clink->header->id, id, APA_IDMAX)==0)
                                 return clink;   // found
                 }
                 clink=apaGetNextHeader(clink, (int *)err);
         }
         if(*err==0) {
                 *err=-ENOENT;
                 return NULL;
                 //return (apa_cache_t *)-ENOENT;                // <-- BUG code tests for NULL only
         }
         *err=0;
         return NULL;
 }
References APA_FLAG_SUB, APA_IDMAX, APA_IO_MODE_READ, apaCacheGetHeader(), apaGetNextHeader(), ENOENT, apa_header_t::flags, apa_cache_t::header, apa_header_t::id, memcmp(), and NULL.
Referenced by apaRemove(), apaRename(), devctlSwapTemp(), and hddGetStat().
apaFreeMem()
void apaFreeMem (void * ptr)
Definition at line 50 of file misc.c.
 {
 #ifdef _IOP
         int intrStat;
         CpuSuspendIntr(&intrStat);
         FreeSysMemory(ptr);
         CpuResumeIntr(intrStat);
 #else
         free(ptr);
 #endif
 }
References CpuResumeIntr(), CpuSuspendIntr(), free, and FreeSysMemory().
apaGetFormat()
int apaGetFormat (s32 device, int * format)
Definition at line 437 of file apa.c.
 {
         apa_cache_t *clink;
         int rv=0;
         u32 *pDW, i;
         clink=apaCacheAlloc();
         *format=0;
         if((rv=apaReadHeader(device, clink->header, 0))==0)
         {
                 *format=clink->header->mbr.version;
                 if(ata_device_sector_io(device, clink->header, APA_SECTOR_SECTOR_ERROR, 2, ATA_DIR_READ))
                         rv=-EIO; // return -EIO;
                 if(rv==0){
                         pDW=(u32 *)clink->header;
                         for(i=0;i < 256; i++)
{
                                 if((i & 0x7F) && pDW[i]!=0)
                                         rv=1;
                         }
                 }
         }
         apaCacheFree(clink);
         return rv==0;
 }
References APA_SECTOR_SECTOR_ERROR, apaCacheAlloc(), apaCacheFree(), apaReadHeader(), ata_device_sector_io(), ATA_DIR_READ, EIO, format(), apa_cache_t::header, apa_header_t::mbr, and apa_header_t::version.
Referenced by _start().
apaGetFreeSectors()
int apaGetFreeSectors (s32 device, u32 * free, apa_device_t * deviceinfo)
Definition at line 45 of file free.c.
 {
         u32 sectors, partMax;
         int rv;
         apa_cache_t *clink;
         sectors = 0;
         *free = 0;
         if((clink = apaCacheGetHeader(device, 0, APA_IO_MODE_READ, &rv)) != NULL)
         {
                 do{
                         if(clink->header->type == 0)
                                 apaCalculateFreeSpace(free, clink->header->length);
                         sectors += clink->header->length;
                 }while((clink = apaGetNextHeader(clink, &rv)) != NULL);
         }
         if(rv == 0)
         {
                 for(partMax = deviceinfo[device].partitionMaxSize; 0x0003FFFF < partMax; partMax = deviceinfo[device].partitionMaxSize)
                 {       //As weird as it looks, this was how it was done in the original HDD.IRX.
                         for( ; 0x0003FFFF < partMax; partMax /= 2)
{
                                 //Non-SONY: Perform 64-bit arithmetic here to avoid overflows when dealing with large disks.
                                 if((sectors % partMax == 0) && ((u64)sectors + partMax < deviceinfo[device].totalLBA))
{
                                         apaCalculateFreeSpace(free, partMax);
                                         sectors += partMax;
                                         break;
                                 }
                         }
                         if(0x0003FFFF >= partMax)
                                 break;
                 }
                 APA_PRINTF(APA_DRV_NAME": total = %08lx sectors, installable = %08lx sectors.\n", sectors, *free);
         }
         return rv;
 }
References APA_DRV_NAME, APA_IO_MODE_READ, APA_PRINTF, apaCacheGetHeader(), apaCalculateFreeSpace(), apaGetNextHeader(), free, apa_cache_t::header, apa_header_t::length, NULL, apa_device_t::partitionMaxSize, and apa_header_t::type.
Referenced by hddDevctl().
apaGetIlinkID()
int apaGetIlinkID (u8 * idbuf)
Definition at line 111 of file misc.c.
 {
 #ifdef _IOP
         u32 stat;
         int i;
         for(i = 0; ; i++)
         {
                 stat=0;
                 memset(idbuf, 0, 32);
                 if((sceCdRI(idbuf, &stat) != 0) && (stat == 0))
                 {
                         return 0;
                 }
                 if(i >= 20)
                         break;
                 DelayThread(100000);
         }
         APA_PRINTF(APA_DRV_NAME": Error: cannot get id\n");
         return -EIO;
 #else
         memset(idbuf, 0, 32);
         return 0;
 #endif
 }
References APA_DRV_NAME, APA_PRINTF, DelayThread(), EIO, memset(), and sceCdRI().
Referenced by unlockDrive().
apaGetNextHeader()
apa_cache_t* apaGetNextHeader (apa_cache_t * clink, int * err)
Definition at line 480 of file apa.c.
 {
         u32 start=clink->header->start;
         apaCacheFree(clink);
         if(!clink->header->next)
                 return NULL;
         if(!(clink=apaCacheGetHeader(clink->device, clink->header->next, APA_IO_MODE_READ, err)))
                 return NULL;
         if(start!=clink->header->prev) {
                 APA_PRINTF(APA_DRV_NAME": Warning: Invalid partition information. start != prev\n");
                 clink->header->prev=start;
                 clink->flags|=APA_CACHE_FLAG_DIRTY;
                 apaCacheFlushAllDirty(clink->device);
         }
         return clink;
 }
References APA_CACHE_FLAG_DIRTY, APA_DRV_NAME, APA_IO_MODE_READ, APA_PRINTF, apaCacheFlushAllDirty(), apaCacheFree(), apaCacheGetHeader(), apa_cache_t::device, apa_cache_t::flags, apa_cache_t::header, apa_header_t::next, NULL, apa_header_t::prev, and apa_header_t::start.
Referenced by apaFindPartition(), apaGetFreeSectors(), apaGetPartErrorName(), apaOpen(), and ioctl2AddSub().
apaGetPartErrorName()
int apaGetPartErrorName (s32 device, char * name)
Definition at line 64 of file apa.c.
 {
         u32 lba;
         int rv=0;
         apa_cache_t *clink;
         if((rv=apaGetPartErrorSector(device, APA_SECTOR_PART_ERROR, &lba)) <= 0)
                 return rv;
         if(!(clink=apaCacheGetHeader(device, 0, APA_IO_MODE_READ, &rv)))
                 return rv;
         while(clink)
         {
                 if(clink->header->type!=APA_TYPE_FREE &&
                         !(clink->header->flags & APA_CACHE_FLAG_DIRTY) &&
                         clink->header->start==lba)
                 {
                                 if(name)
{
                                         strncpy(name, clink->header->id, APA_IDMAX - 1);
                                         name[APA_IDMAX - 1] = '\0';
                                 }
                                 apaCacheFree(clink);
                                 return 1;
                 }
                 clink=apaGetNextHeader(clink, &rv);
         }
         // clear error if no errors and partitions was not found...
         if(rv==0)
                 apaSetPartErrorSector(device, 0);
         return rv;
 }
References APA_CACHE_FLAG_DIRTY, APA_IDMAX, APA_IO_MODE_READ, APA_SECTOR_PART_ERROR, APA_TYPE_FREE, apaCacheFree(), apaCacheGetHeader(), apaGetNextHeader(), apaGetPartErrorSector(), apaSetPartErrorSector(), apa_header_t::flags, apa_cache_t::header, apa_header_t::id, apa_header_t::start, strncpy(), and apa_header_t::type.
Referenced by hddDevctl().
apaGetPartErrorSector()
int apaGetPartErrorSector (s32 device, u32 lba, u32 * lba_out)
Definition at line 45 of file apa.c.
 {
         apa_cache_t     *clink;
         int                     rv=0;
         if(!(clink=apaCacheAlloc()))
                 return -ENOMEM;
         if(ata_device_sector_io(device, clink->header, lba, 1, ATA_DIR_READ))
                 return -EIO;
         if(lba_out)
                 *lba_out=*clink->error_lba;
         if(*clink->error_lba)
                 rv=1;// error is set ;)
         apaCacheFree(clink);
         return rv;
 }
References apaCacheAlloc(), apaCacheFree(), ata_device_sector_io(), ATA_DIR_READ, EIO, ENOMEM, apa_cache_t::error_lba, and apa_cache_t::header.
Referenced by apaGetPartErrorName(), hddDevctl(), and hddIoctl2().
apaGetPartitionMax()
u32 apaGetPartitionMax (u32 totalLBA)
Definition at line 463 of file apa.c.
 {
         u32 i, size;
         totalLBA>>=6; // totalLBA/64
         size=(1<<0x1F);
         for(i=31;i!=0;i--)
         {
                 size=1<<i;
                 if(size&totalLBA)
                         break;
         }
         if(size<totalLBA)
                 i++;
         return(1 << i);
 }
Referenced by _start().
apaGetTime()
int apaGetTime (apa_ps2time_t * tm)
Definition at line 63 of file misc.c.
 {
 #ifdef _IOP
         int ret, i;
         sceCdCLOCK      cdtime;
         static apa_ps2time_t timeBuf={
                 0, 7, 6, 5, 4, 3, 2000  // used if can not get time...
         };
         for(i = 0; i < 20; i++)
         {
                 ret = sceCdReadClock(&cdtime);
                 if(ret!=0 && cdtime.stat==0)
                 {
                         timeBuf.sec=btoi(cdtime.second);
                         timeBuf.min=btoi(cdtime.minute);
                         timeBuf.hour=btoi(cdtime.hour);
                         timeBuf.day=btoi(cdtime.day);
                         timeBuf.month=btoi(cdtime.month & 0x7F);        //The old CDVDMAN sceCdReadClock() function does not automatically file off the highest bit.
                         timeBuf.year=btoi(cdtime.year) + 2000;
                         break;
                 } else {
                         if(!(cdtime.stat & 0x80))
                                 break;
                 }
                 DelayThread(100000);
         }
         memcpy(tm, &timeBuf, sizeof(apa_ps2time_t));
 #else
         time_t rawtime;
         struct tm * timeinfo;
         time (&rawtime);
         timeinfo=localtime (&rawtime);
         tm->sec=timeinfo->tm_sec;
         tm->min=timeinfo->tm_min;
         tm->hour=timeinfo->tm_hour;
         tm->day=timeinfo->tm_mday;
         tm->month=timeinfo->tm_mon;
         tm->year=timeinfo->tm_year+1900;
 #endif
         return 0;
 }
References btoi, sceCdCLOCK::day, apa_ps2time_t::day, DelayThread(), sceCdCLOCK::hour, apa_ps2time_t::hour, memcpy(), apa_ps2time_t::min, sceCdCLOCK::minute, sceCdCLOCK::month, apa_ps2time_t::month, sceCdReadClock(), apa_ps2time_t::sec, sceCdCLOCK::second, sceCdCLOCK::stat, sceCdCLOCK::year, and apa_ps2time_t::year.
Referenced by _start(), apaFillHeader(), apaMakeEmpty(), apaRemovePartition(), hddDevctl(), and hddFormat().
apaInsertPartition()
apa_cache_t* apaInsertPartition (s32 device, const apa_params_t * params, u32 sector, int * err)
Definition at line 133 of file apa.c.
 {       // Adds a new partition using an empty block.
         apa_cache_t *clink_empty;
         apa_cache_t *clink_this;
         apa_cache_t *clink_next;
         if((clink_this=apaCacheGetHeader(device, sector, APA_IO_MODE_READ, err))==0)
                 return 0;
         while(clink_this->header->length!=params->size)
         {
                 if((clink_next=apaCacheGetHeader(device, clink_this->header->next, APA_IO_MODE_READ, err))==NULL)
                 {       // Get next partition
                         apaCacheFree(clink_this);
                         return 0;
                 }
                 clink_this->header->length>>=1;
                 clink_empty=apaRemovePartition(device, (clink_this->header->start+clink_this->header->length),
                         clink_this->header->next, clink_this->header->start, clink_this->header->length);
                 clink_this->header->next=clink_empty->header->start;
                 clink_this->flags|=APA_CACHE_FLAG_DIRTY;
                 clink_next->header->prev=clink_empty->header->start;
                 clink_next->flags|=APA_CACHE_FLAG_DIRTY;
                 apaCacheFlushAllDirty(device);
                 apaCacheFree(clink_empty);
                 apaCacheFree(clink_next);
         }
         apaCacheFree(clink_this);
         clink_this=apaFillHeader(device, params, clink_this->header->start, clink_this->header->next,
                 clink_this->header->prev, params->size, err);
         apaCacheFlushAllDirty(device);
         return clink_this;
 }
References APA_CACHE_FLAG_DIRTY, APA_IO_MODE_READ, apaCacheFlushAllDirty(), apaCacheFree(), apaCacheGetHeader(), apaFillHeader(), apaRemovePartition(), apa_cache_t::flags, apa_cache_t::header, apa_header_t::length, apa_header_t::next, NULL, apa_header_t::prev, apa_params_t::size, and apa_header_t::start.
Referenced by hddAddPartitionHere().
apaJournalFlush()
int apaJournalFlush (s32 device)
Definition at line 30 of file journal.c.
 {// this write any thing that in are journal buffer :)
         if(ata_device_flush_cache(device))
                 return -EIO;
         if(ata_device_sector_io(device, &journalBuf, APA_SECTOR_APAL, 1, ATA_DIR_WRITE))
                 return -EIO;
         if(ata_device_flush_cache(device))
                 return -EIO;
         return 0;
 }
References APA_SECTOR_APAL, ata_device_flush_cache(), ata_device_sector_io(), ATA_DIR_WRITE, EIO, and journalBuf.
Referenced by apaCacheFlushAllDirty(), and apaJournalReset().
apaJournalReset()
int apaJournalReset (s32 device)
Definition at line 41 of file journal.c.
 {
         memset(&journalBuf, 0, sizeof(apa_journal_t));
         journalBuf.magic=APAL_MAGIC;
         return apaJournalFlush(device);
 }
References apaJournalFlush(), APAL_MAGIC, journalBuf, apa_journal_t::magic, and memset().
Referenced by apaCacheFlushAllDirty(), apaJournalRestore(), and hddFormat().
apaJournalRestore()
int apaJournalRestore (s32 device)
Definition at line 59 of file journal.c.
 {       // copies the journal from the HDD and erases the original.
         int i, ret;
         u32 sector;
         apa_cache_t *clink;
         APA_PRINTF(APA_DRV_NAME": checking log...\n");
         ret = ata_device_sector_io(device, &journalBuf, APA_SECTOR_APAL, sizeof(apa_journal_t)/512, ATA_DIR_READ) == 0 ? 0 : -EIO;
         if((ret == 0) && (journalBuf.magic == APAL_MAGIC))
         {
                 if(journalBuf.num == 0)
                         return 0;
                 clink=apaCacheAlloc();
                 for(i=0, sector=APA_SECTOR_APAL_HEADERS;i<journalBuf.num;i++, sector+=2)
                 {
                         ret = (ata_device_sector_io(device, clink->header, sector, 2, ATA_DIR_READ) == 0) ? 0 : -EIO;
                         if(ret != 0)
                                 break;
                         ret = (ata_device_sector_io(device, clink->header, journalBuf.sectors[i], 2, ATA_DIR_WRITE) == 0) ? 0 : -EIO;
                         if(ret != 0)
                                 break;
                 }
                 apaCacheFree(clink);
         }
         return apaJournalReset(device);
 }
References APA_DRV_NAME, APA_PRINTF, APA_SECTOR_APAL, APA_SECTOR_APAL_HEADERS, apaCacheAlloc(), apaCacheFree(), apaJournalReset(), APAL_MAGIC, ata_device_sector_io(), ATA_DIR_READ, ATA_DIR_WRITE, EIO, apa_cache_t::header, journalBuf, apa_journal_t::magic, apa_journal_t::num, and apa_journal_t::sectors.
Referenced by _start().
apaJournalWrite()
int apaJournalWrite (apa_cache_t * clink)
Definition at line 48 of file journal.c.
 {
         clink->header->checksum=journalCheckSum(clink->header);
         if(ata_device_sector_io(clink->device, clink->header,
                 (journalBuf.num << 1)+APA_SECTOR_APAL_HEADERS, 2, ATA_DIR_WRITE))
                         return -EIO;
         journalBuf.sectors[journalBuf.num]=clink->sector;
         journalBuf.num++;
         return 0;
 }
References APA_SECTOR_APAL_HEADERS, ata_device_sector_io(), ATA_DIR_WRITE, apa_header_t::checksum, apa_cache_t::device, EIO, apa_cache_t::header, journalBuf, journalCheckSum, apa_journal_t::num, apa_cache_t::sector, and apa_journal_t::sectors.
Referenced by apaCacheFlushAllDirty().
apaMakeEmpty()
void apaMakeEmpty (apa_cache_t * clink)
Definition at line 227 of file apa.c.
 {
         u32             saved_start;
         u32             saved_next;
         u32             saved_prev;
         u32             saved_length;
         saved_start  = clink->header->start;
         saved_next   = clink->header->next;
         saved_prev   = clink->header->prev;
         saved_length = clink->header->length;
         memset(clink->header, 0, sizeof(apa_header_t));
         clink->header->magic  = APA_MAGIC;
         clink->header->start  = saved_start;
         clink->header->next   = saved_next;
         clink->header->prev   = saved_prev;
         clink->header->length = saved_length;
         apaGetTime(&clink->header->created);
         strcpy(clink->header->id, "__empty");
         clink->flags|=APA_CACHE_FLAG_DIRTY;
 }
References APA_CACHE_FLAG_DIRTY, APA_MAGIC, apaGetTime(), apa_header_t::created, apa_cache_t::flags, apa_cache_t::header, apa_header_t::id, apa_header_t::length, apa_header_t::magic, memset(), apa_header_t::next, apa_header_t::prev, apa_header_t::start, and strcpy().
Referenced by apaDelete(), and apaDeleteFixNext().
apaPassCmp()
int apaPassCmp (const char * password1, const char * password2)
Definition at line 27 of file password.c.
 {
 #ifdef APA_ENABLE_PASSWORDS
          return memcmp(pw1, pw2, APA_PASSMAX) ? -EACCES : 0;
 #else
         //Passwords are not supported, hence this check should always pass.
         return 0;
 #endif
 }
References APA_PASSMAX, EACCES, and memcmp().
Referenced by apaOpen(), apaRemove(), apaRename(), devctlSwapTemp(), and hddGetStat().
apaReadHeader()
int apaReadHeader (s32 device, apa_header_t * header, u32 lba)
Definition at line 412 of file apa.c.
 {
         if(ata_device_sector_io(device, header, lba, 2, ATA_DIR_READ)!=0)
                 return -EIO;
         if(header->magic!=APA_MAGIC)
                 return -EIO;
         if(apaCheckSum(header)!=header->checksum)
                 return -EIO;
         if(lba==APA_SECTOR_MBR)
         {
                 if(strncmp(header->mbr.magic, apaMBRMagic, sizeof(header->mbr.magic))==0)
                         return 0;
                 APA_PRINTF(APA_DRV_NAME": error: invalid partition table or version newer than I know.\n");
                 return -EIO;
         }
         return 0;
 }
References APA_DRV_NAME, APA_MAGIC, APA_PRINTF, APA_SECTOR_MBR, apaCheckSum(), apaMBRMagic, ata_device_sector_io(), ATA_DIR_READ, apa_header_t::checksum, EIO, apa_header_t::magic, apa_header_t::mbr, and strncmp().
Referenced by apaCacheTransfer(), and apaGetFormat().
apaRemovePartition()
apa_cache_t* apaRemovePartition (s32 device, u32 start, u32 next, u32 prev, u32 length)
Definition at line 207 of file apa.c.
 {
         apa_cache_t *clink;
         int err;
         if((clink=apaCacheGetHeader(device, start, APA_IO_MODE_WRITE, &err))==NULL)
                 return NULL;
         memset(clink->header, 0, sizeof(apa_header_t));
         clink->header->magic=APA_MAGIC;
         clink->header->start=start;
         clink->header->next=next;
         clink->header->prev=prev;
         clink->header->length=length;
         strcpy(clink->header->id, "__empty");
         apaGetTime(&clink->header->created);
         clink->flags|=APA_CACHE_FLAG_DIRTY;
         return clink;
 }
References APA_CACHE_FLAG_DIRTY, APA_IO_MODE_WRITE, APA_MAGIC, apaCacheGetHeader(), apaGetTime(), apa_header_t::created, apa_cache_t::flags, apa_cache_t::header, apa_header_t::id, apa_header_t::length, apa_header_t::magic, memset(), apa_header_t::next, NULL, apa_header_t::prev, apa_header_t::start, and strcpy().
Referenced by apaInsertPartition(), and hddAddPartitionHere().
apaSaveError()
void apaSaveError (s32 device, void * buffer, u32 lba, u32 err_lba)
Definition at line 29 of file apa.c.
 {
         memset(buffer, 0, 512);
         *(u32 *)buffer=err_lba;
         ata_device_sector_io(device, buffer, lba, 1, ATA_DIR_WRITE);
         ata_device_flush_cache(device);
 }
References ata_device_flush_cache(), ata_device_sector_io(), ATA_DIR_WRITE, buffer, and memset().
Referenced by apaCacheTransfer(), and apaSetPartErrorSector().
apaSetPartErrorSector()
void apaSetPartErrorSector (s32 device, u32 lba)
Definition at line 37 of file apa.c.
 {// used to set the lba of a partition that has a error...
         apa_cache_t *clink;
         clink=apaCacheAlloc();
         apaSaveError(device, clink->header, APA_SECTOR_PART_ERROR, lba);
         apaCacheFree(clink);
 }
References APA_SECTOR_PART_ERROR, apaCacheAlloc(), apaCacheFree(), apaSaveError(), and apa_cache_t::header.
Referenced by apaGetPartErrorName(), and hddIoctl2().
apaWriteHeader()
int apaWriteHeader (s32 device, apa_header_t * header, u32 lba)
Definition at line 430 of file apa.c.
 {
         if(ata_device_sector_io(device, header, lba, 2, ATA_DIR_WRITE))
                 return -EIO;
         return 0;
 }
References ata_device_sector_io(), ATA_DIR_WRITE, and EIO.
Referenced by apaCacheTransfer().