ps2sdk: iop/hdd/libpfs/src/cache.c File Reference
cache.c File Reference
#include <errno.h>
#include <stdio.h>
#include <sysclib.h>
#include <hdd-ioctl.h>
#include "pfs-opt.h"
#include "libpfs.h"
Functions
void pfsCacheFree (pfs_cache_t *clink)
void pfsCacheLink (pfs_cache_t *clink, pfs_cache_t *cnew)
pfs_cache_t * pfsCacheUnLink (pfs_cache_t *clink)
pfs_cache_t * pfsCacheUsedAdd (pfs_cache_t *clink)
int pfsCacheTransfer (pfs_cache_t *clink, int mode)
void pfsCacheFlushAllDirty (pfs_mount_t *pfsMount)
pfs_cache_t * pfsCacheAlloc (pfs_mount_t *pfsMount, u16 sub, u32 block, int flags, int *result)
pfs_cache_t * pfsCacheGetData (pfs_mount_t *pfsMount, u16 sub, u32 block, int flags, int *result)
pfs_cache_t * pfsCacheAllocClean (int *result)
int pfsCacheIsFull (void)
int pfsCacheInit (u32 numBuf, u32 bufSize)
void pfsCacheClose (pfs_mount_t *pfsMount)
void pfsCacheMarkClean (pfs_mount_t *pfsMount, u32 subpart, u32 blockStart, u32 blockEnd)
Variables
u32 pfsBlockSize
pfs_cache_t * pfsCacheBuf
u32 pfsCacheNumBuffers
Function Documentation
pfsCacheAlloc()
pfs_cache_t* pfsCacheAlloc (pfs_mount_t * pfsMount, u16 sub, u32 block, int flags, int * result)
Definition at line 132 of file cache.c.
 {
         pfs_cache_t *allocated;
         if (pfsCacheBuf->prev==pfsCacheBuf && pfsCacheBuf->prev->next==pfsCacheBuf->prev) {
                 PFS_PRINTF(PFS_DRV_NAME": Error: Free buffer list is empty\n");
                 *result=-ENOMEM;
                 return NULL;
         }
         allocated=pfsCacheBuf->next;
         if (pfsCacheBuf->next==NULL)
                 PFS_PRINTF(PFS_DRV_NAME": Panic: Null pointer allocated\n");
         if (allocated->pfsMount && (allocated->flags & PFS_CACHE_FLAG_DIRTY))
                 pfsCacheFlushAllDirty(allocated->pfsMount);
         allocated->flags        = flags & PFS_CACHE_FLAG_MASKTYPE;
         allocated->pfsMount     = pfsMount;
         allocated->sub          = sub;
         allocated->block        = block;
         allocated->nused        = 1;
         return pfsCacheUnLink(allocated);
 }
References pfs_cache_t::block, ENOMEM, pfs_cache_t::flags, pfs_cache_t::next, NULL, pfs_cache_t::nused, PFS_CACHE_FLAG_DIRTY, PFS_CACHE_FLAG_MASKTYPE, PFS_DRV_NAME, PFS_PRINTF, pfsCacheBuf, pfsCacheFlushAllDirty(), pfsCacheUnLink(), pfs_cache_t::pfsMount, pfs_cache_t::prev, result, and pfs_cache_t::sub.
Referenced by pfsCacheAllocClean(), and pfsCacheGetData().
pfsCacheAllocClean()
pfs_cache_t* pfsCacheAllocClean (int * result)
Definition at line 191 of file cache.c.
 {
         *result = 0;
         return pfsCacheAlloc(NULL, 0, 0, 0, result);
 }
References NULL, pfsCacheAlloc(), and result.
Referenced by devctlFsckStat(), pfsFormat(), pfsFormatSub(), pfsJournalRestore(), and pfsMountSuperBlock().
pfsCacheClose()
void pfsCacheClose (pfs_mount_t * pfsMount)
Definition at line 235 of file cache.c.
 {
         unsigned int i;
         pfsCacheFlushAllDirty(pfsMount);
         for(i=1; i < pfsCacheNumBuffers+1;i++){
                 if(pfsCacheBuf[i].pfsMount==pfsMount)
                         pfsCacheBuf[i].pfsMount=NULL;
         }
 }
References NULL, pfsCacheBuf, pfsCacheFlushAllDirty(), pfsCacheNumBuffers, and pfs_cache_t::pfsMount.
Referenced by pfsFioUmount().
pfsCacheFlushAllDirty()
void pfsCacheFlushAllDirty (pfs_mount_t * pfsMount)
Definition at line 110 of file cache.c.
 {
         u32 i;
         int found=0;
         for(i=1;i<pfsCacheNumBuffers+1;i++){
                 if(pfsCacheBuf[i].pfsMount == pfsMount &&
                         pfsCacheBuf[i].flags & PFS_CACHE_FLAG_DIRTY)
                                 found=1;
         }
         if(found) {
                 pfsJournalWrite(pfsMount, pfsCacheBuf+1, pfsCacheNumBuffers);
                 for(i=1;i<pfsCacheNumBuffers+1;i++){
                         if(pfsCacheBuf[i].pfsMount == pfsMount &&
                                 pfsCacheBuf[i].flags & PFS_CACHE_FLAG_DIRTY)
                                         pfsCacheTransfer(&pfsCacheBuf[i], 1);
                 }
         }
         pfsJournalReset(pfsMount);
 }
References PFS_CACHE_FLAG_DIRTY, pfsCacheBuf, pfsCacheNumBuffers, pfsCacheTransfer(), pfsJournalReset(), and pfsJournalWrite().
Referenced by openFile(), pfsCacheAlloc(), pfsCacheClose(), pfsFioChstat(), pfsFioCloseFileSlot(), pfsFioDevctlCloseAll(), pfsFioIoctl2(), pfsFioRename(), pfsFioSync(), pfsFioWrite(), and pfsInodeRemove().
pfsCacheFree()
void pfsCacheFree (pfs_cache_t * clink)
Definition at line 30 of file cache.c.
 {
         if(clink==NULL) {
                 PFS_PRINTF(PFS_DRV_NAME": Warning: NULL buffer returned\n");
                 return;
         }
         if(clink->nused==0){
                 PFS_PRINTF(PFS_DRV_NAME": Error: Unused cache returned\n");
                 return;
         }
         clink->nused--;
         if(clink->pfsMount!=NULL) {
                 if(clink->nused!=0)
                         return;
                 pfsCacheLink(pfsCacheBuf->prev, clink);
                 return;
         }
         if(clink->nused!=0) {
                 PFS_PRINTF(PFS_DRV_NAME": Warning: Invalidated buffer is in use\n");
                 return;
         }
         pfsCacheLink(pfsCacheBuf, clink);
 }
References NULL, pfs_cache_t::nused, PFS_DRV_NAME, PFS_PRINTF, pfsCacheBuf, pfsCacheLink(), pfs_cache_t::pfsMount, and pfs_cache_t::prev.
Referenced by _remove(), _seek(), devctlFsckStat(), ioctl2Attr(), openFile(), pfsAllocZones(), pfsBitmapAllocateAdditionalZones(), pfsBitmapAllocFree(), pfsBitmapAllocZones(), pfsBitmapCalcFreeZones(), pfsBitmapFreeInodeBlocks(), pfsBitmapShow(), pfsBlockAllocNewSegment(), pfsBlockGetNextSegment(), pfsBlockSeekNextSegment(), pfsCacheGetData(), pfsCheckDirForFiles(), pfsFioChdir(), pfsFioChstat(), pfsFioCloseFileSlot(), pfsFioDread(), pfsFioGetstat(), pfsFioReadlink(), pfsFioRename(), pfsFormat(), pfsFormatSub(), pfsFreeZones(), pfsGetDentriesAtPos(), pfsGetDentry(), pfsGetNextDentry(), pfsInodeCreate(), pfsInodeGetFile(), pfsInodeGetFileInDir(), pfsInodeGetParent(), pfsInodeRemove(), pfsJournalRestore(), and pfsMountSuperBlock().
pfsCacheGetData()
pfs_cache_t* pfsCacheGetData (pfs_mount_t * pfsMount, u16 sub, u32 block, int flags, int * result)
Definition at line 155 of file cache.c.
 {
         u32 i;
         pfs_cache_t *clink;
         *result=0;
         for (i=1; i < pfsCacheNumBuffers + 1; i++)
                 if ( pfsCacheBuf[i].pfsMount &&
                     (pfsCacheBuf[i].pfsMount==pfsMount) &&
                     (pfsCacheBuf[i].block  == block))
                         if (pfsCacheBuf[i].sub==sub){
                                 pfsCacheBuf[i].flags &= PFS_CACHE_FLAG_MASKSTATUS;
                                 pfsCacheBuf[i].flags |= flags & PFS_CACHE_FLAG_MASKTYPE;
                                 if (pfsCacheBuf[i].nused == 0)
                                         pfsCacheUnLink(&pfsCacheBuf[i]);
                                 pfsCacheBuf[i].nused++;
                                 return &pfsCacheBuf[i];
                         }
         clink=pfsCacheAlloc(pfsMount, sub, block, flags, result);
         if (clink){
                 if (flags & PFS_CACHE_FLAG_NOLOAD)
                         return clink;
                 if ((*result=pfsCacheTransfer(clink, PFS_IO_MODE_READ))>=0)
                         return clink;
                 clink->pfsMount=NULL;
                 pfsCacheFree(clink);
         }
         return NULL;
 }
References pfs_cache_t::flags, NULL, pfs_cache_t::nused, PFS_CACHE_FLAG_MASKSTATUS, PFS_CACHE_FLAG_MASKTYPE, PFS_CACHE_FLAG_NOLOAD, PFS_IO_MODE_READ, pfsCacheAlloc(), pfsCacheBuf, pfsCacheFree(), pfsCacheNumBuffers, pfsCacheTransfer(), pfsCacheUnLink(), pfs_cache_t::pfsMount, and result.
Referenced by ioctl2Attr(), openFile(), pfsBitmapAllocateAdditionalZones(), pfsBitmapAllocFree(), pfsBitmapAllocZones(), pfsBitmapCalcFreeZones(), pfsBitmapFreeBlockSegment(), pfsBitmapShow(), pfsBlockAllocNewSegment(), pfsBlockGetLastSegmentDescriptorInode(), pfsBlockGetNextSegment(), pfsGetDentriesChunk(), pfsInodeCreate(), and pfsInodeGetData().
pfsCacheInit()
int pfsCacheInit (u32 numBuf, u32 bufSize)
Definition at line 204 of file cache.c.
 {
         char *cacheData;
         u32 i;
         if(numBuf > 127) {
                 PFS_PRINTF(PFS_DRV_NAME": Error: Number of buffers larger than 127.\n");
                 return -EINVAL;
         }
         cacheData = pfsAllocMem(numBuf * bufSize);
         if(!cacheData || !(pfsCacheBuf = pfsAllocMem((numBuf + 1) * sizeof(pfs_cache_t))))
                 return -ENOMEM;
         pfsCacheNumBuffers = numBuf;
         memset(pfsCacheBuf, 0, (numBuf + 1) * sizeof(pfs_cache_t));
         pfsCacheBuf->next = pfsCacheBuf;
         pfsCacheBuf->prev = pfsCacheBuf;
         for(i = 1; i < numBuf + 1; i++)
         {
                 pfsCacheBuf[i].u.data = cacheData;
                 pfsCacheLink(pfsCacheBuf->prev, &pfsCacheBuf[i]);
                 cacheData += bufSize;
         }
         return 0;
 }
References pfs_cache_t::data, EINVAL, ENOMEM, memset(), pfs_cache_t::next, PFS_DRV_NAME, PFS_PRINTF, pfsAllocMem(), pfsCacheBuf, pfsCacheLink(), pfsCacheNumBuffers, pfs_cache_t::prev, and pfs_cache_t::u.
Referenced by _start().
pfsCacheIsFull()
int pfsCacheIsFull (void)
Definition at line 198 of file cache.c.
 {
         if (pfsCacheBuf->prev != pfsCacheBuf)   return 0;
         return pfsCacheBuf->prev->next == pfsCacheBuf->prev;
 }
References pfsCacheBuf, and pfs_cache_t::prev.
Referenced by pfsBlockAllocNewSegment().
pfsCacheLink()
void pfsCacheLink (pfs_cache_t * clink, pfs_cache_t * cnew)
Definition at line 56 of file cache.c.
 {
         cnew->prev=clink;
         cnew->next=clink->next;
         clink->next->prev=cnew;
         clink->next=cnew;
 }
References pfs_cache_t::next, and pfs_cache_t::prev.
Referenced by pfsCacheFree(), and pfsCacheInit().
pfsCacheMarkClean()
void pfsCacheMarkClean (pfs_mount_t * pfsMount, u32 subpart, u32 blockStart, u32 blockEnd)
Definition at line 246 of file cache.c.
 {
         u32 i;
         for(i=1; i< pfsCacheNumBuffers+1;i++){
                 if(pfsCacheBuf[i].pfsMount==pfsMount && pfsCacheBuf[i].sub==subpart) {
                         if(pfsCacheBuf[i].block >= blockStart && pfsCacheBuf[i].block < blockEnd)
                                 pfsCacheBuf[i].flags&=~PFS_CACHE_FLAG_DIRTY;
                 }
         }
 }
References pfs_cache_t::flags, PFS_CACHE_FLAG_DIRTY, pfsCacheBuf, and pfsCacheNumBuffers.
Referenced by pfsBitmapFreeInodeBlocks(), and pfsFreeZones().
pfsCacheTransfer()
int pfsCacheTransfer (pfs_cache_t * clink, int mode)
Definition at line 77 of file cache.c.
 {
         pfs_mount_t *pfsMount=clink->pfsMount;
         int err;
         if(pfsMount->lastError == 0) {  // no error
                 if((err=pfsMount->blockDev->transfer(pfsMount->fd, clink->u.data, clink->sub,
                         clink->block << pfsBlockSize, 1 << pfsBlockSize, mode))==0) {
                         if(mode==PFS_IO_MODE_READ) {
                                 if(clink->flags & PFS_CACHE_FLAG_SEGD && ((pfs_inode_t *)clink->u.inode)->magic!=PFS_SEGD_MAGIC)
                                         err=-EIO;
                                 if(clink->flags & PFS_CACHE_FLAG_SEGI && ((pfs_inode_t *)clink->u.inode)->magic!=PFS_SEGI_MAGIC)
                                         err=-EIO;
                                 if(clink->flags & (PFS_CACHE_FLAG_SEGD|PFS_CACHE_FLAG_SEGI)) {
                                         if(((pfs_inode_t *)clink->u.inode)->checksum!=pfsInodeCheckSum(clink->u.inode))
                                                 err=-EIO;
                                 }
                         }
                 }
                 if(err!=0) {
                         PFS_PRINTF(PFS_DRV_NAME": Error: Disk error partition %ld, block %ld, err %d\n",
                                 clink->sub, clink->block, err);
 #ifndef PFS_NO_WRITE_ERROR_STAT
                         pfsMount->blockDev->setPartitionError(pfsMount->fd);
                         pfsFsckStat(pfsMount, clink->u.superblock, PFS_FSCK_STAT_WRITE_ERROR, PFS_MODE_SET_FLAG);
                         pfsMount->lastError=err;
 #endif
                 }
         }
         clink->flags&=~PFS_CACHE_FLAG_DIRTY; // clear dirty :)
         return pfsMount->lastError;
 }
References pfs_cache_t::block, pfs_mount_t::blockDev, pfs_cache_t::data, EIO, pfs_mount_t::fd, pfs_cache_t::flags, pfs_cache_t::inode, pfs_mount_t::lastError, PFS_CACHE_FLAG_DIRTY, PFS_CACHE_FLAG_SEGD, PFS_CACHE_FLAG_SEGI, PFS_DRV_NAME, PFS_FSCK_STAT_WRITE_ERROR, PFS_IO_MODE_READ, PFS_MODE_SET_FLAG, PFS_PRINTF, PFS_SEGD_MAGIC, PFS_SEGI_MAGIC, pfsBlockSize, pfsFsckStat(), pfsInodeCheckSum(), pfs_cache_t::pfsMount, pfs_block_device_t::setPartitionError, pfs_cache_t::sub, pfs_cache_t::superblock, pfs_block_device_t::transfer, and pfs_cache_t::u.
Referenced by pfsCacheFlushAllDirty(), and pfsCacheGetData().
pfsCacheUnLink()
pfs_cache_t* pfsCacheUnLink (pfs_cache_t * clink)
Definition at line 64 of file cache.c.
 {
         clink->prev->next=clink->next;
         clink->next->prev=clink->prev;
         return clink;
 }
References pfs_cache_t::next, and pfs_cache_t::prev.
Referenced by pfsCacheAlloc(), and pfsCacheGetData().
pfsCacheUsedAdd()
pfs_cache_t* pfsCacheUsedAdd (pfs_cache_t * clink)
Definition at line 71 of file cache.c.
 {
         clink->nused++;
         return clink;
 }
References pfs_cache_t::nused.
Referenced by pfsBitmapFreeInodeBlocks(), pfsBlockInitPos(), pfsBlockSeekNextSegment(), pfsFioRename(), pfsFreeZones(), pfsGetDentry(), and pfsInodeGetFileInDir().
Variable Documentation
pfsBlockSize
u32 pfsBlockSize extern
Definition at line 25 of file super.c.
Referenced by pfsCacheTransfer().
pfsCacheBuf
pfs_cache_t* pfsCacheBuf
Definition at line 27 of file cache.c.
Referenced by pfsCacheAlloc(), pfsCacheClose(), pfsCacheFlushAllDirty(), pfsCacheFree(), pfsCacheGetData(), pfsCacheInit(), pfsCacheIsFull(), and pfsCacheMarkClean().
pfsCacheNumBuffers
u32 pfsCacheNumBuffers
Definition at line 28 of file cache.c.
Referenced by pfsCacheClose(), pfsCacheFlushAllDirty(), pfsCacheGetData(), pfsCacheInit(), pfsCacheMarkClean(), and pfsJournalWrite().