ps2sdk: iop/hdd/libpfs/src/misc.c File Reference
misc.c File Reference
#include <errno.h>
#include <stdio.h>
#include <iomanX.h>
#include <intrman.h>
#include <sysmem.h>
#include <sysclib.h>
#include <thbase.h>
#include <cdvdman.h>
#include <ctype.h>
#include <hdd-ioctl.h>
#include "pfs-opt.h"
#include "libpfs.h"
Macros
#define NUM_SUPPORTED_DEVICES 1
Functions
void * pfsAllocMem (int size)
void pfsFreeMem (void *buffer)
int pfsGetTime (pfs_datetime_t *tm)
int pfsFsckStat (pfs_mount_t *pfsMount, pfs_super_block_t *superblock, u32 stat, int mode)
void pfsPrintBitmap (const u32 *bitmap)
u32 pfsGetScale (u32 num, u32 size)
u32 pfsFixIndex (u32 index)
static int pfsHddTransfer (int fd, void *buffer, u32 sub, u32 sector, u32 size, u32 mode)
static u32 pfsHddGetSubCount (int fd)
static u32 pfsHddGetPartSize (int fd, u32 sub)
static void pfsHddSetPartError (int fd)
static int pfsHddFlushCache (int fd)
pfs_block_device_t * pfsGetBlockDeviceTable (const char *name)
Variables
pfs_block_device_t pfsBlockDeviceCallTable [NUM_SUPPORTED_DEVICES]
Macro Definition Documentation
NUM_SUPPORTED_DEVICES
#define NUM_SUPPORTED_DEVICES 1
Definition at line 184 of file misc.c.
Function Documentation
pfsAllocMem()
void* pfsAllocMem (int size)
Definition at line 36 of file misc.c.
 {
 #ifdef _IOP
         int intrStat;
         void *mem;
         CpuSuspendIntr(&intrStat);
         mem = AllocSysMemory(ALLOC_FIRST, size, NULL);
         CpuResumeIntr(intrStat);
         return mem;
 #else
         return malloc(size);
 #endif
 }
References ALLOC_FIRST, AllocSysMemory(), CpuResumeIntr(), CpuSuspendIntr(), malloc, and NULL.
Referenced by _start(), allocateMountBuffer(), and pfsCacheInit().
pfsFixIndex()
u32 pfsFixIndex (u32 index)
Definition at line 165 of file misc.c.
 {
         if(index < PFS_INODE_MAX_BLOCKS)
                 return index;
         index -= PFS_INODE_MAX_BLOCKS;
         return index % 123;
 }
References index(), and PFS_INODE_MAX_BLOCKS.
Referenced by pfsBitmapFreeInodeBlocks(), pfsBlockAllocNewSegment(), pfsBlockExpandSegment(), pfsBlockGetCurrent(), pfsBlockSeekNextSegment(), pfsFreeZones(), pfsGetDentriesChunk(), and pfsInodeSync().
pfsFreeMem()
void pfsFreeMem (void * buffer)
Definition at line 52 of file misc.c.
 {
 #ifdef _IOP
         int OldState;
         CpuSuspendIntr(&OldState);
         FreeSysMemory(buffer);
         CpuResumeIntr(OldState);
 #else
         free(buffer);
 #endif
 }
References buffer, CpuResumeIntr(), CpuSuspendIntr(), free, and FreeSysMemory().
pfsFsckStat()
int pfsFsckStat (pfs_mount_t * pfsMount, pfs_super_block_t * superblock, u32 stat, int mode)
Definition at line 112 of file misc.c.
 {       // mode 0=set flag, 1=remove flag, else check stat
         if(pfsMount->blockDev->transfer(pfsMount->fd, superblock, 0, PFS_SUPER_SECTOR, 1,
                 PFS_IO_MODE_READ)==0)
         {
                 switch(mode)
                 {
                         case PFS_MODE_SET_FLAG:
                                 superblock->pfsFsckStat|=stat;
                                 break;
                         case PFS_MODE_REMOVE_FLAG:
                                 superblock->pfsFsckStat&=~stat;
                                 break;
                         default/*PFS_MODE_CHECK_FLAG*/:
                                 return 0 < (superblock->pfsFsckStat & stat);
                 }
                 pfsMount->blockDev->transfer(pfsMount->fd, superblock, 0, PFS_SUPER_SECTOR, 1,
                         PFS_IO_MODE_WRITE);
                 pfsMount->blockDev->flushCache(pfsMount->fd);
         }
         return 0;
 }
References pfs_mount_t::blockDev, pfs_mount_t::fd, pfs_block_device_t::flushCache, PFS_IO_MODE_READ, PFS_IO_MODE_WRITE, PFS_MODE_REMOVE_FLAG, PFS_MODE_SET_FLAG, PFS_SUPER_SECTOR, pfs_super_block_t::pfsFsckStat, and pfs_block_device_t::transfer.
Referenced by devctlFsckStat(), and pfsCacheTransfer().
pfsGetBlockDeviceTable()
pfs_block_device_t* pfsGetBlockDeviceTable (const char * name)
Definition at line 196 of file misc.c.
 {
         char *end;
         char devname[32];
         char *tmp;
         u32 len;
         int i;
         while(name[0] == ' ')
                 name++;
         end = strchr(name, ':');
         if(!end) {
                 PFS_PRINTF(PFS_DRV_NAME": Error: Unknown block device '%s'\n", name);
                 return NULL;
         }
         len = (u32)end - (u32)name;
         strncpy(devname, name, len);
         devname[len] = '\0';
         // Loop until digit is found, then terminate string at that digit.
         // Should then have just the device name left, minus any front spaces or trailing digits.
         tmp = devname;
         while(!(isdigit(tmp[0])))
                 tmp++;
         tmp[0] = '\0';
         for(i = 0; i < NUM_SUPPORTED_DEVICES; i++)
                 if(!strcmp(pfsBlockDeviceCallTable[i].devName, devname))
                         return &pfsBlockDeviceCallTable[i];
         return NULL;
 }
References isdigit, NULL, NUM_SUPPORTED_DEVICES, PFS_DRV_NAME, PFS_PRINTF, pfsBlockDeviceCallTable, strchr(), strcmp(), and strncpy().
Referenced by pfsFioFormat(), and pfsFioMount().
pfsGetScale()
u32 pfsGetScale (u32 num, u32 size)
Definition at line 155 of file misc.c.
 {
         u32 scale = 0;
         while((size << scale) != num)
                 scale++;
         return scale;
 }
Referenced by pfsFormat(), pfsMountSuperBlock(), and pfsUpdateSuperBlock().
pfsGetTime()
int pfsGetTime (pfs_datetime_t * tm)
Definition at line 65 of file misc.c.
 {
 #ifdef _IOP
         int ret, i;
         sceCdCLOCK      cdtime;
         static pfs_datetime_t timeBuf={
                 0, 7, 6, 5, 4, 3, 2000  // used if can not get time...
         };
         for(i = 0; i < 20; i++)
         {
                 ret = sceCdReadClock(&cdtime);
                 if(ret!=0 && cdtime.stat==0)
                 {
                         timeBuf.sec=btoi(cdtime.second);
                         timeBuf.min=btoi(cdtime.minute);
                         timeBuf.hour=btoi(cdtime.hour);
                         timeBuf.day=btoi(cdtime.day);
                         timeBuf.month=btoi(cdtime.month & 0x7F);        //The old CDVDMAN sceCdReadClock() function does not automatically file off the highest bit.
                         timeBuf.year=btoi(cdtime.year) + 2000;
                         break;
                 } else {
                         if(!(cdtime.stat & 0x80))
                                 break;
                 }
                 DelayThread(100000);
         }
         memcpy(tm, &timeBuf, sizeof(pfs_datetime_t));
 #else
         time_t rawtime;
         struct tm * timeinfo;
         time (&rawtime);
         timeinfo=localtime (&rawtime);
         tm->sec=timeinfo->tm_sec;
         tm->min=timeinfo->tm_min;
         tm->hour=timeinfo->tm_hour;
         tm->day=timeinfo->tm_mday;
         tm->month=timeinfo->tm_mon;
         tm->year=timeinfo->tm_year+1900;
 #endif
         return 0;
 }
References btoi, sceCdCLOCK::day, pfs_datetime_t::day, DelayThread(), sceCdCLOCK::hour, pfs_datetime_t::hour, memcpy(), pfs_datetime_t::min, sceCdCLOCK::minute, sceCdCLOCK::month, pfs_datetime_t::month, sceCdReadClock(), pfs_datetime_t::sec, sceCdCLOCK::second, sceCdCLOCK::stat, sceCdCLOCK::year, and pfs_datetime_t::year.
Referenced by pfsInodeFill(), and pfsInodeSetTime().
pfsHddFlushCache()
static int pfsHddFlushCache (int fd) static
Definition at line 260 of file misc.c.
 {
         return ioctl2(fd,HIOCFLUSH, NULL, 0, NULL, 0);
 }
References HIOCFLUSH, ioctl2(), and NULL.
pfsHddGetPartSize()
static u32 pfsHddGetPartSize (int fd, u32 sub) static
Definition at line 250 of file misc.c.
 {       // of a partition
         return ioctl2(fd, HIOCGETSIZE, &sub, 0, NULL, 0);
 }
References HIOCGETSIZE, ioctl2(), and NULL.
pfsHddGetSubCount()
static u32 pfsHddGetSubCount (int fd) static
Definition at line 245 of file misc.c.
 {
         return ioctl2(fd, HIOCNSUB, NULL, 0, NULL, 0);
 }
References HIOCNSUB, ioctl2(), and NULL.
pfsHddSetPartError()
static void pfsHddSetPartError (int fd) static
Definition at line 255 of file misc.c.
 {
         ioctl2(fd, HIOCSETPARTERROR, NULL, 0, NULL, 0);
 }
References HIOCSETPARTERROR, ioctl2(), and NULL.
pfsHddTransfer()
static int pfsHddTransfer (int fd, void * buffer, u32 sub, u32 sector, u32 size, u32 mode) static
Definition at line 231 of file misc.c.
 {
         hddIoctl2Transfer_t t;
         t.sub=sub;
         t.sector=sector;
         t.size=size;
         t.mode=mode;
         t.buffer=buffer;
         return ioctl2(fd, HIOCTRANSFER, &t, 0, NULL, 0);
 }
References hddIoctl2Transfer_t::buffer, buffer, HIOCTRANSFER, ioctl2(), hddIoctl2Transfer_t::mode, NULL, hddIoctl2Transfer_t::sector, hddIoctl2Transfer_t::size, and hddIoctl2Transfer_t::sub.
pfsPrintBitmap()
void pfsPrintBitmap (const u32 * bitmap)
Definition at line 137 of file misc.c.
{
         u32 i, j;
         char a[48+1], b[16+1];
         b[16]=0;
         for (i=0; i < 32; i++){
                 memset(a, 0, 49);
                 for (j=0; j < 16; j++){
                         const char *c=(const char*)bitmap+j+i*16;
                         sprintf(a+j*3, "%02x ", *c);
                         b[j] = ((*c>=0) && (isgraph(*c))) ?
                                 *c : '.';
                 }
                 PFS_PRINTF("%s%s\n", a, b);
         }
 }
References isgraph, memset(), PFS_PRINTF, and sprintf().
Referenced by pfsBitmapShow().
Variable Documentation
pfsBlockDeviceCallTable
pfs_block_device_t pfsBlockDeviceCallTable[NUM_SUPPORTED_DEVICES]
Initial value:
= {
        {
                "hdd",
                &pfsHddTransfer,
                &pfsHddGetSubCount,
                &pfsHddGetPartSize,
                &pfsHddSetPartError,
                &pfsHddFlushCache,
        }
}
Definition at line 185 of file misc.c.
Referenced by pfsGetBlockDeviceTable().