ps2sdk: iop/hdd/libpfs/include/libpfs.h File Reference
libpfs.h File Reference
#include <types.h>
Data Structures
struct pfs_journal_t
struct pfs_aentry_t
struct pfs_dentry_t
struct pfs_blockinfo_t
struct pfs_datetime_t
struct pfs_super_block_t
struct pfs_inode_t
struct pfs_block_device_t
struct pfs_mount_t
struct pfs_cache_t
struct pfs_blockpos_t
struct pfs_bitmapInfo_t
Macros
#define PFS_BLOCKSIZE 0x2000
#define PFS_SUPER_MAGIC 0x50465300
#define PFS_JOUNRNAL_MAGIC 0x5046534C
#define PFS_SEGD_MAGIC 0x53454744
#define PFS_SEGI_MAGIC 0x53454749
#define PFS_MAX_SUBPARTS 64
#define PFS_NAME_LEN 255
#define PFS_FORMAT_VERSION 3
#define PFS_INODE_MAX_BLOCKS 114
#define PFS_FIO_ATTR_READABLE 0x0001
#define PFS_FIO_ATTR_WRITEABLE 0x0002
#define PFS_FIO_ATTR_EXECUTABLE 0x0004
#define PFS_FIO_ATTR_COPYPROTECT 0x0008
#define PFS_FIO_ATTR_UNK0010 0x0010
#define PFS_FIO_ATTR_SUBDIR 0x0020
#define PFS_FIO_ATTR_UNK0040 0x0040
#define PFS_FIO_ATTR_CLOSED 0x0080
#define PFS_FIO_ATTR_UNK0100 0x0100
#define PFS_FIO_ATTR_UNK0200 0x0200
#define PFS_FIO_ATTR_UNK0400 0x0400
#define PFS_FIO_ATTR_PDA 0x0800
#define PFS_FIO_ATTR_PSX 0x1000
#define PFS_FIO_ATTR_UNK2000 0x2000
#define PFS_FIO_ATTR_HIDDEN 0x4000
#define PFS_CACHE_FLAG_DIRTY 0x01
#define PFS_CACHE_FLAG_NOLOAD 0x02
#define PFS_CACHE_FLAG_MASKSTATUS 0x0F
#define PFS_CACHE_FLAG_NOTHING 0x00
#define PFS_CACHE_FLAG_SEGD 0x10
#define PFS_CACHE_FLAG_SEGI 0x20
#define PFS_CACHE_FLAG_BITMAP 0x40
#define PFS_CACHE_FLAG_MASKTYPE 0xF0
#define PFS_FSCK_STAT_OK 0x00
#define PFS_FSCK_STAT_WRITE_ERROR 0x01
#define PFS_FSCK_STAT_ERRORS_FIXED 0x02
#define PFS_MODE_SET_FLAG 0x00
#define PFS_MODE_REMOVE_FLAG 0x01
#define PFS_MODE_CHECK_FLAG 0x02
#define PFS_UID 0xFFFF
#define PFS_GID 0xFFFF
#define PFS_SUPER_SECTOR 8192
#define PFS_SUPER_BACKUP_SECTOR 8193
#define PFS_BITMAP_ALLOC 0
#define PFS_BITMAP_FREE 1
Functions
int pfsCheckZoneSize (u32 zone_size)
u32 pfsGetBitmapSizeSectors (int zoneScale, u32 partSize)
u32 pfsGetBitmapSizeBlocks (int scale, u32 mainsize)
int pfsFormatSub (pfs_block_device_t *blockDev, int fd, u32 sub, u32 reserved, u32 scale, u32 fragment)
int pfsFormat (pfs_block_device_t *blockDev, int fd, int zonesize, int fragment)
int pfsUpdateSuperBlock (pfs_mount_t *pfsMount, pfs_super_block_t *superblock, u32 sub)
int pfsMountSuperBlock (pfs_mount_t *pfsMount)
void pfsCacheFree (pfs_cache_t *clink)
void pfsCacheLink (pfs_cache_t *clink, pfs_cache_t *cnew)
pfs_cache_t * pfsCacheUnLink (pfs_cache_t *clink)
pfs_cache_t * pfsCacheUsedAdd (pfs_cache_t *clink)
int pfsCacheTransfer (pfs_cache_t *clink, int mode)
void pfsCacheFlushAllDirty (pfs_mount_t *pfsMount)
pfs_cache_t * pfsCacheAlloc (pfs_mount_t *pfsMount, u16 sub, u32 block, int flags, int *result)
pfs_cache_t * pfsCacheGetData (pfs_mount_t *pfsMount, u16 sub, u32 block, int flags, int *result)
pfs_cache_t * pfsCacheAllocClean (int *result)
int pfsCacheIsFull (void)
int pfsCacheInit (u32 numBuf, u32 bufSize)
void pfsCacheClose (pfs_mount_t *pfsMount)
void pfsCacheMarkClean (pfs_mount_t *pfsMount, u32 subpart, u32 blockStart, u32 blockEnd)
void pfsBitmapSetupInfo (pfs_mount_t *pfsMount, pfs_bitmapInfo_t *info, u32 subpart, u32 number)
void pfsBitmapAllocFree (pfs_cache_t *clink, u32 operation, u32 subpart, u32 chunk, u32 index, u32 _bit, u32 count)
int pfsBitmapAllocateAdditionalZones (pfs_mount_t *pfsMount, pfs_blockinfo_t *bi, u32 count)
int pfsBitmapAllocZones (pfs_mount_t *pfsMount, pfs_blockinfo_t *bi, u32 amount)
int pfsBitmapSearchFreeZone (pfs_mount_t *pfsMount, pfs_blockinfo_t *bi, u32 max_count)
void pfsBitmapFreeBlockSegment (pfs_mount_t *pfsMount, pfs_blockinfo_t *bi)
int pfsBitmapCalcFreeZones (pfs_mount_t *pfsMount, int sub)
void pfsBitmapShow (pfs_mount_t *pfsMount)
void pfsBitmapFreeInodeBlocks (pfs_cache_t *clink)
int pfsBlockSeekNextSegment (pfs_cache_t *clink, pfs_blockpos_t *blockpos)
u32 pfsBlockSyncPos (pfs_blockpos_t *blockpos, u64 size)
int pfsBlockInitPos (pfs_cache_t *clink, pfs_blockpos_t *blockpos, u64 position)
int pfsBlockExpandSegment (pfs_cache_t *clink, pfs_blockpos_t *blockpos, u32 count)
int pfsBlockAllocNewSegment (pfs_cache_t *clink, pfs_blockpos_t *blockpos, u32 blocks)
pfs_blockinfo_t * pfsBlockGetCurrent (pfs_blockpos_t *blockpos)
pfs_cache_t * pfsBlockGetNextSegment (pfs_cache_t *clink, int *result)
pfs_cache_t * pfsBlockGetLastSegmentDescriptorInode (pfs_cache_t *clink, int *result)
pfs_cache_t * pfsGetDentry (pfs_cache_t *clink, char *path, pfs_dentry_t **dentry, u32 *size, int option)
int pfsGetNextDentry (pfs_cache_t *clink, pfs_blockpos_t *blockpos, u32 *position, char *name, pfs_blockinfo_t *bi)
pfs_cache_t * pfsFillDentry (pfs_cache_t *clink, pfs_dentry_t *dentry, char *path1, pfs_blockinfo_t *bi, u32 len, u16 mode)
pfs_cache_t * pfsDirAddEntry (pfs_cache_t *dir, char *filename, pfs_blockinfo_t *bi, u16 mode, int *result)
pfs_cache_t * pfsDirRemoveEntry (pfs_cache_t *clink, char *path)
int pfsCheckDirForFiles (pfs_cache_t *clink)
void pfsFillSelfAndParentDentries (pfs_cache_t *clink, pfs_blockinfo_t *self, pfs_blockinfo_t *parent)
pfs_cache_t * pfsSetDentryParent (pfs_cache_t *clink, pfs_blockinfo_t *bi, int *result)
pfs_cache_t * pfsInodeGetFileInDir (pfs_cache_t *dirInode, char *path, int *result)
pfs_cache_t * pfsInodeGetFile (pfs_mount_t *pfsMount, pfs_cache_t *clink, const char *name, int *result)
void pfsInodeFill (pfs_cache_t *ci, pfs_blockinfo_t *bi, u16 mode, u16 uid, u16 gid)
int pfsInodeRemove (pfs_cache_t *parent, pfs_cache_t *inode, char *path)
pfs_cache_t * pfsInodeGetParent (pfs_mount_t *pfsMount, pfs_cache_t *clink, const char *filename, char *path, int *result)
pfs_cache_t * pfsInodeCreate (pfs_cache_t *clink, u16 mode, u16 uid, u16 gid, int *result)
int pfsCheckAccess (pfs_cache_t *clink, int flags)
char * pfsSplitPath (char *filename, char *path, int *result)
u16 pfsGetMaxIndex (pfs_mount_t *pfsMount)
int pfsAllocZones (pfs_cache_t *clink, int msize, int mode)
void pfsFreeZones (pfs_cache_t *pfree)
void pfsInodePrint (pfs_inode_t *inode)
int pfsInodeCheckSum (pfs_inode_t *inode)
void pfsInodeSetTime (pfs_cache_t *clink)
void pfsInodeSetTimeParent (pfs_cache_t *parent, pfs_cache_t *self)
pfs_cache_t * pfsInodeGetData (pfs_mount_t *pfsMount, u16 sub, u32 inode, int *result)
int pfsInodeSync (pfs_blockpos_t *blockpos, u64 size, u32 used_segments)
pfs_cache_t * pfsGetDentriesChunk (pfs_blockpos_t *position, int *result)
pfs_cache_t * pfsGetDentriesAtPos (pfs_cache_t *clink, u64 position, int *offset, int *result)
int pfsJournalChecksum (void *header)
void pfsJournalWrite (pfs_mount_t *pfsMount, pfs_cache_t *clink, u32 pfsCacheNumBuffers)
int pfsJournalReset (pfs_mount_t *pfsMount)
int pfsJournalFlush (pfs_mount_t *pfsMount)
int pfsJournalRestore (pfs_mount_t *pfsMount)
int pfsJournalResetThis (pfs_block_device_t *blockDev, int fd, u32 sector)
int pfsFsckStat (pfs_mount_t *pfsMount, pfs_super_block_t *superblock, u32 stat, int mode)
void * pfsAllocMem (int size)
void pfsFreeMem (void *buffer)
int pfsGetTime (pfs_datetime_t *tm)
void pfsPrintBitmap (const u32 *bitmap)
pfs_block_device_t * pfsGetBlockDeviceTable (const char *name)
u32 pfsGetScale (u32 num, u32 size)
u32 pfsFixIndex (u32 index)
Macro Definition Documentation
PFS_BITMAP_ALLOC
#define PFS_BITMAP_ALLOC 0
Definition at line 249 of file libpfs.h.
PFS_BITMAP_FREE
#define PFS_BITMAP_FREE 1
Definition at line 250 of file libpfs.h.
PFS_BLOCKSIZE
#define PFS_BLOCKSIZE 0x2000
Definition at line 18 of file libpfs.h.
PFS_CACHE_FLAG_BITMAP
#define PFS_CACHE_FLAG_BITMAP 0x40
Definition at line 54 of file libpfs.h.
PFS_CACHE_FLAG_DIRTY
#define PFS_CACHE_FLAG_DIRTY 0x01
Definition at line 46 of file libpfs.h.
PFS_CACHE_FLAG_MASKSTATUS
#define PFS_CACHE_FLAG_MASKSTATUS 0x0F
Definition at line 48 of file libpfs.h.
PFS_CACHE_FLAG_MASKTYPE
#define PFS_CACHE_FLAG_MASKTYPE 0xF0
Definition at line 55 of file libpfs.h.
PFS_CACHE_FLAG_NOLOAD
#define PFS_CACHE_FLAG_NOLOAD 0x02
Definition at line 47 of file libpfs.h.
PFS_CACHE_FLAG_NOTHING
#define PFS_CACHE_FLAG_NOTHING 0x00
Definition at line 51 of file libpfs.h.
PFS_CACHE_FLAG_SEGD
#define PFS_CACHE_FLAG_SEGD 0x10
Definition at line 52 of file libpfs.h.
PFS_CACHE_FLAG_SEGI
#define PFS_CACHE_FLAG_SEGI 0x20
Definition at line 53 of file libpfs.h.
PFS_FIO_ATTR_CLOSED
#define PFS_FIO_ATTR_CLOSED 0x0080
Definition at line 36 of file libpfs.h.
PFS_FIO_ATTR_COPYPROTECT
#define PFS_FIO_ATTR_COPYPROTECT 0x0008
Definition at line 32 of file libpfs.h.
PFS_FIO_ATTR_EXECUTABLE
#define PFS_FIO_ATTR_EXECUTABLE 0x0004
Definition at line 31 of file libpfs.h.
PFS_FIO_ATTR_HIDDEN
#define PFS_FIO_ATTR_HIDDEN 0x4000
Definition at line 43 of file libpfs.h.
PFS_FIO_ATTR_PDA
#define PFS_FIO_ATTR_PDA 0x0800
Definition at line 40 of file libpfs.h.
PFS_FIO_ATTR_PSX
#define PFS_FIO_ATTR_PSX 0x1000
Definition at line 41 of file libpfs.h.
PFS_FIO_ATTR_READABLE
#define PFS_FIO_ATTR_READABLE 0x0001
Definition at line 29 of file libpfs.h.
PFS_FIO_ATTR_SUBDIR
#define PFS_FIO_ATTR_SUBDIR 0x0020
Definition at line 34 of file libpfs.h.
PFS_FIO_ATTR_UNK0010
#define PFS_FIO_ATTR_UNK0010 0x0010
Definition at line 33 of file libpfs.h.
PFS_FIO_ATTR_UNK0040
#define PFS_FIO_ATTR_UNK0040 0x0040
Definition at line 35 of file libpfs.h.
PFS_FIO_ATTR_UNK0100
#define PFS_FIO_ATTR_UNK0100 0x0100
Definition at line 37 of file libpfs.h.
PFS_FIO_ATTR_UNK0200
#define PFS_FIO_ATTR_UNK0200 0x0200
Definition at line 38 of file libpfs.h.
PFS_FIO_ATTR_UNK0400
#define PFS_FIO_ATTR_UNK0400 0x0400
Definition at line 39 of file libpfs.h.
PFS_FIO_ATTR_UNK2000
#define PFS_FIO_ATTR_UNK2000 0x2000
Definition at line 42 of file libpfs.h.
PFS_FIO_ATTR_WRITEABLE
#define PFS_FIO_ATTR_WRITEABLE 0x0002
Definition at line 30 of file libpfs.h.
PFS_FORMAT_VERSION
#define PFS_FORMAT_VERSION 3
Definition at line 25 of file libpfs.h.
PFS_FSCK_STAT_ERRORS_FIXED
#define PFS_FSCK_STAT_ERRORS_FIXED 0x02
Definition at line 60 of file libpfs.h.
PFS_FSCK_STAT_OK
#define PFS_FSCK_STAT_OK 0x00
Definition at line 58 of file libpfs.h.
PFS_FSCK_STAT_WRITE_ERROR
#define PFS_FSCK_STAT_WRITE_ERROR 0x01
Definition at line 59 of file libpfs.h.
PFS_GID
#define PFS_GID 0xFFFF
Definition at line 78 of file libpfs.h.
PFS_INODE_MAX_BLOCKS
#define PFS_INODE_MAX_BLOCKS 114
Definition at line 26 of file libpfs.h.
PFS_JOUNRNAL_MAGIC
#define PFS_JOUNRNAL_MAGIC 0x5046534C
Definition at line 20 of file libpfs.h.
PFS_MAX_SUBPARTS
#define PFS_MAX_SUBPARTS 64
Definition at line 23 of file libpfs.h.
PFS_MODE_CHECK_FLAG
#define PFS_MODE_CHECK_FLAG 0x02
Definition at line 65 of file libpfs.h.
PFS_MODE_REMOVE_FLAG
#define PFS_MODE_REMOVE_FLAG 0x01
Definition at line 64 of file libpfs.h.
PFS_MODE_SET_FLAG
#define PFS_MODE_SET_FLAG 0x00
Definition at line 63 of file libpfs.h.
PFS_NAME_LEN
#define PFS_NAME_LEN 255
Definition at line 24 of file libpfs.h.
PFS_SEGD_MAGIC
#define PFS_SEGD_MAGIC 0x53454744
Definition at line 21 of file libpfs.h.
PFS_SEGI_MAGIC
#define PFS_SEGI_MAGIC 0x53454749
Definition at line 22 of file libpfs.h.
PFS_SUPER_BACKUP_SECTOR
#define PFS_SUPER_BACKUP_SECTOR 8193
Definition at line 219 of file libpfs.h.
PFS_SUPER_MAGIC
#define PFS_SUPER_MAGIC 0x50465300
Definition at line 19 of file libpfs.h.
PFS_SUPER_SECTOR
#define PFS_SUPER_SECTOR 8192
Definition at line 218 of file libpfs.h.
PFS_UID
#define PFS_UID 0xFFFF
Definition at line 77 of file libpfs.h.
Function Documentation
pfsAllocMem()
void* pfsAllocMem (int size)
Definition at line 36 of file misc.c.
 {
 #ifdef _IOP
         int intrStat;
         void *mem;
         CpuSuspendIntr(&intrStat);
         mem = AllocSysMemory(ALLOC_FIRST, size, NULL);
         CpuResumeIntr(intrStat);
         return mem;
 #else
         return malloc(size);
 #endif
 }
References ALLOC_FIRST, AllocSysMemory(), CpuResumeIntr(), CpuSuspendIntr(), malloc, and NULL.
Referenced by _start(), allocateMountBuffer(), and pfsCacheInit().
pfsAllocZones()
int pfsAllocZones (pfs_cache_t * clink, int msize, int mode)
Definition at line 615 of file dir.c.
 {
         pfs_blockpos_t blockpos;
         int result=0;
         u32 val;
         int zsize;
         zsize=clink->pfsMount->zsize;
         val=((msize-1 + zsize) & (-zsize)) / zsize;
         if(mode==0)
                 if (((clink->u.inode->number_blocks-clink->u.inode->number_segdesg) *(u64)zsize)
                         >= (clink->u.inode->size + msize))
                         return 0;
         if((blockpos.inode = pfsBlockGetLastSegmentDescriptorInode(clink, &result)))
         {
                 blockpos.block_offset=blockpos.byte_offset=0;
                 blockpos.block_segment=clink->u.inode->number_data-1;
                 val-=pfsBlockExpandSegment(clink, &blockpos, val);
                 while (val && ((result=pfsBlockAllocNewSegment(clink, &blockpos, val))>=0)){
                         val-=result;
                         result=0;
                 }
                 pfsCacheFree(blockpos.inode);
         }
         return result;
 }
References pfs_blockpos_t::block_offset, pfs_blockpos_t::block_segment, pfs_blockpos_t::byte_offset, pfs_cache_t::inode, pfs_blockpos_t::inode, pfs_inode_t::number_blocks, pfs_inode_t::number_data, pfs_inode_t::number_segdesg, pfsBlockAllocNewSegment(), pfsBlockExpandSegment(), pfsBlockGetLastSegmentDescriptorInode(), pfsCacheFree(), pfs_cache_t::pfsMount, result, pfs_inode_t::size, pfs_cache_t::u, and pfs_mount_t::zsize.
Referenced by pfsDirAddEntry(), and pfsFioIoctl2().
pfsBitmapAllocateAdditionalZones()
int pfsBitmapAllocateAdditionalZones (pfs_mount_t * pfsMount, pfs_blockinfo_t * bi, u32 count)
Definition at line 87 of file bitmap.c.
 {
         int result;
         pfs_bitmapInfo_t info;
         pfs_cache_t *c;
         int res=0;
         u32 bitmapMax;
         u32 *bitmapWord, *bitmapEnd;
         pfsBitmapSetupInfo(pfsMount, &info, bi->subpart, bi->number+bi->count);
         // Make sure we're not trying to allocate more than is possible
         if ((u32)USHRT_MAX - bi->count < count)
                 count = USHRT_MAX - bi->count;
         // Loop over each bitmap chunk (each is 1024 bytes in size) until either we have allocated
         // the requested amount of blocks, or until we have run out of space on the current partition
         while ((((info.partitionRemainder==0) && (info.chunk < info.partitionChunks  )) ||
                 ((info.partitionRemainder!=0) && (info.chunk < info.partitionChunks+1))) && count)
         {
                 u32 sector=(1<<pfsMount->inode_scale) + info.chunk;
                 // if main partition, add offset (in units of blocks)
                 if (bi->subpart==0)
                         sector += 0x2000 >> pfsBlockSize;
                 // Read the bitmap chunk from the hdd
                 c=pfsCacheGetData(pfsMount, bi->subpart, sector, PFS_CACHE_FLAG_BITMAP, &result);
                 if (c==NULL)break;
                 // Loop over each 32-bit word in the current bitmap chunk until
                 // we find a used zone or we've allocated all the zones we need
                 bitmapMax = info.chunk==info.partitionChunks ? info.partitionRemainder / 8 : pfsMetaSize;
                 bitmapEnd = (u32*)&((u8*)c->u.bitmap)[bitmapMax];
                 for (bitmapWord=&c->u.bitmap[info.index]; (bitmapWord < bitmapEnd) && count;  bitmapWord++, info.bit=0)
                 {
                         // Loop over each of the 32 bits in the current word from the current bitmap chunk,
                         // trying to allocate the requested number of zones
                         for ( ; (info.bit < 32) && count; count--)
{
                                 // We only want to allocate a continuous area, so if we come
                                 // accross a used zone bail
                                 if (*bitmapWord & (1<<info.bit))
{
                                         pfsCacheFree(c);
                                         goto exit;
                                 }
                                 // If the current bit in the bitmap is marked as free, mark it was used
                                 res++;
                                 *bitmapWord |= 1<<info.bit;
                                 info.bit++;
                                 c->flags |= PFS_CACHE_FLAG_DIRTY;
                         }
                 }
                 pfsCacheFree(c);
                 info.index=0;
                 info.chunk++;
         }
 exit:
         // Adjust global free zone counts
         pfsMount->free_zone[bi->subpart]-=res;
         pfsMount->zfree-=res;
         return res;
 }
References pfs_cache_t::bitmap, pfs_blockinfo_t::count, pfs_cache_t::flags, pfs_mount_t::free_zone, pfs_mount_t::inode_scale, NULL, pfs_blockinfo_t::number, PFS_CACHE_FLAG_BITMAP, PFS_CACHE_FLAG_DIRTY, pfsBitmapSetupInfo(), pfsBlockSize, pfsCacheFree(), pfsCacheGetData(), pfsMetaSize, result, pfs_blockinfo_t::subpart, pfs_cache_t::u, USHRT_MAX, and pfs_mount_t::zfree.
Referenced by pfsBlockExpandSegment().
pfsBitmapAllocFree()
void pfsBitmapAllocFree (pfs_cache_t * clink, u32 operation, u32 subpart, u32 chunk, u32 index, u32 _bit, u32 count)
Definition at line 39 of file bitmap.c.
 {
         int result;
         u32 sector, bit;
         u32 *bitmapWord, *bitmapEnd;
         while (clink)
         {
                 bitmapEnd = (u32*)&((u8*)clink->u.bitmap)[pfsMetaSize];
                 for (bitmapWord = &clink->u.bitmap[index]; (bitmapWord < bitmapEnd) && count; bitmapWord++, _bit = 0)
                 {
                         for (bit = _bit; bit < 32 && count; bit++, count--)
{
                                 if(operation == PFS_BITMAP_ALLOC)
{
                                         if (*bitmapWord & (1 << bit))
                                                 PFS_PRINTF(PFS_DRV_NAME": Error: Tried to allocate used block!\n");
                                         *bitmapWord |= (1 << bit);
                                 }
                                 else
{
                                         if ((*bitmapWord & (1 << bit))==0)
                                                 PFS_PRINTF(PFS_DRV_NAME": Error: Tried to free unused block!\n");
                                         *bitmapWord &= ~(1 << bit);
                                 }
                         }
                 }
                 index = 0;
                 clink->flags |= PFS_CACHE_FLAG_DIRTY;
                 pfsCacheFree(clink);
                 if (count==0)
                         break;
                 chunk++;
                 sector = (1 << clink->pfsMount->inode_scale) + chunk;
                 if(subpart==0)
                         sector += 0x2000 >> pfsBlockSize;
                 clink = pfsCacheGetData(clink->pfsMount, subpart, sector, PFS_CACHE_FLAG_BITMAP, &result);
         }
 }
References pfs_cache_t::bitmap, pfs_cache_t::flags, index(), pfs_mount_t::inode_scale, PFS_BITMAP_ALLOC, PFS_CACHE_FLAG_BITMAP, PFS_CACHE_FLAG_DIRTY, PFS_DRV_NAME, PFS_PRINTF, pfsBlockSize, pfsCacheFree(), pfsCacheGetData(), pfsMetaSize, pfs_cache_t::pfsMount, result, and pfs_cache_t::u.
Referenced by pfsBitmapAllocZones(), and pfsBitmapFreeBlockSegment().
pfsBitmapAllocZones()
int pfsBitmapAllocZones (pfs_mount_t * pfsMount, pfs_blockinfo_t * bi, u32 amount)
Definition at line 156 of file bitmap.c.
 {
         pfs_bitmapInfo_t info;
         int result;
         u32 startBit = 0, startPos = 0, startChunk = 0, count = 0;
         u32 sector;
         pfs_cache_t *bitmap;
         u32 *bitmapWord, *bitmapEnd;
         u32 i, bitmapMax;
         pfsBitmapSetupInfo(pfsMount, &info, bi->subpart, bi->number);
         for ( ; ((info.partitionRemainder==0) && (info.chunk < info.partitionChunks))||
                 ((info.partitionRemainder!=0) && (info.chunk < info.partitionChunks+1)); info.chunk++){
                 sector = info.chunk + (1 << pfsMount->inode_scale);
                 if(bi->subpart==0)
                         sector += 0x2000 >> pfsBlockSize;
                 // read in the bitmap chunk
                 bitmap = pfsCacheGetData(pfsMount, bi->subpart, sector, PFS_CACHE_FLAG_BITMAP, &result);
                 if(bitmap==0)
                         return 0;
                 bitmapMax = info.chunk == info.partitionChunks ? info.partitionRemainder / 8 : pfsMetaSize;
                 bitmapEnd = (u32*)&((u8*)bitmap->u.bitmap)[bitmapMax];
                 for (bitmapWord=&bitmap->u.bitmap[info.index]; bitmapWord < bitmapEnd; info.bit=0, bitmapWord++)
                 {
                         for (i=info.bit; i < 32; i++)
{
                                 // if this bit is marked as free..
                                 if (((*bitmapWord >> i) & 1)==0)
{
                                         if (count==0)
{
                                                 startBit = i;
                                                 startChunk = info.chunk;
                                                 startPos = bitmapWord - bitmap->u.bitmap;
                                         }
                                         if (++count == amount)
{
                                                 bi->number = (startPos * 32) + (startChunk * pfsBitsPerBitmapChunk) + startBit;
                                                 if (count < bi->count)
                                                         bi->count=count;
                                                 if (bitmap->block != (startChunk + (1 << pfsMount->inode_scale)))
{
                                                         pfsCacheFree(bitmap);
                                                         sector = (1 << pfsMount->inode_scale) + startChunk;
                                                         if(bi->subpart==0)
                                                                 sector += 0x2000 >> pfsBlockSize;
                                                         bitmap = pfsCacheGetData(pfsMount, bi->subpart, sector, PFS_CACHE_FLAG_BITMAP, &result);
                                                 }
                                                 pfsBitmapAllocFree(bitmap, PFS_BITMAP_ALLOC, bi->subpart, startChunk, startPos, startBit, bi->count);
                                                 return 1;
                                         }
                                 }
                                 else
                                         count=0;
                         }
                 }
                 pfsCacheFree(bitmap);
                 info.index=0;
         }
         return 0;
 }
References pfs_cache_t::bitmap, pfs_cache_t::block, pfs_blockinfo_t::count, pfs_mount_t::inode_scale, pfs_blockinfo_t::number, PFS_BITMAP_ALLOC, PFS_CACHE_FLAG_BITMAP, pfsBitmapAllocFree(), pfsBitmapSetupInfo(), pfsBitsPerBitmapChunk, pfsBlockSize, pfsCacheFree(), pfsCacheGetData(), pfsMetaSize, result, pfs_blockinfo_t::subpart, and pfs_cache_t::u.
Referenced by pfsBitmapSearchFreeZone().
pfsBitmapCalcFreeZones()
int pfsBitmapCalcFreeZones (pfs_mount_t * pfsMount, int sub)
Definition at line 288 of file bitmap.c.
 {
         // "Free zone" map. Used to get number of free zone in bitmap, 4-bits at a time
         u32 pfsFreeZoneBitmap[16]={4, 3, 3, 2, 3, 2, 2, 1, 3, 2, 2, 1, 2, 1, 1, 0};
         int result;
         pfs_bitmapInfo_t info;
         pfs_cache_t *clink;
         u32 i, bitmapSize, zoneFree=0, sector;
         pfsBitmapSetupInfo(pfsMount, &info, sub, 0);
         while (((info.partitionRemainder!=0) && (info.chunk<info.partitionChunks+1)) ||
                ((info.partitionRemainder==0) && (info.chunk<info.partitionChunks)))
         {
                 bitmapSize = info.chunk==info.partitionChunks ? info.partitionRemainder / 8 : pfsMetaSize;
                 sector = (1<<pfsMount->inode_scale) + info.chunk;
                 if (sub==0)
                         sector +=0x2000>>pfsBlockSize;
                 if ((clink=pfsCacheGetData(pfsMount, sub, sector, PFS_CACHE_FLAG_BITMAP, &result)))
                 {
                         for (i=0; i<bitmapSize; i++)
{
                                 zoneFree+=pfsFreeZoneBitmap[((u8*)clink->u.bitmap)[i] & 0xF]
                                    +pfsFreeZoneBitmap[((u8*)clink->u.bitmap)[i] >> 4];
                         }
                         pfsCacheFree(clink);
                 }
                 info.chunk++;
         }
         return zoneFree;
 }
References pfs_cache_t::bitmap, pfs_mount_t::inode_scale, PFS_CACHE_FLAG_BITMAP, pfsBitmapSetupInfo(), pfsBlockSize, pfsCacheFree(), pfsCacheGetData(), pfsMetaSize, result, and pfs_cache_t::u.
Referenced by pfsMountSuperBlock().
pfsBitmapFreeBlockSegment()
void pfsBitmapFreeBlockSegment (pfs_mount_t * pfsMount, pfs_blockinfo_t * bi)
Definition at line 266 of file bitmap.c.
 {
         pfs_bitmapInfo_t info;
         pfs_cache_t *clink;
         u32 sector;
         int rv;
         pfsBitmapSetupInfo(pfsMount, &info, bi->subpart, bi->number);
         sector = (1 << pfsMount->inode_scale) + info.chunk;
         if(bi->subpart==0)
                 sector += 0x2000 >> pfsBlockSize;
         if((clink=pfsCacheGetData(pfsMount, (u16)bi->subpart, sector, PFS_CACHE_FLAG_BITMAP, &rv)) != NULL)
         {
                 pfsBitmapAllocFree(clink, PFS_BITMAP_FREE, bi->subpart, info.chunk, info.index, info.bit, bi->count);
                 pfsMount->free_zone[(u16)bi->subpart]+=bi->count;
                 pfsMount->zfree+=bi->count;
         }
 }
References pfs_blockinfo_t::count, pfs_mount_t::free_zone, pfs_mount_t::inode_scale, NULL, pfs_blockinfo_t::number, PFS_BITMAP_FREE, PFS_CACHE_FLAG_BITMAP, pfsBitmapAllocFree(), pfsBitmapSetupInfo(), pfsBlockSize, pfsCacheGetData(), pfs_blockinfo_t::subpart, and pfs_mount_t::zfree.
Referenced by pfsBitmapFreeInodeBlocks(), pfsFreeZones(), and pfsInodeCreate().
pfsBitmapFreeInodeBlocks()
void pfsBitmapFreeInodeBlocks (pfs_cache_t * clink)
Definition at line 362 of file bitmap.c.
 {
         pfs_mount_t *pfsMount=clink->pfsMount;
         u32 i;
         pfsCacheUsedAdd(clink);
         for(i=0;i < clink->u.inode->number_data; i++)
         {
                 u32 index = pfsFixIndex(i);
                 pfs_blockinfo_t *bi=&clink->u.inode->data[index];
                 int err;
                 if(i!=0) {
                         if(index==0)
                                 if((clink = pfsBlockGetNextSegment(clink, &err))==NULL)
                                         return;
                 }
                 pfsBitmapFreeBlockSegment(pfsMount, bi);
                 pfsCacheMarkClean(pfsMount, (u16)bi->subpart,  bi->number << pfsMount->inode_scale,
                         (bi->number + bi->count) << pfsMount->inode_scale);
         }
         pfsCacheFree(clink);
 }
References pfs_blockinfo_t::count, pfs_inode_t::data, index(), pfs_cache_t::inode, pfs_mount_t::inode_scale, NULL, pfs_blockinfo_t::number, pfs_inode_t::number_data, pfsBitmapFreeBlockSegment(), pfsBlockGetNextSegment(), pfsCacheFree(), pfsCacheMarkClean(), pfsCacheUsedAdd(), pfsFixIndex(), pfs_cache_t::pfsMount, pfs_blockinfo_t::subpart, and pfs_cache_t::u.
Referenced by pfsFioRename(), and pfsInodeRemove().
pfsBitmapSearchFreeZone()
int pfsBitmapSearchFreeZone (pfs_mount_t * pfsMount, pfs_blockinfo_t * bi, u32 max_count)
Definition at line 228 of file bitmap.c.
 {
         u32 num, count, n;
         num = pfsMount->num_subs + 1;
         if (bi->subpart >= num)
                 bi->subpart = 0;
         if (bi->number)
                 num = pfsMount->num_subs + 2;
         count = max_count < 33 ? max_count : 32;                //min(max_count, 32)
         if(count < bi->count)
                 count = bi->count;                              //max(count, bi->count)
                                                                 // => count = bound(bi->count, 32);
         for(--num; num >= 0; num--)
         {
                 for (n = count; n; n /= 2)
                 {
                         if ((pfsMount->free_zone[bi->subpart] >= n) &&
                             pfsBitmapAllocZones(pfsMount, bi, n))
{
                                 pfsMount->free_zone[bi->subpart] -= bi->count;
                                 pfsMount->zfree -= bi->count;
                                 return 0;       // the good exit ;)
                         }
                 }
                 bi->number=0;
                 bi->subpart++;
                 if(bi->subpart == pfsMount->num_subs + 1)
                         bi->subpart=0;
         }
         return -ENOSPC;
 }
References pfs_blockinfo_t::count, ENOSPC, pfs_mount_t::free_zone, pfs_mount_t::num_subs, pfs_blockinfo_t::number, pfsBitmapAllocZones(), pfs_blockinfo_t::subpart, and pfs_mount_t::zfree.
Referenced by pfsBlockAllocNewSegment(), and pfsInodeCreate().
pfsBitmapSetupInfo()
void pfsBitmapSetupInfo (pfs_mount_t * pfsMount, pfs_bitmapInfo_t * info, u32 subpart, u32 number)
Definition at line 25 of file bitmap.c.
 {
         u32 size;
         size = pfsMount->blockDev->getSize(pfsMount->fd, subpart) >> pfsMount->sector_scale;
         info->chunk = number / pfsBitsPerBitmapChunk;
         info->bit = number & 31;
         info->index = (number % pfsBitsPerBitmapChunk) / 32;
         info->partitionChunks = size / pfsBitsPerBitmapChunk;
         info->partitionRemainder = size % pfsBitsPerBitmapChunk;
 }
References pfs_mount_t::blockDev, pfs_mount_t::fd, pfs_block_device_t::getSize, pfsBitsPerBitmapChunk, and pfs_mount_t::sector_scale.
Referenced by pfsBitmapAllocateAdditionalZones(), pfsBitmapAllocZones(), pfsBitmapCalcFreeZones(), pfsBitmapFreeBlockSegment(), and pfsBitmapShow().
pfsBitmapShow()
void pfsBitmapShow (pfs_mount_t * pfsMount)
Definition at line 325 of file bitmap.c.
 {
         int result;
         pfs_bitmapInfo_t info;
         u32 pn, bitcnt;
         for (pn=0; pn < pfsMount->num_subs+1; pn++)
         {
                 bitcnt=pfsBitsPerBitmapChunk;
                 pfsBitmapSetupInfo(pfsMount, &info, pn, 0);
                 while (((info.partitionRemainder!=0) && (info.chunk<info.partitionChunks+1)) ||
                        ((info.partitionRemainder==0) && (info.chunk<info.partitionChunks)))
                 {
                         pfs_cache_t *clink;
                         u32 sector = (1<<pfsMount->inode_scale) + info.chunk;
                         u32 i;
                         if(pn==0)
                                 sector += 0x2000 >> pfsBlockSize;
                         clink=pfsCacheGetData(pfsMount, pn, sector, PFS_CACHE_FLAG_BITMAP, &result);
                         if (info.chunk == info.partitionChunks)
                                 bitcnt=info.partitionRemainder;
                         PFS_PRINTF(PFS_DRV_NAME": Zone show: pn %ld, bn %ld, bitcnt %ld\n", pn, info.chunk, bitcnt);
                         for(i=0; (i < (u32)(1<<pfsBlockSize)) && ((i * 512) < (bitcnt / 8)); i++)
                                 pfsPrintBitmap(clink->u.bitmap+128*i);
                         pfsCacheFree(clink);
                         info.chunk++;
                 }
         }
 }
References pfs_cache_t::bitmap, pfs_mount_t::inode_scale, pfs_mount_t::num_subs, PFS_CACHE_FLAG_BITMAP, PFS_DRV_NAME, PFS_PRINTF, pfsBitmapSetupInfo(), pfsBitsPerBitmapChunk, pfsBlockSize, pfsCacheFree(), pfsCacheGetData(), pfsPrintBitmap(), result, and pfs_cache_t::u.
Referenced by pfsFioDevctl().
pfsBlockAllocNewSegment()
int pfsBlockAllocNewSegment (pfs_cache_t * clink, pfs_blockpos_t * blockpos, u32 blocks)
Definition at line 47 of file blockWrite.c.
 {
         pfs_blockinfo_t bi, *bi2;
         int result=0;
         pfs_mount_t *pfsMount=clink->pfsMount;
         u32 i, old_blocks = blocks;
         if (pfsCacheIsFull())
                 return -ENOMEM;
         // create "indirect segment descriptor" if necessary
         if (pfsFixIndex(clink->u.inode->number_data) == 0)
         {
                 pfs_cache_t *clink2;
                 bi2 = &blockpos->inode->u.inode->data[pfsFixIndex(blockpos->block_segment)];
                 bi.subpart=bi2->subpart;
                 bi.count=1;
                 bi.number=bi2->number+bi2->count;
                 result=pfsBitmapSearchFreeZone(pfsMount, &bi, clink->u.inode->number_blocks);
                 if (result<0)
                 {
                         PFS_PRINTF(PFS_DRV_NAME": Error: Couldnt allocate zone! (1)\n");
                         return result;
                 }
                 clink2=pfsCacheGetData(pfsMount, bi.subpart, bi.number << pfsMount->inode_scale,
                                                                 PFS_CACHE_FLAG_SEGI | PFS_CACHE_FLAG_NOLOAD, &result);
                 memset(clink2->u.inode, 0, sizeof(pfs_inode_t));
                 clink2->u.inode->magic=PFS_SEGI_MAGIC;
                 memcpy(&clink2->u.inode->inode_block, &clink->u.inode->inode_block, sizeof(pfs_blockinfo_t));
                 memcpy(&clink2->u.inode->last_segment, &blockpos->inode->u.inode->data[0], sizeof(pfs_blockinfo_t));
                 memcpy(&clink2->u.inode->data[0], &bi, sizeof(pfs_blockinfo_t));
                 clink2->flags |= PFS_CACHE_FLAG_DIRTY;
                 clink->u.inode->number_blocks+=bi.count;
                 clink->u.inode->number_data++;
                 memcpy(&clink->u.inode->last_segment, &bi, sizeof(pfs_blockinfo_t));
                 clink->u.inode->number_segdesg++;
                 clink->flags |= PFS_CACHE_FLAG_DIRTY;
                 blockpos->block_segment++;
                 blockpos->block_offset=0;
                 memcpy(&blockpos->inode->u.inode->next_segment, &bi, sizeof(pfs_blockinfo_t));
                 blockpos->inode->flags |= PFS_CACHE_FLAG_DIRTY;
                 pfsCacheFree(blockpos->inode);
                 blockpos->inode=clink2;
         }
         bi2 = &blockpos->inode->u.inode->data[pfsFixIndex(blockpos->block_segment)];
         bi.subpart = bi2->subpart;
         bi.count = blocks;
         bi.number = bi2->number + bi2->count;
         result = pfsBitmapSearchFreeZone(pfsMount, &bi, clink->u.inode->number_blocks);
         if(result < 0)
         {
                 PFS_PRINTF(PFS_DRV_NAME": Error: Couldnt allocate zone! (2)\n");
                 return result;
         }
         clink->u.inode->number_blocks += bi.count;
         clink->u.inode->number_data++;
         clink->flags |= PFS_CACHE_FLAG_DIRTY;
         blockpos->block_offset=0;
         blockpos->block_segment++;
         i = pfsFixIndex(clink->u.inode->number_data-1);
         memcpy(&blockpos->inode->u.inode->data[i], &bi, sizeof(pfs_blockinfo_t));
         blockpos->inode->flags |= PFS_CACHE_FLAG_DIRTY;
         blocks -= bi.count;
         if (blocks)
                 blocks -= pfsBlockExpandSegment(clink, blockpos, blocks);
         return old_blocks - blocks;
 }
References pfs_blockpos_t::block_offset, pfs_blockpos_t::block_segment, pfs_blockinfo_t::count, pfs_inode_t::data, ENOMEM, pfs_cache_t::flags, pfs_cache_t::inode, pfs_blockpos_t::inode, pfs_inode_t::inode_block, pfs_mount_t::inode_scale, pfs_inode_t::last_segment, pfs_inode_t::magic, memcpy(), memset(), pfs_inode_t::next_segment, pfs_blockinfo_t::number, pfs_inode_t::number_blocks, pfs_inode_t::number_data, pfs_inode_t::number_segdesg, PFS_CACHE_FLAG_DIRTY, PFS_CACHE_FLAG_NOLOAD, PFS_CACHE_FLAG_SEGI, PFS_DRV_NAME, PFS_PRINTF, PFS_SEGI_MAGIC, pfsBitmapSearchFreeZone(), pfsBlockExpandSegment(), pfsCacheFree(), pfsCacheGetData(), pfsCacheIsFull(), pfsFixIndex(), pfs_cache_t::pfsMount, result, pfs_blockinfo_t::subpart, and pfs_cache_t::u.
Referenced by fileTransfer(), and pfsAllocZones().
pfsBlockExpandSegment()
int pfsBlockExpandSegment (pfs_cache_t * clink, pfs_blockpos_t * blockpos, u32 count)
Definition at line 25 of file blockWrite.c.
 {
         int ret;
         pfs_blockinfo_t *bi;
         if(pfsFixIndex(blockpos->block_segment)==0)
                 return 0;
         bi = &blockpos->inode->u.inode->data[pfsFixIndex(blockpos->block_segment)];
         if ((ret = pfsBitmapAllocateAdditionalZones(clink->pfsMount, bi, count)))
         {
                 bi->count+=ret;
                 clink->u.inode->number_blocks+=ret;
                 blockpos->inode->flags |= PFS_CACHE_FLAG_DIRTY;
                 clink->flags |= PFS_CACHE_FLAG_DIRTY;
         }
         return ret;
 }
References pfs_blockpos_t::block_segment, pfs_blockinfo_t::count, pfs_inode_t::data, pfs_cache_t::flags, pfs_cache_t::inode, pfs_blockpos_t::inode, pfs_inode_t::number_blocks, PFS_CACHE_FLAG_DIRTY, pfsBitmapAllocateAdditionalZones(), pfsFixIndex(), pfs_cache_t::pfsMount, and pfs_cache_t::u.
Referenced by fileTransfer(), pfsAllocZones(), and pfsBlockAllocNewSegment().
pfsBlockGetCurrent()
pfs_blockinfo_t* pfsBlockGetCurrent (pfs_blockpos_t * blockpos)
Definition at line 133 of file blockWrite.c.
 {
         return &blockpos->inode->u.inode->data[pfsFixIndex(blockpos->block_segment)];
 }
References pfs_blockpos_t::block_segment, pfs_inode_t::data, pfs_cache_t::inode, pfs_blockpos_t::inode, pfsFixIndex(), and pfs_cache_t::u.
Referenced by fileTransfer(), and fileTransferRemainder().
pfsBlockGetLastSegmentDescriptorInode()
pfs_cache_t* pfsBlockGetLastSegmentDescriptorInode (pfs_cache_t * clink, int * result)
Definition at line 138 of file blockWrite.c.
 {
         return pfsCacheGetData(clink->pfsMount, clink->u.inode->last_segment.subpart,
                 clink->u.inode->last_segment.number<<clink->pfsMount->inode_scale,
                 (clink->u.inode->last_segment.subpart==
                  clink->u.inode->inode_block.subpart)&&
                 (clink->u.inode->last_segment.number==
                  clink->u.inode->inode_block.number) ? 16 : 32, result);
 }
References pfs_cache_t::inode, pfs_inode_t::inode_block, pfs_mount_t::inode_scale, pfs_inode_t::last_segment, pfs_blockinfo_t::number, pfsCacheGetData(), pfs_cache_t::pfsMount, result, pfs_blockinfo_t::subpart, and pfs_cache_t::u.
Referenced by pfsAllocZones().
pfsBlockGetNextSegment()
pfs_cache_t* pfsBlockGetNextSegment (pfs_cache_t * clink, int * result)
Definition at line 25 of file block.c.
 {
         pfsCacheFree(clink);
         if (clink->u.inode->next_segment.number)
                 return pfsCacheGetData(clink->pfsMount,
                 clink->u.inode->next_segment.subpart,
                 clink->u.inode->next_segment.number << clink->pfsMount->inode_scale,
                 PFS_CACHE_FLAG_SEGI, result);
         PFS_PRINTF(PFS_DRV_NAME": Error: There is no next segment descriptor\n");
         *result=-EINVAL;
         return NULL;
 }
References EINVAL, pfs_cache_t::inode, pfs_mount_t::inode_scale, pfs_inode_t::next_segment, NULL, pfs_blockinfo_t::number, PFS_CACHE_FLAG_SEGI, PFS_DRV_NAME, PFS_PRINTF, pfsCacheFree(), pfsCacheGetData(), pfs_cache_t::pfsMount, result, pfs_blockinfo_t::subpart, and pfs_cache_t::u.
Referenced by pfsBitmapFreeInodeBlocks(), pfsBlockSeekNextSegment(), pfsFreeZones(), and pfsInodeSync().
pfsBlockInitPos()
int pfsBlockInitPos (pfs_cache_t * clink, pfs_blockpos_t * blockpos, u64 position)
Definition at line 85 of file block.c.
 {
         blockpos->inode=pfsCacheUsedAdd(clink);
         blockpos->byte_offset=0;
         if (clink->u.inode->size)
         {
                 blockpos->block_segment=1;
                 blockpos->block_offset=0;
         }else{
                 blockpos->block_segment=0;
                 blockpos->block_offset=1;
         }
         return pfsInodeSync(blockpos, position, clink->u.inode->number_data);
 }
References pfs_blockpos_t::block_offset, pfs_blockpos_t::block_segment, pfs_blockpos_t::byte_offset, pfs_cache_t::inode, pfs_blockpos_t::inode, pfs_inode_t::number_data, pfsCacheUsedAdd(), pfsInodeSync(), pfs_inode_t::size, and pfs_cache_t::u.
Referenced by _seek(), openFile(), and pfsGetDentriesAtPos().
pfsBlockSeekNextSegment()
int pfsBlockSeekNextSegment (pfs_cache_t * clink, pfs_blockpos_t * blockpos)
Definition at line 42 of file block.c.
 {
         pfs_cache_t *nextSegment;
         int result=0;
         if (blockpos->byte_offset)
         {
                 PFS_PRINTF(PFS_DRV_NAME": Panic: This is a bug!\n");
                 return -1;
         }
         // If we're at the end of the block descriptor array for the current
         // inode, then move onto the next inode
         if (pfsFixIndex(blockpos->block_segment+1)==0)
         {
                 if ((nextSegment=pfsBlockGetNextSegment(pfsCacheUsedAdd(blockpos->inode), &result)) == NULL)
                         return result;
                 pfsCacheFree(blockpos->inode);
                 blockpos->inode=nextSegment;
                 if (clink->u.inode->number_data-1 == ++blockpos->block_segment)
                         return -EINVAL;
         }
         blockpos->block_offset=0;
         blockpos->block_segment++;
         return result;
 }
References pfs_blockpos_t::block_offset, pfs_blockpos_t::block_segment, pfs_blockpos_t::byte_offset, EINVAL, pfs_cache_t::inode, pfs_blockpos_t::inode, NULL, pfs_inode_t::number_data, PFS_DRV_NAME, PFS_PRINTF, pfsBlockGetNextSegment(), pfsCacheFree(), pfsCacheUsedAdd(), pfsFixIndex(), result, and pfs_cache_t::u.
Referenced by fileTransfer().
pfsBlockSyncPos()
u32 pfsBlockSyncPos (pfs_blockpos_t * blockpos, u64 size)
Definition at line 70 of file block.c.
 {
         u32 i;
         i = (u32)(size / blockpos->inode->pfsMount->zsize);
         blockpos->byte_offset += size % blockpos->inode->pfsMount->zsize;
         if (blockpos->byte_offset >= blockpos->inode->pfsMount->zsize)
         {
                 blockpos->byte_offset -= blockpos->inode->pfsMount->zsize;
                 i++;
         }
         return i;
 }
References pfs_blockpos_t::byte_offset, pfs_blockpos_t::inode, pfs_cache_t::pfsMount, and pfs_mount_t::zsize.
Referenced by fileTransfer(), and pfsInodeSync().
pfsCacheAlloc()
pfs_cache_t* pfsCacheAlloc (pfs_mount_t * pfsMount, u16 sub, u32 block, int flags, int * result)
Definition at line 132 of file cache.c.
 {
         pfs_cache_t *allocated;
         if (pfsCacheBuf->prev==pfsCacheBuf && pfsCacheBuf->prev->next==pfsCacheBuf->prev) {
                 PFS_PRINTF(PFS_DRV_NAME": Error: Free buffer list is empty\n");
                 *result=-ENOMEM;
                 return NULL;
         }
         allocated=pfsCacheBuf->next;
         if (pfsCacheBuf->next==NULL)
                 PFS_PRINTF(PFS_DRV_NAME": Panic: Null pointer allocated\n");
         if (allocated->pfsMount && (allocated->flags & PFS_CACHE_FLAG_DIRTY))
                 pfsCacheFlushAllDirty(allocated->pfsMount);
         allocated->flags        = flags & PFS_CACHE_FLAG_MASKTYPE;
         allocated->pfsMount     = pfsMount;
         allocated->sub          = sub;
         allocated->block        = block;
         allocated->nused        = 1;
         return pfsCacheUnLink(allocated);
 }
References pfs_cache_t::block, ENOMEM, pfs_cache_t::flags, pfs_cache_t::next, NULL, pfs_cache_t::nused, PFS_CACHE_FLAG_DIRTY, PFS_CACHE_FLAG_MASKTYPE, PFS_DRV_NAME, PFS_PRINTF, pfsCacheBuf, pfsCacheFlushAllDirty(), pfsCacheUnLink(), pfs_cache_t::pfsMount, pfs_cache_t::prev, result, and pfs_cache_t::sub.
Referenced by pfsCacheAllocClean(), and pfsCacheGetData().
pfsCacheAllocClean()
pfs_cache_t* pfsCacheAllocClean (int * result)
Definition at line 191 of file cache.c.
 {
         *result = 0;
         return pfsCacheAlloc(NULL, 0, 0, 0, result);
 }
References NULL, pfsCacheAlloc(), and result.
Referenced by devctlFsckStat(), pfsFormat(), pfsFormatSub(), pfsJournalRestore(), and pfsMountSuperBlock().
pfsCacheClose()
void pfsCacheClose (pfs_mount_t * pfsMount)
Definition at line 235 of file cache.c.
 {
         unsigned int i;
         pfsCacheFlushAllDirty(pfsMount);
         for(i=1; i < pfsCacheNumBuffers+1;i++){
                 if(pfsCacheBuf[i].pfsMount==pfsMount)
                         pfsCacheBuf[i].pfsMount=NULL;
         }
 }
References NULL, pfsCacheBuf, pfsCacheFlushAllDirty(), pfsCacheNumBuffers, and pfs_cache_t::pfsMount.
Referenced by pfsFioUmount().
pfsCacheFlushAllDirty()
void pfsCacheFlushAllDirty (pfs_mount_t * pfsMount)
Definition at line 110 of file cache.c.
 {
         u32 i;
         int found=0;
         for(i=1;i<pfsCacheNumBuffers+1;i++){
                 if(pfsCacheBuf[i].pfsMount == pfsMount &&
                         pfsCacheBuf[i].flags & PFS_CACHE_FLAG_DIRTY)
                                 found=1;
         }
         if(found) {
                 pfsJournalWrite(pfsMount, pfsCacheBuf+1, pfsCacheNumBuffers);
                 for(i=1;i<pfsCacheNumBuffers+1;i++){
                         if(pfsCacheBuf[i].pfsMount == pfsMount &&
                                 pfsCacheBuf[i].flags & PFS_CACHE_FLAG_DIRTY)
                                         pfsCacheTransfer(&pfsCacheBuf[i], 1);
                 }
         }
         pfsJournalReset(pfsMount);
 }
References PFS_CACHE_FLAG_DIRTY, pfsCacheBuf, pfsCacheNumBuffers, pfsCacheTransfer(), pfsJournalReset(), and pfsJournalWrite().
Referenced by openFile(), pfsCacheAlloc(), pfsCacheClose(), pfsFioChstat(), pfsFioCloseFileSlot(), pfsFioDevctlCloseAll(), pfsFioIoctl2(), pfsFioRename(), pfsFioSync(), pfsFioWrite(), and pfsInodeRemove().
pfsCacheFree()
void pfsCacheFree (pfs_cache_t * clink)
Definition at line 30 of file cache.c.
 {
         if(clink==NULL) {
                 PFS_PRINTF(PFS_DRV_NAME": Warning: NULL buffer returned\n");
                 return;
         }
         if(clink->nused==0){
                 PFS_PRINTF(PFS_DRV_NAME": Error: Unused cache returned\n");
                 return;
         }
         clink->nused--;
         if(clink->pfsMount!=NULL) {
                 if(clink->nused!=0)
                         return;
                 pfsCacheLink(pfsCacheBuf->prev, clink);
                 return;
         }
         if(clink->nused!=0) {
                 PFS_PRINTF(PFS_DRV_NAME": Warning: Invalidated buffer is in use\n");
                 return;
         }
         pfsCacheLink(pfsCacheBuf, clink);
 }
References NULL, pfs_cache_t::nused, PFS_DRV_NAME, PFS_PRINTF, pfsCacheBuf, pfsCacheLink(), pfs_cache_t::pfsMount, and pfs_cache_t::prev.
Referenced by _remove(), _seek(), devctlFsckStat(), ioctl2Attr(), openFile(), pfsAllocZones(), pfsBitmapAllocateAdditionalZones(), pfsBitmapAllocFree(), pfsBitmapAllocZones(), pfsBitmapCalcFreeZones(), pfsBitmapFreeInodeBlocks(), pfsBitmapShow(), pfsBlockAllocNewSegment(), pfsBlockGetNextSegment(), pfsBlockSeekNextSegment(), pfsCacheGetData(), pfsCheckDirForFiles(), pfsFioChdir(), pfsFioChstat(), pfsFioCloseFileSlot(), pfsFioDread(), pfsFioGetstat(), pfsFioReadlink(), pfsFioRename(), pfsFormat(), pfsFormatSub(), pfsFreeZones(), pfsGetDentriesAtPos(), pfsGetDentry(), pfsGetNextDentry(), pfsInodeCreate(), pfsInodeGetFile(), pfsInodeGetFileInDir(), pfsInodeGetParent(), pfsInodeRemove(), pfsJournalRestore(), and pfsMountSuperBlock().
pfsCacheGetData()
pfs_cache_t* pfsCacheGetData (pfs_mount_t * pfsMount, u16 sub, u32 block, int flags, int * result)
Definition at line 155 of file cache.c.
 {
         u32 i;
         pfs_cache_t *clink;
         *result=0;
         for (i=1; i < pfsCacheNumBuffers + 1; i++)
                 if ( pfsCacheBuf[i].pfsMount &&
                     (pfsCacheBuf[i].pfsMount==pfsMount) &&
                     (pfsCacheBuf[i].block  == block))
                         if (pfsCacheBuf[i].sub==sub){
                                 pfsCacheBuf[i].flags &= PFS_CACHE_FLAG_MASKSTATUS;
                                 pfsCacheBuf[i].flags |= flags & PFS_CACHE_FLAG_MASKTYPE;
                                 if (pfsCacheBuf[i].nused == 0)
                                         pfsCacheUnLink(&pfsCacheBuf[i]);
                                 pfsCacheBuf[i].nused++;
                                 return &pfsCacheBuf[i];
                         }
         clink=pfsCacheAlloc(pfsMount, sub, block, flags, result);
         if (clink){
                 if (flags & PFS_CACHE_FLAG_NOLOAD)
                         return clink;
                 if ((*result=pfsCacheTransfer(clink, PFS_IO_MODE_READ))>=0)
                         return clink;
                 clink->pfsMount=NULL;
                 pfsCacheFree(clink);
         }
         return NULL;
 }
References pfs_cache_t::flags, NULL, pfs_cache_t::nused, PFS_CACHE_FLAG_MASKSTATUS, PFS_CACHE_FLAG_MASKTYPE, PFS_CACHE_FLAG_NOLOAD, PFS_IO_MODE_READ, pfsCacheAlloc(), pfsCacheBuf, pfsCacheFree(), pfsCacheNumBuffers, pfsCacheTransfer(), pfsCacheUnLink(), pfs_cache_t::pfsMount, and result.
Referenced by ioctl2Attr(), openFile(), pfsBitmapAllocateAdditionalZones(), pfsBitmapAllocFree(), pfsBitmapAllocZones(), pfsBitmapCalcFreeZones(), pfsBitmapFreeBlockSegment(), pfsBitmapShow(), pfsBlockAllocNewSegment(), pfsBlockGetLastSegmentDescriptorInode(), pfsBlockGetNextSegment(), pfsGetDentriesChunk(), pfsInodeCreate(), and pfsInodeGetData().
pfsCacheInit()
int pfsCacheInit (u32 numBuf, u32 bufSize)
Definition at line 204 of file cache.c.
 {
         char *cacheData;
         u32 i;
         if(numBuf > 127) {
                 PFS_PRINTF(PFS_DRV_NAME": Error: Number of buffers larger than 127.\n");
                 return -EINVAL;
         }
         cacheData = pfsAllocMem(numBuf * bufSize);
         if(!cacheData || !(pfsCacheBuf = pfsAllocMem((numBuf + 1) * sizeof(pfs_cache_t))))
                 return -ENOMEM;
         pfsCacheNumBuffers = numBuf;
         memset(pfsCacheBuf, 0, (numBuf + 1) * sizeof(pfs_cache_t));
         pfsCacheBuf->next = pfsCacheBuf;
         pfsCacheBuf->prev = pfsCacheBuf;
         for(i = 1; i < numBuf + 1; i++)
         {
                 pfsCacheBuf[i].u.data = cacheData;
                 pfsCacheLink(pfsCacheBuf->prev, &pfsCacheBuf[i]);
                 cacheData += bufSize;
         }
         return 0;
 }
References pfs_cache_t::data, EINVAL, ENOMEM, memset(), pfs_cache_t::next, PFS_DRV_NAME, PFS_PRINTF, pfsAllocMem(), pfsCacheBuf, pfsCacheLink(), pfsCacheNumBuffers, pfs_cache_t::prev, and pfs_cache_t::u.
Referenced by _start().
pfsCacheIsFull()
int pfsCacheIsFull (void)
Definition at line 198 of file cache.c.
 {
         if (pfsCacheBuf->prev != pfsCacheBuf)   return 0;
         return pfsCacheBuf->prev->next == pfsCacheBuf->prev;
 }
References pfsCacheBuf, and pfs_cache_t::prev.
Referenced by pfsBlockAllocNewSegment().
pfsCacheLink()
void pfsCacheLink (pfs_cache_t * clink, pfs_cache_t * cnew)
Definition at line 56 of file cache.c.
 {
         cnew->prev=clink;
         cnew->next=clink->next;
         clink->next->prev=cnew;
         clink->next=cnew;
 }
References pfs_cache_t::next, and pfs_cache_t::prev.
Referenced by pfsCacheFree(), and pfsCacheInit().
pfsCacheMarkClean()
void pfsCacheMarkClean (pfs_mount_t * pfsMount, u32 subpart, u32 blockStart, u32 blockEnd)
Definition at line 246 of file cache.c.
 {
         u32 i;
         for(i=1; i< pfsCacheNumBuffers+1;i++){
                 if(pfsCacheBuf[i].pfsMount==pfsMount && pfsCacheBuf[i].sub==subpart) {
                         if(pfsCacheBuf[i].block >= blockStart && pfsCacheBuf[i].block < blockEnd)
                                 pfsCacheBuf[i].flags&=~PFS_CACHE_FLAG_DIRTY;
                 }
         }
 }
References pfs_cache_t::flags, PFS_CACHE_FLAG_DIRTY, pfsCacheBuf, and pfsCacheNumBuffers.
Referenced by pfsBitmapFreeInodeBlocks(), and pfsFreeZones().
pfsCacheTransfer()
int pfsCacheTransfer (pfs_cache_t * clink, int mode)
Definition at line 77 of file cache.c.
 {
         pfs_mount_t *pfsMount=clink->pfsMount;
         int err;
         if(pfsMount->lastError == 0) {  // no error
                 if((err=pfsMount->blockDev->transfer(pfsMount->fd, clink->u.data, clink->sub,
                         clink->block << pfsBlockSize, 1 << pfsBlockSize, mode))==0) {
                         if(mode==PFS_IO_MODE_READ) {
                                 if(clink->flags & PFS_CACHE_FLAG_SEGD && ((pfs_inode_t *)clink->u.inode)->magic!=PFS_SEGD_MAGIC)
                                         err=-EIO;
                                 if(clink->flags & PFS_CACHE_FLAG_SEGI && ((pfs_inode_t *)clink->u.inode)->magic!=PFS_SEGI_MAGIC)
                                         err=-EIO;
                                 if(clink->flags & (PFS_CACHE_FLAG_SEGD|PFS_CACHE_FLAG_SEGI)) {
                                         if(((pfs_inode_t *)clink->u.inode)->checksum!=pfsInodeCheckSum(clink->u.inode))
                                                 err=-EIO;
                                 }
                         }
                 }
                 if(err!=0) {
                         PFS_PRINTF(PFS_DRV_NAME": Error: Disk error partition %ld, block %ld, err %d\n",
                                 clink->sub, clink->block, err);
 #ifndef PFS_NO_WRITE_ERROR_STAT
                         pfsMount->blockDev->setPartitionError(pfsMount->fd);
                         pfsFsckStat(pfsMount, clink->u.superblock, PFS_FSCK_STAT_WRITE_ERROR, PFS_MODE_SET_FLAG);
                         pfsMount->lastError=err;
 #endif
                 }
         }
         clink->flags&=~PFS_CACHE_FLAG_DIRTY; // clear dirty :)
         return pfsMount->lastError;
 }
References pfs_cache_t::block, pfs_mount_t::blockDev, pfs_cache_t::data, EIO, pfs_mount_t::fd, pfs_cache_t::flags, pfs_cache_t::inode, pfs_mount_t::lastError, PFS_CACHE_FLAG_DIRTY, PFS_CACHE_FLAG_SEGD, PFS_CACHE_FLAG_SEGI, PFS_DRV_NAME, PFS_FSCK_STAT_WRITE_ERROR, PFS_IO_MODE_READ, PFS_MODE_SET_FLAG, PFS_PRINTF, PFS_SEGD_MAGIC, PFS_SEGI_MAGIC, pfsBlockSize, pfsFsckStat(), pfsInodeCheckSum(), pfs_cache_t::pfsMount, pfs_block_device_t::setPartitionError, pfs_cache_t::sub, pfs_cache_t::superblock, pfs_block_device_t::transfer, and pfs_cache_t::u.
Referenced by pfsCacheFlushAllDirty(), and pfsCacheGetData().
pfsCacheUnLink()
pfs_cache_t* pfsCacheUnLink (pfs_cache_t * clink)
Definition at line 64 of file cache.c.
 {
         clink->prev->next=clink->next;
         clink->next->prev=clink->prev;
         return clink;
 }
References pfs_cache_t::next, and pfs_cache_t::prev.
Referenced by pfsCacheAlloc(), and pfsCacheGetData().
pfsCacheUsedAdd()
pfs_cache_t* pfsCacheUsedAdd (pfs_cache_t * clink)
Definition at line 71 of file cache.c.
 {
         clink->nused++;
         return clink;
 }
References pfs_cache_t::nused.
Referenced by pfsBitmapFreeInodeBlocks(), pfsBlockInitPos(), pfsBlockSeekNextSegment(), pfsFioRename(), pfsFreeZones(), pfsGetDentry(), and pfsInodeGetFileInDir().
pfsCheckAccess()
int pfsCheckAccess (pfs_cache_t * clink, int flags)
Definition at line 553 of file dir.c.
 {
         int mode;
         // Bail if trying to write to read-only mount
         if ((clink->pfsMount->flags & FIO_MT_RDONLY) && (flags & O_WRONLY))
                 return -EROFS;
         if (((clink->u.inode->mode & FIO_S_IFMT) != FIO_S_IFDIR) &&
                 ((clink->u.inode->mode & 0111) == 0))
                 mode=6;
         else
                 mode=7;
         return ((mode & flags) & 7) == flags ? 0 : -EACCES;
 }
References EACCES, EROFS, FIO_MT_RDONLY, FIO_S_IFDIR, FIO_S_IFMT, pfs_mount_t::flags, pfs_cache_t::inode, pfs_inode_t::mode, O_WRONLY, pfs_cache_t::pfsMount, and pfs_cache_t::u.
Referenced by _remove(), openFile(), pfsFioChdir(), pfsFioChstat(), pfsFioRename(), and pfsInodeGetFileInDir().
pfsCheckDirForFiles()
int pfsCheckDirForFiles (pfs_cache_t * clink)
Definition at line 237 of file dir.c.
 {
         pfs_dentry_t *dentry;
         pfs_cache_t *dcache;
         u32 size;
         if((dcache=pfsGetDentry(clink, NULL, &dentry, &size, 2))){
                 pfsCacheFree(dcache);
                 return 0;
         }
         return 1;
 }
References NULL, pfsCacheFree(), and pfsGetDentry().
Referenced by _remove(), and pfsFioRename().
pfsCheckZoneSize()
int pfsCheckZoneSize (u32 zone_size)
Definition at line 28 of file super.c.
 {
         if((zone_size & (zone_size - 1)) || (zone_size < (2 * 1024)) || (zone_size > (128 * 1024)))
         {
                 PFS_PRINTF(PFS_DRV_NAME": Error: Invalid zone size\n");
                 return 0;
         }
         return 1;
 }
References PFS_DRV_NAME, and PFS_PRINTF.
Referenced by pfsFormat(), and pfsMountSuperBlock().
pfsDirAddEntry()
pfs_cache_t* pfsDirAddEntry (pfs_cache_t * dir, char * filename, pfs_blockinfo_t * bi, u16 mode, int * result)
Definition at line 167 of file dir.c.
 {
         pfs_dentry_t *dentry;
         u32 size;
         u32 len;
         pfs_cache_t *dcache;
         dcache=pfsGetDentry(dir, filename, &dentry, &size, 1);
         if (dcache != NULL){
                 len=dentry->aLen & 0xFFF;
                 if (dentry->pLen)
                         len-=(dentry->pLen + 11) & 0x1FC;
                 dentry->aLen=(dentry->aLen & FIO_S_IFMT) | ((dentry->aLen & 0xFFF) - len);
                 dentry=(pfs_dentry_t *)((u8*)dentry + (dentry->aLen & 0xFFF));
         }else{
                 int offset;
                 if ((*result=pfsAllocZones(dir, sizeof(pfs_dentry_t), 0))<0)
                         return NULL;
                 dcache=pfsGetDentriesAtPos(dir, dir->u.inode->size, &offset, result);
                 if (dcache==NULL)
                         return NULL;
                 dir->u.inode->size += sizeof(pfs_dentry_t);
                 dentry=(pfs_dentry_t*)((u8*)dcache->u.dentry+offset);
                 len=sizeof(pfs_dentry_t);
         }
         return pfsFillDentry(dcache, dentry, filename, bi, len, mode);
 }
References pfs_dentry_t::aLen, pfs_cache_t::dentry, FIO_S_IFMT, pfs_cache_t::inode, NULL, pfsAllocZones(), pfsFillDentry(), pfsGetDentriesAtPos(), pfsGetDentry(), pfs_dentry_t::pLen, result, pfs_inode_t::size, and pfs_cache_t::u.
Referenced by openFile(), and pfsFioRename().
pfsDirRemoveEntry()
pfs_cache_t* pfsDirRemoveEntry (pfs_cache_t * clink, char * path)
Definition at line 198 of file dir.c.
 {
         pfs_dentry_t *dentry;
         u32 size;
         u16 aLen;
         int i=0, val;
         pfs_dentry_t *dlast=NULL, *dnext;
         pfs_cache_t *c;
         if ((c=pfsGetDentry(clink, path, &dentry, &size, 0)) != NULL){
                 val=(int)dentry-(int)c->u.dentry;
                 if (val<0)      val +=511;
                 val /=512;
                 val *=512;
                 dnext=(pfs_dentry_t*)((u8*)c->u.dentry+val);
                 do{
                         aLen = dnext->aLen & 0xFFF;
                         if (dnext==dentry){
                                 if (dlast)
                                         dlast->aLen=(dlast->aLen & FIO_S_IFMT) | ((dlast->aLen & 0xFFF) + aLen);
                                 else{
                                         dnext->inode=0;
                                         dnext->pLen=0;
                                         if (size+aLen >= clink->u.inode->size)
                                                         clink->u.inode->size -= aLen;
                                 }
                                 return c;
                         }
                         i+=aLen;
                         dlast=dnext;
                         dnext=(pfs_dentry_t *)((u8*)dnext + aLen);
                 }while (i<512);
         }
         return NULL;
 }
References pfs_dentry_t::aLen, pfs_cache_t::dentry, FIO_S_IFMT, pfs_cache_t::inode, NULL, pfsGetDentry(), pfs_inode_t::size, and pfs_cache_t::u.
Referenced by pfsFioRename(), and pfsInodeRemove().
pfsFillDentry()
pfs_cache_t* pfsFillDentry (pfs_cache_t * clink, pfs_dentry_t * dentry, char * path1, pfs_blockinfo_t * bi, u32 len, u16 mode)
Definition at line 156 of file dir.c.
 {
         dentry->inode=bi->number;
         dentry->sub=(u8)bi->subpart;
         dentry->pLen=strlen(path1);
         dentry->aLen=len | (mode & FIO_S_IFMT);
         memcpy(dentry->path, path1, dentry->pLen & 0xFF);
         return clink;
 }
References pfs_dentry_t::aLen, FIO_S_IFMT, pfs_dentry_t::inode, memcpy(), pfs_blockinfo_t::number, pfs_dentry_t::path, pfs_dentry_t::pLen, strlen(), pfs_dentry_t::sub, and pfs_blockinfo_t::subpart.
Referenced by pfsDirAddEntry().
pfsFillSelfAndParentDentries()
void pfsFillSelfAndParentDentries (pfs_cache_t * clink, pfs_blockinfo_t * self, pfs_blockinfo_t * parent)
Definition at line 250 of file dir.c.
 {
         pfs_dentry_t *dentry=clink->u.dentry;
         memset(dentry, 0, pfsMetaSize);
         dentry->inode=self->number;
         dentry->path[0]='.';
         dentry->path[1]='\0';
         dentry->sub=(u8)self->subpart;
         dentry->pLen=1;
         dentry->aLen=12 | FIO_S_IFDIR;
         dentry=(pfs_dentry_t *)((u8*)dentry + 12);
         dentry->inode=parent->number;
         dentry->path[0]='.';
         dentry->path[1]='.';
         dentry->path[2]='\0';
         dentry->sub=(u8)parent->subpart;
         dentry->pLen=2;
         dentry->aLen=500 | FIO_S_IFDIR;
 }
References pfs_dentry_t::aLen, pfs_cache_t::dentry, FIO_S_IFDIR, pfs_dentry_t::inode, memset(), pfs_blockinfo_t::number, pfs_dentry_t::path, pfsMetaSize, pfs_dentry_t::pLen, pfs_dentry_t::sub, pfs_blockinfo_t::subpart, and pfs_cache_t::u.
Referenced by openFile(), and pfsFormat().
pfsFixIndex()
u32 pfsFixIndex (u32 index)
Definition at line 165 of file misc.c.
 {
         if(index < PFS_INODE_MAX_BLOCKS)
                 return index;
         index -= PFS_INODE_MAX_BLOCKS;
         return index % 123;
 }
References index(), and PFS_INODE_MAX_BLOCKS.
Referenced by pfsBitmapFreeInodeBlocks(), pfsBlockAllocNewSegment(), pfsBlockExpandSegment(), pfsBlockGetCurrent(), pfsBlockSeekNextSegment(), pfsFreeZones(), pfsGetDentriesChunk(), and pfsInodeSync().
pfsFormat()
int pfsFormat (pfs_block_device_t * blockDev, int fd, int zonesize, int fragment)
Definition at line 74 of file superWrite.c.
 {
         int result, result2;
         pfs_cache_t *clink, *cache;
         pfs_super_block_t *sb;
         int scale;
         u32 i, mainsize, subnumber = blockDev->getSubNumber(fd);
         mainsize=blockDev->getSize(fd, 0);
         if(pfsCheckZoneSize(zonesize) == 0)
                 return -EINVAL;
         scale = pfsGetScale(zonesize, 512);
         if((clink=pfsCacheAllocClean(&result)))
         {
                 sb = clink->u.superblock;
                 memset(sb, 0, pfsMetaSize);
                 sb->magic = PFS_SUPER_MAGIC;
                 sb->version = PFS_FORMAT_VERSION;
                 sb->modver = ((PFS_MAJOR << 8) | PFS_MINOR);
                 sb->zone_size = zonesize;
                 sb->num_subs = subnumber;
                 sb->log.number = pfsGetBitmapSizeBlocks(scale, mainsize) + (0x2000 >> scale) + 1;
                 sb->log.count = 0x20000 / zonesize ? 0x20000 / zonesize : 1;
                 PFS_PRINTF(PFS_DRV_NAME": Format: log.number = %ld, log.count = %d\n", sb->log.number << scale, sb->log.count);
                 sb->root.count = 1;
                 sb->root.number = sb->log.number + sb->log.count;
                 if((result = pfsJournalResetThis(blockDev, fd, sb->log.number<<scale)) >= 0)
                 {
                         if((cache = pfsCacheAllocClean(&result2)))
{
                                 pfsFillSelfAndParentDentries(cache, &sb->root, &sb->root);
                                 result2 = blockDev->transfer(fd, cache->u.dentry, 0, (sb->root.number+1) << scale,
                                                                                                 1 << pfsBlockSize, 1);
                                 if(result2 == 0)
{
                                         // setup root directory
                                         pfsInodeFill(cache, &sb->root, 0x11FF, 0, 0);
                                         cache->u.inode->data[1].subpart = 0;
                                         cache->u.inode->data[1].number = sb->root.number + 1;
                                         cache->u.inode->data[1].count = 1;
                                         cache->u.inode->checksum = pfsInodeCheckSum(cache->u.inode);
                                         result2=blockDev->transfer(fd, cache->u.inode, 0, sb->root.number << scale,
                                                                                                 1 << pfsBlockSize, 1);
                                 }
                                 pfsCacheFree(cache);
                         }
                         if((result = result2) >= 0)
{
                                 for (i=0; i < subnumber+1; i++)
                                         if((result=pfsFormatSub(blockDev, fd, i, i ? 1 : (0x2000 >> scale) +
                                                                                         sb->log.count + 3, scale, fragment))<0)
                                                 break;
                                 if((result == 0) && ((result = blockDev->transfer(fd, sb, 0, PFS_SUPER_BACKUP_SECTOR, 1, 1))==0))
                                         result = blockDev->transfer(fd, sb, 0, PFS_SUPER_SECTOR, 1, 1);
                         }
                 }
                 pfsCacheFree(clink);
                 blockDev->flushCache(fd);
         }
         return result;
 }
References pfs_inode_t::checksum, pfs_blockinfo_t::count, pfs_inode_t::data, pfs_cache_t::dentry, EINVAL, pfs_block_device_t::flushCache, pfs_block_device_t::getSize, pfs_block_device_t::getSubNumber, pfs_cache_t::inode, memset(), pfs_blockinfo_t::number, PFS_DRV_NAME, PFS_FORMAT_VERSION, PFS_MAJOR, PFS_MINOR, PFS_PRINTF, PFS_SUPER_BACKUP_SECTOR, PFS_SUPER_MAGIC, PFS_SUPER_SECTOR, pfsBlockSize, pfsCacheAllocClean(), pfsCacheFree(), pfsCheckZoneSize(), pfsFillSelfAndParentDentries(), pfsFormatSub(), pfsGetBitmapSizeBlocks(), pfsGetScale(), pfsInodeCheckSum(), pfsInodeFill(), pfsJournalResetThis(), pfsMetaSize, result, sb, pfs_blockinfo_t::subpart, pfs_cache_t::superblock, pfs_block_device_t::transfer, and pfs_cache_t::u.
Referenced by pfsFioFormat().
pfsFormatSub()
int pfsFormatSub (pfs_block_device_t * blockDev, int fd, u32 sub, u32 reserved, u32 scale, u32 fragment)
Definition at line 29 of file superWrite.c.
 {
         pfs_cache_t *cache;
         int i;
         unsigned int j;
         u32 sector, count, size, *b;
         int result = 0;
         size = blockDev->getSize(fd, sub);
         sector = 1 << scale;
         count = pfsGetBitmapSizeSectors(scale, size);
         if (reserved>=2)
                 sector+=0x2000;
         reserved += pfsGetBitmapSizeBlocks(scale, size);
         if((cache = pfsCacheAllocClean(&result)))
         {
                 // fill with fragment pattern
                 for (i=127; i>=0; i--)
                         cache->u.bitmap[i]=fragment;
                 // set as allocated the sectors up to reserved, for the first part of the bitmap
                 // this will mark the area the bitmaps themselves occupy as used
                 for (j=0, b=cache->u.bitmap; j<reserved; j++)
                 {
                         if (j && ((j & 0x1F)==0))
                                 b++;
                         *b |= 1 << (j & 0x1F);
                 }
                 PFS_PRINTF(PFS_DRV_NAME": Format sub: sub = %ld, sector start = %ld, ", sub, sector);
                 // set the rest of the bitmap to the fragment
                 while (count-- && ((result=blockDev->transfer(fd, cache->u.bitmap, sub, sector++, 1, 1))>=0))
                         for (i=127; i>=0; i--)
                                 cache->u.bitmap[i]=fragment;
                 PFS_PRINTF("sector end = %ld\n", sector - 1);
                 pfsCacheFree(cache);
         }
         return result;
 }
References pfs_cache_t::bitmap, pfs_block_device_t::getSize, PFS_DRV_NAME, PFS_PRINTF, pfsCacheAllocClean(), pfsCacheFree(), pfsGetBitmapSizeBlocks(), pfsGetBitmapSizeSectors(), result, pfs_block_device_t::transfer, and pfs_cache_t::u.
Referenced by pfsFormat(), and pfsUpdateSuperBlock().
pfsFreeMem()
void pfsFreeMem (void * buffer)
Definition at line 52 of file misc.c.
 {
 #ifdef _IOP
         int OldState;
         CpuSuspendIntr(&OldState);
         FreeSysMemory(buffer);
         CpuResumeIntr(OldState);
 #else
         free(buffer);
 #endif
 }
References buffer, CpuResumeIntr(), CpuSuspendIntr(), free, and FreeSysMemory().
pfsFreeZones()
void pfsFreeZones (pfs_cache_t * pfree)
Definition at line 644 of file dir.c.
 {
         pfs_blockinfo_t b;
         int result;
         pfs_mount_t *pfsMount = pfree->pfsMount;
         pfs_inode_t *inode = pfree->u.inode;
         u32 nextsegdesc = 1, limit = inode->number_data, i, j = 0, zones;
         pfs_blockinfo_t *bi;
         pfs_cache_t *clink;
         zones = (u32)(inode->size / pfsMount->zsize);
         if(inode->size % pfsMount->zsize)
                 zones++;
         if(inode->number_segdesg + zones == inode->number_blocks)
                 return;
         j = zones;
         b.number = 0;
         clink = pfsCacheUsedAdd(pfree);
         // iterate through each of the block segments used by the inode
         for (i = 1; i < limit && j; i++)
         {
                 if(pfsFixIndex(i) == 0)
                 {
                         if ((clink = pfsBlockGetNextSegment(clink, &result)) == 0)
                                 return;
                         nextsegdesc++;
                 }
                 else
                 {
                         bi = &clink->u.inode->data[pfsFixIndex(i)];
                         if(j < bi->count)
{
                                 bi->count -= j;
                                 b.subpart = bi->subpart;
                                 b.count = j;
                                 b.number = bi->number +
                                         bi->count;
                                 j = 0;
                                 clink->flags |= PFS_CACHE_FLAG_DIRTY;
                         }
                         else
                                 j -= bi->count;
                 }
         }
         pfree->u.inode->number_data = i;
         pfree->u.inode->number_blocks = zones + nextsegdesc;
         pfree->u.inode->number_segdesg = nextsegdesc;
         pfree->u.inode->last_segment.number = clink->u.inode->data[0].number;
         pfree->u.inode->last_segment.subpart= clink->u.inode->data[0].subpart;
         pfree->u.inode->last_segment.count  = clink->u.inode->data[0].count;
         pfree->flags |= PFS_CACHE_FLAG_DIRTY;
         if (b.number)
                 pfsBitmapFreeBlockSegment(pfsMount, &b);
         for( ; i < limit; i++)
         {
                 if (pfsFixIndex(i) == 0)
                 {
                         if((clink = pfsBlockGetNextSegment(clink, &result)) == 0)
                                 return;
                 }
                 bi = &clink->u.inode->data[pfsFixIndex(i)];
                 pfsBitmapFreeBlockSegment(pfsMount, bi);
                 pfsCacheMarkClean(pfsMount, bi->subpart, bi->number<<pfsMount->inode_scale,
                         (bi->number+bi->count)<<pfsMount->inode_scale);
         }
         pfsCacheFree(clink);
 }
References pfs_blockinfo_t::count, pfs_inode_t::data, pfs_cache_t::flags, pfs_cache_t::inode, pfs_mount_t::inode_scale, pfs_inode_t::last_segment, pfs_blockinfo_t::number, pfs_inode_t::number_blocks, pfs_inode_t::number_data, pfs_inode_t::number_segdesg, PFS_CACHE_FLAG_DIRTY, pfsBitmapFreeBlockSegment(), pfsBlockGetNextSegment(), pfsCacheFree(), pfsCacheMarkClean(), pfsCacheUsedAdd(), pfsFixIndex(), pfs_cache_t::pfsMount, result, pfs_inode_t::size, pfs_blockinfo_t::subpart, pfs_cache_t::u, and pfs_mount_t::zsize.
Referenced by openFile(), and pfsFioIoctl2().
pfsFsckStat()
int pfsFsckStat (pfs_mount_t * pfsMount, pfs_super_block_t * superblock, u32 stat, int mode)
Definition at line 112 of file misc.c.
 {       // mode 0=set flag, 1=remove flag, else check stat
         if(pfsMount->blockDev->transfer(pfsMount->fd, superblock, 0, PFS_SUPER_SECTOR, 1,
                 PFS_IO_MODE_READ)==0)
         {
                 switch(mode)
                 {
                         case PFS_MODE_SET_FLAG:
                                 superblock->pfsFsckStat|=stat;
                                 break;
                         case PFS_MODE_REMOVE_FLAG:
                                 superblock->pfsFsckStat&=~stat;
                                 break;
                         default/*PFS_MODE_CHECK_FLAG*/:
                                 return 0 < (superblock->pfsFsckStat & stat);
                 }
                 pfsMount->blockDev->transfer(pfsMount->fd, superblock, 0, PFS_SUPER_SECTOR, 1,
                         PFS_IO_MODE_WRITE);
                 pfsMount->blockDev->flushCache(pfsMount->fd);
         }
         return 0;
 }
References pfs_mount_t::blockDev, pfs_mount_t::fd, pfs_block_device_t::flushCache, PFS_IO_MODE_READ, PFS_IO_MODE_WRITE, PFS_MODE_REMOVE_FLAG, PFS_MODE_SET_FLAG, PFS_SUPER_SECTOR, pfs_super_block_t::pfsFsckStat, and pfs_block_device_t::transfer.
Referenced by devctlFsckStat(), and pfsCacheTransfer().
pfsGetBitmapSizeBlocks()
u32 pfsGetBitmapSizeBlocks (int scale, u32 mainsize)
Definition at line 53 of file super.c.
 {
         u32 a=pfsGetBitmapSizeSectors(scale, mainsize);
         return a / (1<<scale) + ((a % (1<<scale))>0);
 }
References pfsGetBitmapSizeSectors().
Referenced by pfsFormat(), and pfsFormatSub().
pfsGetBitmapSizeSectors()
u32 pfsGetBitmapSizeSectors (int zoneScale, u32 partSize)
Definition at line 41 of file super.c.
 {
         int w, zones = partSize / (1 << zoneScale);
         w = (zones & 7);
         zones = zones / 8 + w;
         w = (zones & 511);
         return zones / 512 + w;
 }
Referenced by pfsFormatSub(), and pfsGetBitmapSizeBlocks().
pfsGetBlockDeviceTable()
pfs_block_device_t* pfsGetBlockDeviceTable (const char * name)
Definition at line 196 of file misc.c.
 {
         char *end;
         char devname[32];
         char *tmp;
         u32 len;
         int i;
         while(name[0] == ' ')
                 name++;
         end = strchr(name, ':');
         if(!end) {
                 PFS_PRINTF(PFS_DRV_NAME": Error: Unknown block device '%s'\n", name);
                 return NULL;
         }
         len = (u32)end - (u32)name;
         strncpy(devname, name, len);
         devname[len] = '\0';
         // Loop until digit is found, then terminate string at that digit.
         // Should then have just the device name left, minus any front spaces or trailing digits.
         tmp = devname;
         while(!(isdigit(tmp[0])))
                 tmp++;
         tmp[0] = '\0';
         for(i = 0; i < NUM_SUPPORTED_DEVICES; i++)
                 if(!strcmp(pfsBlockDeviceCallTable[i].devName, devname))
                         return &pfsBlockDeviceCallTable[i];
         return NULL;
 }
References isdigit, NULL, NUM_SUPPORTED_DEVICES, PFS_DRV_NAME, PFS_PRINTF, pfsBlockDeviceCallTable, strchr(), strcmp(), and strncpy().
Referenced by pfsFioFormat(), and pfsFioMount().
pfsGetDentriesAtPos()
pfs_cache_t* pfsGetDentriesAtPos (pfs_cache_t * clink, u64 position, int * offset, int * result)
Definition at line 122 of file inode.c.
 {
         pfs_blockpos_t blockpos;
         pfs_cache_t *r;
         *result=pfsBlockInitPos(clink, &blockpos, position);
         if (*result)    return 0;
         *offset=blockpos.byte_offset % pfsMetaSize;
         r=pfsGetDentriesChunk(&blockpos, result);
         pfsCacheFree(blockpos.inode);
         return r;
 }
References pfs_blockpos_t::byte_offset, pfs_blockpos_t::inode, pfsBlockInitPos(), pfsCacheFree(), pfsGetDentriesChunk(), pfsMetaSize, and result.
Referenced by pfsDirAddEntry(), and pfsSetDentryParent().
pfsGetDentriesChunk()
pfs_cache_t* pfsGetDentriesChunk (pfs_blockpos_t * position, int * result)
Definition at line 110 of file inode.c.
 {
         pfs_blockinfo_t *bi;
         pfs_mount_t *pfsMount=position->inode->pfsMount;
         bi = &position->inode->u.inode->data[pfsFixIndex(position->block_segment)];
         return pfsCacheGetData(pfsMount, bi->subpart,
                  ((bi->number + position->block_offset) << pfsMount->inode_scale) +
                  position->byte_offset / pfsMetaSize, PFS_CACHE_FLAG_NOTHING, result);
 }
References pfs_blockpos_t::block_offset, pfs_blockpos_t::block_segment, pfs_blockpos_t::byte_offset, pfs_inode_t::data, pfs_cache_t::inode, pfs_blockpos_t::inode, pfs_mount_t::inode_scale, pfs_blockinfo_t::number, PFS_CACHE_FLAG_NOTHING, pfsCacheGetData(), pfsFixIndex(), pfsMetaSize, pfs_cache_t::pfsMount, result, pfs_blockinfo_t::subpart, and pfs_cache_t::u.
Referenced by pfsGetDentriesAtPos(), pfsGetDentry(), and pfsGetNextDentry().
pfsGetDentry()
pfs_cache_t* pfsGetDentry (pfs_cache_t * clink, char * path, pfs_dentry_t ** dentry, u32 * size, int option)
Definition at line 28 of file dir.c.
 {
         pfs_blockpos_t block_pos;
         pfs_dentry_t *d;
         u16 aLen;
         pfs_dentry_t *d2;
         pfs_cache_t *dentCache;
         u32 new_dentryLen=0,dentryLen;
         int len=0, result;
         if (path)
         {
                 len = strlen(path);
                 new_dentryLen = (len+8+3) &~3;
         }
         *size = 0;
         block_pos.inode = pfsCacheUsedAdd(clink);
         block_pos.block_segment = 1;
         block_pos.block_offset = 0;
         block_pos.byte_offset = 0;
         dentCache = pfsGetDentriesChunk(&block_pos, &result);
         if (dentCache != NULL)
         {
                 d2=d=dentCache->u.dentry;
                 while(*size < clink->u.inode->size)
                 {
                         // Read another dentry chunk if we need to
                         if (d2 >= (pfs_dentry_t*)((u8*)dentCache->u.inode + pfsMetaSize))
{
                                 if (pfsInodeSync(&block_pos, pfsMetaSize, clink->u.inode->number_data))
                                         break;
                                 pfsCacheFree(dentCache);
                                 if ((dentCache=pfsGetDentriesChunk(&block_pos, &result)) == NULL)
                                         break;
                                 d=dentCache->u.dentry;
                         }
                         // Scan through the sector.
                         for (d2=(pfs_dentry_t*)((u8*)d+512); d < d2; d=(pfs_dentry_t *)((u8*)d + aLen))
{
                                 aLen=(d->aLen & 0xFFF);
                                 if (aLen & 3){
                                         PFS_PRINTF(PFS_DRV_NAME": Error: dentry allocated length/4 != 0\n");
                                         goto _exit;
                                 }
                                 dentryLen = (d->pLen + 8 + 3) & 0x1FC;
                                 if (aLen < dentryLen){
                                         PFS_PRINTF(PFS_DRV_NAME": Error: dentry is too small\n");
                                         goto _exit;
                                 }
                                 if (d2 < (pfs_dentry_t*)((u8*)d + aLen)){
                                         PFS_PRINTF(PFS_DRV_NAME": Error: dentry across sectors\n");
                                         goto _exit;
                                 }
                                 // decide if the current dentry meets the required criteria, based on 'option'
                                 switch(option)
{
                                         case 0: // result = 1 when paths are equal
                                                 result = (len==d->pLen) && (memcmp(path, d->path, d->pLen)==0);
                                                 break;
                                         case 1: // result = 1 when either there is no inode or if there is enough space remaining in the inode.
                                                 result = ((d->inode) || (aLen < new_dentryLen)) ? (aLen - dentryLen
                                                                 >= new_dentryLen) : 1;
                                                 break;
                                         case 2: // result = 1 when dir path is not empty, "." or ".."
                                                 result = d->pLen && strcmp(d->path, ".") && strcmp(d->path, "..");
                                                 break;
                                         default:
                                                 goto _exit;
                                 }
                                 if (result)
{
                                         *dentry=d;
                                         pfsCacheFree(block_pos.inode);
                                         return dentCache;
                                 }
                                 *size+=aLen;
                         }
                 }
 _exit:          pfsCacheFree(dentCache);
         }
         pfsCacheFree(block_pos.inode);
         return NULL;
 }
References _exit(), pfs_dentry_t::aLen, pfs_blockpos_t::block_offset, pfs_blockpos_t::block_segment, pfs_blockpos_t::byte_offset, pfs_cache_t::dentry, pfs_dentry_t::inode, pfs_cache_t::inode, pfs_blockpos_t::inode, memcmp(), NULL, pfs_inode_t::number_data, pfs_dentry_t::path, PFS_DRV_NAME, PFS_PRINTF, pfsCacheFree(), pfsCacheUsedAdd(), pfsGetDentriesChunk(), pfsInodeSync(), pfsMetaSize, pfs_dentry_t::pLen, result, strcmp(), strlen(), and pfs_cache_t::u.
Referenced by pfsCheckDirForFiles(), pfsDirAddEntry(), pfsDirRemoveEntry(), and pfsInodeGetFileInDir().
pfsGetMaxIndex()
u16 pfsGetMaxIndex (pfs_mount_t * pfsMount)
Definition at line 598 of file dir.c.
 {
         u32 max=0, maxI=0, i, v;
         for (i=0; i < pfsMount->num_subs + 1; i++)  //enumerate all subs
         {
                 v =     (pfsMount->free_zone[i] * (u64)100) /
                         (pfsMount->blockDev->getSize(pfsMount->fd, i) >> pfsMount->sector_scale);
                 if (max < v)
                 {
                         max=v;
                         maxI=i;
                 }
         }
         return maxI;
 }
References pfs_mount_t::blockDev, pfs_mount_t::fd, pfs_mount_t::free_zone, pfs_block_device_t::getSize, pfs_mount_t::num_subs, and pfs_mount_t::sector_scale.
Referenced by pfsInodeCreate().
pfsGetNextDentry()
int pfsGetNextDentry (pfs_cache_t * clink, pfs_blockpos_t * blockpos, u32 * position, char * name, pfs_blockinfo_t * bi)
Definition at line 119 of file dir.c.
 {
         int result;
         pfs_cache_t *dcache;
         pfs_dentry_t *dentry;
         u32 len=0;
         // loop until a non-empty entry is found or until the end of the dentry chunk is reached
         while((len == 0) && (*position < clink->u.inode->size))
         {
                 if (!(dcache=pfsGetDentriesChunk(blockpos, &result)))
                 {
                         PFS_PRINTF(PFS_DRV_NAME": couldnt get dentries chunk for dread!\n");
                         break;
                 }
                 dentry = (pfs_dentry_t*)((u8*)dcache->u.data + (blockpos->byte_offset % pfsMetaSize));
                 len = dentry->pLen;
                 memcpy(name, dentry->path, len);
                 name[len] = '\0';
                 bi->subpart = dentry->sub;
                 bi->number = dentry->inode;
                 pfsCacheFree(dcache);
                 *position += dentry->aLen & 0xFFF;
                 // update blockpos
                 if (pfsInodeSync(blockpos, dentry->aLen & 0xFFF, clink->u.inode->number_data))
                         break;
         }
         return len;
 }
References pfs_dentry_t::aLen, pfs_blockpos_t::byte_offset, pfs_cache_t::data, pfs_dentry_t::inode, pfs_cache_t::inode, memcpy(), pfs_blockinfo_t::number, pfs_inode_t::number_data, pfs_dentry_t::path, PFS_DRV_NAME, PFS_PRINTF, pfsCacheFree(), pfsGetDentriesChunk(), pfsInodeSync(), pfsMetaSize, pfs_dentry_t::pLen, result, pfs_dentry_t::sub, pfs_blockinfo_t::subpart, and pfs_cache_t::u.
Referenced by pfsFioDread().
pfsGetScale()
u32 pfsGetScale (u32 num, u32 size)
Definition at line 155 of file misc.c.
 {
         u32 scale = 0;
         while((size << scale) != num)
                 scale++;
         return scale;
 }
Referenced by pfsFormat(), pfsMountSuperBlock(), and pfsUpdateSuperBlock().
pfsGetTime()
int pfsGetTime (pfs_datetime_t * tm)
Definition at line 65 of file misc.c.
 {
 #ifdef _IOP
         int ret, i;
         sceCdCLOCK      cdtime;
         static pfs_datetime_t timeBuf={
                 0, 7, 6, 5, 4, 3, 2000  // used if can not get time...
         };
         for(i = 0; i < 20; i++)
         {
                 ret = sceCdReadClock(&cdtime);
                 if(ret!=0 && cdtime.stat==0)
                 {
                         timeBuf.sec=btoi(cdtime.second);
                         timeBuf.min=btoi(cdtime.minute);
                         timeBuf.hour=btoi(cdtime.hour);
                         timeBuf.day=btoi(cdtime.day);
                         timeBuf.month=btoi(cdtime.month & 0x7F);        //The old CDVDMAN sceCdReadClock() function does not automatically file off the highest bit.
                         timeBuf.year=btoi(cdtime.year) + 2000;
                         break;
                 } else {
                         if(!(cdtime.stat & 0x80))
                                 break;
                 }
                 DelayThread(100000);
         }
         memcpy(tm, &timeBuf, sizeof(pfs_datetime_t));
 #else
         time_t rawtime;
         struct tm * timeinfo;
         time (&rawtime);
         timeinfo=localtime (&rawtime);
         tm->sec=timeinfo->tm_sec;
         tm->min=timeinfo->tm_min;
         tm->hour=timeinfo->tm_hour;
         tm->day=timeinfo->tm_mday;
         tm->month=timeinfo->tm_mon;
         tm->year=timeinfo->tm_year+1900;
 #endif
         return 0;
 }
References btoi, sceCdCLOCK::day, pfs_datetime_t::day, DelayThread(), sceCdCLOCK::hour, pfs_datetime_t::hour, memcpy(), pfs_datetime_t::min, sceCdCLOCK::minute, sceCdCLOCK::month, pfs_datetime_t::month, sceCdReadClock(), pfs_datetime_t::sec, sceCdCLOCK::second, sceCdCLOCK::stat, sceCdCLOCK::year, and pfs_datetime_t::year.
Referenced by pfsInodeFill(), and pfsInodeSetTime().
pfsInodeCheckSum()
int pfsInodeCheckSum (pfs_inode_t * inode)
Definition at line 36 of file inode.c.
 {
         u32 *ptr=(u32 *)inode;
         u32 sum=0;
         int i;
         for(i=1; i < 256; i++)
                 sum+=ptr[i];
         return sum;
 }
Referenced by pfsCacheTransfer(), pfsFormat(), and pfsJournalWrite().
pfsInodeCreate()
pfs_cache_t* pfsInodeCreate (pfs_cache_t * clink, u16 mode, u16 uid, u16 gid, int * result)
Definition at line 493 of file dir.c.
 {
         pfs_blockinfo_t a, b;
         pfs_mount_t *pfsMount=clink->pfsMount;
         u32 j;
         u32 i;
         pfs_cache_t *inode;
         if ((mode & FIO_S_IFMT) == FIO_S_IFDIR)
         {
                 if (pfsMount->num_subs > clink->u.inode->subpart)
                         clink->u.inode->subpart++;
                 else
                         clink->u.inode->subpart=0;
                 a.number =0;
                 a.subpart=clink->u.inode->subpart;
                 j= (pfsMount->zfree * (u64)100) / pfsMount->total_zones;
                 i= (pfsMount->free_zone[a.subpart] * (u64)100) /
                         (pfsMount->blockDev->getSize(pfsMount->fd, a.subpart) >> pfsMount->sector_scale);
                 if ((i < j) && ((j-i) >= 11))
                         a.subpart=pfsGetMaxIndex(pfsMount);
         }else{
                 a.number=clink->u.inode->inode_block.number;
                 a.subpart=clink->u.inode->inode_block.subpart;
                 a.count=clink->u.inode->inode_block.count;
         }
         a.count=1;
         // Search for a free zone, starting from parent dir inode block
         *result=pfsBitmapSearchFreeZone(pfsMount, &a, 2);
         if (*result<0)  return 0;
         inode=pfsCacheGetData(pfsMount, a.subpart, a.number << pfsMount->inode_scale,
                         PFS_CACHE_FLAG_SEGD | PFS_CACHE_FLAG_NOLOAD, result);
         if (inode == NULL)
                 return NULL;
         // Initialise the inode (which has been allocate blocks specified by a)
         pfsInodeFill(inode, (pfs_blockinfo_t*)&a, mode, uid, gid);
         if ((mode & FIO_S_IFMT) != FIO_S_IFDIR)
                 return inode;
         b.number=a.number;
         b.subpart=a.subpart;
         b.count=a.count;
         *result=pfsBitmapSearchFreeZone(pfsMount, (pfs_blockinfo_t*)&a, 0);
         if (*result<0){
                 pfsCacheFree(inode);
                 pfsBitmapFreeBlockSegment(pfsMount, (pfs_blockinfo_t*)&b);
                 return NULL;
         }
         inode->u.inode->data[1].number=a.number;
         inode->u.inode->data[1].subpart=a.subpart;
         inode->u.inode->data[1].count =a.count;
         return inode;
 }
References pfs_mount_t::blockDev, pfs_blockinfo_t::count, pfs_inode_t::data, pfs_mount_t::fd, FIO_S_IFDIR, FIO_S_IFMT, pfs_mount_t::free_zone, pfs_block_device_t::getSize, pfs_cache_t::inode, pfs_inode_t::inode_block, pfs_mount_t::inode_scale, NULL, pfs_mount_t::num_subs, pfs_blockinfo_t::number, PFS_CACHE_FLAG_NOLOAD, PFS_CACHE_FLAG_SEGD, pfsBitmapFreeBlockSegment(), pfsBitmapSearchFreeZone(), pfsCacheFree(), pfsCacheGetData(), pfsGetMaxIndex(), pfsInodeFill(), pfs_cache_t::pfsMount, result, pfs_mount_t::sector_scale, pfs_blockinfo_t::subpart, pfs_inode_t::subpart, pfs_mount_t::total_zones, pfs_cache_t::u, and pfs_mount_t::zfree.
Referenced by openFile().
pfsInodeFill()
void pfsInodeFill (pfs_cache_t * ci, pfs_blockinfo_t * bi, u16 mode, u16 uid, u16 gid)
Definition at line 334 of file dir.c.
 {
         u32 val;
         memset(ci->u.inode, 0, pfsMetaSize);
         ci->u.inode->magic=PFS_SEGD_MAGIC;
         ci->u.inode->inode_block.number=bi->number;
         ci->u.inode->inode_block.subpart=bi->subpart;
         ci->u.inode->inode_block.count=bi->count;
         ci->u.inode->last_segment.number=bi->number;
         ci->u.inode->last_segment.subpart=bi->subpart;
         ci->u.inode->last_segment.count=bi->count;
         ci->u.inode->mode=mode;
         ci->u.inode->uid=uid;
         ci->u.inode->gid=gid;
         if ((mode & FIO_S_IFMT) == FIO_S_IFDIR){
                 ci->u.inode->attr=0xA0;
                 ci->u.inode->size=sizeof(pfs_dentry_t);
                 val=2;
         }else{
                 ci->u.inode->size=0;
                 val=1;
         }
         ci->u.inode->number_data=val;
         ci->u.inode->number_blocks=val;
         pfsGetTime(&ci->u.inode->ctime);
         memcpy(&ci->u.inode->atime, &ci->u.inode->ctime, sizeof(pfs_datetime_t));
         memcpy(&ci->u.inode->mtime, &ci->u.inode->ctime, sizeof(pfs_datetime_t));
         ci->u.inode->number_segdesg=1;
         ci->u.inode->data[0].number =bi->number;
         ci->u.inode->data[0].subpart=bi->subpart;
         ci->u.inode->data[0].count  =bi->count;
         ci->u.inode->subpart=bi->subpart;
         ci->flags |= PFS_CACHE_FLAG_DIRTY;
 }
References pfs_inode_t::atime, pfs_inode_t::attr, pfs_blockinfo_t::count, pfs_inode_t::ctime, pfs_inode_t::data, FIO_S_IFDIR, FIO_S_IFMT, pfs_cache_t::flags, pfs_inode_t::gid, pfs_cache_t::inode, pfs_inode_t::inode_block, pfs_inode_t::last_segment, pfs_inode_t::magic, memcpy(), memset(), pfs_inode_t::mode, pfs_inode_t::mtime, pfs_blockinfo_t::number, pfs_inode_t::number_blocks, pfs_inode_t::number_data, pfs_inode_t::number_segdesg, PFS_CACHE_FLAG_DIRTY, PFS_SEGD_MAGIC, pfsGetTime(), pfsMetaSize, pfs_inode_t::size, pfs_blockinfo_t::subpart, pfs_inode_t::subpart, pfs_cache_t::u, and pfs_inode_t::uid.
Referenced by pfsFormat(), and pfsInodeCreate().
pfsInodeGetData()
pfs_cache_t* pfsInodeGetData (pfs_mount_t * pfsMount, u16 sub, u32 inode, int * result)
Definition at line 47 of file inode.c.
 {
         return pfsCacheGetData(pfsMount, sub, inode << pfsMount->inode_scale,
                                 PFS_CACHE_FLAG_SEGD, result);
 }
References pfs_mount_t::inode_scale, PFS_CACHE_FLAG_SEGD, pfsCacheGetData(), and result.
Referenced by pfsFioDread(), pfsInodeGetFileInDir(), and pfsInodeGetParent().
pfsInodeGetFile()
pfs_cache_t* pfsInodeGetFile (pfs_mount_t * pfsMount, pfs_cache_t * clink, const char * name, int * result)
Definition at line 320 of file dir.c.
{
         char path[256];
         pfs_cache_t *c,*fileInode;
         c=pfsInodeGetParent(pfsMount, clink, name, path, result);
         if (c){
                 fileInode=pfsInodeGetFileInDir(c, path, result);
                 pfsCacheFree(c);
                 return fileInode;
         }
         return NULL;
 }
References NULL, pfsCacheFree(), pfsInodeGetFileInDir(), pfsInodeGetParent(), and result.
Referenced by pfsFioChdir(), pfsFioChstat(), pfsFioGetstat(), pfsFioReadlink(), and pfsInodeGetParent().
pfsInodeGetFileInDir()
pfs_cache_t* pfsInodeGetFileInDir (pfs_cache_t * dirInode, char * path, int * result)
Definition at line 289 of file dir.c.
 {
         pfs_dentry_t *dentry;
         u32     size;
         pfs_cache_t *clink;
         if (path[0]==0)
                 return pfsCacheUsedAdd(dirInode);
         // If we're in the root dir, don't do anything for ".."
         if ((dirInode->block ==
              dirInode->pfsMount->root_dir.number << dirInode->pfsMount->inode_scale) &&
             (dirInode->sub    == dirInode->pfsMount->root_dir.subpart) &&
             (strcmp(path, "..") == 0))
                 return pfsCacheUsedAdd(dirInode);
         if ((*result=pfsCheckAccess(dirInode, 1)) < 0)
                 return NULL;
         // Get dentry of file/dir specified by path from the dir pointed to
         // by the inode (dirInode). Then return the cached inode for that dentry.
         if ((clink=pfsGetDentry(dirInode, path, &dentry, &size, 0))){
                 pfsCacheFree(clink);
                 return pfsInodeGetData(dirInode->pfsMount,
                         dentry->sub, dentry->inode, result);
         }
         *result=-ENOENT;
         return NULL;
 }
References pfs_cache_t::block, ENOENT, pfs_dentry_t::inode, pfs_mount_t::inode_scale, NULL, pfs_blockinfo_t::number, pfsCacheFree(), pfsCacheUsedAdd(), pfsCheckAccess(), pfsGetDentry(), pfsInodeGetData(), pfs_cache_t::pfsMount, result, pfs_mount_t::root_dir, strcmp(), pfs_dentry_t::sub, pfs_cache_t::sub, and pfs_blockinfo_t::subpart.
Referenced by _remove(), openFile(), pfsFioRename(), pfsInodeGetFile(), and pfsInodeGetParent().
pfsInodeGetParent()
pfs_cache_t* pfsInodeGetParent (pfs_mount_t * pfsMount, pfs_cache_t * clink, const char * filename, char * path, int * result)
Definition at line 384 of file dir.c.
 {
         static int pfsSymbolicLinks = 0;
         pfs_cache_t *link, *inode;
         char *filename2=(char*)filename;
         if (filename2[0]==0)
         {
                 *result=-ENOENT;
                 if (clink)      pfsCacheFree(clink);
                 return NULL;
         }
         if (filename2[0] == '/')
         {
                 // Get inode for root dir
                 if (clink)      pfsCacheFree(clink);
                 if ((clink=pfsInodeGetData(pfsMount, pfsMount->root_dir.subpart,
                                           pfsMount->root_dir.number, result))==0)
                         return NULL;
         }
         else if (clink==NULL)
         {
                 // Otherwise if relative path, get inode for current dir
                 if ((clink=pfsInodeGetData(pfsMount, pfsMount->current_dir.subpart,
                                           pfsMount->current_dir.number, result))==0)
                         return NULL;
         }
         do
         {
                 filename2=pfsSplitPath(filename2, path, result);
                 if (filename2==NULL)    return NULL;
                 // If we've reached the end of the path, then we want to return
                 // the cached inode for the directory which holds the file/dir in path
                 if (filename2[0]==0)
                 {
                         if ((clink->u.inode->mode & FIO_S_IFMT) == FIO_S_IFDIR)
                                 return clink;
                         pfsCacheFree(clink);
                         *result=-ENOTDIR;       // not a directory
                         return NULL;
                 }
                 inode=pfsInodeGetFileInDir(clink, path, result);
                 if (inode && ((inode->u.inode->mode & FIO_S_IFMT) == FIO_S_IFLNK))
                 {
                         if (pfsSymbolicLinks >= 4)
{
                                 *result=-ELOOP; // too many symbolic links
                                 pfsCacheFree(clink);
                                 pfsCacheFree(inode);
                                 return NULL;
                         }
                         pfsSymbolicLinks++;
                         link=pfsInodeGetFile(pfsMount, clink, (char*)&inode->u.inode->data[1], result);
                         pfsSymbolicLinks--;
                         clink=inode;
                         if (link==0)
{
                                 pfsCacheFree(inode);
                                 return NULL;
                         }
                         inode=link;
                 }
                 pfsCacheFree(clink);
                 clink=inode;
         } while (inode);
         return NULL;
 }
References pfs_mount_t::current_dir, pfs_inode_t::data, ELOOP, ENOENT, ENOTDIR, FIO_S_IFDIR, FIO_S_IFLNK, FIO_S_IFMT, pfs_cache_t::inode, pfs_inode_t::mode, NULL, pfs_blockinfo_t::number, pfsCacheFree(), pfsInodeGetData(), pfsInodeGetFile(), pfsInodeGetFileInDir(), pfsSplitPath(), result, pfs_mount_t::root_dir, pfs_blockinfo_t::subpart, and pfs_cache_t::u.
Referenced by _remove(), openFile(), pfsFioRename(), and pfsInodeGetFile().
pfsInodePrint()
void pfsInodePrint (pfs_inode_t * inode)
Definition at line 29 of file inode.c.
 {
         PFS_PRINTF(PFS_DRV_NAME": pfsInodePrint: Checksum = 0x%lX, Magic = 0x%lX\n", inode->checksum, inode->magic);
         PFS_PRINTF(PFS_DRV_NAME":     Mode = 0x%X, attr = 0x%X\n", inode->mode, inode->attr);
         PFS_PRINTF(PFS_DRV_NAME":     size = 0x%08lX%08lX\n", (u32)(inode->size >> 32), (u32)(inode->size));
 }
References pfs_inode_t::attr, pfs_inode_t::checksum, pfs_inode_t::magic, pfs_inode_t::mode, PFS_DRV_NAME, PFS_PRINTF, and pfs_inode_t::size.
pfsInodeRemove()
int pfsInodeRemove (pfs_cache_t * parent, pfs_cache_t * inode, char * path)
Definition at line 467 of file dir.c.
 {
         pfs_cache_t *entry;
         int rv=0;
         if((entry=pfsDirRemoveEntry(parent, path))!=NULL)
         {
                 pfsInodeSetTimeParent(parent, entry);
                 pfsCacheFree(entry);
         }
         else
                 rv=-ENOENT;
         pfsCacheFree(parent);
         if(rv==0)
         {
                 inode->flags&=~PFS_CACHE_FLAG_DIRTY;
                 pfsBitmapFreeInodeBlocks(inode);
                 //if(parent->pfsMount->flags & PFS_FIO_ATTR_WRITEABLE)  //Not checked for in late versions of PFS.
                 pfsCacheFlushAllDirty(parent->pfsMount);
         }
         pfsCacheFree(inode);
         return rv;
 }
References ENOENT, pfs_cache_t::flags, NULL, PFS_CACHE_FLAG_DIRTY, pfsBitmapFreeInodeBlocks(), pfsCacheFlushAllDirty(), pfsCacheFree(), pfsDirRemoveEntry(), pfsInodeSetTimeParent(), and pfs_cache_t::pfsMount.
Referenced by _remove().
pfsInodeSetTime()
void pfsInodeSetTime (pfs_cache_t * clink)
Definition at line 53 of file inode.c.
 {       // set the inode time's in cache
         pfsGetTime(&clink->u.inode->mtime);
         memcpy(&clink->u.inode->ctime, &clink->u.inode->mtime, sizeof(pfs_datetime_t));
         memcpy(&clink->u.inode->atime, &clink->u.inode->mtime, sizeof(pfs_datetime_t));
         clink->flags|=PFS_CACHE_FLAG_DIRTY;
 }
References pfs_inode_t::atime, pfs_inode_t::ctime, pfs_cache_t::flags, pfs_cache_t::inode, memcpy(), pfs_inode_t::mtime, PFS_CACHE_FLAG_DIRTY, pfsGetTime(), and pfs_cache_t::u.
Referenced by pfsFioCloseFileSlot(), and pfsInodeSetTimeParent().
pfsInodeSetTimeParent()
void pfsInodeSetTimeParent (pfs_cache_t * parent, pfs_cache_t * self)
Definition at line 61 of file inode.c.
 {       // set the inode time's in cache
         pfsInodeSetTime(parent);
         self->flags|=PFS_CACHE_FLAG_DIRTY;
 }
References PFS_CACHE_FLAG_DIRTY, and pfsInodeSetTime().
Referenced by openFile(), pfsFioRename(), and pfsInodeRemove().
pfsInodeSync()
int pfsInodeSync (pfs_blockpos_t * blockpos, u64 size, u32 used_segments)
Definition at line 67 of file inode.c.
 {
         int result=0;
         u32 i;
         u16 count;
         for(i=pfsBlockSyncPos(blockpos, size); i; )
         {
                 count=blockpos->inode->u.inode->data[pfsFixIndex(blockpos->block_segment)].count;
                 i+=blockpos->block_offset;
                 if (i < count){
                         blockpos->block_offset=i;
                         break;
                 }
                 i-=count;
                 if (blockpos->block_segment + 1 == used_segments)
                 {
                         blockpos->block_offset=count;
                         if (i || blockpos->byte_offset){
                                 PFS_PRINTF(PFS_DRV_NAME": panic: fp exceeds file.\n");
                                 return -EINVAL;
                         }
                 }else{
                         blockpos->block_offset=0;
                         blockpos->block_segment++;
                 }
                 if (pfsFixIndex(blockpos->block_segment))
                         continue;
                 if ((blockpos->inode = pfsBlockGetNextSegment(blockpos->inode, &result)) == 0)
                         break;
                 i++;
         }
         return result;
 }
References pfs_blockpos_t::block_offset, pfs_blockpos_t::block_segment, pfs_blockpos_t::byte_offset, pfs_blockinfo_t::count, pfs_inode_t::data, EINVAL, pfs_cache_t::inode, pfs_blockpos_t::inode, PFS_DRV_NAME, PFS_PRINTF, pfsBlockGetNextSegment(), pfsBlockSyncPos(), pfsFixIndex(), result, and pfs_cache_t::u.
Referenced by pfsBlockInitPos(), pfsGetDentry(), and pfsGetNextDentry().
pfsJournalChecksum()
int pfsJournalChecksum (void * header)
Definition at line 34 of file journal.c.
 {
         u32 *ptr=(u32 *)header;
         u32 sum=0;
         int i;
         for(i=2; i < 256; i++)
                 sum+=ptr[i];
         return sum & 0xFFFF;
 }
Referenced by pfsJournalFlush(), and pfsJournalRestore().
pfsJournalFlush()
int pfsJournalFlush (pfs_mount_t * pfsMount)
Definition at line 91 of file journal.c.
 {// this write any thing that in are journal buffer :)
         int rv;
         pfsMount->blockDev->flushCache(pfsMount->fd);
         pfsJournalBuf.checksum=pfsJournalChecksum(&pfsJournalBuf);
         rv=pfsMount->blockDev->transfer(pfsMount->fd, &pfsJournalBuf, 0,
                 (pfsMount->log.number << pfsMount->sector_scale), 2, PFS_IO_MODE_WRITE);
         pfsMount->blockDev->flushCache(pfsMount->fd);
         return rv;
 }
References pfs_mount_t::blockDev, pfs_journal_t::checksum, pfs_mount_t::fd, pfs_block_device_t::flushCache, pfs_mount_t::log, pfs_blockinfo_t::number, PFS_IO_MODE_WRITE, pfsJournalBuf, pfsJournalChecksum(), pfs_mount_t::sector_scale, and pfs_block_device_t::transfer.
Referenced by pfsJournalWrite().
pfsJournalReset()
int pfsJournalReset (pfs_mount_t * pfsMount)
Definition at line 68 of file journal.c.
 {
         int rv;
         memset(&pfsJournalBuf, 0, sizeof(pfs_journal_t));
         pfsJournalBuf.magic=PFS_JOUNRNAL_MAGIC;
         pfsMount->blockDev->flushCache(pfsMount->fd);
         rv = pfsMount->blockDev->transfer(pfsMount->fd, &pfsJournalBuf, 0,
                 (pfsMount->log.number << pfsMount->sector_scale), 2, PFS_IO_MODE_WRITE);
         pfsMount->blockDev->flushCache(pfsMount->fd);
         return rv;
 }
References pfs_mount_t::blockDev, pfs_mount_t::fd, pfs_block_device_t::flushCache, pfs_mount_t::log, pfs_journal_t::magic, memset(), pfs_blockinfo_t::number, PFS_IO_MODE_WRITE, PFS_JOUNRNAL_MAGIC, pfsJournalBuf, pfs_mount_t::sector_scale, and pfs_block_device_t::transfer.
Referenced by pfsCacheFlushAllDirty(), and pfsJournalRestore().
pfsJournalResetThis()
int pfsJournalResetThis (pfs_block_device_t * blockDev, int fd, u32 sector)
Definition at line 84 of file journal.c.
 {
         memset(&pfsJournalBuf, 0, sizeof(pfs_journal_t));
         pfsJournalBuf.magic=PFS_JOUNRNAL_MAGIC;
         return blockDev->transfer(fd, &pfsJournalBuf, 0, sector, 2, 1);
 }
References pfs_journal_t::magic, memset(), PFS_JOUNRNAL_MAGIC, pfsJournalBuf, and pfs_block_device_t::transfer.
Referenced by pfsFormat().
pfsJournalRestore()
int pfsJournalRestore (pfs_mount_t * pfsMount)
Definition at line 106 of file journal.c.
 {
         int rv;
         int result;
         pfs_cache_t *clink;
         u32 i;
         // Read journal buffer from disk
         rv = pfsMount->blockDev->transfer(pfsMount->fd, &pfsJournalBuf, 0,
                 (pfsMount->log.number << pfsMount->sector_scale), 2, PFS_IO_MODE_READ);
         if(rv || (pfsJournalBuf.magic != PFS_JOUNRNAL_MAGIC) ||
                 (pfsJournalBuf.checksum != (u16)pfsJournalChecksum(&pfsJournalBuf)))
                 {
                         PFS_PRINTF(PFS_DRV_NAME": Error: cannot read log/invalid log\n");
                         return pfsJournalReset(pfsMount);
                 }
         if(pfsJournalBuf.num == 0)
         {
                 return pfsJournalReset(pfsMount);
         }
         clink = pfsCacheAllocClean(&result);
         if(!clink)
                 return result;
         for(i = 0; i < pfsJournalBuf.num; i++)
         {
                 PFS_PRINTF(PFS_DRV_NAME": Log overwrite %d:%08lx\n", pfsJournalBuf.log[i].sub, pfsJournalBuf.log[i].sector);
                 // Read data in from log section on disk into cache buffer
                 rv = pfsMount->blockDev->transfer(pfsMount->fd, clink->u.data, 0,
                         (pfsMount->log.number << pfsMount->sector_scale) + pfsJournalBuf.log[i].logSector, 2,
                         PFS_IO_MODE_READ);
                 // Write from cache buffer into destination location on disk
                 if(!rv)
                         pfsMount->blockDev->transfer(pfsMount->fd, clink->u.data, pfsJournalBuf.log[i].sub,
                                 pfsJournalBuf.log[i].sector, 2, PFS_IO_MODE_WRITE);
         }
         pfsCacheFree(clink);
         return pfsJournalReset(pfsMount);
 }
References pfs_mount_t::blockDev, pfs_journal_t::checksum, pfs_cache_t::data, pfs_mount_t::fd, pfs_journal_t::log, pfs_mount_t::log, pfs_journal_t::logSector, pfs_journal_t::magic, pfs_journal_t::num, pfs_blockinfo_t::number, PFS_DRV_NAME, PFS_IO_MODE_READ, PFS_IO_MODE_WRITE, PFS_JOUNRNAL_MAGIC, PFS_PRINTF, pfsCacheAllocClean(), pfsCacheFree(), pfsJournalBuf, pfsJournalChecksum(), pfsJournalReset(), result, pfs_journal_t::sector, pfs_mount_t::sector_scale, pfs_journal_t::sub, pfs_block_device_t::transfer, and pfs_cache_t::u.
Referenced by pfsMountSuperBlock().
pfsJournalWrite()
void pfsJournalWrite (pfs_mount_t * pfsMount, pfs_cache_t * clink, u32 pfsCacheNumBuffers)
Definition at line 44 of file journal.c.
 {
         u32 i=0;
         u32 logSector=2;
         for(i=0; i <pfsCacheNumBuffers;i++)
         {
                 if((clink[i].flags & PFS_CACHE_FLAG_DIRTY) && clink[i].pfsMount == pfsMount) {
                         if(clink[i].flags & (PFS_CACHE_FLAG_SEGD|PFS_CACHE_FLAG_SEGI))
                                 clink[i].u.inode->checksum=pfsInodeCheckSum(clink[i].u.inode);
                         pfsJournalBuf.log[pfsJournalBuf.num].sector = clink[i].block << pfsBlockSize;
                         pfsJournalBuf.log[pfsJournalBuf.num].sub = clink[i].sub;
                         pfsJournalBuf.log[pfsJournalBuf.num].logSector = logSector;
                         pfsJournalBuf.num+=1;
                 }
                 logSector+=2;
         }
         if(pfsMount->blockDev->transfer(pfsMount->fd, clink->u.inode, 0,
                 (pfsMount->log.number << pfsMount->sector_scale) + 2, pfsCacheNumBuffers*2,
                         PFS_IO_MODE_WRITE)>=0)
                                 pfsJournalFlush(pfsMount);
 }
References pfs_cache_t::block, pfs_mount_t::blockDev, pfs_inode_t::checksum, pfs_mount_t::fd, pfs_cache_t::inode, pfs_journal_t::log, pfs_mount_t::log, pfs_journal_t::logSector, pfs_journal_t::num, pfs_blockinfo_t::number, PFS_CACHE_FLAG_DIRTY, PFS_CACHE_FLAG_SEGD, PFS_CACHE_FLAG_SEGI, PFS_IO_MODE_WRITE, pfsBlockSize, pfsCacheNumBuffers, pfsInodeCheckSum(), pfsJournalBuf, pfsJournalFlush(), pfs_journal_t::sector, pfs_mount_t::sector_scale, pfs_journal_t::sub, pfs_cache_t::sub, pfs_block_device_t::transfer, and pfs_cache_t::u.
Referenced by pfsCacheFlushAllDirty().
pfsMountSuperBlock()
int pfsMountSuperBlock (pfs_mount_t * pfsMount)
Definition at line 174 of file superWrite.c.
 {
         int result;
         pfs_cache_t *clink;
         pfs_super_block_t *superblock;
         u32 sub;
         u32 i;
         // Get number of sub partitions attached to the main partition
         sub = pfsMount->blockDev->getSubNumber(pfsMount->fd);
         // Allocate a cache entry for the superblock
         clink = pfsCacheAllocClean(&result);
         if(!clink)
                 return result;
         superblock = clink->u.superblock;
         // Read the suprerblock from the main partition
         result = pfsMount->blockDev->transfer(pfsMount->fd, superblock, 0, PFS_SUPER_SECTOR, 1, PFS_IO_MODE_READ);
         if(result) goto error;
         if((superblock->magic != PFS_SUPER_MAGIC) || (superblock->version > PFS_FORMAT_VERSION))
         {
                 PFS_PRINTF(PFS_DRV_NAME": Error: Invalid magic/version\n");
                 pfsCacheFree(clink);
                 return -EIO;
         }
         if(!pfsCheckZoneSize(superblock->zone_size))
                 result = -EIO;
         if((superblock->pfsFsckStat & PFS_FSCK_STAT_WRITE_ERROR) && (pfsMount->flags & PFS_FIO_ATTR_EXECUTABLE))
                 result = -EIO;
         if(sub < superblock->num_subs)
         {
                 PFS_PRINTF(PFS_DRV_NAME": Error: Filesystem larger than partition\n");
                 result = -EIO;
         }
         if(result) goto error;
         // If new subs have been added, update filesystem
         if(superblock->num_subs < sub)
         {
                 PFS_PRINTF(PFS_DRV_NAME": New subs added, updating filesystem..\n");
                 result = pfsUpdateSuperBlock(pfsMount, superblock, sub);
         }
         if(result) goto error;
         pfsMount->zsize = superblock->zone_size;
         pfsMount->sector_scale = pfsGetScale(pfsMount->zsize, 512);
         pfsMount->inode_scale = pfsGetScale(pfsMount->zsize, pfsMetaSize);
         pfsMount->num_subs = superblock->num_subs;
         memcpy(&pfsMount->root_dir, &superblock->root, sizeof(pfs_blockinfo_t));
         memcpy(&pfsMount->log, &superblock->log, sizeof(pfs_blockinfo_t));
         memcpy(&pfsMount->current_dir, &superblock->root, sizeof(pfs_blockinfo_t));
         pfsMount->total_zones = 0;
         // Do a journal restore (in case of un-clean unmount)
         pfsJournalRestore(pfsMount);
         // Calculate free space and total size
         for(i = 0; i < (pfsMount->num_subs + 1); i++)
         {
                 int free;
                 pfsMount->total_zones += pfsMount->blockDev->getSize(pfsMount->fd, i) >> pfsMount->sector_scale;
                 free = pfsBitmapCalcFreeZones(pfsMount, i);
                 pfsMount->free_zone[i] = free;
                 pfsMount->zfree += free;
         }
 error:
         pfsCacheFree(clink);
         return result;
 }
References pfs_mount_t::blockDev, pfs_mount_t::current_dir, EIO, pfs_mount_t::fd, pfs_mount_t::flags, free, pfs_mount_t::free_zone, pfs_block_device_t::getSize, pfs_block_device_t::getSubNumber, pfs_mount_t::inode_scale, pfs_super_block_t::log, pfs_mount_t::log, pfs_super_block_t::magic, memcpy(), pfs_super_block_t::num_subs, pfs_mount_t::num_subs, PFS_DRV_NAME, PFS_FIO_ATTR_EXECUTABLE, PFS_FORMAT_VERSION, PFS_FSCK_STAT_WRITE_ERROR, PFS_IO_MODE_READ, PFS_PRINTF, PFS_SUPER_MAGIC, PFS_SUPER_SECTOR, pfsBitmapCalcFreeZones(), pfsCacheAllocClean(), pfsCacheFree(), pfsCheckZoneSize(), pfs_super_block_t::pfsFsckStat, pfsGetScale(), pfsJournalRestore(), pfsMetaSize, pfsUpdateSuperBlock(), result, pfs_super_block_t::root, pfs_mount_t::root_dir, pfs_mount_t::sector_scale, pfs_cache_t::superblock, pfs_mount_t::total_zones, pfs_block_device_t::transfer, pfs_cache_t::u, pfs_super_block_t::version, pfs_mount_t::zfree, pfs_super_block_t::zone_size, and pfs_mount_t::zsize.
Referenced by mountDevice().
pfsPrintBitmap()
void pfsPrintBitmap (const u32 * bitmap)
Definition at line 137 of file misc.c.
{
         u32 i, j;
         char a[48+1], b[16+1];
         b[16]=0;
         for (i=0; i < 32; i++){
                 memset(a, 0, 49);
                 for (j=0; j < 16; j++){
                         const char *c=(const char*)bitmap+j+i*16;
                         sprintf(a+j*3, "%02x ", *c);
                         b[j] = ((*c>=0) && (isgraph(*c))) ?
                                 *c : '.';
                 }
                 PFS_PRINTF("%s%s\n", a, b);
         }
 }
References isgraph, memset(), PFS_PRINTF, and sprintf().
Referenced by pfsBitmapShow().
pfsSetDentryParent()
pfs_cache_t* pfsSetDentryParent (pfs_cache_t * clink, pfs_blockinfo_t * bi, int * result)
Definition at line 273 of file dir.c.
 {
         int offset;
         pfs_cache_t *dcache;
         dcache=pfsGetDentriesAtPos(clink, 0, &offset, result);
         if (dcache){
                 pfs_dentry_t *d=(pfs_dentry_t*)(12+(u8*)dcache->u.data);
                 d->inode=bi->number;
                 d->sub  =(u8)bi->subpart;
         }
         return dcache;
 }
References pfs_cache_t::data, pfs_dentry_t::inode, pfs_blockinfo_t::number, pfsGetDentriesAtPos(), result, pfs_dentry_t::sub, pfs_blockinfo_t::subpart, and pfs_cache_t::u.
Referenced by pfsFioRename().
pfsSplitPath()
char* pfsSplitPath (char * filename, char * path, int * result)
Definition at line 569 of file dir.c.
 {
         int i=0;
         int j=0;
         for (i=0; filename[i] == '/'; i++)
                 ;
         for (; i<1024 && filename[i] != '/'; i++){
                 if (filename[i] == 0)   break;
                 if (j < 255)
                         path[j++] = filename[i];
         }
         if (j<256)
                 path[j]=0;
         while (filename[i] == '/')
                 if (i<1024)
                         i++;
                 else
                         break;
         if (i<1024)
                 return &filename[i];
         *result=-ENAMETOOLONG;
         return 0;
 }
References ENAMETOOLONG, and result.
Referenced by pfsInodeGetParent().
pfsUpdateSuperBlock()
int pfsUpdateSuperBlock (pfs_mount_t * pfsMount, pfs_super_block_t * superblock, u32 sub)
Definition at line 147 of file superWrite.c.
 {
         u32 scale;
         u32 i;
         int rv;
         scale = pfsGetScale(superblock->zone_size, 512);
         for(i = superblock->num_subs + 1; i < sub + 1; i++)
         {
                 rv = pfsFormatSub(pfsMount->blockDev, pfsMount->fd, i, 1, scale, 0);
                 if(rv < 0)
                         return rv;
         }
         superblock->num_subs = sub;
         // Write superblock, then write backup
         rv = pfsMount->blockDev->transfer(pfsMount->fd, superblock, 0, PFS_SUPER_SECTOR, 1, PFS_IO_MODE_WRITE);
         if(!rv)
                 rv = pfsMount->blockDev->transfer(pfsMount->fd, superblock, 0, PFS_SUPER_BACKUP_SECTOR, 1, PFS_IO_MODE_WRITE);
         pfsMount->blockDev->flushCache(pfsMount->fd);
         return rv;
 }
References pfs_mount_t::blockDev, pfs_mount_t::fd, pfs_block_device_t::flushCache, pfs_super_block_t::num_subs, PFS_IO_MODE_WRITE, PFS_SUPER_BACKUP_SECTOR, PFS_SUPER_SECTOR, pfsFormatSub(), pfsGetScale(), pfs_block_device_t::transfer, and pfs_super_block_t::zone_size.
Referenced by pfsMountSuperBlock().