ps2sdk: common/include/libsd-common.h File Reference
libsd-common.h File Reference
#include <tamtypes.h>
Data Structures
struct sceSdBatch
struct sceSdEffectAttr
Macros
#define SD_VOICE(_core, _v) ((_core)|((_v)<<1))
#define SD_ADSR_AR_LINEARi 0
#define SD_ADSR_AR_EXPi 1
#define SD_ADSR_SR_LINEARi 0
#define SD_ADSR_SR_LINEARd 2
#define SD_ADSR_SR_EXPi 4
#define SD_ADSR_SR_EXPd 6
#define SD_ADSR_RR_LINEARd 0
#define SD_ADSR_RR_EXPd 1
#define SD_SET_ADSR1(_arm, _ar, _dr, _sl) ((((_arm)&1)<<15) | (((_ar)&0x7f)<<8) | (((_dr)&0xf)<<4) | ((_sl)&0xf))
#define SD_SET_ADSR2(_srm, _sr, _rrm, _rr) ((((_srm)&7)<<13) | (((_sr)&0x7f)<<6) | (((_rrm)&1)<<5) | ((_rr)&0x1f))
#define SD_VPARAM_VOLL (0x00<<8)
#define SD_VPARAM_VOLR (0x01<<8)
#define SD_VPARAM_PITCH (0x02<<8)
#define SD_VPARAM_ADSR1 (0x03<<8)
#define SD_VPARAM_ADSR2 (0x04<<8)
#define SD_VPARAM_ENVX (0x05<<8)
#define SD_VPARAM_VOLXL (0x06<<8)
#define SD_VPARAM_VOLXR (0x07<<8)
#define SD_PARAM_MMIX (0x08<<8)
#define SD_PARAM_MVOLL ((0x09<<8)|0x80)
#define SD_PARAM_MVOLR ((0x0A<<8)|0x80)
#define SD_PARAM_EVOLL ((0x0B<<8)|0x80)
#define SD_PARAM_EVOLR ((0x0C<<8)|0x80)
#define SD_PARAM_AVOLL ((0x0D<<8)|0x80)
#define SD_PARAM_AVOLR ((0x0E<<8)|0x80)
#define SD_PARAM_BVOLL ((0x0F<<8)|0x80)
#define SD_PARAM_BVOLR ((0x10<<8)|0x80)
#define SD_PARAM_MVOLXL ((0x11<<8)|0x80)
#define SD_PARAM_MVOLXR ((0x12<<8)|0x80)
#define SD_TRANS_WRITE 0
#define SD_TRANS_READ 1
#define SD_TRANS_STOP 2
#define SD_TRANS_WRITE_FROM 3 /* only for block */
#define SD_TRANS_LOOP 0x10 /* only for block*/
#define SD_TRANS_MODE_DMA 0
#define SD_TRANS_MODE_IO 8
#define SD_EFFECT_MODE_OFF 0x0
#define SD_EFFECT_MODE_ROOM 0x1
#define SD_EFFECT_MODE_STUDIO_1 0x2
#define SD_EFFECT_MODE_STUDIO_2 0x3
#define SD_EFFECT_MODE_STUDIO_3 0x4
#define SD_EFFECT_MODE_HALL 0x5
#define SD_EFFECT_MODE_SPACE 0x6
#define SD_EFFECT_MODE_ECHO 0x7
#define SD_EFFECT_MODE_DELAY 0x8
#define SD_EFFECT_MODE_PIPE 0x9
#define SD_EFFECT_MODE_CLEAR 0x100
#define SD_CORE_EFFECT_ENABLE 0x2
#define SD_CORE_IRQ_ENABLE 0x4
#define SD_CORE_MUTE_ENABLE 0x6
#define SD_CORE_NOISE_CLK 0x8
#define SD_CORE_SPDIF_MODE 0xA
#define SD_SWITCH_PMON (0x13<<8)
#define SD_SWITCH_NON (0x14<<8)
#define SD_SWITCH_KON (0x15<<8)
#define SD_SWITCH_KEYDOWN SD_SWITCH_KON
#define SD_SWITCH_KOFF (0x16<<8)
#define SD_SWITCH_KEYUP SD_SWITCH_KOFF
#define SD_SWITCH_ENDX (0x17<<8)
#define SD_SWITCH_VMIXL (0x18<<8)
#define SD_SWITCH_VMIXEL (0x19<<8)
#define SD_SWITCH_VMIXR (0x1A<<8)
#define SD_SWITCH_VMIXER (0x1B<<8)
#define SD_ADDR_ESA (0x1C<<8)
#define SD_ADDR_EEA (0x1D<<8)
#define SD_ADDR_TSA (0x1E<<8)
#define SD_ADDR_IRQA (0x1F<<8)
#define SD_VADDR_SSA (0x20<<8)
#define SD_VADDR_LSAX (0x21<<8)
#define SD_VADDR_NAX (0x22<<8)
#define SD_SPU2_ON (1 << 15)
#define SD_MUTE (1 << 14)
#define SD_NOISE_CLOCK(c) ((c & 0x1F) << 8)
#define SD_ENABLE_EFFECTS (1 << 7)
#define SD_ENABLE_IRQ (1 << 6)
#define SD_DMA_IO (1 << 4)
#define SD_DMA_WRITE (2 << 4)
#define SD_DMA_READ (3 << 4)
#define SD_DMA_IN_PROCESS (3 << 4)
#define SD_CORE_DMA (3 << 4)
#define SD_ENABLE_EX_INPUT (1 << 0)
#define SD_IO_IN_PROCESS (1 << 10)
#define SD_BATCH_SETPARAM 0x1
#define SD_BATCH_SETSWITCH 0x2
#define SD_BATCH_SETADDR 0x3
#define SD_BATCH_SETCORE 0x4
#define SD_BATCH_WRITEIOP 0x5
#define SD_BATCH_WRITEEE 0x6
#define SD_BATCH_EERETURN 0x7
#define SD_BATCH_GETPARAM 0x10
#define SD_BATCH_GETSWITCH 0x12
#define SD_BATCH_GETADDR 0x13
#define SD_BATCH_GETCORE 0x14
#define ADPCM_LOOP_START 4 /* Set on first block of looped data */
#define ADPCM_LOOP 2 /* Set on all blocks (?that are inside the loop?) */
#define ADPCM_LOOP_END 1 /* Set on last block to loop */
#define BATCH_SETPARAM SD_BATCH_SETPARAM
#define BATCH_SETSWITCH SD_BATCH_SETSWITCH
#define BATCH_SETADDR SD_BATCH_SETADDR
#define BATCH_SETCORE SD_BATCH_SETCORE
#define BATCH_WRITEIOP SD_BATCH_WRITEIOP
#define BATCH_WRITEEE SD_BATCH_WRITEEE
#define BATCH_EERETURN SD_BATCH_EERETURN
#define BATCH_GETPARAM SD_BATCH_GETPARAM
#define BATCH_GETSWITCH SD_BATCH_GETSWITCH
#define BATCH_GETADDR SD_BATCH_GETADDR
#define BATCH_GETCORE SD_BATCH_GETCORE
#define SD_BLOCK_TRANS_WRITE SD_TRANS_WRITE
#define SD_BLOCK_TRANS_READ SD_TRANS_READ
#define SD_BLOCK_TRANS_STOP SD_TRANS_STOP
#define SD_BLOCK_TRANS_WRITE_FROM SD_TRANS_WRITE_FROM
#define SD_BLOCK_TRANS_LOOP SD_TRANS_LOOP
#define SD_VOICE_TRANS_WRITE SD_TRANS_WRITE
#define SD_VOICE_TRANS_READ SD_TRANS_READ
#define SD_VOICE_TRANS_STOP SD_TRANS_STOP
#define SD_VOICE_TRANS_MODE_DMA SD_TRANS_MODE_DMA
#define SD_VOICE_TRANS_MODE_IO SD_TRANS_MODE_IO
#define SdBatch sceSdBatch
#define SdEffectAttr sceSdEffectAttr
#define SdSpu2IntrHandler sceSdSpu2IntrHandler
#define SdTransIntrHandler sceSdTransIntrHandler
#define IntrCallback SdIntrCallback
#define SdQuit sceSdQuit
#define SdInit sceSdInit
#define SdSetIRQCallback sceSdSetIRQCallback
#define SdSetTransCallback sceSdSetTransCallback
#define SdSetParam sceSdSetParam
#define SdGetParam sceSdGetParam
#define SdSetCoreAttr sceSdSetCoreAttr
#define SdGetCoreAttr sceSdGetCoreAttr
#define SdClearEffectWorkArea sceSdClearEffectWorkArea
#define SdSetAddr sceSdSetAddr
#define SdGetAddr sceSdGetAddr
#define SdSetSwitch sceSdSetSwitch
#define SdGetSwitch sceSdGetSwitch
#define SdNote2Pitch sceSdNote2Pitch
#define SdPitch2Note sceSdPitch2Note
#define SdSetEffectAttr sceSdSetEffectAttr
#define SdGetEffectAttr sceSdGetEffectAttr
#define SdProcBatch sceSdProcBatch
#define SdProcBatchEx sceSdProcBatchEx
#define SdVoiceTrans sceSdVoiceTrans
#define SdBlockTrans sceSdBlockTrans
#define SdVoiceTransStatus sceSdVoiceTransStatus
#define SdBlockTransStatus sceSdBlockTransStatus
#define SdSetTransIntrHandler sceSdSetTransIntrHandler
#define SdSetSpu2IntrHandler sceSdSetSpu2IntrHandler
#define SdGetTransIntrHandlerArgument sceSdGetTransIntrHandlerArgument
#define SdGetSpu2IntrHandlerArgument sceSdGetSpu2IntrHandlerArgument
#define SdStopTrans sceSdStopTrans
#define SdCleanEffectWorkArea sceSdCleanEffectWorkArea
#define SdSetEffectMode sceSdSetEffectMode
#define SdSetEffectModeParams sceSdSetEffectModeParams
Typedefs
typedef int(* sceSdSpu2IntrHandler) (int, void *)
typedef int(* sceSdTransIntrHandler) (int, void *)
typedef int(* SdIntrCallback) (void *data)
Functions
int sceSdQuit ()
int sceSdInit (int flag)
SdIntrCallback sceSdSetIRQCallback (SdIntrCallback cb)
SdIntrCallback sceSdSetTransCallback (s32 core, SdIntrCallback cb)
void sceSdSetParam (u16 entry, u16 value)
u16 sceSdGetParam (u16 entry)
void sceSdSetCoreAttr (u16 entry, u16 value)
u16 sceSdGetCoreAttr (u16 entry)
int sceSdClearEffectWorkArea (int core, int channel, int effect_mode)
void sceSdSetAddr (u16 entry, u32 value)
u32 sceSdGetAddr (u16 entry)
void sceSdSetSwitch (u16 entry, u32 value)
u32 sceSdGetSwitch (u16 entry)
u16 sceSdNote2Pitch (u16 center_note, u16 center_fine, u16 note, s16 fine)
u16 sceSdPitch2Note (u16 center_note, u16 center_fine, u16 pitch)
int sceSdSetEffectAttr (int core, sceSdEffectAttr *attr)
void sceSdGetEffectAttr (int core, sceSdEffectAttr *attr)
int sceSdProcBatch (sceSdBatch *batch, u32 *rets, u32 num)
int sceSdProcBatchEx (sceSdBatch *batch, u32 *rets, u32 num, u32 voice)
int sceSdVoiceTrans (s16 chan, u16 mode, u8 *iopaddr, u32 *spuaddr, u32 size)
int sceSdBlockTrans (s16 chan, u16 mode, u8 *iopaddr, u32 size,...)
u32 sceSdVoiceTransStatus (s16 channel, s16 flag)
u32 sceSdBlockTransStatus (s16 channel, s16 flag)
sceSdTransIntrHandler sceSdSetTransIntrHandler (int channel, sceSdTransIntrHandler func, void *arg)
sceSdSpu2IntrHandler sceSdSetSpu2IntrHandler (sceSdSpu2IntrHandler func, void *arg)
void * sceSdGetTransIntrHandlerArgument (int arg)
void * sceSdGetSpu2IntrHandlerArgument ()
int sceSdStopTrans (int channel)
int sceSdCleanEffectWorkArea (int core, int channel, int effect_mode)
int sceSdSetEffectMode (int core, sceSdEffectAttr *param)
int sceSdSetEffectModeParams (int core, sceSdEffectAttr *attr)
Detailed Description
Common definitions for libsd on the EE and IOP
Definition in file libsd-common.h.
Macro Definition Documentation
ADPCM_LOOP
#define ADPCM_LOOP 2 /* Set on all blocks (?that are inside the loop?) */
Definition at line 127 of file libsd-common.h.
ADPCM_LOOP_END
#define ADPCM_LOOP_END 1 /* Set on last block to loop */
Definition at line 128 of file libsd-common.h.
ADPCM_LOOP_START
#define ADPCM_LOOP_START 4 /* Set on first block of looped data */
Definition at line 126 of file libsd-common.h.
BATCH_EERETURN
#define BATCH_EERETURN SD_BATCH_EERETURN
Definition at line 208 of file libsd-common.h.
BATCH_GETADDR
#define BATCH_GETADDR SD_BATCH_GETADDR
Definition at line 211 of file libsd-common.h.
BATCH_GETCORE
#define BATCH_GETCORE SD_BATCH_GETCORE
Definition at line 212 of file libsd-common.h.
BATCH_GETPARAM
#define BATCH_GETPARAM SD_BATCH_GETPARAM
Definition at line 209 of file libsd-common.h.
BATCH_GETSWITCH
#define BATCH_GETSWITCH SD_BATCH_GETSWITCH
Definition at line 210 of file libsd-common.h.
BATCH_SETADDR
#define BATCH_SETADDR SD_BATCH_SETADDR
Definition at line 204 of file libsd-common.h.
BATCH_SETCORE
#define BATCH_SETCORE SD_BATCH_SETCORE
Definition at line 205 of file libsd-common.h.
BATCH_SETPARAM
#define BATCH_SETPARAM SD_BATCH_SETPARAM
Definition at line 202 of file libsd-common.h.
BATCH_SETSWITCH
#define BATCH_SETSWITCH SD_BATCH_SETSWITCH
Definition at line 203 of file libsd-common.h.
BATCH_WRITEEE
#define BATCH_WRITEEE SD_BATCH_WRITEEE
Definition at line 207 of file libsd-common.h.
BATCH_WRITEIOP
#define BATCH_WRITEIOP SD_BATCH_WRITEIOP
Definition at line 206 of file libsd-common.h.
IntrCallback
#define IntrCallback SdIntrCallback
Definition at line 230 of file libsd-common.h.
SD_ADDR_EEA
#define SD_ADDR_EEA (0x1D<<8)
Definition at line 90 of file libsd-common.h.
SD_ADDR_ESA
#define SD_ADDR_ESA (0x1C<<8)
Definition at line 89 of file libsd-common.h.
SD_ADDR_IRQA
#define SD_ADDR_IRQA (0x1F<<8)
Definition at line 92 of file libsd-common.h.
SD_ADDR_TSA
#define SD_ADDR_TSA (0x1E<<8)
Definition at line 91 of file libsd-common.h.
SD_ADSR_AR_EXPi
#define SD_ADSR_AR_EXPi 1
Definition at line 15 of file libsd-common.h.
SD_ADSR_AR_LINEARi
#define SD_ADSR_AR_LINEARi 0
Definition at line 14 of file libsd-common.h.
SD_ADSR_RR_EXPd
#define SD_ADSR_RR_EXPd 1
Definition at line 21 of file libsd-common.h.
SD_ADSR_RR_LINEARd
#define SD_ADSR_RR_LINEARd 0
Definition at line 20 of file libsd-common.h.
SD_ADSR_SR_EXPd
#define SD_ADSR_SR_EXPd 6
Definition at line 19 of file libsd-common.h.
SD_ADSR_SR_EXPi
#define SD_ADSR_SR_EXPi 4
Definition at line 18 of file libsd-common.h.
SD_ADSR_SR_LINEARd
#define SD_ADSR_SR_LINEARd 2
Definition at line 17 of file libsd-common.h.
SD_ADSR_SR_LINEARi
#define SD_ADSR_SR_LINEARi 0
Definition at line 16 of file libsd-common.h.
SD_BATCH_EERETURN
#define SD_BATCH_EERETURN 0x7
Definition at line 120 of file libsd-common.h.
SD_BATCH_GETADDR
#define SD_BATCH_GETADDR 0x13
Definition at line 123 of file libsd-common.h.
SD_BATCH_GETCORE
#define SD_BATCH_GETCORE 0x14
Definition at line 124 of file libsd-common.h.
SD_BATCH_GETPARAM
#define SD_BATCH_GETPARAM 0x10
Definition at line 121 of file libsd-common.h.
SD_BATCH_GETSWITCH
#define SD_BATCH_GETSWITCH 0x12
Definition at line 122 of file libsd-common.h.
SD_BATCH_SETADDR
#define SD_BATCH_SETADDR 0x3
Definition at line 116 of file libsd-common.h.
SD_BATCH_SETCORE
#define SD_BATCH_SETCORE 0x4
Definition at line 117 of file libsd-common.h.
SD_BATCH_SETPARAM
#define SD_BATCH_SETPARAM 0x1
Definition at line 114 of file libsd-common.h.
SD_BATCH_SETSWITCH
#define SD_BATCH_SETSWITCH 0x2
Definition at line 115 of file libsd-common.h.
SD_BATCH_WRITEEE
#define SD_BATCH_WRITEEE 0x6
Definition at line 119 of file libsd-common.h.
SD_BATCH_WRITEIOP
#define SD_BATCH_WRITEIOP 0x5
Definition at line 118 of file libsd-common.h.
SD_BLOCK_TRANS_LOOP
#define SD_BLOCK_TRANS_LOOP SD_TRANS_LOOP
Definition at line 218 of file libsd-common.h.
SD_BLOCK_TRANS_READ
#define SD_BLOCK_TRANS_READ SD_TRANS_READ
Definition at line 215 of file libsd-common.h.
SD_BLOCK_TRANS_STOP
#define SD_BLOCK_TRANS_STOP SD_TRANS_STOP
Definition at line 216 of file libsd-common.h.
SD_BLOCK_TRANS_WRITE
#define SD_BLOCK_TRANS_WRITE SD_TRANS_WRITE
Definition at line 214 of file libsd-common.h.
SD_BLOCK_TRANS_WRITE_FROM
#define SD_BLOCK_TRANS_WRITE_FROM SD_TRANS_WRITE_FROM
Definition at line 217 of file libsd-common.h.
SD_CORE_DMA
#define SD_CORE_DMA (3 << 4)
Definition at line 107 of file libsd-common.h.
SD_CORE_EFFECT_ENABLE
#define SD_CORE_EFFECT_ENABLE 0x2
Definition at line 69 of file libsd-common.h.
SD_CORE_IRQ_ENABLE
#define SD_CORE_IRQ_ENABLE 0x4
Definition at line 70 of file libsd-common.h.
SD_CORE_MUTE_ENABLE
#define SD_CORE_MUTE_ENABLE 0x6
Definition at line 71 of file libsd-common.h.
SD_CORE_NOISE_CLK
#define SD_CORE_NOISE_CLK 0x8
Definition at line 72 of file libsd-common.h.
SD_CORE_SPDIF_MODE
#define SD_CORE_SPDIF_MODE 0xA
Definition at line 73 of file libsd-common.h.
SD_DMA_IN_PROCESS
#define SD_DMA_IN_PROCESS (3 << 4)
Definition at line 106 of file libsd-common.h.
SD_DMA_IO
#define SD_DMA_IO (1 << 4)
Definition at line 103 of file libsd-common.h.
SD_DMA_READ
#define SD_DMA_READ (3 << 4)
Definition at line 105 of file libsd-common.h.
SD_DMA_WRITE
#define SD_DMA_WRITE (2 << 4)
Definition at line 104 of file libsd-common.h.
SD_EFFECT_MODE_CLEAR
#define SD_EFFECT_MODE_CLEAR 0x100
Definition at line 66 of file libsd-common.h.
SD_EFFECT_MODE_DELAY
#define SD_EFFECT_MODE_DELAY 0x8
Definition at line 64 of file libsd-common.h.
SD_EFFECT_MODE_ECHO
#define SD_EFFECT_MODE_ECHO 0x7
Definition at line 63 of file libsd-common.h.
SD_EFFECT_MODE_HALL
#define SD_EFFECT_MODE_HALL 0x5
Definition at line 61 of file libsd-common.h.
SD_EFFECT_MODE_OFF
#define SD_EFFECT_MODE_OFF 0x0
Definition at line 56 of file libsd-common.h.
SD_EFFECT_MODE_PIPE
#define SD_EFFECT_MODE_PIPE 0x9
Definition at line 65 of file libsd-common.h.
SD_EFFECT_MODE_ROOM
#define SD_EFFECT_MODE_ROOM 0x1
Definition at line 57 of file libsd-common.h.
SD_EFFECT_MODE_SPACE
#define SD_EFFECT_MODE_SPACE 0x6
Definition at line 62 of file libsd-common.h.
SD_EFFECT_MODE_STUDIO_1
#define SD_EFFECT_MODE_STUDIO_1 0x2
Definition at line 58 of file libsd-common.h.
SD_EFFECT_MODE_STUDIO_2
#define SD_EFFECT_MODE_STUDIO_2 0x3
Definition at line 59 of file libsd-common.h.
SD_EFFECT_MODE_STUDIO_3
#define SD_EFFECT_MODE_STUDIO_3 0x4
Definition at line 60 of file libsd-common.h.
SD_ENABLE_EFFECTS
#define SD_ENABLE_EFFECTS (1 << 7)
Definition at line 101 of file libsd-common.h.
SD_ENABLE_EX_INPUT
#define SD_ENABLE_EX_INPUT (1 << 0)
Definition at line 108 of file libsd-common.h.
SD_ENABLE_IRQ
#define SD_ENABLE_IRQ (1 << 6)
Definition at line 102 of file libsd-common.h.
SD_IO_IN_PROCESS
#define SD_IO_IN_PROCESS (1 << 10)
Definition at line 111 of file libsd-common.h.
SD_MUTE
#define SD_MUTE (1 << 14)
Definition at line 99 of file libsd-common.h.
SD_NOISE_CLOCK
#define SD_NOISE_CLOCK (c) ((c & 0x1F) << 8)
Definition at line 100 of file libsd-common.h.
SD_PARAM_AVOLL
#define SD_PARAM_AVOLL ((0x0D<<8)|0x80)
Definition at line 39 of file libsd-common.h.
SD_PARAM_AVOLR
#define SD_PARAM_AVOLR ((0x0E<<8)|0x80)
Definition at line 40 of file libsd-common.h.
SD_PARAM_BVOLL
#define SD_PARAM_BVOLL ((0x0F<<8)|0x80)
Definition at line 41 of file libsd-common.h.
SD_PARAM_BVOLR
#define SD_PARAM_BVOLR ((0x10<<8)|0x80)
Definition at line 42 of file libsd-common.h.
SD_PARAM_EVOLL
#define SD_PARAM_EVOLL ((0x0B<<8)|0x80)
Definition at line 37 of file libsd-common.h.
SD_PARAM_EVOLR
#define SD_PARAM_EVOLR ((0x0C<<8)|0x80)
Definition at line 38 of file libsd-common.h.
SD_PARAM_MMIX
#define SD_PARAM_MMIX (0x08<<8)
Definition at line 34 of file libsd-common.h.
SD_PARAM_MVOLL
#define SD_PARAM_MVOLL ((0x09<<8)|0x80)
Definition at line 35 of file libsd-common.h.
SD_PARAM_MVOLR
#define SD_PARAM_MVOLR ((0x0A<<8)|0x80)
Definition at line 36 of file libsd-common.h.
SD_PARAM_MVOLXL
#define SD_PARAM_MVOLXL ((0x11<<8)|0x80)
Definition at line 43 of file libsd-common.h.
SD_PARAM_MVOLXR
#define SD_PARAM_MVOLXR ((0x12<<8)|0x80)
Definition at line 44 of file libsd-common.h.
SD_SET_ADSR1
#define SD_SET_ADSR1 (_arm, _ar, _dr, _sl) ((((_arm)&1)<<15) | (((_ar)&0x7f)<<8) | (((_dr)&0xf)<<4) | ((_sl)&0xf))
Definition at line 22 of file libsd-common.h.
SD_SET_ADSR2
#define SD_SET_ADSR2 (_srm, _sr, _rrm, _rr) ((((_srm)&7)<<13) | (((_sr)&0x7f)<<6) | (((_rrm)&1)<<5) | ((_rr)&0x1f))
Definition at line 23 of file libsd-common.h.
SD_SPU2_ON
#define SD_SPU2_ON (1 << 15)
Definition at line 98 of file libsd-common.h.
SD_SWITCH_ENDX
#define SD_SWITCH_ENDX (0x17<<8)
Definition at line 82 of file libsd-common.h.
SD_SWITCH_KEYDOWN
#define SD_SWITCH_KEYDOWN SD_SWITCH_KON
Definition at line 79 of file libsd-common.h.
SD_SWITCH_KEYUP
#define SD_SWITCH_KEYUP SD_SWITCH_KOFF
Definition at line 81 of file libsd-common.h.
SD_SWITCH_KOFF
#define SD_SWITCH_KOFF (0x16<<8)
Definition at line 80 of file libsd-common.h.
SD_SWITCH_KON
#define SD_SWITCH_KON (0x15<<8)
Definition at line 78 of file libsd-common.h.
SD_SWITCH_NON
#define SD_SWITCH_NON (0x14<<8)
Definition at line 77 of file libsd-common.h.
SD_SWITCH_PMON
#define SD_SWITCH_PMON (0x13<<8)
Definition at line 76 of file libsd-common.h.
SD_SWITCH_VMIXEL
#define SD_SWITCH_VMIXEL (0x19<<8)
Definition at line 84 of file libsd-common.h.
SD_SWITCH_VMIXER
#define SD_SWITCH_VMIXER (0x1B<<8)
Definition at line 86 of file libsd-common.h.
SD_SWITCH_VMIXL
#define SD_SWITCH_VMIXL (0x18<<8)
Definition at line 83 of file libsd-common.h.
SD_SWITCH_VMIXR
#define SD_SWITCH_VMIXR (0x1A<<8)
Definition at line 85 of file libsd-common.h.
SD_TRANS_LOOP
#define SD_TRANS_LOOP 0x10 /* only for block*/
Definition at line 51 of file libsd-common.h.
SD_TRANS_MODE_DMA
#define SD_TRANS_MODE_DMA 0
Definition at line 52 of file libsd-common.h.
SD_TRANS_MODE_IO
#define SD_TRANS_MODE_IO 8
Definition at line 53 of file libsd-common.h.
SD_TRANS_READ
#define SD_TRANS_READ 1
Definition at line 48 of file libsd-common.h.
SD_TRANS_STOP
#define SD_TRANS_STOP 2
Definition at line 49 of file libsd-common.h.
SD_TRANS_WRITE
#define SD_TRANS_WRITE 0
Definition at line 47 of file libsd-common.h.
SD_TRANS_WRITE_FROM
#define SD_TRANS_WRITE_FROM 3 /* only for block */
Definition at line 50 of file libsd-common.h.
SD_VADDR_LSAX
#define SD_VADDR_LSAX (0x21<<8)
Definition at line 94 of file libsd-common.h.
SD_VADDR_NAX
#define SD_VADDR_NAX (0x22<<8)
Definition at line 95 of file libsd-common.h.
SD_VADDR_SSA
#define SD_VADDR_SSA (0x20<<8)
Definition at line 93 of file libsd-common.h.
SD_VOICE
#define SD_VOICE (_core, _v) ((_core)|((_v)<<1))
Definition at line 11 of file libsd-common.h.
SD_VOICE_TRANS_MODE_DMA
#define SD_VOICE_TRANS_MODE_DMA SD_TRANS_MODE_DMA
Definition at line 223 of file libsd-common.h.
SD_VOICE_TRANS_MODE_IO
#define SD_VOICE_TRANS_MODE_IO SD_TRANS_MODE_IO
Definition at line 224 of file libsd-common.h.
SD_VOICE_TRANS_READ
#define SD_VOICE_TRANS_READ SD_TRANS_READ
Definition at line 221 of file libsd-common.h.
SD_VOICE_TRANS_STOP
#define SD_VOICE_TRANS_STOP SD_TRANS_STOP
Definition at line 222 of file libsd-common.h.
SD_VOICE_TRANS_WRITE
#define SD_VOICE_TRANS_WRITE SD_TRANS_WRITE
Definition at line 220 of file libsd-common.h.
SD_VPARAM_ADSR1
#define SD_VPARAM_ADSR1 (0x03<<8)
Definition at line 29 of file libsd-common.h.
SD_VPARAM_ADSR2
#define SD_VPARAM_ADSR2 (0x04<<8)
Definition at line 30 of file libsd-common.h.
SD_VPARAM_ENVX
#define SD_VPARAM_ENVX (0x05<<8)
Definition at line 31 of file libsd-common.h.
SD_VPARAM_PITCH
#define SD_VPARAM_PITCH (0x02<<8)
Definition at line 28 of file libsd-common.h.
SD_VPARAM_VOLL
#define SD_VPARAM_VOLL (0x00<<8)
Definition at line 26 of file libsd-common.h.
SD_VPARAM_VOLR
#define SD_VPARAM_VOLR (0x01<<8)
Definition at line 27 of file libsd-common.h.
SD_VPARAM_VOLXL
#define SD_VPARAM_VOLXL (0x06<<8)
Definition at line 32 of file libsd-common.h.
SD_VPARAM_VOLXR
#define SD_VPARAM_VOLXR (0x07<<8)
Definition at line 33 of file libsd-common.h.
SdBatch
#define SdBatch sceSdBatch
Definition at line 226 of file libsd-common.h.
SdBlockTrans
#define SdBlockTrans sceSdBlockTrans
Definition at line 252 of file libsd-common.h.
SdBlockTransStatus
#define SdBlockTransStatus sceSdBlockTransStatus
Definition at line 254 of file libsd-common.h.
SdCleanEffectWorkArea
#define SdCleanEffectWorkArea sceSdCleanEffectWorkArea
Definition at line 260 of file libsd-common.h.
SdClearEffectWorkArea
#define SdClearEffectWorkArea sceSdClearEffectWorkArea
Definition at line 240 of file libsd-common.h.
SdEffectAttr
#define SdEffectAttr sceSdEffectAttr
Definition at line 227 of file libsd-common.h.
SdGetAddr
#define SdGetAddr sceSdGetAddr
Definition at line 242 of file libsd-common.h.
SdGetCoreAttr
#define SdGetCoreAttr sceSdGetCoreAttr
Definition at line 239 of file libsd-common.h.
SdGetEffectAttr
#define SdGetEffectAttr sceSdGetEffectAttr
Definition at line 248 of file libsd-common.h.
SdGetParam
#define SdGetParam sceSdGetParam
Definition at line 237 of file libsd-common.h.
SdGetSpu2IntrHandlerArgument
#define SdGetSpu2IntrHandlerArgument sceSdGetSpu2IntrHandlerArgument
Definition at line 258 of file libsd-common.h.
SdGetSwitch
#define SdGetSwitch sceSdGetSwitch
Definition at line 244 of file libsd-common.h.
SdGetTransIntrHandlerArgument
#define SdGetTransIntrHandlerArgument sceSdGetTransIntrHandlerArgument
Definition at line 257 of file libsd-common.h.
SdInit
#define SdInit sceSdInit
Definition at line 233 of file libsd-common.h.
SdNote2Pitch
#define SdNote2Pitch sceSdNote2Pitch
Definition at line 245 of file libsd-common.h.
SdPitch2Note
#define SdPitch2Note sceSdPitch2Note
Definition at line 246 of file libsd-common.h.
SdProcBatch
#define SdProcBatch sceSdProcBatch
Definition at line 249 of file libsd-common.h.
SdProcBatchEx
#define SdProcBatchEx sceSdProcBatchEx
Definition at line 250 of file libsd-common.h.
SdQuit
#define SdQuit sceSdQuit
Definition at line 232 of file libsd-common.h.
SdSetAddr
#define SdSetAddr sceSdSetAddr
Definition at line 241 of file libsd-common.h.
SdSetCoreAttr
#define SdSetCoreAttr sceSdSetCoreAttr
Definition at line 238 of file libsd-common.h.
SdSetEffectAttr
#define SdSetEffectAttr sceSdSetEffectAttr
Definition at line 247 of file libsd-common.h.
SdSetEffectMode
#define SdSetEffectMode sceSdSetEffectMode
Definition at line 261 of file libsd-common.h.
SdSetEffectModeParams
#define SdSetEffectModeParams sceSdSetEffectModeParams
Definition at line 262 of file libsd-common.h.
SdSetIRQCallback
#define SdSetIRQCallback sceSdSetIRQCallback
Definition at line 234 of file libsd-common.h.
SdSetParam
#define SdSetParam sceSdSetParam
Definition at line 236 of file libsd-common.h.
SdSetSpu2IntrHandler
#define SdSetSpu2IntrHandler sceSdSetSpu2IntrHandler
Definition at line 256 of file libsd-common.h.
SdSetSwitch
#define SdSetSwitch sceSdSetSwitch
Definition at line 243 of file libsd-common.h.
SdSetTransCallback
#define SdSetTransCallback sceSdSetTransCallback
Definition at line 235 of file libsd-common.h.
SdSetTransIntrHandler
#define SdSetTransIntrHandler sceSdSetTransIntrHandler
Definition at line 255 of file libsd-common.h.
SdSpu2IntrHandler
#define SdSpu2IntrHandler sceSdSpu2IntrHandler
Definition at line 228 of file libsd-common.h.
SdStopTrans
#define SdStopTrans sceSdStopTrans
Definition at line 259 of file libsd-common.h.
SdTransIntrHandler
#define SdTransIntrHandler sceSdTransIntrHandler
Definition at line 229 of file libsd-common.h.
SdVoiceTrans
#define SdVoiceTrans sceSdVoiceTrans
Definition at line 251 of file libsd-common.h.
SdVoiceTransStatus
#define SdVoiceTransStatus sceSdVoiceTransStatus
Definition at line 253 of file libsd-common.h.
Typedef Documentation
sceSdSpu2IntrHandler
typedef int(* sceSdSpu2IntrHandler) (int, void *)
Definition at line 147 of file libsd-common.h.
sceSdTransIntrHandler
typedef int(* sceSdTransIntrHandler) (int, void *)
Definition at line 148 of file libsd-common.h.
SdIntrCallback
typedef int(* SdIntrCallback) (void *data)
Definition at line 149 of file libsd-common.h.
Function Documentation
sceSdBlockTrans()
int sceSdBlockTrans (s16 chan, u16 mode, u8 * iopaddr, u32 size, ...)
Definition at line 745 of file spu2.c.
 {
         #ifndef ISJPCM
         int transfer_dir = mode & 3;
         #endif
         int core = chan & 1;
         int _size = size;
         va_list alist;
         u8* startaddr;
         #ifndef ISJPCM
         switch(transfer_dir)
         {
                 case SD_TRANS_WRITE:
                 {
                         TransIntrData[core].mode = 0x100 | core;
                         if(mode & SD_TRANS_LOOP)
{
                                 TransIntrData[core].mode |= SD_TRANS_LOOP << 8;
                                 _size /= 2;
                         }
                         if(BlockTransWrite(iopaddr, _size, core) >= 0)
                                 return 0;
                 } break;
                 case SD_TRANS_READ:
                 {
                         TransIntrData[core].mode = 0x300 | core;
                         if(mode & SD_TRANS_LOOP)
{
                                 TransIntrData[core].mode |= SD_TRANS_LOOP << 8;
                                 _size /= 2;
                         }
                         if(BlockTransRead(iopaddr, _size, chan, mode) >= 0)
                                 return 0;
                 } break;
                 case SD_TRANS_STOP:
                 {
                         return DmaStop(core);
                 } break;
                 case SD_TRANS_WRITE_FROM:
                 {
                         va_start(alist, size);
                         startaddr = va_arg(alist, u8*);
                         va_end(alist);
                         TransIntrData[core].mode = 0x100 | core;
                         if(mode & SD_TRANS_LOOP)
{
                                 TransIntrData[core].mode |= SD_TRANS_LOOP << 8;
                                 _size /= 2;
                         }
                         if(BlockTransWriteFrom(iopaddr, _size, core, mode, startaddr) >= 0)
                                 return 0;
                 } break;
         }
         #else
         TransIntrData[core].mode = 0x100 | core;
         TransIntrData[core].mode |= SD_TRANS_LOOP << 8;
         _size /= 2;
         if(BlockTransWrite(iopaddr, _size, core) >= 0)
                 return 0;
         #endif
         return -1;
 }
References BlockTransRead(), BlockTransWrite(), BlockTransWriteFrom(), DmaStop(), IntrData::mode, SD_TRANS_LOOP, SD_TRANS_READ, SD_TRANS_STOP, SD_TRANS_WRITE, SD_TRANS_WRITE_FROM, and TransIntrData.
Referenced by AHX_Init(), AHX_Quit(), audsrv_init(), audsrv_quit(), audsrv_stop_cd_stream(), cdda_procedure(), and rpc_server().
sceSdBlockTransStatus()
u32 sceSdBlockTransStatus (s16 channel, s16 flag)
Definition at line 829 of file spu2.c.
 {
         u32 retval;
         chan &= 1;
         if(*U16_REGISTER(0x1B0 + (chan * 1024)) == 0)
                 retval = 0;
         else
                 retval = *SD_DMA_ADDR(chan);
         retval = (BlockTransBuff[chan] << 24) | (retval & 0xFFFFFF);
         return retval;
 }
References BlockTransBuff, SD_DMA_ADDR, and U16_REGISTER.
Referenced by AHX_PlayThread(), cdda_procedure(), play_thread(), and rpc_server().
sceSdCleanEffectWorkArea()
int sceSdCleanEffectWorkArea (int core, int channel, int effect_mode)
sceSdClearEffectWorkArea()
int sceSdClearEffectWorkArea (int core, int channel, int effect_mode)
Definition at line 203 of file effect.c.
 {
         if(effect_type > 9) return -1;
         if(effect_type != SD_EFFECT_MODE_OFF)
         {
                 u32 aligned_addr = 0;
                 u32 effect_addr;
                 s32 effect_size;
                 s32 old_iomode;
                 sceSdTransIntrHandler old_handler = NULL;
                 SdIntrCallback old_callback = NULL;
                 effect_size = EffectSizes[effect_type] << 4;
                 effect_addr = (GetEEA(core) - (effect_size - 2));
                 if(effect_size & 127)
                 {
                         effect_size &= ~127;
                         aligned_addr = (GetEEA(core) - (effect_size - 2));
                 }
                 old_iomode = VoiceTransIoMode[chan];
                 if(VoiceTransIoMode[chan] == 1) VoiceTransIoMode[chan] = 0;
                 // Disable intr_handlers by removing them
                 if(TransIntrHandlers[chan])
                 {
                         old_handler = TransIntrHandlers[chan];
                         TransIntrHandlers[chan] = 0;
                 }
                 if(TransIntrCallbacks[chan])
                 {
                         old_callback = TransIntrCallbacks[chan];
                         TransIntrCallbacks[chan] = NULL;
                 }
                 if(aligned_addr)
                 {
                         sceSdVoiceTrans(chan, 0, (u8*)ClearEffectData, (u32*)effect_addr, 64);
                         sceSdVoiceTransStatus(chan, 1);
                         effect_addr = aligned_addr;
                 }
                 while(effect_size > 0)
                 {
                         u32 size;
                         if(effect_size < 1024)
                                 size = effect_size;
                         else
                                 size = 1024;
                         sceSdVoiceTrans(chan, 0, (u8*)ClearEffectData, (u32*)effect_addr, size);
                         sceSdVoiceTransStatus(chan, 1); // Wait for completion
                         effect_size -= 1024;
                         effect_addr += 1024;
                 }
                 VoiceTransIoMode[chan] = old_iomode;
                 // Enable intr_handlers by adding them again
                 if(old_handler) TransIntrHandlers[chan] = old_handler;
                 if(old_callback) TransIntrCallbacks[chan] = old_callback;
         }
         return 0;
 }
References ClearEffectData, EffectSizes, GetEEA(), NULL, sceSdVoiceTrans(), sceSdVoiceTransStatus(), SD_EFFECT_MODE_OFF, TransIntrCallbacks, TransIntrHandlers, and VoiceTransIoMode.
Referenced by rpc_server(), and sceSdSetEffectAttr().
sceSdGetAddr()
u32 sceSdGetAddr (u16 entry)
Definition at line 866 of file freesd.c.
 {
         volatile u16 *reg1;
         u16 voice;
         u32 retlo, rethi;
         reg1 = ParamRegList[(reg >> 8) & 0xFF] + ((reg & 1) << 9);
         voice = reg & 0x3E;
         reg1 += ((voice << 1) + voice);
         rethi = *reg1 << 17;
         retlo = 0x1FFFF;
         reg &= 0xFF00;
         if(reg != 0x1D00)
         {
                 retlo = *(reg1 + 1) << 1;
                 if((reg == 0x2100) || (reg == 0x2200))
                 {
                         u32 lo, hi;
                         hi = *reg1 << 17;
                         lo = *(reg1 + 1) << 1;
                         if((rethi == hi) || (retlo != lo))
{
                                 retlo = lo;
                                 rethi = hi;
                         }
                 }
         }
         return rethi | retlo;
 }
References ParamRegList.
Referenced by rpc_server(), sceSdProcBatch(), sceSdProcBatchEx(), and sndStreamGetPosition().
sceSdGetCoreAttr()
u16 sceSdGetCoreAttr (u16 entry)
Definition at line 800 of file freesd.c.
 {
         switch(entry & ~1)
         {
                 case SD_CORE_NOISE_CLK:
                         return (*SD_CORE_ATTR(entry & 1) >> 8) & 0x3F;
                 case SD_CORE_SPDIF_MODE:
                         return SpdifSettings;
                 default:
                 {
                         u32 core = entry & 1;
                         entry = (entry >> 1)-1;
                         return (*SD_CORE_ATTR(core) >> CoreAttrShifts[entry]) & 1;
                 }
         }
 }
References CoreAttrShifts, SD_CORE_ATTR, SD_CORE_NOISE_CLK, SD_CORE_SPDIF_MODE, and SpdifSettings.
Referenced by rpc_server(), sceSdProcBatch(), and sceSdProcBatchEx().
sceSdGetEffectAttr()
void sceSdGetEffectAttr (int core, sceSdEffectAttr * attr)
Definition at line 198 of file effect.c.
 {
         *attr = EffectAttr[core & 1];
 }
References EffectAttr.
Referenced by rpc_server().
sceSdGetParam()
u16 sceSdGetParam (u16 entry)
Definition at line 529 of file freesd.c.
 {
         u32 offs;
         u32 voice;
         u32 reg_index;
         u32 core;
         volatile u16 *reg_p;
         core = reg & 1;
         // Determine the channel offset
         if(reg & 0x80)
                 offs = (40 * core) >> 1;
         else
                 offs = (1024 * core) >> 1;
         reg_index = (reg >> 8) & 0xFF;
         voice = (reg & 0x3E) << 2;
         reg_p = ParamRegList[reg_index] + offs + voice;
         return *reg_p;
 }
References ParamRegList.
Referenced by rpc_server(), sceSdProcBatch(), and sceSdProcBatchEx().
sceSdGetSpu2IntrHandlerArgument()
void* sceSdGetSpu2IntrHandlerArgument ()
sceSdGetSwitch()
u32 sceSdGetSwitch (u16 entry)
Definition at line 564 of file freesd.c.
 {
         u32 reg_index;
         volatile u16 *reg_p;
         u32 ret;
         reg_index = (reg >> 8) & 0xFF;
         reg_p = ParamRegList[reg_index] + ((reg & 1) << 9);
         ret =  reg_p[0];
         ret |= reg_p[1] << 16;
         return ret;
 }
References ParamRegList.
Referenced by audsrv_adpcm_alloc_channel(), audsrv_ch_play_adpcm(), rpc_server(), sceSdProcBatch(), and sceSdProcBatchEx().
sceSdGetTransIntrHandlerArgument()
void* sceSdGetTransIntrHandlerArgument (int arg)
sceSdInit()
int sceSdInit (int flag)
Definition at line 417 of file spu2.c.
 {
         flag &= 1;
         InitSpu2();
         InitSpdif();
         if(flag == 0) ResetAll();
         RegisterInterrupts();
         InitVoices();
         InitCoreVolume(flag);
         EnableIntr(0x24);
         EnableIntr(0x28);
         #ifndef ISJPCM
         EnableIntr(9);
         #endif
         return 0;
 }
References EnableIntr(), InitCoreVolume(), InitSpdif(), InitSpu2(), InitVoices(), IOP_IRQ_DMA_SPU, IOP_IRQ_DMA_SPU2, IOP_IRQ_SPU, RegisterInterrupts(), Reset(), and ResetAll().
Referenced by AHX_Init(), audsrv_init(), and rpc_server().
sceSdNote2Pitch()
u16 sceSdNote2Pitch (u16 center_note, u16 center_fine, u16 note, s16 fine)
sceSdPitch2Note()
u16 sceSdPitch2Note (u16 center_note, u16 center_fine, u16 pitch)
Definition at line 661 of file freesd.c.
 {
         s32 _pitch;
         s32 i = 0;
         s32 bit = 0;
         s32 offset1 = 0;
         s32 offset2 = 0;
         s32 val;
         s32 ret;
         if(((u16)pitch) >= 0x4000) pitch = 0x3FFF;
         _pitch = (u16)pitch;
         do
         {
                 if((_pitch & 1) == 1) bit = i;
                 _pitch >>= 1;
                 i++;
         } while(i < 14);
         val = (u16)pitch << (15 - bit);
         i = 11;
         do
         {
                 if((u16)val >= NotePitchTable[i])
                 {
                         offset1 = i;
                         break;
                 }
                 i--;
         } while(i >= 0);
         val = ((u16)val * 0x8000) / NotePitchTable[(u16)offset1];
         i = 127;
         do
         {
                 if((u16)val >= NotePitchTable[12 + i])
                 {
                         offset2 = i;
                         break;
                 }
                 i--;
         } while(i >= 0);
         val = (u16)(center_fine + offset2 +1);
         ret = (center_note + offset1 + ((bit - 12) * 12) + (val/128)) * 256;
         ret = (ret + (val & 0x7E)) & 0xFFFE;
         return (u16)ret;
 }
References NotePitchTable.
Referenced by rpc_server().
sceSdProcBatch()
int sceSdProcBatch (sceSdBatch * batch, u32 * rets, u32 num)
Definition at line 43 of file batch.c.
 {
         s32 loop;
         s32 ret;
         for(loop = 0; loop < num; loop++)
         {
                 ret = 0;
                 switch(batch[loop].func)
                 {
                 case SD_BATCH_SETPARAM:
                         sceSdSetParam(batch[loop].entry, batch[loop].value);
                         break;
                 case SD_BATCH_GETPARAM:
                         ret = sceSdGetParam(batch[loop].entry);
                         break;
                 case SD_BATCH_SETSWITCH:
                         sceSdSetSwitch(batch[loop].entry, batch[loop].value);
                         break;
                 case SD_BATCH_GETSWITCH:
                         ret = sceSdGetSwitch(batch[loop].entry);
                         break;
                 case SD_BATCH_SETADDR:
                         sceSdSetAddr(batch[loop].entry, batch[loop].value);
                         break;
                 case SD_BATCH_GETADDR:
                         ret = sceSdGetAddr(batch[loop].entry);
                         break;
                 case SD_BATCH_SETCORE:
                         sceSdSetCoreAttr(batch[loop].entry, batch[loop].value);
                         break;
                 case SD_BATCH_GETCORE:
                         ret = sceSdGetCoreAttr(batch[loop].entry);
                         break;
                 case SD_BATCH_WRITEIOP:
                         *((u32 *) batch[loop].value) = batch[loop].entry;
                         break;
                 case SD_BATCH_WRITEEE:
                         BatchData = batch[loop].entry;
                         SifDmaBatch(batch[loop].value, &BatchData, 4);
                         break;
                 case SD_BATCH_EERETURN:
                         SifDmaBatch(batch[loop].value, rets, batch[loop].entry);
                         break;
                 default:
                         return -1 - loop;
                 }
                 if(rets) rets[loop] = ret;
         }
         return loop;
 }
References BatchData, sceSdBatch::entry, sceSdGetAddr(), sceSdGetCoreAttr(), sceSdGetParam(), sceSdGetSwitch(), sceSdSetAddr(), sceSdSetCoreAttr(), sceSdSetParam(), sceSdSetSwitch(), SD_BATCH_EERETURN, SD_BATCH_GETADDR, SD_BATCH_GETCORE, SD_BATCH_GETPARAM, SD_BATCH_GETSWITCH, SD_BATCH_SETADDR, SD_BATCH_SETCORE, SD_BATCH_SETPARAM, SD_BATCH_SETSWITCH, SD_BATCH_WRITEEE, SD_BATCH_WRITEIOP, and SifDmaBatch().
Referenced by rpc_server().
sceSdProcBatchEx()
int sceSdProcBatchEx (sceSdBatch * batch, u32 * rets, u32 num, u32 voice)
Definition at line 98 of file batch.c.
 {
         s32 loop;
         s32 ret;
         s32 voice_loop;
         s32 cmd_count;
         cmd_count = 0;
         for(loop = 0; loop < num; loop++)
         {
                 ret = 0;
                 switch(batch[loop].func)
                 {
                         case SD_BATCH_SETPARAM:
{
                                 if((batch[loop].entry & 0x3E) != 0x3E)
{
                                         sceSdSetParam(batch[loop].entry, batch[loop].value);
                                 }
                                 else
{
                                         for(voice_loop = 0; voice_loop < 24; voice_loop++)
{
                                                 if(voice & (1 << voice_loop))
{
                                                         sceSdSetParam((batch[loop].entry & 0xFFC1) | (1 << (voice_loop + 1)), batch[loop].value);
                                                         cmd_count++;
                                                 }
                                         }
                                         cmd_count--;
                                 }
                         } break;
                         case SD_BATCH_GETPARAM:
{
                                 if((batch[loop].entry & 0x3E) != 0x3E)
{
                                         ret = sceSdGetParam(batch[loop].entry);
                                 }
                                 else
{
                                         for(voice_loop = 0; voice_loop < 24; voice_loop++)
{
                                                 if(voice & (1 << voice_loop))
{
                                                         ret = sceSdGetParam((batch[loop].entry & 0xFFC1) | (1 << (voice_loop + 1)));
                                                         cmd_count++;
                                                 }
                                                 if(rets)
{
                                                         rets[cmd_count] = ret;
                                                 }
                                         }
                                         cmd_count--;
                                 }
                         } break;
                         case SD_BATCH_SETSWITCH:
                                 sceSdSetSwitch(batch[loop].entry, batch[loop].value);
                         break;
                         case SD_BATCH_GETSWITCH:
                                 ret = sceSdGetSwitch(batch[loop].entry);
                         break;
                         case SD_BATCH_SETADDR:
{
                                 if((batch[loop].entry & 0x3E) != 0x3E)
{
                                         sceSdSetAddr(batch[loop].entry, batch[loop].value);
                                 }
                                 else
{
                                         for(voice_loop = 0; voice_loop < 24; voice_loop++)
{
                                                 if(voice & (1 << voice_loop))
{
                                                         sceSdSetAddr((batch[loop].entry & 0xFFC1) | (1 << (voice_loop + 1)), batch[loop].value);
                                                         cmd_count++;
                                                 }
                                         }
                                 }
                                 cmd_count--;
                         } break;
                         case SD_BATCH_GETADDR:
{
                                 if((batch[loop].entry & 0x3E) != 0x3E)
{
                                         ret = sceSdGetAddr(batch[loop].entry);
                                 }
                                 else
{
                                         for(voice_loop = 0; voice_loop < 24; voice_loop++)
{
                                                 if(voice & (1 << voice_loop))
{
                                                 ret = sceSdGetAddr((batch[loop].entry & 0xFFC1) | (1 << (voice_loop + 1)));
                                                 cmd_count++;
                                                 }
                                                 if(rets)
{
                                                 rets[cmd_count] = ret;
                                                 }
                                         }
                                 }
                                 cmd_count--;
                         } break;
                         case SD_BATCH_SETCORE:
                                 sceSdSetCoreAttr(batch[loop].entry, batch[loop].value);
                                 break;
                         case SD_BATCH_GETCORE:
                                 ret = sceSdGetCoreAttr(batch[loop].entry);
                                 break;
                         case SD_BATCH_WRITEIOP:
                                 *((u32 *) batch[loop].value) = batch[loop].entry;
                                 break;
                         case SD_BATCH_WRITEEE:
                                 BatchData = batch[loop].entry;
                                 SifDmaBatch(batch[loop].value, &BatchData, 4);
                                 break;
                         case SD_BATCH_EERETURN:
                                 SifDmaBatch(batch[loop].value, rets, batch[loop].entry);
                                 break;
                         default:
                                 return -1 - cmd_count;
                 }
                 if(rets)
                 {
                         rets[cmd_count] = ret;
                 }
                 cmd_count++;
         }
         return cmd_count;
 }
References BatchData, sceSdBatch::entry, sceSdGetAddr(), sceSdGetCoreAttr(), sceSdGetParam(), sceSdGetSwitch(), sceSdSetAddr(), sceSdSetCoreAttr(), sceSdSetParam(), sceSdSetSwitch(), SD_BATCH_EERETURN, SD_BATCH_GETADDR, SD_BATCH_GETCORE, SD_BATCH_GETPARAM, SD_BATCH_GETSWITCH, SD_BATCH_SETADDR, SD_BATCH_SETCORE, SD_BATCH_SETPARAM, SD_BATCH_SETSWITCH, SD_BATCH_WRITEEE, SD_BATCH_WRITEIOP, and SifDmaBatch().
Referenced by rpc_server().
sceSdQuit()
int sceSdQuit ()
Definition at line 831 of file freesd.c.
 {
         s32 ret;
         DmaStop(0);
         DmaStop(1);
         DisableIntr(0x28, (int *)&ret);
         DisableIntr(0x24, (int *)&ret);
         DisableIntr(0x9, (int *)&ret);
         ReleaseIntrHandler(0x28);
         ReleaseIntrHandler(0x24);
         ReleaseIntrHandler(0x9);
         return 0;
 }
References DisableIntr(), DmaStop(), and ReleaseIntrHandler().
sceSdSetAddr()
void sceSdSetAddr (u16 entry, u32 value)
Definition at line 848 of file freesd.c.
 {
         volatile u16 *reg1;
         u16 voice;
         reg1 = ParamRegList[(reg >> 8) & 0xFF] + ((reg & 1) << 9);
         voice = reg & 0x3E;
         reg1 += ((voice << 1) + voice);
         *reg1++ = (val >> 17) & 0xFFFF;
         if((reg & 0xFF00) != 0x1D00)
         {
                 *reg1 = (val >> 1) & 0xFFF8;
         }
 }
References ParamRegList.
Referenced by audsrv_ch_play_adpcm(), rpc_server(), sceSdProcBatch(), sceSdProcBatchEx(), sndStreamSetPosition(), and stream_thread().
sceSdSetCoreAttr()
void sceSdSetCoreAttr (u16 entry, u16 value)
Definition at line 498 of file spu2.c.
 {
         u16 core_attr = *SD_CORE_ATTR(entry & 1);
         switch(entry & ~1)
         {
                 case SD_CORE_NOISE_CLK: // 0x8
                         *SD_CORE_ATTR(entry & 1) = (core_attr-0x3F01) | ((val & 0x3F) << 8);
                         break;
                 #ifndef ISJPCM
                 case SD_CORE_SPDIF_MODE: // 0xA
                         SetSpdifMode(val); // sub1
                         break;
                 #endif
                 default:
                 {
                         u32 core = entry & 1;
                         entry = (entry >> 1)-1;
                         core_attr &= ~(1 << CoreAttrShifts[entry]);
                         core_attr |= (val & 1) << CoreAttrShifts[entry];
                         *SD_CORE_ATTR(core) = core_attr;
                 }
                 break;
         }
 }
References CoreAttrShifts, SD_CORE_ATTR, SD_CORE_NOISE_CLK, SD_CORE_SPDIF_MODE, and SetSpdifMode().
Referenced by rpc_server(), sceSdProcBatch(), sceSdProcBatchEx(), sndStreamOpen(), sndStreamPause(), sndStreamPlay(), and stream_thread().
sceSdSetEffectAttr()
int sceSdSetEffectAttr (int core, sceSdEffectAttr * attr)
Definition at line 109 of file effect.c.
 {
         u32 mode = attr->mode;
         u32 clearram = 0;
         u32 effects_disabled = 0;
         u32 last_mode = 0;
         u16     mode_data[32];
         core &= 1;
         if(mode & SD_EFFECT_MODE_CLEAR)
         {
                 mode &= ~SD_EFFECT_MODE_CLEAR;
                 clearram = 1;
                 last_mode = EffectAttr[core].mode;
         }
         // Check if valid mode
         if(mode > 9) return -1;
         EffectAddr[core] = GetEEA(core) - ((EffectSizes[mode] << 4) - 2);
         memcpy(mode_data, &EffectParams[mode * 16], 64);
         memcpy(&EffectAttr[core], attr, sizeof(sceSdEffectAttr));
         EffectAttr[core].core = core;
         switch(mode)
         {
                 case SD_EFFECT_MODE_ECHO:
                         EffectAttr[core].feedback = 0x80;
                         EffectAttr[core].delay = 0x80;
                         break;
                 case SD_EFFECT_MODE_DELAY:
                         EffectAttr[core].feedback = 0;
                         EffectAttr[core].delay = 0x80;
                         break;
                 default:
                         EffectAttr[core].feedback = 0;
                         EffectAttr[core].delay = 0;
                         break;
         }
         if((mode == SD_EFFECT_MODE_DELAY) || (mode == SD_EFFECT_MODE_ECHO))
         {
                 u16 delay               = ((attr->delay+1) << 5);
                 u16 feedback    = ((attr->feedback << 7) + attr->feedback) << 1;
                 mode_data[7]  = feedback;
                 mode_data[10] = (delay << 1) - mode_data[0];
                 mode_data[11] = delay - mode_data[1];
                 mode_data[16] = mode_data[17] + delay;
                 mode_data[12] = mode_data[13] + delay;
                 mode_data[27] = mode_data[29] + delay;
                 mode_data[26] = mode_data[28] + delay;
         }
         // Disable effects
         if(*SD_CORE_ATTR(core) & SD_ENABLE_EFFECTS)
         {
                 effects_disabled = 1;
                 *SD_CORE_ATTR(core) &= ~SD_ENABLE_EFFECTS;
         }
         // Clean up after last mode
         if((effects_disabled) && (clearram))
                 sceSdClearEffectWorkArea(core, 0, last_mode);
         // Depth / Volume
         *SD_P_EVOLL(core) = attr->depth_L;
         *SD_P_EVOLR(core) = attr->depth_R;
         SetEffectData(mode_data, core);
         // Set effect start addr (ESA)
         SetESA(core, EffectAddr[core]);
         if(clearram)
                 sceSdClearEffectWorkArea(core, 0, mode);
         // Enable effects
         if(effects_disabled)
                 *SD_CORE_ATTR(core) |= SD_ENABLE_EFFECTS;
         return 0;
 }
References sceSdEffectAttr::core, sceSdEffectAttr::delay, sceSdEffectAttr::depth_L, sceSdEffectAttr::depth_R, EffectAddr, EffectAttr, EffectParams, EffectSizes, sceSdEffectAttr::feedback, GetEEA(), memcpy(), sceSdEffectAttr::mode, sceSdClearEffectWorkArea(), SD_CORE_ATTR, SD_EFFECT_MODE_CLEAR, SD_EFFECT_MODE_DELAY, SD_EFFECT_MODE_ECHO, SD_ENABLE_EFFECTS, SD_P_EVOLL, SD_P_EVOLR, SetEffectData(), and SetESA().
Referenced by rpc_server().
sceSdSetEffectMode()
int sceSdSetEffectMode (int core, sceSdEffectAttr * param)
sceSdSetEffectModeParams()
int sceSdSetEffectModeParams (int core, sceSdEffectAttr * attr)
sceSdSetIRQCallback()
SdIntrCallback sceSdSetIRQCallback (SdIntrCallback cb)
Definition at line 913 of file freesd.c.
 {
         SdIntrCallback old_cb;
         old_cb = Spu2IrqCallback;
         Spu2IrqCallback = cb;
         return old_cb;
 }
References Spu2IrqCallback.
sceSdSetParam()
void sceSdSetParam (u16 entry, u16 value)
Definition at line 525 of file spu2.c.
 {
         #ifndef ISJPCM
         u32 offs;
         u32 voice;
         u32 reg_index;
         u32 core;
         volatile u16 *reg_p;
         core = reg & 1;
         // Determine the channel offset
         if(reg & 0x80)
                 offs = (40 * core) >> 1;
         else
                 offs = (1024 * core) >> 1;
         reg_index = (reg >> 8) & 0xFF;
         voice = (reg & 0x3E) << 2;
         reg_p = ParamRegList[reg_index] + offs + voice;
         *reg_p = val;
         #else
         u32 core;
         core = reg & 1;
         reg &= ~1;
         switch(reg)
         {
                 case SD_PARAM_MVOLL:
                         *SD_P_MVOLL(core) = val;
                 break;
                 case SD_PARAM_MVOLR:
                         *SD_P_MVOLR(core) = val;
                 break;
                 case SD_PARAM_BVOLL:
                         *SD_P_BVOLL(core) = val;
                 break;
                 case SD_PARAM_BVOLR:
                         *SD_P_BVOLR(core) = val;
                 break;
         }
         #endif
 }
References ParamRegList, SD_P_BVOLL, SD_P_BVOLR, SD_P_MVOLL, SD_P_MVOLR, SD_PARAM_BVOLL, SD_PARAM_BVOLR, SD_PARAM_MVOLL, and SD_PARAM_MVOLR.
Referenced by AHX_Init(), AHX_SetVol(), audsrv_adpcm_init(), audsrv_adpcm_set_volume(), audsrv_ch_play_adpcm(), audsrv_play_cd(), rpc_server(), sceSdProcBatch(), sceSdProcBatchEx(), sndStreamOpen(), sndStreamSetVolume(), and update_volume().
sceSdSetSpu2IntrHandler()
sceSdSpu2IntrHandler sceSdSetSpu2IntrHandler (sceSdSpu2IntrHandler func, void * arg)
Definition at line 327 of file freesd.c.
 {
         sceSdSpu2IntrHandler old_handler;
         old_handler = Spu2IntrHandler;
         Spu2IntrHandler = handler;
         Spu2IntrData = data;
         return old_handler;
 }
References handler, Spu2IntrData, and Spu2IntrHandler.
Referenced by sndStreamClose(), and sndStreamOpen().
sceSdSetSwitch()
void sceSdSetSwitch (u16 entry, u32 value)
Definition at line 552 of file freesd.c.
 {
         u32 reg_index;
         volatile u16 *reg_p;
         reg_index = (reg >> 8) & 0xFF;
         reg_p = ParamRegList[reg_index] + ((reg & 1) << 9);
         reg_p[0] = (u16)val;
         reg_p[1] = (u16)((val >> 16) & 0xFF);
 }
References ParamRegList.
Referenced by audsrv_adpcm_init(), audsrv_ch_play_adpcm(), rpc_server(), sceSdProcBatch(), sceSdProcBatchEx(), sndStreamPause(), and sndStreamPlay().
sceSdSetTransCallback()
SdIntrCallback sceSdSetTransCallback (s32 core, SdIntrCallback cb)
Definition at line 577 of file spu2.c.
 {
         SdIntrCallback old_cb;
         old_cb = TransIntrCallbacks[core & 1];
         TransIntrCallbacks[core & 1] = cb;
         return old_cb;
 }
References TransIntrCallbacks.
Referenced by AHX_Init(), AHX_Quit(), audsrv_init(), audsrv_quit(), audsrv_stop_cd_stream(), and cdda_procedure().
sceSdSetTransIntrHandler()
sceSdTransIntrHandler sceSdSetTransIntrHandler (int channel, sceSdTransIntrHandler func, void * arg)
Definition at line 818 of file freesd.c.
 {
         sceSdTransIntrHandler old_handler;
         old_handler = TransIntrHandlers[chan & 1];
         TransIntrHandlers[chan & 1] = func;
         TransIntrData[chan & 1].data = data;
         return old_handler;
 }
References IntrData::data, TransIntrData, and TransIntrHandlers.
sceSdStopTrans()
int sceSdStopTrans (int channel)
sceSdVoiceTrans()
int sceSdVoiceTrans (s16 chan, u16 mode, u8 * iopaddr, u32 * spuaddr, u32 size)
Definition at line 122 of file voice.c.
 {
         s32 res = size;
         chan &= 1;
         if(mode & SD_TRANS_MODE_IO)
                 VoiceTransIoMode[chan] = 1;
         else
                 VoiceTransIoMode[chan] = 0;
         if(VoiceTransIoMode[chan] == 0)
         {
                 res = VoiceTransDma(chan, mode & 3, iopaddr, spuaddr, size);
         }
         else
         {
                 if((mode & 3) == SD_TRANS_WRITE)
                 {
                         res = VoiceTrans_Write_IOMode( (u32)iopaddr, (u32)spuaddr, size, chan);
                 }
         }
         VoiceTransStatus[chan] = 0;
         return res;
 }
References SD_TRANS_MODE_IO, SD_TRANS_WRITE, VoiceTrans_Write_IOMode(), VoiceTransDma(), VoiceTransIoMode, and VoiceTransStatus.
Referenced by audsrv_load_adpcm(), fillbuf(), rpc_server(), and sceSdClearEffectWorkArea().
sceSdVoiceTransStatus()
u32 sceSdVoiceTransStatus (s16 channel, s16 flag)
Definition at line 150 of file voice.c.
 {
         chan &= 1;
         flag &= 1;
         if((VoiceTransIoMode[chan] == 1) || (VoiceTransStatus[chan] == 1))
                 return 1;
         if(flag)
         {
                 while(!VoiceTransComplete[chan]);
                 VoiceTransStatus[chan] = 1;
                 VoiceTransComplete[chan] = 0;
                 return 1;
         }
         else
         {
                 if(VoiceTransComplete[chan] == 0) return 0;
                 VoiceTransStatus[chan] = 1;
                 VoiceTransComplete[chan] = 0;
         }
         return 0;
 }
References VoiceTransComplete, VoiceTransIoMode, and VoiceTransStatus.
Referenced by audsrv_load_adpcm(), fillbuf(), rpc_server(), and sceSdClearEffectWorkArea().