ps2sdk: iop/kernel/include/loadcore.h File Reference
loadcore.h File Reference
#include <types.h>
#include <irx.h>
Data Structures
struct ModuleInfo_t
struct iop_library_t
struct lc_internals_t
struct iop_bootmode_t
struct iop_init_entry_t
struct iop_library_table_t
Macros
#define MODULE_RESIDENT_END 0
#define MODULE_NO_RESIDENT_END 1
#define loadcore_IMPORTS
#define loadcore_IMPORTS_start DECLARE_IMPORT_TABLE(loadcore, 1, 1)
#define loadcore_IMPORTS_end END_IMPORT_TABLE
#define I_GetLibraryEntryTable DECLARE_IMPORT(3, GetLibraryEntryTable)
#define I_GetLoadcoreInternalData DECLARE_IMPORT(3, GetLoadcoreInternalData)
#define I_FlushIcache DECLARE_IMPORT(4, FlushIcache)
#define I_FlushDcache DECLARE_IMPORT(5, FlushDcache)
#define I_RegisterLibraryEntries DECLARE_IMPORT(6, RegisterLibraryEntries)
#define I_ReleaseLibraryEntries DECLARE_IMPORT(7, ReleaseLibraryEntries)
#define I_RegisterNonAutoLinkEntries DECLARE_IMPORT(10, RegisterNonAutoLinkEntries)
#define I_QueryLibraryEntryTable DECLARE_IMPORT(11, QueryLibraryEntryTable)
#define I_QueryBootMode DECLARE_IMPORT(12, QueryBootMode)
#define I_RegisterBootMode DECLARE_IMPORT(13, RegisterBootMode)
#define I_RegisterBootCallback DECLARE_IMPORT(20, RegisterBootCallback);
Typedefs
typedef int(* BootupCallback_t) (iop_init_entry_t *next, int delayed)
Functions
iop_library_table_t * GetLibraryEntryTable (void)
lc_internals_t * GetLoadcoreInternalData (void)
void FlushIcache (void)
void FlushDcache (void)
int RegisterLibraryEntries (struct irx_export_table *exports)
int ReleaseLibraryEntries (struct irx_export_table *exports)
int RegisterNonAutoLinkEntries (struct irx_export_table *exports)
void * QueryLibraryEntryTable (iop_library_t *library)
int * QueryBootMode (int mode)
void RegisterBootMode (iop_bootmode_t *b)
int RegisterPostBootCallback (BootupCallback_t func, int priority, int *stat)
Detailed Description
Kernel module loader.
Definition in file loadcore.h.
Macro Definition Documentation
I_FlushDcache
#define I_FlushDcache DECLARE_IMPORT(5, FlushDcache)
Definition at line 129 of file loadcore.h.
I_FlushIcache
#define I_FlushIcache DECLARE_IMPORT(4, FlushIcache)
Definition at line 128 of file loadcore.h.
I_GetLibraryEntryTable
#define I_GetLibraryEntryTable DECLARE_IMPORT(3, GetLibraryEntryTable)
Definition at line 126 of file loadcore.h.
I_GetLoadcoreInternalData
#define I_GetLoadcoreInternalData DECLARE_IMPORT(3, GetLoadcoreInternalData)
Definition at line 127 of file loadcore.h.
I_QueryBootMode
#define I_QueryBootMode DECLARE_IMPORT(12, QueryBootMode)
Definition at line 134 of file loadcore.h.
I_QueryLibraryEntryTable
#define I_QueryLibraryEntryTable DECLARE_IMPORT(11, QueryLibraryEntryTable)
Definition at line 133 of file loadcore.h.
I_RegisterBootCallback
#define I_RegisterBootCallback DECLARE_IMPORT(20, RegisterBootCallback);
Definition at line 136 of file loadcore.h.
I_RegisterBootMode
#define I_RegisterBootMode DECLARE_IMPORT(13, RegisterBootMode)
Definition at line 135 of file loadcore.h.
I_RegisterLibraryEntries
#define I_RegisterLibraryEntries DECLARE_IMPORT(6, RegisterLibraryEntries)
Definition at line 130 of file loadcore.h.
I_RegisterNonAutoLinkEntries
#define I_RegisterNonAutoLinkEntries DECLARE_IMPORT(10, RegisterNonAutoLinkEntries)
Definition at line 132 of file loadcore.h.
I_ReleaseLibraryEntries
#define I_ReleaseLibraryEntries DECLARE_IMPORT(7, ReleaseLibraryEntries)
Definition at line 131 of file loadcore.h.
loadcore_IMPORTS
#define loadcore_IMPORTS
Value:
        loadcore_IMPORTS_start \
 \
        I_GetLibraryEntryTable \
 \
        I_FlushIcache \
        I_FlushDcache \
 \
        I_RegisterLibraryEntries \
        I_ReleaseLibraryEntries \
 \
        I_QueryLibraryEntryTable \
        I_QueryBootMode \
 \
        loadcore_IMPORTS_end
Definition at line 107 of file loadcore.h.
loadcore_IMPORTS_end
#define loadcore_IMPORTS_end END_IMPORT_TABLE
Definition at line 124 of file loadcore.h.
loadcore_IMPORTS_start
#define loadcore_IMPORTS_start DECLARE_IMPORT_TABLE(loadcore, 1, 1)
Definition at line 123 of file loadcore.h.
MODULE_NO_RESIDENT_END
#define MODULE_NO_RESIDENT_END 1
Definition at line 23 of file loadcore.h.
MODULE_RESIDENT_END
#define MODULE_RESIDENT_END 0
Definition at line 22 of file loadcore.h.
Typedef Documentation
BootupCallback_t
typedef int(* BootupCallback_t) (iop_init_entry_t *next, int delayed)
Definition at line 77 of file loadcore.h.
Function Documentation
FlushDcache()
void FlushDcache (void)
Referenced by _sif2_cmd_dbg_control(), _start(), fix_imports(), and TransInterrupt().
FlushIcache()
void FlushIcache (void)
Referenced by _sif2_cmd_dbg_control(), _start(), AddDrv(), and fix_imports().
GetLibraryEntryTable()
iop_library_table_t* GetLibraryEntryTable (void)
Retained for backward-compatibility with older projects. This function actually returns a pointer to LOADCORE's internal data structure.
GetLoadcoreInternalData()
lc_internals_t* GetLoadcoreInternalData (void)
Referenced by _start(), devscan_getmodule(), list_all_libraries(), slib_get_lib_by_name(), and smod_get_next_mod().
QueryBootMode()
int* QueryBootMode (int mode)
Referenced by pcmcia_init().
QueryLibraryEntryTable()
void* QueryLibraryEntryTable (iop_library_t * library)
Referenced by hook_ioman().
RegisterBootMode()
void RegisterBootMode (iop_bootmode_t * b)
RegisterLibraryEntries()
int RegisterLibraryEntries (struct irx_export_table * exports)
Referenced by _start(), expbay_init(), InitializeLWIP(), and pcmcia_init().
RegisterNonAutoLinkEntries()
int RegisterNonAutoLinkEntries (struct irx_export_table * exports)
RegisterPostBootCallback()
int RegisterPostBootCallback (BootupCallback_t func, int priority, int * stat)
ReleaseLibraryEntries()
int ReleaseLibraryEntries (struct irx_export_table * exports)
Referenced by _exit(), _start(), and slib_release_library().