ps2sdk: iop/system/sio2man/include/log.h File Reference
log.h File Reference
#include <types.h>
#include "sio2man.h"
Enumerations
enum _log_types {
LOG_HEADER = 0x02 ,
LOG_PAD_READY ,
LOG_MC_READY ,
LOG_MTAP_READY ,
LOG_TRS ,
LOG_TRS_PD ,
LOG_TRS_RD ,
LOG_TRS_DATA ,
LOG_TRS_DMA_IN ,
LOG_TRS_DMA_OUT ,
LOG_TRR ,
LOG_TRR_STAT ,
LOG_TRR_DATA ,
LOG_RESET
}
Functions
void log_write8 (u8 val)
void log_write32 (u32 val)
void log_flush (int now)
void log_default (int type)
void log_portdata (u32 *pd1, u32 *pd2)
void log_regdata (u32 *rd)
void log_data (int type, u8 *data, u32 size)
void log_dma (int type, struct _sio2_dma_arg *arg)
void log_stat (u32 stat6c, u32 stat70, u32 stat74)
Detailed Description
SIO2 logging.
Definition in file log.h.
Enumeration Type Documentation
_log_types
enum _log_types
Enumerator
LOG_HEADER
LOG_PAD_READY
LOG_MC_READY
LOG_MTAP_READY
LOG_TRS
LOG_TRS_PD
LOG_TRS_RD
LOG_TRS_DATA
LOG_TRS_DMA_IN
LOG_TRS_DMA_OUT
LOG_TRR
LOG_TRR_STAT
LOG_TRR_DATA
LOG_RESET
Definition at line 23 of file log.h.
                 {
         LOG_HEADER = 0x02, LOG_PAD_READY, LOG_MC_READY, LOG_MTAP_READY,
         LOG_TRS, LOG_TRS_PD, LOG_TRS_RD, LOG_TRS_DATA, LOG_TRS_DMA_IN,
         LOG_TRS_DMA_OUT,
         LOG_TRR, LOG_TRR_STAT, LOG_TRR_DATA,
         LOG_RESET
 };
Function Documentation
log_data()
void log_data (int type, u8 * data, u32 size)
Referenced by recv_td(), and send_td().
log_default()
void log_default (int type)
Referenced by main_thread(), recv_td(), and send_td().
log_dma()
void log_dma (int type, struct _sio2_dma_arg * arg)
Referenced by send_td().
log_flush()
void log_flush (int now)
Referenced by main_thread(), and shutdown().
log_portdata()
void log_portdata (u32 * pd1, u32 * pd2)
Referenced by send_td().
log_regdata()
void log_regdata (u32 * rd)
Referenced by send_td().
log_stat()
void log_stat (u32 stat6c, u32 stat70, u32 stat74)
Referenced by recv_td().
log_write32()
void log_write32 (u32 val)
log_write8()
void log_write8 (u8 val)