ps2sdk: iop/network/smap/src/include/main.h File Reference
main.h File Reference
#include "xfer.h"
Data Structures
struct SmapDriverData
Macros
#define DEBUG_PRINTF(args...) printf(args)
#define SMAP_EVENT_START 0x01
#define SMAP_EVENT_STOP 0x02
#define SMAP_EVENT_INTR 0x04
#define SMAP_EVENT_XMIT 0x08
#define SMAP_EVENT_LINK_CHECK 0x10
Functions
int DisplayBanner (void)
int smap_init (int argc, char *argv[])
int SMAPStart (void)
void SMAPStop (void)
void SMAPXmit (void)
int SMAPGetMACAddress (u8 *buffer)
Macro Definition Documentation
DEBUG_PRINTF
#define DEBUG_PRINTF (args...) printf(args)
Definition at line 2 of file main.h.
SMAP_EVENT_INTR
#define SMAP_EVENT_INTR 0x04
Definition at line 29 of file main.h.
SMAP_EVENT_LINK_CHECK
#define SMAP_EVENT_LINK_CHECK 0x10
Definition at line 31 of file main.h.
SMAP_EVENT_START
#define SMAP_EVENT_START 0x01
Definition at line 27 of file main.h.
SMAP_EVENT_STOP
#define SMAP_EVENT_STOP 0x02
Definition at line 28 of file main.h.
SMAP_EVENT_XMIT
#define SMAP_EVENT_XMIT 0x08
Definition at line 30 of file main.h.
Function Documentation
DisplayBanner()
int DisplayBanner (void)
Definition at line 67 of file smap.c.
{
         printf("SMAP (%s)\n", VersionString);
         return MODULE_NO_RESIDENT_END;
 }
References MODULE_NO_RESIDENT_END, printf(), and VersionString.
Referenced by _start(), DisplayHelpMessage(), and smap_init().
smap_init()
int smap_init (int argc, char * argv[])
Definition at line 825 of file smap.c.
{
         int result, i;
         const char *CmdString;
         u16 eeprom_data[4], checksum16;
         u32 mac_address;
         USE_SPD_REGS;
         USE_SMAP_REGS;
         USE_SMAP_EMAC3_REGS;
         USE_SMAP_TX_BD;
         USE_SMAP_RX_BD;
         checksum16=0;
         argc--;
         argv++;
         while(argc>0){
                 if(strcmp("-help", *argv)==0){
                         return DisplayHelpMessage();
                 }
                 else if(strcmp("-version", *argv)==0){
                         return DisplayBanner();
                 }
                 else if(strcmp("-verbose", *argv)==0){
                         EnableVerboseOutput=1;
                 }
                 else if(strcmp("-auto", *argv)==0){
                         EnableAutoNegotiation=1;
                 }
                 else if(strcmp("-no_auto", *argv)==0){
                         EnableAutoNegotiation=0;
                 }
                 else if(strcmp("-strap", *argv)==0){
                         EnablePinStrapConfig=1;
                 }
                 else if(strcmp("-no_strap", *argv)==0){
                         EnablePinStrapConfig=0;
                 }
                 else if(strncmp("thpri=", *argv, 6)==0){
                         CmdString=&(*argv)[6];
                         if(isdigit(CmdString[0])){
                                 ThreadPriority=strtoul(&(*argv)[6], NULL, 10);
                                 if(ThreadPriority-9>=0x73){
                                         return DisplayHelpMessage();
                                 }
                                 if((*argv)[6]!='\0'){
                                         while(isdigit(*CmdString)){
                                                 CmdString++;
                                         }
                                         if(*CmdString!='\0') return DisplayHelpMessage();
                                 }
                         }
                         else return DisplayHelpMessage();
                 }
                 else if(strncmp("thstack=", *argv, 8)==0){
                         CmdString=&(*argv)[8];
                         if(isdigit(CmdString[0])){
                                 ThreadStackSize=strtoul(&(*argv)[8], NULL, 10);
                                 if((*argv)[8]!='\0'){
                                         while(isdigit(*CmdString)){
                                                 CmdString++;
                                         }
                                 }
                                 if(strcmp(CmdString, "KB")==0) ThreadStackSize<<=10;
                         }
                         else return DisplayHelpMessage();
                 }
                 else{
                         if(ParseSmapConfiguration(*argv, &SmapConfiguration)!=0) return DisplayHelpMessage();
                 }
                 argc--;
                 argv++;
         }
         if(argc!=0) return DisplayHelpMessage();
         SmapDriverData.smap_regbase=smap_regbase;
         SmapDriverData.emac3_regbase=emac3_regbase;
         if(!SPD_REG16(SPD_R_REV_3)&SPD_CAPS_SMAP) return -1;
         if(SPD_REG16(SPD_R_REV_1)<0x11) return -6;      // Minimum: revision 17, ES2.
         dev9IntrDisable(DEV9_SMAP_ALL_INTR_MASK);
         /* Reset FIFOs. */
         SMAP_REG8(SMAP_R_TXFIFO_CTRL)=SMAP_TXFIFO_RESET;
         for(i=9; SMAP_REG8(SMAP_R_TXFIFO_CTRL)&SMAP_TXFIFO_RESET; i--){
                 if(i<=0) return -2;
                 DelayThread(1000);
         }
         SMAP_REG8(SMAP_R_RXFIFO_CTRL)=SMAP_RXFIFO_RESET;
         for(i=9; SMAP_REG8(SMAP_R_RXFIFO_CTRL)&SMAP_RXFIFO_RESET; i--){
                 if(i<=0) return -3;
                 DelayThread(1000);
         }
         SMAP_EMAC3_SET32(SMAP_R_EMAC3_MODE0, SMAP_E3_SOFT_RESET);
         for(i=9; SMAP_EMAC3_GET32(SMAP_R_EMAC3_MODE0)&SMAP_E3_SOFT_RESET; i--){
                 if(i<=0) return -4;
                 DelayThread(1000);
         }
         SMAP_REG8(SMAP_R_BD_MODE) = 0;
         for(i=0; i<SMAP_BD_MAX_ENTRY; i++){
                 tx_bd[i].ctrl_stat=0;
                 tx_bd[i].reserved=0;
                 tx_bd[i].length=0;
                 tx_bd[i].pointer=0;
         }
         for(i=0; i<SMAP_BD_MAX_ENTRY; i++){
                 rx_bd[i].ctrl_stat=SMAP_BD_RX_EMPTY;
                 rx_bd[i].reserved=0;
                 rx_bd[i].length=0;
                 rx_bd[i].pointer=0;
         }
         SmapDriverData.TxBufferSpaceAvailable=SMAP_TX_BUFSIZE;
         SMAP_REG16(SMAP_R_INTR_CLR)=DEV9_SMAP_ALL_INTR_MASK;
         /* Retrieve the MAC address and verify it's integrity. */
         bzero(eeprom_data, 8);
         if((result=dev9GetEEPROM(eeprom_data))<0){
                 return(result==-1?-7:-4);
         }
         for(i=0; i<3; i++) checksum16+=eeprom_data[i];
         if(eeprom_data[0]==0 && eeprom_data[1]==0 && eeprom_data[2]==0){
                 return -5;
         }
         if(checksum16!=eeprom_data[3]) return -5;
         SMAP_EMAC3_SET32(SMAP_R_EMAC3_MODE1, SMAP_E3_FDX_ENABLE|SMAP_E3_IGNORE_SQE|SMAP_E3_MEDIA_100M|SMAP_E3_RXFIFO_2K|SMAP_E3_TXFIFO_1K|SMAP_E3_TXREQ0_MULTI|SMAP_E3_TXREQ1_SINGLE);
         //Tx FIFO request priority. Low: 7*8=56, urgent: 15*8=120.
         SMAP_EMAC3_SET32(SMAP_R_EMAC3_TxMODE1, (7&SMAP_E3_TX_LOW_REQ_MSK) << SMAP_E3_TX_LOW_REQ_BITSFT | (15&SMAP_E3_TX_URG_REQ_MSK) << SMAP_E3_TX_URG_REQ_BITSFT);
         SMAP_EMAC3_SET32(SMAP_R_EMAC3_RxMODE, SMAP_E3_RX_STRIP_PAD|SMAP_E3_RX_STRIP_FCS|SMAP_E3_RX_INDIVID_ADDR|SMAP_E3_RX_BCAST|SMAP_E3_RX_MCAST);
         SMAP_EMAC3_SET32(SMAP_R_EMAC3_INTR_STAT, SMAP_E3_INTR_TX_ERR_0|SMAP_E3_INTR_SQE_ERR_0|SMAP_E3_INTR_DEAD_0);
         SMAP_EMAC3_SET32(SMAP_R_EMAC3_INTR_ENABLE, SMAP_E3_INTR_TX_ERR_0|SMAP_E3_INTR_SQE_ERR_0|SMAP_E3_INTR_DEAD_0);
         mac_address=(u16)(eeprom_data[0]>>8 | eeprom_data[0]<<8);
         SMAP_EMAC3_SET32(SMAP_R_EMAC3_ADDR_HI, mac_address);
         mac_address=((u16)(eeprom_data[1]>>8 | eeprom_data[1]<<8) << 16) | (u16)(eeprom_data[2]>>8 | eeprom_data[2]<<8);
         SMAP_EMAC3_SET32(SMAP_R_EMAC3_ADDR_LO, mac_address);
         SMAP_EMAC3_SET32(SMAP_R_EMAC3_PAUSE_TIMER, 0xFFFF);
         SMAP_EMAC3_SET32(SMAP_R_EMAC3_GROUP_HASH1, 0);
         SMAP_EMAC3_SET32(SMAP_R_EMAC3_GROUP_HASH2, 0);
         SMAP_EMAC3_SET32(SMAP_R_EMAC3_GROUP_HASH3, 0);
         SMAP_EMAC3_SET32(SMAP_R_EMAC3_GROUP_HASH4, 0);
         SMAP_EMAC3_SET32(SMAP_R_EMAC3_INTER_FRAME_GAP, 4);
         //Tx threshold, (12+1)*64=832.
         SMAP_EMAC3_SET32(SMAP_R_EMAC3_TX_THRESHOLD, (12&SMAP_E3_TX_THRESHLD_MSK) << SMAP_E3_TX_THRESHLD_BITSFT);
         //Rx watermark, low: 16*8=128, high: 128*8=1024.
         SMAP_EMAC3_SET32(SMAP_R_EMAC3_RX_WATERMARK, (16&SMAP_E3_RX_LO_WATER_MSK) << SMAP_E3_RX_LO_WATER_BITSFT | (128&SMAP_E3_RX_HI_WATER_MSK) << SMAP_E3_RX_HI_WATER_BITSFT);
         //Register the interrupt handlers for all SMAP events.
         for(i=2; i<7; i++) dev9RegisterIntrCb(i, &Dev9IntrCb);
         dev9RegisterPreDmaCb(1, &Dev9PreDmaCbHandler);
         dev9RegisterPostDmaCb(1, &Dev9PostDmaCbHandler);
         return SetupNetDev();
 }
References bzero(), DelayThread(), DEV9_SMAP_ALL_INTR_MASK, dev9GetEEPROM(), Dev9IntrCb(), dev9IntrDisable(), Dev9PostDmaCbHandler(), Dev9PreDmaCbHandler(), dev9RegisterIntrCb(), dev9RegisterPostDmaCb(), dev9RegisterPreDmaCb(), DisplayBanner(), DisplayHelpMessage(), eeprom_data, SmapDriverData::emac3_regbase, EnableAutoNegotiation, EnablePinStrapConfig, EnableVerboseOutput, isdigit, NULL, ParseSmapConfiguration(), result, SetupNetDev(), SMAP_BD_MAX_ENTRY, SMAP_BD_RX_EMPTY, SMAP_E3_FDX_ENABLE, SMAP_E3_IGNORE_SQE, SMAP_E3_INTR_DEAD_0, SMAP_E3_INTR_SQE_ERR_0, SMAP_E3_INTR_TX_ERR_0, SMAP_E3_MEDIA_100M, SMAP_E3_RX_BCAST, SMAP_E3_RX_HI_WATER_BITSFT, SMAP_E3_RX_HI_WATER_MSK, SMAP_E3_RX_INDIVID_ADDR, SMAP_E3_RX_LO_WATER_BITSFT, SMAP_E3_RX_LO_WATER_MSK, SMAP_E3_RX_MCAST, SMAP_E3_RX_STRIP_FCS, SMAP_E3_RX_STRIP_PAD, SMAP_E3_RXFIFO_2K, SMAP_E3_SOFT_RESET, SMAP_E3_TX_LOW_REQ_BITSFT, SMAP_E3_TX_LOW_REQ_MSK, SMAP_E3_TX_THRESHLD_BITSFT, SMAP_E3_TX_THRESHLD_MSK, SMAP_E3_TX_URG_REQ_BITSFT, SMAP_E3_TX_URG_REQ_MSK, SMAP_E3_TXFIFO_1K, SMAP_E3_TXREQ0_MULTI, SMAP_E3_TXREQ1_SINGLE, SMAP_EMAC3_GET32, SMAP_EMAC3_SET32, SMAP_R_BD_MODE, SMAP_R_EMAC3_ADDR_HI, SMAP_R_EMAC3_ADDR_LO, SMAP_R_EMAC3_GROUP_HASH1, SMAP_R_EMAC3_GROUP_HASH2, SMAP_R_EMAC3_GROUP_HASH3, SMAP_R_EMAC3_GROUP_HASH4, SMAP_R_EMAC3_INTER_FRAME_GAP, SMAP_R_EMAC3_INTR_ENABLE, SMAP_R_EMAC3_INTR_STAT, SMAP_R_EMAC3_MODE0, SMAP_R_EMAC3_MODE1, SMAP_R_EMAC3_PAUSE_TIMER, SMAP_R_EMAC3_RX_WATERMARK, SMAP_R_EMAC3_RxMODE, SMAP_R_EMAC3_TX_THRESHOLD, SMAP_R_EMAC3_TxMODE1, SMAP_R_INTR_CLR, SMAP_R_RXFIFO_CTRL, SMAP_R_TXFIFO_CTRL, SMAP_REG16, SMAP_REG8, SmapDriverData::smap_regbase, SMAP_RXFIFO_RESET, SMAP_TX_BUFSIZE, SMAP_TXFIFO_RESET, SmapConfiguration, SPD_CAPS_SMAP, SPD_R_REV_1, SPD_R_REV_3, SPD_REG16, strcmp(), strncmp(), strtoul(), ThreadPriority, ThreadStackSize, SmapDriverData::TxBufferSpaceAvailable, USE_SMAP_EMAC3_REGS, USE_SMAP_REGS, USE_SMAP_RX_BD, USE_SMAP_TX_BD, and USE_SPD_REGS.
Referenced by _start().
SMAPGetMACAddress()
int SMAPGetMACAddress (u8 * buffer)
Definition at line 993 of file smap.c.
{
         u32 mac_address_lo, mac_address_hi;
         volatile u8 *emac3_regbase;
         int OldState;
         emac3_regbase=SmapDriverData.emac3_regbase;
         CpuSuspendIntr(&OldState);
         mac_address_hi=SMAP_EMAC3_GET32(SMAP_R_EMAC3_ADDR_HI);
         mac_address_lo=SMAP_EMAC3_GET32(SMAP_R_EMAC3_ADDR_LO);
         CpuResumeIntr(OldState);
         buffer[0]=mac_address_hi>>8;
         buffer[1]=mac_address_hi;
         buffer[2]=mac_address_lo>>24;
         buffer[3]=mac_address_lo>>16;
         buffer[4]=mac_address_lo>>8;
         buffer[5]=mac_address_lo;
         return 0;
 }
References buffer, CpuResumeIntr(), CpuSuspendIntr(), SmapDriverData::emac3_regbase, SMAP_EMAC3_GET32, SMAP_R_EMAC3_ADDR_HI, and SMAP_R_EMAC3_ADDR_LO.
Referenced by SMAPIoctl().
SMAPStart()
int SMAPStart (void)
Definition at line 539 of file smap.c.
                    {
         void *OldGP;
         OldGP = SetModuleGP();
         SetEventFlag(SmapDriverData.Dev9IntrEventFlag, SMAP_EVENT_START);
         SetGP(OldGP);
         return 0;
 }
References SmapDriverData::Dev9IntrEventFlag, SetEventFlag(), SetGP(), SetModuleGP, and SMAP_EVENT_START.
Referenced by SetupNetDev().
SMAPStop()
void SMAPStop (void)
Definition at line 551 of file smap.c.
                    {
         void *OldGP;
         OldGP = SetModuleGP();
         SetEventFlag(SmapDriverData.Dev9IntrEventFlag, SMAP_EVENT_STOP);
         SmapDriverData.NetDevStopFlag=1;
         SetGP(OldGP);
 }
References SmapDriverData::Dev9IntrEventFlag, SmapDriverData::NetDevStopFlag, SetEventFlag(), SetGP(), SetModuleGP, and SMAP_EVENT_STOP.
Referenced by SetupNetDev().
SMAPXmit()
void SMAPXmit (void)
Definition at line 577 of file smap.c.
                    {
         void *OldGP;
         OldGP = SetModuleGP();
         if(SmapDriverData.LinkStatus){
                 if(QueryIntrContext())
                         iSetEventFlag(SmapDriverData.Dev9IntrEventFlag, SMAP_EVENT_XMIT);
                 else
                         SetEventFlag(SmapDriverData.Dev9IntrEventFlag, SMAP_EVENT_XMIT);
         } else {
                 //No link. Clear the packet queue.
                 ClearPacketQueue(&SmapDriverData);
         }
         SetGP(OldGP);
 }
References ClearPacketQueue(), SmapDriverData::Dev9IntrEventFlag, iSetEventFlag(), SmapDriverData::LinkStatus, QueryIntrContext(), SetEventFlag(), SetGP(), SetModuleGP, and SMAP_EVENT_XMIT.
Referenced by SetupNetDev().