ps2sdk: iop/usb/usbhdfsd/src/include/mass_stor.h File Reference
mass_stor.h File Reference
Functions
int InitUSB (void)
int mass_stor_disconnect (int devId)
int mass_stor_connect (int devId)
int mass_stor_probe (int devId)
int mass_stor_readSector (mass_dev *dev, unsigned int sector, unsigned char *buffer, unsigned short int count)
int mass_stor_writeSector (mass_dev *dev, unsigned int sector, const unsigned char *buffer, unsigned short int count)
int mass_stor_configureNextDevice (void)
int mass_stor_stop_unit (mass_dev *dev)
void mass_store_stop_all (void)
Function Documentation
InitUSB()
int InitUSB (void)
Definition at line 1123 of file usb_driver.c.
 {
         int i;
         int ret = 0;
         for (i = 0; i < NUM_DEVICES; ++i)
         {
                 g_mass_device[i].status = 0;
                 g_mass_device[i].devId = -1;
         }
         driver.next             = NULL;
         driver.prev             = NULL;
         driver.name             = "mass-stor";
         driver.probe            = mass_stor_probe;
         driver.connect          = mass_stor_connect;
         driver.disconnect       = mass_stor_disconnect;
         ret = sceUsbdRegisterLdd(&driver);
         XPRINTF("USBHDFSD: registerDriver=%i \n", ret);
         if (ret < 0)
         {
                 printf("USBHDFSD: register driver failed! ret=%d\n", ret);
                 return(-1);
         }
         return(0);
 }
References sceUsbdLddOps::connect, mass_dev::devId, sceUsbdLddOps::disconnect, driver, g_mass_device, mass_stor_connect(), mass_stor_disconnect(), mass_stor_probe(), sceUsbdLddOps::name, sceUsbdLddOps::next, NULL, NUM_DEVICES, sceUsbdLddOps::prev, printf(), sceUsbdLddOps::probe, sceUsbdRegisterLdd(), mass_dev::status, and XPRINTF.
mass_stor_configureNextDevice()
int mass_stor_configureNextDevice (void)
Definition at line 1081 of file usb_driver.c.
 {
         int i;
         XPRINTF("USBHDFSD: configuring devices... \n");
         for (i = 0; i < NUM_DEVICES; ++i)
         {
                 mass_dev *dev = &g_mass_device[i];
                 if (dev->devId != -1 && (dev->status & USBMASS_DEV_STAT_CONN) && !(dev->status & USBMASS_DEV_STAT_CONF))
                 {
                         int ret;
                         ret = mass_store_configureDevice(dev);
                         if (ret != USB_RC_OK)
{
                                 mass_stor_release(dev);
                                 continue;
                         }
                         dev->status |= USBMASS_DEV_STAT_CONF;
                         ret = mass_stor_warmup(dev);
                         if (ret < 0)
{
                                 printf("USBHDFSD: Error - failed to warmup device %d\n", dev->devId);
                                 mass_stor_release(dev);
                                 continue;
                         }
                         dev->cache = scache_init(dev, dev->sectorSize); // modified by Hermes
                         if (dev->cache == NULL) {
                                 printf("USBHDFSD: Error - scache_init failed \n" );
                                 mass_stor_release(dev);
                                 continue;
                         }
                         return part_connect(dev) >= 0;
                 }
         }
         return 0;
 }
References mass_dev::devId, g_mass_device, mass_stor_release(), mass_stor_warmup(), mass_store_configureDevice(), NULL, NUM_DEVICES, part_connect(), printf(), scache_init(), mass_dev::status, USB_RC_OK, USBMASS_DEV_STAT_CONF, USBMASS_DEV_STAT_CONN, and XPRINTF.
Referenced by fat_getData().
mass_stor_connect()
int mass_stor_connect (int devId)
Definition at line 866 of file usb_driver.c.
 {
         int i;
         int epCount;
         UsbDeviceDescriptor *device;
         UsbConfigDescriptor *config;
         UsbInterfaceDescriptor *interface;
         UsbEndpointDescriptor *endpoint;
         iop_sema_t SemaData;
         mass_dev* dev;
         printf("USBHDFSD: connect: devId=%i\n", devId);
         dev = mass_stor_findDevice(devId, 1);
         if (dev == NULL) {
                 printf("USBHDFSD: Error - no free device descriptors!\n");
                 return 1;
         }
         /* Device cannot be registered twice. */
         if (dev->devId != -1) {
                 printf("USBHDFSD: Error - device descriptor in use!\n");
                 return 1;
         }
         dev->status = 0;
         dev->sectorSize = 0;
         dev->bulkEpI = -1;
         dev->bulkEpO = -1;
         /* open the config endpoint */
         dev->controlEp = sceUsbdOpenPipe(devId, NULL);
         device = (UsbDeviceDescriptor*)sceUsbdScanStaticDescriptor(devId, NULL, USB_DT_DEVICE);
         config = (UsbConfigDescriptor*)sceUsbdScanStaticDescriptor(devId, device, USB_DT_CONFIG);
         interface = (UsbInterfaceDescriptor *) ((char *) config + config->bLength); /* Get first interface */
         // store interface numbers
         dev->interfaceNumber = interface->bInterfaceNumber;
         dev->interfaceAlt    = interface->bAlternateSetting;
         epCount = interface->bNumEndpoints;
         endpoint = (UsbEndpointDescriptor*)sceUsbdScanStaticDescriptor(devId, NULL, USB_DT_ENDPOINT);
         usb_bulk_probeEndpoint(devId, dev, endpoint);
         for (i = 1; i < epCount; i++)
         {
                 endpoint = (UsbEndpointDescriptor*) ((char *) endpoint + endpoint->bLength);
                 usb_bulk_probeEndpoint(devId, dev, endpoint);
         }
         // Bail out if we do NOT have enough bulk endpoints.
         if (dev->bulkEpI < 0 || dev->bulkEpO < 0) {
                 mass_stor_release(dev);
                 printf("USBHDFSD: Error - connect failed: not enough bulk endpoints! \n");
                 return -1;
         }
         SemaData.initial = 0;
         SemaData.max = 1;
         SemaData.option = 0;
         SemaData.attr = 0;
         if((dev->ioSema = CreateSema(&SemaData)) <0){
                 mass_stor_release(dev);
                 printf("USBHDFSD: Failed to allocate I/O semaphore.\n");
                 return -1;
         }
         /*store current configuration id - can't call set_configuration here */
         dev->devId = devId;
         dev->configId = config->bConfigurationValue;
         dev->status = USBMASS_DEV_STAT_CONN;
         XPRINTF("USBHDFSD: connect ok: epI=%i, epO=%i \n", dev->bulkEpI, dev->bulkEpO);
         if(dev->callback != NULL) dev->callback(USBMASS_DEV_EV_CONN);
         return 0;
 }
References iop_sema_t::attr, UsbInterfaceDescriptor::bAlternateSetting, UsbConfigDescriptor::bConfigurationValue, UsbInterfaceDescriptor::bInterfaceNumber, UsbConfigDescriptor::bLength, UsbEndpointDescriptor::bLength, UsbInterfaceDescriptor::bNumEndpoints, mass_dev::bulkEpI, mass_dev::bulkEpO, mass_dev::configId, mass_dev::controlEp, CreateSema(), mass_dev::devId, iop_sema_t::initial, mass_dev::interfaceAlt, mass_dev::interfaceNumber, mass_dev::ioSema, mass_stor_findDevice(), mass_stor_release(), iop_sema_t::max, NULL, iop_sema_t::option, printf(), sceUsbdOpenPipe(), sceUsbdScanStaticDescriptor(), mass_dev::status, usb_bulk_probeEndpoint(), USB_DT_CONFIG, USB_DT_DEVICE, USB_DT_ENDPOINT, USBMASS_DEV_EV_CONN, USBMASS_DEV_STAT_CONN, and XPRINTF.
Referenced by InitUSB().
mass_stor_disconnect()
int mass_stor_disconnect (int devId)
Definition at line 966 of file usb_driver.c.
{
         mass_dev* dev;
         dev = mass_stor_findDevice(devId, 0);
         printf("USBHDFSD: disconnect: devId=%i\n", devId);
         if (dev == NULL)
         {
                 printf("USBHDFSD: Error - disconnect: no device storage!\n");
                 return 0;
         }
         if (dev->status & USBMASS_DEV_STAT_CONN)
         {
                 mass_stor_release(dev);
                 part_disconnect(dev);
                 scache_kill(dev->cache);
                 dev->cache = NULL;
                 dev->devId = -1;
                 DeleteSema(dev->ioSema);
                 if(dev->callback != NULL) dev->callback(USBMASS_DEV_EV_DISCONN);
         }
         return 0;
 }
References DeleteSema(), mass_dev::devId, mass_dev::ioSema, mass_stor_findDevice(), mass_stor_release(), NULL, part_disconnect(), printf(), scache_kill(), mass_dev::status, USBMASS_DEV_EV_DISCONN, and USBMASS_DEV_STAT_CONN.
Referenced by InitUSB().
mass_stor_probe()
int mass_stor_probe (int devId)
Definition at line 811 of file usb_driver.c.
 {
         UsbDeviceDescriptor *device = NULL;
         UsbConfigDescriptor *config = NULL;
         UsbInterfaceDescriptor *intf = NULL;
         XPRINTF("USBHDFSD: probe: devId=%i\n", devId);
         mass_dev* mass_device = mass_stor_findDevice(devId, 0);
         /* Check that a device descriptor was successfully allocated and the device was not already connected. */
         if ((mass_device != NULL) && (mass_device->status & USBMASS_DEV_STAT_CONN))
         {
                 printf("USBHDFSD: Error - no free device descriptors!\n");
                 return 0;
         }
         /* get device descriptor */
         device = (UsbDeviceDescriptor*)sceUsbdScanStaticDescriptor(devId, NULL, USB_DT_DEVICE);
         if (device == NULL)  {
                 printf("USBHDFSD: Error - Couldn't get device descriptor\n");
                 return 0;
         }
         /* Check if the device has at least one configuration */
         if (device->bNumConfigurations < 1) { return 0; }
         /* read configuration */
         config = (UsbConfigDescriptor*)sceUsbdScanStaticDescriptor(devId, device, USB_DT_CONFIG);
         if (config == NULL) {
             printf("USBHDFSD: Error - Couldn't get configuration descriptor\n");
             return 0;
         }
         /* check that at least one interface exists */
         XPRINTF("USBHDFSD: bNumInterfaces %d\n", config->bNumInterfaces);
         if ((config->bNumInterfaces < 1) ||
                 (config->wTotalLength < (sizeof(UsbConfigDescriptor) + sizeof(UsbInterfaceDescriptor)))) {
                         printf("USBHDFSD: Error - No interfaces available\n");
                         return 0;
         }
         /* get interface */
         intf = (UsbInterfaceDescriptor *) ((char *) config + config->bLength); /* Get first interface */
         XPRINTF("USBHDFSD: bInterfaceClass %X bInterfaceSubClass %X bInterfaceProtocol %X\n",
         intf->bInterfaceClass, intf->bInterfaceSubClass, intf->bInterfaceProtocol);
         if ((intf->bInterfaceClass              != USB_CLASS_MASS_STORAGE) ||
                 (intf->bInterfaceSubClass       != USB_SUBCLASS_MASS_SCSI  &&
                  intf->bInterfaceSubClass       != USB_SUBCLASS_MASS_SFF_8070I) ||
                 (intf->bInterfaceProtocol       != USB_PROTOCOL_MASS_BULK_ONLY) ||
                 (intf->bNumEndpoints < 2))    { //4.3: There shall be at least 2 endpoints, for bulk in and bulk out.
                         return 0;
         }
         return 1;
 }
References UsbInterfaceDescriptor::bInterfaceClass, UsbInterfaceDescriptor::bInterfaceProtocol, UsbInterfaceDescriptor::bInterfaceSubClass, UsbConfigDescriptor::bLength, UsbDeviceDescriptor::bNumConfigurations, UsbInterfaceDescriptor::bNumEndpoints, UsbConfigDescriptor::bNumInterfaces, mass_stor_findDevice(), NULL, printf(), sceUsbdScanStaticDescriptor(), mass_dev::status, USB_CLASS_MASS_STORAGE, USB_DT_CONFIG, USB_DT_DEVICE, USB_PROTOCOL_MASS_BULK_ONLY, USB_SUBCLASS_MASS_SCSI, USB_SUBCLASS_MASS_SFF_8070I, USBMASS_DEV_STAT_CONN, UsbConfigDescriptor::wTotalLength, and XPRINTF.
Referenced by InitUSB().
mass_stor_readSector()
int mass_stor_readSector (mass_dev * dev, unsigned int sector, unsigned char * buffer, unsigned short int count)
Definition at line 763 of file usb_driver.c.
 {
         int retries;
         for(retries = USB_IO_MAX_RETRIES; retries > 0; retries--)
         {
                 if(cbw_scsi_read_sector(dev, sector, buffer, count) == 0)
                         return 0;
         }
         return -EIO;
 }
References buffer, cbw_scsi_read_sector(), EIO, and USB_IO_MAX_RETRIES.
mass_stor_stop_unit()
int mass_stor_stop_unit (mass_dev * dev)
Definition at line 1186 of file usb_driver.c.
 {
         int stat;
         if ((stat = cbw_scsi_start_stop_unit(dev, 0)) != 0) {
                 printf("USBHDFSD: Error - cbw_scsi_start_stop_unit %d\n", stat);
         }
         return stat;
 }
References cbw_scsi_start_stop_unit(), and printf().
Referenced by fs_devctl(), and mass_store_stop_all().
mass_stor_writeSector()
int mass_stor_writeSector (mass_dev * dev, unsigned int sector, const unsigned char * buffer, unsigned short int count)
Definition at line 776 of file usb_driver.c.
 {
         int retries;
         for(retries = USB_IO_MAX_RETRIES; retries > 0; retries--)
         {
                 if(cbw_scsi_write_sector(dev, sector, buffer, count) == 0)
                         return 0;
         }
         return -EIO;
 }
References buffer, cbw_scsi_write_sector(), EIO, and USB_IO_MAX_RETRIES.
mass_store_stop_all()
void mass_store_stop_all (void)
Definition at line 1197 of file usb_driver.c.
 {
         int i;
         for (i = 0; i < NUM_DEVICES; ++i)
         {
                 mass_dev *dev = &g_mass_device[i];
                 if (dev->devId != -1 && (dev->status & USBMASS_DEV_STAT_CONN))
                 {
                         if(!(dev->status & USBMASS_DEV_STAT_CONF))
                         {       //Configure unconfigured devices, to be able to shut them down.
                                 if (mass_store_configureDevice(dev) != USB_RC_OK)
                                         continue;
                         }
                         mass_stor_stop_unit(dev);
                 }
         }
 }
References mass_dev::devId, g_mass_device, mass_stor_stop_unit(), mass_store_configureDevice(), NUM_DEVICES, mass_dev::status, USB_RC_OK, USBMASS_DEV_STAT_CONF, and USBMASS_DEV_STAT_CONN.
Referenced by fs_devctl().