ps2sdk: iop/memorycard/mcman/src/mcdev.c File Reference
mcdev.c File Reference
#include <mcman.h>
#include "mcman-internal.h"
Functions
int mc_init (iop_device_t *iop_dev)
int mc_deinit (iop_device_t *dev)
int mc_open (iop_file_t *f, char *filename, int mode, int flags)
int mc_close (iop_file_t *f)
int mc_lseek (iop_file_t *f, int pos, int where)
int mc_read (iop_file_t *f, void *buf, int size)
int mc_write (iop_file_t *f, void *buf, int size)
int mc_format (iop_file_t *f, char *a1, char *a2, void *a3, int a4)
int mc_remove (iop_file_t *f, char *filename)
int mc_mkdir (iop_file_t *f, char *dirname)
int mc_rmdir (iop_file_t *f, char *dirname)
int mc_dopen (iop_file_t *f, char *dirname)
int mc_dclose (iop_file_t *f)
int mc_dread (iop_file_t *f, io_dirent_t *dirent)
int mc_getstat (iop_file_t *f, char *filename, io_stat_t *stat)
int mc_chstat (iop_file_t *f, char *filename, io_stat_t *stat, u32 statmask)
int mc_ioctl (iop_file_t *f, int a1, void *a2)
int mcman_ioerrcode (int errcode)
int mcman_modloadcb (char *filename, int *port, int *slot)
void mcman_unit2card (u32 unit)
int mcman_initdev (void)
Variables
static int mcman_mc_port = 0
static int mcman_mc_slot = 0
static int mcman_io_sema = 0
void * mcman_mcops [17]
static iop_device_t mcman_mcdev
Function Documentation
mc_chstat()
int mc_chstat (iop_file_t * f, char * filename, io_stat_t * stat, u32 statmask)
Definition at line 417 of file mcdev.c.
 {
         register int r, flags;
         sceMcTblGetDir mctbl;
         WaitSema(mcman_io_sema);
         mcman_unit2card(f->unit);
         r = McDetectCard2(mcman_mc_port, mcman_mc_slot);
         if (r >= -1) {
                 if (statmask & SCE_CST_ATTR) {
                         flags = 0x008;
                         mctbl.Reserve2 = stat->attr;
                 }
                 else flags = 0x000;
                 if (statmask & SCE_CST_MODE) {
                         flags |= 0x200;
                         if (stat->mode & SCE_STM_R) mctbl.AttrFile |= sceMcFileAttrReadable;
                         else mctbl.AttrFile &= (unsigned short)~sceMcFileAttrReadable;
                         if (stat->mode & SCE_STM_W) mctbl.AttrFile |= sceMcFileAttrWriteable;
                         else mctbl.AttrFile &= (unsigned short)~sceMcFileAttrWriteable;
                         if (stat->mode & SCE_STM_X) mctbl.AttrFile |= sceMcFileAttrExecutable;
                         else mctbl.AttrFile &= (unsigned short)~sceMcFileAttrExecutable;
                         if (stat->mode & SCE_STM_C) mctbl.AttrFile |= sceMcFileAttrDupProhibit;
                         else mctbl.AttrFile &= (unsigned short)~sceMcFileAttrDupProhibit;
                         if (stat->mode & sceMcFileAttrPS1) mctbl.AttrFile |= sceMcFileAttrPS1;
                         else mctbl.AttrFile &= (unsigned short)~sceMcFileAttrPS1;
                         if (stat->mode & sceMcFileAttrPDAExec) mctbl.AttrFile |= sceMcFileAttrPDAExec;
                         else mctbl.AttrFile &= (unsigned short)~sceMcFileAttrPDAExec;
                 }
                 if (statmask & SCE_CST_CT) {
                         flags |= 0x001;
                         memcpy(&mctbl._Create, stat->ctime, sizeof(sceMcStDateTime));
                 }
                 if (statmask & SCE_CST_MT) {
                         flags |= 0x002;
                         memcpy(&mctbl._Modify, stat->mtime, sizeof(sceMcStDateTime));
                 }
                 r = McSetFileInfo(mcman_mc_port, mcman_mc_slot, filename, &mctbl, flags);
         }
         SignalSema(mcman_io_sema);
         return mcman_ioerrcode(r);
 }
References sceMcTblGetDir::_Create, sceMcTblGetDir::_Modify, io_stat_t::attr, sceMcTblGetDir::AttrFile, io_stat_t::ctime, McDetectCard2(), mcman_io_sema, mcman_ioerrcode(), mcman_mc_port, mcman_mc_slot, mcman_unit2card(), McSetFileInfo(), memcpy(), io_stat_t::mode, io_stat_t::mtime, sceMcTblGetDir::Reserve2, SCE_CST_ATTR, SCE_CST_CT, SCE_CST_MODE, SCE_CST_MT, SCE_STM_C, SCE_STM_R, SCE_STM_W, SCE_STM_X, sceMcFileAttrDupProhibit, sceMcFileAttrExecutable, sceMcFileAttrPDAExec, sceMcFileAttrPS1, sceMcFileAttrReadable, sceMcFileAttrWriteable, SignalSema(), iop_file_t::unit, and WaitSema().
mc_close()
int mc_close (iop_file_t * f)
Definition at line 239 of file mcdev.c.
 {
         register int r;
         WaitSema(mcman_io_sema);
         r = McClose((int)f->privdata);
         SignalSema(mcman_io_sema);
         return mcman_ioerrcode(r);
 }
References McClose(), mcman_io_sema, mcman_ioerrcode(), iop_file_t::privdata, SignalSema(), and WaitSema().
mc_dclose()
int mc_dclose (iop_file_t * f)
Definition at line 375 of file mcdev.c.
 {
         register int r;
         WaitSema(mcman_io_sema);
         r = McClose((int)f->privdata);
         SignalSema(mcman_io_sema);
         return mcman_ioerrcode(r);
 }
References McClose(), mcman_io_sema, mcman_ioerrcode(), iop_file_t::privdata, SignalSema(), and WaitSema().
mc_deinit()
int mc_deinit (iop_device_t * dev)
Definition at line 211 of file mcdev.c.
 {
         DeleteSema(mcman_io_sema);
         McCloseAll();
         return 0;
 }
References DeleteSema(), McCloseAll(), and mcman_io_sema.
mc_dopen()
int mc_dopen (iop_file_t * f, char * dirname)
Definition at line 355 of file mcdev.c.
 {
         register int r;
         WaitSema(mcman_io_sema);
         mcman_unit2card(f->unit);
         r = McDetectCard2(mcman_mc_port, mcman_mc_slot);
         if (r >= -1) {
                 r = McOpen(mcman_mc_port, mcman_mc_slot, dirname, 0);
                 if (r >= 0)
                         f->privdata = (void*)r;
         }
         SignalSema(mcman_io_sema);
         return mcman_ioerrcode(r);
 }
References McDetectCard2(), mcman_io_sema, mcman_ioerrcode(), mcman_mc_port, mcman_mc_slot, mcman_unit2card(), McOpen(), iop_file_t::privdata, SignalSema(), iop_file_t::unit, and WaitSema().
mc_dread()
int mc_dread (iop_file_t * f, io_dirent_t * dirent)
Definition at line 387 of file mcdev.c.
 {
         register int r;
         WaitSema(mcman_io_sema);
         r = mcman_dread((int)f->privdata, dirent);
         SignalSema(mcman_io_sema);
         return mcman_ioerrcode(r);
 }
References mcman_dread(), mcman_io_sema, mcman_ioerrcode(), iop_file_t::privdata, SignalSema(), and WaitSema().
mc_format()
int mc_format (iop_file_t * f, char * a1, char * a2, void * a3, int a4)
Definition at line 287 of file mcdev.c.
 {
         register int r;
         WaitSema(mcman_io_sema);
         mcman_unit2card(f->unit);
         r = McDetectCard2(mcman_mc_port, mcman_mc_slot);
         if (r >= -2) {
                 r = McFormat(mcman_mc_port, mcman_mc_slot);
         }
         SignalSema(mcman_io_sema);
         return mcman_ioerrcode(r);
 }
References McDetectCard2(), McFormat(), mcman_io_sema, mcman_ioerrcode(), mcman_mc_port, mcman_mc_slot, mcman_unit2card(), SignalSema(), iop_file_t::unit, and WaitSema().
mc_getstat()
int mc_getstat (iop_file_t * f, char * filename, io_stat_t * stat)
Definition at line 399 of file mcdev.c.
 {
         register int r;
         WaitSema(mcman_io_sema);
         mcman_unit2card(f->unit);
         r = McDetectCard2(mcman_mc_port, mcman_mc_slot);
         if (r >= -1) {
                 r = mcman_getstat(mcman_mc_port, mcman_mc_slot, filename, stat);
         }
         SignalSema(mcman_io_sema);
         return mcman_ioerrcode(r);
 }
References McDetectCard2(), mcman_getstat(), mcman_io_sema, mcman_ioerrcode(), mcman_mc_port, mcman_mc_slot, mcman_unit2card(), SignalSema(), iop_file_t::unit, and WaitSema().
mc_init()
int mc_init (iop_device_t * iop_dev)
Definition at line 69 of file mcdev.c.
 {
         return 0;
 }
mc_ioctl()
int mc_ioctl (iop_file_t * f, int a1, void * a2)
Definition at line 472 of file mcdev.c.
 {
         WaitSema(mcman_io_sema);
         return 0;
 }
References mcman_io_sema, and WaitSema().
mc_lseek()
int mc_lseek (iop_file_t * f, int pos, int where)
Definition at line 251 of file mcdev.c.
 {
         register int r;
         WaitSema(mcman_io_sema);
         r = McSeek((int)f->privdata, pos, where);
         SignalSema(mcman_io_sema);
         return mcman_ioerrcode(r);
 }
References mcman_io_sema, mcman_ioerrcode(), McSeek(), pos, iop_file_t::privdata, SignalSema(), and WaitSema().
mc_mkdir()
int mc_mkdir (iop_file_t * f, char * dirname)
Definition at line 321 of file mcdev.c.
 {
         register int r;
         WaitSema(mcman_io_sema);
         mcman_unit2card(f->unit);
         r = McDetectCard2(mcman_mc_port, mcman_mc_slot);
         if (r >= -1) {
                 r = McOpen(mcman_mc_port, mcman_mc_slot, dirname, 0x40);
         }
         SignalSema(mcman_io_sema);
         return mcman_ioerrcode(r);
 }
References McDetectCard2(), mcman_io_sema, mcman_ioerrcode(), mcman_mc_port, mcman_mc_slot, mcman_unit2card(), McOpen(), SignalSema(), iop_file_t::unit, and WaitSema().
mc_open()
int mc_open (iop_file_t * f, char * filename, int mode, int flags)
Definition at line 220 of file mcdev.c.
 {
         register int r;
         WaitSema(mcman_io_sema);
         mcman_unit2card(f->unit);
         r = McDetectCard2(mcman_mc_port, mcman_mc_slot);
         if (r >= -1) {
                 r = McOpen(mcman_mc_port, mcman_mc_slot, filename, mode);
                 if (r >= 0)
                         f->privdata = (void*)r;
         }
         SignalSema(mcman_io_sema);
         return mcman_ioerrcode(r);
 }
References McDetectCard2(), mcman_io_sema, mcman_ioerrcode(), mcman_mc_port, mcman_mc_slot, mcman_unit2card(), McOpen(), iop_file_t::privdata, SignalSema(), iop_file_t::unit, and WaitSema().
mc_read()
int mc_read (iop_file_t * f, void * buf, int size)
Definition at line 263 of file mcdev.c.
 {
         register int r;
         WaitSema(mcman_io_sema);
         r = McRead((int)f->privdata, buf, size);
         SignalSema(mcman_io_sema);
         return mcman_ioerrcode(r);
 }
References mcman_io_sema, mcman_ioerrcode(), McRead(), iop_file_t::privdata, SignalSema(), and WaitSema().
mc_remove()
int mc_remove (iop_file_t * f, char * filename)
Definition at line 304 of file mcdev.c.
 {
         register int r;
         WaitSema(mcman_io_sema);
         mcman_unit2card(f->unit);
         r = McDetectCard2(mcman_mc_port, mcman_mc_slot);
         if (r >= -1) {
                 r = McDelete(mcman_mc_port, mcman_mc_slot, filename, 0);
         }
         SignalSema(mcman_io_sema);
         return mcman_ioerrcode(r);
 }
References McDelete(), McDetectCard2(), mcman_io_sema, mcman_ioerrcode(), mcman_mc_port, mcman_mc_slot, mcman_unit2card(), SignalSema(), iop_file_t::unit, and WaitSema().
mc_rmdir()
int mc_rmdir (iop_file_t * f, char * dirname)
Definition at line 338 of file mcdev.c.
 {
         register int r;
         WaitSema(mcman_io_sema);
         mcman_unit2card(f->unit);
         r = McDetectCard2(mcman_mc_port, mcman_mc_slot);
         if (r >= -1) {
                 r = McDelete(mcman_mc_port, mcman_mc_slot, dirname, 0);
         }
         SignalSema(mcman_io_sema);
         return mcman_ioerrcode(r);
 }
References McDelete(), McDetectCard2(), mcman_io_sema, mcman_ioerrcode(), mcman_mc_port, mcman_mc_slot, mcman_unit2card(), SignalSema(), iop_file_t::unit, and WaitSema().
mc_write()
int mc_write (iop_file_t * f, void * buf, int size)
Definition at line 275 of file mcdev.c.
 {
         register int r;
         WaitSema(mcman_io_sema);
         r = McWrite((int)f->privdata, buf, size);
         SignalSema(mcman_io_sema);
         return mcman_ioerrcode(r);
 }
References mcman_io_sema, mcman_ioerrcode(), McWrite(), iop_file_t::privdata, SignalSema(), and WaitSema().
mcman_initdev()
int mcman_initdev (void)
Definition at line 189 of file mcdev.c.
 {
         iop_sema_t smp;
         SetCheckKelfPathCallback(mcman_modloadcb);
         DelDrv(mcman_mcdev.name);
         if (AddDrv(&mcman_mcdev)) {
                 McCloseAll();
                 return 1;
         }
         smp.attr = 1;
         smp.initial = 1;
         smp.max = 1;
         smp.option = 0;
         mcman_io_sema = CreateSema(&smp);
         return 0;
 }
References AddDrv(), iop_sema_t::attr, CreateSema(), DelDrv(), iop_sema_t::initial, iop_sema_t::max, McCloseAll(), mcman_io_sema, mcman_mcdev, mcman_modloadcb(), iop_device_t::name, iop_sema_t::option, and SetCheckKelfPathCallback().
Referenced by _start().
mcman_ioerrcode()
int mcman_ioerrcode (int errcode)
Definition at line 75 of file mcdev.c.
 {
         register int r = errcode;
         if (r < 0) {
                 switch (r + 8) {
                         case 0:
                                 r = -EIO;
                                 break;
                         case 1:
                                 r = -EMFILE;
                                 break;
                         case 2:
                                 r = -EEXIST;
                                 break;
                         case 3:
                                 r = -EACCES;
                                 break;
                         case 4:
                                 r = -ENOENT;
                                 break;
                         case 5:
                                 r = -ENOSPC;
                                 break;
                         case 6:
                                 r = -EFORMAT;
                                 break;
                         default:
                                 r = -ENXIO;
                                 break;
                 }
         }
         return r;
 }
References EACCES, EEXIST, EFORMAT, EIO, EMFILE, ENOENT, ENOSPC, and ENXIO.
Referenced by mc_chstat(), mc_close(), mc_dclose(), mc_dopen(), mc_dread(), mc_format(), mc_getstat(), mc_lseek(), mc_mkdir(), mc_open(), mc_read(), mc_remove(), mc_rmdir(), and mc_write().
mcman_modloadcb()
int mcman_modloadcb (char * filename, int * port, int * slot)
Definition at line 111 of file mcdev.c.
 {
         register char *path = filename;
         register int   upos;
         if (*path == 0x20) {
                 path++;
                 while (*path == 0x20)
                         path++;
         }
         if (((u8)path[0] | 0x20) != mcman_mcdev.name[0])
                 return 0;
         if (((u8)path[1] | 0x20) != mcman_mcdev.name[1])
                 return 0;
         if ((u32)strlen(path) < 2) return 2;
         upos = mcman_chrpos(path, ':');
         if (upos < 0)
                 upos = strlen(path);
         if (port) {
                 upos --;
                 if (((u8)path[upos] - 0x30) < 10)
                         *port = (u8)path[upos] - 0x30;
                 else *port = 0;
         }
         upos--;
         *port += 2;
         if (slot) {
                 register int m, v;
                 *slot = 0;
                 for (m = 1; ((u8)path[upos --] - 0x30) < 10; m = v << 1) {
                         v = m << 2;
                         *slot += m * (path[upos] - 0x30);
                         v += m;
                 }
         }
         return 1;
 }
References mcman_chrpos(), mcman_mcdev, iop_device_t::name, and strlen().
Referenced by mcman_initdev().
mcman_unit2card()
void mcman_unit2card (u32 unit)
Definition at line 159 of file mcdev.c.
 {
         mcman_mc_port = unit & 1;
         mcman_mc_slot = (unit >> 1) & (MCMAN_MAXSLOT - 1);
         // original mcman/xmcman code below is silly and I doubt it
         // can support more than 2 units anyway...
         /*
         register u32 mask = 0xF0000000;
         while (!(unit & mask)) {
                 mask >>= 4;
                 if (mask < 0x10)
                         break;
         }
         mcman_mc_port = unit & 0xf;
         mcman_mc_slot = 0;
         if (mask < 0xf) {
                 while (mask) {
                         mcman_mc_slot = ((u32)(unit & mask)) / ((u32)(mask & (mask >> 0x3))) \
                                 + (((mcman_mc_slot << 2) + mcman_mc_slot) << 1);
                         mask >>= 4;
                 }
         }
         */
 }
References MCMAN_MAXSLOT, mcman_mc_port, and mcman_mc_slot.
Referenced by mc_chstat(), mc_dopen(), mc_format(), mc_getstat(), mc_mkdir(), mc_open(), mc_remove(), and mc_rmdir().
Variable Documentation
mcman_io_sema
int mcman_io_sema = 0 static
Definition at line 17 of file mcdev.c.
Referenced by mc_chstat(), mc_close(), mc_dclose(), mc_deinit(), mc_dopen(), mc_dread(), mc_format(), mc_getstat(), mc_ioctl(), mc_lseek(), mc_mkdir(), mc_open(), mc_read(), mc_remove(), mc_rmdir(), mc_write(), and mcman_initdev().
mcman_mc_port
int mcman_mc_port = 0 static
Definition at line 15 of file mcdev.c.
Referenced by mc_chstat(), mc_dopen(), mc_format(), mc_getstat(), mc_mkdir(), mc_open(), mc_remove(), mc_rmdir(), and mcman_unit2card().
mcman_mc_slot
int mcman_mc_slot = 0 static
Definition at line 16 of file mcdev.c.
Referenced by mc_chstat(), mc_dopen(), mc_format(), mc_getstat(), mc_mkdir(), mc_open(), mc_remove(), mc_rmdir(), and mcman_unit2card().
mcman_mcdev
iop_device_t mcman_mcdev static
Initial value:
= {
        "mc",
        IOP_DT_FS,
        1,
        "Memory Card",
        (struct _iop_device_ops *)&mcman_mcops
}
Definition at line 60 of file mcdev.c.
Referenced by mcman_initdev(), and mcman_modloadcb().
mcman_mcops
void* mcman_mcops[17]
Initial value:
= {
        (void*)mc_init,
        (void*)mc_deinit,
        (void*)mc_format,
        (void*)mc_open,
        (void*)mc_close,
        (void*)mc_read,
        (void*)mc_write,
        (void*)mc_lseek,
        (void*)mc_ioctl,
        (void*)mc_remove,
        (void*)mc_mkdir,
        (void*)mc_rmdir,
        (void*)mc_dopen,
        (void*)mc_dclose,
        (void*)mc_dread,
        (void*)mc_getstat,
        (void*)mc_chstat
}
Definition at line 39 of file mcdev.c.