ps2sdk: iop/memorycard/mcman/src/mcman-internal.h File Reference
mcman-internal.h File Reference
#include <loadcore.h>
#include <intrman.h>
#include <sysclib.h>
#include <thbase.h>
#include <thsemap.h>
#include <timrman.h>
#include <modload.h>
#include <ioman.h>
#include <secrman.h>
#include <cdvdman.h>
#include <stdio.h>
#include <errno.h>
#include <io_common.h>
#include "sio2man_imports.h"
Data Structures
struct McCacheDir
struct McFatCluster
struct McFatCache
struct MC_FHANDLE
struct MCDevInfo
union mcman_pagebuf
union mcman_PS1PDApagebuf
Macros
#define DPRINTF(args...) printf(args)
#define MODNAME "mcman_cex"
#define MODVER 0x20b
#define CF_USE_ECC 0x01
#define CF_BAD_BLOCK 0x08
#define CF_ERASE_ZEROES 0x10
#define MCMAN_MAXSLOT 4
#define MCMAN_CLUSTERSIZE 1024
#define MCMAN_CLUSTERFATENTRIES 256
#define MAX_CACHEENTRY 0x24
#define MAX_CACHEDIRENTRY 0x3
#define MAX_FDHANDLES 3
Functions
int mcsio2_transfer (int port, int slot, sio2_transfer_data_t *sio2data)
int mcsio2_transfer2 (int port, int slot, sio2_transfer_data_t *sio2data)
void long_multiply (u32 v1, u32 v2, u32 *HI, u32 *LO)
int mcman_chrpos (char *str, int chr)
void mcman_wmemset (void *buf, int size, int value)
int mcman_calcEDC (void *buf, int size)
int mcman_checkpath (char *str)
int mcman_checkdirpath (char *str1, char *str2)
void mcman_invhandles (int port, int slot)
int McCloseAll (void)
int mcman_detectcard (int port, int slot)
int mcman_dread (int fd, io_dirent_t *dirent)
int mcman_getstat (int port, int slot, char *filename, io_stat_t *stat)
int mcman_getmcrtime (sceMcStDateTime *time)
void mcman_initPS2com (void)
void sio2packet_add (int port, int slot, int cmd, u8 *buf)
int mcman_eraseblock (int port, int slot, int block, void **pagebuf, void *eccbuf)
int mcman_readpage (int port, int slot, int page, void *buf, void *eccbuf)
int mcman_cardchanged (int port, int slot)
int mcman_resetauth (int port, int slot)
int mcman_probePS2Card2 (int port, int slot)
int mcman_probePS2Card (int port, int slot)
int secrman_mc_command (int port, int slot, sio2_transfer_data_t *sio2data)
int mcman_getcnum (int port, int slot)
int mcman_correctdata (void *buf, void *ecc)
int mcman_sparesize (int port, int slot)
int mcman_setdevspec (int port, int slot)
int mcman_reportBadBlocks (int port, int slot)
int mcman_setdevinfos (int port, int slot)
int mcman_format2 (int port, int slot)
int mcman_fatRseek (int fd)
int mcman_fatWseek (int fd)
int mcman_findfree2 (int port, int slot, int reserve)
int mcman_dread2 (int fd, io_dirent_t *dirent)
int mcman_getstat2 (int port, int slot, char *filename, io_stat_t *stat)
int mcman_setinfo2 (int port, int slot, char *filename, sceMcTblGetDir *info, int flags)
int mcman_read2 (int fd, void *buffer, int nbyte)
int mcman_write2 (int fd, void *buffer, int nbyte)
int mcman_close2 (int fd)
int mcman_getentspace (int port, int slot, char *dirname)
int mcman_cachedirentry (int port, int slot, char *filename, McCacheDir *pcacheDir, McFsEntry **pfse, int unknown_flag)
int mcman_getdirinfo (int port, int slot, McFsEntry *pfse, char *filename, McCacheDir *pcd, int unknown_flag)
int mcman_open2 (int port, int slot, char *filename, int flags)
int mcman_chdir (int port, int slot, char *newdir, char *currentdir)
int mcman_writecluster (int port, int slot, int cluster, int flag)
int mcman_getdir2 (int port, int slot, char *dirname, int flags, int maxent, sceMcTblGetDir *info)
int mcman_delete2 (int port, int slot, char *filename, int flags)
int mcman_checkBackupBlocks (int port, int slot)
int mcman_unformat2 (int port, int slot)
void mcman_initPS1PDAcom (void)
int mcman_probePS1Card2 (int port, int slot)
int mcman_probePS1Card (int port, int slot)
int mcman_probePDACard (int port, int slot)
int mcman_setPS1devinfos (int port, int slot)
int mcman_format1 (int port, int slot)
int mcman_open1 (int port, int slot, char *filename, int flags)
int mcman_read1 (int fd, void *buffer, int nbyte)
int mcman_write1 (int fd, void *buffer, int nbyte)
int mcman_getPS1direntry (int port, int slot, char *filename, McFsEntryPS1 **pfse, int flag)
int mcman_dread1 (int fd, io_dirent_t *dirent)
int mcman_getstat1 (int port, int slot, char *filename, io_stat_t *stat)
int mcman_setinfo1 (int port, int slot, char *filename, sceMcTblGetDir *info, int flags)
int mcman_getdir1 (int port, int slot, char *dirname, int flags, int maxent, sceMcTblGetDir *info)
int mcman_clearPS1direntry (int port, int slot, int cluster, int flags)
int mcman_delete1 (int port, int slot, char *filename, int flags)
int mcman_close1 (int fd)
int mcman_findfree1 (int port, int slot, int reserve)
int mcman_fatRseekPS1 (int fd)
int mcman_fatWseekPS1 (int fd)
int mcman_FNC8ca4 (int port, int slot, MC_FHANDLE *fh)
int mcman_PS1pagetest (int port, int slot, int page)
int mcman_unformat1 (int port, int slot)
int mcman_cachePS1dirs (int port, int slot)
int mcman_fillPS1backuparea (int port, int slot, int block)
void mcman_initcache (void)
int mcman_clearcache (int port, int slot)
McCacheEntry * mcman_getcacheentry (int port, int slot, int cluster)
void mcman_freecluster (int port, int slot, int cluster)
int mcman_getFATindex (int port, int slot, int num)
McCacheEntry * mcman_get1stcacheEntp (void)
void mcman_addcacheentry (McCacheEntry *mce)
int mcman_flushcacheentry (McCacheEntry *mce)
int mcman_readdirentryPS1 (int port, int slot, int cluster, McFsEntryPS1 **pfse)
int mcman_readclusterPS1 (int port, int slot, int cluster, McCacheEntry **pmce)
int mcman_replaceBackupBlock (int port, int slot, int block)
int mcman_fillbackupblock1 (int port, int slot, int block, void **pagedata, void *eccdata)
int mcman_clearsuperblock (int port, int slot)
int mcman_ioerrcode (int errcode)
int mcman_modloadcb (char *filename, int *port, int *slot)
void mcman_unit2card (u32 unit)
int mcman_initdev (void)
Macro Definition Documentation
CF_BAD_BLOCK
#define CF_BAD_BLOCK 0x08
Definition at line 49 of file mcman-internal.h.
CF_ERASE_ZEROES
#define CF_ERASE_ZEROES 0x10
Definition at line 50 of file mcman-internal.h.
CF_USE_ECC
#define CF_USE_ECC 0x01
Definition at line 48 of file mcman-internal.h.
DPRINTF
#define DPRINTF (args...) printf(args)
Definition at line 34 of file mcman-internal.h.
MAX_CACHEDIRENTRY
#define MAX_CACHEDIRENTRY 0x3
Definition at line 66 of file mcman-internal.h.
MAX_CACHEENTRY
#define MAX_CACHEENTRY 0x24
Definition at line 60 of file mcman-internal.h.
MAX_FDHANDLES
#define MAX_FDHANDLES 3
Definition at line 89 of file mcman-internal.h.
MCMAN_CLUSTERFATENTRIES
#define MCMAN_CLUSTERFATENTRIES 256
Definition at line 54 of file mcman-internal.h.
MCMAN_CLUSTERSIZE
#define MCMAN_CLUSTERSIZE 1024
Definition at line 53 of file mcman-internal.h.
MCMAN_MAXSLOT
#define MCMAN_MAXSLOT 4
Definition at line 52 of file mcman-internal.h.
MODNAME
#define MODNAME "mcman_cex"
Definition at line 37 of file mcman-internal.h.
MODVER
#define MODVER 0x20b
Definition at line 38 of file mcman-internal.h.
Function Documentation
long_multiply()
void long_multiply (u32 v1, u32 v2, u32 * HI, u32 * LO)
Definition at line 100 of file main.c.
 {
         register long a, b, c, d;
         register long x, y;
         a = (v1 >> 16) & 0xffff;
         b = v1 & 0xffff;
         c = (v2 >> 16) & 0xffff;
         d = v2 & 0xffff;
         *LO = b * d;
         x = a * d + c * b;
         y = ((*LO >> 16) & 0xffff) + x;
         *LO = (*LO & 0xffff) | ((y & 0xffff) << 16);
         *HI = (y >> 16) & 0xffff;
         *HI += a * c;
 }
References v1.
Referenced by mcman_format2(), mcman_probePS1Card(), mcman_probePS1Card2(), mcman_setdevinfos(), McReadPS1PDACard(), and McWritePS1PDACard().
McCloseAll()
int McCloseAll (void)
Definition at line 463 of file main.c.
 {
         register int fd = 0, rv = 0;
         do {
                 if (mcman_fdhandles[fd].status) {
                         register int rc;
                         rc = McClose(fd);
                         if (rc < rv)
                                 rv = rc;
                 }
                 fd++;
         } while (fd < MAX_FDHANDLES);
         return rv;
 }
Referenced by _start().
mcman_addcacheentry()
void mcman_addcacheentry (McCacheEntry * mce)
Definition at line 3285 of file main.c.
 {
         register int i;
         McCacheEntry **pmce = (McCacheEntry **)pmcman_mccache;
         i = MAX_CACHEENTRY - 1;
         if (i < 0)
                 goto lbl1;
         do {
                 if (pmce[i] == mce)
                         break;
         } while (--i >= 0);
         if (i != 0) {
 lbl1:
                 do {
                         pmce[i] = pmce[i-1];
                 } while (--i != 0);
         }
         pmce[0] = (McCacheEntry *)mce;
 }
References MAX_CACHEENTRY, and pmcman_mccache.
Referenced by mcman_fatWseek(), mcman_open2(), mcman_readclusterPS1(), and McReadCluster().
mcman_cachedirentry()
int mcman_cachedirentry (int port, int slot, char * filename, McCacheDir * pcacheDir, McFsEntry ** pfse, int unknown_flag)
Definition at line 1777 of file main.c.
 {
         register int r, fsindex, cluster, fmode;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         McFsEntry *fse;
         McCacheDir cacheDir;
         u8 *pfsentry, *pcache, *pfseend;
         char *p;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_cachedirentry port%d slot%d name %s\n", port, slot, filename);
 #endif
         if (pcacheDir == NULL) {
                 pcacheDir = &cacheDir;
                 pcacheDir->maxent = -1;
         }
         p = filename;
         if (*p == '/') {
                 p++;
                 cluster = 0;
                 fsindex = 0;
         }
         else {
                 cluster = mcdi->rootdir_cluster2;
                 fsindex = mcdi->unknown1;
         }
         r = McReadDirEntry(port, slot, cluster, fsindex, &fse);
         if (r != sceMcResSucceed)
                 return r;
         if (*p == 0) {
                 if (!(fse->mode & sceMcFileAttrExists))
                         return 2;
                 if (pcacheDir == NULL) {
                         *pfse = (McFsEntry *)fse;
                         return sceMcResSucceed;
                 }
                 pfsentry = (u8 *)fse;
                 pcache = (u8 *)&mcman_dircache[0];
                 pfseend = (u8 *)(pfsentry + sizeof (McFsEntry));
                 do {
                         *((u32 *)pcache  ) = *((u32 *)pfsentry  );
                         *((u32 *)pcache+1) = *((u32 *)pfsentry+1);
                         *((u32 *)pcache+2) = *((u32 *)pfsentry+2);
                         *((u32 *)pcache+3) = *((u32 *)pfsentry+3);
                         pfsentry += 16;
                         pcache += 16;
                 } while (pfsentry < pfseend);
                 r = mcman_getdirinfo(port, slot, (McFsEntry *)&mcman_dircache[0], ".", pcacheDir, unknown_flag);
                 McReadDirEntry(port, slot, pcacheDir->cluster, pcacheDir->fsindex, pfse);
                 if (r > 0)
                         return 2;
                 return r;
         } else {
                 do {
                         fmode = sceMcFileAttrReadable | sceMcFileAttrExecutable;
                         if ((fse->mode & fmode) != fmode)
                                 return sceMcResDeniedPermit;
                         if (mcman_chrpos(p, '/') < 0)
                                 strlen(p);
                         pfsentry = (u8 *)fse;
                         pcache = (u8 *)&mcman_dircache[0];
                         pfseend = (u8 *)(pfsentry + sizeof(McFsEntry));
                         do {
                                 *((u32 *)pcache  ) = *((u32 *)pfsentry  );
                                 *((u32 *)pcache+1) = *((u32 *)pfsentry+1);
                                 *((u32 *)pcache+2) = *((u32 *)pfsentry+2);
                                 *((u32 *)pcache+3) = *((u32 *)pfsentry+3);
                                 pfsentry += 16;
                                 pcache += 16;
                         } while (pfsentry < pfseend);
                         r = mcman_getdirinfo(port, slot, (McFsEntry *)&mcman_dircache[0], p, pcacheDir, unknown_flag);
                         if (r > 0) {
                                 if (mcman_chrpos(p, '/') >= 0)
                                         return 2;
                                 pcacheDir->cluster = cluster;
                                 pcacheDir->fsindex = fsindex;
                                 return 1;
                         }
                         r = mcman_chrpos(p, '/');
                         if ((r >= 0) && (p[r + 1] != 0)) {
                                 p += mcman_chrpos(p, '/') + 1;
                                 cluster = pcacheDir->cluster;
                                 fsindex = pcacheDir->fsindex;
                                 McReadDirEntry(port, slot, cluster, fsindex, &fse);
                         }
                         else {
                                 McReadDirEntry(port, slot, pcacheDir->cluster, pcacheDir->fsindex, pfse);
                                 return sceMcResSucceed;
                         }
                 } while (*p != 0);
         }
         return sceMcResSucceed;
 }
References McCacheDir::cluster, DPRINTF, McCacheDir::fsindex, McCacheDir::maxent, mcman_chrpos(), mcman_devinfos, mcman_dircache, mcman_getdirinfo(), McReadDirEntry(), McFsEntry::mode, NULL, MCDevInfo::rootdir_cluster2, sceMcFileAttrExecutable, sceMcFileAttrExists, sceMcFileAttrReadable, sceMcResDeniedPermit, sceMcResSucceed, strlen(), and MCDevInfo::unknown1.
Referenced by mcman_chdir(), mcman_delete2(), mcman_getdir2(), mcman_getentspace(), mcman_getstat2(), mcman_open2(), and mcman_setinfo2().
mcman_cachePS1dirs()
int mcman_cachePS1dirs (int port, int slot)
<– Special fix for saves from a real PS1
Definition at line 2979 of file main.c.
 {
         register int r, i, j, temp1, temp2, index, linked_block;
         McFsEntryPS1 *fs_t[15];
         McCacheEntry *mce[2];
         int cluster_t[15];
 #ifdef DEBUG
         DPRINTF("mcman: mcman_cachePS1dirs port%d slot%d\n", port, slot);
 #endif
         i = 0;
         do {
                 r = mcman_readdirentryPS1(port, slot, i, &fs_t[i]);
                 if (r != sceMcResSucceed)
                         return r;
                 fs_t[i]->field_38 = fs_t[i]->length;
                 if (i == 0) {
                         mce[0] = mcman_get1stcacheEntp();
                 }
                 else {
                         if (i == 7)
                                 mce[1] = mcman_get1stcacheEntp();
                 }
         } while (++i < 15);
         memset((void *)cluster_t, -1, sizeof(cluster_t));
         i = 0;
         do {
                 temp1 = fs_t[i]->mode & 0xf0;
                 if ((fs_t[i]->mode & 0xf) != 1)
                         continue;
                 cluster_t[i] = i;
                 linked_block = fs_t[i]->linked_block;
                 if (linked_block >= 0) {
                         do {
                                 if ((fs_t[linked_block]->mode & 0xf0) != temp1)
                                         temp1 = 0;
                                 if (fs_t[linked_block]->mode == 0xa0)
                                         break;
                                 if (cluster_t[linked_block] != -1)
                                         break;
                                 cluster_t[linked_block] = i;
                                 linked_block = fs_t[linked_block]->linked_block;
                         } while (linked_block >= 0);
                         if ((linked_block < 0) && (temp1 != 0))
                                 continue;
                 }
                 else {
                         if (temp1 != 0)
                                 continue;
                 }
                 j = 0;
                 do {
                         if (cluster_t[j] != i)
                                 continue;
                         memset((void *)fs_t[j], 0, sizeof (McFsEntryPS1));
                         fs_t[j]->mode = 0xa0;
                         fs_t[j]->linked_block = -1;
                         fs_t[j]->edc = mcman_calcEDC((void *)fs_t[j], 127);
                         temp2 = j + 1;
                         if (j < 7)
                                 index = 0;
                         else
                                 index = 1;
                         if (temp2 < 0)
                                 temp1 = j + 8;
                         else
                                 temp1 = temp2;
                         mce[index]->wr_flag |= (1 << (temp2 - ((temp1 >> 3) << 3)));
                 } while (++j < 15);
         } while (++i < 15);
         i = 0;
         do {
                 if ((cluster_t[i] != -1) || (fs_t[i]->mode == 0xa0))
                         continue;
                 memset((void *)fs_t[i], 0, sizeof (McFsEntryPS1));
                 fs_t[i]->mode = 0xa0;
                 fs_t[i]->linked_block = cluster_t[i];
                 fs_t[i]->edc = mcman_calcEDC((void *)fs_t[i], 127);
                 temp2 = i + 1;
                 if (i < 7)
                         index = 0;
                 else
                         index = 1;
                 if (temp2 < 0)
                         temp1 = i + 8;
                 else
                         temp1 = temp2;
                 mce[index]->wr_flag |= (1 << (temp2 - ((temp1 >> 3) << 3)));
         } while (++i < 15);
         return sceMcResSucceed;
 }
References DPRINTF, McFsEntryPS1::edc, McFsEntryPS1::field_38, index(), McFsEntryPS1::length, McFsEntryPS1::linked_block, mcman_calcEDC(), mcman_get1stcacheEntp(), mcman_readdirentryPS1(), memset(), McFsEntryPS1::mode, sceMcResSucceed, and McCacheEntry::wr_flag.
Referenced by mcman_setPS1devinfos().
mcman_calcEDC()
int mcman_calcEDC (void * buf, int size)
Definition at line 357 of file main.c.
 {
         register u32 checksum;
         register int i;
         u8 *p = (u8 *)buf;
         checksum = 0;
         if (size > 0) {
                 size--;
                 i = 0;
                 while (size-- != -1) {
                         checksum ^= p[i];
                         i++;
                 }
         }
         return checksum & 0xff;
 }
Referenced by McGetCardSpec(), mcman_cachePS1dirs(), mcman_clearPS1direntry(), mcman_close1(), mcman_fillPS1backuparea(), mcman_FNC8ca4(), mcman_format1(), mcman_open1(), mcman_readpage(), mcman_setPS1devinfos(), McReadPS1PDACard(), McWritePS1PDACard(), sio2packet_add_ecc_in(), sio2packet_add_pagedata_in(), and sio2packet_add_wdma_u32().
mcman_cardchanged()
int mcman_cardchanged (int port, int slot)
Definition at line 344 of file mcsio2.c.
 {
         register int retries;
         u8 *p = mcman_sio2packet.out_dma.addr;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_cardchanged sio2cmd port%d slot%d\n", port, slot);
 #endif
         sio2packet_add(port, slot, 0xffffffff, NULL);
         sio2packet_add(port, slot, 0, NULL);
         sio2packet_add(port, slot, 0xfffffffe, NULL);
         retries = 0;
         do {
                 mcman_sio2transfer(port, slot, &mcman_sio2packet);
                 if (((mcman_sio2packet.stat6c & 0xF000) == 0x1000) && (p[3] != 0x66))
                         break;
         } while (++retries < 5);
         if (retries >= 5) {
 #ifdef DEBUG
                 DPRINTF("mcman: mcman_cardchanged sio2cmd card changed!\n");
 #endif
                 return sceMcResChangedCard;
         }
 #ifdef DEBUG
         DPRINTF("mcman: mcman_cardchanged sio2cmd succeeded\n");
 #endif
         return sceMcResSucceed;
 }
References _sio2_dma_arg::addr, DPRINTF, mcman_sio2packet, mcman_sio2transfer, NULL, sio2_transfer_data_t::out_dma, sceMcResChangedCard, sceMcResSucceed, sio2packet_add(), and sio2_transfer_data_t::stat6c.
Referenced by mcman_probePS2Card(), mcman_readpage(), and McWritePage().
mcman_chdir()
int mcman_chdir (int port, int slot, char * newdir, char * currentdir)
Definition at line 1044 of file ps2mc_fio.c.
 {
         register int r, len, len2, cluster;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         McCacheDir cacheDir;
         McFsEntry *fse;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_chdir port%d slot%d newdir %s\n", port, slot, newdir);
 #endif
         //if (!mcman_checkpath(newdir))
         //      return sceMcResNoEntry;
         cacheDir.maxent = -1;
         r = mcman_cachedirentry(port, slot, newdir, &cacheDir, &fse, 1);
         if (r < 0)
                 return r;
         if (((u32)(r - 1)) < 2)
                 return sceMcResNoEntry;
         mcdi->rootdir_cluster2 = cacheDir.cluster;
         mcdi->unknown1 = cacheDir.fsindex;
         cluster = cacheDir.cluster;
         if (!strcmp(fse->name, "..")) {
                 r = McReadDirEntry(port, slot, cluster, 0, &fse);
                 if (r != sceMcResSucceed)
                         return r;
         }
         if (!strcmp(fse->name, ".")) {
                 mcdi->rootdir_cluster2 = fse->cluster;
                 mcdi->unknown1 = fse->dir_entry;
                 cluster = fse->cluster;
                 r = McReadDirEntry(port, slot, cluster, fse->dir_entry, &fse);
                 if (r != sceMcResSucceed)
                         return r;
         }
         currentdir[0] = 0;
 lbl1:
         if (strcmp(fse->name, ".")) {
                 if (strlen(fse->name) < 32)
                         len = strlen(fse->name);
                 else
                         len = 32;
                 if (strlen(currentdir)) {
                         len2 = strlen(currentdir);
                         if (len2 >= 0) {
                                 do {
                                         currentdir[1 + len2 + len] = currentdir[len2];
                                 } while (--len2 >= 0);
                         }
                         currentdir[len] = '/';
                         strncpy(currentdir, fse->name, len);
                 }
                 else {
                         strncpy(currentdir, fse->name, 32);
                         currentdir[32] = 0;
                 }
                 r = McReadDirEntry(port, slot, cluster, 0, &fse);
                 if (r != sceMcResSucceed)
                         return r;
                 r = McReadDirEntry(port, slot, fse->cluster, fse->dir_entry, &fse);
                 if (r == sceMcResSucceed)
                         goto lbl1;
                 return r;
         }
         else {
                 strlen(fse->name);
                 len = strlen(currentdir);
                 if (len >= 0) {
                         do {
                                 currentdir[1 + len] = currentdir[len];
                         } while (--len >= 0);
                 }
                 currentdir[0] = '/';
                 r = sceMcResSucceed;
         }
         return sceMcResSucceed;
 }
References McFsEntry::cluster, McCacheDir::cluster, McFsEntry::dir_entry, DPRINTF, McCacheDir::fsindex, McCacheDir::maxent, mcman_cachedirentry(), mcman_devinfos, McReadDirEntry(), McFsEntry::name, MCDevInfo::rootdir_cluster2, sceMcResNoEntry, sceMcResSucceed, strcmp(), strlen(), strncpy(), and MCDevInfo::unknown1.
Referenced by McChDir().
mcman_checkBackupBlocks()
int mcman_checkBackupBlocks (int port, int slot)
Definition at line 2249 of file main.c.
 {
         register int r1, r2, r, eccsize;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         McCacheEntry *mce;
         u32 *pagebuf = mcman_pagebuf.word;
         u32 value1, value2;
         // First check backup block2 to see if it's in erased state
         r1 = McReadPage(port, slot, mcdi->backup_block2 * mcdi->blocksize, &mcman_pagebuf); //s1
         value1 = *pagebuf; //s3
         if (((mcdi->cardflags & CF_ERASE_ZEROES) != 0) && (value1 == 0))
                 value1 = 0xffffffff;
         if (value1 != 0xffffffff)
                 value1 = value1 & 0x7fffffff;
         r2 = McReadPage(port, slot, (mcdi->backup_block2 * mcdi->blocksize) + 1, &mcman_pagebuf); //a0
         value2 = *pagebuf; //s0
         if (((mcdi->cardflags & CF_ERASE_ZEROES) != 0) && (value2 == 0))
                 value2 = 0xffffffff;
         if (value2 != 0xffffffff)
                 value2 = value2 & 0x7fffffff;
         if ((value1 != 0xffffffff) && (value2 == 0xffffffff))
                 goto check_done;
         if ((r1 < 0) || (r2 < 0))
                 goto check_done;
         if ((value1 == 0xffffffff) && (value1 == value2))
                 return sceMcResSucceed;
         // bachup block2 is not erased, so programming is assumed to have not been completed
         // reads content of backup block1
         for (r1 = 0; r1 < mcdi->clusters_per_block; r1++) {
                 McReadCluster(port, slot, (mcdi->backup_block1 * mcdi->clusters_per_block) + r1, &mce);
                 mce->rd_flag = 1;
                 for (r2 = 0; r2 < mcdi->pages_per_cluster; r2++) {
                         mcman_pagedata[(r1 * ((mcdi->pages_per_cluster << 16) >> 16)) + r2] = \
                                 (void *)(mce->cl_data + (r2 * mcdi->pagesize));
                 }
         }
         // Erase the block where data must be written
         r = mcman_eraseblock(port, slot, value1, (void **)mcman_pagedata, (void *)mcman_eccdata);
         if (r != sceMcResSucceed)
                 return r;
         // Write the block
         for (r1 = 0; r1 < mcdi->blocksize; r1++) {
                 eccsize = mcdi->pagesize;
                 if (eccsize < 0)
                         eccsize += 0x1f;
                 eccsize = eccsize >> 5;
                 r = McWritePage(port, slot, (value1 * ((mcdi->blocksize << 16) >> 16)) + r1, \
                         mcman_pagedata[r1], (void *)(mcman_eccdata + (eccsize * r1)));
                 if (r != sceMcResSucceed)
                         return r;
         }
         for (r1 = 0; r1 < mcdi->clusters_per_block; r1++)
                 mcman_freecluster(port, slot, (mcdi->backup_block1 * mcdi->clusters_per_block) + r1);
 check_done:
         // Finally erase backup block2
         return mcman_eraseblock(port, slot, mcdi->backup_block2, NULL, NULL);
 }
References MCDevInfo::backup_block1, MCDevInfo::backup_block2, MCDevInfo::blocksize, MCDevInfo::cardflags, CF_ERASE_ZEROES, McCacheEntry::cl_data, MCDevInfo::clusters_per_block, mcman_devinfos, mcman_eccdata, mcman_eraseblock(), mcman_freecluster(), mcman_pagedata, McReadCluster(), McReadPage(), McWritePage(), NULL, MCDevInfo::pages_per_cluster, MCDevInfo::pagesize, McCacheEntry::rd_flag, sceMcResSucceed, and mcman_pagebuf::word.
Referenced by mcman_setdevinfos().
mcman_checkdirpath()
int mcman_checkdirpath (char * str1, char * str2)
Definition at line 394 of file main.c.
 {
         register int r, pos1, pos2, pos;
         char *p1 = str1;
         char *p2 = str2;
         do {
                 pos1 = mcman_chrpos(p2, '?');
                 pos2 = mcman_chrpos(p2, '*');
                 if ((pos1 < 0) && (pos2 < 0)) {
                         if (!strcmp(p2, p1))
                                 return 1;
                         return 0;
                 }
                 pos = pos2;
                 if (pos1 >= 0) {
                         pos = pos1;
                         if (pos2 >= 0) {
                                 pos = pos2;
                                 if (pos1 < pos2) {
                                         pos = pos1;
                                 }
                         }
                 }
                 if (strncmp(p2, p1, pos) != 0)
                         return 0;
                 p2 += pos;
                 p1 += pos;
                 while (p2[0] == '?') {
                         if (p1[0] == 0)
                                 return 1;
                         p2++;
                         p1++;
                 }
         } while (p2[0] != '*');
         while((p2[0] == '*') || (p2[0] == '?'))
                 p2++;
         if (p2[0] != 0) {
                 do {
                         pos = mcman_chrpos(p1, (u8)p2[0]);
                         p1 += pos;
                         if (pos < 0)
                                 return 0;
                         r = mcman_checkdirpath(p1, p2);
                         p1++;
                 } while (r == 0);
         }
         return 1;
 }
References mcman_chrpos(), pos, strcmp(), and strncmp().
Referenced by mcman_getdir1(), and mcman_getdir2().
mcman_checkpath()
int mcman_checkpath (char * str)
Definition at line 377 of file main.c.
 {
         register int i;
         u8 *p = (u8 *)str;
         i = 0;
         while (p[i]) {
                 if (((p[i] & 0xff) == '?') || ((p[i] & 0xff) == '*'))
                         return 0;
                 if ((p[i] & 0xff) < 32)
                         return 0;
                 i++;
         }
         return 1;
 }
mcman_chrpos()
int mcman_chrpos (char * str, int chr)
Definition at line 121 of file main.c.
 {
         char *p;
         p = str;
         if (*str) {
                 do {
                         if (*p == (chr & 0xff))
                                 break;
                         p++;
                 } while (*p);
         }
         if (*p != (chr & 0xff))
                 return -1;
         return p - str;
 }
Referenced by mcman_cachedirentry(), mcman_checkdirpath(), mcman_getdir1(), mcman_getdir2(), mcman_getdirinfo(), mcman_modloadcb(), mcman_open2(), and mcman_setinfo2().
mcman_clearcache()
int mcman_clearcache (int port, int slot)
Definition at line 3188 of file main.c.
 {
         register int i, j;
         McCacheEntry **pmce = (McCacheEntry **)pmcman_mccache;
         McCacheEntry *mce, *mce_save;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_clearcache port%d, slot%d\n", port, slot);
 #endif
         for (i = MAX_CACHEENTRY - 1; i >= 0; i--) {
                 mce = (McCacheEntry *)pmce[i];
                 if ((mce->mc_port == port) && (mce->mc_slot == slot) && (mce->cluster >= 0)) {
                         mce->mc_port = -1;
                         mce->mc_slot = -1;
                         mce->wr_flag = 0;
                         mce->cluster = -1;
                 }
         }
         for (i = 0; i < (MAX_CACHEENTRY - 1); i++) {
                 mce = (McCacheEntry *)pmce[i];
                 mce_save = (McCacheEntry *)pmce[i];
                 if (mce->cluster < 0) {
                         for (j = i+1; j < MAX_CACHEENTRY; j++) {
                                 mce = (McCacheEntry *)pmce[j];
                                 if (mce->cluster >= 0)
                                         break;
                         }
                         if (j == MAX_CACHEENTRY)
                                 break;
                         pmce[i] = (McCacheEntry *)pmce[j];
                         pmce[j] = (McCacheEntry *)mce_save;
                 }
         }
         memset((void *)&mcman_fatcache[port][slot], -1, sizeof (McFatCache));
         mcman_fatcache[port][slot].entry[0] = 0;
         return sceMcResSucceed;
 }
References McCacheEntry::cluster, DPRINTF, McFatCache::entry, MAX_CACHEENTRY, McCacheEntry::mc_port, McCacheEntry::mc_slot, mcman_fatcache, memset(), pmcman_mccache, sceMcResSucceed, and McCacheEntry::wr_flag.
Referenced by McChDir(), McClose(), McDelete(), McDetectCard2(), McFlush(), McFormat(), McGetDir(), McGetEntSpace(), mcman_detectcard(), mcman_dread(), mcman_getstat(), mcman_probePS1Card(), mcman_probePS2Card(), McOpen(), McRead(), McReplaceBadBlock(), McSetFileInfo(), McUnformat(), and McWrite().
mcman_clearPS1direntry()
int mcman_clearPS1direntry (int port, int slot, int cluster, int flags)
Definition at line 2593 of file main.c.
 {
         register int r, i, temp;
         McFsEntryPS1 *fse;
         MC_FHANDLE *fh;
         McCacheEntry *mce;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_clearPS1direntry port%d slot%d cluster %x flags %x\n", port, slot, cluster, flags);
 #endif
         r = mcman_readdirentryPS1(port, slot, cluster, &fse);
         if (r != sceMcResSucceed)
                 return r;
         fh = (MC_FHANDLE *)&mcman_fdhandles[0];
         for (i = 0; i < MAX_FDHANDLES; i++) {
                 if ((fh->status != 0) && (fh->port == port) && (fh->slot == slot)) {
                         if (fh->freeclink == cluster)
                                 return sceMcResDeniedPermit;
                 }
                 fh++;
         }
         if (!flags) {
                 if (fse->mode != 0x51)
                         return sceMcResNoEntry;
         }
         else {
                 if (fse->mode != 0xa1)
                         return sceMcResNoEntry;
         }
         do {
 lbl0:
                 mce = mcman_get1stcacheEntp();
                 if (cluster + 1 < 0)
                         temp = cluster + 8;
                 else
                         temp = cluster + 1;
                 mce->wr_flag |= 1 << ((cluster + 1) - ((temp >> 3) << 3));
                 if (flags == 0)
                         temp = (fse->mode & 0xf) | 0xa0;
                 else
                         temp = (fse->mode & 0xf) | 0x50;
                 fse->mode = temp;
                 fse->edc = mcman_calcEDC((void *)fse, 127);
                 if (fse->linked_block < 0) {
                         //cluster = 0;
                         goto lbl1;
                 }
                 cluster = fse->linked_block;
                 r = mcman_readdirentryPS1(port, slot, cluster, &fse);
                 if (r != sceMcResSucceed)
                         return r;
                 if (flags == 0) {
                         if ((fse->mode & 0xf0) != 0x50)
                                 break;
                         goto lbl0;
                 }
         } while ((fse->mode & 0xf0) == 0xa0);
         r = McFlushCache(port, slot);
         if (r != sceMcResSucceed)
                 return r;
         return sceMcResNoEntry;
 lbl1:
         r = McFlushCache(port, slot);
         if (r != sceMcResSucceed)
                 return r;
         return sceMcResSucceed;
 }
References DPRINTF, McFsEntryPS1::edc, MC_FHANDLE::freeclink, MAX_FDHANDLES, McFlushCache(), mcman_calcEDC(), mcman_fdhandles, mcman_get1stcacheEntp(), mcman_readdirentryPS1(), McFsEntryPS1::mode, MC_FHANDLE::port, sceMcResDeniedPermit, sceMcResNoEntry, sceMcResSucceed, MC_FHANDLE::slot, MC_FHANDLE::status, and McCacheEntry::wr_flag.
Referenced by mcman_delete1(), and mcman_open1().
mcman_clearsuperblock()
int mcman_clearsuperblock (int port, int slot)
Definition at line 4292 of file main.c.
 {
         register int r, i, size, temp;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         McCacheEntry *mce;
         // set superblock magic & version
         memset((void *)mcdi->magic, 0, sizeof (mcdi->magic) + sizeof (mcdi->version));
         strcpy(mcdi->magic, SUPERBLOCK_MAGIC);
         strcat(mcdi->magic, SUPERBLOCK_VERSION);
         for (i = 0; (u32)(i < sizeof(MCDevInfo)); i += 1024) {
                 temp = i;
                 if (i < 0)
                         temp = i + 1023;
                 r = McReadCluster(port, slot, temp >> 10, &mce);
                 if (r != sceMcResSucceed)
                         return -48;
                 mce->wr_flag = 1;
                 size = 1024;
                 temp = sizeof(MCDevInfo) - i;
                 if (temp <= 1024)
                         size = temp;
                 memcpy((void *)mce->cl_data, (void *)mcdi, size);
         }
         r = McFlushCache(port, slot);
         return r;
 }
References McCacheEntry::cl_data, MCDevInfo::magic, McFlushCache(), mcman_devinfos, McReadCluster(), memcpy(), memset(), sceMcResSucceed, strcat(), strcpy(), SUPERBLOCK_MAGIC, SUPERBLOCK_VERSION, MCDevInfo::version, and McCacheEntry::wr_flag.
Referenced by McReplaceBadBlock().
mcman_close1()
int mcman_close1 (int fd)
Definition at line 644 of file ps1mc_fio.c.
 {
         register int r, temp;
         MC_FHANDLE *fh = (MC_FHANDLE *)&mcman_fdhandles[fd];
         McFsEntryPS1 *fse;
         McCacheEntry *mce;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_close1 fd %d\n", fd);
 #endif
         r = mcman_readdirentryPS1(fh->port, fh->slot, fh->freeclink, &fse);
         if (r != sceMcResSucceed)
                 return -31;
         mce = mcman_get1stcacheEntp();
         if (fh->freeclink + 1 < 0)
                 temp = fh->freeclink + 8;
         else
                 temp = fh->freeclink + 1;
         mce->wr_flag |= 1 << ((fh->freeclink + 1) - ((temp >> 3) << 3));
         if (fh->filesize == 0) {
                 fse->length = 0x2000;
         }
         else {
                 if ((fh->filesize - 1) < 0)
                         temp = (fh->filesize + 8190) >> 13;
                 else
                         temp = (fh->filesize - 1) >> 13;
                 temp++;
                 fse->length = temp << 13;
         }
         if (sio2man_type >= XSIO2MAN) {
                 fse->field_7d = 0; // <--- To preserve for XMCMAN
                 fse->field_2c = 0; //
                 fse->field_38 = 0; //
                 memset((void *)&fse->created, 0, 8);  //
                 memset((void *)&fse->modified, 0, 8); //
         }
         else { // MCMAN does as following
                 fse->field_7d = 1;
                 fse->field_38 = fh->filesize;
                 mcman_getmcrtime(&fse->modified);
         }
         fse->edc = mcman_calcEDC((void *)fse, 127);
         r = McFlushCache(fh->port, fh->slot);
         if (r != sceMcResSucceed)
                 return r;
         return sceMcResSucceed;
 }
References McFsEntryPS1::created, DPRINTF, McFsEntryPS1::edc, McFsEntryPS1::field_2c, McFsEntryPS1::field_38, McFsEntryPS1::field_7d, MC_FHANDLE::filesize, MC_FHANDLE::freeclink, McFsEntryPS1::length, McFlushCache(), mcman_calcEDC(), mcman_fdhandles, mcman_get1stcacheEntp(), mcman_getmcrtime(), mcman_readdirentryPS1(), memset(), McFsEntryPS1::modified, MC_FHANDLE::port, sceMcResSucceed, sio2man_type, MC_FHANDLE::slot, McCacheEntry::wr_flag, and XSIO2MAN.
Referenced by McClose(), McFlush(), and mcman_write1().
mcman_close2()
int mcman_close2 (int fd)
Definition at line 625 of file ps2mc_fio.c.
 {
         register int r, fmode;
         register MC_FHANDLE *fh = (MC_FHANDLE *)&mcman_fdhandles[fd];
         McFsEntry *fse1, *fse2;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_close2 fd %d\n", fd);
 #endif
         r = McReadDirEntry(fh->port, fh->slot, fh->field_20, fh->field_24, &fse1);
         if (r != sceMcResSucceed)
                 return -31;
         if (fh->unknown2 == 0) {
                 fmode = fse1->mode | sceMcFileAttrClosed;
         }
         else {
                 fmode = fse1->mode & 0xff7f;
         }
         fse1->mode = fmode;
         mcman_getmcrtime(&fse1->modified);
         fse1->cluster = fh->freeclink;
         fse1->length = fh->filesize;
         Mc1stCacheEntSetWrFlagOff();
         mcman_fsmodtime = fse1->modified;
         r = McReadDirEntry(fh->port, fh->slot, fh->field_28, fh->field_2C, &fse2);
         if (r != sceMcResSucceed)
                 return r;
         fse2->modified = mcman_fsmodtime;
         Mc1stCacheEntSetWrFlagOff();
         return sceMcResSucceed;
 }
References McFsEntry::cluster, DPRINTF, MC_FHANDLE::field_20, MC_FHANDLE::field_24, MC_FHANDLE::field_28, MC_FHANDLE::field_2C, MC_FHANDLE::filesize, MC_FHANDLE::freeclink, McFsEntry::length, Mc1stCacheEntSetWrFlagOff(), mcman_fdhandles, mcman_fsmodtime, mcman_getmcrtime(), McReadDirEntry(), McFsEntry::mode, McFsEntry::modified, MC_FHANDLE::port, sceMcFileAttrClosed, sceMcResSucceed, MC_FHANDLE::slot, and MC_FHANDLE::unknown2.
Referenced by McClose(), McFlush(), mcman_fatWseek(), and mcman_write2().
mcman_correctdata()
int mcman_correctdata (void * buf, void * ecc)
Definition at line 1243 of file main.c.
 {
         register int xor0, xor1, xor2, xor3, xor4;
         u8 eccbuf[12];
         u8 *p = (u8 *)ecc;
         McDataChecksum(buf, eccbuf);
         xor0 = p[0] ^ eccbuf[0];
         xor1 = p[1] ^ eccbuf[1];
         xor2 = p[2] ^ eccbuf[2];
         xor3 = xor1 ^ xor2;
         xor4 = (xor0 & 0xf) ^ (xor0 >> 4);
         if (!xor0 && !xor1 && !xor2)
                 return 0;
         if ((xor3 == 0x7f) && (xor4 == 0x7)) {
                 p[xor2] ^= 1 << (xor0 >> 4);
                 return -1;
         }
         xor0 = 0;
         xor2 = 7;
         do {
                 if ((xor3 & 1))
                         xor0++;
                 xor2--;
                 xor3 = xor3 >> 1;
         } while (xor2 >= 0);
         xor2 = 3;
         do {
                 if ((xor4 & 1))
                         xor0++;
                 xor2--;
                 xor4 = xor4 >> 1;
         } while (xor2 >= 0);
         if (xor0 == 1)
                 return -2;
         return -3;
 }
References McDataChecksum().
Referenced by McCheckBlock(), and McReadPage().
mcman_delete1()
int mcman_delete1 (int port, int slot, char * filename, int flags)
Definition at line 625 of file ps1mc_fio.c.
 {
         register int r;
         McFsEntryPS1 *fse;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_delete1 port%d slot%d filename %s flags %x\n", port, slot, filename, flags);
 #endif
         r = mcman_getPS1direntry(port, slot, filename, &fse, ((u32)flags < 1) ? 1 : 0);
         if (r < 0)
                 return r;
         r = mcman_clearPS1direntry(port, slot, r, flags);
         return r;
 }
References DPRINTF, mcman_clearPS1direntry(), and mcman_getPS1direntry().
Referenced by McDelete().
mcman_delete2()
int mcman_delete2 (int port, int slot, char * filename, int flags)
Definition at line 1281 of file ps2mc_fio.c.
 {
         register int r, i;
         McCacheDir cacheDir;
         McFsEntry *fse1, *fse2;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_delete2 port%d slot%d filename %s flags %x\n",  port, slot, filename, flags);
 #endif
         //if (!mcman_checkpath(filename))
         //      return sceMcResNoEntry;
         r = mcman_cachedirentry(port, slot, filename, &cacheDir, &fse1, ((u32)(flags < 1)) ? 1 : 0);
         if (r > 0)
                 return sceMcResNoEntry;
         if (r < 0)
                 return r;
         if (!flags) {
                 if (!(fse1->mode & sceMcFileAttrExists))
                         return sceMcResNoEntry;
         }
         else {
                 if (fse1->mode & sceMcFileAttrExists)
                         return sceMcResNoEntry;
         }
         if ((!PS1CardFlag) && (!flags)) {
                 if (!(fse1->mode & sceMcFileAttrWriteable))
                         return sceMcResDeniedPermit;
         }
         if ((!fse1->cluster) && (!fse1->dir_entry))
                 return sceMcResNoEntry;
         i = 2;
         if ((!flags) && (fse1->mode & sceMcFileAttrSubdir) && (i < fse1->length)) {
                 do {
                         r = McReadDirEntry(port, slot, fse1->cluster, i, &fse2);
                         if (r != sceMcResSucceed)
                                 return r;
                         if (fse2->mode & sceMcFileAttrExists)
                                 return sceMcResNotEmpty;
                 } while (++i < fse1->length);
         }
         r = McSetDirEntryState(port, slot, cacheDir.cluster, cacheDir.fsindex, flags);
         if (r != sceMcResSucceed)
                 return r;
         r = McFlushCache(port, slot);
         if (r != sceMcResSucceed)
                 return r;
         return sceMcResSucceed;
 }
References McFsEntry::cluster, McCacheDir::cluster, McFsEntry::dir_entry, DPRINTF, McCacheDir::fsindex, McFlushCache(), mcman_cachedirentry(), McReadDirEntry(), McSetDirEntryState(), McFsEntry::mode, PS1CardFlag, sceMcFileAttrExists, sceMcFileAttrSubdir, sceMcFileAttrWriteable, sceMcResDeniedPermit, sceMcResNoEntry, sceMcResNotEmpty, and sceMcResSucceed.
Referenced by McDelete().
mcman_detectcard()
int mcman_detectcard (int port, int slot)
Definition at line 489 of file main.c.
 {
         register int r;
         register MCDevInfo *mcdi;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_detectcard port%d slot%d\n", port, slot);
 #endif
         mcdi = (MCDevInfo *)&mcman_devinfos[port][slot];
         if ((mcdi->cardtype == sceMcTypeNoCard) || (mcdi->cardtype == sceMcTypePS2)) {
                 r = mcman_probePS2Card2(port, slot);
                 if (r < -9) {
                         r = mcman_probePS1Card2(port, slot);
                         if (!(r < -9)) {
                                 if (mcman_probePDACard(port, slot)) {
                                         mcdi->cardtype = sceMcTypePS1;
                                         return (!PS1CardFlag) ? sceMcResDeniedPS1Permit : r;
                                 }
                                 else {
                                         mcdi->cardtype = sceMcTypePDA;
                                         return r;
                                 }
                         }
                 }
                 else {
                         mcdi->cardtype = sceMcTypePS2;
                         return r;
                 }
         }
         else {
                 r = mcman_probePS1Card2(port, slot);
                 if (r) {
                         if ((r < -9) || (r >= 0)) {
                                 r = mcman_probePS2Card2(port, slot);
                                 if (!(r < -9)) {
                                         mcdi->cardtype = sceMcTypePS2;
                                         return r;
                                 }
                         }
                         else {
                                 if (mcman_probePDACard(port, slot)) {
                                         mcdi->cardtype = sceMcTypePS1;
                                         return (!PS1CardFlag) ? sceMcResDeniedPS1Permit : r;
                                 }
                                 else {
                                         mcdi->cardtype = sceMcTypePDA;
                                         return r;
                                 }
                         }
                 }
                 else {
                         if (PS1CardFlag)
                                 return sceMcResSucceed;
                         if (mcdi->cardtype == sceMcTypePS1)
                                 return sceMcResDeniedPS1Permit;
                         return sceMcResSucceed;
                 }
         }
         mcdi->cardtype = 0;
         mcdi->cardform = 0;
         mcman_invhandles(port, slot);
         mcman_clearcache(port, slot);
         return r;
 }
References MCDevInfo::cardform, MCDevInfo::cardtype, DPRINTF, mcman_clearcache(), mcman_devinfos, mcman_invhandles(), mcman_probePDACard(), mcman_probePS1Card2(), mcman_probePS2Card2(), PS1CardFlag, sceMcResDeniedPS1Permit, sceMcResSucceed, sceMcTypeNoCard, sceMcTypePDA, sceMcTypePS1, and sceMcTypePS2.
Referenced by _start().
mcman_dread()
int mcman_dread (int fd, io_dirent_t * dirent)
Definition at line 919 of file main.c.
 {
         register int r;
         register MC_FHANDLE *fh;
         if (!((u32)fd < MAX_FDHANDLES))
                 return sceMcResDeniedPermit;
         fh = (MC_FHANDLE *)&mcman_fdhandles[fd];
         if (!fh->status)
                 return sceMcResDeniedPermit;
         if (!fh->drdflag)
                 return sceMcResDeniedPermit;
         r = McDetectCard(fh->port, fh->slot);
         if (r != sceMcResSucceed)
                 return r;
         if (mcman_devinfos[fh->port][fh->slot].cardtype == sceMcTypePS2)
                 r = mcman_dread2(fd, dirent);
         else
                 r = mcman_dread1(fd, dirent);
         if (r < 0)
                 fh->status = 0;
         if (r < -9) {
                 mcman_invhandles(fh->port, fh->slot);
                 mcman_clearcache(fh->port, fh->slot);
         }
         return r;
 }
References MCDevInfo::cardtype, MC_FHANDLE::drdflag, MAX_FDHANDLES, McDetectCard(), mcman_clearcache(), mcman_devinfos, mcman_dread1(), mcman_dread2(), mcman_fdhandles, mcman_invhandles(), MC_FHANDLE::port, sceMcResDeniedPermit, sceMcResSucceed, sceMcTypePS2, MC_FHANDLE::slot, and MC_FHANDLE::status.
Referenced by mc_dread().
mcman_dread1()
int mcman_dread1 (int fd, io_dirent_t * dirent)
Definition at line 363 of file ps1mc_fio.c.
 {
         register int r;
         register MC_FHANDLE *fh = (MC_FHANDLE *)&mcman_fdhandles[fd];
         McFsEntryPS1 *fse;
         if (fh->position < fh->filesize) {
                 do {
                         r = mcman_readdirentryPS1(fh->port, fh->slot, fh->position, &fse);
                         if (r != sceMcResSucceed)
                                 return r;
                         if (fse->mode == 0x51)
                                 break;
                 } while (++fh->position < fh->filesize);
         }
         if (fh->position >= fh->filesize)
                 return 0;
         fh->position++;
         mcman_wmemset((void *)dirent, sizeof(io_dirent_t), 0);
         strncpy(dirent->name, fse->name, 20);
         dirent->name[20] = 0;
         dirent->stat.mode = 0x101f;
         if (fse->field_7e == 1)
                 dirent->stat.mode = 0x181f;
         if (fse->field_7d == 1) {
                 memcpy(dirent->stat.ctime, &fse->created, sizeof(sceMcStDateTime));
                 memcpy(dirent->stat.mtime, &fse->modified, sizeof(sceMcStDateTime));
                 dirent->stat.size = fse->field_38;
                 dirent->stat.attr = fse->field_28;
         }
         else {
                 dirent->stat.size = fse->length;
         }
         return 1;
 }
References io_stat_t::attr, McFsEntryPS1::created, io_stat_t::ctime, McFsEntryPS1::field_28, McFsEntryPS1::field_38, McFsEntryPS1::field_7d, McFsEntryPS1::field_7e, MC_FHANDLE::filesize, McFsEntryPS1::length, mcman_fdhandles, mcman_readdirentryPS1(), mcman_wmemset(), memcpy(), io_stat_t::mode, McFsEntryPS1::mode, McFsEntryPS1::modified, io_stat_t::mtime, McFsEntryPS1::name, io_dirent_t::name, MC_FHANDLE::port, MC_FHANDLE::position, sceMcResSucceed, io_stat_t::size, MC_FHANDLE::slot, io_dirent_t::stat, and strncpy().
Referenced by mcman_dread().
mcman_dread2()
int mcman_dread2 (int fd, io_dirent_t * dirent)
Definition at line 276 of file ps2mc_fio.c.
 {
         register int r;
         register MC_FHANDLE *fh = (MC_FHANDLE *)&mcman_fdhandles[fd];
         McFsEntry *fse;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_dread2 fd %d\n", fd);
 #endif
         if (fh->position >= fh->filesize)
                 return sceMcResSucceed;
         do {
                 r = McReadDirEntry(fh->port, fh->slot, fh->freeclink, fh->position, &fse);
                 if (r != sceMcResSucceed)
                         return r;
                 if (fse->mode & sceMcFileAttrExists)
                         break;
                 fh->position++;
         } while (fh->position < fh->filesize);
         if (fh->position >= fh->filesize)
                 return sceMcResSucceed;
         fh->position++;
         mcman_wmemset((void *)dirent, sizeof (io_dirent_t), 0);
         strcpy(dirent->name, fse->name);
         *(u8 *)&dirent->name[32] = 0;
         if (fse->mode & sceMcFileAttrReadable)
                 dirent->stat.mode |= sceMcFileAttrReadable;
         if (fse->mode & sceMcFileAttrWriteable)
                 dirent->stat.mode |= sceMcFileAttrWriteable;
         if (fse->mode & sceMcFileAttrExecutable)
                 dirent->stat.mode |= sceMcFileAttrExecutable;
         if (fse->mode & sceMcFileAttrPS1)
                 dirent->stat.mode |= sceMcFileAttrPS1;
         if (fse->mode & sceMcFileAttrPDAExec)
                 dirent->stat.mode |= sceMcFileAttrPDAExec;
         if (fse->mode & sceMcFileAttrDupProhibit)
                 dirent->stat.mode |= sceMcFileAttrDupProhibit;
         if (fse->mode & sceMcFileAttrSubdir)
                 dirent->stat.mode |= sceMcFileAttrSubdir;
         else
                 dirent->stat.mode |= sceMcFileAttrFile;
         dirent->stat.attr = fse->attr;
         dirent->stat.size = fse->length;
         memcpy(dirent->stat.ctime, &fse->created, sizeof(sceMcStDateTime));
         memcpy(dirent->stat.mtime, &fse->modified, sizeof(sceMcStDateTime));
         return 1;
 }
References io_stat_t::attr, McFsEntry::attr, McFsEntry::created, io_stat_t::ctime, DPRINTF, MC_FHANDLE::filesize, MC_FHANDLE::freeclink, McFsEntry::length, mcman_fdhandles, mcman_wmemset(), McReadDirEntry(), memcpy(), io_stat_t::mode, McFsEntry::mode, McFsEntry::modified, io_stat_t::mtime, io_dirent_t::name, McFsEntry::name, MC_FHANDLE::port, MC_FHANDLE::position, sceMcFileAttrDupProhibit, sceMcFileAttrExecutable, sceMcFileAttrExists, sceMcFileAttrFile, sceMcFileAttrPDAExec, sceMcFileAttrPS1, sceMcFileAttrReadable, sceMcFileAttrSubdir, sceMcFileAttrWriteable, sceMcResSucceed, io_stat_t::size, MC_FHANDLE::slot, io_dirent_t::stat, and strcpy().
Referenced by mcman_dread().
mcman_eraseblock()
int mcman_eraseblock (int port, int slot, int block, void ** pagebuf, void * eccbuf)
Definition at line 381 of file mcsio2.c.
 {
         register int retries, size, ecc_offset;
         int page;
         u8 *p = mcman_sio2packet.out_dma.addr;
         void *p_ecc;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         page = block * mcdi->blocksize;
         sio2packet_add(port, slot, 0xffffffff, NULL);
         sio2packet_add(port, slot, 0x02, (u8 *)&page);
         sio2packet_add(port, slot, 0x0d, NULL);
         sio2packet_add(port, slot, 0xfffffffe, NULL);
         retries = 0;
         do {
                 mcman_sio2transfer(port, slot, &mcman_sio2packet);
                 if (((mcman_sio2packet.stat6c & 0xF000) != 0x1000) || (p[8] != 0x5a))
                         continue;
                 if (p[0x93] == p[8])
                         break;
         } while (++retries < 5);
         if (retries >= 5)
                 return sceMcResChangedCard;
         if (pagebuf && eccbuf) { // This part leave the first ecc byte of each block page in eccbuf
                 mcman_wmemset(eccbuf, 32, 0);
                 page = 0;
                 while (page < mcdi->blocksize) {
                         ecc_offset = page * mcdi->pagesize;
                         if (ecc_offset < 0)
                                 ecc_offset += 0x1f;
                         ecc_offset = ecc_offset >> 5;
                         p_ecc = (void *)(eccbuf + ecc_offset);
                         size = 0;
                         while (size < mcdi->pagesize)   {
                                 if (*pagebuf)
                                         McDataChecksum((void *)(*pagebuf + size), p_ecc);
                                 size += 128;
                                 p_ecc += 3;
                         }
                         pagebuf++;
                         page++;
                 }
         }
         sio2packet_add(port, slot, 0xffffffff, NULL);
         sio2packet_add(port, slot, 0x1, NULL);
         sio2packet_add(port, slot, 0xfffffffe, NULL);
         retries = 0;
         do {
                 mcman_sio2transfer(port, slot, &mcman_sio2packet);
                 if (((mcman_sio2packet.stat6c & 0xF000) != 0x1000))
                         continue;
                 if (p[3] == 0x5a)
                         return sceMcResSucceed;
         } while (++retries < 100);
         if (p[3] == 0x66)
                 return sceMcResFailReplace;
         return sceMcResNoFormat;
 }
References _sio2_dma_arg::addr, MCDevInfo::blocksize, McDataChecksum(), mcman_devinfos, mcman_sio2packet, mcman_sio2transfer, mcman_wmemset(), NULL, sio2_transfer_data_t::out_dma, MCDevInfo::pagesize, sceMcResChangedCard, sceMcResFailReplace, sceMcResNoFormat, sceMcResSucceed, sio2packet_add(), and sio2_transfer_data_t::stat6c.
Referenced by McCheckBlock(), McEraseBlock(), McEraseBlock2(), mcman_checkBackupBlocks(), mcman_fillbackupblock1(), mcman_flushcacheentry(), mcman_format2(), mcman_unformat2(), and mcman_writecluster().
mcman_fatRseek()
int mcman_fatRseek (int fd)
Definition at line 1559 of file main.c.
 {
         register int r, entries_to_read, fat_index;
         register MC_FHANDLE *fh = (MC_FHANDLE *)&mcman_fdhandles[fd]; //s1
         register MCDevInfo *mcdi = &mcman_devinfos[fh->port][fh->slot]; //s2
         int fat_entry;
         entries_to_read = fh->position / mcdi->cluster_size; //s0
         //s5 = 0
         if (entries_to_read < fh->clust_offset) //v1 = fh->fh->clust_offset
                 fat_index = fh->freeclink;
         else {
                 fat_index = fh->clink; // a2
                 entries_to_read -= fh->clust_offset;
         }
         if (entries_to_read == 0) {
                 if (fat_index >= 0)
                         return fat_index + mcdi->alloc_offset;
                 return sceMcResFullDevice;
         }
         do {
                 r = McGetFATentry(fh->port, fh->slot, fat_index, &fat_entry);
                 if (r != sceMcResSucceed)
                         return r;
                 fat_index = fat_entry;
                 if (fat_index >= -1)
                         return sceMcResFullDevice;
                 entries_to_read--;
                 fat_index &= 0x7fffffff;
                 fh->clink = fat_index;
                 fh->clust_offset = (fh->position / mcdi->cluster_size) - entries_to_read;
         } while (entries_to_read > 0);
         return fat_index + mcdi->alloc_offset;
 }
References MCDevInfo::alloc_offset, MC_FHANDLE::clink, MC_FHANDLE::clust_offset, MCDevInfo::cluster_size, MC_FHANDLE::freeclink, McGetFATentry(), mcman_devinfos, mcman_fdhandles, MC_FHANDLE::port, MC_FHANDLE::position, sceMcResFullDevice, sceMcResSucceed, and MC_FHANDLE::slot.
Referenced by mcman_read2(), and mcman_write2().
mcman_fatRseekPS1()
int mcman_fatRseekPS1 (int fd)
Definition at line 2715 of file main.c.
 {
         register int r, rpos, numclust, clust;
         MC_FHANDLE *fh = (MC_FHANDLE *)&mcman_fdhandles[fd];
         MCDevInfo *mcdi = &mcman_devinfos[fh->port][fh->slot];
         McFsEntryPS1 *fse;
         numclust = fh->position / mcdi->cluster_size;
         numclust--;
         clust = fh->freeclink;
         if (numclust > -1) {
                 do {
                         if (clust < 0)
                                 return sceMcResFullDevice;
                         r = mcman_readdirentryPS1(fh->port, fh->slot, clust, &fse);
                         if (r != sceMcResSucceed)
                                 return r;
                         clust = fse->linked_block;
                 } while (--numclust > -1);
         }
         if (clust < 0)
                 return sceMcResFullDevice;
         rpos = fh->position % mcdi->cluster_size;
         if (rpos < 0)
                 rpos += 1023;
         return ((clust + 1) << 6) + ((rpos >> 10) * (1024 / mcdi->pagesize));
 }
References MCDevInfo::cluster_size, MC_FHANDLE::freeclink, McFsEntryPS1::linked_block, mcman_devinfos, mcman_fdhandles, mcman_readdirentryPS1(), MCDevInfo::pagesize, MC_FHANDLE::port, MC_FHANDLE::position, sceMcResFullDevice, sceMcResSucceed, and MC_FHANDLE::slot.
Referenced by mcman_read1(), and mcman_write1().
mcman_fatWseek()
int mcman_fatWseek (int fd)
Definition at line 1606 of file main.c.
 {
         register int r, entries_to_write, fat_index;
         register MC_FHANDLE *fh = (MC_FHANDLE *)&mcman_fdhandles[fd];
         register MCDevInfo *mcdi = &mcman_devinfos[fh->port][fh->slot];
         register McCacheEntry *mce;
         int fat_entry;
         entries_to_write = fh->position / mcdi->cluster_size;
         if ((fh->clust_offset == 0) || (entries_to_write < fh->clust_offset)) {
                 fat_index = fh->freeclink;
                 if (fat_index < 0) {
                         fat_index = mcman_findfree2(fh->port, fh->slot, 1);
                         if (fat_index < 0)
                                 return sceMcResFullDevice;
                         mce = (McCacheEntry *)mcman_get1stcacheEntp();
                         fh->freeclink = fat_index;
                         r = mcman_close2(fd);
                         if (r != sceMcResSucceed)
                                 return r;
                         mcman_addcacheentry(mce);
                         McFlushCache(fh->port, fh->slot);
                 }
         }
         else {
                 fat_index = fh->clink;
                 entries_to_write -= fh->clust_offset;
         }
         if (entries_to_write != 0) {
                 do {
                         r = McGetFATentry(fh->port, fh->slot, fat_index, &fat_entry);
                         if (r != sceMcResSucceed)
                                 return r;
                         if (fat_entry >= 0xffffffff) {
                                 r = mcman_findfree2(fh->port, fh->slot, 1);
                                 if (r < 0)
                                                 return r;
                                 fat_entry = r;
                                 fat_entry |= 0x80000000;
                                 mce = (McCacheEntry *)mcman_get1stcacheEntp();
                                 r = McSetFATentry(fh->port, fh->slot, fat_index, fat_entry);
                                 if (r != sceMcResSucceed)
                                         return r;
                                 mcman_addcacheentry(mce);
                         }
                         entries_to_write--;
                         fat_index = fat_entry & 0x7fffffff;
                 } while (entries_to_write > 0);
         }
         fh->clink = fat_index;
         fh->clust_offset = fh->position / mcdi->cluster_size;
         return sceMcResSucceed;
 }
References MC_FHANDLE::clink, MC_FHANDLE::clust_offset, MCDevInfo::cluster_size, MC_FHANDLE::freeclink, McFlushCache(), McGetFATentry(), mcman_addcacheentry(), mcman_close2(), mcman_devinfos, mcman_fdhandles, mcman_findfree2(), mcman_get1stcacheEntp(), McSetFATentry(), MC_FHANDLE::port, MC_FHANDLE::position, sceMcResFullDevice, sceMcResSucceed, and MC_FHANDLE::slot.
Referenced by mcman_write2().
mcman_fatWseekPS1()
int mcman_fatWseekPS1 (int fd)
Definition at line 2751 of file main.c.
 {
         register int r, numclust, clust;
         MC_FHANDLE *fh = (MC_FHANDLE *)&mcman_fdhandles[fd];
         MCDevInfo *mcdi = &mcman_devinfos[fh->port][fh->slot];
         McFsEntryPS1 *fse;
         numclust = fh->position / mcdi->cluster_size;
         if (numclust > 0) {
                 clust = fh->freeclink;
                 do {
                         r = mcman_readdirentryPS1(fh->port, fh->slot, clust, &fse);
                         if (r != sceMcResSucceed)
                                 return r;
                         clust = fse->linked_block;
                         if (clust < 0) {
                                 r = mcman_FNC8ca4(fh->port, fh->slot, (MC_FHANDLE *)fh);
                                 if (r < 0)
                                         return r;
                                 clust = r;
                         }
                 } while (--numclust);
         }
         r = McFlushCache(fh->port, fh->slot);
         return r;
 }
References MCDevInfo::cluster_size, MC_FHANDLE::freeclink, McFsEntryPS1::linked_block, McFlushCache(), mcman_devinfos, mcman_fdhandles, mcman_FNC8ca4(), mcman_readdirentryPS1(), MC_FHANDLE::port, MC_FHANDLE::position, sceMcResSucceed, and MC_FHANDLE::slot.
Referenced by mcman_write1().
mcman_fillbackupblock1()
int mcman_fillbackupblock1 (int port, int slot, int block, void ** pagedata, void * eccdata)
Definition at line 3927 of file main.c.
 {
         register int r, i, sparesize, page_offset;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         register u8 *p_ecc;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_fillbackupblock1 port%d slot%d block %x mcman_badblock %x\n", port, slot, block, mcman_badblock);
 #endif
         sparesize = mcman_sparesize(port, slot);
         if (mcman_badblock != 0) {
                 if ((mcman_badblock != block) || (mcman_badblock_port != port) || (mcman_badblock_slot != slot))
                         return sceMcResFailReplace;
         }
         if ((mcdi->alloc_offset / mcdi->clusters_per_block) == block) // Appparently this refuse to take care of a bad rootdir cluster
                 return sceMcResFailReplace;
         r = mcman_eraseblock(port, slot, mcdi->backup_block2, NULL, NULL);
         if (r != sceMcResSucceed)
                 return r;
         r = mcman_eraseblock(port, slot, mcdi->backup_block1, NULL, NULL);
         if (r != sceMcResSucceed)
                 return r;
         for (i = 0; i < 16; i++) {
                 if (mcdi->bad_block_list[i] == -1)
                         break;
         }
         if (i >= 16)
                 return sceMcResFailReplace;
         page_offset = mcdi->backup_block1 * mcdi->blocksize;
         p_ecc = (u8 *)eccdata;
         for (i = 0; i < mcdi->blocksize; i++) {
                 r = McWritePage(port, slot, page_offset + i, pagedata[i], p_ecc);
                 if (r != sceMcResSucceed)
                         return r;
                 p_ecc += sparesize;
         }
         mcman_badblock_port = port;
         mcman_badblock_slot = slot;
         mcman_badblock = block;
         i = 15;
         do {
                 mcman_replacementcluster[i] = 0;
         } while (--i >= 0);
         return sceMcResSucceed;
 }
References MCDevInfo::alloc_offset, MCDevInfo::backup_block1, MCDevInfo::backup_block2, MCDevInfo::bad_block_list, MCDevInfo::blocksize, MCDevInfo::clusters_per_block, DPRINTF, mcman_badblock, mcman_badblock_port, mcman_badblock_slot, mcman_devinfos, mcman_eraseblock(), mcman_replacementcluster, mcman_sparesize(), McWritePage(), NULL, sceMcResFailReplace, and sceMcResSucceed.
Referenced by mcman_flushcacheentry().
mcman_fillPS1backuparea()
int mcman_fillPS1backuparea (int port, int slot, int block)
Definition at line 3103 of file main.c.
 {
         register int r, i, curpage;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         memset(&mcman_PS1PDApagebuf, 0, 128);
         curpage = 16;
         i = 0;
         do {
                 if (mcdi->bad_block_list[i] == block) {
                         mcdi->bad_block_list[i] = block | 0x01000000;
                         mcman_PS1PDApagebuf.word[0] = block | 0x01000000;
                         mcman_PS1PDApagebuf.byte[127] = mcman_calcEDC(&mcman_PS1PDApagebuf, 127);
                         r = McWritePS1PDACard(port, slot, curpage, &mcman_PS1PDApagebuf);
                         if (r != sceMcResSucceed)
                                 return -43;
                 }
                 else {
                         if (mcdi->bad_block_list[i] < 0) {
                                 mcman_PS1PDApagebuf.word[0] = block;
                                 mcman_PS1PDApagebuf.byte[127] = mcman_calcEDC(&mcman_PS1PDApagebuf, 127);
                                 r = McWritePS1PDACard(port, slot, curpage, &mcman_PS1PDApagebuf);
                                 if (r != sceMcResSucceed)
                                         return -43;
                                 mcdi->bad_block_list[i] = block;
                                 break;
                         }
                 }
                 curpage++;
         } while (++i < 20);
         return sceMcResSucceed;
 }
References MCDevInfo::bad_block_list, mcman_PS1PDApagebuf::byte, mcman_calcEDC(), mcman_devinfos, McWritePS1PDACard(), memset(), sceMcResSucceed, and mcman_PS1PDApagebuf::word.
Referenced by mcman_flushcacheentry().
mcman_findfree1()
int mcman_findfree1 (int port, int slot, int reserve)
Definition at line 2681 of file main.c.
 {
         register int r, i, free;
         McFsEntryPS1 *fse;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_findfree1 port%d slot%d reserve %d\n", port, slot, reserve);
 #endif
         free = 0;
         i = 0;
         do {
                 r = mcman_readdirentryPS1(port, slot, i, &fse);
                 if (r != sceMcResSucceed)
                         return -37;
                 if ((fse->mode & 0xf0) == 0xa0) {
                         if (reserve)
                                 return i;
                         free++;
                 }
         } while (++i < 15);
         if (reserve)
                 return sceMcResFullDevice;
         if (free)
                 return free;
         return sceMcResFullDevice;
 }
References DPRINTF, free(), mcman_readdirentryPS1(), McFsEntryPS1::mode, sceMcResFullDevice, and sceMcResSucceed.
Referenced by McGetFreeClusters(), and mcman_FNC8ca4().
mcman_findfree2()
int mcman_findfree2 (int port, int slot, int reserve)
Definition at line 1675 of file main.c.
 {
         register int r, rfree, indirect_index, ifc_index, fat_offset, indirect_offset, fat_index, block;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         McCacheEntry *mce1, *mce2;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_findfree2 port%d slot%d reserve%d\n", port, slot, reserve);
 #endif
         fat_index = mcdi->unknown2;
         rfree = 0;
         for (fat_index = mcdi->unknown2; fat_index < mcdi->max_allocatable_clusters; fat_index++) {
                 indirect_index = fat_index / mcdi->FATentries_per_cluster;
                 fat_offset = fat_index % mcdi->FATentries_per_cluster;
                 if ((fat_offset == 0) || (fat_index == mcdi->unknown2)) {
                         ifc_index = indirect_index / mcdi->FATentries_per_cluster;
                         r = McReadCluster(port, slot, mcdi->ifc_list[ifc_index], &mce1);
                         if (r != sceMcResSucceed)
                                 return r;
                 //}
                 //if ((fat_offset == 0) || (fat_index == mcdi->unknown2)) {
                         indirect_offset = indirect_index % mcdi->FATentries_per_cluster;
                         McFatCluster *fc = (McFatCluster *)mce1->cl_data;
                         r = McReadCluster(port, slot, fc->entry[indirect_offset], &mce2);
                         if (r != sceMcResSucceed)
                                 return r;
                 }
                 McFatCluster *fc = (McFatCluster *)mce2->cl_data;
                 if (fc->entry[fat_offset] >= 0) {
                         block = (mcdi->alloc_offset + fat_offset) / mcdi->clusters_per_block;
                         if (block != mcman_badblock) {
                                 if (reserve) {
                                         fc->entry[fat_offset] = 0xffffffff;
                                         mce2->wr_flag = 1;
                                         mcdi->unknown2 = fat_index;
                                         return fat_index;
                                 }
                                 rfree++;
                         }
                 }
         }
         if (reserve)
                 return sceMcResFullDevice;
         return (rfree) ? rfree : sceMcResFullDevice;
 }
References MCDevInfo::alloc_offset, McCacheEntry::cl_data, MCDevInfo::clusters_per_block, DPRINTF, McFatCluster::entry, MCDevInfo::FATentries_per_cluster, MCDevInfo::ifc_list, mcman_badblock, mcman_devinfos, McReadCluster(), sceMcResFullDevice, sceMcResSucceed, MCDevInfo::unknown2, and McCacheEntry::wr_flag.
Referenced by McGetFreeClusters(), mcman_fatWseek(), mcman_open2(), and McReplaceBadBlock().
mcman_flushcacheentry()
int mcman_flushcacheentry (McCacheEntry * mce)
Definition at line 3339 of file main.c.
 {
         register int r, i, j, ecc_count;
         register int temp1, temp2, offset, pageindex;
         static int clusters_per_block, blocksize, cardtype, pagesize, sparesize, flag, cluster, block, pages_per_fatclust;
         McCacheEntry *pmce[16]; // sp18
         register MCDevInfo *mcdi;
         McCacheEntry *mcee;
         static u8 eccbuf[32];
         void *p_page, *p_ecc;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_flushcacheentry mce %x cluster %x\n", (int)mce, (int)mce->cluster);
 #endif
         if (mce->wr_flag == 0)
                 return sceMcResSucceed;
         mcdi = (MCDevInfo *)&mcman_devinfos[mce->mc_port][mce->mc_slot];
         //mcdi->pagesize = sp84
         pagesize = mcdi->pagesize; //sp84
         cardtype = mcdi->cardtype;
         if (cardtype == 0) {
                 mce->wr_flag = 0;
                 return sceMcResSucceed;
         }
         if ((cardtype == sceMcTypePS1) || (cardtype == sceMcTypePDA)) {
                 pages_per_fatclust = MCMAN_CLUSTERSIZE / pagesize;
                 i = mce->cluster; //s0
                 j = 0; //s1
                 r = 0;
                 if (pages_per_fatclust > 0) {
 lbl0:
                         do {
                                 if (((mce->wr_flag >> j) & 1) != 0) {
                                         //DPRINTF("flushing ent %x cl_data %x to page %d offset %d\n", mce, mce->cl_data, i, (pagesize * j));
                                         r = McWritePS1PDACard(mce->mc_port, mce->mc_slot, i, (void *)(mce->cl_data + (pagesize * j)));
                                         if (r == sceMcResFailReplace)
                                                 break;
                                         if (r != sceMcResSucceed)
                                                 return -50;
                                 }
                                 i++;
                         } while (++j < pages_per_fatclust);
                 }
                 if (j == pages_per_fatclust) {
                         r = mcman_probePS1Card2(mce->mc_port, mce->mc_slot);
                         if (r == -14)
                                 r = sceMcResFailReplace;
                 }
                 if (cardtype != sceMcTypePS1) {
                         if (r == sceMcResFailReplace)
                                 return r;
                         mce->wr_flag = 0;
                         return sceMcResSucceed;
                 }
                 if (r != 8) {
                         mce->wr_flag = 0;
                         return sceMcResSucceed;
                 }
                 if ((mce->wr_flag & ~(-1 << j)) == 0) {
                         mce->wr_flag = 0;
                         return sceMcResSucceed;
                 }
                 if (j-- == 0) {
                         mce->wr_flag = 0;
                         return sceMcResSucceed;
                 }
                 i--;
                 do {
                         if (((mce->wr_flag >> j) & 1) != 0) {
                                 r = mcman_fillPS1backuparea(mce->mc_port, mce->mc_slot, i);
                                 if (r != sceMcResSucceed)
                                         return sceMcResFailReplace;
                                 goto lbl0;
                         }
                 } while (j++);
                 mce->wr_flag = 0;
                 return sceMcResSucceed;
         }
         clusters_per_block = mcdi->clusters_per_block; //sp7c
         block = mce->cluster / mcdi->clusters_per_block; //sp78
         blocksize = mcdi->blocksize;  //sp80
         sparesize = mcman_sparesize(mce->mc_port, mce->mc_slot); //sp84
         flag = 0; //sp88
         memset((void *)pmce, 0, 64);
         i = 0; //s1
         if (MAX_CACHEENTRY > 0) {
                 mcee = (McCacheEntry *)pmcman_entrycache;
                 do {
                         if ((mcee->mc_slot == mce->mc_slot) && (mcee->mc_port == mce->mc_port)) {
                                 temp1 = mcee->cluster / clusters_per_block;
                                 temp2 = mcee->cluster % clusters_per_block;
                                 if (temp1 == block) {
                                         pmce[temp2] = (McCacheEntry *)mcee;
                                         if (mcee->rd_flag == 0)
                                                 flag = 1;
                                 }
                         }
                         mcee++;
                 } while (++i < MAX_CACHEENTRY);
         }
         if (clusters_per_block > 0) {
                 i = 0; //s1
                 pageindex = 0; //s5
                 cluster = block * clusters_per_block; // sp8c
                 do {
                         if (pmce[i] != 0) {
                                 j = 0; // s0
                                 offset = 0; //a0
                                 for (j = 0; j < mcdi->pages_per_cluster; j++) {
                                         mcman_pagedata[pageindex + j] = (void *)(pmce[i]->cl_data + offset);
                                         offset += pagesize;
                                 }
                         }
                         else {
                                 //s3 = s5
                                 // s2 = (cluster + i) * mcdi->pages_per_cluster
                                 j = 0; //s0
                                 do {
                                         offset = (pageindex + j) * pagesize; // t0
                                         mcman_pagedata[pageindex + j] = (void *)(mcman_backupbuf + offset);
                                         r = McReadPage(mce->mc_port, mce->mc_slot, \
                                                 ((cluster + i) * mcdi->pages_per_cluster) + j, \
                                                         mcman_backupbuf + offset);
                                         if (r != sceMcResSucceed)
                                                 return -51;
                                 } while (++j < mcdi->pages_per_cluster);
                         }
                         pageindex += mcdi->pages_per_cluster;
                 } while (++i < clusters_per_block);
         }
 lbl1:
         if ((flag != 0) && (mcman_badblock <= 0)) {
                 r = mcman_eraseblock(mce->mc_port, mce->mc_slot, mcdi->backup_block1, (void**)mcman_pagedata, mcman_eccdata);
                 if (r == sceMcResFailReplace) {
 lbl2:
                         r = mcman_replaceBackupBlock(mce->mc_port, mce->mc_slot, mcdi->backup_block1);
                         mcdi->backup_block1 = r;
                         goto lbl1;
                 }
                 if (r != sceMcResSucceed)
                         return -52;
                 mcman_pagebuf.word[0] = block | 0x80000000;
                 p_page = (void *)&mcman_pagebuf; //s0
                 p_ecc = (void *)eccbuf; //s2 = sp58
                 i = 0;  //s1
                 do {
                         if (pagesize < 0)
                                 ecc_count = (pagesize + 0x7f) >> 7;
                         else
                                 ecc_count = pagesize >> 7;
                         if (i >= ecc_count)
                                 break;
                         McDataChecksum(p_page, p_ecc);
                         p_ecc += 3;
                         p_page += 128;
                         i++;
                 } while (1);
                 r = McWritePage(mce->mc_port, mce->mc_slot, mcdi->backup_block2 * blocksize, &mcman_pagebuf, eccbuf);
                 if (r == sceMcResFailReplace)
                         goto lbl3;
                 if (r != sceMcResSucceed)
                         return -53;
                 if (r < mcdi->blocksize) {
                         i = 0; //s0
                         p_ecc = (void *)mcman_eccdata;
                         do {
                                 r = McWritePage(mce->mc_port, mce->mc_slot, (mcdi->backup_block1 * blocksize) + i, mcman_pagedata[i], p_ecc);
                                 if (r == sceMcResFailReplace)
                                         goto lbl2;
                                 if (r != sceMcResSucceed)
                                         return -54;
                                 p_ecc += sparesize;
                         } while (++i < mcdi->blocksize);
                 }
                 r = McWritePage(mce->mc_port, mce->mc_slot, (mcdi->backup_block2 * blocksize) + 1, &mcman_pagebuf, eccbuf);
                 if (r == sceMcResFailReplace)
                         goto lbl3;
                 if (r != sceMcResSucceed)
                         return -55;
         }
         r = mcman_eraseblock(mce->mc_port, mce->mc_slot, block, (void**)mcman_pagedata, mcman_eccdata);
         //if (block == 1) /////
         //      r = sceMcResFailReplace; /////
         if (r == sceMcResFailReplace) {
                 r = mcman_fillbackupblock1(mce->mc_port, mce->mc_slot, block, (void**)mcman_pagedata, mcman_eccdata);
                 for (i = 0; i < clusters_per_block; i++) {
                         if (pmce[i] != 0)
                                 pmce[i]->wr_flag = 0;
                 }
                 if (r == sceMcResFailReplace)
                         return r;
                 return -58;
         }
         if (r != sceMcResSucceed)
                 return -57;
         if (mcdi->blocksize > 0) {
                 i = 0; //s0
                 p_ecc = (void *)mcman_eccdata;
                 do {
                         if (pmce[i / mcdi->pages_per_cluster] == 0) {
                                 r = McWritePage(mce->mc_port, mce->mc_slot, (block * blocksize) + i, mcman_pagedata[i], p_ecc);
                                 if (r == sceMcResFailReplace) {
                                         r = mcman_fillbackupblock1(mce->mc_port, mce->mc_slot, block, (void**)mcman_pagedata, mcman_eccdata);
                                         for (i = 0; i < clusters_per_block; i++) {
                                                 if (pmce[i] != 0)
                                                         pmce[i]->wr_flag = 0;
                                         }
                                         if (r == sceMcResFailReplace)
                                                 return r;
                                         return -58;
                                 }
                                 if (r != sceMcResSucceed)
                                         return -57;
                         }
                         p_ecc += sparesize;
                 } while (++i < mcdi->blocksize);
         }
         if (mcdi->blocksize > 0) {
                 i = 0; //s0
                 p_ecc = (void *)mcman_eccdata;
                 do {
                         if (pmce[i / mcdi->pages_per_cluster] != 0) {
                                 r = McWritePage(mce->mc_port, mce->mc_slot, (block * blocksize) + i, mcman_pagedata[i], p_ecc);
                                 if (r == sceMcResFailReplace) {
                                         r = mcman_fillbackupblock1(mce->mc_port, mce->mc_slot, block, (void**)mcman_pagedata, mcman_eccdata);
                                         for (i = 0; i < clusters_per_block; i++) {
                                                 if (pmce[i] != 0)
                                                         pmce[i]->wr_flag = 0;
                                         }
                                         if (r == sceMcResFailReplace)
                                                 return r;
                                         return -58;
                                 }
                                 if (r != sceMcResSucceed)
                                         return -57;
                         }
                         p_ecc += sparesize;
                 } while (++i < mcdi->blocksize);
         }
         if (clusters_per_block > 0) {
                 i = 0;
                 do {
                         if (pmce[i] != 0)
                                 pmce[i]->wr_flag = 0;
                 } while (++i < clusters_per_block);
         }
         if ((flag != 0) && (mcman_badblock <= 0)) {
                 r = mcman_eraseblock(mce->mc_port, mce->mc_slot, mcdi->backup_block2, NULL, NULL);
                 if (r == sceMcResFailReplace) {
                         goto lbl3;
                 }
                 if (r != sceMcResSucceed)
                         return -58;
         }
         goto lbl_exit;
 lbl3:
         r = mcman_replaceBackupBlock(mce->mc_port, mce->mc_slot, mcdi->backup_block2);
         mcdi->backup_block2 = r;
         goto lbl1;
 lbl_exit:
         return sceMcResSucceed;
 }
References MCDevInfo::backup_block1, MCDevInfo::backup_block2, MCDevInfo::blocksize, MCDevInfo::cardtype, McCacheEntry::cl_data, McCacheEntry::cluster, MCDevInfo::clusters_per_block, DPRINTF, MAX_CACHEENTRY, McCacheEntry::mc_port, McCacheEntry::mc_slot, McDataChecksum(), mcman_backupbuf, mcman_badblock, MCMAN_CLUSTERSIZE, mcman_devinfos, mcman_eccdata, mcman_eraseblock(), mcman_fillbackupblock1(), mcman_fillPS1backuparea(), mcman_pagedata, mcman_probePS1Card2(), mcman_replaceBackupBlock(), mcman_sparesize(), McReadPage(), McWritePage(), McWritePS1PDACard(), memset(), NULL, MCDevInfo::pages_per_cluster, MCDevInfo::pagesize, pmcman_entrycache, McCacheEntry::rd_flag, sceMcResFailReplace, sceMcResSucceed, sceMcTypePDA, sceMcTypePS1, mcman_pagebuf::word, and McCacheEntry::wr_flag.
Referenced by McFlushCache(), mcman_readclusterPS1(), and McReadCluster().
mcman_FNC8ca4()
int mcman_FNC8ca4 (int port, int slot, MC_FHANDLE * fh)
Definition at line 2783 of file main.c.
 {
         register int r, i, j, mcfree, cluster_size, pages_per_FATclust;
         register int temp;
         MCDevInfo *mcdi = &mcman_devinfos[fh->port][fh->slot];
         McFsEntryPS1 *fse1, *fse2, *fse3;
         McCacheEntry *mce;
         u8 *pfsentry, *pfsee, *pfseend;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_FNC8ca4 port%d slot%d\n", port, slot);
 #endif
         if (mcdi->cluster_size < 0)
                 cluster_size = mcdi->cluster_size + 1023;
         else
                 cluster_size = mcdi->cluster_size;
         cluster_size = cluster_size >> 10;
         pages_per_FATclust = 1024 / mcdi->pagesize;
         r = mcman_findfree1(port, slot, 1);
         if (r < 0)
                 return r;
         i = fh->freeclink;
         mcfree = r;
         j = -1;
         if (i >= 0) {
                 do {
                         if (mcfree < i) {
                                 if (cluster_size > 0) {
                                         i = 0;
                                         do {
                                                 mcman_freecluster(port, slot, ((mcfree * cluster_size) + i) * pages_per_FATclust);
                                                 r = mcman_readclusterPS1(port, slot, ((i * cluster_size) + i) * pages_per_FATclust, &mce);
                                                 if (r != sceMcResSucceed)
                                                         return r;
                                                 mce->wr_flag = -1;
                                                 mce->cluster -= (i - mcfree) * cluster_size;
                                         } while (++i < cluster_size);
                                 }
                                 r = mcman_readdirentryPS1(port, slot, i, &fse1);
                                 if (r != sceMcResSucceed)
                                         return r;
                                 r = mcman_readdirentryPS1(port, slot, mcfree, &fse2);
                                 if (r != sceMcResSucceed)
                                         return r;
                                 mce = mcman_get1stcacheEntp();
                                 if (mcfree + 1 < 0)
                                         temp = mcfree + 8;
                                 else
                                         temp = mcfree + 1;
                                 mce->wr_flag |= 1 << ((mcfree + 1) - ((temp >> 3) << 3));
                                 pfsentry = (u8 *)fse1;
                                 pfsee = (u8 *)fse2;
                                 pfseend = (u8 *)(pfsentry + sizeof(McFsEntryPS1));
                                 do {
                                         *((u32 *)pfsee  ) = *((u32 *)pfsentry  );
                                         *((u32 *)pfsee+1) = *((u32 *)pfsentry+1);
                                         *((u32 *)pfsee+2) = *((u32 *)pfsentry+2);
                                         *((u32 *)pfsee+3) = *((u32 *)pfsentry+3);
                                         pfsentry += 16;
                                         pfsee += 16;
                                 } while (pfsentry < pfseend);
                                 if (j >= 0) {
                                         r = mcman_readdirentryPS1(port, slot, j, &fse3);
                                         if (r != sceMcResSucceed)
                                                 return r;
                                         mce = mcman_get1stcacheEntp();
                                         if ((j + 1) < 0)
                                                 temp = j + 8;
                                         else
                                                 temp = j + 1;
                                         mce->wr_flag |= 1 << ((j + 1) - ((temp >> 3) << 3));
                                         fse3->linked_block = mcfree;
                                         fse3->edc = mcman_calcEDC((void *)fse3, 127);
                                 }
                                 else {
                                         fh->freeclink = mcfree;
                                 }
                                 j = mcfree;
                                 mcfree = i;
                         }
                         else {
                                 j = i;
                                 r = mcman_readdirentryPS1(port, slot, j, &fse1);
                                 if (r != sceMcResSucceed)
                                         return r;
                         }
                         i = fse1->linked_block;
                 } while (i >= 0);
         }
         r = mcman_readdirentryPS1(port, slot, mcfree, &fse2);
         if (r != sceMcResSucceed)
                 return r;
         mce = mcman_get1stcacheEntp();
         if (mcfree + 1 < 0)
                 temp = mcfree + 8;
         else
                 temp = mcfree + 1;
         mce->wr_flag |= 1 << ((mcfree + 1) - ((temp >> 3) << 3));
         mcman_wmemset((void *)fse2, sizeof(McFsEntryPS1), 0);
         fse2->mode = 0x53;
         fse2->linked_block = -1;
         fse2->edc = mcman_calcEDC((void *)fse2, 127);
         r = mcman_readdirentryPS1(port, slot, j, &fse3);
         if (r != sceMcResSucceed)
                 return r;
         mce = mcman_get1stcacheEntp();
         if ((j + 1) < 0)
                 temp = j + 8;
         else
                 temp = j + 1;
         mce->wr_flag |= 1 << ((j + 1) - ((temp >> 3) << 3));
         if (fse3->mode == 0x53)
                 fse3->mode = 0x52;
         fse3->linked_block =    mcfree;
         fse3->edc = mcman_calcEDC((void *)fse3, 127);
         return mcfree;
 }
References McCacheEntry::cluster, MCDevInfo::cluster_size, DPRINTF, McFsEntryPS1::edc, MC_FHANDLE::freeclink, McFsEntryPS1::linked_block, mcman_calcEDC(), mcman_devinfos, mcman_findfree1(), mcman_freecluster(), mcman_get1stcacheEntp(), mcman_readclusterPS1(), mcman_readdirentryPS1(), mcman_wmemset(), McFsEntryPS1::mode, MCDevInfo::pagesize, MC_FHANDLE::port, sceMcResSucceed, MC_FHANDLE::slot, and McCacheEntry::wr_flag.
Referenced by mcman_fatWseekPS1().
mcman_format1()
int mcman_format1 (int port, int slot)
Definition at line 25 of file ps1mc_fio.c.
 {
         register int r, i;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
 #ifdef DEBUG
         DPRINTF("mcman: mcman_format1 port%d slot%d\n", port, slot);
 #endif
         mcman_invhandles(port, slot);
         for (i = 0; i < 56; i++) {
                 r = mcman_PS1pagetest(port, slot, i);
                 if (r == 0)
                         return sceMcResNoFormat;
                 if (r != 1)
                         return -41;
         }
         memset(&mcman_PS1PDApagebuf, 0, 128);
         mcman_PS1PDApagebuf.word[0] = 0xa0;
         mcman_PS1PDApagebuf.half[2] = 0xffff;
         mcman_PS1PDApagebuf.byte[127] = mcman_calcEDC(&mcman_PS1PDApagebuf, 127);
         for (i = 1; i < 15; i++) {
                 r = McWritePS1PDACard(port, slot, i, &mcman_PS1PDApagebuf);
                 if (r != sceMcResSucceed)
                         return -42;
         }
         memset(&mcman_PS1PDApagebuf, 0, 128);
         mcman_PS1PDApagebuf.word[0] = 0xffffffff;
         for (i = 0; i < 20; i++) {
                 mcman_PS1PDApagebuf.word[0] = mcdi->bad_block_list[i];
                 mcman_PS1PDApagebuf.byte[127] = mcman_calcEDC(&mcman_PS1PDApagebuf, 127);
                 r = McWritePS1PDACard(port, slot, i + 16, &mcman_PS1PDApagebuf);
                 if (r != sceMcResSucceed)
                         return -43;
         }
         mcman_wmemset(&mcman_PS1PDApagebuf, 128, 0);
         mcman_PS1PDApagebuf.byte[0] = 0x4d;
         mcman_PS1PDApagebuf.byte[1] = 0x43;
         mcman_PS1PDApagebuf.byte[127] = 0x0e;
         r = McWritePS1PDACard(port, slot, 0, &mcman_PS1PDApagebuf);
         if (r != sceMcResSucceed)
                 return -44;
         mcdi->cardform = 1;
         return sceMcResSucceed;
 }
References MCDevInfo::bad_block_list, mcman_PS1PDApagebuf::byte, MCDevInfo::cardform, DPRINTF, mcman_PS1PDApagebuf::half, mcman_calcEDC(), mcman_devinfos, mcman_invhandles(), mcman_PS1pagetest(), mcman_wmemset(), McWritePS1PDACard(), memset(), sceMcResNoFormat, sceMcResSucceed, and mcman_PS1PDApagebuf::word.
Referenced by McFormat().
mcman_format2()
int mcman_format2 (int port, int slot)
Definition at line 40 of file ps2mc_fio.c.
 {
         register int r, i, size, ifc_index, indirect_offset, allocatable_clusters_per_card;
         register int ifc_length, fat_length, fat_entry, alloc_offset;
         register int j = 0, z = 0;
         MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         McCacheEntry *mce;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_format2 port%d, slot%d cardform %d\n", port, slot, mcdi->cardform);
 #endif
         if (mcdi->cardform == sceMcResNoFormat) {
                 for (i = 0; i < 32; i++)
                         mcdi->bad_block_list[i] = -1;
                 mcdi->rootdir_cluster = 0;
                 mcdi->rootdir_cluster2 = 0;
                 goto lbl1;
         }
         if (mcdi->cardform > 0) {
                 if (((mcdi->version[0] - 48) >= 2) || ((mcdi->version[2] - 48) >= 2))
                         goto lbl1;
         }
         r = mcman_reportBadBlocks(port, slot);
         if ((r != sceMcResSucceed) && (r != sceMcResNoFormat))
                 return sceMcResChangedCard;
 lbl1:
         // set superblock magic & version
         memset((void *)&mcdi->magic, 0, sizeof (mcdi->magic) + sizeof (mcdi->version));
         strcpy(mcdi->magic, SUPERBLOCK_MAGIC);
         strcat(mcdi->magic, SUPERBLOCK_VERSION);
         //size = 8192 / mcdi->cluster_size; // get blocksize in cluster a better way must be found
         size = mcdi->blocksize;
         mcdi->cardform = -1;
         mcman_wr_port = -1;
         mcman_wr_slot = -1;
         mcman_wr_block = -1;
         mcman_wr_flag3 = -10;
         //if (size <= 0)
         //      size = 1;
         if (mcdi->blocksize <= 0)
                 size = 8;
         // clear first 8 clusters
         for (i = 0; i < size; i++) {
                 r = mcman_writecluster(port, slot, i, 1);
                 if (r == 0)
                         return sceMcResNoFormat;
                 if (r != 1)
                         return -40;
         }
         fat_length = (((mcdi->clusters_per_card << 2) - 1) / mcdi->cluster_size) + 1; // get length of fat in clusters
         ifc_length = (((fat_length << 2) - 1) / mcdi->cluster_size) + 1; // get number of needed ifc clusters
         if (!(ifc_length <= 32)) {
                 ifc_length = 32;
                 fat_length = mcdi->FATentries_per_cluster << 5;
         }
         // clear ifc clusters
         if (ifc_length > 0) {
                 j = 0;
                 do {
                         if (i >= mcdi->clusters_per_card)
                                 return sceMcResNoFormat;
                         do {
                                 if (mcman_writecluster(port, slot, i, 1) != 0)
                                         break;
                                 i++;
                         } while (i < mcdi->clusters_per_card);
                         if (i >= mcdi->clusters_per_card)
                                 return sceMcResNoFormat;
                         mcdi->ifc_list[j] = i;
                         j++;
                         i++;
                 } while (j < ifc_length);
         }
         // read ifc clusters to mc cache and clear fat clusters
         if (fat_length > 0) {
                 j = 0;
                 do {
                         ifc_index = j / mcdi->FATentries_per_cluster;
                         indirect_offset = j % mcdi->FATentries_per_cluster;
                         if (indirect_offset == 0) {
                                 if (McReadCluster(port, slot, mcdi->ifc_list[ifc_index], &mce) != sceMcResSucceed)
                                         return -42;
                                 mce->wr_flag = 1;
                         }
                         if (i >= mcdi->clusters_per_card)
                                 return sceMcResNoFormat;
                         do {
                                 r = mcman_writecluster(port, slot, i, 1);
                                 if (r == 1)
                                         break;
                                 if (r < 0)
                                         return -43;
                                 i++;
                         } while (i < mcdi->clusters_per_card);
                         if (i >= mcdi->clusters_per_card)
                                 return sceMcResNoFormat;
                         j++;
                         McFatCluster *fc = (McFatCluster *)mce->cl_data;
                         fc->entry[indirect_offset] = i;
                         i++;
                 } while (j < fat_length);
         }
         alloc_offset = i;
         mcdi->backup_block1 = 0;
         mcdi->backup_block2 = 0;
         // clear backup blocks
         for (i = (mcdi->clusters_per_card / mcdi->clusters_per_block) - 1; i > 0; i--) {
                 r = mcman_writecluster(port, slot, mcdi->clusters_per_block * i, 1);
                 if (r < 0)
                         return -44;
                 if ((r != 0) && (mcdi->backup_block1 == 0))
                         mcdi->backup_block1 = i;
                 else if ((r != 0) && (mcdi->backup_block2 == 0)) {
                         mcdi->backup_block2 = i;
                         break;
                 }
         }
         // set backup block2 to erased state
         if (mcman_eraseblock(port, slot, mcdi->backup_block2, NULL, NULL) != sceMcResSucceed)
                 return -45;
         u32 hi, lo, temp;
         long_multiply(mcdi->clusters_per_card, 0x10624dd3, &hi, &lo);
         temp = (hi >> 6) - (mcdi->clusters_per_card >> 31);
         allocatable_clusters_per_card = (((((temp << 5) - temp) << 2) + temp) << 3) + 1;
         j = alloc_offset;
         // checking for bad allocated clusters and building FAT
         if (j < i * mcdi->clusters_per_block) {
                 z = 0;
                 do { // quick check for bad clusters
                         r = mcman_writecluster(port, slot, j, 0);
                         if (r == 1) {
                                 if (z == 0) {
                                         mcdi->alloc_offset = j;
                                         mcdi->rootdir_cluster = 0;
                                         fat_entry = 0xffffffff; // marking rootdir end
                                 }
                                 else
                                         fat_entry = 0x7fffffff; // marking free cluster
                                 z++;
                                 if (z == allocatable_clusters_per_card)
                                         mcdi->max_allocatable_clusters = (j - mcdi->alloc_offset) + 1;
                         }
                         else {
                                 if (r != 0)
                                         return -45;
                                 fat_entry = 0xfffffffd; // marking bad cluster
                         }
                         if (McSetFATentry(port, slot, j - mcdi->alloc_offset, fat_entry) != sceMcResSucceed)
                                 return -46;
                         j++;
                 } while (j < (i * mcdi->clusters_per_block));
         }
         mcdi->alloc_end = (i * mcdi->clusters_per_block) - mcdi->alloc_offset;
         if (mcdi->max_allocatable_clusters == 0)
                 mcdi->max_allocatable_clusters = i * mcdi->clusters_per_block;
         if (z < mcdi->clusters_per_block)
                 return sceMcResNoFormat;
         // read superblock to mc cache
         for (i = 0; i < sizeof (MCDevInfo); i += MCMAN_CLUSTERSIZE) {
                 if (i < 0)
                         size = i + (MCMAN_CLUSTERSIZE - 1);
                 else
                         size = i;
                 if (McReadCluster(port, slot, size >> 10, &mce) != sceMcResSucceed)
                         return -48;
                 size = MCMAN_CLUSTERSIZE;
                 mce->wr_flag = 1;
                 if ((sizeof (MCDevInfo) - i) <= 1024)
                         size = sizeof (MCDevInfo) - i;
                 memcpy((void *)mce->cl_data, (void *)(mcdi + i), size);
         }
         mcdi->unknown1 = 0;
         mcdi->unknown2 = 0;
         mcdi->unknown5 = -1;
         mcdi->rootdir_cluster2 = mcdi->rootdir_cluster;
         // Create root dir
         if (McCreateDirentry(port, slot, 0, 0, 0, NULL) != sceMcResSucceed)
                 return -49;
         // finally flush cache to memcard
         r = McFlushCache(port, slot);
         if (r != sceMcResSucceed)
                 return r;
         mcdi->cardform = 1;
         return sceMcResSucceed;
 }
References MCDevInfo::alloc_end, MCDevInfo::alloc_offset, MCDevInfo::backup_block1, MCDevInfo::backup_block2, MCDevInfo::bad_block_list, MCDevInfo::blocksize, MCDevInfo::cardform, McCacheEntry::cl_data, MCDevInfo::cluster_size, MCDevInfo::clusters_per_block, MCDevInfo::clusters_per_card, DPRINTF, McFatCluster::entry, MCDevInfo::FATentries_per_cluster, MCDevInfo::ifc_list, long_multiply(), MCDevInfo::magic, MCDevInfo::max_allocatable_clusters, McCreateDirentry(), McFlushCache(), MCMAN_CLUSTERSIZE, mcman_devinfos, mcman_eraseblock(), mcman_reportBadBlocks(), mcman_wr_block, mcman_wr_flag3, mcman_wr_port, mcman_wr_slot, mcman_writecluster(), McReadCluster(), McSetFATentry(), memcpy(), memset(), NULL, MCDevInfo::rootdir_cluster, MCDevInfo::rootdir_cluster2, sceMcResChangedCard, sceMcResNoFormat, sceMcResSucceed, strcat(), strcpy(), SUPERBLOCK_MAGIC, SUPERBLOCK_VERSION, MCDevInfo::unknown1, MCDevInfo::unknown2, MCDevInfo::unknown5, MCDevInfo::version, and McCacheEntry::wr_flag.
Referenced by McFormat().
mcman_freecluster()
void mcman_freecluster (int port, int slot, int cluster)
Definition at line 3250 of file main.c.
 {
         register int i;
         McCacheEntry *mce = (McCacheEntry *)pmcman_entrycache;
         for (i = 0; i < MAX_CACHEENTRY; i++) {
                 if ((mce->mc_port == port) && (mce->mc_slot == slot) && (mce->cluster == cluster)) {
                         mce->cluster = -1;
                         mce->wr_flag = 0;
                 }
                 mce++;
         }
 }
References McCacheEntry::cluster, MAX_CACHEENTRY, McCacheEntry::mc_port, McCacheEntry::mc_slot, pmcman_entrycache, and McCacheEntry::wr_flag.
Referenced by mcman_checkBackupBlocks(), and mcman_FNC8ca4().
mcman_get1stcacheEntp()
McCacheEntry* mcman_get1stcacheEntp (void)
Definition at line 3279 of file main.c.
 {
         return *pmcman_mccache;
 }
References pmcman_mccache.
Referenced by mcman_cachePS1dirs(), mcman_clearPS1direntry(), mcman_close1(), mcman_fatWseek(), mcman_FNC8ca4(), mcman_open1(), mcman_open2(), and mcman_setinfo1().
mcman_getcacheentry()
McCacheEntry* mcman_getcacheentry (int port, int slot, int cluster)
Definition at line 3233 of file main.c.
 {
         register int i;
         McCacheEntry *mce = (McCacheEntry *)pmcman_entrycache;
         //DPRINTF("mcman: mcman_getcacheentry port%d slot%d cluster %x\n", port, slot, cluster);
         for (i = 0; i < MAX_CACHEENTRY; i++) {
                 if ((mce->mc_port == port) && (mce->mc_slot == slot) && (mce->cluster == cluster))
                         return mce;
                 mce++;
         }
         return NULL;
 }
References McCacheEntry::cluster, MAX_CACHEENTRY, McCacheEntry::mc_port, McCacheEntry::mc_slot, NULL, and pmcman_entrycache.
Referenced by mcman_readclusterPS1(), and McReadCluster().
mcman_getcnum()
int mcman_getcnum (int port, int slot)
Definition at line 1237 of file main.c.
 {
         return ((port & 1) << 3) + slot;
 }
Referenced by mcman_initPS2com(), and mcman_probePS2Card().
mcman_getdir1()
int mcman_getdir1 (int port, int slot, char * dirname, int flags, int maxent, sceMcTblGetDir * info)
Definition at line 547 of file ps1mc_fio.c.
 {
         register int r, i;
         char *p;
         McFsEntryPS1 *fse;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_getdir1 port%d slot%d dirname %s maxent %d flags %x\n", port, slot, dirname, maxent, flags);
 #endif
         flags &= 0xffff;
         i = 0;
         if (!flags) {
                 mcman_PS1curcluster = 0;
                 p = dirname;
                 do {
                         r = mcman_chrpos(p, '/');
                         if (r < 0)
                                 break;
                         p += mcman_chrpos(p, '/') + 1;
                 } while (1);
                 strncpy(mcman_PS1curdir, p, 63);
         }
         if (maxent) {
                 do {
                         if (mcman_PS1curcluster >= 15)
                                 break;
                         r = mcman_readdirentryPS1(port, slot, mcman_PS1curcluster, &fse);
                         if (r != sceMcResSucceed)
                                 return r;
                         mcman_PS1curcluster++;
                         if (fse->mode != 0x51)
                                 continue;
                         if (!mcman_checkdirpath(fse->name, mcman_PS1curdir))
                                 continue;
                         memset((void *)info, 0, sizeof (sceMcTblGetDir));
                         info->AttrFile = 0x9417;
                         if (fse->field_7e == 1)
                                 info->AttrFile = 0x9c17; //MC_ATTR_PDAEXEC set !!!
                         if (fse->field_7d == 1) {
                                 if ((fse->field_2c & sceMcFileAttrClosed) != 0) {
                                         info->AttrFile |= sceMcFileAttrClosed;
                                 }
                                 info->Reserve1 = fse->field_2e;
                                 info->_Create = fse->created;
                                 info->_Modify = fse->modified;
                                 info->FileSizeByte = fse->field_38;
                                 info->Reserve2 = fse->field_28;
                         }
                         else {
                                 info->FileSizeByte = fse->length;
                         }
                         strncpy((char*)info->EntryName, fse->name, 20);
                         info->EntryName[20] = 0;
                         i++;
                         info++;
                         maxent--;
                 } while (maxent);
         }
         return i;
 }
References McFsEntryPS1::created, DPRINTF, McFsEntryPS1::field_28, McFsEntryPS1::field_2c, McFsEntryPS1::field_2e, McFsEntryPS1::field_38, McFsEntryPS1::field_7d, McFsEntryPS1::field_7e, McFsEntryPS1::length, mcman_checkdirpath(), mcman_chrpos(), mcman_PS1curcluster, mcman_PS1curdir, mcman_readdirentryPS1(), memset(), McFsEntryPS1::mode, McFsEntryPS1::modified, McFsEntryPS1::name, sceMcFileAttrClosed, sceMcResSucceed, and strncpy().
Referenced by McGetDir().
mcman_getdir2()
int mcman_getdir2 (int port, int slot, char * dirname, int flags, int maxent, sceMcTblGetDir * info)
Definition at line 1141 of file ps2mc_fio.c.
 {
         register int r, pos, nument;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         McFsEntry *fse;
         char *p;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_getdir2 port%d slot%d dir=%s flags=%d maxent=%d\n", port, slot, dirname, flags, maxent);
 #endif
         nument = 0;
         flags &= 0xffff;
         if (!flags) {
                 p = mcman_curdirpath;
                 strncpy(p, dirname, 1023);
                 mcman_curdirpath[1023] = 0;
                 pos = -1;       // s1
                 p++;            //s0
                 do {
                         r = mcman_chrpos((void *)&p[pos], '/');
                         if (r < 0)
                                 break;
                         pos += 1 + r;
                 } while (1);
                 if (pos <= 0) {
                         if (pos == 0)
                                 *p = 0;
                         else
                                 p[-1] = 0;
                 }
                 else {
                         mcman_curdirpath[pos] = 0;
                 }
                 mcman_curdirname = &dirname[pos] + 1;
                 r = mcman_cachedirentry(port, slot, mcman_curdirpath, NULL, &fse, 1);
                 if (r > 0)
                         return sceMcResNoEntry;
                 if (r < 0)
                         return r;
                 if (!(fse->mode & sceMcFileAttrSubdir)) {
                         mcman_curdircluster = -1;
                         return sceMcResNoEntry;
                 }
                 mcman_curdircluster = fse->cluster;
                 mcman_curdirlength = fse->length;
                 if ((fse->cluster == mcdi->rootdir_cluster) && (fse->dir_entry == 0))
                         mcman_curdirmaxent = 2;
                 else
                         mcman_curdirmaxent = 0;
         }
         else {
                 if (mcman_curdircluster < 0)
                         return sceMcResNoEntry;
         }
         if (maxent != 0) {
                 do {
                         if (mcman_curdirmaxent >= mcman_curdirlength)
                                 break;
                         r = McReadDirEntry(port, slot, mcman_curdircluster, mcman_curdirmaxent, &fse);
                         if (r != sceMcResSucceed)
                                 return r;
                         mcman_curdirmaxent++;
                         if (!(fse->mode & sceMcFileAttrExists))
                                 continue;
                         if ((fse->mode & sceMcFileAttrHidden) && (!PS1CardFlag))
                                 continue;
                         if (!mcman_checkdirpath(fse->name, mcman_curdirname))
                                 continue;
                         mcman_wmemset((void *)info, sizeof (sceMcTblGetDir), 0);
                         if (mcman_curdirmaxent == 2) {
                                 r = McReadDirEntry(port, slot, mcman_curdircluster, 0, &fse);
                                 if (r != sceMcResSucceed)
                                         return r;
                                 r = McReadDirEntry(port, slot, fse->cluster, 0, &fse);
                                 if (r != sceMcResSucceed)
                                         return r;
                                 r = McReadDirEntry(port, slot, fse->cluster, fse->dir_entry, &fse);
                                 if (r != sceMcResSucceed)
                                         return r;
                                 info->EntryName[0] = '.';
                                 info->EntryName[1] = '.';
                                 info->EntryName[2] = '\0';
                         }
                         else if (mcman_curdirmaxent == 1) {
                                 r = McReadDirEntry(port, slot, mcman_curdircluster, 0, &fse);
                                 if (r != sceMcResSucceed)
                                         return r;
                                 r = McReadDirEntry(port, slot, fse->cluster, fse->dir_entry, &fse);
                                 if (r != sceMcResSucceed)
                                         return r;
                                 info->EntryName[0] = '.';
                                 info->EntryName[1] = '\0';
                         }
                         else {
                                 strncpy((char*)info->EntryName, fse->name, 32);
                         }
                         info->AttrFile = fse->mode;
                         info->Reserve1 = fse->unused;
                         info->_Create = fse->created;
                         info->_Modify = fse->modified;
                         if (!(fse->mode & sceMcFileAttrSubdir))
                                 info->FileSizeByte = fse->length;
                         nument++;
                         maxent--;
                         info++;
                 } while (maxent);
         }
         return nument;
 }
References McFsEntry::cluster, McFsEntry::created, McFsEntry::dir_entry, DPRINTF, McFsEntry::length, mcman_cachedirentry(), mcman_checkdirpath(), mcman_chrpos(), mcman_curdircluster, mcman_curdirlength, mcman_curdirmaxent, mcman_curdirname, mcman_curdirpath, mcman_devinfos, mcman_wmemset(), McReadDirEntry(), McFsEntry::mode, McFsEntry::modified, McFsEntry::name, NULL, pos, PS1CardFlag, MCDevInfo::rootdir_cluster, sceMcFileAttrExists, sceMcFileAttrHidden, sceMcFileAttrSubdir, sceMcResNoEntry, sceMcResSucceed, strncpy(), and McFsEntry::unused.
Referenced by McGetDir().
mcman_getdirinfo()
int mcman_getdirinfo (int port, int slot, McFsEntry * pfse, char * filename, McCacheDir * pcd, int unknown_flag)
Definition at line 1895 of file main.c.
 {
         register int i, r, ret, len, pos;
         McFsEntry *fse;
         u8 *pfsentry, *pfsee, *pfseend;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_getdirinfo port%d slot%d name %s\n", port, slot, filename);
 #endif
         pos = mcman_chrpos(filename, '/');
         if (pos < 0)
                 pos = strlen(filename);
         ret = 0;
         if ((pos == 2) && (!strncmp(filename, "..", 2))) {
                 r = McReadDirEntry(port, slot, pfse->cluster, 0, &fse);
                 if (r != sceMcResSucceed)
                         return r;
                 r = McReadDirEntry(port, slot, fse->cluster, 0, &fse);
                 if (r != sceMcResSucceed)
                         return r;
                 if (pcd) {
                         pcd->cluster = fse->cluster;
                         pcd->fsindex = fse->dir_entry;
                 }
                 r = McReadDirEntry(port, slot, fse->cluster, fse->dir_entry, &fse);
                 if (r != sceMcResSucceed)
                         return r;
                 pfsentry = (u8 *)fse;
                 pfsee = (u8 *)pfse;
                 pfseend = (u8 *)(pfsentry + sizeof(McFsEntry));
                 do {
                         *((u32 *)pfsee  ) = *((u32 *)pfsentry  );
                         *((u32 *)pfsee+1) = *((u32 *)pfsentry+1);
                         *((u32 *)pfsee+2) = *((u32 *)pfsentry+2);
                         *((u32 *)pfsee+3) = *((u32 *)pfsentry+3);
                         pfsentry += 16;
                         pfsee += 16;
                 } while (pfsentry < pfseend);
                 if ((fse->mode & sceMcFileAttrHidden) != 0) {
                         ret = 1;
                         if (!PS1CardFlag) {
                                 ret = 2;
                                 if ((pcd == NULL) || (pcd->maxent < 0))
                                         return 3;
                         }
                 }
                 if ((pcd == NULL) || (pcd->maxent < 0))
                         return sceMcResSucceed;
         }
         else {
                 if ((pos == 1) && (!strncmp(filename, ".", 1))) {
                         r = McReadDirEntry(port, slot, pfse->cluster, 0, &fse);
                         if (r != sceMcResSucceed)
                                 return r;
                         if (pcd) {
                                 pcd->cluster = fse->cluster;
                                 pcd->fsindex = fse->dir_entry;
                         }
                         if ((fse->mode & sceMcFileAttrHidden) != 0) {
                                 ret = 1;
                                 if (!PS1CardFlag) {
                                         ret = 2;
                                         if ((pcd == NULL) || (pcd->maxent < 0))
                                                 return 3;
                                 }
                                 else {
                                         if ((pcd == NULL) || (pcd->maxent < 0))
                                                 return sceMcResSucceed;
                                 }
                         }
                         else {
                                 ret = 1;
                                 if ((pcd == NULL) || (pcd->maxent < 0))
                                         return sceMcResSucceed;
                         }
                 }
         }
         if ((pcd) && (pcd->maxent >= 0))
                 pcd->maxent = pfse->length;
         if (pfse->length > 0) {
                 i = 0;
                 do {
                         r = McReadDirEntry(port, slot, pfse->cluster, i, &fse);
                         if (r != sceMcResSucceed)
                                 return r;
                         if (((fse->mode & sceMcFileAttrExists) == 0) && (pcd) && (i < pcd->maxent))
                                  pcd->maxent = i;
                         if (unknown_flag) {
                                 if ((fse->mode & sceMcFileAttrExists) == 0)
                                         continue;
                         }
                         else {
                                 if ((fse->mode & sceMcFileAttrExists) != 0)
                                         continue;
                         }
                         if (ret != 0)
                                 continue;
                         if ((pos >= 11) && (!strncmp(&filename[10], &fse->name[10], pos-10))) {
                                 len = pos;
                                 if (strlen(fse->name) >= pos)
                                         len = strlen(fse->name);
                                 if (!strncmp(filename, fse->name, len))
                                         goto continue_check;
                         }
                         if (strlen(fse->name) >= pos)
                                 len = strlen(fse->name);
                         else
                                 len = pos;
                         if (strncmp(filename, fse->name, len))
                                 continue;
 continue_check:
                         ret = 1;
                         if ((fse->mode & sceMcFileAttrHidden) != 0) {
                                 if (!PS1CardFlag)
                                         ret = 2;
                         }
                         if (pcd == NULL)
                                 break;
                         pcd->fsindex = i;
                         pcd->cluster = pfse->cluster;
                         if (pcd->maxent < 0)
                                 break;
                 } while (++i < pfse->length);
         }
         if (ret == 2)
                 return 2;
         return ((ret < 1) ? 1 : 0);
 }
References McFsEntry::cluster, McCacheDir::cluster, McFsEntry::dir_entry, DPRINTF, McCacheDir::fsindex, McFsEntry::length, McCacheDir::maxent, mcman_chrpos(), McReadDirEntry(), McFsEntry::mode, McFsEntry::name, NULL, pos, PS1CardFlag, sceMcFileAttrExists, sceMcFileAttrHidden, sceMcResSucceed, strlen(), and strncmp().
Referenced by mcman_cachedirentry(), and mcman_setinfo2().
mcman_getentspace()
int mcman_getentspace (int port, int slot, char * dirname)
Definition at line 1731 of file main.c.
 {
         register int r, i, entspace;
         McCacheDir cacheDir;
         McFsEntry *fse;
         McFsEntry mfe;
         u8 *pfsentry, *pmfe, *pfseend;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_getentspace port%d slot%d dirname %s\n", port, slot, dirname);
 #endif
         r = mcman_cachedirentry(port, slot, dirname, &cacheDir, &fse, 1);
         if (r > 0)
                 return sceMcResNoEntry;
         if (r < 0)
                 return r;
         pfsentry = (u8 *)fse;
         pmfe = (u8 *)&mfe;
         pfseend = (u8 *)(pfsentry + sizeof (McFsEntry));
         do {
                 *((u32 *)pmfe  ) = *((u32 *)pfsentry  );
                 *((u32 *)pmfe+1) = *((u32 *)pfsentry+1);
                 *((u32 *)pmfe+2) = *((u32 *)pfsentry+2);
                 *((u32 *)pmfe+3) = *((u32 *)pfsentry+3);
                 pfsentry += 16;
                 pmfe += 16;
         } while (pfsentry < pfseend);
         entspace = mfe.length & 1;
         for (i = 0; i < mfe.length; i++) {
                 r = McReadDirEntry(port, slot, mfe.cluster, i, &fse);
                 if (r != sceMcResSucceed)
                         return r;
                 if ((fse->mode & sceMcFileAttrExists) == 0)
                         entspace++;
         }
         return entspace;
 }
References McFsEntry::cluster, DPRINTF, McFsEntry::length, mcman_cachedirentry(), McReadDirEntry(), McFsEntry::mode, sceMcFileAttrExists, sceMcResNoEntry, and sceMcResSucceed.
Referenced by McGetEntSpace().
mcman_getFATindex()
int mcman_getFATindex (int port, int slot, int num)
Definition at line 3265 of file main.c.
 {
         return mcman_fatcache[port][slot].entry[num];
 }
References McFatCache::entry, and mcman_fatcache.
Referenced by mcman_open2().
mcman_getmcrtime()
int mcman_getmcrtime (sceMcStDateTime * time)
Definition at line 1107 of file main.c.
 {
         register int retries;
         sceCdCLOCK cdtime;
         retries = 64;
         do {
                 if (sceCdRC(&cdtime))
                         break;
         } while (--retries > 0);
         if (cdtime.stat & 0x80) {
                 time->Year = 2000;
                 time->Month = 3;
                 time->Day = 4;
                 time->Hour = 0;
                 time->Min = 0;
                 time->Sec = 0;
                 time->Resv2 = 0;
         }
         else {
                 time->Resv2 = 0;
                 time->Sec = btoi(cdtime.second);
                 time->Min = btoi(cdtime.minute);
                 time->Hour = btoi(cdtime.hour);
                 time->Day = btoi(cdtime.day);
                 if ((cdtime.month & 0x10) != 0) //Keep only valid bits: 0x1f (for month values 1-12 in BCD)
                         time->Month = (cdtime.month & 0xf) + 0xa;
                 else
                         time->Month = cdtime.month & 0xf;
                 time->Year = btoi(cdtime.year) + 2000;
         }
         return 0;
 }
References btoi, sceCdCLOCK::day, sceMcStDateTime::Day, sceCdCLOCK::hour, sceMcStDateTime::Hour, sceMcStDateTime::Min, sceCdCLOCK::minute, sceCdCLOCK::month, sceMcStDateTime::Month, sceMcStDateTime::Resv2, sceCdRC(), sceMcStDateTime::Sec, sceCdCLOCK::second, sceCdCLOCK::stat, sceCdCLOCK::year, and sceMcStDateTime::Year.
Referenced by McCreateDirentry(), mcman_close1(), mcman_close2(), and mcman_open2().
mcman_getPS1direntry()
int mcman_getPS1direntry (int port, int slot, char * filename, McFsEntryPS1 ** pfse, int flag)
Definition at line 2557 of file main.c.
 {
         register int r, i;
         char *p = filename;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_getPS1direntry port%d slot%d file %s flag %x\n", port, slot, filename, flag);
 #endif
         if (*p == '/')
                 p++;
         i = 0;
         do {
                 r = mcman_readdirentryPS1(port, slot, i, pfse);
                 if (r != sceMcResSucceed)
                         return r;
                 if (flag != 0) {
                         if (pfse[0]->mode != 0x51)
                                 continue;
                 }
                 else {
                         if (pfse[0]->mode != 0xa1)
                                 continue;
                 }
                 if (!strcmp(p, pfse[0]->name))
                         return i;
         } while (++i < 15);
         return sceMcResNoEntry;
 }
References DPRINTF, mcman_readdirentryPS1(), sceMcResNoEntry, sceMcResSucceed, and strcmp().
Referenced by mcman_delete1(), mcman_getstat1(), mcman_open1(), and mcman_setinfo1().
mcman_getstat()
int mcman_getstat (int port, int slot, char * filename, io_stat_t * stat)
Definition at line 955 of file main.c.
 {
         register int r;
         r = McDetectCard(port, slot);
         if (r != sceMcResSucceed)
                 return r;
         if (mcman_devinfos[port][slot].cardtype == sceMcTypePS2)
                 r = mcman_getstat2(port, slot, filename, stat);
         else
                 r = mcman_getstat1(port, slot, filename, stat);
         if (r < -9) {
                 mcman_invhandles(port, slot);
                 mcman_clearcache(port, slot);
         }
         return r;
 }
References McDetectCard(), mcman_clearcache(), mcman_devinfos, mcman_getstat1(), mcman_getstat2(), mcman_invhandles(), sceMcResSucceed, and sceMcTypePS2.
Referenced by mc_getstat().
mcman_getstat1()
int mcman_getstat1 (int port, int slot, char * filename, io_stat_t * stat)
Definition at line 409 of file ps1mc_fio.c.
 {
         register int r;
         McFsEntryPS1 *fse;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_getstat1 port%d slot%d filename %s\n", port, slot, filename);
 #endif
         r = mcman_getPS1direntry(port, slot, filename, &fse, 1);
         if ((fse->mode & 0xf0) == 0xa0)
                 r = -4;
         if (r < 0)
                 return sceMcResNoEntry;
         mcman_wmemset(stat, sizeof(io_stat_t), 0);
         stat->mode = 0x1f;
         if (fse->field_7d == 1) {
                 if ((fse->field_2c & sceMcFileAttrClosed) != 0)
                         stat->mode = 0x9f;
                 memcpy(stat->ctime, &fse->created, sizeof(sceMcStDateTime));
                 memcpy(stat->mtime, &fse->modified, sizeof(sceMcStDateTime));
                 stat->size = fse->field_38;
                 stat->attr = fse->field_28;
                 return sceMcResSucceed;
         }
         stat->size = fse->length;
         return sceMcResSucceed;
 }
References io_stat_t::attr, McFsEntryPS1::created, io_stat_t::ctime, DPRINTF, McFsEntryPS1::field_28, McFsEntryPS1::field_2c, McFsEntryPS1::field_38, McFsEntryPS1::field_7d, McFsEntryPS1::length, mcman_getPS1direntry(), mcman_wmemset(), memcpy(), io_stat_t::mode, McFsEntryPS1::mode, McFsEntryPS1::modified, io_stat_t::mtime, sceMcFileAttrClosed, sceMcResNoEntry, sceMcResSucceed, and io_stat_t::size.
Referenced by mcman_getstat().
mcman_getstat2()
int mcman_getstat2 (int port, int slot, char * filename, io_stat_t * stat)
Definition at line 334 of file ps2mc_fio.c.
 {
         register int r;
         McFsEntry *fse;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_getstat2 port%d slot%d filename %s\n", port, slot, filename);
 #endif
         r = mcman_cachedirentry(port, slot, filename, NULL, &fse, 1);
         if (r != sceMcResSucceed)
                 return r;
         mcman_wmemset((void *)stat, sizeof (io_stat_t), 0);
         if (fse->mode & sceMcFileAttrReadable)
                 stat->mode |= sceMcFileAttrReadable;
         if (fse->mode & sceMcFileAttrWriteable)
                 stat->mode |= sceMcFileAttrWriteable;
         if (fse->mode & sceMcFileAttrExecutable)
                 stat->mode |= sceMcFileAttrExecutable;
         if (fse->mode & sceMcFileAttrPS1)
                 stat->mode |= sceMcFileAttrPS1;
         if (fse->mode & sceMcFileAttrPDAExec)
                 stat->mode |= sceMcFileAttrPDAExec;
         if (fse->mode & sceMcFileAttrDupProhibit)
                 stat->mode |= sceMcFileAttrDupProhibit;
         if (fse->mode & sceMcFileAttrSubdir)
                 stat->mode |= sceMcFileAttrSubdir;
         else
                 stat->mode |= sceMcFileAttrFile;
         stat->attr = fse->attr;
         if (!(fse->mode & sceMcFileAttrSubdir))
                 stat->size = fse->length;
         memcpy(stat->ctime, &fse->created, sizeof(sceMcStDateTime));
         memcpy(stat->mtime, &fse->modified, sizeof(sceMcStDateTime));
         return sceMcResSucceed;
 }
References io_stat_t::attr, McFsEntry::attr, McFsEntry::created, io_stat_t::ctime, DPRINTF, McFsEntry::length, mcman_cachedirentry(), mcman_wmemset(), memcpy(), io_stat_t::mode, McFsEntry::mode, McFsEntry::modified, io_stat_t::mtime, NULL, sceMcFileAttrDupProhibit, sceMcFileAttrExecutable, sceMcFileAttrFile, sceMcFileAttrPDAExec, sceMcFileAttrPS1, sceMcFileAttrReadable, sceMcFileAttrSubdir, sceMcFileAttrWriteable, sceMcResSucceed, and io_stat_t::size.
Referenced by mcman_getstat().
mcman_initcache()
void mcman_initcache (void)
Definition at line 3139 of file main.c.
 {
         register int i, j;
         u8 *p;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_initcache\n");
 #endif
         j = MAX_CACHEENTRY - 1;
         p = (u8 *)mcman_cachebuf;
         for (i = 0; i < MAX_CACHEENTRY; i++) {
                 mcman_entrycache[i].cl_data = (u8 *)p;
                 mcman_mccache[i] = (McCacheEntry *)&mcman_entrycache[j - i];
                 mcman_entrycache[i].cluster = -1;
                 p += MCMAN_CLUSTERSIZE;
         }
         pmcman_entrycache = (McCacheEntry *)mcman_entrycache;
         pmcman_mccache = (McCacheEntry **)mcman_mccache;
         for (i = 0; i < MCMAN_MAXSLOT; i++) {
                 mcman_devinfos[0][i].unknown3 = -1;
                 mcman_devinfos[0][i].unknown4 = -1;
                 mcman_devinfos[0][i].unknown5 = -1;
                 mcman_devinfos[1][i].unknown3 = -1;
                 mcman_devinfos[1][i].unknown4 = -1;
                 mcman_devinfos[1][i].unknown5 = -1;
         }
         memset((void *)mcman_fatcache, -1, sizeof (mcman_fatcache));
         for (i = 0; i < MCMAN_MAXSLOT; i++) {
                 mcman_fatcache[0][i].entry[0] = 0;
                 mcman_fatcache[1][i].entry[0] = 0;
         }
 }
References McCacheEntry::cl_data, McCacheEntry::cluster, DPRINTF, McFatCache::entry, MAX_CACHEENTRY, mcman_cachebuf, MCMAN_CLUSTERSIZE, mcman_devinfos, mcman_entrycache, mcman_fatcache, MCMAN_MAXSLOT, mcman_mccache, memset(), pmcman_entrycache, pmcman_mccache, MCDevInfo::unknown3, MCDevInfo::unknown4, and MCDevInfo::unknown5.
Referenced by _start().
mcman_initdev()
int mcman_initdev (void)
Definition at line 189 of file mcdev.c.
 {
         iop_sema_t smp;
         SetCheckKelfPathCallback(mcman_modloadcb);
         DelDrv(mcman_mcdev.name);
         if (AddDrv(&mcman_mcdev)) {
                 McCloseAll();
                 return 1;
         }
         smp.attr = 1;
         smp.initial = 1;
         smp.max = 1;
         smp.option = 0;
         mcman_io_sema = CreateSema(&smp);
         return 0;
 }
References AddDrv(), iop_sema_t::attr, CreateSema(), DelDrv(), iop_sema_t::initial, iop_sema_t::max, McCloseAll(), mcman_io_sema, mcman_mcdev, mcman_modloadcb(), iop_device_t::name, iop_sema_t::option, and SetCheckKelfPathCallback().
Referenced by _start().
mcman_initPS1PDAcom()
void mcman_initPS1PDAcom (void)
Definition at line 311 of file mcsio2.c.
 {
         memset((void *)&mcman_sio2packet_PS1PDA, 0, sizeof (mcman_sio2packet_PS1PDA));
         mcman_sio2packet_PS1PDA.port_ctrl1[0] = 0xffc00505;
         mcman_sio2packet_PS1PDA.port_ctrl1[1] = 0xffc00505;
         mcman_sio2packet_PS1PDA.port_ctrl1[2] = 0xffc00505;
         mcman_sio2packet_PS1PDA.port_ctrl1[3] = 0xffc00505;
         mcman_sio2packet_PS1PDA.port_ctrl2[0] = 0x000201f4 & 0xfcffffff;
         mcman_sio2packet_PS1PDA.port_ctrl2[1] = 0x000201f4 & 0xfcffffff;
         mcman_sio2packet_PS1PDA.port_ctrl2[2] = 0x000201f4 & 0xfcffffff;
         mcman_sio2packet_PS1PDA.port_ctrl2[3] = 0x000201f4 & 0xfcffffff;
         mcman_sio2packet_PS1PDA.in = (u8 *)&mcman_sio2inbufs_PS1PDA;
         mcman_sio2packet_PS1PDA.out = (u8 *)&mcman_sio2outbufs_PS1PDA;
 }
References sio2_transfer_data_t::in, mcman_sio2inbufs_PS1PDA, mcman_sio2outbufs_PS1PDA, mcman_sio2packet_PS1PDA, memset(), sio2_transfer_data_t::out, sio2_transfer_data_t::port_ctrl1, and sio2_transfer_data_t::port_ctrl2.
Referenced by _start().
mcman_initPS2com()
void mcman_initPS2com (void)
Definition at line 283 of file mcsio2.c.
 {
         mcman_wmemset((void *)&mcman_sio2packet, sizeof (mcman_sio2packet), 0);
         mcman_sio2packet.port_ctrl1[2] = 0xff020405;
         mcman_sio2packet.port_ctrl1[3] = 0xff020405;
         mcman_sio2packet.port_ctrl2[2] = 0x0005ffff & 0xfcffffff;
         mcman_sio2packet.port_ctrl2[3] = 0x0005ffff & 0xfcffffff;
         mcman_sio2packet.in_dma.addr = &mcman_wdmabufs;
         mcman_sio2packet.in_dma.size = 0x24;
         mcman_sio2packet.out_dma.addr = &mcman_rdmabufs;
         mcman_sio2packet.out_dma.size = 0x24;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_initPS2com registering secrman_mc_command callback\n");
 #endif
         SecrSetMcCommandHandler((void *)secrman_mc_command);
 #ifdef DEBUG
         DPRINTF("mcman: mcman_initPS2com registering mcman_getcnum callback\n");
 #endif
         SecrSetMcDevIDHandler((void *)mcman_getcnum);
 }
References _sio2_dma_arg::addr, DPRINTF, sio2_transfer_data_t::in_dma, mcman_getcnum(), mcman_rdmabufs, mcman_sio2packet, mcman_wdmabufs, mcman_wmemset(), sio2_transfer_data_t::out_dma, sio2_transfer_data_t::port_ctrl1, sio2_transfer_data_t::port_ctrl2, secrman_mc_command(), SecrSetMcCommandHandler(), SecrSetMcDevIDHandler(), and _sio2_dma_arg::size.
Referenced by _start().
mcman_invhandles()
void mcman_invhandles (int port, int slot)
Definition at line 450 of file main.c.
 {
         register int i = 0;
         register MC_FHANDLE *fh = (MC_FHANDLE *)&mcman_fdhandles;
         do {
                 if ((fh->port == port) && (fh->slot == slot))
                         fh->status = 0;
                 fh++;
         } while (++i < MAX_FDHANDLES);
 }
References MAX_FDHANDLES, mcman_fdhandles, MC_FHANDLE::port, MC_FHANDLE::slot, and MC_FHANDLE::status.
Referenced by McChDir(), McClose(), McDelete(), McDetectCard2(), McFlush(), McFormat(), McGetDir(), McGetEntSpace(), mcman_detectcard(), mcman_dread(), mcman_format1(), mcman_getstat(), McOpen(), McRead(), McSetFileInfo(), McUnformat(), and McWrite().
mcman_ioerrcode()
int mcman_ioerrcode (int errcode)
Definition at line 75 of file mcdev.c.
 {
         register int r = errcode;
         if (r < 0) {
                 switch (r + 8) {
                         case 0:
                                 r = -EIO;
                                 break;
                         case 1:
                                 r = -EMFILE;
                                 break;
                         case 2:
                                 r = -EEXIST;
                                 break;
                         case 3:
                                 r = -EACCES;
                                 break;
                         case 4:
                                 r = -ENOENT;
                                 break;
                         case 5:
                                 r = -ENOSPC;
                                 break;
                         case 6:
                                 r = -EFORMAT;
                                 break;
                         default:
                                 r = -ENXIO;
                                 break;
                 }
         }
         return r;
 }
References EACCES, EEXIST, EFORMAT, EIO, EMFILE, ENOENT, ENOSPC, and ENXIO.
Referenced by mc_chstat(), mc_close(), mc_dclose(), mc_dopen(), mc_dread(), mc_format(), mc_getstat(), mc_lseek(), mc_mkdir(), mc_open(), mc_read(), mc_remove(), mc_rmdir(), and mc_write().
mcman_modloadcb()
int mcman_modloadcb (char * filename, int * port, int * slot)
Definition at line 111 of file mcdev.c.
 {
         register char *path = filename;
         register int   upos;
         if (*path == 0x20) {
                 path++;
                 while (*path == 0x20)
                         path++;
         }
         if (((u8)path[0] | 0x20) != mcman_mcdev.name[0])
                 return 0;
         if (((u8)path[1] | 0x20) != mcman_mcdev.name[1])
                 return 0;
         if ((u32)strlen(path) < 2) return 2;
         upos = mcman_chrpos(path, ':');
         if (upos < 0)
                 upos = strlen(path);
         if (port) {
                 upos --;
                 if (((u8)path[upos] - 0x30) < 10)
                         *port = (u8)path[upos] - 0x30;
                 else *port = 0;
         }
         upos--;
         *port += 2;
         if (slot) {
                 register int m, v;
                 *slot = 0;
                 for (m = 1; ((u8)path[upos --] - 0x30) < 10; m = v << 1) {
                         v = m << 2;
                         *slot += m * (path[upos] - 0x30);
                         v += m;
                 }
         }
         return 1;
 }
References mcman_chrpos(), mcman_mcdev, iop_device_t::name, and strlen().
Referenced by mcman_initdev().
mcman_open1()
int mcman_open1 (int port, int slot, char * filename, int flags)
Definition at line 86 of file ps1mc_fio.c.
 {
         register int r, i, fd = 0, cluster, temp;
         register MC_FHANDLE *fh = (MC_FHANDLE *)&mcman_fdhandles[fd];
         McFsEntryPS1 *fse; //sp18
         McCacheEntry *mce;
         char *p = filename;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_open1 port%d slot%d filename %s flags %x\n", port, slot, filename, flags);
 #endif
         if ((flags & sceMcFileCreateFile) != 0)
                 flags |= sceMcFileAttrWriteable;
         for (fd = 0; fd < MAX_FDHANDLES; fd++) {
                 fh = (MC_FHANDLE *)&mcman_fdhandles[fd];
                 if (fh->status == 0)
                         break;
         }
         if (fd == MAX_FDHANDLES)
                 return -7;
         mcman_wmemset((void *)fh, sizeof (MC_FHANDLE), 0);
         fh->port = port;
         fh->slot = slot;
         if (*p == '/')
                 p++;
         if ((*p == 0) || ((*p == '.') && (p[1] == 0))) {
                 fh->filesize = 15;
                 fh->drdflag = 1;
                 fh->status = 1;
                 return fd;
         }
         r = mcman_getPS1direntry(port, slot, p, &fse, 1);
         if ((fse->mode & 0xf0) == 0xa0)
                 r = -4;
         fh->freeclink = r;
         if (r >= 0) {
                 if (fse->field_7d == 1)
                         fh->filesize = fse->field_38;
                 else
                         fh->filesize = fse->length;
         }
         else
                 fh->filesize = 0;
         fh->rdflag = flags & sceMcFileAttrReadable;
         fh->wrflag = flags & sceMcFileAttrWriteable;
         fh->unknown1 = 0;
         if ((flags & sceMcFileCreateFile) == 0) {
                 if (r < 0)
                         return sceMcResNoEntry;
                 fh->status = 1;
                 return fd;
         }
         for (i = 0; i < MAX_FDHANDLES; i++) {
                 if ((mcman_fdhandles[i].status != 0) && \
                         (mcman_fdhandles[i].port == port) && (mcman_fdhandles[i].slot == slot) && \
                                 (mcman_fdhandles[i].freeclink == r) && (fh->wrflag != 0))
                         return sceMcResDeniedPermit;
         }
         if (r >= 0) {
                 r = mcman_clearPS1direntry(port, slot, r, 0);
                 if (r != sceMcResSucceed)
                         return r;
         }
         cluster = -1;
         for (i = 0; i < 15; i++) {
                 r = mcman_readdirentryPS1(port, slot, i, &fse);
                 if (r != sceMcResSucceed)
                         return r;
                 if ((fse->mode & 0xf0) == 0xa0) {
                         if (cluster < 0)
                                 cluster = i;
                         if (fse->mode != 0xa0) {
                                 mcman_wmemset((void *)fse, sizeof(McFsEntryPS1), 0);
                                 fse->mode = 0xa0;
                                 fse->linked_block = -1;
                                 fse->edc = mcman_calcEDC((void *)fse, 127);
                                 mce = mcman_get1stcacheEntp();
                                 if ((i + 1) < 0)
                                         temp = i + 8;
                                 else
                                         temp = i + 1;
                                 mce->wr_flag |= 1 << ((i + 1) - ((temp >> 3) << 3));
                         }
                 }
         }
         r = McFlushCache(port, slot);
         if (r != sceMcResSucceed)
                 return r;
         if (cluster < 0)
                 return sceMcResFullDevice;
         r = mcman_readdirentryPS1(port, slot, cluster, &fse);
         if (r != sceMcResSucceed)
                 return r;
         mcman_wmemset((void *)fse, sizeof(McFsEntryPS1), 0);
         fse->mode = 0x51;
         fse->length = 0;
         fse->linked_block = -1;
         strncpy(fse->name, p, 20);
         if ((flags & sceMcFileAttrPDAExec) != 0)
                 fse->field_7e = 1;
         fse->edc = mcman_calcEDC((void *)fse, 127);
         fh->freeclink = cluster;
         mce = mcman_get1stcacheEntp();
         if ((cluster + 1) < 0)
                 temp = cluster + 8;
         else
                 temp = cluster + 1;
         mce->wr_flag |= 1 << ((cluster + 1) - ((temp >> 3) << 3));
         r = McFlushCache(port, slot);
         if (r != sceMcResSucceed)
                 return r;
         fh->unknown2 = 1;
         fh->status = 1;
         return fd;
 }
References DPRINTF, MC_FHANDLE::drdflag, McFsEntryPS1::edc, McFsEntryPS1::field_38, McFsEntryPS1::field_7d, McFsEntryPS1::field_7e, MC_FHANDLE::filesize, MC_FHANDLE::freeclink, McFsEntryPS1::length, McFsEntryPS1::linked_block, MAX_FDHANDLES, McFlushCache(), mcman_calcEDC(), mcman_clearPS1direntry(), mcman_fdhandles, mcman_get1stcacheEntp(), mcman_getPS1direntry(), mcman_readdirentryPS1(), mcman_wmemset(), McFsEntryPS1::mode, McFsEntryPS1::name, MC_FHANDLE::port, MC_FHANDLE::rdflag, sceMcFileAttrPDAExec, sceMcFileAttrReadable, sceMcFileAttrWriteable, sceMcFileCreateFile, sceMcResDeniedPermit, sceMcResFullDevice, sceMcResNoEntry, sceMcResSucceed, MC_FHANDLE::slot, status, MC_FHANDLE::status, strncpy(), MC_FHANDLE::unknown1, MC_FHANDLE::unknown2, McCacheEntry::wr_flag, and MC_FHANDLE::wrflag.
Referenced by McOpen().
mcman_open2()
int mcman_open2 (int port, int slot, char * filename, int flags)
Definition at line 668 of file ps2mc_fio.c.
 {
         register int fd, i, r, fsindex, fsoffset, fat_index, rdflag, wrflag, pos, mcfree;
         register MC_FHANDLE *fh, *fh2;
         register MCDevInfo *mcdi;
         McCacheDir cacheDir;
         McFsEntry *fse1, *fse2;
         McCacheEntry *mce;
         u8 *pfsentry, *pcache, *pfseend;
         char *p;
         int fat_entry;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_open2 port%d slot%d name %s flags %x\n", port, slot, filename, flags);
 #endif
         if ((flags & sceMcFileCreateFile) != 0)
                 flags |= sceMcFileAttrWriteable; // s5
         //if (!mcman_checkpath(filename))
         //      return sceMcResNoEntry;
         if (filename[0] == 0)
                 return sceMcResNoEntry;
         fd = 0;
         do {
                 fh = (MC_FHANDLE *)&mcman_fdhandles[fd];
                 if (fh->status == 0)
                         break;
         } while (++fd < MAX_FDHANDLES);
         if (fd == MAX_FDHANDLES)
                 return sceMcResUpLimitHandle;
         fh = (MC_FHANDLE *)&mcman_fdhandles[fd]; // s2
         mcman_wmemset((void *)fh, sizeof (MC_FHANDLE), 0);
         mcdi = (MCDevInfo *)&mcman_devinfos[port][slot]; // s3
         if ((flags & (sceMcFileCreateFile | sceMcFileCreateDir)) == 0)
                 cacheDir.maxent = -1; //sp20
         else
                 cacheDir.maxent = 0;  //sp20
         //fse1 = sp28
         //sp18 = cacheDir
         fse1 = NULL;
         r = mcman_cachedirentry(port, slot, filename, &cacheDir, &fse1, 1);
         if (r < 0)
                 return r;
         if (fse1) {
                 pfsentry = (u8 *)fse1;
                 pcache = (u8 *)&mcman_dircache[1];
                 pfseend = (u8 *)(pfsentry + sizeof(McFsEntry));
                 do {
                         *((u32 *)pcache  ) = *((u32 *)pfsentry  );
                         *((u32 *)pcache+1) = *((u32 *)pfsentry+1);
                         *((u32 *)pcache+2) = *((u32 *)pfsentry+2);
                         *((u32 *)pcache+3) = *((u32 *)pfsentry+3);
                         pfsentry += 16;
                         pcache += 16;
                 } while (pfsentry < pfseend);
         }
         if ((flags == 0) && ((fse1->mode & sceMcFileAttrExists) == 0))
                 r = 1;
         if (r == 2)
                 return sceMcResNoEntry;
         if (r == 3)
                 return sceMcResDeniedPermit;
         if ((r == 0) && ((flags & sceMcFileCreateDir) != 0))
                 return sceMcResNoEntry;
         if ((r == 1) && ((flags & (sceMcFileCreateFile | sceMcFileCreateDir)) == 0))
                 return sceMcResNoEntry;
         rdflag = flags & sceMcFileAttrReadable;
         wrflag = flags & sceMcFileAttrWriteable;
         fh->freeclink = -1;
         fh->clink = -1;
         fh->clust_offset = 0;
         fh->filesize = 0;
         fh->position = 0;
         fh->port = port;
         fh->slot = slot;
         fh->unknown2 = 0;
         fh->rdflag = rdflag;
         fh->wrflag = wrflag;
         fh->unknown1 = 0;
         fh->field_20 = cacheDir.cluster;
         fh->field_24 = cacheDir.fsindex;
         // fse2 = sp2c
         if (r == 0) {
                 if ((wrflag != 0) && ((mcman_dircache[1].mode & sceMcFileAttrWriteable) == 0))
                         return sceMcResDeniedPermit;
                 if (!PS1CardFlag) {
                         if ((flags & sceMcFileAttrReadable) != 0) {
                                 if ((mcman_dircache[1].mode & sceMcFileAttrReadable) == 0)
                                         return sceMcResDeniedPermit;
                         }
                 }
                 r = McReadDirEntry(port, slot, cacheDir.cluster, 0, &fse2);
                 if (r != sceMcResSucceed)
                         return r;
                 fh->field_28 = fse2->cluster;
                 fh->field_2C = fse2->dir_entry;
                 if ((mcman_dircache[1].mode & sceMcFileAttrSubdir) != 0) {
                         if ((mcman_dircache[1].mode & sceMcFileAttrReadable) == 0)
                                 return sceMcResDeniedPermit;
                         fh->freeclink = mcman_dircache[1].cluster;
                         fh->rdflag = 0;
                         fh->wrflag = 0;
                         fh->unknown1 = 0;
                         fh->drdflag = 1;
                         fh->status = 1;
                         fh->filesize = mcman_dircache[1].length;
                         fh->clink = fh->freeclink;
                         return fd;
                 }
                 if ((flags & sceMcFileAttrWriteable) != 0) {
                         i = 0;
                         do {
                                 fh2 = (MC_FHANDLE *)&mcman_fdhandles[i];
                                 if ((fh2->status == 0) || (fh2->port != port) || (fh2->slot != slot) \
                                         || (fh2->field_20 != cacheDir.cluster) || (fh2->field_24 != cacheDir.fsindex))
                                         continue;
                                 if (fh2->wrflag != 0)
                                         return sceMcResDeniedPermit;
                         } while (++i < MAX_FDHANDLES);
                 }
                 if ((flags & sceMcFileCreateFile) != 0) {
                         r = McSetDirEntryState(port, slot, cacheDir.cluster, cacheDir.fsindex, 0);
                         McFlushCache(port, slot);
                         if (r != sceMcResSucceed)
                                 return -43;
                         if (cacheDir.fsindex < cacheDir.maxent)
                                 cacheDir.maxent = cacheDir.fsindex;
                 }
                 else {
                         fh->freeclink = mcman_dircache[1].cluster;
                         fh->filesize = mcman_dircache[1].length;
                         fh->clink = fh->freeclink;
                         if (fh->rdflag != 0)
                                 fh->rdflag = (*((u8 *)&mcman_dircache[1].mode)) & sceMcFileAttrReadable;
                         else
                                 fh->rdflag = 0;
                         if (fh->wrflag != 0)
                                 fh->wrflag = (mcman_dircache[1].mode >> 1) & sceMcFileAttrReadable;
                         else
                                 fh->wrflag = 0;
                         fh->status = 1;
                         return fd;
                 }
         }
         else {
                 fh->field_28 = cacheDir.cluster;
                 fh->field_2C = cacheDir.fsindex;
         }
         r = McReadDirEntry(port, slot, fh->field_28, fh->field_2C, &fse1);
         if (r != sceMcResSucceed)
                 return r;
         pfsentry = (u8 *)fse1;
         pcache = (u8 *)&mcman_dircache[2];
         pfseend = (u8 *)(pfsentry + sizeof(McFsEntry));
         do {
                 *((u32 *)pcache  ) = *((u32 *)pfsentry  );
                 *((u32 *)pcache+1) = *((u32 *)pfsentry+1);
                 *((u32 *)pcache+2) = *((u32 *)pfsentry+2);
                 *((u32 *)pcache+3) = *((u32 *)pfsentry+3);
                 pfsentry += 16;
                 pcache += 16;
         } while (pfsentry < pfseend);
         i = -1;
         if (mcman_dircache[2].length == cacheDir.maxent) {
                 fsindex = mcman_dircache[2].length / (mcdi->cluster_size >> 9); //v1
                 fsoffset = mcman_dircache[2].length % (mcdi->cluster_size >> 9); //v0
                 if (fsoffset == 0) {
                         fat_index = mcman_dircache[2].cluster;
                         i = fsindex;
                         if ((mcman_dircache[2].cluster == 0) && (i >= 2)) {
                                 if (mcman_getFATindex(port, slot, i - 1) >= 0) {
                                         fat_index = mcman_getFATindex(port, slot, i - 1); // s3
                                         i = 1;
                                 }
                         }
                         i--;
                         if (i != -1) {
                                 do {
                                         r = McGetFATentry(port, slot, fat_index, &fat_entry);
                                         if (r != sceMcResSucceed)
                                                 return r;
                                         if (fat_entry >= -1) {
                                                 r = mcman_findfree2(port, slot, 1);
                                                 if (r < 0)
                                                         return r;
                                                 fat_entry = r;
                                                 mce = mcman_get1stcacheEntp(); // s4
                                                 fat_entry |= 0x80000000;
                                                 r = McSetFATentry(port, slot, fat_index, fat_entry);
                                                 if (r != sceMcResSucceed)
                                                         return r;
                                                 mcman_addcacheentry(mce);
                                         }
                                         i--;
                                         fat_index = fat_entry & 0x7fffffff;
                                 } while (i != -1);
                         }
                 }
                 r = McFlushCache(port, slot);
                 if (r != sceMcResSucceed)
                         return r;
                 i = -1;
                 mcman_dircache[2].length++;
         }
         do {
                 p = filename + i + 1;
                 pos = i + 1;
                 r = mcman_chrpos(p, '/');
                 if (r < 0)
                         break;
                 i = pos + r;
         } while (1);
         p = filename + pos;
         mcfree = 0;
         if ((flags & sceMcFileCreateDir) != 0) {
                 r = mcman_findfree2(port, slot, 1); // r = s3
                 if (r < 0)
                         return r;
                 mcfree = r;
         }
         mce = mcman_get1stcacheEntp(); // mce = s4
         mcman_getmcrtime(&mcman_dircache[2].modified);
         r = McReadDirEntry(port, slot, mcman_dircache[2].cluster, cacheDir.maxent, &fse2);
         if (r != sceMcResSucceed)
                 return r;
         mcman_wmemset((void *)fse2, sizeof (McFsEntry), 0);
         strncpy(fse2->name, p, 32);
         fse2->created = mcman_dircache[2].modified;
         fse2->modified = mcman_dircache[2].modified;
         Mc1stCacheEntSetWrFlagOff();
         mcman_addcacheentry(mce);
         if (!PS1CardFlag)
                 flags &= 0xffffdfff;
         if ((flags & sceMcFileCreateDir) != 0) {
                 fse2->mode = ((flags & sceMcFileAttrHidden) | sceMcFileAttrReadable | sceMcFileAttrWriteable \
                                 | sceMcFileAttrExecutable | sceMcFileAttrSubdir | sceMcFile0400 | sceMcFileAttrExists) // 0x8427
                                         | (flags & (sceMcFileAttrPS1 | sceMcFileAttrPDAExec));
                 fse2->length = 2;
                 fse2->cluster = mcfree;
                 r = McCreateDirentry(port, slot, mcman_dircache[2].cluster, cacheDir.maxent, mcfree, (sceMcStDateTime *)&fse2->created);
                 if (r != sceMcResSucceed)
                         return -46;
                 r = McReadDirEntry(port, slot, fh->field_28, fh->field_2C, &fse1);
                 if (r != sceMcResSucceed)
                         return r;
                 pfsentry = (u8 *)fse1;
                 pcache = (u8 *)&mcman_dircache[2];
                 pfseend = (u8 *)(pfsentry + sizeof(McFsEntry));
                 do {
                         *((u32 *)pfsentry  ) = *((u32 *)pcache  );
                         *((u32 *)pfsentry+1) = *((u32 *)pcache+1);
                         *((u32 *)pfsentry+2) = *((u32 *)pcache+2);
                         *((u32 *)pfsentry+3) = *((u32 *)pcache+3);
                         pfsentry += 16;
                         pcache += 16;
                 } while (pfsentry < pfseend);
                 Mc1stCacheEntSetWrFlagOff();
                 r = McFlushCache(port, slot);
                 if (r != sceMcResSucceed)
                         return r;
                 return sceMcResSucceed;
         }
         else {
                 fse2->mode = ((flags & sceMcFileAttrHidden) | sceMcFileAttrReadable | sceMcFileAttrWriteable \
                                 | sceMcFileAttrExecutable | sceMcFileAttrFile | sceMcFile0400 | sceMcFileAttrExists) // 0x8417
                                         | (flags & (sceMcFileAttrPS1 | sceMcFileAttrPDAExec));
                 fse2->cluster = -1;
                 fh->field_20 = mcman_dircache[2].cluster;
                 fh->status = 1;
                 fh->field_24 = cacheDir.maxent;
                 r = McReadDirEntry(port, slot, fh->field_28, fh->field_2C, &fse1);
                 if (r != sceMcResSucceed)
                         return r;
                 pfsentry = (u8 *)fse1;
                 pcache = (u8 *)&mcman_dircache[2];
                 pfseend = (u8 *)(pfsentry + sizeof(McFsEntry));
                 do {
                         *((u32 *)pfsentry  ) = *((u32 *)pcache  );
                         *((u32 *)pfsentry+1) = *((u32 *)pcache+1);
                         *((u32 *)pfsentry+2) = *((u32 *)pcache+2);
                         *((u32 *)pfsentry+3) = *((u32 *)pcache+3);
                         pfsentry += 16;
                         pcache += 16;
                 } while (pfsentry < pfseend);
                 Mc1stCacheEntSetWrFlagOff();
                 r = McFlushCache(port, slot);
                 if (r != sceMcResSucceed)
                         return r;
         }
         return fd;
 }
References MC_FHANDLE::clink, MC_FHANDLE::clust_offset, McFsEntry::cluster, McCacheDir::cluster, MCDevInfo::cluster_size, McFsEntry::created, McFsEntry::dir_entry, DPRINTF, MC_FHANDLE::drdflag, MC_FHANDLE::field_20, MC_FHANDLE::field_24, MC_FHANDLE::field_28, MC_FHANDLE::field_2C, MC_FHANDLE::filesize, MC_FHANDLE::freeclink, McCacheDir::fsindex, McFsEntry::length, MAX_FDHANDLES, McCacheDir::maxent, Mc1stCacheEntSetWrFlagOff(), McCreateDirentry(), McFlushCache(), McGetFATentry(), mcman_addcacheentry(), mcman_cachedirentry(), mcman_chrpos(), mcman_devinfos, mcman_dircache, mcman_fdhandles, mcman_findfree2(), mcman_get1stcacheEntp(), mcman_getFATindex(), mcman_getmcrtime(), mcman_wmemset(), McReadDirEntry(), McSetDirEntryState(), McSetFATentry(), McFsEntry::mode, McFsEntry::modified, McFsEntry::name, NULL, MC_FHANDLE::port, pos, MC_FHANDLE::position, PS1CardFlag, MC_FHANDLE::rdflag, sceMcFile0400, sceMcFileAttrExecutable, sceMcFileAttrExists, sceMcFileAttrFile, sceMcFileAttrHidden, sceMcFileAttrPDAExec, sceMcFileAttrPS1, sceMcFileAttrReadable, sceMcFileAttrSubdir, sceMcFileAttrWriteable, sceMcFileCreateDir, sceMcFileCreateFile, sceMcResDeniedPermit, sceMcResNoEntry, sceMcResSucceed, sceMcResUpLimitHandle, MC_FHANDLE::slot, MC_FHANDLE::status, strncpy(), MC_FHANDLE::unknown1, MC_FHANDLE::unknown2, and MC_FHANDLE::wrflag.
Referenced by McOpen().
mcman_probePDACard()
int mcman_probePDACard (int port, int slot)
Definition at line 964 of file mcsio2.c.
 {
         register int retries;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_probePDACard port%d slot%d\n", port, slot);
 #endif
         mcman_sio2packet_PS1PDA.regdata[0] = 0;
         mcman_sio2packet_PS1PDA.regdata[0] = (port & 3) | 0x00140540;
         mcman_sio2packet_PS1PDA.in_size = 5;
         mcman_sio2packet_PS1PDA.out_size = 5;
         mcman_sio2packet_PS1PDA.regdata[1] = 0;
         mcman_sio2inbufs_PS1PDA[0] = 0x81;
         mcman_sio2inbufs_PS1PDA[1] = 0x58;
         retries = 0;
         do {
                 mcman_sio2transfer(port, slot, &mcman_sio2packet_PS1PDA);
                 if ((mcman_sio2packet_PS1PDA.stat6c & 0xf000) == 0x1000)
                                 break;
         } while (++retries < 5);
         if (retries >= 5)
                 return -11;
         return sceMcResSucceed;
 }
References DPRINTF, sio2_transfer_data_t::in_size, mcman_sio2inbufs_PS1PDA, mcman_sio2packet_PS1PDA, mcman_sio2transfer, sio2_transfer_data_t::out_size, sio2_transfer_data_t::regdata, sceMcResSucceed, and sio2_transfer_data_t::stat6c.
Referenced by McDetectCard2(), and mcman_detectcard().
mcman_probePS1Card()
int mcman_probePS1Card (int port, int slot)
Definition at line 893 of file mcsio2.c.
 {
         register int i, r, retries;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         u32 *p;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_probePS1Card port%d slot%d\n", port, slot);
 #endif
         mcman_sio2packet_PS1PDA.regdata[0] = 0;
         mcman_sio2packet_PS1PDA.regdata[0] = (((port & 1) + 2)) | 0x000c0340;
         mcman_sio2packet_PS1PDA.in_size = 3;
         mcman_sio2packet_PS1PDA.out_size = 3;
         mcman_sio2packet_PS1PDA.regdata[1] = 0;
         mcman_sio2inbufs_PS1PDA[0] = 0x81;
         mcman_sio2inbufs_PS1PDA[1] = 0x52;
         retries = 0;
         do {
                 mcman_timercount = (u32)(GetTimerCounter(timer_ID) - mcman_timercount);
                 u32 hi, lo;
                 long_multiply(mcman_timercount, 0x3e0f83e1, &hi, &lo);
                 if ((u32)((hi >> 3) < mcman_timerthick))
                         DelayThread(mcman_timerthick - (hi >> 3));
                 mcman_sio2transfer(port, slot, &mcman_sio2packet_PS1PDA);
                 mcman_timercount = GetTimerCounter(timer_ID);
                 mcman_timerthick = 0;
                 if (((mcman_sio2packet_PS1PDA.stat6c & 0xf000) == 0x1000) \
                                 && (mcman_sio2outbufs_PS1PDA[2] == 0x5a)) {
                         break;
                 }
         } while (++retries < 5);
         if (retries >= 5)
                 return -11;
         if (mcman_sio2outbufs_PS1PDA[1] == 0) {
                 if (mcdi->cardform != 0)
                         return sceMcResSucceed;
         }
         else if (mcman_sio2outbufs_PS1PDA[1] != 8) {
                 return -12;
         }
         mcman_clearcache(port, slot);
         p = (u32 *)&mcman_sio2outbufs_PS1PDA[124];
         for (i = 31; i >= 0; i--)
                 *p-- = 0;
         r = McWritePS1PDACard(port, slot, 63, mcman_sio2outbufs_PS1PDA);
         if (r < 0)
                 return -13;
         r = mcman_setPS1devinfos(port, slot);
         if (r == 0)
                 return sceMcResChangedCard;
         mcdi->cardform = r;
         return r;
 }
References MCDevInfo::cardform, DelayThread(), DPRINTF, GetTimerCounter(), sio2_transfer_data_t::in_size, long_multiply(), mcman_clearcache(), mcman_devinfos, mcman_setPS1devinfos(), mcman_sio2inbufs_PS1PDA, mcman_sio2outbufs_PS1PDA, mcman_sio2packet_PS1PDA, mcman_sio2transfer, mcman_timercount, mcman_timerthick, McWritePS1PDACard(), sio2_transfer_data_t::out_size, sio2_transfer_data_t::regdata, sceMcResChangedCard, sceMcResSucceed, sio2_transfer_data_t::stat6c, and timer_ID.
Referenced by McDetectCard2().
mcman_probePS1Card2()
int mcman_probePS1Card2 (int port, int slot)
Definition at line 837 of file mcsio2.c.
 {
         register int retries;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
 #ifdef DEBUG
         DPRINTF("mcman: mcman_probePS1Card2 port%d slot%d\n", port, slot);
 #endif
         mcman_sio2packet_PS1PDA.regdata[0] = 0;
         mcman_sio2packet_PS1PDA.regdata[0] = (((port & 1) + 2)) | 0x000c0340;
         mcman_sio2packet_PS1PDA.in_size = 3;
         mcman_sio2packet_PS1PDA.out_size = 3;
         mcman_sio2packet_PS1PDA.regdata[1] = 0;
         mcman_sio2inbufs_PS1PDA[0] = 0x81;
         mcman_sio2inbufs_PS1PDA[1] = 0x52;
         retries = 0;
         do {
                 mcman_timercount = (u32)(GetTimerCounter(timer_ID) - mcman_timercount);
                 u32 hi, lo;
                 long_multiply(mcman_timercount, 0x3e0f83e1, &hi, &lo);
                 if ((u32)((hi >> 3) < mcman_timerthick))
                         DelayThread(mcman_timerthick - (hi >> 3));
                 mcman_sio2transfer(port, slot, &mcman_sio2packet_PS1PDA);
                 mcman_timercount = GetTimerCounter(timer_ID);
                 mcman_timerthick = 0;
                 if (((mcman_sio2packet_PS1PDA.stat6c & 0xf000) == 0x1000) \
                                 && (mcman_sio2outbufs_PS1PDA[2] == 0x5a)) {
                         break;
                 }
         } while (++retries < 5);
         if (retries >= 5)
                 return -12;
         if (mcman_sio2outbufs_PS1PDA[1] == 0) {
                 if (mcdi->cardform > 0)
                         return sceMcResSucceed;
                 if (mcdi->cardform < 0)
                         return sceMcResNoFormat;
         }
         else if (mcman_sio2outbufs_PS1PDA[1] != 8) {
                 return -14;
         }
         return -13;
 }
References MCDevInfo::cardform, DelayThread(), DPRINTF, GetTimerCounter(), sio2_transfer_data_t::in_size, long_multiply(), mcman_devinfos, mcman_sio2inbufs_PS1PDA, mcman_sio2outbufs_PS1PDA, mcman_sio2packet_PS1PDA, mcman_sio2transfer, mcman_timercount, mcman_timerthick, sio2_transfer_data_t::out_size, sio2_transfer_data_t::regdata, sceMcResNoFormat, sceMcResSucceed, sio2_transfer_data_t::stat6c, and timer_ID.
Referenced by mcman_detectcard(), and mcman_flushcacheentry().
mcman_probePS2Card()
int mcman_probePS2Card (int port, int slot)
Definition at line 730 of file mcsio2.c.
 {
         register int retries, r;
         register MCDevInfo *mcdi;
         u8 *p = mcman_sio2packet.out_dma.addr;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_probePS2Card sio2cmd port%d slot%d\n", port, slot);
 #endif
         r = mcman_cardchanged(port, slot);
         if (r == sceMcResSucceed) {
                 r = McGetFormat(port, slot);
                 if (r != 0) {
 #ifdef DEBUG
                         DPRINTF("mcman: mcman_probePS2Card sio2cmd succeeded\n");
 #endif
                         return sceMcResSucceed;
                 }
         }
         if (mcman_resetauth(port, slot) != sceMcResSucceed) {
 #ifdef DEBUG
                 DPRINTF("mcman: mcman_probePS2Card sio2cmd failed (auth reset failed)\n");
 #endif
                 return sceMcResFailResetAuth;
         }
         if (SecrAuthCard(port + 2, slot, mcman_getcnum(port, slot)) == 0) {
 #ifdef DEBUG
                 DPRINTF("mcman: mcman_probePS2Card sio2cmd failed (auth failed)\n");
 #endif
                 return sceMcResFailAuth;
         }
         retries = 0;
         do {
                 sio2packet_add(port, slot, 0xffffffff, NULL);
                 sio2packet_add(port, slot, 0x09, NULL);
                 sio2packet_add(port, slot, 0xfffffffe, NULL);
                 mcman_sio2transfer(port, slot, &mcman_sio2packet);
                 if (((mcman_sio2packet.stat6c & 0xF000) == 0x1000) && (p[4] != 0x66))
                         break;
         } while (++retries < 5);
         if (retries >= 5) {
 #ifdef DEBUG
                 DPRINTF("mcman: mcman_probePS2Card sio2cmd failed (mc detection failed)\n");
 #endif
                 return sceMcResFailDetect;
         }
         mcman_clearcache(port, slot);
         sio2packet_add(port, slot, 0xffffffff, NULL);
         sio2packet_add(port, slot, 0x08, NULL);
         sio2packet_add(port, slot, 0xfffffffe, NULL);
         retries = 0;
     do {
                 mcman_sio2transfer(port, slot, &mcman_sio2packet);
         if ((mcman_sio2packet.stat6c & 0xF000) != 0x1000)
                 continue;
         if (p[4] == 0x5a)
                 break;
         } while (++retries < 5);
         if (retries >= 5) {
 #ifdef DEBUG
                 DPRINTF("mcman: mcman_probePS2Card sio2cmd failed (mc detection failed)\n");
 #endif
                 return sceMcResFailDetect2;
         }
         r = mcman_setdevinfos(port, slot);
         if (r == 0) {
 #ifdef DEBUG
                 DPRINTF("mcman: mcman_probePS2Card sio2cmd card changed!\n");
 #endif
                 return sceMcResChangedCard;
         }
         if (r != sceMcResNoFormat) {
 #ifdef DEBUG
                 DPRINTF("mcman: mcman_probePS2Card sio2cmd failed (mc detection failed)\n");
 #endif
                 return sceMcResFailDetect2;
         }
         mcdi = &mcman_devinfos[port][slot];
         mcdi->cardform = r;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_probePS2Card sio2cmd succeeded\n");
 #endif
         return r;
 }
References _sio2_dma_arg::addr, MCDevInfo::cardform, DPRINTF, McGetFormat(), mcman_cardchanged(), mcman_clearcache(), mcman_devinfos, mcman_getcnum(), mcman_resetauth(), mcman_setdevinfos(), mcman_sio2packet, mcman_sio2transfer, NULL, sio2_transfer_data_t::out_dma, sceMcResChangedCard, sceMcResFailAuth, sceMcResFailDetect, sceMcResFailDetect2, sceMcResFailResetAuth, sceMcResNoFormat, sceMcResSucceed, SecrAuthCard(), sio2packet_add(), and sio2_transfer_data_t::stat6c.
Referenced by McDetectCard2().
mcman_probePS2Card2()
int mcman_probePS2Card2 (int port, int slot)
Definition at line 678 of file mcsio2.c.
 {
         register int retries, r;
         u8 *p = mcman_sio2packet.out_dma.addr;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_probePS2Card2 sio2cmd port%d slot%d\n", port, slot);
 #endif
         retries = 0;
         do {
                 sio2packet_add(port, slot, 0xffffffff, NULL);
                 sio2packet_add(port, slot, 0x09, NULL);
                 sio2packet_add(port, slot, 0xfffffffe, NULL);
                 mcman_sio2transfer(port, slot, &mcman_sio2packet);
                 if (((mcman_sio2packet.stat6c & 0xF000) == 0x1000) && (p[4] != 0x66))
                         break;
         } while (++retries < 5);
         if (retries >= 5)
                 return sceMcResFailDetect;
         if (p[3] == 0x5a) {
                 r = McGetFormat(port, slot);
                 if (r > 0) {
 #ifdef DEBUG
                         DPRINTF("mcman: mcman_probePS2Card2 succeeded\n");
 #endif
                         return sceMcResSucceed;
                 }
                 r = McGetFormat(port, slot);
                 if (r < 0) {
 #ifdef DEBUG
                         DPRINTF("mcman: mcman_probePS2Card2 sio2cmd failed (no format)\n");
 #endif
                         return sceMcResNoFormat;
                 }
         }
 #ifdef DEBUG
         DPRINTF("mcman: mcman_probePS2Card2 sio2cmd failed (mc detection failed)\n");
 #endif
         return sceMcResFailDetect2;
 }
References _sio2_dma_arg::addr, DPRINTF, McGetFormat(), mcman_sio2packet, mcman_sio2transfer, NULL, sio2_transfer_data_t::out_dma, sceMcResFailDetect, sceMcResFailDetect2, sceMcResNoFormat, sceMcResSucceed, sio2packet_add(), and sio2_transfer_data_t::stat6c.
Referenced by McCheckBlock(), and mcman_detectcard().
mcman_PS1pagetest()
int mcman_PS1pagetest (int port, int slot, int page)
Definition at line 2937 of file main.c.
 {
         register int r, i;
         for (i = 0; i < 32; i++)
                 mcman_PS1PDApagebuf.word[i] = 0xffffffff;
         r = McWritePS1PDACard(port, slot, page, &mcman_PS1PDApagebuf);
         if (r != sceMcResSucceed)
                 return sceMcResDeniedPermit;
         r = McReadPS1PDACard(port, slot, page, &mcman_PS1PDApagebuf);
         if (r != sceMcResSucceed)
                 return sceMcResNotEmpty;
         for (i = 0; i < 32; i++) {
                 if (mcman_PS1PDApagebuf.word[i] != 0xffffffff) {
                         return 0;
                 }
         }
         for (i = 0; i < 32; i++)
                 mcman_PS1PDApagebuf.word[i] = 0;
         r = McWritePS1PDACard(port, slot, page, &mcman_PS1PDApagebuf);
         if (r != sceMcResSucceed)
                 return sceMcResDeniedPermit;
         r = McReadPS1PDACard(port, slot, page, &mcman_PS1PDApagebuf);
         if (r != sceMcResSucceed)
                 return sceMcResNotEmpty;
         for (i = 0; i < 32; i++) {
                 if (mcman_PS1PDApagebuf.word[i] != 0) {
                         return 0;
                 }
         }
         return 1;
 }
References McReadPS1PDACard(), McWritePS1PDACard(), sceMcResDeniedPermit, sceMcResNotEmpty, sceMcResSucceed, and mcman_PS1PDApagebuf::word.
Referenced by mcman_format1().
mcman_read1()
int mcman_read1 (int fd, void * buffer, int nbyte)
Definition at line 239 of file ps1mc_fio.c.
 {
         register int r, size, temp, rpos, offset, maxsize;
         register MC_FHANDLE *fh = (MC_FHANDLE *)&mcman_fdhandles[fd];
         McCacheEntry *mce;
         u8 *p = (u8 *)buffer;
         if (fh->position >= fh->filesize)
                 return 0;
         if (nbyte >= (fh->filesize - fh->position))
                 nbyte = fh->filesize - fh->position;
         rpos = 0;
         if (nbyte) {
                 do {
                         if (fh->position < 0)
                                 temp = fh->position + 0x3ff;
                         else
                                 temp = fh->position;
                         offset = (fh->position - ((temp >> 10) << 10));
                         maxsize = MCMAN_CLUSTERSIZE - offset;
                         if (maxsize < nbyte)
                                 size = maxsize;
                         else
                                 size = nbyte;
                         r = mcman_fatRseekPS1(fd);
                         if (r < 0)
                                 return r;
                         r = mcman_readclusterPS1(fh->port, fh->slot, r, &mce);
                         if (r != sceMcResSucceed)
                                 return r;
                         memcpy(&p[rpos], (void *)(mce->cl_data + offset), size);
                         rpos += size;
                         nbyte -= size;
                         fh->position += size;
                 } while (nbyte);
         }
         return rpos;
 }
References buffer, McCacheEntry::cl_data, MC_FHANDLE::filesize, MCMAN_CLUSTERSIZE, mcman_fatRseekPS1(), mcman_fdhandles, mcman_readclusterPS1(), memcpy(), MC_FHANDLE::port, MC_FHANDLE::position, sceMcResSucceed, and MC_FHANDLE::slot.
Referenced by McRead().
mcman_read2()
int mcman_read2 (int fd, void * buffer, int nbyte)
Definition at line 494 of file ps2mc_fio.c.
 {
         register int r, temp, rpos, size, offset;
         register MC_FHANDLE *fh = (MC_FHANDLE *)&mcman_fdhandles[fd];
         register MCDevInfo *mcdi = &mcman_devinfos[fh->port][fh->slot];
         McCacheEntry *mce;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_read2 fd %d buf %x size %d\n", fd, (int)buffer, nbyte);
 #endif
         if (fh->position < fh->filesize) {
                 temp = fh->filesize - fh->position;
                 if (nbyte > temp)
                         nbyte = temp;
                 rpos = 0;
                 if (nbyte > 0) {
                         do {
                                 offset = fh->position % mcdi->cluster_size;  // file pointer offset % cluster size
                                 temp = mcdi->cluster_size - offset;
                                 if (temp < nbyte)
                                         size = temp;
                                 else
                                         size = nbyte;
                                 r = mcman_fatRseek(fd);
                                 if (r <= 0)
                                         return r;
                                 r = McReadCluster(fh->port, fh->slot, r, &mce);
                                 if (r != sceMcResSucceed)
                                         return r;
                                 memcpy((void *)(buffer + rpos), (void *)(mce->cl_data + offset), size);
                                 rpos += size;
                                 mce->rd_flag = 1;
                                 nbyte -= size;
                                 fh->position += size;
                         } while (nbyte);
                 }
                 return rpos;
         }
         return 0;
 }
References buffer, McCacheEntry::cl_data, MCDevInfo::cluster_size, DPRINTF, MC_FHANDLE::filesize, mcman_devinfos, mcman_fatRseek(), mcman_fdhandles, McReadCluster(), memcpy(), MC_FHANDLE::port, MC_FHANDLE::position, McCacheEntry::rd_flag, sceMcResSucceed, and MC_FHANDLE::slot.
Referenced by McRead().
mcman_readclusterPS1()
int mcman_readclusterPS1 (int port, int slot, int cluster, McCacheEntry ** pmce)
Definition at line 3861 of file main.c.
 {
         register int r, i, pages_per_fatclust;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         McCacheEntry *mce;
         mce = mcman_getcacheentry(port, slot, cluster);
         if (mce == NULL) {
                 mce = pmcman_mccache[MAX_CACHEENTRY - 1];
                 if (mce->wr_flag != 0) {
                         r = mcman_flushcacheentry((McCacheEntry *)mce);
                         if (r != sceMcResSucceed)
                                 return r;
                 }
                 mce->mc_port = port;
                 mce->mc_slot = slot;
                 mce->cluster = cluster;
                 pages_per_fatclust = MCMAN_CLUSTERSIZE / mcdi->pagesize;
                 for (i = 0; i < pages_per_fatclust; i++) {
                         r = McReadPS1PDACard(port, slot, cluster + i, (void *)(mce->cl_data + (i * mcdi->pagesize)));
                         if (r != sceMcResSucceed)
                                 return -21;
                 }
         }
         mcman_addcacheentry(mce);
         *pmce = (McCacheEntry *)mce;
         return sceMcResSucceed;
 }
References McCacheEntry::cl_data, McCacheEntry::cluster, MAX_CACHEENTRY, McCacheEntry::mc_port, McCacheEntry::mc_slot, mcman_addcacheentry(), MCMAN_CLUSTERSIZE, mcman_devinfos, mcman_flushcacheentry(), mcman_getcacheentry(), McReadPS1PDACard(), NULL, MCDevInfo::pagesize, pmcman_mccache, sceMcResSucceed, and McCacheEntry::wr_flag.
Referenced by mcman_FNC8ca4(), mcman_read1(), mcman_readdirentryPS1(), and mcman_write1().
mcman_readdirentryPS1()
int mcman_readdirentryPS1 (int port, int slot, int cluster, McFsEntryPS1 ** pfse)
Definition at line 3768 of file main.c.
 {
         register int r, offset, index, pages_per_fatclust;
         McCacheEntry *mce;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         if (cluster >= 15)
                 return -73;
         pages_per_fatclust = MCMAN_CLUSTERSIZE / mcdi->pagesize;
         cluster++;
         index = cluster / pages_per_fatclust;
         offset = cluster % pages_per_fatclust;
         r = mcman_readclusterPS1(port, slot, index * pages_per_fatclust, &mce);
         if (r != sceMcResSucceed)
                 return -74;
         *pfse = (void *)&mce->cl_data[offset << 7];
         if (sio2man_type >= XSIO2MAN) {
                 McFsEntryPS1 *fse = (McFsEntryPS1 *)*pfse; // <--- XMCMAN seems to work with this
                 fse->field_7d = 0;                                                 //
         }
         return sceMcResSucceed;
 }
References McCacheEntry::cl_data, McFsEntryPS1::field_7d, index(), MCMAN_CLUSTERSIZE, mcman_devinfos, mcman_readclusterPS1(), MCDevInfo::pagesize, sceMcResSucceed, sio2man_type, and XSIO2MAN.
Referenced by mcman_cachePS1dirs(), mcman_clearPS1direntry(), mcman_close1(), mcman_dread1(), mcman_fatRseekPS1(), mcman_fatWseekPS1(), mcman_findfree1(), mcman_FNC8ca4(), mcman_getdir1(), mcman_getPS1direntry(), and mcman_open1().
mcman_readpage()
int mcman_readpage (int port, int slot, int page, void * buf, void * eccbuf)
Definition at line 525 of file mcsio2.c.
 {
         register int index, count, retries, r, i;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         u8 *pbuf = (u8 *)buf;
         u8 *pecc = (u8 *)eccbuf;
         u8 *p = mcman_sio2packet.out_dma.addr;
         count = (mcdi->pagesize + 127) >> 7;
         retries = 0;
         do {
                 if (retries > 0)
                         mcman_cardchanged(port, slot);
                 sio2packet_add(port, slot, 0xffffffff, NULL);
                 sio2packet_add(port, slot, 0x04, (u8 *)&page);
                 if (count > 0) {
                         index = 0;
                 while (index < count) {
                         sio2packet_add(port, slot, 0x0b, NULL);
                         index++;
                 }
                 }
                 if (mcdi->cardflags & CF_USE_ECC) // if memcard have ECC support
                         sio2packet_add(port, slot, 0x0f, NULL);
                 sio2packet_add(port, slot, 0x0c, NULL);
                 sio2packet_add(port, slot, 0xfffffffe, NULL);
                 mcman_sio2transfer(port, slot, &mcman_sio2packet);
                 if (((mcman_sio2packet.stat6c & 0xF000) != 0x1000)
                         || (p[8] != 0x5a)
                                 || (p[0x94 + 0x2cf] != 0x5a))
                         continue;
                 if (count > 0) {
                         index = 0;
                         while (index < count) {
                                 // checking EDC
                                 r = mcman_calcEDC(&p[0x94 + ((index + (index << 3)) << 4)], 128) & 0xFF;
                                 if (r != p[0x94 + 128 + ((index + (index << 3)) << 4)])
                                         break;
                         index++;
                         }
                         if (index < count)
                                 continue;
                         index = 0;
                         while (index < count) {
                         for (i=0; i<128; i++)
                                 pbuf[(index << 7) + i] = p[0x94 + ((index + (index << 3)) << 4) + i];
                         index++;
                         }
                 }
                 memcpy(pecc, &p[0x94 + ((count + (count << 3)) << 4)] , mcman_sparesize(port, slot));
                 break;
         } while (++retries < 5);
         if (retries < 5)
                 return sceMcResSucceed;
         return sceMcResChangedCard;
 }
References _sio2_dma_arg::addr, MCDevInfo::cardflags, CF_USE_ECC, index(), mcman_calcEDC(), mcman_cardchanged(), mcman_devinfos, mcman_sio2packet, mcman_sio2transfer, mcman_sparesize(), memcpy(), NULL, sio2_transfer_data_t::out_dma, MCDevInfo::pagesize, sceMcResChangedCard, sceMcResSucceed, sio2packet_add(), and sio2_transfer_data_t::stat6c.
Referenced by McCheckBlock(), and McReadPage().
mcman_replaceBackupBlock()
int mcman_replaceBackupBlock (int port, int slot, int block)
Definition at line 3897 of file main.c.
 {
         register int i;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         if (mcman_badblock > 0)
                 return sceMcResFailReplace;
         for (i = 0; i < 16; i++) {
                 if (mcdi->bad_block_list[i] == -1)
                         break;
         }
         if (i < 16) {
                 if ((mcdi->alloc_end - mcdi->max_allocatable_clusters) < 8)
                         return sceMcResFullDevice;
                 mcdi->alloc_end -= 8;
                 mcdi->bad_block_list[i] = block;
                 mcman_badblock_port = port;
                 mcman_badblock_slot = slot;
                 mcman_badblock = -1;
                 return (mcdi->alloc_offset + mcdi->alloc_end) / mcdi->clusters_per_block;
         }
         return sceMcResFullDevice;
 }
References MCDevInfo::alloc_end, MCDevInfo::alloc_offset, MCDevInfo::bad_block_list, MCDevInfo::clusters_per_block, MCDevInfo::max_allocatable_clusters, mcman_badblock, mcman_badblock_port, mcman_badblock_slot, mcman_devinfos, sceMcResFailReplace, and sceMcResFullDevice.
Referenced by mcman_flushcacheentry().
mcman_reportBadBlocks()
int mcman_reportBadBlocks (int port, int slot)
Definition at line 1418 of file main.c.
 {
         register int r, i, block, bad_blocks, page, erase_byte, err_cnt, err_limit;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         u8 *p;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_reportBadBlocks port%d, slot%d\n", port, slot);
 #endif
         mcman_wmemset((void *)mcdi->bad_block_list, 128, -1);
         if ((mcdi->cardflags & CF_BAD_BLOCK) == 0)
                 return sceMcResSucceed;
         err_limit = (((mcdi->pagesize << 16) >> 16) + ((mcdi->pagesize << 16) >> 31)) >> 1; //s7
         erase_byte = 0;
         if ((mcdi->cardflags & CF_ERASE_ZEROES) != 0)
                 erase_byte = 0xff;
         bad_blocks = 0; // s2
         if ((mcdi->clusters_per_card / mcdi->clusters_per_block) > 0) {
                 block = 0; // s1
                 do {
                         if (bad_blocks >= 16)
                                 break;
                         err_cnt = 0;    //s4
                         page = 0; //s3
                         do {
                                 r = McReadPage(port, slot, (block * mcdi->blocksize) + page, &mcman_pagebuf);
                                 if (r == sceMcResNoFormat) {
                                         mcdi->bad_block_list[bad_blocks] = block;
                                         bad_blocks++;
                                         break;
                                 }
                                 if (r != sceMcResSucceed)
                                         return r;
                                 if ((mcdi->cardflags & CF_USE_ECC) == 0) {
                                         p = mcman_pagebuf.byte;
                                         for (i = 0; i < mcdi->pagesize; i++) {
                                                 // check if the content of page is clean
                                                 if (*p++ != erase_byte)
                                                         err_cnt++;
                                                 if (err_cnt >= err_limit) {
                                                         mcdi->bad_block_list[bad_blocks] = block;
                                                         bad_blocks++;
                                                         break;
                                                 }
                                         }
                                 }
                         } while (++page < 2);
                 } while (++block < (mcdi->clusters_per_card / mcdi->clusters_per_block));
         }
         return sceMcResSucceed;
 }
References MCDevInfo::bad_block_list, MCDevInfo::blocksize, mcman_pagebuf::byte, MCDevInfo::cardflags, CF_BAD_BLOCK, CF_ERASE_ZEROES, CF_USE_ECC, MCDevInfo::clusters_per_block, MCDevInfo::clusters_per_card, DPRINTF, mcman_devinfos, mcman_wmemset(), McReadPage(), MCDevInfo::pagesize, sceMcResNoFormat, and sceMcResSucceed.
Referenced by mcman_format2().
mcman_resetauth()
int mcman_resetauth (int port, int slot)
Definition at line 640 of file mcsio2.c.
 {
         register int retries;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_resetauth sio2cmd port%d slot%d\n", port, slot);
 #endif
         sio2packet_add(port, slot, 0xffffffff, NULL);
         sio2packet_add(port, slot, 0x11, NULL);
         sio2packet_add(port, slot, 0xfffffffe, NULL);
         retries = 0;
         do {
                 mcman_sio2transfer(port, slot, &mcman_sio2packet);
                 if ((mcman_sio2packet.stat6c & 0xF000) == 0x1000)
                         break;
         } while (++retries < 5);
         if (retries >= 5) {
 #ifdef DEBUG
                 DPRINTF("mcman: mcman_resetauth sio2cmd card changed!\n");
 #endif
                 return sceMcResChangedCard;
         }
 #ifdef DEBUG
         DPRINTF("mcman: mcman_resetauth sio2cmd succeeded\n");
 #endif
         return sceMcResSucceed;
 }
References DPRINTF, mcman_sio2packet, mcman_sio2transfer, NULL, sceMcResChangedCard, sceMcResSucceed, sio2packet_add(), and sio2_transfer_data_t::stat6c.
Referenced by mcman_probePS2Card().
mcman_setdevinfos()
int mcman_setdevinfos (int port, int slot)
Definition at line 1323 of file main.c.
 {
         register int r, allocatable_clusters_per_card, iscluster_valid, current_allocatable_cluster, cluster_cnt;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         McFsEntry *pfse;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_setdevinfos port%d slot%d\n", port, slot);
 #endif
         mcman_wmemset((void *)mcdi, sizeof(MCDevInfo), 0);
         r = mcman_setdevspec(port, slot);
         if (r != sceMcResSucceed)
                 return -49;
         r = McReadPage(port, slot, 0, &mcman_pagebuf);
         if (r == sceMcResNoFormat)
                 return sceMcResNoFormat; // should rebuild a valid superblock here
         if (r != sceMcResSucceed)
                 return -48;
         if (strncmp(SUPERBLOCK_MAGIC, mcman_pagebuf.magic, 28) != 0) {
 #ifdef DEBUG
                 DPRINTF("mcman: mcman_setdevinfos No card format !!!\n");
 #endif
                 return sceMcResNoFormat;
         }
         if (((mcman_pagebuf.byte[28] - 48) == 1) && ((mcman_pagebuf.byte[30] - 48) == 0))  // check ver major & minor
                 return sceMcResNoFormat;
         u8 *p = (u8 *)mcdi;
         for (r=0; r<0x150; r++)
                 p[r] = mcman_pagebuf.byte[r];
         mcdi->cardtype = sceMcTypePS2; // <--
         r = mcman_checkBackupBlocks(port, slot);
         if (r != sceMcResSucceed)
                 return -47;
         r = McReadDirEntry(port, slot, 0, 0, &pfse);
         if (r != sceMcResSucceed)
                 return sceMcResNoFormat; // -46
         if (strcmp(pfse->name, ".") != 0)
                 return sceMcResNoFormat;
         if (McReadDirEntry(port, slot, 0, 1, &pfse) != sceMcResSucceed)
                 return -45;
         if (strcmp(pfse->name, "..") != 0)
                 return sceMcResNoFormat;
         mcdi->cardform = 1;
 //      mcdi->cardtype = sceMcTypePS2;
         if (((mcman_pagebuf.byte[28] - 48) == 1) && ((mcman_pagebuf.byte[30] - 48) == 1)) {  // check ver major & minor
                 if ((mcdi->clusters_per_block * mcdi->backup_block2) == mcdi->alloc_end)
                         mcdi->alloc_end = (mcdi->clusters_per_block * mcdi->backup_block2) - mcdi->alloc_offset;
         }
         u32 hi, lo, temp;
         long_multiply(mcdi->clusters_per_card, 0x10624dd3, &hi, &lo);
         temp = (hi >> 6) - (mcdi->clusters_per_card >> 31);
         allocatable_clusters_per_card = (((((temp << 5) - temp) << 2) + temp) << 3) + 1;
         iscluster_valid = 0;
         cluster_cnt = 0;
         current_allocatable_cluster = mcdi->alloc_offset;
         while (cluster_cnt < allocatable_clusters_per_card) {
                 if (current_allocatable_cluster >= mcdi->clusters_per_card)
                         break;
                 if (((current_allocatable_cluster % mcdi->clusters_per_block) == 0) \
                         || (mcdi->alloc_offset == current_allocatable_cluster)) {
                         iscluster_valid = 1;
                         for (r=0; r<16; r++) {
                                 if ((current_allocatable_cluster / mcdi->clusters_per_block) == mcdi->bad_block_list[r])
                                         iscluster_valid = 0;
                         }
                 }
                 if (iscluster_valid == 1)
                         cluster_cnt++;
                 current_allocatable_cluster++;
         }
         mcdi->max_allocatable_clusters = current_allocatable_cluster - mcdi->alloc_offset;
         return sceMcResSucceed;
 }
References MCDevInfo::alloc_end, MCDevInfo::alloc_offset, MCDevInfo::backup_block2, MCDevInfo::bad_block_list, mcman_pagebuf::byte, MCDevInfo::cardform, MCDevInfo::cardtype, MCDevInfo::clusters_per_block, MCDevInfo::clusters_per_card, DPRINTF, long_multiply(), mcman_pagebuf::magic, MCDevInfo::max_allocatable_clusters, mcman_checkBackupBlocks(), mcman_devinfos, mcman_setdevspec(), mcman_wmemset(), McReadDirEntry(), McReadPage(), McFsEntry::name, sceMcResNoFormat, sceMcResSucceed, sceMcTypePS2, strcmp(), strncmp(), and SUPERBLOCK_MAGIC.
Referenced by mcman_probePS2Card().
mcman_setdevspec()
int mcman_setdevspec (int port, int slot)
Definition at line 1296 of file main.c.
 {
         int cardsize;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
 #ifdef DEBUG
         DPRINTF("mcman: mcman_setdevspec port%d, slot%d\n", port, slot);
 #endif
         if (McGetCardSpec(port, slot, &mcdi->pagesize, &mcdi->blocksize, &cardsize, &mcdi->cardflags) != sceMcResSucceed)
                 return sceMcResFullDevice;
         mcdi->pages_per_cluster = MCMAN_CLUSTERSIZE / mcdi->pagesize;
         mcdi->cluster_size = MCMAN_CLUSTERSIZE;
         mcdi->unknown1 = 0;
         mcdi->unknown2 = 0;
         mcdi->unused = 0xff00;
         mcdi->FATentries_per_cluster = MCMAN_CLUSTERFATENTRIES;
         mcdi->unknown5 = -1;
         mcdi->rootdir_cluster2 = mcdi->rootdir_cluster;
         mcdi->clusters_per_block = mcdi->blocksize / mcdi->pages_per_cluster;
         mcdi->clusters_per_card = (cardsize / mcdi->blocksize) * (mcdi->blocksize / mcdi->pages_per_cluster);
         return sceMcResSucceed;
 }
References MCDevInfo::blocksize, MCDevInfo::cardflags, MCDevInfo::cluster_size, MCDevInfo::clusters_per_block, MCDevInfo::clusters_per_card, DPRINTF, MCDevInfo::FATentries_per_cluster, McGetCardSpec(), MCMAN_CLUSTERFATENTRIES, MCMAN_CLUSTERSIZE, mcman_devinfos, MCDevInfo::pages_per_cluster, MCDevInfo::pagesize, MCDevInfo::rootdir_cluster, MCDevInfo::rootdir_cluster2, sceMcResFullDevice, sceMcResSucceed, MCDevInfo::unknown1, MCDevInfo::unknown2, MCDevInfo::unknown5, and MCDevInfo::unused.
Referenced by mcman_setdevinfos().
mcman_setinfo1()
int mcman_setinfo1 (int port, int slot, char * filename, sceMcTblGetDir * info, int flags)
Definition at line 450 of file ps1mc_fio.c.
 {
         register int r, temp, ret;
         McFsEntryPS1 *fse1, *fse2;
         McCacheEntry *mce;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_setinfo1 port%d slot%d filename %s flags %x\n", port, slot, filename, flags);
 #endif
         ret = 0;
         if (sio2man_type >= XSIO2MAN) {
                 if ((flags & sceMcFileAttrFile) != 0) {
                         r = mcman_getPS1direntry(port, slot, (char*)info->EntryName, &fse1, 1);
                         if (r < 0) {
                                 if (r != sceMcResNoEntry) {
                                         ret = r;
                                 }
                                 else {
                                         if ((!strcmp(".", (char*)info->EntryName)) || (!strcmp("..", (char*)info->EntryName)) || (info->EntryName[0] == 0))
                                                 ret = sceMcResNoEntry;
                                 }
                         }
                 }
         }
         r = mcman_getPS1direntry(port, slot, filename, &fse2, 1);
         if ((fse2->mode & 0xf0) == 0)
                 r = sceMcResNoEntry;
         if (r < 0)
                 return r;
         if (sio2man_type >= XSIO2MAN) {
                 if (ret != sceMcResSucceed)
                         return sceMcResNoEntry;
         }
         mce = mcman_get1stcacheEntp();
         temp = r + 1;
         if ((r + 1) < 0)
                 temp = r + 8;
         mce->wr_flag |= 1 << ((r + 1) - ((temp >> 3) << 3));
         if (sio2man_type >= XSIO2MAN) {
                 fse2->field_7d = 0;
                 fse2->field_2c = 0;
                 flags &= -12;
         }
         else {
                 if(fse2->field_7d != 1) {
                         fse2->field_7d = 1;
                         fse2->field_38 = fse2->length;
                 }
         }
         if ((flags & sceMcFileAttrExecutable) != 0) {
                 if ((info->AttrFile & sceMcFileAttrPDAExec) != 0)
                         fse2->field_7e = 1;
                 else
                         fse2->field_7e = 0;
         }
         //Special fix clause for file managers (like uLaunchELF)
         //This allows writing most entries that can be read by mcGetDir
         //and without usual restrictions. This flags value should cause no conflict
         //as Sony code never uses it, and the value is changed after its use here.
         //This is primarily needed for PS2 MC backups, but must be implemented here
         //too since the 'flags' argument may be used indiscriminately for both
         if(flags == 0xFEED){
                 flags = sceMcFileAttrReadable|sceMcFileAttrWriteable;
                 //The changed flags value allows more entries to be copied below
         }
         if ((flags & sceMcFileAttrDupProhibit) != 0)
                 fse2->field_28 = info->Reserve2;
         if ((flags & sceMcFileAttrReadable) != 0)
                 fse2->created = info->_Create;
         if ((flags & sceMcFileAttrWriteable) != 0)
                 fse2->modified = info->_Modify;
         if ((flags & sceMcFileAttrFile) != 0)
                 strncpy(fse2->name, (char*)info->EntryName, 20);
         fse2->field_1e = 0;
         r = McFlushCache(port, slot);
         return r;
 }
References McFsEntryPS1::created, DPRINTF, McFsEntryPS1::field_1e, McFsEntryPS1::field_28, McFsEntryPS1::field_2c, McFsEntryPS1::field_38, McFsEntryPS1::field_7d, McFsEntryPS1::field_7e, McFsEntryPS1::length, McFlushCache(), mcman_get1stcacheEntp(), mcman_getPS1direntry(), McFsEntryPS1::mode, McFsEntryPS1::modified, McFsEntryPS1::name, sceMcFileAttrDupProhibit, sceMcFileAttrExecutable, sceMcFileAttrFile, sceMcFileAttrPDAExec, sceMcFileAttrReadable, sceMcFileAttrWriteable, sceMcResNoEntry, sceMcResSucceed, sio2man_type, strcmp(), strncpy(), McCacheEntry::wr_flag, and XSIO2MAN.
Referenced by McSetFileInfo().
mcman_setinfo2()
int mcman_setinfo2 (int port, int slot, char * filename, sceMcTblGetDir * info, int flags)
Definition at line 378 of file ps2mc_fio.c.
 {
         register int r, fmode;
         McFsEntry *fse;
         McCacheDir dirInfo;
         McFsEntry mfe;
         u8 *pfsentry, *pfseend, *mfee;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_setinfo2 port%d slot%d filename %s flags %x\n", port, slot, filename, flags);
 #endif
         r = mcman_cachedirentry(port, slot, filename, &dirInfo, &fse, 1); //dirInfo=sp218 fse=sp228
         if (r != sceMcResSucceed)
                 return r;
         if ((flags & sceMcFileAttrFile) != 0)   {
                 if ((!strcmp(".", (char*)info->EntryName)) || (!strcmp("..", (char*)info->EntryName)))
                         return sceMcResNoEntry;
                 if (info->EntryName[0] == 0)
                         return sceMcResNoEntry;
                 r = mcman_chrpos((char*)info->EntryName, '/');
                 if (r >= 0)
                         return sceMcResNoEntry;
                 if (dirInfo.fsindex < 2)
                         return sceMcResNoEntry;
                 r = McReadDirEntry(port, slot, dirInfo.cluster, 0, &fse);
                 if (r != sceMcResSucceed)
                         return r;
                 r = McReadDirEntry(port, slot, fse->cluster, fse->dir_entry, &fse);
                 if (r != sceMcResSucceed)
                         return r;
                 pfsentry = (u8 *)fse;
                 mfee = (u8 *)&mfe;
                 pfseend = (u8 *)(pfsentry + sizeof (McFsEntry));
                 do {
                         *((u32 *)mfee  ) = *((u32 *)pfsentry  );
                         *((u32 *)mfee+1) = *((u32 *)pfsentry+1);
                         *((u32 *)mfee+2) = *((u32 *)pfsentry+2);
                         *((u32 *)mfee+3) = *((u32 *)pfsentry+3);
                         pfsentry += 16;
                         mfee += 16;
                 } while (pfsentry < pfseend);
                 r = mcman_getdirinfo(port, slot, &mfe, (char*)info->EntryName, NULL, 1);
                 if (r != 1) {
                         if (r < 2) {
                                 if (r == 0)
                                         return sceMcResNoEntry;
                                 return r;
                         }
                         else {
                                 if (r != 2)
                                         return r;
                                 return sceMcResDeniedPermit;
                         }
                 }
         }
         r = McReadDirEntry(port, slot, dirInfo.cluster, dirInfo.fsindex, &fse);
         if (r != sceMcResSucceed)
                 return r;
         Mc1stCacheEntSetWrFlagOff();
         //Special fix clause for file managers (like uLaunchELF)
         //This allows writing most entries that can be read by mcGetDir
         //and without usual restrictions. This flags value should cause no conflict
         //as Sony code never uses it, and the value is changed after its use here.
         if(flags == 0xFEED){
                 fse->mode = info->AttrFile;
                 //fse->unused = info->Reserve1;
                 //fse->length = info->FileSizeByte;
                 flags = sceMcFileAttrReadable|sceMcFileAttrWriteable;
                 //The changed flags value allows more entries to be copied below
         }
         if ((flags & sceMcFileAttrDupProhibit) != 0)
                 fse->attr = info->Reserve2;
         if ((flags & sceMcFileAttrExecutable) != 0) {
                 fmode = 0xffff7fcf;
                 if (!PS1CardFlag)
                         fmode = 0x180f;
                 fse->mode = (fse->mode & ~fmode) | (info->AttrFile & fmode);
         }
         if ((flags & sceMcFileCreateFile) != 0) {
                 fmode = 0x380f;
                 if (!PS1CardFlag)
                         fmode = 0x180f;
                 fse->mode = (fse->mode & ~fmode) | (info->AttrFile & fmode);
         }
         if ((flags & sceMcFileAttrReadable) != 0)
                 fse->created = info->_Create;
         if ((flags & sceMcFileAttrWriteable) != 0)
                 fse->modified = info->_Modify;
         if ((flags & sceMcFileAttrFile) != 0) {
                 strncpy(fse->name, (char*)info->EntryName, 32);
                 fse->name[31] = 0;
         }
         return sceMcResSucceed;
 }
References McFsEntry::attr, McFsEntry::cluster, McCacheDir::cluster, McFsEntry::created, McFsEntry::dir_entry, DPRINTF, McCacheDir::fsindex, Mc1stCacheEntSetWrFlagOff(), mcman_cachedirentry(), mcman_chrpos(), mcman_getdirinfo(), McReadDirEntry(), McFsEntry::mode, McFsEntry::modified, McFsEntry::name, NULL, PS1CardFlag, sceMcFileAttrDupProhibit, sceMcFileAttrExecutable, sceMcFileAttrFile, sceMcFileAttrReadable, sceMcFileAttrWriteable, sceMcFileCreateFile, sceMcResDeniedPermit, sceMcResNoEntry, sceMcResSucceed, strcmp(), and strncpy().
Referenced by McSetFileInfo().
mcman_setPS1devinfos()
int mcman_setPS1devinfos (int port, int slot)
Definition at line 2500 of file main.c.
 {
         register int r, i;
         MCDevInfo *mcdi = &mcman_devinfos[port][slot];
 #ifdef DEBUG
         DPRINTF("mcman: mcman_setPS1devinfos port%d slot%d\n", port, slot);
 #endif
         memset((void *)mcdi, 0, sizeof (MCDevInfo));
         memset((void *)&mcdi->bad_block_list[0], -1, 128);
         mcdi->pagesize = 128;
         mcdi->blocksize = 128;
         mcdi->pages_per_cluster = 64;
         mcdi->unused = 0xff00;
         mcdi->cluster_size = 8192;
         mcdi->FATentries_per_cluster = 2048;
         mcdi->clusters_per_card = 16;
         mcdi->clusters_per_block = 0;
         mcdi->cardform = 0;
         mcdi->cardtype = 1;
         r = McReadPS1PDACard(port, slot, 0, &mcman_PS1PDApagebuf);
         if (r < 0)
                 return -14;
         if (mcman_sio2outbufs_PS1PDA[1] != 0)
                 return -15;
         if (mcman_PS1PDApagebuf.byte[0] != 0x4d)
                 return sceMcResNoFormat;
         if (mcman_PS1PDApagebuf.byte[1] != 0x43)
                 return sceMcResNoFormat;
         for (i = 0; i < 20; i++) {
                 r = McReadPS1PDACard(port, slot, i + 16, &mcman_PS1PDApagebuf);
                 if (r != sceMcResSucceed)
                         return -43;
                 if (mcman_PS1PDApagebuf.byte[127] == (mcman_calcEDC(&mcman_PS1PDApagebuf, 127) & 0xff)) {
                         mcdi->bad_block_list[i] = mcman_PS1PDApagebuf.word[0];
                 }
         }
         r = mcman_cachePS1dirs(port, slot);
         if (r != sceMcResSucceed)
                 return r;
         mcdi->cardform = 1;
         return sceMcResSucceed;
 }
References MCDevInfo::bad_block_list, MCDevInfo::blocksize, mcman_PS1PDApagebuf::byte, MCDevInfo::cardform, MCDevInfo::cardtype, MCDevInfo::cluster_size, MCDevInfo::clusters_per_block, MCDevInfo::clusters_per_card, DPRINTF, MCDevInfo::FATentries_per_cluster, mcman_cachePS1dirs(), mcman_calcEDC(), mcman_devinfos, mcman_sio2outbufs_PS1PDA, McReadPS1PDACard(), memset(), MCDevInfo::pages_per_cluster, MCDevInfo::pagesize, sceMcResNoFormat, sceMcResSucceed, MCDevInfo::unused, and mcman_PS1PDApagebuf::word.
Referenced by mcman_probePS1Card().
mcman_sparesize()
int mcman_sparesize (int port, int slot)
Definition at line 1290 of file main.c.
 { // Get ps2 mc spare size by dividing pagesize / 32
         return (mcman_devinfos[port][slot].pagesize + 0x1F) >> 5;
 }
References mcman_devinfos.
Referenced by McCheckBlock(), mcman_fillbackupblock1(), mcman_flushcacheentry(), mcman_readpage(), McReadPage(), McWritePage(), sio2packet_add_ecc_in(), and sio2packet_add_ecc_out().
mcman_unformat1()
int mcman_unformat1 (int port, int slot)
Definition at line 704 of file ps1mc_fio.c.
 {
         register int r, i;
         u32 *p;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_unformat1 port%d slot%d\n", port, slot);
 #endif
         p = mcman_PS1PDApagebuf.word;
         for (i = 0; i < 32; i++)
                 *p++ = 0;
         for (i = 0; i < 1024; i++) {
                 r = McWritePS1PDACard(port, slot, i, &mcman_PS1PDApagebuf);
                 if (r != sceMcResSucceed)
                         return -41;
         }
         return r;
 }
References DPRINTF, McWritePS1PDACard(), sceMcResSucceed, and mcman_PS1PDApagebuf::word.
Referenced by McUnformat().
mcman_unformat2()
int mcman_unformat2 (int port, int slot)
Definition at line 1343 of file ps2mc_fio.c.
 {
         register int r, i, j, z, l, pageword_cnt, page, blocks_on_card, erase_byte, err_cnt;
         register u32 erase_value;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
 #ifdef DEBUG
         DPRINTF("mcman: mcman_unformat2 port%d slot%d\n", port, slot);
 #endif
         pageword_cnt = mcdi->pagesize >> 2;
         blocks_on_card = mcdi->clusters_per_card / mcdi->clusters_per_block; //sp18
         erase_value = 0xffffffff; //s6
         if (!(mcdi->cardflags & CF_ERASE_ZEROES))
                 erase_value = 0x00000000;
         for (i = 0; i < pageword_cnt; i++)
                 mcman_pagebuf.word[i] = erase_value;
         for (i = 0; i < 128; i++)
                 *((u32 *)&mcman_eccdata + i) = erase_value;
         i = 1;
         if (i < blocks_on_card) {
                 erase_byte = erase_value & 0xff;        // sp20
                 do {
                         page = i * mcdi->blocksize;
                         if (mcdi->cardform > 0) {
                                 j = 0;
                                 for (j = 0; j < 16; j++) {
                                         if (mcdi->bad_block_list[j] <= 0) {
                                                 j = 16;
                                                 goto lbl1;
                                         }
                                         if (mcdi->bad_block_list[j] == i)
                                                 goto lbl1;
                                 }
                         }
                         else {
                                 err_cnt = 0;
                                 j = -1;
                                 z = 0;
                                 if (mcdi->blocksize > 0) {
                                         do {
                                                 r = McReadPage(port, slot, page + z, &mcman_pagebuf);
                                                 if (r == sceMcResNoFormat) {
                                                         j = -2;
                                                         break;
                                                 }
                                                 if (r != sceMcResSucceed)
                                                         return -42;
                                                 if ((mcdi->cardflags & CF_USE_ECC) == 0)        {
                                                         for (l = 0; l < mcdi->pagesize; l++) {
                                                                 if (mcman_pagebuf.byte[l] != erase_byte)
                                                                         err_cnt++;
                                                                 if (err_cnt >= (mcdi->clusters_per_block << 6)) {
                                                                         j = 16;
                                                                         break;
                                                                 }
                                                         }
                                                         if (j != -1)
                                                                 break;
                                                 }
                                         } while (++z < mcdi->blocksize);
                                 }
                         }
                         if (((mcdi->cardflags & CF_USE_ECC) != 0) && (j == -1))
                                 j = 16;
 lbl1:
                         if (j == 16) {
                                 r = mcman_eraseblock(port, slot, i, NULL, NULL);
                                 if (r != sceMcResSucceed)
                                         return -43;
                         }
                         else {
                                 for (l = 0; l < pageword_cnt; l++)
                                         mcman_pagebuf.word[l] = erase_value;
                                 if (mcdi->blocksize > 0) {
                                         z = 0;
                                         do {
                                                 r = McWritePage(port, slot, page + z, &mcman_pagebuf, mcman_eccdata);
                                                 if (r != sceMcResSucceed)
                                                         return -44;
                                         } while (++z < mcdi->blocksize);
                                 }
                         }
                 } while (++i < blocks_on_card);
         }
         r = mcman_eraseblock(port, slot, 0, NULL, NULL);
         if (r != sceMcResSucceed)
                 return -45;
         return sceMcResSucceed;
 }
References MCDevInfo::bad_block_list, MCDevInfo::blocksize, mcman_pagebuf::byte, MCDevInfo::cardflags, MCDevInfo::cardform, CF_ERASE_ZEROES, CF_USE_ECC, MCDevInfo::clusters_per_block, MCDevInfo::clusters_per_card, DPRINTF, mcman_devinfos, mcman_eccdata, mcman_eraseblock(), McReadPage(), McWritePage(), NULL, MCDevInfo::pagesize, sceMcResNoFormat, sceMcResSucceed, and mcman_pagebuf::word.
Referenced by McUnformat().
mcman_unit2card()
void mcman_unit2card (u32 unit)
Definition at line 159 of file mcdev.c.
 {
         mcman_mc_port = unit & 1;
         mcman_mc_slot = (unit >> 1) & (MCMAN_MAXSLOT - 1);
         // original mcman/xmcman code below is silly and I doubt it
         // can support more than 2 units anyway...
         /*
         register u32 mask = 0xF0000000;
         while (!(unit & mask)) {
                 mask >>= 4;
                 if (mask < 0x10)
                         break;
         }
         mcman_mc_port = unit & 0xf;
         mcman_mc_slot = 0;
         if (mask < 0xf) {
                 while (mask) {
                         mcman_mc_slot = ((u32)(unit & mask)) / ((u32)(mask & (mask >> 0x3))) \
                                 + (((mcman_mc_slot << 2) + mcman_mc_slot) << 1);
                         mask >>= 4;
                 }
         }
         */
 }
References MCMAN_MAXSLOT, mcman_mc_port, and mcman_mc_slot.
Referenced by mc_chstat(), mc_dopen(), mc_format(), mc_getstat(), mc_mkdir(), mc_open(), mc_remove(), and mc_rmdir().
mcman_wmemset()
void mcman_wmemset (void * buf, int size, int value)
Definition at line 344 of file main.c.
 {
         int *p = buf;
         size = (size >> 2) - 1;
         if (size > -1) {
                 do {
                         *p++ = value;
                 } while (--size > -1);
         }
 }
Referenced by McCreateDirentry(), mcman_dread1(), mcman_dread2(), mcman_eraseblock(), mcman_FNC8ca4(), mcman_format1(), mcman_getdir2(), mcman_getstat1(), mcman_getstat2(), mcman_initPS2com(), mcman_open1(), mcman_open2(), mcman_reportBadBlocks(), and mcman_setdevinfos().
mcman_write1()
int mcman_write1 (int fd, void * buffer, int nbyte)
Definition at line 288 of file ps1mc_fio.c.
 {
         register int r, size, temp, wpos, offset, maxsize;
         register MC_FHANDLE *fh = (MC_FHANDLE *)&mcman_fdhandles[fd];
         McCacheEntry *mce;
         u8 *p = (u8 *)buffer;
         if (nbyte) {
                 if (fh->unknown2 == 0) {
                         fh->unknown2 = 1;
                         r = mcman_close1(fd);
                         if (r != sceMcResSucceed)
                                 return r;
                         r = McFlushCache(fh->port, fh->slot);
                         if (r != sceMcResSucceed)
                                 return r;
                 }
         }
         wpos = 0;
         if (nbyte) {
                 do {
                         r = mcman_fatRseekPS1(fd);
                         if (r == sceMcResFullDevice) {
                                 r = mcman_fatWseekPS1(fd);
                                 if (r == sceMcResFullDevice)
                                         return r;
                                 if (r!= sceMcResSucceed)
                                         return r;
                                 r = mcman_fatRseekPS1(fd);
                         }
                         else {
                                 if (r < 0)
                                         return r;
                         }
                         r = mcman_readclusterPS1(fh->port, fh->slot, r, &mce);
                         if (r != sceMcResSucceed)
                                 return r;
                         if (fh->position < 0)
                                 temp = fh->position + 0x3ff;
                         else
                                 temp = fh->position;
                         offset = fh->position - ((temp >> 10) << 10);
                         maxsize = MCMAN_CLUSTERSIZE - offset;
                         if (maxsize < nbyte)
                                 size = maxsize;
                         else
                                 size = nbyte;
                         memcpy((void *)(mce->cl_data + offset), &p[wpos], size);
                         mce->wr_flag = -1;
                         fh->position += size;
                         if (fh->position >= fh->filesize)
                                 fh->filesize = fh->position;
                         nbyte -= size;
                         wpos += size;
                 } while (nbyte);
         }
         mcman_close1(fd);
         return wpos;
 }
References buffer, McCacheEntry::cl_data, MC_FHANDLE::filesize, McFlushCache(), mcman_close1(), MCMAN_CLUSTERSIZE, mcman_fatRseekPS1(), mcman_fatWseekPS1(), mcman_fdhandles, mcman_readclusterPS1(), memcpy(), MC_FHANDLE::port, MC_FHANDLE::position, sceMcResFullDevice, sceMcResSucceed, MC_FHANDLE::slot, MC_FHANDLE::unknown2, and McCacheEntry::wr_flag.
Referenced by McWrite().
mcman_write2()
int mcman_write2 (int fd, void * buffer, int nbyte)
Definition at line 547 of file ps2mc_fio.c.
 {
         register int r, r2, wpos, size, offset;
         register MC_FHANDLE *fh = (MC_FHANDLE *)&mcman_fdhandles[fd];
         register MCDevInfo *mcdi = &mcman_devinfos[fh->port][fh->slot];
         McCacheEntry *mce;
         if (nbyte) {
                 if (fh->unknown2 == 0) {
                         fh->unknown2 = 1;
                         r = mcman_close2(fd);
                         if (r != sceMcResSucceed)
                                 return r;
                         r = McFlushCache(fh->port, fh->slot);
                         if (r != sceMcResSucceed)
                                 return r;
                 }
         }
         wpos = 0;
         if (nbyte) {
                 do {
                         r = mcman_fatRseek(fd);
                         if (r == sceMcResFullDevice) {
                                 r2 = mcman_fatWseek(fd);
                                 if (r2 == r)
                                         return sceMcResFullDevice;
                                 if (r2 != sceMcResSucceed)
                                         return r2;
                                 r = mcman_fatRseek(fd);
                         }
                         else {
                                 if (r < 0)
                                         return r;
                         }
                         r = McReadCluster(fh->port, fh->slot, r, &mce);
                         if (r != sceMcResSucceed)
                                 return r;
                         mce->rd_flag = 1;
                         offset = fh->position % mcdi->cluster_size;  // file pointer offset % cluster size
                         r2 = mcdi->cluster_size - offset;
                         if (r2 < nbyte)
                                 size = r2;
                         else
                                 size = nbyte;
                         memcpy((void *)(mce->cl_data + offset), (void *)(buffer + wpos), size);
                         mce->wr_flag = 1;
                         r = fh->position + size;
                         fh->position += size;
                         if (r < fh->filesize)
                                 r = fh->filesize ;
                         fh->filesize = r;
                         nbyte -= size;
                         wpos += size;
                 } while (nbyte);
         }
         r = mcman_close2(fd);
         if (r != sceMcResSucceed)
                 return r;
         return wpos;
 }
References buffer, McCacheEntry::cl_data, MCDevInfo::cluster_size, MC_FHANDLE::filesize, McFlushCache(), mcman_close2(), mcman_devinfos, mcman_fatRseek(), mcman_fatWseek(), mcman_fdhandles, McReadCluster(), memcpy(), MC_FHANDLE::port, MC_FHANDLE::position, McCacheEntry::rd_flag, sceMcResFullDevice, sceMcResSucceed, MC_FHANDLE::slot, MC_FHANDLE::unknown2, and McCacheEntry::wr_flag.
Referenced by McWrite().
mcman_writecluster()
int mcman_writecluster (int port, int slot, int cluster, int flag)
Definition at line 2056 of file main.c.
 {
         register int r, i, j, page, block, pageword_cnt;
         register u32 erase_value;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         block = cluster / mcdi->clusters_per_block;
         if ((mcman_wr_port == port) && (mcman_wr_slot == slot) && (mcman_wr_block == block))
                 return mcman_wr_flag3;
         mcman_wr_port = port;
         mcman_wr_slot = slot;
         mcman_wr_block = block;
         mcman_wr_flag3 = -9;
         for (i = 0; i < 16; i++) { // check only 16 bad blocks ?
                 if (mcdi->bad_block_list[i] < 0)
                         break;
                 if (mcdi->bad_block_list[i] == block) {
                         mcman_wr_flag3 = 0;
                         return sceMcResSucceed;
                 }
         }
         if (flag) {
                 for (i = 1; i < mcdi->blocksize; i++)
                         mcman_pagedata[i] = 0;
                 mcman_pagedata[0] = mcman_pagebuf.byte;
                 pageword_cnt = mcdi->pagesize >> 2;
                 page = block * mcdi->blocksize;
                 if (mcdi->cardflags & CF_ERASE_ZEROES)
                         erase_value = 0xffffffff;
                 else
                         erase_value = 0x00000000;
                 for (i = 0; i < pageword_cnt; i++)
                         mcman_pagebuf.word[i] = erase_value;
                 r = mcman_eraseblock(port, slot, block, (void **)mcman_pagedata, (void *)mcman_eccdata);
                 if (r == sceMcResFailReplace)
                         return sceMcResSucceed;
                 if (r != sceMcResSucceed)
                         return sceMcResChangedCard;
                 for (i = 1; i < mcdi->blocksize; i++) {
                         r = McWritePage(port, slot, page + i, &mcman_pagebuf, mcman_eccdata);
                         if (r == sceMcResFailReplace)
                                 return sceMcResSucceed;
                         if (r != sceMcResSucceed)
                                 return sceMcResNoFormat;
                 }
                 for (i = 1; i < mcdi->blocksize; i++) {
                         r = McReadPage(port, slot, page + i, &mcman_pagebuf);
                         if (r == sceMcResNoFormat)
                                 return sceMcResSucceed;
                         if (r != sceMcResSucceed)
                                 return sceMcResFullDevice;
                         for (j = 0; j < pageword_cnt; j++) {
                                 if (mcman_pagebuf.word[j] != erase_value) {
                                         mcman_wr_flag3 = 0;
                                         return sceMcResSucceed;
                                 }
                         }
                 }
                 r = mcman_eraseblock(port, slot, block, NULL, NULL);
                 if (r != sceMcResSucceed)
                         return sceMcResChangedCard;
                 r = McWritePage(port, slot, page, &mcman_pagebuf, mcman_eccdata);
                 if (r == sceMcResFailReplace)
                         return sceMcResSucceed;
                 if (r != sceMcResSucceed)
                         return sceMcResNoFormat;
                 r = McReadPage(port, slot, page, &mcman_pagebuf);
                 if (r == sceMcResNoFormat)
                         return sceMcResSucceed;
                 if (r != sceMcResSucceed)
                         return sceMcResFullDevice;
                 for (j = 0; j < pageword_cnt; j++) {
                         if (mcman_pagebuf.word[j] != erase_value) {
                                 mcman_wr_flag3 = 0;
                                 return sceMcResSucceed;
                         }
                 }
                 r = mcman_eraseblock(port, slot, block, NULL, NULL);
                 if (r == sceMcResFailReplace)
                         return sceMcResSucceed;
                 if (r != sceMcResSucceed)
                         return sceMcResFullDevice;
                 erase_value = ~erase_value;
                 for (i = 0; i < mcdi->blocksize; i++) {
                         r = McReadPage(port, slot, page + i, &mcman_pagebuf);
                         if (r != sceMcResSucceed)
                                 return sceMcResDeniedPermit;
                         for (j = 0; j < pageword_cnt; j++) {
                                 if (mcman_pagebuf.word[j] != erase_value) {
                                         mcman_wr_flag3 = 0;
                                         return sceMcResSucceed;
                                 }
                         }
                 }
         }
         mcman_wr_flag3 = 1;
         return mcman_wr_flag3;
 }
References MCDevInfo::bad_block_list, MCDevInfo::blocksize, mcman_pagebuf::byte, MCDevInfo::cardflags, CF_ERASE_ZEROES, MCDevInfo::clusters_per_block, mcman_devinfos, mcman_eccdata, mcman_eraseblock(), mcman_pagedata, mcman_wr_block, mcman_wr_flag3, mcman_wr_port, mcman_wr_slot, McReadPage(), McWritePage(), NULL, MCDevInfo::pagesize, sceMcResChangedCard, sceMcResDeniedPermit, sceMcResFailReplace, sceMcResFullDevice, sceMcResNoFormat, sceMcResSucceed, and mcman_pagebuf::word.
Referenced by mcman_format2().
mcsio2_transfer()
int mcsio2_transfer (int port, int slot, sio2_transfer_data_t * sio2data)
Definition at line 227 of file mcsio2.c.
 {
         register int r;
 #ifdef DEBUG
         u8 *p = (u8 *)(sio2data->in_dma.addr);
         if (p)
                 DPRINTF("mcman: mcsio2_transfer port%d slot%d cmd = %02x %02x %02x ", port, slot, p[0], p[1], p[2]);
         else {
                 p = (u8 *)(sio2data->in);
                 DPRINTF("mcman: mcsio2_transfer for secrman port%d slot%d cmd = %02x %02x %02x ", port, slot, p[0], p[1], p[2]);
         }
 #endif
         // SIO2 transfer for MCMAN
         psio2_mc_transfer_init();
         r = psio2_transfer(sio2data);
 #ifdef DEBUG
         DPRINTF("returns %d\n", r);
 #endif
         return r;
 }
References _sio2_dma_arg::addr, DPRINTF, sio2_transfer_data_t::in, sio2_transfer_data_t::in_dma, psio2_mc_transfer_init, and psio2_transfer.
Referenced by _start().
mcsio2_transfer2()
int mcsio2_transfer2 (int port, int slot, sio2_transfer_data_t * sio2data)
Definition at line 253 of file mcsio2.c.
 {
         // SIO2 transfer for XMCMAN
         register int r;
         s32 port_ctrl[8];
 #ifdef DEBUG
         DPRINTF("mcman: mcsio2_transfer2 port%d slot%d\n", port, slot);
 #endif
         port_ctrl[0] = -1;
         port_ctrl[1] = -1;
         port_ctrl[2] = -1;
         port_ctrl[3] = -1;
         port_ctrl[(port & 1) + 2] = slot;
         psio2_mc_transfer_init();
         psio2_mtap_change_slot(port_ctrl);
         r = psio2_transfer(sio2data);
         psio2_transfer_reset();
 #ifdef DEBUG
         DPRINTF("mcman: mcsio2_transfer2 returns %d\n", r);
 #endif
         return r;
 }
References DPRINTF, psio2_mc_transfer_init, psio2_mtap_change_slot, psio2_transfer, and psio2_transfer_reset.
Referenced by _start().
secrman_mc_command()
int secrman_mc_command (int port, int slot, sio2_transfer_data_t * sio2data)
Definition at line 330 of file mcsio2.c.
 {
         register int r;
 #ifdef DEBUG
         DPRINTF("mcman: secrman_mc_command port%d slot%d\n", port, slot);
 #endif
         r = mcman_sio2transfer(port, slot, sio2data);
         return r;
 }
References DPRINTF, and mcman_sio2transfer.
Referenced by mcman_initPS2com().
sio2packet_add()
void sio2packet_add (int port, int slot, int cmd, u8 * buf)
Definition at line 73 of file mcsio2.c.
 {       // Used to build the sio2packets for all mc commands
         register u32 regdata;
         register int pos;
         u8 *p;
         if (cmd == 0xffffffff) {
                 mcman_sio2packet.in_dma.count = 0;
                 return;
         }
         if (mcman_sio2packet.in_dma.count < 0xb) {
                 if (cmd == 0xfffffffe) {
                         mcman_sio2packet.regdata[mcman_sio2packet.in_dma.count] = 0;
                         mcman_sio2packet.out_dma.count = mcman_sio2packet.in_dma.count;
                         return;
                 }
                 regdata = (((port & 1) + 2) & 3) | 0x70;
                 regdata |= mcman_cmdtable[(cmd << 1) + 1] << 18;
                 regdata |= mcman_cmdtable[(cmd << 1) + 1] << 8;
                 mcman_sio2packet.regdata[mcman_sio2packet.in_dma.count] = regdata;
                 pos = ((mcman_sio2packet.in_dma.count + (mcman_sio2packet.in_dma.count << 3)) << 4);
                 mcman_sio2packet.in_dma.count++;
                 p = mcman_sio2packet.in_dma.addr + pos;
                 p[0] = 0x81;
                 p[1] = mcman_cmdtable[cmd << 1];
                 if (((cmd - 1) >= 16) || ((cmd - 1) < 0))
                         return;
                 sio2packet_add_func = (void*)sio2packet_add_funcs_array[(cmd - 1)];
                 (sio2packet_add_func)(port, slot, cmd, buf, pos); // call to the needed child func
         }
 }
References _sio2_dma_arg::addr, _sio2_dma_arg::count, sio2_transfer_data_t::in_dma, mcman_cmdtable, mcman_sio2packet, sio2_transfer_data_t::out_dma, pos, sio2_transfer_data_t::regdata, sio2packet_add_func, and sio2packet_add_funcs_array.
Referenced by McGetCardSpec(), mcman_cardchanged(), mcman_eraseblock(), mcman_probePS2Card(), mcman_probePS2Card2(), mcman_readpage(), mcman_resetauth(), and McWritePage().