ps2sdk: iop/memorycard/mcman/include/mcman.h File Reference
mcman.h File Reference
#include <types.h>
#include <irx.h>
#include <libmc-common.h>
Data Structures
struct sceMcTblGetDir
Macros
#define mcman_IMPORTS_start DECLARE_IMPORT_TABLE(mcman, 1, 1)
#define mcman_IMPORTS_end END_IMPORT_TABLE
#define xmcman_IMPORTS_start DECLARE_IMPORT_TABLE(mcman, 2, 3)
#define xmcman_IMPORTS_end END_IMPORT_TABLE
#define I_McDetectCard DECLARE_IMPORT(5, McDetectCard)
#define I_McOpen DECLARE_IMPORT(6, McOpen)
#define I_McClose DECLARE_IMPORT(7, McClose)
#define I_McRead DECLARE_IMPORT(8, McRead)
#define I_McWrite DECLARE_IMPORT(9, McWrite)
#define I_McSeek DECLARE_IMPORT(10, McSeek)
#define I_McFormat DECLARE_IMPORT(11, McFormat)
#define I_McGetDir DECLARE_IMPORT(12, McGetDir)
#define I_McDelete DECLARE_IMPORT(13, McDelete)
#define I_McFlush DECLARE_IMPORT(14, McFlush)
#define I_McChDir DECLARE_IMPORT(15, McChDir)
#define I_McSetFileInfo DECLARE_IMPORT(16, McSetFileInfo)
#define I_McEraseBlock DECLARE_IMPORT(17, McEraseBlock)
#define I_McReadPage DECLARE_IMPORT(18, McReadPage)
#define I_McWritePage DECLARE_IMPORT(19, McWritePage)
#define I_McDataChecksum DECLARE_IMPORT(20, McDataChecksum);
#define I_McReadPS1PDACard DECLARE_IMPORT(29, McReadPS1PDACard)
#define I_McWritePS1PDACard DECLARE_IMPORT(30, McWritePS1PDACard)
#define I_McUnformat DECLARE_IMPORT(36, McUnformat)
#define I_McRetOnly DECLARE_IMPORT(37, McRetOnly)
#define I_McGetFreeClusters DECLARE_IMPORT(38, McGetFreeClusters)
#define I_McGetMcType DECLARE_IMPORT(39, McGetMcType)
#define I_McSetPS1CardFlag DECLARE_IMPORT(40, McSetPS1CardFlag)
#define I_McEraseBlock2 DECLARE_IMPORT(17, McEraseBlock2)
#define I_McDetectCard2 DECLARE_IMPORT(21, McDetectCard2)
#define I_McGetFormat DECLARE_IMPORT(22, McGetFormat)
#define I_McGetEntSpace DECLARE_IMPORT(23, McGetEntSpace)
#define I_McReplaceBadBlock DECLARE_IMPORT(24, McReplaceBadBlock)
#define I_McCloseAll DECLARE_IMPORT(25, McCloseAll)
#define I_McGetModuleInfo DECLARE_IMPORT(42, McGetModuleInfo)
#define I_McGetCardSpec DECLARE_IMPORT(43, McGetCardSpec)
#define I_McGetFATentry DECLARE_IMPORT(44, McGetFATentry)
#define I_McCheckBlock DECLARE_IMPORT(45, McCheckBlock)
#define I_McSetFATentry DECLARE_IMPORT(46, McSetFATentry)
#define I_McReadDirEntry DECLARE_IMPORT(47, McReadDirEntry)
#define I_Mc1stCacheEntSetWrFlagOff DECLARE_IMPORT(48, Mc1stCacheEntSetWrFlagOff)
#define I_McCreateDirentry DECLARE_IMPORT(49, McCreateDirentry)
#define I_McReadCluster DECLARE_IMPORT(50, McReadCluster)
#define I_McFlushCache DECLARE_IMPORT(51, McFlushCache)
#define I_McSetDirEntryState DECLARE_IMPORT(52, McSetDirEntryState)
Functions
int McDetectCard (int port, int slot)
int McOpen (int port, int slot, char *filename, int flags)
int McClose (int fd)
int McRead (int fd, void *buf, int length)
int McWrite (int fd, void *buf, int length)
int McSeek (int fd, int offset, int origin)
int McFormat (int port, int slot)
int McGetDir (int port, int slot, char *dirname, int flags, int maxent, sceMcTblGetDir *info)
int McDelete (int port, int slot, char *filename, int flags)
int McFlush (int fd)
int McChDir (int port, int slot, char *newdir, char *currentdir)
int McSetFileInfo (int port, int slot, char *filename, sceMcTblGetDir *info, int flags)
int McEraseBlock (int port, int block, void **pagebuf, void *eccbuf)
int McReadPage (int port, int slot, int page, void *buf)
int McWritePage (int port, int slot, int page, void *pagebuf, void *eccbuf)
void McDataChecksum (void *buf, void *ecc)
int McReadPS1PDACard (int port, int slot, int page, void *buf)
int McWritePS1PDACard (int port, int slot, int page, void *buf)
int McUnformat (int port, int slot)
int McRetOnly (int fd)
int McGetFreeClusters (int port, int slot)
int McGetMcType (int port, int slot)
void McSetPS1CardFlag (int flag)
int McEraseBlock2 (int port, int slot, int block, void **pagebuf, void *eccbuf)
int McDetectCard2 (int port, int slot)
int McGetFormat (int port, int slot)
int McGetEntSpace (int port, int slot, char *dirname)
int McReplaceBadBlock (void)
int McCloseAll (void)
struct irx_id * McGetModuleInfo (void)
int McGetCardSpec (int port, int slot, s16 *pagesize, u16 *blocksize, int *cardsize, u8 *flags)
int McGetFATentry (int port, int slot, int fat_index, int *fat_entry)
int McCheckBlock (int port, int slot, int block)
int McSetFATentry (int port, int slot, int fat_index, int fat_entry)
int McReadDirEntry (int port, int slot, int cluster, int fsindex, McFsEntry **pfse)
void Mc1stCacheEntSetWrFlagOff (void)
int McCreateDirentry (int port, int slot, int parent_cluster, int num_entries, int cluster, sceMcStDateTime *ctime)
int McReadCluster (int port, int slot, int cluster, McCacheEntry **pmce)
int McFlushCache (int port, int slot)
int McSetDirEntryState (int port, int slot, int cluster, int fsindex, int flags)
Detailed Description
Memory card manager definitions
Definition in file mcman.h.
Macro Definition Documentation
I_Mc1stCacheEntSetWrFlagOff
#define I_Mc1stCacheEntSetWrFlagOff DECLARE_IMPORT(48, Mc1stCacheEntSetWrFlagOff)
Definition at line 119 of file mcman.h.
I_McChDir
#define I_McChDir DECLARE_IMPORT(15, McChDir)
Definition at line 94 of file mcman.h.
I_McCheckBlock
#define I_McCheckBlock DECLARE_IMPORT(45, McCheckBlock)
Definition at line 116 of file mcman.h.
I_McClose
#define I_McClose DECLARE_IMPORT(7, McClose)
Definition at line 86 of file mcman.h.
I_McCloseAll
#define I_McCloseAll DECLARE_IMPORT(25, McCloseAll)
Definition at line 112 of file mcman.h.
I_McCreateDirentry
#define I_McCreateDirentry DECLARE_IMPORT(49, McCreateDirentry)
Definition at line 120 of file mcman.h.
I_McDataChecksum
#define I_McDataChecksum DECLARE_IMPORT(20, McDataChecksum);
Definition at line 99 of file mcman.h.
I_McDelete
#define I_McDelete DECLARE_IMPORT(13, McDelete)
Definition at line 92 of file mcman.h.
I_McDetectCard
#define I_McDetectCard DECLARE_IMPORT(5, McDetectCard)
Definition at line 84 of file mcman.h.
I_McDetectCard2
#define I_McDetectCard2 DECLARE_IMPORT(21, McDetectCard2)
Definition at line 108 of file mcman.h.
I_McEraseBlock
#define I_McEraseBlock DECLARE_IMPORT(17, McEraseBlock)
Definition at line 96 of file mcman.h.
I_McEraseBlock2
#define I_McEraseBlock2 DECLARE_IMPORT(17, McEraseBlock2)
Definition at line 107 of file mcman.h.
I_McFlush
#define I_McFlush DECLARE_IMPORT(14, McFlush)
Definition at line 93 of file mcman.h.
I_McFlushCache
#define I_McFlushCache DECLARE_IMPORT(51, McFlushCache)
Definition at line 122 of file mcman.h.
I_McFormat
#define I_McFormat DECLARE_IMPORT(11, McFormat)
Definition at line 90 of file mcman.h.
I_McGetCardSpec
#define I_McGetCardSpec DECLARE_IMPORT(43, McGetCardSpec)
Definition at line 114 of file mcman.h.
I_McGetDir
#define I_McGetDir DECLARE_IMPORT(12, McGetDir)
Definition at line 91 of file mcman.h.
I_McGetEntSpace
#define I_McGetEntSpace DECLARE_IMPORT(23, McGetEntSpace)
Definition at line 110 of file mcman.h.
I_McGetFATentry
#define I_McGetFATentry DECLARE_IMPORT(44, McGetFATentry)
Definition at line 115 of file mcman.h.
I_McGetFormat
#define I_McGetFormat DECLARE_IMPORT(22, McGetFormat)
Definition at line 109 of file mcman.h.
I_McGetFreeClusters
#define I_McGetFreeClusters DECLARE_IMPORT(38, McGetFreeClusters)
Definition at line 104 of file mcman.h.
I_McGetMcType
#define I_McGetMcType DECLARE_IMPORT(39, McGetMcType)
Definition at line 105 of file mcman.h.
I_McGetModuleInfo
#define I_McGetModuleInfo DECLARE_IMPORT(42, McGetModuleInfo)
Definition at line 113 of file mcman.h.
I_McOpen
#define I_McOpen DECLARE_IMPORT(6, McOpen)
Definition at line 85 of file mcman.h.
I_McRead
#define I_McRead DECLARE_IMPORT(8, McRead)
Definition at line 87 of file mcman.h.
I_McReadCluster
#define I_McReadCluster DECLARE_IMPORT(50, McReadCluster)
Definition at line 121 of file mcman.h.
I_McReadDirEntry
#define I_McReadDirEntry DECLARE_IMPORT(47, McReadDirEntry)
Definition at line 118 of file mcman.h.
I_McReadPage
#define I_McReadPage DECLARE_IMPORT(18, McReadPage)
Definition at line 97 of file mcman.h.
I_McReadPS1PDACard
#define I_McReadPS1PDACard DECLARE_IMPORT(29, McReadPS1PDACard)
Definition at line 100 of file mcman.h.
I_McReplaceBadBlock
#define I_McReplaceBadBlock DECLARE_IMPORT(24, McReplaceBadBlock)
Definition at line 111 of file mcman.h.
I_McRetOnly
#define I_McRetOnly DECLARE_IMPORT(37, McRetOnly)
Definition at line 103 of file mcman.h.
I_McSeek
#define I_McSeek DECLARE_IMPORT(10, McSeek)
Definition at line 89 of file mcman.h.
I_McSetDirEntryState
#define I_McSetDirEntryState DECLARE_IMPORT(52, McSetDirEntryState)
Definition at line 123 of file mcman.h.
I_McSetFATentry
#define I_McSetFATentry DECLARE_IMPORT(46, McSetFATentry)
Definition at line 117 of file mcman.h.
I_McSetFileInfo
#define I_McSetFileInfo DECLARE_IMPORT(16, McSetFileInfo)
Definition at line 95 of file mcman.h.
I_McSetPS1CardFlag
#define I_McSetPS1CardFlag DECLARE_IMPORT(40, McSetPS1CardFlag)
Definition at line 106 of file mcman.h.
I_McUnformat
#define I_McUnformat DECLARE_IMPORT(36, McUnformat)
Definition at line 102 of file mcman.h.
I_McWrite
#define I_McWrite DECLARE_IMPORT(9, McWrite)
Definition at line 88 of file mcman.h.
I_McWritePage
#define I_McWritePage DECLARE_IMPORT(19, McWritePage)
Definition at line 98 of file mcman.h.
I_McWritePS1PDACard
#define I_McWritePS1PDACard DECLARE_IMPORT(30, McWritePS1PDACard)
Definition at line 101 of file mcman.h.
mcman_IMPORTS_end
#define mcman_IMPORTS_end END_IMPORT_TABLE
Definition at line 79 of file mcman.h.
mcman_IMPORTS_start
#define mcman_IMPORTS_start DECLARE_IMPORT_TABLE(mcman, 1, 1)
Definition at line 78 of file mcman.h.
xmcman_IMPORTS_end
#define xmcman_IMPORTS_end END_IMPORT_TABLE
Definition at line 82 of file mcman.h.
xmcman_IMPORTS_start
#define xmcman_IMPORTS_start DECLARE_IMPORT_TABLE(mcman, 2, 3)
Definition at line 81 of file mcman.h.
Function Documentation
Mc1stCacheEntSetWrFlagOff()
void Mc1stCacheEntSetWrFlagOff (void)
Definition at line 3271 of file main.c.
 {
         McCacheEntry *mce = (McCacheEntry *)*pmcman_mccache;
         mce->wr_flag = -1;
 }
References pmcman_mccache, and McCacheEntry::wr_flag.
Referenced by _start(), mcman_close2(), mcman_open2(), mcman_setinfo2(), McReplaceBadBlock(), and McSetDirEntryState().
McChDir()
int McChDir (int port, int slot, char * newdir, char * currentdir)
Definition at line 1007 of file main.c.
 {
         register int r;
         r = McDetectCard(port, slot);
         if (r != sceMcResSucceed)
                 return r;
         if (mcman_devinfos[port][slot].cardtype == sceMcTypePS2)
                 r = mcman_chdir(port, slot, newdir, currentdir);
         else {
                 currentdir[0] = 0;
                 r = sceMcResSucceed;
         }
         if (r < -9) {
                 mcman_invhandles(port, slot);
                 mcman_clearcache(port, slot);
         }
         return r;
 }
References McDetectCard(), mcman_chdir(), mcman_clearcache(), mcman_devinfos, mcman_invhandles(), sceMcResSucceed, and sceMcTypePS2.
McCheckBlock()
int McCheckBlock (int port, int slot, int block)
Definition at line 2324 of file main.c.
 {
         register int r, i, j, page, ecc_count, pageword_cnt, flag, erase_value;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         u8 *p_page, *p_ecc;
 #ifdef DEBUG
         DPRINTF("mcman: McCheckBlock port%d slot%d block 0x%x\n", port, slot, block);
 #endif
         // sp50 = block;
         page = block * mcdi->blocksize; //sp18
         pageword_cnt = mcdi->pagesize >> 2; //s6
         ecc_count = mcdi->pagesize;
         if (mcdi->pagesize < 0)
                 ecc_count += 127;
         ecc_count = ecc_count >> 7; // s7
         flag = 0; // s4
         if (mcdi->cardform > 0) {
                 for (i = 0; i < 16; i++) {
                         if (mcdi->bad_block_list[i] <= 0)
                                 break;
                         if (mcdi->bad_block_list[i] == block)
                                 goto lbl_8764;
                 }
         }
         flag = 16; // s4
         for (i = 0; i < mcdi->blocksize; i++) {
                 r = mcman_readpage(port, slot, page + i, &mcman_pagebuf, mcman_eccdata);
                 if (r != sceMcResSucceed)
                         return -45;
                 if ((mcdi->cardflags & CF_USE_ECC) != 0) {
                         if (mcman_eccdata[mcman_sparesize(port, slot) - 1] != 0xff) {
                                 p_page = mcman_pagebuf.byte; //s1
                                 p_ecc = (void *)mcman_eccdata; //s2
                                 for (j = 0; j < ecc_count; j++) {
                                         r = mcman_correctdata(p_page, p_ecc);
                                         if (r != sceMcResSucceed) {
                                                 flag = -1;
                                                 goto lbl_8764;
                                         }
                                         p_ecc += 3;
                                         p_page += 128;
                                 }
                         }
                 }
         }
         for (j = 0; j < pageword_cnt; j++)
                 mcman_pagebuf.word[j] = 0x5a5aa5a5;
         for (j = 0; j < 128; j++)
                 *((u32 *)&mcman_eccdata + j) = 0x5a5aa5a5;
         r = mcman_eraseblock(port, slot, block, NULL, NULL);
         if (r != sceMcResSucceed) {
                 r = mcman_probePS2Card2(port, slot);
                 if (r != sceMcResSucceed)
                         return -45;
                 flag = -1;
                 goto lbl_8764;
         }
         for (i = 0; i < mcdi->blocksize; i++) {
                 r = McWritePage(port, slot, page + i, &mcman_pagebuf, mcman_eccdata);
                 if (r != sceMcResSucceed) {
                         r = mcman_probePS2Card2(port, slot);
                         if (r != sceMcResSucceed)
                                 return -44;
                         flag = -1;
                         goto lbl_8764;
                 }
         }
         for (i = 0; i < mcdi->blocksize; i++) {
                 r = mcman_readpage(port, slot, page + i, &mcman_pagebuf, mcman_eccdata);
                 if (r != sceMcResSucceed)
                         return -45;
                 for (j = 0; j < pageword_cnt; j++) {
                         if (mcman_pagebuf.word[j] != 0x5a5aa5a5) {
                                 flag = -1;
                                 goto lbl_8764;
                         }
                 }
                 for (j = 0; j < 128; j++) {
                         if (*((u32 *)&mcman_eccdata + j) != 0x5a5aa5a5) {
                                 flag = -1;
                                 goto lbl_8764;
                         }
                 }
         }
         for (j = 0; j < pageword_cnt; j++)
                 mcman_pagebuf.word[j] = 0x05a55a5a;
         for (j = 0; j < 128; j++)
                 *((u32 *)&mcman_eccdata + j) = 0x05a55a5a;
         r = mcman_eraseblock(port, slot, block, NULL, NULL);
         if (r != sceMcResSucceed) {
                 r = mcman_probePS2Card2(port, slot);
                 if (r != sceMcResSucceed)
                         return -42;
                 flag = -1;
                 goto lbl_8764;
         }
         for (i = 0; i < mcdi->blocksize; i++) {
                 r = McWritePage(port, slot, page + i, &mcman_pagebuf, mcman_eccdata);
                 if (r != sceMcResSucceed) {
                         r = mcman_probePS2Card2(port, slot);
                         if (r != sceMcResSucceed)
                                 return -46;
                         flag = -1;
                         goto lbl_8764;
                 }
         }
         for (i = 0; i < mcdi->blocksize; i++) {
                 r = mcman_readpage(port, slot, page + i, &mcman_pagebuf, mcman_eccdata);
                 if (r != sceMcResSucceed)
                         return -45;
                 for (j = 0; j < pageword_cnt; j++) {
                         if (mcman_pagebuf.word[j] != 0x05a55a5a) {
                                 flag = -1;
                                 goto lbl_8764;
                         }
                 }
                 for (j = 0; j < 128; j++) {
                         if (*((u32 *)&mcman_eccdata + j) != 0x05a55a5a) {
                                 flag = -1;
                                 goto lbl_8764;
                         }
                 }
         }
 lbl_8764:
         if (flag == 16) {
                 mcman_eraseblock(port, slot, block, NULL, NULL);
                 return sceMcResSucceed;
         }
         erase_value = 0x00000000;
         if ((mcdi->cardflags & CF_ERASE_ZEROES) != 0)
                 erase_value = 0xffffffff;
         for (j = 0; j < pageword_cnt; j++)
                 mcman_pagebuf.word[j] = erase_value;
         for (j = 0; j < 128; j++)
                 *((u32 *)&mcman_eccdata + j) = erase_value;
         for (i = 0; i < mcdi->blocksize; i++) {
                 r = McWritePage(port, slot, page + i, &mcman_pagebuf, mcman_eccdata);
                 if (r != sceMcResSucceed) {
                         r = mcman_probePS2Card2(port, slot);
                         if (r != sceMcResSucceed)
                                 return -48;
                 }
         }
         return 1;
 }
References MCDevInfo::bad_block_list, MCDevInfo::blocksize, mcman_pagebuf::byte, MCDevInfo::cardflags, MCDevInfo::cardform, CF_ERASE_ZEROES, CF_USE_ECC, DPRINTF, mcman_correctdata(), mcman_devinfos, mcman_eccdata, mcman_eraseblock(), mcman_probePS2Card2(), mcman_readpage(), mcman_sparesize(), McWritePage(), NULL, MCDevInfo::pagesize, sceMcResSucceed, and mcman_pagebuf::word.
Referenced by _start().
McClose()
int McClose (int fd)
Definition at line 653 of file main.c.
 {
         register MC_FHANDLE *fh;
         register MCDevInfo *mcdi;
         register int r;
         if (!((u32)fd < MAX_FDHANDLES))
                 return sceMcResDeniedPermit;
         fh = (MC_FHANDLE *)&mcman_fdhandles[fd];
         if (!fh->status)
                 return sceMcResDeniedPermit;
         fh->status = 0;
         r = McDetectCard(fh->port, fh->slot);
         if (r != sceMcResSucceed)
                 return r;
         r = McFlushCache(fh->port, fh->slot);
         if (r < -9)     {
                 mcman_invhandles(fh->port, fh->slot);
                 mcman_clearcache(fh->port, fh->slot);
         }
         if (r != sceMcResSucceed)
                 return r;
         if (fh->unknown2 != 0) {
                 fh->unknown2 = 0;
                 mcdi = (MCDevInfo *)&mcman_devinfos[fh->port][fh->slot];
                 if (mcdi->cardtype == sceMcTypePS2)
                         r = mcman_close2(fd);
                 else
                         r = mcman_close1(fd);
                 if (r < -9)     {
                         mcman_invhandles(fh->port, fh->slot);
                         mcman_clearcache(fh->port, fh->slot);
                 }
                 if (r != sceMcResSucceed)
                         return r;
         }
         r = McFlushCache(fh->port, fh->slot);
         if (r < -9)     {
                 mcman_invhandles(fh->port, fh->slot);
                 mcman_clearcache(fh->port, fh->slot);
         }
         return r;
 }
References MCDevInfo::cardtype, MAX_FDHANDLES, McDetectCard(), McFlushCache(), mcman_clearcache(), mcman_close1(), mcman_close2(), mcman_devinfos, mcman_fdhandles, mcman_invhandles(), MC_FHANDLE::port, sceMcResDeniedPermit, sceMcResSucceed, sceMcTypePS2, MC_FHANDLE::slot, MC_FHANDLE::status, and MC_FHANDLE::unknown2.
Referenced by mc_close(), mc_dclose(), and McCloseAll().
McCloseAll()
int McCloseAll (void)
Definition at line 463 of file main.c.
 {
         register int fd = 0, rv = 0;
         do {
                 if (mcman_fdhandles[fd].status) {
                         register int rc;
                         rc = McClose(fd);
                         if (rc < rv)
                                 rv = rc;
                 }
                 fd++;
         } while (fd < MAX_FDHANDLES);
         return rv;
 }
References MAX_FDHANDLES, McClose(), mcman_fdhandles, and status.
Referenced by mc_deinit(), and mcman_initdev().
McCreateDirentry()
int McCreateDirentry (int port, int slot, int parent_cluster, int num_entries, int cluster, sceMcStDateTime * ctime)
Definition at line 1485 of file main.c.
 {
         register int r;
         McCacheEntry *mce;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         McFsEntry *mfe, *mfe_next, *pfse;
 #ifdef DEBUG
         DPRINTF("mcman: McCreateDirentry port%d slot%d parent_cluster %x num_entries %d cluster %x\n", port, slot, parent_cluster, num_entries, cluster);
 #endif
         r = McReadCluster(port, slot, mcdi->alloc_offset + cluster, &mce);
         if (r != sceMcResSucceed)
                 return r;
         mcman_wmemset(mce->cl_data, MCMAN_CLUSTERSIZE, 0);
         mfe = (McFsEntry*)mce->cl_data;
         mfe_next = (McFsEntry*)(mce->cl_data + sizeof (McFsEntry));
         mfe->mode = sceMcFileAttrReadable | sceMcFileAttrWriteable | sceMcFileAttrExecutable \
                           | sceMcFileAttrSubdir | sceMcFile0400 | sceMcFileAttrExists; // 0x8427
         if (ctime == NULL)
                 mcman_getmcrtime(&mfe->created);
         else
                 mfe->created = *ctime;
         mfe->modified = mfe->created;
         mfe->length = 0;
         mfe->dir_entry = num_entries;
         mfe->cluster = parent_cluster;
         mfe->name[0] = '.';
         mfe->name[1] = '\0';
         if ((parent_cluster == 0) && (num_entries == 0)) {
                 // entry is root directory
                 mfe_next->created = mfe->created;
                 mfe->length = 2;
                 mfe++;
                 mfe->mode = sceMcFileAttrWriteable | sceMcFileAttrExecutable | sceMcFileAttrSubdir \
                                   | sceMcFile0400 | sceMcFileAttrExists | sceMcFileAttrHidden; // 0xa426
                 mfe->dir_entry = 0;
                 mfe->cluster = 0;
         }
         else {
                 // entry is normal "." / ".."
                 McReadDirEntry(port, slot, parent_cluster, 0, &pfse);
                 mfe_next->created = pfse->created;
                 mfe++;
                 mfe->mode = sceMcFileAttrReadable | sceMcFileAttrWriteable | sceMcFileAttrExecutable \
                                   | sceMcFileAttrSubdir | sceMcFile0400 | sceMcFileAttrExists; // 0x8427
                 mfe->dir_entry = pfse->dir_entry;
                 mfe->cluster = pfse->cluster;
         }
         mfe->modified = mfe->created;
         mfe->length = 0;
         mfe->name[0] = '.';
         mfe->name[1] = '.';
         mfe->name[2] = '\0';
         mce->wr_flag = 1;
         return sceMcResSucceed;
 }
References MCDevInfo::alloc_offset, McCacheEntry::cl_data, McFsEntry::cluster, McFsEntry::created, McFsEntry::dir_entry, DPRINTF, McFsEntry::length, MCMAN_CLUSTERSIZE, mcman_devinfos, mcman_getmcrtime(), mcman_wmemset(), McReadCluster(), McReadDirEntry(), McFsEntry::mode, McFsEntry::modified, McFsEntry::name, NULL, sceMcFile0400, sceMcFileAttrExecutable, sceMcFileAttrExists, sceMcFileAttrHidden, sceMcFileAttrReadable, sceMcFileAttrSubdir, sceMcFileAttrWriteable, sceMcResSucceed, and McCacheEntry::wr_flag.
Referenced by _start(), mcman_format2(), and mcman_open2().
McDataChecksum()
void McDataChecksum (void * buf, void * ecc)
Definition at line 1210 of file main.c.
 {
         register u8 *p, *p_ecc;
         register int i, a2, a3, v, t0;
         p = buf;
         i = 0;
         a2 = 0;
         a3 = 0;
         t0 = 0;
         do {
                 v = mcman_xortable[*p++];
                 a2 ^= v;
                 if (v & 0x80) {
                         a3 ^= ~i;
                         t0 ^= i;
                 }
         } while (++i < 0x80);
         p_ecc = ecc;
         p_ecc[0] = ~a2 & 0x77;
         p_ecc[1] = ~a3 & 0x7F;
         p_ecc[2] = ~t0 & 0x7F;
 }
References a2, a3, mcman_xortable, t0, and irx_id::v.
Referenced by mcman_correctdata(), mcman_eraseblock(), and mcman_flushcacheentry().
McDelete()
int McDelete (int port, int slot, char * filename, int flags)
Definition at line 1031 of file main.c.
 {
         register int r;
         r = McDetectCard(port, slot);
         if (r != sceMcResSucceed)
                 return r;
         if (mcman_devinfos[port][slot].cardtype == sceMcTypePS2)
                 r = mcman_delete2(port, slot, filename, flags);
         else
                 r = mcman_delete1(port, slot, filename, flags);
         if (r < -9) {
                 mcman_invhandles(port, slot);
                 mcman_clearcache(port, slot);
         }
         return r;
 }
References McDetectCard(), mcman_clearcache(), mcman_delete1(), mcman_delete2(), mcman_devinfos, mcman_invhandles(), sceMcResSucceed, and sceMcTypePS2.
Referenced by mc_remove(), and mc_rmdir().
McDetectCard()
int McDetectCard (int port, int slot)
Definition at line 483 of file main.c.
 {
         return mc_detectcard(port, slot);
 }
References mc_detectcard.
Referenced by McChDir(), McClose(), McDelete(), McFlush(), McFormat(), McGetDir(), McGetEntSpace(), mcman_dread(), mcman_getstat(), McOpen(), McRead(), McSeek(), McSetFileInfo(), McUnformat(), and McWrite().
McDetectCard2()
int McDetectCard2 (int port, int slot)
Definition at line 558 of file main.c.
 {
         register int r;
         register MCDevInfo *mcdi;
 #ifdef DEBUG
         DPRINTF("mcman: McDetectCard2 port%d slot%d\n", port, slot);
 #endif
         mcdi = (MCDevInfo *)&mcman_devinfos[port][slot];
         if ((mcdi->cardtype == sceMcTypeNoCard) || (mcdi->cardtype == sceMcTypePS2)) {
                 r = mcman_probePS2Card(port, slot);
                 if (r < -9) {
                         r = mcman_probePS1Card(port, slot);
                         if (!(r < -9)) {
                                 if (mcman_probePDACard(port, slot)) {
                                         mcdi->cardtype = sceMcTypePS1;
                                         return (!PS1CardFlag) ? sceMcResDeniedPS1Permit : r;
                                 }
                                 else {
                                         mcdi->cardtype = sceMcTypePDA;
                                         return r;
                                 }
                         }
                 }
                 else {
                         mcdi->cardtype = sceMcTypePS2;
                         return r;
                 }
         }
         else {
                 r = mcman_probePS1Card(port, slot);
                 if (r) {
                         if ((r < -9) || (r >= 0)) {
                                 r = mcman_probePS2Card(port, slot);
                                 if (!(r < -9)) {
                                         mcdi->cardtype = sceMcTypePS2;
                                         return r;
                                 }
                         }
                         else {
                                 if (mcman_probePDACard(port, slot)) {
                                         mcdi->cardtype = sceMcTypePS1;
                                         return (!PS1CardFlag) ? sceMcResDeniedPS1Permit : r;
                                 }
                                 else {
                                         mcdi->cardtype = sceMcTypePDA;
                                         return r;
                                 }
                         }
                 }
                 else {
                         if (PS1CardFlag)
                                 return sceMcResSucceed;
                         if (mcdi->cardtype == sceMcTypePS1)
                                 return sceMcResDeniedPS1Permit;
                         return sceMcResSucceed;
                 }
         }
         mcdi->cardtype = 0;
         mcdi->cardform = 0;
         mcman_invhandles(port, slot);
         mcman_clearcache(port, slot);
         return r;
 }
References MCDevInfo::cardform, MCDevInfo::cardtype, DPRINTF, mcman_clearcache(), mcman_devinfos, mcman_invhandles(), mcman_probePDACard(), mcman_probePS1Card(), mcman_probePS2Card(), PS1CardFlag, sceMcResDeniedPS1Permit, sceMcResSucceed, sceMcTypeNoCard, sceMcTypePDA, sceMcTypePS1, and sceMcTypePS2.
Referenced by _start(), mc_chstat(), mc_dopen(), mc_format(), mc_getstat(), mc_mkdir(), mc_open(), mc_remove(), and mc_rmdir().
McEraseBlock()
int McEraseBlock (int port, int block, void ** pagebuf, void * eccbuf)
Definition at line 1147 of file main.c.
 {
         return mcman_eraseblock(port, 0, block, (void **)pagebuf, eccbuf);
 }
References mcman_eraseblock().
McEraseBlock2()
int McEraseBlock2 (int port, int slot, int block, void ** pagebuf, void * eccbuf)
Definition at line 1153 of file main.c.
 {
         return mcman_eraseblock(port, slot, block, (void **)pagebuf, eccbuf);
 }
References mcman_eraseblock().
Referenced by _start().
McFlush()
int McFlush (int fd)
Definition at line 707 of file main.c.
 {
         register int r;
         register MC_FHANDLE *fh;
         register MCDevInfo *mcdi;
         if (!((u32)fd < MAX_FDHANDLES))
                 return sceMcResDeniedPermit;
         fh = (MC_FHANDLE *)&mcman_fdhandles[fd];
         if (!fh->status)
                 return sceMcResDeniedPermit;
         r = McDetectCard(fh->port, fh->slot);
         if (r != sceMcResSucceed)
                 return r;
         r = McFlushCache(fh->port, fh->slot);
         if (r < -9) {
                 mcman_invhandles(fh->port, fh->slot);
                 mcman_clearcache(fh->port, fh->slot);
         }
         if (r != sceMcResSucceed) {
                 fh->status = 0;
                 return r;
         }
         if (fh->unknown2 != 0) {
                 fh->unknown2 = 0;
                 mcdi = (MCDevInfo *)&mcman_devinfos[fh->port][fh->slot];
                 if (mcdi->cardtype == sceMcTypePS2)
                         r = mcman_close2(fd);
                 else
                         r = mcman_close1(fd);
                 if (r < -9)     {
                         mcman_invhandles(fh->port, fh->slot);
                         mcman_clearcache(fh->port, fh->slot);
                 }
                 if (r != sceMcResSucceed) {
                         fh->status = 0;
                         return r;
                 }
         }
         r = McFlushCache(fh->port, fh->slot);
         if (r < 0)
                 fh->status = 0;
         if (r < -9) {
                 mcman_invhandles(fh->port, fh->slot);
                 mcman_clearcache(fh->port, fh->slot);
         }
         return r;
 }
References MCDevInfo::cardtype, MAX_FDHANDLES, McDetectCard(), McFlushCache(), mcman_clearcache(), mcman_close1(), mcman_close2(), mcman_devinfos, mcman_fdhandles, mcman_invhandles(), MC_FHANDLE::port, sceMcResDeniedPermit, sceMcResSucceed, sceMcTypePS2, MC_FHANDLE::slot, MC_FHANDLE::status, and MC_FHANDLE::unknown2.
McFlushCache()
int McFlushCache (int port, int slot)
Definition at line 3311 of file main.c.
 {
         register int i, r;
         McCacheEntry **pmce = (McCacheEntry **)pmcman_mccache;
         McCacheEntry *mce;
 #ifdef DEBUG
         DPRINTF("mcman: McFlushCache port%d slot%d\n", port, slot);
 #endif
         i = MAX_CACHEENTRY - 1;
         if (i >= 0) {
                 do {
                         mce = (McCacheEntry *)pmce[i];
                         if ((mce->mc_port == port) && (mce->mc_slot == slot) && (mce->wr_flag != 0)) {
                                 r = mcman_flushcacheentry((McCacheEntry *)mce);
                                 if (r != sceMcResSucceed)
                                         return r;
                         }
                         i--;
                 } while (i >= 0);
         }
         return sceMcResSucceed;
 }
References DPRINTF, MAX_CACHEENTRY, McCacheEntry::mc_port, McCacheEntry::mc_slot, mcman_flushcacheentry(), pmcman_mccache, sceMcResSucceed, and McCacheEntry::wr_flag.
Referenced by _start(), McClose(), McFlush(), mcman_clearPS1direntry(), mcman_clearsuperblock(), mcman_close1(), mcman_delete2(), mcman_fatWseek(), mcman_fatWseekPS1(), mcman_format2(), mcman_open1(), mcman_open2(), mcman_setinfo1(), mcman_write1(), mcman_write2(), McReplaceBadBlock(), and McSetFileInfo().
McFormat()
int McFormat (int port, int slot)
Definition at line 1053 of file main.c.
 {
         register int r;
         mcman_invhandles(port, slot);
         r = McDetectCard(port, slot);
         if (r < -2)
                 return r;
         mcman_clearcache(port, slot);
         if (mcman_devinfos[port][slot].cardtype == sceMcTypePS2)
                 r = mcman_format2(port, slot);
         else
                 r = mcman_format1(port, slot);
         if (r < -9) {
                 mcman_invhandles(port, slot);
                 mcman_clearcache(port, slot);
         }
         return r;
 }
References McDetectCard(), mcman_clearcache(), mcman_devinfos, mcman_format1(), mcman_format2(), mcman_invhandles(), and sceMcTypePS2.
Referenced by mc_format().
McGetCardSpec()
int McGetCardSpec (int port, int slot, s16 * pagesize, u16 * blocksize, int * cardsize, u8 * flags)
Definition at line 598 of file mcsio2.c.
 {
         register int retries, r;
         u8 *p = mcman_sio2packet.out_dma.addr;
 #ifdef DEBUG
         DPRINTF("mcman: McGetCardSpec sio2cmd port%d slot%d\n", port, slot);
 #endif
         sio2packet_add(port, slot, 0xffffffff, NULL);
         sio2packet_add(port, slot, 0x07, NULL);
         sio2packet_add(port, slot, 0xfffffffe, NULL);
         retries = 0;
         do {
                 mcman_sio2transfer(port, slot, &mcman_sio2packet);
                 if (((mcman_sio2packet.stat6c & 0xF000) == 0x1000) && (p[12] == 0x5a)) {
                         // checking EDC
                         r = mcman_calcEDC(&p[3], 8) & 0xFF;
                         if (r == p[11])
                                 break;
                 }
         } while (++retries < 5);
         if (retries >= 5)
                 return sceMcResChangedCard;
         *pagesize = (p[4] << 8) + p[3];
         *blocksize = (p[6] << 8) + p[5];
         *cardsize = (p[8] << 8) + p[7] + (p[9] << 16) + (p[10] << 24);
         *flags = p[2];
 #ifdef DEBUG
         DPRINTF("mcman: McGetCardSpec sio2cmd pagesize=%d blocksize=%u cardsize=%d flags%x\n", *pagesize, *blocksize, *cardsize, *flags);
 #endif
         return sceMcResSucceed;
 }
References _sio2_dma_arg::addr, DPRINTF, mcman_calcEDC(), mcman_sio2packet, mcman_sio2transfer, NULL, sio2_transfer_data_t::out_dma, sceMcResChangedCard, sceMcResSucceed, sio2packet_add(), and sio2_transfer_data_t::stat6c.
Referenced by _start(), and mcman_setdevspec().
McGetDir()
int McGetDir (int port, int slot, char * dirname, int flags, int maxent, sceMcTblGetDir * info)
Definition at line 897 of file main.c.
 {
         register int r;
         r = McDetectCard(port, slot);
         if (r != sceMcResSucceed)
                 return r;
         if (mcman_devinfos[port][slot].cardtype == sceMcTypePS2)
                 r = mcman_getdir2(port, slot, dirname, flags & 0xFFFF, maxent, info);
         else
                 r = mcman_getdir1(port, slot, dirname, flags & 0xFFFF, maxent, info);
         if (r < -9) {
                 mcman_invhandles(port, slot);
                 mcman_clearcache(port, slot);
         }
         return r;
 }
References McDetectCard(), mcman_clearcache(), mcman_devinfos, mcman_getdir1(), mcman_getdir2(), mcman_invhandles(), sceMcResSucceed, and sceMcTypePS2.
McGetEntSpace()
int McGetEntSpace (int port, int slot, char * dirname)
Definition at line 876 of file main.c.
 {
         register int r;
         r = McDetectCard(port, slot);
         if (r != sceMcResSucceed)
                 return r;
         if (mcman_devinfos[port][slot].cardtype == sceMcTypePS2) {
                 r = mcman_getentspace(port, slot, dirname);
         }
         if (r < -9) {
                 mcman_invhandles(port, slot);
                 mcman_clearcache(port, slot);
         }
         return r;
 }
References McDetectCard(), mcman_clearcache(), mcman_devinfos, mcman_getentspace(), mcman_invhandles(), sceMcResSucceed, and sceMcTypePS2.
Referenced by _start().
McGetFATentry()
int McGetFATentry (int port, int slot, int fat_index, int * fat_entry)
Definition at line 3831 of file main.c.
 {
         register int r, ifc_index, indirect_index, indirect_offset, fat_offset;
         McCacheEntry *mce;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         indirect_index = fat_index / mcdi->FATentries_per_cluster;
         fat_offset = fat_index % mcdi->FATentries_per_cluster;
         ifc_index = indirect_index / mcdi->FATentries_per_cluster;
         indirect_offset = indirect_index % mcdi->FATentries_per_cluster;
         r = McReadCluster(port, slot, mcdi->ifc_list[ifc_index], &mce);
         if (r != sceMcResSucceed)
                 return -78;
         McFatCluster *fc = (McFatCluster *)mce->cl_data;
         r = McReadCluster(port, slot, fc->entry[indirect_offset], &mce);
         if (r != sceMcResSucceed)
                 return -79;
         fc = (McFatCluster *)mce->cl_data;
         *fat_entry = fc->entry[fat_offset];
         return sceMcResSucceed;
 }
References McCacheEntry::cl_data, McFatCluster::entry, MCDevInfo::FATentries_per_cluster, MCDevInfo::ifc_list, mcman_devinfos, McReadCluster(), and sceMcResSucceed.
Referenced by _start(), mcman_fatRseek(), mcman_fatWseek(), mcman_open2(), McReadDirEntry(), McReplaceBadBlock(), and McSetDirEntryState().
McGetFormat()
int McGetFormat (int port, int slot)
Definition at line 273 of file main.c.
 {
 #ifdef DEBUG
         DPRINTF("mcman: McGetFormat port%d slot%d\n", port, slot);
 #endif
         return mcman_devinfos[port][slot].cardform;
 }
References MCDevInfo::cardform, DPRINTF, and mcman_devinfos.
Referenced by _start(), mcman_probePS2Card(), and mcman_probePS2Card2().
McGetFreeClusters()
int McGetFreeClusters (int port, int slot)
Definition at line 309 of file main.c.
 {
         register int r, mcfree;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
 #ifdef DEBUG
         DPRINTF("mcman: McGetFreeClusters port%d slot%d\n", port, slot);
 #endif
         mcfree = 0;
         if (mcdi->cardform)     {
                 switch (mcdi->cardtype) {
                         case sceMcTypePS2:
                                 mcfree = mcman_findfree2(port, slot, 0);
                                 break;
                         case sceMcTypePS1:
                         case sceMcTypePDA:
                                 mcfree = mcman_findfree1(port, slot, 0);
                                 break;
                         case sceMcTypeNoCard:
                                 mcfree = 0;
                                 break;
                 }
                 if (mcfree == sceMcResFullDevice)
                         mcfree = 0;
                 r = mcfree;
         }
         else
                 return 0;
         return r;
 }
References MCDevInfo::cardform, MCDevInfo::cardtype, DPRINTF, mcman_devinfos, mcman_findfree1(), mcman_findfree2(), sceMcResFullDevice, sceMcTypeNoCard, sceMcTypePDA, sceMcTypePS1, and sceMcTypePS2.
McGetMcType()
int McGetMcType (int port, int slot)
Definition at line 282 of file main.c.
 {
 #ifdef DEBUG
         DPRINTF("mcman: McGetMcType port%d slot%d\n", port, slot);
 #endif
         return mcman_devinfos[port][slot].cardtype;
 }
References MCDevInfo::cardtype, DPRINTF, and mcman_devinfos.
McGetModuleInfo()
struct irx_id* McGetModuleInfo (void)
Definition at line 291 of file main.c.
 {
 #ifdef DEBUG
         DPRINTF("mcman: McGetModuleInfo\n");
 #endif
         return &_irx_id;
 }
References _irx_id, and DPRINTF.
Referenced by _start().
McOpen()
int McOpen (int port, int slot, char * filename, int flags)
Definition at line 628 of file main.c.
 {
         register int r;
         r = McDetectCard(port, slot);
         if (r != sceMcResSucceed)
                 return r;
         if (!PS1CardFlag)
                 flag &= 0xFFFFDFFF; // disables FRCOM flag OR what is it
         if (mcman_devinfos[port][slot].cardtype == sceMcTypePS2)
                 r = mcman_open2(port, slot, filename, flag);
         else
                 r = mcman_open1(port, slot, filename, flag);
         if (r < -9)     {
                 mcman_invhandles(port, slot);
                 mcman_clearcache(port, slot);
         }
         return r;
 }
References McDetectCard(), mcman_clearcache(), mcman_devinfos, mcman_invhandles(), mcman_open1(), mcman_open2(), PS1CardFlag, sceMcResSucceed, and sceMcTypePS2.
Referenced by mc_dopen(), mc_mkdir(), and mc_open().
McRead()
int McRead (int fd, void * buf, int length)
Definition at line 804 of file main.c.
 {
         register int r;
         register MC_FHANDLE *fh;
         if (!((u32)fd < MAX_FDHANDLES))
                 return sceMcResDeniedPermit;
         fh = (MC_FHANDLE *)&mcman_fdhandles[fd];
         if (!fh->status)
                 return sceMcResDeniedPermit;
         if (!fh->rdflag)
                 return sceMcResDeniedPermit;
         r = McDetectCard(fh->port, fh->slot);
         if (r != sceMcResSucceed)
                 return r;
         if (mcman_devinfos[fh->port][fh->slot].cardtype == sceMcTypePS2)
                 r = mcman_read2(fd, buf, length);
         else
                 r = mcman_read1(fd, buf, length);
         if (r < 0)
                 fh->status = 0;
         if (r < -9) {
                 mcman_invhandles(fh->port, fh->slot);
                 mcman_clearcache(fh->port, fh->slot);
         }
         return r;
 }
References MCDevInfo::cardtype, MAX_FDHANDLES, McDetectCard(), mcman_clearcache(), mcman_devinfos, mcman_fdhandles, mcman_invhandles(), mcman_read1(), mcman_read2(), MC_FHANDLE::port, MC_FHANDLE::rdflag, sceMcResDeniedPermit, sceMcResSucceed, sceMcTypePS2, MC_FHANDLE::slot, and MC_FHANDLE::status.
Referenced by mc_read().
McReadCluster()
int McReadCluster (int port, int slot, int cluster, McCacheEntry ** pmce)
Definition at line 3648 of file main.c.
 {
         register int r, i, block, block_offset;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         McCacheEntry *mce;
         if (mcman_badblock > 0) {
                 block = cluster / mcdi->clusters_per_block;
                 block_offset = cluster % mcdi->clusters_per_block;
                 if ((block == mcman_badblock) && (mcman_badblock_port == port) && (mcman_badblock_slot == slot)) {
                         cluster = (mcdi->backup_block1 * mcdi->clusters_per_block) + block_offset;
                 }
                 else {
                         if (mcman_badblock > 0) {
                                 for (i = 0; i < mcdi->clusters_per_block; i++) {
                                         if ((mcman_replacementcluster[i] != 0) && (mcman_replacementcluster[i] == cluster)) {
                                                 block_offset = i % mcdi->clusters_per_block;
                                                 cluster = (mcdi->backup_block1 * mcdi->clusters_per_block) + block_offset;
                                         }
                                 }
                         }
                 }
         }
         mce = mcman_getcacheentry(port, slot, cluster);
         if (mce == NULL) {
                 mce = pmcman_mccache[MAX_CACHEENTRY - 1];
                 if (mce->wr_flag != 0) {
                         r = mcman_flushcacheentry((McCacheEntry *)mce);
                         if (r != sceMcResSucceed)
                                 return r;
                 }
                 mce->mc_port = port;
                 mce->mc_slot = slot;
                 mce->cluster = cluster;
                 mce->rd_flag = 0;
                 //s3 = (cluster * mcdi->pages_per_cluster);
                 for (i = 0; i < mcdi->pages_per_cluster; i++) {
                         r = McReadPage(port, slot, (cluster * mcdi->pages_per_cluster) + i, \
                                         (void *)(mce->cl_data + (i * mcdi->pagesize)));
                         if (r != sceMcResSucceed)
                                 return -21;
                 }
         }
         mcman_addcacheentry(mce);
         *pmce = (McCacheEntry *)mce;
         return sceMcResSucceed;
 }
References MCDevInfo::backup_block1, McCacheEntry::cl_data, McCacheEntry::cluster, MCDevInfo::clusters_per_block, MAX_CACHEENTRY, McCacheEntry::mc_port, McCacheEntry::mc_slot, mcman_addcacheentry(), mcman_badblock, mcman_badblock_port, mcman_badblock_slot, mcman_devinfos, mcman_flushcacheentry(), mcman_getcacheentry(), mcman_replacementcluster, McReadPage(), NULL, MCDevInfo::pages_per_cluster, MCDevInfo::pagesize, pmcman_mccache, McCacheEntry::rd_flag, sceMcResSucceed, and McCacheEntry::wr_flag.
Referenced by _start(), McCreateDirentry(), McGetFATentry(), mcman_checkBackupBlocks(), mcman_clearsuperblock(), mcman_findfree2(), mcman_format2(), mcman_read2(), mcman_write2(), McReadDirEntry(), McReplaceBadBlock(), and McSetFATentry().
McReadDirEntry()
int McReadDirEntry (int port, int slot, int cluster, int fsindex, McFsEntry ** pfse)
Definition at line 3704 of file main.c.
 {
         register int r, i;
         static int maxent, index, clust;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         register McFatCache *fci = &mcman_fatcache[port][slot];
         McCacheEntry *mce;
 #ifdef DEBUG
         DPRINTF("mcman: McReadDirEntry port%d slot%d cluster %d fsindex %d\n", port, slot, cluster, fsindex);
 #endif
         maxent = 0x402 / (mcdi->cluster_size >> 9); //a1
         index = fsindex / (mcdi->cluster_size >> 9);//s2
         clust = cluster;
         i = 0; // s0
         if ((cluster == 0) && (index != 0)) {
                 if (index < maxent) {
                         i = index;
                         if ((fci->entry[index]) >= 0 )
                                 clust = fci->entry[index];
                 }
                 i = 0;
                 if (index > 0) {
                         do {
                                 if (i >= maxent)
                                         break;
                                 if (fci->entry[i] < 0)
                                         break;
                                 clust = fci->entry[i];
                         } while (++i < index);
                 }
                 i--;
         }
         if (i < index) {
                 do {
                         r = McGetFATentry(port, slot, clust, &clust);
                         if (r != sceMcResSucceed)
                                 return -70;
                         if (clust == 0xffffffff)
                                 return sceMcResNoEntry;
                         clust &= 0x7fffffff;
                         i++;
                         if (cluster == 0) {
                                 if (i < maxent)
                                         fci->entry[i] = clust;
                         }
                 } while (i < index);
         }
         r = McReadCluster(port ,slot, mcdi->alloc_offset + clust, &mce);
         if (r != sceMcResSucceed)
                 return -71;
         *pfse = (McFsEntry *)(mce->cl_data + ((fsindex % (mcdi->cluster_size >> 9)) << 9));
         return sceMcResSucceed;
 }
References MCDevInfo::alloc_offset, McCacheEntry::cl_data, MCDevInfo::cluster_size, DPRINTF, McFatCache::entry, index(), McGetFATentry(), mcman_devinfos, mcman_fatcache, McReadCluster(), sceMcResNoEntry, and sceMcResSucceed.
Referenced by _start(), McCreateDirentry(), mcman_cachedirentry(), mcman_chdir(), mcman_close2(), mcman_delete2(), mcman_dread2(), mcman_getdir2(), mcman_getdirinfo(), mcman_getentspace(), mcman_open2(), mcman_setdevinfos(), mcman_setinfo2(), McReplaceBadBlock(), and McSetDirEntryState().
McReadPage()
int McReadPage (int port, int slot, int page, void * buf)
Definition at line 1159 of file main.c.
 {
         register int r, index, ecres, retries, count, erase_byte;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         u8 eccbuf[32];
         u8 *pdata, *peccb;
         count = (mcdi->pagesize + 127) >> 7;
         erase_byte = (mcdi->cardflags & CF_ERASE_ZEROES) ? 0x0 : 0xFF;
         retries = 0;
         ecres = sceMcResSucceed;
         do {
                 if (!mcman_readpage(port, slot, page, buf, eccbuf)) {
                         if (mcdi->cardflags & CF_USE_ECC) { // checking ECC from spare data block
                                 // check for erased page (last byte of spare data set to 0xFF or 0x0)/
                         if (eccbuf[mcman_sparesize(port, slot) - 1] == erase_byte)
                                 break;
                         index = 0;
                         if (count > 0) {
                                 peccb = (u8 *)eccbuf;
                                 pdata = (u8 *)buf;
                                 do {
                                         r = mcman_correctdata(pdata, peccb);
                                         if (r < ecres)
                                                 ecres = r;
                                         peccb += 3;
                                         pdata += 128;
                                         } while (++index < count);
                                 }
                                 if (ecres == sceMcResSucceed)
                                         break;
                                 if ((retries == 4) && (!(ecres < sceMcResNoFormat)))
                                         break;
                         }
                 }
         } while (++retries < 5);
         if (retries < 5)
                 return sceMcResSucceed;
         return (ecres != sceMcResSucceed) ? sceMcResNoFormat : sceMcResChangedCard;
 }
References MCDevInfo::cardflags, CF_ERASE_ZEROES, CF_USE_ECC, index(), mcman_correctdata(), mcman_devinfos, mcman_readpage(), mcman_sparesize(), MCDevInfo::pagesize, sceMcResChangedCard, sceMcResNoFormat, and sceMcResSucceed.
Referenced by mcman_checkBackupBlocks(), mcman_flushcacheentry(), mcman_reportBadBlocks(), mcman_setdevinfos(), mcman_unformat2(), mcman_writecluster(), and McReadCluster().
McReadPS1PDACard()
int McReadPS1PDACard (int port, int slot, int page, void * buf)
Definition at line 1062 of file mcsio2.c.
 {
         register int i, retries;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         u8 *p;
 #ifdef DEBUG
         //DPRINTF("mcman: McReadPS1PDACard port%d slot%d page %x\n", port, slot, page);
 #endif
         mcman_sio2packet_PS1PDA.regdata[0] = 0;
         mcman_sio2packet_PS1PDA.regdata[0] = (((port & 1) + 2) & 3) | 0x02308c40;
         mcman_sio2packet_PS1PDA.in_size = 140;
         mcman_sio2packet_PS1PDA.out_size = 140;
         mcman_sio2packet_PS1PDA.regdata[1] = 0;
         for (i = 0; i < 20; i++) {
                 if (mcdi->bad_block_list[i] == page)
                         page += 36;
         }
         mcman_sio2inbufs_PS1PDA[0] = 0x81;
         mcman_sio2inbufs_PS1PDA[1] = 0x52;
         mcman_sio2inbufs_PS1PDA[4] = (u8)(page >> 8);
         mcman_sio2inbufs_PS1PDA[5] = (u8)page;
         retries = 0;
         do {
                 mcman_timercount = (u32)(GetTimerCounter(timer_ID) - mcman_timercount);
                 u32 hi, lo;
                 long_multiply(mcman_timercount, 0x3e0f83e1, &hi, &lo);
                 if ((u32)((hi >> 3) < mcman_timerthick))
                         DelayThread(mcman_timerthick - (hi >> 3));
                 mcman_sio2transfer(port, slot, &mcman_sio2packet_PS1PDA);
                 mcman_timercount = GetTimerCounter(timer_ID);
                 mcman_timerthick = 10000;
                 if (((mcman_sio2packet_PS1PDA.stat6c & 0xf000) == 0x1000) \
                                 && (mcman_sio2outbufs_PS1PDA[2] == 0x5a) \
                                         && (mcman_sio2outbufs_PS1PDA[3] == 0x5d) \
                                                 && (mcman_sio2outbufs_PS1PDA[4] == 0x00) \
                                                         && (mcman_sio2outbufs_PS1PDA[6] == 0x5c) \
                                                                 && (mcman_sio2outbufs_PS1PDA[7] == 0x5d) \
                                                                         && (mcman_sio2outbufs_PS1PDA[139] == 0x47)) {
                         if (mcman_sio2outbufs_PS1PDA[138] == (mcman_calcEDC(&mcman_sio2outbufs_PS1PDA[8], 130) & 0xff))
                                 break;
                 }
         } while (++retries < 5);
         if (retries >= 5)
                 return sceMcResNoEntry;
         p = (u8 *)buf;
         for (i = 0; i < 128; i++)
                 p[i] = mcman_sio2outbufs_PS1PDA[10 + i];
         if ((mcman_sio2outbufs_PS1PDA[1] != 0) && (mcman_sio2outbufs_PS1PDA[1] != 8))
                 return sceMcResDeniedPermit;
         return sceMcResSucceed;
 }
References MCDevInfo::bad_block_list, DelayThread(), GetTimerCounter(), sio2_transfer_data_t::in_size, long_multiply(), mcman_calcEDC(), mcman_devinfos, mcman_sio2inbufs_PS1PDA, mcman_sio2outbufs_PS1PDA, mcman_sio2packet_PS1PDA, mcman_sio2transfer, mcman_timercount, mcman_timerthick, sio2_transfer_data_t::out_size, sio2_transfer_data_t::regdata, sceMcResDeniedPermit, sceMcResNoEntry, sceMcResSucceed, sio2_transfer_data_t::stat6c, and timer_ID.
Referenced by mcman_PS1pagetest(), mcman_readclusterPS1(), and mcman_setPS1devinfos().
McReplaceBadBlock()
int McReplaceBadBlock (void)
Definition at line 3986 of file main.c.
 {
         register int r, i, curentry, clust, index, offset, numifc, fat_length, temp, length;
         register int value, value2, cluster, index2, offset2, s3;
         register MCDevInfo *mcdi = &mcman_devinfos[mcman_badblock_port][mcman_badblock_slot];
         int fat_entry[16];
         int fat_entry2;
         McCacheEntry *mce;
         McFsEntry *fse;
 #ifdef DEBUG
         DPRINTF("mcman: McReplaceBadBlock mcman_badblock_port%d mcman_badblock_slot%d mcman_badblock %x\n", mcman_badblock_port, mcman_badblock_slot, mcman_badblock);
 #endif
         if (mcman_badblock == 0)
                 return sceMcResSucceed;
         if (mcman_badblock >= 0) {
                 McFlushCache(mcman_badblock_port, mcman_badblock_slot);
                 mcman_clearcache(mcman_badblock_port, mcman_badblock_slot);
                 for (i = 0; i <16; i++) {
                         if (mcdi->bad_block_list[i] == -1)
                                 break;
                 }
                 if (i >= 16)
                         goto lbl_e168;
                 if (mcdi->alloc_end >= (mcdi->max_allocatable_clusters + 8)) {
                         mcdi->max_allocatable_clusters += 8;
                         mcdi->bad_block_list[i] = mcman_badblock;
                 }
                 fat_length = (((mcdi->clusters_per_card << 2) - 1) / mcdi->cluster_size) + 1;
                 numifc = (((fat_length << 2) - 1) / mcdi->cluster_size) + 1;
                 if (numifc > 32) {
                         numifc = 32;
                         fat_length = mcdi->FATentries_per_cluster << 5;
                 }
                 i = 0; //sp5c
                 value = ~(-1 << mcdi->clusters_per_block);
                 do {
                         clust = (mcman_badblock * mcdi->clusters_per_block) + i;
                         if (clust < mcdi->alloc_offset) {
                                 fat_entry[i] = 0;
                         }
                         else {
                                 r = McGetFATentry(mcman_badblock_port, mcman_badblock_slot, clust - mcdi->alloc_offset, &fat_entry[i]);
                                 if (r != sceMcResSucceed)
                                         goto lbl_e168;
                                 if (((fat_entry[i] & 0x80000000) == 0) || ((fat_entry[i] < -1) && (fat_entry[i] >= -9)))
                                         value &= ~(1 << i);
                         }
                 } while (++i < mcdi->clusters_per_block);
                 if (mcdi->clusters_per_block > 0) {
                         i = 0;
                         do {
                                 if ((value & (1 << i)) != 0) {
                                         r = mcman_findfree2(mcman_badblock_port, mcman_badblock_slot, 1);
                                         if (r < 0) {
                                                 mcman_replacementcluster[i] = r;
                                                 goto lbl_e168;
                                         }
                                         r += mcdi->alloc_offset;
                                         mcman_replacementcluster[i] = r;
                                 }
                         } while (++i < mcdi->clusters_per_block);
                 }
                 if (mcdi->clusters_per_block > 0) {
                         i = 0;
                         do {
                                 if ((value & (1 << i)) != 0) {
                                         if (fat_entry[i] != 0) {
                                                 index = ((fat_entry[i] & 0x7fffffff) + mcdi->alloc_offset) / mcdi->clusters_per_block;
                                                 offset = ((fat_entry[i] & 0x7fffffff) + mcdi->alloc_offset) % mcdi->clusters_per_block;
                                                 if (index == mcman_badblock) {
                                                         fat_entry[i] = (mcman_replacementcluster[offset] - mcdi->alloc_offset) | 0x80000000;
                                                 }
                                         }
                                 }
                         } while (++i < mcdi->clusters_per_block);
                 }
                 if (mcdi->clusters_per_block > 0) {
                         i = 0;
                         do {
                                 if ((mcman_replacementcluster[i] != 0) && (fat_entry[i] != 0)) {
                                         r = McSetFATentry(mcman_badblock_port, mcman_badblock_slot, mcman_replacementcluster[i] + mcdi->alloc_offset, fat_entry[i]);
                                         if (r != sceMcResSucceed)
                                                 goto lbl_e168;
                                 }
                         } while (++i < mcdi->clusters_per_block);
                 }
                 for (i = 0; i < numifc; i++) {
                         index = mcdi->ifc_list[i] / mcdi->clusters_per_block;
                         offset = mcdi->ifc_list[i] % mcdi->clusters_per_block;
                         if (index == mcman_badblock) {
                                 value &= ~(1 << offset);
                                 mcdi->ifc_list[i] = mcman_replacementcluster[i];
                         }
                 }
                 if (value == 0)
                         goto lbl_e030;
                 for (i = 0; i < fat_length; i++) {
                         index = i / mcdi->FATentries_per_cluster;
                         offset = i % mcdi->FATentries_per_cluster;
                         if (offset == 0) {
                                 r = McReadCluster(mcman_badblock_port, mcman_badblock_slot, mcdi->ifc_list[index], &mce);
                                 if (r != sceMcResSucceed)
                                         goto lbl_e168;
                         }
                         offset = i % mcdi->FATentries_per_cluster;
                         index2 = *((u32 *)&mce->cl_data[offset]) / mcdi->clusters_per_block;
                         offset2 = *((u32 *)&mce->cl_data[offset]) % mcdi->clusters_per_block;
                         if (index2 == mcman_badblock) {
                                 value &= ~(1 << offset2);
                                 *((u32 *)&mce->cl_data[offset]) = mcman_replacementcluster[offset2];
                                 mce->wr_flag = 1;
                         }
                 }
                 McFlushCache(mcman_badblock_port, mcman_badblock_slot);
                 mcman_clearcache(mcman_badblock_port, mcman_badblock_slot);
                 if (value == 0)
                         goto lbl_e030;
                 value2 = value;
                 for (i = 0; i < mcdi->alloc_end; i++) {
                         r = McGetFATentry(mcman_badblock_port, mcman_badblock_slot, i, &fat_entry2);
                         if (r != sceMcResSucceed)
                                 goto lbl_e168;
                         index = (u32)(((fat_entry2 & 0x7fffffff) + mcdi->alloc_offset) / mcdi->clusters_per_block);
                         offset = (u32)(((fat_entry2 & 0x7fffffff) + mcdi->alloc_offset) % mcdi->clusters_per_block);
                         if (index == mcman_badblock) {
                                 value &= ~(1 << offset);
                                 r = McSetFATentry(mcman_badblock_port, mcman_badblock_slot, i, (mcman_replacementcluster[offset] - mcdi->alloc_offset) | 0x80000000);
                                 if (r != sceMcResSucceed)
                                         goto lbl_e168;
                         }
                 }
                 if (value2 != value)
                         McFlushCache(mcman_badblock_port, mcman_badblock_slot);
                 r = McReadDirEntry(mcman_badblock_port, mcman_badblock_slot, 0, 0, &fse);
                 if (r != sceMcResSucceed)
                         goto lbl_e168;
                 curentry = 2;
                 s3 = 0;
                 length = fse->length;
 lbl_dd8c:
                 if (curentry >= length)
                         goto lbl_ded0;
                 r = McReadDirEntry(mcman_badblock_port, mcman_badblock_slot, s3, curentry, &fse);
                 if (r != sceMcResSucceed)
                         goto lbl_e168;
                 cluster = fse->cluster;
                 index = (fse->cluster + mcdi->alloc_offset) / mcdi->clusters_per_block;
                 offset = (fse->cluster + mcdi->alloc_offset) % mcdi->clusters_per_block;
                 temp = fse->length;
                 if (index == mcman_badblock) {
                         fse->cluster = mcman_replacementcluster[offset] - mcdi->alloc_offset;
                         Mc1stCacheEntSetWrFlagOff();
                 }
                 if ((fse->mode & sceMcFileAttrSubdir) == 0) {
                         curentry++;
                         goto lbl_dd8c;
                 }
                 r = McReadDirEntry(mcman_badblock_port, mcman_badblock_slot, cluster, 0, &fse);
                 if (r != sceMcResSucceed)
                         goto lbl_e168;
                 if ((fse->mode & sceMcFileAttrSubdir) == 0) {
                         curentry++;
                         goto lbl_dd8c;
                 }
                 if (fse->cluster != 0) {
                         curentry++;
                         goto lbl_dd8c;
                 }
                 if (fse->dir_entry != curentry) {
                         curentry++;
                         goto lbl_dd8c;
                 }
                 curentry++;
                 if (strcmp(fse->name, "."))
                         goto lbl_dd8c;
                 s3 = cluster;
                 curentry = 2;
                 length = temp;
                 goto lbl_dd8c;
 lbl_ded0:
                 r = McReadDirEntry(mcman_badblock_port, mcman_badblock_slot, s3, 1, &fse);
                 if (r != sceMcResSucceed)
                         goto lbl_e168;
                 index = (fse->cluster + mcdi->alloc_offset) / mcdi->clusters_per_block;
                 offset = (fse->cluster + mcdi->alloc_offset) % mcdi->clusters_per_block;
                 if (index == mcman_badblock) {
                         fse->cluster = mcman_replacementcluster[offset] - mcdi->alloc_offset;
                         Mc1stCacheEntSetWrFlagOff();
                 }
                 r = McReadDirEntry(mcman_badblock_port, mcman_badblock_slot, fse->cluster, fse->dir_entry, &fse);
                 if (r != sceMcResSucceed)
                         goto lbl_e168;
                 length = fse->length;
                 r = McReadDirEntry(mcman_badblock_port, mcman_badblock_slot, s3, 0, &fse);
                 if (r != sceMcResSucceed)
                         goto lbl_e168;
                 s3 = fse->cluster;
                 index = (fse->cluster + mcdi->alloc_offset) / mcdi->clusters_per_block;
                 offset = (fse->cluster + mcdi->alloc_offset) % mcdi->clusters_per_block;
                 curentry = fse->dir_entry + 1;
                 if (index == mcman_badblock) {
                         fse->cluster = mcman_replacementcluster[offset] - mcdi->alloc_offset;
                         Mc1stCacheEntSetWrFlagOff();
                 }
                 if (s3 != 0)
                         goto lbl_dd8c;
                 if (curentry != 1)
                         goto lbl_dd8c;
 lbl_e030:
                 if (mcdi->clusters_per_block > 0) {
                         i = 0;
                         do {
                                 clust = (mcman_badblock * mcdi->clusters_per_block) + i;
                                 if (clust >= mcdi->alloc_offset) {
                                         r = McSetFATentry(mcman_badblock_port, mcman_badblock_slot, clust - mcdi->alloc_offset, 0xfffffffd);
                                         if (r != sceMcResSucceed)
                                                 goto lbl_e168;
                                 }
                         } while (++i < mcdi->clusters_per_block);
                 }
                 McFlushCache(mcman_badblock_port, mcman_badblock_slot);
                 mcman_clearcache(mcman_badblock_port, mcman_badblock_slot);
                 mcman_badblock = 0;
                 if (mcdi->clusters_per_block > 0) {
                         i = 0;
                         do {
                                 if (mcman_replacementcluster[i] != 0) {
                                         r = McReadCluster(mcman_badblock_port, mcman_badblock_slot, (mcdi->backup_block1 * mcdi->clusters_per_block) + i, &mce);
                                         if (r != sceMcResSucceed)
                                                 goto lbl_e168;
                                         mce->cluster = mcman_replacementcluster[i];
                                         mce->wr_flag = 1;
                                 }
                         } while (++i < mcdi->clusters_per_block);
                 }
                 McFlushCache(mcman_badblock_port, mcman_badblock_slot);
         }
         else {
                 mcman_badblock = 0;
         }
         r = mcman_clearsuperblock(mcman_badblock_port, mcman_badblock_slot);
         return r;
 lbl_e168:
         mcman_badblock = 0;
         return sceMcResFailReplace;
 }
References MCDevInfo::alloc_end, MCDevInfo::alloc_offset, MCDevInfo::backup_block1, MCDevInfo::bad_block_list, McCacheEntry::cl_data, McFsEntry::cluster, McCacheEntry::cluster, MCDevInfo::cluster_size, MCDevInfo::clusters_per_block, MCDevInfo::clusters_per_card, McFsEntry::dir_entry, DPRINTF, MCDevInfo::FATentries_per_cluster, MCDevInfo::ifc_list, index(), McFsEntry::length, MCDevInfo::max_allocatable_clusters, Mc1stCacheEntSetWrFlagOff(), McFlushCache(), McGetFATentry(), mcman_badblock, mcman_badblock_port, mcman_badblock_slot, mcman_clearcache(), mcman_clearsuperblock(), mcman_devinfos, mcman_findfree2(), mcman_replacementcluster, McReadCluster(), McReadDirEntry(), McSetFATentry(), McFsEntry::mode, McFsEntry::name, s3, sceMcFileAttrSubdir, sceMcResFailReplace, sceMcResSucceed, strcmp(), and McCacheEntry::wr_flag.
Referenced by _start().
McRetOnly()
int McRetOnly (int fd)
Definition at line 3179 of file main.c.
 {
 #ifdef DEBUG
         DPRINTF("mcman: McRetOnly param %x\n", fd);
 #endif
         return sceMcResSucceed;
 }
References DPRINTF, and sceMcResSucceed.
McSeek()
int McSeek (int fd, int offset, int origin)
Definition at line 767 of file main.c.
 {
         register int r;
         register MC_FHANDLE *fh;
 #ifdef DEBUG
         DPRINTF("mcman: McSeek fd %d offset %d origin %d\n", fd, offset, origin);
 #endif
         if (!((u32)fd < MAX_FDHANDLES))
                 return sceMcResDeniedPermit;
         fh = (MC_FHANDLE *)&mcman_fdhandles[fd];
         if (!fh->status)
                 return sceMcResDeniedPermit;
         r = McDetectCard(fh->port, fh->slot);
         if (r != sceMcResSucceed)
                 return r;
         switch (origin) {
                 default:
                 case SEEK_CUR:
                         r = fh->position + offset;
                         break;
                 case SEEK_SET:
                         r = offset;
                         break;
                 case SEEK_END:
                         r = fh->filesize + offset;
                         break;
         }
         return fh->position = (r < 0) ? 0 : r;
 }
References DPRINTF, MC_FHANDLE::filesize, MAX_FDHANDLES, McDetectCard(), mcman_fdhandles, MC_FHANDLE::port, MC_FHANDLE::position, sceMcResDeniedPermit, sceMcResSucceed, SEEK_CUR, SEEK_END, SEEK_SET, MC_FHANDLE::slot, and MC_FHANDLE::status.
Referenced by mc_lseek().
McSetDirEntryState()
int McSetDirEntryState (int port, int slot, int cluster, int fsindex, int flags)
Definition at line 2177 of file main.c.
 {
         register int r, i, fat_index;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         McFsEntry *fse;
         int fat_entry;
         r = McReadDirEntry(port, slot, cluster, fsindex, &fse);
         if (r != sceMcResSucceed)
                 return r;
         if (fse->name[0] == '.') {
                 if ((fse->name[1] == 0) || (fse->name[1] == '.'))
                         return sceMcResNoEntry;
         }
         i = 0;
         do {
                 if (mcman_fdhandles[i].status == 0)
                         continue;
                 if ((mcman_fdhandles[i].port != port) || (mcman_fdhandles[i].slot != slot))
                         continue;
                 if (mcman_fdhandles[i].field_20 != cluster)
                         continue;
                 if (mcman_fdhandles[i].field_24 == fsindex)
                         return sceMcResDeniedPermit;
         } while (++i < MAX_FDHANDLES);
         if (flags == 0)
                 fse->mode = fse->mode & (sceMcFileAttrExists - 1);
         else
                 fse->mode = fse->mode | sceMcFileAttrExists;
         Mc1stCacheEntSetWrFlagOff();
         fat_index = fse->cluster;
         if (fat_index >= 0) {
                 if (fat_index < mcdi->unknown2)
                         mcdi->unknown2 = fat_index;
                 mcdi->unknown5 = -1;
                 do {
                         r = McGetFATentry(port, slot, fat_index, &fat_entry);
                         if (r != sceMcResSucceed)
                                 return r;
                         if (flags == 0) {
                                 fat_entry &= 0x7fffffff;
                                 if (fat_index < mcdi->unknown2)
                                         mcdi->unknown2 = fat_entry;
                         }
                         else
                                 fat_entry |= 0x80000000;
                         r = McSetFATentry(port, slot, fat_index, fat_entry);
                         if (r != sceMcResSucceed)
                                 return r;
                         fat_index = fat_entry & 0x7fffffff;
                 } while (fat_index != 0x7fffffff);
         }
         return sceMcResSucceed;
 }
References McFsEntry::cluster, MAX_FDHANDLES, Mc1stCacheEntSetWrFlagOff(), McGetFATentry(), mcman_devinfos, mcman_fdhandles, McReadDirEntry(), McSetFATentry(), McFsEntry::mode, McFsEntry::name, sceMcFileAttrExists, sceMcResDeniedPermit, sceMcResNoEntry, sceMcResSucceed, status, MCDevInfo::unknown2, and MCDevInfo::unknown5.
Referenced by _start(), mcman_delete2(), and mcman_open2().
McSetFATentry()
int McSetFATentry (int port, int slot, int fat_index, int fat_entry)
Definition at line 3798 of file main.c.
 {
         register int r, ifc_index, indirect_index, indirect_offset, fat_offset;
         McCacheEntry *mce;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         //DPRINTF("mcman: McSetFATentry port%d slot%d fat_index %x fat_entry %x\n", port, slot, fat_index, fat_entry);
         indirect_index = fat_index / mcdi->FATentries_per_cluster;
         fat_offset = fat_index % mcdi->FATentries_per_cluster;
         ifc_index = indirect_index / mcdi->FATentries_per_cluster;
         indirect_offset = indirect_index % mcdi->FATentries_per_cluster;
         r = McReadCluster(port, slot, mcdi->ifc_list[ifc_index], &mce);
         if (r != sceMcResSucceed)
                 return -75;
         McFatCluster *fc = (McFatCluster *)mce->cl_data;
         r = McReadCluster(port, slot, fc->entry[indirect_offset], &mce);
         if (r != sceMcResSucceed)
                 return -76;
         fc = (McFatCluster *)mce->cl_data;
         fc->entry[fat_offset] = fat_entry;
         mce->wr_flag = 1;
         return sceMcResSucceed;
 }
References McCacheEntry::cl_data, McFatCluster::entry, MCDevInfo::FATentries_per_cluster, MCDevInfo::ifc_list, mcman_devinfos, McReadCluster(), sceMcResSucceed, and McCacheEntry::wr_flag.
Referenced by _start(), mcman_fatWseek(), mcman_format2(), mcman_open2(), McReplaceBadBlock(), and McSetDirEntryState().
McSetFileInfo()
int McSetFileInfo (int port, int slot, char * filename, sceMcTblGetDir * info, int flags)
Definition at line 977 of file main.c.
 {
         register int r;
         r = McDetectCard(port, slot);
         if (r != sceMcResSucceed)
                 return r;
         if (mcman_devinfos[port][slot].cardtype == sceMcTypePS2)
                 r = mcman_setinfo2(port, slot, filename, info, flags);
         else
                 r = mcman_setinfo1(port, slot, filename, info, flags);
         if (r < -9) {
                 mcman_invhandles(port, slot);
                 mcman_clearcache(port, slot);
         }
         if (r == sceMcResSucceed) {
                 r = McFlushCache(port, slot);
                 if (r < -9) {
                         mcman_invhandles(port, slot);
                         mcman_clearcache(port, slot);
                 }
         }
         return r;
 }
References McDetectCard(), McFlushCache(), mcman_clearcache(), mcman_devinfos, mcman_invhandles(), mcman_setinfo1(), mcman_setinfo2(), sceMcResSucceed, and sceMcTypePS2.
Referenced by mc_chstat().
McSetPS1CardFlag()
void McSetPS1CardFlag (int flag)
Definition at line 300 of file main.c.
 {
 #ifdef DEBUG
         DPRINTF("mcman: McSetPS1CardFlag flag %x\n", flag);
 #endif
         PS1CardFlag = flag;
 }
References DPRINTF, and PS1CardFlag.
McUnformat()
int McUnformat (int port, int slot)
Definition at line 1079 of file main.c.
 {
         register int r;
         mcman_invhandles(port, slot);
         r = McDetectCard(port, slot);
         if (r < -2)
                 return r;
         mcman_clearcache(port, slot);
         if (mcman_devinfos[port][slot].cardtype == sceMcTypePS2)
                 r = mcman_unformat2(port, slot);
         else
                 r = mcman_unformat1(port, slot);
         mcman_devinfos[port][slot].cardform = 0;
         if (r < -9) {
                 mcman_invhandles(port, slot);
                 mcman_clearcache(port, slot);
         }
         return r;
 }
References MCDevInfo::cardform, McDetectCard(), mcman_clearcache(), mcman_devinfos, mcman_invhandles(), mcman_unformat1(), mcman_unformat2(), and sceMcTypePS2.
McWrite()
int McWrite (int fd, void * buf, int length)
Definition at line 840 of file main.c.
 {
         register int r;
         register MC_FHANDLE *fh;
         if (!((u32)fd < MAX_FDHANDLES))
                 return sceMcResDeniedPermit;
         fh = (MC_FHANDLE *)&mcman_fdhandles[fd];
         if (!fh->status)
                 return sceMcResDeniedPermit;
         if (!fh->wrflag)
                 return sceMcResDeniedPermit;
         r = McDetectCard(fh->port, fh->slot);
         if (r != sceMcResSucceed)
                 return r;
         if (mcman_devinfos[fh->port][fh->slot].cardtype == sceMcTypePS2)
                 r = mcman_write2(fd, buf, length);
         else
                 r = mcman_write1(fd, buf, length);
         if (r < 0)
                 fh->status = 0;
         if (r < -9) {
                 mcman_invhandles(fh->port, fh->slot);
                 mcman_clearcache(fh->port, fh->slot);
         }
         return r;
 }
References MCDevInfo::cardtype, MAX_FDHANDLES, McDetectCard(), mcman_clearcache(), mcman_devinfos, mcman_fdhandles, mcman_invhandles(), mcman_write1(), mcman_write2(), MC_FHANDLE::port, sceMcResDeniedPermit, sceMcResSucceed, sceMcTypePS2, MC_FHANDLE::slot, MC_FHANDLE::status, and MC_FHANDLE::wrflag.
Referenced by mc_write().
McWritePage()
int McWritePage (int port, int slot, int page, void * pagebuf, void * eccbuf)
Definition at line 454 of file mcsio2.c.
 {
         register int index, count, retries;
         u8 *p_pagebuf = (u8 *)pagebuf;
         u8 *p = mcman_sio2packet.out_dma.addr;
         count = (mcman_devinfos[port][slot].pagesize + 127) >> 7;
         retries = 0;
         do {
                 if (retries > 0)
                         mcman_cardchanged(port, slot);
                 sio2packet_add(port, slot, 0xffffffff, NULL);
                 sio2packet_add(port, slot, 0x03, (u8 *)&page);
                 index = 0;
                 while (index < count) {
                 sio2packet_add(port, slot, 0x0a, (u8 *)&p_pagebuf[index << 7]);
                         index++;
                 }
                 if (mcman_devinfos[port][slot].cardflags & CF_USE_ECC) {
                 // if memcard have ECC support
                         sio2packet_add(port, slot, 0x0e, eccbuf);
                 }
                 sio2packet_add(port, slot, 0xfffffffe, NULL);
                 mcman_sio2transfer(port, slot, &mcman_sio2packet);
                 if (((mcman_sio2packet.stat6c & 0xF000) != 0x1000) || (p[8] != 0x5a))
                         continue;
                 index = 0;
                 while (index < count) {
                         if (p[0x94 + 128 + 1 + ((index + (index << 3)) << 4)] != 0x5a)
                                 break;
                         index++;
                 }
                 if (index < count)
                         continue;
                 if (mcman_devinfos[port][slot].cardflags & CF_USE_ECC) {
                 // if memcard have ECC support
                         index++;
                 if (p[5 + ((index + (index << 3)) << 4) + mcman_sparesize(port, slot)] != 0x5a)
                         continue;
                 }
                 sio2packet_add(port, slot, 0xffffffff, NULL);
                 sio2packet_add(port, slot, 0x0c, NULL);
                 sio2packet_add(port, slot, 0xfffffffe, NULL);
                 mcman_sio2transfer(port, slot, &mcman_sio2packet);
                 if (((mcman_sio2packet.stat6c & 0xF000) != 0x1000) || (p[3] != 0x5a))
                         continue;
                 return sceMcResSucceed;
         } while (++retries < 5);
         if (p[3] == 0x66)
                 return sceMcResFailReplace;
         return sceMcResNoFormat;
 }
References _sio2_dma_arg::addr, CF_USE_ECC, index(), mcman_cardchanged(), mcman_devinfos, mcman_sio2packet, mcman_sio2transfer, mcman_sparesize(), NULL, sio2_transfer_data_t::out_dma, MCDevInfo::pagesize, sceMcResFailReplace, sceMcResNoFormat, sceMcResSucceed, sio2packet_add(), and sio2_transfer_data_t::stat6c.
Referenced by McCheckBlock(), mcman_checkBackupBlocks(), mcman_fillbackupblock1(), mcman_flushcacheentry(), mcman_unformat2(), and mcman_writecluster().
McWritePS1PDACard()
int McWritePS1PDACard (int port, int slot, int page, void * buf)
Definition at line 997 of file mcsio2.c.
 {
         register int i, retries;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         u8 *p;
 #ifdef DEBUG
         //DPRINTF("mcman: McWritePS1PDACard port%d slot%d page %x\n", port, slot, page);
 #endif
         mcman_sio2packet_PS1PDA.regdata[0] = 0;
         mcman_sio2packet_PS1PDA.regdata[0] = (((port & 1) + 2) & 3) | 0x02288a40;
         mcman_sio2packet_PS1PDA.in_size = 138;
         mcman_sio2packet_PS1PDA.out_size = 138;
         mcman_sio2packet_PS1PDA.regdata[1] = 0;
         for (i = 0; i < 20; i++) {
                 if (mcdi->bad_block_list[i] == page)
                         page += 36;
         }
         mcman_sio2inbufs_PS1PDA[0] = 0x81;
         mcman_sio2inbufs_PS1PDA[1] = 0x57;
         mcman_sio2inbufs_PS1PDA[4] = (u8)(page >> 8);
         mcman_sio2inbufs_PS1PDA[5] = (u8)page;
         p = (u8 *)buf;
         for (i = 0; i < 128; i++)
                 mcman_sio2inbufs_PS1PDA[6 + i] = p[i];
         mcman_sio2inbufs_PS1PDA[4 + 130] = mcman_calcEDC(&mcman_sio2inbufs_PS1PDA[4], 130);
         retries = 0;
         do {
                 mcman_timercount = (u32)(GetTimerCounter(timer_ID) - mcman_timercount);
                 u32 hi, lo;
                 long_multiply(mcman_timercount, 0x3e0f83e1, &hi, &lo);
                 if ((u32)((hi >> 3) < mcman_timerthick))
                         DelayThread(mcman_timerthick - (hi >> 3));
                 mcman_sio2transfer(port, slot, &mcman_sio2packet_PS1PDA);
                 mcman_timercount = GetTimerCounter(timer_ID);
                 mcman_timerthick = 20000;
                 if (((mcman_sio2packet_PS1PDA.stat6c & 0xf000) == 0x1000) \
                                 && (mcman_sio2outbufs_PS1PDA[2] == 0x5a) \
                                         && (mcman_sio2outbufs_PS1PDA[3] == 0x5d) \
                                                 && (mcman_sio2outbufs_PS1PDA[137] == 0x47)) {
                         break;
                 }
         } while (++retries < 5);
         if (retries >= 5)
                 return sceMcResNoEntry;
         if ((mcman_sio2outbufs_PS1PDA[1] != 0) && (mcman_sio2outbufs_PS1PDA[1] != 8))
                 return sceMcResFullDevice;
         return sceMcResSucceed;
 }
References MCDevInfo::bad_block_list, DelayThread(), GetTimerCounter(), sio2_transfer_data_t::in_size, long_multiply(), mcman_calcEDC(), mcman_devinfos, mcman_sio2inbufs_PS1PDA, mcman_sio2outbufs_PS1PDA, mcman_sio2packet_PS1PDA, mcman_sio2transfer, mcman_timercount, mcman_timerthick, sio2_transfer_data_t::out_size, sio2_transfer_data_t::regdata, sceMcResFullDevice, sceMcResNoEntry, sceMcResSucceed, sio2_transfer_data_t::stat6c, and timer_ID.
Referenced by mcman_fillPS1backuparea(), mcman_flushcacheentry(), mcman_format1(), mcman_probePS1Card(), mcman_PS1pagetest(), and mcman_unformat1().