ps2sdk: iop/memorycard/mcserv/src/mcman_imports.h File Reference
mcman_imports.h File Reference
#include "types.h"
#include "irx.h"
Macros
#define MCMAN 0
#define XMCMAN 1
Variables
char mcman_modname [8] = "mcman\0\0\0"
int mcman_type = MCMAN
int(* pMcDetectCard)(int port, int slot)
int(* pMcOpen)(int port, int slot, char *filename, int flags)
int(* pMcClose)(int fd)
int(* pMcRead)(int fd, void *buf, int length)
int(* pMcWrite)(int fd, void *buf, int length)
int(* pMcSeek)(int fd, int offset, int origin)
int(* pMcFormat)(int port, int slot)
int(* pMcGetDir)(int port, int slot, char *dirname, int flags, int nument, sceMcTblGetDir *info)
int(* pMcDelete)(int port, int slot, char *filename, int flags)
int(* pMcFlush)(int fd)
int(* pMcChDir)(int port, int slot, char *newdir, char *currentdir)
int(* pMcSetFileInfo)(int port, int slot, char *filename, sceMcTblGetDir *info, int flags)
int(* pMcEraseBlock)(int port, int block, void **pagebuf, void *eccbuf)
int(* pMcReadPage)(int port, int slot, int page, void *buf)
int(* pMcWritePage)(int port, int slot, int page, void *pagebuf, void *eccbuf)
void(* pMcDataChecksum)(void *buf, void *ecc)
int(* pMcReadPS1PDACard)(int port, int slot, int page, void *buf)
int(* pMcWritePS1PDACard)(int port, int slot, int page, void *buf)
int(* pMcUnformat)(int port, int slot)
int(* pMcRetOnly)(int fd)
int(* pMcGetFreeClusters)(int port, int slot)
int(* pMcGetMcType)(int port, int slot)
void(* pMcSetPS1CardFlag)(int flag)
int(* pMcDetectCard2)(int port, int slot)
int(* pMcGetFormat)(int port, int slot)
int(* pMcGetEntSpace)(int port, int slot, char *dirname)
int(* pMcReplaceBadBlock)(void)
struct irx_id *(* pMcGetModuleInfo)(void)
int(* pMcCheckBlock)(int port, int slot, int block)
Macro Definition Documentation
MCMAN
#define MCMAN 0
Definition at line 7 of file mcman_imports.h.
XMCMAN
#define XMCMAN 1
Definition at line 8 of file mcman_imports.h.
Variable Documentation
mcman_modname
char mcman_modname[8] = "mcman\0\0\0"
Definition at line 10 of file mcman_imports.h.
Referenced by _start().
mcman_type
int mcman_type = MCMAN
Definition at line 11 of file mcman_imports.h.
Referenced by _McInit(), _start(), cb_rpc_S_0400(), and sceMcInit().
pMcChDir
int(* pMcChDir) (int port, int slot, char *newdir, char *currentdir) (int port, int slot, char * newdir, char * currentdir)
Definition at line 23 of file mcman_imports.h.
Referenced by _McChDir(), and _start().
pMcCheckBlock
int(* pMcCheckBlock) (int port, int slot, int block) (int port, int slot, int block)
Definition at line 43 of file mcman_imports.h.
Referenced by _McCheckBlock(), and _start().
pMcClose
int(* pMcClose) (int fd) (int fd)
Definition at line 15 of file mcman_imports.h.
Referenced by _McClose(), and _start().
pMcDataChecksum
void(* pMcDataChecksum) (void *buf, void *ecc) (void * buf, void * ecc)
Definition at line 28 of file mcman_imports.h.
Referenced by _McEraseBlock(), _McWritePage(), and _start().
pMcDelete
int(* pMcDelete) (int port, int slot, char *filename, int flags) (int port, int slot, char * filename, int flags)
Definition at line 21 of file mcman_imports.h.
Referenced by _McDelete(), and _start().
pMcDetectCard
int(* pMcDetectCard) (int port, int slot) (int port, int slot)
Definition at line 13 of file mcman_imports.h.
Referenced by _McGetInfo(), and _start().
pMcDetectCard2
int(* pMcDetectCard2) (int port, int slot) (int port, int slot)
Definition at line 38 of file mcman_imports.h.
Referenced by _McGetInfo2(), and _start().
pMcEraseBlock
int(* pMcEraseBlock) (int port, int block, void **pagebuf, void *eccbuf) (int port, int block, void ** pagebuf, void * eccbuf)
Definition at line 25 of file mcman_imports.h.
Referenced by _McEraseBlock(), and _start().
pMcFlush
int(* pMcFlush) (int fd) (int fd)
Definition at line 22 of file mcman_imports.h.
Referenced by _McFlush(), and _start().
pMcFormat
int(* pMcFormat) (int port, int slot) (int port, int slot)
Definition at line 19 of file mcman_imports.h.
Referenced by _McFormat(), and _start().
pMcGetDir
int(* pMcGetDir) (int port, int slot, char *dirname, int flags, int nument, sceMcTblGetDir *info) (int port, int slot, char * dirname, int flags, int nument, sceMcTblGetDir * info)
Definition at line 20 of file mcman_imports.h.
Referenced by _McGetDir(), and _start().
pMcGetEntSpace
int(* pMcGetEntSpace) (int port, int slot, char *dirname) (int port, int slot, char * dirname)
Definition at line 40 of file mcman_imports.h.
Referenced by _McGetEntSpace(), and _start().
pMcGetFormat
int(* pMcGetFormat) (int port, int slot) (int port, int slot)
Definition at line 39 of file mcman_imports.h.
Referenced by _McGetInfo2(), and _start().
pMcGetFreeClusters
int(* pMcGetFreeClusters) (int port, int slot) (int port, int slot)
Definition at line 33 of file mcman_imports.h.
Referenced by _McGetInfo(), _McGetInfo2(), and _start().
pMcGetMcType
int(* pMcGetMcType) (int port, int slot) (int port, int slot)
Definition at line 34 of file mcman_imports.h.
Referenced by _McEraseBlock(), _McGetInfo(), _McGetInfo2(), _McReadPage(), and _start().
pMcGetModuleInfo
struct irx_id*(* pMcGetModuleInfo) (void) (void)
Definition at line 41 of file mcman_imports.h.
Referenced by _start(), and sceMcInit().
pMcOpen
int(* pMcOpen) (int port, int slot, char *filename, int flags) (int port, int slot, char * filename, int flags)
Definition at line 14 of file mcman_imports.h.
Referenced by _McOpen(), and _start().
pMcRead
int(* pMcRead) (int fd, void *buf, int length) (int fd, void * buf, int length)
Definition at line 16 of file mcman_imports.h.
Referenced by _McRead(), _McRead2(), and _start().
pMcReadPage
int(* pMcReadPage) (int port, int slot, int page, void *buf) (int port, int slot, int page, void * buf)
Definition at line 26 of file mcman_imports.h.
Referenced by _McReadPage(), and _start().
pMcReadPS1PDACard
int(* pMcReadPS1PDACard) (int port, int slot, int page, void *buf) (int port, int slot, int page, void * buf)
Definition at line 29 of file mcman_imports.h.
Referenced by _McReadPage(), and _start().
pMcReplaceBadBlock
int(* pMcReplaceBadBlock) (void) (void)
Definition at line 41 of file mcman_imports.h.
Referenced by _start(), and cb_rpc_S_0400().
pMcRetOnly
int(* pMcRetOnly) (int fd) (int fd)
Definition at line 32 of file mcman_imports.h.
Referenced by _McInit(), and _start().
pMcSeek
int(* pMcSeek) (int fd, int offset, int origin) (int fd, int offset, int origin)
Definition at line 18 of file mcman_imports.h.
Referenced by _McSeek(), and _start().
pMcSetFileInfo
int(* pMcSetFileInfo) (int port, int slot, char *filename, sceMcTblGetDir *info, int flags) (int port, int slot, char * filename, sceMcTblGetDir * info, int flags)
Definition at line 24 of file mcman_imports.h.
Referenced by _McSetFileInfo(), and _start().
pMcSetPS1CardFlag
void(* pMcSetPS1CardFlag) (int flag) (int flag)
Definition at line 35 of file mcman_imports.h.
Referenced by _McInit(), and _start().
pMcUnformat
int(* pMcUnformat) (int port, int slot) (int port, int slot)
Definition at line 31 of file mcman_imports.h.
Referenced by _McUnformat(), and _start().
pMcWrite
int(* pMcWrite) (int fd, void *buf, int length) (int fd, void * buf, int length)
Definition at line 17 of file mcman_imports.h.
Referenced by _McWrite(), and _start().
pMcWritePage
int(* pMcWritePage) (int port, int slot, int page, void *pagebuf, void *eccbuf) (int port, int slot, int page, void * pagebuf, void * eccbuf)
Definition at line 27 of file mcman_imports.h.
Referenced by _McEraseBlock(), _McWritePage(), and _start().
pMcWritePS1PDACard
int(* pMcWritePS1PDACard) (int port, int slot, int page, void *buf) (int port, int slot, int page, void * buf)
Definition at line 30 of file mcman_imports.h.
Referenced by _McEraseBlock(), and _start().