ps2sdk: iop/memorycard/mcserv/src/mcserv.c File Reference
mcserv.c File Reference
#include "mcserv.h"
Macros
#define DPRINTF(args...) printf(args)
#define MCSERV_BUFSIZE 8192
Functions
IRX_ID (MODNAME, 2, 8)
int _start (int argc, const char **argv)
void thread_rpc_S_0400 (void *arg)
void * cb_rpc_S_0400 (u32 fno, void *buf, int size)
int sceMcInit (void)
int sceMcOpen (void)
int sceMcClose (void)
int sceMcRead (void)
int sceMcRead2 (void)
int sceMcWrite (void)
int sceMcSeek (void)
int sceMcGetDir (void)
int sceMcFormat (void)
int sceMcUnformat (void)
int sceMcGetInfo (void)
int sceMcGetInfo2 (void)
int sceMcDelete (void)
int sceMcFlush (void)
int sceMcChDir (void)
int sceMcEraseBlock (void)
int sceMcReadPage (void)
int sceMcWritePage (void)
int sceMcSetFileInfo (void)
int sceMcGetEntSpace (void)
int sceMcCheckBlock (void)
int _McInit (void *rpc_buf)
int _McOpen (void *rpc_buf)
int _McClose (void *rpc_buf)
int _McSeek (void *rpc_buf)
int _McRead (void *rpc_buf)
int _McRead2 (void *rpc_buf)
int _McWrite (void *rpc_buf)
int _McGetDir (void *rpc_buf)
int _McChDir (void *rpc_buf)
int _McFormat (void *rpc_buf)
int _McUnformat (void *rpc_buf)
int _McGetInfo (void *rpc_buf)
int _McGetInfo2 (void *rpc_buf)
int _McGetEntSpace (void *rpc_buf)
int _McDelete (void *rpc_buf)
int _McFlush (void *rpc_buf)
int _McEraseBlock (void *rpc_buf)
int _McReadPage (void *rpc_buf)
int _McWritePage (void *rpc_buf)
int _McSetFileInfo (void *rpc_buf)
int _McCheckBlock (void *rpc_buf)
Variables
static const u8 XMCSERV_RpcCmd [2][16]
static void * rpc_funcs_array [21]
static int mcserv_tidS_0400
static SifRpcDataQueue_t mcserv_qdS_0400
static SifRpcServerData_t mcserv_sdS_0400
static u8 mcserv_rpc_buf [2048]
static mcRpcStat_t rpc_stat
static u8 mcserv_buf [MCSERV_BUFSIZE]
struct irx_export_table _exp_mcserv
Macro Definition Documentation
DPRINTF
#define DPRINTF (args...) printf(args)
Definition at line 20 of file mcserv.c.
MCSERV_BUFSIZE
#define MCSERV_BUFSIZE 8192
Definition at line 95 of file mcserv.c.
Function Documentation
_McChDir()
int _McChDir (void * rpc_buf)
Definition at line 829 of file mcserv.c.
 {
         mcNameParam_t *nP = (mcNameParam_t *)rpc_buf;
         register int status, r;
         SifDmaTransfer_t dmaStruct;
         int intStatus;
 #ifdef DEBUG
         DPRINTF("mcserv: _McChDir port%d slot%d newdir %s\n", nP->port, nP->slot, nP->name);
 #endif
         r = pMcChDir(nP->port, nP->slot, nP->name, (char *)mcserv_buf);
         dmaStruct.src = (void *)mcserv_buf;
         dmaStruct.dest = (void *)nP->curdir;
         dmaStruct.size = 1024;
         dmaStruct.attr = 0;
         CpuSuspendIntr(&intStatus);
         status = sceSifSetDma(&dmaStruct, 1);
         CpuResumeIntr(intStatus);
         while (sceSifDmaStat(status) >= 0)
                 DelayThread(100);
         return r;
 }
References SifDmaTransfer_t::attr, CpuResumeIntr(), CpuSuspendIntr(), mcNameParam_t::curdir, DelayThread(), SifDmaTransfer_t::dest, DPRINTF, mcserv_buf, mcNameParam_t::name, pMcChDir, mcNameParam_t::port, sceSifDmaStat(), sceSifSetDma(), SifDmaTransfer_t::size, mcNameParam_t::slot, SifDmaTransfer_t::src, and status.
Referenced by sceMcChDir().
_McCheckBlock()
int _McCheckBlock (void * rpc_buf)
Definition at line 1221 of file mcserv.c.
 {
         mcDescParam_t *dP = (mcDescParam_t *)rpc_buf;
 #ifdef DEBUG
         DPRINTF("mcserv: _McCheckBlock port%d slot%d block %d\n", dP->port, dP->slot, dP->offset);
 #endif
         return pMcCheckBlock(dP->port, dP->slot, dP->offset);
 }
References DPRINTF, mcDescParam_t::offset, pMcCheckBlock, mcDescParam_t::port, and mcDescParam_t::slot.
Referenced by sceMcCheckBlock().
_McClose()
int _McClose (void * rpc_buf)
Definition at line 434 of file mcserv.c.
 {
         mcDescParam_t *dP = (mcDescParam_t *)rpc_buf;
 #ifdef DEBUG
         DPRINTF("mcserv: _McClose fd %d\n", dP->fd);
 #endif
         return pMcClose(dP->fd);
 }
References DPRINTF, mcDescParam_t::fd, and pMcClose.
Referenced by sceMcClose().
_McDelete()
int _McDelete (void * rpc_buf)
Definition at line 1005 of file mcserv.c.
 {
         mcNameParam_t *nP = (mcNameParam_t *)rpc_buf;
 #ifdef DEBUG
         DPRINTF("mcserv: _McDelete port%d slot%d file %s flags %d\n", nP->port, nP->slot, nP->name, nP->flags);
 #endif
         return pMcDelete(nP->port, nP->slot, nP->name, nP->flags);
 }
References DPRINTF, mcNameParam_t::flags, mcNameParam_t::name, pMcDelete, mcNameParam_t::port, and mcNameParam_t::slot.
Referenced by sceMcDelete().
_McEraseBlock()
int _McEraseBlock (void * rpc_buf)
Definition at line 1029 of file mcserv.c.
 {
         mcDescParam_t *dP = (mcDescParam_t *)rpc_buf;
         register int pagenum, r;
         u8 eccbuf[16];
 #ifdef DEBUG
         DPRINTF("mcserv: _McEraseBlock port%d slot%d offset %d\n", dP->port, dP->slot, dP->offset);
 #endif
         dP->port = (dP->port & 1) + 2;
         if (pMcGetMcType(dP->port, dP->slot) == 2) {
                 r = pMcEraseBlock(dP->port, dP->offset, NULL, NULL);
                 if (r != 0)
                         return r;
                 if (dP->origin == -1)
                         return r;
                 memset(mcserv_buf, dP->origin, 512);
                 pMcDataChecksum(&mcserv_buf[0], &eccbuf[0]);
                 pMcDataChecksum(&mcserv_buf[128], &eccbuf[3]);
                 pMcDataChecksum(&mcserv_buf[256], &eccbuf[6]);
                 pMcDataChecksum(&mcserv_buf[384], &eccbuf[9]);
                 pagenum = 0;
                 do {
                         r = pMcWritePage(dP->port, dP->slot, (dP->offset << 4) + pagenum, mcserv_buf, eccbuf);
                 } while (++pagenum < 16);   // <-- and the last page of the block ???
                 return r;
         }
         memset(mcserv_buf, dP->origin, 128);
         r = pMcWritePS1PDACard(dP->port, dP->slot, dP->offset, mcserv_buf);
         return r;
 }
References DPRINTF, mcserv_buf, memset(), NULL, mcDescParam_t::offset, mcDescParam_t::origin, pMcDataChecksum, pMcEraseBlock, pMcGetMcType, pMcWritePage, pMcWritePS1PDACard, mcDescParam_t::port, and mcDescParam_t::slot.
Referenced by sceMcEraseBlock().
_McFlush()
int _McFlush (void * rpc_buf)
Definition at line 1017 of file mcserv.c.
 {
         mcDescParam_t *dP = (mcDescParam_t *)rpc_buf;
 #ifdef DEBUG
         DPRINTF("mcserv: _McFlush fd %d\n", dP->fd);
 #endif
         return pMcFlush(dP->fd);
 }
References DPRINTF, mcDescParam_t::fd, and pMcFlush.
Referenced by sceMcFlush().
_McFormat()
int _McFormat (void * rpc_buf)
Definition at line 858 of file mcserv.c.
 {
         mcDescParam_t *dP = (mcDescParam_t *)rpc_buf;
 #ifdef DEBUG
         DPRINTF("mcserv: _McFormat port%d slot%d\n", dP->port, dP->slot);
 #endif
         return pMcFormat(dP->port, dP->slot);
 }
References DPRINTF, pMcFormat, mcDescParam_t::port, and mcDescParam_t::slot.
Referenced by sceMcFormat().
_McGetDir()
int _McGetDir (void * rpc_buf)
Definition at line 777 of file mcserv.c.
 {
         mcNameParam_t *nP = (mcNameParam_t *)rpc_buf;
         register int status, file_entries, flags, r;
         SifDmaTransfer_t dmaStruct;
         int intStatus;
 #ifdef DEBUG
         DPRINTF("mcserv: _McGetDir port%d slot%d dir %s flags %d maxent %d mcT addr %x\n", nP->port, nP->slot, nP->name, nP->flags, nP->maxent, (int)nP->mcT);
 #endif
         status = 0;
         file_entries = 0;
         flags = nP->flags;
         nP->maxent--;
         while (nP->maxent > -1) {
                 r = pMcGetDir(nP->port, nP->slot, nP->name, flags & 0xffff, 1, (sceMcTblGetDir *)mcserv_buf);
                 if (r < 0)
                         return r;
                 if (r == 0)
                         goto dma_wait;
                 file_entries++;
                 dmaStruct.src = (void *)mcserv_buf;
                 dmaStruct.dest = (void *)nP->mcT;
                 dmaStruct.size = sizeof (sceMcTblGetDir);
                 dmaStruct.attr = 0;
                 CpuSuspendIntr(&intStatus);
                 status = sceSifSetDma(&dmaStruct, 1);
                 CpuResumeIntr(intStatus);
                 flags = 1;
                 nP->mcT++;
                 nP->maxent--;
         }
 dma_wait:
         if (status == 0)
                 return file_entries;
         while (sceSifDmaStat(status) >= 0)
                 DelayThread(100);
         return file_entries;
 }
References SifDmaTransfer_t::attr, CpuResumeIntr(), CpuSuspendIntr(), DelayThread(), SifDmaTransfer_t::dest, DPRINTF, mcNameParam_t::flags, mcNameParam_t::maxent, mcserv_buf, mcNameParam_t::mcT, mcNameParam_t::name, pMcGetDir, mcNameParam_t::port, sceSifDmaStat(), sceSifSetDma(), SifDmaTransfer_t::size, mcNameParam_t::slot, SifDmaTransfer_t::src, and status.
Referenced by sceMcGetDir().
_McGetEntSpace()
int _McGetEntSpace (void * rpc_buf)
Definition at line 993 of file mcserv.c.
 {
         mcNameParam_t *nP = (mcNameParam_t *)rpc_buf;
 #ifdef DEBUG
         DPRINTF("mcserv: _McGetEntSpace port%d slot%d dirname %s\n", nP->port, nP->slot, nP->name);
 #endif
         return pMcGetEntSpace(nP->port, nP->slot, nP->name);
 }
References DPRINTF, mcNameParam_t::name, pMcGetEntSpace, mcNameParam_t::port, and mcNameParam_t::slot.
Referenced by sceMcGetEntSpace().
_McGetInfo()
int _McGetInfo (void * rpc_buf)
Definition at line 882 of file mcserv.c.
 {
         mcDescParam_t *dP = (mcDescParam_t *)rpc_buf;
         register int status, mc_free, r;
         mcEndParam_t eP;
         SifDmaTransfer_t dmaStruct;
         int intStatus;
 #ifdef DEBUG
         DPRINTF("mcserv: _McGetInfo port%d slot%d\n", dP->port, dP->slot);
 #endif
         mc_free = 0;
         r = pMcDetectCard(dP->port, dP->slot);
         if (dP->size > 0)
                 eP.type = pMcGetMcType(dP->port, dP->slot);
         eP.free = 0;
         if (r >= -1) {
                 if (dP->offset == 0)
                         goto dma_transfer;
                 mc_free = pMcGetFreeClusters(dP->port, dP->slot);
                 if (mc_free >= 0)
                         eP.free = mc_free;
         }
 dma_transfer:
         dmaStruct.src = (void *)&eP;
         dmaStruct.dest = (void *)dP->param;
         dmaStruct.size = sizeof (mcEndParam_t);
         dmaStruct.attr = 0;
         CpuSuspendIntr(&intStatus);
         status = sceSifSetDma(&dmaStruct, 1);
         CpuResumeIntr(intStatus);
         while (sceSifDmaStat(status) >= 0)
                 DelayThread(100);
         if (mc_free < 0)
                 return mc_free;
         return r;
 }
References SifDmaTransfer_t::attr, CpuResumeIntr(), CpuSuspendIntr(), DelayThread(), SifDmaTransfer_t::dest, DPRINTF, mcEndParam_t::free, mcDescParam_t::offset, mcDescParam_t::param, pMcDetectCard, pMcGetFreeClusters, pMcGetMcType, mcDescParam_t::port, sceSifDmaStat(), sceSifSetDma(), mcDescParam_t::size, SifDmaTransfer_t::size, mcDescParam_t::slot, SifDmaTransfer_t::src, status, and mcEndParam_t::type.
Referenced by sceMcGetInfo().
_McGetInfo2()
int _McGetInfo2 (void * rpc_buf)
Definition at line 932 of file mcserv.c.
 {
         mcDescParam_t *dP = (mcDescParam_t *)rpc_buf;
         register int status, mc_free, r;
         mcEndParam2_t eP;
         SifDmaTransfer_t dmaStruct;
         int intStatus;
 #ifdef DEBUG
         DPRINTF("mcserv: _McGetInfo2 port%d slot%d\n", dP->port, dP->slot);
 #endif
         mc_free = 0;
         r = pMcDetectCard2(dP->port, dP->slot);
         if (dP->origin > 0)
                 eP.type = pMcGetMcType(dP->port, dP->slot);
         if (r < -1) {
                 eP.free = 0;
                 eP.formatted = 0;
                 goto dma_transfer;
         }
         if (dP->offset > 0) {
                 mc_free = pMcGetFreeClusters(dP->port, dP->slot);
                 if (mc_free < 0)
                         eP.free = 0;
                 else
                         eP.free = mc_free;
         }
         if (dP->size > 0) {
                 eP.formatted = 0;
                 if (pMcGetFormat(dP->port, dP->slot) > 0)
                         eP.formatted = 1;
         }
 dma_transfer:
         dmaStruct.src = (void *)&eP;
         dmaStruct.dest = (void *)dP->param;
         dmaStruct.size = sizeof (mcEndParam2_t);
         dmaStruct.attr = 0;
         CpuSuspendIntr(&intStatus);
         status = sceSifSetDma(&dmaStruct, 1);
         CpuResumeIntr(intStatus);
         while (sceSifDmaStat(status) >= 0)
                 DelayThread(100);
         if (mc_free < 0)
                 return mc_free;
         return r;
 }
References SifDmaTransfer_t::attr, CpuResumeIntr(), CpuSuspendIntr(), DelayThread(), SifDmaTransfer_t::dest, DPRINTF, mcEndParam2_t::formatted, mcEndParam2_t::free, mcDescParam_t::offset, mcDescParam_t::origin, mcDescParam_t::param, pMcDetectCard2, pMcGetFormat, pMcGetFreeClusters, pMcGetMcType, mcDescParam_t::port, sceSifDmaStat(), sceSifSetDma(), mcDescParam_t::size, SifDmaTransfer_t::size, mcDescParam_t::slot, SifDmaTransfer_t::src, status, and mcEndParam2_t::type.
Referenced by sceMcGetInfo2().
_McInit()
int _McInit (void * rpc_buf)
Definition at line 402 of file mcserv.c.
 {
         mcDescParam_t *dP = (mcDescParam_t *)rpc_buf;
         int ps1flag = 0;
 #ifdef DEBUG
         DPRINTF("mcserv: _McInit fd %d offset %d\n", dP->fd, dP->offset);
 #endif
         if (mcman_type == MCMAN) {
                 if (dP->offset == -217)
                         ps1flag = 1;
                 pMcSetPS1CardFlag(ps1flag);
         }
         return pMcRetOnly(dP->fd);
 }
References DPRINTF, mcDescParam_t::fd, MCMAN, mcman_type, mcDescParam_t::offset, pMcRetOnly, and pMcSetPS1CardFlag.
Referenced by sceMcInit().
_McOpen()
int _McOpen (void * rpc_buf)
Definition at line 422 of file mcserv.c.
 {
         mcNameParam_t *nP = (mcNameParam_t *)rpc_buf;
 #ifdef DEBUG
         DPRINTF("mcserv: _McOpen port%d slot%d file %s flags %d\n", nP->port, nP->slot, nP->name, nP->flags);
 #endif
         return pMcOpen(nP->port, nP->slot, nP->name, nP->flags);
 }
References DPRINTF, mcNameParam_t::flags, mcNameParam_t::name, pMcOpen, mcNameParam_t::port, and mcNameParam_t::slot.
Referenced by sceMcOpen().
_McRead()
int _McRead (void * rpc_buf)
Definition at line 458 of file mcserv.c.
 {
         mcDescParam_t *dP = (mcDescParam_t *)rpc_buf;
         register int file_offset, status;
         register int left_to_read, size_readed, size_to_read;
         mcEndParam_t eP;
         SifDmaTransfer_t dmaStruct;
         int intStatus;
         void *eedata;
 #ifdef DEBUG
         DPRINTF("mcserv: _McRead fd %d ee buffer addr %x size %d\n", dP->fd, (int)dP->buffer, dP->size);
 #endif
         eP.size1 = 0;
         eP.size2 = 0;
         eP.dest1 = NULL;
         eP.dest2 = NULL;
         size_readed = 0;
         file_offset = 0;
         eedata = dP->buffer;
         eP.size1 = dP->size;
         if (dP->size > 16)
                 eP.size1 = (((int)(eedata)-1) & 0xfffffff0) - ((int)(eedata) - 16);
         eP.size2 = (dP->size - eP.size1) & 0x0f;
         left_to_read = (dP->size - eP.size1) - eP.size2;
         if (eP.size2 != 0)
                 eP.dest2 = (void *)(eedata + eP.size1 + left_to_read);
         if (eP.size1 != 0) {
                 size_readed = pMcRead(dP->fd, eP.src1, eP.size1);
                 if (size_readed < 0) {
                         eP.size1 = 0;
                         eP.size2 = 0;
                         goto dma_transfer2;
                 }
                 else {
                         file_offset = size_readed;
                         eP.dest1 = eedata;
                         eedata += size_readed;
                         if (size_readed != eP.size1) {
                                 eP.size1 = size_readed;
                                 eP.size2 = 0;
                                 size_readed = 0;
                                 goto dma_transfer2;
                         }
                         else
                                 size_readed = 0;
                 }
         }
         while (left_to_read > 0) {
                 size_to_read = left_to_read;
                 if (left_to_read > MCSERV_BUFSIZE)
                         size_to_read = MCSERV_BUFSIZE;
                 size_readed = pMcRead(dP->fd, mcserv_buf, size_to_read);
                 if (size_readed < 0) {
                         eP.size2 = 0;
                         goto dma_transfer2;
                 }
                 dmaStruct.src = (void *)mcserv_buf;
                 dmaStruct.dest = (void *)eedata;
                 dmaStruct.size = size_readed;
                 dmaStruct.attr = 0;
                 CpuSuspendIntr(&intStatus);
                 sceSifSetDma(&dmaStruct, 1);
                 file_offset += size_readed;
                 left_to_read -= size_readed;
                 CpuResumeIntr(intStatus);
                 eedata += size_readed;
                 if (size_to_read != size_readed) {
                         eP.size2 = 0;
                         size_readed = 0;
                         goto dma_transfer2;
                 }
                 size_readed = 0;
         }
         if (eP.size2 == 0)
                 goto dma_transfer2;
         size_readed = pMcRead(dP->fd, eP.src2, eP.size2);
         if (size_readed < 0) {
                 eP.size2 = 0;
                 goto dma_transfer2;
         }
         file_offset += size_readed;
         eP.size2 = size_readed;
         size_readed = 0;
 dma_transfer2:
         dmaStruct.src = (void *)&eP;
         dmaStruct.dest = (void *)dP->param;
         dmaStruct.size = sizeof (mcEndParam_t);
         dmaStruct.attr = 0;
         CpuSuspendIntr(&intStatus);
         status = sceSifSetDma(&dmaStruct, 1);
         CpuResumeIntr(intStatus);
         while (sceSifDmaStat(status) >= 0)
                 DelayThread(100);
         if (size_readed != 0)
                 return size_readed;
         return file_offset;
 }
References SifDmaTransfer_t::attr, mcDescParam_t::buffer, CpuResumeIntr(), CpuSuspendIntr(), DelayThread(), SifDmaTransfer_t::dest, mcEndParam_t::dest1, mcEndParam_t::dest2, DPRINTF, mcDescParam_t::fd, mcserv_buf, MCSERV_BUFSIZE, NULL, mcDescParam_t::param, pMcRead, sceSifDmaStat(), sceSifSetDma(), mcDescParam_t::size, SifDmaTransfer_t::size, mcEndParam_t::size1, mcEndParam_t::size2, SifDmaTransfer_t::src, mcEndParam_t::src1, mcEndParam_t::src2, and status.
Referenced by sceMcRead().
_McRead2()
int _McRead2 (void * rpc_buf)
Definition at line 588 of file mcserv.c.
 {
         mcDescParam_t *dP = (mcDescParam_t *)rpc_buf;
         register int file_offset, status;
         register int left_to_read, size_readed, size_to_read;
         mcEndParam2_t eP;
         SifDmaTransfer_t dmaStruct;
         int intStatus;
         void *eedata;
 #ifdef DEBUG
         DPRINTF("mcserv: _McRead2 fd %d ee buffer addr %x size %d\n", dP->fd, (int)dP->buffer, dP->size);
 #endif
         eP.size1 = 0;
         eP.size2 = 0;
         eP.dest1 = NULL;
         eP.dest2 = NULL;
         size_readed = 0;
         file_offset = 0;
         eedata = dP->buffer;
         eP.size1 = dP->size;
         if (dP->size > 64)
                 eP.size1 = (((u32)(eedata)-1) & 0xffffffc0) - ((u32)(eedata) - 64);
         eP.size2 = (dP->size - eP.size1) & 0x3f;
         left_to_read = (dP->size - eP.size1) - eP.size2;
         if (eP.size2 != 0)
                 eP.dest2 = (void *)(eedata + eP.size1 + left_to_read);
         if (eP.size1 != 0) {
                 size_readed = pMcRead(dP->fd, eP.src1, eP.size1);
                 if (size_readed < 0) {
                         eP.size1 = 0;
                         eP.size2 = 0;
                         goto dma_transfer2;
                 }
                 else {
                         file_offset = size_readed;
                         eP.dest1 = eedata;
                         eedata += size_readed;
                         if (size_readed != eP.size1) {
                                 eP.size1 = size_readed;
                                 eP.size2 = 0;
                                 size_readed = 0;
                                 goto dma_transfer2;
                         }
                         else
                                 size_readed = 0;
                 }
         }
         while (left_to_read > 0) {
                 size_to_read = left_to_read;
                 if (left_to_read > MCSERV_BUFSIZE)
                         size_to_read = MCSERV_BUFSIZE;
                 size_readed = pMcRead(dP->fd, mcserv_buf, size_to_read);
                 if (size_readed < 0) {
                         eP.size2 = 0;
                         goto dma_transfer2;
                 }
                 if (size_readed == size_to_read) {
                         dmaStruct.size = size_readed;
                         goto dma_transfer;
                 }
                 eP.size2 = size_readed & 0x3f;
                 if ((size_readed & 0x3f) != 0) {
                         eP.dest2 = (void *)(eedata + (size_readed & 0xffffffc0));
                         memcpy(eP.src2, (void *)(mcserv_buf + (size_readed & 0xffffffc0)), size_readed & 0x3f);
                 }
                 if (eP.size2 == size_readed)
                         goto skip_dma_transfer;
                 dmaStruct.size = size_readed - eP.size2;
 dma_transfer:
                 dmaStruct.src = (void *)mcserv_buf;
                 dmaStruct.dest = (void *)eedata;
                 dmaStruct.attr = 0;
                 CpuSuspendIntr(&intStatus);
                 sceSifSetDma(&dmaStruct, 1);
                 CpuResumeIntr(intStatus);
 skip_dma_transfer:
                 file_offset += size_readed;
                 left_to_read -= size_readed;
                 eedata += size_readed;
                 if (size_to_read != size_readed) {
                         size_readed = 0;
                         goto dma_transfer2;
                 }
                 size_readed = 0;
         }
         if (eP.size2 == 0)
                 goto dma_transfer2;
         size_readed = pMcRead(dP->fd, eP.src2, eP.size2);
         if (size_readed < 0) {
                 eP.size2 = 0;
                 goto dma_transfer2;
         }
         file_offset += size_readed;
         eP.size2 = size_readed;
         size_readed = 0;
 dma_transfer2:
         dmaStruct.src = (void *)&eP;
         dmaStruct.dest = (void *)dP->param;
         dmaStruct.size = sizeof (mcEndParam2_t);
         dmaStruct.attr = 0;
         CpuSuspendIntr(&intStatus);
         status = sceSifSetDma(&dmaStruct, 1);
         CpuResumeIntr(intStatus);
         while (sceSifDmaStat(status) >= 0)
                 DelayThread(100);
         if (size_readed != 0)
                 return size_readed;
         return file_offset;
 }
References SifDmaTransfer_t::attr, mcDescParam_t::buffer, CpuResumeIntr(), CpuSuspendIntr(), DelayThread(), SifDmaTransfer_t::dest, mcEndParam2_t::dest1, mcEndParam2_t::dest2, DPRINTF, mcDescParam_t::fd, mcserv_buf, MCSERV_BUFSIZE, memcpy(), NULL, mcDescParam_t::param, pMcRead, sceSifDmaStat(), sceSifSetDma(), mcDescParam_t::size, SifDmaTransfer_t::size, mcEndParam2_t::size1, mcEndParam2_t::size2, SifDmaTransfer_t::src, mcEndParam2_t::src1, mcEndParam2_t::src2, and status.
Referenced by sceMcRead2().
_McReadPage()
int _McReadPage (void * rpc_buf)
Definition at line 1075 of file mcserv.c.
 {
         mcDescParam_t *dP = (mcDescParam_t *)rpc_buf;
         mcEndParam_t eP;
         register int status, fastsize, r, i, j;
         SifDmaTransfer_t dmaStruct;
         int intStatus;
 #ifdef DEBUG
         DPRINTF("mcserv: _McReadPage port%d slot%d page %d\n", dP->port, dP->slot, dP->fd);
 #endif
         eP.dest1 = dP->buffer;
         fastsize = ((u32)dP->buffer) & 0xf;
         dP->port = (dP->port & 1) + 2;
         if (pMcGetMcType(dP->port, dP->slot) == 2) {
                 r = 0;
                 pMcReadPage(dP->port, dP->slot, dP->fd, (void *)(mcserv_buf + fastsize));
         }
         else {
                 memset((void *)(mcserv_buf + fastsize), 0, 512);
                 r = pMcReadPS1PDACard(dP->port, dP->slot, dP->fd, (void *)(mcserv_buf + fastsize));
         }
         if (fastsize == 0)
                 goto fullpage;
         i = 0;
         j = fastsize;
         while (j < 16) {
                 eP.src1[i] = mcserv_buf[j];
                 j++;
                 i++;
         }
         j = 0;
         if (fastsize > 0) {
                 while (j < 16) {
                         eP.src1[i] = mcserv_buf[512 + j];
                         j++;
                         i++;
                 }
         }
         dmaStruct.src = (void *)(mcserv_buf + 16);
         dmaStruct.dest = (void *)(dP->buffer - (fastsize - 16));
         dmaStruct.size = 496;
         dmaStruct.attr = 0;
         goto dma_transfer;
 fullpage:
         dmaStruct.src = (void *)mcserv_buf;
         dmaStruct.dest = (void *)dP->buffer;
         dmaStruct.size = 512;
         dmaStruct.attr = 0;
 dma_transfer:
         CpuSuspendIntr(&intStatus);
         status = sceSifSetDma(&dmaStruct, 1);
         CpuResumeIntr(intStatus);
         dmaStruct.src = (void *)&eP;
         dmaStruct.dest = (void *)dP->param;
         dmaStruct.size = sizeof (mcEndParam_t);
         dmaStruct.attr = 0;
         CpuSuspendIntr(&intStatus);
         status = sceSifSetDma(&dmaStruct, 1);
         CpuResumeIntr(intStatus);
         while (sceSifDmaStat(status) >= 0)
                 DelayThread(100);
         return r;
 }
References SifDmaTransfer_t::attr, mcDescParam_t::buffer, CpuResumeIntr(), CpuSuspendIntr(), DelayThread(), SifDmaTransfer_t::dest, mcEndParam_t::dest1, DPRINTF, mcDescParam_t::fd, mcserv_buf, memset(), mcDescParam_t::param, pMcGetMcType, pMcReadPage, pMcReadPS1PDACard, mcDescParam_t::port, sceSifDmaStat(), sceSifSetDma(), SifDmaTransfer_t::size, mcDescParam_t::slot, SifDmaTransfer_t::src, mcEndParam_t::src1, and status.
Referenced by sceMcReadPage().
_McSeek()
int _McSeek (void * rpc_buf)
Definition at line 446 of file mcserv.c.
 {
         mcDescParam_t *dP = (mcDescParam_t *)rpc_buf;
 #ifdef DEBUG
         DPRINTF("mcserv: _McSeek fd %d offset %d origin %d\n", dP->fd, dP->offset, dP->origin);
 #endif
         return pMcSeek(dP->fd, dP->offset, dP->origin);
 }
References DPRINTF, mcDescParam_t::fd, mcDescParam_t::offset, mcDescParam_t::origin, and pMcSeek.
Referenced by sceMcSeek().
_McSetFileInfo()
int _McSetFileInfo (void * rpc_buf)
Definition at line 1206 of file mcserv.c.
 {
         mcNameParam_t *nP = (mcNameParam_t *)rpc_buf;
         SifRpcReceiveData_t     rD;
 #ifdef DEBUG
         DPRINTF("mcserv: _McSetFileInfo port%d slot%d file %s flags %d\n", nP->port, nP->slot, nP->name, nP->flags);
 #endif
         sceSifGetOtherData(&rD, (void *)nP->mcT, &mcserv_buf, sizeof (sceMcTblGetDir), 0);
         return pMcSetFileInfo(nP->port, nP->slot, nP->name, (sceMcTblGetDir *)mcserv_buf, nP->flags);
 }
References DPRINTF, mcNameParam_t::flags, mcserv_buf, mcNameParam_t::mcT, mcNameParam_t::name, pMcSetFileInfo, mcNameParam_t::port, sceSifGetOtherData(), and mcNameParam_t::slot.
Referenced by sceMcSetFileInfo().
_McUnformat()
int _McUnformat (void * rpc_buf)
Definition at line 870 of file mcserv.c.
 {
         mcDescParam_t *dP = (mcDescParam_t *)rpc_buf;
 #ifdef DEBUG
         DPRINTF("mcserv: _McUnformat port%d slot%d\n", dP->port, dP->slot);
 #endif
         return pMcUnformat(dP->port, dP->slot);
 }
References DPRINTF, pMcUnformat, mcDescParam_t::port, and mcDescParam_t::slot.
Referenced by sceMcUnformat().
_McWrite()
int _McWrite (void * rpc_buf)
Definition at line 732 of file mcserv.c.
 {
         mcDescParam_t *dP = (mcDescParam_t *)rpc_buf;
         SifRpcReceiveData_t     rD;
         register int size_to_write, size_written, r;
 #ifdef DEBUG
         DPRINTF("mcserv: _McWrite fd %d ee buffer addr %x size %d\n", dP->fd, (int)dP->buffer, dP->size);
 #endif
         size_written = 0;
         if (dP->origin != 0) {
                 size_written = pMcWrite(dP->fd, dP->data, dP->origin);
                 if (size_written != dP->origin)
                         return size_written;
         }
         while (dP->size > 0) {
                 size_to_write = dP->size;
                 if (dP->size > MCSERV_BUFSIZE)
                         size_to_write = MCSERV_BUFSIZE;
                 sceSifGetOtherData(&rD, dP->buffer, &mcserv_buf, size_to_write, 0);
                 r = pMcWrite(dP->fd, &mcserv_buf, size_to_write);
                 if (r != size_to_write) {
                         if (r < 0)
                                 return r;
                         return r + size_written;
                 }
                 size_written += size_to_write;
                 dP->size -= size_to_write;
                 dP->buffer += size_to_write;
         }
         return size_written;
 }
References mcDescParam_t::buffer, mcDescParam_t::data, DPRINTF, mcDescParam_t::fd, mcserv_buf, MCSERV_BUFSIZE, mcDescParam_t::origin, pMcWrite, sceSifGetOtherData(), and mcDescParam_t::size.
Referenced by sceMcWrite().
_McWritePage()
int _McWritePage (void * rpc_buf)
Definition at line 1154 of file mcserv.c.
 {
         mcDescParam_t *dP = (mcDescParam_t *)rpc_buf;
         register int fastsize, i, j;
         SifRpcReceiveData_t     rD;
         u8 eccbuf[16];
 #ifdef DEBUG
         DPRINTF("mcserv: _McWritePage port%d slot%d page %d\n", dP->port, dP->slot, dP->fd);
 #endif
         fastsize = ((u32)dP->buffer) & 0xf;
         if (fastsize == 0)
                 goto fullpage;
         sceSifGetOtherData(&rD, (void *)(dP->buffer - (fastsize - 16)), &mcserv_buf, 496, 0);
         i = fastsize;
         while (i < 16) {
                 mcserv_buf[i] = dP->data[i - fastsize];
                 i++;
         }
         if (fastsize == 0)
                 goto ecc_calc;
         j = 16;
         i = 0;
         while (i < fastsize) {
                 mcserv_buf[496 + j] = dP->data[j - fastsize];
                 i++;
                 j++;
         }
         goto ecc_calc;
 fullpage:
         sceSifGetOtherData(&rD, dP->buffer, &mcserv_buf, 512, 0);
 ecc_calc:
         pMcDataChecksum((void *)(mcserv_buf + fastsize), &eccbuf[0]);
         pMcDataChecksum(&mcserv_buf[128], &eccbuf[3]);
         pMcDataChecksum(&mcserv_buf[256], &eccbuf[6]);
         pMcDataChecksum(&mcserv_buf[384], &eccbuf[9]);
         return pMcWritePage((dP->port & 1) | 2, dP->slot, dP->fd, (void *)(mcserv_buf + fastsize), eccbuf);
 }
References mcDescParam_t::buffer, mcDescParam_t::data, DPRINTF, mcDescParam_t::fd, mcserv_buf, pMcDataChecksum, pMcWritePage, mcDescParam_t::port, sceSifGetOtherData(), and mcDescParam_t::slot.
Referenced by sceMcWritePage().
_start()
int _start (int argc, const char ** argv)
Definition at line 101 of file mcserv.c.
 {
         iop_thread_t thread_param;
         register int thread_id;
         iop_library_t *libptr;
         int i, mcman_loaded;
         void **export_tab;
 #ifdef SIO_DEBUG
         sio_init(38400, 0, 0, 0, 0);
 #endif
 #ifdef DEBUG
         DPRINTF("mcserv: _start...\n");
 #endif
         // Get mcman lib ptr
         mcman_loaded = 0;
         libptr = GetLoadcoreInternalData()->let_next;
         while (libptr != 0) {
                 for (i=0; i<8; i++) {
                         if (libptr->name[i] != mcman_modname[i])
                                 break;
                 }
                 if (i == 8) {
                         mcman_loaded = 1;
                         break;
                 }
                 libptr = libptr->prev;
         }
         if (!mcman_loaded) {
 #ifdef DEBUG
                 DPRINTF("mcserv: mcman module is not loaded...\n");
 #endif
                 goto err_out;
         }
 #ifdef DEBUG
         DPRINTF("mcserv: mcman version=%03x\n", libptr->version);
 #endif
         if (libptr->version > 0x200)
                 mcman_type = XMCMAN;
         // Get mcman export table
         export_tab = (void **)(((struct irx_export_table *)libptr)->fptrs);
         // Set functions pointers to match MCMAN exports
         pMcDetectCard = export_tab[5];
         pMcOpen = export_tab[6];
         pMcClose = export_tab[7];
         pMcRead = export_tab[8];
         pMcWrite = export_tab[9];
         pMcSeek = export_tab[10];
         pMcFormat = export_tab[11];
         pMcGetDir = export_tab[12];
         pMcDelete = export_tab[13];
         pMcFlush = export_tab[14];
         pMcChDir = export_tab[15];
         pMcSetFileInfo = export_tab[16];
         pMcEraseBlock = export_tab[17];
         pMcReadPage = export_tab[18];
         pMcWritePage = export_tab[19];
         pMcDataChecksum = export_tab[20];
         pMcReplaceBadBlock = export_tab[24]; // dummy in MCMAN !!!
         pMcReadPS1PDACard = export_tab[29];
         pMcWritePS1PDACard = export_tab[30];
         pMcUnformat = export_tab[36];
         pMcRetOnly = export_tab[37];
         pMcGetFreeClusters = export_tab[38];
         pMcGetMcType = export_tab[39];
         pMcSetPS1CardFlag = export_tab[40];
         // Set functions pointers to match XMCMAN exports if needed
         if (mcman_type == XMCMAN) {
         pMcDetectCard2 = export_tab[21];
         pMcGetFormat = export_tab[22];
         pMcGetEntSpace = export_tab[23];
         pMcGetModuleInfo = export_tab[42];
         pMcCheckBlock = export_tab[45];
         }
         // Register mcserv dummy export table
 #ifdef DEBUG
         DPRINTF("mcserv: registering exports...\n");
 #endif
         if (RegisterLibraryEntries(&_exp_mcserv) != 0)
                 goto err_out;
         CpuEnableIntr();
 #ifdef DEBUG
         DPRINTF("mcserv: starting RPC thread...\n");
 #endif
         thread_param.attr = TH_C;
         thread_param.thread = (void *)thread_rpc_S_0400;
         thread_param.priority = 0x68;
         thread_param.stacksize = 0x1000;
         thread_param.option = 0;
         thread_id = CreateThread(&thread_param);
         mcserv_tidS_0400 = thread_id;
         StartThread(thread_id, 0);
 #ifdef DEBUG
         DPRINTF("mcserv: _start returns MODULE_RESIDENT_END...\n");
 #endif
         return MODULE_RESIDENT_END;
 err_out:
 #ifdef DEBUG
         DPRINTF("mcserv: _start returns MODULE_NO_RESIDENT_END...\n");
 #endif
         return MODULE_NO_RESIDENT_END;
 }
References _exp_mcserv, iop_thread_t::attr, CpuEnableIntr(), CreateThread(), DPRINTF, GetLoadcoreInternalData(), lc_internals_t::let_next, mcman_modname, mcman_type, mcserv_tidS_0400, MODULE_NO_RESIDENT_END, MODULE_RESIDENT_END, iop_library_t::name, iop_thread_t::option, pMcChDir, pMcCheckBlock, pMcClose, pMcDataChecksum, pMcDelete, pMcDetectCard, pMcDetectCard2, pMcEraseBlock, pMcFlush, pMcFormat, pMcGetDir, pMcGetEntSpace, pMcGetFormat, pMcGetFreeClusters, pMcGetMcType, pMcGetModuleInfo, pMcOpen, pMcRead, pMcReadPage, pMcReadPS1PDACard, pMcReplaceBadBlock, pMcRetOnly, pMcSeek, pMcSetFileInfo, pMcSetPS1CardFlag, pMcUnformat, pMcWrite, pMcWritePage, pMcWritePS1PDACard, iop_library_t::prev, iop_thread_t::priority, RegisterLibraryEntries(), sio_init(), iop_thread_t::stacksize, StartThread(), TH_C, iop_thread_t::thread, thread_rpc_S_0400(), iop_library_t::version, and XMCMAN.
cb_rpc_S_0400()
void* cb_rpc_S_0400 (u32 fno, void * buf, int size)
Definition at line 233 of file mcserv.c.
 {
         // Rpc Callback function
         int (*rpc_func)(void);
         register int i;
         if (mcman_type == XMCMAN) {
                 for (i=0; i<16; i++) { // retrieve correct function number for xmcserv
                         if (fno == XMCSERV_RpcCmd[0][i]) {
                                 fno = XMCSERV_RpcCmd[1][i];
                                 break;
                         }
                 }
         }
         else { // retrieve correct function number for mcserv
                 fno -= 112;
                 if (fno > 16)
                         return (void *)&rpc_stat;
         }
         // Get function pointer
         rpc_func = (void *)rpc_funcs_array[fno];
         // Call needed rpc func
         rpc_stat.result = rpc_func();
         pMcReplaceBadBlock();
         return (void *)&rpc_stat;
 }
References mcman_type, pMcReplaceBadBlock, mcRpcStat_t::result, rpc_funcs_array, rpc_stat, XMCMAN, and XMCSERV_RpcCmd.
Referenced by thread_rpc_S_0400().
IRX_ID()
IRX_ID (MODNAME , 2 , 8)
sceMcChDir()
int sceMcChDir (void)
Definition at line 360 of file mcserv.c.
 {
         return _McChDir(&mcserv_rpc_buf);
 }
References _McChDir(), and mcserv_rpc_buf.
sceMcCheckBlock()
int sceMcCheckBlock (void)
Definition at line 396 of file mcserv.c.
 {
         return _McCheckBlock(&mcserv_rpc_buf);
 }
References _McCheckBlock(), and mcserv_rpc_buf.
sceMcClose()
int sceMcClose (void)
Definition at line 288 of file mcserv.c.
 {
         return _McClose(&mcserv_rpc_buf);
 }
References _McClose(), and mcserv_rpc_buf.
sceMcDelete()
int sceMcDelete (void)
Definition at line 348 of file mcserv.c.
 {
         return _McDelete(&mcserv_rpc_buf);
 }
References _McDelete(), and mcserv_rpc_buf.
sceMcEraseBlock()
int sceMcEraseBlock (void)
Definition at line 366 of file mcserv.c.
 {
         return _McEraseBlock(&mcserv_rpc_buf);
 }
References _McEraseBlock(), and mcserv_rpc_buf.
sceMcFlush()
int sceMcFlush (void)
Definition at line 354 of file mcserv.c.
 {
         return _McFlush(&mcserv_rpc_buf);
 }
References _McFlush(), and mcserv_rpc_buf.
sceMcFormat()
int sceMcFormat (void)
Definition at line 324 of file mcserv.c.
 {
         return _McFormat(&mcserv_rpc_buf);
 }
References _McFormat(), and mcserv_rpc_buf.
sceMcGetDir()
int sceMcGetDir (void)
Definition at line 318 of file mcserv.c.
 {
         return _McGetDir(&mcserv_rpc_buf);
 }
References _McGetDir(), and mcserv_rpc_buf.
sceMcGetEntSpace()
int sceMcGetEntSpace (void)
Definition at line 390 of file mcserv.c.
 {
         return _McGetEntSpace(&mcserv_rpc_buf);
 }
References _McGetEntSpace(), and mcserv_rpc_buf.
sceMcGetInfo()
int sceMcGetInfo (void)
Definition at line 336 of file mcserv.c.
 {
         return _McGetInfo(&mcserv_rpc_buf);
 }
References _McGetInfo(), and mcserv_rpc_buf.
sceMcGetInfo2()
int sceMcGetInfo2 (void)
Definition at line 342 of file mcserv.c.
 {
         return _McGetInfo2(&mcserv_rpc_buf);
 }
References _McGetInfo2(), and mcserv_rpc_buf.
sceMcInit()
int sceMcInit (void)
Definition at line 265 of file mcserv.c.
 {
         register int r;
         struct irx_id *ModuleInfo;
         r = _McInit(&mcserv_rpc_buf);
         if (mcman_type == XMCMAN) {
                 ModuleInfo = pMcGetModuleInfo();
                 rpc_stat.mcserv_version = MODVER;
                 rpc_stat.mcman_version = ModuleInfo->v;
         }
         return r;
 }
References _McInit(), mcman_type, mcRpcStat_t::mcman_version, mcserv_rpc_buf, mcRpcStat_t::mcserv_version, MODVER, pMcGetModuleInfo, rpc_stat, irx_id::v, and XMCMAN.
sceMcOpen()
int sceMcOpen (void)
Definition at line 282 of file mcserv.c.
 {
         return _McOpen(&mcserv_rpc_buf);
 }
References _McOpen(), and mcserv_rpc_buf.
sceMcRead()
int sceMcRead (void)
Definition at line 294 of file mcserv.c.
 {
         return _McRead(&mcserv_rpc_buf);
 }
References _McRead(), and mcserv_rpc_buf.
sceMcRead2()
int sceMcRead2 (void)
Definition at line 300 of file mcserv.c.
 {
         return _McRead2(&mcserv_rpc_buf);
 }
References _McRead2(), and mcserv_rpc_buf.
sceMcReadPage()
int sceMcReadPage (void)
Definition at line 372 of file mcserv.c.
 {
         return _McReadPage(&mcserv_rpc_buf);
 }
References _McReadPage(), and mcserv_rpc_buf.
sceMcSeek()
int sceMcSeek (void)
Definition at line 312 of file mcserv.c.
 {
         return _McSeek(&mcserv_rpc_buf);
 }
References _McSeek(), and mcserv_rpc_buf.
sceMcSetFileInfo()
int sceMcSetFileInfo (void)
Definition at line 384 of file mcserv.c.
 {
         return _McSetFileInfo(&mcserv_rpc_buf);
 }
References _McSetFileInfo(), and mcserv_rpc_buf.
sceMcUnformat()
int sceMcUnformat (void)
Definition at line 330 of file mcserv.c.
 {
         return _McUnformat(&mcserv_rpc_buf);
 }
References _McUnformat(), and mcserv_rpc_buf.
sceMcWrite()
int sceMcWrite (void)
Definition at line 306 of file mcserv.c.
 {
         return _McWrite(&mcserv_rpc_buf);
 }
References _McWrite(), and mcserv_rpc_buf.
sceMcWritePage()
int sceMcWritePage (void)
Definition at line 378 of file mcserv.c.
 {
         return _McWritePage(&mcserv_rpc_buf);
 }
References _McWritePage(), and mcserv_rpc_buf.
thread_rpc_S_0400()
void thread_rpc_S_0400 (void * arg)
Definition at line 221 of file mcserv.c.
 {
         if (!sceSifCheckInit())
                 sceSifInit();
         sceSifInitRpc(0);
         sceSifSetRpcQueue(&mcserv_qdS_0400, GetThreadId());
         sceSifRegisterRpc(&mcserv_sdS_0400, 0x80000400, (void *)cb_rpc_S_0400, &mcserv_rpc_buf, NULL, NULL, &mcserv_qdS_0400);
         sceSifRpcLoop(&mcserv_qdS_0400);
 }
References cb_rpc_S_0400(), GetThreadId(), mcserv_qdS_0400, mcserv_rpc_buf, mcserv_sdS_0400, NULL, sceSifCheckInit(), sceSifInit(), sceSifInitRpc(), sceSifRegisterRpc(), sceSifRpcLoop(), and sceSifSetRpcQueue().
Referenced by _start().
Variable Documentation
_exp_mcserv
struct irx_export_table _exp_mcserv extern
Referenced by _start().
mcserv_buf
u8 mcserv_buf[MCSERV_BUFSIZE] static
Definition at line 96 of file mcserv.c.
Referenced by _McChDir(), _McEraseBlock(), _McGetDir(), _McRead(), _McRead2(), _McReadPage(), _McSetFileInfo(), _McWrite(), and _McWritePage().
mcserv_qdS_0400
SifRpcDataQueue_t mcserv_qdS_0400 static
Definition at line 89 of file mcserv.c.
Referenced by thread_rpc_S_0400().
mcserv_rpc_buf
u8 mcserv_rpc_buf[2048] static
Definition at line 92 of file mcserv.c.
Referenced by sceMcChDir(), sceMcCheckBlock(), sceMcClose(), sceMcDelete(), sceMcEraseBlock(), sceMcFlush(), sceMcFormat(), sceMcGetDir(), sceMcGetEntSpace(), sceMcGetInfo(), sceMcGetInfo2(), sceMcInit(), sceMcOpen(), sceMcRead(), sceMcRead2(), sceMcReadPage(), sceMcSeek(), sceMcSetFileInfo(), sceMcUnformat(), sceMcWrite(), sceMcWritePage(), and thread_rpc_S_0400().
mcserv_sdS_0400
SifRpcServerData_t mcserv_sdS_0400 static
Definition at line 90 of file mcserv.c.
Referenced by thread_rpc_S_0400().
mcserv_tidS_0400
int mcserv_tidS_0400 static
Definition at line 87 of file mcserv.c.
Referenced by _start().
rpc_funcs_array
void* rpc_funcs_array[21] static
Initial value:
= {
    (void *)sceMcInit,
    (void *)sceMcOpen,
    (void *)sceMcClose,
    (void *)sceMcRead,
    (void *)sceMcWrite,
    (void *)sceMcSeek,
    (void *)sceMcGetDir,
    (void *)sceMcFormat,
    (void *)sceMcGetInfo,
    (void *)sceMcDelete,
    (void *)sceMcFlush,
    (void *)sceMcChDir,
    (void *)sceMcSetFileInfo,
    (void *)sceMcEraseBlock,
    (void *)sceMcReadPage,
    (void *)sceMcWritePage,
    (void *)sceMcUnformat,
    (void *)sceMcRead2,
    (void *)sceMcGetInfo2,
    (void *)sceMcGetEntSpace,
    (void *)sceMcCheckBlock
}
Definition at line 63 of file mcserv.c.
Referenced by cb_rpc_S_0400().
rpc_stat
mcRpcStat_t rpc_stat static
Definition at line 93 of file mcserv.c.
Referenced by cb_rpc_S_0400(), and sceMcInit().
XMCSERV_RpcCmd
const u8 XMCSERV_RpcCmd[2][16] static
Definition at line 23 of file mcserv.c.
Referenced by cb_rpc_S_0400().