ps2sdk: iop/memorycard/mcman/src/mcsio2.c File Reference
mcsio2.c File Reference
#include <mcman.h>
#include "mcman-internal.h"
Functions
static void sio2packet_add_wdma_u32 (int port, int slot, int cmd, u8 *buf, int pos)
static void sio2packet_add_pagedata_out (int port, int slot, int cmd, u8 *buf, int pos)
static void sio2packet_add_pagedata_in (int port, int slot, int cmd, u8 *buf, int pos)
static void sio2packet_add_ecc_in (int port, int slot, int cmd, u8 *buf, int pos)
static void sio2packet_add_ecc_out (int port, int slot, int cmd, u8 *buf, int pos)
static void sio2packet_add_wdma_5a (int port, int slot, int cmd, u8 *buf, int pos)
static void sio2packet_add_wdma_00 (int port, int slot, int cmd, u8 *buf, int pos)
static void sio2packet_add_wdma_u8 (int port, int slot, int cmd, u8 *buf, int pos)
static void sio2packet_add_do_nothing (int port, int slot, int cmd, u8 *buf, int pos)
void sio2packet_add (int port, int slot, int cmd, u8 *buf)
int mcsio2_transfer (int port, int slot, sio2_transfer_data_t *sio2data)
int mcsio2_transfer2 (int port, int slot, sio2_transfer_data_t *sio2data)
void mcman_initPS2com (void)
void mcman_initPS1PDAcom (void)
int secrman_mc_command (int port, int slot, sio2_transfer_data_t *sio2data)
int mcman_cardchanged (int port, int slot)
int mcman_eraseblock (int port, int slot, int block, void **pagebuf, void *eccbuf)
int McWritePage (int port, int slot, int page, void *pagebuf, void *eccbuf)
int mcman_readpage (int port, int slot, int page, void *buf, void *eccbuf)
int McGetCardSpec (int port, int slot, s16 *pagesize, u16 *blocksize, int *cardsize, u8 *flags)
int mcman_resetauth (int port, int slot)
int mcman_probePS2Card2 (int port, int slot)
int mcman_probePS2Card (int port, int slot)
int mcman_probePS1Card2 (int port, int slot)
int mcman_probePS1Card (int port, int slot)
int mcman_probePDACard (int port, int slot)
int McWritePS1PDACard (int port, int slot, int page, void *buf)
int McReadPS1PDACard (int port, int slot, int page, void *buf)
Variables
int timer_ID
MCDevInfo mcman_devinfos [4][MCMAN_MAXSLOT]
static sio2_transfer_data_t mcman_sio2packet
static u8 mcman_wdmabufs [0x0b *0x90]
static u8 mcman_rdmabufs [0x0b *0x90]
static sio2_transfer_data_t mcman_sio2packet_PS1PDA
static u8 mcman_sio2inbufs_PS1PDA [0x90]
u8 mcman_sio2outbufs_PS1PDA [0x90]
static u32 mcman_timercount
static int mcman_timerthick
static const u8 mcman_cmdtable [36]
int(* mcman_sio2transfer)(int port, int slot, sio2_transfer_data_t *sio2data)
static void(* sio2packet_add_func)(int port, int slot, int cmd, u8 *buf, int pos)
static void * sio2packet_add_funcs_array [16]
Function Documentation
McGetCardSpec()
int McGetCardSpec (int port, int slot, s16 * pagesize, u16 * blocksize, int * cardsize, u8 * flags)
Definition at line 598 of file mcsio2.c.
 {
         register int retries, r;
         u8 *p = mcman_sio2packet.out_dma.addr;
 #ifdef DEBUG
         DPRINTF("mcman: McGetCardSpec sio2cmd port%d slot%d\n", port, slot);
 #endif
         sio2packet_add(port, slot, 0xffffffff, NULL);
         sio2packet_add(port, slot, 0x07, NULL);
         sio2packet_add(port, slot, 0xfffffffe, NULL);
         retries = 0;
         do {
                 mcman_sio2transfer(port, slot, &mcman_sio2packet);
                 if (((mcman_sio2packet.stat6c & 0xF000) == 0x1000) && (p[12] == 0x5a)) {
                         // checking EDC
                         r = mcman_calcEDC(&p[3], 8) & 0xFF;
                         if (r == p[11])
                                 break;
                 }
         } while (++retries < 5);
         if (retries >= 5)
                 return sceMcResChangedCard;
         *pagesize = (p[4] << 8) + p[3];
         *blocksize = (p[6] << 8) + p[5];
         *cardsize = (p[8] << 8) + p[7] + (p[9] << 16) + (p[10] << 24);
         *flags = p[2];
 #ifdef DEBUG
         DPRINTF("mcman: McGetCardSpec sio2cmd pagesize=%d blocksize=%u cardsize=%d flags%x\n", *pagesize, *blocksize, *cardsize, *flags);
 #endif
         return sceMcResSucceed;
 }
References _sio2_dma_arg::addr, DPRINTF, mcman_calcEDC(), mcman_sio2packet, mcman_sio2transfer, NULL, sio2_transfer_data_t::out_dma, sceMcResChangedCard, sceMcResSucceed, sio2packet_add(), and sio2_transfer_data_t::stat6c.
Referenced by _start(), and mcman_setdevspec().
mcman_cardchanged()
int mcman_cardchanged (int port, int slot)
Definition at line 344 of file mcsio2.c.
 {
         register int retries;
         u8 *p = mcman_sio2packet.out_dma.addr;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_cardchanged sio2cmd port%d slot%d\n", port, slot);
 #endif
         sio2packet_add(port, slot, 0xffffffff, NULL);
         sio2packet_add(port, slot, 0, NULL);
         sio2packet_add(port, slot, 0xfffffffe, NULL);
         retries = 0;
         do {
                 mcman_sio2transfer(port, slot, &mcman_sio2packet);
                 if (((mcman_sio2packet.stat6c & 0xF000) == 0x1000) && (p[3] != 0x66))
                         break;
         } while (++retries < 5);
         if (retries >= 5) {
 #ifdef DEBUG
                 DPRINTF("mcman: mcman_cardchanged sio2cmd card changed!\n");
 #endif
                 return sceMcResChangedCard;
         }
 #ifdef DEBUG
         DPRINTF("mcman: mcman_cardchanged sio2cmd succeeded\n");
 #endif
         return sceMcResSucceed;
 }
References _sio2_dma_arg::addr, DPRINTF, mcman_sio2packet, mcman_sio2transfer, NULL, sio2_transfer_data_t::out_dma, sceMcResChangedCard, sceMcResSucceed, sio2packet_add(), and sio2_transfer_data_t::stat6c.
Referenced by mcman_probePS2Card(), mcman_readpage(), and McWritePage().
mcman_eraseblock()
int mcman_eraseblock (int port, int slot, int block, void ** pagebuf, void * eccbuf)
Definition at line 381 of file mcsio2.c.
 {
         register int retries, size, ecc_offset;
         int page;
         u8 *p = mcman_sio2packet.out_dma.addr;
         void *p_ecc;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         page = block * mcdi->blocksize;
         sio2packet_add(port, slot, 0xffffffff, NULL);
         sio2packet_add(port, slot, 0x02, (u8 *)&page);
         sio2packet_add(port, slot, 0x0d, NULL);
         sio2packet_add(port, slot, 0xfffffffe, NULL);
         retries = 0;
         do {
                 mcman_sio2transfer(port, slot, &mcman_sio2packet);
                 if (((mcman_sio2packet.stat6c & 0xF000) != 0x1000) || (p[8] != 0x5a))
                         continue;
                 if (p[0x93] == p[8])
                         break;
         } while (++retries < 5);
         if (retries >= 5)
                 return sceMcResChangedCard;
         if (pagebuf && eccbuf) { // This part leave the first ecc byte of each block page in eccbuf
                 mcman_wmemset(eccbuf, 32, 0);
                 page = 0;
                 while (page < mcdi->blocksize) {
                         ecc_offset = page * mcdi->pagesize;
                         if (ecc_offset < 0)
                                 ecc_offset += 0x1f;
                         ecc_offset = ecc_offset >> 5;
                         p_ecc = (void *)(eccbuf + ecc_offset);
                         size = 0;
                         while (size < mcdi->pagesize)   {
                                 if (*pagebuf)
                                         McDataChecksum((void *)(*pagebuf + size), p_ecc);
                                 size += 128;
                                 p_ecc += 3;
                         }
                         pagebuf++;
                         page++;
                 }
         }
         sio2packet_add(port, slot, 0xffffffff, NULL);
         sio2packet_add(port, slot, 0x1, NULL);
         sio2packet_add(port, slot, 0xfffffffe, NULL);
         retries = 0;
         do {
                 mcman_sio2transfer(port, slot, &mcman_sio2packet);
                 if (((mcman_sio2packet.stat6c & 0xF000) != 0x1000))
                         continue;
                 if (p[3] == 0x5a)
                         return sceMcResSucceed;
         } while (++retries < 100);
         if (p[3] == 0x66)
                 return sceMcResFailReplace;
         return sceMcResNoFormat;
 }
References _sio2_dma_arg::addr, MCDevInfo::blocksize, McDataChecksum(), mcman_devinfos, mcman_sio2packet, mcman_sio2transfer, mcman_wmemset(), NULL, sio2_transfer_data_t::out_dma, MCDevInfo::pagesize, sceMcResChangedCard, sceMcResFailReplace, sceMcResNoFormat, sceMcResSucceed, sio2packet_add(), and sio2_transfer_data_t::stat6c.
Referenced by McCheckBlock(), McEraseBlock(), McEraseBlock2(), mcman_checkBackupBlocks(), mcman_fillbackupblock1(), mcman_flushcacheentry(), mcman_format2(), mcman_unformat2(), and mcman_writecluster().
mcman_initPS1PDAcom()
void mcman_initPS1PDAcom (void)
Definition at line 311 of file mcsio2.c.
 {
         memset((void *)&mcman_sio2packet_PS1PDA, 0, sizeof (mcman_sio2packet_PS1PDA));
         mcman_sio2packet_PS1PDA.port_ctrl1[0] = 0xffc00505;
         mcman_sio2packet_PS1PDA.port_ctrl1[1] = 0xffc00505;
         mcman_sio2packet_PS1PDA.port_ctrl1[2] = 0xffc00505;
         mcman_sio2packet_PS1PDA.port_ctrl1[3] = 0xffc00505;
         mcman_sio2packet_PS1PDA.port_ctrl2[0] = 0x000201f4 & 0xfcffffff;
         mcman_sio2packet_PS1PDA.port_ctrl2[1] = 0x000201f4 & 0xfcffffff;
         mcman_sio2packet_PS1PDA.port_ctrl2[2] = 0x000201f4 & 0xfcffffff;
         mcman_sio2packet_PS1PDA.port_ctrl2[3] = 0x000201f4 & 0xfcffffff;
         mcman_sio2packet_PS1PDA.in = (u8 *)&mcman_sio2inbufs_PS1PDA;
         mcman_sio2packet_PS1PDA.out = (u8 *)&mcman_sio2outbufs_PS1PDA;
 }
References sio2_transfer_data_t::in, mcman_sio2inbufs_PS1PDA, mcman_sio2outbufs_PS1PDA, mcman_sio2packet_PS1PDA, memset(), sio2_transfer_data_t::out, sio2_transfer_data_t::port_ctrl1, and sio2_transfer_data_t::port_ctrl2.
Referenced by _start().
mcman_initPS2com()
void mcman_initPS2com (void)
Definition at line 283 of file mcsio2.c.
 {
         mcman_wmemset((void *)&mcman_sio2packet, sizeof (mcman_sio2packet), 0);
         mcman_sio2packet.port_ctrl1[2] = 0xff020405;
         mcman_sio2packet.port_ctrl1[3] = 0xff020405;
         mcman_sio2packet.port_ctrl2[2] = 0x0005ffff & 0xfcffffff;
         mcman_sio2packet.port_ctrl2[3] = 0x0005ffff & 0xfcffffff;
         mcman_sio2packet.in_dma.addr = &mcman_wdmabufs;
         mcman_sio2packet.in_dma.size = 0x24;
         mcman_sio2packet.out_dma.addr = &mcman_rdmabufs;
         mcman_sio2packet.out_dma.size = 0x24;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_initPS2com registering secrman_mc_command callback\n");
 #endif
         SecrSetMcCommandHandler((void *)secrman_mc_command);
 #ifdef DEBUG
         DPRINTF("mcman: mcman_initPS2com registering mcman_getcnum callback\n");
 #endif
         SecrSetMcDevIDHandler((void *)mcman_getcnum);
 }
References _sio2_dma_arg::addr, DPRINTF, sio2_transfer_data_t::in_dma, mcman_getcnum(), mcman_rdmabufs, mcman_sio2packet, mcman_wdmabufs, mcman_wmemset(), sio2_transfer_data_t::out_dma, sio2_transfer_data_t::port_ctrl1, sio2_transfer_data_t::port_ctrl2, secrman_mc_command(), SecrSetMcCommandHandler(), SecrSetMcDevIDHandler(), and _sio2_dma_arg::size.
Referenced by _start().
mcman_probePDACard()
int mcman_probePDACard (int port, int slot)
Definition at line 964 of file mcsio2.c.
 {
         register int retries;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_probePDACard port%d slot%d\n", port, slot);
 #endif
         mcman_sio2packet_PS1PDA.regdata[0] = 0;
         mcman_sio2packet_PS1PDA.regdata[0] = (port & 3) | 0x00140540;
         mcman_sio2packet_PS1PDA.in_size = 5;
         mcman_sio2packet_PS1PDA.out_size = 5;
         mcman_sio2packet_PS1PDA.regdata[1] = 0;
         mcman_sio2inbufs_PS1PDA[0] = 0x81;
         mcman_sio2inbufs_PS1PDA[1] = 0x58;
         retries = 0;
         do {
                 mcman_sio2transfer(port, slot, &mcman_sio2packet_PS1PDA);
                 if ((mcman_sio2packet_PS1PDA.stat6c & 0xf000) == 0x1000)
                                 break;
         } while (++retries < 5);
         if (retries >= 5)
                 return -11;
         return sceMcResSucceed;
 }
References DPRINTF, sio2_transfer_data_t::in_size, mcman_sio2inbufs_PS1PDA, mcman_sio2packet_PS1PDA, mcman_sio2transfer, sio2_transfer_data_t::out_size, sio2_transfer_data_t::regdata, sceMcResSucceed, and sio2_transfer_data_t::stat6c.
Referenced by McDetectCard2(), and mcman_detectcard().
mcman_probePS1Card()
int mcman_probePS1Card (int port, int slot)
Definition at line 893 of file mcsio2.c.
 {
         register int i, r, retries;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         u32 *p;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_probePS1Card port%d slot%d\n", port, slot);
 #endif
         mcman_sio2packet_PS1PDA.regdata[0] = 0;
         mcman_sio2packet_PS1PDA.regdata[0] = (((port & 1) + 2)) | 0x000c0340;
         mcman_sio2packet_PS1PDA.in_size = 3;
         mcman_sio2packet_PS1PDA.out_size = 3;
         mcman_sio2packet_PS1PDA.regdata[1] = 0;
         mcman_sio2inbufs_PS1PDA[0] = 0x81;
         mcman_sio2inbufs_PS1PDA[1] = 0x52;
         retries = 0;
         do {
                 mcman_timercount = (u32)(GetTimerCounter(timer_ID) - mcman_timercount);
                 u32 hi, lo;
                 long_multiply(mcman_timercount, 0x3e0f83e1, &hi, &lo);
                 if ((u32)((hi >> 3) < mcman_timerthick))
                         DelayThread(mcman_timerthick - (hi >> 3));
                 mcman_sio2transfer(port, slot, &mcman_sio2packet_PS1PDA);
                 mcman_timercount = GetTimerCounter(timer_ID);
                 mcman_timerthick = 0;
                 if (((mcman_sio2packet_PS1PDA.stat6c & 0xf000) == 0x1000) \
                                 && (mcman_sio2outbufs_PS1PDA[2] == 0x5a)) {
                         break;
                 }
         } while (++retries < 5);
         if (retries >= 5)
                 return -11;
         if (mcman_sio2outbufs_PS1PDA[1] == 0) {
                 if (mcdi->cardform != 0)
                         return sceMcResSucceed;
         }
         else if (mcman_sio2outbufs_PS1PDA[1] != 8) {
                 return -12;
         }
         mcman_clearcache(port, slot);
         p = (u32 *)&mcman_sio2outbufs_PS1PDA[124];
         for (i = 31; i >= 0; i--)
                 *p-- = 0;
         r = McWritePS1PDACard(port, slot, 63, mcman_sio2outbufs_PS1PDA);
         if (r < 0)
                 return -13;
         r = mcman_setPS1devinfos(port, slot);
         if (r == 0)
                 return sceMcResChangedCard;
         mcdi->cardform = r;
         return r;
 }
References MCDevInfo::cardform, DelayThread(), DPRINTF, GetTimerCounter(), sio2_transfer_data_t::in_size, long_multiply(), mcman_clearcache(), mcman_devinfos, mcman_setPS1devinfos(), mcman_sio2inbufs_PS1PDA, mcman_sio2outbufs_PS1PDA, mcman_sio2packet_PS1PDA, mcman_sio2transfer, mcman_timercount, mcman_timerthick, McWritePS1PDACard(), sio2_transfer_data_t::out_size, sio2_transfer_data_t::regdata, sceMcResChangedCard, sceMcResSucceed, sio2_transfer_data_t::stat6c, and timer_ID.
Referenced by McDetectCard2().
mcman_probePS1Card2()
int mcman_probePS1Card2 (int port, int slot)
Definition at line 837 of file mcsio2.c.
 {
         register int retries;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
 #ifdef DEBUG
         DPRINTF("mcman: mcman_probePS1Card2 port%d slot%d\n", port, slot);
 #endif
         mcman_sio2packet_PS1PDA.regdata[0] = 0;
         mcman_sio2packet_PS1PDA.regdata[0] = (((port & 1) + 2)) | 0x000c0340;
         mcman_sio2packet_PS1PDA.in_size = 3;
         mcman_sio2packet_PS1PDA.out_size = 3;
         mcman_sio2packet_PS1PDA.regdata[1] = 0;
         mcman_sio2inbufs_PS1PDA[0] = 0x81;
         mcman_sio2inbufs_PS1PDA[1] = 0x52;
         retries = 0;
         do {
                 mcman_timercount = (u32)(GetTimerCounter(timer_ID) - mcman_timercount);
                 u32 hi, lo;
                 long_multiply(mcman_timercount, 0x3e0f83e1, &hi, &lo);
                 if ((u32)((hi >> 3) < mcman_timerthick))
                         DelayThread(mcman_timerthick - (hi >> 3));
                 mcman_sio2transfer(port, slot, &mcman_sio2packet_PS1PDA);
                 mcman_timercount = GetTimerCounter(timer_ID);
                 mcman_timerthick = 0;
                 if (((mcman_sio2packet_PS1PDA.stat6c & 0xf000) == 0x1000) \
                                 && (mcman_sio2outbufs_PS1PDA[2] == 0x5a)) {
                         break;
                 }
         } while (++retries < 5);
         if (retries >= 5)
                 return -12;
         if (mcman_sio2outbufs_PS1PDA[1] == 0) {
                 if (mcdi->cardform > 0)
                         return sceMcResSucceed;
                 if (mcdi->cardform < 0)
                         return sceMcResNoFormat;
         }
         else if (mcman_sio2outbufs_PS1PDA[1] != 8) {
                 return -14;
         }
         return -13;
 }
References MCDevInfo::cardform, DelayThread(), DPRINTF, GetTimerCounter(), sio2_transfer_data_t::in_size, long_multiply(), mcman_devinfos, mcman_sio2inbufs_PS1PDA, mcman_sio2outbufs_PS1PDA, mcman_sio2packet_PS1PDA, mcman_sio2transfer, mcman_timercount, mcman_timerthick, sio2_transfer_data_t::out_size, sio2_transfer_data_t::regdata, sceMcResNoFormat, sceMcResSucceed, sio2_transfer_data_t::stat6c, and timer_ID.
Referenced by mcman_detectcard(), and mcman_flushcacheentry().
mcman_probePS2Card()
int mcman_probePS2Card (int port, int slot)
Definition at line 730 of file mcsio2.c.
 {
         register int retries, r;
         register MCDevInfo *mcdi;
         u8 *p = mcman_sio2packet.out_dma.addr;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_probePS2Card sio2cmd port%d slot%d\n", port, slot);
 #endif
         r = mcman_cardchanged(port, slot);
         if (r == sceMcResSucceed) {
                 r = McGetFormat(port, slot);
                 if (r != 0) {
 #ifdef DEBUG
                         DPRINTF("mcman: mcman_probePS2Card sio2cmd succeeded\n");
 #endif
                         return sceMcResSucceed;
                 }
         }
         if (mcman_resetauth(port, slot) != sceMcResSucceed) {
 #ifdef DEBUG
                 DPRINTF("mcman: mcman_probePS2Card sio2cmd failed (auth reset failed)\n");
 #endif
                 return sceMcResFailResetAuth;
         }
         if (SecrAuthCard(port + 2, slot, mcman_getcnum(port, slot)) == 0) {
 #ifdef DEBUG
                 DPRINTF("mcman: mcman_probePS2Card sio2cmd failed (auth failed)\n");
 #endif
                 return sceMcResFailAuth;
         }
         retries = 0;
         do {
                 sio2packet_add(port, slot, 0xffffffff, NULL);
                 sio2packet_add(port, slot, 0x09, NULL);
                 sio2packet_add(port, slot, 0xfffffffe, NULL);
                 mcman_sio2transfer(port, slot, &mcman_sio2packet);
                 if (((mcman_sio2packet.stat6c & 0xF000) == 0x1000) && (p[4] != 0x66))
                         break;
         } while (++retries < 5);
         if (retries >= 5) {
 #ifdef DEBUG
                 DPRINTF("mcman: mcman_probePS2Card sio2cmd failed (mc detection failed)\n");
 #endif
                 return sceMcResFailDetect;
         }
         mcman_clearcache(port, slot);
         sio2packet_add(port, slot, 0xffffffff, NULL);
         sio2packet_add(port, slot, 0x08, NULL);
         sio2packet_add(port, slot, 0xfffffffe, NULL);
         retries = 0;
     do {
                 mcman_sio2transfer(port, slot, &mcman_sio2packet);
         if ((mcman_sio2packet.stat6c & 0xF000) != 0x1000)
                 continue;
         if (p[4] == 0x5a)
                 break;
         } while (++retries < 5);
         if (retries >= 5) {
 #ifdef DEBUG
                 DPRINTF("mcman: mcman_probePS2Card sio2cmd failed (mc detection failed)\n");
 #endif
                 return sceMcResFailDetect2;
         }
         r = mcman_setdevinfos(port, slot);
         if (r == 0) {
 #ifdef DEBUG
                 DPRINTF("mcman: mcman_probePS2Card sio2cmd card changed!\n");
 #endif
                 return sceMcResChangedCard;
         }
         if (r != sceMcResNoFormat) {
 #ifdef DEBUG
                 DPRINTF("mcman: mcman_probePS2Card sio2cmd failed (mc detection failed)\n");
 #endif
                 return sceMcResFailDetect2;
         }
         mcdi = &mcman_devinfos[port][slot];
         mcdi->cardform = r;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_probePS2Card sio2cmd succeeded\n");
 #endif
         return r;
 }
References _sio2_dma_arg::addr, MCDevInfo::cardform, DPRINTF, McGetFormat(), mcman_cardchanged(), mcman_clearcache(), mcman_devinfos, mcman_getcnum(), mcman_resetauth(), mcman_setdevinfos(), mcman_sio2packet, mcman_sio2transfer, NULL, sio2_transfer_data_t::out_dma, sceMcResChangedCard, sceMcResFailAuth, sceMcResFailDetect, sceMcResFailDetect2, sceMcResFailResetAuth, sceMcResNoFormat, sceMcResSucceed, SecrAuthCard(), sio2packet_add(), and sio2_transfer_data_t::stat6c.
Referenced by McDetectCard2().
mcman_probePS2Card2()
int mcman_probePS2Card2 (int port, int slot)
Definition at line 678 of file mcsio2.c.
 {
         register int retries, r;
         u8 *p = mcman_sio2packet.out_dma.addr;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_probePS2Card2 sio2cmd port%d slot%d\n", port, slot);
 #endif
         retries = 0;
         do {
                 sio2packet_add(port, slot, 0xffffffff, NULL);
                 sio2packet_add(port, slot, 0x09, NULL);
                 sio2packet_add(port, slot, 0xfffffffe, NULL);
                 mcman_sio2transfer(port, slot, &mcman_sio2packet);
                 if (((mcman_sio2packet.stat6c & 0xF000) == 0x1000) && (p[4] != 0x66))
                         break;
         } while (++retries < 5);
         if (retries >= 5)
                 return sceMcResFailDetect;
         if (p[3] == 0x5a) {
                 r = McGetFormat(port, slot);
                 if (r > 0) {
 #ifdef DEBUG
                         DPRINTF("mcman: mcman_probePS2Card2 succeeded\n");
 #endif
                         return sceMcResSucceed;
                 }
                 r = McGetFormat(port, slot);
                 if (r < 0) {
 #ifdef DEBUG
                         DPRINTF("mcman: mcman_probePS2Card2 sio2cmd failed (no format)\n");
 #endif
                         return sceMcResNoFormat;
                 }
         }
 #ifdef DEBUG
         DPRINTF("mcman: mcman_probePS2Card2 sio2cmd failed (mc detection failed)\n");
 #endif
         return sceMcResFailDetect2;
 }
References _sio2_dma_arg::addr, DPRINTF, McGetFormat(), mcman_sio2packet, mcman_sio2transfer, NULL, sio2_transfer_data_t::out_dma, sceMcResFailDetect, sceMcResFailDetect2, sceMcResNoFormat, sceMcResSucceed, sio2packet_add(), and sio2_transfer_data_t::stat6c.
Referenced by McCheckBlock(), and mcman_detectcard().
mcman_readpage()
int mcman_readpage (int port, int slot, int page, void * buf, void * eccbuf)
Definition at line 525 of file mcsio2.c.
 {
         register int index, count, retries, r, i;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         u8 *pbuf = (u8 *)buf;
         u8 *pecc = (u8 *)eccbuf;
         u8 *p = mcman_sio2packet.out_dma.addr;
         count = (mcdi->pagesize + 127) >> 7;
         retries = 0;
         do {
                 if (retries > 0)
                         mcman_cardchanged(port, slot);
                 sio2packet_add(port, slot, 0xffffffff, NULL);
                 sio2packet_add(port, slot, 0x04, (u8 *)&page);
                 if (count > 0) {
                         index = 0;
                 while (index < count) {
                         sio2packet_add(port, slot, 0x0b, NULL);
                         index++;
                 }
                 }
                 if (mcdi->cardflags & CF_USE_ECC) // if memcard have ECC support
                         sio2packet_add(port, slot, 0x0f, NULL);
                 sio2packet_add(port, slot, 0x0c, NULL);
                 sio2packet_add(port, slot, 0xfffffffe, NULL);
                 mcman_sio2transfer(port, slot, &mcman_sio2packet);
                 if (((mcman_sio2packet.stat6c & 0xF000) != 0x1000)
                         || (p[8] != 0x5a)
                                 || (p[0x94 + 0x2cf] != 0x5a))
                         continue;
                 if (count > 0) {
                         index = 0;
                         while (index < count) {
                                 // checking EDC
                                 r = mcman_calcEDC(&p[0x94 + ((index + (index << 3)) << 4)], 128) & 0xFF;
                                 if (r != p[0x94 + 128 + ((index + (index << 3)) << 4)])
                                         break;
                         index++;
                         }
                         if (index < count)
                                 continue;
                         index = 0;
                         while (index < count) {
                         for (i=0; i<128; i++)
                                 pbuf[(index << 7) + i] = p[0x94 + ((index + (index << 3)) << 4) + i];
                         index++;
                         }
                 }
                 memcpy(pecc, &p[0x94 + ((count + (count << 3)) << 4)] , mcman_sparesize(port, slot));
                 break;
         } while (++retries < 5);
         if (retries < 5)
                 return sceMcResSucceed;
         return sceMcResChangedCard;
 }
References _sio2_dma_arg::addr, MCDevInfo::cardflags, CF_USE_ECC, index(), mcman_calcEDC(), mcman_cardchanged(), mcman_devinfos, mcman_sio2packet, mcman_sio2transfer, mcman_sparesize(), memcpy(), NULL, sio2_transfer_data_t::out_dma, MCDevInfo::pagesize, sceMcResChangedCard, sceMcResSucceed, sio2packet_add(), and sio2_transfer_data_t::stat6c.
Referenced by McCheckBlock(), and McReadPage().
mcman_resetauth()
int mcman_resetauth (int port, int slot)
Definition at line 640 of file mcsio2.c.
 {
         register int retries;
 #ifdef DEBUG
         DPRINTF("mcman: mcman_resetauth sio2cmd port%d slot%d\n", port, slot);
 #endif
         sio2packet_add(port, slot, 0xffffffff, NULL);
         sio2packet_add(port, slot, 0x11, NULL);
         sio2packet_add(port, slot, 0xfffffffe, NULL);
         retries = 0;
         do {
                 mcman_sio2transfer(port, slot, &mcman_sio2packet);
                 if ((mcman_sio2packet.stat6c & 0xF000) == 0x1000)
                         break;
         } while (++retries < 5);
         if (retries >= 5) {
 #ifdef DEBUG
                 DPRINTF("mcman: mcman_resetauth sio2cmd card changed!\n");
 #endif
                 return sceMcResChangedCard;
         }
 #ifdef DEBUG
         DPRINTF("mcman: mcman_resetauth sio2cmd succeeded\n");
 #endif
         return sceMcResSucceed;
 }
References DPRINTF, mcman_sio2packet, mcman_sio2transfer, NULL, sceMcResChangedCard, sceMcResSucceed, sio2packet_add(), and sio2_transfer_data_t::stat6c.
Referenced by mcman_probePS2Card().
McReadPS1PDACard()
int McReadPS1PDACard (int port, int slot, int page, void * buf)
Definition at line 1062 of file mcsio2.c.
 {
         register int i, retries;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         u8 *p;
 #ifdef DEBUG
         //DPRINTF("mcman: McReadPS1PDACard port%d slot%d page %x\n", port, slot, page);
 #endif
         mcman_sio2packet_PS1PDA.regdata[0] = 0;
         mcman_sio2packet_PS1PDA.regdata[0] = (((port & 1) + 2) & 3) | 0x02308c40;
         mcman_sio2packet_PS1PDA.in_size = 140;
         mcman_sio2packet_PS1PDA.out_size = 140;
         mcman_sio2packet_PS1PDA.regdata[1] = 0;
         for (i = 0; i < 20; i++) {
                 if (mcdi->bad_block_list[i] == page)
                         page += 36;
         }
         mcman_sio2inbufs_PS1PDA[0] = 0x81;
         mcman_sio2inbufs_PS1PDA[1] = 0x52;
         mcman_sio2inbufs_PS1PDA[4] = (u8)(page >> 8);
         mcman_sio2inbufs_PS1PDA[5] = (u8)page;
         retries = 0;
         do {
                 mcman_timercount = (u32)(GetTimerCounter(timer_ID) - mcman_timercount);
                 u32 hi, lo;
                 long_multiply(mcman_timercount, 0x3e0f83e1, &hi, &lo);
                 if ((u32)((hi >> 3) < mcman_timerthick))
                         DelayThread(mcman_timerthick - (hi >> 3));
                 mcman_sio2transfer(port, slot, &mcman_sio2packet_PS1PDA);
                 mcman_timercount = GetTimerCounter(timer_ID);
                 mcman_timerthick = 10000;
                 if (((mcman_sio2packet_PS1PDA.stat6c & 0xf000) == 0x1000) \
                                 && (mcman_sio2outbufs_PS1PDA[2] == 0x5a) \
                                         && (mcman_sio2outbufs_PS1PDA[3] == 0x5d) \
                                                 && (mcman_sio2outbufs_PS1PDA[4] == 0x00) \
                                                         && (mcman_sio2outbufs_PS1PDA[6] == 0x5c) \
                                                                 && (mcman_sio2outbufs_PS1PDA[7] == 0x5d) \
                                                                         && (mcman_sio2outbufs_PS1PDA[139] == 0x47)) {
                         if (mcman_sio2outbufs_PS1PDA[138] == (mcman_calcEDC(&mcman_sio2outbufs_PS1PDA[8], 130) & 0xff))
                                 break;
                 }
         } while (++retries < 5);
         if (retries >= 5)
                 return sceMcResNoEntry;
         p = (u8 *)buf;
         for (i = 0; i < 128; i++)
                 p[i] = mcman_sio2outbufs_PS1PDA[10 + i];
         if ((mcman_sio2outbufs_PS1PDA[1] != 0) && (mcman_sio2outbufs_PS1PDA[1] != 8))
                 return sceMcResDeniedPermit;
         return sceMcResSucceed;
 }
References MCDevInfo::bad_block_list, DelayThread(), GetTimerCounter(), sio2_transfer_data_t::in_size, long_multiply(), mcman_calcEDC(), mcman_devinfos, mcman_sio2inbufs_PS1PDA, mcman_sio2outbufs_PS1PDA, mcman_sio2packet_PS1PDA, mcman_sio2transfer, mcman_timercount, mcman_timerthick, sio2_transfer_data_t::out_size, sio2_transfer_data_t::regdata, sceMcResDeniedPermit, sceMcResNoEntry, sceMcResSucceed, sio2_transfer_data_t::stat6c, and timer_ID.
Referenced by mcman_PS1pagetest(), mcman_readclusterPS1(), and mcman_setPS1devinfos().
mcsio2_transfer()
int mcsio2_transfer (int port, int slot, sio2_transfer_data_t * sio2data)
Definition at line 227 of file mcsio2.c.
 {
         register int r;
 #ifdef DEBUG
         u8 *p = (u8 *)(sio2data->in_dma.addr);
         if (p)
                 DPRINTF("mcman: mcsio2_transfer port%d slot%d cmd = %02x %02x %02x ", port, slot, p[0], p[1], p[2]);
         else {
                 p = (u8 *)(sio2data->in);
                 DPRINTF("mcman: mcsio2_transfer for secrman port%d slot%d cmd = %02x %02x %02x ", port, slot, p[0], p[1], p[2]);
         }
 #endif
         // SIO2 transfer for MCMAN
         psio2_mc_transfer_init();
         r = psio2_transfer(sio2data);
 #ifdef DEBUG
         DPRINTF("returns %d\n", r);
 #endif
         return r;
 }
References _sio2_dma_arg::addr, DPRINTF, sio2_transfer_data_t::in, sio2_transfer_data_t::in_dma, psio2_mc_transfer_init, and psio2_transfer.
Referenced by _start().
mcsio2_transfer2()
int mcsio2_transfer2 (int port, int slot, sio2_transfer_data_t * sio2data)
Definition at line 253 of file mcsio2.c.
 {
         // SIO2 transfer for XMCMAN
         register int r;
         s32 port_ctrl[8];
 #ifdef DEBUG
         DPRINTF("mcman: mcsio2_transfer2 port%d slot%d\n", port, slot);
 #endif
         port_ctrl[0] = -1;
         port_ctrl[1] = -1;
         port_ctrl[2] = -1;
         port_ctrl[3] = -1;
         port_ctrl[(port & 1) + 2] = slot;
         psio2_mc_transfer_init();
         psio2_mtap_change_slot(port_ctrl);
         r = psio2_transfer(sio2data);
         psio2_transfer_reset();
 #ifdef DEBUG
         DPRINTF("mcman: mcsio2_transfer2 returns %d\n", r);
 #endif
         return r;
 }
References DPRINTF, psio2_mc_transfer_init, psio2_mtap_change_slot, psio2_transfer, and psio2_transfer_reset.
Referenced by _start().
McWritePage()
int McWritePage (int port, int slot, int page, void * pagebuf, void * eccbuf)
Definition at line 454 of file mcsio2.c.
 {
         register int index, count, retries;
         u8 *p_pagebuf = (u8 *)pagebuf;
         u8 *p = mcman_sio2packet.out_dma.addr;
         count = (mcman_devinfos[port][slot].pagesize + 127) >> 7;
         retries = 0;
         do {
                 if (retries > 0)
                         mcman_cardchanged(port, slot);
                 sio2packet_add(port, slot, 0xffffffff, NULL);
                 sio2packet_add(port, slot, 0x03, (u8 *)&page);
                 index = 0;
                 while (index < count) {
                 sio2packet_add(port, slot, 0x0a, (u8 *)&p_pagebuf[index << 7]);
                         index++;
                 }
                 if (mcman_devinfos[port][slot].cardflags & CF_USE_ECC) {
                 // if memcard have ECC support
                         sio2packet_add(port, slot, 0x0e, eccbuf);
                 }
                 sio2packet_add(port, slot, 0xfffffffe, NULL);
                 mcman_sio2transfer(port, slot, &mcman_sio2packet);
                 if (((mcman_sio2packet.stat6c & 0xF000) != 0x1000) || (p[8] != 0x5a))
                         continue;
                 index = 0;
                 while (index < count) {
                         if (p[0x94 + 128 + 1 + ((index + (index << 3)) << 4)] != 0x5a)
                                 break;
                         index++;
                 }
                 if (index < count)
                         continue;
                 if (mcman_devinfos[port][slot].cardflags & CF_USE_ECC) {
                 // if memcard have ECC support
                         index++;
                 if (p[5 + ((index + (index << 3)) << 4) + mcman_sparesize(port, slot)] != 0x5a)
                         continue;
                 }
                 sio2packet_add(port, slot, 0xffffffff, NULL);
                 sio2packet_add(port, slot, 0x0c, NULL);
                 sio2packet_add(port, slot, 0xfffffffe, NULL);
                 mcman_sio2transfer(port, slot, &mcman_sio2packet);
                 if (((mcman_sio2packet.stat6c & 0xF000) != 0x1000) || (p[3] != 0x5a))
                         continue;
                 return sceMcResSucceed;
         } while (++retries < 5);
         if (p[3] == 0x66)
                 return sceMcResFailReplace;
         return sceMcResNoFormat;
 }
References _sio2_dma_arg::addr, CF_USE_ECC, index(), mcman_cardchanged(), mcman_devinfos, mcman_sio2packet, mcman_sio2transfer, mcman_sparesize(), NULL, sio2_transfer_data_t::out_dma, MCDevInfo::pagesize, sceMcResFailReplace, sceMcResNoFormat, sceMcResSucceed, sio2packet_add(), and sio2_transfer_data_t::stat6c.
Referenced by McCheckBlock(), mcman_checkBackupBlocks(), mcman_fillbackupblock1(), mcman_flushcacheentry(), mcman_unformat2(), and mcman_writecluster().
McWritePS1PDACard()
int McWritePS1PDACard (int port, int slot, int page, void * buf)
Definition at line 997 of file mcsio2.c.
 {
         register int i, retries;
         register MCDevInfo *mcdi = &mcman_devinfos[port][slot];
         u8 *p;
 #ifdef DEBUG
         //DPRINTF("mcman: McWritePS1PDACard port%d slot%d page %x\n", port, slot, page);
 #endif
         mcman_sio2packet_PS1PDA.regdata[0] = 0;
         mcman_sio2packet_PS1PDA.regdata[0] = (((port & 1) + 2) & 3) | 0x02288a40;
         mcman_sio2packet_PS1PDA.in_size = 138;
         mcman_sio2packet_PS1PDA.out_size = 138;
         mcman_sio2packet_PS1PDA.regdata[1] = 0;
         for (i = 0; i < 20; i++) {
                 if (mcdi->bad_block_list[i] == page)
                         page += 36;
         }
         mcman_sio2inbufs_PS1PDA[0] = 0x81;
         mcman_sio2inbufs_PS1PDA[1] = 0x57;
         mcman_sio2inbufs_PS1PDA[4] = (u8)(page >> 8);
         mcman_sio2inbufs_PS1PDA[5] = (u8)page;
         p = (u8 *)buf;
         for (i = 0; i < 128; i++)
                 mcman_sio2inbufs_PS1PDA[6 + i] = p[i];
         mcman_sio2inbufs_PS1PDA[4 + 130] = mcman_calcEDC(&mcman_sio2inbufs_PS1PDA[4], 130);
         retries = 0;
         do {
                 mcman_timercount = (u32)(GetTimerCounter(timer_ID) - mcman_timercount);
                 u32 hi, lo;
                 long_multiply(mcman_timercount, 0x3e0f83e1, &hi, &lo);
                 if ((u32)((hi >> 3) < mcman_timerthick))
                         DelayThread(mcman_timerthick - (hi >> 3));
                 mcman_sio2transfer(port, slot, &mcman_sio2packet_PS1PDA);
                 mcman_timercount = GetTimerCounter(timer_ID);
                 mcman_timerthick = 20000;
                 if (((mcman_sio2packet_PS1PDA.stat6c & 0xf000) == 0x1000) \
                                 && (mcman_sio2outbufs_PS1PDA[2] == 0x5a) \
                                         && (mcman_sio2outbufs_PS1PDA[3] == 0x5d) \
                                                 && (mcman_sio2outbufs_PS1PDA[137] == 0x47)) {
                         break;
                 }
         } while (++retries < 5);
         if (retries >= 5)
                 return sceMcResNoEntry;
         if ((mcman_sio2outbufs_PS1PDA[1] != 0) && (mcman_sio2outbufs_PS1PDA[1] != 8))
                 return sceMcResFullDevice;
         return sceMcResSucceed;
 }
References MCDevInfo::bad_block_list, DelayThread(), GetTimerCounter(), sio2_transfer_data_t::in_size, long_multiply(), mcman_calcEDC(), mcman_devinfos, mcman_sio2inbufs_PS1PDA, mcman_sio2outbufs_PS1PDA, mcman_sio2packet_PS1PDA, mcman_sio2transfer, mcman_timercount, mcman_timerthick, sio2_transfer_data_t::out_size, sio2_transfer_data_t::regdata, sceMcResFullDevice, sceMcResNoEntry, sceMcResSucceed, sio2_transfer_data_t::stat6c, and timer_ID.
Referenced by mcman_fillPS1backuparea(), mcman_flushcacheentry(), mcman_format1(), mcman_probePS1Card(), mcman_PS1pagetest(), and mcman_unformat1().
secrman_mc_command()
int secrman_mc_command (int port, int slot, sio2_transfer_data_t * sio2data)
Definition at line 330 of file mcsio2.c.
 {
         register int r;
 #ifdef DEBUG
         DPRINTF("mcman: secrman_mc_command port%d slot%d\n", port, slot);
 #endif
         r = mcman_sio2transfer(port, slot, sio2data);
         return r;
 }
References DPRINTF, and mcman_sio2transfer.
Referenced by mcman_initPS2com().
sio2packet_add()
void sio2packet_add (int port, int slot, int cmd, u8 * buf)
Definition at line 73 of file mcsio2.c.
 {       // Used to build the sio2packets for all mc commands
         register u32 regdata;
         register int pos;
         u8 *p;
         if (cmd == 0xffffffff) {
                 mcman_sio2packet.in_dma.count = 0;
                 return;
         }
         if (mcman_sio2packet.in_dma.count < 0xb) {
                 if (cmd == 0xfffffffe) {
                         mcman_sio2packet.regdata[mcman_sio2packet.in_dma.count] = 0;
                         mcman_sio2packet.out_dma.count = mcman_sio2packet.in_dma.count;
                         return;
                 }
                 regdata = (((port & 1) + 2) & 3) | 0x70;
                 regdata |= mcman_cmdtable[(cmd << 1) + 1] << 18;
                 regdata |= mcman_cmdtable[(cmd << 1) + 1] << 8;
                 mcman_sio2packet.regdata[mcman_sio2packet.in_dma.count] = regdata;
                 pos = ((mcman_sio2packet.in_dma.count + (mcman_sio2packet.in_dma.count << 3)) << 4);
                 mcman_sio2packet.in_dma.count++;
                 p = mcman_sio2packet.in_dma.addr + pos;
                 p[0] = 0x81;
                 p[1] = mcman_cmdtable[cmd << 1];
                 if (((cmd - 1) >= 16) || ((cmd - 1) < 0))
                         return;
                 sio2packet_add_func = (void*)sio2packet_add_funcs_array[(cmd - 1)];
                 (sio2packet_add_func)(port, slot, cmd, buf, pos); // call to the needed child func
         }
 }
References _sio2_dma_arg::addr, _sio2_dma_arg::count, sio2_transfer_data_t::in_dma, mcman_cmdtable, mcman_sio2packet, sio2_transfer_data_t::out_dma, pos, sio2_transfer_data_t::regdata, sio2packet_add_func, and sio2packet_add_funcs_array.
Referenced by McGetCardSpec(), mcman_cardchanged(), mcman_eraseblock(), mcman_probePS2Card(), mcman_probePS2Card2(), mcman_readpage(), mcman_resetauth(), and McWritePage().
sio2packet_add_do_nothing()
static void sio2packet_add_do_nothing (int port, int slot, int cmd, u8 * buf, int pos) static
Definition at line 221 of file mcsio2.c.
 {
         // do nothing
 }
sio2packet_add_ecc_in()
static void sio2packet_add_ecc_in (int port, int slot, int cmd, u8 * buf, int pos) static
Definition at line 153 of file mcsio2.c.
 {
         // used for sio2 command 0x81 0x42 to write page ecc
         register u32 regdata;
         int i;
         u8 *p = mcman_sio2packet.in_dma.addr + pos;
         p[2] = mcman_sparesize(port, slot);
         for (i=0; i<(p[2] & 0xff); i++)
                 p[3 + i] = buf[i];
         p[3 + p[2]] = mcman_calcEDC(&buf[0], p[2]);
         regdata  = (p[2] + mcman_cmdtable[(cmd << 1) + 1]) << 18;
         regdata |= mcman_sio2packet.regdata[mcman_sio2packet.in_dma.count-1] & 0xf803ffff;
         regdata &= 0xfffe00ff;
         regdata |= (p[2] + mcman_cmdtable[(cmd << 1) + 1]) << 8;
         mcman_sio2packet.regdata[mcman_sio2packet.in_dma.count-1] = regdata;
 }
References _sio2_dma_arg::addr, _sio2_dma_arg::count, sio2_transfer_data_t::in_dma, mcman_calcEDC(), mcman_cmdtable, mcman_sio2packet, mcman_sparesize(), pos, and sio2_transfer_data_t::regdata.
sio2packet_add_ecc_out()
static void sio2packet_add_ecc_out (int port, int slot, int cmd, u8 * buf, int pos) static
Definition at line 177 of file mcsio2.c.
 {
         // used for sio2 command 0x81 0x43 to read page ecc
         register u32 regdata;
         u8 *p = mcman_sio2packet.in_dma.addr + pos;
         p[2] = mcman_sparesize(port, slot);
         regdata  = (p[2] + mcman_cmdtable[(cmd << 1) + 1]) << 18;
         regdata |= mcman_sio2packet.regdata[mcman_sio2packet.in_dma.count-1] & 0xf803ffff;
         regdata &= 0xfffe00ff;
         regdata |= (p[2] + mcman_cmdtable[(cmd << 1) + 1]) << 8;
         mcman_sio2packet.regdata[mcman_sio2packet.in_dma.count-1] = regdata;
 }
References _sio2_dma_arg::addr, _sio2_dma_arg::count, sio2_transfer_data_t::in_dma, mcman_cmdtable, mcman_sio2packet, mcman_sparesize(), pos, and sio2_transfer_data_t::regdata.
sio2packet_add_pagedata_in()
static void sio2packet_add_pagedata_in (int port, int slot, int cmd, u8 * buf, int pos) static
Definition at line 138 of file mcsio2.c.
 {
         // used for sio2 command 0x81 0x42 to write page data
         register int i;
         u8 *p = mcman_sio2packet.in_dma.addr + pos;
         p[2] = 128;
         for (i=0; i<128; i++)
                 p[3 + i] = buf[i];
         p[3 + 128] = mcman_calcEDC(&buf[0], 128);
 }
References _sio2_dma_arg::addr, sio2_transfer_data_t::in_dma, mcman_calcEDC(), mcman_sio2packet, and pos.
sio2packet_add_pagedata_out()
static void sio2packet_add_pagedata_out (int port, int slot, int cmd, u8 * buf, int pos) static
Definition at line 129 of file mcsio2.c.
 {
         // used for sio2 command 0x81 0x43 to read page data
         u8 *p = mcman_sio2packet.in_dma.addr + pos;
         p[2] = 128;
 }
References _sio2_dma_arg::addr, sio2_transfer_data_t::in_dma, mcman_sio2packet, and pos.
sio2packet_add_wdma_00()
static void sio2packet_add_wdma_00 (int port, int slot, int cmd, u8 * buf, int pos) static
Definition at line 204 of file mcsio2.c.
 {
         u8 *p = mcman_sio2packet.in_dma.addr + pos;
         p[2] = 0x00;
 }
References _sio2_dma_arg::addr, sio2_transfer_data_t::in_dma, mcman_sio2packet, and pos.
sio2packet_add_wdma_5a()
static void sio2packet_add_wdma_5a (int port, int slot, int cmd, u8 * buf, int pos) static
Definition at line 195 of file mcsio2.c.
 {
         // used for sio2 command 0x81 0x27 to set a termination code
         u8 *p = mcman_sio2packet.in_dma.addr + pos;
         p[2] = 0x5a;
 }
References _sio2_dma_arg::addr, sio2_transfer_data_t::in_dma, mcman_sio2packet, and pos.
sio2packet_add_wdma_u32()
static void sio2packet_add_wdma_u32 (int port, int slot, int cmd, u8 * buf, int pos) static
Definition at line 117 of file mcsio2.c.
 {
         u8 *p = mcman_sio2packet.in_dma.addr + pos;
         p[2] = buf[0];
         p[3] = buf[1];
         p[4] = buf[2];
         p[5] = buf[3];
         p[6] = mcman_calcEDC(&p[2], 4);
 }
References _sio2_dma_arg::addr, sio2_transfer_data_t::in_dma, mcman_calcEDC(), mcman_sio2packet, and pos.
sio2packet_add_wdma_u8()
static void sio2packet_add_wdma_u8 (int port, int slot, int cmd, u8 * buf, int pos) static
Definition at line 213 of file mcsio2.c.
 {
         u8 *p = mcman_sio2packet.in_dma.addr + pos;
         p[2] = buf[0];
 }
References _sio2_dma_arg::addr, sio2_transfer_data_t::in_dma, mcman_sio2packet, and pos.
Variable Documentation
mcman_cmdtable
const u8 mcman_cmdtable[36] static
Initial value:
= {
        0x11, 0x04, 0x12, 0x04, 0x21, 0x09, 0x22, 0x09,
        0x23, 0x09, 0x24, 0x86, 0x25, 0x04, 0x26, 0x0d,
        0x27, 0x05, 0x28, 0x05, 0x42, 0x86, 0x43, 0x86,
        0x81, 0x04, 0x82, 0x04, 0x42, 0x06, 0x43, 0x06,
        0xbf, 0x05, 0xf3, 0x05
}
Definition at line 30 of file mcsio2.c.
Referenced by sio2packet_add(), sio2packet_add_ecc_in(), and sio2packet_add_ecc_out().
mcman_devinfos
MCDevInfo mcman_devinfos[4][MCMAN_MAXSLOT] extern
Definition at line 56 of file main.c.
Referenced by mcman_eraseblock(), mcman_probePS1Card(), mcman_probePS1Card2(), mcman_probePS2Card(), mcman_readpage(), McReadPS1PDACard(), McWritePage(), and McWritePS1PDACard().
mcman_rdmabufs
u8 mcman_rdmabufs[0x0b *0x90] static
Definition at line 20 of file mcsio2.c.
Referenced by mcman_initPS2com().
mcman_sio2inbufs_PS1PDA
u8 mcman_sio2inbufs_PS1PDA[0x90] static
Definition at line 23 of file mcsio2.c.
Referenced by mcman_initPS1PDAcom(), mcman_probePDACard(), mcman_probePS1Card(), mcman_probePS1Card2(), McReadPS1PDACard(), and McWritePS1PDACard().
mcman_sio2outbufs_PS1PDA
u8 mcman_sio2outbufs_PS1PDA[0x90]
Definition at line 24 of file mcsio2.c.
Referenced by mcman_initPS1PDAcom(), mcman_probePS1Card(), mcman_probePS1Card2(), mcman_setPS1devinfos(), McReadPS1PDACard(), and McWritePS1PDACard().
mcman_sio2packet
sio2_transfer_data_t mcman_sio2packet static
Definition at line 18 of file mcsio2.c.
Referenced by McGetCardSpec(), mcman_cardchanged(), mcman_eraseblock(), mcman_initPS2com(), mcman_probePS2Card(), mcman_probePS2Card2(), mcman_readpage(), mcman_resetauth(), McWritePage(), sio2packet_add(), sio2packet_add_ecc_in(), sio2packet_add_ecc_out(), sio2packet_add_pagedata_in(), sio2packet_add_pagedata_out(), sio2packet_add_wdma_00(), sio2packet_add_wdma_5a(), sio2packet_add_wdma_u32(), and sio2packet_add_wdma_u8().
mcman_sio2packet_PS1PDA
sio2_transfer_data_t mcman_sio2packet_PS1PDA static
Definition at line 22 of file mcsio2.c.
Referenced by mcman_initPS1PDAcom(), mcman_probePDACard(), mcman_probePS1Card(), mcman_probePS1Card2(), McReadPS1PDACard(), and McWritePS1PDACard().
mcman_sio2transfer
int(* mcman_sio2transfer) (int port, int slot, sio2_transfer_data_t *sio2data) (int port, int slot, sio2_transfer_data_t * sio2data) extern
Definition at line 60 of file main.c.
Referenced by _start(), McGetCardSpec(), mcman_cardchanged(), mcman_eraseblock(), mcman_probePDACard(), mcman_probePS1Card(), mcman_probePS1Card2(), mcman_probePS2Card(), mcman_probePS2Card2(), mcman_readpage(), mcman_resetauth(), McReadPS1PDACard(), McWritePage(), McWritePS1PDACard(), and secrman_mc_command().
mcman_timercount
u32 mcman_timercount static
Definition at line 26 of file mcsio2.c.
Referenced by mcman_probePS1Card(), mcman_probePS1Card2(), McReadPS1PDACard(), and McWritePS1PDACard().
mcman_timerthick
int mcman_timerthick static
Definition at line 27 of file mcsio2.c.
Referenced by mcman_probePS1Card(), mcman_probePS1Card2(), McReadPS1PDACard(), and McWritePS1PDACard().
mcman_wdmabufs
u8 mcman_wdmabufs[0x0b *0x90] static
Definition at line 19 of file mcsio2.c.
Referenced by mcman_initPS2com().
sio2packet_add_func
void(* sio2packet_add_func) (int port, int slot, int cmd, u8 *buf, int pos) (int port, int slot, int cmd, u8 * buf, int pos) static
Definition at line 41 of file mcsio2.c.
Referenced by sio2packet_add().
sio2packet_add_funcs_array
void* sio2packet_add_funcs_array[16] static
Initial value:
= {
    (void *)sio2packet_add_wdma_00,
    (void *)sio2packet_add_wdma_u32,
    (void *)sio2packet_add_wdma_u32,
    (void *)sio2packet_add_wdma_u32,
    (void *)sio2packet_add_wdma_u8,
    (void *)sio2packet_add_do_nothing,
    (void *)sio2packet_add_do_nothing,
    (void *)sio2packet_add_wdma_5a,
    (void *)sio2packet_add_do_nothing,
    (void *)sio2packet_add_pagedata_in,
    (void *)sio2packet_add_pagedata_out,
    (void *)sio2packet_add_do_nothing,
    (void *)sio2packet_add_do_nothing,
    (void *)sio2packet_add_ecc_in,
    (void *)sio2packet_add_ecc_out,
    (void *)sio2packet_add_wdma_u8
}
Definition at line 53 of file mcsio2.c.
Referenced by sio2packet_add().
timer_ID
int timer_ID extern
Definition at line 28 of file main.c.
Referenced by _start(), mcman_probePS1Card(), mcman_probePS1Card2(), McReadPS1PDACard(), and McWritePS1PDACard().