ps2sdk: iop/network/smbman/src/md4.h File Reference
md4.h File Reference
Functions
unsigned char * MD4 (unsigned char *message, int len, unsigned char *cipher)
Function Documentation
MD4()
unsigned char* MD4 (unsigned char * message, int len, unsigned char * cipher)
produce a MD4 message digest from message of len bytes
Definition at line 145 of file md4.c.
 {
         union {
                 unsigned char ucbuff[128];
                 unsigned int uibuff[128/sizeof(unsigned int)];
         } buffer;
         unsigned int b = len * 8;
         engineReset();
         while (len > 64) {
                 memcpy(buffer.ucbuff, message, 64);
                 transform(buffer.ucbuff);
                 message += 64;
                 len -= 64;
         }
         memset(buffer.ucbuff, 0, 128);
         memcpy(buffer.ucbuff, message, len);
         buffer.ucbuff[len] = 0x80;
         if (len < 56) {
                 buffer.uibuff[56/sizeof(unsigned int)] = b;
                 transform(buffer.ucbuff);
         } else {
                 buffer.uibuff[120/sizeof(unsigned int)] = b;
                 transform(buffer.ucbuff);
                 transform(&buffer.ucbuff[64]);
         }
         *((unsigned int *)&cipher[0]) = context[0];
         *((unsigned int *)&cipher[4]) = context[1];
         *((unsigned int *)&cipher[8]) = context[2];
         *((unsigned int *)&cipher[12]) = context[3];
         return (unsigned char *)cipher;
 }
References buffer, context, engineReset(), memcpy(), memset(), and transform().
Referenced by NTLM_Password_Hash().