ps2sdk: iop/usb/usbd/src/mem.c File Reference
mem.c File Reference
#include "usbdpriv.h"
#include "mem.h"
#include "stdio.h"
Functions
HcIsoTD * allocIsoTd (void)
void freeIsoTd (HcIsoTD *argTd)
HcTD * allocTd (void)
void freeTd (HcTD *argTd)
Device * attachChildDevice (Device *parent, u32 portNum)
void freeDevice (Device *dev)
Device * fetchPortElemByNumber (Device *hub, int port)
void addToHcEndpointList (u8 type, HcED *ed)
void removeHcEdFromList (int type, HcED *hcEd)
Endpoint * allocEndpointForDevice (Device *dev, u32 align)
Device * fetchDeviceById (int devId)
Endpoint * fetchEndpointById (int id)
IoRequest * allocIoRequest (void)
void freeIoRequest (IoRequest *req)
Variables
MemoryPool memPool
Detailed Description
USB Driver function prototypes and constants.
Definition in file mem.c.
Function Documentation
addToHcEndpointList()
void addToHcEndpointList (u8 type, HcED * ed)
Definition at line 135 of file mem.c.
{
         ed->next = memPool.hcEdBuf[type].next;
         memPool.hcEdBuf[type].next = ed;
 }
References MemoryPool::hcEdBuf, memPool, and HcED::next.
Referenced by openDeviceEndpoint().
allocEndpointForDevice()
Endpoint* allocEndpointForDevice (Device * dev, u32 align)
Definition at line 153 of file mem.c.
{
         Endpoint *newEp = memPool.freeEpListStart;
         if (!newEp)
                 return NULL;
         if (newEp->next)
                 newEp->next->prev = newEp->prev;
         else
                 memPool.freeEpListEnd = newEp->prev;
         if (newEp->prev)
                 newEp->prev->next = newEp->next;
         else
                 memPool.freeEpListStart = newEp->next;
         newEp->correspDevice = dev;
         newEp->ioReqListStart = newEp->ioReqListEnd = NULL;
         newEp->busyNext = newEp->busyPrev = NULL;
         newEp->inTdQueue = 0;
         newEp->alignFlag = align;
         newEp->next = NULL;
         newEp->prev = dev->endpointListEnd;
         if (dev->endpointListEnd)
                 dev->endpointListEnd->next = newEp;
         else
                 dev->endpointListStart = newEp;
         dev->endpointListEnd = newEp;
         return newEp;
 }
References Endpoint::alignFlag, Endpoint::busyNext, Endpoint::busyPrev, Endpoint::correspDevice, Device::endpointListEnd, Device::endpointListStart, MemoryPool::freeEpListEnd, MemoryPool::freeEpListStart, Endpoint::inTdQueue, Endpoint::ioReqListEnd, Endpoint::ioReqListStart, memPool, Endpoint::next, NULL, and Endpoint::prev.
Referenced by openDeviceEndpoint().
allocIoRequest()
IoRequest* allocIoRequest (void)
Definition at line 205 of file mem.c.
{
         IoRequest *res = memPool.freeIoReqList;
         if (res) {
                 if (res->next)
                         res->next->prev = res->prev;
                 else
                         memPool.freeIoReqListEnd = res->prev;
                 if (res->prev)
                         res->prev->next = res->next;
                 else
                         memPool.freeIoReqList = res->next;
                 res->prev = res->next = NULL;
         } else
                 dbg_printf("ran out of IoReqs\n");
         return res;
 }
References dbg_printf, MemoryPool::freeIoReqList, MemoryPool::freeIoReqListEnd, memPool, IoRequest::next, NULL, and IoRequest::prev.
Referenced by sceUsbdTransferPipe().
allocIsoTd()
HcIsoTD* allocIsoTd (void)
Definition at line 23 of file mem.c.
{
         HcIsoTD *newTd = memPool.freeHcIsoTdList;
         if (newTd) {
                 memPool.freeHcIsoTdList = newTd->next;
                 newTd->next = NULL;
         }
         return newTd;
 }
References MemoryPool::freeHcIsoTdList, memPool, HcIsoTD::next, and NULL.
Referenced by openDeviceEndpoint(), and setupIsocronTransfer().
allocTd()
HcTD* allocTd (void)
Definition at line 45 of file mem.c.
                     {
         HcTD *res = memPool.freeHcTdList;
         if (res) {
                 memPool.freeHcTdList = res->next;
                 res->next = NULL;
         }
         return res;
 }
References MemoryPool::freeHcTdList, memPool, HcTD::next, and NULL.
Referenced by openDeviceEndpoint(), setupBulkTransfer(), and setupControlTransfer().
attachChildDevice()
Device* attachChildDevice (Device * parent, u32 portNum)
Definition at line 67 of file mem.c.
{
         Device *newDev = memPool.freeDeviceListStart;
         if (!newDev) {
                 dbg_printf("Ran out of device handles\n");
                 return NULL;
         }
         if (newDev->next)
                 newDev->next->prev = newDev->prev;
         else
                 memPool.freeDeviceListEnd = newDev->prev;
         if (newDev->prev)
                 newDev->prev->next = newDev->next;
         else
                 memPool.freeDeviceListStart = newDev->next;
         newDev->endpointListEnd = newDev->endpointListStart = NULL;
         newDev->devDriver = NULL;
         newDev->deviceStatus = DEVICE_NOTCONNECTED;
         newDev->resetFlag = 0;
         newDev->childListEnd = newDev->childListStart = NULL;
         newDev->parent = parent;
         newDev->attachedToPortNo = portNum;
         newDev->privDataField = NULL;
         if (parent) {
                 newDev->prev = parent->childListEnd;
                 if (parent->childListEnd)
                         parent->childListEnd->next = newDev;
                 else
                         parent->childListStart = newDev;
                 newDev->next = NULL;
                 parent->childListEnd = newDev;
         } else
                 newDev->next = newDev->prev = NULL;
     return newDev;
 }
References Device::attachedToPortNo, Device::childListEnd, Device::childListStart, dbg_printf, Device::devDriver, DEVICE_NOTCONNECTED, Device::deviceStatus, Device::endpointListEnd, Device::endpointListStart, MemoryPool::freeDeviceListEnd, MemoryPool::freeDeviceListStart, memPool, Device::next, NULL, Device::parent, Device::prev, Device::privDataField, and Device::resetFlag.
Referenced by hubSetupPorts(), and initHcdStructs().
fetchDeviceById()
Device* fetchDeviceById (int devId)
Definition at line 185 of file mem.c.
{
         Device *dev;
         if ((devId > 0) && (devId < usbConfig.maxDevices)) {
                 dev = memPool.deviceTreeBuf + devId;
                 if (dev->parent)
                         return dev;
         }
         return NULL;
 }
References MemoryPool::deviceTreeBuf, UsbdConfig::maxDevices, memPool, NULL, Device::parent, and usbConfig.
Referenced by doGetDeviceStaticDescriptor(), hubDrvConnect(), hubDrvDisconnect(), sceUsbdGetDeviceLocation(), sceUsbdGetPrivateData(), sceUsbdOpenPipe(), sceUsbdOpenPipeAligned(), and sceUsbdSetPrivateData().
fetchEndpointById()
Endpoint* fetchEndpointById (int id)
Definition at line 195 of file mem.c.
{
         Endpoint *res;
         if ((id >= 0) && (id < usbConfig.maxEndpoints)) {
                 res = memPool.endpointBuf + id;
                 if (res->correspDevice)
                         return res;
         }
         return NULL;
 }
References Endpoint::correspDevice, MemoryPool::endpointBuf, UsbdConfig::maxEndpoints, memPool, NULL, and usbConfig.
Referenced by sceUsbdClosePipe(), and sceUsbdTransferPipe().
fetchPortElemByNumber()
Device* fetchPortElemByNumber (Device * hub, int port)
Definition at line 125 of file mem.c.
{
         Device *res = hub->childListStart;
         while (--port > 0) {
                 if (!res)
                         return NULL;
                 res = res->next;
         }
         return res;
 }
References Device::childListStart, Device::next, and NULL.
Referenced by hubGetPortStatusCallback().
freeDevice()
void freeDevice (Device * dev)
Definition at line 105 of file mem.c.
{
         if (!dev)
                 return;
         if ((dev < memPool.deviceTreeBuf) || (dev >= memPool.deviceTreeBuf + usbConfig.maxDevices)) {
                 printf("freeDevice %p: Arg is not part of dev buffer\n", dev);
                 return;
         }
         dev->prev = memPool.freeDeviceListEnd;
         if (memPool.freeDeviceListEnd)
                 memPool.freeDeviceListEnd->next = dev;
         else
                 memPool.freeDeviceListStart = dev;
         dev->next = NULL;
         dev->parent = NULL;
         memPool.freeDeviceListEnd = dev;
 }
References MemoryPool::deviceTreeBuf, MemoryPool::freeDeviceListEnd, MemoryPool::freeDeviceListStart, UsbdConfig::maxDevices, memPool, Device::next, NULL, Device::parent, Device::prev, printf(), and usbConfig.
Referenced by flushPort().
freeIoRequest()
void freeIoRequest (IoRequest * req)
Definition at line 223 of file mem.c.
{
         int num = req - memPool.ioReqBufPtr;
         IoRequest *pos;
         if (req) {
                 if ((num >= 0) && (num < usbConfig.maxIoReqs)) {
                         for (pos = memPool.freeIoReqList; pos != NULL; pos = pos->next)
                                 if (pos == req) {
                                         printf("freeIoRequest %p: already free.\n", req);
                                         return;
                                 }
                         req->prev = memPool.freeIoReqListEnd;
                         if (memPool.freeIoReqListEnd)
                                 memPool.freeIoReqListEnd->next = req;
                         else
                                 memPool.freeIoReqList = req;
                         req->next = NULL;
                         memPool.freeIoReqListEnd = req;
                 }
                 req->busyFlag = 0;
         }
 }
References IoRequest::busyFlag, MemoryPool::freeIoReqList, MemoryPool::freeIoReqListEnd, MemoryPool::ioReqBufPtr, UsbdConfig::maxIoReqs, memPool, IoRequest::next, NULL, pos, IoRequest::prev, printf(), and usbConfig.
Referenced by callbackThreadFunc(), killEndpoint(), processDoneQueue_GenTd(), processDoneQueue_IsoTd(), and sceUsbdTransferPipe().
freeIsoTd()
void freeIsoTd (HcIsoTD * argTd)
Definition at line 32 of file mem.c.
{
         HcIsoTD *pos;
         if (argTd) {
                 for (pos = memPool.freeHcIsoTdList; pos != NULL; pos = pos->next)
                         if (pos == argTd) {
                                 printf("freeIsoTd %p: already free\n", argTd);
                                 return;
                         }
                 argTd->next = memPool.freeHcIsoTdList;
                 memPool.freeHcIsoTdList = argTd;
         }
 }
References MemoryPool::freeHcIsoTdList, memPool, HcIsoTD::next, NULL, pos, and printf().
Referenced by killEndpoint(), and processDoneQueue_IsoTd().
freeTd()
void freeTd (HcTD * argTd)
Definition at line 54 of file mem.c.
{
         HcTD *pos;
         if (argTd) {
                 for (pos = memPool.freeHcTdList; pos != NULL; pos = pos->next)
                         if (pos == argTd) {
                                 printf("FreeTD %p: already free\n", argTd);
                                 return;
                         }
                 argTd->next = memPool.freeHcTdList;
                 memPool.freeHcTdList = argTd;
         }
 }
References MemoryPool::freeHcTdList, memPool, HcTD::next, NULL, pos, and printf().
Referenced by killEndpoint(), processDoneQueue_GenTd(), and setupControlTransfer().
removeHcEdFromList()
void removeHcEdFromList (int type, HcED * hcEd)
Definition at line 140 of file mem.c.
{
         HcED *prev = memPool.hcEdBuf + type;
         HcED *pos  = prev->next;
         while (pos) {
                 if (pos == hcEd) {
                         prev->next = pos->next;
                         return;
                 }
                 prev = pos;
                 pos = pos->next;
         }
 }
References MemoryPool::hcEdBuf, memPool, HcED::next, and pos.
Referenced by removeEndpointFromDevice().
Variable Documentation
memPool
MemoryPool memPool
Definition at line 21 of file mem.c.
Referenced by addTimerCallback(), addToHcEndpointList(), allocEndpointForDevice(), allocIoRequest(), allocIsoTd(), allocTd(), attachChildDevice(), cancelTimerCallback(), checkDelayedResets(), checkTdQueue(), cleanUpFunc(), doGetDeviceLocation(), doRegisterAutoLoader(), doRegisterDriver(), doUnregisterDriver(), enqueueEndpoint(), fetchDeviceById(), fetchEndpointById(), freeDevice(), freeIoRequest(), freeIsoTd(), freeTd(), handleRhsc(), handleTimerList(), hcdProcessIntr(), hubResetDevice(), initHardware(), initHcdStructs(), killEndpoint(), PostIntrEnableFunction(), processDoneQueue_GenTd(), processDoneQueue_IsoTd(), removeEndpointFromQueue(), removeHcEdFromList(), setupBulkTransfer(), setupControlTransfer(), and setupIsocronTransfer().