ps2sdk: common/include/netman.h File Reference
netman.h File Reference
#include <tamtypes.h>
Data Structures
struct NetManNetProtStack
struct NetManEthRuntimeStats
struct NetManEthStatus
struct NetManNetIF
Macros
#define NETMAN_NETIF_NAME_MAX_LEN 4
#define NETMAN_NETIF_FRAME_SIZE 1514
#define NETMAN_FRAME_GROUP_SIZE 8
#define NETMAN_NETIF_ETH_LINK_DISABLE_PAUSE 0x40
#define NETMAN_NETIF_IN_USE 0x80
#define NETMAN_NETIF_ETHERNET 1
#define NETMAN_NETIF_DIALUP 2
#define NETMAN_NETIF_LINK_UP 4
#define NETMAN_NETIF_EVF_UP 0x01
#define NETMAN_NETIF_EVF_DOWN 0x02
#define NETMAN_MAX_NETIF_COUNT 2
#define netman_IMPORTS_start DECLARE_IMPORT_TABLE(netman, 3, 1)
#define netman_IMPORTS_end END_IMPORT_TABLE
#define I_NetManRegisterNetworkStack DECLARE_IMPORT(4, NetManRegisterNetworkStack)
#define I_NetManUnregisterNetworkStack DECLARE_IMPORT(5, NetManUnregisterNetworkStack)
#define I_NetManNetIFXmit DECLARE_IMPORT(6, NetManNetIFXmit)
#define I_NetManIoctl DECLARE_IMPORT(7, NetManIoctl)
#define I_NetManNetProtStackAllocPacket DECLARE_IMPORT(8, NetManNetProtStackAllocRxPacket)
#define I_NetManNetProtStackFreePacket DECLARE_IMPORT(9, NetManNetProtStackFreeRxPacket)
#define I_NetManNetProtStackEnQPacket DECLARE_IMPORT(10, NetManNetProtStackEnQRxPacket)
#define I_NetManRegisterNetIF DECLARE_IMPORT(11, NetManRegisterNetIF)
#define I_NetManUnregisterNetIF DECLARE_IMPORT(12, NetManUnregisterNetIF)
#define I_NetManToggleNetIFLinkState DECLARE_IMPORT(13, NetManToggleNetIFLinkState)
#define I_NetManGetGlobalNetIFLinkState DECLARE_IMPORT(14, NetManGetGlobalNetIFLinkState)
#define I_NetManSetMainIF DECLARE_IMPORT(15, NetManSetMainIF)
#define I_NetManQueryMainIF DECLARE_IMPORT(16, NetManQueryMainIF)
#define I_NetManSetLinkMode DECLARE_IMPORT(17, NetManSetLinkMode)
#define I_NetManTxPacketNext DECLARE_IMPORT(18, NetManTxPacketNext)
#define I_NetManTxPacketDeQ DECLARE_IMPORT(19, NetManTxPacketDeQ)
Enumerations
enum NETMAN_NETIF_ETH_LINK_MODE {
NETMAN_NETIF_ETH_LINK_MODE_AUTO = 0 ,
NETMAN_NETIF_ETH_LINK_MODE_10M_HDX ,
NETMAN_NETIF_ETH_LINK_MODE_10M_FDX ,
NETMAN_NETIF_ETH_LINK_MODE_100M_HDX ,
NETMAN_NETIF_ETH_LINK_MODE_100M_FDX ,
NETMAN_NETIF_ETH_LINK_MODE_COUNT
}
enum NETMAN_NETIF_ETH_LINK_STATE {
NETMAN_NETIF_ETH_LINK_STATE_DOWN = 0 ,
NETMAN_NETIF_ETH_LINK_STATE_UP
}
enum NETMAN_NETIF_IOCTL_CODES {
NETMAN_NETIF_IOCTL_ETH_GET_MAC = 0x1000 ,
NETMAN_NETIF_IOCTL_ETH_GET_LINK_MODE ,
NETMAN_NETIF_IOCTL_ETH_GET_RX_EOVERRUN_CNT ,
NETMAN_NETIF_IOCTL_ETH_GET_RX_EBADLEN_CNT ,
NETMAN_NETIF_IOCTL_ETH_GET_RX_EBADFCS_CNT ,
NETMAN_NETIF_IOCTL_ETH_GET_RX_EBADALIGN_CNT ,
NETMAN_NETIF_IOCTL_ETH_GET_TX_ELOSSCR_CNT ,
NETMAN_NETIF_IOCTL_ETH_GET_TX_EEDEFER_CNT ,
NETMAN_NETIF_IOCTL_ETH_GET_TX_ECOLL_CNT ,
NETMAN_NETIF_IOCTL_ETH_GET_TX_EUNDERRUN_CNT ,
NETMAN_NETIF_IOCTL_ETH_GET_STATUS ,
NETMAN_NETIF_IOCTL_ETH_SET_LINK_MODE ,
NETMAN_NETIF_IOCTL_GET_LINK_STATUS = 0x3000 ,
NETMAN_NETIF_IOCTL_GET_TX_DROPPED_COUNT ,
NETMAN_NETIF_IOCTL_GET_RX_DROPPED_COUNT
}
Functions
int NetManGetGlobalNetIFLinkState (void)
int NetManSetMainIF (const char *name)
int NetManQueryMainIF (char *name)
int NetManRegisterNetworkStack (const struct NetManNetProtStack *stack)
void NetManUnregisterNetworkStack (void)
int NetManIoctl (unsigned int command, void *args, unsigned int args_len, void *output, unsigned int length)
int NetManSetLinkMode (int mode)
void NetManNetIFXmit (void)
void * NetManNetProtStackAllocRxPacket (unsigned int length, void **payload)
void NetManNetProtStackFreeRxPacket (void *packet)
void NetManNetProtStackEnQRxPacket (void *packet)
int NetManTxPacketNext (void **payload)
void NetManTxPacketDeQ (void)
int NetManTxPacketAfter (void **payload)
void NetManNetProtStackReallocRxPacket (void *packet, unsigned int length)
int NetManRegisterNetIF (struct NetManNetIF *NetIF)
void NetManUnregisterNetIF (const char *name)
void NetManToggleNetIFLinkState (int NetIFID, unsigned char state)
Detailed Description
Netman common definitions
Definition in file netman.h.
Macro Definition Documentation
I_NetManGetGlobalNetIFLinkState
#define I_NetManGetGlobalNetIFLinkState DECLARE_IMPORT(14, NetManGetGlobalNetIFLinkState)
Definition at line 188 of file netman.h.
I_NetManIoctl
#define I_NetManIoctl DECLARE_IMPORT(7, NetManIoctl)
Definition at line 179 of file netman.h.
I_NetManNetIFXmit
#define I_NetManNetIFXmit DECLARE_IMPORT(6, NetManNetIFXmit)
Definition at line 178 of file netman.h.
I_NetManNetProtStackAllocPacket
#define I_NetManNetProtStackAllocPacket DECLARE_IMPORT(8, NetManNetProtStackAllocRxPacket)
Definition at line 181 of file netman.h.
I_NetManNetProtStackEnQPacket
#define I_NetManNetProtStackEnQPacket DECLARE_IMPORT(10, NetManNetProtStackEnQRxPacket)
Definition at line 183 of file netman.h.
I_NetManNetProtStackFreePacket
#define I_NetManNetProtStackFreePacket DECLARE_IMPORT(9, NetManNetProtStackFreeRxPacket)
Definition at line 182 of file netman.h.
I_NetManQueryMainIF
#define I_NetManQueryMainIF DECLARE_IMPORT(16, NetManQueryMainIF)
Definition at line 191 of file netman.h.
I_NetManRegisterNetIF
#define I_NetManRegisterNetIF DECLARE_IMPORT(11, NetManRegisterNetIF)
Definition at line 185 of file netman.h.
I_NetManRegisterNetworkStack
#define I_NetManRegisterNetworkStack DECLARE_IMPORT(4, NetManRegisterNetworkStack)
Definition at line 175 of file netman.h.
I_NetManSetLinkMode
#define I_NetManSetLinkMode DECLARE_IMPORT(17, NetManSetLinkMode)
Definition at line 193 of file netman.h.
I_NetManSetMainIF
#define I_NetManSetMainIF DECLARE_IMPORT(15, NetManSetMainIF)
Definition at line 190 of file netman.h.
I_NetManToggleNetIFLinkState
#define I_NetManToggleNetIFLinkState DECLARE_IMPORT(13, NetManToggleNetIFLinkState)
Definition at line 187 of file netman.h.
I_NetManTxPacketDeQ
#define I_NetManTxPacketDeQ DECLARE_IMPORT(19, NetManTxPacketDeQ)
Definition at line 196 of file netman.h.
I_NetManTxPacketNext
#define I_NetManTxPacketNext DECLARE_IMPORT(18, NetManTxPacketNext)
Definition at line 195 of file netman.h.
I_NetManUnregisterNetIF
#define I_NetManUnregisterNetIF DECLARE_IMPORT(12, NetManUnregisterNetIF)
Definition at line 186 of file netman.h.
I_NetManUnregisterNetworkStack
#define I_NetManUnregisterNetworkStack DECLARE_IMPORT(5, NetManUnregisterNetworkStack)
Definition at line 176 of file netman.h.
NETMAN_FRAME_GROUP_SIZE
#define NETMAN_FRAME_GROUP_SIZE 8
Definition at line 14 of file netman.h.
netman_IMPORTS_end
#define netman_IMPORTS_end END_IMPORT_TABLE
Definition at line 173 of file netman.h.
netman_IMPORTS_start
#define netman_IMPORTS_start DECLARE_IMPORT_TABLE(netman, 3, 1)
Definition at line 172 of file netman.h.
NETMAN_MAX_NETIF_COUNT
#define NETMAN_MAX_NETIF_COUNT 2
Definition at line 163 of file netman.h.
NETMAN_NETIF_DIALUP
#define NETMAN_NETIF_DIALUP 2
Set = network IF is a dailup modem.
Definition at line 143 of file netman.h.
NETMAN_NETIF_ETH_LINK_DISABLE_PAUSE
#define NETMAN_NETIF_ETH_LINK_DISABLE_PAUSE 0x40
Flow-control
Definition at line 50 of file netman.h.
NETMAN_NETIF_ETHERNET
#define NETMAN_NETIF_ETHERNET 1
Set = network IF is an Ethernet IF.
Definition at line 141 of file netman.h.
NETMAN_NETIF_EVF_DOWN
#define NETMAN_NETIF_EVF_DOWN 0x02
Definition at line 161 of file netman.h.
NETMAN_NETIF_EVF_UP
#define NETMAN_NETIF_EVF_UP 0x01
Definition at line 160 of file netman.h.
NETMAN_NETIF_FRAME_SIZE
#define NETMAN_NETIF_FRAME_SIZE 1514
Definition at line 13 of file netman.h.
NETMAN_NETIF_IN_USE
#define NETMAN_NETIF_IN_USE 0x80
Set internally by NETMAN. Do not set externally.
Definition at line 139 of file netman.h.
NETMAN_NETIF_LINK_UP
#define NETMAN_NETIF_LINK_UP 4
Set = network IF has a link up status.
Definition at line 145 of file netman.h.
NETMAN_NETIF_NAME_MAX_LEN
#define NETMAN_NETIF_NAME_MAX_LEN 4
Definition at line 12 of file netman.h.
Enumeration Type Documentation
NETMAN_NETIF_ETH_LINK_MODE
enum NETMAN_NETIF_ETH_LINK_MODE
Enumerator
NETMAN_NETIF_ETH_LINK_MODE_AUTO
Auto negotiation cannot be reflected by NETMAN_NETIF_IOCTL_ETH_GET_LINK_MODE.
NETMAN_NETIF_ETH_LINK_MODE_10M_HDX
10Mbit Half-DupleX
NETMAN_NETIF_ETH_LINK_MODE_10M_FDX
10Mbit Full-DupleX
NETMAN_NETIF_ETH_LINK_MODE_100M_HDX
100Mbit Half-DupleX
NETMAN_NETIF_ETH_LINK_MODE_100M_FDX
100Mbit Full-DupleX
NETMAN_NETIF_ETH_LINK_MODE_COUNT
Definition at line 52 of file netman.h.
{
         NETMAN_NETIF_ETH_LINK_MODE_AUTO         = 0,
         NETMAN_NETIF_ETH_LINK_MODE_10M_HDX,
         NETMAN_NETIF_ETH_LINK_MODE_10M_FDX,
         NETMAN_NETIF_ETH_LINK_MODE_100M_HDX,
         NETMAN_NETIF_ETH_LINK_MODE_100M_FDX,
         NETMAN_NETIF_ETH_LINK_MODE_COUNT
 };
NETMAN_NETIF_ETH_LINK_STATE
enum NETMAN_NETIF_ETH_LINK_STATE
Enumerator
NETMAN_NETIF_ETH_LINK_STATE_DOWN
NETMAN_NETIF_ETH_LINK_STATE_UP
Definition at line 67 of file netman.h.
{
         NETMAN_NETIF_ETH_LINK_STATE_DOWN        = 0,
         NETMAN_NETIF_ETH_LINK_STATE_UP
 };
NETMAN_NETIF_IOCTL_CODES
enum NETMAN_NETIF_IOCTL_CODES
Enumerator
NETMAN_NETIF_IOCTL_ETH_GET_MAC
Output = 6 bytes of MAC address.
NETMAN_NETIF_IOCTL_ETH_GET_LINK_MODE
NETMAN_NETIF_IOCTL_ETH_GET_RX_EOVERRUN_CNT
NETMAN_NETIF_IOCTL_ETH_GET_RX_EBADLEN_CNT
NETMAN_NETIF_IOCTL_ETH_GET_RX_EBADFCS_CNT
NETMAN_NETIF_IOCTL_ETH_GET_RX_EBADALIGN_CNT
NETMAN_NETIF_IOCTL_ETH_GET_TX_ELOSSCR_CNT
NETMAN_NETIF_IOCTL_ETH_GET_TX_EEDEFER_CNT
NETMAN_NETIF_IOCTL_ETH_GET_TX_ECOLL_CNT
NETMAN_NETIF_IOCTL_ETH_GET_TX_EUNDERRUN_CNT
NETMAN_NETIF_IOCTL_ETH_GET_STATUS
NETMAN_NETIF_IOCTL_ETH_SET_LINK_MODE
Input = struct NetManIFLinkModeParams. Note: does not wait for the IF to finish. Use NetManSetLinkMode() instead.
NETMAN_NETIF_IOCTL_GET_LINK_STATUS
NETMAN_NETIF_IOCTL_GET_TX_DROPPED_COUNT
NETMAN_NETIF_IOCTL_GET_RX_DROPPED_COUNT
Definition at line 72 of file netman.h.
{
         // Ethernet I/F-only IOCTL codes
         NETMAN_NETIF_IOCTL_ETH_GET_MAC  = 0x1000,
         //Function codes with no input and no output; the result is in the return value.
         NETMAN_NETIF_IOCTL_ETH_GET_LINK_MODE,
         NETMAN_NETIF_IOCTL_ETH_GET_RX_EOVERRUN_CNT,
         NETMAN_NETIF_IOCTL_ETH_GET_RX_EBADLEN_CNT,
         NETMAN_NETIF_IOCTL_ETH_GET_RX_EBADFCS_CNT,
         NETMAN_NETIF_IOCTL_ETH_GET_RX_EBADALIGN_CNT,
         NETMAN_NETIF_IOCTL_ETH_GET_TX_ELOSSCR_CNT,
         NETMAN_NETIF_IOCTL_ETH_GET_TX_EEDEFER_CNT,
         NETMAN_NETIF_IOCTL_ETH_GET_TX_ECOLL_CNT,
         NETMAN_NETIF_IOCTL_ETH_GET_TX_EUNDERRUN_CNT,
         //Returns struct NetManEthStatus
         NETMAN_NETIF_IOCTL_ETH_GET_STATUS,
         NETMAN_NETIF_IOCTL_ETH_SET_LINK_MODE,
         // Dial-up I/F-only IOCTL codes
         // 0x2000
         // Common IOCTL codes
         NETMAN_NETIF_IOCTL_GET_LINK_STATUS      = 0x3000,
         NETMAN_NETIF_IOCTL_GET_TX_DROPPED_COUNT,
         NETMAN_NETIF_IOCTL_GET_RX_DROPPED_COUNT,
 };
Function Documentation
NetManGetGlobalNetIFLinkState()
int NetManGetGlobalNetIFLinkState (void)
Definition at line 72 of file netman.c.
{
         return NIFLinkState;
 }
References NIFLinkState.
NetManIoctl()
int NetManIoctl (unsigned int command, void * args, unsigned int args_len, void * output, unsigned int length)
Definition at line 143 of file netman.c.
{
         int result;
         WaitSema(NetManIOSemaID);
         if(MainNetIF!=NULL){
                 result=MainNetIF->ioctl(command, args, args_len, output, length);
         }
         else result=-1;
         SignalSema(NetManIOSemaID);
         return result;
 }
References NetManNetIF::ioctl, MainNetIF, NetManIOSemaID, NULL, result, SignalSema(), and WaitSema().
Referenced by NETMAN_rpc_handler(), NetManNetIFSetLinkMode(), and SMapIFInit().
NetManNetIFXmit()
void NetManNetIFXmit (void)
Definition at line 138 of file netman.c.
{
         if(MainNetIF != NULL)
                 MainNetIF->xmit();
 }
References MainNetIF, NULL, and NetManNetIF::xmit.
Referenced by HandleRxEvent(), and SMapLowLevelOutput().
NetManNetProtStackAllocRxPacket()
void* NetManNetProtStackAllocRxPacket (unsigned int length, void ** payload)
Definition at line 162 of file netman.c.
{
         return IsInitialized?MainNetProtStack.AllocRxPacket(length, payload):NULL;
 }
References NetManNetProtStack::AllocRxPacket, IsInitialized, MainNetProtStack, and NULL.
Referenced by HandleRxIntr().
NetManNetProtStackEnQRxPacket()
void NetManNetProtStackEnQRxPacket (void * packet)
Definition at line 171 of file netman.c.
{
         if(IsInitialized)
                 MainNetProtStack.EnQRxPacket(packet);
 }
References NetManNetProtStack::EnQRxPacket, IsInitialized, and MainNetProtStack.
Referenced by HandleRxIntr().
NetManNetProtStackFreeRxPacket()
void NetManNetProtStackFreeRxPacket (void * packet)
Definition at line 166 of file netman.c.
{
         if(IsInitialized)
                 MainNetProtStack.FreeRxPacket(packet);
 }
References NetManNetProtStack::FreeRxPacket, IsInitialized, and MainNetProtStack.
NetManNetProtStackReallocRxPacket()
void NetManNetProtStackReallocRxPacket (void * packet, unsigned int length)
NetManQueryMainIF()
int NetManQueryMainIF (char * name)
Definition at line 278 of file netman.c.
{
         int result;
         WaitSema(NetManIOSemaID);
         if(MainNetIF!=NULL && (MainNetIF->flags&NETMAN_NETIF_IN_USE)){
                 strcpy(name, MainNetIF->name);
                 result = 0;
         }else result = -ENXIO;
         SignalSema(NetManIOSemaID);
         return result;
 }
References ENXIO, NetManNetIF::flags, MainNetIF, NetManNetIF::name, NETMAN_NETIF_IN_USE, NetManIOSemaID, NULL, result, SignalSema(), strcpy(), and WaitSema().
Referenced by NETMAN_rpc_handler().
NetManRegisterNetIF()
int NetManRegisterNetIF (struct NetManNetIF * NetIF)
Definition at line 185 of file netman.c.
{
         unsigned int i;
         int result;
         iop_event_t EventFlag;
         WaitSema(NetManIOSemaID);
         for(i=0, result=-ENOMEM; i<NETMAN_MAX_NETIF_COUNT; i++){
                 if(!(NetIFs[i].flags&NETMAN_NETIF_IN_USE)){
                         if(NetIF->init()==0){
                                 EventFlag.attr = 0;
                                 EventFlag.option = 0;
                                 EventFlag.bits = 0;
                                 if((result = NetIF->EventFlagID = CreateEventFlag(&EventFlag)) >= 0){
                                         memcpy(&NetIFs[i], NetIF, sizeof(NetIFs[i]));
                                         NetIFs[i].flags|=NETMAN_NETIF_IN_USE;
                                         result=NetIFs[i].id=((unsigned int)NextNetIFID)<<8|i;
                                         UpdateNetIFStatus();
                                         NextNetIFID++;
                                 }
                         }
                         else result=-EIO;
                         break;
                 }
         }
         SignalSema(NetManIOSemaID);
         return result;
 }
References iop_event_t::attr, iop_event_t::bits, CreateEventFlag(), EIO, ENOMEM, NetManNetIF::EventFlagID, NetManNetIF::flags, NetManNetIF::id, NetManNetIF::init, memcpy(), NetIFs, NETMAN_MAX_NETIF_COUNT, NETMAN_NETIF_IN_USE, NetManIOSemaID, NextNetIFID, iop_event_t::option, result, SignalSema(), UpdateNetIFStatus(), and WaitSema().
Referenced by SetupNetDev().
NetManRegisterNetworkStack()
int NetManRegisterNetworkStack (const struct NetManNetProtStack * stack)
Definition at line 104 of file netman.c.
{
         WaitSema(NetManIOSemaID);
         if(!IsInitialized){
                 memcpy(&MainNetProtStack, stack, sizeof(MainNetProtStack));
                 IsInitialized=1;
                 NetManUpdateStackNIFLinkState();
         }
         SignalSema(NetManIOSemaID);
         return 0;
 }
References IsInitialized, MainNetProtStack, memcpy(), NetManIOSemaID, NetManUpdateStackNIFLinkState(), SignalSema(), and WaitSema().
Referenced by InitLWIPStack(), and NETMAN_rpc_handler().
NetManSetLinkMode()
int NetManSetLinkMode (int mode)
Definition at line 293 of file netman.c.
{
         int result, evfid;
         WaitSema(NetManIOSemaID);
         if(MainNetIF!=NULL){
                 evfid = MainNetIF->EventFlagID;
                 ClearEventFlag(evfid, ~NETMAN_NETIF_EVF_DOWN);
                 result = MainNetIF->ioctl(NETMAN_NETIF_IOCTL_ETH_SET_LINK_MODE, &mode, sizeof(mode), NULL, 0);
         }
         else{
                 evfid = -1;
                 result = -1;
         }
         SignalSema(NetManIOSemaID);
         if(result == 0  && evfid >= 0)
                 WaitEventFlag(evfid, NETMAN_NETIF_EVF_DOWN, WEF_OR, NULL);      //Wait for the IF to go down.
         return result;
 }
References ClearEventFlag(), NetManNetIF::EventFlagID, NetManNetIF::ioctl, MainNetIF, NETMAN_NETIF_EVF_DOWN, NETMAN_NETIF_IOCTL_ETH_SET_LINK_MODE, NetManIOSemaID, NULL, result, SignalSema(), WaitEventFlag(), WaitSema(), and WEF_OR.
Referenced by NETMAN_rpc_handler().
NetManSetMainIF()
int NetManSetMainIF (const char * name)
Definition at line 260 of file netman.c.
{
         int result, i;
         WaitSema(NetManIOSemaID);
         for(i=0,result=-ENXIO; i<NETMAN_MAX_NETIF_COUNT; i++){
                 if((NetIFs[i].flags&NETMAN_NETIF_IN_USE) && strcmp(name, NetIFs[i].name)==0){
                         MainNetIF=&NetIFs[i];
                         result = 0;
                         break;
                 }
         }
         SignalSema(NetManIOSemaID);
         return result;
 }
References ENXIO, NetManNetIF::flags, MainNetIF, NetManNetIF::name, NetIFs, NETMAN_MAX_NETIF_COUNT, NETMAN_NETIF_IN_USE, NetManIOSemaID, result, SignalSema(), strcmp(), and WaitSema().
Referenced by NETMAN_rpc_handler().
NetManToggleNetIFLinkState()
void NetManToggleNetIFLinkState (int NetIFID, unsigned char state)
Definition at line 235 of file netman.c.
{
         struct NetManNetIF *pNetIF;
         WaitSema(NetManIOSemaID);
         if((NetIFID&0xFF)<NETMAN_MAX_NETIF_COUNT && NetIFID==NetIFs[NetIFID&0xFF].id && (NetIFs[NetIFID&0xFF].flags&NETMAN_NETIF_IN_USE)){
                 pNetIF = &NetIFs[NetIFID&0xFF];
                 ClearEventFlag(pNetIF->EventFlagID, ~(NETMAN_NETIF_EVF_UP|NETMAN_NETIF_EVF_DOWN));
                 if(state){
                         pNetIF->flags|=NETMAN_NETIF_LINK_UP;
                         SetEventFlag(pNetIF->EventFlagID, NETMAN_NETIF_EVF_UP);
                 }
                 else{
                         pNetIF->flags&=~NETMAN_NETIF_LINK_UP;
                         SetEventFlag(pNetIF->EventFlagID, NETMAN_NETIF_EVF_DOWN);
                 }
                 UpdateNetIFStatus();
         }
         SignalSema(NetManIOSemaID);
 }
References ClearEventFlag(), NetManNetIF::EventFlagID, NetManNetIF::flags, NetIFs, NETMAN_MAX_NETIF_COUNT, NETMAN_NETIF_EVF_DOWN, NETMAN_NETIF_EVF_UP, NETMAN_NETIF_IN_USE, NETMAN_NETIF_LINK_UP, NetManIOSemaID, SetEventFlag(), SignalSema(), state, UpdateNetIFStatus(), and WaitSema().
Referenced by CheckLinkStatus(), and IntrHandlerThread().
NetManTxPacketAfter()
int NetManTxPacketAfter (void ** payload)
NetManTxPacketDeQ()
void NetManTxPacketDeQ (void)
Definition at line 180 of file netman.c.
{
         if(IsInitialized)
                 MainNetProtStack.DeQTxPacket();
 }
References NetManNetProtStack::DeQTxPacket, IsInitialized, and MainNetProtStack.
Referenced by ClearPacketQueue(), and HandleTxReqs().
NetManTxPacketNext()
int NetManTxPacketNext (void ** payload)
Definition at line 176 of file netman.c.
{
         return IsInitialized?MainNetProtStack.NextTxPacket(payload):0;
 }
References IsInitialized, MainNetProtStack, and NetManNetProtStack::NextTxPacket.
Referenced by ClearPacketQueue(), and HandleTxReqs().
NetManUnregisterNetIF()
void NetManUnregisterNetIF (const char * name)
Definition at line 217 of file netman.c.
{
         unsigned int i;
         WaitSema(NetManIOSemaID);
         for(i=0; i<NETMAN_MAX_NETIF_COUNT; i++){
                 if((NetIFs[i].flags&NETMAN_NETIF_IN_USE) && strcmp(name, NetIFs[i].name)==0){
                         NetIFs[i].flags=0;
                         NetIFs[i].deinit();
                         DeleteEventFlag(NetIFs[i].EventFlagID);
                         UpdateNetIFStatus();
                         break;
                 }
         }
         SignalSema(NetManIOSemaID);
 }
References NetManNetIF::deinit, DeleteEventFlag(), NetManNetIF::flags, irx_export_table::name, NetIFs, NETMAN_MAX_NETIF_COUNT, NETMAN_NETIF_IN_USE, NetManIOSemaID, SignalSema(), strcmp(), UpdateNetIFStatus(), and WaitSema().
NetManUnregisterNetworkStack()
void NetManUnregisterNetworkStack (void)
Definition at line 119 of file netman.c.
{
         unsigned int i;
         WaitSema(NetManIOSemaID);
         for(i=0; i<NETMAN_MAX_NETIF_COUNT; i++){
                 if(NetIFs[i].flags&NETMAN_NETIF_IN_USE){
                         NetIFs[i].flags=0;
                         NetIFs[i].deinit();
                 }
         }
         UpdateNetIFStatus();
         memset(&MainNetProtStack, 0, sizeof(MainNetProtStack));
         IsInitialized=0;
         SignalSema(NetManIOSemaID);
 }
References NetManNetIF::deinit, NetManNetIF::flags, IsInitialized, MainNetProtStack, memset(), NetIFs, NETMAN_MAX_NETIF_COUNT, NETMAN_NETIF_IN_USE, NetManIOSemaID, SignalSema(), UpdateNetIFStatus(), and WaitSema().
Referenced by unregisterEENetworkStack().