ps2sdk: iop/network/netman/src/netman.c File Reference
netman.c File Reference
#include <errno.h>
#include <intrman.h>
#include <irx.h>
#include <loadcore.h>
#include <sysclib.h>
#include <sysmem.h>
#include <sifman.h>
#include <thevent.h>
#include <thsemap.h>
#include <netman.h>
#include <netman_rpc.h>
#include "rpc_client.h"
#include "rpc_server.h"
#include "internal.h"
Functions
IRX_ID ("Network_Manager", 2, 1)
int _start (int argc, char *argv[])
void * malloc (int size)
void free (void *buffer)
void NetManToggleGlobalNetIFLinkState (unsigned char state)
int NetManGetGlobalNetIFLinkState (void)
void NetManUpdateStackNIFLinkState (void)
static void UpdateNetIFStatus (void)
int NetManRegisterNetworkStack (const struct NetManNetProtStack *stack)
void NetManUnregisterNetworkStack (void)
void NetManNetIFXmit (void)
int NetManIoctl (unsigned int command, void *args, unsigned int args_len, void *output, unsigned int length)
int NetManNetIFSetLinkMode (int mode)
void * NetManNetProtStackAllocRxPacket (unsigned int length, void **payload)
void NetManNetProtStackFreeRxPacket (void *packet)
void NetManNetProtStackEnQRxPacket (void *packet)
int NetManTxPacketNext (void **payload)
void NetManTxPacketDeQ (void)
int NetManRegisterNetIF (struct NetManNetIF *NetIF)
void NetManUnregisterNetIF (const char *name)
void NetManToggleNetIFLinkState (int NetIFID, unsigned char state)
int NetManSetMainIF (const char *name)
int NetManQueryMainIF (char *name)
int NetManSetLinkMode (int mode)
Variables
static struct NetManNetProtStack MainNetProtStack
static struct NetManNetIF NetIFs [NETMAN_MAX_NETIF_COUNT]
static struct NetManNetIF * MainNetIF =NULL
static unsigned char IsInitialized =0
static char NIFLinkState =0
static unsigned char NextNetIFID =0
static int NetManIOSemaID
struct irx_export_table _exp_netman
Function Documentation
_start()
int _start (int argc, char * argv[])
Definition at line 29 of file netman.c.
{
         iop_sema_t sema;
         if(RegisterLibraryEntries(&_exp_netman) == 0){
                 sema.attr = 0;
                 sema.option = 0;
                 sema.initial = 1;
                 sema.max = 1;
                 NetManIOSemaID = CreateSema(&sema);
                 NetmanInitRPCServer();
                 return MODULE_RESIDENT_END;
         }
         return MODULE_NO_RESIDENT_END;
 }
References _exp_netman, iop_sema_t::attr, CreateSema(), iop_sema_t::initial, iop_sema_t::max, MODULE_NO_RESIDENT_END, MODULE_RESIDENT_END, NetmanInitRPCServer(), NetManIOSemaID, iop_sema_t::option, and RegisterLibraryEntries().
free()
void free (void * buffer)
Definition at line 58 of file netman.c.
{
         int OldState;
         CpuSuspendIntr(&OldState);
         FreeSysMemory(buffer);
         CpuResumeIntr(OldState);
 }
References buffer, CpuResumeIntr(), CpuSuspendIntr(), and FreeSysMemory().
IRX_ID()
IRX_ID ("Network_Manager" , 2 , 1)
malloc()
void* malloc (int size)
Definition at line 47 of file netman.c.
                       {
         int OldState;
         void *result;
         CpuSuspendIntr(&OldState);
         result = AllocSysMemory(ALLOC_FIRST, size, NULL);
         CpuResumeIntr(OldState);
         return result;
 }
References ALLOC_FIRST, AllocSysMemory(), CpuResumeIntr(), CpuSuspendIntr(), NULL, and result.
NetManGetGlobalNetIFLinkState()
int NetManGetGlobalNetIFLinkState (void)
Definition at line 72 of file netman.c.
{
         return NIFLinkState;
 }
References NIFLinkState.
NetManIoctl()
int NetManIoctl (unsigned int command, void * args, unsigned int args_len, void * output, unsigned int length)
Definition at line 143 of file netman.c.
{
         int result;
         WaitSema(NetManIOSemaID);
         if(MainNetIF!=NULL){
                 result=MainNetIF->ioctl(command, args, args_len, output, length);
         }
         else result=-1;
         SignalSema(NetManIOSemaID);
         return result;
 }
References NetManNetIF::ioctl, MainNetIF, NetManIOSemaID, NULL, result, SignalSema(), and WaitSema().
Referenced by NETMAN_rpc_handler(), NetManNetIFSetLinkMode(), and SMapIFInit().
NetManNetIFSetLinkMode()
int NetManNetIFSetLinkMode (int mode)
Definition at line 158 of file netman.c.
{
         return NetManIoctl(NETMAN_NETIF_IOCTL_ETH_SET_LINK_MODE, &mode, sizeof(mode), NULL, 0);
 }
References irx_export_table::mode, NETMAN_NETIF_IOCTL_ETH_SET_LINK_MODE, NetManIoctl(), and NULL.
NetManNetIFXmit()
void NetManNetIFXmit (void)
Definition at line 138 of file netman.c.
{
         if(MainNetIF != NULL)
                 MainNetIF->xmit();
 }
References MainNetIF, NULL, and NetManNetIF::xmit.
Referenced by HandleRxEvent(), and SMapLowLevelOutput().
NetManNetProtStackAllocRxPacket()
void* NetManNetProtStackAllocRxPacket (unsigned int length, void ** payload)
Definition at line 162 of file netman.c.
{
         return IsInitialized?MainNetProtStack.AllocRxPacket(length, payload):NULL;
 }
References NetManNetProtStack::AllocRxPacket, IsInitialized, MainNetProtStack, and NULL.
Referenced by HandleRxIntr().
NetManNetProtStackEnQRxPacket()
void NetManNetProtStackEnQRxPacket (void * packet)
Definition at line 171 of file netman.c.
{
         if(IsInitialized)
                 MainNetProtStack.EnQRxPacket(packet);
 }
References NetManNetProtStack::EnQRxPacket, IsInitialized, and MainNetProtStack.
Referenced by HandleRxIntr().
NetManNetProtStackFreeRxPacket()
void NetManNetProtStackFreeRxPacket (void * packet)
Definition at line 166 of file netman.c.
{
         if(IsInitialized)
                 MainNetProtStack.FreeRxPacket(packet);
 }
References NetManNetProtStack::FreeRxPacket, IsInitialized, and MainNetProtStack.
NetManQueryMainIF()
int NetManQueryMainIF (char * name)
Definition at line 278 of file netman.c.
{
         int result;
         WaitSema(NetManIOSemaID);
         if(MainNetIF!=NULL && (MainNetIF->flags&NETMAN_NETIF_IN_USE)){
                 strcpy(name, MainNetIF->name);
                 result = 0;
         }else result = -ENXIO;
         SignalSema(NetManIOSemaID);
         return result;
 }
References ENXIO, NetManNetIF::flags, MainNetIF, NetManNetIF::name, NETMAN_NETIF_IN_USE, NetManIOSemaID, NULL, result, SignalSema(), strcpy(), and WaitSema().
Referenced by NETMAN_rpc_handler().
NetManRegisterNetIF()
int NetManRegisterNetIF (struct NetManNetIF * NetIF)
Definition at line 185 of file netman.c.
{
         unsigned int i;
         int result;
         iop_event_t EventFlag;
         WaitSema(NetManIOSemaID);
         for(i=0, result=-ENOMEM; i<NETMAN_MAX_NETIF_COUNT; i++){
                 if(!(NetIFs[i].flags&NETMAN_NETIF_IN_USE)){
                         if(NetIF->init()==0){
                                 EventFlag.attr = 0;
                                 EventFlag.option = 0;
                                 EventFlag.bits = 0;
                                 if((result = NetIF->EventFlagID = CreateEventFlag(&EventFlag)) >= 0){
                                         memcpy(&NetIFs[i], NetIF, sizeof(NetIFs[i]));
                                         NetIFs[i].flags|=NETMAN_NETIF_IN_USE;
                                         result=NetIFs[i].id=((unsigned int)NextNetIFID)<<8|i;
                                         UpdateNetIFStatus();
                                         NextNetIFID++;
                                 }
                         }
                         else result=-EIO;
                         break;
                 }
         }
         SignalSema(NetManIOSemaID);
         return result;
 }
References iop_event_t::attr, iop_event_t::bits, CreateEventFlag(), EIO, ENOMEM, NetManNetIF::EventFlagID, NetManNetIF::flags, NetManNetIF::id, NetManNetIF::init, memcpy(), NetIFs, NETMAN_MAX_NETIF_COUNT, NETMAN_NETIF_IN_USE, NetManIOSemaID, NextNetIFID, iop_event_t::option, result, SignalSema(), UpdateNetIFStatus(), and WaitSema().
Referenced by SetupNetDev().
NetManRegisterNetworkStack()
int NetManRegisterNetworkStack (const struct NetManNetProtStack * stack)
Definition at line 104 of file netman.c.
{
         WaitSema(NetManIOSemaID);
         if(!IsInitialized){
                 memcpy(&MainNetProtStack, stack, sizeof(MainNetProtStack));
                 IsInitialized=1;
                 NetManUpdateStackNIFLinkState();
         }
         SignalSema(NetManIOSemaID);
         return 0;
 }
References IsInitialized, MainNetProtStack, memcpy(), NetManIOSemaID, NetManUpdateStackNIFLinkState(), SignalSema(), and WaitSema().
Referenced by InitLWIPStack(), and NETMAN_rpc_handler().
NetManSetLinkMode()
int NetManSetLinkMode (int mode)
Definition at line 293 of file netman.c.
{
         int result, evfid;
         WaitSema(NetManIOSemaID);
         if(MainNetIF!=NULL){
                 evfid = MainNetIF->EventFlagID;
                 ClearEventFlag(evfid, ~NETMAN_NETIF_EVF_DOWN);
                 result = MainNetIF->ioctl(NETMAN_NETIF_IOCTL_ETH_SET_LINK_MODE, &mode, sizeof(mode), NULL, 0);
         }
         else{
                 evfid = -1;
                 result = -1;
         }
         SignalSema(NetManIOSemaID);
         if(result == 0  && evfid >= 0)
                 WaitEventFlag(evfid, NETMAN_NETIF_EVF_DOWN, WEF_OR, NULL);      //Wait for the IF to go down.
         return result;
 }
References ClearEventFlag(), NetManNetIF::EventFlagID, NetManNetIF::ioctl, MainNetIF, NETMAN_NETIF_EVF_DOWN, NETMAN_NETIF_IOCTL_ETH_SET_LINK_MODE, NetManIOSemaID, NULL, result, SignalSema(), WaitEventFlag(), WaitSema(), and WEF_OR.
Referenced by NETMAN_rpc_handler().
NetManSetMainIF()
int NetManSetMainIF (const char * name)
Definition at line 260 of file netman.c.
{
         int result, i;
         WaitSema(NetManIOSemaID);
         for(i=0,result=-ENXIO; i<NETMAN_MAX_NETIF_COUNT; i++){
                 if((NetIFs[i].flags&NETMAN_NETIF_IN_USE) && strcmp(name, NetIFs[i].name)==0){
                         MainNetIF=&NetIFs[i];
                         result = 0;
                         break;
                 }
         }
         SignalSema(NetManIOSemaID);
         return result;
 }
References ENXIO, NetManNetIF::flags, MainNetIF, NetManNetIF::name, NetIFs, NETMAN_MAX_NETIF_COUNT, NETMAN_NETIF_IN_USE, NetManIOSemaID, result, SignalSema(), strcmp(), and WaitSema().
Referenced by NETMAN_rpc_handler().
NetManToggleGlobalNetIFLinkState()
void NetManToggleGlobalNetIFLinkState (unsigned char state)
Definition at line 66 of file netman.c.
{
         NIFLinkState = state;
         NetManUpdateStackNIFLinkState();
 }
References NetManUpdateStackNIFLinkState(), NIFLinkState, and state.
Referenced by UpdateNetIFStatus().
NetManToggleNetIFLinkState()
void NetManToggleNetIFLinkState (int NetIFID, unsigned char state)
Definition at line 235 of file netman.c.
{
         struct NetManNetIF *pNetIF;
         WaitSema(NetManIOSemaID);
         if((NetIFID&0xFF)<NETMAN_MAX_NETIF_COUNT && NetIFID==NetIFs[NetIFID&0xFF].id && (NetIFs[NetIFID&0xFF].flags&NETMAN_NETIF_IN_USE)){
                 pNetIF = &NetIFs[NetIFID&0xFF];
                 ClearEventFlag(pNetIF->EventFlagID, ~(NETMAN_NETIF_EVF_UP|NETMAN_NETIF_EVF_DOWN));
                 if(state){
                         pNetIF->flags|=NETMAN_NETIF_LINK_UP;
                         SetEventFlag(pNetIF->EventFlagID, NETMAN_NETIF_EVF_UP);
                 }
                 else{
                         pNetIF->flags&=~NETMAN_NETIF_LINK_UP;
                         SetEventFlag(pNetIF->EventFlagID, NETMAN_NETIF_EVF_DOWN);
                 }
                 UpdateNetIFStatus();
         }
         SignalSema(NetManIOSemaID);
 }
References ClearEventFlag(), NetManNetIF::EventFlagID, NetManNetIF::flags, NetIFs, NETMAN_MAX_NETIF_COUNT, NETMAN_NETIF_EVF_DOWN, NETMAN_NETIF_EVF_UP, NETMAN_NETIF_IN_USE, NETMAN_NETIF_LINK_UP, NetManIOSemaID, SetEventFlag(), SignalSema(), state, UpdateNetIFStatus(), and WaitSema().
Referenced by CheckLinkStatus(), and IntrHandlerThread().
NetManTxPacketDeQ()
void NetManTxPacketDeQ (void)
Definition at line 180 of file netman.c.
{
         if(IsInitialized)
                 MainNetProtStack.DeQTxPacket();
 }
References NetManNetProtStack::DeQTxPacket, IsInitialized, and MainNetProtStack.
Referenced by ClearPacketQueue(), and HandleTxReqs().
NetManTxPacketNext()
int NetManTxPacketNext (void ** payload)
Definition at line 176 of file netman.c.
{
         return IsInitialized?MainNetProtStack.NextTxPacket(payload):0;
 }
References IsInitialized, MainNetProtStack, and NetManNetProtStack::NextTxPacket.
Referenced by ClearPacketQueue(), and HandleTxReqs().
NetManUnregisterNetIF()
void NetManUnregisterNetIF (const char * name)
Definition at line 217 of file netman.c.
{
         unsigned int i;
         WaitSema(NetManIOSemaID);
         for(i=0; i<NETMAN_MAX_NETIF_COUNT; i++){
                 if((NetIFs[i].flags&NETMAN_NETIF_IN_USE) && strcmp(name, NetIFs[i].name)==0){
                         NetIFs[i].flags=0;
                         NetIFs[i].deinit();
                         DeleteEventFlag(NetIFs[i].EventFlagID);
                         UpdateNetIFStatus();
                         break;
                 }
         }
         SignalSema(NetManIOSemaID);
 }
References NetManNetIF::deinit, DeleteEventFlag(), NetManNetIF::flags, irx_export_table::name, NetIFs, NETMAN_MAX_NETIF_COUNT, NETMAN_NETIF_IN_USE, NetManIOSemaID, SignalSema(), strcmp(), UpdateNetIFStatus(), and WaitSema().
NetManUnregisterNetworkStack()
void NetManUnregisterNetworkStack (void)
Definition at line 119 of file netman.c.
{
         unsigned int i;
         WaitSema(NetManIOSemaID);
         for(i=0; i<NETMAN_MAX_NETIF_COUNT; i++){
                 if(NetIFs[i].flags&NETMAN_NETIF_IN_USE){
                         NetIFs[i].flags=0;
                         NetIFs[i].deinit();
                 }
         }
         UpdateNetIFStatus();
         memset(&MainNetProtStack, 0, sizeof(MainNetProtStack));
         IsInitialized=0;
         SignalSema(NetManIOSemaID);
 }
References NetManNetIF::deinit, NetManNetIF::flags, IsInitialized, MainNetProtStack, memset(), NetIFs, NETMAN_MAX_NETIF_COUNT, NETMAN_NETIF_IN_USE, NetManIOSemaID, SignalSema(), UpdateNetIFStatus(), and WaitSema().
Referenced by unregisterEENetworkStack().
NetManUpdateStackNIFLinkState()
void NetManUpdateStackNIFLinkState (void)
Definition at line 76 of file netman.c.
{
         if(IsInitialized){
                 if(NIFLinkState){
                         MainNetProtStack.LinkStateUp();
                 }
                 else{
                         MainNetProtStack.LinkStateDown();
                 }
         }
 }
References IsInitialized, NetManNetProtStack::LinkStateDown, NetManNetProtStack::LinkStateUp, MainNetProtStack, and NIFLinkState.
Referenced by NetManRegisterNetworkStack(), and NetManToggleGlobalNetIFLinkState().
UpdateNetIFStatus()
static void UpdateNetIFStatus (void) static
Definition at line 87 of file netman.c.
{
         unsigned char i;
         if(!(MainNetIF->flags&NETMAN_NETIF_IN_USE)) MainNetIF = NULL;
         if(MainNetIF == NULL){
                 for(i=0; i<NETMAN_MAX_NETIF_COUNT; i++){
                         if(NetIFs[i].flags&NETMAN_NETIF_IN_USE){
                                 MainNetIF=&NetIFs[i];
                                 break;
                         }
                 }
         }
         NetManToggleGlobalNetIFLinkState((MainNetIF!=NULL && (MainNetIF->flags&NETMAN_NETIF_LINK_UP)) ? 1 : 0);
 }
References NetManNetIF::flags, MainNetIF, NetIFs, NETMAN_MAX_NETIF_COUNT, NETMAN_NETIF_IN_USE, NETMAN_NETIF_LINK_UP, NetManToggleGlobalNetIFLinkState(), and NULL.
Referenced by NetManRegisterNetIF(), NetManToggleNetIFLinkState(), NetManUnregisterNetIF(), and NetManUnregisterNetworkStack().
Variable Documentation
_exp_netman
struct irx_export_table _exp_netman extern
Referenced by _start().
IsInitialized
unsigned char IsInitialized =0 static
Definition at line 20 of file netman.c.
Referenced by NetManNetProtStackAllocRxPacket(), NetManNetProtStackEnQRxPacket(), NetManNetProtStackFreeRxPacket(), NetManRegisterNetworkStack(), NetManTxPacketDeQ(), NetManTxPacketNext(), NetManUnregisterNetworkStack(), and NetManUpdateStackNIFLinkState().
MainNetIF
struct NetManNetIF* MainNetIF =NULL static
Definition at line 19 of file netman.c.
Referenced by NetManIoctl(), NetManNetIFXmit(), NetManQueryMainIF(), NetManSetLinkMode(), NetManSetMainIF(), and UpdateNetIFStatus().
MainNetProtStack
struct NetManNetProtStack MainNetProtStack static
Definition at line 1 of file netman.c.
Referenced by NetManNetProtStackAllocRxPacket(), NetManNetProtStackEnQRxPacket(), NetManNetProtStackFreeRxPacket(), NetManRegisterNetworkStack(), NetManTxPacketDeQ(), NetManTxPacketNext(), NetManUnregisterNetworkStack(), and NetManUpdateStackNIFLinkState().
NetIFs
struct NetManNetIF NetIFs[NETMAN_MAX_NETIF_COUNT] static
Definition at line 1 of file netman.c.
Referenced by NetManRegisterNetIF(), NetManSetMainIF(), NetManToggleNetIFLinkState(), NetManUnregisterNetIF(), NetManUnregisterNetworkStack(), and UpdateNetIFStatus().
NetManIOSemaID
int NetManIOSemaID static
Definition at line 23 of file netman.c.
Referenced by _start(), NetManIoctl(), NetManQueryMainIF(), NetManRegisterNetIF(), NetManRegisterNetworkStack(), NetManSetLinkMode(), NetManSetMainIF(), NetManToggleNetIFLinkState(), NetManUnregisterNetIF(), and NetManUnregisterNetworkStack().
NextNetIFID
unsigned char NextNetIFID =0 static
Definition at line 22 of file netman.c.
Referenced by NetManRegisterNetIF().
NIFLinkState
char NIFLinkState =0 static
Definition at line 21 of file netman.c.
Referenced by NetManGetGlobalNetIFLinkState(), NetManToggleGlobalNetIFLinkState(), and NetManUpdateStackNIFLinkState().