ps2sdk: iop/network/netman/src/include/rpc_client.h File Reference
rpc_client.h File Reference
Functions
int NetManInitRPCClient (void)
void NetManDeinitRPCClient (void)
void NetManRpcToggleGlobalNetIFLinkState (int state)
void * NetManRpcNetProtStackAllocRxPacket (unsigned int length, void **payload)
void NetManRpcNetProtStackFreeRxPacket (void *packet)
void NetManRpcProtStackEnQRxPacket (void *packet)
Function Documentation
NetManDeinitRPCClient()
void NetManDeinitRPCClient (void)
Definition at line 84 of file rpc_client.c.
 {
         if(FrameBuffer != NULL)
         {
                 free(FrameBuffer);
                 FrameBuffer = NULL;
         }
         if(FrameBufferStatus != NULL)
         {
                 free(FrameBufferStatus);
                 FrameBufferStatus = NULL;
         }
         if(NetManIOSemaID >= 0)
         {
                 DeleteSema(NetManIOSemaID);
                 NetManIOSemaID = -1;
         }
         memset(&EEClient, 0, sizeof(EEClient));
 }
References DeleteSema(), EEClient, FrameBuffer, FrameBufferStatus, free, memset(), NetManIOSemaID, and NULL.
Referenced by NETMAN_rpc_handler().
NetManInitRPCClient()
int NetManInitRPCClient (void)
Definition at line 45 of file rpc_client.c.
 {
         static const char NetManID[] = "NetMan";
         iop_sema_t sema;
         int result, i;
         if(FrameBuffer == NULL) FrameBuffer = malloc(NETMAN_RPC_BLOCK_SIZE * NETMAN_MAX_FRAME_SIZE);
         if(FrameBufferStatus == NULL) FrameBufferStatus = malloc(NETMAN_RPC_BLOCK_SIZE * sizeof(struct NetManBD));
         if(FrameBuffer != NULL && FrameBufferStatus != NULL)
         {
                 memset(FrameBuffer, 0, NETMAN_RPC_BLOCK_SIZE * NETMAN_MAX_FRAME_SIZE);
                 memset(FrameBufferStatus, 0, NETMAN_RPC_BLOCK_SIZE * sizeof(struct NetManBD));
                 EEFrameBufferWrPtr = 0;
                 NumFramesInQueue = 0;
                 for(i = 0; i < NETMAN_RPC_BLOCK_SIZE; i++)      //Mark all descriptors as "in-use", until the EE-side allocates buffers.
                         FrameBufferStatus[i].length = USHRT_MAX;
                 while((result=sceSifBindRpc(&EEClient, NETMAN_RPC_NUMBER, 0))<0 || EEClient.server==NULL) DelayThread(500);
                 if((result=sceSifCallRpc(&EEClient, NETMAN_EE_RPC_FUNC_INIT, 0, &FrameBufferStatus, 4, &SifRpcRxBuffer, sizeof(struct NetManEEInitResult), NULL, NULL))>=0)
                 {
                         if((result=SifRpcRxBuffer.EEInitResult.result) == 0)
{
                                 EEFrameBufferStatus = SifRpcRxBuffer.EEInitResult.FrameBufferStatus;
                                 sema.attr = 0;
                                 sema.option = (u32)NetManID;
                                 sema.initial = 1;
                                 sema.max = 1;
                                 NetManIOSemaID = CreateSema(&sema);
                         }
                 }
         }else result = -ENOMEM;
         return result;
 }
References iop_sema_t::attr, CreateSema(), DelayThread(), EEClient, EEFrameBufferStatus, EEFrameBufferWrPtr, ENOMEM, FrameBuffer, FrameBufferStatus, iop_sema_t::initial, NetManBD::length, malloc, iop_sema_t::max, memset(), NETMAN_EE_RPC_FUNC_INIT, NETMAN_MAX_FRAME_SIZE, NETMAN_RPC_BLOCK_SIZE, NETMAN_RPC_NUMBER, NetManIOSemaID, NULL, NumFramesInQueue, iop_sema_t::option, result, sceSifBindRpc(), sceSifCallRpc(), SifRpcClientData_t::server, SifRpcRxBuffer, and USHRT_MAX.
Referenced by NETMAN_rpc_handler().
NetManRpcNetProtStackAllocRxPacket()
void* NetManRpcNetProtStackAllocRxPacket (unsigned int length, void ** payload)
Definition at line 114 of file rpc_client.c.
 {
         struct NetManPacketBuffer *result;
         volatile const struct NetManBD *bd = &FrameBufferStatus[EEFrameBufferWrPtr];
         //Wait for a free spot to appear in the ring buffer.
         while(bd->length != 0) { }
         //Allocation of PBUF descriptors is tied with the allocation of frame slots in the ring buffer by EnQ.
         result = &pbufs[EEFrameBufferWrPtr];
         result->handle = (void*)bd;
         result->payload = &FrameBuffer[EEFrameBufferWrPtr * NETMAN_MAX_FRAME_SIZE];
         result->length = length;
         //The write pointer is not incremented here because the interface driver might discard the frame and free this allocated buffer.
         *payload = result->payload;
         return result;
 }
References EEFrameBufferWrPtr, FrameBuffer, FrameBufferStatus, NetManBD::length, NETMAN_MAX_FRAME_SIZE, NetManBD::payload, pbufs, and result.
Referenced by AllocRxPacket().
NetManRpcNetProtStackFreeRxPacket()
void NetManRpcNetProtStackFreeRxPacket (void * packet)
Definition at line 135 of file rpc_client.c.
 {
         ((struct NetManPacketBuffer*)packet)->handle = NULL;
 }
References NULL.
Referenced by FreeRxPacket().
NetManRpcProtStackEnQRxPacket()
void NetManRpcProtStackEnQRxPacket (void * packet)
Definition at line 227 of file rpc_client.c.
 {
         EnQFrame(((struct NetManPacketBuffer*)packet)->payload, ((struct NetManPacketBuffer*)packet)->length);
 }
References EnQFrame(), NetManBD::length, NetManBD::packet, and NetManBD::payload.
Referenced by EnQRxPacket().
NetManRpcToggleGlobalNetIFLinkState()
void NetManRpcToggleGlobalNetIFLinkState (int state)
Definition at line 105 of file rpc_client.c.
 {
         WaitSema(NetManIOSemaID);
         SifRpcTxBuffer.state=state;
         sceSifCallRpc(&EEClient, NETMAN_EE_RPC_FUNC_HANDLE_LINK_STATUS_CHANGE, 0, &SifRpcTxBuffer, sizeof(s32), NULL, 0, NULL, NULL);
         SignalSema(NetManIOSemaID);
 }
References EEClient, NETMAN_EE_RPC_FUNC_HANDLE_LINK_STATUS_CHANGE, NetManIOSemaID, NULL, sceSifCallRpc(), SifRpcTxBuffer, SignalSema(), state, and WaitSema().
Referenced by LinkStateDown(), and LinkStateUp().