ps2sdk: iop/network/netman/src/include/rpc_server.h File Reference
rpc_server.h File Reference
Functions
int NetmanInitRPCServer (void)
void NetmanDeinitRPCClient (void)
Function Documentation
NetmanDeinitRPCClient()
void NetmanDeinitRPCClient (void)
NetmanInitRPCServer()
int NetmanInitRPCServer (void)
Definition at line 227 of file rpc_server.c.
 {
         iop_thread_t ThreadData;
         if(!IsInitialized)
         {
                 ThreadData.attr=TH_C;
                 ThreadData.option=0;
                 ThreadData.thread=&NETMAN_RPC_srv;
                 ThreadData.stacksize=0x600;
                 ThreadData.priority=0x27;       //Should have higher priority than the IF driver thread, in order to dump frames in the IOP before returning.
                 StartThread(RpcThreadID=CreateThread(&ThreadData), NULL);
                 IsInitialized=1;
         }
         return 0;
 }
References iop_thread_t::attr, CreateThread(), IsInitialized, NETMAN_RPC_srv(), NULL, iop_thread_t::option, iop_thread_t::priority, RpcThreadID, iop_thread_t::stacksize, StartThread(), TH_C, and iop_thread_t::thread.
Referenced by _start().