ps2sdk: iop/network/netman/src/rpc_server.c File Reference
rpc_server.c File Reference
#include <errno.h>
#include <stdio.h>
#include <sysclib.h>
#include <sifcmd.h>
#include <sifman.h>
#include <loadcore.h>
#include <thbase.h>
#include <thevent.h>
#include <thsemap.h>
#include <intrman.h>
#include <netman.h>
#include <netman_rpc.h>
#include "internal.h"
#include "rpc_server.h"
#include "rpc_client.h"
Functions
static void ClearBufferLen (int index)
static void LinkStateUp (void)
static void LinkStateDown (void)
static void * AllocRxPacket (unsigned int length, void **payload)
static void FreeRxPacket (void *packet)
static void EnQRxPacket (void *packet)
static int NextTxPacket (void **payload)
static void DeQTxPacket (void)
static void unregisterEENetworkStack (void)
static void HandleRxEvent (void *packet, void *common)
static void * NETMAN_rpc_handler (int fno, void *buffer, int size)
static void NETMAN_RPC_srv (void *args)
int NetmanInitRPCServer (void)
void NetmanDeinitRPCServer (void)
Variables
static SifRpcServerData_t rpc_sdata
static unsigned char rpc_buffer [80]
static SifRpcDataQueue_t rpc_qdata
union {
s32 result
struct NetManIoctlResult IoctlResult
struct NetManQueryMainNetIFResult QueryMainNetIFResult
struct NetManRegNetworkStackResult RegNetworkStackResult
u8 buffer [80]
} SifRpcTxBuffer
static u8 * TxFrameBuffer = NULL
static struct NetManBD * FrameBufferStatus = NULL
static struct NetManBD * EEFrameBufferStatus = NULL
static unsigned short int IOPFrameBufferRdPtr
static int RpcThreadID = -1
static unsigned char IsInitialized =0
static unsigned char IsRpcStackInitialized =0
static struct NetManNetProtStack RpcStack
Function Documentation
AllocRxPacket()
static void* AllocRxPacket (unsigned int length, void ** payload) static
Definition at line 52 of file rpc_server.c.
 {
         return NetManRpcNetProtStackAllocRxPacket(length, payload);
 }
References NetManBD::length, NetManRpcNetProtStackAllocRxPacket(), and NetManBD::payload.
ClearBufferLen()
static void ClearBufferLen (int index) static
Definition at line 115 of file rpc_server.c.
 {
         static struct NetManBD zero = { 0 };
         SifDmaTransfer_t dmat;
         int dmat_id, OldState;
         FrameBufferStatus[index].length = 0;
         //Transfer to EE RAM
         dmat.src = (void*)&zero;
         dmat.dest = &EEFrameBufferStatus[index];
         dmat.size = sizeof(zero);
         dmat.attr = 0;
         do{
                 CpuSuspendIntr(&OldState);
                 dmat_id = sceSifSetDma(&dmat, 1);
                 CpuResumeIntr(OldState);
         }while(dmat_id == 0);
 }
References SifDmaTransfer_t::attr, CpuResumeIntr(), CpuSuspendIntr(), SifDmaTransfer_t::dest, EEFrameBufferStatus, FrameBufferStatus, index(), NetManBD::length, sceSifSetDma(), SifDmaTransfer_t::size, SifDmaTransfer_t::src, and zero.
Referenced by DeQTxPacket().
DeQTxPacket()
static void DeQTxPacket (void) static
Definition at line 73 of file rpc_server.c.
 {
         ClearBufferLen(IOPFrameBufferRdPtr);
         //Increment read pointer by one place.
         IOPFrameBufferRdPtr = (IOPFrameBufferRdPtr + 1) % NETMAN_RPC_BLOCK_SIZE;
 }
References ClearBufferLen(), IOPFrameBufferRdPtr, and NETMAN_RPC_BLOCK_SIZE.
EnQRxPacket()
static void EnQRxPacket (void * packet) static
Definition at line 62 of file rpc_server.c.
 {
         NetManRpcProtStackEnQRxPacket(packet);
 }
References NetManRpcProtStackEnQRxPacket(), and NetManBD::packet.
FreeRxPacket()
static void FreeRxPacket (void * packet) static
Definition at line 57 of file rpc_server.c.
 {
         NetManRpcNetProtStackFreeRxPacket(packet);
 }
References NetManRpcNetProtStackFreeRxPacket(), and NetManBD::packet.
HandleRxEvent()
static void HandleRxEvent (void * packet, void * common) static
Definition at line 136 of file rpc_server.c.
 {
         struct NetManPktCmd *bd = (struct NetManPktCmd*)&((SifCmdHeader_t*)packet)->opt;
         u8 id = bd->id;
         u8 offset = bd->offset;
         u16 len = bd->length;
         FrameBufferStatus[id].length = len;
         FrameBufferStatus[id].offset = offset;
         NetManNetIFXmit();
 }
References FrameBufferStatus, NetManPktCmd::id, NetManPktCmd::length, NetManBD::length, NetManNetIFXmit(), NetManPktCmd::offset, and NetManBD::offset.
Referenced by NETMAN_rpc_handler().
LinkStateDown()
static void LinkStateDown (void) static
Definition at line 47 of file rpc_server.c.
 {
         NetManRpcToggleGlobalNetIFLinkState(0);
 }
References NetManRpcToggleGlobalNetIFLinkState().
LinkStateUp()
static void LinkStateUp (void) static
Definition at line 42 of file rpc_server.c.
 {
         NetManRpcToggleGlobalNetIFLinkState(1);
 }
References NetManRpcToggleGlobalNetIFLinkState().
NETMAN_rpc_handler()
static void* NETMAN_rpc_handler (int fno, void * buffer, int size) static
Definition at line 149 of file rpc_server.c.
 {
         static int ResultValue;
         void *result;
         switch(fno)
         {
                 case NETMAN_IOP_RPC_FUNC_INIT:
                         ResultValue=NetManInitRPCClient();
                         result=&ResultValue;
                         break;
                 case NETMAN_IOP_RPC_FUNC_DEINIT:
                         unregisterEENetworkStack();
                         NetManDeinitRPCClient();
                         result=NULL;
                         break;
                 case NETMAN_IOP_RPC_FUNC_REG_NETWORK_STACK:
                         result = &SifRpcTxBuffer;
                         if(TxFrameBuffer == NULL) TxFrameBuffer = malloc(NETMAN_MAX_FRAME_SIZE * NETMAN_RPC_BLOCK_SIZE);
                         if(FrameBufferStatus == NULL) FrameBufferStatus = malloc(sizeof(struct NetManBD) * NETMAN_RPC_BLOCK_SIZE);
                         if(TxFrameBuffer != NULL && FrameBufferStatus != NULL)
{
                                 EEFrameBufferStatus = ((struct NetManRegNetworkStack*)buffer)->FrameBufferStatus;
                                 memset(FrameBufferStatus, 0, sizeof(struct NetManBD) * NETMAN_RPC_BLOCK_SIZE);
                                 memset(TxFrameBuffer, 0, NETMAN_MAX_FRAME_SIZE * NETMAN_RPC_BLOCK_SIZE);
                                 SifRpcTxBuffer.RegNetworkStackResult.FrameBuffer = TxFrameBuffer;
                                 IOPFrameBufferRdPtr = 0;
                                 ResultValue = NetManRegisterNetworkStack(&RpcStack);
                                 if(ResultValue == 0)
                                         sceSifAddCmdHandler(NETMAN_SIFCMD_ID, &HandleRxEvent, NULL);
                         }else{
                                 ResultValue = -ENOMEM;
                         }
                         IsRpcStackInitialized=1;
                         SifRpcTxBuffer.RegNetworkStackResult.result = ResultValue;
                         SifRpcTxBuffer.RegNetworkStackResult.FrameBufferStatus = FrameBufferStatus;
                         break;
                 case NETMAN_IOP_RPC_FUNC_UNREG_NETWORK_STACK:
                         unregisterEENetworkStack();
                         result=NULL;
                         break;
                 case NETMAN_IOP_RPC_FUNC_IOCTL:
                         SifRpcTxBuffer.IoctlResult.result=NetManIoctl(((struct NetManIoctl*)buffer)->command, ((struct NetManIoctl*)buffer)->args, ((struct NetManIoctl*)buffer)->args_len, SifRpcTxBuffer.IoctlResult.output, ((struct NetManIoctl*)buffer)->length);
                         result=&SifRpcTxBuffer;
                         break;
                 case NETMAN_IOP_RPC_FUNC_SET_MAIN_NETIF:
                         SifRpcTxBuffer.result=NetManSetMainIF(buffer);
                         result=&SifRpcTxBuffer;
                         break;
                 case NETMAN_IOP_RPC_FUNC_QUERY_MAIN_NETIF:
                         SifRpcTxBuffer.QueryMainNetIFResult.result=NetManQueryMainIF(SifRpcTxBuffer.QueryMainNetIFResult.name);
                         result=&SifRpcTxBuffer;
                         break;
                 case NETMAN_IOP_RPC_FUNC_SET_LINK_MODE:
                         ResultValue=NetManSetLinkMode(*(s32*)buffer);
                         result=&ResultValue;
                         break;
                 default:
                         printf("NETMAN [IOP]: Unrecognized command: 0x%x\n", fno);
                         ResultValue=-1;
                         result=&ResultValue;
         }
         return result;
 }
References buffer, EEFrameBufferStatus, ENOMEM, FrameBufferStatus, HandleRxEvent(), IOPFrameBufferRdPtr, IsRpcStackInitialized, malloc, memset(), NETMAN_IOP_RPC_FUNC_DEINIT, NETMAN_IOP_RPC_FUNC_INIT, NETMAN_IOP_RPC_FUNC_IOCTL, NETMAN_IOP_RPC_FUNC_QUERY_MAIN_NETIF, NETMAN_IOP_RPC_FUNC_REG_NETWORK_STACK, NETMAN_IOP_RPC_FUNC_SET_LINK_MODE, NETMAN_IOP_RPC_FUNC_SET_MAIN_NETIF, NETMAN_IOP_RPC_FUNC_UNREG_NETWORK_STACK, NETMAN_MAX_FRAME_SIZE, NETMAN_RPC_BLOCK_SIZE, NETMAN_SIFCMD_ID, NetManDeinitRPCClient(), NetManInitRPCClient(), NetManIoctl(), NetManQueryMainIF(), NetManRegisterNetworkStack(), NetManSetLinkMode(), NetManSetMainIF(), NULL, printf(), result, RpcStack, sceSifAddCmdHandler(), SifRpcTxBuffer, TxFrameBuffer, and unregisterEENetworkStack().
Referenced by NETMAN_RPC_srv().
NETMAN_RPC_srv()
static void NETMAN_RPC_srv (void * args) static
Definition at line 219 of file rpc_server.c.
 {
         sceSifSetRpcQueue(&rpc_qdata, RpcThreadID);
         sceSifRegisterRpc(&rpc_sdata, NETMAN_RPC_NUMBER, &NETMAN_rpc_handler, rpc_buffer, NULL, NULL, &rpc_qdata);
         sceSifRpcLoop(&rpc_qdata);
 }
References NETMAN_rpc_handler(), NETMAN_RPC_NUMBER, NULL, rpc_buffer, rpc_qdata, rpc_sdata, RpcThreadID, sceSifRegisterRpc(), sceSifRpcLoop(), and sceSifSetRpcQueue().
Referenced by NetmanInitRPCServer().
NetmanDeinitRPCServer()
void NetmanDeinitRPCServer (void)
Definition at line 246 of file rpc_server.c.
 {
         if(IsInitialized)
         {
                 sceSifRemoveRpc(&rpc_sdata, &rpc_qdata);
                 sceSifRemoveRpcQueue(&rpc_qdata);
                 TerminateThread(RpcThreadID);
                 DeleteThread(RpcThreadID);
                 IsInitialized=0;
         }
 }
References DeleteThread(), IsInitialized, rpc_qdata, rpc_sdata, RpcThreadID, sceSifRemoveRpc(), sceSifRemoveRpcQueue(), and TerminateThread().
NetmanInitRPCServer()
int NetmanInitRPCServer (void)
Definition at line 227 of file rpc_server.c.
 {
         iop_thread_t ThreadData;
         if(!IsInitialized)
         {
                 ThreadData.attr=TH_C;
                 ThreadData.option=0;
                 ThreadData.thread=&NETMAN_RPC_srv;
                 ThreadData.stacksize=0x600;
                 ThreadData.priority=0x27;       //Should have higher priority than the IF driver thread, in order to dump frames in the IOP before returning.
                 StartThread(RpcThreadID=CreateThread(&ThreadData), NULL);
                 IsInitialized=1;
         }
         return 0;
 }
References iop_thread_t::attr, CreateThread(), IsInitialized, NETMAN_RPC_srv(), NULL, iop_thread_t::option, iop_thread_t::priority, RpcThreadID, iop_thread_t::stacksize, StartThread(), TH_C, and iop_thread_t::thread.
Referenced by _start().
NextTxPacket()
static int NextTxPacket (void ** payload) static
Definition at line 67 of file rpc_server.c.
 {
         *payload = &TxFrameBuffer[IOPFrameBufferRdPtr * NETMAN_MAX_FRAME_SIZE + FrameBufferStatus[IOPFrameBufferRdPtr].offset];
         return FrameBufferStatus[IOPFrameBufferRdPtr].length;
 }
References FrameBufferStatus, IOPFrameBufferRdPtr, NetManBD::length, NETMAN_MAX_FRAME_SIZE, NetManBD::offset, NetManBD::payload, and TxFrameBuffer.
unregisterEENetworkStack()
static void unregisterEENetworkStack (void) static
Definition at line 91 of file rpc_server.c.
 {
         if(IsRpcStackInitialized)
         {
                 IsRpcStackInitialized=0;
                 NetManUnregisterNetworkStack();
                 if(TxFrameBuffer != NULL)
                 {
                         free(TxFrameBuffer);
                         TxFrameBuffer = NULL;
                 }
                 if(FrameBufferStatus != NULL)
                 {
                         free(FrameBufferStatus);
                         FrameBufferStatus = NULL;
                 }
                 EEFrameBufferStatus = NULL;
         }
         sceSifRemoveCmdHandler(NETMAN_SIFCMD_ID);
 }
References EEFrameBufferStatus, FrameBufferStatus, free, IsRpcStackInitialized, NETMAN_SIFCMD_ID, NetManUnregisterNetworkStack(), NULL, sceSifRemoveCmdHandler(), and TxFrameBuffer.
Referenced by NETMAN_rpc_handler().
Variable Documentation
buffer
u8 buffer[80]
Definition at line 28 of file rpc_server.c.
Referenced by NETMAN_rpc_handler().
EEFrameBufferStatus
struct NetManBD* EEFrameBufferStatus = NULL static
Definition at line 34 of file rpc_server.c.
Referenced by ClearBufferLen(), NETMAN_rpc_handler(), and unregisterEENetworkStack().
FrameBufferStatus
struct NetManBD* FrameBufferStatus = NULL static
Definition at line 33 of file rpc_server.c.
Referenced by ClearBufferLen(), HandleRxEvent(), NETMAN_rpc_handler(), NextTxPacket(), and unregisterEENetworkStack().
IoctlResult
struct NetManIoctlResult IoctlResult
Definition at line 24 of file rpc_server.c.
IOPFrameBufferRdPtr
unsigned short int IOPFrameBufferRdPtr static
Definition at line 35 of file rpc_server.c.
Referenced by DeQTxPacket(), NETMAN_rpc_handler(), and NextTxPacket().
IsInitialized
unsigned char IsInitialized =0 static
Definition at line 38 of file rpc_server.c.
Referenced by NetmanDeinitRPCServer(), and NetmanInitRPCServer().
IsRpcStackInitialized
unsigned char IsRpcStackInitialized =0 static
Definition at line 38 of file rpc_server.c.
Referenced by NETMAN_rpc_handler(), and unregisterEENetworkStack().
QueryMainNetIFResult
struct NetManQueryMainNetIFResult QueryMainNetIFResult
Definition at line 24 of file rpc_server.c.
RegNetworkStackResult
struct NetManRegNetworkStackResult RegNetworkStackResult
Definition at line 24 of file rpc_server.c.
result
s32 result
Definition at line 24 of file rpc_server.c.
Referenced by NETMAN_rpc_handler().
rpc_buffer
unsigned char rpc_buffer[80] static
Definition at line 20 of file rpc_server.c.
Referenced by NETMAN_RPC_srv().
rpc_qdata
SifRpcDataQueue_t rpc_qdata static
Definition at line 21 of file rpc_server.c.
Referenced by NETMAN_RPC_srv(), and NetmanDeinitRPCServer().
rpc_sdata
SifRpcServerData_t rpc_sdata static
Definition at line 19 of file rpc_server.c.
Referenced by NETMAN_RPC_srv(), and NetmanDeinitRPCServer().
RpcStack
struct NetManNetProtStack RpcStack static
Initial value:
={
        &LinkStateUp,
        &LinkStateDown,
        &AllocRxPacket,
        &FreeRxPacket,
        &EnQRxPacket,
        &NextTxPacket,
        &DeQTxPacket
}
Definition at line 73 of file rpc_server.c.
Referenced by NETMAN_rpc_handler().
RpcThreadID
int RpcThreadID = -1 static
Definition at line 37 of file rpc_server.c.
Referenced by NETMAN_RPC_srv(), NetmanDeinitRPCServer(), and NetmanInitRPCServer().
union { ... } SifRpcTxBuffer
Referenced by NETMAN_rpc_handler().
TxFrameBuffer
u8* TxFrameBuffer = NULL static
Definition at line 32 of file rpc_server.c.
Referenced by NETMAN_rpc_handler(), NextTxPacket(), and unregisterEENetworkStack().