ps2sdk: iop/hdd/pfs/src/pfs.h File Reference
pfs.h File Reference
Data Structures
struct pfs_unaligned_io_t
struct pfs_ioctl2attr_t
struct pfs_file_slot_t
struct pfs_config_t
Macros
#define min(a, b) ((a) < (b) ? (a) : (b))
#define PFS_AENTRY_KEY_MAX 256
#define PFS_AENTRY_VALUE_MAX 256
#define PFS_MOUNT_BUSY 0x8000
Functions
pfs_mount_t * pfsGetMountedUnit (s32 unit)
void pfsClearMount (pfs_mount_t *pfsMount)
Macro Definition Documentation
min
#define min (a, b) ((a) < (b) ? (a) : (b))
Definition at line 15 of file pfs.h.
PFS_AENTRY_KEY_MAX
#define PFS_AENTRY_KEY_MAX 256
Definition at line 29 of file pfs.h.
PFS_AENTRY_VALUE_MAX
#define PFS_AENTRY_VALUE_MAX 256
Definition at line 30 of file pfs.h.
PFS_MOUNT_BUSY
#define PFS_MOUNT_BUSY 0x8000
Definition at line 56 of file pfs.h.
Function Documentation
pfsClearMount()
void pfsClearMount (pfs_mount_t * pfsMount)
Definition at line 114 of file pfs.c.
 {
         memset(pfsMount, 0, sizeof(pfs_mount_t));
 }
References memset().
Referenced by pfsFioUmount().
pfsGetMountedUnit()
pfs_mount_t* pfsGetMountedUnit (s32 unit)
Definition at line 119 of file pfs.c.
 {       // get mounted unit
         if(unit>=pfsConfig.maxMount)
                 return NULL;
         if(!(pfsMountBuf[unit].flags & PFS_MOUNT_BUSY))
                 return NULL;
         return &pfsMountBuf[unit];
 }
References pfs_config_t::maxMount, NULL, PFS_MOUNT_BUSY, pfsConfig, and pfsMountBuf.
Referenced by pfsFioDevctlCloseAll(), and pfsFioGetMountedUnit().