ps2sdk: iop/hdd/pfs/src/pfs_fioctl.h File Reference
pfs_fioctl.h File Reference
Functions
int pfsFioIoctl (iop_file_t *f, int cmd, void *param)
int pfsFioIoctl2 (iop_file_t *f, int cmd, void *arg, size_t arglen, void *buf, size_t buflen)
int pfsFioDevctl (iop_file_t *f, const char *name, int cmd, void *arg, size_t arglen, void *buf, size_t buflen)
void pfsFioDevctlCloseAll (void)
Function Documentation
pfsFioDevctl()
int pfsFioDevctl (iop_file_t * f, const char * name, int cmd, void * arg, size_t arglen, void * buf, size_t buflen)
Definition at line 64 of file pfs_fioctl.c.
 {
         pfs_mount_t *pfsMount;
         int rv=0;
         if(!(pfsMount=pfsFioGetMountedUnit(f->unit)))
                 return -ENODEV;
         switch(cmd)
         {
         case PDIOC_ZONESZ:
                 rv=pfsMount->zsize;
                 break;
         case PDIOC_ZONEFREE:
                 rv=pfsMount->zfree;
                 break;
         case PDIOC_CLOSEALL:
                 pfsFioDevctlCloseAll();
                 break;
         case PDIOC_CLRFSCKSTAT:
                 rv=devctlFsckStat(pfsMount, PFS_MODE_REMOVE_FLAG);
                 break;
         case PDIOC_GETFSCKSTAT:
                 rv=devctlFsckStat(pfsMount, PFS_MODE_CHECK_FLAG);
                 break;
         case PDIOC_SHOWBITMAP:
                 pfsBitmapShow(pfsMount);
                 break;
         default:
                 rv=-EINVAL;
                 break;
         }
         SignalSema(pfsFioSema);
         return rv;
 }
References devctlFsckStat(), EINVAL, ENODEV, PDIOC_CLOSEALL, PDIOC_CLRFSCKSTAT, PDIOC_GETFSCKSTAT, PDIOC_SHOWBITMAP, PDIOC_ZONEFREE, PDIOC_ZONESZ, PFS_MODE_CHECK_FLAG, PFS_MODE_REMOVE_FLAG, pfsBitmapShow(), pfsFioDevctlCloseAll(), pfsFioGetMountedUnit(), pfsFioSema, SignalSema(), iop_file_t::unit, pfs_mount_t::zfree, and pfs_mount_t::zsize.
pfsFioDevctlCloseAll()
void pfsFioDevctlCloseAll (void)
Definition at line 211 of file pfs_fioctl.c.
 {
         s32 i;
         for(i=0;i < pfsConfig.maxOpen;i++)
         {
                 if(pfsFileSlots[i].fd)
                         pfsFioCloseFileSlot(&pfsFileSlots[i]);
         }
         for(i=0;i < pfsConfig.maxOpen;i++)
         {
                 pfs_mount_t *pfsMount;
                 if((pfsMount=pfsGetMountedUnit(i))!=NULL)
                         pfsCacheFlushAllDirty(pfsMount);
         }
 }
References pfs_config_t::maxOpen, NULL, pfsCacheFlushAllDirty(), pfsConfig, pfsFileSlots, pfsFioCloseFileSlot(), and pfsGetMountedUnit().
Referenced by pfsFioDeinit(), and pfsFioDevctl().
pfsFioIoctl()
int pfsFioIoctl (iop_file_t * f, int cmd, void * param)
Definition at line 59 of file pfs_fioctl.c.
 {
         return -1;
 }
pfsFioIoctl2()
int pfsFioIoctl2 (iop_file_t * f, int cmd, void * arg, size_t arglen, void * buf, size_t buflen)
Definition at line 116 of file pfs_fioctl.c.
 {
         int rv;
         pfs_file_slot_t *fileSlot = (pfs_file_slot_t *)f->privdata;
         pfs_mount_t *pfsMount;
         if(f->mode & O_DIROPEN)
                 if(cmd==PIOCATTRREAD)
                         return -EISDIR;
         if(!(f->mode & O_WRONLY))
         {
                 switch(cmd)
                 {
                         case PIOCATTRLOOKUP:
                         case PIOCATTRREAD:
                         case PIOCINVINODE:
                                 break;
                         default:
                                 return -EACCES;
                 }
         }
         if((rv=pfsFioCheckFileSlot(fileSlot))<0)
                 return rv;
         pfsMount=fileSlot->clink->pfsMount;
         switch(cmd)
         {
         case PIOCALLOC:
                 rv=pfsAllocZones(fileSlot->clink, *(int *)(arg), 1);
                 break;
         case PIOCFREE:
                 pfsFreeZones(fileSlot->clink);
                 break;
         case PIOCATTRADD:
         case PIOCATTRDEL:
         case PIOCATTRLOOKUP:
         case PIOCATTRREAD:
                 rv=ioctl2Attr(fileSlot->clink, cmd, arg, buf, &fileSlot->aentryOffset);
                 break;
 #ifdef PFS_IOCTL2_INC_CHECKSUM
         case PIOCINVINODE:
                 rv=ioctl2InvalidateInode(fileSlot->clink);
                 break;
 #endif
         default:
                 rv=-EINVAL;
                 break;
         }
         if(pfsMount->flags & PFS_FIO_ATTR_WRITEABLE)
                 pfsCacheFlushAllDirty(pfsMount);
         rv=pfsFioCheckForLastError(pfsMount, rv);
         SignalSema(pfsFioSema);
         return rv;
 }
References pfs_file_slot_t::aentryOffset, arg, pfs_file_slot_t::clink, EACCES, EINVAL, EISDIR, ioctl2Attr(), iop_file_t::mode, O_DIROPEN, O_WRONLY, PFS_FIO_ATTR_WRITEABLE, pfsAllocZones(), pfsCacheFlushAllDirty(), pfsFioCheckFileSlot(), pfsFioCheckForLastError(), pfsFioSema, pfsFreeZones(), pfs_cache_t::pfsMount, PIOCALLOC, PIOCATTRADD, PIOCATTRDEL, PIOCATTRLOOKUP, PIOCATTRREAD, PIOCFREE, PIOCINVINODE, iop_file_t::privdata, and SignalSema().