ps2sdk: iop/hdd/pfs/src/pfs_fioctl.c File Reference
pfs_fioctl.c File Reference
#include <stdio.h>
#include <sysclib.h>
#include <errno.h>
#include <iomanX.h>
#include <thsemap.h>
#include <hdd-ioctl.h>
#include "pfs-opt.h"
#include "libpfs.h"
#include "pfs.h"
#include "pfs_fio.h"
#include "pfs_fioctl.h"
Enumerations
enum PFS_AENTRY_MODE {
PFS_AENTRY_MODE_LOOKUP = 0 ,
PFS_AENTRY_MODE_ADD ,
PFS_AENTRY_MODE_DELETE
}
Functions
static int devctlFsckStat (pfs_mount_t *pfsMount, int mode)
static int ioctl2Attr (pfs_cache_t *clink, int cmd, void *arg, void *outbuf, u32 *offset)
static pfs_aentry_t * getAentry (pfs_cache_t *clink, char *key, char *value, int mode)
static int ioctl2AttrAdd (pfs_cache_t *clink, pfs_ioctl2attr_t *attr)
static int ioctl2AttrDelete (pfs_cache_t *clink, void *arg)
static int ioctl2AttrLookUp (pfs_cache_t *clink, char *key, char *value)
static int ioctl2AttrRead (pfs_cache_t *clink, pfs_ioctl2attr_t *attr, u32 *unkbuf)
int pfsFioIoctl (iop_file_t *f, int cmd, void *param)
int pfsFioDevctl (iop_file_t *f, const char *name, int cmd, void *arg, size_t arglen, void *buf, size_t buflen)
int pfsFioIoctl2 (iop_file_t *f, int cmd, void *arg, size_t arglen, void *buf, size_t buflen)
void pfsFioDevctlCloseAll (void)
Variables
pfs_config_t pfsConfig
int pfsFioSema
pfs_file_slot_t * pfsFileSlots
Enumeration Type Documentation
PFS_AENTRY_MODE
enum PFS_AENTRY_MODE
Enumerator
PFS_AENTRY_MODE_LOOKUP
PFS_AENTRY_MODE_ADD
PFS_AENTRY_MODE_DELETE
Definition at line 38 of file pfs_fioctl.c.
                      {
         PFS_AENTRY_MODE_LOOKUP = 0,
         PFS_AENTRY_MODE_ADD,
         PFS_AENTRY_MODE_DELETE
 };
Function Documentation
devctlFsckStat()
static int devctlFsckStat (pfs_mount_t * pfsMount, int mode) static
Definition at line 229 of file pfs_fioctl.c.
 {
         int rv;
         pfs_cache_t *clink;
         if((clink=pfsCacheAllocClean(&rv))!=NULL){
                 rv=pfsFsckStat(pfsMount, clink->u.superblock, PFS_FSCK_STAT_ERRORS_FIXED, mode);
                 pfsCacheFree(clink);
         }
         return rv;
 }
References NULL, PFS_FSCK_STAT_ERRORS_FIXED, pfsCacheAllocClean(), pfsCacheFree(), pfsFsckStat(), pfs_cache_t::superblock, and pfs_cache_t::u.
Referenced by pfsFioDevctl().
getAentry()
static pfs_aentry_t * getAentry (pfs_cache_t * clink, char * key, char * value, int mode) static
Definition at line 241 of file pfs_fioctl.c.
 {
         int kLen, fullsize;
         pfs_aentry_t *aentry=clink->u.aentry;
         pfs_aentry_t *aentryLast=NULL;
         pfs_aentry_t *end;
         kLen=strlen(key);
         fullsize=(kLen+strlen(value)+7) & ~3;
         for(end=(pfs_aentry_t *)((u8*)aentry+1024);aentry < end; aentry=(pfs_aentry_t *)((u8*)aentry+aentry->aLen))
         {       //Other than critical errors, do nothing about the filesystem errors.
                 if(aentry->aLen & 3)
                         PFS_PRINTF(PFS_DRV_NAME" Error: aentry allocated length/4 != 0\n");
                 if(aentry->aLen < ((aentry->kLen+aentry->vLen+7) & ~3))
                 {
                         PFS_PRINTF(PFS_DRV_NAME" Panic: aentry is too small\n");
                         return NULL;
                 }
                 if(end < (pfs_aentry_t*)((u8*)aentry+aentry->aLen))
                         PFS_PRINTF(PFS_DRV_NAME" Error: aentry too big\n");
                 switch(mode)
                 {
                 case PFS_AENTRY_MODE_LOOKUP:
                         if(kLen==aentry->kLen)
                                 if(memcmp(key, aentry->str, kLen)==0)
                                         return aentry;
                         break;
                 case PFS_AENTRY_MODE_ADD:
                         if(aentry->kLen==0)
{
                                 if(aentry->aLen>=fullsize)
                                         return aentry;
                         }
                         if(aentry->aLen - ((aentry->kLen+aentry->vLen+7) & ~3) < fullsize)
                                 continue;
                         return aentry;
                 case PFS_AENTRY_MODE_DELETE:
                 default:
                         if(kLen==aentry->kLen)
{
                                 if(memcmp(key, aentry->str, kLen)==0)
{
                                         if(aentryLast!=NULL)
{
                                                 aentryLast->aLen+=aentry->aLen;
                                                 return aentry;
                                         }
                                         // delete it :P
                                         aentry->kLen=0;
                                         aentry->vLen=0;
                                         return aentry;
                                 }
                         }
                         aentryLast=aentry;
                         break;
                 }
         }
         return NULL;
 }
References pfs_cache_t::aentry, pfs_aentry_t::aLen, pfs_aentry_t::kLen, memcmp(), NULL, PFS_AENTRY_MODE_ADD, PFS_AENTRY_MODE_DELETE, PFS_AENTRY_MODE_LOOKUP, PFS_DRV_NAME, PFS_PRINTF, pfs_aentry_t::str, strlen(), pfs_cache_t::u, and pfs_aentry_t::vLen.
Referenced by ioctl2AttrAdd(), ioctl2AttrDelete(), and ioctl2AttrLookUp().
ioctl2Attr()
static int ioctl2Attr (pfs_cache_t * clink, int cmd, void * arg, void * outbuf, u32 * offset) static
Definition at line 178 of file pfs_fioctl.c.
 {       // attr set, attr delete, attr lookup, attr read cmds
         int rv;
         pfs_cache_t *flink;
         if((flink=pfsCacheGetData(clink->pfsMount, clink->sub, clink->block+1
                 ,PFS_CACHE_FLAG_NOTHING, &rv))==NULL)
                 return rv;
         switch(cmd)
         {
         case PIOCATTRADD:
                 rv=ioctl2AttrAdd(flink, arg);
                 break;
         case PIOCATTRDEL:
                 rv=ioctl2AttrDelete(flink, arg);
                 break;
         case PIOCATTRLOOKUP:
                 rv=ioctl2AttrLookUp(flink, arg, outbuf);
                 break;
         case PIOCATTRREAD:
                 rv=ioctl2AttrRead(flink, outbuf, offset);
                 break;
         }
         pfsCacheFree(flink);
         return rv;
 }
References arg, pfs_cache_t::block, ioctl2AttrAdd(), ioctl2AttrDelete(), ioctl2AttrLookUp(), ioctl2AttrRead(), NULL, PFS_CACHE_FLAG_NOTHING, pfsCacheFree(), pfsCacheGetData(), pfs_cache_t::pfsMount, PIOCATTRADD, PIOCATTRDEL, PIOCATTRLOOKUP, PIOCATTRREAD, and pfs_cache_t::sub.
Referenced by pfsFioIoctl2().
ioctl2AttrAdd()
static int ioctl2AttrAdd (pfs_cache_t * clink, pfs_ioctl2attr_t * attr) static
Definition at line 305 of file pfs_fioctl.c.
 {
         u32 kLen, vLen;
         pfs_aentry_t *aentry;
         u32 tmp;
         // input check
         kLen=strlen(attr->key);
         vLen=strlen(attr->value);
         if(kLen>=PFS_AENTRY_KEY_MAX || vLen>=PFS_AENTRY_VALUE_MAX)      // max size bounds check
                 return -EINVAL;
         if(kLen==0 || vLen==0)          // no input check
                 return -EINVAL;
         if(getAentry(clink, attr->key, NULL, PFS_AENTRY_MODE_LOOKUP))
                 return -EEXIST;
         if((aentry=getAentry(clink, attr->key, attr->value, PFS_AENTRY_MODE_ADD)) == NULL)
                 return -ENOSPC;
         if(aentry->kLen==0)
                 tmp=aentry->aLen;
         else
                 tmp=aentry->aLen-((aentry->kLen+(aentry->vLen + 7)) & 0x3FC);   //The only case that uses 0x3FC within the whole PFS driver.
         aentry->aLen-=tmp;
         aentry = (pfs_aentry_t*)((u8 *)aentry + aentry->aLen);
         aentry->kLen=kLen;
         aentry->vLen=vLen;
         aentry->aLen=tmp;
         memcpy(&aentry->str[0], attr->key, aentry->kLen);
         memcpy(&aentry->str[aentry->kLen], attr->value, aentry->vLen);
         clink->flags|=PFS_CACHE_FLAG_DIRTY;
         return 0;
 }
References pfs_aentry_t::aLen, EEXIST, EINVAL, ENOSPC, pfs_cache_t::flags, getAentry(), pfs_ioctl2attr_t::key, pfs_aentry_t::kLen, memcpy(), NULL, PFS_AENTRY_KEY_MAX, PFS_AENTRY_MODE_ADD, PFS_AENTRY_MODE_LOOKUP, PFS_AENTRY_VALUE_MAX, PFS_CACHE_FLAG_DIRTY, pfs_aentry_t::str, strlen(), pfs_ioctl2attr_t::value, and pfs_aentry_t::vLen.
Referenced by ioctl2Attr().
ioctl2AttrDelete()
static int ioctl2AttrDelete (pfs_cache_t * clink, void * arg) static
Definition at line 342 of file pfs_fioctl.c.
 {
         pfs_aentry_t *aentry;
         if((aentry=getAentry(clink, arg, NULL, PFS_AENTRY_MODE_DELETE)) == NULL)
                 return -ENOENT;
         clink->flags|=PFS_CACHE_FLAG_DIRTY;
         return 0;
 }
References arg, ENOENT, pfs_cache_t::flags, getAentry(), NULL, PFS_AENTRY_MODE_DELETE, and PFS_CACHE_FLAG_DIRTY.
Referenced by ioctl2Attr().
ioctl2AttrLookUp()
static int ioctl2AttrLookUp (pfs_cache_t * clink, char * key, char * value) static
Definition at line 352 of file pfs_fioctl.c.
 {
         pfs_aentry_t *aentry;
         if((aentry=getAentry(clink, key, NULL, PFS_AENTRY_MODE_LOOKUP)) != NULL)
         {
                 memcpy(value, &aentry->str[aentry->kLen], aentry->vLen);
                 value[aentry->vLen]=0;
                 return aentry->vLen;
         }
         return -ENOENT;
 }
References ENOENT, getAentry(), pfs_aentry_t::kLen, memcpy(), NULL, PFS_AENTRY_MODE_LOOKUP, pfs_aentry_t::str, and pfs_aentry_t::vLen.
Referenced by ioctl2Attr().
ioctl2AttrRead()
static int ioctl2AttrRead (pfs_cache_t * clink, pfs_ioctl2attr_t * attr, u32 * unkbuf) static
Definition at line 365 of file pfs_fioctl.c.
 {
         pfs_aentry_t *aentry;
         if(*offset >= 1024)
                 return 0;
         do {
                 aentry=(pfs_aentry_t *)((u8*)clink->u.inode+*offset);
                 memcpy(attr->key, &aentry->str[0], aentry->kLen);
                 attr->key[aentry->kLen]=0;
                 memcpy(attr->value, &aentry->str[aentry->kLen], aentry->vLen);
                 attr->value[aentry->vLen]=0;
                 *offset+=aentry->aLen;          // next
                 if(aentry->kLen!=0)
                         break;
         } while(*offset < 1024);
         return aentry->kLen;
 }
References pfs_aentry_t::aLen, pfs_cache_t::inode, pfs_ioctl2attr_t::key, pfs_aentry_t::kLen, memcpy(), pfs_aentry_t::str, pfs_cache_t::u, pfs_ioctl2attr_t::value, and pfs_aentry_t::vLen.
Referenced by ioctl2Attr().
pfsFioDevctl()
int pfsFioDevctl (iop_file_t * f, const char * name, int cmd, void * arg, size_t arglen, void * buf, size_t buflen)
Definition at line 64 of file pfs_fioctl.c.
 {
         pfs_mount_t *pfsMount;
         int rv=0;
         if(!(pfsMount=pfsFioGetMountedUnit(f->unit)))
                 return -ENODEV;
         switch(cmd)
         {
         case PDIOC_ZONESZ:
                 rv=pfsMount->zsize;
                 break;
         case PDIOC_ZONEFREE:
                 rv=pfsMount->zfree;
                 break;
         case PDIOC_CLOSEALL:
                 pfsFioDevctlCloseAll();
                 break;
         case PDIOC_CLRFSCKSTAT:
                 rv=devctlFsckStat(pfsMount, PFS_MODE_REMOVE_FLAG);
                 break;
         case PDIOC_GETFSCKSTAT:
                 rv=devctlFsckStat(pfsMount, PFS_MODE_CHECK_FLAG);
                 break;
         case PDIOC_SHOWBITMAP:
                 pfsBitmapShow(pfsMount);
                 break;
         default:
                 rv=-EINVAL;
                 break;
         }
         SignalSema(pfsFioSema);
         return rv;
 }
References devctlFsckStat(), EINVAL, ENODEV, PDIOC_CLOSEALL, PDIOC_CLRFSCKSTAT, PDIOC_GETFSCKSTAT, PDIOC_SHOWBITMAP, PDIOC_ZONEFREE, PDIOC_ZONESZ, PFS_MODE_CHECK_FLAG, PFS_MODE_REMOVE_FLAG, pfsBitmapShow(), pfsFioDevctlCloseAll(), pfsFioGetMountedUnit(), pfsFioSema, SignalSema(), iop_file_t::unit, pfs_mount_t::zfree, and pfs_mount_t::zsize.
pfsFioDevctlCloseAll()
void pfsFioDevctlCloseAll (void)
Definition at line 211 of file pfs_fioctl.c.
 {
         s32 i;
         for(i=0;i < pfsConfig.maxOpen;i++)
         {
                 if(pfsFileSlots[i].fd)
                         pfsFioCloseFileSlot(&pfsFileSlots[i]);
         }
         for(i=0;i < pfsConfig.maxOpen;i++)
         {
                 pfs_mount_t *pfsMount;
                 if((pfsMount=pfsGetMountedUnit(i))!=NULL)
                         pfsCacheFlushAllDirty(pfsMount);
         }
 }
References pfs_config_t::maxOpen, NULL, pfsCacheFlushAllDirty(), pfsConfig, pfsFileSlots, pfsFioCloseFileSlot(), and pfsGetMountedUnit().
Referenced by pfsFioDeinit(), and pfsFioDevctl().
pfsFioIoctl()
int pfsFioIoctl (iop_file_t * f, int cmd, void * param)
Definition at line 59 of file pfs_fioctl.c.
 {
         return -1;
 }
pfsFioIoctl2()
int pfsFioIoctl2 (iop_file_t * f, int cmd, void * arg, size_t arglen, void * buf, size_t buflen)
Definition at line 116 of file pfs_fioctl.c.
 {
         int rv;
         pfs_file_slot_t *fileSlot = (pfs_file_slot_t *)f->privdata;
         pfs_mount_t *pfsMount;
         if(f->mode & O_DIROPEN)
                 if(cmd==PIOCATTRREAD)
                         return -EISDIR;
         if(!(f->mode & O_WRONLY))
         {
                 switch(cmd)
                 {
                         case PIOCATTRLOOKUP:
                         case PIOCATTRREAD:
                         case PIOCINVINODE:
                                 break;
                         default:
                                 return -EACCES;
                 }
         }
         if((rv=pfsFioCheckFileSlot(fileSlot))<0)
                 return rv;
         pfsMount=fileSlot->clink->pfsMount;
         switch(cmd)
         {
         case PIOCALLOC:
                 rv=pfsAllocZones(fileSlot->clink, *(int *)(arg), 1);
                 break;
         case PIOCFREE:
                 pfsFreeZones(fileSlot->clink);
                 break;
         case PIOCATTRADD:
         case PIOCATTRDEL:
         case PIOCATTRLOOKUP:
         case PIOCATTRREAD:
                 rv=ioctl2Attr(fileSlot->clink, cmd, arg, buf, &fileSlot->aentryOffset);
                 break;
 #ifdef PFS_IOCTL2_INC_CHECKSUM
         case PIOCINVINODE:
                 rv=ioctl2InvalidateInode(fileSlot->clink);
                 break;
 #endif
         default:
                 rv=-EINVAL;
                 break;
         }
         if(pfsMount->flags & PFS_FIO_ATTR_WRITEABLE)
                 pfsCacheFlushAllDirty(pfsMount);
         rv=pfsFioCheckForLastError(pfsMount, rv);
         SignalSema(pfsFioSema);
         return rv;
 }
References pfs_file_slot_t::aentryOffset, arg, pfs_file_slot_t::clink, EACCES, EINVAL, EISDIR, ioctl2Attr(), iop_file_t::mode, O_DIROPEN, O_WRONLY, PFS_FIO_ATTR_WRITEABLE, pfsAllocZones(), pfsCacheFlushAllDirty(), pfsFioCheckFileSlot(), pfsFioCheckForLastError(), pfsFioSema, pfsFreeZones(), pfs_cache_t::pfsMount, PIOCALLOC, PIOCATTRADD, PIOCATTRDEL, PIOCATTRLOOKUP, PIOCATTRREAD, PIOCFREE, PIOCINVINODE, iop_file_t::privdata, and SignalSema().
Variable Documentation
pfsConfig
pfs_config_t pfsConfig extern
Definition at line 77 of file pfs.c.
Referenced by _start(), pfsFioDevctlCloseAll(), and pfsGetMountedUnit().
pfsFileSlots
pfs_file_slot_t* pfsFileSlots extern
Definition at line 35 of file pfs_fio.c.
Referenced by _sync(), fileTransferRemainder(), pfsFioDevctlCloseAll(), pfsFioOpen(), and pfsFioUmount().
pfsFioSema
int pfsFioSema extern
Definition at line 34 of file pfs_fio.c.
Referenced by pfsFioChdir(), pfsFioCheckFileSlot(), pfsFioChstat(), pfsFioClose(), pfsFioDeinit(), pfsFioDevctl(), pfsFioDread(), pfsFioFormat(), pfsFioGetMountedUnit(), pfsFioGetstat(), pfsFioInit(), pfsFioIoctl2(), pfsFioLseek(), pfsFioLseek64(), pfsFioMkdir(), pfsFioMount(), pfsFioOpen(), pfsFioRead(), pfsFioReadlink(), pfsFioRemove(), pfsFioRename(), pfsFioRmdir(), pfsFioSymlink(), pfsFioSync(), pfsFioUmount(), and pfsFioWrite().