ps2sdk: iop/hdd/pfs/src/pfs_fio.h File Reference
pfs_fio.h File Reference
Macros
#define PFS_FDIRO (0x0008) /* internal use for dopen */
Functions
int pfsFioCheckForLastError (pfs_mount_t *pfsMount, int rv)
int pfsFioCheckFileSlot (pfs_file_slot_t *fileSlot)
pfs_mount_t * pfsFioGetMountedUnit (int unit)
void pfsFioCloseFileSlot (pfs_file_slot_t *fileSlot)
int pfsFioInit (iop_device_t *f)
int pfsFioDeinit (iop_device_t *f)
int pfsFioFormat (iop_file_t *, const char *dev, const char *blockdev, void *arg, int arglen)
int pfsFioOpen (iop_file_t *f, const char *name, int flags, int mode)
int pfsFioClose (iop_file_t *f)
int pfsFioRead (iop_file_t *f, void *buf, int size)
int pfsFioWrite (iop_file_t *f, void *buf, int size)
int pfsFioLseek (iop_file_t *f, int pos, int whence)
int pfsFioRemove (iop_file_t *f, const char *name)
int pfsFioMkdir (iop_file_t *f, const char *path, int mode)
int pfsFioRmdir (iop_file_t *f, const char *path)
int pfsFioDopen (iop_file_t *f, const char *name)
int pfsFioDclose (iop_file_t *f)
int pfsFioDread (iop_file_t *f, iox_dirent_t *buf)
int pfsFioGetstat (iop_file_t *f, const char *name, iox_stat_t *stat)
int pfsFioChstat (iop_file_t *f, const char *name, iox_stat_t *stat, unsigned int statmask)
int pfsFioRename (iop_file_t *f, const char *old, const char *new)
int pfsFioChdir (iop_file_t *f, const char *name)
int pfsFioSync (iop_file_t *f, const char *dev, int flag)
int pfsFioMount (iop_file_t *f, const char *fsname, const char *devname, int flag, void *arg, int arglen)
int pfsFioUmount (iop_file_t *f, const char *fsname)
s64 pfsFioLseek64 (iop_file_t *f, s64 offset, int whence)
int pfsFioSymlink (iop_file_t *f, const char *old, const char *new)
int pfsFioReadlink (iop_file_t *f, const char *path, char *buf, unsigned int buflen)
Macro Definition Documentation
PFS_FDIRO
#define PFS_FDIRO (0x0008) /* internal use for dopen */
Definition at line 14 of file pfs_fio.h.
Function Documentation
pfsFioChdir()
int pfsFioChdir (iop_file_t * f, const char * name)
Definition at line 1149 of file pfs_fio.c.
 {
         pfs_mount_t *pfsMount;
         pfs_cache_t *clink;
         int result = 0;
         if(!(pfsMount = pfsFioGetMountedUnit(f->unit)))
                 return -ENODEV;
         clink = pfsInodeGetFile(pfsMount, 0, name, &result);
         if(clink != NULL) {
                 if((clink->u.inode->mode & FIO_S_IFMT) != FIO_S_IFDIR)
                         result = -ENOTDIR;
                 else {
                         result = pfsCheckAccess(clink, 0x01);
                         if(result == 0)
                                 memcpy(&pfsMount->current_dir, &clink->u.inode->inode_block, sizeof(pfs_blockinfo_t));
                 }
                 pfsCacheFree(clink);
         }
         SignalSema(pfsFioSema);
         return pfsFioCheckForLastError(pfsMount, result);
 }
References pfs_mount_t::current_dir, ENODEV, ENOTDIR, FIO_S_IFDIR, FIO_S_IFMT, pfs_cache_t::inode, pfs_inode_t::inode_block, memcpy(), pfs_inode_t::mode, NULL, pfsCacheFree(), pfsCheckAccess(), pfsFioCheckForLastError(), pfsFioGetMountedUnit(), pfsFioSema, pfsInodeGetFile(), result, SignalSema(), pfs_cache_t::u, and iop_file_t::unit.
pfsFioCheckFileSlot()
int pfsFioCheckFileSlot (pfs_file_slot_t * fileSlot)
Definition at line 66 of file pfs_fio.c.
 {
         WaitSema(pfsFioSema);
         if(fileSlot->clink==NULL)
         {
                 SignalSema(pfsFioSema);
                 return -EBADF;
         }
         return 0;
 }
References pfs_file_slot_t::clink, EBADF, NULL, pfsFioSema, SignalSema(), and WaitSema().
Referenced by pfsFioClose(), pfsFioDread(), pfsFioIoctl2(), pfsFioLseek(), pfsFioLseek64(), pfsFioRead(), and pfsFioWrite().
pfsFioCheckForLastError()
int pfsFioCheckForLastError (pfs_mount_t * pfsMount, int rv)
Definition at line 61 of file pfs_fio.c.
 {
         return pfsMount->lastError ? pfsMount->lastError : rv;
 }
References pfs_mount_t::lastError.
Referenced by _remove(), openFile(), pfsFioChdir(), pfsFioChstat(), pfsFioDread(), pfsFioGetstat(), pfsFioIoctl2(), pfsFioRead(), pfsFioReadlink(), pfsFioRename(), pfsFioSync(), and pfsFioWrite().
pfsFioChstat()
int pfsFioChstat (iop_file_t * f, const char * name, iox_stat_t * stat, unsigned int statmask)
Definition at line 948 of file pfs_fio.c.
 {
         pfs_mount_t *pfsMount;
         pfs_cache_t *clink;
         int rv = 0;
         if(!(pfsMount = pfsFioGetMountedUnit(f->unit)))
                 return -ENODEV;
         clink = pfsInodeGetFile(pfsMount, NULL, name, &rv);
         if(clink != NULL) {
                 rv = pfsCheckAccess(clink, 0x02);
                 if(rv == 0) {
                         clink->flags |= PFS_CACHE_FLAG_DIRTY;
                         if((statmask & FIO_CST_MODE) && ((clink->u.inode->mode & FIO_S_IFMT) != FIO_S_IFLNK))
                                 clink->u.inode->mode = (clink->u.inode->mode & FIO_S_IFMT) | (stat->mode & 0xfff);
                         if(statmask & FIO_CST_ATTR)
                                 clink->u.inode->attr = (clink->u.inode->attr & 0xA0) | (stat->attr & 0xFF5F);
                         if(statmask & FIO_CST_SIZE)
                                 rv = -EACCES;
                         if(statmask & FIO_CST_CT)
                                 memcpy(&clink->u.inode->ctime, stat->ctime, sizeof(pfs_datetime_t));
                         if(statmask & FIO_CST_AT)
                                 memcpy(&clink->u.inode->atime, stat->atime, sizeof(pfs_datetime_t));
                         if(statmask & FIO_CST_MT)
                                 memcpy(&clink->u.inode->mtime, stat->mtime, sizeof(pfs_datetime_t));
 /*                      //By PFS v2.2, changing UID and GID was no longer allowed.
                         if(statmask & FIO_CST_PRVT) {
                                 clink->u.inode->uid = stat->private_0;
                                 clink->u.inode->gid = stat->private_1;
                         }       */
                         if(pfsMount->flags & PFS_FIO_ATTR_WRITEABLE)
                                 pfsCacheFlushAllDirty(pfsMount);
                 }
                 pfsCacheFree(clink);
         }
         SignalSema(pfsFioSema);
         return pfsFioCheckForLastError(pfsMount, rv);
 }
References iox_stat_t::atime, pfs_inode_t::atime, iox_stat_t::attr, pfs_inode_t::attr, iox_stat_t::ctime, pfs_inode_t::ctime, EACCES, ENODEV, FIO_CST_AT, FIO_CST_ATTR, FIO_CST_CT, FIO_CST_MODE, FIO_CST_MT, FIO_CST_SIZE, FIO_S_IFLNK, FIO_S_IFMT, pfs_mount_t::flags, pfs_cache_t::flags, pfs_cache_t::inode, memcpy(), iox_stat_t::mode, pfs_inode_t::mode, iox_stat_t::mtime, pfs_inode_t::mtime, NULL, PFS_CACHE_FLAG_DIRTY, PFS_FIO_ATTR_WRITEABLE, pfsCacheFlushAllDirty(), pfsCacheFree(), pfsCheckAccess(), pfsFioCheckForLastError(), pfsFioGetMountedUnit(), pfsFioSema, pfsInodeGetFile(), SignalSema(), pfs_cache_t::u, and iop_file_t::unit.
pfsFioClose()
int pfsFioClose (iop_file_t * f)
Definition at line 623 of file pfs_fio.c.
 {
         pfs_file_slot_t *fileSlot = (pfs_file_slot_t *)f->privdata;
         int rv;
         rv = pfsFioCheckFileSlot(fileSlot);
         if(rv)
                 return rv;
         pfsFioCloseFileSlot(fileSlot);
         SignalSema(pfsFioSema);
         return rv;
 }
References pfsFioCheckFileSlot(), pfsFioCloseFileSlot(), pfsFioSema, iop_file_t::privdata, and SignalSema().
pfsFioCloseFileSlot()
void pfsFioCloseFileSlot (pfs_file_slot_t * fileSlot)
Definition at line 79 of file pfs_fio.c.
 {
         pfs_mount_t *pfsMount=fileSlot->clink->pfsMount;
         if(fileSlot->fd->mode & O_WRONLY)
         {
                 if(fileSlot->unaligned.dirty!=0)
                 {
                         pfsMount->blockDev->transfer(pfsMount->fd, fileSlot->unaligned.buffer,
                                 fileSlot->unaligned.sub, fileSlot->unaligned.sector, 1, PFS_IO_MODE_WRITE);
                 }
                 pfsInodeSetTime(fileSlot->clink);       // set time :P
                 fileSlot->clink->u.inode->attr|=PFS_FIO_ATTR_CLOSED;
                 if(pfsMount->flags & PFS_FIO_ATTR_WRITEABLE)
                         pfsCacheFlushAllDirty(pfsMount);
         }
         pfsCacheFree(fileSlot->block_pos.inode);
         pfsCacheFree(fileSlot->clink);
         memset(fileSlot, 0, sizeof(pfs_file_slot_t));
 }
References pfs_inode_t::attr, pfs_file_slot_t::block_pos, pfs_mount_t::blockDev, pfs_unaligned_io_t::buffer, pfs_file_slot_t::clink, pfs_unaligned_io_t::dirty, pfs_mount_t::fd, pfs_file_slot_t::fd, pfs_mount_t::flags, pfs_cache_t::inode, pfs_blockpos_t::inode, memset(), iop_file_t::mode, O_WRONLY, PFS_FIO_ATTR_CLOSED, PFS_FIO_ATTR_WRITEABLE, PFS_IO_MODE_WRITE, pfsCacheFlushAllDirty(), pfsCacheFree(), pfsInodeSetTime(), pfs_cache_t::pfsMount, pfs_unaligned_io_t::sector, pfs_unaligned_io_t::sub, pfs_block_device_t::transfer, pfs_cache_t::u, and pfs_file_slot_t::unaligned.
Referenced by pfsFioClose(), and pfsFioDevctlCloseAll().
pfsFioDclose()
int pfsFioDclose (iop_file_t * f)
pfsFioDeinit()
int pfsFioDeinit (iop_device_t * f)
Definition at line 535 of file pfs_fio.c.
 {
         pfsFioDevctlCloseAll();
         DeleteSema(pfsFioSema);
         return 0;
 }
References DeleteSema(), pfsFioDevctlCloseAll(), and pfsFioSema.
pfsFioDopen()
int pfsFioDopen (iop_file_t * f, const char * name)
Definition at line 858 of file pfs_fio.c.
 {
     return pfsFioOpen(f, name, 0, 0);
 }
References pfsFioOpen().
pfsFioDread()
int pfsFioDread (iop_file_t * f, iox_dirent_t * buf)
Definition at line 863 of file pfs_fio.c.
 {
         pfs_file_slot_t *fileSlot = (pfs_file_slot_t *)f->privdata;
         pfs_mount_t *pfsMount;
         pfs_cache_t *clink;
         pfs_blockinfo_t bi;
         int result;
         int rv;
         rv = pfsFioCheckFileSlot(fileSlot);
         if(rv < 0)
                 return rv;
         pfsMount = fileSlot->clink->pfsMount;
         if((fileSlot->clink->u.inode->mode & FIO_S_IFMT) != FIO_S_IFDIR)
         {
                 rv = -ENOTDIR;
         }
         else
         {
                 if((rv = pfsGetNextDentry(fileSlot->clink, &fileSlot->block_pos, (u32 *)&fileSlot->position,
                                                                         dirent->name, &bi)) > 0)
                 {
                         clink = pfsInodeGetData(pfsMount, bi.subpart, bi.number, &result);
                         if(clink != NULL)
{
                                 fioStatFiller(clink, &dirent->stat);
                                 pfsCacheFree(clink);
                         }
                         if(result)
                                 rv = result;
                 }
         }
         rv = pfsFioCheckForLastError(pfsMount, rv);
         SignalSema(pfsFioSema);
         return rv;
 }
References pfs_file_slot_t::block_pos, pfs_file_slot_t::clink, ENOTDIR, FIO_S_IFDIR, FIO_S_IFMT, fioStatFiller(), pfs_cache_t::inode, pfs_inode_t::mode, iox_dirent_t::name, NULL, pfsCacheFree(), pfsFioCheckFileSlot(), pfsFioCheckForLastError(), pfsFioSema, pfsGetNextDentry(), pfsInodeGetData(), pfs_cache_t::pfsMount, pfs_file_slot_t::position, iop_file_t::privdata, result, SignalSema(), iox_dirent_t::stat, and pfs_cache_t::u.
pfsFioFormat()
int pfsFioFormat (iop_file_t * t, const char * dev, const char * blockdev, void * arg, int arglen)
Definition at line 544 of file pfs_fio.c.
 {
         int *arg = (int *)args;
         int fragment = 0;
         int fd;
         pfs_block_device_t *blockDev;
         int rv;
         // Has a fragment bit pattern been specified ?
         if((arglen == (3 * sizeof(int))) && (arg[1] == 0x2D66)) //arg[1] == "-f"
                 fragment = arg[2];
         if((blockDev = pfsGetBlockDeviceTable(blockdev)) == 0)
                 return -ENXIO;
         WaitSema(pfsFioSema);
         fd = open(blockdev, O_RDWR);
         if(fd < 0)
                 rv = fd;
         else {
                 rv = pfsFormat(blockDev, fd, arg[0], fragment);
                 close(fd);
         }
         SignalSema(pfsFioSema);
         return rv;
 }
References arg, close(), ENXIO, O_RDWR, open(), pfsFioSema, pfsFormat(), pfsGetBlockDeviceTable(), SignalSema(), and WaitSema().
pfsFioGetMountedUnit()
pfs_mount_t* pfsFioGetMountedUnit (int unit)
Definition at line 100 of file pfs_fio.c.
 {
         pfs_mount_t *pfsMount;
         WaitSema(pfsFioSema);
         if((pfsMount=pfsGetMountedUnit(unit))==NULL)
                 SignalSema(pfsFioSema);
         return pfsMount;
 }
References NULL, pfsFioSema, pfsGetMountedUnit(), SignalSema(), and WaitSema().
Referenced by pfsFioChdir(), pfsFioChstat(), pfsFioDevctl(), pfsFioGetstat(), pfsFioMkdir(), pfsFioOpen(), pfsFioReadlink(), pfsFioRemove(), pfsFioRename(), pfsFioRmdir(), pfsFioSymlink(), pfsFioSync(), and pfsFioUmount().
pfsFioGetstat()
int pfsFioGetstat (iop_file_t * f, const char * name, iox_stat_t * stat)
Definition at line 928 of file pfs_fio.c.
 {
         pfs_mount_t *pfsMount;
         pfs_cache_t *clink;
         int rv=0;
         if(!(pfsMount = pfsFioGetMountedUnit(f->unit)))
                 return -ENODEV;
         clink=pfsInodeGetFile(pfsMount, NULL, name, &rv);
         if(clink!=NULL)
         {
                 fioStatFiller(clink, stat);
                 pfsCacheFree(clink);
         }
         SignalSema(pfsFioSema);
         return pfsFioCheckForLastError(pfsMount, rv);
 }
References ENODEV, fioStatFiller(), NULL, pfsCacheFree(), pfsFioCheckForLastError(), pfsFioGetMountedUnit(), pfsFioSema, pfsInodeGetFile(), SignalSema(), and iop_file_t::unit.
pfsFioInit()
int pfsFioInit (iop_device_t * f)
Definition at line 521 of file pfs_fio.c.
 {
         iop_sema_t sema;
         sema.attr = 1;
         sema.option = 0;
         sema.initial = 1;
         sema.max = 1;
         pfsFioSema = CreateSema(&sema);
         return 0;
 }
References iop_sema_t::attr, CreateSema(), iop_sema_t::initial, iop_sema_t::max, iop_sema_t::option, and pfsFioSema.
pfsFioLseek()
int pfsFioLseek (iop_file_t * f, int pos, int whence)
Definition at line 734 of file pfs_fio.c.
 {
         pfs_file_slot_t *fileSlot = (pfs_file_slot_t*)f->privdata;
         int result = pfsFioCheckFileSlot(fileSlot);
         if (result)
                 return result;
         result = (u32)_seek(fileSlot, (s64)pos, whence, f->mode);
         SignalSema(pfsFioSema);
         return result;
 }
References _seek(), iop_file_t::mode, pfsFioCheckFileSlot(), pfsFioSema, pos, iop_file_t::privdata, result, and SignalSema().
pfsFioLseek64()
s64 pfsFioLseek64 (iop_file_t * f, s64 offset, int whence)
Definition at line 748 of file pfs_fio.c.
 {
         pfs_file_slot_t *fileSlot = (pfs_file_slot_t *)f->privdata;
         u64 rv;
         rv=pfsFioCheckFileSlot(fileSlot);
         if(!rv)
         {
                 rv=_seek(fileSlot, offset, whence, f->mode);
                 SignalSema(pfsFioSema);
         }
         return rv;
 }
References _seek(), iop_file_t::mode, pfsFioCheckFileSlot(), pfsFioSema, iop_file_t::privdata, and SignalSema().
pfsFioMkdir()
int pfsFioMkdir (iop_file_t * f, const char * path, int mode)
Definition at line 821 of file pfs_fio.c.
 {
         pfs_mount_t *pfsMount;
         int rv;
         mode = (mode & 0xfff) | 0x10000 | FIO_S_IFDIR;  // TODO: change to some constant/macro
         if(!(pfsMount = pfsFioGetMountedUnit(f->unit)))
                 return -ENODEV;
         rv = openFile(pfsMount, NULL, path, O_CREAT | O_WRONLY, mode);
         SignalSema(pfsFioSema);
         return rv;
 }
References ENODEV, FIO_S_IFDIR, NULL, O_CREAT, O_WRONLY, openFile(), pfsFioGetMountedUnit(), pfsFioSema, SignalSema(), and iop_file_t::unit.
pfsFioMount()
int pfsFioMount (iop_file_t * f, const char * fsname, const char * devname, int flag, void * arg, int arglen)
Definition at line 1221 of file pfs_fio.c.
 {
         int rv;
         int fd;
         pfs_block_device_t *blockDev;
         if(!(blockDev = pfsGetBlockDeviceTable(devname)))
                 return -ENXIO;
         WaitSema(pfsFioSema);
         fd = open(devname, (flag & FIO_MT_RDONLY) ? O_RDONLY : O_RDWR); // ps2hdd.irx fd
         if(fd < 0)
                 rv = fd;
         else {
                 if((rv=mountDevice(blockDev, fd, f->unit, flag)) < 0)
                         close(fd);
         }
         SignalSema(pfsFioSema);
         return rv;
 }
References close(), ENXIO, FIO_MT_RDONLY, mountDevice(), O_RDONLY, O_RDWR, open(), pfsFioSema, pfsGetBlockDeviceTable(), SignalSema(), iop_file_t::unit, and WaitSema().
pfsFioOpen()
int pfsFioOpen (iop_file_t * f, const char * name, int flags, int mode)
Definition at line 575 of file pfs_fio.c.
 {
         int rv = 0;
         s32 i;
         pfs_file_slot_t *freeSlot;
         pfs_mount_t *pfsMount;
         if(!name)
                 return -ENOENT;
         if(!(pfsMount = pfsFioGetMountedUnit(f->unit)))
         {
                 return -ENODEV;
         }
         // Find free file slot
         for(i = 0; i < pfsConfig.maxOpen; i++)
         {
                 if(!pfsFileSlots[i].fd) {
                         freeSlot = &pfsFileSlots[i];
                         goto pfsOpen_slotFound;
                 }
         }
         PFS_PRINTF(PFS_DRV_NAME" Error: There are no free file slots!\n");
         freeSlot = NULL;
 pfsOpen_slotFound:
         if(!freeSlot) {
                 rv = -EMFILE;
                 goto pfsOpen_end;
         }
         // Do actual open
         if((rv = openFile(pfsMount, freeSlot, name, f->mode, (mode & 0xfff) | FIO_S_IFREG)))
                 goto pfsOpen_end;
         freeSlot->fd = f;
         f->privdata = freeSlot;
 pfsOpen_end:
         SignalSema(pfsFioSema);
         return rv;
 }
References EMFILE, ENODEV, ENOENT, pfs_file_slot_t::fd, FIO_S_IFREG, pfs_config_t::maxOpen, iop_file_t::mode, NULL, openFile(), PFS_DRV_NAME, PFS_PRINTF, pfsConfig, pfsFileSlots, pfsFioGetMountedUnit(), pfsFioSema, iop_file_t::privdata, SignalSema(), and iop_file_t::unit.
Referenced by pfsFioDopen().
pfsFioRead()
int pfsFioRead (iop_file_t * f, void * buf, int size)
Definition at line 639 of file pfs_fio.c.
 {
         pfs_file_slot_t *fileSlot = (pfs_file_slot_t*)f->privdata;
         int result = pfsFioCheckFileSlot(fileSlot);
         if (result)
         {
                 return result;
         }
         // Check bounds, adjust size if necessary
         if(fileSlot->clink->u.inode->size <  (fileSlot->position + size))
                 size = (int)(fileSlot->clink->u.inode->size - fileSlot->position);
         result = size ? fileTransfer(fileSlot, buf, size, 0) : 0;
         result = pfsFioCheckForLastError(fileSlot->clink->pfsMount, result);
         SignalSema(pfsFioSema);
         return result;
 }
References pfs_file_slot_t::clink, fileTransfer(), pfs_cache_t::inode, pfsFioCheckFileSlot(), pfsFioCheckForLastError(), pfsFioSema, pfs_cache_t::pfsMount, pfs_file_slot_t::position, iop_file_t::privdata, result, SignalSema(), pfs_inode_t::size, and pfs_cache_t::u.
pfsFioReadlink()
int pfsFioReadlink (iop_file_t * f, const char * path, char * buf, unsigned int buflen)
Definition at line 1291 of file pfs_fio.c.
 {
         int rv=0;
         pfs_mount_t *pfsMount;
         pfs_cache_t *clink;
         if(buflen < 0)
                 return -EINVAL;
         if(!(pfsMount=pfsFioGetMountedUnit(f->unit)))
                 return -ENODEV;
         if((clink=pfsInodeGetFile(pfsMount, NULL, path, &rv))!=NULL)
         {
                 if(!FIO_S_ISLNK(clink->u.inode->mode))
                         rv=-EINVAL;
                 else
                 {
                         rv=strlen((char *)&clink->u.inode->data[1]);
                         if(buflen < (unsigned int)rv)
                                 rv=(int)buflen;
                         memcpy(buf, &clink->u.inode->data[1], rv);
                 }
                 pfsCacheFree(clink);
         }
         SignalSema(pfsFioSema);
         return pfsFioCheckForLastError(pfsMount, rv);
 }
References pfs_inode_t::data, EINVAL, ENODEV, FIO_S_ISLNK, pfs_cache_t::inode, memcpy(), pfs_inode_t::mode, NULL, pfsCacheFree(), pfsFioCheckForLastError(), pfsFioGetMountedUnit(), pfsFioSema, pfsInodeGetFile(), SignalSema(), strlen(), pfs_cache_t::u, and iop_file_t::unit.
pfsFioRemove()
int pfsFioRemove (iop_file_t * f, const char * name)
Definition at line 806 of file pfs_fio.c.
 {
         pfs_mount_t *pfsMount;
         int rv;
         if(!(pfsMount = pfsFioGetMountedUnit(f->unit)))
                 return -ENODEV;
         rv = _remove(pfsMount, name, 0);
         SignalSema(pfsFioSema);
         return rv;
 }
References _remove(), ENODEV, pfsFioGetMountedUnit(), pfsFioSema, SignalSema(), and iop_file_t::unit.
pfsFioRename()
int pfsFioRename (iop_file_t * f, const char * old, const char * new)
Definition at line 995 of file pfs_fio.c.
 {
         char path1[256], path2[256];
         int result=0;
         pfs_mount_t *pfsMount;
         int f, sameParent;
         pfs_cache_t *parentOld=NULL, *parentNew=NULL;
         pfs_cache_t *removeOld=NULL, *removeNew=NULL;
         pfs_cache_t *iFileOld=NULL, *iFileNew=NULL;
         pfs_cache_t *newParent=NULL,*addNew=NULL;
         pfsMount=pfsFioGetMountedUnit(ff->unit);
         if (pfsMount==0)        return -ENODEV;
         parentOld=pfsInodeGetParent(pfsMount, NULL, old, path1, &result);
         if (parentOld){
                 u32 nused=parentOld->nused;
                 if (nused != 1){
                         result=-EBUSY;
                         goto exit;
                 }
                 if ((iFileOld=pfsInodeGetFileInDir(parentOld, path1, &result))==NULL) goto exit;
                 if ((parentNew=pfsInodeGetParent(pfsMount, NULL, new, path2, &result))==NULL) goto exit;
                 f=(iFileOld->u.inode->mode & FIO_S_IFMT) == FIO_S_IFDIR;
                 sameParent = parentOld == parentNew;
                 if ((parentNew->nused != nused) && ((!sameParent) || (parentNew->nused!=2))){
                         result=-EBUSY;
                         goto exit;
                 }
                 iFileNew=pfsInodeGetFileInDir(parentNew, path2, &result);
                 if (iFileNew){
                         if (f){
                                 if ((iFileNew->u.inode->mode & FIO_S_IFMT) != FIO_S_IFDIR)
                                         result=-ENOTDIR;
                                 else
                                         if (pfsCheckDirForFiles(iFileNew)){
                                                 if (iFileNew->nused >= 2)
                                                         result=-EBUSY;
                                                 else{
                                                         if (iFileOld==iFileNew)
                                                                 goto exit;
                                                 }
                                         }else
                                                 result=-ENOTEMPTY;
                         }else
                                 if ((iFileNew->u.inode->mode & FIO_S_IFMT) == FIO_S_IFDIR)
                                         result=-EISDIR;
                                 else
                                         if (iFileNew->nused >= 2)
                                                 result=-EBUSY;
                                         else{
                                                 if (iFileOld==iFileNew)
                                                         goto exit;
                                         }
                 }else
                         if (result==-ENOENT)
                                 result=0;
                 if (result)     goto exit;
                 if (f && (!sameParent)){
                         pfs_cache_t *parent;
                         parent=pfsCacheUsedAdd(parentNew);
                         do{
                                 pfs_cache_t *tmp;
                                 if (parent==iFileOld){
                                         result=-EINVAL;
                                         break;
                                 }
                                 tmp=pfsInodeGetFileInDir(parent, "..", &result);
                                 pfsCacheFree(parent);
                                 if (tmp==parent)break;
                                 parent=tmp;
                         }while(parent);
                         pfsCacheFree(parent);
                 }
                 if (result==0){
                         if (strcmp(path1, ".") && strcmp(path1, "..") &&
                             strcmp(path2, ".") && strcmp(path2, "..")){
                                 result=pfsCheckAccess(parentOld, 3);
                                 if (result==0)
                                         result=pfsCheckAccess(parentNew, 3);
                         }else
                                 result=-EINVAL;
                         if (result==0){
                                 if (iFileNew && ((removeNew=pfsDirRemoveEntry(parentNew, path2))==NULL))
                                         result=-ENOENT;
                                 else{
                                         removeOld=pfsDirRemoveEntry(parentOld, path1);
                                         if (removeOld==0)
                                                 result=-ENOENT;
                                         else{
                                                 addNew=pfsDirAddEntry(parentNew, path2, &iFileOld->u.inode->inode_block, iFileOld->u.inode->mode, &result);
                                                 if (addNew && f && (!sameParent))
                                                         newParent=pfsSetDentryParent(iFileOld, &parentNew->u.inode->inode_block, &result);
                                         }
                                 }
                         }
                 }
                 if (result){
                         if (removeNew)  removeNew->pfsMount=NULL;
                         if (removeOld)  removeOld->pfsMount=NULL;
                         if (addNew)             addNew->pfsMount=NULL;
                         if (iFileNew)   iFileNew->pfsMount=NULL;
                         parentOld->pfsMount=NULL;
                         parentNew->pfsMount=NULL;
                 }else{
                         if (sameParent){
                                 if (removeOld!=addNew)
                                         removeOld->flags |= PFS_CACHE_FLAG_DIRTY;
                         }else
{
                                 pfsInodeSetTimeParent(parentOld, removeOld);
                         }
                         pfsInodeSetTimeParent(parentNew, addNew);
                         if (newParent != NULL){
                                 pfsInodeSetTimeParent(iFileOld, newParent);
                                 pfsCacheFree(newParent);
                         }
                         if (iFileNew != NULL){
                                 iFileNew->flags &= ~PFS_CACHE_FLAG_DIRTY;
                                 pfsBitmapFreeInodeBlocks(iFileNew);
                         }
                         //if (pfsMount->flags & PFS_FIO_ATTR_WRITEABLE)         No check for this in late versions of PFS.
                         pfsCacheFlushAllDirty(pfsMount);
                 }
                 if (removeOld)  pfsCacheFree(removeOld);
                 if (addNew)             pfsCacheFree(addNew);
                 if (removeNew)  pfsCacheFree(removeNew);
 exit:
                 if (iFileNew)   pfsCacheFree(iFileNew);
                 pfsCacheFree(iFileOld);
                 pfsCacheFree(parentOld);
                 pfsCacheFree(parentNew);
         }
         SignalSema(pfsFioSema);
         return pfsFioCheckForLastError(pfsMount, result);
 }
References EBUSY, EINVAL, EISDIR, ENODEV, ENOENT, ENOTDIR, ENOTEMPTY, FIO_S_IFDIR, FIO_S_IFMT, pfs_cache_t::flags, pfs_cache_t::inode, pfs_inode_t::inode_block, pfs_inode_t::mode, NULL, pfs_cache_t::nused, PFS_CACHE_FLAG_DIRTY, pfsBitmapFreeInodeBlocks(), pfsCacheFlushAllDirty(), pfsCacheFree(), pfsCacheUsedAdd(), pfsCheckAccess(), pfsCheckDirForFiles(), pfsDirAddEntry(), pfsDirRemoveEntry(), pfsFioCheckForLastError(), pfsFioGetMountedUnit(), pfsFioSema, pfsInodeGetFileInDir(), pfsInodeGetParent(), pfsInodeSetTimeParent(), pfs_cache_t::pfsMount, pfsSetDentryParent(), result, SignalSema(), strcmp(), pfs_cache_t::u, and iop_file_t::unit.
pfsFioRmdir()
int pfsFioRmdir (iop_file_t * f, const char * path)
Definition at line 838 of file pfs_fio.c.
 {
         pfs_mount_t *pfsMount;
         const char *temp;
         int rv;
         temp = path + strlen(path);
         if(*temp == '.')
                 return -EINVAL;
         if(!(pfsMount = pfsFioGetMountedUnit(f->unit)))
                 return -ENODEV;
         rv = _remove(pfsMount, path, 0x01); // TODO: constant for 0x01 ?
         SignalSema(pfsFioSema);
         return rv;
 }
References _remove(), EINVAL, ENODEV, pfsFioGetMountedUnit(), pfsFioSema, SignalSema(), strlen(), and iop_file_t::unit.
pfsFioSymlink()
int pfsFioSymlink (iop_file_t * f, const char * old, const char * new)
Definition at line 1274 of file pfs_fio.c.
 {
         int rv;
         pfs_mount_t *pfsMount;
         int mode = 0x10000 | FIO_S_IFLNK | 0x1FF;
         if(old==NULL || new==NULL)
                 return -ENOENT;
         if(!(pfsMount=pfsFioGetMountedUnit(f->unit)))
                 return -ENODEV;
         rv = openFile(pfsMount, (pfs_file_slot_t *)old, (const char *)new, O_CREAT|O_WRONLY, mode);
         SignalSema(pfsFioSema);
         return rv;
 }
References ENODEV, ENOENT, FIO_S_IFLNK, NULL, O_CREAT, O_WRONLY, openFile(), pfsFioGetMountedUnit(), pfsFioSema, SignalSema(), and iop_file_t::unit.
pfsFioSync()
int pfsFioSync (iop_file_t * f, const char * dev, int flag)
Definition at line 1207 of file pfs_fio.c.
 {
         pfs_mount_t *pfsMount;
         if(!(pfsMount = pfsFioGetMountedUnit(f->unit)))
                 return -ENODEV;
         _sync();
         pfsCacheFlushAllDirty(pfsMount);
         SignalSema(pfsFioSema);
         return pfsFioCheckForLastError(pfsMount, 0);
 }
References _sync(), ENODEV, pfsCacheFlushAllDirty(), pfsFioCheckForLastError(), pfsFioGetMountedUnit(), pfsFioSema, SignalSema(), and iop_file_t::unit.
pfsFioUmount()
int pfsFioUmount (iop_file_t * f, const char * fsname)
Definition at line 1243 of file pfs_fio.c.
 {
         s32 i;
         int rv=0;
         int     busy_flag=0;
         pfs_mount_t *pfsMount;
         if((pfsMount = pfsFioGetMountedUnit(f->unit))==NULL)
                 return -ENODEV;
         for(i = 0; i < pfsConfig.maxOpen; i++)
         {
                 if((pfsFileSlots[i].clink!=NULL) && (pfsFileSlots[i].clink->pfsMount==pfsMount))
                 {
                         busy_flag=1;
                         break;
                 }
         }
         if(busy_flag==0)
         {
                 pfsCacheClose(pfsMount);
                 close(pfsMount->fd);
                 pfsClearMount(pfsMount);
         }
         else
                 rv=-EBUSY;      // Mount device busy
         SignalSema(pfsFioSema);
         return rv;
 }
References close(), EBUSY, ENODEV, pfs_mount_t::fd, pfs_config_t::maxOpen, NULL, pfsCacheClose(), pfsClearMount(), pfsConfig, pfsFileSlots, pfsFioGetMountedUnit(), pfsFioSema, SignalSema(), and iop_file_t::unit.
pfsFioWrite()
int pfsFioWrite (iop_file_t * f, void * buf, int size)
Definition at line 660 of file pfs_fio.c.
 {
         pfs_mount_t *pfsMount;
         pfs_file_slot_t *fileSlot = (pfs_file_slot_t*)f->privdata;
         int result = pfsFioCheckFileSlot(fileSlot);
         if(result)
                 return result;
         pfsMount = fileSlot->clink->pfsMount;
         if(fileSlot->position + (unsigned int)size < fileSlot->position)
                 result = -EINVAL;
         else
                 result = fileTransfer(fileSlot, buf, size, 1);
         if (pfsMount->flags & PFS_FIO_ATTR_WRITEABLE)
                 pfsCacheFlushAllDirty(pfsMount);
         result = pfsFioCheckForLastError(pfsMount, result);
         SignalSema(pfsFioSema);
         return result;
 }
References pfs_file_slot_t::clink, EINVAL, fileTransfer(), pfs_mount_t::flags, PFS_FIO_ATTR_WRITEABLE, pfsCacheFlushAllDirty(), pfsFioCheckFileSlot(), pfsFioCheckForLastError(), pfsFioSema, pfs_cache_t::pfsMount, pfs_file_slot_t::position, iop_file_t::privdata, result, and SignalSema().