ps2sdk: iop/hdd/pfs/src/pfs.c File Reference
pfs.c File Reference
#include <stdio.h>
#include <sysclib.h>
#include <loadcore.h>
#include <irx.h>
#include <iomanX.h>
#include <errno.h>
#include <thsemap.h>
#include "pfs-opt.h"
#include "libpfs.h"
#include "pfs.h"
#include "pfs_fio.h"
#include "pfs_fioctl.h"
Functions
IRX_ID ("pfs_driver", PFS_MAJOR, PFS_MINOR)
static int printPfsArgError (void)
static int allocateMountBuffer (int size)
void pfsClearMount (pfs_mount_t *pfsMount)
pfs_mount_t * pfsGetMountedUnit (s32 unit)
int _start (int argc, char *argv[])
Variables
iop_device_ops_t pfsOps
iop_device_t pfsFioDev
pfs_config_t pfsConfig = { 1, 2 }
pfs_mount_t * pfsMountBuf
char * pfsFilename = NULL
u32 pfsMetaSize
pfs_file_slot_t * pfsFileSlots
Function Documentation
_start()
int _start (int argc, char * argv[])
Definition at line 130 of file pfs.c.
 {
         char *filename;
         int number;
         int numBuf = 8;
         int reqBuf;
         int size, ret;
         PFS_PRINTF(PFS_DRV_NAME" Playstation Filesystem Driver v%d.%d\nps2fs: (c) 2003 Sjeep, Vector and Florin Sasu\n", PFS_MAJOR, PFS_MINOR);
         // Get filename of IRX
         filename = strrchr(argv[0], '/');
         if(filename++)
                 pfsFilename = filename;
         else
                 pfsFilename = argv[0];
         argc--;
         argv++;
         // Parse arguments
         while(argc > 0)
         {
                 if(argv[0][0] != '-')
                         break;
                 if(!strcmp(argv[0], "-m"))
                 {
                         if(--argc <= 0)
                                 return printPfsArgError();
                         argv++;
                         number = strtol(argv[0], 0, 10);
                         if(number <= 32)
                                 pfsConfig.maxMount = number;
                 }
                 else if(!strcmp(argv[0], "-o"))
                 {
                         if(--argc <= 0)
                                 return printPfsArgError();
                         argv++;
                         number = strtol(argv[0], NULL, 10);
                         if(number <= 32)
                                 pfsConfig.maxOpen = number;
                 }
                 else if(!strcmp(argv[0], "-n"))
                 {
                         if(--argc <= 0)
                                 return printPfsArgError();
                         argv++;
                         number = strtol(argv[0], NULL, 10);
                         if(number > numBuf)
                                 numBuf = number;
                         if(numBuf > 127) {
                                 PFS_PRINTF(PFS_DRV_NAME" ERROR: Number of buffers is larger than 127!\n");
                                 return -EINVAL;
                         }
                 }
                 else
                         return printPfsArgError();
                 argc--;
                 argv++;
         }
         PFS_PRINTF(PFS_DRV_NAME" Max mount: %ld, Max open: %ld, Number of buffers: %d\n", pfsConfig.maxMount,
                         pfsConfig.maxOpen, numBuf);
         // Do we have enough buffers ?
         reqBuf = (pfsConfig.maxOpen * 2) + 8;
         if(numBuf < reqBuf)
                 PFS_PRINTF(PFS_DRV_NAME" Warning: %d buffers may be needed, but only %d buffers are allocated\n", reqBuf, numBuf);
         if(allocateMountBuffer(pfsConfig.maxMount) < 0)
                 return MODULE_NO_RESIDENT_END;
         // Allocate and zero memory for file slots
         size = pfsConfig.maxOpen * sizeof(pfs_file_slot_t);
         pfsFileSlots = pfsAllocMem(size);
         ret = (pfsFileSlots == NULL) ? -ENOMEM : 0;
         if(ret != 0)
         {       //Official PFS module does not print an error message here.
                 PFS_PRINTF(PFS_DRV_NAME" Error: Failed to allocate memory for file descriptors!\n");
                 return MODULE_NO_RESIDENT_END;
         }
         memset(pfsFileSlots, 0, size);
         if(pfsCacheInit(numBuf, pfsMetaSize) < 0)
                 return MODULE_NO_RESIDENT_END;
         DelDrv("pfs");
         if(AddDrv(&pfsFioDev) == 0) {
 #ifdef PFS_OSD_VER
                 PFS_PRINTF(PFS_DRV_NAME" version %04x driver start. This is OSD version!\n", IRX_VER(PFS_MAJOR, PFS_MINOR));
 #else
                 PFS_PRINTF(PFS_DRV_NAME" version %04x driver start.\n", IRX_VER(PFS_MAJOR, PFS_MINOR));
 #endif
                 return MODULE_RESIDENT_END;
         }
         return MODULE_NO_RESIDENT_END;
 }
References AddDrv(), allocateMountBuffer(), DelDrv(), EINVAL, ENOMEM, IRX_VER, pfs_config_t::maxMount, pfs_config_t::maxOpen, memset(), MODULE_NO_RESIDENT_END, MODULE_RESIDENT_END, NULL, PFS_DRV_NAME, PFS_MAJOR, PFS_MINOR, PFS_PRINTF, pfsAllocMem(), pfsCacheInit(), pfsConfig, pfsFilename, pfsFileSlots, pfsFioDev, pfsMetaSize, printPfsArgError(), strcmp(), strrchr(), and strtol().
allocateMountBuffer()
static int allocateMountBuffer (int size) static
Definition at line 101 of file pfs.c.
 {
         int tsize = size * sizeof(pfs_mount_t);
         pfsMountBuf = pfsAllocMem(tsize);
         if(!pfsMountBuf)
                 return -ENOMEM;
         memset(pfsMountBuf, 0, tsize);
         return 0;
 }
References ENOMEM, memset(), pfsAllocMem(), and pfsMountBuf.
Referenced by _start().
IRX_ID()
IRX_ID ("pfs_driver" , PFS_MAJOR , PFS_MINOR)
pfsClearMount()
void pfsClearMount (pfs_mount_t * pfsMount)
Definition at line 114 of file pfs.c.
 {
         memset(pfsMount, 0, sizeof(pfs_mount_t));
 }
References memset().
Referenced by pfsFioUmount().
pfsGetMountedUnit()
pfs_mount_t* pfsGetMountedUnit (s32 unit)
Definition at line 119 of file pfs.c.
 {       // get mounted unit
         if(unit>=pfsConfig.maxMount)
                 return NULL;
         if(!(pfsMountBuf[unit].flags & PFS_MOUNT_BUSY))
                 return NULL;
         return &pfsMountBuf[unit];
 }
References pfs_config_t::maxMount, NULL, PFS_MOUNT_BUSY, pfsConfig, and pfsMountBuf.
Referenced by pfsFioDevctlCloseAll(), and pfsFioGetMountedUnit().
printPfsArgError()
static int printPfsArgError (void) static
Definition at line 94 of file pfs.c.
 {
         PFS_PRINTF(PFS_DRV_NAME" ERROR: Usage: %s [-m <maxmount>] [-o <maxopen>] [-n <numbuffer>]\n", pfsFilename);
         return MODULE_NO_RESIDENT_END;
 }
References MODULE_NO_RESIDENT_END, PFS_DRV_NAME, PFS_PRINTF, and pfsFilename.
Referenced by _start().
Variable Documentation
pfsConfig
pfs_config_t pfsConfig = { 1, 2 }
Definition at line 77 of file pfs.c.
Referenced by _start(), _sync(), fileTransferRemainder(), mountDevice(), pfsFioDevctlCloseAll(), pfsFioOpen(), pfsFioUmount(), and pfsGetMountedUnit().
pfsFilename
char* pfsFilename = NULL
Definition at line 79 of file pfs.c.
Referenced by _start(), and printPfsArgError().
pfsFileSlots
pfs_file_slot_t* pfsFileSlots extern
Definition at line 35 of file pfs_fio.c.
Referenced by _start().
pfsFioDev
iop_device_t pfsFioDev
Initial value:
= {
        "pfs",
        (IOP_DT_FS | IOP_DT_FSEXT),
        1,
        "PFS",
        &pfsOps
}
Definition at line 69 of file pfs.c.
Referenced by _start().
pfsMetaSize
u32 pfsMetaSize extern
Definition at line 26 of file super.c.
Referenced by _start().
pfsMountBuf
pfs_mount_t* pfsMountBuf
Definition at line 78 of file pfs.c.
Referenced by allocateMountBuffer(), mountDevice(), and pfsGetMountedUnit().
pfsOps
iop_device_ops_t pfsOps
Initial value:
= {
        pfsFioInit,
        pfsFioDeinit,
        pfsFioFormat,
        pfsFioOpen,
        pfsFioClose,
        pfsFioRead,
        pfsFioWrite,
        pfsFioLseek,
        pfsFioIoctl,
        pfsFioRemove,
        pfsFioMkdir,
        pfsFioRmdir,
        pfsFioDopen,
        pfsFioClose,
        pfsFioDread,
        pfsFioGetstat,
        pfsFioChstat,
        pfsFioRename,
        pfsFioChdir,
        pfsFioSync,
        pfsFioMount,
        pfsFioUmount,
        pfsFioLseek64,
        pfsFioDevctl,
        pfsFioSymlink,
        pfsFioReadlink,
        pfsFioIoctl2
}
Definition at line 39 of file pfs.c.