ps2sdk: iop/dev9/poweroff/include/poweroff.h File Reference
poweroff.h File Reference
#include <irx.h>
Macros
#define poweroff_IMPORTS_start DECLARE_IMPORT_TABLE(poweroff, 1, 1)
#define poweroff_IMPORTS_end END_IMPORT_TABLE
#define I_SetPowerButtonHandler DECLARE_IMPORT(4, SetPowerButtonHandler)
#define I_AddPowerOffHandler DECLARE_IMPORT(5, AddPowerOffHandler)
#define I_RemovePowerOffHandler DECLARE_IMPORT(6, RemovePowerOffHandler)
#define I_PoweroffShutdown DECLARE_IMPORT(7, PoweroffShutdown)
Typedefs
typedef void(* pwoffcb) (void *)
Functions
void SetPowerButtonHandler (pwoffcb func, void *param)
void AddPowerOffHandler (pwoffcb func, void *param)
void RemovePowerOffHandler (pwoffcb func)
void PoweroffShutdown ()
Detailed Description
Power-off processing definitions and imports.
Definition in file poweroff.h.
Macro Definition Documentation
I_AddPowerOffHandler
#define I_AddPowerOffHandler DECLARE_IMPORT(5, AddPowerOffHandler)
Definition at line 32 of file poweroff.h.
I_PoweroffShutdown
#define I_PoweroffShutdown DECLARE_IMPORT(7, PoweroffShutdown)
Definition at line 34 of file poweroff.h.
I_RemovePowerOffHandler
#define I_RemovePowerOffHandler DECLARE_IMPORT(6, RemovePowerOffHandler)
Definition at line 33 of file poweroff.h.
I_SetPowerButtonHandler
#define I_SetPowerButtonHandler DECLARE_IMPORT(4, SetPowerButtonHandler)
Definition at line 31 of file poweroff.h.
poweroff_IMPORTS_end
#define poweroff_IMPORTS_end END_IMPORT_TABLE
Definition at line 29 of file poweroff.h.
poweroff_IMPORTS_start
#define poweroff_IMPORTS_start DECLARE_IMPORT_TABLE(poweroff, 1, 1)
Definition at line 28 of file poweroff.h.
Typedef Documentation
pwoffcb
typedef void(* pwoffcb) (void *)
Definition at line 21 of file poweroff.h.
Function Documentation
AddPowerOffHandler()
void AddPowerOffHandler (pwoffcb func, void * param)
Definition at line 146 of file poweroff.c.
 {
         int i;
         for(i = 0; i < MAX_CALLBACKS; i++)
         {
                 if(CallbackTable[i].cb == 0)
                 {
                         CallbackTable[i].cb = func;
                         CallbackTable[i].data = param;
 #ifdef DEBUG
                         printf("Added callback at position %d\n", i);
 #endif
                         break;
                 }
         }
         if(i == MAX_CALLBACKS)
         {
                 printf("Could not add poweroff callback\n");
         }
 }
References CallbackTable, CallbackEntry::cb, CallbackEntry::data, MAX_CALLBACKS, and printf().
PoweroffShutdown()
void PoweroffShutdown ()
Definition at line 191 of file poweroff.c.
 {
         Shutdown(0);
 }
References Shutdown().
RemovePowerOffHandler()
void RemovePowerOffHandler (pwoffcb func)
Definition at line 169 of file poweroff.c.
 {
         int i;
         for(i = 0; i < MAX_CALLBACKS; i++)
         {
                 if(CallbackTable[i].cb == func)
                 {
                         break;
                 }
         }
         if(i < MAX_CALLBACKS)
         {
                 for(; i < (MAX_CALLBACKS-1); i++)
                 {
                         CallbackTable[i] = CallbackTable[i+1];
                 }
                 memset(&CallbackTable[i], 0, sizeof(struct CallbackEntry));
         }
 }
References CallbackTable, MAX_CALLBACKS, and memset().
SetPowerButtonHandler()
void SetPowerButtonHandler (pwoffcb func, void * param)
Definition at line 140 of file poweroff.c.
 {
         poweroff_button_cb = func;
         poweroff_button_data = param;
 }
References poweroff_button_cb, and poweroff_button_data.
Referenced by _start(), and poweroff_rpc_server().