ps2sdk: iop/dev9/poweroff/src/poweroff.c File Reference
poweroff.c File Reference
#include "types.h"
#include "defs.h"
#include "irx.h"
#include "loadcore.h"
#include "sysmem.h"
#include "stdio.h"
#include "sysclib.h"
#include "sifcmd.h"
#include "thbase.h"
#include "intrman.h"
#include "thsemap.h"
#include "poweroff.h"
#include "pwroff_rpc.h"
Data Structures
struct handlerTableEntry
struct CallbackEntry
Macros
#define TYPE_C 1
#define CDVDreg_PWOFF (*(volatile unsigned char*)0xBF402008)
#define MAX_CALLBACKS 8
Typedefs
typedef int(* intrhandler) (void *)
Functions
IRX_ID ("Poweroff_Handler", 1, 1)
int _start (int, char **)
static void Shutdown ()
static void SendCmd (void *data)
static int myCdHandler (void *param)
static void Shutdown (void *data)
static void PowerOffThread (void *arg)
static void InitPowerOffThread (void)
void SetPowerButtonHandler (pwoffcb func, void *param)
void AddPowerOffHandler (pwoffcb func, void *param)
void RemovePowerOffHandler (pwoffcb func)
void PoweroffShutdown ()
void * poweroff_rpc_server (int fno, void *data, int size)
void poweroff_rpc_Thread (void *param)
int _start (int argc, char *argv[])
Variables
struct irx_export_table _exp_poweroff
static intrhandler oldCdHandler =0
struct CallbackEntry CallbackTable [MAX_CALLBACKS]
static char cmdData [16]
static pwoffcb poweroff_button_cb = 0
static void * poweroff_button_data = 0
static struct t_SifRpcDataQueue qd
static struct t_SifRpcServerData sd0
static int PowerOffThreadID = -1
static SifRpcClientData_t client
Macro Definition Documentation
CDVDreg_PWOFF
#define CDVDreg_PWOFF (*(volatile unsigned char*)0xBF402008)
Definition at line 29 of file poweroff.c.
MAX_CALLBACKS
#define MAX_CALLBACKS 8
Definition at line 31 of file poweroff.c.
TYPE_C
#define TYPE_C 1
Definition at line 28 of file poweroff.c.
Typedef Documentation
intrhandler
typedef int(* intrhandler) (void *)
Definition at line 44 of file poweroff.c.
Function Documentation
_start()
int _start (int argc, char * argv[])
Definition at line 226 of file poweroff.c.
 {
         register struct handlerTableEntry *handlers=(struct handlerTableEntry*)0x480;//iopmem
         iop_thread_t mythread;
         int i;
         if(RegisterLibraryEntries(&_exp_poweroff) != 0)
         {
                 printf("Poweroff already registered\n");
                 return 1;
         }
         SetPowerButtonHandler(Shutdown, 0);
         if (handlers[IOP_IRQ_CDVD].handler==0) {
                 printf("No CDROM handler. Run CDVDMAN first\n");
                 return 1;
         }
         if (((int)handlers[IOP_IRQ_CDVD].handler & 3) != TYPE_C){
                 printf("Cannot chain to non-C handler\n");
                 return 1;
         }
         oldCdHandler=(intrhandler)((int)handlers[IOP_IRQ_CDVD].handler & ~3);
         handlers[IOP_IRQ_CDVD].handler=(intrhandler)((int)myCdHandler | TYPE_C);
         memset(CallbackTable, 0, sizeof(struct CallbackEntry) * MAX_CALLBACKS);
         mythread.attr = TH_C;
         mythread.option = PWROFF_IRX;
         mythread.thread = poweroff_rpc_Thread;
         mythread.stacksize = 0x1000;
         mythread.priority = 0x27;
         int pid = CreateThread(&mythread);
         if (pid > 0) {
                 if ((i=StartThread(pid, NULL)) < 0) {
                         printf("StartThread failed (%d)\n", i);
                         return MODULE_NO_RESIDENT_END;
                 }
         }
         else {
                 printf("CreateThread failed (%d)\n", pid);
                 return MODULE_NO_RESIDENT_END;
         }
         printf("Poweroff installed\n");
         return MODULE_RESIDENT_END;
 }
References _exp_poweroff, iop_thread_t::attr, CallbackTable, CreateThread(), handler, handlers, IOP_IRQ_CDVD, MAX_CALLBACKS, memset(), MODULE_NO_RESIDENT_END, MODULE_RESIDENT_END, myCdHandler(), NULL, oldCdHandler, iop_thread_t::option, poweroff_rpc_Thread(), printf(), iop_thread_t::priority, PWROFF_IRX, RegisterLibraryEntries(), SetPowerButtonHandler(), Shutdown(), iop_thread_t::stacksize, StartThread(), TH_C, iop_thread_t::thread, and TYPE_C.
AddPowerOffHandler()
void AddPowerOffHandler (pwoffcb func, void * param)
Definition at line 146 of file poweroff.c.
 {
         int i;
         for(i = 0; i < MAX_CALLBACKS; i++)
         {
                 if(CallbackTable[i].cb == 0)
                 {
                         CallbackTable[i].cb = func;
                         CallbackTable[i].data = param;
 #ifdef DEBUG
                         printf("Added callback at position %d\n", i);
 #endif
                         break;
                 }
         }
         if(i == MAX_CALLBACKS)
         {
                 printf("Could not add poweroff callback\n");
         }
 }
References CallbackTable, CallbackEntry::cb, CallbackEntry::data, MAX_CALLBACKS, and printf().
InitPowerOffThread()
static void InitPowerOffThread (void) static
Definition at line 117 of file poweroff.c.
 {
         iop_thread_t thread;
         if(PowerOffThreadID < 0)
         {
                 thread.thread = &PowerOffThread;
                 thread.attr = TH_C;
                 thread.option = PWROFF_IRX;
                 thread.stacksize = 0x400;
                 thread.priority = 0x27;
                 PowerOffThreadID = CreateThread(&thread);
                 StartThread(PowerOffThreadID, NULL);
                 client.server = NULL;
                 while(sceSifBindRpc(&client, PWROFF_IRX, 0) < 0 || client.server == NULL) DelayThread(500);
         }
 }
References iop_thread_t::attr, client, CreateThread(), DelayThread(), NULL, iop_thread_t::option, PowerOffThread(), PowerOffThreadID, iop_thread_t::priority, PWROFF_IRX, sceSifBindRpc(), SifRpcClientData_t::server, iop_thread_t::stacksize, StartThread(), TH_C, and iop_thread_t::thread.
Referenced by poweroff_rpc_server().
IRX_ID()
IRX_ID ("Poweroff_Handler" , 1 , 1)
myCdHandler()
static int myCdHandler (void * param) static
Definition at line 69 of file poweroff.c.
 {
         if (((CDVDreg_PWOFF & 1)==0) && (CDVDreg_PWOFF & 4))
         {
                 /* can't seem to register a sif cmd callback in ps2link so... */
                 /* Clear interrupt bit */
                 CDVDreg_PWOFF = 4;
 #ifdef DEBUG
                 printf("Poweroff!!!! %08x\n", CDVDreg_PWOFF);
 #endif
                 if (poweroff_button_cb)
                         poweroff_button_cb(poweroff_button_data);
         }
         return oldCdHandler(param);
 }
References CDVDreg_PWOFF, oldCdHandler, poweroff_button_cb, poweroff_button_data, and printf().
Referenced by _start().
poweroff_rpc_server()
void* poweroff_rpc_server (int fno, void * data, int size)
Definition at line 196 of file poweroff.c.
 {
         switch(fno) {
         case PWROFF_SHUTDOWN:
                 Shutdown(0);
                 break;
         case PWROFF_ENABLE_AUTO_SHUTOFF:
                 InitPowerOffThread();
                 int* sbuff = data;
                 if (sbuff[0])
                         SetPowerButtonHandler(Shutdown, 0);
                 else
                         SetPowerButtonHandler(SendCmd, 0);
                 sbuff[0] = 1;
                 return sbuff;
         }
         return NULL;
 }
References InitPowerOffThread(), NULL, PWROFF_ENABLE_AUTO_SHUTOFF, PWROFF_SHUTDOWN, SendCmd(), SetPowerButtonHandler(), and Shutdown().
Referenced by poweroff_rpc_Thread().
poweroff_rpc_Thread()
void poweroff_rpc_Thread (void * param)
Definition at line 217 of file poweroff.c.
 {
         SifInitRpc(0);
         SifSetRpcQueue(&qd, GetThreadId());
         SifRegisterRpc(&sd0, PWROFF_IRX, poweroff_rpc_server, cmdData, NULL, NULL, &qd);
         SifRpcLoop(&qd);
 }
References cmdData, GetThreadId(), NULL, poweroff_rpc_server(), PWROFF_IRX, qd, sd0, SifInitRpc, SifRegisterRpc, SifRpcLoop, and SifSetRpcQueue.
Referenced by _start().
PoweroffShutdown()
void PoweroffShutdown ()
Definition at line 191 of file poweroff.c.
 {
         Shutdown(0);
 }
References Shutdown().
PowerOffThread()
static void PowerOffThread (void * arg) static
Definition at line 111 of file poweroff.c.
 {
         SleepThread();
         sceSifCallRpc(&client, POFF_RPC_BUTTON, 0, NULL, 0, NULL, 0, NULL, NULL);
 }
References client, NULL, POFF_RPC_BUTTON, sceSifCallRpc(), and SleepThread().
Referenced by InitPowerOffThread().
RemovePowerOffHandler()
void RemovePowerOffHandler (pwoffcb func)
Definition at line 169 of file poweroff.c.
 {
         int i;
         for(i = 0; i < MAX_CALLBACKS; i++)
         {
                 if(CallbackTable[i].cb == func)
                 {
                         break;
                 }
         }
         if(i < MAX_CALLBACKS)
         {
                 for(; i < (MAX_CALLBACKS-1); i++)
                 {
                         CallbackTable[i] = CallbackTable[i+1];
                 }
                 memset(&CallbackTable[i], 0, sizeof(struct CallbackEntry));
         }
 }
References CallbackTable, MAX_CALLBACKS, and memset().
SendCmd()
static void SendCmd (void * data) static
Definition at line 106 of file poweroff.c.
 {
         iWakeupThread(PowerOffThreadID);
 }
References iWakeupThread(), and PowerOffThreadID.
Referenced by poweroff_rpc_server().
SetPowerButtonHandler()
void SetPowerButtonHandler (pwoffcb func, void * param)
Definition at line 140 of file poweroff.c.
 {
         poweroff_button_cb = func;
         poweroff_button_data = param;
 }
References poweroff_button_cb, and poweroff_button_data.
Referenced by _start(), and poweroff_rpc_server().
Shutdown() [1/2]
static void Shutdown () static
Referenced by _start(), poweroff_rpc_server(), and PoweroffShutdown().
Shutdown() [2/2]
static void Shutdown (void * data) static
Definition at line 86 of file poweroff.c.
 {
 #ifdef DEBUG
         printf("Shutdown\n");
 #endif
         int i;
         /* Do callbacks in reverse order */
         for(i = MAX_CALLBACKS-1; i >= 0; i--)
         {
                 if(CallbackTable[i].cb)
                 {
                         CallbackTable[i].cb(CallbackTable[i].data);
                 }
         }
         // Turn off PS2
         *((unsigned char *)0xBF402017) = 0;
         *((unsigned char *)0xBF402016) = 0xF;
 }
References CallbackTable, CallbackEntry::cb, MAX_CALLBACKS, and printf().
Variable Documentation
_exp_poweroff
struct irx_export_table _exp_poweroff extern
Referenced by _start().
CallbackTable
struct CallbackEntry CallbackTable[MAX_CALLBACKS]
Referenced by _start(), AddPowerOffHandler(), RemovePowerOffHandler(), and Shutdown().
client
SifRpcClientData_t client static
Definition at line 67 of file poweroff.c.
Referenced by InitPowerOffThread(), and PowerOffThread().
cmdData
char cmdData[16] static
Definition at line 61 of file poweroff.c.
Referenced by poweroff_rpc_Thread().
oldCdHandler
intrhandler oldCdHandler =0 static
Definition at line 46 of file poweroff.c.
Referenced by _start(), and myCdHandler().
poweroff_button_cb
pwoffcb poweroff_button_cb = 0 static
Definition at line 62 of file poweroff.c.
Referenced by myCdHandler(), and SetPowerButtonHandler().
poweroff_button_data
void* poweroff_button_data = 0 static
Definition at line 63 of file poweroff.c.
Referenced by myCdHandler(), and SetPowerButtonHandler().
PowerOffThreadID
int PowerOffThreadID = -1 static
Definition at line 66 of file poweroff.c.
Referenced by InitPowerOffThread(), and SendCmd().
qd
struct t_SifRpcDataQueue qd static
Definition at line 63 of file poweroff.c.
Referenced by poweroff_rpc_Thread().
sd0
struct t_SifRpcServerData sd0 static
Definition at line 63 of file poweroff.c.
Referenced by poweroff_rpc_Thread().