ps2sdk: iop/fs/netfs/src/ps2_fio.c File Reference
ps2_fio.c File Reference
#include <types.h>
#include <defs.h>
#include <irx.h>
#include <loadcore.h>
#include <ioman_mod.h>
#include <iomanX.h>
#include <thbase.h>
#include <thsemap.h>
#include <stdio.h>
#include <sysclib.h>
#include <errno.h>
#include <ps2ip.h>
#include <iopmgr.h>
#include "ps2_fio.h"
#include "ps2fs.h"
#include "byteorder.h"
#include "devscan.h"
Data Structures
struct fd_table_t
Macros
#define dbgprintf(args...) do { } while(0)
#define PACKET_MAXSIZE 4096
#define FIOTRAN_MAXSIZE 65535
#define FDH_MAX 50
#define fdh_get(a) (&fd_info_list[a])
#define fdh_getused(a) (fd_info_list[a].used)
#define fdh_getfdtype(a) (fd_info_list[a].devtype)
#define fdh_getrealfd(a) (fd_info_list[a].realfd)
#define PFS_ZONE_SIZE 8192
#define PFS_FRAGMENT 0x00000000
Functions
int fsysUnmount (void)
static void fdh_setup ()
static int fdh_getfd (int devtype, int fd)
static void fdh_freefd (int fd)
static int convmode_to_iomanx (int stat)
static int convmode_from_iomanx (int stat)
int ps2netfs_close_socket (void)
void ps2netfs_close_fsys (void)
static int ps2netfs_lwip_send (int sock, void *buf, int len, int flag)
int ps2netfs_recv_bytes (int sock, char *buf, int bytes)
int ps2netfs_accept_pktunknown (int sock, char *buf)
static int ps2netfs_op_info (char *buf, int len)
static int ps2netfs_op_fstype (char *buf, int len)
static int ps2netfs_op_devlist (char *buf, int len)
static int ps2netfs_op_open (char *buf, int len)
static int ps2netfs_op_close (char *buf, int len)
static int ps2netfs_op_read (char *buf, int len)
static int ps2netfs_op_write (char *buf, int len)
static int ps2netfs_op_lseek (char *buf, int len)
static int ps2netfs_op_ioctl (char *buf, int len)
static int ps2netfs_op_remove (char *buf, int len)
static int ps2netfs_op_mkdir (char *buf, int len)
static int ps2netfs_op_rmdir (char *buf, int len)
static int ps2netfs_op_dopen (char *buf, int len)
static int ps2netfs_op_dclose (char *buf, int len)
static int ps2netfs_op_dread (char *buf, int len)
static int ps2netfs_op_getstat (char *buf, int len)
static int ps2netfs_op_chstat (char *buf, int len)
static int ps2netfs_op_format (char *buf, int len)
static int ps2netfs_op_rename (char *buf, int len)
static int ps2netfs_op_chdir (char *buf, int len)
static int ps2netfs_op_sync (char *buf, int len)
static int ps2netfs_op_mount (char *buf, int len)
static int ps2netfs_op_umount (char *buf, int len)
static int ps2netfs_op_lseek64 (char *buf, int len)
static int ps2netfs_op_devctl (char *buf, int len)
static int ps2netfs_op_symlink (char *buf, int len)
static int ps2netfs_op_readlink (char *buf, int len)
static int ps2netfs_op_ioctl2 (char *buf, int len)
static void ps2netfs_Listener (int sock)
int ps2netfs_serv (void *argv)
int ps2netfs_Init (void)
int ps2fs_Destroy (void)
Variables
static char ps2netfs_send_packet [PACKET_MAXSIZE]
static char ps2netfs_recv_packet [PACKET_MAXSIZE]
static int ps2netfs_sock = -1
static int ps2netfs_active = 0
static int ps2netfs_sema
static int ps2netfs_pid = 0
static char ps2netfs_fiobuffer [FIOTRAN_MAXSIZE+1]
static fd_table_t fd_info_list [FDH_MAX+1]
Detailed Description
iop tcp fs driver.
Definition in file ps2_fio.c.
Macro Definition Documentation
dbgprintf
#define dbgprintf (args...) do { } while(0)
Definition at line 41 of file ps2_fio.c.
fdh_get
#define fdh_get (a) (&fd_info_list[a])
Get fd list entry.
Definition at line 135 of file ps2_fio.c.
fdh_getfdtype
#define fdh_getfdtype (a) (fd_info_list[a].devtype)
Get fd list entry type value.
Definition at line 139 of file ps2_fio.c.
fdh_getrealfd
#define fdh_getrealfd (a) (fd_info_list[a].realfd)
Get fd list entry ps2 file descriptor value.
Definition at line 141 of file ps2_fio.c.
fdh_getused
#define fdh_getused (a) (fd_info_list[a].used)
Get fd list entry used value.
Definition at line 137 of file ps2_fio.c.
FDH_MAX
#define FDH_MAX 50
Definition at line 76 of file ps2_fio.c.
FIOTRAN_MAXSIZE
#define FIOTRAN_MAXSIZE 65535
Definition at line 60 of file ps2_fio.c.
PACKET_MAXSIZE
#define PACKET_MAXSIZE 4096
Definition at line 49 of file ps2_fio.c.
PFS_FRAGMENT
#define PFS_FRAGMENT 0x00000000
Definition at line 1300 of file ps2_fio.c.
Function Documentation
fsysUnmount()
int fsysUnmount (void)
ps2netfs_accept_pktunknown()
int ps2netfs_accept_pktunknown (int sock, char * buf)
Receive a 'packet' of unknown type, max size 4096 bytes
Definition at line 250 of file ps2_fio.c.
 {
   int length;
   ps2netfs_pkt_hdr *hdr;
 #ifdef DEBUG
   unsigned int hcmd;
 #endif
   unsigned short hlen;
   dbgprintf("ps2netfs: accept_pkt\n");
   length = ps2netfs_recv_bytes(sock, buf, sizeof(ps2netfs_pkt_hdr));
   if (length == 0) return 0;
   if (length < 0) {
     dbgprintf("ps2netfs: accept_pkt recv error\n");
     return -1;
   }
   if (length < sizeof(ps2netfs_pkt_hdr)) {
     dbgprintf("ps2netfs: XXX: did not receive a full header!!!! "
               "Fix this! (%d)\n", length);
     return -1;
   }
   hdr = (ps2netfs_pkt_hdr *)buf;
 #ifdef DEBUG
   hcmd = ntohl(hdr->cmd);
 #endif
   hlen = ntohs(hdr->len);
   dbgprintf("ps2netfs: accept_pkt: got 0x%x , hlen: %d, length: %d\n", hcmd,hlen,length);
   if ((length > PACKET_MAXSIZE) || (hlen > PACKET_MAXSIZE))
   {
     dbgprintf("ps2netfs: accept_pkt: hlen is too large!! "
               "(%d,%d can only receive %d)\n", length,hlen, PACKET_MAXSIZE);
     return -1;
   }
   // get the actual packet data
   length = ps2netfs_recv_bytes(sock, buf + sizeof(ps2netfs_pkt_hdr),
                                hlen - sizeof(ps2netfs_pkt_hdr));
   if (length < 0) {
     dbgprintf("ps2netfs: accept recv2 error!!\n");
     return -1;
   }
   if (length < (hlen - sizeof(ps2netfs_pkt_hdr))) {
     dbgprintf("ps2netfs: Did not receive full packet!!! "
               "Fix this! (%d)\n", length);
   }
   return hlen;
 }
References ps2netfs_pkt_hdr::cmd, dbgprintf, ps2netfs_pkt_hdr::len, ntohl, ntohs, PACKET_MAXSIZE, and ps2netfs_recv_bytes().
Referenced by ps2netfs_Listener().
ps2netfs_lwip_send()
static int ps2netfs_lwip_send (int sock, void * buf, int len, int flag) inline static
Definition at line 207 of file ps2_fio.c.
 {
   int ret;
   ret = send(sock, buf, len, flag);
   if (ret < 0)
   {
     dbgprintf("ps2netfs: lwip_send() error %d\n", ret);
     ps2netfs_close_socket();
     return -1;
   }
   else if (len == 0)
   { // send is blocking, so 0 means error
     dbgprintf("ps2netfs: lwip_send() - disconnected\n");
     return -2;
   }
   else return ret;
 }
References dbgprintf, ps2netfs_close_socket(), and send.
Referenced by ps2netfs_op_chdir(), ps2netfs_op_close(), ps2netfs_op_dclose(), ps2netfs_op_devlist(), ps2netfs_op_dopen(), ps2netfs_op_dread(), ps2netfs_op_format(), ps2netfs_op_fstype(), ps2netfs_op_info(), ps2netfs_op_ioctl(), ps2netfs_op_lseek(), ps2netfs_op_mkdir(), ps2netfs_op_mount(), ps2netfs_op_open(), ps2netfs_op_read(), ps2netfs_op_readlink(), ps2netfs_op_remove(), ps2netfs_op_rename(), ps2netfs_op_rmdir(), ps2netfs_op_symlink(), ps2netfs_op_sync(), ps2netfs_op_umount(), and ps2netfs_op_write().
ps2netfs_op_format()
static int ps2netfs_op_format (char * buf, int len) static
Definition at line 1301 of file ps2_fio.c.
 {
   ps2netfs_pkt_format_req *cmd;
   ps2netfs_pkt_file_rly *formatrly;
   int retval = -ENODEV;
   int devtype = 0;
   cmd = (ps2netfs_pkt_format_req *)buf;
   dbgprintf("ps2netfs: format\n");
   if (len != sizeof(ps2netfs_pkt_format_req))
   {
     dbgprintf("ps2netfs: got a broken packet (%d)!\n", len);
     return -1;
   }
   // do the stuff here
   devtype = devscan_gettype(cmd->dev);
   if (devtype == IOPMGR_DEVTYPE_IOMANX)
   { // if other end has not set args, add some standard ones (hdd use only for mo)
     if (ntohl(cmd->arglen) == 0)
     {
       int Arg[3] = { PFS_ZONE_SIZE, 0x2d66, PFS_FRAGMENT };
       retval = format(cmd->dev,cmd->blockdev,(char*)&Arg,sizeof(Arg));
     }
     else retval = format(cmd->dev,cmd->blockdev,cmd->arg,ntohl(cmd->arglen));
   }
   // now build the response
   formatrly = (ps2netfs_pkt_file_rly *)&ps2netfs_send_packet[0];
   // Build packet
   formatrly->cmd = htonl(PS2NETFS_FORMAT_RLY);
   formatrly->len = htons((unsigned short)sizeof(ps2netfs_pkt_file_rly));
   formatrly->retval = htonl(retval);
   if (ps2netfs_lwip_send(ps2netfs_sock, formatrly, sizeof(ps2netfs_pkt_file_rly), 0) < 0)
   {
     dbgprintf("ps2netfs: error sending reply!\n");
     return -1;
   }
   return 0;
 }
References ps2netfs_pkt_format_req::arg, ps2netfs_pkt_format_req::arglen, ps2netfs_pkt_format_req::blockdev, ps2netfs_pkt_file_rly::cmd, dbgprintf, ps2netfs_pkt_format_req::dev, devscan_gettype(), ENODEV, format(), htonl(), htons(), IOPMGR_DEVTYPE_IOMANX, ps2netfs_pkt_file_rly::len, ntohl, PFS_FRAGMENT, PFS_ZONE_SIZE, PS2NETFS_FORMAT_RLY, ps2netfs_lwip_send(), ps2netfs_send_packet, ps2netfs_sock, and ps2netfs_pkt_file_rly::retval.
Referenced by ps2netfs_Listener().
ps2netfs_recv_bytes()
int ps2netfs_recv_bytes (int sock, char * buf, int bytes)
Do repetetive recv() calls until 'bytes' bytes are received or error returned
Definition at line 226 of file ps2_fio.c.
 {
   int left;
   int len;
   left = bytes;
   while (left > 0) {
     len = recv(sock, &buf[bytes - left], left, 0);
     if (len < 0) {
       dbgprintf("ps2netfs: recv_bytes error!! (%d)\n",len);
       return -1;
     }
     if (len == 0)
     { // recv is blocking, so 0 means error
       dbgprintf("ps2netfs: recv_bytes - disconnected\n");
       return -2;
     }
     left -= len;
   }
   return bytes;
 }
References dbgprintf, and recv.
Referenced by ps2netfs_accept_pktunknown(), and ps2netfs_op_write().
Variable Documentation
fd_info_list
fd_table_t fd_info_list[FDH_MAX+1] static
Definition at line 77 of file ps2_fio.c.
Referenced by fdh_freefd(), fdh_getfd(), and fdh_setup().
ps2netfs_active
int ps2netfs_active = 0 static
Definition at line 55 of file ps2_fio.c.
Referenced by ps2netfs_close_fsys(), and ps2netfs_serv().
ps2netfs_fiobuffer
char ps2netfs_fiobuffer[FIOTRAN_MAXSIZE+1] static
Definition at line 61 of file ps2_fio.c.
Referenced by ps2netfs_op_read(), and ps2netfs_op_write().
ps2netfs_pid
int ps2netfs_pid = 0 static
Definition at line 58 of file ps2_fio.c.
Referenced by ps2netfs_Init().
ps2netfs_recv_packet
char ps2netfs_recv_packet[PACKET_MAXSIZE] static
Definition at line 52 of file ps2_fio.c.
Referenced by ps2netfs_Listener().
ps2netfs_sema
int ps2netfs_sema static
Definition at line 57 of file ps2_fio.c.
Referenced by ps2fs_Destroy().
ps2netfs_send_packet
char ps2netfs_send_packet[PACKET_MAXSIZE] static
Definition at line 51 of file ps2_fio.c.
Referenced by ps2netfs_op_chdir(), ps2netfs_op_close(), ps2netfs_op_dclose(), ps2netfs_op_devlist(), ps2netfs_op_dopen(), ps2netfs_op_dread(), ps2netfs_op_format(), ps2netfs_op_fstype(), ps2netfs_op_info(), ps2netfs_op_ioctl(), ps2netfs_op_lseek(), ps2netfs_op_mkdir(), ps2netfs_op_mount(), ps2netfs_op_open(), ps2netfs_op_read(), ps2netfs_op_readlink(), ps2netfs_op_remove(), ps2netfs_op_rename(), ps2netfs_op_rmdir(), ps2netfs_op_symlink(), ps2netfs_op_sync(), ps2netfs_op_umount(), and ps2netfs_op_write().
ps2netfs_sock
int ps2netfs_sock = -1 static
Definition at line 54 of file ps2_fio.c.
Referenced by ps2netfs_close_fsys(), ps2netfs_close_socket(), ps2netfs_op_chdir(), ps2netfs_op_close(), ps2netfs_op_dclose(), ps2netfs_op_devlist(), ps2netfs_op_dopen(), ps2netfs_op_dread(), ps2netfs_op_format(), ps2netfs_op_fstype(), ps2netfs_op_info(), ps2netfs_op_ioctl(), ps2netfs_op_lseek(), ps2netfs_op_mkdir(), ps2netfs_op_mount(), ps2netfs_op_open(), ps2netfs_op_read(), ps2netfs_op_readlink(), ps2netfs_op_remove(), ps2netfs_op_rename(), ps2netfs_op_rmdir(), ps2netfs_op_symlink(), ps2netfs_op_sync(), ps2netfs_op_umount(), ps2netfs_op_write(), and ps2netfs_serv().