ps2sdk: iop/usb/camera/include/ps2cam.h File Reference
ps2cam.h File Reference
#include <types.h>
Data Structures
struct PS2CAM_DEVICE_INFO
struct CAMERA_DEVICE
struct PS2CAM_DEVICE_HANDLE
struct PS2CAM_DEVICE_CONFIG
struct EYETOY_FRAME_HEAD
Macros
#define PS2CAM_RPC_GETIRXVERSION 40
#define PS2CAM_RPC_INITIALIZE 41
#define PS2CAM_RPC_GETDEVCOUNT 42
#define PS2CAM_RPC_OPENDEVICE 43
#define PS2CAM_RPC_CLOSEDEVICE 44
#define PS2CAM_RPC_GETDEVSTATUS 45
#define PS2CAM_RPC_GETDEVINFO 46
#define PS2CAM_RPC_SETDEVBANDWIDTH 47
#define PS2CAM_RPC_READPACKET 48
#define PS2CAM_RPC_SETLEDMODE 49
#define PS2CAM_RPC_SETDEVCONFIG 50
#define PS2CAM_VEND_SONY 0x054C
#define PS2CAM_VEND_DLINK 0x05A9
#define PS2CAM_VEND_LOGITECH 0x0000
#define PS2CAM_PROD_EYETOY 0x0154
#define PS2CAM_PROD_EYETOY2 0x0155
#define PS2CAM_PROD_EYETOY3 0x0156
#define PS2CAM_PROD_EYETOY4 0x0157
#define PS2CAM_PROD_VISUALSTREAM 0x8519
#define EYETOY_IREG_H_SIZE 0x10
#define EYETOY_IREG_V_SIZE 0x11
#define EYETOY_IREG_X_OFFSETL 0x12
#define EYETOY_IREG_X_OFFSETH 0x13
#define EYETOY_IREG_Y_OFFSETL 0x14
#define EYETOY_IREG_Y_OFFSETH 0x15
#define EYETOY_IREG_DIVIDER 0x16
#define EYETOY_IREG_DFR 0x20
#define EYETOY_IREG_SR 0x21
#define EYETOY_IREG_FRAR 0x22
#define EYETOY_IREG_FORMAT 0x25
#define EYETOY_CREG_RESET0 0x50
#define EYETOY_CREG_RESET1 0x51
#define EYETOY_CREG_EN_CLK0 0x53
#define EYETOY_CREG_EN_CLK1 0x54
#define EYETOY_CREG_AUDIO_CLK 0x55
#define EYETOY_CREG_SNAPSHOT 0x57
#define EYETOY_CREG_PONOFF 0x58
#define EYETOY_CREG_CAMERA_CLK 0x59
#define EYETOY_CREG_CTRL1 0x5A
#define EYETOY_CREG_DEB_CLK 0x5B
#define EYETOY_CREG_CLK 0x5C
#define EYETOY_CREG_PWDN 0x5D
#define EYETOY_CREG_USR_DFN 0x5E
#define EYETOY_CREG_CTRL2 0x5F
#define EYETOY_CREG_INTERRUPT0 0x60
#define EYETOY_CREG_INTERRUPT1 0x61
#define EYETOY_CREG_MASK0 0x62
#define EYETOY_CREG_MASK1 0x63
#define EYETOY_CREG_VCI_R0 0x64
#define EYETOY_CREG_VCI_R1 0x65
#define EYETOY_CREG_ADC_CTRL 0x68
#define EYETOY_CREG_UC_CTRL 0x6D
#define EYETOY_GPIO_DATA_OUT0 0x71
#define EYETOY_GPIO_IO_CTRL0 0x72
#define EYETOY_ALTERNATE_SIZE_0 0x00
#define EYETOY_ALTERNATE_SIZE_384 0x01
#define EYETOY_ALTERNATE_SIZE_512 0x02
#define EYETOY_ALTERNATE_SIZE_768 0x03
#define EYETOY_ALTERNATE_SIZE_896 0x04
#define CAM_STATUS_NOTCONNECTED 0
#define CAM_STATUS_CONNECTED 1
#define CAM_STATUS_CONNECTEDREADY 2
#define CAM_CONFIG_MASK_DIMENSION 0x00000001
#define CAM_CONFIG_MASK_OFFSET 0x00000002
#define CAM_CONFIG_MASK_DIVIDER 0x00000004
#define CAM_CONFIG_MASK_FRAMERATE 0x00000008
#define CAM_ERROR_NONE (00)
#define CAM_ERROR_NOTINIT -(20)
#define CAM_ERROR_INVALIDDEVICE -(21)
#define CAM_ERROR_COMMUNKNOWN -(22)
#define CAM_ERROR_DEVNOTREADY -(23)
#define CAM_ERROR_NODEVICE -(24)
#define CAM_ERROR_BADRANGE -(25)
#define CAM_ERROR_UNKNOWN -(26)
#define CAM_ERROR_MAXHANDLE -(27)
#define CAM_ERROR_BADHANDLE -(28)
#define CAM_ERROR_DISCONNECTED -(29)
#define camSetDIVIDER(p, hdiv, en_lpf, vdiv, en_sa)
Functions
void rpcMainThread (void *param)
void * rpcCommandHandler (u32 command, void *buffer, int size)
int PS2CamInitDriver ()
int PS2CamProbe (int devId)
int PS2CamConnect (int devId)
int PS2CamDisconnect (int devId)
void PS2CamGetDeviceSring (CAMERA_DEVICE *dev, int index, char *str, int strmax)
void PS2CamCallback (int resultCode, int bytes, void *arg)
void PS2CamSetDeviceConfiguration (CAMERA_DEVICE *dev, int id)
void PS2CamInitializeNewDevice (CAMERA_DEVICE *argv)
void PS2CamSetDeviceDefaults (CAMERA_DEVICE *dev)
int PS2CamGetIRXVersion (void)
int PS2CamInit (int mode)
int PS2CamGetDeviceCount (void)
int PS2CamOpenDevice (int device_index)
int PS2CamCloseDevice (int handle)
int PS2CamGetDeviceInfo (int handle, int *info)
int setReg8 (CAMERA_DEVICE *dev, unsigned char reg_id, unsigned char value)
int getReg8 (CAMERA_DEVICE *dev, unsigned char reg_id, unsigned char *value)
int setReg8Mask (CAMERA_DEVICE *dev, unsigned char reg_id, unsigned char value, unsigned char mask)
int setReg16 (CAMERA_DEVICE *dev, unsigned char reg_id, unsigned short value)
int PS2CamSelectInterface (CAMERA_DEVICE *dev, int interface, int altSetting)
void camResetDevice (CAMERA_DEVICE *dev)
void camEnableAutoLaunch (CAMERA_DEVICE *dev)
void camDisableAutoLaunch (CAMERA_DEVICE *dev)
void camClearSnapButton (CAMERA_DEVICE *dev)
int camCheckAutoLaunch (CAMERA_DEVICE *dev)
void camEnableSystem (CAMERA_DEVICE *dev)
void camDisableSystem (CAMERA_DEVICE *dev)
void camResetUsb (CAMERA_DEVICE *dev)
void camSetUsbInit (CAMERA_DEVICE *dev)
void camSetUsbWork (CAMERA_DEVICE *dev)
void camTurnOnRedLed (CAMERA_DEVICE *dev)
void camTurnOffRedLed (CAMERA_DEVICE *dev)
void camBlockStream (CAMERA_DEVICE *dev)
void camStartStream (CAMERA_DEVICE *dev)
void camStopStream (CAMERA_DEVICE *dev)
int PS2CamReadPacket (int device_id)
int PS2CamGetDeviceStatus (int device_id)
int PS2CamSetDeviceBandwidth (int device_id, char bandwidth)
int PS2CamSetLEDMode (int device_id, int mode)
int PS2CamSetDeviceConfig (int handle, void *config)
Detailed Description
PS2Camera driver irx
Definition in file ps2cam.h.
Macro Definition Documentation
CAM_CONFIG_MASK_DIMENSION
#define CAM_CONFIG_MASK_DIMENSION 0x00000001
Definition at line 117 of file ps2cam.h.
CAM_CONFIG_MASK_DIVIDER
#define CAM_CONFIG_MASK_DIVIDER 0x00000004
Definition at line 119 of file ps2cam.h.
CAM_CONFIG_MASK_FRAMERATE
#define CAM_CONFIG_MASK_FRAMERATE 0x00000008
Definition at line 120 of file ps2cam.h.
CAM_CONFIG_MASK_OFFSET
#define CAM_CONFIG_MASK_OFFSET 0x00000002
Definition at line 118 of file ps2cam.h.
CAM_ERROR_BADHANDLE
#define CAM_ERROR_BADHANDLE -(28)
invalid device handle
Definition at line 140 of file ps2cam.h.
CAM_ERROR_BADRANGE
#define CAM_ERROR_BADRANGE -(25)
a value was out of range
Definition at line 134 of file ps2cam.h.
CAM_ERROR_COMMUNKNOWN
#define CAM_ERROR_COMMUNKNOWN -(22)
unknown command
Definition at line 128 of file ps2cam.h.
CAM_ERROR_DEVNOTREADY
#define CAM_ERROR_DEVNOTREADY -(23)
device not ready
Definition at line 130 of file ps2cam.h.
CAM_ERROR_DISCONNECTED
#define CAM_ERROR_DISCONNECTED -(29)
device was removed
Definition at line 142 of file ps2cam.h.
CAM_ERROR_INVALIDDEVICE
#define CAM_ERROR_INVALIDDEVICE -(21)
Definition at line 126 of file ps2cam.h.
CAM_ERROR_MAXHANDLE
#define CAM_ERROR_MAXHANDLE -(27)
out of free device handle(s)
Definition at line 138 of file ps2cam.h.
CAM_ERROR_NODEVICE
#define CAM_ERROR_NODEVICE -(24)
no compatible device connected
Definition at line 132 of file ps2cam.h.
CAM_ERROR_NONE
#define CAM_ERROR_NONE (00)
ok
Definition at line 124 of file ps2cam.h.
CAM_ERROR_NOTINIT
#define CAM_ERROR_NOTINIT -(20)
Definition at line 125 of file ps2cam.h.
CAM_ERROR_UNKNOWN
#define CAM_ERROR_UNKNOWN -(26)
unknown error
Definition at line 136 of file ps2cam.h.
CAM_STATUS_CONNECTED
#define CAM_STATUS_CONNECTED 1
connected but initializing
Definition at line 112 of file ps2cam.h.
CAM_STATUS_CONNECTEDREADY
#define CAM_STATUS_CONNECTEDREADY 2
connect & ready for commands
Definition at line 114 of file ps2cam.h.
CAM_STATUS_NOTCONNECTED
#define CAM_STATUS_NOTCONNECTED 0
device not connected
Definition at line 110 of file ps2cam.h.
camSetDIVIDER
#define camSetDIVIDER (p, hdiv, en_lpf, vdiv, en_sa)
Value:
                                                                                                                        setReg8((p), EYETOY_IREG_DIVIDER,        \
                                                                                                                        ((unsigned char)(hdiv)          <<0)|\
                                                                                                                        ((unsigned char)(en_lpf)        <<3)|\
                                                                                                                        ((unsigned char)(vdiv)          <<4)|\
                                                                                                                        ((unsigned char)(en_sa)         <<7));
Definition at line 230 of file ps2cam.h.
EYETOY_ALTERNATE_SIZE_0
#define EYETOY_ALTERNATE_SIZE_0 0x00
xfer disable
Definition at line 102 of file ps2cam.h.
EYETOY_ALTERNATE_SIZE_384
#define EYETOY_ALTERNATE_SIZE_384 0x01
Definition at line 103 of file ps2cam.h.
EYETOY_ALTERNATE_SIZE_512
#define EYETOY_ALTERNATE_SIZE_512 0x02
Definition at line 104 of file ps2cam.h.
EYETOY_ALTERNATE_SIZE_768
#define EYETOY_ALTERNATE_SIZE_768 0x03
Definition at line 105 of file ps2cam.h.
EYETOY_ALTERNATE_SIZE_896
#define EYETOY_ALTERNATE_SIZE_896 0x04
Definition at line 106 of file ps2cam.h.
EYETOY_CREG_ADC_CTRL
#define EYETOY_CREG_ADC_CTRL 0x68
Definition at line 93 of file ps2cam.h.
EYETOY_CREG_AUDIO_CLK
#define EYETOY_CREG_AUDIO_CLK 0x55
Definition at line 77 of file ps2cam.h.
EYETOY_CREG_CAMERA_CLK
#define EYETOY_CREG_CAMERA_CLK 0x59
Definition at line 80 of file ps2cam.h.
EYETOY_CREG_CLK
#define EYETOY_CREG_CLK 0x5C
Definition at line 83 of file ps2cam.h.
EYETOY_CREG_CTRL1
#define EYETOY_CREG_CTRL1 0x5A
Definition at line 81 of file ps2cam.h.
EYETOY_CREG_CTRL2
#define EYETOY_CREG_CTRL2 0x5F
Definition at line 86 of file ps2cam.h.
EYETOY_CREG_DEB_CLK
#define EYETOY_CREG_DEB_CLK 0x5B
Definition at line 82 of file ps2cam.h.
EYETOY_CREG_EN_CLK0
#define EYETOY_CREG_EN_CLK0 0x53
Definition at line 75 of file ps2cam.h.
EYETOY_CREG_EN_CLK1
#define EYETOY_CREG_EN_CLK1 0x54
Definition at line 76 of file ps2cam.h.
EYETOY_CREG_INTERRUPT0
#define EYETOY_CREG_INTERRUPT0 0x60
Definition at line 87 of file ps2cam.h.
EYETOY_CREG_INTERRUPT1
#define EYETOY_CREG_INTERRUPT1 0x61
Definition at line 88 of file ps2cam.h.
EYETOY_CREG_MASK0
#define EYETOY_CREG_MASK0 0x62
Definition at line 89 of file ps2cam.h.
EYETOY_CREG_MASK1
#define EYETOY_CREG_MASK1 0x63
Definition at line 90 of file ps2cam.h.
EYETOY_CREG_PONOFF
#define EYETOY_CREG_PONOFF 0x58
Definition at line 79 of file ps2cam.h.
EYETOY_CREG_PWDN
#define EYETOY_CREG_PWDN 0x5D
Definition at line 84 of file ps2cam.h.
EYETOY_CREG_RESET0
#define EYETOY_CREG_RESET0 0x50
Definition at line 73 of file ps2cam.h.
EYETOY_CREG_RESET1
#define EYETOY_CREG_RESET1 0x51
Definition at line 74 of file ps2cam.h.
EYETOY_CREG_SNAPSHOT
#define EYETOY_CREG_SNAPSHOT 0x57
Definition at line 78 of file ps2cam.h.
EYETOY_CREG_UC_CTRL
#define EYETOY_CREG_UC_CTRL 0x6D
Definition at line 94 of file ps2cam.h.
EYETOY_CREG_USR_DFN
#define EYETOY_CREG_USR_DFN 0x5E
Definition at line 85 of file ps2cam.h.
EYETOY_CREG_VCI_R0
#define EYETOY_CREG_VCI_R0 0x64
Definition at line 91 of file ps2cam.h.
EYETOY_CREG_VCI_R1
#define EYETOY_CREG_VCI_R1 0x65
Definition at line 92 of file ps2cam.h.
EYETOY_GPIO_DATA_OUT0
#define EYETOY_GPIO_DATA_OUT0 0x71
Definition at line 97 of file ps2cam.h.
EYETOY_GPIO_IO_CTRL0
#define EYETOY_GPIO_IO_CTRL0 0x72
Definition at line 98 of file ps2cam.h.
EYETOY_IREG_DFR
#define EYETOY_IREG_DFR 0x20
Definition at line 68 of file ps2cam.h.
EYETOY_IREG_DIVIDER
#define EYETOY_IREG_DIVIDER 0x16
Definition at line 67 of file ps2cam.h.
EYETOY_IREG_FORMAT
#define EYETOY_IREG_FORMAT 0x25
Definition at line 71 of file ps2cam.h.
EYETOY_IREG_FRAR
#define EYETOY_IREG_FRAR 0x22
Definition at line 70 of file ps2cam.h.
EYETOY_IREG_H_SIZE
#define EYETOY_IREG_H_SIZE 0x10
Definition at line 61 of file ps2cam.h.
EYETOY_IREG_SR
#define EYETOY_IREG_SR 0x21
Definition at line 69 of file ps2cam.h.
EYETOY_IREG_V_SIZE
#define EYETOY_IREG_V_SIZE 0x11
Definition at line 62 of file ps2cam.h.
EYETOY_IREG_X_OFFSETH
#define EYETOY_IREG_X_OFFSETH 0x13
Definition at line 64 of file ps2cam.h.
EYETOY_IREG_X_OFFSETL
#define EYETOY_IREG_X_OFFSETL 0x12
Definition at line 63 of file ps2cam.h.
EYETOY_IREG_Y_OFFSETH
#define EYETOY_IREG_Y_OFFSETH 0x15
Definition at line 66 of file ps2cam.h.
EYETOY_IREG_Y_OFFSETL
#define EYETOY_IREG_Y_OFFSETL 0x14
Definition at line 65 of file ps2cam.h.
PS2CAM_PROD_EYETOY
#define PS2CAM_PROD_EYETOY 0x0154
SLEH-00030
Definition at line 49 of file ps2cam.h.
PS2CAM_PROD_EYETOY2
#define PS2CAM_PROD_EYETOY2 0x0155
SLEH-00031
Definition at line 51 of file ps2cam.h.
PS2CAM_PROD_EYETOY3
#define PS2CAM_PROD_EYETOY3 0x0156
SLEH-000?? rinco thinks its japan
Definition at line 53 of file ps2cam.h.
PS2CAM_PROD_EYETOY4
#define PS2CAM_PROD_EYETOY4 0x0157
SLEH-000?? ,, ,, ,,
Definition at line 55 of file ps2cam.h.
PS2CAM_PROD_VISUALSTREAM
#define PS2CAM_PROD_VISUALSTREAM 0x8519
D-Link VisualStream DSB-C310
Definition at line 58 of file ps2cam.h.
PS2CAM_RPC_CLOSEDEVICE
#define PS2CAM_RPC_CLOSEDEVICE 44
Definition at line 25 of file ps2cam.h.
PS2CAM_RPC_GETDEVCOUNT
#define PS2CAM_RPC_GETDEVCOUNT 42
PS2CamGetDeviceCount
Definition at line 23 of file ps2cam.h.
PS2CAM_RPC_GETDEVINFO
#define PS2CAM_RPC_GETDEVINFO 46
PS2CamGetInfo
Definition at line 29 of file ps2cam.h.
PS2CAM_RPC_GETDEVSTATUS
#define PS2CAM_RPC_GETDEVSTATUS 45
PS2CamGetStatus
Definition at line 27 of file ps2cam.h.
PS2CAM_RPC_GETIRXVERSION
#define PS2CAM_RPC_GETIRXVERSION 40
get irx version
Definition at line 19 of file ps2cam.h.
PS2CAM_RPC_INITIALIZE
#define PS2CAM_RPC_INITIALIZE 41
PS2CamInit
Definition at line 21 of file ps2cam.h.
PS2CAM_RPC_OPENDEVICE
#define PS2CAM_RPC_OPENDEVICE 43
Definition at line 24 of file ps2cam.h.
PS2CAM_RPC_READPACKET
#define PS2CAM_RPC_READPACKET 48
PS2CamReadPacketCOMMAND
Definition at line 33 of file ps2cam.h.
PS2CAM_RPC_SETDEVBANDWIDTH
#define PS2CAM_RPC_SETDEVBANDWIDTH 47
PS2CamSetDeviceBandwidth
Definition at line 31 of file ps2cam.h.
PS2CAM_RPC_SETDEVCONFIG
#define PS2CAM_RPC_SETDEVCONFIG 50
Definition at line 37 of file ps2cam.h.
PS2CAM_RPC_SETLEDMODE
#define PS2CAM_RPC_SETLEDMODE 49
PS2CamSetLEDMode
Definition at line 35 of file ps2cam.h.
PS2CAM_VEND_DLINK
#define PS2CAM_VEND_DLINK 0x05A9
D-Link
Definition at line 43 of file ps2cam.h.
PS2CAM_VEND_LOGITECH
#define PS2CAM_VEND_LOGITECH 0x0000
Logitech
Definition at line 45 of file ps2cam.h.
PS2CAM_VEND_SONY
#define PS2CAM_VEND_SONY 0x054C
Sony
Definition at line 41 of file ps2cam.h.
Function Documentation
camBlockStream()
void camBlockStream (CAMERA_DEVICE * dev)
camCheckAutoLaunch()
int camCheckAutoLaunch (CAMERA_DEVICE * dev)
Definition at line 755 of file ps2cam.c.
 {
         //setReg8Mask(dev, EYETOY_CREG_SNAPSHOT, 10,10);
         return 0;
 }
camClearSnapButton()
void camClearSnapButton (CAMERA_DEVICE * dev)
Definition at line 749 of file ps2cam.c.
 {
         setReg8Mask(dev, EYETOY_CREG_SNAPSHOT, 03,02);
 }
References EYETOY_CREG_SNAPSHOT, and setReg8Mask().
camDisableAutoLaunch()
void camDisableAutoLaunch (CAMERA_DEVICE * dev)
Definition at line 743 of file ps2cam.c.
 {
         setReg8(dev, EYETOY_CREG_SNAPSHOT, 23);
 }
References EYETOY_CREG_SNAPSHOT, and setReg8().
camDisableSystem()
void camDisableSystem (CAMERA_DEVICE * dev)
Disable some stuff
Definition at line 775 of file ps2cam.c.
 {
         setReg8Mask(dev, EYETOY_CREG_EN_CLK0, 0x9b,0x9b);
 }
References EYETOY_CREG_EN_CLK0, and setReg8Mask().
camEnableAutoLaunch()
void camEnableAutoLaunch (CAMERA_DEVICE * dev)
Definition at line 737 of file ps2cam.c.
 {
         setReg8(dev, EYETOY_CREG_SNAPSHOT, 23);
 }
References EYETOY_CREG_SNAPSHOT, and setReg8().
camEnableSystem()
void camEnableSystem (CAMERA_DEVICE * dev)
Enable some setting that make the cam capture
Definition at line 763 of file ps2cam.c.
 {
         setReg8(dev,0x5a, 0x6d);
         setReg8(dev,0x53, 0x9b);
         setReg8(dev,0x54, 0x0f);
         setReg8(dev,0x5d, 0x03);
         setReg8(dev,0x49, 0x01);
         setReg8(dev,0x48, 0x00);
 }
References setReg8().
Referenced by PS2CamSetDeviceDefaults().
camResetDevice()
void camResetDevice (CAMERA_DEVICE * dev)
Reset the eyetoy
Definition at line 730 of file ps2cam.c.
 {
         setReg8(dev,EYETOY_CREG_RESET1, 0x0f);
         setReg8(dev,EYETOY_CREG_RESET1, 0x00);
 }
References EYETOY_CREG_RESET1, and setReg8().
Referenced by PS2CamSetDeviceDefaults().
camResetUsb()
void camResetUsb (CAMERA_DEVICE * dev)
This is just a reguler reset to jpeg stuff
Definition at line 782 of file ps2cam.c.
 {
         setReg8(dev,0x51, 0x0f);
         setReg8(dev,0x51, 0x00);
 }
References setReg8().
camSetUsbInit()
void camSetUsbInit (CAMERA_DEVICE * dev)
reset jpeg and clear the frame reg
Definition at line 790 of file ps2cam.c.
 {
         setReg8(dev,0x51, 0x0f);
         setReg8(dev,0x51, 0x00);
         setReg8(dev,0x22, 0x00);
 }
References setReg8().
Referenced by PS2CamSetDeviceDefaults().
camSetUsbWork()
void camSetUsbWork (CAMERA_DEVICE * dev)
reset jpeg and set the frame default value
Definition at line 799 of file ps2cam.c.
 {
         setReg8(dev,0x51, 0x0f);
         setReg8(dev,0x51, 0x00);
         setReg8(dev,0x22, 0x1d);
 }
References setReg8().
camStartStream()
void camStartStream (CAMERA_DEVICE * dev)
restart stream
Definition at line 822 of file ps2cam.c.
 {
         setReg8(dev, EYETOY_CREG_RESET1, 0x00);
 }
References EYETOY_CREG_RESET1, and setReg8().
Referenced by PS2CamInitializeNewDevice(), PS2CamSetDeviceConfig(), and PS2CamSetDeviceDefaults().
camStopStream()
void camStopStream (CAMERA_DEVICE * dev)
Definition at line 829 of file ps2cam.c.
 {
         setReg8(dev, EYETOY_CREG_RESET1, 0x0f);
 }
References EYETOY_CREG_RESET1, and setReg8().
Referenced by PS2CamInitializeNewDevice(), PS2CamSetDeviceBandwidth(), PS2CamSetDeviceConfig(), and PS2CamSetDeviceDefaults().
camTurnOffRedLed()
void camTurnOffRedLed (CAMERA_DEVICE * dev)
turn off the red leg on the GPIO pin
Definition at line 815 of file ps2cam.c.
 {
         setReg8Mask(dev, EYETOY_GPIO_DATA_OUT0, 0x00,0x01);
 }
References EYETOY_GPIO_DATA_OUT0, and setReg8Mask().
Referenced by PS2CamSetDeviceDefaults(), and PS2CamSetLEDMode().
camTurnOnRedLed()
void camTurnOnRedLed (CAMERA_DEVICE * dev)
turn on the red leg on the GPIO pin
Definition at line 808 of file ps2cam.c.
 {
         setReg8Mask(dev, EYETOY_GPIO_DATA_OUT0, 0x01,0x01);
 }
References EYETOY_GPIO_DATA_OUT0, and setReg8Mask().
Referenced by PS2CamSetLEDMode().
getReg8()
int getReg8 (CAMERA_DEVICE * dev, unsigned char reg_id, unsigned char * value)
Read the camera's 8bit register and return the value
Definition at line 593 of file ps2cam.c.
 {
         int                                     ret;
         WaitSema(ps2cam_sema);
         ret = sceUsbdControlTransfer(dev->controll,USB_DIR_IN|USB_TYPE_VENDOR | USB_RECIP_DEVICE, 1, 0,(unsigned short)reg_id, 1, value, PS2CamCallback, (void*)ps2cam_sema);
         if(ret != USB_RC_OK)
         {
                 printf("sceUsbdControlTransfer failed in 'getRegValue'.\n");
                 ret = -1;
         }
         else
         {
                 WaitSema(ps2cam_sema);
         }
         SignalSema(ps2cam_sema);
         return ret;
 }
References CAMERA_DEVICE::controll, printf(), ps2cam_sema, PS2CamCallback(), sceUsbdControlTransfer(), SignalSema(), USB_DIR_IN, USB_RC_OK, USB_RECIP_DEVICE, USB_TYPE_VENDOR, and WaitSema().
Referenced by setReg8Mask().
PS2CamCallback()
void PS2CamCallback (int resultCode, int bytes, void * arg)
call back for most lowlevel usb funtions
Definition at line 557 of file ps2cam.c.
 {
         if(resultCode !=0)
                 printf("callback: result= %d, bytes= %d, arg= %p \n", resultCode, bytes, arg);
         SignalSema(ps2cam_sema);
 }
References arg, printf(), ps2cam_sema, and SignalSema().
Referenced by getReg8(), PS2CamGetDeviceSring(), PS2CamSelectInterface(), PS2CamSetDeviceConfiguration(), setReg16(), and setReg8().
PS2CamCloseDevice()
int PS2CamCloseDevice (int handle)
close the device if it is no longer needed or disconnected
Definition at line 1036 of file ps2cam.c.
 {
         int                             i;
         if(! irx_initialized)
                 return CAM_ERROR_NOTINIT;
         //find device handle and clear the status
         for(i=0;i<MAX_CAM_DEVICE_HANDLE;i++)
         {
                 if(CamHandle[i].fd == handle)
                 {
                         CamHandle[i].status=0;
                         break;
                 }
                 //see error to return
                 if((i+1)== MAX_CAM_DEVICE_HANDLE)
                 {
                         return CAM_ERROR_BADHANDLE;
                 }
         }
         return 0;
 }
References CAM_ERROR_BADHANDLE, CAM_ERROR_NOTINIT, CamHandle, irx_initialized, MAX_CAM_DEVICE_HANDLE, and PS2CAM_DEVICE_HANDLE::status.
Referenced by rpcCommandHandler().
PS2CamConnect()
int PS2CamConnect (int devId)
this is executed when a compatible camera is detected
Definition at line 206 of file ps2cam.c.
 {
         int                                             i;
         UsbDeviceDescriptor             *dev;
         UsbInterfaceDescriptor  *intf0,*intf1;
         UsbEndpointDescriptor   *endp1;
         CAMERA_DEVICE                   *cam = NULL;
         iop_thread_t                    param;
         printf("camera was connected\n");
         dev   = sceUsbdScanStaticDescriptor(devId, NULL, USB_DT_DEVICE);
         intf0 = sceUsbdScanStaticDescriptor(devId, dev,  USB_DT_INTERFACE);
         intf1 = sceUsbdScanStaticDescriptor(devId, intf0,  USB_DT_INTERFACE);
         endp1= (UsbEndpointDescriptor  *) ((char *) intf1 + intf1->bLength);
         //get a free device slot
         for(i=0;i<MAX_CAM_DEVICE;i++)
         {
                 if(Camera[i].status == 0)
                 {
                         cam = (CAMERA_DEVICE *)&Camera[i];
                         cam->status = CAM_STATUS_CONNECTED;
                         break;
                 }
         }
         cam->device_id                  = devId;
         cam->controll                   = sceUsbdOpenPipe(devId, NULL);
         cam->stream                             = sceUsbdOpenPipe(devId, endp1);
         cam->stream_pocket_size = (endp1->wMaxPacketSizeHB * 256 + endp1->wMaxPacketSizeLB);
         /*create thread that will execute funtions that cant be called*/
         /*in this funtion*/
         param.attr       = TH_C;
         param.thread     = (void *)PS2CamInitializeNewDevice;
         param.priority   = 40;
         param.stacksize  = 0x800;
         param.option     = 0;
         maintain_thread = CreateThread(&param);
         StartThread(maintain_thread, cam);
         return 0;
 }
References iop_thread_t::attr, UsbInterfaceDescriptor::bLength, CAM_STATUS_CONNECTED, Camera, CAMERA_DEVICE::controll, CreateThread(), CAMERA_DEVICE::device_id, maintain_thread, MAX_CAM_DEVICE, NULL, iop_thread_t::option, printf(), iop_thread_t::priority, PS2CamInitializeNewDevice(), sceUsbdOpenPipe(), sceUsbdScanStaticDescriptor(), iop_thread_t::stacksize, StartThread(), status, CAMERA_DEVICE::status, CAMERA_DEVICE::stream, CAMERA_DEVICE::stream_pocket_size, TH_C, iop_thread_t::thread, USB_DT_DEVICE, USB_DT_INTERFACE, UsbEndpointDescriptor::wMaxPacketSizeHB, and UsbEndpointDescriptor::wMaxPacketSizeLB.
PS2CamDisconnect()
int PS2CamDisconnect (int devId)
this is executed when a compatible camera is unplugged
Definition at line 286 of file ps2cam.c.
 {
         int                                             i;
         CAMERA_DEVICE                   *cam = NULL;
         printf("camera was unplugged\n");
         //find device in slots and remove/clear/free it
         for(i=0;i<MAX_CAM_DEVICE;i++)
         {
                 if(Camera[i].device_id == devId)
                 {
                         cam = (CAMERA_DEVICE *)&Camera[i];
                         cam->status = CAM_STATUS_NOTCONNECTED;
                         break;
                 }
         }
         // inform any handle that is using this device
         //find device handle and set the status
         for(i=0;i<MAX_CAM_DEVICE_HANDLE;i++)
         {
                 if(CamHandle[i].cam == cam)
                 {
                         CamHandle[i].status = -1;
                 }
         }
         // close endpoints
         sceUsbdClosePipe(cam->controll);
         sceUsbdClosePipe(cam->stream  );
         cam->status     = CAM_STATUS_NOTCONNECTED;
         return 0;
 }
References CAM_STATUS_NOTCONNECTED, Camera, CamHandle, CAMERA_DEVICE::controll, MAX_CAM_DEVICE, MAX_CAM_DEVICE_HANDLE, NULL, printf(), sceUsbdClosePipe(), CAMERA_DEVICE::status, PS2CAM_DEVICE_HANDLE::status, and CAMERA_DEVICE::stream.
PS2CamGetDeviceCount()
int PS2CamGetDeviceCount (void)
get the number of compatible camera connected
Definition at line 947 of file ps2cam.c.
 {
         int                             i;
         static int              count;
         if(! irx_initialized)
                 return CAM_ERROR_NOTINIT;
         //scan device slots for camara(s)
         for(i=0;i<MAX_CAM_DEVICE;i++)
         {
                 if(Camera[i].status > 0)
                 {
                         count++;
                 }
         }
         return count;
 }
References CAM_ERROR_NOTINIT, Camera, irx_initialized, MAX_CAM_DEVICE, and status.
Referenced by rpcCommandHandler().
PS2CamGetDeviceInfo()
int PS2CamGetDeviceInfo (int handle, int * info)
get information about the compatible device
Definition at line 1090 of file ps2cam.c.
 {
         static unsigned int             size;
         UsbDeviceDescriptor             *dev;
         PS2CAM_DEVICE_INFO              inf;
         PS2CAM_DEVICE_INFO              *ptr;
         CAMERA_DEVICE                   *cam;
         if(! irx_initialized)
                 return CAM_ERROR_NOTINIT;
         if(handle > MAX_CAM_DEVICE_HANDLE || handle <= 0 || CamHandle[handle-1].status == 0)
                 return CAM_ERROR_BADHANDLE;
         if(CamHandle[handle-1].status == -1)
                 return CAM_ERROR_DISCONNECTED;
         ptr = (PS2CAM_DEVICE_INFO *)info;
         size = ptr->ssize;
         if(size > sizeof(PS2CAM_DEVICE_INFO))
         {
                 size = sizeof(PS2CAM_DEVICE_INFO);
         }
         cam = CamHandle[handle-1].cam;
         //get descripters
         dev  = sceUsbdScanStaticDescriptor(cam->device_id, NULL, USB_DT_DEVICE);
         // now collect inf
         inf.ssize               = size;
         inf.vendor_id   = dev->idVendor;
         inf.product_id  = dev->idProduct;
         PS2CamGetDeviceSring(cam, dev->iManufacturer, (char *)&inf.vendor_name[0] , 32);
         PS2CamGetDeviceSring(cam, dev->iProduct,      (char *)&inf.product_name[0], 32);
         if(dev->idProduct == PS2CAM_PROD_EYETOY)
         {
                 strcpy((char *)&inf.model[0],"SLEH-00030\0");
         }
         else if(dev->idProduct == PS2CAM_PROD_EYETOY2)
         {
                 strcpy((char *)&inf.model[0],"SLEH-00031\0");
         }
         else
         {
                 strcpy((char *)&inf.model[0],"UNKNOWN\0");
         }
         memcpy(info, &inf, size);
         return 0;
 }
References PS2CAM_DEVICE_HANDLE::cam, CAM_ERROR_BADHANDLE, CAM_ERROR_DISCONNECTED, CAM_ERROR_NOTINIT, CamHandle, CAMERA_DEVICE::device_id, UsbDeviceDescriptor::idProduct, UsbDeviceDescriptor::idVendor, UsbDeviceDescriptor::iManufacturer, UsbDeviceDescriptor::iProduct, irx_initialized, MAX_CAM_DEVICE_HANDLE, memcpy(), PS2CAM_DEVICE_INFO::model, NULL, PS2CAM_DEVICE_INFO::product_id, PS2CAM_DEVICE_INFO::product_name, PS2CAM_PROD_EYETOY, PS2CAM_PROD_EYETOY2, PS2CamGetDeviceSring(), sceUsbdScanStaticDescriptor(), PS2CAM_DEVICE_INFO::ssize, status, strcpy(), USB_DT_DEVICE, PS2CAM_DEVICE_INFO::vendor_id, and PS2CAM_DEVICE_INFO::vendor_name.
Referenced by rpcCommandHandler().
PS2CamGetDeviceSring()
void PS2CamGetDeviceSring (CAMERA_DEVICE * dev, int index, char * str, int strmax)
Get a string descriptor from device
Definition at line 661 of file ps2cam.c.
 {
         int                             i;
         static char             buff[50];
         UsbStringDescriptor     *sd;
         int                             ret;
         WaitSema(ps2cam_sema);
         ret = sceUsbdControlTransfer(dev->controll, 0x80, USB_REQ_GET_DESCRIPTOR, (USB_DT_STRING << 8) | index, 0, sizeof(buff), (char *)&buff[0], PS2CamCallback, (void*)ps2cam_sema);
         if(ret != USB_RC_OK)
         {
                 printf("Usb: Error getting string (%d)\n",ret);
         }
         else
         {
                 WaitSema(ps2cam_sema);
                 sd = (UsbStringDescriptor *)&buff[0];
                 for(i=0;(i<(sd->bLength-4)/2 && i<strmax-1);i++)
                 {
                         str[i]          = sd->wData[i] & 0xFF;
                         str[i+1]        = 0x00;
                 }
         }
         SignalSema(ps2cam_sema);
 }
References CAMERA_DEVICE::controll, index(), printf(), ps2cam_sema, PS2CamCallback(), sceUsbdControlTransfer(), sd, SignalSema(), USB_DT_STRING, USB_RC_OK, USB_REQ_GET_DESCRIPTOR, and WaitSema().
Referenced by PS2CamGetDeviceInfo(), and PS2CamInitializeNewDevice().
PS2CamGetDeviceStatus()
int PS2CamGetDeviceStatus (int handle)
get the status of the compatible camera
Definition at line 1066 of file ps2cam.c.
 {
         CAMERA_DEVICE   *dev;
         if(! irx_initialized)
                 return CAM_ERROR_NOTINIT;
         if(handle > MAX_CAM_DEVICE_HANDLE || handle <= 0 || CamHandle[handle-1].status == 0)
                 return CAM_ERROR_BADHANDLE;
         if(CamHandle[handle-1].status == -1)
                 return CAM_ERROR_DISCONNECTED;
         dev = CamHandle[handle-1].cam;
         return dev->status;
 }
References PS2CAM_DEVICE_HANDLE::cam, CAM_ERROR_BADHANDLE, CAM_ERROR_DISCONNECTED, CAM_ERROR_NOTINIT, CamHandle, irx_initialized, MAX_CAM_DEVICE_HANDLE, status, and CAMERA_DEVICE::status.
Referenced by rpcCommandHandler().
PS2CamGetIRXVersion()
int PS2CamGetIRXVersion (void)
Return the current version of the 'ps2cam.irx'
Definition at line 922 of file ps2cam.c.
 {
         static unsigned short   ver[2];
         int                                             *ret;
         ret             = (int *)&ver[2];
         ver[0]  =DRIVER_VERSON_MAJOR;
         ver[1]  =DRIVER_VERSON_MINOR;
         return *ret;
 }
References DRIVER_VERSON_MAJOR, and DRIVER_VERSON_MINOR.
Referenced by rpcCommandHandler().
PS2CamInit()
int PS2CamInit (int mode)
initalize the camera driver. must be called 1st
Definition at line 937 of file ps2cam.c.
 {
         irx_initialized = 1;
         return 0;
 }
References irx_initialized.
Referenced by rpcCommandHandler().
PS2CamInitDriver()
int PS2CamInitDriver (void)
Register This driver with usbd.irx
Definition at line 102 of file ps2cam.c.
 {
         int                             i;
         iop_sema_t              sema;
         printf("PS2 USB Camera Driver v.%d.%d  ((C) www.ps2dev.org)\n",DRIVER_VERSON_MAJOR,DRIVER_VERSON_MINOR);
         memset(&Camera[0],    0, sizeof(Camera)*MAX_CAM_DEVICE       );
         memset(&CamHandle[0], 0, sizeof(Camera)*MAX_CAM_DEVICE_HANDLE);
         for(i=0;i<MAX_CAM_DEVICE_HANDLE;i++)
         {
                 CamHandle[i].fd = i+1;
         }
         //setup sema
         sema.initial= 1;
         sema.max        = 1;
         sema.option = 0;
         sema.attr       = 0;
         ps2cam_sema = CreateSema(&sema);
         //connect to usb.irx
         return sceUsbdRegisterLdd(&cam_driver);
 }
References iop_sema_t::attr, cam_driver, Camera, CamHandle, CreateSema(), DRIVER_VERSON_MAJOR, DRIVER_VERSON_MINOR, PS2CAM_DEVICE_HANDLE::fd, iop_sema_t::initial, iop_sema_t::max, MAX_CAM_DEVICE, MAX_CAM_DEVICE_HANDLE, memset(), iop_sema_t::option, printf(), ps2cam_sema, and sceUsbdRegisterLdd().
Referenced by _start().
PS2CamInitializeNewDevice()
void PS2CamInitializeNewDevice (CAMERA_DEVICE * cam)
called after a camera is accepted
Definition at line 369 of file ps2cam.c.
 {
         unsigned char                   *temp_str;
         UsbDeviceDescriptor             *d;
         PS2CamSetDeviceConfiguration(cam,1);
         camStopStream(cam);
         PS2CamSelectInterface(cam,0,0);
         camStartStream(cam);
         PS2CamSetDeviceDefaults(cam);
 /*      camStopStream(dev);
         setReg16(dev, 0x30, 384);
         camStartStream(dev);
 */
         camStopStream(cam);
         PS2CamSelectInterface(cam,0,EYETOY_ALTERNATE_SIZE_384);
         camStartStream(cam);
         cam->status = CAM_STATUS_CONNECTEDREADY;
         // connected message (alloc som mem and get device string then print it and free the mem we alloced)
         d   = sceUsbdScanStaticDescriptor(cam->device_id, NULL, USB_DT_DEVICE);
         temp_str = AllocSysMemory(0, 128, 0);
         temp_str[0]=0x00;
         PS2CamGetDeviceSring(cam, d->iProduct,      (char *)temp_str, 128);
         printf("cam initialized(%s)\n",temp_str);
         FreeSysMemory(temp_str);
         DeleteThread(maintain_thread);
         return;
 }
References AllocSysMemory(), CAM_STATUS_CONNECTEDREADY, camStartStream(), camStopStream(), DeleteThread(), CAMERA_DEVICE::device_id, EYETOY_ALTERNATE_SIZE_384, FreeSysMemory(), UsbDeviceDescriptor::iProduct, maintain_thread, NULL, printf(), PS2CamGetDeviceSring(), PS2CamSelectInterface(), PS2CamSetDeviceConfiguration(), PS2CamSetDeviceDefaults(), sceUsbdScanStaticDescriptor(), CAMERA_DEVICE::status, and USB_DT_DEVICE.
Referenced by PS2CamConnect().
PS2CamOpenDevice()
int PS2CamOpenDevice (int device_index)
open one of the compatible camera for reading
Definition at line 971 of file ps2cam.c.
 {
         int                                             i;
         CAMERA_DEVICE                   *cam = NULL;
         PS2CAM_DEVICE_HANDLE    *handle = NULL;
         int                                             index;
         if(! irx_initialized)
                 return CAM_ERROR_NOTINIT;
         //search for a connected camera
         for(i=0,index=0;i<MAX_CAM_DEVICE;i++)
         {
                 if(Camera[i].status > 0)
                 {
                         if(index == device_index)
{
                                 cam = &Camera[i];
                                 break;
                         }
                         index++;
                 }
                 //see the error code to return
                 if((i+1) == (MAX_CAM_DEVICE))
                 {
                         if(index                ==    0)return CAM_ERROR_NODEVICE;
                         if(index < device_index)return CAM_ERROR_BADRANGE;
                         return CAM_ERROR_UNKNOWN;
                 }
         }
         //find a free device handle slot for the device
         for(i=0;i<MAX_CAM_DEVICE_HANDLE;i++)
         {
                 if(CamHandle[i].status == 0)
                 {
                         handle = &CamHandle[i];
                         break;
                 }
                 //see error to return
                 if((i+1)== MAX_CAM_DEVICE_HANDLE)
                 {
                         return CAM_ERROR_MAXHANDLE;
                 }
         }
         //now we point handle attribute to the camera
         handle->status          = 1;
         handle->cam                     = cam;
         return handle->fd;
 }
References PS2CAM_DEVICE_HANDLE::cam, CAM_ERROR_BADRANGE, CAM_ERROR_MAXHANDLE, CAM_ERROR_NODEVICE, CAM_ERROR_NOTINIT, CAM_ERROR_UNKNOWN, Camera, CamHandle, PS2CAM_DEVICE_HANDLE::fd, index(), irx_initialized, MAX_CAM_DEVICE, MAX_CAM_DEVICE_HANDLE, NULL, status, and PS2CAM_DEVICE_HANDLE::status.
Referenced by rpcCommandHandler().
PS2CamProbe()
int PS2CamProbe (int devId)
check if the device is pluged in
Definition at line 136 of file ps2cam.c.
 {
         static short                    count;
         int                                             i;
         UsbDeviceDescriptor             *dev;
         UsbConfigDescriptor             *conf;
         UsbInterfaceDescriptor  *intf;
         dev  = sceUsbdScanStaticDescriptor(devId, NULL, USB_DT_DEVICE);
         conf = sceUsbdScanStaticDescriptor(devId, dev,  USB_DT_CONFIG);
         intf = (UsbInterfaceDescriptor  *) ((char *) conf + conf->bLength);
         // check for a free device slot. if none just ignore new device
         count=0;
         for(i=0;i<MAX_CAM_DEVICE;i++)
         {
                 if(Camera[i].status==0)count++;
         }
         if(count <= 0) return 0;
         if(intf->bInterfaceClass == USB_CLASS_VENDOR_SPEC)
         {
                 // eyetoy 1
                 if(dev->idVendor == PS2CAM_VEND_SONY  &&  dev->idProduct == PS2CAM_PROD_EYETOY)
                 {
                         return 1;
                 }
                 // eyetoy 2
                 if(dev->idVendor == PS2CAM_VEND_SONY  &&  dev->idProduct == PS2CAM_PROD_EYETOY2)
                 {
                         return 1;
                 }
                 // eyetoy 3
                 if(dev->idVendor == PS2CAM_VEND_SONY  &&  dev->idProduct == PS2CAM_PROD_EYETOY3)
                 {
                         return 1;
                 }
                 // eyetoy 4
                 if(dev->idVendor == PS2CAM_VEND_SONY  &&  dev->idProduct == PS2CAM_PROD_EYETOY4)
                 {
                         return 1;
                 }
                 // D-Link VisualStream DSB-C310
                 if(dev->idVendor == PS2CAM_VEND_DLINK  &&  dev->idProduct == PS2CAM_PROD_VISUALSTREAM)
                 {
                         return 1;
                 }
         }
         return 0;
 }
References UsbInterfaceDescriptor::bInterfaceClass, UsbConfigDescriptor::bLength, Camera, UsbDeviceDescriptor::idProduct, UsbDeviceDescriptor::idVendor, MAX_CAM_DEVICE, NULL, PS2CAM_PROD_EYETOY, PS2CAM_PROD_EYETOY2, PS2CAM_PROD_EYETOY3, PS2CAM_PROD_EYETOY4, PS2CAM_PROD_VISUALSTREAM, PS2CAM_VEND_DLINK, PS2CAM_VEND_SONY, sceUsbdScanStaticDescriptor(), status, USB_CLASS_VENDOR_SPEC, USB_DT_CONFIG, and USB_DT_DEVICE.
PS2CamReadPacket()
int PS2CamReadPacket (int handle)
read some data from the camera based on bandwidth
Definition at line 1231 of file ps2cam.c.
 {
         CAMERA_DEVICE   *cam;
         int                             ret;
         if(! irx_initialized)
                 return CAM_ERROR_NOTINIT;
         if(handle > MAX_CAM_DEVICE_HANDLE || handle <= 0 || CamHandle[handle-1].status == 0)
                 return CAM_ERROR_BADHANDLE;
         if(CamHandle[handle-1].status == -1)
                 return CAM_ERROR_DISCONNECTED;
         cam = CamHandle[handle-1].cam;
         if(cam                  <= 0) return CAM_ERROR_INVALIDDEVICE;
         if(cam->status  <  2) return CAM_ERROR_DEVNOTREADY;
         switch(cam->bandwidth)
         {
         case EYETOY_ALTERNATE_SIZE_0:
                 ret =0;
         break;
         case EYETOY_ALTERNATE_SIZE_384:
                 ret = PS2CamReadData(cam, &campacket[0], 384);
         break;
         case EYETOY_ALTERNATE_SIZE_512:
                 ret = PS2CamReadData(cam, &campacket[0], 512);
         break;
         case EYETOY_ALTERNATE_SIZE_768:
                 ret = PS2CamReadData(cam, &campacket[0], 768);
         break;
         case EYETOY_ALTERNATE_SIZE_896:
                 ret = PS2CamReadData(cam, &campacket[0], 896);
         break;
         default :
                 ret = PS2CamReadData(cam, &campacket[0], 384);
         break;
         }
         return ret;
 }
References CAMERA_DEVICE::bandwidth, PS2CAM_DEVICE_HANDLE::cam, CAM_ERROR_BADHANDLE, CAM_ERROR_DEVNOTREADY, CAM_ERROR_DISCONNECTED, CAM_ERROR_INVALIDDEVICE, CAM_ERROR_NOTINIT, CamHandle, campacket, EYETOY_ALTERNATE_SIZE_0, EYETOY_ALTERNATE_SIZE_384, EYETOY_ALTERNATE_SIZE_512, EYETOY_ALTERNATE_SIZE_768, EYETOY_ALTERNATE_SIZE_896, irx_initialized, MAX_CAM_DEVICE_HANDLE, PS2CamReadData(), status, and CAMERA_DEVICE::status.
Referenced by rpcCommandHandler().
PS2CamSelectInterface()
int PS2CamSelectInterface (CAMERA_DEVICE * dev, int interface, int altSetting)
Select the interface and alternet settting to use
Definition at line 699 of file ps2cam.c.
 {
         int ret;
         //int semh;
         //iop_sema_t s;
         WaitSema(ps2cam_sema);
         ret = sceUsbdSetInterface(dev->controll, interface, altSetting, PS2CamCallback, (void*)ps2cam_sema);
     if(ret != USB_RC_OK)
         {
                 printf("Usb: PS2CamSelectInterface  Error...\n");
         }
         else
         {
                 WaitSema(ps2cam_sema);
         }
         SignalSema(ps2cam_sema);
         return ret;
 }
References CAMERA_DEVICE::controll, printf(), ps2cam_sema, PS2CamCallback(), sceUsbdSetInterface, SignalSema(), USB_RC_OK, and WaitSema().
Referenced by PS2CamInitializeNewDevice(), and PS2CamSetDeviceBandwidth().
PS2CamSetDeviceBandwidth()
int PS2CamSetDeviceBandwidth (int handle, char bandwidth)
before reading you must set the camera's bandwidth
Definition at line 1155 of file ps2cam.c.
 {
         int                                             i;
         CAMERA_DEVICE                   *cam;
         UsbDeviceDescriptor             *dev;
         UsbInterfaceDescriptor  *intf;
         UsbEndpointDescriptor   *endp;
         if(! irx_initialized)
                 return CAM_ERROR_NOTINIT;
         if(handle > MAX_CAM_DEVICE_HANDLE || handle <= 0 || CamHandle[handle-1].status == 0)
                 return CAM_ERROR_BADHANDLE;
         if(CamHandle[handle-1].status == -1)
                 return CAM_ERROR_DISCONNECTED;
         cam = CamHandle[handle-1].cam;
         cam->bandwidth = bandwidth;
         //search for enpoint to open
         dev  = sceUsbdScanStaticDescriptor(cam->device_id, NULL, USB_DT_DEVICE);
         intf = sceUsbdScanStaticDescriptor(cam->device_id, dev,  USB_DT_INTERFACE);
         for(i=0;i<cam->bandwidth;i++)
         {
                 intf = sceUsbdScanStaticDescriptor(cam->device_id, intf,  USB_DT_INTERFACE);
         }
         endp= (UsbEndpointDescriptor  *) ((char *) intf + intf->bLength);
         // close old endpoint and open new one
                                         sceUsbdClosePipe(cam->stream);
         cam->stream =   sceUsbdOpenPipe(cam->device_id, endp);
         cam->stream_pocket_size = (endp->wMaxPacketSizeHB * 256 + endp->wMaxPacketSizeLB);
         printf("bandwidth =%d\n",cam->stream_pocket_size);
         camStopStream(cam);
         switch(bandwidth)
         {
         case 0:
                 PS2CamSelectInterface(cam,0,EYETOY_ALTERNATE_SIZE_0);
         break;
         case 1:
                 PS2CamSelectInterface(cam,0,EYETOY_ALTERNATE_SIZE_384);
         break;
         case 2:
                 PS2CamSelectInterface(cam,0,EYETOY_ALTERNATE_SIZE_512);
         break;
         case 3:
                 PS2CamSelectInterface(cam,0,EYETOY_ALTERNATE_SIZE_768);
         break;
         case 4:
                 PS2CamSelectInterface(cam,0,EYETOY_ALTERNATE_SIZE_896);
         break;
         }
         setReg8(cam, EYETOY_CREG_RESET1, 0x00);
         return 0;
 }
References CAMERA_DEVICE::bandwidth, UsbInterfaceDescriptor::bLength, PS2CAM_DEVICE_HANDLE::cam, CAM_ERROR_BADHANDLE, CAM_ERROR_DISCONNECTED, CAM_ERROR_NOTINIT, CamHandle, camStopStream(), CAMERA_DEVICE::device_id, EYETOY_ALTERNATE_SIZE_0, EYETOY_ALTERNATE_SIZE_384, EYETOY_ALTERNATE_SIZE_512, EYETOY_ALTERNATE_SIZE_768, EYETOY_ALTERNATE_SIZE_896, EYETOY_CREG_RESET1, irx_initialized, MAX_CAM_DEVICE_HANDLE, NULL, printf(), PS2CamSelectInterface(), sceUsbdClosePipe(), sceUsbdOpenPipe(), sceUsbdScanStaticDescriptor(), setReg8(), status, CAMERA_DEVICE::stream, CAMERA_DEVICE::stream_pocket_size, USB_DT_DEVICE, USB_DT_INTERFACE, UsbEndpointDescriptor::wMaxPacketSizeHB, and UsbEndpointDescriptor::wMaxPacketSizeLB.
Referenced by rpcCommandHandler().
PS2CamSetDeviceConfig()
int PS2CamSetDeviceConfig (int handle, void * config)
activate setting that is in config struct
Definition at line 1330 of file ps2cam.c.
 {
         CAMERA_DEVICE                   *cam;
         PS2CAM_DEVICE_CONFIG    *cfg;
         unsigned char                   *p;
         if(! irx_initialized)
                 return CAM_ERROR_NOTINIT;
         if(handle > MAX_CAM_DEVICE_HANDLE || handle <= 0 || CamHandle[handle-1].status == 0)
                 return CAM_ERROR_BADHANDLE;
         if(CamHandle[handle-1].status == -1)
                 return CAM_ERROR_DISCONNECTED;
         cam = CamHandle[handle-1].cam;
         if(cam                  <= 0) return CAM_ERROR_INVALIDDEVICE;
         if(cam->status  <  2) return CAM_ERROR_DEVNOTREADY;
         cfg = (PS2CAM_DEVICE_CONFIG *)config;
         // stop data
         camStopStream(cam);
         //set rez
         if(cfg->mask & CAM_CONFIG_MASK_DIMENSION)
         {
                 setReg8(cam, EYETOY_IREG_H_SIZE,                cfg->width >>4);
                 setReg8(cam, EYETOY_IREG_V_SIZE,                cfg->height >>3);
         }
         //set offset
         if(cfg->mask & CAM_CONFIG_MASK_OFFSET)
         {
                 p = (unsigned char *)&cfg->x_offset;
                 setReg8(cam, EYETOY_IREG_X_OFFSETL,             p[0]);
                 setReg8(cam, EYETOY_IREG_X_OFFSETH,             p[1]);
                 p = (unsigned char *)&cfg->y_offset;
                 setReg8(cam, EYETOY_IREG_Y_OFFSETL,             p[0]);
                 setReg8(cam, EYETOY_IREG_Y_OFFSETH,             p[1]);
         }
         //set divider
         if(cfg->mask & CAM_CONFIG_MASK_DIVIDER)
         {
                 if(cfg->h_divider > 4)cfg->h_divider = 4;
                 if(cfg->v_divider > 4)cfg->v_divider = 4;
                 camSetDIVIDER(cam, cfg->h_divider, 0, cfg->v_divider, 0);
         }
         //set framerate
         if(cfg->mask & CAM_CONFIG_MASK_FRAMERATE)
         {
                 switch(cfg->framerate)
                 {
                 case 5:
                         setReg8(cam, 0xa4, 0x04);
                         setReg8(cam, 0x23, 0x1b);
                 break;
                 case 10:
                         setReg8(cam, 0xa4, 0x04);
                         setReg8(cam, 0x23, 0x1f);
                 break;
                 case 15:
                         setReg8(cam, 0xa4, 0x04);
                         setReg8(cam, 0x23, 0xff);
                 break;
                 case 25:
                         setReg8(cam, 0xa4, 0x0c);
                         setReg8(cam, 0x23, 0x1f);
                 break;
                 case 30:
                         setReg8(cam, 0xa4, 0x0c);
                         setReg8(cam, 0x23, 0xff);
                 break;
                 default:
                         setReg8(cam, 0xa4, 0x0c);
                         setReg8(cam, 0x23, 0xff);
                 break;
                 }
         }
         // restart data
         camStartStream(cam);
         return 0;
 }
References PS2CAM_DEVICE_HANDLE::cam, CAM_CONFIG_MASK_DIMENSION, CAM_CONFIG_MASK_DIVIDER, CAM_CONFIG_MASK_FRAMERATE, CAM_CONFIG_MASK_OFFSET, CAM_ERROR_BADHANDLE, CAM_ERROR_DEVNOTREADY, CAM_ERROR_DISCONNECTED, CAM_ERROR_INVALIDDEVICE, CAM_ERROR_NOTINIT, CamHandle, camSetDIVIDER, camStartStream(), camStopStream(), EYETOY_IREG_H_SIZE, EYETOY_IREG_V_SIZE, EYETOY_IREG_X_OFFSETH, EYETOY_IREG_X_OFFSETL, EYETOY_IREG_Y_OFFSETH, EYETOY_IREG_Y_OFFSETL, PS2CAM_DEVICE_CONFIG::framerate, PS2CAM_DEVICE_CONFIG::h_divider, PS2CAM_DEVICE_CONFIG::height, irx_initialized, PS2CAM_DEVICE_CONFIG::mask, MAX_CAM_DEVICE_HANDLE, setReg8(), status, CAMERA_DEVICE::status, PS2CAM_DEVICE_CONFIG::v_divider, PS2CAM_DEVICE_CONFIG::width, PS2CAM_DEVICE_CONFIG::x_offset, and PS2CAM_DEVICE_CONFIG::y_offset.
Referenced by rpcCommandHandler().
PS2CamSetDeviceConfiguration()
void PS2CamSetDeviceConfiguration (CAMERA_DEVICE * dev, int id)
select the configuration for the device
Definition at line 416 of file ps2cam.c.
 {
         int                             ret;
         WaitSema(ps2cam_sema);
         ret = sceUsbdSetConfiguration(dev->controll, id, PS2CamCallback, (void*)ps2cam_sema);
         if(ret != USB_RC_OK)
         {
                 printf("Usb: Error sending set_configuration\n");
         }
         else
         {
                 WaitSema(ps2cam_sema);
         }
         SignalSema(ps2cam_sema);
 }
References CAMERA_DEVICE::controll, printf(), ps2cam_sema, PS2CamCallback(), sceUsbdSetConfiguration, SignalSema(), USB_RC_OK, and WaitSema().
Referenced by PS2CamInitializeNewDevice().
PS2CamSetDeviceDefaults()
void PS2CamSetDeviceDefaults (CAMERA_DEVICE * dev)
set the defaults for the camera
Definition at line 440 of file ps2cam.c.
 {
         //int i;
         static int width,height;
         camResetDevice(dev);
         //stop cam before we change settings then start it back later
         camStopStream(dev);
         camEnableSystem(dev);
         /*set red led pin to out before turning it on*/
         setReg8(dev,EYETOY_GPIO_IO_CTRL0, 0xee);
         camSetUsbInit(dev);
         //turn red led off by default
         camTurnOffRedLed(dev);
         /* some info sent to cam while peeking at
            the usb log under windows
         */
         setReg8(dev, EYETOY_CREG_PWDN,          0x03);
         setReg8(dev, EYETOY_CREG_EN_CLK0,       0x9f);
         setReg8(dev, EYETOY_CREG_EN_CLK1,       0x0f);
         setReg8(dev, 0xa2,                                      0x20);
         setReg8(dev, 0xa3,                                      0x18);
         setReg8(dev, 0xa4,                                      0x04);
         setReg8(dev, 0xa5,                                      0x28);
         setReg8(dev, 0x37,                                      0x00);
         setReg8(dev, EYETOY_CREG_AUDIO_CLK,     0x02);
         setReg8(dev, EYETOY_IREG_FRAR,          0x1f);
         setReg8(dev, 0x17,                                      0x50);
         setReg8(dev, 0x37,                                      0x00);
         setReg8(dev, 0x40,                                      0xff);
         setReg8(dev, 0x46,                                      0x00);
         setReg8(dev, EYETOY_CREG_CAMERA_CLK,0x04);
 //      setReg8(dev, 0xff,      0x00 );
         // my Y Enhancement
         setReg8(dev, 0xa8,      0x00 );
         setReg8(dev, 0xa9,      0x20 );
         setReg8(dev, 0xaa,      0x00 );
         /* Select 8-bit input mode */
         setReg8Mask(dev, EYETOY_IREG_DFR, 0x10, 0x10);
         // 320x240
         width = 320;
         height= 240;
         //set rez
         setReg8(dev, EYETOY_IREG_H_SIZE,                width>>4);
         setReg8(dev, EYETOY_IREG_V_SIZE,                height>>3);
         //set offset
         setReg8(dev, EYETOY_IREG_X_OFFSETL,             0x00);
         setReg8(dev, EYETOY_IREG_X_OFFSETH,             0x00);
         setReg8(dev, EYETOY_IREG_Y_OFFSETL,             0x00);
         setReg8(dev, EYETOY_IREG_Y_OFFSETH,             0x00);
         //div & color
         //setReg8(dev, EYETOY_IREG_DIVIDER,             0x11);
         camSetDIVIDER(dev, 1, 0, 1, 0);
         setReg8(dev, EYETOY_IREG_FORMAT,                0x03);
         setReg8(dev, 0x26,                                              0x00);
         // 30 fps
         setReg8(dev, 0xa4, 0x0c);
         setReg8(dev, 0x23, 0xff);
         // start cam after changing settings
         camStartStream(dev);
 }
References camEnableSystem(), camResetDevice(), camSetDIVIDER, camSetUsbInit(), camStartStream(), camStopStream(), camTurnOffRedLed(), EYETOY_CREG_AUDIO_CLK, EYETOY_CREG_CAMERA_CLK, EYETOY_CREG_EN_CLK0, EYETOY_CREG_EN_CLK1, EYETOY_CREG_PWDN, EYETOY_GPIO_IO_CTRL0, EYETOY_IREG_DFR, EYETOY_IREG_FORMAT, EYETOY_IREG_FRAR, EYETOY_IREG_H_SIZE, EYETOY_IREG_V_SIZE, EYETOY_IREG_X_OFFSETH, EYETOY_IREG_X_OFFSETL, EYETOY_IREG_Y_OFFSETH, EYETOY_IREG_Y_OFFSETL, setReg8(), and setReg8Mask().
Referenced by PS2CamInitializeNewDevice().
PS2CamSetLEDMode()
int PS2CamSetLEDMode (int handle, int mode)
set the mode for the red led
Definition at line 1285 of file ps2cam.c.
 {
         CAMERA_DEVICE   *cam;
         if(! irx_initialized)
                 return CAM_ERROR_NOTINIT;
         if(handle > MAX_CAM_DEVICE_HANDLE || handle <= 0 || CamHandle[handle-1].status == 0)
                 return CAM_ERROR_BADHANDLE;
         if(CamHandle[handle-1].status == -1)
                 return CAM_ERROR_DISCONNECTED;
         cam = CamHandle[handle-1].cam;
         if(cam                  <= 0) return CAM_ERROR_INVALIDDEVICE;
         if(cam->status  <  2) return CAM_ERROR_DEVNOTREADY;
         switch(mode)
         {
                 case 0://off
                         camTurnOffRedLed(cam);
                 break;
                 case 1://on
                         camTurnOnRedLed(cam);
                 break;
 //              case 2://flash
 //
 //              break;
                 default:
                         camTurnOffRedLed(cam);
                 break;
         }
         return 0;
 }
References PS2CAM_DEVICE_HANDLE::cam, CAM_ERROR_BADHANDLE, CAM_ERROR_DEVNOTREADY, CAM_ERROR_DISCONNECTED, CAM_ERROR_INVALIDDEVICE, CAM_ERROR_NOTINIT, CamHandle, camTurnOffRedLed(), camTurnOnRedLed(), irx_initialized, MAX_CAM_DEVICE_HANDLE, status, and CAMERA_DEVICE::status.
Referenced by rpcCommandHandler().
rpcCommandHandler()
void * rpcCommandHandler (u32 command, void * buffer, int size)
Definition at line 718 of file ps2mouse.c.
 {
   switch(command)
     {
     case PS2MOUSE_READ: do_ps2mouse_read((u8 *) buffer, size);
       break;
     case PS2MOUSE_SETREADMODE: do_ps2mouse_setreadmode((u32 *) buffer, size);
       break;
     case PS2MOUSE_GETREADMODE: do_ps2mouse_getreadmode((u32 *) buffer, size);
       break;
     case PS2MOUSE_SETTHRES: do_ps2mouse_setthres((u32 *) buffer, size);
       break;
     case PS2MOUSE_GETTHRES: do_ps2mouse_getthres((u32 *) buffer, size);
       break;
     case PS2MOUSE_SETACCEL: do_ps2mouse_setaccel((u32 *) buffer, size);
       break;
     case PS2MOUSE_GETACCEL: do_ps2mouse_getaccel((u32 *) buffer, size);
       break;
     case PS2MOUSE_SETBOUNDARY: do_ps2mouse_setboundary((s32 *) buffer, size);
       break;
     case PS2MOUSE_GETBOUNDARY: do_ps2mouse_getboundary((s32 *) buffer, size);
       break;
     case PS2MOUSE_SETPOSITION: do_ps2mouse_setposition((s32 *) buffer, size);
       break;
     case PS2MOUSE_RESET: do_ps2mouse_reset();
       break;
     case PS2MOUSE_ENUM: do_ps2mouse_enum((u32 *) buffer, size);
       break;
     case PS2MOUSE_SETDBLCLICKTIME: do_ps2mouse_setdblclicktime((u32 *) buffer, size);
       break;
     case PS2MOUSE_GETDBLCLICKTIME: do_ps2mouse_getdblclicktime((u32 *) buffer, size);
       break;
     case PS2MOUSE_GETVERSION: do_ps2mouse_getversion((u32 *) buffer, size);
       break;
     default : printf("Unknown PS2MOUSE command %ld\n", command);
       break;
     }
   return buffer;
 }
References buffer, CAM_ERROR_COMMUNKNOWN, campacket, do_ps2mouse_enum(), do_ps2mouse_getaccel(), do_ps2mouse_getboundary(), do_ps2mouse_getdblclicktime(), do_ps2mouse_getreadmode(), do_ps2mouse_getthres(), do_ps2mouse_getversion(), do_ps2mouse_read(), do_ps2mouse_reset(), do_ps2mouse_setaccel(), do_ps2mouse_setboundary(), do_ps2mouse_setdblclicktime(), do_ps2mouse_setposition(), do_ps2mouse_setreadmode(), do_ps2mouse_setthres(), printf(), PS2CAM_RPC_CLOSEDEVICE, PS2CAM_RPC_GETDEVCOUNT, PS2CAM_RPC_GETDEVINFO, PS2CAM_RPC_GETDEVSTATUS, PS2CAM_RPC_GETIRXVERSION, PS2CAM_RPC_INITIALIZE, PS2CAM_RPC_OPENDEVICE, PS2CAM_RPC_READPACKET, PS2CAM_RPC_SETDEVBANDWIDTH, PS2CAM_RPC_SETDEVCONFIG, PS2CAM_RPC_SETLEDMODE, PS2CamCloseDevice(), PS2CamGetDeviceCount(), PS2CamGetDeviceInfo(), PS2CamGetDeviceStatus(), PS2CamGetIRXVersion(), PS2CamInit(), PS2CamOpenDevice(), PS2CamReadPacket(), PS2CamSetDeviceBandwidth(), PS2CamSetDeviceConfig(), PS2CamSetLEDMode(), PS2MOUSE_ENUM, PS2MOUSE_GETACCEL, PS2MOUSE_GETBOUNDARY, PS2MOUSE_GETDBLCLICKTIME, PS2MOUSE_GETREADMODE, PS2MOUSE_GETTHRES, PS2MOUSE_GETVERSION, PS2MOUSE_READ, PS2MOUSE_RESET, PS2MOUSE_SETACCEL, PS2MOUSE_SETBOUNDARY, PS2MOUSE_SETDBLCLICKTIME, PS2MOUSE_SETPOSITION, PS2MOUSE_SETREADMODE, and PS2MOUSE_SETTHRES.
Referenced by rpcMainThread().
rpcMainThread()
void rpcMainThread (void * param)
Definition at line 121 of file ps2mouse.c.
 {
   int tid;
   SifInitRpc(0);
   //printf("PS2MOUSE - RPC Initialise\n");
   printf("PS2MOUSE - USB Mouse Library\n");
   tid = GetThreadId();
   SifSetRpcQueue(&ps2mouse_queue, tid);
   SifRegisterRpc(&ps2mouse_server, PS2MOUSE_BIND_RPC_ID, (void *) rpcCommandHandler, (u8 *) &_rpc_buffer, 0, 0, &ps2mouse_queue);
   SifRpcLoop(&ps2mouse_queue);
 }
References _rpc_buffer, BIND_RPC_ID, GetThreadId(), printf(), PS2MOUSE_BIND_RPC_ID, ps2mouse_queue, ps2mouse_server, rpc_queue, rpc_server, rpcCommandHandler(), sceSifInitRpc(), sceSifRegisterRpc(), sceSifRpcLoop(), sceSifSetRpcQueue(), SifInitRpc, SifRegisterRpc, SifRpcLoop, SifSetRpcQueue, and tid.
Referenced by _start().
setReg16()
int setReg16 (CAMERA_DEVICE * dev, unsigned char reg_id, unsigned short value)
Definition at line 637 of file ps2cam.c.
 {
         int                     ret;
         WaitSema(ps2cam_sema);
         ret = sceUsbdControlTransfer(dev->controll,USB_TYPE_VENDOR | USB_RECIP_DEVICE, 1, 0, (unsigned short)reg_id, 2, &value, PS2CamCallback, (void*)ps2cam_sema);
         if(ret != USB_RC_OK)
         {
                 printf("Usb: setReg16 Error (%d)\n",ret);
         }else
         {
                 WaitSema(ps2cam_sema);
         }
         SignalSema(ps2cam_sema);
         return 0;
 }
References CAMERA_DEVICE::controll, printf(), ps2cam_sema, PS2CamCallback(), sceUsbdControlTransfer(), SignalSema(), USB_RC_OK, USB_RECIP_DEVICE, USB_TYPE_VENDOR, and WaitSema().
setReg8()
int setReg8 (CAMERA_DEVICE * dev, unsigned char reg_id, unsigned char value)
Set the value in a 8bit register
Definition at line 567 of file ps2cam.c.
 {
         int                                             ret;
         WaitSema(ps2cam_sema);
         ret = sceUsbdControlTransfer(dev->controll, USB_TYPE_VENDOR | USB_RECIP_DEVICE, 1, 0, (unsigned short)reg_id, 1, &value, PS2CamCallback, (void*)ps2cam_sema);
         if(ret != USB_RC_OK)
         {
                 printf("sceUsbdControlTransfer failed in 'setReg8'.\n");
                 ret = -1;
         }
         else
         {
                 WaitSema(ps2cam_sema);
         }
         SignalSema(ps2cam_sema);
         return ret;
 }
References CAMERA_DEVICE::controll, printf(), ps2cam_sema, PS2CamCallback(), sceUsbdControlTransfer(), SignalSema(), USB_RC_OK, USB_RECIP_DEVICE, USB_TYPE_VENDOR, and WaitSema().
Referenced by camDisableAutoLaunch(), camEnableAutoLaunch(), camEnableSystem(), camResetDevice(), camResetUsb(), camSetUsbInit(), camSetUsbWork(), camStartStream(), camStopStream(), PS2CamSetDeviceBandwidth(), PS2CamSetDeviceConfig(), PS2CamSetDeviceDefaults(), and setReg8Mask().
setReg8Mask()
int setReg8Mask (CAMERA_DEVICE * dev, unsigned char reg_id, unsigned char value, unsigned char mask)
Set the value in a 8bit register using a mask
Definition at line 620 of file ps2cam.c.
 {
         int                             ret;
         unsigned char   current, final;
         ret = getReg8(dev, reg_id, &current);
         if (ret < 0) return -1;
         current &= (~mask);
         value   &= mask;
         final    = current | value;
         ret = setReg8(dev, reg_id, final);
         return ret;
 }
References getReg8(), and setReg8().
Referenced by camClearSnapButton(), camDisableSystem(), camTurnOffRedLed(), camTurnOnRedLed(), and PS2CamSetDeviceDefaults().