ps2sdk: iop/fs/http/src/ps2http.c File Reference
ps2http.c File Reference
#include <types.h>
#include <irx.h>
#include <stdio.h>
#include <thbase.h>
#include <sysclib.h>
#include <ioman_mod.h>
#include <sysmem.h>
#include "ps2ip.h"
Data Structures
struct t_fioPrivData
Macros
#define DBG_printf(args...) do { } while(0)
Functions
int parseContentLength (char *mimeBuffer)
int isErrorHeader (char *mimeBuffer)
int readLine (int socket, char *buffer, int size)
int httpConnect (struct sockaddr_in *server, char *hostAddr, const char *url, t_fioPrivData *pHandle)
char * strnchr (char *str, char ch, int max)
static int _ResolveHostname (const char *hostname, struct in_addr *ip)
const char * resolveAddress (struct sockaddr_in *server, const char *url, char *hostAddr)
int httpDummy ()
int httpInitialize (iop_io_device_t *driver)
int httpOpen (iop_io_file_t *f, const char *name, int mode)
int httpRead (iop_io_file_t *f, void *buffer, int size)
int httpClose (iop_io_file_t *f)
int httpLseek (iop_io_file_t *f, int offset, int mode)
int _start (int argc, char **argv)
Variables
char strTest [] = "GET /blah HTTP/1.0\n\n"
char HTTPGET [] = "GET "
char HTTPHOST [] = "Host: "
char HTTPGETEND [] = " HTTP/1.0\r\n"
char HTTPUSERAGENT [] = "User-Agent: PS2IP HTTP Client\r\n"
char HTTPENDHEADER [] = "\r\n"
iop_io_device_ops_t ps2httpOps
iop_io_device_t ps2httpDev
Macro Definition Documentation
DBG_printf
#define DBG_printf (args...) do { } while(0)
Definition at line 47 of file ps2http.c.
Function Documentation
_ResolveHostname()
static int _ResolveHostname (const char * hostname, struct in_addr * ip) static
Definition at line 241 of file ps2http.c.
 {
         struct hostent *HostEntry;
         struct in_addr **addr_list;
         if((HostEntry = gethostbyname(hostname)) == NULL)
                 return 1;
         for(addr_list = (struct in_addr **) HostEntry->h_addr_list; addr_list != NULL; addr_list++)
         {
                 ip->s_addr = (*addr_list)->s_addr;
                 return 0;
         }
         return 1;
 }
References gethostbyname, hostent::h_addr_list, NULL, and in_addr::s_addr.
Referenced by resolveAddress().
httpClose()
int httpClose (iop_io_file_t * f)
Close finds the correct handle and calls disconnect.
Definition at line 465 of file ps2http.c.
 {
         t_fioPrivData *privData = (t_fioPrivData *)f->privdata;
 #ifdef DEBUG
         printf("httpClose(-)\n");
 #endif
         lwip_close(privData->sockFd);
         FreeSysMemory(privData);
         return 0;
 }
References FreeSysMemory(), lwip_close(), printf(), iop_io_file_t::privdata, and t_fioPrivData::sockFd.
httpConnect()
int httpConnect (struct sockaddr_in * server, char * hostAddr, const char * url, t_fioPrivData * pHandle)
This is the main HTTP client connect work. Makes the connection and handles the protocol and reads the return headers. Needs to leave the stream at the start of the real data.
Definition at line 152 of file ps2http.c.
 {
         int sockHandle;
         int peerHandle;
         int rc;
         char mimeBuffer[100];
 #ifdef DEBUG
         printf( "create socket\n" );
 #endif
         if((sockHandle = socket( PF_INET, SOCK_STREAM, IPPROTO_TCP )) < 0)
         {
                 printf( "HTTP: SOCKET FAILED\n" );
                 return -1;
         }
         DBG_printf( "connect\n" );
         rc = connect( sockHandle, (struct sockaddr *) server, sizeof(*server));
         if ( rc < 0 )
         {
                 printf( "HTTP: CONNECT FAILED %i\n", sockHandle );
                 return -1;
         }
         peerHandle = sockHandle;
         DBG_printf( "send\n" );
         // Needs more error checking here.....
         rc = send( peerHandle, HTTPGET,  sizeof( HTTPGET ) - 1, 0 );
         rc = send( peerHandle, (void*) url, strlen( url ), 0 );
         rc = send( peerHandle, HTTPGETEND, sizeof( HTTPGETEND ) - 1, 0 );
         rc = send( peerHandle, HTTPHOST,  sizeof( HTTPHOST ) - 1, 0 );
         rc = send( peerHandle, hostAddr, strlen( hostAddr ), 0 );
         rc = send( peerHandle, HTTPENDHEADER, sizeof( HTTPENDHEADER ) - 1, 0 ); // "\r\n"
         rc = send( peerHandle, HTTPUSERAGENT, sizeof( HTTPUSERAGENT ) - 1, 0 );
         rc = send( peerHandle, HTTPENDHEADER, sizeof( HTTPENDHEADER ) - 1, 0 );
         // We now need to read the header information
         while ( 1 )
         {
                 int i;
                 // read a line from the header information.
                 rc = readLine( peerHandle, mimeBuffer, 100 );
                 DBG_printf(">> %s", mimeBuffer);
                 if ( rc < 0 ) return rc;
                 // End of headers is a blank line.  exit.
                 if ( rc == 0 ) break;
                 if ( (rc == 1) && (mimeBuffer[0] == '\r') ) break;
                 // Convert mimeBuffer to upper case, so we can do string comps
                 for(i = 0; i < strlen(mimeBuffer); i++)
                         mimeBuffer[i] = toupper(mimeBuffer[i]);
                 if(strstr(mimeBuffer, "HTTP/1.")) // First line of header, contains status code. Check for an error code
                         if((rc = isErrorHeader(mimeBuffer))) {
                                 printf("HTTP: status code = %d!\n", rc);
                                 return -rc;
                         }
                 if(strstr(mimeBuffer, "CONTENT-LENGTH:"))
                 {
                         pHandle->fileSize = parseContentLength(mimeBuffer);
                         DBG_printf("fileSize = %d\n", pHandle->fileSize);
                 }
         }
         // We've sent the request, and read the headers.  SockHandle is
         // now at the start of the main data read for a file io read.
         return peerHandle;
 }
References connect, DBG_printf, t_fioPrivData::fileSize, HTTPENDHEADER, HTTPGET, HTTPGETEND, HTTPHOST, HTTPUSERAGENT, IPPROTO_TCP, isErrorHeader(), parseContentLength(), PF_INET, printf(), readLine(), send, server, SOCK_STREAM, socket, strlen(), strstr(), and toupper.
Referenced by httpOpen().
httpDummy()
int httpDummy ()
Any calls we don't implement calls dummy.
Definition at line 358 of file ps2http.c.
 {
         printf("PS2HTTP: dummy function called\n");
         return -5;
 }
References printf().
httpInitialize()
int httpInitialize (iop_io_device_t * driver)
Definition at line 364 of file ps2http.c.
 {
         printf("PS2HTTP: filesystem driver initialized\n");
         return 0;
 }
References printf().
httpLseek()
int httpLseek (iop_io_file_t * f, int offset, int mode)
lseek is only supported in order to get the size of a file. Allough the function does modify the filePos member, this does not have any effect on the read position of the file in the current implimentation.
Definition at line 484 of file ps2http.c.
 {
         t_fioPrivData *privData = (t_fioPrivData *)f->privdata;
 #ifdef DEBUG
         printf("httpLseek(-, %d, %d)\n", (int)offset, mode);
 #endif
         switch(mode)
         {
                 case SEEK_SET:
                         privData->filePos = offset;
                         break;
                 case SEEK_CUR:
                         privData->filePos += offset;
                         break;
                 case SEEK_END:
                         privData->filePos = privData->fileSize + offset;
                         break;
                 default:
                         return -1;
         }
         return privData->filePos;
 }
References t_fioPrivData::filePos, t_fioPrivData::fileSize, printf(), iop_io_file_t::privdata, SEEK_CUR, SEEK_END, and SEEK_SET.
httpOpen()
int httpOpen (iop_io_file_t * f, const char * name, int mode)
Open has the most work to do in the file driver. It must:
Find a free file Handle.
Check we have a valid IP address and URL.
Try and connect to the remote server.
Send a GET request to the server
Parse the GET response header from the server
Definition at line 380 of file ps2http.c.
 {
         int peerHandle = 0;
         struct sockaddr_in server;
         const char *getName;
         t_fioPrivData *privData;
         char hostAddr[100];
 #ifdef DEBUG
         printf("httpOpen(-, %s, %d)\n", name, mode);
 #endif
         if((privData = AllocSysMemory(ALLOC_FIRST, sizeof(t_fioPrivData), NULL)) == NULL)
                 return -1;
         f->privdata = privData;
         privData->fileSize = 0;
         privData->filePos = 0;
         memset(&server, 0, sizeof(server));
         // Check valid IP address and URL
         if((getName = resolveAddress( &server, name, hostAddr )) == NULL)
         {
                 FreeSysMemory(privData);
                 return -2;
         }
         // Now we connect and initiate the transfer by sending a
         // request header to the server, and receiving the response header
         if((peerHandle = httpConnect( &server, hostAddr, getName, privData )) < 0)
         {
         printf("HTTP: failed to connect to '%s'!\n", hostAddr);
                 FreeSysMemory(privData);
                 return peerHandle;
         }
         // http connect returns valid socket.  Save in handle list.
         privData->sockFd = peerHandle;
         // return success.  We got it all ready. :)
         return 0;
 }
References ALLOC_FIRST, AllocSysMemory(), t_fioPrivData::filePos, t_fioPrivData::fileSize, FreeSysMemory(), httpConnect(), memset(), NULL, printf(), iop_io_file_t::privdata, resolveAddress(), server, and t_fioPrivData::sockFd.
httpRead()
int httpRead (iop_io_file_t * f, void * buffer, int size)
Read is simple. It simply needs to find the socket no based on the file handle and call recv.
Definition at line 429 of file ps2http.c.
 {
         int bytesRead = 0;
         t_fioPrivData *privData = (t_fioPrivData *)f->privdata;
         int left = size;
         int totalRead = 0;
 #ifdef DEBUG
         printf("httpRead(-, 0x%X, %d)\n", (int)buffer, size);
 #endif
         // Read until: there is an error, we've read "size" bytes or the remote
         //             side has closed the connection.
         do {
                 bytesRead = recv( privData->sockFd, buffer + totalRead, left, 0 );
 #ifdef DEBUG
 //              printf("bytesRead = %d\n", bytesRead);
 #endif
                 if(bytesRead <= 0) break;
                 left -= bytesRead;
                 totalRead += bytesRead;
         } while(left);
         return totalRead;
 }
References buffer, printf(), iop_io_file_t::privdata, recv, and t_fioPrivData::sockFd.
isErrorHeader()
int isErrorHeader (char * mimeBuffer)
This function will parse the initial response header line and return 0 for a "200 OK", or return the error code in the event of an error (such as 404 - not found)
Definition at line 87 of file ps2http.c.
 {
         char *line;
         int i;
         int code;
         line = strstr(mimeBuffer, "HTTP/1.");
         line += strlen("HTTP/1.");
         // Advance past minor protocol version number
         line++;
         // Advance past any whitespace characters
         while((*line == ' ') || (*line == '\t')) line++;
         // Terminate string after status code
         for(i = 0; ((line[i] != ' ') && (line[i] != '\t')); i++);
         line[i] = '\0';
         code = (int)strtol(line,NULL, 10);
         if( code == 200 )
                 return 0;
         else
                 return code;
 }
References NULL, strlen(), strstr(), and strtol().
Referenced by httpConnect().
parseContentLength()
int parseContentLength (char * mimeBuffer)
This function will parse the Content-Length header line and return the file size
Definition at line 70 of file ps2http.c.
 {
         char *line;
         line = strstr(mimeBuffer, "CONTENT-LENGTH:");
         line += strlen("CONTENT-LENGTH:");
         // Advance past any whitepace characters
         while((*line == ' ') || (*line == '\t')) line++;
         return (int)strtol(line,NULL, 10);
 }
References NULL, strlen(), strstr(), and strtol().
Referenced by httpConnect().
readLine()
int readLine (int socket, char * buffer, int size)
When a request has been sent, we can expect mime headers to be before the data. We need to read exactly to the end of the headers and no more data. This readline reads a single char at a time.
Definition at line 118 of file ps2http.c.
 {
         char * ptr = buffer;
         int count = 0;
         int rc;
         // Keep reading until we fill the buffer.
         while ( count < size )
         {
                 rc = recv( socket, ptr, 1, 0 );
                 if ( rc <= 0 ) return rc;
                 if ( (*ptr == '\n') ) break;
                 // increment after check for cr.  Don't want to count the cr.
                 count++;
                 ptr++;
         }
         // Terminate string
         *ptr = '\0';
         // return how many bytes read.
         return count;
 }
References buffer, recv, and socket.
Referenced by httpConnect().
resolveAddress()
const char* resolveAddress (struct sockaddr_in * server, const char * url, char * hostAddr)
Before we can connect we need to parse the server address and optional port from the url provided. the format of "url" as passed to this function is "//192.168.0.1:8080/blah.elf" where "192.168.0.1" can be either an IP or a domain name and ":8080" is the optional port to connect to, default port is 80.
This function will return a filename string for use in GET requests, and fill the structure pointed to by *server with the correct values.
Definition at line 269 of file ps2http.c.
 {
         unsigned char w,x,y,z;
         const char *char_ptr;
         char addr[128];
         char port[6] = "80"; // default port of 80(HTTP)
         int i = 0, rv;
         int isDomain = 0;
         // eg url= //192.168.0.1/fred.elf  (the http: is already stripped)
         // NOTE: Need more error checking in parsing code
         // URL must start with double forward slashes.
         while(url[0] == '/') {
                 url++;
         }
         for(i = 0; ((url[i] != '\0') && (url[i] != '/')) && (i < 127); i++)
             if((((addr[i] = url[i]) < '0') || (url[i] > '9')) && (url[i] != '.')) {
                 if(url[i] == ':') {// allow specification of port in URL like http://www.server.net:8080/
                     for(w = 0; ((w + i + 1) < 127) && (w < 5) && (url[w + i + 1] != '/') && (url[w + i + 1] != '\0'); w++)
                         port[w] = url[w + i + 1];
                     port[w] = '\0';
                     DBG_printf("HTTP: using port %s for connection\n", port);
                     break;
                     }
             else // it's a domain name if a non-numeric char is contained in the "server" part of the URL.
                     isDomain = 1;
                 }
     addr[i] = '\0'; // overwrite last char copied(should be '/', '\0' or ':') with a '\0'
     strcpy(hostAddr, addr);
     if(isDomain) {
                 // resolve the host name.
                 rv = _ResolveHostname(addr, &server->sin_addr);
                 if(rv != 0) {
                     printf("HTTP: failed to resolve domain '%s'\n", addr);
                         return NULL;
                         }
         }
     else {
                 // turn '.' characters in ip string into null characters
                 for(i = 0, w = 0; i < 16; i++)
                         if(addr[i] == '.') { addr[i] = '\0'; w++; }
         if(w != 3) { // w is used as a simple error check here
             printf("HTTP: invalid IP address '%s'\n", hostAddr);
             return(NULL);
             }
                 i = 0;
                 // Extract individual ip number octets from string
                 w = (int)strtol(&addr[i],NULL, 10);
                 i += (strlen(&addr[i]) + 1);
                 x = (int)strtol(&addr[i],NULL, 10);
                 i += (strlen(&addr[i]) + 1);
                 y = (int)strtol(&addr[i],NULL, 10);
                 i += (strlen(&addr[i]) + 1);
                 z = (int)strtol(&addr[i],NULL, 10);
                 i += (strlen(&addr[i]) + 1);
                 IP4_ADDR( (struct ip4_addr *)&(server->sin_addr) ,w,x,y,z );
         }
     i = (int) strtol(port, NULL, 10); // set the port
         server->sin_port = htons(i);
         server->sin_family = AF_INET;
 #if 1
         char_ptr = url;
         while(*char_ptr != '/') char_ptr++;
         return char_ptr;
 #else
         return url;
 #endif
 }
References _ResolveHostname(), AF_INET, DBG_printf, htons(), IP4_ADDR, NULL, printf(), server, strcpy(), strlen(), and strtol().
Referenced by httpOpen().
strnchr()
char* strnchr (char * str, char ch, int max)
Definition at line 231 of file ps2http.c.
{
     int i;
     for(i = 0; (i < max) && (str[i] != '\0'); i++)
         if(str[i] == ch)
             return(&str[i]);
     return(NULL);
 }
References NULL.
Variable Documentation
HTTPENDHEADER
char HTTPENDHEADER[] = "\r\n"
Definition at line 65 of file ps2http.c.
Referenced by httpConnect().
HTTPGET
char HTTPGET[] = "GET "
Definition at line 61 of file ps2http.c.
Referenced by httpConnect().
HTTPGETEND
char HTTPGETEND[] = " HTTP/1.0\r\n"
Definition at line 63 of file ps2http.c.
Referenced by httpConnect().
HTTPHOST
char HTTPHOST[] = "Host: "
Definition at line 62 of file ps2http.c.
Referenced by httpConnect().
HTTPUSERAGENT
char HTTPUSERAGENT[] = "User-Agent: PS2IP HTTP Client\r\n"
Definition at line 64 of file ps2http.c.
Referenced by httpConnect().
ps2httpDev
iop_io_device_t ps2httpDev
Initial value:
= {
        "http",
        IOP_DT_FS,
        1,
        "HTTP client file driver",
        &ps2httpOps
}
Definition at line 520 of file ps2http.c.
Referenced by _start().
ps2httpOps
iop_io_device_ops_t ps2httpOps
Initial value:
= {
        httpInitialize, httpDummy, httpDummy, httpOpen, httpClose, httpRead, httpDummy, httpLseek,
        httpDummy, httpDummy, httpDummy, httpDummy, httpDummy, httpDummy, httpDummy, httpDummy,
        httpDummy
}
Definition at line 514 of file ps2http.c.
strTest
char strTest[] = "GET /blah HTTP/1.0\n\n"
Definition at line 59 of file ps2http.c.