ps2sdk: iop/tcpip/tcpip/include/ps2ip.h File Reference
ps2ip.h File Reference
#include <types.h>
#include <irx.h>
#include <tcpip.h>
#include <sys/time.h>
Macros
#define tcpip_callback(f, ctx) tcpip_callback_with_block(f, ctx, 1)
#define inet_addr(cp) ipaddr_addr(cp)
#define inet_aton(cp, addr) ip4addr_aton(cp, (ip4_addr_t*)addr)
#define inet_ntoa(addr) ip4addr_ntoa((const ip4_addr_t*)&(addr))
#define inet_ntoa_r(addr, buf, buflen) ip4addr_ntoa_r((const ip4_addr_t*)&(addr), buf, buflen)
#define accept lwip_accept
#define bind lwip_bind
#define disconnect lwip_close
#define closesocket lwip_close
#define shutdown lwip_shutdown
#define connect lwip_connect
#define listen lwip_listen
#define recv lwip_recv
#define recvfrom lwip_recvfrom
#define send lwip_send
#define sendto lwip_sendto
#define socket lwip_socket
#define select lwip_select
#define ioctlsocket lwip_ioctl
#define fcntlsocket lwip_fcntl
#define gethostbyname lwip_gethostbyname
#define gethostbyname_r lwip_gethostbyname_r
#define freeaddrinfo lwip_freeaddrinfo
#define getaddrinfo lwip_getaddrinfo
#define getsockname lwip_getsockname
#define getpeername lwip_getpeername
#define getsockopt lwip_getsockopt
#define setsockopt lwip_setsockopt
#define ps2ip_IMPORTS_start DECLARE_IMPORT_TABLE(ps2ip, 2, 6)
#define ps2ip_IMPORTS_end END_IMPORT_TABLE
#define I_lwip_accept DECLARE_IMPORT(4, lwip_accept)
#define I_lwip_bind DECLARE_IMPORT(5, lwip_bind)
#define I_lwip_close DECLARE_IMPORT(6, lwip_close)
#define I_lwip_connect DECLARE_IMPORT(7, lwip_connect)
#define I_lwip_listen DECLARE_IMPORT(8, lwip_listen)
#define I_lwip_recv DECLARE_IMPORT(9, lwip_recv)
#define I_lwip_recvfrom DECLARE_IMPORT(10, lwip_recvfrom)
#define I_lwip_send DECLARE_IMPORT(11, lwip_send)
#define I_lwip_sendto DECLARE_IMPORT(12, lwip_sendto)
#define I_lwip_socket DECLARE_IMPORT(13, lwip_socket)
#define I_lwip_select DECLARE_IMPORT(14, lwip_select)
#define I_lwip_ioctl DECLARE_IMPORT(15, lwip_ioctl)
#define I_lwip_getpeername DECLARE_IMPORT(16, lwip_getpeername)
#define I_lwip_getsockname DECLARE_IMPORT(17, lwip_getsockname)
#define I_lwip_getsockopt DECLARE_IMPORT(18, lwip_getsockopt)
#define I_lwip_setsockopt DECLARE_IMPORT(19, lwip_setsockopt)
#define I_ps2ip_setconfig DECLARE_IMPORT(20, ps2ip_setconfig)
#define I_ps2ip_getconfig DECLARE_IMPORT(21, ps2ip_getconfig)
#define I_ps2ip_input DECLARE_IMPORT(22, ps2ip_input)
#define I_lwip_shutdown DECLARE_IMPORT(46, lwip_shutdown)
#define I_lwip_fcntl DECLARE_IMPORT(47, lwip_fcntl)
#define I_etharp_output DECLARE_IMPORT(23, etharp_output)
#define I_tcpip_input DECLARE_IMPORT(25, tcpip_input)
#define I_tcpip_callback_with_block DECLARE_IMPORT(56, tcpip_callback_with_block)
#define I_netif_add DECLARE_IMPORT(26, netif_add)
#define I_netif_find DECLARE_IMPORT(27, netif_find)
#define I_netif_set_default DECLARE_IMPORT(28, netif_set_default)
#define I_netif_set_ipaddr DECLARE_IMPORT(29, netif_set_ipaddr)
#define I_netif_set_netmask DECLARE_IMPORT(30, netif_set_netmask)
#define I_netif_set_gw DECLARE_IMPORT(31, netif_set_gw)
#define I_netif_set_up DECLARE_IMPORT(32, netif_set_up)
#define I_netif_set_down DECLARE_IMPORT(33, netif_set_down)
#define I_netif_set_link_up DECLARE_IMPORT(54, netif_set_link_up)
#define I_netif_set_link_down DECLARE_IMPORT(55, netif_set_link_down)
#define I_pbuf_alloc DECLARE_IMPORT(34, pbuf_alloc)
#define I_pbuf_realloc DECLARE_IMPORT(35, pbuf_realloc)
#define I_pbuf_header DECLARE_IMPORT(36, pbuf_header)
#define I_pbuf_ref DECLARE_IMPORT(37, pbuf_ref)
#define I_pbuf_free DECLARE_IMPORT(38, pbuf_free)
#define I_pbuf_clen DECLARE_IMPORT(39, pbuf_clen)
#define I_pbuf_chain DECLARE_IMPORT(40, pbuf_chain)
#define I_pbuf_dechain DECLARE_IMPORT(41, pbuf_dechain)
#define I_pbuf_take DECLARE_IMPORT(42, pbuf_take)
#define I_pbuf_coalesce DECLARE_IMPORT(57, pbuf_coalesce)
#define I_ipaddr_addr DECLARE_IMPORT(24, ipaddr_addr)
#define I_inet_addr DECLARE_IMPORT(24, ipaddr_addr)
#define I_ipaddr4_aton DECLARE_IMPORT(43, ipaddr4_aton)
#define I_inet_aton DECLARE_IMPORT(43, ip4addr_aton)
#define I_ip4addr_ntoa DECLARE_IMPORT(44, ip4addr_ntoa)
#define I_inet_ntoa DECLARE_IMPORT(44, ip4addr_ntoa)
#define I_ip4addr_ntoa_r DECLARE_IMPORT(45, ip4addr_ntoa_r)
#define I_inet_ntoa_r DECLARE_IMPORT(45, ip4addr_ntoa_r)
#define I_lwip_gethostbyname DECLARE_IMPORT(48, lwip_gethostbyname)
#define I_lwip_gethostbyname_r DECLARE_IMPORT(49, lwip_gethostbyname_r)
#define I_lwip_freeaddrinfo DECLARE_IMPORT(50, lwip_freeaddrinfo)
#define I_lwip_getaddrinfo DECLARE_IMPORT(51, lwip_getaddrinfo)
#define I_dns_setserver DECLARE_IMPORT(52, dns_setserver)
#define I_dns_getserver DECLARE_IMPORT(53, dns_getserver)
Typedefs
typedef void(* tcpip_callback_fn) (void *ctx)
Functions
int lwip_accept (int s, struct sockaddr *addr, socklen_t *addrlen)
int lwip_bind (int s, struct sockaddr *name, socklen_t namelen)
int lwip_close (int s)
int lwip_connect (int s, struct sockaddr *name, socklen_t namelen)
int lwip_listen (int s, int backlog)
int lwip_recv (int s, void *mem, int len, unsigned int flags)
int lwip_recvfrom (int s, void *mem, int len, unsigned int flags, struct sockaddr *from, socklen_t *fromlen)
int lwip_send (int s, void *dataptr, int size, unsigned int flags)
int lwip_sendto (int s, void *dataptr, int size, unsigned int flags, struct sockaddr *to, socklen_t tolen)
int lwip_socket (int domain, int type, int protocol)
int lwip_select (int maxfdp1, fd_set *readset, fd_set *writeset, fd_set *exceptset, struct timeval *timeout)
int lwip_ioctl (int s, long cmd, void *argp)
int lwip_getpeername (int s, struct sockaddr *name, socklen_t *namelen)
int lwip_getsockname (int s, struct sockaddr *name, socklen_t *namelen)
int lwip_getsockopt (int s, int level, int optname, void *optval, socklen_t *optlen)
int lwip_setsockopt (int s, int level, int optname, const void *optval, socklen_t optlen)
int ps2ip_setconfig (const t_ip_info *ip_info)
int ps2ip_getconfig (char *netif_name, t_ip_info *ip_info)
void ps2ip_input (struct pbuf *p, struct netif *inp)
int lwip_shutdown (int s, int how)
int lwip_fcntl (int s, int cmd, int val)
err_t etharp_output (struct netif *netif, struct pbuf *q, const ip_addr_t *ipaddr)
err_t tcpip_input (struct pbuf *p, struct netif *inp)
err_t tcpip_callback_with_block (tcpip_callback_fn function, void *ctx, u8 block)
struct netif * netif_add (struct netif *netif, void *state, netif_init_fn init, netif_input_fn input)
struct netif * netif_find (const char *name)
void netif_set_default (struct netif *netif)
void netif_set_ipaddr (struct netif *netif, const ip4_addr_t *ipaddr)
void netif_set_netmask (struct netif *netif, const ip4_addr_t *netmask)
void netif_set_gw (struct netif *netif, const ip4_addr_t *gw)
void netif_set_up (struct netif *netif)
void netif_set_down (struct netif *netif)
void netif_set_link_up (struct netif *netif)
void netif_set_link_down (struct netif *netif)
struct pbuf * pbuf_alloc (pbuf_layer l, u16 size, pbuf_type type)
void pbuf_realloc (struct pbuf *p, u16 size)
u8 pbuf_header (struct pbuf *p, s16 header_size)
void pbuf_ref (struct pbuf *p)
u8 pbuf_free (struct pbuf *p)
u8 pbuf_clen (struct pbuf *p)
void pbuf_chain (struct pbuf *h, struct pbuf *t)
struct pbuf * pbuf_dechain (struct pbuf *p)
struct pbuf * pbuf_take (struct pbuf *f)
struct pbuf * pbuf_coalesce (struct pbuf *p, pbuf_layer layer)
u32 ipaddr_addr (const char *cp)
int ipaddr4_aton (const char *cp, ip4_addr_t *addr)
char * ip4addr_ntoa (const ip4_addr_t *addr)
char * ip4addr_ntoa_r (const ip4_addr_t *addr, char *buf, int buflen)
Detailed Description
Imports and definitions for ps2ip.
Definition in file ps2ip.h.
Macro Definition Documentation
accept
#define accept lwip_accept
Definition at line 137 of file ps2ip.h.
bind
#define bind lwip_bind
Definition at line 138 of file ps2ip.h.
closesocket
#define closesocket lwip_close
Definition at line 140 of file ps2ip.h.
connect
#define connect lwip_connect
Definition at line 142 of file ps2ip.h.
disconnect
#define disconnect lwip_close
Definition at line 139 of file ps2ip.h.
fcntlsocket
#define fcntlsocket lwip_fcntl
Definition at line 151 of file ps2ip.h.
freeaddrinfo
#define freeaddrinfo lwip_freeaddrinfo
Definition at line 154 of file ps2ip.h.
getaddrinfo
#define getaddrinfo lwip_getaddrinfo
Definition at line 155 of file ps2ip.h.
gethostbyname
#define gethostbyname lwip_gethostbyname
Definition at line 152 of file ps2ip.h.
gethostbyname_r
#define gethostbyname_r lwip_gethostbyname_r
Definition at line 153 of file ps2ip.h.
getpeername
#define getpeername lwip_getpeername
Definition at line 159 of file ps2ip.h.
getsockname
#define getsockname lwip_getsockname
Definition at line 158 of file ps2ip.h.
getsockopt
#define getsockopt lwip_getsockopt
Definition at line 160 of file ps2ip.h.
I_dns_getserver
#define I_dns_getserver DECLARE_IMPORT(53, dns_getserver)
Definition at line 223 of file ps2ip.h.
I_dns_setserver
#define I_dns_setserver DECLARE_IMPORT(52, dns_setserver)
Definition at line 222 of file ps2ip.h.
I_etharp_output
#define I_etharp_output DECLARE_IMPORT(23, etharp_output)
Definition at line 187 of file ps2ip.h.
I_inet_addr
#define I_inet_addr DECLARE_IMPORT(24, ipaddr_addr)
Definition at line 211 of file ps2ip.h.
I_inet_aton
#define I_inet_aton DECLARE_IMPORT(43, ip4addr_aton)
Definition at line 213 of file ps2ip.h.
I_inet_ntoa
#define I_inet_ntoa DECLARE_IMPORT(44, ip4addr_ntoa)
Definition at line 215 of file ps2ip.h.
I_inet_ntoa_r
#define I_inet_ntoa_r DECLARE_IMPORT(45, ip4addr_ntoa_r)
Definition at line 217 of file ps2ip.h.
I_ip4addr_ntoa
#define I_ip4addr_ntoa DECLARE_IMPORT(44, ip4addr_ntoa)
Definition at line 214 of file ps2ip.h.
I_ip4addr_ntoa_r
#define I_ip4addr_ntoa_r DECLARE_IMPORT(45, ip4addr_ntoa_r)
Definition at line 216 of file ps2ip.h.
I_ipaddr4_aton
#define I_ipaddr4_aton DECLARE_IMPORT(43, ipaddr4_aton)
Definition at line 212 of file ps2ip.h.
I_ipaddr_addr
#define I_ipaddr_addr DECLARE_IMPORT(24, ipaddr_addr)
Definition at line 210 of file ps2ip.h.
I_lwip_accept
#define I_lwip_accept DECLARE_IMPORT(4, lwip_accept)
Definition at line 166 of file ps2ip.h.
I_lwip_bind
#define I_lwip_bind DECLARE_IMPORT(5, lwip_bind)
Definition at line 167 of file ps2ip.h.
I_lwip_close
#define I_lwip_close DECLARE_IMPORT(6, lwip_close)
Definition at line 168 of file ps2ip.h.
I_lwip_connect
#define I_lwip_connect DECLARE_IMPORT(7, lwip_connect)
Definition at line 169 of file ps2ip.h.
I_lwip_fcntl
#define I_lwip_fcntl DECLARE_IMPORT(47, lwip_fcntl)
Definition at line 186 of file ps2ip.h.
I_lwip_freeaddrinfo
#define I_lwip_freeaddrinfo DECLARE_IMPORT(50, lwip_freeaddrinfo)
Definition at line 220 of file ps2ip.h.
I_lwip_getaddrinfo
#define I_lwip_getaddrinfo DECLARE_IMPORT(51, lwip_getaddrinfo)
Definition at line 221 of file ps2ip.h.
I_lwip_gethostbyname
#define I_lwip_gethostbyname DECLARE_IMPORT(48, lwip_gethostbyname)
Definition at line 218 of file ps2ip.h.
I_lwip_gethostbyname_r
#define I_lwip_gethostbyname_r DECLARE_IMPORT(49, lwip_gethostbyname_r)
Definition at line 219 of file ps2ip.h.
I_lwip_getpeername
#define I_lwip_getpeername DECLARE_IMPORT(16, lwip_getpeername)
Definition at line 178 of file ps2ip.h.
I_lwip_getsockname
#define I_lwip_getsockname DECLARE_IMPORT(17, lwip_getsockname)
Definition at line 179 of file ps2ip.h.
I_lwip_getsockopt
#define I_lwip_getsockopt DECLARE_IMPORT(18, lwip_getsockopt)
Definition at line 180 of file ps2ip.h.
I_lwip_ioctl
#define I_lwip_ioctl DECLARE_IMPORT(15, lwip_ioctl)
Definition at line 177 of file ps2ip.h.
I_lwip_listen
#define I_lwip_listen DECLARE_IMPORT(8, lwip_listen)
Definition at line 170 of file ps2ip.h.
I_lwip_recv
#define I_lwip_recv DECLARE_IMPORT(9, lwip_recv)
Definition at line 171 of file ps2ip.h.
I_lwip_recvfrom
#define I_lwip_recvfrom DECLARE_IMPORT(10, lwip_recvfrom)
Definition at line 172 of file ps2ip.h.
I_lwip_select
#define I_lwip_select DECLARE_IMPORT(14, lwip_select)
Definition at line 176 of file ps2ip.h.
I_lwip_send
#define I_lwip_send DECLARE_IMPORT(11, lwip_send)
Definition at line 173 of file ps2ip.h.
I_lwip_sendto
#define I_lwip_sendto DECLARE_IMPORT(12, lwip_sendto)
Definition at line 174 of file ps2ip.h.
I_lwip_setsockopt
#define I_lwip_setsockopt DECLARE_IMPORT(19, lwip_setsockopt)
Definition at line 181 of file ps2ip.h.
I_lwip_shutdown
#define I_lwip_shutdown DECLARE_IMPORT(46, lwip_shutdown)
Definition at line 185 of file ps2ip.h.
I_lwip_socket
#define I_lwip_socket DECLARE_IMPORT(13, lwip_socket)
Definition at line 175 of file ps2ip.h.
I_netif_add
#define I_netif_add DECLARE_IMPORT(26, netif_add)
Definition at line 190 of file ps2ip.h.
I_netif_find
#define I_netif_find DECLARE_IMPORT(27, netif_find)
Definition at line 191 of file ps2ip.h.
I_netif_set_default
#define I_netif_set_default DECLARE_IMPORT(28, netif_set_default)
Definition at line 192 of file ps2ip.h.
I_netif_set_down
#define I_netif_set_down DECLARE_IMPORT(33, netif_set_down)
Definition at line 197 of file ps2ip.h.
I_netif_set_gw
#define I_netif_set_gw DECLARE_IMPORT(31, netif_set_gw)
Definition at line 195 of file ps2ip.h.
I_netif_set_ipaddr
#define I_netif_set_ipaddr DECLARE_IMPORT(29, netif_set_ipaddr)
Definition at line 193 of file ps2ip.h.
I_netif_set_link_down
#define I_netif_set_link_down DECLARE_IMPORT(55, netif_set_link_down)
Definition at line 199 of file ps2ip.h.
I_netif_set_link_up
#define I_netif_set_link_up DECLARE_IMPORT(54, netif_set_link_up)
Definition at line 198 of file ps2ip.h.
I_netif_set_netmask
#define I_netif_set_netmask DECLARE_IMPORT(30, netif_set_netmask)
Definition at line 194 of file ps2ip.h.
I_netif_set_up
#define I_netif_set_up DECLARE_IMPORT(32, netif_set_up)
Definition at line 196 of file ps2ip.h.
I_pbuf_alloc
#define I_pbuf_alloc DECLARE_IMPORT(34, pbuf_alloc)
Definition at line 200 of file ps2ip.h.
I_pbuf_chain
#define I_pbuf_chain DECLARE_IMPORT(40, pbuf_chain)
Definition at line 206 of file ps2ip.h.
I_pbuf_clen
#define I_pbuf_clen DECLARE_IMPORT(39, pbuf_clen)
Definition at line 205 of file ps2ip.h.
I_pbuf_coalesce
#define I_pbuf_coalesce DECLARE_IMPORT(57, pbuf_coalesce)
Definition at line 209 of file ps2ip.h.
I_pbuf_dechain
#define I_pbuf_dechain DECLARE_IMPORT(41, pbuf_dechain)
Definition at line 207 of file ps2ip.h.
I_pbuf_free
#define I_pbuf_free DECLARE_IMPORT(38, pbuf_free)
Definition at line 204 of file ps2ip.h.
I_pbuf_header
#define I_pbuf_header DECLARE_IMPORT(36, pbuf_header)
Definition at line 202 of file ps2ip.h.
I_pbuf_realloc
#define I_pbuf_realloc DECLARE_IMPORT(35, pbuf_realloc)
Definition at line 201 of file ps2ip.h.
I_pbuf_ref
#define I_pbuf_ref DECLARE_IMPORT(37, pbuf_ref)
Definition at line 203 of file ps2ip.h.
I_pbuf_take
#define I_pbuf_take DECLARE_IMPORT(42, pbuf_take)
Definition at line 208 of file ps2ip.h.
I_ps2ip_getconfig
#define I_ps2ip_getconfig DECLARE_IMPORT(21, ps2ip_getconfig)
Definition at line 183 of file ps2ip.h.
I_ps2ip_input
#define I_ps2ip_input DECLARE_IMPORT(22, ps2ip_input)
Definition at line 184 of file ps2ip.h.
I_ps2ip_setconfig
#define I_ps2ip_setconfig DECLARE_IMPORT(20, ps2ip_setconfig)
Definition at line 182 of file ps2ip.h.
I_tcpip_callback_with_block
#define I_tcpip_callback_with_block DECLARE_IMPORT(56, tcpip_callback_with_block)
Definition at line 189 of file ps2ip.h.
I_tcpip_input
#define I_tcpip_input DECLARE_IMPORT(25, tcpip_input)
Definition at line 188 of file ps2ip.h.
inet_addr
#define inet_addr (cp) ipaddr_addr(cp)
Definition at line 108 of file ps2ip.h.
inet_aton
#define inet_aton (cp, addr) ip4addr_aton(cp, (ip4_addr_t*)addr)
Definition at line 109 of file ps2ip.h.
inet_ntoa
#define inet_ntoa (addr) ip4addr_ntoa((const ip4_addr_t*)&(addr))
Definition at line 110 of file ps2ip.h.
inet_ntoa_r
#define inet_ntoa_r (addr, buf, buflen) ip4addr_ntoa_r((const ip4_addr_t*)&(addr), buf, buflen)
Definition at line 111 of file ps2ip.h.
ioctlsocket
#define ioctlsocket lwip_ioctl
Definition at line 150 of file ps2ip.h.
listen
#define listen lwip_listen
Definition at line 143 of file ps2ip.h.
ps2ip_IMPORTS_end
#define ps2ip_IMPORTS_end END_IMPORT_TABLE
Definition at line 164 of file ps2ip.h.
ps2ip_IMPORTS_start
#define ps2ip_IMPORTS_start DECLARE_IMPORT_TABLE(ps2ip, 2, 6)
Definition at line 163 of file ps2ip.h.
recv
#define recv lwip_recv
Definition at line 144 of file ps2ip.h.
recvfrom
#define recvfrom lwip_recvfrom
Definition at line 145 of file ps2ip.h.
select
#define select lwip_select
Definition at line 149 of file ps2ip.h.
send
#define send lwip_send
Definition at line 146 of file ps2ip.h.
sendto
#define sendto lwip_sendto
Definition at line 147 of file ps2ip.h.
setsockopt
#define setsockopt lwip_setsockopt
Definition at line 161 of file ps2ip.h.
shutdown
#define shutdown (void) lwip_shutdown
Definition at line 141 of file ps2ip.h.
socket
#define socket lwip_socket
Definition at line 148 of file ps2ip.h.
tcpip_callback
#define tcpip_callback (f, ctx) tcpip_callback_with_block(f, ctx, 1)
See also
tcpip_callback_with_block
Definition at line 70 of file ps2ip.h.
Typedef Documentation
tcpip_callback_fn
typedef void(* tcpip_callback_fn) (void *ctx)
Function prototype for functions passed to tcpip_callback()
Definition at line 62 of file ps2ip.h.
Function Documentation
etharp_output()
err_t etharp_output (struct netif * netif, struct pbuf * q, const ip_addr_t * ipaddr)
Referenced by SMapIFInit().
ip4addr_ntoa()
char* ip4addr_ntoa (const ip4_addr_t * addr)
returns ptr to static buffer; not reentrant!
ip4addr_ntoa_r()
char* ip4addr_ntoa_r (const ip4_addr_t * addr, char * buf, int buflen)
ipaddr4_aton()
int ipaddr4_aton (const char * cp, ip4_addr_t * addr)
ipaddr_addr()
u32 ipaddr_addr (const char * cp)
lwip_accept()
int lwip_accept (int s, struct sockaddr * addr, socklen_t * addrlen)
lwip_bind()
int lwip_bind (int s, struct sockaddr * name, socklen_t namelen)
lwip_close()
int lwip_close (int s)
Referenced by _shutdown(), httpClose(), and smb_Disconnect().
lwip_connect()
int lwip_connect (int s, struct sockaddr * name, socklen_t namelen)
Referenced by OpenTCPSession().
lwip_fcntl()
int lwip_fcntl (int s, int cmd, int val)
lwip_getpeername()
int lwip_getpeername (int s, struct sockaddr * name, socklen_t * namelen)
lwip_getsockname()
int lwip_getsockname (int s, struct sockaddr * name, socklen_t * namelen)
lwip_getsockopt()
int lwip_getsockopt (int s, int level, int optname, void * optval, socklen_t * optlen)
lwip_ioctl()
int lwip_ioctl (int s, long cmd, void * argp)
lwip_listen()
int lwip_listen (int s, int backlog)
lwip_recv()
int lwip_recv (int s, void * mem, int len, unsigned int flags)
Referenced by RecvTimeout().
lwip_recvfrom()
int lwip_recvfrom (int s, void * mem, int len, unsigned int flags, struct sockaddr * from, socklen_t * fromlen)
lwip_select()
int lwip_select (int maxfdp1, fd_set * readset, fd_set * writeset, fd_set * exceptset, struct timeval * timeout)
Referenced by poll().
lwip_send()
int lwip_send (int s, void * dataptr, int size, unsigned int flags)
Referenced by SendData().
lwip_sendto()
int lwip_sendto (int s, void * dataptr, int size, unsigned int flags, struct sockaddr * to, socklen_t tolen)
Referenced by udp_send().
lwip_setsockopt()
int lwip_setsockopt (int s, int level, int optname, const void * optval, socklen_t optlen)
Referenced by OpenTCPSession().
lwip_shutdown()
int lwip_shutdown (int s, int how)
lwip_socket()
int lwip_socket (int domain, int type, int protocol)
Referenced by _start(), and OpenTCPSession().
netif_add()
struct netif* netif_add (struct netif * netif, void * state, netif_init_fn init, netif_input_fn input)
Referenced by InitLWIPStack().
netif_find()
struct netif* netif_find (const char * name)
Referenced by ps2ip_getconfig(), and ps2ip_setconfig().
netif_set_default()
void netif_set_default (struct netif * netif)
Referenced by InitLWIPStack().
netif_set_down()
void netif_set_down (struct netif * netif)
netif_set_gw()
void netif_set_gw (struct netif * netif, const ip4_addr_t * gw)
Referenced by ps2ip_setconfig().
netif_set_ipaddr()
void netif_set_ipaddr (struct netif * netif, const ip4_addr_t * ipaddr)
Referenced by ps2ip_setconfig().
netif_set_link_down()
void netif_set_link_down (struct netif * netif)
Referenced by LinkStateDown().
netif_set_link_up()
void netif_set_link_up (struct netif * netif)
Referenced by LinkStateUp().
netif_set_netmask()
void netif_set_netmask (struct netif * netif, const ip4_addr_t * netmask)
Referenced by ps2ip_setconfig().
netif_set_up()
void netif_set_up (struct netif * netif)
Referenced by InitLWIPStack().
pbuf_alloc()
struct pbuf* pbuf_alloc (pbuf_layer l, u16 size, pbuf_type type)
Referenced by AllocRxPacket().
pbuf_chain()
void pbuf_chain (struct pbuf * h, struct pbuf * t)
pbuf_clen()
u8 pbuf_clen (struct pbuf * p)
pbuf_coalesce()
struct pbuf* pbuf_coalesce (struct pbuf * p, pbuf_layer layer)
Referenced by SMapLowLevelOutput().
pbuf_dechain()
struct pbuf* pbuf_dechain (struct pbuf * p)
pbuf_free()
u8 pbuf_free (struct pbuf * p)
Referenced by DeQTxPacket(), FreeRxPacket(), and ps2ip_input().
pbuf_header()
u8 pbuf_header (struct pbuf * p, s16 header_size)
pbuf_realloc()
void pbuf_realloc (struct pbuf * p, u16 size)
pbuf_ref()
void pbuf_ref (struct pbuf * p)
Referenced by SMapLowLevelOutput().
pbuf_take()
struct pbuf* pbuf_take (struct pbuf * f)
ps2ip_getconfig()
int ps2ip_getconfig (char * netif_name, t_ip_info * ip_info)
Definition at line 55 of file ps2ip.c.
 {
         NetIF*  pNetIF=netif_find(pszName);
         if (pNetIF==NULL)
         {
                 //Net interface not found.
                 memset(pInfo,0,sizeof(*pInfo));
                 return  0;
         }
         strcpy(pInfo->netif_name,pszName);
         pInfo->ipaddr.s_addr=pNetIF->ip_addr.addr;
         pInfo->netmask.s_addr=pNetIF->netmask.addr;
         pInfo->gw.s_addr=pNetIF->gw.addr;
         memcpy(pInfo->hw_addr,pNetIF->hwaddr,sizeof(pInfo->hw_addr));
 #if             LWIP_DHCP
         struct dhcp *dhcp = netif_dhcp_data(pNetIF);
         if ((dhcp != NULL) && (dhcp->state != DHCP_STATE_OFF))
         {
                 pInfo->dhcp_enabled=1;
                 pInfo->dhcp_status=dhcp->state;
         }
         else
         {
                 pInfo->dhcp_enabled=0;
                 pInfo->dhcp_status=DHCP_STATE_OFF;
         }
 #else
         pInfo->dhcp_enabled=0;
 #endif
         return  1;
 }
References t_ip_info::dhcp_enabled, DHCP_STATE_OFF, t_ip_info::dhcp_status, t_ip_info::gw, t_ip_info::hw_addr, t_ip_info::ipaddr, memcpy(), memset(), netif_dhcp_data, netif_find(), t_ip_info::netif_name, t_ip_info::netmask, NULL, in_addr::s_addr, and strcpy().
Referenced by do_getconfig().
ps2ip_input()
void ps2ip_input (struct pbuf * p, struct netif * inp)
ps2ip_setconfig()
int ps2ip_setconfig (const t_ip_info * ip_info)
Definition at line 99 of file ps2ip.c.
 {
         NetIF*  pNetIF=netif_find(pInfo->netif_name);
         if      (pNetIF==NULL)
         {
                 return  0;
         }
 #if     LWIP_DHCP
         struct dhcp *dhcp = netif_dhcp_data(pNetIF);
         //Enable dhcp here
         if (pInfo->dhcp_enabled)
         {
                 if ((dhcp == NULL) || (dhcp->state == DHCP_STATE_OFF))
                 {
                         //Set initial IP address
                         netif_set_ipaddr(pNetIF,(const IPAddr*)&pInfo->ipaddr);
                         netif_set_netmask(pNetIF,(const IPAddr*)&pInfo->netmask);
                         netif_set_gw(pNetIF,(const IPAddr*)&pInfo->gw);
                         //Start DHCP client
                         dhcp_start(pNetIF);
                 }
         }
         else
         {
                 if ((dhcp != NULL) && (dhcp->state != DHCP_STATE_OFF))
                 {
                         //Release DHCP lease
                         dhcp_release(pNetIF);
                         //Stop DHCP client
                         dhcp_stop(pNetIF);
                 }
                 netif_set_ipaddr(pNetIF,(const IPAddr*)&pInfo->ipaddr);
                 netif_set_netmask(pNetIF,(const IPAddr*)&pInfo->netmask);
                 netif_set_gw(pNetIF,(const IPAddr*)&pInfo->gw);
         }
 #else
         netif_set_ipaddr(pNetIF,(const IPAddr*)&pInfo->ipaddr);
         netif_set_netmask(pNetIF,(const IPAddr*)&pInfo->netmask);
         netif_set_gw(pNetIF,(const IPAddr*)&pInfo->gw);
 #endif
         return  1;
 }
References t_ip_info::dhcp_enabled, DHCP_STATE_OFF, t_ip_info::gw, t_ip_info::ipaddr, netif_dhcp_data, netif_find(), t_ip_info::netif_name, netif_set_gw(), netif_set_ipaddr(), netif_set_netmask(), t_ip_info::netmask, and NULL.
Referenced by do_setconfig().
tcpip_callback_with_block()
err_t tcpip_callback_with_block (tcpip_callback_fn function, void * ctx, u8 block)
tcpip_input()
err_t tcpip_input (struct pbuf * p, struct netif * inp)
Referenced by InitLWIPStack().