ps2sdk: iop/tcpip/tcpips/src/ps2ips.c File Reference
ps2ips.c File Reference
#include <types.h>
#include <loadcore.h>
#include <stdio.h>
#include <sifman.h>
#include <sifcmd.h>
#include <sysclib.h>
#include <thbase.h>
#include <intrman.h>
#include <ps2ip.h>
#include <ps2ip_rpc.h>
Macros
#define MODNAME "TCP/IP_Stack_RPC"
#define BUFF_SIZE (1024)
#define MIN(a, b) (((a)<(b))?(a):(b))
#define RDOWN_64(a) (((a) >> 6) << 6)
Functions
IRX_ID (MODNAME, 1, 1)
static void do_accept (void *rpcBuffer, int size)
static void do_bind (void *rpcBuffer, int size)
static void do_disconnect (void *rpcBuffer, int size)
static void do_connect (void *rpcBuffer, int size)
static void do_listen (void *rpcBuffer, int size)
static void do_recv (void *rpcBuffer, int size)
static void do_recvfrom (void *rpcBuffer, int size)
static void do_send (void *rpcBuffer, int size)
static void do_sendto (void *rpcBuffer, int size)
static void do_socket (void *rpcBuffer, int size)
static void do_getconfig (void *rpcBuffer, int size)
static void do_setconfig (void *rpcBuffer, int size)
static void do_select (void *rpcBuffer, int size)
static void do_ioctlsocket (void *rpcBuffer, int size)
static void do_getsockname (void *rpcBuffer, int size)
static void do_getpeername (void *rpcBuffer, int size)
static void do_getsockopt (void *rpcBuffer, int size)
static void do_setsockopt (void *rpcBuffer, int size)
static void * rpcHandlerFunction (unsigned int command, void *rpcBuffer, int size)
static void threadRpcFunction (void *arg)
int _start (int argc, char *argv[])
Variables
static SifRpcDataQueue_t ps2ips_queue
static SifRpcServerData_t ps2ips_server
static int _rpc_buffer [512]
static char lwip_buffer [BUFF_SIZE+32]
static rests_pkt rests
Detailed Description
Remote Procedure Call server for ps2ip. Depends on ps2ip.irx and dns.irx.
Definition in file ps2ips.c.
Macro Definition Documentation
BUFF_SIZE
#define BUFF_SIZE (1024)
Definition at line 40 of file ps2ips.c.
MIN
#define MIN (a, b) (((a)<(b))?(a):(b))
Definition at line 42 of file ps2ips.c.
MODNAME
#define MODNAME "TCP/IP_Stack_RPC"
Definition at line 37 of file ps2ips.c.
RDOWN_64
#define RDOWN_64 (a) (((a) >> 6) << 6)
Definition at line 43 of file ps2ips.c.
Function Documentation
_start()
int _start (int argc, char * argv[])
Definition at line 577 of file ps2ips.c.
 {
         int             threadId;
         iop_thread_t    t;
         printf( "PS2IPS: Module Loaded.\n" );
         t.attr = TH_C;
         t.option = 0;
         t.thread = &threadRpcFunction;
         t.stacksize = 0x800;
         t.priority = 0x1e;
         threadId = CreateThread( &t );
         if ( threadId < 0 )
         {
                 printf( "PS2IPS: CreateThread failed.  %i\n", threadId );
                 return MODULE_NO_RESIDENT_END;
         }
         else
         {
                 StartThread( threadId, NULL );
                 return MODULE_RESIDENT_END;
         }
 }
References iop_thread_t::attr, CreateThread(), MODULE_NO_RESIDENT_END, MODULE_RESIDENT_END, NULL, iop_thread_t::option, printf(), iop_thread_t::priority, iop_thread_t::stacksize, StartThread(), TH_C, iop_thread_t::thread, and threadRpcFunction().
do_accept()
static void do_accept (void * rpcBuffer, int size) static
Definition at line 52 of file ps2ips.c.
 {
         int *ptr = rpcBuffer;
         cmd_pkt *pkt = (cmd_pkt *)ptr;
         struct sockaddr addr;
         int addrlen, ret;
         ret = accept(pkt->socket, &addr, &addrlen);
         pkt->socket = ret;
         memcpy(&pkt->sockaddr, &addr, sizeof(struct sockaddr));
         pkt->len = sizeof(struct sockaddr);
 }
References accept, cmd_pkt::len, memcpy(), cmd_pkt::sockaddr, and cmd_pkt::socket.
Referenced by rpcHandlerFunction().
do_bind()
static void do_bind (void * rpcBuffer, int size) static
Definition at line 66 of file ps2ips.c.
 {
         int *ptr = rpcBuffer;
         cmd_pkt *pkt = (cmd_pkt *)rpcBuffer;
         int ret;
         ret = bind(pkt->socket, &pkt->sockaddr, pkt->len);
         ptr[0] = ret;
 }
References bind, cmd_pkt::len, cmd_pkt::sockaddr, and cmd_pkt::socket.
Referenced by rpcHandlerFunction().
do_connect()
static void do_connect (void * rpcBuffer, int size) static
Definition at line 87 of file ps2ips.c.
 {
         int *ptr = rpcBuffer;
         cmd_pkt *pkt = (cmd_pkt *)_rpc_buffer;
         int ret;
         ret = connect(pkt->socket, &pkt->sockaddr, pkt->len);
         ptr[0] = ret;
 }
References _rpc_buffer, connect, cmd_pkt::len, cmd_pkt::sockaddr, and cmd_pkt::socket.
Referenced by rpcHandlerFunction().
do_disconnect()
static void do_disconnect (void * rpcBuffer, int size) static
Definition at line 77 of file ps2ips.c.
 {
         int *ptr = rpcBuffer;
         int ret;
         ret = disconnect(ptr[0]);
         ptr[0] = ret;
 }
References disconnect.
Referenced by rpcHandlerFunction().
do_getconfig()
static void do_getconfig (void * rpcBuffer, int size) static
Definition at line 368 of file ps2ips.c.
 {
         ps2ip_getconfig((char *)rpcBuffer, (t_ip_info *)rpcBuffer);
 }
References ps2ip_getconfig().
Referenced by rpcHandlerFunction().
do_getpeername()
static void do_getpeername (void * rpcBuffer, int size) static
Definition at line 411 of file ps2ips.c.
 {
         int *ptr = rpcBuffer;
         cmd_pkt *pkt = (cmd_pkt *)ptr;
         struct sockaddr addr;
         int addrlen, ret;
         ret = getpeername(pkt->socket, &addr, &addrlen);
         pkt->socket = ret;
         memcpy(&pkt->sockaddr, &addr, sizeof(struct sockaddr));
         pkt->len = sizeof(struct sockaddr);
 }
References getpeername, cmd_pkt::len, memcpy(), cmd_pkt::sockaddr, and cmd_pkt::socket.
Referenced by rpcHandlerFunction().
do_getsockname()
static void do_getsockname (void * rpcBuffer, int size) static
Definition at line 397 of file ps2ips.c.
 {
         int *ptr = rpcBuffer;
         cmd_pkt *pkt = (cmd_pkt *)ptr;
         struct sockaddr addr;
         int addrlen, ret;
         ret = getsockname(pkt->socket, &addr, &addrlen);
         pkt->socket = ret;
         memcpy(&pkt->sockaddr, &addr, sizeof(struct sockaddr));
         pkt->len = sizeof(struct sockaddr);
 }
References getsockname, cmd_pkt::len, memcpy(), cmd_pkt::sockaddr, and cmd_pkt::socket.
Referenced by rpcHandlerFunction().
do_getsockopt()
static void do_getsockopt (void * rpcBuffer, int size) static
Definition at line 425 of file ps2ips.c.
 {
         int ret, s, level, optname, optlen;
         unsigned char optval[128];
         s       = ((getsockopt_pkt*)rpcBuffer)->s;
         level   = ((getsockopt_pkt*)rpcBuffer)->level;
         optname = ((getsockopt_pkt*)rpcBuffer)->optname;
         optlen  = sizeof(optval);
         ret = getsockopt(s, level, optname, optval, &optlen);
         ((getsockopt_res_pkt*)rpcBuffer)->result = ret;
         ((getsockopt_res_pkt*)rpcBuffer)->optlen = optlen;
         memcpy( ((getsockopt_res_pkt*)rpcBuffer)->buffer, optval, 128 );
 }
References buffer, getsockopt, and memcpy().
Referenced by rpcHandlerFunction().
do_ioctlsocket()
static void do_ioctlsocket (void * rpcBuffer, int size) static
Definition at line 389 of file ps2ips.c.
 {
         ioctl_pkt *pkt = (ioctl_pkt*)_rpc_buffer;
         pkt->result = ioctlsocket(      pkt->s,
                                         pkt->cmd,
                                         pkt->argp != NULL ? &pkt->value : NULL );
 }
References _rpc_buffer, ioctl_pkt::argp, ioctl_pkt::cmd, ioctlsocket, NULL, ioctl_pkt::result, ioctl_pkt::s, and ioctl_pkt::value.
Referenced by rpcHandlerFunction().
do_listen()
static void do_listen (void * rpcBuffer, int size) static
Definition at line 98 of file ps2ips.c.
 {
         int *ptr = rpcBuffer;
         int ret;
         ret = listen(ptr[0], ptr[1]);
         ptr[0] = ret;
 }
References listen.
Referenced by rpcHandlerFunction().
do_recv()
static void do_recv (void * rpcBuffer, int size) static
Definition at line 108 of file ps2ips.c.
 {
         int srest, erest, asize; // size of unaligned portion, remainder portion, aligned portion
         void *abuffer, *aebuffer; // aligned buffer start, aligned buffer end
         int s_offset; // offset into lwip_buffer of srest data
         int rlen, recvlen;
         int dma_id = 0;
         int intr_stat;
         s_recv_pkt *recv_pkt = (s_recv_pkt *)rpcBuffer;
         r_recv_pkt *ret_pkt = (r_recv_pkt *)rpcBuffer;
         struct t_SifDmaTransfer sifdma;
         if(recv_pkt->length <= 64)
         {
                 srest = recv_pkt->length;
         } else {
                 if( ((int)recv_pkt->ee_addr & 0x3F) == 0 ) // ee address is aligned
                         srest = 0;
                 else
                         srest = RDOWN_64((int)recv_pkt->ee_addr) - (int)recv_pkt->ee_addr + 64;
         }
         s_offset = 64 - srest;
         recvlen = MIN(BUFF_SIZE, recv_pkt->length);
         // Do actual TCP recv
         rlen = recv(recv_pkt->socket, lwip_buffer + s_offset, recvlen, recv_pkt->flags);
         if(rlen <= 0) goto recv_end;
         if(rlen <= 64) srest = rlen;
         // fill sbuffer, calculate align buffer & erest valules, fill ebuffer
         if(srest)
                 memcpy((void *)rests.sbuffer, (void *)(lwip_buffer + s_offset), srest);
         if(rlen > 64)
         {
                 abuffer = recv_pkt->ee_addr + srest; // aligned buffer (round up)
                 aebuffer = (void *)RDOWN_64((int)recv_pkt->ee_addr + rlen); // aligned buffer end (round down)
                 asize = (int)aebuffer - (int)abuffer;
                 erest = recv_pkt->ee_addr + rlen - aebuffer;
                 if(erest)
                         memcpy((void *)rests.ebuffer, (void *)(lwip_buffer + 64 + asize), erest);
 //              printf("srest = 0x%X\nabuffer = 0x%X\naebuffer = 0x%X\nasize = 0x%X\nerest = 0x%X\n", srest, abuffer, aebuffer, asize, erest);
         } else {
                 abuffer = aebuffer = NULL;
                 erest = asize =  0;
         }
         // DMA back the abuffer
         if(asize)
         {
                 while(SifDmaStat(dma_id) >= 0);
                 sifdma.src = lwip_buffer + 64;
                 sifdma.dest = abuffer;
                 sifdma.size = asize;
                 sifdma.attr = 0;
                 CpuSuspendIntr(&intr_stat);
                 dma_id = SifSetDma(&sifdma, 1);
                 CpuResumeIntr(intr_stat);
         }
         // Fill rest of rests structure, dma back
         rests.ssize = srest;
         rests.esize = erest;
         rests.sbuf = recv_pkt->ee_addr;
         rests.ebuf = aebuffer;
         while(SifDmaStat(dma_id) >= 0);
         sifdma.src = &rests;
         sifdma.dest = recv_pkt->intr_data;
         sifdma.size = sizeof(rests_pkt);
         sifdma.attr = 0;
         CpuSuspendIntr(&intr_stat);
         dma_id = SifSetDma(&sifdma, 1);
         CpuResumeIntr(intr_stat);
 recv_end:
         ret_pkt->ret = rlen;
 }
References BUFF_SIZE, CpuResumeIntr(), CpuSuspendIntr(), rests_pkt::ebuf, rests_pkt::ebuffer, s_recv_pkt::ee_addr, rests_pkt::esize, s_recv_pkt::flags, s_recv_pkt::intr_data, s_recv_pkt::length, lwip_buffer, memcpy(), MIN, NULL, RDOWN_64, recv, rests, rests_pkt::sbuf, rests_pkt::sbuffer, SifDmaStat, SifSetDma, s_recv_pkt::socket, and rests_pkt::ssize.
Referenced by rpcHandlerFunction().
do_recvfrom()
static void do_recvfrom (void * rpcBuffer, int size) static
Definition at line 200 of file ps2ips.c.
 {
         int srest, erest, asize; // size of unaligned portion, remainder portion, aligned portion
         void *abuffer, *aebuffer; // aligned buffer start, aligned buffer end
         int s_offset; // offset into lwip_buffer of srest data
         int rlen, recvlen;
         int dma_id = 0;
         int intr_stat;
         s_recv_pkt *recv_pkt = (s_recv_pkt *)rpcBuffer;
         r_recv_pkt *ret_pkt = (r_recv_pkt *)rpcBuffer;
         static struct t_SifDmaTransfer sifdma;
         static struct sockaddr sockaddr;
         int fromlen;
         if(recv_pkt->length <= 64)
         {
                 srest = recv_pkt->length;
         } else {
                 if( ((int)recv_pkt->ee_addr & 0x3F) == 0 ) // ee address is aligned
                         srest = 0;
                 else
                         srest = RDOWN_64((int)recv_pkt->ee_addr) - (int)recv_pkt->ee_addr + 64;
         }
         s_offset = 64 - srest;
         recvlen = MIN(BUFF_SIZE, recv_pkt->length);
         // Do actual UDP recvfrom
         rlen = recvfrom(recv_pkt->socket, lwip_buffer + s_offset, recvlen, recv_pkt->flags, &sockaddr, &fromlen);
         if(rlen <= 0) goto recv_end;
         if(rlen <= 64) srest = rlen;
         // copy sockaddr struct to return packet
         memcpy((void *)&ret_pkt->sockaddr, (void *)&sockaddr, sizeof(struct sockaddr));
         // fill sbuffer, calculate align buffer & erest valules, fill ebuffer
         if(srest)
                 memcpy((void *)rests.sbuffer, (void *)(lwip_buffer + s_offset), srest);
         if(rlen > 64)
         {
                 abuffer = recv_pkt->ee_addr + srest; // aligned buffer (round up)
                 aebuffer = (void *)RDOWN_64((int)recv_pkt->ee_addr + rlen); // aligned buffer end (round down)
                 asize = (int)aebuffer - (int)abuffer;
                 erest = recv_pkt->ee_addr + rlen - aebuffer;
                 if(erest)
                         memcpy((void *)rests.ebuffer, (void *)(lwip_buffer + 64 + asize), erest);
 //              printf("srest = 0x%X\nabuffer = 0x%X\naebuffer = 0x%X\nasize = 0x%X\nerest = 0x%X\n", srest, abuffer, aebuffer, asize, erest);
         } else {
                 abuffer = aebuffer = NULL;
                 erest = asize = 0;
         }
         // DMA back the abuffer
         if(asize)
         {
                 while(SifDmaStat(dma_id) >= 0);
                 sifdma.src = lwip_buffer + 64;
                 sifdma.dest = abuffer;
                 sifdma.size = asize;
                 sifdma.attr = 0;
                 CpuSuspendIntr(&intr_stat);
                 dma_id = SifSetDma(&sifdma, 1);
                 CpuResumeIntr(intr_stat);
         }
         // Fill rest of rests structure, dma back
         rests.ssize = srest;
         rests.esize = erest;
         rests.sbuf = recv_pkt->ee_addr;
         rests.ebuf = aebuffer;
         while(SifDmaStat(dma_id) >= 0);
         sifdma.src = &rests;
         sifdma.dest = recv_pkt->intr_data;
         sifdma.size = sizeof(rests_pkt);
         sifdma.attr = 0;
         CpuSuspendIntr(&intr_stat);
         dma_id = SifSetDma(&sifdma, 1);
         CpuResumeIntr(intr_stat);
 recv_end:
         ret_pkt->ret = rlen;
 }
References BUFF_SIZE, CpuResumeIntr(), CpuSuspendIntr(), rests_pkt::ebuf, rests_pkt::ebuffer, s_recv_pkt::ee_addr, rests_pkt::esize, s_recv_pkt::flags, s_recv_pkt::intr_data, s_recv_pkt::length, lwip_buffer, memcpy(), MIN, NULL, RDOWN_64, recvfrom, rests, rests_pkt::sbuf, rests_pkt::sbuffer, SifDmaStat, SifSetDma, ret_pkt::sockaddr, s_recv_pkt::socket, and rests_pkt::ssize.
Referenced by rpcHandlerFunction().
do_select()
static void do_select (void * rpcBuffer, int size) static
Definition at line 378 of file ps2ips.c.
 {
         select_pkt *pkt = (select_pkt*)_rpc_buffer;
         pkt->result = select(   pkt->maxfdp1,
                                 pkt->readset_p != NULL ? &pkt->readset : NULL,
                                 pkt->writeset_p != NULL ? &pkt->writeset : NULL,
                                 pkt->exceptset_p != NULL ? &pkt->exceptset : NULL,
                                 pkt->timeout_p != NULL ? &pkt->timeout : NULL );
 }
References _rpc_buffer, select_pkt::exceptset, select_pkt::exceptset_p, select_pkt::maxfdp1, NULL, select_pkt::readset, select_pkt::readset_p, select_pkt::result, select, select_pkt::timeout, select_pkt::timeout_p, select_pkt::writeset, and select_pkt::writeset_p.
Referenced by rpcHandlerFunction().
do_send()
static void do_send (void * rpcBuffer, int size) static
Definition at line 297 of file ps2ips.c.
 {
         int *ptr = rpcBuffer;
         send_pkt *pkt = (send_pkt *)rpcBuffer;
         int slen, sendlen;
         int s_offset; // offset into lwip_buffer for malign data
         void *ee_pos;
         SifRpcReceiveData_t rdata;
         if(pkt->malign)
         {
 //              printf("send: misaligned = %d\n", pkt->malign);
                 s_offset = 64 - pkt->malign;
                 memcpy((void *)(lwip_buffer + s_offset), pkt->malign_buff, pkt->malign);
         } else s_offset = 64;
         ee_pos = pkt->ee_addr + pkt->malign;
         sendlen = MIN(BUFF_SIZE, pkt->length);
         SifRpcGetOtherData(&rdata, ee_pos, lwip_buffer + 64, sendlen - pkt->malign, 0);
         // So actual TCP send
         slen = send(pkt->socket, lwip_buffer + s_offset, sendlen, pkt->flags);
         ptr[0] = slen;
 }
References BUFF_SIZE, send_pkt::ee_addr, send_pkt::flags, send_pkt::length, lwip_buffer, send_pkt::malign, send_pkt::malign_buff, memcpy(), MIN, send, SifRpcGetOtherData, and send_pkt::socket.
Referenced by rpcHandlerFunction().
do_sendto()
static void do_sendto (void * rpcBuffer, int size) static
Definition at line 328 of file ps2ips.c.
 {
         int *ptr = rpcBuffer;
         send_pkt *pkt = (send_pkt *)rpcBuffer;
         int slen, sendlen;
         int s_offset; // offset into lwip_buffer for malign data
         void *ee_pos;
         SifRpcReceiveData_t rdata;
         if(pkt->malign)
         {
 //              printf("send: misaligned = %d\n", pkt->malign);
                 s_offset = 64 - pkt->malign;
                 memcpy((void *)(lwip_buffer + s_offset), pkt->malign_buff, pkt->malign);
         } else s_offset = 64;
         ee_pos = pkt->ee_addr + pkt->malign;
         sendlen = MIN(BUFF_SIZE, pkt->length);
         SifRpcGetOtherData(&rdata, ee_pos, lwip_buffer + 64, sendlen - pkt->malign, 0);
         // So actual UDP sendto
         slen = sendto(pkt->socket, lwip_buffer + s_offset, sendlen, pkt->flags, &pkt->sockaddr, sizeof(struct sockaddr));
         ptr[0] = slen;
 }
References BUFF_SIZE, send_pkt::ee_addr, send_pkt::flags, send_pkt::length, lwip_buffer, send_pkt::malign, send_pkt::malign_buff, memcpy(), MIN, sendto, SifRpcGetOtherData, send_pkt::sockaddr, and send_pkt::socket.
Referenced by rpcHandlerFunction().
do_setconfig()
static void do_setconfig (void * rpcBuffer, int size) static
Definition at line 373 of file ps2ips.c.
 {
         ps2ip_setconfig((t_ip_info *)rpcBuffer);
 }
References ps2ip_setconfig().
Referenced by rpcHandlerFunction().
do_setsockopt()
static void do_setsockopt (void * rpcBuffer, int size) static
Definition at line 442 of file ps2ips.c.
 {
         int *ptr = rpcBuffer, ret;
         int s;
         int level;
         int optname;
         int optlen;
         unsigned char optval[128];
         s       = ((setsockopt_pkt*)rpcBuffer)->s;
         level   = ((setsockopt_pkt*)rpcBuffer)->level;
         optname = ((setsockopt_pkt*)rpcBuffer)->optname;
         optlen  = ((setsockopt_pkt*)rpcBuffer)->optlen;
         memcpy(optval, ((setsockopt_pkt*)rpcBuffer)->buffer, optlen);
         ret = setsockopt(s, level, optname, optval, optlen);
         ptr[0] = ret;
 }
References buffer, memcpy(), and setsockopt.
Referenced by rpcHandlerFunction().
do_socket()
static void do_socket (void * rpcBuffer, int size) static
Definition at line 358 of file ps2ips.c.
 {
         int *ptr = rpcBuffer;
         int ret;
         ret = socket(ptr[0], ptr[1], ptr[2]);
         ptr[0] = ret;
 }
References socket.
Referenced by rpcHandlerFunction().
IRX_ID()
IRX_ID (MODNAME , 1 , 1)
rpcHandlerFunction()
static void* rpcHandlerFunction (unsigned int command, void * rpcBuffer, int size) static
Definition at line 491 of file ps2ips.c.
 {
         switch(command)
         {
         case PS2IPS_ID_ACCEPT:
                 do_accept(rpcBuffer, size);
                 break;
         case PS2IPS_ID_BIND:
                 do_bind(rpcBuffer, size);
                 break;
         case PS2IPS_ID_DISCONNECT:
                 do_disconnect(rpcBuffer, size);
                 break;
         case PS2IPS_ID_CONNECT:
                 do_connect(rpcBuffer, size);
                 break;
         case PS2IPS_ID_LISTEN:
                 do_listen(rpcBuffer, size);
                 break;
         case PS2IPS_ID_RECV:
                 do_recv(rpcBuffer, size);
                 break;
         case PS2IPS_ID_RECVFROM:
                 do_recvfrom(rpcBuffer, size);
                 break;
         case PS2IPS_ID_SEND:
                 do_send(rpcBuffer, size);
                 break;
         case PS2IPS_ID_SENDTO:
                 do_sendto(rpcBuffer, size);
                 break;
         case PS2IPS_ID_SOCKET:
                 do_socket(rpcBuffer, size);
                 break;
         case PS2IPS_ID_GETCONFIG:
                 do_getconfig(rpcBuffer, size);
                 break;
         case PS2IPS_ID_SETCONFIG:
                 do_setconfig(rpcBuffer, size);
                 break;
         case PS2IPS_ID_SELECT:
                 do_select(rpcBuffer, size);
                 break;
         case PS2IPS_ID_IOCTL:
                 do_ioctlsocket(rpcBuffer, size);
                 break;
         case PS2IPS_ID_GETSOCKNAME:
                 do_getsockname(rpcBuffer, size);
                 break;
         case PS2IPS_ID_GETPEERNAME:
                 do_getpeername(rpcBuffer, size);
                 break;
         case PS2IPS_ID_GETSOCKOPT:
                 do_getsockopt(rpcBuffer, size);
                 break;
         case PS2IPS_ID_SETSOCKOPT:
                 do_setsockopt(rpcBuffer, size);
                 break;
 #ifdef PS2IP_DNS
         case PS2IPS_ID_GETHOSTBYNAME:
                 do_gethostbyname(rpcBuffer, size);
                 break;
         case PS2IPS_ID_DNS_SETSERVER:
                 do_dns_setserver(rpcBuffer, size);
                 break;
         case PS2IPS_ID_DNS_GETSERVER:
                 do_dns_getserver(rpcBuffer, size);
                 break;
 #endif
         default:
                 printf("PS2IPS: Unknown Function called!\n");
   }
   return rpcBuffer;
 }
References do_accept(), do_bind(), do_connect(), do_disconnect(), do_getconfig(), do_getpeername(), do_getsockname(), do_getsockopt(), do_ioctlsocket(), do_listen(), do_recv(), do_recvfrom(), do_select(), do_send(), do_sendto(), do_setconfig(), do_setsockopt(), do_socket(), printf(), PS2IPS_ID_ACCEPT, PS2IPS_ID_BIND, PS2IPS_ID_CONNECT, PS2IPS_ID_DISCONNECT, PS2IPS_ID_GETCONFIG, PS2IPS_ID_GETHOSTBYNAME, PS2IPS_ID_GETPEERNAME, PS2IPS_ID_GETSOCKNAME, PS2IPS_ID_GETSOCKOPT, PS2IPS_ID_IOCTL, PS2IPS_ID_LISTEN, PS2IPS_ID_RECV, PS2IPS_ID_RECVFROM, PS2IPS_ID_SELECT, PS2IPS_ID_SEND, PS2IPS_ID_SENDTO, PS2IPS_ID_SETCONFIG, PS2IPS_ID_SETSOCKOPT, and PS2IPS_ID_SOCKET.
Referenced by threadRpcFunction().
threadRpcFunction()
static void threadRpcFunction (void * arg) static
Definition at line 568 of file ps2ips.c.
 {
         printf("PS2IPS: RPC Thread Started\n");
         SifSetRpcQueue( &ps2ips_queue , GetThreadId() );
         SifRegisterRpc( &ps2ips_server, PS2IP_IRX, (void *)rpcHandlerFunction,(u8 *)&_rpc_buffer,NULL,NULL, &ps2ips_queue );
         SifRpcLoop( &ps2ips_queue );
 }
References _rpc_buffer, GetThreadId(), NULL, printf(), PS2IP_IRX, ps2ips_queue, ps2ips_server, rpcHandlerFunction(), SifRegisterRpc, SifRpcLoop, and SifSetRpcQueue.
Referenced by _start().
Variable Documentation
_rpc_buffer
int _rpc_buffer[512] static
Definition at line 47 of file ps2ips.c.
Referenced by do_connect(), do_ioctlsocket(), do_select(), and threadRpcFunction().
lwip_buffer
char lwip_buffer[BUFF_SIZE+32] static
Definition at line 49 of file ps2ips.c.
Referenced by do_recv(), do_recvfrom(), do_send(), and do_sendto().
ps2ips_queue
SifRpcDataQueue_t ps2ips_queue static
Definition at line 45 of file ps2ips.c.
Referenced by threadRpcFunction().
ps2ips_server
SifRpcServerData_t ps2ips_server static
Definition at line 46 of file ps2ips.c.
Referenced by threadRpcFunction().
rests
rests_pkt rests static
Definition at line 50 of file ps2ips.c.
Referenced by do_recv(), and do_recvfrom().