ps2sdk: common/include/ps2snd.h File Reference
ps2snd.h File Reference
#include <tamtypes.h>
#include <libsd.h>
Macros
#define STREAM_STEREO 1
#define STREAM_END_CLOSE 0x0000
#define STREAM_END_REPEAT 0x1000
#define BINDID_PS2SND 0x80068000
#define PS2SND_Init 4
#define PS2SND_SetParam 5
#define PS2SND_GetParam 6
#define PS2SND_SetSwitch 7
#define PS2SND_GetSwitch 8
#define PS2SND_SetAddr 9
#define PS2SND_GetAddr 10
#define PS2SND_SetCoreAttr 11
#define PS2SND_GetCoreAttr 12
#define PS2SND_Note2Pitch 13
#define PS2SND_Pitch2Note 14
#define PS2SND_ProcBatch 15
#define PS2SND_ProcBatchEx 16
#define PS2SND_VoiceTrans 17
#define PS2SND_BlockTrans 18
#define PS2SND_VoiceTransStatus 19
#define PS2SND_BlockTransStatus 20
#define PS2SND_SetTransCallback 21
#define PS2SND_SetIRQCallback 22
#define PS2SND_SetEffectAttr 23
#define PS2SND_GetEffectAttr 24
#define PS2SND_ClearEffectWorkArea 25
#define PS2SND_SetTransIntrHandler 26
#define PS2SND_SetSpu2IntrHandler 27
#define PS2SND_StreamOpen 64
#define PS2SND_StreamClose 65
#define PS2SND_StreamPlay 66
#define PS2SND_StreamPause 67
#define PS2SND_StreamSetPosition 68
#define PS2SND_StreamGetPosition 69
#define PS2SND_StreamSetVolume 70
#define PS2SND_QueryMaxFreeMemSize 99 /* XXX: Hack until i can figure out how to do it right */
Functions
int sndStreamOpen (char *file, u32 voices, u32 flags, u32 bufaddr, u32 bufsize)
int sndStreamClose (void)
int sndStreamPlay (void)
int sndStreamPause (void)
int sndStreamSetPosition (int block)
int sndStreamGetPosition (void)
int sndStreamSetVolume (int left, int right)
u32 sndQueryMaxFreeMemSize ()
Detailed Description
PS2SND definitions.
Definition in file ps2snd.h.
Macro Definition Documentation
BINDID_PS2SND
#define BINDID_PS2SND 0x80068000
Definition at line 26 of file ps2snd.h.
PS2SND_BlockTrans
#define PS2SND_BlockTrans 18
Definition at line 42 of file ps2snd.h.
PS2SND_BlockTransStatus
#define PS2SND_BlockTransStatus 20
Definition at line 44 of file ps2snd.h.
PS2SND_ClearEffectWorkArea
#define PS2SND_ClearEffectWorkArea 25
Definition at line 49 of file ps2snd.h.
PS2SND_GetAddr
#define PS2SND_GetAddr 10
Definition at line 34 of file ps2snd.h.
PS2SND_GetCoreAttr
#define PS2SND_GetCoreAttr 12
Definition at line 36 of file ps2snd.h.
PS2SND_GetEffectAttr
#define PS2SND_GetEffectAttr 24
Definition at line 48 of file ps2snd.h.
PS2SND_GetParam
#define PS2SND_GetParam 6
Definition at line 30 of file ps2snd.h.
PS2SND_GetSwitch
#define PS2SND_GetSwitch 8
Definition at line 32 of file ps2snd.h.
PS2SND_Init
#define PS2SND_Init 4
Definition at line 28 of file ps2snd.h.
PS2SND_Note2Pitch
#define PS2SND_Note2Pitch 13
Definition at line 37 of file ps2snd.h.
PS2SND_Pitch2Note
#define PS2SND_Pitch2Note 14
Definition at line 38 of file ps2snd.h.
PS2SND_ProcBatch
#define PS2SND_ProcBatch 15
Definition at line 39 of file ps2snd.h.
PS2SND_ProcBatchEx
#define PS2SND_ProcBatchEx 16
Definition at line 40 of file ps2snd.h.
PS2SND_QueryMaxFreeMemSize
#define PS2SND_QueryMaxFreeMemSize 99 /* XXX: Hack until i can figure out how to do it right */
Definition at line 62 of file ps2snd.h.
PS2SND_SetAddr
#define PS2SND_SetAddr 9
Definition at line 33 of file ps2snd.h.
PS2SND_SetCoreAttr
#define PS2SND_SetCoreAttr 11
Definition at line 35 of file ps2snd.h.
PS2SND_SetEffectAttr
#define PS2SND_SetEffectAttr 23
Definition at line 47 of file ps2snd.h.
PS2SND_SetIRQCallback
#define PS2SND_SetIRQCallback 22
Definition at line 46 of file ps2snd.h.
PS2SND_SetParam
#define PS2SND_SetParam 5
Definition at line 29 of file ps2snd.h.
PS2SND_SetSpu2IntrHandler
#define PS2SND_SetSpu2IntrHandler 27
Definition at line 51 of file ps2snd.h.
PS2SND_SetSwitch
#define PS2SND_SetSwitch 7
Definition at line 31 of file ps2snd.h.
PS2SND_SetTransCallback
#define PS2SND_SetTransCallback 21
Definition at line 45 of file ps2snd.h.
PS2SND_SetTransIntrHandler
#define PS2SND_SetTransIntrHandler 26
Definition at line 50 of file ps2snd.h.
PS2SND_StreamClose
#define PS2SND_StreamClose 65
Definition at line 54 of file ps2snd.h.
PS2SND_StreamGetPosition
#define PS2SND_StreamGetPosition 69
Definition at line 58 of file ps2snd.h.
PS2SND_StreamOpen
#define PS2SND_StreamOpen 64
Definition at line 53 of file ps2snd.h.
PS2SND_StreamPause
#define PS2SND_StreamPause 67
Definition at line 56 of file ps2snd.h.
PS2SND_StreamPlay
#define PS2SND_StreamPlay 66
Definition at line 55 of file ps2snd.h.
PS2SND_StreamSetPosition
#define PS2SND_StreamSetPosition 68
Definition at line 57 of file ps2snd.h.
PS2SND_StreamSetVolume
#define PS2SND_StreamSetVolume 70
Definition at line 59 of file ps2snd.h.
PS2SND_VoiceTrans
#define PS2SND_VoiceTrans 17
Definition at line 41 of file ps2snd.h.
PS2SND_VoiceTransStatus
#define PS2SND_VoiceTransStatus 19
Definition at line 43 of file ps2snd.h.
STREAM_END_CLOSE
#define STREAM_END_CLOSE 0x0000
Definition at line 23 of file ps2snd.h.
STREAM_END_REPEAT
#define STREAM_END_REPEAT 0x1000
Definition at line 24 of file ps2snd.h.
STREAM_STEREO
#define STREAM_STEREO 1
Definition at line 22 of file ps2snd.h.
Function Documentation
sndQueryMaxFreeMemSize()
u32 sndQueryMaxFreeMemSize ()
sndStreamClose()
int sndStreamClose (void)
Definition at line 269 of file adpcm-stream.c.
 {
         if (stream_status==STATUS_PLAYING)
                 sndStreamPause();
         if (stream_status==STATUS_CLOSED)
                 return(-1);
         if (stream_thid>=0)
                 DeleteThread(stream_thid);
         close(stream_fd);
         FreeSysMemory(stream_buf);
         sceSdSetSpu2IntrHandler(NULL, NULL);
         stream_status = STATUS_CLOSED;
         dprintf(OUT_INFO, "Closed!\n");
         return(0);
 }
References close(), DeleteThread(), dprintf, FreeSysMemory(), NULL, OUT_INFO, sceSdSetSpu2IntrHandler(), sndStreamPause(), STATUS_CLOSED, STATUS_PLAYING, stream_buf, stream_fd, stream_status, and stream_thid.
Referenced by rpc_server(), sndStreamOpen(), sndStreamSetPosition(), and stream_thread().
sndStreamGetPosition()
int sndStreamGetPosition (void)
Definition at line 378 of file adpcm-stream.c.
 {
         int i;
         if (stream_status==STATUS_CLOSED)
                 return(-1);
         if (stream_status==STATUS_OPEN)
                 return(stream_cur);
         /* During playback we can get the current position in the buffer from the SPU2! */
         i = sceSdGetAddr(stream_voice[0] | SD_VADDR_NAX);
         i -= stream_bufspu[0]+(stream_buflen*stream_bufid);
         i /= 16;
         return(stream_cur+i);
 }
References sceSdGetAddr(), SD_VADDR_NAX, STATUS_CLOSED, STATUS_OPEN, stream_bufid, stream_buflen, stream_bufspu, stream_cur, stream_status, and stream_voice.
Referenced by rpc_server().
sndStreamOpen()
int sndStreamOpen (char * file, u32 voices, u32 flags, u32 bufaddr, u32 bufsize)
Definition at line 149 of file adpcm-stream.c.
 {
         iop_thread_t thread;
         dprintf(OUT_DEBUG, "%s\n", file);
         if (stream_status)
         {
                 dprintf(OUT_WARNING, "There's a stream already open\n");
                 return(-1);
         }
         stream_voice[0] = voices&0xffff;
         stream_voice[1] = (voices>>16)&0xffff;
         dprintf(OUT_INFO, "%s  Voices %d:%d and %d:%d\n", file, (int)stream_voice[0]&1, (int)stream_voice[0]>>1, (int)stream_voice[1]&1, (int)stream_voice[1]>>1);
         if ((stream_voice[0]&1) != (stream_voice[1]&1))
         {
                 dprintf(OUT_ERROR, "Stream voices arn't on the same core!!!!\n");
                 return(-1);
         }
         /* Setup Semaphore */
         if (stream_sema<0)
         {
                 iop_sema_t sema;
                 sema.attr = 0;
                 sema.option = 0;
                 sema.initial = 0;
                 sema.max = 1;
                 stream_sema = CreateSema(&sema);
                 if (stream_sema<0)
                         dprintf(OUT_ERROR, "Failed to get a semaphore\n");
         }
         stream_buflen = bufsize*16;
         stream_flags = flags&0xffff; /* only the bottom 16bits are for user use! */
         stream_buf = AllocSysMemory(ALLOC_FIRST, stream_buflen, NULL);
         if (stream_buf==NULL)
         {
                 dprintf(OUT_ERROR, "malloc failed (%u bytes)\n", (unsigned int)stream_buflen);
                 return(-2);
         }
         /* Try to open file... */
         stream_fd = open(file, O_RDONLY);
         if (stream_fd<0)
         {
                 dprintf(OUT_ERROR, "open failed (%d)\n", stream_fd);
                 FreeSysMemory(stream_buf);
                 return(-3);
         }
         stream_bufspu[0] = bufaddr;
         stream_bufspu[1] = bufaddr + (stream_buflen*2);
         /* Setup SPU2 voice volumes.... */
         if (stream_flags&FLAG_STEREO)
         {
                 dprintf(OUT_INFO, "stereo...\n");
                 stream_chans = 2;
                 sceSdSetParam(stream_voice[0] | SD_VPARAM_VOLL,  0x1fff);
                 sceSdSetParam(stream_voice[0] | SD_VPARAM_VOLR,  0);
                 sceSdSetParam(stream_voice[1] | SD_VPARAM_VOLL,  0);
                 sceSdSetParam(stream_voice[1] | SD_VPARAM_VOLR,  0x1fff);
         }
         else
         {
                 dprintf(OUT_INFO, "mono...\n");
                 stream_chans = 1;
                 sceSdSetParam(stream_voice[0] | SD_VPARAM_VOLL,  0x1fff);
                 sceSdSetParam(stream_voice[0] | SD_VPARAM_VOLR,  0x1fff);
         }
         /* Setup other SPU2 voice stuff... */
         for (int i=0;i<stream_chans;i++) /* XXX */
         {
                 sceSdSetParam(stream_voice[i] | SD_VPARAM_PITCH, 0x1000); /* 0x1000 = normal pitch */
                 sceSdSetParam(stream_voice[i] | SD_VPARAM_ADSR1, SD_SET_ADSR1(SD_ADSR_AR_EXPi, 0, 0xf, 0xf));
                 sceSdSetParam(stream_voice[i] | SD_VPARAM_ADSR2, SD_SET_ADSR2(SD_ADSR_SR_EXPd, 127, SD_ADSR_RR_EXPd, 0));
         }
         /* Get a thread */
         thread.attr      = TH_C;
         thread.thread    = stream_thread;
         thread.priority  = 40;
         thread.stacksize = 0x800;
         thread.option    = 0;
         stream_thid = CreateThread(&thread);
         if (stream_thid<0)
         {
                 dprintf(OUT_ERROR, "Failed to make play thread\n");
                 sndStreamClose();
                 return(-1);
         }
         /* Start the thread (it'll wait patiently until it gets an interrupt) */
         StartThread(stream_thid, NULL);
         /* Get some interrupts going! */
         sceSdSetCoreAttr(SD_CORE_IRQ_ENABLE, 0); /* disable pesky interrupts for a minute */
         sceSdSetSpu2IntrHandler(stream_handler, (void*)1);
         stream_status = STATUS_OPEN;
         stream_cur = 0;
         if (sndStreamSetPosition(0)<0)
         {
                 sndStreamClose();
                 return(-1);
         }
         dprintf(OUT_INFO, "Opened %s\n", file);
         return(0);
 }
References ALLOC_FIRST, AllocSysMemory(), iop_thread_t::attr, iop_sema_t::attr, CreateSema(), CreateThread(), dprintf, FLAG_STEREO, FreeSysMemory(), iop_sema_t::initial, iop_sema_t::max, NULL, O_RDONLY, open(), iop_thread_t::option, iop_sema_t::option, OUT_DEBUG, OUT_ERROR, OUT_INFO, OUT_WARNING, iop_thread_t::priority, sceSdSetCoreAttr(), sceSdSetParam(), sceSdSetSpu2IntrHandler(), SD_ADSR_AR_EXPi, SD_ADSR_RR_EXPd, SD_ADSR_SR_EXPd, SD_CORE_IRQ_ENABLE, SD_SET_ADSR1, SD_SET_ADSR2, SD_VPARAM_ADSR1, SD_VPARAM_ADSR2, SD_VPARAM_PITCH, SD_VPARAM_VOLL, SD_VPARAM_VOLR, sndStreamClose(), sndStreamSetPosition(), iop_thread_t::stacksize, StartThread(), STATUS_OPEN, stream_buf, stream_buflen, stream_bufspu, stream_chans, stream_cur, stream_fd, stream_flags, stream_handler(), stream_sema, stream_status, stream_thid, stream_thread(), stream_voice, TH_C, and iop_thread_t::thread.
Referenced by rpc_server().
sndStreamPause()
int sndStreamPause (void)
Definition at line 313 of file adpcm-stream.c.
 {
         if (stream_status==STATUS_CLOSED)
                 return(-1);
         if (stream_status==STATUS_OPEN)
                 return(0);
         /* Release keys */
         if (stream_chans>1)
                 sceSdSetSwitch((stream_voice[0]&1) | SD_SWITCH_KEYUP, 1<<(stream_voice[0]>>1) | 1<<(stream_voice[1]>>1));
         else
                 sceSdSetSwitch((stream_voice[0]&1) | SD_SWITCH_KEYUP, 1<<(stream_voice[0]>>1));
         sceSdSetCoreAttr(SD_CORE_IRQ_ENABLE, 0); /* disable pesky interrupts for a minute */
         stream_status=STATUS_OPEN;
         dprintf(OUT_INFO, "Paused!\n");
         return(1);
 }
References dprintf, OUT_INFO, sceSdSetCoreAttr(), sceSdSetSwitch(), SD_CORE_IRQ_ENABLE, SD_SWITCH_KEYUP, STATUS_CLOSED, STATUS_OPEN, stream_chans, stream_status, and stream_voice.
Referenced by rpc_server(), sndStreamClose(), and sndStreamSetPosition().
sndStreamPlay()
int sndStreamPlay (void)
Definition at line 291 of file adpcm-stream.c.
 {
         if (stream_status==STATUS_CLOSED)
                 return(-1);
         if (stream_status==STATUS_PLAYING)
                 return(0);
         /* Press down the keys :) */
         if (stream_chans>1)
                 sceSdSetSwitch((stream_voice[0]&1) | SD_SWITCH_KEYDOWN, 1<<(stream_voice[0]>>1) | 1<<(stream_voice[1]>>1));
         else
                 sceSdSetSwitch((stream_voice[0]&1) | SD_SWITCH_KEYDOWN, 1<<(stream_voice[0]>>1));
         sceSdSetCoreAttr(SD_CORE_IRQ_ENABLE, 1);
         stream_status=STATUS_PLAYING;
         dprintf(OUT_INFO, "Playing!\n");
         return(1);
 }
References dprintf, OUT_INFO, sceSdSetCoreAttr(), sceSdSetSwitch(), SD_CORE_IRQ_ENABLE, SD_SWITCH_KEYDOWN, STATUS_CLOSED, STATUS_PLAYING, stream_chans, stream_status, and stream_voice.
Referenced by rpc_server(), and sndStreamSetPosition().
sndStreamSetPosition()
int sndStreamSetPosition (int block)
Definition at line 334 of file adpcm-stream.c.
 {
         int chunk;
         int r=0;
         if (stream_status==STATUS_CLOSED)
                 return(-1);
         if (stream_status==STATUS_PLAYING)
                 r = sndStreamPause();
         if (block<0)
                 return(-2);
         /* lock block number to a chunk */
         chunk = (stream_buflen/16)*stream_chans;
         dprintf(OUT_DEBUG, "chunk = %d\n", chunk);
         block = (block/chunk)*chunk;
         stream_cur = block;
         lseek(stream_fd, block*16*stream_chans, SEEK_SET);
         stream_bufid = 0;
         sceSdSetAddr(SD_ADDR_IRQA, stream_bufspu[0]+stream_buflen);
         for (int i=0;i<2;i++)
         for (int c=0;c<stream_chans;c++)
         if (fillbuf(i, c)<=0)
                 {
                         dprintf(OUT_ERROR, "Hit EOF or error on buffer fill %d\n", i);
                         sndStreamClose();
                         return(-1);
                 }
         for (int c=0;c<stream_chans;c++)
                 sceSdSetAddr(stream_voice[c] | SD_VADDR_SSA, stream_bufspu[c]);
         /* Restart playing if we were playing before */
         if (r)
                 sndStreamPlay();
         dprintf(OUT_INFO, "Position %d!\n", stream_cur);
         return(block);
 }
References dprintf, fillbuf(), lseek(), OUT_DEBUG, OUT_ERROR, OUT_INFO, sceSdSetAddr(), SD_ADDR_IRQA, SD_VADDR_SSA, SEEK_SET, sndStreamClose(), sndStreamPause(), sndStreamPlay(), STATUS_CLOSED, STATUS_PLAYING, stream_bufid, stream_buflen, stream_bufspu, stream_chans, stream_cur, stream_fd, stream_status, and stream_voice.
Referenced by rpc_server(), and sndStreamOpen().
sndStreamSetVolume()
int sndStreamSetVolume (int left, int right)
Definition at line 395 of file adpcm-stream.c.
 {
         if (stream_status==STATUS_CLOSED)
                 return(-1);
         if (stream_chans>1)
         {
                 sceSdSetParam(stream_voice[0] | SD_VPARAM_VOLL,  left);
                 sceSdSetParam(stream_voice[0] | SD_VPARAM_VOLR,  0);
                 sceSdSetParam(stream_voice[1] | SD_VPARAM_VOLL,  0);
                 sceSdSetParam(stream_voice[1] | SD_VPARAM_VOLR,  right);
         }
         else
         {
                 sceSdSetParam(stream_voice[0] | SD_VPARAM_VOLL,  left);
                 sceSdSetParam(stream_voice[0] | SD_VPARAM_VOLR,  right);
         }
         return(0);
 }
References sceSdSetParam(), SD_VPARAM_VOLL, SD_VPARAM_VOLR, STATUS_CLOSED, stream_chans, stream_status, and stream_voice.
Referenced by rpc_server().