ps2sdk: iop/system/rmman/include/rmman.h File Reference
rmman.h File Reference
#include <types.h>
#include <irx.h>
#include <librm-common.h>
Macros
#define rmman_IMPORTS_start DECLARE_IMPORT_TABLE(rmman, 1, 1)
#define rmman_IMPORTS_end END_IMPORT_TABLE
#define I_rmmanInit DECLARE_IMPORT(4, rmmanInit)
#define I_rmmanOpen DECLARE_IMPORT(5, rmmanOpen)
#define I_rmmanClose DECLARE_IMPORT(6, rmmanClose)
#define I_rmmanEnd DECLARE_IMPORT(7, rmmanEnd)
Functions
int rmmanInit (void)
int rmmanOpen (int port, int slot, void *buffer)
int rmmanClose (int port, int slot)
int rmmanEnd (void)
Detailed Description
RMMAN definitions
Definition in file rmman.h.
Macro Definition Documentation
I_rmmanClose
#define I_rmmanClose DECLARE_IMPORT(6, rmmanClose)
Definition at line 33 of file rmman.h.
I_rmmanEnd
#define I_rmmanEnd DECLARE_IMPORT(7, rmmanEnd)
Definition at line 34 of file rmman.h.
I_rmmanInit
#define I_rmmanInit DECLARE_IMPORT(4, rmmanInit)
Definition at line 31 of file rmman.h.
I_rmmanOpen
#define I_rmmanOpen DECLARE_IMPORT(5, rmmanOpen)
Definition at line 32 of file rmman.h.
rmman_IMPORTS_end
#define rmman_IMPORTS_end END_IMPORT_TABLE
Definition at line 29 of file rmman.h.
rmman_IMPORTS_start
#define rmman_IMPORTS_start DECLARE_IMPORT_TABLE(rmman, 1, 1)
Definition at line 28 of file rmman.h.
Function Documentation
rmmanClose()
int rmmanClose (int port, int slot)
Definition at line 148 of file rmman.c.
 {
         int result;
         struct RmData *pRmData;
         u32 bits;
         if((portStatus[port] >> slot) & 1)
         {
                 pRmData = &RmData[port][slot];
                 if(pRmData->state != RM_STATE_FINDRM)
                 {
                         SetEventFlag(pRmData->eventFlagID, RM_EF_EXIT_THREAD);
                         WaitEventFlag(pRmData->eventFlagID, RM_EF_EXIT_THREAD_DONE, WEF_AND|WEF_CLEAR, &bits);
                         if(pRmData->closed != 0)
                         {       //Remote Control port was closed successfully.
                                 portStatus[port] ^= (1 << slot);
                                 result = 1;
                         } else {
                                 result = 0;
                         }
                 } else {
                         portStatus[port] ^= (1 << slot);
                         result = 1;
                 }
         } else
                 result = 0;
         return result;
 }
References RmData::closed, RmData::eventFlagID, RmData::port, portStatus, result, RM_EF_EXIT_THREAD, RM_EF_EXIT_THREAD_DONE, RM_STATE_FINDRM, SetEventFlag(), RmData::slot, RmData::state, WaitEventFlag(), WEF_AND, and WEF_CLEAR.
Referenced by rmmanEnd(), and RmmanRpc_close().
rmmanEnd()
int rmmanEnd (void)
Definition at line 180 of file rmman.c.
 {
         u32 bits;
         int port, slot, result;
         if(IsInitialized != 0)
         {
                 for(port = 0; port < 2; port++)
                 {
                         for(slot = 0; slot < 4; slot++)
                         {       //If port,slot is opened, close it.
                                 if((portStatus[port] >> slot) & 1)
                                         rmmanClose(port, slot);
                         }
                 }
                 SetEventFlag(eventFlagID, RM_EF_EXIT_THREAD);
                 WaitEventFlag(eventFlagID, RM_EF_EXIT_THREAD_DONE, WEF_AND|WEF_CLEAR, &bits);
                 DeleteEventFlag(eventFlagID);
                 eventFlagID = 0;
                 if(DeleteThread(eventFlagID) == 0)
                 {
                         MainThreadID = 0;
                         IsInitialized = 0;
                         result = 1;
                 } else
                         result = 0;
         } else
                 result = 1;
         return result;
 }
References DeleteEventFlag(), DeleteThread(), eventFlagID, IsInitialized, MainThreadID, RmData::port, portStatus, result, RM_EF_EXIT_THREAD, RM_EF_EXIT_THREAD_DONE, rmmanClose(), SetEventFlag(), RmData::slot, WaitEventFlag(), WEF_AND, and WEF_CLEAR.
Referenced by RmmanRpc_end().
rmmanInit()
int rmmanInit (void)
Definition at line 86 of file rmman.c.
 {
         iop_event_t EventFlagData;
         iop_thread_t ThreadData;
         int result;
         portStatus[0] = 0;
         portStatus[1] = 0;
         IsInitialized = 1;
         EventFlagData.attr = 2;
         EventFlagData.bits = 0;
         if((eventFlagID = CreateEventFlag(&EventFlagData)) != 0)
         {
                 ThreadData.attr = TH_C;
                 ThreadData.thread = &MainThread;
                 ThreadData.priority = 0x2E;
                 ThreadData.stacksize = 0x800;
                 if((MainThreadID = CreateThread(&ThreadData)) != 0)
                 {
                         StartThread(MainThreadID, NULL);
                         result=MainThreadID;
                 }
                 else result=0;
         }
         else result=0;
         return result;
 }
References iop_thread_t::attr, iop_event_t::attr, iop_event_t::bits, CreateEventFlag(), CreateThread(), EventFlagData, eventFlagID, IsInitialized, MainThread(), MainThreadID, NULL, portStatus, iop_thread_t::priority, result, iop_thread_t::stacksize, StartThread(), TH_C, and iop_thread_t::thread.
Referenced by RmmanRpc_init().
rmmanOpen()
int rmmanOpen (int port, int slot, void * buffer)
Definition at line 115 of file rmman.c.
 {
         iop_event_t evf;
         int result;
         struct RmData *pRmData;
         if(!((portStatus[port] >> slot) & 1))
         {
                 pRmData = &RmData[port][slot];
                 pRmData->port = port;
                 pRmData->slot = slot;
                 pRmData->state = RM_STATE_EXECCMD;
                 pRmData->reqState = RM_RSTATE_COMPLETE;
                 pRmData->eeBuffer = buffer;
                 pRmData->currentTask = RM_TASK_QUERY;
                 pRmData->counter = 0;
                 evf.attr = EA_MULTI;
                 evf.bits = 0;
                 if((pRmData->eventFlagID = CreateEventFlag(&evf)) != 0)
                 {
                         pRmData->powerMode = 0;
                         portStatus[port] |= (1 << slot);
                         result = 1;
                 } else
                         result = 0;
         } else
                 result = 0;
         return result;
 }
References iop_event_t::attr, iop_event_t::bits, buffer, RmData::counter, CreateEventFlag(), RmData::currentTask, EA_MULTI, RmData::eeBuffer, RmData::eventFlagID, RmData::port, portStatus, RmData::powerMode, RmData::reqState, result, RM_RSTATE_COMPLETE, RM_STATE_EXECCMD, RM_TASK_QUERY, RmData::slot, and RmData::state.
Referenced by RmmanRpc_open().