ps2sdk: iop/system/rmman/src/rmman.c File Reference
rmman.c File Reference
#include <intrman.h>
#include <loadcore.h>
#include <sifcmd.h>
#include <sifman.h>
#include <stdio.h>
#include <thbase.h>
#include <thevent.h>
#include <vblank.h>
#include <rsio2man.h>
#include <irx.h>
#include "rmman.h"
Data Structures
struct RmData
Macros
#define RM_EF_EXIT_THREAD 1
#define RM_EF_EXIT_THREAD_DONE 2
#define RM_EF_CLOSE_PORT 4
#define RM_EF_CLOSE_PORT_DONE 8
Enumerations
enum RM_TASK {
RM_TASK_QUERY = 0 ,
RM_TASK_INIT ,
RM_TASK_POLL
}
Functions
IRX_ID ("rmman", 1, 16)
static int CreateMainThread (void)
static void MainThread (void *arg)
static int HandleTasks (struct RmData *RmData)
static int FindRemote (struct RmData *RmData)
static int InitFindRmCmd (struct RmData *RmData)
static int PollRemote (struct RmData *RmData)
static int InitPollRmCmd (struct RmData *RmData)
static int RmExecute (struct RmData *RmData)
static int DmaSendEE (struct RmData *RmData)
static int HandleRmTaskFailed (struct RmData *RmData)
static int InitRemote (struct RmData *RmData)
static int InitInitRmCmd (struct RmData *RmData)
int _start (int argc, char *argv[])
int rmmanInit (void)
int rmmanOpen (int port, int slot, void *buffer)
int rmmanClose (int port, int slot)
int rmmanEnd (void)
static int rmmanVersion (void)
static void * RmmanRpc_init (struct rmRpcPacket *packet)
static void * RmmanRpc_version (struct rmRpcPacket *packet)
static void * RmmanRpc_open (struct rmRpcPacket *packet)
static void * RmmanRpc_end (struct rmRpcPacket *packet)
static void * RmmanRpc_close (struct rmRpcPacket *packet)
static void * RpcHandler (int fno, void *buffer, int len)
static void RpcThread (void *arg)
Variables
struct irx_export_table _exp_rmman
static struct RmData RmData [2][4]
static int portStatus [2]
static int eventFlagID
static int MainThreadID
static int IsInitialized
static int RpcThreadID
static SifRpcDataQueue_t RpcDataQueue
static SifRpcServerData_t RpcServerData
static struct rmRpcPacket RpcDataBuffer
Macro Definition Documentation
RM_EF_CLOSE_PORT
#define RM_EF_CLOSE_PORT 4
Definition at line 18 of file rmman.c.
RM_EF_CLOSE_PORT_DONE
#define RM_EF_CLOSE_PORT_DONE 8
Definition at line 19 of file rmman.c.
RM_EF_EXIT_THREAD
#define RM_EF_EXIT_THREAD 1
Definition at line 16 of file rmman.c.
RM_EF_EXIT_THREAD_DONE
#define RM_EF_EXIT_THREAD_DONE 2
Definition at line 17 of file rmman.c.
Enumeration Type Documentation
RM_TASK
enum RM_TASK
Enumerator
RM_TASK_QUERY
RM_TASK_INIT
RM_TASK_POLL
Definition at line 21 of file rmman.c.
              {
         RM_TASK_QUERY = 0,
         RM_TASK_INIT,
         RM_TASK_POLL
 };
Function Documentation
_start()
int _start (int argc, char * argv[])
Definition at line 73 of file rmman.c.
 {
         int result;
         if(RegisterLibraryEntries(&_exp_rmman) == 0)
         {
                 result = CreateMainThread() <= 0 ? MODULE_NO_RESIDENT_END : MODULE_RESIDENT_END;
         }
         else result = MODULE_NO_RESIDENT_END;
         return result;
 }
References _exp_rmman, CreateMainThread(), MODULE_NO_RESIDENT_END, MODULE_RESIDENT_END, RegisterLibraryEntries(), and result.
CreateMainThread()
static int CreateMainThread (void) static
Definition at line 539 of file rmman.c.
 {
         iop_thread_t ThreadData;
         int result;
         ThreadData.attr=TH_C;
         ThreadData.thread=&RpcThread;
         ThreadData.priority=0x2E;
         ThreadData.stacksize=0x800;
         if((RpcThreadID=CreateThread(&ThreadData))!=0)
         {
                 StartThread(RpcThreadID, NULL);
                 result = 1;
         }
         else result = 0;
         return result;
 }
Referenced by _start().
DmaSendEE()
static int DmaSendEE (struct RmData * RmData) static
Definition at line 415 of file rmman.c.
 {
         SifDmaTransfer_t dmat;
         int i, OldState, dmatID;
         RmData->eeData.frame = RmData->frame;
         RmData->frame++;
         for(i = 0; i < sizeof(RmData->eeData.data); i++)
                 RmData->eeData.data[i] = RmData->outBuffer[i];
         RmData->eeData.state = RmData->state;
         RmData->eeData.connected = RmData->connected;
         dmat.src = &RmData->eeData;
         dmat.dest = ((RmData->frame & 1) == 0) ? (u8*)RmData->eeBuffer : (u8*)RmData->eeBuffer + 128;
         dmat.size = 128;
         dmat.attr = 0;
         CpuSuspendIntr(&OldState);
         dmatID = sceSifSetDma(&dmat, 1);
         CpuResumeIntr(OldState);
         return(dmatID > 0);
 }
References SifDmaTransfer_t::attr, rmEEData::connected, RmData::connected, CpuResumeIntr(), CpuSuspendIntr(), rmEEData::data, SifDmaTransfer_t::dest, RmData::eeBuffer, RmData::eeData, rmEEData::frame, RmData::frame, RmData::outBuffer, sceSifSetDma(), SifDmaTransfer_t::size, SifDmaTransfer_t::src, rmEEData::state, and RmData::state.
Referenced by HandleTasks().
FindRemote()
static int FindRemote (struct RmData * RmData) static
Definition at line 306 of file rmman.c.
 {
         int result;
         InitFindRmCmd(RmData);
         if(RmExecute(RmData) != 0)
         {
                 if(RmData->port < 2)
                 {
                         switch(RmData->outBuffer[1])
{
                                 case 0x12:
                                         result = 1;
                                         break;
                                 case 0x1F:
                                         InitRemote(RmData);
                                         result = 1;
                                         break;
                                 default:
                                         RmData->connected = 0;
                                         result = 0;
                         }
                 } else
                         result = 1;
         } else
                 result = 0;
         return result;
 }
References RmData::connected, InitFindRmCmd(), InitRemote(), RmData::outBuffer, RmData::port, result, and RmExecute().
Referenced by HandleTasks().
HandleRmTaskFailed()
static int HandleRmTaskFailed (struct RmData * RmData) static
Definition at line 403 of file rmman.c.
 {
         if(RmData->counter + 1 < 10)
         {
                 RmData->counter++;
                 return RmData->counter;
         } else {
                 RmData->currentTask = RM_TASK_QUERY;
                 return 0;
         }
 }
References RmData::counter, RmData::currentTask, and RM_TASK_QUERY.
Referenced by HandleTasks().
HandleTasks()
static int HandleTasks (struct RmData * RmData) static
Definition at line 257 of file rmman.c.
 {
         switch(RmData->currentTask)
         {
                 case RM_TASK_QUERY:
                         if(RmData->counter == 0 && FindRemote(RmData) != 0)
{
                                 RmData->counter = 0;
                                 RmData->state = RM_STATE_EXECCMD;
                                 RmData->currentTask++;
                          } else {
                                  if(RmData->counter < 10)
{
                                          RmData->counter++;
                                          RmData->state = RM_STATE_FINDRM;
                                  } else {
                                          RmData->counter = 0;
                                  }
                          }
                         break;
                 case RM_TASK_INIT:
                         if(InitRemote(RmData) != 0)
{
                                 RmData->counter = 0;
                                 RmData->currentTask++;
                         } else {
                                 HandleRmTaskFailed(RmData);
                         }
                         break;
                 case RM_TASK_POLL:
                         RmData->state = RM_STATE_STABLE;
                         if(PollRemote(RmData) != 0)
{
                                 RmData->counter = 0;
                                 if(RmData->reqState == RM_RSTATE_BUSY)
                                         RmData->reqState = RM_RSTATE_COMPLETE;
                         } else {
                                 if(HandleRmTaskFailed(RmData) == 0 && RmData->reqState == RM_RSTATE_BUSY)
                                         RmData->reqState = RM_RSTATE_FAILED;
                         }
                         break;
         }
         DmaSendEE(RmData);
         return 1;
 }
References RmData::counter, RmData::currentTask, DmaSendEE(), FindRemote(), HandleRmTaskFailed(), InitRemote(), PollRemote(), RmData::reqState, RM_RSTATE_BUSY, RM_RSTATE_COMPLETE, RM_RSTATE_FAILED, RM_STATE_EXECCMD, RM_STATE_FINDRM, RM_STATE_STABLE, RM_TASK_INIT, RM_TASK_POLL, RM_TASK_QUERY, and RmData::state.
Referenced by MainThread().
InitFindRmCmd()
static int InitFindRmCmd (struct RmData * RmData) static
Definition at line 336 of file rmman.c.
 {
         int i;
         //The original was setting these, byte by byte.
         RmData->sio2Data.port_ctrl1[RmData->port] = 0xFFC0050F;
         RmData->sio2Data.port_ctrl2[RmData->port] = 0x00060014;
         RmData->sio2Data.port_ctrl2[RmData->port] = (RmData->sio2Data.port_ctrl2[RmData->port] & ~0x03000000) | 0x01000000;
         RmData->sio2Data.in = RmData->inBuffer;
         RmData->sio2Data.out = RmData->outBuffer;
         RmData->inBuffer[0] = 0x61;
         RmData->sio2Data.in_size = 7;
         RmData->sio2Data.out_size = 7;
         RmData->sio2Data.regdata[1] = 0;
         RmData->inBuffer[1] = 0x0F;
         RmData->sio2Data.regdata[0] = (RmData->sio2Data.regdata[0] & ~3) | (RmData->port & 3);
         RmData->sio2Data.regdata[0] = (RmData->sio2Data.regdata[0] & ~0x000000C0) | 0x40;
         RmData->sio2Data.regdata[0] = (RmData->sio2Data.regdata[0] & ~0x0001FF00) | 0x00700;
         RmData->sio2Data.regdata[0] = (RmData->sio2Data.regdata[0] & ~0x07FC0000) | 0x001C0000;
         for(i = 2; i < 7; i++)
                 RmData->inBuffer[i] = 0;
         return 1;
 }
References sio2_transfer_data_t::in, sio2_transfer_data_t::in_size, RmData::inBuffer, sio2_transfer_data_t::out, sio2_transfer_data_t::out_size, RmData::outBuffer, RmData::port, sio2_transfer_data_t::port_ctrl1, sio2_transfer_data_t::port_ctrl2, sio2_transfer_data_t::regdata, and RmData::sio2Data.
Referenced by FindRemote().
InitInitRmCmd()
static int InitInitRmCmd (struct RmData * RmData) static
Definition at line 446 of file rmman.c.
 {
         int i;
         RmData->inBuffer[0] = 0x61;
         RmData->inBuffer[1] = 0x06;
         RmData->inBuffer[2] = (u8)RmData->powerMode;
         for(i = 3; i < 7; i++)
                 RmData->inBuffer[i] = 0;
         return 1;
 }
References RmData::inBuffer, and RmData::powerMode.
Referenced by InitRemote().
InitPollRmCmd()
static int InitPollRmCmd (struct RmData * RmData) static
Definition at line 371 of file rmman.c.
 {
         int i;
         RmData->inBuffer[0] = 0x61;
         RmData->inBuffer[1] = 0x04;
         for(i = 2; i < 7; i++)
                 RmData->inBuffer[i] = 0;
         return 1;
 }
References RmData::inBuffer.
Referenced by PollRemote().
InitRemote()
static int InitRemote (struct RmData * RmData) static
Definition at line 440 of file rmman.c.
 {
         InitInitRmCmd(RmData);
         return(RmExecute(RmData) > 0);
 }
References InitInitRmCmd(), and RmExecute().
Referenced by FindRemote(), HandleTasks(), and MainThread().
IRX_ID()
IRX_ID ("rmman" , 1 , 16)
MainThread()
static void MainThread (void * arg) static
Definition at line 214 of file rmman.c.
 {
         iop_event_info_t evfInfo;
         int port, slot;
         while(1)
         {
                 WaitVblankStart();
                 ReferEventFlagStatus(eventFlagID, &evfInfo);
                 if(evfInfo.currBits == RM_EF_EXIT_THREAD)
                 {
                         SetEventFlag(eventFlagID, RM_EF_EXIT_THREAD_DONE);
                         ExitThread();
                 }
                 for(port = 0; port < 2; port++)
                 {
                         for(slot = 0; slot < 4; slot++)
{
                                 if((portStatus[port] >> slot) & 1)
{
                                         ReferEventFlagStatus(RmData[port][slot].eventFlagID, &evfInfo);
                                         if(evfInfo.currBits == RM_EF_CLOSE_PORT)
{
                                                 RmData[port][slot].powerMode = 3;
                                                 if(InitRemote(&RmData[port][slot]) == 0)
                                                         RmData[port][slot].closed = 0;
                                                 else
                                                         RmData[port][slot].closed = 1;
                                                 SetEventFlag(RmData[port][slot].eventFlagID, RM_EF_CLOSE_PORT_DONE);
                                         } else {
                                                 HandleTasks(&RmData[port][slot]);
                                         }
                                 }
                         }
                 }
         }
 }
References RmData::closed, iop_event_info_t::currBits, eventFlagID, ExitThread(), HandleTasks(), InitRemote(), RmData::port, portStatus, RmData::powerMode, ReferEventFlagStatus(), RM_EF_CLOSE_PORT, RM_EF_CLOSE_PORT_DONE, RM_EF_EXIT_THREAD, RM_EF_EXIT_THREAD_DONE, SetEventFlag(), RmData::slot, and WaitVblankStart().
Referenced by rmmanInit().
PollRemote()
static int PollRemote (struct RmData * RmData) static
Definition at line 365 of file rmman.c.
 {
         InitPollRmCmd(RmData);
         return(RmExecute(RmData) > 0);
 }
References InitPollRmCmd(), and RmExecute().
Referenced by HandleTasks().
RmExecute()
static int RmExecute (struct RmData * RmData) static
Definition at line 383 of file rmman.c.
 {
         int result;
         sio2_rm_transfer_init();
         sio2_transfer(&RmData->sio2Data);
         sio2_transfer_reset();
         if(((RmData->sio2Data.stat6c >> 14) & 3) == 0)
         {
                 RmData->connected = 1;
                 result = 1;
         } else {
                 RmData->connected = 0;
                 result = 0;
         }
         return result;
 }
References RmData::connected, result, sio2_rm_transfer_init(), sio2_transfer(), sio2_transfer_reset(), RmData::sio2Data, and sio2_transfer_data_t::stat6c.
Referenced by FindRemote(), InitRemote(), and PollRemote().
rmmanClose()
int rmmanClose (int port, int slot)
Definition at line 148 of file rmman.c.
 {
         int result;
         struct RmData *pRmData;
         u32 bits;
         if((portStatus[port] >> slot) & 1)
         {
                 pRmData = &RmData[port][slot];
                 if(pRmData->state != RM_STATE_FINDRM)
                 {
                         SetEventFlag(pRmData->eventFlagID, RM_EF_EXIT_THREAD);
                         WaitEventFlag(pRmData->eventFlagID, RM_EF_EXIT_THREAD_DONE, WEF_AND|WEF_CLEAR, &bits);
                         if(pRmData->closed != 0)
                         {       //Remote Control port was closed successfully.
                                 portStatus[port] ^= (1 << slot);
                                 result = 1;
                         } else {
                                 result = 0;
                         }
                 } else {
                         portStatus[port] ^= (1 << slot);
                         result = 1;
                 }
         } else
                 result = 0;
         return result;
 }
References RmData::closed, RmData::eventFlagID, RmData::port, portStatus, result, RM_EF_EXIT_THREAD, RM_EF_EXIT_THREAD_DONE, RM_STATE_FINDRM, SetEventFlag(), RmData::slot, RmData::state, WaitEventFlag(), WEF_AND, and WEF_CLEAR.
Referenced by rmmanEnd(), and RmmanRpc_close().
rmmanEnd()
int rmmanEnd (void)
Definition at line 180 of file rmman.c.
 {
         u32 bits;
         int port, slot, result;
         if(IsInitialized != 0)
         {
                 for(port = 0; port < 2; port++)
                 {
                         for(slot = 0; slot < 4; slot++)
                         {       //If port,slot is opened, close it.
                                 if((portStatus[port] >> slot) & 1)
                                         rmmanClose(port, slot);
                         }
                 }
                 SetEventFlag(eventFlagID, RM_EF_EXIT_THREAD);
                 WaitEventFlag(eventFlagID, RM_EF_EXIT_THREAD_DONE, WEF_AND|WEF_CLEAR, &bits);
                 DeleteEventFlag(eventFlagID);
                 eventFlagID = 0;
                 if(DeleteThread(eventFlagID) == 0)
                 {
                         MainThreadID = 0;
                         IsInitialized = 0;
                         result = 1;
                 } else
                         result = 0;
         } else
                 result = 1;
         return result;
 }
References DeleteEventFlag(), DeleteThread(), eventFlagID, IsInitialized, MainThreadID, RmData::port, portStatus, result, RM_EF_EXIT_THREAD, RM_EF_EXIT_THREAD_DONE, rmmanClose(), SetEventFlag(), RmData::slot, WaitEventFlag(), WEF_AND, and WEF_CLEAR.
Referenced by RmmanRpc_end().
rmmanInit()
int rmmanInit (void)
Definition at line 86 of file rmman.c.
 {
         iop_event_t EventFlagData;
         iop_thread_t ThreadData;
         int result;
         portStatus[0] = 0;
         portStatus[1] = 0;
         IsInitialized = 1;
         EventFlagData.attr = 2;
         EventFlagData.bits = 0;
         if((eventFlagID = CreateEventFlag(&EventFlagData)) != 0)
         {
                 ThreadData.attr = TH_C;
                 ThreadData.thread = &MainThread;
                 ThreadData.priority = 0x2E;
                 ThreadData.stacksize = 0x800;
                 if((MainThreadID = CreateThread(&ThreadData)) != 0)
                 {
                         StartThread(MainThreadID, NULL);
                         result=MainThreadID;
                 }
                 else result=0;
         }
         else result=0;
         return result;
 }
References iop_thread_t::attr, iop_event_t::attr, iop_event_t::bits, CreateEventFlag(), CreateThread(), EventFlagData, eventFlagID, IsInitialized, MainThread(), MainThreadID, NULL, portStatus, iop_thread_t::priority, result, iop_thread_t::stacksize, StartThread(), TH_C, and iop_thread_t::thread.
Referenced by RmmanRpc_init().
rmmanOpen()
int rmmanOpen (int port, int slot, void * buffer)
Definition at line 115 of file rmman.c.
 {
         iop_event_t evf;
         int result;
         struct RmData *pRmData;
         if(!((portStatus[port] >> slot) & 1))
         {
                 pRmData = &RmData[port][slot];
                 pRmData->port = port;
                 pRmData->slot = slot;
                 pRmData->state = RM_STATE_EXECCMD;
                 pRmData->reqState = RM_RSTATE_COMPLETE;
                 pRmData->eeBuffer = buffer;
                 pRmData->currentTask = RM_TASK_QUERY;
                 pRmData->counter = 0;
                 evf.attr = EA_MULTI;
                 evf.bits = 0;
                 if((pRmData->eventFlagID = CreateEventFlag(&evf)) != 0)
                 {
                         pRmData->powerMode = 0;
                         portStatus[port] |= (1 << slot);
                         result = 1;
                 } else
                         result = 0;
         } else
                 result = 0;
         return result;
 }
References iop_event_t::attr, iop_event_t::bits, buffer, RmData::counter, CreateEventFlag(), RmData::currentTask, EA_MULTI, RmData::eeBuffer, RmData::eventFlagID, RmData::port, portStatus, RmData::powerMode, RmData::reqState, result, RM_RSTATE_COMPLETE, RM_STATE_EXECCMD, RM_TASK_QUERY, RmData::slot, and RmData::state.
Referenced by RmmanRpc_open().
RmmanRpc_close()
static void* RmmanRpc_close (struct rmRpcPacket * packet) static
Definition at line 489 of file rmman.c.
 {
         packet->cmd.result = rmmanClose(packet->cmd.port, packet->cmd.slot);
         return packet;
 }
References rmRpcPacket::cmd, and rmmanClose().
Referenced by RpcHandler().
RmmanRpc_end()
static void* RmmanRpc_end (struct rmRpcPacket * packet) static
Definition at line 483 of file rmman.c.
 {
         packet->cmd.result = rmmanEnd();
         return packet;
 }
References rmRpcPacket::cmd, and rmmanEnd().
Referenced by RpcHandler().
RmmanRpc_init()
static void* RmmanRpc_init (struct rmRpcPacket * packet) static
Definition at line 465 of file rmman.c.
 {
         packet->cmd.result = rmmanInit();
         return packet;
 }
References rmRpcPacket::cmd, and rmmanInit().
Referenced by RpcHandler().
RmmanRpc_open()
static void* RmmanRpc_open (struct rmRpcPacket * packet) static
Definition at line 477 of file rmman.c.
 {
         packet->cmd.result = rmmanOpen(packet->cmd.port, packet->cmd.slot, packet->cmd.data);
         return packet;
 }
References rmRpcPacket::cmd, and rmmanOpen().
Referenced by RpcHandler().
RmmanRpc_version()
static void* RmmanRpc_version (struct rmRpcPacket * packet) static
Definition at line 471 of file rmman.c.
 {
         packet->cmd.result = rmmanVersion();
         return packet;
 }
References rmRpcPacket::cmd, and rmmanVersion().
Referenced by RpcHandler().
rmmanVersion()
static int rmmanVersion (void) static
Definition at line 460 of file rmman.c.
 {
         return _irx_id.v;
 }
References _irx_id, and irx_id::v.
Referenced by RmmanRpc_version().
RpcHandler()
static void* RpcHandler (int fno, void * buffer, int len) static
Definition at line 495 of file rmman.c.
 {
         void *retBuff;
         switch(((struct rmRpcPacket *)buffer)->cmd.command)
         {
                 case RMMAN_RPCFUNC_END:
                         retBuff = RmmanRpc_end((struct rmRpcPacket *)buffer);
                         break;
                 case RMMAN_RPCFUNC_INIT:
                         retBuff = RmmanRpc_init((struct rmRpcPacket *)buffer);
                         break;
                 case RMMAN_RPCFUNC_CLOSE:
                         retBuff = RmmanRpc_close((struct rmRpcPacket *)buffer);
                         break;
                 case RMMAN_RPCFUNC_OPEN:
                         retBuff = RmmanRpc_open((struct rmRpcPacket *)buffer);
                         break;
                 case RMMAN_RPCFUNC_VERSION:
                         retBuff = RmmanRpc_version((struct rmRpcPacket *)buffer);
                         break;
                 default:
                         printf("invalid function code (%03x)\n", (unsigned int)((struct rmRpcPacket *)buffer)->cmd.command);
                         retBuff = buffer;
         }
         return retBuff;
 }
References buffer, printf(), RMMAN_RPCFUNC_CLOSE, RMMAN_RPCFUNC_END, RMMAN_RPCFUNC_INIT, RMMAN_RPCFUNC_OPEN, RMMAN_RPCFUNC_VERSION, RmmanRpc_close(), RmmanRpc_end(), RmmanRpc_init(), RmmanRpc_open(), and RmmanRpc_version().
Referenced by RpcThread().
RpcThread()
static void RpcThread (void * arg) static
Definition at line 524 of file rmman.c.
 {
         if(!sceSifCheckInit())
         {
                 printf("yet sif hasn't been init\n");
                 sceSifInit();
         }
         sceSifInitRpc(0);
         sceSifSetRpcQueue(&RpcDataQueue, GetThreadId());
         sceSifRegisterRpc(&RpcServerData, RMMAN_RPC_ID, &RpcHandler, &RpcDataBuffer, NULL, NULL, &RpcDataQueue);
         sceSifRpcLoop(&RpcDataQueue);
 }
References GetThreadId(), NULL, printf(), RMMAN_RPC_ID, RpcDataBuffer, RpcDataQueue, RpcHandler(), RpcServerData, sceSifCheckInit(), sceSifInit(), sceSifInitRpc(), sceSifRegisterRpc(), sceSifRpcLoop(), and sceSifSetRpcQueue().
Variable Documentation
_exp_rmman
struct irx_export_table _exp_rmman extern
Referenced by _start().
eventFlagID
int eventFlagID static
Definition at line 52 of file rmman.c.
Referenced by MainThread(), rmmanEnd(), and rmmanInit().
IsInitialized
int IsInitialized static
Definition at line 54 of file rmman.c.
Referenced by rmmanEnd(), and rmmanInit().
MainThreadID
int MainThreadID static
Definition at line 53 of file rmman.c.
Referenced by rmmanEnd(), and rmmanInit().
portStatus
int portStatus[2] static
Definition at line 51 of file rmman.c.
Referenced by MainThread(), rmmanClose(), rmmanEnd(), rmmanInit(), and rmmanOpen().
RmData
struct RmData RmData[2][4] static
Definition at line 14 of file rmman.c.
RpcDataBuffer
struct rmRpcPacket RpcDataBuffer static
Definition at line 57 of file rmman.c.
Referenced by RpcThread().
RpcDataQueue
SifRpcDataQueue_t RpcDataQueue static
Definition at line 56 of file rmman.c.
Referenced by RpcThread().
RpcServerData
SifRpcServerData_t RpcServerData static
Definition at line 57 of file rmman.c.
Referenced by RpcThread().
RpcThreadID
int RpcThreadID static
Definition at line 55 of file rmman.c.