ps2sdk: iop/system/mtapman/src/rpcservers.c File Reference
rpcservers.c File Reference
#include "types.h"
#include "irx.h"
#include "stdio.h"
#include "freemtap.h"
#include "sifman.h"
#include "sifcmd.h"
#include "thbase.h"
Macros
#define MTAPSERV_PORT_OPEN 0x80000901
#define MTAPSERV_PORT_CLOSE 0x80000902
#define MTAPSERV_GET_CONNECTION 0x80000903
#define MTAPSERV_GET_SLOT_NUMBER 0x800009FE
#define MTAPSERV_CHANGE_SLOT 0x800009FF
Functions
void * rpc_server_change_slot (s32 fno, u32 *data, s32 size)
void rpc_thread_change_slot ()
void * rpc_server_get_slot_number (s32 fno, u32 *data, s32 size)
void rpc_thread_get_slot_number ()
void * RpcServerGetConnection (s32 fno, u32 *data, s32 size)
void RpcThreadGetConnection ()
void * RpcServerPortClose (s32 fno, u32 *data, s32 size)
void RpcThreadPortClose ()
void * RpcServerPortOpen (s32 fno, u32 *data, s32 size)
void RpcThreadPortOpen ()
s32 InitRpcServers ()
Variables
static u32 sb [4]
static s32 threadid_rpc1
static SifRpcDataQueue_t qd1
static SifRpcServerData_t sd1
static s32 threadid_rpc2
static SifRpcDataQueue_t qd2
static SifRpcServerData_t sd2
static s32 threadid_rpc3
static SifRpcDataQueue_t qd3
static SifRpcServerData_t sd3
static s32 threadid_rpc4
static SifRpcDataQueue_t qd4
static SifRpcServerData_t sd4
static s32 threadid_rpc5
static SifRpcDataQueue_t qd5
static SifRpcServerData_t sd5
Detailed Description
IOP multitap driver
Definition in file rpcservers.c.
Macro Definition Documentation
MTAPSERV_CHANGE_SLOT
#define MTAPSERV_CHANGE_SLOT 0x800009FF
Definition at line 24 of file rpcservers.c.
MTAPSERV_GET_CONNECTION
#define MTAPSERV_GET_CONNECTION 0x80000903
Definition at line 22 of file rpcservers.c.
MTAPSERV_GET_SLOT_NUMBER
#define MTAPSERV_GET_SLOT_NUMBER 0x800009FE
Definition at line 23 of file rpcservers.c.
MTAPSERV_PORT_CLOSE
#define MTAPSERV_PORT_CLOSE 0x80000902
Definition at line 21 of file rpcservers.c.
MTAPSERV_PORT_OPEN
#define MTAPSERV_PORT_OPEN 0x80000901
Definition at line 20 of file rpcservers.c.
Function Documentation
InitRpcServers()
s32 InitRpcServers ()
Definition at line 166 of file rpcservers.c.
 {
         iop_thread_t rpc_thread;
         // mtapPortOpen RPC Server
         rpc_thread.attr = TH_C;
         rpc_thread.thread = RpcThreadPortOpen;
         rpc_thread.stacksize = 0x2000;
         rpc_thread.priority = 32;
         threadid_rpc1 = CreateThread(&rpc_thread);
         if(threadid_rpc1 == 0) return 0;
         StartThread(threadid_rpc1, 0);
         // mtapPortClose RPC Server
         rpc_thread.thread = RpcThreadPortClose;
         threadid_rpc2 = CreateThread(&rpc_thread);
         if(threadid_rpc2 == 0) return 0;
         StartThread(threadid_rpc2, 0);
         // mtapGetConnection RPC Server
         rpc_thread.thread = RpcThreadGetConnection;
         threadid_rpc3 = CreateThread(&rpc_thread);
         if(threadid_rpc3 == 0) return 0;
         StartThread(threadid_rpc3, 0);
         // mtapGetSlotNumber RPC Server
         rpc_thread.thread = rpc_thread_get_slot_number;
         threadid_rpc4 = CreateThread(&rpc_thread);
         if(threadid_rpc4 == 0) return 0;
         StartThread(threadid_rpc4, 0);
         // mtapChangeSlot RPC Server
         rpc_thread.thread = rpc_thread_change_slot;
         threadid_rpc5 = CreateThread(&rpc_thread);
         if(threadid_rpc5 == 0) return 0;
         StartThread(threadid_rpc5, 0);
         return 1;
 }
References CreateThread(), rpc_thread(), rpc_thread_change_slot(), rpc_thread_get_slot_number(), RpcThreadGetConnection(), RpcThreadPortClose(), RpcThreadPortOpen(), StartThread(), TH_C, threadid_rpc1, threadid_rpc2, threadid_rpc3, threadid_rpc4, and threadid_rpc5.
Referenced by _start().
rpc_server_change_slot()
void* rpc_server_change_slot (s32 fno, u32 * data, s32 size)
Definition at line 50 of file rpcservers.c.
 {
         data[1] = mtapChangeSlot( data[0], data[1] );
         return data;
 }
References mtapChangeSlot().
Referenced by rpc_thread_change_slot().
rpc_server_get_slot_number()
void* rpc_server_get_slot_number (s32 fno, u32 * data, s32 size)
Definition at line 73 of file rpcservers.c.
 {
         data[1] = mtapGetSlotNumber( data[0] );
         return data;
 }
References mtapGetSlotNumber().
Referenced by rpc_thread_get_slot_number().
rpc_thread_change_slot()
void rpc_thread_change_slot ()
Definition at line 58 of file rpcservers.c.
 {
         if( sceSifCheckInit() == 0)
         {
                 M_PRINTF("Sif not initialized.\n");
                 sceSifInit();
         }
         sceSifInitRpc(0);
         sceSifSetRpcQueue(&qd5, GetThreadId());
         sceSifRegisterRpc(&sd5, MTAPSERV_CHANGE_SLOT, (void*)rpc_server_change_slot, sb, 0, 0, &qd5);
         sceSifRpcLoop(&qd5);
 }
References GetThreadId(), M_PRINTF, MTAPSERV_CHANGE_SLOT, qd5, rpc_server_change_slot(), sb, sceSifCheckInit(), sceSifInit(), sceSifInitRpc(), sceSifRegisterRpc(), sceSifRpcLoop(), sceSifSetRpcQueue(), and sd5.
Referenced by InitRpcServers().
rpc_thread_get_slot_number()
void rpc_thread_get_slot_number ()
Definition at line 81 of file rpcservers.c.
 {
         if( sceSifCheckInit() == 0)
         {
                 M_PRINTF("Sif not initialized.\n");
                 sceSifInit();
         }
         sceSifInitRpc(0);
         sceSifSetRpcQueue(&qd4, GetThreadId());
         sceSifRegisterRpc(&sd4, MTAPSERV_GET_SLOT_NUMBER, (void*)rpc_server_get_slot_number, sb, 0, 0, &qd4);
         sceSifRpcLoop(&qd4);
 }
References GetThreadId(), M_PRINTF, MTAPSERV_GET_SLOT_NUMBER, qd4, rpc_server_get_slot_number(), sb, sceSifCheckInit(), sceSifInit(), sceSifInitRpc(), sceSifRegisterRpc(), sceSifRpcLoop(), sceSifSetRpcQueue(), and sd4.
Referenced by InitRpcServers().
RpcServerGetConnection()
void* RpcServerGetConnection (s32 fno, u32 * data, s32 size)
Definition at line 95 of file rpcservers.c.
 {
         data[1] = mtapGetConnection( data[0] );
         return data;
 }
References mtapGetConnection().
Referenced by RpcThreadGetConnection().
RpcServerPortClose()
void* RpcServerPortClose (s32 fno, u32 * data, s32 size)
Definition at line 116 of file rpcservers.c.
 {
         data[1] = mtapPortClose( data[0] );
         return data;
 }
References mtapPortClose().
Referenced by RpcThreadPortClose().
RpcServerPortOpen()
void* RpcServerPortOpen (s32 fno, u32 * data, s32 size)
Definition at line 137 of file rpcservers.c.
 {
         data[1] = mtapPortOpen( data[0] );
         return data;
 }
References mtapPortOpen().
Referenced by RpcThreadPortOpen().
RpcThreadGetConnection()
void RpcThreadGetConnection ()
Definition at line 102 of file rpcservers.c.
 {
         if( sceSifCheckInit() == 0)
         {
                 M_PRINTF("Sif not initialized.\n");
                 sceSifInit();
         }
         sceSifInitRpc(0);
         sceSifSetRpcQueue(&qd3, GetThreadId());
         sceSifRegisterRpc(&sd3, MTAPSERV_GET_CONNECTION, (void*)RpcServerGetConnection, sb, 0, 0, &qd3);
         sceSifRpcLoop(&qd3);
 }
References GetThreadId(), M_PRINTF, MTAPSERV_GET_CONNECTION, qd3, RpcServerGetConnection(), sb, sceSifCheckInit(), sceSifInit(), sceSifInitRpc(), sceSifRegisterRpc(), sceSifRpcLoop(), sceSifSetRpcQueue(), and sd3.
Referenced by InitRpcServers().
RpcThreadPortClose()
void RpcThreadPortClose ()
Definition at line 123 of file rpcservers.c.
 {
         if( sceSifCheckInit() == 0)
         {
                 M_PRINTF("Sif not initialized.\n");
                 sceSifInit();
         }
         sceSifInitRpc(0);
         sceSifSetRpcQueue(&qd2, GetThreadId());
         sceSifRegisterRpc(&sd2, MTAPSERV_PORT_CLOSE, (void*)RpcServerPortClose, sb, 0, 0, &qd2);
         sceSifRpcLoop(&qd2);
 }
References GetThreadId(), M_PRINTF, MTAPSERV_PORT_CLOSE, qd2, RpcServerPortClose(), sb, sceSifCheckInit(), sceSifInit(), sceSifInitRpc(), sceSifRegisterRpc(), sceSifRpcLoop(), sceSifSetRpcQueue(), and sd2.
Referenced by InitRpcServers().
RpcThreadPortOpen()
void RpcThreadPortOpen ()
Definition at line 145 of file rpcservers.c.
 {
         if( sceSifCheckInit() == 0)
         {
                 M_PRINTF("Sif not initialized.\n");
                 sceSifInit();
         }
         sceSifInitRpc(0);
         sceSifSetRpcQueue(&qd1, GetThreadId());
         sceSifRegisterRpc(&sd1, MTAPSERV_PORT_OPEN, (void*)RpcServerPortOpen, sb, 0, 0, &qd1);
         sceSifRpcLoop(&qd1);
 }
References GetThreadId(), M_PRINTF, MTAPSERV_PORT_OPEN, qd1, RpcServerPortOpen(), sb, sceSifCheckInit(), sceSifInit(), sceSifInitRpc(), sceSifRegisterRpc(), sceSifRpcLoop(), sceSifSetRpcQueue(), and sd1.
Referenced by InitRpcServers().
Variable Documentation
qd1
SifRpcDataQueue_t qd1 static
Definition at line 30 of file rpcservers.c.
Referenced by RpcThreadPortOpen().
qd2
SifRpcDataQueue_t qd2 static
Definition at line 34 of file rpcservers.c.
Referenced by RpcThreadPortClose().
qd3
SifRpcDataQueue_t qd3 static
Definition at line 38 of file rpcservers.c.
Referenced by RpcThreadGetConnection().
qd4
SifRpcDataQueue_t qd4 static
Definition at line 42 of file rpcservers.c.
Referenced by rpc_thread_get_slot_number().
qd5
SifRpcDataQueue_t qd5 static
Definition at line 46 of file rpcservers.c.
Referenced by rpc_thread_change_slot().
sb
u32 sb[4] static
Definition at line 27 of file rpcservers.c.
Referenced by pfsFormat(), rpc_thread_change_slot(), rpc_thread_get_slot_number(), RpcThreadGetConnection(), RpcThreadPortClose(), and RpcThreadPortOpen().
sd1
SifRpcServerData_t sd1 static
Definition at line 31 of file rpcservers.c.
Referenced by RpcThreadPortOpen().
sd2
SifRpcServerData_t sd2 static
Definition at line 35 of file rpcservers.c.
Referenced by RpcThreadPortClose().
sd3
SifRpcServerData_t sd3 static
Definition at line 39 of file rpcservers.c.
Referenced by RpcThreadGetConnection().
sd4
SifRpcServerData_t sd4 static
Definition at line 43 of file rpcservers.c.
Referenced by rpc_thread_get_slot_number().
sd5
SifRpcServerData_t sd5 static
Definition at line 47 of file rpcservers.c.
Referenced by rpc_thread_change_slot().
threadid_rpc1
s32 threadid_rpc1 static
Definition at line 29 of file rpcservers.c.
Referenced by InitRpcServers().
threadid_rpc2
s32 threadid_rpc2 static
Definition at line 33 of file rpcservers.c.
Referenced by InitRpcServers().
threadid_rpc3
s32 threadid_rpc3 static
Definition at line 37 of file rpcservers.c.
Referenced by InitRpcServers().
threadid_rpc4
s32 threadid_rpc4 static
Definition at line 41 of file rpcservers.c.
Referenced by InitRpcServers().
threadid_rpc5
s32 threadid_rpc5 static
Definition at line 45 of file rpcservers.c.
Referenced by InitRpcServers().