ps2sdk: iop/system/sbusintr/include/sbusintr.h File Reference
sbusintr.h File Reference
#include <types.h>
#include <irx.h>
Macros
#define sbusintr_IMPORTS_start DECLARE_IMPORT_TABLE(sbusintr, 1, 1)
#define sbusintr_IMPORTS_end END_IMPORT_TABLE
#define I_sbus_intr_init DECLARE_IMPORT(4, sbus_intr_init)
#define I_sbus_intr_exit DECLARE_IMPORT(2, sbus_intr_exit)
#define I_sbus_intr_handler_add DECLARE_IMPORT(5, sbus_intr_handler_add)
#define I_sbus_intr_handler_del DECLARE_IMPORT(6, sbus_intr_handler_del)
#define I_sbus_intr_main_interrupt DECLARE_IMPORT(7, sbus_intr_main_interrupt)
Typedefs
typedef int(* sbus_intr_handler_t) (u32, void *)
Enumerations
enum sbus_errors {
SBUS_E_OK ,
SBUS_E_INIT = 0xd600 ,
SBUS_E_ARG ,
SBUS_E_IRQ
}
Functions
int sbus_intr_init ()
void sbus_intr_exit ()
int sbus_intr_handler_add (u32 irq, sbus_intr_handler_t handler, void *arg)
int sbus_intr_handler_del (u32 irq)
void sbus_intr_main_interrupt (u32 irq)
Detailed Description
SBUS interrupts.
Definition in file sbusintr.h.
Macro Definition Documentation
I_sbus_intr_exit
#define I_sbus_intr_exit DECLARE_IMPORT(2, sbus_intr_exit)
Definition at line 48 of file sbusintr.h.
I_sbus_intr_handler_add
#define I_sbus_intr_handler_add DECLARE_IMPORT(5, sbus_intr_handler_add)
Definition at line 49 of file sbusintr.h.
I_sbus_intr_handler_del
#define I_sbus_intr_handler_del DECLARE_IMPORT(6, sbus_intr_handler_del)
Definition at line 50 of file sbusintr.h.
I_sbus_intr_init
#define I_sbus_intr_init DECLARE_IMPORT(4, sbus_intr_init)
Definition at line 47 of file sbusintr.h.
I_sbus_intr_main_interrupt
#define I_sbus_intr_main_interrupt DECLARE_IMPORT(7, sbus_intr_main_interrupt)
Definition at line 51 of file sbusintr.h.
sbusintr_IMPORTS_end
#define sbusintr_IMPORTS_end END_IMPORT_TABLE
Definition at line 45 of file sbusintr.h.
sbusintr_IMPORTS_start
#define sbusintr_IMPORTS_start DECLARE_IMPORT_TABLE(sbusintr, 1, 1)
Definition at line 44 of file sbusintr.h.
Typedef Documentation
sbus_intr_handler_t
typedef int(* sbus_intr_handler_t) (u32, void *)
Definition at line 34 of file sbusintr.h.
Enumeration Type Documentation
sbus_errors
enum sbus_errors
Enumerator
SBUS_E_OK
SBUS_E_INIT
Initialization error
SBUS_E_ARG
Error with an argument
SBUS_E_IRQ
Wrong IRQ number / already in use
Definition at line 23 of file sbusintr.h.
                  {
         SBUS_E_OK,
         SBUS_E_INIT = 0xd600,
         SBUS_E_ARG,
         SBUS_E_IRQ,
 };
Function Documentation
sbus_intr_exit()
void sbus_intr_exit ()
Definition at line 141 of file sbusintr.c.
 {
         DisableIntr(IOP_IRQ_SBUS, NULL);
         ReleaseIntrHandler(IOP_IRQ_SBUS);
         initialized = 0;
 }
References DisableIntr(), initialized, IOP_IRQ_SBUS, NULL, and ReleaseIntrHandler().
sbus_intr_handler_add()
int sbus_intr_handler_add (u32 irq, sbus_intr_handler_t handler, void * arg)
Definition at line 64 of file sbusintr.c.
 {
         int res = irq, state = 0;
         /* I hope this correct... */
         CpuSuspendIntr(&state);
         if (irq > 31) {
                 res = -SBUS_E_ARG;
                 goto out;
         }
         if (sbus_handler_table[irq].handler) {
                 res = -SBUS_E_IRQ;
                 goto out;
         }
         sbus_handler_table[irq].handler = handler;
         sbus_handler_table[irq].arg     = arg;
 out:
         CpuResumeIntr(state);
         return res;
 }
References arg, CpuResumeIntr(), CpuSuspendIntr(), handler, SBUS_E_ARG, SBUS_E_IRQ, sbus_handler_table, and state.
Referenced by _start().
sbus_intr_handler_del()
int sbus_intr_handler_del (u32 irq)
Definition at line 88 of file sbusintr.c.
 {
         if (irq > 31)
                 return -SBUS_E_ARG;
         sbus_handler_table[irq].handler = NULL;
         sbus_handler_table[irq].arg     = NULL;
         return irq;
 }
References NULL, SBUS_E_ARG, and sbus_handler_table.
sbus_intr_init()
int sbus_intr_init ()
Definition at line 116 of file sbusintr.c.
 {
         int i, state, res = 0;
         if (initialized)
                 return res;
         CpuSuspendIntr(&state);
         for (i = 0; i < 32; ++i) {
                 sbus_handler_table[i].handler = NULL;
                 sbus_handler_table[i].arg     = NULL;
         }
         if (RegisterIntrHandler(IOP_IRQ_SBUS, 1, sbus_dispatch, NULL) < 0) {
                 res = -SBUS_E_INIT;
                 goto out;
         }
         EnableIntr(IOP_IRQ_SBUS);
         initialized = 1;
 out:
         CpuResumeIntr(state);
         return res;
 }
References CpuResumeIntr(), CpuSuspendIntr(), EnableIntr(), initialized, IOP_IRQ_SBUS, NULL, RegisterIntrHandler(), sbus_dispatch(), SBUS_E_INIT, sbus_handler_table, and state.
Referenced by _start().
sbus_intr_main_interrupt()
void sbus_intr_main_interrupt (u32 irq)
Definition at line 99 of file sbusintr.c.
 {
         u32 flag = 1 << irq;
         if (irq > 31 || (sceSifGetSMFlag() & flag))
                 return;
         sceSifSetSMFlag(flag);
         sceSifIntrMain();
 }
References sceSifGetSMFlag(), sceSifIntrMain(), and sceSifSetSMFlag().