ps2sdk: iop/debug/iop_sbusdbg/src/sbus_dbg.c File Reference
sbus_dbg.c File Reference
#include <tamtypes.h>
#include <stdio.h>
#include <stdarg.h>
#include <sysclib.h>
#include <sysmem.h>
#include <excepman.h>
#include <intrman.h>
#include <loadcore.h>
#include <thbase.h>
#include <ioman.h>
#include <ps2_debug.h>
#include <ps2_sbus.h>
#include "iopdebug.h"
Data Structures
struct SBUS_ControlCPU_Params
Macros
#define SIF2_CMD_DBG_PUTS (1)
#define SIF2_CMD_DBG_EXC (2)
#define SIF2_CMD_DBG_CTRL (3)
Functions
void sbus_tty_puts (const char *str)
void signal_iop_exception (IOP_RegFrame *frame)
void _sif2_cmd_dbg_control (SIF2_CmdPkt *cmd, void *param)
void SBUS_dbg_init (void)
Variables
int _iop_exception_state
static IOP_RegFrame * _iop_ex_def_frame
static IOP_RegFrame * _iop_ex_dbg_frame
int _iop_controlled
int tid
Macro Definition Documentation
SIF2_CMD_DBG_CTRL
#define SIF2_CMD_DBG_CTRL (3)
Definition at line 18 of file sbus_dbg.c.
SIF2_CMD_DBG_EXC
#define SIF2_CMD_DBG_EXC (2)
Definition at line 17 of file sbus_dbg.c.
SIF2_CMD_DBG_PUTS
#define SIF2_CMD_DBG_PUTS (1)
Definition at line 16 of file sbus_dbg.c.
Function Documentation
_sif2_cmd_dbg_control()
void _sif2_cmd_dbg_control (SIF2_CmdPkt * cmd, void * param)
Definition at line 46 of file sbus_dbg.c.
 {
     SBUS_ControlCPU_Params *params;
     IOP_RegFrame *frame;
     params = (SBUS_ControlCPU_Params *) ((((u32) cmd) + sizeof(SIF2_CmdPkt)) | 0x00000000);
     if(params->mode == 1)
     {
         // wake up the controller thread.
         iWakeupThread(tid);
     }
     else
     {
         if(_iop_exception_state == 0) { return; }
         if(_iop_exception_state == 1) { frame = _iop_ex_def_frame; }
         else { frame = _iop_ex_dbg_frame; }
         // update the register frame and release the CPU.
         memcpy(frame, &params->reg_frame, sizeof(IOP_RegFrame));
         FlushIcache();
         FlushDcache();
         _iop_exception_state = 0;
         _iop_controlled = 0;
     }
 }
References _iop_controlled, _iop_ex_dbg_frame, _iop_ex_def_frame, _iop_exception_state, FlushDcache(), FlushIcache(), iWakeupThread(), memcpy(), SBUS_ControlCPU_Params::mode, SBUS_ControlCPU_Params::reg_frame, and tid.
Referenced by SBUS_dbg_init().
SBUS_dbg_init()
void SBUS_dbg_init (void)
Definition at line 76 of file sbus_dbg.c.
 {
     iop_dbg_get_reg_frames(&_iop_ex_def_frame, &_iop_ex_dbg_frame);
     SIF2_set_cmd_handler(SIF2_CMD_DBG_CTRL, &_sif2_cmd_dbg_control, NULL);
 }
References _iop_ex_dbg_frame, _iop_ex_def_frame, _sif2_cmd_dbg_control(), iop_dbg_get_reg_frames(), NULL, and SIF2_CMD_DBG_CTRL.
Referenced by _start().
sbus_tty_puts()
void sbus_tty_puts (const char * str)
Definition at line 34 of file sbus_dbg.c.
 {
     SIF2_send_cmd(SIF2_CMD_DBG_PUTS, (void *) str, strlen(str) + 1);
 }
References SIF2_CMD_DBG_PUTS, and strlen().
Referenced by _kPrintf(), and ttyfs_write().
signal_iop_exception()
void signal_iop_exception (IOP_RegFrame * frame)
Definition at line 39 of file sbus_dbg.c.
 {
     SIF2_send_cmd(SIF2_CMD_DBG_EXC, (void *) frame, sizeof(IOP_RegFrame));
 }
References SIF2_CMD_DBG_EXC.
Referenced by _iop_ex_handler().
Variable Documentation
_iop_controlled
int _iop_controlled extern
Definition at line 13 of file main.c.
Referenced by _iop_ex_handler(), and _sif2_cmd_dbg_control().
_iop_ex_dbg_frame
IOP_RegFrame* _iop_ex_dbg_frame static
Definition at line 23 of file sbus_dbg.c.
Referenced by _sif2_cmd_dbg_control(), and SBUS_dbg_init().
_iop_ex_def_frame
IOP_RegFrame* _iop_ex_def_frame static
Definition at line 22 of file sbus_dbg.c.
Referenced by _sif2_cmd_dbg_control(), and SBUS_dbg_init().
_iop_exception_state
int _iop_exception_state extern
Definition at line 14 of file main.c.
Referenced by _iop_ex_handler(), and _sif2_cmd_dbg_control().
tid
int tid extern
Definition at line 46 of file main.c.
Referenced by _sif2_cmd_dbg_control(), create_th(), create_thread(), rpcMainThread(), and sys_thread_new().