ps2sdk: iop/debug/iop_sbusdbg/src/sbus_tty.c File Reference
sbus_tty.c File Reference
#include <tamtypes.h>
#include <stdio.h>
#include <stdarg.h>
#include <sysclib.h>
#include <sysmem.h>
#include <excepman.h>
#include <intrman.h>
#include <ioman.h>
#include <fileXio.h>
#include <ps2_debug.h>
#include <ps2_sbus.h>
#include "iopdebug.h"
Functions
void sbus_tty_puts (const char *str)
static int ttyfs_error ()
static int ttyfs_init ()
static int ttyfs_deinit ()
static int ttyfs_open (iop_file_t *file, const char *name, int flags, int mode)
static int ttyfs_close (iop_file_t *file, int fd)
static int ttyfs_read (iop_file_t *file, void *ptr, size_t size)
static int ttyfs_write (iop_file_t *file, u8 *ptr, size_t size)
static int ttyfs_lseek (iop_file_t *file, int offset, int mode)
static int ttyfs_format (iop_file_t *file, const char *dev, const char *blockdev, void *arg, size_t arglen)
static int ttyfs_remove (iop_file_t *file, const char *name)
static int ttyfs_dread (iop_file_t *file, iox_dirent_t *dirent)
static int ttyfs_getstat (iop_file_t *file, const char *name, iox_stat_t *stat)
static int ttyfs_devctl (iop_file_t *file, const char *name, int cmd, void *arg, size_t arglen, void *buf, size_t buflen)
static int ttyfs_ioctl2 (iop_file_t *file, int cmd, void *arg, size_t arglen, void *buf, size_t buflen)
void sprintf_putchar (void *context, int c)
int _vsprintf (char *str, const char *format, va_list ap)
int _kPrintf (void *context, const char *format, va_list ap)
int sbus_tty_init (void)
Variables
static void * fsd_ops []
iop_device_t tty_fsd
static char kprint_buffer [1024]
Function Documentation
_kPrintf()
int _kPrintf (void * context, const char * format, va_list ap)
Definition at line 154 of file sbus_tty.c.
 {
     int r = prnt(&sprintf_putchar, &format, format, ap);
     sbus_tty_puts(kprint_buffer);
     return r;
 }
References format(), kprint_buffer, prnt(), sbus_tty_puts(), and sprintf_putchar().
Referenced by sbus_tty_init().
_vsprintf()
int _vsprintf (char * str, const char * format, va_list ap)
sbus_tty_init()
int sbus_tty_init (void)
Definition at line 161 of file sbus_tty.c.
 {
     close(0);
     close(1);
         DelDrv("tty");
         DelDrv("dummytty");
         if(AddDrv(&tty_fsd) != 0) { return(-1); }
     open("tty:", O_RDONLY);
     open("tty:", O_WRONLY);
     KprintfSet(&_kPrintf, NULL);
     return(0);
 }
References _kPrintf(), AddDrv(), close(), DelDrv(), KprintfSet(), NULL, O_RDONLY, O_WRONLY, open(), and tty_fsd.
Referenced by _start().
sbus_tty_puts()
void sbus_tty_puts (const char * str)
Definition at line 34 of file sbus_dbg.c.
 {
     SIF2_send_cmd(SIF2_CMD_DBG_PUTS, (void *) str, strlen(str) + 1);
 }
References SIF2_CMD_DBG_PUTS, and strlen().
Referenced by _kPrintf(), and ttyfs_write().
sprintf_putchar()
void sprintf_putchar (void * context, int c)
Definition at line 142 of file sbus_tty.c.
 {
     char **string = (char **)context;
     if(c < 0x100) { ((*string)++)[0] = c; }
     else { (*string)[0] = 0; }
 }
References context.
Referenced by _kPrintf().
ttyfs_close()
static int ttyfs_close (iop_file_t * file, int fd) static
Definition at line 50 of file sbus_tty.c.
 {
     //DBG_puts("SIOTTY: FS Close()\n");
     return(0);
 }
ttyfs_deinit()
static int ttyfs_deinit () static
Definition at line 38 of file sbus_tty.c.
 {
     //DBG_puts("SIOTTY: FS Deinit()\n");
         return 0;
 }
ttyfs_devctl()
static int ttyfs_devctl (iop_file_t * file, const char * name, int cmd, void * arg, size_t arglen, void * buf, size_t buflen) static
Definition at line 113 of file sbus_tty.c.
{
     //DBG_puts("SIOTTY: FS DEVCTL()\n");
     return(-1);
 }
ttyfs_dread()
static int ttyfs_dread (iop_file_t * file, iox_dirent_t * dirent) static
Definition at line 101 of file sbus_tty.c.
{
     //DBG_puts("SIOTTY: FS Dread()\n");
     return(-1);
 }
ttyfs_error()
static int ttyfs_error () static
Definition at line 30 of file sbus_tty.c.
 { return -1; }
ttyfs_format()
static int ttyfs_format (iop_file_t * file, const char * dev, const char * blockdev, void * arg, size_t arglen) static
Definition at line 89 of file sbus_tty.c.
{
     //DBG_puts("SIOTTY: FS Format()\n");
     return(-1);
 }
ttyfs_getstat()
static int ttyfs_getstat (iop_file_t * file, const char * name, iox_stat_t * stat) static
Definition at line 107 of file sbus_tty.c.
{
     //DBG_puts("SIOTTY: FS GetStat()\n");
     return(-1);
 }
ttyfs_init()
static int ttyfs_init () static
Definition at line 32 of file sbus_tty.c.
 {
     //DBG_puts("SIOTTY: FS Init()\n");
         return 0;
 }
ttyfs_ioctl2()
static int ttyfs_ioctl2 (iop_file_t * file, int cmd, void * arg, size_t arglen, void * buf, size_t buflen) static
Definition at line 119 of file sbus_tty.c.
{
     //DBG_puts("SIOTTY: FS IOCTL2()\n");
     return(-1);
 }
ttyfs_lseek()
static int ttyfs_lseek (iop_file_t * file, int offset, int mode) static
Definition at line 83 of file sbus_tty.c.
{
     //DBG_puts("SIOTTY: FS Lseek()\n");
     return(-1);
 }
ttyfs_open()
static int ttyfs_open (iop_file_t * file, const char * name, int flags, int mode) static
Definition at line 44 of file sbus_tty.c.
 {
     //DBG_puts("SIOTTY: FS Open()\n");
         return 0;
 }
ttyfs_read()
static int ttyfs_read (iop_file_t * file, void * ptr, size_t size) static
Definition at line 56 of file sbus_tty.c.
{
     //DBG_puts("SIOTTY: FS Read()\n");
     return(-1);
 }
ttyfs_remove()
static int ttyfs_remove (iop_file_t * file, const char * name) static
Definition at line 95 of file sbus_tty.c.
{
     //DBG_puts("SIOTTY: FS Remove()\n");
     return(-1);
 }
ttyfs_write()
static int ttyfs_write (iop_file_t * file, u8 * ptr, size_t size) static
Definition at line 61 of file sbus_tty.c.
{
     char temp[65];
     int bCount = 0, toWrite;
     //DBG_puts("SIOTTY: FS Write()\n");
     while(bCount < size)
     {
         toWrite = (size - bCount);
         if(toWrite > 64)
             toWrite = 64;
         memcpy(temp, &ptr[bCount], toWrite);
         temp[toWrite] = '\0';
         sbus_tty_puts(temp);
         bCount += toWrite;
     }
     return(bCount);
 }
References memcpy(), and sbus_tty_puts().
Variable Documentation
fsd_ops
void* fsd_ops[] static
Initial value:
= { ttyfs_init, ttyfs_deinit, ttyfs_format, ttyfs_open, ttyfs_close,
        ttyfs_read, ttyfs_write, ttyfs_lseek, ttyfs_error, ttyfs_remove, ttyfs_error, ttyfs_error,
        ttyfs_open, ttyfs_close, ttyfs_dread, ttyfs_getstat, ttyfs_error, ttyfs_error, ttyfs_error,
        ttyfs_error, ttyfs_error, ttyfs_error, ttyfs_error, ttyfs_devctl, ttyfs_error, ttyfs_error,
        ttyfs_ioctl2
}
Definition at line 126 of file sbus_tty.c.
kprint_buffer
char kprint_buffer[1024] static
Definition at line 152 of file sbus_tty.c.
Referenced by _kPrintf().
tty_fsd
iop_device_t tty_fsd
Initial value:
=
{
        "tty",
        0x10,
        1,
        "TTY via EE SIO",
        (iop_device_ops_t *) &fsd_ops
}
Definition at line 133 of file sbus_tty.c.
Referenced by sbus_tty_init().