ps2sdk: iop/debug/iop_sbusdbg/src/sbus_tty.h File Reference
sbus_tty.h File Reference
#include "tamtypes.h"
Functions
int sbus_tty_init (void)
Function Documentation
sbus_tty_init()
int sbus_tty_init (void)
Definition at line 161 of file sbus_tty.c.
 {
     close(0);
     close(1);
         DelDrv("tty");
         DelDrv("dummytty");
         if(AddDrv(&tty_fsd) != 0) { return(-1); }
     open("tty:", O_RDONLY);
     open("tty:", O_WRONLY);
     KprintfSet(&_kPrintf, NULL);
     return(0);
 }
References _kPrintf(), AddDrv(), close(), DelDrv(), KprintfSet(), NULL, O_RDONLY, O_WRONLY, open(), and tty_fsd.
Referenced by _start().