ps2sdk: iop/kernel/include/secrman.h File Reference
secrman.h File Reference
#include <types.h>
#include <irx.h>
#include <sio2man.h>
#include <libsecr-common.h>
Macros
#define secrman_IMPORTS_start DECLARE_IMPORT_TABLE(secrman, 1, 3)
#define secrman_IMPORTS_end END_IMPORT_TABLE
#define I_SecrSetMcCommandHandler DECLARE_IMPORT(4, SecrSetMcCommandHandler)
#define I_SecrSetMcDevIDHandler DECLARE_IMPORT(5, SecrSetMcDevIDHandler)
#define I_SecrAuthCard DECLARE_IMPORT(6, SecrAuthCard)
#define I_SecrResetAuthCard DECLARE_IMPORT(7, SecrResetAuthCard)
#define I_SecrCardBootHeader DECLARE_IMPORT(8, SecrCardBootHeader)
#define I_SecrCardBootBlock DECLARE_IMPORT(9, SecrCardBootBlock)
#define I_SecrCardBootFile DECLARE_IMPORT(10, SecrCardBootFile)
#define I_SecrDiskBootHeader DECLARE_IMPORT(11, SecrDiskBootHeader)
#define I_SecrDiskBootBlock DECLARE_IMPORT(12, SecrDiskBootBlock)
#define I_SecrDiskBootFile DECLARE_IMPORT(13, SecrDiskBootFile)
#define I_SecrDownloadHeader DECLARE_IMPORT(14, SecrDownloadHeader)
#define I_SecrDownloadBlock DECLARE_IMPORT(15, SecrDownloadBlock)
#define I_SecrDownloadFile DECLARE_IMPORT(16, SecrDownloadFile)
#define I_SecrDownloadGetKbit DECLARE_IMPORT(17, SecrDownloadGetKbit)
#define I_SecrDownloadGetKc DECLARE_IMPORT(18, SecrDownloadGetKc)
#define I_SecrDownloadGetICVPS2 DECLARE_IMPORT(19, SecrDownloadGetICVPS2)
Typedefs
typedef int(* McCommandHandler_t) (int port, int slot, sio2_transfer_data_t *sio2_trans_data)
typedef int(* McDevIDHandler_t) (int port, int slot)
Functions
void SecrSetMcCommandHandler (McCommandHandler_t handler)
void SecrSetMcDevIDHandler (McDevIDHandler_t handler)
int SecrAuthCard (int port, int slot, int cnum)
void SecrResetAuthCard (int port, int slot, int cnum)
Detailed Description
Definitions and imports for secrman module.
Definition in file secrman.h.
Macro Definition Documentation
I_SecrAuthCard
#define I_SecrAuthCard DECLARE_IMPORT(6, SecrAuthCard)
Definition at line 38 of file secrman.h.
I_SecrCardBootBlock
#define I_SecrCardBootBlock DECLARE_IMPORT(9, SecrCardBootBlock)
Definition at line 42 of file secrman.h.
I_SecrCardBootFile
#define I_SecrCardBootFile DECLARE_IMPORT(10, SecrCardBootFile)
Definition at line 43 of file secrman.h.
I_SecrCardBootHeader
#define I_SecrCardBootHeader DECLARE_IMPORT(8, SecrCardBootHeader)
Definition at line 41 of file secrman.h.
I_SecrDiskBootBlock
#define I_SecrDiskBootBlock DECLARE_IMPORT(12, SecrDiskBootBlock)
Definition at line 45 of file secrman.h.
I_SecrDiskBootFile
#define I_SecrDiskBootFile DECLARE_IMPORT(13, SecrDiskBootFile)
Definition at line 46 of file secrman.h.
I_SecrDiskBootHeader
#define I_SecrDiskBootHeader DECLARE_IMPORT(11, SecrDiskBootHeader)
Definition at line 44 of file secrman.h.
I_SecrDownloadBlock
#define I_SecrDownloadBlock DECLARE_IMPORT(15, SecrDownloadBlock)
Definition at line 50 of file secrman.h.
I_SecrDownloadFile
#define I_SecrDownloadFile DECLARE_IMPORT(16, SecrDownloadFile)
Definition at line 51 of file secrman.h.
I_SecrDownloadGetICVPS2
#define I_SecrDownloadGetICVPS2 DECLARE_IMPORT(19, SecrDownloadGetICVPS2)
Definition at line 54 of file secrman.h.
I_SecrDownloadGetKbit
#define I_SecrDownloadGetKbit DECLARE_IMPORT(17, SecrDownloadGetKbit)
Definition at line 52 of file secrman.h.
I_SecrDownloadGetKc
#define I_SecrDownloadGetKc DECLARE_IMPORT(18, SecrDownloadGetKc)
Definition at line 53 of file secrman.h.
I_SecrDownloadHeader
#define I_SecrDownloadHeader DECLARE_IMPORT(14, SecrDownloadHeader)
Definition at line 49 of file secrman.h.
I_SecrResetAuthCard
#define I_SecrResetAuthCard DECLARE_IMPORT(7, SecrResetAuthCard)
Definition at line 39 of file secrman.h.
I_SecrSetMcCommandHandler
#define I_SecrSetMcCommandHandler DECLARE_IMPORT(4, SecrSetMcCommandHandler)
Definition at line 36 of file secrman.h.
I_SecrSetMcDevIDHandler
#define I_SecrSetMcDevIDHandler DECLARE_IMPORT(5, SecrSetMcDevIDHandler)
Definition at line 37 of file secrman.h.
secrman_IMPORTS_end
#define secrman_IMPORTS_end END_IMPORT_TABLE
Definition at line 34 of file secrman.h.
secrman_IMPORTS_start
#define secrman_IMPORTS_start DECLARE_IMPORT_TABLE(secrman, 1, 3)
Definition at line 33 of file secrman.h.
Typedef Documentation
McCommandHandler_t
typedef int(* McCommandHandler_t) (int port, int slot, sio2_transfer_data_t *sio2_trans_data)
Definition at line 24 of file secrman.h.
McDevIDHandler_t
typedef int(* McDevIDHandler_t) (int port, int slot)
Definition at line 25 of file secrman.h.
Function Documentation
SecrAuthCard()
int SecrAuthCard (int port, int slot, int cnum)
Referenced by mcman_probePS2Card().
SecrResetAuthCard()
void SecrResetAuthCard (int port, int slot, int cnum)
SecrSetMcCommandHandler()
void SecrSetMcCommandHandler (McCommandHandler_t handler)
Referenced by mcman_initPS2com().
SecrSetMcDevIDHandler()
void SecrSetMcDevIDHandler (McDevIDHandler_t handler)
Referenced by mcman_initPS2com().