ps2sdk: iop/kernel/include/sifcmd.h File Reference
sifcmd.h File Reference
#include <types.h>
#include <irx.h>
Data Structures
struct SifCmdHeader_t
struct SifCmdSRegData_t
struct SifCmdHandlerData_t
struct SifRpcServerData_t
struct SifRpcHeader_t
struct SifRpcClientData_t
struct SifRpcReceiveData_t
struct SifRpcDataQueue_t
Macros
#define SIF_CMD_ID_SYSTEM 0x80000000
#define SIF_CMD_SET_SREG (SIF_CMD_ID_SYSTEM | 1)
#define SIF_CMD_INIT_CMD (SIF_CMD_ID_SYSTEM | 2)
#define SIF_CMD_RESET_CMD (SIF_CMD_ID_SYSTEM | 3)
#define SIF_CMD_RPC_END (SIF_CMD_ID_SYSTEM | 8)
#define SIF_CMD_RPC_BIND (SIF_CMD_ID_SYSTEM | 9)
#define SIF_CMD_RPC_CALL (SIF_CMD_ID_SYSTEM | 10)
#define SIF_CMD_RPC_RDATA (SIF_CMD_ID_SYSTEM | 12)
#define SIF_SREG_RPCINIT 0
#define SIF_RPC_M_NOWAIT 0x01
#define SIF_RPC_M_NOWBDC 0x02
#define SifInitRpc sceSifInitRpc
#define SifBindRpc sceSifBindRpc
#define SifCallRpc sceSifCallRpc
#define SifRegisterRpc sceSifRegisterRpc
#define SifCheckStatRpc sceSifCheckStatRpc
#define SifSetRpcQueue sceSifSetRpcQueue
#define SifGetNextRequest sceSifGetNextRequest
#define SifExecRequest sceSifExecRequest
#define SifRpcLoop sceSifRpcLoop
#define SifRpcGetOtherData sceSifGetOtherData
#define sifcmd_IMPORTS_start DECLARE_IMPORT_TABLE(sifcmd, 1, 1)
#define sifcmd_IMPORTS_end END_IMPORT_TABLE
#define I_sceSifInitCmd DECLARE_IMPORT(4, sceSifInitCmd)
#define I_sceSifExitCmd DECLARE_IMPORT(5, sceSifExitCmd)
#define I_sceSifGetSreg DECLARE_IMPORT(6, sceSifGetSreg)
#define I_sceSifSetSreg DECLARE_IMPORT(7, sceSifSetSreg)
#define I_sceSifSetCmdBuffer DECLARE_IMPORT(8, sceSifSetCmdBuffer)
#define I_sceSifSetSysCmdBuffer DECLARE_IMPORT(9, sceSifSetSysCmdBuffer)
#define I_sceSifAddCmdHandler DECLARE_IMPORT(10, sceSifAddCmdHandler)
#define I_sceSifRemoveCmdHandler DECLARE_IMPORT(11, sceSifRemoveCmdHandler)
#define I_sceSifSendCmd DECLARE_IMPORT(12, sceSifSendCmd)
#define I_isceSifSendCmd DECLARE_IMPORT(13, isceSifSendCmd)
#define I_sceSifInitRpc DECLARE_IMPORT(14, sceSifInitRpc)
#define I_sceSifBindRpc DECLARE_IMPORT(15, sceSifBindRpc)
#define I_sceSifCallRpc DECLARE_IMPORT(16, sceSifCallRpc)
#define I_sceSifRegisterRpc DECLARE_IMPORT(17, sceSifRegisterRpc)
#define I_sceSifCheckStatRpc DECLARE_IMPORT(18, sceSifCheckStatRpc)
#define I_sceSifSetRpcQueue DECLARE_IMPORT(19, sceSifSetRpcQueue)
#define I_sceSifGetNextRequest DECLARE_IMPORT(20, sceSifGetNextRequest)
#define I_sceSifExecRequest DECLARE_IMPORT(21, sceSifExecRequest)
#define I_sceSifRpcLoop DECLARE_IMPORT(22, sceSifRpcLoop)
#define I_sceSifGetOtherData DECLARE_IMPORT(23, sceSifGetOtherData)
#define I_sceSifRemoveRpc DECLARE_IMPORT(24, sceSifRemoveRpc)
#define I_sceSifRemoveRpcQueue DECLARE_IMPORT(25, sceSifRemoveRpcQueue)
#define I_sceSifSetSif1CB DECLARE_IMPORT(26, sceSifSetSif1CB)
#define I_sceSifClearSif1CB DECLARE_IMPORT(27, sceSifClearSif1CB)
#define I_sceSifSendCmdIntr DECLARE_IMPORT(28, sceSifSendCmdIntr)
#define I_isceSifSendCmdIntr DECLARE_IMPORT(29, isceSifSendCmdIntr)
Typedefs
typedef void(* SifCmdHandler_t) (void *data, void *harg)
typedef void *(* SifRpcFunc_t) (int fno, void *buffer, int length)
typedef void(* SifRpcEndFunc_t) (void *end_param)
Functions
void sceSifInitCmd (void)
void sceSifExitCmd (void)
void sceSifGetSreg (int index)
void sceSifSetSreg (int index, unsigned int value)
void sceSifSetCmdBuffer (SifCmdHandlerData_t *cmdBuffer, int size)
void sceSifSetSysCmdBuffer (SifCmdHandlerData_t *sysCmdBuffer, int size)
void sceSifAddCmdHandler (int cid, SifCmdHandler_t handler, void *harg)
void sceSifRemoveCmdHandler (int cid)
unsigned int sceSifSendCmd (int cmd, void *packet, int packet_size, void *src_extra, void *dest_extra, int size_extra)
unsigned int isceSifSendCmd (int cmd, void *packet, int packet_size, void *src_extra, void *dest_extra, int size_extra)
void sceSifInitRpc (int mode)
int sceSifBindRpc (SifRpcClientData_t *client, int rpc_number, int mode)
int sceSifCallRpc (SifRpcClientData_t *client, int rpc_number, int mode, void *send, int ssize, void *receive, int rsize, SifRpcEndFunc_t end_function, void *end_param)
void sceSifRegisterRpc (SifRpcServerData_t *sd, int sid, SifRpcFunc_t func, void *buf, SifRpcFunc_t cfunc, void *cbuf, SifRpcDataQueue_t *qd)
int sceSifCheckStatRpc (SifRpcClientData_t *cd)
SifRpcDataQueue_t * sceSifSetRpcQueue (SifRpcDataQueue_t *q, int thread_id)
SifRpcServerData_t * sceSifGetNextRequest (SifRpcDataQueue_t *qd)
void sceSifExecRequest (SifRpcServerData_t *srv)
void sceSifRpcLoop (SifRpcDataQueue_t *qd)
int sceSifGetOtherData (SifRpcReceiveData_t *rd, void *src, void *dest, int size, int mode)
SifRpcServerData_t * sceSifRemoveRpc (SifRpcServerData_t *sd, SifRpcDataQueue_t *qd)
SifRpcDataQueue_t * sceSifRemoveRpcQueue (SifRpcDataQueue_t *qd)
void sceSifSetSif1CB (void *func, int param)
void sceSifClearSif1CB (void)
unsigned int sceSifSendCmdIntr (unsigned int, void *, int, void *, void *, int, void(*func)(), void *)
unsigned int isceSifSendCmdIntr (unsigned int, void *, int, void *, void *, int, void(*func)(), void *)
Detailed Description
SIF CMD and RPC.
Definition in file sifcmd.h.
Macro Definition Documentation
I_isceSifSendCmd
#define I_isceSifSendCmd DECLARE_IMPORT(13, isceSifSendCmd)
Definition at line 204 of file sifcmd.h.
I_isceSifSendCmdIntr
#define I_isceSifSendCmdIntr DECLARE_IMPORT(29, isceSifSendCmdIntr)
Definition at line 220 of file sifcmd.h.
I_sceSifAddCmdHandler
#define I_sceSifAddCmdHandler DECLARE_IMPORT(10, sceSifAddCmdHandler)
Definition at line 201 of file sifcmd.h.
I_sceSifBindRpc
#define I_sceSifBindRpc DECLARE_IMPORT(15, sceSifBindRpc)
Definition at line 206 of file sifcmd.h.
I_sceSifCallRpc
#define I_sceSifCallRpc DECLARE_IMPORT(16, sceSifCallRpc)
Definition at line 207 of file sifcmd.h.
I_sceSifCheckStatRpc
#define I_sceSifCheckStatRpc DECLARE_IMPORT(18, sceSifCheckStatRpc)
Definition at line 209 of file sifcmd.h.
I_sceSifClearSif1CB
#define I_sceSifClearSif1CB DECLARE_IMPORT(27, sceSifClearSif1CB)
Definition at line 218 of file sifcmd.h.
I_sceSifExecRequest
#define I_sceSifExecRequest DECLARE_IMPORT(21, sceSifExecRequest)
Definition at line 212 of file sifcmd.h.
I_sceSifExitCmd
#define I_sceSifExitCmd DECLARE_IMPORT(5, sceSifExitCmd)
Definition at line 196 of file sifcmd.h.
I_sceSifGetNextRequest
#define I_sceSifGetNextRequest DECLARE_IMPORT(20, sceSifGetNextRequest)
Definition at line 211 of file sifcmd.h.
I_sceSifGetOtherData
#define I_sceSifGetOtherData DECLARE_IMPORT(23, sceSifGetOtherData)
Definition at line 214 of file sifcmd.h.
I_sceSifGetSreg
#define I_sceSifGetSreg DECLARE_IMPORT(6, sceSifGetSreg)
Definition at line 197 of file sifcmd.h.
I_sceSifInitCmd
#define I_sceSifInitCmd DECLARE_IMPORT(4, sceSifInitCmd)
Definition at line 195 of file sifcmd.h.
I_sceSifInitRpc
#define I_sceSifInitRpc DECLARE_IMPORT(14, sceSifInitRpc)
Definition at line 205 of file sifcmd.h.
I_sceSifRegisterRpc
#define I_sceSifRegisterRpc DECLARE_IMPORT(17, sceSifRegisterRpc)
Definition at line 208 of file sifcmd.h.
I_sceSifRemoveCmdHandler
#define I_sceSifRemoveCmdHandler DECLARE_IMPORT(11, sceSifRemoveCmdHandler)
Definition at line 202 of file sifcmd.h.
I_sceSifRemoveRpc
#define I_sceSifRemoveRpc DECLARE_IMPORT(24, sceSifRemoveRpc)
Definition at line 215 of file sifcmd.h.
I_sceSifRemoveRpcQueue
#define I_sceSifRemoveRpcQueue DECLARE_IMPORT(25, sceSifRemoveRpcQueue)
Definition at line 216 of file sifcmd.h.
I_sceSifRpcLoop
#define I_sceSifRpcLoop DECLARE_IMPORT(22, sceSifRpcLoop)
Definition at line 213 of file sifcmd.h.
I_sceSifSendCmd
#define I_sceSifSendCmd DECLARE_IMPORT(12, sceSifSendCmd)
Definition at line 203 of file sifcmd.h.
I_sceSifSendCmdIntr
#define I_sceSifSendCmdIntr DECLARE_IMPORT(28, sceSifSendCmdIntr)
Definition at line 219 of file sifcmd.h.
I_sceSifSetCmdBuffer
#define I_sceSifSetCmdBuffer DECLARE_IMPORT(8, sceSifSetCmdBuffer)
Definition at line 199 of file sifcmd.h.
I_sceSifSetRpcQueue
#define I_sceSifSetRpcQueue DECLARE_IMPORT(19, sceSifSetRpcQueue)
Definition at line 210 of file sifcmd.h.
I_sceSifSetSif1CB
#define I_sceSifSetSif1CB DECLARE_IMPORT(26, sceSifSetSif1CB)
Definition at line 217 of file sifcmd.h.
I_sceSifSetSreg
#define I_sceSifSetSreg DECLARE_IMPORT(7, sceSifSetSreg)
Definition at line 198 of file sifcmd.h.
I_sceSifSetSysCmdBuffer
#define I_sceSifSetSysCmdBuffer DECLARE_IMPORT(9, sceSifSetSysCmdBuffer)
Definition at line 200 of file sifcmd.h.
SIF_CMD_ID_SYSTEM
#define SIF_CMD_ID_SYSTEM 0x80000000
Definition at line 37 of file sifcmd.h.
SIF_CMD_INIT_CMD
#define SIF_CMD_INIT_CMD (SIF_CMD_ID_SYSTEM | 2)
Definition at line 40 of file sifcmd.h.
SIF_CMD_RESET_CMD
#define SIF_CMD_RESET_CMD (SIF_CMD_ID_SYSTEM | 3)
Definition at line 41 of file sifcmd.h.
SIF_CMD_RPC_BIND
#define SIF_CMD_RPC_BIND (SIF_CMD_ID_SYSTEM | 9)
Definition at line 43 of file sifcmd.h.
SIF_CMD_RPC_CALL
#define SIF_CMD_RPC_CALL (SIF_CMD_ID_SYSTEM | 10)
Definition at line 44 of file sifcmd.h.
SIF_CMD_RPC_END
#define SIF_CMD_RPC_END (SIF_CMD_ID_SYSTEM | 8)
Definition at line 42 of file sifcmd.h.
SIF_CMD_RPC_RDATA
#define SIF_CMD_RPC_RDATA (SIF_CMD_ID_SYSTEM | 12)
Definition at line 45 of file sifcmd.h.
SIF_CMD_SET_SREG
#define SIF_CMD_SET_SREG (SIF_CMD_ID_SYSTEM | 1)
Definition at line 39 of file sifcmd.h.
SIF_RPC_M_NOWAIT
#define SIF_RPC_M_NOWAIT 0x01
Don't wait for end function
Definition at line 78 of file sifcmd.h.
SIF_RPC_M_NOWBDC
#define SIF_RPC_M_NOWBDC 0x02
Don't write back the D cache
Definition at line 80 of file sifcmd.h.
SIF_SREG_RPCINIT
#define SIF_SREG_RPCINIT 0
Definition at line 48 of file sifcmd.h.
SifBindRpc
#define SifBindRpc sceSifBindRpc
Definition at line 178 of file sifcmd.h.
SifCallRpc
#define SifCallRpc sceSifCallRpc
Definition at line 179 of file sifcmd.h.
SifCheckStatRpc
#define SifCheckStatRpc sceSifCheckStatRpc
Definition at line 183 of file sifcmd.h.
sifcmd_IMPORTS_end
#define sifcmd_IMPORTS_end END_IMPORT_TABLE
Definition at line 193 of file sifcmd.h.
sifcmd_IMPORTS_start
#define sifcmd_IMPORTS_start DECLARE_IMPORT_TABLE(sifcmd, 1, 1)
Definition at line 192 of file sifcmd.h.
SifExecRequest
#define SifExecRequest sceSifExecRequest
Definition at line 187 of file sifcmd.h.
SifGetNextRequest
#define SifGetNextRequest sceSifGetNextRequest
Definition at line 186 of file sifcmd.h.
SifInitRpc
#define SifInitRpc sceSifInitRpc
Definition at line 177 of file sifcmd.h.
SifRegisterRpc
#define SifRegisterRpc sceSifRegisterRpc
Definition at line 181 of file sifcmd.h.
SifRpcGetOtherData
#define SifRpcGetOtherData sceSifGetOtherData
Definition at line 190 of file sifcmd.h.
SifRpcLoop
#define SifRpcLoop sceSifRpcLoop
Definition at line 188 of file sifcmd.h.
SifSetRpcQueue
#define SifSetRpcQueue sceSifSetRpcQueue
Definition at line 185 of file sifcmd.h.
Typedef Documentation
SifCmdHandler_t
typedef void(* SifCmdHandler_t) (void *data, void *harg)
Definition at line 59 of file sifcmd.h.
SifRpcEndFunc_t
typedef void(* SifRpcEndFunc_t) (void *end_param)
Definition at line 83 of file sifcmd.h.
SifRpcFunc_t
typedef void*(* SifRpcFunc_t) (int fno, void *buffer, int length)
Definition at line 82 of file sifcmd.h.
Function Documentation
isceSifSendCmd()
unsigned int isceSifSendCmd (int cmd, void * packet, int packet_size, void * src_extra, void * dest_extra, int size_extra)
isceSifSendCmdIntr()
unsigned int isceSifSendCmdIntr (unsigned int , void * , int , void * , void * , int , void(*)() func, void *)
sceSifAddCmdHandler()
void sceSifAddCmdHandler (int cid, SifCmdHandler_t handler, void * harg)
Referenced by NETMAN_rpc_handler().
sceSifBindRpc()
int sceSifBindRpc (SifRpcClientData_t * client, int rpc_number, int mode)
Referenced by initialize_rpc_client(), InitPowerOffThread(), and NetManInitRPCClient().
sceSifCallRpc()
int sceSifCallRpc (SifRpcClientData_t * client, int rpc_number, int mode, void * send, int ssize, void * receive, int rsize, SifRpcEndFunc_t end_function, void * end_param)
Referenced by call_client_callback(), NetManInitRPCClient(), NetManRpcToggleGlobalNetIFLinkState(), and PowerOffThread().
sceSifCheckStatRpc()
int sceSifCheckStatRpc (SifRpcClientData_t * cd)
sceSifClearSif1CB()
void sceSifClearSif1CB (void)
sceSifExecRequest()
void sceSifExecRequest (SifRpcServerData_t * srv)
sceSifExitCmd()
void sceSifExitCmd (void)
sceSifGetNextRequest()
SifRpcServerData_t* sceSifGetNextRequest (SifRpcDataQueue_t * qd)
sceSifGetOtherData()
int sceSifGetOtherData (SifRpcReceiveData_t * rd, void * src, void * dest, int size, int mode)
Referenced by _McSetFileInfo(), _McWrite(), and _McWritePage().
sceSifGetSreg()
void sceSifGetSreg (int index)
sceSifInitCmd()
void sceSifInitCmd (void)
sceSifInitRpc()
void sceSifInitRpc (int mode)
Referenced by rpc_thread(), rpc_thread_change_slot(), rpc_thread_get_slot_number(), rpcMainThread(), RpcThread(), RpcThreadExt(), RpcThreadGetConnection(), RpcThreadPortClose(), RpcThreadPortOpen(), and thread_rpc_S_0400().
sceSifRegisterRpc()
void sceSifRegisterRpc (SifRpcServerData_t * sd, int sid, SifRpcFunc_t func, void * buf, SifRpcFunc_t cfunc, void * cbuf, SifRpcDataQueue_t * qd)
Referenced by NETMAN_RPC_srv(), rpc_thread(), rpc_thread_change_slot(), rpc_thread_get_slot_number(), rpcMainThread(), RpcThread(), RpcThreadExt(), RpcThreadGetConnection(), RpcThreadPortClose(), RpcThreadPortOpen(), and thread_rpc_S_0400().
sceSifRemoveCmdHandler()
void sceSifRemoveCmdHandler (int cid)
Referenced by unregisterEENetworkStack().
sceSifRemoveRpc()
SifRpcServerData_t* sceSifRemoveRpc (SifRpcServerData_t * sd, SifRpcDataQueue_t * qd)
Referenced by NetmanDeinitRPCServer().
sceSifRemoveRpcQueue()
SifRpcDataQueue_t* sceSifRemoveRpcQueue (SifRpcDataQueue_t * qd)
Referenced by NetmanDeinitRPCServer().
sceSifRpcLoop()
void sceSifRpcLoop (SifRpcDataQueue_t * qd)
Referenced by NETMAN_RPC_srv(), rpc_thread(), rpc_thread_change_slot(), rpc_thread_get_slot_number(), rpcMainThread(), RpcThread(), RpcThreadExt(), RpcThreadGetConnection(), RpcThreadPortClose(), RpcThreadPortOpen(), and thread_rpc_S_0400().
sceSifSendCmd()
unsigned int sceSifSendCmd (int cmd, void * packet, int packet_size, void * src_extra, void * dest_extra, int size_extra)
sceSifSendCmdIntr()
unsigned int sceSifSendCmdIntr (unsigned int , void * , int , void * , void * , int , void(*)() func, void *)
sceSifSetCmdBuffer()
void sceSifSetCmdBuffer (SifCmdHandlerData_t * cmdBuffer, int size)
sceSifSetRpcQueue()
SifRpcDataQueue_t* sceSifSetRpcQueue (SifRpcDataQueue_t * q, int thread_id)
Referenced by NETMAN_RPC_srv(), rpc_thread(), rpc_thread_change_slot(), rpc_thread_get_slot_number(), rpcMainThread(), RpcThread(), RpcThreadExt(), RpcThreadGetConnection(), RpcThreadPortClose(), RpcThreadPortOpen(), and thread_rpc_S_0400().
sceSifSetSif1CB()
void sceSifSetSif1CB (void * func, int param)
sceSifSetSreg()
void sceSifSetSreg (int index, unsigned int value)
sceSifSetSysCmdBuffer()
void sceSifSetSysCmdBuffer (SifCmdHandlerData_t * sysCmdBuffer, int size)