ps2sdk: iop/system/padman/src/sio2Cmds.h File Reference
sio2Cmds.h File Reference
Macros
#define SIO2_CMD_MAX 16
#define PAD_ID_FINDPADS 0x01
#define PAD_ID_MOUSE 0x12
#define PAD_ID_NEGICON 0x23
#define PAD_ID_KONAMIGUN 0x31
#define PAD_ID_DIGITAL 0x41
#define PAD_ID_JOYSTICK 0x53
#define PAD_ID_NAMCOGUN 0x63
#define PAD_ID_ANALOG 0x73
#define PAD_ID_ANALOG2 0x79
#define PAD_ID_MULTITAP 0x80
#define PAD_ID_JOGCON 0xE3
#define PAD_ID_JOGCON2 0xE5
#define PAD_ID_CONFIG 0xF3
#define PAD_ID_HI(id) ((id)>>4)
#define PAD_ID_LO(id) ((id)&0xF)
Functions
void sio2cmdReset (void)
void sio2cmdInitFindPads (void)
void sio2cmdInitMouse (void)
void sio2cmdInitNegicon (void)
void sio2cmdInitKonamiGun (void)
void sio2cmdInitDigital (void)
void sio2cmdInitJoystick (void)
void sio2cmdInitNamcoGun (void)
void sio2cmdInitAnalog (void)
void sio2cmdInitJogcon (void)
void sio2cmdInitConfig (void)
u32 sio2cmdCheckId (u8 id)
void sio2CmdSetReadData (u32 id, u8 *buf)
u32 sio2CmdSetEnterConfigMode (u32 id, u8 *buf)
u32 sio2CmdSetExitConfigMode (u32 id, u8 *buf)
u32 sio2CmdSetQueryModel (u32 id, u8 *buf)
u32 sio2CmdSetQueryAct (u32 id, u8 *buf)
u32 sio2CmdSetQueryComb (u32 id, u8 *buf)
u32 sio2CmdSetQueryMode (u32 id, u8 *buf)
u32 sio2CmdSetQueryButtonMask (u32 id, u8 *buf)
u32 sio2CmdSetSetButtonInfo (u32 id, u8 *buf)
u32 sio2CmdSetSetVrefParam (u32 id, u8 *buf)
u32 sio2CmdSetSetMainMode (u32 id, u8 *buf)
u32 sio2CmdSetSetActAlign (u32 id, u8 *buf)
u32 sio2CmdGetPortCtrl1 (u8 id, u32 b, u8 c)
u32 sio2CmdGetPortCtrl2 (u32 id, u32 b)
Detailed Description
IOP pad driver
Definition in file sio2Cmds.h.
Macro Definition Documentation
PAD_ID_ANALOG
#define PAD_ID_ANALOG 0x73
Definition at line 24 of file sio2Cmds.h.
PAD_ID_ANALOG2
#define PAD_ID_ANALOG2 0x79
Definition at line 25 of file sio2Cmds.h.
PAD_ID_CONFIG
#define PAD_ID_CONFIG 0xF3
Definition at line 29 of file sio2Cmds.h.
PAD_ID_DIGITAL
#define PAD_ID_DIGITAL 0x41
Definition at line 21 of file sio2Cmds.h.
PAD_ID_FINDPADS
#define PAD_ID_FINDPADS 0x01
Definition at line 17 of file sio2Cmds.h.
PAD_ID_HI
#define PAD_ID_HI (id) ((id)>>4)
Definition at line 31 of file sio2Cmds.h.
PAD_ID_JOGCON
#define PAD_ID_JOGCON 0xE3
Definition at line 27 of file sio2Cmds.h.
PAD_ID_JOGCON2
#define PAD_ID_JOGCON2 0xE5
Definition at line 28 of file sio2Cmds.h.
PAD_ID_JOYSTICK
#define PAD_ID_JOYSTICK 0x53
Definition at line 22 of file sio2Cmds.h.
PAD_ID_KONAMIGUN
#define PAD_ID_KONAMIGUN 0x31
Definition at line 20 of file sio2Cmds.h.
PAD_ID_LO
#define PAD_ID_LO (id) ((id)&0xF)
Definition at line 32 of file sio2Cmds.h.
PAD_ID_MOUSE
#define PAD_ID_MOUSE 0x12
Definition at line 18 of file sio2Cmds.h.
PAD_ID_MULTITAP
#define PAD_ID_MULTITAP 0x80
Definition at line 26 of file sio2Cmds.h.
PAD_ID_NAMCOGUN
#define PAD_ID_NAMCOGUN 0x63
Definition at line 23 of file sio2Cmds.h.
PAD_ID_NEGICON
#define PAD_ID_NEGICON 0x23
Definition at line 19 of file sio2Cmds.h.
SIO2_CMD_MAX
#define SIO2_CMD_MAX 16
Definition at line 15 of file sio2Cmds.h.
Function Documentation
sio2cmdCheckId()
u32 sio2cmdCheckId (u8 id)
Definition at line 1149 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if( sio2Cmds[i].id == id )
                         return 1;
         }
         return 0;
 }
References numControllers, PAD_ID_HI, and sio2Cmds.
Referenced by PadIsSupported().
sio2CmdGetPortCtrl1()
u32 sio2CmdGetPortCtrl1 (u8 id, u32 b, u8 c)
Definition at line 1164 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if(sio2Cmds[i].id == id)
                 {
                         if(sio2Cmds[i].getportctrl1 != NULL)
                                 return sio2Cmds[i].getportctrl1(b, c);
                 }
         }
         return 0;
 }
References sio2Cmds_t::getportctrl1, NULL, numControllers, PAD_ID_HI, and sio2Cmds.
Referenced by EnterConfigMode(), ExitConfigMode(), PadIsSupported(), QueryAct(), QueryButtonMask(), QueryComb(), QueryMode(), QueryModel(), ReadData(), SetActAlign(), SetButtonInfo(), SetMainMode(), setupReadData(), and VrefParam().
sio2CmdGetPortCtrl2()
u32 sio2CmdGetPortCtrl2 (u32 id, u32 b)
Definition at line 1181 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if(sio2Cmds[i].id == id)
                 {
                         if(sio2Cmds[i].getportctrl2 != NULL)
                                 return sio2Cmds[i].getportctrl2(b);
                 }
         }
         return 0;
 }
References sio2Cmds_t::getportctrl2, NULL, numControllers, PAD_ID_HI, and sio2Cmds.
Referenced by EnterConfigMode(), ExitConfigMode(), PadIsSupported(), QueryAct(), QueryButtonMask(), QueryComb(), QueryMode(), QueryModel(), ReadData(), SetActAlign(), SetButtonInfo(), SetMainMode(), setupReadData(), and VrefParam().
sio2cmdInitAnalog()
void sio2cmdInitAnalog (void)
Definition at line 796 of file sio2Cmds.c.
 {
         sio2Cmds_t s;
         s.id = PAD_ID_HI(PAD_ID_ANALOG);
         s.readdata = &AnalogReadData;
         s.getportctrl1 = &AnalogGetPortCtrl1;
         s.getportctrl2 = &AnalogGetPortCtrl2;
         s.reg_data = NULL;
         s.size1 = NULL;
         s.size2 = NULL;
         s.enterconfigmode = &AnalogEnterConfigMode;
         s.exitconfigmode = NULL;
         s.querymodel = NULL;
         s.queryact = NULL;
         s.querycomb = NULL;
         s.querymode = NULL;
         s.querybuttonmask = NULL;
         s.setbuttoninfo = NULL;
         s.setvrefparam = NULL;
         s.setmainmode = NULL;
         s.setactalign = NULL;
         SetupCmds(&s);
 }
References AnalogEnterConfigMode(), AnalogGetPortCtrl1(), AnalogGetPortCtrl2(), AnalogReadData(), sio2Cmds_t::enterconfigmode, sio2Cmds_t::exitconfigmode, sio2Cmds_t::getportctrl1, sio2Cmds_t::getportctrl2, sio2Cmds_t::id, NULL, PAD_ID_ANALOG, PAD_ID_HI, sio2Cmds_t::queryact, sio2Cmds_t::querybuttonmask, sio2Cmds_t::querycomb, sio2Cmds_t::querymode, sio2Cmds_t::querymodel, sio2Cmds_t::readdata, sio2Cmds_t::reg_data, sio2Cmds_t::setactalign, sio2Cmds_t::setbuttoninfo, sio2Cmds_t::setmainmode, SetupCmds(), sio2Cmds_t::setvrefparam, sio2Cmds_t::size1, and sio2Cmds_t::size2.
Referenced by padInit().
sio2cmdInitConfig()
void sio2cmdInitConfig (void)
Definition at line 1119 of file sio2Cmds.c.
 {
         sio2Cmds_t s;
         s.id = PAD_ID_HI( PAD_ID_CONFIG );
         s.readdata = &ConfigReadData;
         s.getportctrl1 = &ConfigGetPortCtrl1;
         s.getportctrl2 = &ConfigGetPortCtrl2;
         s.reg_data = &ConfigRegData;
         s.size1 = &ConfigSize1;
         s.size2 = &ConfigSize2;
         s.enterconfigmode = NULL;
         s.exitconfigmode = &ConfigExitConfigMode;
         s.querymodel = &ConfigQueryModel;
         s.queryact = &ConfigQueryAct;
         s.querycomb = &ConfigQueryComb;
         s.querymode = &ConfigQueryMode;
         s.querybuttonmask = &ConfigQueryButtonMask;
         s.setbuttoninfo = &ConfigSetButtonInfo;
         s.setvrefparam = &ConfigSetVrefParam;
         s.setmainmode = &ConfigSetMainMode;
         s.setactalign = &ConfigSetSetActAlign;
         SetupCmds(&s);
 }
References ConfigExitConfigMode(), ConfigGetPortCtrl1(), ConfigGetPortCtrl2(), ConfigQueryAct(), ConfigQueryButtonMask(), ConfigQueryComb(), ConfigQueryMode(), ConfigQueryModel(), ConfigReadData(), ConfigRegData(), ConfigSetButtonInfo(), ConfigSetMainMode(), ConfigSetSetActAlign(), ConfigSetVrefParam(), ConfigSize1(), ConfigSize2(), sio2Cmds_t::enterconfigmode, sio2Cmds_t::exitconfigmode, sio2Cmds_t::getportctrl1, sio2Cmds_t::getportctrl2, sio2Cmds_t::id, NULL, PAD_ID_CONFIG, PAD_ID_HI, sio2Cmds_t::queryact, sio2Cmds_t::querybuttonmask, sio2Cmds_t::querycomb, sio2Cmds_t::querymode, sio2Cmds_t::querymodel, sio2Cmds_t::readdata, sio2Cmds_t::reg_data, sio2Cmds_t::setactalign, sio2Cmds_t::setbuttoninfo, sio2Cmds_t::setmainmode, SetupCmds(), sio2Cmds_t::setvrefparam, sio2Cmds_t::size1, and sio2Cmds_t::size2.
Referenced by padInit().
sio2cmdInitDigital()
void sio2cmdInitDigital (void)
Definition at line 503 of file sio2Cmds.c.
 {
         sio2Cmds_t s;
         s.id = PAD_ID_HI(PAD_ID_DIGITAL);
         s.readdata = &DigitalReadData;
         s.getportctrl1 = &DigitalGetPortCtrl1;
         s.getportctrl2 = &DigitalGetPortCtrl2;
         s.reg_data = &DigitalRegData;
         s.size1 = &DigitalSize1;
         s.size2 = &DigitalSize2;
         s.enterconfigmode = &DigitalEnterConfigMode;
         s.exitconfigmode = NULL;
         s.querymodel = NULL;
         s.queryact = NULL;
         s.querycomb = NULL;
         s.querymode = NULL;
         s.querybuttonmask = NULL;
         s.setbuttoninfo = NULL;
         s.setvrefparam = NULL;
         s.setmainmode = NULL;
         s.setactalign = NULL;
         SetupCmds(&s);
 }
References DigitalEnterConfigMode(), DigitalGetPortCtrl1(), DigitalGetPortCtrl2(), DigitalReadData(), DigitalRegData(), DigitalSize1(), DigitalSize2(), sio2Cmds_t::enterconfigmode, sio2Cmds_t::exitconfigmode, sio2Cmds_t::getportctrl1, sio2Cmds_t::getportctrl2, sio2Cmds_t::id, NULL, PAD_ID_DIGITAL, PAD_ID_HI, sio2Cmds_t::queryact, sio2Cmds_t::querybuttonmask, sio2Cmds_t::querycomb, sio2Cmds_t::querymode, sio2Cmds_t::querymodel, sio2Cmds_t::readdata, sio2Cmds_t::reg_data, sio2Cmds_t::setactalign, sio2Cmds_t::setbuttoninfo, sio2Cmds_t::setmainmode, SetupCmds(), sio2Cmds_t::setvrefparam, sio2Cmds_t::size1, and sio2Cmds_t::size2.
Referenced by padInit().
sio2cmdInitFindPads()
void sio2cmdInitFindPads (void)
Definition at line 161 of file sio2Cmds.c.
 {
         sio2Cmds_t s;
         s.id = PAD_ID_HI(PAD_ID_FINDPADS);
         s.readdata = &FindPadsReadData;
         s.getportctrl1 = &FindPadsGetPortCtrl1;
         s.getportctrl2 = &FindPadsGetPortCtrl2;
         s.reg_data = &FindPadsRegData;
         s.size1 = &FindPadsGetSize1;
         s.size2 = &FindPadsGetSize2;
         s.enterconfigmode = &FindPadsEnterConfigMode;
         s.exitconfigmode = NULL;
         s.querymodel = NULL;
         s.queryact = NULL;
         s.querycomb = NULL;
         s.querymode = NULL;
         s.querybuttonmask = NULL;
         s.setbuttoninfo = NULL;
         s.setvrefparam = NULL;
         s.setmainmode = NULL;
         s.setactalign = NULL;
         SetupCmds(&s);
 }
References sio2Cmds_t::enterconfigmode, sio2Cmds_t::exitconfigmode, FindPadsEnterConfigMode(), FindPadsGetPortCtrl1(), FindPadsGetPortCtrl2(), FindPadsGetSize1(), FindPadsGetSize2(), FindPadsReadData(), FindPadsRegData(), sio2Cmds_t::getportctrl1, sio2Cmds_t::getportctrl2, sio2Cmds_t::id, NULL, PAD_ID_FINDPADS, PAD_ID_HI, sio2Cmds_t::queryact, sio2Cmds_t::querybuttonmask, sio2Cmds_t::querycomb, sio2Cmds_t::querymode, sio2Cmds_t::querymodel, sio2Cmds_t::readdata, sio2Cmds_t::reg_data, sio2Cmds_t::setactalign, sio2Cmds_t::setbuttoninfo, sio2Cmds_t::setmainmode, SetupCmds(), sio2Cmds_t::setvrefparam, sio2Cmds_t::size1, and sio2Cmds_t::size2.
Referenced by padInit().
sio2cmdInitJogcon()
void sio2cmdInitJogcon (void)
Definition at line 894 of file sio2Cmds.c.
 {
         sio2Cmds_t s;
         s.id = PAD_ID_HI(PAD_ID_JOGCON);
         s.readdata = &JogconReadData;
         s.getportctrl1 = &JogconGetPortCtrl1;
         s.getportctrl2 = &JogconGetPortCtrl2;
         s.reg_data = &JogconRegData;
         s.size1 = &JogconSize1;
         s.size2 = &JogconSize2;
         s.enterconfigmode = &JogconEnterConfigMode;
         s.exitconfigmode = NULL;
         s.querymodel = NULL;
         s.queryact = NULL;
         s.querycomb = NULL;
         s.querymode = NULL;
         s.querybuttonmask = NULL;
         s.setbuttoninfo = NULL;
         s.setvrefparam = NULL;
         s.setmainmode = NULL;
         s.setactalign = NULL;
         SetupCmds(&s);
 }
References sio2Cmds_t::enterconfigmode, sio2Cmds_t::exitconfigmode, sio2Cmds_t::getportctrl1, sio2Cmds_t::getportctrl2, sio2Cmds_t::id, JogconEnterConfigMode(), JogconGetPortCtrl1(), JogconGetPortCtrl2(), JogconReadData(), JogconRegData(), JogconSize1(), JogconSize2(), NULL, PAD_ID_HI, PAD_ID_JOGCON, sio2Cmds_t::queryact, sio2Cmds_t::querybuttonmask, sio2Cmds_t::querycomb, sio2Cmds_t::querymode, sio2Cmds_t::querymodel, sio2Cmds_t::readdata, sio2Cmds_t::reg_data, sio2Cmds_t::setactalign, sio2Cmds_t::setbuttoninfo, sio2Cmds_t::setmainmode, SetupCmds(), sio2Cmds_t::setvrefparam, sio2Cmds_t::size1, and sio2Cmds_t::size2.
Referenced by padInit().
sio2cmdInitJoystick()
void sio2cmdInitJoystick (void)
Definition at line 593 of file sio2Cmds.c.
 {
         sio2Cmds_t s;
         s.id = PAD_ID_HI( PAD_ID_JOYSTICK );
         s.readdata = &JoystickReadData;
         s.getportctrl1 = &JoystickGetPortCtrl1;
         s.getportctrl2 = &JoystickGetPortCtrl2;
         s.reg_data = &JoystickRegData;
         s.size1 = &JoystickSize1;
         s.size2 = &JoystickSize2;
         s.enterconfigmode = &JoystickEnterConfigMode;
         s.exitconfigmode = NULL;
         s.querymodel = NULL;
         s.queryact = NULL;
         s.querycomb = NULL;
         s.querymode = NULL;
         s.querybuttonmask = NULL;
         s.setbuttoninfo = NULL;
         s.setvrefparam = NULL;
         s.setmainmode = NULL;
         s.setactalign = NULL;
         SetupCmds(&s);
 }
References sio2Cmds_t::enterconfigmode, sio2Cmds_t::exitconfigmode, sio2Cmds_t::getportctrl1, sio2Cmds_t::getportctrl2, sio2Cmds_t::id, JoystickEnterConfigMode(), JoystickGetPortCtrl1(), JoystickGetPortCtrl2(), JoystickReadData(), JoystickRegData(), JoystickSize1(), JoystickSize2(), NULL, PAD_ID_HI, PAD_ID_JOYSTICK, sio2Cmds_t::queryact, sio2Cmds_t::querybuttonmask, sio2Cmds_t::querycomb, sio2Cmds_t::querymode, sio2Cmds_t::querymodel, sio2Cmds_t::readdata, sio2Cmds_t::reg_data, sio2Cmds_t::setactalign, sio2Cmds_t::setbuttoninfo, sio2Cmds_t::setmainmode, SetupCmds(), sio2Cmds_t::setvrefparam, sio2Cmds_t::size1, and sio2Cmds_t::size2.
Referenced by padInit().
sio2cmdInitKonamiGun()
void sio2cmdInitKonamiGun (void)
Definition at line 421 of file sio2Cmds.c.
 {
         sio2Cmds_t s;
         s.id = PAD_ID_HI( PAD_ID_KONAMIGUN );
         s.readdata = &KonamiGunReadData;
         s.getportctrl1 = &KonamiGunGetPortCtrl1;
         s.getportctrl2 = &KonamiGunGetPortCtrl2;
         s.reg_data = &KonamiGunRegData;
         s.size1 = &KonamiGunSize1;
         s.size2 = &KonamiGunSize2;
         s.enterconfigmode = &KonamiGunEnterConfigMode;
         s.exitconfigmode = NULL;
         s.querymodel = NULL;
         s.queryact = NULL;
         s.querycomb = NULL;
         s.querymode = NULL;
         s.querybuttonmask = NULL;
         s.setbuttoninfo = NULL;
         s.setvrefparam = NULL;
         s.setmainmode = NULL;
         s.setactalign = NULL;
         SetupCmds(&s);
 }
References sio2Cmds_t::enterconfigmode, sio2Cmds_t::exitconfigmode, sio2Cmds_t::getportctrl1, sio2Cmds_t::getportctrl2, sio2Cmds_t::id, KonamiGunEnterConfigMode(), KonamiGunGetPortCtrl1(), KonamiGunGetPortCtrl2(), KonamiGunReadData(), KonamiGunRegData(), KonamiGunSize1(), KonamiGunSize2(), NULL, PAD_ID_HI, PAD_ID_KONAMIGUN, sio2Cmds_t::queryact, sio2Cmds_t::querybuttonmask, sio2Cmds_t::querycomb, sio2Cmds_t::querymode, sio2Cmds_t::querymodel, sio2Cmds_t::readdata, sio2Cmds_t::reg_data, sio2Cmds_t::setactalign, sio2Cmds_t::setbuttoninfo, sio2Cmds_t::setmainmode, SetupCmds(), sio2Cmds_t::setvrefparam, sio2Cmds_t::size1, and sio2Cmds_t::size2.
Referenced by padInit().
sio2cmdInitMouse()
void sio2cmdInitMouse (void)
Definition at line 247 of file sio2Cmds.c.
 {
         sio2Cmds_t s;
         s.id = PAD_ID_HI(PAD_ID_MOUSE);
         s.readdata = &MouseReadData;
         s.getportctrl1 = &MouseGetPortCtrl1;
         s.getportctrl2 = &MouseGetPortCtrl2;
         s.reg_data = &MouseRegData;
         s.size1 = &MouseSize1;
         s.size2 = &MouseSize2;
         s.enterconfigmode = &MouseEnterConfigMode;
         s.exitconfigmode = NULL;
         s.querymodel = NULL;
         s.queryact = NULL;
         s.querycomb = NULL;
         s.querymode = NULL;
         s.querybuttonmask = NULL;
         s.setbuttoninfo = NULL;
         s.setvrefparam = NULL;
         s.setmainmode = NULL;
         s.setactalign = NULL;
         SetupCmds(&s);
 }
References sio2Cmds_t::enterconfigmode, sio2Cmds_t::exitconfigmode, sio2Cmds_t::getportctrl1, sio2Cmds_t::getportctrl2, sio2Cmds_t::id, MouseEnterConfigMode(), MouseGetPortCtrl1(), MouseGetPortCtrl2(), MouseReadData(), MouseRegData(), MouseSize1(), MouseSize2(), NULL, PAD_ID_HI, PAD_ID_MOUSE, sio2Cmds_t::queryact, sio2Cmds_t::querybuttonmask, sio2Cmds_t::querycomb, sio2Cmds_t::querymode, sio2Cmds_t::querymodel, sio2Cmds_t::readdata, sio2Cmds_t::reg_data, sio2Cmds_t::setactalign, sio2Cmds_t::setbuttoninfo, sio2Cmds_t::setmainmode, SetupCmds(), sio2Cmds_t::setvrefparam, sio2Cmds_t::size1, and sio2Cmds_t::size2.
Referenced by padInit().
sio2cmdInitNamcoGun()
void sio2cmdInitNamcoGun (void)
Definition at line 683 of file sio2Cmds.c.
 {
         sio2Cmds_t s;
         s.id = PAD_ID_HI(PAD_ID_NAMCOGUN);
         s.readdata = &NamcoGunReadData;
         s.getportctrl1 = &NamcoGunGetPortCtrl1;
         s.getportctrl2 = &NamcoGunGetPortCtrl2;
         s.reg_data = &NamcoGunRegData;
         s.size1 = &NamcoGunSize1;
         s.size2 = &NamcoGunSize2;
         s.enterconfigmode = &NamcoGunEnterConfigMode;
         s.exitconfigmode = NULL;
         s.querymodel = NULL;
         s.queryact = NULL;
         s.querycomb = NULL;
         s.querymode = NULL;
         s.querybuttonmask = NULL;
         s.setbuttoninfo = NULL;
         s.setvrefparam = NULL;
         s.setmainmode = NULL;
         s.setactalign = NULL;
         SetupCmds(&s);
 }
References sio2Cmds_t::enterconfigmode, sio2Cmds_t::exitconfigmode, sio2Cmds_t::getportctrl1, sio2Cmds_t::getportctrl2, sio2Cmds_t::id, NamcoGunEnterConfigMode(), NamcoGunGetPortCtrl1(), NamcoGunGetPortCtrl2(), NamcoGunReadData(), NamcoGunRegData(), NamcoGunSize1(), NamcoGunSize2(), NULL, PAD_ID_HI, PAD_ID_NAMCOGUN, sio2Cmds_t::queryact, sio2Cmds_t::querybuttonmask, sio2Cmds_t::querycomb, sio2Cmds_t::querymode, sio2Cmds_t::querymodel, sio2Cmds_t::readdata, sio2Cmds_t::reg_data, sio2Cmds_t::setactalign, sio2Cmds_t::setbuttoninfo, sio2Cmds_t::setmainmode, SetupCmds(), sio2Cmds_t::setvrefparam, sio2Cmds_t::size1, and sio2Cmds_t::size2.
Referenced by padInit().
sio2cmdInitNegicon()
void sio2cmdInitNegicon (void)
Definition at line 339 of file sio2Cmds.c.
 {
         sio2Cmds_t s;
         s.id = PAD_ID_HI(PAD_ID_NEGICON);
         s.readdata = &NegiconReadData;
         s.getportctrl1 = &NegiconGetPortCtrl1;
         s.getportctrl2 = &NegiconGetPortCtrl2;
         s.reg_data = &NegiconRegData;
         s.size1 = &NegiconSize1;
         s.size2 = &NegiconSize2;
         s.enterconfigmode = &NegiconEnterConfigMode;
         s.exitconfigmode = NULL;
         s.querymodel = NULL;
         s.queryact = NULL;
         s.querycomb = NULL;
         s.querymode = NULL;
         s.querybuttonmask = NULL;
         s.setbuttoninfo = NULL;
         s.setvrefparam = NULL;
         s.setmainmode = NULL;
         s.setactalign = NULL;
         SetupCmds(&s);
 }
References sio2Cmds_t::enterconfigmode, sio2Cmds_t::exitconfigmode, sio2Cmds_t::getportctrl1, sio2Cmds_t::getportctrl2, sio2Cmds_t::id, NegiconEnterConfigMode(), NegiconGetPortCtrl1(), NegiconGetPortCtrl2(), NegiconReadData(), NegiconRegData(), NegiconSize1(), NegiconSize2(), NULL, PAD_ID_HI, PAD_ID_NEGICON, sio2Cmds_t::queryact, sio2Cmds_t::querybuttonmask, sio2Cmds_t::querycomb, sio2Cmds_t::querymode, sio2Cmds_t::querymodel, sio2Cmds_t::readdata, sio2Cmds_t::reg_data, sio2Cmds_t::setactalign, sio2Cmds_t::setbuttoninfo, sio2Cmds_t::setmainmode, SetupCmds(), sio2Cmds_t::setvrefparam, sio2Cmds_t::size1, and sio2Cmds_t::size2.
Referenced by padInit().
sio2cmdReset()
void sio2cmdReset (void)
Definition at line 42 of file sio2Cmds.c.
 {
         int i;
         for(i=0; i < SIO2_CMD_MAX; i++)
                 sio2Cmds[i].id = 0;
         numControllers = 0;
 }
References numControllers, SIO2_CMD_MAX, and sio2Cmds.
Referenced by padInit().
sio2CmdSetEnterConfigMode()
u32 sio2CmdSetEnterConfigMode (u32 id, u8 * buf)
Definition at line 1216 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if(sio2Cmds[i].id == id)
                 {
                         if(sio2Cmds[i].enterconfigmode != NULL)
                                 return sio2Cmds[i].enterconfigmode(buf);
                 }
         }
         return 0;
 }
References sio2Cmds_t::enterconfigmode, NULL, numControllers, PAD_ID_HI, and sio2Cmds.
Referenced by EnterConfigMode().
sio2CmdSetExitConfigMode()
u32 sio2CmdSetExitConfigMode (u32 id, u8 * buf)
Definition at line 1319 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if( sio2Cmds[i].id == id )
                 {
                         if( sio2Cmds[i].exitconfigmode != NULL)
                                 return sio2Cmds[i].exitconfigmode(buf);
                 }
         }
         return 0;
 }
References sio2Cmds_t::exitconfigmode, NULL, numControllers, PAD_ID_HI, and sio2Cmds.
Referenced by ExitConfigMode().
sio2CmdSetQueryAct()
u32 sio2CmdSetQueryAct (u32 id, u8 * buf)
Definition at line 1268 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if( sio2Cmds[i].id == id )
                 {
                         if( sio2Cmds[i].queryact != NULL)
                                 return sio2Cmds[i].queryact(buf);
                 }
         }
         return 0;
 }
References NULL, numControllers, PAD_ID_HI, sio2Cmds_t::queryact, and sio2Cmds.
Referenced by QueryAct().
sio2CmdSetQueryButtonMask()
u32 sio2CmdSetQueryButtonMask (u32 id, u8 * buf)
Definition at line 1353 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if( sio2Cmds[i].id == id )
                 {
                         if( sio2Cmds[i].querybuttonmask != NULL)
                                 return sio2Cmds[i].querybuttonmask(buf);
                 }
         }
         return 0;
 }
References NULL, numControllers, PAD_ID_HI, sio2Cmds_t::querybuttonmask, and sio2Cmds.
Referenced by QueryButtonMask().
sio2CmdSetQueryComb()
u32 sio2CmdSetQueryComb (u32 id, u8 * buf)
Definition at line 1285 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if( sio2Cmds[i].id == id )
                 {
                         if( sio2Cmds[i].querycomb != NULL)
                                 return sio2Cmds[i].querycomb(buf);
                 }
         }
         return 0;
 }
References NULL, numControllers, PAD_ID_HI, sio2Cmds_t::querycomb, and sio2Cmds.
Referenced by QueryComb().
sio2CmdSetQueryMode()
u32 sio2CmdSetQueryMode (u32 id, u8 * buf)
Definition at line 1302 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if( sio2Cmds[i].id == id )
                 {
                         if( sio2Cmds[i].querymode != NULL)
                                 return sio2Cmds[i].querymode(buf);
                 }
         }
         return 0;
 }
References NULL, numControllers, PAD_ID_HI, sio2Cmds_t::querymode, and sio2Cmds.
Referenced by QueryMode().
sio2CmdSetQueryModel()
u32 sio2CmdSetQueryModel (u32 id, u8 * buf)
Definition at line 1234 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if( sio2Cmds[i].id == id )
                 {
                         if( sio2Cmds[i].querymodel != NULL)
                                 return sio2Cmds[i].querymodel(buf);
                 }
         }
         return 0;
 }
References NULL, numControllers, PAD_ID_HI, sio2Cmds_t::querymodel, and sio2Cmds.
Referenced by QueryModel().
sio2CmdSetReadData()
void sio2CmdSetReadData (u32 id, u8 * buf)
Definition at line 1198 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if(sio2Cmds[i].id == id)
                 {
                         if(sio2Cmds[i].readdata != NULL)
{
                                 sio2Cmds[i].readdata(buf);
                                 return;
                         }
                 }
         }
 }
References NULL, numControllers, PAD_ID_HI, sio2Cmds_t::readdata, and sio2Cmds.
Referenced by PadIsSupported(), ReadData(), and setupReadData().
sio2CmdSetSetActAlign()
u32 sio2CmdSetSetActAlign (u32 id, u8 * buf)
Definition at line 1336 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if( sio2Cmds[i].id == id )
                 {
                         if( sio2Cmds[i].setactalign != NULL)
                                 return sio2Cmds[i].setactalign(buf);
                 }
         }
         return 0;
 }
References NULL, numControllers, PAD_ID_HI, sio2Cmds_t::setactalign, and sio2Cmds.
Referenced by SetActAlign().
sio2CmdSetSetButtonInfo()
u32 sio2CmdSetSetButtonInfo (u32 id, u8 * buf)
Definition at line 1388 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if( sio2Cmds[i].id == id )
                 {
                         if( sio2Cmds[i].setbuttoninfo != NULL)
                                 return sio2Cmds[i].setbuttoninfo(buf);
                 }
         }
         return 0;
 }
References NULL, numControllers, PAD_ID_HI, sio2Cmds_t::setbuttoninfo, and sio2Cmds.
Referenced by SetButtonInfo().
sio2CmdSetSetMainMode()
u32 sio2CmdSetSetMainMode (u32 id, u8 * buf)
Definition at line 1251 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if( sio2Cmds[i].id == id )
                 {
                         if( sio2Cmds[i].setmainmode != NULL)
                                 return sio2Cmds[i].setmainmode(buf);
                 }
         }
         return 0;
 }
References NULL, numControllers, PAD_ID_HI, sio2Cmds_t::setmainmode, and sio2Cmds.
Referenced by SetMainMode().
sio2CmdSetSetVrefParam()
u32 sio2CmdSetSetVrefParam (u32 id, u8 * buf)
Definition at line 1370 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if( sio2Cmds[i].id == id )
                 {
                         if( sio2Cmds[i].setvrefparam != NULL)
                                 return sio2Cmds[i].setvrefparam(buf);
                 }
         }
         return 0;
 }
References NULL, numControllers, PAD_ID_HI, sio2Cmds_t::setvrefparam, and sio2Cmds.
Referenced by VrefParam().