ps2sdk: iop/system/sio2man/include/sio2man.h File Reference
sio2man.h File Reference
#include <types.h>
#include <irx.h>
Data Structures
struct _sio2_dma_arg
struct sio2_transfer_data_t
Macros
#define sio2man_IMPORTS_start DECLARE_IMPORT_TABLE(sio2man, 1, 1)
#define sio2man_IMPORTS_end END_IMPORT_TABLE
#define I_sio2_ctrl_set DECLARE_IMPORT(4, sio2_ctrl_set)
#define I_sio2_ctrl_get DECLARE_IMPORT(5, sio2_ctrl_get)
#define I_sio2_stat6c_get DECLARE_IMPORT(6, sio2_stat6c_get)
#define I_sio2_portN_ctrl1_set DECLARE_IMPORT(7, sio2_portN_ctrl1_set)
#define I_sio2_portN_ctrl1_get DECLARE_IMPORT(8, sio2_portN_ctrl1_get)
#define I_sio2_portN_ctrl2_set DECLARE_IMPORT(9, sio2_portN_ctrl2_set)
#define I_sio2_portN_ctrl2_get DECLARE_IMPORT(10, sio2_portN_ctrl2_get)
#define I_sio2_stat70_get DECLARE_IMPORT(11, sio2_stat70_get)
#define I_sio2_regN_set DECLARE_IMPORT(12, sio2_regN_set)
#define I_sio2_regN_get DECLARE_IMPORT(13, sio2_regN_get)
#define I_sio2_stat74_get DECLARE_IMPORT(14, sio2_stat74_get)
#define I_sio2_unkn78_set DECLARE_IMPORT(15, sio2_unkn78_set)
#define I_sio2_unkn78_get DECLARE_IMPORT(16, sio2_unkn78_get)
#define I_sio2_unkn7c_set DECLARE_IMPORT(17, sio2_unkn7c_set)
#define I_sio2_unkn7c_get DECLARE_IMPORT(18, sio2_unkn7c_get)
#define I_sio2_data_out DECLARE_IMPORT(19, sio2_data_out)
#define I_sio2_data_in DECLARE_IMPORT(20, sio2_data_in)
#define I_sio2_stat_set DECLARE_IMPORT(21, sio2_stat_set)
#define I_sio2_stat_get DECLARE_IMPORT(22, sio2_stat_get)
#define I_sio2_pad_transfer_init DECLARE_IMPORT(23, sio2_pad_transfer_init)
#define I_sio2_mc_transfer_init DECLARE_IMPORT(24, sio2_mc_transfer_init)
#define I_sio2_transfer DECLARE_IMPORT(25, sio2_transfer)
Functions
void sio2_ctrl_set (u32 val)
u32 sio2_ctrl_get (void)
u32 sio2_stat6c_get (void)
void sio2_portN_ctrl1_set (int N, u32 val)
u32 sio2_portN_ctrl1_get (int N)
void sio2_portN_ctrl2_set (int N, u32 val)
u32 sio2_portN_ctrl2_get (int N)
u32 sio2_stat70_get (void)
void sio2_regN_set (int N, u32 val)
u32 sio2_regN_get (int N)
u32 sio2_stat74_get (void)
void sio2_unkn78_set (u32 val)
u32 sio2_unkn78_get (void)
void sio2_unkn7c_set (u32 val)
u32 sio2_unkn7c_get (void)
void sio2_data_out (u8 val)
u8 sio2_data_in (void)
void sio2_stat_set (u32 val)
u32 sio2_stat_get (void)
void sio2_pad_transfer_init (void)
void sio2_mc_transfer_init (void)
int sio2_transfer (sio2_transfer_data_t *td)
Detailed Description
rom0:SIO2MAN module definitions
Definition in file sio2man.h.
Macro Definition Documentation
I_sio2_ctrl_get
#define I_sio2_ctrl_get DECLARE_IMPORT(5, sio2_ctrl_get)
Definition at line 76 of file sio2man.h.
I_sio2_ctrl_set
#define I_sio2_ctrl_set DECLARE_IMPORT(4, sio2_ctrl_set)
Definition at line 75 of file sio2man.h.
I_sio2_data_in
#define I_sio2_data_in DECLARE_IMPORT(20, sio2_data_in)
Definition at line 91 of file sio2man.h.
I_sio2_data_out
#define I_sio2_data_out DECLARE_IMPORT(19, sio2_data_out)
Definition at line 90 of file sio2man.h.
I_sio2_mc_transfer_init
#define I_sio2_mc_transfer_init DECLARE_IMPORT(24, sio2_mc_transfer_init)
Definition at line 95 of file sio2man.h.
I_sio2_pad_transfer_init
#define I_sio2_pad_transfer_init DECLARE_IMPORT(23, sio2_pad_transfer_init)
Definition at line 94 of file sio2man.h.
I_sio2_portN_ctrl1_get
#define I_sio2_portN_ctrl1_get DECLARE_IMPORT(8, sio2_portN_ctrl1_get)
Definition at line 79 of file sio2man.h.
I_sio2_portN_ctrl1_set
#define I_sio2_portN_ctrl1_set DECLARE_IMPORT(7, sio2_portN_ctrl1_set)
Definition at line 78 of file sio2man.h.
I_sio2_portN_ctrl2_get
#define I_sio2_portN_ctrl2_get DECLARE_IMPORT(10, sio2_portN_ctrl2_get)
Definition at line 81 of file sio2man.h.
I_sio2_portN_ctrl2_set
#define I_sio2_portN_ctrl2_set DECLARE_IMPORT(9, sio2_portN_ctrl2_set)
Definition at line 80 of file sio2man.h.
I_sio2_regN_get
#define I_sio2_regN_get DECLARE_IMPORT(13, sio2_regN_get)
Definition at line 84 of file sio2man.h.
I_sio2_regN_set
#define I_sio2_regN_set DECLARE_IMPORT(12, sio2_regN_set)
Definition at line 83 of file sio2man.h.
I_sio2_stat6c_get
#define I_sio2_stat6c_get DECLARE_IMPORT(6, sio2_stat6c_get)
Definition at line 77 of file sio2man.h.
I_sio2_stat70_get
#define I_sio2_stat70_get DECLARE_IMPORT(11, sio2_stat70_get)
Definition at line 82 of file sio2man.h.
I_sio2_stat74_get
#define I_sio2_stat74_get DECLARE_IMPORT(14, sio2_stat74_get)
Definition at line 85 of file sio2man.h.
I_sio2_stat_get
#define I_sio2_stat_get DECLARE_IMPORT(22, sio2_stat_get)
Definition at line 93 of file sio2man.h.
I_sio2_stat_set
#define I_sio2_stat_set DECLARE_IMPORT(21, sio2_stat_set)
Definition at line 92 of file sio2man.h.
I_sio2_transfer
#define I_sio2_transfer DECLARE_IMPORT(25, sio2_transfer)
Definition at line 96 of file sio2man.h.
I_sio2_unkn78_get
#define I_sio2_unkn78_get DECLARE_IMPORT(16, sio2_unkn78_get)
Definition at line 87 of file sio2man.h.
I_sio2_unkn78_set
#define I_sio2_unkn78_set DECLARE_IMPORT(15, sio2_unkn78_set)
Definition at line 86 of file sio2man.h.
I_sio2_unkn7c_get
#define I_sio2_unkn7c_get DECLARE_IMPORT(18, sio2_unkn7c_get)
Definition at line 89 of file sio2man.h.
I_sio2_unkn7c_set
#define I_sio2_unkn7c_set DECLARE_IMPORT(17, sio2_unkn7c_set)
Definition at line 88 of file sio2man.h.
sio2man_IMPORTS_end
#define sio2man_IMPORTS_end END_IMPORT_TABLE
Definition at line 73 of file sio2man.h.
sio2man_IMPORTS_start
#define sio2man_IMPORTS_start DECLARE_IMPORT_TABLE(sio2man, 1, 1)
Definition at line 72 of file sio2man.h.
Function Documentation
sio2_ctrl_get()
u32 sio2_ctrl_get (void)
Definition at line 443 of file sio2man.c.
 { return _lw(SIO2_REG_CTRL); }
References _lw(), and SIO2_REG_CTRL.
Referenced by main_thread().
sio2_ctrl_set()
void sio2_ctrl_set (u32 val)
Definition at line 442 of file sio2man.c.
 { _sw(val, SIO2_REG_CTRL); }
References _sw(), and SIO2_REG_CTRL.
Referenced by _start(), and main_thread().
sio2_data_in()
u8 sio2_data_in (void)
Definition at line 458 of file sio2man.c.
 { return _lb(SIO2_REG_DATA_IN); }
References _lb(), and SIO2_REG_DATA_IN.
Referenced by recv_td().
sio2_data_out()
void sio2_data_out (u8 val)
Definition at line 457 of file sio2man.c.
 { _sb(val, SIO2_REG_DATA_OUT); }
References _sb(), and SIO2_REG_DATA_OUT.
Referenced by send_td().
sio2_mc_transfer_init()
void sio2_mc_transfer_init (void)
Definition at line 347 of file sio2man.c.
 {
         SetEventFlag(event_flag, EF_MC_TRANSFER_INIT);
         WaitEventFlag(event_flag, EF_MC_TRANSFER_READY, 0, NULL);
         ClearEventFlag(event_flag, ~EF_MC_TRANSFER_READY);
 }
References ClearEventFlag(), EF_MC_TRANSFER_INIT, EF_MC_TRANSFER_READY, event_flag, NULL, SetEventFlag(), and WaitEventFlag().
sio2_pad_transfer_init()
void sio2_pad_transfer_init (void)
Definition at line 339 of file sio2man.c.
 {
         SetEventFlag(event_flag, EF_PAD_TRANSFER_INIT);
         WaitEventFlag(event_flag, EF_PAD_TRANSFER_READY, 0, NULL);
         ClearEventFlag(event_flag, ~EF_PAD_TRANSFER_READY);
 }
References ClearEventFlag(), EF_PAD_TRANSFER_INIT, EF_PAD_TRANSFER_READY, event_flag, NULL, SetEventFlag(), and WaitEventFlag().
Referenced by pdCheckConnection(), and pdTransfer().
sio2_portN_ctrl1_get()
u32 sio2_portN_ctrl1_get (int N)
Definition at line 446 of file sio2man.c.
 { return _lw(SIO2_REG_PORT0_CTRL1 + (N * 8)); }
References _lw(), and SIO2_REG_PORT0_CTRL1.
sio2_portN_ctrl1_set()
void sio2_portN_ctrl1_set (int N, u32 val)
Definition at line 445 of file sio2man.c.
 { _sw(val, SIO2_REG_PORT0_CTRL1 + (N * 8)); }
References _sw(), and SIO2_REG_PORT0_CTRL1.
Referenced by send_td().
sio2_portN_ctrl2_get()
u32 sio2_portN_ctrl2_get (int N)
Definition at line 448 of file sio2man.c.
 { return _lw(SIO2_REG_PORT0_CTRL2 + (N * 8)); }
References _lw(), and SIO2_REG_PORT0_CTRL2.
sio2_portN_ctrl2_set()
void sio2_portN_ctrl2_set (int N, u32 val)
Definition at line 447 of file sio2man.c.
 { _sw(val, SIO2_REG_PORT0_CTRL2 + (N * 8)); }
References _sw(), and SIO2_REG_PORT0_CTRL2.
Referenced by send_td().
sio2_regN_get()
u32 sio2_regN_get (int N)
Definition at line 451 of file sio2man.c.
 { return _lw(SIO2_REG_BASE + (N * 4)); }
References _lw(), and SIO2_REG_BASE.
sio2_regN_set()
void sio2_regN_set (int N, u32 val)
Definition at line 450 of file sio2man.c.
 { _sw(val, SIO2_REG_BASE + (N * 4)); }
References _sw(), and SIO2_REG_BASE.
Referenced by send_td().
sio2_stat6c_get()
u32 sio2_stat6c_get (void)
Definition at line 444 of file sio2man.c.
 { return _lw(SIO2_REG_STAT6C); }
References _lw(), and SIO2_REG_STAT6C.
Referenced by recv_td().
sio2_stat70_get()
u32 sio2_stat70_get (void)
Definition at line 449 of file sio2man.c.
 { return _lw(SIO2_REG_STAT70); }
References _lw(), and SIO2_REG_STAT70.
Referenced by padTransfer(), recv_td(), and SlotCheckConnection().
sio2_stat74_get()
u32 sio2_stat74_get (void)
Definition at line 452 of file sio2man.c.
 { return _lw(SIO2_REG_STAT74); }
References _lw(), and SIO2_REG_STAT74.
Referenced by recv_td().
sio2_stat_get()
u32 sio2_stat_get (void)
Definition at line 460 of file sio2man.c.
 { return _lw(SIO2_REG_STAT); }
References _lw(), and SIO2_REG_STAT.
Referenced by sio2_intr_handler().
sio2_stat_set()
void sio2_stat_set (u32 val)
Definition at line 459 of file sio2man.c.
 { _sw(val, SIO2_REG_STAT); }
References _sw(), and SIO2_REG_STAT.
Referenced by sio2_intr_handler().
sio2_transfer()
int sio2_transfer (sio2_transfer_data_t * td)
Definition at line 363 of file sio2man.c.
 {
         transfer_data = td;
         SetEventFlag(event_flag, EF_TRANSFER_START);
         WaitEventFlag(event_flag, EF_TRANSFER_FINISH, 0, NULL);
         ClearEventFlag(event_flag, ~EF_TRANSFER_FINISH);
         return 1;
 }
References ClearEventFlag(), EF_TRANSFER_FINISH, EF_TRANSFER_START, event_flag, NULL, SetEventFlag(), td, transfer_data, and WaitEventFlag().
Referenced by RmExecute().
sio2_unkn78_get()
u32 sio2_unkn78_get (void)
Definition at line 454 of file sio2man.c.
 { return _lw(SIO2_REG_UNKN78); }
References _lw(), and SIO2_REG_UNKN78.
sio2_unkn78_set()
void sio2_unkn78_set (u32 val)
Definition at line 453 of file sio2man.c.
 { _sw(val, SIO2_REG_UNKN78); }
References _sw(), and SIO2_REG_UNKN78.
sio2_unkn7c_get()
u32 sio2_unkn7c_get (void)
Definition at line 456 of file sio2man.c.
 { return _lw(SIO2_REG_UNKN7C); }
References _lw(), and SIO2_REG_UNKN7C.
sio2_unkn7c_set()
void sio2_unkn7c_set (u32 val)
Definition at line 455 of file sio2man.c.
 { _sw(val, SIO2_REG_UNKN7C); }
References _sw(), and SIO2_REG_UNKN7C.