ps2sdk: iop/system/padman/src/sio2Cmds.c File Reference
sio2Cmds.c File Reference
#include "irx.h"
#include "types.h"
#include "sio2Cmds.h"
Data Structures
struct sio2Cmds_t
Functions
void sio2cmdReset (void)
static int SetupCmds (const sio2Cmds_t *s)
static void FindPadsReadData (u8 *a)
static u32 FindPadsGetPortCtrl1 (u32 a, u32 b)
static u32 FindPadsGetPortCtrl2 (u32 a)
static u32 FindPadsGetSize1 (void)
static u32 FindPadsGetSize2 (void)
static u32 FindPadsRegData (void)
static u32 FindPadsEnterConfigMode (u8 *a)
void sio2cmdInitFindPads (void)
static void MouseReadData (u8 *a)
static u32 MouseGetPortCtrl1 (u32 a, u32 b)
static u32 MouseGetPortCtrl2 (u32 a)
static u32 MouseRegData (void)
static u32 MouseSize1 (void)
static u32 MouseSize2 (void)
static u32 MouseEnterConfigMode (u8 *a)
void sio2cmdInitMouse (void)
static void NegiconReadData (u8 *a)
static u32 NegiconGetPortCtrl1 (u32 a, u32 b)
static u32 NegiconGetPortCtrl2 (u32 a)
static u32 NegiconRegData (void)
static u32 NegiconSize1 (void)
static u32 NegiconSize2 (void)
static u32 NegiconEnterConfigMode (u8 *a)
void sio2cmdInitNegicon (void)
static void KonamiGunReadData (u8 *a)
static u32 KonamiGunGetPortCtrl1 (u32 a, u32 b)
static u32 KonamiGunGetPortCtrl2 (u32 a)
static u32 KonamiGunRegData (void)
static u32 KonamiGunSize1 (void)
static u32 KonamiGunSize2 (void)
static u32 KonamiGunEnterConfigMode (u8 *a)
void sio2cmdInitKonamiGun (void)
static void DigitalReadData (u8 *a)
static u32 DigitalGetPortCtrl1 (u32 a, u32 b)
static u32 DigitalGetPortCtrl2 (u32 a)
static u32 DigitalRegData (void)
static u32 DigitalSize1 (void)
static u32 DigitalSize2 (void)
static u32 DigitalEnterConfigMode (u8 *a)
void sio2cmdInitDigital (void)
static void JoystickReadData (u8 *a)
static u32 JoystickGetPortCtrl1 (u32 a, u32 b)
static u32 JoystickGetPortCtrl2 (u32 a)
static u32 JoystickRegData (void)
static u32 JoystickSize1 (void)
static u32 JoystickSize2 (void)
static u32 JoystickEnterConfigMode (u8 *a)
void sio2cmdInitJoystick (void)
static void NamcoGunReadData (u8 *a)
static u32 NamcoGunGetPortCtrl1 (u32 a, u32 b)
static u32 NamcoGunGetPortCtrl2 (u32 a)
static u32 NamcoGunRegData (void)
static u32 NamcoGunSize1 (void)
static u32 NamcoGunSize2 (void)
static u32 NamcoGunEnterConfigMode (u8 *a)
void sio2cmdInitNamcoGun (void)
static void AnalogReadData (u8 *a)
static u32 AnalogGetPortCtrl1 (u32 a, u32 b)
static u32 AnalogGetPortCtrl2 (u32 a)
static u32 AnalogEnterConfigMode (u8 *a)
void sio2cmdInitAnalog (void)
static void JogconReadData (u8 *a)
static u32 JogconGetPortCtrl1 (u32 a, u32 b)
static u32 JogconGetPortCtrl2 (u32 a)
static u32 JogconRegData (void)
static u32 JogconSize1 (void)
static u32 JogconSize2 (void)
static u32 JogconEnterConfigMode (u8 *a)
void sio2cmdInitJogcon (void)
static void ConfigReadData (u8 *a)
static u32 ConfigGetPortCtrl1 (u32 a, u32 b)
static u32 ConfigGetPortCtrl2 (u32 a)
static u32 ConfigRegData (void)
static u32 ConfigSize1 (void)
static u32 ConfigSize2 (void)
static u32 ConfigExitConfigMode (u8 *a)
static u32 ConfigQueryModel (u8 *a)
static u32 ConfigQueryAct (u8 *a)
static u32 ConfigQueryComb (u8 *a)
static u32 ConfigQueryMode (u8 *a)
static u32 ConfigQueryButtonMask (u8 *a)
static u32 ConfigSetButtonInfo (u8 *a)
static u32 ConfigSetVrefParam (u8 *a)
static u32 ConfigSetMainMode (u8 *a)
static u32 ConfigSetSetActAlign (u8 *a)
void sio2cmdInitConfig (void)
u32 sio2cmdCheckId (u8 id)
u32 sio2CmdGetPortCtrl1 (u8 id, u32 b, u8 c)
u32 sio2CmdGetPortCtrl2 (u32 id, u32 b)
void sio2CmdSetReadData (u32 id, u8 *buf)
u32 sio2CmdSetEnterConfigMode (u32 id, u8 *buf)
u32 sio2CmdSetQueryModel (u32 id, u8 *buf)
u32 sio2CmdSetSetMainMode (u32 id, u8 *buf)
u32 sio2CmdSetQueryAct (u32 id, u8 *buf)
u32 sio2CmdSetQueryComb (u32 id, u8 *buf)
u32 sio2CmdSetQueryMode (u32 id, u8 *buf)
u32 sio2CmdSetExitConfigMode (u32 id, u8 *buf)
u32 sio2CmdSetSetActAlign (u32 id, u8 *buf)
u32 sio2CmdSetQueryButtonMask (u32 id, u8 *buf)
u32 sio2CmdSetSetVrefParam (u32 id, u8 *buf)
u32 sio2CmdSetSetButtonInfo (u32 id, u8 *buf)
Variables
static sio2Cmds_t sio2Cmds [SIO2_CMD_MAX]
static int numControllers
Detailed Description
IOP pad driver
Definition in file sio2Cmds.c.
Function Documentation
AnalogEnterConfigMode()
static u32 AnalogEnterConfigMode (u8 * a) static
Definition at line 775 of file sio2Cmds.c.
 {
         a[0] = 0x1;
         a[1] = 0x43;
         a[2] = 0;
         a[3] = 0x1;
         a[4] = 0;
         a[5] = 0;
         a[6] = 0;
         a[7] = 0;
         a[8] = 0;
         a[9] = 0;
         a[10] = 0;
         a[11] = 0;
         a[12] = 0;
         a[13] = 0;
         a[14] = 0;
         return 0x15;
 }
Referenced by sio2cmdInitAnalog().
AnalogGetPortCtrl1()
static u32 AnalogGetPortCtrl1 (u32 a, u32 b) static
Definition at line 733 of file sio2Cmds.c.
 {
         if(a != 0)
                 return 0xFF060505;
         else
         {
                 u32 val1, val2, val3 ;
                 if((b & 0x2) == 0)
                         val1 = 0x5;
                 else
                         val1 = 0xA;
                 if((b & 0x2) == 0)
                         val2 = 0x5;
                 else
                         val2 = 0xA;
                 val1 &= 0xFFFF00FF;
                 val3 = val1 | ( val2 << 8);
                 if((b & 0x2) == 0)
                         val1 = 0xC0;
                 else
                         val1 = 0x60;
                 val3 &= 0xFF00FFFF;
                 val3 = val3 | (val1 << 16) | 0xFF000000;
                 return val3;
         }
 }
Referenced by sio2cmdInitAnalog().
AnalogGetPortCtrl2()
static u32 AnalogGetPortCtrl2 (u32 a) static
Definition at line 767 of file sio2Cmds.c.
 {
         if(a == 0)
                 return 0x20014;
         else
                 return 0x2012C;
 }
Referenced by sio2cmdInitAnalog().
AnalogReadData()
static void AnalogReadData (u8 * a) static
Definition at line 714 of file sio2Cmds.c.
 {
         a[0] = 1;
         a[1] = 0x42;
         a[2] = 0;
         a[3] = 0;
         a[4] = 0;
         a[5] = 0;
         a[6] = 0;
         a[7] = 0;
         a[8] = 0;
         a[9] = 0;
         a[10] = 0;
         a[11] = 0;
         a[12] = 0;
         a[13] = 0;
         a[14] = 0;
 }
Referenced by sio2cmdInitAnalog().
ConfigExitConfigMode()
static u32 ConfigExitConfigMode (u8 * a) static
Definition at line 969 of file sio2Cmds.c.
 {
         a[0] = 1;
         a[1] = 0x43;
         a[2] = 0x0;
         a[3] = 0x0;
         a[4] = 0x5a;
         a[5] = 0x5a;
         a[6] = 0x5a;
         a[7] = 0x5a;
         a[8] = 0x5a;
         return 9;
 }
Referenced by sio2cmdInitConfig().
ConfigGetPortCtrl1()
static u32 ConfigGetPortCtrl1 (u32 a, u32 b) static
Definition at line 938 of file sio2Cmds.c.
 {
         if(a == 0)
                 return 0xFFC00505;
         else
                 return 0xFF060505;
 }
Referenced by sio2cmdInitConfig().
ConfigGetPortCtrl2()
static u32 ConfigGetPortCtrl2 (u32 a) static
Definition at line 946 of file sio2Cmds.c.
 {
         if(a == 0)
                 return 0x20014;
         else
                 return 0x2012C;
 }
Referenced by sio2cmdInitConfig().
ConfigQueryAct()
static u32 ConfigQueryAct (u8 * a) static
Definition at line 999 of file sio2Cmds.c.
 {
         a[0] = 1;
         a[1] = 0x46;
         a[2] = 0x0;
         a[3] = 0x0;
         a[4] = 0x5a;
         a[5] = 0x5a;
         a[6] = 0x5a;
         a[7] = 0x5a;
         a[8] = 0x5a;
         return 9;
 }
Referenced by sio2cmdInitConfig().
ConfigQueryButtonMask()
static u32 ConfigQueryButtonMask (u8 * a) static
Definition at line 1044 of file sio2Cmds.c.
 {
         a[0] = 1;
         a[1] = 0x41;
         a[2] = 0x0;
         a[3] = 0x5a;
         a[4] = 0x5a;
         a[5] = 0x5a;
         a[6] = 0x5a;
         a[7] = 0x5a;
         a[8] = 0x5a;
         return 9;
 }
Referenced by sio2cmdInitConfig().
ConfigQueryComb()
static u32 ConfigQueryComb (u8 * a) static
Definition at line 1014 of file sio2Cmds.c.
 {
         a[0] = 1;
         a[1] = 0x47;
         a[2] = 0x0;
         a[3] = 0x0;
         a[4] = 0x5a;
         a[5] = 0x5a;
         a[6] = 0x5a;
         a[7] = 0x5a;
         a[8] = 0x5a;
         return 9;
 }
Referenced by sio2cmdInitConfig().
ConfigQueryMode()
static u32 ConfigQueryMode (u8 * a) static
Definition at line 1029 of file sio2Cmds.c.
 {
         a[0] = 1;
         a[1] = 0x4c;
         a[2] = 0x0;
         a[3] = 0x0;
         a[4] = 0x5a;
         a[5] = 0x5a;
         a[6] = 0x5a;
         a[7] = 0x5a;
         a[8] = 0x5a;
         return 9;
 }
Referenced by sio2cmdInitConfig().
ConfigQueryModel()
static u32 ConfigQueryModel (u8 * a) static
Definition at line 984 of file sio2Cmds.c.
 {
         a[0] = 1;
         a[1] = 0x45;
         a[2] = 0x0;
         a[3] = 0x5a;
         a[4] = 0x5a;
         a[5] = 0x5a;
         a[6] = 0x5a;
         a[7] = 0x5a;
         a[8] = 0x5a;
         return 9;
 }
Referenced by sio2cmdInitConfig().
ConfigReadData()
static void ConfigReadData (u8 * a) static
Definition at line 925 of file sio2Cmds.c.
 {
         a[0] = 1;
         a[1] = 0x42;
         a[2] = 0;
         a[3] = 0x5A;
         a[4] = 0x5A;
         a[5] = 0x5A;
         a[6] = 0x5A;
         a[7] = 0x5A;
         a[8] = 0x5A;
 }
Referenced by sio2cmdInitConfig().
ConfigRegData()
static u32 ConfigRegData (void) static
Definition at line 954 of file sio2Cmds.c.
 {
         return 0x240940;
 }
Referenced by sio2cmdInitConfig().
ConfigSetButtonInfo()
static u32 ConfigSetButtonInfo (u8 * a) static
Definition at line 1059 of file sio2Cmds.c.
 {
         a[0] = 1;
         a[1] = 0x4F;
         a[2] = 0x0;
         a[3] = 0x0;
         a[4] = 0x0;
         a[5] = 0x0;
         a[6] = 0x0;
         a[7] = 0x0;
         a[8] = 0x0;
         return 9;
 }
Referenced by sio2cmdInitConfig().
ConfigSetMainMode()
static u32 ConfigSetMainMode (u8 * a) static
Definition at line 1089 of file sio2Cmds.c.
 {
         a[0] = 1;
         a[1] = 0x44;
         a[2] = 0x0;
         a[3] = 0x0;
         a[4] = 0x0;
         a[5] = 0x0;
         a[6] = 0x0;
         a[7] = 0x0;
         a[8] = 0x0;
         return 9;
 }
Referenced by sio2cmdInitConfig().
ConfigSetSetActAlign()
static u32 ConfigSetSetActAlign (u8 * a) static
Definition at line 1104 of file sio2Cmds.c.
 {
         a[0] = 1;
         a[1] = 0x4d;
         a[2] = 0x0;
         a[3] = 0x0;
         a[4] = 0x0;
         a[5] = 0x0;
         a[6] = 0x0;
         a[7] = 0x0;
         a[8] = 0x0;
         return 9;
 }
Referenced by sio2cmdInitConfig().
ConfigSetVrefParam()
static u32 ConfigSetVrefParam (u8 * a) static
Definition at line 1074 of file sio2Cmds.c.
 {
         a[0] = 1;
         a[1] = 0x40;
         a[2] = 0x0;
         a[3] = 0x0;
         a[4] = 0x0;
         a[5] = 0x0;
         a[6] = 0x0;
         a[7] = 0x0;
         a[8] = 0x0;
         return 9;
 }
Referenced by sio2cmdInitConfig().
ConfigSize1()
static u32 ConfigSize1 (void) static
Definition at line 959 of file sio2Cmds.c.
 {
         return 0x9;
 }
Referenced by sio2cmdInitConfig().
ConfigSize2()
static u32 ConfigSize2 (void) static
Definition at line 964 of file sio2Cmds.c.
 {
         return 0x9;
 }
Referenced by sio2cmdInitConfig().
DigitalEnterConfigMode()
static u32 DigitalEnterConfigMode (u8 * a) static
Definition at line 492 of file sio2Cmds.c.
 {
         a[0] = 0x1;
         a[1] = 0x43;
         a[2] = 0;
         a[3] = 0x1;
         a[4] = 0;
         return 0x5;
 }
Referenced by sio2cmdInitDigital().
DigitalGetPortCtrl1()
static u32 DigitalGetPortCtrl1 (u32 a, u32 b) static
Definition at line 461 of file sio2Cmds.c.
 {
         if(a == 0)
                 return 0xFFC00505;
         else
                 return 0xFF060505;
 }
Referenced by sio2cmdInitDigital().
DigitalGetPortCtrl2()
static u32 DigitalGetPortCtrl2 (u32 a) static
Definition at line 469 of file sio2Cmds.c.
 {
         if(a == 0)
                 return 0x20014;
         else
                 return 0x2012C;
 }
Referenced by sio2cmdInitDigital().
DigitalReadData()
static void DigitalReadData (u8 * a) static
Definition at line 452 of file sio2Cmds.c.
 {
         a[0] = 1;
         a[1] = 0x42;
         a[2] = 0;
         a[3] = 0;
         a[4] = 0;
 }
Referenced by sio2cmdInitDigital().
DigitalRegData()
static u32 DigitalRegData (void) static
Definition at line 477 of file sio2Cmds.c.
 {
         return 0x140540;
 }
Referenced by sio2cmdInitDigital().
DigitalSize1()
static u32 DigitalSize1 (void) static
Definition at line 482 of file sio2Cmds.c.
 {
         return 0x5;
 }
Referenced by sio2cmdInitDigital().
DigitalSize2()
static u32 DigitalSize2 (void) static
Definition at line 487 of file sio2Cmds.c.
 {
         return 0x5;
 }
Referenced by sio2cmdInitDigital().
FindPadsEnterConfigMode()
static u32 FindPadsEnterConfigMode (u8 * a) static
Definition at line 156 of file sio2Cmds.c.
 {
         return 0;
 }
Referenced by sio2cmdInitFindPads().
FindPadsGetPortCtrl1()
static u32 FindPadsGetPortCtrl1 (u32 a, u32 b) static
Definition at line 115 of file sio2Cmds.c.
 {
         if(a == 0)
                 return 0xFFC00505;
         else
                 return 0xFF060505;
 }
Referenced by sio2cmdInitFindPads().
FindPadsGetPortCtrl2()
static u32 FindPadsGetPortCtrl2 (u32 a) static
Definition at line 123 of file sio2Cmds.c.
 {
         if(a == 0)
                 return 0x2000A;
         else
                 return 0x2012C;
 }
Referenced by sio2cmdInitFindPads().
FindPadsGetSize1()
static u32 FindPadsGetSize1 (void) static
Definition at line 131 of file sio2Cmds.c.
 {
         return 0x5;
 }
Referenced by FindPadsRegData(), and sio2cmdInitFindPads().
FindPadsGetSize2()
static u32 FindPadsGetSize2 (void) static
Definition at line 136 of file sio2Cmds.c.
 {
         return 0x5;
 }
Referenced by FindPadsRegData(), and sio2cmdInitFindPads().
FindPadsReadData()
static void FindPadsReadData (u8 * a) static
Definition at line 106 of file sio2Cmds.c.
 {
         a[0] = 1;
         a[1] = 0x42;
         a[2] = 0;
         a[3] = 0;
         a[4] = 0;
 }
Referenced by sio2cmdInitFindPads().
FindPadsRegData()
static u32 FindPadsRegData (void) static
Definition at line 141 of file sio2Cmds.c.
 {
         u32 res1, res2;
         res1 = FindPadsGetSize1();
         res1 = ((res1 & 0x1FF) << 8) | 0x40;
         res2 = FindPadsGetSize2();
         res2 = (res2 & 0x1FF) << 18;
         return (res1 | res2);
 }
References FindPadsGetSize1(), and FindPadsGetSize2().
Referenced by sio2cmdInitFindPads().
JogconEnterConfigMode()
static u32 JogconEnterConfigMode (u8 * a) static
Definition at line 875 of file sio2Cmds.c.
 {
         a[0] = 0x1;
         a[1] = 0x43;
         a[2] = 0;
         a[3] = 0x1;
         a[4] = 0;
         a[5] = 0;
         a[6] = 0;
         a[7] = 0;
         a[8] = 0;
         a[9] = 0;
         a[10] = 0;
         a[11] = 0;
         a[12] = 0;
         return 0xD;
 }
Referenced by sio2cmdInitJogcon().
JogconGetPortCtrl1()
static u32 JogconGetPortCtrl1 (u32 a, u32 b) static
Definition at line 844 of file sio2Cmds.c.
 {
         if(a == 0)
                 return 0xFFC00505;
         else
                 return 0xFF060505;
 }
Referenced by sio2cmdInitJogcon().
JogconGetPortCtrl2()
static u32 JogconGetPortCtrl2 (u32 a) static
Definition at line 852 of file sio2Cmds.c.
 {
         if(a == 0)
                 return 0x20014;
         else
                 return 0x2012C;
 }
Referenced by sio2cmdInitJogcon().
JogconReadData()
static void JogconReadData (u8 * a) static
Definition at line 827 of file sio2Cmds.c.
 {
         a[0] = 1;
         a[1] = 0x42;
         a[2] = 0;
         a[3] = 0;
         a[4] = 0;
         a[5] = 0;
         a[6] = 0;
         a[7] = 0;
         a[8] = 0;
         a[9] = 0;
         a[10] = 0;
         a[11] = 0;
         a[12] = 0;
 }
Referenced by sio2cmdInitJogcon().
JogconRegData()
static u32 JogconRegData (void) static
Definition at line 860 of file sio2Cmds.c.
 {
         return 0x340d40;
 }
Referenced by sio2cmdInitJogcon().
JogconSize1()
static u32 JogconSize1 (void) static
Definition at line 865 of file sio2Cmds.c.
 {
         return 0xD;
 }
Referenced by sio2cmdInitJogcon().
JogconSize2()
static u32 JogconSize2 (void) static
Definition at line 870 of file sio2Cmds.c.
 {
         return 0xD;
 }
Referenced by sio2cmdInitJogcon().
JoystickEnterConfigMode()
static u32 JoystickEnterConfigMode (u8 * a) static
Definition at line 578 of file sio2Cmds.c.
 {
         a[0] = 0x1;
         a[1] = 0x43;
         a[2] = 0;
         a[3] = 0x1;
         a[4] = 0;
         a[5] = 0;
         a[6] = 0;
         a[7] = 0;
         a[8] = 0;
         return 0x9;
 }
Referenced by sio2cmdInitJoystick().
JoystickGetPortCtrl1()
static u32 JoystickGetPortCtrl1 (u32 a, u32 b) static
Definition at line 547 of file sio2Cmds.c.
 {
         if(a == 0)
                 return 0xFFC00505;
         else
                 return 0xFF060505;
 }
Referenced by sio2cmdInitJoystick().
JoystickGetPortCtrl2()
static u32 JoystickGetPortCtrl2 (u32 a) static
Definition at line 555 of file sio2Cmds.c.
 {
         if(a == 0)
                 return 0x20014;
         else
                 return 0x2012C;
 }
Referenced by sio2cmdInitJoystick().
JoystickReadData()
static void JoystickReadData (u8 * a) static
Definition at line 534 of file sio2Cmds.c.
 {
         a[0] = 1;
         a[1] = 0x42;
         a[2] = 0;
         a[3] = 0;
         a[4] = 0;
         a[5] = 0;
         a[6] = 0;
         a[7] = 0;
         a[8] = 0;
 }
Referenced by sio2cmdInitJoystick().
JoystickRegData()
static u32 JoystickRegData (void) static
Definition at line 563 of file sio2Cmds.c.
 {
         return 0x240940;
 }
Referenced by sio2cmdInitJoystick().
JoystickSize1()
static u32 JoystickSize1 (void) static
Definition at line 568 of file sio2Cmds.c.
 {
         return 0x9;
 }
Referenced by sio2cmdInitJoystick().
JoystickSize2()
static u32 JoystickSize2 (void) static
Definition at line 573 of file sio2Cmds.c.
 {
         return 0x9;
 }
Referenced by sio2cmdInitJoystick().
KonamiGunEnterConfigMode()
static u32 KonamiGunEnterConfigMode (u8 * a) static
Definition at line 410 of file sio2Cmds.c.
 {
         a[0] = 0x1;
         a[1] = 0x43;
         a[2] = 0;
         a[3] = 0x1;
         a[4] = 0;
         return 0x5;
 }
Referenced by sio2cmdInitKonamiGun().
KonamiGunGetPortCtrl1()
static u32 KonamiGunGetPortCtrl1 (u32 a, u32 b) static
Definition at line 379 of file sio2Cmds.c.
 {
         if(a == 0)
                 return 0xFFC00505;
         else
                 return 0xFF060505;
 }
Referenced by sio2cmdInitKonamiGun().
KonamiGunGetPortCtrl2()
static u32 KonamiGunGetPortCtrl2 (u32 a) static
Definition at line 387 of file sio2Cmds.c.
 {
         if(a == 0)
                 return 0x20014;
         else
                 return 0x2012C;
 }
Referenced by sio2cmdInitKonamiGun().
KonamiGunReadData()
static void KonamiGunReadData (u8 * a) static
Definition at line 370 of file sio2Cmds.c.
 {
         a[0] = 1;
         a[1] = 0x42;
         a[2] = 0;
         a[3] = 0;
         a[4] = 0;
 }
Referenced by sio2cmdInitKonamiGun().
KonamiGunRegData()
static u32 KonamiGunRegData (void) static
Definition at line 395 of file sio2Cmds.c.
 {
         return 0x140540;
 }
Referenced by sio2cmdInitKonamiGun().
KonamiGunSize1()
static u32 KonamiGunSize1 (void) static
Definition at line 400 of file sio2Cmds.c.
 {
         return 0x5;
 }
Referenced by sio2cmdInitKonamiGun().
KonamiGunSize2()
static u32 KonamiGunSize2 (void) static
Definition at line 405 of file sio2Cmds.c.
 {
         return 0x5;
 }
Referenced by sio2cmdInitKonamiGun().
MouseEnterConfigMode()
static u32 MouseEnterConfigMode (u8 * a) static
Definition at line 234 of file sio2Cmds.c.
 {
         a[0] = 0x1;
         a[1] = 0x43;
         a[2] = 0;
         a[3] = 0x1;
         a[4] = 0;
         a[5] = 0;
         a[6] = 0;
         return 0x7;
 }
Referenced by sio2cmdInitMouse().
MouseGetPortCtrl1()
static u32 MouseGetPortCtrl1 (u32 a, u32 b) static
Definition at line 203 of file sio2Cmds.c.
 {
         if(a == 0)
                 return 0xFFC00505;
         else
                 return 0xFF060505;
 }
Referenced by sio2cmdInitMouse().
MouseGetPortCtrl2()
static u32 MouseGetPortCtrl2 (u32 a) static
Definition at line 211 of file sio2Cmds.c.
 {
         if(a == 0)
                 return 0x20014;
         else
                 return 0x2012C;
 }
Referenced by sio2cmdInitMouse().
MouseReadData()
static void MouseReadData (u8 * a) static
Definition at line 192 of file sio2Cmds.c.
 {
         a[0] = 1;
         a[1] = 0x42;
         a[2] = 0;
         a[3] = 0;
         a[4] = 0;
         a[5] = 0;
         a[6] = 0;
 }
Referenced by sio2cmdInitMouse().
MouseRegData()
static u32 MouseRegData (void) static
Definition at line 219 of file sio2Cmds.c.
 {
         return 0x1c0740;
 }
Referenced by sio2cmdInitMouse().
MouseSize1()
static u32 MouseSize1 (void) static
Definition at line 224 of file sio2Cmds.c.
 {
         return 0x7;
 }
Referenced by sio2cmdInitMouse().
MouseSize2()
static u32 MouseSize2 (void) static
Definition at line 229 of file sio2Cmds.c.
 {
         return 0x7;
 }
Referenced by sio2cmdInitMouse().
NamcoGunEnterConfigMode()
static u32 NamcoGunEnterConfigMode (u8 * a) static
Definition at line 668 of file sio2Cmds.c.
 {
         a[0] = 0x1;
         a[1] = 0x43;
         a[2] = 0;
         a[3] = 0x1;
         a[4] = 0;
         a[5] = 0;
         a[6] = 0;
         a[7] = 0;
         a[8] = 0;
         return 0x9;
 }
Referenced by sio2cmdInitNamcoGun().
NamcoGunGetPortCtrl1()
static u32 NamcoGunGetPortCtrl1 (u32 a, u32 b) static
Definition at line 637 of file sio2Cmds.c.
 {
         if(a == 0)
                 return 0xFFC00505;
         else
                 return 0xFF060505;
 }
Referenced by sio2cmdInitNamcoGun().
NamcoGunGetPortCtrl2()
static u32 NamcoGunGetPortCtrl2 (u32 a) static
Definition at line 645 of file sio2Cmds.c.
 {
         if(a == 0)
                 return 0x20014;
         else
                 return 0x2012C;
 }
Referenced by sio2cmdInitNamcoGun().
NamcoGunReadData()
static void NamcoGunReadData (u8 * a) static
Definition at line 624 of file sio2Cmds.c.
 {
         a[0] = 1;
         a[1] = 0x42;
         a[2] = 0;
         a[3] = 0;
         a[4] = 0;
         a[5] = 0;
         a[6] = 0;
         a[7] = 0;
         a[8] = 0;
 }
Referenced by sio2cmdInitNamcoGun().
NamcoGunRegData()
static u32 NamcoGunRegData (void) static
Definition at line 653 of file sio2Cmds.c.
 {
         return 0x240940;
 }
Referenced by sio2cmdInitNamcoGun().
NamcoGunSize1()
static u32 NamcoGunSize1 (void) static
Definition at line 658 of file sio2Cmds.c.
 {
         return 0x9;
 }
Referenced by sio2cmdInitNamcoGun().
NamcoGunSize2()
static u32 NamcoGunSize2 (void) static
Definition at line 663 of file sio2Cmds.c.
 {
         return 0x9;
 }
Referenced by sio2cmdInitNamcoGun().
NegiconEnterConfigMode()
static u32 NegiconEnterConfigMode (u8 * a) static
Definition at line 324 of file sio2Cmds.c.
 {
         a[0] = 0x1;
         a[1] = 0x43;
         a[2] = 0;
         a[3] = 0x1;
         a[4] = 0;
         a[5] = 0;
         a[6] = 0;
         a[7] = 0;
         a[8] = 0;
         return 0x9;
 }
Referenced by sio2cmdInitNegicon().
NegiconGetPortCtrl1()
static u32 NegiconGetPortCtrl1 (u32 a, u32 b) static
Definition at line 292 of file sio2Cmds.c.
 {
         if(a == 0)
                 return 0xFFC00505;
         else
                 return 0xFF060505;
 }
Referenced by sio2cmdInitNegicon().
NegiconGetPortCtrl2()
static u32 NegiconGetPortCtrl2 (u32 a) static
Definition at line 301 of file sio2Cmds.c.
 {
         if(a == 0)
                 return 0x20014;
         else
                 return 0x2012C;
 }
Referenced by sio2cmdInitNegicon().
NegiconReadData()
static void NegiconReadData (u8 * a) static
Definition at line 279 of file sio2Cmds.c.
 {
         a[0] = 1;
         a[1] = 0x42;
         a[2] = 0;
         a[3] = 0;
         a[4] = 0;
         a[5] = 0;
         a[6] = 0;
         a[7] = 0;
         a[8] = 0;
 }
Referenced by sio2cmdInitNegicon().
NegiconRegData()
static u32 NegiconRegData (void) static
Definition at line 309 of file sio2Cmds.c.
 {
         return 0x240940;
 }
Referenced by sio2cmdInitNegicon().
NegiconSize1()
static u32 NegiconSize1 (void) static
Definition at line 314 of file sio2Cmds.c.
 {
         return 0x9;
 }
Referenced by sio2cmdInitNegicon().
NegiconSize2()
static u32 NegiconSize2 (void) static
Definition at line 319 of file sio2Cmds.c.
 {
         return 0x9;
 }
Referenced by sio2cmdInitNegicon().
SetupCmds()
static int SetupCmds (const sio2Cmds_t * s) static
Definition at line 52 of file sio2Cmds.c.
 {
         if( ((numControllers+1) < SIO2_CMD_MAX) && (s != NULL) )
         {
                 if(numControllers > 0)
                 {
                         int i = 0;
                         // Check if the controller was already registered (if so, do nothing).
                         do
{
                                 if(s->id == sio2Cmds[i].id)
                                         return 0;
                                 i++;
                         } while(numControllers > i);
                 }
                 //Register new controller
                 int i = numControllers;
                 sio2Cmds[i].id = s->id;
                 sio2Cmds[i].readdata = s->readdata;
                 sio2Cmds[i].getportctrl1 = s->getportctrl1;
                 sio2Cmds[i].getportctrl2 = s->getportctrl2;
                 sio2Cmds[i].reg_data = s->reg_data;
                 sio2Cmds[i].size1 = s->size1;
                 sio2Cmds[i].size2 = s->size2;
                 sio2Cmds[i].enterconfigmode = s->enterconfigmode;
                 sio2Cmds[i].exitconfigmode = s->exitconfigmode;
                 sio2Cmds[i].querymodel = s->querymodel;
                 sio2Cmds[i].queryact = s->queryact;
                 sio2Cmds[i].querycomb = s->querycomb;
                 sio2Cmds[i].querymode = s->querymode;
                 sio2Cmds[i].querybuttonmask = s->querybuttonmask;
                 sio2Cmds[i].setbuttoninfo = s->setbuttoninfo;
                 sio2Cmds[i].setvrefparam = s->setvrefparam;
                 sio2Cmds[i].setmainmode = s->setmainmode;
                 sio2Cmds[i].setactalign = s->setactalign;
                 numControllers++;
                 return 1;
         }
         else
         {
                 return 0;
         }
 }
References sio2Cmds_t::enterconfigmode, sio2Cmds_t::exitconfigmode, sio2Cmds_t::getportctrl1, sio2Cmds_t::getportctrl2, sio2Cmds_t::id, NULL, numControllers, sio2Cmds_t::queryact, sio2Cmds_t::querybuttonmask, sio2Cmds_t::querycomb, sio2Cmds_t::querymode, sio2Cmds_t::querymodel, sio2Cmds_t::readdata, sio2Cmds_t::reg_data, sio2Cmds_t::setactalign, sio2Cmds_t::setbuttoninfo, sio2Cmds_t::setmainmode, sio2Cmds_t::setvrefparam, SIO2_CMD_MAX, sio2Cmds, sio2Cmds_t::size1, and sio2Cmds_t::size2.
Referenced by sio2cmdInitAnalog(), sio2cmdInitConfig(), sio2cmdInitDigital(), sio2cmdInitFindPads(), sio2cmdInitJogcon(), sio2cmdInitJoystick(), sio2cmdInitKonamiGun(), sio2cmdInitMouse(), sio2cmdInitNamcoGun(), and sio2cmdInitNegicon().
sio2cmdCheckId()
u32 sio2cmdCheckId (u8 id)
Definition at line 1149 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if( sio2Cmds[i].id == id )
                         return 1;
         }
         return 0;
 }
References numControllers, PAD_ID_HI, and sio2Cmds.
Referenced by PadIsSupported().
sio2CmdGetPortCtrl1()
u32 sio2CmdGetPortCtrl1 (u8 id, u32 b, u8 c)
Definition at line 1164 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if(sio2Cmds[i].id == id)
                 {
                         if(sio2Cmds[i].getportctrl1 != NULL)
                                 return sio2Cmds[i].getportctrl1(b, c);
                 }
         }
         return 0;
 }
References sio2Cmds_t::getportctrl1, NULL, numControllers, PAD_ID_HI, and sio2Cmds.
Referenced by EnterConfigMode(), ExitConfigMode(), PadIsSupported(), QueryAct(), QueryButtonMask(), QueryComb(), QueryMode(), QueryModel(), ReadData(), SetActAlign(), SetButtonInfo(), SetMainMode(), setupReadData(), and VrefParam().
sio2CmdGetPortCtrl2()
u32 sio2CmdGetPortCtrl2 (u32 id, u32 b)
Definition at line 1181 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if(sio2Cmds[i].id == id)
                 {
                         if(sio2Cmds[i].getportctrl2 != NULL)
                                 return sio2Cmds[i].getportctrl2(b);
                 }
         }
         return 0;
 }
References sio2Cmds_t::getportctrl2, NULL, numControllers, PAD_ID_HI, and sio2Cmds.
Referenced by EnterConfigMode(), ExitConfigMode(), PadIsSupported(), QueryAct(), QueryButtonMask(), QueryComb(), QueryMode(), QueryModel(), ReadData(), SetActAlign(), SetButtonInfo(), SetMainMode(), setupReadData(), and VrefParam().
sio2cmdInitAnalog()
void sio2cmdInitAnalog (void)
Definition at line 796 of file sio2Cmds.c.
 {
         sio2Cmds_t s;
         s.id = PAD_ID_HI(PAD_ID_ANALOG);
         s.readdata = &AnalogReadData;
         s.getportctrl1 = &AnalogGetPortCtrl1;
         s.getportctrl2 = &AnalogGetPortCtrl2;
         s.reg_data = NULL;
         s.size1 = NULL;
         s.size2 = NULL;
         s.enterconfigmode = &AnalogEnterConfigMode;
         s.exitconfigmode = NULL;
         s.querymodel = NULL;
         s.queryact = NULL;
         s.querycomb = NULL;
         s.querymode = NULL;
         s.querybuttonmask = NULL;
         s.setbuttoninfo = NULL;
         s.setvrefparam = NULL;
         s.setmainmode = NULL;
         s.setactalign = NULL;
         SetupCmds(&s);
 }
References AnalogEnterConfigMode(), AnalogGetPortCtrl1(), AnalogGetPortCtrl2(), AnalogReadData(), sio2Cmds_t::enterconfigmode, sio2Cmds_t::exitconfigmode, sio2Cmds_t::getportctrl1, sio2Cmds_t::getportctrl2, sio2Cmds_t::id, NULL, PAD_ID_ANALOG, PAD_ID_HI, sio2Cmds_t::queryact, sio2Cmds_t::querybuttonmask, sio2Cmds_t::querycomb, sio2Cmds_t::querymode, sio2Cmds_t::querymodel, sio2Cmds_t::readdata, sio2Cmds_t::reg_data, sio2Cmds_t::setactalign, sio2Cmds_t::setbuttoninfo, sio2Cmds_t::setmainmode, SetupCmds(), sio2Cmds_t::setvrefparam, sio2Cmds_t::size1, and sio2Cmds_t::size2.
Referenced by padInit().
sio2cmdInitConfig()
void sio2cmdInitConfig (void)
Definition at line 1119 of file sio2Cmds.c.
 {
         sio2Cmds_t s;
         s.id = PAD_ID_HI( PAD_ID_CONFIG );
         s.readdata = &ConfigReadData;
         s.getportctrl1 = &ConfigGetPortCtrl1;
         s.getportctrl2 = &ConfigGetPortCtrl2;
         s.reg_data = &ConfigRegData;
         s.size1 = &ConfigSize1;
         s.size2 = &ConfigSize2;
         s.enterconfigmode = NULL;
         s.exitconfigmode = &ConfigExitConfigMode;
         s.querymodel = &ConfigQueryModel;
         s.queryact = &ConfigQueryAct;
         s.querycomb = &ConfigQueryComb;
         s.querymode = &ConfigQueryMode;
         s.querybuttonmask = &ConfigQueryButtonMask;
         s.setbuttoninfo = &ConfigSetButtonInfo;
         s.setvrefparam = &ConfigSetVrefParam;
         s.setmainmode = &ConfigSetMainMode;
         s.setactalign = &ConfigSetSetActAlign;
         SetupCmds(&s);
 }
References ConfigExitConfigMode(), ConfigGetPortCtrl1(), ConfigGetPortCtrl2(), ConfigQueryAct(), ConfigQueryButtonMask(), ConfigQueryComb(), ConfigQueryMode(), ConfigQueryModel(), ConfigReadData(), ConfigRegData(), ConfigSetButtonInfo(), ConfigSetMainMode(), ConfigSetSetActAlign(), ConfigSetVrefParam(), ConfigSize1(), ConfigSize2(), sio2Cmds_t::enterconfigmode, sio2Cmds_t::exitconfigmode, sio2Cmds_t::getportctrl1, sio2Cmds_t::getportctrl2, sio2Cmds_t::id, NULL, PAD_ID_CONFIG, PAD_ID_HI, sio2Cmds_t::queryact, sio2Cmds_t::querybuttonmask, sio2Cmds_t::querycomb, sio2Cmds_t::querymode, sio2Cmds_t::querymodel, sio2Cmds_t::readdata, sio2Cmds_t::reg_data, sio2Cmds_t::setactalign, sio2Cmds_t::setbuttoninfo, sio2Cmds_t::setmainmode, SetupCmds(), sio2Cmds_t::setvrefparam, sio2Cmds_t::size1, and sio2Cmds_t::size2.
Referenced by padInit().
sio2cmdInitDigital()
void sio2cmdInitDigital (void)
Definition at line 503 of file sio2Cmds.c.
 {
         sio2Cmds_t s;
         s.id = PAD_ID_HI(PAD_ID_DIGITAL);
         s.readdata = &DigitalReadData;
         s.getportctrl1 = &DigitalGetPortCtrl1;
         s.getportctrl2 = &DigitalGetPortCtrl2;
         s.reg_data = &DigitalRegData;
         s.size1 = &DigitalSize1;
         s.size2 = &DigitalSize2;
         s.enterconfigmode = &DigitalEnterConfigMode;
         s.exitconfigmode = NULL;
         s.querymodel = NULL;
         s.queryact = NULL;
         s.querycomb = NULL;
         s.querymode = NULL;
         s.querybuttonmask = NULL;
         s.setbuttoninfo = NULL;
         s.setvrefparam = NULL;
         s.setmainmode = NULL;
         s.setactalign = NULL;
         SetupCmds(&s);
 }
References DigitalEnterConfigMode(), DigitalGetPortCtrl1(), DigitalGetPortCtrl2(), DigitalReadData(), DigitalRegData(), DigitalSize1(), DigitalSize2(), sio2Cmds_t::enterconfigmode, sio2Cmds_t::exitconfigmode, sio2Cmds_t::getportctrl1, sio2Cmds_t::getportctrl2, sio2Cmds_t::id, NULL, PAD_ID_DIGITAL, PAD_ID_HI, sio2Cmds_t::queryact, sio2Cmds_t::querybuttonmask, sio2Cmds_t::querycomb, sio2Cmds_t::querymode, sio2Cmds_t::querymodel, sio2Cmds_t::readdata, sio2Cmds_t::reg_data, sio2Cmds_t::setactalign, sio2Cmds_t::setbuttoninfo, sio2Cmds_t::setmainmode, SetupCmds(), sio2Cmds_t::setvrefparam, sio2Cmds_t::size1, and sio2Cmds_t::size2.
Referenced by padInit().
sio2cmdInitFindPads()
void sio2cmdInitFindPads (void)
Definition at line 161 of file sio2Cmds.c.
 {
         sio2Cmds_t s;
         s.id = PAD_ID_HI(PAD_ID_FINDPADS);
         s.readdata = &FindPadsReadData;
         s.getportctrl1 = &FindPadsGetPortCtrl1;
         s.getportctrl2 = &FindPadsGetPortCtrl2;
         s.reg_data = &FindPadsRegData;
         s.size1 = &FindPadsGetSize1;
         s.size2 = &FindPadsGetSize2;
         s.enterconfigmode = &FindPadsEnterConfigMode;
         s.exitconfigmode = NULL;
         s.querymodel = NULL;
         s.queryact = NULL;
         s.querycomb = NULL;
         s.querymode = NULL;
         s.querybuttonmask = NULL;
         s.setbuttoninfo = NULL;
         s.setvrefparam = NULL;
         s.setmainmode = NULL;
         s.setactalign = NULL;
         SetupCmds(&s);
 }
References sio2Cmds_t::enterconfigmode, sio2Cmds_t::exitconfigmode, FindPadsEnterConfigMode(), FindPadsGetPortCtrl1(), FindPadsGetPortCtrl2(), FindPadsGetSize1(), FindPadsGetSize2(), FindPadsReadData(), FindPadsRegData(), sio2Cmds_t::getportctrl1, sio2Cmds_t::getportctrl2, sio2Cmds_t::id, NULL, PAD_ID_FINDPADS, PAD_ID_HI, sio2Cmds_t::queryact, sio2Cmds_t::querybuttonmask, sio2Cmds_t::querycomb, sio2Cmds_t::querymode, sio2Cmds_t::querymodel, sio2Cmds_t::readdata, sio2Cmds_t::reg_data, sio2Cmds_t::setactalign, sio2Cmds_t::setbuttoninfo, sio2Cmds_t::setmainmode, SetupCmds(), sio2Cmds_t::setvrefparam, sio2Cmds_t::size1, and sio2Cmds_t::size2.
Referenced by padInit().
sio2cmdInitJogcon()
void sio2cmdInitJogcon (void)
Definition at line 894 of file sio2Cmds.c.
 {
         sio2Cmds_t s;
         s.id = PAD_ID_HI(PAD_ID_JOGCON);
         s.readdata = &JogconReadData;
         s.getportctrl1 = &JogconGetPortCtrl1;
         s.getportctrl2 = &JogconGetPortCtrl2;
         s.reg_data = &JogconRegData;
         s.size1 = &JogconSize1;
         s.size2 = &JogconSize2;
         s.enterconfigmode = &JogconEnterConfigMode;
         s.exitconfigmode = NULL;
         s.querymodel = NULL;
         s.queryact = NULL;
         s.querycomb = NULL;
         s.querymode = NULL;
         s.querybuttonmask = NULL;
         s.setbuttoninfo = NULL;
         s.setvrefparam = NULL;
         s.setmainmode = NULL;
         s.setactalign = NULL;
         SetupCmds(&s);
 }
References sio2Cmds_t::enterconfigmode, sio2Cmds_t::exitconfigmode, sio2Cmds_t::getportctrl1, sio2Cmds_t::getportctrl2, sio2Cmds_t::id, JogconEnterConfigMode(), JogconGetPortCtrl1(), JogconGetPortCtrl2(), JogconReadData(), JogconRegData(), JogconSize1(), JogconSize2(), NULL, PAD_ID_HI, PAD_ID_JOGCON, sio2Cmds_t::queryact, sio2Cmds_t::querybuttonmask, sio2Cmds_t::querycomb, sio2Cmds_t::querymode, sio2Cmds_t::querymodel, sio2Cmds_t::readdata, sio2Cmds_t::reg_data, sio2Cmds_t::setactalign, sio2Cmds_t::setbuttoninfo, sio2Cmds_t::setmainmode, SetupCmds(), sio2Cmds_t::setvrefparam, sio2Cmds_t::size1, and sio2Cmds_t::size2.
Referenced by padInit().
sio2cmdInitJoystick()
void sio2cmdInitJoystick (void)
Definition at line 593 of file sio2Cmds.c.
 {
         sio2Cmds_t s;
         s.id = PAD_ID_HI( PAD_ID_JOYSTICK );
         s.readdata = &JoystickReadData;
         s.getportctrl1 = &JoystickGetPortCtrl1;
         s.getportctrl2 = &JoystickGetPortCtrl2;
         s.reg_data = &JoystickRegData;
         s.size1 = &JoystickSize1;
         s.size2 = &JoystickSize2;
         s.enterconfigmode = &JoystickEnterConfigMode;
         s.exitconfigmode = NULL;
         s.querymodel = NULL;
         s.queryact = NULL;
         s.querycomb = NULL;
         s.querymode = NULL;
         s.querybuttonmask = NULL;
         s.setbuttoninfo = NULL;
         s.setvrefparam = NULL;
         s.setmainmode = NULL;
         s.setactalign = NULL;
         SetupCmds(&s);
 }
References sio2Cmds_t::enterconfigmode, sio2Cmds_t::exitconfigmode, sio2Cmds_t::getportctrl1, sio2Cmds_t::getportctrl2, sio2Cmds_t::id, JoystickEnterConfigMode(), JoystickGetPortCtrl1(), JoystickGetPortCtrl2(), JoystickReadData(), JoystickRegData(), JoystickSize1(), JoystickSize2(), NULL, PAD_ID_HI, PAD_ID_JOYSTICK, sio2Cmds_t::queryact, sio2Cmds_t::querybuttonmask, sio2Cmds_t::querycomb, sio2Cmds_t::querymode, sio2Cmds_t::querymodel, sio2Cmds_t::readdata, sio2Cmds_t::reg_data, sio2Cmds_t::setactalign, sio2Cmds_t::setbuttoninfo, sio2Cmds_t::setmainmode, SetupCmds(), sio2Cmds_t::setvrefparam, sio2Cmds_t::size1, and sio2Cmds_t::size2.
Referenced by padInit().
sio2cmdInitKonamiGun()
void sio2cmdInitKonamiGun (void)
Definition at line 421 of file sio2Cmds.c.
 {
         sio2Cmds_t s;
         s.id = PAD_ID_HI( PAD_ID_KONAMIGUN );
         s.readdata = &KonamiGunReadData;
         s.getportctrl1 = &KonamiGunGetPortCtrl1;
         s.getportctrl2 = &KonamiGunGetPortCtrl2;
         s.reg_data = &KonamiGunRegData;
         s.size1 = &KonamiGunSize1;
         s.size2 = &KonamiGunSize2;
         s.enterconfigmode = &KonamiGunEnterConfigMode;
         s.exitconfigmode = NULL;
         s.querymodel = NULL;
         s.queryact = NULL;
         s.querycomb = NULL;
         s.querymode = NULL;
         s.querybuttonmask = NULL;
         s.setbuttoninfo = NULL;
         s.setvrefparam = NULL;
         s.setmainmode = NULL;
         s.setactalign = NULL;
         SetupCmds(&s);
 }
References sio2Cmds_t::enterconfigmode, sio2Cmds_t::exitconfigmode, sio2Cmds_t::getportctrl1, sio2Cmds_t::getportctrl2, sio2Cmds_t::id, KonamiGunEnterConfigMode(), KonamiGunGetPortCtrl1(), KonamiGunGetPortCtrl2(), KonamiGunReadData(), KonamiGunRegData(), KonamiGunSize1(), KonamiGunSize2(), NULL, PAD_ID_HI, PAD_ID_KONAMIGUN, sio2Cmds_t::queryact, sio2Cmds_t::querybuttonmask, sio2Cmds_t::querycomb, sio2Cmds_t::querymode, sio2Cmds_t::querymodel, sio2Cmds_t::readdata, sio2Cmds_t::reg_data, sio2Cmds_t::setactalign, sio2Cmds_t::setbuttoninfo, sio2Cmds_t::setmainmode, SetupCmds(), sio2Cmds_t::setvrefparam, sio2Cmds_t::size1, and sio2Cmds_t::size2.
Referenced by padInit().
sio2cmdInitMouse()
void sio2cmdInitMouse (void)
Definition at line 247 of file sio2Cmds.c.
 {
         sio2Cmds_t s;
         s.id = PAD_ID_HI(PAD_ID_MOUSE);
         s.readdata = &MouseReadData;
         s.getportctrl1 = &MouseGetPortCtrl1;
         s.getportctrl2 = &MouseGetPortCtrl2;
         s.reg_data = &MouseRegData;
         s.size1 = &MouseSize1;
         s.size2 = &MouseSize2;
         s.enterconfigmode = &MouseEnterConfigMode;
         s.exitconfigmode = NULL;
         s.querymodel = NULL;
         s.queryact = NULL;
         s.querycomb = NULL;
         s.querymode = NULL;
         s.querybuttonmask = NULL;
         s.setbuttoninfo = NULL;
         s.setvrefparam = NULL;
         s.setmainmode = NULL;
         s.setactalign = NULL;
         SetupCmds(&s);
 }
References sio2Cmds_t::enterconfigmode, sio2Cmds_t::exitconfigmode, sio2Cmds_t::getportctrl1, sio2Cmds_t::getportctrl2, sio2Cmds_t::id, MouseEnterConfigMode(), MouseGetPortCtrl1(), MouseGetPortCtrl2(), MouseReadData(), MouseRegData(), MouseSize1(), MouseSize2(), NULL, PAD_ID_HI, PAD_ID_MOUSE, sio2Cmds_t::queryact, sio2Cmds_t::querybuttonmask, sio2Cmds_t::querycomb, sio2Cmds_t::querymode, sio2Cmds_t::querymodel, sio2Cmds_t::readdata, sio2Cmds_t::reg_data, sio2Cmds_t::setactalign, sio2Cmds_t::setbuttoninfo, sio2Cmds_t::setmainmode, SetupCmds(), sio2Cmds_t::setvrefparam, sio2Cmds_t::size1, and sio2Cmds_t::size2.
Referenced by padInit().
sio2cmdInitNamcoGun()
void sio2cmdInitNamcoGun (void)
Definition at line 683 of file sio2Cmds.c.
 {
         sio2Cmds_t s;
         s.id = PAD_ID_HI(PAD_ID_NAMCOGUN);
         s.readdata = &NamcoGunReadData;
         s.getportctrl1 = &NamcoGunGetPortCtrl1;
         s.getportctrl2 = &NamcoGunGetPortCtrl2;
         s.reg_data = &NamcoGunRegData;
         s.size1 = &NamcoGunSize1;
         s.size2 = &NamcoGunSize2;
         s.enterconfigmode = &NamcoGunEnterConfigMode;
         s.exitconfigmode = NULL;
         s.querymodel = NULL;
         s.queryact = NULL;
         s.querycomb = NULL;
         s.querymode = NULL;
         s.querybuttonmask = NULL;
         s.setbuttoninfo = NULL;
         s.setvrefparam = NULL;
         s.setmainmode = NULL;
         s.setactalign = NULL;
         SetupCmds(&s);
 }
References sio2Cmds_t::enterconfigmode, sio2Cmds_t::exitconfigmode, sio2Cmds_t::getportctrl1, sio2Cmds_t::getportctrl2, sio2Cmds_t::id, NamcoGunEnterConfigMode(), NamcoGunGetPortCtrl1(), NamcoGunGetPortCtrl2(), NamcoGunReadData(), NamcoGunRegData(), NamcoGunSize1(), NamcoGunSize2(), NULL, PAD_ID_HI, PAD_ID_NAMCOGUN, sio2Cmds_t::queryact, sio2Cmds_t::querybuttonmask, sio2Cmds_t::querycomb, sio2Cmds_t::querymode, sio2Cmds_t::querymodel, sio2Cmds_t::readdata, sio2Cmds_t::reg_data, sio2Cmds_t::setactalign, sio2Cmds_t::setbuttoninfo, sio2Cmds_t::setmainmode, SetupCmds(), sio2Cmds_t::setvrefparam, sio2Cmds_t::size1, and sio2Cmds_t::size2.
Referenced by padInit().
sio2cmdInitNegicon()
void sio2cmdInitNegicon (void)
Definition at line 339 of file sio2Cmds.c.
 {
         sio2Cmds_t s;
         s.id = PAD_ID_HI(PAD_ID_NEGICON);
         s.readdata = &NegiconReadData;
         s.getportctrl1 = &NegiconGetPortCtrl1;
         s.getportctrl2 = &NegiconGetPortCtrl2;
         s.reg_data = &NegiconRegData;
         s.size1 = &NegiconSize1;
         s.size2 = &NegiconSize2;
         s.enterconfigmode = &NegiconEnterConfigMode;
         s.exitconfigmode = NULL;
         s.querymodel = NULL;
         s.queryact = NULL;
         s.querycomb = NULL;
         s.querymode = NULL;
         s.querybuttonmask = NULL;
         s.setbuttoninfo = NULL;
         s.setvrefparam = NULL;
         s.setmainmode = NULL;
         s.setactalign = NULL;
         SetupCmds(&s);
 }
References sio2Cmds_t::enterconfigmode, sio2Cmds_t::exitconfigmode, sio2Cmds_t::getportctrl1, sio2Cmds_t::getportctrl2, sio2Cmds_t::id, NegiconEnterConfigMode(), NegiconGetPortCtrl1(), NegiconGetPortCtrl2(), NegiconReadData(), NegiconRegData(), NegiconSize1(), NegiconSize2(), NULL, PAD_ID_HI, PAD_ID_NEGICON, sio2Cmds_t::queryact, sio2Cmds_t::querybuttonmask, sio2Cmds_t::querycomb, sio2Cmds_t::querymode, sio2Cmds_t::querymodel, sio2Cmds_t::readdata, sio2Cmds_t::reg_data, sio2Cmds_t::setactalign, sio2Cmds_t::setbuttoninfo, sio2Cmds_t::setmainmode, SetupCmds(), sio2Cmds_t::setvrefparam, sio2Cmds_t::size1, and sio2Cmds_t::size2.
Referenced by padInit().
sio2cmdReset()
void sio2cmdReset (void)
Definition at line 42 of file sio2Cmds.c.
 {
         int i;
         for(i=0; i < SIO2_CMD_MAX; i++)
                 sio2Cmds[i].id = 0;
         numControllers = 0;
 }
References numControllers, SIO2_CMD_MAX, and sio2Cmds.
Referenced by padInit().
sio2CmdSetEnterConfigMode()
u32 sio2CmdSetEnterConfigMode (u32 id, u8 * buf)
Definition at line 1216 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if(sio2Cmds[i].id == id)
                 {
                         if(sio2Cmds[i].enterconfigmode != NULL)
                                 return sio2Cmds[i].enterconfigmode(buf);
                 }
         }
         return 0;
 }
References sio2Cmds_t::enterconfigmode, NULL, numControllers, PAD_ID_HI, and sio2Cmds.
Referenced by EnterConfigMode().
sio2CmdSetExitConfigMode()
u32 sio2CmdSetExitConfigMode (u32 id, u8 * buf)
Definition at line 1319 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if( sio2Cmds[i].id == id )
                 {
                         if( sio2Cmds[i].exitconfigmode != NULL)
                                 return sio2Cmds[i].exitconfigmode(buf);
                 }
         }
         return 0;
 }
References sio2Cmds_t::exitconfigmode, NULL, numControllers, PAD_ID_HI, and sio2Cmds.
Referenced by ExitConfigMode().
sio2CmdSetQueryAct()
u32 sio2CmdSetQueryAct (u32 id, u8 * buf)
Definition at line 1268 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if( sio2Cmds[i].id == id )
                 {
                         if( sio2Cmds[i].queryact != NULL)
                                 return sio2Cmds[i].queryact(buf);
                 }
         }
         return 0;
 }
References NULL, numControllers, PAD_ID_HI, sio2Cmds_t::queryact, and sio2Cmds.
Referenced by QueryAct().
sio2CmdSetQueryButtonMask()
u32 sio2CmdSetQueryButtonMask (u32 id, u8 * buf)
Definition at line 1353 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if( sio2Cmds[i].id == id )
                 {
                         if( sio2Cmds[i].querybuttonmask != NULL)
                                 return sio2Cmds[i].querybuttonmask(buf);
                 }
         }
         return 0;
 }
References NULL, numControllers, PAD_ID_HI, sio2Cmds_t::querybuttonmask, and sio2Cmds.
Referenced by QueryButtonMask().
sio2CmdSetQueryComb()
u32 sio2CmdSetQueryComb (u32 id, u8 * buf)
Definition at line 1285 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if( sio2Cmds[i].id == id )
                 {
                         if( sio2Cmds[i].querycomb != NULL)
                                 return sio2Cmds[i].querycomb(buf);
                 }
         }
         return 0;
 }
References NULL, numControllers, PAD_ID_HI, sio2Cmds_t::querycomb, and sio2Cmds.
Referenced by QueryComb().
sio2CmdSetQueryMode()
u32 sio2CmdSetQueryMode (u32 id, u8 * buf)
Definition at line 1302 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if( sio2Cmds[i].id == id )
                 {
                         if( sio2Cmds[i].querymode != NULL)
                                 return sio2Cmds[i].querymode(buf);
                 }
         }
         return 0;
 }
References NULL, numControllers, PAD_ID_HI, sio2Cmds_t::querymode, and sio2Cmds.
Referenced by QueryMode().
sio2CmdSetQueryModel()
u32 sio2CmdSetQueryModel (u32 id, u8 * buf)
Definition at line 1234 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if( sio2Cmds[i].id == id )
                 {
                         if( sio2Cmds[i].querymodel != NULL)
                                 return sio2Cmds[i].querymodel(buf);
                 }
         }
         return 0;
 }
References NULL, numControllers, PAD_ID_HI, sio2Cmds_t::querymodel, and sio2Cmds.
Referenced by QueryModel().
sio2CmdSetReadData()
void sio2CmdSetReadData (u32 id, u8 * buf)
Definition at line 1198 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if(sio2Cmds[i].id == id)
                 {
                         if(sio2Cmds[i].readdata != NULL)
{
                                 sio2Cmds[i].readdata(buf);
                                 return;
                         }
                 }
         }
 }
References NULL, numControllers, PAD_ID_HI, sio2Cmds_t::readdata, and sio2Cmds.
Referenced by PadIsSupported(), ReadData(), and setupReadData().
sio2CmdSetSetActAlign()
u32 sio2CmdSetSetActAlign (u32 id, u8 * buf)
Definition at line 1336 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if( sio2Cmds[i].id == id )
                 {
                         if( sio2Cmds[i].setactalign != NULL)
                                 return sio2Cmds[i].setactalign(buf);
                 }
         }
         return 0;
 }
References NULL, numControllers, PAD_ID_HI, sio2Cmds_t::setactalign, and sio2Cmds.
Referenced by SetActAlign().
sio2CmdSetSetButtonInfo()
u32 sio2CmdSetSetButtonInfo (u32 id, u8 * buf)
Definition at line 1388 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if( sio2Cmds[i].id == id )
                 {
                         if( sio2Cmds[i].setbuttoninfo != NULL)
                                 return sio2Cmds[i].setbuttoninfo(buf);
                 }
         }
         return 0;
 }
References NULL, numControllers, PAD_ID_HI, sio2Cmds_t::setbuttoninfo, and sio2Cmds.
Referenced by SetButtonInfo().
sio2CmdSetSetMainMode()
u32 sio2CmdSetSetMainMode (u32 id, u8 * buf)
Definition at line 1251 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if( sio2Cmds[i].id == id )
                 {
                         if( sio2Cmds[i].setmainmode != NULL)
                                 return sio2Cmds[i].setmainmode(buf);
                 }
         }
         return 0;
 }
References NULL, numControllers, PAD_ID_HI, sio2Cmds_t::setmainmode, and sio2Cmds.
Referenced by SetMainMode().
sio2CmdSetSetVrefParam()
u32 sio2CmdSetSetVrefParam (u32 id, u8 * buf)
Definition at line 1370 of file sio2Cmds.c.
 {
         int i;
         id = PAD_ID_HI(id);
         for(i=0; i < numControllers; i++)
         {
                 if( sio2Cmds[i].id == id )
                 {
                         if( sio2Cmds[i].setvrefparam != NULL)
                                 return sio2Cmds[i].setvrefparam(buf);
                 }
         }
         return 0;
 }
References NULL, numControllers, PAD_ID_HI, sio2Cmds_t::setvrefparam, and sio2Cmds.
Referenced by VrefParam().
Variable Documentation
numControllers
int numControllers static
Definition at line 40 of file sio2Cmds.c.
Referenced by SetupCmds(), sio2cmdCheckId(), sio2CmdGetPortCtrl1(), sio2CmdGetPortCtrl2(), sio2cmdReset(), sio2CmdSetEnterConfigMode(), sio2CmdSetExitConfigMode(), sio2CmdSetQueryAct(), sio2CmdSetQueryButtonMask(), sio2CmdSetQueryComb(), sio2CmdSetQueryMode(), sio2CmdSetQueryModel(), sio2CmdSetReadData(), sio2CmdSetSetActAlign(), sio2CmdSetSetButtonInfo(), sio2CmdSetSetMainMode(), and sio2CmdSetSetVrefParam().
sio2Cmds
sio2Cmds_t sio2Cmds[SIO2_CMD_MAX] static
Definition at line 39 of file sio2Cmds.c.
Referenced by SetupCmds(), sio2cmdCheckId(), sio2CmdGetPortCtrl1(), sio2CmdGetPortCtrl2(), sio2cmdReset(), sio2CmdSetEnterConfigMode(), sio2CmdSetExitConfigMode(), sio2CmdSetQueryAct(), sio2CmdSetQueryButtonMask(), sio2CmdSetQueryComb(), sio2CmdSetQueryMode(), sio2CmdSetQueryModel(), sio2CmdSetReadData(), sio2CmdSetSetActAlign(), sio2CmdSetSetButtonInfo(), sio2CmdSetSetMainMode(), and sio2CmdSetSetVrefParam().