ps2sdk: iop/memorycard/mcman/src/sio2man_imports.h File Reference
sio2man_imports.h File Reference
#include <types.h>
#include <irx.h>
#include <sio2man.h>
Macros
#define SIO2MAN 0
#define XSIO2MAN 1
#define XSIO2MAN_V2 2
Variables
void(* psio2_mc_transfer_init)(void)
int(* psio2_transfer)(sio2_transfer_data_t *sio2data)
void(* psio2_transfer_reset)(void)
int(* psio2_mtap_change_slot)(s32 *arg)
Macro Definition Documentation
SIO2MAN
#define SIO2MAN 0
Definition at line 8 of file sio2man_imports.h.
XSIO2MAN
#define XSIO2MAN 1
Definition at line 9 of file sio2man_imports.h.
XSIO2MAN_V2
#define XSIO2MAN_V2 2
Definition at line 10 of file sio2man_imports.h.
Variable Documentation
psio2_mc_transfer_init
void(* psio2_mc_transfer_init) (void) (void)
Definition at line 13 of file sio2man_imports.h.
Referenced by _start(), mcsio2_transfer(), and mcsio2_transfer2().
psio2_mtap_change_slot
int(* psio2_mtap_change_slot) (s32 *arg) (s32 * arg)
Definition at line 18 of file sio2man_imports.h.
Referenced by _start(), and mcsio2_transfer2().
psio2_transfer
int(* psio2_transfer) (sio2_transfer_data_t *sio2data) (sio2_transfer_data_t * sio2data)
Definition at line 14 of file sio2man_imports.h.
Referenced by _start(), mcsio2_transfer(), and mcsio2_transfer2().
psio2_transfer_reset
void(* psio2_transfer_reset) (void) (void)
Definition at line 17 of file sio2man_imports.h.
Referenced by _start(), and mcsio2_transfer2().