ps2sdk: iop/network/smbman/src/smb_fio.h File Reference
smb_fio.h File Reference
Functions
int smb_initdev (void)
int smb_dummy (void)
int smb_init (iop_device_t *iop_dev)
int smb_deinit (iop_device_t *dev)
int smb_open (iop_file_t *f, const char *filename, int flags, int mode)
int smb_close (iop_file_t *f)
int smb_lseek (iop_file_t *f, int pos, int where)
int smb_read (iop_file_t *f, void *buf, int size)
int smb_write (iop_file_t *f, void *buf, int size)
int smb_remove (iop_file_t *f, const char *filename)
int smb_mkdir (iop_file_t *f, const char *dirname, int mode)
int smb_rmdir (iop_file_t *f, const char *dirname)
int smb_dopen (iop_file_t *f, const char *dirname)
int smb_dclose (iop_file_t *f)
int smb_dread (iop_file_t *f, iox_dirent_t *dirent)
int smb_getstat (iop_file_t *f, const char *filename, iox_stat_t *stat)
int smb_rename (iop_file_t *f, const char *oldname, const char *newname)
int smb_chdir (iop_file_t *f, const char *dirname)
s64 smb_lseek64 (iop_file_t *f, s64 pos, int where)
int smb_devctl (iop_file_t *f, const char *devname, int cmd, void *arg, unsigned int arglen, void *bufp, unsigned int buflen)
Function Documentation
smb_chdir()
int smb_chdir (iop_file_t * f, const char * dirname)
Definition at line 771 of file smb_fio.c.
 {
         int r = 0, i;
         PathInformation_t info;
         if (!dirname)
                 return -ENOENT;
         if ((UID == -1) || (TID == -1))
                 return -ENOTCONN;
         char *path = prepare_path(dirname, smb_curpath, SMB_PATH_MAX);
         smb_io_lock();
         if ((path[strlen(path)-2] == '.') && (path[strlen(path)-1] == '.')) {
                 char *p = (char *)smb_curdir;
                 for (i=strlen(p)-1; i>=0; i--) {
                         if (p[i] == '\\') {
                                 p[i] = 0;
                                 break;
                         }
                 }
         }
         else if (path[strlen(path)-1] == '.') {
                 smb_curdir[0] = 0;
         }
         else {
                 r = smb_QueryPathInformation(UID, TID, &info, path);
                 if (r < 0) {
                         goto io_unlock;
                 }
                 if (!(info.FileAttributes & EXT_ATTR_DIRECTORY)) {
                         r = -ENOTDIR;
                         goto io_unlock;
                 }
                 strncpy(smb_curdir, path, sizeof(smb_curdir)-1);
         }
 io_unlock:
         smb_io_unlock();
         return r;
 }
References ENOENT, ENOTCONN, ENOTDIR, EXT_ATTR_DIRECTORY, prepare_path(), smb_curdir, smb_curpath, smb_io_lock(), smb_io_unlock(), SMB_PATH_MAX, smb_QueryPathInformation(), strlen(), strncpy(), TID, and UID.
smb_close()
int smb_close (iop_file_t * f)
Definition at line 366 of file smb_fio.c.
 {
         FHANDLE *fh = (FHANDLE *)f->privdata;
         int r = 0;
         if ((UID == -1) || (TID == -1) || (fh->smb_fid == -1))
                 return -EBADF;
         smb_io_lock();
         if (fh) {
                 if (fh->mode != O_DIROPEN) {
                         r = smb_Close(UID, TID, fh->smb_fid);
                         if (r != 0) {
                                 goto io_unlock;
                         }
                 }
                 memset(fh, 0, sizeof(FHANDLE));
                 fh->smb_fid = -1;
                 r = 0;
         }
 io_unlock:
         smb_io_unlock();
         return r;
 }
References EBADF, memset(), FHANDLE::mode, O_DIROPEN, iop_file_t::privdata, smb_Close(), FHANDLE::smb_fid, smb_io_lock(), smb_io_unlock(), TID, and UID.
Referenced by smb_dclose().
smb_dclose()
int smb_dclose (iop_file_t * f)
Definition at line 666 of file smb_fio.c.
 {
         return smb_close(f);
 }
References smb_close().
smb_deinit()
int smb_deinit (iop_device_t * dev)
Definition at line 261 of file smb_fio.c.
 {
         keepalive_deinit();
         DeleteThread(keepalive_tid);
         DeleteSema(smbman_io_sema);
         DeleteSema(keepalive_mutex);
         keepalive_mutex = -1;
         return 0;
 }
References DeleteSema(), DeleteThread(), keepalive_deinit(), keepalive_mutex, keepalive_tid, and smbman_io_sema.
smb_devctl()
int smb_devctl (iop_file_t * f, const char * devname, int cmd, void * arg, unsigned int arglen, void * bufp, unsigned int buflen)
Definition at line 1063 of file smb_fio.c.
 {
         int r = 0;
         smb_io_lock();
         switch(cmd) {
                 case SMB_DEVCTL_GETPASSWORDHASHES:
                         smb_GetPasswordHashes((smbGetPasswordHashes_in_t *)arg, (smbGetPasswordHashes_out_t *)bufp);
                         r = 0;
                         break;
                 case SMB_DEVCTL_LOGON:
                         r = smb_LogOn((smbLogOn_in_t *)arg);
                         break;
                 case SMB_DEVCTL_LOGOFF:
                         r = smb_LogOff();
                         break;
                 case SMB_DEVCTL_GETSHARELIST:
                         r = smb_GetShareList((smbGetShareList_in_t *)arg);
                         break;
                 case SMB_DEVCTL_OPENSHARE:
                         r = smb_OpenShare((smbOpenShare_in_t *)arg);
                         break;
                 case SMB_DEVCTL_CLOSESHARE:
                         r = smb_CloseShare();
                         break;
                 case SMB_DEVCTL_ECHO:
                         r = smb_EchoServer((smbEcho_in_t *)arg);
                         break;
                 case SMB_DEVCTL_QUERYDISKINFO:
                         r = smb_QueryDiskInfo((smbQueryDiskInfo_out_t *)bufp);
                         break;
                 default:
                         r = -EINVAL;
         }
         smb_io_unlock();
         return r;
 }
References arg, EINVAL, smb_CloseShare(), SMB_DEVCTL_CLOSESHARE, SMB_DEVCTL_ECHO, SMB_DEVCTL_GETPASSWORDHASHES, SMB_DEVCTL_GETSHARELIST, SMB_DEVCTL_LOGOFF, SMB_DEVCTL_LOGON, SMB_DEVCTL_OPENSHARE, SMB_DEVCTL_QUERYDISKINFO, smb_EchoServer(), smb_GetPasswordHashes(), smb_GetShareList(), smb_io_lock(), smb_io_unlock(), smb_LogOff(), smb_LogOn(), smb_OpenShare(), and smb_QueryDiskInfo().
smb_dopen()
int smb_dopen (iop_file_t * f, const char * dirname)
Definition at line 614 of file smb_fio.c.
 {
         int r = 0;
         PathInformation_t info;
         FHANDLE *fh;
         if (!dirname)
                 return -ENOENT;
         if ((UID == -1) || (TID == -1))
                 return -ENOTCONN;
         char *path = prepare_path(dirname, smb_curpath, SMB_PATH_MAX);
         smb_io_lock();
         // test if the dir exists
         r = smb_QueryPathInformation(UID, TID, &info, path);
         if (r < 0) {
                 goto io_unlock;
         }
         if (!(info.FileAttributes & EXT_ATTR_DIRECTORY)) {
                 r = -ENOTDIR;
                 goto io_unlock;
         }
         fh = smbman_getfilefreeslot();
         if (fh) {
                 f->privdata = fh;
                 fh->f = f;
                 fh->mode = O_DIROPEN;
                 fh->filesize = 0;
                 fh->position = 0;
                 strncpy(fh->name, path, 255);
                 if (fh->name[strlen(fh->name)-1] != '\\')
                         strcat(fh->name, "\\");
                 strcat(fh->name, "*");
                 r = 0;
         }
         else
                 r = -EMFILE;
 io_unlock:
         smb_io_unlock();
         return r;
 }
References EMFILE, ENOENT, ENOTCONN, ENOTDIR, EXT_ATTR_DIRECTORY, FHANDLE::f, FHANDLE::filesize, FHANDLE::mode, FHANDLE::name, O_DIROPEN, FHANDLE::position, prepare_path(), iop_file_t::privdata, smb_curpath, smb_io_lock(), smb_io_unlock(), SMB_PATH_MAX, smb_QueryPathInformation(), smbman_getfilefreeslot(), strcat(), strlen(), strncpy(), TID, and UID.
smb_dread()
int smb_dread (iop_file_t * f, iox_dirent_t * dirent)
Definition at line 672 of file smb_fio.c.
 {
         FHANDLE *fh = (FHANDLE *)f->privdata;
         int r;
         if ((UID == -1) || (TID == -1))
                 return -ENOTCONN;
         smb_io_lock();
         memset((void *)dirent, 0, sizeof(iox_dirent_t));
         SearchInfo_t *info = (SearchInfo_t *)SearchBuf;
         if (fh->smb_fid == -1) {
                 r = smb_FindFirstNext2(UID, TID, fh->name, TRANS2_FIND_FIRST2, info);
                 if (r < 0) {
                         goto io_unlock;
                 }
                 fh->smb_fid = info->SID;
                 r = 1;
         }
         else {
                 info->SID = fh->smb_fid;
                 r = smb_FindFirstNext2(UID, TID, NULL, TRANS2_FIND_NEXT2, info);
                 if (r < 0) {
                         goto io_unlock;
                 }
                 r = 1;
         }
         if (r == 1) {
                 smb_statFiller(&info->fileInfo, &dirent->stat);
                 strncpy(dirent->name, info->FileName, SMB_NAME_MAX);
         }
 io_unlock:
         smb_io_unlock();
         return r;
 }
References ENOTCONN, memset(), iox_dirent_t::name, FHANDLE::name, NULL, iop_file_t::privdata, SearchBuf, FHANDLE::smb_fid, smb_FindFirstNext2(), smb_io_lock(), smb_io_unlock(), SMB_NAME_MAX, smb_statFiller(), iox_dirent_t::stat, strncpy(), TID, TRANS2_FIND_FIRST2, TRANS2_FIND_NEXT2, and UID.
smb_dummy()
int smb_dummy (void)
Definition at line 206 of file smb_fio.c.
 {
         return -EIO;
 }
References EIO.
smb_getstat()
int smb_getstat (iop_file_t * f, const char * filename, iox_stat_t * stat)
Definition at line 715 of file smb_fio.c.
 {
         int r;
         PathInformation_t info;
         if (!filename)
                 return -ENOENT;
         if ((UID == -1) || (TID == -1))
                 return -ENOTCONN;
         char *path = prepare_path(filename, smb_curpath, SMB_PATH_MAX);
         smb_io_lock();
         memset((void *)stat, 0, sizeof(iox_stat_t));
         r = smb_QueryPathInformation(UID, TID, &info, path);
         if (r < 0) {
                 goto io_unlock;
         }
         smb_statFiller(&info, stat);
 io_unlock:
         smb_io_unlock();
         return r;
 }
References ENOENT, ENOTCONN, memset(), prepare_path(), smb_curpath, smb_io_lock(), smb_io_unlock(), SMB_PATH_MAX, smb_QueryPathInformation(), smb_statFiller(), TID, and UID.
smb_init()
int smb_init (iop_device_t * iop_dev)
Definition at line 212 of file smb_fio.c.
 {
         iop_thread_t thread;
         // create a mutex for IO ops
         smbman_io_sema = CreateMutex(IOP_MUTEX_UNLOCKED);
         // create a mutex for keep alive
         keepalive_mutex = CreateMutex(IOP_MUTEX_LOCKED);
         // set the keepalive timer (3 seconds)
         USec2SysClock(3000*1000, &keepalive_sysclock);
         // starting the keepalive thead
         thread.attr = TH_C;
         thread.option = 0;
         thread.thread = (void *)keepalive_thread;
         thread.stacksize = 0x600;
         thread.priority = 0x64;
         keepalive_tid = CreateThread(&thread);
         StartThread(keepalive_tid, NULL);
         return 0;
 }
References iop_thread_t::attr, CreateMutex(), CreateThread(), IOP_MUTEX_LOCKED, IOP_MUTEX_UNLOCKED, keepalive_mutex, keepalive_sysclock, keepalive_thread(), keepalive_tid, NULL, iop_thread_t::option, iop_thread_t::priority, smbman_io_sema, iop_thread_t::stacksize, StartThread(), TH_C, iop_thread_t::thread, and USec2SysClock().
smb_initdev()
int smb_initdev (void)
Definition at line 239 of file smb_fio.c.
 {
         int i;
         FHANDLE *fh;
         DelDrv(smbdev.name);
         if (AddDrv((iop_device_t *)&smbdev))
                 return 1;
         for (i=0; i<MAX_FDHANDLES; i++) {
                 fh = (FHANDLE *)&smbman_fdhandles[i];
                 fh->f = NULL;
                 fh->smb_fid = -1;
                 fh->filesize = 0;
                 fh->position = 0;
                 fh->mode = 0;
         }
         return 0;
 }
References AddDrv(), DelDrv(), FHANDLE::f, FHANDLE::filesize, MAX_FDHANDLES, FHANDLE::mode, iop_device_t::name, NULL, FHANDLE::position, FHANDLE::smb_fid, smbdev, and smbman_fdhandles.
Referenced by _start().
smb_lseek()
int smb_lseek (iop_file_t * f, int pos, int where)
Definition at line 408 of file smb_fio.c.
 {
         return (int)smb_lseek64(f, pos, where);
 }
References pos, and smb_lseek64().
smb_lseek64()
s64 smb_lseek64 (iop_file_t * f, s64 pos, int where)
Definition at line 819 of file smb_fio.c.
 {
         s64 r;
         FHANDLE *fh = (FHANDLE *)f->privdata;
         smb_io_lock();
         switch (where) {
                 case SEEK_CUR:
                         r = fh->position + pos;
                         if (r > fh->filesize) {
                                 r = -EINVAL;
                                 goto io_unlock;
                         }
                         break;
                 case SEEK_SET:
                         r = pos;
                         if (fh->filesize < pos) {
                                 r = -EINVAL;
                                 goto io_unlock;
                         }
                         break;
                 case SEEK_END:
                         r = fh->filesize;
                         break;
                 default:
                         r = -EINVAL;
                         goto io_unlock;
         }
         fh->position = r;
 io_unlock:
         smb_io_unlock();
         return r;
 }
References EINVAL, FHANDLE::filesize, pos, FHANDLE::position, iop_file_t::privdata, SEEK_CUR, SEEK_END, SEEK_SET, smb_io_lock(), and smb_io_unlock().
Referenced by smb_lseek().
smb_mkdir()
int smb_mkdir (iop_file_t * f, const char * dirname, int mode)
Definition at line 488 of file smb_fio.c.
 {
         int r;
         if (!dirname)
                 return -ENOENT;
         if ((UID == -1) || (TID == -1))
                 return -ENOTCONN;
         char *path = prepare_path(dirname, smb_curpath, SMB_PATH_MAX);
         smb_io_lock();
         r = smb_ManageDirectory(UID, TID, path, SMB_COM_CREATE_DIRECTORY);
         smb_io_unlock();
         return r;
 }
References ENOENT, ENOTCONN, prepare_path(), SMB_COM_CREATE_DIRECTORY, smb_curpath, smb_io_lock(), smb_io_unlock(), smb_ManageDirectory(), SMB_PATH_MAX, TID, and UID.
smb_open()
int smb_open (iop_file_t * f, const char * filename, int flags, int mode)
Definition at line 323 of file smb_fio.c.
 {
         int r = 0;
         FHANDLE *fh;
         s64 filesize;
         if (!filename)
                 return -ENOENT;
         if ((UID == -1) || (TID == -1))
                 return -ENOTCONN;
         char *path = prepare_path(filename, smb_curpath, SMB_PATH_MAX);
         smb_io_lock();
         fh = smbman_getfilefreeslot();
         if (fh) {
                 r = smb_OpenAndX(UID, TID, path, &filesize, flags);
                 if (r >= 0) {
                         f->privdata = fh;
                         fh->f = f;
                         fh->smb_fid = r;
                         fh->mode = flags;
                         fh->filesize = filesize;
                         fh->position = 0;
                         if (fh->mode & O_TRUNC)
                                 fh->filesize = 0;
                         else if (fh->mode & O_APPEND)
                                 fh->position = filesize;
                         strncpy(fh->name, path, SMB_NAME_MAX);
                         r = 0;
                 }
         }
         else
                 r = -EMFILE;
         smb_io_unlock();
         return r;
 }
References EMFILE, ENOENT, ENOTCONN, FHANDLE::f, FHANDLE::filesize, FHANDLE::mode, FHANDLE::name, O_APPEND, O_TRUNC, FHANDLE::position, prepare_path(), iop_file_t::privdata, smb_curpath, FHANDLE::smb_fid, smb_io_lock(), smb_io_unlock(), SMB_NAME_MAX, smb_OpenAndX(), SMB_PATH_MAX, smbman_getfilefreeslot(), strncpy(), TID, and UID.
smb_read()
int smb_read (iop_file_t * f, void * buf, int size)
Definition at line 414 of file smb_fio.c.
 {
         FHANDLE *fh = (FHANDLE *)f->privdata;
         int r;
         if ((UID == -1) || (TID == -1) || (fh->smb_fid == -1))
                 return -EBADF;
         if ((fh->position + size) > fh->filesize)
                 size = fh->filesize - fh->position;
         smb_io_lock();
         r = smb_ReadFile(UID, TID, fh->smb_fid, fh->position, buf, size);
         if (r > 0) {
                 fh->position += r;
         }
         smb_io_unlock();
         return r;
 }
References EBADF, FHANDLE::filesize, FHANDLE::position, iop_file_t::privdata, FHANDLE::smb_fid, smb_io_lock(), smb_io_unlock(), smb_ReadFile(), TID, and UID.
smb_remove()
int smb_remove (iop_file_t * f, const char * filename)
Definition at line 464 of file smb_fio.c.
 {
         int r;
         if (!filename)
                 return -ENOENT;
         if ((UID == -1) || (TID == -1))
                 return -ENOTCONN;
         char *path = prepare_path(filename, smb_curpath, SMB_PATH_MAX);
         smb_io_lock();
         DPRINTF("smb_remove: filename=%s\n", filename);
         r = smb_Delete(UID, TID, path);
         smb_io_unlock();
         return r;
 }
References DPRINTF, ENOENT, ENOTCONN, prepare_path(), smb_curpath, smb_Delete(), smb_io_lock(), smb_io_unlock(), SMB_PATH_MAX, TID, and UID.
smb_rename()
int smb_rename (iop_file_t * f, const char * oldname, const char * newname)
Definition at line 746 of file smb_fio.c.
 {
         int r;
         if ((!oldname) || (!newname))
                 return -ENOENT;
         if ((UID == -1) || (TID == -1))
                 return -ENOTCONN;
         char *oldpath = prepare_path(oldname, smb_curpath, SMB_PATH_MAX);
         char *newpath = prepare_path(newname, smb_secpath, SMB_PATH_MAX);
         smb_io_lock();
         DPRINTF("smb_rename: oldname=%s newname=%s\n", oldname, newname);
         r = smb_Rename(UID, TID, oldpath, newpath);
         smb_io_unlock();
         return r;
 }
References DPRINTF, ENOENT, ENOTCONN, prepare_path(), smb_curpath, smb_io_lock(), smb_io_unlock(), SMB_PATH_MAX, smb_Rename(), smb_secpath, TID, and UID.
smb_rmdir()
int smb_rmdir (iop_file_t * f, const char * dirname)
Definition at line 510 of file smb_fio.c.
 {
         int r;
         PathInformation_t info;
         if (!dirname)
                 return -ENOENT;
         if ((UID == -1) || (TID == -1))
                 return -ENOTCONN;
         char *path = prepare_path(dirname, smb_curpath, SMB_PATH_MAX);
         smb_io_lock();
         r = smb_QueryPathInformation(UID, TID, &info, path);
         if (r < 0) {
                 goto io_unlock;
         }
         if (!(info.FileAttributes & EXT_ATTR_DIRECTORY)) {
                 r = -ENOTDIR;
                 goto io_unlock;
         }
         r = smb_ManageDirectory(UID, TID, path, SMB_COM_DELETE_DIRECTORY);
 io_unlock:
         smb_io_unlock();
         return r;
 }
References ENOENT, ENOTCONN, ENOTDIR, EXT_ATTR_DIRECTORY, prepare_path(), SMB_COM_DELETE_DIRECTORY, smb_curpath, smb_io_lock(), smb_io_unlock(), smb_ManageDirectory(), SMB_PATH_MAX, smb_QueryPathInformation(), TID, and UID.
smb_write()
int smb_write (iop_file_t * f, void * buf, int size)
Definition at line 438 of file smb_fio.c.
 {
         FHANDLE *fh = (FHANDLE *)f->privdata;
         int r;
         if ((UID == -1) || (TID == -1) || (fh->smb_fid == -1))
                 return -EBADF;
         if ((!(fh->mode & O_RDWR)) && (!(fh->mode & O_WRONLY)))
                 return -EACCES;
         smb_io_lock();
         r = smb_WriteFile(UID, TID, fh->smb_fid, fh->position, buf, size);
         if (r > 0) {
                 fh->position += r;
                 if (fh->position > fh->filesize)
                         fh->filesize += fh->position - fh->filesize;
         }
         smb_io_unlock();
         return r;
 }
References EACCES, EBADF, FHANDLE::filesize, FHANDLE::mode, O_RDWR, O_WRONLY, FHANDLE::position, iop_file_t::privdata, FHANDLE::smb_fid, smb_io_lock(), smb_io_unlock(), smb_WriteFile(), TID, and UID.