ps2sdk: iop/network/smbman/src/smb.c File Reference
smb.c File Reference
#include <types.h>
#include <errno.h>
#include <irx.h>
#include <limits.h>
#include <stdio.h>
#include <sysclib.h>
#include <ps2ip.h>
#include <ioman.h>
#include "smb.h"
#include "auth.h"
#include "poll.h"
#include "debug.h"
Macros
#define ZERO_PKT_ALIGNED(hdr, hdrSize) memset((hdr), 0, ((hdrSize) + 3) & ~3)
#define LM_AUTH 0
#define NTLM_AUTH 1
#define CLIENT_MAX_BUFFER_SIZE USHRT_MAX
#define CLIENT_MAX_XFER_SIZE USHRT_MAX
Functions
server_specs_t * getServerSpecs (void)
static void nb_SetSessionMessage (u32 size)
static int nb_GetSessionMessageLength (void)
static u8 nb_GetPacketType (void)
static int OpenTCPSession (struct in_addr dst_IP, u16 dst_port, int *sock)
static int RecvTimeout (int sock, void *buf, int bsize, int timeout_ms)
static int SendData (int sock, char *buf, int size)
static int RecvData (int sock, char *buf, int size, int timeout_ms)
static int GetSMBServerReply (int shdrlen, void *spayload, int rhdrlen)
static int asciiToUtf16 (char *out, const char *in)
static int utf16ToAscii (char *out, const char *in, int inbytes)
static int setStringField (char *out, const char *in)
static int getStringField (char *out, const char *in, int inbytes)
int smb_NegotiateProtocol (u32 *capabilities)
static int AddPassword (char *Password, int PasswordType, int AuthType, u16 *AnsiPassLen, u16 *UnicodePassLen, u8 *Buffer)
int smb_SessionSetupAndX (char *User, char *Password, int PasswordType, u32 capabilities)
int smb_TreeConnectAndX (int UID, char *ShareName, char *Password, int PasswordType)
int smb_NetShareEnum (int UID, int TID, ShareEntry_t *shareEntries, int index, int maxEntries)
int smb_QueryInformationDisk (int UID, int TID, smbQueryDiskInfo_out_t *QueryInformationDisk)
int smb_QueryPathInformation (int UID, int TID, PathInformation_t *Info, char *Path)
int smb_NTCreateAndX (int UID, int TID, char *filename, s64 *filesize, int mode)
int smb_OpenAndX (int UID, int TID, char *filename, s64 *filesize, int mode)
int smb_ReadAndX (int UID, int TID, int FID, s64 fileoffset, void *readbuf, int nbytes)
int smb_ReadFile (int UID, int TID, int FID, s64 fileoffset, void *readbuf, int nbytes)
int smb_WriteAndX (int UID, int TID, int FID, s64 fileoffset, void *writebuf, int nbytes)
int smb_WriteFile (int UID, int TID, int FID, s64 fileoffset, void *writebuf, int nbytes)
int smb_Close (int UID, int TID, int FID)
int smb_Delete (int UID, int TID, char *Path)
int smb_ManageDirectory (int UID, int TID, char *Path, int cmd)
int smb_Rename (int UID, int TID, char *oldPath, char *newPath)
int smb_FindFirstNext2 (int UID, int TID, char *Path, int cmd, SearchInfo_t *info)
int smb_TreeDisconnect (int UID, int TID)
int smb_LogOffAndX (int UID)
int smb_Echo (void *echo, int len)
int smb_Connect (char *SMBServerIP, int SMBServerPort)
int smb_Disconnect (void)
Variables
static server_specs_t server_specs
static int main_socket = -1
struct {
u32 sessionHeader
union {
u8 u8buff [MAX_SMB_BUF+MAX_SMB_BUF_HDR]
u16 u16buff [(MAX_SMB_BUF+MAX_SMB_BUF_HDR)/sizeof(u16)]
s16 s16buff [(MAX_SMB_BUF+MAX_SMB_BUF_HDR)/sizeof(s16)]
NegotiateProtocolRequest_t negotiateProtocolRequest
NegotiateProtocolResponse_t negotiateProtocolResponse
SessionSetupAndXRequest_t sessionSetupAndXRequest
SessionSetupAndXResponse_t sessionSetupAndXResponse
TreeConnectAndXRequest_t treeConnectAndXRequest
TreeConnectAndXResponse_t treeConnectAndXResponse
TreeDisconnectRequest_t treeDisconnectRequest
TreeDisconnectResponse_t treeDisconnectResponse
NetShareEnumRequest_t netShareEnumRequest
NetShareEnumResponse_t netShareEnumResponse
LogOffAndXRequest_t logOffAndXRequest
LogOffAndXResponse_t logOffAndXResponse
EchoRequest_t echoRequest
EchoResponse_t echoResponse
QueryInformationDiskRequest_t queryInformationDiskRequest
QueryInformationDiskResponse_t queryInformationDiskResponse
QueryPathInformationRequest_t queryPathInformationRequest
QueryPathInformationResponse_t queryPathInformationResponse
FindFirstNext2Request_t findFirstNext2Request
FindFirstNext2Response_t findFirstNext2Response
NTCreateAndXRequest_t ntCreateAndXRequest
NTCreateAndXResponse_t ntCreateAndXResponse
OpenAndXRequest_t openAndXRequest
OpenAndXResponse_t openAndXResponse
ReadAndXRequest_t readAndXRequest
ReadAndXResponse_t readAndXResponse
WriteAndXRequest_t writeAndXRequest
WriteAndXResponse_t writeAndXResponse
CloseRequest_t closeRequest
CloseResponse_t closeResponse
DeleteRequest_t deleteRequest
DeleteResponse_t deleteResponse
ManageDirectoryRequest_t manageDirectoryRequest
ManageDirectoryResponse_t manageDirectoryResponse
RenameRequest_t renameRequest
RenameResponse_t renameResponse
} smb
} SMB_buf
Macro Definition Documentation
CLIENT_MAX_BUFFER_SIZE
#define CLIENT_MAX_BUFFER_SIZE USHRT_MAX
Definition at line 28 of file smb.c.
CLIENT_MAX_XFER_SIZE
#define CLIENT_MAX_XFER_SIZE USHRT_MAX
Definition at line 29 of file smb.c.
LM_AUTH
#define LM_AUTH 0
Definition at line 25 of file smb.c.
NTLM_AUTH
#define NTLM_AUTH 1
Definition at line 26 of file smb.c.
ZERO_PKT_ALIGNED
#define ZERO_PKT_ALIGNED (hdr, hdrSize) memset((hdr), 0, ((hdrSize) + 3) & ~3)
Definition at line 21 of file smb.c.
Function Documentation
AddPassword()
static int AddPassword (char * Password, int PasswordType, int AuthType, u16 * AnsiPassLen, u16 * UnicodePassLen, u8 * Buffer) static
Definition at line 424 of file smb.c.
 {
         u8 passwordhash[16];
         u8 LMresponse[24];
         u16 passwordlen = 0;
         if ((Password) && (PasswordType != NO_PASSWORD)) {
                 if (server_specs.PasswordType == SERVER_USE_ENCRYPTED_PASSWORD) {
                         passwordlen = 24;
                         switch (PasswordType) {
                                 case HASHED_PASSWORD:
                                         if (AuthType == LM_AUTH) {
                                                 memcpy(passwordhash, Password, 16);
                                                 memcpy(AnsiPassLen, &passwordlen, 2);
                                         }
                                         if (AuthType == NTLM_AUTH) {
                                                 memcpy(passwordhash, &Password[16], 16);
                                                 memcpy(UnicodePassLen, &passwordlen, 2);
                                         }
                                         break;
                                 default:
                                         if (AuthType == LM_AUTH) {
                                                 LM_Password_Hash((const unsigned char*)Password, passwordhash);
                                                 memcpy(AnsiPassLen, &passwordlen, 2);
                                         }
                                         else if (AuthType == NTLM_AUTH) {
                                                 NTLM_Password_Hash((const unsigned char*)Password, passwordhash);
                                                 memcpy(UnicodePassLen, &passwordlen, 2);
                                         }
                         }
                         LM_Response(passwordhash, server_specs.EncryptionKey, LMresponse);
                         memcpy(Buffer, LMresponse, passwordlen);
                 }
                 else if (server_specs.PasswordType == SERVER_USE_PLAINTEXT_PASSWORD) {
                         // It seems that PlainText passwords and Unicode isn't meant to be...
                         passwordlen = strlen(Password);
                         if (passwordlen > 14)
                                 passwordlen = 14;
                         else if (passwordlen == 0)
                                 passwordlen = 1;
                         memcpy(AnsiPassLen, &passwordlen, 2);
                         memcpy(Buffer, Password, passwordlen);
                 }
         }
         else {
                 if (server_specs.SecurityMode == SERVER_SHARE_SECURITY_LEVEL) {
                         passwordlen = 1;
                         memcpy(AnsiPassLen, &passwordlen, 2);
                         Buffer[0] = 0;
                 }
         }
         return passwordlen;
 }
References server_specs_t::EncryptionKey, HASHED_PASSWORD, LM_AUTH, LM_Password_Hash(), LM_Response(), memcpy(), NO_PASSWORD, NTLM_AUTH, NTLM_Password_Hash(), server_specs_t::PasswordType, server_specs_t::SecurityMode, SERVER_SHARE_SECURITY_LEVEL, server_specs, SERVER_USE_ENCRYPTED_PASSWORD, SERVER_USE_PLAINTEXT_PASSWORD, and strlen().
Referenced by smb_SessionSetupAndX(), and smb_TreeConnectAndX().
asciiToUtf16()
static int asciiToUtf16 (char * out, const char * in) static
Definition at line 265 of file smb.c.
 {
         int len;
         const char *pIn;
         u8 *pOut;
         for(pIn = in, pOut = out, len = 0; *pIn != '\0'; pIn++, pOut += 2, len += 2)
         {
                 pOut[0] = *pIn;
                 pOut[1] = '\0';
         }
         pOut[0] = '\0'; //NULL terminate.
         pOut[1] = '\0';
         len += 2;
         return len;
 }
Referenced by setStringField().
getServerSpecs()
server_specs_t* getServerSpecs (void)
Definition at line 80 of file smb.c.
 {
         return &server_specs;
 }
References server_specs.
Referenced by smb_GetShareList(), and smb_OpenShare().
GetSMBServerReply()
static int GetSMBServerReply (int shdrlen, void * spayload, int rhdrlen) static
Definition at line 218 of file smb.c.
 {
         int rcv_size, totalpkt_size, size;
         totalpkt_size = nb_GetSessionMessageLength() + 4;
         if (shdrlen == 0)
         {
                 //Send the whole message, including the 4-byte direct transport packet header.
                 rcv_size = SendData(main_socket, (char*)&SMB_buf, totalpkt_size);
                 if (rcv_size <= 0)
                         return -1;
         }
         else
         {
                 size = shdrlen + 4;
                 //Send the headers, followed by the payload.
                 rcv_size = SendData(main_socket, (char*)&SMB_buf, size);
                 if (rcv_size <= 0)
                         return -1;
                 rcv_size = SendData(main_socket, spayload, totalpkt_size - size);
                 if (rcv_size <= 0)
                         return -1;
         }
         //Read NetBIOS session message header. Drop NBSS Session Keep alive messages (type == 0x85, with no body), but process session messages (type == 0x00).
         do{
                 rcv_size = RecvData(main_socket, (char *)&SMB_buf.sessionHeader, sizeof(SMB_buf.sessionHeader), 10000); // 10s before the packet is considered lost
                 if (rcv_size <= 0)
                         return -2;
         } while (nb_GetPacketType() != 0);
         totalpkt_size = nb_GetSessionMessageLength();
         //If rhdrlen is not specified, retrieve the whole packet. Otherwise, retrieve only the headers (caller will retrieve the payload separately).
         size = (rhdrlen == 0) ? totalpkt_size : rhdrlen;
         rcv_size = RecvData(main_socket, (char *)&SMB_buf.smb, size, 3000); // 3s before the packet is considered lost
         if (rcv_size <= 0)
                 return -2;
         return totalpkt_size;
 }
References main_socket, nb_GetPacketType(), nb_GetSessionMessageLength(), RecvData(), SendData(), and SMB_buf.
Referenced by smb_Close(), smb_Delete(), smb_Echo(), smb_FindFirstNext2(), smb_LogOffAndX(), smb_ManageDirectory(), smb_NegotiateProtocol(), smb_NetShareEnum(), smb_NTCreateAndX(), smb_OpenAndX(), smb_QueryInformationDisk(), smb_QueryPathInformation(), smb_ReadAndX(), smb_Rename(), smb_SessionSetupAndX(), smb_TreeConnectAndX(), smb_TreeDisconnect(), and smb_WriteAndX().
getStringField()
static int getStringField (char * out, const char * in, int inbytes) static
Definition at line 337 of file smb.c.
 {
         int len;
         if (server_specs.Capabilities & SERVER_CAP_UNICODE)
         {
                 len = utf16ToAscii(out, in, inbytes);
         }
         else
         {
                 if (inbytes != 0)
                 {
                         strncpy(out, in, inbytes);
                         out[inbytes] = '\0';
                 }
                 else
                         strcpy(out, in);
                 len = strlen(out) + 1;
         }
         return len;
 }
References server_specs_t::Capabilities, SERVER_CAP_UNICODE, server_specs, strcpy(), strlen(), strncpy(), and utf16ToAscii().
Referenced by smb_FindFirstNext2(), and smb_NegotiateProtocol().
nb_GetPacketType()
static u8 nb_GetPacketType (void) static
Definition at line 105 of file smb.c.
 {
         // Byte-swap length from network byte-order.
         return((u8)(SMB_buf.sessionHeader & 0xff));
 }
References SMB_buf.
Referenced by GetSMBServerReply().
nb_GetSessionMessageLength()
static int nb_GetSessionMessageLength (void) static
Definition at line 94 of file smb.c.
 {
         u32 size;
         // maximum for raw TCP transport (24 bits) !!!
         // Byte-swap length from network byte-order.
         size = ((SMB_buf.sessionHeader << 8) & 0xff0000) | ((SMB_buf.sessionHeader >> 8) & 0xff00) | ((SMB_buf.sessionHeader >> 24) & 0xff);
         return (int)size;
 }
References SMB_buf.
Referenced by GetSMBServerReply().
nb_SetSessionMessage()
static void nb_SetSessionMessage (u32 size) static
Definition at line 86 of file smb.c.
 {
         // maximum for raw TCP transport (24 bits) !!!
         // Byte-swap length into network byte-order.
         SMB_buf.sessionHeader = ((size & 0xff0000) >> 8) | ((size & 0xff00) << 8) | ((size & 0xff) << 24);
 }
References SMB_buf.
Referenced by smb_Close(), smb_Delete(), smb_Echo(), smb_FindFirstNext2(), smb_LogOffAndX(), smb_ManageDirectory(), smb_NegotiateProtocol(), smb_NetShareEnum(), smb_NTCreateAndX(), smb_OpenAndX(), smb_QueryInformationDisk(), smb_QueryPathInformation(), smb_ReadAndX(), smb_Rename(), smb_SessionSetupAndX(), smb_TreeConnectAndX(), smb_TreeDisconnect(), and smb_WriteAndX().
OpenTCPSession()
static int OpenTCPSession (struct in_addr dst_IP, u16 dst_port, int * sock) static
Definition at line 112 of file smb.c.
 {
         int sck, ret, opt;
         struct sockaddr_in sock_addr;
         *sock = -1;
         // Creating socket
         sck = lwip_socket(PF_INET, SOCK_STREAM, IPPROTO_TCP);
         if (sck < 0)
                 return -1;
         *sock = sck;
         opt = 1;
         lwip_setsockopt(sck, IPPROTO_TCP, TCP_NODELAY, (char*)&opt, sizeof(opt));
         memset(&sock_addr, 0, sizeof(sock_addr));
         sock_addr.sin_addr = dst_IP;
         sock_addr.sin_family = AF_INET;
         sock_addr.sin_port = htons(dst_port);
         ret = lwip_connect(sck, (struct sockaddr *)&sock_addr, sizeof(sock_addr));
         if (ret < 0)
                 return -2;
         return 0;
 }
References AF_INET, htons(), IPPROTO_TCP, lwip_connect(), lwip_setsockopt(), lwip_socket(), memset(), PF_INET, sockaddr_in::sin_addr, sockaddr_in::sin_family, sockaddr_in::sin_port, SOCK_STREAM, and TCP_NODELAY.
Referenced by smb_Connect().
RecvData()
static int RecvData (int sock, char * buf, int size, int timeout_ms) static
Definition at line 197 of file smb.c.
 {
         int remaining, result;
         char *ptr;
         ptr = buf;
         remaining = size;
         while (remaining > 0)
         {
                 result = RecvTimeout(sock, ptr, remaining, timeout_ms);
                 if (result <= 0)
                         return result;
                 ptr += result;
                 remaining -= result;
         }
         return size;
 }
References RecvTimeout(), and result.
Referenced by GetSMBServerReply(), and smb_ReadAndX().
RecvTimeout()
static int RecvTimeout (int sock, void * buf, int bsize, int timeout_ms) static
Definition at line 150 of file smb.c.
 {
         int ret;
         struct pollfd pollfd[1];
         pollfd->fd = sock;
         pollfd->events = POLLIN;
         pollfd->revents = 0;
         ret = poll(pollfd, 1, timeout_ms);
         // a result less than 0 is an error
         if (ret < 0)
                 return -1;
         // 0 is a timeout
         if (ret == 0)
                 return 0;
         // receive the packet
         ret = lwip_recv(sock, buf, bsize, 0);
         if (ret < 0)
                 return -2;
         return ret;
 }
References lwip_recv(), poll(), and POLLIN.
Referenced by RecvData().
SendData()
static int SendData (int sock, char * buf, int size) static
Definition at line 177 of file smb.c.
 {
         int remaining, result;
         char *ptr;
         ptr = buf;
         remaining = size;
         while (remaining > 0)
         {
                 result = lwip_send(sock, ptr, remaining, 0);
                 if (result <= 0)
                         return result;
                 ptr += result;
                 remaining -= result;
         }
         return size;
 }
References lwip_send(), and result.
Referenced by GetSMBServerReply().
setStringField()
static int setStringField (char * out, const char * in) static
Definition at line 320 of file smb.c.
 {
         int len;
         if (server_specs.Capabilities & SERVER_CAP_UNICODE)
         {
                 len = asciiToUtf16(out, in);
         }
         else
         {
                 len = strlen(in) + 1;
                 strcpy(out, in);
         }
         return len;
 }
References asciiToUtf16(), server_specs_t::Capabilities, SERVER_CAP_UNICODE, server_specs, strcpy(), and strlen().
Referenced by smb_Delete(), smb_FindFirstNext2(), smb_ManageDirectory(), smb_NTCreateAndX(), smb_OpenAndX(), smb_QueryPathInformation(), smb_Rename(), smb_SessionSetupAndX(), and smb_TreeConnectAndX().
smb_Close()
int smb_Close (int UID, int TID, int FID)
Definition at line 1177 of file smb.c.
 {
         int r;
         CloseRequest_t *CR = &SMB_buf.smb.closeRequest;
         CloseResponse_t *CRsp = &SMB_buf.smb.closeResponse;
         ZERO_PKT_ALIGNED(CR, sizeof(CloseRequest_t));
         CR->smbH.Magic = SMB_MAGIC;
         CR->smbH.Cmd = SMB_COM_CLOSE;
         CR->smbH.Flags = SMB_FLAGS_CANONICAL_PATHNAMES;
         CR->smbH.Flags2 = SMB_FLAGS2_KNOWS_LONG_NAMES | SMB_FLAGS2_32BIT_STATUS;
         CR->smbH.UID = (u16)UID;
         CR->smbH.TID = (u16)TID;
         CR->smbWordcount = 3;
         CR->FID = (u16)FID;
         nb_SetSessionMessage(sizeof(CloseRequest_t));
         r = GetSMBServerReply(0, NULL, 0);
         if (r <= 0)
                 return -EIO;
         // check sanity of SMB header
         if (CRsp->smbH.Magic != SMB_MAGIC)
                 return -EIO;
         // check there's no error
         if ((CRsp->smbH.Eclass | (CRsp->smbH.Ecode << 16)) != STATUS_SUCCESS)
                 return -EIO;
         return 0;
 }
References SMBHeader_t::Cmd, SMBHeader_t::Eclass, SMBHeader_t::Ecode, EIO, CloseRequest_t::FID, SMBHeader_t::Flags, SMBHeader_t::Flags2, GetSMBServerReply(), SMBHeader_t::Magic, nb_SetSessionMessage(), NULL, SMB_buf, SMB_COM_CLOSE, SMB_FLAGS2_32BIT_STATUS, SMB_FLAGS2_KNOWS_LONG_NAMES, SMB_FLAGS_CANONICAL_PATHNAMES, SMB_MAGIC, CloseRequest_t::smbH, CloseResponse_t::smbH, CloseRequest_t::smbWordcount, STATUS_SUCCESS, SMBHeader_t::TID, TID, SMBHeader_t::UID, UID, and ZERO_PKT_ALIGNED.
Referenced by smb_close(), and smb_closeAll().
smb_Connect()
int smb_Connect (char * SMBServerIP, int SMBServerPort)
Definition at line 1578 of file smb.c.
 {
         int r;
         struct in_addr dst_addr;
         dst_addr.s_addr = inet_addr(SMBServerIP);
         // Close the connection if it was already opened
         smb_Disconnect();
         // Opening TCP session
         r = OpenTCPSession(dst_addr, SMBServerPort, &main_socket);
         if (r < 0) {
                 return -1;
         }
         // We keep the server IP for SMB logon
         strncpy(server_specs.ServerIP, SMBServerIP, 16);
         return 0;
 }
References inet_addr, main_socket, OpenTCPSession(), in_addr::s_addr, server_specs, server_specs_t::ServerIP, smb_Disconnect(), and strncpy().
Referenced by smb_LogOn().
smb_Delete()
int smb_Delete (int UID, int TID, char * Path)
Definition at line 1211 of file smb.c.
 {
         int r, PathLen;
         DeleteRequest_t *DR = &SMB_buf.smb.deleteRequest;
         DeleteResponse_t *DRsp = &SMB_buf.smb.deleteResponse;
         ZERO_PKT_ALIGNED(DR, sizeof(DeleteRequest_t));
         DR->smbH.Magic = SMB_MAGIC;
         DR->smbH.Cmd = SMB_COM_DELETE;
         DR->smbH.Flags = SMB_FLAGS_CANONICAL_PATHNAMES;
         DR->smbH.Flags2 = SMB_FLAGS2_KNOWS_LONG_NAMES | SMB_FLAGS2_32BIT_STATUS;
         if (server_specs.Capabilities & SERVER_CAP_UNICODE)
                 DR->smbH.Flags2 |= SMB_FLAGS2_UNICODE_STRING;
         DR->smbH.UID = (u16)UID;
         DR->smbH.TID = (u16)TID;
         DR->smbWordcount = 1;
         DR->SearchAttributes = 0; // coud be other attributes to find Hidden/System files
         DR->BufferFormat = 0x04;
         // Add path
         PathLen = setStringField(DR->FileName, Path);
         DR->ByteCount = PathLen+1;                      // +1 for the BufferFormat byte
         nb_SetSessionMessage(sizeof(DeleteRequest_t) + PathLen);
         r = GetSMBServerReply(0, NULL, 0);
         if (r <= 0)
                 return -EIO;
         // check sanity of SMB header
         if (DRsp->smbH.Magic != SMB_MAGIC)
                 return -EIO;
         // check there's no error
         if ((DRsp->smbH.Eclass | (DRsp->smbH.Ecode << 16)) != STATUS_SUCCESS)
                 return -EIO;
         return 0;
 }
References DeleteRequest_t::BufferFormat, DeleteRequest_t::ByteCount, server_specs_t::Capabilities, SMBHeader_t::Cmd, SMBHeader_t::Eclass, SMBHeader_t::Ecode, EIO, DeleteRequest_t::FileName, SMBHeader_t::Flags, SMBHeader_t::Flags2, GetSMBServerReply(), SMBHeader_t::Magic, nb_SetSessionMessage(), NULL, DeleteRequest_t::SearchAttributes, SERVER_CAP_UNICODE, server_specs, setStringField(), SMB_buf, SMB_COM_DELETE, SMB_FLAGS2_32BIT_STATUS, SMB_FLAGS2_KNOWS_LONG_NAMES, SMB_FLAGS2_UNICODE_STRING, SMB_FLAGS_CANONICAL_PATHNAMES, SMB_MAGIC, DeleteRequest_t::smbH, DeleteResponse_t::smbH, DeleteRequest_t::smbWordcount, STATUS_SUCCESS, SMBHeader_t::TID, TID, SMBHeader_t::UID, UID, and ZERO_PKT_ALIGNED.
Referenced by smb_remove().
smb_Disconnect()
int smb_Disconnect (void)
Definition at line 1601 of file smb.c.
 {
         char dummy;
         if (main_socket != -1) {
                 //Ensure that all data has been received by the other side before closing.
                 shutdown(main_socket, SHUT_WR);
                 //Wait for the remote end to close the socket, which shall happen after all sent data has been received.
                 while(recv(main_socket, &dummy, sizeof(dummy), 0) > 0);
                 lwip_close(main_socket);
                 main_socket = -1;
         }
         return 0;
 }
References dummy(), lwip_close(), main_socket, recv, SHUT_WR, and shutdown.
Referenced by smb_Connect(), and smb_LogOff().
smb_Echo()
int smb_Echo (void * echo, int len)
Definition at line 1542 of file smb.c.
 {
         int r;
         EchoRequest_t *ER = &SMB_buf.smb.echoRequest;
         EchoResponse_t *ERsp = &SMB_buf.smb.echoResponse;
         ZERO_PKT_ALIGNED(ER, sizeof(EchoRequest_t));
         ER->smbH.Magic = SMB_MAGIC;
         ER->smbH.Cmd = SMB_COM_ECHO;
         ER->smbWordcount = 1;
         ER->EchoCount = 1;
         memcpy(&ER->ByteField[0], echo, (u16)len);
         ER->ByteCount = (u16)len;
         nb_SetSessionMessage(sizeof(EchoRequest_t)+(u16)len);
         r = GetSMBServerReply(0, NULL, 0);
         if (r <= 0)
                 return -EIO;
         // check sanity of SMB header
         if (ERsp->smbH.Magic != SMB_MAGIC)
                 return -EIO;
         // check there's no error
         if ((ERsp->smbH.Eclass | (ERsp->smbH.Ecode << 16)) != STATUS_SUCCESS)
                 return -EIO;
         if (memcmp(&ERsp->ByteField[0], echo, len))
                 return -EIO;
         return 0;
 }
References EchoRequest_t::ByteCount, EchoRequest_t::ByteField, EchoResponse_t::ByteField, SMBHeader_t::Cmd, EchoRequest_t::EchoCount, SMBHeader_t::Eclass, SMBHeader_t::Ecode, EIO, GetSMBServerReply(), SMBHeader_t::Magic, memcmp(), memcpy(), nb_SetSessionMessage(), NULL, SMB_buf, SMB_COM_ECHO, SMB_MAGIC, EchoRequest_t::smbH, EchoResponse_t::smbH, EchoRequest_t::smbWordcount, STATUS_SUCCESS, and ZERO_PKT_ALIGNED.
Referenced by keepalive_thread(), and smb_EchoServer().
smb_FindFirstNext2()
int smb_FindFirstNext2 (int UID, int TID, char * Path, int cmd, SearchInfo_t * info)
Definition at line 1365 of file smb.c.
 {
         int r, PathLen, offset;
         FindFirstNext2Request_t *FFNR = &SMB_buf.smb.findFirstNext2Request;
         FindFirstNext2Response_t *FFNRsp = &SMB_buf.smb.findFirstNext2Response;
         ZERO_PKT_ALIGNED(FFNR, sizeof(FindFirstNext2Request_t));
         FFNR->smbH.Magic = SMB_MAGIC;
         FFNR->smbH.Cmd = SMB_COM_TRANSACTION2;
         FFNR->smbH.Flags = SMB_FLAGS_CANONICAL_PATHNAMES;
         FFNR->smbH.Flags2 = SMB_FLAGS2_KNOWS_LONG_NAMES | SMB_FLAGS2_32BIT_STATUS;
         if (server_specs.Capabilities & SERVER_CAP_UNICODE)
                 FFNR->smbH.Flags2 |= SMB_FLAGS2_UNICODE_STRING;
         FFNR->smbH.UID = (u16)UID;
         FFNR->smbH.TID = (u16)TID;
         FFNR->smbWordcount = 15;
         FFNR->smbTrans.SetupCount = 1;
         FFNR->SubCommand = (u8)cmd;
         FFNR->smbTrans.ParamOffset = (sizeof(FindFirstNext2Request_t) + 3) & ~3;                //Keep aligned to a 4-byte boundary as required.
         FFNR->smbTrans.MaxParamCount = 256;                                                     // Max Parameters len in reply
         FFNR->smbTrans.MaxDataCount = MAX_SMB_BUF - FFNR->smbTrans.MaxParamCount;               // Max Data len in reply
         //Zero Pad1.
         memset((void*)(FFNR + 1), 0, FFNR->smbTrans.ParamOffset - sizeof(FindFirstNext2Request_t));
         if (cmd == TRANS2_FIND_FIRST2) {
                 FindFirst2RequestParam_t *FFRParam = (FindFirst2RequestParam_t *)&SMB_buf.smb.u8buff[FFNR->smbTrans.ParamOffset];
                 FFRParam->SearchAttributes = ATTR_READONLY | ATTR_HIDDEN | ATTR_SYSTEM | ATTR_DIRECTORY | ATTR_ARCHIVE;
                 FFRParam->SearchCount = 1;
                 FFRParam->Flags = CLOSE_SEARCH_IF_EOS | RESUME_SEARCH;
                 FFRParam->LevelOfInterest = SMB_FIND_FILE_BOTH_DIRECTORY_INFO;
                 FFRParam->StorageType = 0;
                 // Add path
                 PathLen = setStringField(FFRParam->SearchPattern, Path);
                 FFNR->smbTrans.TotalParamCount = FFNR->smbTrans.ParamCount = sizeof(FindFirst2RequestParam_t) + PathLen;
         }
         else {
                 FindNext2RequestParam_t *FNRParam = (FindNext2RequestParam_t *)&SMB_buf.smb.u8buff[FFNR->smbTrans.ParamOffset];
                 FNRParam->SearchID = (u16)info->SID;
                 FNRParam->SearchCount = 1;
                 FNRParam->LevelOfInterest = SMB_FIND_FILE_BOTH_DIRECTORY_INFO;
                 FNRParam->ResumeKey = 0;
                 FNRParam->Flags = CLOSE_SEARCH_IF_EOS | RESUME_SEARCH | CONTINUE_SEARCH;
                 FNRParam->SearchPattern[0] = 0;
                 FFNR->smbTrans.TotalParamCount = FFNR->smbTrans.ParamCount = sizeof(FindNext2RequestParam_t) + 1;
         }
         FFNR->ByteCount = 3 + FFNR->smbTrans.TotalParamCount;
         offset = FFNR->smbTrans.ParamOffset + FFNR->smbTrans.TotalParamCount;
         //No data, so no Pad2. As DataCount is 0, the client may set DataOffset to 0.
         //FFNR->smbTrans.DataOffset = (u16)offset;
         nb_SetSessionMessage(offset);
         r = GetSMBServerReply(0, NULL, 0);
         if (r <= 0)
                 return -EIO;
         // check sanity of SMB header
         if (FFNRsp->smbH.Magic != SMB_MAGIC)
                 return -EIO;
         // check there's no error
         switch(FFNRsp->smbH.Eclass | (FFNRsp->smbH.Ecode << 16)){
                 // check there's no error
                 case STATUS_SUCCESS:
                         break;
                 // check if access denied
                 case STATUS_ACCESS_DENIED:
                         return -EACCES;
                 default:
                         return -EIO;
         }
         FindFirstNext2ResponseParam_t *FFNRspParam;
         if (cmd == TRANS2_FIND_FIRST2) {
                 FFNRspParam = (FindFirstNext2ResponseParam_t *)&SMB_buf.smb.u8buff[FFNRsp->smbTrans.ParamOffset];
                 info->SID = FFNRspParam->SearchID;
         }
         else
                 FFNRspParam = (FindFirstNext2ResponseParam_t *)&SMB_buf.smb.u8buff[FFNRsp->smbTrans.ParamOffset-2];
         FindFirst2ResponseData_t *FFRspData = (FindFirst2ResponseData_t *)&SMB_buf.smb.u8buff[FFNRsp->smbTrans.DataOffset];
         info->EOS = FFNRspParam->EndOfSearch;
         if (FFNRspParam->SearchCount == 0)
                 return -EINVAL;
         info->fileInfo.Created = FFRspData->Created;
         info->fileInfo.LastAccess = FFRspData->LastAccess;
         info->fileInfo.LastWrite = FFRspData->LastWrite;
         info->fileInfo.Change = FFRspData->Change;
         info->fileInfo.FileAttributes = FFRspData->FileAttributes;
         if (FFRspData->FileAttributes & EXT_ATTR_DIRECTORY)
                 info->fileInfo.IsDirectory = 1;
         info->fileInfo.AllocationSize = FFRspData->AllocationSize;
         info->fileInfo.EndOfFile = FFRspData->EndOfFile;
         getStringField(info->FileName, FFRspData->FileName, FFRspData->FileNameLen);
         return 0;
 }
References ATTR_ARCHIVE, ATTR_DIRECTORY, ATTR_HIDDEN, ATTR_READONLY, ATTR_SYSTEM, FindFirstNext2Request_t::ByteCount, server_specs_t::Capabilities, CLOSE_SEARCH_IF_EOS, SMBHeader_t::Cmd, CONTINUE_SEARCH, SMBTransactionResponse_t::DataOffset, EACCES, SMBHeader_t::Eclass, SMBHeader_t::Ecode, EINVAL, EIO, FindFirstNext2ResponseParam_t::EndOfSearch, EXT_ATTR_DIRECTORY, SMBHeader_t::Flags, FindFirst2RequestParam_t::Flags, FindNext2RequestParam_t::Flags, SMBHeader_t::Flags2, GetSMBServerReply(), getStringField(), FindFirst2RequestParam_t::LevelOfInterest, FindNext2RequestParam_t::LevelOfInterest, SMBHeader_t::Magic, MAX_SMB_BUF, SMBTransactionRequest_t::MaxDataCount, SMBTransactionRequest_t::MaxParamCount, memset(), nb_SetSessionMessage(), NULL, SMBTransactionRequest_t::ParamCount, SMBTransactionRequest_t::ParamOffset, SMBTransactionResponse_t::ParamOffset, RESUME_SEARCH, FindNext2RequestParam_t::ResumeKey, FindFirst2RequestParam_t::SearchAttributes, FindFirst2RequestParam_t::SearchCount, FindNext2RequestParam_t::SearchCount, FindFirstNext2ResponseParam_t::SearchCount, FindNext2RequestParam_t::SearchID, FindFirstNext2ResponseParam_t::SearchID, FindFirst2RequestParam_t::SearchPattern, FindNext2RequestParam_t::SearchPattern, SERVER_CAP_UNICODE, server_specs, setStringField(), SMBTransactionRequest_t::SetupCount, SMB_buf, SMB_COM_TRANSACTION2, SMB_FIND_FILE_BOTH_DIRECTORY_INFO, SMB_FLAGS2_32BIT_STATUS, SMB_FLAGS2_KNOWS_LONG_NAMES, SMB_FLAGS2_UNICODE_STRING, SMB_FLAGS_CANONICAL_PATHNAMES, SMB_MAGIC, FindFirstNext2Request_t::smbH, FindFirstNext2Response_t::smbH, FindFirstNext2Request_t::smbTrans, FindFirstNext2Response_t::smbTrans, FindFirstNext2Request_t::smbWordcount, STATUS_ACCESS_DENIED, STATUS_SUCCESS, FindFirst2RequestParam_t::StorageType, FindFirstNext2Request_t::SubCommand, SMBHeader_t::TID, TID, SMBTransactionRequest_t::TotalParamCount, TRANS2_FIND_FIRST2, SMBHeader_t::UID, UID, and ZERO_PKT_ALIGNED.
Referenced by smb_dread().
smb_LogOffAndX()
int smb_LogOffAndX (int UID)
Definition at line 1509 of file smb.c.
 {
         int r;
         LogOffAndXRequest_t *LR = &SMB_buf.smb.logOffAndXRequest;
         LogOffAndXResponse_t *LRsp = &SMB_buf.smb.logOffAndXResponse;
         ZERO_PKT_ALIGNED(LR, sizeof(LogOffAndXRequest_t));
         LR->smbH.Magic = SMB_MAGIC;
         LR->smbH.Cmd = SMB_COM_LOGOFF_ANDX;
         LR->smbH.UID = (u16)UID;
         LR->smbWordcount = 2;
         LR->smbAndxCmd = SMB_COM_NONE;          // no ANDX command
         nb_SetSessionMessage(sizeof(LogOffAndXRequest_t));
         r = GetSMBServerReply(0, NULL, 0);
         if (r <= 0)
                 return -EIO;
         // check sanity of SMB header
         if (LRsp->smbH.Magic != SMB_MAGIC)
                 return -EIO;
         // check there's no error
         if ((LRsp->smbH.Eclass | (LRsp->smbH.Ecode << 16)) != STATUS_SUCCESS)
                 return -EIO;
         UID = -1;
         return 0;
 }
References SMBHeader_t::Cmd, SMBHeader_t::Eclass, SMBHeader_t::Ecode, EIO, GetSMBServerReply(), SMBHeader_t::Magic, nb_SetSessionMessage(), NULL, SMB_buf, SMB_COM_LOGOFF_ANDX, SMB_COM_NONE, SMB_MAGIC, LogOffAndXRequest_t::smbAndxCmd, LogOffAndXRequest_t::smbH, LogOffAndXResponse_t::smbH, LogOffAndXRequest_t::smbWordcount, STATUS_SUCCESS, SMBHeader_t::UID, UID, and ZERO_PKT_ALIGNED.
Referenced by smb_LogOff().
smb_ManageDirectory()
int smb_ManageDirectory (int UID, int TID, char * Path, int cmd)
Definition at line 1252 of file smb.c.
 {
         int r, PathLen;
         ManageDirectoryRequest_t *MDR = &SMB_buf.smb.manageDirectoryRequest;
         ManageDirectoryResponse_t *MDRsp = &SMB_buf.smb.manageDirectoryResponse;
         ZERO_PKT_ALIGNED(MDR, sizeof(ManageDirectoryRequest_t));
         MDR->smbH.Magic = SMB_MAGIC;
         MDR->smbH.Cmd = (u8)cmd;
         MDR->smbH.Flags = SMB_FLAGS_CANONICAL_PATHNAMES;
         MDR->smbH.Flags2 = SMB_FLAGS2_KNOWS_LONG_NAMES | SMB_FLAGS2_32BIT_STATUS;
         if (server_specs.Capabilities & SERVER_CAP_UNICODE)
                 MDR->smbH.Flags2 |= SMB_FLAGS2_UNICODE_STRING;
         MDR->smbH.UID = (u16)UID;
         MDR->smbH.TID = (u16)TID;
         MDR->BufferFormat = 0x04;
         // Add path
         PathLen = setStringField(MDR->DirectoryName, Path);
         MDR->ByteCount = PathLen+1;                     // +1 for the BufferFormat byte
         nb_SetSessionMessage(sizeof(ManageDirectoryRequest_t)+PathLen);
         r = GetSMBServerReply(0, NULL, 0);
         if (r <= 0)
                 return -EIO;
         // check sanity of SMB header
         if (MDRsp->smbH.Magic != SMB_MAGIC)
                 return -EIO;
         switch(MDRsp->smbH.Eclass | (MDRsp->smbH.Ecode << 16)){
                 // check there's no error
                 case STATUS_SUCCESS:
                         break;
                 // check if access denied
                 case STATUS_ACCESS_DENIED:
                         return -EACCES;
                 default:
                         return -EIO;
         }
         return 0;
 }
References ManageDirectoryRequest_t::BufferFormat, ManageDirectoryRequest_t::ByteCount, server_specs_t::Capabilities, SMBHeader_t::Cmd, ManageDirectoryRequest_t::DirectoryName, EACCES, SMBHeader_t::Eclass, SMBHeader_t::Ecode, EIO, SMBHeader_t::Flags, SMBHeader_t::Flags2, GetSMBServerReply(), SMBHeader_t::Magic, nb_SetSessionMessage(), NULL, SERVER_CAP_UNICODE, server_specs, setStringField(), SMB_buf, SMB_FLAGS2_32BIT_STATUS, SMB_FLAGS2_KNOWS_LONG_NAMES, SMB_FLAGS2_UNICODE_STRING, SMB_FLAGS_CANONICAL_PATHNAMES, SMB_MAGIC, ManageDirectoryRequest_t::smbH, ManageDirectoryResponse_t::smbH, STATUS_ACCESS_DENIED, STATUS_SUCCESS, SMBHeader_t::TID, TID, SMBHeader_t::UID, UID, and ZERO_PKT_ALIGNED.
Referenced by smb_mkdir(), and smb_rmdir().
smb_NegotiateProtocol()
int smb_NegotiateProtocol (u32 * capabilities)
Definition at line 361 of file smb.c.
 {
         static char *dialect = "NT LM 0.12";
         int r, length, retry_count;
         NegotiateProtocolRequest_t *NPR = &SMB_buf.smb.negotiateProtocolRequest;
         NegotiateProtocolResponse_t *NPRsp = &SMB_buf.smb.negotiateProtocolResponse;
         retry_count = 0;
 negotiate_retry:
         ZERO_PKT_ALIGNED(NPR, sizeof(NegotiateProtocolRequest_t));
         NPR->smbH.Magic = SMB_MAGIC;
         NPR->smbH.Cmd = SMB_COM_NEGOTIATE;
         NPR->smbH.Flags = SMB_FLAGS_CASELESS_PATHNAMES;
         NPR->smbH.Flags2 = SMB_FLAGS2_KNOWS_LONG_NAMES | SMB_FLAGS2_32BIT_STATUS;
         length = strlen(dialect);
         NPR->ByteCount = length + sizeof(NPR->DialectFormat) + 1;
         NPR->DialectFormat = 0x02;
         strcpy(NPR->DialectName, dialect);
         nb_SetSessionMessage(sizeof(NegotiateProtocolRequest_t) + length + 1);
         r = GetSMBServerReply(0, NULL, 0);
         if (r <= 0)
                 goto negotiate_error;
         // check sanity of SMB header
         if (NPRsp->smbH.Magic != SMB_MAGIC)
                 goto negotiate_error;
         // check there's no error
         if (NPRsp->smbH.Eclass != STATUS_SUCCESS)
                 goto negotiate_error;
         if (NPRsp->smbWordcount != 17)
                 goto negotiate_error;
         *capabilities = NPRsp->Capabilities & (CLIENT_CAP_LARGE_WRITEX | CLIENT_CAP_LARGE_READX | CLIENT_CAP_UNICODE | CLIENT_CAP_LARGE_FILES | CLIENT_CAP_STATUS32);
         server_specs.Capabilities = NPRsp->Capabilities;
         server_specs.SecurityMode = (NPRsp->SecurityMode & NEGOTIATE_SECURITY_USER_LEVEL) ? SERVER_USER_SECURITY_LEVEL : SERVER_SHARE_SECURITY_LEVEL;
         server_specs.PasswordType = (NPRsp->SecurityMode & NEGOTIATE_SECURITY_CHALLENGE_RESPONSE) ? SERVER_USE_ENCRYPTED_PASSWORD : SERVER_USE_PLAINTEXT_PASSWORD;
         // copy to global to keep needed information for further communication
         server_specs.MaxBufferSize = NPRsp->MaxBufferSize;
         server_specs.MaxMpxCount = NPRsp->MaxMpxCount;
         server_specs.SessionKey = NPRsp->SessionKey;
         memcpy(server_specs.EncryptionKey, NPRsp->ByteField, NPRsp->KeyLength);
         getStringField(server_specs.PrimaryDomainServerName, &NPRsp->ByteField[NPRsp->KeyLength], 0);
         return 0;
 negotiate_error:
         retry_count++;
         if (retry_count < 3)
                 goto negotiate_retry;
         return -1;
 }
References NegotiateProtocolRequest_t::ByteCount, NegotiateProtocolResponse_t::ByteField, server_specs_t::Capabilities, NegotiateProtocolResponse_t::Capabilities, CLIENT_CAP_LARGE_FILES, CLIENT_CAP_LARGE_READX, CLIENT_CAP_LARGE_WRITEX, CLIENT_CAP_STATUS32, CLIENT_CAP_UNICODE, SMBHeader_t::Cmd, NegotiateProtocolRequest_t::DialectFormat, NegotiateProtocolRequest_t::DialectName, SMBHeader_t::Eclass, server_specs_t::EncryptionKey, SMBHeader_t::Flags, SMBHeader_t::Flags2, GetSMBServerReply(), getStringField(), NegotiateProtocolResponse_t::KeyLength, SMBHeader_t::Magic, server_specs_t::MaxBufferSize, NegotiateProtocolResponse_t::MaxBufferSize, server_specs_t::MaxMpxCount, NegotiateProtocolResponse_t::MaxMpxCount, memcpy(), nb_SetSessionMessage(), NEGOTIATE_SECURITY_CHALLENGE_RESPONSE, NEGOTIATE_SECURITY_USER_LEVEL, NULL, server_specs_t::PasswordType, server_specs_t::PrimaryDomainServerName, server_specs_t::SecurityMode, NegotiateProtocolResponse_t::SecurityMode, SERVER_SHARE_SECURITY_LEVEL, server_specs, SERVER_USE_ENCRYPTED_PASSWORD, SERVER_USE_PLAINTEXT_PASSWORD, SERVER_USER_SECURITY_LEVEL, server_specs_t::SessionKey, NegotiateProtocolResponse_t::SessionKey, SMB_buf, SMB_COM_NEGOTIATE, SMB_FLAGS2_32BIT_STATUS, SMB_FLAGS2_KNOWS_LONG_NAMES, SMB_FLAGS_CASELESS_PATHNAMES, SMB_MAGIC, NegotiateProtocolRequest_t::smbH, NegotiateProtocolResponse_t::smbH, NegotiateProtocolResponse_t::smbWordcount, STATUS_SUCCESS, strcpy(), strlen(), and ZERO_PKT_ALIGNED.
Referenced by smb_LogOn().
smb_NetShareEnum()
int smb_NetShareEnum (int UID, int TID, ShareEntry_t * shareEntries, int index, int maxEntries)
Definition at line 654 of file smb.c.
 {
         int r, i;
         int count = 0;
         NetShareEnumRequest_t *NSER = &SMB_buf.smb.netShareEnumRequest;
         NetShareEnumResponse_t *NSERsp = &SMB_buf.smb.netShareEnumResponse;
         ZERO_PKT_ALIGNED(NSER, sizeof(NetShareEnumRequest_t));
         NSER->smbH.Magic = SMB_MAGIC;
         NSER->smbH.Cmd = SMB_COM_TRANSACTION;
         NSER->smbH.UID = (u16)UID;
         NSER->smbH.TID = (u16)TID;
         NSER->smbWordcount = 14;
         NSER->smbTrans.TotalParamCount = NSER->smbTrans.ParamCount = 19;
         NSER->smbTrans.MaxParamCount = 1024;
         NSER->smbTrans.MaxDataCount = MAX_SMB_BUF - NSER->smbTrans.MaxParamCount;
         NSER->smbTrans.ParamOffset = 76;
         NSER->smbTrans.DataOffset = 95;
         NSER->ByteCount = 32;
         // SMB PIPE PROTOCOL
         // Transaction Name: "\PIPE\LANMAN"
         // Function Code : 0x0000 = NetShareEnum
         // Parameter Descriptor: "WrLeh"
         // Return Descriptor: "B13BWz"
         // Detail Level: 0x0001
         // Receive Buffer Length: 0x1fa0
         memcpy(&NSER->ByteField[0], "\\PIPE\\LANMAN\0\0\0WrLeh\0B13BWz\0\x01\0\xa0\x1f", 32);
         nb_SetSessionMessage(sizeof(NetShareEnumRequest_t) + NSER->ByteCount);
         r = GetSMBServerReply(0, NULL, 0);
         if (r <= 0)
                 return -EIO;
         // check sanity of SMB header
         if (NSERsp->smbH.Magic != SMB_MAGIC)
                 return -EIO;
         switch(NSERsp->smbH.Eclass | (NSERsp->smbH.Ecode << 16)){
                 // check there's no error
                 case STATUS_SUCCESS:
                         break;
                 // check if access denied
                 case STATUS_ACCESS_DENIED:
                         return -EACCES;
                 default:
                         return -EIO;
         }
         // API status must be 0
         if (SMB_buf.smb.u16buff[NSERsp->smbTrans.ParamOffset / sizeof(u16)] != 0)
                 return -EIO;
         // available entries
         int AvailableEntries = SMB_buf.smb.s16buff[(NSERsp->smbTrans.ParamOffset+6) / sizeof(s16)];
         // data start
         char *data = (char *)&SMB_buf.smb.u8buff[NSERsp->smbTrans.DataOffset];
         char *p = data;
         for (i=0; i<AvailableEntries; i++) {
                 // calculate the padding after the Share name
                 int padding = (strlen(p)+1+2) % 16 ? 16-((strlen(p)+1) % 16) : 0;
                 if (*((u16 *)&p[strlen(p)+1+padding-2]) == 0) { // Directory Tree type
                         if (maxEntries > 0) {
                                 if ((count < maxEntries) && (i >= index)) {
                                         count++;
                                         strncpy(shareEntries->ShareName, p, 256);
                                         strncpy(shareEntries->ShareComment, &data[*((u16 *)&p[strlen(p)+1+padding])], 256);
                                         shareEntries++;
                                 }
                         }
                         else // if maxEntries is 0 then we're just counting shares
                                 count++;
                 }
                 p += strlen(p)+1+padding+4;
         }
         return count;
 }
References NetShareEnumRequest_t::ByteCount, NetShareEnumRequest_t::ByteField, SMBHeader_t::Cmd, SMBTransactionRequest_t::DataOffset, SMBTransactionResponse_t::DataOffset, EACCES, SMBHeader_t::Eclass, SMBHeader_t::Ecode, EIO, GetSMBServerReply(), index(), SMBHeader_t::Magic, MAX_SMB_BUF, SMBTransactionRequest_t::MaxDataCount, SMBTransactionRequest_t::MaxParamCount, memcpy(), nb_SetSessionMessage(), NULL, SMBTransactionRequest_t::ParamCount, SMBTransactionRequest_t::ParamOffset, SMBTransactionResponse_t::ParamOffset, ShareEntry_t::ShareComment, ShareEntry_t::ShareName, SMB_buf, SMB_COM_TRANSACTION, SMB_MAGIC, NetShareEnumRequest_t::smbH, NetShareEnumResponse_t::smbH, NetShareEnumRequest_t::smbTrans, NetShareEnumResponse_t::smbTrans, NetShareEnumRequest_t::smbWordcount, STATUS_ACCESS_DENIED, STATUS_SUCCESS, strlen(), strncpy(), SMBHeader_t::TID, TID, SMBTransactionRequest_t::TotalParamCount, SMBHeader_t::UID, UID, and ZERO_PKT_ALIGNED.
Referenced by smb_GetShareList().
smb_NTCreateAndX()
int smb_NTCreateAndX (int UID, int TID, char * filename, s64 * filesize, int mode)
Definition at line 876 of file smb.c.
 {
         NTCreateAndXRequest_t *NTCR = &SMB_buf.smb.ntCreateAndXRequest;
         NTCreateAndXResponse_t *NTCRsp = &SMB_buf.smb.ntCreateAndXResponse;
         int r, offset;
         ZERO_PKT_ALIGNED(NTCR, sizeof(NTCreateAndXRequest_t));
         NTCR->smbH.Magic = SMB_MAGIC;
         NTCR->smbH.Cmd = SMB_COM_NT_CREATE_ANDX;
         NTCR->smbH.Flags = SMB_FLAGS_CANONICAL_PATHNAMES;
         NTCR->smbH.Flags2 = SMB_FLAGS2_KNOWS_LONG_NAMES | SMB_FLAGS2_32BIT_STATUS;
         if (server_specs.Capabilities & SERVER_CAP_UNICODE)
                 NTCR->smbH.Flags2 |= SMB_FLAGS2_UNICODE_STRING;
         NTCR->smbH.UID = (u16)UID;
         NTCR->smbH.TID = (u16)TID;
         NTCR->smbWordcount = 24;
         NTCR->smbAndxCmd = SMB_COM_NONE;        // no ANDX command
         NTCR->AccessMask = ((mode & O_RDWR) == O_RDWR || (mode & O_WRONLY)) ? 0x2019f : 0x20089;
         NTCR->FileAttributes = ((mode & O_RDWR) == O_RDWR || (mode & O_WRONLY)) ? EXT_ATTR_NORMAL : EXT_ATTR_READONLY;
         NTCR->ShareAccess = 0x01; // Share in read mode only
         if (mode & O_CREAT)
                 NTCR->CreateDisposition |= 0x02;
         if (mode & O_TRUNC)
                 NTCR->CreateDisposition |= 0x04;
         else
                 NTCR->CreateDisposition |= 0x01;
         if (NTCR->CreateDisposition == 0x06)
                 NTCR->CreateDisposition = 0x05;
         NTCR->ImpersonationLevel = 2;
         NTCR->SecurityFlags = 0x03;
         offset = 0;
         if (server_specs.Capabilities & SERVER_CAP_UNICODE)
         {
                 NTCR->ByteField[offset] = '\0';
                 offset++;                               // pad needed only for unicode as aligment fix
         }
         // Add filename
         NTCR->NameLength = setStringField(&NTCR->ByteField[offset], filename);
         offset += NTCR->NameLength;
         NTCR->ByteCount = offset;
         nb_SetSessionMessage(sizeof(NTCreateAndXRequest_t) + offset + 1);
         r = GetSMBServerReply(0, NULL, 0);
         if (r <= 0)
                 return -EIO;
         // check sanity of SMB header
         if (NTCRsp->smbH.Magic != SMB_MAGIC)
                 return -EIO;
         switch(NTCRsp->smbH.Eclass | (NTCRsp->smbH.Ecode << 16)){
                 // check there's no error
                 case STATUS_SUCCESS:
                         break;
                 // check if access denied
                 case STATUS_ACCESS_DENIED:
                         return -EACCES;
                 default:
                         return -EIO;
         }
         *filesize = NTCRsp->FileSize;
         return (int)NTCRsp->FID;
 }
References NTCreateAndXRequest_t::AccessMask, NTCreateAndXRequest_t::ByteCount, NTCreateAndXRequest_t::ByteField, server_specs_t::Capabilities, SMBHeader_t::Cmd, NTCreateAndXRequest_t::CreateDisposition, EACCES, SMBHeader_t::Eclass, SMBHeader_t::Ecode, EIO, EXT_ATTR_NORMAL, EXT_ATTR_READONLY, NTCreateAndXResponse_t::FID, NTCreateAndXRequest_t::FileAttributes, NTCreateAndXResponse_t::FileSize, SMBHeader_t::Flags, SMBHeader_t::Flags2, GetSMBServerReply(), NTCreateAndXRequest_t::ImpersonationLevel, SMBHeader_t::Magic, NTCreateAndXRequest_t::NameLength, nb_SetSessionMessage(), NULL, O_CREAT, O_RDWR, O_TRUNC, O_WRONLY, NTCreateAndXRequest_t::SecurityFlags, SERVER_CAP_UNICODE, server_specs, setStringField(), NTCreateAndXRequest_t::ShareAccess, SMB_buf, SMB_COM_NONE, SMB_COM_NT_CREATE_ANDX, SMB_FLAGS2_32BIT_STATUS, SMB_FLAGS2_KNOWS_LONG_NAMES, SMB_FLAGS2_UNICODE_STRING, SMB_FLAGS_CANONICAL_PATHNAMES, SMB_MAGIC, NTCreateAndXRequest_t::smbAndxCmd, NTCreateAndXRequest_t::smbH, NTCreateAndXResponse_t::smbH, NTCreateAndXRequest_t::smbWordcount, STATUS_ACCESS_DENIED, STATUS_SUCCESS, SMBHeader_t::TID, TID, SMBHeader_t::UID, UID, and ZERO_PKT_ALIGNED.
Referenced by smb_OpenAndX().
smb_OpenAndX()
int smb_OpenAndX (int UID, int TID, char * filename, s64 * filesize, int mode)
Definition at line 947 of file smb.c.
 {
         // does not supports filesize > 4Gb, so we'll have to use
         // smb_QueryPathInformation to find the real size.
         // OpenAndX is needed for a few NAS units that doesn't supports
         // NT SMB commands set.
         PathInformation_t info;
         OpenAndXRequest_t *OR = &SMB_buf.smb.openAndXRequest;
         OpenAndXResponse_t *ORsp = &SMB_buf.smb.openAndXResponse;
         int r, offset;
         if (server_specs.Capabilities & SERVER_CAP_NT_SMBS)
                 return smb_NTCreateAndX(UID, TID, filename, filesize, mode);
         ZERO_PKT_ALIGNED(OR, sizeof(OpenAndXRequest_t));
         OR->smbH.Magic = SMB_MAGIC;
         OR->smbH.Cmd = SMB_COM_OPEN_ANDX;
         OR->smbH.Flags = SMB_FLAGS_CANONICAL_PATHNAMES;
         OR->smbH.Flags2 = SMB_FLAGS2_KNOWS_LONG_NAMES | SMB_FLAGS2_32BIT_STATUS;
         if (server_specs.Capabilities & SERVER_CAP_UNICODE)
                 OR->smbH.Flags2 |= SMB_FLAGS2_UNICODE_STRING;
         OR->smbH.UID = (u16)UID;
         OR->smbH.TID = (u16)TID;
         OR->smbWordcount = 15;
         OR->smbAndxCmd = SMB_COM_NONE;          // no ANDX command
         OR->AccessMask = ((mode & O_RDWR) == O_RDWR || (mode & O_WRONLY)) ? 0x02 : 0x00;
         OR->FileAttributes = ((mode & O_RDWR) == O_RDWR || (mode & O_WRONLY)) ? EXT_ATTR_NORMAL : EXT_ATTR_READONLY;
         if (mode & O_CREAT)
                 OR->CreateOptions |= 0x10;
         if (mode & O_TRUNC)
                 OR->CreateOptions |= 0x02;
         else
                 OR->CreateOptions |= 0x01;
         offset = 0;
         if (server_specs.Capabilities & SERVER_CAP_UNICODE)
         {
                 OR->ByteField[offset] = '\0';
                 offset++;                               // pad needed only for unicode as aligment fix
         }
         // Add filename
         offset += setStringField(&OR->ByteField[offset], filename);
         OR->ByteCount = offset;
         nb_SetSessionMessage(sizeof(OpenAndXRequest_t) + offset + 1);
         r = GetSMBServerReply(0, NULL, 0);
         if (r <= 0)
                 return -EIO;
         // check sanity of SMB header
         if (ORsp->smbH.Magic != SMB_MAGIC)
                 return -EIO;
         switch(ORsp->smbH.Eclass | (ORsp->smbH.Ecode << 16)){
                 // check there's no error
                 case STATUS_SUCCESS:
                         break;
                 // check if access denied
                 case STATUS_ACCESS_DENIED:
                         return -EACCES;
                 default:
                         return -EIO;
         }
         r = (int)ORsp->FID;
         if(smb_QueryPathInformation(UID, TID, &info, filename) >= 0)
                 *filesize = info.EndOfFile;
         else
                 r = -1;
         return r;
 }
References OpenAndXRequest_t::AccessMask, OpenAndXRequest_t::ByteCount, OpenAndXRequest_t::ByteField, server_specs_t::Capabilities, SMBHeader_t::Cmd, OpenAndXRequest_t::CreateOptions, EACCES, SMBHeader_t::Eclass, SMBHeader_t::Ecode, EIO, EXT_ATTR_NORMAL, EXT_ATTR_READONLY, OpenAndXResponse_t::FID, OpenAndXRequest_t::FileAttributes, SMBHeader_t::Flags, SMBHeader_t::Flags2, GetSMBServerReply(), SMBHeader_t::Magic, nb_SetSessionMessage(), NULL, O_CREAT, O_RDWR, O_TRUNC, O_WRONLY, SERVER_CAP_NT_SMBS, SERVER_CAP_UNICODE, server_specs, setStringField(), SMB_buf, SMB_COM_NONE, SMB_COM_OPEN_ANDX, SMB_FLAGS2_32BIT_STATUS, SMB_FLAGS2_KNOWS_LONG_NAMES, SMB_FLAGS2_UNICODE_STRING, SMB_FLAGS_CANONICAL_PATHNAMES, SMB_MAGIC, smb_NTCreateAndX(), smb_QueryPathInformation(), OpenAndXRequest_t::smbAndxCmd, OpenAndXRequest_t::smbH, OpenAndXResponse_t::smbH, OpenAndXRequest_t::smbWordcount, STATUS_ACCESS_DENIED, STATUS_SUCCESS, SMBHeader_t::TID, TID, SMBHeader_t::UID, UID, and ZERO_PKT_ALIGNED.
Referenced by smb_open().
smb_QueryInformationDisk()
int smb_QueryInformationDisk (int UID, int TID, smbQueryDiskInfo_out_t * QueryInformationDisk)
Definition at line 741 of file smb.c.
 {
         int r;
         QueryInformationDiskRequest_t *QIDR = &SMB_buf.smb.queryInformationDiskRequest;
         QueryInformationDiskResponse_t *QIDRsp = &SMB_buf.smb.queryInformationDiskResponse;
         ZERO_PKT_ALIGNED(QIDR, sizeof(QueryInformationDiskRequest_t));
         QIDR->smbH.Magic = SMB_MAGIC;
         QIDR->smbH.Cmd = SMB_COM_QUERY_INFORMATION_DISK;
         QIDR->smbH.UID = (u16)UID;
         QIDR->smbH.TID = (u16)TID;
         nb_SetSessionMessage(sizeof(QueryInformationDiskRequest_t));
         r = GetSMBServerReply(0, NULL, 0);
         if (r <= 0)
                 return -EIO;
         // check sanity of SMB header
         if (QIDRsp->smbH.Magic != SMB_MAGIC)
                 return -EIO;
         switch(QIDRsp->smbH.Eclass | (QIDRsp->smbH.Ecode << 16)){
                 // check there's no error
                 case STATUS_SUCCESS:
                         break;
                 // check if access denied
                 case STATUS_ACCESS_DENIED:
                         return -EACCES;
                 default:
                         return -EIO;
         }
         QueryInformationDisk->TotalUnits = QIDRsp->TotalUnits;
         QueryInformationDisk->BlocksPerUnit = QIDRsp->BlocksPerUnit;
         QueryInformationDisk->BlockSize = QIDRsp->BlockSize;
         QueryInformationDisk->FreeUnits = QIDRsp->FreeUnits;
         return 0;
 }
References smbQueryDiskInfo_out_t::BlockSize, QueryInformationDiskResponse_t::BlockSize, smbQueryDiskInfo_out_t::BlocksPerUnit, QueryInformationDiskResponse_t::BlocksPerUnit, SMBHeader_t::Cmd, EACCES, SMBHeader_t::Eclass, SMBHeader_t::Ecode, EIO, smbQueryDiskInfo_out_t::FreeUnits, QueryInformationDiskResponse_t::FreeUnits, GetSMBServerReply(), SMBHeader_t::Magic, nb_SetSessionMessage(), NULL, SMB_buf, SMB_COM_QUERY_INFORMATION_DISK, SMB_MAGIC, QueryInformationDiskRequest_t::smbH, QueryInformationDiskResponse_t::smbH, STATUS_ACCESS_DENIED, STATUS_SUCCESS, SMBHeader_t::TID, TID, smbQueryDiskInfo_out_t::TotalUnits, QueryInformationDiskResponse_t::TotalUnits, SMBHeader_t::UID, UID, and ZERO_PKT_ALIGNED.
Referenced by smb_QueryDiskInfo().
smb_QueryPathInformation()
int smb_QueryPathInformation (int UID, int TID, PathInformation_t * Info, char * Path)
Definition at line 783 of file smb.c.
 {
         int r, PathLen, queryType;
         QueryPathInformationRequest_t *QPIR = &SMB_buf.smb.queryPathInformationRequest;
         QueryPathInformationResponse_t *QPIRsp = &SMB_buf.smb.queryPathInformationResponse;
         queryType = SMB_QUERY_FILE_BASIC_INFO;
 query:
         ZERO_PKT_ALIGNED(QPIR, sizeof(QueryPathInformationRequest_t));
         QPIR->smbH.Magic = SMB_MAGIC;
         QPIR->smbH.Cmd = SMB_COM_TRANSACTION2;
         QPIR->smbH.Flags = SMB_FLAGS_CANONICAL_PATHNAMES;
         QPIR->smbH.Flags2 = SMB_FLAGS2_KNOWS_LONG_NAMES | SMB_FLAGS2_32BIT_STATUS;
         if (server_specs.Capabilities & SERVER_CAP_UNICODE)
                 QPIR->smbH.Flags2 |= SMB_FLAGS2_UNICODE_STRING;
         QPIR->smbH.UID = (u16)UID;
         QPIR->smbH.TID = (u16)TID;
         QPIR->smbWordcount = 15;
         QPIR->smbTrans.SetupCount = 1;
         QPIR->SubCommand = TRANS2_QUERY_PATH_INFORMATION;
         QPIR->smbTrans.ParamOffset = 68;
         QPIR->smbTrans.MaxParamCount = 256;                                             // Max Parameters len in reply
         QPIR->smbTrans.MaxDataCount = MAX_SMB_BUF - QPIR->smbTrans.MaxParamCount;       // Max Data len in reply
         QueryPathInformationRequestParam_t *QPIRParam = (QueryPathInformationRequestParam_t *)&SMB_buf.smb.u8buff[QPIR->smbTrans.ParamOffset];
         QPIRParam->LevelOfInterest = queryType;
         QPIRParam->Reserved = 0;
         // Add path
         PathLen = setStringField(QPIRParam->FileName, Path);
         QPIR->smbTrans.TotalParamCount = QPIR->smbTrans.ParamCount = 2+4+PathLen;
         QPIR->ByteCount = 3 + QPIR->smbTrans.TotalParamCount;
         QPIR->smbTrans.DataOffset = QPIR->smbTrans.ParamOffset + QPIR->smbTrans.TotalParamCount;
         nb_SetSessionMessage(QPIR->smbTrans.DataOffset);
         r = GetSMBServerReply(0, NULL, 0);
         if (r <= 0)
                 return -EIO;
         // check sanity of SMB header
         if (QPIRsp->smbH.Magic != SMB_MAGIC)
                 return -EIO;
         // check there's no error
         switch(QPIRsp->smbH.Eclass | (QPIRsp->smbH.Ecode << 16)){
                 // check there's no error
                 case STATUS_SUCCESS:
                         break;
                 // check if access denied
                 case STATUS_ACCESS_DENIED:
                         return -EACCES;
                 default:
                         return -EIO;
         }
         if (queryType == SMB_QUERY_FILE_BASIC_INFO) {
                 BasicFileInfo_t *BFI = (BasicFileInfo_t *)&SMB_buf.smb.u8buff[QPIRsp->smbTrans.DataOffset];
                 Info->Created = BFI->Created;
                 Info->LastAccess = BFI->LastAccess;
                 Info->LastWrite = BFI->LastWrite;
                 Info->Change = BFI->Change;
                 Info->FileAttributes = BFI->FileAttributes;
                 // a 2nd query is done with SMB_QUERY_FILE_STANDARD_INFO LevelOfInterest to get a valid 64bit size
                 queryType = SMB_QUERY_FILE_STANDARD_INFO;
                 goto query;
         }
         else if (queryType == SMB_QUERY_FILE_STANDARD_INFO) {
                 StandardFileInfo_t *SFI = (StandardFileInfo_t *)&SMB_buf.smb.u8buff[QPIRsp->smbTrans.DataOffset];
                 Info->AllocationSize = SFI->AllocationSize;
                 Info->EndOfFile = SFI->EndOfFile;
                 Info->LinkCount = SFI->LinkCount;
                 Info->DeletePending = SFI->DeletePending;
                 Info->IsDirectory = SFI->IsDirectory;
         }
         return 0;
 }
References PathInformation_t::AllocationSize, StandardFileInfo_t::AllocationSize, QueryPathInformationRequest_t::ByteCount, server_specs_t::Capabilities, PathInformation_t::Change, BasicFileInfo_t::Change, SMBHeader_t::Cmd, PathInformation_t::Created, BasicFileInfo_t::Created, SMBTransactionRequest_t::DataOffset, SMBTransactionResponse_t::DataOffset, PathInformation_t::DeletePending, StandardFileInfo_t::DeletePending, EACCES, SMBHeader_t::Eclass, SMBHeader_t::Ecode, EIO, PathInformation_t::EndOfFile, StandardFileInfo_t::EndOfFile, PathInformation_t::FileAttributes, BasicFileInfo_t::FileAttributes, QueryPathInformationRequestParam_t::FileName, SMBHeader_t::Flags, SMBHeader_t::Flags2, GetSMBServerReply(), PathInformation_t::IsDirectory, StandardFileInfo_t::IsDirectory, PathInformation_t::LastAccess, BasicFileInfo_t::LastAccess, PathInformation_t::LastWrite, BasicFileInfo_t::LastWrite, QueryPathInformationRequestParam_t::LevelOfInterest, PathInformation_t::LinkCount, StandardFileInfo_t::LinkCount, SMBHeader_t::Magic, MAX_SMB_BUF, SMBTransactionRequest_t::MaxDataCount, SMBTransactionRequest_t::MaxParamCount, nb_SetSessionMessage(), NULL, SMBTransactionRequest_t::ParamCount, SMBTransactionRequest_t::ParamOffset, QueryPathInformationRequestParam_t::Reserved, SERVER_CAP_UNICODE, server_specs, setStringField(), SMBTransactionRequest_t::SetupCount, SMB_buf, SMB_COM_TRANSACTION2, SMB_FLAGS2_32BIT_STATUS, SMB_FLAGS2_KNOWS_LONG_NAMES, SMB_FLAGS2_UNICODE_STRING, SMB_FLAGS_CANONICAL_PATHNAMES, SMB_MAGIC, SMB_QUERY_FILE_BASIC_INFO, SMB_QUERY_FILE_STANDARD_INFO, QueryPathInformationRequest_t::smbH, QueryPathInformationResponse_t::smbH, QueryPathInformationRequest_t::smbTrans, QueryPathInformationResponse_t::smbTrans, QueryPathInformationRequest_t::smbWordcount, STATUS_ACCESS_DENIED, STATUS_SUCCESS, QueryPathInformationRequest_t::SubCommand, SMBHeader_t::TID, TID, SMBTransactionRequest_t::TotalParamCount, TRANS2_QUERY_PATH_INFORMATION, SMBHeader_t::UID, UID, and ZERO_PKT_ALIGNED.
Referenced by smb_chdir(), smb_dopen(), smb_getstat(), smb_OpenAndX(), and smb_rmdir().
smb_ReadAndX()
int smb_ReadAndX (int UID, int TID, int FID, s64 fileoffset, void * readbuf, int nbytes)
Definition at line 1025 of file smb.c.
 {
         ReadAndXRequest_t *RR = &SMB_buf.smb.readAndXRequest;
         ReadAndXResponse_t *RRsp = &SMB_buf.smb.readAndXResponse;
         int r, padding, DataLength;
         ZERO_PKT_ALIGNED(RR, sizeof(ReadAndXRequest_t));
         RR->smbH.Magic = SMB_MAGIC;
         RR->smbH.Flags2 = SMB_FLAGS2_32BIT_STATUS;
         RR->smbH.Cmd = SMB_COM_READ_ANDX;
         RR->smbH.UID = (u16)UID;
         RR->smbH.TID = (u16)TID;
         RR->smbWordcount = 12;
         RR->smbAndxCmd = SMB_COM_NONE;          // no ANDX command
         RR->FID = (u16)FID;
         RR->OffsetLow = (u32)(fileoffset & 0xffffffff);
         RR->OffsetHigh = (u32)((fileoffset >> 32) & 0xffffffff);
         RR->MaxCountLow = (u16)nbytes;
         RR->MaxCountHigh = (u16)(nbytes >> 16);
         nb_SetSessionMessage(sizeof(ReadAndXRequest_t));
         r = GetSMBServerReply(0, NULL, sizeof(ReadAndXResponse_t));
         if (r <= 0)
                 return -EIO;
         // check sanity of SMB header
         if (RRsp->smbH.Magic != SMB_MAGIC)
                 return -EIO;
         // check there's no error
         if ((RRsp->smbH.Eclass | (RRsp->smbH.Ecode << 16)) != STATUS_SUCCESS)
                 return -EIO;
         //Skip any padding bytes.
         padding = RRsp->DataOffset - sizeof(ReadAndXResponse_t);
         if (padding > 0)
         {
                 r = RecvData(main_socket, (char *)(RRsp + 1), padding, 3000); // 3s before the packet is considered lost
                 if (r <= 0)
                         return -2;
         }
         DataLength = (int)(((u32)RRsp->DataLengthHigh << 16) | RRsp->DataLengthLow);
         if (DataLength > 0)
         {
                 r = RecvData(main_socket, readbuf, DataLength, 3000); // 3s before the packet is considered lost
                 if (r <= 0)
                         return -2;
         }
         r = DataLength;
         return r;
 }
References SMBHeader_t::Cmd, ReadAndXResponse_t::DataLengthHigh, ReadAndXResponse_t::DataLengthLow, ReadAndXResponse_t::DataOffset, SMBHeader_t::Eclass, SMBHeader_t::Ecode, EIO, ReadAndXRequest_t::FID, SMBHeader_t::Flags2, GetSMBServerReply(), SMBHeader_t::Magic, main_socket, ReadAndXRequest_t::MaxCountHigh, ReadAndXRequest_t::MaxCountLow, nb_SetSessionMessage(), NULL, ReadAndXRequest_t::OffsetHigh, ReadAndXRequest_t::OffsetLow, RecvData(), SMB_buf, SMB_COM_NONE, SMB_COM_READ_ANDX, SMB_FLAGS2_32BIT_STATUS, SMB_MAGIC, ReadAndXRequest_t::smbAndxCmd, ReadAndXRequest_t::smbH, ReadAndXResponse_t::smbH, ReadAndXRequest_t::smbWordcount, STATUS_SUCCESS, SMBHeader_t::TID, TID, SMBHeader_t::UID, UID, and ZERO_PKT_ALIGNED.
Referenced by smb_ReadFile().
smb_ReadFile()
int smb_ReadFile (int UID, int TID, int FID, s64 fileoffset, void * readbuf, int nbytes)
Definition at line 1081 of file smb.c.
 {
         int result, remaining, toRead;
         char *ptr;
         s64 pos;
         remaining = nbytes;
         ptr = readbuf;
         pos = fileoffset;
         while (remaining > 0)
         {
                 toRead = remaining > CLIENT_MAX_XFER_SIZE ? CLIENT_MAX_XFER_SIZE : remaining;
                 result = smb_ReadAndX(UID, TID, FID, pos, ptr, toRead);
                 if (result <= 0)
                         return result;
                 pos += result;
                 ptr += result;
                 remaining -= result;
         }
         return nbytes;
 }
References CLIENT_MAX_XFER_SIZE, pos, result, smb_ReadAndX(), TID, and UID.
Referenced by smb_read().
smb_Rename()
int smb_Rename (int UID, int TID, char * oldPath, char * newPath)
Definition at line 1299 of file smb.c.
 {
         int r, offset;
         RenameRequest_t *RR = &SMB_buf.smb.renameRequest;
         RenameResponse_t *RRsp = &SMB_buf.smb.renameResponse;
         ZERO_PKT_ALIGNED(RR, sizeof(RenameRequest_t));
         RR->smbH.Magic = SMB_MAGIC;
         RR->smbH.Cmd = SMB_COM_RENAME;
         RR->smbH.Flags = SMB_FLAGS_CANONICAL_PATHNAMES;
         RR->smbH.Flags2 = SMB_FLAGS2_KNOWS_LONG_NAMES | SMB_FLAGS2_32BIT_STATUS;
         if (server_specs.Capabilities & SERVER_CAP_UNICODE)
                 RR->smbH.Flags2 |= SMB_FLAGS2_UNICODE_STRING;
         RR->smbH.UID = (u16)UID;
         RR->smbH.TID = (u16)TID;
         RR->smbWordcount = 1;
         // NOTE: on samba seems it doesn't care of attribute to rename directories
         // to be tested on windows
         RR->SearchAttributes = 0; // coud be other attributes to find Hidden/System files /Directories
         offset = 0;
         // Add oldPath
         RR->ByteField[offset] = 0x04;                   // BufferFormat
         offset++;
         offset += setStringField(&RR->ByteField[offset], oldPath);
         // Add newPath
         RR->ByteField[offset] = 0x04;                   // BufferFormat
         offset++;
         if (server_specs.Capabilities & SERVER_CAP_UNICODE)
         {
                 RR->ByteField[offset] = '\0';
                 offset++;                               // pad needed for unicode
         }
         offset += setStringField(&RR->ByteField[offset], newPath);
         RR->ByteCount = offset;
         nb_SetSessionMessage(sizeof(RenameRequest_t) + offset);
         r = GetSMBServerReply(0, NULL, 0);
         if (r <= 0)
                 return -EIO;
         // check sanity of SMB header
         if (RRsp->smbH.Magic != SMB_MAGIC)
                 return -EIO;
         // check there's no error
         switch(RRsp->smbH.Eclass | (RRsp->smbH.Ecode << 16)){
                 // check there's no error
                 case STATUS_SUCCESS:
                         break;
                 // check if access denied
                 case STATUS_ACCESS_DENIED:
                         return -EACCES;
                 default:
                         return -EIO;
         }
         return 0;
 }
References RenameRequest_t::ByteCount, RenameRequest_t::ByteField, server_specs_t::Capabilities, SMBHeader_t::Cmd, EACCES, SMBHeader_t::Eclass, SMBHeader_t::Ecode, EIO, SMBHeader_t::Flags, SMBHeader_t::Flags2, GetSMBServerReply(), SMBHeader_t::Magic, nb_SetSessionMessage(), NULL, RenameRequest_t::SearchAttributes, SERVER_CAP_UNICODE, server_specs, setStringField(), SMB_buf, SMB_COM_RENAME, SMB_FLAGS2_32BIT_STATUS, SMB_FLAGS2_KNOWS_LONG_NAMES, SMB_FLAGS2_UNICODE_STRING, SMB_FLAGS_CANONICAL_PATHNAMES, SMB_MAGIC, RenameRequest_t::smbH, RenameResponse_t::smbH, RenameRequest_t::smbWordcount, STATUS_ACCESS_DENIED, STATUS_SUCCESS, SMBHeader_t::TID, TID, SMBHeader_t::UID, UID, and ZERO_PKT_ALIGNED.
Referenced by smb_rename().
smb_SessionSetupAndX()
int smb_SessionSetupAndX (char * User, char * Password, int PasswordType, u32 capabilities)
Definition at line 481 of file smb.c.
 {
         SessionSetupAndXRequest_t *SSR = &SMB_buf.smb.sessionSetupAndXRequest;
         SessionSetupAndXResponse_t *SSRsp = &SMB_buf.smb.sessionSetupAndXResponse;
         int r, offset, useUnicode;
         int passwordlen = 0;
         int AuthType = NTLM_AUTH;
 lbl_session_setup:
         ZERO_PKT_ALIGNED(SSR, sizeof(SessionSetupAndXRequest_t));
         useUnicode = (server_specs.Capabilities & SERVER_CAP_UNICODE) ? 1 : 0;
         SSR->smbH.Magic = SMB_MAGIC;
         SSR->smbH.Cmd = SMB_COM_SESSION_SETUP_ANDX;
         SSR->smbH.Flags = SMB_FLAGS_CASELESS_PATHNAMES;
         SSR->smbH.Flags2 = SMB_FLAGS2_KNOWS_LONG_NAMES | SMB_FLAGS2_32BIT_STATUS;
         if (useUnicode)
                 SSR->smbH.Flags2 |= SMB_FLAGS2_UNICODE_STRING;
         SSR->smbWordcount = 13;
         SSR->smbAndxCmd = SMB_COM_NONE;         // no ANDX command
         SSR->MaxBufferSize = CLIENT_MAX_BUFFER_SIZE;
         SSR->MaxMpxCount = server_specs.MaxMpxCount >= 2 ? 2 : (u16)server_specs.MaxMpxCount;
         SSR->VCNumber = 1;
         SSR->SessionKey = server_specs.SessionKey;
         SSR->Capabilities = capabilities;
         // Fill ByteField
         offset = 0;
         if (server_specs.SecurityMode == SERVER_USER_SECURITY_LEVEL) {
                 passwordlen = AddPassword(Password, PasswordType, AuthType, &SSR->AnsiPasswordLength, &SSR->UnicodePasswordLength, &SSR->ByteField[0]);
                 offset += passwordlen;
         }
         if ((useUnicode) && (!(passwordlen & 1)))
         {
                 SSR->ByteField[offset] = '\0';
                 offset++;                               // pad needed only for unicode as aligment fix if password length is even
         }
         // Add User name
         offset += setStringField(&SSR->ByteField[offset], User);
         // PrimaryDomain, acquired from Negotiate Protocol Response data
         offset += setStringField(&SSR->ByteField[offset], server_specs.PrimaryDomainServerName);
         // NativeOS
         if (useUnicode && ((offset & 1) != 0))
         {       //If Unicode is used, the field must begin on a 16-bit aligned address.
                 SSR->ByteField[offset] = '\0';
                 offset++;
         }
         offset += setStringField(&SSR->ByteField[offset], "PlayStation 2");
         // NativeLanMan
         if (useUnicode && ((offset & 1) != 0))
         {       //If Unicode is used, the field must begin on a 16-bit aligned address.
                 SSR->ByteField[offset] = '\0';
                 offset++;
         }
         offset += setStringField(&SSR->ByteField[offset], "SMBMAN");
         SSR->ByteCount = offset;
         nb_SetSessionMessage(sizeof(SessionSetupAndXRequest_t)+offset);
         r = GetSMBServerReply(0, NULL, 0);
         if (r <= 0)
                 return -EIO;
         // check sanity of SMB header
         if (SSRsp->smbH.Magic != SMB_MAGIC)
                 return -EIO;
         // check there's no error (NT STATUS error type!)
         switch(SSRsp->smbH.Eclass | (SSRsp->smbH.Ecode << 16)){
                 case STATUS_SUCCESS:
                         break;
                 case STATUS_LOGON_FAILURE:      // check there's no auth failure
                         if ((server_specs.SecurityMode == SERVER_USER_SECURITY_LEVEL)
                                 && (AuthType == NTLM_AUTH)) {
                                 AuthType = LM_AUTH;
                                 goto lbl_session_setup;
                         }
                         return -EACCES;
                 default:
                         return -EIO;
         }
         // return UID
         return (int)SSRsp->smbH.UID;
 }
References AddPassword(), SessionSetupAndXRequest_t::AnsiPasswordLength, SessionSetupAndXRequest_t::ByteCount, SessionSetupAndXRequest_t::ByteField, server_specs_t::Capabilities, SessionSetupAndXRequest_t::Capabilities, CLIENT_MAX_BUFFER_SIZE, SMBHeader_t::Cmd, EACCES, SMBHeader_t::Eclass, SMBHeader_t::Ecode, EIO, SMBHeader_t::Flags, SMBHeader_t::Flags2, GetSMBServerReply(), LM_AUTH, SMBHeader_t::Magic, SessionSetupAndXRequest_t::MaxBufferSize, server_specs_t::MaxMpxCount, SessionSetupAndXRequest_t::MaxMpxCount, nb_SetSessionMessage(), NTLM_AUTH, NULL, server_specs_t::PrimaryDomainServerName, server_specs_t::SecurityMode, SERVER_CAP_UNICODE, server_specs, SERVER_USER_SECURITY_LEVEL, server_specs_t::SessionKey, SessionSetupAndXRequest_t::SessionKey, setStringField(), SMB_buf, SMB_COM_NONE, SMB_COM_SESSION_SETUP_ANDX, SMB_FLAGS2_32BIT_STATUS, SMB_FLAGS2_KNOWS_LONG_NAMES, SMB_FLAGS2_UNICODE_STRING, SMB_FLAGS_CASELESS_PATHNAMES, SMB_MAGIC, SessionSetupAndXRequest_t::smbAndxCmd, SessionSetupAndXRequest_t::smbH, SessionSetupAndXResponse_t::smbH, SessionSetupAndXRequest_t::smbWordcount, STATUS_LOGON_FAILURE, STATUS_SUCCESS, SMBHeader_t::UID, SessionSetupAndXRequest_t::UnicodePasswordLength, SessionSetupAndXRequest_t::VCNumber, and ZERO_PKT_ALIGNED.
Referenced by smb_LogOn().
smb_TreeConnectAndX()
int smb_TreeConnectAndX (int UID, char * ShareName, char * Password, int PasswordType)
Definition at line 577 of file smb.c.
 {
         TreeConnectAndXRequest_t *TCR = &SMB_buf.smb.treeConnectAndXRequest;
         TreeConnectAndXResponse_t *TCRsp = &SMB_buf.smb.treeConnectAndXResponse;
         int r, offset;
         int passwordlen = 0;
         int AuthType = NTLM_AUTH;
 lbl_tree_connect:
         ZERO_PKT_ALIGNED(TCR, sizeof(TreeConnectAndXRequest_t));
         TCR->smbH.Magic = SMB_MAGIC;
         TCR->smbH.Cmd = SMB_COM_TREE_CONNECT_ANDX;
         TCR->smbH.Flags = SMB_FLAGS_CASELESS_PATHNAMES;
         TCR->smbH.Flags2 = SMB_FLAGS2_KNOWS_LONG_NAMES | SMB_FLAGS2_32BIT_STATUS;
         if (server_specs.Capabilities & SERVER_CAP_UNICODE)
                 TCR->smbH.Flags2 |= SMB_FLAGS2_UNICODE_STRING;
         TCR->smbH.UID = UID;
         TCR->smbWordcount = 4;
         TCR->smbAndxCmd = SMB_COM_NONE;         // no ANDX command
         // Fill ByteField
         offset = 0;
         if (server_specs.SecurityMode == SERVER_SHARE_SECURITY_LEVEL)
                 passwordlen = AddPassword(Password, PasswordType, AuthType, &TCR->PasswordLength, &TCR->PasswordLength, &TCR->ByteField[offset]);
         else {
                 passwordlen = 1;
                 TCR->PasswordLength = passwordlen;
         }
         offset += passwordlen;
         if ((server_specs.Capabilities & SERVER_CAP_UNICODE) && (!(passwordlen & 1)))
         {
                 TCR->ByteField[offset] = '\0';
                 offset++;                               // pad needed only for unicode as aligment fix is password len is even
         }
         // Add share name
         offset += setStringField(&TCR->ByteField[offset], ShareName);
         memcpy(&TCR->ByteField[offset], "?????\0", 6);  // Service, any type of device
         offset += 6;
         TCR->ByteCount = offset;
         nb_SetSessionMessage(sizeof(TreeConnectAndXRequest_t)+offset);
         r = GetSMBServerReply(0, NULL, 0);
         if (r <= 0)
                 return -EIO;
         // check sanity of SMB header
         if (TCRsp->smbH.Magic != SMB_MAGIC)
                 return -EIO;
         // check there's no error (NT STATUS error type!)
         switch(TCRsp->smbH.Eclass | (TCRsp->smbH.Ecode << 16)){
                 case STATUS_SUCCESS:
                         break;
                 case STATUS_LOGON_FAILURE:      // check there's no auth failure
                         if ((server_specs.SecurityMode == SERVER_USER_SECURITY_LEVEL)
                                 && (AuthType == NTLM_AUTH)) {
                                 AuthType = LM_AUTH;
                                 goto lbl_tree_connect;
                         }
                         return -EACCES;
                 default:
                         return -EIO;
         }
         // return TID
         return (int)TCRsp->smbH.TID;
 }
References AddPassword(), TreeConnectAndXRequest_t::ByteCount, TreeConnectAndXRequest_t::ByteField, server_specs_t::Capabilities, SMBHeader_t::Cmd, EACCES, SMBHeader_t::Eclass, SMBHeader_t::Ecode, EIO, SMBHeader_t::Flags, SMBHeader_t::Flags2, GetSMBServerReply(), LM_AUTH, SMBHeader_t::Magic, memcpy(), nb_SetSessionMessage(), NTLM_AUTH, NULL, TreeConnectAndXRequest_t::PasswordLength, server_specs_t::SecurityMode, SERVER_CAP_UNICODE, SERVER_SHARE_SECURITY_LEVEL, server_specs, SERVER_USER_SECURITY_LEVEL, setStringField(), SMB_buf, SMB_COM_NONE, SMB_COM_TREE_CONNECT_ANDX, SMB_FLAGS2_32BIT_STATUS, SMB_FLAGS2_KNOWS_LONG_NAMES, SMB_FLAGS2_UNICODE_STRING, SMB_FLAGS_CASELESS_PATHNAMES, SMB_MAGIC, TreeConnectAndXRequest_t::smbAndxCmd, TreeConnectAndXRequest_t::smbH, TreeConnectAndXResponse_t::smbH, TreeConnectAndXRequest_t::smbWordcount, STATUS_LOGON_FAILURE, STATUS_SUCCESS, SMBHeader_t::TID, SMBHeader_t::UID, UID, and ZERO_PKT_ALIGNED.
Referenced by smb_GetShareList(), and smb_OpenShare().
smb_TreeDisconnect()
int smb_TreeDisconnect (int UID, int TID)
Definition at line 1477 of file smb.c.
 {
         int r;
         TreeDisconnectRequest_t *TDR = &SMB_buf.smb.treeDisconnectRequest;
         TreeDisconnectResponse_t *TDRsp = &SMB_buf.smb.treeDisconnectResponse;
         ZERO_PKT_ALIGNED(TDR, sizeof(TreeDisconnectRequest_t));
         TDR->smbH.Magic = SMB_MAGIC;
         TDR->smbH.Cmd = SMB_COM_TREE_DISCONNECT;
         TDR->smbH.UID = (u16)UID;
         TDR->smbH.TID = (u16)TID;
         nb_SetSessionMessage(sizeof(TreeDisconnectRequest_t));
         r = GetSMBServerReply(0, NULL, 0);
         if (r <= 0)
                 return -EIO;
         // check sanity of SMB header
         if (TDRsp->smbH.Magic != SMB_MAGIC)
                 return -EIO;
         // check there's no error
         if ((TDRsp->smbH.Eclass | (TDRsp->smbH.Ecode << 16)) != STATUS_SUCCESS)
                 return -EIO;
         TID = -1;
         return 0;
 }
References SMBHeader_t::Cmd, SMBHeader_t::Eclass, SMBHeader_t::Ecode, EIO, GetSMBServerReply(), SMBHeader_t::Magic, nb_SetSessionMessage(), NULL, SMB_buf, SMB_COM_TREE_DISCONNECT, SMB_MAGIC, TreeDisconnectRequest_t::smbH, TreeDisconnectResponse_t::smbH, STATUS_SUCCESS, SMBHeader_t::TID, TID, SMBHeader_t::UID, UID, and ZERO_PKT_ALIGNED.
Referenced by smb_CloseShare(), smb_GetShareList(), smb_LogOff(), and smb_OpenShare().
smb_WriteAndX()
int smb_WriteAndX (int UID, int TID, int FID, s64 fileoffset, void * writebuf, int nbytes)
Definition at line 1108 of file smb.c.
 {
         int r;
         const int padding = 1;  //1 padding byte, to keep the payload aligned for writing performance.
         WriteAndXRequest_t *WR = &SMB_buf.smb.writeAndXRequest;
         WriteAndXResponse_t *WRsp = &SMB_buf.smb.writeAndXResponse;
         ZERO_PKT_ALIGNED(WR, sizeof(WriteAndXRequest_t) + padding);
         WR->smbH.Magic = SMB_MAGIC;
         WR->smbH.Flags2 = SMB_FLAGS2_32BIT_STATUS;
         WR->smbH.Cmd = SMB_COM_WRITE_ANDX;
         WR->smbH.UID = (u16)UID;
         WR->smbH.TID = (u16)TID;
         WR->smbWordcount = 14;
         WR->smbAndxCmd = SMB_COM_NONE;          // no ANDX command
         WR->FID = (u16)FID;
         WR->OffsetLow = (u32)(fileoffset & 0xffffffff);
         WR->OffsetHigh = (u32)((fileoffset >> 32) & 0xffffffff);
         WR->WriteMode = 0x0001;                 //WritethroughMode
         WR->DataOffset = sizeof(WriteAndXRequest_t) + padding;
         WR->Remaining = (u16)nbytes;
         WR->DataLengthLow = (u16)nbytes;
         WR->DataLengthHigh = (u16)(nbytes >> 16);
         WR->ByteCount = (u16)nbytes + padding;
         nb_SetSessionMessage(sizeof(WriteAndXRequest_t) + padding + nbytes);
         r = GetSMBServerReply(sizeof(WriteAndXRequest_t) + padding, writebuf, 0);
         if (r <= 0)
                 return -EIO;
         // check sanity of SMB header
         if (WRsp->smbH.Magic != SMB_MAGIC)
                 return -EIO;
         // check there's no error
         if ((WRsp->smbH.Eclass | (WRsp->smbH.Ecode << 16)) != STATUS_SUCCESS)
                 return -EIO;
         return nbytes;
 }
References WriteAndXRequest_t::ByteCount, SMBHeader_t::Cmd, WriteAndXRequest_t::DataLengthHigh, WriteAndXRequest_t::DataLengthLow, WriteAndXRequest_t::DataOffset, SMBHeader_t::Eclass, SMBHeader_t::Ecode, EIO, WriteAndXRequest_t::FID, SMBHeader_t::Flags2, GetSMBServerReply(), SMBHeader_t::Magic, nb_SetSessionMessage(), WriteAndXRequest_t::OffsetHigh, WriteAndXRequest_t::OffsetLow, WriteAndXRequest_t::Remaining, SMB_buf, SMB_COM_NONE, SMB_COM_WRITE_ANDX, SMB_FLAGS2_32BIT_STATUS, SMB_MAGIC, WriteAndXRequest_t::smbAndxCmd, WriteAndXRequest_t::smbH, WriteAndXResponse_t::smbH, WriteAndXRequest_t::smbWordcount, STATUS_SUCCESS, SMBHeader_t::TID, TID, SMBHeader_t::UID, UID, WriteAndXRequest_t::WriteMode, and ZERO_PKT_ALIGNED.
Referenced by smb_WriteFile().
smb_WriteFile()
int smb_WriteFile (int UID, int TID, int FID, s64 fileoffset, void * writebuf, int nbytes)
Definition at line 1150 of file smb.c.
 {
         int result, remaining, toWrite;
         char *ptr;
         s64 pos;
         remaining = nbytes;
         ptr = writebuf;
         pos = fileoffset;
         while (remaining > 0)
         {
                 toWrite = remaining > CLIENT_MAX_XFER_SIZE ? CLIENT_MAX_XFER_SIZE : remaining;
                 result = smb_WriteAndX(UID, TID, FID, pos, ptr, toWrite);
                 if (result <= 0)
                         return result;
                 pos += result;
                 ptr += result;
                 remaining -= result;
         }
         return nbytes;
 }
References CLIENT_MAX_XFER_SIZE, pos, result, smb_WriteAndX(), TID, and UID.
Referenced by smb_write().
utf16ToAscii()
static int utf16ToAscii (char * out, const char * in, int inbytes) static
Definition at line 284 of file smb.c.
 {
         int len, bytesProcessed;
         const u8 *pIn;
         char *pOut;
         u16 wchar;
         for(pIn = in, pOut = out, len = 0, bytesProcessed = 0; (inbytes == 0) || (bytesProcessed < inbytes) ; len++)
         {
                 wchar = pIn[0] | ((u16)pIn[1] << 8);
                 if (wchar == '\0')
                         break;
                 if (wchar >= 0xD800 && wchar < 0xDC00)
                 {       //Skip surrogate. Replace unsupported character with '?'.
                         *pOut = '?';
                         pIn += 4;
                         bytesProcessed += 4;
                         pOut++;
                 } else {
                         // Write decoded character. Replace unsupported characters with '?'.
                         *pOut = (wchar > 128) ? '?' : (char)wchar;
                         pIn += 2;
                         bytesProcessed += 2;
                         pOut++;
                 }
         }
         pOut[0] = '\0'; //NULL terminate.
         len++;
         return len;
 }
Referenced by getStringField().
Variable Documentation
closeRequest
CloseRequest_t closeRequest
Definition at line 68 of file smb.c.
closeResponse
CloseResponse_t closeResponse
Definition at line 69 of file smb.c.
deleteRequest
DeleteRequest_t deleteRequest
Definition at line 70 of file smb.c.
deleteResponse
DeleteResponse_t deleteResponse
Definition at line 71 of file smb.c.
echoRequest
EchoRequest_t echoRequest
Definition at line 52 of file smb.c.
echoResponse
EchoResponse_t echoResponse
Definition at line 53 of file smb.c.
findFirstNext2Request
FindFirstNext2Request_t findFirstNext2Request
Definition at line 58 of file smb.c.
findFirstNext2Response
FindFirstNext2Response_t findFirstNext2Response
Definition at line 59 of file smb.c.
logOffAndXRequest
LogOffAndXRequest_t logOffAndXRequest
Definition at line 50 of file smb.c.
logOffAndXResponse
LogOffAndXResponse_t logOffAndXResponse
Definition at line 51 of file smb.c.
main_socket
int main_socket = -1 static
Definition at line 31 of file smb.c.
Referenced by GetSMBServerReply(), smb_Connect(), smb_Disconnect(), and smb_ReadAndX().
manageDirectoryRequest
ManageDirectoryRequest_t manageDirectoryRequest
Definition at line 72 of file smb.c.
manageDirectoryResponse
ManageDirectoryResponse_t manageDirectoryResponse
Definition at line 73 of file smb.c.
negotiateProtocolRequest
NegotiateProtocolRequest_t negotiateProtocolRequest
Definition at line 40 of file smb.c.
negotiateProtocolResponse
NegotiateProtocolResponse_t negotiateProtocolResponse
Definition at line 41 of file smb.c.
netShareEnumRequest
NetShareEnumRequest_t netShareEnumRequest
Definition at line 48 of file smb.c.
netShareEnumResponse
NetShareEnumResponse_t netShareEnumResponse
Definition at line 49 of file smb.c.
ntCreateAndXRequest
NTCreateAndXRequest_t ntCreateAndXRequest
Definition at line 60 of file smb.c.
ntCreateAndXResponse
NTCreateAndXResponse_t ntCreateAndXResponse
Definition at line 61 of file smb.c.
openAndXRequest
OpenAndXRequest_t openAndXRequest
Definition at line 62 of file smb.c.
openAndXResponse
OpenAndXResponse_t openAndXResponse
Definition at line 63 of file smb.c.
queryInformationDiskRequest
QueryInformationDiskRequest_t queryInformationDiskRequest
Definition at line 54 of file smb.c.
queryInformationDiskResponse
QueryInformationDiskResponse_t queryInformationDiskResponse
Definition at line 55 of file smb.c.
queryPathInformationRequest
QueryPathInformationRequest_t queryPathInformationRequest
Definition at line 56 of file smb.c.
queryPathInformationResponse
QueryPathInformationResponse_t queryPathInformationResponse
Definition at line 57 of file smb.c.
readAndXRequest
ReadAndXRequest_t readAndXRequest
Definition at line 64 of file smb.c.
readAndXResponse
ReadAndXResponse_t readAndXResponse
Definition at line 65 of file smb.c.
renameRequest
RenameRequest_t renameRequest
Definition at line 74 of file smb.c.
renameResponse
RenameResponse_t renameResponse
Definition at line 75 of file smb.c.
s16buff
s16 s16buff[(MAX_SMB_BUF+MAX_SMB_BUF_HDR)/sizeof(s16)]
Definition at line 39 of file smb.c.
server_specs
server_specs_t server_specs static
Definition at line 23 of file smb.c.
Referenced by AddPassword(), getServerSpecs(), getStringField(), setStringField(), smb_Connect(), smb_Delete(), smb_FindFirstNext2(), smb_ManageDirectory(), smb_NegotiateProtocol(), smb_NTCreateAndX(), smb_OpenAndX(), smb_QueryPathInformation(), smb_Rename(), smb_SessionSetupAndX(), and smb_TreeConnectAndX().
sessionHeader
u32 sessionHeader
Definition at line 35 of file smb.c.
sessionSetupAndXRequest
SessionSetupAndXRequest_t sessionSetupAndXRequest
Definition at line 42 of file smb.c.
sessionSetupAndXResponse
SessionSetupAndXResponse_t sessionSetupAndXResponse
Definition at line 43 of file smb.c.
union { ... } smb
struct { ... } SMB_buf
Referenced by GetSMBServerReply(), nb_GetPacketType(), nb_GetSessionMessageLength(), nb_SetSessionMessage(), smb_Close(), smb_Delete(), smb_Echo(), smb_FindFirstNext2(), smb_LogOffAndX(), smb_ManageDirectory(), smb_NegotiateProtocol(), smb_NetShareEnum(), smb_NTCreateAndX(), smb_OpenAndX(), smb_QueryInformationDisk(), smb_QueryPathInformation(), smb_ReadAndX(), smb_Rename(), smb_SessionSetupAndX(), smb_TreeConnectAndX(), smb_TreeDisconnect(), and smb_WriteAndX().
treeConnectAndXRequest
TreeConnectAndXRequest_t treeConnectAndXRequest
Definition at line 44 of file smb.c.
treeConnectAndXResponse
TreeConnectAndXResponse_t treeConnectAndXResponse
Definition at line 45 of file smb.c.
treeDisconnectRequest
TreeDisconnectRequest_t treeDisconnectRequest
Definition at line 46 of file smb.c.
treeDisconnectResponse
TreeDisconnectResponse_t treeDisconnectResponse
Definition at line 47 of file smb.c.
u16buff
u16 u16buff[(MAX_SMB_BUF+MAX_SMB_BUF_HDR)/sizeof(u16)]
Definition at line 38 of file smb.c.
u8buff
u8 u8buff[MAX_SMB_BUF+MAX_SMB_BUF_HDR]
Definition at line 37 of file smb.c.
writeAndXRequest
WriteAndXRequest_t writeAndXRequest
Definition at line 66 of file smb.c.
writeAndXResponse
WriteAndXResponse_t writeAndXResponse
Definition at line 67 of file smb.c.