ps2sdk: iop/sound/libsd/src/block.c File Reference
block.c File Reference
#include "types.h"
#include <stdarg.h>
#include "freesd.h"
#include "spu2regs.h"
Functions
void SetDmaWrite (s32 chan)
void SetDmaRead (s32 chan)
u32 DmaStop (u32 core)
s32 BlockTransWriteFrom (u8 *iopaddr, u32 size, s32 chan, u16 mode, u8 *startaddr)
s32 BlockTransWrite (u8 *iopaddr, u32 size, s32 chan)
s32 BlockTransRead (u8 *iopaddr, u32 size, s32 chan, s16 mode)
int sceSdBlockTrans (s16 chan, u16 mode, u8 *iopaddr, u32 size,...)
u32 sceSdBlockTransStatus (s16 chan, s16 flag)
Variables
u32 BlockTransBuff [2]
u32 BlockTransAddr [2]
u32 BlockTransSize [2]
IntrData TransIntrData [2]
Detailed Description
Part of the IOP Sound Driver
Definition in file block.c.
Function Documentation
BlockTransRead()
s32 BlockTransRead (u8 * iopaddr, u32 size, s32 chan, s16 mode)
Definition at line 108 of file block.c.
 {
         u32 i;
         s32 core = chan & 1;
         BlockTransBuff[core] = 0;
         BlockTransSize[core] = size;
         BlockTransAddr[core] = (u32)iopaddr;
         if(*SD_CORE_ATTR(core) & SD_DMA_IN_PROCESS) return -1;
         if(*SD_DMA_CHCR(core) & SD_DMA_START) return -1;
         *SD_CORE_ATTR(core) &= 0xFFCF;
         *SD_A_TSA_HI(core) = 0;
         *SD_A_TSA_LO(core) = ((mode & 0xF00) << 1) + 0x400;
         *U16_REGISTER(0x1AE + (core*1024)) = (mode & 0xF000) >> 11;
         i = 0x4937;
         while(i--);
         *U16_REGISTER(0x1B0+(core*1024)) = 4;
         SetDmaRead(core);
         *SD_DMA_ADDR(core) = (u32)iopaddr;
         *SD_DMA_MODE(core) = 0x10;
         *SD_DMA_SIZE(core) = (size/64)+((size&63)>0);
         *SD_DMA_CHCR(core) = SD_DMA_CS | SD_DMA_START | SD_DMA_DIR_SPU2IOP;
         return 0;
 }
References BlockTransAddr, BlockTransBuff, BlockTransSize, SD_A_TSA_HI, SD_A_TSA_LO, SD_CORE_ATTR, SD_DMA_ADDR, SD_DMA_CHCR, SD_DMA_CS, SD_DMA_DIR_SPU2IOP, SD_DMA_IN_PROCESS, SD_DMA_MODE, SD_DMA_SIZE, SD_DMA_START, SetDmaRead(), and U16_REGISTER.
Referenced by sceSdBlockTrans().
BlockTransWrite()
s32 BlockTransWrite (u8 * iopaddr, u32 size, s32 chan)
Definition at line 79 of file block.c.
 {
         s32 core = chan & 1;
         BlockTransBuff[core] = 0;
         BlockTransSize[core] = size;
         BlockTransAddr[core] = (u32)iopaddr;
         if(*SD_CORE_ATTR(core) & SD_DMA_IN_PROCESS) return -1;
         if(*SD_DMA_CHCR(core) & SD_DMA_START) return -1;
         *SD_CORE_ATTR(core) &= 0xFFCF;
         *SD_A_TSA_HI(core) = 0;
         *SD_A_TSA_LO(core) = 0;
         *U16_REGISTER(0x1B0+(core*1024)) = 1 << core;
         SetDmaWrite(core);
         *SD_DMA_ADDR(core) = (u32)iopaddr;
         *SD_DMA_MODE(core) = 0x10;
         *SD_DMA_SIZE(core) = (size/64)+((size&63)>0);
         *SD_DMA_CHCR(core) = SD_DMA_CS | SD_DMA_START | SD_DMA_DIR_IOP2SPU;
         return 0;
 }
References BlockTransAddr, BlockTransBuff, BlockTransSize, SD_A_TSA_HI, SD_A_TSA_LO, SD_CORE_ATTR, SD_DMA_ADDR, SD_DMA_CHCR, SD_DMA_CS, SD_DMA_DIR_IOP2SPU, SD_DMA_IN_PROCESS, SD_DMA_MODE, SD_DMA_SIZE, SD_DMA_START, SetDmaWrite(), and U16_REGISTER.
Referenced by sceSdBlockTrans().
BlockTransWriteFrom()
s32 BlockTransWriteFrom (u8 * iopaddr, u32 size, s32 chan, u16 mode, u8 * startaddr)
Definition at line 28 of file block.c.
 {
         s32 core = chan & 1;
         s32 offset;
         BlockTransBuff[core] = 0;
         BlockTransSize[core] = size;
         BlockTransAddr[core] = (u32)iopaddr;
         if(startaddr == 0)
                 startaddr = iopaddr;
         offset = startaddr - iopaddr;
         if(offset > size)
         {
                 if(mode & SD_TRANS_LOOP)
                 {
                         offset -= size;
                         BlockTransBuff[core] = 1;
                 }
                 else
                 {
                         return -1;
                 }
         }
         if(offset & 1023) offset += 1024;
         iopaddr += (BlockTransSize[core] * BlockTransBuff[core]) + offset;
         if(*SD_CORE_ATTR(core) & SD_DMA_IN_PROCESS) return -1;
         if(*SD_DMA_CHCR(core) & SD_DMA_START) return -1;
         *SD_CORE_ATTR(core) &= 0xFFCF;
         *SD_A_TSA_HI(core) = 0;
         *SD_A_TSA_LO(core) = 0;
         *U16_REGISTER(0x1B0+(core*1024)) = 1 << core;
         SetDmaWrite(core);
         *SD_DMA_ADDR(core) = (u32)iopaddr;
         *SD_DMA_MODE(core) = 0x10;
         *SD_DMA_SIZE(core) = (size/64)+((size&63)>0);
         *SD_DMA_CHCR(core) = SD_DMA_CS | SD_DMA_START | SD_DMA_DIR_IOP2SPU;
         return 0;
 }
References BlockTransAddr, BlockTransBuff, BlockTransSize, SD_A_TSA_HI, SD_A_TSA_LO, SD_CORE_ATTR, SD_DMA_ADDR, SD_DMA_CHCR, SD_DMA_CS, SD_DMA_DIR_IOP2SPU, SD_DMA_IN_PROCESS, SD_DMA_MODE, SD_DMA_SIZE, SD_DMA_START, SD_TRANS_LOOP, SetDmaWrite(), and U16_REGISTER.
Referenced by sceSdBlockTrans().
DmaStop()
u32 DmaStop (u32 core)
Definition at line 589 of file spu2.c.
 {
         u32 retval;
         core &= 1;
         if(*U16_REGISTER(0x1B0 + (core * 1024)) == 0)
                 retval = 0;
         else
                 retval = *SD_DMA_ADDR(core);
         *SD_DMA_CHCR(core) &= ~SD_DMA_START;
         *U16_REGISTER(0x1B0 + (core * 1024)) = 0;
         retval = (BlockTransBuff[core] << 24) | (retval & 0xFFFFFF);
         return retval;
 }
Referenced by sceSdBlockTrans().
sceSdBlockTrans()
int sceSdBlockTrans (s16 chan, u16 mode, u8 * iopaddr, u32 size, ...)
Definition at line 146 of file block.c.
 {
         int transfer_dir = mode & 3;
         int core = chan & 1;
         int _size = size;
         va_list alist;
         u8* startaddr;
         switch(transfer_dir)
         {
                 case SD_TRANS_WRITE:
                 {
                         TransIntrData[core].mode = 0x100 | core;
                         if(mode & SD_TRANS_LOOP)
{
                                 TransIntrData[core].mode |= SD_TRANS_LOOP << 8;
                                 _size /= 2;
                         }
                         if(BlockTransWrite(iopaddr, _size, core) >= 0)
                                 return 0;
                 } break;
                 case SD_TRANS_READ:
                 {
                         TransIntrData[core].mode = 0x300 | core;
                         if(mode & SD_TRANS_LOOP)
{
                                 TransIntrData[core].mode |= SD_TRANS_LOOP << 8;
                                 _size /= 2;
                         }
                         if(BlockTransRead(iopaddr, _size, chan, mode) >= 0)
                                 return 0;
                 } break;
                 case SD_TRANS_STOP:
                 {
                         return DmaStop(core);
                 } break;
                 case SD_TRANS_WRITE_FROM:
                 {
                         va_start(alist, size);
                         startaddr = va_arg(alist, u8*);
                         va_end(alist);
                         TransIntrData[core].mode = 0x100 | core;
                         if(mode & SD_TRANS_LOOP)
{
                                 TransIntrData[core].mode |= SD_TRANS_LOOP << 8;
                                 _size /= 2;
                         }
                         if(BlockTransWriteFrom(iopaddr, _size, core, mode, startaddr) >= 0)
                                 return 0;
                 } break;
         }
         return -1;
 }
References BlockTransRead(), BlockTransWrite(), BlockTransWriteFrom(), DmaStop(), IntrData::mode, SD_TRANS_LOOP, SD_TRANS_READ, SD_TRANS_STOP, SD_TRANS_WRITE, SD_TRANS_WRITE_FROM, and TransIntrData.
sceSdBlockTransStatus()
u32 sceSdBlockTransStatus (s16 chan, s16 flag)
Definition at line 216 of file block.c.
 {
         u32 retval;
         chan &= 1;
         if(*U16_REGISTER(0x1B0 + (chan * 1024)) == 0)
                 retval = 0;
         else
                 retval = *SD_DMA_ADDR(chan);
         retval = (BlockTransBuff[chan] << 24) | (retval & 0xFFFFFF);
         return retval;
 }
References BlockTransBuff, SD_DMA_ADDR, and U16_REGISTER.
SetDmaRead()
void SetDmaRead (s32 chan)
Definition at line 614 of file spu2.c.
 {
         volatile u32 *reg = U32_REGISTER(0x1014 + (chan << 10));
         *reg = (*reg & 0xF0FFFFFF) | 0x22000000;
 }
Referenced by BlockTransRead().
SetDmaWrite()
void SetDmaWrite (s32 chan)
Definition at line 608 of file spu2.c.
 {
         volatile u32 *reg = U32_REGISTER(0x1014 + (chan << 10));
         *reg = (*reg & 0xF0FFFFFF) | 0x20000000;
 }
Referenced by BlockTransWrite(), and BlockTransWriteFrom().
Variable Documentation
BlockTransAddr
u32 BlockTransAddr[2]
Definition at line 19 of file block.c.
Referenced by BlockTransRead(), BlockTransWrite(), BlockTransWriteFrom(), and TransInterrupt().
BlockTransBuff
u32 BlockTransBuff[2]
Definition at line 18 of file block.c.
Referenced by BlockTransRead(), BlockTransWrite(), BlockTransWriteFrom(), DmaStop(), sceSdBlockTransStatus(), and TransInterrupt().
BlockTransSize
u32 BlockTransSize[2]
Definition at line 20 of file block.c.
Referenced by BlockTransRead(), BlockTransWrite(), BlockTransWriteFrom(), and TransInterrupt().
TransIntrData
IntrData TransIntrData[2] extern
Definition at line 44 of file spu2.c.
Referenced by sceSdBlockTrans().