ps2sdk: iop/sound/audsrv/src/common.h File Reference
common.h File Reference
Functions
int create_thread (void *func, int priority, void *param)
void print_hex_buffer (unsigned char *ptr, int len)
Detailed Description
audsrv helpers.
Definition in file common.h.
Function Documentation
create_thread()
int create_thread (void * func, int priority, void * param)
Helper function to easily create threads
Parameters
func thread procedure
priority thread priority (usually 40)
param optional argument for thread procedure
Returns
thread_id (int), negative on error
Creates a thread based on the given parameter. Upon completion, thread is started.
Definition at line 34 of file common.c.
 {
         int tid;
         iop_thread_t thr;
         thr.attr = TH_C;
         thr.thread = func;
         thr.option = 0;
         thr.priority = priority;
         thr.stacksize = 4096;
         tid = CreateThread(&thr);
         if (tid < 0)
         {
                 return 0;
         }
         StartThread(tid, param);
         return tid;
 }
References iop_thread_t::attr, CreateThread(), iop_thread_t::option, iop_thread_t::priority, iop_thread_t::stacksize, StartThread(), TH_C, iop_thread_t::thread, and tid.
Referenced by audsrv_cd_play_sectors(), audsrv_init(), and initialize_rpc_thread().
print_hex_buffer()
void print_hex_buffer (unsigned char * ptr, int len)
Helper to print buffer in hex. Useful for debugging.
Parameters
ptr pointer to buffer
len buffer length
Definition at line 58 of file common.c.
 {
         int p;
         for (p=0; p<len; p++)
         {
                 if (p > 0 && (p & 0x0f) == 0)
                 {
                         printf("\n");
                 }
                 printf("%02x ", ptr[p]);
         }
 }
References printf().