ps2sdk: iop/sound/audsrv/src/rpc_server.c File Reference
rpc_server.c File Reference
#include <stdio.h>
#include <thbase.h>
#include <thsemap.h>
#include <loadcore.h>
#include <sysmem.h>
#include <intrman.h>
#include <sifcmd.h>
#include <audsrv.h>
#include "audsrv_internal.h"
#include "common.h"
#include "rpc_client.h"
Functions
static void * rpc_command (int func, unsigned *data, int size)
static void rpc_server_thread (void *arg)
int initialize_rpc_thread ()
Variables
static int rpc_buffer [18000/4]
static SifRpcDataQueue_t qd
static SifRpcServerData_t sd0
Detailed Description
audsrv iop rpc server.
Definition in file rpc_server.c.
Function Documentation
initialize_rpc_thread()
int initialize_rpc_thread ()
Definition at line 174 of file rpc_server.c.
 {
         int rpc_tid;
         rpc_tid = create_thread(rpc_server_thread, 40, 0);
         printf("audsrv: rpc server thread 0x%x started\n", rpc_tid);
         return 0;
 }
References create_thread(), printf(), and rpc_server_thread().
Referenced by _start().
rpc_command()
static void* rpc_command (int func, unsigned * data, int size) static
RPC command handler.
Parameters
func command (one of AUDSRV_x)
data pointer to data array
size size of data array (in bytes)
Returns
value depends on function invoked
This is a single rpc handler, it unpacks the data array and calls local functions.
Definition at line 46 of file rpc_server.c.
 {
         int ret;
         /* printf("audsrv: rpc command %d\n", func); */
         switch(func)
         {
                 case AUDSRV_INIT:
                 ret = audsrv_init();
                 initialize_rpc_client();
                 break;
                 case AUDSRV_FORMAT_OK:
                 ret = audsrv_format_ok(data[0], data[1], data[2]);
                 break;
                 case AUDSRV_SET_FORMAT:
                 ret = audsrv_set_format(data[0], data[1], data[2]);
                 break;
                 case AUDSRV_WAIT_AUDIO:
                 ret = audsrv_wait_audio(data[0]);
                 break;
                 case AUDSRV_PLAY_AUDIO:
                 ret = audsrv_play_audio((const char *)&data[1], data[0]);
                 break;
                 case AUDSRV_STOP_AUDIO:
                 ret = audsrv_stop_audio();
                 break;
                 case AUDSRV_SET_VOLUME:
                 ret = audsrv_set_volume(data[0]);
                 break;
                 case AUDSRV_QUIT:
                 ret = audsrv_quit();
                 break;
                 case AUDSRV_PLAY_CD:
                 ret = audsrv_play_cd(data[0]);
                 break;
                 case AUDSRV_STOP_CD:
                 ret = audsrv_stop_cd();
                 break;
                 case AUDSRV_GET_CDPOS:
                 ret = audsrv_get_cdpos();
                 break;
                 case AUDSRV_GET_TRACKPOS:
                 ret = audsrv_get_trackpos();
                 break;
                 case AUDSRV_SET_THRESHOLD:
                 ret = audsrv_set_threshold(data[0]);
                 break;
                 case AUDSRV_GET_NUMTRACKS:
                 ret = audsrv_get_numtracks();
                 break;
                 case AUDSRV_GET_TRACKOFFSET:
                 ret = audsrv_get_track_offset(data[0]);
                 break;
                 case AUDSRV_PLAY_SECTORS:
                 ret = audsrv_cd_play_sectors(data[0], data[1]);
                 break;
                 case AUDSRV_GET_CD_STATUS:
                 ret = audsrv_get_cd_status();
                 break;
                 case AUDSRV_GET_CD_TYPE:
                 ret = audsrv_get_cd_type();
                 break;
                 case AUDSRV_PAUSE_CD:
                 ret = audsrv_cd_pause();
                 break;
                 case AUDSRV_RESUME_CD:
                 ret = audsrv_cd_resume();
                 break;
                 case AUDSRV_INIT_ADPCM:
                 ret = audsrv_adpcm_init();
                 break;
                 case AUDSRV_LOAD_ADPCM:
                 return audsrv_load_adpcm((u32*)data[0], data[1], data[2]);
                 case AUDSRV_PLAY_ADPCM:
                 ret = audsrv_ch_play_adpcm(data[0], data[1]);
                 break;
                 case AUDSRV_SET_ADPCM_VOL:
                 ret = audsrv_adpcm_set_volume(data[0], data[1]);
                 break;
                 default:
                 ret = -1;
                 break;
         }
         data[0] = ret;
         return data;
 }
References audsrv_adpcm_init(), audsrv_adpcm_set_volume(), audsrv_cd_pause(), audsrv_cd_play_sectors(), audsrv_cd_resume(), audsrv_ch_play_adpcm(), AUDSRV_FORMAT_OK, audsrv_format_ok(), AUDSRV_GET_CD_STATUS, audsrv_get_cd_status(), AUDSRV_GET_CD_TYPE, audsrv_get_cd_type(), AUDSRV_GET_CDPOS, audsrv_get_cdpos(), AUDSRV_GET_NUMTRACKS, audsrv_get_numtracks(), audsrv_get_track_offset(), AUDSRV_GET_TRACKOFFSET, AUDSRV_GET_TRACKPOS, audsrv_get_trackpos(), AUDSRV_INIT, audsrv_init(), AUDSRV_INIT_ADPCM, AUDSRV_LOAD_ADPCM, audsrv_load_adpcm(), AUDSRV_PAUSE_CD, AUDSRV_PLAY_ADPCM, AUDSRV_PLAY_AUDIO, audsrv_play_audio(), AUDSRV_PLAY_CD, audsrv_play_cd(), AUDSRV_PLAY_SECTORS, AUDSRV_QUIT, audsrv_quit(), AUDSRV_RESUME_CD, AUDSRV_SET_ADPCM_VOL, AUDSRV_SET_FORMAT, audsrv_set_format(), AUDSRV_SET_THRESHOLD, audsrv_set_threshold(), AUDSRV_SET_VOLUME, audsrv_set_volume(), AUDSRV_STOP_AUDIO, audsrv_stop_audio(), AUDSRV_STOP_CD, audsrv_stop_cd(), AUDSRV_WAIT_AUDIO, audsrv_wait_audio(), and initialize_rpc_client().
Referenced by rpc_server_thread().
rpc_server_thread()
static void rpc_server_thread (void * arg) static
RPC listener thread
Parameters
arg not used
This is the main RPC thread. Nothing fancy here.
Definition at line 163 of file rpc_server.c.
 {
         SifInitRpc(0);
         printf("audsrv: creating rpc server\n");
         SifSetRpcQueue(&qd, GetThreadId());
         SifRegisterRpc(&sd0, AUDSRV_IRX, (void *)rpc_command, rpc_buffer, NULL, NULL, &qd);
         SifRpcLoop(&qd);
 }
References AUDSRV_IRX, GetThreadId(), NULL, printf(), qd, rpc_buffer, rpc_command(), sd0, SifInitRpc, SifRegisterRpc, SifRpcLoop, and SifSetRpcQueue.
Referenced by initialize_rpc_thread().
Variable Documentation
qd
SifRpcDataQueue_t qd static
RPC thread variables
Definition at line 32 of file rpc_server.c.
Referenced by rpc_server_thread().
rpc_buffer
int rpc_buffer[18000/4] static
buffer for RPC DMA
Definition at line 30 of file rpc_server.c.
Referenced by rpc_server_thread().
sd0
SifRpcServerData_t sd0 static
RPC thread variables
Definition at line 34 of file rpc_server.c.
Referenced by rpc_server_thread().