ps2sdk: iop/sound/audsrv/src/rpc_client.h File Reference
rpc_client.h File Reference
Functions
void initialize_rpc_client (void)
void deinitialize_rpc_client (void)
void call_client_callback (int id)
Detailed Description
audsrv iop rpc client.
Definition in file rpc_client.h.
Function Documentation
call_client_callback()
void call_client_callback (int id)
Definition at line 37 of file rpc_client.c.
 {
         WaitSema(rpc_sema);
         sceSifCallRpc(&client, id, SIF_RPC_M_NOWAIT, NULL, 0, NULL, 0, &call_end_callback, NULL);
 }
References call_end_callback(), client, NULL, rpc_sema, sceSifCallRpc(), SIF_RPC_M_NOWAIT, and WaitSema().
Referenced by cdda_procedure(), and play_thread().
deinitialize_rpc_client()
void deinitialize_rpc_client (void)
Definition at line 26 of file rpc_client.c.
 {
         memset(&client, 0, sizeof(client));
         DeleteSema(rpc_sema);
 }
References client, DeleteSema(), memset(), and rpc_sema.
Referenced by audsrv_quit().
initialize_rpc_client()
void initialize_rpc_client (void)
Definition at line 18 of file rpc_client.c.
 {
         rpc_sema = CreateMutex(IOP_MUTEX_UNLOCKED);
         client.server = NULL;
         while(sceSifBindRpc(&client, AUDSRV_IRX, 0) < 0 || client.server == NULL) DelayThread(500);
 }
References AUDSRV_IRX, client, CreateMutex(), DelayThread(), IOP_MUTEX_UNLOCKED, NULL, rpc_sema, sceSifBindRpc(), and SifRpcClientData_t::server.
Referenced by rpc_command().