ps2sdk: iop/sound/audsrv/src/rpc_server.h File Reference
rpc_server.h File Reference
Functions
int initialize_rpc_thread ()
Detailed Description
audsrv iop rpc server.
Definition in file rpc_server.h.
Function Documentation
initialize_rpc_thread()
int initialize_rpc_thread ()
Definition at line 174 of file rpc_server.c.
 {
         int rpc_tid;
         rpc_tid = create_thread(rpc_server_thread, 40, 0);
         printf("audsrv: rpc server thread 0x%x started\n", rpc_tid);
         return 0;
 }
References create_thread(), printf(), and rpc_server_thread().
Referenced by _start().