ps2sdk: iop/kernel/include/stdio.h File Reference
stdio.h File Reference
#include <stdarg.h>
#include <irx.h>
Macros
#define stdio_IMPORTS_start DECLARE_IMPORT_TABLE(stdio, 1, 2)
#define stdio_IMPORTS_end END_IMPORT_TABLE
#define I_printf DECLARE_IMPORT(4, printf)
#define I_getchar DECLARE_IMPORT(5, getchar)
#define I_putchar DECLARE_IMPORT(6, putchar)
#define I_puts DECLARE_IMPORT(7, puts)
#define I_gets DECLARE_IMPORT(8, gets)
#define I_fdprintf DECLARE_IMPORT(9, fdprintf)
#define I_fdgetc DECLARE_IMPORT(10, fdgetc)
#define I_fdputc DECLARE_IMPORT(11, fdputc)
#define I_fdputs DECLARE_IMPORT(12, fdputs)
#define I_fdgets DECLARE_IMPORT(13, fdgets)
#define I_vfdprintf DECLARE_IMPORT(14, vfdprintf)
Functions
int printf (const char *format,...)
int getchar (void)
int putchar (int c)
int puts (const char *s)
char * gets (char *s)
int fdprintf (int fd, const char *format,...)
int fdgetc (int fd)
int fdputc (int c, int fd)
int fdputs (const char *s, int fd)
char * fdgets (char *buf, int fd)
int vfdprintf (int fd, const char *format, va_list ap)
Detailed Description
Standard C Library I/O.
Definition in file stdio.h.
Macro Definition Documentation
I_fdgetc
#define I_fdgetc DECLARE_IMPORT(10, fdgetc)
Definition at line 43 of file stdio.h.
I_fdgets
#define I_fdgets DECLARE_IMPORT(13, fdgets)
Definition at line 46 of file stdio.h.
I_fdprintf
#define I_fdprintf DECLARE_IMPORT(9, fdprintf)
Definition at line 42 of file stdio.h.
I_fdputc
#define I_fdputc DECLARE_IMPORT(11, fdputc)
Definition at line 44 of file stdio.h.
I_fdputs
#define I_fdputs DECLARE_IMPORT(12, fdputs)
Definition at line 45 of file stdio.h.
I_getchar
#define I_getchar DECLARE_IMPORT(5, getchar)
Definition at line 38 of file stdio.h.
I_gets
#define I_gets DECLARE_IMPORT(8, gets)
Definition at line 41 of file stdio.h.
I_printf
#define I_printf DECLARE_IMPORT(4, printf)
Definition at line 37 of file stdio.h.
I_putchar
#define I_putchar DECLARE_IMPORT(6, putchar)
Definition at line 39 of file stdio.h.
I_puts
#define I_puts DECLARE_IMPORT(7, puts)
Definition at line 40 of file stdio.h.
I_vfdprintf
#define I_vfdprintf DECLARE_IMPORT(14, vfdprintf)
Definition at line 47 of file stdio.h.
stdio_IMPORTS_end
#define stdio_IMPORTS_end END_IMPORT_TABLE
Definition at line 35 of file stdio.h.
stdio_IMPORTS_start
#define stdio_IMPORTS_start DECLARE_IMPORT_TABLE(stdio, 1, 2)
Definition at line 34 of file stdio.h.
Function Documentation
fdgetc()
int fdgetc (int fd)
fdgets()
char* fdgets (char * buf, int fd)
fdprintf()
int fdprintf (int fd, const char * format, ...)
fdputc()
int fdputc (int c, int fd)
fdputs()
int fdputs (const char * s, int fd)
getchar()
int getchar (void)
gets()
char* gets (char * s)
printf()
int printf (const char * format, ...)
Referenced by _smap_read_phy(), _smap_write_phy(), _start(), AddPowerOffHandler(), AHX_Init(), AHX_LoadSong(), AHXPlayer_LoadSongBuffer(), audsrv_adpcm_init(), audsrv_cd_play_sectors(), audsrv_init(), audsrv_play_cd(), audsrv_set_format(), audsrv_set_threshold(), cdda_procedure(), cmdline_handle(), devfs_create_device(), devfs_deinit(), devfs_dummy(), devfs_init(), DisplayBanner(), DisplayHelpMessage(), do_ps2mouse_setreadmode(), dummy(), fat_getPartitionBootSector(), fat_mount(), fat_writeSingleSector(), fd_initialize(), fd_open(), fileXio_GetDir_RPC(), fileXio_Mount_RPC(), fileXio_Thread(), fileXioRpc_AddDrv(), fileXioRpc_ChDir(), fileXioRpc_ChStat(), fileXioRpc_Close(), fileXioRpc_Dclose(), fileXioRpc_DelDrv(), fileXioRpc_Devctl(), fileXioRpc_Dopen(), fileXioRpc_Dread(), fileXioRpc_Format(), fileXioRpc_GetStat(), fileXioRpc_Ioctl(), fileXioRpc_Ioctl2(), fileXioRpc_Lseek(), fileXioRpc_Lseek64(), fileXioRpc_MkDir(), fileXioRpc_Mount(), fileXioRpc_Open(), fileXioRpc_Read(), fileXioRpc_ReadLink(), fileXioRpc_Remove(), fileXioRpc_Rename(), fileXioRpc_RmDir(), fileXioRpc_Stop(), fileXioRpc_SymLink(), fileXioRpc_Sync(), fileXioRpc_uMount(), fileXioRpc_Write(), fio_close(), fio_closeDir(), fio_dread(), fio_init(), fio_open(), fio_openDir(), fio_read(), fio_write(), fioGetInput(), flushbuffer(), freeDevice(), freeIoRequest(), freeIsoTd(), freeTd(), getIndexWrite(), getReg8(), HandleTxReqs(), hcdProcessIntr(), httpClose(), httpConnect(), httpDummy(), httpInitialize(), httpLseek(), httpOpen(), httpRead(), initConfigureSBP2Device(), initialize_cdda(), initialize_rpc_thread(), InitializeLWIP(), InitializeSCSIDevice(), InitUSB(), list_all_libraries(), list_all_modules(), list_devices_ioman(), list_devices_iomanx(), list_fs_devices(), mass_stor_configureNextDevice(), mass_stor_connect(), mass_stor_disconnect(), mass_stor_probe(), mass_stor_stop_unit(), mass_stor_warmup(), mass_store_configureDevice(), myCdHandler(), naplinkRpcInit(), NETMAN_rpc_handler(), ParseSmapConfiguration(), part_connect(), part_disconnect(), part_getPartitionTable(), play_thread(), print_help(), print_hex_buffer(), process_toc(), ProcessStatus(), PS2CamCallback(), PS2CamConnect(), PS2CamDisconnect(), PS2CamGetDeviceSring(), PS2CamInitDriver(), PS2CamInitializeNewDevice(), PS2CamReadData(), PS2CamSelectInterface(), PS2CamSetDeviceBandwidth(), PS2CamSetDeviceConfiguration(), ps2kbd_config_set(), ps2kbd_connect(), ps2kbd_data_recv(), ps2kbd_disconnect(), ps2kbd_getstring_set(), ps2kbd_idlemode_set(), ps2kbd_init(), ps2kbd_probe(), ps2mouse_config_set(), ps2mouse_connect(), ps2mouse_data_recv(), ps2mouse_disconnect(), ps2mouse_getstring_set(), ps2mouse_init(), ps2mouse_probe(), ps2netfs_close_socket(), ps2netfs_Init(), resolveAddress(), rpc_server_thread(), rpc_thread(), rpcCommandHandler(), RpcHandler(), rpcHandlerFunction(), rpcMainThread(), RpcThread(), scache_flushSector(), scache_flushSectors(), scache_init(), scache_readSector(), scache_writeSector(), setReg16(), setReg8(), SetupNetDev(), shutdown(), Shutdown(), sio_vprintf(), sys_mbox_new(), sys_sem_new(), threadRpcFunction(), usb_bulk_clear_halt(), usb_bulk_command(), usb_bulk_manage_status(), usb_bulk_reset(), usb_bulk_status(), usb_bulk_transfer(), and usb_getstring().
putchar()
int putchar (int c)
puts()
int puts (const char * s)
vfdprintf()
int vfdprintf (int fd, const char * format, va_list ap)