ps2sdk: pfs_block_device_t Struct Reference
pfs_block_device_t Struct Reference
#include <libpfs.h>
Data Fields
char * devName
int(* transfer)(int fd, void *buffer, u32 sub, u32 sector, u32 size, u32 mode)
u32(* getSubNumber)(int fd)
u32(* getSize)(int fd, u32 sub)
void(* setPartitionError)(int fd)
int(* flushCache)(int fd)
Detailed Description
Definition at line 163 of file libpfs.h.
Field Documentation
devName
char* pfs_block_device_t::devName
Definition at line 164 of file libpfs.h.
flushCache
int(* pfs_block_device_t::flushCache) (int fd)
Definition at line 169 of file libpfs.h.
Referenced by pfsFormat(), pfsFsckStat(), pfsJournalFlush(), pfsJournalReset(), and pfsUpdateSuperBlock().
getSize
u32(* pfs_block_device_t::getSize) (int fd, u32 sub)
Definition at line 167 of file libpfs.h.
Referenced by pfsBitmapSetupInfo(), pfsFormat(), pfsFormatSub(), pfsGetMaxIndex(), pfsInodeCreate(), and pfsMountSuperBlock().
getSubNumber
u32(* pfs_block_device_t::getSubNumber) (int fd)
Definition at line 166 of file libpfs.h.
Referenced by pfsFormat(), and pfsMountSuperBlock().
setPartitionError
void(* pfs_block_device_t::setPartitionError) (int fd)
Definition at line 168 of file libpfs.h.
Referenced by pfsCacheTransfer().
transfer
int(* pfs_block_device_t::transfer) (int fd, void *buffer, u32 sub, u32 sector, u32 size, u32 mode)
Definition at line 165 of file libpfs.h.
Referenced by _sync(), fileTransfer(), fileTransferRemainder(), pfsCacheTransfer(), pfsFioCloseFileSlot(), pfsFormat(), pfsFormatSub(), pfsFsckStat(), pfsJournalFlush(), pfsJournalReset(), pfsJournalResetThis(), pfsJournalRestore(), pfsJournalWrite(), pfsMountSuperBlock(), and pfsUpdateSuperBlock().
The documentation for this struct was generated from the following file:
iop/hdd/libpfs/include/libpfs.h