ps2sdk: iop_io_device_ops_t Struct Reference
iop_io_device_ops_t Struct Reference
#include <ioman_mod.h>
Data Fields
int(* io_init)(iop_io_device_t *)
int(* io_deinit)(iop_io_device_t *)
int(* io_format)(iop_io_file_t *)
int(* io_open)(iop_io_file_t *, const char *, int)
int(* io_close)(iop_io_file_t *)
int(* io_read)(iop_io_file_t *, void *, int)
int(* io_write)(iop_io_file_t *, void *, int)
int(* io_lseek)(iop_io_file_t *, int, int)
int(* io_ioctl)(iop_io_file_t *, unsigned long, void *)
int(* io_remove)(iop_io_file_t *, const char *)
int(* io_mkdir)(iop_io_file_t *, const char *)
int(* io_rmdir)(iop_io_file_t *, const char *)
int(* io_dopen)(iop_io_file_t *, const char *)
int(* io_dclose)(iop_io_file_t *)
int(* io_dread)(iop_io_file_t *, io_dirent_t *)
int(* io_getstat)(iop_io_file_t *, const char *, io_stat_t *)
int(* io_chstat)(iop_io_file_t *, const char *, io_stat_t *, unsigned int)
Detailed Description
Definition at line 71 of file ioman_mod.h.
Field Documentation
io_chstat
int(* iop_io_device_ops_t::io_chstat) (iop_io_file_t *, const char *, io_stat_t *, unsigned int)
Definition at line 88 of file ioman_mod.h.
Referenced by _start().
io_close
int(* iop_io_device_ops_t::io_close) (iop_io_file_t *)
Definition at line 76 of file ioman_mod.h.
Referenced by _start().
io_dclose
int(* iop_io_device_ops_t::io_dclose) (iop_io_file_t *)
Definition at line 85 of file ioman_mod.h.
Referenced by _start().
io_deinit
int(* iop_io_device_ops_t::io_deinit) (iop_io_device_t *)
Definition at line 73 of file ioman_mod.h.
Referenced by _start().
io_dopen
int(* iop_io_device_ops_t::io_dopen) (iop_io_file_t *, const char *)
Definition at line 84 of file ioman_mod.h.
Referenced by _start().
io_dread
int(* iop_io_device_ops_t::io_dread) (iop_io_file_t *, io_dirent_t *)
Definition at line 86 of file ioman_mod.h.
Referenced by _start().
io_format
int(* iop_io_device_ops_t::io_format) (iop_io_file_t *)
Definition at line 74 of file ioman_mod.h.
Referenced by _start().
io_getstat
int(* iop_io_device_ops_t::io_getstat) (iop_io_file_t *, const char *, io_stat_t *)
Definition at line 87 of file ioman_mod.h.
Referenced by _start().
io_init
int(* iop_io_device_ops_t::io_init) (iop_io_device_t *)
Definition at line 72 of file ioman_mod.h.
Referenced by _start().
io_ioctl
int(* iop_io_device_ops_t::io_ioctl) (iop_io_file_t *, unsigned long, void *)
Definition at line 80 of file ioman_mod.h.
Referenced by _start().
io_lseek
int(* iop_io_device_ops_t::io_lseek) (iop_io_file_t *, int, int)
Definition at line 79 of file ioman_mod.h.
Referenced by _start().
io_mkdir
int(* iop_io_device_ops_t::io_mkdir) (iop_io_file_t *, const char *)
Definition at line 82 of file ioman_mod.h.
Referenced by _start().
io_open
int(* iop_io_device_ops_t::io_open) (iop_io_file_t *, const char *, int)
Definition at line 75 of file ioman_mod.h.
Referenced by _start().
io_read
int(* iop_io_device_ops_t::io_read) (iop_io_file_t *, void *, int)
Definition at line 77 of file ioman_mod.h.
Referenced by _start().
io_remove
int(* iop_io_device_ops_t::io_remove) (iop_io_file_t *, const char *)
Definition at line 81 of file ioman_mod.h.
Referenced by _start().
io_rmdir
int(* iop_io_device_ops_t::io_rmdir) (iop_io_file_t *, const char *)
Definition at line 83 of file ioman_mod.h.
Referenced by _start().
io_write
int(* iop_io_device_ops_t::io_write) (iop_io_file_t *, void *, int)
Definition at line 78 of file ioman_mod.h.
Referenced by _start().
The documentation for this struct was generated from the following file:
iop/kernel/include/ioman_mod.h