ps2sdk: sceUsbdLddOps Struct Reference
sceUsbdLddOps Struct Reference
#include <usbd.h>
Data Fields
struct _UsbDriver * next
struct _UsbDriver * prev
char * name
int(* probe)(int devID)
int(* connect)(int devID)
int(* disconnect)(int devID)
u32 reserved1
u32 reserved2
u32 reserved3
u32 reserved4
u32 reserved5
void * gp
Detailed Description
USB driver bus event listener structure
Definition at line 45 of file usbd.h.
Field Documentation
connect
int(* sceUsbdLddOps::connect) (int devID)
Definition at line 50 of file usbd.h.
Referenced by connectNewDevice(), InitUSB(), probeDeviceTree(), and usb_mass_init().
disconnect
int(* sceUsbdLddOps::disconnect) (int devID)
Definition at line 51 of file usbd.h.
Referenced by flushPort(), InitUSB(), and usb_mass_init().
gp
void* sceUsbdLddOps::gp
Definition at line 57 of file usbd.h.
Referenced by connectNewDevice(), doRegisterAutoLoader(), doRegisterDriver(), flushPort(), and probeDeviceTree().
name
char* sceUsbdLddOps::name
short sweet name for your driver, like "usbmouse" or "pl2301"
Definition at line 48 of file usbd.h.
Referenced by connectNewDevice(), doRegisterAutoLoader(), doRegisterDriver(), InitUSB(), and usb_mass_init().
next
struct _UsbDriver* sceUsbdLddOps::next
Definition at line 46 of file usbd.h.
Referenced by connectNewDevice(), doRegisterAutoLoader(), doRegisterDriver(), doUnregisterDriver(), InitUSB(), and usb_mass_init().
prev
struct _UsbDriver * sceUsbdLddOps::prev
Definition at line 46 of file usbd.h.
Referenced by doRegisterAutoLoader(), doRegisterDriver(), doUnregisterDriver(), InitUSB(), and usb_mass_init().
probe
int(* sceUsbdLddOps::probe) (int devID)
Definition at line 49 of file usbd.h.
Referenced by connectNewDevice(), doRegisterAutoLoader(), doRegisterDriver(), InitUSB(), probeDeviceTree(), and usb_mass_init().
reserved1
u32 sceUsbdLddOps::reserved1
Definition at line 52 of file usbd.h.
Referenced by doRegisterAutoLoader(), and doRegisterDriver().
reserved2
u32 sceUsbdLddOps::reserved2
Definition at line 53 of file usbd.h.
Referenced by doRegisterAutoLoader(), and doRegisterDriver().
reserved3
u32 sceUsbdLddOps::reserved3
Definition at line 54 of file usbd.h.
reserved4
u32 sceUsbdLddOps::reserved4
Definition at line 55 of file usbd.h.
reserved5
u32 sceUsbdLddOps::reserved5
Definition at line 56 of file usbd.h.
The documentation for this struct was generated from the following file:
iop/usb/usbd/include/usbd.h