ps2sdk: iop_device_ops_t Struct Reference
iop_device_ops_t Struct Reference
#include <ioman.h>
Data Fields
int(* init)(iop_device_t *)
int(* deinit)(iop_device_t *)
int(* format)(iop_file_t *)
int(* open)(iop_file_t *, const char *, int)
int(* close)(iop_file_t *)
int(* read)(iop_file_t *, void *, int)
int(* write)(iop_file_t *, void *, int)
int(* lseek)(iop_file_t *, int, int)
int(* ioctl)(iop_file_t *, int, void *)
int(* remove)(iop_file_t *, const char *)
int(* mkdir)(iop_file_t *, const char *)
int(* rmdir)(iop_file_t *, const char *)
int(* dopen)(iop_file_t *, const char *)
int(* dclose)(iop_file_t *)
int(* dread)(iop_file_t *, io_dirent_t *)
int(* getstat)(iop_file_t *, const char *, io_stat_t *)
int(* chstat)(iop_file_t *, const char *, io_stat_t *, unsigned int)
int(* rename)(iop_file_t *, const char *, const char *)
int(* chdir)(iop_file_t *, const char *)
int(* sync)(iop_file_t *, const char *, int)
int(* mount)(iop_file_t *, const char *, const char *, int, void *, int)
int(* umount)(iop_file_t *, const char *)
s64(* lseek64)(iop_file_t *, s64, int)
int(* devctl)(iop_file_t *, const char *, int, void *, unsigned int, void *, unsigned int)
int(* symlink)(iop_file_t *, const char *, const char *)
int(* readlink)(iop_file_t *, const char *, char *, unsigned int)
int(* ioctl2)(iop_file_t *, int, void *, unsigned int, void *, unsigned int)
Detailed Description
Definition at line 69 of file ioman.h.
Field Documentation
chdir
int(* iop_device_ops_t::chdir) (iop_file_t *, const char *)
Definition at line 80 of file iomanX.h.
Referenced by path_common().
chstat
int(* iop_device_ops_t::chstat)(iop_file_t *, const char *, iox_stat_t *, unsigned int)
Definition at line 86 of file ioman.h.
close
int(* iop_device_ops_t::close)(iop_file_t *)
Definition at line 74 of file ioman.h.
Referenced by init_devfs().
dclose
int(* iop_device_ops_t::dclose)(iop_file_t *)
Definition at line 83 of file ioman.h.
Referenced by init_devfs().
deinit
int(* iop_device_ops_t::deinit)(iop_device_t *)
Definition at line 71 of file ioman.h.
Referenced by init_devfs().
devctl
int(* iop_device_ops_t::devctl) (iop_file_t *, const char *, int, void *, unsigned int, void *, unsigned int)
Definition at line 85 of file iomanX.h.
dopen
int(* iop_device_ops_t::dopen)(iop_file_t *, const char *)
Definition at line 82 of file ioman.h.
Referenced by init_devfs().
dread
int(* iop_device_ops_t::dread)(iop_file_t *, iox_dirent_t *)
Definition at line 84 of file ioman.h.
Referenced by init_devfs().
format
int(* iop_device_ops_t::format)(iop_file_t *, const char *, const char *, void *, int)
Definition at line 72 of file ioman.h.
getstat
int(* iop_device_ops_t::getstat)(iop_file_t *, const char *, iox_stat_t *)
Definition at line 85 of file ioman.h.
Referenced by init_devfs().
init
int(* iop_device_ops_t::init)(iop_device_t *)
Definition at line 70 of file ioman.h.
Referenced by init_devfs().
ioctl
int(* iop_device_ops_t::ioctl)(iop_file_t *, int, void *)
Definition at line 78 of file ioman.h.
Referenced by init_devfs().
ioctl2
int(* iop_device_ops_t::ioctl2) (iop_file_t *, int, void *, unsigned int, void *, unsigned int)
Definition at line 88 of file iomanX.h.
Referenced by init_devfs().
lseek
int(* iop_device_ops_t::lseek)(iop_file_t *, int, int)
Definition at line 77 of file ioman.h.
lseek64
s64(* iop_device_ops_t::lseek64) (iop_file_t *, s64, int)
Definition at line 84 of file iomanX.h.
mkdir
int(* iop_device_ops_t::mkdir)(iop_file_t *, const char *, int)
Definition at line 80 of file ioman.h.
Referenced by path_common().
mount
int(* iop_device_ops_t::mount) (iop_file_t *, const char *, const char *, int, void *, int)
Definition at line 82 of file iomanX.h.
open
int(* iop_device_ops_t::open)(iop_file_t *, const char *, int, int)
Definition at line 73 of file ioman.h.
Referenced by init_devfs().
read
int(* iop_device_ops_t::read)(iop_file_t *, void *, int)
Definition at line 75 of file ioman.h.
Referenced by init_devfs().
readlink
int(* iop_device_ops_t::readlink) (iop_file_t *, const char *, char *, unsigned int)
Definition at line 87 of file iomanX.h.
remove
int(* iop_device_ops_t::remove)(iop_file_t *, const char *)
Definition at line 79 of file ioman.h.
rename
int(* iop_device_ops_t::rename) (iop_file_t *, const char *, const char *)
Definition at line 79 of file iomanX.h.
rmdir
int(* iop_device_ops_t::rmdir)(iop_file_t *, const char *)
Definition at line 81 of file ioman.h.
Referenced by path_common().
symlink
int(* iop_device_ops_t::symlink) (iop_file_t *, const char *, const char *)
Definition at line 86 of file iomanX.h.
sync
int(* iop_device_ops_t::sync) (iop_file_t *, const char *, int)
Definition at line 81 of file iomanX.h.
Referenced by path_common().
umount
int(* iop_device_ops_t::umount) (iop_file_t *, const char *)
Definition at line 83 of file iomanX.h.
write
int(* iop_device_ops_t::write)(iop_file_t *, void *, int)
Definition at line 76 of file ioman.h.
The documentation for this struct was generated from the following files:
iop/kernel/include/ioman.h
iop/kernel/include/iomanX.h