ps2sdk: iop/tcpip/tcpip-base/include/arch/sys_arch.h File Reference
sys_arch.h File Reference
Data Structures
struct arch_message
Macros
#define SYS_MBOX_NULL -1
#define SYS_SEM_NULL -1
#define SYS_MAX_MESSAGES (MEMP_NUM_TCPIP_MSG_API+MEMP_NUM_TCPIP_MSG_INPKT)
Typedefs
typedef int sys_prot_t
typedef int sys_sem_t
typedef int sys_mbox_t
typedef int sys_thread_t
Functions
void * malloc (size_t size)
void free (void *ptr)
void * calloc (size_t n, size_t size)
Macro Definition Documentation
SYS_MAX_MESSAGES
#define SYS_MAX_MESSAGES (MEMP_NUM_TCPIP_MSG_API+MEMP_NUM_TCPIP_MSG_INPKT)
Definition at line 12 of file sys_arch.h.
SYS_MBOX_NULL
#define SYS_MBOX_NULL -1
Definition at line 9 of file sys_arch.h.
SYS_SEM_NULL
#define SYS_SEM_NULL -1
Definition at line 10 of file sys_arch.h.
Typedef Documentation
sys_mbox_t
typedef int sys_mbox_t
Definition at line 6 of file sys_arch.h.
sys_prot_t
typedef int sys_prot_t
Definition at line 4 of file sys_arch.h.
sys_sem_t
typedef int sys_sem_t
Definition at line 5 of file sys_arch.h.
sys_thread_t
typedef int sys_thread_t
Definition at line 7 of file sys_arch.h.
Function Documentation
calloc()
void* calloc (size_t n, size_t size)
Definition at line 307 of file alloc.c.
 {
         void *ptr = NULL;
         size_t sz = n * size;
         if ((ptr = malloc(sz)) == NULL)
                 return ptr;
         memset(ptr, 0, sz);
         return ptr;
 }
References ALLOC_LAST, AllocSysMemory(), CpuResumeIntr(), CpuSuspendIntr(), memset(), and NULL.
free()
void free (void * ptr)
Definition at line 63 of file main.c.
 {
     int OldState;
     CpuSuspendIntr(&OldState);
     FreeSysMemory(ptr);
     CpuResumeIntr(OldState);
 }
malloc()
void* malloc (size_t size)
Definition at line 144 of file alloc.c.
 {
         void *ptr = NULL, *mem_ptr;
         heap_mem_header_t *new_mem, *prev_mem;
         size_t mem_sz, heap_align_bytes;
         mem_sz = size + sizeof(heap_mem_header_t);
         if ((mem_sz & (DEFAULT_ALIGNMENT - 1)) != 0)
                 mem_sz = ALIGN(mem_sz, DEFAULT_ALIGNMENT);
         alloc_lock();
         /* If we don't have any allocated blocks, reserve the first block from
            the OS and initialize __alloc_heap_tail.  */
         if (__alloc_heap_head == NULL) {
                 /* Align the bottom of the heap to our default alignment.  */
                 if (__alloc_heap_base == NULL) {
                         heap_align_bytes = (u32)alloc_sbrk(0) & (DEFAULT_ALIGNMENT - 1);
                         alloc_sbrk(heap_align_bytes);
                         __alloc_heap_base = alloc_sbrk(0);
                 }
                 /* Allocate the physical heap and setup the head block.  */
                 if ((mem_ptr = alloc_sbrk(mem_sz)) == (void *)-1)
                         return ptr;     /* NULL */
                 ptr = (void *)((u32)mem_ptr + sizeof(heap_mem_header_t));
                 __alloc_heap_head       = (heap_mem_header_t *)mem_ptr;
                 __alloc_heap_head->ptr  = ptr;
                 __alloc_heap_head->size = mem_sz - sizeof(heap_mem_header_t);
                 __alloc_heap_head->prev = NULL;
                 __alloc_heap_head->next = NULL;
                 __alloc_heap_tail = __alloc_heap_head;
                 alloc_unlock();
                 return ptr;
         }
         /* Check to see if there's free space at the bottom of the heap.  */
         if ((__alloc_heap_base + mem_sz) < (void *)__alloc_heap_head) {
                 new_mem = (heap_mem_header_t *)__alloc_heap_base;
                 ptr     = (void *)((u32)new_mem + sizeof(heap_mem_header_t));
                 new_mem->ptr  = ptr;
                 new_mem->size = mem_sz - sizeof(heap_mem_header_t);
                 new_mem->prev = NULL;
                 new_mem->next = __alloc_heap_head;
                 new_mem->next->prev = new_mem;
                 __alloc_heap_head = new_mem;
                 alloc_unlock();
                 return ptr;
         }
         /* See if we can allocate the block without extending the heap. */
         prev_mem = _heap_mem_fit(__alloc_heap_head, mem_sz);
         if (prev_mem != NULL) {
                 new_mem = (heap_mem_header_t *)((u32)prev_mem->ptr + prev_mem->size);
                 ptr     = (void *)((u32)new_mem + sizeof(heap_mem_header_t));
                 new_mem->ptr  = ptr;
                 new_mem->size = mem_sz - sizeof(heap_mem_header_t);
                 new_mem->prev = prev_mem;
                 new_mem->next = prev_mem->next;
                 new_mem->next->prev = new_mem;
                 prev_mem->next = new_mem;
                 alloc_unlock();
                 return ptr;
         }
         /* Extend the heap, but make certain the block is inserted in
            order. */
         if ((mem_ptr = alloc_sbrk(mem_sz)) == (void *)-1) {
                 alloc_unlock();
                 return ptr;     /* NULL */
         }
         ptr = (void *)((u32)mem_ptr + sizeof(heap_mem_header_t));
         new_mem       = (heap_mem_header_t *)mem_ptr;
         new_mem->ptr  = ptr;
         new_mem->size = mem_sz - sizeof(heap_mem_header_t);
         new_mem->prev = __alloc_heap_tail;
         new_mem->next = NULL;
         __alloc_heap_tail->next = new_mem;
         __alloc_heap_tail       = new_mem;
         alloc_unlock();
         return ptr;
 }
References ALLOC_LAST, AllocSysMemory(), CpuResumeIntr(), CpuSuspendIntr(), and NULL.
Referenced by calloc(), memalign(), and realloc().