ps2sdk: iop/kernel/include/sysclib.h File Reference
sysclib.h File Reference
#include <types.h>
#include <irx.h>
#include <stdarg.h>
#include <setjmp.h>
Macros
#define toupper(c) _toupper(c)
#define tolower(c) _tolower(c)
#define sysclib_IMPORTS_start DECLARE_IMPORT_TABLE(sysclib, 1, 1)
#define sysclib_IMPORTS_end END_IMPORT_TABLE
#define I_setjmp DECLARE_IMPORT(4, setjmp)
#define I_longjmp DECLARE_IMPORT(5, longjmp)
#define I_toupper DECLARE_IMPORT(6, _toupper)
#define I_tolower DECLARE_IMPORT(7, _tolower)
#define I_look_ctype_table DECLARE_IMPORT(8, look_ctype_table)
#define I_get_ctype_table DECLARE_IMPORT(9, get_ctype_table)
#define I_memchr DECLARE_IMPORT(10, memchr)
#define I_memcmp DECLARE_IMPORT(11, memcmp)
#define I_memcpy DECLARE_IMPORT(12, memcpy)
#define I_memmove DECLARE_IMPORT(13, memmove)
#define I_memset DECLARE_IMPORT(14, memset)
#define I_bcmp DECLARE_IMPORT(15, bcmp);
#define I_bcopy DECLARE_IMPORT(16, bcopy);
#define I_bzero DECLARE_IMPORT(17, bzero);
#define I_prnt DECLARE_IMPORT(18, prnt)
#define I_sprintf DECLARE_IMPORT(19, sprintf)
#define I_strcat DECLARE_IMPORT(20, strcat)
#define I_strchr DECLARE_IMPORT(21, strchr)
#define I_strcmp DECLARE_IMPORT(22, strcmp)
#define I_strcpy DECLARE_IMPORT(23, strcpy)
#define I_strcspn DECLARE_IMPORT(24, strcspn)
#define I_index DECLARE_IMPORT(25, index)
#define I_rindex DECLARE_IMPORT(26, rindex)
#define I_strlen DECLARE_IMPORT(27, strlen)
#define I_strncat DECLARE_IMPORT(28, strncat)
#define I_strncmp DECLARE_IMPORT(29, strncmp)
#define I_strncpy DECLARE_IMPORT(30, strncpy)
#define I_strpbrk DECLARE_IMPORT(31, strpbrk)
#define I_strrchr DECLARE_IMPORT(32, strrchr)
#define I_strspn DECLARE_IMPORT(33, strspn)
#define I_strstr DECLARE_IMPORT(34, strstr)
#define I_strtok DECLARE_IMPORT(35, strtok)
#define I_strtol DECLARE_IMPORT(36, strtol)
#define I_atob DECLARE_IMPORT(37, atob)
#define I_strtoul DECLARE_IMPORT(38, strtoul)
#define I_wmemcopy DECLARE_IMPORT(40, wmemcopy)
#define I_wmemset DECLARE_IMPORT(41, wmemset)
#define I_vsprintf DECLARE_IMPORT(42, vsprintf)
#define I_strtok_r DECLARE_IMPORT(43, strtok_r)
Typedefs
typedef void(* print_callback_t) (void *context, int c)
Functions
char _toupper (char c)
char _tolower (char c)
unsigned char look_ctype_table (char character)
void * get_ctype_table ()
void * memchr (const void *s, int c, size_t n)
int memcmp (const void *p, const void *q, size_t size)
void * memcpy (void *dest, const void *src, size_t size)
void * memmove (void *dest, const void *src, size_t size)
void * memset (void *ptr, int c, size_t size)
int bcmp (const void *, const void *, size_t)
void bcopy (const void *, void *, size_t)
void bzero (void *, size_t)
int prnt (print_callback_t, void *context, const char *format, va_list ap)
int sprintf (char *str, const char *format,...)
char * strcat (char *dest, const char *src)
char * strchr (const char *s, int c)
int strcmp (const char *p, const char *q)
char * strcpy (char *dest, const char *src)
size_t strcspn (const char *s, const char *reject)
char * index (const char *s, int c)
char * rindex (const char *s, int c)
size_t strlen (const char *s)
char * strncat (char *dest, const char *src, size_t size)
int strncmp (const char *p, const char *q, size_t size)
char * strncpy (char *dest, const char *src, size_t size)
char * strpbrk (const char *s, const char *accept)
char * strrchr (const char *s, int c)
size_t strspn (const char *s, const char *accept)
char * strstr (const char *haystack, const char *needle)
char * strtok (char *s, const char *delim)
long strtol (const char *s, char **endptr, int base)
char * atob (char *s, int *i)
unsigned long strtoul (const char *s, char **endptr, int base)
void * wmemcopy (u32 *dest, const u32 *src, size_t size)
void * wmemset (u32 *dest, u32 c, size_t size)
int vsprintf (char *, const char *, va_list)
char * strtok_r (char *s, const char *delim, char **lasts)
Detailed Description
Standard C Library subset.
Definition in file sysclib.h.
Macro Definition Documentation
I_atob
#define I_atob DECLARE_IMPORT(37, atob)
Definition at line 117 of file sysclib.h.
I_bcmp
#define I_bcmp DECLARE_IMPORT(15, bcmp);
Definition at line 95 of file sysclib.h.
I_bcopy
#define I_bcopy DECLARE_IMPORT(16, bcopy);
Definition at line 96 of file sysclib.h.
I_bzero
#define I_bzero DECLARE_IMPORT(17, bzero);
Definition at line 97 of file sysclib.h.
I_get_ctype_table
#define I_get_ctype_table DECLARE_IMPORT(9, get_ctype_table)
Definition at line 89 of file sysclib.h.
I_index
#define I_index DECLARE_IMPORT(25, index)
Definition at line 105 of file sysclib.h.
I_longjmp
#define I_longjmp DECLARE_IMPORT(5, longjmp)
Definition at line 85 of file sysclib.h.
I_look_ctype_table
#define I_look_ctype_table DECLARE_IMPORT(8, look_ctype_table)
Definition at line 88 of file sysclib.h.
I_memchr
#define I_memchr DECLARE_IMPORT(10, memchr)
Definition at line 90 of file sysclib.h.
I_memcmp
#define I_memcmp DECLARE_IMPORT(11, memcmp)
Definition at line 91 of file sysclib.h.
I_memcpy
#define I_memcpy DECLARE_IMPORT(12, memcpy)
Definition at line 92 of file sysclib.h.
I_memmove
#define I_memmove DECLARE_IMPORT(13, memmove)
Definition at line 93 of file sysclib.h.
I_memset
#define I_memset DECLARE_IMPORT(14, memset)
Definition at line 94 of file sysclib.h.
I_prnt
#define I_prnt DECLARE_IMPORT(18, prnt)
Definition at line 98 of file sysclib.h.
I_rindex
#define I_rindex DECLARE_IMPORT(26, rindex)
Definition at line 106 of file sysclib.h.
I_setjmp
#define I_setjmp DECLARE_IMPORT(4, setjmp)
Definition at line 84 of file sysclib.h.
I_sprintf
#define I_sprintf DECLARE_IMPORT(19, sprintf)
Definition at line 99 of file sysclib.h.
I_strcat
#define I_strcat DECLARE_IMPORT(20, strcat)
Definition at line 100 of file sysclib.h.
I_strchr
#define I_strchr DECLARE_IMPORT(21, strchr)
Definition at line 101 of file sysclib.h.
I_strcmp
#define I_strcmp DECLARE_IMPORT(22, strcmp)
Definition at line 102 of file sysclib.h.
I_strcpy
#define I_strcpy DECLARE_IMPORT(23, strcpy)
Definition at line 103 of file sysclib.h.
I_strcspn
#define I_strcspn DECLARE_IMPORT(24, strcspn)
Definition at line 104 of file sysclib.h.
I_strlen
#define I_strlen DECLARE_IMPORT(27, strlen)
Definition at line 107 of file sysclib.h.
I_strncat
#define I_strncat DECLARE_IMPORT(28, strncat)
Definition at line 108 of file sysclib.h.
I_strncmp
#define I_strncmp DECLARE_IMPORT(29, strncmp)
Definition at line 109 of file sysclib.h.
I_strncpy
#define I_strncpy DECLARE_IMPORT(30, strncpy)
Definition at line 110 of file sysclib.h.
I_strpbrk
#define I_strpbrk DECLARE_IMPORT(31, strpbrk)
Definition at line 111 of file sysclib.h.
I_strrchr
#define I_strrchr DECLARE_IMPORT(32, strrchr)
Definition at line 112 of file sysclib.h.
I_strspn
#define I_strspn DECLARE_IMPORT(33, strspn)
Definition at line 113 of file sysclib.h.
I_strstr
#define I_strstr DECLARE_IMPORT(34, strstr)
Definition at line 114 of file sysclib.h.
I_strtok
#define I_strtok DECLARE_IMPORT(35, strtok)
Definition at line 115 of file sysclib.h.
I_strtok_r
#define I_strtok_r DECLARE_IMPORT(43, strtok_r)
Definition at line 122 of file sysclib.h.
I_strtol
#define I_strtol DECLARE_IMPORT(36, strtol)
Definition at line 116 of file sysclib.h.
I_strtoul
#define I_strtoul DECLARE_IMPORT(38, strtoul)
Definition at line 118 of file sysclib.h.
I_tolower
#define I_tolower DECLARE_IMPORT(7, _tolower)
Definition at line 87 of file sysclib.h.
I_toupper
#define I_toupper DECLARE_IMPORT(6, _toupper)
Definition at line 86 of file sysclib.h.
I_vsprintf
#define I_vsprintf DECLARE_IMPORT(42, vsprintf)
Definition at line 121 of file sysclib.h.
I_wmemcopy
#define I_wmemcopy DECLARE_IMPORT(40, wmemcopy)
Definition at line 119 of file sysclib.h.
I_wmemset
#define I_wmemset DECLARE_IMPORT(41, wmemset)
Definition at line 120 of file sysclib.h.
sysclib_IMPORTS_end
#define sysclib_IMPORTS_end END_IMPORT_TABLE
Definition at line 82 of file sysclib.h.
sysclib_IMPORTS_start
#define sysclib_IMPORTS_start DECLARE_IMPORT_TABLE(sysclib, 1, 1)
Definition at line 81 of file sysclib.h.
tolower
#define tolower (c) _tolower(c)
Definition at line 42 of file sysclib.h.
toupper
#define toupper (c) _toupper(c)
Definition at line 35 of file sysclib.h.
Typedef Documentation
print_callback_t
typedef void(* print_callback_t) (void *context, int c)
Definition at line 24 of file sysclib.h.
Function Documentation
_tolower()
char _tolower (char c)
_toupper()
char _toupper (char c)
atob()
char* atob (char * s, int * i)
bcmp()
int bcmp (const void * , const void * , size_t)
bcopy()
void bcopy (const void * , void * , size_t)
bzero()
void bzero (void * , size_t)
Referenced by smap_init().
get_ctype_table()
void* get_ctype_table ()
index()
char* index (const char * s, int c)
Referenced by ClearBufferLen(), doControlTransfer(), fat_setFatDirChain(), find_iop_device(), fio_openDir(), getIndexRead(), getIndexWrite(), HubControlTransfer(), link_common(), mcman_cachePS1dirs(), mcman_readdirentryPS1(), mcman_readpage(), McReadDirEntry(), McReadPage(), McReplaceBadBlock(), McWritePage(), pfsBitmapAllocFree(), pfsBitmapFreeInodeBlocks(), pfsFixIndex(), PS2CamGetDeviceSring(), PS2CamOpenDevice(), scache_allocSector(), scache_flushSector(), scache_invalidate(), scache_readSector(), scache_writeSector(), sceUsbdControlTransfer(), setupTransferData(), smb_NetShareEnum(), and usb_getstring().
look_ctype_table()
unsigned char look_ctype_table (char character)
memchr()
void* memchr (const void * s, int c, size_t n)
memcmp()
int memcmp (const void * p, const void * q, size_t size)
Referenced by apaFindPartition(), apaOpen(), apaPassCmp(), apaRemove(), apaRename(), devscan_getmodule(), getAentry(), getFileSlot(), iopmgr_get_iomandev(), iopmgr_get_iomanxdev(), pfsGetDentry(), slib_get_lib_by_name(), smb_Echo(), smod_get_mod_by_name(), smod_get_modcount_by_name(), and updateDirectoryParent().
memcpy()
void* memcpy (void * dest, const void * src, size_t size)
Referenced by _McRead2(), _sif2_cmd_dbg_control(), _sync(), AddPassword(), AHXPlayer_SetAudio(), apaEncryptPassword(), apaFillHeader(), apaGetTime(), apaOpen(), apaRename(), ata_device_sce_sec_set_password(), ata_device_sce_sec_unlock(), audsrv_play_audio(), BuildConfigurationROM(), callbackThreadFunc(), cdfs_getVolumeDescriptor(), cdfs_readSect(), devctlSwapTemp(), devfs_create_device(), do_accept(), do_getpeername(), do_getsockname(), do_getsockopt(), do_ps2mouse_read(), do_recv(), do_recvfrom(), do_send(), do_sendto(), do_setsockopt(), dread(), fat_readFile(), fat_readSingleSector(), fat_renameFile(), fat_writeFile(), fat_writeSingleSector(), fileTransferRemainder(), fio_dread(), fio_getstat(), fio_read(), fioGetStatFiller(), fioInputBreaker(), fioStatFiller(), flash_get_info(), hddFormat(), hook_ioman(), hubDrvConnect(), ioctl2AttrAdd(), ioctl2AttrLookUp(), ioctl2AttrRead(), list_all_libraries(), LM_Password_Hash(), LM_Response(), mc_chstat(), mcman_clearsuperblock(), mcman_dread1(), mcman_dread2(), mcman_format2(), mcman_getstat1(), mcman_getstat2(), mcman_read1(), mcman_read2(), mcman_readpage(), mcman_write1(), mcman_write2(), MD4(), memalign(), NetManRegisterNetIF(), NetManRegisterNetworkStack(), pfsBlockAllocNewSegment(), pfsFillDentry(), pfsFioChdir(), pfsFioChstat(), pfsFioReadlink(), pfsGetNextDentry(), pfsGetTime(), pfsInodeFill(), pfsInodeSetTime(), pfsMountSuperBlock(), PS2CamGetDeviceInfo(), ps2ip_getconfig(), ps2kbd_data_recv(), ps2kbd_init(), ps2kbd_ioctl_resetkeymap(), ps2kbd_ioctl_setaltmap(), ps2kbd_ioctl_setctrlmap(), ps2kbd_ioctl_setkeymap(), ps2kbd_ioctl_setspecialmap(), ps2netfs_op_dread(), realloc(), sceSdSetEffectAttr(), setSfnEntryFromOld(), smb_Echo(), smb_LogOn(), smb_NegotiateProtocol(), smb_NetShareEnum(), smb_OpenShare(), smb_TreeConnectAndX(), smod_get_next_mod(), stat2statx(), statx2stat(), ttyfs_write(), and usb_queue_cmd().
memmove()
void* memmove (void * dest, const void * src, size_t size)
Referenced by cdfs_readSect().
memset()
void* memset (void * ptr, int c, size_t size)
Referenced by _McEraseBlock(), _McReadPage(), _start(), AHX_ClearSoundBuffers(), AHXOutput_MixBuffer(), AHXPlayer_LoadSongBuffer(), AHXVoice_Init(), allocateMountBuffer(), apaCacheInit(), apaFillHeader(), apaGetIlinkID(), apaJournalReset(), apaMakeEmpty(), apaOpen(), apaRemovePartition(), apaSaveError(), ata_device_sce_sec_set_password(), ata_device_sce_sec_unlock(), ata_init_devices(), ata_intr_cb(), calloc(), cdda_procedure(), cdfs_readSect(), createDirectorySpace(), deinitialize_rpc_client(), devctlSwapTemp(), devfs_create_device(), devfs_fill_dirent(), devfs_getstat(), DevFSAddSubDevice(), devscan_setup(), do_ps2mouse_reset(), do_ps2mouse_setreadmode(), enlargeDirentryClusterSpace(), fat_fillDirentryInfo(), fat_getFileStartCluster(), fdh_setup(), fileXio_GetDir_RPC(), fioGetInput(), flash_get_info(), flushbuffer(), fs_dopen(), fs_dread(), fs_getstat(), hddClose(), hddFormat(), httpOpen(), hubDrvConnect(), ieee1394_InitializeFetchAgent(), ieee1394_SendCommandBlockORB(), ieee1394_SendManagementORB(), init_devfs(), initHcdStructs(), initHubDriver(), InitializeSCSIDevice(), ioctl2AddSub(), list_all_libraries(), LM_Response(), mass_stor_warmup(), mcman_cachePS1dirs(), mcman_clearcache(), mcman_clearsuperblock(), mcman_close1(), mcman_fillPS1backuparea(), mcman_flushcacheentry(), mcman_format1(), mcman_format2(), mcman_getdir1(), mcman_initcache(), mcman_initPS1PDAcom(), mcman_setPS1devinfos(), MD4(), NETMAN_rpc_handler(), NetManDeinitRPCClient(), NetManInitRPCClient(), NetManUnregisterNetworkStack(), NTLM_Password_Hash(), openFile(), OpenTCPSession(), pfsBlockAllocNewSegment(), pfsCacheInit(), pfsClearMount(), pfsFillSelfAndParentDentries(), pfsFioCloseFileSlot(), pfsFormat(), pfsInodeFill(), pfsJournalReset(), pfsJournalResetThis(), pfsPrintBitmap(), play_thread(), PS2CamInitDriver(), ps2ip_getconfig(), ps2kbd_connect(), ps2kbd_data_recv(), ps2kbd_getstring_set(), ps2kbd_init(), ps2mouse_getstring_set(), ps2mouse_init(), ps2netfs_op_dread(), ps2netfs_serv(), RemovePowerOffHandler(), scsi_warmup(), setShortNameSequence(), smb_close(), smb_dread(), smb_FindFirstNext2(), and smb_getstat().
prnt()
int prnt (print_callback_t , void * context, const char * format, va_list ap)
Referenced by _kPrintf().
rindex()
char* rindex (const char * s, int c)
sprintf()
int sprintf (char * str, const char * format, ...)
Referenced by _start(), pfsPrintBitmap(), setShortNameSequence(), smb_GetShareList(), and smb_OpenShare().
strcat()
char* strcat (char * dest, const char * src)
Referenced by devfs_fill_dirent(), fd_name(), findPath(), mcman_clearsuperblock(), mcman_format2(), prepare_path(), and smb_dopen().
strchr()
char* strchr (const char * s, int c)
Referenced by fioInputBreaker(), and pfsGetBlockDeviceTable().
strcmp()
int strcmp (const char * p, const char * q)
Referenced by _start(), DelDrv(), find_iop_device(), fio_open(), fioGetInput(), fioPartitionSizeLookUp(), mcman_chdir(), mcman_checkdirpath(), mcman_getPS1direntry(), mcman_setdevinfos(), mcman_setinfo1(), mcman_setinfo2(), McReplaceBadBlock(), NetManSetMainIF(), NetManUnregisterNetIF(), pfsFioRename(), pfsGetBlockDeviceTable(), pfsGetDentry(), pfsInodeGetFileInDir(), smap_init(), and smb_GetShareList().
strcpy()
char* strcpy (char * dest, const char * src)
Referenced by AHXPlayer_LoadSongBuffer(), apaMakeEmpty(), apaRemovePartition(), cdfs_cacheDir(), cdfs_getDir(), cdfs_prepare(), devctlSwapTemp(), devfs_fill_dirent(), devscan_getdevlist(), fat_renameFile(), fd_name(), findPath(), fs_dread(), getStringField(), hddFormat(), iopmgr_get_devicelist(), mcman_clearsuperblock(), mcman_dread2(), mcman_format2(), NetManQueryMainIF(), openFile(), PS2CamGetDeviceInfo(), ps2ip_getconfig(), resolveAddress(), separatePathAndName(), setStringField(), and smb_NegotiateProtocol().
strcspn()
size_t strcspn (const char * s, const char * reject)
strlen()
size_t strlen (const char * s)
Referenced by AddPassword(), AHXPlayer_LoadSongBuffer(), cdfs_cacheDir(), cdfs_getDir(), createShortNameMask(), devfs_check_devname(), devfs_create_device(), devfs_fill_dirent(), devfs_find_devicename(), devfs_getstat(), devfs_ioctl2(), devfs_open(), devscan_getdevlist(), devscan_getmodule(), devscan_setup(), fioInputBreaker(), getAentry(), getDirentrySize(), getStringField(), hddDread(), httpConnect(), ioctl2AttrAdd(), iopmgr_get_devicelist(), iopmgr_get_iomandev(), iopmgr_get_iomanxdev(), isErrorHeader(), list_fs_devices(), mcman_cachedirentry(), mcman_chdir(), mcman_getdirinfo(), mcman_modloadcb(), NTLM_Password_Hash(), parseContentLength(), pfsFillDentry(), pfsFioReadlink(), pfsFioRmdir(), pfsGetDentry(), prepare_path(), ps2netfs_op_devlist(), resolveAddress(), saveDirentry(), sbus_tty_puts(), separatePathAndName(), setShortNameSequence(), setStringField(), slib_get_lib_by_name(), smb_chdir(), smb_dopen(), smb_NegotiateProtocol(), smb_NetShareEnum(), smod_get_mod_by_name(), smod_get_modcount_by_name(), and vxprintf().
strncat()
char* strncat (char * dest, const char * src, size_t size)
strncmp()
int strncmp (const char * p, const char * q, size_t size)
Referenced by apaFillHeader(), apaReadHeader(), cdfs_getVolumeDescriptor(), cmdline_handle(), devfs_find_devicename(), devscan_gettype(), mcman_checkdirpath(), mcman_getdirinfo(), mcman_setdevinfos(), ParseParams(), and smap_init().
strncpy()
char* strncpy (char * dest, const char * src, size_t size)
Referenced by _start(), apaGetPartErrorName(), compareTocEntry(), copyToTocEntry(), devfs_ioctl2(), devscan_setup(), DirEntryCopy(), dread(), fileXio_GetDeviceList_RPC(), find_iop_device(), fio_dread(), getStringField(), hddDread(), ioman_dread(), LM_Password_Hash(), mcman_chdir(), mcman_dread1(), mcman_getdir1(), mcman_getdir2(), mcman_open1(), mcman_open2(), mcman_setinfo1(), mcman_setinfo2(), pfsGetBlockDeviceTable(), prepare_path(), ps2netfs_op_dread(), separatePathAndName(), smb_chdir(), smb_Connect(), smb_dopen(), smb_dread(), smb_NetShareEnum(), smb_open(), and splitPath().
strpbrk()
char* strpbrk (const char * s, const char * accept)
strrchr()
char* strrchr (const char * s, int c)
Referenced by _start(), compareTocEntry(), findPath(), separatePathAndName(), and splitPath().
strspn()
size_t strspn (const char * s, const char * accept)
strstr()
char* strstr (const char * haystack, const char * needle)
Referenced by httpConnect(), isErrorHeader(), and parseContentLength().
strtok()
char* strtok (char * s, const char * delim)
Referenced by compareTocEntry(), copyToTocEntry(), and findPath().
strtok_r()
char* strtok_r (char * s, const char * delim, char ** lasts)
strtol()
long strtol (const char * s, char ** endptr, int base)
Referenced by _start(), find_iop_device(), getShortNameSequence(), isErrorHeader(), parseContentLength(), ParseParams(), and resolveAddress().
strtoul()
unsigned long strtoul (const char * s, char ** endptr, int base)
Referenced by _start(), devfs_getstat(), devfs_open(), and smap_init().
vsprintf()
int vsprintf (char * , const char * , va_list)
wmemcopy()
void* wmemcopy (u32 * dest, const u32 * src, size_t size)
wmemset()
void* wmemset (u32 * dest, u32 c, size_t size)