ps2sdk: iop/kernel/include/sysmem.h File Reference
sysmem.h File Reference
#include <types.h>
#include <irx.h>
#include <stdarg.h>
Macros
#define ALLOC_FIRST 0
#define ALLOC_LAST 1
#define ALLOC_ADDRESS 2
#define USED 0x00000000
#define FREE 0x80000000
#define sysmem_IMPORTS_start DECLARE_IMPORT_TABLE(sysmem, 1, 1)
#define sysmem_IMPORTS_end END_IMPORT_TABLE
#define I_AllocSysMemory DECLARE_IMPORT(4, AllocSysMemory)
#define I_FreeSysMemory DECLARE_IMPORT(5, FreeSysMemory)
#define I_QueryMemSize DECLARE_IMPORT(6, QueryMemSize)
#define I_QueryMaxFreeMemSize DECLARE_IMPORT(7, QueryMaxFreeMemSize)
#define I_QueryTotalFreeMemSize DECLARE_IMPORT(8, QueryTotalFreeMemSize)
#define I_QueryBlockTopAddress DECLARE_IMPORT(9, QueryBlockTopAddress)
#define I_QueryBlockSize DECLARE_IMPORT(10, QueryBlockSize)
#define I_Kprintf DECLARE_IMPORT(14, Kprintf)
#define I_KprintfSet DECLARE_IMPORT(15, KprintfSet)
Typedefs
typedef int() KprintfHandler_t(void *context, const char *format, va_list ap)
Functions
void * AllocSysMemory (int mode, int size, void *ptr)
int FreeSysMemory (void *ptr)
u32 QueryMemSize ()
u32 QueryMaxFreeMemSize ()
u32 QueryTotalFreeMemSize ()
void * QueryBlockTopAddress (void *address)
int QueryBlockSize (void *address)
int Kprintf (const char *format,...)
void KprintfSet (KprintfHandler_t *, void *context)
Detailed Description
System memory manager.
Definition in file sysmem.h.
Macro Definition Documentation
ALLOC_ADDRESS
#define ALLOC_ADDRESS 2
Definition at line 26 of file sysmem.h.
ALLOC_FIRST
#define ALLOC_FIRST 0
Definition at line 24 of file sysmem.h.
ALLOC_LAST
#define ALLOC_LAST 1
Definition at line 25 of file sysmem.h.
FREE
#define FREE 0x80000000
Definition at line 30 of file sysmem.h.
I_AllocSysMemory
#define I_AllocSysMemory DECLARE_IMPORT(4, AllocSysMemory)
Definition at line 50 of file sysmem.h.
I_FreeSysMemory
#define I_FreeSysMemory DECLARE_IMPORT(5, FreeSysMemory)
Definition at line 51 of file sysmem.h.
I_Kprintf
#define I_Kprintf DECLARE_IMPORT(14, Kprintf)
Definition at line 57 of file sysmem.h.
I_KprintfSet
#define I_KprintfSet DECLARE_IMPORT(15, KprintfSet)
Definition at line 58 of file sysmem.h.
I_QueryBlockSize
#define I_QueryBlockSize DECLARE_IMPORT(10, QueryBlockSize)
Definition at line 56 of file sysmem.h.
I_QueryBlockTopAddress
#define I_QueryBlockTopAddress DECLARE_IMPORT(9, QueryBlockTopAddress)
Definition at line 55 of file sysmem.h.
I_QueryMaxFreeMemSize
#define I_QueryMaxFreeMemSize DECLARE_IMPORT(7, QueryMaxFreeMemSize)
Definition at line 53 of file sysmem.h.
I_QueryMemSize
#define I_QueryMemSize DECLARE_IMPORT(6, QueryMemSize)
Definition at line 52 of file sysmem.h.
I_QueryTotalFreeMemSize
#define I_QueryTotalFreeMemSize DECLARE_IMPORT(8, QueryTotalFreeMemSize)
Definition at line 54 of file sysmem.h.
sysmem_IMPORTS_end
#define sysmem_IMPORTS_end END_IMPORT_TABLE
Definition at line 48 of file sysmem.h.
sysmem_IMPORTS_start
#define sysmem_IMPORTS_start DECLARE_IMPORT_TABLE(sysmem, 1, 1)
Definition at line 47 of file sysmem.h.
USED
#define USED 0x00000000
Definition at line 29 of file sysmem.h.
Typedef Documentation
KprintfHandler_t
typedef int() KprintfHandler_t(void *context, const char *format, va_list ap)
Definition at line 42 of file sysmem.h.
Function Documentation
AllocSysMemory()
void* AllocSysMemory (int mode, int size, void * ptr)
Referenced by _start(), AHX_Thread(), alloc_new_sample(), apaAllocMem(), calloc(), cdfs_prepare(), devfs_create_device(), devfs_open(), fileXio_Thread(), filexioRpc_SetRWBufferSize(), httpOpen(), initHcdStructs(), initHubDriver(), malloc(), pfsAllocMem(), PS2CamInitializeNewDevice(), ps2kbd_connect(), ps2kbd_init(), ps2mouse_connect(), sndStreamOpen(), and usb_getstring().
FreeSysMemory()
int FreeSysMemory (void * ptr)
Referenced by _exit(), apaFreeMem(), cdfs_finish(), devfs_close(), devfs_create_device(), devfs_delete_device(), devfs_ioctl(), devfs_ioctl2(), devfs_lseek(), devfs_lseek64(), devfs_open(), devfs_read(), devfs_write(), filexioRpc_SetRWBufferSize(), free(), free_all_samples(), httpClose(), httpOpen(), pfsFreeMem(), PS2CamInitializeNewDevice(), ps2kbd_disconnect(), ps2kbd_getstring_set(), ps2mouse_disconnect(), ps2mouse_getstring_set(), shutdown(), sndStreamClose(), sndStreamOpen(), and usb_getstring().
Kprintf()
int Kprintf (const char * format, ...)
KprintfSet()
void KprintfSet (KprintfHandler_t * , void * context)
Referenced by sbus_tty_init().
QueryBlockSize()
int QueryBlockSize (void * address)
QueryBlockTopAddress()
void* QueryBlockTopAddress (void * address)
QueryMaxFreeMemSize()
u32 QueryMaxFreeMemSize ()
Referenced by rpc_server().
QueryMemSize()
u32 QueryMemSize ()
QueryTotalFreeMemSize()
u32 QueryTotalFreeMemSize ()
Referenced by AHX_LoadSong(), and AHX_Thread().