ps2sdk: common/include/tamtypes.h File Reference
tamtypes.h File Reference
Macros
#define NULL (void *)0
Typedefs
typedef unsigned char u8
typedef unsigned short u16
typedef volatile u8 vu8
typedef volatile u16 vu16
typedef unsigned long u32
typedef unsigned long long u64
typedef volatile u32 vu32
typedef volatile u64 vu64
typedef signed char s8
typedef signed short s16
typedef volatile s8 vs8
typedef volatile s16 vs16
typedef signed long s32
typedef signed long long s64
typedef volatile s32 vs32
typedef volatile s64 vs64
Functions
static u8 _lb (u32 addr)
static u16 _lh (u32 addr)
static u32 _lw (u32 addr)
static void _sb (u8 val, u32 addr)
static void _sh (u16 val, u32 addr)
static void _sw (u32 val, u32 addr)
Detailed Description
Commonly used typedefs
Definition in file tamtypes.h.
Macro Definition Documentation
NULL
#define NULL (void *)0
Definition at line 91 of file tamtypes.h.
Typedef Documentation
s16
typedef signed short s16
Definition at line 52 of file tamtypes.h.
s32
typedef signed long s32
Definition at line 72 of file tamtypes.h.
s64
typedef signed long long s64
Definition at line 73 of file tamtypes.h.
s8
typedef signed char s8
Definition at line 51 of file tamtypes.h.
u16
typedef unsigned short u16
Definition at line 24 of file tamtypes.h.
u32
typedef unsigned long u32
Definition at line 44 of file tamtypes.h.
u64
typedef unsigned long long u64
Definition at line 45 of file tamtypes.h.
u8
typedef unsigned char u8
Definition at line 23 of file tamtypes.h.
vs16
typedef volatile s16 vs16
Definition at line 55 of file tamtypes.h.
vs32
typedef volatile s32 vs32
Definition at line 75 of file tamtypes.h.
vs64
typedef volatile s64 vs64
Definition at line 76 of file tamtypes.h.
vs8
typedef volatile s8 vs8
Definition at line 54 of file tamtypes.h.
vu16
typedef volatile u16 vu16
Definition at line 27 of file tamtypes.h.
vu32
typedef volatile u32 vu32
Definition at line 47 of file tamtypes.h.
vu64
typedef volatile u64 vu64
Definition at line 48 of file tamtypes.h.
vu8
typedef volatile u8 vu8
Definition at line 26 of file tamtypes.h.
Function Documentation
_lb()
static u8 _lb (u32 addr) inline static
Definition at line 94 of file tamtypes.h.
 { return *(vu8 *)addr; }
Referenced by sio2_data_in().
_lh()
static u16 _lh (u32 addr) inline static
Definition at line 95 of file tamtypes.h.
 { return *(vu16 *)addr; }
_lw()
static u32 _lw (u32 addr) inline static
Definition at line 96 of file tamtypes.h.
 { return *(vu32 *)addr; }
Referenced by sio2_ctrl_get(), sio2_portN_ctrl1_get(), sio2_portN_ctrl2_get(), sio2_regN_get(), sio2_stat6c_get(), sio2_stat70_get(), sio2_stat74_get(), sio2_stat_get(), sio2_unkn78_get(), and sio2_unkn7c_get().
_sb()
static void _sb (u8 val, u32 addr) inline static
Definition at line 98 of file tamtypes.h.
 { *(vu8 *)addr = val; }
Referenced by sio2_data_out().
_sh()
static void _sh (u16 val, u32 addr) inline static
Definition at line 99 of file tamtypes.h.
 { *(vu16 *)addr = val; }
_sw()
static void _sw (u32 val, u32 addr) inline static
Definition at line 100 of file tamtypes.h.
 { *(vu32 *)addr = val; }
Referenced by card_find_manfid(), expbay_init(), pcic_ssbus_mode(), pcmcia_init(), sio2_ctrl_set(), sio2_portN_ctrl1_set(), sio2_portN_ctrl2_set(), sio2_regN_set(), sio2_stat_set(), sio2_unkn78_set(), and sio2_unkn7c_set().