ps2sdk: iop/tcpip/tcpip-netman/src/ps2ip.c File Reference
ps2ip.c File Reference
#include <types.h>
#include <stdio.h>
#include <intrman.h>
#include <netman.h>
#include <loadcore.h>
#include <thbase.h>
#include <sysclib.h>
#include <thevent.h>
#include <sysmem.h>
#include <lwip/memp.h>
#include "lwip/sys.h"
#include "lwip/tcp.h"
#include "lwip/tcpip.h"
#include "lwip/prot/dhcp.h"
#include "lwip/netif.h"
#include "lwip/dhcp.h"
#include "lwip/inet.h"
#include "netif/etharp.h"
#include "ps2ip_internal.h"
Macros
#define MODNAME "TCP/IP Stack"
Functions
IRX_ID (MODNAME, 2, 3)
int ps2ip_getconfig (char *pszName, t_ip_info *pInfo)
int ps2ip_setconfig (const t_ip_info *pInfo)
static void InitDone (void *pvArg)
err_t ps2ip_input (PBuf *pInput, NetIF *pNetIF)
int _exit (int argc, char **argv)
static void LinkStateUp (void)
static void LinkStateDown (void)
static void * AllocRxPacket (unsigned int size, void **payload)
static void FreeRxPacket (void *packet)
static void EnQRxPacket (void *packet)
static int NextTxPacket (void **payload)
static void DeQTxPacket (void)
static void EnQTxPacket (struct pbuf *tx)
static err_t SMapLowLevelOutput (struct netif *pNetIF, struct pbuf *pOutput)
static err_t SMapIFInit (struct netif *pNetIF)
static int InitializeLWIP (void)
static int InitLWIPStack (IPAddr *IP, IPAddr *NM, IPAddr *GW)
int _start (int argc, char *argv[])
Variables
static struct pbuf * TxHead
static struct pbuf * TxTail
struct irx_export_table _exp_ps2ip
static struct netif NIF
Detailed Description
PS2 TCP/IP STACK FOR IOP
Definition in file ps2ip.c.
Macro Definition Documentation
MODNAME
#define MODNAME "TCP/IP Stack"
Definition at line 44 of file ps2ip.c.
Function Documentation
_exit()
int _exit (int argc, char ** argv)
Definition at line 222 of file ps2ip.c.
 {
         return MODULE_NO_RESIDENT_END; // return "not resident"!
 }
References MODULE_NO_RESIDENT_END.
_start()
int _start (int argc, char * argv[])
Definition at line 446 of file ps2ip.c.
{
         IPAddr IP, NM, GW;
         //Parse IP address arguments.
         if(argc>=4)
         {
                 dbgprintf("SMAP: %s %s %s\n", argv[1],argv[2],argv[3]);
                 IP.addr=inet_addr(argv[1]);
                 NM.addr=inet_addr(argv[2]);
                 GW.addr=inet_addr(argv[3]);
         }
         else
         {
                 //Set some defaults.
                 IP4_ADDR(&IP,192,168,0,80);
                 IP4_ADDR(&NM,255,255,255,0);
                 IP4_ADDR(&GW,192,168,0,1);
         }
         return InitLWIPStack(&IP, &NM, &GW)==0?MODULE_RESIDENT_END:MODULE_NO_RESIDENT_END;
 }
References dbgprintf, inet_addr, InitLWIPStack(), IP4_ADDR, MODULE_NO_RESIDENT_END, and MODULE_RESIDENT_END.
AllocRxPacket()
static void* AllocRxPacket (unsigned int size, void ** payload) static
Definition at line 237 of file ps2ip.c.
 {
         struct pbuf* pbuf;
         if((pbuf = pbuf_alloc(PBUF_RAW, size, PBUF_POOL)) != NULL)
         {
                 *payload = pbuf->payload;
         }
         return pbuf;
 }
References NULL, PBuf::payload, pbuf_alloc(), PBUF_POOL, and PBUF_RAW.
Referenced by InitLWIPStack().
DeQTxPacket()
static void DeQTxPacket (void) static
Definition at line 273 of file ps2ip.c.
 {
         struct pbuf *toFree;
         int OldState;
         toFree = NULL;
         CpuSuspendIntr(&OldState);
         if(TxTail != NULL)
         {
                 toFree = TxTail;
                 if(TxTail == TxHead) {
                         //Last in queue.
                         TxTail = NULL;
                         TxHead = NULL;
                 } else {
                         TxTail = TxTail->next;
                 }
         }
         CpuResumeIntr(OldState);
         if(toFree != NULL)
         {
                 toFree->next = NULL;
                 pbuf_free(toFree);
         }
 }
References CpuResumeIntr(), CpuSuspendIntr(), PBuf::next, NULL, pbuf_free(), TxHead, and TxTail.
Referenced by InitLWIPStack().
EnQRxPacket()
static void EnQRxPacket (void * packet) static
Definition at line 254 of file ps2ip.c.
 {
         ps2ip_input(packet, &NIF);
 }
References NIF, and ps2ip_input().
Referenced by InitLWIPStack().
EnQTxPacket()
static void EnQTxPacket (struct pbuf * tx) static
Definition at line 302 of file ps2ip.c.
 {
         int OldState;
         CpuSuspendIntr(&OldState);
         if(TxHead != NULL)
                 TxHead->next = tx;
         TxHead = tx;
         tx->next = NULL;
         if(TxTail == NULL)      //Queue empty
                 TxTail = TxHead;
         CpuResumeIntr(OldState);
 }
References CpuResumeIntr(), CpuSuspendIntr(), PBuf::next, NULL, TxHead, and TxTail.
Referenced by SMapLowLevelOutput().
FreeRxPacket()
static void FreeRxPacket (void * packet) static
Definition at line 249 of file ps2ip.c.
 {
         pbuf_free(packet);
 }
References pbuf_free().
Referenced by InitLWIPStack().
InitDone()
static void InitDone (void * pvArg) static
Definition at line 153 of file ps2ip.c.
 {
         dbgprintf("InitDone: TCPIP initialized\n");
         sys_sem_signal((sys_sem_t*)pvArg);
 }
References dbgprintf, and sys_sem_signal().
Referenced by InitializeLWIP().
InitializeLWIP()
static int InitializeLWIP (void) inline static
Definition at line 390 of file ps2ip.c.
{
         sys_sem_t       Sema;
         int             result;
         dbgprintf("PS2IP: Module Loaded.\n");
         if ((result = RegisterLibraryEntries(&_exp_ps2ip))!=0)
         {
                 printf("PS2IP: RegisterLibraryEntries returned: %d\n", result);
         } else {
                 sys_sem_new(&Sema, 0);
                 dbgprintf("PS2IP: Calling tcpip_init\n");
                 tcpip_init(InitDone,&Sema);
                 sys_arch_sem_wait(&Sema, 0);
                 sys_sem_free(&Sema);
                 dbgprintf("PS2IP: tcpip_init called\n");
 #if NOSYS
                 InitTimer();
 #endif
                 dbgprintf("PS2IP: System Initialised\n");
                 result = 0;
         }
         return result;
 }
References _exp_ps2ip, dbgprintf, InitDone(), printf(), RegisterLibraryEntries(), result, sys_arch_sem_wait(), sys_sem_free(), and sys_sem_new().
Referenced by InitLWIPStack().
InitLWIPStack()
static int InitLWIPStack (IPAddr * IP, IPAddr * NM, IPAddr * GW) inline static
Definition at line 420 of file ps2ip.c.
{
         int result;
         static struct NetManNetProtStack stack={
                 &LinkStateUp,
                 &LinkStateDown,
                 &AllocRxPacket,
                 &FreeRxPacket,
                 &EnQRxPacket,
                 &NextTxPacket,
                 &DeQTxPacket,
                 NULL,
                 NULL
         };
         if((result = InitializeLWIP()) != 0)
                 return result;
         netif_add(&NIF, IP, NM, GW, NULL, &SMapIFInit, tcpip_input);
         netif_set_default(&NIF);
         NetManRegisterNetworkStack(&stack);
         netif_set_up(&NIF);
         return 0;
 }
References AllocRxPacket(), DeQTxPacket(), EnQRxPacket(), FreeRxPacket(), InitializeLWIP(), LinkStateDown(), LinkStateUp(), netif_add(), netif_set_default(), netif_set_up(), NetManRegisterNetworkStack(), NextTxPacket(), NIF, NULL, result, SMapIFInit(), and tcpip_input().
Referenced by _start().
IRX_ID()
IRX_ID (MODNAME , 2 , 3)
LinkStateDown()
static void LinkStateDown (void) static
Definition at line 233 of file ps2ip.c.
{
         tcpip_callback((void*)&netif_set_link_down, &NIF);
 }
References netif_set_link_down(), NIF, and tcpip_callback.
Referenced by InitLWIPStack().
LinkStateUp()
static void LinkStateUp (void) static
Definition at line 229 of file ps2ip.c.
{
         tcpip_callback((void*)&netif_set_link_up, &NIF);
 }
References netif_set_link_up(), NIF, and tcpip_callback.
Referenced by InitLWIPStack().
NextTxPacket()
static int NextTxPacket (void ** payload) static
Definition at line 259 of file ps2ip.c.
 {
         int len;
         if(TxTail != NULL)
         {
                 *payload = TxTail->payload;
                 len = TxTail->len;
         } else
                 len = 0;
         return len;
 }
References PBuf::len, NULL, PBuf::payload, and TxTail.
Referenced by InitLWIPStack().
ps2ip_getconfig()
int ps2ip_getconfig (char * pszName, t_ip_info * pInfo)
Definition at line 58 of file ps2ip.c.
 {
         NetIF*  pNetIF=netif_find(pszName);
         if (pNetIF==NULL)
         {
                 //Net interface not found.
                 memset(pInfo,0,sizeof(*pInfo));
                 return  0;
         }
         strcpy(pInfo->netif_name,pszName);
         pInfo->ipaddr.s_addr=pNetIF->ip_addr.addr;
         pInfo->netmask.s_addr=pNetIF->netmask.addr;
         pInfo->gw.s_addr=pNetIF->gw.addr;
         memcpy(pInfo->hw_addr,pNetIF->hwaddr,sizeof(pInfo->hw_addr));
 #if             LWIP_DHCP
         struct dhcp *dhcp = netif_dhcp_data(pNetIF);
         if ((dhcp != NULL) && (dhcp->state != DHCP_STATE_OFF))
         {
                 pInfo->dhcp_enabled=1;
                 pInfo->dhcp_status=dhcp->state;
         }
         else
         {
                 pInfo->dhcp_enabled=0;
                 pInfo->dhcp_status=DHCP_STATE_OFF;
         }
 #else
         pInfo->dhcp_enabled=0;
 #endif
         return  1;
 }
References t_ip_info::dhcp_enabled, DHCP_STATE_OFF, t_ip_info::dhcp_status, t_ip_info::gw, t_ip_info::hw_addr, t_ip_info::ipaddr, memcpy(), memset(), netif_dhcp_data, netif_find(), t_ip_info::netif_name, t_ip_info::netmask, NULL, in_addr::s_addr, and strcpy().
Referenced by do_getconfig().
ps2ip_input()
err_t ps2ip_input (PBuf * pInput, NetIF * pNetIF)
Definition at line 212 of file ps2ip.c.
 {
         err_t result;
         if((result = pNetIF->input(pInput, pNetIF)) != ERR_OK)
                 pbuf_free(pInput);
         return result;
 }
References pbuf_free(), and result.
ps2ip_setconfig()
int ps2ip_setconfig (const t_ip_info * pInfo)
Definition at line 102 of file ps2ip.c.
 {
         NetIF*  pNetIF=netif_find(pInfo->netif_name);
         if      (pNetIF==NULL)
         {
                 return  0;
         }
 #if     LWIP_DHCP
         struct dhcp *dhcp = netif_dhcp_data(pNetIF);
         //Enable dhcp here
         if (pInfo->dhcp_enabled)
         {
                 if ((dhcp == NULL) || (dhcp->state == DHCP_STATE_OFF))
                 {
                         //Set initial IP address
                         netif_set_ipaddr(pNetIF,(const IPAddr*)&pInfo->ipaddr);
                         netif_set_netmask(pNetIF,(const IPAddr*)&pInfo->netmask);
                         netif_set_gw(pNetIF,(const IPAddr*)&pInfo->gw);
                         //Start DHCP client
                         dhcp_start(pNetIF);
                 }
         }
         else
         {
                 if ((dhcp != NULL) && (dhcp->state != DHCP_STATE_OFF))
                 {
                         //Release DHCP lease
                         dhcp_release(pNetIF);
                         //Stop DHCP client
                         dhcp_stop(pNetIF);
                 }
                 netif_set_ipaddr(pNetIF,(const IPAddr*)&pInfo->ipaddr);
                 netif_set_netmask(pNetIF,(const IPAddr*)&pInfo->netmask);
                 netif_set_gw(pNetIF,(const IPAddr*)&pInfo->gw);
         }
 #else
         netif_set_ipaddr(pNetIF,(const IPAddr*)&pInfo->ipaddr);
         netif_set_netmask(pNetIF,(const IPAddr*)&pInfo->netmask);
         netif_set_gw(pNetIF,(const IPAddr*)&pInfo->gw);
 #endif
         return  1;
 }
References t_ip_info::dhcp_enabled, DHCP_STATE_OFF, t_ip_info::gw, t_ip_info::ipaddr, netif_dhcp_data, netif_find(), t_ip_info::netif_name, netif_set_gw(), netif_set_ipaddr(), netif_set_netmask(), t_ip_info::netmask, and NULL.
Referenced by do_setconfig().
SMapIFInit()
static err_t SMapIFInit (struct netif * pNetIF) static
Definition at line 361 of file ps2ip.c.
 {
         TxHead = NULL;
         TxTail = NULL;
         pNetIF->name[0]='s';
         pNetIF->name[1]='m';
 #ifdef PRE_LWIP_130_COMPAT
         pNetIF->output=&SMapOutput;     // For LWIP versions before v1.3.0.
 #else
         pNetIF->output=&etharp_output;  // For LWIP 1.3.0 and later.
 #endif
         pNetIF->linkoutput=&SMapLowLevelOutput;
         pNetIF->hwaddr_len=NETIF_MAX_HWADDR_LEN;
 #ifdef PRE_LWIP_130_COMPAT
         pNetIF->flags|=(NETIF_FLAG_LINK_UP|NETIF_FLAG_BROADCAST);       // For LWIP versions before v1.3.0.
 #else
         pNetIF->flags|=(NETIF_FLAG_ETHARP|NETIF_FLAG_BROADCAST);        // For LWIP v1.3.0 and later.
 #endif
         pNetIF->mtu=1500;
         //Get MAC address.
         NetManIoctl(NETMAN_NETIF_IOCTL_ETH_GET_MAC, NULL, 0, pNetIF->hwaddr, sizeof(pNetIF->hwaddr));
 //      DEBUG_PRINTF("MAC address : %02x:%02x:%02x:%02x:%02x:%02x\n",pNetIF->hwaddr[0],pNetIF->hwaddr[1],pNetIF->hwaddr[2],
 //                               pNetIF->hwaddr[3],pNetIF->hwaddr[4],pNetIF->hwaddr[5]);
         return  ERR_OK;
 }
References etharp_output(), NetIF::flags, NetIF::hwaddr, NetIF::hwaddr_len, NetIF::linkoutput, NetIF::mtu, NetIF::name, NETIF_FLAG_BROADCAST, NETIF_FLAG_ETHARP, NETIF_FLAG_LINK_UP, NETIF_MAX_HWADDR_LEN, NETMAN_NETIF_IOCTL_ETH_GET_MAC, NetManIoctl(), NULL, NetIF::output, SMapLowLevelOutput(), TxHead, and TxTail.
Referenced by InitLWIPStack().
SMapLowLevelOutput()
static err_t SMapLowLevelOutput (struct netif * pNetIF, struct pbuf * pOutput) static
Definition at line 321 of file ps2ip.c.
 {
         err_t result;
         struct pbuf* pbuf;
         result = ERR_OK;
         if(pOutput->tot_len > pOutput->len)
         {
                 pbuf_ref(pOutput);      //Increment reference count because LWIP must free the PBUF, not the driver!
                 if((pbuf = pbuf_coalesce(pOutput, PBUF_RAW)) != pOutput)
                 {       //No need to increase reference count because pbuf_coalesce() does it.
                         EnQTxPacket(pbuf);
                         NetManNetIFXmit();
                 } else
                         result = ERR_MEM;
         } else {
                 pbuf_ref(pOutput);      //This will be freed later.
                 EnQTxPacket(pOutput);
                 NetManNetIFXmit();
         }
         return result;
 }
References EnQTxPacket(), PBuf::len, NetManNetIFXmit(), pbuf_coalesce(), PBUF_RAW, pbuf_ref(), result, and PBuf::tot_len.
Referenced by SMapIFInit().
Variable Documentation
_exp_ps2ip
struct irx_export_table _exp_ps2ip extern
NIF
struct netif NIF static
Definition at line 222 of file ps2ip.c.
Referenced by EnQRxPacket(), InitLWIPStack(), LinkStateDown(), and LinkStateUp().
TxHead
struct pbuf* TxHead static
Definition at line 42 of file ps2ip.c.
Referenced by DeQTxPacket(), EnQTxPacket(), and SMapIFInit().
TxTail
struct pbuf * TxTail static
Definition at line 42 of file ps2ip.c.
Referenced by DeQTxPacket(), EnQTxPacket(), NextTxPacket(), and SMapIFInit().