ps2sdk: iop/tcpip/tcpip/src/ps2ip.c File Reference
ps2ip.c File Reference
#include <types.h>
#include <stdio.h>
#include <intrman.h>
#include <loadcore.h>
#include <thbase.h>
#include <sysclib.h>
#include <thevent.h>
#include <sysmem.h>
#include <lwip/memp.h>
#include "lwip/sys.h"
#include "lwip/tcp.h"
#include "lwip/tcpip.h"
#include "lwip/prot/dhcp.h"
#include "lwip/netif.h"
#include "lwip/dhcp.h"
#include "lwip/inet.h"
#include "netif/etharp.h"
#include "ps2ip_internal.h"
Macros
#define MODNAME "TCP/IP Stack"
Functions
IRX_ID (MODNAME, 2, 3)
int ps2ip_getconfig (char *pszName, t_ip_info *pInfo)
int ps2ip_setconfig (const t_ip_info *pInfo)
static void InitDone (void *pvArg)
err_t ps2ip_input (PBuf *pInput, NetIF *pNetIF)
int _exit (int argc, char **argv)
int _start (int argc, char *argv[])
Variables
struct irx_export_table _exp_ps2ip
Detailed Description
PS2 TCP/IP STACK FOR IOP
Definition in file ps2ip.c.
Macro Definition Documentation
MODNAME
#define MODNAME "TCP/IP Stack"
Definition at line 41 of file ps2ip.c.
Function Documentation
_exit()
int _exit (int argc, char ** argv)
Definition at line 219 of file ps2ip.c.
 {
         return MODULE_NO_RESIDENT_END; // return "not resident"!
 }
References MODULE_NO_RESIDENT_END.
_start()
int _start (int argc, char * argv[])
Definition at line 224 of file ps2ip.c.
{
         sys_sem_t       Sema;
         int             result;
         dbgprintf("PS2IP: Module Loaded.\n");
         if ((result = RegisterLibraryEntries(&_exp_ps2ip)) != 0)
         {
                 printf("PS2IP: RegisterLibraryEntries returned: %d\n", result);
                 return MODULE_NO_RESIDENT_END;
         } else {
                 sys_sem_new(&Sema, 0);
                 dbgprintf("PS2IP: Calling tcpip_init\n");
                 tcpip_init(InitDone,&Sema);
                 sys_arch_sem_wait(&Sema, 0);
                 sys_sem_free(&Sema);
                 dbgprintf("PS2IP: tcpip_init called\n");
 #if NOSYS
                 InitTimer();
 #endif
                 dbgprintf("PS2IP: System Initialised\n");
         }
         return MODULE_RESIDENT_END;
 }
References _exp_ps2ip, dbgprintf, InitDone(), MODULE_NO_RESIDENT_END, MODULE_RESIDENT_END, printf(), RegisterLibraryEntries(), result, sys_arch_sem_wait(), sys_sem_free(), and sys_sem_new().
InitDone()
static void InitDone (void * pvArg) static
Definition at line 150 of file ps2ip.c.
 {
         dbgprintf("InitDone: TCPIP initialized\n");
         sys_sem_signal((sys_sem_t*)pvArg);
 }
References dbgprintf, and sys_sem_signal().
Referenced by _start().
IRX_ID()
IRX_ID (MODNAME , 2 , 3)
ps2ip_getconfig()
int ps2ip_getconfig (char * pszName, t_ip_info * pInfo)
Definition at line 55 of file ps2ip.c.
 {
         NetIF*  pNetIF=netif_find(pszName);
         if (pNetIF==NULL)
         {
                 //Net interface not found.
                 memset(pInfo,0,sizeof(*pInfo));
                 return  0;
         }
         strcpy(pInfo->netif_name,pszName);
         pInfo->ipaddr.s_addr=pNetIF->ip_addr.addr;
         pInfo->netmask.s_addr=pNetIF->netmask.addr;
         pInfo->gw.s_addr=pNetIF->gw.addr;
         memcpy(pInfo->hw_addr,pNetIF->hwaddr,sizeof(pInfo->hw_addr));
 #if             LWIP_DHCP
         struct dhcp *dhcp = netif_dhcp_data(pNetIF);
         if ((dhcp != NULL) && (dhcp->state != DHCP_STATE_OFF))
         {
                 pInfo->dhcp_enabled=1;
                 pInfo->dhcp_status=dhcp->state;
         }
         else
         {
                 pInfo->dhcp_enabled=0;
                 pInfo->dhcp_status=DHCP_STATE_OFF;
         }
 #else
         pInfo->dhcp_enabled=0;
 #endif
         return  1;
 }
ps2ip_input()
err_t ps2ip_input (PBuf * pInput, NetIF * pNetIF)
Definition at line 209 of file ps2ip.c.
 {
         err_t result;
         if((result = pNetIF->input(pInput, pNetIF)) != ERR_OK)
                 pbuf_free(pInput);
         return result;
 }
References pbuf_free(), and result.
Referenced by EnQRxPacket().
ps2ip_setconfig()
int ps2ip_setconfig (const t_ip_info * pInfo)
Definition at line 99 of file ps2ip.c.
 {
         NetIF*  pNetIF=netif_find(pInfo->netif_name);
         if      (pNetIF==NULL)
         {
                 return  0;
         }
 #if     LWIP_DHCP
         struct dhcp *dhcp = netif_dhcp_data(pNetIF);
         //Enable dhcp here
         if (pInfo->dhcp_enabled)
         {
                 if ((dhcp == NULL) || (dhcp->state == DHCP_STATE_OFF))
                 {
                         //Set initial IP address
                         netif_set_ipaddr(pNetIF,(const IPAddr*)&pInfo->ipaddr);
                         netif_set_netmask(pNetIF,(const IPAddr*)&pInfo->netmask);
                         netif_set_gw(pNetIF,(const IPAddr*)&pInfo->gw);
                         //Start DHCP client
                         dhcp_start(pNetIF);
                 }
         }
         else
         {
                 if ((dhcp != NULL) && (dhcp->state != DHCP_STATE_OFF))
                 {
                         //Release DHCP lease
                         dhcp_release(pNetIF);
                         //Stop DHCP client
                         dhcp_stop(pNetIF);
                 }
                 netif_set_ipaddr(pNetIF,(const IPAddr*)&pInfo->ipaddr);
                 netif_set_netmask(pNetIF,(const IPAddr*)&pInfo->netmask);
                 netif_set_gw(pNetIF,(const IPAddr*)&pInfo->gw);
         }
 #else
         netif_set_ipaddr(pNetIF,(const IPAddr*)&pInfo->ipaddr);
         netif_set_netmask(pNetIF,(const IPAddr*)&pInfo->netmask);
         netif_set_gw(pNetIF,(const IPAddr*)&pInfo->gw);
 #endif
         return  1;
 }
Variable Documentation
_exp_ps2ip
struct irx_export_table _exp_ps2ip extern
Referenced by _start(), and InitializeLWIP().