ps2sdk: iop/kernel/include/thbase.h File Reference
thbase.h File Reference
#include <types.h>
#include <irx.h>
Data Structures
struct iop_thread_t
struct iop_thread_info_t
struct iop_sys_clock_t
struct iop_thread_run_status_t
struct iop_sys_status_t
Macros
#define TH_ASM 0x01000000
#define TH_C 0x02000000
#define TH_UMODE 0x00000008
#define TH_NO_FILLSTACK 0x00100000
#define TH_CLEAR_STACK 0x00200000
#define TH_SELF 0
#define THS_RUN 0x01
#define THS_READY 0x02
#define THS_WAIT 0x04
#define THS_SUSPEND 0x08
#define THS_WAITSUSPEND 0x0C
#define THS_DORMANT 0x10
#define TSW_SLEEP 1
#define TSW_DELAY 2
#define TSW_SEMA 3
#define TSW_EVENTFLAG 4
#define TSW_MBX 5
#define TSW_VPL 6
#define TSW_FPL 7
#define thbase_IMPORTS
#define thbase_IMPORTS_start DECLARE_IMPORT_TABLE(thbase, 1, 1)
#define thbase_IMPORTS_end END_IMPORT_TABLE
#define I_CreateThread DECLARE_IMPORT(4, CreateThread)
#define I_DeleteThread DECLARE_IMPORT(5, DeleteThread)
#define I_StartThread DECLARE_IMPORT(6, StartThread)
#define I_StartThreadArgs DECLARE_IMPORT(7, StartThreadArgs)
#define I_ExitThread DECLARE_IMPORT(8, ExitThread)
#define I_ExitDeleteThread DECLARE_IMPORT(9, ExitDeleteThread)
#define I_TerminateThread DECLARE_IMPORT(10, TerminateThread)
#define I_iTerminateThread DECLARE_IMPORT(11, iTerminateThread)
#define I_ChangeThreadPriority DECLARE_IMPORT(14, ChangeThreadPriority)
#define I_iChangeThreadPriority DECLARE_IMPORT(15, iChangeThreadPriority)
#define I_RotateThreadReadyQueue DECLARE_IMPORT(16, RotateThreadReadyQueue)
#define I_iRotateThreadReadyQueue DECLARE_IMPORT(17, iRotateThreadReadyQueue)
#define I_ReleaseWaitThread DECLARE_IMPORT(18, ReleaseWaitThread)
#define I_iReleaseWaitThread DECLARE_IMPORT(19, iReleaseWaitThread)
#define I_GetThreadId DECLARE_IMPORT(20, GetThreadId)
#define I_CheckThreadStack DECLARE_IMPORT(21, CheckThreadStack)
#define I_ReferThreadStatus DECLARE_IMPORT(22, ReferThreadStatus)
#define I_iReferThreadStatus DECLARE_IMPORT(23, iReferThreadStatus)
#define I_SleepThread DECLARE_IMPORT(24, SleepThread)
#define I_WakeupThread DECLARE_IMPORT(25, WakeupThread)
#define I_iWakeupThread DECLARE_IMPORT(26, iWakeupThread)
#define I_CancelWakeupThread DECLARE_IMPORT(27, CancelWakeupThread)
#define I_iCancelWakeupThread DECLARE_IMPORT(28, iCancelWakeupThread)
#define I_DelayThread DECLARE_IMPORT(33, DelayThread)
#define I_GetSystemTime DECLARE_IMPORT(34, GetSystemTime)
#define I_SetAlarm DECLARE_IMPORT(35, SetAlarm)
#define I_iSetAlarm DECLARE_IMPORT(36, iSetAlarm)
#define I_CancelAlarm DECLARE_IMPORT(37, CancelAlarm)
#define I_iCancelAlarm DECLARE_IMPORT(38, iCancelAlarm)
#define I_USec2SysClock DECLARE_IMPORT(39, USec2SysClock)
#define I_SysClock2USec DECLARE_IMPORT(40, SysClock2USec)
#define I_GetSystemStatusFlag DECLARE_IMPORT(41, GetSystemStatusFlag)
Functions
int CreateThread (iop_thread_t *thread)
int DeleteThread (int thid)
int StartThread (int thid, void *arg)
int StartThreadArgs (int thid, int args, void *argp)
int ExitThread ()
int ExitDeleteThread ()
int TerminateThread (int thid)
int iTerminateThread (int thid)
int ChangeThreadPriority (int thid, int priority)
int iChangeThreadPriority (int thid, int priority)
int RotateThreadReadyQueue (int priority)
int iRotateThreadReadyQueue (int priority)
int ReleaseWaitThread (int thid)
int iReleaseWaitThread (int thid)
int GetThreadId (void)
int CheckThreadStack (void)
int ReferThreadStatus (int thid, iop_thread_info_t *info)
int iReferThreadStatus (int thid, iop_thread_info_t *info)
int SleepThread (void)
int WakeupThread (int thid)
int iWakeupThread (int thid)
int CancelWakeupThread (int thid)
int iCancelWakeupThread (int thid)
int DelayThread (int usec)
int GetSystemTime (iop_sys_clock_t *sys_clock)
int SetAlarm (iop_sys_clock_t *sys_clock, unsigned int(*alarm_cb)(void *), void *arg)
int iSetAlarm (iop_sys_clock_t *sys_clock, unsigned int(*alarm_cb)(void *), void *arg)
int CancelAlarm (unsigned int(*alarm_cb)(void *), void *arg)
int iCancelAlarm (unsigned int(*alarm_cb)(void *), void *arg)
void USec2SysClock (u32 usec, iop_sys_clock_t *sys_clock)
void SysClock2USec (iop_sys_clock_t *sys_clock, u32 *sec, u32 *usec)
int GetSystemStatusFlag ()
Detailed Description
Kernel-based threads.
Definition in file thbase.h.
Macro Definition Documentation
I_CancelAlarm
#define I_CancelAlarm DECLARE_IMPORT(37, CancelAlarm)
Definition at line 222 of file thbase.h.
I_CancelWakeupThread
#define I_CancelWakeupThread DECLARE_IMPORT(27, CancelWakeupThread)
Definition at line 216 of file thbase.h.
I_ChangeThreadPriority
#define I_ChangeThreadPriority DECLARE_IMPORT(14, ChangeThreadPriority)
Definition at line 203 of file thbase.h.
I_CheckThreadStack
#define I_CheckThreadStack DECLARE_IMPORT(21, CheckThreadStack)
Definition at line 210 of file thbase.h.
I_CreateThread
#define I_CreateThread DECLARE_IMPORT(4, CreateThread)
Definition at line 195 of file thbase.h.
I_DelayThread
#define I_DelayThread DECLARE_IMPORT(33, DelayThread)
Definition at line 218 of file thbase.h.
I_DeleteThread
#define I_DeleteThread DECLARE_IMPORT(5, DeleteThread)
Definition at line 196 of file thbase.h.
I_ExitDeleteThread
#define I_ExitDeleteThread DECLARE_IMPORT(9, ExitDeleteThread)
Definition at line 200 of file thbase.h.
I_ExitThread
#define I_ExitThread DECLARE_IMPORT(8, ExitThread)
Definition at line 199 of file thbase.h.
I_GetSystemStatusFlag
#define I_GetSystemStatusFlag DECLARE_IMPORT(41, GetSystemStatusFlag)
Definition at line 226 of file thbase.h.
I_GetSystemTime
#define I_GetSystemTime DECLARE_IMPORT(34, GetSystemTime)
Definition at line 219 of file thbase.h.
I_GetThreadId
#define I_GetThreadId DECLARE_IMPORT(20, GetThreadId)
Definition at line 209 of file thbase.h.
I_iCancelAlarm
#define I_iCancelAlarm DECLARE_IMPORT(38, iCancelAlarm)
Definition at line 223 of file thbase.h.
I_iCancelWakeupThread
#define I_iCancelWakeupThread DECLARE_IMPORT(28, iCancelWakeupThread)
Definition at line 217 of file thbase.h.
I_iChangeThreadPriority
#define I_iChangeThreadPriority DECLARE_IMPORT(15, iChangeThreadPriority)
Definition at line 204 of file thbase.h.
I_iReferThreadStatus
#define I_iReferThreadStatus DECLARE_IMPORT(23, iReferThreadStatus)
Definition at line 212 of file thbase.h.
I_iReleaseWaitThread
#define I_iReleaseWaitThread DECLARE_IMPORT(19, iReleaseWaitThread)
Definition at line 208 of file thbase.h.
I_iRotateThreadReadyQueue
#define I_iRotateThreadReadyQueue DECLARE_IMPORT(17, iRotateThreadReadyQueue)
Definition at line 206 of file thbase.h.
I_iSetAlarm
#define I_iSetAlarm DECLARE_IMPORT(36, iSetAlarm)
Definition at line 221 of file thbase.h.
I_iTerminateThread
#define I_iTerminateThread DECLARE_IMPORT(11, iTerminateThread)
Definition at line 202 of file thbase.h.
I_iWakeupThread
#define I_iWakeupThread DECLARE_IMPORT(26, iWakeupThread)
Definition at line 215 of file thbase.h.
I_ReferThreadStatus
#define I_ReferThreadStatus DECLARE_IMPORT(22, ReferThreadStatus)
Definition at line 211 of file thbase.h.
I_ReleaseWaitThread
#define I_ReleaseWaitThread DECLARE_IMPORT(18, ReleaseWaitThread)
Definition at line 207 of file thbase.h.
I_RotateThreadReadyQueue
#define I_RotateThreadReadyQueue DECLARE_IMPORT(16, RotateThreadReadyQueue)
Definition at line 205 of file thbase.h.
I_SetAlarm
#define I_SetAlarm DECLARE_IMPORT(35, SetAlarm)
Definition at line 220 of file thbase.h.
I_SleepThread
#define I_SleepThread DECLARE_IMPORT(24, SleepThread)
Definition at line 213 of file thbase.h.
I_StartThread
#define I_StartThread DECLARE_IMPORT(6, StartThread)
Definition at line 197 of file thbase.h.
I_StartThreadArgs
#define I_StartThreadArgs DECLARE_IMPORT(7, StartThreadArgs)
Definition at line 198 of file thbase.h.
I_SysClock2USec
#define I_SysClock2USec DECLARE_IMPORT(40, SysClock2USec)
Definition at line 225 of file thbase.h.
I_TerminateThread
#define I_TerminateThread DECLARE_IMPORT(10, TerminateThread)
Definition at line 201 of file thbase.h.
I_USec2SysClock
#define I_USec2SysClock DECLARE_IMPORT(39, USec2SysClock)
Definition at line 224 of file thbase.h.
I_WakeupThread
#define I_WakeupThread DECLARE_IMPORT(25, WakeupThread)
Definition at line 214 of file thbase.h.
TH_ASM
#define TH_ASM 0x01000000
Definition at line 23 of file thbase.h.
TH_C
#define TH_C 0x02000000
Definition at line 24 of file thbase.h.
TH_CLEAR_STACK
#define TH_CLEAR_STACK 0x00200000
Definition at line 27 of file thbase.h.
TH_NO_FILLSTACK
#define TH_NO_FILLSTACK 0x00100000
Definition at line 26 of file thbase.h.
TH_SELF
#define TH_SELF 0
Special thread ID for referring to the running thread. Not supported by all functions.
Definition at line 38 of file thbase.h.
TH_UMODE
#define TH_UMODE 0x00000008
Definition at line 25 of file thbase.h.
thbase_IMPORTS
#define thbase_IMPORTS
Definition at line 145 of file thbase.h.
thbase_IMPORTS_end
#define thbase_IMPORTS_end END_IMPORT_TABLE
Definition at line 193 of file thbase.h.
thbase_IMPORTS_start
#define thbase_IMPORTS_start DECLARE_IMPORT_TABLE(thbase, 1, 1)
Definition at line 192 of file thbase.h.
THS_DORMANT
#define THS_DORMANT 0x10
Definition at line 46 of file thbase.h.
THS_READY
#define THS_READY 0x02
Definition at line 42 of file thbase.h.
THS_RUN
#define THS_RUN 0x01
Definition at line 41 of file thbase.h.
THS_SUSPEND
#define THS_SUSPEND 0x08
Definition at line 44 of file thbase.h.
THS_WAIT
#define THS_WAIT 0x04
Definition at line 43 of file thbase.h.
THS_WAITSUSPEND
#define THS_WAITSUSPEND 0x0C
Definition at line 45 of file thbase.h.
TSW_DELAY
#define TSW_DELAY 2
Definition at line 50 of file thbase.h.
TSW_EVENTFLAG
#define TSW_EVENTFLAG 4
Definition at line 52 of file thbase.h.
TSW_FPL
#define TSW_FPL 7
Definition at line 55 of file thbase.h.
TSW_MBX
#define TSW_MBX 5
Definition at line 53 of file thbase.h.
TSW_SEMA
#define TSW_SEMA 3
Definition at line 51 of file thbase.h.
TSW_SLEEP
#define TSW_SLEEP 1
Definition at line 49 of file thbase.h.
TSW_VPL
#define TSW_VPL 6
Definition at line 54 of file thbase.h.
Function Documentation
CancelAlarm()
int CancelAlarm (unsigned int(*)(void *) alarm_cb, void * arg)
Referenced by ata_io_finish(), EnQFrame(), flash_device_reset(), flash_page_erase(), flash_page_read(), flash_page_write(), iLinkSync(), keepalive_deinit(), ps2kbd_data_recv(), ps2kbd_ioctl_setreadmode(), sys_arch_mbox_fetch_internal(), and sys_arch_sem_wait().
CancelWakeupThread()
int CancelWakeupThread (int thid)
ChangeThreadPriority()
int ChangeThreadPriority (int thid, int priority)
Referenced by sceUsbdChangeThreadPriority().
CheckThreadStack()
int CheckThreadStack (void)
CreateThread()
int CreateThread (iop_thread_t * thread)
Referenced by _start(), AHX_Init(), bdm_init(), create_main_thread(), create_th(), create_thread(), hcdInit(), init_ieee1394DiskDriver(), init_repeatthread(), initCallbackThread(), InitPowerOffThread(), InitRpcServers(), naplinkRpcInit(), NetmanInitRPCServer(), padInit(), padPortOpen(), PS2CamConnect(), ps2netfs_Init(), rmmanInit(), SetupNetDev(), smb_init(), sndStreamOpen(), sys_thread_new(), and usb_mass_init().
DelayThread()
int DelayThread (int usec)
Referenced by _McChDir(), _McGetDir(), _McGetInfo(), _McGetInfo2(), _McRead(), _McRead2(), _McReadPage(), _smap_read_phy(), _smap_write_phy(), _start(), apaGetIlinkID(), apaGetTime(), ata_bus_reset(), ata_io_finish(), ata_reset_devices(), dev9_smap_init(), dev9_smap_read_phy(), dev9_smap_write_phy(), dev9Shutdown(), expbay_device_reset(), fat_getData(), gen_ata_wait_busy(), hdpro_io_finish(), ieee1394_SendCommandBlockORB(), ieee1394_Sync(), ieee1394_Sync_withTimeout(), iLinkReadCROM(), iLinkResetHW(), initConfigureSBP2Device(), initialize_rpc_client(), InitPHY(), InitPowerOffThread(), IntrHandlerThread(), mcman_probePS1Card(), mcman_probePS1Card2(), McReadPS1PDACard(), McWritePS1PDACard(), NetManInitRPCClient(), pcic_power(), pcic_ssbus_mode(), pcmcia_device_reset(), pfsGetTime(), read_eeprom_data(), smap_init(), and speed_device_init().
DeleteThread()
int DeleteThread (int thid)
Referenced by _exit(), AHX_Quit(), audsrv_quit(), audsrv_stop_cd(), bdm_init(), DeinitIEEE1394(), DeleteThreads(), DeleteThreadsEventFlag(), naplinkRpcInit(), NetmanDeinitRPCServer(), PS2CamInitializeNewDevice(), rmmanEnd(), SetupNetDev(), smb_deinit(), sndStreamClose(), sys_thread_new(), and usb_mass_init().
ExitDeleteThread()
int ExitDeleteThread ()
Referenced by AHX_Init(), AHX_Thread(), napThread(), and ps2netfs_serv().
ExitThread()
int ExitThread ()
Referenced by MainThread(), QueryPadThread(), SetActAlignThread(), SetButtonInfoThread(), SetMainModeThread(), SetVrefParamThread(), update_slot_numbers_thread(), and WaitClearEvent().
GetSystemStatusFlag()
int GetSystemStatusFlag ()
GetSystemTime()
int GetSystemTime (iop_sys_clock_t * sys_clock)
Referenced by initConfigureSBP2Device(), ps2mouse_data_recv(), sys_arch_mbox_fetch_internal(), sys_arch_sem_wait(), and sys_now().
GetThreadId()
int GetThreadId (void)
Referenced by AHX_Thread(), fileXio_Thread(), napThread(), poweroff_rpc_Thread(), rpc_server_thread(), rpc_thread(), rpc_thread_change_slot(), rpc_thread_get_slot_number(), rpcMainThread(), RpcThread(), RpcThreadExt(), RpcThreadGetConnection(), RpcThreadPortClose(), RpcThreadPortOpen(), sys_arch_mbox_fetch_internal(), sys_arch_sem_wait(), thread_rpc_S_0400(), and threadRpcFunction().
iCancelAlarm()
int iCancelAlarm (unsigned int(*)(void *) alarm_cb, void * arg)
iCancelWakeupThread()
int iCancelWakeupThread (int thid)
iChangeThreadPriority()
int iChangeThreadPriority (int thid, int priority)
iReferThreadStatus()
int iReferThreadStatus (int thid, iop_thread_info_t * info)
Referenced by VbReferThreadStatus().
iReleaseWaitThread()
int iReleaseWaitThread (int thid)
Referenced by TimeoutHandler().
iRotateThreadReadyQueue()
int iRotateThreadReadyQueue (int priority)
iSetAlarm()
int iSetAlarm (iop_sys_clock_t * sys_clock, unsigned int(*)(void *) alarm_cb, void * arg)
Referenced by ps2kbd_repeathandler(), and timer_intr_handler().
iTerminateThread()
int iTerminateThread (int thid)
iWakeupThread()
int iWakeupThread (int thid)
Referenced by _sif2_cmd_dbg_control(), and SendCmd().
ReferThreadStatus()
int ReferThreadStatus (int thid, iop_thread_info_t * info)
Referenced by GetThreadsStatus(), QueryPadThread(), SetActAlignThread(), SetButtonInfoThread(), SetMainModeThread(), SetVrefParamThread(), UpdatePadThread(), and WaitClearEvent().
ReleaseWaitThread()
int ReleaseWaitThread (int thid)
RotateThreadReadyQueue()
int RotateThreadReadyQueue (int priority)
SetAlarm()
int SetAlarm (iop_sys_clock_t * sys_clock, unsigned int(*)(void *) alarm_cb, void * arg)
Referenced by ata_io_start(), EnQFrame(), flash_device_reset(), flash_page_erase(), flash_page_read(), flash_page_write(), iLinkSync(), IntrHandlerThread(), keepalive_init(), ps2kbd_getkeys(), sys_arch_mbox_fetch_internal(), and sys_arch_sem_wait().
SleepThread()
int SleepThread (void)
Referenced by _controller_thread(), fileXio_Thread(), and PowerOffThread().
StartThread()
int StartThread (int thid, void * arg)
Referenced by _start(), AHX_Init(), bdm_init(), create_th(), create_thread(), hcdInit(), init_ieee1394DiskDriver(), init_repeatthread(), initCallbackThread(), InitPowerOffThread(), InitRpcServers(), MainThread(), naplinkRpcInit(), NetmanInitRPCServer(), padInit(), padPortOpen(), PS2CamConnect(), ps2netfs_Init(), rmmanInit(), SetupNetDev(), smb_init(), sndStreamOpen(), sys_thread_new(), UpdatePadThread(), and usb_mass_init().
StartThreadArgs()
int StartThreadArgs (int thid, int args, void * argp)
SysClock2USec()
void SysClock2USec (iop_sys_clock_t * sys_clock, u32 * sec, u32 * usec)
Referenced by ComputeTimeDiff(), initConfigureSBP2Device(), ps2mouse_data_recv(), and sys_now().
TerminateThread()
int TerminateThread (int thid)
Referenced by _exit(), AHX_Quit(), audsrv_quit(), audsrv_stop_cd(), DeinitIEEE1394(), NetmanDeinitRPCServer(), and SetupNetDev().
USec2SysClock()
void USec2SysClock (u32 usec, iop_sys_clock_t * sys_clock)
Referenced by ata_io_start(), IntrHandlerThread(), ps2kbd_getkeys(), ps2kbd_repeathandler(), smb_init(), sys_arch_mbox_fetch_internal(), and sys_arch_sem_wait().
WakeupThread()
int WakeupThread (int thid)