ps2sdk: iop/kernel/include/thevent.h File Reference
thevent.h File Reference
#include <types.h>
#include <irx.h>
Data Structures
struct iop_event_t
struct iop_event_info_t
Macros
#define WEF_AND 0
#define WEF_OR 1
#define WEF_CLEAR 0x10
#define EA_SINGLE 0
#define EA_MULTI 2
#define thevent_IMPORTS
#define thevent_IMPORTS_start DECLARE_IMPORT_TABLE(thevent, 1, 1)
#define thevent_IMPORTS_end END_IMPORT_TABLE
#define I_CreateEventFlag DECLARE_IMPORT(4, CreateEventFlag)
#define I_DeleteEventFlag DECLARE_IMPORT(5, DeleteEventFlag)
#define I_SetEventFlag DECLARE_IMPORT(6, SetEventFlag)
#define I_iSetEventFlag DECLARE_IMPORT(7, iSetEventFlag)
#define I_ClearEventFlag DECLARE_IMPORT(8, ClearEventFlag)
#define I_iClearEventFlag DECLARE_IMPORT(9, iClearEventFlag)
#define I_WaitEventFlag DECLARE_IMPORT(10, WaitEventFlag)
#define I_PollEventFlag DECLARE_IMPORT(11, PollEventFlag)
#define I_ReferEventFlagStatus DECLARE_IMPORT(13, ReferEventFlagStatus)
#define I_iReferEventFlagStatus DECLARE_IMPORT(14, iReferEventFlagStatus)
Functions
int CreateEventFlag (iop_event_t *event)
int DeleteEventFlag (int ef)
int SetEventFlag (int ef, u32 bits)
int iSetEventFlag (int ef, u32 bits)
int ClearEventFlag (int ef, u32 bits)
int iClearEventFlag (int ef, u32 bits)
int WaitEventFlag (int ef, u32 bits, int mode, u32 *resbits)
int PollEventFlag (int ef, u32 bits, int mode, u32 *resbits)
int ReferEventFlagStatus (int ef, iop_event_info_t *info)
int iReferEventFlagStatus (int ef, iop_event_info_t *info)
Detailed Description
Event flags for threads.
Definition in file thevent.h.
Macro Definition Documentation
EA_MULTI
#define EA_MULTI 2
Multiple threads can wait on the event flag.
Definition at line 31 of file thevent.h.
EA_SINGLE
#define EA_SINGLE 0
Only one thread can wait on the event flag.
Definition at line 29 of file thevent.h.
I_ClearEventFlag
#define I_ClearEventFlag DECLARE_IMPORT(8, ClearEventFlag)
Definition at line 98 of file thevent.h.
I_CreateEventFlag
#define I_CreateEventFlag DECLARE_IMPORT(4, CreateEventFlag)
Definition at line 94 of file thevent.h.
I_DeleteEventFlag
#define I_DeleteEventFlag DECLARE_IMPORT(5, DeleteEventFlag)
Definition at line 95 of file thevent.h.
I_iClearEventFlag
#define I_iClearEventFlag DECLARE_IMPORT(9, iClearEventFlag)
Definition at line 99 of file thevent.h.
I_iReferEventFlagStatus
#define I_iReferEventFlagStatus DECLARE_IMPORT(14, iReferEventFlagStatus)
Definition at line 103 of file thevent.h.
I_iSetEventFlag
#define I_iSetEventFlag DECLARE_IMPORT(7, iSetEventFlag)
Definition at line 97 of file thevent.h.
I_PollEventFlag
#define I_PollEventFlag DECLARE_IMPORT(11, PollEventFlag)
Definition at line 101 of file thevent.h.
I_ReferEventFlagStatus
#define I_ReferEventFlagStatus DECLARE_IMPORT(13, ReferEventFlagStatus)
Definition at line 102 of file thevent.h.
I_SetEventFlag
#define I_SetEventFlag DECLARE_IMPORT(6, SetEventFlag)
Definition at line 96 of file thevent.h.
I_WaitEventFlag
#define I_WaitEventFlag DECLARE_IMPORT(10, WaitEventFlag)
Definition at line 100 of file thevent.h.
thevent_IMPORTS
#define thevent_IMPORTS
Value:
        thevent_IMPORTS_start \
 \
        I_CreateEventFlag \
        I_DeleteEventFlag \
 \
        I_SetEventFlag \
        I_iSetEventFlag \
 \
        I_ClearEventFlag \
        I_iClearEventFlag \
 \
        I_WaitEventFlag \
 \
        I_PollEventFlag \
 \
        I_ReferEventFlagStatus \
        I_iReferEventFlagStatus \
 \
        thevent_IMPORTS_end END_IMPORT_TABLE
Definition at line 70 of file thevent.h.
thevent_IMPORTS_end
#define thevent_IMPORTS_end END_IMPORT_TABLE
Definition at line 92 of file thevent.h.
thevent_IMPORTS_start
#define thevent_IMPORTS_start DECLARE_IMPORT_TABLE(thevent, 1, 1)
Definition at line 91 of file thevent.h.
WEF_AND
#define WEF_AND 0
Definition at line 23 of file thevent.h.
WEF_CLEAR
#define WEF_CLEAR 0x10
Definition at line 25 of file thevent.h.
WEF_OR
#define WEF_OR 1
Definition at line 24 of file thevent.h.
Function Documentation
ClearEventFlag()
int ClearEventFlag (int ef, u32 bits)
Referenced by ata_io_start(), iLinkPHTSendData(), iLinkResetSBus(), iLinkSendData(), main_thread(), NetManSetLinkMode(), NetManToggleNetIFLinkState(), sio2_mc_transfer_init(), sio2_mtap_transfer_init(), sio2_pad_transfer_init(), sio2_transfer(), UBUFThread(), and WaitClearEvent().
CreateEventFlag()
int CreateEventFlag (iop_event_t * event)
Referenced by _start(), ata_create_event_flag(), bdm_init(), create_event_flag(), hcdInit(), init_ieee1394DiskDriver(), init_repeatthread(), initCallbackThread(), NetManRegisterNetIF(), padInit(), padPortOpen(), rmmanInit(), rmmanOpen(), and SetupNetDev().
DeleteEventFlag()
int DeleteEventFlag (int ef)
Referenced by _exit(), bdm_init(), DeinitIEEE1394(), DeleteThreadsEventFlag(), NetManUnregisterNetIF(), padPortClose(), rmmanEnd(), and SetupNetDev().
iClearEventFlag()
int iClearEventFlag (int ef, u32 bits)
iReferEventFlagStatus()
int iReferEventFlagStatus (int ef, iop_event_info_t * info)
iSetEventFlag()
int iSetEventFlag (int ef, u32 bits)
Referenced by ata_alarm_cb(), ata_intr_cb(), Dev9IntrCb(), iLinkIntrHandler(), LinkCheckTimerCB(), ps2kbd_repeathandler(), sio2_intr_handler(), SMAPXmit(), TimeoutCallbackFunction(), usbdIntrHandler(), and VblankStart().
PollEventFlag()
int PollEventFlag (int ef, u32 bits, int mode, u32 * resbits)
Referenced by ata_io_finish().
ReferEventFlagStatus()
int ReferEventFlagStatus (int ef, iop_event_info_t * info)
Referenced by MainThread().
SetEventFlag()
int SetEventFlag (int ef, u32 bits)
Referenced by bdm_connect_bd(), bdm_connect_fs(), bdm_disconnect_bd(), bdm_disconnect_fs(), bdm_RegisterCallback(), bdm_try_mount(), EnterConfigMode(), ExitConfigMode(), ieee1394_callback(), main_thread(), MainThread(), NetManToggleNetIFLinkState(), padEnd(), PadIsSupported(), PHYPacketHandler(), QueryAct(), QueryButtonMask(), QueryComb(), QueryMode(), QueryModel(), ReadData(), ResponseHandler(), rmmanClose(), rmmanEnd(), SetActAlign(), SetButtonInfo(), SetMainMode(), signalCallbackThreadFunc(), sio2_mc_transfer_init(), sio2_mtap_transfer_init(), sio2_pad_transfer_init(), sio2_transfer(), sio2_transfer_reset(), SMAPSetLinkMode(), SMAPStart(), SMAPStop(), SMAPXmit(), TransferThread(), update_slot_numbers(), update_slot_numbers_thread(), VrefParam(), and WaitClearEvent().
WaitEventFlag()
int WaitEventFlag (int ef, u32 bits, int mode, u32 * resbits)
Referenced by ata_dma_complete(), ata_io_finish(), bdm_thread(), callbackThreadFunc(), hcdIrqThread(), iLinkIntrCBHandlingThread(), iLinkPHTSendData(), iLinkResetSBus(), iLinkSendData(), iLinkSync(), IntrHandlerThread(), main_thread(), MainThread(), NetManSetLinkMode(), padEnd(), padPortClose(), repeat_thread(), rmmanClose(), rmmanEnd(), sio2_mc_transfer_init(), sio2_mtap_transfer_init(), sio2_pad_transfer_init(), sio2_transfer(), UBUFThread(), update_slot_numbers_thread(), and WaitClearEvent().