ps2sdk: iop/kernel/include/thsemap.h File Reference
thsemap.h File Reference
#include <types.h>
#include <irx.h>
Data Structures
struct iop_sema_t
struct iop_sema_info_t
Macros
#define SA_THFIFO 0x000
#define SA_THPRI 0x001
#define SA_IHTHPRI 0x100
#define IOP_MUTEX_LOCKED 0
#define IOP_MUTEX_UNLOCKED 1
#define thsemap_IMPORTS_start DECLARE_IMPORT_TABLE(thsemap, 1, 2)
#define thsemap_IMPORTS_end END_IMPORT_TABLE
#define I_CreateSema DECLARE_IMPORT(4, CreateSema)
#define I_DeleteSema DECLARE_IMPORT(5, DeleteSema)
#define I_SignalSema DECLARE_IMPORT(6, SignalSema)
#define I_iSignalSema DECLARE_IMPORT(7, iSignalSema)
#define I_WaitSema DECLARE_IMPORT(8, WaitSema);
#define I_PollSema DECLARE_IMPORT(9, PollSema);
#define I_ReferSemaStatus DECLARE_IMPORT(11, ReferSemaStatus)
#define I_iReferSemaStatus DECLARE_IMPORT(12, iReferSemaStatus)
Functions
int CreateSema (iop_sema_t *sema)
int DeleteSema (int semid)
int SignalSema (int semid)
int iSignalSema (int semid)
int WaitSema (int semid)
int PollSema (int semid)
int ReferSemaStatus (int semid, iop_sema_info_t *info)
int iReferSemaStatus (int semid, iop_sema_info_t *info)
static int CreateMutex (int state)
Detailed Description
Kernel-based semaphores.
Definition in file thsemap.h.
Macro Definition Documentation
I_CreateSema
#define I_CreateSema DECLARE_IMPORT(4, CreateSema)
Definition at line 78 of file thsemap.h.
I_DeleteSema
#define I_DeleteSema DECLARE_IMPORT(5, DeleteSema)
Definition at line 79 of file thsemap.h.
I_iReferSemaStatus
#define I_iReferSemaStatus DECLARE_IMPORT(12, iReferSemaStatus)
Definition at line 85 of file thsemap.h.
I_iSignalSema
#define I_iSignalSema DECLARE_IMPORT(7, iSignalSema)
Definition at line 81 of file thsemap.h.
I_PollSema
#define I_PollSema DECLARE_IMPORT(9, PollSema);
Definition at line 83 of file thsemap.h.
I_ReferSemaStatus
#define I_ReferSemaStatus DECLARE_IMPORT(11, ReferSemaStatus)
Definition at line 84 of file thsemap.h.
I_SignalSema
#define I_SignalSema DECLARE_IMPORT(6, SignalSema)
Definition at line 80 of file thsemap.h.
I_WaitSema
#define I_WaitSema DECLARE_IMPORT(8, WaitSema);
Definition at line 82 of file thsemap.h.
IOP_MUTEX_LOCKED
#define IOP_MUTEX_LOCKED 0
Definition at line 62 of file thsemap.h.
IOP_MUTEX_UNLOCKED
#define IOP_MUTEX_UNLOCKED 1
Definition at line 63 of file thsemap.h.
SA_IHTHPRI
#define SA_IHTHPRI 0x100
Definition at line 32 of file thsemap.h.
SA_THFIFO
#define SA_THFIFO 0x000
Definition at line 30 of file thsemap.h.
SA_THPRI
#define SA_THPRI 0x001
Definition at line 31 of file thsemap.h.
thsemap_IMPORTS_end
#define thsemap_IMPORTS_end END_IMPORT_TABLE
Definition at line 76 of file thsemap.h.
thsemap_IMPORTS_start
#define thsemap_IMPORTS_start DECLARE_IMPORT_TABLE(thsemap, 1, 2)
Definition at line 75 of file thsemap.h.
Function Documentation
CreateMutex()
static int CreateMutex (int state) inline static
Definition at line 65 of file thsemap.h.
 {
         iop_sema_t sema;
         sema.attr = 0;
         sema.option = 0;
         sema.initial = state;
         sema.max = 1;
         return CreateSema(&sema);
 }
References iop_sema_t::attr, CreateSema(), iop_sema_t::initial, iop_sema_t::max, iop_sema_t::option, and state.
Referenced by _start(), audsrv_cd_init(), audsrv_init(), initialize_rpc_client(), smb_init(), and tty_init().
CreateSema()
int CreateSema (iop_sema_t * sema)
Referenced by _fs_init_lock(), _start(), AHX_Thread(), CreateMutex(), dev9_init(), flushbuffer(), hddInit(), mass_stor_connect(), mcman_initdev(), NetManInitRPCClient(), pfsFioInit(), PS2CamInitDriver(), ps2kbd_init(), ps2mouse_init(), sndStreamOpen(), sys_init(), sys_sem_new(), usb_mass_connect(), and usb_mass_init().
DeleteSema()
int DeleteSema (int semid)
Referenced by _exit(), AHX_Quit(), audsrv_init(), audsrv_quit(), deinitialize_rpc_client(), flushbuffer(), fs_reset(), hddDeinit(), mass_stor_disconnect(), mc_deinit(), NetManDeinitRPCClient(), pfsFioDeinit(), ps2fs_Destroy(), shutdown(), smb_deinit(), sys_sem_free(), tty_deinit(), and usb_mass_disconnect().
iReferSemaStatus()
int iReferSemaStatus (int semid, iop_sema_info_t * info)
iSignalSema()
int iSignalSema (int semid)
Referenced by AHX_TransCallback(), call_end_callback(), cd_transfer_complete(), stream_handler(), timer_intr_handler(), and transfer_complete().
PollSema()
int PollSema (int semid)
Referenced by fio_read(), sys_arch_sem_wait(), and try_alloc_msg().
ReferSemaStatus()
int ReferSemaStatus (int semid, iop_sema_info_t * info)
SignalSema()
int SignalSema (int semid)
Referenced by _fs_unlock(), alloc_unlock(), apaRename(), dev9DmaTransfer(), do_ps2mouse_setposition(), fio_read(), fioDataTransfer(), free_msg(), getReg8(), hddClose(), hddDevctl(), hddDread(), hddGetStat(), hddIoctl2(), hddLseek(), hddOpen(), hddRemove(), hddReName(), iLinkSendData(), keepalive_thread(), mc_chstat(), mc_close(), mc_dclose(), mc_dopen(), mc_dread(), mc_format(), mc_getstat(), mc_lseek(), mc_mkdir(), mc_open(), mc_read(), mc_remove(), mc_rmdir(), mc_write(), NetManIoctl(), NetManQueryMainIF(), NetManRegisterNetIF(), NetManRegisterNetworkStack(), NetManRpcToggleGlobalNetIFLinkState(), NetManSetLinkMode(), NetManSetMainIF(), NetManToggleNetIFLinkState(), NetManUnregisterNetIF(), NetManUnregisterNetworkStack(), pfsFioChdir(), pfsFioCheckFileSlot(), pfsFioChstat(), pfsFioClose(), pfsFioDevctl(), pfsFioDread(), pfsFioFormat(), pfsFioGetMountedUnit(), pfsFioGetstat(), pfsFioIoctl2(), pfsFioLseek(), pfsFioLseek64(), pfsFioMkdir(), pfsFioMount(), pfsFioOpen(), pfsFioRead(), pfsFioReadlink(), pfsFioRemove(), pfsFioRename(), pfsFioRmdir(), pfsFioSymlink(), pfsFioSync(), pfsFioUmount(), pfsFioWrite(), play_thread(), PS2CamCallback(), PS2CamGetDeviceSring(), PS2CamReadData(), PS2CamReadDataCallback(), PS2CamSelectInterface(), PS2CamSetDeviceConfiguration(), ps2fs_Destroy(), ps2kbd_data_recv(), ps2kbd_getkeys(), ps2kbd_getkeys_raw(), ps2kbd_ioctl_flushbuffer(), ps2kbd_ioctl_resetkeymap(), ps2kbd_ioctl_setaltmap(), ps2kbd_ioctl_setctrlmap(), ps2kbd_ioctl_setkeymap(), ps2kbd_ioctl_setreadmode(), ps2kbd_ioctl_setspecialmap(), ps2mouse_data_recv(), repeat_thread(), setReg16(), setReg8(), smb_io_unlock(), sys_sem_signal(), tty_write(), usb_callback(), usb_mass_connect(), usb_transfer_callback(), and usbdUnlock().
WaitSema()
int WaitSema (int semid)
Referenced by _fs_lock(), AHX_LoadSong(), AHX_PlayThread(), alloc_lock(), alloc_msg(), audsrv_wait_audio(), call_client_callback(), cdda_procedure(), dev9DmaTransfer(), do_ps2mouse_setposition(), fio_read(), fioDataTransfer(), getReg8(), hddClose(), hddDevctl(), hddDread(), hddGetStat(), hddIoctl2(), hddLseek(), hddOpen(), hddRemove(), hddReName(), iLinkSendData(), keepalive_thread(), mc_chstat(), mc_close(), mc_dclose(), mc_dopen(), mc_dread(), mc_format(), mc_getstat(), mc_ioctl(), mc_lseek(), mc_mkdir(), mc_open(), mc_read(), mc_remove(), mc_rmdir(), mc_write(), NetManIoctl(), NetManQueryMainIF(), NetManRegisterNetIF(), NetManRegisterNetworkStack(), NetManRpcToggleGlobalNetIFLinkState(), NetManSetLinkMode(), NetManSetMainIF(), NetManToggleNetIFLinkState(), NetManUnregisterNetIF(), NetManUnregisterNetworkStack(), pfsFioCheckFileSlot(), pfsFioFormat(), pfsFioGetMountedUnit(), pfsFioMount(), play_thread(), PS2CamGetDeviceSring(), PS2CamReadData(), PS2CamSelectInterface(), PS2CamSetDeviceConfiguration(), ps2fs_Destroy(), ps2kbd_data_recv(), ps2kbd_ioctl_flushbuffer(), ps2kbd_ioctl_resetkeymap(), ps2kbd_ioctl_setaltmap(), ps2kbd_ioctl_setctrlmap(), ps2kbd_ioctl_setkeymap(), ps2kbd_ioctl_setreadmode(), ps2kbd_ioctl_setspecialmap(), ps2mouse_data_recv(), repeat_thread(), setReg16(), setReg8(), smb_io_lock(), stream_thread(), sys_arch_sem_wait(), tty_write(), usb_bulk_clear_halt(), usb_bulk_command(), usb_bulk_get_max_lun(), usb_bulk_reset(), usb_bulk_status(), usb_bulk_transfer(), usb_mass_update(), usb_queue_cmd(), usb_set_configuration(), usb_set_interface(), and usbdLock().