ps2sdk: iop/kernel/include/timrman.h File Reference
timrman.h File Reference
#include <types.h>
#include <irx.h>
Macros
#define timrman_IMPORTS
#define timrman_IMPORTS_start DECLARE_IMPORT_TABLE(timrman, 1, 1)
#define timrman_IMPORTS_end END_IMPORT_TABLE
#define I_AllocHardTimer DECLARE_IMPORT(4, AllocHardTimer)
#define I_ReferHardTimer DECLARE_IMPORT(5, ReferHardTimer)
#define I_FreeHardTimer DECLARE_IMPORT(6, FreeHardTimer)
#define I_SetTimerMode DECLARE_IMPORT(7, SetTimerMode)
#define I_GetTimerStatus DECLARE_IMPORT(8, GetTimerStatus)
#define I_SetTimerCounter DECLARE_IMPORT(9, SetTimerCounter)
#define I_GetTimerCounter DECLARE_IMPORT(10, GetTimerCounter)
#define I_SetTimerCompare DECLARE_IMPORT(11, SetTimerCompare)
#define I_GetTimerCompare DECLARE_IMPORT(12, GetTimerCompare)
#define I_SetHoldMode DECLARE_IMPORT(13, SetHoldMode)
#define I_GetHoldMode DECLARE_IMPORT(14, GetHoldMode)
#define I_GetHoldReg DECLARE_IMPORT(15, GetHoldReg)
#define I_GetHardTimerIntrCode DECLARE_IMPORT(16, GetHardTimerIntrCode)
Functions
int AllocHardTimer (int source, int size, int prescale)
int ReferHardTimer (int source, int size, int mode, int modemask)
int FreeHardTimer (int timid)
void SetTimerMode (int timid, int mode)
u32 GetTimerStatus (int timid)
void SetTimerCounter (int timid, u32 count)
u32 GetTimerCounter (int timid)
void SetTimerCompare (int timid, u32 compare)
u32 GetTimerCompare (int timid)
void SetHoldMode (int holdnum, int mode)
u32 GetHoldMode (int holdnum)
u32 GetHoldReg (int holdnum)
int GetHardTimerIntrCode (int timid)
Detailed Description
Timer manager.
Definition in file timrman.h.
Macro Definition Documentation
I_AllocHardTimer
#define I_AllocHardTimer DECLARE_IMPORT(4, AllocHardTimer)
Definition at line 113 of file timrman.h.
I_FreeHardTimer
#define I_FreeHardTimer DECLARE_IMPORT(6, FreeHardTimer)
Definition at line 115 of file timrman.h.
I_GetHardTimerIntrCode
#define I_GetHardTimerIntrCode DECLARE_IMPORT(16, GetHardTimerIntrCode)
Definition at line 125 of file timrman.h.
I_GetHoldMode
#define I_GetHoldMode DECLARE_IMPORT(14, GetHoldMode)
Definition at line 123 of file timrman.h.
I_GetHoldReg
#define I_GetHoldReg DECLARE_IMPORT(15, GetHoldReg)
Definition at line 124 of file timrman.h.
I_GetTimerCompare
#define I_GetTimerCompare DECLARE_IMPORT(12, GetTimerCompare)
Definition at line 121 of file timrman.h.
I_GetTimerCounter
#define I_GetTimerCounter DECLARE_IMPORT(10, GetTimerCounter)
Definition at line 119 of file timrman.h.
I_GetTimerStatus
#define I_GetTimerStatus DECLARE_IMPORT(8, GetTimerStatus)
Definition at line 117 of file timrman.h.
I_ReferHardTimer
#define I_ReferHardTimer DECLARE_IMPORT(5, ReferHardTimer)
Definition at line 114 of file timrman.h.
I_SetHoldMode
#define I_SetHoldMode DECLARE_IMPORT(13, SetHoldMode)
Definition at line 122 of file timrman.h.
I_SetTimerCompare
#define I_SetTimerCompare DECLARE_IMPORT(11, SetTimerCompare)
Definition at line 120 of file timrman.h.
I_SetTimerCounter
#define I_SetTimerCounter DECLARE_IMPORT(9, SetTimerCounter)
Definition at line 118 of file timrman.h.
I_SetTimerMode
#define I_SetTimerMode DECLARE_IMPORT(7, SetTimerMode)
Definition at line 116 of file timrman.h.
timrman_IMPORTS
#define timrman_IMPORTS
Value:
        timrman_IMPORTS_start \
 \
        I_AllocHardTimer \
        I_ReferHardTimer \
        I_FreeHardTimer \
 \
        I_SetTimerMode \
 \
        I_GetTimerStatus \
 \
        I_SetTimerCounter \
        I_GetTimerCounter \
 \
        I_SetTimerCompare \
        I_GetTimerCompare \
 \
        I_SetHoldMode \
        I_GetHoldMode \
 \
        I_GetHardTimerIntrCode \
 \
        timrman_IMPORTS_end END_IMPORT_TABLE
Definition at line 85 of file timrman.h.
timrman_IMPORTS_end
#define timrman_IMPORTS_end END_IMPORT_TABLE
Definition at line 111 of file timrman.h.
timrman_IMPORTS_start
#define timrman_IMPORTS_start DECLARE_IMPORT_TABLE(timrman, 1, 1)
Definition at line 110 of file timrman.h.
Function Documentation
AllocHardTimer()
int AllocHardTimer (int source, int size, int prescale)
Referenced by _start().
FreeHardTimer()
int FreeHardTimer (int timid)
GetHardTimerIntrCode()
int GetHardTimerIntrCode (int timid)
GetHoldMode()
u32 GetHoldMode (int holdnum)
GetHoldReg()
u32 GetHoldReg (int holdnum)
GetTimerCompare()
u32 GetTimerCompare (int timid)
GetTimerCounter()
u32 GetTimerCounter (int timid)
Referenced by mcman_probePS1Card(), mcman_probePS1Card2(), McReadPS1PDACard(), and McWritePS1PDACard().
GetTimerStatus()
u32 GetTimerStatus (int timid)
ReferHardTimer()
int ReferHardTimer (int source, int size, int mode, int modemask)
Referenced by _start().
SetHoldMode()
void SetHoldMode (int holdnum, int mode)
SetTimerCompare()
void SetTimerCompare (int timid, u32 compare)
SetTimerCounter()
void SetTimerCounter (int timid, u32 count)
SetTimerMode()
void SetTimerMode (int timid, int mode)
Referenced by _start().