ps2sdk: iop/network/udptty/src/udptty.c File Reference
udptty.c File Reference
#include <tamtypes.h>
#include <loadcore.h>
#include <stdio.h>
#include <thsemap.h>
#include <ioman.h>
#include <intrman.h>
#include <sysclib.h>
#include <sysmem.h>
#include <thbase.h>
#include <thevent.h>
#include <ps2ip.h>
#include <errno.h>
Macros
#define MODNAME "udptty"
#define DEVNAME "tty"
Functions
IRX_ID (MODNAME, 2, 1)
static int tty_init (iop_device_t *device)
static int tty_deinit (iop_device_t *device)
static int tty_stdout_fd (void)
static int tty_write (iop_file_t *file, void *buf, size_t size)
static int tty_error (void)
int _start (int argc, char **argv)
int _shutdown ()
static int udp_send (void *buf, size_t size)
Variables
struct irx_export_table _exp_udptty
static int udp_socket
static int tty_sema = -1
static iop_device_ops_t tty_ops
static iop_device_t tty_device
Macro Definition Documentation
DEVNAME
#define DEVNAME "tty"
Definition at line 35 of file udptty.c.
MODNAME
#define MODNAME "udptty"
Definition at line 30 of file udptty.c.
Function Documentation
_shutdown()
int _shutdown ()
Definition at line 215 of file udptty.c.
 {
     lwip_close(udp_socket);
     return 0;
 }
References lwip_close(), and udp_socket.
IRX_ID()
IRX_ID (MODNAME , 2 , 1)
tty_deinit()
static int tty_deinit (iop_device_t * device) static
Definition at line 247 of file udptty.c.
 {
     DeleteSema(tty_sema);
     return 0;
 }
References DeleteSema(), and tty_sema.
tty_error()
static int tty_error (void) static
Definition at line 269 of file udptty.c.
 {
     return -EIO;
 }
References EIO.
tty_init()
static int tty_init (iop_device_t * device) static
Definition at line 239 of file udptty.c.
 {
     if ((tty_sema = CreateMutex(IOP_MUTEX_UNLOCKED)) < 0)
         return -1;
     return 0;
 }
References CreateMutex(), IOP_MUTEX_UNLOCKED, and tty_sema.
tty_stdout_fd()
static int tty_stdout_fd (void) static
Definition at line 253 of file udptty.c.
 {
     return 1;
 }
tty_write()
static int tty_write (iop_file_t * file, void * buf, size_t size) static
Definition at line 258 of file udptty.c.
 {
     int res = 0;
     WaitSema(tty_sema);
     res = udp_send(buf, size);
     SignalSema(tty_sema);
     return res;
 }
References SignalSema(), tty_sema, udp_send(), and WaitSema().
udp_send()
static int udp_send (void * buf, size_t size) static
Definition at line 224 of file udptty.c.
 {
     struct sockaddr_in peer;
     peer.sin_family = AF_INET;
     peer.sin_port = htons(18194);
     peer.sin_addr.s_addr = inet_addr("255.255.255.255");
     lwip_sendto(udp_socket, buf, size, 0, (struct sockaddr *)&peer, sizeof(peer));
     return 0;
 }
References AF_INET, htons(), inet_addr, lwip_sendto(), in_addr::s_addr, sockaddr_in::sin_addr, sockaddr_in::sin_family, sockaddr_in::sin_port, and udp_socket.
Referenced by tty_write().
Variable Documentation
_exp_udptty
struct irx_export_table _exp_udptty extern
Referenced by _start().
tty_device
iop_device_t tty_device static
Initial value:
= {
    DEVNAME,
    IOP_DT_CHAR | IOP_DT_CONS,
    1,
    "TTY via SMAP UDP",
    &tty_ops}
Definition at line 67 of file udptty.c.
Referenced by _start().
tty_ops
iop_device_ops_t tty_ops static
Initial value:
= {
    tty_init,
    tty_deinit,
    (void *)tty_error,
    (void *)tty_stdout_fd,
    (void *)tty_stdout_fd,
    (void *)tty_error,
    (void *)tty_write,
    (void *)tty_error,
    (void *)tty_error,
    (void *)tty_error,
    (void *)tty_error,
    (void *)tty_error,
    (void *)tty_error,
    (void *)tty_error,
    (void *)tty_error,
    (void *)tty_error,
    (void *)tty_error}
Definition at line 47 of file udptty.c.
tty_sema
int tty_sema = -1 static
Definition at line 38 of file udptty.c.
Referenced by tty_deinit(), tty_init(), and tty_write().
udp_socket
int udp_socket static
Definition at line 37 of file udptty.c.
Referenced by _shutdown(), _start(), and udp_send().