ps2sdk: iop/sound/audsrv/src/upsamplers.h File Reference
upsamplers.h File Reference
Data Structures
struct upsample_t
Typedefs
typedef int(* upsampler_t) (struct upsample_t *)
Functions
upsampler_t find_upsampler (int freq, int bits, int channels)
Detailed Description
audsrv IOP-side upsamplers
Definition in file upsamplers.h.
Typedef Documentation
upsampler_t
typedef int(* upsampler_t) (struct upsample_t *)
Definition at line 25 of file upsamplers.h.
Function Documentation
find_upsampler()
upsampler_t find_upsampler (int freq, int bits, int channels)
Returns an upsampler from a specified format to SPU2's native
Parameters
freq frequency used
bits bits per sample
channels number of audio channels
Returns
a function to be used for upsampling, null if not found
Will return a function to convert source audio to Playstation's native. Note a very limited selection of upsamplers are available, only the most commonly used.
Definition at line 539 of file upsamplers.c.
 {
         struct entry_t *p = upsamplers;
         while (p->func != NULL)
         {
                 if (p->freq == freq && p->bits == bits && p->channels == channels)
                 {
                         /* found us an upsampler */
                         return p->func;
                 }
                 p++;
         }
         /* no more upsamplers */
         return NULL;
 }
References entry_t::bits, entry_t::channels, entry_t::freq, entry_t::func, NULL, and upsamplers.
Referenced by audsrv_format_ok(), cdda_procedure(), and play_thread().