ps2sdk: iop/sound/audsrv/src/upsamplers.c File Reference
upsamplers.c File Reference
#include <stdio.h>
#include "upsamplers.h"
Data Structures
struct entry_t
Functions
static void demux (short *mux, short *left, short *right, int len)
static int up_12000_16_stereo (struct upsample_t *up)
static int up_24000_16_stereo (struct upsample_t *up)
static void up_generic_16_stereo (struct upsample_t *up, const short *lut)
static void up_generic_16_mono (struct upsample_t *up, const short *lut)
static void up_generic_8_mono (struct upsample_t *up, const short *lut)
static void up_generic_8_stereo (struct upsample_t *up, const short *lut)
static int up_11025_8_mono (struct upsample_t *up)
static int up_11025_8_stereo (struct upsample_t *up)
static int up_11025_16_mono (struct upsample_t *up)
static int up_11025_16_stereo (struct upsample_t *up)
static int up_22050_8_mono (struct upsample_t *up)
static int up_22050_16_mono (struct upsample_t *up)
static int up_22050_16_stereo (struct upsample_t *up)
static int up_44100_8_mono (struct upsample_t *up)
static int up_44100_16_mono (struct upsample_t *up)
static int up_44100_16_stereo (struct upsample_t *up)
static int up_48000_16_mono (struct upsample_t *up)
static int up_48000_16_stereo (struct upsample_t *up)
upsampler_t find_upsampler (int freq, int bits, int channels)
Variables
static const short int up_11025_lut [512]
static const short up_22050_lut [512]
static const short up_44100_lut [512]
static entry_t upsamplers []
Detailed Description
audsrv IOP-side upsamplers
Definition in file upsamplers.c.
Function Documentation
demux()
static void demux (short * mux, short * left, short * right, int len) static
Demux, split interleaved audio to left and right
Parameters
mux source buffer
left left channel destination buffer
right right channel destination buffer
len number of samples to copy
Definition at line 302 of file upsamplers.c.
 {
         while (len > 0)
         {
                 *left++ = *mux++;
                 *right++ = *mux++;
                 len--;
         }
 }
Referenced by up_48000_16_stereo().
find_upsampler()
upsampler_t find_upsampler (int freq, int bits, int channels)
Returns an upsampler from a specified format to SPU2's native
Parameters
freq frequency used
bits bits per sample
channels number of audio channels
Returns
a function to be used for upsampling, null if not found
Will return a function to convert source audio to Playstation's native. Note a very limited selection of upsamplers are available, only the most commonly used.
Definition at line 539 of file upsamplers.c.
 {
         struct entry_t *p = upsamplers;
         while (p->func != NULL)
         {
                 if (p->freq == freq && p->bits == bits && p->channels == channels)
                 {
                         /* found us an upsampler */
                         return p->func;
                 }
                 p++;
         }
         /* no more upsamplers */
         return NULL;
 }
References entry_t::bits, entry_t::channels, entry_t::freq, entry_t::func, NULL, and upsamplers.
Referenced by audsrv_format_ok(), cdda_procedure(), and play_thread().
up_11025_16_mono()
static int up_11025_16_mono (struct upsample_t * up) static
Definition at line 427 of file upsamplers.c.
 {
         up_generic_16_mono(up, up_11025_lut);
         return 234; /* (11025 / 48000) * 512 * 16bit */
 }
References up_11025_lut, and up_generic_16_mono().
up_11025_16_stereo()
static int up_11025_16_stereo (struct upsample_t * up) static
Definition at line 433 of file upsamplers.c.
 {
         up_generic_16_stereo(up, up_11025_lut);
         return 470; /* (11025 / 48000) * 512 * stereo * 16bit */
 }
References up_11025_lut, and up_generic_16_stereo().
up_11025_8_mono()
static int up_11025_8_mono (struct upsample_t * up) static
Definition at line 415 of file upsamplers.c.
 {
         up_generic_8_mono(up, up_11025_lut);
         return 116; /* (11025 / 48000) * 512 */
 }
References up_11025_lut, and up_generic_8_mono().
up_11025_8_stereo()
static int up_11025_8_stereo (struct upsample_t * up) static
Definition at line 421 of file upsamplers.c.
 {
         up_generic_8_stereo(up, up_11025_lut);
         return 234; /* (11025 / 48000) * 512 * stereo */
 }
References up_11025_lut, and up_generic_8_stereo().
up_12000_16_stereo()
static int up_12000_16_stereo (struct upsample_t * up) static
Definition at line 312 of file upsamplers.c.
 {
         int p;
         short *left = up->left;
         short *right = up->right;
         short *src = (short *)up->src;
         for (p=0; p<128; p++)
         {
                 *left++ = src[0];
                 *right++ = src[1];
                 *left++ = src[0];
                 *right++ = src[1];
                 *left++ = src[0];
                 *right++ = src[1];
                 *left++ = *src++;
                 *right++ = *src++;
         }
         return 512;
 }
References upsample_t::left, upsample_t::right, and upsample_t::src.
up_22050_16_mono()
static int up_22050_16_mono (struct upsample_t * up) static
Definition at line 445 of file upsamplers.c.
 {
         up_generic_16_mono(up, up_22050_lut);
         return 470; /* (22050 / 48000) * 512 * 2 */
 }
References up_22050_lut, and up_generic_16_mono().
up_22050_16_stereo()
static int up_22050_16_stereo (struct upsample_t * up) static
Definition at line 451 of file upsamplers.c.
 {
         up_generic_16_stereo(up, up_22050_lut);
         return 940; /* (22050 / 48000) * 512 * stereo * 16bit */
 }
References up_22050_lut, and up_generic_16_stereo().
up_22050_8_mono()
static int up_22050_8_mono (struct upsample_t * up) static
Definition at line 439 of file upsamplers.c.
 {
         up_generic_8_mono(up, up_22050_lut);
         return 235; /* (22050 / 48000) * 512 */
 }
References up_22050_lut, and up_generic_8_mono().
up_24000_16_stereo()
static int up_24000_16_stereo (struct upsample_t * up) static
Definition at line 334 of file upsamplers.c.
 {
         int p;
         short *left = up->left;
         short *right = up->right;
         short *src = (short *)up->src;
         for (p=0; p<256; p++)
         {
                 *left++ = src[0];
                 *right++ = src[1];
                 *left++ = *src++;
                 *right++ = *src++;
         }
         return 1024;
 }
References upsample_t::left, upsample_t::right, and upsample_t::src.
up_44100_16_mono()
static int up_44100_16_mono (struct upsample_t * up) static
Definition at line 463 of file upsamplers.c.
 {
         up_generic_16_mono(up, up_44100_lut);
         return 940; /* (44100 / 48000) * 512 * 16bit */
 }
References up_44100_lut, and up_generic_16_mono().
up_44100_16_stereo()
static int up_44100_16_stereo (struct upsample_t * up) static
Definition at line 469 of file upsamplers.c.
 {
         up_generic_16_stereo(up, up_44100_lut);
         return 1880; /* (44100 / 48000) * 512 * stereo * 16bit */
 }
References up_44100_lut, and up_generic_16_stereo().
up_44100_8_mono()
static int up_44100_8_mono (struct upsample_t * up) static
Definition at line 457 of file upsamplers.c.
 {
         up_generic_8_mono(up, up_44100_lut);
         return 470; /* (44100 / 48000) * 512 */
 }
References up_44100_lut, and up_generic_8_mono().
up_48000_16_mono()
static int up_48000_16_mono (struct upsample_t * up) static
Definition at line 475 of file upsamplers.c.
 {
         int i;
         short *left = (short *)up->left;
         short *right = (short *)up->right;
         short *src = (short *)up->src;
         for (i=0; i<512; i++)
         {
                 *left++ = *right++ = *src++;
         }
         return 1024; /* 512 * 16bit */
 }
References upsample_t::left, upsample_t::right, and upsample_t::src.
up_48000_16_stereo()
static int up_48000_16_stereo (struct upsample_t * up) static
Definition at line 490 of file upsamplers.c.
 {
         /* simple demux */
         demux((short *)up->src, up->left, up->right, 512);
         return 2048; /* 512 * stereo * 16bit */
 }
References demux(), upsample_t::left, upsample_t::right, and upsample_t::src.
up_generic_16_mono()
static void up_generic_16_mono (struct upsample_t * up, const short * lut) static
Definition at line 367 of file upsamplers.c.
 {
         int q, p;
         short *left = up->left;
         short *right = up->right;
         short *src = (short *)up->src;
         for (p=0; p<512; p++)
         {
                 q = lut[p];
                 *left++ = *right++ = src[q];
         }
 }
References upsample_t::left, upsample_t::right, and upsample_t::src.
Referenced by up_11025_16_mono(), up_22050_16_mono(), and up_44100_16_mono().
up_generic_16_stereo()
static void up_generic_16_stereo (struct upsample_t * up, const short * lut) static
Definition at line 352 of file upsamplers.c.
 {
         int q, p;
         short *left = up->left;
         short *right = up->right;
         short *src = (short *)up->src;
         for (p=0; p<512; p++)
         {
                 q = lut[p] << 1;
                 *left++ = src[q + 0];
                 *right++ = src[q + 1];
         }
 }
References upsample_t::left, upsample_t::right, and upsample_t::src.
Referenced by up_11025_16_stereo(), up_22050_16_stereo(), and up_44100_16_stereo().
up_generic_8_mono()
static void up_generic_8_mono (struct upsample_t * up, const short * lut) static
Definition at line 381 of file upsamplers.c.
 {
         int q, p;
         signed char b;
         short *left = up->left;
         short *right = up->right;
         char *src = (char *)up->src;
         for (p=0; p<512; p++)
         {
                 q = lut[p];
                 b = src[q];
                 *left++ = *right++ = (short)((b + (b << 8)) - 32768);
         }
 }
References upsample_t::left, upsample_t::right, and upsample_t::src.
Referenced by up_11025_8_mono(), up_22050_8_mono(), and up_44100_8_mono().
up_generic_8_stereo()
static void up_generic_8_stereo (struct upsample_t * up, const short * lut) static
Definition at line 397 of file upsamplers.c.
 {
         int q, p;
         signed char b;
         short *left = up->left;
         short *right = up->right;
         char *src = (char *)up->src;
         for (p=0; p<512; p++)
         {
                 q = lut[p] << 1;
                 b = src[q + 0];
                 *left++ = (short)((b + (b << 8)) - 32768);
                 b = src[q + 1];
                 *right++ = (short)((b + (b << 8)) - 32768);
         }
 }
References upsample_t::left, upsample_t::right, and upsample_t::src.
Referenced by up_11025_8_stereo().
Variable Documentation
up_11025_lut
const short int up_11025_lut[512] static
lut for converting 11025 -> 48000
Definition at line 90 of file upsamplers.c.
Referenced by up_11025_16_mono(), up_11025_16_stereo(), up_11025_8_mono(), and up_11025_8_stereo().
up_22050_lut
const short up_22050_lut[512] static
lut for converting 22050 -> 48000
Definition at line 159 of file upsamplers.c.
Referenced by up_22050_16_mono(), up_22050_16_stereo(), and up_22050_8_mono().
up_44100_lut
const short up_44100_lut[512] static
lut for converting 44100 -> 48000
Definition at line 228 of file upsamplers.c.
Referenced by up_44100_16_mono(), up_44100_16_stereo(), and up_44100_8_mono().
upsamplers
entry_t upsamplers[] static
Initial value:
=
{
        {11025,  8, 1, up_11025_8_mono},
        {11025,  8, 2, up_11025_8_stereo},
        {11025, 16, 1, up_11025_16_mono},
        {11025, 16, 2, up_11025_16_stereo},
        {12000, 16, 2, up_12000_16_stereo},
        {22050,  8, 1, up_22050_8_mono},
        {22050, 16, 1, up_22050_16_mono},
        {22050, 16, 2, up_22050_16_stereo},
        {24000, 16, 2, up_24000_16_stereo},
        {44100,  8, 1, up_44100_8_mono},
        {44100, 16, 1, up_44100_16_mono},
        {44100, 16, 2, up_44100_16_stereo},
        {48000, 16, 1, up_48000_16_mono},
        {48000, 16, 2, up_48000_16_stereo},
        {0, 0, 0, 0}
}
supported upsamplers
Definition at line 510 of file upsamplers.c.
Referenced by find_upsampler().