ps2sdk: iop/usb/usbhdfsd/src/include/scache.h File Reference
scache.h File Reference
Functions
cache_set * scache_init (mass_dev *dev, int sectorSize)
void scache_close (cache_set *cache)
void scache_kill (cache_set *cache)
int scache_readSector (cache_set *cache, unsigned int sector, void **buf)
int scache_writeSector (cache_set *cache, unsigned int sector)
int scache_flushSectors (cache_set *cache)
void scache_invalidate (cache_set *cache, unsigned int sector, int count)
void scache_getStat (cache_set *cache, unsigned int *access, unsigned int *hits)
Function Documentation
scache_close()
void scache_close (cache_set * cache)
Definition at line 330 of file scache.c.
 {
     M_DEBUG("scache: close devId = %i \n", cache->bd->devNr);
     scache_flushSectors(cache);
     scache_kill(cache);
 }
References scache_flushSectors(), scache_kill(), and XPRINTF.
scache_flushSectors()
int scache_flushSectors (cache_set * cache)
Definition at line 130 of file scache.c.
 {
     unsigned int i;
     int counter = 0, ret;
     M_DEBUG("scache: flushSectors devId = %i \n", cache->bd->devNr);
     M_DEBUG("scache: flushSectors writeFlag=%d\n", cache->writeFlag);
     //no write operation occured since last flush
     if (cache->writeFlag == 0) {
         return 0;
     }
     for (i = 0; i < CACHE_SIZE; i++) {
         if (cache->rec[i].writeDirty) {
             M_DEBUG("scache: flushSectors dirty index=%d sector=%u \n", i, cache->rec[i].sector);
             ret = WRITE_SECTOR(cache, cache->rec[i].sector, cache->sectorBuf + (i * BLOCK_SIZE), BLOCK_SIZE / cache->sectorSize);
             if (ret < 0) {
                 M_PRINTF("scache: ERROR writing sector to disk! sector=%u\n", cache->rec[i].sector);
                 return ret;
             }
             cache->rec[i].writeDirty = 0;
             counter++;
         }
     }
     cache->writeFlag = 0;
     return counter;
 }
References BLOCK_SIZE, CACHE_SIZE, printf(), cache_set::rec, scache_flushSector(), cache_record::sector, cache_set::sectorBuf, WRITE_SECTOR, cache_record::writeDirty, cache_set::writeFlag, and XPRINTF.
Referenced by scache_close().
scache_getStat()
void scache_getStat (cache_set * cache, unsigned int * access, unsigned int * hits)
Definition at line 291 of file scache.c.
{
         *access = cache->cacheAccess;
         *hits = cache->cacheHits;
 }
scache_init()
cache_set* scache_init (mass_dev * dev, int sectorSize)
Definition at line 299 of file scache.c.
 {
         cache_set* cache;
         XPRINTF("cache: init devId = %i sectSize = %u \n", dev->devId, sectSize);
         cache = malloc(sizeof(cache_set));
         if (cache == NULL) {
                 printf("scache init! Sector cache: can't alloate cache!\n");
                 return NULL;
         }
         XPRINTF("scache init! \n");
         cache->dev = dev;
         cache->sectorBuf = (unsigned char*) malloc(BLOCK_SIZE * CACHE_SIZE);
         if (cache->sectorBuf == NULL) {
                 printf("Sector cache: can't alloate memory of size:%d \n", BLOCK_SIZE * CACHE_SIZE);
                 free(cache);
                 return NULL;
         }
         XPRINTF("Sector cache: allocated memory at:%p of size:%d \n", cache->sectorBuf, BLOCK_SIZE * CACHE_SIZE);
         //added by Hermes
         cache->sectorSize = sectSize;
         cache->indexLimit = BLOCK_SIZE/cache->sectorSize; //number of sectors per 1 cache slot
 #ifdef SCACHE_RECORD_STATS
         cache->cacheAccess = 0;
         cache->cacheHits = 0;
 #endif
         initRecords(cache);
         return cache;
 }
References BLOCK_SIZE, CACHE_SIZE, mass_dev::devId, free, cache_set::indexLimit, initRecords(), malloc, NULL, printf(), cache_set::sectorBuf, cache_set::sectorSize, and XPRINTF.
scache_invalidate()
void scache_invalidate (cache_set * cache, unsigned int sector, int count)
Definition at line 279 of file scache.c.
{
         int index; //index is given in single sectors not octal sectors
         int i;
         XPRINTF("cache: invalidate devId = %i sector = %u count = %d \n", cache->dev->devId, sector, count);
         for(i = 0; i < count; i++, sector++)
         {
                 index = getSlot(cache, sector);
                 if (index >=  0) { //sector found in cache. Write back and invalidate the block it belongs to.
                         scache_flushSector(cache, index);
                         cache->rec[index].sector = 0xFFFFFFF0;
                         cache->rec[index].tax = 0;
                         cache->rec[index].writeDirty = 0;
                 }
         }
 }
References getSlot(), index(), cache_set::rec, scache_flushSector(), cache_record::sector, cache_record::tax, cache_record::writeDirty, and XPRINTF.
scache_kill()
void scache_kill (cache_set * cache)
Definition at line 320 of file scache.c.
 {
     M_DEBUG("scache: kill devId = %i \n", cache->bd->devNr);
     if (cache->sectorBuf != NULL) {
         free(cache->sectorBuf);
         cache->sectorBuf = NULL;
     }
     free(cache);
 }
References free, NULL, cache_set::sectorBuf, and XPRINTF.
Referenced by scache_close().
scache_readSector()
int scache_readSector (cache_set * cache, unsigned int sector, void ** buf)
Definition at line 161 of file scache.c.
 {
     int index; //index is given in single sectors not octal sectors
     int ret;
     unsigned int alignedSector;
     M_DEBUG("scache: readSector devId = %i %p sector = %u \n", cache->bd->devNr, cache, sector);
     if (cache == NULL) {
         M_PRINTF("scache: devId cache not created = %i \n", cache->bd->devNr);
         return -1;
     }
 #ifdef SCACHE_RECORD_STATS
     cache->cacheAccess++;
 #endif
     index = getIndexRead(cache, sector);
     M_DEBUG("scache: indexRead=%i \n", index);
     if (index >= 0) { //sector found in cache
 #ifdef SCACHE_RECORD_STATS
         cache->cacheHits++;
 #endif
         *buf = cache->sectorBuf + (index * cache->sectorSize);
         M_DEBUG("scache: hit and done reading sector \n");
         return cache->sectorSize;
     }
     //compute alignedSector - to prevent storage of duplicit sectors in slots
     alignedSector = (sector / cache->indexLimit) * cache->indexLimit;
     index         = getIndexWrite(cache, alignedSector);
     M_DEBUG("scache: indexWrite=%i slot=%d  alignedSector=%u\n", index, index / cache->indexLimit, alignedSector);
     ret = READ_SECTOR(cache, alignedSector, cache->sectorBuf + (index * cache->sectorSize), BLOCK_SIZE / cache->sectorSize);
     if (ret < 0) {
         M_PRINTF("scache: ERROR reading sector from disk! sector=%u\n", alignedSector);
         return ret;
     }
     *buf = cache->sectorBuf + (index * cache->sectorSize) + ((sector % cache->indexLimit) * cache->sectorSize);
     M_DEBUG("scache: done reading physical sector \n");
     //write precaution
     //cache->flushCounter++;
     //if (cache->flushCounter == FLUSH_TRIGGER) {
     //scache_flushSectors(cache);
     //}
     return cache->sectorSize;
 }
References BLOCK_SIZE, getIndexRead(), getIndexWrite(), index(), cache_set::indexLimit, NULL, printf(), READ_SECTOR, cache_set::sectorBuf, cache_set::sectorSize, and XPRINTF.
scache_writeSector()
int scache_writeSector (cache_set * cache, unsigned int sector)
Definition at line 244 of file scache.c.
 {
     int index; //index is given in single sectors not octal sectors
     //int ret;
     M_DEBUG("scache: writeSector devId = %i sector = %u \n", cache->bd->devNr, sector);
     index = getSlot(cache, sector);
     if (index < 0) { //sector not found in cache
         M_PRINTF("scache: writeSector: ERROR! the sector is not allocated! \n");
         return -1;
     }
     M_DEBUG("scache: slotFound=%i \n", index);
     //prefere written sectors to stay in cache longer than read sectors
     cache->rec[index].tax += 2;
     //set dirty status
     cache->rec[index].writeDirty = 1;
     cache->writeFlag++;
     M_DEBUG("scache: done soft writing sector \n");
     //write precaution
     //cache->flushCounter++;
     //if (cache->flushCounter == FLUSH_TRIGGER) {
     //scache_flushSectors(devId);
     //}
     return cache->sectorSize;
 }
References getSlot(), index(), printf(), cache_set::rec, cache_set::sectorSize, cache_record::tax, cache_record::writeDirty, cache_set::writeFlag, and XPRINTF.