ps2sdk: iop/usb/usbhdfsd/src/include/fat_driver.h File Reference
fat_driver.h File Reference
Data Structures
struct fat_dir_list
struct fat_dir_chain_record
struct fat_dir
Macros
#define DIR_CHAIN_SIZE 32
#define FAT_MAX_NAME 256
#define FAT_ATTR_READONLY 0x01
#define FAT_ATTR_HIDDEN 0x02
#define FAT_ATTR_SYSTEM 0x04
#define FAT_ATTR_VOLUME_LABEL 0x08
#define FAT_ATTR_DIRECTORY 0x10
#define FAT_ATTR_ARCHIVE 0x20
Functions
int strEqual (const char *s1, const char *s2)
int fat_mount (mass_dev *dev, unsigned int start, unsigned int count)
void fat_forceUnmount (mass_dev *dev)
void fat_setFatDirChain (fat_driver *fatd, fat_dir *fatDir)
int fat_readFile (fat_driver *fatd, fat_dir *fatDir, unsigned int filePos, unsigned char *buffer, unsigned int size)
int fat_getFirstDirentry (fat_driver *fatd, const char *dirName, fat_dir_list *fatdlist, fat_dir *fatDir_host, fat_dir *fatDir)
int fat_getNextDirentry (fat_driver *fatd, fat_dir_list *fatdlist, fat_dir *fatDir)
fat_driver * fat_getData (int device)
int fat_getFileStartCluster (fat_driver *fatd, const char *fname, unsigned int *startCluster, fat_dir *fatDir)
int fat_getClusterChain (fat_driver *fatd, unsigned int cluster, unsigned int *buf, unsigned int bufSize, int startFlag)
Macro Definition Documentation
DIR_CHAIN_SIZE
#define DIR_CHAIN_SIZE 32
Definition at line 4 of file fat_driver.h.
FAT_ATTR_ARCHIVE
#define FAT_ATTR_ARCHIVE 0x20
Definition at line 14 of file fat_driver.h.
FAT_ATTR_DIRECTORY
#define FAT_ATTR_DIRECTORY 0x10
Definition at line 13 of file fat_driver.h.
FAT_ATTR_HIDDEN
#define FAT_ATTR_HIDDEN 0x02
Definition at line 10 of file fat_driver.h.
FAT_ATTR_READONLY
#define FAT_ATTR_READONLY 0x01
Definition at line 9 of file fat_driver.h.
FAT_ATTR_SYSTEM
#define FAT_ATTR_SYSTEM 0x04
Definition at line 11 of file fat_driver.h.
FAT_ATTR_VOLUME_LABEL
#define FAT_ATTR_VOLUME_LABEL 0x08
Definition at line 12 of file fat_driver.h.
FAT_MAX_NAME
#define FAT_MAX_NAME 256
Definition at line 6 of file fat_driver.h.
Function Documentation
fat_forceUnmount()
void fat_forceUnmount (mass_dev * dev)
Definition at line 1031 of file fat_driver.c.
 {
         unsigned int i;
         XPRINTF("USBHDFSD: usb fat: forceUnmount devId %i \n", dev->devId);
         for (i = 0; i < NUM_DRIVES; ++i)
         {
                 if (g_fatd[i] != NULL && g_fatd[i]->dev == dev)
                         g_fatd[i] = NULL;
         }
 }
References mass_dev::devId, g_fatd, NULL, NUM_DRIVES, and XPRINTF.
fat_getClusterChain()
int fat_getClusterChain (fat_driver * fatd, unsigned int cluster, unsigned int * buf, unsigned int bufSize, int startFlag)
Definition at line 235 of file fat_driver.c.
 {
     M_DEBUG("%s\n", __func__);
     if (cluster == fatd->lastChainCluster) {
         return fatd->lastChainResult;
     }
     switch (fatd->partBpb.fatType) {
     case FAT12:
         fatd->lastChainResult = fat_getClusterChain12(fatd, cluster, buf, bufSize, startFlag);
         break;
     case FAT16:
         fatd->lastChainResult = fat_getClusterChain16(fatd, cluster, buf, bufSize, startFlag);
         break;
     case FAT32:
         fatd->lastChainResult = fat_getClusterChain32(fatd, cluster, buf, bufSize, startFlag);
         break;
     }
     fatd->lastChainCluster = cluster;
     return fatd->lastChainResult;
 }
References FAT12, FAT16, FAT32, fat_getClusterChain12(), fat_getClusterChain16(), fat_getClusterChain32(), fat_bpb::fatType, fat_driver::lastChainCluster, fat_driver::lastChainResult, M_DEBUG, and fat_driver::partBpb.
Referenced by fat_deleteClusterChain(), fat_getDirentrySectorData(), fat_readFile(), fat_setFatDirChain(), and fat_writeFile().
fat_getData()
fat_driver* fat_getData (int device)
Definition at line 1032 of file fat_driver.c.
 {
     M_DEBUG("%s(%d)\n", __func__, device);
     if (device >= NUM_DRIVES)
         return NULL;
     if (g_fatd[device] == NULL || g_fatd[device]->bd == NULL)
         return NULL;
     return g_fatd[device];
 }
References DelayThread(), g_fatd, M_DEBUG, mass_stor_configureNextDevice(), NULL, and NUM_DRIVES.
Referenced by fat_stopAll(), fat_stopUnit(), fs_close(), fs_devctl(), fs_dopen(), fs_dread(), fs_getstat(), fs_ioctl(), fs_lseek(), fs_mkdir(), fs_open(), fs_read(), fs_remove(), fs_rename(), fs_rmdir(), and fs_write().
fat_getFileStartCluster()
int fat_getFileStartCluster (fat_driver * fatd, const char * fname, unsigned int * startCluster, fat_dir * fatDir)
Definition at line 702 of file fat_driver.c.
 {
     static char tmpName[FAT_MAX_NAME + 1]; // TOO BIG FOR STACK!
     unsigned int i, offset;
     int ret;
     M_DEBUG("%s\n", __func__);
     offset = 0;
     i      = 0;
     *startCluster = 0;
     if (fatDir != NULL) {
         memset(fatDir, 0, sizeof(fat_dir));
         fatDir->attr = FAT_ATTR_DIRECTORY;
     }
     if (fname[i] == '/') {
         i++;
     }
     for (; fname[i] != 0; i++) {
         if (fname[i] == '/') {   //directory separator
             tmpName[offset] = 0; //terminate string
             ret             = fat_getDirentryStartCluster(fatd, tmpName, startCluster, fatDir);
             if (ret < 0) {
                 return -ENOENT;
             }
             offset = 0;
         } else {
             tmpName[offset] = fname[i];
             offset++;
         }
     } //ends "for"
     //and the final file
     tmpName[offset] = 0; //terminate string
     M_DEBUG("Ready to get cluster for file \"%s\"\n", tmpName);
     if (fatDir != NULL) {
         //if the last char of the name was slash - the name was already found -exit
         if (offset == 0) {
             M_DEBUG("Exiting from fat_getFileStartCluster with a folder\n");
             return 2;
         }
         ret = fat_getDirentryStartCluster(fatd, tmpName, startCluster, fatDir);
         if (ret < 0) {
             M_DEBUG("Exiting from fat_getFileStartCluster with error %i\n", ret);
             return ret;
         }
         M_DEBUG("file's startCluster found. Name=%s, cluster=%u \n", fname, *startCluster);
     }
     M_DEBUG("Exiting from fat_getFileStartCluster with no error.\n");
     return 1;
 }
References fat_dir::attr, ENOENT, FAT_ATTR_DIRECTORY, fat_getDirentryStartCluster(), FAT_MAX_NAME, M_DEBUG, memset(), NULL, and XPRINTF.
Referenced by fat_createFile(), fat_deleteFile(), fat_getFirstDirentry(), fat_renameFile(), fs_getstat(), fs_open(), fs_remove(), and fs_rename().
fat_getFirstDirentry()
int fat_getFirstDirentry (fat_driver * fatd, const char * dirName, fat_dir_list * fatdlist, fat_dir * fatDir_host, fat_dir * fatDir)
Definition at line 939 of file fat_driver.c.
 {
     int ret;
     unsigned int startCluster = 0;
     M_DEBUG("%s\n", __func__);
     ret = fat_getFileStartCluster(fatd, dirName, &startCluster, fatDir_host);
     if (ret < 0) { //dir name not found
         return -ENOENT;
     }
     //check that direntry is directory
     if (!(fatDir_host->attr & FAT_ATTR_DIRECTORY)) {
         return -ENOTDIR; //it's a file - exit
     }
     fatdlist->direntryCluster = startCluster;
     fatdlist->direntryIndex   = 0;
     return fat_getNextDirentry(fatd, fatdlist, fatDir);
 }
References fat_dir::attr, fat_dir_list::direntryCluster, fat_dir_list::direntryIndex, ENOENT, ENOTDIR, FAT_ATTR_DIRECTORY, fat_getFileStartCluster(), fat_getNextDirentry(), and M_DEBUG.
Referenced by fs_dopen().
fat_getNextDirentry()
int fat_getNextDirentry (fat_driver * fatd, fat_dir_list * fatdlist, fat_dir * fatDir)
Definition at line 861 of file fat_driver.c.
 {
     static fat_direntry_summary dir; // TOO BIG FOR STACK!
     int i, ret;
     unsigned int startSector, dirSector, dirPos, dirCluster;
     unsigned char cont, new_entry;
     M_DEBUG("%s\n", __func__);
     //the getFirst function was not called
     if (fatdlist->direntryCluster == 0xFFFFFFFF || fatDir == NULL) {
         return -EFAULT;
     }
     dirCluster = fatdlist->direntryCluster;
     //clear name strings
     dir.sname[0] = 0;
     dir.name[0]  = 0;
     ret = fat_getDirentrySectorData(fatd, &dirCluster, &startSector, &dirSector);
     if (ret < 0)
         return ret;
     M_DEBUG("dirCluster=%u startSector=%u (%u) dirSector=%u \n", dirCluster, startSector, startSector * fatd->bd->sectorSize, dirSector);
     //go through first directory sector till the max number of directory sectors
     //or stop when no more direntries detected
     //dlanor: but avoid rescanning same areas redundantly (if possible)
     cont      = 1;
     new_entry = 1;
     dirPos    = (fatdlist->direntryIndex * 32) % fatd->partBpb.sectorSize;
     for (i = ((fatdlist->direntryIndex * 32) / fatd->partBpb.sectorSize); (i < dirSector) && cont; i++) {
         unsigned char* sbuf = NULL; //sector buffer
         //At cluster borders, get correct sector from cluster chain buffer
         if ((dirCluster != 0) && (new_entry || (i % fatd->partBpb.clusterSize == 0))) {
             startSector = fat_cluster2sector(&fatd->partBpb, fatd->cbuf[(i / fatd->partBpb.clusterSize)])
                 - i + (i % fatd->partBpb.clusterSize);
             new_entry = 0;
         }
         ret = READ_SECTOR(fatd, startSector + i, sbuf);
         if (ret < 0) {
             M_DEBUG("Read directory  sector failed ! sector=%u\n", startSector + i);
             return -EIO;
         }
         // go through sector from current pos till its end
         while (cont && (dirPos < fatd->partBpb.sectorSize)) {
             fat_direntry* dir_entry = (fat_direntry*)(sbuf + dirPos);
             cont                    = fat_getDirentry(fatd->partBpb.fatType, dir_entry, &dir); //get a directory entry from sector
             fatdlist->direntryIndex++;                                                         //Note current entry processed
             if (cont == 1) {                                                                   //when short file name entry detected
                 fat_setFatDir(fatd, fatDir, dirCluster, &dir_entry->sfn, &dir, 0);
 #if 0
                         M_DEBUG("fat_getNextDirentry %c%c%c%c%c%c %x %s %s\n",
                                 (dir.attr & FAT_ATTR_VOLUME_LABEL) ? 'v' : '-',
                                 (dir.attr & FAT_ATTR_DIRECTORY) ? 'd' : '-',
                                 (dir.attr & FAT_ATTR_READONLY) ? 'r' : '-',
                                 (dir.attr & FAT_ATTR_ARCHIVE) ? 'a' : '-',
                                 (dir.attr & FAT_ATTR_SYSTEM) ? 's' : '-',
                                 (dir.attr & FAT_ATTR_HIDDEN) ? 'h' : '-',
                                 dir.attr,
                                 dir.sname,
                                 dir.name);
 #endif
                 return 1;
             }
             dirPos += sizeof(fat_direntry);
         } //ends "while"
         dirPos = 0;
     } //ends "for"
     // when we get this far - reset the direntry cluster
     fatdlist->direntryCluster = 0xFFFFFFFF; //no more files
     return 0;                               //indicate that no direntry is avalable
 }
References fat_direntry_summary::attr, fat_driver::bd, fat_driver::cbuf, fat_bpb::clusterSize, fat_driver::dev, fat_dir_list::direntryCluster, fat_dir_list::direntryIndex, EFAULT, EIO, FAT_ATTR_ARCHIVE, FAT_ATTR_DIRECTORY, FAT_ATTR_HIDDEN, FAT_ATTR_READONLY, FAT_ATTR_SYSTEM, FAT_ATTR_VOLUME_LABEL, fat_cluster2sector(), fat_getDirentry(), fat_getDirentrySectorData(), fat_setFatDir(), fat_bpb::fatType, M_DEBUG, fat_direntry_summary::name, NULL, fat_driver::partBpb, READ_SECTOR, sbuf, block_device::sectorSize, fat_bpb::sectorSize, SBP2Device::sectorSize, fat_direntry::sfn, fat_direntry_summary::sname, and XPRINTF.
Referenced by fat_getFirstDirentry(), and fs_dread().
fat_mount()
int fat_mount (mass_dev * dev, unsigned int start, unsigned int count)
Definition at line 984 of file fat_driver.c.
 {
         fat_driver* fatd = NULL;
         unsigned int i;
         for (i = 0; i < NUM_DRIVES && fatd == NULL; ++i)
         {
                 if (g_fatd[i] == NULL)
                 {
                         XPRINTF("USBHDFSD: usb fat: allocate fat_driver %d!\n", sizeof(fat_driver));
                         g_fatd[i] = malloc(sizeof(fat_driver));
                         if (g_fatd[i] != NULL)
{
                                 g_fatd[i]->dev = NULL;
                         }
                         fatd = g_fatd[i];
                 }
                 else if(g_fatd[i]->dev == NULL)
                 {
                         fatd = g_fatd[i];
                 }
         }
         if (fatd == NULL)
         {
                 printf("USBHDFSD: usb fat: unable to allocate drive!\n");
                 return -1;
         }
         if (fatd->dev != NULL)
         {
                 printf("USBHDFSD: usb fat: mount ERROR: alread mounted\n");
                 fat_forceUnmount(fatd->dev);
         }
         if (fat_getPartitionBootSector(dev, start, &fatd->partBpb) < 0)
                 return -1;
         fatd->dev = dev;
         fatd->deIdx = 0;
         fatd->clStackIndex = 0;
         fatd->clStackLast = 0;
         fatd->lastChainCluster = 0xFFFFFFFF;
         fatd->lastChainResult = -1;
         return 0;
 }
References fat_driver::clStackIndex, fat_driver::clStackLast, fat_driver::deIdx, fat_driver::dev, fat_forceUnmount(), fat_getPartitionBootSector(), g_fatd, fat_driver::lastChainCluster, fat_driver::lastChainResult, malloc, NULL, NUM_DRIVES, fat_driver::partBpb, printf(), and XPRINTF.
fat_readFile()
int fat_readFile (fat_driver * fatd, fat_dir * fatDir, unsigned int filePos, unsigned char * buffer, unsigned int size)
Definition at line 775 of file fat_driver.c.
 {
     int ret, chainSize;
     unsigned int i, j, startSector, clusterChainStart, bufSize, sectorSkip, clusterSkip, dataSkip;
     unsigned char nextChain;
     unsigned int bufferPos, fileCluster, clusterPos;
     M_DEBUG("%s\n", __func__);
     fat_getClusterAtFilePos(fatd, fatDir, filePos, &fileCluster, &clusterPos);
     sectorSkip  = (filePos - clusterPos) / fatd->partBpb.sectorSize;
     clusterSkip = sectorSkip / fatd->partBpb.clusterSize;
     sectorSkip %= fatd->partBpb.clusterSize;
     dataSkip  = filePos % fatd->partBpb.sectorSize;
     bufferPos = 0;
     M_DEBUG("fileCluster = %u,  clusterPos= %u clusterSkip=%u, sectorSkip=%u dataSkip=%u \n",
         fileCluster, clusterPos, clusterSkip, sectorSkip, dataSkip);
     if (fileCluster < 2) {
         return 0;
     }
     bufSize           = fatd->bd->sectorSize;
     nextChain         = 1;
     clusterChainStart = 1;
     while (nextChain && size > 0) {
         if ((chainSize = fat_getClusterChain(fatd, fileCluster, fatd->cbuf, MAX_DIR_CLUSTER, clusterChainStart)) < 0) {
             return chainSize;
         }
         clusterChainStart = 0;
         if (chainSize >= MAX_DIR_CLUSTER) { //the chain is full, but more chain parts exist
             fileCluster = fatd->cbuf[MAX_DIR_CLUSTER - 1];
         } else { //chain fits in the chain buffer completely - no next chain needed
             nextChain = 0;
         }
         while (clusterSkip >= MAX_DIR_CLUSTER) {
             chainSize         = fat_getClusterChain(fatd, fileCluster, fatd->cbuf, MAX_DIR_CLUSTER, clusterChainStart);
             clusterChainStart = 0;
             if (chainSize >= MAX_DIR_CLUSTER) { //the chain is full, but more chain parts exist
                 fileCluster = fatd->cbuf[MAX_DIR_CLUSTER - 1];
             } else { //chain fits in the chain buffer completely - no next chain needed
                 nextChain = 0;
             }
             clusterSkip -= MAX_DIR_CLUSTER;
         }
         //process the cluster chain (fatd->cbuf) and skip leading clusters if needed
         for (i = 0 + clusterSkip; i < chainSize && size > 0; i++) {
             //read cluster and save cluster content
             startSector = fat_cluster2sector(&fatd->partBpb, fatd->cbuf[i]);
             //process all sectors of the cluster (and skip leading sectors if needed)
             for (j = 0 + sectorSkip; j < fatd->partBpb.clusterSize && size > 0; j++) {
                 unsigned char* sbuf = NULL; //sector buffer
                 ret = READ_SECTOR(fatd, startSector + j, sbuf);
                 if (ret < 0) {
                     M_DEBUG("Read sector failed ! sector=%u\n", startSector + j);
                     return bufferPos;
                 }
                 //compute exact size of transfered bytes
                 if (size < bufSize) {
                     bufSize = size + dataSkip;
                 }
                 if (bufSize > fatd->bd->sectorSize) {
                     bufSize = fatd->bd->sectorSize;
                 }
                 M_DEBUG("memcopy dst=%u, src=%u, size=%u  bufSize=%u \n", bufferPos, dataSkip, bufSize - dataSkip, bufSize);
                 memcpy(buffer + bufferPos, sbuf + dataSkip, bufSize - dataSkip);
                 size -= (bufSize - dataSkip);
                 bufferPos += (bufSize - dataSkip);
                 dataSkip = 0;
                 bufSize  = fatd->bd->sectorSize;
             }
             sectorSkip = 0;
         }
         clusterSkip = 0;
     }
     return bufferPos;
 }
References fat_driver::bd, buffer, fat_driver::cbuf, fat_bpb::clusterSize, fat_driver::dev, fat_cluster2sector(), fat_getClusterAtFilePos(), fat_getClusterChain(), fat_readSingleSector(), INVALIDATE_SECTORS, M_DEBUG, MAX_DIR_CLUSTER, memcpy(), NULL, fat_driver::partBpb, READ_SECTOR, READ_SECTORS_RAW, sbuf, block_device::sectorSize, fat_bpb::sectorSize, SBP2Device::sectorSize, and XPRINTF.
Referenced by fs_read().
fat_setFatDirChain()
void fat_setFatDirChain (fat_driver * fatd, fat_dir * fatDir)
Definition at line 474 of file fat_driver.c.
 {
     int i, j;
     unsigned int index, clusterChainStart, fileCluster, fileSize, blockSize;
     unsigned char nextChain;
     int chainSize;
     M_DEBUG("%s\n", __func__);
     fileCluster = fatDir->chain[0].cluster;
     if (fileCluster < 2) {
         M_DEBUG("early exit...\n");
         return;
     }
     fileSize  = fatDir->size;
     blockSize = fileSize / DIR_CHAIN_SIZE;
     nextChain         = 1;
     clusterChainStart = 0;
     j                 = 1;
     fileSize          = 0;
     index             = 0;
     while (nextChain) {
         if ((chainSize = fat_getClusterChain(fatd, fileCluster, fatd->cbuf, MAX_DIR_CLUSTER, 1)) >= 0) {
             if (chainSize >= MAX_DIR_CLUSTER) { //the chain is full, but more chain parts exist
                 fileCluster = fatd->cbuf[MAX_DIR_CLUSTER - 1];
             } else { //chain fits in the chain buffer completely - no next chain exist
                 nextChain = 0;
             }
         } else {
             M_DEBUG("fat_setFatDirChain(): fat_getClusterChain() failed: %d\n", chainSize);
             return;
         }
         //process the cluster chain (fatd->cbuf)
         for (i = clusterChainStart; i < chainSize; i++) {
             fileSize += (fatd->partBpb.clusterSize * fatd->partBpb.sectorSize);
             while (fileSize >= (j * blockSize) && j < DIR_CHAIN_SIZE) {
                 fatDir->chain[j].cluster = fatd->cbuf[i];
                 fatDir->chain[j].index   = index;
                 j++;
             } //ends "while"
             index++;
         } //ends "for"
         clusterChainStart = 1;
     } //ends "while"
     fatDir->lastCluster = fatd->cbuf[i - 1];
 #ifdef DEBUG_EXTREME //dlanor: I patched this because this bloat hid important stuff
     //debug
     M_DEBUG("SEEK CLUSTER CHAIN CACHE fileSize=%u blockSize=%u \n", fatDir->size, blockSize);
     for (i = 0; i < DIR_CHAIN_SIZE; i++) {
         M_DEBUG("index=%u cluster=%u offset= %u - %u start=%u \n",
             fatDir->chain[i].index, fatDir->chain[i].cluster,
             fatDir->chain[i].index * fatd->partBpb.clusterSize * fatd->partBpb.sectorSize,
             (fatDir->chain[i].index + 1) * fatd->partBpb.clusterSize * fatd->partBpb.sectorSize,
             i * blockSize);
     }
 #endif /* debug */
     M_DEBUG("read cluster chain done!\n");
 }
References fat_driver::cbuf, fat_dir::chain, fat_dir_chain_record::cluster, fat_bpb::clusterSize, DIR_CHAIN_SIZE, fat_getClusterChain(), fat_dir_chain_record::index, index(), fat_dir::lastCluster, M_DEBUG, MAX_DIR_CLUSTER, fat_driver::partBpb, fat_bpb::sectorSize, fat_dir::size, and XPRINTF.
Referenced by fat_setFatDir(), and fs_write().
strEqual()
int strEqual (const char * s1, const char * s2)
Definition at line 36 of file fat_driver.c.
 {
     char u1, u2;
     M_DEBUG("%s\n", __func__);
     for (;;) {
         u1 = *s1++;
         u2 = *s2++;
         if (u1 > 64 && u1 < 91)
             u1 += 32;
         if (u2 > 64 && u2 < 91)
             u2 += 32;
         if (u1 != u2) {
             return -1;
         }
         if (u1 == '\0') {
             return 0;
         }
     }
 }
References M_DEBUG, s1, and s2.
Referenced by fat_fillDirentryInfo(), and fat_getDirentryStartCluster().