ps2sdk: iop/usb/usbhdfsd/src/include/part_driver.h File Reference
part_driver.h File Reference
Functions
int part_connect (mass_dev *dev)
void part_disconnect (mass_dev *dev)
Function Documentation
part_connect()
int part_connect (mass_dev * dev)
Definition at line 108 of file part_driver.c.
 {
         part_table partTable;
         unsigned int count = 0, i;
         int parts;
         XPRINTF("USBHDFSD: part_connect devId %i \n", dev->devId);
         if ((parts = part_getPartitionTable(dev, &partTable)) < 0)
                 return -1;
         if (parts > 0)
         {
                 for ( i = 0; i < parts; i++)
                 {
                         if(
                                 partTable.record[ i ].sid == 6    ||
                                 partTable.record[ i ].sid == 4    ||
                                 partTable.record[ i ].sid == 1    ||  // fat 16, fat 12
                                 partTable.record[ i ].sid == 0x0B ||
                                 partTable.record[ i ].sid == 0x0C ||  // fat 32
                                 partTable.record[ i ].sid == 0x0E)    // fat 16 LBA
{
                                 XPRINTF("USBHDFSD: mount partition %d id %02x\n", i, partTable.record[i].sid);
                                 if (fat_mount(dev, partTable.record[i].start, partTable.record[i].count) >= 0)
                                         count++;
                         }
                 }
                 if (count == 0)
                 {
                         printf("USBHDFSD: error - no mountable partitions.\n");
                         return -1;
                 }
         }
         else
         {       /* No partition table detected, so try to use "floppy" option and hope for the best. */
                 printf("USBHDFSD: mount drive\n");
                 if (fat_mount(dev, 0, dev->maxLBA) < 0)
                         return -1;
         }
         return 0;
 }
References part_record::count, mass_dev::devId, fat_mount(), part_getPartitionTable(), printf(), part_table::record, part_record::sid, part_record::start, and XPRINTF.
part_disconnect()
void part_disconnect (mass_dev * dev)
Definition at line 153 of file part_driver.c.
 {
         printf("USBHDFSD: part_disconnect devId %i \n", dev->devId);
         fat_forceUnmount(dev);
 }
References mass_dev::devId, fat_forceUnmount(), and printf().