ps2sdk: iop/usb/usbhdfsd/src/part_driver.c File Reference
part_driver.c File Reference
#include <stdio.h>
#include <errno.h>
#include <usbhdfsd.h>
#include "usbhd_common.h"
#include "scache.h"
#include "part_driver.h"
#include "mass_stor.h"
#include "fat_driver.h"
#include "mass_debug.h"
Data Structures
struct part_record
struct part_table
struct part_raw_record
Macros
#define READ_SECTOR(d, a, b) scache_readSector((d)->cache, (a), (void **)&b)
Functions
static USBHD_INLINE int part_getPartitionRecord (mass_dev *dev, part_raw_record *raw, part_record *rec)
static int part_getPartitionTable (mass_dev *dev, part_table *part)
int part_connect (mass_dev *dev)
void part_disconnect (mass_dev *dev)
Macro Definition Documentation
READ_SECTOR
#define READ_SECTOR (d, a, b) scache_readSector((d)->cache, (a), (void **)&b)
Definition at line 18 of file part_driver.c.
Function Documentation
part_connect()
int part_connect (mass_dev * dev)
Definition at line 108 of file part_driver.c.
 {
         part_table partTable;
         unsigned int count = 0, i;
         int parts;
         XPRINTF("USBHDFSD: part_connect devId %i \n", dev->devId);
         if ((parts = part_getPartitionTable(dev, &partTable)) < 0)
                 return -1;
         if (parts > 0)
         {
                 for ( i = 0; i < parts; i++)
                 {
                         if(
                                 partTable.record[ i ].sid == 6    ||
                                 partTable.record[ i ].sid == 4    ||
                                 partTable.record[ i ].sid == 1    ||  // fat 16, fat 12
                                 partTable.record[ i ].sid == 0x0B ||
                                 partTable.record[ i ].sid == 0x0C ||  // fat 32
                                 partTable.record[ i ].sid == 0x0E)    // fat 16 LBA
{
                                 XPRINTF("USBHDFSD: mount partition %d id %02x\n", i, partTable.record[i].sid);
                                 if (fat_mount(dev, partTable.record[i].start, partTable.record[i].count) >= 0)
                                         count++;
                         }
                 }
                 if (count == 0)
                 {
                         printf("USBHDFSD: error - no mountable partitions.\n");
                         return -1;
                 }
         }
         else
         {       /* No partition table detected, so try to use "floppy" option and hope for the best. */
                 printf("USBHDFSD: mount drive\n");
                 if (fat_mount(dev, 0, dev->maxLBA) < 0)
                         return -1;
         }
         return 0;
 }
References part_record::count, mass_dev::devId, fat_mount(), part_getPartitionTable(), printf(), part_table::record, part_record::sid, part_record::start, and XPRINTF.
part_disconnect()
void part_disconnect (mass_dev * dev)
Definition at line 153 of file part_driver.c.
 {
         printf("USBHDFSD: part_disconnect devId %i \n", dev->devId);
         fat_forceUnmount(dev);
 }
References mass_dev::devId, fat_forceUnmount(), and printf().
part_getPartitionRecord()
static USBHD_INLINE int part_getPartitionRecord (mass_dev * dev, part_raw_record * raw, part_record * rec) static
Definition at line 44 of file part_driver.c.
 {
         rec->sid = raw->sid;
         rec->start = getI32(raw->startLBA);
         rec->count = getI32(raw->size);
         //Ignore partitions that have a partition type/system ID set to 0.
         if(rec->sid != 0x00)
         {       /*      Windows appears to check if the start LBA is not 0 and whether the start LBA is within the disk.
                         There may be checks against the size, but I didn't manage to identify a pattern.
                         If the disk has no partition table (i.e. disks with "removable" media), then this check is also one safeguard. */
                 if((rec->start == 0) || (rec->start >= dev->maxLBA))
                         return -1;
                 return 0;
         }
         return 1;
 }
References part_record::count, getI32, part_record::sid, part_raw_record::sid, part_raw_record::size, part_record::start, and part_raw_record::startLBA.
Referenced by part_getPartitionTable().
part_getPartitionTable()
static int part_getPartitionTable (mass_dev * dev, part_table * part) static
Definition at line 65 of file part_driver.c.
 {
         part_raw_record* part_raw;
         int ret, partitions;
         unsigned int i;
         unsigned char* sbuf;
         ret = READ_SECTOR(dev, 0, sbuf);  // read sector 0 - Disk MBR or boot sector
         if ( ret < 0 )
         {
                 XPRINTF("USBHDFSD: part_getPartitionTable read failed %d!\n", ret);
                 return -EIO;
         }
         /* A VBR (i.e. diskette-like) also shares this signature, in the same place.
            Hence passing this check only indicates the presence of a VBR/MBR, but does not indicate which it is. */
         printf("USBHDFSD: boot signature %X %X\n", sbuf[0x1FE], sbuf[0x1FF]);
         if (sbuf[0x1FE] == 0x55 && sbuf[0x1FF] == 0xAA)
         {
                 for ( partitions = 0, i = 0; i < 4; i++)
                 {
                         part_raw = ( part_raw_record* )(  sbuf + 0x01BE + ( i * 16 )  );
                         ret = part_getPartitionRecord(dev, part_raw, &part->record[i]);
                         if(ret < 0)
                                 return 0;       //Invalid record encountered, so the table is probably invalid.
                         else if (ret == 0)      //Count the number of valid entries.
                                 partitions++;
                 }
                 //Check the number of partitions validated. Having all entries set to 0, could mean it is not a MBR.
                 return(partitions == 0 ? 0 : 4);
         }
         else
         {
                 for ( i = 0; i < 4; i++)
                 {
                         part->record[i].sid = 0;
                 }
                 return 0;
         }
 }
References EIO, part_getPartitionRecord(), printf(), READ_SECTOR, part_table::record, sbuf, part_record::sid, and XPRINTF.