ps2sdk: iop/usb/usbhdfsd/src/fs_driver.c File Reference
fs_driver.c File Reference
#include <stdio.h>
#include <errno.h>
#include <iomanX.h>
#include <sysclib.h>
#include <thsemap.h>
#include <thbase.h>
#include <sysmem.h>
#include <usbhdfsd.h>
#include "usbhd_common.h"
#include "fat_driver.h"
#include "fat_write.h"
#include "fat.h"
#include "mass_stor.h"
#include "mass_debug.h"
Data Structures
struct fs_dirent
struct fs_rec
struct fs_dir
Macros
#define FLUSH_SECTORS fat_flushSectors
#define MAX_FILES 16
Enumerations
enum FS_FILE_FLAG {
FS_FILE_FLAG_FOLDER = 0 ,
FS_FILE_FLAG_FILE ,
FS_FILE_FLAG_FOLDER = 0 ,
FS_FILE_FLAG_FILE ,
FS_FILE_FLAG_FOLDER = 0 ,
FS_FILE_FLAG_FILE
}
Functions
static void fillStat (iox_stat_t *stat, const fat_dir *fatdir)
static fs_rec * fs_findFreeFileSlot (void)
static fs_rec * fs_findFileSlotByCluster (unsigned int startCluster)
static int _fs_init_lock (void)
static void _fs_lock (void)
static void _fs_unlock (void)
static void fs_reset (void)
static int fs_dummy (void)
static int fs_init (iop_device_t *driver)
static int fs_open (iop_file_t *fd, const char *name, int flags, int mode)
static int fs_close (iop_file_t *fd)
static int fs_lseek (iop_file_t *fd, int offset, int whence)
static int fs_write (iop_file_t *fd, void *buffer, int size)
static int fs_read (iop_file_t *fd, void *buffer, int size)
static int fs_remove (iop_file_t *fd, const char *name)
static int fs_mkdir (iop_file_t *fd, const char *name, int mode)
static int fs_rmdir (iop_file_t *fd, const char *name)
static int fs_dopen (iop_file_t *fd, const char *name)
static int fs_dclose (iop_file_t *fd)
static int fs_dread (iop_file_t *fd, iox_dirent_t *buffer)
static int fs_getstat (iop_file_t *fd, const char *name, iox_stat_t *stat)
int fs_ioctl (iop_file_t *fd, int cmd, void *data)
int fs_rename (iop_file_t *fd, const char *path, const char *newpath)
static int fs_devctl (iop_file_t *fd, const char *name, int cmd, void *arg, unsigned int arglen, void *buf, unsigned int buflen)
int InitFS (void)
Variables
static fs_rec fsRec [MAX_FILES]
static int _lock_sema_id = -1
static int fs_inited = 0
static iop_device_ops_t fs_functarray
static iop_device_t fs_driver
Macro Definition Documentation
FLUSH_SECTORS
#define FLUSH_SECTORS fat_flushSectors
Definition at line 43 of file fs_driver.c.
MAX_FILES
#define MAX_FILES 16
Definition at line 75 of file fs_driver.c.
Enumeration Type Documentation
FS_FILE_FLAG
enum FS_FILE_FLAG
Enumerator
FS_FILE_FLAG_FOLDER
FS_FILE_FLAG_FILE
FS_FILE_FLAG_FOLDER
FS_FILE_FLAG_FILE
FS_FILE_FLAG_FOLDER
FS_FILE_FLAG_FILE
Definition at line 45 of file fs_driver.c.
                  {
         FS_FILE_FLAG_FOLDER     = 0,
         FS_FILE_FLAG_FILE
 };
Function Documentation
_fs_init_lock()
static int _fs_init_lock (void) static
Definition at line 153 of file fs_driver.c.
 {
 #ifndef WIN32
         iop_sema_t sp;
         sp.initial = 1;
         sp.max = 1;
         sp.option = 0;
         sp.attr = 0;
         if((_lock_sema_id = CreateSema(&sp)) < 0) { return(-1); }
 #endif
         return(0);
 }
References _lock_sema_id, CreateSema(), and sp.
Referenced by fs_reset().
_fs_lock()
static void _fs_lock (void) static
Definition at line 169 of file fs_driver.c.
 {
 #ifndef WIN32
         WaitSema(_lock_sema_id);
 #endif
 }
References _lock_sema_id, and WaitSema().
Referenced by fs_close(), fs_dclose(), fs_devctl(), fs_dopen(), fs_dread(), fs_getstat(), fs_ioctl(), fs_lseek(), fs_mkdir(), fs_open(), fs_read(), fs_remove(), fs_rename(), fs_rmdir(), and fs_write().
_fs_unlock()
static void _fs_unlock (void) static
Definition at line 177 of file fs_driver.c.
 {
 #ifndef WIN32
         SignalSema(_lock_sema_id);
 #endif
 }
References _lock_sema_id, and SignalSema().
Referenced by fs_close(), fs_dclose(), fs_devctl(), fs_dopen(), fs_dread(), fs_getstat(), fs_ioctl(), fs_lseek(), fs_mkdir(), fs_open(), fs_read(), fs_remove(), fs_rename(), fs_rmdir(), and fs_write().
fillStat()
static void fillStat (iox_stat_t * stat, const fat_dir * fatdir) static
Definition at line 78 of file fs_driver.c.
 {
         stat->mode = FIO_S_IROTH | FIO_S_IXOTH;
         if (fatdir->attr & FAT_ATTR_DIRECTORY) {
                 stat->mode |= FIO_S_IFDIR;
         } else {
                 stat->mode |= FIO_S_IFREG;
         }
         if (!(fatdir->attr & FAT_ATTR_READONLY)) {
                 stat->mode |= FIO_S_IWOTH;
         }
         stat->size = fatdir->size;
         //set created Date: Day, Month, Year
         stat->ctime[4] = fatdir->cdate[0];
         stat->ctime[5] = fatdir->cdate[1];
         stat->ctime[6] = fatdir->cdate[2];
         stat->ctime[7] = fatdir->cdate[3];
         //set created Time: Hours, Minutes, Seconds
         stat->ctime[3] = fatdir->ctime[0];
         stat->ctime[2] = fatdir->ctime[1];
         stat->ctime[1] = fatdir->ctime[2];
         //set accessed Date: Day, Month, Year
         stat->atime[4] = fatdir->adate[0];
         stat->atime[5] = fatdir->adate[1];
         stat->atime[6] = fatdir->adate[2];
         stat->atime[7] = fatdir->adate[3];
         //set modified Date: Day, Month, Year
         stat->mtime[4] = fatdir->mdate[0];
         stat->mtime[5] = fatdir->mdate[1];
         stat->mtime[6] = fatdir->mdate[2];
         stat->mtime[7] = fatdir->mdate[3];
         //set modified Time: Hours, Minutes, Seconds
         stat->mtime[3] = fatdir->mtime[0];
         stat->mtime[2] = fatdir->mtime[1];
         stat->mtime[1] = fatdir->mtime[2];
 }
References fat_dir::adate, iox_stat_t::atime, fat_dir::attr, fat_dir::cdate, fat_dir::ctime, iox_stat_t::ctime, FAT_ATTR_DIRECTORY, FAT_ATTR_READONLY, fs_dirent::fatdir, FIO_S_IFDIR, FIO_S_IFREG, FIO_S_IROTH, FIO_S_IWOTH, FIO_S_IXOTH, fat_dir::mdate, iox_stat_t::mode, fat_dir::mtime, iox_stat_t::mtime, iox_stat_t::size, and fat_dir::size.
Referenced by fs_dread(), and fs_getstat().
fs_close()
static int fs_close (iop_file_t * fd) static
Definition at line 317 of file fs_driver.c.
{
         fat_driver* fatd;
         fs_rec* rec = (fs_rec*)fd->privdata;
         if (rec == NULL)
                 return -EBADF;
         _fs_lock();
         if (rec->dirent.file_flag != FS_FILE_FLAG_FILE) {
                 _fs_unlock();
                 return -EISDIR;
         }
         rec->dirent.file_flag = -1;
         fd->privdata = NULL;
         fatd = fat_getData(fd->unit);
         if (fatd == NULL) { _fs_unlock(); return -ENODEV; }
         if ((rec->mode & O_WRONLY)) {
                 //update direntry size and time
                 if (rec->sizeChange) {
                         fat_updateSfn(fatd, rec->dirent.fatdir.size, rec->sfnSector, rec->sfnOffset);
                 }
                 FLUSH_SECTORS(fatd);
         }
         _fs_unlock();
         return 0;
 }
References _fs_lock(), _fs_unlock(), fs_rec::dirent, EBADF, EISDIR, ENODEV, fat_getData(), fat_updateSfn(), fs_dirent::fatdir, fs_dirent::file_flag, FLUSH_SECTORS, FS_FILE_FLAG_FILE, fs_rec::mode, NULL, O_WRONLY, iop_file_t::privdata, fs_rec::sfnOffset, fs_rec::sfnSector, fat_dir::size, fs_rec::sizeChange, and iop_file_t::unit.
fs_dclose()
static int fs_dclose (iop_file_t * fd) static
Definition at line 603 of file fs_driver.c.
 {
         fs_dir *rec = (fs_dir*)fd->privdata;
         if (fd->privdata == NULL)
                 return -EBADF;
         _fs_lock();
         XPRINTF("USBHDFSD: fs_dclose called: unit %d\n", fd->unit);
         if (rec->dirent.file_flag != FS_FILE_FLAG_FOLDER) {
                 _fs_unlock();
                 return -ENOTDIR;
         }
         free(fd->privdata);
         fd->privdata = NULL;
         _fs_unlock();
         return 0;
 }
References _fs_lock(), _fs_unlock(), fs_dir::dirent, EBADF, ENOTDIR, fs_dirent::file_flag, free, FS_FILE_FLAG_FOLDER, NULL, iop_file_t::privdata, iop_file_t::unit, and XPRINTF.
fs_devctl()
static int fs_devctl (iop_file_t * fd, const char * name, int cmd, void * arg, unsigned int arglen, void * buf, unsigned int buflen) static
Definition at line 771 of file fs_driver.c.
 {
         fat_driver *fatd;
         int ret;
         _fs_lock();
         switch(cmd)
         {
                 case USBMASS_DEVCTL_STOP_UNIT:
                         fatd = fat_getData(fd->unit);
                         ret = (fatd != NULL) ? mass_stor_stop_unit(fatd->dev) : -ENODEV;
                         break;
                 case USBMASS_DEVCTL_STOP_ALL:
                         mass_store_stop_all();
                         ret = 0;
                         break;
                 default:
                         ret = -ENXIO;
         }
         _fs_unlock();
         return ret;
 }
References _fs_lock(), _fs_unlock(), fat_driver::dev, ENODEV, ENXIO, fat_getData(), mass_stor_stop_unit(), mass_store_stop_all(), NULL, iop_file_t::unit, USBMASS_DEVCTL_STOP_ALL, and USBMASS_DEVCTL_STOP_UNIT.
fs_dopen()
static int fs_dopen (iop_file_t * fd, const char * name) static
Definition at line 565 of file fs_driver.c.
 {
         fat_driver* fatd;
         int is_root = 0;
         fs_dir* rec;
         _fs_lock();
         XPRINTF("USBHDFSD: fs_dopen called: unit %d name %s\n", fd->unit, name);
         fatd = fat_getData(fd->unit);
         if (fatd == NULL) { _fs_unlock(); return -ENODEV; }
         if( ((name[0] == '/') && (name[1] == '\0'))
                 ||((name[0] == '/') && (name[1] == '.') && (name[2] == '\0')))
         {
                 name = "/";
                 is_root = 1;
         }
         fd->privdata = malloc(sizeof(fs_dir));
         memset(fd->privdata, 0, sizeof(fs_dir)); //NB: also implies "file_flag = FS_FILE_FLAG_FOLDER;"
         rec = (fs_dir *) fd->privdata;
         rec->status = fat_getFirstDirentry(fatd, name, &rec->fatdlist, &rec->dirent.fatdir, &rec->current_fatdir);
         // root directory may have no entries, nothing else may.
         if(rec->status == 0 && !is_root)
                 rec->status = -EFAULT;
         if (rec->status < 0)
                 free(fd->privdata);
         _fs_unlock();
         return rec->status;
 }
References _fs_lock(), _fs_unlock(), fs_dir::current_fatdir, fs_dir::dirent, EFAULT, ENODEV, fat_getData(), fat_getFirstDirentry(), fs_dirent::fatdir, fs_dir::fatdlist, free, malloc, memset(), NULL, iop_file_t::privdata, fs_dir::status, iop_file_t::unit, and XPRINTF.
fs_dread()
static int fs_dread (iop_file_t * fd, iox_dirent_t * buffer) static
Definition at line 624 of file fs_driver.c.
 {
         fat_driver* fatd;
         int ret;
         fs_dir* rec = (fs_dir *) fd->privdata;
         if (rec == NULL)
                 return -EBADF;
         _fs_lock();
         XPRINTF("USBHDFSD: fs_dread called: unit %d\n", fd->unit);
         fatd = fat_getData(fd->unit);
         if (fatd == NULL) { _fs_unlock(); return -ENODEV; }
         if (rec->dirent.file_flag != FS_FILE_FLAG_FOLDER) {
                 _fs_unlock();
                 return -ENOTDIR;
         }
         while (rec->status > 0
                 && (rec->current_fatdir.attr & FAT_ATTR_VOLUME_LABEL
                 || ((rec->current_fatdir.attr & (FAT_ATTR_HIDDEN | FAT_ATTR_SYSTEM)) == (FAT_ATTR_HIDDEN | FAT_ATTR_SYSTEM))))
                         rec->status = fat_getNextDirentry(fatd, &rec->fatdlist, &rec->current_fatdir);
         ret = rec->status;
         if (rec->status >= 0)
         {
                 memset(buffer, 0, sizeof(iox_dirent_t));
                 fillStat(&buffer->stat, &rec->current_fatdir);
                 strcpy(buffer->name, (const char*)rec->current_fatdir.name);
         }
         if (rec->status > 0)
                 rec->status = fat_getNextDirentry(fatd, &rec->fatdlist, &rec->current_fatdir);
         _fs_unlock();
         return ret;
 }
References _fs_lock(), _fs_unlock(), fat_dir::attr, buffer, fs_dir::current_fatdir, fs_dir::dirent, EBADF, ENODEV, ENOTDIR, FAT_ATTR_HIDDEN, FAT_ATTR_SYSTEM, FAT_ATTR_VOLUME_LABEL, fat_getData(), fat_getNextDirentry(), fs_dir::fatdlist, fs_dirent::file_flag, fillStat(), FS_FILE_FLAG_FOLDER, memset(), fat_dir::name, NULL, iop_file_t::privdata, fs_dir::status, strcpy(), iop_file_t::unit, and XPRINTF.
fs_dummy()
static int fs_dummy (void) static
Definition at line 199 of file fs_driver.c.
 {
         return -5;
 }
Referenced by fs_ioctl().
fs_findFileSlotByCluster()
static fs_rec* fs_findFileSlotByCluster (unsigned int startCluster) static
Definition at line 138 of file fs_driver.c.
{
         int i;
         for (i = 0; i < MAX_FILES; i++) {
                 if (fsRec[i].dirent.file_flag >= 0 && fsRec[i].dirent.fatdir.startCluster == startCluster) {
                         return &fsRec[i];
                 }
         }
         return NULL;
 }
References fs_rec::dirent, fs_dirent::fatdir, fsRec, MAX_FILES, NULL, and fat_dir::startCluster.
Referenced by fs_open(), fs_remove(), and fs_rename().
fs_findFreeFileSlot()
static fs_rec* fs_findFreeFileSlot (void) static
Definition at line 126 of file fs_driver.c.
{
         int i;
         for (i = 0; i < MAX_FILES; i++) {
                 if (fsRec[i].dirent.file_flag < 0) {
                         return &fsRec[i];
                         break;
                 }
         }
         return NULL;
 }
References fsRec, MAX_FILES, and NULL.
Referenced by fs_open().
fs_getstat()
static int fs_getstat (iop_file_t * fd, const char * name, iox_stat_t * stat) static
Definition at line 666 of file fs_driver.c.
 {
         fat_driver* fatd;
         int ret;
         unsigned int cluster = 0;
         fat_dir fatdir;
         _fs_lock();
         XPRINTF("USBHDFSD: fs_getstat called: unit %d name %s\n", fd->unit, name);
         fatd = fat_getData(fd->unit);
         if (fatd == NULL) { _fs_unlock(); return -ENODEV; }
         XPRINTF("USBHDFSD: Calling fat_getFileStartCluster from fs_getstat\n");
         ret = fat_getFileStartCluster(fatd, name, &cluster, &fatdir);
         if (ret < 0) {
                 _fs_unlock();
                 return ret;
         }
         memset(stat, 0, sizeof(iox_stat_t));
         fillStat(stat, &fatdir);
         _fs_unlock();
         return 0;
 }
References _fs_lock(), _fs_unlock(), ENODEV, fat_getData(), fat_getFileStartCluster(), fs_dirent::fatdir, fillStat(), memset(), NULL, iop_file_t::unit, and XPRINTF.
fs_init()
static int fs_init (iop_device_t * driver) static
Definition at line 205 of file fs_driver.c.
 {
         if(!fs_inited) {
                 fs_reset();
                 fs_inited = 1;
         }
         return 1;
 }
References fs_inited, and fs_reset().
fs_ioctl()
int fs_ioctl (iop_file_t * fd, int cmd, void * data)
Definition at line 695 of file fs_driver.c.
 {
         fat_driver* fatd;
         struct fs_dirent* dirent = (struct fs_dirent *) fd->privdata;   //Remember to re-cast this to the right structure (either fs_rec or fs_dir)!
         int ret;
         if (dirent == NULL)
                 return -EBADF;
         _fs_lock();
         fatd = fat_getData(fd->unit);
         if (fatd == NULL) { _fs_unlock(); return -ENODEV; }
         switch (cmd) {
                 case USBMASS_IOCTL_RENAME:
                         ret = fat_renameFile(fatd, &dirent->fatdir, data);      //No need to re-cast since this inner structure is a common one.
                         FLUSH_SECTORS(fatd);
                         break;
                 case USBMASS_IOCTL_GET_CLUSTER:
                         ret = ((fs_rec *)fd->privdata)->dirent.fatdir.startCluster;
                         break;
                 case USBMASS_IOCTL_GET_LBA:
                         ret = fat_cluster2sector(&fatd->partBpb, ((fs_rec *)fd->privdata)->dirent.fatdir.startCluster);
                         break;
                 default:
                         ret = fs_dummy();
         }
         _fs_unlock();
         return ret;
 }
References _fs_lock(), _fs_unlock(), EBADF, ENODEV, fat_cluster2sector(), fat_getData(), fat_renameFile(), fs_dirent::fatdir, FLUSH_SECTORS, fs_dummy(), NULL, fat_driver::partBpb, iop_file_t::privdata, iop_file_t::unit, USBMASS_IOCTL_GET_CLUSTER, USBMASS_IOCTL_GET_LBA, and USBMASS_IOCTL_RENAME.
fs_lseek()
static int fs_lseek (iop_file_t * fd, int offset, int whence) static
Definition at line 351 of file fs_driver.c.
{
         fat_driver* fatd;
         fs_rec* rec = (fs_rec*)fd->privdata;
         if (rec == NULL)
                 return -EBADF;
         _fs_lock();
         fatd = fat_getData(fd->unit);
         if (fatd == NULL) { _fs_unlock(); return -ENODEV; }
         if (rec->dirent.file_flag != FS_FILE_FLAG_FILE) {
                 _fs_unlock();
                 return -EISDIR;
         }
         switch(whence) {
                 case SEEK_SET:
                         rec->filePos = offset;
                         break;
                 case SEEK_CUR:
                         rec->filePos += offset;
                         break;
                 case SEEK_END:
                         rec->filePos = rec->dirent.fatdir.size + offset;
                         break;
                 default:
                         _fs_unlock();
                         return -1;
         }
         if (rec->filePos < 0) {
                 rec->filePos = 0;
         }
         if (rec->filePos > rec->dirent.fatdir.size) {
                 rec->filePos = rec->dirent.fatdir.size;
         }
         _fs_unlock();
         return rec->filePos;
 }
References _fs_lock(), _fs_unlock(), fs_rec::dirent, EBADF, EISDIR, ENODEV, fat_getData(), fs_dirent::fatdir, fs_dirent::file_flag, fs_rec::filePos, FS_FILE_FLAG_FILE, NULL, iop_file_t::privdata, SEEK_CUR, SEEK_END, SEEK_SET, fat_dir::size, and iop_file_t::unit.
fs_mkdir()
static int fs_mkdir (iop_file_t * fd, const char * name, int mode) static
Definition at line 523 of file fs_driver.c.
{
         fat_driver* fatd;
         int ret;
         int sfnOffset;
         unsigned int sfnSector;
         unsigned int cluster;
         _fs_lock();
         fatd = fat_getData(fd->unit);
         if (fatd == NULL) { _fs_unlock(); return -ENODEV; }
         XPRINTF("USBHDFSD: fs_mkdir: name=%s \n",name);
         ret = fat_createFile(fatd, name, 1, 0, &cluster,  &sfnSector, &sfnOffset);
         //directory of the same name already exist
         if (ret == 2) {
                 ret = -EEXIST;
         }
         FLUSH_SECTORS(fatd);
         _fs_unlock();
         return ret;
 }
References _fs_lock(), _fs_unlock(), EEXIST, ENODEV, fat_createFile(), fat_getData(), FLUSH_SECTORS, NULL, iop_file_t::unit, and XPRINTF.
fs_open()
static int fs_open (iop_file_t * fd, const char * name, int flags, int mode) static
Definition at line 216 of file fs_driver.c.
{
         fat_driver* fatd;
         fs_rec* rec, *rec2;
         int ret;
         unsigned int cluster;
         char escapeNotExist;
         _fs_lock();
         XPRINTF("USBHDFSD: fs_open called: %s flags=%X mode=%X \n", name, flags, mode) ;
         fatd = fat_getData(fd->unit);
         if (fatd == NULL) { _fs_unlock(); return -ENODEV; }
         //check if the slot is free
         rec = fs_findFreeFileSlot();
         if (rec == NULL) { _fs_unlock(); return -EMFILE; }
         //find the file
         cluster = 0; //allways start from root
         XPRINTF("USBHDFSD: Calling fat_getFileStartCluster from fs_open\n");
         ret = fat_getFileStartCluster(fatd, name, &cluster, &rec->dirent.fatdir);
         if (ret < 0 && ret != -ENOENT) {
                 _fs_unlock();
                 return ret;
         }else{
                 //File exists. Check if the file is already open
                 rec2 = fs_findFileSlotByCluster(rec->dirent.fatdir.startCluster);
                 if (rec2 != NULL) {
                         if ((flags & O_WRONLY) || //current file is opened for write
                                 (rec2->mode & O_WRONLY) ) {//other file is opened for write
                                 _fs_unlock();
                                 return -EACCES;
                         }
                 }
         }
         if(flags & O_WRONLY)  { //dlanor: corrected bad test condition
                 cluster = 0; //start from root
                 escapeNotExist = 1;
                 if (flags & O_CREAT) {
                         XPRINTF("USBHDFSD: FAT I: O_CREAT detected!\n");
                         escapeNotExist = 0;
                 }
                 rec->sfnSector = 0;
                 rec->sfnOffset = 0;
                 ret = fat_createFile(fatd, name, 0, escapeNotExist, &cluster, &rec->sfnSector, &rec->sfnOffset);
                 if (ret < 0) {
                         FLUSH_SECTORS(fatd);
                         _fs_unlock();
                         return ret;
                 }
                 //the file already exist but flags is set to truncate
                 if (ret == EEXIST && (flags & O_TRUNC)) {
                         XPRINTF("USBHDFSD: FAT I: O_TRUNC detected!\n");
                         ret = fat_truncateFile(fatd, cluster, rec->sfnSector, rec->sfnOffset);
                         if (ret < 0) {
                                 FLUSH_SECTORS(fatd);
                                 XPRINTF("USBHDFSD: FAT E: failed to truncate!\n");
                                 _fs_unlock();
                                 return ret;
                         }
                 }
                 //find the file
                 cluster = 0; //allways start from root
                 XPRINTF("USBHDFSD: Calling fat_getFileStartCluster from fs_open after file creation\n");
                 ret = fat_getFileStartCluster(fatd, name, &cluster, &rec->dirent.fatdir);
         }
         if (ret < 0) {  //At this point, the file should be locatable without any errors.
                 _fs_unlock();
                 return ret;
         }
         if ((rec->dirent.fatdir.attr & FAT_ATTR_DIRECTORY) == FAT_ATTR_DIRECTORY) {
                 // Can't open a directory with open
                 _fs_unlock();
                 return -EISDIR;
         }
         rec->dirent.file_flag = FS_FILE_FLAG_FILE;
         rec->mode = flags;
         rec->filePos = 0;
         rec->sizeChange  = 0;
         if ((flags & O_APPEND) && (flags & O_WRONLY)) {
                 XPRINTF("USBHDFSD: FAT I: O_APPEND detected!\n");
                 rec->filePos = rec->dirent.fatdir.size;
         }
         //store the slot to user parameters
         fd->privdata = rec;
         _fs_unlock();
         return 1;
 }
References _fs_lock(), _fs_unlock(), fat_dir::attr, fs_rec::dirent, EACCES, EEXIST, EISDIR, EMFILE, ENODEV, ENOENT, FAT_ATTR_DIRECTORY, fat_createFile(), fat_getData(), fat_getFileStartCluster(), fat_truncateFile(), fs_dirent::fatdir, fs_dirent::file_flag, fs_rec::filePos, FLUSH_SECTORS, FS_FILE_FLAG_FILE, fs_findFileSlotByCluster(), fs_findFreeFileSlot(), fs_rec::mode, NULL, O_APPEND, O_CREAT, O_TRUNC, O_WRONLY, iop_file_t::privdata, fs_rec::sfnOffset, fs_rec::sfnSector, fat_dir::size, fs_rec::sizeChange, fat_dir::startCluster, iop_file_t::unit, and XPRINTF.
fs_read()
static int fs_read (iop_file_t * fd, void * buffer, int size) static
Definition at line 439 of file fs_driver.c.
{
         fat_driver* fatd;
         fs_rec* rec = (fs_rec*)fd->privdata;
         int result;
         if (rec == NULL)
                 return -EBADF;
         _fs_lock();
         fatd = fat_getData(fd->unit);
         if (fatd == NULL) { _fs_unlock(); return -ENODEV; }
         if (rec->dirent.file_flag != FS_FILE_FLAG_FILE) {
                 _fs_unlock();
                 return -EISDIR;
         }
         if (!(rec->mode & O_RDONLY)) {
                 _fs_unlock();
                 return -EACCES;
         }
         if (size<=0) {
                 _fs_unlock();
                 return 0;
         }
         if ((rec->filePos+size) > rec->dirent.fatdir.size) {
                 size = rec->dirent.fatdir.size - rec->filePos;
         }
         result = fat_readFile(fatd, &rec->dirent.fatdir, rec->filePos, (unsigned char*) buffer, size);
         if (result > 0) { //read succesful
                 rec->filePos += result;
         }
         _fs_unlock();
         return result;
 }
References _fs_lock(), _fs_unlock(), buffer, fs_rec::dirent, EACCES, EBADF, EISDIR, ENODEV, fat_getData(), fat_readFile(), fs_dirent::fatdir, fs_dirent::file_flag, fs_rec::filePos, FS_FILE_FLAG_FILE, fs_rec::mode, NULL, O_RDONLY, iop_file_t::privdata, result, fat_dir::size, and iop_file_t::unit.
fs_remove()
static int fs_remove (iop_file_t * fd, const char * name) static
Definition at line 481 of file fs_driver.c.
{
         fat_driver* fatd;
         fs_rec* rec;
         int result;
         unsigned int cluster;
         fat_dir fatdir;
         _fs_lock();
         fatd = fat_getData(fd->unit);
         if (fatd == NULL)
         {
                 result = -ENODEV;
                 _fs_unlock();
                 return result;
         }
         cluster = 0; //allways start from root
         XPRINTF("USBHDFSD: Calling fat_getFileStartCluster from fs_remove\n");
         result = fat_getFileStartCluster(fatd, name, &cluster, &fatdir);
         if (result < 0) {
                 _fs_unlock();
                 return result;
         }
         rec = fs_findFileSlotByCluster(fatdir.startCluster);
         //file is opened - can't delete the file
         if (rec != NULL) {
                 result = -EINVAL;
                 _fs_unlock();
                 return result;
         }
         result = fat_deleteFile(fatd, name, 0);
         FLUSH_SECTORS(fatd);
         _fs_unlock();
         return result;
 }
References _fs_lock(), _fs_unlock(), EINVAL, ENODEV, fat_deleteFile(), fat_getData(), fat_getFileStartCluster(), fs_dirent::fatdir, FLUSH_SECTORS, fs_findFileSlotByCluster(), NULL, result, fat_dir::startCluster, iop_file_t::unit, and XPRINTF.
fs_rename()
int fs_rename (iop_file_t * fd, const char * path, const char * newpath)
Definition at line 728 of file fs_driver.c.
 {
         fat_dir fatdir;
         fat_driver *fatd;
         fs_rec *rec = NULL;
         unsigned int cluster;
         struct fs_dirent *dirent = (struct fs_dirent *)fd->privdata;
         int ret;
         if (dirent == NULL)
                 return -EBADF;
         _fs_lock();
         fatd = fat_getData(fd->unit);
         if (fatd == NULL) {
                 _fs_unlock();
                 return -ENODEV;
         }
         //find the file
         cluster = 0; //allways start from root
         XPRINTF("USBHDFSD: Calling fat_getFileStartCluster from fs_rename\n");
         ret = fat_getFileStartCluster(fatd, path, &cluster, &fatdir);
         if (ret < 0 && ret != -ENOENT) {
                 _fs_unlock();
                 return ret;
         } else {
                 //File exists. Check if the file is already open
                 rec = fs_findFileSlotByCluster(fatdir.startCluster);
                 if (rec != NULL) {
                         _fs_unlock();
                         return -EACCES;
                 }
         }
         ret = fat_renameFile(fatd, &fatdir, newpath);
         FLUSH_SECTORS(fatd);
         _fs_unlock();
         return ret;
 }
References _fs_lock(), _fs_unlock(), EACCES, EBADF, ENODEV, ENOENT, fat_getData(), fat_getFileStartCluster(), fat_renameFile(), fs_dirent::fatdir, FLUSH_SECTORS, fs_findFileSlotByCluster(), NULL, iop_file_t::privdata, fat_dir::startCluster, iop_file_t::unit, and XPRINTF.
fs_reset()
static void fs_reset (void) static
Definition at line 185 of file fs_driver.c.
 {
         int i;
         for (i = 0; i < MAX_FILES; i++) { fsRec[i].dirent.file_flag = -1; }
 #ifndef WIN32
         if(_lock_sema_id >= 0) { DeleteSema(_lock_sema_id); }
 #endif
         _fs_init_lock();
 }
References _fs_init_lock(), _lock_sema_id, DeleteSema(), fs_rec::dirent, fs_dirent::file_flag, fsRec, and MAX_FILES.
Referenced by fs_init().
fs_rmdir()
static int fs_rmdir (iop_file_t * fd, const char * name) static
Definition at line 549 of file fs_driver.c.
{
         fat_driver* fatd;
         int ret;
         _fs_lock();
         fatd = fat_getData(fd->unit);
         if (fatd == NULL) { _fs_unlock(); return -ENODEV; }
         ret = fat_deleteFile(fatd, name, 1);
         FLUSH_SECTORS(fatd);
         _fs_unlock();
         return ret;
 }
References _fs_lock(), _fs_unlock(), ENODEV, fat_deleteFile(), fat_getData(), FLUSH_SECTORS, NULL, and iop_file_t::unit.
fs_write()
static int fs_write (iop_file_t * fd, void * buffer, int size) static
Definition at line 394 of file fs_driver.c.
 {
         fat_driver* fatd;
         fs_rec* rec = (fs_rec*)fd->privdata;
         int result;
         int updateClusterIndices = 0;
         if (rec == NULL)
                 return -EBADF;
         _fs_lock();
         fatd = fat_getData(fd->unit);
         if (fatd == NULL) { _fs_unlock(); return -ENODEV; }
         if (rec->dirent.file_flag != FS_FILE_FLAG_FILE) {
                 _fs_unlock();
                 return -EISDIR;
         }
         if (!(rec->mode & O_WRONLY)) {
                 _fs_unlock();
                 return -EACCES;
         }
         if (size <= 0) { _fs_unlock(); return 0; }
         result = fat_writeFile(fatd, &rec->dirent.fatdir, &updateClusterIndices, rec->filePos, (unsigned char*) buffer, size);
         if (result > 0) { //write succesful
                 rec->filePos += result;
                 if (rec->filePos > rec->dirent.fatdir.size) {
                         rec->dirent.fatdir.size = rec->filePos;
                         rec->sizeChange = 1;
                         //if new clusters allocated - then update file cluster indices
                         if (updateClusterIndices) {
                                 fat_setFatDirChain(fatd, &rec->dirent.fatdir);
                         }
                 }
         }
         _fs_unlock();
         return result;
 }
References _fs_lock(), _fs_unlock(), buffer, fs_rec::dirent, EACCES, EBADF, EISDIR, ENODEV, fat_getData(), fat_setFatDirChain(), fat_writeFile(), fs_dirent::fatdir, fs_dirent::file_flag, fs_rec::filePos, FS_FILE_FLAG_FILE, fs_rec::mode, NULL, O_WRONLY, iop_file_t::privdata, result, fat_dir::size, fs_rec::sizeChange, and iop_file_t::unit.
InitFS()
int InitFS (void)
Definition at line 836 of file fs_driver.c.
 {
         DelDrv("mass");
         return(AddDrv(&fs_driver) == 0 ? 0 : -1);
 }
References AddDrv(), DelDrv(), and fs_driver.
Referenced by _start().
Variable Documentation
_lock_sema_id
int _lock_sema_id = -1 static
Definition at line 150 of file fs_driver.c.
Referenced by _fs_init_lock(), _fs_lock(), _fs_unlock(), and fs_reset().
fs_driver
iop_device_t fs_driver static
Initial value:
={
        "mass",
        IOP_DT_FS | IOP_DT_FSEXT,
        2,
        "USB mass storage driver",
        &fs_functarray
}
Definition at line 827 of file fs_driver.c.
Referenced by InitFS().
fs_functarray
iop_device_ops_t fs_functarray static
Initial value:
={
        &fs_init,
        (void*)&fs_dummy,
        (void*)&fs_dummy,
        &fs_open,
        &fs_close,
        &fs_read,
        &fs_write,
        &fs_lseek,
        &fs_ioctl,
        &fs_remove,
        &fs_mkdir,
        &fs_rmdir,
        &fs_dopen,
        &fs_dclose,
        &fs_dread,
        &fs_getstat,
        (void*)&fs_dummy,
        &fs_rename,
        (void*)&fs_dummy,
        (void*)&fs_dummy,
        (void*)&fs_dummy,
        (void*)&fs_dummy,
        (void*)&fs_dummy,
        &fs_devctl,
        (void*)&fs_dummy,
        (void*)&fs_dummy,
        (void*)&fs_dummy,
}
Definition at line 798 of file fs_driver.c.
fs_inited
int fs_inited = 0 static
Definition at line 196 of file fs_driver.c.
Referenced by fs_init().
fsRec
fs_rec fsRec[MAX_FILES] static
Definition at line 76 of file fs_driver.c.
Referenced by fs_findFileSlotByCluster(), fs_findFreeFileSlot(), and fs_reset().