ps2sdk: iop/usb/usbhdfsd/src/include/usbhd_common.h File Reference
usbhd_common.h File Reference
Macros
#define USBHD_INLINE inline
#define getI32(buf) ((int)(((u8*)(buf))[0] + (((u8*)(buf))[1] <<8) + (((u8*)(buf))[2] << 16) + (((u8*)(buf))[3] << 24)))
#define getI32_2(buf1, buf2) ((int)(((u8*)(buf1))[0] + (((u8*)(buf1))[1] <<8) + (((u8*)(buf2))[0] << 16) + (((u8*)(buf2))[1] << 24)))
#define getI16(buf) ((int)(((u8*)(buf))[0] + (((u8*)(buf))[1] <<8)))
Functions
void * malloc (int size)
void free (void *ptr)
Macro Definition Documentation
getI16
#define getI16 (buf) ((int)(((u8*)(buf))[0] + (((u8*)(buf))[1] <<8)))
Definition at line 16 of file usbhd_common.h.
getI32
#define getI32 (buf) ((int)(((u8*)(buf))[0] + (((u8*)(buf))[1] <<8) + (((u8*)(buf))[2] << 16) + (((u8*)(buf))[3] << 24)))
Definition at line 14 of file usbhd_common.h.
getI32_2
#define getI32_2 (buf1, buf2) ((int)(((u8*)(buf1))[0] + (((u8*)(buf1))[1] <<8) + (((u8*)(buf2))[0] << 16) + (((u8*)(buf2))[1] << 24)))
Definition at line 15 of file usbhd_common.h.
USBHD_INLINE
#define USBHD_INLINE inline
Definition at line 8 of file usbhd_common.h.
Function Documentation
free()
void free (void * ptr)
Definition at line 63 of file main.c.
 {
     int OldState;
     CpuSuspendIntr(&OldState);
     FreeSysMemory(ptr);
     CpuResumeIntr(OldState);
 }
References __alloc_heap_head, __alloc_heap_tail, alloc_lock(), alloc_sbrk(), alloc_unlock(), buffer, CpuResumeIntr(), CpuSuspendIntr(), FreeSysMemory(), heap_mem_header_t::next, NULL, heap_mem_header_t::prev, heap_mem_header_t::ptr, and heap_mem_header_t::size.
Referenced by ieee1394_InitializeFetchAgent(), initConfigureSBP2Device(), mcman_findfree1(), and realloc().
malloc()
void* malloc (int size)
Definition at line 51 of file main.c.
 {
     void* result;
     int OldState;
     CpuSuspendIntr(&OldState);
     result = AllocSysMemory(ALLOC_FIRST, size, NULL);
     CpuResumeIntr(OldState);
     return result;
 }
References ALLOC_FIRST, AllocSysMemory(), buffer, CpuResumeIntr(), CpuSuspendIntr(), NULL, and result.
Referenced by ieee1394_InitializeFetchAgent(), init_ieee1394DiskDriver(), and initConfigureSBP2Device().