ps2sdk: iop/usb/usbhdfsd/src/usb_driver.c File Reference
usb_driver.c File Reference
#include <errno.h>
#include <sysclib.h>
#include <thsemap.h>
#include <stdio.h>
#include <usbd.h>
#include <usbd_macro.h>
#include "mass_debug.h"
#include <usbhdfsd.h>
#include "usbhd_common.h"
#include "mass_stor.h"
#include "scache.h"
#include "part_driver.h"
Data Structures
struct cbw_packet
struct csw_packet
struct inquiry_data
struct sense_data
struct read_capacity_data
struct usb_callback_data
struct usb_transfer_callback_data
Macros
#define getBI32(__buf) ((((u8 *) (__buf))[3] << 0) | (((u8 *) (__buf))[2] << 8) | (((u8 *) (__buf))[1] << 16) | (((u8 *) (__buf))[0] << 24))
#define USB_SUBCLASS_MASS_RBC 0x01
#define USB_SUBCLASS_MASS_ATAPI 0x02
#define USB_SUBCLASS_MASS_QIC 0x03
#define USB_SUBCLASS_MASS_UFI 0x04
#define USB_SUBCLASS_MASS_SFF_8070I 0x05
#define USB_SUBCLASS_MASS_SCSI 0x06
#define USB_PROTOCOL_MASS_CBI 0x00
#define USB_PROTOCOL_MASS_CBI_NO_CCI 0x01
#define USB_PROTOCOL_MASS_BULK_ONLY 0x50
#define TAG_TEST_UNIT_READY 0
#define TAG_REQUEST_SENSE 3
#define TAG_INQUIRY 18
#define TAG_READ_CAPACITY 37
#define TAG_READ 40
#define TAG_START_STOP_UNIT 33
#define TAG_WRITE 42
#define USB_BLK_EP_IN 0
#define USB_BLK_EP_OUT 1
#define USB_XFER_MAX_RETRIES 8
#define USB_IO_MAX_RETRIES 16
#define CBW_TAG 0x43425355
#define CSW_TAG 0x53425355
#define USB_BLOCK_SIZE 4096
#define NUM_DEVICES 2
Functions
static void usb_callback (int resultCode, int bytes, void *arg)
static int perform_bulk_transfer (usb_transfer_callback_data *data)
static void usb_transfer_callback (int resultCode, int bytes, void *arg)
static void mass_stor_release (mass_dev *dev)
static int usb_set_configuration (mass_dev *dev, int configNumber)
static int usb_set_interface (mass_dev *dev, int interface, int altSetting)
static int usb_bulk_clear_halt (mass_dev *dev, int endpoint)
static void usb_bulk_reset (mass_dev *dev, int mode)
static int usb_bulk_status (mass_dev *dev, csw_packet *csw, unsigned int tag)
static int usb_bulk_manage_status (mass_dev *dev, unsigned int tag)
static int usb_bulk_get_max_lun (mass_dev *dev)
static int usb_bulk_command (mass_dev *dev, cbw_packet *packet)
static int usb_bulk_transfer (mass_dev *dev, int direction, void *buffer, unsigned int transferSize)
static int cbw_scsi_test_unit_ready (mass_dev *dev)
static int cbw_scsi_request_sense (mass_dev *dev, void *buffer, int size)
static int cbw_scsi_inquiry (mass_dev *dev, void *buffer, int size)
static int cbw_scsi_start_stop_unit (mass_dev *dev, u8 param)
static int cbw_scsi_read_capacity (mass_dev *dev, void *buffer, int size)
static int cbw_scsi_read_sector (mass_dev *dev, unsigned int lba, void *buffer, unsigned short int sectorCount)
static int cbw_scsi_write_sector (mass_dev *dev, unsigned int lba, const void *buffer, unsigned short int sectorCount)
static mass_dev * mass_stor_findDevice (int devId, int create)
int mass_stor_readSector (mass_dev *dev, unsigned int sector, unsigned char *buffer, unsigned short int count)
int mass_stor_writeSector (mass_dev *dev, unsigned int sector, const unsigned char *buffer, unsigned short int count)
static void usb_bulk_probeEndpoint (int devId, mass_dev *dev, UsbEndpointDescriptor *endpoint)
int mass_stor_probe (int devId)
int mass_stor_connect (int devId)
int mass_stor_disconnect (int devId)
static int mass_stor_warmup (mass_dev *dev)
static int mass_store_configureDevice (mass_dev *dev)
int mass_stor_configureNextDevice (void)
int InitUSB (void)
int UsbMassGetDeviceInfo (int device, UsbMassDeviceInfo_t *info)
int UsbMassRegisterCallback (int device, usbmass_cb_t callback)
int mass_stor_stop_unit (mass_dev *dev)
void mass_store_stop_all (void)
Variables
static sceUsbdLddOps driver
static mass_dev g_mass_device [NUM_DEVICES]
Macro Definition Documentation
CBW_TAG
#define CBW_TAG 0x43425355
Definition at line 49 of file usb_driver.c.
CSW_TAG
#define CSW_TAG 0x53425355
Definition at line 50 of file usb_driver.c.
getBI32
#define getBI32 (__buf) ((((u8 *) (__buf))[3] << 0) | (((u8 *) (__buf))[2] << 8) | (((u8 *) (__buf))[1] << 16) | (((u8 *) (__buf))[0] << 24))
Definition at line 22 of file usb_driver.c.
NUM_DEVICES
#define NUM_DEVICES 2
Definition at line 116 of file usb_driver.c.
TAG_INQUIRY
#define TAG_INQUIRY 18
Definition at line 37 of file usb_driver.c.
TAG_READ
#define TAG_READ 40
Definition at line 39 of file usb_driver.c.
TAG_READ_CAPACITY
#define TAG_READ_CAPACITY 37
Definition at line 38 of file usb_driver.c.
TAG_REQUEST_SENSE
#define TAG_REQUEST_SENSE 3
Definition at line 36 of file usb_driver.c.
TAG_START_STOP_UNIT
#define TAG_START_STOP_UNIT 33
Definition at line 40 of file usb_driver.c.
TAG_TEST_UNIT_READY
#define TAG_TEST_UNIT_READY 0
Definition at line 35 of file usb_driver.c.
TAG_WRITE
#define TAG_WRITE 42
Definition at line 41 of file usb_driver.c.
USB_BLK_EP_IN
#define USB_BLK_EP_IN 0
Definition at line 43 of file usb_driver.c.
USB_BLK_EP_OUT
#define USB_BLK_EP_OUT 1
Definition at line 44 of file usb_driver.c.
USB_BLOCK_SIZE
#define USB_BLOCK_SIZE 4096
Definition at line 106 of file usb_driver.c.
USB_IO_MAX_RETRIES
#define USB_IO_MAX_RETRIES 16
Definition at line 47 of file usb_driver.c.
USB_PROTOCOL_MASS_BULK_ONLY
#define USB_PROTOCOL_MASS_BULK_ONLY 0x50
Definition at line 33 of file usb_driver.c.
USB_PROTOCOL_MASS_CBI
#define USB_PROTOCOL_MASS_CBI 0x00
Definition at line 31 of file usb_driver.c.
USB_PROTOCOL_MASS_CBI_NO_CCI
#define USB_PROTOCOL_MASS_CBI_NO_CCI 0x01
Definition at line 32 of file usb_driver.c.
USB_SUBCLASS_MASS_ATAPI
#define USB_SUBCLASS_MASS_ATAPI 0x02
Definition at line 25 of file usb_driver.c.
USB_SUBCLASS_MASS_QIC
#define USB_SUBCLASS_MASS_QIC 0x03
Definition at line 26 of file usb_driver.c.
USB_SUBCLASS_MASS_RBC
#define USB_SUBCLASS_MASS_RBC 0x01
Definition at line 24 of file usb_driver.c.
USB_SUBCLASS_MASS_SCSI
#define USB_SUBCLASS_MASS_SCSI 0x06
Definition at line 29 of file usb_driver.c.
USB_SUBCLASS_MASS_SFF_8070I
#define USB_SUBCLASS_MASS_SFF_8070I 0x05
Definition at line 28 of file usb_driver.c.
USB_SUBCLASS_MASS_UFI
#define USB_SUBCLASS_MASS_UFI 0x04
Definition at line 27 of file usb_driver.c.
USB_XFER_MAX_RETRIES
#define USB_XFER_MAX_RETRIES 8
Definition at line 46 of file usb_driver.c.
Function Documentation
cbw_scsi_inquiry()
static int cbw_scsi_inquiry (mass_dev * dev, void * buffer, int size) static
Definition at line 511 of file usb_driver.c.
 {
         int rcode, result, retries;
         static cbw_packet cbw={
                 CBW_TAG,                // cbw.signature
                 -TAG_INQUIRY,           // cbw.tag
                 0,                      // cbw.dataTransferLength
                 0x80,                   // cbw.flags
                 0,                      // cbw.lun
                 12,                     // cbw.comLength
                 /* scsi command packet */
                 {
                         0x12,           // inquiry operation code
                         0,              // lun/reserved
                         0,              // reserved
                         0,              // reserved
                         0,              // inquiry reply length
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                 }
         };
         XPRINTF("USBHDFSD: cbw_scsi_inquiry\n");
         cbw.dataTransferLength = size;  //INQUIRY_REPLY_LENGTH
         cbw.comData[4] = size;          //inquiry reply length
         for(retries = USB_XFER_MAX_RETRIES; retries > 0; retries--){
                 if(usb_bulk_command(dev, &cbw) == USB_RC_OK){
                         rcode = usb_bulk_transfer(dev, USB_BLK_EP_IN, buffer, size);
                         result = usb_bulk_manage_status(dev, -TAG_INQUIRY);
                         if(rcode == USB_RC_OK && result == 0) return 0;
                 }
         }
         return -EIO;
 }
References buffer, CBW_TAG, cbw_packet::comData, cbw_packet::dataTransferLength, EIO, result, TAG_INQUIRY, USB_BLK_EP_IN, usb_bulk_command(), usb_bulk_manage_status(), usb_bulk_transfer(), USB_RC_OK, USB_XFER_MAX_RETRIES, and XPRINTF.
Referenced by mass_stor_warmup().
cbw_scsi_read_capacity()
static int cbw_scsi_read_capacity (mass_dev * dev, void * buffer, int size) static
Definition at line 597 of file usb_driver.c.
 {
         int rcode, result, retries;
         static cbw_packet cbw={
                 CBW_TAG,                // cbw.signature
                 -TAG_READ_CAPACITY,     // cbw.tag
                 0,                      // cbw.dataTransferLength
                 0x80,                   // cbw.flags
                 0,                      // cbw.lun
                 12,                     // cbw.comLength
                 /* scsi command packet */
                 {
                         0x25,           // read capacity operation code
                         0,              // lun/reserved/RelAdr
                         0,              // LBA 1
                         0,              // LBA 2
                         0,              // LBA 3
                         0,              // LBA 4
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved/PMI
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                 }
         };
         cbw.dataTransferLength = size;
         XPRINTF("USBHDFSD: cbw_scsi_read_capacity\n");
         for(retries = USB_XFER_MAX_RETRIES; retries > 0; retries--){
                 if(usb_bulk_command(dev, &cbw) == USB_RC_OK){
                         rcode = usb_bulk_transfer(dev, USB_BLK_EP_IN, buffer, size);
                         result = usb_bulk_manage_status(dev, -TAG_READ_CAPACITY);
                         if(rcode == USB_RC_OK && result == 0) return 0;
                 }
         }
         return -EIO;
 }
References buffer, CBW_TAG, cbw_packet::dataTransferLength, EIO, result, TAG_READ_CAPACITY, USB_BLK_EP_IN, usb_bulk_command(), usb_bulk_manage_status(), usb_bulk_transfer(), USB_RC_OK, USB_XFER_MAX_RETRIES, and XPRINTF.
Referenced by mass_stor_warmup().
cbw_scsi_read_sector()
static int cbw_scsi_read_sector (mass_dev * dev, unsigned int lba, void * buffer, unsigned short int sectorCount) static
Definition at line 641 of file usb_driver.c.
 {
         int rcode, result;
         static cbw_packet cbw={
                 CBW_TAG,                // cbw.signature
                 -TAG_READ,              // cbw.tag
                 0,                      // cbw.dataTransferLength
                 0x80,                   // cbw.flags
                 0,                      // cbw.lun
                 12,                     // cbw.comLength
                 /* scsi command packet */
                 {
                         0x28,           // Operation code
                         0,              // LUN/DPO/FUA/Reserved/Reldr
                         0,              // lba 1 (MSB)
                         0,              // lba 2
                         0,              // lba 3
                         0,              // lba 4 (LSB)
                         0,              // reserved
                         0,              // Transfer length MSB
                         0,              // Transfer length LSB
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                 }
         };
         XPRINTF("USBHDFSD: cbw_scsi_read_sector - 0x%08x %p 0x%04x\n", lba, buffer, sectorCount);
         cbw.dataTransferLength = dev->sectorSize * sectorCount;
         //scsi command packet
         cbw.comData[2] = (lba & 0xFF000000) >> 24;      //lba 1 (MSB)
         cbw.comData[3] = (lba & 0xFF0000) >> 16;        //lba 2
         cbw.comData[4] = (lba & 0xFF00) >> 8;           //lba 3
         cbw.comData[5] = (lba & 0xFF);                  //lba 4 (LSB)
         cbw.comData[7] = (sectorCount & 0xFF00) >> 8;   //Transfer length MSB
         cbw.comData[8] = (sectorCount & 0xFF);          //Transfer length LSB
         result = -EIO;
         if(usb_bulk_command(dev, &cbw) == USB_RC_OK){
                 rcode = usb_bulk_transfer(dev, USB_BLK_EP_IN, buffer, dev->sectorSize * sectorCount);
                 result = usb_bulk_manage_status(dev, -TAG_READ);
                 if(rcode != USB_RC_OK) result = -EIO;
         }
         return result;
 }
References buffer, CBW_TAG, cbw_packet::comData, cbw_packet::dataTransferLength, EIO, result, TAG_READ, USB_BLK_EP_IN, usb_bulk_command(), usb_bulk_manage_status(), usb_bulk_transfer(), USB_RC_OK, and XPRINTF.
Referenced by mass_stor_readSector().
cbw_scsi_request_sense()
static int cbw_scsi_request_sense (mass_dev * dev, void * buffer, int size) static
Definition at line 466 of file usb_driver.c.
 {
         int rcode, result, retries;
         static cbw_packet cbw={
                 CBW_TAG,                // cbw.signature
                 -TAG_REQUEST_SENSE,     // cbw.tag
                 0,                      // cbw.dataTransferLength
                 0x80,                   // cbw.flags
                 0,                      // cbw.lun
                 12,                     // cbw.comLength
                 /* scsi command packet */
                 {
                         0x03,           // request sense operation code
                         0,              // lun/reserved
                         0,              // reserved
                         0,              // reserved
                         0,              // allocation length
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                 }
         };
         cbw.dataTransferLength = size;
         cbw.comData[4] = size;
         XPRINTF("USBHDFSD: cbw_scsi_request_sense\n");
         for(retries = USB_XFER_MAX_RETRIES; retries > 0; retries--){
                 if(usb_bulk_command(dev, &cbw) == USB_RC_OK){
                         rcode = usb_bulk_transfer(dev, USB_BLK_EP_IN, buffer, size);
                         result = usb_bulk_manage_status(dev, -TAG_REQUEST_SENSE);
                         if(rcode == USB_RC_OK && result == 0) return 0;
                 }
         }
         return -EIO;
 }
References buffer, CBW_TAG, cbw_packet::comData, cbw_packet::dataTransferLength, EIO, result, TAG_REQUEST_SENSE, USB_BLK_EP_IN, usb_bulk_command(), usb_bulk_manage_status(), usb_bulk_transfer(), USB_RC_OK, USB_XFER_MAX_RETRIES, and XPRINTF.
Referenced by mass_stor_warmup().
cbw_scsi_start_stop_unit()
static int cbw_scsi_start_stop_unit (mass_dev * dev, u8 param) static
Definition at line 556 of file usb_driver.c.
 {
         int result, retries;
         static cbw_packet cbw={
                 CBW_TAG,                // cbw.signature
                 -TAG_START_STOP_UNIT,   // cbw.tag
                 0,                      // cbw.dataTransferLength
                 0x80,                   // cbw.flags
                 0,                      // cbw.lun
                 12,                     // cbw.comLength
                 /* scsi command packet */
                 {
                         0x1B,           // start stop unit operation code
                         0,              // lun/reserved/immed
                         0,              // reserved
                         0,              // reserved
                         1,              // reserved/LoEj/Start "Start the media and acquire the format type"
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                 }
         };
         XPRINTF("USBHDFSD: cbw_scsi_start_stop_unit. param: %02x\n", param);
         cbw.comData[4] = param;
         for(result = -EIO, retries = USB_XFER_MAX_RETRIES; retries > 0; retries--){
                 if(usb_bulk_command(dev, &cbw) == USB_RC_OK){
                         if((result = usb_bulk_manage_status(dev, -TAG_START_STOP_UNIT)) == 0) break;
                 }
         }
         return result;
 }
References CBW_TAG, cbw_packet::comData, EIO, result, TAG_START_STOP_UNIT, usb_bulk_command(), usb_bulk_manage_status(), USB_RC_OK, USB_XFER_MAX_RETRIES, and XPRINTF.
Referenced by mass_stor_stop_unit(), and mass_stor_warmup().
cbw_scsi_test_unit_ready()
static int cbw_scsi_test_unit_ready (mass_dev * dev) static
Definition at line 427 of file usb_driver.c.
 {
         int result, retries;
         static cbw_packet cbw={
                 CBW_TAG,                // cbw.signature
                 -TAG_TEST_UNIT_READY,   // cbw.tag
                 0,                      // cbw.dataTransferLength
                 0x80,                   // cbw.flags
                 0,                      // cbw.lun
                 12,                     // cbw.comLength
                 /* scsi command packet */
                 {
                         0x00,           // test unit ready operation code
                         0,              // lun/reserved
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                         0,              // reserved
                 }
         };
         XPRINTF("USBHDFSD: cbw_scsi_test_unit_ready\n");
         for(result = -EIO, retries = USB_XFER_MAX_RETRIES; retries > 0; retries--){
                 if(usb_bulk_command(dev, &cbw) == USB_RC_OK){
                         if((result = usb_bulk_manage_status(dev, -TAG_TEST_UNIT_READY)) >= 0) break;
                 }
         }
         return result;
 }
References CBW_TAG, EIO, result, TAG_TEST_UNIT_READY, usb_bulk_command(), usb_bulk_manage_status(), USB_RC_OK, USB_XFER_MAX_RETRIES, and XPRINTF.
Referenced by mass_stor_warmup().
cbw_scsi_write_sector()
static int cbw_scsi_write_sector (mass_dev * dev, unsigned int lba, const void * buffer, unsigned short int sectorCount) static
Definition at line 691 of file usb_driver.c.
 {
         int rcode, result;
         static cbw_packet cbw={
                 CBW_TAG,                // cbw.signature
                 -TAG_WRITE,             // cbw.tag
                 0,                      // cbw.dataTransferLength
                 0,                      // cbw.flags
                 0,                      // cbw.lun
                 12,                     // cbw.comLength
                 /* scsi command packet */
                 {
                         0x2A,           //write operation code
                         0,              //LUN/DPO/FUA/Reserved/Reldr
                         0,              //lba 1 (MSB)
                         0,              //lba 2
                         0,              //lba 3
                         0,              //lba 4 (LSB)
                         0,              //Reserved
                         0,              //Transfer length MSB
                         0,              //Transfer length LSB
                         0,              //reserved
                         0,              //reserved
                         0,              //reserved
                 }
         };
         XPRINTF("USBHDFSD: cbw_scsi_write_sector - 0x%08x %p 0x%04x\n", lba, buffer, sectorCount);
         cbw.dataTransferLength = dev->sectorSize * sectorCount;
         //scsi command packet
         cbw.comData[2] = (lba & 0xFF000000) >> 24;      //lba 1 (MSB)
         cbw.comData[3] = (lba & 0xFF0000) >> 16;        //lba 2
         cbw.comData[4] = (lba & 0xFF00) >> 8;           //lba 3
         cbw.comData[5] = (lba & 0xFF);                  //lba 4 (LSB)
         cbw.comData[7] = (sectorCount & 0xFF00) >> 8;   //Transfer length MSB
         cbw.comData[8] = (sectorCount & 0xFF);          //Transfer length LSB
         result = -EIO;
         if(usb_bulk_command(dev, &cbw) == USB_RC_OK){
                 rcode = usb_bulk_transfer(dev, USB_BLK_EP_OUT, (void*)buffer, dev->sectorSize * sectorCount);
                 result = usb_bulk_manage_status(dev, -TAG_WRITE);
                 if(rcode != USB_RC_OK) result = -EIO;
         }
         return result;
 }
References buffer, CBW_TAG, cbw_packet::comData, cbw_packet::dataTransferLength, EIO, result, TAG_WRITE, USB_BLK_EP_OUT, usb_bulk_command(), usb_bulk_manage_status(), usb_bulk_transfer(), USB_RC_OK, and XPRINTF.
Referenced by mass_stor_writeSector().
InitUSB()
int InitUSB (void)
Definition at line 1123 of file usb_driver.c.
 {
         int i;
         int ret = 0;
         for (i = 0; i < NUM_DEVICES; ++i)
         {
                 g_mass_device[i].status = 0;
                 g_mass_device[i].devId = -1;
         }
         driver.next             = NULL;
         driver.prev             = NULL;
         driver.name             = "mass-stor";
         driver.probe            = mass_stor_probe;
         driver.connect          = mass_stor_connect;
         driver.disconnect       = mass_stor_disconnect;
         ret = sceUsbdRegisterLdd(&driver);
         XPRINTF("USBHDFSD: registerDriver=%i \n", ret);
         if (ret < 0)
         {
                 printf("USBHDFSD: register driver failed! ret=%d\n", ret);
                 return(-1);
         }
         return(0);
 }
References sceUsbdLddOps::connect, mass_dev::devId, sceUsbdLddOps::disconnect, driver, g_mass_device, mass_stor_connect(), mass_stor_disconnect(), mass_stor_probe(), sceUsbdLddOps::name, sceUsbdLddOps::next, NULL, NUM_DEVICES, sceUsbdLddOps::prev, printf(), sceUsbdLddOps::probe, sceUsbdRegisterLdd(), mass_dev::status, and XPRINTF.
Referenced by _start().
mass_stor_configureNextDevice()
int mass_stor_configureNextDevice (void)
Definition at line 1081 of file usb_driver.c.
 {
         int i;
         XPRINTF("USBHDFSD: configuring devices... \n");
         for (i = 0; i < NUM_DEVICES; ++i)
         {
                 mass_dev *dev = &g_mass_device[i];
                 if (dev->devId != -1 && (dev->status & USBMASS_DEV_STAT_CONN) && !(dev->status & USBMASS_DEV_STAT_CONF))
                 {
                         int ret;
                         ret = mass_store_configureDevice(dev);
                         if (ret != USB_RC_OK)
{
                                 mass_stor_release(dev);
                                 continue;
                         }
                         dev->status |= USBMASS_DEV_STAT_CONF;
                         ret = mass_stor_warmup(dev);
                         if (ret < 0)
{
                                 printf("USBHDFSD: Error - failed to warmup device %d\n", dev->devId);
                                 mass_stor_release(dev);
                                 continue;
                         }
                         dev->cache = scache_init(dev, dev->sectorSize); // modified by Hermes
                         if (dev->cache == NULL) {
                                 printf("USBHDFSD: Error - scache_init failed \n" );
                                 mass_stor_release(dev);
                                 continue;
                         }
                         return part_connect(dev) >= 0;
                 }
         }
         return 0;
 }
References mass_dev::devId, g_mass_device, mass_stor_release(), mass_stor_warmup(), mass_store_configureDevice(), NULL, NUM_DEVICES, part_connect(), printf(), scache_init(), mass_dev::status, USB_RC_OK, USBMASS_DEV_STAT_CONF, USBMASS_DEV_STAT_CONN, and XPRINTF.
Referenced by fat_getData().
mass_stor_connect()
int mass_stor_connect (int devId)
Definition at line 866 of file usb_driver.c.
 {
         int i;
         int epCount;
         UsbDeviceDescriptor *device;
         UsbConfigDescriptor *config;
         UsbInterfaceDescriptor *interface;
         UsbEndpointDescriptor *endpoint;
         iop_sema_t SemaData;
         mass_dev* dev;
         printf("USBHDFSD: connect: devId=%i\n", devId);
         dev = mass_stor_findDevice(devId, 1);
         if (dev == NULL) {
                 printf("USBHDFSD: Error - no free device descriptors!\n");
                 return 1;
         }
         /* Device cannot be registered twice. */
         if (dev->devId != -1) {
                 printf("USBHDFSD: Error - device descriptor in use!\n");
                 return 1;
         }
         dev->status = 0;
         dev->sectorSize = 0;
         dev->bulkEpI = -1;
         dev->bulkEpO = -1;
         /* open the config endpoint */
         dev->controlEp = sceUsbdOpenPipe(devId, NULL);
         device = (UsbDeviceDescriptor*)sceUsbdScanStaticDescriptor(devId, NULL, USB_DT_DEVICE);
         config = (UsbConfigDescriptor*)sceUsbdScanStaticDescriptor(devId, device, USB_DT_CONFIG);
         interface = (UsbInterfaceDescriptor *) ((char *) config + config->bLength); /* Get first interface */
         // store interface numbers
         dev->interfaceNumber = interface->bInterfaceNumber;
         dev->interfaceAlt    = interface->bAlternateSetting;
         epCount = interface->bNumEndpoints;
         endpoint = (UsbEndpointDescriptor*)sceUsbdScanStaticDescriptor(devId, NULL, USB_DT_ENDPOINT);
         usb_bulk_probeEndpoint(devId, dev, endpoint);
         for (i = 1; i < epCount; i++)
         {
                 endpoint = (UsbEndpointDescriptor*) ((char *) endpoint + endpoint->bLength);
                 usb_bulk_probeEndpoint(devId, dev, endpoint);
         }
         // Bail out if we do NOT have enough bulk endpoints.
         if (dev->bulkEpI < 0 || dev->bulkEpO < 0) {
                 mass_stor_release(dev);
                 printf("USBHDFSD: Error - connect failed: not enough bulk endpoints! \n");
                 return -1;
         }
         SemaData.initial = 0;
         SemaData.max = 1;
         SemaData.option = 0;
         SemaData.attr = 0;
         if((dev->ioSema = CreateSema(&SemaData)) <0){
                 mass_stor_release(dev);
                 printf("USBHDFSD: Failed to allocate I/O semaphore.\n");
                 return -1;
         }
         /*store current configuration id - can't call set_configuration here */
         dev->devId = devId;
         dev->configId = config->bConfigurationValue;
         dev->status = USBMASS_DEV_STAT_CONN;
         XPRINTF("USBHDFSD: connect ok: epI=%i, epO=%i \n", dev->bulkEpI, dev->bulkEpO);
         if(dev->callback != NULL) dev->callback(USBMASS_DEV_EV_CONN);
         return 0;
 }
References iop_sema_t::attr, UsbInterfaceDescriptor::bAlternateSetting, UsbConfigDescriptor::bConfigurationValue, UsbInterfaceDescriptor::bInterfaceNumber, UsbConfigDescriptor::bLength, UsbEndpointDescriptor::bLength, UsbInterfaceDescriptor::bNumEndpoints, mass_dev::bulkEpI, mass_dev::bulkEpO, mass_dev::configId, mass_dev::controlEp, CreateSema(), mass_dev::devId, iop_sema_t::initial, mass_dev::interfaceAlt, mass_dev::interfaceNumber, mass_dev::ioSema, mass_stor_findDevice(), mass_stor_release(), iop_sema_t::max, NULL, iop_sema_t::option, printf(), sceUsbdOpenPipe(), sceUsbdScanStaticDescriptor(), mass_dev::status, usb_bulk_probeEndpoint(), USB_DT_CONFIG, USB_DT_DEVICE, USB_DT_ENDPOINT, USBMASS_DEV_EV_CONN, USBMASS_DEV_STAT_CONN, and XPRINTF.
Referenced by InitUSB().
mass_stor_disconnect()
int mass_stor_disconnect (int devId)
Definition at line 966 of file usb_driver.c.
{
         mass_dev* dev;
         dev = mass_stor_findDevice(devId, 0);
         printf("USBHDFSD: disconnect: devId=%i\n", devId);
         if (dev == NULL)
         {
                 printf("USBHDFSD: Error - disconnect: no device storage!\n");
                 return 0;
         }
         if (dev->status & USBMASS_DEV_STAT_CONN)
         {
                 mass_stor_release(dev);
                 part_disconnect(dev);
                 scache_kill(dev->cache);
                 dev->cache = NULL;
                 dev->devId = -1;
                 DeleteSema(dev->ioSema);
                 if(dev->callback != NULL) dev->callback(USBMASS_DEV_EV_DISCONN);
         }
         return 0;
 }
References DeleteSema(), mass_dev::devId, mass_dev::ioSema, mass_stor_findDevice(), mass_stor_release(), NULL, part_disconnect(), printf(), scache_kill(), mass_dev::status, USBMASS_DEV_EV_DISCONN, and USBMASS_DEV_STAT_CONN.
Referenced by InitUSB().
mass_stor_findDevice()
static mass_dev* mass_stor_findDevice (int devId, int create) static
Definition at line 741 of file usb_driver.c.
 {
         mass_dev* dev = NULL;
         int i;
         XPRINTF("USBHDFSD: mass_stor_findDevice devId %i\n", devId);
         for (i = 0; i < NUM_DEVICES; ++i)
         {
                 if (g_mass_device[i].devId == devId)
                 {
                         XPRINTF("USBHDFSD: mass_stor_findDevice exists %i\n", i);
                         dev = &g_mass_device[i];
                         break;
                 }
                 else if (create && dev == NULL && g_mass_device[i].devId == -1)
                 {
                         dev = &g_mass_device[i];
                         break;
                 }
         }
         return dev;
 }
References g_mass_device, NULL, NUM_DEVICES, and XPRINTF.
Referenced by mass_stor_connect(), mass_stor_disconnect(), and mass_stor_probe().
mass_stor_probe()
int mass_stor_probe (int devId)
Definition at line 811 of file usb_driver.c.
 {
         UsbDeviceDescriptor *device = NULL;
         UsbConfigDescriptor *config = NULL;
         UsbInterfaceDescriptor *intf = NULL;
         XPRINTF("USBHDFSD: probe: devId=%i\n", devId);
         mass_dev* mass_device = mass_stor_findDevice(devId, 0);
         /* Check that a device descriptor was successfully allocated and the device was not already connected. */
         if ((mass_device != NULL) && (mass_device->status & USBMASS_DEV_STAT_CONN))
         {
                 printf("USBHDFSD: Error - no free device descriptors!\n");
                 return 0;
         }
         /* get device descriptor */
         device = (UsbDeviceDescriptor*)sceUsbdScanStaticDescriptor(devId, NULL, USB_DT_DEVICE);
         if (device == NULL)  {
                 printf("USBHDFSD: Error - Couldn't get device descriptor\n");
                 return 0;
         }
         /* Check if the device has at least one configuration */
         if (device->bNumConfigurations < 1) { return 0; }
         /* read configuration */
         config = (UsbConfigDescriptor*)sceUsbdScanStaticDescriptor(devId, device, USB_DT_CONFIG);
         if (config == NULL) {
             printf("USBHDFSD: Error - Couldn't get configuration descriptor\n");
             return 0;
         }
         /* check that at least one interface exists */
         XPRINTF("USBHDFSD: bNumInterfaces %d\n", config->bNumInterfaces);
         if ((config->bNumInterfaces < 1) ||
                 (config->wTotalLength < (sizeof(UsbConfigDescriptor) + sizeof(UsbInterfaceDescriptor)))) {
                         printf("USBHDFSD: Error - No interfaces available\n");
                         return 0;
         }
         /* get interface */
         intf = (UsbInterfaceDescriptor *) ((char *) config + config->bLength); /* Get first interface */
         XPRINTF("USBHDFSD: bInterfaceClass %X bInterfaceSubClass %X bInterfaceProtocol %X\n",
         intf->bInterfaceClass, intf->bInterfaceSubClass, intf->bInterfaceProtocol);
         if ((intf->bInterfaceClass              != USB_CLASS_MASS_STORAGE) ||
                 (intf->bInterfaceSubClass       != USB_SUBCLASS_MASS_SCSI  &&
                  intf->bInterfaceSubClass       != USB_SUBCLASS_MASS_SFF_8070I) ||
                 (intf->bInterfaceProtocol       != USB_PROTOCOL_MASS_BULK_ONLY) ||
                 (intf->bNumEndpoints < 2))    { //4.3: There shall be at least 2 endpoints, for bulk in and bulk out.
                         return 0;
         }
         return 1;
 }
References UsbInterfaceDescriptor::bInterfaceClass, UsbInterfaceDescriptor::bInterfaceProtocol, UsbInterfaceDescriptor::bInterfaceSubClass, UsbConfigDescriptor::bLength, UsbDeviceDescriptor::bNumConfigurations, UsbInterfaceDescriptor::bNumEndpoints, UsbConfigDescriptor::bNumInterfaces, mass_stor_findDevice(), NULL, printf(), sceUsbdScanStaticDescriptor(), mass_dev::status, USB_CLASS_MASS_STORAGE, USB_DT_CONFIG, USB_DT_DEVICE, USB_PROTOCOL_MASS_BULK_ONLY, USB_SUBCLASS_MASS_SCSI, USB_SUBCLASS_MASS_SFF_8070I, USBMASS_DEV_STAT_CONN, UsbConfigDescriptor::wTotalLength, and XPRINTF.
Referenced by InitUSB().
mass_stor_readSector()
int mass_stor_readSector (mass_dev * dev, unsigned int sector, unsigned char * buffer, unsigned short int count)
Definition at line 763 of file usb_driver.c.
 {
         int retries;
         for(retries = USB_IO_MAX_RETRIES; retries > 0; retries--)
         {
                 if(cbw_scsi_read_sector(dev, sector, buffer, count) == 0)
                         return 0;
         }
         return -EIO;
 }
References buffer, cbw_scsi_read_sector(), EIO, and USB_IO_MAX_RETRIES.
mass_stor_release()
static void mass_stor_release (mass_dev * dev) static
Definition at line 948 of file usb_driver.c.
 {
         if (dev->bulkEpI >= 0)
         {
                 sceUsbdClosePipe(dev->bulkEpI);
         }
         if (dev->bulkEpO >= 0)
         {
                 sceUsbdClosePipe(dev->bulkEpO);
         }
         dev->bulkEpI = -1;
         dev->bulkEpO = -1;
         dev->controlEp = -1;
         dev->status = 0;
 }
References mass_dev::bulkEpI, mass_dev::bulkEpO, mass_dev::controlEp, sceUsbdClosePipe(), and mass_dev::status.
Referenced by mass_stor_configureNextDevice(), mass_stor_connect(), and mass_stor_disconnect().
mass_stor_stop_unit()
int mass_stor_stop_unit (mass_dev * dev)
Definition at line 1186 of file usb_driver.c.
 {
         int stat;
         if ((stat = cbw_scsi_start_stop_unit(dev, 0)) != 0) {
                 printf("USBHDFSD: Error - cbw_scsi_start_stop_unit %d\n", stat);
         }
         return stat;
 }
References cbw_scsi_start_stop_unit(), and printf().
Referenced by fs_devctl(), and mass_store_stop_all().
mass_stor_warmup()
static int mass_stor_warmup (mass_dev * dev) static
Definition at line 994 of file usb_driver.c.
{
         inquiry_data id;
         sense_data sd;
         read_capacity_data rcd;
         int stat;
         XPRINTF("USBHDFSD: mass_stor_warmup\n");
         if (!(dev->status & USBMASS_DEV_STAT_CONN)) {
                 printf("USBHDFSD: Error - no mass storage device found!\n");
                 return -1;
         }
         stat = usb_bulk_get_max_lun(dev);
         printf("USBHDFSD: usb_bulk_get_max_lun %d\n", stat);
         memset(&id, 0, sizeof(inquiry_data));
         if ((stat = cbw_scsi_inquiry(dev, &id, sizeof(inquiry_data))) < 0) {
                 printf("USBHDFSD: Error - cbw_scsi_inquiry %d\n", stat);
                 return -1;
         }
         printf( "USBHDFSD:\tVendor: %.8s\n"
                         "\t\tProduct: %.16s\n"
                         "\t\tRevision: %.4s\n", id.vendor, id.product, id.revision);
         while((stat = cbw_scsi_test_unit_ready(dev)) != 0)
         {
                 printf("USBHDFSD: cbw_scsi_test_unit_ready %d\n", stat);
                 stat = cbw_scsi_request_sense(dev, &sd, sizeof(sense_data));
                 if (stat != 0)
                         printf("USBHDFSD: Error - cbw_scsi_request_sense %d\n", stat);
                 if ((sd.error_code == 0x70) && (sd.sense_key != 0x00))
                 {
                         printf("USBHDFSD: Sense Data key: %02X code: %02X qual: %02X\n", sd.sense_key, sd.add_sense_code, sd.add_sense_qual);
                         if ((sd.sense_key == 0x02) && (sd.add_sense_code == 0x04) && (sd.add_sense_qual == 0x02))
{
                                 printf("USBHDFSD: Error - Additional initalization is required for this device!\n");
                                 if ((stat = cbw_scsi_start_stop_unit(dev, 1)) != 0) {
                                         printf("USBHDFSD: Error - cbw_scsi_start_stop_unit %d\n", stat);
                                         return -1;
                                 }
                         }
                 }
         }
         if ((stat = cbw_scsi_read_capacity(dev, &rcd, sizeof(read_capacity_data))) != 0) {
                 printf("USBHDFSD: Error - cbw_scsi_read_capacity %d\n", stat);
                 return -1;
         }
         dev->sectorSize = getBI32(&rcd.block_length);
         dev->maxLBA     = getBI32(&rcd.last_lba);
         printf("USBHDFSD: sectorSize %u maxLBA %u\n", dev->sectorSize, dev->maxLBA);
         return 0;
 }
References read_capacity_data::block_length, cbw_scsi_inquiry(), cbw_scsi_read_capacity(), cbw_scsi_request_sense(), cbw_scsi_start_stop_unit(), cbw_scsi_test_unit_ready(), getBI32, read_capacity_data::last_lba, memset(), printf(), sd, mass_dev::status, usb_bulk_get_max_lun(), USBMASS_DEV_STAT_CONN, and XPRINTF.
Referenced by mass_stor_configureNextDevice().
mass_stor_writeSector()
int mass_stor_writeSector (mass_dev * dev, unsigned int sector, const unsigned char * buffer, unsigned short int count)
Definition at line 776 of file usb_driver.c.
 {
         int retries;
         for(retries = USB_IO_MAX_RETRIES; retries > 0; retries--)
         {
                 if(cbw_scsi_write_sector(dev, sector, buffer, count) == 0)
                         return 0;
         }
         return -EIO;
 }
References buffer, cbw_scsi_write_sector(), EIO, and USB_IO_MAX_RETRIES.
mass_store_configureDevice()
static int mass_store_configureDevice (mass_dev * dev) static
Definition at line 1055 of file usb_driver.c.
 {
         int ret;
         if ((ret = usb_set_configuration(dev, dev->configId)) != USB_RC_OK)
         {
                 printf("USBHDFSD: Error - sending set_configuration %d\n", ret);
                 return ret;
         }
         if((ret = usb_set_interface(dev, dev->interfaceNumber, dev->interfaceAlt)) != USB_RC_OK)
         {
                 printf("USBHDFSD: Error - sending set_interface %d\n", ret);
                 if (ret == USB_RC_STALL)
                 {       /* USB Specification 1.1, section 9.4.10: Devices that only support a default setting for the specified interface may return a STALL.
                            As with Linux, we shall clear the halt state of the interface's pipes and continue. */
                         usb_bulk_clear_halt(dev, USB_BLK_EP_IN);
                         usb_bulk_clear_halt(dev, USB_BLK_EP_OUT);
                         ret = USB_RC_OK;
                 }
         }
         return ret;
 }
References mass_dev::configId, mass_dev::interfaceAlt, mass_dev::interfaceNumber, printf(), USB_BLK_EP_IN, USB_BLK_EP_OUT, usb_bulk_clear_halt(), USB_RC_OK, USB_RC_STALL, usb_set_configuration(), and usb_set_interface().
Referenced by mass_stor_configureNextDevice(), and mass_store_stop_all().
mass_store_stop_all()
void mass_store_stop_all (void)
Definition at line 1197 of file usb_driver.c.
 {
         int i;
         for (i = 0; i < NUM_DEVICES; ++i)
         {
                 mass_dev *dev = &g_mass_device[i];
                 if (dev->devId != -1 && (dev->status & USBMASS_DEV_STAT_CONN))
                 {
                         if(!(dev->status & USBMASS_DEV_STAT_CONF))
                         {       //Configure unconfigured devices, to be able to shut them down.
                                 if (mass_store_configureDevice(dev) != USB_RC_OK)
                                         continue;
                         }
                         mass_stor_stop_unit(dev);
                 }
         }
 }
References mass_dev::devId, g_mass_device, mass_stor_stop_unit(), mass_store_configureDevice(), NUM_DEVICES, mass_dev::status, USB_RC_OK, USBMASS_DEV_STAT_CONF, and USBMASS_DEV_STAT_CONN.
Referenced by fs_devctl().
perform_bulk_transfer()
static int perform_bulk_transfer (usb_transfer_callback_data * data) static
Definition at line 133 of file usb_driver.c.
 {
         int ret, len;
         len = data->remaining > USB_BLOCK_SIZE ? USB_BLOCK_SIZE : data->remaining;
         ret = sceUsbdBulkTransfer(
                 data->pipe,             //bulk pipe epI (Read) or epO (Write)
                 data->buffer,           //data ptr
                 len,                    //data length
                 &usb_transfer_callback,
                 (void*)data
                 );
         return ret;
 }
References usb_transfer_callback_data::buffer, usb_transfer_callback_data::pipe, usb_transfer_callback_data::remaining, sceUsbdBulkTransfer, USB_BLOCK_SIZE, and usb_transfer_callback().
Referenced by usb_bulk_transfer(), and usb_transfer_callback().
usb_bulk_clear_halt()
static int usb_bulk_clear_halt (mass_dev * dev, int endpoint) static
Definition at line 209 of file usb_driver.c.
{
         int ret;
         usb_callback_data cb_data;
         cb_data.sema = dev->ioSema;
         ret = sceUsbdClearEndpointFeature(
                 dev->controlEp,         //Config pipe
                 0,                      //HALT feature
                 (endpoint==USB_BLK_EP_IN) ? dev->bulkEpI : dev->bulkEpO,
                 usb_callback,
                 (void*)&cb_data
                 );
         if (ret == USB_RC_OK) {
                 WaitSema(cb_data.sema);
                 ret = cb_data.returnCode;
         }
         if (ret != USB_RC_OK) {
                 printf("USBHDFSD: Error - sending clear halt %d\n", ret);
         }
         return ret;
 }
References mass_dev::bulkEpI, mass_dev::bulkEpO, mass_dev::controlEp, mass_dev::ioSema, printf(), usb_callback_data::returnCode, sceUsbdClearEndpointFeature, usb_callback_data::sema, USB_BLK_EP_IN, usb_callback(), USB_RC_OK, and WaitSema().
Referenced by mass_store_configureDevice(), usb_bulk_get_max_lun(), usb_bulk_manage_status(), usb_bulk_reset(), and usb_bulk_transfer().
usb_bulk_command()
static int usb_bulk_command (mass_dev * dev, cbw_packet * packet) static
Definition at line 373 of file usb_driver.c.
{
         int ret;
         usb_callback_data cb_data;
         if(dev->status & USBMASS_DEV_STAT_ERR){
                 printf("USBHDFSD: Rejecting I/O to offline device %d.\n", dev->devId);
                 return -1;
         }
         cb_data.sema = dev->ioSema;
         ret =  sceUsbdBulkTransfer(
                 dev->bulkEpO,           //bulk output pipe
                 packet,                 //data ptr
                 31,     //data length
                 usb_callback,
                 (void*)&cb_data
         );
         if (ret == USB_RC_OK) {
                 WaitSema(cb_data.sema);
                 ret = cb_data.returnCode;
         }
         if (ret != USB_RC_OK) {
                 printf("USBHDFSD: Error - sending bulk command %d. Calling reset recovery.\n", ret);
                 usb_bulk_reset(dev, 3);
         }
         return ret;
 }
References mass_dev::bulkEpO, mass_dev::devId, mass_dev::ioSema, printf(), usb_callback_data::returnCode, sceUsbdBulkTransfer, usb_callback_data::sema, mass_dev::status, usb_bulk_reset(), usb_callback(), USB_RC_OK, USBMASS_DEV_STAT_ERR, and WaitSema().
Referenced by cbw_scsi_inquiry(), cbw_scsi_read_capacity(), cbw_scsi_read_sector(), cbw_scsi_request_sense(), cbw_scsi_start_stop_unit(), cbw_scsi_test_unit_ready(), and cbw_scsi_write_sector().
usb_bulk_get_max_lun()
static int usb_bulk_get_max_lun (mass_dev * dev) static
Definition at line 336 of file usb_driver.c.
{
         int ret;
         usb_callback_data cb_data;
         char max_lun;
         cb_data.sema = dev->ioSema;
         //Call Bulk only mass storage reset
         ret = sceUsbdControlTransfer(
                 dev->controlEp,         //default pipe
                 0xA1,
                 0xFE,
                 0,
                 dev->interfaceNumber,   //interface number
                 1,                      //length
                 &max_lun,               //data
                 usb_callback,
                 (void*) &cb_data
                 );
         if (ret == USB_RC_OK) {
                 WaitSema(cb_data.sema);
                 ret = cb_data.returnCode;
         }
         if(ret == USB_RC_OK){
                 ret = max_lun;
         } else {
                 //Devices that do not support multiple LUNs may STALL this command.
                 usb_bulk_clear_halt(dev, USB_BLK_EP_IN);
                 usb_bulk_clear_halt(dev, USB_BLK_EP_OUT);
                 ret = -ret;
         }
         return ret;
 }
References mass_dev::controlEp, mass_dev::interfaceNumber, mass_dev::ioSema, usb_callback_data::returnCode, sceUsbdControlTransfer(), usb_callback_data::sema, USB_BLK_EP_IN, USB_BLK_EP_OUT, usb_bulk_clear_halt(), usb_callback(), USB_RC_OK, and WaitSema().
Referenced by mass_stor_warmup().
usb_bulk_manage_status()
static int usb_bulk_manage_status (mass_dev * dev, unsigned int tag) static
Definition at line 314 of file usb_driver.c.
{
         int ret;
         csw_packet csw;
         //XPRINTF("USBHDFSD: usb_bulk_manage_status 1 ...\n");
         ret = usb_bulk_status(dev, &csw, tag); /* Attempt to read CSW from bulk in endpoint */
         if (ret != USB_RC_OK) { /* STALL bulk in  -OR- Bulk error */
                 usb_bulk_clear_halt(dev, USB_BLK_EP_IN); /* clear the stall condition for bulk in */
                 printf("USBHDFSD: usb_bulk_manage_status error %d ...\n", ret);
                 ret = usb_bulk_status(dev, &csw, tag); /* Attempt to read CSW from bulk in endpoint */
         }
         /* CSW not valid  or stalled or phase error */
         if (ret != USB_RC_OK || csw.signature != CSW_TAG || csw.tag != tag || csw.status == 2) {
                 printf("USBHDFSD: usb_bulk_manage_status call reset recovery ...\n");
                 usb_bulk_reset(dev, 3); /* Perform reset recovery */
         }
         return((ret == USB_RC_OK && csw.signature == CSW_TAG && csw.tag == tag) ? csw.status : -1);
 }
References CSW_TAG, printf(), csw_packet::signature, csw_packet::status, csw_packet::tag, USB_BLK_EP_IN, usb_bulk_clear_halt(), usb_bulk_reset(), usb_bulk_status(), and USB_RC_OK.
Referenced by cbw_scsi_inquiry(), cbw_scsi_read_capacity(), cbw_scsi_read_sector(), cbw_scsi_request_sense(), cbw_scsi_start_stop_unit(), cbw_scsi_test_unit_ready(), and cbw_scsi_write_sector().
usb_bulk_probeEndpoint()
static void usb_bulk_probeEndpoint (int devId, mass_dev * dev, UsbEndpointDescriptor * endpoint) static
Definition at line 790 of file usb_driver.c.
{
         if (endpoint->bmAttributes == USB_ENDPOINT_XFER_BULK) {
                 /* out transfer */
                 if ((endpoint->bEndpointAddress & USB_ENDPOINT_DIR_MASK) == USB_DIR_OUT && dev->bulkEpO < 0) {
                         /* When sceUsbdOpenPipe() is used to work around the hardware errata that occurs when an unaligned memory address is specified,
                            some USB devices become incompatible. Hence it is preferable to do alignment correction in software instead. */
                         dev->bulkEpO = sceUsbdOpenPipeAligned(devId, endpoint);
                         XPRINTF("USBHDFSD: register Output endpoint id =%i addr=%02X packetSize=%i\n", dev->bulkEpO, endpoint->bEndpointAddress, (unsigned short int)endpoint->wMaxPacketSizeHB<<8 | endpoint->wMaxPacketSizeLB);
                 } else
                 /* in transfer */
                 if ((endpoint->bEndpointAddress & USB_ENDPOINT_DIR_MASK) == USB_DIR_IN && dev->bulkEpI < 0) {
                         /* Open this pipe with sceUsbdOpenPipe, to allow unaligned addresses to be used.
                            According to the Sony documentation and the USBD code,
                            there is always an alignment check if the pipe is opened with the sceUsbdOpenPipeAligned(),
                            even when there is never any correction for the bulk out pipe. */
                         dev->bulkEpI = sceUsbdOpenPipe(devId, endpoint);
                         XPRINTF("USBHDFSD: register Input endpoint id =%i addr=%02X packetSize=%i\n", dev->bulkEpI, endpoint->bEndpointAddress, (unsigned short int)endpoint->wMaxPacketSizeHB<<8 | endpoint->wMaxPacketSizeLB);
                 }
         }
 }
References UsbEndpointDescriptor::bEndpointAddress, UsbEndpointDescriptor::bmAttributes, mass_dev::bulkEpI, mass_dev::bulkEpO, sceUsbdOpenPipe(), sceUsbdOpenPipeAligned(), USB_DIR_IN, USB_DIR_OUT, USB_ENDPOINT_DIR_MASK, USB_ENDPOINT_XFER_BULK, UsbEndpointDescriptor::wMaxPacketSizeHB, UsbEndpointDescriptor::wMaxPacketSizeLB, and XPRINTF.
Referenced by mass_stor_connect().
usb_bulk_reset()
static void usb_bulk_reset (mass_dev * dev, int mode) static
Definition at line 234 of file usb_driver.c.
{
         int ret;
         usb_callback_data cb_data;
         cb_data.sema = dev->ioSema;
         //Call Bulk only mass storage reset
         ret = sceUsbdControlTransfer(
                 dev->controlEp,                 //default pipe
                 0x21,                   //bulk reset
                 0xFF,
                 0,
                 dev->interfaceNumber, //interface number
                 0,                      //length
                 NULL,                   //data
                 usb_callback,
                 (void*) &cb_data
                 );
         if (ret == USB_RC_OK) {
                 WaitSema(cb_data.sema);
                 ret = cb_data.returnCode;
         }
         if(ret == USB_RC_OK) {
                 //clear bulk-in endpoint
                 if (mode & 0x01)
                         ret = usb_bulk_clear_halt(dev, USB_BLK_EP_IN);
         }
         if(ret == USB_RC_OK) {
                 //clear bulk-out endpoint
                 if (mode & 0x02)
                         ret = usb_bulk_clear_halt(dev, USB_BLK_EP_OUT);
         }
         if(ret != USB_RC_OK){
                 printf("USBHDFSD: Error - sending reset %d to device %d.\n", ret, dev->devId);
                 dev->status |= USBMASS_DEV_STAT_ERR;
         }
 }
References mass_dev::controlEp, mass_dev::devId, mass_dev::interfaceNumber, mass_dev::ioSema, NULL, printf(), usb_callback_data::returnCode, sceUsbdControlTransfer(), usb_callback_data::sema, mass_dev::status, USB_BLK_EP_IN, USB_BLK_EP_OUT, usb_bulk_clear_halt(), usb_callback(), USB_RC_OK, USBMASS_DEV_STAT_ERR, and WaitSema().
Referenced by usb_bulk_command(), and usb_bulk_manage_status().
usb_bulk_status()
static int usb_bulk_status (mass_dev * dev, csw_packet * csw, unsigned int tag) static
Definition at line 273 of file usb_driver.c.
{
         int ret;
         usb_callback_data cb_data;
         cb_data.sema = dev->ioSema;
         csw->signature = CSW_TAG;
         csw->tag = tag;
         csw->dataResidue = 0;
         csw->status = 0;
         ret = sceUsbdBulkTransfer(
                 dev->bulkEpI,           //bulk input pipe
                 csw,                    //data ptr
                 13,     //data length
                 usb_callback,
                 (void*)&cb_data
         );
         if (ret == USB_RC_OK) {
                 WaitSema(cb_data.sema);
                 ret = cb_data.returnCode;
                 if (cb_data.returnSize != 13)
                         printf("USBHDFSD: bulk csw.status returnSize: %i != 13\n", cb_data.returnSize);
                 if (csw->dataResidue != 0)
                         printf("USBHDFSD: bulk csw.status residue: %i\n", csw->dataResidue);
                 XPRINTF("USBHDFSD: bulk csw result: %d, csw.status: %i\n", ret, csw->status);
         }
         return ret;
 }
References mass_dev::bulkEpI, CSW_TAG, csw_packet::dataResidue, mass_dev::ioSema, printf(), usb_callback_data::returnCode, usb_callback_data::returnSize, sceUsbdBulkTransfer, usb_callback_data::sema, csw_packet::signature, csw_packet::status, csw_packet::tag, usb_callback(), USB_RC_OK, WaitSema(), and XPRINTF.
Referenced by usb_bulk_manage_status().
usb_bulk_transfer()
static int usb_bulk_transfer (mass_dev * dev, int direction, void * buffer, unsigned int transferSize) static
Definition at line 404 of file usb_driver.c.
{
         int ret;
         usb_transfer_callback_data cb_data;
         cb_data.sema = dev->ioSema;
         cb_data.pipe = (direction==USB_BLK_EP_IN) ? dev->bulkEpI : dev->bulkEpO;
         cb_data.buffer = buffer;
         cb_data.remaining = transferSize;
         ret = perform_bulk_transfer(&cb_data);
         if (ret == USB_RC_OK) {
                 WaitSema(cb_data.sema);
                 ret = cb_data.returnCode;
         }
         if(ret != USB_RC_OK) {
                 printf("USBHDFSD: Error - bulk data transfer %d. Clearing HALT state.\n", cb_data.returnCode);
                 usb_bulk_clear_halt(dev, direction);
         }
         return ret;
 }
References buffer, usb_transfer_callback_data::buffer, mass_dev::bulkEpI, mass_dev::bulkEpO, mass_dev::ioSema, perform_bulk_transfer(), usb_transfer_callback_data::pipe, printf(), usb_transfer_callback_data::remaining, usb_transfer_callback_data::returnCode, usb_transfer_callback_data::sema, USB_BLK_EP_IN, usb_bulk_clear_halt(), USB_RC_OK, and WaitSema().
Referenced by cbw_scsi_inquiry(), cbw_scsi_read_capacity(), cbw_scsi_read_sector(), cbw_scsi_request_sense(), and cbw_scsi_write_sector().
usb_callback()
static void usb_callback (int resultCode, int bytes, void * arg) static
Definition at line 124 of file usb_driver.c.
 {
         usb_callback_data* data = (usb_callback_data*) arg;
         data->returnCode = resultCode;
         data->returnSize = bytes;
         XPRINTF("USBHDFSD: callback: res %d, bytes %d, arg %p \n", resultCode, bytes, arg);
         SignalSema(data->sema);
 }
References arg, usb_callback_data::returnCode, usb_callback_data::returnSize, usb_callback_data::sema, SignalSema(), and XPRINTF.
Referenced by usb_bulk_clear_halt(), usb_bulk_command(), usb_bulk_get_max_lun(), usb_bulk_reset(), usb_bulk_status(), usb_set_configuration(), and usb_set_interface().
usb_set_configuration()
static int usb_set_configuration (mass_dev * dev, int configNumber) static
Definition at line 175 of file usb_driver.c.
{
         int ret;
         usb_callback_data cb_data;
         cb_data.sema = dev->ioSema;
         XPRINTF("USBHDFSD: setting configuration controlEp=%i, confNum=%i \n", dev->controlEp, configNumber);
         ret = sceUsbdSetConfiguration(dev->controlEp, configNumber, usb_callback, (void*)&cb_data);
         if (ret == USB_RC_OK) {
                 WaitSema(cb_data.sema);
                 ret = cb_data.returnCode;
         }
         return ret;
 }
References mass_dev::controlEp, mass_dev::ioSema, usb_callback_data::returnCode, sceUsbdSetConfiguration, usb_callback_data::sema, usb_callback(), USB_RC_OK, WaitSema(), and XPRINTF.
Referenced by mass_store_configureDevice().
usb_set_interface()
static int usb_set_interface (mass_dev * dev, int interface, int altSetting) static
Definition at line 192 of file usb_driver.c.
{
         int ret;
         usb_callback_data cb_data;
         cb_data.sema = dev->ioSema;
         XPRINTF("USBHDFSD: setting interface controlEp=%i, interface=%i altSetting=%i\n", dev->controlEp, interface, altSetting);
         ret = sceUsbdSetInterface(dev->controlEp, interface, altSetting, usb_callback, (void*)&cb_data);
         if (ret == USB_RC_OK) {
                 WaitSema(cb_data.sema);
                 ret = cb_data.returnCode;
         }
         return ret;
 }
References mass_dev::controlEp, mass_dev::ioSema, usb_callback_data::returnCode, sceUsbdSetInterface, usb_callback_data::sema, usb_callback(), USB_RC_OK, WaitSema(), and XPRINTF.
Referenced by mass_store_configureDevice().
usb_transfer_callback()
static void usb_transfer_callback (int resultCode, int bytes, void * arg) static
Definition at line 148 of file usb_driver.c.
 {
         int ret;
         usb_transfer_callback_data* data = (usb_transfer_callback_data*)arg;
         data->returnCode = resultCode;
         if(resultCode == USB_RC_OK)
         {       //Update transfer progress if successful.
                 data->remaining -= bytes;
                 data->buffer += bytes;
         }
         if((resultCode == USB_RC_OK) && (data->remaining > 0))
         {       //OK to continue.
                 ret = perform_bulk_transfer(data);
                 if (ret != USB_RC_OK)
                 {
                         data->returnCode = ret;
                         SignalSema(data->sema);
                 }
         }
         else
         {
                 SignalSema(data->sema);
         }
 }
References arg, usb_transfer_callback_data::buffer, perform_bulk_transfer(), usb_transfer_callback_data::remaining, usb_transfer_callback_data::returnCode, usb_transfer_callback_data::sema, SignalSema(), and USB_RC_OK.
Referenced by perform_bulk_transfer().
UsbMassGetDeviceInfo()
int UsbMassGetDeviceInfo (int device, UsbMassDeviceInfo_t * info)
Definition at line 1151 of file usb_driver.c.
 {
         int result;
         mass_dev *pDev;
         if(device >=0 && device < NUM_DEVICES){
                 pDev = &g_mass_device[device];
                 info->status = pDev->status;
                 info->SectorSize = pDev->sectorSize;
                 info->MaxLBA = pDev->maxLBA;
                 result = 0;
         } else result = -ENODEV;
         return result;
 }
References ENODEV, g_mass_device, NUM_DEVICES, result, and mass_dev::status.
UsbMassRegisterCallback()
int UsbMassRegisterCallback (int device, usbmass_cb_t callback)
Definition at line 1169 of file usb_driver.c.
 {
         int result;
         if(device >=0 && device < NUM_DEVICES){
                 g_mass_device[device].callback = callback;
                 result = 0;
                 if(g_mass_device[device].status & USBMASS_DEV_STAT_CONN)
                 {       //If the device is already connected, let the callback know.
                         if(callback != NULL) callback(USBMASS_DEV_EV_CONN);
                 }
         } else result = -ENODEV;
         return result;
 }
References ENODEV, g_mass_device, NULL, NUM_DEVICES, result, status, USBMASS_DEV_EV_CONN, and USBMASS_DEV_STAT_CONN.
Variable Documentation
driver
sceUsbdLddOps driver static
Definition at line 98 of file usb_driver.c.
Referenced by InitUSB().
g_mass_device
mass_dev g_mass_device[NUM_DEVICES] static
Definition at line 117 of file usb_driver.c.
Referenced by InitUSB(), mass_stor_configureNextDevice(), mass_stor_findDevice(), mass_store_stop_all(), UsbMassGetDeviceInfo(), and UsbMassRegisterCallback().