ps2sdk: iop/usb/usbhdfsd/src/scache.c File Reference
scache.c File Reference
#include <stdio.h>
#include <tamtypes.h>
#include <sysmem.h>
#include <usbhdfsd.h>
#include "usbhd_common.h"
#include "mass_stor.h"
#include "mass_debug.h"
Macros
#define READ_SECTOR mass_stor_readSector
#define WRITE_SECTOR mass_stor_writeSector
#define BLOCK_SIZE 4096
Functions
static int scache_flushSector (cache_set *cache, int index)
static void initRecords (cache_set *cache)
static int getSlot (cache_set *cache, unsigned int sector)
static int getIndexRead (cache_set *cache, unsigned int sector)
static int getIndexWrite (cache_set *cache, unsigned int sector)
int scache_flushSectors (cache_set *cache)
int scache_readSector (cache_set *cache, unsigned int sector, void **buf)
int scache_writeSector (cache_set *cache, unsigned int sector)
void scache_invalidate (cache_set *cache, unsigned int sector, int count)
cache_set * scache_init (mass_dev *dev, int sectSize)
void scache_kill (cache_set *cache)
void scache_close (cache_set *cache)
Macro Definition Documentation
BLOCK_SIZE
#define BLOCK_SIZE 4096
Definition at line 41 of file scache.c.
READ_SECTOR
#define READ_SECTOR mass_stor_readSector
Definition at line 34 of file scache.c.
WRITE_SECTOR
#define WRITE_SECTOR mass_stor_writeSector
Definition at line 35 of file scache.c.
Function Documentation
getIndexRead()
static int getIndexRead (cache_set * cache, unsigned int sector) static
Definition at line 80 of file scache.c.
{
         unsigned int i;
         int index =-1;
         for (i = 0; i < CACHE_SIZE; i++) {
                 if (sector >= cache->rec[i].sector && sector < (cache->rec[i].sector + cache->indexLimit)) {
                         if (cache->rec[i].tax < 0) cache->rec[i].tax = 0;
                         cache->rec[i].tax +=2;
                         index = i;
                 }
                 cache->rec[i].tax--;     //apply tax penalty
         }
         if (index < 0)
                 return index;
         else
                 return ((index * cache->indexLimit) + (sector - cache->rec[index].sector));
 }
References CACHE_SIZE, index(), cache_set::indexLimit, cache_set::rec, cache_record::sector, and cache_record::tax.
getIndexWrite()
static int getIndexWrite (cache_set * cache, unsigned int sector) static
Definition at line 100 of file scache.c.
{
         int ret;
         int minTax = 0x0FFFFFFF;
         unsigned int i, index = 0;
         for (i = 0; i < CACHE_SIZE; i++) {
                 if (cache->rec[i].tax < minTax) {
                         index = i;
                         minTax = cache->rec[i].tax;
                 }
         }
         //this sector is dirty - we need to flush it first
         ret = scache_flushSector(cache, index);
         if (ret != 1)
                 return ret;
         cache->rec[index].tax +=2;
         cache->rec[index].sector = sector;
         return index * cache->indexLimit;
 }
References CACHE_SIZE, index(), cache_set::indexLimit, cache_set::rec, scache_flushSector(), cache_record::sector, and cache_record::tax.
getSlot()
static int getSlot (cache_set * cache, unsigned int sector) static
Definition at line 67 of file scache.c.
{
         int i;
         for (i = 0; i < CACHE_SIZE; i++) {
                 if (sector >= cache->rec[i].sector && sector < (cache->rec[i].sector + cache->indexLimit)) {
                         return i;
                 }
         }
         return -1;
 }
References CACHE_SIZE, cache_set::indexLimit, cache_set::rec, and cache_record::sector.
initRecords()
static void initRecords (cache_set * cache) static
Definition at line 49 of file scache.c.
 {
         unsigned int i;
         for (i = 0; i < CACHE_SIZE; i++)
         {
                 cache->rec[i].sector = 0xFFFFFFF0;
                 cache->rec[i].tax = 0;
                 cache->rec[i].writeDirty = 0;
         }
         cache->writeFlag = 0;
 }
References CACHE_SIZE, cache_set::rec, cache_record::sector, cache_record::tax, cache_record::writeDirty, and cache_set::writeFlag.
scache_close()
void scache_close (cache_set * cache)
Definition at line 352 of file scache.c.
 {
         XPRINTF("cache: close devId = %i \n", cache->dev->devId);
         scache_flushSectors(cache);
         scache_kill(cache);
 }
References cache_set::bd, block_device::devNr, M_DEBUG, scache_flushSectors(), scache_kill(), and XPRINTF.
scache_flushSector()
static int scache_flushSector (cache_set * cache, int index) static
Definition at line 127 of file scache.c.
{
         int ret;
         if (cache->rec[index].writeDirty) {
                 XPRINTF("scache: flushSector dirty index=%d sector=%u \n", index, cache->rec[index].sector);
                 ret = WRITE_SECTOR(cache->dev, cache->rec[index].sector, cache->sectorBuf + (index * BLOCK_SIZE), BLOCK_SIZE/cache->sectorSize);
                 if (ret < 0) {
                         printf("scache: ERROR writing sector to disk! sector=%u\n", cache->rec[index].sector);
                         return ret;
                 }
                 cache->rec[index].writeDirty = 0;
         }
         return 1;
 }
References BLOCK_SIZE, index(), printf(), cache_set::rec, cache_record::sector, cache_set::sectorBuf, cache_set::sectorSize, WRITE_SECTOR, cache_record::writeDirty, and XPRINTF.
Referenced by getIndexWrite(), scache_flushSectors(), and scache_invalidate().
scache_flushSectors()
int scache_flushSectors (cache_set * cache)
Definition at line 143 of file scache.c.
{
         unsigned int i;
         int counter = 0, ret;
         XPRINTF("cache: flushSectors devId = %i \n", cache->dev->devId);
         XPRINTF("scache: flushSectors writeFlag=%d\n", cache->writeFlag);
         //no write operation occured since last flush
         if (cache->writeFlag==0) {
                 return 0;
         }
         for (i = 0; i < CACHE_SIZE; i++) {
                 if((ret = scache_flushSector(cache, i)) >= 0)
                         counter ++;
                 else
                         return ret;
         }
         cache->writeFlag = 0;
         return counter;
 }
References cache_set::bd, BLOCK_SIZE, CACHE_SIZE, block_device::devNr, M_DEBUG, M_PRINTF, cache_set::rec, scache_flushSector(), cache_record::sector, cache_set::sectorBuf, cache_set::sectorSize, WRITE_SECTOR, cache_record::writeDirty, cache_set::writeFlag, and XPRINTF.
scache_init()
cache_set* scache_init (mass_dev * dev, int sectSize)
Definition at line 299 of file scache.c.
 {
         cache_set* cache;
         XPRINTF("cache: init devId = %i sectSize = %u \n", dev->devId, sectSize);
         cache = malloc(sizeof(cache_set));
         if (cache == NULL) {
                 printf("scache init! Sector cache: can't alloate cache!\n");
                 return NULL;
         }
         XPRINTF("scache init! \n");
         cache->dev = dev;
         cache->sectorBuf = (unsigned char*) malloc(BLOCK_SIZE * CACHE_SIZE);
         if (cache->sectorBuf == NULL) {
                 printf("Sector cache: can't alloate memory of size:%d \n", BLOCK_SIZE * CACHE_SIZE);
                 free(cache);
                 return NULL;
         }
         XPRINTF("Sector cache: allocated memory at:%p of size:%d \n", cache->sectorBuf, BLOCK_SIZE * CACHE_SIZE);
         //added by Hermes
         cache->sectorSize = sectSize;
         cache->indexLimit = BLOCK_SIZE/cache->sectorSize; //number of sectors per 1 cache slot
 #ifdef SCACHE_RECORD_STATS
         cache->cacheAccess = 0;
         cache->cacheHits = 0;
 #endif
         initRecords(cache);
         return cache;
 }
References BLOCK_SIZE, CACHE_SIZE, mass_dev::devId, free, cache_set::indexLimit, initRecords(), malloc, NULL, printf(), cache_set::sectorBuf, cache_set::sectorSize, and XPRINTF.
scache_invalidate()
void scache_invalidate (cache_set * cache, unsigned int sector, int count)
Definition at line 279 of file scache.c.
{
         int index; //index is given in single sectors not octal sectors
         int i;
         XPRINTF("cache: invalidate devId = %i sector = %u count = %d \n", cache->dev->devId, sector, count);
         for(i = 0; i < count; i++, sector++)
         {
                 index = getSlot(cache, sector);
                 if (index >=  0) { //sector found in cache. Write back and invalidate the block it belongs to.
                         scache_flushSector(cache, index);
                         cache->rec[index].sector = 0xFFFFFFF0;
                         cache->rec[index].tax = 0;
                         cache->rec[index].writeDirty = 0;
                 }
         }
 }
References getSlot(), index(), cache_set::rec, scache_flushSector(), cache_record::sector, cache_record::tax, cache_record::writeDirty, and XPRINTF.
scache_kill()
void scache_kill (cache_set * cache)
Definition at line 341 of file scache.c.
 {
         XPRINTF("cache: kill devId = %i \n", cache->dev->devId);
         if(cache->sectorBuf != NULL)
         {
                 free(cache->sectorBuf);
                 cache->sectorBuf = NULL;
         }
         free(cache);
 }
References cache_set::bd, block_device::devNr, free, M_DEBUG, NULL, cache_set::sectorBuf, and XPRINTF.
Referenced by fat_forceUnmount(), fat_mount(), mass_stor_disconnect(), and releaseSBP2Device().
scache_readSector()
int scache_readSector (cache_set * cache, unsigned int sector, void ** buf)
Definition at line 166 of file scache.c.
{
         int index; //index is given in single sectors not octal sectors
         int ret;
         unsigned int alignedSector;
         XPRINTF("cache: readSector devId = %i %p sector = %u \n", cache->dev->devId, cache, sector);
         if (cache == NULL) {
                 printf("cache: devId cache not created = %i \n", cache->dev->devId);
                 return -1;
         }
 #ifdef SCACHE_RECORD_STATS
         cache->cacheAccess ++;
 #endif
         index = getIndexRead(cache, sector);
         XPRINTF("cache: indexRead=%i \n", index);
         if (index >= 0) { //sector found in cache
 #ifdef SCACHE_RECORD_STATS
                 cache->cacheHits ++;
 #endif
                 *buf = cache->sectorBuf + (index * cache->sectorSize);
                 XPRINTF("cache: hit and done reading sector \n");
                 return cache->sectorSize;
         }
         //compute alignedSector - to prevent storage of duplicit sectors in slots
         alignedSector = (sector/cache->indexLimit)*cache->indexLimit;
         index = getIndexWrite(cache, alignedSector);
         XPRINTF("cache: indexWrite=%i slot=%d  alignedSector=%u\n", index, index / cache->indexLimit, alignedSector);
         ret = READ_SECTOR(cache->dev, alignedSector, cache->sectorBuf + (index * cache->sectorSize), BLOCK_SIZE/cache->sectorSize);
         if (ret < 0) {
                 printf("scache: ERROR reading sector from disk! sector=%u\n", alignedSector);
                 return ret;
         }
         *buf = cache->sectorBuf + (index * cache->sectorSize) + ((sector%cache->indexLimit) * cache->sectorSize);
         XPRINTF("cache: done reading physical sector \n");
         //write precaution
         //cache->flushCounter++;
         //if (cache->flushCounter == FLUSH_TRIGGER) {
                 //scache_flushSectors(cache);
         //}
         return cache->sectorSize;
 }
References cache_set::bd, BLOCK_SIZE, block_device::devNr, getIndexRead(), getIndexWrite(), index(), cache_set::indexLimit, M_DEBUG, M_PRINTF, NULL, printf(), READ_SECTOR, cache_set::sectorBuf, cache_set::sectorSize, and XPRINTF.
scache_writeSector()
int scache_writeSector (cache_set * cache, unsigned int sector)
Definition at line 248 of file scache.c.
{
         int index; //index is given in single sectors not octal sectors
         //int ret;
         XPRINTF("cache: writeSector devId = %i sector = %u \n", cache->dev->devId, sector);
         index = getSlot(cache, sector);
         if (index <  0) { //sector not found in cache
                 printf("cache: writeSector: ERROR! the sector is not allocated! \n");
                 return -1;
         }
         XPRINTF("cache: slotFound=%i \n", index);
         //prefere written sectors to stay in cache longer than read sectors
         cache->rec[index].tax += 2;
         //set dirty status
         cache->rec[index].writeDirty = 1;
         cache->writeFlag++;
         XPRINTF("cache: done soft writing sector \n");
         //write precaution
         //cache->flushCounter++;
         //if (cache->flushCounter == FLUSH_TRIGGER) {
                 //scache_flushSectors(devId);
         //}
         return cache->sectorSize;
 }
References cache_set::bd, block_device::devNr, getSlot(), index(), M_DEBUG, M_PRINTF, printf(), cache_set::rec, cache_set::sectorSize, cache_record::tax, cache_record::writeDirty, cache_set::writeFlag, and XPRINTF.