ps2sdk: iop/usb/usbmass_bd/src/main.c File Reference
main.c File Reference
#include "scsi.h"
#include <irx.h>
#include <loadcore.h>
#include <stdio.h>
#include "module_debug.h"
Macros
#define MAJOR_VER 1
#define MINOR_VER 1
#define MODNAME "usbmass_bd"
Functions
IRX_ID (MODNAME, MAJOR_VER, MINOR_VER)
int usb_mass_init (void)
int _start (int argc, char *argv[])
Macro Definition Documentation
MAJOR_VER
#define MAJOR_VER 1
Definition at line 1 of file main.c.
MINOR_VER
#define MINOR_VER 1
Definition at line 2 of file main.c.
MODNAME
#define MODNAME "usbmass_bd"
Definition at line 3 of file main.c.
Function Documentation
_start()
int _start (int argc, char * argv[])
Definition at line 17 of file main.c.
 {
     M_PRINTF("USB MASS Driver v%d.%d\n", MAJOR_VER, MINOR_VER);
     // initialize the SCSI driver
     if (scsi_init() != 0) {
         M_PRINTF("ERROR: initializing SCSI driver!\n");
         return MODULE_NO_RESIDENT_END;
     }
     // initialize the USB driver
     if (usb_mass_init() != 0) {
         M_PRINTF("ERROR: initializing USB driver!\n");
         return MODULE_NO_RESIDENT_END;
     }
     // return resident
     return MODULE_RESIDENT_END;
 }
References M_PRINTF, MAJOR_VER, MINOR_VER, MODULE_NO_RESIDENT_END, MODULE_RESIDENT_END, scsi_init(), and usb_mass_init().
IRX_ID()
IRX_ID (MODNAME , MAJOR_VER , MINOR_VER)
usb_mass_init()
int usb_mass_init (void)
Definition at line 764 of file usb_mass.c.
 {
     iop_thread_t thread;
     iop_sema_t sema;
     int ret;
     int i;
     M_DEBUG("%s\n", __func__);
     for (i = 0; i < NUM_DEVICES; ++i) {
         g_mass_device[i].status = 0;
         g_mass_device[i].devId  = -1;
         g_mass_device[i].scsi.priv        = &g_mass_device[i];
         g_mass_device[i].scsi.name        = "usb";
         g_mass_device[i].scsi.max_sectors = 0xffff;
         g_mass_device[i].scsi.get_max_lun = usb_bulk_get_max_lun;
         g_mass_device[i].scsi.queue_cmd   = usb_queue_cmd;
     }
     sema.attr            = 0;
     sema.option          = 0;
     sema.initial         = 0;
     sema.max             = 1;
     usb_mass_update_sema = CreateSema(&sema);
     driver.next       = NULL;
     driver.prev       = NULL;
     driver.name       = "mass-stor";
     driver.probe      = usb_mass_probe;
     driver.connect    = usb_mass_connect;
     driver.disconnect = usb_mass_disconnect;
     ret = sceUsbdRegisterLdd(&driver);
     M_DEBUG("sceUsbdRegisterLdd=%i\n", ret);
     if (ret < 0) {
         M_PRINTF("ERROR: register driver failed! ret=%d\n", ret);
         return -1;
     }
     thread.attr      = TH_C;
     thread.option    = 0;
     thread.thread    = usb_mass_update;
     thread.stacksize = 2 * 1024;
     thread.priority  = 0x10;
     ret = CreateThread(&thread);
     if (ret < 0) {
         M_PRINTF("ERROR: CreateThread failed! ret=%d\n", ret);
         return -1;
     }
     ret = StartThread(ret, 0);
     if (ret < 0) {
         M_PRINTF("ERROR: StartThread failed! ret=%d\n", ret);
         DeleteThread(ret);
         return -1;
     }
     return 0;
 }
References iop_thread_t::attr, iop_sema_t::attr, sceUsbdLddOps::connect, CreateSema(), CreateThread(), DeleteThread(), mass_dev::devId, sceUsbdLddOps::disconnect, driver, g_mass_device, scsi_interface::get_max_lun, iop_sema_t::initial, M_DEBUG, M_PRINTF, iop_sema_t::max, scsi_interface::max_sectors, scsi_interface::name, sceUsbdLddOps::name, sceUsbdLddOps::next, NULL, NUM_DEVICES, iop_thread_t::option, iop_sema_t::option, sceUsbdLddOps::prev, iop_thread_t::priority, scsi_interface::priv, sceUsbdLddOps::probe, scsi_interface::queue_cmd, sceUsbdRegisterLdd(), mass_dev::scsi, iop_thread_t::stacksize, StartThread(), mass_dev::status, TH_C, iop_thread_t::thread, usb_bulk_get_max_lun(), usb_mass_connect(), usb_mass_disconnect(), usb_mass_probe(), usb_mass_update(), usb_mass_update_sema, and usb_queue_cmd().
Referenced by _start().