ps2sdk: iop/usb/usbhdfsd/src/fat_driver.c File Reference
fat_driver.c File Reference
#include <stdio.h>
#include <errno.h>
#include <limits.h>
#include <sysclib.h>
#include <thbase.h>
#include <sysmem.h>
#include <usbhdfsd.h>
#include "usbhd_common.h"
#include "scache.h"
#include "fat_driver.h"
#include "fat.h"
#include "mass_stor.h"
#include "mass_debug.h"
Macros
#define READ_SECTOR(d, a, b) scache_readSector((d)->cache, (a), (void **)&b)
#define READ_SECTORS_RAW(d, a, c, b) mass_stor_readSector((d), a, b, c);
#define INVALIDATE_SECTORS(d, s, c) scache_invalidate((d)->cache, s, c)
#define NUM_DRIVES 10
Functions
int InitFAT (void)
int strEqual (const char *s1, const char *s2)
unsigned int fat_getClusterRecord12 (unsigned char *buf, int type)
static int fat_getClusterChain12 (fat_driver *fatd, unsigned int cluster, unsigned int *buf, unsigned int bufSize, int startFlag)
static int fat_getClusterChain16 (fat_driver *fatd, unsigned int cluster, unsigned int *buf, unsigned int bufSize, int startFlag)
static int fat_getClusterChain32 (fat_driver *fatd, unsigned int cluster, unsigned int *buf, unsigned int bufSize, int startFlag)
int fat_getClusterChain (fat_driver *fatd, unsigned int cluster, unsigned int *buf, unsigned int bufSize, int startFlag)
void fat_invalidateLastChainResult (fat_driver *fatd)
static void fat_determineFatType (fat_bpb *partBpb)
static int fat_getPartitionBootSector (mass_dev *dev, unsigned int sector, fat_bpb *partBpb)
int fat_getDirentry (unsigned char fatType, fat_direntry *dir_entry, fat_direntry_summary *dir)
void fat_setFatDirChain (fat_driver *fatd, fat_dir *fatDir)
static void fat_setFatDir (fat_driver *fatd, fat_dir *fatDir, unsigned int parentDirCluster, fat_direntry_sfn *dsfn, fat_direntry_summary *dir, int getClusterInfo)
int fat_getDirentrySectorData (fat_driver *fatd, unsigned int *startCluster, unsigned int *startSector, unsigned int *dirSector)
static int fat_getDirentryStartCluster (fat_driver *fatd, char *dirName, unsigned int *startCluster, fat_dir *fatDir)
int fat_getFileStartCluster (fat_driver *fatd, const char *fname, unsigned int *startCluster, fat_dir *fatDir)
void fat_getClusterAtFilePos (fat_driver *fatd, fat_dir *fatDir, unsigned int filePos, unsigned int *cluster, unsigned int *clusterPos)
static int fat_readSingleSector (mass_dev *dev, unsigned int sector, void *buffer, int size, int dataSkip)
int fat_readFile (fat_driver *fatd, fat_dir *fatDir, unsigned int filePos, unsigned char *buffer, unsigned int size)
int fat_getNextDirentry (fat_driver *fatd, fat_dir_list *fatdlist, fat_dir *fatDir)
int fat_getFirstDirentry (fat_driver *fatd, const char *dirName, fat_dir_list *fatdlist, fat_dir *fatDir_host, fat_dir *fatDir)
int fat_mount (mass_dev *dev, unsigned int start, unsigned int count)
void fat_forceUnmount (mass_dev *dev)
fat_driver * fat_getData (int device)
Variables
static fat_driver * g_fatd [NUM_DRIVES]
Macro Definition Documentation
INVALIDATE_SECTORS
#define INVALIDATE_SECTORS (d, s, c) scache_invalidate((d)->cache, s, c)
Definition at line 33 of file fat_driver.c.
NUM_DRIVES
#define NUM_DRIVES 10
Definition at line 35 of file fat_driver.c.
READ_SECTOR
#define READ_SECTOR (d, a, b) scache_readSector((d)->cache, (a), (void **)&b)
Definition at line 31 of file fat_driver.c.
READ_SECTORS_RAW
#define READ_SECTORS_RAW (d, a, c, b) mass_stor_readSector((d), a, b, c);
Definition at line 32 of file fat_driver.c.
Function Documentation
fat_determineFatType()
static void fat_determineFatType (fat_bpb * partBpb) static
Definition at line 254 of file fat_driver.c.
{
         unsigned int sector, clusterCount;
         //get sector of cluster 0
         sector = fat_cluster2sector(partBpb, 0);
         //remove partition start sector to get BR+FAT+ROOT_DIR sector count
         sector -= partBpb->partStart;
         sector = partBpb->sectorCount - sector;
         clusterCount = sector / partBpb->clusterSize;
         //XPRINTF("USBHDFSD: Data cluster count = %u \n", clusterCount);
         if (clusterCount < 4085) {
                 partBpb->fatType = FAT12;
         } else
         if (clusterCount < 65525) {
                 partBpb->fatType = FAT16;
         } else {
                 partBpb->fatType = FAT32;
         }
 }
References fat_bpb::clusterSize, FAT12, FAT16, FAT32, fat_cluster2sector(), fat_bpb::fatType, fat_bpb::partStart, and fat_bpb::sectorCount.
Referenced by fat_getPartitionBootSector().
fat_forceUnmount()
void fat_forceUnmount (mass_dev * dev)
Definition at line 1031 of file fat_driver.c.
 {
         unsigned int i;
         XPRINTF("USBHDFSD: usb fat: forceUnmount devId %i \n", dev->devId);
         for (i = 0; i < NUM_DRIVES; ++i)
         {
                 if (g_fatd[i] != NULL && g_fatd[i]->dev == dev)
                         g_fatd[i] = NULL;
         }
 }
References mass_dev::devId, g_fatd, NULL, NUM_DRIVES, and XPRINTF.
fat_getClusterAtFilePos()
void fat_getClusterAtFilePos (fat_driver * fatd, fat_dir * fatDir, unsigned int filePos, unsigned int * cluster, unsigned int * clusterPos)
Definition at line 723 of file fat_driver.c.
{
         unsigned int i, j, blockSize;
         blockSize = fatd->partBpb.clusterSize * fatd->partBpb.sectorSize;
         for (i = 0, j = (DIR_CHAIN_SIZE-1); i < (DIR_CHAIN_SIZE-1); i++) {
                 if (fatDir->chain[i].index   * blockSize <= filePos &&
                         fatDir->chain[i+1].index * blockSize >  filePos) {
                                 j = i;
                                 break;
                         }
         }
         *cluster    = fatDir->chain[j].cluster;
         *clusterPos = (fatDir->chain[j].index * blockSize);
 }
References fat_dir::chain, fat_dir_chain_record::cluster, fat_bpb::clusterSize, DIR_CHAIN_SIZE, fat_dir_chain_record::index, fat_driver::partBpb, and fat_bpb::sectorSize.
fat_getClusterChain()
int fat_getClusterChain (fat_driver * fatd, unsigned int cluster, unsigned int * buf, unsigned int bufSize, int startFlag)
Definition at line 232 of file fat_driver.c.
{
         if (cluster == fatd->lastChainCluster) {
                 return fatd->lastChainResult;
         }
         switch (fatd->partBpb.fatType) {
                 case FAT12: fatd->lastChainResult = fat_getClusterChain12(fatd, cluster, buf, bufSize, startFlag); break;
                 case FAT16: fatd->lastChainResult = fat_getClusterChain16(fatd, cluster, buf, bufSize, startFlag); break;
                 case FAT32: fatd->lastChainResult = fat_getClusterChain32(fatd, cluster, buf, bufSize, startFlag); break;
         }
         fatd->lastChainCluster = cluster;
         return fatd->lastChainResult;
 }
References FAT12, FAT16, FAT32, fat_getClusterChain12(), fat_getClusterChain16(), fat_getClusterChain32(), fat_bpb::fatType, fat_driver::lastChainCluster, fat_driver::lastChainResult, and fat_driver::partBpb.
fat_getClusterChain12()
static int fat_getClusterChain12 (fat_driver * fatd, unsigned int cluster, unsigned int * buf, unsigned int bufSize, int startFlag) static
Definition at line 98 of file fat_driver.c.
{
         int ret;
         unsigned int i, recordOffset, fatSector, lastFatSector;
         unsigned char xbuf[4], sectorSpan, cont;
         unsigned char* sbuf = NULL; //sector buffer
         cont = 1;
         lastFatSector = -1;
         i = 0;
         if (startFlag) {
                 buf[i] = cluster; //store first cluster
                 i++;
         }
         while(i < bufSize && cont) {
                 recordOffset = (cluster * 3) / 2; //offset of the cluster record (in bytes) from the FAT start
                 fatSector = recordOffset / fatd->partBpb.sectorSize;
                 sectorSpan = 0;
                 if ((recordOffset % fatd->partBpb.sectorSize) == (fatd->partBpb.sectorSize - 1)) {
                         sectorSpan = 1;
                 }
                 if (lastFatSector !=  fatSector || sectorSpan) {
                         ret = READ_SECTOR(fatd->dev, fatd->partBpb.partStart + fatd->partBpb.resSectors + fatSector, sbuf);
                         if (ret < 0) {
                                 XPRINTF("USBHDFSD: Read fat12 sector failed! sector=%u! \n", fatd->partBpb.partStart + fatd->partBpb.resSectors + fatSector );
                                 return -EIO;
                         }
                         lastFatSector = fatSector;
                         if (sectorSpan) {
                                 xbuf[0] = sbuf[fatd->partBpb.sectorSize - 2];
                                 xbuf[1] = sbuf[fatd->partBpb.sectorSize - 1];
                                 ret = READ_SECTOR(fatd->dev, fatd->partBpb.partStart + fatd->partBpb.resSectors + fatSector + 1, sbuf);
                                 if (ret < 0) {
                                         XPRINTF("USBHDFSD: Read fat12 sector failed sector=%u! \n", fatd->partBpb.partStart + fatd->partBpb.resSectors + fatSector + 1);
                                         return -EIO;
                                 }
                                 xbuf[2] = sbuf[0];
                                 xbuf[3] = sbuf[1];
                         }
                 }
                 if (sectorSpan) { // use xbuf as source buffer
                         cluster = fat_getClusterRecord12(xbuf + (recordOffset % fatd->partBpb.sectorSize) - (fatd->partBpb.sectorSize-2), cluster % 2);
                 } else { // use sector buffer as source buffer
                         cluster = fat_getClusterRecord12(sbuf + (recordOffset % fatd->partBpb.sectorSize), cluster % 2);
                 }
                 if ((cluster & 0xFFF) >= 0xFF8) {
                         cont = 0; //continue = false
                 } else {
                         buf[i] = cluster & 0xFFF;
                         i++;
                 }
         }
         return i;
 }
References fat_driver::dev, EIO, fat_getClusterRecord12(), NULL, fat_driver::partBpb, fat_bpb::partStart, READ_SECTOR, fat_bpb::resSectors, sbuf, fat_bpb::sectorSize, and XPRINTF.
Referenced by fat_getClusterChain().
fat_getClusterChain16()
static int fat_getClusterChain16 (fat_driver * fatd, unsigned int cluster, unsigned int * buf, unsigned int bufSize, int startFlag) static
Definition at line 157 of file fat_driver.c.
{
         int ret;
         unsigned int i, indexCount, fatSector, lastFatSector;
         unsigned char cont;
         unsigned char* sbuf = NULL; //sector buffer
         cont = 1;
         indexCount = fatd->partBpb.sectorSize / 2; //FAT16->2, FAT32->4
         lastFatSector = -1;
         i = 0;
         if (startFlag) {
                 buf[i] = cluster; //store first cluster
                 i++;
         }
         while(i < bufSize && cont) {
                 fatSector = cluster / indexCount;
                 if (lastFatSector !=  fatSector) {
                         ret = READ_SECTOR(fatd->dev, fatd->partBpb.partStart + fatd->partBpb.resSectors + fatSector,  sbuf);
                         if (ret < 0) {
                                 XPRINTF("USBHDFSD: Read fat16 sector failed! sector=%u! \n", fatd->partBpb.partStart + fatd->partBpb.resSectors + fatSector );
                                 return -EIO;
                         }
                         lastFatSector = fatSector;
                 }
                 cluster = getI16(sbuf + ((cluster % indexCount) * 2));
                 if ((cluster & 0xFFFF) >= 0xFFF8) {
                         cont = 0; //continue = false
                 } else {
                         buf[i] = cluster & 0xFFFF;
                         i++;
                 }
         }
         return i;
 }
References fat_driver::dev, EIO, getI16, NULL, fat_driver::partBpb, fat_bpb::partStart, READ_SECTOR, fat_bpb::resSectors, sbuf, fat_bpb::sectorSize, and XPRINTF.
Referenced by fat_getClusterChain().
fat_getClusterChain32()
static int fat_getClusterChain32 (fat_driver * fatd, unsigned int cluster, unsigned int * buf, unsigned int bufSize, int startFlag) static
Definition at line 195 of file fat_driver.c.
{
         int ret;
         unsigned int i, indexCount, fatSector, lastFatSector;
         unsigned char cont;
         unsigned char* sbuf = NULL; //sector buffer
         cont = 1;
         indexCount = fatd->partBpb.sectorSize / 4; //FAT16->2, FAT32->4
         lastFatSector = -1;
         i = 0;
         if (startFlag) {
                 buf[i] = cluster; //store first cluster
                 i++;
         }
         while(i < bufSize && cont) {
                 fatSector = cluster / indexCount;
                 if (lastFatSector !=  fatSector) {
                         ret = READ_SECTOR(fatd->dev, fatd->partBpb.partStart + fatd->partBpb.resSectors + fatSector,  sbuf);
                         if (ret < 0) {
                                 XPRINTF("USBHDFSD: Read fat32 sector failed sector=%u! \n", fatd->partBpb.partStart + fatd->partBpb.resSectors + fatSector );
                                 return -EIO;
                         }
                         lastFatSector = fatSector;
                 }
                 cluster = getI32(sbuf + ((cluster % indexCount) * 4));
                 if ((cluster & 0xFFFFFFF) >= 0xFFFFFF8) {
                         cont = 0; //continue = false
                 } else {
                         buf[i] = cluster & 0xFFFFFFF;
                         i++;
                 }
         }
         return i;
 }
References fat_driver::dev, EIO, getI32, NULL, fat_driver::partBpb, fat_bpb::partStart, READ_SECTOR, fat_bpb::resSectors, sbuf, fat_bpb::sectorSize, and XPRINTF.
Referenced by fat_getClusterChain().
fat_getClusterRecord12()
unsigned int fat_getClusterRecord12 (unsigned char * buf, int type)
Definition at line 79 of file fat_driver.c.
{
         if (type) { //1
                 return ((buf[1]<< 4) + (buf[0] >>4));
         } else { // 0
                 return (((buf[1] & 0x0F) << 8) + buf[0]);
         }
 }
fat_getData()
fat_driver* fat_getData (int device)
Definition at line 1044 of file fat_driver.c.
 {
         if (device >= NUM_DRIVES)
                 return NULL;
         while (g_fatd[device] == NULL || g_fatd[device]->dev == NULL)
         {
                 if (mass_stor_configureNextDevice() <= 0)
                         break;
                 //Do not block USBD by busy-looping here, if the device is not ready. This function call will carry the priority of the calling thread.
                 DelayThread(5000);
         }
         if (g_fatd[device] == NULL || g_fatd[device]->dev == NULL)
                 return NULL;
         else
                 return g_fatd[device];
 }
References DelayThread(), g_fatd, mass_stor_configureNextDevice(), NULL, and NUM_DRIVES.
fat_getDirentry()
int fat_getDirentry (unsigned char fatType, fat_direntry * dir_entry, fat_direntry_summary * dir)
Definition at line 345 of file fat_driver.c.
{
         int i, j;
         unsigned int offset;
         unsigned char cont;
         u16 character;
         //detect last entry - all zeros (slight modification by radad)
         if (dir_entry->sfn.name[0] == 0) {
                 return 0;
         }
         //detect deleted entry - it will be ignored
         if (dir_entry->sfn.name[0] == 0xE5) {
                 return 3;
         }
         //detect long filename
         if (dir_entry->lfn.rshv == 0x0F && dir_entry->lfn.reserved1 == 0x00 && dir_entry->lfn.reserved2[0] == 0x00) {
                 //long filename - almost whole direntry is unicode string - extract it
                 offset = dir_entry->lfn.entrySeq & 0x3f;
                 offset--;
                 offset = offset * 13;
                 //name - 1st part
                 cont = 1;
                 for (i = 0; i < 10 && cont; i+=2) {
                         character = dir_entry->lfn.name1[i] | (dir_entry->lfn.name1[i+1] << 8);
                         if (character == 0 || offset >= (FAT_MAX_NAME - 1)) {
                                 dir->name[offset] = 0; //terminate
                                 cont = 0; //stop
                         } else {
                                 // Handle characters that we don't support.
                                 dir->name[offset] = character <= UCHAR_MAX ? dir_entry->lfn.name1[i] : '?';
                                 offset++;
                         }
                 }
                 //name - 2nd part
                 for (i = 0; i < 12 && cont; i+=2) {
                         character = dir_entry->lfn.name2[i] | (dir_entry->lfn.name2[i+1] << 8);
                         if (character == 0 || offset >= (FAT_MAX_NAME - 1)) {
                                 dir->name[offset] = 0; //terminate
                                 cont = 0; //stop
                         } else {
                                 // Handle characters that we don't support.
                                 dir->name[offset] = character <= UCHAR_MAX ? dir_entry->lfn.name2[i] : '?';
                                 offset++;
                         }
                 }
                 //name - 3rd part
                 for (i = 0; i < 4 && cont; i+=2) {
                         character = dir_entry->lfn.name3[i] | (dir_entry->lfn.name3[i+1] << 8);
                         if (character == 0 || offset >= (FAT_MAX_NAME - 1)) {
                                 dir->name[offset] = 0; //terminate
                                 cont = 0; //stop
                         } else {
                                 // Handle characters that we don't support.
                                 dir->name[offset] = character <= UCHAR_MAX ? dir_entry->lfn.name3[i] : '?';
                                 offset++;
                         }
                 }
                 if ((dir_entry->lfn.entrySeq & 0x40)) { //terminate string flag
                         dir->name[offset] = 0;
                 }
                 return 2;
         } else {
                 //short filename
                 //copy name
                 for (i = 0; i < 8 && dir_entry->sfn.name[i]!= ' '; i++) {
                         dir->sname[i] = dir_entry->sfn.name[i];
                         // NT-adaption for LaunchELF
                         if (dir_entry->sfn.reservedNT & 0x08 &&
                           dir->sname[i] >= 'A' && dir->sname[i] <= 'Z') {
                                 dir->sname[i] += 0x20;  //Force standard letters in name to lower case
                         }
                 }
                 for (j=0; j < 3 && dir_entry->sfn.ext[j] != ' '; j++) {
                         if (j == 0) {
                                 dir->sname[i] = '.';
                                 i++;
                         }
                         dir->sname[i+j] = dir_entry->sfn.ext[j];
                         // NT-adaption for LaunchELF
                         if (dir_entry->sfn.reservedNT & 0x10 &&
                           dir->sname[i+j] >= 'A' && dir->sname[i+j] <= 'Z') {
                                 dir->sname[i+j] += 0x20;        //Force standard letters in ext to lower case
                         }
                 }
                 dir->sname[i+j] = 0; //terminate
                 if (dir->name[0] == 0) { //long name desn't exit
                         for (i =0 ; dir->sname[i] !=0; i++) dir->name[i] = dir->sname[i];
                         dir->name[i] = 0;
                 }
                 dir->attr = dir_entry->sfn.attr;
                 dir->size = getI32(dir_entry->sfn.size);
                 dir->cluster = (fatType == FAT32) ? getI32_2(dir_entry->sfn.clusterL, dir_entry->sfn.clusterH) : getI16(dir_entry->sfn.clusterL);
                 return 1;
         }
 }
References fat_direntry_sfn::attr, fat_direntry_summary::attr, fat_direntry_summary::cluster, fat_direntry_sfn::clusterH, fat_direntry_sfn::clusterL, fat_direntry_lfn::entrySeq, fat_direntry_sfn::ext, FAT32, FAT_MAX_NAME, getI16, getI32, getI32_2, fat_direntry::lfn, fat_direntry_sfn::name, fat_direntry_summary::name, fat_direntry_lfn::name1, fat_direntry_lfn::name2, fat_direntry_lfn::name3, fat_direntry_lfn::reserved1, fat_direntry_lfn::reserved2, fat_direntry_sfn::reservedNT, fat_direntry_lfn::rshv, fat_direntry::sfn, fat_direntry_sfn::size, fat_direntry_summary::size, fat_direntry_summary::sname, and UCHAR_MAX.
fat_getDirentrySectorData()
int fat_getDirentrySectorData (fat_driver * fatd, unsigned int * startCluster, unsigned int * startSector, unsigned int * dirSector)
Definition at line 571 of file fat_driver.c.
{
         unsigned int chainSize;
         if (*startCluster == 0 && fatd->partBpb.fatType < FAT32) { //Root directory
                 *startSector = fatd->partBpb.rootDirStart;
                 *dirSector =  fatd->partBpb.rootSize / (fatd->partBpb.sectorSize / 32);
                 return 0;
         }
          //other directory or fat 32
         if (*startCluster == 0 && fatd->partBpb.fatType == FAT32) {
                 *startCluster = fatd->partBpb.rootDirCluster;
         }
         *startSector = fat_cluster2sector(&fatd->partBpb, *startCluster);
         chainSize = fat_getClusterChain(fatd, *startCluster, fatd->cbuf, MAX_DIR_CLUSTER, 1);
         if (chainSize >= MAX_DIR_CLUSTER) {
                 XPRINTF("USBHDFSD: Chain too large\n");
                 return -EFAULT;
         } else if (chainSize > 0) {
                 *dirSector = chainSize * fatd->partBpb.clusterSize;
         } else {
                 XPRINTF("USBHDFSD: Error getting cluster chain! startCluster=%u \n", *startCluster);
                 return -EFAULT;
         }
         return chainSize;
 }
References fat_driver::cbuf, fat_bpb::clusterSize, EFAULT, FAT32, fat_cluster2sector(), fat_getClusterChain(), fat_bpb::fatType, MAX_DIR_CLUSTER, fat_driver::partBpb, fat_bpb::rootDirCluster, fat_bpb::rootDirStart, fat_bpb::rootSize, fat_bpb::sectorSize, and XPRINTF.
fat_getDirentryStartCluster()
static int fat_getDirentryStartCluster (fat_driver * fatd, char * dirName, unsigned int * startCluster, fat_dir * fatDir) static
Definition at line 599 of file fat_driver.c.
{
         fat_direntry_summary dir;
         unsigned int i, dirSector, startSector, dirPos;
         unsigned char cont;
         int ret;
 #ifdef DEBUG
         mass_dev* mass_device = fatd->dev;
 #endif
         cont = 1;
         XPRINTF("USBHDFSD: getting cluster for dir entry: %s \n", dirName);
         //clear name strings
         dir.sname[0] = 0;
         dir.name[0] = 0;
         ret = fat_getDirentrySectorData(fatd, startCluster, &startSector, &dirSector);
         if (ret < 0)
                 return ret;
         XPRINTF("USBHDFSD: dirCluster=%u startSector=%u (%u) dirSector=%u \n", *startCluster, startSector, startSector * mass_device->sectorSize, dirSector);
         //go through first directory sector till the max number of directory sectors
         //or stop when no more direntries detected
         for (i = 0; i < dirSector && cont; i++) {
                 unsigned char* sbuf = NULL; //sector buffer
                 //At cluster borders, get correct sector from cluster chain buffer
                 if ((*startCluster != 0) && (i % fatd->partBpb.clusterSize == 0)) {
                         startSector = fat_cluster2sector(&fatd->partBpb, fatd->cbuf[(i / fatd->partBpb.clusterSize)]) -i;
                 }
                 ret = READ_SECTOR(fatd->dev, startSector + i, sbuf);
                 if (ret < 0) {
                         XPRINTF("USBHDFSD: read directory sector failed ! sector=%u\n", startSector + i);
                         return -EIO;
                 }
                 XPRINTF("USBHDFSD: read sector ok, scanning sector for direntries...\n");
                 dirPos = 0;
                 // go through start of the sector till the end of sector
                 while (cont &&  dirPos < fatd->partBpb.sectorSize) {
                         fat_direntry* dir_entry = (fat_direntry*) (sbuf + dirPos);
                         cont = fat_getDirentry(fatd->partBpb.fatType, dir_entry, &dir); //get single directory entry from sector buffer
                         if (cont == 1) { //when short file name entry detected
                                 if (!(dir.attr & FAT_ATTR_VOLUME_LABEL)) { //not volume label
                                         if ((strEqual(dir.sname, dirName) == 0) ||
                                                 (strEqual(dir.name, dirName) == 0) ) {
                                                         XPRINTF("USBHDFSD: found! %s\n", dir.name);
                                                         if (fatDir != NULL) { //fill the directory properties
                                                                 fat_setFatDir(fatd, fatDir, *startCluster, &dir_entry->sfn, &dir, 1);
                                                         }
                                                         *startCluster = dir.cluster;
                                                         XPRINTF("USBHDFSD: direntry %s found at cluster: %u \n", dirName, dir.cluster);
                                                         return dir.attr; //returns file or directory attr
                                                 }
                                 }//ends "if(!(dir.attr & FAT_ATTR_VOLUME_LABEL))"
                                 //clear name strings
                                 dir.sname[0] = 0;
                                 dir.name[0] = 0;
                         }//ends "if (cont == 1)"
                         dirPos += sizeof(fat_direntry);
                 }//ends "while"
         }//ends "for"
         XPRINTF("USBHDFSD: direntry %s not found! \n", dirName);
         return -ENOENT;
 }
References fat_direntry_summary::attr, fat_driver::cbuf, fat_direntry_summary::cluster, fat_bpb::clusterSize, fat_driver::dev, EIO, ENOENT, FAT_ATTR_VOLUME_LABEL, fat_cluster2sector(), fat_getDirentry(), fat_getDirentrySectorData(), fat_setFatDir(), fat_bpb::fatType, fat_direntry_summary::name, NULL, fat_driver::partBpb, READ_SECTOR, sbuf, fat_direntry::sfn, fat_direntry_summary::sname, strEqual(), and XPRINTF.
Referenced by fat_getFileStartCluster().
fat_getFileStartCluster()
int fat_getFileStartCluster (fat_driver * fatd, const char * fname, unsigned int * startCluster, fat_dir * fatDir)
Definition at line 670 of file fat_driver.c.
{
         char tmpName[FAT_MAX_NAME+1];
         unsigned int i, offset;
         int ret;
         XPRINTF("USBHDFSD: Entering fat_getFileStartCluster\n");
         offset = 0;
         i=0;
         *startCluster = 0;
         if (fatDir != NULL) {
                 memset(fatDir, 0, sizeof(fat_dir));
                 fatDir->attr = FAT_ATTR_DIRECTORY;
         }
         if (fname[i] == '/') {
                 i++;
         }
         for ( ; fname[i] !=0; i++) {
                 if (fname[i] == '/') { //directory separator
                         tmpName[offset] = 0; //terminate string
                         ret = fat_getDirentryStartCluster(fatd, tmpName, startCluster, fatDir);
                         if (ret < 0) {
                                 return -ENOENT;
                         }
                         offset = 0;
                 } else{
                         tmpName[offset] = fname[i];
                         offset++;
                 }
         }//ends "for"
         //and the final file
         tmpName[offset] = 0; //terminate string
         XPRINTF("USBHDFSD: Ready to get cluster for file \"%s\"\n", tmpName);
         if (fatDir != NULL) {
                 //if the last char of the name was slash - the name was already found -exit
                 if (offset == 0) {
                         XPRINTF("USBHDFSD: Exiting from fat_getFileStartCluster with a folder\n");
                         return 2;
                 }
                 ret = fat_getDirentryStartCluster(fatd, tmpName, startCluster, fatDir);
                 if (ret < 0) {
                         XPRINTF("USBHDFSD: Exiting from fat_getFileStartCluster with error %i\n", ret);
                         return ret;
                 }
                 XPRINTF("USBHDFSD: file's startCluster found. Name=%s, cluster=%u \n", fname, *startCluster);
         }
         XPRINTF("USBHDFSD: Exiting from fat_getFileStartCluster with no error.\n");
         return 1;
 }
References fat_dir::attr, ENOENT, FAT_ATTR_DIRECTORY, fat_getDirentryStartCluster(), FAT_MAX_NAME, memset(), NULL, and XPRINTF.
fat_getFirstDirentry()
int fat_getFirstDirentry (fat_driver * fatd, const char * dirName, fat_dir_list * fatdlist, fat_dir * fatDir_host, fat_dir * fatDir)
Definition at line 966 of file fat_driver.c.
{
         int ret;
         unsigned int startCluster = 0;
         ret = fat_getFileStartCluster(fatd, dirName, &startCluster, fatDir_host);
         if (ret < 0) { //dir name not found
                 return -ENOENT;
         }
         //check that direntry is directory
         if (!(fatDir_host->attr & FAT_ATTR_DIRECTORY)) {
                 return -ENOTDIR; //it's a file - exit
         }
         fatdlist->direntryCluster = startCluster;
         fatdlist->direntryIndex = 0;
         return fat_getNextDirentry(fatd, fatdlist, fatDir);
 }
References fat_dir::attr, fat_dir_list::direntryCluster, fat_dir_list::direntryIndex, ENOENT, ENOTDIR, FAT_ATTR_DIRECTORY, fat_getFileStartCluster(), and fat_getNextDirentry().
fat_getNextDirentry()
int fat_getNextDirentry (fat_driver * fatd, fat_dir_list * fatdlist, fat_dir * fatDir)
Definition at line 888 of file fat_driver.c.
{
         fat_direntry_summary dir;
         int i, ret;
         unsigned int startSector, dirSector, dirPos, dirCluster;
         unsigned char cont, new_entry;
 #ifdef DEBUG
         mass_dev* mass_device = fatd->dev;
 #endif
         //the getFirst function was not called
         if (fatdlist->direntryCluster == 0xFFFFFFFF || fatDir == NULL) {
                 return -EFAULT;
         }
         dirCluster = fatdlist->direntryCluster;
         //clear name strings
         dir.sname[0] = 0;
         dir.name[0] = 0;
         ret = fat_getDirentrySectorData(fatd, &dirCluster, &startSector, &dirSector);
         if (ret < 0)
                 return ret;
         XPRINTF("USBHDFSD: dirCluster=%u startSector=%u (%u) dirSector=%u \n", dirCluster, startSector, startSector * mass_device->sectorSize, dirSector);
         //go through first directory sector till the max number of directory sectors
         //or stop when no more direntries detected
         //dlanor: but avoid rescanning same areas redundantly (if possible)
         cont = 1;
         new_entry = 1;
         dirPos = (fatdlist->direntryIndex*32) % fatd->partBpb.sectorSize;
         for (i = ((fatdlist->direntryIndex*32) / fatd->partBpb.sectorSize); (i < dirSector) && cont; i++) {
                 unsigned char* sbuf = NULL; //sector buffer
                 //At cluster borders, get correct sector from cluster chain buffer
                 if ((dirCluster != 0) && (new_entry || (i % fatd->partBpb.clusterSize == 0))) {
                         startSector = fat_cluster2sector(&fatd->partBpb, fatd->cbuf[(i / fatd->partBpb.clusterSize)])
                                 -i + (i % fatd->partBpb.clusterSize);
                         new_entry = 0;
                 }
                 ret = READ_SECTOR(fatd->dev, startSector + i, sbuf);
                 if (ret < 0) {
                         XPRINTF("USBHDFSD: Read directory  sector failed ! sector=%u\n", startSector + i);
                         return -EIO;
                 }
                 // go through sector from current pos till its end
                 while (cont &&  (dirPos < fatd->partBpb.sectorSize)) {
                         fat_direntry* dir_entry = (fat_direntry*) (sbuf + dirPos);
                         cont = fat_getDirentry(fatd->partBpb.fatType, dir_entry, &dir); //get a directory entry from sector
                         fatdlist->direntryIndex++; //Note current entry processed
                         if (cont == 1) { //when short file name entry detected
                                 fat_setFatDir(fatd, fatDir, dirCluster, &dir_entry->sfn, &dir, 0);
 #if 0
                         XPRINTF("USBHDFSD: fat_getNextDirentry %c%c%c%c%c%c %x %s %s\n",
                                 (dir.attr & FAT_ATTR_VOLUME_LABEL) ? 'v' : '-',
                                 (dir.attr & FAT_ATTR_DIRECTORY) ? 'd' : '-',
                                 (dir.attr & FAT_ATTR_READONLY) ? 'r' : '-',
                                 (dir.attr & FAT_ATTR_ARCHIVE) ? 'a' : '-',
                                 (dir.attr & FAT_ATTR_SYSTEM) ? 's' : '-',
                                 (dir.attr & FAT_ATTR_HIDDEN) ? 'h' : '-',
                                 dir.attr,
                                 dir.sname,
                                 dir.name);
 #endif
                                 return 1;
                         }
                         dirPos += sizeof(fat_direntry);
                 }//ends "while"
                 dirPos = 0;
         }//ends "for"
         // when we get this far - reset the direntry cluster
         fatdlist->direntryCluster = 0xFFFFFFFF; //no more files
         return 0; //indicate that no direntry is avalable
 }
References fat_direntry_summary::attr, fat_driver::cbuf, fat_bpb::clusterSize, fat_driver::dev, fat_dir_list::direntryCluster, fat_dir_list::direntryIndex, EFAULT, EIO, FAT_ATTR_ARCHIVE, FAT_ATTR_DIRECTORY, FAT_ATTR_HIDDEN, FAT_ATTR_READONLY, FAT_ATTR_SYSTEM, FAT_ATTR_VOLUME_LABEL, fat_cluster2sector(), fat_getDirentry(), fat_getDirentrySectorData(), fat_setFatDir(), fat_bpb::fatType, fat_direntry_summary::name, NULL, fat_driver::partBpb, READ_SECTOR, sbuf, fat_bpb::sectorSize, fat_direntry::sfn, fat_direntry_summary::sname, and XPRINTF.
fat_getPartitionBootSector()
static int fat_getPartitionBootSector (mass_dev * dev, unsigned int sector, fat_bpb * partBpb) static
Definition at line 276 of file fat_driver.c.
{
         fat_raw_bpb* bpb_raw; //fat16, fat12
         fat32_raw_bpb* bpb32_raw; //fat32
         int ret;
         unsigned char* sbuf = NULL; //sector buffer
         ret = READ_SECTOR(dev, sector, sbuf); //read partition boot sector (first sector on partition)
         if (ret < 0) {
                 XPRINTF("USBHDFSD: Read partition boot sector failed sector=%u! \n", sector);
                 return -EIO;
         }
         bpb_raw = (fat_raw_bpb*) sbuf;
         bpb32_raw = (fat32_raw_bpb*) sbuf;
         //set fat common properties
         partBpb->sectorSize = getI16(bpb_raw->sectorSize);
         partBpb->clusterSize = bpb_raw->clusterSize;
         partBpb->resSectors = getI16(bpb_raw->resSectors);
         partBpb->fatCount = bpb_raw->fatCount;
         partBpb->rootSize = getI16(bpb_raw->rootSize);
         partBpb->fatSize = getI16(bpb_raw->fatSize);
         partBpb->trackSize = getI16(bpb_raw->trackSize);
         partBpb->headCount = getI16(bpb_raw->headCount);
         partBpb->sectorCount = getI16(bpb_raw->sectorCountO);
         if (partBpb->sectorCount == 0) {
                 partBpb->sectorCount = getI32(bpb_raw->sectorCount); // large partition
         }
         partBpb->partStart = sector;
         partBpb->rootDirStart = partBpb->partStart + (partBpb->fatCount * partBpb->fatSize) + partBpb->resSectors;
         for (ret = 0; ret < 8; ret++) {
                 partBpb->fatId[ret] = bpb_raw->fatId[ret];
         }
         partBpb->fatId[ret] = 0;
         partBpb->rootDirCluster = 0;
         partBpb->dataStart = partBpb->rootDirStart + (partBpb->rootSize / (partBpb->sectorSize >> 5));
         fat_determineFatType(partBpb);
         //fat32 specific info
         if (partBpb->fatType == FAT32 && partBpb->fatSize == 0) {
                 partBpb->fatSize = getI32(bpb32_raw->fatSize32);
                 partBpb->activeFat = getI16(bpb32_raw->fatStatus);
                 if (partBpb->activeFat & 0x80) { //fat not synced
                         partBpb->activeFat = (partBpb->activeFat & 0xF);
                 } else {
                         partBpb->activeFat = 0;
                 }
                 partBpb->rootDirStart = partBpb->partStart + (partBpb->fatCount * partBpb->fatSize) + partBpb->resSectors;
                 partBpb->rootDirCluster = getI32(bpb32_raw->rootDirCluster);
                 for (ret = 0; ret < 8; ret++) {
                         partBpb->fatId[ret] = bpb32_raw->fatId[ret];
                 }
                 partBpb->fatId[ret] = 0;
                 partBpb->dataStart = partBpb->rootDirStart;
         }
         printf("USBHDFSD: Fat type %u Id %s \n", partBpb->fatType, partBpb->fatId);
         return 1;
 }
References fat_bpb::activeFat, fat_raw_bpb::clusterSize, fat_bpb::clusterSize, fat_bpb::dataStart, EIO, FAT32, fat_determineFatType(), fat_raw_bpb::fatCount, fat_bpb::fatCount, fat_raw_bpb::fatId, fat32_raw_bpb::fatId, fat_bpb::fatId, fat_raw_bpb::fatSize, fat_bpb::fatSize, fat32_raw_bpb::fatSize32, fat32_raw_bpb::fatStatus, fat_bpb::fatType, getI16, getI32, fat_raw_bpb::headCount, fat_bpb::headCount, NULL, fat_bpb::partStart, printf(), READ_SECTOR, fat_raw_bpb::resSectors, fat_bpb::resSectors, fat32_raw_bpb::rootDirCluster, fat_bpb::rootDirCluster, fat_bpb::rootDirStart, fat_raw_bpb::rootSize, fat_bpb::rootSize, sbuf, fat_raw_bpb::sectorCount, fat_bpb::sectorCount, fat_raw_bpb::sectorCountO, fat_raw_bpb::sectorSize, fat_bpb::sectorSize, fat_raw_bpb::trackSize, fat_bpb::trackSize, and XPRINTF.
Referenced by fat_mount().
fat_invalidateLastChainResult()
void fat_invalidateLastChainResult (fat_driver * fatd)
Definition at line 248 of file fat_driver.c.
 {
         fatd->lastChainCluster  = 0;
 }
References fat_driver::lastChainCluster.
fat_mount()
int fat_mount (mass_dev * dev, unsigned int start, unsigned int count)
Definition at line 984 of file fat_driver.c.
 {
         fat_driver* fatd = NULL;
         unsigned int i;
         for (i = 0; i < NUM_DRIVES && fatd == NULL; ++i)
         {
                 if (g_fatd[i] == NULL)
                 {
                         XPRINTF("USBHDFSD: usb fat: allocate fat_driver %d!\n", sizeof(fat_driver));
                         g_fatd[i] = malloc(sizeof(fat_driver));
                         if (g_fatd[i] != NULL)
{
                                 g_fatd[i]->dev = NULL;
                         }
                         fatd = g_fatd[i];
                 }
                 else if(g_fatd[i]->dev == NULL)
                 {
                         fatd = g_fatd[i];
                 }
         }
         if (fatd == NULL)
         {
                 printf("USBHDFSD: usb fat: unable to allocate drive!\n");
                 return -1;
         }
         if (fatd->dev != NULL)
         {
                 printf("USBHDFSD: usb fat: mount ERROR: alread mounted\n");
                 fat_forceUnmount(fatd->dev);
         }
         if (fat_getPartitionBootSector(dev, start, &fatd->partBpb) < 0)
                 return -1;
         fatd->dev = dev;
         fatd->deIdx = 0;
         fatd->clStackIndex = 0;
         fatd->clStackLast = 0;
         fatd->lastChainCluster = 0xFFFFFFFF;
         fatd->lastChainResult = -1;
         return 0;
 }
References fat_driver::clStackIndex, fat_driver::clStackLast, fat_driver::deIdx, fat_driver::dev, fat_forceUnmount(), fat_getPartitionBootSector(), g_fatd, fat_driver::lastChainCluster, fat_driver::lastChainResult, malloc, NULL, NUM_DRIVES, fat_driver::partBpb, printf(), and XPRINTF.
fat_readFile()
int fat_readFile (fat_driver * fatd, fat_dir * fatDir, unsigned int filePos, unsigned char * buffer, unsigned int size)
Definition at line 755 of file fat_driver.c.
{
         int ret, chainSize;
         unsigned int i, j, startSector, clusterChainStart, bufSize, sectorSkip, clusterSkip, dataSkip, toRead;
         unsigned char nextChain;
         mass_dev* mass_device = fatd->dev;
         unsigned int bufferPos, fileCluster, clusterPos;
         fat_getClusterAtFilePos(fatd, fatDir, filePos, &fileCluster, &clusterPos);
         sectorSkip = (filePos - clusterPos) / fatd->partBpb.sectorSize;
         clusterSkip = sectorSkip / fatd->partBpb.clusterSize;
         sectorSkip %= fatd->partBpb.clusterSize;
         dataSkip  = filePos  % fatd->partBpb.sectorSize;
         bufferPos = 0;
         XPRINTF("USBHDFSD: fileCluster = %u,  clusterPos= %u clusterSkip=%u, sectorSkip=%u dataSkip=%u \n",
                 fileCluster, clusterPos, clusterSkip, sectorSkip, dataSkip);
         if (fileCluster < 2) {
                 return 0;
         }
         nextChain = 1;
         clusterChainStart = 1;
         while (nextChain && size > 0 ) {
                 if((chainSize = fat_getClusterChain(fatd, fileCluster, fatd->cbuf, MAX_DIR_CLUSTER, clusterChainStart))<0){
                         return chainSize;
                 }
                 clusterChainStart = 0;
                 if (chainSize >= MAX_DIR_CLUSTER) { //the chain is full, but more chain parts exist
                         fileCluster = fatd->cbuf[MAX_DIR_CLUSTER - 1];
                 }else { //chain fits in the chain buffer completely - no next chain needed
                         nextChain = 0;
                 }
                 while (clusterSkip >= MAX_DIR_CLUSTER) {
                         chainSize = fat_getClusterChain(fatd, fileCluster, fatd->cbuf, MAX_DIR_CLUSTER, clusterChainStart);
                         clusterChainStart = 0;
                         if (chainSize >= MAX_DIR_CLUSTER) { //the chain is full, but more chain parts exist
                                 fileCluster = fatd->cbuf[MAX_DIR_CLUSTER - 1];
                         }else { //chain fits in the chain buffer completely - no next chain needed
                                 nextChain = 0;
                         }
                         clusterSkip -= MAX_DIR_CLUSTER;
                 }
                 //process the cluster chain (fatd->cbuf) and skip leading clusters if needed
                 for (i = 0 + clusterSkip; i < chainSize && size > 0; i++) {
                         //read cluster and save cluster content
                         startSector = fat_cluster2sector(&fatd->partBpb, fatd->cbuf[i]);
                         //Calculate how long we can continuously read for.
                         j = (size + dataSkip) / fatd->partBpb.sectorSize + sectorSkip;
                         toRead = 0;
                         while (1) {
                                 if(j >= fatd->partBpb.clusterSize)
{
                                         toRead += fatd->partBpb.clusterSize;
                                         j -= fatd->partBpb.clusterSize;
                                 }
                                 else
{
                                         toRead += j;
                                         j = 0;
                                 }
                                 //Check that the next cluster is adjacent to this one, so we can read across.
                                 if ((i >= chainSize - 1) || (fatd->cbuf[i] != (fatd->cbuf[i+1]-1)))
                                         break;
                                 if (j == 0)
                                         break;
                                 i++; //Advance to the next cluster.
                         }
                         //Consider the number of sectors within the cluster to skip.
                         startSector += sectorSkip;
                         toRead -= sectorSkip;
                         //process all sectors of the cluster (and skip leading sectors if needed)
                         if (dataSkip > 0) {
                                 bufSize = mass_device->sectorSize - dataSkip;
                                 if (size < bufSize)
                                         bufSize = size;
                                 ret = fat_readSingleSector(fatd->dev, startSector, buffer + bufferPos, bufSize, dataSkip);
                                 if (ret != 1) {
                                         return bufferPos;
                                 }
                                 if(size + dataSkip >= mass_device->sectorSize)
                                         toRead--;
                                 size -= bufSize;
                                 bufferPos += bufSize;
                                 dataSkip = 0;
                                 startSector++;
                         }
                         if(toRead > 0) {
                                 INVALIDATE_SECTORS(fatd->dev, startSector, toRead);
                                 ret = READ_SECTORS_RAW(fatd->dev, startSector, toRead, buffer + bufferPos);
                                 if (ret != 0) {
                                         XPRINTF("USBHDFSD: Read sectors failed ! sector=%u (%u)\n", startSector, toRead);
                                         return bufferPos;
                                 }
                                 bufSize = toRead * mass_device->sectorSize;
                                 size -= bufSize;
                                 bufferPos += bufSize;
                                 startSector += toRead;
                         }
                         if (size > 0 && size <= mass_device->sectorSize) {
                                 bufSize = size;
                                 ret = fat_readSingleSector(fatd->dev, startSector, buffer + bufferPos, bufSize, 0);
                                 if (ret != 1) {
                                         return bufferPos;
                                 }
                                 size -= bufSize;
                                 bufferPos += bufSize;
                         }
                         sectorSkip = 0;
                 }
                 clusterSkip = 0;
         }
         return bufferPos;
 }
References buffer, fat_driver::cbuf, fat_bpb::clusterSize, fat_driver::dev, fat_cluster2sector(), fat_getClusterAtFilePos(), fat_getClusterChain(), fat_readSingleSector(), INVALIDATE_SECTORS, MAX_DIR_CLUSTER, fat_driver::partBpb, READ_SECTORS_RAW, fat_bpb::sectorSize, and XPRINTF.
fat_readSingleSector()
static int fat_readSingleSector (mass_dev * dev, unsigned int sector, void * buffer, int size, int dataSkip) static
Definition at line 740 of file fat_driver.c.
{
         unsigned char* sbuf = NULL; //sector buffer
         int ret;
         ret = READ_SECTOR(dev, sector, sbuf);
         if (ret < 0) {
                 XPRINTF("USBHDFSD: Read sector failed ! sector=%u\n", sector);
                 return 0;
         }
         memcpy(buffer, sbuf + dataSkip, size);
         return 1;
 }
References buffer, memcpy(), NULL, READ_SECTOR, sbuf, and XPRINTF.
Referenced by fat_readFile().
fat_setFatDir()
static void fat_setFatDir (fat_driver * fatd, fat_dir * fatDir, unsigned int parentDirCluster, fat_direntry_sfn * dsfn, fat_direntry_summary * dir, int getClusterInfo) static
Definition at line 513 of file fat_driver.c.
{
         unsigned int i;
         char* srcName;
         XPRINTF("USBHDFSD: setting fat dir...\n");
         srcName = dir->sname;
         if (dir->name[0] != 0) { //long filename not empty
                 srcName = dir->name;
         }
         //copy name
         for (i = 0; srcName[i] != 0; i++) fatDir->name[i] = srcName[i];
         fatDir->name[i] = 0; //terminate
         fatDir->attr = dir->attr;
         fatDir->size = dir->size;
         //created Date: Day, Month, Year-low, Year-high
         fatDir->cdate[0] = (dsfn->dateCreate[0] & 0x1F);
         fatDir->cdate[1] = (dsfn->dateCreate[0] >> 5) + ((dsfn->dateCreate[1] & 0x01) << 3 );
         i = 1980 + (dsfn->dateCreate[1] >> 1);
         fatDir->cdate[2] = (i & 0xFF);
         fatDir->cdate[3] = ((i & 0xFF00)>> 8);
         //created Time: Hours, Minutes, Seconds
         fatDir->ctime[0] = ((dsfn->timeCreate[1] & 0xF8) >> 3);
         fatDir->ctime[1] = ((dsfn->timeCreate[1] & 0x07) << 3) + ((dsfn->timeCreate[0] & 0xE0) >> 5);
         fatDir->ctime[2] = ((dsfn->timeCreate[0] & 0x1F) << 1);
         //accessed Date: Day, Month, Year-low, Year-high
         fatDir->adate[0] = (dsfn->dateAccess[0] & 0x1F);
         fatDir->adate[1] = (dsfn->dateAccess[0] >> 5) + ((dsfn->dateAccess[1] & 0x01) << 3 );
         i = 1980 + (dsfn->dateAccess[1] >> 1);
         fatDir->adate[2] = (i & 0xFF);
         fatDir->adate[3] = ((i & 0xFF00)>> 8);
         //modified Date: Day, Month, Year-low, Year-high
         fatDir->mdate[0] = (dsfn->dateWrite[0] & 0x1F);
         fatDir->mdate[1] = (dsfn->dateWrite[0] >> 5) + ((dsfn->dateWrite[1] & 0x01) << 3 );
         i = 1980 + (dsfn->dateWrite[1] >> 1);
         fatDir->mdate[2] = (i & 0xFF);
         fatDir->mdate[3] = ((i & 0xFF00)>> 8);
         //modified Time: Hours, Minutes, Seconds
         fatDir->mtime[0] = ((dsfn->timeWrite[1] & 0xF8) >> 3);
         fatDir->mtime[1] = ((dsfn->timeWrite[1] & 0x07) << 3) + ((dsfn->timeWrite[0] & 0xE0) >> 5);
         fatDir->mtime[2] = ((dsfn->timeWrite[0] & 0x1F) << 1);
         fatDir->chain[0].cluster = dir->cluster;
         fatDir->chain[0].index  = 0;
         if (getClusterInfo) {
                 fat_setFatDirChain(fatd, fatDir);
         }
         fatDir->parentDirCluster = parentDirCluster;
         fatDir->startCluster = dir->cluster;
 }
References fat_dir::adate, fat_direntry_summary::attr, fat_dir::attr, fat_dir::cdate, fat_dir::chain, fat_direntry_summary::cluster, fat_dir_chain_record::cluster, fat_dir::ctime, fat_direntry_sfn::dateAccess, fat_direntry_sfn::dateCreate, fat_direntry_sfn::dateWrite, fat_setFatDirChain(), fat_dir_chain_record::index, fat_dir::mdate, fat_dir::mtime, fat_direntry_summary::name, fat_dir::name, fat_dir::parentDirCluster, fat_direntry_summary::size, fat_dir::size, fat_direntry_summary::sname, fat_dir::startCluster, fat_direntry_sfn::timeCreate, fat_direntry_sfn::timeWrite, and XPRINTF.
Referenced by fat_getDirentryStartCluster(), and fat_getNextDirentry().
fat_setFatDirChain()
void fat_setFatDirChain (fat_driver * fatd, fat_dir * fatDir)
Definition at line 448 of file fat_driver.c.
{
         int i,j;
         unsigned int index, clusterChainStart, fileCluster, fileSize, blockSize;
         unsigned char nextChain;
         int chainSize;
         XPRINTF("USBHDFSD: reading cluster chain  \n");
         fileCluster = fatDir->chain[0].cluster;
         if (fileCluster < 2) {
                 XPRINTF("USBHDFSD:    early exit... \n");
                 return;
         }
         fileSize = fatDir->size;
         blockSize = fileSize / DIR_CHAIN_SIZE;
         nextChain = 1;
         clusterChainStart = 0;
         j = 1;
         fileSize = 0;
         index = 0;
         while (nextChain) {
                 if((chainSize = fat_getClusterChain(fatd, fileCluster, fatd->cbuf, MAX_DIR_CLUSTER, 1)) >=0){
                         if (chainSize >= MAX_DIR_CLUSTER) { //the chain is full, but more chain parts exist
                                 fileCluster = fatd->cbuf[MAX_DIR_CLUSTER - 1];
                         }else { //chain fits in the chain buffer completely - no next chain exist
                                 nextChain = 0;
                         }
                 }else{
                         XPRINTF("USBHDFSD: fat_setFatDirChain(): fat_getClusterChain() failed: %d\n", chainSize);
                         return;
                 }
                 //process the cluster chain (fatd->cbuf)
                 for (i = clusterChainStart; i < chainSize; i++) {
                         fileSize += (fatd->partBpb.clusterSize * fatd->partBpb.sectorSize);
                         while (fileSize >= (j * blockSize) && j < DIR_CHAIN_SIZE) {
                                 fatDir->chain[j].cluster = fatd->cbuf[i];
                                 fatDir->chain[j].index = index;
                                 j++;
                         }//ends "while"
                         index++;
                 }//ends "for"
                 clusterChainStart = 1;
         }//ends "while"
         fatDir->lastCluster = fatd->cbuf[i-1];
 #ifdef DEBUG_EXTREME //dlanor: I patched this because this bloat hid important stuff
         //debug
         XPRINTF("USBHDFSD: SEEK CLUSTER CHAIN CACHE fileSize=%u blockSize=%u \n", fatDir->size, blockSize);
         for (i = 0; i < DIR_CHAIN_SIZE; i++) {
                 XPRINTF("USBHDFSD: index=%u cluster=%u offset= %u - %u start=%u \n",
                         fatDir->chain[i].index, fatDir->chain[i].cluster,
                         fatDir->chain[i].index * fatd->partBpb.clusterSize * fatd->partBpb.sectorSize,
                         (fatDir->chain[i].index+1) * fatd->partBpb.clusterSize * fatd->partBpb.sectorSize,
                         i * blockSize);
         }
 #endif /* debug */
         XPRINTF("USBHDFSD: read cluster chain  done!\n");
 }
References fat_driver::cbuf, fat_dir::chain, fat_dir_chain_record::cluster, fat_bpb::clusterSize, DIR_CHAIN_SIZE, fat_getClusterChain(), fat_dir_chain_record::index, index(), fat_dir::lastCluster, MAX_DIR_CLUSTER, fat_driver::partBpb, fat_bpb::sectorSize, fat_dir::size, and XPRINTF.
InitFAT()
int InitFAT (void)
Definition at line 39 of file fat_driver.c.
 {
     int i;
     for (i = 0; i < NUM_DRIVES; ++i)
         g_fatd[i] = NULL;
     return 0;
 }
References g_fatd, NULL, and NUM_DRIVES.
Referenced by _start().
strEqual()
int strEqual (const char * s1, const char * s2)
Definition at line 50 of file fat_driver.c.
{
     char u1, u2;
     for (;;) {
                 u1 = *s1++;
                 u2 = *s2++;
                 if (u1 >64 && u1 < 91)  u1+=32;
                 if (u2 >64 && u2 < 91)  u2+=32;
                 if (u1 != u2) {
                         return -1;
                 }
                 if (u1 == '\0') {
                     return 0;
                 }
     }
 }
References s1, and s2.
Variable Documentation
g_fatd
fat_driver* g_fatd[NUM_DRIVES] static
Definition at line 36 of file fat_driver.c.
Referenced by fat_forceUnmount(), fat_getData(), fat_mount(), and InitFAT().