ps2sdk: iop/usb/usbmass_bd/src/usb_mass.c File Reference
usb_mass.c File Reference
#include <errno.h>
#include <stdio.h>
#include <sysclib.h>
#include <thbase.h>
#include <thsemap.h>
#include <usbd.h>
#include <usbd_macro.h>
#include "scsi.h"
#include <usbhdfsd-common.h>
#include "module_debug.h"
Data Structures
struct mass_dev
struct cbw_packet
struct csw_packet
struct usb_callback_data
struct usb_transfer_callback_data
struct usbmass_cmd
Macros
#define USB_SUBCLASS_MASS_RBC 0x01
#define USB_SUBCLASS_MASS_ATAPI 0x02
#define USB_SUBCLASS_MASS_QIC 0x03
#define USB_SUBCLASS_MASS_UFI 0x04
#define USB_SUBCLASS_MASS_SFF_8070I 0x05
#define USB_SUBCLASS_MASS_SCSI 0x06
#define USB_PROTOCOL_MASS_CBI 0x00
#define USB_PROTOCOL_MASS_CBI_NO_CCI 0x01
#define USB_PROTOCOL_MASS_BULK_ONLY 0x50
#define USB_BLK_EP_IN 0
#define USB_BLK_EP_OUT 1
#define USB_XFER_MAX_RETRIES 8
#define CBW_TAG 0x43425355
#define CSW_TAG 0x53425355
#define USB_BLOCK_SIZE 4096
#define NUM_DEVICES 2
Functions
static void usb_callback (int resultCode, int bytes, void *arg)
static int perform_bulk_transfer (usb_transfer_callback_data *data)
static void usb_transfer_callback (int resultCode, int bytes, void *arg)
static void usb_mass_release (mass_dev *dev)
static int usb_set_configuration (mass_dev *dev, int configNumber)
static int usb_set_interface (mass_dev *dev, int interface, int altSetting)
static int usb_bulk_clear_halt (mass_dev *dev, int endpoint)
static void usb_bulk_reset (mass_dev *dev, int mode)
static int usb_bulk_status (mass_dev *dev, csw_packet *csw, unsigned int tag)
static int usb_bulk_manage_status (mass_dev *dev, unsigned int tag)
static int usb_bulk_get_max_lun (struct scsi_interface *scsi)
static int usb_bulk_command (mass_dev *dev, cbw_packet *packet)
static int usb_bulk_transfer (mass_dev *dev, int direction, void *buffer, unsigned int transferSize)
int usb_queue_cmd (struct scsi_interface *scsi, const unsigned char *cmd, unsigned int cmd_len, unsigned char *data, unsigned int data_len, unsigned int data_wr)
static mass_dev * usb_mass_findDevice (int devId, int create)
static void usb_bulk_probeEndpoint (int devId, mass_dev *dev, UsbEndpointDescriptor *endpoint)
static int usb_mass_probe (int devId)
static int usb_mass_connect (int devId)
static int usb_mass_disconnect (int devId)
static void usb_mass_update (void *arg)
int usb_mass_init (void)
Variables
static sceUsbdLddOps driver
static mass_dev g_mass_device [NUM_DEVICES]
static int usb_mass_update_sema
Macro Definition Documentation
CBW_TAG
#define CBW_TAG 0x43425355
Definition at line 36 of file usb_mass.c.
CSW_TAG
#define CSW_TAG 0x53425355
Definition at line 37 of file usb_mass.c.
NUM_DEVICES
#define NUM_DEVICES 2
Definition at line 87 of file usb_mass.c.
USB_BLK_EP_IN
#define USB_BLK_EP_IN 0
Definition at line 31 of file usb_mass.c.
USB_BLK_EP_OUT
#define USB_BLK_EP_OUT 1
Definition at line 32 of file usb_mass.c.
USB_BLOCK_SIZE
#define USB_BLOCK_SIZE 4096
Definition at line 77 of file usb_mass.c.
USB_PROTOCOL_MASS_BULK_ONLY
#define USB_PROTOCOL_MASS_BULK_ONLY 0x50
Definition at line 29 of file usb_mass.c.
USB_PROTOCOL_MASS_CBI
#define USB_PROTOCOL_MASS_CBI 0x00
Definition at line 27 of file usb_mass.c.
USB_PROTOCOL_MASS_CBI_NO_CCI
#define USB_PROTOCOL_MASS_CBI_NO_CCI 0x01
Definition at line 28 of file usb_mass.c.
USB_SUBCLASS_MASS_ATAPI
#define USB_SUBCLASS_MASS_ATAPI 0x02
Definition at line 21 of file usb_mass.c.
USB_SUBCLASS_MASS_QIC
#define USB_SUBCLASS_MASS_QIC 0x03
Definition at line 22 of file usb_mass.c.
USB_SUBCLASS_MASS_RBC
#define USB_SUBCLASS_MASS_RBC 0x01
Definition at line 20 of file usb_mass.c.
USB_SUBCLASS_MASS_SCSI
#define USB_SUBCLASS_MASS_SCSI 0x06
Definition at line 25 of file usb_mass.c.
USB_SUBCLASS_MASS_SFF_8070I
#define USB_SUBCLASS_MASS_SFF_8070I 0x05
Definition at line 24 of file usb_mass.c.
USB_SUBCLASS_MASS_UFI
#define USB_SUBCLASS_MASS_UFI 0x04
Definition at line 23 of file usb_mass.c.
USB_XFER_MAX_RETRIES
#define USB_XFER_MAX_RETRIES 8
Definition at line 34 of file usb_mass.c.
Function Documentation
perform_bulk_transfer()
static int perform_bulk_transfer (usb_transfer_callback_data * data) static
Definition at line 106 of file usb_mass.c.
 {
         int ret, len;
         len = data->remaining > USB_BLOCK_SIZE ? USB_BLOCK_SIZE : data->remaining;
         ret = sceUsbdBulkTransfer(
                 data->pipe,             //bulk pipe epI (Read) or epO (Write)
                 data->buffer,           //data ptr
                 len,                    //data length
                 &usb_transfer_callback,
                 (void*)data
                 );
         return ret;
 }
References usb_transfer_callback_data::buffer, usb_transfer_callback_data::pipe, usb_transfer_callback_data::remaining, sceUsbdBulkTransfer, USB_BLOCK_SIZE, and usb_transfer_callback().
Referenced by usb_bulk_transfer(), and usb_transfer_callback().
usb_bulk_clear_halt()
static int usb_bulk_clear_halt (mass_dev * dev, int endpoint) static
Definition at line 185 of file usb_mass.c.
 {
     int ret;
     usb_callback_data cb_data;
     cb_data.sema = dev->ioSema;
     ret = sceUsbdClearEndpointFeature(
         dev->controlEp, //Config pipe
         0,              //HALT feature
         (endpoint == USB_BLK_EP_IN) ? dev->bulkEpI : dev->bulkEpO,
         usb_callback,
         (void*)&cb_data);
     if (ret == USB_RC_OK) {
         WaitSema(cb_data.sema);
         ret = cb_data.returnCode;
     }
     if (ret != USB_RC_OK) {
         M_DEBUG("ERROR: sending clear halt %d\n", ret);
     }
     return ret;
 }
References mass_dev::bulkEpI, mass_dev::bulkEpO, mass_dev::controlEp, mass_dev::ioSema, M_DEBUG, usb_callback_data::returnCode, sceUsbdClearEndpointFeature, usb_callback_data::sema, USB_BLK_EP_IN, usb_callback(), USB_RC_OK, and WaitSema().
Referenced by usb_bulk_get_max_lun(), usb_bulk_manage_status(), usb_bulk_reset(), usb_bulk_transfer(), and usb_mass_update().
usb_bulk_command()
static int usb_bulk_command (mass_dev * dev, cbw_packet * packet) static
Definition at line 365 of file usb_mass.c.
{
         int ret;
         usb_callback_data cb_data;
         if(dev->status & USBMASS_DEV_STAT_ERR){
                 M_DEBUG("Rejecting I/O to offline device %d.\n", dev->devId);
                 return -1;
         }
         cb_data.sema = dev->ioSema;
         ret =  sceUsbdBulkTransfer(
                 dev->bulkEpO,           //bulk output pipe
                 packet,                 //data ptr
                 31,     //data length
                 usb_callback,
                 (void*)&cb_data
         );
         if (ret == USB_RC_OK) {
                 WaitSema(cb_data.sema);
                 ret = cb_data.returnCode;
         }
         if (ret != USB_RC_OK) {
                 M_DEBUG("ERROR: sending bulk command %d. Calling reset recovery.\n", ret);
                 usb_bulk_reset(dev, 3);
         }
         return ret;
 }
References mass_dev::bulkEpO, mass_dev::devId, mass_dev::ioSema, M_DEBUG, usb_callback_data::returnCode, sceUsbdBulkTransfer, usb_callback_data::sema, mass_dev::status, usb_bulk_reset(), usb_callback(), USB_RC_OK, USBMASS_DEV_STAT_ERR, and WaitSema().
Referenced by usb_queue_cmd().
usb_bulk_get_max_lun()
static int usb_bulk_get_max_lun (struct scsi_interface * scsi) static
Definition at line 316 of file usb_mass.c.
 {
     mass_dev* dev = (mass_dev*)scsi->priv;
     int ret;
     usb_callback_data cb_data;
     char max_lun;
     cb_data.sema = dev->ioSema;
     //Call Bulk only mass storage reset
     ret = sceUsbdControlTransfer(
         dev->controlEp, //default pipe
         0xA1,
         0xFE,
         0,
         dev->interfaceNumber, //interface number
         1,                    //length
         &max_lun,             //data
         usb_callback,
         (void*)&cb_data);
     if (ret == USB_RC_OK) {
         WaitSema(cb_data.sema);
         ret = cb_data.returnCode;
     }
     if (ret == USB_RC_OK) {
         ret = max_lun;
     } else {
         //Devices that do not support multiple LUNs may STALL this command.
         usb_bulk_clear_halt(dev, USB_BLK_EP_IN);
         usb_bulk_clear_halt(dev, USB_BLK_EP_OUT);
         ret = -ret;
     }
     return ret;
 }
References mass_dev::controlEp, mass_dev::interfaceNumber, mass_dev::ioSema, scsi_interface::priv, sceUsbdControlTransfer(), usb_callback_data::sema, USB_BLK_EP_IN, USB_BLK_EP_OUT, usb_bulk_clear_halt(), usb_callback(), USB_RC_OK, and WaitSema().
Referenced by usb_mass_init().
usb_bulk_manage_status()
static int usb_bulk_manage_status (mass_dev * dev, unsigned int tag) static
Definition at line 293 of file usb_mass.c.
{
         int ret;
         csw_packet csw;
         //XPRINTF("USBHDFSD: usb_bulk_manage_status 1 ...\n");
         ret = usb_bulk_status(dev, &csw, tag); /* Attempt to read CSW from bulk in endpoint */
         if (ret != USB_RC_OK) { /* STALL bulk in  -OR- Bulk error */
                 usb_bulk_clear_halt(dev, USB_BLK_EP_IN); /* clear the stall condition for bulk in */
                 M_DEBUG("ERROR: usb_bulk_manage_status error %d ...\n", ret);
                 ret = usb_bulk_status(dev, &csw, tag); /* Attempt to read CSW from bulk in endpoint */
         }
         /* CSW not valid  or stalled or phase error */
         if (ret != USB_RC_OK || csw.signature != CSW_TAG || csw.tag != tag || csw.status == 2) {
                 M_DEBUG("ERROR: usb_bulk_manage_status call reset recovery ...\n");
                 usb_bulk_reset(dev, 3); /* Perform reset recovery */
         }
         return((ret == USB_RC_OK && csw.signature == CSW_TAG && csw.tag == tag) ? csw.status : -1);
 }
References CSW_TAG, M_DEBUG, csw_packet::signature, csw_packet::status, csw_packet::tag, USB_BLK_EP_IN, usb_bulk_clear_halt(), usb_bulk_reset(), usb_bulk_status(), and USB_RC_OK.
Referenced by usb_queue_cmd().
usb_bulk_probeEndpoint()
static void usb_bulk_probeEndpoint (int devId, mass_dev * dev, UsbEndpointDescriptor * endpoint) static
Definition at line 537 of file usb_mass.c.
 {
     if (endpoint->bmAttributes == USB_ENDPOINT_XFER_BULK) {
         /* out transfer */
         if ((endpoint->bEndpointAddress & USB_ENDPOINT_DIR_MASK) == USB_DIR_OUT && dev->bulkEpO < 0) {
             dev->bulkEpO = sceUsbdOpenPipeAligned(devId, endpoint);
             M_DEBUG("register Output endpoint id =%i addr=%02X packetSize=%i\n", dev->bulkEpO, endpoint->bEndpointAddress, (unsigned short int)endpoint->wMaxPacketSizeHB << 8 | endpoint->wMaxPacketSizeLB);
         } else
             /* in transfer */
             if ((endpoint->bEndpointAddress & USB_ENDPOINT_DIR_MASK) == USB_DIR_IN && dev->bulkEpI < 0) {
             dev->bulkEpI = sceUsbdOpenPipeAligned(devId, endpoint);
             M_DEBUG("register Input endpoint id =%i addr=%02X packetSize=%i\n", dev->bulkEpI, endpoint->bEndpointAddress, (unsigned short int)endpoint->wMaxPacketSizeHB << 8 | endpoint->wMaxPacketSizeLB);
         }
     }
 }
References UsbEndpointDescriptor::bEndpointAddress, UsbEndpointDescriptor::bmAttributes, mass_dev::bulkEpI, mass_dev::bulkEpO, usbmass_cmd::dev, M_DEBUG, sceUsbdOpenPipeAligned(), USB_DIR_IN, USB_DIR_OUT, USB_ENDPOINT_DIR_MASK, USB_ENDPOINT_XFER_BULK, UsbEndpointDescriptor::wMaxPacketSizeHB, and UsbEndpointDescriptor::wMaxPacketSizeLB.
Referenced by usb_mass_connect().
usb_bulk_reset()
static void usb_bulk_reset (mass_dev * dev, int mode) static
Definition at line 211 of file usb_mass.c.
{
         int ret;
         usb_callback_data cb_data;
         cb_data.sema = dev->ioSema;
         //Call Bulk only mass storage reset
         ret = sceUsbdControlTransfer(
                 dev->controlEp,                 //default pipe
                 0x21,                   //bulk reset
                 0xFF,
                 0,
                 dev->interfaceNumber, //interface number
                 0,                      //length
                 NULL,                   //data
                 usb_callback,
                 (void*) &cb_data
                 );
         if (ret == USB_RC_OK) {
                 WaitSema(cb_data.sema);
                 ret = cb_data.returnCode;
         }
         if(ret == USB_RC_OK) {
                 //clear bulk-in endpoint
                 if (mode & 0x01)
                         ret = usb_bulk_clear_halt(dev, USB_BLK_EP_IN);
         }
         if(ret == USB_RC_OK) {
                 //clear bulk-out endpoint
                 if (mode & 0x02)
                         ret = usb_bulk_clear_halt(dev, USB_BLK_EP_OUT);
         }
         if(ret != USB_RC_OK){
                 M_DEBUG("ERROR: sending reset %d to device %d.\n", ret, dev->devId);
                 dev->status |= USBMASS_DEV_STAT_ERR;
         }
 }
References mass_dev::controlEp, mass_dev::devId, mass_dev::interfaceNumber, mass_dev::ioSema, M_DEBUG, NULL, usb_callback_data::returnCode, sceUsbdControlTransfer(), usb_callback_data::sema, mass_dev::status, USB_BLK_EP_IN, USB_BLK_EP_OUT, usb_bulk_clear_halt(), usb_callback(), USB_RC_OK, USBMASS_DEV_STAT_ERR, and WaitSema().
Referenced by usb_bulk_command(), and usb_bulk_manage_status().
usb_bulk_status()
static int usb_bulk_status (mass_dev * dev, csw_packet * csw, unsigned int tag) static
Definition at line 250 of file usb_mass.c.
{
         int ret;
         usb_callback_data cb_data;
         cb_data.sema = dev->ioSema;
         csw->signature = CSW_TAG;
         csw->tag = tag;
         csw->dataResidue = 0;
         csw->status = 0;
         ret = sceUsbdBulkTransfer(
                 dev->bulkEpI,           //bulk input pipe
                 csw,                    //data ptr
                 13,     //data length
                 usb_callback,
                 (void*)&cb_data
         );
         if (ret == USB_RC_OK) {
                 WaitSema(cb_data.sema);
                 ret = cb_data.returnCode;
 #ifdef DEBUG
                 if (cb_data.returnSize != 13)
                         M_DEBUG("bulk csw.status returnSize: %i != 13\n", cb_data.returnSize);
                 if (csw->dataResidue != 0)
                         M_DEBUG("bulk csw.status residue: %i\n", csw->dataResidue);
                 M_DEBUG("bulk csw result: %d, csw.status: %i\n", ret, csw->status);
 #endif
         }
         return ret;
 }
References mass_dev::bulkEpI, CSW_TAG, csw_packet::dataResidue, mass_dev::ioSema, M_DEBUG, usb_callback_data::returnCode, usb_callback_data::returnSize, sceUsbdBulkTransfer, usb_callback_data::sema, csw_packet::signature, csw_packet::status, csw_packet::tag, usb_callback(), USB_RC_OK, and WaitSema().
Referenced by usb_bulk_manage_status().
usb_bulk_transfer()
static int usb_bulk_transfer (mass_dev * dev, int direction, void * buffer, unsigned int transferSize) static
Definition at line 396 of file usb_mass.c.
{
         int ret;
         usb_transfer_callback_data cb_data;
         cb_data.sema = dev->ioSema;
         cb_data.pipe = (direction==USB_BLK_EP_IN) ? dev->bulkEpI : dev->bulkEpO;
         cb_data.buffer = buffer;
         cb_data.remaining = transferSize;
         ret = perform_bulk_transfer(&cb_data);
         if (ret == USB_RC_OK) {
                 WaitSema(cb_data.sema);
                 ret = cb_data.returnCode;
         }
         if(ret != USB_RC_OK) {
                 M_DEBUG("ERROR: bulk data transfer %d. Clearing HALT state.\n", cb_data.returnCode);
                 usb_bulk_clear_halt(dev, direction);
         }
         return ret;
 }
References buffer, usb_transfer_callback_data::buffer, mass_dev::bulkEpI, mass_dev::bulkEpO, mass_dev::ioSema, M_DEBUG, perform_bulk_transfer(), usb_transfer_callback_data::pipe, usb_transfer_callback_data::remaining, usb_transfer_callback_data::returnCode, usb_transfer_callback_data::sema, USB_BLK_EP_IN, usb_bulk_clear_halt(), USB_RC_OK, and WaitSema().
Referenced by usb_queue_cmd().
usb_callback()
static void usb_callback (int resultCode, int bytes, void * arg) static
Definition at line 96 of file usb_mass.c.
 {
     usb_callback_data* data = (usb_callback_data*)arg;
     data->returnCode        = resultCode;
     data->returnSize        = bytes;
     M_DEBUG("callback: res %d, bytes %d, arg %p \n", resultCode, bytes, arg);
     SignalSema(data->sema);
 }
References arg, M_DEBUG, usb_callback_data::returnCode, usb_callback_data::returnSize, usb_callback_data::sema, and SignalSema().
Referenced by usb_bulk_clear_halt(), usb_bulk_command(), usb_bulk_get_max_lun(), usb_bulk_reset(), usb_bulk_status(), usb_set_configuration(), and usb_set_interface().
usb_mass_connect()
static int usb_mass_connect (int devId) static
Definition at line 605 of file usb_mass.c.
 {
     int i;
     int epCount;
     UsbDeviceDescriptor* device;
     UsbConfigDescriptor* config;
     UsbInterfaceDescriptor* interface;
     UsbEndpointDescriptor* endpoint;
     iop_sema_t SemaData;
     mass_dev* dev;
     M_PRINTF("connect: devId=%i\n", devId);
     dev = usb_mass_findDevice(devId, 1);
     if (dev == NULL) {
         M_PRINTF("ERROR: Unable to allocate space!\n");
         return 1;
     }
     /* only one mass device allowed */
     if (dev->devId != -1) {
         M_PRINTF("ERROR: Only one mass storage device allowed!\n");
         return 1;
     }
     dev->status  = 0;
     dev->bulkEpI = -1;
     dev->bulkEpO = -1;
     /* open the config endpoint */
     dev->controlEp = sceUsbdOpenPipe(devId, NULL);
     device = (UsbDeviceDescriptor*)sceUsbdScanStaticDescriptor(devId, NULL, USB_DT_DEVICE);
     config = (UsbConfigDescriptor*)sceUsbdScanStaticDescriptor(devId, device, USB_DT_CONFIG);
     interface = (UsbInterfaceDescriptor*)((char*)config + config->bLength); /* Get first interface */
     // store interface numbers
     dev->interfaceNumber = interface->bInterfaceNumber;
     dev->interfaceAlt    = interface->bAlternateSetting;
     epCount  = interface->bNumEndpoints;
     endpoint = (UsbEndpointDescriptor*)sceUsbdScanStaticDescriptor(devId, NULL, USB_DT_ENDPOINT);
     usb_bulk_probeEndpoint(devId, dev, endpoint);
     for (i = 1; i < epCount; i++) {
         endpoint = (UsbEndpointDescriptor*)((char*)endpoint + endpoint->bLength);
         usb_bulk_probeEndpoint(devId, dev, endpoint);
     }
     // Bail out if we do NOT have enough bulk endpoints.
     if (dev->bulkEpI < 0 || dev->bulkEpO < 0) {
         usb_mass_release(dev);
         M_PRINTF("ERROR: connect failed: not enough bulk endpoints!\n");
         return -1;
     }
     SemaData.initial = 0;
     SemaData.max     = 1;
     SemaData.option  = 0;
     SemaData.attr    = 0;
     if ((dev->ioSema = CreateSema(&SemaData)) < 0) {
         M_PRINTF("ERROR: Failed to allocate I/O semaphore\n");
         return -1;
     }
     /*store current configuration id - can't call set_configuration here */
     dev->devId    = devId;
     dev->configId = config->bConfigurationValue;
     dev->status   = USBMASS_DEV_STAT_CONN;
     M_DEBUG("connect ok: epI=%i, epO=%i\n", dev->bulkEpI, dev->bulkEpO);
     SignalSema(usb_mass_update_sema);
     return 0;
 }
References iop_sema_t::attr, UsbInterfaceDescriptor::bAlternateSetting, UsbConfigDescriptor::bConfigurationValue, UsbInterfaceDescriptor::bInterfaceNumber, UsbConfigDescriptor::bLength, UsbEndpointDescriptor::bLength, UsbInterfaceDescriptor::bNumEndpoints, mass_dev::bulkEpI, mass_dev::bulkEpO, mass_dev::configId, mass_dev::controlEp, CreateSema(), usbmass_cmd::dev, mass_dev::devId, iop_sema_t::initial, mass_dev::interfaceAlt, mass_dev::interfaceNumber, mass_dev::ioSema, M_DEBUG, M_PRINTF, iop_sema_t::max, NULL, iop_sema_t::option, sceUsbdOpenPipe(), sceUsbdScanStaticDescriptor(), SignalSema(), mass_dev::status, usb_bulk_probeEndpoint(), USB_DT_CONFIG, USB_DT_DEVICE, USB_DT_ENDPOINT, usb_mass_findDevice(), usb_mass_release(), usb_mass_update_sema, and USBMASS_DEV_STAT_CONN.
Referenced by usb_mass_init().
usb_mass_disconnect()
static int usb_mass_disconnect (int devId) static
Definition at line 697 of file usb_mass.c.
 {
     mass_dev* dev;
     dev = usb_mass_findDevice(devId, 0);
     M_PRINTF("disconnect: devId=%i\n", devId);
     if (dev == NULL) {
         M_PRINTF("ERROR: disconnect: no device storage!\n");
         return 0;
     }
     if (dev->status & USBMASS_DEV_STAT_CONN) {
         usb_mass_release(dev);
         dev->devId = -1;
         DeleteSema(dev->ioSema);
         // Should this move to the thread
         // just like the scsi_connect?
         scsi_disconnect(&dev->scsi);
     }
     return 0;
 }
References DeleteSema(), mass_dev::devId, mass_dev::ioSema, M_PRINTF, NULL, mass_dev::scsi, scsi_disconnect(), mass_dev::status, usb_mass_findDevice(), usb_mass_release(), and USBMASS_DEV_STAT_CONN.
Referenced by usb_mass_init().
usb_mass_findDevice()
static mass_dev* usb_mass_findDevice (int devId, int create) static
Definition at line 518 of file usb_mass.c.
 {
     mass_dev* dev = NULL;
     int i;
     M_DEBUG("usb_mass_findDevice devId %i\n", devId);
     for (i = 0; i < NUM_DEVICES; ++i) {
         if (g_mass_device[i].devId == devId) {
             M_DEBUG("usb_mass_findDevice exists %i\n", i);
             dev = &g_mass_device[i];
             break;
         } else if (create && dev == NULL && g_mass_device[i].devId == -1) {
             dev = &g_mass_device[i];
             break;
         }
     }
     return dev;
 }
References usbmass_cmd::dev, g_mass_device, M_DEBUG, NULL, and NUM_DEVICES.
Referenced by usb_mass_connect(), usb_mass_disconnect(), and usb_mass_probe().
usb_mass_init()
int usb_mass_init (void)
Definition at line 764 of file usb_mass.c.
 {
     iop_thread_t thread;
     iop_sema_t sema;
     int ret;
     int i;
     M_DEBUG("%s\n", __func__);
     for (i = 0; i < NUM_DEVICES; ++i) {
         g_mass_device[i].status = 0;
         g_mass_device[i].devId  = -1;
         g_mass_device[i].scsi.priv        = &g_mass_device[i];
         g_mass_device[i].scsi.name        = "usb";
         g_mass_device[i].scsi.max_sectors = 0xffff;
         g_mass_device[i].scsi.get_max_lun = usb_bulk_get_max_lun;
         g_mass_device[i].scsi.queue_cmd   = usb_queue_cmd;
     }
     sema.attr            = 0;
     sema.option          = 0;
     sema.initial         = 0;
     sema.max             = 1;
     usb_mass_update_sema = CreateSema(&sema);
     driver.next       = NULL;
     driver.prev       = NULL;
     driver.name       = "mass-stor";
     driver.probe      = usb_mass_probe;
     driver.connect    = usb_mass_connect;
     driver.disconnect = usb_mass_disconnect;
     ret = sceUsbdRegisterLdd(&driver);
     M_DEBUG("sceUsbdRegisterLdd=%i\n", ret);
     if (ret < 0) {
         M_PRINTF("ERROR: register driver failed! ret=%d\n", ret);
         return -1;
     }
     thread.attr      = TH_C;
     thread.option    = 0;
     thread.thread    = usb_mass_update;
     thread.stacksize = 2 * 1024;
     thread.priority  = 0x10;
     ret = CreateThread(&thread);
     if (ret < 0) {
         M_PRINTF("ERROR: CreateThread failed! ret=%d\n", ret);
         return -1;
     }
     ret = StartThread(ret, 0);
     if (ret < 0) {
         M_PRINTF("ERROR: StartThread failed! ret=%d\n", ret);
         DeleteThread(ret);
         return -1;
     }
     return 0;
 }
References iop_thread_t::attr, iop_sema_t::attr, sceUsbdLddOps::connect, CreateSema(), CreateThread(), DeleteThread(), mass_dev::devId, sceUsbdLddOps::disconnect, driver, g_mass_device, scsi_interface::get_max_lun, iop_sema_t::initial, M_DEBUG, M_PRINTF, iop_sema_t::max, scsi_interface::max_sectors, scsi_interface::name, sceUsbdLddOps::name, sceUsbdLddOps::next, NULL, NUM_DEVICES, iop_thread_t::option, iop_sema_t::option, sceUsbdLddOps::prev, iop_thread_t::priority, scsi_interface::priv, sceUsbdLddOps::probe, scsi_interface::queue_cmd, sceUsbdRegisterLdd(), mass_dev::scsi, iop_thread_t::stacksize, StartThread(), mass_dev::status, TH_C, iop_thread_t::thread, usb_bulk_get_max_lun(), usb_mass_connect(), usb_mass_disconnect(), usb_mass_probe(), usb_mass_update(), usb_mass_update_sema, and usb_queue_cmd().
Referenced by _start().
usb_mass_probe()
static int usb_mass_probe (int devId) static
Definition at line 553 of file usb_mass.c.
 {
     UsbDeviceDescriptor* device  = NULL;
     UsbConfigDescriptor* config  = NULL;
     UsbInterfaceDescriptor* intf = NULL;
     M_DEBUG("probe: devId=%i\n", devId);
     mass_dev* mass_device = usb_mass_findDevice(devId, 0);
     /* only one device supported */
     if ((mass_device != NULL) && (mass_device->status & USBMASS_DEV_STAT_CONN)) {
         M_PRINTF("ERROR: Only one mass storage device allowed!\n");
         return 0;
     }
     /* get device descriptor */
     device = (UsbDeviceDescriptor*)sceUsbdScanStaticDescriptor(devId, NULL, USB_DT_DEVICE);
     if (device == NULL) {
         M_DEBUG("ERROR: Couldn't get device descriptor\n");
         return 0;
     }
     /* Check if the device has at least one configuration */
     if (device->bNumConfigurations < 1) {
         return 0;
     }
     /* read configuration */
     config = (UsbConfigDescriptor*)sceUsbdScanStaticDescriptor(devId, device, USB_DT_CONFIG);
     if (config == NULL) {
         M_DEBUG("ERROR: Couldn't get configuration descriptor\n");
         return 0;
     }
     /* check that at least one interface exists */
     M_DEBUG("bNumInterfaces %d\n", config->bNumInterfaces);
     if ((config->bNumInterfaces < 1) || (config->wTotalLength < (sizeof(UsbConfigDescriptor) + sizeof(UsbInterfaceDescriptor)))) {
         M_DEBUG("ERROR: No interfaces available\n");
         return 0;
     }
     /* get interface */
     intf = (UsbInterfaceDescriptor*)((char*)config + config->bLength); /* Get first interface */
     M_DEBUG("bInterfaceClass %X bInterfaceSubClass %X bInterfaceProtocol %X\n",
         intf->bInterfaceClass, intf->bInterfaceSubClass, intf->bInterfaceProtocol);
     if ((intf->bInterfaceClass != USB_CLASS_MASS_STORAGE) || (intf->bInterfaceSubClass != USB_SUBCLASS_MASS_SCSI && intf->bInterfaceSubClass != USB_SUBCLASS_MASS_SFF_8070I) || (intf->bInterfaceProtocol != USB_PROTOCOL_MASS_BULK_ONLY) || (intf->bNumEndpoints < 2)) { //one bulk endpoint is not enough because
         return 0;                                                                                                                                                                                                                                                         //we send the CBW to te bulk out endpoint
     }
     return 1;
 }
References UsbInterfaceDescriptor::bInterfaceClass, UsbInterfaceDescriptor::bInterfaceProtocol, UsbInterfaceDescriptor::bInterfaceSubClass, UsbConfigDescriptor::bLength, UsbDeviceDescriptor::bNumConfigurations, UsbInterfaceDescriptor::bNumEndpoints, UsbConfigDescriptor::bNumInterfaces, M_DEBUG, M_PRINTF, NULL, sceUsbdScanStaticDescriptor(), mass_dev::status, USB_CLASS_MASS_STORAGE, USB_DT_CONFIG, USB_DT_DEVICE, usb_mass_findDevice(), USB_PROTOCOL_MASS_BULK_ONLY, USB_SUBCLASS_MASS_SCSI, USB_SUBCLASS_MASS_SFF_8070I, USBMASS_DEV_STAT_CONN, and UsbConfigDescriptor::wTotalLength.
Referenced by usb_mass_init().
usb_mass_release()
static void usb_mass_release (mass_dev * dev) static
Definition at line 683 of file usb_mass.c.
 {
     if (dev->bulkEpI >= 0)
         sceUsbdClosePipe(dev->bulkEpI);
     if (dev->bulkEpO >= 0)
         sceUsbdClosePipe(dev->bulkEpO);
     dev->bulkEpI   = -1;
     dev->bulkEpO   = -1;
     dev->controlEp = -1;
     dev->status    = 0;
 }
References mass_dev::bulkEpI, mass_dev::bulkEpO, mass_dev::controlEp, sceUsbdClosePipe(), and mass_dev::status.
Referenced by usb_mass_connect(), usb_mass_disconnect(), and usb_mass_update().
usb_mass_update()
static void usb_mass_update (void * arg) static
Definition at line 723 of file usb_mass.c.
 {
     int i;
     M_DEBUG("update thread running\n");
     while (1) {
         // Wait for event from USBD thread
         WaitSema(usb_mass_update_sema);
         // Connect new devices
         for (i = 0; i < NUM_DEVICES; ++i) {
             mass_dev* dev = &g_mass_device[i];
             if (dev->devId != -1 && (dev->status & USBMASS_DEV_STAT_CONN) && !(dev->status & USBMASS_DEV_STAT_CONF)) {
                 int ret;
                 if ((ret = usb_set_configuration(dev, dev->configId)) != USB_RC_OK) {
                     M_PRINTF("ERROR: sending set_configuration %d\n", ret);
                     usb_mass_release(dev);
                     continue;
                 }
                 if ((ret = usb_set_interface(dev, dev->interfaceNumber, dev->interfaceAlt)) != USB_RC_OK) {
                     M_PRINTF("ERROR: sending set_interface %d\n", ret);
                     if (ret == USB_RC_STALL) {
                         /* USB Specification 1.1, section 9.4.10: Devices that only support a default setting for the specified interface may return a STALL.
                            As with Linux, we shall clear the halt state of the interface's pipes and continue. */
                         usb_bulk_clear_halt(dev, USB_BLK_EP_IN);
                         usb_bulk_clear_halt(dev, USB_BLK_EP_OUT);
                     } else {
                         usb_mass_release(dev);
                         continue;
                     }
                 }
                 dev->status |= USBMASS_DEV_STAT_CONF;
                 scsi_connect(&dev->scsi);
             }
         }
     }
 }
References mass_dev::configId, mass_dev::devId, g_mass_device, mass_dev::interfaceAlt, mass_dev::interfaceNumber, M_DEBUG, M_PRINTF, NUM_DEVICES, mass_dev::scsi, scsi_connect(), mass_dev::status, USB_BLK_EP_IN, USB_BLK_EP_OUT, usb_bulk_clear_halt(), usb_mass_release(), usb_mass_update_sema, USB_RC_OK, USB_RC_STALL, usb_set_configuration(), usb_set_interface(), USBMASS_DEV_STAT_CONF, USBMASS_DEV_STAT_CONN, and WaitSema().
Referenced by usb_mass_init().
usb_queue_cmd()
int usb_queue_cmd (struct scsi_interface * scsi, const unsigned char * cmd, unsigned int cmd_len, unsigned char * data, unsigned int data_len, unsigned int data_wr)
Definition at line 437 of file usb_mass.c.
 {
     mass_dev* dev = (mass_dev*)scsi->priv;
     static struct usbmass_cmd ucmd;
     int result;
 #ifndef ASYNC
     int rcode;
 #endif
     static unsigned int tag = 0;
     M_DEBUG("%s\n", __func__);
     tag++;
     // Create USB command
     ucmd.dev       = dev;
     ucmd.cmd_count = 0;
     // Create CBW
     ucmd.cbw.signature          = CBW_TAG;
     ucmd.cbw.tag                = tag;
     ucmd.cbw.dataTransferLength = data_len;
     ucmd.cbw.flags              = data_wr ? 0 : 0x80;
     ucmd.cbw.lun                = 0;
     ucmd.cbw.comLength          = cmd_len;
     memcpy(ucmd.cbw.comData, cmd, cmd_len);
     // Create CSW
     ucmd.csw.signature   = CSW_TAG;
     ucmd.csw.tag         = tag;
     ucmd.csw.dataResidue = 0;
     ucmd.csw.status      = 0;
 #ifndef ASYNC
         result = -EIO;
         if(usb_bulk_command(dev, &ucmd.cbw) == USB_RC_OK){
                 if (data_len > 0)
             rcode = usb_bulk_transfer(dev, data_wr ? USB_BLK_EP_OUT : USB_BLK_EP_IN, data, data_len);
         else
             rcode = USB_RC_OK;
                 result = usb_bulk_manage_status(dev, tag);
                 if(rcode != USB_RC_OK)
             result = -EIO;
         }
         return result;
 #else
     // Send the CBW (command)
     ucmd.cmd_count++;
     result = sceUsbdBulkTransfer(dev->bulkEpO, &ucmd.cbw, 31, scsi_cmd_callback, (void*)&ucmd);
     if (result != USB_RC_OK)
         return -EIO;
     // Send/Receive data
     while (data_len > 0) {
         unsigned int tr_len = (data_len < USB_BLOCK_SIZE) ? data_len : USB_BLOCK_SIZE;
         ucmd.cmd_count++;
         result = sceUsbdBulkTransfer(data_wr ? dev->bulkEpO : dev->bulkEpI, data, tr_len, scsi_cmd_callback, (void*)&ucmd);
         if (result != USB_RC_OK)
             return -EIO;
         data_len -= tr_len;
         data += tr_len;
     }
     // Receive CSW (status)
     ucmd.cmd_count++;
     result = sceUsbdBulkTransfer(dev->bulkEpI, &ucmd.csw, 13, scsi_cmd_callback, (void*)&ucmd);
     if (result != USB_RC_OK)
         return -EIO;
     // Wait for SCSI command to finish
     WaitSema(dev->ioSema);
     if (ucmd.returnCode != USB_RC_OK)
         return -EIO;
     return 0;
 #endif
 }
References mass_dev::bulkEpI, mass_dev::bulkEpO, usbmass_cmd::cbw, CBW_TAG, usbmass_cmd::cmd_count, cbw_packet::comData, cbw_packet::comLength, usbmass_cmd::csw, CSW_TAG, csw_packet::dataResidue, cbw_packet::dataTransferLength, usbmass_cmd::dev, EIO, cbw_packet::flags, mass_dev::ioSema, cbw_packet::lun, M_DEBUG, memcpy(), scsi_interface::priv, result, sceUsbdBulkTransfer, cbw_packet::signature, csw_packet::signature, csw_packet::status, cbw_packet::tag, csw_packet::tag, USB_BLK_EP_IN, USB_BLK_EP_OUT, USB_BLOCK_SIZE, usb_bulk_command(), usb_bulk_manage_status(), usb_bulk_transfer(), USB_RC_OK, and WaitSema().
Referenced by usb_mass_init().
usb_set_configuration()
static int usb_set_configuration (mass_dev * dev, int configNumber) static
Definition at line 149 of file usb_mass.c.
 {
     int ret;
     usb_callback_data cb_data;
     cb_data.sema = dev->ioSema;
     M_DEBUG("setting configuration controlEp=%i, confNum=%i \n", dev->controlEp, configNumber);
     ret = sceUsbdSetConfiguration(dev->controlEp, configNumber, usb_callback, (void*)&cb_data);
     if (ret == USB_RC_OK) {
         WaitSema(cb_data.sema);
         ret = cb_data.returnCode;
     }
     return ret;
 }
References mass_dev::controlEp, mass_dev::ioSema, M_DEBUG, usb_callback_data::returnCode, sceUsbdSetConfiguration, usb_callback_data::sema, usb_callback(), USB_RC_OK, and WaitSema().
Referenced by usb_mass_update().
usb_set_interface()
static int usb_set_interface (mass_dev * dev, int interface, int altSetting) static
Definition at line 167 of file usb_mass.c.
 {
     int ret;
     usb_callback_data cb_data;
     cb_data.sema = dev->ioSema;
     M_DEBUG("setting interface controlEp=%i, interface=%i altSetting=%i\n", dev->controlEp, interface, altSetting);
     ret = sceUsbdSetInterface(dev->controlEp, interface, altSetting, usb_callback, (void*)&cb_data);
     if (ret == USB_RC_OK) {
         WaitSema(cb_data.sema);
         ret = cb_data.returnCode;
     }
     return ret;
 }
References mass_dev::controlEp, mass_dev::ioSema, M_DEBUG, usb_callback_data::returnCode, sceUsbdSetInterface, usb_callback_data::sema, usb_callback(), USB_RC_OK, and WaitSema().
Referenced by usb_mass_update().
usb_transfer_callback()
static void usb_transfer_callback (int resultCode, int bytes, void * arg) static
Definition at line 121 of file usb_mass.c.
 {
         int ret;
         usb_transfer_callback_data* data = (usb_transfer_callback_data*)arg;
         data->returnCode = resultCode;
         if(resultCode == USB_RC_OK)
         {       //Update transfer progress if successful.
                 data->remaining -= bytes;
                 data->buffer += bytes;
         }
         if((resultCode == USB_RC_OK) && (data->remaining > 0))
         {       //OK to continue.
                 ret = perform_bulk_transfer(data);
                 if (ret != USB_RC_OK)
                 {
                         data->returnCode = ret;
                         SignalSema(data->sema);
                 }
         }
         else
         {
                 SignalSema(data->sema);
         }
 }
References arg, usb_transfer_callback_data::buffer, perform_bulk_transfer(), usb_transfer_callback_data::remaining, usb_transfer_callback_data::returnCode, usb_transfer_callback_data::sema, SignalSema(), and USB_RC_OK.
Referenced by perform_bulk_transfer().
Variable Documentation
driver
sceUsbdLddOps driver static
Definition at line 69 of file usb_mass.c.
Referenced by usb_mass_init().
g_mass_device
mass_dev g_mass_device[NUM_DEVICES] static
Definition at line 88 of file usb_mass.c.
Referenced by usb_mass_findDevice(), usb_mass_init(), and usb_mass_update().
usb_mass_update_sema
int usb_mass_update_sema static
Definition at line 89 of file usb_mass.c.
Referenced by usb_mass_connect(), usb_mass_init(), and usb_mass_update().