ps2sdk: iop/usb/usbmass_bd/src/include/scsi.h File Reference
scsi.h File Reference
Data Structures
struct scsi_interface
Functions
int scsi_init (void)
void scsi_connect (struct scsi_interface *scsi)
void scsi_disconnect (struct scsi_interface *scsi)
Function Documentation
scsi_connect()
void scsi_connect (struct scsi_interface * scsi)
Definition at line 239 of file scsi.c.
 {
     int i;
     M_DEBUG("%s\n", __func__);
     for (i = 0; i < NUM_DEVICES; ++i) {
         if (g_scsi_bd[i].priv == NULL) {
             struct block_device* bd = &g_scsi_bd[i];
             bd->priv = scsi;
             bd->name = scsi->name;
             scsi_warmup(bd);
             bdm_connect_bd(bd);
             break;
         }
     }
 }
References bdm_connect_bd(), g_scsi_bd, M_DEBUG, block_device::name, scsi_interface::name, NULL, NUM_DEVICES, block_device::priv, scsi_interface::priv, and scsi_warmup().
scsi_disconnect()
void scsi_disconnect (struct scsi_interface * scsi)
Definition at line 258 of file scsi.c.
 {
     int i;
     M_DEBUG("%s\n", __func__);
     for (i = 0; i < NUM_DEVICES; ++i) {
         if (g_scsi_bd[i].priv == scsi) {
             struct block_device* bd = &g_scsi_bd[i];
             bdm_disconnect_bd(bd);
             bd->priv = NULL;
             break;
         }
     }
 }
References bdm_disconnect_bd(), g_scsi_bd, M_DEBUG, NULL, NUM_DEVICES, and block_device::priv.
scsi_init()
int scsi_init (void)
Definition at line 274 of file scsi.c.
 {
     int i;
     M_DEBUG("%s\n", __func__);
     for (i = 0; i < NUM_DEVICES; ++i) {
         g_scsi_bd[i].devNr = i;
         g_scsi_bd[i].parNr = 0;
         g_scsi_bd[i].priv  = NULL;
         g_scsi_bd[i].read  = scsi_read;
         g_scsi_bd[i].write = scsi_write;
         g_scsi_bd[i].flush = scsi_flush;
     }
     return 0;
 }
References block_device::devNr, block_device::flush, g_scsi_bd, M_DEBUG, NULL, NUM_DEVICES, block_device::parNr, block_device::priv, block_device::read, scsi_flush(), scsi_read(), scsi_stop(), scsi_write(), block_device::stop, and block_device::write.