ps2sdk: iop/usb/usbd/include/usbd.h File Reference
usbd.h File Reference
#include <types.h>
#include <irx.h>
Data Structures
struct UsbDeviceRequest
struct UsbHubDescriptor
struct sceUsbdLddOps
struct UsbDeviceDescriptor
struct UsbConfigDescriptor
struct UsbInterfaceDescriptor
struct UsbEndpointDescriptor
struct UsbStringDescriptor
struct sceUsbdIsochronousPswLen
struct sceUsbdMultiIsochronousRequest
Macros
#define USB_MAX_ISOCH_PACKETS 8
#define USB_CLASS_PER_INTERFACE 0 /* for DeviceClass */
#define USB_CLASS_AUDIO 1
#define USB_CLASS_COMM 2
#define USB_CLASS_HID 3
#define USB_CLASS_PHYSICAL 5
#define USB_CLASS_PRINTER 7
#define USB_CLASS_MASS_STORAGE 8
#define USB_CLASS_HUB 9
#define USB_CLASS_DATA 10
#define USB_CLASS_APP_SPEC 0xfe
#define USB_CLASS_VENDOR_SPEC 0xff
#define USB_TYPE_STANDARD (0x00 << 5)
#define USB_TYPE_CLASS (0x01 << 5)
#define USB_TYPE_VENDOR (0x02 << 5)
#define USB_TYPE_RESERVED (0x03 << 5)
#define USB_RECIP_DEVICE 0x00
#define USB_RECIP_INTERFACE 0x01
#define USB_RECIP_ENDPOINT 0x02
#define USB_RECIP_OTHER 0x03
#define USB_ENDPOINT_XFER_CONTROL 0
#define USB_ENDPOINT_XFER_ISOC 1
#define USB_ENDPOINT_XFER_BULK 2
#define USB_ENDPOINT_XFER_INT 3
#define USB_ENDPOINT_XFERTYPE_MASK 3
#define USB_REQ_GET_REPORT 0x01
#define USB_REQ_GET_IDLE 0x02
#define USB_REQ_GET_PROTOCOL 0x03
#define USB_REQ_SET_REPORT 0x09
#define USB_REQ_SET_IDLE 0x0A
#define USB_REQ_SET_PROTOCOL 0x0B
#define USB_DIR_OUT 0
#define USB_DIR_IN 0x80
#define USB_ENDPOINT_DIR_MASK 0x80
#define USB_DT_DEVICE 1
#define USB_DT_CONFIG 2
#define USB_DT_STRING 3
#define USB_DT_INTERFACE 4
#define USB_DT_ENDPOINT 5
#define USB_DT_HUB 0x29
#define USB_CLASS_HUB 9
#define USB_RT_HUB (USB_TYPE_CLASS | USB_RECIP_DEVICE)
#define USB_RT_PORT (USB_TYPE_CLASS | USB_RECIP_OTHER)
#define USB_REQ_GET_STATUS 0x00
#define USB_REQ_CLEAR_FEATURE 0x01
#define USB_REQ_SET_FEATURE 0x03
#define USB_REQ_SET_ADDRESS 0x05
#define USB_REQ_GET_DESCRIPTOR 0x06
#define USB_REQ_SET_DESCRIPTOR 0x07
#define USB_REQ_GET_CONFIGURATION 0x08
#define USB_REQ_SET_CONFIGURATION 0x09
#define USB_REQ_GET_INTERFACE 0x0A
#define USB_REQ_SET_INTERFACE 0x0B
#define USB_REQ_SYNCH_FRAME 0x0C
#define USB_RC_OK 0x000
#define USB_RC_CRC 0x001
#define USB_RC_BITSTUFF 0x002
#define USB_RC_TOGGLE 0x003
#define USB_RC_STALL 0x004
#define USB_RC_NORESPONSE 0x005
#define USB_RC_BADPID 0x006
#define USB_RC_WRONGPID 0x007
#define USB_RC_DATAOVER 0x008
#define USB_RC_DATAUNDER 0x009
#define USB_RC_BUFFOVER 0x00C
#define USB_RC_BUFFUNDER 0x00D
#define USB_RC_NOTACCESSED 0x00E
#define USB_RC_NOTACCESSED2 0x00F
#define USB_RC_BADDEV 0x101
#define USB_RC_BADPIPE 0x102
#define USB_RC_BADLENGTH 0x103
#define USB_RC_BADDRIVER 0x104
#define USB_RC_BADCONTEXT 0x105
#define USB_RC_BADALIGN 0x106
#define USB_RC_BADHUBDEPTH 0x107
#define USB_RC_ED 0x111
#define USB_RC_IOREQ 0x112
#define USB_RC_BADOPTION 0x113
#define USB_RC_BUSY 0x121
#define USB_RC_ABORTED 0x122
#define USB_RC_NOSUPPORT 0x131
#define USB_RC_UNKNOWN 0x132
#define UsbCallbackProc sceUsbdDoneCallback
#define UsbDriver sceUsbdLddOps
#define UsbIsochronousPswLen sceUsbdIsochronousPswLen
#define UsbMultiIsochronousRequest sceUsbdMultiIsochronousRequest
#define UsbMultiIsochronousDoneCallback sceUsbdMultiIsochronousDoneCallback
#define UsbRegisterDriver sceUsbdRegisterLdd
#define UsbUnregisterDriver sceUsbdUnregisterLdd
#define UsbGetDeviceStaticDescriptor sceUsbdScanStaticDescriptor
#define UsbGetDeviceLocation sceUsbdGetDeviceLocation
#define UsbSetDevicePrivateData sceUsbdSetPrivateData
#define UsbGetDevicePrivateData sceUsbdGetPrivateData
#define UsbOpenEndpoint sceUsbdOpenPipe
#define UsbOpenEndpointAligned sceUsbdOpenPipeAligned
#define UsbCloseEndpoint sceUsbdClosePipe
#define UsbTransfer sceUsbdTransferPipe
#define UsbRegisterAutoloader sceUsbdRegisterAutoloader
#define UsbUnregisterAutoloader sceUsbdUnregisterAutoloader
#define UsbChangeThreadPriority sceUsbdChangeThreadPriority
#define UsbGetReportDescriptor sceUsbdGetReportDescriptor
#define UsbMultiIsochronousTransfer sceUsbdMultiIsochronousTransfer
#define usbd_IMPORTS_start DECLARE_IMPORT_TABLE(usbd,1,1)
#define usbd_IMPORTS_end END_IMPORT_TABLE
#define I_sceUsbdRegisterLdd DECLARE_IMPORT(4, sceUsbdRegisterLdd)
#define I_sceUsbdUnregisterLdd DECLARE_IMPORT(5, sceUsbdUnregisterLdd)
#define I_sceUsbdScanStaticDescriptor DECLARE_IMPORT(6, sceUsbdScanStaticDescriptor)
#define I_sceUsbdSetPrivateData DECLARE_IMPORT(7, sceUsbdSetPrivateData)
#define I_sceUsbdGetPrivateData DECLARE_IMPORT(8, sceUsbdGetPrivateData)
#define I_sceUsbdOpenPipe DECLARE_IMPORT(9, sceUsbdOpenPipe)
#define I_sceUsbdClosePipe DECLARE_IMPORT(10, sceUsbdClosePipe)
#define I_sceUsbdTransferPipe DECLARE_IMPORT(11, sceUsbdTransferPipe)
#define I_sceUsbdOpenPipeAligned DECLARE_IMPORT(12, sceUsbdOpenPipeAligned)
#define I_sceUsbdGetDeviceLocation DECLARE_IMPORT(13, sceUsbdGetDeviceLocation)
#define I_sceUsbdRegisterAutoloader DECLARE_IMPORT(14, sceUsbRegisterAutoloader)
#define I_sceUsbdUnregisterAutoloader DECLARE_IMPORT(15, sceUsbUnregisterAutoloader)
#define I_sceUsbdChangeThreadPriority DECLARE_IMPORT(16, sceUsbdChangeThreadPriority)
#define I_sceUsbdGetReportDescriptor DECLARE_IMPORT(17, sceUsbdGetReportDescriptor)
#define I_sceUsbdMultiIsochronousTransfer DECLARE_IMPORT(18, sceUsbdMultiIsochronousTransfer)
Typedefs
typedef void(* sceUsbdDoneCallback) (int result, int count, void *arg)
typedef void(* sceUsbdMultiIsochronousDoneCallback) (int result, sceUsbdMultiIsochronousRequest *req, void *arg)
Functions
int sceUsbdRegisterLdd (sceUsbdLddOps *driver)
int sceUsbdUnregisterLdd (sceUsbdLddOps *driver)
void * sceUsbdScanStaticDescriptor (int devId, void *data, u8 type)
int sceUsbdGetDeviceLocation (int devId, u8 *path)
int sceUsbdSetPrivateData (int devId, void *data)
void * sceUsbdGetPrivateData (int devId)
int sceUsbdOpenPipe (int devId, UsbEndpointDescriptor *desc)
int sceUsbdOpenPipeAligned (int devId, UsbEndpointDescriptor *desc)
int sceUsbdClosePipe (int id)
int sceUsbdTransferPipe (int id, void *data, u32 len, void *option, sceUsbdDoneCallback callback, void *cbArg)
int sceUsbdRegisterAutoloader (sceUsbdLddOps *drv)
int sceUsbdUnregisterAutoloader (void)
int sceUsbdChangeThreadPriority (int prio1, int prio2)
int sceUsbdGetReportDescriptor (int devId, int cfgNum, int ifNum, void **desc, u32 *len)
int sceUsbdMultiIsochronousTransfer (int pipeId, sceUsbdMultiIsochronousRequest *request, sceUsbdMultiIsochronousDoneCallback callback, void *cbArg)
Detailed Description
USB Driver function prototypes and constants.
Definition in file usbd.h.
Macro Definition Documentation
I_sceUsbdChangeThreadPriority
#define I_sceUsbdChangeThreadPriority DECLARE_IMPORT(16, sceUsbdChangeThreadPriority)
Definition at line 325 of file usbd.h.
I_sceUsbdClosePipe
#define I_sceUsbdClosePipe DECLARE_IMPORT(10, sceUsbdClosePipe)
Definition at line 319 of file usbd.h.
I_sceUsbdGetDeviceLocation
#define I_sceUsbdGetDeviceLocation DECLARE_IMPORT(13, sceUsbdGetDeviceLocation)
Definition at line 322 of file usbd.h.
I_sceUsbdGetPrivateData
#define I_sceUsbdGetPrivateData DECLARE_IMPORT(8, sceUsbdGetPrivateData)
Definition at line 317 of file usbd.h.
I_sceUsbdGetReportDescriptor
#define I_sceUsbdGetReportDescriptor DECLARE_IMPORT(17, sceUsbdGetReportDescriptor)
Definition at line 326 of file usbd.h.
I_sceUsbdMultiIsochronousTransfer
#define I_sceUsbdMultiIsochronousTransfer DECLARE_IMPORT(18, sceUsbdMultiIsochronousTransfer)
Definition at line 327 of file usbd.h.
I_sceUsbdOpenPipe
#define I_sceUsbdOpenPipe DECLARE_IMPORT(9, sceUsbdOpenPipe)
Definition at line 318 of file usbd.h.
I_sceUsbdOpenPipeAligned
#define I_sceUsbdOpenPipeAligned DECLARE_IMPORT(12, sceUsbdOpenPipeAligned)
Definition at line 321 of file usbd.h.
I_sceUsbdRegisterAutoloader
#define I_sceUsbdRegisterAutoloader DECLARE_IMPORT(14, sceUsbRegisterAutoloader)
Definition at line 323 of file usbd.h.
I_sceUsbdRegisterLdd
#define I_sceUsbdRegisterLdd DECLARE_IMPORT(4, sceUsbdRegisterLdd)
Definition at line 313 of file usbd.h.
I_sceUsbdScanStaticDescriptor
#define I_sceUsbdScanStaticDescriptor DECLARE_IMPORT(6, sceUsbdScanStaticDescriptor)
Definition at line 315 of file usbd.h.
I_sceUsbdSetPrivateData
#define I_sceUsbdSetPrivateData DECLARE_IMPORT(7, sceUsbdSetPrivateData)
Definition at line 316 of file usbd.h.
I_sceUsbdTransferPipe
#define I_sceUsbdTransferPipe DECLARE_IMPORT(11, sceUsbdTransferPipe)
Definition at line 320 of file usbd.h.
I_sceUsbdUnregisterAutoloader
#define I_sceUsbdUnregisterAutoloader DECLARE_IMPORT(15, sceUsbUnregisterAutoloader)
Definition at line 324 of file usbd.h.
I_sceUsbdUnregisterLdd
#define I_sceUsbdUnregisterLdd DECLARE_IMPORT(5, sceUsbdUnregisterLdd)
Definition at line 314 of file usbd.h.
USB_CLASS_APP_SPEC
#define USB_CLASS_APP_SPEC 0xfe
Definition at line 147 of file usbd.h.
USB_CLASS_AUDIO
#define USB_CLASS_AUDIO 1
Definition at line 139 of file usbd.h.
USB_CLASS_COMM
#define USB_CLASS_COMM 2
Definition at line 140 of file usbd.h.
USB_CLASS_DATA
#define USB_CLASS_DATA 10
Definition at line 146 of file usbd.h.
USB_CLASS_HID
#define USB_CLASS_HID 3
Definition at line 141 of file usbd.h.
USB_CLASS_HUB [1/2]
#define USB_CLASS_HUB 9
Definition at line 193 of file usbd.h.
USB_CLASS_HUB [2/2]
#define USB_CLASS_HUB 9
Definition at line 193 of file usbd.h.
USB_CLASS_MASS_STORAGE
#define USB_CLASS_MASS_STORAGE 8
Definition at line 144 of file usbd.h.
USB_CLASS_PER_INTERFACE
#define USB_CLASS_PER_INTERFACE 0 /* for DeviceClass */
Definition at line 138 of file usbd.h.
USB_CLASS_PHYSICAL
#define USB_CLASS_PHYSICAL 5
Definition at line 142 of file usbd.h.
USB_CLASS_PRINTER
#define USB_CLASS_PRINTER 7
Definition at line 143 of file usbd.h.
USB_CLASS_VENDOR_SPEC
#define USB_CLASS_VENDOR_SPEC 0xff
Definition at line 148 of file usbd.h.
USB_DIR_IN
#define USB_DIR_IN 0x80
Definition at line 183 of file usbd.h.
USB_DIR_OUT
#define USB_DIR_OUT 0
Definition at line 182 of file usbd.h.
USB_DT_CONFIG
#define USB_DT_CONFIG 2
Definition at line 187 of file usbd.h.
USB_DT_DEVICE
#define USB_DT_DEVICE 1
Definition at line 186 of file usbd.h.
USB_DT_ENDPOINT
#define USB_DT_ENDPOINT 5
Definition at line 190 of file usbd.h.
USB_DT_HUB
#define USB_DT_HUB 0x29
Definition at line 191 of file usbd.h.
USB_DT_INTERFACE
#define USB_DT_INTERFACE 4
Definition at line 189 of file usbd.h.
USB_DT_STRING
#define USB_DT_STRING 3
Definition at line 188 of file usbd.h.
USB_ENDPOINT_DIR_MASK
#define USB_ENDPOINT_DIR_MASK 0x80
Definition at line 184 of file usbd.h.
USB_ENDPOINT_XFER_BULK
#define USB_ENDPOINT_XFER_BULK 2
Definition at line 168 of file usbd.h.
USB_ENDPOINT_XFER_CONTROL
#define USB_ENDPOINT_XFER_CONTROL 0
Definition at line 166 of file usbd.h.
USB_ENDPOINT_XFER_INT
#define USB_ENDPOINT_XFER_INT 3
Definition at line 169 of file usbd.h.
USB_ENDPOINT_XFER_ISOC
#define USB_ENDPOINT_XFER_ISOC 1
Definition at line 167 of file usbd.h.
USB_ENDPOINT_XFERTYPE_MASK
#define USB_ENDPOINT_XFERTYPE_MASK 3
Definition at line 170 of file usbd.h.
USB_MAX_ISOCH_PACKETS
#define USB_MAX_ISOCH_PACKETS 8
Definition at line 124 of file usbd.h.
USB_RC_ABORTED
#define USB_RC_ABORTED 0x122
Operation Aborted
Definition at line 262 of file usbd.h.
USB_RC_BADALIGN
#define USB_RC_BADALIGN 0x106
Definition at line 249 of file usbd.h.
USB_RC_BADCONTEXT
#define USB_RC_BADCONTEXT 0x105
Invalid context
Definition at line 248 of file usbd.h.
USB_RC_BADDEV
#define USB_RC_BADDEV 0x101
Invalid device ID
Definition at line 240 of file usbd.h.
USB_RC_BADDRIVER
#define USB_RC_BADDRIVER 0x104
Invalid driver
Definition at line 246 of file usbd.h.
USB_RC_BADHUBDEPTH
#define USB_RC_BADHUBDEPTH 0x107
Definition at line 250 of file usbd.h.
USB_RC_BADLENGTH
#define USB_RC_BADLENGTH 0x103
Invalid length
Definition at line 244 of file usbd.h.
USB_RC_BADOPTION
#define USB_RC_BADOPTION 0x113
Bad Option
Definition at line 257 of file usbd.h.
USB_RC_BADPID
#define USB_RC_BADPID 0x006
PID Check Failed
Definition at line 223 of file usbd.h.
USB_RC_BADPIPE
#define USB_RC_BADPIPE 0x102
Invalid pipe ID
Definition at line 242 of file usbd.h.
USB_RC_BITSTUFF
#define USB_RC_BITSTUFF 0x002
Bit Stuffing
Definition at line 215 of file usbd.h.
USB_RC_BUFFOVER
#define USB_RC_BUFFOVER 0x00C
Buffer Overrun
Definition at line 231 of file usbd.h.
USB_RC_BUFFUNDER
#define USB_RC_BUFFUNDER 0x00D
Buffer Underrun
Definition at line 233 of file usbd.h.
USB_RC_BUSY
#define USB_RC_BUSY 0x121
Device or Bus Busy
Definition at line 260 of file usbd.h.
USB_RC_CRC
#define USB_RC_CRC 0x001
Bad CRC
Definition at line 213 of file usbd.h.
USB_RC_DATAOVER
#define USB_RC_DATAOVER 0x008
Data Overrun
Definition at line 227 of file usbd.h.
USB_RC_DATAUNDER
#define USB_RC_DATAUNDER 0x009
Data Underrun
Definition at line 229 of file usbd.h.
USB_RC_ED
#define USB_RC_ED 0x111
No space for Endpoint Descriptor
Definition at line 253 of file usbd.h.
USB_RC_IOREQ
#define USB_RC_IOREQ 0x112
No space for Input/Output Request
Definition at line 255 of file usbd.h.
USB_RC_NORESPONSE
#define USB_RC_NORESPONSE 0x005
Device Is Not Responding
Definition at line 221 of file usbd.h.
USB_RC_NOSUPPORT
#define USB_RC_NOSUPPORT 0x131
Unsupported Operation (not implemented)
Definition at line 265 of file usbd.h.
USB_RC_NOTACCESSED
#define USB_RC_NOTACCESSED 0x00E
Not Accessed
Definition at line 235 of file usbd.h.
USB_RC_NOTACCESSED2
#define USB_RC_NOTACCESSED2 0x00F
Not Accessed
Definition at line 237 of file usbd.h.
USB_RC_OK
#define USB_RC_OK 0x000
No Error
Definition at line 211 of file usbd.h.
USB_RC_STALL
#define USB_RC_STALL 0x004
Endpoint Stalled
Definition at line 219 of file usbd.h.
USB_RC_TOGGLE
#define USB_RC_TOGGLE 0x003
Bad Direction Toggle
Definition at line 217 of file usbd.h.
USB_RC_UNKNOWN
#define USB_RC_UNKNOWN 0x132
Unknown Error (USBD.IRX doesn't know what went wrong)
Definition at line 267 of file usbd.h.
USB_RC_WRONGPID
#define USB_RC_WRONGPID 0x007
Unexpected PID
Definition at line 225 of file usbd.h.
USB_RECIP_DEVICE
#define USB_RECIP_DEVICE 0x00
Definition at line 161 of file usbd.h.
USB_RECIP_ENDPOINT
#define USB_RECIP_ENDPOINT 0x02
Definition at line 163 of file usbd.h.
USB_RECIP_INTERFACE
#define USB_RECIP_INTERFACE 0x01
Definition at line 162 of file usbd.h.
USB_RECIP_OTHER
#define USB_RECIP_OTHER 0x03
Definition at line 164 of file usbd.h.
USB_REQ_CLEAR_FEATURE
#define USB_REQ_CLEAR_FEATURE 0x01
Definition at line 199 of file usbd.h.
USB_REQ_GET_CONFIGURATION
#define USB_REQ_GET_CONFIGURATION 0x08
Definition at line 204 of file usbd.h.
USB_REQ_GET_DESCRIPTOR
#define USB_REQ_GET_DESCRIPTOR 0x06
Definition at line 202 of file usbd.h.
USB_REQ_GET_IDLE
#define USB_REQ_GET_IDLE 0x02
Definition at line 173 of file usbd.h.
USB_REQ_GET_INTERFACE
#define USB_REQ_GET_INTERFACE 0x0A
Definition at line 206 of file usbd.h.
USB_REQ_GET_PROTOCOL
#define USB_REQ_GET_PROTOCOL 0x03
Definition at line 174 of file usbd.h.
USB_REQ_GET_REPORT
#define USB_REQ_GET_REPORT 0x01
Definition at line 172 of file usbd.h.
USB_REQ_GET_STATUS
#define USB_REQ_GET_STATUS 0x00
Definition at line 198 of file usbd.h.
USB_REQ_SET_ADDRESS
#define USB_REQ_SET_ADDRESS 0x05
Definition at line 201 of file usbd.h.
USB_REQ_SET_CONFIGURATION
#define USB_REQ_SET_CONFIGURATION 0x09
Definition at line 205 of file usbd.h.
USB_REQ_SET_DESCRIPTOR
#define USB_REQ_SET_DESCRIPTOR 0x07
Definition at line 203 of file usbd.h.
USB_REQ_SET_FEATURE
#define USB_REQ_SET_FEATURE 0x03
Definition at line 200 of file usbd.h.
USB_REQ_SET_IDLE
#define USB_REQ_SET_IDLE 0x0A
Definition at line 176 of file usbd.h.
USB_REQ_SET_INTERFACE
#define USB_REQ_SET_INTERFACE 0x0B
Definition at line 207 of file usbd.h.
USB_REQ_SET_PROTOCOL
#define USB_REQ_SET_PROTOCOL 0x0B
Definition at line 177 of file usbd.h.
USB_REQ_SET_REPORT
#define USB_REQ_SET_REPORT 0x09
Definition at line 175 of file usbd.h.
USB_REQ_SYNCH_FRAME
#define USB_REQ_SYNCH_FRAME 0x0C
Definition at line 208 of file usbd.h.
USB_RT_HUB
#define USB_RT_HUB (USB_TYPE_CLASS | USB_RECIP_DEVICE)
Definition at line 195 of file usbd.h.
USB_RT_PORT
#define USB_RT_PORT (USB_TYPE_CLASS | USB_RECIP_OTHER)
Definition at line 196 of file usbd.h.
USB_TYPE_CLASS
#define USB_TYPE_CLASS (0x01 << 5)
Definition at line 154 of file usbd.h.
USB_TYPE_RESERVED
#define USB_TYPE_RESERVED (0x03 << 5)
Definition at line 156 of file usbd.h.
USB_TYPE_STANDARD
#define USB_TYPE_STANDARD (0x00 << 5)
Definition at line 153 of file usbd.h.
USB_TYPE_VENDOR
#define USB_TYPE_VENDOR (0x02 << 5)
Definition at line 155 of file usbd.h.
UsbCallbackProc
#define UsbCallbackProc sceUsbdDoneCallback
Definition at line 289 of file usbd.h.
UsbChangeThreadPriority
#define UsbChangeThreadPriority sceUsbdChangeThreadPriority
Definition at line 306 of file usbd.h.
UsbCloseEndpoint
#define UsbCloseEndpoint sceUsbdClosePipe
Definition at line 302 of file usbd.h.
usbd_IMPORTS_end
#define usbd_IMPORTS_end END_IMPORT_TABLE
Definition at line 311 of file usbd.h.
usbd_IMPORTS_start
#define usbd_IMPORTS_start DECLARE_IMPORT_TABLE(usbd,1,1)
Definition at line 310 of file usbd.h.
UsbDriver
#define UsbDriver sceUsbdLddOps
Definition at line 290 of file usbd.h.
UsbGetDeviceLocation
#define UsbGetDeviceLocation sceUsbdGetDeviceLocation
Definition at line 297 of file usbd.h.
UsbGetDevicePrivateData
#define UsbGetDevicePrivateData sceUsbdGetPrivateData
Definition at line 299 of file usbd.h.
UsbGetDeviceStaticDescriptor
#define UsbGetDeviceStaticDescriptor sceUsbdScanStaticDescriptor
Definition at line 296 of file usbd.h.
UsbGetReportDescriptor
#define UsbGetReportDescriptor sceUsbdGetReportDescriptor
Definition at line 307 of file usbd.h.
UsbIsochronousPswLen
#define UsbIsochronousPswLen sceUsbdIsochronousPswLen
Definition at line 291 of file usbd.h.
UsbMultiIsochronousDoneCallback
#define UsbMultiIsochronousDoneCallback sceUsbdMultiIsochronousDoneCallback
Definition at line 293 of file usbd.h.
UsbMultiIsochronousRequest
#define UsbMultiIsochronousRequest sceUsbdMultiIsochronousRequest
Definition at line 292 of file usbd.h.
UsbMultiIsochronousTransfer
#define UsbMultiIsochronousTransfer sceUsbdMultiIsochronousTransfer
Definition at line 308 of file usbd.h.
UsbOpenEndpoint
#define UsbOpenEndpoint sceUsbdOpenPipe
Definition at line 300 of file usbd.h.
UsbOpenEndpointAligned
#define UsbOpenEndpointAligned sceUsbdOpenPipeAligned
Definition at line 301 of file usbd.h.
UsbRegisterAutoloader
#define UsbRegisterAutoloader sceUsbdRegisterAutoloader
Definition at line 304 of file usbd.h.
UsbRegisterDriver
#define UsbRegisterDriver sceUsbdRegisterLdd
Definition at line 294 of file usbd.h.
UsbSetDevicePrivateData
#define UsbSetDevicePrivateData sceUsbdSetPrivateData
Definition at line 298 of file usbd.h.
UsbTransfer
#define UsbTransfer sceUsbdTransferPipe
Definition at line 303 of file usbd.h.
UsbUnregisterAutoloader
#define UsbUnregisterAutoloader sceUsbdUnregisterAutoloader
Definition at line 305 of file usbd.h.
UsbUnregisterDriver
#define UsbUnregisterDriver sceUsbdUnregisterLdd
Definition at line 295 of file usbd.h.
Typedef Documentation
sceUsbdDoneCallback
typedef void(* sceUsbdDoneCallback) (int result, int count, void *arg)
Definition at line 30 of file usbd.h.
sceUsbdMultiIsochronousDoneCallback
typedef void(* sceUsbdMultiIsochronousDoneCallback) (int result, sceUsbdMultiIsochronousRequest *req, void *arg)
Definition at line 133 of file usbd.h.
Function Documentation
sceUsbdChangeThreadPriority()
int sceUsbdChangeThreadPriority (int prio1, int prio2)
Definition at line 322 of file interface.c.
{
         int res;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return USB_RC_BADCONTEXT;
         }
         res = 0;
         if(usbConfig.hcdThreadPrio != prio1) {
                 usbConfig.hcdThreadPrio = prio1;
                 res = ChangeThreadPriority(hcdTid, prio1);
         }
         if(usbConfig.cbThreadPrio != prio2) {
                 usbConfig.cbThreadPrio = prio2;
                 res = ChangeThreadPriority(callbackTid, prio2);
         }
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References callbackTid, UsbdConfig::cbThreadPrio, ChangeThreadPriority(), UsbdConfig::hcdThreadPrio, hcdTid, SetGP(), SetModuleGP, USB_RC_BADCONTEXT, usbConfig, usbdLock(), and usbdUnlock().
sceUsbdClosePipe()
int sceUsbdClosePipe (int id)
Definition at line 211 of file interface.c.
{
         Endpoint *ep;
         int res;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return -1;
         }
         ep = fetchEndpointById(id);
         if (ep)
                 res = doCloseEndpoint(ep);
         else
                 res = USB_RC_BADPIPE;
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References doCloseEndpoint(), fetchEndpointById(), SetGP(), SetModuleGP, USB_RC_BADPIPE, usbdLock(), and usbdUnlock().
Referenced by mass_stor_release(), PS2CamDisconnect(), PS2CamSetDeviceBandwidth(), and usb_mass_release().
sceUsbdGetDeviceLocation()
int sceUsbdGetDeviceLocation (int devId, u8 * path)
Definition at line 119 of file interface.c.
{
         Device *dev;
         int res;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return USB_RC_BADCONTEXT;
         }
         dev = fetchDeviceById(devId);
         if (dev)
                 res = doGetDeviceLocation(dev, path);
         else
                 res = USB_RC_BADDEV;
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References doGetDeviceLocation(), fetchDeviceById(), SetGP(), SetModuleGP, USB_RC_BADCONTEXT, USB_RC_BADDEV, usbdLock(), and usbdUnlock().
sceUsbdGetPrivateData()
void* sceUsbdGetPrivateData (int devId)
Definition at line 165 of file interface.c.
{
         Device *dev;
         void *res = NULL;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return NULL;
         }
         dev = fetchDeviceById(devId);
         if (dev)
                 res = dev->privDataField;
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References fetchDeviceById(), NULL, Device::privDataField, SetGP(), SetModuleGP, usbdLock(), and usbdUnlock().
sceUsbdGetReportDescriptor()
int sceUsbdGetReportDescriptor (int devId, int cfgNum, int ifNum, void ** desc, u32 * len)
sceUsbdMultiIsochronousTransfer()
int sceUsbdMultiIsochronousTransfer (int pipeId, sceUsbdMultiIsochronousRequest * request, sceUsbdMultiIsochronousDoneCallback callback, void * cbArg)
sceUsbdOpenPipe()
int sceUsbdOpenPipe (int devId, UsbEndpointDescriptor * desc)
Definition at line 186 of file interface.c.
{
         Device *dev;
         Endpoint *ep;
         int res = -1;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return -1;
         }
         dev = fetchDeviceById(devId);
         if (dev) {
                 ep = doOpenEndpoint(dev, desc, 0);
                 if (ep)
                         res = ep->id;
         }
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References doOpenEndpoint(), fetchDeviceById(), Endpoint::id, SetGP(), SetModuleGP, usbdLock(), and usbdUnlock().
Referenced by mass_stor_connect(), PS2CamConnect(), PS2CamSetDeviceBandwidth(), ps2kbd_connect(), ps2mouse_connect(), usb_bulk_probeEndpoint(), and usb_mass_connect().
sceUsbdOpenPipeAligned()
int sceUsbdOpenPipeAligned (int devId, UsbEndpointDescriptor * desc)
Definition at line 297 of file interface.c.
{
         Device *dev;
         Endpoint *ep;
         int res = -1;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return -1;
         }
         dev = fetchDeviceById(devId);
         if (dev) {
                 ep = doOpenEndpoint(dev, desc, 1);
                 if (ep)
                         res = ep->id;
         }
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References doOpenEndpoint(), fetchDeviceById(), Endpoint::id, SetGP(), SetModuleGP, usbdLock(), and usbdUnlock().
Referenced by usb_bulk_probeEndpoint().
sceUsbdRegisterAutoloader()
int sceUsbdRegisterAutoloader (sceUsbdLddOps * drv)
Definition at line 47 of file interface.c.
{
         int res;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return USB_RC_BADCONTEXT;
         }
         res = doRegisterAutoLoader(drv, OldGP);
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References doRegisterAutoLoader(), SetGP(), SetModuleGP, USB_RC_BADCONTEXT, usbdLock(), and usbdUnlock().
sceUsbdRegisterLdd()
int sceUsbdRegisterLdd (sceUsbdLddOps * driver)
Definition at line 29 of file interface.c.
{
         int res;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return USB_RC_BADCONTEXT;
         }
         res = doRegisterDriver(driver, OldGP);
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References doRegisterDriver(), driver, SetGP(), SetModuleGP, USB_RC_BADCONTEXT, usbdLock(), and usbdUnlock().
Referenced by InitUSB(), PS2CamInitDriver(), ps2kbd_init(), ps2mouse_init(), and usb_mass_init().
sceUsbdScanStaticDescriptor()
void* sceUsbdScanStaticDescriptor (int devId, void * data, u8 type)
Definition at line 101 of file interface.c.
{
         void *res;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return NULL;
         }
         res = doGetDeviceStaticDescriptor(devId, data, type);
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References doGetDeviceStaticDescriptor(), NULL, SetGP(), SetModuleGP, usbdLock(), and usbdUnlock().
Referenced by mass_stor_connect(), mass_stor_probe(), PS2CamConnect(), PS2CamGetDeviceInfo(), PS2CamInitializeNewDevice(), PS2CamProbe(), PS2CamSetDeviceBandwidth(), ps2kbd_connect(), ps2kbd_probe(), ps2mouse_connect(), ps2mouse_probe(), usb_mass_connect(), and usb_mass_probe().
sceUsbdSetPrivateData()
int sceUsbdSetPrivateData (int devId, void * data)
Definition at line 142 of file interface.c.
{
         Device *dev;
         int res = USB_RC_OK;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return USB_RC_BADCONTEXT;
         }
         dev = fetchDeviceById(devId);
         if (dev)
                 dev->privDataField = data;
         else
                 res = USB_RC_BADDEV;
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References fetchDeviceById(), Device::privDataField, SetGP(), SetModuleGP, USB_RC_BADCONTEXT, USB_RC_BADDEV, USB_RC_OK, usbdLock(), and usbdUnlock().
Referenced by ps2kbd_connect(), and ps2mouse_connect().
sceUsbdTransferPipe()
int sceUsbdTransferPipe (int id, void * data, u32 len, void * option, sceUsbdDoneCallback callback, void * cbArg)
Definition at line 234 of file interface.c.
{
         UsbDeviceRequest *ctrlPkt = (UsbDeviceRequest *)option;
         IoRequest *req;
         Endpoint *ep;
         int res = 0;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return USB_RC_BADCONTEXT;
         }
         ep = fetchEndpointById(id);
         if (!ep) {
                 dbg_printf("sceUsbdTransferPipe: Endpoint %d not found\n", id);
                 res = USB_RC_BADPIPE;
         }
         if ((res == 0) && data && len) {
                 if ((((u32)(data + len - 1) >> 12) - ((u32)data >> 12)) > 1)
                         res = USB_RC_BADLENGTH;
                 else if (ep->alignFlag && ((u32)data & 3))
                         res = USB_RC_BADALIGN;
                 else if ((ep->endpointType == TYPE_ISOCHRON) && ((ep->hcEd.maxPacketSize & 0x7FF) < len))
                         res = USB_RC_BADLENGTH;
         }
         if (res == 0) {
                 req = allocIoRequest();
                 if (!req) {
                         dbg_printf("Ran out of IoReqs\n");
                         res = USB_RC_IOREQ;
                 }
         }
         if (res == 0) {
                 req->userCallbackProc = callback;
                 req->userCallbackArg = cbArg;
                 req->gpSeg = GetGP(); // gp of the calling module
                 if (ep->endpointType == TYPE_CONTROL) {
                         if (!ctrlPkt) {
                                 res = USB_RC_BADOPTION;
                                 freeIoRequest(req);
                         } else if (ctrlPkt->length != len) {
                                 res = USB_RC_BADLENGTH;
                                 freeIoRequest(req);
                         } else {
                                 res = doControlTransfer(ep, req,
                                         ctrlPkt->requesttype, ctrlPkt->request, ctrlPkt->value, ctrlPkt->index, ctrlPkt->length,
                                         data, signalCallbackThreadFunc);
                         }
                 } else {
                         if (ep->endpointType == TYPE_ISOCHRON)
                                 req->waitFrames = (u32)option;
                         res = attachIoReqToEndpoint(ep, req, data, len, signalCallbackThreadFunc);
                 }
         }
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References Endpoint::alignFlag, allocIoRequest(), attachIoReqToEndpoint(), dbg_printf, doControlTransfer(), Endpoint::endpointType, fetchEndpointById(), freeIoRequest(), GetGP(), IoRequest::gpSeg, Endpoint::hcEd, UsbDeviceRequest::index, UsbDeviceRequest::length, HcED::maxPacketSize, UsbDeviceRequest::request, UsbDeviceRequest::requesttype, SetGP(), SetModuleGP, signalCallbackThreadFunc(), TYPE_CONTROL, TYPE_ISOCHRON, USB_RC_BADALIGN, USB_RC_BADCONTEXT, USB_RC_BADLENGTH, USB_RC_BADOPTION, USB_RC_BADPIPE, USB_RC_IOREQ, usbdLock(), usbdUnlock(), IoRequest::userCallbackArg, IoRequest::userCallbackProc, UsbDeviceRequest::value, and IoRequest::waitFrames.
Referenced by sceUsbdControlTransfer().
sceUsbdUnregisterAutoloader()
int sceUsbdUnregisterAutoloader (void)
Definition at line 83 of file interface.c.
{
         int res;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return USB_RC_BADCONTEXT;
         }
         res = doUnregisterAutoLoader();
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References doUnregisterAutoLoader(), SetGP(), SetModuleGP, USB_RC_BADCONTEXT, usbdLock(), and usbdUnlock().
sceUsbdUnregisterLdd()
int sceUsbdUnregisterLdd (sceUsbdLddOps * driver)
Definition at line 65 of file interface.c.
{
         int res;
         void *OldGP;
         OldGP = SetModuleGP();
         if (usbdLock() != 0) {
                 SetGP(OldGP);
                 return USB_RC_BADCONTEXT;
         }
         res = doUnregisterDriver(driver);
         usbdUnlock();
         SetGP(OldGP);
         return res;
 }
References doUnregisterDriver(), driver, SetGP(), SetModuleGP, USB_RC_BADCONTEXT, usbdLock(), and usbdUnlock().