ps2sdk: iop/usb/usbd/src/usbdpriv.h File Reference
usbdpriv.h File Reference
#include "usbd.h"
#include "types.h"
Data Structures
struct UsbdConfig
struct TimerCbStruct
struct IoRequest
struct Device
struct HcTD
struct HcIsoTD
struct HcED
struct Endpoint
struct UsbHub
struct HcCA
struct OhciRegs
struct MemoryPool
Macros
#define OHCI_REG_BASE 0xBF801600
#define dbg_printf(a...) (void)0
#define READ_UINT16(a) (((u8*)a)[0] | (((u8 *)a)[1] << 8))
#define GENTD_QUEUE 1
#define ISOTD_QUEUE 2
#define TYPE_CONTROL 0x3F
#define TYPE_BULK 0x40
#define TYPE_ISOCHRON 0x41
#define DEVICE_NOTCONNECTED 0
#define DEVICE_CONNECTED 1
#define DEVICE_RESETDELAYED 2
#define DEVICE_RESETPENDING 3
#define DEVICE_RESETCOMPLETE 4
#define DEVICE_READY 5
#define PORT_CONNECTION 0
#define PORT_ENABLE 1
#define PORT_SUSPEND 2
#define PORT_OVER_CURRENT 3
#define PORT_RESET 4
#define PORT_POWER 8
#define PORT_LOW_SPEED 9
#define C_HUB_LOCAL_POWER 0
#define C_HUB_OVER_CURRENT 1
#define C_PORT_CONNECTION 16
#define C_PORT_ENABLE 17
#define C_PORT_SUSPEND 18
#define C_PORT_OVER_CURRENT 19
#define C_PORT_RESET 20
#define BIT(x) (1 << (x))
#define C_PORT_FLAGS (BIT(C_PORT_CONNECTION) | BIT(C_PORT_ENABLE) | BIT(C_PORT_SUSPEND) | BIT(C_PORT_OVER_CURRENT) | BIT(C_PORT_RESET))
#define HCED_DIR_OUT BIT(11)
#define HCED_DIR_IN BIT(12)
#define HCED_SPEED BIT(13)
#define HCED_SKIP BIT(14)
#define HCED_ISOC BIT(15)
#define HCED_DIR_MASK (HCED_DIR_OUT | HCED_DIR_IN)
#define ED_HALTED(a) ((u32)((a).tdHead) & 1)
#define ED_SKIPPED(a) ((u32)((a).hcArea) & HCED_SKIP)
#define TD_HCAREA(CC, T, DI, DP, R) (((CC) << 12) | ((T) << 8) | ((DI) << 5) | ((DP) << 3) | ((R) << 2))
#define TD_SETUP 0
#define TD_OUT 1
#define TD_IN 2
#define OHCI_INT_SO BIT(0)
#define OHCI_INT_WDH BIT(1)
#define OHCI_INT_SF BIT(2)
#define OHCI_INT_RD BIT(3)
#define OHCI_INT_UE BIT(4)
#define OHCI_INT_FNO BIT(5)
#define OHCI_INT_RHSC BIT(6)
#define OHCI_INT_OC BIT(30)
#define OHCI_INT_MIE BIT(31)
#define OHCI_COM_HCR BIT(0)
#define OHCI_COM_CLF BIT(1)
#define OHCI_COM_BLF BIT(2)
#define OHCI_CTR_PLE BIT(2)
#define OHCI_CTR_IE BIT(3)
#define OHCI_CTR_CLE BIT(4)
#define OHCI_CTR_BLE BIT(5)
#define OHCI_CTR_USB_RESET (0 << 6)
#define OHCI_CTR_USB_RESUME (1 << 6)
#define OHCI_CTR_USB_OPERATIONAL (2 << 6)
#define OHCI_CTR_USB_SUSPEND (3 << 6)
Typedefs
typedef void(* TimerCallback) (void *arg)
typedef void(* InternCallback) (struct _ioRequest *arg)
Functions
int usbdLock (void)
int usbdUnlock (void)
int doGetDeviceLocation (Device *dev, u8 *path)
void processDoneQueue_IsoTd (HcIsoTD *arg)
void processDoneQueue_GenTd (HcTD *arg)
void handleTimerList (void)
Variables
UsbdConfig usbConfig
Detailed Description
USB Driver function prototypes and constants.
Definition in file usbdpriv.h.
Macro Definition Documentation
BIT
#define BIT (x) (1 << (x))
Definition at line 262 of file usbdpriv.h.
C_HUB_LOCAL_POWER
#define C_HUB_LOCAL_POWER 0
Definition at line 253 of file usbdpriv.h.
C_HUB_OVER_CURRENT
#define C_HUB_OVER_CURRENT 1
Definition at line 254 of file usbdpriv.h.
C_PORT_CONNECTION
#define C_PORT_CONNECTION 16
Definition at line 256 of file usbdpriv.h.
C_PORT_ENABLE
#define C_PORT_ENABLE 17
Definition at line 257 of file usbdpriv.h.
C_PORT_FLAGS
#define C_PORT_FLAGS (BIT(C_PORT_CONNECTION) | BIT(C_PORT_ENABLE) | BIT(C_PORT_SUSPEND) | BIT(C_PORT_OVER_CURRENT) | BIT(C_PORT_RESET))
Definition at line 264 of file usbdpriv.h.
C_PORT_OVER_CURRENT
#define C_PORT_OVER_CURRENT 19
Definition at line 259 of file usbdpriv.h.
C_PORT_RESET
#define C_PORT_RESET 20
Definition at line 260 of file usbdpriv.h.
C_PORT_SUSPEND
#define C_PORT_SUSPEND 18
Definition at line 258 of file usbdpriv.h.
dbg_printf
#define dbg_printf (a...) (void)0
Definition at line 27 of file usbdpriv.h.
DEVICE_CONNECTED
#define DEVICE_CONNECTED 1
Definition at line 239 of file usbdpriv.h.
DEVICE_NOTCONNECTED
#define DEVICE_NOTCONNECTED 0
Definition at line 238 of file usbdpriv.h.
DEVICE_READY
#define DEVICE_READY 5
Definition at line 243 of file usbdpriv.h.
DEVICE_RESETCOMPLETE
#define DEVICE_RESETCOMPLETE 4
Definition at line 242 of file usbdpriv.h.
DEVICE_RESETDELAYED
#define DEVICE_RESETDELAYED 2
Definition at line 240 of file usbdpriv.h.
DEVICE_RESETPENDING
#define DEVICE_RESETPENDING 3
Definition at line 241 of file usbdpriv.h.
ED_HALTED
#define ED_HALTED (a) ((u32)((a).tdHead) & 1)
Definition at line 273 of file usbdpriv.h.
ED_SKIPPED
#define ED_SKIPPED (a) ((u32)((a).hcArea) & HCED_SKIP)
Definition at line 274 of file usbdpriv.h.
GENTD_QUEUE
#define GENTD_QUEUE 1
Definition at line 231 of file usbdpriv.h.
HCED_DIR_IN
#define HCED_DIR_IN BIT(12)
Definition at line 267 of file usbdpriv.h.
HCED_DIR_MASK
#define HCED_DIR_MASK (HCED_DIR_OUT | HCED_DIR_IN)
Definition at line 271 of file usbdpriv.h.
HCED_DIR_OUT
#define HCED_DIR_OUT BIT(11)
Definition at line 266 of file usbdpriv.h.
HCED_ISOC
#define HCED_ISOC BIT(15)
Definition at line 270 of file usbdpriv.h.
HCED_SKIP
#define HCED_SKIP BIT(14)
Definition at line 269 of file usbdpriv.h.
HCED_SPEED
#define HCED_SPEED BIT(13)
Definition at line 268 of file usbdpriv.h.
ISOTD_QUEUE
#define ISOTD_QUEUE 2
Definition at line 232 of file usbdpriv.h.
OHCI_COM_BLF
#define OHCI_COM_BLF BIT(2)
Definition at line 294 of file usbdpriv.h.
OHCI_COM_CLF
#define OHCI_COM_CLF BIT(1)
Definition at line 293 of file usbdpriv.h.
OHCI_COM_HCR
#define OHCI_COM_HCR BIT(0)
Definition at line 292 of file usbdpriv.h.
OHCI_CTR_BLE
#define OHCI_CTR_BLE BIT(5)
Definition at line 299 of file usbdpriv.h.
OHCI_CTR_CLE
#define OHCI_CTR_CLE BIT(4)
Definition at line 298 of file usbdpriv.h.
OHCI_CTR_IE
#define OHCI_CTR_IE BIT(3)
Definition at line 297 of file usbdpriv.h.
OHCI_CTR_PLE
#define OHCI_CTR_PLE BIT(2)
Definition at line 296 of file usbdpriv.h.
OHCI_CTR_USB_OPERATIONAL
#define OHCI_CTR_USB_OPERATIONAL (2 << 6)
Definition at line 302 of file usbdpriv.h.
OHCI_CTR_USB_RESET
#define OHCI_CTR_USB_RESET (0 << 6)
Definition at line 300 of file usbdpriv.h.
OHCI_CTR_USB_RESUME
#define OHCI_CTR_USB_RESUME (1 << 6)
Definition at line 301 of file usbdpriv.h.
OHCI_CTR_USB_SUSPEND
#define OHCI_CTR_USB_SUSPEND (3 << 6)
Definition at line 303 of file usbdpriv.h.
OHCI_INT_FNO
#define OHCI_INT_FNO BIT(5)
Definition at line 287 of file usbdpriv.h.
OHCI_INT_MIE
#define OHCI_INT_MIE BIT(31)
Definition at line 290 of file usbdpriv.h.
OHCI_INT_OC
#define OHCI_INT_OC BIT(30)
Definition at line 289 of file usbdpriv.h.
OHCI_INT_RD
#define OHCI_INT_RD BIT(3)
Definition at line 285 of file usbdpriv.h.
OHCI_INT_RHSC
#define OHCI_INT_RHSC BIT(6)
Definition at line 288 of file usbdpriv.h.
OHCI_INT_SF
#define OHCI_INT_SF BIT(2)
Definition at line 284 of file usbdpriv.h.
OHCI_INT_SO
#define OHCI_INT_SO BIT(0)
Definition at line 282 of file usbdpriv.h.
OHCI_INT_UE
#define OHCI_INT_UE BIT(4)
Definition at line 286 of file usbdpriv.h.
OHCI_INT_WDH
#define OHCI_INT_WDH BIT(1)
Definition at line 283 of file usbdpriv.h.
OHCI_REG_BASE
#define OHCI_REG_BASE 0xBF801600
Definition at line 22 of file usbdpriv.h.
PORT_CONNECTION
#define PORT_CONNECTION 0
Definition at line 245 of file usbdpriv.h.
PORT_ENABLE
#define PORT_ENABLE 1
Definition at line 246 of file usbdpriv.h.
PORT_LOW_SPEED
#define PORT_LOW_SPEED 9
Definition at line 251 of file usbdpriv.h.
PORT_OVER_CURRENT
#define PORT_OVER_CURRENT 3
Definition at line 248 of file usbdpriv.h.
PORT_POWER
#define PORT_POWER 8
Definition at line 250 of file usbdpriv.h.
PORT_RESET
#define PORT_RESET 4
Definition at line 249 of file usbdpriv.h.
PORT_SUSPEND
#define PORT_SUSPEND 2
Definition at line 247 of file usbdpriv.h.
READ_UINT16
#define READ_UINT16 (a) (((u8*)a)[0] | (((u8 *)a)[1] << 8))
Definition at line 30 of file usbdpriv.h.
TD_HCAREA
#define TD_HCAREA (CC, T, DI, DP, R) (((CC) << 12) | ((T) << 8) | ((DI) << 5) | ((DP) << 3) | ((R) << 2))
Definition at line 276 of file usbdpriv.h.
TD_IN
#define TD_IN 2
Definition at line 280 of file usbdpriv.h.
TD_OUT
#define TD_OUT 1
Definition at line 279 of file usbdpriv.h.
TD_SETUP
#define TD_SETUP 0
Definition at line 278 of file usbdpriv.h.
TYPE_BULK
#define TYPE_BULK 0x40
Definition at line 235 of file usbdpriv.h.
TYPE_CONTROL
#define TYPE_CONTROL 0x3F
Definition at line 234 of file usbdpriv.h.
TYPE_ISOCHRON
#define TYPE_ISOCHRON 0x41
Definition at line 236 of file usbdpriv.h.
Typedef Documentation
InternCallback
typedef void(* InternCallback) (struct _ioRequest *arg)
Definition at line 58 of file usbdpriv.h.
TimerCallback
typedef void(* TimerCallback) (void *arg)
Definition at line 57 of file usbdpriv.h.
Function Documentation
doGetDeviceLocation()
int doGetDeviceLocation (Device * dev, u8 * path)
Definition at line 58 of file usbd.c.
{
         u8 tempPath[6];
         int count, cpCount;
         for (count = 0; (count < 6) && (dev != memPool.deviceTreeRoot); count++) {
                 tempPath[count] = dev->attachedToPortNo;
                 dev = dev->parent;
         }
         if (dev == memPool.deviceTreeRoot) {
                 for (cpCount = 0; cpCount < 7; cpCount++) {
                         if (cpCount < count)
                                 path[cpCount] = tempPath[count - (cpCount + 1)];
                         else
                                 path[cpCount] = 0;
                 }
                 return 0;
         } else
                 return USB_RC_BADHUBDEPTH;
 }
References Device::attachedToPortNo, MemoryPool::deviceTreeRoot, memPool, Device::parent, and USB_RC_BADHUBDEPTH.
Referenced by sceUsbdGetDeviceLocation().
handleTimerList()
void handleTimerList (void)
Definition at line 234 of file usbd.c.
{
         TimerCbStruct *timer = memPool.timerListStart;
         if (timer) {
                 if (timer->delayCount > 0)
                         timer->delayCount--;
                 while (memPool.timerListStart && (memPool.timerListStart->delayCount == 0)) {
                         dbg_printf("timer expired\n");
                         timer = memPool.timerListStart;
                         memPool.timerListStart = timer->next;
                         if (timer->next)
                                 timer->next->prev = NULL;
                         else
                                 memPool.timerListEnd = NULL;
                         timer->next = timer->prev = NULL;
                         timer->isActive = 0;
                         timer->callbackProc(timer->callbackArg);
                 }
         }
         // disable SOF interrupts if there are no timers left
         if (memPool.timerListStart == NULL)
                 memPool.ohciRegs->HcInterruptDisable = OHCI_INT_SF;
 }
References TimerCbStruct::callbackArg, TimerCbStruct::callbackProc, dbg_printf, TimerCbStruct::delayCount, OhciRegs::HcInterruptDisable, TimerCbStruct::isActive, memPool, TimerCbStruct::next, NULL, OHCI_INT_SF, MemoryPool::ohciRegs, TimerCbStruct::prev, MemoryPool::timerListEnd, and MemoryPool::timerListStart.
Referenced by hcdProcessIntr().
processDoneQueue_GenTd()
void processDoneQueue_GenTd (HcTD * arg)
Definition at line 153 of file usbd.c.
{
         IoRequest *req;
         IoRequest *firstElem = NULL, *lastElem = NULL;
         u32 hcRes;
         if ((req = memPool.hcTdToIoReqLUT[arg - memPool.hcTdBuf])) {
                 memPool.hcTdToIoReqLUT[arg - memPool.hcTdBuf] = NULL;
                 u32 tdHcArea = arg->HcArea;
                 if (arg->bufferEnd && (tdHcArea & 0x180000)) { // dir != SETUP
                         if (arg->curBufPtr == 0) // transfer successful
                                 req->transferedBytes = req->length;
                         else
                                 req->transferedBytes = (u8 *)arg->curBufPtr - (u8 *)req->destPtr;
                 }
                 hcRes = tdHcArea >> 28;
                 freeTd(arg);
                 if (req->resultCode == USB_RC_OK)
                         req->resultCode = hcRes;
                 if (hcRes || ((tdHcArea & 0xE00000) != 0xE00000)) { // E00000: interrupts disabled
                         req->prev = lastElem;
                         if (lastElem)
                                 lastElem->next = req;
                         else
                                 firstElem = req;
                         req->next = NULL;
                         lastElem = req;
                 }
                 HcED *ed = &req->correspEndpoint->hcEd;
                 if (hcRes && ED_HALTED(req->correspEndpoint->hcEd)) {
                         HcTD *tdListPos = (HcTD*)((u32)ed->tdHead & ~0xF);
                         while (tdListPos && (tdListPos != ed->tdTail)) {
                                 HcTD *nextTd = tdListPos->next;
                                 freeTd(tdListPos);
                                 IoRequest *req = memPool.hcTdToIoReqLUT[tdListPos - memPool.hcTdBuf];
                                 if (req) {
                                         memPool.hcTdToIoReqLUT[tdListPos - memPool.hcTdBuf] = NULL;
                                         IoRequest *listPos;
                                         for (listPos = firstElem; listPos != NULL; listPos = listPos->next)
                                                 if (listPos == req)
                                                         break;
                                         if (!listPos) {
                                                 req->resultCode = USB_RC_ABORTED;
                                                 req->prev = lastElem;
                                                 if (lastElem)
                                                         lastElem->next = req;
                                                 else
                                                         firstElem = req;
                                                 req->next = NULL;
                                                 lastElem = req;
                                         }
                                 }
                                 tdListPos = nextTd;
                         }
                         ed->tdHead = ed->tdTail;
                 }
                 IoRequest *pos = firstElem;
                 while (pos) {
                         pos->busyFlag = 0;
                         Device *dev = pos->correspEndpoint->correspDevice;
                         IoRequest *next = pos->next;
                         if (dev) {
                                 if (pos->callbackProc)
                                         pos->callbackProc(pos);
                         } else
                                 freeIoRequest(pos);
                         pos = next;
                 }
                 checkTdQueue(GENTD_QUEUE);
         }
 }
References arg, checkTdQueue(), IoRequest::correspEndpoint, IoRequest::destPtr, ED_HALTED, freeIoRequest(), freeTd(), GENTD_QUEUE, MemoryPool::hcTdBuf, MemoryPool::hcTdToIoReqLUT, IoRequest::length, memPool, irx_export_table::next, IoRequest::next, HcTD::next, NULL, pos, IoRequest::prev, IoRequest::resultCode, HcED::tdHead, HcED::tdTail, IoRequest::transferedBytes, USB_RC_ABORTED, and USB_RC_OK.
Referenced by hcdProcessIntr().
processDoneQueue_IsoTd()
void processDoneQueue_IsoTd (HcIsoTD * arg)
Definition at line 77 of file usbd.c.
{
         u32 tdHcRes = arg->hcArea >> 28;
         u32 pswRes = arg->psw[0] >> 12;
         u32 pswOfs = arg->psw[0] & 0x7FF;
         IoRequest *listStart = NULL, *listEnd = NULL;
         IoRequest *req = memPool.hcIsoTdToIoReqLUT[arg - memPool.hcIsoTdBuf];
         if (!req)
                 return;
         memPool.hcIsoTdToIoReqLUT[arg - memPool.hcIsoTdBuf] = NULL;
         freeIsoTd(arg);
         req->transferedBytes = 0;
         req->resultCode = (pswRes << 4) | tdHcRes;
         if ((tdHcRes == USB_RC_OK) && ((pswRes == USB_RC_OK) || (pswRes == USB_RC_DATAUNDER))) {
                 if ((req->correspEndpoint->hcEd.hcArea & HCED_DIR_MASK) == HCED_DIR_IN)
                         req->transferedBytes = pswOfs;
                 else
                         req->transferedBytes = req->length;
         }
         req->prev = listEnd;
         if (listEnd)
                 listEnd->next = req;
         else
                 listStart = req;
         req->next = NULL;
         listEnd = req;
         HcED *ed = &req->correspEndpoint->hcEd;
         if (ED_HALTED(req->correspEndpoint->hcEd)) {
                 HcIsoTD *curTd = (HcIsoTD *)((u32)ed->tdHead & ~0xF);
                 while (curTd && (curTd != (HcIsoTD*)ed->tdTail)) {
                         HcIsoTD *nextTd = curTd->next;
                         freeIsoTd(curTd);
                         IoRequest *req = memPool.hcIsoTdToIoReqLUT[curTd - memPool.hcIsoTdBuf];
                         if (req) {
                                 memPool.hcIsoTdToIoReqLUT[arg - memPool.hcIsoTdBuf] = NULL;
                                 IoRequest *listPos;
                                 for (listPos = listStart; listPos != NULL; listPos = listPos->next)
                                         if (listPos == req)
                                                 break;
                                 if (listPos == NULL) {
                                         req->resultCode = USB_RC_ABORTED;
                                         req->prev = listEnd;
                                         if (listEnd)
                                                 listEnd->next = req;
                                         else
                                                 listStart = req;
                                         req->next = NULL;
                                         listEnd = req;
                                 }
                         }
                         curTd = nextTd;
                 }
                 ed->tdHead = ed->tdTail;
         }
         IoRequest *listPos = listStart;
         while (listPos) {
                 IoRequest *listNext = listPos->next;
                 listPos->busyFlag = 0;
                 if (listPos->correspEndpoint->correspDevice) {
                         if (listPos->callbackProc)
                                 listPos->callbackProc(listPos);
                 } else
                         freeIoRequest(listPos);
                 listPos = listNext;
         }
         checkTdQueue(ISOTD_QUEUE);
 }
References arg, IoRequest::busyFlag, IoRequest::callbackProc, checkTdQueue(), IoRequest::correspEndpoint, ED_HALTED, freeIoRequest(), freeIsoTd(), HCED_DIR_IN, HCED_DIR_MASK, MemoryPool::hcIsoTdBuf, MemoryPool::hcIsoTdToIoReqLUT, ISOTD_QUEUE, IoRequest::length, memPool, IoRequest::next, HcIsoTD::next, NULL, IoRequest::prev, IoRequest::resultCode, HcED::tdHead, HcED::tdTail, IoRequest::transferedBytes, USB_RC_ABORTED, USB_RC_DATAUNDER, and USB_RC_OK.
Referenced by hcdProcessIntr().
usbdLock()
int usbdLock (void)
Definition at line 50 of file usbd.c.
                    {
         return WaitSema(usbdSema);
 }
References usbdSema, and WaitSema().
Referenced by callbackThreadFunc(), callUsbDriverFunc(), hcdIrqThread(), sceUsbdChangeThreadPriority(), sceUsbdClosePipe(), sceUsbdGetDeviceLocation(), sceUsbdGetPrivateData(), sceUsbdOpenPipe(), sceUsbdOpenPipeAligned(), sceUsbdRegisterAutoloader(), sceUsbdRegisterLdd(), sceUsbdScanStaticDescriptor(), sceUsbdSetPrivateData(), sceUsbdTransferPipe(), sceUsbdUnregisterAutoloader(), and sceUsbdUnregisterLdd().
usbdUnlock()
int usbdUnlock (void)
Definition at line 54 of file usbd.c.
                      {
         return SignalSema(usbdSema);
 }
References SignalSema(), and usbdSema.
Referenced by callbackThreadFunc(), callUsbDriverFunc(), hcdIrqThread(), sceUsbdChangeThreadPriority(), sceUsbdClosePipe(), sceUsbdGetDeviceLocation(), sceUsbdGetPrivateData(), sceUsbdOpenPipe(), sceUsbdOpenPipeAligned(), sceUsbdRegisterAutoloader(), sceUsbdRegisterLdd(), sceUsbdScanStaticDescriptor(), sceUsbdSetPrivateData(), sceUsbdTransferPipe(), sceUsbdUnregisterAutoloader(), and sceUsbdUnregisterLdd().
Variable Documentation
usbConfig
UsbdConfig usbConfig extern
Definition at line 34 of file usbd.c.
Referenced by _start().