ps2sdk: iop/usb/usbd/include/usbd_macro.h File Reference
usbd_macro.h File Reference
#include <usbd.h>
Macros
#define sceUsbdIsochronousTransfer(epID, dataptr, len, delta, doneCB, arg) sceUsbdTransferPipe((epID), (dataptr), (len), (void *)(delta), (doneCB), (arg))
#define sceUsbdBulkTransfer(epID, dataptr, len, doneCB, arg) sceUsbdTransferPipe((epID), (dataptr), (len), NULL, (doneCB), (arg))
#define sceUsbdInterruptTransfer(epID, dataptr, len, doneCB, arg) sceUsbdTransferPipe((epID), (dataptr), (len), NULL, (doneCB), (arg))
#define sceUsbdClearDeviceFeature(epID, feature, doneCB, arg)
#define sceUsbdSetDeviceFeature(epID, feature, doneCB, arg)
#define sceUsbdGetConfiguration(epID, dataptr, doneCB, arg)
#define sceUsbdSetConfiguration(epID, config, doneCB, arg) sceUsbdControlTransfer((epID), USB_DIR_OUT | USB_RECIP_DEVICE, USB_REQ_SET_CONFIGURATION, (config), 0, 0, NULL, (doneCB), (arg))
#define sceUsbdGetDescriptor(epID, type, index, language, dataptr, len, doneCB, arg)
#define sceUsbdSetDeviceDescriptor(epID, type, index, language, dataptr, len, doneCB, arg)
#define sceUsbdGetDeviceStatus(epID, dataptr, doneCB, arg)
#define sceUsbdSetAddress(epID, address, doneCB, arg)
#define sceUsbdClearInterfaceFeature(epID, feature, interface, doneCB, arg)
#define sceUsbdSetInterfaceFeature(epID, feature, interface, doneCB, arg)
#define sceUsbdGetInterface(epID, interface, dataptr, doneCB, arg)
#define sceUsbdSetInterface(epID, interface, alt_setting, doneCB, arg)
#define sceUsbdGetInterfaceDescriptor(epID, type, index, language, dataptr, len, doneCB, arg)
#define sceUsbdSetInterfaceDescriptor(epID, type, index, language, dataptr, len, doneCB, arg)
#define sceUsbdGetInterfaceStatus(epID, interface, dataptr, doneCB, arg)
#define sceUsbdClearEndpointFeature(epID, feature, endpoint, doneCB, arg)
#define sceUsbdSetEndpointFeature(epID, feature, endpoint, doneCB, arg)
#define sceUsbdGetEndpointStatus(epID, endpoint, dataptr, doneCB, arg)
#define sceUsbdGetEndpointDescriptor(epID, type, index, language, dataptr, len, doneCB, arg)
#define sceUsbdSetEndpointDescriptor(epID, type, index, language, dataptr, len, doneCB, arg)
#define sceUsbdSynchFrame(epID, endpoint, pfn, doneCB, arg)
#define UsbControlTransfer sceUsbdControlTransfer
#define UsbIsochronousTransfer sceUsbdIsochronousTransfer
#define UsbBulkTransfer sceUsbdBulkTransfer
#define UsbInterruptTransfer sceUsbdInterruptTransfer
#define UsbClearDeviceFeature sceUsbdClearDeviceFeature
#define UsbSetDeviceFeature sceUsbdSetDeviceFeature
#define UsbGetDeviceConfiguration sceUsbdGetConfiguration
#define UsbSetDeviceConfiguration sceUsbdSetConfiguration
#define UsbGetDeviceDescriptor sceUsbdGetDescriptor
#define UsbSetDeviceDescriptor sceUsbdSetDeviceDescriptor
#define UsbGetDeviceStatus sceUsbdGetDeviceStatus
#define UsbSetDeviceAddress sceUsbdSetAddress
#define UsbClearInterfaceFeature sceUsbdClearInterfaceFeature
#define UsbSetInterfaceFeature sceUsbdSetInterfaceFeature
#define UsbGetInterface sceUsbdGetInterface
#define UsbSetInterface sceUsbdSetInterface
#define UsbGetInterfaceDescriptor sceUsbdGetInterfaceDescriptor
#define UsbSetInterfaceDescriptor sceUsbdSetInterfaceDescriptor
#define UsbGetInterfaceStatus sceUsbdGetInterfaceStatus
#define UsbClearEndpointFeature sceUsbdClearEndpointFeature
#define UsbSetEndpointFeature sceUsbdSetEndpointFeature
#define UsbGetEndpointStatus sceUsbdGetEndpointStatus
#define UsbGetEndpointDescriptor sceUsbdGetEndpointDescriptor
#define UsbSetEndpointDescriptor sceUsbdSetEndpointDescriptor
#define UsbSynchEndpointFrame sceUsbdSynchFrame
Functions
static int sceUsbdControlTransfer (int epID, int reqtyp, int req, int val, int index, int leng, void *dataptr, void *doneCB, void *arg)
Detailed Description
USB Driver function prototypes and constants.
Definition in file usbd_macro.h.
Macro Definition Documentation
sceUsbdBulkTransfer
#define sceUsbdBulkTransfer (epID, dataptr, len, doneCB, arg) sceUsbdTransferPipe((epID), (dataptr), (len), NULL, (doneCB), (arg))
Definition at line 36 of file usbd_macro.h.
sceUsbdClearDeviceFeature
#define sceUsbdClearDeviceFeature (epID, feature, doneCB, arg)
Value:
        sceUsbdControlTransfer((epID), USB_DIR_OUT | USB_RECIP_DEVICE, USB_REQ_CLEAR_FEATURE, \
        (feature), 0, 0, NULL, (doneCB), (arg))
Definition at line 44 of file usbd_macro.h.
sceUsbdClearEndpointFeature
#define sceUsbdClearEndpointFeature (epID, feature, endpoint, doneCB, arg)
Value:
        sceUsbdControlTransfer((epID), USB_DIR_OUT | USB_RECIP_ENDPOINT, USB_REQ_CLEAR_FEATURE, \
        (feature), (endpoint), 0, NULL, (doneCB), (arg))
Definition at line 103 of file usbd_macro.h.
sceUsbdClearInterfaceFeature
#define sceUsbdClearInterfaceFeature (epID, feature, interface, doneCB, arg)
Value:
        sceUsbdControlTransfer((epID), USB_DIR_OUT | USB_RECIP_INTERFACE, USB_REQ_CLEAR_FEATURE, \
        (feature), (interface), 0, NULL, (doneCB), (arg))
Definition at line 75 of file usbd_macro.h.
sceUsbdGetConfiguration
#define sceUsbdGetConfiguration (epID, dataptr, doneCB, arg)
Value:
        sceUsbdControlTransfer((epID), USB_DIR_IN | USB_RECIP_DEVICE, USB_REQ_GET_CONFIGURATION, \
        0, 0, 1, (dataptr), (doneCB), (arg))
Definition at line 52 of file usbd_macro.h.
sceUsbdGetDescriptor
#define sceUsbdGetDescriptor (epID, type, index, language, dataptr, len, doneCB, arg)
Value:
        sceUsbdControlTransfer((epID), USB_DIR_IN | USB_RECIP_DEVICE, USB_REQ_GET_DESCRIPTOR, \
        ((type) << 8) | (index), (language), (len), (dataptr), (doneCB), (arg))
Definition at line 59 of file usbd_macro.h.
sceUsbdGetDeviceStatus
#define sceUsbdGetDeviceStatus (epID, dataptr, doneCB, arg)
Value:
        sceUsbdControlTransfer((epID), USB_DIR_IN | USB_RECIP_DEVICE, USB_REQ_GET_STATUS, \
        0, 0, 2, (dataptr), (doneCB), (arg))
Definition at line 67 of file usbd_macro.h.
sceUsbdGetEndpointDescriptor
#define sceUsbdGetEndpointDescriptor (epID, type, index, language, dataptr, len, doneCB, arg)
Value:
        sceUsbdControlTransfer((epID), USB_DIR_IN | USB_RECIP_ENDPOINT, USB_REQ_GET_DESCRIPTOR, \
        ((type) << 8) | (index), (language), (len), (dataptr), (doneCB), (arg))
Definition at line 115 of file usbd_macro.h.
sceUsbdGetEndpointStatus
#define sceUsbdGetEndpointStatus (epID, endpoint, dataptr, doneCB, arg)
Value:
        sceUsbdControlTransfer((epID), USB_DIR_IN | USB_RECIP_ENDPOINT, USB_REQ_GET_STATUS, \
        0, (endpoint), 2, (dataptr), (doneCB), (arg))
Definition at line 111 of file usbd_macro.h.
sceUsbdGetInterface
#define sceUsbdGetInterface (epID, interface, dataptr, doneCB, arg)
Value:
        sceUsbdControlTransfer((epID), USB_DIR_IN | USB_RECIP_INTERFACE, USB_REQ_GET_INTERFACE, \
        0, (interface), 1, (dataptr), (doneCB), (arg))
Definition at line 83 of file usbd_macro.h.
sceUsbdGetInterfaceDescriptor
#define sceUsbdGetInterfaceDescriptor (epID, type, index, language, dataptr, len, doneCB, arg)
Value:
        sceUsbdControlTransfer((epID), USB_DIR_IN | USB_RECIP_INTERFACE, USB_REQ_GET_DESCRIPTOR, \
        ((type) << 8) | (index), (language), (len), (dataptr), (doneCB), (arg))
Definition at line 91 of file usbd_macro.h.
sceUsbdGetInterfaceStatus
#define sceUsbdGetInterfaceStatus (epID, interface, dataptr, doneCB, arg)
Value:
        sceUsbdControlTransfer((epID), USB_DIR_IN | USB_RECIP_INTERFACE, USB_REQ_GET_STATUS, \
        0, (interface), 2, (dataptr), (doneCB), (arg))
Definition at line 99 of file usbd_macro.h.
sceUsbdInterruptTransfer
#define sceUsbdInterruptTransfer (epID, dataptr, len, doneCB, arg) sceUsbdTransferPipe((epID), (dataptr), (len), NULL, (doneCB), (arg))
Definition at line 39 of file usbd_macro.h.
sceUsbdIsochronousTransfer
#define sceUsbdIsochronousTransfer (epID, dataptr, len, delta, doneCB, arg) sceUsbdTransferPipe((epID), (dataptr), (len), (void *)(delta), (doneCB), (arg))
Definition at line 33 of file usbd_macro.h.
sceUsbdSetAddress
#define sceUsbdSetAddress (epID, address, doneCB, arg)
Value:
        sceUsbdControlTransfer((epID), USB_DIR_OUT | USB_RECIP_DEVICE, USB_REQ_SET_ADDRESS, \
        (address), 0, 0, NULL, (doneCB), (arg))
Definition at line 71 of file usbd_macro.h.
sceUsbdSetConfiguration
#define sceUsbdSetConfiguration (epID, config, doneCB, arg) sceUsbdControlTransfer((epID), USB_DIR_OUT | USB_RECIP_DEVICE, USB_REQ_SET_CONFIGURATION, (config), 0, 0, NULL, (doneCB), (arg))
Definition at line 56 of file usbd_macro.h.
sceUsbdSetDeviceDescriptor
#define sceUsbdSetDeviceDescriptor (epID, type, index, language, dataptr, len, doneCB, arg)
Value:
        sceUsbdControlTransfer((epID), USB_DIR_OUT | USB_RECIP_DEVICE, USB_REQ_SET_DESCRIPTOR, \
        ((type) << 8) | (index), (language), (len), (dataptr), (doneCB), (arg))
Definition at line 63 of file usbd_macro.h.
sceUsbdSetDeviceFeature
#define sceUsbdSetDeviceFeature (epID, feature, doneCB, arg)
Value:
        sceUsbdControlTransfer((epID), USB_DIR_OUT | USB_RECIP_DEVICE, USB_REQ_SET_FEATURE, \
        (feature), 0, 0, NULL, (doneCB), (arg))
Definition at line 48 of file usbd_macro.h.
sceUsbdSetEndpointDescriptor
#define sceUsbdSetEndpointDescriptor (epID, type, index, language, dataptr, len, doneCB, arg)
Value:
        sceUsbdControlTransfer((epID), USB_DIR_OUT | USB_RECIP_ENDPOINT, USB_REQ_SET_DESCRIPTOR, \
        ((type) << 8) | (index), (language), (len), (dataptr), (doneCB), (arg))
Definition at line 119 of file usbd_macro.h.
sceUsbdSetEndpointFeature
#define sceUsbdSetEndpointFeature (epID, feature, endpoint, doneCB, arg)
Value:
        sceUsbdControlTransfer((epID), USB_DIR_OUT | USB_RECIP_ENDPOINT, USB_REQ_SET_FEATURE, \
        (feature), (endpoint), 0, NULL, (doneCB), (arg))
Definition at line 107 of file usbd_macro.h.
sceUsbdSetInterface
#define sceUsbdSetInterface (epID, interface, alt_setting, doneCB, arg)
Value:
        sceUsbdControlTransfer((epID), USB_DIR_OUT | USB_RECIP_INTERFACE, USB_REQ_SET_INTERFACE, \
        (alt_setting), (interface), 0, NULL, (doneCB), (arg))
Definition at line 87 of file usbd_macro.h.
sceUsbdSetInterfaceDescriptor
#define sceUsbdSetInterfaceDescriptor (epID, type, index, language, dataptr, len, doneCB, arg)
Value:
        sceUsbdControlTransfer((epID), USB_DIR_OUT | USB_RECIP_INTERFACE, USB_REQ_SET_DESCRIPTOR, \
        ((type) << 8) | (index), (language), (len), (dataptr), (doneCB), (arg))
Definition at line 95 of file usbd_macro.h.
sceUsbdSetInterfaceFeature
#define sceUsbdSetInterfaceFeature (epID, feature, interface, doneCB, arg)
Value:
        sceUsbdControlTransfer((epID), USB_DIR_OUT | USB_RECIP_INTERFACE, USB_REQ_SET_FEATURE, \
        (feature), (interface), 0, NULL, (doneCB), (arg))
Definition at line 79 of file usbd_macro.h.
sceUsbdSynchFrame
#define sceUsbdSynchFrame (epID, endpoint, pfn, doneCB, arg)
Value:
        sceUsbdControlTransfer((epID), USB_DIR_IN | USB_RECIP_ENDPOINT, USB_REQ_SYNCH_FRAME, \
        0, (endpoint), 2, (pfn), (doneCB), (arg))
Definition at line 123 of file usbd_macro.h.
UsbBulkTransfer
#define UsbBulkTransfer sceUsbdBulkTransfer
Definition at line 130 of file usbd_macro.h.
UsbClearDeviceFeature
#define UsbClearDeviceFeature sceUsbdClearDeviceFeature
Definition at line 132 of file usbd_macro.h.
UsbClearEndpointFeature
#define UsbClearEndpointFeature sceUsbdClearEndpointFeature
Definition at line 147 of file usbd_macro.h.
UsbClearInterfaceFeature
#define UsbClearInterfaceFeature sceUsbdClearInterfaceFeature
Definition at line 140 of file usbd_macro.h.
UsbControlTransfer
#define UsbControlTransfer sceUsbdControlTransfer
Definition at line 128 of file usbd_macro.h.
UsbGetDeviceConfiguration
#define UsbGetDeviceConfiguration sceUsbdGetConfiguration
Definition at line 134 of file usbd_macro.h.
UsbGetDeviceDescriptor
#define UsbGetDeviceDescriptor sceUsbdGetDescriptor
Definition at line 136 of file usbd_macro.h.
UsbGetDeviceStatus
#define UsbGetDeviceStatus sceUsbdGetDeviceStatus
Definition at line 138 of file usbd_macro.h.
UsbGetEndpointDescriptor
#define UsbGetEndpointDescriptor sceUsbdGetEndpointDescriptor
Definition at line 150 of file usbd_macro.h.
UsbGetEndpointStatus
#define UsbGetEndpointStatus sceUsbdGetEndpointStatus
Definition at line 149 of file usbd_macro.h.
UsbGetInterface
#define UsbGetInterface sceUsbdGetInterface
Definition at line 142 of file usbd_macro.h.
UsbGetInterfaceDescriptor
#define UsbGetInterfaceDescriptor sceUsbdGetInterfaceDescriptor
Definition at line 144 of file usbd_macro.h.
UsbGetInterfaceStatus
#define UsbGetInterfaceStatus sceUsbdGetInterfaceStatus
Definition at line 146 of file usbd_macro.h.
UsbInterruptTransfer
#define UsbInterruptTransfer sceUsbdInterruptTransfer
Definition at line 131 of file usbd_macro.h.
UsbIsochronousTransfer
#define UsbIsochronousTransfer sceUsbdIsochronousTransfer
Definition at line 129 of file usbd_macro.h.
UsbSetDeviceAddress
#define UsbSetDeviceAddress sceUsbdSetAddress
Definition at line 139 of file usbd_macro.h.
UsbSetDeviceConfiguration
#define UsbSetDeviceConfiguration sceUsbdSetConfiguration
Definition at line 135 of file usbd_macro.h.
UsbSetDeviceDescriptor
#define UsbSetDeviceDescriptor sceUsbdSetDeviceDescriptor
Definition at line 137 of file usbd_macro.h.
UsbSetDeviceFeature
#define UsbSetDeviceFeature sceUsbdSetDeviceFeature
Definition at line 133 of file usbd_macro.h.
UsbSetEndpointDescriptor
#define UsbSetEndpointDescriptor sceUsbdSetEndpointDescriptor
Definition at line 151 of file usbd_macro.h.
UsbSetEndpointFeature
#define UsbSetEndpointFeature sceUsbdSetEndpointFeature
Definition at line 148 of file usbd_macro.h.
UsbSetInterface
#define UsbSetInterface sceUsbdSetInterface
Definition at line 143 of file usbd_macro.h.
UsbSetInterfaceDescriptor
#define UsbSetInterfaceDescriptor sceUsbdSetInterfaceDescriptor
Definition at line 145 of file usbd_macro.h.
UsbSetInterfaceFeature
#define UsbSetInterfaceFeature sceUsbdSetInterfaceFeature
Definition at line 141 of file usbd_macro.h.
UsbSynchEndpointFrame
#define UsbSynchEndpointFrame sceUsbdSynchFrame
Definition at line 152 of file usbd_macro.h.
Function Documentation
sceUsbdControlTransfer()
static int sceUsbdControlTransfer (int epID, int reqtyp, int req, int val, int index, int leng, void * dataptr, void * doneCB, void * arg) static
Definition at line 21 of file usbd_macro.h.
 {
         UsbDeviceRequest devreq;
         devreq.requesttype = reqtyp;
         devreq.request = req;
         devreq.value = val;
         devreq.index = index;
         devreq.length = leng;
         return sceUsbdTransferPipe(epID, dataptr, devreq.length, &devreq, doneCB, arg);
 }
References arg, index(), UsbDeviceRequest::index, UsbDeviceRequest::length, UsbDeviceRequest::request, UsbDeviceRequest::requesttype, sceUsbdTransferPipe(), and UsbDeviceRequest::value.
Referenced by getReg8(), PS2CamGetDeviceSring(), ps2kbd_config_set(), ps2kbd_data_recv(), ps2kbd_ioctl_setleds(), setReg16(), setReg8(), usb_bulk_get_max_lun(), usb_bulk_reset(), and usb_getstring().