ps2sdk: iop/usb/usbhdfsd/src/usbhdfsd.c File Reference
usbhdfsd.c File Reference
#include <loadcore.h>
#include <intrman.h>
#include <stdio.h>
#include <sysmem.h>
#include <usbhdfsd.h>
#include <irx.h>
Macros
#define MAJOR_VER 1
#define MINOR_VER 6
Functions
IRX_ID ("usbhdfsd", MAJOR_VER, MINOR_VER)
int InitFAT ()
int InitFS ()
int InitUSB ()
int _start (int argc, char *argv[])
void * malloc (int size)
void free (void *ptr)
Variables
struct irx_export_table _exp_usbmass
Macro Definition Documentation
MAJOR_VER
#define MAJOR_VER 1
Definition at line 5 of file usbhdfsd.c.
MINOR_VER
#define MINOR_VER 6
Definition at line 6 of file usbhdfsd.c.
Function Documentation
_start()
int _start (int argc, char * argv[])
Definition at line 24 of file usbhdfsd.c.
 {
         printf("USB HDD FileSystem Driver v%d.%d\n", MAJOR_VER, MINOR_VER);
         if (RegisterLibraryEntries(&_exp_usbmass) != 0) {
                 printf("USBHDFSD: Already registered.\n");
                 return MODULE_NO_RESIDENT_END;
         }
         // initialize the FAT driver
         if(InitFAT() != 0)
         {
                 printf("USBHDFSD: Error initializing FAT driver!\n");
                 return MODULE_NO_RESIDENT_END;
         }
         // initialize the USB driver
         if(InitUSB() != 0)
         {
                 printf("USBHDFSD: Error initializing USB driver!\n");
                 return MODULE_NO_RESIDENT_END;
         }
         // initialize the file system driver
         if(InitFS() != 0)
         {
                 printf("USBHDFSD: Error initializing FS driver!\n");
                 return MODULE_NO_RESIDENT_END;
         }
         // return resident
         return MODULE_RESIDENT_END;
 }
References _exp_usbmass, InitFAT(), InitFS(), InitUSB(), MAJOR_VER, MINOR_VER, MODULE_NO_RESIDENT_END, MODULE_RESIDENT_END, printf(), and RegisterLibraryEntries().
free()
void free (void * ptr)
Definition at line 70 of file usbhdfsd.c.
                     {
         int OldState;
         CpuSuspendIntr(&OldState);
         FreeSysMemory(ptr);
         CpuResumeIntr(OldState);
 }
References buffer, CpuResumeIntr(), CpuSuspendIntr(), and FreeSysMemory().
InitFAT()
int InitFAT ()
Definition at line 23 of file fat_driver.c.
 {
     int i;
     M_DEBUG("%s\n", __func__);
     for (i = 0; i < NUM_DRIVES; ++i)
         g_fatd[i] = NULL;
     return 0;
 }
References g_fatd, M_DEBUG, NULL, and NUM_DRIVES.
Referenced by _start().
InitFS()
int InitFS ()
Definition at line 905 of file fs_driver.c.
 {
     M_DEBUG("%s\n", __func__);
     DelDrv("mass");
     return (AddDrv(&fs_driver) == 0 ? 0 : -1);
 }
References AddDrv(), DelDrv(), fs_driver, and M_DEBUG.
Referenced by _start().
InitUSB()
int InitUSB ()
Definition at line 1123 of file usb_driver.c.
 {
         int i;
         int ret = 0;
         for (i = 0; i < NUM_DEVICES; ++i)
         {
                 g_mass_device[i].status = 0;
                 g_mass_device[i].devId = -1;
         }
         driver.next             = NULL;
         driver.prev             = NULL;
         driver.name             = "mass-stor";
         driver.probe            = mass_stor_probe;
         driver.connect          = mass_stor_connect;
         driver.disconnect       = mass_stor_disconnect;
         ret = sceUsbdRegisterLdd(&driver);
         XPRINTF("USBHDFSD: registerDriver=%i \n", ret);
         if (ret < 0)
         {
                 printf("USBHDFSD: register driver failed! ret=%d\n", ret);
                 return(-1);
         }
         return(0);
 }
Referenced by _start().
IRX_ID()
IRX_ID ("usbhdfsd" , MAJOR_VER , MINOR_VER)
malloc()
void* malloc (int size)
Definition at line 59 of file usbhdfsd.c.
                       {
         void *result;
         int OldState;
         CpuSuspendIntr(&OldState);
         result = AllocSysMemory(ALLOC_FIRST, size, NULL);
         CpuResumeIntr(OldState);
         return result;
 }
References ALLOC_FIRST, AllocSysMemory(), buffer, CpuResumeIntr(), CpuSuspendIntr(), NULL, and result.
Variable Documentation
_exp_usbmass
struct irx_export_table _exp_usbmass extern
Referenced by _start().