ps2sdk: iop/usb/usbd/src/usbio.c File Reference
usbio.c File Reference
#include "usbdpriv.h"
#include "mem.h"
#include "usbio.h"
#include "stdio.h"
Functions
void removeEndpointFromQueue (Endpoint *ep)
void enqueueEndpoint (Endpoint *ep, u32 listType)
void checkTdQueue (int type)
int setupControlTransfer (Endpoint *ep)
int setupIsocronTransfer (Endpoint *ep)
int setupBulkTransfer (Endpoint *ep)
void handleIoReqList (Endpoint *ep)
int attachIoReqToEndpoint (Endpoint *ep, IoRequest *req, void *destdata, u16 length, void *callback)
int doControlTransfer (Endpoint *ep, IoRequest *req, u8 requestType, u8 request, u16 value, u16 index, u16 length, void *destdata, void *callback)
Detailed Description
USB Driver function prototypes and constants.
Definition in file usbio.c.
Function Documentation
attachIoReqToEndpoint()
int attachIoReqToEndpoint (Endpoint * ep, IoRequest * req, void * destdata, u16 length, void * callback)
Definition at line 270 of file usbio.c.
{
         if (!ep->correspDevice)
                 return USB_RC_BUSY;
         if (req->busyFlag)
                 return USB_RC_BUSY;
         req->busyFlag = 1;
         req->correspEndpoint = ep;
         req->destPtr = destdata;
         req->length  = length;
         req->resultCode = 0;
         req->transferedBytes = 0;
         req->callbackProc = callback;
         req->next = NULL;
         req->prev = ep->ioReqListEnd;
         if (ep->ioReqListEnd)
                 ep->ioReqListEnd->next = req;
         else
                 ep->ioReqListStart = req;
         ep->ioReqListEnd = req;
         handleIoReqList(ep);
         return 0;
 }
References IoRequest::busyFlag, IoRequest::callbackProc, Endpoint::correspDevice, IoRequest::correspEndpoint, IoRequest::destPtr, handleIoReqList(), Endpoint::ioReqListEnd, Endpoint::ioReqListStart, IoRequest::length, IoRequest::next, NULL, IoRequest::prev, IoRequest::resultCode, IoRequest::transferedBytes, and USB_RC_BUSY.
Referenced by doControlTransfer(), getHubStatusChange(), and sceUsbdTransferPipe().
checkTdQueue()
void checkTdQueue (int type)
Definition at line 54 of file usbio.c.
{
         if ((type == GENTD_QUEUE) && !memPool.freeHcTdList)
                 return;
         else if ((type == ISOTD_QUEUE) && !memPool.freeHcIsoTdList)
                 return;
         if (memPool.tdQueueStart[type - 1])
                 handleIoReqList(memPool.tdQueueStart[type - 1]);
 }
References MemoryPool::freeHcIsoTdList, MemoryPool::freeHcTdList, GENTD_QUEUE, handleIoReqList(), ISOTD_QUEUE, memPool, and MemoryPool::tdQueueStart.
Referenced by processDoneQueue_GenTd(), and processDoneQueue_IsoTd().
doControlTransfer()
int doControlTransfer (Endpoint * ep, IoRequest * req, u8 requestType, u8 request, u16 value, u16 index, u16 length, void * destdata, void * callback)
Definition at line 296 of file usbio.c.
 {
         if (req->busyFlag) {
                 dbg_printf("ERROR: doControlTransfer: IoReq busy\n");
                 return USB_RC_BUSY;
         }
         req->devReq.requesttype = requestType;
         req->devReq.request     = request;
         req->devReq.value       = value;
         req->devReq.index       = index;
         req->devReq.length      = length;
     return attachIoReqToEndpoint(ep, req, destdata, length, callback);
 }
References attachIoReqToEndpoint(), IoRequest::busyFlag, dbg_printf, IoRequest::devReq, index(), UsbDeviceRequest::index, UsbDeviceRequest::length, UsbDeviceRequest::request, UsbDeviceRequest::requesttype, USB_RC_BUSY, and UsbDeviceRequest::value.
Referenced by fetchConfigDescriptors(), HubControlTransfer(), hubSetFuncAddress(), requestDeviceDescriptor(), and sceUsbdTransferPipe().
enqueueEndpoint()
void enqueueEndpoint (Endpoint * ep, u32 listType)
Definition at line 39 of file usbio.c.
{
         if (ep->inTdQueue)
                 return;
         ep->busyNext = NULL;
         ep->busyPrev = memPool.tdQueueEnd[listType - 1];
         if (memPool.tdQueueEnd[listType - 1])
                 memPool.tdQueueEnd[listType - 1]->busyNext = ep;
         else
                 memPool.tdQueueStart[listType - 1] = ep;
         memPool.tdQueueEnd[listType - 1] = ep;
         ep->inTdQueue = listType;
 }
References Endpoint::busyNext, Endpoint::busyPrev, Endpoint::inTdQueue, memPool, NULL, MemoryPool::tdQueueEnd, and MemoryPool::tdQueueStart.
Referenced by setupBulkTransfer(), setupControlTransfer(), and setupIsocronTransfer().
handleIoReqList()
void handleIoReqList (Endpoint * ep)
Definition at line 261 of file usbio.c.
{
         if (ep->endpointType == TYPE_CONTROL)
                 setupControlTransfer(ep);
         else if (ep->endpointType == TYPE_ISOCHRON)
                 setupIsocronTransfer(ep);
         else    // bulk or interrupt
                 setupBulkTransfer(ep);
 }
References Endpoint::endpointType, setupBulkTransfer(), setupControlTransfer(), setupIsocronTransfer(), TYPE_CONTROL, and TYPE_ISOCHRON.
Referenced by attachIoReqToEndpoint(), and checkTdQueue().
removeEndpointFromQueue()
void removeEndpointFromQueue (Endpoint * ep)
Definition at line 22 of file usbio.c.
{
         if (!ep->inTdQueue)
                 return;
         if (ep->busyNext)
                 ep->busyNext->busyPrev = ep->busyPrev;
         else
                 memPool.tdQueueEnd[ep->inTdQueue - 1] = ep->busyPrev;
         if (ep->busyPrev)
                 ep->busyPrev->busyNext = ep->busyNext;
         else
                 memPool.tdQueueStart[ep->inTdQueue - 1] = ep->busyNext;
         ep->inTdQueue = 0;
 }
References Endpoint::busyNext, Endpoint::busyPrev, Endpoint::inTdQueue, memPool, MemoryPool::tdQueueEnd, and MemoryPool::tdQueueStart.
Referenced by cleanUpFunc(), killEndpoint(), setupBulkTransfer(), setupControlTransfer(), and setupIsocronTransfer().
setupBulkTransfer()
int setupBulkTransfer (Endpoint * ep)
Definition at line 209 of file usbio.c.
{
         IoRequest *curIoReq = ep->ioReqListStart;
         HcED      *ed = &ep->hcEd;
         HcTD      *curTd = ed->tdTail;
         HcTD      *newTd;
         if (ep->hcEd.tdTail && !ED_HALTED(ep->hcEd) && !ED_SKIPPED(ep->hcEd) && curIoReq) {
                 newTd = allocTd();
                 if (!newTd) {
                         enqueueEndpoint(ep, GENTD_QUEUE);
                         return 0;
                 }
                 if (curIoReq->next)
                         curIoReq->next->prev = curIoReq->prev;
                 else
                         ep->ioReqListEnd = curIoReq->prev;
                 if (curIoReq->prev)
                         curIoReq->prev->next = curIoReq->next;
                 else
                         ep->ioReqListStart = curIoReq->next;
                 curTd->HcArea    = TD_HCAREA(USB_RC_NOTACCESSED, 0, 0, 3, 1) << 16;
                 curTd->next              = newTd;
                 curTd->curBufPtr = curIoReq->destPtr;
                 if (curIoReq->destPtr && curIoReq->length)
                         curTd->bufferEnd = (u8*)curIoReq->destPtr + curIoReq->length - 1;
                 else
                         curTd->bufferEnd = NULL;
                 memPool.hcTdToIoReqLUT[curTd - memPool.hcTdBuf] = curIoReq;
                 ed->tdTail = newTd;
                 if (ep->endpointType == TYPE_BULK)
                         memPool.ohciRegs->HcCommandStatus |= OHCI_COM_BLF; // Bulk List Filled
                 // remove endpoint from busy list if there are no IoRequests left
                 if (!ep->ioReqListStart)
                         removeEndpointFromQueue(ep);
                 return 1;
         } else {
                 // endpoint error
                 dbg_printf("ERROR Endpoint error\n");
                 removeEndpointFromQueue(ep);
                 return 0;
         }
 }
References allocTd(), HcTD::bufferEnd, HcTD::curBufPtr, dbg_printf, IoRequest::destPtr, ED_HALTED, ED_SKIPPED, Endpoint::endpointType, enqueueEndpoint(), GENTD_QUEUE, HcTD::HcArea, OhciRegs::HcCommandStatus, Endpoint::hcEd, MemoryPool::hcTdBuf, MemoryPool::hcTdToIoReqLUT, Endpoint::ioReqListEnd, Endpoint::ioReqListStart, IoRequest::length, memPool, IoRequest::next, HcTD::next, NULL, OHCI_COM_BLF, MemoryPool::ohciRegs, IoRequest::prev, removeEndpointFromQueue(), TD_HCAREA, HcED::tdTail, TYPE_BULK, and USB_RC_NOTACCESSED.
Referenced by handleIoReqList().
setupControlTransfer()
int setupControlTransfer (Endpoint * ep)
Definition at line 64 of file usbio.c.
{
         HcTD *statusTd, *tailTd, *dataTd = NULL;
         IoRequest *curIoReq = ep->ioReqListStart;
         if (ep->hcEd.tdTail && !ED_HALTED(ep->hcEd) && !ED_SKIPPED(ep->hcEd) && curIoReq) {
                 if (curIoReq->destPtr && curIoReq->length) {
                         dataTd = allocTd();
                         if (!dataTd) {
                                 enqueueEndpoint(ep, GENTD_QUEUE);
                                 return 0;
                         }
                 }
                 statusTd = allocTd();
                 tailTd = allocTd();
                 if (!statusTd || !tailTd) {
                         freeTd(statusTd);
                         freeTd(tailTd);
                         freeTd(dataTd);
                         enqueueEndpoint(ep, GENTD_QUEUE);
                         return 0;
                 }
                 if (curIoReq->next)
                         curIoReq->next->prev = curIoReq->prev;
                 else
                         ep->ioReqListEnd = curIoReq->prev;
                 if (curIoReq->prev)
                         curIoReq->prev->next = curIoReq->next;
                 else
                         ep->ioReqListStart = curIoReq->next;
                 // first stage: setup
                 ep->hcEd.tdTail->HcArea = TD_HCAREA(USB_RC_NOTACCESSED, 2, 7, TD_SETUP, 0) << 16;
                 ep->hcEd.tdTail->curBufPtr = &curIoReq->devReq;
                 ep->hcEd.tdTail->bufferEnd = ((u8 *)&curIoReq->devReq) + sizeof(UsbDeviceRequest) - 1;
                 memPool.hcTdToIoReqLUT[ep->hcEd.tdTail - memPool.hcTdBuf] = curIoReq;
                 // second stage: data
                 if (dataTd) {
                         ep->hcEd.tdTail->next = dataTd;
                         if (curIoReq->devReq.requesttype & USB_DIR_IN)
                                 dataTd->HcArea = TD_HCAREA(USB_RC_NOTACCESSED, 3, 7,  TD_IN, 1) << 16;
                         else
                                 dataTd->HcArea = TD_HCAREA(USB_RC_NOTACCESSED, 3, 7, TD_OUT, 1) << 16;
                         dataTd->curBufPtr = curIoReq->destPtr;
                         dataTd->bufferEnd = (u8 *)curIoReq->destPtr + curIoReq->length - 1;
                         dataTd->next = statusTd;
                         memPool.hcTdToIoReqLUT[dataTd - memPool.hcTdBuf] = curIoReq;
                 } else
                         ep->hcEd.tdTail->next = statusTd;
                 // third stage: status
                 if (curIoReq->devReq.requesttype & USB_DIR_IN)
                         statusTd->HcArea = TD_HCAREA(USB_RC_NOTACCESSED, 3, 0, TD_OUT, 0) << 16;
                 else
                         statusTd->HcArea = TD_HCAREA(USB_RC_NOTACCESSED, 3, 0,  TD_IN, 0) << 16;
                 statusTd->curBufPtr = NULL;
                 statusTd->bufferEnd = NULL;
                 statusTd->next = tailTd;
                 memPool.hcTdToIoReqLUT[statusTd - memPool.hcTdBuf] = curIoReq;
                 ep->hcEd.tdTail = tailTd;
                 memPool.ohciRegs->HcCommandStatus |= OHCI_COM_CLF; // control list filled
                 // remove endpoint from busy list if there are no IoRequests left
                 if (!ep->ioReqListStart)
                         removeEndpointFromQueue(ep);
                 return 1;
         } else {
                 // endpoint error
                 removeEndpointFromQueue(ep);
                 return 0;
         }
 }
References allocTd(), HcTD::bufferEnd, HcTD::curBufPtr, IoRequest::destPtr, IoRequest::devReq, ED_HALTED, ED_SKIPPED, enqueueEndpoint(), freeTd(), GENTD_QUEUE, HcTD::HcArea, OhciRegs::HcCommandStatus, Endpoint::hcEd, MemoryPool::hcTdBuf, MemoryPool::hcTdToIoReqLUT, Endpoint::ioReqListEnd, Endpoint::ioReqListStart, IoRequest::length, memPool, IoRequest::next, HcTD::next, NULL, OHCI_COM_CLF, MemoryPool::ohciRegs, IoRequest::prev, removeEndpointFromQueue(), UsbDeviceRequest::requesttype, TD_HCAREA, TD_IN, TD_OUT, TD_SETUP, HcED::tdTail, USB_DIR_IN, and USB_RC_NOTACCESSED.
Referenced by handleIoReqList().
setupIsocronTransfer()
int setupIsocronTransfer (Endpoint * ep)
Definition at line 148 of file usbio.c.
{
         IoRequest *curIoReq = ep->ioReqListStart;
         HcED      *ed = &ep->hcEd;
         HcIsoTD   *curTd = (HcIsoTD*)ed->tdTail;
         HcIsoTD   *newTd;
         u32 frameNo;
         if (ep->hcEd.tdTail && !ED_HALTED(ep->hcEd) && !ED_SKIPPED(ep->hcEd) && curIoReq) {
                 newTd = allocIsoTd();
                 if (!newTd) {
                         enqueueEndpoint(ep, ISOTD_QUEUE);
                         return 0;
                 }
                 if (curIoReq->next)
                         curIoReq->next->prev = curIoReq->prev;
                 else
                         ep->ioReqListEnd = curIoReq->prev;
                 if (curIoReq->prev)
                         curIoReq->prev->next = curIoReq->next;
                 else
                         ep->ioReqListStart = curIoReq->next;
                 if (ed->tdTail == (HcTD *)((u32)ed->tdHead & ~0xF))
                         frameNo = memPool.hcHCCA->FrameNumber + 2;
                 else
                         frameNo = ep->isochronLastFrameNum;
                 frameNo = (frameNo + curIoReq->waitFrames) & 0xFFFF;
                 ep->isochronLastFrameNum = frameNo + 1;
                 curTd->hcArea      = (USB_RC_NOTACCESSED << 28) | frameNo;
                 curTd->bufferPage0 = (void*)((u32)curIoReq->destPtr & ~0xFFF);
                 curTd->next                = newTd;
                 if (curIoReq->destPtr && curIoReq->length)
                         curTd->bufferEnd = (u8*)curIoReq->destPtr + curIoReq->length - 1;
                 else
                         curTd->bufferEnd = NULL;
                 curTd->psw[0] = (USB_RC_NOTACCESSED << 12) | ((u32)curIoReq->destPtr & 0xFFF);
                 memPool.hcIsoTdToIoReqLUT[curTd - memPool.hcIsoTdBuf] = curIoReq;
                 ed->tdTail = (HcTD *)newTd;
                 // remove endpoint from busy list if there are no IoRequests left
                 if (!ep->ioReqListStart)
                         removeEndpointFromQueue(ep);
                 return 1;
         } else {
                 // endpoint error
                 removeEndpointFromQueue(ep);
                 return 0;
         }
 }
References allocIsoTd(), HcIsoTD::bufferEnd, HcIsoTD::bufferPage0, IoRequest::destPtr, ED_HALTED, ED_SKIPPED, enqueueEndpoint(), HcCA::FrameNumber, HcIsoTD::hcArea, Endpoint::hcEd, MemoryPool::hcHCCA, MemoryPool::hcIsoTdBuf, MemoryPool::hcIsoTdToIoReqLUT, Endpoint::ioReqListEnd, Endpoint::ioReqListStart, Endpoint::isochronLastFrameNum, ISOTD_QUEUE, IoRequest::length, memPool, IoRequest::next, HcIsoTD::next, NULL, IoRequest::prev, HcIsoTD::psw, removeEndpointFromQueue(), HcED::tdHead, HcED::tdTail, USB_RC_NOTACCESSED, and IoRequest::waitFrames.
Referenced by handleIoReqList().