ps2sdk: iop/usb/usbd/src/usbio.h File Reference
usbio.h File Reference
Functions
void removeEndpointFromQueue (Endpoint *ep)
void checkTdQueue (int type)
void handleIoReqList (Endpoint *ep)
int doControlTransfer (Endpoint *ep, IoRequest *req, u8 requestType, u8 request, u16 value, u16 index, u16 length, void *destdata, void *callback)
int attachIoReqToEndpoint (Endpoint *ep, IoRequest *req, void *destdata, u16 length, void *callback)
Detailed Description
USB Driver function prototypes and constants.
Definition in file usbio.h.
Function Documentation
attachIoReqToEndpoint()
int attachIoReqToEndpoint (Endpoint * ep, IoRequest * req, void * destdata, u16 length, void * callback)
Definition at line 270 of file usbio.c.
{
         if (!ep->correspDevice)
                 return USB_RC_BUSY;
         if (req->busyFlag)
                 return USB_RC_BUSY;
         req->busyFlag = 1;
         req->correspEndpoint = ep;
         req->destPtr = destdata;
         req->length  = length;
         req->resultCode = 0;
         req->transferedBytes = 0;
         req->callbackProc = callback;
         req->next = NULL;
         req->prev = ep->ioReqListEnd;
         if (ep->ioReqListEnd)
                 ep->ioReqListEnd->next = req;
         else
                 ep->ioReqListStart = req;
         ep->ioReqListEnd = req;
         handleIoReqList(ep);
         return 0;
 }
References IoRequest::busyFlag, IoRequest::callbackProc, Endpoint::correspDevice, IoRequest::correspEndpoint, IoRequest::destPtr, handleIoReqList(), Endpoint::ioReqListEnd, Endpoint::ioReqListStart, IoRequest::length, IoRequest::next, NULL, IoRequest::prev, IoRequest::resultCode, IoRequest::transferedBytes, and USB_RC_BUSY.
Referenced by doControlTransfer(), getHubStatusChange(), and sceUsbdTransferPipe().
checkTdQueue()
void checkTdQueue (int type)
Definition at line 54 of file usbio.c.
{
         if ((type == GENTD_QUEUE) && !memPool.freeHcTdList)
                 return;
         else if ((type == ISOTD_QUEUE) && !memPool.freeHcIsoTdList)
                 return;
         if (memPool.tdQueueStart[type - 1])
                 handleIoReqList(memPool.tdQueueStart[type - 1]);
 }
References MemoryPool::freeHcIsoTdList, MemoryPool::freeHcTdList, GENTD_QUEUE, handleIoReqList(), ISOTD_QUEUE, memPool, and MemoryPool::tdQueueStart.
Referenced by processDoneQueue_GenTd(), and processDoneQueue_IsoTd().
doControlTransfer()
int doControlTransfer (Endpoint * ep, IoRequest * req, u8 requestType, u8 request, u16 value, u16 index, u16 length, void * destdata, void * callback)
Definition at line 296 of file usbio.c.
 {
         if (req->busyFlag) {
                 dbg_printf("ERROR: doControlTransfer: IoReq busy\n");
                 return USB_RC_BUSY;
         }
         req->devReq.requesttype = requestType;
         req->devReq.request     = request;
         req->devReq.value       = value;
         req->devReq.index       = index;
         req->devReq.length      = length;
     return attachIoReqToEndpoint(ep, req, destdata, length, callback);
 }
References attachIoReqToEndpoint(), IoRequest::busyFlag, dbg_printf, IoRequest::devReq, index(), UsbDeviceRequest::index, UsbDeviceRequest::length, UsbDeviceRequest::request, UsbDeviceRequest::requesttype, USB_RC_BUSY, and UsbDeviceRequest::value.
Referenced by fetchConfigDescriptors(), HubControlTransfer(), hubSetFuncAddress(), requestDeviceDescriptor(), and sceUsbdTransferPipe().
handleIoReqList()
void handleIoReqList (Endpoint * ep)
Definition at line 261 of file usbio.c.
{
         if (ep->endpointType == TYPE_CONTROL)
                 setupControlTransfer(ep);
         else if (ep->endpointType == TYPE_ISOCHRON)
                 setupIsocronTransfer(ep);
         else    // bulk or interrupt
                 setupBulkTransfer(ep);
 }
References Endpoint::endpointType, setupBulkTransfer(), setupControlTransfer(), setupIsocronTransfer(), TYPE_CONTROL, and TYPE_ISOCHRON.
Referenced by attachIoReqToEndpoint(), and checkTdQueue().
removeEndpointFromQueue()
void removeEndpointFromQueue (Endpoint * ep)
Definition at line 22 of file usbio.c.
{
         if (!ep->inTdQueue)
                 return;
         if (ep->busyNext)
                 ep->busyNext->busyPrev = ep->busyPrev;
         else
                 memPool.tdQueueEnd[ep->inTdQueue - 1] = ep->busyPrev;
         if (ep->busyPrev)
                 ep->busyPrev->busyNext = ep->busyNext;
         else
                 memPool.tdQueueStart[ep->inTdQueue - 1] = ep->busyNext;
         ep->inTdQueue = 0;
 }
References Endpoint::busyNext, Endpoint::busyPrev, Endpoint::inTdQueue, memPool, MemoryPool::tdQueueEnd, and MemoryPool::tdQueueStart.
Referenced by cleanUpFunc(), killEndpoint(), setupBulkTransfer(), setupControlTransfer(), and setupIsocronTransfer().