ps2sdk: iop/kernel/include/vblank.h File Reference
vblank.h File Reference
#include <irx.h>
Macros
#define vblank_IMPORTS_start DECLARE_IMPORT_TABLE(vblank, 1, 1)
#define vblank_IMPORTS_end END_IMPORT_TABLE
#define I_WaitVblankStart DECLARE_IMPORT(4, WaitVblankStart)
#define I_WaitVblankEnd DECLARE_IMPORT(5, WaitVblankEnd)
#define I_WaitVblank DECLARE_IMPORT(6, WaitVblank)
#define I_WaitNonVblank DECLARE_IMPORT(7, WaitNonVblank)
#define I_RegisterVblankHandler DECLARE_IMPORT(8, RegisterVblankHandler)
#define I_ReleaseVblankHandler DECLARE_IMPORT(9, ReleaseVblankHandler)
Functions
void WaitVblankStart ()
void WaitVblankEnd ()
void WaitVblank ()
void WaitNonVblank ()
int RegisterVblankHandler (int startend, int priority, int(*handler)(void *), void *arg)
int ReleaseVblankHandler (int startend, int(*handler)(void *))
Detailed Description
Vertical blank interrupt routines.
Definition in file vblank.h.
Macro Definition Documentation
I_RegisterVblankHandler
#define I_RegisterVblankHandler DECLARE_IMPORT(8, RegisterVblankHandler)
Definition at line 37 of file vblank.h.
I_ReleaseVblankHandler
#define I_ReleaseVblankHandler DECLARE_IMPORT(9, ReleaseVblankHandler)
Definition at line 38 of file vblank.h.
I_WaitNonVblank
#define I_WaitNonVblank DECLARE_IMPORT(7, WaitNonVblank)
Definition at line 36 of file vblank.h.
I_WaitVblank
#define I_WaitVblank DECLARE_IMPORT(6, WaitVblank)
Definition at line 35 of file vblank.h.
I_WaitVblankEnd
#define I_WaitVblankEnd DECLARE_IMPORT(5, WaitVblankEnd)
Definition at line 34 of file vblank.h.
I_WaitVblankStart
#define I_WaitVblankStart DECLARE_IMPORT(4, WaitVblankStart)
Definition at line 33 of file vblank.h.
vblank_IMPORTS_end
#define vblank_IMPORTS_end END_IMPORT_TABLE
Definition at line 31 of file vblank.h.
vblank_IMPORTS_start
#define vblank_IMPORTS_start DECLARE_IMPORT_TABLE(vblank, 1, 1)
Definition at line 30 of file vblank.h.
Function Documentation
RegisterVblankHandler()
int RegisterVblankHandler (int startend, int priority, int(*)(void *) handler, void * arg)
Referenced by padInit().
ReleaseVblankHandler()
int ReleaseVblankHandler (int startend, int(*)(void *) handler)
Referenced by padEnd().
WaitNonVblank()
void WaitNonVblank ()
WaitVblank()
void WaitVblank ()
WaitVblankEnd()
void WaitVblankEnd ()
WaitVblankStart()
void WaitVblankStart ()
Referenced by MainThread().