ps2sdk: iop/sound/libsd/src/voice.c File Reference
voice.c File Reference
#include "types.h"
#include "irx.h"
#include "sifman.h"
#include "freesd.h"
#include "spu2regs.h"
Functions
void SetDmaWrite (s32 chan)
void SetDmaRead (s32 chan)
void DmaStop (u32 core)
s32 VoiceTransDma (s16 chan, u16 mode, u8 *iop_addr, u32 *spu_addr, u32 size)
s32 VoiceTrans_Write_IOMode (u32 iopaddr, u32 spu_addr, s32 size, s16 chan)
int sceSdVoiceTrans (s16 chan, u16 mode, u8 *iopaddr, u32 *spuaddr, u32 size)
u32 sceSdVoiceTransStatus (s16 chan, s16 flag)
Variables
volatile u16 VoiceTransComplete [2]
u32 VoiceTransStatus [2]
u32 VoiceTransIoMode [2]
IntrData TransIntrData [2]
Detailed Description
Part of the IOP Sound Driver
Definition in file voice.c.
Function Documentation
DmaStop()
void DmaStop (u32 core)
Definition at line 589 of file spu2.c.
 {
         u32 retval;
         core &= 1;
         if(*U16_REGISTER(0x1B0 + (core * 1024)) == 0)
                 retval = 0;
         else
                 retval = *SD_DMA_ADDR(core);
         *SD_DMA_CHCR(core) &= ~SD_DMA_START;
         *U16_REGISTER(0x1B0 + (core * 1024)) = 0;
         retval = (BlockTransBuff[core] << 24) | (retval & 0xFFFFFF);
         return retval;
 }
References BlockTransBuff, SD_DMA_ADDR, SD_DMA_CHCR, SD_DMA_START, and U16_REGISTER.
Referenced by sceSdBlockTrans(), and sceSdQuit().
sceSdVoiceTrans()
int sceSdVoiceTrans (s16 chan, u16 mode, u8 * iopaddr, u32 * spuaddr, u32 size)
Definition at line 122 of file voice.c.
 {
         s32 res = size;
         chan &= 1;
         if(mode & SD_TRANS_MODE_IO)
                 VoiceTransIoMode[chan] = 1;
         else
                 VoiceTransIoMode[chan] = 0;
         if(VoiceTransIoMode[chan] == 0)
         {
                 res = VoiceTransDma(chan, mode & 3, iopaddr, spuaddr, size);
         }
         else
         {
                 if((mode & 3) == SD_TRANS_WRITE)
                 {
                         res = VoiceTrans_Write_IOMode( (u32)iopaddr, (u32)spuaddr, size, chan);
                 }
         }
         VoiceTransStatus[chan] = 0;
         return res;
 }
References SD_TRANS_MODE_IO, SD_TRANS_WRITE, VoiceTrans_Write_IOMode(), VoiceTransDma(), VoiceTransIoMode, and VoiceTransStatus.
Referenced by audsrv_load_adpcm(), fillbuf(), rpc_server(), and sceSdClearEffectWorkArea().
sceSdVoiceTransStatus()
u32 sceSdVoiceTransStatus (s16 chan, s16 flag)
Definition at line 150 of file voice.c.
 {
         chan &= 1;
         flag &= 1;
         if((VoiceTransIoMode[chan] == 1) || (VoiceTransStatus[chan] == 1))
                 return 1;
         if(flag)
         {
                 while(!VoiceTransComplete[chan]);
                 VoiceTransStatus[chan] = 1;
                 VoiceTransComplete[chan] = 0;
                 return 1;
         }
         else
         {
                 if(VoiceTransComplete[chan] == 0) return 0;
                 VoiceTransStatus[chan] = 1;
                 VoiceTransComplete[chan] = 0;
         }
         return 0;
 }
References VoiceTransComplete, VoiceTransIoMode, and VoiceTransStatus.
Referenced by audsrv_load_adpcm(), fillbuf(), rpc_server(), and sceSdClearEffectWorkArea().
SetDmaRead()
void SetDmaRead (s32 chan)
Definition at line 614 of file spu2.c.
 {
         volatile u32 *reg = U32_REGISTER(0x1014 + (chan << 10));
         *reg = (*reg & 0xF0FFFFFF) | 0x22000000;
 }
References U32_REGISTER.
Referenced by BlockTransRead(), and VoiceTransDma().
SetDmaWrite()
void SetDmaWrite (s32 chan)
Definition at line 608 of file spu2.c.
 {
         volatile u32 *reg = U32_REGISTER(0x1014 + (chan << 10));
         *reg = (*reg & 0xF0FFFFFF) | 0x20000000;
 }
References U32_REGISTER.
Referenced by BlockTransWrite(), BlockTransWriteFrom(), and VoiceTransDma().
VoiceTrans_Write_IOMode()
s32 VoiceTrans_Write_IOMode (u32 iopaddr, u32 spu_addr, s32 size, s16 chan)
Definition at line 71 of file voice.c.
 {
         volatile u16 *statx;
         if(*SD_CORE_ATTR(chan) & SD_DMA_IN_PROCESS)
                 return -1;
         if(*SD_DMA_CHCR(chan) & SD_DMA_START)
                 return -1;
         *SD_A_TSA_HI(chan) = (u16)spu_addr >> 17;
         *SD_A_TSA_LO(chan) = (u16)spu_addr >> 1;
         TransIntrData[chan].mode = chan;
         if(size)
         {
                 s32 loop, count;
                 volatile u16* iop_mem = (volatile u16 *) iopaddr;
                 while(size > 0)
                 {
                         if(size > 64)
                                 count = 64;
                         else
                                 count = size;
                         if(count > 0)
{
                                 for(loop = 0; loop < count; loop += 2)
                                         *SD_A_STD(chan) = *iop_mem++;
                         }
                         // Set Transfer mode to IO
                         *SD_CORE_ATTR(chan) = (*SD_CORE_ATTR(chan) & ~SD_CORE_DMA) | SD_DMA_IO;
                         statx = U16_REGISTER(0x344 + (chan << 10));
                         // Wait for transfer to complete;
                         while(*statx & SD_IO_IN_PROCESS);
                         size -= count;
                 }
         }
         // Reset DMA settings
         *SD_CORE_ATTR(chan) &= ~SD_CORE_DMA;
         return 0;
 }
References IntrData::mode, SD_A_STD, SD_A_TSA_HI, SD_A_TSA_LO, SD_CORE_ATTR, SD_CORE_DMA, SD_DMA_CHCR, SD_DMA_IN_PROCESS, SD_DMA_IO, SD_DMA_START, SD_IO_IN_PROCESS, TransIntrData, and U16_REGISTER.
Referenced by sceSdVoiceTrans().
VoiceTransDma()
s32 VoiceTransDma (s16 chan, u16 mode, u8 * iop_addr, u32 * spu_addr, u32 size)
Definition at line 29 of file voice.c.
 {
         u32 direction;
         if(*SD_CORE_ATTR(chan) & SD_DMA_IN_PROCESS)
                 return -1;
         if(*SD_DMA_CHCR(chan) & SD_DMA_START)
                 return -1;
         *SD_A_TSA_HI(chan) = (u32)spu_addr >> 17;
         *SD_A_TSA_LO(chan) = (u32)spu_addr >> 1;
         if(mode == SD_TRANS_WRITE)
         {
                 TransIntrData[chan].mode = chan;
                 direction = SD_DMA_DIR_IOP2SPU;
                 *SD_CORE_ATTR(chan) = (*SD_CORE_ATTR(chan) & ~SD_CORE_DMA) | SD_DMA_WRITE;
                 SetDmaWrite(chan);
         }
         else
         {
                 if(mode == SD_TRANS_READ)
                 {
                         TransIntrData[chan].mode = (chan << 2) | 0x200;
                         direction = SD_DMA_DIR_SPU2IOP;
                         *SD_CORE_ATTR(chan) = (*SD_CORE_ATTR(chan) & ~SD_CORE_DMA) | SD_DMA_READ;
                         SetDmaRead(chan);
                 }
                 else
                 {
                         return -1;
                 }
         }
         *SD_DMA_ADDR(chan)      = (u32)iop_addr;
         *SD_DMA_MSIZE(chan) = (((size+63)/64) << 16) | 0x10;
         *SD_DMA_CHCR(chan)      = SD_DMA_CS | SD_DMA_START | direction;
         return size;
 }
References IntrData::mode, SD_A_TSA_HI, SD_A_TSA_LO, SD_CORE_ATTR, SD_CORE_DMA, SD_DMA_ADDR, SD_DMA_CHCR, SD_DMA_CS, SD_DMA_DIR_IOP2SPU, SD_DMA_DIR_SPU2IOP, SD_DMA_IN_PROCESS, SD_DMA_MSIZE, SD_DMA_READ, SD_DMA_START, SD_DMA_WRITE, SD_TRANS_READ, SD_TRANS_WRITE, SetDmaRead(), SetDmaWrite(), and TransIntrData.
Referenced by sceSdVoiceTrans().
Variable Documentation
TransIntrData
IntrData TransIntrData[2] extern
Definition at line 44 of file spu2.c.
Referenced by RegisterInterrupts(), Reset(), sceSdBlockTrans(), sceSdSetTransIntrHandler(), VoiceTrans_Write_IOMode(), and VoiceTransDma().
VoiceTransComplete
volatile u16 VoiceTransComplete[2]
Definition at line 20 of file voice.c.
Referenced by RegisterInterrupts(), sceSdVoiceTransStatus(), and TransInterrupt().
VoiceTransIoMode
u32 VoiceTransIoMode[2]
Definition at line 22 of file voice.c.
Referenced by Reset(), ResetAll(), sceSdClearEffectWorkArea(), sceSdVoiceTrans(), and sceSdVoiceTransStatus().
VoiceTransStatus
u32 VoiceTransStatus[2]
Definition at line 21 of file voice.c.
Referenced by Reset(), sceSdVoiceTrans(), and sceSdVoiceTransStatus().