ps2sdk: iop/debug/sior/src/xprintf.h File Reference
xprintf.h File Reference
#include <stdarg.h>
Macros
#define F_vxprintf
#define NOFLOATINGPOINT /* won't compile without it */
#define F___sout
#define F_vsnprintf
Functions
int vsnprintf (char *buf, size_t n, const char *fmt, va_list ap)
Macro Definition Documentation
F___sout
#define F___sout
Definition at line 17 of file xprintf.h.
F_vsnprintf
#define F_vsnprintf
Definition at line 22 of file xprintf.h.
F_vxprintf
#define F_vxprintf
Definition at line 15 of file xprintf.h.
NOFLOATINGPOINT
#define NOFLOATINGPOINT /* won't compile without it */
Definition at line 16 of file xprintf.h.
Function Documentation
vsnprintf()
int vsnprintf (char * buf, size_t n, const char * fmt, va_list ap)
Definition at line 716 of file xprintf.c.
{
   struct s_strargument arg;
   arg.next = buf;
   arg.last = &buf[n-1];
   *buf = 0;
   return vxprintf(__sout,&arg,fmt,ap);
 }
References __sout(), arg, and vxprintf().
Referenced by sio_vprintf().