ps2sdk: iop/kernel/include/xsio2man.h File Reference
xsio2man.h File Reference
#include <sio2man.h>
Macros
#define xsio2man_IMPORTS_start DECLARE_IMPORT_TABLE(sio2man, 1, 2)
#define xsio2man_IMPORTS_end END_IMPORT_TABLE
#define I_sio2_transfer_reset DECLARE_IMPORT(26, sio2_transfer_reset)
#define I_sio2_mtap_transfer_init DECLARE_IMPORT(48, sio2_mtap_transfer_init)
#define I_sio2_transfer2 DECLARE_IMPORT(49, sio2_transfer2)
#define I_sio2_transfer_reset2 DECLARE_IMPORT(50, sio2_transfer_reset2)
#define I_sio2_mtap_change_slot_set DECLARE_IMPORT(51, sio2_mtap_change_slot_set)
#define I_sio2_mtap_get_slot_max_set DECLARE_IMPORT(52, sio2_mtap_get_slot_max_set)
#define I_sio2_mtap_get_slot_max2_set DECLARE_IMPORT(53, sio2_mtap_get_slot_max2_set)
#define I_sio2_mtap_update_slots_set DECLARE_IMPORT(54, sio2_mtap_update_slots_set)
#define I_sio2_mtap_change_slot DECLARE_IMPORT(55, sio2_mtap_change_slot)
#define I_sio2_mtap_get_slot_max DECLARE_IMPORT(56, sio2_mtap_get_slot_max)
#define I_sio2_mtap_get_slot_max2 DECLARE_IMPORT(57, sio2_mtap_get_slot_max2)
#define I_sio2_mtap_update_slots DECLARE_IMPORT(58, sio2_mtap_update_slots)
Typedefs
typedef int(* sio2_mtap_change_slot_cb_t) (s32 *status)
typedef int(* sio2_mtap_get_slot_max_cb_t) (int port)
typedef int(* sio2_mtap_get_slot_max2_cb_t) (int port)
typedef void(* sio2_mtap_update_slots_t) (void)
Functions
void sio2_transfer_reset (void)
void sio2_mtap_transfer_init (void)
int sio2_transfer2 (sio2_transfer_data_t *td)
void sio2_transfer_reset2 (void)
void sio2_mtap_change_slot_set (sio2_mtap_change_slot_cb_t cb)
void sio2_mtap_get_slot_max_set (sio2_mtap_get_slot_max_cb_t cb)
void sio2_mtap_get_slot_max2_set (sio2_mtap_get_slot_max2_cb_t cb)
void sio2_mtap_update_slots_set (sio2_mtap_update_slots_t cb)
int sio2_mtap_change_slot (s32 *arg)
int sio2_mtap_get_slot_max (int port)
int sio2_mtap_get_slot_max2 (int port)
void sio2_mtap_update_slots (void)
Detailed Description
rom0:XSIO2MAN module definitions
Definition in file xsio2man.h.
Macro Definition Documentation
I_sio2_mtap_change_slot
#define I_sio2_mtap_change_slot DECLARE_IMPORT(55, sio2_mtap_change_slot)
Definition at line 51 of file xsio2man.h.
I_sio2_mtap_change_slot_set
#define I_sio2_mtap_change_slot_set DECLARE_IMPORT(51, sio2_mtap_change_slot_set)
Definition at line 47 of file xsio2man.h.
I_sio2_mtap_get_slot_max
#define I_sio2_mtap_get_slot_max DECLARE_IMPORT(56, sio2_mtap_get_slot_max)
Definition at line 52 of file xsio2man.h.
I_sio2_mtap_get_slot_max2
#define I_sio2_mtap_get_slot_max2 DECLARE_IMPORT(57, sio2_mtap_get_slot_max2)
Definition at line 53 of file xsio2man.h.
I_sio2_mtap_get_slot_max2_set
#define I_sio2_mtap_get_slot_max2_set DECLARE_IMPORT(53, sio2_mtap_get_slot_max2_set)
Definition at line 49 of file xsio2man.h.
I_sio2_mtap_get_slot_max_set
#define I_sio2_mtap_get_slot_max_set DECLARE_IMPORT(52, sio2_mtap_get_slot_max_set)
Definition at line 48 of file xsio2man.h.
I_sio2_mtap_transfer_init
#define I_sio2_mtap_transfer_init DECLARE_IMPORT(48, sio2_mtap_transfer_init)
Definition at line 44 of file xsio2man.h.
I_sio2_mtap_update_slots
#define I_sio2_mtap_update_slots DECLARE_IMPORT(58, sio2_mtap_update_slots)
Definition at line 54 of file xsio2man.h.
I_sio2_mtap_update_slots_set
#define I_sio2_mtap_update_slots_set DECLARE_IMPORT(54, sio2_mtap_update_slots_set)
Definition at line 50 of file xsio2man.h.
I_sio2_transfer2
#define I_sio2_transfer2 DECLARE_IMPORT(49, sio2_transfer2)
Definition at line 45 of file xsio2man.h.
I_sio2_transfer_reset
#define I_sio2_transfer_reset DECLARE_IMPORT(26, sio2_transfer_reset)
Definition at line 43 of file xsio2man.h.
I_sio2_transfer_reset2
#define I_sio2_transfer_reset2 DECLARE_IMPORT(50, sio2_transfer_reset2)
Definition at line 46 of file xsio2man.h.
xsio2man_IMPORTS_end
#define xsio2man_IMPORTS_end END_IMPORT_TABLE
Definition at line 40 of file xsio2man.h.
xsio2man_IMPORTS_start
#define xsio2man_IMPORTS_start DECLARE_IMPORT_TABLE(sio2man, 1, 2)
Definition at line 39 of file xsio2man.h.
Typedef Documentation
sio2_mtap_change_slot_cb_t
typedef int(* sio2_mtap_change_slot_cb_t) (s32 *status)
Definition at line 21 of file xsio2man.h.
sio2_mtap_get_slot_max2_cb_t
typedef int(* sio2_mtap_get_slot_max2_cb_t) (int port)
Definition at line 23 of file xsio2man.h.
sio2_mtap_get_slot_max_cb_t
typedef int(* sio2_mtap_get_slot_max_cb_t) (int port)
Definition at line 22 of file xsio2man.h.
sio2_mtap_update_slots_t
typedef void(* sio2_mtap_update_slots_t) (void)
Definition at line 24 of file xsio2man.h.
Function Documentation
sio2_mtap_change_slot()
int sio2_mtap_change_slot (s32 * arg)
Definition at line 396 of file sio2man.c.
 {
         int i, ret = 1;
         if (mtap_change_slot_cb)
                 return mtap_change_slot_cb(status);
         for (i = 0; i < 4; i++, status++) {
                 if ((*status + 1) < 2)
                         status[4] = 1;
                 else {
                         status[4] = 0;
                         ret = 0;
                 }
         }
         return ret;
 }
References mtap_change_slot_cb, and status.
Referenced by mtapChangeSlot(), and pdCheckConnection().
sio2_mtap_change_slot_set()
void sio2_mtap_change_slot_set (sio2_mtap_change_slot_cb_t cb)
Definition at line 437 of file sio2man.c.
 { mtap_change_slot_cb = cb; }
References mtap_change_slot_cb.
Referenced by _start(), and shutdown().
sio2_mtap_get_slot_max()
int sio2_mtap_get_slot_max (int port)
Definition at line 415 of file sio2man.c.
 {
         if (mtap_get_slot_max_cb)
                 return mtap_get_slot_max_cb(port);
         return 1;
 }
References mtap_get_slot_max_cb.
Referenced by padGetSlotMax().
sio2_mtap_get_slot_max2()
int sio2_mtap_get_slot_max2 (int port)
Definition at line 423 of file sio2man.c.
 {
         if (mtap_get_slot_max2_cb)
                 return mtap_get_slot_max2_cb(port);
         return 1;
 }
References mtap_get_slot_max2_cb.
sio2_mtap_get_slot_max2_set()
void sio2_mtap_get_slot_max2_set (sio2_mtap_get_slot_max2_cb_t cb)
Definition at line 439 of file sio2man.c.
 { mtap_get_slot_max2_cb = cb; }
References mtap_get_slot_max2_cb.
Referenced by _start(), and shutdown().
sio2_mtap_get_slot_max_set()
void sio2_mtap_get_slot_max_set (sio2_mtap_get_slot_max_cb_t cb)
Definition at line 438 of file sio2man.c.
 { mtap_get_slot_max_cb = cb; }
References mtap_get_slot_max_cb.
Referenced by _start(), and shutdown().
sio2_mtap_transfer_init()
void sio2_mtap_transfer_init (void)
Definition at line 355 of file sio2man.c.
 {
         SetEventFlag(event_flag, EF_MTAP_TRANSFER_INIT);
         WaitEventFlag(event_flag, EF_MTAP_TRANSFER_READY, 0, NULL);
         ClearEventFlag(event_flag, ~EF_MTAP_TRANSFER_READY);
 }
References ClearEventFlag(), EF_MTAP_TRANSFER_INIT, EF_MTAP_TRANSFER_READY, event_flag, NULL, SetEventFlag(), and WaitEventFlag().
Referenced by get_slot_number(), and mtapChangeSlot().
sio2_mtap_update_slots()
void sio2_mtap_update_slots (void)
Definition at line 431 of file sio2man.c.
 {
         if (mtap_update_slots_cb)
                 mtap_update_slots_cb();
 }
References mtap_update_slots_cb.
Referenced by MainThread().
sio2_mtap_update_slots_set()
void sio2_mtap_update_slots_set (sio2_mtap_update_slots_t cb)
Definition at line 440 of file sio2man.c.
 { mtap_update_slots_cb = cb; }
References mtap_update_slots_cb.
Referenced by _start(), and shutdown().
sio2_transfer2()
int sio2_transfer2 (sio2_transfer_data_t * td)
Referenced by change_slot(), get_slot_number(), padTransfer(), and SlotCheckConnection().
sio2_transfer_reset()
void sio2_transfer_reset (void)
Definition at line 391 of file sio2man.c.
 {
         SetEventFlag(event_flag, EF_TRANSFER_RESET);
 }
References EF_TRANSFER_RESET, event_flag, and SetEventFlag().
Referenced by RmExecute().
sio2_transfer_reset2()
void sio2_transfer_reset2 (void)
Referenced by get_slot_number(), mtapChangeSlot(), pdCheckConnection(), and pdTransfer().